### ISSUE TITLE
istiod reported a metrics error

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#31417]
**Bug description**
Query istiod with`prometheus` or `grafana` and find two istiod, then there is only one istiod in the cluster `istio-system`, what caused it? the number of proxies is also incorrect.

i think return an istiod is correct.

```shell
[root@mesh-dev-10-20-1-180 ~]# kubectl get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-767c5487d6-cf7fp                1/1     Running   0          5h8m
istio-egressgateway-69f9b49569-87dkh    1/1     Running   0          18h
istio-ingressgateway-7cd5b9b4d4-wnjq6   1/1     Running   0          18h
istiocoredns-757778695c-l94mm           2/2     Running   0          18h
istiod-iop-1-8-1-58f6d6f46-dklrn        1/1     Running   0          18h
prometheus-fbdccfbfd-2ltcx              2/2     Running   0          18h
```
<img width="1905" alt="WeChat40f706907e0a45082fdc55ec77ac0ae6" src="https://user-images.githubusercontent.com/40875627/110903713-d3d58c80-8342-11eb-80a1-f26794e3c71e.png">

---
About memory monitoring, i set the limits and request for istiod, but look at prometheus, i found that the memory has exceeded my settings
```yaml
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 50Mi
```
![截屏2021-03-12 下午3 15 50](https://user-images.githubusercontent.com/40875627/110905779-fe751480-8345-11eb-8077-0c2162c62b51.png)

**Comment by bianpengyuan** [comment]
I suspect you probably have some recording rule to add pod label to scraped metrics? the short version of `istio_build` is scraped and stored at prometheus, then a recording rule create a new time series from it with extra pod labels.

**Comment by xichengliudui** [comment]
like what recording rule @bianpengyuan

**Comment by tanjunchen** [comment]
@bianpengyuan     @xichengliudui 
Look at whether there are pilot and kubernetes-pods in the prometheus job. Prometheus may have duplicate crawls.

**Comment by bianpengyuan** [comment]
Ah yeah, indeed. two time series are from different jobs.
