### ISSUE TITLE
Facing issue while using Istio SSL gateway offloading 

### ISSUE THREAD

**Issue by Himansh-ilink** [istio/istio#31423]
Hello,
We are using Istio 1.5.9 in our environment, we have configured SSL offloading in the Istio gateway. We are getting errors when we do curl on our Ip Address. Below is the command and error.

**Command:-** 
    curl -kI https://107.89.72.89/ -H host:testdomain.example.com
**Error:-**
   curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 102.89.72.89:443
   Here is the virtualservice and gateway.

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-nginx
  namespace: istio-system
spec:
  gateways:
  - test-gateway
  hosts:
  - test.example.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: svc-nginx-1-a.default.svc.cluster.local
        port:
          number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'test.example.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      httpsRedirect: false
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/test.example.com.key
      serverCertificate: /etc/istio/ingressgateway-certs/test.example.com.crt
-------
Can someone please help me with this issue?

Thank you.

**Comment by howardjohn** [comment]
This is working as expected, please see https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/. `hosts: 'test.example.com'` means do an SNI match on `'test.example.com'`. You are not setting that in the SNI because you are sending to the IP. You need to get a real domain or use --resolve. Thanks!
