### ISSUE TITLE
AWS load-balancer with TLS ingress-gateway

### ISSUE THREAD

**Issue by a8j8i8t8** [istio/istio#31421]
What I'm trying to do is call my app via AWS LB. I tried all three ALB, NLB and ELB. But I'm not able to achieve so. Is this not valid usecase?
AWS LB is listening on 443 and forwarding the TLS/HTTPS request to ingressgateway on port 30443.

My deployment, service and virtual-service are in namespace-1.
```
spec:
  gateways:
    - istio-system/my-gateway
  hosts:
    - links.dev.domain.us
  http:
    - route:
        - destination:
            host: httpbin.namespace-1.svc.cluster.local
            port:
              number: 8000
```
My gateway and secrets are in istio-system namespace
```
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.dev.domain.us'
      port:
        name: http-gw
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*.dev.domain.us'
      port:
        name: https-gw
        number: 443
        protocol: HTTPS
      tls:
        credentialName: links-credential
        mode: SIMPLE
```

It works as expected when I hit the service directly as below.
```
# curl -HHost:links.dev.domain.us --resolve "links.dev.domain.us:30443:172.23.8.175" "https://links.dev.domain.us:30443/status/418" -k

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```

But when I try to access the same via ALB like `curl -XGET https://links.dev.domain.us/status/418 -v --resolve links.dev.domain.us:443:3.213.184.218` I'm getting `502 Bad Gateway` where `3.213.184.218` is IP of ALB.

And for classic loadbalancer (ELB) I'm getting 408 REQUEST_TIMEOUT.

Following is what I see in ingressgateway logs.
```
2021-03-12T11:28:44.275090Z debug envoy conn_handler [C961] new connection
2021-03-12T11:28:44.275145Z debug envoy http [C961] new stream
2021-03-12T11:28:44.275166Z debug envoy http [C961][S6781970186881343100] Sending local reply with details http1.codec_error
2021-03-12T11:28:44.275204Z debug envoy http [C961][S6781970186881343100] closing connection due to connection close header
2021-03-12T11:28:44.275224Z debug envoy http [C961][S6781970186881343100] encoding headers via codec (end_stream=false):
':status', '400'
'content-length', '11'
'content-type', 'text/plain'
'date', 'Fri, 12 Mar 2021 11:28:44 GMT'
'server', 'envoy'
'connection', 'close'

2021-03-12T11:28:44.275251Z debug envoy http [C961][S6781970186881343100] doEndStream() resetting stream
2021-03-12T11:28:44.275256Z debug envoy http [C961][S6781970186881343100] stream reset
2021-03-12T11:28:44.275265Z debug envoy connection [C961] closing data_to_write=156 type=2
2021-03-12T11:28:44.275277Z debug envoy connection [C961] setting delayed close timer with timeout 1000 ms
2021-03-12T11:28:44.275291Z debug envoy http [C961] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
2021-03-12T11:28:44.275300Z debug envoy connection [C961] closing data_to_write=156 type=2
2021-03-12T11:28:44.275303Z debug envoy connection [C961] remote close
2021-03-12T11:28:44.275306Z debug envoy connection [C961] closing socket: 0
2021-03-12T11:28:44.275352Z debug envoy conn_handler [C961] adding to cleanup list
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio version - 1.9.1
K8S version - 1.19.8

**How was Istio installed?**
With Istio operator.

**Comment by howardjohn** [comment]
Looks like its getting invalid HTTP data. maybe you are sending TLS connection to the plaintext port (80)?

**Comment by a8j8i8t8** [comment]
Something is not correct. Following is ingressgw service spec.
```
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
      nodePort: 31170
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30443
    - name: tcp-istiod
      protocol: TCP
      port: 15012
      targetPort: 15012
      nodePort: 31551
    - name: tls
      protocol: TCP
      port: 15443
      targetPort: 15443
      nodePort: 30666
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  clusterIP: 100.71.120.64
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
```

I did try everything in below but all unsuccessful :-(

1. ALB
-  listening on HTTP port 80 and forwarding it to HTTP port 30080 - I got too many redirects 
- listening on HTTP port 80 and forwarding it to HTTPS port 30443 - I got 502
- listening on HTTPS port 443 and forwarding it to HTTPS port 30443 - I got 502
2. NLB
- listening on TCP port 80 and forwarding it to TCP port 30080 - I got too many redirects 
- listening on TLS port 443 and forwarding it to TLS port 30443 - I got curl: (55) SSL_write() returned SYSCALL, errno = 32
3. CLB
-  listening on HTTP port 80 and forwarding it to HTTP port 30080 - I got too many redirects 
- listening on HTTP port 80 and forwarding it to HTTPS port 30443 - I got timeout 408
- listening on HTTPS port 443 and forwarding it to HTTPS port 30443 - I got timeout 408

Any help with this will be appreciated.
Thanks.

**Comment by a8j8i8t8** [comment]
Ok I've another update here. If I change my gateway to below then it's working with ALB.
```
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http-gw
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*'
      port:
        name: https-gw
        number: 443
        protocol: HTTPS
      tls:
        credentialName: links-credential
        mode: SIMPLE
```
Any idea why?

**Comment by howardjohn** [comment]
Is the ALB terminating TLS? If so, it will re-initiate TLS but without SNI most likely, which won't match the hosts. I am not an expert in AWS lb but that is the most likely case

**Comment by a8j8i8t8** [comment]
@howardjohn that's exactly the reason. If I don't terminate TLS at AWS NLB then it's working. Thanks.

**Comment by a8j8i8t8** [comment]
One more thing, after above is working fine, if I create these three filters https://gist.github.com/a8j8i8t8/36d6b4069ae2a23a93acc6e38d3732d1 - I'm getting error like below.
```
curl -HHost:links.dev.domain.us --resolve "links.dev.domain.us:30443:172.23.8.43" "https://links.dev.domain.us:30443/anything" -kvL
* Added links.dev.domain.us:30443:172.23.8.43 to DNS cache
* Hostname links.dev.domain.us was found in DNS cache
*   Trying 172.23.8.43...
* TCP_NODELAY set
* Connected to links.dev.domain.us (172.23.8.43) port 30443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to links.dev.domain.us:30443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to links.dev.domain.us:30443
```

As soon as I delete those filters, it starts working again. I'm trying to enable `x-forwarded-for` as mentioned in one of Istio blogs - https://istio.io/latest/blog/2020/show-source-ip/

**Comment by rahul6941** [comment]
@a8j8i8t8 we are facing same issue . Did you figure how its working with ALB not NLB . We dont terminate TLS at AWS ALB  then also it's not working. We have to configure ALB

**Comment by anteliano** [comment]
ALB has the annotation alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.preserve_host_header.enabled=true
to make it preserve the Host: header when communicating with the targets, without this, depending on your istio setup you would get 502s.
