### ISSUE TITLE
istio/tools: package golang.org/x/tools/go/loader is deprecated

### ISSUE THREAD

**Issue by ericvn** [istio/istio#31436]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

istio tools uses package golang.org/x/tools/go/loader. Update to use package golang.org/x/tools/go/pages.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ericvn** [comment]
Comment to remove stale.

**Comment by zhlsunshine** [comment]
Hi @ericvn, shall we move this issue to 1.12?
