### ISSUE TITLE
Workload evidence when using RBAC policy

### ISSUE THREAD

**Issue by jaygridley** [istio/istio#31452]
**Describe the feature request**

Hello, when using RBAC with Istio and some workload is denied by policies, e.g. AuthorizationPolicy, Istio returns 403 - RBAC: access denied. It would be great to have s possibility to configure Istio/Envoy to return 404 Not Found instead to “hide” workload existence.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by wzshiming** [comment]
Do you want to customize the rejection code and information of the access denied?
Is it used to isolate different tenants so that they are invisible to each other?

**Comment by wzshiming** [comment]
I took a look, xDS does not have this related configuration, and now it may be necessary to support this feature in Envoy first.

**Comment by jaygridley** [comment]
> Do you want to customize the rejection code and information of the access denied? Is it used to isolate different tenants so that they are invisible to each other?

Yes, customization of the rejection code and information is exactly what I am looking for.

Our use-case here is that we want to hide the existence of the workload from the public network (internet) access by presenting 404, but for internal access (from the private network, we are fine with 403.

**Comment by jaygridley** [comment]
> I took a look, xDS does not have this related configuration, and it may be necessary to support this feature in Envoy first.

Would you be able to help out with raising it? I am not familiar with Envoy internals and I do not know what to put into the feature request.

**Comment by wzshiming** [comment]
Sure, I will take time to follow up on this.

**Comment by wzshiming** [comment]
https://istio.io/latest/docs/reference/config/networking/sidecar/#Sidecar
https://github.com/istio/istio/blob/e8c442ea21680a397406fa8bf92aee7f34d0c121/pilot/pkg/networking/core/v1alpha3/httproute.go#L535-L591

Sidecar.OutboundTrafficPolicy, whether it meets your needs, based on namespace isolation, unregistered routes will return 504

**Comment by yangminzhu** [comment]
Thanks for opening the issue! I think the current workaround is probably to use EnvoyFilter to configure the https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply (see more details in the Envoy issue).

But I also feel it might still worth to add first-class support in the Envoy RBAC filter directly and then expose it in Istio, One benefit is it could potentially give more flexibility, for example, different response for different RBAC rules, embed policy name in response for debugging purpose. Just commenting the idea here for some more comments from the community.
