### ISSUE TITLE
sidecar-to-sidecar communication should be over HTTP2 by default, instead of requiring a user to configure `DestinationRule` explicitly

### ISSUE THREAD

**Issue by yskopets** [istio/istio#31454]
**Context**

* Consider `bookinfo` example:
  * expose `productpage` app externally via `istio-ingressgateway` (use `Gateway` and `VirtualService` resources for that)
  * create some load on the `istio-ingressgateway` (`/productpage` endpoint), e.g. 1000 concurrent connections
  * it's unexpected to see that the link between `Istio Ingress Gateway` and `Isitio Sidecar` (`productpage`) doesn't take advantage of HTTP2 and instead opens the same 1000 outgoing connections

**Describe the feature request**

* Istio should leverage HTTP2 on sidecar-to-sidecar connections by default (it must be safe to do anyway if the link is Istio mTLS)
* I see a `TODO` in the [source code](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L520-L525) on the same subject:
  ```go
  // TODO (mjog)
  // Upgrade if tls.GetMode() == networking.TLSSettings_ISTIO_MUTUAL
  override := networking.ConnectionPoolSettings_HTTPSettings_DEFAULT
  if connectionPool != nil && connectionPool.Http != nil {
      override = connectionPool.Http.H2UpgradePolicy
  }  
  ```
* @mandarjog was it simply forgotten over time or is there a blocker ? 

**Describe alternatives you've considered**

* Istio gives users an option to enable `HTTP/1.X` to `HTTP2` upgrade explicitly via `DestinationRule` ([ConnectionPoolSettings.HTTPSettings.h2UpgradePolicy](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings))
* However, I haven't found documentation stressing importance of `h2UpgradePolicy`
* And, as a user, I expect such behaviour to be on by default

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by mandarjog** [comment]
The issue was how do we ensure that there is a h2 capable sidecar on the other side. tLS_mutual is a good indication but not conclusive. I think we can now use the auto mtls related annotation and then turn it on by default.

**Comment by mandarjog** [comment]
There is additional complication due to use-Downstream protocol. We do not want the last mile to be upgraded by the local inbound cluster by using use-downstream protocol

**Comment by su225** [comment]
@yskopets - Why not set it in mesh config? https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-H2UpgradePolicy

@mandarjog - any caveats on setting it in mesh config?

**Comment by mandarjog** [comment]
Same caveats as described above. If you set it mesh wide, you have to be always sure that sidecars only communicate with other sidecars. If you do not have any destination opting out of a sidecar, this works fine. But if you have uninjected destinations in the mesh then it will fail.

We need to use the automtls style annotation for surety that there is a sidecar on the other side. And also remove use_downstream_protocol unless we can continue to restrict use for named ports only.

**Comment by howardjohn** [comment]
cc @lambdai
