### ISSUE TITLE
eastwestgateway external ip updated, but sidecar endpoint not update (1.8)

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#31453]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

when eastwestgateway external ip updated, sidecar endpoint should update.

**Steps to reproduce the bug**

1. install primary cluster (set ext ip for gateway)
2. install remote cluster(not set external ip for gateway)

```
# primary cluster endpints
$ istioctl proxy-config endpoint productpage-v1-598558b447-jpt4v.cftest --cluster 'outbound|9080|v3|reviews.cftest.svc.cluster.local'
ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
192.168.81.12:9080     HEALTHY     OK                outbound|9080|v3|reviews.cftest.svc.cluster.local
192.168.94.9:9080      HEALTHY     OK                outbound|9080|v3|reviews.cftest.svc.cluster.local
```
is error

3. set external ip for gateway, endpoint not update
4. delete pod then rebuild

```
$ istioctl proxy-config endpoint productpage-v1-598558b447-cv4n5.cftest --cluster 'outbound|9080|v3|reviews.cftest.svc.cluster.local'
ENDPOINT                STATUS      OUTLIER CHECK     CLUSTER
172.19.35.134:15443     HEALTHY     OK                outbound|9080|v3|reviews.cftest.svc.cluster.local
192.168.81.13:9080      HEALTHY     OK                outbound|9080|v3|reviews.cftest.svc.cluster.local
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.8.3
data plane version: none


$ kubectl version --short
Client Version: v1.19.6
Server Version: v1.19.6
```

**How was Istio installed?**
1.8.3

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @stevenctl

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/30070 should be the fix

**Comment by stevenctl** [comment]
Ah, thanks @hzxuzhonghu.. didn't realize that was so recent. I'll try to pull it into 1.8 as well.
