### ISSUE TITLE
MultiCluster communications fail randomly after 30 minutes

### ISSUE THREAD

**Issue by ironpeak** [istio/istio#31464]
**Bug description**

Installed Istio 1.9.1 on 3 clusters using the multi-primary on differnt networks [docs](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/), after which communications between cluster weren't working when we did tried to [verify the installation](https://istio.io/latest/docs/setup/install/multicluster/verify/). The sleep pod always hit the helloworld service in the same cluster.

But we managed to get that working using this [workaround](https://github.com/istio/istio/issues/29359#issuecomment-739258089).

But once a service has been running for a while (~30 min) communications suddenly stops working with error:

`503, upstream connect error or disconnect/reset before headers. reset reason: connection termination`

The failure doesn't always affect every pod, some are able to continue communicating. The ones that do start failing will continue to fail consistantly for ~30 min before correcting at which point some of the previously working pods will have started to fail.

In the istiod logs I can see:

Failed to authenticate client from 10.2.75.98:53492: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "clusterx-istio": the service account authentication returns an error: [invalid bearer token, Token has been invalidated, unknown]

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Expected the communications between clusters to work consistently.

**Steps to reproduce the bug**

- Setup EKS clusters
- [Install istio on both clusters](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/)
- Use [workaround](https://github.com/istio/istio/issues/29359#issuecomment-739258089) because AWS uses hostnames
- [Verify install](https://istio.io/latest/docs/setup/install/multicluster/verify/)
- Setup a pods that pings the other clusters every 30 seconds
- Wait ~30 minutes

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio:

~~~
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (54 proxies)
~~~

Kubectl:
~~~
Server Version: v1.18.9-eks-d1db3c
~~~

**How was Istio installed?**

https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/

~~~yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:XXXXXXXXXXXX:certificate/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https

  values:
    global:
      meshID: production
      multiCluster:
        enabled: true
        clusterName: clusterx-istio
      network: clusterx

    pilot:
      autoscaleEnabled: true
      autoscaleMin: 3
      autoscaleMax: 5
      traceSampling: 100

    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        autoscaleMin: 3
        autoscaleMax: 5
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
spec:
  revision: ""
  profile: empty
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
          topology.istio.io/network: clusterx
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
            # traffic through this gateway should be routed inside the network
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: clusterx
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  values:
    global:
      meshID: production
      network: clusterx
      multiCluster:
        clusterName: clusterx-istio
~~~

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS (EKS, v1.18.9-eks-d1db3c)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
If you want to reproduce faster I suspect changing `--keepaliveMaxServerConnectionAge` to a lower time will trigger it faster. Its currently 30m which suspiciously lines up with times here. This means a pod will disconnect from istiod after 30mins.

It seems to figure out the root we need to understand why the token is invalid. A few possible options: k8s is not updating the token, the sidecar is sending a stale token despite k8s updating it, istiod is incorrectly validating it.

> The ones that do start failing will continue to fail consistantly for ~30 min before correcting at which point some of the previously working pods will have started to fail.

If we are failing to authentication (`Failed to authenticate client from ...`) I would expect it to immediately reconnect, not after 30 minutes, which is a bit odd..

**Comment by ironpeak** [comment]
You are right, they did make some successful request after they started failing,  but the pod never stabilized.

The pods were setup to ping the service in the remote cluster every 30 seconds.

Out of 3 pods, 2 had failures. The ones that did have failures did managed to intermittently make successful requests and then failed again within 30s-5m.

For the initial 30 minutes of the test, there were not failures.

**Comment by ironpeak** [comment]
We were using an nlb load balancer rather that an elb in AWS.

I haven't tested it for this multi-cluster configuration but it did fix some networking issue we had in standalone installations of istio.

We suspect it's because the nlb has an idle timeout for TCP traffic and terminates the connection silently.

**Comment by antonio-te** [comment]
@ironpeak, how did you fix this, if at all? Did you migrate to an ELB? Change the idle timeout in Istio?

**Comment by antonio-te** [comment]
I found the fix myself, and it was actually quite simple: I set `ISTIO_META_IDLE_TIMEOUT="300s"` in the environment of the east-west gateways. As I'm a Helm user, I accomplished this by setting `env,ISTIO_META_IDLE_TIMEOUT` in [the values file](https://artifacthub.io/packages/helm/istio-official/gateway/1.17.2?modal=values).

**Comment by eduardobaitello** [comment]
@antonio-te Do you know what explains why this parameter solved the problem?

We're having similar issues with eastwest-gateway with NLB, and I want to understand how this can help before testing.

**Comment by agurgel-te** [comment]
@eduardobaitello (e @drequena), me desculpe pela espera.

AWS NLBs have [a hard-coded TCP idle timeout of 350s](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout), and Istio's default timeout [is null](https://github.com/istio/istio/pull/13515/files#diff-c5e34bbbc28f05f1174272301d92b6cdaf376d11e4dd176f1cfd225bf701a0baR605). Since Istio's connections never time out, the NLBs cuts them off with an RST, hence "disconnect/reset before headers".

**Comment by eduardobaitello** [comment]
Hi @agurgel-te, thanks for the explanation.

We realized precisely this, and as soon as we defined `ISTIO_META_IDLE_TIMEOUT="300s"` the problem was solved 🙏🏻
