### ISSUE TITLE
Inbound metrics missing for ingress gateway 

### ISSUE THREAD

**Issue by ashleythomasv28** [istio/istio#31468]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Currently, ingress metrics are missing for ingress gateway (we don't have metrics with `reporter=destination`)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Inbound metrics present for ingress gateway 

**Steps to reproduce the bug**
Check metrics emitted by endpoint _<IP>:15090/stats/prometheus_. Metrics with tag `reporter=destination` will be missing. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
`istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0`

`kubectl version --short
Client Version: v1.18.3
Server Version: v1.18.4`

`helm version --short
v3.4.1+gc4e7485`

**How was Istio installed?**
Helm 

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ashleythomasv28** [comment]
Is this by design or a bug? Can we add some configuration to enable inbound metrics for ingress gateway?

**Comment by bianpengyuan** [comment]
Ingressgateway request metrics are reported as client metrics. Close as this works as expected. Thanks!

**Comment by ashleythomasv28** [comment]
@bianpengyuan  is this in roadmap to add these metrics. We will require these metrics to monitor if there is some issue and compare the inbound and outbound metrics.

**Comment by bianpengyuan** [comment]
> We will require these metrics to monitor if there is some issue and compare the inbound and outbound metrics.

What exactly do you want to monitor? All request go through ingress are tracked as outbound metrics at ingress proxy, and requests from ingress to applications are tracked as inbound metrics at application sidecar proxy.

**Comment by ashleythomasv28** [comment]
@bianpengyuan for requests which are dropped at ingress gateway due to some reasons like cluster not present or any other reason, having inbound metrics helps. With that we could see what % of requests actually go through ingress gateway and what gets dropped at it.

**Comment by bianpengyuan** [comment]
Any requests that are processed by ingress will be tracked with the inbound request metrics. There is no forwarding inside the ingress gateway (i.e. an inbound listener forward to an outbound listener). There is just one listener, and one filter chain deals with any ingress requests.
