### ISSUE TITLE
proxy response flags UO

### ISSUE THREAD

**Issue by rush24** [istio/istio#31466]
**Bug description**
Part of requests failed once injecting sidecar in our tcp service, the access log shows response_flags UO, and i never config any Destination Rule, may there was some default config triggers the circuit breaker or something. 

**Expected behavior**
Zero errors
**Steps to reproduce the bug**
May it's related to the qps. some grpc services are fine with sidecar.

**How was Istio installed?**
istio 1.3.6

**Comment by bianpengyuan** [comment]
1.3 was out of support more than a year ago: https://istio.io/latest/news/support/announcing-1.3-eol/ We could not help on this nor patch it if there is really a bug in that minor version. Please upgrade and see if the issue is gone. Thanks!
