### ISSUE TITLE
Enhance statusgen to report last sync time and statuses of more XDS types added (like NDS, ECDS etc)

### ISSUE THREAD

**Issue by su225** [istio/istio#31474]
**Describe the feature request**
Currently, statusgen only reports status of LDS, EDS, CDS and RDS. 

**Our use case** - Besides the status like SYNCED, STALE, NOT_SENT etc, we also want to report the last sync time. Plus, new features like NDS and ECDS were added and their status is not reported. 

**NOTE** - As a nice side-effect of this work, `istioctl proxy-status` can be enhanced to show NDS and ECDS sync statuses)

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by su225** [comment]
I would like to work on this. I already have prototype implementing some of these.

**Comment by howardjohn** [comment]
What is the use case for seeing the time?

**Comment by su225** [comment]
It is used for reporting purposes. We don't get to know that it has moved on to the next configuration change. There is a difference between `SYNCED on time a` and `SYNCED on time b` when you show in the real-time (or close to it) dashboard (or in some admin tools.). Currently, we just get `SYNCED` or `STALE` based on the following logic.
```go
	if wr.NonceAcked == wr.NonceSent {
		return status.ConfigStatus_SYNCED
	}
```
Another way is providing nonce, but it is not user-friendly as it is mostly gibberish. Also, to make it clear including time in sync-status response does not mean `istioctl proxy-status` has to use it. It need not, but we do in our internal product.

**Comment by therealmitchconnors** [comment]
Can you help me understand what you are doing with the statusgen code?  This interface will be undergoing serious change in the next few versions, and may be going away altogether.  We have been treating this as an internal API - not needing deprecation before breaking changes are pushed.  Is that not the case?

**Comment by su225** [comment]
@therealmitchconnors - We do something that istioctl does, but instead of one shot commands we need streaming updates. One more use case is getting syncz statuses for various XDS resources. The alternative (like what `istioctl proxy-status` does) is to exec into the pod and hit the debug endpoint (no-no as we could have permissions issue - This is not `istioctl` doing it. It is a component of our internal product). Is it going away? I see `istioctl x proxy-status` using syncz XDS endpoint. 

Another usecase we have is getting connected/disconnected notifications - again for reporting purposes. There is one alternative using Kubernetes controllers, but we have to handle VM cases separately - the latter is a bit painful for our particular usecase as we pick some fields from the metadata. This is far more convenient.

In case statusgen is going away or is changing significantly, could you point me to a doc with the alternative design or the changes for statusgen? Although internal, it is very important from observability perspective. I see `debuggen` to hit debug endpoints. I see `/debug/connections` could be enhanced with metadata, but still it does not provide notification feature. We also use NACK notifications.
