### ISSUE TITLE
Detect crashes in tests, not just restarts

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31477]
Example https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31467/integ-pilot-k8s-tests_istio/1371492283119046656/artifacts/pilot-analysis-2f9ed6b8171244a3/_suite_context/istio-state-996081096/cluster-0/istiod-f8bf844b7-b5xmb_pod-state.yaml

Right now, we just check the pod restarts: https://github.com/istio/istio/blob/9366430b10ee745bdf369a47213e2c0940795779/pkg/test/kube/dump.go#L221

We should check that it didn't crash, since it may just have not restarted yet.

**Comment by nicomitchell** [comment]
Would it be okay if I took a look at this?

**Comment by howardjohn** [comment]
That would be great

**Comment by nicomitchell** [comment]
Is the way to check this just to see if the state is terminated, or are there other checks that mark a crash?

**Comment by howardjohn** [comment]
If it crashes the container will terminate. So I think we just need to check "has the container every terminated". I am not exactly sure what the manifests into in the pod spec/status, but it must be there somewhere.

The issue with our current code is that it looks for restarts, so if we crash then immediately stop the test the container may not have restarted yet.
