### ISSUE TITLE
Istio client certificate authentication

### ISSUE THREAD

**Issue by apryiomka** [istio/istio#31482]
**Describe the feature request**
Currently we use certificate to authenticate our clients. No way to enable this without providing the client certificate that hinders our ability to avoid downtime for certificate migration.

We should be able to enable certificate validation of the client and use the following parameters to validate: Common Name of the client and Certificate authority chain.

**Describe alternatives you've considered**
Currently istio support mutual TLS on the gateway, but that requires certificate to be present and doesn't allow CN configuration for verification.

What we need is:

1. Cert secret that contains full Certificate Authority chain
2. The validation depth between the provided client certificate and the Certification Authority chain
3. Common Name validation

We should not require the client certificate since the cert can be re-issued an any point.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Sorry it's not clear to me what the request is. Istio supports the MUTUAL tls type that does client authentication - does that meet your needs? If not, what changes are needed?

**Comment by apryiomka** [comment]
> Sorry it's not clear to me what the request is. Istio supports the MUTUAL tls type that does client authentication - does that meet your needs? If not, what changes are needed?

Currently nginx allows you to setup two properties for client certificate authentication:

```
ssl_client_issuer = the authority that issued client certificate
ssl_client_list = CNames of accepted client certificates
```

which looks something like

```
"ssl_client_enabled": true,
"ssl_client_issuer": "CN=Company IT TLS CA 4,OU=Company IT,O=Company Corporation,L=City,ST=State,C=US",
"ssl_client_list": [
"CN=ops.example.com",
"CN=blah.example.net",
"CN=somethingelse.example.org"
]
```
this in fact enables the client certificate validation against the issuer and the common names. I don't see where istio allows this kind of configuration? What am I missing?

**Comment by howardjohn** [comment]
Couldn't I just self sign a certificate with those properties? or is this in addition to standard authorization?

You can get the CN part with `subjectAltNames` more or less - CN has been deprecated for like 20 years and isn't really supported anymore.

**Comment by apryiomka** [comment]
The purpose of the client certificate is that the client can maintain it independently of the server. I also do not dictate how the client issues the cert or when they update it. There is no "self sign" here, all our certs are issued by the trusted root authority within the company. The client's common name and the root authority doesn't changer, whereas the cert does as it expires every 12 months. Currently we should be able to 100% validate the client's certificate using the config above since we can validate the authority and the common name which is unique and cannot be forged. I don't see how this is now can be configured in Istio. The above is a common config for nginx, why doesn't istio support it?

**Comment by apryiomka** [comment]
it is also fine to not validate common names and validate DNS names instead. It doesn't change the fact that this is not configurable on istio side. I am happy to validate the entire subject if this is supported.

**Comment by howardjohn** [comment]
It is configurable by `subjectAltNames` in the Gateway, unless I misunderstand.

**Comment by apryiomka** [comment]
I am looking at [this example](https://istio.io/v1.7/docs/tasks/traffic-management/ingress/secure-ingress/) - we use istio 1.7:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: mygateway
spec:
 selector:
   istio: ingressgateway # use istio default ingress gateway
 servers:
 - port:
     number: 443
     name: https
     protocol: HTTPS
   tls:
     mode: MUTUAL
     credentialName: httpbin-credential # must be the same as secret
   hosts:
   - httpbin.example.com
```
The `credentialName: httpbin-credential` currently holds the server certificate. We do use ALB controller in EKS with certificate offloading and forward traffic to port `80`. Do we still need the `credentialName: httpbin-credential` in this case?
