### ISSUE TITLE
istioctl install creates unused istio-system namespace when root namespace is different 

### ISSUE THREAD

**Issue by frankbu** [istio/istio#31495]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Running `istioctl install` in a cluster where the root namespace is not `istio-system`, creates an empty `istio-system` ns as a side effect. For example, when you enable the `istio-ingressgateway` using `istioctl install` on a cluster with an external control plane (istio root is `external-istiod`, not `istio-system`) as [documented here](https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/#enable-gateways), it deploys the gateway in the `external-istiod` ns (as expected), but it also creates the `istio-system` namesapace (nothing in it, just the empty ns).

If you use `istioctl manifest generate -f istio-ingressgateway.yaml | kubectl apply -f -` instead of `istioctl install ...` it doesn't create the `istio-system` ns.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Should not create the extra istio-system namespace.

**Steps to reproduce the bug**

See bug description.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Latest version.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
I didn't write this code but @litong01 asked me about it.

https://github.com/istio/istio/blob/master/operator/pkg/manifest/shared.go#L212 shows that the installer is looking for the option `values.global.istioNamespace` and uses that to create the IOP bill-of-materials when installing Istio.

The profiles themselves, e.g. _manifests/profiles/default.yaml_, have the namespace.

Probably the docs or the behavior of the tool should be changed.  It would be straightforward to add a setting for `values.global.istioNamespace` to the docs.

It might be possible to pick up the IOP namespace from somewhere else if `values.global.istioNamespace` is unset, but I am not sure what a good choice would be.

**Comment by litong01** [comment]
@frankbu @esnible This problem can not be reproduced from 1.9.4 or master branch build. I think this was fixed by other PRs @frankbu mentioned.

**Comment by litong01** [comment]
@frankbu see my test.
```
ubuntu@u2004:~/test/istio-1.9.4/bin$ ./istioctl install --set profile=demo -y --set values.global.istioNamespace=tongli
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Egress gateways installed
✔ Installation complete                                                                                              
ubuntu@u2004:~/test/istio-1.9.4/bin
```
This has been tested against gke and iks, with k8s release 1.18 and 1.19

**Comment by frankbu** [comment]
@litong01 Sounds like you're right, it's already fixed by some other PR. I removed [this workaround](https://github.com/istio/istio.io/blob/3bfd43bcb8655c5600cac8434271e33e40a25ea3/content/en/docs/setup/additional-setup/external-controlplane/test.sh#L134) to test out the place I originally noticed the problem. If https://github.com/istio/istio.io/pull/9616 passes the test, we can close this issue.

**Comment by frankbu** [comment]
@litong01 The test failed, so the bug is still there. https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/9616/doc.test.multicluster_istio.io/1387453380695166976/artifacts/tests-setup-multicluster-4d17fb/TestDocs/setup/additional-setup/external-controlplane/test.sh/after_snapshot/_test_context/diff.txt

**Comment by frankbu** [comment]
Not fixed yet.
