### ISSUE TITLE
fix workload-trust-bundle remote endpoint fetch functionality

### ISSUE THREAD

**Issue by shankgan** [istio/istio#31497]
Fixes are needed for the way we fetch trustAnchors from Spiffe remote Endpoints

- To ensure consistency, we will prevent Istiod from starting until we are able to fetch trustAnchors from all remote endpoints

- When endpoints are temporarily unavailable, we will continue to hold on to their previously provided trustAnchors

 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by apolovov** [comment]
I think it isn't kind to hold Ready status till the remote endpoint becomes reachable.
A similar case with multicluster setup and remote API server in issue #30838.
