### ISSUE TITLE
Collect istio access logs to external db

### ISSUE THREAD

**Issue by ningyougang** [istio/istio#31507]
**Describe the feature request**

I refered to the article https://istio.io/latest/docs/tasks/observability/logs/access-log/, i can get the access logs successfully, but it just prints the standard output.

My target is `send the logs to external db`, i found the old istio supported it, but after 1.7.8+ version, it seems istio deleted it.
When executed old version article's command in `istio 1.9.1` env, it reported below error, e.g.
```
# kubectl apply -f fluentd-istio.yaml 
unable to recognize "fluentd-istio.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "fluentd-istio.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "fluentd-istio.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
```

Have any idea?
 
**Describe alternatives you've considered**

Firstly, i want to know why some crd is deleted in new version, then, there has some method to send the access log to external db?
Currently, my idea is, configure the accessLogFile to `a file path`, and use `filebeat` to send the log file content to external http endpoint.

Have any better idea?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ningyougang** [comment]
In https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/, `enableEnvoyAccessLogService = false` by default
If we configure `enableEnvoyAccessLogService = true`, maybe we can do some things.

In https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/als.proto
It say `The v2 xDS API is not supported in Envoy v1.18.0 and above.`,
I am not sure it can do some thing, i am looking into it.

**Comment by bianpengyuan** [comment]
Those CRs (handler, rules etc) were for Mixer. Mixer has been deprecated and removed completely since Istio 1.8.

You basically have found all the alternatives, to either forward your proxy log (either from std or some file) via agent like fluentbit, or use the access log service. V2 protocol has been deprecated, and updated to v3: https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/accesslog/v3/als.proto which you will need to implement via a log service.

**Comment by mjrlgue** [comment]
same issue for me, I am using istio v 1.7.3 in windows 10 with Docker desktop installed, as prior version of istio (1.8 and 1.9) didn't work for me, I'm unable to export istio logs (istio components) and access logs. I tried like you all the steps you listed without success, hope istio team will add a feature to export logs.

**Comment by 13567436138** [comment]
how to deal with this
