### ISSUE TITLE
istioctl experimental wait for virtualservice will hung till timeout after the bookinfo pod re-connect to istiod

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#31509]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
**Step 1**: Install istio(v1.9.1) in the **demo** mode in my kubernetes (v1.20), make sure that **istio-egressgateway** pod can be running in istio-system
**Step 2**: Deploy bookinfo application
**Step 3**: Execute following command in one terminal: 
`istioctl experimental wait --for=distribution --threshold=.99 --timeout=20s virtualservice bookinfo.default`
**Step 4**: Execute following command in another terminal: 
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`

For now, everything is fine, and the command in **step 3** can be completed quickly. However, after a long time wait, when the pods, such as bookinfo or istio-egressgateway pod, re-connect to the istiod, then re-do the **Step 3**,  the command can not finish quickly and it will exit till timeout. Here is the output as below:
` Error: timeout expired before resource VirtualService/default/bookinfo became effective on all sidecars`

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
There should be completed quickly as the first time even if the pods re-connect to istiod

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
Install istio(v1.9.1) in the **demo** mode in my kubernetes (v1.20), make sure that **istio-egressgateway** pod can be running in istio-system

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ericvn** [comment]
Not sure if https://github.com/istio/istio/issues/27330 is related, but it seems similar.

**Comment by ericvn** [comment]
istio.io tests worked around the issue https://github.com/istio/istio.io/pull/8163. A change in the utils after the `wait` works correctly could be done.

**Comment by zhlsunshine** [comment]
Hi @ericvn ,  this issue is similar with #27330 on the surface, however, they are not the same issues. This issue was caused by some incorrect calculation on number of distribution resources based on particular threshold which I have set ` --threshold=.99`.
