### ISSUE TITLE
How to combine istio and nginx without using ingress gateway？

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#31508]
Link of the current cluster：
```bash
slb->nginx-nodeport->k8s-svc

# nginx is not nginx-ngress 
# nginx has ssl config
```
For historical reasons, nginx cannot be replaced now. But I don't want to join ingress-gateway to add a jump:
```bash
slb->ingress-gateway->nginx-svc->k8s-svc
```

Is there a good solution to this problem? 

ths

**Comment by bianpengyuan** [comment]
You can deploy Istio without Ingress, by disabling the ingress component in your operator manifest. I think it is actually good practice to manage gateway and rest of Istio separately. See https://istio.io/latest/docs/setup/upgrade/gateways/ for some configuration examples.

**Comment by howardjohn** [comment]
https://www.tetrate.io/blog/using-istio-with-other-ingress-proxies/ may help. Feel free to ask followup questions on discuss.istio.io. Thanks!
