### ISSUE TITLE
istioctl proxy-config lookup localhost on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by setevoy2** [istio/istio#31515]
**Bug description**

When executing any of the proxy-config commands - have error saying:

```
$ istioctl proxy-config cluster productpage-v1-6b746f74dc-cjlxw
Error: failed to execute command on productpage-v1-6b746f74dc-cjlxw.default sidecar: failure running port forward process: Get "http://localhost:44217/config_dump": dial tcp: lookup localhost on 8.8.8.8:53: no such host
```

Reproduced on an AWS EKS and local minikube clusters.

Looks line `istioctl proxy-config` going to the locally configured DNS on a workstation instead on the pod.

My `resolv.conf` has Google DNS set:

```
$ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

`istioctl proxy-config` must return dump from a pod's local Envoy.

**Steps to reproduce the bug**

1. spin up a minicube cluster
2. install the Bookinfo app from the Getting Started guide
3. issue any of the `istioctl proxy-config`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (8 proxies)
```

**How was Istio installed?**

```istioctl install --set profile=demo -y```

**Environment where the bug was observed (cloud vendor, OS, etc)**

- minikube
- AWS EKS

**Comment by howardjohn** [comment]
I think its a reasonable expectation that `localhost` resolves. You should have something like
```
$ cat /etc/hosts
127.0.0.1        localhost
```

This will break a lot of other apps if you don't do this (source: I had the same issue with other apps :slightly_smiling_face: )

**Comment by setevoy2** [comment]
OMG! Thanks a lot, @howardjohn!
Didn't even thought about that.
Yeah, checked my `/etc/hosts` and I had no `127.0.0.1 localhost` in there.
After adding - everything works as expected.
