### ISSUE TITLE
Installing istio in other namespaces will always try to create an IOP under istio-system

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#31517]
**Bug description**

```console
# istioctl install --set values.global.istioNamespace=istio-demo -y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed 
✔ Installation complete
Error: failed to install manifests: failed to create "IstioOperator/istio-system/installed-state": namespaces "istio-system" not found
```

[X] Installation

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
installing istio successfully without any errors.

IOP should be created in istio-demo.

**Steps to reproduce the bug**
run `istioctl install --set values.global.istioNamespace=istio-demo -y`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10

**How was Istio installed?**
istioctl install

**Comment by shamsher31** [comment]
Similar issue https://github.com/istio/istio/issues/30897
