### ISSUE TITLE
Istio monitor external HTTPS calls behind cooperate proxy

### ISSUE THREAD

**Issue by semihural** [istio/istio#31523]
We've several microservices running in on-prem k8s(v.1.19) cluster with Istio(v.1.9.0).Some of the microservices makes a https call to an external API outside of our mesh/cluster where the traffics should go through the cooperate proxy which is also outside of cluster. Thus each microservice's pod has an environment variable such as `HTTP_PROXY` and `HTTPS_PROXY`

What my aim is, monitor whole this traffic and implement Istio's retry logic when server response 5xx.. First I tried with ServiceEntry without configuring Istio's egressgateway but I only able to see the traffic between pod and proxy inside pod's log as below. Meanwhile, in Kiali, again I can only able to see proxy as a external-mesh.
 

    Use 'kubectl describe pod/api-dev-7d65d79f8b-c9c55 -n hub-dev' to see all of the containers in this pod.
    /usr/src/app $ https_proxy=$HTTPS_PROXY curl -I -L  https://api.example.com 2>/dev/null | head -n 1
    HTTP/1.1 200 Connection established

    $ kubectl logs -f api-dev-7d65d79f8b-c9c55 -n dev -c istio-proxy
    [2021-03-16T09:31:06.620Z] "- - -" 0 - - - "-" 987 4733 43 - "-" "-" "-" "-" "53.18.191.131:3128" outbound|3128||security-proxy 10.6.21.236:40810 53.xx.xx.xx:3128 10.6.21.236:40808 - -

So I wonder whether if Istio can able to catch the final destination or not for the traffics going through over the external proxy.If I understood correctly from the documentation as below it is not possible but maybe I am wrong.

So, how can I see the logs and monitor the traffic between the pod and external API ? How can I implement a virtual logic.. As I mentioned currently I can only able to see the logs between pod and proxy server

From Istio [documentation][1]:

> Note that you must not create service entries for the external
> services you access through the external proxy, like wikipedia.org.
> This is because from Istio’s point of view the requests are sent to
> the external proxy only; Istio is not aware of the fact that the
> external proxy forwards the requests further.

Here are the ServiceEntry that I created without egressgateway configuration.

    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: cooperate-proxy
      namespace: dev
    spec:
      hosts:
      - security-proxy
      ports:
      - number: 3128
        name: tcp
        protocol: TCP
      location: MESH_EXTERNAL
    
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: api.example.com
    spec:
      hosts:
        - api.example.com
      ports:
        - number: 80
          name: http-port
          protocol: HTTP
          targetPort: 443
        - number: 443
          name: https
          protocol: HTTPS
      resolution: NONE
      location: MESH_EXTERNAL

I also tried with EgressGateway but still it did not work for me. 

    --
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: egressgateway-for-devapi
      namespace: dev
    spec:
      host: api.example.com
      trafficPolicy:
        portLevelSettings:
        - port:
            number: 443
          tls:
            mode: SIMPLE
            credentialName: devapi-credential
    ---
    
    apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: devapi-egressgateway
      namespace: dev
    spec:
      selector:
        istio: egressgateway
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
        - api.example.com
    
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: devapi-egress-vs
      namespace: dev
    spec:
      hosts:
      - api.example.com
      gateways:
      - istio-egressgateway
      - mesh
      http:
      - match:
        - gateways:
          - mesh
        route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            port:
              number: 80
          weight: 100
      - match:
        - gateways:
          - devapi-egressgateway
          port: 80
        route:
        - destination:
            host: api.example.com
            port:
              number: 443
          weight: 100
        retries:
          retryOn: "5xx"
          attempts: 3
          perTryTimeout: 30s

  [1]: https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/#understanding-what-happened

**Comment by bianpengyuan** [comment]
If the app initiates TLS, sidecar proxy or egress gateway won't be able to decipher the request and do monitoring or retry. They just treat the request as opaque TCP bytes stream. You will need to send plain text (http instead of https) and let Istio proxy do the TLS initiation via destination rule.

**Comment by semihural** [comment]
hi @bianpengyuan,
Actually this is also what I tried. If you check the DestinationRule I tried to pass a TLS secret for TLS origination..I wonder whether if I can explain the issue properly or not but can it be the case that I cant see the final destination of request.

Let me try to explain simply

ServiceA(Microservice running inside our mesh)
ServiceB(Cooperate proxy running outside of mesh)
ServiceC(External API service running outside of mesh)

Traffic goes through (ServiceA can reach ServiceC only through ServiceB due to policy)

ServiceA -> ServiceB -> ServiceC..

So in this case, I could not able to visualise or monitor or see the logs the call of ServiceC.. I only able to see ServiceA and ServiceB as I mentioned in question.

Here is how Kiali looks like.. Might be out of topic but wanna share to explain what is my issue.
![image](https://user-images.githubusercontent.com/38153463/111580808-37d7d500-87c9-11eb-83f6-df0d0e8ed119.png)

**Comment by bianpengyuan** [comment]
Sorry it is not easy to interpret the kiali image, as it is cut in half and I am not sure which service should I look at. Also for the service a->b->c hop you described, there is no egressgateway anymore? Would be great if you can provide information on how destination rule & virtual service etc are configured in this flow, with a stats dump from each proxy involved (`k exec <pod> -c istio-proxy curl localhost:15000/stats/prometheus`)

**Comment by semihural** [comment]
Hi @bianpengyuan,
I guess I found the issue but not sure really..Seems Istio 1.9.0 can not able to handle CONNECT method.. I just created separate issue as  below.. If you confirm that might be the issue we can close this.

https://github.com/istio/istio/issues/31557

**Comment by bianpengyuan** [comment]
Ok thanks! It makes sense then that you cannot observe the service in the graph. Let's track it there.
