### ISSUE TITLE
Auto config injection for gateways as well

### ISSUE THREAD

**Issue by ashleythomasv28** [istio/istio#31542]
**Describe the feature request**
Automatic injection of the envoy configuration like env variables in gateways as well. Currently it happens through deployment of gateway with required configuration. If it is possible to inject the config similar to sidecar proxies through a template present in istio-sidecar-injector config map in istio-system namespace, there won't be discrepancies and duplication of helm charts for ingress gateway and sidecar config. 

**Describe alternatives you've considered**
Alternative is have the config duplicated in the ingress gateway helm chart and control plane helm chart

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
We are actually adding this in Istio 1.10! https://github.com/istio/istio/blob/1a7af4606a4eaceadd4f1b46d656467eeb56f26a/tests/integration/pilot/ingress_test.go#L404

Most of the code is ready but remaining work is documentation. Would love to get your feedback on this.

**Comment by ashleythomasv28** [comment]
That's great! Can this template be stored in a config map? Like _istio-sidecar-injector_ config map for sidecars?

**Comment by howardjohn** [comment]
It is created by default in Istio 1.10, stored as another entry in the same configmap

**Comment by ashleythomasv28** [comment]
Sure, could you please point to the design document (If present) ? Also if there is something on how upgrade would work with this change.

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit.
For upgrades - that is TBD. This was something we were casually
experimenting with and then suddenly got a lot of interest so are starting
to ramp up more investment here.

**Comment by ashleythomasv28** [comment]
Thanks. This looks good and fits our requirement as well. What's the timeline for this release?

**Comment by ashleythomasv28** [comment]
@howardjohn  I see this feature has been released in 1.9.2 release. Could you please let me know if this feature is fit for use in production yet?

**Comment by howardjohn** [comment]
While I would encourage you to try it out and give feedback, this feature
is currently "experimental" in 1.9.2. That being said, there is substantial
interest so we will be aggressively promoting this to alpha/beta/stable as
soon as possible.

**Comment by ashleythomasv28** [comment]
@howardjohn where can we track the status of this feature (if it has been promoted to alpha/beta/stable)? I don't see it any docs for 1.9.4 as well?

**Comment by howardjohn** [comment]
I have a PR for docs in https://github.com/istio/istio.io/pull/9706

**Comment by howardjohn** [comment]
This has shipped https://istio.io/latest/docs/setup/additional-setup/gateway/
