### ISSUE TITLE
Is there any proposal for data plane losess upgrade?

### ISSUE THREAD

**Issue by ks864148379** [istio/istio#31540]
**Describe the feature request**
Istio control plane is easy to upgrade but if we want to upgrade the data plane sidecar container, we must rebuild all pods to upgrade envoy.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
Related: https://github.com/istio/istio/issues/31246. Let's track it there since it has more context. Thanks!
