### ISSUE TITLE
istio-telemetry-pod-is-hitting-zipkin-dns-address-continuously-but-we-have-istio-tracing-disabled

### ISSUE THREAD

**Issue by raviatsapient** [istio/istio#31550]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
**Version**
Istio-1.6.7

**How was Istio installed?**
istioctl install -i istio-system -n istio-system  -f  iop.yaml

**Environment where the bug was observed (cloud vendor, OS, etc)**
Google Cloud

**Bug Details**
We installed istio 1.6.7 in our environment with enableTracing: false. But istio telemetry pod is getting

> --trace_zipkin_url=http://zipkin.istio-system:9411/api/v1/spans value. Now istio-telemetry pod unnecessary hitting the kube-dns very frequently. Why Zipkin URL is coming in the configuration? and How can I disable this“–trace_zipkin_url”?. any help would be appreciated.

**Comment by howardjohn** [comment]
Please see https://github.com/istio/istio/issues/31553. Thanks!!
