### ISSUE TITLE
enableTracing not working on istio 1.6.7

### ISSUE THREAD

**Issue by boredabdel** [istio/istio#31553]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Using the IstioOperator Pattern and setting enableTracing to false doesn't seem to do anything. I run a tcpdump from the node where the pod is and i'm finding out that the sidecar is still trying to resolve zipkin.istio-system with kubedns

The doc seems to indicate that this flag is supposed to disable Tracing on the proxies side https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig

Is this a bug ? was is fixed in newer versions of Istio ?

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

➜  bin ./istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (4 proxies)
➜  bin ./istioctl version --short  
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (4 proxies)

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
From the docs "Flag to control generation of trace spans and request IDs.". It doesn't stop setting up Zipkin, rather it tells it not to generate trace spans.

The tracing config currently is part of the static bootsrtap of envoy. There is work in https://github.com/istio/api/pull/1740 to make this dynamic. For now, to fully disable it, you can modify the `istio` configmap to look like:
```yaml
data:
  mesh: |-
    defaultConfig:
      tracing: {}
```

**Comment by boredabdel** [comment]
Hi John

Yeap thanks for your response, i figure out a way to disable tracing in the meanwhile. it's a bit complicated with the Operator API 

Thanks ;)

**Comment by yvespp** [comment]
@boredabdel can you post how you managed to disable it with the operator please? I tried it like this https://github.com/istio/istio/issues/31809#issuecomment-811683918 put it didn't work.
