### ISSUE TITLE
Citadel custom CA injection on existing install

### ISSUE THREAD

**Issue by darkdatter** [istio/istio#31552]
**Bug description**
Plugging a CA into Citadel/Istio on an _existing_ Istio install does not work per documentation

https://preliminary.istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/ 

Documentation should reflect an additional, following use case:

```
Existing Istio install/cluster:

You must restart the istiod pods, and the istio-proxy (sidecar) pods after: creating the cacerts secret,
and running istioctl install.
```

Now, this obviously poses as an issue for prod users that can't just restart all their pods...so perhaps there is a less destructive way to restart the istio-proxies in bulk (new istioctl feature, some existing way to signal to the istio-proxy containers to die and start again, etc.).

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
istiod and istio-proxies should utilized your plugged-in certificates. 

**Steps to reproduce the bug**
- Install istio
- Deploy a sample workload
- Configure a secret with your custom Intermediate CA certs for istio (https://preliminary.istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)

**Version**
Istio:
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (16 proxies)

kubectl:
Client Version: v1.18.15+k3s1
Server Version: v1.18.15+k3s1

k3s:
k3s version v1.18.15+k3s1 (60f1e80d)

**How was Istio installed?**
istioctl install
(default profile)

**Environment where the bug was observed (cloud vendor, OS, etc)**
k3s running on AWS instances (k3s version v1.18.15+k3s1 (60f1e80d))

**Comment by bianpengyuan** [comment]
I believe this is being worked on: https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit#heading=h.io2z16q0yjxj

**Comment by darkdatter** [comment]
> 
> 
> I believe this is being worked on: https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit#heading=h.io2z16q0yjxj

I have requested access to this resource.

**Comment by bianpengyuan** [comment]
You can join Istio community drive access group and gain access to all design docs: https://groups.google.com/forum/#!forum/istio-team-drive-access

**Comment by bianpengyuan** [comment]
and GH issue for this: https://github.com/istio/istio/issues/31111

**Comment by darkdatter** [comment]
> 
> 
> You can join Istio community drive access group and gain access to all design docs: https://groups.google.com/forum/#!forum/istio-team-drive-access

Given these two items, I feel that once implemented...this gap in documentation/functionality should be filled. Thanks @bianpengyuan! Closing issue.
