### ISSUE TITLE
Sporadic 'Connection reset' issues

### ISSUE THREAD

**Issue by martin-dodo-hartmann** [istio/istio#31576]
**Bug description**
In <1% of requests, some users of our cluster face sporadic _java.net.SocketException: Connection reset_ errors, when calling an endpoint. 

As we were not able to reproduce this issue, the only error information we have are the user's stacktraces:
`Caused by: java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:466)
...`

To trace the requests, we enabled request logging on istio side and checked incoming requests. For the timestamp the user mentioned an issue for, we saw 8 requests for a given IP on NLB, but only 5 of them were logged in istio ingress gateway.

Might be related to [#29995](https://github.com/istio/istio/issues/29995)

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
No 'Connection reset' errors occur.

**Steps to reproduce the bug**
N/A, as we were not able to reproduce it ourselves.

**Version** 
`istioctl version --remote
> client version: 1.9.0
> control plane version: 1.8.3
> data plane version: 1.8.3 (66 proxies)
kubectl version --short
> Client Version: v1.17.6
> Server Version: v1.17.12-eks-7684af
helm version --short
> v3.3.4+ga61ce56`

**How was Istio installed?**
Via istio-operator 1.8.3.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS 
Istio config information:
* 6 Ingress Gateways
* 5711 VirtualServices
* 14620 K8s Services
* 761 Namespaces

I could not attach an Istio bug-report, as it runs since 2 hours now and currently is at namespace 4/761. It it does not timeout, I will add it later.

**Comment by Yorkerrr** [comment]
Hello @martin-dodo-hartmann, we have a similar issue in AKS. Did you find any solution for this?

**Comment by martin-dodo-hartmann** [comment]
Unfortunately not. We are currently updating to istio 1.9 to see if this helps us somehow. But with 1.8.3, our users still face these issues.

**Comment by martin-dodo-hartmann** [comment]
Just for the records: We finally found the root cause for our issues. 
In our infrastructure we have the following request flow:
NLB -> IstioIngress -> Tomcat(3rd party app)
The tomcat has configured a connectionKeepAlive of 5 seconds, whereas envoy doesn't have such a timeout. This lead to the case, where 2 requests cam in within an (exact) 5 second window. While tomcat was closing the connection for idleness, envoy just sent another request at the exact same time.
Our solution was, to add a keepAlive configuration on the affected VirtualServices of 4seconds (slightly below what tomcat has), so that always envoy is the one, terminating connections.

**Comment by infa-ddeore** [comment]
> 
@martin-dodo-hartmann could you provide exact istio settings that you did?

**Comment by infa-ddeore** [comment]
> Just for the records: We finally found the root cause for our issues. In our infrastructure we have the following request flow: NLB -> IstioIngress -> Tomcat(3rd party app) The tomcat has configured a connectionKeepAlive of 5 seconds, whereas envoy doesn't have such a timeout. This lead to the case, where 2 requests cam in within an (exact) 5 second window. While tomcat was closing the connection for idleness, envoy just sent another request at the exact same time. Our solution was, to add a keepAlive configuration on the affected VirtualServices of 4seconds (slightly below what tomcat has), so that always envoy is the one, terminating connections.

@martin-dodo-hartmann could you provide exact istio settings that you did?

**Comment by infa-ayalagar** [comment]
@Yorkerrr : Did the issue got fixed in AKS?

**Comment by anoopkny** [comment]
@martin-dodo-hartmann , Could you please share the config implemented on virtual service?
We are also experiencing same issue but in our case AKS NLB has 4min of timeout and there is no proof from the client side that request took more than 4min nor it was idle.
