### ISSUE TITLE
Auto discovery of istiod for custom gateway upon upgrade with revision

### ISSUE THREAD

**Issue by ashleythomasv28** [istio/istio#31572]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Upon trying upgrade of ingress gateway in a custom namespace by providing revision, gateway still uses istiod.istio-system.svc:15012 as the discovery address. This will make gateway fail to start if istiod is removed. 

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When revision is specified, custom gateway should get the name of correct istiod discovery address to connect to. 

**Steps to reproduce the bug**
Perform upgrade by specifying revision as given [here](https://istio.io/latest/docs/setup/upgrade/gateways/). 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.3

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ashleythomasv28** [comment]
Adding following environment variable solves the issue. Could you confirm if this is the correct way of getting the discovery address. I can raise a PR for the same then: 
```
- name: PROXY_CONFIG #Way for ingress gateway to discover the new istiod upon upgrade
            value: |
                {"discoveryAddress":"istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}.{{ .Values.global.istioNamespace }}.svc:15012"}
```

**Comment by bvandewalle** [comment]
Got the same issue, Gateways by default don't use the correct discovery service. I had to manually modify the PROXY_CONFIG to add the correct revision service.
