### ISSUE TITLE
[Istio 1.9.1] Multicluster VM traces are not collected

### ISSUE THREAD

**Issue by Zero-2** [istio/istio#31581]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I've installed a Primary-Remote on different networks multicluster with a VM. I configured and checked the connectivity between VM and other clusters. 
I also checked that the zipkin instance is reachable from the VM.
But i'm not able to see the traces for the service deployed into the VM.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I want to see the trace also for the VM's service.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio/bin/istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (28 proxies), 1.9.0 (1 proxies)

kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.7

**How was Istio installed?**

https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/

**Environment where the bug was observed (cloud vendor, OS, etc)**
One cluster onprem
One cluster on GKE
One cluster on AKS
One cluster on EKS
One VM on GCE

**Comment by bianpengyuan** [comment]
Was it just a span for the VM call missing, but all other service on kube reporting trace as expected?

Can you get a configuration dump of the VM proxy? https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecargateway-problems

**Comment by Zero-2** [comment]
> Was it just a span for the VM call missing, but all other service on kube reporting trace as expected?
> 
> Can you get a configuration dump of the VM proxy? https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecargateway-problems

Yes spans for the other kube services are working as expected as the image above describe
![image](https://user-images.githubusercontent.com/43739/111864217-eb72cd80-895f-11eb-9f32-8f339c4a0a2c.png)

Instead in the image above no span for the service running on the VM
![image](https://user-images.githubusercontent.com/43739/111864188-d4cc7680-895f-11eb-9e33-b60e07b8b148.png)

Querying Jager, instead , spans seem to exists.
![image](https://user-images.githubusercontent.com/43739/111864352-a4d1a300-8960-11eb-8604-112e69ed6498.png)

Dump:
[clusters.tar.gz](https://github.com/istio/istio/files/6175132/clusters.tar.gz)
[config_dump.json.tar.gz](https://github.com/istio/istio/files/6175133/config_dump.json.tar.gz)
[stats.tar.gz](https://github.com/istio/istio/files/6175134/stats.tar.gz)

**Comment by bianpengyuan** [comment]
Sorry I am confused. Where were the first two graphs from? If jaeger shows the trace fine, it means the VM proxies are reporting spans correctly, no?

**Comment by Zero-2** [comment]
First two screenshots are from Kiali.
Investigating deeper I think could be a Kiali bug.
Maybe it's not able to show the external service traces.
Excuse me.

**Comment by bianpengyuan** [comment]
Ok thanks! Could you please open an issue at Kiali repo? I am going to close this, feel free to reopen this issue if Kiali folks think that this is an Istio issue.
