### ISSUE TITLE
Mutual TLS doesn't work with intermediate certificate

### ISSUE THREAD

**Issue by apryiomka** [istio/istio#31586]
We have in house CA that uses numerous intermediate certificates to the applications. 

When I create cert secret
```
kubectl create -n istio-system secret generic httpbin-credential \
   --from-file=tls.key=company.com.key.pem \
   --from-file=tls.crt=company.com.cert.pem \
   --from-file=ca.crt=root.ca.pem
```

I can make mutual TLS requests

```
curl -v -HHost:httpbin.company.com "https://tls.company.com/status/418" --cert company.com.cert.pem --key company.com.key.pem
...
TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.company.com
*  start date: Oct 20 08:52:18 2020 GMT
*  expire date: Oct 20 08:52:18 2021 GMT
*  subjectAltName: host "tls.company.com" matched cert's "*.company.com"
*  issuer: C=US; O=Company Corporation; CN=Company RSA TLS CA 01
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd420009200)
> GET /status/418 HTTP/2
> Host:httpbin.company.com
```

When I print the cert info used in the cert:

```
openssl x509 -in company.com.cert.pem -noout -issuer
issuer= /C=US/O=Company Corporation/CN=Company RSA TLS CA 01
```

But if I update the ca cert with the Company's intermediate certificate:

```
kubectl create -n istio-system secret generic httpbin-credential \
   --from-file=tls.key=company.com.key.pem \
   --from-file=tls.crt=company.com.cert.pem \
   --from-file=ca.crt=interm.cer.pem
```

I can no longer make requests, mTLS fails

This is the print form the interm cert:
```
openssl x509 -in interm.cer.pem -noout -issuer
issuer= /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
```

**Bug description**

Should be able to validate the intermediate cert 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**How was Istio installed?**
v1.7.4

**Comment by JimmyCYJ** [comment]
Could you verify the certificate manually using `openssl` first? e.g.
``` openssl verify -CAfile root.crt sidecar.crt ```
You can add intermediate cert to the file `root.crt`, and workload cert to the file `sidecar.crt`.
Istiod CA will use the plugged in ca cert to issue workload cert.
A workload cert can be found by a [istioctl command](https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-proxy-config-secret).

If that fails, then probably your mTLS handshake fails because of cert verification.

**Comment by JimmyCYJ** [comment]
cc @myidpt @lei-tang
