### ISSUE TITLE
 Multi-Primary on different networks setup , Load balancing issue

### ISSUE THREAD

**Issue by Sathishkunisai** [istio/istio#31583]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Multi-Primary setup , traffic is always landing in first available POD**

**Istio Multicluster**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version**
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1

**How was Istio installed?** Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)** Azure AKS , Ubuntu

I have Multi-Primary setup on two different network running.

1) Having three Pods running in Region 1 and three Pods running in Region 2
2) Localitylbsettings is enabled
2) No Destination rule (purposefully removed)

Observation : Traffic sharing between pods in Region 1 is even meaning getting distributed evenly.  Where as in Region2 traffic/load is always on First POD  (long lived pod), if I delete first pod and then it goes to second pod meaning not evenly distributing. This behavior is on only one region, Installation steps on both the regions are Same (used operator)

Please advise

Thanks
Sathish

**Comment by bianpengyuan** [comment]
Looks like a dup of https://github.com/istio/istio/issues/31549

**Comment by Sathishkunisai** [comment]
Thanks closing it, Posted my comments in the bug id given

**Comment by bianpengyuan** [comment]
Looks like this is a different one from #31549, which means destination rule is not functioning with auto passthrough.

**Comment by chaudyg** [comment]
@Sathishkunisai where do you originate each request? Are the requests within the same regions (region1 --> region1 AND region2 -> region2) are are you crossing regions (region1 -> region2)?

**Comment by Sathishkunisai** [comment]
Sorry for the delay in reply. Requests are triggered in Region-1 for a service living in Region-2.  (It is a multicluster, two controlplane deployment)

**Comment by Sathishkunisai** [comment]
Problem Statement: in a Multiclustered environment with "two" control planes,  I have same Service-A (caller-service) running on two different regions (two different clusters), incase of failure in region-1 (say 503 from one the instances), traffic is shifting to region-2 at the same time load unevenly distributed among the instances, sometimes 65:45, sometime 70:30, sometime is 100 on long lived pod. (edited) 

did further observations. with localitylbsettings enabled, weightage/priority getting updated (priority 1, 2, 3).  If I collocate all the pods on "one worker Node" distribution is even (50:50), if pods are scattered between nodes (more than one node), then distribution is uneven. My services are "clusterIP" type
