### ISSUE TITLE
[ Istio 1.9.1 ] Prometheus and VM

### ISSUE THREAD

**Issue by Zero-2** [istio/istio#31596]
In order to collect informations about metrics from the services running in the VM I should install Prometheus into the VM?
It's the right way?

Also, is it a best practise to deploy multiple services in the VM?

**Comment by bianpengyuan** [comment]
You can scrape VM proxies with a k8s prometheus server.

VM is like a pod, you can serve whatever number of services with a VM.

For more questions, please try posting at [discuss.istio.io](discuss.istio.io) or Istio slack channel. Thanks!

**Comment by Zero-2** [comment]
Forgive me, i used the wrong term. With service i mean Application.
You already answered me , so if a VM is like a pod i can have one VM <--> one Application. Right?

**Comment by bianpengyuan** [comment]
You can definitely run as many app on a VM, like you can have many containers in a pod.

**Comment by Zero-2** [comment]
Yes, this is clear. I mean that if i want an app that consumes data from a DB i should , for example, deploy database and application on different VMs if i want to trace and see the traffic between them.

Thank you so much.

Regards

**Comment by bianpengyuan** [comment]
You don't need to. Istio should configure the IP table to capture traffic from any app, even it loops back. That said, the app DB query will go through the proxy twice, once outbound, once inbound.
