### ISSUE TITLE
Allow required hosts at ingress gateway auth envoyfilter

### ISSUE THREAD

**Issue by anannaya** [istio/istio#31600]
Description https://github.com/istio/istio/issues/24508

**Comment by bianpengyuan** [comment]
See https://istio.io/latest/docs/tasks/security/authorization/authz-custom/ you can use `AuthroizationPolicy` to control enablement of ext authz call on some hosts. Thanks!

**Comment by anannaya** [comment]
Not this. Is there any way to allow specific virtual hosts in envoyfilter ext_auth?

**Comment by bianpengyuan** [comment]
No, AFAIK there is no plan to support per route ext authz, you'd need to use authz policy to enable CUSTOM action based on host match.

**Comment by anannaya** [comment]
I am looking for Envoyfilter solution , Found this https://github.com/istio/istio/issues/29734#issuecomment-802703317

**Comment by bianpengyuan** [comment]
Is there any reason you cannot use authz policy to select hosts to apply ext authz filter?

**Comment by anannaya** [comment]
I have been using Envoyfilter from istio 1.4 .. and more over  ext authz filter says **Experimental**.

**Comment by anannaya** [comment]
@bianpengyuan  Can you point me a example in CUSTOM , how to handle based on virtual Hosts?
