### ISSUE TITLE
Can't access productpage in windows 10

### ISSUE THREAD

**Issue by mjrlgue** [istio/istio#31613]
**Bug description**
I followed this [demo](https://www.docker.com/blog/getting-started-with-istio-using-docker-desktop/) to set up istio in Windows 10, the installation was successful but I can't access the web page http://localhost/productpage, I checked the ingressgateway with `kubectl get svc istio-ingressgateway -n istio-system` and have the following response:
```
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP                                                                                                                                         AGE
istio-ingressgateway   LoadBalancer   10.106.170.227   localhost
```
but I am able to access **kiali** on localhost:15029/kiali

What I did is to change the type to **NodePort** using  `kubectl edit svc istio-ingressgateway -n istio-system` to assign an external ip to ingressgateway and I was able to access http://localhost:31380/productpage but I can't access **kiali**, how to fix this please ? 

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I have to be able to access both productpage and kiali with localhost
**Steps to reproduce the bug**
install istio with the steps in this [demo](https://www.docker.com/blog/getting-started-with-istio-using-docker-desktop/) in windows 10 with docker desktop 3.2.2
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
kubectl : Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}

**How was Istio installed?**
in Windows 10 [version 10.0.17763.1757], Docker Desktop 3.2.2 (61853) with kubernetes 1.19.7

**Comment by howardjohn** [comment]
The demo is out of date. It is expected port 15029 to be exposed on the ingress gateway service when it isn't. This needs to either be done explicitly (see https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) or follow https://istio.io/latest/docs/tasks/observability/gateways/.

Closing this as its working as expected - thanks!!
