### ISSUE TITLE
Regression: istio.io egress test case gets 408 instead of 504

### ISSUE THREAD

**Issue by ericvn** [istio/istio#31616]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Running the `tasks/traffic-management/egress/egress-control` test and it is failing. Specifically, the tests for this section: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#manage-traffic-to-external-services. This section says the test should go from a `2002` to a `504` return code, and instead we are getting back a 408.

```
VERIFY FAILED snip_manage_traffic_to_external_services_3 (timeout after 120s):
received:
"408
real	0m 3.02s
user	0m 0.00s
sys	0m 0.00s"
expected:
"504
real    0m3.149s
user    0m0.004s
sys     0m0.004s"
```

I'm not sure if this is a regression, or a desired. If the later, we can update the docs.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Existing tests should continue to pass

**Steps to reproduce the bug**

Run the istio.io test. See https://github.com/istio/istio.io/tree/master/tests.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Latest `master`

**How was Istio installed?**

Via pipeline

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
@ramaraochavali we get `408 - max_duration_timeout` is it expected?

**Comment by howardjohn** [comment]
Even if we merge something like https://github.com/istio/istio.io/pull/9356, please keep this open as a release blocker until ^ is answered

**Comment by howardjohn** [comment]
@ramaraochavali did you have a chance to look into the 408?

**Comment by ramaraochavali** [comment]
Sorry. I missed this notification. 
`408 - max_duration_timeout` seems incorrect.  408 should be returned when idle timeout happens. Any way this https://github.com/envoyproxy/envoy/pull/15585 is close to be merged, once it is merged we can remove max_duration setting and try. Keep this issue open till we figure that out.

**Comment by ericvn** [comment]
I think we still wanted to keep this open

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/9568 is a test which has the envoy and istio PRs to see if the regression is reversed.

**Comment by ericvn** [comment]
@ramaraochavali @howardjohn The tests (which are looking for the incorrect 408) still pass, so the regression is still not fixed.

**Comment by ericvn** [comment]
For reference, I did start a `kind` cluster, installed 1.10-alpha.1, and worked through `https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/` and did receive the 408 (expected 504) during the last step.

**Comment by ericvn** [comment]
I do see within the config:
```
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "outbound|80||httpbin.org",
           "timeout": "3s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_stream_duration": {
            "grpc_timeout_header_max": "3s"
           }
```
and other configs have:
```
           },
           "max_stream_duration": {
            "max_stream_duration": "0s",
            "grpc_timeout_header_max": "0s"
           }
```

**Comment by ericvn** [comment]
I going to assign this issue to @ramaraochavali so it as an owner as it's a release-blocker. Please assign as appropriate. Thanks.

**Comment by ramaraochavali** [comment]
This should be fixed now.

**Comment by ericvn** [comment]
@ramaraochavali Can you identify where it was fixed so I can test? Thanks.

**Comment by ramaraochavali** [comment]
The fix is available with this PR https://github.com/istio/istio/pull/32139 in master and it has been backported to 1.10 also

**Comment by ericvn** [comment]
@ramaraochavali As noted in my comment above, https://github.com/istio/istio/issues/31616#issuecomment-823497361, I did test with the Envoy change and the mentioned Istio change (they should be in 1.10-alpha.1) and it still failed.

**Comment by ramaraochavali** [comment]
Ah. Sorry. I missed that comment. I will take a look.

**Comment by ramaraochavali** [comment]
Looking at it - I was thinking setting max_stream_duration was causing the issue. But it looks like it is not the cause. So it might be some thing else. I will debug more and let you know. Can you please share full config_dump if it is avaiable?

**Comment by ericvn** [comment]
No comments in Envoy PR yet. I notice the one Google team updated to use the new return codes.

**Comment by ramaraochavali** [comment]
No. We should not do that. https://github.com/envoyproxy/envoy/pull/16131 - See the latest discussion on this. I am pushing a PR to use use the deprecated fields so that it is fixed for now.

**Comment by ericvn** [comment]
@ramaraochavali Just checking on the status of this release-blocker fix. Are we waiting on a PR on envoyproxy/envoy `main` or the `1.18` release branches? Maybe a change in istio/istio? Thanks.

**Comment by ramaraochavali** [comment]
The Envoy PR is merged to master. https://github.com/envoyproxy/envoy/pull/16133 is approved for backport to 1.18.2. If it does not land in time for us, we will have to do a workaround in istio/istio for 1.10. 

cc: @Monkeyanator @howardjohn

**Comment by Monkeyanator** [comment]
@ramaraochavali thanks for the info. I'm not sure how this process normally goes but is it viable to get it backported within the next week? Or who can we ping to make sure that happens? Code freeze isn't until May 11th so we have a bit of time

**Comment by ericvn** [comment]
I'm hoping that it would get back ported to the `https://github.com/envoyproxy/envoy/tree/release/v1.18` branch. At that point, we would pick the change up within 24 hrs and be in our builds. Then not sure if we need something else in istio/istio. Once this happens, the istio.io test should fail when picking up the istio build, and require a change in the test to use 504 instead of 408.

**Comment by ramaraochavali** [comment]
> Then not sure if we need something else in istio/istio.

Once we get the backport - We do not need any thing on Istio

> Or who can we ping to make sure that happens?

I pinged the release manager https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#release-management - Let us see. I am also not sure how backports happen in Envoy (manual or automatic). Based on the reply we can decide.

**Comment by ericvn** [comment]
Looks like https://github.com/envoyproxy/envoy/pull/16289 is close to being merged.

**Comment by caoyukun0430** [comment]
Hi @ramaraochavali , would this be a problem for istio 1.9.x?

 When I tested with istio 1.9 and configured timeout value in vs, my config looks like:
```
"route": {
           "cluster": "outbound|8000||httpbin.default.svc.cluster.local",
           "timeout": "3s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_stream_duration": {
            "max_stream_duration": "0s",
            "grpc_timeout_header_max": "3s"
           }
```
Where I have **"max_stream_duration": "0s"**, and I didn't see 408 errors.

From my understanding, this would be the default max_stream_duration as I didn't set it. But it's different than your config here and in https://github.com/envoyproxy/envoy/issues/15530, where you don't have the  **"max_stream_duration"** field at all.

So will 1,9 also has the issue that timeout is not honored or it's only an issue if   **"max_stream_duration"** field doesn't show up in the config?

Thanks a lot for your explanation!

**Comment by ramaraochavali** [comment]
Could be. I need to check to confirm though

**Comment by caoyukun0430** [comment]
Hi, I think it's an issue in istio 1.8.x, as you can see the MaxStreamDuration is set to be equal to timeout(I tested with istio 1.8.x and I did get 408 while expecting 504) https://github.com/istio/istio/blob/97e10d79b8b5b32be0f92175586a4e11c466e640/pilot/pkg/networking/core/v1alpha3/route/route.go#L423-L427
But I think istio 1.9.x changes/solves it by defining MaxStreamDuration default to be 0s (no longer equals to route timeout) https://github.com/istio/istio/blob/13fb8ac89420d8cc5b3f895adc614233e805a61c/pilot/pkg/networking/core/v1alpha3/route/route.go#L420-L424
This also matches the config dump I had above, where "max_stream_duration": "0s" is shown up.

But it would be nice if you can check to confirm if my statement is correct or why in your case, "max_stream_duration" field doesn't show up in the config. 
Thanks a lot!

**Comment by ramaraochavali** [comment]
Yes. Your understanding is correct.
