### ISSUE TITLE
envoy report request traffic confused when multi services with same port access to same group workloads

### ISSUE THREAD

**Issue by jinglina** [istio/istio#31610]
****

**Comment by jinglina** [comment]
step1 : Create gray release, bind service1 at the same time (sidecar injected)​
step2: Create destination rule and virtual service to related workloads according to policy 
step3: access to service1, notice route traffic displayed in kiali
step4: create new service2 which is same port to service1, bind same workloads, destination rule and virtual service same to **step2** result
step5: access to service2, notice route traffic in kiali; no data from service2 to workloads ,but with data from service1 to worklaods

**Comment by jinglina** [comment]
I try to catch data from envoy, access to workload1 from service2, but its upstream_cluster is service1 instead.

**Comment by jinglina** [comment]
I just wander if Istio version 1.9 has noticed this limitation or other further efforts?

**Comment by bianpengyuan** [comment]
This limitation is well known since 1.8. There will be efforts to address this, probably by piggybacking on the upstream cluster extension effort: https://github.com/istio/istio/issues/31444 cc @tbarrella @lambdai

**Comment by jinglina** [comment]
Thanks.

**Comment by jinglina** [comment]
I noticed this scenario : a pod with two containers exposing the two ports separately, 8080 and 8090; two services access to it with different port. Routes traffic in kiali are all displayed , upstream_cluster is accurate

**Comment by bianpengyuan** [comment]
Yeah this is expected, as long as port and service are 1:1 mapping, there will be no ambiguity in telemetry.

**Comment by jinglina** [comment]
yes.

**Comment by lambdai** [comment]
> Yeah this is a known limitation. At inbound, if different services are defined at the same port, we cannot accurately identify the intended destination service. The intended destination service has to be forwarded from the client sidecar.

so only client sidecar knows the exact service. The routing is correct from the context. Is metadata exchange not running?

**Comment by bianpengyuan** [comment]
We don't forward destination service with metadata exchange, yet.
