### ISSUE TITLE
sysdig agent fails to get sidecar injected

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#31611]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
installing sysdig-agent to a namespace with ISTIO-INJECTION enabled doesn't get a sidecar:

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
sysdig-agent to get a sidecar injected into its pod

**Steps to reproduce the bug**
deploy sysdig-agent, its deployed as a daemonset (not sure if this matters) 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.9.1

kubectl version --short
Client Version: v1.17.7
Server Version: v1.18.3+e574db2

helm version --short
v3.5.2+g167aac7

openshift version:
4.5.31_1531

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM Cloud 

istiod log:
[istiod-777b98d848-2twz2] 2021-03-22T14:40:28.273863Z	info	Sidecar injection request for sysdig/sysdig-agent-***** (actual name not yet known) 
[istiod-777b98d848-2twz2] 2021-03-22T14:40:28.273903Z	info	Skipping sysdig/sysdig-agent-***** (actual name not yet known) due to policy check 

sysdig-agent daemonset yaml:
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      meta.helm.sh/release-name: sysdig-agent
      meta.helm.sh/release-namespace: sysdig
    creationTimestamp: "2021-03-18T15:58:54Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: sysdig-agent
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sysdig-agent
      app.kubernetes.io/version: 11.0.0
      helm.sh/chart: sysdig-1.11.9
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deprecated.daemonset.template.generation: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:app.kubernetes.io/instance: {}
              f:app.kubernetes.io/name: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/name: {}
                f:app.kubernetes.io/version: {}
                f:helm.sh/chart: {}
              f:name: {}
            f:spec:
              f:affinity:
                .: {}
                f:nodeAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution:
                    .: {}
                    f:nodeSelectorTerms: {}
              f:containers:
                k:{"name":"sysdig"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:exec:
                      .: {}
                      f:command: {}
                    f:failureThreshold: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:readinessProbe:
                    .: {}
                    f:exec:
                      .: {}
                      f:command: {}
                    f:failureThreshold: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                    f:runAsUser: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/dev/shm"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/etc/modprobe.d"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/boot"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/dev"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/host/etc/os-release"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/lib/modules"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/proc"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/run"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/host/usr"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:readOnly: {}
                    k:{"mountPath":"/host/var/run"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/opt/draios/etc/kubernetes/config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/opt/draios/etc/kubernetes/secrets"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:hostNetwork: {}
              f:hostPID: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"docker-fedramp"}:
                  .: {}
                  f:name: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
              f:volumes:
                .: {}
                k:{"name":"boot-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"dev-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"dshm"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:medium: {}
                  f:name: {}
                k:{"name":"modprobe-d"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"modules-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"osrel"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"proc-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"run-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"sysdig-agent-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                    f:optional: {}
                  f:name: {}
                k:{"name":"sysdig-agent-secrets"}:
                  .: {}
                  f:name: {}
                  f:secret:
                    .: {}
                    f:defaultMode: {}
                    f:secretName: {}
                k:{"name":"usr-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
                k:{"name":"varrun-vol"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:maxUnavailable: {}
            f:type: {}
      manager: Go-http-client
      operation: Update
      time: "2021-03-18T15:58:54Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:currentNumberScheduled: {}
          f:desiredNumberScheduled: {}
          f:numberAvailable: {}
          f:numberReady: {}
          f:observedGeneration: {}
          f:updatedNumberScheduled: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-03-22T14:48:53Z"
    name: sysdig-agent
    namespace: sysdig
    resourceVersion: "3040120"
    selfLink: /apis/apps/v1/namespaces/sysdig/daemonsets/sysdig-agent
    uid: 7b635c4d-3243-4a1b-a105-a01ec334527d
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: sysdig-agent
        app.kubernetes.io/name: sysdig-agent
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: sysdig-agent
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: sysdig-agent
          app.kubernetes.io/version: 11.0.0
          helm.sh/chart: sysdig-1.11.9
        name: sysdig-agent
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                - key: beta.kubernetes.io/os
                  operator: In
                  values:
                  - linux
        containers:
        - image: remote-registry.com/sysdig-agent:11.0.0-20210318155643
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - test
              - -e
              - /opt/draios/logs/running
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sysdig
          readinessProbe:
            exec:
              command:
              - test
              - -e
              - /opt/draios/logs/running
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 1536Mi
            requests:
              cpu: 600m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
              - ALL
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/modprobe.d
            name: modprobe-d
            readOnly: true
          - mountPath: /host/dev
            name: dev-vol
          - mountPath: /host/proc
            name: proc-vol
            readOnly: true
          - mountPath: /host/boot
            name: boot-vol
            readOnly: true
          - mountPath: /host/lib/modules
            name: modules-vol
            readOnly: true
          - mountPath: /host/usr
            name: usr-vol
            readOnly: true
          - mountPath: /host/run
            name: run-vol
          - mountPath: /host/var/run
            name: varrun-vol
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /opt/draios/etc/kubernetes/config
            name: sysdig-agent-config
          - mountPath: /opt/draios/etc/kubernetes/secrets
            name: sysdig-agent-secrets
          - mountPath: /host/etc/os-release
            name: osrel
            readOnly: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        hostPID: true
        imagePullSecrets:
        - name: its-a-secret
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: sysdig-agent
        serviceAccountName: sysdig-agent
        terminationGracePeriodSeconds: 5
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        volumes:
        - hostPath:
            path: /etc/modprobe.d
            type: ""
          name: modprobe-d
        - hostPath:
            path: /etc/os-release
            type: FileOrCreate
          name: osrel
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /dev
            type: ""
          name: dev-vol
        - hostPath:
            path: /proc
            type: ""
          name: proc-vol
        - hostPath:
            path: /boot
            type: ""
          name: boot-vol
        - hostPath:
            path: /lib/modules
            type: ""
          name: modules-vol
        - hostPath:
            path: /usr
            type: ""
          name: usr-vol
        - hostPath:
            path: /run
            type: ""
          name: run-vol
        - hostPath:
            path: /var/run
            type: ""
          name: varrun-vol
        - configMap:
            defaultMode: 420
            name: sysdig-agent
            optional: true
          name: sysdig-agent-config
        - name: sysdig-agent-secrets
          secret:
            defaultMode: 420
            secretName: sysdig-agent
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 34%
      type: RollingUpdate
  status:
    currentNumberScheduled: 18
    desiredNumberScheduled: 18
    numberAvailable: 18
    numberMisscheduled: 0
    numberReady: 18
    observedGeneration: 1
    updatedNumberScheduled: 18
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by GregHanson** [comment]
There are unit tests for daemonsets in Istio, see [here](https://github.com/istio/istio/blob/master/pkg/kube/inject/testdata/inject/daemonset.yaml).  That validation error was added [here](https://github.com/istio/istio/pull/8636) - I think all you need to do is add a `metadata.name` field to the daemonset yaml

**Comment by howardjohn** [comment]
hostNetwork pods are not supported

**Comment by ceastman-ibm** [comment]
ok thanks.
