### ISSUE TITLE
Prepare Release 1.10 branches

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#31627]
Modified version of https://github.com/istio/istio/issues/29490

---

This issue aims to track all steps needed to prepare the release 1.10 branches/builds.

This issue was created early to help document the steps using some new automation (I hope) as well as any ordering changes, etc. Please update/add additional steps taken here so we can document for future releases.

See https://github.com/istio/istio/issues/24473 for steps used for the release 1.7 branch cutting; (note: 1.8 will be more relevant, see https://github.com/istio/istio/issues/27993). Note that was before automation, but does have pointers to PRs to see what some of the steps did. **Note that the actual coding steps done by the automation steps are left in this issue for reference only. You only need to run the automated steps, and not the individual instructions.**

For now, the code to run is in https://github.com/ericvn/release-builder/tree/autoBranch. From within that branch, one can do a `make shell` and then within the shell run `REPO_ORG=myorg STEP=x ./release/branch.sh` (you can update the STEP in the `trigger-branch` file and not set it manually). This generates the changes for review (try`git status` or `git diff`).  Adding DRY_RUN=true will cause the PRs to be created in the REPO_ORG.

Note that the automated steps 3 and on require the new release's branch which is created in automated step 2.

- [x] Set up release manager team - Make sure the new team has write access to the repositories. ([done](https://github.com/istio/community/pull/547))

- [x] Build new base images: `1.11-dev.0`. Run `tools/build-base-images.sh`. You should also update the `1.10-dev` image as it may contains new CVEs. (reach out to @howardjohn) (done [here](https://hub.docker.com/r/istio/app_sidecar_base_ubuntu_bionic/tags?page=1&ordering=last_updated), [here](https://console.cloud.google.com/gcr/images/istio-release/GLOBAL/app_sidecar_base_ubuntu_bionic@sha256:3101510d3a9a6912158cc5a05378494bff75613f30ce10af30a5ce3bc5f65408/details?tab=info))

- [x] (**Automation step=1**) Update dependencies. This must be done **before branching** so that PRs can be easily backported later. ([done](https://github.com/istio/istio/pull/31932))
  - Check if `github.com/envoyproxy/go-control-plane` dependency needs to be updated (to master?). Ask Kuat.
  - Run the following command in istio/istio `UPDATE_BRANCH=master ./bin/update_deps.sh; make gen`
  - [x] Merge PR in istio/istio. Wait for it to complete. 

- [x]  (**Automation step=2**)  (new step because we are waiting on prior change to master before branching) Create a `release-1.10` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.10 && git push --set-upstream origin release-1.10)`.
  - [x] istio/istio 
  - [x] istio/pkg
  - [x] istio/api 
  - [x] istio/proxy
  - [x] istio/envoy 
  - [x] istio/client-go 
  - [x] istio/tools
  - [x] istio/common-files 
  - [x] istio/gogo-genproto 
  - [x] istio/release-builder 
  - Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
  - [x] No PRs to merge as the new branches were created by automation

- [x] Set up branch protection. Modify prow/config.yaml in test-infra to add release manages as owners for a branch. Ex: https://github.com/istio/test-infra/pull/3122. 

- [ ] (not automated) Adjust istio/proxy to correct version of istio/envoy. Requires istio/envoy to be set up for new release.

- [x] (**Automation step=3**) (doesn't work locally, appears to need credential to add a tag to an existing build-tools image)(new step because this might need to be done separately) Set up prow on release branches `go run generate.go branch 1.10` (Note: Needed to run postsubmit in next step) (Contact Googler or ping in #test-and-release slack channel for help).

- [x] (**Automation step=4**) (new step since we want the automation from prior step to actually create the image after PR merges)
  - [x] Updates istio/tools to build new release-1.10 build image (update BRANCH in docker/build-tools/build-and-push.sh. PR postsubmit will create new container images whose name will be used in the next step)  eg: https://github.com/istio/tools/pull/1397
  - Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_  (but not in common-files). The next step will cause the prow automation to actually call `make update-common` in these repos to do the actual `make update-common` against the new common-files release branch
    - [x] istio/common-files - skipped. Covered in next step
    - [x] istio/istio 
    - [x] istio/pkg 
    - [x] istio/api
    - [x] istio/envoy 
    - [x] istio/client-go
    - [x] istio/gogo-genproto
    - [x] istio/proxy 
    - [x] istio/release-builder 
    - [x] istio/tools 
  - Update `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.10 && git checkout -b release-1.10-codeowners && echo '* @istio/release-managers-1-10' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.10' && git push --set-upstream origin release-1.10-codeowners)`.
    - [x] istio/istio 
    - [x] istio/pkg 
    - [x] istio/api 
    - [x] istio/envoy
    - [x] istio/proxy
    - [x] istio/client-go 
    - [x] istio/tools
    - [x] istio/common-files
    - [x] istio/gogo-genproto 
    - [x] istio/release-builder
  - [ ] Stop publishing `latest` tags
  - Update istio/release-builder branch changes from `master` to new release in build.sh, publish.sh and manifests. Eg: https://github.com/istio/release-builder/pull/522
- [x] Merge PRs from STEP 4. Wait for the new build images to be created at https://gcr.io/istio-testing/build-tools.

- [x] (**Automation step=5**) (new step since we need image from prior step) Update istio/common-files to set release-1.10 build image (Update the UPDATE_BRANCH in files/common/Makefile.common.mk to be the new release name, and IMAGE_VERSION in files/common/scripts/setup_env.sh  to be the new build image from prior step (found at https://gcr.io/istio-testing/build-tools)
- [x] Merge PR from STEP 5. Wait until step 5 PR merges and all the postsubmit generated PRs (to update common files in repos) merge.

Additional steps that still need automation (if possible)
- [x] Add new label: cherrypick/release-1.10. eg: https://github.com/istio/bots/pull/325 Also, create a 1.11 milestone: https://github.com/istio/bots/pull/328

- [x] Bump master to version 1.11 
  - [x] Update istio: 1.10-dev to 1.11-dev, 1.10-dev.x to 1.11-dev.0, 1.10 to 1.11, 1.10.0 to 1.11.0 (Eg: https://github.com/istio/istio/pull/30069)
- [x] Ask istio.io team to run job to update to use the 1.10 branch
- [ ] Run the long-running tests on the dev builds (owner: )
- [x] Send an announcement on Discuss
- [ ] Add release lock for release 1.10 in master branch of API repo. See https://github.com/istio/api/blob/master/scripts/check-release-locks.md
- [ ] Publish a beta release 
  - [ ] Trigger a 1.10 alpha build
  - [ ] Publish a 1.10 alpha release

**Comment by brian-avery** [comment]
@Monkeyanator I think this is done?

**Comment by Monkeyanator** [comment]
Yep should be done
