### ISSUE TITLE
Possible bug in trace sampling configuration handling

### ISSUE THREAD

**Issue by phsiao** [istio/istio#31629]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

While browsing through the code, I found this to be odd:

https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L1740-L1742

```
		if sampling > 100.0 {
			sampling = 1.0
		}
```

I think it should be sampling = 100.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

N/A

**Steps to reproduce the bug**

N/A

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

N/A

**How was Istio installed?**

N/A

**Environment where the bug was observed (cloud vendor, OS, etc)**

N/A

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
cc @linsun who made the change: https://github.com/istio/istio/pull/29508
