### ISSUE TITLE
Is there any possibility that we support XDS static cluster

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#31670]
istiod auto generates several static xds cluster like xds-grpc, envoy_accesslog_service, zipkin and so on, but seems there is no way we can add static cluster dynamically, using envoyfilter or serviceEntry.

background:
some envoy feature need static cluster, like access log service: https://github.com/envoyproxy/envoy/issues/3660
we want enable access log service for some of pod, but not all(so we disabled enableEnvoyAccessLogService in mesh global config). then we tried use envoyfilter to add access log config to LDS, it's ok, but we can not find a way to generate the static cluster.

Is there any possibility that we support generate XDS static cluster?

**Comment by bianpengyuan** [comment]
See https://github.com/istio/istio/tree/master/samples/custom-bootstrap

**Comment by zhongfox** [comment]
> See https://github.com/istio/istio/tree/master/samples/custom-bootstrap

this works for me, thank you @bianpengyuan, close this.
