### ISSUE TITLE
expose more xDS statistics in istio-proxy stats api

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#31727]
I notice there are some XDS statistics in envoy doc:
https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/mgmt_server#xds-subscription-statistics
we want compare metric "config_reload" or "update_success",  after using istio sidecar CRD.

in istio proxy (127.0.0.1:15090/stats/prometheus), there are some related metrics:
envoy_cluster_manager_cds_update_success
envoy_listener_manager_lds_update_success
 
but not sure why there is no eds_update_success, or total updated count (like  envoy "config_reload")
is there any probability we add "config_reload"  or "update_success" to istio proxy metric?

(I know there is total pushes count in isitod metric, but I want get the metric for one specific sidecar)

**Comment by howardjohn** [comment]
cc @bianpengyuan @ramaraochavali

**Comment by bianpengyuan** [comment]
Yeah make sense to have more control path stats created. Do you have a list of stats prefix in mind? We can simply add them here https://github.com/istio/istio/blob/5e91f26e0660dc699e1b9f7451923477328658ab/pkg/bootstrap/config.go#L50

**Comment by zhongfox** [comment]
> Yeah make sense to have more control path stats created. Do you have a list of stats prefix in mind? We can simply add them here
> 
> https://github.com/istio/istio/blob/5e91f26e0660dc699e1b9f7451923477328658ab/pkg/bootstrap/config.go#L50

thanks for the code guide, the metric I want are:
config_reload
update_success

so I tried update proxy code:
```
requiredEnvoyStatsMatcherInclusionPrefixes = "cluster_manager,listener_manager,server,cluster.xds-grpc,wasm,config_reload,update"
```
I  added 2 more prefix: `config_reload,update`
and there are several new metrics show in stats/prometheus:

```
# TYPE envoy_update_attempt counter
envoy_update_attempt{} 4

# TYPE envoy_update_failure counter
envoy_update_failure{} 0

# TYPE envoy_update_rejected counter
envoy_update_rejected{} 0

# TYPE envoy_update_success counter
envoy_update_success{} 2
```

but I can not find the metric `config_reload`, Im using istio proxy 1.8.2.
another issue is: after I scale up/down some endpoints in mesh, the new metric envoy_update_attempt, envoy_update_success has no change(without any sidecar CRD),I expect the 2 metrics should increase after endpoints scale.

can you please give me some guide, summary：
1. why config_reload not show
2. why envoy_update_attempt, envoy_update_success  not change.

**Comment by bianpengyuan** [comment]
You can examine all envoy metrics by adding `sidecar.istio.io/statsInclusionRegexps: .*` annotation to your workload.

Looks like `update_attempt` and `config_reload` etc are stats suffixes.

`update_attempt` seems to be generated both at aggregated resource manager level and per resource level, which is actually concerning because of increased envoy resource consumption and prometheus scraping cost. I think with the default config, we'd only want to have aggregated stats for resource management. You can customize your usage to by default expose more stats with `ProxyStatsMatcher` at mesh config: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyStatsMatcher

`config_reload` seems to be only collected at listener & rds, but not other resources. I looked at envoy code a bit, and looks like it is only meant for rds and dynamic filter reload.

**Comment by zhongfox** [comment]
thanks for the guide @bianpengyuan 

I tried ProxyConfig.ProxyStatsMatcher inclusionSuffixes, and get more metrics I need, like
envoy_cluster_update_attempt{cluster_name="outbound|7000||XXX"}
envoy_cluster_update_success{cluster_name="outbound|7000||XXX"} 
these metrics are useful.

also I found the metric `envoy_cluster_manager_cluster_updated` which I missed at first. 
according to https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats this is "Total cluster updates".
I verified the istio Sidecar CRD will reduce the `envoy_cluster_manager_cluster_updated` , so I think this metric can reflect the  count of envoy config/xds reload.

**Comment by bianpengyuan** [comment]
> I tried ProxyConfig.ProxyStatsMatcher inclusionSuffixes, and get more metrics I need, like
envoy_cluster_update_attempt{cluster_name="outbound|7000||XXX"}
envoy_cluster_update_success{cluster_name="outbound|7000||XXX"}
these metrics are useful.

Yeah, but I don't think we'd want to expose them by default.

> also I found the metric envoy_cluster_manager_cluster_updated which I missed at first.
according to https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats this is "Total cluster updates".
I verified the istio Sidecar CRD will reduce the envoy_cluster_manager_cluster_updated , so I think this metric can reflect the count of envoy config/xds reload (when eds/cds scale).

Ok, so I guess there is no extra aggregated non-per-resource stats that we can generate?

**Comment by zhongfox** [comment]
yeah, this meet my needs. I will close it as it's resolved.
