### ISSUE TITLE
Undocumented k8s secret format/handling for mTLS

### ISSUE THREAD

**Issue by freegroup** [istio/istio#31725]
from the istio documentation I got this 
( https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ at the bottom of the page )

---

Istio supports reading a few different Secret formats, to support integration with various tools such as cert-manager:

 - A TLS Secret with keys `tls.key` and `tls.crt`, as described above. For mutual TLS, a `ca.crt` key can be used.  
 - A generic Secret with keys `key` and `cert`. For mutual TLS, a `cacert` key can be used.
 - A generic Secret with keys `key` and `cert`. For mutual TLS, a separate generic Secret named `<secret>-cacert`, with a cacert key. For example, httpbin-credential has key and cert, and httpbin-credential-cacert has cacert.
----

But is seems that there is a 4th version possible

A generic Secret with keys `tls.key` and `tls.crt`. For mutual TLS, a separate generic Secret named `-cacert`, with a `cacert` key or a `ca.crt` key. For example, `httpbin-credential` has tls.key and tls.crt, and `httpbin-credential-cacert` has ca.crt

Coding
See https://github.com/istio/istio/blob/master/pilot/pkg/secrets/kube/secrets.go#L181-L227
and https://github.com/istio/istio/blob/master/pilot/pkg/secrets/kube/secrets_test.go#L110-L111

**Question**: is the documentation for this feature missing and it is official supported or is this an unwanted hidden feature?

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by howardjohn** [comment]
Yeah good call, there are actually 4. 2 key formats X 2 ways to store the ca cert (inline or separate secret). We should update the docs, and make sure the tests cover all of them

**Comment by freegroup** [comment]
perfect - any plans when the doc is available?   :-)
(as a comment in this ticket would help for the first time)

**Comment by freegroup** [comment]
adding a new secret side by side do not work.

original tls-secret **gateway-sms-tls**:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
  name: gateway-sms-tls
  namespace: istio-system
data:
  tls.crt: LS0tLS1CRU...................RFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0E.................LS0tCg==

```

Before I patched my secret by adding a new key to an existing secret - which is working *fine*
```
kubectl patch secret -n istio-system gateway-sms-tls -p="{\"data\":{\"ca.crt\": \"`cat ca.crt  | base64`\"}}"

```

Now i try to use the side-by-side approach but it seems not to work:
```
kubectl create secret generic -n istio-system gateway-sms-tls-cacert --from-literal=ca.crt=\"`cat ca.crt  | base64`\"

```

Are the secret and the key name correct - aren't they?

**Comment by freegroup** [comment]
Hi,

for some reason the CA certificate is "invalid". Unfortunately I have no idea whats the reason for.
```
istioctl proxy-config secret istio-ingressgateway-56d9b7fdb-zwzqz.istio-system
RESOURCE NAME                           TYPE           STATUS     VALID CERT     SERIAL NUMBER                                  NOT AFTER                NOT BEFORE
default                                 Cert Chain     ACTIVE     true           108812331135335491536489580615374087759        2021-04-30T15:03:07Z     2021-04-29T15:03:07Z
kubernetes://gateway-sms-tls            Cert Chain     ACTIVE     true           348453890058408935203594957711249107172809     2021-07-23T20:19:15Z     2021-04-24T20:19:15Z
kubernetes://gateway-ui-tls             Cert Chain     ACTIVE     true           432651121583645156125280465978859729181660     2021-06-05T10:00:55Z     2021-03-07T10:00:55Z
kubernetes://osb-tls                    Cert Chain     ACTIVE     true           337268053773523349460147441661034375808584     2021-07-13T13:08:49Z     2021-04-14T13:08:49Z
ROOTCA                                  CA             ACTIVE     true           280912645485316032978209874125524080633        2031-02-20T11:45:19Z     2021-02-22T11:45:19Z
kubernetes://gateway-sms-tls-cacert                    ACTIVE     false                                                                                  
```

any help is welcome :-)

**Comment by freegroup** [comment]
sorry for the noise. double base64 encoded in the secret. "-cacert" ist working fine....but not documented ;-)

correct command to create the secret

```
kubectl create secret generic -n istio-system gateway-sms-tls-cacert "--from-literal=ca.crt=`cat ca.crt`"
```

**Comment by jonathanzhang02** [comment]
Hi @howardjohn 

> A generic Secret with keys tls.key and tls.crt. For mutual TLS, a separate generic Secret named -cacert, with a cacert key or a ca.crt key.

Could you please help clarify where is this format of generic (opaque) Secret documented?  I could not seem to find in current document:

<img width="906" height="334" alt="Image" src="https://github.com/user-attachments/assets/6b64bf30-6387-4454-a802-1570bbc7fe63" />

BTW,  this also affects the documentation for DestinationRule's "credentialName" parameter in https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings
