### ISSUE TITLE
Donot output istiod tls key to file system

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#31722]
Currently, the self signed key/cert pairs are saved to `/var/run/secrets/istio-dns`. This is not secure and I think we can save the key/cert to k8s secret. 

It seems CaCerts in `./etc/cacerts` can also be avoided.

**Comment by howardjohn** [comment]
I don't think we need to write it anywhere, can't we just store it in memory? Its not shared between instances

**Comment by hzxuzhonghu** [comment]
Yeah, each istiod signs its own dns certs.

**Comment by hzxuzhonghu** [comment]
For cacerts we used in multicluster installation, it is mounted to all the istiod instances.

**Comment by hzxuzhonghu** [comment]
This is done
