### ISSUE TITLE
Istioctl Install - Offline Install/ Behind Proxy

### ISSUE THREAD

**Issue by ParthibanSG** [istio/istio#31739]
**Describe the feature request**

I would like to know if istio can be installed in a offline manner since we don't have direct internet connection from our linux servers. Istio is part of an application that we use and application install fails during istioctl install command

**Describe alternatives you've considered**

It is the similar case like docker client and I was able to add proxy details to docker client to get docker images. In a similar fashion, I am expecting istio to take up proxy details either from linux environment or from the k3s service. I also tried to create custom manifest to point the images to local docker registry but still istioctl is looking for the image in docker hub

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Istio Version: 1.6 (I cannot upgrade to higher version of istioctl since it is a part of the application itself)
Istio is being installed in a k3s platform

**Error from Kubernetes:**

istio-system     2m36s       Normal    BackOff                        pod/istiod-5d4c5c69d-s44m7                     Back-off pulling image "docker.io/istio/pilot:1.6.10"
istio-system     12m         Warning   Failed                         pod/istiod-5d4c5c69d-s44m7                     Error: ImagePullBackOff

**Comment by howardjohn** [comment]
Yes, you can override the hub to a local one with `--set hub=foo`

**Comment by howardjohn** [comment]
Closing as this is answered
