### ISSUE TITLE
Allow slash characters in env variable values passed to injector

### ISSUE THREAD

**Issue by frankbu** [istio/istio#31732]
**Describe the feature request**

The [parseInjectEnvs() function](https://github.com/istio/istio/blob/fb35b6c9381436aa8b2b35cd964e302c37006b82/pkg/kube/inject/webhook.go#L838) in webhook.go uses / characters to separate keys and values for environment variables passed through the injector webhook URL path. This doesn't work if the value of an env variable includes / characters. For example, it's not possible to set an environment variable like: `FOO_LOCATION=/path/to/foo`.

This should be possible and is also needed in the external control plane multicluster configuration if the [remote cluster name includes / characters](https://github.com/istio/istio.io/pull/9280/files#r602588367).

Perhaps this could be fixed by accepting values that are urlencoded (e.g., `"/inject/FOO_LOCATION/%2Fpath%2Fto%2Ffoo"`) or some similar encoding?

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by litong01** [comment]
Since the character slash is used as separators, if a value needs that character, naturally it should be escaped, seems to me using url encoded slash is a good idea, could be easily detected in the value by replacing url encoded slash `%2F` like the following:

```
newEnvs[env] = strings.Replace(res[i+1], "%2F", "/", -1)
```

The only drawback is that %2f would not be replaced unless do another replace or regular expression based replacement (seems a bit over kill for this issue), a bit of performance hit.

**Comment by litong01** [comment]
The PR can contain the one line patch, a new test case and a bit of document somewhere indicating this small new capability.

**Comment by litong01** [comment]
Since the character slash is used as separators, if a value needs that character, naturally it should be escaped, seems to me using url encoded slash is a good idea, could be easily detected in the value by replacing the %2F

**Comment by ericvn** [comment]
Closed by https://github.com/istio/istio/pull/31797
