### ISSUE TITLE
gateway-apis: spec.tls in HTTPRoute is not supported

### ISSUE THREAD

**Issue by nak3** [istio/istio#31747]
**Bug description**

- `spec.tls` in HTTPRoute is not supported.
- As per comment code below, gateway's `tls.routeOverride` is not supported as well.

https://github.com/istio/istio/blob/75974d56a327e9857f36d17151b2ef3146745b92/pilot/pkg/config/kube/gateway/conversion.go#L776-L777

[X] Networking

**Expected behavior**

- HTTPRoute's tls is supported.

**Comment by howardjohn** [comment]
This needs some resolution on API side: https://github.com/kubernetes-sigs/gateway-api/issues/577

Specifically, its not clear what `hostnames` refer to what. In Istio, Gateway hostname is SNI and VirtualService hostname is Host header. In gateway, it appears the same, but then suddenly if you have a tls config in HTTPRoute it becomes SNI? I think its inconsistent/unclear right now

**Comment by howardjohn** [comment]
For net-istio its doing `rewrite: authority: xyz`. Maybe we need to make `set :authority` convert to that

**Comment by nak3** [comment]
Reopen. I think it is not implemented yet.
