### ISSUE TITLE
istiod not push config to sidecar

### ISSUE THREAD

**Issue by debbyku** [istio/istio#31755]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We have istio injected pod running for 14 days.   Until few days ago we did a deployment with a new authorization policy and we found that istiod did not push the updated config to the sidecar. We also found that there was no config pushed to the sidecar from istiod for 10 days.  As it has happened for days and we have lost relevant log for istiod.  

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Istiod pushes updated configs to sidecar 

**Steps to reproduce the bug**
we cannot reproduce it

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.3 (43 proxies)

**How was Istio installed?**
spec:
  components:
    cni:
      enabled: true
    egressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: PILOT_CERT_PROVIDER
          value: kubernetes
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: dev-svc-cluster
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: https
            port: 443
            targetPort: 8443
          - name: mtls
            port: 15443
            targetPort: 15443
          - name: tcp-istiod
            port: 15012
            targetPort: 15012
          - name: tcp-webhook
            port: 15017
            targetPort: 15017
          - name: http2
            port: 80
            targetPort: 8080
          - name: ssh
            port: 2222
            targetPort: 2222
          - name: http-web
            port: 8008
            targetPort: 8008
          - name: tcp-smf
            port: 55555
            targetPort: 55555
          - name: tcp-amqp
            port: 5672
            targetPort: 5672
          - name: tcp-mqtt
            port: 1883
            targetPort: 1883
          - name: tcp-rest
            port: 9000
            targetPort: 9000
          - name: http-semptls
            port: 1943
            targetPort: 1943
          - name: tcp-smftls
            port: 55443
            targetPort: 55443
          - name: http-webtls
            port: 1443
            targetPort: 1443
          - name: tcp-amqptls
            port: 5671
            targetPort: 5671
          - name: tcp-mqtttls
            port: 8883
            targetPort: 8883
          - name: tcp-mqttws
            port: 8000
            targetPort: 8000
           - name: tcp-resttls
            port: 9443
            targetPort: 9443
      label:
        topology.istio.io/network: dev-svc-cluster
      name: istio-ingressgateway
    pilot:
      k8s:
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PILOT_CERT_PROVIDER
          value: kubernetes
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
  hub: devjcr01.corpdev.hkjc.com/sp22-docker-repo/production/istio-system/istio
  profile: default
  values:
    base:
      enableCRDTemplates: false
    cni:
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
      istio-ingressgateway:
        autoscaleEnabled: true
    global:
      defaultResources:
        requests:
          cpu: 10m
          memory: 128Mi
      imagePullSecrets:
      - platform-tool-docker-repo
      meshID: mesh-DEV1
      multiCluster:
        clusterName: dev-svc-cluster
      network: dev-svc-cluster
      pilotCertProvider: kubernetes
      podDNSSearchNamespaces:
      - global
      proxy:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
      proxy_init:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
          ISTIO_META_DNS_CAPTURE: "true"
        tracing:
          custom_tags:
            cluster:
              literal:
                value: dev-svc-cluster
          sampling: 50
          tlsSettings:
            mode: DISABLE
          zipkin:
            address: 10.194.177.4:9411
      enableTracing: true
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
    pilot:
      autoscaleMin: 2

**Environment where the bug was observed (cloud vendor, OS, etc)**
4.19.129-1.ph3-esx #1-photon SMP Tue Jun 30 02:18:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
![log](https://user-images.githubusercontent.com/32248438/112797964-c805fc00-909e-11eb-9f27-53505a0836eb.png)

**Comment by howardjohn** [comment]
So the pod had no logs in the proxy for these 10 days?

**Comment by debbyku** [comment]
It showed access log in istio-proxy container. However, I couldn't find any
xdsproxy related log.

And in istiod, I couldn't find any xds push log for such sidecar in last 5
day's log. all other istiod log has been housekept.


在 2021年3月30日週二 01:15，John Howard ***@***.***> 寫道：

**Comment by hzxuzhonghu** [comment]
Is there any log related to ADS stream connect/disconnect?

**Comment by debbyku** [comment]
I can only see the xds log in the sidecar in the attached pic. that log is
on Mar 16. 10 days before I discovered the issue.

在 2021年3月31日週三 17:08，Zhonghu Xu ***@***.***> 寫道：

**Comment by hzxuzhonghu** [comment]
I guess the sidecar can not connect to istiod, can you enter the sidecar and test the network manually?

**Comment by debbyku** [comment]
Sorry, the pod has been restarted. Can't do any investigation on it and I
cannot reproduce it. Just wonder any log pattern I can monitor for such
error. I can't find any error log about it.

Thanks.

在 2021年4月1日週四 09:21，Zhonghu Xu ***@***.***> 寫道：
