### ISSUE TITLE
Istio telemetry component always reports that CPU load is too high

### ISSUE THREAD

**Issue by yuanyiran** [istio/istio#31751]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Extensions and Telemetry

**Affected features (please put an X in all that apply)**

[ ] Physical machine

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istio 1.2.2
kubernetes 1.14.2
helm 2.16.0

**How was Istio installed?**

helm install istio 1.2.2

**Environment where bug was observed (cloud vendor, OS, etc)**

Local physical machine kubernetes cluster istio no cluster deployment

**error describe**

I am using Prometheus to monitor the CPU utilization of pod components. The monitoring expression is as follows:
`
sum by (instance,namespace,pod_name)(rate(container_cpu_usage_seconds_total{image!="",namespace=~"kube-system.*|istio-system.*"}[5m] ) ) * 100
`
Recently, I have been receiving the alarm that the CPU utilization rate of istio telemetry component is too high. The alarm is as follows

![image](https://user-images.githubusercontent.com/64528937/112777603-3635c900-9075-11eb-8339-b48646762fa7.png)

But I don't know how to find out why the CPU of this component is too high. Is it because I have too many visits that I report too much data? Here, I ask for your help.

At present, the resources value of istio telemetry component is:
`
"resources": {
          "limits": {
            "cpu": "4800m",
            "memory": "4G"
          },
          "requests": {
            "cpu": "50m",
            "memory": "100Mi"
          }
        },
`
Can I solve this problem by adjusting the CPU limit of limits?

**Comment by bianpengyuan** [comment]
You can probably give istio-telemetry more instances, and distribute the load.

Mixer based istio-telemetry is deprecated for very long time, and 1.2.2 was way out of support window. Please consider upgrading to telemetry v2 and newer version of Istio.

**Comment by yuanyiran** [comment]
So the root cause is that I call too many services, resulting in too much telemetry data reported, so the CPU load is too high, right？

**Comment by yuanyiran** [comment]
In istio environment, I have modified the istio telemetry component, removed the expiration time of reported data, and added telemetry data at API request level. Therefore, is it the statistics of API request level data that causes excessive CPU load of istio telemetry component? Will it cause too much memory?
@bianpengyuan

**Comment by bianpengyuan** [comment]
lack of expiry and dimension with large number of cardinality (like API request label) are going to cause high memory usage, but should not affect CPU. Likely it is just too many reports that current number of telemetry instance cannot handle properly. HPA would be an easy way to mitigate.

**Comment by bianpengyuan** [comment]
I am going to close this issue since istio-telemetry and 1.2.x are way out of support window. thanks!

**Comment by yuanyiran** [comment]
Thank you very much for your answer. And What is HPA you said?
@bianpengyuan

**Comment by yuanyiran** [comment]
@bianpengyuan Hello, I want to ask you, I am currently kubernetes is 1.19.9 version, so which version of isio should I use, suitable for production level?
