### ISSUE TITLE
Adding CNI integration test suite

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#31765]
Propose adding CNI test suites based on the existing pilot and security suite:

```
integ-pilot-k8s-cni-tests_istio
integ-security-k8s-cni-tests_istio
```

This will be useful to catch tricky CNI bugs, make sure feature parity with istio-init, and give us confidence for beta graduation.

**Comment by bianpengyuan** [comment]
Some experiment run: https://github.com/istio/istio/pull/31718

cc @therealmitchconnors @howardjohn @nmittler @stevenctl for comment.

**Comment by howardjohn** [comment]
Should we do what we do for the k8s version tests? Which is run *all* test suites? the slow test time is fine for postsubmit, its only like an hour anyways

**Comment by bianpengyuan** [comment]
Yeah, that is exactly what I am planning to do.

**Comment by bianpengyuan** [comment]
This is done.
