### ISSUE TITLE
Introduce a DNS-based on-demand loading.

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#31785]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Introduce a DNS-based on-demand loading.

Although envoy has plans for on-demand XDS, resources such as linstener still seem to be unable to load on demand.

Therefore, we can discover service dependencies through DNS Proxy in Pilot-Agent.

For example, when the application `reviews` access `ratings`, the application will first initiate a dns query of ratings.default.svc.cluster.local.

Pilot-Agent can record this domain name and send these domain names to ISTIOD through XDS (this requires a new resource type, EgressScope).

For simplicity, we create a new memory store in istiod to store these dependencies.

We can reuse the Sidecar type, but use a new GVK, such as networking.internal.istio.io for group.

WorkloadSelector can use app=xxx by default, or you can customize the labels  by configuring a new environment variable ISTIO_META_SHARED_DNS_EGRESS_SCOPE .

These Sidecar configurations can be merged when PushContext initializes SidecarScopes.

![image](https://user-images.githubusercontent.com/2241753/112957059-a75ba600-9173-11eb-9c83-d33e4bc95895.png)

( I'll create a pull request later. )

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by cocotyty** [comment]
> I think this is a great idea, but I am not sure it makes sense as is with the plans for on demand XDS discussed in [#31488 (comment)](https://github.com/istio/istio/issues/31488#issuecomment-800384318). Likely we can utilize the DNS as a hint like described, but instead of updating SidecarScope we would pre-push the cluster using on demand CDS/EDS. So similar end result, but slightly different methodology

I think we still need on demand LDS / RDS .

**Comment by bianpengyuan** [comment]
> I think we still need on demand LDS / RDS .

Curious, how do you plan to make ondemand LDS/RDS work without Envoy support? Just let the initial request fail?
