### ISSUE TITLE
No Services in Jaeger UI if install it with Helm

### ISSUE THREAD

**Issue by setevoy2** [istio/istio#31802]
**Bug description**

After installing Jaeger via its [Helm chart](https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger) can't see any Service, only `jaeger-query` in the Jaeger UI.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

A test application must be available in the Service.

**Steps to reproduce the bug**

Install Jaeger via Helm-chart with Zipkin port enabled for the Collector:

```
      collector:
        service:
          zipkin:
            port: 9411
```
Update Istio with Zipkin address:

```
      global:
        tracer:
          zipkin:
            address: "jaeger-collector.istio-system.svc.cluster.local:9411"
```
Confirm Jaeger Collector have port opened:

```
$ kubectl -n istio-system get svc jaeger-collector
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
jaeger-collector   ClusterIP   172.20.246.211   <none>        14250/TCP,14268/TCP,9411/TCP,14269/TCP   23s
```

And from its Pod's logs:

```
{"level":"info","ts":1617168477.7440195,"caller":"server/zipkin.go:52","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"}
```

Still, if install Jaeger via `samples/addons/jaeger.yaml`, and configure Istio for the `zipkin.istio-system:9411` Zipkin address - everything is working as expected.

Seems to be some connectivity issue between Istio and Jaeger collector when installing via Helm-chart, but I'm able to access the `jaeger-collector.istio-system.svc.cluster.local:9411` with `curl` from pods in the cluster.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (3 proxies)
```

**How was Istio installed?**

Helm chart

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by bianpengyuan** [comment]
To identify the issue, you can enable and collect extra log for Envoy trace system: `k exec your-app-pod -c istio-proxy -- curl -X POST localhost:15000/logging?tracing=trace` and to turn it off `k exec your-app-pod -c istio-proxy -- curl -X POST localhost:15000/logging?tracing=warning`

**Comment by bianpengyuan** [comment]
Could you provide proxy config dump? Especially the tracing part at bootstrap.

Also there could be some error from tracing system during envoy start up. It would be great if you can add the following annotation to your app pod and restart it see if there is anything suspicious:

```
sidecar.istio.io/componentLogLevel: tracing:trace
```
