### ISSUE TITLE
Investigate initial fetch timeouts

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31818]
Seeing errors like `initial fetch timed out for type.googleapis.com/envoy.config.listener.v3.Listener`

Also saw EDS. I got the EDS from massive config freezing my computer. We shouldn't have timeout for listener?

**Comment by howardjohn** [comment]
Looks like this was intended in https://github.com/istio/istio/pull/30948/. What I don't know is why we wanted to time out - seems like we would always want to wait indefinitely for things we know must exists (everything but SDS)? Especially listener - can we really start up without fetching LDS? That seems concerning; the PR did not change that part though as it is in the bootstrap

cc @ramaraochavali

**Comment by SpecialYang** [comment]
It is very necessary to explicitly set initialFetchTimeout to 0 to prevent Envoy from obtaining imperfect configurations.
