### ISSUE TITLE
tcp filter

### ISSUE THREAD

**Issue by rtttech** [istio/istio#31811]
is it possible to write a tcp(not http) filter that can parse the content of tcp stream and route accordingly?

**Comment by bianpengyuan** [comment]
It is possible, but going to be quite complex. See https://github.com/envoyproxy/envoy/tree/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/source/extensions/filters/network for some example such as thrift proxy, dubbo proxy etc. Thanks!
