### ISSUE TITLE
mtls not working when using traefik as ingress

### ISSUE THREAD

**Issue by kutsav** [istio/istio#31829]
I am using traefik as an ingress for the cluster and sidecar injection is also enabled for it, there are few ingress defined which point to a service in another namespace. 
I enabled mtls in the cluster, it works fine for services in same namespace, but traffic between traefik pod and the service mentioned in ingress is not getting encrypted, rather it shows in kiali that traffic is going to the target service via "PassThroughCluster".

Expected behaviour was traffic between traefik and the target ingress service should also be encrpyted if they are part of the mesh but that is not the case

Istio version in 1.8.1

Will appreciate help on this.

**Comment by bianpengyuan** [comment]
Not familiar with traefik, but curious does it forward request using `pod_ip:target_port`? Is the destination service mentioned in the ingress have different port and target port?

**Comment by kutsav** [comment]
The target port is same, and the request is also going through, only thing is its not getting encrpyted.

**Comment by bianpengyuan** [comment]
Yeah need to understand why it passes through. Typically it is because the request are sent with pod port instead of service port, which is not supported by Istio. Can you enable trace level log and it should tell why passthrough cluster is chosen: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2 set `--level=trace`

**Comment by kutsav** [comment]
Ok, let me check the logs and come back

**Comment by kutsav** [comment]
@bianpengyuan I see the following log on traefik's sidecar:

`2021-03-31T18:37:23.879162Z	debug	envoy router	[C2237][S8260567670040239438] cluster 'PassthroughCluster' match for URL '***<removed_for_this_issue>***'`

requests from ingress service to target service for that url are being sent using service port only

**Comment by bianpengyuan** [comment]
If you check config dump of your proxy, can you see the wanted service domain in route named as "8080"? https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2  has information about how to get config dump.

**Comment by kutsav** [comment]
I can see following in config dump:
```
          {
           "name": "envoy.filters.network.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
            "stat_prefix": "inbound_0.0.0.0_8080",
            "route_config": {
             "name": "inbound|8080||",
             "virtual_hosts": [
              {
               "name": "inbound|http|8080",
               "domains": [
                "*"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "cluster": "inbound|8080||",
                  "timeout": "0s",
                  "max_stream_duration": {
                   "max_stream_duration": "0s"
                  }
                 },
                 "decorator": {
                  "operation": "svc_name.namespace.svc.cluster.local:8080/*"
                 },
                 "name": "default"
                }
               ]
              }
             ],
             "validate_clusters": false
            },
```
Is this what you are referring to?

**Comment by bianpengyuan** [comment]
No I am looking for something under `"dynamic_route_configs"`, with name `8080`. Also it would be great if you can share your configuration for ingress and virtual service if any.

**Comment by kutsav** [comment]
vs:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: app
  name: app
  namespace: namespace
spec:
  hosts:
  - app.namespace.svc
  http:
  - route:
    - destination:
        host: app.namespace.svc.cluster.local
```
Ingress:
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: http
    traefik.ingress.kubernetes.io/router.middlewares: regular@file
    traefik.ingress.kubernetes.io/router.priority: "1"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: default
  labels:
    app: regular-ingress
  name: regular-ingress
  namespace: namespace
spec:
  rules:
  - host: '*.somehost.com'
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 8080
        path: /`
        
routes section for that service:
`    {
        "name": "webtier.idcs-data-plane.svc.cluster.local:8990",
        "domains": [
         "app.namespace.svc.cluster.local",
         "app.namespace.svc.cluster.local:8990",
         "app.namespace",
         "app.namespace:8080",
         "app.namespace.svc.cluster",
         "app.namespace.svc.cluster:8080",
         "app.namespace.svc",
         "app.namespace.svc:8080",
         "10.96.64.226",
         "10.96.64.226:8080"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "outbound|8080||app.namespace.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_stream_duration": {
            "max_stream_duration": "0s"
           }
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/idcs-data-plane/virtual-service/webtier"
            }
           }
          },
          "decorator": {
           "operation": "app.namespace.svc.cluster.local:8080/*"
          }
         }
        ],
        "include_request_attempt_count": true
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2021-04-01T08:31:44.548Z"
    },`

**Comment by bianpengyuan** [comment]
What is the host:port that taefik uses when forwarding the request? It should also be part of the trace log. I am wondering why this route rule is not matches.

**Comment by kutsav** [comment]
Traefik uses pod ip to send traffic to the backend. I tried overriding the Host header via traefik for a route by adding svc:port in the value but it caused problems in redirections.

Found this issue mentioning the same problem: https://github.com/istio/istio/issues/19536

is there any way istio can track pod to pod communication?

**Comment by bianpengyuan** [comment]
No it is not possible. The configuration churn due to pod churn will kill the proxies.

**Comment by bianpengyuan** [comment]
I will close this issue since this unlikely will be supported. Please reopen if you think otherwise. Thanks!

**Comment by putharekulu** [comment]
@kutsav Were you able to get traefik working with Istio? In permissive mode all  works fine for me, When i strict mode I get NR filter_chain_not_found in istio logs... I believe this is because traefik is sending traffic on IP:port instead of service:port and istio couldn't find any routes to route the traffic. Any suggestions on what can be done to make this work?
