### ISSUE TITLE
Services Deployed in Istio cannot communicate to external service behind corporate proxy

### ISSUE THREAD

**Issue by anthonyvk** [istio/istio#31820]
**Services Deployed in Istio cannot communicate to external services. The cluster where istio deployed is behind corporate/company proxy. When the company proxy is disabled everything works fine.**

Was using NGINX ingress controller behind corporate proxy, everything was working fine.
Looks like there must be a proxy configuration to be added at istio side (Not sure). But what was working with NGINX ingress controller is not working with Istio.

[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Must be able to connect to External services**

**Steps to reproduce the bug**
- Install Docker Desktop.
- Add proxy to the cluster.
- Install Istio - Ingress, Egress.
- Try communicating to external services.

**Version**
Istio :
client version: 1.9.1
control plane version: 1.9.2
data plane version: 1.9.2 (5 proxies)

Kubectl :
Client Version: v1.18.6
Server Version: v1.17.7

Helm : v3.3.4+ga61ce56

**How was Istio installed?**
Using Helm chart

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal and Docker Desktop.

**Comment by howardjohn** [comment]
Can you give some more info about how the corporate proxy is configured? and what errors you see?

**Comment by anthonyvk** [comment]
The proxy is added in the Windows system settings (machine where docker desktop is running).
And also the proxy is added to the Docker desktop : 

![image](https://user-images.githubusercontent.com/16552837/113290940-ecb4da80-930f-11eb-80b4-bff584333fe8.png)

**Comment by anthonyvk** [comment]
> 
> 
> The proxy is added in the Windows system settings (machine where docker desktop is running).
> And also the proxy is added to the Docker desktop :
> 
> ![image](https://user-images.githubusercontent.com/16552837/113290940-ecb4da80-930f-11eb-80b4-bff584333fe8.png)

I am getting the following error from the application when it trying to connect to external service : 
`502 Bad Gateway: [no body] `

**Comment by anthonyvk** [comment]
any update?

**Comment by anthonyvk** [comment]
Hi team, this is a blocker we are facing. Would be great if anyone would help us in resolving.
