### ISSUE TITLE
istioctl bug-report does not take flags --context and --kubeconfig

### ISSUE THREAD

**Issue by fan309** [istio/istio#31834]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
istioctl bug-report does not take flags --context and --kubeconfig
'istioctl bug-report --context admin-admin@admin --kubeconfig mykube.conf'
the above command should snapshot targeting cluster defined in --context admin-admin@admin in mykube.conf kubeconfig file. But my observation is that the snapshot will still run against to my local kubeconfig context.

https://github.com/istio/istio/blob/master/tools/bug-report/pkg/bugreport/bugreport.go#L113

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
see above.

**Steps to reproduce the bug**
see above

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

$ istioctl version --remote
client version: 1.7.6-asm.1
control plane version: 1.7.3-asm.6
data plane version: 1.7.3-asm.6 (12 proxies)

$ kubectl version --short
Client Version: v1.16.4
Server Version: v1.19.7-gke.1200

**How was Istio installed?**
use istioctl binary

**Environment where the bug was observed (cloud vendor, OS, etc)**
linux

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by kebe7jun** [comment]
already fixed in #31840
