### ISSUE TITLE
Ability to control ISTIO_META_WORKLOAD_NAME for custom resources

### ISSUE THREAD

**Issue by jessesuen** [istio/istio#31854]
**Describe the feature request**

Istio currently infers the workload name of a Pod, based on the following logic in the mutating webhook:
https://github.com/istio/istio/blob/96f8bc126f5cd81cf84f5dd23ffd3b8d66e90ed7/pkg/kube/util.go#L185-L200

From the above logic, the workload name is calculated based on known naming conventions and behaviors of native Kubernetes controllers. For example, a Pods workload name is determined to be the Deployment name if a Pod has a parent ReplicaSet, and has `pod-template-hash` as one of its labels. It then trims the ReplicaSet suffix to infer the Deployment name.

Similarly, if the webhook sees a Pod whose owner is a Job object, it then decides if the true workload name is a CronJob based on if the Job name has a 10-digit suffix.

The above logic does not work for any non-native kubernetes kinds, and so for custom resources, it chooses to use the parent resource as the workload name as a default.

We would like the ability for Istio to support explicit workload names for custom resources, such as an Argo Rollout, and benefit from the same observability metrics that a Deployment object currently receives.

Note that there is an open TODO item to recurse ownership of a pod to determine the workload name:
https://github.com/istio/istio/blob/96f8bc126f5cd81cf84f5dd23ffd3b8d66e90ed7/pkg/kube/util.go#L161
However, I don't see how recursion could be cheaply/easily implemented in the mutating webhook, as it would require multiple API calls to eventually determine the top-level owner.

Instead, of recursing ownership to determine the workload name, an alternative option is that the mutating webhook can look at annotations of the Pod which explicitly set a workload name, and would override the inference behavior currently happening in the istio mutating webhook. This would let custom resource controllers (such as Argo Rollouts), to affect workload names by injecting the annotation to pods, with the understanding that Istio would honor it.

**Describe alternatives you've considered**

I have not been able to find a workaround for this issue, but am open to suggestions

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

https://github.com/argoproj/argo-rollouts/issues/914

**Comment by bianpengyuan** [comment]
A dirty but easy fix is to find any label with `pod-template-hash` in it and trim workload name based on it, but the label named exactly as `pod-template-hash` will always take precedence. Does this work for you?

If this could work, since the whole workload name trimming is already a hack, I think it is reasonable to extend it a bit to support argo use case. @douglas-reid wdyt?

**Comment by jessesuen** [comment]
> A dirty but easy fix is to find any label with pod-template-hash in it and trim workload name based on it, but the label named exactly as pod-template-hash will always take precedence. Does this work for you?

An Argo Rollout actually injects a label `rollouts-pod-template-hash`, which serves the same purpose that `pod-template-hash` does for Deployments. I don't think we'll want to change the behavior of the rollout controller to inject both labels, just as a dirty workaround for this (hopefully temporary) limitation. Furthermore, I don't believe your proposed workaround would actually work, because while we might be able to trick Istio to formulate the proper workload *name*, the workload kind would still be incorrectly inferred as a Deployment, and the workload kind is `Rollout` in our case.

The way I see it, the only options I see for solving this is for custom resources, are:
1. Istio performs a recursive lookup of a Pod's owner until it finds the true top-level object. However, this would be an expensive operation to do as a webhook (without caching), and would introduce additional failure points.
2. Istio would be enhanced to support explicit workload names (i.e. through pod annotations), so that 3rd-party controllers (such as Argo Rollouts), can better integrate with Istio.

**Comment by bianpengyuan** [comment]
I was actually suggesting adjusting Istio code to accommodate your use by looking at any labels with `pod-template-hash`, like in your case, if `pod-template-hash` does not exist, we can fallback to `rollouts-pod-template-hash`. But I see your point, you not only want workload name to be appropriate, but also owner label?

**Comment by jessesuen** [comment]
Hmm, I think I incorrectly assumed that workload kind was somehow significant or perhaps a telemetry tag (e.g. `destination_workload_kind`). But based on code inspection, it does not seem to be the case:
https://github.com/istio/istio/blob/590cdfe6e62fed60e0fa86a341015bbd53a1d42f/pkg/bootstrap/config.go#L145-L177

> But I see your point, you not only want workload name to be appropriate, but also owner label?

I'm not sure the implications (if any) of returning inaccurate type metadata (e.g. returning a Deployment kind when the underlying is really a Rollout). I had just noticed that `GetDeployMetaFromPod()` returns both deploy and type metadata, and so it seemed important to get the type metadata correct. Perhaps you can explain?

**Comment by bianpengyuan** [comment]
Yeah it will only affect `ISTIO_META_OWNER` env variable, which is reflected as destination / source owner metric labels. However we did not set owner label for prometheus metric, only Stackdriver metrics. So that's fine for the argo use case I believe.

**Comment by douglas-reid** [comment]
@jessesuen it sounds like you may not need to address this issue any more?

But, on the off chance that you do, I think we could do with a full rewrite of the logic around "ownership".  There were grand plans around allowing access to workloads, etc., that have morphed and/or disappeared (some replaced with concepts of canonical service, etc.). I'd love to someone take a serious look at what we could improve here.

**Comment by jessesuen** [comment]
> @jessesuen it sounds like you may not need to address this issue any more?

Actually we do still need it, because it's not possible for the rollout controller to "trick" istio in formulating the correct `ISTIO_META_WORKLOAD_NAME`, unless we resorted to injecting a dummy `pod-template-hash` into the pod labels, which is not a hack that we'd be willing to add to the rollout controller.

Based on https://github.com/istio/istio/issues/31854#issuecomment-812244208, I now understand that `ISTIO_META_OWNER` is affected by what `GetDeployMetaFromPod` returns as the owner. So even if Rollout were to inject `pod-template-hash` to the pods, the `ISTIO_META_WORKLOAD_NAME` would still be inaccurate and affect Stackdriver metrics (but not Prometheus).

So the ideal solution would address both `ISTIO_META_WORKLOAD_NAME` and `ISTIO_META_OWNER`. I think a new pod annotation that allowed these values to be set explicitly, such that they were understood/honored by the mutating webhook, would be the most flexible solution to address this, and other 3rd party controllers would be able to leverage the technique.

**Comment by bianpengyuan** [comment]
We don't see other people raising the need before, so adding annotations for this seems to be an overkill. We can add that if that becomes a popular ask. For now, we can have the workaround mentioned at https://github.com/istio/istio/issues/31854#issuecomment-812225369.

**Comment by Yorkerrr** [comment]
@bianpengyuan is any chance that the workaround mentioned in https://github.com/istio/istio/issues/31854#issuecomment-812225369 will be implemented soon? we use ArgoRollout and istio in production and because of the issue istio-workload grafana charts are not convenient to use, since every deployment considered as a separate workload

**Comment by jessesuen** [comment]
> We don't see other people raising the need before, so adding annotations for this seems to be an overkill. We can add that if that becomes a popular ask. For now, we can have the workaround mentioned at #31854 (comment).

I didn't think special case handling in istio codebase would be desired, so I didn't suggest it initially. But given that the workaround would be acceptable, I think I could submit a PR for this.

**Comment by ringerc** [comment]
This issue remains problematic for controllers that deploy `Pod`s directly, without a corresponding conventional kube workload resource as an intermediary.

Amongst other things, it can result in very high accumulated metric cardinality if pods churn quickly, because Istio won't "generalize" source and destination workload names like it does for `Deployment`-managed pods etc. Combined with Istio not expiring unused metric series by default,  I've seen some Envoy sidecars with 100MiB scrape payloads containing 100s of 1000s of samples per scrape.

I'll check whether it can be worked around by providing a custom sidecar template with env-vars injected to override workload identification.

**Comment by ringerc** [comment]
This was fixed by https://github.com/istio/istio/pull/54340, with label

```
service.istio.io/workload-name
```

On prior versions I _think_ it should probably be effective to add a `proxy.istio.io/config` annotation with a payload like

```
proxyMetadata:
  ISTIO_META_WORKLOAD_NAME: overridden_name_here
```

See https://istio.io/latest/docs/reference/config/labels/#ServiceWorkloadName
