### ISSUE TITLE
Release notes tooling can fail if a PR needs to be rebased

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#31851]
**Bug description**
In the [release notes tooling](https://github.com/istio/tools/blob/master/cmd/gen-release-notes/main.go#L246), we check to see if a release note has been added/modified in this PR. This works fine most of the time and lets us track whether release notes have been documented. 

We do this through a git diff command

```
git diff-tree -r --diff-filter=AMR --name-only --relative=releasenotes/notes '4f001b70f61e41df9d3f068a590b1a9c9f9217af' 'd4f88fae62c5b2ae6c12f4e9949b68b46ba5f7e8'
```
The problem here happens if a release note is removed between when a branch is started and it's merged back in: 

1. PR branch is created from master
2. Release note gets removed in another PR that gets merged into master
3. PR gets opened from this PR branch
4. Git command above gets run. It looks for files added/modified/removed from this PR
5. When it compares the currently existing release note (removed in step 2) against the version in master, it finds that the file wasn't added/removed/modified, but also doesn't exist. It errors and the release notes tooling fails.  
6. A rebase of the PR branch should fix this, but it would be nice to not have this problem to begin with.

**Comment by howardjohn** [comment]
I believe https://github.com/istio/istio/issues/31816 is the same, feel free to close that one if so

**Comment by brian-avery** [comment]
Yeah. That's the same. Thanks.
