### ISSUE TITLE
Unable to find global.yaml in version 1.9.0 and above 

### ISSUE THREAD

**Issue by gxp136** [istio/istio#31908]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Unable to find global.yaml for 1.9.0 and above versions

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
unable to find global.yaml in 1.9.0 and above versions. I was able to download from 1.8.0 and 1.7.0 versions 
**Steps to reproduce the bug**
https://github.com/istio/istio/releases/tag/1.9.0
downloading the below file from above link 
 istio-1.9.0-win.zip
but when going to manifests->charts->unable to find global.yaml
![1122](https://user-images.githubusercontent.com/72878486/113618263-6c4eec00-9625-11eb-878a-073f8dc53489.PNG)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
I am using helm3 to install istio base,ingress,control plane

**How was Istio installed?**
using helm 
**Environment where the bug was observed (cloud vendor, OS, etc)**
Installing in gcp cloud
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This is working as intended. global.yaml is no longer needed; values.yaml in each chart contains all options needed per standard helm practices

**Comment by gxp136** [comment]
Hey @howardjohn  Thaks for the reply but this is how i am using for 1.8.1 and before versions without global.yaml how can i run below command  
helm install -n istio-system istio-ingress manifests/charts/gateways/istio-ingress -f manifests/charts/global.yaml

**Comment by howardjohn** [comment]
just remove `-f manifests/charts/global.yaml`
