### ISSUE TITLE
PDB maxUnavailable field cannot be set in Istio operator

### ISSUE THREAD

**Issue by nairb774** [istio/istio#31910]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

NOTE: This is a re-opening of #28748 as it was only closed with a workaround rather than an actual fix.

Currently, it looks like there is no way to set the maxUnavailable field in the PDB for istiod, ingress gateway or egress gateway. The Istio Operator spec allows this setting:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
        k8s:
          podDisruptionBudget:
            maxUnavailable: 1
```

However, in practice, this results in an error:

```
2020-11-10T15:28:46.939281Z	error	installer	PodDisruptionBudget.policy "istio-ingressgateway" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc01e820180), Selector:(*v1.LabelSelector)(0xc01e8201a0), MaxUnavailable:(*intstr.IntOrString)(0xc01e8201c0)}: minAvailable and maxUnavailable cannot be both set
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The PDB as configured would work correctly _without_ additional patching or workarounds.

**Steps to reproduce the bug**

Apply the yaml above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.9.1
control plane version: 1.8.2
data plane version: 1.8.2 (74 proxies)
```

**How was Istio installed?**

Using the 1.8.2 operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @morvencao

**Comment by ostromart** [comment]
Seems like we need a special handling for this use case: if maxUnavailable is set, we must unset minAvailable. minAvailable is coming from default.yaml and is needed.

**Comment by morvencao** [comment]
Not sure if special handling is a good idea.

At the same time, I did some other attempts, still can't resolve it perfectly. Currently we use strategic merge patch for these k8s settings overlay, but the problem with strategic merge patch is that it depends too much on the the value of the `patchStrategy` key in a field tag in the Kubernetes source code. For example, the `maxUnavailable` and  `minAvailable` are actually exclusive in the server side, but we can't handle it in the client side with strategic merge patch.

**Comment by litong01** [comment]
@morvencao I think that strategic merge can work only when the user's intention is clear, in this case, user wants to set maxUnavailable but our default chart template has minAvailable hard coded, that is, regardless if a user sets maxUnavailable or not, minAvailable will be present, which causes conflict when reaches k8s, and k8s would not know what the user's intention is. The solution is to remove the minAvailable when maxUnavailable is present and also to make sure minAvailable will be 1 if neither maxUnavilable nor minAvailable is set by user.
