### ISSUE TITLE
Cannot reach k8s service - cluster not found error

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#31925]
Istio Version 1.9.0

I am trying to reach a k8s service with istio, the following components are deployed:

Gateway:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: "2021-03-31T14:47:20Z"
  generation: 1
  labels:
    kubefed.io/managed: "true"
  name: emea-test-mgg76w7ky2fndh-r2rmq4gppfjbgznkaihh-gw-tpl9k
  namespace: emea-test-mesh-operator
  resourceVersion: "21532380"
  uid: 0835949c-9b5d-4d81-841d-4fd466c90a63
spec:
  selector:
    app: emea-test-mgg76w7ky2fndh
  servers:
  - hosts:
    - test.emea.dam.corpintra.net
    port:
      name: emea-test-mgg76w7ky2fndh-r2rmq4gppfjbgznkaihh-gw-tpl9k
      number: 80
      protocol: HTTP
```

VirtualService
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  creationTimestamp: "2021-04-01T11:19:31Z"
  generation: 11
  labels:
    kubefed.io/managed: "true"
  name: emea-test-mgg76w7ky2fndh-rvsrc52hf3zdible6xin-vs-9tvdh
  namespace: emea-test-mesh-operator
  resourceVersion: "21954379"
  uid: 770f20fb-12ee-401e-90a6-896d80c742dd
spec:
  gateways:
  - emea-test-mgg76w7ky2fndh-r2rmq4gppfjbgznkaihh-gw-tpl9k
  hosts:
  - test.emea.dam.corpintra.net
  http:
  - match:
    - port: 80
      uri:
        prefix: /infra/lbtest1.html
    rewrite:
      uri: /infra/lbtest1.html
    route:
    - destination:
        host: gslb-probe.emea-test-gslb-probe.svc.cluster.local
        port:
          number: 80
        subset: v1
```

ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2021-04-01T11:19:31Z"
  generation: 1
  labels:
    kubefed.io/managed: "true"
  name: emea-test-mgg76w7ky2fndh-rvsrc52hf3zdible6xin-se-m4swp
  namespace: emea-test-mesh-operator
  resourceVersion: "21943509"
  uid: ae1460b8-bdd7-4b06-b966-6db2bfbea579
spec:
  hosts:
  - gslb-probe.emea-test-gslb-probe.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: HTTP-se-m4swp-80
    number: 80
    protocol: HTTP
  resolution: DNS
```

DestinationRule:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  creationTimestamp: "2021-04-01T11:19:31Z"
  generation: 6
  labels:
    kubefed.io/managed: "true"
  name: emea-test-mgg76w7ky2fndh-rvsrc52hf3zdible6xin-dr-xq2rv
  namespace: emea-test-mesh-operator
  resourceVersion: "21954649"
  uid: 4ba341c3-dea3-4668-9bcc-15d9146b68e6
spec:
  host: gslb-probe.emea-test-gslb-probe.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DO_NOT_UPGRADE
        idleTimeout: 10s
      tcp:
        connectTimeout: 2s
        maxConnections: 1800

```

I understand that I have to use this "subset" configuration in order to reach a k8s service. The above configuration does not work anymore however, it worked with no issues just before redeploying it all. Right after I redeployed that configuration, I received a 503 cluster not found error in the istio-ingressgateway pod and since then I am not able to fix the configuration.

Istio-Ingressgateway Log:
```bash
{"authority":"test.emea.dam.corpintra.net","duration":0,"requested_server_name":null,"bytes_sent":0,"method":"GET","upstream_local_address":null,"path":"/infra/lbtest1.html/","upstream_transport_failure_reason":null,"bytes_received":0,"downstream_remote_address":"192.168.0.36:25373","request_id":"4a6d902b-1582-4ab3-98a7-03b132321c2c","connection_termination_details":null,"user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","upstream_host":null,"route_name":null,"protocol":"HTTP/1.1","response_code":503,"start_time":"2021-04-06T06:44:39.456Z","response_flags":"NR","response_code_details":"cluster_not_found","downstream_local_address":"192.168.129.136:8080","upstream_service_time":null,"x_forwarded_for":"192.168.0.36","upstream_cluster":null}

```

What have I tried:
- restarted envoy
- redeployed above configuration multiple times
- restarted pod that serves as "gslb-probe"
- read documentation trying to find a solution: https://istio.io/latest/docs/reference/config/networking/virtual-service/

What is confusing me the most is that the above setup did work and now just seems to not work anymore regardless of what I do. Does anyone see my mistake or faulty setup? Inbetween the "it works" and "it doesn't work anymore" I have not changed anything at the target pod or k8s service at all.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I am able to reach the k8s service internally through k8s services.

**Steps to reproduce the bug**
Deploy the above configuration.

**How was Istio installed?**
Helm

**Comment by bianpengyuan** [comment]
Is `gslb-probe.emea-test-gslb-probe.svc.cluster.local` running in the cluster or not? looks weird to have a sevice entry for it..

**Comment by yalctay93** [comment]
> Is `gslb-probe.emea-test-gslb-probe.svc.cluster.local` running in the cluster or not? looks weird to have a sevice entry for it..

Hello, thanks for the reply. Yes, it is running in the cluster. So it'd seem tht a service entry is unecessary? I wonder if that is the error here though as it worked with the above setup once before. I thought that I'd have a mistake on the subset configurations but I cant seem to find it.

**Comment by bianpengyuan** [comment]
yeah you might be seeing some undefined behavior and it works by chance. Please try to remove the service entry and see if works.

**Comment by yalctay93** [comment]
> yeah you might be seeing some undefined behavior and it works by chance. Please try to remove the service entry and see if works.

I've removed the service entry however, the same error persists. :/

**Comment by yalctay93** [comment]
Can anyone help? I am literally just trying to reach a k8s service over istio-ingressgateway how complicated can it be? I just cant seem to find my error.

**Comment by sridharlreddy** [comment]
@yalctay93 Looks like subset v1 you have defined is empty. To just route a connection from ingress to a pod, gateway and virtual service is enough. ServiceEntry is not required since the service is already created in k8s. DestinationRule is needed for additional customisations to the flow.

Check the label on your pods and update it correctly. You can remove the subset and try also.
```
  host: gslb-probe.emea-test-gslb-probe.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
```

**Comment by yalctay93** [comment]
> @yalctay93 Looks like subset v1 you have defined is empty. To just route a connection from ingress to a pod, gateway and virtual service is enough. ServiceEntry is not required since the service is already created in k8s. DestinationRule is needed for additional customisations to the flow.
> 
> Check the label on your pods and update it correctly. You can remove the subset and try also.
> 
> ```
>   host: gslb-probe.emea-test-gslb-probe.svc.cluster.local
>   subsets:
>   - labels:
>       version: v1
>     name: v1
> ```

Alright  was able to fix the issue. I removed the entire subset configuration and also deleted the ServiceEntry. Now I can reach the k8s service. Thanks for the help @sridharlreddy  and @bianpengyuan

**Comment by sridharlreddy** [comment]
> > @yalctay93 Looks like subset v1 you have defined is empty. To just route a connection from ingress to a pod, gateway and virtual service is enough. ServiceEntry is not required since the service is already created in k8s. DestinationRule is needed for additional customisations to the flow.
> > Check the label on your pods and update it correctly. You can remove the subset and try also.
> > ```
> >   host: gslb-probe.emea-test-gslb-probe.svc.cluster.local
> >   subsets:
> >   - labels:
> >       version: v1
> >     name: v1
> > ```
> 
> Alright was able to fix the issue. I removed the entire subset configuration and also deleted the ServiceEntry. Now I can reach the k8s service. Thanks for the help @sridharlreddy and @bianpengyuan

Good to hear, could you please close the issue?

**Comment by koushick123** [comment]
I faced a similar problem and was unable to hit other K8s services from inside the K8s cluster in AKS. I removed the subset portion of virtual service for those services and it worked.
Thanks @sridharlreddy
