### ISSUE TITLE
Istio CNI: Retry if iptables programming fails [xtables locked]

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#31936]
Istio CNI programs iptables rules inside pod network namespace.
Based how many pods are starting and how many other tools are reprogramming iptables there may be contention on the xtables lock.

When this happens we see 
```
nsenter failed, out: ...     Another app is currently holding the xtables lock. Perhaps you want to use the -w option
```
note: `iptables-restore` does not support `-w` options suggested by the error message. `iptables` itself supports it.

We need to ensure that we put `nsenter iptables-restore` in a backoff retry loop to ensure that we do not fail on retryable error.
`xtables lock` in the error message is a very good indicator of retryability.

**Comment by mandarjog** [comment]
@therealmitchconnors for Beta graduation.

**Comment by howardjohn** [comment]
see https://github.com/istio/istio/pull/30394 as well

**Comment by mandarjog** [comment]
@bianpengyuan since you are fixing a bunch of other cni issues can you take this too?
The approach in the attached pr does not work since there is no “-w” option in iptables-restore so we just need to put it in a back off loop. There is a simple back off available in the k8s library.

**Comment by mandarjog** [comment]
https://pkg.go.dev/k8s.io/client-go/util/retry#OnError
