### ISSUE TITLE
istio-ingressgateway not ready (Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected)

### ISSUE THREAD

**Issue by Dimiftb** [istio/istio#31938]
Hi everyone, 

I attempted to install Istio on my single control-plane k8cluster with helm, however I'm having issues with istio-ingressgateway. I'm relatively new at this, so I'm not really sure what's going on.

[X] Installation

**Expected behavior**

<img width="521" alt="image" src="https://user-images.githubusercontent.com/26279721/113744443-a212d400-96fc-11eb-9d1e-7d454cb90e46.png">

`istio-ingressgateway` should be ready

**Steps to reproduce the bug**

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/26279721/113745553-472dac80-96fd-11eb-9fb8-be5f7cf430e0.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/26279721/113745592-514fab00-96fd-11eb-8e0b-af6200550935.png">

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/26279721/113744078-48120e80-96fc-11eb-84dc-5d9b3423e2ac.png">

After installing following these steps Istio-ingressgateway pod is showing as not ready: 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/26279721/113744443-a212d400-96fc-11eb-9d1e-7d454cb90e46.png">

From logs and my limited understanding it seems that some certificate is missing so I attempted to dry-run the install commands above in hope to generate the missing certificate without any luck. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`istioctl version --remote`

<img width="204" alt="image" src="https://user-images.githubusercontent.com/26279721/113744929-0cc40f80-96fd-11eb-9ff7-e4bcd5c41a11.png">

`kubectl version --short`

<img width="178" alt="image" src="https://user-images.githubusercontent.com/26279721/113743667-d5089800-96fb-11eb-8c6d-f009edc631c5.png">

`helm version --short`

<img width="113" alt="image" src="https://user-images.githubusercontent.com/26279721/113743750-ece01c00-96fb-11eb-8476-75ab9b612473.png">

**How was Istio installed?**
Following guide here: https://istio.io/latest/docs/setup/install/helm/ 

`cd istio-1.9.2`
Using helm following steps 1-4 on the guide

**Environment where the bug was observed (cloud vendor, OS, etc)**

<img width="248" alt="image" src="https://user-images.githubusercontent.com/26279721/113743948-20bb4180-96fc-11eb-9189-1367e113f1b8.png">

**Logs**

`kubectl get pod -n istio-system`

<img width="515" alt="image" src="https://user-images.githubusercontent.com/26279721/113745887-9ecc1800-96fd-11eb-8553-457d007bd215.png">

`kubectl describe pod istio-ingressgateway-7cc49dcd99-nxwp2 -n istio-system`

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/26279721/113746078-d3d86a80-96fd-11eb-8e5e-54c237a3af9b.png">

`kubectl logs istiod-687f965684-lczks -n istio-system`

https://filebin.net/x4ojc7qj1uun3r0z

`kubectl logs istio-ingressgateway-7cc49dcd99-nxwp2 -n istio-system`

https://filebin.net/x4ojc7qj1uun3r0z

**Similar issues**

#14205, #23487, #22800, #12446, #18209

Thanks so much for your help guys. Please let me know if I need to provide anything else.

**Comment by howardjohn** [comment]
`10.96.0.10:53: i/o timeout` means the DNS request is failing. Istio requires the Kubernetes cluster to have DNS. Please check your Kubernetes configuration, etc; this is not an Istio issue as far as I can tell.

**Comment by Dimiftb** [comment]
Hi @howardjohn, 

Appreciate your help. I'm relatively new, so I couldn't figure out what i/o timeout meant the DNS request is failing. Upon inspecting the coredns pod I found out that there was indeed issues with it. Reinstalling the cluster from scratch fixed the issue. Maybe if there's something to point us noobs that this error means DNS request is failing it would save you the trouble of having to answer such questions. I'm closing this now.

Thank you very much for your help.
