### ISSUE TITLE
Provide necessary bits for `request.auth.claims`

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#3194]
There are no entries in the deployment attribute manifests for `request.auth.claims`, nor is there documentation for it in the reference docs on the website.

If it is intended to be used in Mixer, it needs to be in `istio-mixer.yaml.tmpl` (and elsewhere).

**Comment by theganyo** [comment]
It appears to be a STRING_MAP, but I don't believe that's sufficient. It would need to be the equivalent to a `map[string]interface{}`... as claim values can be other than string.

**Comment by theganyo** [comment]
`mixer/testdata/config/attributes.yaml` also has no definition for `request.auth.claims`.

**Comment by theganyo** [comment]
Any progress on this? The latest in master still doesn't include `request.auth.claims` as a valid attribute.

**Comment by qiwzhang** [comment]
@douglas-reid is this still the case?  Should I use #5040  to track this issue and close this one?

**Comment by douglas-reid** [comment]
@qiwzhang as far as I'm aware, there is no representation of `request.auth.claims` anywhere.

I'm fine iwht using #5040, as long as @theganyo is.

**Comment by theganyo** [comment]
I don't care which issue we use... as long as it gets fixed for 0.8. :)

**Comment by theganyo** [comment]
verified as fixed in nightly build. thanks!
