### ISSUE TITLE
first-party-jwt incompatible with Kubernetes 1.21+

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31964]
This test is hidden which is why it doesn't sound alarms

https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-121_istio_postsubmit/1379544581607002112

**Comment by howardjohn** [comment]
seems first-party-jwt is broken

**Comment by howardjohn** [comment]
I sent a few PRs, I think we still want istioctl to warn/fail, mark the field as deprecated, and some release notes? @jacob-delgado can you own this?

**Comment by Monkeyanator** [comment]
Release note and istioctl warning both made it in, should be good to close?

**Comment by howardjohn** [comment]
Yeah I think so. We need to remove the feature entirely, but probably need to wait ~ a year
