### ISSUE TITLE
Distributed tracing sampling rate of 0.0 not possible

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#31985]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
According to the [tracing documentation](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#customizing-trace-sampling) it should be possible to set a sampling rate of `0.0`. However, when you do that, Envoy will fall back to a default value of `1`.

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
If `0.0` is not valid, the documentation should be fixed. If it is, Envoy should accept the value and not change it to something else.

**Steps to reproduce the bug**
Enable tracing with this configuration:
```
    values:
      meshConfig:
        enableTracing: true
        defaultConfig:
          tracing:
            sampling: 0.0
      global:
        proxy:
          tracer: stackdriver
```
Restart a pod and observe the following in the config_dump:
```
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 1
             },
             "overall_sampling": {
              "value": 100
             },
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
ASM 1.9.1, revision 1

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @douglas-reid

**Comment by bianpengyuan** [comment]
It is an API flaw of proxyConfig tracing API, that it cannot tell unset from zero value. At 1.10 this will be resolved by the new tracing API.

As a work around, you can set `PILOT_TRACE_SAMPLING` env variable to 0 at istiod. That way proxyConfig could take control of global default tracing sampling rate.

**Comment by rolandkool** [comment]
Thanks for the feedback. We're still in pilot phase so we can wait for 1.10 for a fix.
