### ISSUE TITLE
 Cannot assign requested address (Address not available) after hitting too many requests. 

### ISSUE THREAD

**Issue by Phaniharsha2908** [istio/istio#31994]
Hi,

We are doing performance test on Elasticsearch through Istio ingress gateway - we are getting the following error's - i could not find these error's in istio ingress gateway pod 

Code	Description	Count
Non HTTP response code: java.net.NoRouteToHostException	Non HTTP response message: Cannot assign requested address (Address not available)	6708

performance Test config:   
200 users, duration 5 mins, Ramp up time 1 min.

istio ingress gateway pod resources:
Request: 4vcpu,4gb mem
Limits: 8vcpu, 8gb mem

istio version: 1.7
Environment::  GKE

**Comment by howardjohn** [comment]
This seems maybe not related to Istio and instead your client? See https://stackoverflow.com/questions/53189126/jmeter-java-net-noroutetohostexception-cannot-assign-requested-address-addre/53189277

**Comment by Phaniharsha2908** [comment]
Hi @howardjohn - Thank for the response.
We are using a blaze meter for a performance test, it has several engines that it uses to execute the performance script. However, we ran the same test using nginx proxy for elastic search.  I don't see any NoRouteToHostException with nginx proxy. I don't think this is a port range issue or internal Environment issue as both the namespaces (Istio-elasticsearch and nginx-elasticsearch) belong to the same gke cluster.

Can you please let me know what kind of information needed for analyzing this issue.

Thanks

**Comment by Phaniharsha2908** [comment]
Hi @howardjohn 

I would appreciate it, if you can you help us here?

Thanks,
