### ISSUE TITLE
Some default tag extractor in envoy_bootstrap.json not working

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#32025]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
https://github.com/istio/istio/blob/5c752dc4572c11ac0d4f09cfbdb8d146eecb50d1/tools/packaging/common/envoy_bootstrap.json defined many default tag extractors.

It seems some are broken due to the format change in the stat name that is never matched with the regex. for example, the following tag extractor `http_conn_manager_prefix`:

```
      {
        "tag_name": "http_conn_manager_prefix",
        "regex": "^http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
      },
```

There is no `http_conn_manager_prefix` tag in the prometheus output at all. 
```
# TYPE envoy_http_InboundPassthroughClusterIpv4_rbac counter
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_enforce_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_enforce_result="denied"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_action="allow",authz_dry_run_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_action="allow",authz_dry_run_result="denied"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_action="deny",authz_dry_run_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_action="deny",authz_dry_run_result="denied"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_result="denied"} 0

# TYPE envoy_http_inbound_0_0_0_0_80_rbac counter
envoy_http_inbound_0_0_0_0_80_rbac{authz_enforce_result="allowed"} 0
envoy_http_inbound_0_0_0_0_80_rbac{authz_enforce_result="denied"} 0
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_action="allow",authz_dry_run_result="allowed"} 2
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_action="allow",authz_dry_run_result="denied"} 1
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_action="deny",authz_dry_run_result="allowed"} 1
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_action="deny",authz_dry_run_result="denied"} 2
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_result="allowed"} 0
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_result="denied"} 0
```

It might be due to the regex never matched to the current Istio stat name, for example:

```
http.InboundPassthroughClusterIpv4.rbac.istio_ext_authz_.shadow_allowed: 0
http.InboundPassthroughClusterIpv4.rbac.istio_ext_authz_.shadow_denied: 0
http.inbound_0.0.0.0_80.ext_authz.denied: 0
http.inbound_0.0.0.0_80.ext_authz.failure_mode_allowed: 0
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
We should just remove the ones that do not match anymore.

**Comment by yangminzhu** [comment]
> We should just remove the ones that do not match anymore.

shouldn't it be fixed to properly handle the new stat name?

**Comment by bianpengyuan** [comment]
I think they were added back to the time when we still generate all envoy stats. Right now we only expose a limit set of stats, so this set of tag extractor is essentially noop. If user want to expose more stats based on their needs, they should also configure tag extractor pattern use proxyConfig as needed.
