### ISSUE TITLE
Do not create self signed root CA and istio-ca-root-cert configmap when values.global.pilotCertProvider is kubernetes

### ISSUE THREAD

**Issue by jtrbs** [istio/istio#32023]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

When PILOT_CERT_PROVIDER is kubernetes, there is no need to create self-signed certificate as the CA certificate and create istio-ca-root-cert configmap for every namespace. 
Currently when the istio is installed via
```
istioctl install --set values.global.pilotCertProvider=kubernetes
```
We will see the follow log in istiod which is misleading
```
2021-04-07T20:24:34.710915Z	info	initializing mesh handlers
2021-04-07T20:24:34.710934Z	info	creating CA and initializing public key
2021-04-07T20:24:34.710958Z	info	Use self-signed certificate as the CA certificate
2021-04-07T20:24:34.719314Z	info	pkica	Failed to get secret (error: secrets "istio-ca-secret" not found), will create one
2021-04-07T20:24:35.427100Z	info	pkica	Using self-generated public key: -----BEGIN CERTIFICATE-----
```
And we will see  istio-ca-root-cert configmap is created in every new namespace which is not needed. 

After this is fix, we can also help cloudrun to upgrade to newer istio version. Currently cloudrun and istio add on exist together on one cluster. There are conflicts on istio-ca-root-cert configmap as both istio control plane for cloudrun and istio control plane for istio add on will try to modify istio-ca-root-cert configmap. If cloudrun uses kubernetes CA, with the this bug fixed, it can coexist with istio add on. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When PILOT_CERT_PROVIDER is kubernetes, no self-signed certificate as the CA certificate is created and no istio-ca-root-cert configmap is created. 

**Steps to reproduce the bug**
Download istio 1.9.2
Install istio via
```
istioctl install --set values.global.pilotCertProvider=kubernetes
```
Check istiod log
Create a new namespace and check the config map
```
kubectl create ns test
kubectl get configmaps -n test
NAME                 DATA   AGE
istio-ca-root-cert   1      113m
kube-root-ca.crt     1      113m
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (7 proxies)
```
```
kubectl version --short
Client Version: v1.18.15
Server Version: v1.18.16-gke.302
```

**How was Istio installed?**
```
istioctl install --set values.global.pilotCertProvider=kubernetes
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE-on-GCP cluster
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by jtrbs** [comment]
@myidpt

**Comment by jtrbs** [comment]
Hi @costinm @howardjohn, may you help take a look into the issue? Thanks a lot!

**Comment by c0ffeec0der** [comment]
I think this bug is not fixed...

using istio

client version: 1.12.1
control plane version: 1.12.1

deploy istiod with environment

    Environment:
      ENABLE_CA_SERVER:                             false
      PILOT_CERT_PROVIDER:                          kubernetes

found istio-ca-root-cert configmap across namespaces...

default           istio-ca-root-cert                                    1      30m
istio-system      istio-ca-root-cert                                    1      30m
kube-node-lease   istio-ca-root-cert                                    1      30m
kube-public       istio-ca-root-cert                                    1      30m
kube-system       istio-ca-root-cert                                    1      30m
