### ISSUE TITLE
e2e-simple complains about injection & fortio

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3203]
https://circleci.com/gh/istio/istio/24851?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by andraxylia** [comment]
This affects e2e-simple automated tests, please fix with priority.

**Comment by ldemailly** [comment]
@costinm was making it work on circle - I don't know that it's ready/working (or that that build is blocking yet), the PR may just need rebase ?

**Comment by ldemailly** [comment]
https://circleci.com/gh/istio/istio/tree/master seems green so I would think it's just a PR that needs rebase ? will close for now to avoid noise but if you see a recent or rebased PR that has the issue, please reopen
