### ISSUE TITLE
How to make istio-proxy prevent from intecepting set of hosts and IP

### ISSUE THREAD

**Issue by anthonyvk** [istio/istio#32047]
**Many services communicating to external services failing after installing Istio service mesh. The services communicate to Newrelic collector through corporate proxy. Tried all the options of adding ServiceEntry, it doesnt work. This has become a critical blocker for the team. Without Istio service mesh things work fine.**

Tried adding ServiceEntry, entry in includeIPRanges, and disabling Egress.

[ ] Docs
[ X ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ]  User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
- Services must be able to connect to Newrelic and External services through company proxy.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istioctl : 
client version: 1.9.1
control plane version: 1.9.2
data plane version: 1.9.2 (3 proxies)

Kubectl : 
Client Version: v1.18.6
Server Version: v1.19.7

Helm : v3.3.4+ga61ce56

**How was Istio installed?**
Helm charts

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal and Docker Desktop

**Comment by bianpengyuan** [comment]
Have you tried this https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

**Comment by anthonyvk** [comment]
> Have you tried this https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

Tried, but didn't work
