### ISSUE TITLE
encrypted service to service communication via istio gateway

### ISSUE THREAD

**Issue by rajivml** [istio/istio#32051]
Hi,

A general question w.r.t Istio please see if you can provide us any guidance.

For service to service communication within the k8 cluster, we have this use case where service A has to talk to Service B via istio gateway in an encrypted fashion, it has to be via istio gateway because at the gateway layer we have an envoy filter written in Lua which populate headers and we want this communication to be on https, but since there won't be any side car injected at istio gateway (with mtls and istio injection enabled), https communication between services has become tricky via gateway, if it's just service to service communication without gateway involved, then mutuals tls handles the encryption but with no side car involved at istio-gateway not sure how to handle this situation,  do you guys have any suggestions or workarounds here ? 

**"Service A -> Sidecar A (mTLS) -> IstioGateway -> Sidecar B (mTLS) -> Service B"**

**Comment by bianpengyuan** [comment]
Gateway support `ISTIO_MUTUAL` mode: https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-TLSmode
