### ISSUE TITLE
Remove TestCustomizeMetrics dependency on istio build bucket

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#32050]
Currently `TestCustomizeMetrics` depends on public istio build bucket, which does not work in ci running in private repo.

https://github.com/istio/istio/blob/455957e0a6cdad9bec5fad88bdbeeee273cef87b/tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml#L84

**Comment by jacob-delgado** [comment]
Following this issue.
