### ISSUE TITLE
Failures in race tests 

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3206]
Failed tests in this run have to be disabled until fixed properly:
https://circleci.com/gh/istio/istio/23976

Your build ran 3174 tests with 10 failures
TestBatchMeasurements - appoptics
Failed
TestBatchMeasurements/All_Good - appoptics
Failed
TestLog - papertrail
Failed
Less
TestLog/All_Good - papertrail
Failed
TestNewMetricsHandler - solarwinds
Failed
TestNewMetricsHandler/All_good - solarwinds
Failed
TestPersistBatches - appoptics
Failed
TestPersistBatches/Persist_all_good - appoptics
Failed
TestStressEnvoy - stress
Failed
TestTCPMixerFilter - tcp_filter

**Comment by girishranganathan** [comment]
K will check
