### ISSUE TITLE
Lua envoyfilter creates error when using metadata in response handle and request method is OPTIONS 

### ISSUE THREAD

**Issue by mikosa** [istio/istio#32064]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I created a lua filter that saves headers in request metadata to be used in the response handle. This works great when the request is GET or POST

When the request method is OPTIONS, it seems that metadata is returning nil. and this is creating an error.

- I am not able to check using lua if the metadata is nil before trying to query the metadata. If I try to check if metadata is nil, i still get a nil error

- Also I tried to run the code only when the request method is GET but in the response handle, I dont have access to the request method. so cant put a condition on that

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Expected to not have errors if request method is OPTIONS

**Steps to reproduce the bug**
add a lua filter with this code
``` 
           function envoy_on_request(handle)
            local headers = handle:headers()
            local metadata = handle:streamInfo():dynamicMetadata()                
            local rid = headers:get("x-request-id")
            local mymeta = metadata:set("envoy.filters.http.lua", "request-id", rid)
          end
          function envoy_on_response(res_handle)
             local metadata = res_handle:streamInfo():dynamicMetadata()
             local pis =  metadata:get("envoy.filters.http.lua")["request-id"]
             res_handle:headers():add("x-request-id", pis)
          end
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**
?
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Looks like an envoy issue. Can you open an issue there instead?

**Comment by mikosa** [comment]
Yeah, I did. They asked me for an envoy filter example :)
maybe i should invest some time to create an envoy example to reproduce the issue

**Comment by bianpengyuan** [comment]
You can find the LUA envoy filter config from the config dump, if that is what they are asking for: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

**Comment by bianpengyuan** [comment]
Also could you link the Envoy issue here, so that people who find this issue by searching could know the progress of fixing.
