### ISSUE TITLE
TestPersistBatches failes race tests and flaky

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3209]
See #3206

This test fails race and it has been disabled for race tests.

@girishranganathan you are the author of this, please asses the cause of failure.

**Comment by andraxylia** [comment]
cc @douglas-reid

**Comment by xiaolanz** [comment]
run it 100 times. see 2 failures. investigating...
go test -v -run TestPersistBatches ./mixer/adapter/solarwinds/internal/appoptics/... -count 100 -race > /tmp/persistBatches.out
