### ISSUE TITLE
Image scanner: fail open when there are issues

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32096]
We sometimes get `524 Origin Time-out` errors from scanner. We should just ignore them and continue

cc @ericvn

**Comment by ericvn** [comment]
https://storage.googleapis.com/istio-prow/logs/release_istio_release-1.10_postsubmit/1404498488158326784/build-log.txt had a 400 from the scanner.

**Comment by ericvn** [comment]
The current code will retry 4 times if the `http.Get` returns an error, but does not retry if the `Get` succeeds without an error.
