### ISSUE TITLE
[multicluster] istio pod can't start until remote apiserver endpoint becomes ready

### ISSUE THREAD

**Issue by apolovov** [istio/istio#32102]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

If there is a remote cluster configured (via secret with label istio/multiCluster: true) and its apiserver endpoint is unreachable, the istiod pod doesn't become Ready.
On the other hand, if I add an unhealthy remote configuration at the moment when the pod is Ready, it continues to work and serve the local cluster.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Istiod's pod should become ready if the remote cluster is unhealthy.

**Steps to reproduce the bug**

* Add unhealthy kubeconfig to istio by creating a special secret.
* Restart istiod pod.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.9.1

**Comment by bianpengyuan** [comment]
https://github.com/istio/istio/issues/30838 tracks the fix for this issue.
