### ISSUE TITLE
TestStressEnvoy fails race tests

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3210]
See #3206

This test fails race and it has been disabled for race tests.

@qiwzhang  you are the author of this, please asses the cause of failure.

**Comment by ldemailly** [comment]
it also fails regular tests
https://circleci.com/gh/istio/istio/30187

**Comment by GregHanson** [comment]
This test is still periodically failing:
https://circleci.com/gh/istio/istio/35289

**Comment by ldemailly** [comment]
let's close this after we have at least 3 greens for that test/build
