### ISSUE TITLE
Configuring a different tracing sampling rate via proxyConfig override, removes tracing configuration completely

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#32114]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When using the proxyConfig annotation on a pod to set a different tracing sampling rate, the whole tracing configuration is removed from the Envoy configuration

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Configuration should be merged with the mesh wide configuration

**Steps to reproduce the bug**
Enable tracing by adding the following meshConfig:
```    values:
      meshConfig:
        enableTracing: true
        defaultConfig:
          tracing:
            sampling: 0.02
      global:
        proxy:
          tracer: stackdriver
```

Restart a pod to validate the tracing configuration is picked up by checking the config_dump. Search for `stackdriver` and you should see a section containing tracing configuration.

Now add the following annotation to the pod template:
```
        proxy.istio.io/config: |
          tracing:
            sampling: 100
```
This will restart the pod. Recheck the config_dump and notice the `stackdriver` section for tracing is all gone. The sampling configuration can be found, though, but does not have any effect.

It can be worked around by adding this as a proxy config override:
```
        proxy.istio.io/config: |
          tracing:
            sampling: 100
            stackdriver:
              maxNumberOfAttributes: 200
              maxNumberOfAnnotations: 200
              maxNumberOfMessageEvents: 200
```

If this is expected, the documentation may need to be improved to better describe this behavior. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
ASM 1.9.1, rev 1

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE 1.18

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by mandarjog** [comment]
@douglas-reid 
@richardwxn either our templates or merge behaviour unsetting the entire stackdriver message if override does not specify it.

**Comment by howardjohn** [comment]
This is "working as implemented". It is expected this would happen - so we can either change behavior or document it better?

**Comment by bianpengyuan** [comment]
We have a note here: https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#available-tracing-configurations

**Comment by douglas-reid** [comment]
Agree with @bianpengyuan - there is a warning in the docs. We could reorder the warnings a bit, but I'm not sure how much that would help. Possibly, we could add some specific warnings in the docs for the annotation, but that might be a bit too in the weeds for all of proxy config. 

The behavior is a bit surprising, but I think what we really want to do is to start the transition over to the new API and focus on delivering high-quality docs around that.

**Comment by rolandkool** [comment]
I've missed that warning, that is my bad.

Perhaps move the warning towards [the example proxy config override](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#using-proxy-istio-io-config-annotation-for-trace-settings) because there is where it becomes relevant. Another idea could be to make the example more complete by adding the driver configuration. The example now seems to indicate it is not required.

If it helps, I would not mind starting a PR.
