### ISSUE TITLE
Prometheus unable to scrape node-exporter after upgrade 1.7.6 -> 1.8.4

### ISSUE THREAD

**Issue by ericjohansson89** [istio/istio#32112]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We are running an istio sidecar proxy on our prometheus server which is scraping pods in our cluster. When upgrading from istio 1.7.6 to istio 1.8.4 prometheus is unable to scrape the [node exporter](https://github.com/prometheus/node_exporter). Logging level set to verbose gives the following message from the sidecar proxy.

`2021-04-08T08:57:24.589761Z     debug   envoy http      [C149][S17405316898299644747] Sending local reply with details route_not_found`

What we thought could be the issue is that the node-exporter is running as a headless service so we tried enabling the setting on pilot with `PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES` by setting it to true but no change.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The prometheus pod is able to scrape the node-exporter

**Steps to reproduce the bug**
Install istio 1.7.6 via operator
Install prometheus with node-exporter via this helm chart: https://github.com/helm/charts/tree/master/stable/prometheus with version 10.5.1. Prometheus running with sidecar, node-exporter without.
Upgrade istio to 1.8.4, prometheus is unable to scrape 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl
`client version: 1.8.4
control plane version: 1.8.4
data plane version: 1.8.4 (x proxies)`

kubctl
`Client Version: v1.20.2
Server Version: v1.18.9-eks-d1db3c`

**How was Istio installed?**
Istioctl using operator init.
IstioOperator CustomResource installed through helm.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Amazon EKS.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
do you have a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio) and some more context in the debug logs (it should show the request that failed)?

**Comment by ericjohansson89** [comment]
Sure, so I have identified the issue. When I switch it to not being a headless service it works.

Providing config dump with and without the headless service. So it is the node-exporter parts
[config_dump_headless.json.zip](https://github.com/istio/istio/files/6309588/config_dump_headless.json.zip)
[config_dump_clusterIP.json.zip](https://github.com/istio/istio/files/6309657/config_dump_clusterIP.json.zip)
