### ISSUE TITLE
istioctl x precheck yields Error

### ISSUE THREAD

**Issue by ericvn** [istio/istio#32119]
**Bug description**

The downloadIstio script was used to pull the 1.10-alpha.0 release. At the end of the script it says to:
```
Begin the Istio pre-installation check by running:
	 istioctl x precheck
```
which for me yields the error:
```
Error: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I should not receive an error when running the specified pre-installation check

**Steps to reproduce the bug**
- curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.10.0-alpha.0 sh -
- istio-1.10.0-alpha.0/bin/istioctl x precheck

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.10.0-alpha.0

**How was Istio installed?**

At this point, it isn't.

**Environment where the bug was observed (cloud vendor, OS, etc)**

MacOS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
that means its not detecting kubeconfig correctly. Does `istioctl version`, `kubectl version`, and/or `istioctl install` work?

**Comment by ericvn** [comment]
At the point I was running the commands, my cluster may have been still creating, so I suspect `kubeconfig` wasn't set yet. Should we have a better message in that case?

Going to a non specified kubeconfig, I see from kubectl a similar message, but agree it doesn't point at an incomplete kubeconfig:
```
> kubectl version 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
also
```
>./bin/istioctl version
unable to retrieve Pods: Get "http://localhost:8080/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Distiod": dial tcp [::1]:8080: connect: connection refused
1.10.0-alpha.0
```
so similar message to recheck.

I'm fine closing this as user error.

**Comment by ericvn** [comment]
Tried the same on the 1.8.4 client:
```
Checking the cluster to make sure it is ready for Istio installation...

#1. Kubernetes-api
-----------------------
Can initialize the Kubernetes client.
Failed to query the Kubernetes API Server: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused.
Istio install NOT verified because the cluster is unreachable.
Error: 1 error occurred:
	* failed to query the Kubernetes API Server: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
	* ``

**Comment by daisy-ycguo** [comment]
I've tested istioctl 1.10.0. Without kubeconfig correctly, it reports:
```
$ ./istioctl x precheck
Error: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```
