### ISSUE TITLE
Websocket connection between services in the cluster throws "java.io.IOException: Upgrade responses cannot have a transfer coding"

### ISSUE THREAD

**Issue by anthonyvk** [istio/istio#32127]
**Websocket connection between java services in the cluster throws "java.io.IOException: Upgrade responses cannot have a transfer coding in the application."**
Works fine when istio sidecar injection is disabled.
Even tried adding : 
```
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: "10.96.0.0/12"
```
but didnt work.

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Websocket communication must be successful.

**Steps to reproduce the bug**
- Install 2 Java process which creates websocket connection to other.
- Enable Sidecar injection in the namespace.

**Version** 
istioctl version --remote :                                                                                                               
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (10 proxies)

kubectl version --short : 
Client Version: v1.18.6
Server Version: v1.17.7

**How was Istio installed?**
Istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @Monkeyanator @lambdai

**Comment by Monkeyanator** [comment]
Almost certainly caused by [https://github.com/istio/istio/pull/28450](https://github.com/istio/istio/pull/28450). When upgrading http1.1 to websockets connection the server sends `101 Switching Protocols`, and with `strict_1xx_and_204_reponse_headers=false`, Envoy will add the transfer encoding header. I'm guessing the Java client library being used is strict on the spec here.

Once we have [this](https://github.com/envoyproxy/envoy/pull/15880) in our Envoy we can fix this behavior.

**Comment by anthonyvk** [comment]
Got it @Monkeyanator

**Comment by anthonyvk** [comment]
Looks this fixed in the Envoy proxy. I guess istio need to make a release

**Comment by anthonyvk** [comment]
> 
> 
> Almost certainly caused by #28450. When upgrading http1.1 to websockets connection the server sends `101 Switching Protocols`, and with `strict_1xx_and_204_reponse_headers=false`, Envoy will add the transfer encoding header. I'm guessing the Java client library being used is strict on the spec here.
> 
> Once we have [this](https://github.com/envoyproxy/envoy/pull/15880) in our Envoy we can fix this behavior.

Looks like this is fixed now :
https://github.com/envoyproxy/envoy/pull/15880

**Comment by anthonyvk** [comment]
We are still facing this issue on the latest version of istio

**Comment by anthonyvk** [comment]
> 
> 
> We are still facing this issue on the latest version of istio

@Monkeyanator

**Comment by Monkeyanator** [comment]
Locally I'm able to see that `transfer-encoding: chunked` response headers go away on newer versions so maybe that wasn't the problem... what's the output when you run `curl -svI <service>` against the endpoint that tries the websockets upgrade?

Also if you let me know what client library you're using I can try and reproduce.

**Comment by anthonyvk** [comment]
> 
> 
> Locally I'm able to see that `transfer-encoding: chunked` response headers go away on newer versions so maybe that wasn't the problem... what's the output when you run `curl -svI <service>` against the endpoint that tries the websockets upgrade?
> 
> Also if you let me know what client library you're using I can try and reproduce.

Sure, let me try and get back to you

**Comment by anthonyvk** [comment]
We are seeing this issue in latest version if istio also.

**Comment by anthonyvk** [comment]
As mentioned in this : https://github.com/istio/istio/issues/29427

When I changed by Service Port name from http to tcp issues disappeared.
