### ISSUE TITLE
echo: allow adding workloads from external config

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32126]
- make parts of `echo.Config` serializable/deserializable
- accept a config file to add workloads to a test run from the outside in

Workload agnostic tests are required to fully take advantage of this, but we can configure additional cases, (such as VMs on different distros) at the job level while re-using existing tests

**Comment by brian-avery** [comment]
@stevenctl Is this needed to support anything?

**Comment by stevenctl** [comment]
I think I'm going to close this. I wanted to be able to arbitrarily add workloads without touching the Go tests, to semi-automate edge cases, or have postsubmit test a larget set of workloads. I'm not sure how valuable it is compared to the effort to implement.
