### ISSUE TITLE
Defaulting interaction with istio-proxy container injection

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32120]
```
      - name: istio-proxy
        image: auto
        securityContext: # to allow core dumps
          readOnlyRootFilesystem: false
```

imagePullPolicy is always set to `Always`, because the deployment will add it as a default. I do not know any way to fix this.

**Comment by sridharlreddy** [comment]
can be set using values.global.imagePullPolicy

**Comment by isfong** [comment]
> can be set using values.global.imagePullPolicy

How can I change this policy after Istio has been installed

**Comment by isfong** [comment]
> > can be set using values.global.imagePullPolicy
> 
> How can I change this policy after Istio has been installed

I find it by configmaps istio-sidecar-injector
```shell
kubectl -n istio-system edit configmaps istio-sidecar-injector 
```
