### ISSUE TITLE
istio looks for egress hosts to apply inbound cluster settings(connection pool settsing)

### ISSUE THREAD

**Issue by edieYoung** [istio/istio#32130]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When the server itself is not added in to the egress hosts list, connection pool settings won't be applied, it uses default settings.

sidecar config:
```
egress:
    - hosts:
      - ~/*
```

generated config:
```
 {
     "version_info": "2021-03-11T17:42:23Z/5086",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "InboundPassthroughClusterIpv4",
      "type": "ORIGINAL_DST",
      "connect_timeout": "10s",
      "lb_policy": "CLUSTER_PROVIDED",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "upstream_bind_config": {
       "source_address": {
        "address": "127.0.0.6",
        "port_value": 0
       }
      },
      "protocol_selection": "USE_DOWNSTREAM_PROTOCOL"
     },
     "last_updated": "2021-03-11T17:42:23.849Z"
    },
```

When the server itself is added in to the egress hosts list, connection pool settings will be applied.

sidecar config:
```
egress:
    - hosts:
      - ./*
```

generated config:
```
 {
version_info: "2021-03-11T18:57:55Z/5491",
cluster: {
@type: "type.googleapis.com/envoy.config.cluster.v3.Cluster",
name: "inbound|8080||",
type: "STATIC",
connect_timeout: "0.200s",
circuit_breakers: {
thresholds: [
{
max_connections: 8192,
max_pending_requests: 1024,
max_requests: 1024,
max_retries: 1000
}
]
},
metadata: {
filter_metadata: {
istio: {
config: "/apis/networking.istio.io/v1alpha3/namespaces/airmesh-test-fortioserver/destination-rule/fortioserver",
services: [
{
name: "fortioserver",
namespace: "airmesh-test-fortioserver",
host: "fortioserver.airmesh-test-fortioserver.svc.ea1t.us.a"
}
]
}
}
},
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

inbound cluster settings(connection pool settings) shouldn't depend on egress list, since it's for inbound traffic, egress list should be only for handling outbound traffic.

And we found that this is due to the Istio will look for DestinationRule to apply connection pool settings for inbound clusters, [source](https://github.com/istio/istio/blob/3211c6b8e414e574de0ab792233a14ca0aa172e9/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L262).

**Steps to reproduce the bug**
See bug description. 

**Version**
```
istioctl version --remote
1.8.4
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This would/will be fixed by https://github.com/istio/api/pull/1754
