### ISSUE TITLE
Canary upgrade: ValidatingWebhookConfiguration is not pointed to new revision of istiod

### ISSUE THREAD

**Issue by TamasNeumer** [istio/istio#32143]
**Bug description**

When performing canary upgrade (in my case 1.7.8 to 1.8.4), the `ValidatingWebhookConfiguration` was not updates to use the new version of the istiod service (`istiod-1-8-4)`

When deleting the old control plane (installed **without** a revision) the new `istiod-1-8-4` pod starts logging that:

```
2021-04-13T14:40:25.877052Z     info    validationController    Reconcile(enter): retry dry-run creation of invalid config
2021-04-13T14:40:25.877958Z     info    validationController    validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail, resourceVersion=247891) is up-to-date. No change required.
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ x ] Upgrade

**Expected behavior**

I would have expected that the `istiod-1-8-4` uses a `ValidatingWebhookConfiguration` named `istiod-istio-system-1-8-4` and upon deleting the old (unlabeled) control plane, it keeps working.

**Steps to reproduce the bug**

- Install Istio 1.7.8 without a release tag
- Install Istio 1.8.4 with a release of "1-8-4" 
- Delete the old control plane as describe in the docs using: `istioctl x uninstall -f manifests/profiles/default.yaml`

**How was Istio installed?**

```sh
ISTIO_VERSION_1_7_8=1.7.8
ISTIO_NODE_POOL=istio-pool

cat <<EOF > values-1-7-8.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        nodeSelector:
          node-dedication: ${ISTIO_NODE_POOL}
        tolerations:
        - key: node-pool
          value: ${ISTIO_NODE_POOL}
          effect: NoSchedule
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            node-dedication: ${ISTIO_NODE_POOL}
          tolerations:
          - key: node-pool
            value: ${ISTIO_NODE_POOL}
            effect: NoSchedule
          serviceAnnotations:
            cloud.google.com/neg: '{"exposed_ports": {"443":{}}}'
          service:
            type: NodePort
            ports:
              - port: 443
                targetPort: 8443
                name: https
  values:
    global:
      meshExpansion:
        enabled: true
EOF

curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${ISTIO_VERSION_1_7_8} sh -

istio-${ISTIO_VERSION_1_7_8}/bin/istioctl install -f values-1-7-8.yaml
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Google Cloud, GKE version `1.18.15-gke.1501`

**Comment by Monkeyanator** [comment]
Thanks for posting @TamasNeumer, this issue is being tracked [here](https://github.com/istio/istio/issues/28880). Until there's a better fix in we have workaround instructions on the canary upgrade page
