### ISSUE TITLE
Support for OAuth2 workflow 

### ISSUE THREAD

**Issue by sudeeptoroy** [istio/istio#32149]
**Describe the feature request**
Envoy natively support OAuth2 workflow. This request is to expose the same via Istio configuration.

**Describe alternatives you've considered**
I am not sure if this can be achieved via envoyfilter. I have configured envoy natively to enable OAuth2 workflow for my application.

[ X] Security

**Additional context**
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter

**Comment by yangminzhu** [comment]
Currently the alternative is to use the oauth2-proxy with the CUSTOM action in authz policy, there are several successful examples on the discuss.istio.io for referehce.

Regarding the oauth2 filter, I think it's still in alpha and under active development, we probably need to wait it to be in a more mature state (at least wait until its API becomes stable).

**Comment by sudeeptoroy** [comment]
HI @yangminzhu , thanks for suggesting the alternatives.
Are there any development or design happening around supporting OAuth2 filter natively on Istio?

**Comment by Zeka13** [comment]
Can someone share please this "successful examples"? I am looking for something like this https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

**Comment by anannaya** [comment]
@yangminzhu  Is there any way we can apply the istio AUthz policy after the oauth2-proxy processing at the oauth2-proxy pod layer it self.   I am basically looking to enable Authorization for the application which does not contain sidecar .

**Comment by nc-ruth** [comment]
@Zeka13 here is a example:

istio configmap in istio-system:
`
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    enableTracing: true
    extensionProviders:
    - name: "oauth2-proxy-service"
      envoyExtAuthzHttp:
        service: "oauth2-proxy.oauth2.svc.cluster.local"
        port: 4180
        includeHeadersInCheck: ["authorization", "cookie"]
        headersToDownstreamOnDeny:
          - content-type
          - set-cookie
        headersToUpstreamOnAllow:
          - authorization
          - cookie
          - path
        includeHeadersInCheck:
          - "cookie"
          - "x-forwarded-access-token"
          - "x-forwarded-user"
          - "x-forwarded-email"
          - "authorization"
          - "x-forwarded-proto"
          - "proxy-authorization"
          - "user-agent"
          - "x-forwarded-host"
          - "from"
          - "x-forwarded-for"
          - "x-forwarded-uri"
          - "x-auth-request-redirect"
          - "accept"
  meshNetworks: 'networks: {}'
`

Istio authorizationpolicy for oauth2 (can be placed in istio-system):
`
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oauth2
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy-service
  rules:
    - to:
        - operation:
            paths:
              - "*"
  selector:
    matchLabels:
      authorizationType: oauth2
`

Add label "authorizationType: oauth2" to your deployments.

**Comment by phllpmcphrsn** [comment]
@nc-ruth why do you have `includeheadersincheck` twice? Typo?

**Comment by dtu-ruth** [comment]
@phllpmcphrsn yes probably a typo.
I am pretty sure we use the last definition. 😄
