### ISSUE TITLE
Unable to Import Istio Service Dashboard to Grafana via Web Interface Due to Emoji 🔐

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#32160]
**Bug description**
Istio Service Dashboard v1.9.2 (rev58) cannot be directly imported into Grafana 7.5.3 due to the emoji for mTLS existing in dashboard legend. After removing all "🔐" emoji from the JSON, it can be imported normally.

Note: it is not the only dashboard that has a similar issue.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The dashboard can be imported to Grafana via web interface normally.

**Steps to reproduce the bug**
Use the "import" feature in Grafana web interface to import the JSON downloaded from Grafana site (https://grafana.com/grafana/dashboards/7636) (https://grafana.com/api/dashboards/7636/revisions/58/download). Screenshot attached:

![image](https://user-images.githubusercontent.com/15870761/114646111-3c7ea300-9d0d-11eb-8250-8cff0c9ab286.png)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.2 (should be unrelated)

**How was Istio installed?**
Using istio-operator (should be unrelated)

**Environment where the bug was observed (cloud vendor, OS, etc)**
Bitnami Grafana 7.5.3

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
It worked for me, but I recall having similar issues at some point in the past. Exact steps I took:
* https://grafana.com/api/dashboards/7636/revisions/58/download in browser, gets downloaded to a file.
* Copy the file, paste into grafana UI

**Comment by ethernoy** [comment]
> It worked for me, but I recall having similar issues at some point in the past. Exact steps I took:
> 
> * https://grafana.com/api/dashboards/7636/revisions/58/download in browser, gets downloaded to a file.
> * Copy the file, paste into grafana UI

It is exactly the same way I trigger this issue.

**Comment by howardjohn** [comment]
can you show in the grafana UI what the invalid part of the emoji is? I am wondering if your copy+paste somehow is mangling it

**Comment by ethernoy** [comment]
> can you show in the grafana UI what the invalid part of the emoji is? I am wondering if your copy+paste somehow is mangling it

Grafana UI does not highlight the exact invalid part. The exact step I executed was like this:

- Download dashboard JSON from grafana.com
- Open with visual studio code
- Copy all content inside the JSON and paste in Grafana UI

The following image shows the emoji in istio-service-dashboard_rev58.json after copy-paste:

![image](https://user-images.githubusercontent.com/15870761/114802515-6947be80-9dd0-11eb-9b80-65f7ccc90d0e.png)

**Comment by howardjohn** [comment]
When I copied it it was like \u012e3 or something like that - escaped. I'll
see if I can reproduce with vscode

**Comment by howardjohn** [comment]
![2021-16-04_08-23-55](https://user-images.githubusercontent.com/623453/115047128-1849d000-9e8d-11eb-9ea5-1db490737ea2.png)

works for me. On linux
