### ISSUE TITLE
Test Flake: Multicluster security tests

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#32172]
**Bug description**

Test Flake: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32165/integ-security-multicluster-tests_istio/1382383815300747264

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by ryantking** [comment]
Moving to 1.12 milestone due to recent inactivity

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34662/integ-security-multicluster-tests_istio/1427390643587518464

**Comment by stevenctl** [comment]
cc @JimmyCYJ @yangminzhu can you take a look? we see these a lot

**Comment by Kmoneal** [comment]
@incfly @yangminzhu @liminw @JimmyCYJ How is this looking for 1.12? Should it be moved to 1.13?
