### ISSUE TITLE
Add support for contains authz header matcher

### ISSUE THREAD

**Issue by dmorina** [istio/istio#32173]
It would be very helpful to be able to use the `HeaderMatcher_ContainsMatch` so that we don't have to rely on the sort order of an array header value. For example if we use `X-Forwarded-Client-Cert` to match on a SAN of the cert  and the order of the names changes the authorization policies have to be updated.

Happy to push a PR if you think that this is a good change.

**Comment by bianpengyuan** [comment]
Partially related to https://github.com/istio/istio/issues/25021 and https://github.com/istio/istio/pull/30956. Regex should also satisfy this use case I suppose.

**Comment by dmorina** [comment]
It seems like there's a lot of discussion around the regex support, I agree that regex would satisfy all use cases but my take from the discussions in that issue and PR is that it would be better to stick to wildcard matching rather than regex.

What do you think about reusing and combining the current logic for prefix and suffix matching by just checking if the string is wrapped with `*`? That way we could have `contains` support until the regex approach is approved and implemented

**Comment by bianpengyuan** [comment]
I think that makes sense. @yangminzhu ^^

**Comment by dmorina** [comment]
pushed a PR https://github.com/istio/istio/pull/32180 for this, @yangminzhu let me know what you think, thanks!
