### ISSUE TITLE
egress gateway miss inbound metrics

### ISSUE THREAD

**Issue by jiangpengcheng** [istio/istio#32196]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

egress gateway doesn't report inbound metrics(metrics with label `reporter=destination`)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
egress metrics should able to collect inboud metrics

**Steps to reproduce the bug**

I followed the official document:
1. Deploy k8s using kind:  https://istio.io/latest/docs/setup/platform-setup/kind/
2. Deploy istio: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway
3. Deploy app: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#before-you-begin
4. Deploy kiali: https://istio.io/latest/docs/tasks/observability/kiali/
5. Deploy egress gateway: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway 
6. Check kiali

![image](https://user-images.githubusercontent.com/1858477/114838296-281ed100-9e07-11eb-8381-2d7cd65121a3.png)

I think above graph missed traffic from `sleep` app to the `istio-egressgateway`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
[raja@localhost]$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (12 proxies)
```

**How was Istio installed?**
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway

**Environment where the bug was observed (cloud vendor, OS, etc)**
Physical Machine CentOS Linux release 7.9.2009 (Core)
Kind version: 0.9.0
Docker version: 20.0.1

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Egressgateway is modeled as an outbound proxy. I am not sure how Kiali handles egress gateway. @jshaughn probably would know.

**Comment by jshaughn** [comment]
Sorry, had missed this one.  Kiali doesn't really do anything special wrt egressgateway, as far as I can remember.  If there is telemetry reported in istio_requests_total or istio_tcp_sent_bytes then I would expect to see it in the graph.  Although, starting with Kiali 1.32.0 the graph does a better job of incorporating reporter=destination telemetry, earlier versions were more reliant on reporter=source.

**Comment by bianpengyuan** [comment]
Yeah I suppose in this case the sleep app proxy should report a stats with egressgateway as destination_service, which I think kiali should plot an edge for that. @jiangpengcheng could you check if there is such a time series?

**Comment by pandagodyyy** [comment]
I met same issue. I saw telemetry which destination is egress-gateway. I reported a issue https://github.com/kiali/kiali/issues/3959 in Kiali community as well
