### ISSUE TITLE
e2e-pilot failure in routing rules with websocket upgrades

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3220]
This failure is unrelated to the PR tested and affects automated tests:

https://circleci.com/gh/istio/istio/23359?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

=================== Failed =====================
routing-rules 3 errors occurred:

* routing-rules run 0 routing 100 percent to c-v1 with websocket upgrades attempt 0 expected 100 requests (+/-5) to reach v1 => Got 0
* routing-rules run 0 routing 100 percent to c-v1 with websocket upgrades attempt 1 expected 100 requests (+/-5) to reach v1 => Got 0
* routing-rules run 0 routing 100 percent to c-v1 with websocket upgrades attempt 2 expected 100 requests (+/-5) to reach v1 => Got 0

**Comment by rshriram** [comment]
This issue seems to have resolved itself. I have not seen this flake occur again. Please let me know if we need to keep this open
