### ISSUE TITLE
TestTraffic/virtualservice/shifting test flakes in multicluster

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32208]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32206/integ-pilot-multicluster-tests_istio/1382736986078449664

We are getting errors about unbalanced load. I verified the client side load balancing is correct - we send exactly 1/3 of traffic to each gw

I think this is the current state:
![2021-15-04_10-42-41](https://user-images.githubusercontent.com/623453/114914570-4ff64080-9dd7-11eb-9fe8-8384f892ee6c.png)

Basically because Envoy client will do HTTP connection pool, we may have only a single connection to the Gateways. Because its TCP routing, that connection will go to a single location. There is a 50/50 shot of both gateways choosing the same destination, at which point our test fails?

I think envoy is not always using exactly 1 connection, but even with 2 connections each its a 12.% chance of failure, and with 3 connections each 1%

cc @stevenctl

**Comment by howardjohn** [comment]
Consdiering this fixed unless we see more failures

**Comment by hzxuzhonghu** [comment]
@howardjohn Isn't it http connection? Is that connection reused?  Not sure if we set maxRequestsPerConnection to enforce recreating a new connection could fix it.

Also it is not reasonable for eastwest-gateway of cluster1 being able to access endpoints in cluster2. WDYT?

**Comment by howardjohn** [comment]
http to eastwestgateway, which has a single (or couple) connections re-used. Then eastwestgateway just sees raw TLS connection and forwards it without load balancing.

> Also it is not reasonable for eastwest-gateway of cluster1 being able to access endpoints in cluster2. WDYT?

I was initially thinking the same but am not sure. You don't need a gateway in all clusters. If pods in cluster1 will load balance between cluster1 and cluster2, then why shouldn't the gateway?

**Comment by hzxuzhonghu** [comment]
>Then eastwestgateway just sees raw TLS connection and forwards it without load balancing.
why tls connection without lb?

>. If pods in cluster1 will load balance between cluster1 and cluster2, then why shouldn't the gateway?

The tricky point is that pods can access a remote gateway and then forwarded back to the local cluster. A way to distinguish the east-west gateway from others looks more reasonable.

**Comment by howardjohn** [comment]
> why tls connection without lb

The gateway just sees tls connection, it doesn't terminate the TLS so it cannot do l7 request routing.

**Comment by howardjohn** [comment]
https://docs.google.com/document/u/0/d/1DxwqhNqxm1r3fSomyQgJWy103bv29B0ZTEvu_hZqQgc/mobilebasic?resourcekey=0-uPN2Gtx-BHvj-sAvN9SGKA#heading=h.xw1gqgyqs5b

discuss this a bit more

**Comment by hzxuzhonghu** [comment]
Great,  my understanding has been wrong for a very long time.
