### ISSUE TITLE
Mixer crashing because HandleBuilder affecting automated tests

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3221]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3218/e2e-smoke/2458/

panic: HandlerBuilder from adapter noop does not implement the required interfaces for the templates it supports: HandlerBuilder does not implement interface authorization.HandlerBuilder. Therefore, it cannot support template authorization
HandlerBuilder does not implement interface tracespan.HandlerBuilder. Therefore, it cannot support template tracespan

goroutine 1 [running]:

istio.io/istio/mixer/pkg/config.newRegistry(0xc42018a200, 0xf, 0xf, 0xc420533d20, 0x0)
	/home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/adapterInfoRegistry.go:61 +0x53e
istio.io/istio/mixer/pkg/config.AdapterInfoMap(0xc42018a200, 0xf, 0xf, 0xc420533d20, 0xc42019e620)
	/home/bootstrap/go/src/istio.io/istio/mixer/pkg/config/adapterInfoRegistry.go:73 +0x49
istio.io/istio/mixer/cmd/mixs/cmd.validatorCmd(0xc42019adb0, 0xc42018a200, 0xf, 0xf, 0x1832bf8, 0x1832bf0, 0xc4203be6c0)
	/home/bootstrap/go/src/istio.io/istio/mixer/cmd/mixs/cmd/validator.go:39 +0xec
istio.io/istio/mixer/cmd/mixs/cmd.GetRootCmd(0xc42000e090, 0x7, 0x7, 0xc42019adb0, 0xc42018a200, 0xf, 0xf, 0x1832bf8, 0x1832bf0, 0x1832fe0)
	/home/bootstrap/go/src/istio.io/istio/mixer/cmd/mixs/cmd/root.go:58 +0x310
main.main()
	/home/bootstrap/go/src/istio.io/istio/mixer/cmd/mixs/main.go:37 +0x225

**Comment by douglas-reid** [comment]
I believe this was fixed by #3219 .

**Comment by douglas-reid** [comment]
@andraxylia can you confirm?

**Comment by geeknoid** [comment]
Fixed by PR #3219
