### ISSUE TITLE
GRPC failure in istio-pilot-e2e affecting automated tests

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3222]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3212/istio-pilot-e2e/2434/

I0206 07:29:33.213] 2018-02-06T07:29:33.168258Z	info	kubectl exec t-67bdf84bfd-lsnp4 --kubeconfig pilot/pkg/kube/config -n istio-test-app-5mlzd -c app -- client -url grpc://d:7070 -count 1 
I0206 07:29:35.336] 2018-02-06T07:29:35.336304Z	info	2018/02/06 07:29:35 [0] grpcecho.Echo(message:"request #0" )
I0206 07:29:35.337] 2018/02/06 07:29:35 Error rpc error: code = Unavailable desc = all SubConns are in TransientFailure
I0206 07:29:35.337] command terminated with exit code 1
I0206 07:29:35.338] 
I0206 07:29:35.339] 2018-02-06T07:29:35.336370Z	error	client request error command "kubectl exec t-67bdf84bfd-lsnp4 --kubeconfig pilot/pkg/kube/config -n istio-test-app-5mlzd -c app -- client -url grpc://d.istio-test-app-5mlzd:7070 -count 1 " failed: "2018/02/06 07:29:35 [0] grpcecho.Echo(message:\"request #0\" )\n2018/02/06 07:29:35 Error rpc error: code = Unavailable desc = all SubConns are in TransientFailure\ncommand terminated with exit code 1\n" exit status 1 for grpc://d.istio-test-app-5mlzd:7070 in t
I0206 07:29:38.456] 2018-02-06T07:29:38.456109Z	info	2018/02/06 07:29:37 [0] grpcecho.Echo(message:"request #0" )
I0206 07:29:38.456] 2018/02/06 07:29:37 Error rpc error: code = Unavailable desc = transport is closing
I0206 07:29:38.457] command terminated with exit code 1

**Comment by xiaolanz** [comment]
I kept hitting the same error in my PR
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3214/istio-pilot-e2e/3188/

Is it disabled?

**Comment by cmluciano** [comment]
@nmittler Not sure if this is still failing frequently. Can you update the status of this issue?

**Comment by nmittler** [comment]
I don't think we're seeing this anymore.  Closing for now.
