### ISSUE TITLE
Istiod should install CA root cert in remote cluster namepaces

### ISSUE THREAD

**Issue by frankbu** [istio/istio#32244]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Istiod installs the `istio-ca-root-cert` configmap in all mesh namespaces of the primary cluster (or config cluster in the external control plane case), but it is not doing the same for remote clusters that it is also managing.
The documented primary-remote multicluster installation works anyway, because the remote cluster
is currently running its own istiod for CA, but this will change in the future.
The [external control plane multicluster instructions WIP PR](https://github.com/istio/istio.io/pull/9280) is working around the issue by manually
copying the configmaps needed to run the sample.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istiod should install the `istio-ca-root-cert` configmap in the namespaces of remote clusters it is managing.

**Steps to reproduce the bug**

1. Install istio on a primary cluster or setup an [external control plane](https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/) mesh.
2. Run `istioctl x create-remote-secret` for a second cluster, and apply the secret. For example:
    ```
    istioctl x create-remote-secret \
      --context="${CTX_SECOND_CLUSTER}" \
      --name=cluster2 \
      --type=remote \
      kubectl apply -f - --context="${CTX_PRIMARY_CLUSTER}"
   ```
3. Observe that istiod does not install the `istio-ca-root-cert` in namespaces of the second cluster.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Latest.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by stevenctl** [comment]
https://github.com/istio/istio/blob/5f5cd773bbcedfb91ae1030211c08d49a9a7d67b/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L236-L245

We _do_ support this, but it's gated by a feature flag `EXTERNAL_ISTIOD`

There are a couple of problems with this approach:
* Many istiods in many clusters may compete over this lock – we need a better solution for leader election that gives some priority associated with locality
* We don't have a way to tell different "remote" clusters apart. Istiod needs to read from both primary and remote clusters, but we only want to run this controller for remotes. Right now, it's possible to have 2 primary clusters that are running the namespace controller for one another.

**Comment by frankbu** [comment]
@stevenctl I tried turning on the `EXTERNAL_ISTIOD` feature flag. When I add a remote cluster, the above code runs but generates the following error:
```
2021-04-30T19:05:31.132747Z	info	kube	Initializing Kubernetes service registry "cluster2"
2021-04-30T19:05:31.133292Z	info	Number of remote clusters: 1
2021-04-30T19:05:31.133772Z	info	kube	joining leader-election for istio-namespace-controller-election in external-istiod on cluster cluster2
2021-04-30T19:05:31.133894Z	info	klog	attempting to acquire leader lease external-istiod/istio-namespace-controller-election...
2021-04-30T19:05:31.151874Z	error	klog	error retrieving resource lock external-istiod/istio-namespace-controller-election: configmaps "istio-namespace-controller-election" is forbidden: User "system:serviceaccount:external-istiod:istio-reader-service-account" cannot get resource "configmaps" in API group "" in the namespace "external-istiod"
2021-04-30T19:05:31.154081Z	error	klog	k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1.ValidatingWebhookConfiguration: failed to list *v1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:external-istiod:istio-reader-service-account" cannot list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
```

IIUC, it seems to be trying to lock the `istio-namespace-controller-election` configmap, which doesn't exist yet on the new cluster. I thought istiod was supposed to create the configmap and root CA.

This happens immediately after running step 1 in these instructions: http://localhost:1313/latest/docs/setup/additional-setup/external-controlplane/#register-the-new-cluster

Can you tell/explain what's going on?

**Comment by stevenctl** [comment]
We only allow one istiod to manage the configmap at a time, so we have that lock.

I think some profile or other creates the cluster role with the permission for that.

**Comment by frankbu** [comment]
@stevenctl, the lock makes sense, and it looks like the cluster role is present in the second cluster (the remote cluster that's being added), but it seem like the problem is that the `istio-namespace-controller-election` and `istio-leader` configmaps don't exist on the second cluster. How and when are they supposed to get created?

**Comment by stevenctl** [comment]
The library will create the cm:

https://github.com/kubernetes/client-go/blob/8c8fa70f7a2acc191d4787327639621f69992efd/tools/leaderelection/resourcelock/configmaplock.go#L71

if it doesn't exist:

https://github.com/kubernetes/client-go/blob/8c8fa70f7a2acc191d4787327639621f69992efd/tools/leaderelection/leaderelection.go#L326-L333

**Comment by stevenctl** [comment]
The issue is permissions:

https://github.com/istio/istio/blob/32c9b0993c04a7bd75f4acb900ebaf8abd7d81e3/manifests/charts/base/templates/clusterrole.yaml#L152-L162
