### ISSUE TITLE
fix cross-cluster gRPC in security tests

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32280]
https://github.com/istio/istio/blob/a26f344ec07efc4a435ca086347acf68b4d1eb23/tests/integration/security/util/connection/checker.go#L48-L49

This is one of many cases where we have some skip for multi-cluster without an explanation or issue attached.

**Comment by brian-avery** [comment]
@stevenctl can you please provide some more detail on what this is needed for? Thanks

**Comment by stevenctl** [comment]
Added slightly more detail – but it's hard to tell if this is a known limitation, a bug or something else. There are a lot of skips in our test that aren't linked back to an issue to investigate/unskip.
