### ISSUE TITLE
test framework: support external istiod

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32283]
https://github.com/istio/istio/blob/88a2bfb3bd8e0010229ee66befc4e56b326c2a3a/tests/integration/multicluster/centralremotekubeconfig/main_test.go#L38

Currently, the only coverage for external istiod exists in a single test suite. This suite only covers a simple gateway test.

Instead, the framework should support clusters that are both `remote` and `config` clusters. This can be configured today using the cluster Config API via topology files (such as [multicluster.json](https://github.com/istio/istio/blob/228352ca12473273b1d67dd81f322376dfb4bdc0/prow/config/topology/multicluster.json)) . 

https://github.com/istio/istio/blob/e094796708289700c4133c05c22a2f81bfefc5f8/pkg/test/framework/components/cluster/config.go#L35-L36

If a cluster has `ConfigClusterName` set to a different value than it's `PrimaryClusterName`, that means the `ConfigCluster` is not running the control plane, and should be treated as an external control plane. 

Our istio-installation logic should take this into account, and set the install values accordingly.

Simply we need to:

* Add topology file like: https://github.com/istio/istio/pull/34142/files with this content:

```json
[
  {
    "kind": "Kubernetes",
    "clusterName": "external-control-plane",
    "configClusterName": "config-cluster",
    "podSubnet": "10.10.0.0/16",
    "svcSubnet": "10.255.10.0/24",
    "network": "network-1"
  },
  {
    "kind": "Kubernetes",
    "clusterName": "remote",
    "podSubnet": "10.20.0.0/16",
    "svcSubnet": "10.255.20.0/24",
    "network": "network-1",
    "primaryClusterName": "config-cluster",
    "meta": {
      "fakeVM": false
    }
  },
  {
    "kind": "Kubernetes",
    "clusterName": "remote",
    "podSubnet": "10.30.0.0/16",
    "svcSubnet": "10.255.30.0/24",
    "network": "network-2"
  }
]
```

**Comment by stevenctl** [comment]
cc @linsun @irisdingbj @ericvn @frankbu 
The `centralremotekubeconfig`integ-multicluster-k8s-tests_istio ` prow job. 

To promote external istiod, we should support the customizations inside that `TestMain` within the greater test framework. 

We have the concepts in the test framework topology, but not the implementation of the install steps. 

This will likely look one of the following:
1. Adding another 3 jobs for pilot, security, telemetry where the topology contains 3 clusters:

  * external istiod cluster
  * config cluster
  * remote cluster (non-config)

2. Adding 3 more clusters to our current multicluster jobs.

Expanding the # of jobs is probably the better choice, as 6 kind clusters per job plus a few `^2` scaling in # of calls/subtests would be too much for the test times/test infra. 

The effort to do this is probably not trivial. Do we have anyone who can take this on?

**Comment by stevenctl** [comment]
@ericvn, continuing conversation here so we don't lose context/message history

When you say base integration test, are you referring to integration/multicluster/base? Ideally we don’t bother fixing that up, we want to get rid of that entire multicluster/ job anyway.  The approach we should be taking is having jobs like: integ-externalistiod-<pilot|security|telemetry>

The framework has these [topology files](https://github.com/istio/istio/blob/d3f9ceaa54bdabb736583067263dc001063824aa/prow/config/topology/multicluster.json#L10) that are read both by the kind-provisioner and by the framework itself. 
For the in-framework part, we look at fields like primaryClusterName and configClusterName to determine how to do the install (see [operator.go](https://github.com/istio/istio/blob/cabd1c2454702585426e5ddfa08144280ca299b6/pkg/test/framework/components/istio/operator.go#L6)) 

Right now, the [centralremotekubeconfig](https://github.com/istio/istio/blob/389164c898e594797e66db8593fda8ca5cdd3183/tests/integration/multicluster/centralremotekubeconfig/main_test.go#L38) suite overrides those values at runtime. 

The first step should be creating a new job definition in "skip" mode + a new topology file that covers external istiod and runs the ITs in `pilot` directory and troubleshooting the install-time issues.

**Comment by ericvn** [comment]
@stevenctl Yes, we were trying to just run the `integration/multicluster/base` test locally, but with IKS clusters specified or `kind` clusters. I may or may not have been successful using some kind clusters today. Running within a build container, I actually had:
```
build-tools:/work$ ARTIFACTS=artifacts  TEST_ENV=kind go test -tags integ ./tests/integration/multicluster/... --istio.test.kube.config=$PWD/artifacts/kubeconfig/primary,$PWD/artifacts/kubeconfig/remote,$PWD/artifacts/kubeconfig/cross-network-primary --istio.test.kube.topology=$PWD/prow/config/topology/multicluster.json --istio.test.ci=true
?   	istio.io/istio/tests/integration/multicluster	[no test files]
ok  	istio.io/istio/tests/integration/multicluster/base	68.099s
ok  	istio.io/istio/tests/integration/multicluster/centralremotekubeconfig	0.162s
```
and if I removed the .skip from centralremotekubeconfig:
```
build-tools:/work$ ARTIFACTS=artifacts  TEST_ENV=kind go test -tags integ ./tests/integration/multicluster/centralremotekubeconfig/... --istio.test.kube.config=$PWD/artifacts/kubeconfig/primary,$PWD/artifacts/kubeconfig/remote,$PWD/artifacts/kubeconfig/cross-network-primary --istio.test.kube.topology=$PWD/prow/config/topology/multicluster.json --istio.test.ci=true
ok  	istio.io/istio/tests/integration/multicluster/centralremotekubeconfig	327.935s
```
Running from the Mac command line I usually see more information with a failure:
```
ARTIFACTS=artifacts  TEST_ENV=kind go test -tags integ ./tests/integration/multicluster/base/... \
   --istio.test.kube.config=$PWD/artifacts/kubeconfig/primary,$PWD/artifacts/kubeconfig/remote,$PWD/artifacts/kubeconfig/cross-network-primary  \
  --istio.test.kube.topology=$PWD/prow/config/topology/multicluster.json --istio.test.kube.loadbalancer=false
2021-07-09T21:07:56.321626Z	info	tf	Using clusterConfigs file: /Users/ericvn/work/go/src/istio.io/istio/prow/config/topology/multicluster.json.
2021-07-09T21:07:56.321691Z	info	tf	=== Test Framework Settings ===
2021-07-09T21:07:56.321710Z	info	tf	TestID:            multicluster_base
RunID:             173afa6e-fa35-4b76-a651-c48911cee234
NoCleanup:         false
BaseDir:           /var/folders/sy/1lbtjp6n6bn5y530lrf5x9140000gn/T/
Selector:
FailOnDeprecation: false
CIMode:            false
Retries:           0
StableNamespaces:  false
Revision:
SkipVM:            false
Compatibility:     false
Revisions:

2021-07-09T21:07:56.321715Z	info	tf	===============================
2021-07-09T21:07:56.321887Z	info	tf	Test run dir: /var/folders/sy/1lbtjp6n6bn5y530lrf5x9140000gn/T/multicluster-base-173afa6efa354
2021-07-09T21:07:56.322018Z	info	tf	Test Framework Kubernetes environment Settings:
Kubeconfigs:           [/Users/ericvn/work/go/src/istio.io/istio/artifacts/kubeconfig/primary /Users/ericvn/work/go/src/istio.io/istio/artifacts/kubeconfig/remote /Users/ericvn/work/go/src/istio.io/istio/artifacts/kubeconfig/cross-network-primary]
LoadBalancerSupported:      false
ControlPlaneTopology: map[]
NetworkTopology:      map[]
ConfigTopology:      map[]

2021-07-09T21:07:56.322036Z	info	tf	=== BEGIN: Building clusters ===
2021-07-09T21:07:56.325951Z	info	tf	Built Cluster:
Name:               primary
StableName:         primary
Kind:               Kubernetes
PrimaryCluster:     primary
ConfigCluster:      primary
Network:            network-1
Filename:           /Users/ericvn/work/go/src/istio.io/istio/artifacts/kubeconfig/primary
.....
2021-07-09T21:10:21.538952Z	info	tf	=== BEGIN: Setup: 'multicluster_base' ===
2021-07-09T21:10:51.546931Z	error	tf	Test setup error: Post "https://172.21.0.3:6443/api/v1/namespaces": dial tcp 172.21.0.3:6443: i/o timeout
2021-07-09T21:10:51.546950Z	info	tf	=== FAILED: Setup: 'multicluster_base' (Post "https://172.21.0.3:6443/api/v1/namespaces": dial tcp 172.21.0.3:6443: i/o timeout) ===
2021-07-09T21:10:51.546956Z	error	tf	Exiting due to setup failure: Post "https://172.21.0.3:6443/api/v1/namespaces": dial tcp 172.21.0.3:6443: i/o timeout
2021-07-09T21:12:21.552260Z	error	tf	Error during close: 1 error occurred:
	* Delete "https://172.21.0.4:6443/api/v1/namespaces/mc-reachability-1-12217": dial tcp 172.21.0.4:6443: i/o timeout


FAIL	istio.io/istio/tests/integration/multicluster/base	121.550s
FAIL
```

**Comment by ericvn** [comment]
When using IKS clusters, we see items like:
```
2021-07-09T20:44:56.352587Z	info	tf	=== FAILED: Deploy Istio in 34.011750635s [Suite=multicluster_base] ===
2021-07-09T20:44:56.352656Z	error	tf	=== Dumping Istio Deployment State...
2021-07-09T20:44:56.352683Z	error	tf	=== Dumping Namespace mc-reachability-1-64539 State...
2021-07-09T20:44:56.352708Z	error	tf	=== Dumping Namespace cluster-local-2-42963 State...
2021-07-09T20:45:04.442589Z	error	tf	Test setup error: 2 errors occurred:
	* failed generating eastwestgateway operator yaml: exit status 1
	* failed generating eastwestgateway operator yaml: exit status 1
```

**Comment by ericvn** [comment]
Just want to document https://github.com/istio/istio/pull/34142 was an attempt to use the framework and make some changes to make a valid external Istiod (centralremotekubeconfig) test. The test would actually create the ingress gateway on the `remote` system and make sure the pod becomes ready.

Currently, the replicates fails to start the pod as it cannot connect to the istiod service:
```
  Warning  FailedCreate  27s (x14 over 68s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "object.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": cannot route to service with ClusterIP "None"
```
Earlier, before removing the validation URL, we ran into an issue:
```
Error creating: Internal error occurred: failed calling webhook "object.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp: lookup istiod.istio-system.svc on 192.168.65.2:53: no such host
```
where `192.168.65.2` is the API Server which doesn't work with cluster services.

**Comment by ericvn** [comment]
#34142 (centralremotekubeconfig) is now working.

**Comment by ryantking** [comment]
@ericvn @GregHanson What's the status on this issue? Looks like it'll be done before the 1.11 code freeze (8/3) or can we bump it back to the 1.12 milestone?

**Comment by ericvn** [comment]
Closing this issue as we have some tests.
