### ISSUE TITLE
Make CNI upgrade safe

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#32298]
Currently CNi upgrade is performed in place. This generally works ok, since istio iptable does not have much version incompatibility changes. However to prevent future breaking changes, we need to make sure istio-iptable have version guards, and istio-cni could feed proxy version info into istio-iptable. We'd also need to make separated installation of CNI as recommended, and require user to upgrade CNI first before adding new control plane revisions to prevent tricky race conditions.

cc @mandarjog @howardjohn @therealmitchconnors @lambdai

**Comment by bianpengyuan** [comment]
We should treat this one of the CNI beta graduate requirements.

**Comment by mandarjog** [comment]
1. CNI version 1.11 should work with controlplane version 1.10 and 1.11.
2. Add tests (even right away), that run CNI version 1.10 with Istio version 1.9. We may not claim support, but we will know the 
 modes of failure.

**Comment by zhlsunshine** [comment]
Hi @bianpengyuan,  I noticed that the PR for this issue need to be approved, shall we move this issue to 1.12?
