### ISSUE TITLE
Sidecar injection doc: Broken link to OKD info on s2i builds

### ISSUE THREAD

**Issue by birbilis** [istio/istio#32316]
**Bug description**

At
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
the link for "OpenShift Source to Image Builds is broken

need to change from
https://docs.okd.io/latest/builds/understanding-image-builds.html#build-strategy-s2i_understanding-image-builds
to
https://docs.okd.io/latest/cicd/builds/understanding-image-builds.html#builds-strategy-s2i-build_understanding-image-builds
note the missing /cicd/ part in the URL (rest seems to be the same at first glance)

[x] Docs

**Comment by shamsher31** [comment]
@birbilis Thanks for reporting. Looks like it's a documentation issue, can you please open the issue in https://github.com/istio/istio.io?

**Comment by birbilis** [comment]
thanks for the pointer, submitted to https://github.com/istio/istio.io/issues/9566
