### ISSUE TITLE
Envoy endpoints contain removed pod (service) ip

### ISSUE THREAD

**Issue by JackTroy** [istio/istio#32310]
[bug-report.zip](https://github.com/istio/istio/files/6341658/bug-report.zip)
**Bug description**
I install Istio in three k8s clusters as multi-primary over a single network according to https://istio.io/latest/docs/setup/install/multicluster/multi-primary/.

Then I deploy helleworld and sleep service following https://istio.io/latest/docs/setup/install/multicluster/verify/.
After helloworld service at other clusters except cluster-1 are removed, envoy endpoints of helloworld service still contain removed helloworld pod IP of other cluster.

```
$ kubectl get pod  -n sample -o wide --context="${CTX_CLUSTER1}"
NAME                             READY   STATUS    RESTARTS   AGE     IP            NODE             NOMINATED NODE   READINESS GATES
helloworld-v1-776f57d5f6-pj649   2/2     Running   0          3h27m   172.20.4.10   192.168.50.154   <none>           <none>
sleep-557747455f-6f8cb           2/2     Running   0          3h27m   172.20.3.11   192.168.50.155   <none>           <none>
$ kubectl get svc -n sample -o wide --context="${CTX_CLUSTER1}"
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE     SELECTOR
helloworld   ClusterIP   10.68.239.91    <none>        5000/TCP   3h29m   app=helloworld
sleep        ClusterIP   10.68.163.209   <none>        80/TCP     3h28m   app=sleep
$ istioctl --context="${CTX_CLUSTER1}" proxy-config endpoints sleep-557747455f-6f8cb.sample --cluster "outbound|5000||helloworld.sample.svc.cluster.local"
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
172.20.3.5:5000      HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.20.4.10:5000     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

$ kubectl get pod  -n sample -o wide --context="${CTX_CLUSTER2}"
No resources found in sample namespace.
$ kubectl get pod  -n sample -o wide --context="${CTX_CLUSTER3}"
No resources found in sample namespace.
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Expected behavior**
Envoy endpoints should contain available target ips.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (3 proxies)
$ kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5
```

**How was Istio installed?**
Multi-primary on single network

**Environment where the bug was observed (cloud vendor, OS, etc)**
Self-hosted

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Your istiod logs show a bunch of api server errors, to 192.168.199.131. Is that cluster 3 perhaps, where that IP is still showing up? Perhaps we fail to connect to api server so we have stale data.

**Comment by JackTroy** [comment]
@howardjohn You are right. Cluster 1 lost network connection to cluster 3 (192.168.199.131). After fixing the network, everything is ok.

**Comment by ramaraochavali** [comment]
Seems this is closed.
