### ISSUE TITLE
App Envoy to Pilot/Mixer Envoy communication error in system upgrade

### ISSUE THREAD

**Issue by wattli** [istio/istio#3232]
Currently if the control plane is disabled with mTLS, then all App Envoy will not talk to pilot/mixer with mTLS, however if the control plane is upgrade with mTLS enabled, then every regular App Envoy will not be able to talk to pilot/mixer, since their config was not updated (which was generated in bootstrapping time).

The solution is to let pilot/mixer expose two ports, one for http the other for https. And App Envoy will be configured with proper ports. 

This requires for both istioctl and initializer side change, but we can focus on istioclt first. Hopefully initializer change is similar

Relevant person are cc'ed @costinm @wattli

**Comment by ayj** [comment]
For `kube-inject` the internal template needs to be updated [here](https://github.com/istio/istio/blob/41203341818c4dada2ea5385cfedc7859c01e957/pilot/pkg/kube/inject/mesh.go#L20). For automatic injection the template files should be updated [here](https://github.com/istio/istio/blob/41203341818c4dada2ea5385cfedc7859c01e957/pilot/pkg/kube/inject/mesh.go#L20) and [here](https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl)

**Comment by wattli** [comment]
https://github.com/istio/api/pull/370 introduces the proto change by adding one more address for pilot and mixer.

**Comment by andraxylia** [comment]
this is fixed now.
