### ISSUE TITLE
Allow opt-out of multicluster SDS

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32364]
Currently istio requires permission to read Secret from remote clusters which is used for SDS. 
For many users, this permission is too much. 

We need to:
* Clarify what istiod is doing when it reads these secrets in docs
* Allow turning this off. In [Costin's comment here](https://docs.google.com/document/d/1eS72Ozu_tREk3Zw5PTrPA8oGeAMis1VwvkgTgLgUr7g/edit?resourcekey=0-0OnlRQXkFqL09ZXyqMhpog&disco=AAAAL6Lre3Y), he suggests removing this entirely. 
  * How would this look? Would the remote clusters receive SDS using certs/keys that exist in their primary clusters? 
  * As a first step, could we remove this permission for multi-primary? 

cc @howardjohn @nmittler @costinm

**Comment by S-Chan** [comment]
IIUC, istiod is reading secrets for gateway SDS only. As a stopgap, could we add a feature flag to opt-out of istiod SDS entirely? This is how we avoided granting the secret permission previously, but it was removed in https://github.com/istio/istio/pull/28672/files#diff-91e0a18a58ea36d2c656d7b2706c52917a74103820c07fc843f48a110c847678L434.

This assumes that no gateways are in use.
