### ISSUE TITLE
[release-1.9] TestPassthroughFilterChain flakiness

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32365]
https://github.com/istio/istio/pull/32345

This test is extremely flaky and takes several retests to get a PR merged. 

Assigned several people to get visibility.

**Comment by yangminzhu** [comment]
do we know when the flakiness start to happen? I remember the test is added some time ago and we didn't see any flakiness before.

**Comment by stevenctl** [comment]
https://testgrid.k8s.io/istio_release-1.9_istio_postsubmit#integ-security-multicluster-tests_istio_release-1.9_postsubmit

It's been a while, my guess is https://github.com/istio/istio/pull/31742 but it's hard to be certain.

**Comment by stevenctl** [comment]
We do see this flake in master as well,just not as frequently: https://testgrid.k8s.io/istio_istio_postsubmit#integ-security-multicluster-tests_istio_postsubmit

**Comment by stevenctl** [comment]
So previously the config was all applied upfront rather than per-subtest? 

Maybe we can add a util to `echotest` that allows frontloading the setup? 


```
echotest.New(...).
  SetupForPair(perConfigSetup).
  UpfrontSetup().
  Run()
```

Setup for pair would produce distinct configs, and upfront setup would cause all those to be run sooner than later. I think several tests would get a speedup from this as well. 

WDYT @JimmyCYJ ?
