### ISSUE TITLE
test grid for release branches

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#32363]
For master we have https://testgrid.k8s.io/istio_istio_postsubmit which allows us to check if a failing test is flaky at a glance. This is something that would be nice to have for release branches to more easily differentiate flakes/broken tests in-tree from actual failures caused by PRs. For now we rely on https://prow.istio.io/?repo=istio%2Fistio&job=*release-1.9*

**Comment by howardjohn** [comment]
We do, see https://testgrid.k8s.io/istio_release-1.9_istio_postsubmit, etc. You can find it from the top level page https://testgrid.k8s.io/

**Comment by stevenctl** [comment]
Thanks! cc @jacob-delgado
