### ISSUE TITLE
[1.9.1] Sidecar inject pod notation override not working

### ISSUE THREAD

**Issue by njTaljaard** [istio/istio#32388]
**Description**
Sidecar is not injected on designated workloads.

Namespace label: istio-injection: disabled
Pod annotation: sidecar.istio.io/inject: true

From documentation: [https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#policy](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#policy)

**Affected product area**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected results**
To disable the namespace to not auto inject to all jobs, and add a pod annotation to only inject sidecars to preferred workloads.
`
matchPolicy: Equivalent
name: object.sidecar-injector.istio.io
namespaceSelector:
matchExpressions:
- key: istio-injection
operator: DoesNotExist
- key: istio.io/rev
operator: DoesNotExist
objectSelector:
matchExpressions:
- key: sidecar.istio.io/inject
operator: In
values:
- "true"
- key: istio.io/rev
operator: DoesNotExist
reinvocationPolicy: Never
rules:
- apiGroups:
- ""
apiVersions:
- v1
operations:
- CREATE
resources:
- pods
scope: '*'
sideEffects: None
timeoutSeconds: 10
`

**Steps to reproduce the bug**
Namespace label: istio-injection: disabled
Pod annotation: sidecar.istio.io/inject: true

**Version**
istio:
  client version: 1.8.1
  control plane version: 1.11-alpha.938c80bf9f6e738d17117e406f8a6a62a20c3550
  data plane version: 1.11-alpha.938c80bf9f6e738d17117e406f8a6a62a20c3550 (2 proxies), 1.9.1 (1 proxies)

kubectl:
  Client Version: v1.17.0
  Server Version: v1.17.17

helm:
  v3.5.4+g1b5edb6

**How was Istio installed?**
Helm installation

**Environment where the bug was observed (cloud vendor, OS, etc)**
kubeadm cluster on vmware
Ubuntu 20.04 VMs for cluster members

**Comment by howardjohn** [comment]
This is working as expected. You can enable the behavior you want in 1.10, or 1.9 with `values.sidecarInjectorWebhook.useLegacySelectors=false`.

See https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

You would not label the namespace, then *label* (not annotate) the pod `sidecar.istio.io/inject=true`.

**Comment by njTaljaard** [comment]
Sorry for the delay, I'm currently running 1.10.0-rc.0 i can confirm that it works. 
NO label on the Namespace
Label in your deployment template section.
