### ISSUE TITLE
TestRequestAuthentication test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32392]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1385260440560340992
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/1385260440539369472

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32295/integ-security-multicluster-tests_istio/1385086884895526912

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32377/integ-security-multicluster-tests_istio/1385364747473391616

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1385367698736680960
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1385349491812470784
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1385336916601212928

**Comment by howardjohn** [comment]
Any updates on this @JimmyCYJ ? It is blocking a lot of PRs

**Comment by yangminzhu** [comment]
@JimmyCYJ could you enable the TestRequestAuthentication test and only disable those flaky ones (I think it's only vm being flaky)? This a very important e2e tests that covers the core RequestAuthentication policy, we cannot just keep it skipped for months.
