### ISSUE TITLE
Istiod error verifying certificate with intermediates

### ISSUE THREAD

**Issue by scmeggitt** [istio/istio#32403]
**Bug description**
We observed a certificate verification error in istiod when using the Kubernetes RA and our own CA controller: 
```
failed to verify the certificate chain: x509: certificate signed by unknown authority
````
Analysis: This certificate was signed by an intermediate which is concentrated to the leaf in the k8s CertificateSigningRequest status.Certificate field populated by the CA controller. However, istiod only parses the leaf from status.Certificate and does not pass in the intermediate when it calls [*Certificate.verify()](https://golang.org/pkg/crypto/x509/#Certificate.Verify).

Proposal: Parse the leaf certificate and pool of intermediate certs from status.Certificate in [readSignedCertificate()](https://github.com/istio/istio/blob/6e4665c22b35447ab2c4509b37b4009b319ba945/security/pkg/k8s/chiron/utils.go#L262) . Any pem block following the first PEM block in status.Certificate should be added to the intermediate certificate pool. Finally, the intermediate certificate pool will be passed into [*Certificate.verify()](https://golang.org/pkg/crypto/x509/#Certificate.Verify) using the `opts.Intermediates` option.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When istiod is running as an RA, it should be able to verify certificates with intermediates

**Steps to reproduce the bug**

**Version** 
istio 1.9

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

**Comment by shankgan** [comment]
duplicate of https://github.com/istio/istio/issues/34218
