### ISSUE TITLE
istio sidecar consuming high CPU

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#32417]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
![image](https://user-images.githubusercontent.com/2241753/115831532-4eb2bc80-a444-11eb-9bd4-7a19e8de9a53.png)

istio sidecar consuming high CPU
Request per second: 1400
[envoy.prof.tar.gz](https://github.com/istio/istio/files/6363375/envoy.prof.tar.gz)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[*] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio:
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (2972 proxies)

kubernetes:
Client Version: v1.15.10
Server Version: v1.16.3

**How was Istio installed?**

istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by cocotyty** [comment]
![image](https://user-images.githubusercontent.com/2241753/115833013-262bc200-a446-11eb-99bd-ee36c35ef924.png)
@bianpengyuan I don't know why wasm log  used so much cpu.

**Comment by bianpengyuan** [comment]
The log call is used to generate Istio stats, which unfortunately involves many copies operation and not cheap.

**Comment by cocotyty** [comment]
> The log call is used to generate Istio stats, which unfortunately involves many copies operation and not cheap.

Maybe istio-proxy could provide a way that not using wasm.
