### ISSUE TITLE
Add more configurability on what should be traced

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#32423]
**Describe the feature request**
Istio's tracing feature only has a single know to determine how much is traced for a specific application: the sampling rate.
However, it would be very useful if flexible filters could be added to limit what is being traced. For example, for some services we are only interested in starting traces for Ingress traffic only. In other cases, we may only be interested in starting traces for calls to specific URLs (i.e. tracing the /metrics URL or js/png/css URLs is not very useful).
Traces, as seen in tracing backends like Stackdriver, seem to have a lot of labels that could be useful to filter on. Of course, the filters should also apply when a new trace is initiated, not when it is part of an existing trace (where sampled header is set to 1)

**Describe alternatives you've considered**
Alternative would be to implement this in each application and not use Istio's tracing feature.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
@rolandkool how are you currently segmenting that traffic?  are you using Istio's existing APIs for handling js/png/css URLs?  would adding `Tracing` config to `HTTPRoute` meet your use case?

The new Telemetry API should allow you to set sampling to 0 for non-ingress workloads, which I think meets part of your request.

**Comment by douglas-reid** [comment]
@zioproto that's one possibility. we don't have route-level tracing configuration option (beside EnvoyFilter hacking) at the moment. i'm trying to gather requirements and make sure we address what is being asked for. Do you use `HTTPRoute` to separate health-checks etc. already?

**Comment by rolandkool** [comment]
We currently don't use a lot of traffic routing, but that what we have, utilizes VirtualService. I think using a VirtualService could work for us as a way to configure more fine grained tracing. Other option would be to use the proxy config, but perhaps that makes implementation more difficult.
Would using a VirtualService make it possible to only start tracing for incoming calls?

**Comment by douglas-reid** [comment]
@rolandkool it is one possible way of doing it. the new Telemetry API was going to introduce a selection mechanism based on port, traffic direction, and protocol, but we left it out to start. that would be a different way of doing it. it wouldn't provide route-level filtering, however.

**Comment by rolandkool** [comment]
Hi Douglas,

I'm getting more and more feedback from our users that there is strong desire to be able to configure which URLs/endpoints need to be traced and which should be ignored. Example of URLs for which permanent tracing is not very useful are metrics URLs (for Prometheus), internal pages and health checks. Any idea if something like this could make it into 1.11?

**Comment by douglas-reid** [comment]
For 1.11, probably not. The cut off for 1.11 is the end of this week. We've had some discussion about adding a flag somewhere for disabling telemetry for admin ports. We've also talked about adding support for linking to metrics config in route configuration, etc. That _could_ be something we shoot for in 1.12.

**Comment by rolandkool** [comment]
@douglas-reid could this issue be kept open? We'd still very much like to see this functionality end up in the new Telemetry API

**Comment by douglas-reid** [comment]
Yes. Let's leave this open.

**Comment by rolandkool** [comment]
@douglas-reid as discussed via chat, will this feature include the possibility to use `listener_direction` wasm attribute?

**Comment by rolandkool** [comment]
https://github.com/istio/istio/issues/37665 was created for the direction-based filtering
