### ISSUE TITLE
Improve CNI supportability

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#32437]
Currently CNI is not very easy to debug. This issue various supportability improvements that will be needed for CNI beta graduation.

* Add label / prefix to CNI binary (istio-cni, istio-iptable) log, so that they can be easily filtered out from other kubelet logs.
* Collect better signals from istio-cni and istio-iptable plugin. The only CNI related metric we collected right now is pod repaired. We need to do some research on whether it is possible to collect metrics from cni binaries. Some ideas such as cni binaries write to a host file, istio-install periodically read and parse the file, and generates z pages or stats based on that. A default dashboard should also be provided. This might borrow the Calico's [logging solution](https://github.com/projectcalico/cni-plugin/blob/7495c0279c34faac315b82c1838bca638e23dbbe/internal/pkg/utils/utils.go#L710).
* istioctl integration, such as command to collect logs, get pod repaired, and bug report tools, etc.

**Comment by bianpengyuan** [comment]
cc @mandarjog @therealmitchconnors @howardjohn @stewartbutler @ostromart  Please add anything that you think will be valuable for CNI supportability.

**Comment by bianpengyuan** [comment]
This is done.

**Comment by believening** [comment]
teeToUDSServer only returns a zapcore.Core, but check the err

https://github.com/istio/pkg/blob/fbcf820ec6e9beb2de2928e83d70d103c920b77f/log/config.go#L354-L364
```	
	if options.teeToUDSServer {
		// build uds core.
		core = teeToUDSServer(core, options.udsSocketAddress, options.udsServerPath)
		if err != nil {
			return err
		}
		captureCore = teeToUDSServer(captureCore, options.udsSocketAddress, options.udsServerPath)
		if err != nil {
			return err
		}
	}
```
