### ISSUE TITLE
Provide an option to exclude namespaces from ConfigMap creation

### ISSUE THREAD

**Issue by DamianFekete** [istio/istio#32460]
**Describe the feature request**
Please provide an option to exclude namespaces from ConfigMap creation/update and/or limit the rate of logging of the following information.

In our cluster Istio doesn't have the permission to create `ConfigMaps` in all namespaces (for example in `kube-system`). Because of that, it logs every second this message for each namespace where the create action is denied:
```
2021-04-26T09:22:47.847447Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps is forbidden: 
User "system:serviceaccount:istio-system:istiod-service-account" cannot create resource "configmaps" in API group "" in the namespace "kube-system": 
["You're not allowed to create/update/delete/exec on namespaced resources in kube-system and xxxx-system"]), retry after delay 1s
```

This spams the logs with unwanted information.

**Describe alternatives you've considered**
I've asked in the forum for a workaround https://discuss.istio.io/t/how-to-exclude-namespaces-from-creation-of-configmap-with-root-certificate/9614 and I've also checked the source code (`\pilot\pkg\serviceregistry\kube\controller\namespacecontroller.go`) to no avail.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
What Kubernetes platform is blocking the permission? `You're not allowed to create/update/delete/exec on namespaced resources in ` does not seem like a standard k8s one.

@lei-tang should we just not retry on RBAC denied?

**Comment by lei-tang** [comment]
There are a few possible options to address the issue (first two have been mentioned above):
-  Provide an option to exclude namespaces from ConfigMap creation/update and/or limit the rate of logging of the following information.
- If the ConfigMap creation failure is caused by the lack of RBAC permission, print the error log and do not retry.
- Provide an option to configure the maximum number of retries for ConfigMap creation.

**Comment by DamianFekete** [comment]
@howardjohn, we're deploying in a K8s cluster (v1.20.5-xyz) that has a custom deny policy for two namespaces (implemented using https://github.com/c445/kubernetes-policy-controller and https://github.com/open-policy-agent/opa).

**Comment by vanzin** [comment]
RBAC is not the only issue this would help with. In our cluster we create many (multiple thousands) of namespaces, many of which are short lived, where we run things that don't need istio at all. istiod has a very hard time keeping up with that. Worse, if it doesn't create the config map before the namespace goes away, it will forever requeue the internal task to try to create that config map. This creates an ever-increasing list of tasks in istiod's queue, tasks which will never succeed. We have to periodically kill istiod to get around that.

istio 1.4 (I think) supported a namespace label (`ca.istio.io/override`) which IIRC caused istio to ignore the namespace completely. That option seems to have gone away in 1.5 and I couldn't find anything to replace it.
