### ISSUE TITLE
Issue with URI resolution in istio 

### ISSUE THREAD

**Issue by saradaathavale** [istio/istio#32463]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ x] Test and Release
[ x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I have a gateway bpsportal-gateway. I have two virtual service configuration.yaml. onevs.yaml has uri /bpsconnect and related service is bpsconnect service. Two vs.yaml has /bpsconnect038 URI and related service is bpsconnect038. When accessing /bpsconnect038 from browser, bpsconnect038 should be invoked. But bpsconnect is getting routed which can be seen in telemetry log.

**Steps to reproduce the bug**
Create a gateway bpsportal-gateway. Create two virtual service configuration.yaml. onevs.yaml has uri /bpsconnect and related service is bpsconnect service. Two vs.yaml has /bpsconnect038 URI and related service is bpsconnect038. Access bpsconnect038 from browser. The request gets routed to bpsconnect.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[dcosadmin@bsgclvmebootp1 bin]$ ./istioctl version --remote
client version: 1.2.6
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
[dcosadmin@bsgclvmebootp1 bin]$ helm version --short --tiller-namespace=kube-helm
Client: v2.14.2+ga8b13cc
Server: v2.14.2+ga8b13cc

**How was Istio installed?**
Not sure. Was done by a resource who left the team
**Environment where the bug was observed (cloud vendor, OS, etc)**
Red Hat Enterprise Linux Server release 7.9 (Maipo)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
My istio version does not have istiod. Please let me know what logs I should provide. I will be attaching the required information.

**Comment by howardjohn** [comment]
Istio 1.2 was EOL almost 2 years ago, sorry wecannot help with this version. https://istio.io/news/support/announcing-1.2-eol/

**Comment by saradaathavale** [comment]
> Istio 1.2 was EOL almost 2 years ago, sorry wecannot help with this version. https://istio.io/news/support/announcing-1.2-eol/

Thank you for a quick response. We will migrate in couple of months.
