### ISSUE TITLE
Validate Release notes against template

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#32508]
Currently, we validate that release notes parse properly, but we could go further:

Templates give you a flexible way of specifying which release notes you want included where, but because of the nature of filtering, not all release notes are included if they aren't all covered by a filter. We should add a `--validateAgainst` field to the release notes tooling to allow specifying a template to validate against. This would then return an error if any release notes are missed.

**Comment by shamsher31** [comment]
Also will be good to add validation for missing issue number. I faced this during the 1.9 release. See PR https://github.com/istio/istio/pull/30551

**Comment by brian-avery** [comment]
Challenge with a missing issue number is Istio doesn't require GitHub issues, even for user facing changes.

**Comment by ryantking** [comment]
Moving this to the 1.12 milestone due to recent inactivity
