### ISSUE TITLE
multi Root for workload mTLS for different users/tenants

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#32502]
Istio will sign all workloads’ (Pod’s) CSR via one root cert and private key.  It means certs for all workloads will be signed by the same root cert/private key.   

In some cases especially edge scenarios, there are multi users/tenants in a single mesh in the cluster.    Tenants require strong  security isolation: certs for different tenants’ workloads must be signed from different root cert. 

So we need make istio CA support this scenarios, to sign the workload cert from different tenant with different root cert.

**Comment by hzxuzhonghu** [comment]
Does it mean to provide hard isolation in one mesh? If so, why not use different service meshes to manage different tenants?

**Comment by irisdingbj** [comment]
> Does it mean to provide hard isolation in one mesh? If so, why not use different service meshes to manage different tenants?

The disadvantage for this is obvious comparing with multi mesh in a cluster:

Besides the multiple istio control plane overhead, Cluster admin need to take care of multiple istiod control planes as well.
The following upgrade and maintenance effort will be multiplexed.

**Comment by irisdingbj** [comment]
https://docs.google.com/document/d/1V97F5tyg_DA9RHR-Mc4o6XrRVhOGu1aW7y8juGUz970/edit#  @hzxuzhonghu

**Comment by zhaohuabing** [comment]
It seems to make sense at the edge.
