### ISSUE TITLE
PILOT_CERT_PROVIDER=custom makes istiod hang forever

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32509]
This was broken in 5f5cd773bbcedfb91ae1030211c08d49a9a7d67b. Basically it waits forever, with no logs, for the certificate to arrive, but it never does since we never set up a watch for it.

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/blob/b18a9b08f9fda5463c2bd33afa44130dfd222f58/pkg/security/security.go#L132-L137
