### ISSUE TITLE
can anybody give me an config example of destinationrule tls policy is simple or mutual

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32528]
**Describe the feature request**
can anybody give me an config example of destinationrule tls policy is simple or mutual
always error when I configed
**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
See https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings
