### ISSUE TITLE
Unable to access sample `Bookinfo` application through ingress

### ISSUE THREAD

**Issue by odiolog** [istio/istio#32531]
(related to )

**Bug description**

Unable to get the _Bookinfo sample application_ working in neither Kind nor k3d. 

After installing the _Bookinfo sample application_  I am still not able to reach it from outside (browser, curl, etc...). The port is listening but there is no answer. I first noticed the problem with k3d but since there is an internal ingress that could interfere with my test, so I decided to try with kind and I got the same result. 

After some investigations, I noticed the same symptoms as issue #22636.

```shell
% kubectl describe pdb -n istio-system istiod
Name:           istiod
Namespace:      istio-system
Min available:  1
Selector:       app=istiod,istio=pilot
Status:
    Allowed disruptions:  0
    Current:              1
    Desired:              1
    Total:                1
Events:
  Type    Reason  Age   From               Message
  ----    ------  ----  ----               -------
  Normal  NoPods  19m   controllermanager  No matching pods found
```

```shell
% kubectl get pods -l app=istiod,istio=pilot -n istio-system 
NAME                      READY   STATUS    RESTARTS   AGE
istiod-6d7d8f6558-s9zgf   1/1     Running   0          21m
```

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[ ] Multi Cluster
[ ] Virtual Machine
[] Multi Control Plane

**Expected behavior**

Able to reach inside the cluster after having configured ingress. 

**Steps to reproduce the bug**

Follow the steps to install the booking application on kind (note: this was the only running cluster): 

```shell
% kind create cluster
% istioctl install --set profile=demo -y
% kubectl label namespace default istio-injection=enabled
% kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.9/samples/bookinfo/platform/kube/bookinfo.yaml
% kubectl exec "$(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')" -c ratings -- curl -sS productpage:9080/productpage | grep -o "<title>.*</title>"
% kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.9/samples/bookinfo/networking/bookinfo-gateway.yaml
% export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
% export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}')
% export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
% echo "http://$GATEWAY_URL/productpage"
```

Connect to the resulting url. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```shell
% istioctl version --remote
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (8 proxies)

```

**How was Istio installed?**

Using:

```shell
% istioctl install --set profile=demo -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

macOS 10.15.7 (19H15)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.tgz.zip](https://github.com/istio/istio/files/6397434/bug-report.tgz.zip)

**Comment by sridharlreddy** [comment]
kind node ip (docker container) will not be reachable from the mac, so you cannot use that ip. Add portmappings in kind https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings or use lb solution like https://www.thehumblelab.com/kind-and-metallb-on-mac/ to connect.

To test the connectivity you can use kubectl port-forward
`kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80`
and `curl localhost:8080/productpage`

**Comment by sebastienh** [comment]
Thanks for the answer! I will test it out soon as I am back with Istio configuration. Since memory usage is quite high in Kind, it would be good to also have k3d  installation instructions.

**Comment by odiolog** [comment]
Thanks for the answer! I will test it out soon as I am back with Istio configuration. Since memory usage is quite high in Kind, it would be good to also have k3d installation instructions.
