### ISSUE TITLE
Release Notes Tooling Improvements

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#32536]
This issue is to track release notes tooling improvement issues.

**Comment by brian-avery** [comment]
#32508 
#28276 
#31851 
#29561

**Comment by brian-avery** [comment]
[Rebase issue](https://github.com/istio/istio/issues/31851) -- failure if a file is removed from master but not from a branch, Git finds it in the branch and tries to compare it against the original but can't find it.

**Comment by zhlsunshine** [comment]
Hi @brian-avery, shall we move this issue to 1.12?
