### ISSUE TITLE
e2e-pilot test failure in checking logs of mixer - part 2

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3254]
#3180 turned off the check but that's hiding a real issue 

see details in https://github.com/istio/istio/issues/3125

jun said he'll have a PR

we need to make sure we turn back on the test

**Comment by andraxylia** [comment]
This is about the crash in mixer, right? Can you set the PR's title properly?

**Comment by ldemailly** [comment]
it was about a check that used to work and doesn't work anymore  (and an incoming PR)

but you indicated offline/since that you think checking ids is not useful

**Comment by douglas-reid** [comment]
what is the status of this issue?  OBE?
