### ISSUE TITLE
istioctl install: consider removing dry run

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32556]
This doesn't seem like there is any strong use case for this, other than having us accidentally introduce bugs where it is not a dry run and actually applies resources?

WDYT @ostromart @richardwxn ?

Context:
https://github.com/istio/istio/issues/32554
https://github.com/istio/istio/issues/32555

**Comment by ostromart** [comment]
I've heard a number of users express a strong desire to have a dry run even more verbose than what we have right now. Specifically, they want to see exactly what Istio plans to change in the cluster before they execute it. 
@litong is working on https://github.com/istio/istio/issues/31185 to implement that. 
Is the concern more around the bugs? I completely agree dry-run should be rock solid so we need to fix these asap.
