### ISSUE TITLE
Use startupProbe, make readiness probe a lot longer period

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32569]
Today our readiness probe runs every 2s after the first second of the pod life. This has two concerns:
* Lots of calls, which makes logs spammy - especially in debug logs, and adds a small overhead
* if we miss the first probe at 1s, we will definitely take 3s+ to become ready

In newer k8s, we can use startup probe. I suggest:
```
startupProbe:
  interval: 1s
readdinessProbe:
  interval: 15s
```

With this, we will aggresively probe every second until we are ready the first time, then we will backoff to once every 15s.

To do this safely we need to only do it on k8s 1.21+ so we have https://github.com/kubernetes/kubernetes/commit/c193c1b2347c2f9bfbdd4f5c4dd7f41fcd91a204

cc @mandarjog

**Comment by mandarjog** [comment]
Using it makes sense for the initial start, we can speed it up even more if possible. About reducing the steady state to 15s means that unreadiness will not be reflected quickly. 

we should not emit logs infra related activities, but yes debug logs will emit everything and may be spammy.

**Comment by howardjohn** [comment]
We currently have failureThreshold=30, interval=2s so 60s to become unready.

We can make it failureThreshold=4, interval=15s, so its still 60s to become unready

**Comment by howardjohn** [comment]
Notstale

**Comment by howardjohn** [comment]
Still worth exploring

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
still valid

**Comment by howardjohn** [comment]
Another idea is to make the probe not return 503 immediately but wait until ready then give 200. That way we can give long period but show readiness the moment we are ready.

Downside is the requests before we bind to port fail and ruin it. Maybe if we can have short interval but huge timeout, but I think timeout must be smaller
