### ISSUE TITLE
/debug/resourcesz shows skipped CRDs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32567]
Istiod logs (correctly) show `Skipping CRD networking.istio.io/v1alpha3/DestinationRule as it is not present`

But `localhost:8080/debug/resourcesz` still shows them. It is supposed to ignore the ones we skip.

Alternatively we could just make CRD watching and then this problem goes away..

**Comment by zhlsunshine** [comment]
Hi @howardjohn, I find another issue relate to this. I get a CRD resource list which is GVK based When I call API `resourcesz` . And this CRD list is different from another list which is retrieved via `kubectl get crds`. So I think the resource schema need to sync with the real CRD list, then this issue should be fixed at the same time.

**Comment by zhlsunshine** [comment]
> `resourcesz` is not intended to be equal to list of real CRDs in cluster, its supposed to be the ones that Istio is handling. This may be disjoint from the set of CRDs in the cluster.

I want to deep dive more, I understand that:
For CRDs in the cluster,  it means that there is a list of CRDs which display all CRDs registered when install Isito
For `resourcesz`, it means that there are some instances of such kind of CRD in the cluster
Should this be the difference between them? @howardjohn

**Comment by zhlsunshine** [comment]
@howardjohn And if `localhost:8080/debug/resourcesz` need to ignore the ones `Istiod logs` skip, then it means that `resourcesz` CRD list should be the same as `kubectl get crds` list in CRD types. The source code file dir is: `pilot/pkg/config/kube/crdclient/client.go` on funciton `knownCRDs`

**Comment by zhlsunshine** [comment]
Okay, got it. non-business with `kubectl get crds`.
