### ISSUE TITLE
Mismatch of supported regex

### ISSUE THREAD

**Issue by lonnix** [istio/istio#32598]
**Bug description**
The docs at https://istio.io/latest/docs/reference/config/networking/virtual-service/ (and possibly other pages) say that regex follows ECMAscript syntax. However, when I put invalid regex in a VirtualService .spec.http.match.uri.regex value I got this error 
```
 Error: UPGRADE FAILED: failed to create resource: admission webhook "validation.istio.io" denied the request: configuration is invalid: "uri": error parsing regexp: missing argument to repetition operator: `*`; Istio uses RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax)
```
"RE2" and "ECMAscript" are not entirely the same and its unclear which one is actually supported. 

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect that the docs and error messages align

**Steps to reproduce the bug**
Put invalid regex syntax at .spec.http.match.uri.regex in a VirtualService and apply. It should fail and produce the above error message

**Version** 
Istio 1.8.0

**How was Istio installed?**
via Helm

**Comment by shamsher31** [comment]
> "RE2" and "ECMAscript" are not entirely the same and its unclear which one is actually supported.

`RE2` is supported and not the `ECMAscript`. See https://github.com/istio/api/pull/1327
