### ISSUE TITLE
Jaeger task not having expected results

### ISSUE THREAD

**Issue by esnible** [istio/istio#32596]
Related: #32132 and #32026 and https://github.com/istio/istio.io/issues/9668

I attempted to follow the instructions to Install Jaeger.  I modified them slightly.  I did

```bash
istioctl-1.10.0-rc.0 install \
  --set meshConfig.accessLogFile="/dev/stdout" \
  --set meshConfig.defaultConfig.tracing.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:9411 \
  --set meshConfig.defaultConfig.tracing.sampling=100 \
   && say installed || say failed
```

I followed all of the other steps including `for i in $(seq 1 100); do curl -s -o /dev/null "http://$GATEWAY_URL/productpage"; done`

In the Jaeger dashboard, I see two services: `istio-ingressgateway` and `jaeger-query`.  I do not see the `productpage.default` promised by https://preliminary.istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/

Traffic is working ... bookinfo works for me.  I see traces from istio-ingressgateway to productpage.default.svc.cluster.local:9080/productpage.  I don't see calls to details, ratings, or reviews.

I see only 3 traces.  I expected because I set `sampling=100` that I would see the query default, 20, traces.

**Comment by bianpengyuan** [comment]
Was bookinfo injected with sidecar?

**Comment by esnible** [comment]
Especially see https://github.com/istio/istio.io/issues/9669

Yes, pods have sidecars.

```
$ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-79f774bdb9-mv8x9       2/2     Running   0          50m
httpbin-95db65f-6rtx5             2/2     Running   0          48m
productpage-v1-6b746f74dc-xckdk   2/2     Running   0          50m
ratings-v1-b6994bb9-bw8hm         2/2     Running   0          50m
reviews-v1-545db77b95-58mmd       2/2     Running   0          50m
reviews-v2-7bf8c9648f-z9vlh       2/2     Running   0          50m
reviews-v3-84779c7bbc-jhd74       2/2     Running   0          50m
```

**Comment by bianpengyuan** [comment]
And bookinfo proxy is using 1.10.0-rc.0?

**Comment by esnible** [comment]
```bash
$ kubectl get pod productpage-v1-6b746f74dc-xckdk -o jsonpath="{.spec.containers[1].image}"

docker.io/istio/proxyv2:1.10.0-rc.0
```

**Comment by bianpengyuan** [comment]
Works fine for me with 1.10.0-rc.0. 

Looks like you configured jaeger collector service with wrong port. Should be `14268`.

**Comment by esnible** [comment]
Still not working for me.

I had no problem redeploying with 14268 and restarting pods.

There are two things I am confused about.  The first thing I want to point out is that the ingressgateway has no trouble sending traces.  It's configuration Envoy bootstrap has nothing about tracing.  It's 0.0.0.0_8080 listener, filter chain has
```json
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 1
             },
             "overall_sampling": {
              "value": 100
             },
```

The productpage-v1 sidecar, whose distributed traces are not being caught by Jaeger, has an Envoy bootstrap with
```json
       "tracing": {
        "zipkin": {
         "address": "jaeger-collector.istio-system.svc.cluster.local:14268"
        },
        "sampling": 100
       },
```

It also has a listener with

```json
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 100
             },
             "overall_sampling": {
              "value": 100
             },
```

... but this listener moves around.  I have seen it on listener "0.0.0.0_15014" and on listener "0.0.0.0_8081".  I would expect it to be listening on all of the HTTP ports, or all of the bookinfo ports, not on just a single port...

**Comment by bianpengyuan** [comment]
Then what is the tracer address used by ingress? Have you restarte istio-ingressgateway pod to get new trace sampling rate?

I don't quite understand what do you mean by `listener moves around`.

**Comment by esnible** [comment]
Adding `networking` because Istio 1.9.2 generates Envoy config with

```json
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 100
             },
             "overall_sampling": {
              "value": 100
             },
```
on every HTTP port, but 1.10.0-rc.0 only generates that for a single random port.

**Comment by esnible** [comment]
@bianpengyuan I had thought `istioctl install` was restarting the ingressgateways when the meshconfig changes, but it isn't.  So I can't trust my experiments.

I am not restarting both Istiod and the ingressgateway after each change of meshconfig.  Now I am not getting any traces to appear in Jaeger, from the ingressgateway or my working pods.

What do you see when you do `kubectl -n istio-system exec deployment/istio-ingressgateway -- curl localhost:15000/config_dump | jq ".configs[0].bootstrap.node.metadata.PROXY_CONFIG.tracing"`?

What other settings should I look at?

I am installing Jaeger 1.20 using `kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/jaeger.yaml` as recommended by the Istio docs.

**Comment by bianpengyuan** [comment]
Could you remove the trace address, just use the default zipkin tracing service address and try again?

I did not use jaeger collector directly and I am not familiar with it at all. I am not sure if trace span emitted by Envoy is compatible with the format expected by the jaeger collector)

**Comment by esnible** [comment]
I will close this because the Jaeger task does work if Jaeger is installed correctly.

For an explanation as to why my config was wrong, see https://github.com/istio/istio.io/issues/9668#issuecomment-831613196

I am leaving open the doc issues to improve the doc and the automated test.

**Comment by tampler** [comment]
Still not working in #32044
