### ISSUE TITLE
[Ingress] Support for Mutual TLS with external clients

### ISSUE THREAD

**Issue by schmitzhermes** [istio/istio#326]
It would be great to support mutual TLS with Ingress clients. 
A working example can be found in nginx ingress controller: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#certificate-authentication

This should not be confused with mutual TLS _inside_ your cluster (i.e. service-to-service communication) -> that's what https://github.com/istio/auth is for.

**Comment by rshriram** [comment]
Hi,
 Can you please post this issue on istio/issues repo? We are keeping track of all bugs and feature requests in that repo. The issues here are for our internal tracking purposes.

**Comment by ldemailly** [comment]
Issue moved to [istio/issues #50](https://github.com/istio/issues/issues/50) via [**ZenHub**](https://www.zenhub.com/)
