### ISSUE TITLE
analyzer for changes in meshConfig.defaultConfig

### ISSUE THREAD

**Issue by esnible** [istio/istio#32602]
Feature request:

If I install Istio with `--set meshConfig.defaultConfig.tracing.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:9411`, deploy pods, then re-install Istio with `--set meshConfig.defaultConfig.tracing.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:14268`, the sidecars will have stale data.

They should be restarted, but the only value analysis currently checks for is the image name of the sidecar.

**Comment by zhlsunshine** [comment]
Here are the reproduce steps below:
1. Install istio by `istioctl install --set profile=demo -y --set meshConfig.defaultConfig.tracing.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:9411`
2. Deploy bookinfo by `kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`
3. Check pod's sidecar data by `kubectl describe pods productpage-v1-xxxxxx` in environment `PROXY_CONFIG`  of container `istio-proxy`
4. Re-install istio by `istioctl install --set profile=demo -y --set meshConfig.defaultConfig.tracing.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:14268` 
5. redo the step 3 and verify that this pod is not restarted

So @esnible, do you think all existing pods should be restarted or just some pods can be triggered by istioctl command, such as in namespace level? Any idea?

**Comment by zhlsunshine** [comment]
@esnible I think the solution is not to restart all existing pods, but just create a analyzer for this? Am I correct? If yes,  I think this analyzer should be only for between meshConfig and pod? Is this assumption right?

**Comment by zhlsunshine** [comment]
@esnible if all above is correct, then do you think it's good idea to start from [here](https://github.com/istio/istio/blob/70e42c66694e1d264c304d94f3ca0ed535d80877/pkg/config/validation/validation.go#L1472)? Thanks for your time!
