### ISSUE TITLE
TestAuthorization_JWT test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32622]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1389142380707319808

**Comment by yangminzhu** [comment]
It looks like the test is no longer flaky: https://k8s-testgrid.appspot.com/istio_istio_postsubmit#integ-security-multicluster-tests_istio_postsubmit&include-filter-by-regex=TestAuthorization_JWT&width=20, closing the issue now, feel free to reopen if it still fails.
