### ISSUE TITLE
TestPassthroughFilterChain test failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32623]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1389590835284152320

cc @JimmyCYJ

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1392152356514172928

**Comment by yangminzhu** [comment]
It looks like the test is no longer flaky: https://k8s-testgrid.appspot.com/istio_istio_postsubmit#integ-security-multicluster-tests_istio_postsubmit&include-filter-by-regex=TestPassThroughFilterChain&width=20, closing for now, feel free to reopen if it still fails.
