### ISSUE TITLE
add support for local origin errors in outlier detection

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#32645]
Envoy supports splitting of local origin/remote errors while deciding a host to be outlier.  https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#config-cluster-v3-outlierdetection.

This is useful in certain cases where we want to just rely on local failures to remove from load balancer pool.

The feature request is to add to Destination rule API.
     split_external_local_origin_errors
     consecutive_local_origin_failure
     enforcing_consecutive_local_origin_failure

**Comment by ramaraochavali** [comment]
@nrjpoddar @howardjohn @hzxuzhonghu what do you think??

**Comment by ramaraochavali** [comment]
I looked at possible options of doing this via Envoy filter. But it is. becoming challenging to add to every client namespace especially when the services that need this behaviour are growing.  

I think this would be useful API -  https://github.com/istio/api/pull/1989

**Comment by hzxuzhonghu** [comment]
>This is useful in certain cases where we want to just rely on local failures to remove from load balancer pool.


Not sure i understand the case here, i think both side failures should be relied on by load balancer.

**Comment by ramaraochavali** [comment]
> Not sure i understand the case here, i think both side failures should be relied on by load balancer.

This happens when server some times returns 5xx explicitly for few requests based on request but is generally up and processing requests. We do not want to eject that server because of that. We want to eject only if it is unreachable. This is to address the case explained here https://github.com/envoyproxy/envoy/issues/3643#issue-332919412

**Comment by nrjpoddar** [comment]
Seems reasonable to add though I wouldn't want to mimic Envoy APIs blindly.
