### ISSUE TITLE
HTTP request hangs intermittently

### ISSUE THREAD

**Issue by ediezh** [istio/istio#32668]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
POD A and POD B both with sidecar enabled, HTTP call from POD A -> POD B to download files > 100 MB. Normally the request takes less than 1s to finish. But occasionally it takes over 1 hour. Inspecting the istio debug logs I found there is a 1h gap in the log messages for the same request. 

<img width="990" alt="Screen Shot 2021-05-06 at 12 23 59 pm" src="https://user-images.githubusercontent.com/15918714/117241255-15cc0c00-ae76-11eb-94fb-92bb38561bd1.png">

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Request finishes within reasonable time.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.6

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS 1.17

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by sumitaneja** [comment]
Observe same issue with
bash-4.2$ istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (674 proxies)
bash-4.2$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.18.10
bash-4.2$ helm version --short
v3.2.1+gfe51cd1
bash-4.2$

**Comment by sumitaneja** [comment]
@ediezh were you able to triage this out
