### ISSUE TITLE
Automatic side-car injection failed 

### ISSUE THREAD

**Issue by jnitin** [istio/istio#32667]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Automatic side car injection failed and pod not started after enabling automatic side car injection. 

[ ] Docs
[ ] Installation  X
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[ ] Multi Cluster 
[ ] Virtual Machine X
[ ] Multi Control Plane

**Expected behavior**
After istiod is running successfully and automatic side car injection is enabled , then if any pod is deleted then side car should be injected automatically 

**Steps to reproduce the bug**

1. Download  pilot:19.4 version  and pushed the image to docker local repo ( mylocalrepo)
2. istioctl install --set hub=mylocalrepo:5000/istio
3. istiod was installed suceessufully and is in running state . 
4. delete one pod in default where auto side car injection is enabled 
5. POD does not started and deployment is not in ready state 
Below errors in kubectl get events

`Error creating: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:1: function "Template_Version_And_Istio_Version_Mismatched_Check_Installation" not defined`

In kubeapi server logs below error is observed 

`W0505 02:05:30.750732 1 dispatcher.go:142] rejected by webhook "validation.istio.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"validation.istio.io\" denied the request: configuration is invalid: gateway must have at least one server", Reason:"", Details:(*v1.StatusDetails)(nil), Code:400}}`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.4
control plane version: 954110286bab41a32e09d480b356d5c4fa9d6d25-dirty-954110286bab41a32e09d480b356d5c4fa9d6d25
data plane version: none
```

```
kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

**How was Istio installed?**
Istio was installed using istioctl  and docker image was pulled from docker and pushed to mylocalrepo since installation where istio needs to be installed does not have internet access . 

Online machine 
```
docker pull docker.io/istio/pilot:1.9.4
docker save docker.io/istio/pilot:1.9.4 > pilot:1.9.4.tar
docker tag istio/pilot:1.9.4 mylocalrepo:5000/istio/pilot:1.9.4 
docker push mylocalrepo:5000/istio/pilot:1.9.4
```

Offline machine 
`istioctl install --set hub=mylocalrepo:5000/istio`

**Environment where the bug was observed (cloud vendor, OS, etc)**

CentOS v7.8  system . Kubernetes cluster ( 1 master and 2 worker nodes ) was created using kubeadm and working fine without istio service mesh. 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
This is because the sidecar template configmap version does not match the control plane version.
