### ISSUE TITLE
Doc : performance-and-scalability

### ISSUE THREAD

**Issue by nehaseth** [istio/istio#32678]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
In performance documentation : https://istio.io/latest/docs/ops/deployment/performance-and-scalability/
some minor points which may be updated to bring more clarity

- In **Summary** section there is line : `The Envoy proxy adds 2.65 ms to the 90th percentile latency. `
   but also on the same page under section **Latency for Istio 1.9.4** we see :  `Inside the mesh, a request traverses the client-side proxy and then the server-side proxy. In the default configuration of Istio 1.9.4 (i.e. Istio with telemetry v2), the two proxies add about 2.65 ms and 2.91 ms to the 90th and 99th percentile latency`  which indicates the additional latency is because of 2 proxies and not per proxy level.

- Additionally, lines referring an older version may be removed to avoid confusion from this page : `As of Istio 1.7, a proxy consumes about 0.5 vCPU per 1000 requests per second.` whereas in **Summary**, it says : `The Envoy proxy uses 0.35 vCPU and 40 MB memory per 1000 requests per second going through the proxy`

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
NA

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
NA

**How was Istio installed?**
NA

**Environment where the bug was observed (cloud vendor, OS, etc)**
NA
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @mandarjog do we have a new owner for this page?
