### ISSUE TITLE
Documentation for Prometheus scraping with Istio mTLS STRICT is incorrect

### ISSUE THREAD

**Issue by linxcat** [istio/istio#32680]
**Bug description**
When following the directions at https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings it is impossible to see success because for some reason the string "istio-certs" for the volume will not work. The volume and mount will both be created and exist in the statefulset but as indicated in this [bug](https://github.com/istio/istio/issues/29919) the pod creation will fail with the volume mount indicating the volume cannot be found. The root cause is this specific [issue](https://github.com/istio/istio/issues/29919#issuecomment-778411275), in which the name of the volume is not acepted for no understood reason.

changing the volume name and mount reference slightly resolves the issue.

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
If any name for the volume could be possible, that would be preferable, but in lieu of that, the documentation should describe steps that actually function correctly

**Steps to reproduce the bug**
Follow the documentation on a cluster containing both Prometheus and istio with mTLS enabled (in my case both installed with helm on K8S 1.18)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Helm 3.5.3
Istio 1.8.4

**How was Istio installed?**
With Helm in Terraform

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS running K8S 1.18

**Comment by howardjohn** [comment]
cc @bianpengyuan

**Comment by bianpengyuan** [comment]
If you check the rendered prom deployment manifest, is volume name the only difference? Could you paste your prom deployment spec here with `istio-certs`? It works for me by editing the prom deployment directly, it is hard for me to think of a reason why volume name matters.

**Comment by linxcat** [comment]
Yes. I find it to be incredibly stupid as well, but that is literally the only change I made between helm deployments.

```
@@ -312,11 +312,15 @@ alertmanager:
     ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
-    scheme: ""
+    scheme: "https"

     ## tlsConfig: TLS configuration to use when scraping the endpoint. For example if using istio mTLS.
     ## Of type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig
-    tlsConfig: {}
+    tlsConfig:
+      caFile: /etc/prom-certs/root-cert.pem
+      certFile: /etc/prom-certs/cert-chain.pem
+      keyFile: /etc/prom-certs/key.pem
+      insecureSkipVerify: true

@@ -1097,7 +1101,13 @@ prometheus:

   ## Annotations for Prometheus
   ##
-  annotations: {}
+  annotations:
+    traffic.sidecar.istio.io/includeInboundPorts: ""
+    traffic.sidecar.istio.io/includeOutboundIPRanges: ""
+    proxy.istio.io/config: |
+      proxyMetadata:
+        OUTPUT_CERTS: /etc/istio-output-certs
+    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'

   ## Service account for Prometheuses to use.
   ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
@@ -1661,10 +1671,15 @@ prometheus:
+      - name: istio-certs
+        emptyDir:
+          medium: Memory

     # Additional VolumeMounts on the output StatefulSet definition.
-    volumeMounts: []
+    volumeMounts:
+      - name: istio-certs
+        mountPath: /etc/prom-certs/
```

The above git diff caused failure. The Below git diff caused success:
```
@@ -312,11 +312,15 @@ alertmanager:
     ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
-    scheme: ""
+    scheme: "https"

     ## tlsConfig: TLS configuration to use when scraping the endpoint. For example if using istio mTLS.
     ## Of type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig
-    tlsConfig: {}
+    tlsConfig:
+      caFile: /etc/prom-certs/root-cert.pem
+      certFile: /etc/prom-certs/cert-chain.pem
+      keyFile: /etc/prom-certs/key.pem
+      insecureSkipVerify: true

@@ -1097,7 +1101,13 @@ prometheus:

   ## Annotations for Prometheus
   ##
-  annotations: {}
+  annotations:
+    traffic.sidecar.istio.io/includeInboundPorts: ""
+    traffic.sidecar.istio.io/includeOutboundIPRanges: ""
+    proxy.istio.io/config: |
+      proxyMetadata:
+        OUTPUT_CERTS: /etc/istio-output-certs
+    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs-dir", "mountPath": "/etc/istio-output-certs"}]'

   ## Service account for Prometheuses to use.
   ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
@@ -1661,10 +1671,15 @@ prometheus:
+      - name: istio-certs-dir
+        emptyDir:
+          medium: Memory

     # Additional VolumeMounts on the output StatefulSet definition.
-    volumeMounts: []
+    volumeMounts:
+      - name: istio-certs-dir
+        mountPath: /etc/prom-certs/
```

**Comment by linxcat** [comment]
> If you check the rendered prom deployment manifest, is volume name the only difference? Could you paste your prom deployment spec here with `istio-certs`? It works for me by editing the prom deployment directly, it is hard for me to think of a reason why volume name matters.

To be clear, there is no deployment at all involved with deploying the Prometheus server from prometheus operator. It is a StatefulSet alone.

**Comment by linxcat** [comment]
Here is the bottom of the describe for the StatefulSet proving there's no typo:
```
   istio-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
Volume Claims:  <none>
Events:
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  4m46s (x97 over 21h)  statefulset-controller  create Pod prometheus-cluster-monitoring-kube-pr-prometheus-0 in StatefulSet prometheus-cluster-monitoring-kube-pr-prometheus failed error: Pod "prometheus-cluster-monitoring-kube-pr-prometheus-0" is invalid: spec.containers[0].volumeMounts[3].name: Not found: "istio-certs"
```

**Comment by linxcat** [comment]
And now here is is immediately after, working fine:
```
   istio-certs-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
Volume Claims:  <none>
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Warning  FailedCreate      10m (x97 over 21h)  statefulset-controller  create Pod prometheus-cluster-monitoring-kube-pr-prometheus-0 in StatefulSet prometheus-cluster-monitoring-kube-pr-prometheus failed error: Pod "prometheus-cluster-monitoring-kube-pr-prometheus-0" is invalid: spec.containers[0].volumeMounts[3].name: Not found: "istio-certs"
  Normal   SuccessfulCreate  3m32s               statefulset-controller  create Pod prometheus-cluster-monitoring-kube-pr-prometheus-0 in StatefulSet prometheus-cluster-monitoring-kube-pr-prometheus successful
```
