### ISSUE TITLE
Istioctl falls back to internet when doing an upgrade

### ISSUE THREAD

**Issue by brendarearden** [istio/istio#32689]
**Bug description**
Istioctl does not use locally available manifests when performing an upgrade

The logic that is causing this problem is located here (see linked code). It appears that if there is a current version of istio installed (which is always true on upgrade), then it sets the installPackagePath to a github url. There is not a way to override this behavior as all the flags or passed in values apply to the updated istio, not the "current" version. This is a problem, especially when attempting an upgrade in an airgapped environment. 

https://github.com/istio/istio/blob/b9c81e74328c18a50924154ed33efb3ccb02fffa/operator/cmd/mesh/upgrade.go#L170
https://github.com/istio/istio/blob/b9c81e74328c18a50924154ed33efb3ccb02fffa/operator/cmd/mesh/upgrade.go#L202
https://github.com/istio/istio/blob/b9c81e74328c18a50924154ed33efb3ccb02fffa/operator/cmd/mesh/upgrade.go#L63

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Potential Work Around(s)**
(1). utilize the `canary upgrade` process instead of the `in-place upgrade` as canary upgrades only utilize the `istioctl install` command and never the `istioctl upgrade`. This could add unnecessary complexity, but it is an option. 

(2). Use an nginx server to redirect the traffic call to github.com to local 127.0.0.1 

**Expected behavior**
Istioctl should use the manifests that are available locally to perform the upgrade, should return an error of where the expected manifests should be available to the installer or should allow a user to pass in manifests when running the command similar to what you can do on install and then only then reach out to download from an external source that is configurable (but has a default value). 

**Steps to reproduce the bug**
Run `istioctl upgrade --manifests /path/to/manifests --set profile=demo`

**Version** 
This issue has been confirmed in 1.7.2 - up to the current release 1.9.4

**How was Istio installed?**
`curl -L https://istio.io/downloadIstio | sh -`

**Additional Notes** 
https://github.com/istio/istio/issues/28995 was opened and https://github.com/istio/istio/pull/30651 - both have closed due to inactivity but this is still an issue.

**Comment by brianplexxi** [comment]
if I changed my installation to use helm and used helm upgrade - is this still an issue for this scenario ?

**Comment by trieszecg** [comment]
hi @brianplexxi , yes it is. Please note that this is typically causing issue in airgapped environments.

**Comment by brendarearden** [comment]
Just chiming in to say this is still an issue! 

I am curious as to why we have to have the current version and then install the new version for upgrade. Is the new version not able to generate the config for the currently installed version? If the flag could just be like "dont get upstream istio binary, use the one we have right in the existing installation path"

**Comment by brianplexxi** [comment]
If it is of any help as a workaround I upgraded from a previous installed istio version (1.7) that used istioctl to istion 1.9 by upgrading/migrating using helm. Thereafter helm to helm upgrades of istio do not seem to have this issue

**Comment by papanito** [comment]
Any plans to fix this soon? For us this is a huge problem as we are using Rancher (see https://github.com/rancher/rancher/issues/30842) in an air-gapped environment

**Comment by papanito** [comment]
Can we reopen the issue?

**Comment by Nino-K** [comment]
I'm going to reopen this issue since it is still a real problem. @morvencao made this [PR](https://github.com/istio/istio/pull/30651) which could potentially allow the user to specify local chart, however, it was closed without merging. We also have https://github.com/istio/istio/issues/28995 which addresses the same issue and is closed.

**Comment by papanito** [comment]
This is still valid

**Comment by papanito** [comment]
Can you re-open it!? This is still a valid issue

**Comment by zirain** [comment]
not stale

**Comment by vardhaman22** [comment]
as per https://github.com/istio/istio/issues/28995#issuecomment-1327121142 this issue is also fixed (PR: https://github.com/istio/istio/pull/36168 corresponding to issue: https://github.com/istio/istio/issues/35951).
