### ISSUE TITLE
helm chart istio ingress needs attention

### ISSUE THREAD

**Issue by linsun** [istio/istio#3269]
I noticed a few issues with istio ingress while testing helm chart today:

1. we are calling it istio-istio in pod, deployment, service account, cluster role and cluster role binding.  we did call it istio-ingress in service name.  This is confusing, I'd rather they are called istio-ingress* to be consistent with the non helm install.

2. we need to allow users to configure istio ingress to be enabled or disabled.  

cc @sdake @luisyonaldo if you have bandwidth to help.

```
LAST DEPLOYED: Wed Feb  7 10:37:05 2018
NAMESPACE: istio-system
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                          READY  STATUS   RESTARTS  AGE
istio-mixer-3354504390-4w54p  3/3    Running  0         19s
istio-pilot-262150295-tj6s0   1/2    Running  0         19s
istio-istio-3312840516-6rx4v  1/1    Running  0         19s

==> v1/ConfigMap
NAME                          DATA  AGE
istio-mixer-custom-resources  1     19s
istio-mixer                   1     19s
istio                         1     19s

==> v1/ServiceAccount
NAME         SECRETS  AGE
istio-mixer  1        19s
istio-pilot  1        19s
istio-istio  1        19s

==> v1beta1/CustomResourceDefinition
NAME                                 AGE
kubernetesenvs.config.istio.io       19s
quotas.config.istio.io               19s
metrics.config.istio.io              19s
rules.config.istio.io                19s
attributemanifests.config.istio.io   19s
listcheckers.config.istio.io         19s
logentries.config.istio.io           19s
noops.config.istio.io                19s
memquotas.config.istio.io            19s
prometheuses.config.istio.io         19s
statsds.config.istio.io              19s
svcctrls.config.istio.io             19s
reportnothings.config.istio.io       19s
stdios.config.istio.io               19s
stackdrivers.config.istio.io         19s
listentries.config.istio.io          19s
deniers.config.istio.io              19s
kuberneteses.config.istio.io         19s
checknothings.config.istio.io        19s
routerules.config.istio.io           19s
egressrules.config.istio.io          19s
destinationpolicies.config.istio.io  19s

==> v1beta1/ClusterRole
istio-mixer  19s
istio-pilot  19s
istio-istio  19s

==> v1beta1/ClusterRoleBinding
NAME         AGE
istio-mixer  19s
istio-pilot  19s
istio-istio  19s

==> v1/Service
NAME           TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)                                                           AGE
istio-mixer    ClusterIP     172.21.105.164  <none>       9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP  19s
istio-pilot    ClusterIP     172.21.215.124  <none>       15003/TCP,443/TCP                                                 19s
istio-ingress  LoadBalancer  172.21.210.42   <pending>    80:31045/TCP,443:32046/TCP                                        19s

==> v1beta1/Deployment
NAME         DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
istio-mixer  1        1        1           1          19s
istio-pilot  1        1        1           0          19s
istio-istio  1        1        1           1          19s

```

**Comment by sdake** [comment]
@linsun I'll take a look.

**Comment by luisyonaldo** [comment]
yes it's confusing, and is because that definition is inside `istio` forlder and not inside `ingress` subchart (name right now is `.Realease.Name-.Chart.Name`).

Also, what do you guys think of moving subcharts to actual chart and have the istio chart as main chart which call other charts as requirements?.
helm folder:
- istio (main char which call all other charts)
- mixer
- pilot
- security
- sidecar-injecotr
- addons
   - zipkin
    - ... other addons

Maybe after chart is more stable we can do it.

**Comment by luisyonaldo** [comment]
and again, if there is not reason to have multiple istio helm releases, then naming can be static, maybe is easier to match current manifest, later on if needed it could be dynamic

**Comment by sdake** [comment]
I've gone ahead and moved ingress into its own chart dir for the moment so we don't have to do a bunch of rework 
 on the structure of the charts until the high priority issues are resolved (in no particular order):
* descaling values.yaml
* gating
* updateVersion.sh removal
* istioctl sanitization with master helm chart

I'll submit a PR after I've done a bit of testing and modified updateVersions.sh appropriately - although the initial bringup seems to work.   Should hit queue today.

**Comment by linsun** [comment]
Thank you @sdake @luisyonaldo I agree ingress should be its own chart dir.

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/3275

**Comment by sdake** [comment]
this has been merged.
