### ISSUE TITLE
expose envoy hot restart in pilot-agent

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#32696]
**Describe the feature request**
we are using custom lua code to generate a RSA signature in envoy filter. the private key is distributed via secure mount to a VM, but because the envoy lua filter doesn't posses asynchronous capability, we need to be able to reload the filter when the file containing private key changes.
it seems the envoy's hot restart capability is the easiest way to achieve this currently, without a downtime (systemd path watcher can be then setup to trigger this)

this feature already exists in envoy, and was even used by pilot agent prior sds implementation change, so it shouldn't be a large effort to expose it to custom use by the agent

**Describe alternatives you've considered**
* cold restart, which doesn't work well, since the mount changes on all participating VMs in the same time, causing a service downtime
* manual rolling restart on secret change (not user friendly)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by kyessenov** [comment]
/sub
cc @mandarjog
