### ISSUE TITLE
"Istio is being downgraded" message during the upgrade to 1.9

### ISSUE THREAD

**Issue by jdomag** [istio/istio#32749]
**Bug description**
I try to install Istio 1.9.3 (same for 1.9.4) from 1.8.5 and I get ugly message:
`Istio is being downgraded from 1.8.5 -> 1.9.3.This will install the Istio 1.9.3 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N)` 

That's misleading, I'm trying to upgrade to higher version, not downgrade.  

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Message should specify that it's upgrade procedure not downgrade. 

**Steps to reproduce the bug**

`istioctl install --set profile=default --set revision=v194`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.9.3
control plane version: 1.8.5
data plane version: 1.8.5
```
**How was Istio installed?**
istioctl 
**Environment where the bug was observed (cloud vendor, OS, etc)**
Fedora34
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @shamsher31

**Comment by jdomag** [comment]
@tylern91 
Thanks for fixing that. If I understand it correctly it was just about a message, so it should be safe to go ahead and do the upgrade from 1.8 -> 1.9.4 (and ignore downgrade message)?

**Comment by shamsher31** [comment]
> Thanks for fixing that. If I understand it correctly it was just about a message, so it should be safe to go ahead and do the upgrade from 1.8 -> 1.9.4 (and ignore downgrade message)?

@jdomag Yes, it's just a message so safe to upgrade.

Closed by https://github.com/istio/istio/pull/32876
