### ISSUE TITLE
Istio Service Dashboard: Reporter=Source+Destination results in no data

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32762]
The dashboard allows selecting source+destination:
![2021-10-05_14-45-23](https://user-images.githubusercontent.com/623453/117728481-60af9180-b19e-11eb-90b5-7ce6abe3255c.png)

But when you do this no data shows up. Data does show up for selecting one or the other, just not both

**Comment by howardjohn** [comment]
We end up with `reporter="(destination|source)",`, but its not a regex so it fails

**Comment by douglas-reid** [comment]
Is this a new Grafana handling for drop-down options by any chance?
