### ISSUE TITLE
ingressgateway stuck.  Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32776]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
ingressgateway stuck.  Readiness probe failed: HTTP probe failed with statuscode: 503
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
  Normal   Scheduled  57s                default-scheduler  Successfully assigned istio-system/istio-ingressgateway-7cdccb7b58-k69wt to 192.168.198.154
  Normal   Pulled     53s                kubelet            Container image "docker.io/istio/proxyv2:1.9.4" already present on machine
  Normal   Created    53s                kubelet            Created container istio-proxy
  Normal   Started    53s                kubelet            Started container istio-proxy
  Warning  Unhealthy  48s (x2 over 50s)  kubelet            Readiness probe failed: Get "http://172.20.0.144:15021/healthz/ready": dial tcp 172.20.0.144:15021: connect: connection refused
  Warning  Unhealthy  8s (x20 over 46s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503

```
[root@master01 ~]# istioctl ps
NAME                                                    CDS        LDS                            EDS        RDS          ISTIOD                      VERSION
busybox.istio                                           SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
csrf-68bd9f9574-7tkxc.istio                             SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
details-v1-79f774bdb9-wrhcw.istio                       SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
http2-6b85d7bfdc-gd5b7.istio                            SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
istio-eastwestgateway-7fc4f97b45-wgm26.istio-system     SYNCED     SYNCED                         SYNCED     NOT SENT     istiod-7fbdd57c4f-7vk9p     1.9.4
istio-egressgateway-6bddfd6fd9-f68rt.istio-system       SYNCED     SYNCED                         SYNCED     NOT SENT     istiod-7fbdd57c4f-7vk9p     1.9.4
istio-ingressgateway-7cdccb7b58-k69wt.istio-system      SYNCED     STALE (Never Acknowledged)     SYNCED     NOT SENT     istiod-7fbdd57c4f-7vk9p     1.9.4
productpage-v1-6b746f74dc-gvkpz.istio                   SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
ratings-v1-b6994bb9-fvnbs.istio                         SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
reviews-v1-545db77b95-2nxk8.istio                       SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
reviews-v2-7bf8c9648f-g9sgk.istio                       SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
reviews-v3-84779c7bbc-qlzz9.istio                       SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
sleep-557747455f-dvzhl.istio                            SYNCED     SYNCED                         SYNCED     SYNCED       istiod-7fbdd57c4f-7vk9p     1.9.4
```

2021-05-11T08:34:11.018028Z     warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2021-05-11T08:34:13.017992Z     warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2021-05-11T08:34:15.018523Z     warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2021-05-11T08:34:17.018443Z     warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
[root@master01 ~]# 

[root@master01 ~]# kubectl get pod -n istio-system -w
NAME                                     READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-7fc4f97b45-wgm26   1/1     Running   3          2d2h
istio-egressgateway-6bddfd6fd9-f68rt     1/1     Running   3          2d2h
istio-ingressgateway-7cdccb7b58-k69wt    0/1     Running   0          3m20s
istiod-7fbdd57c4f-7vk9p                  1/1     Running   0          3m30s

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
^C[root@master01 ~]# istioctl version --remote
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (13 proxies)
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by mabushey** [comment]
As the logs are showing errors with Pilot which is no longer a part of Istio, I'm going to deduce this cluster is corrupt from trying to do upgrades. Blow away the istio-system namepsace and do a `istioctrl operator init`. Trying to do minor version upgrades just results in a dead cluster. Istio is awesome, but it's not upgradable between minor versions w/o seeing these type of failures.
