### ISSUE TITLE
istio istio-init run first before custom init container

### ISSUE THREAD

**Issue by chenglanguo** [istio/istio#32775]
I'm new to istio, Current i have an application need run database migration before it start, so i made a initContainer to do that, but when i enable the istio inject, it keep status init like this
```
devops-6cb75898c7-9p5tn      0/2     Init:0/2   0          33m
devops-db-69db4fcdc4-nrs9m   2/2     Running    0          69m
```

When i describe the pod status, i found it run migration task first
```
Init Containers:
  devops-migration:
...
    State:          Running
    Ready:          False
  istio-init:
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
```
So, because I have my own initContainer, that must finish before the normal containers are started, and this container requires network traffic… so it fails because istio-proxy is not yet running…

anyone have some idea to resolve this problem ?

**Comment by howardjohn** [comment]
Hi @chenglanguo thanks for the report. The pod should have network connectivity but it will not be captured by istio proxy, so if you require mtls, etc it would not work.

This is a known issue tracked in https://github.com/istio/istio/issues/11130. There are lots of discussions and workarounds there I suggest you look through. Thanks!

**Comment by wayanshuman** [comment]
@clguo-tw I am facing exactly the same issue. Any workarounds or fixes for this?

**Comment by luisiturrios1** [comment]
I have the same issue
