### ISSUE TITLE
Prometheus is not showing requests that are blocked by PeerAuthentication 

### ISSUE THREAD

**Issue by gleichda** [istio/istio#32774]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

When securing namespaces with Peer Authentication and then calling from a namespace outside the request is blocked as expected. Within the Sidecar access logs I can see the request being blocked with the Response code detail `filter_chain_not_found` and Response Code 0. But checking Prometheus I couldn't find that entry.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Prometheus shows the blocked requests the same way it does e.g. for Timeouts

**Steps to reproduce the bug**

1. Setup istio and a Prometheus with scraping for the sidecars
2. Inject a namespace (e.g. istio-apps)
3. Install a Small web server in the istio-apps namespace (I used the httpbin docker container)
4. Expose the Server cluster internal
5. Apply a PeerAuthentication to the isto-apps namespace with mTLS STRICT
6. Curl from the istio-apps namespace to the server (will work and show up in the Prometheus)
7. Curl from the default namespace. This will fail as expected and also show in the access logs but not in the Prometheus

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```shell
$ istioctl version --remote
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (28 proxies)
```

**How was Istio installed?**

Using the Istio Operator applied via Flux V1

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE 1.19.9-gke.1400

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I think this is "working as implemented" - but probably not as expected for users. I think the issue is the access logs comes from the listener, but metrics generation is in the filter chain, so we never reach that part.

@kyessenov

**Comment by gleichda** [comment]
@bianpengyuan @howardjohn Just for my understanding is this an expected behaviour now or is it a bug?

**Comment by bianpengyuan** [comment]
@gleichda yeah I think it is working as expected. Ideally they should be reflected but very hard with how envoy works now. If the client has a sidecar, I think we should be able to observe the request failure there, not sure if that helps or not.

**Comment by gleichda** [comment]
@bianpengyuan thanks for your support. 
Should I leave the issue open as a Feature Request (Or does it make no sense as it is hard to implement)?

FYI @steinbrueckri

**Comment by bianpengyuan** [comment]
Yeah This needs to be an Envoy feature request, to make TLS failure visible at to the filter chain. Although, I don't think this is even feasible considering how Envoy listener and filter chain work.
