### ISSUE TITLE
auto mtls: add support for workload selectors on PeerAuthentication

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32788]
Currently, auto mtls only works for namespace or cluster scoped PeerAuthentications. This makes creating a DISABLE PeerAuthentication for a specific workload really hard, since now you need a DR which is confusing.

cc @incfly

**Comment by howardjohn** [comment]
Somewhat documented https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#enable-mutual-tls-per-workload

**Comment by incfly** [comment]
tracked in https://github.com/istio/istio/issues/32788
