### ISSUE TITLE
Sidecar obfuscates client IP

### ISSUE THREAD

**Issue by GabrielLasso** [istio/istio#32802]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I have Istio running on a GKE cluster, I’ve already set the externalTrafficPolicy to Local. However, the pods stil sees the client IP as 127.0.0.1.

I tried to deploy another load balancer and use it to access the pod directly, without the gateway, and got the same problem.

However, when I tried it in a namespace that doesn’t have envoy sidecar injection, it worked as expected.

Hence I am pretty sure that it is the sidecar that is causing this.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Get my real IP

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
~ istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (9 proxies)
```

```
~ kubectl version --short
Client Version: v1.21.0
Server Version: v1.18.17-gke.100
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```
**How was Istio installed?**
istioctl install --set meshConfig.accessLogFile=/dev/stdout
**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by mabushey** [comment]
```
Client Version: v1.21.0
Server Version: v1.18.17-gke.100
```
Kubectl must be within 1 minor version of the server, downgrade to 1.19.

**Comment by GabrielLasso** [comment]
> ```
> Client Version: v1.21.0
> Server Version: v1.18.17-gke.100
> ```
> 
> Kubectl must be within 1 minor version of the server, downgrade to 1.19.

Well, it shouldn't affect the server behaviour, but ok, I downgraded

**Comment by GabrielLasso** [comment]
> You will need to use TPROXY mode to do the redirection: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-InboundInterceptionMode

Thanks for replying

I did it but the problem persists.

This is my meshConfig:
```yaml
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      interceptionMode: TPROXY
      proxyMetadata: {}
    enablePrometheusMerge: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
```

I restarted the pod and it sees the request coming from 127.0.0.1

**Comment by bianpengyuan** [comment]
Oh in order to see it in pod, I think you will need to configure origin_src listener filter. See https://github.com/istio/istio/issues/5679

**Comment by GabrielLasso** [comment]
@bianpengyuan I noticed something odd...

In my mesh config, I got this:
```
~ kubectl describe istiooperators installed-state -n istio-system
Name:         installed-state
Namespace:    istio-system
Labels:       <none>
Annotations:  install.istio.io/ignoreReconcile: true
API Version:  install.istio.io/v1alpha1
Kind:         IstioOperator
Metadata:
  Creation Timestamp:  2020-11-30T22:05:00Z
  Generation:          4
  Resource Version:    167272132
  Self Link:           /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/installed-state
  UID:                 bf6e1f0e-b12a-4d8d-b90a-3cf4cbff8b73
Spec:
  ...
  Mesh Config:
    Access Log File:  /dev/stdout
    Default Config:
      Interception Mode:  TPROXY
      Proxy Metadata:
    Enable Prometheus Merge:  true
    Outbound Traffic Policy:
      Mode:  ALLOW_ANY
  Tag:       1.9.0
  ...
```
However, in the istio-init logs, I got this:

```
~ kubectl logs debug-7666f9d856-vnjhd istio-init 
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT <- THIS
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_SERVERS=[],[]

...
```

**Comment by GabrielLasso** [comment]
Do I need to restart something to change this?

**Comment by mabushey** [comment]
Typically you need to do a rolling restart of your deployment or statefulset so the pods are recreated with the updated sidecar proxy. I'm not sure what you mean by `debug deployment`.

**Comment by GabrielLasso** [comment]
> Typically you need to do a rolling restart of your deployment or statefulset so the pods are recreated with the updated sidecar proxy. I'm not sure what you mean by `debug deployment`.

@mabushey debug is the name of my deployment... Opss... I rollout restart deployment debug

Btw, I think I solved the part of the sidecar. Now the pod sees the client IP as the IP of the pod `istio-ingressgateway`

**Comment by GabrielLasso** [comment]
How do I configure the gateway to pass the origin IP to my pods?

**Comment by bianpengyuan** [comment]
The only way that I know of is through gateway topology: https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/

**Comment by GabrielLasso** [comment]
I noticed that the header X-Forwarded-For contains only the node IP, but not my IP...

And i created a new service of type `LoadBalancer` and when I used it instead of the istio gateway, the pod saw my real IP

**Comment by GabrielLasso** [comment]
Thanks @bianpengyuan  and @mabushey, I am closing the issue for now
