### ISSUE TITLE
Please fix the container name of istiod

### ISSUE THREAD

**Issue by mabushey** [istio/istio#32803]
When I previously read this https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/:
```
The istio-pilot deployment has been removed in favor of the istiod deployment, which contains all functionality that Pilot once had. For backwards compatibility, there are still some references to Pilot.
```

I [incorrectly] Assumed the numerous microservices were merged together into istiod.

```
✗  kubectl -n istio-system get pod istiod-696649974b-htff5 -o yaml | grep image
            f:image: {}
            f:imagePullPolicy: {}
    image: docker.io/istio/pilot:1.9.4
    imagePullPolicy: IfNotPresent
    image: istio/pilot:1.9.4
    imageID: docker-pullable://istio/pilot@sha256:a613e4535cad4028d0aca7e16450f16f41ed2466fa522f6c22c2b96bfbc26eba
```

Nope, the deployment was renamed to istiod, but it's still running the pilot container. If you guys say this has been removed, the container needs to be renamed to istiod. This naming nightmare has probably cost hundreds of users thousands of hours of frustration.

**Comment by howardjohn** [comment]
For backwards compatibility, etc, this seems tricky to do this due to the pains this would cause. The deployment/service name, container name, and image name are orthogonal. For example, look at ingressgateway -- all 3 are different.

Why is the name of the container impacting you?

**Comment by mabushey** [comment]
Hello @howardjohn , thanks for responding. The documentation talks about how mixer, pilot, etc have all been replaced by istiod. When I would see error messages about pilot, I would just delete the istio namespace as it was `obviously` corrupt - it was referring to old components that haven't existed since 1.4. I guarantee I'm not the only one who sees error messages involving deprecated and replaced components and came to the conclusion that the install was corrupt and needs to be reinstalled from scratch.
