### ISSUE TITLE
Multicluster dns proxy: different service domains can be resolved to same IP address

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#32819]
Let's say we have two clusters: cluster1 and cluster2.

And two service: 
foo deployed in cluster1 with ClusterIP 10.96.196.41
bar deployed in cluster2 also with ClusterIP 10.96.196.41

Then both foo and bar are resolved to `10.96.196.41`. This is definitely a bug.

**Comment by hzxuzhonghu** [comment]
cc @howardjohn @ramaraochavali

**Comment by howardjohn** [comment]
If the two services have the same cluster IP, wouldn't it happen with or without dns proxy?

**Comment by hzxuzhonghu** [comment]
Without dns proxy, In this case the remote cluster service can not be resolved, so I think no two services can be resolved to same ip.

**Comment by hzxuzhonghu** [comment]
Another find is after we support cross cluster workload entry, serviceEntry can be discovered from different clusters but the procedure of auto-allocating ips for them are separate and  can be duplicate.

**Comment by howardjohn** [comment]
cc @stevenctl

**Comment by hzxuzhonghu** [comment]
> serviceEntry can be discovered from different clusters but the procedure of auto-allocating ips for them are separate and can be duplicate.

NVM, Only WLE ssupport cross-cluster discovery not ServiceEntries
