### ISSUE TITLE
Pilot-agent in high CPU after an upgrade to 1.8.4 

### ISSUE THREAD

**Issue by sudeeptoroy** [istio/istio#32822]
**Bug description**

After an upgrade to istio 1.8.4 in multiple clusters we have observed each clusters having a few pods in crashloopback state. 
From the underlying VM we see pilot-agent consuming 200% cpu and in sleep state (top output).

Observation: 
From the dashboards we see input packet and CPU going up together. Network traffic comes down but CPU stays high forever.
If we kill only the pilot-agent process the pod start off fine(no crashloopback) and VM cpu's percentage come back down.
It takes a while to get to this state but once it does, pods stays in this bad state. 
istioctl proxy status does not list these agents.

We have also seen a similar case reported earlier with envoy (not pilot-agent) - #18229. Will the fix apply to this case.

Any ideas on how I can troubleshoot further?
We do not have livenessProbe on pilot-agent, not sure why we have not configured this?

[X ] Test and Release
[X] Upgrade

**Comment by sudeeptoroy** [comment]
strace output:

strace -r -f -p 25890
strace: Process 25890 attached with 16 threads
strace: [ Process PID=27938 runs in x32 mode. ]
strace: [ Process PID=26477 runs in x32 mode. ]
strace: [ Process PID=26285 runs in x32 mode. ]
strace: [ Process PID=26283 runs in x32 mode. ]
strace: [ Process PID=26282 runs in x32 mode. ]
strace: [ Process PID=26281 runs in x32 mode. ]
strace: [ Process PID=25890 runs in x32 mode. ]
[pid 23507]      0.000000 futex(0xc000378548, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26302]      0.000031 futex(0x3cc1d18, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26289]      0.000010 futex(0x3cc1e60, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26287]      0.000010 waitid(P_PID, 15,  <unfinished ...>
[pid 26286]      0.000015 futex(0xc000408148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26284]      0.000010 futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULLstrace: [ Process PID=13294 runs in x32 mode. ]
strace: [ Process PID=26478 runs in x32 mode. ]
strace: [ Process PID=26431 runs in x32 mode. ]
^Cstrace: Process 25890 detached
strace: Process 26281 detached
strace: Process 26282 detached
strace: Process 26283 detached
strace: Process 26284 detached
<detached ...>
strace: Process 26285 detached
strace: Process 26286 detached
strace: Process 26287 detached
strace: Process 26289 detached
strace: Process 26302 detached


pstree -p 25890
pilot-agent(25890)─┬─envoy(26309)─┬─{envoy}(26405)
                   │              ├─{envoy}(26406)
                   │              ├─{envoy}(26407)
                   │              ├─{envoy}(26408)
                   │              ├─{envoy}(26411)
                   │              ├─{envoy}(26412)
                   │              ├─{envoy}(26484)
                   │              ├─{envoy}(26485)
                   │              ├─{envoy}(26486)
                   │              ├─{envoy}(26487)
                   │              ├─{envoy}(26506)
                   │              └─{envoy}(28097)
                   ├─{pilot-agent}(26281)
                   ├─{pilot-agent}(26282)
                   ├─{pilot-agent}(26283)
                   ├─{pilot-agent}(26284)
                   ├─{pilot-agent}(26285)
                   ├─{pilot-agent}(26286)
                   ├─{pilot-agent}(26287)
                   ├─{pilot-agent}(26289)
                   ├─{pilot-agent}(26302)
                   ├─{pilot-agent}(26431)
                   ├─{pilot-agent}(26477)
                   ├─{pilot-agent}(26478)
                   ├─{pilot-agent}(23507)
                   ├─{pilot-agent}(27938)
                   └─{pilot-agent}(13294)

**Comment by howardjohn** [comment]
can you get a CPU profile? localhost:15020/debug/pprof/profile. https://github.com/istio/istio/wiki/Analyzing-Istio-Performance has some more info about this.


One thing I am confused at - why does pstree show so many process under 25890? I only see:
```
pilot-agent─┬─envoy───8*[{envoy}]
            └─14*[{pilot-agent}]
```

on my cluster

**Comment by vikaschoudhary16** [comment]
pilot-agent does not run a pprof server. will have to build a custom proxyv2 image i think to get cpu profile

**Comment by sudeeptoroy** [comment]
Hi @vikaschoudhary16 , @howardjohn , thank you for looking into the issue. 

yes pprof is unavailable on istio-agent. Listing a few findings we have:

Strace of the parent pid of the stuck pilot-agent shows errors. 

Pilot agent PID 10765 consuming 200% CPU share
Getting the parent process

cat /proc/10765/status | grep PPid
PPid:   10699


strace -p 10699 -f -c
strace: Process 10699 attached with 9 threads
^Cstrace: Process 10699 detached
strace: Process 10700 detached
strace: Process 10701 detached
strace: Process 10702 detached
strace: Process 10703 detached
strace: Process 10704 detached
strace: Process 10708 detached
strace: Process 10820 detached
strace: Process 12178 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
49.25    0.015352          44       347             11          futex
19.35    0.006033          26       227                          nanosleep
15.73    0.004903          15       313                          epoll_pwait
  6.21    0.001935           6       278               135       read
  5.05    0.001574          15       103                          sched_yield
  4.39    0.001370           9       143                           write
  0.02    0.000007           7         1                   1         restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.031174                  1412       147 total


in strace we see this log repeated. 
[pid 10708] read(15,  <unfinished ...>
[pid 10700] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid 10708] <... read resumed> 0xc00018c000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 10708] epoll_pwait(5, [{EPOLLOUT, {u32=3493202088, u64=140083851561128}}], 128, 0, NULL, 2) = 1
[pid 10708] epoll_pwait(5,  <unfinished ...>

**Comment by howardjohn** [comment]
pprof was added in 1.9, it would be great to upgrade, especially since 1.8 is EOL (https://istio.io/latest/news/support/announcing-1.8-eol-final/)

**Comment by soulxu** [comment]
FYI, I think there is a regression of https://github.com/envoyproxy/envoy/pull/8922 is fixed original, I filed an issue and working on it  https://github.com/envoyproxy/envoy/issues/16951
