### ISSUE TITLE
IngressGateway cannot route multicluster traffic to target service with v1.8.6

### ISSUE THREAD

**Issue by rytswd** [istio/istio#32848]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I have done canary upgrade of control plane from v1.8.5 to v1.8.6, and everything was working as expected. But when I switched over to v1.8.6 data plane, multicluster communication started to fail completely with 503 errors. I can see that the source cluster seems to have got the right endpoint details, and the source Pod is trying to reach the correct IP for the target service, but the logs of IngressGateway in the target cluster says NR.

```log
 [2021-05-12T23:27:24.305Z] "- - -" 0 NR "-" 0 0 8 - "-" "-" "-" "-" "-" - - 10.244.1.68:15443 10.244.1 .1:37598 - -
 [2021-05-12T23:27:24.315Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.68:15443 10.244.1 .1:35174 - -
 [2021-05-12T23:27:24.350Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.68:15443 10.244.1 .1:1814 - -
 [2021-05-12T23:27:26.392Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.68:15443 10.244.1 .1:58561 - -
```

NOTE: `10.244.1.68` is the Pod IP of IngressGateway in the target cluster.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

Multicluster behaviour does not change between v1.8.5 and v1.8.6, and the traffic hits the target service correctly.

**Steps to reproduce the bug**

I'm using KinD clusters for testing, and `istioctl manifest generate` to create the installation definitions.

Most of the setup steps are documented here (but this involves quite a bit of moving parts unrelated to the issue).
https://github.com/rytswd/get-istio-multicluster/blob/main/docs/2-local-clusters/argo-cd-with-generated-manifests.md

I'm still working on simpler reproducible steps. The main canary upgrade is done in Kustomization, and you can find commented out v1.8.5 to v1.8.6 with canary, and then to full migration.
https://github.com/rytswd/get-istio-multicluster/blob/main/clusters/armadillo/istio/installation/generated-manifests/kustomization.yaml

I could confirm that the multicluster communication was working with canary upgrade, where IngressGateway was still v1.8.5. As soon as I upgraded the data plane to v1.8.6, it started to fail to connect with 503 errors.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Both clusters show the same results:

```console
$ istioctl version --remote
client version: 1.9.4
control plane version: 1.8.6
data plane version: 1.8.6 (8 proxies)
```

```console
$ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.15
```

**How was Istio installed?**

Using YAML definition generated by `istioctl manifest generate`. 

**Environment where the bug was observed (cloud vendor, OS, etc)**

KinD with v1.18 cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

I have added both clusters' bug reports.
[bug-report-cluster-armadillo.tar.gz](https://github.com/istio/istio/files/6469635/bug-report-cluster-armadillo.tar.gz)
[bug-report-cluster-bison.tar.gz](https://github.com/istio/istio/files/6469636/bug-report-cluster-bison.tar.gz)

**Comment by rytswd** [comment]
I have dumped the bug-reports before and after Gateway replacement.

[bug-report-cluster-armadillo-v1.8.5-gateways.tar.gz](https://github.com/istio/istio/files/6478598/bug-report-cluster-armadillo-v1.8.5-gateways.tar.gz)
[bug-report-cluster-armadillo-v1.8.6-gateways.tar.gz](https://github.com/istio/istio/files/6478600/bug-report-cluster-armadillo-v1.8.6-gateways.tar.gz)
[bug-report-cluster-bison-v1.8.5-gateways.tar.gz](https://github.com/istio/istio/files/6478601/bug-report-cluster-bison-v1.8.5-gateways.tar.gz)
[bug-report-cluster-bison-v1.8.6-gateways.tar.gz](https://github.com/istio/istio/files/6478602/bug-report-cluster-bison-v1.8.6-gateways.tar.gz)

Also, I tested installing v1.8.6 directly into a brand new cluster, but still got the same behaviour where IngressGateway was complaining with NR 503.

[bug-report-cluster-bison-v1.8.6-gateways-without-canary.tar.gz](https://github.com/istio/istio/files/6480463/bug-report-cluster-bison-v1.8.6-gateways-without-canary.tar.gz)
[bug-report-cluster-armadillo-v1.8.6-gateways-without-canary.tar.gz](https://github.com/istio/istio/files/6480462/bug-report-cluster-armadillo-v1.8.6-gateways-without-canary.tar.gz)

---

Although it is rather lengthy and has many other unnecessary moving parts, I have put all the steps to repro the issue here:
- For v1.8.5 Gateways + v1.8.6 Control Plane:  https://github.com/rytswd/get-istio-multicluster/blob/istio-32848-with-v1.8.5-and-v1.8.6/docs/issue-related/istio-32848-with-canary.md
- For v1.8.6 only: https://github.com/rytswd/get-istio-multicluster/blob/istio-32848/docs/issue-related/istio-32848.md

**Comment by rytswd** [comment]
As per offline discussion, I have tried with `PILOT_ENABLE_LEGACY_AUTO_PASSTHROUGH` set to `"true"` to imitate v1.8.5 behaviour with v1.8.6.
⚠️ NOTE: For anyone coming to find this ticket, this setting is NOT recommended, this was only for testing. ⚠️

[bug-report-cluster-armadillo-v1.8.6-gateways-with-legacy-auto-passthrough.tar.gz](https://github.com/istio/istio/files/6480909/bug-report-cluster-armadillo-v1.8.6-gateways-with-legacy-auto-passthrough.tar.gz)
[bug-report-cluster-bison-v1.8.6-gateways-without-legacy-auto-passthrough.tar.gz](https://github.com/istio/istio/files/6480913/bug-report-cluster-bison-v1.8.6-gateways-without-legacy-auto-passthrough.tar.gz)

**Comment by howardjohn** [comment]
Ok so what is going on is the `.global` rewrite stuff, which has not been documented/recommended since 1.7(?) was broken in the recent security fix. The envoyfilter depends on sni_cluster filter, which is no longer used due to major security issues associated.

Related issue: https://github.com/istio/istio/issues/29335#issuecomment-841475900

**Comment by rytswd** [comment]
Sorry for coming back to this old ticket - I remember seeing some Slack discussion around `.global` use cases, where some granular control with `.global` setup is sometimes preferable. I hadn't had the chance to try it out until recently, but finally managed to get the same traffic pattern to work on v1.8.6 onwards.

### With v1.8.5 and below

Before the security fix with v1.8.6, my understanding is that `.global` traffic was handled with the following setup

- [ Source cluster ]: `ServiceEntry` for the `.global` endpoint (e.g. `httpbin.bison-offerings.global`, which lives in the destination cluster)
- [ Source cluster ]: `DestinationRule` for `ISTIO_MUTUAL` TLS
- [ Destination cluster ]: `Gateway` for listening to `.global` ingress traffic with `AUTO_PASSTHROUGH` TLS
- 📌 [ Destination cluster ]: `EnvoyFilter` for updating `.global` to `.svc.cluster.local`

As mentioned the security note https://istio.io/latest/news/security/istio-security-2021-006/, `AUTO_PASSTHROUGH` setup in the Gateway was about the security issue. My understanding is that the security fix affected `EnvoyFilter` handling of  `.global`, and thus could not be used for multicluster communication anymore.

### With v1.8.6 and onwards (including v1.9.5)

With the following setup, the same traffic pattern can still be achieved. It's basically the same, except for the last item.

- [ Source cluster ]: `ServiceEntry` for the `.global` endpoint (e.g. `httpbin.bison-offerings.global`, which lives in the destination cluster)
- [ Source cluster ]: `DestinationRule` for `ISTIO_MUTUAL` TLS
- [ Destination cluster ]: `Gateway` for listening to `.global` ingress traffic with `AUTO_PASSTHROUGH` TLS
- ✅ [ Destination cluster ]: `ServiceEntry` to handle incoming `.global` traffic (e.g. another `ServiceEntry` for `httpbin.bison-offerings.global` to `httpbin.bison-offerings.svc.cluster.local`)


---

This means we can have 2 different patterns for multicluster configuration.

1. Using remote secret, clusters use Kubernetes API Server to connect to Istio Control Plane to get all the endpoint details on the remote cluster.
2. Using explicit ServiceEntry on both clusters, specific services can be made available in the multicluster setup.

If multicluster setup is only for cluster redundancy and availability, using Kubernetes API Server may suffice. However, I find this approach not suitable for some cases such as when I want to have only limited number of services exposed, and/or have many Pods and clusters that Kubernetes API Server and Istio Control Plane get hammered by the frequent updates.

The explicit `ServiceEntry` setup as described above may be a bit cumbersome, but the control we gain from it is just like how Istio used to have `.global` usage, and it can also work with any domain such as `.cluster-x` instead. This may be a specific and uncommon use case, but it may still be useful for some.

I have not been able to catch up with the latest v1.10 and v1.11, so will need to dig into those.

**Comment by rytswd** [comment]
@romanlehner
Sorry I've been tied up quite a bit with other stuff, let me get back to you within this week. I think I have a working example and configuration I can share, but will need to revisit and verify once again.

**Comment by romanlehner** [comment]
Hey @rytswd multi-mesh master,

have you found some time getting into this challenge?

**Comment by rytswd** [comment]
Hi @romanlehner - sorry I haven't, did a quick testing with my setup in https://github.com/rytswd/get-istio-multicluster, but I think it needs some more fix. I could see it working with VirtualService also in place, and that may be the missing piece from the description above. But not 100% sure yet, please allow me some more time to get to the bottom of this.

**Comment by romanlehner** [comment]
Sure, looking forward to see your magic happening ;)

**Comment by rytswd** [comment]
@romanlehner
So I have done some testing, and as long as you have all the resources I mentioned above, it should work - and you wouldn't need extra resources such as VirtualService. DestinationRule at the source cluster plays a role as well, so make sure you have it in place (just pointing out as you didn't mention it in your configs above).

Even with everything in place, though, with v1.8, you could potentially get some routing errors just like you saw. One thing you need to check is the use of `outbound_.80_._.static-server.service.consul` endpoint being available from your IngressGateway. You can check with `istioctl pc endpoints -n istio-system your-istio-ingress-gateway` - and if you don't see any cluster with the `_` notation, it's probably that your IngressGateway needs configuration update.

In other words, if you see `outbound|80||static-server.service.consul` but not `outbound_.80_._.static-server.service.consul`, you need to sort it out. I'm not 100% sure of the internal logic, but the cluster information with `|` and `_` are different, and multicluster communication requires the latter to be in place.

The actual configuration for handling this logic is the env variable `ISTIO_META_ROUTER_MODE` on your IngressGateway. Make sure to set it to `sni-dnat` rather than `standard`, which is the new default value from v1.8. (But I read somewhere that this is an old setup that's no longer required for the recent versions.)
From my own testing, I could actually see `sni-dnat` being used as my default for IngressGateways I created with different name (e.g. `armadillo-multicluster-ingressgateway`), but IngressGateway with the name of `istio-ingressgateway`, for some reason, was using `standard`. As you can see in the [release note of v1.8](https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/) and specifically [this part](https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/#auto-passthrough-gateway-mode), you can update that from IstioOperator.

I will be refining my repository YAMLs and documentation a bit more, but you can find the [actual IstioOperator resource here ](https://github.com/rytswd/get-istio-multicluster/blob/dev/clusters/armadillo/istio/installation/operator-usage/istio-multicluster-gateways.yaml), and how that generates [these resources](https://github.com/rytswd/get-istio-multicluster/blob/dev/clusters/armadillo/istio/installation/generated-manifests/1.8.6/full-installation/istio-multicluster-gateways-install.yaml) (created with `istioctl generate manifest`).

**Comment by romanlehner** [comment]
Many thanks @rytswd for your hints and taking your time to look into it. I experimented further with my setup. After following the official guide for [istio multi network cluster](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/) with version `1.12.0`, this is what I needed to add to make custom host names work to communicate between mesh clusters:

Service Entry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: static-server
  namespace: default
spec:
  hosts:
  - static-server.service.consul
  location: MESH_INTERNAL
  ports:
  - number: 8080 
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 3.124.235.218 # the east-west gateway IP address of the external cluster
      ports: 
        http: 15443 
  - address: static-server.default # this directs to the app in the local cluster
    ports:
      http: 8080
  subjectAltNames:
  - "spiffe://cluster.local/ns/default/sa/static-server"
```
Destination rule:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: static-server
  namespace: default
spec:
  host: static-server.service.consul
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
East-West Gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"
        - "*.service.consul" # accepting requests from the custom host name defined in the service entry
```
## Notes
The env variable `ISTIO_META_ROUTER_MODE=sni-dnat` is not necessary after `1.11+`. 

## What I was missing
- The destination rule to make sure the service is communicating over mTLS (even though istio is configured to use auto-mTLS)
- AWS load balancers are not supported to resolve the host name such as `<name>.<zone>.elb.amazonaws.com`. I had to replace that with the actual IP address in the service entry. In our case the loadbalancer has 3 addresses, I added only one here for simplicity. I found this issue through in the `istiod` logs.
