### ISSUE TITLE
1 node(s) didn't match Pod's node affinity.

### ISSUE THREAD

**Issue by JCzz** [istio/istio#32841]
**Bug description**

```
get pods -n istio-system
NAME                                    READY   STATUS             RESTARTS   AGE
istio-ingressgateway-564b5ffdf7-497wb   0/1     Pending            0          58m
istio-ingressgateway-564b5ffdf7-nlcts   0/1     Pending            0          58m
istio-ingressgateway-564b5ffdf7-wj722   0/1     Pending            0          58m
istiod-7b688587d8-qrxr6                 0/1     CrashLoopBackOff   7          16m
istiod-7b688587d8-tcjjp                 0/1     Running            3          17m
istiod-7b688587d8-z6xf2                 0/1     Running   
```

`  kubectl describe pod istio-ingressgateway-564b5ffdf7-wj722 -n istio-system
Warning  FailedScheduling  3m25s (x50 over 48m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity.
`

[ ] Docs
[x ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version
2 errors occurred:
	* error port-forwarding into istiod-7b688587d8-qrxr6.istio-system: an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-7b688587d8-qrxr6:15014)
	* error exec'ing into istiod-7b688587d8-qrxr6 discovery container: error exec'ing into istiod-7b688587d8-qrxr6/istio-system discovery container: unable to upgrade connection: container not found ("discovery")

1.9.5

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:10:45Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

```
**How was Istio installed?**

kubectl apply -f https://github.com/knative/serving/releases/download/v0.22.0/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.22.0/serving-core.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.22.0/istio.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.22.0/net-istio.yaml

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Istio does not support ARM kubernetes clusters. See https://github.com/istio/istio/issues/21094 for tracking. Thanks!

**Comment by Leschge** [comment]
> Istio does not support ARM kubernetes clusters. See #21094 for tracking. Thanks!

@howardjohn the latest release (https://github.com/istio/istio/releases/tag/1.10.0) lists a build for arm64 but I am still receiving the same error. Even tho Isitio arm64 build exists it does not support Kubernetes clusters running on arm64? Is that correct?

```
kubectl get pods
NAME                                    READY   STATUS             RESTARTS   AGE
istio-ingressgateway-8657768d87-nnz7p   0/1     Pending            0          91m
istio-egressgateway-585f7668fc-dmz4r    0/1     Pending            0          91m
svclb-istio-ingressgateway-pwx9x        5/5     Running            0          91m
istiod-56874696b5-ms4lk                 0/1     CrashLoopBackOff   23         96m
```

**Comment by howardjohn** [comment]
Yes, we have only arm64 client binary (istioctl) not server binaries (istiod, etc)
