### ISSUE TITLE
Failed to start proxy: fork/exec /work/out/linux_amd64/envoy: no such file or directory

### ISSUE THREAD

**Issue by timmyyuan** [istio/istio#32855]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I tried to run unit tests in my local host. but failed by the following error:
```
--- FAIL: TestRenewToken (1.35s)
mockserver.go:209: Registered handler for endpoints:
/v1/projects/-/serviceAccounts/service-1234567@gcp-sa-meshdataplane.iam.gserviceaccount.com:generateAccessToken
 /v1/token
setup.go:200: 2021-05-12 05:03:04.211270956 +0000 UTC m=+1.414034799 check if all servers in the STS flow are up and ready
setup.go:206: set up server address to dial 127.0.0.1:20023
setup.go:218: 2021-05-12 05:03:04.230754727 +0000 UTC m=+1.433518561 all servers in the STS flow are up and ready
setup.go:192: failed to start proxy: fork/exec /work/out/linux_amd64/envoy: no such file or directory
FAIL
FAIL	istio.io/istio/security/pkg/stsservice/test/renew_sts_token	1.518s
2021-05-12T05:03:05.3334164Z 2021-05-12T05:03:04.033520Z	info	port allocation status
```

Test and Release

Virtual Machine

**Expected behavior**

The tests pass

**Steps to reproduce the bug**

Checkout the master branch of Istio and `make test`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

master

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Ubuntu 20.04, go 1.16

```
$ uname -a
Linux vultr.guest 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Please run `make build` first, which will download envoy.
