### ISSUE TITLE
istioctl manifest apply --set failed

### ISSUE THREAD

**Issue by rtttech** [istio/istio#32879]
istio 1.8.2, the following command failed:

istioctl manifest apply  --set .values.global.proxy.image="mosnio/proxyv2:1.5.2-mosn"  --set meshConfig.defaultConfig.binaryPath="/usr/local/bin/mosn"

Error: unknown flag: --set

**Comment by howardjohn** [comment]
The error message here is really bad, but the command has been replaed with `istioctl install --set ...`

**Comment by rtttech** [comment]
istioctl install --set will lead to the reinstall of istio, is it the expected action?

**Comment by howardjohn** [comment]
`istioctl install` is just a rename of `manifest apply`. They do the same.

Its a declarative API, like `kubectl apply`.
