### ISSUE TITLE
panic: no valid local IP address found

### ISSUE THREAD

**Issue by nc-ruth** [istio/istio#32885]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Some of my pods are crashing with an error saying: "panic: no valid local IP address found"

The full description is:
`panic: no valid local IP address found

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/cmd.constructConfig(0xc000a7dd88)
istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:120 +0xaf4
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x3c58c20, 0xc000b10200, 0x0, 0x10)
istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:48 +0x26
github.com/spf13/cobra.(*Command).execute(0x3c58c20, 0xc000b10100, 0x10, 0x10, 0x3c58c20, 0xc000b10100)
github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3c58ec0, 0x0, 0x0, 0x0)
github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
istio.io/istio/pilot/cmd/pilot-agent/main.go:487 +0x31`

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Pod should start up successfully.

**Steps to reproduce the bug**
Kinda hard to reproduce directly, but it happens frequently right now on my cluster.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version: 1.8.2
Kubernetes server: 1.19.7

**How was Istio installed?**
Istio was installed using Helm. 

**Environment where the bug was observed (cloud vendor, OS, etc)**
Cloud vendor: AKS, 
OS: Ubuntu 18.04.5 LTS  
Kernel: 5.4.0-1040-azure   
Runtime: containerd://1.4.4+azure

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
What kind of CNI is this? The code is:

```
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return nil, err
	}

	for _, a := range addrs {
		if ipnet, ok := a.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			return ipnet.IP, nil
		}
	}
	return nil, fmt.Errorf("no valid local IP address found")
```

So it seems like there is no pod IP provisioned for the pod somehow?

**Comment by nc-ruth** [comment]
We are using Azure CNI, and there is some limitations on how many IP's the Azure CNI can propagate, but we are nowhere near that limit. (AFAIK). 

We are looking into the Azure CNI limitation is upon node level. The default limit on node level seems like it is 40, but is way higher on cluster level. 
Thank you @howardjohn for pointing into the CNI direction.
