### ISSUE TITLE
istioctl validate does not allow period in exportTo

### ISSUE THREAD

**Issue by Stono** [istio/istio#32881]
**Bug description**

Given:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stuff
spec:
  exportTo:
  - '.'
```

Istioctl validate gives:
```
❯ istioctl validate -f 1
Error: 2 errors occurred:
        * VirtualService//stuff: only .,*,~, or a valid DNS 1123 label is allowed as exportTo entry
```

However modifying the resource on the cluster directly works fine (passes validating webhook).

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Are you using an old (1.8) istioctl perhaps?

**Comment by Stono** [comment]
Nope, 1.9.5

**Comment by howardjohn** [comment]
Ah yeah I see that as well. It works on 1.10 which is where I got mixed up. Weird, will look into it
