### ISSUE TITLE
istioctl install does not wait for install cni to become ready

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#32887]
istioctl should wait for install-cni container to become ready at installation time.

**Comment by HarleyB123** [comment]
Hey 👋 

I’d like to take this one. Not sure where to start though - can someone point me in the right direction? 😅

**Comment by bianpengyuan** [comment]
Thanks @HarleyB123 !

The wait logic should be part of this function, need to investigate why istioctl does not wait for istio-cni-node daemonset to become ready: https://github.com/istio/istio/blob/da6178604559bdf2c707a57f452d16bee0de90c8/operator/pkg/helmreconciler/apply.go#L42

**Comment by HarleyB123** [comment]
Interesting, looks like it should already work based on what I think the function is doing. 

@bianpengyuan Do you have steps to reproduce this so that I can debug?

**Comment by bianpengyuan** [comment]
@HarleyB123 do you have Istio installed with CNI? It should be pretty easy to reproduce by pointing the CNI network directory to some non-existing file name using `cniConfFileName` https://istio.io/latest/docs/setup/additional-setup/cni/

**Comment by bianpengyuan** [comment]
Note unlike other istio components, istio cni runs as daemonset, not sure if that makes any difference at istioctl readiness check.

**Comment by holooooo** [comment]
'cause daemonset dose not have statud phase ready or something else for check daemonset is ready.When user add a new daemonset, all the params in status is 0. It hard to judge it ready or not.(meybe desiredNumberScheduled should be 0).

And if user deploy in minukube(or only one node can run daemonset pod), default maxUnavailable num will equal DesiredNumberScheduled. That make unready to ready.

So I check if NumberReady == 0, it can treat initialization and no available nodes as unavailable

**Comment by morvencao** [comment]
@bianpengyuan Does this only happens when the number of k8s node that meets the istio-cni scheduling condition is **1** ?
As you knonw, the default `maxUnavailable` for istio-cni is **1**, which means if if the node also **1**, then the current check 

```
if !(int(ds.Status.NumberReady) >= int(ds.Status.DesiredNumberScheduled) - maxUnavailable) { }
``` 

will also return `false`, that's the cause of the issue, right? 
If this is the case, I suggest to add case for `1` node.

**Comment by bianpengyuan** [comment]
It not only happens on one node. The case I ran into is that at installation time, there is a brief period where (NumberDesired = -1, NumberReady = 0). Current logic will consider this as ready. It looks like @holooooo also sees the case where (NumberDesired = 0, NumberReady = 0).
