### ISSUE TITLE
AWS platform/locality detection is not working when istio-proxy is running in non-root mode

### ISSUE THREAD

**Issue by alx13** [istio/istio#32880]
**Bug description**
If istio-proxy is running in non root mode on AWS EKS optimized AMI it's not detecting platform hence not providing locality information to envoy.

The code [here](https://github.com/istio/istio/blob/master/pkg/bootstrap/platform/aws.go#L120) is trying to read files from `/sys` filesystem, but it fails:

```
Container: istio-proxy
istio-proxy@pod-75d7bbf784-qvntg:/$ cat /sys/hypervisor/uuid
cat: /sys/hypervisor/uuid: No such file or directory
istio-proxy@pod-75d7bbf784-qvntg:/$ cat /sys/class/dmi/id/product_uuid
cat: /sys/class/dmi/id/product_uuid: Permission denied
istio-proxy@pod-75d7bbf784-qvntg:/$ ls -la /sys/class/dmi/id/product_uuid
-r-------- 1 root root 4096 May 13 05:08 /sys/class/dmi/id/product_uuid
istio-proxy@pod-75d7bbf784-qvntg:/$ cat /sys/class/dmi/id/product_version
istio-proxy@pod-75d7bbf784-qvntg:/$
```

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
platform and locality detection works with non-root privileges

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
- same code is used in istio 1.8, 1.9
- kubernetes 1.18 on EKS with AMI id `ami-07ab1fd3a20f0cfbf`

**Comment by howardjohn** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
Is there anyone with AWS expertise that can comment on a way to detect platform without root privileges?

**Comment by alx13** [comment]
Currently I solved it with EC2 userdata and chmod a+r on

/sys/class/dmi/id/product_uuid

But feels a little bit dirty.

**Comment by ramaraochavali** [comment]
@douglas-reid @howardjohn  WDYT about users specifying the platform via Env var or some other way and if specified can take precedence over auto detection?

**Comment by ramaraochavali** [comment]
@howardjohn @douglas-reid ^^ WDYT? In our env also in AWS we do not get locality set and because of which zone metrics are not being generated.

**Comment by douglas-reid** [comment]
@ramaraochavali using an ENV var is already (semi-)supported for GCP. adding a similar mechanism for AWS attributes would be acceptable. with GCP, collapsing into a single ENV var ultimately proved problematic, so it would be good to avoid repeating that same mistake for AWS.

**Comment by howardjohn** [comment]
Are the region/zone labels not set on the node? It should fallback to
those..?

Or is this envoy native metrics?

**Comment by ramaraochavali** [comment]
@douglas-reid Thank you. I see the usage of env var for GCP.  I will try to add multiple env vars for AWS metadata as a fallback.


@howardjohn  These are Envoy native metrics
