### ISSUE TITLE
Ingressgateways listeners are not created for port 80/443

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#32898]
**Bug description**
I recently upgraded to v1.9.4, and I am running the ingressgateway pods as daemonset on hostNetwork as well, the patch mentioned here used to work for me in 1.6.3: https://github.com/istio/istio/issues/24204#issuecomment-636907074 - by changing the `targetPort` to `80` in the service, but it isnt working anymore? Now the behavior is - it does not open the listeners for port `80` and the ingress stops working. 

To check if there is something wrong with my setup, I tried with default istio installation (no hostNetwork). I have a gateway with port 80, this is what it looks like:

```
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```
Now after patching the istio-ingressgateway service to targetPort 80 instead of '8080', it removes the listener on 8080 and doesnt add anything back - which is consistent with the hostNetwork setup. Any idea why this isnt working now? There should be an entry like this:
```
0.0.0.0 80  ALL   Route: http.80
```

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
v1.9.4

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**
k8s v0.20

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
you need to set the pod to run as root most likely, which is required for binding to port 80

**Comment by Shashankft9** [comment]
The pods are running as root only, I didnt do any custom user configs;

```
kubectl exec -it -n istio-system istio-ingressgateway-ltnhz bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@k8s-cloud-w01:/#

```

Did you mean something else by run as root?

**Comment by howardjohn** [comment]
Does the pod have env var `ISTIO_META_UNPRIVILEGED_POD=true` set? If so then it will be treated by the control plane as non-root and not get configs for ports <1024

**Comment by hzxuzhonghu** [comment]
@Shashankft9 you can check the istiod log to find some evidence.

**Comment by Shashankft9** [comment]
So, `ISTIO_META_UNPRIVILEGED_POD=true` was set, I removed that env var and then changed the securityContext like this:
```
        securityContext: 
          privileged: true
          readOnlyRootFilesystem: true
```
It;s working now, thanks for the help. 
Closing the issue.
