### ISSUE TITLE
pilot-agent 1.8.6 build is broken 

### ISSUE THREAD

**Issue by sudeeptoroy** [istio/istio#32899]
Trying to build 1.8.6 pilot-agent and it  broken. Do you know how to fix it. 

$ make docker.proxyv2
mkdir -p /work/out/linux_amd64/logs
mkdir -p /work/out/linux_amd64/release
STATIC=0 GOOS=linux GOARCH=amd64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /work/out/linux_amd64/ ./istioctl/cmd/istioctl ./pilot/cmd/pilot-discovery ./pkg/test/echo/cmd/client ./pkg/test/echo/cmd/server ./operator/cmd/operator ./cni/cmd/istio-cni ./cni/cmd/istio-cni-repair ./cni/cmd/istio-cni-taint ./cni/cmd/install-cni ./tools/istio-iptables ./tools/bug-report
go: github.com/envoyproxy/go-control-plane@v0.9.8-0.20210420150603-831d6316d7b9: reading https://proxy.golang.org/github.com/envoyproxy/go-control-plane/@v/v0.9.8-0.20210420150603-831d6316d7b9.mod: 410 Gone
	server response: not found: github.com/envoyproxy/go-control-plane@v0.9.8-0.20210420150603-831d6316d7b9: invalid version: unknown revision 831d6316d7b9
real	0m0.140s
user	0m0.151s
sys	0m0.056s
Makefile.core.mk:299: recipe for target 'build-linux' failed

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ X] Upgrade

**Comment by howardjohn** [comment]
see https://github.com/istio/istio/issues/32846
