### ISSUE TITLE
istio-operator chart not found in releases

### ISSUE THREAD

**Issue by Morriz** [istio/istio#32897]
The documentation refers to installation of the operator like this:
```
helm install istio-operator manifests/charts/istio-operator \
  --set operatorNamespace=istio-operator \
  --set watchedNamespaces="istio-namespace1\,istio-namespace2"
```

But that folder location is not packaged into the release.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by shamsher31** [comment]
@Morriz Which version of Istio you are using?

**Comment by shamsher31** [comment]
I just quickly verified and I can see it's available with the following releases.

```
[istio-1.8.3]$ ls manifests/charts/istio-operator/
Chart.yaml  crds  files  templates  values.yaml

[istio-1.9.4]$ ls manifests/charts/istio-operator/
Chart.yaml  crds  files  templates  values.yaml

[istio-1.10.0-rc.0]$ ls manifests/charts/istio-operator/
Chart.yaml  crds  files  templates  values.yaml
```

**Comment by Morriz** [comment]
1.9.5? maybe I just clicked to download the zip then. My excuse
