### ISSUE TITLE
Istioctl very slow when talking to istiod

### ISSUE THREAD

**Issue by e96wic** [istio/istio#32923]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

`istioctl proxy-status` or `istioctl version --remote=true` complete in a reasonable amount of time.

**Steps to reproduce the bug**

Run `istioctl version --remote=true` or `istioctl proxy-status`. Basically any command that talks to istiod is slow like this.

I ran istioctl with log output: `--log_output_level=all:debug,default:debug`

I'm getting this output (trimmed a bit):

```
GET https://<my_ip>/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Distiod 200 OK in 86 milliseconds

GET https://<my_ip>/api/v1/namespaces/istio-system/pods/istiod-1-8-6-66d76d85f6-425qw:15014/proxy/version 503 Service Unavailable in 30043 milliseconds
Response Body: Error trying to reach service: 'dial tcp 10.0.68.76:15014: i/o timeout' // 10.0.68.76 is one of the istiod pod IPs

POST https://<my_ip>/api/v1/namespaces/istio-system/pods/istiod-1-8-6-66d76d85f6-425qw/exec?command=%2Fusr%2Flocal%2Fbin%2Fpilot-discovery&command=version&command=-o&command=json&container=discovery&container=discovery&stderr=true&stdout=true 101 Switching Protocols in 123 milliseconds

...

GET https://<my_ip>/api/v1/namespaces/istio-system/pods/istiod-1-8-6-66d76d85f6-425qw:8080/proxy/debug/syncz 503 Service Unavailable in 30098 milliseconds
Response Body: Error trying to reach service: 'dial tcp 10.0.68.76:8080: i/o timeout'

...
```

Eventually after >3mins the command finishes with the correct version of istio as output. What's strange are the `:15014/proxy/version` and `:8080/proxy/debug/syncz 503` requests which timeout after 30s.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

worked with istioctl 1.6.14
does not work with >=1.7 (I've tested with 1.7.5, 1.8.6, 1.9.3)

**How was Istio installed?**

1. downloaded istioctl tar.gz from github
1. installed istio with a local operator spec, running `istioctl manifest generate -f <my_file>` and a subsequent `kubectl apply`

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
Perhaps a duplicate of https://github.com/istio/istio/issues/30646
