### ISSUE TITLE
Invalid XDS/SDS UDS paths

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32920]
Bootstrap is changed to `{{ .config.ConfigPath }}/SDS`, but the code is hardcoded to `./etc/istio/proxy/{XDS,SDS}`.

We need to make them consistent or ConfigPath must equal /etc/istio/proxy which would be a regression.

**Comment by kyessenov** [comment]
Where in the code is it hardcoded? I just added a test that runs two agents on the same machine.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/d45e4d56addbd7474e0090b760ca3e6d5e781314/pilot/cmd/pilot-agent/options/agent.go#L35

I think the tests overrides it
