### ISSUE TITLE
how to config a wasm filter that works after route?

### ISSUE THREAD

**Issue by rtttech** [istio/istio#32939]
I want to write a wasm filter that works after route, is this possible in istio?

**Comment by mandarjog** [comment]
Can you elaborate?
Are you looking for an "upstream filter ?"  Do you want to add behaviour as the data is sent out to a backend server ?

@kyessenov @PiotrSikora
Is it possible to deploy wasm filter as an upstream filter?

**Comment by kyessenov** [comment]
I don't see why not, but we never tested it.

**Comment by rtttech** [comment]
> Can you elaborate?
> Are you looking for an "upstream filter ?" Do you want to add behaviour as the data is sent out to a backend server ?
> 
> @kyessenov @PiotrSikora
> Is it possible to deploy wasm filter as an upstream filter?

Yes, after destination has been determinated and before sending.
What's more, the filter should be able to work on ingress and  egress gateway.

**Comment by mandarjog** [comment]
There is a difference between destination route/cluster is determined and an actual endpoint is selected.
Do you have a specific need for the latter ? Can you elaborate on the use case?

**Comment by rtttech** [comment]
> There is a difference between destination route/cluster is determined and an actual endpoint is selected.
> Do you have a specific need for the latter ? Can you elaborate on the use case?

I mean "endpoint is selected"
Yes, I can elaborate on the use case.

**Comment by rtttech** [comment]
Actually my use case is:
We need to set parameter which is different for each destination to wasm filter.  We tried to put the parameters in http headers by HTTPRoute headers but can not get the added http headers in wasm filter.
