### ISSUE TITLE
Options to opt-out discovery for service/endpoint/pods

### ISSUE THREAD

**Issue by xinlaini** [istio/istio#32930]
**Describe the feature request**
I wonder if we can add a feature that makes pilot *not* discover certain resources based on annotations or labels. Currently, pilot establishes watch streams for a variety of resources against k8s api server using SharedInformer, but istio doesn't seem to expose the field/label selector to select on the workloads to watch.

The reason we would like this feature is in our cluster, we generate workloads (pods+services) dynamically (spark app). These workloads run for a couple of minutes and got torn down. The updates of these resources were watched by the pilot, who will subsequently push the updated xDS to the entire mesh. However, xDS for these resources were not needed by anybody, so the churn in the mesh is unnecessary and wasteful. We have observed significant compute resource usage drop (cpu,memory) on the pilots when we stopped running these short-lived batch jobs.

An exposed "opt-out-for-discovery" annotation would be helpful to stop pilot from watching the annotated resources. 

**Describe alternatives you've considered**
1. Implement Sidecar CRD that ignores these workloads - this needs all sidecars in the mesh to do so, and this won't work for envoys at the edge.
2. Add exportTo="." annotations for the service we want to opt-out. This doesn't stop pilot from watching the unwanted resources, and it doesn't stop pushing of xDS to the short-lived jobs' sidecars either.
3. Schedule these workloads into a separate k8s cluster, which doesn't participate in pilot's service discovery. This should work, but we deem this short-term solution since the placement of these short-lived jobs are now determined by whether they need to be discovered by istio, which seems arbitrary and breaks the transparency istio aims to provide.

[ ] Docs
[ ] Installation
[ X] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Does https://istio.io/latest/blog/2021/discovery-selectors/ meet your needs?

**Comment by xinlaini** [comment]
thanks, that looks like what we need.  From that blog, it is not clear if we can turn off a workload's discovery but still enable it for sidecar injection. If we can, that'll be exactly what we need. We'll give it a try.

**Comment by whwalter** [comment]
We are currently looking at discovery selectors to deal with similar noisy jobs but would prefer to be able to opt services into the mesh. Ideally via a label selector similar to the way pods opt-in to sidecar injection. Having service selectors that filter the discovered services in  namespace to only services that have opted into the mesh via label would be preferred to having to restrict say out of mesh run to jobs to specific namespaces.

**Comment by howardjohn** [comment]
Discovery selectors can use matchExpressions which can do inversion. So you can have it opt in.

**Comment by whwalter** [comment]
Yes the label selectors seem like a solid choice I would just prefer them on the service listers/indexer in addition to the namespace. That way I could have a service in a namespace opt into the mesh but have pilot and the ingress gateway stay blissfully unaware of my run to completion pods that don't need mesh access.
