### ISSUE TITLE
"Install/upgrade experience" Google Forms is not public

### ISSUE THREAD

**Issue by christophetd** [istio/istio#32940]
**Bug description** The form indicated after running `istioctl install --verify` is not accessible

```
✔ Istio is installed and verified successfully
Thank you for installing Istio 1.10.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/KjkrDnMPByq7akrYA
```

![image](https://user-images.githubusercontent.com/136675/118788937-8e7a9180-b894-11eb-8e54-f988ad380751.png)

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior** Form is accessible to everyone

**Steps to reproduce the bug** Go to https://docs.google.com/forms/d/e/1FAIpQLSfzonL4euvGgUM7kyXjsucP4UV8mH9M2snKVFQnT-L7eIXp_g/formrestricted

**Version** istioctl 1.10.0

**How was Istio installed?** istioctl install --verify

**Environment where the bug was observed (cloud vendor, OS, etc)** EKS

**Comment by shamsher31** [comment]
@christophetd Thanks for reporting the issue.

The work is already initiated and will be in effect by 20 May 2021.

![email](https://user-images.githubusercontent.com/2920003/118791954-d1e4f800-b8b4-11eb-9ce7-73cb80b94d9f.png)
