### ISSUE TITLE
istiodRemote should not be an installation component

### ISSUE THREAD

**Issue by frankbu** [istio/istio#32949]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

The istiodRemote install component doesn't really make much sense. It's not installing a different component, but rather a subset of the pilot component's charts, with a few minor tweaks.

Looking at istiod-remote files and templates, they are an exact copy of a subset (all files and 10/17 templates) of the same charts in istio-control/istio-discovery. The only differences are:

```
templates/clusterrole.yaml (very small diff)
templates/clusterrolebinding.yaml (very small diff)
templates/role.yaml (very small diff)
templates/rolebinding.yaml (very small diff)
values.yaml (telemetry: enabled: false)
Chart.yaml (different keywords)
```

It would seem to make more sense get rid of all the duplication. We should delete the istiod-remote charts completely and add a few more guards in the istio-control/istio-discovery charts.

Users could then install Install in a remote cluster like this:

```
  components:
    pilot:
      enabled: true
  values:
    global:
      externalIstiod: true
```

Instead of the currently more confusing way:

```
  components:
    pilot:
      enabled: false
    istiodRemote:
      enabled: true
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by frankbu** [comment]
I wonder if a further cleanup could be to separate the pilot component into two components: `pilot` and `pilotClient`?

**Comment by howardjohn** [comment]
> I wonder if a further cleanup could be to separate the pilot component into two components: `pilot` and `pilotClient`?

A bit confused what the difference between this and istiodRemote is (other than the name)?

@linsun and @irisdingbj may have some more opinions here, I think they were the ones leading the split

**Comment by frankbu** [comment]
> A bit confused what the difference between this and istiodRemote is (other than the name)?

Two differences, the way I'm imagining it:

1. No duplicate copies of charts. The charts that are duplicated in `istiodRemote` today, would also be deleted from `istio-control/istio-discovery` (`pilot` component) and only apprear in the new (better) named component `pilotClient`.
2. The `pilotClient` charts would be used for both local and remote istiod. The charts in this component that are not exactly the same in `istiod-remote` as in `istio-control/istio-discovery` today, will be merged versions of the two, with remote version triggered by `values.global.istiodRemote=true`.

**Comment by frankbu** [comment]
To clarify, this issue is suggesting that we do the first part (i.e., get rid of the istiod-remote charts, in favour of slightly more customizable ones in istio-control/istio-discovery) only. We can then (maybe) consider splitting out the `pilotClient` charts in the future.

**Comment by linsun** [comment]
Okay with merging it back to istio-discovery.  When we first introduced istiodRemote, we got folks against us adding more configs and extra logic to istio-discovery and so we started with istiodRemote. Now that istiodRemote is a lot more stable and mostly same as istio-discovery, seems make sense to merge it back to istio-discovery.
