### ISSUE TITLE
How to support multiple version of networking CRD in one istio?

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#32946]
Supposed that we have v1alpha3 version and v1beta1 version of VirtualService resources in the K8s cluster, can we use one istio to watch these all VirtualService resources? 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Yes, see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#writing-reading-and-updating-versioned-customresourcedefinition-objects. Kubernetes will convert them for you, you can just ask for one or the other.
