### ISSUE TITLE
Build error for Istio 1.9.5

### ISSUE THREAD

**Issue by elukey** [istio/istio#32978]
Hi!

I am trying to build istio 1.9.5 but I get the following error:

```
GOOS=linux GOARCH=amd64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /home/elukey/github/istio/out/linux_amd64/ ./istioctl/cmd/istioctl ./pilot/cmd/pilot-discovery ./pkg/test/echo/cmd/client ./pkg/test/echo/cmd/server ./operator/cmd/operator ./cni/cmd/istio-cni ./cni/cmd/istio-cni-repair ./cni/cmd/istio-cni-taint ./cni/cmd/install-cni ./tools/istio-iptables ./tools/bug-report
go: github.com/envoyproxy/go-control-plane@v0.9.9-0.20210420150223-d760b7f6014b: reading https://proxy.golang.org/github.com/envoyproxy/go-control-plane/@v/v0.9.9-0.20210420150223-d760b7f6014b.mod: 410 Gone
	server response: not found: github.com/envoyproxy/go-control-plane@v0.9.9-0.20210420150223-d760b7f6014b: invalid version: unknown revision d760b7f6014b
```

Version 0.9.9 seems not present as tag on github.com/envoyproxy/go-control-plane, am I missing something?

Thanks in advance!

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Build completing successfully.

**Steps to reproduce the bug**

Checkout the istio repo and the 1.9.5 tag, then:
```
export BUILD_WITH_CONTAINER=0
make gen-charts && make linux-build
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by shamsher31** [comment]
Ref: https://github.com/golang/go/issues/35164

**Comment by elukey** [comment]
@shamsher31 tried to set `GOSUMDB=off` but I still get the error. My main question mark is around `https://github.com/envoyproxy/go-control-plane@v0.9.9-0.20210420150223-d760b7f6014b` that leads to a 404, and https://github.com/envoyproxy/go-control-plane/tags not mentioning 0.99.

**Comment by shamsher31** [comment]
@elukey Yes, I tried the same thing and it produces the same error. Maybe we need to decrease `go-control-palne` version, but I'm not sure. Let's take a input from @jacob-delgado

**Comment by jacob-delgado** [comment]
To build 1.9.5 you need to use the 1.9.5-patch branch. We had to build 1.9.5 with a private go-control-plane sha that couldn't be pushed publicly since we don't own the repository. There's a commit on that branch that lets you build 1.9.5 by updating the dependencies.

**Comment by howardjohn** [comment]
Hi, thanks for the issue. Please see https://github.com/istio/istio/issues/32846. Thanks!
