### ISSUE TITLE
TestNormalization test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32984]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32952/integ-security-k8s-tests_istio/1395233559047835648

Everything seems right - it just doesn't change the normalization as request. Not sure why.

**Comment by JimmyCYJ** [comment]
@yangminzhu would you mind to take a look?

**Comment by yangminzhu** [comment]
I think the test is already no longer flaky now: https://k8s-testgrid.appspot.com/istio_istio#integ-security-k8s-tests_istio&include-filter-by-regex=.*TestNormalization.*&width=20
