### ISSUE TITLE
Test stability regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32985]
Running summary:
* Last prow update was 5/17 (https://github.com/istio/test-infra/commit/07e88ae5d09da7257ac863e3c5c052bbee754a84). No issues after this until 5/19.
* On 5/19 we updated to kind v0.11.0
* Around 5/19 night we started seeing elevated test failures. These were not isolated to a single failure or job, just generally things not working. A lot of them related to timeouts in api-server, etc.
* Assuming it was a regression in kind, we reverted kind v0.11.0 back to v0.10.0. The errors persisted.
* After analyzing the failures and the cluster, nothing stood out. Failures happened on ~all nodes, node resource utilization look normal, no errors, etc.
* We updated docker to 20.10.6, no improvement
* We updated the build cluster's k8s version. This was mostly to bounce all of the nodes. No improvement.
* We reverted to the exact docker image prior to kind v0.11.0 (rather than reverting the change in Dockerfile and rebuilding), same issues occurring 

Aside from the Kind v0.11.0 update, there were no known changes to any of our infrastructure

The failures seem to have one thing in common: containerd.

* We have seen buildkit fail to connect to local containerd socket (I think, anyhow) with [`grpc: the client connection is closing`](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33009/integ-distroless-k8s-tests_istio/1395738219563192320) and [`no active session for ssyocosy7viqzb53vwjkxf322: context deadline exceeded`](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32990/integ-telemetry-mc-k8s-tests_istio/1395435822206947328/build-log.txt)
* We have seen docker pushes to our local image registry fail [logs](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32996/integ-pilot-multicluster-tests_istio/1395738304959221760)
* We have seen containerd (in kind) fail to start the etcd container [logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32952/integ-pilot-multicluster-tests_istio/1395732447588519936/artifacts/kind/remote-control-plane/containerd.log)
* We have seen containerd (in kind) start the etcd container, but only after health check timeouts are hit [logs](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32998/integ-security-multicluster-tests_istio/1395480913936125952)
* We have seen the kind cluster docker container fail to start with port conflicts [logs](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6-k8s-tests_istio_postsubmit/1395443736476913664)

I have also checked our internal prow instance (which is a completely distinct build cluster, etc) and we do see the `grpc: the client connection is closing` errors; we don't run kind at all for those.

**Comment by howardjohn** [comment]
"grpc: the client connection is closing" seen a few times. This is after kind revert, and not related to kind so hints to other issues?: https://storage.googleapis.com/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1395443736518856704/build-log.txt

https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6-k8s-tests_istio_postsubmit/1395443736476913664 kind failing to start *on 0.10*

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32998/integ-security-multicluster-tests_istio/1395480913936125952 kind start failure
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32997/integ-multicluster-k8s-tests_istio/1395474016524832768 docker build failure
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32998/integ-multicluster-k8s-tests_istio/1395480911595704320 docker build failure

**Comment by ericvn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32990/integ-telemetry-mc-k8s-tests_istio/1395435822206947328/build-log.txt docker build failure -  
failed to solve: rpc error: code = Unknown desc = no active session for ssyocosy7viqzb53vwjkxf322: context deadline exceeded

**Comment by howardjohn** [comment]
Failures are not clustered by node

**Comment by howardjohn** [comment]
Docker upgrade did not help. Bouncing all the nodes

**Comment by howardjohn** [comment]
`May 21 13:34:20 remote-control-plane containerd[206]: time="2021-05-21T13:34:20.547930482Z" level=error msg="CreateContainer within sandbox \"2a0078993edd6bdae73e4e69a42b85a2d159e9b3dd7f5a4f43562c673959a2e1\" for &ContainerMetadata{Name:etcd,Attempt:0,} failed" error="failed to reserve container name \"etcd_etcd-remote-control-plane_kube-system_3bc1fd9c29fabcf8b71551d4490274da_0\": name \"etcd_etcd-remote-control-plane_kube-system_3bc1fd9c29fabcf8b71551d4490274da_0\" is reserved for \"a012fee57a38d2649b0428e6190363d652755be1e8e9a9782cdc168976e9255b\""`
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32952/integ-pilot-multicluster-tests_istio/1395732447588519936/artifacts/kind/remote-control-plane/containerd.log

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32996/integ-pilot-multicluster-tests_istio/1395738304959221760 broken write to... localhost

**Comment by howardjohn** [comment]
grpc: connection close with containerd logs (not interesting, unfortunately...) https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33009/integ-distroless-k8s-tests_istio/1395738219563192320

**Comment by howardjohn** [comment]
Overall summary:
* On 5/19 we updated to kind v0.11.0
* Around 5/19 night we started seeing elevated test failures. These were not isolated to a single failure or job, just generally things not working. A lot of them related to timeouts in api-server, etc.
* Assuming it was a regression in kind, we reverted kind v0.11.0 back to v0.10.0. The errors persisted.
* After analyzing the failures and the cluster, nothing stood out. Failures happened on ~all nodes, node resource utilization look normal, no errors, etc.
* We updated docker to 20.10.6, no improvement
* We updated the build cluster's k8s version. This was mostly to bounce all of the nodes. No improvement.

The failures seem to have one thing in common: containerd.

* We have seen buildkit fail to connect to local containerd socket (I think, anyhow) with [`grpc: the client connection is closing`](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33009/integ-distroless-k8s-tests_istio/1395738219563192320) and [`no active session for ssyocosy7viqzb53vwjkxf322: context deadline exceeded`](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32990/integ-telemetry-mc-k8s-tests_istio/1395435822206947328/build-log.txt)
* We have seen docker pushes to our local image registry fail [logs](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32996/integ-pilot-multicluster-tests_istio/1395738304959221760)
* We have seen containerd (in kind) fail to start the etcd container [logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/32952/integ-pilot-multicluster-tests_istio/1395732447588519936/artifacts/kind/remote-control-plane/containerd.log)
* We have seen containerd (in kind) start the etcd container, but only after health check timeouts are hit [logs](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32998/integ-security-multicluster-tests_istio/1395480913936125952)
* We have seen the kind cluster docker container fail to start with port conflicts [logs](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6-k8s-tests_istio_postsubmit/1395443736476913664)

**Comment by howardjohn** [comment]
Attempted to revert to the exact image as before, to avoid nondeterminstic docker build issues. Still getting failures: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32953/integ-operator-controller-tests_istio/1395767319505932288

**Comment by chaodaiG** [comment]
One observation: the node image used for creating kind cluster is `gcr.io/istio-testing/kind-node:v1.21.0`, which technically is a floating ref to tag`v1.21.0`, any chance the tag was recently moved to a different image hash on 05/19?

**Comment by howardjohn** [comment]
@chaodaiG good call. Looking at the image:
```
Created time	
April 9, 2021 at 7:18:01 AM UTC-7
Uploaded time	
April 9, 2021 at 7:20:08 AM UTC-7
```

Assuming that is reliable, I don't think its changed

**Comment by howardjohn** [comment]
Tested adding a retry on the grpc error: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33009/integ-ipv6-k8s-tests_istio/1395830214612750336

It failed once, then succeeded on subsequent run. Docker logs show some info:
```
time="2021-05-21T19:54:53.367898721Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/e2f291a373d34c6ee9395fabb6687c3295cc200cdbc0d9bbfa2fcbe87277e818 pid=851
time="2021-05-21T19:56:58.925281039Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/83ae1f505711bf01a6bd397cfd614ae24db68da4d78a4e0d85710a9a51436768 pid=9480
2021-05-21 19:57:02.582296 I | http2: server: error reading preface from client @: read unix /var/run/docker.sock->@: read: connection reset by peer
time="2021-05-21T19:57:06.823743730Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/3d9192f943e8c6e9a04b3ef85b81203095a3d93fc1e531d21de493a5427d0b5a pid=10591
time="2021-05-21T19:59:23.241924211Z" level=error msg="Error running exec a91814546355eec66ddb7ddb0643f22a512ff8cc65831c8313f20cb77493e390 in container: exec attach failed: error attaching stdout stream: write unix /var/run/docker.sock->@: write: broken pipe"
```

It then went on to fail in the actual test though

**Comment by howardjohn** [comment]
I briefly thought the grpc errors were gone, but discovered another one: https://prow.istio.io/view/gs/istio-prow/logs/release_istio_postsubmit/1396858572750458880. So all the same symptoms occuring

**Comment by howardjohn** [comment]
![2021-24-05_09-11-52](https://user-images.githubusercontent.com/623453/119375842-2818b900-bc70-11eb-8e56-e143d513b2d0.png)

Our disk throttling might be solved by bigger disk. In theory 500gb (from 256gb) will give us 240mb/s, which is 2x our current and based on current numbers should cover all throttling. Source: https://cloud.google.com/compute/docs/disks/performance#ssd_persistent_disk

**Comment by howardjohn** [comment]
Switching to 512gb SSDs now...

**Comment by howardjohn** [comment]
512gb SSDs seem to have neither reduced the test failure rate, nor decreased the throttle amount:
![2021-24-05_11-28-04](https://user-images.githubusercontent.com/623453/119391375-20aedb00-bc83-11eb-947c-80f61ed161de.png)
Switched over at 10:30. May need a bit more data, but I suspect we will grow our usage as to fill the capacity of the disks we get.

**Comment by howardjohn** [comment]
![2021-24-05_15-41-03](https://user-images.githubusercontent.com/623453/119415437-79439f80-bca6-11eb-9864-d49b6f03bbc0.png)

Here is the first graph I can find that shows a noticeable different before and after our test failures started.
![2021-24-05_15-49-46](https://user-images.githubusercontent.com/623453/119416063-ad6b9000-bca7-11eb-88c0-b8e1cfe6ba4b.png)
Looking at k8s level metrics we can see an increase in "evictable" memory usage

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32619/integ-pilot-k8s-tests_istio/1396942366111174656 is an interesting one. etcd logs show a bunch of `took too long (1m51.026378714s) to execute`. Longest was 1m51s, and we have many instances of >1min

While analyzing built a recent statically compiled fio/; `curl -L https://storage.googleapis.com/howardjohn/tmp/fio -o /usr/bin/fio; chmod +x /usr/bin/fio`

**Comment by howardjohn** [comment]
I have a suspicion somehow we are getting killed in IO. I have been running fio on some nodes an occasionally our performance *substantially* degrades. Like 10-50x worse, when nothing is even running on the node. Need proof though..

**Comment by howardjohn** [comment]
Going to try a few things:
* Disable autoscaling on the normal test pool
* Add a 1 node test pool with the same periodic job running. This will be the sole job on the node, in attempt to isolate noisy neighbor
* Same 1 node test pool but with an n2 instance

**Comment by howardjohn** [comment]
Ok, did ^.

NOTE: I accidentally made the 1 node pools using COS instead of ubuntu. Might as well keep it to test, but if this resolves the issue we should ensure its fixed with ubuntu as well

**Comment by ericvn** [comment]
istio.io test (https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/9841/doc.test.profile_none_istio.io/1397219337504296960/artifacts/tests-setup-profile-none-26c15c/TestDocs/setup/install/virtual-machine/test.sh/test.sh/_test_context/test.sh_output.txt)
```
VERIFY FAILED check_call (timeout after 120s):
received:
"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (56) Recv failure: Connection reset by peer"
expected:
"Hello version:"
```

**Comment by howardjohn** [comment]
More memory graphs
![2021-25-05_10-16-45](https://user-images.githubusercontent.com/623453/119540463-52d34200-bd42-11eb-9a82-175067560cb4.png)
![2021-25-05_10-16-08](https://user-images.githubusercontent.com/623453/119540466-536bd880-bd42-11eb-9e78-6b3cd21513a7.png)
![2021-25-05_10-15-58](https://user-images.githubusercontent.com/623453/119540468-536bd880-bd42-11eb-8851-a23e0ed5fb7b.png)

**Comment by howardjohn** [comment]
Trying to correlate failures with other jobs on the node:

* https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32697/integ-security-multicluster-tests_istio/1397285384815120384 was concurrent with release job (https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32697/release-test_istio/1397285382336286720)

**Comment by howardjohn** [comment]
With https://github.com/istio/test-infra/pull/3349/ we bumped back to kind v0.11, as well as picking up docker debug logs

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-multicluster-k8s-tests-n2_istio_periodic/1397323070787555328 our first n2 failure, proving we can get failures on isolated nodes. However, the failure is one I have seen rarely for months, so I am not convinced its the same: `The connection to the server localhost:8080 was refused - did you specify the right host or port?`. Seems like kubeconfig is setup wrong

**Comment by howardjohn** [comment]
Buildkit failure with debug logs: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/33097/integ-helm-tests_istio/1397331501963546624/build-log.txt

```
time="2021-05-25T23:24:02Z" level=debug msg="saved six5t13imc1gadzlpd1wzc2ds as local.sharedKey:context:context:"
time="2021-05-25T23:24:15Z" level=debug msg="diffcopy took: 18.212038536s"
time="2021-05-25T23:24:15Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Canceled desc = context canceled\n"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:17Z" level=debug msg="session finished: <nil>"
time="2021-05-25T23:24:18Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Canceled desc = context canceled\n"
time="2021-05-25T23:24:20Z" level=error msg="failed to kill runc ze0nowxx2cqdom6nbtruon1km: buildkit-runc did not terminate successfully: exit status 1: container \"ze0nowxx2cqdom6nbtruon1km\" does not exist\n"
```

diffcopy taking 18s

**Comment by howardjohn** [comment]
Found proof of a test failure that was caused by a node problem:
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1397365261627035648

Describe of the node:
```
Events:
  Type     Reason                   Age               From                                                     Message
  ----     ------                   ----              ----                                                     -------
  Warning  KubeletStart             26m (x2 over 8h)  systemd-monitor, gke-prow-test-pool-500gb-f196ce52-frcf  Started Kubernetes kubelet.
  Normal   Starting                 26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Starting kubelet.
  Warning  InvalidDiskCapacity      26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Node gke-prow-test-pool-500gb-f196ce52-frcf status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Node gke-prow-test-pool-500gb-f196ce52-frcf status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Node gke-prow-test-pool-500gb-f196ce52-frcf status is now: NodeHasSufficientPID
  Normal   NodeNotReady             26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Node gke-prow-test-pool-500gb-f196ce52-frcf status is now: NodeNotReady
  Normal   NodeAllocatableEnforced  26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Updated Node Allocatable limit across pods
  Normal   NodeReady                26m               kubelet, gke-prow-test-pool-500gb-f196ce52-frcf          Node gke-prow-test-pool-500gb-f196ce52-frcf status is now: NodeReady
```

(relative to 07:06:45 PST). We can see the test fails at 01:44:51, or 06:44:51 PST, ~26min before the weird restart.

Logs show:
```
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: I0526 01:39:27.127052    3777 trace.go:205] Trace[519564731]: "iptables Monitor CANARY check" (26-May-2021 01:39:00.031) (total time: 27095ms):
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: Trace[519564731]: [27.095591197s] [27.095591197s] END
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: E0526 01:39:27.136097    3777 gce_instances.go:644] Failed to fetch instanceID via Metadata: Get "http://169.254.169.254/computeMetadata/v1/instance/hostname": net/http: timeout awaiting response headers
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: E0526 01:39:27.250917    3777 gce_instances.go:584] getInstanceByName: failed to get instance gke-prow-test-pool-500gb-f196ce52-frcf in zone us-west1-a; err: googleapi: Error 403: Request had insufficient authentication scopes.
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: More details:
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: Reason: insufficientPermissions, Message: Insufficient Permission
May 26 01:39:27 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: E0526 01:39:27.251068    3777 gce_pd.go:146] Failed to get instance type from GCE cloud provider
May 26 01:39:59 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: I0526 01:39:59.262005    3777 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/srv/kubernetes/pki/ca-certificates.crt
May 26 01:39:59 gke-prow-test-pool-500gb-f196ce52-frcf kubelet[3777]: I0526 01:39:59.262865    3777 kubelet_getters.go:178] "Pod status updated" pod="kube-system/kube-proxy-gke-prow-test-pool-500gb-f196ce52-frcf" status=Running
May 26 01:40:13 gke-prow-test-pool-500gb-f196ce52-frcf systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 26 01:40:13 gke-prow-test-pool-500gb-f196ce52-frcf systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
May 26 01:40:13 gke-prow-test-pool-500gb-f196ce52-frcf systemd[1]: Stopped Kubernetes kubelet.
May 26 01:40:13 gke-prow-test-pool-500gb-f196ce52-frcf systemd[1]: Started Kubernetes kubelet.
```

**Comment by howardjohn** [comment]
Found more:

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33102/integ-ipv6-k8s-tests_istio/1397371696771502080 fails at 02:10:51, kubelet restarted at the exact same time on node gke-prow-test-pool-500gb-f196ce52-pj8k

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33102/integ-security-multicluster-tests_istio/1397371698226925568 test still running, but we see `couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request` at the exact same time kubelet restart (2021-05-26T02:11:27.211429Z) on node gke-prow-test-pool-500gb-f196ce52-h2mq. Also at the same time was this job: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-122_istio_postsubmit/1397365270774812672 which seems to be stuck. Not sure what the means

https://prow.istio.io/view/gs/istio-prow/logs/integ-helm-tests_istio_postsubmit/1397376558192136192 fails at the exact same time as kubelet restart on gke-prow-test-pool-500gb-f196ce52-d15r

**Comment by mandarjog** [comment]
@howardjohn did docker max parallelism solve the issue, or we are awaiting results?

**Comment by howardjohn** [comment]
> @howardjohn did docker max parallelism solve the issue, or we are awaiting results?

No, I don't think so,I got a failure on that pr. We are pretty lost and just trying things out and seeing what sticks at the moment

**Comment by howardjohn** [comment]
Deployed this daemonset to measure stalls:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: check-slow-node
  namespace: howardjohn
spec:
  selector:
    matchLabels:
      name: check-slow-node
  template:
    metadata:
      labels:
        name: check-slow-node
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          function log() {
            echo -e "$(date -u '+%Y-%m-%dT%H:%M:%S.%NZ')\t$*"
          }

          i=0
          while :; do
              log "Starting $i"
              START=$(( $(date '+%s%N') / 1000000))
              echo $i > /tmp/data
              END=$(( $(date '+%s%N') / 1000000))
              COMPLETE=$(($END-$START))
              log "Finished $i in $COMPLETE ms"
              if [ $COMPLETE -gt 1000 ]; then
                  log "Command took to long!"
                  exit 1
              fi
              sleep .5
              ((i++))
          done
        image: ubuntu:focal
        name: script
        resources:
          requests:
            cpu: 10m
```

Failure log:

* Node gke-prow-test-pool-500gb-f196ce52-pj8k at `2021-05-26T16:51:07.648325447Z  Finished 2964 in 19556 ms`. https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33120/integ-pilot-k8s-tests_istio/1397581310528065536 is running concurrently and fails. https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32959/integ-pilot-multicluster-tests_istio/1397595204709519360 is also running concurrently and has a 2 minute gap at the same time

**Comment by howardjohn** [comment]
Begrudgingly disabling buildx for now: https://github.com/istio/istio/pull/33133

**Comment by howardjohn** [comment]
Our periodic jobs on COS seem to do a lot better than ubuntu. Since this seems to be low level, I am going to switch the node pool to COS. This will require some changes to the ipv6 stuff to pin them to ubuntu nodes. Will keep this updated

**Comment by howardjohn** [comment]
Currently we have 50 ubuntu, 0 COS. Swapping to 5 ubuntu and 45 COS nodes right now

**Comment by howardjohn** [comment]
After the COS swap stability is WAY better

**Comment by howardjohn** [comment]
Switching to a dedicate IPv6 Node pool, deleting the old nodes, and enabling auto scaling

**Comment by howardjohn** [comment]
Considering this fixed
