### ISSUE TITLE
priavte aks istio

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#32980]
Hello 

I have installed and configured istio on our private cluster aks
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service: 
            type: LoadBalancer
            loadBalancerIP: xx.xxx.xxx.xxx

"code": "PrivateIPAddressIsAllocated",
"message": "IP configuration which is already allocated to resource  networkInterfaces|aks-pool3-13468513-vmss.
How to add a static allocated ip to istio ingress?
I just want to assign a static IP to our istio gateway

do you have any suggestions please?

Thanks

**Comment by howardjohn** [comment]
It looks like you configured it correctly but the IP is already assigned. This seems like a misconfiguration on the config or a bug in Azure. I am not sure this is an istio issue - We are just creating a Service, the load balancer assignment is entirely up to Azure
