### ISSUE TITLE
Host based routing not working for tcp ports

### ISSUE THREAD

**Issue by harwee** [istio/istio#33019]
**Bug description**
Host based routing on tcp ports seems to be not working. Gateways route traffic to tcp ports which are not described in them. Virtual service routing traffic to destination even if hosts don't match the described hosts.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
This is the gateway configuration
      
    kind: Gateway
    apiVersion: networking.istio.io/v1alpha3
    metadata:
    name: common--postgres
    namespace: database-gateways
    spec:
    servers:
        - hosts:
            - postgres.internaldomain.com
            - common.postgres.internaldomain.com
        port:
            name: postgres
            number: 5432
            protocol: TCP
    selector:
        istio: ingressgateway
    ---
    kind: Gateway
    apiVersion: networking.istio.io/v1alpha3
    metadata:
    name: common--mongodb
    namespace: database-gateways
    spec:
    servers:
        - hosts:
            - mongodb.internaldomain.com
            - common.mongodb.internaldomain.com
        port:
            name: mongo
            number: 27017
            protocol: MONGO
    selector:
        istio: ingressgateway

This is the virtual service configuration

    kind: VirtualService
    apiVersion: networking.istio.io/v1alpha3
    metadata:
    name: common-mongos
    namespace: database--mongodb
    spec:
    hosts:
        - common.mongodb.internaldomain.com
    gateways:
        - database-gateways/common--mongodb
    tcp:
        - match:
            port: 27017
        route:
            - destination:
                host: common-mongos
                port:
                number: 27017
    ---

    kind: VirtualService
    apiVersion: networking.istio.io/v1alpha3
    metadata:
    name: common-postgresql
    namespace: crunchydata--postgresql
    spec:
    hosts:
        - common.postgres.internaldomain.com
    gateways:
        - database-gateways/common--postgres
    tcp:
        - match:
            - port: 5432
        route:
            - destination:
                host: common-postgres
                port:
                number: 5432

`common.postgres.internaldomain.com:27017` should not connect to virtual-service common-mongos port 27017
`common.mongodb.internaldomain.com:5432` should not connect to virtual-service common-postgresql port 5432

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
> istioctl version --remote

    client version: 1.6.5
    control plane version: 1.9.5
    data plane version: 1.9.5 (12 proxies)

> kubectl version --short

    Client Version: v1.18.5
    Server Version: v1.18.16-eks-7737de

**How was Istio installed?**
rancher helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS + Classic Loadbalancer Internal

**Comment by howardjohn** [comment]
TCP Does not have a "Host" header to route on like HTTP. This in progress docs page may explain this better: https://github.com/istio/istio.io/pull/9800

**Comment by harwee** [comment]
Ah that makes sense, it never crossed my mind that headers are not available for TCP connection. Closing this issue now. Thankyou!
