### ISSUE TITLE
"VolumeSource" definition not present in "IstioOperator Options" document page

### ISSUE THREAD

**Issue by YSZhuoyang** [istio/istio#33016]
**Bug description**

**Affected product area**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features**

**Expected behavior**

User should be redirected to `VolumeSource` description section when clicking it as below:
![Screen Shot 2021-05-21 at 7 05 33 pm](https://user-images.githubusercontent.com/11630182/119112590-93dc0580-ba67-11eb-9cfa-7567c67cbc23.png)

**Steps to reproduce the bug**

Click `VolumeSource` linked text in `IstioOperator Options` page.

**Version**

Istioctl:
```
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (1 proxies)
```

**How was Istio installed?**

`istioctl install -f <istio-operator.yaml> -y`

**Environment where the bug was observed (cloud vendor, OS, etc)**

MacOS

**Comment by cheriL** [comment]
same problem
