### ISSUE TITLE
Excessive test dump size

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33034]
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1396122398708731904 is one example, its >4gb. I think this may be leading to high IO which may impact other jobs on the same node as well possible

cc @stevenctl I think you were looking at this a bit

**Comment by howardjohn** [comment]
That job took 14 minutes to upload! 6.23gb total

**Comment by stevenctl** [comment]
It's mostly `proxy-config.json` each taking up ~1.5MB in that example. These types of things get duplicated with deeply nested subtests. Working on something to help reduce this by skipping the dump for leaf tests that don't have unique config changes.

**Comment by stevenctl** [comment]
`| grep core.proxy` results in a lot of files around 180mb. We probably don't always want these.

**Comment by stevenctl** [comment]
```
...
63651246/primary/statefulset-v1-0_core.proxy
173.63 MiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/primary/tproxy-v1-664db5df55-spr2w_core.proxy
172.62 MiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/remote/a-v1-6bfb5d5b9d-pwv8x_core.proxy
145.68 MiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/remote/b-v1-5db4fc987c-xjzl7_core.proxy
171.62 MiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/remote/c-v1-7dccbc8f4d-fkqwj_core.proxy
172.5 MiB    gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/remote/headless-v1-6c4869bd9b-dbnqv_core.proxy
172.49 MiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/artifacts/pilot-endpointslice-93577615b20/TestTraffic/virtualservice/set_header/vm/to_vm/from_primary/_test_context/echo-1-69067-state663651246/remote/statefulset-v1-0_core.proxy
..
```

**Comment by stevenctl** [comment]
There are around 2000 of these

**Comment by howardjohn** [comment]
Ah that make sense. Normally we don't hit it since envoy doesn't crash often (hopefully..) but the PR triggering it is updating Envoy and there is a bug in it. Limiting to 2-5 core dumps seems like a simple fix

One thing I am not sure of - I don't think we can keep a global counter across the entire test suite, right? Each suite is its own binary, so a global variable will be wiped? Probably NBD, max 5 * suites is still only like 30. We could do less than 5 as well, probably they represent the same crash if we have multiple

Nice find!

**Comment by stevenctl** [comment]
Closing due to #35355 feel free to re-open if we see the issue again or you don't think it's fixed.
