### ISSUE TITLE
Provide a way to put peer metadatas into envoy's dynamic metadata.

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#33046]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I think maybe istio can provide a way to put peer metadatas into envoy's dynamic metadata.
So users can use a lua plugin to get remote pod's labels or other informations from dynamic metadata.
And also can be used in rate limit configuration.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[*] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kyessenov** [comment]
This has been explored but unfortunately the performance cost is too high. It's better to allow Lua access to peer metadata filter state instead.
