### ISSUE TITLE
Allow caBundle to be specified in the IstioOperator file

### ISSUE THREAD

**Issue by etifontaine** [istio/istio#33052]
Hello all !

It would be great to allow the user to specify his own `caBundle` value.
In a GitOps approach where all generated files from the Operator are pushed to Git, Flux (or any other tool) will try to reconciliate with this empty string. 
For now, we use a Git patch to override this value with the one already in our cluster.

https://github.com/istio/istio/blob/02293121934b6a76beae4ebb307cab5abcd68bf9/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml#L16

I can make the contribution but I want to make sure it might be accepted 

Affected product area (please put an X in all that apply)

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
having it reconciled back is not great, but manually specifying the caBundle seems like a pretty bad UX as well. Is there any way we can get it to not be reconciled? 

For example, in Service, the clusterIP is empty in the YAML but set later and its not overwritten

**Comment by etifontaine** [comment]
The `clusterIP` is not defined at all in the file, so Flux won't try to reconciliate it to the default value.
`caBundle` is defined to an empty string, we can try to remove this default key and let the cluster handle the patch.

What to you think ?

**Comment by howardjohn** [comment]
@etifontaine does that work? I would have thought they end up the same once applied to the cluster. If it works seems like a good change

**Comment by etifontaine** [comment]
I have made the test on my cluster, I have remove the `caBundle: ""` from the generated MutatingWebhookConfiguration istio-sidecar-injector-v18 file.

Then, it has been synced with Flux and I got these logs:
```
istiod-v18-dc6fd44c7-vxpw7 discovery 2021-05-25T14:28:25.925604Z	info	Detected a change in CABundle, patching MutatingWebhookConfiguration again

istiod-v18-dc6fd44c7-vxpw7 discovery 2021-05-25T14:28:25.938957Z	info	Patched webhook sidecar-injector.istio.io
```

The new caBundle value is the one that I used to have so everything seems good.

**Comment by caleygoff-invitae** [comment]
thank you for this, I was seeing this in my istiod logs trying to find the source of the issue. I finally arrived on it by seeing the differences in my live environment. Then I went sleuthing around the interwebs and found this issue. Confirming my suspicions I removed `caBundle: ""` from my gitops `MutatingWebhookConfiguration` and fluxv2/kustomization stopped resetting the value after modified by istio! thanks again

**Comment by etifontaine** [comment]
@caleygoff-invitae what version are you using ? It seems the fix has been removed with the 1.11...

**Comment by caleygoff-invitae** [comment]
@etifontaine I am running 1.11.3 where I saw it in, but from what I saw it definitely was still there

**Comment by fatedier** [comment]
> @caleygoff-invitae what version are you using ? It seems the fix has been removed with the 1.11...

What's wrong with this feature? Why the `caBundle: ""` is still there in master branch?  @etifontaine @howardjohn

**Comment by etifontaine** [comment]
Someone seems to have added it back while changing the template location....

**Comment by caleygoff-invitae** [comment]
Hi I am also seeing this on the `ValidatingWebhookConfiguration` for the `istiod-istio-system` and `istio-validator-1-11-4-istio-system` in 1.11.x
