### ISSUE TITLE
servicediscovery delete ip2instance map by ip may lost other port

### ISSUE THREAD

**Issue by andrewshaoyu** [istio/istio#33050]
**Bug description**
https://github.com/istio/istio/blob/02293121934b6a76beae4ebb307cab5abcd68bf9/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L743-L749

https://github.com/istio/istio/blob/02293121934b6a76beae4ebb307cab5abcd68bf9/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L752-L759

Deleting by IP may be wrong, because different workloadentries may use the same IP, associated with different ServiceEntries with different hosts in different namespaces.

when a serviceentry change, `updateExistingInstances` will delete ip2instance by IP, then add ServiceInstance related to this serviceentry, Other ServiceInstance related to different ServiceEntry with same IP may lost.

with this problem ,Virtual Machine can not get port to build inbound cluster

[x] Networking

[x] Virtual Machine

**Expected behavior**
when delete ip2instance,only delete the serviceinstance with specified ServiceEntry

I can add some test cases  and make a pr to fix

**Comment by hzxuzhonghu** [comment]
>because different workloadentries may use the same IP

IMO, this is not right, workloadentry should be like pod, so no two wles can have same ip address. Though we can not prevent this use case, this is not valid.

**Comment by andrewshaoyu** [comment]
not only wles, ServiceEntry has addresses field, different serviceentries with same ip address in different namespace is also invalid ?

**Comment by hzxuzhonghu** [comment]
I think this is not prohibited now, but from namespace and service semantics we should not encourage it.

**Comment by andrewshaoyu** [comment]
now, should this problem  be resolved?

**Comment by su225** [comment]
@hzxuzhonghu - 
> IMO, this is not right, workloadentry should be like pod, so no two wles can have same ip address. 

It is possible for two workloads to have same IP address. But that is a corner case. If they are in different network/L3 domain, it makes sense. In multicluster scenarios, Istio does support it according to [this docs page](IMO, this is not right, workloadentry should be like pod, so no two wles can have same ip address.)

**Comment by ferrarimarco** [comment]
What would be the correct way to design WorkloadEntries to add services running on the same VM to the mesh? Think about a bookinfo instance running on a VM for example. Shall each WorkloadEntry have it's own IP? So the VM itself should have multiple network interfaces...

**Comment by hzxuzhonghu** [comment]
We donot suggest running different services in one vm. For purely defining multi workloadentries, each for one port. It is tricky to handle such abnormal usage.
