### ISSUE TITLE
Configure Istio proxy PILOT_ADDRESS with DNS_NAME

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#33066]
**Describe the feature request**
Can we add a feature to Istio, to allow configuring PILOT_ADDRESS with DNS name instead of IP address? 

My ingress-gateway is exposed as LoadBalancer on private subnets. External-IP is DNS name of my load balancer. 
If I follow the istio.io documentation on how to install Istio on VirtualMachine it doesn't work for people who's on private subnets. I can't map host to host in /etc/hosts file by following the istio.io documentation.  

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

I couldn't find any work arounds, and if it's already supported please point me to right direction.

**Comment by Arsen-Uulu** [comment]
@howardjohn if I provide my DNS as PILOT_ADDRESS then I'm getting an error 
```
failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = 

connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for istiod.istio-system.svc, istiod-remote.istio-system.svc, istio-pilot.istio-system.svc, not <DNS_NAME>"
```
What do I do in that case?

**Comment by howardjohn** [comment]
@Arsen-Uulu you need the certificate signed with the DNS name you are using. The best way is to use a gateway to proxy the traffic (see samples/multicluster/expose-istiod-https.yaml)

There is some hack of setting ISTIOD_CUSTOM_HOST env var in istiod to whatever your dns name you are using is but its not likely to stick around forever

**Comment by Arsen-Uulu** [comment]
@howardjohn so gateway will terminate TLS? Where re-encryption happens again? Little bit confused here.

**Comment by Arsen-Uulu** [comment]
@howardjohn is it possible to provide  PILOT_ADDRESS with protocol? `https://pilot_address:15012`

If I just provide pilot_address:15012, istio is attempting to connect over http, and I get error `connection reset by peer`

**Comment by Arsen-Uulu** [comment]
@howardjohn If TLS termination is happening on the gateway, is pilot every going to see the certificates that I'm trying to authenticate with?
