### ISSUE TITLE
During performance testing sidecar reports HTTP/2" 0 or HTTP/2" 503 response codes on high tps

### ISSUE THREAD

**Issue by soumyadeb-chattopadhyay** [istio/istio#33067]
Continuing the discussion from [During performance testing sidecar reports HTTP/2&quot; 0 or HTTP/2&quot; 503 response codes](https://discuss.istio.io/t/during-performance-testing-sidecar-reports-http-2-0-or-http-2-503-response-codes/10550):

Hello Everyone

On running traffic (5600 tps) over application with istio injection I am getting below error in sidecar container of applications ingress-gateway for http2 inbound requests

It is either response code 503 or response code 0 DC
Most of the requests (~70 %) to ingress gateway @ 5600 tps are failing.

[2021-05-24T15:11:07.888Z] "GET /nnrf-disc/v1/nf-instances?target-nf-type=PCF&requester-nf-type=SMF&requester-nf-instance-fqdn=nsmf-perf-2.smf.5gc.vzimstest.com&supi=imsi-500&snssais=%5B%7B%22sd%22%3A%22dab37d%22%2C%22sst%22%3A100%7D%5D&dnn=dnn-2 HTTP/2" 503 - "-" "-" 0 148 32256 32255 "-" "Go-http-client/2.0" "ae6bd34b-52ef-486b-968c-e49e4cc6ee7f" "ocnrf-ingressgateway.demo1" "127.0.0.1:8081" inbound|80|http2-tcp|ocnrf-ingressgateway.demo1.svc.prowl 127.0.0.1:45586 10.233.118.108:8081 10.233.125.149:50598 - default

[2021-05-24T15:11:07.597Z] "GET /nnrf-disc/v1/nf-instances?target-nf-type=PCF&requester-nf-type=SMF&requester-nf-instance-fqdn=nsmf-perf-14.smf.5gc.vzimstest.com&supi=imsi-500&snssais=%5B%7B%22sd%22%3A%22dab37d%22%2C%22sst%22%3A100%7D%5D&dnn=dnn-2 HTTP/2" 0 DC "-" "-" 0 0 32546 - "-" "Go-http-client/2.0" "2847a65e-de1b-4a80-a274-ab022cde4305" "ocnrf-ingressgateway.demo1" "127.0.0.1:8081" inbound|80|http2-tcp|ocnrf-ingressgateway.demo1.svc.prowl 127.0.0.1:45550 10.233.118.108:8081 10.233.109.162:53646 - default

I tried tweaking below engineering parameters ; but to no avail  :

1. augemented sidecar cpu / memory and concurrency profile under deployment annotations for each backend micro sevices .

sidecar.istio.io/proxyCPU: "4000m"
        sidecar.istio.io/proxyCPULimit: "4000m"
        sidecar.istio.io/proxyMemory: "4Gi"
        sidecar.istio.io/proxyMemoryLimit: "4Gi"
        proxy.istio.io/config: "{concurrency: 8}"

2. Tweaked application's ingress gateway's engineering parameters :slight_smile: 
    maxConnectionsPerDestination: 16
    maxConnectionsPerIp: 16
    connectionTimeout: 60000 #(ms)
    requestTimeout: 60000 #(ms)
    maxRequestsQueuedPerDestination: 5000
    WEBCLIENT_THREAD_QUEUE_CAPACITY 100000
    ingressServer:
    keepAlive:
    enabled: true
    idealTime: 180  #in seconds
    count: 9
    interval: 60 #in seconds

3. Created a destination rule for ingress service
   

    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: ingress-dr
      namespace: demo1
    spec:
      host: ocnrf-ingressgateway.demo1
      trafficPolicy:
        connectionPool:
          tcp:
            maxConnections: 300
            connectTimeout: 60s
            tcpKeepalive:
              time: 180s
              interval: 60s
          http:
            http2MaxRequests: 450000
            maxRequestsPerConnection: 1500
        loadBalancer:
          simple: LEAST_CONN
        tls:
          mode: DISABLE  (kept is disabled intentionally for debugging)

* Latencies were as high as 40s  at 5600 tps and failures due to 503 or 0 http error codes.
* Same application worked on non istio injected setup with latency below 30 ms
* Latency was also low (12 ms) on istio injected setup with traffic rate halved - 2800 tps

![image](https://user-images.githubusercontent.com/11995595/119416803-138cfd00-bd12-11eb-9f99-bfc967983570.png)
Also in the image attahced I see a spile of almost 8k tps ; although I am pumping at 5600 rate in application's incoming http request metrics.
Is it because istio is retrying due to 503 or 0 error codes ?

I do not see such spike with 2800 tps in same istio injected setup . The graph plateaus at  2800 tps.

OCCNE Version: 1.8.x
Aspen Service Mesh : 1.6.14am4
k8s - v1.18.8
Thanks in advance.

**Comment by soumyadeb-chattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/11995595/119416763-ff490000-bd11-11eb-8e50-4ba50fe4d566.png)

**Comment by Smirl** [comment]
I believe I am seeing a similar issue. For me, I was using an old version of istio (1.4.10) and when my applications concurrent connections where higher than `maxRequestsPerConnection` I would see errors. These errors also counted towards outlier detection making the effects worse. However, when testing locally with an istio 1.13.2 I could no reproduce. So this might not be related if you are using a new version.

A fix for us was to remove or increase `maxRequestsPerConnection`. Hope that helps.
