### ISSUE TITLE
TestAgent test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33062]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1396890790558437376#1:build-log.txt%3A26542

Looks like its an old envoy is still bound to 15006 perhaps? Maybe https://github.com/istio/istio/pull/33043 is related?

cc @kyessenov

**Comment by kyessenov** [comment]
Yeah, possible. Is it running with parallelism?

**Comment by howardjohn** [comment]
It does run packages in parallel, so it could be another package conflicting actually. The individual TestAgent cases shouldn't though. There are a couple other tests that bind to 15006 probably

**Comment by kyessenov** [comment]
If it is a port conflict, then the only way I know to systematically solve it is static port allocation. We'd just have to tolerate flakes and hunt them down one by one.

**Comment by kyessenov** [comment]
Actually I'm also not sure where 15006 comes from. The tests I added do not have that port.

**Comment by howardjohn** [comment]
15006 is the inbound listener port, sent over XDS

**Comment by kyessenov** [comment]
Oh, that doesn't matter. It's intentional that it won't bind from two parallel agents. Envoy still runs.
