### ISSUE TITLE
Ingress Gateway returns 503 errors when I down scale a service with a port which does not follow a naming convention

### ISSUE THREAD

**Issue by georgyturevich** [istio/istio#33074]
**Bug description**

Ingress Gateway returns 503 errors in a moment of downscaling a service with a port that does not follow a naming convention (e.g. foo-http).

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**

1. Install Istio Demo profile and Bookinfo application as described on [Getting Started](https://istio.io/latest/docs/setup/getting-started/) page
```
istioctl install --set profile=demo -y
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
```
2. Upscale productpage-v1 deployment
```
date; kubectl scale --replicas=2 deployment productpage-v1; date; 
```
3. Change the port name for productpage Service
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: foo-http
  selector:
    app: productpage
EOF
```
4. Find an IP and port which can be used for accessing. For `kind` I used the following. A cluster name is `istio-demo-test`
WORKER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' istio-demo-test-worker); echo $WORKER_IP
INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}'); echo $INGRESS_PORT
echo http://$WORKER_IP:$INGRESS_PORT/productpage

5. Create a constant load of 30 parallel threads. I did it with my custom Python script, which shows every second amount of requests splited by response code.
```
#!/usr/bin/python

import threading
import urllib.request
from datetime import datetime
from urllib.error import HTTPError

secondsDict = {}
secondsDictLock = threading.RLock()

url = "http://172.254.0.3:31485/productpage"
hdr = {}
N = 30

class RequestThread (threading.Thread):
    def __init__(self, name):
        threading.Thread.__init__(self)
        self.name = name

    def run(self):
        print("Running thread: " + self.name)
        self.print_time()

    def print_time(self):
        while True:
            begin_datetime = datetime.now()
            begin_time = int(datetime.timestamp(begin_datetime))

            with secondsDictLock:
                if begin_time not in secondsDict:
                    secondsDict[begin_time] = {"sent": 0, "received": 0, "printed": 0, "codes_counters": {}}

                secondsDict[begin_time]["sent"] += 1

                if begin_time-1 in secondsDict and secondsDict[begin_time-1]["printed"] != 1 \
                        and secondsDict[begin_time-1]["sent"] == secondsDict[begin_time-1]["received"]:

                    print(datetime.fromtimestamp(begin_time-1).strftime("%H:%M:%S"), secondsDict[begin_time-1]["codes_counters"])
                    secondsDict[begin_time-1]["printed"] = 1

            try:
                req = urllib.request.Request(url, headers=hdr)
                resp = urllib.request.urlopen(req)

                with secondsDictLock:
                    if resp.code not in secondsDict[begin_time]["codes_counters"]:
                        secondsDict[begin_time]["codes_counters"][resp.code] = 0
                    secondsDict[begin_time]["codes_counters"][resp.code] += 1

                    secondsDict[begin_time]["received"] += 1
            except HTTPError as err:
                with secondsDictLock:
                    if err.code not in secondsDict[begin_time]["codes_counters"]:
                        secondsDict[begin_time]["codes_counters"][err.code] = 0
                    secondsDict[begin_time]["codes_counters"][err.code] += 1

                    secondsDict[begin_time]["received"] += 1

                    print(datetime.fromtimestamp(begin_time).strftime("%H:%M:%S"), err.code)

for i in range(0, N):
    thread1 = RequestThread("Thread-" + str(i))
    thread1.start()
```
6. Downscale the service and fetch debug logs. I did it with the following commands
```
IGW1_POD=$(kubectl -n istio-system get pods --no-headers -o custom-columns=":metadata.name" --selector=app=istio-ingressgateway | head -n 1); echo IGW1_POD $IGW1_POD;
istioctl proxy-config -n istio-system log $IGW1_POD --level trace ;
date; kubectl scale --replicas=1 deployment productpage-v1; date; sleep 3;
istioctl proxy-config -n istio-system log $IGW1_POD --level info ;
kubectl -n istio-system logs $IGW1_POD -c istio-proxy --since 60s > $IGW1_POD.log;
```

As a result, my script shows that there are several 503 errors approximately equals to the number of parallel threads in the next second after downscaling.
In logs, I see the following 
```
2021-05-25T12:33:45.187197Z	debug	envoy router	[C9626][S3883408614724272782] upstream reset: reset reason: connection termination, transport failure reason: 
2021-05-25T12:33:45.187276Z	debug	envoy http	[C9626][S3883408614724272782] Sending local reply with details upstream_reset_before_response_started{connection termination}
2021-05-25T12:33:45.187544Z	debug	envoy http	[C9626][S3883408614724272782] closing connection due to connection close header
2021-05-25T12:33:45.187596Z	debug	envoy http	[C9626][S3883408614724272782] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '95'
'content-type', 'text/plain'
'date', 'Tue, 25 May 2021 12:33:44 GMT'
'server', 'istio-envoy'
'connection', 'close'
```

**Expected behavior**

Ingress Gateway should perform retries and do not return 503 errors.

Although, I was aware of a message that returned by `istioctl analyze`
```
Info [IST0118] (Service productpage.default) Port name foo-http (port: 9080, targetPort: 9080) doesn't follow the naming convention of Istio port.
```
I did not pay attention to it as it has just `Info` level and routing/networking, in general, worked as expected.

Possibly there is some Envoy misconfiguration, which prevents performing retries? In VirtualService we define an HTTP route, so I am unsure why port naming convention affects the system here.

If it is expected behavior, then the IST0118 message should be changed to Error, at least.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio
```
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (8 proxies)
```

Kubernetes
```
Client Version: v1.19.7
Server Version: v1.19.7
```

**How was Istio installed?**
I installed it with the help of `istioctl`. I described it in the first reproducing step.

**Environment where the bug was observed (cloud vendor, OS, etc)**

I reproduced it locally with the help of the `kind` tool. Initially, I noticed this behavior on our EKS infrastructure.

Attaching the tarball generated by `istioctl bug-report` [bug-report.tar.gz](https://github.com/istio/istio/files/6539676/bug-report.tar.gz)

**Comment by howardjohn** [comment]
Do you also see the same behavior if you *do* follow the naming conventions?

**Comment by georgyturevich** [comment]
@howardjohn Hello John,

No, I don't. I do not see 503 errors at the downscaling moment when I follow the naming conventions.
