### ISSUE TITLE
High memory usage (OOMs) with enabled (datadog) tracer

### ISSUE THREAD

**Issue by kirecek** [istio/istio#33073]
Hello,

after we enabled Datadog tracer, proxies started to have huge memory usage causing OOMs.

![2021-05-25-111711_644x318_scrot](https://user-images.githubusercontent.com/4215375/119475499-7d76c800-bd4d-11eb-9dfe-d7bc66121f41.png)

_FTR (sampling for this graph is already set to 0.1 but even lower values 0.0x does not work well in env with higher load). The graph shows ingress-gateway usage._

I would expect that proxy would send all in-memory spans to the trace agent after [900ms](https://github.com/envoyproxy/envoy/blob/41c1da44008ea31969dc604c17ab6efd3b9e70a6/source/extensions/tracers/datadog/datadog_tracer_impl.cc#L94) but it just looks like memory is constantly growing (in the graph in 10 min interval) till proxy is OOM killed.

Is it possible to modify this behavior somehow? Or add support for in-memory trace span limit? 

[ x ] Performance and Scalability
[ x ] Extensions and Telemetry

**How was Istio installed?**

IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**

istio version: 1.10.0 (observed also on 1.9.4-5 versions)

**Comment by howardjohn** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
@kirecek just to confirm: the spans were delivered successfully to the backend?

**Comment by kirecek** [comment]
Yes. We were checking also tcp dumps + debug logs and everything seems to be sent correctly to the backend without errors.

If there is something that could help to clarify this problem please let me know.

---

Just for the record, I was wrong with the sampling value (it seems requests override sampling with [priority header](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-datadog-sampling-priority) 🤔  ) but regardless its value, the memory usage is still too high.

**Comment by douglas-reid** [comment]
@kirecek this is likely an envoy issue (not just an Istio issue). Can this be repro'd with a single datadog agent and a single envoy with minimal config in front of an echo server or similar? I don't have a Datadog testbed to experiment with, unfortunately.

**Comment by kirecek** [comment]
> this is likely an envoy issue (not just an Istio issue)

yup, we thought Istio, Envoy, and probably even also issue on datadog cpp tracer as we could not find any buffer limitation there. But wanted to double-check here first.

> Can this be repro'd with a single datadog agent and a single envoy with minimal config in front of an echo server or similar?

Makes sense.  I'll try to prepare some simple reproducible environment and we will see.

Thanks.

**Comment by kirecek** [comment]
@douglas-reid sorry for the late reply.

However, I finally managed to create manifests that should replicate the issue. You can find all information in this repository: https://github.com/kirecek/istio-dd-tracer-test

The repository contains Istio control-plane configuration; dd agent mock deployment; and siege to generate load. Everything should be described in the repo.

BTW since I used GKE env to replicate the issue, I tried also stackdriver tracer where I observed the same memory growth. Are we doing something wrong? 🤔 For now, we had to disable tracing.

Thanks

**Comment by martin-sucha** [comment]
I think the limit is something that needs to be addressed. How can we reopen the issue?

**Comment by Kyslik** [comment]
We seem to suffer from this on Istio `1.11.4`; we too use `*.tracer: datadog`.
<img width="546" alt="Screen Shot 2021-12-16 at 11 55 11" src="https://user-images.githubusercontent.com/2067589/146358939-a8a4219e-f540-48ca-b14c-8b9ecab13ce7.png">

Anything we can help with in order to get this fixed?

**Comment by douglas-reid** [comment]
@Kyslik i don't think we ever progressed beyond the replication stage. any poking around into the leaks would be helpful.
