### ISSUE TITLE
How to upgrade proxy in place gracefully?

### ISSUE THREAD

**Issue by rtttech** [istio/istio#33072]
We need to upgrade running istio-proxy. How can I do that without affecting the running business?

**Comment by su225** [comment]
In case of Kubernetes pods, the image of istio-proxy changes. That means the pod would be restarted. How about creating a deployment with rolling update strategy configuring max unavailable, surge etc. That way, when a namespace is to be pointed to a new revision, you can restart the deployment with `kubectl rollout restart deployment <my-app> -n <my-ns>`. Then Kubernetes takes care of making sure that some pods would be available as part of rolling update strategy. Best part is that if you discover something has gone wrong, you can do `kubectl rollout undo` to rollback to the previous version.

**Comment by yiyouguisu** [comment]
SidecarSet is a good choice.
#28265
