### ISSUE TITLE
Multicluster local headless service

### ISSUE THREAD

**Issue by jmajoor** [istio/istio#33070]
There seems to be 2 conflicting solutions / features being implemented for multi cluster access to headless services.

In https://github.com/istio/istio/pull/32515 there is a special feature that would enable this.
However if you enable dns-proxy (using ISTIO_META_DNS_CAPTURE=true) then headless services are already accessible across clusters (though maybe that was unintended). 
There is also a discussion on what the default behavior should be.

I actually want the opposite. I want my headless service to resolve locally in the cluster, but I do also want dns-proxy for other services.

I have a set of stateful services and deploy them in 2 different regions (multi cluster, same network using peering).
By having the services in the same namespace in each region I get load balancing and failover across regions (which is what I want).
I also need direct cross region communication. I simply create an east service in the east and a west service in the west. With dns-proxy east and west can directly communicate through these services.

Unfortunately, now the communication of the headless services are not determined as it depends on how the dns-proxy resolved the duplicate names in the headless service (as each region will populate this from a statefulset). The result is that I can have pods in the east using a headless service ending up communicated with a pod in the west and I want to absolutely avoid that (for access through the headless service).

Is it possible to enforce that headless service communication remains local to the cluster?

**Comment by howardjohn** [comment]
cc @stevenctl

**Comment by hzxuzhonghu** [comment]
>I want my headless service to resolve locally in the cluster, 

Suppose you mean your client want to access headless service instances within same region(same cluster). This can be done via declaring another service and make use of the locality load balancing.

It is not possible to do failover if you are using headless service, and it can be only resolved to local cluster pod ip.

**Comment by jmajoor** [comment]
My pods in the statefulset need to be able to directly communicate to pod-0 of the statefulset. This is done through the headless service using the pod-0.<headless service>.<namespace> dns name. Each cluster / region will have such a pod and with dns-proxy enabled it is not guaranteed to stay within the region/cluster. So my pod-1 in one cluster may communicate with pod-0 in another cluster and I want to avoid that.

**Comment by hzxuzhonghu** [comment]
If pods do not communicate with other clusters, how do they sync up?

**Comment by howardjohn** [comment]
> Each cluster / region will have such a pod and with dns-proxy enabled it is not guaranteed to stay within the region/cluster. So my pod-1 in one cluster may communicate with pod-0 in another cluster and I want to avoid that.

This is not quite right I think. There are two DNS names:
* `pod-{n}.headless.ns.svc.cluster.local`. This resolves to a single IP. It will always resolve to the local cluster if available.
* `headless.ns.svc.cluster.local`. This resolves all IPs in all clusters.

I think you are saying the `pod-{n}` is not resolving to the same cluster? This *should* not happen https://github.com/istio/istio/blob/7cc1bb6eb59faa36b73cb64e40d50b588c1153e2/pilot/pkg/networking/core/v1alpha3/name_table.go#L101

**Comment by jmajoor** [comment]
Both the dns-proxy and #32515 are moving istio into the direction of multicluster headless services and I can see the benefits of them. However these features are changing the existing behavior and applications may rely on the fact that headless services were not multicluster before.

I tried using destination rules, but with dns-proxy enabled I get cross cluster communication regardless.
Is there a new feature needed, such as an annotation on a headless service, to guarantee local cluster resolution?
Or is there another way to make sure that I don't get cross cluster communication for my headless service?

**Comment by stevenctl** [comment]
cc @nmittler – DNS is pretty much a service discovery mechanism in this case, we should probably apply the different discoverability settings here as well (ServiceExport, cluster-local service setting).
