### ISSUE TITLE
Galley v1: Design mapping of public/internal CRDs for Istio components.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#3307]
We need to identify the right mapping from a public set of CRDs to an internal set for the initial cut of Galley v1 (See https://github.com/istio/istio/issues/2082 for general info).

Today, the public CRDs are using the config.istio.io API Group. Soon, they will move to their individual API Groups.
ref: https://github.com/istio/istio/pull/3214

Ideally, the mapping would be simple enough so that we can implement it in Mixer and Pilot with minimal disruption, ideally behind a flag.

**Comment by xiaolanz** [comment]
- [ ] Design mapping

- [ ] Pilot change to allow different api group version

- [ ] Mixer change to allow different api group version

- [ ]  Broker change to allow different api group version
