### ISSUE TITLE
Galley v1: Ensure that MCP based config distribution is controlled via a Helm flag

### ISSUE THREAD

**Issue by ozevren** [istio/istio#3308]
It is very likely that Galley will be in Alpha phase when Istio v1 ships. As such, the users should be able to opt-in to using Galley using a (standardized?) Istio mechanism.

(See https://github.com/istio/istio/issues/2082 for more general info).

**Comment by ayj** [comment]
We probably ought to have standardized support for feature gates across Istio. Baking this into istioct/helm install is one option. Finer granularity may require flag support at the component level. An option to selectively enable/disable API groups may also be desirable.

refs

https://kubernetes.io/docs/reference/feature-gates/
https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#turn-on-or-off-an-api-version-for-your-cluster
