### ISSUE TITLE
watch too many duplicate events , pilot may be oom

### ISSUE THREAD

**Issue by andrewshaoyu** [istio/istio#33109]
**Bug description**
https://github.com/istio/istio/blob/ee0efe9dd8d280be216cf743bb95b4a724154bda/pilot/pkg/config/kube/crdclient/cache_handler.go#L88-L94

now pilot put hanlder function in queue. if updating istio resource is faster than consumer. pilot's memory will increase, than over memory limit, be killed by oom_killer

[x] Networking
[x] Performance and Scalability

**Expected behavior**
use k8s workqueue instead of queue, put types.namespacedName instead of handler function in workqueue.
duplicate event from the same resource should be ignore.

I already have a pr to fix , but need to do more tests.

Now we can talk about it

**Comment by hzxuzhonghu** [comment]
Good catch, the mechanism currently has two limitations:

1. Only one thread is running, when a big bunch of resource events comes, it is very slow.
2. duplicate items may exist in the same queue, we should handle the last event with eventual consistent model

**Comment by andrewshaoyu** [comment]
I think the two steps order should be exchanged.
Using more workers to consumer, wokerqueue is very necessary. During handler event, workers should not share any locks,if duplicate event exists in same queue, lock is absolutely necessary

**Comment by howardjohn** [comment]
Is this hypothetical or have you seen this occur?

**Comment by hzxuzhonghu** [comment]
Not hypothetical @andrewshaoyu from Ctrip(https://www.ctrip.com/) has met this and fixed it in their product

**Comment by andrewshaoyu** [comment]
Not fixed yet, testing

two scenarios:
1. we have met when k8s apiserver is not stable, after started,pilot connect to apiserver,but apiserver down soon for many times. then pilot oom
1. update istio resource quickly, so we need to more workers to consume event

**Comment by hzxuzhonghu** [comment]
This can happen when client-go relist all the resources from kube-apiserever, say when  we have 100k pods + svc, after pilot restarted, with single thread handling, the queue can be super accumulative.

**Comment by hzxuzhonghu** [comment]
Either network issue or restart or resources update frequently can cause this.

**Comment by howardjohn** [comment]
I am a bit unclear how this triggers a problem.y understanding is the queue is storing pointers to the objects, not the full objects themselves. Additionally, the event handler is basically instant, it just sends on some channel basically, so I except it to be able to handle millions of updates per second.

I am not saying it cannot happen, but I would like to understand more where the issue can occur

**Comment by andrewshaoyu** [comment]
We have there kubernetes apiservers. some day because of network error, all kubelet connections that connected to apiserver was broken. then all kubelet reconnection to apiservers. Now some kube apiservers were  overloaded and  may be down. some istio-pilot‘s connections were also broken. The failed clients(kubelet and istio-pilot) try to connect apiserver again. istio pilot will get a lot of resources. It is a retry storm. so istio pilot connected to apiservers many times and memory keep increasing then oom happened.

**Comment by howardjohn** [comment]
If api-server is down, how is pilot getting a lot of resources? is it relisting all objects but  getting partial updates, then relisting all of them again repeatedly?

Even if api-server somehow returned 1 billion objects, I don't see how the queue makes things worse because (1) they are just pointers stored on the queue and (2) we handle events ~instantly.

It would be good to see some profiles or way to reproduce this
