### ISSUE TITLE
[proxyv2-distroless] Update OpenSSL and Install Security Patch DLA-2563-1 and DLA-2492-1

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#33104]
**Describe the feature request**
Vulnerability scanning on istio proxyv2:1.10.0-distroless indicates there are two security patches pending install on package OpenSSL: DLA-2563-1 and DLA-2492-1. Can you upgrade OpenSSL on this image to 1.1.0l-1~deb9u2 to resolve this issue?

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This is tracked in https://github.com/istio/istio/issues/29326, thanks for the report.
