### ISSUE TITLE
LUA filter inline httpCall() buffers original request body,

### ISSUE THREAD

**Issue by sumitaneja** [istio/istio#33117]
In lua filter we are making a httpCall to another service. This is simple post call with no response body
But get 413 too large error if original request size is > 1MB

Seems before making http call, it streams and buffers original request body.

not clear why original request body is buffered when there was no call to body()

**Comment by sumitaneja** [comment]
Simplified view of lua script part of envoy Lua filter.

applyTo: HTTP_FILTER
match:
context: SIDECAR_OUTBOUND
patch:
operation: INSERT_BEFORE
value:
name: envoy.lua
typed_config:
'@type': type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
inlineCode: |
function envoy_on_request(request_handle)
local p = request_handle:headers():get(":path")
local rlHeaders = {}
local sid = request_handle:headers():get("someheader")
local ridOr = request_handle:headers():get("someHedaer")
local rid = string.gsub(ridOr, "/", "%%2F")
local rlkey = sid .. "/" .. rid
rlHeaders[":method"] = "PUT"
rlHeaders[":path"] = "/someURL/" .. rlkey
rlHeaders[":authority"] = "cluster.svc.cluster.local"
local headers, body = request_handle:httpCall(
"lua_cluster",
rlHeaders,
nil,
5000)
end
When i make request with payload size >1mb it fails with 413 too large error. Using istio 1.6

**Comment by sumitaneja** [comment]
Envoy version
12cfbda324320f99e0e39d7c393109fcd824591f/1.14.1/Clean/RELEASE/BoringSSL

**Comment by xmapst** [comment]
@sumitaneja Hello, I have also encountered this situation, how did you solve it

**Comment by sumitaneja** [comment]
@xmpast this was enoy problem. see https://github.com/envoyproxy/envoy/issues/16674

 proper solution for me was to use wasm.
workaround could be red and discard body chunks. before http call.

**Comment by xmapst** [comment]
> @xmapst this was enoy problem. see [envoyproxy/envoy#16674](https://github.com/envoyproxy/envoy/issues/16674)
> 
> proper solution for me was to use wasm. workaround could be read and discard body chunks before http call.

thanks for sharing
