### ISSUE TITLE
Proper way of handling connections to an external Microsoft SQL VM cluster

### ISSUE THREAD

**Issue by noahjd** [istio/istio#33119]
Hello,

I have some dotnet core microservices running in my kubernetes cluster (1.19.1), they are all running the istio sidecar proxy (1.9.1), and I am seeing some flaky connection behavior when making calls to the microservice which connects to the external SQL cluster. If I look at the sidecar logs I can see this when the connection failure happens:

istio sidecar log:
```
[2021-05-26T15:00:04.585Z] "- - -" 0 UF,URX - - "-" 0 0 9909 - "-" "-" "-" "-" "11.11.11.11:1433" PassthroughCluster - 11.11.11.11:1433 100.96.13.10:51662 - -
[2021-05-26T15:00:04.585Z] "- - -" 0 UF,URX - - "-" 0 0 9910 - "-" "-" "-" "-" "22.22.22.22:1433" PassthroughCluster - 22.22.22.22:1433 100.96.13.10:59498 - -
[2021-05-26T15:00:04.491Z] "- - -" 0 UF,URX - - "-" 0 0 10003 - "-" "-" "-" "-" "22.22.22.22:1433" PassthroughCluster - 22.22.22.22:1433 100.96.13.10:59484 - -
[2021-05-26T15:00:04.491Z] "- - -" 0 UF,URX - - "-" 0 0 10003 - "-" "-" "-" "-" "33.33.33.33:1433" PassthroughCluster - 33.33.33.33:1433 100.96.13.10:51648 - -
[2021-05-26T15:00:04.491Z] "- - -" 0 UF,URX - - "-" 0 0 10003 - "-" "-" "-" "-" "44.44.44.44:1433" PassthroughCluster - 44.44.44.44:1433 100.96.13.10:58482 - -
[2021-05-26T15:00:04.585Z] "- - -" 0 UF,URX - - "-" 0 0 10001 - "-" "-" "-" "-" "44.44.44.44:1433" PassthroughCluster - 44.44.44.44:1433 100.96.13.10:58496 - -

```
================================
app log exception:

```
Unhandled exception: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
```

Note on the SQL cluster: in the app config we are using a DNS name for the availability group listener e.g. ag_listener.mydomain.com to point to the HA SQL cluster.

This is all working in our nonprod with no issues, we are also running istio there, though we are running only a single sql instance in nonprod.

Currently, I made sure to set the outboundTrafficPolicy to ALLOW_ANY but I am still seeing this flaky connection behavior. It doesn't happen all the time but it's just highly inconsistent. It's been a real pain for my team trying to resolve this. Is there a proper method on istio for handling connections to a mssql db cluster with multiple IPs? thank you

**Comment by noahjd** [comment]
Also I forgot to mention, below is a serviceentry that I tried to use, with no success:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: prod-sql-service-entry
spec:
  addresses:
  - 11.11.11.11/32
  - 22.22.22.22/32
  - 33.33.33.33/32
  - 44.44.44.44/32
  hosts:
  - '*.mydomain.com'
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 1433
    protocol: TCP
```

**Comment by noahjd** [comment]
Hi @nmittler 

We tried the holdApplicationUntilProxyStarts and it did not work, we still were seeing the connection issues shortly after testing the api pod when it came up. For the TCP idle timeouts, is there a particular setting to check on the Istio side to see what those values are? I can ask the dba team if they have some idle timeouts on their end. Appreciate the help!

**Comment by jbilliau-rcd** [comment]
@noahjd  did you ever figure this out? We are having the EXACT same issue; only way we can get the app to work is to bypass Istio entirely on egress by adding this annotation to our deployment: `traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.204.0.0/16`

**Comment by noahjd** [comment]
> @noahjd did you ever figure this out? We are having the EXACT same issue; only way we can get the app to work is to bypass Istio entirely on egress by adding this annotation to our deployment: `traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.204.0.0/16`

Never did figure this out. I just remember we had to disable to side-car entirely for all services with an Mssql backend. The side car proxy is the problem, it interrupts connections going out.

**Comment by jbilliau-rcd** [comment]
Yep, after spending 4 hours on it, we did exactly the same. Sucks that's the solution, but I guess for now it is what it is.

**Comment by jordanjennings** [comment]
I was seeing this same issue and didn't suspect Istio as the problem for several days because when you configure the application to use a single instance rather than the availability group listener DNS name it works fine. Also if you configure the application to use the primary DB node's availability group listener IP directly it works without issue. It's not clear to me why the behavior at the istio-proxy level changes when the application tries to connect to multiple IPs, but it appears that it does.

Ended up going with `traffic.sidecar.istio.io/excludeOutboundPorts: 1433` to avoid having to manage different CIDRs across different environments.
