### ISSUE TITLE
Istio for windows nodes and pods

### ISSUE THREAD

**Issue by grzebis1** [istio/istio#33130]
Now that Envoy supports windows in v1.18.3 when will istio support windows pods? 

[X] Docs
[X] Installation
[X] Networking
[X] Performance and Scalability
[X] Extensions and Telemetry
[X] Security
[X] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Comment by howardjohn** [comment]
Thanks for the interest. There is a lot of effort beyond just envoy support, see tracking here: https://github.com/istio/istio/issues/27893. Thanks!
