### ISSUE TITLE
Add source_container label to merged metrics

### ISSUE THREAD

**Issue by stevehipwell** [istio/istio#33141]
**Describe the feature request**

I'd like the _Istio_ proxy to add a `source_container` (or equivalent) label to all metrics merged and exposed so these metrics can be re-labelled back to the original state before they were merged.

With [Metrics merging](https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging) all of the metrics show up as coming from the `istio-proxy` container which makes using these metrics un-intuitive and goes against the principal that the use of _Istio_ shouldn't cause behavioural changes. This simple change would allow this issue to be easily resolved.

**Describe alternatives you've considered**

As data is lost during the metrics merge there is currently no solution.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Depending on the complexity of the metrics merging code I'd be happy to take a look at opening a PR to do this?

**Comment by howardjohn** [comment]
Perhaps a dumb question, but where does `istio-proxy` come from? How can prometheus know which container is exposing the metric?

**Comment by howardjohn** [comment]
How can does prometheus know though? Doesn't it just hit a ip:port? 

Does it read containerPort maybe and attempt (guess - its not always accurate) to decide from that?

**Comment by stevehipwell** [comment]
We're running the Prometheus Operator which I believe is making use of the K8s metadata, see `__meta_kubernetes_pod_container_name` in the [Prometheus config docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config/) (we're using a `PodMonitor` to capture the metrics but this is just an implementation detail). Adding a `source_container` label would allow us to re-label our metrics back to what they'd be if we weren't using metrics merging.

**Comment by stevehipwell** [comment]
FYI a related issue (https://github.com/istio/istio/issues/27940) and link to the [PodMonitor](https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/extras/prometheus-operator.yaml).

**Comment by douglas-reid** [comment]
Let's add this to the agenda for the next E&T. `source_container` is potentially problematic (overloaded `source`, particularly with the istio standard metrics; potential confusion over the proxy as being a "visible" thing at the service metrics level). I'm also a bit worried about the blanket adding of dimensions to workload metrics (though prometheus k8s service discovery does not have the same concerns). Part of this issue description is concern over Istio impact behavior, and this would patch that with yet another behavioral change. 

@stevehipwell would this be a situation in which we might be better served by turning off metrics merging?  and in that case, provide operator-friendly mTLS configuration?

**Comment by howardjohn** [comment]
Even if our code emits the label, would it resolve the problem. If the
relabelling has conflict does it overwrite? And for configs that do *not*
add source_container now we are adding it. We also cannot actually
accurately add it, because it is ~impossible to accurately know which
container is serving a port.

**Comment by stevehipwell** [comment]
@douglas-reid `source-container` was just an example, the example Istio PodMonitor could be updated to show how to relabel container and clean up the extra label. @howardjohn we're talking about a best effort addition of a single label that can be dropped at scrape after being used to re-label; the current container label is 100% incorrect for all merged metrics so it's a step forwards. 

An alternative to metrics merging that's drop in compatible to an existing Prometheus Operator install would also work; last time I checked there wasn't an easy way to do this with mTLS set to strict.

Personally I'd like to see both approaches; better merged metrics for the short term and better mTLS strict integration with Prometheus Operator (or standard Prometheus) in the medium/long term.

**Comment by bianpengyuan** [comment]
> An alternative to metrics merging that's drop in compatible to an existing Prometheus Operator install would also work; last time I checked there wasn't an easy way to do this with mTLS set to strict.

FWIW, prom should be able to scrape the app container directly with strict mTLS. https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings What are the problem you run into?

**Comment by stevehipwell** [comment]
@bianpengyuan that would require a change to Prometheus which isn't desired. External systems and workloads should be oblivious to Istio.

Labeling would be a simple solution using what's already there. A better solution would be a configuration flag to expose metrics endpoints without mTLS instead of merging them onto a single non mTLS endpoint.

**Comment by bianpengyuan** [comment]
> @bianpengyuan that would require a change to Prometheus which isn't desired. External systems and workloads should be oblivious to Istio.

Yeah, I agree it is not ideal, but this solution is tested and supported by Istio, and the change is relatively small and non-intrusive (it is just adding a container, which provisions and refreshes cert in prom pod). So IMHO it is an acceptable cost.

**Comment by stevehipwell** [comment]
@bianpengyuan it's a pretty big change from a platform perspective where Istio isn't on all clusters and installing Istio shouldn't cause any lower level layers to change. Having to modify Prometheus for Istio seems like an architectural smell to me.

**Comment by douglas-reid** [comment]
@stevehipwell are your metrics served on the same port as the rest of your application?

**Comment by stevehipwell** [comment]
@douglas-reid we currently have no restrictions on how applications expose their metrics. Only supporting metrics on dedicated ports would be something we could do.

**Comment by douglas-reid** [comment]
@stevehipwell ok. until we sort out an approach to address mTLS with the operator or otherwise, is using the annotation `traffic.sidecar.istio.io/excludeInboundPorts` for your app metrics port something that you would consider in conjunction with turning off metrics merging?

**Comment by stevehipwell** [comment]
@douglas-reid thanks I don't think I came across that annotation when I did the work to get Istio and Prometheus Operator integrated. If it does what it looks like it does, then it's probably a better solution for us than the merging.

**Comment by douglas-reid** [comment]
@stevehipwell ok. i think there are (were?) some gotchas, like maybe having to set `traffic.sidecar.istio.io/excludeInboundPorts` to `*` (@howardjohn is that still a thing?), but i'll be curious to know how that works for you.

**Comment by stevehipwell** [comment]
@douglas-reid having to allow all inbound traffic would be a deal breaker here; we use mTLS specifically to require all service to service communication is encrypted.

**Comment by douglas-reid** [comment]
@stevehipwell that was a type. it should be `includeInboundPorts: *`, iirc. I _think_ overridding the exclusions required everything to first be included. i'm not sure that restriction still applies.

**Comment by stevehipwell** [comment]
@douglas-reid @howardjohn I'm about to pick back up this work and am interested if there is a definitive answer on the correct annotations to use?

**Comment by douglas-reid** [comment]
I haven't done any further investigation. I still think `excludeInboundPorts` is probably the right way to go, but I haven't tried this at all (and I'm not familiar enough with the annotations subsystem to know the gotchas).
