### ISSUE TITLE
Sidecar in VM fails to start due to "failed to warm certificate: failed to generate workload certificate: create certificate"

### ISSUE THREAD

**Issue by liorokman** [istio/istio#33146]
**Bug description**

   I installed the Istio sidecar into a virtual machine, as specified [in the documentation](https://istio.io/latest/docs/setup/install/virtual-machine/). 

   The virtual machine connected successfully for 1 day, and on the next day, the envoy log on the VM started filling up with the following errors:

```
2021-05-27T10:28:07.342344Z     warn    ca      ca request failed, starting attempt 1 in 91.589072ms
2021-05-27T10:28:07.434806Z     warn    ca      ca request failed, starting attempt 2 in 203.792343ms
2021-05-27T10:28:07.639557Z     warn    ca      ca request failed, starting attempt 3 in 364.729652ms
2021-05-27T10:28:08.005300Z     warn    ca      ca request failed, starting attempt 4 in 830.723933ms
2021-05-27T10:28:08.836493Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection closed
```

The VM was up and running the entire time, except that I periodically (for various tests) restarted the istio service on the VM using `systemctl`.

I don't know if this is relevant, but during this time period, the Kubernetes cluster running Istio was hibernated, and Istio was only restarted after the certificate in `/etc/certs/cert-bundle.pem` had already expired.

At this point restarting the istio service using `systemctl` on the VM did not fix the problem.

I was able to get the environment working only by manually deleting (as root) the `/etc/certs/key.pem` and `/etc/certs/cert-chain.pem` files. Once these files were deleted, the next time I restarted the istio service using `systemctl` everything connected correctly.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The envoy process on the VM should successfully connect to the pilot-agent and retrieve certificates. If there is an existing `cert-chain.pem`  that is not valid, it should be ignored and the sidecar should behave as if this file did not exist.

**Steps to reproduce the bug**

Connect a virtual machine sidecar so that the virtual machine sidecar retrieves a certificate into `/etc/certs/cert-chain.pem`, and make Istio unavailable at the point in time when the sidecar certificate needs to be rotated, so that the sidecar certificate expires without being rotated.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (7 proxies)

$ kubectl version --short
Client Version: v1.16.4
Server Version: v1.20.6
```

**How was Istio installed?**

As per the instructions in https://istio.io/latest/docs/setup/install/virtual-machine/ for a multi-network installation, with auto-registration  enabled.

**Environment where the bug was observed (cloud vendor, OS, etc)**

The Cloud Vendor is GCP, the Kubernetes cluster is a [Gardener](https://gardener.cloud/) managed cluster.

The VM is a Debian VM running on GCP.
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# dpkg --list istio-sidecar
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  istio-sidecar  1.10.0       amd64        Istio Sidecar

```

**Comment by liminw** [comment]
It sounds like we did not handle expired certificate correctly? The expected behavior is, 
1. if certificate exists and valid, use the cert to get a new cert. 
2. if certificate exists but not valid (expired), use the token to get a new cert.
3. If certificate does not exist, use token to get a new cert. 
Looks like we handle 1 and 3, but not 2?

**Comment by liminw** [comment]
cc. @williamaronli

**Comment by liorokman** [comment]
One more observation; I had to delete both the `cert-chain.pem` and `key.pem` files. It's not enough to just delete the `cert-chain.pem` - I think the code assumes that if a `key.pem` exists then there's a valid certificate, even if the `cert-chain.pem` file is gone.

**Comment by williamaronli** [comment]
currently if it meets a certificate exists but not valid we directly return an error. So we should check either the token or cert when rotating the cert

**Comment by williamaronli** [comment]
@liorokman this fix should resolve the issue

**Comment by danehans** [comment]
@williamaronli I am hitting this issue doing a v1.8.4 > v1.9.7 upgrade. Will #33813 get backported to 1.9?

**Comment by williamaronli** [comment]
it will be merged the the latest version of istio

**Comment by shashankram** [comment]
I recently observed the same issue with latest builds where despite a valid istio-token being present on the VM, Istio would try to use the expired cert. I had to delete cert-chain.pem and key.pem for pilot-agent to refresh the certs.

**Comment by ramprasathasokan** [comment]
In v1.15.x, I faced the same issue with v1.15.7 however downgrading to v1.15.6 resolved it.
