### ISSUE TITLE
The istio application directly accesses the pod IP of the grpc protocol and reports an error. What should I do to solve the NPE?

### ISSUE THREAD

**Issue by yingjianjian** [istio/istio#33186]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
The istio application directly accesses the pod IP of the grpc protocol and reports an error. What should I do to solve the NPE?
`{
  "start_time": "2021-05-29T13:37:34.624Z",
  "request_id": "-",
  "method": "-",
  "upstream_host": "-",
  "x_forwarded_for": "-",
  "bytes_sent": "0",
  "upstream_cluster": "-",
  "downstream_remote_address": "10.11.3.87:35640",
  "path": "-",
  "authority": "-",
  "protocol": "HTTP/2",
  "upstream_service_time": "-",
  "upstream_local_address": "-",
  "duration": "0",
  "downstream_local_address": "10.11.4.231:8080",
  "upstream_transport_failure_reason": "-",
  "response_code": "0",
  "response_flags": "DPE",
  "requested_server_name": "-",
  "bytes_received": "0",
  "istio_policy_status": "-",
  "trace_id": "-",
  "route_name": "-",
  "user_agent": "-"
}`

Istio only knows the protocol of service. How to specify the protocol of direct access to pod IP?

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version - 1.6.8
**How was Istio installed?**
istioctl 
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Do you have strict mtls or something? I am guessing because you send to the pod IP directly we are not applying mTLS (which is expected, Istio works on Services) and then its getting TLS on the server side which is unexpected

**Comment by yingjianjian** [comment]
Yes, so if so, only grpc port can be released
