### ISSUE TITLE
systemctl stop istio - don't stop envoy.

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#33182]
**Bug description**
When trying to stop Istio with `systemctl stop istio`, command only stops pilot-agent, not envoy. 

ps aux | grep istio 

```
istio-p+ 11513  0.3  0.7 203796 60820 ?        Sl   16:16   0:21 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --service-cluster istio-proxy --service-node sidecar~vm.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3--disable-hot-restart --log-format %Y-%m-%dT%T.%fZ?%l?envoy %n?%v -l warning --component-log-level misc:error --concurrency 2
```

when trying to bring Istio back up with `systemctl start istio` it fails to start because there is envoy proxy is still running

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
systemctl stop istio - suppose to stop all processes related to Istio, pilot-agent proxy, envoy.

**Steps to reproduce the bug**
After installing Istio on Amazon ec2 linux 2 ,  please try to stop istio with systemctl command and check for any processes running for istio.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio version - 1.10.0

**How was Istio installed?**
rpm -i istio-sidecar.rpm 

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWSm EC2( Amazon Linux 2)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
Can you test with patch #33043

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  How do I build the rpm with this patch?

**Comment by hzxuzhonghu** [comment]
I am not familiar with how rpm is built. I can tell you to build a new go binary and replace the older one.

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  I need to build pkg/envoy binary correct?

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  how do I build the binary?

**Comment by hzxuzhonghu** [comment]
run `make build`

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  this patch [#33043](https://github.com/istio/istio/pull/33043) didn't fix. envoy is still running even if pilot-agent is stopped

**Comment by Arsen-Uulu** [comment]
/usr/lib/systemd/system/istio.service
```
[Unit]
Description=istio-sidecar: The Istio sidecar
Documentation=http://istio.io/

[Service]
ExecStart=/usr/local/bin/istio-start.sh
ExecStopPost=/usr/local/bin/istio-start.sh clean
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
```
why it's missing the ExecStop?

**Comment by hzxuzhonghu** [comment]
cc @silenceshell Can you investigate?

**Comment by silenceshell** [comment]
@Arsen-Uulu 
Both #33043 and #33040 are needed to enabled in your environment.
The PR #33040 fix the bug that `su` just wait for 2 seconds for the pilot-agent process to exit, however the pilot-agent will [wait for 5 seconds(by default) for the envoy process to drain](https://github.com/istio/istio/blob/master/pkg/envoy/agent.go#L109). So you could try to update the `tools/packaging/common/istio-start.sh` according to PR #33040 to use `sudo` instead of `su`, as `sudo` will wait until the pilot-agent for exit after 5 seconds.

But just PR #33040 is not enough, you need  #33043 to help pilot-agent to wait for the envoy process to exit. If you test on istio 1.10 branch, the pilot-agent [send errAbort to abortCh](https://github.com/istio/istio/blob/master/pkg/envoy/agent.go#L111) and exit immediately, so the envoy process may have no change to receive the kill signal.
If you only enabled #33043 , the `su` will send SIGKILL to pilot-agent, thus the pilot-agent will have no chance to send SIGTERM to envoy.

Try to enable both PRs.

And `ExecStop` is not a MUST in systemd, if it is ignored, systemd will send SIGTERM to the service by default.

**Comment by Arsen-Uulu** [comment]
@silenceshell Yes use those 2 fixes, fixed the issue now. It wasn't clear because those pr's are not linked

**Comment by silenceshell** [comment]
> @silenceshell Yes use those 2 fixes, fixed the issue now. It wasn't clear because those pr's are not linked

Nice advice!
Maybe we could close this issue?

**Comment by Arsen-Uulu** [comment]
@silenceshell Thank you for your help 

Can you help with this? 

When a pilot-agent connects to ControlPlane(Istiod), does it generate workload certificates on every restart? 

Because everytime I restart istio-agent I see that it generates new workload certificates with the SECRET_TLL I provide.

**Comment by Arsen-Uulu** [comment]
@silenceshell  I just created new instance,and following exac same steps from working instance. 

Proxy is not being killed 

```
2021-06-16T17:51:31.295149Z	info	Agent draining Proxy
2021-06-16T17:51:31.295173Z	info	Status server has successfully terminated
2021-06-16T17:51:31.296647Z	error	accept tcp [::]:15020: use of closed network connection
2021-06-16T17:51:31.297291Z	info	Graceful termination period is 5s, starting...
2021-06-16T17:51:36.297485Z	info	Graceful termination period complete, terminating remaining proxies.
2021-06-16T17:51:36.297541Z	warn	Aborted all epochs
2021-06-16T17:51:36.297549Z	info	Agent has successfully terminated
```
```
ps aux | grep istio
istio-p+ 11406  0.6  0.7 226696 59396 ?        Sl   17:50   0:00 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --service-cluster istio-proxy --service-node --local-address-ip-version v4 --bootstrap-version 3 --disable-hot-restart --log-format %Y-%m-%dT%T.%fZ?%l?envoy %n?%v -l debug --component-log-level misc:debug --concurrency 2
```
```
/usr/local/bin/istio-start.sh
exec sudo -E -u ${EXEC_USER} -s /bin/bash -c "INSTANCE_IP=${ISTIO_SVC_IP} POD_NAME=${POD_NAME} POD_NAMESPACE=${NS} exec ${ISTIO_BIN_BASE}/pilot-agent proxy ${ISTIO_AGENT_FLAGS_ARRAY[*]} 2> ${ISTIO_LOG_DIR}/istio.err.log > ${ISTIO_LOG_DIR}/istio.log"
fi
```
envoy binary is from [patch](https://github.com/istio/istio/pull/33043)

**Comment by silenceshell** [comment]
#33043 needs update pilot-agent, not envoy. Try to update the pilot-agent binary :)

**Comment by silenceshell** [comment]
> @silenceshell Thank you for your help
> 
> Can you help with this?
> 
> When a pilot-agent connects to ControlPlane(Istiod), does it generate workload certificates on every restart? 
> 
> Because everytime I restart istio-agent I see that it generates new workload certificates with the SECRET_TLL I provide.

Maybe it is better to create a new issue to track this? It seems like a new situation.
