### ISSUE TITLE
Issue with HTTP communication from Prometheus to Alertmanager

### ISSUE THREAD

**Issue by guusvw** [istio/istio#33188]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Since the upgrade from Istio 1.7 to 1.8 we're seeing issues with specially the communication from our Prometheus to our Alertmanager (pushing alarms via HTTP).

Error message:

```
level=error ts=2021-05-31T07:16:45.210Z caller=notifier.go:527 component=notifier alertmanager=http://100.96.9.151:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"
```

Both, Prometheus & Alertmanager are installed via the `prometheus-operator` and therefore two headless Kubernetes Service exist called `prometheus-operated` & `alertmanager-operated`, those services are hard-coded into the `prometheus-operator` and can not be changed.
Next to it each "installation" of those two components has an own service, which is not headless and under full-control by us. (`alertmanager-main` & `prometheus-k8s`)

One thing we tried and also worked is to down scale the `prometheus-operator` to 0 and add the `appProtocol` tags on the `-operated` Kubernetes services with the value `http` which worked, but is overwritten, as long as the operator is not scaled to zero.

If we're setting the `appProtocol` on the by us controlled service, it is not working out.

Any clue how to to fix it?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure
[ X ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio version:

```
➜ istioctl version --remote
client version: 1.10.0
control plane version: 1.8.5
data plane version: 1.8.5 (78 proxies)
```

Kubernetes version:

```
➜ kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.10
```

**How was Istio installed?**

via the `istio-operator` also in version `1.8.5`

**Environment where the bug was observed (cloud vendor, OS, etc)**

Running on a `kOps` cluster on AWS.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by guusvw** [comment]
[Uploading bug-report.tar.gz…]()

**Comment by howardjohn** [comment]
I think the issue is that the command is matching the `alertmanager-operated.monitoring.svc.cluster.local:9093` route, which has domains:
```
  virtualHosts:
  - domains:
    - alertmanager-operated.monitoring.svc.cluster.local
    - alertmanager-operated.monitoring.svc.cluster.local:9093
    - alertmanager-operated
    - alertmanager-operated:9093
    - alertmanager-operated.monitoring.svc.cluster
    - alertmanager-operated.monitoring.svc.cluster:9093
    - alertmanager-operated.monitoring.svc
    - alertmanager-operated.monitoring.svc:9093
    - alertmanager-operated.monitoring
    - alertmanager-operated.monitoring:9093
    - '*.alertmanager-operated.monitoring.svc.cluster.local'
    - '*.alertmanager-operated.monitoring.svc.cluster.local:9093'
    - '*.alertmanager-operated'
    - '*.alertmanager-operated:9093'
    - '*.alertmanager-operated.monitoring.svc.cluster'
    - '*.alertmanager-operated.monitoring.svc.cluster:9093'
    - '*.alertmanager-operated.monitoring.svc'
    - '*.alertmanager-operated.monitoring.svc:9093'
    - '*.alertmanager-operated.monitoring'
    - '*.alertmanager-operated.monitoring:9093'
```

So the request is probably like `curl 100.96.9.151:9093` equivalent, which then doesn't match.

This seems like a bug.

**Comment by howardjohn** [comment]
@hzxuzhonghu wdyt?

**Comment by guusvw** [comment]
If you need any additional information, let me know.

**Comment by triantium** [comment]
The same behaviour can be reproduced with istio 1.8.3

**Comment by guusvw** [comment]
@triantium did you find away around that issue?

**Comment by guusvw** [comment]
@howardjohn @hzxuzhonghu do you have any tips to workaround this issue or even better a fix?

**Comment by triantium** [comment]
> 
> 
> @triantium did you find away around that issue?

Sadly no. I don't know how the hostnames are discovered, but i think that is the place to look for.

**Comment by sitnik** [comment]
We are running many setup with many Prometheus and one Alertmanager, some of these Prometheuses are Istio-enabled, Alertmanager is not. After upgrading to 1.8 we hit this issue when istio-enabled Prometheuses can't reach Alertmanager.
To workaround this issue we've put this into Promethues resource manifest:
```
spec:
...
  podMetadata:
    annotations:
      traffic.sidecar.istio.io/excludeOutboundPorts: "9093"
```
