### ISSUE TITLE
WASM on ingress/egress gateway

### ISSUE THREAD

**Issue by anishmarokeyGitHub** [istio/istio#33199]
I need to add WASM in ingress/egress gateway. Could some one help me on this?

Or give a sample for the same.

I am able to add WASM using [this link](https://github.com/esnible/experiments-1.8). But same WASM is not working in ingress/egress gateway.

**Comment by bianpengyuan** [comment]
https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution  has an example about loading an wasm filter on gateway.
