### ISSUE TITLE
Unclear logs when Istio client sidecar fails to connect with mTLS to server

### ISSUE THREAD

**Issue by yanniszark** [istio/istio#33208]
**Bug description**

Sometimes, when using mTLS, we may get see an error that looks like this: `TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER`

This error usually indicates that the client sidecar expected a TLS connection but something went wrong, which usually is that the server doesn't have a sidecar when it should. The client expects a TLS connection because of a DestinationRule that instructs it to do so.

We think the message could be more descriptive of what happens and give an idea of what to check. A better message IMO would be, for example:
"Could not connect to server using mTLS but server returned unexpected response. Is the server setup appropriately?"

Is this something that Istio could tackle?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

Send a request from a Pod with an Istio sidecar to a Pod without one and a DestinationRule instructing the client sidecar to talk mTLS to the server.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.9.0

**Comment by howardjohn** [comment]
I would love this, one concern is I think the error messages come from low level TLS libraries we don't have control over. @lizan is there any way around that?
