### ISSUE TITLE
Configurable timeout for HTTP inbound route

### ISSUE THREAD

**Issue by edieYoung** [istio/istio#33209]
**Describe the feature request**
Hi there! We are trying set the inbound timeout for HTTP inbound route because we are seeing strange behavior between the inbound proxy and the server. But it turns out Istio is [hardcoding](https://github.com/istio/istio/blob/372f1427c41abba18639fc04dcf73a80177222cd/pilot/pkg/networking/core/v1alpha3/route/route.go#L845-L851) it to 0s(no timeout), I am wondering why? And can we make it configurable?

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
Can you explain more about strange behaviour? What is happening?

**Comment by edieYoung** [comment]
> Can you explain more about strange behaviour? What is happening?

the connections were corrupted somehow with 0 return code, so the timeout setting for the client side never kicks in, neither does the connection timeout. 
See the response log from the inbound proxy:
```
[2021-06-01T17:18:13.069Z] "POST /HimejiCache/scan HTTP/2" 0 - "-" 101 0 299 - "-" "Firefly Jetty/9.4.18.v20190429" 
```

**Comment by ramaraochavali** [comment]
I am not sure how timeouts on the inbound route will help you in this case. But you can apply Envoy filter on the inbound cluster and change the timeout to test your behaviour?

**Comment by ramaraochavali** [comment]
Closing this as we do not want to support inbound timeouts. If needed, please use envoy filter to configure it for your usecase.
