### ISSUE TITLE
Istio sidecar-proxy is not using workload certs to connect to remote Istiod

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#33203]
**Bug description**
Istio sidecar proxy running on VM, is not using workload certs after initial connection with token. When token expires after 3600s, I will get following errors. 

sidecar-proxy-on-vm-logs: `warn    xdsproxy        upstream terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure`

remote-isitod-logs: 
```
error	ads	Failed to authenticate client from ip:49908: Authenticator ClientCertAuthenticator: no verified chain is found; 

Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "Kubernetes": the service account 

authentication returns an error: [invalid bearer token, Token has expired., unknown]
```
After I regenerate and provide new token to sidecar-proxy connection resumes.

/etc/istio/proxy/envoy-rev0.json file always has PROV_CERT as /etc/certs/root-cert.pem.
even in my sidecar.env is set as /etc/certs folder.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Since token is temp authentication method, I'd expect sidecar-proxy to use workload certs generated on /etc/certs folder.

**Steps to reproduce the bug**
[followed this docs](https://istio.io/latest/docs/setup/install/virtual-machine/#configure-the-virtual-machine)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.10.0

**How was Istio installed?**
istioctl install -f config.yaml - IstioOperator options.
sidecar-proxy on vm is installed by following istio.io docs.
 
**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, Amazon Linux2.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Arsen-Uulu** [comment]
`failed to fetch token from file: open ./var/run/secrets/tokens/istio-token: no such file or directory` 

I got this error when I restarted the istio agent and removed the token.

**Comment by Arsen-Uulu** [comment]
@howardjohn Can you advise here please? 

It's not using the certs. It keeps using the temp token

**Comment by howardjohn** [comment]
Code to configure tls: https://github.com/istio/istio/blob/b53449263b1b23d68a04ddef64a9b6fe64946c6d/pkg/istio-agent/xds_proxy.go#L644

So its basically just looking at the PROV_CERTS

> PROV_CERT as /etc/certs/root-cert.pem

PROV_CERT is supposed to be a folder like /etc/certs

**Comment by Arsen-Uulu** [comment]
@howardjohn  If I set PROV_CERT, not PROV_CERTS as /etc/certs, should this work? 

I had it set as PROV_CERT in /var/lib/envoy/sidecar.env. I was still seeing PROV_CERT as /etc/certs/root-ca.pem. 

If you can tell me the right place to set that variable ? Here /var/lib/istio/config/mesh or /var/lib/envoy/cluster.env?

**Comment by Arsen-Uulu** [comment]
@howardjohn  I think PROV_CERTS is wrong variable right ? Should be PROV_CERT?  but I'm not sure where to set it

I would really appreciate your help

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu Can please advise here? 

After setting `JWT_POLICY=""` in sidecar.env, I see a log  `Using existing certs`, I expect Istio to start using certs right after when certs are generated.

but PROV_CERT is still set to `/etc/cert/root-ca.pem`, not sure where to set the var `PROV_CERT:  /etc/cert`.


On Istiod I get 

```Authentication failed for 172.16.148.48:40840: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: target JWT extraction error: no HTTP authorization header exists```

so it's expecting the token. 

@howardjohn

**Comment by irisdingbj** [comment]
client cert is always the first authenticator - you can also get this info in the log as it tried client cert first and failed.

It fails because below two env var is missing -- I will work on a fix for this soon. 

@Arsen-Uulu 

One workaround for this is to add below two env var into your sidecar.env

```
$ echo "PROV_CERT=/var/run/secrets/istio" >> sidecar.env
$ echo "OUTPUT_CERTS=/var/run/secrets/istio" >>  sidecar.env
```

**Comment by Arsen-Uulu** [comment]
@irisdingbj is it ok to put certs to /var/run? If VM gets restarted, `secrets` folder will be gone. 

I will try this workaround and let you know if it works

**Comment by Arsen-Uulu** [comment]
/var/run is tmpfs and after reboot secrets folder will be gone. Is there a way to specify diff location?

**Comment by irisdingbj** [comment]
> /var/run is tmpfs and after reboot secrets folder will be gone. Is there a way to specify diff location?

You can specify any folder according to your need actually, Above is just an exmaple. Just make sure `istio-proxy` has related authority for this folder 

 ```sudo chown -R istio-proxy the-folder-you-defined```

**Comment by Arsen-Uulu** [comment]
@irisdingbj my remote Istiod is behind IngressGateway that exposed as type LoadBalancer handling TLS with my signed cert. If I don't provide my cert to istio-sidecar it's complaining `certificate is signed my unknown authority`, but if I do provide in /etc/certs/root-cert.pem, connection is established using the temp istio-token, but once token expires, I get error from Istiod that no `no valid certificate chain found`. Can you suggest some work around? Please

**Comment by irisdingbj** [comment]
One possible work around is to let your sidecar use system certs like what external control plane[https://istio.io/latest/docs/setup/install/external-controlplane/]  is currently doing: 
```
      proxyMetadata:
        XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
        CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
```

**Comment by Arsen-Uulu** [comment]
@irisdingbj the ca-certificates.crt should contain only my cert? or Istio CA root cert as well?

**Comment by Arsen-Uulu** [comment]
```warn	serverca	Authentication failed for 172.16.149.157:33914: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found.```

I'm getting this error. I'm not sure why it can't validate the client certs

**Comment by Arsen-Uulu** [comment]
@irisdingbj my issue is that Gateway has the cert that I created for my DNS_NAME($ISTIOD_INGRESS),
How I can provide that cert to istio-sidecar trust store running on VM so I don't get this error? 
```  warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"```

If I provide it in root-cert.pem I no longer get that error , but I get `no valid certificate chain found`. 
If I provide as chain with Istio root CA cert I still get that error no valid certificate chain found`.

**Comment by irisdingbj** [comment]
https://istio.io/latest/docs/setup/install/external-controlplane/  This will help.
