### ISSUE TITLE
Add the kubectl default-container annotation when injecting the istio sidecar to Pods

### ISSUE THREAD

**Issue by alexbrand** [istio/istio#33205]
**Describe the feature request**
Kubernetes is adding an annotation to default a container for kubectl operations such as logs, exec, cp, etc. Add support for that annotation.

Kubernetes KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/2227-kubectl-default-container/README.md#summary

**Describe alternatives you've considered**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
We currently support the default-logs-container. We should migrate to `default-container` as that's where Kubernetes is headed.

**Comment by bianpengyuan** [comment]
This is added at 1.10: https://github.com/istio/istio/pull/31180
