### ISSUE TITLE
BUG: istiod ready status mark

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#33218]
Currently we mark istiod ready when `waitForCacheSync` returns true. It compares `InboundUpdates` and `CommittedUpdates`, and looks right, but the `InboundUpdates` is only added when the event handler get run, not the time istiod receives the resource event.  The event handler for a particular event is deposited into the queue and run by the queue worker asynchrounously. 

```
func (s *Server) waitForCacheSync(stop <-chan struct{}) bool {
	if !cache.WaitForCacheSync(stop, s.cachesSynced) {
		log.Errorf("Failed waiting for cache sync")
		return false
	}

	if !cache.WaitForCacheSync(stop, func() bool {
		return s.XDSServer.CommittedUpdates.Load() >= expected
	}) {
		log.Errorf("Failed waiting for push context initialization")
		return false
	}

	return true
}
```

I  tested it by adding a debug log https://github.com/istio/istio/compare/master...hzxuzhonghu:test-sync?expand=1

The logs printed:

```
2021-06-02T09:05:11.045257Z     error   ====waitForCacheSync: committed 4061, expected 2140
2021-06-02T09:05:11.045327Z     info    ads     All caches have been synced up in 5.182093298s, marking server ready

``` 

It shows the `InboundUpdates` number is only 2140, but actually in my cluster there are 8777 pods + 550 svc + 550 endpoint + other resources(nodes, etc). 
**So the way to mark istiod ready is definitely not right, which could cause sidecar to get temporary xds config and then influence the traffic**

**Comment by howardjohn** [comment]
Shouldn't the controller not pass HasSynced until it has completed all event handlers? Is it not doing that?

**Comment by hzxuzhonghu** [comment]
Yes, it is not doning as expected. Firstly, it is not guaranteed all the resources(service, endpoint, vs, dr all sent to the queue), not to mention the queue worker runs all the event tasks. 
Fortunately, we have syncAll logic for service controller at the beginning, but no clear up the queue of it, a waste of cpu.

But for configcontroller, all the configs handling are async, no guarantee at all. , this could cause the Committed updates are only from a part of the total configs.

**Comment by andrewshaoyu** [comment]
Clearing up queue is very necessary. If pilot is ready,but the queue still have a lot of events, new event will wait for a long time.
So pilot should not be ready until it has completed all event handlers, not only `syncAll`.

**Comment by hzxuzhonghu** [comment]
Yeah， as I said above, many tasks in the queue are duplicate with what SyncAll does, we should come up with a way to clear them out or not to enqueue them
