### ISSUE TITLE
DNS Proxying metrics

### ISSUE THREAD

**Issue by lmarszal** [istio/istio#33222]
**Describe the feature request**
I'd like to see following metrics from agent's DNS proxy:
- total number of DNS requests (in order to calculate requests per second)
- number of requests forwarded upstream
- request duration

We might consider additional dimensions - like response code (NOERROR, NXDOMAIN) and request type (A, AAA, MX, ANY etc).

**Describe alternatives you've considered**
Alternative is to implement this telemetry directly in every app.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
We used to have some problems with DNS in our cluster in the past. DNS Proxying greatly reduces our coredns load. What we want to achieve is to have some additional visibility into how many DNS calls application is making (on per-app basis) and how long does it take. Adding these as agent metrics is a great opportunity do implement this once for every service in our mesh.

**Comment by ramaraochavali** [comment]
Makes sense. I am actually planning to add some of these metrics.
