### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by mcandre** [istio/istio#33232]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

The documentation says to use Kubernetes labels to disable sidecar injection. However, this has no effect on pods. Instead, the user must configure Kubernetes *annotations*.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by mcandre** [comment]
Secondary problem, do not know how to fix:

Applying this annotation to Jenkins worker pods creates an infinite loop. This prevents the job from ever fully initializing. It gets stuck there forever.

**Comment by howardjohn** [comment]
Can you provide some more information? Note the labels part is new and applies *only* to Istio 1.10. If you are on an older versions you should find the appropriate page on https://istio.io/archive/
