### ISSUE TITLE
Istio K8s Ingress fails to setup HTTPS listener for K8s service with the same name in  two namespaces

### ISSUE THREAD

**Issue by darkstarmv** [istio/istio#33241]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We use Istio K8s ingress controller as a default K8s ingress.  If I deploy application to two namespaces and use same K8s service name in both namespaces,  one of the ingresses TLS is not getting configured correctly.
if I use unique K8s service names in each namespace, everything works fine.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I should be able to configure ingress for the same service name in any namespace

**Steps to reproduce the bug**
1. Create deployment, service and ingress  in namesapce1
2. Create deployment, service and ingress  in namesapce2 using same service name as in namespace1
3.  test ingress and one of the endpoints will randomly not work:
curl -vvvI  https://sampleapp
*   Trying 111.111.111.111...
* TCP_NODELAY set
* Connected to sampleapp (111.111.111.111) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sampleapp:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sampleapp:443
( 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version
client version: 1.9.0
control plane version: 1.9.5
data plane version: 1.9.5 (4 proxies)
```
```
kubectl version --short
Client Version: v1.18.19
Server Version: v1.18.17
```
```
helm version --short
v3.5.3+g041ce5a
```

**How was Istio installed?**
helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by blupman** [comment]
I have observed this bug in 

```
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (1 proxies)
```

```
helm version --short
v3.6.3+gd506314
```
```
 helm list -n istio-system 
NAME         	NAMESPACE   	REVISION	UPDATED                              	STATUS  	CHART                 	APP VERSION
istio-base   	istio-system	5       	2021-08-13 11:56:54.1863043 +0000 UTC	deployed	base-1.10.3           	           
istio-ingress	istio-system	5       	2021-08-13 11:57:02.4601344 +0000 UTC	deployed	istio-ingress-1.10.3  	           
istiod       	istio-system	5       	2021-08-13 11:56:58.1967769 +0000 UTC	deployed	istio-discovery-1.10.3	           
```

i have create 2 almost empty ingresses, only difference between 1name_2ns 2name_2ns is the name of the  object
```
root@94ce93b1a1c6:/docker# diff -u 1name_2ns 2name_2ns 
--- 1name_2ns	2021-08-13 14:46:46.497040782 +0000
+++ 2name_2ns	2021-08-13 14:46:47.751258398 +0000
@@ -3,7 +3,7 @@
 metadata:
   annotations:
     kubernetes.io/ingress.class: istio
-  name: test
+  name: test1
   namespace: test1
 spec:
   rules:
@@ -25,7 +25,7 @@
 metadata:
   annotations:
     kubernetes.io/ingress.class: istio
-  name: test
+  name: test2
   namespace: test2
 spec:
   rules:
```
testing :
2 different names, 2 namespaces:
```
root@94ce93b1a1c6:/docker# kubectl apply -f 2name_2ns 
ingress.extensions/test1 created
ingress.extensions/test2 created
root@94ce93b1a1c6:/docker# istioctl pc listener istio-ingressgateway-c4d8648bc-x94ck.istio-system | grep test
0.0.0.0 8443  SNI: feature-hc-897-test2.xyz.eu                   Route: https.443.https-443-ingress-test2-test2-0.test2-istio-autogenerated-k8s-ingress.istio-system
0.0.0.0 8443  SNI: feature-hc-897-test.xyz.eu                    Route: https.443.https-443-ingress-test1-test1-0.test1-istio-autogenerated-k8s-ingress.istio-system
```
1 name, 2 namespaces
```
root@94ce93b1a1c6:/docker# kubectl delete -f 2name_2ns 
ingress.extensions "test1" deleted
ingress.extensions "test2" deleted
root@94ce93b1a1c6:/docker# kubectl apply -f 1name_2ns 
ingress.extensions/test created
ingress.extensions/test created
root@94ce93b1a1c6:/docker# istioctl pc listener istio-ingressgateway-x.istio-system | grep test
0.0.0.0 8443  SNI: feature-hc-897-test.xyz.eu                    Route: https.443.https-443-ingress-test-test1-0.test-istio-autogenerated-k8s-ingress.istio-system
```
