### ISSUE TITLE
[multi-cluster] want support Multi-Primary Consistency

### ISSUE THREAD

**Issue by holooooo** [istio/istio#33253]
**Describe the feature request**
We have double k8s cluster runing in active-active. And we install istio with Multi-Primary mode. It looks like Endpoint Discovery is only for pod, endpoint and service, but without Virtualservice or others istio object.

We want the response of requests in the two clusters be always consistent after we dynamic add/delete vs/dr in one of ours cluster. Is there any idea to sync them? 
**Describe alternatives you've considered**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by stevenctl** [comment]
From https://istio.io/latest/docs/ops/deployment/deployment-models/#control-plane-models

> Configuration isolation: You can make configuration changes in one cluster, zone, or region without impacting others.

> Controlled rollout: You have more fine-grained control over configuration rollout (e.g., one cluster at a time). You can also canary configuration changes in a sub-section of the mesh controlled by a given primary cluster.


Multi-primary intentionally allows configs to be out of sync. One common practice is to use a CI/CD system to control the rollout of configuration.

**Comment by holooooo** [comment]
> One common practice is to use a CI/CD system to control the rollout of configuration.

Thx! cd is a good way for gitops or some Long term change. But we have config which generated in runtime. That why we want to have a sync job. I found remoteClusterController has istioInformer, but never use.Is that mean crd sync is a option feature in futrue?

**Comment by stevenctl** [comment]
Correct me if I'm wrong @nmittler but I don't think keeping configs synced across clusters is something we want to handle from inside Istio.

**Comment by nmittler** [comment]
> Correct me if I'm wrong @nmittler but I don't think keeping configs synced across clusters is something we want to handle from inside Istio.

@stevenctl Yeah that's right. Istio doesn't define the process or any tools for pushing config - those sorts of decisions fall entirely within the purview of the mesh admin. Pushing dynamically generated config isn't AFAIK a particularly common use case. I think at this point, it will likely have to be handled by custom code.

**Comment by holooooo** [comment]
Got it.Thanks :+1:
