### ISSUE TITLE
requesting access logs for denied requests due to REGISTRY_ONLY

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#33281]
**Describe the feature request**

When a request is sent to the BlackHole cluster due to not matching a service entry please output logs so that people can know what hostname was blocked so appropriate service entries can be created.

here is a current log showing a blocked request:

root@ubuntu:/# curl https://www.espn.com
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.espn.com:443 

[ubuntu istio-proxy] {"response_code":0,"upstream_service_time":null,"upstream_host":null,"upstream_local_address":null,"request_id":null,"downstream_remote_address":"172.17.3.28:35070","bytes_sent":0,"upstream_cluster":null,"upstream_transport_failure_reason":null,"authority":null,"duration":8,"response_code_details":null,"response_flags":"UH","protocol":null,"user_agent":null,"path":null,"connection_termination_details":null,"method":null,"downstream_local_address":"13.249.75.75:443","route_name":null,"x_forwarded_for":null,"requested_server_name":null,"start_time":"2021-06-04T14:35:50.462Z","bytes_received":0} 

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
istio 1.9.5

istio install yaml file related contents:

      outboundTrafficPolicy:
        mode: REGISTRY_ONLY

  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: '
      start_time: "%START_TIME%",
      authority: "%REQ(:AUTHORITY)%",
      bytes_received: "%BYTES_RECEIVED%",
      bytes_sent: "%BYTES_SENT%",
      content_length: "%REQ(Content-Length)%",
      connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%",
      downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%",
      downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%",
      duration: "%DURATION%",
      request_duration: "%REQUEST_DURATION%",
      response_duration: "%RESPONSE_DURATION%",
      response_tx_duration: "%RESPONSE_TX_DURATION%",
      method: "%REQ(:METHOD)%",
      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      protocol: "%PROTOCOL%",
      request_id: "%REQ(X-REQUEST-ID)%",
      requested_server_name: "%REQUESTED_SERVER_NAME%",
      response_code: "%RESPONSE_CODE%",
      response_code_details: "%RESPONSE_CODE_DETAILS%",
      response_flags: "%RESPONSE_FLAGS%",
      transfer_encoding: "%REQ(Transfer-Encoding)%",
      upstream_cluster: "%UPSTREAM_CLUSTER%",
      upstream_host: "%UPSTREAM_HOST%",
      upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%",
      upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
      upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
      user_agent: "%REQ(USER-AGENT)%",
      x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
    '

**Comment by bianpengyuan** [comment]
Probably you can see the host via `%REQUESTED_SERVER_NAME%`?

**Comment by ceastman-ibm** [comment]
"requested_server_name":null, is what i see in the access logs

**Comment by howardjohn** [comment]
Probablysimilar issue as https://github.com/envoyproxy/envoy/issues/14922

**Comment by ceastman-ibm** [comment]
yep appears so, we do see requested_server_name populated when we have service entries that match

**Comment by GregHanson** [comment]
not stale

**Comment by ceastman-ibm** [comment]
I just checked and istio 1.11.4 now has a populated "requested_server_name" for when the cluster has an outbound traffic policy of registry_only and you do not have a service entry for what your trying to connect to.

The associated access log shows the following now: 

```
{
  "requested_server_name": "www.google.com",
  "upstream_transport_failure_reason": null,
  "response_flags": "UH",
  "upstream_cluster": "BlackHoleCluster",
  "authority": null,
  "response_code_details": null,
  "route_name": null,
  "method": null,
  "upstream_local_address": null,
  "bytes_received": 0,
  "start_time": "2021-12-02T16:44:39.405Z",
  "response_code": 0,
  "protocol": null,
  "request_id": null,
  "downstream_local_address": "142.251.33.36:443",
  "connection_termination_details": null,
  "downstream_remote_address": "172.17.15.206:47858",
  "upstream_service_time": null,
  "bytes_sent": 0,
  "x_forwarded_for": null,
  "duration": 5,
  "upstream_host": null,
  "path": null,
  "user_agent": null
}
```

which is very helpful
