### ISSUE TITLE
Constantly increasing memory use in istio-proxy

### ISSUE THREAD

**Issue by marcosmoraes88** [istio/istio#33291]
**Bug description**

We started using istio as a sidecar only a short time ago, but I've noticed that memory usage has been growing steadily in the istio-proxy container, about 1-2MB per hour per pod. Memory usage always increases and doesn't decrease even with the drop of requests to the app.

I tried some changes, like removing all service entries we created, but I noticed no difference.

Is that memory increase normal or a leak? Could it be related to using/enabling statistics/telemetry (as I did)?

In this image we can see the sum of memory used by istio-proxy and my-app containers... There are 16 pods of the same app, all of them with sidecar:
![image](https://user-images.githubusercontent.com/5939025/120889356-05bd5e80-c5d3-11eb-8bdd-6a39020472c7.png)

[X] Networking
[X] Performance and Scalability
[X] Extensions and Telemetry

**Expected behavior**

Memory usage is expected to grow as traffic increases, however, with fewer requests, memory should not increase any further (at least not at the rate described above), and maybe even be released.

**Steps to reproduce the bug**

I just used the bookinfo sample to reproduce and analyze memory usage. It increased, but with a very lower rate/scale (due to the lower number of incoming/outgoing requests?).

Our app has about 200 incoming rps and 450 outgoing rps (to 20+ external services) per pod at peak, and 20/60 in/out rps in times of lower access.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (30 proxies)

$ kubectl version --short
Client Version: v1.16.0
Server Version: v1.19.6-eks-49a6c0
```

**How was Istio installed?**

```
$ istioctl operator init --revision 1-9-4
$ kubectl apply -f istio-operator.yaml -n istio-system
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS

**Comment by bianpengyuan** [comment]
Does it become stable eventually or oom?

**Comment by marcosmoraes88** [comment]
I've set the proxy memory to 1GB so we're pretty far away from oom. I'm going to decrease the allocated memory to see if oom occurs or if memory usage stabilizes at a certain point.

**Comment by marcosmoraes88** [comment]
I decreased the proxy memory to see if it stabilizes, but memory usage keeps growing until envoy is oom killed. Any clue about that?

**Comment by bianpengyuan** [comment]
I would suggest to not lower it but keep it at a high value (like 1G) and see if it stabilizes eventually. If it ooms at that level, there is indeed something wrong..

**Comment by djablonski-moia** [comment]
We see the same behaviour (at least since Istio 1.8.5), with the sidecar running into OOMKilled even though it's running with a memory limit of 1GB.
Since now, we haven't been able to track down the specific request patterns that cause this, so we can't reproduce outside of the specific service where it appears. Will open a new issue once we can.
