### ISSUE TITLE
Consider OpenTelemetry access log support

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#33307]
Envoy [open_telemetry accesslog](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3alpha/logs_service.proto) supports exporting to OT agent.

1. Consider supporting this directly
2. Consider how this can be used with our telemetry pipeline.

**Comment by douglas-reid** [comment]
This was the basic shape (with some small diffs) of one of the original Telemetry API for access logging that was proposed. The trick will be providing an API that allows similar control over file-based access loggers (for body/attributes). The rest should be provider details.

**Comment by mandarjog** [comment]
Not stale.

**Comment by zirain** [comment]
API: https://github.com/istio/api/pull/2175
ISTIO: https://github.com/istio/api/pull/2175
