### ISSUE TITLE
go mod vendor failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#33314]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

$ go mod vendor

internal error: failed to find embedded files of github.com/lucas-clemente/quic-go/internal/qtls: D:\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.21.0\internal\qtls\go118.go:3:1: expected 'package', found "quic-go doesn't build on Go 1.18 yet."

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
$ go version
go version go1.16.5 windows/amd64

**Comment by hzxuzhonghu** [comment]
https://github.com/lucas-clemente/quic-go/issues/3194

Not sure how CI passes

**Comment by ericvn** [comment]
I don't think `go mod vendor` is run anywhere in ci. `go mod tidy` is.

**Comment by hzxuzhonghu** [comment]
@howardjohn The biggest issue is i could not even test & build binaries in my local env.

**Comment by ericvn** [comment]
I'm still confused where `go mod vendor` is in your local environment to understand where/what the failure is. I agree that the command does fail as noted, but I haven't had it cause any issues locally so far. I suspect our local dev/test steps are different.
