### ISSUE TITLE
Rolling back to 1.9 from 1.10 causes injector outage

### ISSUE THREAD

**Issue by Stono** [istio/istio#33317]
**Bug description**
Hi, 
We attempted to upgrade (in place control plane upgrade) from 1.9 to 1.10 today, but it failed due to https://github.com/istio/istio/issues/33115#issuecomment-856578303.

We rolled back the control plane to 1.9 which has broken sidecar injection, the error we get is:

```
Error: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: x509: certificate signed by unknown authority
```

Upon inspection the `clientConfig.caBundle` is missing from the `MutatingWebhookConfiguration`

Decided to delete the `istiod` deplyoment as well as the `MutatingWebhookConfiguration`, once redeployed that `caBundle` is still not present.

In the `istiod` logs we're seeing:

```
{"level":"error","time":"2021-06-08T09:57:51.784697Z","scope":"ads","msg":"Failed to authenticate client from 10.206.6.78:43184: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster \"Kubernetes\": the service account authentication returns an error: [invalid bearer token, Token has been invalidated]"}
```

We attempted to delete the service account secret `istiod-service-account-token-ld8tz`, and restart the deployment, no errors in the `istiod` logs now but still no `caBundle`.

Interestingly the `ValidatingWebhookConfiguration` has a caBundle, so we manually copied that onto the `MutatingWebhookConfiguration` and injection started working again.  I'm guessing this indicates there's some logic that's only checking one of these resources for `caBundle`, not both...

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
To be able to roll back the control plane.

**Steps to reproduce the bug**
1.9 -> 1.10 -> 1.9

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
@Monkeyanator are you able to take a look at this?

**Comment by howardjohn** [comment]
@Stono for the ` the service account authentication returns an error: [invalid bearer token, Token has been invalidated]"}`, is it continuous and blocking pods from connecting? When a pod is removed, GKE (I think its a GKE specific thing?) will immediately revoke the token, so as a pod is shutting down you may see this. It may be increased during upgrade/rollback since you are bouncing pods?

Just trying to see if its related to the root cause or noise

**Comment by Monkeyanator** [comment]
Looking into it now. Having trouble reproducing since I just run into [#32761 ](https://github.com/istio/istio/issues/32761) when going from 1.9->1.10->1.9.

**Comment by Monkeyanator** [comment]
Using the latest `release-1.9`, upgrading to 1.10.0, and downgrading back to 1.9, I find that the CA bundle is patched in as expected (on local `kind` setup). 

The webhook patcher should patch all mutating webhooks with `istio.io/rev=default`. Could you possibly dump the full `MutatingWebhookConfiguration` here? And also check `istiod` logs for `New webhook config added, patching MutatingWebhookConfiguration` (should be seeing these near startup time)?

**Comment by Stono** [comment]
Morning folks! 
I think there are two separate things going on here:

1. Some how, the caBundle got removed from the MutatingWebhookConfiguration (not sure how/why, still trying to replicate)
2. It wasn't added back

#2 is easy to replicate for me, both on `1.9.5` and `1.10.0`.  Simply edit the `MutatingWebhookConfiguration`, remove `caBundle`, and restart istiod.  There is nothing in the logs _at all_ relating to the mutating webhook, on the validating webhook, and the resource never gets patched.

The complete resource as you've requested @Monkeyanator currently looks like this:

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: "2021-06-08T10:08:24Z"
  generation: 3
  labels:
    app: istio
    ark: istio
    chart: istio-1.9.5
    heritage: Tiller
    release: istio
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:ark: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:webhooks:
        .: {}
        k:{"name":"sidecar-injector.istio.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector:
            .: {}
            f:matchExpressions: {}
          f:objectSelector: {}
          f:reinvocationPolicy: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: Go-http-client
    operation: Update
    time: "2021-06-08T10:08:24Z"
  name: istio-sidecar-injector
  resourceVersion: "481206079"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/istio-sidecar-injector
  uid: 0ef28f22-f241-4db7-ac87-eba350e078ed
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - istio-system
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
    - key: istio-env
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```

So one thing you pointed out which was the `istio.io/rev` label, this is not present on our Webhook.  Remember that our cluster is long lived and has been upgraded since before revision labels existed, and also isn't deployed in the "standard" way... adding that revision label to the resource and the caBundle gets added again.

I'm guessing #1 is a symptom of the same thing (missing revision labels)
