### ISSUE TITLE
MongoDB TLS Egress not working using Bitnami helm charts

### ISSUE THREAD

**Issue by Aryan-NBS** [istio/istio#33324]
[values-tls.zip](https://github.com/istio/istio/files/6616474/values-tls.zip)
I have attached the values. yaml.

Yamls.: egressgateway
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: istio-egressgateway-mongodb
  namespace: aryan-is
spec:
  servers:
    - hosts:
        - mongodb.xxxxxxxx.svc.cluster.local
      port:
        name: tcp-mongodb
        number: 15443
        protocol: TCP
  selector:
    istio: egressgateway

**Comment by howardjohn** [comment]
@Aryan-NBS thanks for the issue! When you create an issue, there is a bug template. Can you please fill it out? Right now there is so little information that its impossible to help here. We need to know what you tried, and what configuration you have so we know what is going wrong. Thanks!

**Comment by Aryan-NBS** [comment]
**### Error: The server is configured to only allow SSL connections**

[values-tls.zip](https://github.com/istio/istio/files/6621093/values-tls.zip)

@howardjohn Hello, Thanks for your response, We have EKS cluster on AWS, Where in we have deployed MondoDB as stateful set  using Bitnami helm charts. MongoDB pod is in same Cluster but outside of Istio service mesh(in namespace without istio enabled).

Usecase: We are need to prove connectivity to MongoDB via Egress using TLS/Mongo protocol. We are trying to connect using IBM IIB service.

### DataSource
{
	"mongodb": {
		"host": "mongodb-tls-headless.***.svc.cluster.local",
		"port": 27017,
		"database": "fireRecord",
		"name": "mongodb",
		"connector": "mongodb"
	}
}


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-mongodb
  namespace: aryan-is
spec:
  host: mongodb-tls.***.svc.cluster.local
  exportTo: ["*"]
  trafficPolicy:
   tls:
    mode: MUTUAL
    credentialName: secret-mongodb
    sni: mongodb-tls-headless.***.svc.cluster.local
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: mongo-egress-vs
  namespace: aryan-is
spec:
  hosts:
    - mongodb.***.svc.cluster.local
  gateways:
    - mesh
    - istio-egressgateway-mongodb
  tcp:
    - match:
        - gateways:
            - mesh
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            port:
              number: 15443
    - match:
        - gateways:
            - istio-egressgateway-mongodb
          port: 15443
      route:
        - destination:
            host: mongodb.***.svc.cluster.local
            port:
              number: 27017
          weight: 100
---
Yamls.: egressgateway
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
name: istio-egressgateway-mongodb
namespace: aryan-is
spec:
servers:
- hosts:
- mongodb.***.svc.cluster.local
port:
name: tcp-mongodb
number: 15443
protocol: TCP
selector:
istio: egressgateway
