### ISSUE TITLE
WorkloadAgnostic tests have excessive config churn causing slow tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33335]
SetupForServicePair is called for each job. This means new config is applied for each pair.

For a typical job, say virtualservice/rewrite_uri, we end up with 9 pairs. This causes the test to take ~10s, which isn't _that_ slow but it adds up. Just 6 months ago pilot tests took 8 minutes, now they are 25min+.

I think just switching SetupForServicePair with SetupForDestination is not sufficient either unless we invert the ordering to group destinations (right now its source/destination)

This is also in a fast enviornment, config updates are extremely slow when running somewhere like GKE

cc @stevenctl

**Comment by ryantking** [comment]
Moving to the 1.12 milestones due to recent inactivity

**Comment by howardjohn** [comment]
It seems like almost all tests are just looking at dst. We could refactor it to be `to/from` instead of `from/to` and add an optimization to  not delete+re-apply config if its identical, or make it more explicit.

**Comment by howardjohn** [comment]
Not stale

**Comment by stevenctl** [comment]
not-stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale
