### ISSUE TITLE
startTLS support in service entry

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#33345]
**Describe the feature request**
Since startTLS support has been added to envoy: https://github.com/envoyproxy/envoy/pull/13112

Can it be used in the protocol section of service entries? something like:

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: postgresql-service-entry
spec:
  hosts:
  - postgresql.server.com
  location: MESH_EXTERNAL
  ports:
  - name: tls
    number: 30101
    protocol: STARTTLS
  resolution: DNS

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by adityaanand11** [comment]
#3588

**Comment by ceastman-ibm** [comment]
@howardjohn how do we keep this issue from getting closed due to staleness?

**Comment by GregHanson** [comment]
not stale - I am looking into the implementation

**Comment by howardjohn** [comment]
Not sure this makes sense. STARTTLS means that the client starts with raw TCP and then 'upgrades' to TLS. `protocol: TLS` in Istio means we route based on an SNI. The initial connection with STARTTLS does not have SNI, so there is nothing to route beyond `protocol: TCP`.

Add STARTTLS _origination_ could make sense though.

**Comment by remansour** [comment]
Can we get an update or ETA on when this will be addressed?

**Comment by GregHanson** [comment]
@remansour there was a PR started [here](https://github.com/istio/istio/pull/37290) but was eventually abandoned as consensus could not be reached

**Comment by iprasla** [comment]
Is there an update on this? It seems like there was discussion and it was suggested that there will be a solution to that. Can it be re-open or be addressed?
