### ISSUE TITLE
Build broken on Mac/OSX

### ISSUE THREAD

**Issue by esnible** [istio/istio#33346]
To reproduce, use a Mac:

```bash
BUILD_WITH_CONTAINER=0 make istioctl

ISTIO_OUT=/Users/snible/go/src/istio.io/istio/out/darwin_amd64 ISTIO_BIN=/Users/snible/go/bin GOOS_LOCAL=darwin bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
script: illegal option -- -
usage: script [-adkpqr] [-t time] [file [command ...]]
Unexpected failure
```

The problem seems to be that OSX uses BSD-style `script`, but Istio expects GNU-style `script`.  It looks like this started a month ago, with https://github.com/istio/istio/commit/10540330579e5db4ce0011ba5c0ea3e90da83a56#diff-83635019e8ef09ebacebca4fac44b290c12790bd98c35380541fc99805c45c4fR39 which added `script` for the first time.

I first looked for an OSX Mac work-around, but I can't find a way to replace the built-in `script` with a GNU-style `script`.  For now my work-around is to leave off `BUILD_WITH_CONTAINER=0` (but of course that slows down my builds).

FYI `git bisect run bash -c `make istioctl` doesn't report the commit that introduced the problem, perhaps because of caching or lack of need to retry something.

FYI @howardjohn

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/33172

**Comment by ericvn** [comment]
Note that the build is not `broken` as the build uses a build container and as you note that does work.

**Comment by ericvn** [comment]
I believe this is now fixed.

**Comment by brian-avery** [comment]
@esnible can you please confirm and if it is fixed, can you close it?

**Comment by ericvn** [comment]
Closing as fixed. Please re-open if you still see the issue.
