### ISSUE TITLE
The port field implementation of IstioEgressListener is not as expected

### ISSUE THREAD

**Issue by zyfjeff** [istio/istio#33365]
I have looked at the meaning of the port field of [IstioEgressListener](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener). If the port field is used, then only the relevant listener with the specified port will be generated. For example, if I have a service that has two service ports, one is 80 and the other is 8080. If I specify a port field of 80, then only a listener of 80 will be generated. But to generate cluster is the **outbound ||80|xxx** and **outbound||8080|xxx** two cluster, I think this is not in line with the expectations of the port field.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/33113 - See this. This attempted to fix that issue. Got a regression and reverted. I will be fixing it soon.

**Comment by zyfjeff** [comment]
@ramaraochavali Thank you. That really worked out the problem
