### ISSUE TITLE
Merge secretController

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#33370]
There are two components that are starting SecretController which is used to discover multi clusters.

1. kube registery https://github.com/istio/istio/blob/e7911b20b131082ff2f8e648735692036c814d69/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L363
2. SDS Server https://github.com/istio/istio/blob/e7911b20b131082ff2f8e648735692036c814d69/pilot/pkg/secrets/kube/multicluster.go#L69

**Comment by howardjohn** [comment]
@ramaraochavali and @stevenctl have both looked into this I think.

**Comment by ramaraochavali** [comment]
closing this as the issue already exists
