### ISSUE TITLE
Build in only selected Envoy extensions

### ISSUE THREAD

**Issue by rojkov** [istio/istio#33377]
Currently Istio's proxy seems to have all existing Envoy extensions built in even though some of them are not used in meshes, e.g. Dubbo, Lua extensions etc.

Would it be useful for Istio to have control over the list of extensions included in the proxy with an Istio-specific config like in this patch https://github.com/rojkov/proxy/commit/a27459acd57ac9149db1bee9e0fe5194f9b8cef2? 

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
While we may not use them in the core, folks are depending on these in Envoy Filters so I am not sure it's safe to remove
