### ISSUE TITLE
Istio 1.10: Impact of 3rd party token deprecation on Docker Desktop installations

### ISSUE THREAD

**Issue by alecor191** [istio/istio#33388]
**Bug description**
Our developers have local K8S clusters with istio installed on their dev boxes using Docker Desktop (incl. Istio Ingress Gateway and other Istio configurations to be as close as possible to our actual cloud-hosted K8S clusters).

Starting Istio 1.10, istioctl shows the following deprecation warning when installing Istio on Docker Desktop K8S:

```
! values.global.jwtPolicy is deprecated; use Values.global.jwtPolicy=third-party-jwt. See http://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for more information instead
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Allow first party tokens on environments that don't have 3rd party support (like Docker Desktop) or share guidance how to setup Istio on Docker Desktop once this feature is removed.

**Steps to reproduce the bug**
Install Istio 1.10.x on a Docker Desktop K8S installation.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Docker Desktop on Win10

**Comment by howardjohn** [comment]
This feature is now GA in Kubernetes, so it should be enabled by all conformant Kubernetes cluster. Once those are the only supported Kubernetes versions, we may remove the feature, but that won't be for many months and we won't do it before then. I assume docker desktop will update by then.

**Comment by alecor191** [comment]
Thanks a lot @howardjohn and @ericvn for your comments! I can confirm that with Docker Desktop 3.4 there is no such warning anymore. So this issue is addressed for me.
