### ISSUE TITLE
typed_extension_protocol_options of any type supported in istio

### ISSUE THREAD

**Issue by durd07** [istio/istio#33389]
**Describe the feature request**
Like in https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples.html?highlight=typed_extension_protocol_options, typed_extension_protocol_options works as an general way to handle any protocol related configuration. After search code of istio, seems only HttpProtocolOptions handled in this scenario. Is it possible to support other protocol's typed_extension_protocol_options, for example RedisProtocolOptions, ThriftProtocolOptions or others?

**Describe alternatives you've considered**
set the typed_extension_protocol_options at DestinationRule and pass it into envoy configuration.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
https://istio.io/docs/reference/config/networking/envoy-filter/ can patch arbitrary envoy config. I don't think we have plans to support other protocols at this time. https://github.com/aeraki-framework/aeraki is a third party application that abstracts this though

**Comment by durd07** [comment]
@howardjohn thanks for your response. I just use envoyfilter to adapt Lister configuration before. I can have a try with cluster configurations with that.
