### ISSUE TITLE
sidecar egress host not blocking request

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#33387]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
sidecar egress yaml: 
spec:
  egress:
  - hosts:
    - ./*.test.svc.cluster.local
    - ./fqdn.hostname.com
  workloadSelector:
    labels:
      app.kubernetes.io/name: registration

the registration pod can get to other hostnames that are not specified in the sidecar egress. 

we noticed that there were extra unexpected entries in the istioctl pc cluster registration

for instance found there was a *.cloud.ibm.com in the istioctl pc cluster registration even thou it's not in the sidecar egress host

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

the pod with istio proxy should not be able to connect to anything not explicitly allowed in the sidecar egress host spec

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version --remote
client version: 1.9.5
control plane version: 1.9.5
data plane version: 1.9.5 (250 proxies)

kubectl version --short
Client Version: v1.18.0
Server Version: v1.19.0+d856161

**How was Istio installed?**

istioctl install with custom yaml - outboundTrafficPolicy - REGISTRY_ONLY

**Environment where the bug was observed (cloud vendor, OS, etc)**

IBM Cloud
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by GregHanson** [comment]
recreated with `*.wikipedia.org` and `en.wikipedia.org` ServiceEntry's with a corresponding Sidecar to allow traffic to the wildcard in the `awake` service and `en.wikipedia.org` only for `sleep` service.  (gist [here](https://gist.github.com/GregHanson/3567f5a23bcd58ad1a8acf2a4d1155eb))

```bash
$ istioctl install --set profile=demo --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY -y
##apply linked gist
$ export AWAKE_POD=$(kubectl get pod -l app=awake -o jsonpath={.items..metadata.name})
$ export SLEEP_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
$ kubectl exec "$SLEEP_POD" -c sleep -- sh -c 'curl -s https://en.wikipedia.org/wiki/Main_Page | grep -o "<title>.*</title>"; curl -s https://de.wikipedia.org/wiki/Wikipedia:Hauptseite | grep -o "<title>.*</title>"'
<title>Wikipedia, the free encyclopedia</title>
<title>Wikipedia – Die freie Enzyklopädie</title>

$ kubectl exec "$AWAKE_POD" -c awake -- sh -c 'curl -s https://en.wikipedia.org/wiki/Main_Page | grep -o "<title>.*</title>"; curl -s https://de.wikipedia.org/wiki/Wikipedia:Hauptseite | grep -o "<title>.*</title>"'
<title>Wikipedia, the free encyclopedia</title>
<title>Wikipedia – Die freie Enzyklopädie</title>

$ istioctl pc cluster $SLEEP_POD | grep wiki
*.wikipedia.org                                         443       -          outbound      ORIGINAL_DST     
en.wikipedia.org                                        443       -          outbound      ORIGINAL_DST     
$ istioctl pc cluster $AWAKE_POD | grep wiki
*.wikipedia.org                                         443       -          outbound      ORIGINAL_DST     
en.wikipedia.org                                        443       -          outbound      ORIGINAL_DST     
```

`de.wikipedia.org` should only be reachable from `awake` since it has the wildcard in the Sidecar

**Comment by howardjohn** [comment]
I would like to remind you that Istio is not a egress firewall (https://preliminary.istio.io/latest/docs/ops/best-practices/security/#securing-egress-traffic) so this is only a minor bug. If this is a major issue for you I strongly encourage you to rethink your configuration to properly enforce egress policies if needed.

That being said, this does seem like a bug.

I think https://github.com/istio/istio/blob/2a65168a27baffe6d16de47b461316bda2a264fc/pilot/pkg/model/sidecar.go#L683

should be

```
service.Hostname.SubsetOf(importedHost)
```

@ramaraochavali any thoughts?

**Comment by ceastman-ibm** [comment]
@howardjohn is there a recommended way to limit egress of individual microservices that have istio proxy? it seemed like sidecar was the only viable option. and sidecar does appear to be working for the most part.

**Comment by ceastman-ibm** [comment]
@ramaraochavali @howardjohn any more thoughts on this issue and the proposed solution?

**Comment by ramaraochavali** [comment]
@ceastman-ibm Extremely sorry - I missed this some how. Yes @howardjohn 's suggestion looks good to me.

**Comment by ceastman-ibm** [comment]
@howardjohn @ramaraochavali can this be put into 1.9.x and 1.10.x releases?

**Comment by ramaraochavali** [comment]
@ceastman-ibm first this needs to be fixed in Master. I will fix it some time this week unless some one gets to this earlier.

**Comment by ceastman-ibm** [comment]
@ramaraochavali ok thanks for the update. have a great day.
