### ISSUE TITLE
per service mutual TLS authentication in Consul

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#3338]
ref: https://istio.io/docs/tasks/security/per-service-mtls.html

Individual services registered in consul should be able to enable/disable mTLS for their ports. One of the ways of doing this would be use a standard label - "auth.istio.io/port: NONE", similar to Kubernetes annotation.

**Comment by GregHanson** [comment]
resolved by #3339

**Comment by kidiyoor** [comment]
I think the https://github.com/istio/istio/pull/3339 just solves the problem of enabling mTLS for all services. I guess 'per service mTLS'(enable/disable mTLS for individual service) still need to be addressed.
