### ISSUE TITLE
How to remove the specified listener filter through envoyfilter

### ISSUE THREAD

**Issue by kangminze** [istio/istio#33407]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
How to remove the specified listener filter through envoyfilter, for example, remove envoy.filters.listener.http_inspector

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I would recommend you don't do that you will break ~everything if you remove that listener filter since the configs expects it to be there

**Comment by kangminze** [comment]
Thank you for your reply, but I want to know if envoyfilter supports this operation

**Comment by howardjohn** [comment]
I do not believe it does. You can probably add new ones (via Listener) but
not replace
