### ISSUE TITLE
crashing istio-sidecar agent is blocking ALL outbound traffic from VM.

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#33454]
**Bug description**
istio-agent installed on Amazon EC2 Linux 2, istio version 1.10.0. 

When ISTIO_CAPTURE_DNS is enabled all dns traffic from port 53 is redirected to 15053.
if the start is successful my instance hangs for a bit and resumes, meaning terminal( we are using ssm-agent to ssh)
when I stop istio, my instance becomes unresponsive. 
`Note: Please refer to below errors`

if the start is unsuccessful due to some errors, my instance becomes unresponsive, and it needs reboot.

After checking ssm-agent logs I found that, when istio-agent is having issues 

`Post "https://logs.us-west-2.amazonaws.com/": dial tcp: lookup logs.us-west-2.amazonaws.com on <ip>:53: dial udp <Ip>:53: connect: network is unreachable`

`caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: network is unreachable`

I set ISTIO_CAPTURE_DNS to false and OUTBOUND_IPRANGES_EXCLUDE="169.254.169.254/32 to test, 
I still can see that traffic flows thru envoy for 169.254.169.254, except for DNS.  when I stop istio, I see same errors again, lookup's are failing. Why istio-agent with DNS_CAPTURE set to false is still causing dns lookup failures? 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
If I stop istio sidecar, even with DNS_CAPTURE true, I'd expect it to remove all iptable redirects, looks like iptables are still redirecting to sidecar, even when sidecar agent is stopped. 
I know that `systemctl stop istio` runs  ExecStopPost=/usr/local/bin/istio-start.sh clean to clean up iptables. 

but I can observe same behaviour even when DNS_CAPTURE is set to false. 

**Steps to reproduce the bug**
Please follow istio.io docs for vm installtion
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version 1.10
**How was Istio installed?**
IstioOperator
**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, Amazon Linux 2
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by kyadav-cgi** [comment]
How this issue got resolved ..? @Arsen-Uulu
