### ISSUE TITLE
Too much installed on remote clusters, esp. RBAC resources

### ISSUE THREAD

**Issue by frankbu** [istio/istio#33455]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

The [external control plane setup instructions](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/) are intended to install as little as possible on the remote cluster (or config cluster), i.e., only what is needed.

In Istio 1.10 the installation on a remote "non-config" cluster installed only the `MutatingWebhookConfiguration` and nothing else. Since 1.10, however a number of RBAC resources, and the validating webhook have been moved from the `base` to the `istio-dicovery` charts. As a result a number of additional resources are now being installed when running the same command:

```
istioctl install profile=external =>

  MutatingWebhookConfiguration: istio-sidecar-injector-external-istiod
  ServiceAccount: istiod
  Role: istiod
  RoleBinding: istiod
  ClusterRole: istio-reader-clusterrole-external-istiod
  ClusterRole: istiod-clusterrole-external-istiod
  ClusterRoleBinding: istio-reader-clusterrole-external-istiod
  ClusterRoleBinding: istiod-clusterrole-external-istiod
  ValidatingWebhookConfiguration: istio-external-istiod
```

Some of these resources (e.g., `ValidatingWebhookConfiguration`) are not needed, period. Others are questionable, and some are also installed by the `istioctl x create-remote-secret` command, which in addition to creating the remote secret on the control plane cluster, has the side-effect of also creating some of these same resources on the remote cluster:

```
istioctl x create-remote-secret =>

  ServiceAccount: istio-reader-service-account
  ClusterRole: istio-reader-clusterrole-external-istiod
  ClusterRole: istiod-clusterrole-external-istiod
  ClusterRoleBinding: istio-reader-clusterrole-external-istiod
  ClusterRoleBinding: istiod-clusterrole-external-istiod
```

On a remote "config" cluster we additionally enable the `base` component, mostly to enable the Istio CRDs, but are also getting many additional resources, some of which may not all be necessary:

```
istioctl install profile=external --set components.base.enabled=true (config cluster)

  MutatingWebhookConfiguration: istio-sidecar-injector-external-istiod
  ValidatingWebhookConfiguration: istio-external-istiod
  ValidatingWebhookConfiguration: istiod-external-istiod
  ServiceAccount: istio-reader-service-account
  ServiceAccount: istiod
  ServiceAccount: istiod-service-account
  ClusterRole: istio-reader-clusterrole-external-istiod
  ClusterRole: istio-reader-external-istiod
  ClusterRole: istiod-clusterrole-external-istiod
  ClusterRole: istiod-external-istiod
  ClusterRoleBinding: istio-reader-clusterrole-external-istiod
  ClusterRoleBinding: istio-reader-external-istiod
  ClusterRoleBinding: istiod-clusterrole-external-istiod
  ClusterRoleBinding: istiod-external-istiod
  ConfigMap: istio
  Role: istiod
  Role: istiod-external-istiod
  RoleBinding: istiod
  RoleBinding: istiod-external-istiod
  CustomResourceDefinition: authorizationpolicies.security.istio.io
  CustomResourceDefinition: destinationrules.networking.istio.io
  ...
  CustomResourceDefinition: workloadgroups.networking.istio.io
```

So the questions are:

1. Which resources are needed?
2. How to supress unnecessary charts (e.g., everything but the `MutatingWebhookConfiguration` in the non-config cluster)?
3. Should `istioctl x create-remote-secret` install RBAC resources in the remote cluster, or should that be done by the install? 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by stevenctl** [comment]
Context on create-remote-secret behavior: https://github.com/istio/istio/pull/28059

**Comment by frankbu** [comment]
Thanks @stevenctl for the context. I think the reason for creating the resources on the remote cluster may not apply anymore. Now that we install the ingressgatewaymay in a separate later step on remote clusters (using gateway injection), I think it will work fine to just install the the remote cluster first (includes the needed reader service account) and then do the create-remote-secret after that.

**Comment by frankbu** [comment]
After discussing at the last envinronment WG call, I believe these are what should be installed on remote clusters using an external istiod:

1. install on non-config remote cluster
  ```
  MutatingWebhookConfiguration: istio-sidecar-injector-<ns>
  ServiceAccount: istio-reader-service-account
  ClusterRole: istio-reader-clusterrole-<ns>
  ClusterRoleBinding: istio-reader-clusterrole-<ns>
  ```
2. install on config cluster
  ```
  MutatingWebhookConfiguration: istio-sidecar-injector-<ns>
  ServiceAccount: istio-reader-service-account
  ClusterRole: istio-reader-clusterrole-<ns>
  ClusterRoleBinding: istio-reader-clusterrole-<ns>

  ValidatingWebhookConfiguration: istio-<ns>
  ServiceAccount: istiod
  Role: istiod
  RoleBinding: istiod
  ClusterRole: istiod-clusterrole-<ns>
  ClusterRoleBinding: istiod-clusterrole-<ns>

  CustomResourceDefinition: authorizationpolicies.security.istio.io
  CustomResourceDefinition: destinationrules.networking.istio.io
  ...
  CustomResourceDefinition: workloadgroups.networking.istio.io
  ```
3. istioctl create-remote-secret
  ```
  <none> # installs no RBAC resources on remote cluster
  ```

**Comment by howardjohn** [comment]
I think you need the sidecar injector configmap in control plane cluster as well. 

I am also not sure why you need the roles:
```
ServiceAccount: istiod
Role: istiod
RoleBinding: istiod
ClusterRole: istiod-clusterrole-<ns>
ClusterRoleBinding: istiod-clusterrole-<ns>
```

On the config cluster? Are we creating a kubeconfig that is using that service account somehow? If so it makes sense, I just wasn't sure since we do it a bit differently

**Comment by frankbu** [comment]
@howardjohn 

> I think you need the sidecar injector configmap in control plane cluster as well.

We don't need it because istiod volume mounts the one on the control plane cluster.

**Comment by howardjohn** [comment]
then why is the `istio` configmap needed? I would expect both or neither?

**Comment by frankbu** [comment]
> then why is the `istio` configmap needed? I would expect both or neither?

The istio configmap is needed because the control plane install is using SHARED_MESH_CONFIG to separate the user-settable values.

`Notice that istiod is configured to use the locally mounted istio configmap and the SHARED_MESH_CONFIG environment variable is set to istio. This instructs istiod to merge the values set by the mesh admin in the config cluster’s configmap with the values in the local configmap set by the mesh operator, here, which will take precedence if there are any conflicts`

Do you think that both configmaps should be installed on the config cluster, and then it's up to the control plane configuration to use one, both, or neither?

**Comment by howardjohn** [comment]
Ah I see. My expectation was when user runs it, they get not configmap in config cluster. If they want to modify settings, they create the configmap with whatever settings they want.

That is what we will do for our product, but one difference is that users don't run `istioctl install` at all on the remote, so it doesn't make sense to use it to configure the configmap. If they are already using it then maybe it does make sense to just set it as part of `istioctl install` in the `meshConfig` section. However, we may want to default to an empty configmap instead of the current settings? Ideally we do that for normal single cluster install actually (with defaults in golang code)

**Comment by frankbu** [comment]
@howardjohn 

Both the `istio` and `istio-sidecar-injector` configmap charts appear to have a `.Values.global.use/supress` guard, so I think that adding both to the config cluster charts makes sense. Then, depending on how the external istiod is configured, users can choose to enable or disable one or both of the configmaps on the remote cluster. Maximum flexibility, WDYT?

**Comment by JingmingGuo** [comment]
@howardjohn Is there a way that I can config my istio template to not generated these RBAC e.g. ServiceAccount: istio-reader-service-account?
