### ISSUE TITLE
Multi cluster DNS breaks due to they way iptables and conntrack operates

### ISSUE THREAD

**Issue by astrikos** [istio/istio#33469]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We use multi cluster istio and the federation feature using istio's very own DNS.
In order for istio to capture all DNS traffic from app containers there is among others one iptable rule like
`REDIRECT udp – anywhere 169.254.20.10 udp dpt:domain redir ports 15053`

From time to time though we experience DNS resolution errors for endpoints that are from the federated clusters and they supposed to be answered from istio's DNS feature.
Our understanding is that in theory every single DNS UDP packet coming from application inside a container will be captured and redirected to istio port 15053 and then istio might make an additional query to local resolver (53 port) if needed.

Firing up couple of tcpdumps for port 53 and port 15053 we noticed that whenever we saw resolution errors we could only see a packet going directly to the local resolver (169.254.20.10) and nothing on 15053 port of istio. That explained the resolution errors since local resolver doesn't know anything about endpoints from different clusters.

Next we enabled verbose logging in istio for the DNS parts (`dns:debug`).
The logging stream was really big but we managed to verify that when we see resolution failures we don't see any requests in the logs of istio, which in theory prints all requests and answers it served.

What we tried after that is to add LOG to iptables (nat table in the beginning) of istio-proxy using nsenter from the instances to see if we see any packets that don't match the REDIRECT rule and just go to the local resolver instead of the istio.
Surprisingly for the cases that we get resolution errors we couldn't see any logged packet, but for the cases where we got a legit response we were able to see the packets logged in /var/log/kern.log

In order to make sure packets hit iptables we added a LOG rule in the raw table of iptables, that everything should be available. In there we were able to see the logged packets, so packet that resolution was failing did reach iptables.

As can be seen from this picure https://stuffphilwrites.com/wp-content/uploads/2014/09/FW-IDS-iptables-Flowchart-v2019-04-30-1.png before a packet traverses the nat table, the conntrack table will be consulted. So if we have an entry in conntrack with same tuple (protocol, srcIP, srcPort, dstIP, dstPort) the packet will follow the route that the packet that created this entry took.

So in our case what I think we hit is that a UDP packet for a DNS request has a conntrack entry that the decision is to go to the node local dns server and then another packet with same tuple comes which is supposed to go the istio's DNS but because tuple is the same it goes to node local dns. And then the node local dns doesn't know any answer.
An example of couple of conntrack entry might help
```
udp      17 83 src=100.96.126.31 dst=169.254.20.10 sport=51692 dport=53 src=169.254.20.10 dst=100.96.126.31 sport=53 dport=51692 [ASSURED] mark=0 use=1
```
where `100.96.126.31` is pod's IP, `169.254.20.10` is the local node dns.
If a new UDP packet comes from the pod (istio container, or app container) if it has same source port (51692), no further NAT manipulation will happen but it will use the decision was taken for the existing packet. So if the packet that created the entry was sent to node local dns, the new packet will do the same without going through the DNAT rule that exist in `nat` table to redirect it to the istio's DNS.

The chances to have this are higher with the amount of DNS requests we do, since more UDP packets will exist and the probability to pick an ephemeral port that already exists in conntrack table rises.

One thing that we tried and helped the situation a bit but not solved is to change kernel options
```
sysctl -w net.netfilter.nf_conntrack_udp_timeout=1
sysctl -w net.netfilter.nf_conntrack_udp_timeout_stream=1
```
which basically removes the udp entries from conntrack faster so we don't have probabilities to pick a sport that exists.
Ofcourse this comes with downsides.

Do you guys think this is a valid theory? Has anyone else experienced this problem and how they have solved? If that's the case and we indeed hit this case with the conntrack what are the solution you see for multi cluster support?

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.1
control plane version: 1.9.5
data plane version: 1.9.5 (191 proxies)

kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.10

```
**How was Istio installed?**
istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Wow, excellent debugging! If I am understanding right it seems like this could actually apply to standard envoy iptables capture as well, not sure the dns aspect? Or is it udp specific?

We may try lowering net.ipv4.ip_local_port_range to be very small to trigger this easier for testing possibly?

**Comment by howardjohn** [comment]
cc @ramaraochavali @stevenctl

**Comment by astrikos** [comment]
> If I am understanding right it seems like this could actually apply to standard envoy iptables capture as well, not sure the dns aspect? Or is it udp specific?

I think due to the nature of UDP it's more obvious for it. In TCP the ephemeral port can't be reused immediately because after everything is done, socket is in TIME_WAIT mode, and there is a `net.netfilter.nf_conntrack_tcp_timeout_time_wait=120` timeout that it waits before reusing this port. But in UDP that doesn't apply so after packet is sent the ephemeral port is up for grabs.

>We may try lowering net.ipv4.ip_local_port_range to be very small to trigger this easier for testing possibly?

Now that you mention this, it's something that we also tried. To make this range bigger, so we have more ports but we didn't see much improvement.

If you guys have any ideas, we are happy to work with you and make tests for you, if it helps speeding up the debugging and coming up with a solution.

**Comment by howardjohn** [comment]
I was able to reproduce it pretty easily I think. Just ran `dnsperf -d /tmp/se -c 100 -n 10000 -s  10.96.0.10 -p 53`, once with an input like `unknown.host A` and once with an input like `known.host A`. If you just run the known.host one, it works fine - all requests ONLY go to the agent. if you run the unknown host one first, requests go upstream and then some requests start to fail

**Comment by howardjohn** [comment]
Can you try out https://github.com/istio/istio/pull/33480? And thanks again for your excellent debugging here!

**Comment by astrikos** [comment]
>Can you try out #33480

Interesting idea to fix this!

If I understand this correctly it adds 3 new rules in `raw` table
So I did the following in a pod
```
ubuntu@x.x.x.x:~$ sudo nsenter -t <pid> -n iptables -t raw -L --line-numbers
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
1    CT         udp  --  anywhere             anywhere             udp dpt:domain owner GID match 1337 CT zone 1
2    CT         udp  --  anywhere             anywhere             udp dpt:domain owner UID match 1337 CT zone 1
3    CT         udp  --  anywhere             169.254.20.10        udp dpt:domain CT zone 2
```

Trying though from inside the app container things don't work
```
root@testubuntu:/# dig google.com
;; reply from unexpected source: 127.0.0.1#15053, expected 169.254.20.10#53

;; reply from unexpected source: 127.0.0.1#15053, expected 169.254.20.10#53

;; reply from unexpected source: 127.0.0.1#15053, expected 169.254.20.10#53


; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I might miss something, so I'll keep looking unless there is something obvious here that I am doing wrong

**Comment by astrikos** [comment]
Okay I think I figure this out, we miss some iptables rule in order the conntrack zone trick to work.

Before adding any conntrack zone rules we see the following conntrack events upon a DNS query like `dig +short thebeat.co`
```
    [NEW] udp      17 29 src=127.0.0.1 dst=127.0.0.1 sport=40474 dport=40474 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=40474 dport=40474
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=55045 dport=53 [UNREPLIED] src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=55045
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=39439 dport=53 [UNREPLIED] src=169.254.20.10 dst=100.96.94.222 sport=53 dport=39439
 [UPDATE] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=39439 dport=53 src=169.254.20.10 dst=100.96.94.222 sport=53 dport=39439
 [UPDATE] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=55045 dport=53 src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=55045
```
The actual packets we see in tcpdump are
```
08:48:57.166447 IP ubuntu.43640 > localhost.15053: UDP, length 51
08:48:57.166699 IP ubuntu.44706 > 169.254.20.10.53: 32031+ [1au] A? thebeat.co. (51)
08:48:57.167227 IP 169.254.20.10.53 > ubuntu.44706: 32031 1/0/1 A 162.159.134.42 (65)
08:48:57.167387 IP 169.254.20.10.53 > ubuntu.43640: 32031 1/0/1 A 162.159.134.42 (65)
```

Notice that 2 out of the 3 NEW conntrack entries are getting updated because the return packets are matched.

Now with adding the 3 iptables rules that https://github.com/istio/istio/pull/33480 adds we get the following conntrack events
```
    [NEW] udp      17 30 src=127.0.0.1 dst=127.0.0.1 sport=55097 dport=55097 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=55097 dport=55097
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=55823 dport=53 [UNREPLIED] src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=55823 zone=2
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=47306 dport=53 [UNREPLIED] src=169.254.20.10 dst=100.96.94.222 sport=53 dport=47306 zone=1
    [NEW] udp      17 30 src=169.254.20.10 dst=100.96.94.222 sport=53 dport=47306 [UNREPLIED] src=100.96.94.222 dst=169.254.20.10 sport=47306 dport=53
    [NEW] udp      17 30 src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=55823 [UNREPLIED] src=100.96.94.222 dst=127.0.0.1 sport=55823 dport=15053
```
As you see there is no update cause the last two entries which are the answers don't get marked in either conntrack zone, so the packet that return to dig doesn't have the right source and we get errors like `;; reply from unexpected source: 127.0.0.1#15053, expected 169.254.20.10#53`

So we need additional conntrack `CT` rules for incoming packets. I added the two additional rules in ipatbles
```
iptables -t raw -A PREROUTING -p udp --sport 15053  -j CT --zone 2
iptables -t raw -A PREROUTING -p udp --sport 53 -s 169.254.20.10/32 -j CT --zone 1
```
and I noticed one of the answers where matching an existing conntrack entry
```
    [NEW] udp      17 30 src=127.0.0.1 dst=127.0.0.1 sport=44352 dport=44352 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=44352 dport=44352
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=44782 dport=53 [UNREPLIED] src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=44782 zone=2
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=41332 dport=53 [UNREPLIED] src=169.254.20.10 dst=100.96.94.222 sport=53 dport=41332 zone=1
 [UPDATE] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=41332 dport=53 src=169.254.20.10 dst=100.96.94.222 sport=53 dport=41332 zone=1
    [NEW] udp      17 30 src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=44782 [UNREPLIED] src=100.96.94.222 dst=127.0.0.1 sport=44782 dport=15053
```
The last one that don't match it's because it's considered packet that goes out so we need one more `OUTPUT` rule.
So by adding `iptables -t raw -A OUTPUT -p udp --sport 15053 -j CT --zone 2` we see
```
    [NEW] udp      17 30 src=127.0.0.1 dst=127.0.0.1 sport=38041 dport=38041 [UNREPLIED] src=127.0.0.1 dst=127.0.0.1 sport=38041 dport=38041
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=39826 dport=53 [UNREPLIED] src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=39826 zone=2
    [NEW] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=40807 dport=53 [UNREPLIED] src=169.254.20.10 dst=100.96.94.222 sport=53 dport=40807 zone=1
 [UPDATE] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=40807 dport=53 src=169.254.20.10 dst=100.96.94.222 sport=53 dport=40807 zone=1
 [UPDATE] udp      17 30 src=100.96.94.222 dst=169.254.20.10 sport=39826 dport=53 src=127.0.0.1 dst=100.96.94.222 sport=15053 dport=39826 zone=2
```
and `dig` is now happy with the answer.

In summary adding these 3 rules (on top of the ones added in https://github.com/istio/istio/pull/33480)
```
iptables -t raw -A PREROUTING -p udp --sport 53 -s 169.254.20.10/32 -j CT --zone 1
iptables -t raw -A PREROUTING -p udp --sport 15053  -j CT --zone 2
iptables -t raw -A OUTPUT -p udp --sport 15053 -j CT --zone 2
```
our iptables `raw` table now looks like
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
CT         udp  --  anywhere             anywhere             udp spt:15053 CT zone 2
CT         udp  --  169.254.20.10        anywhere             udp spt:domain CT zone 1

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
CT         udp  --  anywhere             anywhere             udp dpt:domain owner UID match 1337 CT zone 1
CT         udp  --  anywhere             anywhere             udp dpt:domain owner GID match 1337 CT zone 1
CT         udp  --  anywhere             169.254.20.10        udp dpt:domain CT zone 2
CT         udp  --  anywhere             anywhere             udp spt:15053 CT zone 2

```
and this seems to fix the initial problem. In my tests I don't see any NXDOMAIN responds any more :tada: 

My iptables skills are not great so there might be a simpler way to do that. 
@howardjohn @ramaraochavali @stevenctl if you have any suggestions/feedback/concerns on the fix please chime in.

@howardjohn would you have some time to see this? I can also take over the PR if you think that will help speed up the fix.
If there is anything else I can help to make this move forward let me know.

**Comment by howardjohn** [comment]
Nice! Feel free to take over the PR, or I will add you as a co-author on the commit since you did most of the work :slightly_smiling_face: . If you don't, I should be able to get to it early this week.

Would be great if anyone with more experience here has suggestions for simplification though since this is pretty complicated - I haven't seen anything simpler though.

**Comment by astrikos** [comment]
>Nice! Feel free to take over the PR, or I will add you as a co-author on the commit since you did most of the work slightly_smiling_face . If you don't, I should be able to get to it early this week.

cool I'll try to get something by tomorrow

>Would be great if anyone with more experience here has suggestions for simplification though since this is pretty complicated - I haven't seen anything simpler though.

I agree, it's not the most trivial thing. Feel free to tag anyone you feel has more experinece with iptables. In the meantime I will try to look around if we can do something more elegant in terms of rules.

**Comment by astrikos** [comment]
Alright PR is ready https://github.com/istio/istio/pull/33572
After some fiddling I ended up with these rules
```
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination
1    CT         udp  --  169.254.20.10        anywhere             udp spt:domain CT zone 1

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
1    CT         udp  --  anywhere             anywhere             udp dpt:domain owner UID match 1337 CT zone 1
2    CT         udp  --  anywhere             anywhere             udp dpt:domain owner GID match 1337 CT zone 1
3    CT         udp  --  anywhere             anywhere             udp spt:15053 owner UID match 1337 CT zone 2
4    CT         udp  --  anywhere             anywhere             udp spt:15053 owner GID match 1337 CT zone 2
5    CT         udp  --  anywhere             169.254.20.10        udp dpt:domain CT zone 2```

I add here as well a graph that can help grasping the whole flow inside the zones easier
![conntrack](https://user-images.githubusercontent.com/1355590/122954436-b96a7080-d37f-11eb-8013-e664d9801402.jpg)

Let me know what you guys think! (maybe in PR as well)

**Comment by ramaraochavali** [comment]
Closing this as this is already implemented.
