### ISSUE TITLE
Add integration tests for external istiod

### ISSUE THREAD

**Issue by ericvn** [istio/istio#33476]
**Describe the feature request**

Create integration tests for an external control plane and remote clusters for promotion of external istiod to beta.

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by zhlsunshine** [comment]
Hi @ericvn & @GregHanson, shall we move this issue to 1.12?
