### ISSUE TITLE
Locality weighted distribution does not work with outlier detection

### ISSUE THREAD

**Issue by smakam** [istio/istio#33470]
Hi
I have configured locality weighted distribution and it works fine based on the percentage distribution. When there is a failure, I do not see the traffic is getting sent to the other region. It seems like outlier detection is not working with locality weighted distribution. I see regular locality based failover working without weighted distribution.
Following is a sample destination rule I used:

_apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: eu-frontend-weight
spec:
  host: whereami-frontend.frontend.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: "*"
          to:
            "us-central1": 100
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 5s_

Thanks
Sreenivas

**Comment by hzxuzhonghu** [comment]
Isn't it expected? The setting means all traffic from any region goes to `us-central1`.

**Comment by smakam** [comment]
In the default scenario where there is no failure in us-central1, its expected that all traffic go to us-central1. When there is a failure in us-central1, I am expecting the traffic to failover to other region. Isn't that the reason that we are specifying outlier detection?

**Comment by hzxuzhonghu** [comment]
Distribution is used to satisfy cases when the source and servers are not evenly scheduled. You should specify locality failover in this case.

**Comment by smakam** [comment]
I needed a usecase like this:
Have 1 service as Active and another as Standby and when Active fails, I wanted Standby to takeover. Is there a way to achieve this?
I was thinking to use weighted distribution with failover, but the failover part does not seem to be working. Maybe, this is not the right usecase for this.

**Comment by hzxuzhonghu** [comment]
Locality failover should work well for this.

**Comment by smakam** [comment]
This is what I tried with Locality failover:
External -> Load balancer -> Istio ingress(region US) -> service
                                             -> Istio ingress(region EU) -> service

With locality based load balancing:
When traffic comes from external world to US region, traffic stays within US.
When traffic comes from external world to EU region, traffic stays within EU.

When traffic comes from EU, traffic does not get routed to US which is what I want in A/S configuration where all traffic has to go to primary site and then get switched over only when there is a failure. 

I was hoping that having weighted distribution with outlier detection based failover can solve my usecase. But outlier detection does not seem to work with weighted distribution.
