### ISSUE TITLE
about the pilot cost the time of init push context is too long

### ISSUE THREAD

**Issue by jjy96** [istio/istio#33485]
we use 1.9 pilot. 
we have 10w+ workloadentry, when we restart pilot. pilot complete init push context will cost 26 minute, so what we can do.

**Comment by jjy96** [comment]
i trace the func callback, and i found this func cost too long time
and when we start, this func will callback repeat, so init context time is so long

![image](https://user-images.githubusercontent.com/38353946/122340104-6f931c00-cf74-11eb-980c-febeea844653.png)
![image](https://user-images.githubusercontent.com/38353946/122340131-77eb5700-cf74-11eb-9c76-634793acb760.png)

**Comment by silenceshell** [comment]
Would you help to calculate the time used by `sortServicesByCreationTime` ?

```
	allServices := sortServicesByCreationTime(services)
```

And also the time used for get all workload entries from k8s [here](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L705)

```
	// Third, refresh workload entry
	wles, err := s.store.List(gvk.WorkloadEntry, model.NamespaceAll)
	if err != nil {
		log.Errorf("Error listing workload entries: %v", err)
	}
```

**Comment by howardjohn** [comment]
Attaching proof would be great https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

**Comment by jjy96** [comment]
> Would you help to calculate the time used by `sortServicesByCreationTime` ?
> 
> ```
> 	allServices := sortServicesByCreationTime(services)
> ```
> 
> And also the time used for get all workload entries from k8s [here](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L705)
> 
> ```
> 	// Third, refresh workload entry
> 	wles, err := s.store.List(gvk.WorkloadEntry, model.NamespaceAll)
> 	if err != nil {
> 		log.Errorf("Error listing workload entries: %v", err)
> 	}
> ```

ok，wait for a moment

**Comment by jjy96** [comment]
> Attaching proof would be great https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

ok

**Comment by jjy96** [comment]
and i have a another question。i found the crd client use one gorotuine handle all the crd resource，when crd resource is many，would this lead performance problem？

why not every crd use privite queue，and use gorotuines parallel processing

![image](https://user-images.githubusercontent.com/38353946/122496181-e9cbab00-d01d-11eb-8919-4b35bb26409a.png)

![image](https://user-images.githubusercontent.com/38353946/122496197-efc18c00-d01d-11eb-8cce-fc59818f35bf.png)

**Comment by jjy96** [comment]
> Attaching proof would be great https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

gorotuine
[gorotuine.result.zip](https://github.com/istio/istio/files/6674241/gorotuine.result.zip)

cpu
[pprof.samples.cpu.001.pb.gz.zip](https://github.com/istio/istio/files/6674242/pprof.samples.cpu.001.pb.gz.zip)

mem
[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz.zip](https://github.com/istio/istio/files/6674243/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz.zip)

**Comment by jjy96** [comment]
> Would you help to calculate the time used by `sortServicesByCreationTime` ?
> 
> ```
> 	allServices := sortServicesByCreationTime(services)
> ```
> 
> And also the time used for get all workload entries from k8s [here](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L705)
> 
> ```
> 	// Third, refresh workload entry
> 	wles, err := s.store.List(gvk.WorkloadEntry, model.NamespaceAll)
> 	if err != nil {
> 		log.Errorf("Error listing workload entries: %v", err)
> 	}
> ```

this is my log:
![image](https://user-images.githubusercontent.com/38353946/122504083-18508280-d02c-11eb-91e1-b8be8c025d95.png)

and cost time:
![image](https://user-images.githubusercontent.com/38353946/122504126-2f8f7000-d02c-11eb-9ee0-64619dc249c0.png)
![image](https://user-images.githubusercontent.com/38353946/122504143-3cac5f00-d02c-11eb-8621-2c0a52f50dda.png)
![image](https://user-images.githubusercontent.com/38353946/122504186-58176a00-d02c-11eb-8714-1f86b5e95233.png)
![image](https://user-images.githubusercontent.com/38353946/122504220-69607680-d02c-11eb-83ca-0219d3d1741d.png)

list workload entry cost time:
![image](https://user-images.githubusercontent.com/38353946/122504263-8301be00-d02c-11eb-9031-8e219b424cd1.png)

**Comment by jjy96** [comment]
> > Would you help to calculate the time used by `sortServicesByCreationTime` ?
> > ```
> > 	allServices := sortServicesByCreationTime(services)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And also the time used for get all workload entries from k8s [here](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L705)
> > ```
> > 	// Third, refresh workload entry
> > 	wles, err := s.store.List(gvk.WorkloadEntry, model.NamespaceAll)
> > 	if err != nil {
> > 		log.Errorf("Error listing workload entries: %v", err)
> > 	}
> > ```
> 
> this is my log:
> ![image](https://user-images.githubusercontent.com/38353946/122504083-18508280-d02c-11eb-91e1-b8be8c025d95.png)
> 
> and cost time:
> ![image](https://user-images.githubusercontent.com/38353946/122504126-2f8f7000-d02c-11eb-9ee0-64619dc249c0.png)
> ![image](https://user-images.githubusercontent.com/38353946/122504143-3cac5f00-d02c-11eb-8621-2c0a52f50dda.png)
> ![image](https://user-images.githubusercontent.com/38353946/122504186-58176a00-d02c-11eb-8714-1f86b5e95233.png)
> ![image](https://user-images.githubusercontent.com/38353946/122504220-69607680-d02c-11eb-83ca-0219d3d1741d.png)
> 
> list workload entry cost time:
> ![image](https://user-images.githubusercontent.com/38353946/122504263-8301be00-d02c-11eb-9031-8e219b424cd1.png)

unit is second

**Comment by jjy96** [comment]
i konw why cost so many time, becase serviceentry , not workloadentry
when pilot restart, every serviceEntryHandler will call maybeRefreshIndexes, leade serviceentry will cost 0.5~1 second

![image](https://user-images.githubusercontent.com/38353946/122509040-a2511900-d035-11eb-9635-61a6fea9e724.png)

**Comment by jjy96** [comment]
i just motify that to asynchronous processing, and restart time cost less than one minute. but i do not know this would lead what probelm?

this is demo for serviceEntryHandler
![image](https://user-images.githubusercontent.com/38353946/122510394-14c2f880-d038-11eb-9ec0-e99bba546dba.png)
![image](https://user-images.githubusercontent.com/38353946/122510411-21475100-d038-11eb-8d86-2b7d389e8363.png)

**Comment by silenceshell** [comment]
Are those service entries and workload entries in the same namespace? (or in a few namespaces)
I check your pprof and find that `IsSupersetOf` costs quite a lot of time.  PR #33515 may reduce that, but I am not sure how much it will resolve your problem.

**Comment by jjy96** [comment]
> Are those service entries and workload entries in the same namespace? (or in a few namespaces)
> I check your pprof and find that `IsSupersetOf` costs quite a lot of time. PR #33515 may reduce that, but I am not sure how much it will resolve your problem.

in the same namespace. 
and i think,  when pilot restart, every serviceEntryHandler will call maybeRefreshIndexes is the problem. so it can be asynchronous? will resolve the problem.

**Comment by silenceshell** [comment]
It is better to split service entries(and workload entries related) to different namespaces.
According to [here](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L691), if they are in the same namespace, it will be 2,000 * 100,000 calls of `IsSupersetOf` totally in every `maybeRefreshIndexes`. 
If we split service entries to 2,000 namespaces, that will only be 100,000 calls of `IsSupersetOf` totally in every `maybeRefreshIndexes`, as there is only one service entry in the namespace of the workload entry.

I am not sure whether it works or not to call `maybeRefreshIndexes` async, it seems that it has a full lock. 
```
func (s *ServiceEntryStore) maybeRefreshIndexes() {
	// We need to take a full lock here, rather than just a read lock and then later updating s.instances
	// otherwise, what may happen is both the refresh thread and workload entry/pod handler both generate their own
	// view of s.instances and then write them, leading to inconsistent state. This lock ensures that both threads do
	// a full R+W before the other can start, rather than R,R,W,W.
	s.storeMutex.Lock()
	defer s.storeMutex.Unlock()
```

**Comment by jjy96** [comment]
ok, i understand. thank you very much
