### ISSUE TITLE
How to specify the different format of accesslog for specific workloads?

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#33511]
Currently, the format of accesslog definition is in `MeshConfig` which is widely config in whole mesh for all workloads. Sometimes, we want to change the format of accesslog for specific workloads. I didn't find any way to solve my issue. There is an annotation named `proxy.istio.io/config` can be used for configuring specific workloads. Unfortunately, the format for accesslog is not defined in `ProxyConfig` struct.

Maybe we can design more annotations within workload to target this case, such as `proxy.istio.io/accesslogencoding`, `proxy.istio.io/accesslogformat`。When envoy connects to istiod, we caculate the final meshconfig for every envoy based on the meshconfig of istiod and the annotations provided by envoy.

CC @howardjohn @hzxuzhonghu

**Comment by howardjohn** [comment]
This will be part of the new Telemetry api in ~1.11 hopefully. cc @douglas-reid

**Comment by douglas-reid** [comment]
Not stale. Please take a look at the draft pr: https://github.com/istio/api/pull/2094

**Comment by SpecialYang** [comment]
> Not stale. Please take a look at the draft pr: [istio/api#2094](https://github.com/istio/api/pull/2094)

Great 🤩. Looking forward to this feature.
