### ISSUE TITLE
Run IST0139 before install

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33537]
```
istioctl x revision tag set default --revision=foo
istioctl install
```

Will result in conflicting webhooks. We run IST0139 to detect this if you do the other order, but we should detect it in `install` as well to prevent this

**Comment by akshitgrover** [comment]
@howardjohn 
I'd like to take this up
I am fairly new to the source code, I might need some help along the way

**Comment by howardjohn** [comment]
Great! I think we just need to equivalent of https://github.com/istio/istio/blob/b18a9b08f9fda5463c2bd33afa44130dfd222f58/istioctl/cmd/tag.go#L354 called somewhere in the `istioctl install` path. Conceptually should be pretty simple, but getting all the right data in the right place in the code may not be trivial

**Comment by akshitgrover** [comment]
I actually saw this code snippet before.
Let me understand the flow here and I'll check with you here if any doubts
Thank you

Should this issue be assigned to me or there is no need?

**Comment by akshitgrover** [comment]
Hi @howardjohn 

I did some code digging in last 2 days

The way I understand it

`istioctl x revision tag set default --revision=foo`
Analyses and deploys template [istio-control/istio-discovery/mutatingwebhook.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml)

`istioctl install`
Mutating webhook which is to be analysed is deployed as part of [Pilot component](https://github.com/istio/istio/blob/master/operator/pkg/translate/translate.go#L119) which also uses the same chart as used by above command but unlike it, The whole chart is deployed rather then just the mutating webhook, [istio-control/istio-discovery](https://github.com/istio/istio/tree/master/manifests/charts/istio-control/istio-discovery)

The way this whole chart deployment pans out is, A merged YAML will be constructed by appending all the templates present in helm chart and that file is then deployed. This is how it's done for all the components, Logic is part of helm [reconciler](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L149) which in turn calls [RenderCharts](https://github.com/istio/istio/blob/09e92989c7eb965bbf24e0a15fa47d46cc010678/operator/pkg/helmreconciler/render.go#L27) and [renderManifest](https://github.com/istio/istio/blob/master/operator/pkg/component/component.go#L352) function called for each component.

So, To analyse the mutating webhook to be deployed as part of Pilot component
Approach which I am thinking is, We get the MutatingWebhookConfiguration from the merged YAML once it is rendered (We get this as part of [manifestMap](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L153))

Once we have the webhook configuration as a YAML string, We can just use the same logic used in revision command
WDYT?

**Comment by howardjohn** [comment]
Sounds great!

fyi @Monkeyanator

**Comment by akshitgrover** [comment]
I am thinking of adding a method with the [HelmReconciler](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L51) as receiver, Which will give us a particular YAML file from the merged YAML file of the component.
This would make this method available for more generic use cases than just what we are trying to achieve

Will raise a PR by tomorrow
Just wanted to update on the approach

**Comment by ramaraochavali** [comment]
@howardjohn We configure additional webhook with the same config but with a different name prefixed with `z-` so that we can make holdApplicationProxy reorder container at the end? Otherwise we have few other webhooks in the chain that modify container order and that functionality not working. Can we drive this by a flag so that we can turn it off? Any other suggestions?
cc: @deveshkandpal24121990

**Comment by howardjohn** [comment]
Hmm.. does `--force` override it? I guess you probably don't want to override *every* error though.

So you are intentionally having 2 istio webhooks? Why not just have a single `z-` prefix one?

**Comment by ramaraochavali** [comment]
> .. does --force override it? I guess you probably don't want to override every error though.

I saw the --force but yeah. We do not want to override every error 


We had to do both because another webhook adds volume mounts for proxy container and that runs before z- and after the istio - So we had to run both.
