### ISSUE TITLE
Istio-Proxy cannot request resources due xdsproxy ResourceExhausted gRPC error

### ISSUE THREAD

**Issue by sergeydeg** [istio/istio#33549]
**Bug description**
After major network failure Istio-Proxy cannot acquire configuration from IstioD.

Around 12 AM our engineers switched network devices causing K8s HA Masler NLB gone.
As a consequences K8s worker nodes cannot comunicate with masters and publish node statuses.
Istio-proxy starting receiving errors like: 
`warn    xdsproxy    downstream terminated with unexpected error rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9430200 vs. 4194304) ` with increasing message size on each request.
After NLB has been put into operational again around 7:36 AM and cluster state synchronized, Istio-Proxy still got this errors until all pods was restarted.

As seen in first image Istio-Proxy finally can communicate with proxy, all tokens was refreshed.
Our cluster size around 150 services backed by 250 PODs.

![istiod-tokenExp](https://user-images.githubusercontent.com/6221680/122785348-fa994c80-d2bb-11eb-9db7-44b69e3d95cd.png)

![istio-proxy_ResourceExhausted](https://user-images.githubusercontent.com/6221680/122785470-169cee00-d2bc-11eb-87c2-396399903aac.png)

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Cluster functional after restoring main network communication.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.9.1
Kubernetes 1.20

**How was Istio installed?**
with Istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**

Onpremise cluster based on Ubuntu 20.04 with Calico CNI

**Comment by howardjohn** [comment]
This should be fixed on latest 1.9: https://github.com/istio/istio/issues/31904#issuecomment-832067735

Basically after N errors in a row (for you triggered by downtime), we get the "received message larger than max" which never recovers

**Comment by sergeydeg** [comment]
@howardjohn thanks for reply.
is there plans to release v1.9.6 soon with this changes incorporated?

**Comment by howardjohn** [comment]
This week

**Comment by howardjohn** [comment]
Closing as this is fixed a few versions back. if you see it on other versions _please_ open a new issue and mention me. Thanks!
