### ISSUE TITLE
about the pilot receive the conn, buf maybe serviceentry callback not complete

### ISSUE THREAD

**Issue by jjy96** [istio/istio#33543]
use release-1.9

if pilot can receive the conn, need two condition. one is the, informer has sync, another is the push_context all commited.

but if the serviceentry is too many, we will cost many time when the list obj callback complete over. in this case, if client connect pilot quickly, we maybe cannot  calculate the DiscoveryServer.EndpointShardsByService over. so the client can not get the all endpoint.

is this expect? 

<img width="925" alt="企业微信截图_8c81e365-bb9f-4b1a-b4d9-12f0fa2b2d8c" src="https://user-images.githubusercontent.com/38353946/122744303-71354a80-d2ba-11eb-9e5e-7c7b0297b69c.png">

this is service/pod run, they have SyncAll, but ServiceEntry do not have
![image](https://user-images.githubusercontent.com/38353946/122751360-3f27e680-d2c2-11eb-8722-99edec1fec6c.png)
![image](https://user-images.githubusercontent.com/38353946/122751377-43ec9a80-d2c2-11eb-9546-a317cd087d7f.png)

**Comment by stevenctl** [comment]
For k8s resources, we don't get good ordering on the initial sync, so we do this SyncAll to make sure it happens in the right order. 

For CRs, we don't have such a requirement. We just make sure everything that was enqueued up until the first informer sync has been processes. @hzxuzhonghu was working on this area recently, may have more detail.

**Comment by jjy96** [comment]
the order you said is the order that first handle node, and handle the service?
and CR have refresh func maybeRefreshIndexes, so it can handle the data, even the workloadentry handle first
did I describe it right？

but another question, even the CR handle order is correct, it can not handle complete, when the conn arrive. so envoy can not fetch the full data, maybe serviceentry callback do not complete
