### ISSUE TITLE
sidecar.istio.io/inject: "false" on pod with namespace injection enabled still injects sidecar

### ISSUE THREAD

**Issue by skk2142** [istio/istio#33555]
**Bug description**
I was under the impression that in a namespace with injection enabled, the pod level annotation still takes precedence. So in production namespace, I have automatic injection enabled using the label
```
NAME         STATUS   AGE   LABELS
production   Active   19d   istio-injection=enabled
```
I want to disable injection in one specific pod. I use the following annotation on the pod
```
annotations:
   sidecar.istio.io/inject: "false"
```
However the sidecar is still injected. 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.10.1
control plane version: 1.10.1
data plane version: 1.10.1 (22 proxies)
```
```
Client Version: v1.19.11
Server Version: v1.19.10-gke.1600
```

**Comment by howardjohn** [comment]
I cannot reproduce. Are you sure the annotation is on the pod, not the deployment?

**Comment by skk2142** [comment]
Ahh never mind....I had two of my own containers in my pod :)
