### ISSUE TITLE
[1.9.1 multicluster] when remote kube-api server is down, istiod fails to start

### ISSUE THREAD

**Issue by samene** [istio/istio#33564]
**Bug description**

I have a multi-cluster istio deployment (Multi-Primary on different networks). There is one cluster that we call the "central" cluster and all the others are "edge" clusters. Central cluster needs to reach all the edge clusters and every edge cluster only needs to reach the central cluster.

In my central cluster I have created the secrets for the edge cluster kubeconfigs, configured the istiooperator etc. and everything works fine.

One day one of my edge clusters kube api server went down and so the server configured in the ```istio-remote-secret-<clustername>``` of the central cluster was no longer reachable. 
After that there was a restart of the istiod pod on the central cluster. Since then the istiod pod is not able to start.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
If the remote cluster is down, it should not affect the other clusters.

**Steps to reproduce the bug**
To reproduce this bug you can edit the remote secret of any working multicluster setup to point to some invalid URL and restart the istiod pod.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio 1.9.1
kubernetes 1.20

**How was Istio installed?**

Istio Operator

**Comment by howardjohn** [comment]
This is already fixed in a later 1.9.x version, please upgrade: https://github.com/istio/istio/pull/31876. Thanks!

**Comment by samene** [comment]
verified working in 1.10.1.
