### ISSUE TITLE
What is comparable version of istio for AKS 1.19.11

### ISSUE THREAD

**Issue by vowne** [istio/istio#33577]
Went through multiple article and couldn't find a better answer for my query.

Would like to know what version of istio need to be required for AKS 1.19.11.

We will be going for AKS upgrade from 1.18.14 to 1.19.11.

Since istio current version is 1.7.3 which version 
should go for istio to compatible with 1.19.11??

Is there any documents to upgrade istio version in AKS

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases describes supported Kubernetes versions

**Comment by vowne** [comment]
@howardjohn  Thanks for your quick help.  So hope we can directly upgrade from Istion 1.7 to latest version 1.10 ( currently our AKS is of version is1.18.14 and planning to upgrade to 1.19.11 )
Also would like to know how istio image can be pulled from our private ACR repo than the dockerhub ( We have private ACR registry inplace, however its noticed that Istio is pulling image from docker.io, wehich is not a trusted registry of Azure Security Center as per the policy set in our environment, we are getting lot of security vulnerability alerts due to this.
 Secondly, looking to remediate the container previlege escalation related to istio, as istio containers are running as root user. Our application containers are running as non root user and because of Istio we are getting the pod itself vulberable.

So would like to know if we can get rid of the above 2 vulnerability alerts when we go for Istio upgrade. Will this latest version will have solution inbuilt for this or during upgrade can we remediate these by any chance?
