### ISSUE TITLE
How to get started with discoverySelectors

### ISSUE THREAD

**Issue by skk2142** [istio/istio#33586]
I was trying to use discovery selector to reduce the load on proxies. All my workloads with sidecar live in the production namespace with istio-injection=enabled label. Istio gateway proxy lives in the istio-system namespace along with the `Gateway` resource to configure listeners on the istio-gateway proxy. The gateway routes traffic to the workloads in the production namespace and a few other namespaces which do not have envoy proxy running as sidecar. When I used discoverySelector mesh config with one selector 
```yaml
  discoverySelectors:
    - matchLabels:
        istio-injection: enabled
```
I expected the routing to keep working. However, I noticed that all the listeners on the gateway envoy proxy got removed, so I started getting 500 for every exposed service. Was it because I was not including the `istio-system` namespace in discovery selector? Also, I wonder how to route traffic from the gateway to services in namespaces other than production which do not have discovery enabled?

**Comment by howardjohn** [comment]
@harveyxia

**Comment by harveyxia** [comment]
@skk2142 Another user [confirmed on the istio community slack](https://istio.slack.com/archives/C38CF1PEC/p1624265248235700) that he had to include `istio-system` for his gateways to have routing information.

This behavior suggests that the set of envoy proxies connected to istiod's xds server is somehow dependent on the services, endpoints, and/or pods known by the service registry. I'm not familiar with how Istio's xds server manages the list of active envoy proxy connections. @howardjohn any insights here?

**Comment by howardjohn** [comment]
Probably its not getting any ServiceInstances for itself. I think ALL istio proxies must be included in discoverySelectors for things to work

> The gateway routes traffic to the workloads in the production namespace and a few other namespaces which do not have envoy proxy running as sidecar. 

Those need to be in discovery selector as well.

**Comment by skk2142** [comment]
I see so it seems like it's either watch all services in a namespace or none situation because the discovery selector is at the namespace level. It'd be great a feature if discovery selector allowed for watch specific services in a namespace.

**Comment by harveyxia** [comment]
To add some more context, an envoy proxy *must be associated with a known service* in order for config to be pushed to it ([reference code here](https://github.com/istio/istio/blob/f401b494bfa956990cabe61a2c501fd0ccb0d3af/pilot/pkg/model/context.go#L804)).

So with the current system behavior, the namespaces of all gateways, and more generally the namespaces of any client proxies, need to be included in discovery selectors for them to have envoy config.

We can either keep the behavior and add documentation to clarify. Alternatively, we could modify istiod such that client proxies can be sent envoy config without themselves having to be associated with a discovered service (but I don't know how much work this would entail, any other related concerns, etc.)

**Comment by skk2142** [comment]
A common use case is a cluster has one namespace where user applications are running and they use istio proxy. There are other namespaces that have services that I want to expose to the outside world (like prometheus, tekton, argo cd etc) but I do not run proxies in them. So I'd want the discovery selector to select the namespaces where my application is running and discover other services like prometheus dashboard for the istio gateway. A service level discovery selector for istio gateway could be a great feature.

**Comment by esnible** [comment]
Would it be possible to write an analyzer so `istioctl analyze` could warn that a `discoverySelector` is unmatched?  Should we?  Currently we have nothing that checks the MeshConfig.

**Comment by howardjohn** [comment]
I am not sure how we can tell what discoverySelector is supposed to select
though? It's up to the user.
