### ISSUE TITLE
Customize and fix the event queue in k8s (pilot too slow for 200 services)

### ISSUE THREAD

**Issue by costinm** [istio/istio#3359]
When adding 200 services to the mesh, pilot gets overwhelmed - memory jumps up, etc.

We need to make the event queue customisable and find some values that allow it to scale to ~1000 services as defaults. If the queue gets too large - it may be worth dropping it and reading directly 
from k8s.

To test/repro, one option is to use:
   kubectl create ns istio-test
   helm template tests/helm --set testHub=$HUB --set testTag=$TAG $v | istioctl \
        kube-inject --debug --hub $HUB --tag $TAG -f - | $apply

(or istioctl genconfig )

It helps to run 'top' on the pilot node (ssh to the gcp machine or minikube ). For minikube it helps to run with "--memory 16384 --cpus 4", similar alloc for k8s.

**Comment by kyessenov** [comment]
Can you run pperf under load and collect the CPU chart? It looks like you have some reproducible set-up.

**Comment by costinm** [comment]
I have - but it would help if more people would have similar setups.

Based on logs and the 5GB of RAM - it is likely to be a memory not CPU issue, and so
far getting hperf was tricky and spotty.

**Comment by costinm** [comment]
To clarify - I'm currently working on other aspects of this problem, the goal is to have 
some fix before next Fri ( for 0.6 ) - increasing the throttle on the queue seems the simplest
solution. It is clear that many events are going in and a lot of allocations happen for each event.

If you have better options that can be done with low disruption and in the given time - even better, 
but I don't see any reason not to allow the queue to be more customisable and test its behavior with
larger number of changes.

**Comment by mandarjog** [comment]
@cheftako This is the issue I was talking about.

services, endpoints, pods and nodes are watched along with certain CRDs.
 https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller.go#L72

**Comment by kyessenov** [comment]
The culprit is the cost of computing Envoy xDS responses. It's too expensive to warrant 1s refresh delay across Envoys in a cluster. We need to slow it down, with a simple workaround of setting multi-minute poll refresh interval.

**Comment by mandarjog** [comment]
Can you put some info here re: time spent / cpu used etc computing the response?

The new Pilot data structures should help here, so will simply scaling number of pilot instances.

**Comment by kyessenov** [comment]
I've tested kubernetes backend on thousand services with no detectable
problems. So the bottleneck is likely the config generation function. The
data structures do not really help there since it's mostly processing rules
and RDS/LDS. The cost of v1alpha2 is unknown.

**Comment by costinm** [comment]
Kuat has other priorites, assigned to Martin.

The bug can be reproduced on a test cluster with envoy proxies running - standalone pilot has a rate limitter and will not show any problems unless it's hit by envoy at a high rate.

As the bug suggest, the rate limit has a big impact - I removed it and the startup time (for 300 services)
went from 100 to 4 seconds. Will work to Martin to make it configurable and test more - it appears that 
a simpler/faster approach is to get rid of the rate limit on events, and instead add a delay/throttle on clear cache, so if clear cache is called too often we want to skip some events. I can try something simple - but 
maybe just removing the throttle will solve our problems.

**Comment by hklai** [comment]
Is this really release blocking? Is anyone actively working on this?

**Comment by costinm** [comment]
I have been working on it - all 3 related PRs are in and they appear to
help.

I'm not sure how much soak / stability testing has been done for 0.6,  and
if it is bug-free,
but if other bugs are found to justify a rebuild or cherry-picks - we
should include this.

**Comment by hklai** [comment]
@costinm  When were the 3 PRs merged? I don't seem to see them linked from this.

And are these more PRs on the horizon?

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/3477
https://github.com/istio/istio/pull/3506
https://github.com/istio/istio/pull/3508

More PRs in 0.7.

**Comment by costinm** [comment]
Closing, this appears to be fixed now.
