### ISSUE TITLE
After configure a PeerAuthentication without destionationRule, I receive 200 or 503 when i request from sleep to httpbin

### ISSUE THREAD

**Issue by zhengtianchi** [istio/istio#33591]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
After configure a PeerAuthentication without destionationRule, I receive 200 or 503 when i request from sleep to httpbin.
sleep and httpbin both have istio-proxy, And, I'm using the examples provided by the authorities.

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I hope i can receive only 503 or 200 when i request from sleep to httpbin after configure a PeerAuthentication without destionationRule

**Steps to reproduce the bug**

firstly, I applied the following application:
```
kubectl create ns foo
kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n foo
kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n foo
kubectl create ns bar
kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n bar
kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n bar
kubectl create ns legacy
kubectl apply -f samples/httpbin/httpbin.yaml -n legacy
kubectl apply -f samples/sleep/sleep.yaml -n legacy
```
secondly, I applied PeerAuthentication for workload httpbin in foo namespace
```
cat <<EOF | kubectl apply -n foo -f -
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "overwrite-example"
  namespace: "foo"
spec:
  selector:
    matchLabels:
      app: httpbin
  mtls:
    mode: DISABLE
EOF
```
thirdly, I made requests from sleep to httpbin several times.The results are as follows:
```
$ for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec "$(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name})" -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 200   # here is 200
sleep.foo to httpbin.bar: 200
sleep.foo to httpbin.legacy: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 200
sleep.bar to httpbin.legacy: 200
sleep.legacy to httpbin.foo: 200
sleep.legacy to httpbin.bar: 200
sleep.legacy to httpbin.legacy: 200

$ for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec "$(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name})" -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503  # here is 503
sleep.foo to httpbin.bar: 200
sleep.foo to httpbin.legacy: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 200
sleep.bar to httpbin.legacy: 200
sleep.legacy to httpbin.foo: 200
sleep.legacy to httpbin.bar: 200
sleep.legacy to httpbin.legacy: 200

$ for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec "$(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name})" -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 200  # here is 200
sleep.foo to httpbin.bar: 200
sleep.foo to httpbin.legacy: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 200
sleep.bar to httpbin.legacy: 200
sleep.legacy to httpbin.foo: 200
sleep.legacy to httpbin.bar: 200
sleep.legacy to httpbin.legacy: 200

$ for from in "foo" "bar" "legacy"; do for to in "foo" "bar" "legacy"; do kubectl exec "$(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name})" -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503  # here is 503
sleep.foo to httpbin.bar: 200
sleep.foo to httpbin.legacy: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 200
sleep.bar to httpbin.legacy: 200
sleep.legacy to httpbin.foo: 200
sleep.legacy to httpbin.bar: 200
sleep.legacy to httpbin.legacy: 200
```

You can see that 200 and 503 are alternating

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
k8s:v1.18.2
istio:v1.9.2

**How was Istio installed?**
istioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
OS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by zhlsunshine** [comment]
I can reproduce this case based on above description, looking into it

**Comment by zhlsunshine** [comment]
BTW, one more question to @zhengtianchi :
What's your purpose for adding this PeerAuthentication policy?  As you know, it's a firmed response code(such as 200) if you remove this policy.

**Comment by zhlsunshine** [comment]
One more question to @zhengtianchi :
What's your purpose for adding this PeerAuthentication policy?  As you know, it's a firmed response code(such as 200) if you remove this policy.

**Comment by zhengtianchi** [comment]
> One more question to @zhengtianchi :
> What's your purpose for adding this PeerAuthentication policy? As you know, it's a firmed response code(such as 200) if you remove this policy.

I want to test this configuration and verify how it is applied in production.So,it is just a test.

**Comment by howardjohn** [comment]
Auto mtls doesn't handle workloadSelector. See https://github.com/istio/istio/issues/32788, I think this is essentially a duplicate of that. Thanks!

**Comment by zhengtianchi** [comment]
> Auto mtls doesn't handle workloadSelector. See #32788, I think this is essentially a duplicate of that. Thanks!

Thank you for your reply

**Comment by incfly** [comment]
Close as the mentioned issue. This is being fixed though.
