### ISSUE TITLE
502 errors with Knative and Istio Mesh

### ISSUE THREAD

**Issue by mhenke1** [istio/istio#33616]
**Bug description**

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

Hello,

we are facing a problem that seems to be related to Istio Mesh.
Our use case is to run Knative services. Only after enabling Istio Mesh we see a lot of 502 error which we do not see in the same scenario without the Mesh. The errors seem to be related to the fact that inflight requests are ungracefully terminated when service pods are scaled down and removed.
We tried to influence the problem with setting the `terminationDrainDuration` to a higher value , but against our expectations we see no consistent improvements.

Our questions would be whether there are more settings we could try to gracefully handle open connections or other ways to get insight in the deletion flow. Maybe you could also point us to the code that handles the SIGTERM signal.  Any thought would be welcome.

Could there be a way to check in a preStop-Hook whether there are still open requests against the proxy ?

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio:
client version: 1.8.2
control plane version: 1.9.1-rc5
data plane version: 1.9.1-rc5 (23 proxies)

Kubernetes:
Client Version: v1.21.0
Server Version: v1.20.7+IKS

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM IKS

**Comment by silenceshell** [comment]
Maybe related #33043 
Would you please try 1.10.1?

**Comment by mhenke1** [comment]
We see the same problems with  1.10.2

Interestingly we found out that we can remove all 502 errors by configuring Istio peer authentication as PERMISSIVE (in opposite to the STRICT setting we used before)
