### ISSUE TITLE
can we upgrade istio to latest patch of next minor version?

### ISSUE THREAD

**Issue by vowne** [istio/istio#33617]
From the IStio docs i understood that we can upgrade istio to only next minor version and cant skip any version in between .. So what about patches ? somwhere i read that we have to first upgrade to initial release of the next minor version
  for example.

Our current istio version is 1.7.3.

so what will be the possible version for upgrade? i know its 1.8.x

but its should be 1.8.0 or latest patch of 1.8.x ?

**Comment by bianpengyuan** [comment]
You can directly upgrade to latest patch version and that is recommended. the initial version typically has bugs which are fixed in latest patch versions. 

Closing as this is answered. Thanks!
