### ISSUE TITLE
Web Socket connection getting closed 

### ISSUE THREAD

**Issue by anannaya** [istio/istio#33613]
We are using istio 1.9.3 , We enabled debug logs for istio-proxy sidecar  whenever after new listener config load connections are getting drained. 
 After the below log we see websocket disconnect
 
 ```
021-06-23T10:54:05.796256Z debug envoy config removing draining listener: name=10.3.145.86_4194, hash=7697804453189935468, address=10.3.145.86:4194
 got postStop: 561548d5-f98f-46df-bf20-077f3f3b6fce, cleaning up registry...notifs-85dcb6d677-gwfngJun 23rd, 16:24:06.357
```

**Comment by anannaya** [comment]
Changed KeepAliveMaxServerConnectionAge to 24h , that's solved the issue. Just wanted is there any alternative way or side effects of this change?

**Comment by jordan-da** [comment]
@anannaya how long did the connection remain open for before being closed?
