### ISSUE TITLE
How to identify what method we followed for istio installation and get the same settings for upgrade

### ISSUE THREAD

**Issue by vowne** [istio/istio#33615]
Hi Experts,

I am very new to ISTIO and  would like to get clarified with my following doubts.

We are planning to upgrade Istio version from 1.7 to 1.8 in our AKS cluster of 1.18.14 in our production

But I am not sure about the  proper method of upgrade to follow in production since there are multiple m,ethods are given by Istio.

I dont have any clue about the how the curent istio setup is done in my environment and what profilesettings we used  as its done long before. Is there any method to export all the existings setting (the one currently running) and do the upgrade

So I am looking for a production ready approach to upgrade Istio with all existing settings in placed.

**Comment by esnible** [comment]
If you installed using _istioctl_ do `kubectl -n istio-system get iop` to get the configuration used to do the install.

You can then feed that back into Istio, for example

```
kubectl -n istio-system get iop installed-state-install -o yaml
istioctl install --dry-run -f /tmp/iop.yaml
```

(Remove the `--dry-run` to actually install)

**Comment by vowne** [comment]
@esnible thanks for your quick guidance. What i understood from your answer that..
 
 -> we can convert the iop details which we are getting from the command "kubectl -n istio-system get iop" to a yaml file.
-> and use the same yaml file to flag to the istioctl install command

Is this method can be applied for Production enviroment? Because Istio is offering multiple ways to upgrade, not sure which one should select

have few doubts on this that... we are not looking for install from a existing configuration, but looking to upgrade the version.

**Comment by vowne** [comment]
@esnible When we tried to do canary model upgrade, we are getting below error.

./istioctl8 install --set revision=1-8 --set profile=default -f /home/admin/upgrade/iop.yml
Error: failed to get profile and enabled components: failed to read profile: unknown field "telemetry" in v1alpha1.IstioComponentSetSpec:

Where the /home/admin/upgrade/iop.yml is the exported iop installed-state yaml file from the existing istio version 1.73

kubectl -n istio-system get iop installed-state-install -o yaml > /home/admin/upgrade/iop.yml
