### ISSUE TITLE
Its dificult to uderstand Istio version compatibility with AKS version

### ISSUE THREAD

**Issue by vowne** [istio/istio#33641]
Its unclear about the version dependency between istio version and AKS version when we read from istio docs or from microsoft docs.

As per the site [isto](https://istio.io/latest/docs/releases/supported-releases/), its telling that istio 1.7 supports only kubernetes versions [1.16, 1.17, 1.18], and for istio 1.8 [kubernetes -1.16, 1.17, 1.18, 1.19].

But as per the Microsoft docs, [AKS](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux)

> The Istio 1.7.x releases have been tested by the Istio team against Kubernetes version 1.16+.

So here its not clear that whether any AKS version higher than 1.16.x is compatible for istio 1.7.3?

Just to clear that, if we Upgrade AKS version 1.19.x, whether it will be compatible for istio 1.7.3?

**Comment by bianpengyuan** [comment]
Istio.io is authoritative re compatibility between Istio and k8s. Please upgrade istio before upgrading k8s.

**Comment by vowne** [comment]
@bianpengyuan .. Sorry that i didnt get you completely. Could you give some more details. 
So you meant to say, Istio 1.7.3 is not compatible for AKS 1.19.x and we would first upgrade istio to 1.8 before AKS upgrade from 1.18.14 to 1.19.11 ?

**Comment by bianpengyuan** [comment]
> @bianpengyuan .. Sorry that i didnt get you completely. Could you give some more details.
> So you meant to say, Istio 1.7.3 is not compatible for AKS 1.19.x and we would first upgrade istio to 1.8 before AKS upgrade from 1.18.14 to 1.19.11 ?

Yes

**Comment by vowne** [comment]
@bianpengyuan thanks for confirming.. closing the issue
