### ISSUE TITLE
Istio URI match with Rewrite

### ISSUE THREAD

**Issue by forumsheth15** [istio/istio#33667]
**Getting 404 error when Virtual service with multiple URI match and rewrite URL created.
Below is the example.
We have one microservice A, we want whenever there is any call to https://hostName/serviceA/ it should get overwrite with https://hostName/ and whenever there is any call to
https://hostName/serviceA/scheme/default/ it should get overwrite with https://hostName/scheme/default
But whenever we hit https://hostName/serviceA/scheme/default/ it gives a 404 error and we can see from the developer's tool that the request goes to /serviceA//scheme/default/
But all request sent to https://hostName/serviceA/ gets 200 response.**

[ ] Docs
[ ] Installation
[X] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Below is the snippet of Virtual Service**

> 

    name: service-A
    match:
    - uri:
        prefix: /serviceA/
      ignoreUriCase: true
    rewrite:
      uri: /
    headers:
      request:
        add:
          Cache-Control: "max-age=0, no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "-1"
    corsPolicy:
      allowOrigins:
      - exact: "*"
      allowMethods:
      - POST
      - GET
      allowCredentials: true
    route:
    - destination:
        host: service-A
        port:
          number: 8080
    name: themes-service-A
    match:
    - uri:
        prefix: /serviceA/scheme/default/
      ignoreUriCase: true
    rewrite:
      uri: /scheme/default
    headers:
      request:
        add:
          Cache-Control: "max-age=0, no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "-1"
          add_header: "more_clear_headers server"
    corsPolicy:
      allowOrigins:
      - exact: "*"
      allowMethods:
      - POST
      - GET
      allowCredentials: true
    route:
    - destination:
        host: service-A
        port:
          number: 8080

**Steps to reproduce the bug**

**➜ kc version**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1600", GitCommit:"7b8e568a7fb4c9d199c2ba29a5f7d76f6b4341c2", GitTreeState:"clean", BuildDate:"2021-05-07T09:18:53Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
**➜ istioctl version**  
1.10.1
**➜ helm version**
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}

**How was Istio installed? ---> Uisng helm chart ---> https://istio.io/latest/docs/setup/install/helm/#installation-steps **

**Environment where the bug was observed (cloud vendor, OS, etc) --> AKS**

**Need your help to solve this issue**

**Comment by ognjen-it** [comment]
Bump 👍
