### ISSUE TITLE
Strange/invalid/numerical response flag 8388608

### ISSUE THREAD

**Issue by Stono** [istio/istio#33664]
**Bug description**
We observed a novel response flag recently, `8388608`.  This happened on a service which received a sudden spike in requests.

![image](https://user-images.githubusercontent.com/1486729/123642944-c83ba200-d81b-11eb-88d5-7cc10a1ccae4.png)

```
istio_requests_total{app="portal", destination_service="app.retailer-tools-portal-login.svc.cluster.local", destination_service_name="app", destination_service_namespace="retailer-tools-portal-login", destination_workload="retailer-tools-portal-login", destination_workload_namespace="retailer-tools-portal-login", job="envoy-stats", namespace="portal", pod="portal-6745b9b8bd-dmr8x", reporter="source", response_code="200", response_flags="8388608", source_app="portal", source_workload="portal", source_workload_namespace="portal"}
```

Obviously this isn't a valid envoy response flag.

It's also interesting that it appears to be 8MB (8 * 1024 * 1024)?

We've never seen this before our 1.10 upgrade.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Valid response flags

**Steps to reproduce the bug**
Unknown

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.1

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Likely response flag stringify function in istio/proxy is out of sync with upstream. I will update it.

**Comment by bianpengyuan** [comment]
Follow up issue to prevent future regression: https://github.com/istio/istio/issues/33678
