### ISSUE TITLE
Add warning when the Istio version is EOL

### ISSUE THREAD

**Issue by clsacramento** [istio/istio#33668]
**Describe the feature request**

I help a lot of people with Istio installation/configurations and often when they hit issues, I have to remind them that they are running an old version and advise them to see if they can reproduce the problem on a supported version.

I was wondering if it would be possible to be more proactive in warning users when the current control plane version is EOL. Perhaps that can be achieved with an analyzer, though it might be even better to add warning every-time istioctl is called.

**Describe alternatives you've considered**

I considered writing custom script to check periodically the current installed version against the content of https://istio.io/latest/news/ but the page format has largely changed so it seems that first we will need to expose an API endpoint to check status of specific release...

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by zhlsunshine** [comment]
Hi @clsacramento, for this requirement,  I think it might be a good choice to fetch the versions of all istiods in current mesh via `istioctl`, in fact, there is a command of istioctl which can support this: `istioctl experimental revision list`. Generally, you can check the versions of istio from `TAG` field. What do you think that?

**Comment by clsacramento** [comment]
Hi @zhlsunshine, 

I ran the command you suggested (see output below), but I do not see how does that help me. I can see which revisions are running on my cluster, how do I know if those revisions are EOL or still supported?

Ideally I would like users to be warned that their current versions are EOL, but it seems we first need to agree on the solution on how to check which versions are currently supported or not.

Thanks,

```
$ istio-1.10.1/bin/istioctl experimental revision list
REVISION  TAG      ISTIO-OPERATOR-CR                      PROFILE REQD-COMPONENTS
istio-195-2 default  istio-system/installed-state-istio-195-2 empty   base
                                                                  istiod
                                                                  ingress:istio-ingressgateway
istio-186-3 <no-tag> <no-iop>
default   <no-tag> <no-iop>
```

**Comment by zhlsunshine** [comment]
Hi @clsacramento,  I think you can use `istioctl x precheck` to verify if the Istio is EOL to your cluster. And here is the output for this command below:
```
$ istioctl x precheck
✔ No issues found when checking the cluster. Istio is safe to install or upgrade!
  To get started, check out https://istio.io/latest/docs/setup/getting-started/
```
As you can see, it's not easy for user to know more, and I agree with @clsacramento that this check should be periodically done. So @therealmitchconnors and @esnible any suggestion?  Thanks!

**Comment by therealmitchconnors** [comment]
Precheck does not inform users when their service mesh is EOL.  Instead, it let's them know if it is safe to upgrade their Istio installation to the version of istioctl.  This is useful for avoiding outages when upgrading from 1.9 to 1.10 for instance.

I like the idea of a supported version check that vendors may override.

**Comment by zhlsunshine** [comment]
Thanks @therealmitchconnors for your reply and recommendation on this, then @costinm could you please help to show your idea for us here? Thank you so much! ^_^
