### ISSUE TITLE
Add check to prevent proxy response flag out of sync with upstream

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#33678]
Istio proxy has a response flag parsing logic, which needs to keep in sync with set of response flags from the upstream https://github.com/istio/proxy/blob/3b13a598565c9af334859b1f8dab5b6e2570373e/extensions/common/util.cc#L25.

We need to add a presubmit check script into istio/proxy, which verifies the `LastFlag` is the same in [istio/proxy](https://github.com/istio/proxy/blob/3b13a598565c9af334859b1f8dab5b6e2570373e/extensions/common/util.cc#L69) and [envoyproxy/envoy](https://github.com/envoyproxy/envoy/blob/1aa65ac88e9888127fe795e3ecb4c1bbc36534bf/envoy/stream_info/stream_info.h#L92).  The script could be added [here](https://github.com/istio/proxy/tree/master/scripts) ([example]([url](https://github.com/istio/proxy/blob/master/scripts/check-repository.sh))) which simply seds the LastFlag in both files and verify they are the same.

**Comment by ChristophBleyer** [comment]
Hello 👋 I am new here and would love to implement this.

**Comment by bianpengyuan** [comment]
@ChristophBleyer That would be great! Let me know if you need any help.

**Comment by ChristophBleyer** [comment]
@bianpengyuan I had the time to look at it now. I have already added the script and linked the WIP PR. Please let me know if this solves the problem as intended.

I will now go ahead and look at how this script can be integrated into the build/release process.
