### ISSUE TITLE
TesLog fails race tests

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3371]
https://circleci.com/gh/istio/istio/29631

==================
--- FAIL: TestLog (0.63s)
    --- PASS: TestLog/No_log_info_for_msg_name (0.00s)
    	env.go:97: Starting TestLog/No_log_info_for_msg_name - test run. . .
    	env.go:97: Got an unknown instance of log: NO ENTRY. Hence Skipping.
    	env.go:97: Finished TestLog/No_log_info_for_msg_name - test run. . .
    --- FAIL: TestLog/All_Good (0.63s)
    	env.go:97: Starting TestLog/All_Good - test run. . .
    	env.go:97: Creating a new paper trail logger for url: localhost:6767
    	env.go:97: Finished TestLog/All_Good - test run. . .
    	testing.go:699: race detected during execution of test
	testing.go:699: race detected during execution of test

**Comment by andraxylia** [comment]
cc @girishranganathan

**Comment by andraxylia** [comment]
cc @costinm

**Comment by douglas-reid** [comment]
Can we close this issue?  Is it still recurring?

Running locally, I see:

```
$ go test --v ./mixer/adapter/solarwinds/...
...
=== RUN   TestNewLogger
=== RUN   TestNewLogger/All_good
--- PASS: TestNewLogger (0.00s)
    --- PASS: TestNewLogger/All_good (0.00s)
        env.go:97: Starting TestNewLogger/All_good - test run. . .
        env.go:97: Creating a new paper trail logger for url: hello.world.org
        env.go:97: Finished TestNewLogger/All_good - test run. . .
=== RUN   TestLog
=== RUN   TestLog/No_log_info_for_msg_name
=== RUN   TestLog/All_Good
--- PASS: TestLog (0.00s)
    --- PASS: TestLog/No_log_info_for_msg_name (0.00s)
        env.go:97: Starting TestLog/No_log_info_for_msg_name - test run. . .
        env.go:97: Got an unknown instance of log: NO ENTRY. Hence Skipping.
        env.go:97: Finished TestLog/No_log_info_for_msg_name - test run. . .
    --- PASS: TestLog/All_Good (0.00s)
        env.go:97: Starting TestLog/All_Good - test run. . .
        env.go:97: Creating a new paper trail logger for url: localhost:6767
        env.go:97: Finished TestLog/All_Good - test run. . .
PASS
ok      istio.io/istio/mixer/adapter/solarwinds/internal/papertrail     0.025s
```

**Comment by douglas-reid** [comment]
Looks like i forgot the `--race`. Now I see it.
