### ISSUE TITLE
Session on Istio architecture and implementation

### ISSUE THREAD

**Issue by sanjaysawant** [istio/istio#33730]
Hi @howardjohn, Actually it's not technical issue, I didn't find a way to approach you, hence creating ticket here, apologize for that. We are in need of one or more sessions on overall Istio architecture and it's implementation. We would also need  support as and when required. Could you please assist here? OR let us know the point of contact who can help us in this regard.

Regards,
Sanjay Sawant

**Comment by howardjohn** [comment]
Hi @sanjaysawant , https://istio.io/latest/about/ecosystem/#providers has a lsit of some providers that provide Istio support, training, etc. I suggest taking a look there. In the future you can direct questions to https://discuss.istio.io/ as well. Thanks

**Comment by sanjaysawant** [comment]
Thank you so much @howardjohn. This helps.
