### ISSUE TITLE
Massive test dumps resulting in out of memory on node disk

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33743]
```
$ gsutil du -sh gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232/
316.28 GiB   gs://istio-prow/pr-logs/pull/istio_istio/33483/integ-pilot-multicluster-tests_istio/1410018472557023232
```

This seems a bit excessive - it actually caused other jobs on the same node to fail as well

cc @stevenctl

**Comment by stevenctl** [comment]
This only happens when we have core dumps, right?

**Comment by howardjohn** [comment]
I believe you mentioned somewhere offline it was the core dumps. We get a lot of info from tests that fail a lot, but no where near 300gb like this one

**Comment by howardjohn** [comment]
duped of https://github.com/istio/istio/issues/33034
