### ISSUE TITLE
Add observability into connected clusters

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33799]
Currently, it can be hard to tell which clusters are connected when using multicluster. It would be great to have a way to see this. This could be debug endpoint and/or istioctl endpoint

Strawman UX:

```
$ istioctl clusters list
NAME            SECRET                 STATUS
cluster-123     cluster-123-secret      healthy
```

cc @stevenctl @esnible @nmittler

**Comment by stevenctl** [comment]
Any proposal for how we define `STATUS`? I can see SYNCING, SYNCED (actually just initial sync) and SYNC TIMEOUT but if our connection breaks afterward it gets tricky. 

We emit a metric now though `controller_sync_errors_total` (probably need to go back and add `pilot_`) that can be helpful. The [way we collect this](https://github.com/kubernetes/client-go/blob/6711973af1c55d544f08252297ebf6dab2031975/tools/cache/shared_informer.go#L169-L182) doesn't provide an equiv for finding out when it becomes "healthy" again though.

**Comment by howardjohn** [comment]
I didn't have any great ideas, just having two columns seemed a bit minimal so I threw in a third :slightly_smiling_face:. We can definitely leave it out if we dont have a a good way to measure it
