### ISSUE TITLE
Make auto mTLS work with workload selector peer authn

### ISSUE THREAD

**Issue by incfly** [istio/istio#33809]
**Describe the feature request**

Thanks to https://github.com/envoyproxy/envoy/issues/16536 being resolved, now we can revisit the known auto mTLS limitation around the workload peer authn. This used to be due to the fact that workload selector and upstream cluster mapping are not 1:1. Plus updating the endpoint label can't trigger data plane transport socket config updates.

But now given that limitation is resolved in Envoy, we should try to fix this, therefore users never need to set DetinationRule regardles what peer authentication policy is, even for [workload level peer authn](https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#enable-mutual-tls-per-workload). This can be achieved by:

1. We calculate the endpoints label, `tlsMode: istio` only when the endpoint has the sidecar & the peer authn policy says server side enables permissive or strict.
1. If a PeerAuthn in namespace `foo` is changed/added/deleted, we selectively pushed all the EDS belonging to the namespace `foo`.

Note that we still have to push all the EDS in namespace `foo`, this is because for a peer authn `selector: {env: prod}`, we don't know what set of the services in namespace foo will be affected. (unless there're some new optimizations in istiod that I'm not aware of).

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by incfly** [comment]
I will start a prototype recently. @howardjohn @hzxuzhonghu FYI Let me know what you think. thanks.

**Comment by howardjohn** [comment]
I have a prototype that I *think* was only missing the envoy PR. Not at my computer now to find the branch name but I can find it next week and send it. Happy to have someone take it over if anyone has time

**Comment by hzxuzhonghu** [comment]
>If a PeerAuthn in namespace foo is changed/added/deleted, we selectively pushed all the EDS belonging to the namespace foo.

You don't need to consider this, it has already been this.
