### ISSUE TITLE
How to rollback Istio  to the old control plane, instead of completing the canary upgrade?

### ISSUE THREAD

**Issue by vowne** [istio/istio#33822]
We were doing a test on Canary upgrade of our Istio setup from 1.7.3 to 1.8.6 version. 

So we installed canary version 1-8-6 for the istio controlplane and we mapped one namespace to the upgraded version. We tested the application and we were getting 200 response.

Everything was working as expected till this point. So in order to try a rollback, we just went to the document but the steps are not clear enough regarding the rollback. 

![image](https://user-images.githubusercontent.com/85581467/124391820-fbd66a80-dcfa-11eb-868b-652c0ee6a3c3.png)

What is the method to reinstall the gatway here? we used istioctl with overlay and default profile for v1.7.3 installation.  So here how to reinstall the gatway? 

After  uninstalled the canary version , the ingress gateway pods got removed and our application got down , getting 500 error.

So would like to clear about the exact process to rollback from cannary version to previous installed version. 
But due to some siisues, we want to rollback to previous vers

**Comment by chadlwilson** [comment]
I agree the docs could do with improvement.

In my project, where we use gateways managed alongside the controlplane we just re-apply the old version of code from our pipeline/deploy automation tool and scripting

i.e scripting (independent of version) for canary `X` -> `Y` does
1. use istioctl version `Y` to install canary control plane of version `Y` (upgrades gateways `X` -> `Y`)
2. for each istio injected namespace
    - label namespace with version `Y`
    - bounce deployments
 3. `istioctl uninstall x --revision=X` (nothing is using revision X anymore so should be safe)
 
 
 Thus a rollback is just re-running the old snapshot of code/config with the older istioctl corresponding to the "target revision". Regardless of where you got up to in the process, it will have the effect of ensuring gateways are on the target revision; ensuring all namespaces and deployments are on target revision, and uninstalling any unused control plane if necessary.
 
 So "reinstall the old gateways" as it mentions here is just "use pre-canary istioctl version and config to re-apply"
 
 However there is some scripting hijinx required to do this fully automated; detect failures etc.
 
 I believe another approach some people use is to manage gateways separately from the control plane by doing two istioctl installs, a second one using `profile=empty` with only gateway definitions in the `IstioOperator`). I haven't done this myself though.
