### ISSUE TITLE
Error when changing istio's default hub

### ISSUE THREAD

**Issue by ahmedTouati** [istio/istio#33834]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**I have pushed istio image (gcr.io/istio-release/pilot:1.7.3) to our private registry and used it to install istio using istioctl :

`istioctl install --set profile=minimal --set values.global.proxy.autoInject=disabled --set hub=our-private-registry/istio-release --set tag=1.7.3`

However in istiod log i see this error :

```2021-07-05T09:57:23.558592Z     error   Injection data: err=template: inject:144:7: executing "inject" at <gt .ProxyConfig.Concurrency 0>: error calling gt: invalid type for comparison spec=```
**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by kebe7jun** [comment]
can you please provide istioctl version by `istioctl version`?

you should use istioctl version 1.7.3 to install istio.

**Comment by ahmedTouati** [comment]
> istioctl version

@kebe7jun this is the output of `istioctl version` :
`
client version: 1.6.8
pilot version: 1.7.3
istiod version: 1.7.1
data plane version: none
`

**Comment by kebe7jun** [comment]
> > istioctl version
> 
> 
> 
> @kebe7jun this is the output of `istioctl version` :
> 
> `
> 
> client version: 1.6.8
> 
> pilot version: 1.7.3
> 
> istiod version: 1.7.1
> 
> data plane version: none
> 
> `

try to upgrade istioctl to 1.7.3, and reinstall.

**Comment by ahmedTouati** [comment]
> > > istioctl version
> > 
> > 
> > @kebe7jun this is the output of `istioctl version` :
> > `
> > client version: 1.6.8
> > pilot version: 1.7.3
> > istiod version: 1.7.1
> > data plane version: none
> > `
> 
> try to upgrade istioctl to 1.7.3, and reinstall.

Yes i did and it worked. Thanks a lot
