### ISSUE TITLE
metric classification feedback

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#33837]
**Bug description**

I've been playing with metrics classification lately and I just would like to share my experience with this feature so far.

1. To state the obvious: this feature is extremely useful 😊. Having the ability to customise and classify the prometheus label based on request/response attributes is very powerful. Thank you!  

2. Prometheus metrics pollution
    Enabling [custom metrics](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics) without adding the `sidecar.istio.io/extraStatTags` to all the sidecars leads to new metrics being generated (such as`envoy_request_operation___somevalue___istio_requests_total`). This is explained in the [classfiy-metrics](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/) docs but not in the  [custom metrics](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/) docs. It means that customising the metrics for a single application isn't really possible without generating more metrics in other sidecars. It's not clear from the docs if there is a way around it? except maybe enabling `extraStatTags` mesh wide 😢, and tolerate the new labels everywhere.
    
 3. Customising gateway metrics.
     It would be useful to document how to enable custom metrics for gateways. The `sidecar.istio.io/extraStatTags` doesn't apply to gateways because gateways are not using automatic sidecar injection. However adding the `ISTIO_METAJSON_ANNOTATIONS` environment variable does the trick 🤷 
     ```
     - name: ISTIO_METAJSON_ANNOTATIONS
          value: >
            {"sidecar.istio.io/extraStatTags":"foo,bar,baz"}
     ``` 

4. The example EnvoyFilter in the [classify-metrics docs](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/) has a matcher on the `1.9.*` proxyVersion. This is a minor thing, but it's not going to work with istio 1.10.
```
context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.9.*'
```

5. How to configure custom metrics for a single application?
   As mentioned before, adding a custom metrics dimension in the meshconfig will pollute every sidecar prometheus metrics.
   Would it preferable to use a custom envoy filter instead? something like this:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-metrics
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  # configure custom attributes
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.9.*'
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "istio.stats"
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.attributegen
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "attributes": [
                      {
                        "output_attribute": "istio_operationId",
                        "match": [
                          {
                            "value": "ListReviews",
                            "condition": "request.url_path == '/reviews' && request.method == 'GET'"
                          },
                          {
                            "value": "GetReview",
                            "condition": "request.url_path.matches('^/reviews/[[:alnum:]]*$') && request.method == 'GET'"
                          },
                          {
                            "value": "CreateReview",
                            "condition": "request.url_path == '/reviews/' && request.method == 'POST'"
                          }
                        ]
                      }
                    ]
                  }
              vm_config:
                runtime: envoy.wasm.runtime.null
                code:
                  local: { inline_string: "envoy.wasm.attributegen" }
  # configure custom dimensions
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.9.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "metrics": [
                      {
                        "name": "requests_total",
                        "dimensions": {
                          "request_operation": "istio_operationId"
                        }
                      }
                    ]
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound```
```

I hope this will be useful to someone 😉 . 

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
N/A

**Steps to reproduce the bug**
N/A

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```istio 1.9 / 1.10```

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
N/A
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by chaudyg** [comment]
I am wondering if we could remove the dependency on EnvoyFilters? Would we allow the configuration of the  `metrics` and `attributes`  via the `SideCar` object directly?

**Comment by bianpengyuan** [comment]
Thanks a lot for your feedback!

For 3, you can use extraStatsTags in proxyConfig, which provides ability to do gateway override via annotations (proxy.istio.io/config): https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

For 2 and 5 essentially are the same problem (i.e. workload level control on metric customization). We have a new Telemetry API, which will support metric customization at mesh/namespace/workload level (https://github.com/istio/api/commit/527b9df3805f973c2ef0651b075a055423ffdc82). It will ship at 1.11.

**Comment by bianpengyuan** [comment]
> I am wondering if we could remove the dependency on EnvoyFilters? Would we allow the configuration of the `metrics` and `attributes` via the `SideCar` object directly?

We can add request classification to the Telemetry API to get rid of EnvoyFilter. cc @douglas-reid

**Comment by chaudyg** [comment]
Thanks 👍 for the reply. Looking forward to trying out the new Telemetry API ☺️.

**Comment by douglas-reid** [comment]
NOTE: We don't currently have a plan to add request classification to the Telemetry API.  We need to decide if/how we want to expose that functionality.

**Comment by hollinwilkins** [comment]
Integrating the Telemetry API with OpenAPI and gRPC definitions could be an easy way to get started with generating `istio_operationId` at least, in an easy-to-configure way.
