### ISSUE TITLE
Support node local traffic routing 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#33849]
**Describe the feature request**

In k8s, users can specify routing traffic to node local endpoints via setting `InternalTrafficPolicy` = `Local`. In istio, we donot respect it. 

But node local traffic routing is required by many users. 

Options we can do:

1. directly use k8s api `InternalTrafficPolicy`, but requires Kubernetes 1.21
2. Support it via enhanced topology-aware load balancing.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
@howardjohn @ramaraochavali @stevenctl

**Comment by howardjohn** [comment]
I think we can do 1 and 2 both?
2 is technically just using an existing API in a new way, no special code changes

for 1 it's slightly different, it means we ONLY send local - no fail over at all

**Comment by nrjpoddar** [comment]
I agree with @howardjohn that we probably want to have both options in the long run
