### ISSUE TITLE
Multi-Primary multicluster

### ISSUE THREAD

**Issue by dimashenkov** [istio/istio#33848]
I have two clusters with istio 1.9.5 . When I configure Multi-Primary multicluster ,after execution of command `istioctl x create-remote-secret`, some of my apps like Kiali and Prometheus  get `Upstream connect error or disconnect/reset before headers`

**Comment by dimashenkov** [comment]
Anyone?

**Comment by stevenctl** [comment]
Sorry for the slow response on this. I'm pretty sure those specific apps should stay cluster-local. I'm assuming you followed the steps in https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/ for each cluster?

**Comment by dimashenkov** [comment]
> Sorry for the slow response on this. I'm pretty sure those specific apps should stay cluster-local. I'm assuming you followed the steps in https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/ for each cluster?

Yes I followed this doc
