### ISSUE TITLE
Potential networking issue with pods talking to external database on older version of istio running on k8s 1.19.

### ISSUE THREAD

**Issue by rushminatorr** [istio/istio#33863]
Our containers are unable to ping an external mongo database. The issue started happening suddenly for one of the running pods. Restarting the pod, could'nt get a ping back from cosmos and failed on timeout. It seems that existing  live connections, are okay and performing database transactions but if we restart a pod, it fails to connect to mongodb(managed service on Azure). 

Two days ago, we updated our k8s version from 1.18 to 1.19. The nodes were all updated and all pods restarted. We did not see this issue until this morning. 

Existing transactional error:
“server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongodb.documents.azure.com:10255, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : tls: first record does not look like a TLS handshake }, ] }”

If we reboot the pod, it fails the ping test and times out. 
```
func newDB(mongoDBConnectionString string) (*mongo.Client, error) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()
	logger.Info("Connecting to DB")
	clientOptions := options.Client().ApplyURI(mongoDBConnectionString).SetDirect(true)
	c, err := mongo.NewClient(clientOptions)
	if err != nil {
		return nil, fmt.Errorf("err at NewClient, %w", err)
	}
	err = c.Connect(ctx)
	if err != nil {
		return nil, fmt.Errorf("err at Connect, %w", err)
	}
	err = c.Ping(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("err at Ping, %w", err)
	}
	logger.Info("Connected to DB")
	return c, nil
}

```

**Environment Details**
*K8s*
Azure Kubernetes Service, version: 1.19.9 (Upgraded 2 days ago)
*Istio Version*
client version: 1.4.6
control plane version: 1.4.3
data plane version: 1.4.3 (69 proxies)

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

** Note: We are running an older version of Istio and understand it's no longer supported. We are hoping to get any information to help us get unblocked. Our istio usage is just for traffic routing and ingress gateway. We do not have any complex setup.

**Comment by howardjohn** [comment]
Unfortunately we do not have the bandwidth to support such old Istio versions, as it has been out of support for over a year, we have a lot of issues, and limited volunteers. Thanks!
