### ISSUE TITLE
question about crdclient do not handle DeletedFinalStateUnknown?

### ISSUE THREAD

**Issue by jjy96** [istio/istio#33867]
version: release-1.9

as we can see, when the curr obj is not runtime.Object, the onEvent do nothing just print log. but the obj can be DeletedFinalStateUnknown. for some case, it maybe lead problem. when watch fali. the mem data of pilot is variance for the data of k8s apiserver.

![image](https://user-images.githubusercontent.com/38353946/124703162-5d2d5200-df24-11eb-8294-0701064a4bfe.png)

**Comment by monsteredc** [comment]
I think it's been checked in line 47 `checkReadyForEvents`

**Comment by jjy96** [comment]
checkReadyForEvents just print log，do not handle
