### ISSUE TITLE
Additional labels to apply on the pod level for monitoring and logging needs

### ISSUE THREAD

**Issue by vedmichv** [istio/istio#33879]
**Describe the feature request**
Add labels on pod level for istio-operator and istiod. The additional labels might be required to configure logging and monitoring systems (fluentd as an example), based on pod's labels select list of pods to send logs/metrics. 
  
**Describe alternatives you've considered**
Add labels to pod can be added after deployment of istio, but that will not allow to set up gitops approach. As result, for example, ArgoCD will revert any changes\mutating those labels. 

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by jacob-delgado** [comment]
Closed by https://github.com/istio/istio/pull/34003/
