### ISSUE TITLE
Pilot should listen to all namespaces

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#339]

**Comment by andraxylia** [comment]
istio/manager#531

**Comment by ayj** [comment]
@andraxylia, can you provide more details on why #339 is blocked by by the current service discovery performance (i.e. https://github.com/istio/manager/pull/531)? In particular, what level of performance/scale would be sufficient to unblock this issue?

**Comment by andraxylia** [comment]
Envoy was crashing, we need to re-try with the latest code.

**Comment by debianmaster** [comment]
any updates on this feature?

**Comment by cmluciano** [comment]
@andraxylia Is this still blocked/do we have a targeted SLO that will enable us to proceed

**Comment by sakshigoel12** [comment]
@andraxylia please could you update this issue

**Comment by andraxylia** [comment]
On track.

**Comment by andraxylia** [comment]
Fixed in istio/pilot#951
