### ISSUE TITLE
Do we have a docker image versiond 1.9.6 and architecture is arm64

### ISSUE THREAD

**Issue by dsy3502** [istio/istio#33902]
Do we have a docker image versiond 1.9.6 and architecture is arm64

**Comment by chadlwilson** [comment]
I believe not currently, you probably want to follow https://github.com/istio/istio/issues/26652 which appears to be being worked on at the moment: https://github.com/istio/tools/pull/1346

**Comment by howardjohn** [comment]
+1, please follow https://github.com/istio/istio/issues/26652
