### ISSUE TITLE
External traffic telemetry

### ISSUE THREAD

**Issue by jgournet** [istio/istio#33922]
**Describe the feature request**
When an application makes an external call, the only metric incremented seems to be:
istio_tcp_connections_closed_total
(istio_requests_total should also be increased, but that does not seem to happen)
Disclaimer: this is based on my observations and this old blog: https://istio.io/latest/blog/2019/monitoring-external-service-traffic/

Would it be possible to populate more useful metrics (like istio_request_duration_milliseconds_bucket for example) ?

**Describe alternatives you've considered**
Note: somehow, I can see that istio_request_duration_milliseconds_bucket is populated for a few external calls, but not all of them - I don't know what makes it so. Any explanation on that would be great as well

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
If the application originates TLS, proxy can only see opaque bytes and only TCP stats will be generated for those request.

**Comment by jgournet** [comment]
> If the application originates TLS, proxy can only see opaque bytes and only TCP stats will be generated for those request.

Indeed, that makes sense; and that's exactly what I would love to see in the "normal" metrics.
ie, using istio_request_duration_milliseconds_bucket as an example (that's the metric I'm interested in at the moment), I would love that metric to include those few TCP stats (bytes, response time, host); as at the moment, those external https calls are not even registered at all.
(hope it makes sense and it's not a silly impossible request)

Side note: just stumbled on https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/ , so I'll explore this now as a workaround in the meantime

**Comment by bianpengyuan** [comment]
istio_request_duration_milliseconds_bucket is only generated for HTTP request.

For TCP, you can only get sent/received bytes, and connection open/closed. TCP does not have a notion of response time. We do attach destination_service label to all tcp metrics, and it will be meaningful if your app call out matches a ServiceEntry instead of passthrough.

> Side note: just stumbled on https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/ , so I'll explore this now as a workaround in the meantime

You can probably try to add SNI to the metrics.

**Comment by jgournet** [comment]
> TCP does not have a notion of response time.

Probably the worst example I could come up with:
```
 {"authority":null,"route_name":null,"protocol":null,"response_code":0,"request_id":null,"duration":240088,"method":null,"upstream_transport_failure_reason":null,"bytes_sent":11715,"connection_termination_details":null,"start_time":"2021-07-08T23:45:19.413Z","upstream_host":"10.11.107.252:443","downstream_remote_address":"10.11.84.47:52878","path":null,"response_code_details":null,"requested_server_name":"sqs.ap-southeast-2.amazonaws.com","upstream_cluster":"outbound|443||sqs.ap-southeast-2.amazonaws.com","response_flags":"-","upstream_local_address":"10.11.84.47:52880","upstream_service_time":null,"user_agent":null,"x_forwarded_for":null,"downstream_local_address":"10.11.107.252:443","bytes_received":23257}
```
That's from the istio-proxy logs.
We do get a "duration" (that's where my example is the worst, since calls to SQS are long polling/streams ...), and that would be good enough for use
(we also do get bytes_received, bytes_sent, start_time and the DNS of the host - that's all we can get from https connections, but that would be great to be able to rely on normal istio metrics to have all the data. ie: when I graph istio_request_* I'd expect to see everything that goes through istio, even if data contains some "unknown" values)

> We do attach destination_service label to all tcp metrics, and it will be meaningful if your app call out matches a ServiceEntry instead of passthrough.

Yes, already doing that and that's great ;)

> istio_request_duration_milliseconds_bucket is only generated for HTTP request.

That's the "spirit" of this feature request: making istio_request_duration_milliseconds_bucket get TCP requests when possible (that's just a random example metric - we'd need to do that for all metrics ...)

**Comment by bianpengyuan** [comment]
> That's the "spirit" of this feature request: making istio_request_duration_milliseconds_bucket get TCP requests when possible (that's just a random example metric - we'd need to do that for all metrics ...)

Issue is for TCP connection, there is really no "request" or "response", so not possible to generate those stats.

**Comment by jgournet** [comment]
> Issue is for TCP connection, there is really no "request" or "response", so not possible to generate those stats.

Well, I understand your point, BUT: 
if envoy can log this:
```
{
  "authority": null,
  "route_name": null,
  "protocol": null,
  "response_code": 0,      <= we have a response code here
  "request_id": null,     <= we have a "request" here (ok, it's null - but that's fine)
  "duration": 240088,        <= that's super interesting for telemetry
  "method": null,
  "upstream_transport_failure_reason": null,
  "bytes_sent": 11715,     <= that's super interesting for telemetry
  "connection_termination_details": null,
  "start_time": "2021-07-08T23:45:19.413Z",     <= that's super interesting for telemetry
  "upstream_host": "10.11.107.252:443",
  "downstream_remote_address": "10.11.84.47:52878",
  "path": null,
  "response_code_details": null,
  "requested_server_name": "sqs.ap-southeast-2.amazonaws.com",      <= that's super interesting for telemetry
  "upstream_cluster": "outbound|443||sqs.ap-southeast-2.amazonaws.com",    <= that's super interesting for telemetry
  "response_flags": "-",
  "upstream_local_address": "10.11.84.47:52880",
  "upstream_service_time": null,
  "user_agent": null,
  "x_forwarded_for": null,
  "downstream_local_address": "10.11.107.252:443",
  "bytes_received": 23257      <= that's super interesting for telemetry
}
```
so, we **DO** have a response (it's "null") and a request (it's "null")
We also have a lot of interesting stuff for telemetry (service_name, duration, start_time, bytes_sent, bytes_received) <= why can't we get those in the normal telemetry ?

**Comment by bianpengyuan** [comment]
Bytes received and sent for TCP connection is tracked by istio metrics already: https://istio.io/latest/docs/reference/config/metrics/. Start time is tracked by connection open metric.

You can use customized metric feature to add server name and cluster name label to the metric if you want. Response code is not meaningful for TCP metric (it is probably always 0). Only thing that is missing and we probably could add is connection duration.

**Comment by jgournet** [comment]
> Bytes received and sent for TCP connection is tracked by istio metrics already: https://istio.io/latest/docs/reference/config/metrics/. Start time is tracked by connection open metric.

Well, that's the problem: those are not tracked in, at least, istio_request_duration_milliseconds
ie: I can see a few external calls in istio_request_duration_milliseconds, but the majority are not tracked in there (and I don't know what makes calls go in it and the opposite)

**Comment by bianpengyuan** [comment]
`istio_request_duration_milliseconds` is only tracked for HTTP request which the sidecar proxy can interpret (i.e. the request data from the app the the proxy is plain text).

If the app sends TLS, which means the sidecar do not know what is being sent over the connection at all, it cannot generate `request_duration`.

**Comment by jgournet** [comment]
> `istio_request_duration_milliseconds` is only tracked for HTTP request which the sidecar proxy can interpret (i.e. the request data from the app to the proxy is plain text).
> 
> If the app sends TLS, which means the sidecar do not know what is being sent over the connection at all, it cannot generate `request_duration`.

In my example, there is a "request duration" in TLS, which is logged by the side car itself.
So even if it's a TLS, there is some notion of request duration

**Comment by bianpengyuan** [comment]
Yeah, that is connection duration, which is not tracked as mentioned in https://github.com/istio/istio/issues/33922#issuecomment-877875921. We unlikely will track this via `istio_request_duration_milliseconds` as that is specifically used to track HTTP request duration. At best we will need to add a new metric to track TCP connection duration.

**Comment by jgournet** [comment]
> Yeah, that is connection duration, which is not tracked as mentioned in [#33922 (comment)](https://github.com/istio/istio/issues/33922#issuecomment-877875921). We unlikely will track this via `istio_request_duration_milliseconds` as that is specifically used to track HTTP request duration. 

Yes, that was the point of this feature request: make istio_request_duration_milliseconds (and others!) also track TLS connections on a best-effort basis. So that people using those metrics can actually expect to have every outbound connections in one graph; having said that:
> At best we will need to add a new metric to track TCP connection duration.

yes, yes yes :)  that's not as ideal as what I had in mind, but that would do the trick

**Comment by B1F030** [comment]
> At best we will need to add a new metric to track TCP connection duration.

@bianpengyuan Hi! Is this metrics implemented yet? or is it on the plan? we may need this, thanks!
