### ISSUE TITLE
Canary uninstall for CI processes

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#33936]
**Describe the feature request**
We are testing canary deployments and are looking for an automated way to uninstall the previous revision without deleting critical istio components like CRDs.

After searching through the docs, it appears the only way to uninstall a revision currently is to use the istioctl command
```
istioctl x uninstall --revision 1-6-5
```
Is there a way to generate yaml to uninstall a revision, or a helm chart that we can use in our CI process?

**Describe alternatives you've considered**
```
istioctl manifest generate --component .....
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by su225** [comment]
`istioctl manifest generate` also provides `--revision` flag.
