### ISSUE TITLE
How to configure egress gateway to connect to remote https server requiring ssl client certificate.

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#33939]
**Describe the feature request**

**Describe alternatives you've considered**

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

istio 1.9.5 

I am currently getting this error from the egress gateway:

[istio-egressgateway-bbc67cff6-xdj6p] {"response_code":0,"user_agent":null,"route_name":null,"bytes_received":0,"request_id":null,"response_code_details":"filter_chain_not_found","duration":0,"authority":null,"start_time":"2021-07-09T17:08:52.966Z","downstream_remote_address":"172.30.104.161:51860","x_forwarded_for":null,"requested_server_name":null,"bytes_sent":0,"path":null,"upstream_host":null,"connection_termination_details":null,"upstream_local_address":null,"upstream_cluster":null,"response_flags":"NR","upstream_service_time":null,"protocol":null,"downstream_local_address":"172.30.104.191:8443","method":null,"upstream_transport_failure_reason":null}

I have a gateway and a destination rule set in the istio-system namespace with the following:
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-imfmobileplatformdashboard-ng-bluemix-net
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - redacted_hostname
    tls:
      mode: MUTUAL
      credentialName: redacted_hostname # this must match the secret created earlier to hold client certs

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-mtls-for-imfmobileplatformdashboard
  namespace: istio-system
spec:
  host: redacted_hostname
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        credentialName: redacted_hostname # this must match the secret created earlier to hold client certs
        sni: redacted_hostname

apiVersion: v1
kind: Secret
metadata:
  name: redacted_hostname
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
        base64 encoded data
  tls.key: |
        base64 encoded data=
  ca.crt: |
        base64 encoded data

**Comment by su225** [comment]
Do you have the corresponding `ServiceEntry` defined with `redacted_hostname` as hostname. When you define a destination rule for a hostname Istio should "know" about the service. When the service is external, you do that with `ServiceEntry`. 

The error says "NR" meaning - No Route. It does not know about `redacted_hostname`. Take a look here - https://istio.io/latest/docs/reference/config/networking/service-entry/ . Define a `MESH_EXTERNAL` service with resolution `DNS` for the `redacted_hostname`. Also set port to 443/HTTPS.
