### ISSUE TITLE
Forward destination_service from source proxy

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#33940]
ref: https://github.com/kiali/kiali/issues/4137

When multiple services bind to the same port of the same workload, the destination proxy cannot tell what is the intended destination service of the request. Current behavior is that the destination proxy will just use the first service in the list based on order of creation time. This is not ideal and lead to disagreement between telemetry reported from source and destination proxy.

This can be achieved by extending metadata exchange filter, or some other mechanism such as upstream extension, which is used to forward destination port for BTS.

cc @kyessenov @lambdai @mandarjog @tbarrella

**Comment by jshaughn** [comment]
I would argue that this should move to P0.  Users have now reported two issues against the Kiali graph, with this being the root cause.  Would love to see this fix in the next release.

**Comment by ldemailly** [comment]
You can see reproduction yaml and details in https://github.com/kiali/kiali/issues/4366

**Comment by bianpengyuan** [comment]
not stable.

**Comment by jshaughn** [comment]
Hi @bianpengyuan , is this still something that will hopefully get a fix?

**Comment by bianpengyuan** [comment]
> Hi @bianpengyuan , is this still something that will hopefully get a fix?

Yeah, although this is not prioritized.. Hopefully this can be picked up one day.

**Comment by jshaughn** [comment]
Still hoping this gets addressed someday.

**Comment by ldemailly** [comment]
bump. any more details on how this information would be carried from source to destination proxies?

**Comment by jshaughn** [comment]
Still don't want this to be closed...

**Comment by ldemailly** [comment]
poke

**Comment by jshaughn** [comment]
-1 on closing.

**Comment by geowalrus4gh** [comment]
2-year-old valid problem! We are using argo rollouts for rolling out applications in a stable-preview (blue-green) fashion. When there is no new pod, stable service, and preview service just point to the stable pod. Only when a new preview comes up, do the stable service and preview service point to the stable pod and preview pod respectively. This is our deployment strategy and has been there in production for a long time. Istio is being evaluated for use in our production but this limitation prevents us from using Istio in production. 

Any workaround for this?

**Comment by keithmattix** [comment]
Sorry this thread hasn't gotten much traction. Ambient helps with this a bit because we have the underlying service in the authority header for HBONE. For sidecar, the destination sidecar only sees a pod IP; it has no way of knowing what requested it. @howardjohn are you aware of any way to persist this downstream metadata in connection attributes? I'm not aware of any

**Comment by howardjohn** [comment]
We do not have the service in the authority header but we could put it in another header

**Comment by geowalrus4gh** [comment]
we are waiting for ambient to go V1.

**Comment by howardjohn** [comment]
Ah forgot - in ztunnel we actually already pass this as `Forwarded`. see parse_forwarded_host in ztunnel and guess_inbound_service.

Envoy doesn't send or read it though
