### ISSUE TITLE
Improve iptables debugability

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33965]
* Iptables allows inserting comments (`--comment`) which can help explain why we have certain rules.
* Iptables allows inserting logs (`iptables -A INPUT -j LOG`, for example). This could be helpful to debug the flow of traffic. I don't think you can add a log a specific line, but for every rule we create we can make a log statement with the same match I think.

**Comment by howardjohn** [comment]
Like need `echo 1 | sudo tee /proc/sys/net/netfilter/nf_log_all_netns` to get logs in containers

**Comment by ramaraochavali** [comment]
Huge +1 for this

**Comment by howardjohn** [comment]
implementation idea:
* Setup a map of shortname -> long description.  example: comment gets `--comment "IPT001: redirect app calls back to self"`, log gets `--log-prefix "IPT001:".
* Each call to append a rule also (conditionally) adds a `-j LOG` rule before with the same match
* Each call has a `--comment` attached
* Likely need to better abstract iptables calls to do this. Probably useful for ipv4+ipv6 consistency anyways

**Comment by howardjohn** [comment]
```
	//if len(params) > 2 && params[len(params)-2] == "-j" {
	//	p := append([]string{"-A", chain}, params...)
	//	p = p[:len(p)-2]
	//	p = append(p, "-j", "LOG", "--log-uid", "--log-prefix", "istio\t")
	//	rb.rules.rulesv4 = append(rb.rules.rulesv4, &Rule{
	//		chain:  chain,
	//		table:  table,
	//		params: p,
	//	})
	//}
```

as a hack to AppendV4Rules actually works pretty well

**Comment by aojea** [comment]
@howardjohn small nit, the field is bounded  to 256 char ;)
```
comment

Allows you to add comments (up to 256 characters) to any rule.
--comment comment
Example:
iptables -A INPUT -s 192.168.0.0/16 -m comment --comment "A privatized IP block"
```
https://linux.die.net/man/8/iptables
