### ISSUE TITLE
unable to connect to in-mesh TCP ports using pod ip directly

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3398]
@terinjokes commented on [Wed Jan 03 2018](https://github.com/istio/issues/issues/150)

**Is this a BUG or FEATURE REQUEST?:**

BUG

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

Y

**Bug:**

I'm unable to connect to generic in-mesh TCP ports.

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```
Istio version: 0.4, installed from the "install" directory of istio/istio at the 0.4 tag.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**

Y

**What happened**:

A ClusterIP service was created with port name "tcp-test" pointing at deployments running a generic TCP service on the specified port. Connections from other containers in the Istio mesh were unable to connect to the TCP service.

There were no logs from any istio-proxy containers.

**What you expected to happen:**

TCP services were able to connect
  

---

@ldemailly commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355846159)

you have to use the release tar, not the source tree at the tag (the yaml in source tree were stale, now removed)
  

---

@terinjokes commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355861833)

@ldemailly Thanks. That change wasn't clearly communicated. Thanks for removing the files. I'll close this if using the release templates resolves the issue.

---

@terinjokes commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355864354)

@ldemailly There's no differences between what's in the 0.4 tarballs and what was in the repositories at the 0.4 tag.

---

@ldemailly commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355864990)

Ah you're right, somehow 0.4.0 was patched up 
unlike https://github.com/istio/istio/blob/0.3.0/install/kubernetes/istio.yaml#L261
for instance

but where did you get istioctl from ?
can you do
```
istioctl version
```
as well as
```
istioctl kube-inject -f any.yaml | grep Image
```

---

@terinjokes commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355865220)

I'm not using istioctl, I'm using the auto-injection initializer.

---

@ldemailly commented on [Sun Jan 07 2018](https://github.com/istio/issues/issues/150#issuecomment-355865752)

can you paste the output of
```
make -C samples/rawvm dump-images
```

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356059897)

```
      3 boostport/kubernetes-vault
      3 boostport/kubernetes-vault:latest
     14 busybox:1.27.2
[internal images omitted]
      1 docker.io/istio/istio-ca:0.4.0
      1 docker.io/istio/mixer:0.4.0
      1 docker.io/istio/pilot:0.4.0
      8 docker.io/istio/proxy:0.2.12
      1 docker.io/istio/proxy_debug:0.2.12
     22 docker.io/istio/proxy_debug:0.4.0
      8 docker.io/istio/proxy_init:0.2.12
     19 docker.io/istio/proxy_init:0.4.0
      1 docker.io/istio/sidecar_initializer:0.4.0
      2 gcr.io/google_containers/addon-resizer:1.0
      2 gcr.io/google_containers/explorer:1.0
      2 grafana/grafana:4.5.2
      1 istio/istio-ca:0.4.0
      1 istio/mixer:0.4.0
      1 istio/pilot:0.4.0
      8 istio/proxy:0.2.12
      1 istio/proxy_debug:0.2.12
     22 istio/proxy_debug:0.4.0
      8 istio/proxy_init:0.2.12
     19 istio/proxy_init:0.4.0
      1 istio/sidecar_initializer:0.4.0
      2 jaegertracing/jaeger-collector:0.9
      2 jaegertracing/jaeger-query:0.9
      4 lyft/envoy:0408b98cd2b150cb26e4b81844788c46059a2dfa
      2 openpolicyagent/kube-mgmt:0.4
      2 openpolicyagent/opa:0.5.12
      2 prom/statsd-exporter
      3 prom/statsd-exporter:latest
      1 prom/statsd-exporter:v0.5.0
      2 quay.io/coreos/grafana-watcher:v0.0.8
      2 quay.io/coreos/kube-state-metrics:v1.0.1
      2 quay.io/coreos/prometheus-operator:v0.15.0
     14 quay.io/pires/docker-elasticsearch-kubernetes:6.1.1
     12 quay.io/prometheus/node-exporter:v0.15.0
```

---

@ldemailly commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356069944)

somehow you have a bunch of 0.2.12 left

did you upgrade from 0.2.12 ? it seems like the upgrade didn't work

if you check which pods do have 0.2.12 and redeploy those, it should help

about NodePort specifically though, you need to use the svcIp, you can't use the nodeIp directly, is that how you connect ?

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356071769)

@ldemailly We're creating a new service and new deployments, so 0.2.12 sidecars shouldn't be part of the problem (the new deployments are getting 0.4 sidecars). We're rotating the remaining deployments, so that should clear up soon.

I'm attempting to connect to the Kubernetes Service IP created from a type: NodePort service.

---

@ldemailly commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356074701)

I assume you do have auth/mtls on ? any details on how it fails ? (connection closed ? hangs ? ...)

---

@ldemailly commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356075367)

I haven't personally tested TCP NodePort, though I believe it should work - can you try a regular TCP service first ? (that works and I personally tested it and we have the mysql/mongodb regression tests for those)
https://github.com/istio/istio/blob/master/samples/bookinfo/kube/bookinfo-mysql.yaml

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356137898)

@ldemailly My apologies, I see where some of the confusion here is coming from. On Friday I said "A NodePort service was created" when I meant "A ClusterIP service was created". I've corrected the issue.

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356161145)

@ldemailly It seems in this case, the multiple parts of the service are communicating over the Kubernetes Service IP long enough to exchange direct IP addresses. They then switch to attempting a connection directly to the pod IP.

My guess, since istio_proxy is silent, is that mTLS can't be established properly, and a proxy somewhere closes the connection.

Is mTLS supposed to handle this case?
  

---

@ldemailly commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356162352)

when you have the proxy injected all inbound traffic goes to the proxy

when you have mtls enabled, all traffic must present a certificate - and the outbound envoy capture makes it happen

but if you use the podip directly, instead of the clusterip, that traffic isn't processed properly as envoy looks at services (cluster ips)
  

edit: in theory envoy could find that is the case by checking the ip+port and reverse matching it to a service but it doesn't for now / this wasn't a need so far. I suggest you try to stick to svc ip ?

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356162925)

@ldemailly Yeah, that's the behavior we assumed and feared. :frowning: 

Unfortunately, this is behavior of the application we can't control. It will always attempt to switch to the pod IPs.

---

@ldemailly commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356163779)

how does it even know the podip ? maybe you can make whoever says that ip believe the pod's ip is the cluster ip ?

alternatively I think it should be possible to configure envoy to mtls secure pod-pod traffic within a k8s cluster maybe we can turn this into a feature request for pilot

@kyessenov, thoughts ? (and did I get the above mostly correct?)

---

@terinjokes commented on [Mon Jan 08 2018](https://github.com/istio/issues/issues/150#issuecomment-356164437)

@ldemailly The services use the service IP to coordinate, and part of that coordination is the pod IP.

In fancier terms: the application has a master election over the service IP, and then they attempt to connect to the elected master's IP address.

The service will only announce an IP address if it can bind to it, and the pod doesn't have the service's IP address in the network namespace.

---

@kyessenov commented on [Tue Jan 09 2018](https://github.com/istio/issues/issues/150#issuecomment-356412846)

I don't think we support mixed-case like this that uses both service VIP and pod IPs. 
For pure VIP case, we don't create separate TCP routes per each pod, as that has a potential to blow up the routing tables.
For pure pod IP case (called headless), we require that the service port be chosen as unique in the cluster. A route is created for that port (0.0.0.0:PORT) that lets traffic go passthrough. This is to support rich client libraries like the one for kafka, to do their own network functions (like LB).

---

@terinjokes commented on [Tue Jan 09 2018](https://github.com/istio/issues/issues/150#issuecomment-356415082)

@kyessenov It would be great if we could opt-in handling mixed cases like this: where only some subset of pods needs be mixed, and thus not every pod in the cluster needs the routing rule. One of our motivations for our move to Kubernetes is to avoid needing to allocate cluster-unique ports.

In the short-term, having the service working with some caveat is better than not working at all. I can create a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). Is the 0.0.0.0:PORT rule an Istio route rule?
  

---

@rlguarino commented on [Thu Jan 11 2018](https://github.com/istio/issues/issues/150#issuecomment-357043106)

Is this something that will be addressed in future releases of Istio? I'm trying to get Prometheus to work and having a tough time without disabling MTLS.

---

@terinjokes commented on [Tue Jan 16 2018](https://github.com/istio/issues/issues/150#issuecomment-358113163)

@kyessenov Do you mind expanding on your kafka example? I searched the issues in a couple Istio repos, and I haven't seem anything similar.

**Comment by evandigby** [comment]
I'm also hitting a wall trying to get Prometheus to scrape my deployments. It connects using pod IP directly. 

Has someone been able to establish a work-around? I haven't been able to find one in my search.

This one surprised me due to the prevalence of Prometheus in the k8s world, and the fact that Istio itself expresses it's metrics through Prometheus.

**Comment by rlguarino** [comment]
The workaround that I've been using it so expose Metrics on a debug port
that has MTLS disabled
<https://istio.io/docs/tasks/security/per-service-mtls.html#disable-mutual-tls-authentication-for-httpbin-service>.
We only ever access these ports directly (not through a LB or Service IP)
so disabling mtls wasn't a huge issue. I'm not sure if there's a new way to
do this now. I'd love to know as well.

**Comment by evandigby** [comment]
@rlguarino Thank you! My deployment doesn't have a service; however, I created one for the sole purpose of exposing Prometheus with MTLS disabled. That's worked around this for me. 

Ultimately our production requirements dictate that this too would be encrypted (our security requirements are substantial) but this will allow me to continue evaluating Istio for our needs. 

Thank you!

**Comment by evandigby** [comment]
@rshriram can you add some commentary on why this is closed?

**Comment by rshriram** [comment]
Sorry, i thought you said your issue was resolved
> Thank you! My deployment doesn't have a service; however, I created one for the sole purpose of exposing Prometheus with MTLS disabled. That's worked around this for me.

Either way, the solution as pointed out above is to use per-service mTLS. We are not exposing direct access to pod IP from a client's sidecar, due to scalability constraints..

**Comment by idoshamun** [comment]
Not sure I understand the solution.
I would like to provide a pod to pod communication for Akka cluster bootstrapping.

**Comment by yancl** [comment]
Yes, we have the same problem when we use prometheus to scrape metrics(business metrics, not service metrics) from pod directly, it just return 404(NOT FOUND) from the pod sidecar since we haven't exposed the metrics port to the service. 

Currently the workaround is that we almost expose the metrics port to every service to make it work, it looks not very ideal for this case. So, @rshriram, do you think the [passthrough](https://github.com/istio/istio/pull/8983) mechanism for **outbound** should work for **inbound** in this case ? thanks.

**Comment by yancl** [comment]
After some deeper thought, we think expose the pod metrics port to each service will double the dynamic listener and route entries from pilot(especially we have several hundreds of k8s services) and not very elegant(we should not expose metrics port to k8s service just for this purpose).

And then we have two basic ideas:
* custom the pod sidecar `static_resource` through pilot template to let each sidecar forward metrics request(`/metrics` for example) to pod business container through localhost(like `/stats/prometheus`).
* let the metrics request bypass the envoy sidecar through iptables

Currently we adopt the second method, only capture and redirect normal service port to envoy sidecar and let the other traffic just bypass to the container.

So the configure looks like this before and after:

**Before**:
```
// k8s pod spec:
    ports:
    - containerPort: 8080 // normal service port other service call
      name: http
      protocol: TCP
    - containerPort: 12345 // internal standard business metrics port
      name: metrics
      protocol: TCP

// the corresponding init containers
  initContainers:
  - args:
    - -p
    - "15001"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - x.x.x.x/10
    - -x
    - ""
    - -b
    - 8080,12345
    - -d
    - ""
```

**After**:
```
// k8s pod spec:
    ports:
    - containerPort: 8080 // normal service port other service call
      name: http
      protocol: TCP

// the corresponding init containers
  initContainers:
  - args:
    - -p
    - "15001"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - x.x.x.x/10
    - -x
    - ""
    - -b
    - 8080
    - -d
    - ""
```

And now the prometheus can scrape each pod business metrics through **podIP**, hope this helps who needs:)
