### ISSUE TITLE
Usage of a deprecated go-control-plane struct

### ISSUE THREAD

**Issue by jwendell** [istio/istio#33980]
https://github.com/istio/istio/blob/0eb61cf4a6b12ef8918193e12d314f03d464e219/istioctl/pkg/writer/pilot/status.go#L173

`make lint` is complaining about `GetXdsConfig()` being deprecated with the upgrade to `github.com/envoyproxy/go-control-plane v0.9.10-0.20210708144103-3a95f2df6351` in https://github.com/istio/istio/pull/33976

**Comment by howardjohn** [comment]
cc @therealmitchconnors

**Comment by jwendell** [comment]
Fixed by https://github.com/istio/istio/pull/33997
