### ISSUE TITLE
Helm values.yaml are pointing to latest version of testing image

### ISSUE THREAD

**Issue by jrhoward** [istio/istio#33991]
https://github.com/istio/istio/blob/25c4362d87b9946d6b59d39bf21c6c8a192d060f/manifests/charts/istio-operator/values.yaml#L1

Hi I have been using a gitops pattern for the istio operator. 

I pull down the 1.10.2 tagged repo and run helm install manifests/istio-operator/

I just noted the values.yaml are pointing to the latest testing image on gcr.io.

Is this as intended ?

**Comment by howardjohn** [comment]
The expectation is you download the release from GitHub, not install from source

**Comment by jrhoward** [comment]
thanks for replying. 👍
