### ISSUE TITLE
Ability to deploy istiod on hostnetwork via helmcharts

### ISSUE THREAD

**Issue by chandrakanthkannam** [istio/istio#34021]
**Describe the feature request**
We are using Istio helm charts from this repo to deploy the services in to our clusters, especially this [chart](https://github.com/istio/istio/tree/master/manifests/charts/istio-control/istio-discovery), can you guys consider this request? it would help us a lot. 

changes would be something like this:

- In [deployment](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml) file:

```
spec:
  template:
    spec:
      {{- if .Values.istiod.hostNetwork }}
      hostNetwork: true
      {{- end }}
```

- In [values.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml)
```
## Ability to run istiod on a hostnetwork. 
istiod:
  hostNetwork: false
```

Appreciate your help with this.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by chandrakanthkannam** [comment]
Hi Team, any help here please?

**Comment by carjessu-zerohash** [comment]
We just ran into the same issue where we wanted to set this value and still are unable to. Can this ticket be reopened?

**Comment by zirain** [comment]
please try with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/
