### ISSUE TITLE
Side container fails when running consul and eureka samples

### ISSUE THREAD

**Issue by kolobok01** [istio/istio#3403]
Looks like sidecar manifest that include in samples for consul and eureka is broken
image: docker.io/istio/proxy_init:0.5.0 -exited
image: docker.io/istio/proxy_debug:0.5.0 - running
Tested on ubuntu 16.04 and macOS 
Steps to replicate . 

1. https://istio.io/docs/setup/consul/quick-start.html (all containers are healthy  -- pilot is running)
2. docker-compose -f samples/bookinfo/consul/bookinfo.yaml up -d (all containers are healthy)
3. docker-compose -f samples/bookinfo/consul/bookinfo.sidecars.yaml up -d (exited with no logs)
4. Force docker start xxxxx on exited conteiner out `failed with iptables: Chain already exists.`

Is there anything i am missing from quick-start ?  log form debug 
```javascript
{
  "listeners": [],
  "lds": {
    "cluster": "lds",
    "refresh_delay_ms": 1000
  },
  "admin": {
    "access_log_path": "/dev/stdout",
    "address": "tcp://127.0.0.1:15000"
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "rds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "lds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "zipkin",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://zipkin:9411"
          }
        ]
      }
    ],
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    },
    "cds": {
      "cluster": {
        "name": "cds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    }
  },
  "tracing": {
    "http": {
      "driver": {
        "type": "zipkin",
        "config": {
          "collector_cluster": "zipkin",
          "collector_endpoint": "/api/v1/spans"
        }
      }
    }
  }
```

**Comment by mgtriffid** [comment]
@kolobok01 , in fact this proxy_init container just contains a script which modifies iptables. It is expected that it finishes work and exits. And you say that repeated execution of this container fails with "chain already exists". And that's also expected: when you run this container first, it modifies iptables, and second execution fails because chain already exists.

**Comment by kolobok01** [comment]
@mgtriffid 
Oh wow, i have not realized that that is what is expected behaviour, the problem that i am hitting though is page: http://$GATEWAY_URL/productpage  is unavailable, i assumed that it will be accessible under http://host_ipv4:9081/productpage (or localhost as stated in the example doc) is this not the case ?

**Comment by GregHanson** [comment]
@kolobok01 are you having a similar error to what was reported here?
https://github.com/istio/istio/issues/2788

**Comment by kolobok01** [comment]
@GregHanson 
yep that was it thank you very much, we can close this solution #2788

**Comment by Xiphin** [comment]
0a66f081ca65        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_ratings-v1-init_1
3dd5b9dd5ccf        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_reviews-v1-init_1
a034f4e475ab        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_reviews-v3-init_1
55a0395d0312        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_productpage-v1-init_1
ed56f628663d        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_reviews-v2-init_1
0ddb8886628b        istio/proxy_init:0.5.1                                 "/usr/local/bin/prep…"   6 seconds ago       Exited (0) 5 seconds ago                                                                                                                     consul_details-v1-init_1

**Comment by Xiphin** [comment]
docker logs consul_reviews-v1-sidecar_1
-
{
  "listeners": [],
  "lds": {
    "cluster": "lds",
    "refresh_delay_ms": 1000
  },
  "admin": {
    "access_log_path": "/dev/stdout",
    "address": "tcp://127.0.0.1:15000"
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "rds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "lds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      {
        "name": "zipkin",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://zipkin:9411"
          }
        ]
      }
    ],
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    },
    "cds": {
      "cluster": {
        "name": "cds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://istio-pilot:15003"
          }
        ]
      },
      "refresh_delay_ms": 1000
    }
  },
  "tracing": {
    "http": {
      "driver": {
        "type": "zipkin",
        "config": {
          "collector_cluster": "zipkin",
          "collector_endpoint": "/api/v1/spans"
        }
      }
    }
  }

**Comment by Xiphin** [comment]
@kolobok01 @GregHanson

**Comment by Xiphin** [comment]
repeat run: docker-compose -f samples/bookinfo/consul/bookinfo.sidecars.yaml up -d
