### ISSUE TITLE
httpReqRetries rules not working as expected

### ISSUE THREAD

**Issue by disha94** [istio/istio#3404]
Hi,
I recently deployed a nginx service with istio, and I am trying to load test the service.Though I am able to achieve the desired qps but with some 503 errors.
Therefore I added a route rule to get rid of all 503 errors, but it is not working as expected, am I missing something in the configuration?
I am using istio-0.5.0 and attached is my route rule.

apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: nginx-retry
spec:
  destination:
    name: nginx-preprod-service
  route: 
    - labels:
      version: v1  
  httpReqRetries:
    simpleRetry:
      attempts: 3
      perTryTimeout: 5s
  httpReqTimeout:
    simpleTimeout:
      timeout: 20s  

Can someone help me with the same.

**Comment by nmnellis** [comment]
What is not working as expected? I would advise you update to Istio 0.5.1 as it has some critical bug fixes and test again.

**Comment by disha1104** [comment]
As I mentioned, after adding the retry rules, my expectation was to get all 200 responses, but I was still getting some errors (503 error).
I had a discussion about the same on group as well, https://groups.google.com/d/msg/istio-users/hhWml2_gEPY/m13cNsvtAAAJ ,  not sure if this is fixed in 0.5.1.
Should I update to new version or wait for the next release?

**Comment by disha94** [comment]
Hi @nmnellis ,
As I mentioned, after adding the retry rules, my expectation was to get all 200 responses, but I was still getting some errors (503 error).
I had a discussion about the same on group as well, https://groups.google.com/d/msg/istio-users/hhWml2_gEPY/m13cNsvtAAAJ , not sure if this is fixed in 0.5.1.
Should I update to Istio 0.5.1 or wait for the next release?

**Comment by nmnellis** [comment]
i would update to 0.5.1, it appears to be a lot more stable and we have seen others with similar issues have success with it

**Comment by ldemailly** [comment]
I see (only now sorry) that you are using fortio - versions of fortio before 0.6.9 had a bug with chaining and would generate 503s/panic in some cases.

This being said I agree your expectation of retries would be mine as well, the rate of 503s should drop dramatically if you have retries. I think we should add a test for that.

in the meantime please upgrade to fortio 0.6.9 and istio 0.5.1 

you can generate explicitly 1% of 503s for instance by putting &status=503:1 on your fortio target url - without retries you should get ~1% 503s and with retries much much less (3 retries should be 1/100/100/100 error eate)

**Comment by disha94** [comment]
Thanks a lot @ldemailly .
Let me upgrade both Istio and fortio versions and check.I'll update you on the same then.
Also I didn't understand generating the 503's explicitly that you mentioned, can you please elaborate a bit on the same??

**Comment by ldemailly** [comment]
if you deploy fortio and query it with /echo?status=503:1  you will get 1% of 503s consistently which then lets you test if the retries work. 
https://github.com/istio/fortio#server-urls-and-features

you can find an example of deployment https://github.com/istio/istio/blob/master/tools/perf_k8svcs.yaml

**Comment by nmittler** [comment]
@disha94 @ldemailly is this still an issue?

**Comment by ldemailly** [comment]
I don't know that it has been fixed. do we have a test for this feature, is it passing ?

**Comment by nmittler** [comment]
@disha94 The original issue was against istio 0.5.  Can you confirm that this is still and issue in 0.8?

**Comment by disha94** [comment]
@nmittler.. Let me check and get back to you in sometime..
