### ISSUE TITLE
Closely inspect Envoy 1.19 changes for Istio impact

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34042]
We always get some subtle change that breaks our users. Trying to find these before release.

I've marked this as a release blocker, release managers can feel free to change

https://www.envoyproxy.io/docs/envoy/latest/version_history/current

- [x] `http: the behavior of the present_match in route header matcher changed. The value of present_match was ignored in the past. The new behavior is present_match is performed when the value is true.`
   - Talked with yuchen. This only impacts present_match=false. present_match is a oneof, so we never set present_match=false. So this should have no impact
- [ ]

**Comment by lambdai** [comment]
link updated: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.19.0

**Comment by ryantking** [comment]
Per @howardjohn, nothing of concern in the changelog. Closing this...
