### ISSUE TITLE
Generalize gen-jwt.py's hacky object-valued claims to general values.

### ISSUE THREAD

**Issue by dsbos** [istio/istio#34050]
**Describe the feature request**

Request: To `gen-jwt.py`, add a command-line option that simply adds a claim of _arbitrary_ JSON value type (any JSON [value](https://datatracker.ietf.org/doc/html/rfc7159#section-3)).

Istio's demo/exploration-support script `gen-jwt.py` supports adding (mostly) arbitrary claims with string values and array-of-strings values, via its `-claims` and `-listclaim` options. (That "mostly" is because `-claims` presumably doesn't provide an escape syntax for representing commas or colons in claim values or names.)

However, its `-nestedclaim` command-line option is really hacky and limited, generating a claim with a hard-coded name of `nested`, whose value is a JSON object with a member `nested-2`(also hard-coded) whose value is another JSON object (with the user's specified array member name and array of values added as members to both `nested` and `nested-2`). 

One key thing the user can't do is have different members and/or values in `nested` and `nested-2`, and of course the user is stuck with that very specific structure with those names `nested` and `nested-2`.

** Could you add a `-claim` option that takes 1) an arbitrary string for a claim name and 2) a string that is an _arbitrary_ JSON value, and simply creates a claim with the given name and given JSON value (i.e., created payload member with given name and given value)?

Probably, take the name string and JSON value string as _separate_ command-line parameters (rather than in a single string combined with some syntax that needs to be parsed apart and the accompanying issue of whether there's an escape mechanism).

Yes, I know that `gen-jwt.py` is not intended as a general-purpose or production tool.  However, it would still be helpful if it handled things more generally.

In my case, I'm exploring using JWTs with claims that are objects with array members (which `-nestedclaim` does partially support), but it would be a lot easier to keep things straight if I could explore using the existing claim names from elsewhere in my system, rather that having to use the hard-coded `nested`, etc.

Also, I can't use `gen-jwt.py` to see if Istio supports claims with deeper structure, because `gen-jwt.py` can only create the forms it know about.  If it would simply let me give it an arbitrary JSON value, I could create a claim with whatever JSON value I wanted to try.

Note: The use of the term "nested claim" in Istio documentation, and `gen-jwt.py`'s help, is confusing, given that the [JWT RFC](https://datatracker.ietf.org/doc/html/rfc7519)  defines no such thing as a "nested claim." The RFC defines one level of claims, and specifies that the value of a claim is an arbitrary JSON value.

The documentation should probably use a term like "object-typed claim" instead of "nested claim" (or maybe "nested claim value" instead of "nested claim" when referring to values inside the claim rather than the claim as a whole), and the documentation example that says `request.auth.claims[nested1][nested2]` should be something like `request.auth.claims[claim_name][member_name]`.

**Describe alternatives you've considered**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by dsbos** [comment]
How do I cancel the staleness so that this issue is kept "live" until Istio team members have time to look at this issue (even if that time comes only after months or a year or two, since it's a low-priority item)?

(Why throw away (from visibility on the open-bugs/-issue-reports list) the information that a reporter has gathered and provided about an issue just because team members haven't yet had time to address it?)

**Comment by zirain** [comment]
Not stale
