### ISSUE TITLE
[Revision] Incorrect discoveryAddress for warm cert in Virtual Machine Installation

### ISSUE THREAD

**Issue by xulingqing** [istio/istio#34058]
**Bug description**

Use Case: 
Install VM following [guide](https://istio.io/latest/docs/setup/install/virtual-machine/) to a controlPlane with revision label.

In the workload entry generation step,  the generated hosts is correctly pointing to `<Eastwestgateway External_IP> istiod-revision-label.istio-system.svc`, but Effective config: binaryPath: /usr/local/bin/envoy  discoveryAddress is pointing to  istiod.istio-system.svc.
```
istioctl x workload entry configure --revision revision-label -f workloadgroup.yaml -o "${WORK_DIR}" --clusterID "${CLUSTER}" --autoregister
```

Observation:
Apply mesh config from file defaultConfig is correctly labeled. Apply proxy config from env will override discoveryAddress to unlabeled svc. 

**Affected product area (please put an X in all that apply)**

Virtual Machine Installation to revision labeled controlPlane.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Expected behavior**

Apply proxy config from env should not override mesh config from defaultConfig

**Steps to reproduce the bug**

Install Vm to istiod with revision label.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.10.2

**How was Istio installed?**

IstioOperator with revision label in spec.

**Environment where the bug was observed (cloud vendor, OS, etc)**

- GCP [BareMetal Cluster 1.7](https://cloud.google.com/anthos/clusters/docs/bare-metal/1.7/installing/creating-clusters/hybrid-cluster-creation). 
- centos8 VM

**Comment by xulingqing** [comment]
@stevenctl

**Comment by xulingqing** [comment]
@liminw

**Comment by xulingqing** [comment]
Fix https://github.com/istio/istio/pull/35290

**Comment by xulingqing** [comment]
VM installation webpage https://istio.io/latest/docs/setup/install/virtual-machine/#configure-the-virtual-machine
change: https://github.com/istio/istio.io/pull/10380

**Comment by stevenctl** [comment]
#35340
