### ISSUE TITLE
[Revision] Incorrect Virtual Service host selection for expose-istiod in Virtual Machine Installation

### ISSUE THREAD

**Issue by xulingqing** [istio/istio#34059]
#**Bug description**

Virtual Service doesn't work for istiod with revision label. All traffic to port 15012 will be route to destination host istiod.istio-system.svc.cluster.local.
https://raw.githubusercontent.com/istio/istio/release-1.10/samples/multicluster/expose-istiod.yaml

Use Case:
Install VM following [guide](https://istio.io/latest/docs/setup/install/virtual-machine/) to a controlPlane with revision label. 

Observation:
It should match different host with SNI in istiod-vs.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

It should probably be smart enough to support multiple revisions

**Comment by stevenctl** [comment]
cc @frankbu @nmittler 

Any possibility we move this into the actual install? May reduce confusion and allow easily revisioning. The alternative is explicitly instructing users to edit this to include the revision in the hosts.

**Comment by xulingqing** [comment]
@liminw
