### ISSUE TITLE
pods are going to Initcrashloopbackoff for every 6 hours.

### ISSUE THREAD

**Issue by shivkumarpatil** [istio/istio#34069]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by shivkumarpatil** [comment]
![Uploading 16263325630731023712276804565804.jpg…]()

**Comment by shivkumarpatil** [comment]
![Uploading 16263326122236155325795564981713.jpg…]()

**Comment by shivkumarpatil** [comment]
![Uploading 16263327262888855617776337705472.jpg…]()

**Comment by kebe7jun** [comment]
Can you describe the problem you are having in detail according to the template content? Also, there is a problem uploading your image and it won't open.

**Comment by shivkumarpatil** [comment]
Hi,

I installed services under istio namespace, when I do kubectl get pods -i
bm-istio

It's showing initcrashloopbackoff error.

Due to this issue, intetnal server error and we are unable to fetch data
from services.

**Comment by xulingqing** [comment]
Hi Shiv,

The images are deprecated. Could you include more logs in the issue description? 

Thanks.

**Comment by howardjohn** [comment]
We don't have enough info to procede.
