### ISSUE TITLE
Improve documentation of sidecar.istio.io/inject as a label

### ISSUE THREAD

**Issue by kevin-lindsay-1** [istio/istio#34082]
I see discrepancies in the documentation on this.

[Being referred to as a label](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy)

[Being referred to as an annotation](https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/)

Which is it?

**Comment by howardjohn** [comment]
https://github.com/istio/api/pull/1997 is work in progress to stop using annotation

Both work, the label is new and better than annotation. The label avoids additional calls to istiod when set to `false` and allows usage even when the namespace is not explicitly labeled when set to `true`.

**Comment by kevin-lindsay-1** [comment]
@howardjohn thanks! I figured as much, what with all the good changes Istio has had recently, especially to the docs.

I assume if I'm using `1.10.2` I can use the label without any gotchas, then?

**Comment by howardjohn** [comment]
Yep! I slightly repurposed the issue to track improving docs here, as there is some catch-up to do

**Comment by kevin-lindsay-1** [comment]
Ok, thank you very much! You want I should leave it open, then?

**Comment by saltbo** [comment]
`sidecar.istio.io/inject` as a pod annotation is invalid on istio v1.13.1, label is ok.  Is it a bug? @howardjohn

**Comment by saltbo** [comment]
how to implement this issue?

I found it is AUTO-GENERATED by the `istio/api`, should we move or copy the defined of `sidecar.istio.io/inject` from [annotations](https://github.com/istio/api/blob/master/annotation/annotations.yaml) to [labels](https://github.com/istio/api/blob/master/label/labels.yaml )?

**Comment by howardjohn** [comment]
Its both an annotation AND a label. Label is preferred
