### ISSUE TITLE
Remove istioctl collateral bash/zsh

### ISSUE THREAD

**Issue by ericvn** [istio/istio#34092]
**Describe the feature request**

The way to create the completion files has changes to istioctl completion zsh/bash per an earlier PR (#33787). I have created a PR to use the new commands as part of the make (#34091). We should deprecate/remove the collateral zsh/bash from istioctl.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
Can this be closed?

**Comment by ericvn** [comment]
No. Running `./out/darwin_amd64/istioctl collateral completion --zsh` still generates a file which is different than `./out/darwin_amd64/istioctl completion zsh > _istioctl_2` and the later should be correct per #33787.
