### ISSUE TITLE
gateway: add kubernetes based integration test

### ISSUE THREAD

**Issue by zachgersh** [istio/istio#3409]
Now that rough HTTP gateway functionality is in place - there should be a Kubernetes based integration test added that would exercise this functionality. The [Cloud Foundry one](https://github.com/istio/istio/blob/1af8c60337cc1566f61fac1eee22dd514d03fc16/tests/e2e/tests/pilot/cloudfoundry/copilot_test.go) can be used as an example as needed.

relevant [conversation](https://istio.slack.com/archives/C38CF1PEC/p1518117512000202)

**Comment by nmnellis** [comment]
Your cloud foundry link is dead. can you please relink it?

**Comment by rosenhouse** [comment]
@nmnellis Thanks, those tests got moved around recently.   I've updated the link to include a commit-sha.

**Comment by rshriram** [comment]
tests are present
