### ISSUE TITLE
Memory leak in xds_proxy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34097]
https://github.com/istio/istio/blob/efef026fa83791b917d064c1ec91d4d95b9b1a32/pkg/istio-agent/xds_proxy.go#L391 is susceptible to a memory leak. This can occur when all reader are blocked, and `responsesChan` has hit capacity (10).

All readers can be blocked if the consumer is slow: https://github.com/istio/istio/blob/efef026fa83791b917d064c1ec91d4d95b9b1a32/pkg/istio-agent/xds_proxy.go#L455. This can be triggered by making the downstream.Send slow (reproduced in tests, with artificial delays), or by `requestsChan` being full and blocking.

This is far worse in 1.8, which can also be blocked by slow upstream.Send (https://github.com/istio/istio/blob/1.8.6/pkg/istio-agent/xds_proxy.go#L294). 

Every time the readers have exited (from conn.stopped closing), but we are still attempting to write on `responsesChan`, we will leak a goroutine+a channel with 10 discovery responses.

In real world (on 1.8, which again, is more susceptible to this), we saw roughly 200 occurrences of such a leak, leading to (presumably, no hard data for this) 2k DiscoveryResponses kept in memory, which took up 20gb of RAM and ultimately led to repeated OOMs.

**Comment by mandarjog** [comment]
@kyessenov can take a look at this ?
