### ISSUE TITLE
Gateway: remaining work for v1

### ISSUE THREAD

**Issue by zachgersh** [istio/istio#3410]
#2982 provided basic HTTP gateway implementation, but several pieces are missing.

## things that can be built w/ v1 apis
- when the backing service has more than one port
- when the route rule applies to a particular ingress port
- when the route has wildcard hostnames
- ~when the gateway has wildcard hostnames~ (prefix wildcard complete, see #3634)

## things that need a conversation
- workload-selectors (if the gateway isn't running any service instances, where do the labels come from?)

## things that probably need envoy v2 apis
- non-HTTP listeners
- merging gateways with different TLS config

cc: @rosenhouse @rshriram @ZackButcher

**Comment by rshriram** [comment]
obsolete
