### ISSUE TITLE
TestCertExpired data race

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#34115]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34113/unit-tests_istio/1416136188011483136

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1417824176810496000

**Comment by williamaronli** [comment]
I think I can add a waitgroup for this case?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34497/unit-tests_istio/1422661520822636544

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/34642
