### ISSUE TITLE
Receive unexpected error when using mcp-over-xds

### ISSUE THREAD

**Issue by zirain** [istio/istio#34126]
**Bug description**

I'm try to set up a demo with mcp-over-xds, here is the code [mcpoverxds](https://github.com/zirain/mcpoverxds)
but got some unexpected warn log, and there's no update event got

![image](https://user-images.githubusercontent.com/4354057/126062172-fce257ca-51b6-4a6c-83b4-78b2e7bacfec.png)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
no warn log and get all istio crd change event

**Steps to reproduce the bug**

- install istio via istioctl 1.8.4
- install the mcpoverxds demo
- apply the helloworld demo app

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

![image](https://user-images.githubusercontent.com/4354057/126062210-60d597fb-c77a-4a80-97b3-08a47df84745.png)

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

windows 10 + docker + kubernetes on docker desktop

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
cc @ChenglongGao327
