### ISSUE TITLE
Istio does not support the finalizer for GatewayClass 

### ISSUE THREAD

**Issue by nak3** [istio/istio#34128]
**Bug description**

- Gateway-API expects Ingress providers to support the following finalizer (`gateway-exists-finalizer.networking.x-k8s.io`) GatewayClass but Istio does not support it.

https://github.com/kubernetes-sigs/gateway-api/blob/9f1a3a1c1b4ed8e77608031e2d1ee3fa60aadf7f/apis/v1alpha1/gatewayclass_types.go#L157-L159

[X] Networking

**Expected behavior**

- Istio supports the finalizer and block for the deletion of GatewayClass if Gateways still exist.

**Steps to reproduce the bug**

1. Deploy Gateway-API by https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/
2. Check GatewayClass by `$ kubectl get gatewayclass -o yaml`. No finalizer is added.

**Version**

```
$ istioctl version
client version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4
control plane version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4
data plane version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4 (1 proxies)
```

**How was Istio installed?**

```
$ istioctl install -y --set values.gateways.istio-ingressgateway.type=NodePort
```

**Comment by howardjohn** [comment]
Why does it matter? Are you expecting to read this finalizer as proof its been admitted?

I think finalizers are a bit of an anti-pattern and lead to major UX projects, and are certainly not required for our implementation. I believe the finalizer is not required to be added, and only an implementation detail, where if a controller _does_ need a finalizer, they should name it that?

**Comment by nak3** [comment]
Umm... I see. I was just testing other Gateway API implementations and found a different behavior from another implementation (contour) which uses the finalizer to block unexpected deletion.

https://github.com/projectcontour/contour-operator/blob/b8fe3a30b7e80f2943c0c6ae593f5ce90ea929bc/internal/objects/gatewayclass/finalizer.go#L26

```
$ kubectl get gatewayclass sample-gatewayclass 
NAME                  CONTROLLER                           AGE
sample-gatewayclass   projectcontour.io/contour-operator   2m55s

$ kubectl get gatewayclass sample-gatewayclass -o=jsonpath={.metadata.finalizers}
["gateway-exists-finalizer.networking.x-k8s.io"]

$ kubectl delete gatewayclass --all
gatewayclass.networking.x-k8s.io "sample-gatewayclass" deleted
 ... hang up ...
```

So, Istio will block the unexpected deletion by a different way or not block it?

**Comment by howardjohn** [comment]
It will not block it. I don't think blocking deletion of resources is a good user experience. This may be my personal opinion but I avoid applications that do this. https://github.com/ibuildthecloud/finalizers project description summarizes my feelings :slightly_smiling_face:

**Comment by nak3** [comment]
Thank you. I understand. I am closing this issue.
