### ISSUE TITLE
How to upgrade sidercar does not affect the application

### ISSUE THREAD

**Issue by lilihongjava** [istio/istio#34135]
My environment：k8s 1.15 istio1.6
I refer to this article https://istio.io/v1.6/docs/setup/upgrade/, I found that upgrading the data plane will still affect the existing applications.

Is there any automated tool that can upgrade sidecar without affecting existing applications?

Supplement: don't affect existing applications, which means to update sidecar without restarting the application

**Comment by howardjohn** [comment]
This is not currently possible. See https://github.com/istio/istio/issues/33072
