### ISSUE TITLE
Document Istio CDS, LDS, EDS, RDS abbreviations

### ISSUE THREAD

**Issue by rhrazdil** [istio/istio#34139]
**Bug description**

The documentation page [Debugging Envoy and Istiod](https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/)
shows output of `istioctl proxy-status`, but doesn't explaint the meaning of these shortcuts: CDS, LDS, EDS, RDS

I think it would make sense to describe these abbreviations to help the reader understand their meaning

[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by antonio-te** [comment]
For those coming here from Google, [these services](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration) are specific to Envoy, the proxy [underpinning Istio](https://istio.io/latest/docs/ops/deployment/architecture/). They are, in title order:
- Cluster Discovery Service
- Listener 〃〃
- Endpoint 〃〃
- Route 〃〃
