### ISSUE TITLE
Istiod couldn’t sense the crd’s change when config a nacos mcp service

### ISSUE THREAD

**Issue by noob-noob** [istio/istio#34134]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
i start istio with nacos mcp server,  here is the istio’s demo.yaml 
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    configSources:
    - address: xds://10.15.4.2:18848

the mcp server works well, service information pass through to the cluster. but when i try to config a istio gateway, it doesn’t work. and i try to config a virtualservice ,doesn’t work either.

here is what i found . when i start istio without mcp server config, the istiod would print logs while deploy CRD like gateway.
![image](https://user-images.githubusercontent.com/18344133/126094893-ef741b94-2123-4e23-bdd8-55412e276530.png)

but when start istio with mcp server config, the istiod print nothing.
**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
the gateway works

**Steps to reproduce the bug**
1. start nacos 2.0.2 with mcp server 
2. add     configSources: - address: xds://10.15.4.2:18848 to istio demo.yaml
3. start istio 1.10.2 with istioctl apply -f demo.yaml
4. apply  gateway on port 80.
![企业微信截图_3e41cb5a-e13d-49ba-8226-57f53fa77905](https://user-images.githubusercontent.com/18344133/126095401-08ca1bd9-c9fa-4084-a09f-38851f50c0db.png)
5. run 'istioctl proxy-config listener $ingress_pod_name  -n istio-system' to see whether the ports is on

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
k3s v1.21.2+k3s1
istio 1.10.2 
**How was Istio installed?**
istioctl apply -f demo.yaml
**Environment where the bug was observed (cloud vendor, OS, etc)**
centOS 7.6
nacos 2.0.2
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I think if you want the MCP service *and* kubernetes your config should be like:

```
configSources:
- address: xds://10.15.4.2:18848
- address: k8s://
```

**Comment by noob-noob** [comment]
> I think if you want the MCP service _and_ kubernetes your config should be like:
> 
> ```
> configSources:
> - address: xds://10.15.4.2:18848
> - address: k8s://
> ```

problem solved, thanks a lot. 

like you said, here is my correct config:
`configSources:
- address: xds://10.15.4.2:18848
- address: k8s://127.0.0.1:6443`

**Comment by howardjohn** [comment]
Great!. Btw it can literally be `k8s://` and auto detect the k8s address instead of hard coded.

**Comment by saltbo** [comment]
The same problem took hours to troubleshoot.

Don't we have any documentation for mcp over xds to implement mcp-server yet?

**Comment by hzxuzhonghu** [comment]
MCP protocol was changed once, the most direct way is to look at how pilot does
