### ISSUE TITLE
istio-proxy transmitting only HEADERS post certain fixed streams

### ISSUE THREAD

**Issue by kunalekawde** [istio/istio#34136]
**Bug description**
istio-proxy providing only HTTP/2 HEADERS instead of HEADER, DATA & content after some fixed number of streams.
Each pod is injected with istio-proxy sidecar.
AS seen in the packet capture done using 'any' interface, the HEADERs and DATA frame for pod to pod looks fine, but on lo interface its seen that on STREAM = 1273 the DATA is not transmitted fully with END_STREAM not set and following this only HEADERS are transmitted. Just a though that total DATA pkts would be 1273/2 = 636 x 103(data size) = 65508 -- This is any buffer limit ?
In the attached capture, please see pkt no: 601, decode as HTTP2 on the port 9001.

![image](https://user-images.githubusercontent.com/4777551/126123793-f6d23a24-118b-4530-9bc0-d1634637cff3.png)
[server-http2-onyHEADERs.zip](https://github.com/istio/istio/files/6838963/server-http2-onyHEADERs.zip)

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
istio-proxy to provide the messages in order as seen in pod to pod communication wireshark capture.

**Steps to reproduce the bug**
2 pods as client and server, run 500 calls(HTTP/2 POST with data-~103bytes) per second - I've timed as 10calls every 20 ms. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio: 1.4.2
k8:
Client Version: v1.18.3
Server Version: v1.18.3
helm: v3.2.4+g0ad800e

**How was Istio installed?**
helm install

**Environment where the bug was observed (cloud vendor, OS, etc)**
On prem vm nodes, test cluster - 1 master, 3 worker nodes

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Hey @kunalekawde , we would be happy to look into this if you upgrade to a supported version. Istio 1.4 has been unsupported for well over a year, so it isn't something we can commit time to debugging, nor something we would fix even if we found an issue. See https://istio.io/latest/news/support/announcing-1.4-eol/ for more information. Thanks!

**Comment by kunalekawde** [comment]
@howardjohn thanks for taking a look. I tried on version 1.8.2 and noticed the exact same behavior.

version.BuildInfo{Version:"1.8.2", GitRevision:"bfa8bcbc116a8736c301a5dfedc4ed2673e2bfa3", GolangVersion:"go1.15.5", BuildStatus:"Clean", GitTag:"1.8.2"}
/usr/local/bin/envoy  version: dbb980e5e222c3fe3c4bb5a299a962ea2f44150e/1.16.1/Clean/RELEASE/BoringSSL

As seen below at stream 1273 only the data is received partial followed by only HEADERS. These prints are from server stack.
```
^[[33m[1626773963.322]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=125, flags=0x04, stream_id=1273> connid:5
^[[33m[1626773963.323]^[[0m ^[[31;1m[on_data_chunk_recv_callback]^[[0m [id=1] stream:1273 app call left_unprocessed:27 len:27
^[[33m[1626773963.323]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv DATA frame <length=27, flags=0x00, stream_id=1273> connid:5
^[[33m[1626773963.324]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=376, flags=0x04, stream_id=1275> connid:5
^[[33m[1626773963.325]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=127, flags=0x04, stream_id=1277> connid:5
^[[33m[1626773963.326]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=127, flags=0x04, stream_id=1279> connid:5
^[[33m[1626773963.327]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=127, flags=0x04, stream_id=1281> connid:5
^[[33m[1626773963.328]^[[0m ^[[31;1m[on_frame_recv_callback]^[[0m [id=1] recv HEADERS frame <length=127, flags=0x04, stream_id=1283> connid:5
```

**Comment by howardjohn** [comment]
Thanks for upgrading! Note that 1.8 is EOL as well (https://istio.io/latest/news/support/announcing-1.8-eol-final/) but probably close enough

@lambdai can you take a look?

**Comment by kunalekawde** [comment]
Thanks for considering this. I shall provide any other debug information required for this.

**Comment by kunalekawde** [comment]
@lambdai  help solicited please.

**Comment by kunalekawde** [comment]
This could be server app issue, I attempted with different app and didn't observe above condition.

**Comment by kunalekawde** [comment]
@lambdai  / @howardjohn , while I'm trying to investigate on the server side stack which is getting quite tricky, It would be great to know if there is any condition based on which envoy would only transmit HEADERS and not DATA, something like getting responses to outstanding requests initiated / high-low watermark / window size ?

**Comment by howardjohn** [comment]
Any info one what caused it? for future references?

**Comment by kunalekawde** [comment]
The server stack is async and processes the requests on single thread by design, so when requests are fetched from the socket, those many are processed and application callback invoked, even if application sends the response inline, untill all read data is processed, write for responses is not invoked. In above observation, server was not writing responses on wire even if application has processed it, I suppose this causes envoy to not continue with DATA frames. Anyways the subsequent observation would be RST_STREAM from client as request would timeout.
