### ISSUE TITLE
TCP service (Kafka) stops working after istiod upgrade without explicit protocol selection

### ISSUE THREAD

**Issue by emike922** [istio/istio#34164]
**Bug description**
When deploying a non-HTTP TCP service (regular+headless, specifically here Kafka) outside the service mesh and WITHOUT explicit protocol selection, the application stops being reachable from an application pod inside the service mesh after istiod gets upgraded from 1.7 to 1.8/1.9/1.10 (does not matter which).
Upgrading the application pod to the new sidecar version restores connectivity.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Service should remain reachable from "old" application pod after istiod got upgraded

**Steps to reproduce the bug**
```
# Deploy Kafka w/o sidecar
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install --namespace kafka-ns my-release bitnami/kafka --create-namespace --set image.registry=<dockerhub mirror> --set persistence.enabled=false

# Kubectl edit service objects my-release-kafka and my-release-kafka-headless to *disable* explicit protocol selection
# Note: This is just to more easily reproduce, as I am not able to share the actual charts
  ports:
# - name: tcp-client
  - name: binary-plain
    port: 9092
    protocol: TCP
    targetPort: kafka-client

# Deploy Istio 1.7
helm install --namespace istio-system --create-namespace istio-base istio-1.10.3/manifests/charts/base
helm upgrade --install --namespace istio-system istiod istio-1.7.8/manifests/charts/istio-control/istio-discovery --set global.hub=<dockerhub mirror> --set global.tag="1.7.8" --set global.istioNamespace=istio-system --set meshConfig.accessLogFile=/dev/stdout

# Deploy Kafka client w/ sidecar
kubectl label namespace kafka-ns istio-injection=enabled
kubectl create -n kafka-ns -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-tester
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-tester
  labels:
    app: kafka-tester
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: kafka-tester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-tester
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kafka-tester
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: kafka-tester
      containers:
      - name: kafka
        image: bitnami/kafka:2.8.0
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
EOF

# Create a topic (once)
kubectl exec -n kafka-ns $(kubectl get pods -n kafka-ns -l app=kafka-tester -o jsonpath='{.items[0].metadata.name}') -c kafka -- /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server my-release-kafka:9092 --topic my-topic --create --partitions 1 --replication-factor 1

# List topics (repeat as necessary to test connectivity)
kubectl exec -n kafka-ns $(kubectl get pods -n kafka-ns -l app=kafka-tester -o jsonpath='{.items[0].metadata.name}') -c kafka -- /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server my-release-kafka:9092 --list

# Access log (istiod 1.7)
[2021-07-19T14:34:33.381Z] "- - -" 0 - "-" "-" 85 542 107 - "-" "-" "-" "-" "10.244.0.47:9092" outbound|9092||my-release-kafka.kafka-ns.svc.cluster.local 10.244.0.59:39376 10.96.130.0:9092 10.244.0.59:54536 - -
[2021-07-19T14:34:33.467Z] "- - -" 0 - "-" "-" 85 602 20 - "-" "-" "-" "-" "10.244.0.47:9092" outbound|9092||my-release-kafka-headless.kafka-ns.svc.cluster.local 10.244.0.59:39380 10.244.0.47:9092 10.244.0.59:39378 - -

# Upgrade Istio to 1.8/1.9 or 1.10
#helm upgrade --install --namespace istio-system istiod istio-1.8.6/manifests/charts/istio-control/istio-discovery --set global.hub=<dockerhub mirror> --set global.tag="1.8.6" --set global.istioNamespace=istio-system --set meshConfig.accessLogFile=/dev/stdout
#helm upgrade --install --namespace istio-system istiod istio-1.9.5/manifests/charts/istio-control/istio-discovery --set global.hub=<dockerhub mirror> --set global.tag="1.9.5" --set global.istioNamespace=istio-system --set meshConfig.accessLogFile=/dev/stdout
helm upgrade --install --namespace istio-system istiod istio-1.10.3/manifests/charts/istio-control/istio-discovery --set global.hub=<dockerhub mirror> --set global.tag="1.10.3" --set global.istioNamespace=istio-system --set meshConfig.accessLogFile=/dev/stdout

# List topics again
kubectl exec -n kafka-ns $(kubectl get pods -n kafka-ns -l app=kafka-tester -o jsonpath='{.items[0].metadata.name}') -c kafka -- /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server my-release-kafka:9092 --list

# Access log (istiod 1.10)
[2021-07-19T14:36:12.270Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.96.130.0:9092 10.244.0.59:57098 - -
[2021-07-19T14:36:12.376Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.96.130.0:9092 10.244.0.59:57106 - -
[2021-07-19T14:36:12.481Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.96.130.0:9092 10.244.0.59:57108 - -
[2021-07-19T14:36:12.587Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.96.130.0:9092 10.244.0.59:57110 - -
[2021-07-19T14:36:12.693Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.96.130.0:9092 10.244.0.59:57112 - -
...
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.8 => 1.8.6 / 1.9.5 / 1.10.3

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
Multiple environments (KaaS, Minikube, Kind)

**Comment by emike922** [comment]
I have collected some listener and cluster configs from the 1.7.8 sidecar before/after upgrade of istiod.
Service naming is a little bit different, message-bus-kf-client corresponds to my-release-kafka and message-bus-kf to my-release-kafka-headless. And namespace is istio-system instead of kafka-ns. But otherwise it should be comparable.

Automatic protocol selection:
[autops_clusters178.txt](https://github.com/istio/istio/files/6846635/autops_clusters178.txt)
[autops_clusters1103.txt](https://github.com/istio/istio/files/6846636/autops_clusters1103.txt)
[autops_listeners178.txt](https://github.com/istio/istio/files/6846637/autops_listeners178.txt)
[autops_listeners1103.txt](https://github.com/istio/istio/files/6846638/autops_listeners1103.txt)

Explicit protocol selection:
[explicitps_clusters178.txt](https://github.com/istio/istio/files/6846639/explicitps_clusters178.txt)
[explicitps_clusters1103.txt](https://github.com/istio/istio/files/6846632/explicitps_clusters1103.txt)
[explicitps_listeners178.txt](https://github.com/istio/istio/files/6846633/explicitps_listeners178.txt)
[explicitps_listeners1103.txt](https://github.com/istio/istio/files/6846634/explicitps_listeners1103.txt)

**Comment by howardjohn** [comment]
Istio 1.10 control plane is not expected to be able to communicated with 1.7 proxy; only 1 version difference is supported, so I wouldn't focus too much on 1.10. But 1.7 -> 1.8 should have worked.

It does look like the code is broken here; we are generating
```
          "filter_chain_match": {
            "transport_protocol": "raw_buffer",
            "application_protocols": [
              "http/1.0",
              "http/1.1",
              "h2c"
            ]
          },
```

Which means we will no longer match the tcp_proxy part (which is not obvious - see https://github.com/envoyproxy/envoy/issues/12572 for a lot of detail) here.

So ultimately, I would say - it is broken unfortunately, but because 1.8 is EOL we will not fix it (see https://istio.io/latest/news/support/announcing-1.8-eol-final/). 1.9+ are not broken, since 1.9 only supports 1.8/1.9 proxy versions, which would not have that issue. Sorry if that isn't the response you were hoping for...

**Comment by emike922** [comment]
Thanks for the explanation! It may not be expected to work beyond n-1, but clearly it still *does* to some extent (old proxy receives these config updates). Anyway..
I don't suppose you can think of some sort of temporary workaround, other than configuring explicit protocol selection for the impacted service(s)?

**Comment by howardjohn** [comment]
The best option is to follow https://istio.io/latest/docs/setup/upgrade/canary/. This ensures the the proxy always connects to the same version of the control plane. Among other benefits, this happens to mitigate this bug.

You could also explicitly configure the protocol (which is good idea in general anyways)
