### ISSUE TITLE
ext_authz EnvoyFilter gets dropped if wild card in hosts entry in gw 

### ISSUE THREAD

**Issue by komalarg2010** [istio/istio#34195]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I have a GW matching with wild card for '*' for hosts 

`apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gui-gw
  namespace: istio-system  
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https-gui
      number: 3443
      protocol: HTTPS
    tls:
      cipherSuites:
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_RSA_WITH_AES_256_GCM_SHA384
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
`

and an envoy filter : 

`apiVersion:` networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ns1-ef
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: istio.metadata_exchange
          **sni: foo.ns1.com**
        portNumber: 3443
    patch:
      operation: INSERT_AFTER
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: accept
                - exact: authorization
                - exact: cookie
                - exact: from
                - exact: proxy-authorization
                - exact: user-agent
                - exact: x-forwarded-access-token
                - exact: x-forwarded-email
                - exact: x-forwarded-for
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-user
                - prefix: x-auth-request
                - prefix: x-forwarded
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              allowedUpstreamHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
            server_uri:
              cluster: outbound|4180||oauth2-proxy.ns1.svc.cluster.local
              timeout: 1.5s
              uri: http://oauth2-proxy.ns1.svc.cluster.local
  workloadSelector:
    labels:
      istio: ingressgateway
`

When I check config dump, envoy filter is not created. 

 kubectl exec -it istio-ingressgateway-568755d77d-c7gj7 -n istio-system  -- pilot-agent request GET config_dump > conf_dump.txt 

However, if I have matching hosts entry (in gw) and sni (in envoyfilter) , filter is created properly. 

<Working config is below gw and previous envoyfilter) 
`apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gui-gw
  namespace: istio-system  
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - **foo.ns1.com**
    port:
      name: https-gui
      number: 3443
      protocol: HTTPS
    tls:
      cipherSuites:
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_RSA_WITH_AES_256_GCM_SHA384
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
`

we have a single gw for multiple GUIs in different namespaces, multiple envoy filters forwarding request to oauth2-proxy in corresponding namespace.. 

I cannot give all hosts entries upfront in gw. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[*] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Expectation is sni in each envoy filter should match wild card host entry 

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.7.6 
k8s: v1.19.5
helm: v3.4.1

**How was Istio installed?**
helm charts 

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This is working as expected - you said to match a filter chain with SNI field set, but the gateway you used does not result in a filter chain with the SNI set.

Note the EnvoyFilter is not say "at runtime match requests with this arbitrary SNI", but rather matching against envoy configuration.

I strongly encourage you to upgrade to a newer version of Istio and use the native ext_authz support.

**Comment by howardjohn** [comment]
Closing as WAI. Thanks!
