### ISSUE TITLE
Build: CentOS proxy build container depends on getenvoy-package (archived project)

### ISSUE THREAD

**Issue by mathetake** [istio/istio#34204]
CentOS build image depends on [getenvoy-package](https://github.com/tetratelabs/getenvoy-package)'s clang tool chain: https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile.centos#L34

The project is archived and that means that there won't be newer versions of LLVM/clang toolchain available. Given that there's no official LLVM toolchain for CentOS, we can go 1) build the toolchain from the source, 2) install from the third party (non-llvm) package manager.

cc @lizan @codefromthecrypt

**Comment by codefromthecrypt** [comment]
maybe we can copy this approach if istio admins can create a misc (or istio-misc) repo the same way https://github.com/envoyproxy/envoy/pull/17497
