### ISSUE TITLE
Istio 1.11.0-beta.1 fails on OCP 4.7 - istio-cni-node pods crashing with "Error: failed to create UDS listener: listen unix /var/run/istio-cni/log.sock: bind: permission denied"

### ISSUE THREAD

**Issue by FilipB** [istio/istio#34211]
**Bug description**
When installing Istio 1.11.0-beta.1 on OCP 4.7, all istio-cni-node pods are crashing with "Error: failed to create UDS listener: listen unix /var/run/istio-cni/log.sock: bind: permission denied"

Full log attached.

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio is installed correctly

**Steps to reproduce the bug**

1. `oc adm policy add-scc-to-group anyuid system:serviceaccounts:istio-system`
2. run `istioctl manifest install ` command specified bellow

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
OCP 4.7.19
Istio 1.11.0-beta.1

**How was Istio installed?**
`istioctl manifest install --skip-confirmation=true --set profile=demo  --set hub=gcr.io/istio-release  --set values.meshConfig.enableAutoMtls=true  --set values.gateways.istio-egressgateway.enabled=true --set values.gateways.istio-ingressgateway.enabled=true --set values.global.meshID=mesh-default --set values.global.multiCluster.clusterName=cluster-default --set values.global.network=network-default --set components.cni.enabled=true --set components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/etc/cni/multus/net.d --set values.cni.chained=false --set values.cni.cniConfFileName=istio-cni.conf --set values.sidecarInjectorWebhook.injectedAnnotations.k8s\.v1\.cni\.cncf\.io/networks=istio-cni   `

```
- Processing resources for Istio core.
��� Istio core installed
- Processing resources for Istiod.

- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
��� Istiod installed
- Processing resources for CNI, Egress gateways, Ingress gateways.
- Processing resources for CNI, Egress gateways, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node

- Processing resources for CNI, Egress gateways, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node, Deployment/istio-system/istio-egressgateway

- Processing resources for CNI, Egress gateways, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node, Deployment/istio-system/istio-egressgateway, Deployment/istio-system/istio-ingressgateway
��� Egress gateways installed
- Processing resources for CNI, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node, Deployment/istio-system/istio-ingressgateway
��� Ingress gateways installed

- Processing resources for CNI. Waiting for DaemonSet/kube-system/istio-cni-node
��� CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
DaemonSet/kube-system/istio-cni-node
- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
Failed to install Istio with profile [demo]. Will retry in 10 seconds...

- Processing resources for Istio core.
��� Istio core installed
- Processing resources for Istiod.
��� Istiod installed
- Processing resources for CNI, Egress gateways, Ingress gateways.
- Processing resources for CNI, Egress gateways, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node
��� Egress gateways installed

��� Ingress gateways installed

- Processing resources for CNI. Waiting for DaemonSet/kube-system/istio-cni-node
��� CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
DaemonSet/kube-system/istio-cni-node
- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
Failed to install Istio with profile [demo]. Will retry in 10 seconds...

- Processing resources for Istio core.
��� Istio core installed

- Processing resources for Istiod.
��� Istiod installed
- Processing resources for CNI, Egress gateways, Ingress gateways.
��� Egress gateways installed
- Processing resources for CNI, Ingress gateways.
- Processing resources for CNI, Ingress gateways. Waiting for DaemonSet/kube-system/istio-cni-node

��� Ingress gateways installed

- Processing resources for CNI. Waiting for DaemonSet/kube-system/istio-cni-node
��� CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
DaemonSet/kube-system/istio-cni-node

- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
OCP 4.7.19

istio-cni-node pod log:
[istio-cni-node-9wpc5-install-cni.log](https://github.com/istio/istio/files/6856151/istio-cni-node-9wpc5-install-cni.log)

**Comment by bianpengyuan** [comment]
@FilipB Could you try set `LOG_UDS_ADDRESS` env variable to a empty string at CNI daemonset and see if that fixes the issue?

**Comment by jwendell** [comment]
@bianpengyuan It doesn't fix it. Empty means viper will use the default value. I still see in the log:

`LogUDSAddress: /var/run/istio-cni/log.sock`

AFAIK, OpenShift doesn't allow bind to unix sockets. A quick solution it to add `privileged: true` in the `securityContext` of the container.

**Comment by YonkaFang** [comment]
> @bianpengyuan It doesn't fix it. Empty means viper will use the default value. I still see in the log:
> 
> `LogUDSAddress: /var/run/istio-cni/log.sock`
> 
> AFAIK, OpenShift doesn't allow bind to unix sockets. A quick solution it to add `privileged: true` in the `securityContext` of the container.

I wanna know if our sidecar works well on openshift as it also use unix socket for uds purpose and etc.

**Comment by jwendell** [comment]
unix sockets work fine on openshift. The failure was that the container needed privileges, which was fixed. Try latest 1.11, not beta1
