### ISSUE TITLE
istiod RA Kubernetes CSR strategy does not parse certificate chains correctly

### ISSUE THREAD

**Issue by JoshVanL** [istio/istio#34218]
**Bug description**

Currently when using Kubernetes CSR resources to sign certificates, istiod only parses the leaf certificate, not the full signed chain returned. This causes verification errors when a  signer is using an intermediate certificate and will never work unless the intermediate certificate _is also_ propagated with the root CA. This negates the point of using an intermediate in the first place, and is impracticable for signers who's intermediates are only known during runtime.

The code causing this issue is [here](https://github.com/istio/istio/blob/77258b37054a4c33b657e61f6133308600dd300d/security/pkg/k8s/chiron/utils.go#L340).

This function should be replaced with a func which will parse the full chain, and any intermediates be included in the Verify further down. The following diff should produce the correct result:

```git
diff --git a/security/pkg/k8s/chiron/utils.go b/security/pkg/k8s/chiron/utils.go
index a9320851a3..00b349a760 100644
--- a/security/pkg/k8s/chiron/utils.go
+++ b/security/pkg/k8s/chiron/utils.go
@@ -293,10 +293,16 @@ func readSignedCertificate(client clientset.Interface, csrName string,
                return []byte{}, []byte{}, nil
        }
 
+       certsParsed, err := util.ParsePemEncodedCertificateChain(certPEM)
+       if err != nil {
+               return nil, nil, fmt.Errorf("decoding certificate failed: %w", err)
+       }
+
        caCert, err := readCACert(caCertPath)
        if err != nil {
                return nil, nil, fmt.Errorf("error when retrieving CA cert: (%v)", err)
        }
+
        // Verify the certificate chain before returning the certificate
        roots := x509.NewCertPool()
        if roots == nil {
@@ -305,12 +311,17 @@ func readSignedCertificate(client clientset.Interface, csrName string,
        if ok := roots.AppendCertsFromPEM(caCert); !ok {
                return nil, nil, fmt.Errorf("failed to append CA certificate")
        }
-       certParsed, err := util.ParsePemEncodedCertificate(certPEM)
-       if err != nil {
-               return nil, nil, fmt.Errorf("decoding certificate failed")
+
+       intermediates := x509.NewCertPool()
+       if len(certsParsed) > 1 {
+               for _, cert := range certsParsed[1:] {
+                       intermediates.AddCert(cert)
+               }
        }
-       _, err = certParsed.Verify(x509.VerifyOptions{
-               Roots: roots,
+
+       _, err = certsParsed[0].Verify(x509.VerifyOptions{
+               Roots:         roots,
+               Intermediates: intermediates,
        })
        if err != nil {
                return nil, nil, fmt.Errorf("failed to verify the certificate chain: %v", err)
diff --git a/security/pkg/pki/util/crypto.go b/security/pkg/pki/util/crypto.go
index f9cc30307d..fbe996d4ac 100644
--- a/security/pkg/pki/util/crypto.go
+++ b/security/pkg/pki/util/crypto.go
@@ -20,6 +20,7 @@ import (
        "crypto/rsa"
        "crypto/x509"
        "encoding/pem"
+       "errors"
        "fmt"
        "reflect"
 )
@@ -46,6 +47,35 @@ func ParsePemEncodedCertificate(certBytes []byte) (*x509.Certificate, error) {
        return cert, nil
 }
 
+// ParsePemEncodedCertificateChain constructs a slice of `x509.Certificate`
+// objects using the given a PEM-encoded certificate chain.
+func ParsePemEncodedCertificateChain(certBytes []byte) ([]*x509.Certificate, error) {
+       var (
+               certs []*x509.Certificate
+               cb    *pem.Block
+       )
+
+       for {
+               cb, certBytes = pem.Decode(certBytes)
+               if cb == nil {
+                       break
+               }
+
+               cert, err := x509.ParseCertificate(cb.Bytes)
+               if err != nil {
+                       return nil, fmt.Errorf("failed to parse X.509 certificate")
+               }
+
+               certs = append(certs, cert)
+       }
+
+       if len(certs) == 0 {
+               return nil, errors.New("no PEM encoded X.509 certificates parsed")
+       }
+
+       return certs, nil
+}
+
 // ParsePemEncodedCSR constructs a `x509.CertificateRequest` object using the
 // given PEM-encoded certificate signing request.
 func ParsePemEncodedCSR(csrBytes []byte) (*x509.CertificateRequest, error) {
```

[x] Security

**Expected behavior**

Using the Kubernetes CSR strategy should allow intermediates to be correctly parsed in `status.Certificate` CertificateSigningRequests.

**Steps to reproduce the bug**

Setup istio using Kubernetes CSR and use a signer who signs with an intermediate. The propagated CA contains the root CA, whilst `status.Certificate` contains the intermediate and leaf certificate.

---

I have a WIP branch with the above changes and am currently working through updating the tests. Please advice is the issue is correct for istio and I will open up a PR to fix once ready.

**Comment by liminw** [comment]
@shankgan Can you take a look the proposed change from @JoshVanL?

**Comment by shankgan** [comment]
Generally looks good. @JoshVanL - Can you submit this change as a PR and I will approve it?

An additional point - I am wondering if its acceptable to remove this validation logic altogether altogether? Today, the CA cert used for cert-chain validation is mounted as a config-map onto Istiod. This makes things challenging if the external signer changes its CA.crt for some reason, or when we have multiple signers. Is the RA actually required to perform this validation for every requested cert? @liminw , @myidpt - any thoughts? would appreciate pointers to RFCs/other implementations for this.

**Comment by shankgan** [comment]
> Generally looks good. @JoshVanL - Can you submit this change as a PR and I will approve it?
> 
> An additional point - I am wondering if its acceptable to remove this validation logic altogether altogether? Today, the CA cert used for cert-chain validation is mounted as a config-map onto Istiod. This makes things challenging if the external signer changes its CA.crt for some reason, or when we have multiple signers. Is the RA actually required to perform this validation for every requested cert? @liminw , @myidpt - any thoughts? would appreciate pointers to RFCs/other implementations for this.

On second thought, this is a bad idea. Malicious signers could hijack our CSR process and sign using their own cert as long as they have the necessary K8s privileges. Better to (TLS) authenticate the root cert in the workload cert chain to confirm identity of the CA.
