### ISSUE TITLE
1.11 CNI does not work on OpenShift

### ISSUE THREAD

**Issue by jwendell** [istio/istio#34222]
`install-cni` pod fails with:

```
Error: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
```

OpenShift does not allow a container to bind to a unix socket unless it's a privileged container

**Comment by bianpengyuan** [comment]
Dup of https://github.com/istio/istio/issues/34211

**Comment by bianpengyuan** [comment]
@jwendell Could you try set LOG_UDS_ADDRESS env variable to a empty string at CNI daemonset and see if that fixes the issue? Asked in the other issue as well, but would be nice if you can try as well.
