### ISSUE TITLE
ServiceEntry is not working with WorkloadEntry.

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#34224]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

1) DNS proxying is enabled
2) Created WorkloadEntry and ServiceEntry with host `address.internal` just for testing purposes. 
SE uses WE as selector. 
3) istio sidecar is bootstrapped and running on VM. 

When creating Kubernetes Service for WE - i can curl my app on VM. 
Creating SE for WE - host in SE can't be resolved. 

`k exec -it <pod_has_sidecar> --  curl -v  addreses.internal - host can not be resolved.`

**Expected behavior**
I expect that when I curl address.internal it should be resolved within the mesh as address.internal. 

Did I miss anything? I don't have K8s Service for this workload.

**Steps to reproduce the bug**

Please follow istio.io docs for ServiceEntry and Dns Proxying

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
v10.0.0

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
It is expected, SE is not a kind of headless service.

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  I simple followed this example 
https://istio.io/latest/docs/reference/config/networking/service-entry/#:~:text=TLS)%20and%20forwards,labels%3A%0A%20%20%20%20%20%20app%3A%20details 

Why is documented if it's not suppose to work with WorkloadEntry?

**Comment by hzxuzhonghu** [comment]
>Created WorkloadEntry and ServiceEntry with host address.internal just for testing purposes.
SE uses WE as selector.

Maybe the selector is different, i will have a look later

**Comment by christian-posta** [comment]
So "ServiceEntry" creates an Envoy cluster under the covers for the sidecar, WorkloadEntry creates endpoints/IPs ... the selector in the ServiceEntry must select the correct WorkloadEntrys for the IPs to appear in the Envoy cluster.

**Comment by christian-posta** [comment]
Sorry, accidentally hit wrong button :)

**Comment by Arsen-Uulu** [comment]
@christian-posta I am using same labels in SE as I used in Kubernetes Services which works.

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu  Any updates? 


curl localhost:15000/config_dump I can see the IP address of my workloadEntry and port and it's reporting healthy, DNS_CAPTURE: True, 

```outbound|80||adress.internal::<IP>:8379::health_flags::healthy``` and I still can't resolve the host

**Comment by hzxuzhonghu** [comment]
With the example in above link, i can resolve the `details.bookinfo.com`. 

```
/ $ nslookup details.bookinfo.com
Server:		10.96.0.10
Address:	10.96.0.10:53

Name:	details.bookinfo.com
Address: 240.240.0.2

```

But when change the resolution to `NONE`, it can not be resolved

```
/ $ nslookup details.bookinfo.com
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find details.bookinfo.com: SERVFAIL

** server can't find details.bookinfo.com: SERVFAIL


```

**Comment by hzxuzhonghu** [comment]
After look into istiod code, i found we did not build nametable for ServiceEntry with resolution = NONE

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu It is failing with resolution: DNS

**Comment by ramaraochavali** [comment]
DNS resolution is resolved by Envoy Not Istio

**Comment by Arsen-Uulu** [comment]
@ramaraochavali  Yes I get.  I still can't resolve the host of ServiceEntry when I try to curl that DNS name within the mesh.

**Comment by Arsen-Uulu** [comment]
> So "ServiceEntry" creates an Envoy cluster under the covers for the sidecar, WorkloadEntry creates endpoints/IPs ... the selector in the ServiceEntry must select the correct WorkloadEntrys for the IPs to appear in the Envoy cluster.

@christian-posta curl localhost:15000/clusters I can see correct IP and port from my workloadEntry. I still can't resolve the host name of ServiceEntry
