### ISSUE TITLE
How to enable alpha Envoy feature: WAVM runtime

### ISSUE THREAD

**Issue by jessberg** [istio/istio#34266]
I am trying to deploy WASM filters that are run using the WAVM runtime with Istio.  The WAVM runtime is not enabled in the official Envoy [build](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto), and so I need to make my own build.  I believe I have successfully done so with the command 
```
bazel build --action_env=PATH="/usr/local/bin:/opt/local/bin:/usr/bin:/bin" //source/exe:envoy-static  //source/exe:envoy-static --//source/extensions/wasm_runtime/wavm:enabled
```
from this [Envoy repo](https://github.com/envoyproxy/envoy).

However, I believe Istio uses its own customized version of Envoy.  Is there a way to pass the command line argument ```
```
-//source/extensions/wasm_runtime/wavm:enabled 
```
through to the Istio build of Envoy?  If not, is there some other way to enable this feature while still using Istio?

**Comment by mathetake** [comment]
It is the same for the Istio proxy - you just need to pass the same argument "--define wasm=wavm" at build time of proxyv2 image.
