### ISSUE TITLE
Automate release manifest creation for upgrade test

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#34276]
We have bunch of release manifest generated from past releases which is used in various upgrade integration test: https://github.com/istio/istio/tree/master/tests/integration/pilot/testdata/upgrade.

Currently creation of those manifest is done manually, we should automate the refresh of those manifest for new releases. 

cc @Monkeyanator

**Comment by bianpengyuan** [comment]
@ericvn Any suggestion on what is the best place to implement this, or any bot that we can piggyback this functionality on?

**Comment by bianpengyuan** [comment]
not stale.

**Comment by ericvn** [comment]
Not stale
