### ISSUE TITLE
sidecar arm7(ubuntu 32)

### ISSUE THREAD

**Issue by jack09791** [istio/istio#34287]
Hi !
In this step 
![图片](https://user-images.githubusercontent.com/83930914/126769575-bbc6a2a7-04cc-4bb7-8a0f-a0140fd67ed9.png)

Did somebody have arm7(ubuntu 32) version's url  ?

**Comment by howardjohn** [comment]
No, ARM is not supported. Please follow https://github.com/istio/istio/issues/26652

**Comment by cfanbo** [comment]
they are diffrentsi decar AND istio

**Comment by morlay** [comment]
@cfanbo 

it is not possible to support 32 bit.
Chrome v8 required by istio-proxy, which is not support 32 bit.

aarch64 enovy could copy envoy from image `docker.io/querycapistio/proxyv2` and run  `make deb` of `istio/istio`.
