### ISSUE TITLE
Update kiali to 1.38

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34340]
https://github.com/kiali/kiali/pull/4108 is required to use it with Istio 1.11

**Comment by ryantking** [comment]
@howardjohn Should we classify this as an RB since we'll need it for 1.11?

**Comment by howardjohn** [comment]
I put it as P0 because technically we don't ship Kiali. So release blocker feels a bit extreme. That being said, Kiali plans to release on the 30th so should be no issue

**Comment by jwendell** [comment]
Fixed by https://github.com/istio/istio/pull/34462#event-5096861760
