### ISSUE TITLE
istioctl commands fail in an IPv6 only cluster

### ISSUE THREAD

**Issue by pseudonator** [istio/istio#34358]
**Bug description**
In an IPv6 only cluster if `istioctl pc` is executed then the following error will pop-up
```
2021-07-27T12:15:12.330900Z	error	klog	an error occurred forwarding 52054 -> 15000: error forwarding port 15000 to pod 516bcfbe033ea20d6db0151ccc7e073c25661a3569ff6671677e2a3c30219883, uid : failed to execute portforward in network namespace "/var/run/netns/cni-e8dd1f78-40d9-f83c-c61c-740add119d6a": failed to dial 15000: dial tcp4 127.0.0.1:15000: connect: connection refused
Error: failed to execute command on istio-ingressgateway-7f66dbb97c-6m62m.rcp-istio-system sidecar: failure running port forward process: Get "http://127.0.0.1:52054/config_dump": EOF
```

This is because admin port `15000` is bound to `::1`
```
tcp6       0      0 ::1:15000               :::*                    LISTEN      10/envoy
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
`istioctl` to work regardless of the underlying cluster running on IPv4, IPv6 or dualstack.

**Steps to reproduce the bug**

**Version**
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (3 proxies)

**Environment where the bug was observed (cloud vendor, OS, etc)**
In an IPv6 cluster.

**Comment by esnible** [comment]
I don't have an IPv6 only cluster to troubleshoot or test this issue.

**Comment by pseudonator** [comment]
@esnible Il see if i can dig into it further and create a PR

**Comment by zhlsunshine** [comment]
Hi @pseudonator,  I have a pure IPv6 k8s cluster, and I also can reproduce this error easily, so could I take this issue if you are not working on it?

**Comment by pseudonator** [comment]
@esnible @zhlsunshine Investigating this further it seems that this is a generic issue relating to IPv6 and CRI.
I was running `containerd` in my setup and `containerd` versions `1.5.0`-`1.5.2` added two PRs ([don't use socat for port forwarding](https://github.com/containerd/containerd/commit/11a78d9d0f1664466fa3fffebd8ff234f3ef2677) and [use happy-eyeballs for port-forwarding](https://github.com/containerd/containerd/commit/305b42583073aa1435d15ff5773c049827fa8d51)) which fixed a number of issues in IPv6 port-forwarding.

Further to pulling in `containerd` version `1.5.2` I was also getting the error `IPv4: dial tcp4 127.0.0.1:15021: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found` when port-forwarding. This is caused by a DNS issue when resolving `localhost`. I added `sed -i 's/::1 ip6-localhost ip6-loopback/::1 localhost ip6-localhost ip6-loopback/' /etc/hosts` in the host to fix it.

Hope this helps someone.

**Comment by zhlsunshine** [comment]
This error relates to kubernetes container runtime, so there are 2 cases as below:

1. **Docker** as the container runtime 
  According to [Istioctl commands support in IPv6 only cluster](https://docs.google.com/document/d/1a6eZ6ldF2l7De3vX-SBAHmuJ00uxlgpPznHocG7zcfs/edit?usp=sharing,) user need to change the runtime from **Docker** to **containerd**
2. **containerd** as the container runtime
  According to [istioctl commands fail in an IPv6 only cluster #34358](https://github.com/istio/istio/issues/34358#issuecomment-923413096), user should make sure that the containerd version is higher than 1.5.0

There would be no error if follow alternative above.
