### ISSUE TITLE
details on docker images used

### ISSUE THREAD

**Issue by rileytg** [istio/istio#344]
I'm trying to find how the grafana image was built, can someone point me towards the dockerfile?

Thanks!

**Comment by douglas-reid** [comment]
Please see: https://github.com/istio/mixer/blob/master/deploy/kube/conf/Dockerfile. in that `deploy/kube/conf` directory, there is a bunch of grafana-related scripts, etc.

**Comment by rileytg** [comment]
wonderful, thank you!
