### ISSUE TITLE
grpc communication between 1.9 and 1.10 proxies not working

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#34408]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
After upgrading to Istio 1.10 (from 1.9) we noticed that there is a connectivity issue between 1.9 and 1.10 proxies when using grpc.

The issue is persistent, it continues to fail until proxy is upgraded to 1.10. We did an in place upgrade and don't run multiple control plane versions. Connectivity between 1.9 proxies (proxies that did not get updated yet after the control plane ugrade) keeps working. Also grpc connectivity between 1.10 proxies works fine. Normal http traffic is not affected and 1.9 proxies can still talk to 1.10 proxies.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**
We do not expect connectivity issues between different version of the proxies when there is not more than one major release in between them.

**Steps to reproduce the bug**
We spotted the issue with the [Online Boutique](https://github.com/GoogleCloudPlatform/microservices-demo) demo application. In particular, the connection from the checkout service (1.9) to the cart service (1.10) was failing for us.

Another way to reproduce is using curl/wget from a pod towards this demo app:

Below from a pod with a 1.9 proxy. Note that we deployed each microservice of the demo app in its own namespace.
```
ky get po hw-956b9c6b7-lrnfl | grep image:
    image: docker.io/istio/examples-helloworld-v1:latest
    image: gcr.io/gke-release/asm/proxyv2:1.9.6-asm.1
    image: gcr.io/gke-release/asm/proxyv2:1.9.6-asm.1

k exec -it hw-956b9c6b7-lrnfl bash
# curl a grpc service
curl cartservice.cartsvc:7070
upstream connect error or disconnect/reset before headers. reset reason: remote resetI have no name!

# curl a http service
curl -I frontend.frontendsvc:8080
HTTP/1.1 200 OK
```

And from a pod with a 1.10 proxy:
```
ky get po checkoutservice-5b4949fd98-4c9mr | grep image:
    image: eu.gcr.io/bolcom-stg-watt-images-6d6/hipstershop/checkoutservice:v0.2.4
    image: gcr.io/gke-release/asm/proxyv2:1.10.2-asm.3
    image: gcr.io/gke-release/asm/proxyv2:1.10.2-asm.3

k exec -it checkoutservice-5b4949fd98-4c9mr sh
# curl a grpc service
wget cartservice.cartsvc:7070 -O /tmp/index.html
cat /tmp/index.html 
Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909/src $ 
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
ASM 1.10.2 rev 3

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE 1.18

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by rolandkool** [comment]
A config dump and debug log from the cartservice can be found here: https://gist.github.com/rolandkool/2b9fd44c9178a5ac01de234259a1c2f0

**Comment by rolandkool** [comment]
Could there be relation with https://github.com/istio/istio/issues/33136 ?

**Comment by tbarrella** [comment]
It does look related to that issue. Are you able to try https://github.com/envoyproxy/envoy/issues/14587#issuecomment-833139246 with the 1.10 proxy?

**Comment by rolandkool** [comment]
@tbarrella how do we set this flag through Istio?

**Comment by tbarrella** [comment]
Try an annotation and ConfigMap as in https://github.com/istio/istio/tree/master/samples/custom-bootstrap. The ConfigMap data should be
```yaml
data:
  custom_bootstrap.json: |
    {
      "layered_runtime": {
        "layers": [
          {
            "name": "scheme",
            "static_layer": {
              "envoy.reloadable_features.preserve_downstream_scheme": false
            }
          }
        ]
      }
    }
```

Note that from my understanding of the issue, this is affecting 1.9 requests to the 1.10 cart service because the cart service uses .NET Core. So far I've only read of this issue affecting server applications that use .NET Core.

**Comment by rolandkool** [comment]
Thanks. We've verified that the annotation does indeed work when we apply it to this cart service. Also, it does indeed seem to be related to just that one service which happens to be .NET. The other grpc calls work without any modifications.
Luckily, within our landscape we barely have any .NET so the impact of this issue is very limited.

Should this issue be kept open to track a structural fix or will this annotation / custom bootstrap be the recommended way to work around this?

**Comment by tbarrella** [comment]
Just created https://github.com/istio/istio/issues/34448 to track this :) It sounds like it will be ok for me to close this.
