### ISSUE TITLE
Automate checks with a command line tool

### ISSUE THREAD

**Issue by mcandre** [istio/istio#34413]
**Describe the feature request**

Please provide a command line tool that reports the istio enabled/disabled status for a given Kubernetes namespace, as well as any pods currently there.

**Describe alternatives you've considered**

The FAQ manual is also a good resource. But it has more potential to be misread by the user, compared to automated checks:

* Labels and annotations can be mistakenly swapped. This is already a known issue in terms of the documentation conflicting with the user experience.
* Typos of "enable" vs "enabled".
* Forgetting to apply the namespace annotation.
* Forgetting about a pod exclusion.

A lightweight checker tool can help provide an objective pair of eyes to identify issues that a human is likely to miss.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by zhlsunshine** [comment]
Hi @mcandre,  
I understand that you want to list all k8s namespaces whose injection feature is enabled for  `reports the istio enabled/disabled status for a given Kubernetes namespace` you mentioned above, if yes, I think it's similar with the command `kubectl get ns -L istio-injection`.

And for `any pods currently there`,  do you mean that all pods injected by Istio in k8s cluster should be listed via `istioctl`?
