### ISSUE TITLE
 restart existing pods in service mesh for changes in meshConfig.defaultConfig

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#34439]
**Feature request:** 
This issue was raised when working on [issue#32602](https://github.com/istio/istio/issues/32602),  but it's different from issue#32602, there is no Istio re-install after changes in meshConfig.defaultConfig. 
After some investigation, I found that these 2 issues focus on different parts. Issue#32602 need to restart all pods already exist in service mesh if the Istio is re-installed, and this issue need to restart all pods in service mesh if the meshConfig.defaultConfig changes.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I do not think we want to be in the business of restarting users pods, its a highly risky and dangerous task.

**Comment by ramaraochavali** [comment]
+1. It is not Istio problem.

**Comment by zhlsunshine** [comment]
Hi @howardjohn & @ramaraochavali,  yes, it's not a good idea to restart users pods, so shall we just analyze them via analyzer?
