### ISSUE TITLE
Request through gateway return Connection refused after add  discoverySelectors 

### ISSUE THREAD

**Issue by zhaoli2333** [istio/istio#34438]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I created a Gateway and a VirtualService for the demo application "helloworld", then I sent a request like:
```
curl -i -H "Host:helloworld.qiyi.domain" http://10.61.233.222/hello
```
and got a correct response like:
```
Hello version: v1, instance: helloworld-v1-5c8655bc7c-ls7l2
```

After that I updated the IstioOperator and added discoverySelectors like:
```
meshConfig:
    discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
``` 
and add a label "istio-discovery=enabled" on namespace "sample", then I send a same request and got this:
```
curl: (7) Failed to connect to 10.61.233.222 port 80: Connection refused
```

this was because I didn't add the label  "istio-discovery=enabled" on namespace "istio-system", so all the requests sent to gateway were refused. But I don't think this is a correct behavior.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio: 1.10.2
k8s: 1.18

**How was Istio installed?**
Primary-Remote on multicluster using IstioOperator.
The gateway and application "helloworld" were deployed on a Remote cluster.

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This is the intended behavior. You need to include all pods that you care about in the selector.

@harveyxia

**Comment by zhaoli2333** [comment]
> This is the intended behavior. You need to include all pods that you care about in the selector.
> 
> @harveyxia

Ok, but I still think that ingressgateway should be discovered by default.
