### ISSUE TITLE
istioctl version cli

### ISSUE THREAD

**Issue by jsenon** [istio/istio#3443]
When I perform 
```
istioctl version > toto                                                                                                                                 
Version: 0.5.0
GitRevision: c9debceacb63a14a9ae24df433e2ec3ce1f16fc7
User: root@211b132eb7f1
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

and perform more `toto`, file is empty. Because output of command line is redirected to stderr:

```
istioctl version 2> toto
more toto
Version: 0.5.0
GitRevision: c9debceacb63a14a9ae24df433e2ec3ce1f16fc7
User: root@211b132eb7f1
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
```

Is it possible to correct output of cobra subcommand `version` ?

**Comment by jsenon** [comment]
I've propose #3450 
Because it's my first PR on this repo let me know if it's correct

**Comment by ldemailly** [comment]
you're right that normal output should go to stdout not stderr - thanks for noticing this

**Comment by ldemailly** [comment]
pro tip add "Fixes xxx" in your PR to autoclose issues
