### ISSUE TITLE
Istio resets service/ingress-service configuration (istioctl / operator)

### ISSUE THREAD

**Issue by schroedt** [istio/istio#34431]
Hi there,

I noticed istio 1.8.1 and 1.10.3 resets my ingress-gateway customization from time to time:

```
kubectl get service -n istio-system -o wide
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                      AGE    SELECTOR
[…]
istio-ingressgateway   LoadBalancer   10.109.36.176    192.168.190.64   15021:31125/TCP,80:31443/TCP,443:30947/TCP,15002:30000/TCP   133d   app=istio-ingressgateway,istio=ingressgateway
[…]
```

Please notice NodePort `30000` routing to gateway at Port `15002`, which I added using:

```
kubectl edit service istio-ingressgateway -n istio-system

[…]
spec:
  ports:
   […]
   - name: https-applications
     nodePort: 30000
     port: 15002
     targetPort: 15002
     protocol: TCP
[…]
```

I need a **defined**, **fixed NodePort** for routing and TLS offloading of external traffic into my clustser through my `Gateway` (Port 15000). The default HTTPS NodePort seems to change sometimes, that's why I added my own one.

Routing is `router` (defined, static Port clearance) » `Kubernetes`.

Is there any configuration file, istio operator uses, when it operator reconciles or does anything?

I installed it using a k8s pod `istio/istioctl:1.10.3` and `default profile`:

```
istioctl operator init
```

**Comment by litong01** [comment]
@schroedt when customize istio gateway two things actually happen, One is the service , the other is the deployment deployment.apps/istio-ingressgateway. I wonder if you can also make changes in the deployment as well and see if it behaves as you desire. For example, in service/istio-ingressgateway, you probably can do the following.

For example, if the service needed this
```
   ports:
   - name: https-applications
     nodePort: 30000
     port: 15002
     targetPort: 15002
     protocol: TCP
```

The deployment needs to add the following as well
```
        ports:
        - containerPort: 15002
          protocol: TCP
```

Probably try this and see if istio behaves better.

**Comment by schroedt** [comment]
Hi @litong01,

routing generally works from `istio-ingress` via `virtualservice` (part of my workload) to `service` (workload) and `pod` (workload). Connetivity is realized by attaching the virtual service to `istio-ingress`, which redirects to a `service`(workload) and it's port.

I do not have any trouble for routing or reaching it.

My issue is, that sometimes `istio-ingressgateway` loses its configuration and I do not know why. Since upgrading to a newer version of Istio, the issue disappeared.

**Comment by litong01** [comment]
@schroedt so when you used 1.10.3 the issue still existed. but after you move to 1.11.x, it is gone? Just want to confirm. Thanks.
