### ISSUE TITLE
Outbound traffic for SMTP port 587 stopped working after istio upgrade 1.7.8 to 1.8.6

### ISSUE THREAD

**Issue by naveen-mindtree** [istio/istio#34443]
Hi,

We have email service running which is configured with 'smtp.office365.com' SMTP server was running fine, we were able to send emails. We did istio upgrade from 1.7.8 to 1.8.6 that instance we are unable to connect SMTP server - 'smtp.office365.com'.

I am not able to find any logs in sidecar proxy. also confirms here there is no any change on the network.

For time being I have excluded port 587 by adding annotation 'traffic.sidecar.istio.io/excludeOutboundPorts' on the deployment. it started working.

Please help on the issue. Thanks in advance !!

**Comment by howardjohn** [comment]
dupe https://github.com/istio/istio/issues/34444
