### ISSUE TITLE
Outbound traffic for SMTP port 587 stopped working after istio upgrade 1.7.8 to 1.8.6

### ISSUE THREAD

**Issue by naveen-mindtree** [istio/istio#34444]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We have email service running which is configured with 'smtp.office365.com' SMTP server was running fine, we were able to send emails. We did istio upgrade from 1.7.8 to 1.8.6 that instance we are unable to connect SMTP server - 'smtp.office365.com'.

I am not able to find any logs in sidecar proxy. also confirms here there is no any change on the network.

For time being I have excluded port 587 by adding annotation 'traffic.sidecar.istio.io/excludeOutboundPorts' on the deployment. it started working.

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Should be able to connect to smtp server

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
naveen:/mnt/c/Users/Desktop/email$ istioctl version
client version: 1.10.3
control plane version: 1.8.6
data plane version: 1.8.6 (247 proxies)

**How was Istio installed?**
using Istio-operator
**Environment where the bug was observed (cloud vendor, OS, etc)**
GCP GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ramaraochavali** [comment]
1.8.7 is Eol and it is difficult to tell what is the problem with such a old version as so many things have changed.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols is probably highly relevant here

**Comment by naveen-mindtree** [comment]
Thanks for the suggestion, yes it was mistake with service name we defined. It Worked after changing the service name with <protocol>-<port>
