### ISSUE TITLE
.NET servers reject https gRPC requests terminated to plaintext by Envoy

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#34448]
**Bug description**
When an application makes an https gRPC request to a .NET server behind an Istio proxy or gateway and Envoy terminates the request to plaintext, starting in 1.10 Envoy preserves `:scheme` as `https`. .NET sees the mismatch between the scheme and the fact that the request from Envoy is plaintext and raises an error, rejecting the request.

This is the root cause of https://github.com/istio/istio/issues/33136 and https://github.com/istio/istio/issues/34408. See also https://github.com/dotnet/aspnetcore/issues/30532 and https://github.com/envoyproxy/envoy/issues/14587#issuecomment-828832216.

Workarounds
- For a .NET Kestrel server, see https://github.com/dotnet/aspnetcore/issues/30532#issuecomment-844386686
- Within Istio, see https://github.com/istio/istio/issues/34408#issuecomment-889338667

It looks like Kestrel 6 will provide a configuration option that fixes this (https://github.com/dotnet/aspnetcore/pull/34013). If this isn't considered a full fix for the issue, it could be worth exposing the option to overwrite scheme added in Envoy 1.19 (https://github.com/envoyproxy/envoy/pull/17070), and/or setting `envoy.reloadable_features.preserve_downstream_scheme` to false by default.

**Expected behavior**
Istio-mTLS requests to .NET are accepted without having to configure TLS at the application level.

**Steps to reproduce the bug**
See e.g. https://github.com/istio/istio/issues/34408

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10

**Comment by janamtote** [comment]
I believe it will only be available starting from .NET 6

![image](https://user-images.githubusercontent.com/83025611/136716818-7c37147d-1e53-412d-a373-3519ed8c7ac9.png)
