### ISSUE TITLE
Validating webhook installation regression

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#34452]
We introduced per-revision validating webhook configurations in [https://github.com/istio/istio/pull/33044/files](https://github.com/istio/istio/pull/33044). As part of this, we had to keep the old validating webhook around to keep from purging it on revisioned upgrade with Helm. However, having a lame-duck validating webhook configuration around, even if it never moves to `FailClose`, has a cost:

1. Produces error logs about missing CA bundle on each resource application
2. Webhook still gets called on each resource application

In addition, with Helm-based install, we never install the revisioned webhook that is meant to actually handle validation since `global: configValidation` is not set in the `istio-discovery` chart.

**Comment by jwendell** [comment]
Fixed in https://github.com/istio/istio/pull/34446
