### ISSUE TITLE
istio does not support multiple tcp services which using k8s' externalName svc 

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#34469]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I think this part "While the examples in this task use HTTP protocols, Kubernetes Services for egress traffic work with other protocols as well."   of the document (https://istio.io/latest/docs/tasks/traffic-management/egress/egress-kubernetes-services/) is a problematic presentation

For Example:

 I have two mysql instances a and b outside the k8s cluster, both bound to port 3306, but with different user names and passwords; now, I create two externalName services corresponding to

mysql-a and mysql-b

Now, when I connect to mysql instance "mysql-a" under a client-example service inside the k8s cluster, I occasionally get a connection authentication failure

This is because the listener that istio sends to Envoy via lds is not able to identify the specific instance that the above mysql request should connect to, because of the lack of clusterIp, resulting in the request being sent to "mysql-b"

[X ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by howardjohn** [comment]
The doc is wrong, this is not expected to work. We should update it. see https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/ for explaination of why

**Comment by zengyuxing007** [comment]
> The doc is wrong, this is not expected to work. We should update it. see https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/ for explaination of why

Thanks for you reply.

I understand that this problem may be fixable if we use the dns address corresponding to the extername service as a match condition (similar to clusterIP)

I understand that this problem may be fixable if we use the dns address corresponding to the extername service as a match condition (similar to clusterIP)

If we don't fix it, users who have been using extername service before istio may need to do some migration adaptations

**Comment by howardjohn** [comment]
That will not work in many many cases - for example if you do dns lookup on
google.com every time you try it you get different results. there is no
stable ip to match on.

**Comment by zengyuxing007** [comment]
Understood, it seems that similar scenarios may use ServiceEntry with address is a better choice
