### ISSUE TITLE
Failed calling webhook "namespace.sidecar-injector.istio.io"

### ISSUE THREAD

**Issue by letthefireflieslive** [istio/istio#34461]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Able to create pod to a istio-injection=enabled namspace

**Steps to reproduce the bug**
It just suddenly didn't work, I dont have any changes istio or k8s control plane manifest-wise

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.3
1.21.3

**How was Istio installed?**
istioct cni

**Environment where the bug was observed (cloud vendor, OS, etc)**
rhel 7

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

I have make my deployment work with istio ingressgateway before. I am not aware of any changes made in istio or k8s side. 

When I tried to deploy, I see an error in replicaset side that's why it cannot create new pod. 

> Error creating: Internal error occurred: failed calling webhook
> "namespace.sidecar-injector.istio.io": Post
> "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp
> 10.104.136.116:443: connect: no route to host

When I try to go inside api-server and ping 10.104.136.116 (istiod service IP) it just hangs. 

What I have tried so far:

 - Deleted all coredns pods 
 - Deleted all istiod pods 
 - Deleted all weave pods 
 - Reinstalling istio via istioctl x uninstall --purge
 - turning all of VMs firewall
 - sudo iptables -P INPUT ACCEPT
   sudo iptables -P FORWARD ACCEPT
   sudo iptables -P OUTPUT ACCEPT
   sudo iptables -F
 - restarted all of the nodes

Setup
 - k8s version: 1.21.2
 - istio: 1.10.3
 - HA setup
 - CNI: weave
 - CRI: containerd

**Comment by howardjohn** [comment]
I would look further down the stack at your CNI or other lower level kubernetes setup. there isn't much istio could do to cause this, seems like a symptom of something else breaking

**Comment by letthefireflieslive** [comment]
Looks like it. I didn't have control and visibility over the infra (VM, networking part). I also changed to flannel and made it work.. since it is what we have working with istio on one of our VMs.
