### ISSUE TITLE
Istio mutual authentication failure - failed to validate the JWT

### ISSUE THREAD

**Issue by naveen210121** [istio/istio#34470]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We are getting below error in istiod the logs, not sure why it is not able to authenticate the client with JWT token. By this our ingressgateway setup was stopped working. after istio-ingressgateway restart it started working automatically.
 
Error:

2021-08-02T11:20:57.405871Z     error   ads     Failed to authenticate client from 172.31.24.24:34536
Authenticator ClientCertAuthenticator: no verified chain is found
; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster Kubernetes: the service account authentication returns an error: [invalid bearer token, Token has expired.]

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
There should not any authentication error on the logs
**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

naveen@A2ML33975:/mnt/c/Users/M1018434$ istioctl version --remote
client version: 1.10.3
control plane version: 1.8.6
data plane version: 1.8.6

GKE v1.18
**How was Istio installed?**
using istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
GCP GKE cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by naveen-mindtree** [comment]
One more observation that after restart of pod, old pod is getting stuck in terminating state not deleting completely.

**Comment by howardjohn** [comment]
Kubernetes is supposed to refresh the token, stored at `/var/run/secrets/tokens/istio-token`. So a few possibilities:
* k8s fails to do so
* it does refresh, but we use the old one. This can be detected by checking `/var/run/secrets/tokens/istio-token` file when it says its expired
* The pod refreshes it fine, but api-server has invalidated it. in GKE, when a pod starts terminating it *immediately* invalidates the token - so this may cause it to fail during shutdown?
