### ISSUE TITLE
Istio adding Passthrough Cluster on EgressListener Port in Sidecar Config.

### ISSUE THREAD

**Issue by Buffer0x7cd** [istio/istio#34492]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
This more a question since I couldn’t figured out the expected behaviour from the documentation. For context the setup is explained below.  

1. A server component running behind a service object with name test-server  and a VirtualService with same name test-server , the service is exposing the 8888.
2. We can access the service from a client pod by hitting
`curl test-service:8888`
and we can see the service is being routed through the mesh

Now for a backward compatibility  model , we want to expose this service on a specific port too. In previous mesh a client can access the service by hitting an endpoint like this
`curl localhost:$PORT `
where PORT will be a number mapped to test-server  service.  Behind the scene the mesh keeps a mapping of PORT: Service and route the traffic to correct service.

To build this interface in istio , we thought about using the sidecar resource in below manner

```

apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
.......
spec:
  egress:
  - port:
      number: 20508
      protocol: HTTP
    captureMode: NONE
    bind: 127.0.0.1
    hosts:
    - "istio/test-server.istio.svc.cluster.local"

```

Where `20508` is the port number used by client to access `test-server` service.

Our assumption was that this will open a virtual listener on port 20508 and configure the it to route traffic to   cluster created for `test-server.istio.svc.cluster.local` ( Since we have already created k8s service and Virtual service for test-server.istio.svc.cluster.local) . But after looking at generated config we noticed that the destination for generated route is PassthroughCluster.  

```
[
    {
        "name": "20508",
        "virtualHosts": [
            {
                "name": "allow_any",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "name": "allow_any",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "PassthroughCluster",
                            "timeout": "0s",
                            "maxGrpcTimeout": "0s"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
        ],
        "validateClusters": false
    }
]

```

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The generated route for listener at 20508 should route the traffic to `test-server` cluster instead of  `PassthroughCluster` cluster

**How was Istio installed?**
We have built istio from master branch. 
`control plane version: 1.12-dev`

Slack thread: https://istio.slack.com/archives/C38CF1PEC/p1627996278036900

**Comment by ramaraochavali** [comment]
Why did you set     captureMode: NONE any specific reason?

**Comment by Buffer0x7cd** [comment]
We are testing the setup by connecting to localhost:20508 directly from client side so we though there are not any use of captureMode here, since clients already know that they have to connect to localhost.

For test we are invoking curl like below
`curl -i localhost:20508`
