### ISSUE TITLE
istio-ingressgateway on EC2 instances k8s does not take LoadBlancer for service

### ISSUE THREAD

**Issue by elnemesisdivina** [istio/istio#34515]
Hi there folks , looking for some help,  I trying istio on top of EC2 instances but the load balancer seems like is not providing anything to the istio-ingressgateway:

![image](https://user-images.githubusercontent.com/5790758/128192004-286fd0fa-1e3f-4e73-926e-55db4b34ce11.png)

So read about the problem and I found the recommendation of annotation on the svc in order to get the elb but I'm a little confused if this is for every time I prepare a cluster to istio? and where to dig more about this issue example or docs?

thanks in advance to any chide

**Comment by howardjohn** [comment]
Sorry for not helping much here but this is purely a Kubernetes concern that you will need to fix on that end; Istio does not provision load balancers, it just sets Type=LoadBalancer. Your cluster needs to actually provision it; if you are not using a cloud lb you can use something like metallb
