### ISSUE TITLE
Bookinfo Reviews Pods Crash

### ISSUE THREAD

**Issue by TrevorTaoARM** [istio/istio#34510]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I had installed the Istio and the Bookinfo sample to the guide in https://istio.io/latest/docs/setup/getting-started/:
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

But the 3 Reviews related pods all are crashed:

productpage-v1-6b746f74dc-xpc45   2/2     Running            0          174m
ratings-v1-b6994bb9-x4sq2         2/2     Running            0          174m
reviews-v1-545db77b95-n6jm6       1/2     CrashLoopBackOff   16         59m
reviews-v2-7bf8c9648f-928mt       1/2     CrashLoopBackOff   39         174m
reviews-v3-84779c7bbc-wmkh2       1/2     CrashLoopBackOff   38         174m

The log are the pod reviews-v1 is as:
$ kubectl logs reviews-v1-545db77b95-n6jm6

Unhandled exception
Type=Bus error vmState=0x00000000
J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000002
Handler1=00007F0051A42EA0 Handler2=00007F0051333BA0 InaccessibleAddress=00007F0000000000
RDI=00007F004C1C1580 RSI=0000000000000008 RAX=00007F004C1CE930 RBX=00007F004C1C1580
RCX=00007F004C03AB70 RDX=0000000000000000 R8=0000000000000000 R9=0000000000000000
R10=00007F004C0008D0 R11=0000000000000000 R12=00007F004C1C1580 R13=00007F0000000000
R14=0000000000000001 R15=0000000000000080
RIP=00007F004B57C39B GS=0000 FS=0000 RSP=00007F005297B4A0
EFlags=0000000000010202 CS=0033 RBP=00007F0000000000 ERR=0000000000000006
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007F0000000000
xmm0 0000003000000020 (f: 32.000000, d: 1.018558e-312)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 ffffffff00000002 (f: 2.000000, d: -nan)
xmm3 6f6d656d2f2f2f79 (f: 791621504.000000, d: 5.571061e+228)
xmm4 6e75616c2e617661 (f: 778139264.000000, d: 1.236562e+224)
xmm5 dddddddd000a313d (f: 667965.000000, d: -1.456815e+144)
xmm6 0000000000000994 (f: 2452.000000, d: 1.211449e-320)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 dd006b6f6f68396a (f: 1869101440.000000, d: -9.776703e+139)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9jit29.so
Module_base_address=00007F004B31F000
Target=2_90_20200402_443261 (Linux 5.4.0-58-generic)
CPU=amd64 (48 logical CPUs) (0x1f5be03000 RAM)
----------- Stack Backtrace -----------
(0x00007F004B57C39B [libj9jit29.so+0x25d39b])
(0x00007F004B57C6EB [libj9jit29.so+0x25d6eb])
(0x00007F004B4734E7 [libj9jit29.so+0x1544e7])
J9VMDllMain+0xb44 (0x00007F004B4616B4 [libj9jit29.so+0x1426b4])
(0x00007F0051A543F1 [libj9vm29.so+0xa43f1])
(0x00007F0051AEBF00 [libj9vm29.so+0x13bf00])
(0x00007F00519C1D44 [libj9vm29.so+0x11d44])
(0x00007F0051A5D654 [libj9vm29.so+0xad654])
(0x00007F0051334903 [libj9prt29.so+0x1c903])
(0x00007F0051A56D36 [libj9vm29.so+0xa6d36])
J9_CreateJavaVM+0x75 (0x00007F0051A4DC65 [libj9vm29.so+0x9dc65])
(0x00007F0051F51005 [libjvm.so+0x12005])
JNI_CreateJavaVM+0xa82 (0x00007F0052D26A92 [libjvm.so+0xaa92])
(0x00007F005373AA84 [libjli.so+0xfa84])
(0x00007F00539546DB [libpthread.so.0+0x76db])
clone+0x3f (0x00007F005325788F [libc.so.6+0x12188f])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/04 09:13:45 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/ibm/wlp/output/defaultServer/core.20210804.091345.1.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.38.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 38 was not found. Expected to find core file with name "/opt/ibm/wlp/output/defaultServer/core"
JVMDUMP032I JVM requested Java dump using '/opt/ibm/wlp/output/defaultServer/javacore.20210804.091345.1.0002.txt' in response to an event
JVMDUMP012E Error in Java dump: /opt/ibm/wlp/output/defaultServer/javacore.20210804.091345.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/opt/ibm/wlp/output/defaultServer/Snap.20210804.091345.1.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /opt/ibm/wlp/output/defaultServer/Snap.20210804.091345.1.0003.trc
JVMDUMP013I Processed dump event "gpf", detail "".

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Shat environment is this in? Any chance it's an ARM cluster (just based on your username 🙂 )?

We do run bookinfo in our tests so I think it's not broken in all cases so just be some environmental issue

**Comment by TrevorTaoARM** [comment]
> Shat environment is this in? Any chance it's an ARM cluster (just based on your username 🙂 )?
> 
> We do run bookinfo in our tests so I think it's not broken in all cases so just be some environmental issue

It's on x86(amd64) server of a normal K8s environment. I found a similar [issue](https://github.com/eclipse-openj9/openj9/issues/12698) and tried to set the flag --cgroups-per-qos=false, but not successfully due to a confliction with anothe flag of Kubelet. 
I don't know if it's really related to my environment, but I found no special thing here.

**Comment by liulangwa** [comment]
echo 0 > /proc/sys/vm/nr_hugepages

**Comment by liulangwa** [comment]
it may be casue by https://github.com/OpenLiberty/open-liberty/issues/13389

**Comment by TrevorTaoARM** [comment]
@liulangwa Thank you.

**Comment by phenixblue** [comment]
Just commenting for anyone else that comes across this. Same issue when trying to schedule bookinfo reviews pods on an Intel Kubernetes Service (IKS) node with Gaudi AI Accelerators installed. Disabling huge pages on the node allowed the pods to schedule without core dumping.
