### ISSUE TITLE
The kafka pod crashes when rejoining the cluster with "Peer Authentication" enabled in Istio

### ISSUE THREAD

**Issue by vinothgj** [istio/istio#34532]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I have an AWS EKS cluster with Kafak installed on it, it has the following dimensions
* Zookeeper - 3 replicas
* Kafka - 3 replicas

With istio installed, the label for the namespace under with the above pods are created are enabled for "istio-injection". When the pods are created by applying the helm for Kafka. The desired & minimum replica for ZK and KF is 3 and max is 6 for the requirement.

Now my cluster will have the pods as below:

$ kubectl get pods -n kube-kafka-zk
NAMESPACE           NAME                   READY   STATUS             RESTARTS   AGE
kube-kafka-zk   XXXX-zk-0              1/1     Running            0          5m15s
kube-kafka-zk   XXXX-zk-1             1/1     Running            0          5m15s
kube-kafka-zk   XXXX-zk-2             1/1     Running            0          4m23s
kube-kafka-zk   XXXX-kf-0              1/1     Running            0          8m26s
kube-kafka-zk   XXXX-kf--1              1/1     Running            0          8m1s
kube-kafka-zk   XXXX-kf--2              1/1     Running            0          6m13s

Now, when I delete one of the pod to ensure the k8s brings up new new pod to balance the minimum and desire replica. The one pod that newly comes up is not able to join the cluster, until the "Peer Authentication" is disabled

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The newly created pod should join the cluster

**Steps to reproduce the bug**

1. An AWS EKS cluster with Kafak installed on it, it has the following dimensions
* Zookeeper - 3 replicas
* Kafka - 3 replicas

2. Enable the peer authentication
3. Delete one of the Kafka pod -> kubectl delete pod <pod-name> -n <namespace>
4. EKS identifies that the cluster is one short of the desired state, it create new pod
5. The new pod should join the cluster but crashes out
6. Disable the peer authentication by overriding the MODE from mode: STRICT to mode: DISABLED
7. the new pod now joins the cluster

This way, the scaling up and down of the pods based on traffic will be cumbersome.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
$ istioctl version --remote
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (3 proxies)

*********
$ kubectl version --short
Client Version: v1.21.2
Server Version: v1.18.20-eks-8c579e
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
We would need some more info like the config dumps and access logs (and maybe zk logs) to see what is going on. It's interesting it initially works and only scale up fails

**Comment by vinothgj** [comment]
One thing that I mentioned it incorrect was that, I have spun up all the containers and the injection of side car container did happen. Then, I enabled the peer-authentication.

**Comment by vinothgj** [comment]
> One thing that I mentioned it incorrect was that, I have spun up all the containers and the injection of side car container did happen. Then, I enabled the peer-authentication.

**Comment by vinothgj** [comment]
Attached
[logs.zip](https://github.com/istio/istio/files/6944092/logs.zip)
 the logs

**Comment by vinothgj** [comment]
@howardjohn  did you get any clue to suggest us. Please revert back, if you have any suggestions.

**Comment by su225** [comment]
@vinothgj - What are the Istio sidecar logs (access logs)? This line - `KeeperErrorCode = ConnectionLoss for /` only says it is not connecting successfully but does not say anything else. I assume that the sidecar is starting up properly. Works without `PeerAuthentication` indicates mTLS issue. Could you also attach filter chain configs (Envoy config dump) for both sides - ZK and Kafka when mTLS mode is `STRICT`? Service and deployment configs, particularly port configs (names are important!) would be useful!
