### ISSUE TITLE
Envoy expects IPv6 address within '[]' for domains under route_config

### ISSUE THREAD

**Issue by sridharlreddy** [istio/istio#34533]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Virtual Service with IPv6 address hosts field are added as numerical address for envoy but envoy expects them to be in within brackets '[]' resulting in throwing Route Not Found error

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Domains with IPv6 address should have brackets
```  "name": "2406:3003:2064:35b8:864:a648:4b96:e37d:80",
  "domains": [
    "[2406:3003:2064:35b8:864:a648:4b96:e37d]",
    "[2406:3003:2064:35b8:864:a648:4b96:e37d]:80"
  ],
```
**Steps to reproduce the bug**
```
➜   kg vs test -o yaml | k neat
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test
  namespace: default
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  - 2406:3003:2064:35b8:864:a648:4b96:e37d
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
```
```
➜ istioctl pc r httpbin-74fb669cc6-f4vfz.istio --name 80 -o json | jq '.[].virtualHosts[] | select(.name=="2406:3003:2064:35b8:864:a648:4b96:e37d:80")'
{
  "name": "2406:3003:2064:35b8:864:a648:4b96:e37d:80",
  "domains": [
    "2406:3003:2064:35b8:864:a648:4b96:e37d",
    "2406:3003:2064:35b8:864:a648:4b96:e37d:80"
  ],
  "routes": [
    {
      "match": {
        "prefix": "/"
      },
      "route": {
        "cluster": "outbound|8000||httpbin.default.svc.cluster.local",
        "timeout": "0s",
        "retryPolicy": {
          "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
          "numRetries": 2,
          "retryHostPredicate": [
            {
              "name": "envoy.retry_host_predicates.previous_hosts"
            }
          ],
          "hostSelectionRetryMaxAttempts": "5",
          "retriableStatusCodes": [
            503
          ]
        },
        "maxStreamDuration": {
          "maxStreamDuration": "0s"
        }
      },
      "metadata": {
        "filterMetadata": {
          "istio": {
            "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/test"
          }
        }
      },
      "decorator": {
        "operation": "httpbin.default.svc.cluster.local:8000/*"
      }
    }
  ],
  "includeRequestAttemptCount": true
}

```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.5

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I am a bit suspicious of this... I feel like clients may not put the brackets? Clearly yours is which is why it isn't working,but not as a general rule?

Envoy isn't matching an "ip" it's just a raw string match

**Comment by sridharlreddy** [comment]
> I am a bit suspicious of this... I feel like clients may not put the brackets? Clearly yours is which is why it isn't working,but not as a general rule?
> 
> Envoy isn't matching an "ip" it's just a raw string match

Yes, you are right, ip is raw string match. IPv6 addresses in URIs are always enclosed in brackets followed by port number  else port number cannot be identified as ':' is delimeter. Hence same name should be given for envoy. 

So, either the hosts regex validation needs to be updated to support ipv6 with brackets or to add brackets if it is ipv6 address under domains while pushing envoy config. I think first one is more clean and simpler but user should be aware to give with brackets. What do you think @howardjohn ? I can make the fix and push once you confirm.

**Comment by howardjohn** [comment]
Ok after reviewing some HTTP clients and specs:

https://tools.ietf.org/html/rfc7230#section-5.4
https://tools.ietf.org/html/rfc3986#section-3.2.2

I think its clear the bracket is required, and we should add brackets to ipv6 addresses while pushing config

**Comment by howardjohn** [comment]
And virtual service spec clearly says `Could be a DNS name with wildcard prefix or an IP address.` so IP is valid here

**Comment by sridharlreddy** [comment]
> Ok after reviewing some HTTP clients and specs:
> 
> https://tools.ietf.org/html/rfc7230#section-5.4
> https://tools.ietf.org/html/rfc3986#section-3.2.2
> 
> I think its clear the bracket is required, and we should add brackets to ipv6 addresses while pushing config

Ok, so the fix is 
 - Add brackets if ipv6 address under route_config/domain while pushing config
 - No change in virtualservice spec to allow brackets, only IP is valid
 - No change in endpoints if address is ipv6 as IP and port are captured with different attributes
