### ISSUE TITLE
Does Cluster-Wide Strict mTLS Break Admission Controllers?

### ISSUE THREAD

**Issue by jsievenpiper** [istio/istio#34543]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Apologies if this is not the right spot -- I've been trying to slowly tweak configuration and pieces one-by-one and I think I've narrowed it down to here, but let me know if you think this belongs elsewhere.

I have a cluster where I'm trying to build a zero-trust network following the patterns outlined by Calico + Istio. Notably my cluster has a `STRICT` PeerAuthentication policy installed in the `istio-system` namespace. In general, things are working _great_ across normal workloads. 🥳 

I have two installations that leverage admissions controllers that both seem to be struggling though: `vault` and `cert-manager`. Both of these services run fine (they can be queried from other pods when network policy allows, vault-ui is accessible via an ingress gateway, etc), but their webhooks on admission of new pods both fail with similar errors: connectivity issues to the `kubernetes` service. `kube-system` pods do not have istio sidecar injected (that seems to be the recommendation). FWIW, `default` has no running workloads (but the `kubernetes` service is exposed there) so there's no sidecar injection enabled on that namespace either, it if impacts anything.

What is the recommendation here? I couldn't find anything in the documentation about this specifically -- if I can get an approved recommendation here I'm happy to update some docs to include a recipe for future users. In particular I suspect cert-manager + istio mTLS is a fairly common combination, so maybe I'm just missing something obvious. 😅 

Thanks in advance!

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Workloads should be able to communicate with the kubernetes service.

**Steps to reproduce the bug**
- Install istio with strict mTLS
- Install something with an admission controller into a namespace with `istio-injection=enabled`. Simple one is cert-manager
- Install works fine, connectivity fine 👍🏾 
- Install something that triggers the webhook (for cert-manager, try to install an `Issuer`
- Connectivity issues to the kubernetes service 👎🏾 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Hel`m)
```
istioctl version --remote
client version: 1.9.1
control plane version: 1.10.0
data plane version: 1.10.0 (7 proxies)
```
```
kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.3+k3s1
```
```
helm version --short
v3.6.2+gee407bd
```

**How was Istio installed?**
helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
bare metal, k3s on rpi4b

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
> Connectivity issues to the kubernetes service 👎🏾

Is this where it's failing? Or is the webhook call *from* the api server failing?

I would expect the latter since the API server does not send mtls requests and they should therefore be rejected

**Comment by jsievenpiper** [comment]
@howardjohn sorry for the delay in getting back to you!

> Or is the webhook call from the api server failing?

Sorry for my miscommunication -- I think that _both_ may be occurring (the webhook attempts to list secrets inside it's namespace and is failing to make that request), but almost certainly the second is occurring. From the k8s logs:

```
W0804 23:28:12.655297 2184776 dispatcher.go:182] Failed calling webhook, failing closed webhook.cert-manager.io: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
```

Should the `kube-system` namespace be part of the mTLS setup (assuming I'd like to build toward whatever Istio would recommend as the best practice for "strict" mTLS)? Is it as simple as configuring it as any other workload?

**Comment by howardjohn** [comment]
It's a very bad idea to do that - I might go as far as to say it's impossible. There is a circular dependency if you have kube-system injected

**Comment by jsievenpiper** [comment]
Cool, totally reasonable (and makes sense)! Feel free to point me at the docs at any time if this is listed anywhere, but is the recommendation then to create a policy that excludes kube-system from part of the strict mTLS requirement? 

The docs mentioned often for best security to enable mTLS, so I'd like to do that on this fresh cluster, but don't mention how you'd actually make that work without losing that functionality. Anything else that should be kept in mind? I'm happy to write up some documentation but wouldn't want to recommend or configure anything in a way that doesn't encourage the right usage pattern for this type of network.

**Comment by howardjohn** [comment]
> excludes kube-system from part of the strict mTLS requirement?

The unfortunate part is the way we know the traffic is from kube-system is... mtls. Which we do not have since.

Afaik the best that can be done is to use permissive mtls on that pod. This can be scoped to even a single port, so if you had  a port dedicated to the webhook you could have only that one allow non-mtls traffic
