### ISSUE TITLE
Prototyping authentication policy config in service config and consumer config

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3455]
design doc: https://docs.google.com/document/d/1ShSLKzDaexJ81FnTM_UEVZq2qtJa7jphDdJ1Xuqx6Dw/edit

**Comment by ozevren** [comment]
@diemtvu is this still relevant? Was there an outcome?

**Comment by diemtvu** [comment]
I'm not aware of Istio config progress in the loop anymore :). However, on authn side, authn policy is now in CRD. I think we can close this for now, and sync back again once we need to test with istio config/galley. Wdyt?
