### ISSUE TITLE
Jaeger - volume for logs

### ISSUE THREAD

**Issue by ognjen-it** [istio/istio#34559]
**Describe the feature request**
Jaeger as the part of the Istio doesn't have volume and because of that, I must delete the pod every 7 days because Jaeger's logs are very big. If I don't delete the pod, the Kubernetes node would be blocked.

**Describe alternatives you've considered**
I tied to edit the deployment script, but I think that it's not a good way.

[ x ] Installation
[ x ] Performance and Scalability

**Additional context**

**Comment by howardjohn** [comment]
The addon yaml we provide is merely a sample to get quickly started for demos, etc. It's not intended for production use - each project has their own production ready deployment methods they maintain that are recommended for those use cases
