### ISSUE TITLE
In place upgrade from 1.9 to 1.10 causes mutating webhook overlap: error [IST0139]

### ISSUE THREAD

**Issue by tbcardoso** [istio/istio#34562]
**Bug description**

We did and in-place upgrade following the [documented instructions](https://istio.io/latest/docs/setup/upgrade/in-place/) from Istio 1.9.7 to 1.10.3. Everything is working fine except that running `istioctl analyze --all-namespaces` returns the following errors:

```
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/sidecar-injector.istio.io]. This may cause injection to occur twice.
```
This errors were not present before the upgrade.

Injection seems to be working correctly though.

Here is the offending MutatingWebhookConfiguration: [sidecar-injector.yml.txt](https://github.com/istio/istio/files/6946780/istio-sidecar-injector.yml.txt)

From my understanding, the admissionReviewVersion named `sidecar-injector.istio.io` should have been removed during the upgrade. Deleting it manually, the errors from `istioctl analyze` disappear and injection continues working.

For now we only did the upgrade in a test cluster, so my question is, is it safe to do the manual deletion mentioned above after upgrading to version 1.10?

Even better would be for the upgrade process to be patched so that this is done automatically.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

The upgrade should result in a valid `MutatingWebhookConfiguration` without overlapping webhooks.

**Steps to reproduce the bug**

Do an in-place upgrade from Istio 1.9.7 to 1.10.3 using `istioctl upgrade -f operator.yaml`.

**Version**

```
$ istioctl version --remote
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (11 proxies)
```

```
$ kubectl version --short
Client Version: v1.21.3
Server Version: v1.20.8-gke.900
```

**How was Istio installed?**

Installed with istioctl following the [documentation](https://istio.io/latest/docs/setup/install/istioctl/).

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE.

**Comment by howardjohn** [comment]
Looks like its merging the webhooks field, when it should be removing the old one.

cc @Monkeyanator

**Comment by howardjohn** [comment]
I also saw the same with real impact from a real old version; it was pointing to the old istio-sidecar-injector service and broke

**Comment by djfinnoy** [comment]
Experiencing the same issue on a fresh GKE cluster with a fresh Istio Operator installation; it's not just a problem when upgrading.

**Comment by deveshkandpal24121990** [comment]
Seeing the same issue in istio-operator logs after upgrading to `b6045c66ad57c3cb09e41a4710137169cbfd9237 `

**Comment by howardjohn** [comment]
on a fresh install? or upgrade? on fresh install seems extremely unexpected

**Comment by deveshkandpal24121990** [comment]
@howardjohn - on upgrade.

**Comment by dgn** [comment]
dropping this to a P1 as it hasn't seen any updates in a while. is this still affecting users?

**Comment by victorhaggqvist** [comment]
Reporting from kubeadm managed 1.23.1 on debian, upgrading 1.11.0 -> 1.12.1, executing upgrade with istioctl 1.12.1 gives
```
info	Error: failed to apply the Istio Control Plane specs. Error: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/sidecar-injector.istio.io]. This may cause injection to occur twice.

Error: failed to apply the Istio Control Plane specs. Error: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/sidecar-injector.istio.io]. This may cause injection to occur twice.
```

However executing upgrade using istioctl 1.11.0 with Operator config for 1.12.1 logs no error, but re-executing upgrade with istioctl 1.12.1 (having already upgraded) the above error is still logged.

**Comment by quentinleclerc** [comment]
Upgrading to 1.12.1 from 1.11.x also gives me this error, blocking the installation from the operator. It disappears when I delete the MutatingWebhookConfiguration and the operator pursue the installation, but the error always reappear in the operator logs. It seems to be some sort of conflict between the namespaced webook and a global one?

```
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-system/istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-system/istio-sidecar-injector/object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-system/istio-sidecar-injector/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-system/istio-sidecar-injector/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector ) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector ) Webhook overlaps with others: [istio-sidecar-injector/object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector ) Webhook overlaps with others: [istio-sidecar-injector/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-system/istio-sidecar-injector ) Webhook overlaps with others: [istio-sidecar-injector/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

**Comment by sukrit007wawa** [comment]
This issue seems to be related to https://github.com/istio/istio/issues/36114   .  Trying to see if there is a workaround for the same?
