### ISSUE TITLE
sidecar will not work when injected in control plane deployments that use CNI

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#34560]
1. Install Istio 1.11 with CNI enabled (I did this on an OpenShift 4 cluster, installed via the "openshift" profile)
2. Inject a sidecar (manual or automatic, doesn't matter) on a deployment in the control plane namespace (for example, inject a sidecar on Kiali, or Grafana, or etc. addon)
3. Watch the deployment fail

The istio-validation container fails:

```
2021-08-06T13:32:10.470667Z	info	in new validator: 10.130.1.103
2021-08-06T13:32:10.471106Z	info	Listening on 127.0.0.1:15001
2021-08-06T13:32:10.471462Z	info	Listening on 127.0.0.1:15006
2021-08-06T13:32:10.471813Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
```

Thus causing the entire deployment to fail to deploy successfully. There is no easy way to find out that this is the error (there are no events indicating an error in the pod, replicaset, or deployment) - you have to hurry up before the pod disappears to examine the istio-validation container logs to get any error messages. So to a user, it is difficult to understand where the error occurs.

Ultimately, what this means is on an Istio deployment _that uses CNI_ (well, technically, that uses CNI and the deployment is in one of the excluded_namespaces declared in the CNI config), you cannot have sidecars on any deployment running in the control plane namespace. (this is not a restriction on a non-CNI deployment - e.g. I can see this work fine on minikube without CNI). If you want a sidecar on a deployment, it must be outside of the control plane namespace (or, more technically, in any excluded_namespace, but the control plane is the obvious one that people would want to use).. e.g. install Kiali or Grafana in its own namespace to work around this.

This is, at least, a documentation issue - it should be documented somewhere. I could not find this mentioned in the sidecar docs page: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/

I saw something that implies this here: https://istio.io/latest/docs/setup/additional-setup/cni/#identifying-pods-requiring-traffic-redirection
But all it says is "The pod is NOT in a Kubernetes namespace in the configured exclude_namespaces list." Of course, when installing with, say, the "openshift" profile, the user has no idea what namespaces are in that list, so it isn't obvious this is what is stopping the deployment from successfully deploying.

**Comment by bianpengyuan** [comment]
In preliminary 1.11 troubleshooting doc we include a section about pod start up failure and example log messages of istio-validate: https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/cni/#diagnose-pod-start-up-failure. Let me know if this helps.

Meanwhile I think we need to refine the istio-validate log message. Will take a stab on this.

**Comment by howardjohn** [comment]
```
      excludeNamespaces:
       - istio-system
       - kube-system
```

Its largely a configuration error due to ^... but not sure why we even have that in CNI - seems like injectors responsibility to decide which namespaces to inject, and CNI should program anything injected?

**Comment by jmazzitelli** [comment]
> Let me know if this helps.

That really would not have helped me. I kind of already understood the problem was with the sidecar failing to initialize. And that doc would have only confirmed that. But it did not tell me the cause. What I did not know was that this is simply expected because I was injecting a sidecar in a pod that was in a namespace found in the CNI excludedNamespaces list.

**Comment by bianpengyuan** [comment]
>  CNI should program anything injected?

Good point, I think we can probably remove the default exclusion.

> But it did not tell me the cause

Ok I can call out checking excluding namespace. Meanwhile at 1.11, there should be log in istio-cni-node daemonset mentioning that why the pod is set up is failing (ignored because of namespace exclusion).
