### ISSUE TITLE
How locality load balancer work with outlier detection?

### ISSUE THREAD

**Issue by masquee** [istio/istio#34605]
**Describe the feature request**

For example, I have a service which has 50% pods resident in locality `region-1`, and another 50% pods resident in `region-2`, and `maxEjectionPercent` is set to `20%`.

When pods of `region-1` of this service crashed entirely, requests from client  in `region-1` to this service will always fail. All of these requests are send to pod in `region-1`(priority is 0), but will not send to  pods in  `region-2` because some pods in `region-1` are not ejected (thus envoy mark its healthy).

The only way I known to solve this is to set `maxEjectionPercent` up to `50%`. Are there any other solutions?

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
Other than ejection setup, you may need enable `RetryRemoteLocalities` as well.
