### ISSUE TITLE
Update all-presets updates

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#34616]
In 1.11, most istio-private jobs are generated automatically. However, the all-presets file is still missing and must have a manual PR opened to update it. This should be automated as part of the job generation

https://github.com/istio/test-infra/pull/3500/files

**Comment by howardjohn** [comment]
Should we even use presets? instead of the "requirements" stuff in the job generation. We basically have two "preset" concepts

**Comment by howardjohn** [comment]
maybe that doesn't really help here at all though
