### ISSUE TITLE
Investigate SA ordering determinism

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34617]
Context: https://discuss.istio.io/t/istiod-full-push-every-5m/11072/2

Based on https://github.com/istio/istio/blob/3732855046e1212a923d344bc1d68771159ab58e/pilot/pkg/model/service.go#L703 seems not sorted, unless we sort somewhere else I missed

cc @hzxuzhonghu @ramaraochavali

**Comment by hzxuzhonghu** [comment]
We have sorted it in aggregator.GetIstioServiceAccounts

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/blob/9ece4910f6ca7433ef62c271e849078360fbcebc/pilot/pkg/serviceregistry/aggregate/controller.go#L343

**Comment by howardjohn** [comment]
nice, I missed that. Maybe it was just an issue in old version then

**Comment by hzxuzhonghu** [comment]
Yes, i have asked there
