### ISSUE TITLE
ExternalAuthz does not support localhost based provider

### ISSUE THREAD

**Issue by incfly** [istio/istio#34622]
**Bug description**

somtimes customer may want to deploy a ext authz within the same container and use the localhost (or 127.0.0.1) for the ext authz service address. However when make such config change, I see the Istiod will complain there's no such service within the registry.

More of a question: can we use passthrough cluster for this case? Or we require users to write a service entry?

---

version, istio 1.9.

meshconfig

```yaml
data:
  mesh: |-
    extensionProviders:
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "127.0.0.1"
        port: "10003"
```

istiod log

```
2021-08-10T23:15:45.216781Z     error   authorization   Processed authorization policy for productpage-v1-cf596fdb6-r7p8r.default, failed to process CUSTOM action: found errors in provider sample-ext-authz-grpc: 1 error occurred:
        * failed to parse extension provider "sample-ext-authz-grpc": could not find service 127.0.0.1 in Istio service registry
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
service is a hostname I think. You should make a service entry pointing to localhost instead. I think there's actually a sample for this in samples/

**Comment by yangminzhu** [comment]
There is an example service entry in the task: https://istio.io/latest/docs/tasks/security/authorization/authz-custom/#deploy-the-external-authorizer. You can also take a look at the e2e test that also covers this use case.

**Comment by incfly** [comment]
thanks, closing the issue.
