### ISSUE TITLE
TestClusterLocal test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34638]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1425491171118944256

Regression in https://github.com/istio/istio/pull/34480

**Comment by hzxuzhonghu** [comment]
I still find one failure https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36269/integ-pilot-multicluster-tests_istio/1464412803237416960

**Comment by hzxuzhonghu** [comment]
<html>
<body>


pilot: TestClusterLocal/cross_cluster/remote expand_less | 26s
-- | --
multicluster_test.go:137: failed calling a (cluster=remote)->'http://b.echo-1-71970.svc.cluster.local:80/': call failed from a (cluster=remote) to http://b.echo-1-71970.svc.cluster.local:80 (using http): timeout while waiting after 109 attempts (last error: did not reach all of [remote cross-network-primary primary], got map[primary:4 remote:5])


</body>
</html>
