### ISSUE TITLE
TestGateway flake: need wait for CRD establishment

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34645]
Example: https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion-k8s-tests_istio_postsubmit/1425529789149614080

There is a race between create CRD and apply CR: https://github.com/istio/istio/blob/ecc1d637f0296c67aa73cd062714a5bcab604d37/tests/integration/pilot/ingress_test.go#L62

Should wait there

**Comment by su225** [comment]
Wait....If `ApplyYAMLOrFail` has race condition, then doesn't that cause trouble all over the place?

**Comment by howardjohn** [comment]
It only applies for this specific test. When we install istio CRDs we do
`istioctl install`, which already waits for CRDs to be established. But for
gateway api, we just kubectl apply them then immediately apply instances of
them. See
https://github.com/istio/istio/blob/9e452308626365014390bf5cb131f3bfc83e94e3/operator/pkg/helmreconciler/wait.go#L172

**Comment by zhlsunshine** [comment]
PR was merged and close this issue
