### ISSUE TITLE
ProxyConfig overrides via "proxy.istio.io/config" are applied to all pods

### ISSUE THREAD

**Issue by Regevd** [istio/istio#34657]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

ProxyConfig overrides via "proxy.istio.io/config" are applied to all pods

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

"proxy.istio.io/config"  annotation should be applied only to the parent pod

**Steps to reproduce the bug**
add this annotation to a pod with Istio injection enabled
`
    annotations:
      proxy.istio.io/config: |
        proxyMetadata:
          TEST: ONLY_THIS_POD
`
create another pod w/o that annotation.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.3

**How was Istio installed?**
 istioctl install
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

solution:
https://github.com/istio/istio/pull/34654

**Comment by Regevd** [comment]
a suggested solution can be found here https://github.com/istio/istio/pull/34654

**Comment by howardjohn** [comment]
I cannot reproduce. Can you help?

**Comment by Regevd** [comment]
istioctl version 1.10.3

1. $ istioctl install

2. apply 

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            TEST: TEST
      labels:
        sidecar.istio.io/inject: "true"
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin

`

3. wait till pod created

4. apply
`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-no-config
spec:
  selector:
    matchLabels:
      app: httpbin-no-config
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: httpbin-no-config
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
`

5. kubectl get pod httpbin-no-config-... -ojson | jq 'try .spec.containers[0].env[-1]'
or any other way to get the new pod's envoy env vars

you would see 
`
name: TEST
value: TEST 
`
in env vars

**Comment by howardjohn** [comment]
Huh, I do see it now. Thanks!!

**Comment by ramaraochavali** [comment]
@howardjohn What is the issue? We are using proxyConfig to set different config from few proxies - basically override metadata , but we do not see it. Curious what is the problem?

**Comment by Regevd** [comment]
> @howardjohn What is the issue? We are using proxyConfig to set different config from few proxies - basically override metadata , but we do not see it. Curious what is the problem?

U can find the problem and a solution in #34654 
ApplyMeshConfig applies overrides to the default config which is being later used to configure proxies of other pods with no overrides

**Comment by ramaraochavali** [comment]
But source of my confusion is `ApplyMeshConfig` should not be called when proxy is being injected with `proxy.istio.io/config` annotation. Can you point me to the code that calls `ApplyMeshConfig` when proxy is injected with that annotation? We should only call `ApplyProxyConfig` ?

**Comment by Regevd** [comment]
'proxy.istio.io/config' annotation is indeed applied by 'ApplyProxyConfig'.
but both  'ApplyMeshConfig' and 'ApplyProxyConfig' have the same issue - applying the overrides on the default config. this pr fixes them both.

**Comment by ramaraochavali** [comment]
Sorry for being dense on this but does not this test case validate that case https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh_test.go#L61?

As I mentioned here https://github.com/istio/istio/pull/34654#issuecomment-897644120 the test case works fine in master and validates that default is not overridden?

**Comment by howardjohn** [comment]
I can reproduce on 1.10 but not master. or 1.11.0.

**Comment by ramaraochavali** [comment]
> I can reproduce on 1.10 but not master. or 1.11.0.

Thanks for confirming. That makes sense to me :-)

**Comment by howardjohn** [comment]
and 1.10.2 is fine, just not 1.10.3

**Comment by Regevd** [comment]
> https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh_test.go#L61

```
	t.Run("apply proxy metadata", func(t *testing.T) {
		**config** := mesh.DefaultMeshConfig()
		config.DefaultConfig.ProxyMetadata = map[string]string{
			"merged":  "original",
			"default": "foo",
		}
		**mc**, err := mesh.ApplyProxyConfig(`proxyMetadata: {"merged":"override","override":"bar"}`, **config**)
		if err != nil {
			t.Fatal(err)
		}
		// Ensure we didn't modify the passed in mesh config
		if !reflect.DeepEqual(**mc**.DefaultConfig.ProxyMetadata, map[string]string{

			"merged":   "override",
			"default":  "foo",
			"override": "bar",
		}) {
			t.Fatalf("unexpected proxy metadata: %+v", mc.DefaultConfig.ProxyMetadata)
		}
	})
```
this test validates the value of `mc`, the output of `ApplyProxyConfig`, not the default config.
there is a mismatch between the comment and what the condition really checks.
For ensuring that we didn't modify the passed in mesh config the value of `config` should be compared to its initial value.
In #34654 there is a condition that verifies the value of `config` and it fails on master

**Comment by howardjohn** [comment]
I am not sure where that actually ends up mattering in real world though? Since nothing is referencing the modified proxy config anymore, as the passed in `mc` is updated?

**Comment by Regevd** [comment]
yeah, you're right, it doesn't matter in the real world. 
#34745 and adding your test to master are enough for fixing the bug.
I just don't like to see a function that behaves differently than expected.
