### ISSUE TITLE
Istio 1.9 and older fails on Kubernetes 1.22+

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34665]
When upgrade to Kubernetes 1.22+ and Istio version 1.9 or older, you may see the following errors:

In existing Istiod pods:
```
error   klog    k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.IngressClass: failed to list *v1beta1.IngressClass: the server could not find the requested resource
error   klog    k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.MutatingWebhookConfiguration: failed to list *v1beta1.MutatingWebhookConfiguration: the server could not find the requested resource
error   klog    k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.IngressClass: failed to list *v1beta1.IngressClass: the server could not find the requested resource
```

In new pods (and Istiod fails to startup):
```
 error   kube    failed to list CRDs: the server could not find the requested resource
```

If you see these issues, please upgrade to Istio 1.10+ (preferably Istio 1.11). See https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases for more information, and https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/ for the reason these changes have occurred.

**Comment by shwsingh** [comment]
https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases 

We should update this page and link the error with it

**Comment by clsacramento** [comment]
John, this affect 1.10.2 also, right? Can update the title to make that clear?
