### ISSUE TITLE
Pilot can discover labels for standalone proxies

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#3467]
we should add a new function to the service-registry interface:

```go
type ServiceDiscovery interface {

  // ...

  // GetProxyLabels will return labels associated with a given proxy
  // These labels are used when determining which Gateways to attach to the proxy
  //
  // When a proxy is a sidecar, the returned labels should include all labels
  // of all service instances co-located with the sidecar.
  //
  // When a proxy is a standalone router (e.g. ingress or egress), the labels
  // may describe the workload hosting the router.
  GetProxyLabels(model.Proxy) Labels
}
```

ref: [mailing list conversation](https://groups.google.com/d/msg/istio-networking/htxJDpZO-G8/t3qU5bRbBwAJ)

cc: @rshriram

**Comment by rshriram** [comment]
I thikn this function is present, isn't it?

**Comment by rosenhouse** [comment]
@rshriram 

I don't see it [in the `ServiceDiscovery` interface on master right now](https://github.com/istio/istio/blob/645c453b3b17022fa36259a6a589654a82afd731/pilot/pkg/model/service.go#L262-L314).

Have we addressed the underlying need some other way?
