### ISSUE TITLE
Improve Auto-detect HTTP Headless Services

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34679]
Route config for auto headless service:
```
      "name": "alertmanager-operated.default.svc.cluster.local:9093",
      "virtual_hosts": [
       {
        "name": "alertmanager-operated.default.svc.cluster.local:9093",
        "domains": [
         "alertmanager-operated.default.svc.cluster.local",
         "alertmanager-operated.default.svc.cluster.local:9093",
         "alertmanager-operated",
         "alertmanager-operated:9093",
         "alertmanager-operated.default.svc",
         "alertmanager-operated.default.svc:9093",
         "alertmanager-operated.default",
         "alertmanager-operated.default:9093",
         "*.alertmanager-operated.default.svc.cluster.local",
         "*.alertmanager-operated.default.svc.cluster.local:9093",
         "*.alertmanager-operated",
         "*.alertmanager-operated:9093",
         "*.alertmanager-operated.default.svc",
         "*.alertmanager-operated.default.svc:9093",
         "*.alertmanager-operated.default",
         "*.alertmanager-operated.default:9093"
        ],
```

Route config for auto non-headless:
```
       {
        "name": "echo.default.svc.cluster.local:80",
        "domains": [
         "echo.default.svc.cluster.local",
         "echo.default.svc.cluster.local:80",
         "echo",
         "echo:80",
         "echo.default.svc",
         "echo.default.svc:80",
         "echo.default",
         "echo.default:80",
         "10.96.75.204",
         "10.96.75.204:80"
        ],
```

This means that with non-headless, I can do `curl IP`. With headless, I cannot.

In the real world, this breaks alertmanager, which is an extremely common deployment.

Because the route is already scoped to the Pod IP (for headless) and cluster IP (for non-headless), I think in all cases of auto-HTTP we should have domains be `*` only.

**Comment by howardjohn** [comment]
BUG: For `http` headless, we generate routes like:
```
       {
        "name": "headless.echo.svc.cluster.local:18080",
        "domains": [
         "headless.echo.svc.cluster.local",
         "headless.echo.svc.cluster.local:18080",
         "headless",
         "headless:18080",
         "headless.echo.svc",
         "headless.echo.svc:18080",
         "headless.echo",
         "headless.echo:18080",
         "*.headless.echo.svc.cluster.local",
         "*.headless.echo.svc.cluster.local:18080",
         "*.headless",
         "*.headless:18080",
         "*.headless.echo.svc",
         "*.headless.echo.svc:18080",
         "*.headless.echo",
         "*.headless.echo:18080"
        ],
```

These are never referenced anywhere!

**Comment by howardjohn** [comment]
Hmm.. route config for headless `http` is like:
```
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "18080",
      "virtual_hosts": [
       {
        "name": "allow_any",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "PassthroughCluster",
           "timeout": "0s",
           "max_grpc_timeout": "0s"
          },
          "name": "allow_any"
         }
        ],
        "include_request_attempt_count": true
       },
       {
        "name": "headless.echo.svc.cluster.local:18080",
        "domains": [
         "headless.echo.svc.cluster.local",
         "headless.echo.svc.cluster.local:18080",
         "headless",
         "headless:18080",
         "headless.echo.svc",
         "headless.echo.svc:18080",
         "headless.echo",
         "headless.echo:18080",
         "*.headless.echo.svc.cluster.local",
         "*.headless.echo.svc.cluster.local:18080",
         "*.headless",
         "*.headless:18080",
         "*.headless.echo.svc",
         "*.headless.echo.svc:18080",
         "*.headless.echo",
         "*.headless.echo:18080"
        ],
```

So we can make auto HTTP headless work, but not explicit HTTP headless (without taking perf hit of 1 listener per pod).

This would lead to a strange result where "auto" is better than explicit in this case. However, there is seemingly no other downside.. 

The being said, "auto" is about migration/adoption mostly. So its important we work out of the box with applications that may not send "istio conformant" traffic; whereas apps that are declaring themselves as `http` are _more likely_ to be Istio conformant, unless they just happened to label themselves as HTTP for non-Istio reasons.

**Comment by howardjohn** [comment]
Test showcasing current behavior: https://github.com/istio/istio/pull/34680

**Comment by hzxuzhonghu** [comment]
@howardjohn It is not suggested to access headless service pod by IP address.  Does `alertmanager` access by pod ip?

**Comment by howardjohn** [comment]
Yes, I think its very common. That is why headless is used, so they can access the pod IP

**Comment by hzxuzhonghu** [comment]
Headless service pod can be accessed by a domain too.

**Comment by JWT95** [comment]
Hi,

Thanks for the fix to this Issue.

To summarise the change:
1. curl <Pod IP>:<port> will now work if the pod is in a headless service and the port is not named http...
2. curl <Pod IP>:<port> will continue to not work if the pod is in a headless service, the port is named http and strict mTLS is required

Is that correct? If so, do you know roughly how long it'' take the fix to make it into an official release? I'm fairly new to the Istio repo

Scenario 2 is of interest to me. I'm trying to get Prometheus metrics scrapes TLS uplifted and:
- There are some services that expose metrics on ports named http-metrics (e.g. Prometheus' scraping for [kube-proxy](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-proxy/service.yaml#L14))
- Prometheus sends traffic to each Pod IP. This means that the hostname is set to the Pod IP

Is there are any scope for 2 to be fixed? You noted for explicit http headless we'd need a listener per pod. Is that needed, or would a domain entry for each Pod IP in the route config suffice?

**Comment by JWT95** [comment]
Ok thanks, that's a shame.

Do you know if there is a workaround for scenario 2 in my message above?

If you've got control of the service definition then you can rename the port to tcp (or auto once this fix goes in).

But if you don't have control of the service definition, is there a way to configure Istio to allow accessing the Pod IP directly for a headless service while performing TLS uplift?
