### ISSUE TITLE
ISTIOD/Pilot proxy support 

### ISSUE THREAD

**Issue by DaxterM** [istio/istio#34686]
Istiod pilot does not read HTTP,HTTP,and NO_PROXY environment variables. This blocks GKE clusters that rely on HTTP Proxies to get out to the internet from using MESH CA 
https://github.com/istio/istio/blob/da6178604559bdf2c707a57f452d16bee0de90c8/pkg/spiffe/spiffe.go#L193

**Comment by yangminzhu** [comment]
cc @shankgan @myidpt @howardjohn

**Comment by yangminzhu** [comment]
Should be fixed by https://github.com/istio/istio/pull/34685.
