### ISSUE TITLE
promote XDS versions of 'istioctl version' and 'proxy-status'

### ISSUE THREAD

**Issue by esnible** [istio/istio#34683]
Currently, `istioctl experimental version` and `x proxy-status` use XDS, but the regular version does not.  (And therefore doesn't work with external Istiod).

The goal is the have the main versions of the commands first try to use XDS, then fallback to strategies that require in-cluster control-plane.

**Comment by zhlsunshine** [comment]
Hi @esnible, is there anybody take this one?  I can take it if no one. Thanks!
