### ISSUE TITLE
attribute mapping and alignement

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#347]
This issue to track alignment and ideally consensus across systems on naming, including for tracing too (aka Open Tracing and other domain standards)  [extracted from email thread]

As we won't have a single standard across everything it's safe to say we will need to map from one set of attributes to others and build that component and configuration

**Comment by ayj** [comment]
This issue hasn't seen real activity in ~11 months. Can we close it? cc @geeknoid @douglas-reid

**Comment by geeknoid** [comment]
Yeah, we'll open specific issues as they come up.

**Comment by ldemailly** [comment]
I don't think this has been addressed, that there is no recorded activity doesn't mean something isn't an issue. But I will let the responsible party handle it the way they desire.
