### ISSUE TITLE
Support MCP-over-XDS delta push besides full push

### ISSUE THREAD

**Issue by Xunzhuo** [istio/istio#34703]
**Describe the feature request**

Support MCP-over-XDS delta push besides full push

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Additional context**

**Comment by wtzhang23** [comment]
Update on this issue?
