### ISSUE TITLE
Best practices when upgrading k8s version

### ISSUE THREAD

**Issue by jl3yr** [istio/istio#34726]
I'm looking to understand more about how istio handles requests during k8s upgrades. We've seen some reliability drops during these upgrades due to "Unexpected end of request content" which I believe is due to the ingress gateways terminating the request before the workload pod can finish reading the payload. 

We have isolated node pools for ingress gateways and for workload which is an API service and K8s can take down multiple nodes at a time. We have pod disruption budget to ensure at least 50% of both workload and istio pods are running. Looking at our ingress pod ages, it looks like during the upgrade, 3/100 pods are taken down at a time but customers saw much larger drop in reliability.

From what I understand, when nodes are taken down AKS initialize the request to drain nodes, which sends "SIGTERM" to ingress pods, where envoy should start working on draining existing connections. "Termination grace period" is set to 30s so if envoy (ingress pod) doesn't exit by then, k8s will send "SIGKILL" signal to kill the pod. Would increasing the grace period help?

**Comment by howardjohn** [comment]
Envoy won't wait the full 30s to exit by default
It will drain for 5s (termination drain duration in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) then exit.

So if your clients and/or AKS cannot handle this short period then it's possible you could hit issues.

If you aren't on a newer Istio (like 1.9 or maybe even 1.10) the draining had serious flaws so I would upgrade. If you are, it would likely be best to understand where things are breaking down. Is AKS still sending traffic to dead pods, are the clients sending really long lived requests, are they not backing off to Envoy's draining (ie accepting the connection=close header to reconnect)

**Comment by jl3yr** [comment]
We are running 1.9 and we set the termination drain duration to 30s. I don't think the requests are going to dead pods since some of the requests are still succeeding and requests should time out after 3.5s. 
I'm not too sure on how to check if requests are still being sent to the ingress gateway after the drain signal.
