### ISSUE TITLE
Port 443 of ingress-gateway not exposed on GKE, only 80 and 15021

### ISSUE THREAD

**Issue by fiftoine** [istio/istio#34735]
**Bug description**

Ingress gateway service has 3 ports and is a LoadBalancer service. On the GCP Frontend, only the ports 80 and 15021 are exposed, not the 443 one.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Ports 80, 443 and 15021 are exposed on the GCP load balancer frontend.

**Steps to reproduce the bug**

Install Istio with helm charts, including ingress gateway containing the 3 default ports. Check in GCP console and see that on the load balancer frontend, only ports 80 and 15021 are exposed.

![image](https://user-images.githubusercontent.com/1417691/129682575-a970c231-0541-43d6-b74d-30cb451d6903.png)

It then prevents HTTPS to work correctly.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (10 proxies)
```

```
kubectl version --short
Client Version: v1.15.3
Server Version: v1.20.9-gke.700
```

```
helm version --short
v3.3.4+ga61ce56
```
**How was Istio installed?**

With Helm charts, including ingress gateway with default values.

**Environment where the bug was observed (cloud vendor, OS, etc)**

On GKE

**Comment by howardjohn** [comment]
Are you sure 80-15021 is not supposed to be a range and actually includes 443?

Regardless, if we are putting 443 in the Service and its not in GKE UI/config, it sounds more like a GKE bug; there is nothing Istio can do other than put the port in the Service.

**Comment by howardjohn** [comment]
I do believe its a range. That being said, this seems more like a GKE UI issue than something Istio can help with.
