### ISSUE TITLE
Missing labels in ConfigMaps and Lease

### ISSUE THREAD

**Issue by Ramilito** [istio/istio#34744]
There are three ConfigMaps and one Lease resource created by istio-operator that are missing recommended labels.

I would be satisfied with labels such as:
```
metadata
    labels
        operator.istio.io/version: 1.10.3
```

name:  istio-namespace-controller-election, kind: ConfigMap
![image](https://user-images.githubusercontent.com/8473233/129748570-0540a609-8952-42f2-a8dc-1523d48d36e5.png)

name: istio-validation-controller-election, kind: ConfigMap
![image](https://user-images.githubusercontent.com/8473233/129748721-6011232f-6ca8-486a-b453-0c9821618f08.png)

name: istio-operator-lock, kind: ConfigMap
![image](https://user-images.githubusercontent.com/8473233/129748978-e53c16e0-c6d2-481c-ba13-6ff3181d339f.png)

name: istio-operator-lock, kind: Lease
![image](https://user-images.githubusercontent.com/8473233/129749074-e6c7eafd-19e5-4b5c-b785-eaeb846d9df0.png)

**Comment by howardjohn** [comment]
Why do you need the labels? I have never seen any controller set these for leader election. For example...:
```
$ kubectl get cm -A --show-labels | rg 'lock|elect'
default           consul-controller-lock                                         0      46d     <none>
kube-system       cert-manager-cainjector-leader-election                        0      7d22h   <none>
kube-system       cert-manager-cainjector-leader-election-core                   0      7d22h   <none>
kube-system       gke-common-webhook-lock                                        0      89d     <none>
kube-system       ingress-gce-lock                                               0      89d     <none>
```

**Comment by Ramilito** [comment]
I use a script to associate all resources in the cluster to yaml files we have in our repository.
When there are no files, ie when the operator creates the resources, then the script has no way to know who the resource belongs to.

In the examples you use, we have the files for them in the cert-manager.yaml so if cert-manager decides to change the name of the leader-election, for example when upgrading, then my script would notify me that there is no one using the dangling resource by comparing the kustomize build with the kubectl diff -k output.

When it comes to operator resources that are missing labels, I usually find a .metadata.ownerReference that works as well.

**Comment by howardjohn** [comment]
A leader election configmap should not be stored in a git repo. It's
transient in-cluster state.

**Comment by Ramilito** [comment]
We are using infrastructure as code but that's beside the point I think, I'm not sure how kuberenetes would garbage collect those resources and that's why we want to associate every resource to its owner, and I cannot be sure that Istio Operator is still using that resource unless there is a version tag on it.

**Comment by howardjohn** [comment]
Kubernetes controllers almost always implement leader election. They almost always use this package to do so: https://github.com/kubernetes/client-go/blob/v0.22.0/tools/leaderelection/resourcelock/interface.go#L100. This does not set any labels nor ownerRefs. Kubernetes own usage of the same library is the same.

Given the overwhelming pattern in the ecosystem I get the impression this is not a recommended pattern. If we get feedback from the Kubernetes team that this is a good idea we can consider it but until then I think it's best we stick to prior art.

**Comment by Ramilito** [comment]
It seems that you are correct, I guess il just ignore those resources manually. Thank you for looking into this!
