### ISSUE TITLE
istioctl manifest generate inconsistent default behavior

### ISSUE THREAD

**Issue by xinlaini** [istio/istio#34758]
Hello, I'm trying to use istioctl (1.10.3) to generate default istio manifests, but I'm seeing a behavior that can't be explained.
basically, if I run
```istioctl manifest generate > /tmp/no-arg.yaml```
vs
```istioctl manifest generate -f ./manifests/profiles/default.yaml > /tmp/with-default.yaml```
I expect them to generate identical manifests. However, the two outputs seem to differ at exactly one location - the former's istiod deployment doesn't have `spec.replicas` specified, but the latter has `spec.replicas` explicitly set to 1.

From the helm chart in manifests/charts/istio-control/istio-discovery/templates/deployment.yaml, it seems like the condition
 ```
{{- if not .Values.pilot.autoscaleEnabled }}
{{- if .Values.pilot.replicaCount }}
  replicas: {{ .Values.pilot.replicaCount }}
{{- end }}
{{- end }}
```
didn't take effect when `-f default.yaml` (which sets values.pilot.autoscaleEnabled to true) is explicitly passed.

**Comment by howardjohn** [comment]
Interesting, I would also expect those to be the same... That being said, the end result show he functionally equivalent, right? replicas default is 1

**Comment by xinlaini** [comment]
For the k8s behavior, yes, whether unsetting replicas or explicitly setting it to 1 is equivalent.
But the confusing part is why the `istioctl manifest generate command` did not seem to respect the if conditions set in the charts.
It's behaving as if the profile's `values.pilot.replicaCount` is set to `spec.replicas` unconditionally.

**Comment by xinlaini** [comment]
To test my hypothesis further, I removed the two ifs from the chart, and change the replicas line to
```
replicas: "foo"
```

Then if default.yaml has `values.pilot.replicaCount: 42`, then the final manifest sets `replicas: 42`, if default.yaml has `values.pilot.replicaCount: 0`, then the final manifest keeps `replicas: foo`

Clearly there are some hard-coded behavior in istioctl binary, regardless of what the chart's logic seems to dictate.

**Comment by howardjohn** [comment]
I think it somehow overlays the IstioOperator settings on top of the
values.yaml files inside the chart itself. Not 100% sure

**Comment by xinlaini** [comment]
To add a little bit more confusion to the issue
Apparently, the results are different if you do 
```
istioctl manifest generate -f ./default.yaml -d ../
```
vs 
```
istioctl manifest generate --set profile=./default.yaml -d ../
```

The manifests generated in the first command has `replicas:1` for istiod deployment, the latter doesn't.

**Comment by monsteredc** [comment]
@howardjohn I just tested the code, and here is the logic that makes the inconsistent situation:
https://github.com/istio/istio/blob/fa911b97449b5f793deabd964f9bfa89e48b9ad1/operator/pkg/manifest/shared.go#L176
When setting the `-f` flag, the `overlayYAML` para will be the default file from `./manifests/profiles/default.yaml`. However, if not setting the `-f` flag or just setting `--set profile=default`, the `overlayYAML` para will be empty or only contains the profile field.
The `TranslateK8SfromValueToIOP` func will translate the yaml to a new yaml with some k8s settings, and then do the overlay process, which causes the inconsistent behavior.
I've tested some of the other profiles, and they are consistent.
The solution I came up with is to read the default file in `./manifests/profiles/default.yaml` if no flag is set or the profile is set to default but no `-f` path is provided, to make the `overlayYAML` parameter not nil. It would be great if you could provide with any better suggestions. Thanks!
