### ISSUE TITLE
pod(istio-proxy) forward traffic to other pod(istio-proxy)

### ISSUE THREAD

**Issue by cfanbo** [istio/istio#34769]
when multiple services，how to proxy serviceB from source serviceA(a pod as a services)

old arch:
```
client(pod) -> server(pod)
```

new arch:
```
client (pod)-> proxy(pod) -> server(pod)
```

now add proxy layer between client and server, when client request server, must first request proxy，then proxy layer forward traffic to server

**Comment by hzxuzhonghu** [comment]
By default istio depends on iptabels to intercep the traffic calling from client to server. Natively, you donot have to change any code logic to migrate to istio.
