### ISSUE TITLE
[1.7.8] Envoy out of memory

### ISSUE THREAD

**Issue by dominicqi** [istio/istio#34779]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ X] Performance and Scalability

**Steps to reproduce the bug**
We have a microservice using istio sidecar ，but  the sidecar memory growth，never release。 The Envoy will be oom killed about ten days later. 
Here is the sidecar container memory 
![image](https://user-images.githubusercontent.com/12235378/130028766-91c48238-0ac9-4b6e-83f8-a7f070004e84.png)

I flow the  https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#generate-profile guide , Here's the profiler result.
[profile001.pdf](https://github.com/istio/istio/files/7012692/profile001.pdf)

I add a sidecar CRD remove all listeners on the workload  ,but the memory not release, so i think this is not the pilot issue。
Other workloads in the same mesh  is ok.  
Is there anyone who can help me ，How can  I find the problem？

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.7.8
control plane version: 1.7.8
data plane version: 1.7.8 (698 proxies), 1.7.1 (9 proxies)

kubernetes version 
Client Version: v1.18.8-aliyun.1
Server Version: v1.18.8-aliyun.1

**How was Istio installed?**
istio operator

**Comment by howardjohn** [comment]
Sorry, we cannot help with performance issues on such old versions. Many performance issues have been fixed on recent version. https://istio.io/latest/news/support/announcing-1.7-eol-final/
