### ISSUE TITLE
Remove all *.tpl files in helm charts

### ISSUE THREAD

**Issue by sdake** [istio/istio#3479]
The *.tpl files add too much complexity to Istio.  While they are good for configurability, Istio is not designed with the model that services can be renamed in a running system.  Many core parts of how pilot and mixer communicate as well as other components rely on specific names for nearly all objects.

**Comment by ldemailly** [comment]
let's hardcode all the names ? probably not, right ? should we identify where it breaks ? otherwise 
it seems like abdicating good practice ?

> Istio is not designed with the model that services can be renamed in a running system. Many core parts of how pilot and mixer communicate as well as other components rely on specific names for nearly all objects.

any example ? and any major reason why that should stay true

**Comment by sdake** [comment]
@costinm had requested I proceed with this work in https://github.com/istio/istio/pull/3473.  Agree Helm best practice is to permit significant configuration on naming of objects.  Personally I think the *.tpl is too complicated, although I also think hardcoding is probably not the right answer.

I could be wrong about the details of pilot->mixer->prometheus->mixer depending on specific naming.  This may be configurable via the current configmaps that are fed into these services.  I don't see any strong reason why it should stay true, but also don't see a lot of motive to permit renaming pilot to "pilot-foo".

Cheers
-steve

**Comment by sdake** [comment]
cc  @linsun @luisyonaldo @munnerz

**Comment by sdake** [comment]
@ldemailly I'll get started on the changes today - if the debate in this thread renders that PR unnecessary we can close it.  I think visualizing the structure may be helpful for all involved as it seems like a tradeoff between maintainability/simplicity/community scaling vs configurability and Helm community best practicies.

**Comment by sdake** [comment]
Hey folks.  I've had a short personal delay for most of the day and will begin this work shortly.

Cheers
-steve

**Comment by ldemailly** [comment]
I think we need 1 good working system that demonstrates it can produce the same `istio-auth.yaml` as we have today to replace what we have. We can't remove the option to change namespaces etc as that's pretty basic and key to some multi namespace shared tests.
If that 1 system can _also_ be base for helm installation, even better.

**Comment by sdake** [comment]
@ldemailly My original intent was  to get the charts into a state where they produce (via `helm template istio --name istio`) an equivalent to istio-auth.yaml (although with alternate object ordering) based upon the various requirements picked up during prior reviews of the Helm chart.  This issue is part of that work.

Unfortunately Helm doesn't have a whole lot of ordering guarantees, so the ordering of the object creation will likely have to change in a helmchart-generated istio-auth.yaml.  This problem with Helm will also effect how helm template works with https://github.com/istio/istio/pull/3193.  I tried that PR, and the Helm chart does not create CRDs in the correct order during `helm install . --name istio` resulting in the problem described in #https://github.com/istio/istio/pull/3193#issuecomment-364196391 that started all this refactoring :).  Not sure about helm template.

As I understand it, the full list of requirements in no particular order form various PRs:

from https://github.com/istio/istio/pull/3193#issuecomment-363832416:
* reduce API surface config
* improve layout of helm (@costinm had stated the layout was bad, however, later indicated he appreciated the structure) this requirement could use clarification
* define a clear maintenance approach for Helm
* istioctl integration

In https://github.com/istio/istio/pull/3193#issuecomment-363834913:
* commitment from community members to change helm to match community requirements
* better separation between critical options and knobs

In https://github.com/istio/istio/pull/3193#issuecomment-364277822:
* Reduce complexity by removing configurability of names of objects (this issue is meant to tackle this requirement) - some things need to be configurable, such as namespaces as you have pointed out
* more discussion around redesigning values.yaml (the API surface config) vs the current super-configurable approach

in https://github.com/istio/istio/pull/3349#issuecomment-364390275
* one source of truth for config

In https://github.com/istio/istio/pull/3349#issuecomment-364630302:
* A diff analysis of the current tmpl generated yamls vs those generated with `helm template`

@linsun is also working on a Helm-specific check

There are probably some requirements I've missed.

I am happy to help drive the delivery of these (somewhat subjective) requirements.  If there are more requirements, or the requirements should be altered, would help to organize the work if they were known now :)

Cheers
-steve

**Comment by sdake** [comment]
Resolved by:
https://github.com/istio/istio/pull/3594
