### ISSUE TITLE
Sidecar injection is slow

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34799]
On largish clusters, sidecar injection accounts for >10% of total memory allocations. This isn't _that_ bad, but still adds some GC pressure.

In worst case, however, on pods with 1500 environment variables set, we saw this maxing 4 CPUs and 15s to inject a single pod. This is due to the json patch generation.

I tried to replace it with a different library (https://github.com/howardjohn/istio/pull/new/inject/better-json-merge), but unfortunately it only makes merge patches - k8s will not accept those.

**Comment by kebe7jun** [comment]
In general, we don't patch the user's own containers, based on this, can we remove the non-istio injected containers before generating the patch? This should reduce a lot of comparisons and calculations.

**Comment by howardjohn** [comment]
Nice! I was thinking remove the managedFields , that idea is great as well - possibly both. Thanks for looking into it
