### ISSUE TITLE
Investigate model.Service.Address

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34807]
This field is a bit suspicious - all references should probably be through ClusterVIPs. I suspect anything using it is actually a bug...

The one legit usage seems to be https://github.com/istio/istio/blob/21af48e524ed581e77a75385788b2c608e6f9caf/pilot/pkg/serviceregistry/aggregate/controller.go#L184, but I think we could replace it with `dst.ClusterVIPs[srcRegistry.Cluster()] = src.ClusterVIPs[srcRegistry.Cluster()]`

**Comment by hzxuzhonghu** [comment]
src is the original svc converted from a single k8s registry, the `ClusterVIPs` is empty

**Comment by hzxuzhonghu** [comment]
func ServiceToServiceEntry(svc *model.Service) *config.Config {

use svc.Address directly , maybe not right

**Comment by hzxuzhonghu** [comment]
`buildOutboundListeners`

**Comment by hzxuzhonghu** [comment]
From my investigation, the most common case does not use svc.Address directly
