### ISSUE TITLE
Istioctl does not wait on CNI DaemonSet update

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#34811]
Unlike deployment ready check https://github.com/istio/istio/blob/c91f589684c0aa9de1c00e327eb5a1038ed52f7a/operator/pkg/helmreconciler/wait.go#L120

which checks the readiness of new replica set. DaemonSet readiness check only compares number of desired pods == ready ones, which is true if wait happens immediately after CNI manifest is applied. We need to find a way to wait for updated DaemonSet pods to be ready.

**Comment by litong01** [comment]
@bianpengyuan what kind of the checks would you like to see? or flows you think will be appropriate. If you provide a bit more information on the checks that will make sense, I can add these checks for DaemonSet.

**Comment by bianpengyuan** [comment]
@litong01 thank you!

I think we probably need to check the `observedGeneration` in the status is the same as the generation of current spec, so that we can be sure number of ready pod in status is the latest.

**Comment by litong01** [comment]
@bianpengyuan Ok, let me go with that direction.
