### ISSUE TITLE
istioctl analyze IST0132 assuming only one Gateway? or doesn't handle wildcards?

### ISSUE THREAD

**Issue by dsbos** [istio/istio#34829]
**Bug description**

It seems that `istioctl analyze`'s logic doesn't "understand" that a VirtualService can use more than one Gateway.

When I run  `istioctl analyze --all-namespaces` on my cluster/mesh, I get warnings like this:

`Warning [IST0132] (VirtualService redacted-service.redacted-namespace) one or more host [redacted-service.redacted-tld] defined in VirtualService redacted-namespace/redacted-service not found in Gateway redacted-namespace/public-ingress.`

My VirtualService uses two Gateways, the `redacted-namespace/public-ingress` Gateway mentioned in that warning message and also Gateway `redacted-namespace/private-ingress`.  The latter covers/enables host name `redacted-service.redacted-tld` by listing host name pattern "*.redacted-tld".

So why is `istioctl analyze` complaining that host name `redacted-service.redacted-tld` isn't found in Gateway `redacted-namespace/public-ingress`?

Does it not "know" that a VirtualService can use more than one only one Gateway?

Or maybe does it not handle host-name wildcards properly?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I would expect that `istioctl analyze` would not complain that that host name is not defined in that Gateway given that another Gateway does cover that host name.

**Steps to reproduce the bug**

Set up working VirtualService and Gateways consistent with description above. 
(I haven't tried with a _non_-wildcarded host-name entry in the other Gateway. Trying that my be interesting.)

**Version** (include the output of `istioctl version --remoteshort` and `helm version --short` if you used Helm)

```
client version: 1.10.3
control plane version: 1.9.7
data plane version: 1.9.7 (89 proxies), 1.8.3 (1 proxies)
```

**How was Istio installed?**

Via `istioctl manifest generate` and then applying generated K8s manifests via Argo CD.

**Environment where the bug was observed (cloud vendor, OS, etc)**

In EKS cluster.

**Comment by monsteredc** [comment]
Seems like a duplicated question with https://github.com/istio/istio/issues/34653.
