### ISSUE TITLE
Cleanup `ISTIO_META_ROUTER_MODE` 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#34848]
**Describe the feature request**

Currently router mode is not used anymore, istio automatically detect gateway route mode now. So we can remove all the 
`ISTIO_META_ROUTER_MODE`

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I think its already done, where are you seeing it?

**Comment by hzxuzhonghu** [comment]
I am seeing a lot of env there

**Comment by hzxuzhonghu** [comment]
Maybe for test, i am not looking closely

**Comment by hzxuzhonghu** [comment]
not stale
