### ISSUE TITLE
istio 1.11.0 multicluster - DNS is not resolving properly / load balancing doesn't work

### ISSUE THREAD

**Issue by guyromb** [istio/istio#34850]
**Bug description**

Hello,
I installed Istio multi cluster using this doc: https://istio.io/latest/docs/setup/install/multicluster/multi-primary/ (same network, multi primary).
I can successfully ping curl IPs from one cluster to a pod in another cluster. 
I am able to see the pods/DNS endpoints urls from both clusters (`istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-dd98b5f48-djwdw.sample | grep helloworld`)

However, load balancing from the verify step in this doc https://istio.io/latest/docs/setup/install/multicluster/verify/ doesn't work: it only shows v1. Also, running curl using the DNS doesn’t work and running nslookup shows just the resolve.conf.

I have these enabled:
      ISTIO_META_MESH_ID:            istio-mesh
      TRUST_DOMAIN:                  cluster.local
      ISTIO_META_DNS_AUTO_ALLOCATE:  true
      ISTIO_META_DNS_CAPTURE:        true
      ISTIO_META_CLUSTER_ID:         cluster1
      ISTIO_META_NETWORK:            istio-mesh-network

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I would expect curl to return randomly v1 and v2 with load balancing as described in the multicluster install verification step.

**Steps to reproduce the bug**

Run two EKS clusters, with VPC peering.
Install two istio as mentioned in this tutorial:  https://istio.io/latest/docs/setup/install/multicluster/multi-primary/

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm) 

1.11.0

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
How is this related to dns?

Does `istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-dd98b5f48-djwdw.sample | grep helloworld` show correct pod ip ?

**Comment by guyromb** [comment]
10.72 is the current cluster, 10.70 is the other cluster - so this is correct
```
istioctl proxy-config endpoint sleep-64cc88858f-5bzg8.sample | grep helloworld
10.70.14.126:5000                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.70.8.201:5000                 HEALTHY     OK                outbound|5000||helloworld.default.svc.cluster.local
10.72.3.17:5000                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.72.7.50:5000                  HEALTHY     OK                outbound|5000||helloworld.default.svc.cluster.local
```

But the following always returns the local cluster pod (hello v1) instead of randomly v1 v2 (v2 is in the other cluster):
```
kubectl exec -it -n sample sleep-64cc88858f-5bzg8 -- sh
/ $ curl -sS helloworld.sample:5000/hello
Hello version: v1, instance: helloworld-v1-945bf7f7d-cx5jq
```
I think it is DNS because only one IP is returned. Otherwise how can it randomly do the loadbalancing @hzxuzhonghu ?
```
/ $ nslookup google.com
Server:		172.20.0.10
Address:	172.20.0.10:53

/ $ nslookup helloworld.sample
Server:		172.20.0.10
Address:	172.20.0.10:53

/ $ dig helloworld.sample a
helloworld.sample.	30	IN	A	172.20.163.124
```

**Comment by guyromb** [comment]
I also tried to add:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"

but same results.

**Comment by stevenctl** [comment]
> These endpoints are not in same namespace, one in default, one in sample, so they are not of a same service.

All 4 are not the same, but there is 1 IP per-cluster/per-namespace, so we should still see the load-balancing happen correctly. 

>  It is mentioned in the link above need to create root CA manually. However, it is not mentioned in the multi-primary setup article

The docs say "Before proceeding, be sure to complete the steps under [before you begin.](https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/)" which link to the [configure trust](https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/#configure-trust) section where you're instructed to setup the certs.

This is a bit of a confusing layout though.. 

Can you try something like this:

```bash
kubectl --context "${CTX_CLUSTER1}" -n sample exec "$(kubectl get pod --context="${CTX_CLUSTER1}" -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" -- curl localhost:15000/clusters | grep helloworld | grep cx_
```

Do you see any `cx_connect_fail` > 0?

**Comment by Brcara** [comment]
I have an essentially identical problem. All cx_connect_fail = 0

**Comment by stevenctl** [comment]
@Brcara One reason curl against the Pod IP could yield different results unless, since this is multi-network, there can be overlap with local IPs. 
 
 Keep in mind this symptom is the most common symptom of a multicluster issue, so there is a good chance there is a different root cause. Especially considering you have a multi-network set up as well. Do you mind opening a separate issue with reproduction steps. (Does curl against the service name work? Are the Pods injected? Multi-network _requires_ a sidecar and _requires_ mTLS not to be disabled.)

**Comment by 13567436138** [comment]
···
root@node01 multicluster]# istioctl proxy-config endpoint productpage-v1-97845bbff-sbnpt.istio | grep productpage
172.20.0.101:9080                HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local
172.21.2.6:9080                  HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local
[root@node01 multicluster]#   kubectl exec  -n istio   "$(kubectl get pod  -n istio -l app=ratings -o jsonpath='{.items[0].metadata.name}')"  -- curl productpage.istio:9080/productpage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
···
I face the same problem，can not connected

**Comment by 13567436138** [comment]
is my cluster in the same network I wonder？

**Comment by 13567436138** [comment]
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
```

is this enough

```
[root@node01 virtualservice]# kubectl get svc -n istio-system 
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
flagger-loadtester     ClusterIP      10.68.154.0     <none>        80/TCP                                       27h
grafana                ClusterIP      10.68.229.122   <none>        3000/TCP                                     41h
istio-ingressgateway   LoadBalancer   10.68.111.4     <pending>     15021:30732/TCP,80:30363/TCP,443:30559/TCP   36m
istiod                 ClusterIP      10.68.142.123   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        36m
prometheus             ClusterIP      10.68.146.205   <none>        9090/TCP                                     41h
```

no egressgateway

**Comment by guyromb** [comment]
hey @stevenctl , I get the following: 

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164k    0  164k    0     0  30.9M      0 --:--:-- --:--:-- --:--:-- 32.1M
outbound|5044||hello.default.svc.cluster.local::10.70.2.108:5044::cx_active::3
outbound|5044||hello.default.svc.cluster.local::10.70.2.108:5044::cx_connect_fail::1088
outbound|5044||hello.default.svc.cluster.local::10.70.2.108:5044::cx_total::1091
```

**Comment by stevenctl** [comment]
@1356743613 it doesn't seem like you have the "eastwest" gateway installed which we use for multi-network. See https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/#install-the-east-west-gateway-in-cluster1

**Comment by stevenctl** [comment]
@guyromb so did you perform the steps to set-up a "common root of trust" (e.g. https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)? If you enable Envoy [access logs](https://istio.io/latest/docs/tasks/observability/logs/access-log/) it can help identify if this is an SSL error or otherwise. Should check on both the client/server.

I re-read your earlier comment https://github.com/istio/istio/issues/34850#issuecomment-906203153 and no, the remote-secret command doesn't set up anything for trust. Just control plane -> remote API server access.

**Comment by guyromb** [comment]
Yes, I did it @stevenctl and I could get things to work. But after sometimes I am having issues to connect even to IP directly as long as the target pod has istio sidecar.

**Comment by guyromb** [comment]
After restarting the pods / side car on the target it seems I am able to connect. However, this keeps happening randomly every few days. how can I fix it permanently?

**Comment by stevenctl** [comment]
AFAICT the logs are from successful conns/reqs? Do you have logs from the time while you saw failures; from istiod or from the proxies?

**Comment by guyromb** [comment]
When I see failure I don't see anything on istiod or the target pod. Only 503 from the envoy where I run curl from

**Comment by vijay-dcrust** [comment]
@guyromb I am also facing this issue in multicluster connectivity where the service communication stops with the above error as mentioned.
However services within the same cluster continue to have access to each other.
