### ISSUE TITLE
Missing Helm Chart 1.8.0

### ISSUE THREAD

**Issue by mvaal** [istio/istio#34851]
**Bug description**
PR was merged to allow namespaces to use the Release namespace, but the chart was never bumped so it is inaccessible (even though the changes ended up as part of the 1.11.0 release).
https://github.com/istio/istio/pull/30741

https://github.com/istio/istio/blob/master/manifests/charts/istio-operator/Chart.yaml#L3

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I should be able to access the new helm chart.

**Comment by howardjohn** [comment]
The chart version in github source is not important. We only support installing from https://github.com/istio/istio/releases. https://github.com/istio/istio/issues/31275 tracks improving this
