### ISSUE TITLE
TestExternalDetailsService failure

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3485]
I0214 02:11:54.269] --- FAIL: TestExternalDetailsService (68.65s)
I0214 02:11:54.270] 	demo_test.go:143: could not find 0486424618 in response
I0214 02:11:54.270] FAIL

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3475/e2e-smoke/2952/

**Comment by vadimeisenbergibm** [comment]
@ldemailly @andraxylia @rshriram @mandarjog we should decide how to treat failures to external sites, like `google.com`, `googleapias.com`, `httpbin.org`, `wikipedia.org`. The connections to these sites fail from time to time. Should we retry the test several times before failing?

**Comment by vadimeisenbergibm** [comment]
Closing the issue, the tests to external services will fail from time to time.
