### ISSUE TITLE
Dramatic increases in Envoy memory usage under load?

### ISSUE THREAD

**Issue by diranged** [istio/istio#34895]
**Bug description**
We are trying to troubleshoot a periodic OOM issue on our Istio IngressGateway Pods. The issue happens very rapidly - a gateway will be humming along just fine, and suddenly it will OOM and be restarted. Here is the situation:

We are beginning to run production traffic through our Istio (1.11.1) service mesh. The traffic flow comes from an application inside our VPC, but outside of our Kubernetes cluster. The traffic flows though an AWS NLB, then into the Ingress Gateways, then through the mesh to a series of application pods. We're running ~3000-6000QPS throughout the day, with an average response time of 3ms.

To troubleshoot the issue, we have increased the `resources.limits.memory` setting (from 1gb -> 4gb) to prevent the pods from OOMing, and catch their metrics during the spikes. This has allowed us to observe an interesting pattern where we will get a traffic spike (or where one pod will be unevenly loaded) and memory will disproportionally increase in comparison to actual traffic.

_Traffic Flow Diagram_
```
[ClientAppOnECS] ---HTTP/2+TLS--->
  AWS NLB --->
    [IngressGateway Pods x 6] ---mTLS--->
        [AppPods x ~4-10 depending on time of day]
```

_Pod Specs_
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
...
spec:
...
  minReadySeconds: 150
  replicas: 6
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
...
```

### Scenario 1: A sudden burst of traffic

In this scenario, some event occurs (unclear what triggered it) and the traffic dipped for a moment, then spiked up. Traffic on each of the 3 ingressgateways spiked almost by *100%* for a brief moment. What is interesting is the graph on the right shows memory usage, and it increases by *300%*, and then stays high for a while. 

This spike popped up the containers way above their 1GB `resources.requests.memory` setting, but they did not OOM because we are allowing them to spike like that.. (however, if the host was loaded down with other containers, then they would have been eligible for OOMing anyways)

![image](https://user-images.githubusercontent.com/768067/131022110-6c7f46b5-4cec-4c47-b286-1162baf15b7f.png)

### Scenario 2: Rolling traffic to a new set of IngressGateways

Right now we only have one client-app going though this NLB, and the ClientApp has a tendency to open one main connection and hammer it with these low-latency requests. For that reason, when we roll our IngressGateways, we tend to see traffic end up unevenly loaded for a while (_we are addressing this issue separately in our client app_). We noticed that during these rolls, when the IngressGateways become unevenly distributed, we see the same huge memory spike:

This graph shows the rollout of new IngressGateway pods over a period of a few minutes. We do these rolls slowly (see `minReadySeconds`) because they are behind an NLB and NLBs do not re-route traffic quickly, and we have to terminate network connections to our  clients during the process. _In practice we do not expect to do this frequently, but we obviously want this to be a supported and reasonable operation we can take without significant impact to our clients._

You can see how again the memory usage spikes massively up by *200+%* even though traffic only spikes by ~70%.

![image](https://user-images.githubusercontent.com/768067/131022708-41da049a-d73e-4348-855f-2237b452b7b5.png)

## The big question

How are we supposed to think about or plan out memory usage in our Istio IngressGateways? It seems like CPU load scales gracefully with request-load, but Memory seems to scale non-linearly and in very surprising jumps. Our steady-run rate to support ~1000QPS/container seems to be between 200 and 400MB. However, they occasionally spike to 1.5-2GB.

**Expected behavior**

I would hope to see memory usage be at least directly correlated to request-rate ... if not even lower. In various blogs and posts we've read, we understood that the Envoy memory should be fairly low.. but we feel like it's actually surprisingly high in this case.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Kubernetes 1.21
Istio 1.11.0 and 1.11.1

**How was Istio installed?**

Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS on EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by diranged** [comment]
Oh - I forgot the point of this.. when the connection counts died down after switching to HTTP/2, we saw all of our various Istio Proxy memory counts drop _dramatically_. We're now seeing the sidecars hover around ~100-130MB. You can see the various spikes before and after the change (Y-axis is megabytes)

*Graph of the istio-proxy container memory usage in our application `ourservice` pods*
![image](https://user-images.githubusercontent.com/768067/131862266-b32616de-55b4-4a1c-9488-723cc025217c.png)

Looking at our `istio-ingressgateway` pods, we can see a similar change:
![image](https://user-images.githubusercontent.com/768067/131862479-5ed2c088-6e06-47f6-824d-340cdc3cfa55.png)

**Comment by howardjohn** [comment]
cc @lambdai

**Comment by howardjohn** [comment]
The big connection spike is pretty interesting. I am not an expert at the Envoy connection pool implementation but for http1 you cannot send multiple requests in parallel on a single connection. So given a perfect 10ms latency 1000qps you would need minimum 10 connections. Reality isn't perfect though; when there is no available connections envoy would open up a new one. So a moderate spike in backend latency or similar could cause many new connections to open up... I am surprised at how big the spike is and that it doesn't go back down though

**Comment by diranged** [comment]
Yeah thanks for the response.. for what its worth, our P95 is ~3ms, but our P99 is ~20ms I think. We're doing upwards of ~6000 QPS right now, so it definitely could add-up quickly in the event of any kind of a backup.

**Comment by diranged** [comment]
So we'd been running pretty stable for a week now, and this morning we saw a big spike of load and memory on our ingressgateways handling inbound requests from an ALB. These are doing HTTP/2 between the ALB and the IngressGateways by the way.

![image](https://user-images.githubusercontent.com/768067/132994388-6c77300e-8a21-4a78-96b4-992d02c1a2fc.png)
![image](https://user-images.githubusercontent.com/768067/132994401-406b61a9-1315-45f5-a01a-3c8b609cfade.png)

The metrics show the pods start spiking memory at 7:30:20s... and the CPU spikes a few seconds later. At the same time, we suddenly start seeing the readiness probes on all the ingress gateways failing:

```


2021-09-12 07:30:27 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-5sz7s : Readiness probe failed: Get "http://100.64.143.149:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
-- | --
  |   | 2021-09-12 07:30:27 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-ww2qh : Readiness probe failed: Get "http://100.64.114.160:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:28 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-zmtf2 : Readiness probe failed: Get "http://100.64.99.209:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:28 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-k7bj7 : Readiness probe failed: Get "http://100.64.39.240:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:29 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-5sz7s : Readiness probe failed: Get "http://100.64.143.149:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:29 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-ww2qh : Readiness probe failed: Get "http://100.64.114.160:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:30 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-zmtf2 : Readiness probe failed: Get "http://100.64.99.209:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:30 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-k7bj7 : Readiness probe failed: Get "http://100.64.39.240:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:31 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-5sz7s : Readiness probe failed: Get "http://100.64.143.149:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:31 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-ww2qh : Readiness probe failed: Get "http://100.64.114.160:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:32 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-zmtf2 : Readiness probe failed: Get "http://100.64.99.209:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  |   | 2021-09-12 07:30:32 | Pod / istio-internal-ingressgateway-6bf7bd7b8f-k7bj7 : Readiness probe failed: Get "http://100.64.39.240:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

The HPA eventually scales up more Pods, and eventually things settle down:
```
2021-09-12 07:30:59 | HorizontalPodAutoscaler / istio-internal-ingressgateway : New size: 5; reason: cpu resource utilization (percentage of request) above target
-- | --
  |   | 2021-09-12 07:30:59 | Deployment / istio-internal-ingressgateway : Scaled up replica set istio-internal-ingressgateway-6bf7bd7b8f to 5
  |   | 2021-09-12 07:30:59 | ReplicaSet / istio-internal-ingressgateway-6bf7bd7b8f : Created pod: istio-internal-ingressgateway-6bf7bd7b8f-ft9sp
```

We are still at a loss here.. we thought we had really solved things with the HTTP/2 fix (turning on HTTP/2 between the ALB and the IngressGateway pods), but this came out of no where and bit us for about a minute. Any thoughts on what to troubleshoot next?
