### ISSUE TITLE
istio-proxy recursion in zipkin

### ISSUE THREAD

**Issue by jmiddleton** [istio/istio#349]
I have a service that when I send a request in zipkin is shown with 198 spans. Not sure if it is a bug or what but just in case someone else has seen the same behaviour.

`Services
565.695ms1.131s1.697s2.263s2.828s
- istio-proxy 
...... 2.828s : 192.168.99.100:31950
- [istio-proxy ]
...... 2.747s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.746s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.745s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.735s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.733s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.731s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.730s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.729s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.728s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.727s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.726s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.725s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.724s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.722s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.721s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.720s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.718s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.717s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.715s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.704s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.703s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.701s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.700s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.698s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.697s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.695s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.694s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.693s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.692s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.690s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.688s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.687s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.686s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.685s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.684s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.682s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.681s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.680s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.678s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.677s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.676s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.674s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.673s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.669s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.667s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.666s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.662s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.660s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.657s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.656s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.654s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.643s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.641s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.637s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.636s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.633s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.630s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.629s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.591s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.586s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.585s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.582s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.528s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.524s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.520s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.341s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.339s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.335s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.334s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.331s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.330s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.328s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.326s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.325s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.319s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.315s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.314s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.313s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.311s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.307s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.306s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.302s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.301s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.299s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.272s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.269s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.268s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.142s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.140s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.137s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.136s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.134s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.131s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.128s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.126s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.124s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.122s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.120s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.119s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.116s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.114s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.112s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.109s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.108s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.105s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.104s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.103s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.100s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.090s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.011s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.004s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.001s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 2.000s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.988s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.986s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.975s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.973s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.950s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.680s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.676s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.672s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.670s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.668s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.666s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.664s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.661s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.659s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.657s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.655s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.653s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.651s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.650s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.647s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.645s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.643s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.640s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.639s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.637s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.635s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.632s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.631s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.604s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.602s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.577s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.552s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.523s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.521s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.499s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.467s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.437s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.433s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.406s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.404s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.377s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.350s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.323s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.293s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.291s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.261s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.201s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.177s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.174s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.144s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.114s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.077s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.024s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 1.019s : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 969.212ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 966.626ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 935.694ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 908.792ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 881.737ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 877.301ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 847.300ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 844.223ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 781.043ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 778.835ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 747.813ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 723.784ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 697.630ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 670.572ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 644.069ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 634.541ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 561.521ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 553.533ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 531.930ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 505.225ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 475.492ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 471.990ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 437.904ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 408.482ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 373.511ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 342.168ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 316.300ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 281.121ms : validation-service.default.svc.cluster.local:5080
- istio-proxy 
...... 251.923ms : validation-service.default.svc.cluster.local:5080
istio-proxy 
...... 223.266ms : validation-service.default.svc.cluster.local:5080`

**Comment by rshriram** [comment]
Wow. This is odd. Can you show us your yaml config if possible? And anything else that would help us reproduce it at our end ?
cc @fabolive @ijsnellf

**Comment by kyessenov** [comment]
could be related to https://github.com/istio/pilot/issues/829?

**Comment by jmiddleton** [comment]
This is my config but I lost my minikube VM so I cannot reproduce it.

apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    app: member-service
spec:
#  type: NodePort
  ports:
  - port: 4080
    name: http
  selector:
    app: member-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: member-service-v1
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: member-service
        version: v1
    spec:
      containers:
      - name: member-service
        image: xxx.dkr.ecr.xxx.amazonaws.com/xx/lsl-member-service:0.0.52-SNAPSHOT
        ports:
        - containerPort: 4080
        env:
        - name: SERVER_PORT
          value: "4080"
---
apiVersion: v1
kind: Service
metadata:
  name: validation-service
  labels:
    app: validation-service
spec:
#  type: NodePort
  ports:
  - port: 5080
    name: http
  selector:
    app: validation-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validation-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: validation-service
        version: v1
    spec:
      containers:
      - name: validation-service
        image: xxx.dkr.ecr.xxx.amazonaws.com/xxx/lsl-member-validation-service:0.0.34-SNAPSHOT
        ports:
        - containerPort: 5080
        env:
        - name: SERVER_PORT
          value: "5080"
        - name: MEMBER_SERVICE_RETRIEVE_PORT
          value: "4080"
        - name: MEMBER_SERVICE_RETRIEVE_URL
          value: member-service.default.svc.cluster.local
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: member-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/members/.*
        backend:
          serviceName: member-service
          servicePort: 4080
      - path: /api/validation/.*
        backend:
          serviceName: validation-service
          servicePort: 5080
---

**Comment by ldemailly** [comment]
Thanks a lot for the report - if you can reproduce it consistently that'd be even more useful but in the meantime I'll close that one in favor of the https://github.com/istio/pilot/issues/978
