### ISSUE TITLE
Pod Security Policy for Istio CNI should be created during installation

### ISSUE THREAD

**Issue by Sh1ftry** [istio/istio#34905]
When installing istio there should be a possibility to enable creation of PSP for Istio CNI, since now it's impossible to install it on clusters with restricted PSPs without some manual steps beforehand. It should also be mentioned in the docs, that such PSP is required.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Sh1ftry** [comment]
So I think it should at least be mentioned in the docs what is the minimal PSP for Istio CNI.

**Comment by bianpengyuan** [comment]
> So I think it should at least be mentioned in the docs what is the minimal PSP for Istio CNI.

Yeah that sounds great. @Sh1ftry would you be able to contribute this doc updates?
