### ISSUE TITLE
gateway-api gateway only effective in istio-system namespace,if mode is same httproute must in istio-system namespace,but serviceName can not use fqdn for example productpage.istio.svc.cluster.local.this means mode same is useless

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34916]
**Describe the feature request**
gateway-api gateway only effective in istio-system namespace,if mode is same httproute must in istio-system namespace,but serviceName can not use fqdn for example productpage.istio.svc.cluster.local.this means mode same is useless

make gateway not only effective in istio-system
or serviceName can use fqdn
*Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
See https://gateway-api.sigs.k8s.io/v1alpha1/guides/multiple-ns/. You can have the HTTPRoute in one namespace and Gateway in istio-system

**Comment by 13567436138** [comment]
I mean namespaces: from: "same" this is useless

**Comment by howardjohn** [comment]
`from: Same` - everything must be in one namespace. `from: All`/`from: Selector` - can be in many namespaces.

**Comment by 13567436138** [comment]
from: Same  everything must be in one namespace.
but actually my workload is in istio namespace,gateway is in istio-system namespace

**Comment by howardjohn** [comment]
Ok, then don't use from=same. It's not intended for that use case.

**Comment by hzxuzhonghu** [comment]
@13567436138 I think you are misunderstanding that the namespace is only for selecting `Route`, it does not say the route backend service should be in same namesapace as it.

**Comment by howardjohn** [comment]
In the v1alpha1 api the backend and route do need to be in the same namespacs actually. In v1alpha2 cross namespace route-backend is allowed.

**Comment by hzxuzhonghu** [comment]
IC, not looking much before, we are planning to follow up closely with it in the future.
