### ISSUE TITLE
delta: EDS and SDS wrongfully remove resources

### ISSUE THREAD

**Issue by adiprerepa** [istio/istio#34949]
With EDS and SDS, we will have PushRequest.Full = false, which is technically an "incremental" update, so we send a few resources.  However, delta takes this to be the SOTW with EDS and SDS, and removes the rest of the resources.

**Comment by howardjohn** [comment]
Ah... the reason it doesn't break the world is envoy just ignores the removal.

For RDS it will give an error log, for SDS/EDS it is silent
