### ISSUE TITLE
Enable metallb on ipv6

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34945]
https://github.com/istio/istio/pull/34943 attempt to do this, but its not right since it assigns the same address to multiple clusters.

Basically we just need to modify https://github.com/istio/istio/blob/4103c2fb1943c352d53524d71f96f24f48c45fe9/common/scripts/kind_provisioner.sh#L328 to add ipv6 addresses if they exist. `jq '[.[0].IPAM.Config[].Subnet]' -c` can give all of the subnets (ipv4 and ipv6)

**Comment by irisdingbj** [comment]
@Chen-Xintong

**Comment by irisdingbj** [comment]
@Chen-Xintong is interested in this issue and is working on this, Thanks！ @Chen-Xintong
