### ISSUE TITLE
add picture describing the perf setup

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3495]
basically what I drew on the board

cc @danehans

**Comment by danehans** [comment]
@ldemailly Let me know if this diagram looks good to you. If so, I'll update `tools/README.md` with a link to the diagram.

![fortio_perf_script_diagram](https://user-images.githubusercontent.com/1878195/36280330-c37e420e-124e-11e8-9ca0-3ad42443f0a0.png)

**Comment by ldemailly** [comment]
great !!! thanks !

**Comment by ldemailly** [comment]
i just noticed (a bit late) there are 2 ingress in the picture (for the test3 path) which I think is confusing. yet this is much better than before, thanks

**Comment by danehans** [comment]
I depicted 2 ingresses in the fortio ns b/c I based the diagram on the https://github.com/istio/istio/pull/3527 proposed changes

**Comment by ldemailly** [comment]
> I depicted 2 ingresses in the fortio ns b/c I based the diagram on the #3527 proposed changes

the top part of the picture, which is what I was referring to, which is about istio injected services has 2 ingresses - there is only 1 ingress for istio and it physically lives in the istio-ingress pod in the istio-system namespace

**Comment by ldemailly** [comment]
I guess maybe you mean ingress spec? but the arrow doesn't go to a spec, the traffic goes directly from ingress to fortio1/fortio2

**Comment by danehans** [comment]
@ldemailly I think the confusion lies in `istio-ingress` in the `istio-system` namespace. `istio-ingress` is the Istio Ingress Controller, whereas `ingress: istio-ingress` is the ingress resource created by the `setup_perf_cluster.sh` script in the `istio` ns.

> I guess maybe you mean ingress spec? but the arrow doesn't go to a spec, the traffic goes directly from ingress to fortio1/fortio2

You are correct, the arrow from the istio ingress controller should point to the service and not the spec. I am going to leave the `ingress: istio-ingress` so users understand how the ingress spec definitions correlate to the overall setup. I also need to update to show gce ingress controller.

**Comment by ldemailly** [comment]
thx ! maybe put "cfg" or "config" for the ingress spec part so it's more obvious the box isn't a process

**Comment by danehans** [comment]
Maybe it's best I remove the ingress resource defs from the diagram to simplify things.

**Comment by danehans** [comment]
He is the updated diagram w/o ingress spec. If this looks good, i'll open a pr to update the .svg
![fortio_perf_script_diagram_no_ingress](https://user-images.githubusercontent.com/1878195/36445912-8162946c-1634-11e8-8a44-d0967ab1bf4c.png)

**Comment by ldemailly** [comment]
sgtm may I also ask to move sidecar proxy on top, and make the arrow land to it

**Comment by danehans** [comment]
@ldemailly I'm not sure what you mean by:

> make the arrow land to it

The Istio ingress controller forwards traffic to the echosvr1 service, which DNAT's to the echosrv1 pod ip.

Here is the latest version:

![fortio_perf_script_diagram_no_ingress_v2](https://user-images.githubusercontent.com/1878195/36507520-c7243e4e-170e-11e8-8fd6-397fe7270b0d.png)

**Comment by ldemailly** [comment]
can you change the box "service: echosrv1" to "istio-proxy" and "pod: echosvr1" to "container: echosvr1" and ditto add the missing envoy in front of echosvr2 ?

**Comment by danehans** [comment]
@ldemailly why change "service: echosrv1" to  "istio-proxy"? The perf script sets-up a service named echosrv1, which proxies to pod: echosrv1. Maybe the better representation would be to make the pods larger and depict the proxy and app containers within the pod(s). Let me know your thoughts.

**Comment by ldemailly** [comment]
I guess the confusion here is the diagram mixes both actual physical components (containers, processes, arrows for network flow,...) with logical concepts (k8s services, ingress spec, etc...)

I would either use different kind of box/lines/color/label for the logical stuff from physical or remove the logical entirely

So again the arrow doesn't go to a service, it goes to a pod and lands in the istio-proxy container which then forwards to the app container

The service to pod mapping is done by the source envoy not at the destination

**Comment by ldemailly** [comment]
We can improve the picture separately

**Comment by ldemailly** [comment]
@danehans I am having issues opening this file with an editor (tried Inkscape, gravitdesigner, omnigrafle... none of which somehow can open this for edit) - before I redo it, can you point me to the source ? (and/or how you made it)

**Comment by ldemailly** [comment]
made a new one in #6059

**Comment by danehans** [comment]
I used draw.io You can get the src [here](https://drive.google.com/drive/folders/13YbtFdztjKIf2Sx6Hve4R_kVIINNxRnH?usp=sharing)
