### ISSUE TITLE
install/updateVersion.sh should generate files in $OUT

### ISSUE THREAD

**Issue by jeffmendoza** [istio/istio#3496]
This will avoid keeping `make clean` and `.gitignore` updated. See #3492

cc @costinm

**Comment by ldemailly** [comment]
careful that changing that means also changing the release making scripts @mattdelco

**Comment by mattdelco** [comment]
Actually the release build already runs updateVersion.sh in $OUT (it uses the "istio-archive" target in the top-level Makefile, which in part runs updateVersion.sh with -d "${ISTIO_OUT}/archive").  I had previously considered changing the other targets to use ${ISTIO_OUT} but it'd be tough to track down all uses that might break (e.g., tests and devs), and I wasn't sure if there was much point in the effort if the helm-related work might make the script obsolete.

**Comment by sdake** [comment]
cc @sdake

**Comment by hklai** [comment]
Obsolete. install/updateVersion.sh is not supposed to be called directly anymore.
