### ISSUE TITLE
Refactor Ledger for improvement

### ISSUE THREAD

**Issue by shirleylb** [istio/istio#34979]
**Describe the feature request**
With the increase of resources, the time to update the Merkle tree and get value from the tree becomes longer. We really want to get performance improvements.  
We noticed that you have already done some efforts. https://github.com/istio/pkg/pull/278 https://github.com/istio/istio/pull/30187 But they are not included in the release version.
1. Why do you give up this idea?
2. Is there any other optimization idea in the future plan?

@therealmitchconnors It will be very appreciated if any idea from you.

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
What do you mean that https://github.com/istio/istio/pull/30187 is not in any release? It seems it was merged a long time ago

**Comment by shirleylb** [comment]
@howardjohn Yes, But they were reverted after that. https://github.com/istio/istio/pull/30319 https://github.com/istio/pkg/pull/322 And it seems there is no progress until now.

**Comment by therealmitchconnors** [comment]
I'm extremely late to this party, but that commit was reverted due to causing panics in some integ tests, which I could never reproduce in my test environment to troubleshoot.  I am trying to find the failures now, as I'd like to resurrect this refactor, but I don't recall which test suite was failing.

**Comment by therealmitchconnors** [comment]
Here is the issue referencing the test failures: https://github.com/istio/istio/issues/30292
