### ISSUE TITLE
Istio installation error

### ISSUE THREAD

**Issue by adet4ever** [istio/istio#34994]
### Bug Description

Delete the istio validation webhooks and everything that has to do with istio when istio uninstalls. following uninstall instruction here: https://istio.io/latest/docs/setup/install/istioctl/#uninstall-istio

I ran into this problem where I was trying to uninstall and re-install istio. the uninstall is fine but the reinstall is causing errors due to left over from webhook validators:
istio-validator-istio-system
istiod-istio-system

The errors looked like:                 
```
~$ istioctl install
This will install the Istio 1.11.1 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
- Processing resources for Istiod.                                                                                                                                           2021-09-01T13:47:16.102170Z     error   installer       failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=30s": dial tcp 10.0.148.163:443: connect: connection refused
2021-09-01T13:47:16.157708Z     error   installer       failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=30s": dial tcp 10.0.148.163:443: connect: connection refused
```
had to run the following to be able to have a clean install again :
 kubectl delete validatingwebhookconfiguration  istiod-istio-system
 kubectl delete validatingwebhookconfiguration istio-validator-istio-system

### Version

```prose
$ istioctl version
no running Istio pods in "istio-system"
1.11.1
azureuser@nodejs-ubuntu:~$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.20.9
```

**Comment by Kmoneal** [comment]
Here's bug report from my own problem: 
[bug-report.tar.gz](https://github.com/istio/istio/files/7094985/bug-report.tar.gz)

**Comment by Kmoneal** [comment]
I only had to run `kubectl delete validatingwebhookconfiguration istiod-istio-system` to install istio again.

**Comment by jacob-delgado** [comment]
@Kmoneal uninstalled istio with `istioctl manifest generate | kubectl delete -f -`. I'm not sure if the original reporter did `istioctl uninstall`.

**Comment by chen-kaka** [comment]
> I only had to run `kubectl delete validatingwebhookconfiguration istiod-istio-system` to install istio again.

it works, thank you!

**Comment by Kampe** [comment]
> > I only had to run `kubectl delete validatingwebhookconfiguration istiod-istio-system` to install istio again.
> 
> it works, thank you!

can confirm, another very useful command.
