### ISSUE TITLE
Single Istio Gateway with TCP protocol is not routing the traffic with Virtual Services defined in different namespaces

### ISSUE THREAD

**Issue by vbalaganes** [istio/istio#35001]
### Bug Description

Hi , 
 
    We have deployed multiple Instances of the same product in our cluster under differnet namespace 
    which are sharing the common istio installed in istio-system.
    
    1. For all the Instances under different namespace , we created a common gateway in istio-system namespace.
    2. Under Every namespace we have Virtual Services created which have reference to the common gateway already 
        created in the istio-system namespace. 
    3. GW created will accept traffic from all hosts.['*]
    4. Each VS under different namespace will redirect to a K8s service in its own namespace based on IP specified in 'hosts' 
        field.

Issue :
   
    The traffic Routing is happening fine , but only one Virtual Service is taken into account.
    So even If the traffic is sent to different host , Istio-Ingressgw tries to send always to the same Virtual Service.
  
**Note :  If the Protocol is HTTP/HTTPS for created GW , all the VS in all namespace are taken into account & works fine.
            If the Protocol is TCP for created GW , only one  VS from any one namespace is taken into account & all other 
            VS or routing is ignored.**

  
     

### Version

```prose
[root@master0 ~]# istioctl version
client version: 1.7.8
control plane version: istio-release-1.7.6
data plane version: 1.7.6 (63 proxies)

[root@master0 ~]# kubectl version --short
Client Version: v1.19.5
Server Version: v1.19.5

[root@master0 ~]# helm version --short
Client: v2.17.0+ga690bad
Server: v2.17.0+ga690bad
```

**Comment by vbalaganes** [comment]
kind: Gateway
metadata:
  name: np-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
      port:
        name: tcp
        number: 3868
        protocol: TCP

kind: VirtualService
metadata:
  name: io-vrs
  namespace: testnamespace
spec:
  gateways:
  - istio-system/np-gateway
  hosts:
  - 100.71.200.3
  tcp:
  - match:
    - port: 3868
    route:
    - destination:
        host: dia-service.testnamespace.svc.cluster.local
        port:
          number: 3868

**Comment by howardjohn** [comment]
For TCP, there is no Host header to match on. All we have is the port. So there is a conflict. https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/
