### ISSUE TITLE
The behavior of istio ingress is different from the ingress documentation.

### ISSUE THREAD

**Issue by wickedev** [istio/istio#35033]
**Describe the feature request**

According to the [ingress documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches), it seems that routing is applied with longest matching path first. But the istio ingress(`kubernetes.io/ingress.class: istio`) seems to be affected by the order described in `paths` . For interoperability, I expect it to work as written in the Ingress documentation.

"In some cases, multiple paths within an Ingress will match a request. In those cases precedence will be given first to the longest matching path. If two paths are still equally matched, precedence will be given to paths with an exact path type over prefix path type."

https://github.com/goharbor/harbor-helm/issues/485#issuecomment-686222551

**Describe alternatives you've considered**

high priority to the longest matching path

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by sathieu** [comment]
@wickedev Could you reopen?

**Comment by wickedev** [comment]
@sathieu @howardjohn @hzxuzhonghu Sorry, I do not have permission to reopen.

**Comment by hzxuzhonghu** [comment]
My initial idea is to sort the rules by url:

1. `Exact` match > `Prefix` match
2. Long Prefix match > short prefix match

**Comment by howardjohn** [comment]
What about 2 Ingress for same host. Do we need to merge them across Ingress and sort?

This is highly related to https://github.com/istio/istio/issues/36719. For that case, we do for sure need to merge

**Comment by hzxuzhonghu** [comment]
> What about 2 Ingress for same host. Do we need to merge them across Ingress and sort?

This depends on k8s behavior, I did not notice that before. And what does other ingress-controller do?
