### ISSUE TITLE
duration much larger than x-envoy-upstream-service-time

### ISSUE THREAD

**Issue by zxh326** [istio/istio#35036]
### Bug Description

I'm not sure if this is a bug, in some requests the duration is much larger than x-envoy-server-time

I don't  know  how to debug, Because it seems random,  same logic, same request, same response.

![image](https://user-images.githubusercontent.com/21299255/132190309-f4d70dec-26e8-4302-af3d-f00ff33fdd39.png)

Here's envoy how explain x-envoy-upstream-service-time

> x-envoy-upstream-service-time
Contains the time in milliseconds spent by the upstream host processing the request and the network latency between Envoy and upstream host. This is useful if the client wants to determine service time compared to network latency between client and Envoy. This header is set on responses.

This value seems to include network latency, so I'm guessing it's not due to network latency

### Version

```prose
> i version
client version: 1.11.2
control plane version: 1.10.2
data plane version: 1.10.2 (219 proxies)
> k version --short
Client Version: v1.22.1
Server Version: v1.18.8
```

### Additional Information

without any VirtualService, DestinationRule

### Affected product area

- [x] Networking

**Comment by bianpengyuan** [comment]
Difference between these two is that duration includes time spend in the proxy.

**Comment by zxh326** [comment]
> Difference between these two is that duration includes time spend in the proxy.

I know the difference between them. I just want to know why some requests are so different, or why so much time is spent on the proxy. Normal requests should only be about 1ms.

**Comment by bianpengyuan** [comment]
Most of the latency should come from filters. First class filters like metadata exchange or stats should not introduce much variance to the latency. Do you have some customized filters or enable some non-default filters?

**Comment by zxh326** [comment]
> Most of the latency should come from filters. First class filters like metadata exchange or stats should not introduce much variance to the latency. Do you have some customized filters or enable some non-default filters?

You mean `EnvoyFilter`? only this

```
> k get EnvoyFilter --all-namespaces
NAMESPACE      NAME                         AGE
istio-system   metadata-exchange-1.10       68d
istio-system   stats-filter-1.10            68d
istio-system   tcp-metadata-exchange-1.10   68d
istio-system   tcp-stats-filter-1.10        68d
```

**Comment by bianpengyuan** [comment]
Ok they should not introduce 40ms latency. Probably the proxy container or the node is not under CPU pressure?

**Comment by zxh326** [comment]
> Ok they should not introduce 40ms latency. Probably the proxy container or the node is under CPU pressure?

Request: 0.1, limit 0.5

It seems that the cpu is not under much pressure.

![image](https://user-images.githubusercontent.com/21299255/132281855-2c578016-1756-4358-9b9e-36d1e5717d0f.png)

**Comment by bianpengyuan** [comment]
Ok it is really hard to identify root cause of this kind of tail latency. So many factors could affect it. I would suggest experimenting with something simple first and see if tail latency goes down, such as scale your app to more replica, increasing sidecar container concurrency, or removing the Istio extensions since they seem to be doing to most heavy work in the filter chain.

**Comment by zxh326** [comment]
@bianpengyuan 

Here is a request for the complete envoy access log. (level: trace)

I found that envoy took 40ms to process the response in [L211-L259](https://gist.github.com/zxh326/a4172631c51cf049ddb74a7d0d375cd2#file-gistfile1-txt-L211-L259)

It looks like there are several error logs like `read error: Resource temporarily unavailable`, not sure if it's because of this. 
https://gist.github.com/zxh326/a4172631c51cf049ddb74a7d0d375cd2

**Comment by bianpengyuan** [comment]
Yeah I think that suggest the socket buffer is full occasionally which causes the high delay. @lambdai probably could give a better insight here, but I think scale up would be helpful.

**Comment by stanxing** [comment]
we debugged the problem of 40ms latency and found that the root cause was **Nagle algorithm and Delay ACK of TCP**. Out backend service is  written in Nodejs and it enabled Nagle algorithm by default  in server side.  

![nagle-dump](https://user-images.githubusercontent.com/23288646/138389888-925dcbdd-bed5-489b-ad9b-113d8c1d7087.png)


But we found a problem that the MSS(Max Segment Size) of envoy negotiates with the upstream process is 65495，but the MSS of client negotiates with envoy is 1460.In our case, if not injected istio-proxy, no delay was obversed, because the length of out data is greater than 1460 but less than 65495.

This inconsistency has troubled our troubleshooting.

Is it possible to keep them consistent?

**Comment by bianpengyuan** [comment]
Not familiar with MTU or MSS, but it looks like Envoy uses local loopback interface MTU when connecting to the upstream? I thought with 1.10 we should have already configure envoy to use eth0 interface, which should have small MTU/MSS.. https://istio.io/latest/blog/2021/upcoming-networking-changes/

**Comment by stanxing** [comment]
surprisingly, my istio version is 1.10.2...

**Comment by stanxing** [comment]
I checked the connections in container, the destination ip envoy connected to is pod ip instead of localhost, I don't know what's wrong...How should I troubleshoot it?
![image](https://user-images.githubusercontent.com/23288646/142178224-9ded6b8e-9e55-4264-a4f2-1ec870d6ac0e.png)

**Comment by stanxing** [comment]
Supplement the configuration of inbound direction.

istioctl pc cluster user-service-xingpeng-istio-7d6bfd5f65-frv7p --direction inbound -o json
```
[
    {
        "name": "inbound|3000||",
        "type": "ORIGINAL_DST",
        "connectTimeout": "10s",
        "lbPolicy": "CLUSTER_PROVIDED",
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295,
                    "trackRemaining": true
                }
            ]
        },
        "cleanupInterval": "60s",
        "upstreamBindConfig": {
            "sourceAddress": {
                "address": "127.0.0.6",
                "portValue": 0
            }
        }
    ...
]
```

**Comment by bianpengyuan** [comment]
> surprisingly, my istio version is 1.10.2...

Not sure.. probably some kernel implementation detail. There could probably be a way to tune mtu, but would it be easier to turn off Nagle algorithm?

**Comment by stanxing** [comment]
> but would it be easier to turn off Nagle algorithm?

Yes, i did it. Just curious about the size of MSS.
