### ISSUE TITLE
Wasm-based telementry cause envoy resetting stream

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#35034]
### Bug Description

Wasm-based telementry cause envoy resetting stream. See details on https://github.com/envoyproxy/envoy/issues/17574

### Version

```prose
$ istioctl version
client version: 1.10.0
control plane version: 1.10.1
data plane version: 1.10.1 (10 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by mathetake** [comment]
Would it be possible to provide us with the reproducer or anything? 

cc @bianpengyuan

**Comment by Patrick0308** [comment]
@mathetake It's so hard to reproducer. We just know that the envoy reset stream after a few days of running. We only has some error log and config dump file.
