### ISSUE TITLE
Istio ingressgateway fails to get ready after being restarted

### ISSUE THREAD

**Issue by AS011** [istio/istio#35032]
### Bug Description

Whenever my istio-ingressgateway pod gets restarted or i restarted it manually the pod comes back in running state but the deployment shows status as 0/1 not ready . Have attach screenshot for reference. 
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/26535491/132176678-c5f79bac-2c6d-49b7-ad77-52039d55ffc3.png">

To fix the above problem i have to first scale down the deployment to 0 , delete the replica sets and then scale up back which i think is not a good thing to do as what if the same thing happens production env. 

### Version

```prose
client version: 1.10.2-asm.3
control plane version: 1.10.2-asm.3
data plane version: 1.10.2-asm.3 (50 proxies)

Client Version: v1.21.0
Server Version: v1.20.8-gke.2100
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
How can the pod be ready but the deployment not be? This sounds more like a Kubernetes bug than an Istio one...

**Comment by howardjohn** [comment]
Eihter way, it would be good to see the yaml of the pod and deployment and any events on the deployment

**Comment by xichengliudui** [comment]
kubectl describe deploy ingressgateway -n istio-system
