### ISSUE TITLE
k8s istio access to external service rabbitmq lost message

### ISSUE THREAD

**Issue by githubmars2020** [istio/istio#35056]
### Bug Description

k8s  istio python access to external service rabbitmq lost message
external service ServiceEntry config

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: app
  name: rabbitmq
spec:
  hosts:
  - rabbitmq1-aba566e2afe2ae10.elb.us-west-2.amazonaws.com
  ports:
  - number: 5672
    name: tcp
    protocol: tcp
  resolution: DNS
  location: MESH_EXTERNAL

### Version

```prose
➜  ~ istioctl version
client version: 1.10.0
control plane version: 1.10.2
data plane version: 1.10.2 (51 proxies)
➜  ~ kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.2-eks-0389ca3
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by hzxuzhonghu** [comment]
Does the connection reconnect? In theory tcp could not lose any packet, not to mention the whole message.

**Comment by cfanbo** [comment]
how i do know connection reconnet?
This problem occurs in both test environments
