### ISSUE TITLE
Switch to SharedInformer instead of Informer across Istio

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3505]
Multiple kube-client instantiations and multiple Informers in Istio create multiple caches of k8s resources, wasting memory and possibly having scalability impact.

Switch to SharedInformer which keeps one copy of each object per process.

Context:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-dev/xyWUWUWH4Yg/KpmSa6SXAQAJ

**Comment by andraxylia** [comment]
cc @costinm @douglas-reid

**Comment by kyessenov** [comment]
huh
https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/controller.go#L69
 ?

**Comment by andraxylia** [comment]
do a grep, there are a few other places in the service registry.

**Comment by kyessenov** [comment]
I did a grep (I wrote that code). Can you point me exactly what's the issue?

**Comment by douglas-reid** [comment]
For the mixer/ section, there was a recent PR to reduce kube-client creation. The only place I see an Informer vs SharedInformer is

```
mixer/pkg/config/crd/admit.go:  _, controller := cache.NewInformer(listWatch, &v1.Secret{}, 30*time.Second,
```

cc: @jmuk

**Comment by kyessenov** [comment]
Great find. This should probably be in scope for @ozevren and @xiaolanz since the config backend will need to migrate.  Not sure why @gnirodi is assigned.

**Comment by mandarjog** [comment]
Mixer proper uses https://github.com/istio/istio/blob/master/mixer/pkg/config/crd/store.go#L68 shared informer already.

Changing Admission controller is not going to affect the Pilot  or the original problem.

**Comment by kyessenov** [comment]
Please change the areas to config, too, as this has little to do with networking.

**Comment by ozevren** [comment]
Galley is already on SharedInformer plan.
