### ISSUE TITLE
Expire stats not reported after some time

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#35066]
**Describe the feature request**

Ensure istio prometheus metrics eventually expire.

When issuing a request to an internal (or external), the sidecar proxy starts exposing multiple metric series regarding that request.
```
# within an injected pod
curl http://httpbin.org

# resulting metrics
istio_requests_total{response_code="200",reporter="source",destination_service="httpbin.org",destination_service_name="PassthroughCluster",...} 1
...
```
When an injected pod makes requests to *many* dependencies (i.e foo.example.com / bar.example.com / baz.ns.svc.cluster.local / ...), the number of prometheus metrics grows linearly with the number of dependencies. This can be problematic for services with many dependencies, for example for egress gateways. The metrics are reported until the pod is restarted, even if the pod ever issued a single request to that dependency. I currently have this issue with a service only communicating with a few dependencies at any point in time, but many over time.  

Is there a mechanism to expired metrics ? For example, the sidecar proxy only exposes those metrics for 10/15 minutes and then stops reporting them given to minimise the number of reported time-series?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
This is a known issue and is tracked at https://github.com/istio/istio/issues/21377. Unfortunately fix will be quite complex. Some work around to reduce cardinality is listed at https://istio.io/latest/faq/metrics-and-logs/#metric-expiry. I am going to close this issue and let's use https://github.com/istio/istio/issues/21377 to track this feature. Thanks!

**Comment by chaudyg** [comment]
Thx @bianpengyuan
