### ISSUE TITLE
I destoryed one k8s cluster,I have three cluster.but in another cluster the endpoint is still healthy?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35082]
### Bug Description

[root@localhost ~]# istioctl pc endpoint productpage-v1-7954fd8cd6-hj8xz -n istio|grep productpage
172.22.0.18:9080                 HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local
192.168.229.100:15443            HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local
192.168.229.101:15443            HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local

I destroyed 192.168.229.100:15443  cluster

### Version

```prose
[root@localhost ~]# istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (9 proxies)

[root@localhost ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

**Comment by hzxuzhonghu** [comment]
I guess you mean you simply destroyed the k8s cluster, but you donot remove it from the multicluster secret. If so this is expected. It is no good way for Pilot do healthcheck for a cluster.

**Comment by 13567436138** [comment]
you mean multi cluster  do not check other cluster endpoint
