### ISSUE TITLE
Ability to disable envoy extensions

### ISSUE THREAD

**Issue by venkatk-25** [istio/istio#35104]
**Describe the feature request**
Envoy's [Thread model](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/threat_model) has various extensions listed as alpha which are enabled by default.
Providing an option to disable these filters would be useful for security reasons
https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-disable-extensions

Lot of these extensions are enabled by default in istio-proxy, but most of them are either not being used or there is no clarity on if they are being used.

A subset from the report which are enabled but mostly not used below:

The below extensions enabled and have alpha status, they might be getting used for generating metrics, not sure all are required.

Envoy.access_loggers.wasm
Envoy.bootstrap.wasm
Envoy.filters.http.wasm
Envoy.filters.network.wasm
Envoy.filters.http.grpc_stats

The below extensions enabled have an unknown security posture and in alpha status.

Envoy.filters.http.adaptive_concurrency
Envoy.filters.http.admission_control
Envoy.filters.http.cdn_loop
Envoy.filters.http.composite
Envoy.filters.http.ext_proc
Envoy.filters.http.grpc_http1_bridge
Envoy.filters.http.grpc_http1_reverse_bridge
Envoy.filters.http.local_ratelimit
Envoy.filters.network.direct_response
Envoy.filters.network.echo
Envoy.filters.network.sni_cluster
Envoy.filters.network.sni_dynamic_forward_proxy
Envoy.rate_limit_descriptors.expr
Envoy.wasm.runtime.null
Envoy.wasm.runtime.v8

There are some extensions that should be used only when both the upstream and downstream are trusted. Some extensions within those are tagged alpha. 

Envoy.filters.http.aws_lambda
Envoy.filters.http.aws_request_signing
Envoy.filters.http.tap
Envoy.filters.network.dubbo_proxy
Envoy.filters.network.mysql_proxy
Envoy.filters.network.rocketmq_proxy
Envoy.filters.network.zookeeper_proxy
Envoy.transport_sockets.tap

Envoy.filters.http.original_src

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
I guess an alternative is that you can control EnvoyFilter resource with Rbac (i.e. only trusted admin can specify EnvoyFilter) to avoid random envoy filter being injected/used.

**Comment by kyessenov** [comment]
Some of the extensions should really be promoted from alpha (e.g. wasm stuff) since they are core to istio feature set.

Other data plane extensions are already guarded by flags (mongo, mysql) and should be disabled by default, and potentially removed from the build.

**Comment by venkatk-25** [comment]
Controlling envoyFilter is difficult, as ratelimiting is one of the key features developers are interested in and envoyFilter os the only way to do it currently.

Like idea of @kyessenov, if it is agreeable, as an alternative to my suggestion.

**Comment by venkatk-25** [comment]
@bianpengyuan can you suggest what is a suggested way to fix among the following or something else completely,
1. parameterizing [cmdOption](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-disable-extensions) as part of envoy startup
2. Disabling these unused alpha extensions as part of the envoy build. 

If any of these approaches is fine, I can start working on these changes.

**Comment by bianpengyuan** [comment]
I don't think 2 is feasible, it will be a breaking change since there are definitely quite some usage of those extensions with Istio proxy.

1 is doable via a proxy env variable. Although I am not sure if that would be a good idea (you'd need to keep eyes on every Envoy release and disable any new extensions, which seems annoying). We are introducing first class rate limiting API by the way. If that is only use case, probably long term solution is to disable EnvoyFilter completely in your cluster to prevent any accidental usage of random extensions.

**Comment by venkatk-25** [comment]
@bianpengyuan makes sense. 

When is the first class ratelimit support coming in 1.12 or 1.13 ?

Also, do you think we can limit usages of specific extensions on EnvoyFilter with custom validation webhook( may be OPA? ) would be viable in the meantime if it is far off.

**Comment by bianpengyuan** [comment]
> When is the first class ratelimit support coming in 1.12 or 1.13 ?

@kyessenov drives the work and would know better, but I think 1.12 might be too ambitious. It will more likely happen at 1.13.

> Also, do you think we can limit usages of specific extensions on EnvoyFilter with custom validation webhook( may be OPA? ) would be viable in the meantime if it is far off.

Yeah I think that will work, by limiting operation and filters being operated.
