### ISSUE TITLE
Setting init and proxy container CPU limit and request

### ISSUE THREAD

**Issue by burk** [istio/istio#35110]
Hey,

To get pods into the Guaranteed QoS class in kubernetes, these points need to be true for all the containers in the pod (even init containers):

 - Every Container in the Pod must have a memory limit and a memory request.
 - For every Container in the Pod, the memory limit must equal the memory request.
 - Every Container in the Pod must have a CPU limit and a CPU request.
 - For every Container in the Pod, the CPU limit must equal the CPU request.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

Is there a way to configure both CPU and memory requests and limits for the istio containers of a pod, without changing the global settings?

I've found `sidecar.istio.io/proxyCPU` and `sidecar.istio.io/proxyMemory`, which allows setting the CPU and memory requests, but not limits.

**Comment by venkatk-25** [comment]
Can be done with `sidecar.istio.io/proxyCPULimit` and `sidecar.istio.io/proxyMemoryLimit`. 
Full list of annotations supported by istio can be found [here](https://istio.io/latest/docs/reference/config/annotations/)

**Comment by burk** [comment]
Worked great, thanks!
