### ISSUE TITLE
istio installation fails on a Raspberry Pi  3ks cluster

### ISSUE THREAD

**Issue by kambei** [istio/istio#35115]
### Bug Description

I have a k3s cluster (Raspberry PI 4).

If I try to install istio with command:
`istioctl install --set profile=demo -y`  it fails on second step saying: 

`Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition`

### Version

```prose
$ istioctl version
no running Istio pods in "istio-system"
1.11.2
$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.21.4+k3s1
```

### Additional Information

output of `kubectl logs <istiod-pod>` is:

`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by howardjohn** [comment]
Unfortunately ARM is not yet supported. We are tracking this effort in https://github.com/istio/istio/issues/21094
