### ISSUE TITLE
Enable TLS termination on the envoy sidecar

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#35111]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Enable TLS termination on the envoy sidecar.
Currently, the server side envoy proxy running as a sidecar can only allow mTLS for secure connection. In a regular Istio mesh deployment the onus of one way TLS termination for downstream requests is on the ingress gateway. Though this satisfies most of the use cases, for some use cases (like an API Gateway on mesh) the ingress gateway resource is not necessarily needed.

This feature request is to introduce an annotation "sidecar.istio.io/proxyMode: true" on a deployment that runs the Istio proxy on the pod in hybrid mode, i.e., it performs a function of both a router/gateway and a sidecar.

**Describe alternatives you've considered**
1. Create a custom EnvoyFilter configuration as described in [this](https://github.com/istio/istio/issues/21368) issue. The problem with this approach is that this could lead to maintenance overhead as EnvoyFilters does not guarantee backwards compatibility. 
2. Use the Ingress Gateway resource to offload the TLS termination. Going this route forces us to add an unnecessary network hop which can be avoided by this feature.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Related Issue: https://github.com/istio/istio/issues/21368
RFC (WIP): https://docs.google.com/document/d/15Qhr7errbylXEzxxCK7ij_oUpn4E5SFU2uDdl_n2GIc/edit?usp=sharing

**Comment by sha-rath** [comment]
I had the exact same request. Linking it here: #32595
The proposal was to enhance the current Sidecar API, since it already has the _IstioIngressListener_ option. The TLS settings from Gateways can somehow be copied to the Sidecar to provide the router like functionality you mention in your hybrid approach.
