### ISSUE TITLE
dr localityloadblance make distribute and failover both use 

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35124]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
```
Resource: "networking.istio.io/v1alpha3, Resource=destinationrules", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=DestinationRule"
Name: "productpage", Namespace: "istio"
for: "dr-productpage-failover.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
        * can not simultaneously specify 'distribute' and 'failover'

```
I have a case,I want to use distribute to weighted loadblance workload in different cluster.
but if cluster2 is down.I want failover from cluster2 to other cluster.
so I need to use both
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
cc: @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
>I have a case,I want to use distribute to weighted loadblance workload in different cluster.
but if cluster2 is down.I want failover from cluster2 to other cluster.

Unfortunately, envoy does not support coupling prioritized lb with weighted lb.

**Comment by 13567436138** [comment]
so how to implement my situation?
