### ISSUE TITLE
Operator Canary Upgrades Fail

### ISSUE THREAD

**Issue by danehans** [istio/istio#35139]
### Bug Description

Canary upgrades fail when following the operator install/canary upgrade docs. The non-revisioned operator reconciles the revisioned IstioOperator:

```
$ kubectl logs deploy/istio-operator -n istio-operator
...
2021-09-10T19:08:57.129277Z     info    installer       Reconciling IstioOperator
2021-09-10T19:08:57.129826Z     info    Adding finalizer istio-finalizer.install.istio.io to istio-system/example-istiocontrolplane-1-11-1
2021-09-10T19:08:57.136818Z     info    installer       Updating IstioOperator
```

```
kubectl get iop -A                                             
NAMESPACE      NAME                               REVISION   STATUS    AGE
istio-system   example-istiocontrolplane                     HEALTHY   51m
istio-system   example-istiocontrolplane-1-11-1   1-11-1     HEALTHY   47m
```

### Version

```prose
1.10.3 > 1.11.1
```

### Additional Information

Follow [these steps](https://gist.github.com/danehans/1381bbf6add44efe99cd0776b3013340#file-05_upstream_repro-md) to repro.

**Comment by pupseba** [comment]
For further reference: https://github.com/istio/istio/issues/32828

**Comment by danehans** [comment]
xref [Slack discussion](https://istio.slack.com/archives/C6KA8TTSS/p1631228967007200)

**Comment by danehans** [comment]
As a workaround, I'm able to set `replicas: 0` to the deployment of the unrevisioned operator so only the revisioned operator is running and reconciling the IstioOperator resource (not ideal).
