### ISSUE TITLE
When I keep accessing the service, I delete iptables from the Pod, and the traffic behavior is abnormal. Is it a bug in envoy or iptables?

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#35157]
### Bug Description

1. I have two services A and B. Both A and B are injected with sidecars. On the service side of A, I constantly use the following command **while true; do curl api-B;sleep 1;done;**(http protocol)  to visit B at an interval of 1 second.
2. Then I manually deleted iptables (pilot-agent istio-clean-iptables) in service B, and found that the traffic passing through service B still passes through envoy.
3. Later, I   stop   **while true; do curl api-B;sleep 1;done;**  and after a break of 5s or more, execute this command again, and the traffic will not go through the envoy of service B.  why?

### Version

```prose
istio : 1.8.0

kubernetes: Server Version: v1.16.8
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
Cleaning up iptables on running pod is not something that is supported. That being said, its probably because `clean-iptables` command needs a bunch of arguments (matching the original construction command) to actually work.

**Comment by tanjunchen** [comment]
@howardjohn    When I stop the curl or sleep for a few seconds and then visit again, cleaning up the iptables rules works, but the traffic is not envoy. If I don't stop the visit, the traffic will always go through envoy.

**Comment by adairxie** [comment]
@tanjunchen Hello，has the problem been solved? I found that closing iptables don't take effect to establish connection.

**Comment by tanjunchen** [comment]
> @tanjunchen Hello，has the problem been solved? I found that closing iptables don't take effect to established connection.

@adairxie  hello, I haven't solved this problem。you can see  https://listman.redhat.com/archives/rhl-list/2006-January/msg03380.html   If you solve it, remember to sync it with me. thanks.
