### ISSUE TITLE
Get error message in kubernetes IPv6 only cluster when executing command `istioctl proxy-config route`

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#35177]
### Bug Description

I get error message when executing istioctl proxy-config route in my cluster which is kubernetes IPv6 only.
And the detail as below:

```
$ istioctl proxy-config route httpbin-74fb669cc6-bpm7b --name 80 -ojson
2021-09-14T06:19:58.748624Z	error	klog	an error occurred forwarding 45017 -> 15000: error forwarding port 15000 to pod df101dc6c65effd3b0904bf8d5a9b3cc124163cefac68106ce348e1247ebd647, uid : exit status 1: 2021/09/14 14:19:58 socat[27452] E connect(5, AF=2 127.0.0.1:15000, 16): Connection refused
Error: failed to execute command on httpbin-74fb669cc6-bpm7b.default sidecar: failure running port forward process: Get "http://127.0.0.1:45017/config_dump": EOF
```

### Version

```prose
$ istioctl version
client version: 1.11.1
control plane version: ce6205d503e5c5e41af496ebbe01ece7dc6c3547
data plane version: 1.11.1 (4 proxies)
$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.1
```

### Additional Information

Found it when working on [issue#](https://github.com/istio/istio/issues/34966)

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by pseudonator** [comment]
@zhlsunshine Il just throw my findings here as per https://github.com/istio/istio/issues/34358.
Also I do notice that your port-forward is using `socat`. Its possible that your runtime doesn't have the fix I talk about.

**Comment by zhlsunshine** [comment]
Hi @pseudonator, I did some investigation again for this issue, as you know, Istio implement its own port-forwarder function, and it's very similar with `kubectl`, and it's okay for `kubectl port-forward`, but not works for `Istio`. So this makes me more confuse.

**Comment by zhlsunshine** [comment]
this error relates to kubernetes container runtime, so there are 2 cases:

1. Docker as the container runtime 
  According to [Istioctl commands support in IPv6 only cluster](https://docs.google.com/document/d/1a6eZ6ldF2l7De3vX-SBAHmuJ00uxlgpPznHocG7zcfs/edit?usp=sharing,) user need to change the runtime from **Docker** to **containerd**
2. containerd as the container runtime
  According to [istioctl commands fail in an IPv6 only cluster #34358](https://github.com/istio/istio/issues/34358#issuecomment-923413096), user should make sure that the containerd version is higher than 1.5.0

There would be no error if follow alternative above.
