### ISSUE TITLE
Why readiness depend on stats?

### ISSUE THREAD

**Issue by zirain** [istio/istio#35175]
**Describe the feature request**
I'm trying to disable stats for special usage, but got [issue](https://github.com/envoyproxy/envoy/issues/18065)

as the issue mentioned, I do believe that readiness depend on envoy stats is not a good design, or there some reason made istio do this?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
We need to determine if envoy is ready. Currently there is no other way to do this. 

Disabling all stats doesn't seem like something we really need to do; there are only like 3 counters we depend on, is it too expensive to have even those 3?

**Comment by zirain** [comment]
> We need to determine if envoy is ready. Currently there is no other way to do this.
> 
> Disabling all stats doesn't seem like something we really need to do; there are only like 3 counters we depend on, is it too expensive to have even those 3?
In [aeraki lazyxds](https://github.com/aeraki-framework/aeraki/tree/master/lazyxds), the `lazy xds egress` component contains all source pod and destination pod istio_requests_total counter

**Comment by howardjohn** [comment]
> update: I can just remove the istio.stats filter on this scenario？


Yes

And in general if you need to disable stats you could disable all but the 3 we need for readiness, so it doesn't seem like an issue that we depend on stats.

**Comment by zirain** [comment]
> > update: I can just remove the istio.stats filter on this scenario？
> 
> Yes
> 
> And in general if you need to disable stats you could disable all but the 3 we need for readiness, so it doesn't seem like an issue that we depend on stats.

so far, I agree with this, thx!
