### ISSUE TITLE
TestServiceExportedInOneCluster flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#35181]
TestServiceExportedInOneCluster/b_exported_in_primary/svc-a/to_svc-b/from_cross-network-primary expand_less | 1m2s
-- | --
discoverability_test.go:126: failed calling svc-a (cluster=cross-network-primary)->'http://svc-b.mcs-1-98176.svc.clusterset.local:80/': call failed from svc-a (cluster=cross-network-primary) to http://svc-b.mcs-1-98176.svc.clusterset.local:80 (using http): timeout while waiting after 493 attempts (last error: reached cluster not in [primary cross-network-primary], got map[cross-network-primary:25 primary:20 remote:5])

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35030/integ-pilot-multicluster-tests_istio/1437671270010327040

**Comment by howardjohn** [comment]
Yeah we should fix this, tracking in https://github.com/istio/istio/issues/34051 though
