### ISSUE TITLE
Aks node in the pool is not able to pull image from docker.io

### ISSUE THREAD

**Issue by vivuu1989** [istio/istio#35186]
### Bug Description

in our AKS cluster - 1.20.9 enabled with azure CNI, we have istio configured as service mesh. Our AKS cluster is running in conatainer subnet (10.50.0.0/22) has a nsg already opened to docker.io connectivity over 443.
 Now we are facing a strange issue in our cluster.
But its noticed that whenever a kubernetes node in the nodepool gets the starting ip of 10.50.0.4 from its subnet , it will get connection error to docker.io.
But all other nodes in the same pool in the subnet can connect without any problem.

> Failed to pull image "docker.io/istio/proxyv2:1.11.2": rpc error: code
> = Unknown desc = failed to pull and unpack image "docker.io/istio/proxyv2:1.11.2": failed to resolve reference
> "docker.io/istio/proxyv2:1.11.2": failed to do request: Head
> "https://registry-1.docker.io/v2/istio/proxyv2/manifests/1.11.2":
> net/http: TLS handshake timeout

### Version

```prose
control plane version: 1.11.2
data plane version: 1.11.2 (20 proxies)
```

**Comment by bianpengyuan** [comment]
This does not seem to relate to Istio, which should not interfere container runtime. Any signal shows that this might relate to istio?
