### ISSUE TITLE
Why is the configuration not effective when install istio?

### ISSUE THREAD

**Issue by cfanbo** [istio/istio#35199]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
install istio, document https://istio.io/latest/docs/setup/install/virtual-machine/
```
$ istioctl install -f vm-cluster.yaml --set values.pilot.env.PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION=true --set values.pilot.env.PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS=true
```
i assign <code>--set values.global.proxy.privileged=true</code>,  but View by command<code>istioctl profile dump --config-path=values.global.proxy</code>, why privileged value unchange?

```
$ istioctl profile dump --config-path=values.global.proxy
autoInject: enabled
clusterDomain: cluster.local
componentLogLevel: misc:error
enableCoreDump: false
excludeIPRanges: ""
excludeInboundPorts: ""
excludeOutboundPorts: ""
image: proxyv2
includeIPRanges: '*'
logLevel: warning
privileged: false # why unchange?
readinessFailureThreshold: 30
readinessInitialDelaySeconds: 1
readinessPeriodSeconds: 2
resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi
statusPort: 15020
tracer: zipkin
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Comment by howardjohn** [comment]
`istioctl profile dump ` is showing the default config, not what you have installed in the cluster.

**Comment by cfanbo** [comment]
How to view the installed configuration？
