### ISSUE TITLE
Consider decreasing gRPC Read/Write buffer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35197]
Currently, we use gRPC default rw buffer sizes, keeping 96kb allocated for these per connection. So for 5k clients, we use about 500mb for these.

Its not clear if the buffers are adding much benefit for the cost they bring as Istiod scales up to a large number of clients. Additionally, real world testing has shown that the cost of the buffers appears to actually be 2x what is discussed above (ie 1gb for 5k clients). The test below looks at the default settings vs buffer disabled:
![2021-14-09_16-42-26](https://user-images.githubusercontent.com/623453/133348009-27634433-5a84-4537-8d99-cb6d64720c13.png)

**Comment by hzxuzhonghu** [comment]
```
// WithWriteBufferSize determines how much data can be batched before doing a
// write on the wire. The corresponding memory allocation for this buffer will
// be twice the size to keep syscalls low. The default value for this buffer is
// 32KB.
//
// Zero will disable the write buffer such that each write will be on underlying
// connection. Note: A Send call may not directly translate to a write.
```

In my knowledge, the rw buffer could improve network communication throughput.

**Comment by howardjohn** [comment]
```
$ grun ./client -test_name=grpc_test -rpc_type=streaming
build complete
qps: 12504.4
Latency: (50/90/99 %ile): 74.02µs/102.132µs/165.394µs
Client CPU utilization: 1m6.319047511s
Client CPU profile: /tmp/grpc_test.cpu
Client Mem Profile: /tmp/grpc_test.mem
$ grun ./client -test_name=grpc_test -rpc_type=streaming
build complete
qps: 9923.533333333333
Latency: (50/90/99 %ile): 95.23µs/119.725µs/186.564µs
Client CPU utilization: 1m13.412146293s
Client CPU profile: /tmp/grpc_test.cpu
Client Mem Profile: /tmp/grpc_test.mem
```

Top is with buffer, bottom without. using grpc's benchmarks.

But.. that is with 1 byte messages. Istio's are way bigger. With 100kb messages the difference is within 1% (likely measuring noise).

Interestingly, there is a grpc write buffer *and* the underlying golang.org/x/http2 library has its own buffer...

**Comment by hzxuzhonghu** [comment]
Maybe we should ask grpc maintainers for help, from the tests, we can see it has very little influence.  I guess the underlying buffer works. Once I did a test on pure tcp throughput long before, the difference between buffered and unbuffered is very obvious.
