### ISSUE TITLE
Customer pain points meta issue

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3519]
# Initial Implementation Pain Points

## Mesh definition 
- only supports "whitelisting" approach (i.e., `includeIPRanges`); in our case, likely would prefer a "blacklisting" approach (e.g., `excludeIPRanges`)
- becomes problematic if _any_ component that is not owned / managed by the istio user requires external connections over TLS; if an istio user can not configure / update the source of these external components to use the correct scheme and port (i.e., `http`, `443`), then must explicitly define the mesh using whitelist approach and include _all_ potential external CIDRs they'd like to include in the mesh; in our case, that means additional tooling to automate the configuration for [AWS CIDRs](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html)
 - several GCP products we currently use meet these conditions:
   * Cloud Endpoints  (`https://servicecontrol.googleapis.com/`)
   * Cloud Logging Clients / Agents (`https://logging.googleapis.com`)
   * Cloud Trace Clients / Agents (`https://cloudtrace.googleapis.com`)

## Service protocol configuration
- currently requires the user to follow convention of prefixing port names with the relevant scheme; an annotation-based API / convention would be preferred
- [limitations of port name length](https://github.com/kubernetes/node-problem-detector/blob/c430627afa185c83bf098d2de5d32e4e5a9c72af/vendor/k8s.io/kubernetes/pkg/api/types.go#L40-L43) one factor to consider.. 

## Readiness / Liveness probes
- I believe the istio team is working on a solution for the case where the “kubelet” is the client and an envoy running in sidecar mode is the destination
- Using the `exec` workaround for now, but that is not always straightforward.. in the case where pod contains containers running images managed externally, CLI HTTP clients are not always available (e.g., [cloud-endpoints](gcr.io/endpoints-release/endpoints-runtime:1.11.0) does not include `curl`)
- Also want to highlight the case where the client is external to the cluster (GCLB in our case) and the destination istio-ingress’s envoy proxy

## GCLB -> istio-ingress
- [cross-namespace limitations](https://github.com/kubernetes/kubernetes/issues/17088) of native Ingress resource requires istio users who prefer targeting the istio-ingress service from [GCE Ingress Controller](https://github.com/kubernetes/ingress-gce) configure their Ingress resource in the `istio-system` namespace
- default istio-ingress Service configuration must be updated to include `service.alpha.kubernetes.io/app-protocols` annotation if TLS from GCLB -> istio-ingress required
- in our case, changed istio-ingress Service type to `NodePort` (no issue there, aside from the customized istio.yaml .. seems like a good candidate for a helm chart parameter if it isn’t already)
- healthcheck / readinessProbes issues: 
  * GCLB requires a healthcheck (and currently GCE Ingress Controller [lacks support for customizing healthcheck via k8s API](https://github.com/kubernetes/ingress-gce/issues/42))
  * istio-ingress deployment must be updated to include a readinessProbe; this currently must use `httpGet` action;  default used if no readinessProbe exists is `/`
  * without existing services configured w/ an Ingress of `kubernetes.io/ingress.class: "istio"` that support requests for the `/` path, healthchecks will fail preventing GCLB Ingress from initializing
  * because request originates from outside the cluster (and requires `httpGet`), can not target `port: 15000`, `path: /healthcheck/ok` of envoy admin interface
- current work around was to run a dummy service and target the istio-ingress envoy container's readinessProbe to a path on that service (e.g., `/status/200` of httpbin service)
- preference would be a dedicated health check endpoint / service in the envoy container itself (similar to cloud endpoints `/endpoints_status`), preferably on a configurable port (also, similar to cloud endpoints `--status_port` option / `STATUS_PORT` env variable)

## istio-"ingress"
- use of the native k8s Ingress resource type (with custom class) can be confusing; my understanding is this configuration is essentially updating the istio-ingress deployment's envoy configuration and is not creating a _new_ LB resource w/ a new externalIP, etc
- would probably prefer a Custom Resource interface here

**Comment by sakshigoel12** [comment]
@ldemailly please could you split these into actionable work items?

**Comment by terinjokes** [comment]
I agree with most of this, though I have no experience with GCLB (being on our own machines).

However, the use of Kubernetes's Ingress resources seems correct to me here. The behavior is not much different than if you had deployed the nginx ingress and configured your Ingress resources to use the nginx class.

**Comment by andraxylia** [comment]
Will need to split this into issues.

**Comment by julianvmodesto** [comment]
Is there a current workaround and example for the GCLB => Istio Ingressgateway config?

**Comment by julianvmodesto** [comment]
This is a big blocker for some pretty interesting Istio <=> GCLB L7 usage w/ features like Cloud IAP + Cloud Armor for us.

**Comment by quanjielin** [comment]
Update for GCLB->Istio ingress-gateway:
Readiness probe was added to Istio ingress-gateway recently; in current Istio/IAP setup, GCLB depends on Istio ingress-gateway readiness probe for health check(details see https://github.com/istio/istio/issues/9385).

**Comment by howardjohn** [comment]
Can we break this into actionable issues? It is hard to manage as is

**Comment by howardjohn** [comment]
I think these are all solved as of 1.3
