### ISSUE TITLE
Istio GW has istio_mutual and i get authentication_denied

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#35206]
Hello

I am using istio version 1.9.16

I have a GW as follows 

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: shared-istio-gateway
  namespace: mysps
  resourceVersion: "28916480"
  uid: 42f4b8de-5cf0-486b-a7d1-713f5264cab6
spec:
  selector:
    app: arunsps
  servers:
  - hosts:
    - '*'
    port:
      name: http-80
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
```

When i a curl request with my client certs 
`curl --cacert ./cacert.pem --cert ./client.crt --key ./client.key -vk https://site1-samson.dyn.nesc.nokia.net/soap/monitoring`

I do see this error in istio ingress logs and i get a 401.

`[2021-09-15T14:27:09.556Z] "GET /soap/monitoring HTTP/1.1" 401 - istio_authn_access_denied - "-" 0 27 0 - "10.139.155.152" "curl/7.29.0" "870c9a99-31ab-9880-b867-2b9ab3344cfa" "site1-samson.dyn.nesc.nokia.net" "-" - - 172.18.162.164:443 10.139.155.152:33910 site1-samson.dyn.nesc.nokia.net -`

Am i missing anything here ?

I do not have any authorization policies at all in the system.

**Comment by bianpengyuan** [comment]
Do you have any `RequestAuthentication` set up in your cluster?

**Comment by arunpmohan** [comment]
No 
```
kubectl get requestauthentication -A
No resources found
```

**Comment by hzxuzhonghu** [comment]
You should not use `ISTIO_MUTUAL` in gateway, if you want to terninate tls in gateway. Please refer: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway

**Comment by arunpmohan** [comment]
Thanks for your answer. So ISTIO_MUTUAL only meant for istio components to talk to each other.. If i need a non ISTIO component to talk then should i be using MUTUAL only ? Is that what you mean ?

**Comment by hzxuzhonghu** [comment]
Yes, never use `ISTIO_MUTUAL ` if one peer is mesh external

**Comment by arunpmohan** [comment]
Thank you.
