### ISSUE TITLE
Ingress report error syncing load balancer

### ISSUE THREAD

**Issue by soloradish** [istio/istio#35228]
We run a AWS EKS cluster with 5 nodes. installed istio version is `1.11.1`, our EKS version is 1.21
and we get this error periodically. 
```
Error syncing load balancer: failed to ensure load balancer: error detaching AWS loadbalancer from subnets: "InvalidConfigurationRequest: Requested configuration change for LoadBalancer \"af830**********0013\" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.\n\tstatus code: 409, request id: 95074755-f146-4c35-8bd6-33b09ac2ba6b"
```
But we didn't change any istio settings. 

For now this not affect our cluster function, but I think these unnormal events should reported.

**Comment by howardjohn** [comment]
istio just sets `type: LoadBalancer`. How EKS choses to actuate that is out of our hands.

I would open this bug on EKS side. Thanks!
