### ISSUE TITLE
Multiple ingress/egress gateways, limiting which DestinationRules get examined by each gateway

### ISSUE THREAD

**Issue by jcmcken** [istio/istio#35224]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

If I have an ingress and an egress gateway, both gateways find DestinationRules in istio-system namespace for the other and attempt to load them, even though it usually doesn't make sense. In cases where an ingress DestinationRule points to the ingress gateway CA path, the egress gateway picks this up and errors (because egress gateway CA is at a different path, it can't find the file mentioned in the DestinationRule and errors).

It's also not ideal from a performance point of view that ingress/egress are examining DestinationRules that will never be used in the respective gateway.

So requesting some ability to use selectors to limit which DestinationRule a particular gateway is allowed to examine.

**Describe alternatives you've considered**

* Customize the Helm chart values, e.g. the volumes. This is brittle because it's an array, meaning I need to reproduce the entire array and then make my modification.
* Customize the Helm chart for ingress/egress gateway to use a common default CA path. This way it won't matter if the ingress or egress gateways look at DestinationRules for the others, since the file should exist in either case. Also not ideal, I don't want to fork the charts.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ewoks** [comment]
@jcmcken I wonder if you found sound better solution or approach for this.. 
// I see the ticket is closed as stale :/
