### ISSUE TITLE
Unable to Override HCM.delayed_close_timeout to 0

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#35239]
Istio uses `EnvoyFilter` API to patch and update arbitrary properties in HTTPConnectionManager and any other XDS objects. 

After introduction of  `PILOT_HTTP_DELAYED_CLOSE_TIMEOUT = 1s`  (in 1.11?)  it is not possible to set `HCM.delayed_close_timeout`  to `0`. Zero has a special meaning.  This is slightly different than `unsetting` the field.

```go
// .. WARNING::
//    A value of 0 will completely disable delayed close processing. When disabled, the downstream
//    connection's socket will be closed immediately after the write flush is completed or will
//    never close if the write flush does not complete.
DelayedCloseTimeout *duration.Duration `protobuf:"bytes,26,opt,name=delayed_close_timeout,json=delayedCloseTimeout,proto3" json:"delayed_close_timeout,omitempty"`
```

This happens because the innermost type `durationpb.Duration` is the following and `Seconds=0` does not have the desired effect for standard `proto.Merge` reasons.

```go
type Duration struct {
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
}
```

At present it is possible to change the `PILOT_HTTP_DELAYED_CLOSE_TIMEOUT=0s` if running own istiod.
When using a managed istiod / remote istiod this may not be available.
We either need to schematize these fields in the API or find some other solution.

**Comment by mandarjog** [comment]
cc @ramaraochavali for PILOT_HTTP_DELAYED_CLOSE_TIMEOUT.

**Comment by mandarjog** [comment]
A user before the introduction of PILOT_HTTP_DELAYED_CLOSE_TIMEOUT could set the value to anything using EnvoyFilter. They could set it to “0” which has a specific meaning. After introducing this field which moved the in-code default into config, it is no longer possible to set the value to zero using EnvoyFilter.
If you are using a remote istiod where you do not have control on env vars it represents a regression. Not only has behaviour has changed, but you cannot fix it unless you can set env vars on istiod.

**Comment by mandarjog** [comment]
Related to https://github.com/istio/istio/issues/29172

**Comment by ramaraochavali** [comment]
@mandarjog Sorry I did not realize the side affect of it. I do not have a great solution for this. so I think it better to remove that feature flag. https://github.com/istio/istio/pull/35268 and let people control it by Envoy filters.

**Comment by mandarjog** [comment]
@ramaraochavali Thanks for fixing it.
