### ISSUE TITLE
Pilot Agent wait for File Mounted Certificate to be loaded

### ISSUE THREAD

**Issue by virajrk** [istio/istio#35254]
Title - Pilot Agent wait for File Mounted Certificate to be loaded

**Describe the feature request**
In case of File Mounted Certificates are used, the istio-proxy should wait before marking itself ready. The pilot agent process can add a wait until file-mounted certificates are available.

This gets handled in the case of Kind: Deployment where container strategy is defined as a restart. (This is still not a good user experience if the restart strategy is not configured in the right way) But in the case of Kind: Job, there is no container restart strategy.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
It was observed after Istio 1.6, the pilot agent is not waiting for file mounted certificate to be available before starting the envoy process. Verified the same behavior with Istio 1.8. Verified code in the current master, it is not waiting for cert to be available. 

This affects Kind: Job because there is no container restart policy present. But in the case of Kind: Deployment it is taken care of by restart policy.

Feel free to let me if there are any workaround. Also, open to contributing back.

**Comment by virajrk** [comment]
CC : @aattuluri

**Comment by ramaraochavali** [comment]
> In case of File Mounted Certificates are used, the istio-proxy should wait before marking itself ready

Is n't the case already? If the certificate is used in cluster - the cluster stays in warming state ?

**Comment by virajrk** [comment]
Hello @ramaraochavali,
We observed specific envoy proxy is not waiting for a certificate when using a file mount certificate. We observed istio-proxy doesn't wait for certs and crashes. For kind job, there is no restart policy present. 

I found this code - https://github.com/istio/istio/blob/master/security/pkg/nodeagent/sds/server.go#L46 before SDS starts it doesn't wait for files to be available. 

Please let me know if I am missing anything.

**Comment by ramaraochavali** [comment]
> We observed specific envoy proxy is not waiting for a certificate when using a file mount certificate. We observed istio-proxy doesn't wait for certs and crashes. For kind job, there is no restart policy present.

Can you please share logs?

**Comment by kpharasi** [comment]
@ramaraochavali We see the istio-proxy container restart multiple times till the file mounted certificates are available. 

Related logs:
```
error	failed to start xds proxy: failed to build TLS dial option to talk to upstream: open /etc/certs/root-cert.pem: no such file or directory
Error: failed to start xds proxy: failed to build TLS dial option to talk to upstream: open /etc/certs/root-cert.pem: no such file or directory
```

Currently we have forked the repo and added a logic to wait for the certificates to be available before the process is started. This has been working fine for us.

Kindly let us know if there is any better way to solve this. Also, if the solution sounds good we are open to contributing back. Thanks in advance!

cc: @nirvanagit

**Comment by kpharasi** [comment]
@ramaraochavali We have another sidecar in our workload pods which is responsible for managing the lifecycle of the certificates. In this scenario it may take some time for it to fetch the initial certificates resulting in the container restarts for Istio proxy. The custom logic to wait for the certificates has helped us here. Also, we went with this approach as we wanted to avoid adding an init container for this purpose.

Let me know if I can answer any other questions.

**Comment by ramaraochavali** [comment]
> Also, we went with this approach as we wanted to avoid adding an init container for this purpose.

Any reason why you want to avoid init container? We do have a similar situation but we solve it by init container. Many people use that because there is no preStart hook https://github.com/kubernetes/kubernetes/issues/140

Another option is to ensure your container that writes certs runs before istio-proxy container if possible.

**Comment by ramaraochavali** [comment]
If none of the above solutions work for you, I think it is OK to [have this ](https://github.com/istio/istio/blob/master/pkg/istio-agent/xds_proxy.go#L720) retry with backoff and exist after a time.

**Comment by kpharasi** [comment]
Thanks a lot! Will look into the suggestions provided.
