### ISSUE TITLE
Upgrading weak hashes in Istio Code Base 

### ISSUE THREAD

**Issue by rakrup** [istio/istio#35250]
This issue is based on the NCC's Security Report here : https://istio.io/latest/blog/2021/ncc-security-assessment/NCC_Group_Google_GOIST2005_Report_2020-08-06_v1.1.pdf

Under Identifier : NCC-GOIST2005-009 - Weak Hash Used for Integrity

The latest istio codebase has one file remaining which has usage of weak hash. Others have been removed in last few months
[istio/istio/galley/pkg/config/source/kube/inmemory/kubesource.go#20](url) 

Should the hash be upgraded to SHA-256 or SHA3 as recommended ?

**Comment by howardjohn** [comment]
The code is not used by anything important where a hash collision would matter at all. Its for a debug tool

**Comment by howardjohn** [comment]
This code is no longer in the codebase
