### ISSUE TITLE
Refactor istio queue

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#35269]
Currently, istio queue allows use push a task handler when a config updated, and the queue is run as a daemon thread.

If one task handler executes fails, then it will be retried with a fixed delay.

This could cause severe bug,  let's say

1. t0:  enqueue a task handler, which handles an objectXX with v0
2. t1: enqueue a task handler, which handles an objectXX with v1

The queue does not know the two handlers will handle the same object. So if 

3. t3:  execute on v0 objectXX  failed, it will retry later
4. t4:  execute on v1 objectXX succeeds
5. t5:  retry handling v0 objectXX , then it will violate eventual consistence

**Comment by hzxuzhonghu** [comment]
cc @howardjohn @ramaraochavali

**Comment by hzxuzhonghu** [comment]
There are some resource handler does not obey eventual consistent principle. Like

- [ ] Ingress controller https://github.com/istio/istio/pull/35342
- [ ] WorkloadEntry handler
- [ ] ServiceEntry handler

**Comment by howardjohn** [comment]
Looking at all queue usages:

ingress: sync error, real user errors
crd: sync error
WE: no errors
kube: only for pod tombstone issues (other tombstone ones do not return error..)
discoverycontroller: no errors
namespace controller: YES. on k8s downtime, invalid config, etc.
webhook patch: YES, on k8s down time, etc

It seems the top priority are ns controller and webhook patch
