### ISSUE TITLE
Provide better back pressure for XDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35263]
![2021-17-09_15-41-01](https://user-images.githubusercontent.com/623453/133860847-4b6522e7-45de-44e0-b0b1-e2f88d419bd0.png)

Above shows connecting 5k proxies and some configs.

What happens is we all start generating CDS for all of them. This means we are holding 5k XDS requests (the big one! because the first has the node and is giant as a result) and in-flight CDS configs.

Because we are trying to generate 5k CDS at once, our CPU grinds to a halt due to throttling. Some responses take *3 minutes* to complete.

Clearly we are better off not allowing so many concurrently...

**Comment by howardjohn** [comment]
Same test with `set env deployment/istiod PILOT_PUSH_THROTTLE=25 PILOT_MAX_REQUESTS_PER_SECOND=25`
![2021-17-09_15-57-04](https://user-images.githubusercontent.com/623453/133862258-edf7f2fb-bbb1-4bd0-aa34-3895c0699abe.png)

And with only `PILOT_MAX_REQUESTS_PER_SECOND=25` (throttle at default of 100):
![2021-17-09_16-04-04](https://user-images.githubusercontent.com/623453/133862251-01ba9b69-989b-49f5-adf2-a61e149dda95.png)

IMO we should drop the default PILOT_MAX_REQUESTS_PER_SECOND. Currently its 100.

**Comment by hzxuzhonghu** [comment]
>IMO we should drop the default PILOT_MAX_REQUESTS_PER_SECOND. Currently its 100.

You mean `PILOT_PUSH_THROTTLE`?

**Comment by howardjohn** [comment]
No there are 2 vars. See https://github.com/istio/istio/issues/35263#issuecomment-922125529. The rate limit alone is enough to prevent this in my tests

**Comment by hzxuzhonghu** [comment]
I remember `PILOT_MAX_REQUESTS_PER_SECOND` was recently added because when a huge number of connections will break down pilot

**Comment by hzxuzhonghu** [comment]
So this is a new finding?

**Comment by howardjohn** [comment]
Yes we recently add the env var but set it to 100rps. IMO this is too high
and we should drop it to 25, since from the tests above 100 wasn't
sufficient to prevent overload.

In our product we are already using 25, it's working great for us.

**Comment by hzxuzhonghu** [comment]
This is interesting, 25rps works best.

**Comment by ramaraochavali** [comment]
+1 to changing the default to 25 rps

**Comment by taitelman** [comment]
so now when I use Istio 1.13.2 I get many of these
```
xdsproxy	upstream [someNumber] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
```
every hour or so we see thousands of that warning.

```
$ istioctl version
client version: 1.9.0
control plane version: 1.13.2
data plane version: 1.13.2 (2559 proxies)
```

**Comment by howardjohn** [comment]
Do you have all 2500 proxies trying to connect to 1 istiod instance at once...?

**Comment by hzxuzhonghu** [comment]
What is your istio model, proxies and istiod resides in same or different clusters?  How many proxies do you have? And how many istiod?

**Comment by taitelman** [comment]
sorry for the delay... its been my weekend off.
so: first we have 6-9 istiod running on node pool A. Then we have the "dataplane" nodes on node pool B. but both pools are in the same K8s cluster.
the dataplane contains:
4283 K8s services
856 VirtualServices
10070 pods.
2 Istio Gateways
3 side cars (namespace isolation - to reduce traffic + security)
9 AuthorizationPolicy
93 DestinationRules
9 SE

**Comment by senior88oqz** [comment]
we're seeing similar error message in the `istio-proxy`, this can be trigger when restarting istiod pods (`kubectl rollout restart deployment istiod`)
```
upstream [5] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF
upstream [5] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
```
we're running istiod in the same cluster, having approx 1500 proxies and 10 istiod pods

**Comment by hzxuzhonghu** [comment]
This is expected, when rolling update, istiod will be down and recreated, so the proxies connect to it will reconnect to another istiod. 

The limit should be overcome after retry, right?

**Comment by senior88oqz** [comment]
> This is expected, when rolling update, istiod will be down and recreated, so the proxies connect to it will reconnect to another istiod.

thanks @hzxuzhonghu, this would make sense, but why increasing `PILOT_MAX_REQUESTS_PER_SECOND` back to 100 eliminate the error message above? also if this is expected, should the log message `upstream [5] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF` at a lower level (currently its log level is `ERROR`)

**Comment by hzxuzhonghu** [comment]
I think it is related to rolling update policy of k8s, kind of remember that can be configured, how many pods can be unavailable during update, not quite sure now.

Increasing the  PILOT_MAX_REQUESTS_PER_SECOND  value definitely help

**Comment by senior88oqz** [comment]
> I think it is related to rolling update policy of k8s, kind of remember that can be configured, how many pods can be unavailable during update, not quite sure now.

I actually tried a rolling update strategy with 100% Surge and 25%/1 Unavailable, both produce the errors

**Comment by hzxuzhonghu** [comment]
According to this, there may be 300 proxies trying to reconnect to 8 istiod at the same time, 300/8 > 25, so it is easily to reproduce ratelimted.

**Comment by howardjohn** [comment]
Getting rate limited is not an error. Its expected behavior is to protect
the server against spiky loads. Note that almost every time you run
`kubectl` you are also getting rate limited.

**Comment by senior88oqz** [comment]
> Getting rate limited is not an error. Its expected behavior is to protect
the server against spiky loads

Agreed, and the below log line about the rate limit is at `warn` level and make sense
```
2022-08-23T14:22:55.256206Z	warn	xdsproxy	upstream [187] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
```

But it also produce the `send error for type url xxxx EOF`, which is a bit confusing given the sidecar is logging it as "error", restarting istiod just exaggerate this, this log line shows up from time to time as "error" to the user 😅 
```
2022-08-23T14:22:55.256420Z	error	xdsproxy	upstream [187] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF
```

**Comment by AkaiNoCat** [comment]
> [pilot: autoscale concurrency and rate limit on xds #48438 ](/istio/istio/pull/48438)

We have also recently discovered a lot of `2,EOF` errors, and the terminated metrics record is canceled. Before the `2,EOF` error, there were a large number of 503+"UF,URX" error requests, many service requests were sent to The IP address of the closed pod， is very strange, as if the proxy has not updated the endpoint.Have you encountered this problem, looking forward to your reply!

**Comment by AkaiNoCat** [comment]
> > Getting rate limited is not an error. Its expected behavior is to protect
> > the server against spiky loads
> 
> Agreed, and the below log line about the rate limit is at `warn` level and make sense
> 
> ```
> 2022-08-23T14:22:55.256206Z	warn	xdsproxy	upstream [187] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
> ```
> 
> But it also produce the `send error for type url xxxx EOF`, which is a bit confusing given the sidecar is logging it as "error", restarting istiod just exaggerate this, this log line shows up from time to time as "error" to the user 😅
> 
> ```
> 2022-08-23T14:22:55.256420Z	error	xdsproxy	upstream [187] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF
> ```

We have also recently discovered a lot of 2,EOF errors, and the terminated metrics record is canceled. Before the 2,EOF error, there were a large number of 503+"UF,URX" error requests, many service requests were sent to The IP address of the closed pod， is very strange, as if the proxy has not updated the endpoint.Have you encountered this problem, looking forward to your reply!
