### ISSUE TITLE
Getting Started on MacOS w/ Docker Desktop w/ Kind does not work

### ISSUE THREAD

**Issue by jonassteinberg1** [istio/istio#35278]
### Bug Description

Following [these](https://istio.io/latest/docs/setup/getting-started/) instructions.

latest kind
latest istio
everything works beautifully until I attempt to verify external access as the doc suggests.  At that point I get a "refused to connect" from my browser.  curl obviously shows the same.

MacOS: 10.15.7
Kind: 0.11.1 (latest)
Istio: 1.11.2

I am not on a VPN.
I have no proxies running.
I have no firewalls on.

### Version

```prose
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (8 proxies)

# kubectl
Client Version: v1.21.3
Server Version: v1.21.1
```

### Additional Information

```
❯ istioctl install --set profile=demo -y
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Installation complete
Thank you for installing Istio 1.11.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/kWULBRjUv7hHci7T6
❯ kubectl port-forward svc/istio-ingressgateway 8080:80 -n istio-system

❯ export PATH=$PWD/bin:$PATH

❯ istioctl install --set profile=demo -y
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Installation complete
Thank you for installing Istio 1.11.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/kWULBRjUv7hHci7T6

❯ kubectl label namespace default istio-injection=enabled
namespace/default labeled

❯ kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
service/details created
serviceaccount/bookinfo-details created
deployment.apps/details-v1 created
service/ratings created
serviceaccount/bookinfo-ratings created
deployment.apps/ratings-v1 created
service/reviews created
serviceaccount/bookinfo-reviews created
deployment.apps/reviews-v1 created
deployment.apps/reviews-v2 created
deployment.apps/reviews-v3 created
service/productpage created
serviceaccount/bookinfo-productpage created
deployment.apps/productpage-v1 created

# all services are up
❯ kubectl get services
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   10.96.206.34    <none>        9080/TCP   2m10s
kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP    18m
productpage   ClusterIP   10.96.145.255   <none>        9080/TCP   2m10s
ratings       ClusterIP   10.96.212.151   <none>        9080/TCP   2m10s
reviews       ClusterIP   10.96.255.13    <none>        9080/TCP   2m10s

# all pods seem good
k get po -A
NAMESPACE            NAME                                                  READY   STATUS    RESTARTS   AGE
default              details-v1-79f774bdb9-g6gjg                           2/2     Running   0          88s
default              productpage-v1-6b746f74dc-wl9bf                       2/2     Running   0          88s
default              ratings-v1-b6994bb9-xqchb                             2/2     Running   0          88s
default              reviews-v1-545db77b95-6cq86                           2/2     Running   0          88s
default              reviews-v2-7bf8c9648f-xfkhx                           2/2     Running   0          87s
default              reviews-v3-84779c7bbc-sm8f6                           2/2     Running   0          88s
istio-system         istio-egressgateway-6cb7bdc7fb-q9gzg                  1/1     Running   0          13m
istio-system         istio-ingressgateway-694d8d7656-9l5fr                 1/1     Running   0          13m
istio-system         istiod-6c68579c55-mldj7                               1/1     Running   0          13m
kube-system          coredns-558bd4d5db-6fjhp                              1/1     Running   0          17m
kube-system          coredns-558bd4d5db-h7vj7                              1/1     Running   0          17m
kube-system          etcd-istio-testing-control-plane                      1/1     Running   0          17m
kube-system          kindnet-2fpfk                                         1/1     Running   0          17m
kube-system          kube-apiserver-istio-testing-control-plane            1/1     Running   0          17m
kube-system          kube-controller-manager-istio-testing-control-plane   1/1     Running   0          17m
kube-system          kube-proxy-zrsdk                                      1/1     Running   0          17m
kube-system          kube-scheduler-istio-testing-control-plane            1/1     Running   0          17m
local-path-storage   local-path-provisioner-547f784dff-txkw7               1/1     Running   0          17m

# initial curl looks good
❯ kubectl exec "$(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')" -c ratings -- curl -sS productpage:9080/productpage | grep -o "<title>.*</title>"
<title>Simple Bookstore App</title>

❯ kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
gateway.networking.istio.io/bookinfo-gateway created
virtualservice.networking.istio.io/bookinfo created

istioctl analyze

✔ No validation issues found when analyzing namespace: default.

❯ kubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.96.211.245   <pending>     15021:30077/TCP,80:32615/TCP,443:30506/TCP,31400:31402/TCP,15443:30087/TCP   17m

# build the URL with correct env vars
❯ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')

❯ export INGRESS_HOST=127.0.0.1

❯ export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

❯ echo "$GATEWAY_URL"
127.0.0.1:32615

❯ echo "http://$GATEWAY_URL/productpage"
http://127.0.0.1:32615/productpage

# curl page
❯ curl -v http://127.0.0.1:32615/productpage
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 32615 failed: Connection refused
* Failed to connect to 127.0.0.1 port 32615: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 32615: Connection refused
```

**Comment by ericvn** [comment]
You probably need to setup networking between the host and your cluster. MetalLB can be used. There are several blogs/articles that discuss getting this to work.

**Comment by jonassteinberg1** [comment]
@ericvn why would I need to do that?  my host is my laptop which is running docker desktop, my cluster is kind.  for the past several years this has been a virtually fool-proof sandbox for istio bookinfo-type stuff.  I'm grateful for the advice, but in any event if there is an istio with the core installation process of bookinfo on macos running kind it needs to be fixed or at least tracked as that is not a small segment of the istio tester's population.  all this could be my fault, but I'm on my third fresh install attempt so...

**Comment by ericvn** [comment]
@jonassteinberg1 I don't think it's your fault. I think it's the way kind works on the MacOS. There are lots of articles that talk about how to get access to the kind cluster from the MacOS command line. Maybe someone can incorporate something into the docs to help MacOS users with kind.

**Comment by jonassteinberg1** [comment]
@ericvn one can gain access to the kind cluster from terminal on mac simply by using docker exec.  not sure if that's what you mean.  whatever the case: all of this used to and should work.  hopefully someone can try and reproduce this on macos is all.

**Comment by ericvn** [comment]
Docker exec and then curling a service does work fine for me on MacOS with kind. The problem is trying to access the cluster from the MacOS command line as your curl shows above. I'm spending a few minutes to see if I can get working what used to work for me. MetalLB has been updated substantially so my old instructions don't work anymore.

**Comment by BenTheElder** [comment]
Docker desktop does not setup networking such that containers are reachable from the host, you can only do so with port forwards. In order to port forward to the kind nodes you need to configure this so kind knows what ports you wish to forward.

Between this and loadbalancer being optional / having no standard implementation a result we don't currently ship one out of the box with kind. You can find docs for setting up a loadbalancer specifically in kind at https://kind.sigs.k8s.io/docs/user/loadbalancer/

To map ports from the host try extraPortMappings which can then be used with e.g. a nodeport or ingress, we have some discussion of that at https://kind.sigs.k8s.io/docs/user/ingress/

via https://kubernetes.slack.com/archives/CEKK1KTN2/p1632170491126900

**Comment by ericvn** [comment]
On MacOs BigSur, Docker Desktop 4.01, and Minikube 1.23.1 (I know things worked in the past on the then current versions, but things have changed):

Using the k8s cluster within Docker Desktop, I was successful curling the application.

I was unsuccessful in getting the curl to work from the host to the BookInfo app using kind. More research needed based on Ben's comments.

I was partially successful in getting the curl to work with Minikube and the Docker driver. I needed to run `minikube service --url istio-ingressgateway` which yielded 5 open ports. Knowing port 80 was the second of the ports listed on the `get service` I used the second Minikube listed port and I was able to open in a browser and see the app. I run a VPN for work so trying to start Minikube with the hyperkit driver failed.

**Comment by jonassteinberg1** [comment]
can confirm docker desktop works without issue.  was up and running in minutes w/ current instructions and bookinfo demo.

**Comment by gamerson** [comment]
> Has anyone gotten Kind + Istio + Mac working? All the guides seem to be out of date, and the official Istio documentation doesn't work for this scenario.

I have tried everything on this issue and in the linked slack thread and have not successfully reached a pod from the host with MacOS + Docker Desktop + Istio with no success yet.

**Comment by ericvn** [comment]
I haven't had this working in a while, although I did using MetalLB in the past. Normally, I just use the Kubernetes option in Docker Desktop or Minikube.

**Comment by codehepta** [comment]
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
worked for me. The port will be 80. 
The url will be something like :
http://localhost/productpage 
Both localhost and 127.0.0.1 is working

Docker Desktop version: 4.21.1 , ISTIO_VERSION=1.18.2
