### ISSUE TITLE
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

### ISSUE THREAD

**Issue by lucasponce** [istio/istio#35277]
When trying to use istio.io/client-go in combination with jaegerproject to access both APIs it gets a panic related grpc and protobuf.

A reproducer can be find here:

https://github.com/lucasponce/lucas-demos/blob/main/go.mod

This blocks projects like Kiali that needs to access both APIs to combine signals.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/26751 would fix it for sure I think.

**Comment by zackzhangkai** [comment]
+1
