### ISSUE TITLE
Merge istio-proxy with the CNI

### ISSUE THREAD

**Issue by RichardoC** [istio/istio#35276]
**Describe the feature request**

Rather than running one istio-proxy container per pod, there should be one istio-proxy running per node as part of the CNI. This would reduce resource requirements and pod start up time in high pod packing scenarios (high number of pods per node.)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is something we have been looking into (https://docs.google.com/document/d/1q1FWaPjW8ko9Eh2m-7DO5wbQTCy6neF8Gl_1r0IoxnQ/edit?resourcekey=0-IJdySFDjGIayhbwLs1bfuA#heading=h.59yzvkytumxu), but I want to be clear that this is a massive re-architecture that will take a very long time to ship if we do go down this path.

**Comment by bianpengyuan** [comment]
https://github.com/istio/istio/issues/11366 is the same FR which has bunch of history.

**Comment by RichardoC** [comment]
> This is something we have been looking into (https://docs.google.com/document/d/1q1FWaPjW8ko9Eh2m-7DO5wbQTCy6neF8Gl_1r0IoxnQ/edit?resourcekey=0-IJdySFDjGIayhbwLs1bfuA#heading=h.59yzvkytumxu), but I want to be clear that this is a massive re-architecture that will take a very long time to ship if we do go down this path.

Is it intention that this document is private? Glad to hear there are discussions ongoing!

**Comment by RichardoC** [comment]
Can we please remove the lifecycle/stale label? It'll be great to see this actually happen!

**Comment by howardjohn** [comment]
This is https://istio.io/latest/blog/2022/introducing-ambient-mesh/
