### ISSUE TITLE
openCensusAgent does not work with mTLS

### ISSUE THREAD

**Issue by SubhadeepSen** [istio/istio#35274]
### Bug Description

Hi,
I have been trying to configure envoy proxy to use opencensus agent for tracing. Cluster wide mTLS has been enabled and OpenTelemetry collector has been deployed as a service to collector the telemetry data. **The opencensus agent does not work with mTLS and I see the following error message.**

**info	envoy tracing	instantiating a new tracer: envoy.tracers.opencensus
OcAgent trace exporter: Export() failed: UNAVAILABLE: Connection reset by peer**

**It works perfectly when I disable mTLS for port 55678 using PeerAuthentication in the collector namespace where OpenTelemetry collector has been deployed.**

I'm not sure if this is not supported or I'm missing any configuration. Could some please help me with right configuration if my configuration is incorrect.

### meshConfig is configured with below configuration:

```tracing:
  sampling: 100
  openCensusAgent:
    address: collector-service.collector:55678
  tlsSettings:
    mode: ISTIO_MUTUAL
```

### Version

```prose
istio v1.8.6
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by verysonglaa** [comment]
Hi @SubhadeepSen it works for me with istio 1.10.3 and mTLS enabled. Here is a snipped of the config:
----
    meshConfig:
      defaultConfig:
        tracing:
          openCensusAgent:
            address: otel-collector.otel-system.svc.cluster.local:55678
[...]
    values:
      global:
        proxy:
          tracer: openCensusAgent
---

In the namespace otel-system I have opentelemetry-collector in a recent version running together with its sidecar.

You might want to upgrade to 1.10 or 1.11 and use this settings instead of troubleshooting 1.8

**Comment by m-mijatovic** [comment]
@SubhadeepSen have you managed to solve your issue as I am looking in setting up the same setup?
