### ISSUE TITLE
istioctl install - Not working on Linux arm64

### ISSUE THREAD

**Issue by rahgadda** [istio/istio#35275]
### Bug Description

Tried to install Istio on Arm64 but getting an error while creating istiod pod

Getting error in istiod pod
standard_init_linux.go:228: exec user process caused: exec format error

### Version

```prose
[root@K8-Master istio-1.11.2]# istioctl version
no running Istio pods in "istio-system"
1.11.2

[root@K8-Master istio-1.11.2]# kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.1
```

### Additional Information

Installation Steps:
-------------------
Step 1:
=====
`curl -L https://istio.io/downloadIstio | sh -`

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   102  100   102    0     0     77      0  0:00:01  0:00:01 --:--:--    77
100  4549  100  4549    0     0   2809      0  0:00:01  0:00:01 --:--:-- 16188

Downloading istio-1.11.2 from https://github.com/istio/istio/releases/download/1.11.2/istio-1.11.2-linux-arm64.tar.gz ...

Istio 1.11.2 Download Complete!

Step 2:
=====
`cd  istio*`
`export PATH="$PATH:/home/opc/Istio/istio-1.11.2/bin"`

Step 3:
=====
`istioctl x precheck`
✔ No issues found when checking the cluster. Istio is safe to install or upgrade!
  To get started, check out https://istio.io/latest/docs/setup/getting-started/

Step 4:
=====
`istioctl install --manifests https://github.com/istio/istio/releases/download/1.11.1/istio-1.11.1-linux-arm64.tar.gz`
This will install the Istio 1.11.2 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) `Y`

- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod                                                        
✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition      
  Deployment/istio-system/istiod (container failed to start: CrashLoopBackOff: back-off 2m40s restarting failed container=discovery pod=istiod-6d9c4fdd6b-cv7xl_istio-system(3b740cb4-0674-4669-b2b8-42ea23bae896))                           
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
  
- Pruning removed resources                                                                                                          Error: failed to install manifests: errors occurred during operation

Step 5:
=====
`kubectl get pods -n istio-system`
NAME                      READY   STATUS             RESTARTS      AGE
istiod-6d9c4fdd6b-cv7xl   0/1     CrashLoopBackOff   2 (15s ago)   30s

Step 6:
=====
`kubectl logs istiod-6d9c4fdd6b-cv7xl -n istio-system` 
standard_init_linux.go:228: exec user process caused: exec format error

Step 7:
====
`kubectl -n istio-system get all`
NAME                                        READY   STATUS             RESTARTS       AGE
pod/istio-ingressgateway-5d76fcbfc9-q94gm   0/1     Pending            0              7s
pod/istiod-6d9c4fdd6b-cv7xl                 0/1     CrashLoopBackOff   5 (2m3s ago)   5m7s

NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
service/istio-ingressgateway   LoadBalancer   10.100.38.128   <pending>     15021:30356/TCP,80:31477/TCP,443:31246/TCP   7s
service/istiod                 ClusterIP      10.103.53.225   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        5m7s

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istio-ingressgateway   0/1     1            0           7s
deployment.apps/istiod                 0/1     1            0           5m7s

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/istio-ingressgateway-5d76fcbfc9   1         1         0       7s
replicaset.apps/istiod-6d9c4fdd6b                 1         1         0       5m7s

NAME                                                       REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         5         0          7s
horizontalpodautoscaler.autoscaling/istiod                 Deployment/istiod                 <unknown>/80%   1         5         1          5m7s

**Comment by howardjohn** [comment]
ARM is not supported. Only the CLI client (istioctl) has ARM builds, not the server-side. Follow https://github.com/istio/istio/issues/21094 for tracking, we are working on this. Thanks!
