### ISSUE TITLE
k8s cilium cni: outbound request connection's ip is pod ip, not svc ip.

### ISSUE THREAD

**Issue by zhengzepeng** [istio/istio#35307]
I change my k8s cni to cilium, and i found envoy can accept the request, but the request(outbound) connection's ip is the **real pod ip, not service ip (beacuse of the ebpf)**. It means it maybe can not find the true listener to handle. 

Any possible to adapt this situtation? Maybe cilium is a good choose.

**Comment by bianpengyuan** [comment]
Looks like a dup of https://github.com/istio/istio/issues/27619.

**Comment by howardjohn** [comment]
Closing as dupe of https://github.com/istio/istio/issues/27619
