### ISSUE TITLE
`no healthy upstream` when simultaneously creating Service+Ingress

### ISSUE THREAD

**Issue by clementnuss** [istio/istio#35309]
### Bug Description

I am currently testing/comparing a series of Ingress Controllers, and for that matter am testing the behaviour of the controllers in dynamic Ingress/Service environments.

A test round unfolds as follows: a bash script automatically creates 50 Services+Ingresses, runs a series of `k6` load tests while there is no change made to the Ingress definitions and then another series of `k6` tests while randomly modifying the ingresses (shuffling backends, deleting/re-creating). Finally, the script deletes the namespace containing the test deployment (and therefore the services and the ingresses)

If I run the same test round / bash script directly afterwards, I get a lot of `no healthy upstream` response from Istio. Instead of 100% of 200/OK HTTP answers, I get ~40% of 503/No healthy upstream responses. The only solution then is to kill `istiod` and ìstio-ingressgateway`, then everything is perfectly fine again ! 

I think this issue is related to #35172 and #35293 , and I have observed that when I create my Services, `sleep 1`, and then create the Ingresses, I do not get the issue I just described and Istio is working perfectly fine, even after several creation/tests/deletions rounds

### Version

```prose
❯ istio-1.11.2/bin/istioctl --istioNamespace kube-istio version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (5 proxies)
❯ kubectl version --short
Client Version: v1.22.2
Server Version: v1.21.4
```

**Comment by ramaraochavali** [comment]
This seems to be the same issue as https://github.com/istio/istio/pull/35293. Sorry for the regression. This https://github.com/istio/istio/pull/35298 fixes it for 1.11
