### ISSUE TITLE
0.5.1 mixer memory leak under certain conditions

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3531]
@alexkoturanov commented on [Thu Feb 15 2018](https://github.com/istio/issues/issues/210)

**Is this a BUG or FEATURE REQUEST?:**
BUG

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl 0.5.1
kubectl 1.9.3
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
No - used istio.yaml

**What happened**:
increasing memory usage for mixer (in GB) under load
![screenshot-koturano-02-15-18-at-11 33-am](https://user-images.githubusercontent.com/36204901/36277998-50747974-1247-11e8-85fc-10beacc8680c.PNG)

I have one mixer pod that is taking reports from 9 ingresses and 9 sidecar proxies.

Surprisingly, the problem went away after restaring the load test a couple of times.

See the attached screenshot - memory usage is ok and there is no report drops for the same load (3k req/sec)
![screenshot-koturano-02-15-18-at-11 46-am](https://user-images.githubusercontent.com/36204901/36278238-16693f16-1248-11e8-8ee2-895f560d7339.PNG)
![screenshot-koturano-02-15-18-at-11 50-am](https://user-images.githubusercontent.com/36204901/36278242-18677c38-1248-11e8-88ec-99a62aec5310.PNG)

**What you expected to happen:**
Mixer memory is stable

**How to reproduce it:**
the issue seems to be intermittent, see my description and screenshots at:
https://groups.google.com/forum/#!topic/istio-users/0er0BegsKvQ%5B1-25%5D

**Feature Request:**
N

**Describe the feature:**
n/a

---

@mandarjog commented on [Thu Feb 15 2018](https://github.com/istio/issues/issues/210#issuecomment-366047728)

note: @ldemailly @jnativio

**Comment by mandarjog** [comment]
@alexkoturanov I moved it to istio repo, thanks.

**Comment by mandarjog** [comment]
@douglas-reid @ldemailly @jnativio

**Comment by ldemailly** [comment]
subscribe

**Comment by mandarjog** [comment]
This is fixed in 0.6 release.

The issue was a stray log statement left on the request path coupled with the new logging library.
The logging library contends on a lock and most of the worker go routines are blocked trying to log this `info` statement.
The front end grpc server continued accept new work including report data. This caused the number of go routines to grow, each holding on to all its data.
