### ISSUE TITLE
Adapt max_requests_per_connection for downstream connections

### ISSUE THREAD

**Issue by sha-rath** [istio/istio#35326]
**Describe the feature request**

Envoyproxy in their upcoming version 1.20.0 will be adding a new feature called [_max_requests_per_connection_ for downstream connections](https://github.com/envoyproxy/envoy/pull/14936). Currently, they have this configurable only for upstream connections and is available under the [Cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html?highlight=max_requests_per_connection) configuration. In the upcoming version, it will be moved under [HttpProtocolOptions](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-max-requests-per-connection), where maximum requests for both upstream and downstream connections can be set. 

The feature request here is to adapt this into Istio and expose the new functionality as a configurable option to the user. If the implementation is not so complicated, it would be great to have this in the next release of Istio i.e 1.12.

**Describe alternatives you've considered**

The alternate is to use EnvoyFilter to get this configuration on the proxy, but I prefer to avoid this for its complexity and maintenance overhead.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
It would be good to understand what the use cases for this are and how they are expected to be used. The implementation is trivial but picking the API design doesn't seem straightforward.

**Comment by sha-rath** [comment]
@howardjohn The main use case for us is rebalancing of long-lived connections from an external load balancer during scale-out/scale-in of the ingress gateway pods. In other words, to [force the load balancers to periodically reopen requests to speed up the convergence to uniform load distribution](https://github.com/envoyproxy/envoy/issues/14531#issue-775800531).

**Case 1:** Assume the downstream connections are initially balanced between 2 ingress gw pods on 2 different worker nodes. In case one of the worker nodes crash, all the downstream connections will be handled by the ingress gw pod on the other worker node. At a certain point, based on the number of requests per connection, we would like to close that connection and open a new connection towards the ingress gw pod that would have successfully rebooted by now. Otherwise, this rebooted ingress gw pod would remain unused.

**Case 2:** Similarly, when a new instance of the ingress gw pod is added. A connection to this new pod can be quickly
opened, when the connection on older pod is closed due to the limit on max requests per downstream connection.

**Comment by sha-rath** [comment]
I hope my explanation was clear. I'm not sure about picking the API design, but overall I felt this would be a good configurable
option to have from Istio. Are you aware of any alternates that would satisfy this requirement?

**Comment by howardjohn** [comment]
EnvoyFitlter is likely the best option in the short term at least. Right now we don't have a good API to configure HCM fields so it may be tricky API design. cc @mandarjog

**Comment by sha-rath** [comment]
Found this PR #35030 which should satisfy this request.

**Comment by sha-rath** [comment]
Ah, right..the changes are only on the cluster and not on the listener side. So, to handle downstream connections I will have to go with the EnvoyFilter approach for now. Thanks for the clarification @ramaraochavali
