### ISSUE TITLE
[QUESTION]: will pilot support hds?

### ISSUE THREAD

**Issue by jjy96** [istio/istio#35325]

**Comment by ramaraochavali** [comment]
Can you add more details? What is hds?

**Comment by jjy96** [comment]
https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/health/v3/hds.proto

healthy check

**Comment by ramaraochavali** [comment]
No. There are no plans to implement it AfAIK

**Comment by jjy96** [comment]
can i know why? have no use for or other reasons?

**Comment by ramaraochavali** [comment]
There are other ways to enable active health checks other than HDS. There is an open issue for it https://github.com/istio/istio/issues/10537 already

**Comment by jjy96** [comment]
thank you very much
