### ISSUE TITLE
External istio control plane support only one remote cluster

### ISSUE THREAD

**Issue by morvencao** [istio/istio#35367]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Current only one remote cluster can be supported for istio external control plane, if you see the configuration from https://istio.io/latest/docs/setup/install/external-controlplane/, you will find that `CLUSTER_ID` is specified to the name of remote cluster when install istio control plane in `external` cluster, and the cluster is actually the primary cluster. That's why only one remote cluster is supported.

However, Istio end-users are more interested with multiple remote clusters, and all the istio apps and configurations can be managed be one external control plane.

**Describe alternatives you've considered**

I tried with primary-remote mode, and it can be working for multiple remote clusters, but still no exactly like the external control plane mode.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ X ] Multi Cluster
[ ] Virtual Machine
[ X ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Watching configuration from multiple clusters is not and has never been supported In Istio multicluster. Just reading endpoints and services

**Comment by frankbu** [comment]
Although there can only be one config cluster, you can add any number of remote clusters to an external control plane. This is documented in the setup instructions here: https://istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters

**Comment by morvencao** [comment]
thanks @frankbu

**Comment by suwliang3** [comment]
@frankbu @morvencao I add another cluster to an external control plane， but it doesn't work as mentioned in [https://github.com/istio/istio/issues/39943](url).
