### ISSUE TITLE
1.11 CNI requires /var/run/istio-cni in PodSecurityPolicy.allowlist

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#35387]
1. Document this in "before you upgrade section" https://istio.io/latest/news/releases/1.11.x/announcing-1.11/upgrade-notes/
2. Consider adding to `istioctl preflight` checks. Otherwise installation will fail.

Upgrade produces the following error

```
Error creating: pods "istio-cni-node-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[2].hostPath.pathPrefix: Invalid value: "/var/run/istio-cni":
```

**Comment by mandarjog** [comment]
@bianpengyuan in addition the doc change, can we also make this optional and then back port it in 1.11 ?

1. Internally, if the daemonset does not see the path, it should gracefully opt-out.
2. Add an install option to add this mount.

Since CNI just graduated to beta in 1.11, we could argue that compatibility is not needed. however it is an immediate hard failure on upgrade.

@smawson @louiscryan  wdyt

**Comment by bianpengyuan** [comment]
Yeah I can add the option. We already have the option at DaemonSet to gracefully opt out usage of this volume, we will only need to introduce an install option to remove the volume and set that option.
