### ISSUE TITLE
Telemetry API not documented

### ISSUE THREAD

**Issue by dansiviter** [istio/istio#35381]
**Describe the feature request**
The Telemetry API, [although there are examples](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/telemetry-api/), is not documented in the Reference section. I'm trying to figure out how to filter noise from the traces.

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by dansiviter** [comment]
Oh, looks like it's coming in the next version: https://preliminary.istio.io/latest/docs/reference/config/telemetry/telemetry/#Tracing

**Comment by douglas-reid** [comment]
@dansiviter there is more documentation work to be done (lots more). but wdyt about closing this issue given that there is some in place now?

**Comment by dansiviter** [comment]
Sure. I managed to address issue with the prelim doc.
