### ISSUE TITLE
Require an option to skip validation on EnvoyFilter proto message 

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#35391]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
**Background:**
I'm working on [Aeraki](https://github.com/aeraki-framework/aeraki) and [MetaProtocol](https://github.com/aeraki-framework/meta-protocol-proxy) to add 3rd-party protocols support to the Istio service mesh. Now Dubbo, Thrift, Redis, Kafka have already been proven working.  Proprietary protocols can also be supported by adding a codec on top of MetaProtocol.

**Problem:**
My intention is to make Aeraki an addon of Istio, like Kaili, adding 3rd-party protocols support without touching the Istio code. However, Istio requires the envoy filter go API to be compiled with its core repo. Otherwise, the validation webhook will complain it doesn't know the proto, like ``` Envoy filter: could not resolve Any message type: xxx_proxy```. So when I tried to support a new protocol in Istio via EnvoyFilter, I had to modify the Istio source code to import the go API of that Envoy Filter, like this: https://github.com/aeraki-framework/istio/blob/270b62b9eff7dfb6439204c0d6be2ed876d82264/pkg/config/xds/filter_types.gen.go#L368

Is it possible that we eliminate this dependency?

**Describe alternatives you've considered**
Maybe we can add an option to Istio to make the error as info or warning, and still apply the EnvoyFilter even if Istio doesn't recognize the proto type in that EnvoyFilter.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Is it only required for validation, nothing else? If so that does seem like a reasonable addition - if it goes deeper it may be challenging

**Comment by zhaohuabing** [comment]
From the reported error, it ooks like the proto message is only required for validation. I'll look into the code to try to solve it.

**Comment by ramaraochavali** [comment]
I thought if the type is not known, the merge wont happen properly. We faced some issue with that with header casing envoy filter.

**Comment by zhaohuabing** [comment]
@ramaraochavali  unfortunately, you're right. The proto has also been used in the patch process, which seems unable to be removed.

**Comment by howardjohn** [comment]
Maybe try using TypedStruct? You can see some examples in the telemetry EnvoyFilter we ship

**Comment by zhaohuabing** [comment]
> Maybe try using TypedStruct? You can see some examples in the telemetry EnvoyFilter we ship

Thanks, @howardjohn.
This should work according to Envoy documentation:

In case the control plane lacks the schema definitions for an extension, udpa.type.v1.TypedStruct should be used as a generic container. The type URL inside it is then used by a client to convert the contents to a typed configuration resource.
