### ISSUE TITLE
istio-peer-exchange should only be added if TCP mx presents

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#35393]
### Bug Description

Currently, `istio-peer-exchange` is added to TLS alpn context regardless of presence of TCP mx filter. Now since we program MX as first class, it should be possible to only add `istio-peer-exchange` when the chain has TCP MX. This will help to fix some edge case which does not work (one side has TCP MX, one does not, the negotiation results in `istio-peer-exchange` so unexpected data being leaked to the app).

### Version

```prose
master
```

**Comment by bianpengyuan** [comment]
> This will help to fix some edge case which does not work (one side has TCP MX, one does not, the negotiation results in istio-peer-exchange so unexpected data being sent).

cc @mandarjog not sure if this is a known limitation? I tested this scenario and mx metadata is leaked to the application. Curious if I am missing something, or how did we survive the initial migration to TCP Mx?

**Comment by mandarjog** [comment]
TCP MX will only exchange metadata when alpn matches, which should only happen after the mTLS negotiation completes.
How is the data being leaked? A data leak on plain tcp stream should result in a protocol error.
cc @kyessenov

**Comment by howardjohn** [comment]
@bianpengyuan I think for the initial migration the 1.3 presented `istio` alpn and 1.4 presented istio-peer-exchange. So that's how the migration worked. (version numbers made up)

**Comment by bianpengyuan** [comment]
> TCP MX will only exchange metadata when alpn matches, which should only happen after the mTLS negotiation completes. How is the data being leaked?

Because istio-peer-exchange is added to both downstream and upstream TLS context regardless of whether mx is injected or not. If mx is only injected at one side, data will be leaked.

> @bianpengyuan I think for the initial migration the 1.3 presented istio alpn and 1.4 presented istio-peer-exchange. So that's how the migration worked. (version numbers made up)

@howardjohn yeah, but I thought there can always be race condition on proxy upgrade / EnvoyFilter being applied, but the window is just too small to run into. I guess a more problematic op is to turn off tcp mx, just deleting tcp MX would break things until all proxies config is updated.

**Comment by kyessenov** [comment]
It seems MX was converted envoyfilter to code (https://github.com/istio/istio/pull/35212). I agree that the right sequence is to enable MX filter first (globally), then switch ALPN to include the MX-capability.  Can this be done now in a transactional manner (not optimistically)?

The saving grace is that there is a magic prefix validation check as well. This might be saving it from catastrophically failing in one direction (server has MX, client does not).

**Comment by bianpengyuan** [comment]
> Can this be done now in a transactional manner

Yeah I think so, ALPN and the filters are in the same object (either cluster, or listener filter chain).

**Comment by kyessenov** [comment]
SG. ALPN should be advertised if and only if MX filter is installed.
