### ISSUE TITLE
TCP telemetry collection and policy enforcement

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#354]
This covers tasks related to having Envoy talk to Mixer for TCP traffic, including any attribute derivation and configuration desired on the Mixer side.

**Comment by ldemailly** [comment]
does this also include end to end making sure envoy/pilot/... also handle tcp services?
can you rename/update the description if that is the case (as the p0 seems to imply)

**Comment by douglas-reid** [comment]
I think it is OK to close this Epic. There is still work to be done to improve attribute generation and reporting (as well as open items for ingress support). But overall, this is now working.
