### ISSUE TITLE
Istio gateway exposed by an AWS load balancer(ALB/NLB) in TLS termination mode

### ISSUE THREAD

**Issue by crismarfr** [istio/istio#35420]
### Bug Description

Hi,
I am having a problem running istio exposed in the AWS cloud by an ALB / NLB type load balancer with TSL termination. 
I get a reset connection in return of the gateway istio. 

This is the configuration of my gateway Istio :

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-kiali
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ca-cert-istio-addons
    hosts:
    - "kiali.istio.hp.arom.dco.aws.internal.cloud.edf.fr"

When i configure the cloud load balancer ALB/NLB with passthrough the TLS connection, it works correctly. 
But when i activate TLS termination on ALB/NLB, the routing SNI doesn't work and cloud load balancer don't forward SNI header to the backend (Gateway Istio).

The istio recommendation is to configure cloud load balancer in passthrough mode. 

In production, it is not a good practice to use passthrough mode on load balancer and it's recommended to use TLS termination.

What is the solution ?
How to force the cloud load balancer to forward the SNI headers to the Istio backend ?

Another istio recommendation is disable SNI matching in the Gateway by setting the hosts field to *. But, in this mode, the routing can't work if you expose several applications.

Thanks you for your help

### Version

```prose
$ istioctl version
1.9.4

$ kubectl version --short
Client Version: v1.19.7
```

**Comment by howardjohn** [comment]
> Another istio recommendation is disable SNI matching in the Gateway by setting the hosts field to *. But, in this mode, the routing can't work if you expose several applications.

You can do the routing at the HTTP level with VirtualService.

**Comment by crismarfr** [comment]
Thank you for your response. 

I agree with you if we apply TLS termination at the gateway istio, and we use http protocol for the backend.
But if we enable passthrough mode at the gateway istio et use https protocole for the backend, we must use sni routing at the virtual service ?

is there another method of routing with the https protocol at the virtual services level ?

Here my configuration for this case :

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: config-gateway
  namespace: platform-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-config
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - config-server-v2.platform-dev.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config-vs
  namespace: platform-dev
spec:
  hosts:
  - config-server-v2.platform-dev.svc.cluster.local
  gateways:
  - config-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - config-server-v2.platform-dev.svc.cluster.local
    route:
    - destination:
        host: config-server-v2
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: config
  namespace: platform-dev
spec:
  host: config-server-v2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

**Comment by howardjohn** [comment]
>I agree with you if we apply TLS termination at the gateway istio, and we use http protocol for the backend. But if we enable passthrough mode at the gateway istio et use https protocole for the backend, we must use sni routing at the virtual service ?

Don't do this. If you want to terminate TLS at the ALB and have the application see TLS traffic you can do:
* Terminate + re-originate at ALB
* Terminate + route on HTTP with VirtualService + re-originate TLS (with SIMPLE DestinationRule)

The one issue is that you cannot re-originate TLS+mTLS (2x tls). But that is your only real option here unless you can make ALB forward SNI (or use a port-per-SNI or something...) or make your app not expect HTTPS.

**Comment by crismarfr** [comment]
Thank you for your response, but I would like to be sure that **HTTP + MTLS** with VirtualService is enough secure between ingress gateway Istio and proxy envoy embedded in sidecar in the pod. Because MTLS make handshake certificates and stream encryption, It's not necessary to enable **HTTPS + MTLS** ?

Thank you for your help

**Comment by crismarfr** [comment]
Great, thank you very much

**Comment by vangahari** [comment]
Hello @crismarfr 

I am trying to setup AWS Application load balancer instead of classic lb, By default when we deploy on EKS its creating Classic lb, instead of that how can we create application lb. I tried with the below config, but it doesnt creates the alb. If possible please suggest me with correct config.

**Service config:**
```---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: tcp
    port: 31400
    targetPort: 31400
  - name: tls
    port: 15443
    targetPort: 15443

---```
**Ingress config:**

```---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
  name: istio-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/group.name: istio
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:
    alb.ingress.kubernetes.io/subnets: us-west-2a,us-west-2b,us-west-2c
    alb.ingress.kubernetes.io/security-groups: nodes.example.com
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80

---```
