### ISSUE TITLE
Istio DNS proxying give bad answer without  a sidecar object

### ISSUE THREAD

**Issue by GeckoSplinter** [istio/istio#35421]
### Bug Description

We observed, while enabling the DNS proxying feature on istio, that the answer we get in a namespace without a sidecar object is wrong.

### Namespace A with a sidecar object
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: namespace-a
spec:
  egress:
  - hosts:
    - "namespace-a/*"
  ```

```
bash-5.1# dig kubernetes.default +search

; <<>> DiG 9.16.20 <<>> kubernetes.default +search

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 26 IN A	10.X.X.X
```

### Namespace B with DNS and without sidecar
```
bash-5.1# dig kubernetes.default +search

; <<>> DiG 9.16.20 <<>> kubernetes.default +search

;; QUESTION SECTION:
;kubernetes.default.namespace-b.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.namespace-b.svc.cluster.local. 30 IN CNAME kubernetes.default.
kubernetes.default.	30	IN	A	10.X.X.X 
```

**=> why do we have a CNAME here** 

### Namespace C without istio DNS

```
bash-5.1# dig kubernetes.default +search

; <<>> DiG 9.16.20 <<>> kubernetes.default +search

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A	10.X.X.X
```

So with istio DNS proxy and without sidecar object we observed that istio give a wrong cname in the answer.

### Version

```prose
istioctl version
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (53 proxies)

kubectl version
Server Version: v1.21.4-gke.301
```

### Additional Information

```
The following Istio control plane revisions/versions were found in the cluster:
Revision v110:
&version.MeshInfo{
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.10.4", GitRevision:"830ecc99fd2d8acb2cb0cd9f6b60fe41e3c5450a", GolangVersion:"go1.16.7", BuildStatus:"Clean", GitTag:"1.10.4"},
    },
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.10.4", GitRevision:"830ecc99fd2d8acb2cb0cd9f6b60fe41e3c5450a", GolangVersion:"go1.16.7", BuildStatus:"Clean", GitTag:"1.10.4"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision v110: Versions {1.10.4}
```

**Comment by howardjohn** [comment]
Is it _wrong_ (as in, it breaks your application) or just different?

The reason we do it is an optimization. In example A and C, `dig` will send ~5 dns requests before arriving at the answer. See https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html for details. With dns proxy, we can short-circuit it on the first request.

**Comment by GeckoSplinter** [comment]
For me it's wrong as `kubernetes.default.namespace-b.svc.cluster.local.` should not be valid and break the standard in k8s 
```
service_name.namespace.svc.cluster.local
```
to 
```
service_name.namespace1.namespace2.svc.cluster.local
```

But yes of course I understand the reason of the optimization. I just do not understand why I have the answer in a "correct" way with a sidecar object and the wrong one without the sidecar configuration. And that without looking at the DNS optimization.

**Comment by howardjohn** [comment]
With the sidecar you are telling that pod to restrict the configuration it
sees, so the DNS proxy doesn't respond and instead forwards it upsteam
(typically kube-dns)

**Comment by GeckoSplinter** [comment]
Thanks, that's why indeed.

But could the proxy answer with the "correct/classical" name instead of appending the dns search ?
(I did not check the implementation but that might be complicated.)

**Comment by howardjohn** [comment]
Hypothetically yes, but there is no existing config in the code to switch the behavior. Note this behavior mirrors https://coredns.io/plugins/autopath/, so its semi-standard.

Is the response breaking your application?

**Comment by GeckoSplinter** [comment]
Thanks

Yes it's breaking things we use, the strimzi kafka operator.
The operator is making a DNS request to autodiscover the cluster DNS domain (most of the time anyway `cluster.local`)
IMHO that implementation is bad and could be set up via a config in the operator that would avoid doing bash oneliner to get that information and make people with custom cluster dns domain have to explicitly set it.
https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/scripts/cluster_operator_run.sh#L6
So we will force the env `KUBERNETES_SERVICE_DNS_DOMAIN` in that script and raise an issue on their side.

I agree that the implementation on the istio side is good, following coredns (authopath) and it seams more complicated to change the behavior than on the strimzi operator.

Thanks again @howardjohn
