### ISSUE TITLE
cni: autodetect bin dir

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35435]
I don't think there is an API we can do to fetch this, but we can definitely add a map of `GKE -> /xyz, Openshift -> /abc` into the install flow to make it a bit simpler to get started

cc @bianpengyuan

**Comment by howardjohn** [comment]
In particular without this we cannot really run the integ tests on GKE easily

**Comment by bianpengyuan** [comment]
By installation time, you mean at istioctl? Do we have a reliable way to tell platform there? Should we instead do it at CNI directly?

**Comment by howardjohn** [comment]
You can tell gke from the version number (in istioctl - maybe even helm). Not sure a better way unfortunately. It would be cool if they had an API to expose the CNI settings but I don;t think they do

**Comment by bianpengyuan** [comment]
Could you remind me why we cannot run tests on GKE easily without this? I think we can pass in some overlay in the test job?

**Comment by howardjohn** [comment]
We probably _can_ run it on GKE (I am sure we do internally?), I couldn't figure out how though. I wouldn't consider this a high priority, just nice to have, especially if CNI becomes more common its nice to not have churn on install
