### ISSUE TITLE
kiali is not loading the graph (the server could not find the requested resource (get workloadentries.networking.istio.io))

### ISSUE THREAD

**Issue by anup1384** [istio/istio#35450]
### Bug Description

I'm getting an issue while opening kiali dashboard, the graph is not loading and in logs it's showing some permission issue.
Error- E1002 16:05:03.869034       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.1/tools/cache/reflector.go:167: Failed to watch *kubernetes.GenericIstioObject: failed to list *kubernetes.GenericIstioObject: the server could not find the requested resource (get workloadentries.networking.istio.io)

Cluster role permission is there.

### Version

```prose
λ istioctl version
client version: 1.11.2
control plane version: 1.12-alpha.d70cd277f4f001461324f989de605487894d95ca
data plane version: 1.12-alpha.27e28972ff1b1229ddd603ba8363827a3f99fad3 (3 proxies), 1.12-alpha.d70cd277f4f001461324f989de605487894d95ca (3 proxies)

λ kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.2-eks-0389ca3
```

**Comment by howardjohn** [comment]
Kiali is not a part of Istio, please report in https://github.com/kiali/kiali. Thanks!
