### ISSUE TITLE
istioctl requires namespace to delete but not add

### ISSUE THREAD

**Issue by chinangela** [istio/istio#3545]
### Problem

Following steps in [this doc](https://istio.io/docs/tasks/traffic-management/traffic-shifting.html#weight-based-version-routing) we tried to run

```
istioctl delete routerule reviews-test-v2
```

but got the error
```
Error: 1 error occurred:

* cannot delete reviews-test-v2: an empty namespace may not be set when a resource name is provided
```

When we try to delete using
```
istioctl delete -f samples/bookinfo/kube/route-rule-reviews-test-v2.yaml
```
it works.

### Possible resolutions:
1. update docs to include `-n default`
2. update the docs to use the file for delete, e.g. `-f ...`
3. change the `delete` command to default the namespace if not set

**Comment by SeriyBg** [comment]
I can work on this issue.
Could someone of the maintainers tell me what is the preferred resolution to fix this one?
I would set the default namespace for delete command if it is not set.

**Comment by wattli** [comment]
@SeriyBg , is this issue fixed?

**Comment by SeriyBg** [comment]
@wattli, PR is not merged yet. Maybe you can review it and approve it? Thank you
