### ISSUE TITLE
helm failing to install charts

### ISSUE THREAD

**Issue by chandrakanthkannam** [istio/istio#35460]
### Bug Description

I'm trying to download/install helm charts following these steps in [README.md](https://github.com/istio/istio/blob/master/manifests/charts/base/README.md) , and receiving below error

`> helm install istio-base istio/base -n istio-system
Error: failed to download "istio/base" (hint: running helm repo update may help)`

### Version

```prose
> helm version --short
v3.6+unreleased+gee91a12
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
You need to add `--devel` until a official (non-prerelease) release is launched (1.12, sometime in nov). Thanks!
