### ISSUE TITLE
Confusion about TCP metrics tcp_received_bytes, tcp_sent_bytes - possible mix-up?

### ISSUE THREAD

**Issue by jobegrabber** [istio/istio#35462]
### Bug Description

I'm working on a university project to analyze network traffic (TCP throughput) during execution of different Apache Flink / Gradoop pipelines running on a bare-metal cluster.
We're utilizing Kubernetes (microk8s) and hence I'd like to use Istio for this project.
Right now I'm trying to measure traffic between Flink TaskManagers running in Kubernetes and HDFS DataNodes running directly on our servers.

With a single TaskManager the pipeline reads in a 2 GB graph representing a social network from HDFS, adds a simple property (Age) to each vertex and writes the graph back to HDFS.

When looking at the TCP metrics recorded by the Envoy proxy, `tcp_received_bytes` and `tcp_sent_bytes` seem to be mixed-up; initially, the relevant `tcp_sent_bytes` counter as recorded on the single executing TaskManager counts up to 2 GB, whereas `tcp_received_bytes` only starts increasing at the end of the pipeline, during the write-out phase.

![image](https://user-images.githubusercontent.com/889310/135856404-d3d5933a-a5ff-495a-908e-51ce4ff101f0.png)

I tried digging through the code of `istio-proxy`.
In [`extensions/stats/plugin.h`](https://github.com/istio/proxy/blob/1.11.3/extensions/stats/plugin.h#L369) the handlers `onDownstreamData` and `onUpstreamData` increase `tcp_received_bytes` and `tcp_sent_bytes` respectively:
```c++
  // Called on onData call, so counting the data that is received.
  FilterStatus onDownstreamData(size_t size, bool) override {
    request_info_.tcp_received_bytes += size;
    return FilterStatus::Continue;
  }
  // Called on onWrite call, so counting the data that is sent.
  FilterStatus onUpstreamData(size_t size, bool) override {
    request_info_.tcp_sent_bytes += size;
    return FilterStatus::Continue;
  }
```

I tried looking for the mentioned calls to `onData` and `onWrite`, but could only find a call to `onData` in [`source/common/tcp/conn_pool.h#L45`](https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/tcp/conn_pool.h#L45) inside the envoy repo:

```c++
class ActiveTcpClient : public Envoy::ConnectionPool::ActiveClient {
public:
  struct ConnReadFilter : public Network::ReadFilterBaseImpl {
    ConnReadFilter(ActiveTcpClient& parent) : parent_(parent) {}

    // Network::ReadFilter
    Network::FilterStatus onData(Buffer::Instance& data, bool end_stream) override {
      parent_.onUpstreamData(data, end_stream);
      return Network::FilterStatus::StopIteration;
    }
    ActiveTcpClient& parent_;
  };
```

This contradicts the comments from the snippet in `stats/plugin.h`.

Could that be a mix-up or am I misunderstanding some concept(s)?

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (3 proxies)

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.20.10-34+3c9720652e8d58
```

### Additional Information

No ingress or egress gateways setup. `ServiceEntry`'s configured for each of the 20 bare-metal nodes and associated HDFS ports.

**Comment by bianpengyuan** [comment]
This was discussed before https://github.com/istio/istio/issues/32399 cc @kyessenov

**Comment by jobegrabber** [comment]
> This was discussed before #32399 cc @kyessenov

Thanks for your reply, @bianpengyuan, and sorry, I'm pretty sure I checked for existing issues, but somehow I must've missed the one you linked :slightly_frowning_face:
