### ISSUE TITLE
Investigate potentional breaking changes in Envoy 1.20

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35480]
Before shipping 1.12, we should take a close look at changes to Envoy for backwards compatibility
https://www.envoyproxy.io/docs/envoy/latest/version_history/current

* config: due to the switch to using work-in-progress annotations and warnings to indicate APIs subject to change, the following API packages have been force migrated from v3alpha to v3
  Impact envoyfilter users perhaps, but shouldn't impact us.
* contrib images
  https://github.com/istio/istio/issues/35336
* dns_filter: dns_filter protobuf fields have been renumbered to restore compatibility with Envoy 1.18, breaking compatibility
  possbile, but unlikely, envoyfilter breakage
* extensions: deprecated extension names now default to triggering a configuration error. The previous warning-only behavior may be temporarily reverted by setting the runtime key envoy.deprecated_features.allow_deprecated_extension_names to true
  VERY likely to break envoyfilters. We need to be very careful here - possibly set the flag for a bit
* config: reduced log level for “Unable to establish new stream” xDS logs to debug.
  we need to make sure our agent logging is up to date to make sense here
* http: correct the use of the x-forwarded-proto header and the :scheme header. Where they differ (which is rare) :scheme will now be used for serving redirect URIs and cached content. This behavior can be reverted by setting runtime guard correct_scheme_and_xfp to false.
  This stuff has broken our users constantly every release. Probably it will break users again - we will need to investigate more
* access log: fix %UPSTREAM_CLUSTER% when used in http upstream access logs. Previously, it was always logging as an unset value.
  might impact log output, but should be beneficial

**Comment by howardjohn** [comment]
cc @lambdai 

@yangminzhu there are lots of ext_authz ones that may be worth a look

**Comment by Kmoneal** [comment]
@lambdai @yangminzhu Are there any updates? Just want to make suer this is resolved before 1.12 needs to be released

**Comment by yangminzhu** [comment]
nothing from my side, we have added the release note for 1.12, thanks for checking.
