### ISSUE TITLE
Access logs not always logging

### ISSUE THREAD

**Issue by irregular-ferret** [istio/istio#35481]
### Bug Description

We have found in particular situations the access logs are not logging requests. The requests are completing successfully, and metrics are being generated (you can see the traffic in Kiali)

Scenarios not logging access logs:
- HTTPS requests originating from the application calling services external to the cluster (tried with and without ServiceEntry) 

Scenarios logging access logs:
- Exec onto application container and curl to same FQDN using HTTPS
- Port 80 traffic to other internal services
- Port 80 to external service

This happens for some applications, whilst others are logging their traffic fine.

### Version

```prose
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (160 proxies)

Client Version: v1.18.20
Server Version: v1.17.11
```

**Comment by howardjohn** [comment]
When the app originates https we just get tcp level logs. This occurs when the connection is closed. Given you are logs with curl but not in your app I would guess your app is keeping the connection alive so it's not log until much later?

**Comment by irregular-ferret** [comment]
Sorry for late reply, this makes a lot of sense and will be the case. Thank you very much John :)
