### ISSUE TITLE
API to set transport protocol used by the sidecar proxy

### ISSUE THREAD

**Issue by Sachin-A** [istio/istio#35491]
Is it possible for a service to instruct the sidecar to use a specific transport protocol (e.g., switch from TCP Cubic to BBR)? 

If such L4 customizations aren't possible, what's a good workaround? Setting the default congestion control in the kernel doesn't seem to do the trick. This is possibly because the sidecar implementation is overriding the kernel defaults and choosing its own CC for the initiated TCP connections.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

The particular context in which I would need this feature is when I want to use two different transport protocols for two different instances of the same service or for different services altogether. Taking the [Istio Bookinfo app](https://istio.io/latest/docs/examples/bookinfo/) as an example, is there a way to configure sidecars in reviews v2 and v3 to run different transport protocols?

**Comment by howardjohn** [comment]
This would be dependant on Envoy support. https://www.infoq.com/news/2018/12/envoycon-ebay-edge/ seems to suggest this exists but I don't see it so it seems likely it was an internal fork they added support.

**Comment by Sachin-A** [comment]
It wasn't quite working when I did that but [envoy socket options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto.html) look promising. Thank you for your help!
