### ISSUE TITLE
Official gateway chart cannot be used as a subchart

### ISSUE THREAD

**Issue by remi-gelinas** [istio/istio#35495]
### Bug Description

Of all the official Istio charts in the[ official repo](https://artifacthub.io/packages/helm/istio-official/gateway), `gateway` is the only one with an enforced values schema - because `global` is not an allowed property in the schema, but is one that is injected to subcharts. one cannot use `istio/gateway` as a subchart.

I am setting up Istio to deploy through ArgoCD, which requires me to use proxy Helm charts when generating `ApplicationSets`.

### Version

```prose
`istio/gateway 1.12.0-alpha.1`
```

**Comment by QuestionAndAnswer** [comment]
Hey, does anyone know about workaround for now?

**Comment by nc-ruth** [comment]
Please check out https://github.com/helm/helm/issues/10392 where there is a discussion

**Comment by billiaz** [comment]
Added a pull request, with one of the solutions: 
https://github.com/istio/istio/pull/36744 might need changes and discussion
