### ISSUE TITLE
TPR "IstioConfig" is not ready 

### ISSUE THREAD

**Issue by fatg1988** [istio/istio#355]
kubectl apply -f install/kubernetes/istio.yaml
how can i do ?

![default](https://cloud.githubusercontent.com/assets/3365952/26677078/ee3e01c8-46fc-11e7-9c92-05b134050d76.png)
![default](https://cloud.githubusercontent.com/assets/3365952/26677089/ff3c72c0-46fc-11e7-91de-d6d2c9a07920.png)

**Comment by ingshtrom** [comment]
I'm getting this too on a brand new cluster in AWS created via Tectonic. I thought it might be a role issue, but I granted all roles every permission and I still get the errors.

**Comment by kyessenov** [comment]
@andraxylia @costinm seems like yet another RBAC issue?

**Comment by andraxylia** [comment]
Definitely RBAC issue with TPR. What k8s version do you have?

Did you install istio 0.1.5 or earlier?

Did you apply the rbac alpha or beta file? 

Can you please check if the rbac file you applied contains "istioconfigs.istio.io"?

- apiGroups: ["istio.io"]
  resources: ["istioconfigs", "istioconfigs.istio.io"]
  verbs: ["*"]

Can you also paste the output of these commands?

kubectl get clusterrole istio-manager -oyaml
kubectl get rolebinding istio-ingress-admin-role-binding -oyaml
kubectl get clusterrolebinding  istio-ingress-admin-role-binding -oyaml

They will tell us if the istio-ingress-admin-role-binding is a RoleBinding or a ClusterRoleBinding. It may help to use ClusterRoleBinding (use alpha or beta version, depending on your cluster), and remove the line containing "namespace: default".

# Grant permissions to the Ingress controller.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: istio-ingress-admin-role-binding
subjects:
- kind: ServiceAccount
  name: istio-ingress-service-account

At start-up, the process will attempt to get or create the TPR, and after that it will get into a loop where it waits for the TPR. Is there something more in the log?

Thanks!

**Comment by fatg1988** [comment]
@andraxylia 
k8s version  1.6.2
follow by this article: https://istio.io/docs/tasks/installing-istio.html

curl -L https://git.io/getIstio | sh -
file istio-rbac-beta.yaml istio-ingress-admin-role-binding
![default](https://cloud.githubusercontent.com/assets/3365952/26708174/c09bdbac-477c-11e7-999c-2e8cf6642ddb.png)


kubectl get clusterrole istio-manager -oyaml
![default](https://cloud.githubusercontent.com/assets/3365952/26707929/d73e747a-477a-11e7-8113-5e2259ca1aca.png)

kubectl get rolebinding istio-ingress-admin-role-binding -oyaml
kubectl get clusterrolebinding istio-ingress-admin-role-binding -oyaml
![default](https://cloud.githubusercontent.com/assets/3365952/26708027/a632bfa2-477b-11e7-99c1-6bb88f4df55c.png)

![default](https://cloud.githubusercontent.com/assets/3365952/26708671/eba39918-477f-11e7-93ae-0b3e8f55b832.png)


![default](https://cloud.githubusercontent.com/assets/3365952/26708734/403972fe-4780-11e7-98bb-54696325f307.png)

**Comment by fatg1988** [comment]
both change the code to do a scoped get on namespace and change the following to a ClusterRoleBinding and add the namespace to the subject.
