### ISSUE TITLE
istio 1.8.6 not work with AKS/GKE v 1.19

### ISSUE THREAD

**Issue by shruti-singh26** [istio/istio#35505]
### Bug Description

Istio Mixer is rejecting 1 out of 10 request with 403 UAEX errors on the istio proxy. All these services and whitelisting where working fine till 1.18 version of GKE/AKS but after we upgraded some of our clusters we see this issues.

[2021-10-04T06:27:22.005Z] "POST /apiHTTP/1.1" 403 UAEX "-" 288 0 5001 - "-" "axios/0.18.1" "616d319a-74d6-9b98-b79b-94e1096a1c47" "pod:8080" "-" - - ip:8080 ip:44102 outbound_.8080_._.pod.svc.cluster.local -

### Version

```prose
client version: 1.9.1
control plane version: 1.8.6
data plane version: 1.8.6 (332 proxies)
```

**Comment by howardjohn** [comment]
Istio 1.8, and with it Mixer, is EOL and unsupported: https://istio.io/latest/news/support/announcing-1.8-eol-final/. Sorry.
