### ISSUE TITLE
Envoy 1.20 logging regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35512]
Right now we are blind to control plane failures: https://github.com/envoyproxy/envoy/issues/18508

We log in xdsproxy at debug level only, envoy logs incorrectly. We must either change our level or fix ^

**Comment by dgn** [comment]
the fix has gone into the v1.20 branch of envoyproxy: https://github.com/envoyproxy/envoy/pull/18886

now it just needs to be picked up by our automation

**Comment by dgn** [comment]
fix is on our release-1.12 branch now. closing
