### ISSUE TITLE
application CONNECT request (HTTP proxy) not working with error 404 route not found

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#35526]
### Bug Description

The application is sending a CONNECT request to an external HTTP proxy at `http://10.124.0.8:3128` (not in the mesh) and failed with Envoy log:
`[2021-10-08T00:39:31.261Z] "CONNECT - HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "-" "cpp-httplib/0.7" "2f10fb53-8b27-42d3-8fd1-5029448731ea" "accounts.google.com:443" "-" - - 10.124.0.8:3128 10.124.2.14:37650 - -`

This seems due to that there is another HTTP service in the cluster that also uses the port `3128` which caused the Istiod to generate a HTTP filter chain on the `0.0.0.0_3128` filter chain. The `http_inspector` inspects the CONNECT request as HTTP and then it is handled by the HTTP filter chain which does not match the CONNECT method at all and caused the 404 route not found error.

This works if I delete the HTTP service on port 3128 because it will remove the extra HTTP filter chain and the only default TCP passthrough filter chain will handle the request.

This seems to me a bug that creating a non-related HTTP service on the same port would cause the CONNECT request not working, which has nothing to do with that HTTP service but just happens to use the same port number?

Also can we use virtual service / service entry to force the CONNECT method to go through the TCP passthrough filter chain?

Our current workaround is to just to exclude the IP or Port from the outbound traffic.

cc @lambdai @howardjohn @liwenhao0810 

### Version

```prose
Tested in 1.11
```

**Comment by howardjohn** [comment]
Seems like CONNECT support is alpha so ideally we would tcp_proxy it, but I think it's too late - we don't realize it's CONNECT until we are in routing logic. So maybe we just add a CONNECT match (or better - make envoy support matching *all* traffic in a route, which is something that should be possible to avoid footguns like this) to the catch all route?

**Comment by pratapagiri** [comment]
@howardjohn I'm facing the similar issue. Could you please solution or workaround to this issue?

**Comment by laiminhtrung1997** [comment]
any news on this?

**Comment by SergeSpinoza** [comment]
Hi! Was this problem solved somehow? I have the same problem.
