### ISSUE TITLE
[Virtual Machine Installation] When stop the istio, the envoy not stop, lead to istio restart fail

### ISSUE THREAD

**Issue by herbguo** [istio/istio#35534]
### Bug Description

After installing istio on the virtual machine.  When  stop the istio, the envoy not stop, lead to istio restart fail.
The reason is that the envoy process does not stop, still occupying 15000 ports, making ISTIO unable to restart.

**The normal operating state:**
root@ubuntuforistio:~/istio# systemctl status istio
● istio.service - istio-sidecar: The Istio sidecar
     Loaded: loaded (/lib/systemd/system/istio.service; disabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-10-10 08:50:10 UTC; 10min ago
       Docs: http://istio.io/
   Main PID: 26395 (su)
      Tasks: 0 (limit: 2279)
     Memory: 1.1M
     CGroup: /system.slice/istio.service
             ‣ 26395 su -s /bin/bash -c ulimit -n 1024; INSTANCE_IP=10.0.2.15 POD_NAME=ubuntuforistio POD_NAMESPACE=ubuntu exec /usr/local/bin/pilot-agent >
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 113 -j RETURN
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_OUTPUT -m owner --gid-owner 113 -j RETURN
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_OUTPUT -d 127.0.0.53/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_OUTPUT -j ISTIO_REDIRECT
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: COMMIT
Oct 10 08:50:10 ubuntuforistio istio-start.sh[26473]: # Completed on Sun Oct 10 08:50:10 2021
Oct 10 08:50:10 ubuntuforistio su[26395]: (to istio-proxy) root on none
Oct 10 08:50:10 ubuntuforistio su[26395]: pam_unix(su:session): session opened for user istio-proxy by (uid=0)

**Next，Stop the istio:**
root@ubuntuforistio:~/istio# systemctl stop istio
root@ubuntuforistio:~/istio# systemctl status istio
● istio.service - istio-sidecar: The Istio sidecar
     Loaded: loaded (/lib/systemd/system/istio.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: http://istio.io/

Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: # Generated by ip6tables-save v1.8.4 on Sun Oct 10 09:00:45 2021
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: *nat
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: :PREROUTING ACCEPT [0:0]
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: :INPUT ACCEPT [0:0]
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: :OUTPUT ACCEPT [0:0]
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: :POSTROUTING ACCEPT [0:0]
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: COMMIT
Oct 10 09:00:45 ubuntuforistio istio-start.sh[26706]: # Completed on Sun Oct 10 09:00:45 2021
Oct 10 09:00:45 ubuntuforistio systemd[1]: istio.service: Succeeded.
Oct 10 09:00:45 ubuntuforistio systemd[1]: Stopped istio-sidecar: The Istio sidecar.

**Then start the istio:**
root@ubuntuforistio:~/istio# systemctl start istio
root@ubuntuforistio:~/istio# systemctl status istio
● istio.service - istio-sidecar: The Istio sidecar
     Loaded: loaded (/lib/systemd/system/istio.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) since Sun 2021-10-10 09:10:13 UTC; 1s ago
       Docs: http://istio.io/
    Process: 30842 ExecStart=/usr/local/bin/istio-start.sh (code=exited, status=0/SUCCESS)
    Process: 30939 ExecStopPost=/usr/local/bin/istio-start.sh clean (code=exited, status=0/SUCCESS)
   Main PID: 30842 (code=exited, status=0/SUCCESS)

Oct 10 09:10:13 ubuntuforistio systemd[1]: istio.service: Succeeded.

**View the log:**
2021-10-10T09:06:01.533699Z     info    Epoch 0 starting
2021-10-10T09:06:01.557263Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --local-address-ip-version v4 --bootstrap-version 3 --file-flush-interval-msec 1000 --disable-hot-restart --log-format %Y-%m-%dT%T.%fZ    %l      envoy %n        %v -l warning --component-log-level misc:error --concurrency 2]
2021-10-10T09:06:01.635218Z     critical        envoy main      error initializing configuration 'etc/istio/proxy/envoy-rev0.json': cannot bind '127.0.0.1:15000': Address already in use
cannot bind '127.0.0.1:15000': Address already in use
2021-10-10T09:06:01.642243Z     error   Epoch 0 exited with error: exit status 1

**View the port status:**
root@ubuntuforistio:~/istio#  netstat -antp| grep 15000
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      26495/envoy

root@ubuntuforistio:~/istio# ps -ef | grep envoy
istio-p+   26495       1  0 08:50 ?        00:00:02 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --local-address-ip-version v4 --bootstrap-version 3 --file-flush-interval-msec 1000 --disable-hot-restart --log-format %Y-%m-%dT%T.%fZ?%l?envoy %n?%v -l warning --component-log-level misc:error --concurrency 2
root       26779   25934  0 09:01 pts/0    00:00:00 grep --color=auto envoy

**Kill the envoy process，the istio can start success:**
root@ubuntuforistio:~/istio# ps -ef | grep envoy
istio-p+   26495       1  0 08:50 ?        00:00:06 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --local-address-ip-version v4 --bootstrap-version 3 --file-flush-interval-msec 1000 --disable-hot-restart --log-format %Y-%m-%dT%T.%fZ?%l?envoy %n?%v -l warning --component-log-level misc:error --concurrency 2
root       38303   25934  0 09:18 pts/0    00:00:00 grep --color=auto envoy
root@ubuntuforistio:~/istio# kill -9 26495
root@ubuntuforistio:~/istio# systemctl status istio
● istio.service - istio-sidecar: The Istio sidecar
     Loaded: loaded (/lib/systemd/system/istio.service; disabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-10-10 09:18:27 UTC; 899ms ago
       Docs: http://istio.io/
   Main PID: 38480 (su)
      Tasks: 0 (limit: 2279)
     Memory: 1.1M
     CGroup: /system.slice/istio.service
             ‣ 38480 su -s /bin/bash -c ulimit -n 1024; INSTANCE_IP=10.0.2.15 POD_NAME=ubuntuforistio POD_NAMESPACE=ubuntu exec /usr/local/bin/pilot-agent >
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 113 -j RETURN
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_OUTPUT -m owner --gid-owner 113 -j RETURN
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_OUTPUT -d 127.0.0.53/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_OUTPUT -j ISTIO_REDIRECT
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: COMMIT
Oct 10 09:18:27 ubuntuforistio istio-start.sh[38558]: # Completed on Sun Oct 10 09:18:27 2021
Oct 10 09:18:27 ubuntuforistio su[38480]: (to istio-proxy) root on none

### Version

```prose
root@ubuntuforistio:~/istio# istioctl version
client version: 1.11.3
control plane version: 1.11.2
data plane version: 1.11.0 (1 proxies), 1.11.2 (11 proxies)
root@ubuntuforistio:~/istio# kubectl version --short
Client Version: v1.22.0
Server Version: v1.18.8
```

**Comment by howardjohn** [comment]
I recall a variety of PRs in this area. Should dig them up to see if they are in 1.11 and didn't fully fix it or if it just hasn't been shipped yet
