### ISSUE TITLE
TestDefaultRevisionChanges flakes frequently

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#35560]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35550/unit-tests_istio/1447742426897715200
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35557/unit-tests_istio/1447676059016237056

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35346/unit-tests_istio/1447756998547345408
