### ISSUE TITLE
Mixer Dashboard metrics out of date

### ISSUE THREAD

**Issue by jeffmendoza** [istio/istio#3556]
Currently the Mixer dashboard is using:

```
envoy_cluster_mixer_server_membership_healthy
envoy_cluster_mixer_server_membership_total
envoy_cluster_mixer_server_outlier_detection_ejections_active
envoy_cluster_mixer_server_outlier_detection_ejections_enforced_total
envoy_cluster_mixer_server_outlier_detection_ejections_overflow
envoy_cluster_mixer_server_upstream_cx_active
envoy_cluster_mixer_server_upstream_rq_4xx
envoy_cluster_mixer_server_upstream_rq_5xx
envoy_cluster_mixer_server_upstream_rq_retry
envoy_cluster_mixer_server_upstream_rq_retry_overflow
envoy_cluster_mixer_server_upstream_rq_retry_success
envoy_cluster_mixer_server_upstream_rq_time
envoy_cluster_mixer_server_upstream_rq_total
```

Prometheus is showing 
![metrics](https://user-images.githubusercontent.com/771387/36319622-5dcdafa8-12f8-11e8-8642-3a393d248a54.png)

@douglas-reid Is it correct to simply add `_check` between mixer and server for all the above metrics? Thanks.

**Comment by douglas-reid** [comment]
@jeffmendoza no, we need to do a bit more. this is related to a very recent change in configuration that enables separation of check and report. we want to monitor both.

@rshriram i thought that we were going to use `mixer_server` as the default cluster name until there was a reason to separate. did that change?

**Comment by douglas-reid** [comment]
Update: apparently, the latest direction is that there will always be 2 clusters: `mixer_check_server` and `mixer_report_server`.

Working on e2e tests to validate dashboard now.

**Comment by douglas-reid** [comment]
I believe this has been resolved by the dashboard e2e tests.
