### ISSUE TITLE
Improve documentation regarding match-rules-merging of distributed VirtualService resource definitions

### ISSUE THREAD

**Issue by tubocurarin** [istio/istio#35598]
Hi :)

During the development of our app-stack I had a lot of discussions about how the behavior is for the merging of match-rules when the definition of VirtualServices happens across different files (according to the ["Best Practices"](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services)).

I did not find immediately information about how the merging of match-rules is performed and what rules it obeys. Finally, they are only mentioned on the ["Best Practices"](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services) page. But even there, they are not 100% precise.

The current documentation should be improved, as right now I believe it is too vague, not complete and partially documented at the wrong places / not written where it actually belongs.

In particular I have identified following improvements that I think would be beneficial:
- Moving/Copying everything/parts of the description on the ["Best Practices"](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services) page to the [VirtualService docs](https://istio.io/latest/docs/reference/config/networking/virtual-service/).
- Be more precise about the terminology of a "catch-all" rule:
  - According to [this issue comment](https://github.com/istio/istio/issues/10485#issuecomment-448255162), a catch-all-rule denotes a match-block with a `prefix: /` directive. Is this maybe the default that is just not documented?
- The [VirtualService docs](https://istio.io/latest/docs/reference/config/networking/virtual-service/) do not mention concretely what happens, if no `match`-block is specified for [`HTTPRoute`s](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute) (might apply to other route types as well). I know this one might be a bit redundant, but personally I would like to read "no match-rules at all = will match all requests" or similar to have a definite statement for that case.
- The description of [`PILOT_ENABLE_ROUTE_COLLAPSE_OPTIMIZATION`](https://istio.io/latest/docs/reference/commands/pilot-discovery/) in the table should link to the relevant documentation above on the VirtualService-docs page.

Do you have maybe more ideas? :smile:

Sorry for writing it so drastically, but this topic really caused some headaches on my side :sweat_smile: 

**References**
- https://github.com/istio/istio/issues/10485
- https://github.com/istio/istio/issues/10464

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by TheAsteroid** [comment]
Note on this, according to the latest documentation the catch-all rule should *not* have any `match` at all: https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services

It appears this has changed recently, after updating from 1.9.2 to 1.11.4 we suddenly started getting warnings about overlapping rules. 

It would be great to have this in the reference docs rather than a best practices page.
