### ISSUE TITLE
Add support for hystrix metrics streams

### ISSUE THREAD

**Issue by dcberg** [istio/istio#356]
Istio should support hystrix metrics streams which are useful with service communication as well as circuit breakers (as seen in Envoy).

https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream

Once we have the event stream then we could run the hystrix dashboard and consume the stream.

https://github.com/Netflix/Hystrix/wiki/Dashboard

**Comment by kalyanam** [comment]
This is a great idea to reuse the existing awesome hystrix dashboard. I see the issue is closed, but can't find relevant commits. Is it implemented or discarded?

**Comment by douglas-reid** [comment]
@kalyanam this was not implemented. if you believe that this has value, please reopen. it will still be a help-wanted task for awhile however.
