### ISSUE TITLE
Analyzing Istio Performance `kubectl cp` commands error: one of src or dest must be a local file specification

### ISSUE THREAD

**Issue by janamtote** [istio/istio#35601]
Hello. I'm trying to follow this guide: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

But the `kubectl cp` commands get an error.

```bash
$ kubectl cp -n "$NS" "$POD":/var/lib/istio/data /tmp/envoy -c istio-proxy
error: one of src or dest must be a local file specification

$ kubectl cp -n "$NS" "$POD":/lib/x86_64-linux-gnu /tmp/envoy/lib -c istio-proxy
error: one of src or dest must be a local file specification

$ kubectl cp -n "$NS" "$POD":/usr/local/bin/envoy /tmp/envoy/lib/envoy -c istio-proxy
error: one of src or dest must be a local file specification
```

```
$ istioctl version
client version: 1.8.0
control plane version: 1.11.3
data plane version: 1.9.8 (178 proxies), 1.11.3 (575 proxies), 1.10.4 (106 proxies)
```

**Comment by janamtote** [comment]
@howardjohn Yes.. The preceding `kubectl exec` commands ran successfully

**Comment by janamtote** [comment]
I tried running `mkdir envoy` in `tmp` but I get an error regarding read only file-system which might be related.. I tried different things to try and resolve that but no success..

**Comment by bazzuka** [comment]
The same for our setup 2600% cpu on 32 core  proc when processing 400 mbit http only traffic.
