### ISSUE TITLE
CoreDNS overwhelmed if MESH_EXTERNAL DNS ServiceEntry is NXDOMAIN

### ISSUE THREAD

**Issue by dnwe** [istio/istio#35603]
### Bug Description

Investigating CoreDNS timeouts in a given cluster I noticed that the DNS pods were getting OOMKilled, which was unusual as their usage is normally quite small. Looking at the CoreDNS logs there was a torrent of NXDOMAIN responses for a given domain with a requesting source IP covering pretty much every in-mesh Pod in the cluster. It seems that the istio-proxy sidecars were rapidly re-querying DNS for this domain (that was no longer registered externally) even though they weren't actually making any requests to it. Is this intended behaviour?

Before — with the MESH_EXTERNAL DNS ServiceEntry still in existance and a few minutes after a restart of the coredns pods:

```
% kubectl top pod -n kube-system -l k8s-app=kube-dns --use-protocol-buffers
NAME                      CPU(cores)   MEMORY(bytes)
coredns-6c6dfcdfc-96dv5   1493m          326Mi
coredns-6c6dfcdfc-jk95k   1518m          350Mi
coredns-6c6dfcdfc-jlr96   1419m          314Mi
```

After deleting the MESH_EXTERNAL DNS ServiceEntry, restarting the pods and waiting 5 mins:

```
% kubectl top pod -n kube-system -l k8s-app=kube-dns --use-protocol-buffers
NAME                       CPU(cores)   MEMORY(bytes)
coredns-5f78b66474-2xh4r   402m         28Mi
coredns-5f78b66474-4tgzs   319m         41Mi
coredns-5f78b66474-7bdt4   376m         29Mi
```

Memory usage continues to idle at this point with the normal cluster DNS traffic.

### Version

```prose
% istioctl version
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (136 proxies)

% kubectl version --short
Client Version: v1.19.15
Server Version: v1.19.15
```

**Comment by howardjohn** [comment]
@lambdai it seems like lazy-loading the dns stuff may be useful. Users normally apply SE to entire mesh but likely only a tiny subset actually use that cluster. Not sure how feasible that is.

We do respect the DNS ttl but with nxdomain it's like low/ignored which exacerbates this

**Comment by ramaraochavali** [comment]
@howardjohn I am wondering for these type of usecases, we should probably add an option to specify DNS refresh rate in DR or Service Entry (probably DR is better) so that we honour what user says for that particular cluster and do not set respect_dns_ttl or default dns refresh rate to mesh config value/5s?

**Comment by howardjohn** [comment]
What is the TTL in these cases is what I would be interested in. Clients are supposed to follow ttl, right? So if we are not we ought to have a pretty good reason.

5s default is probably too low as a fallback. Especially if Envoy goes to the refresh rate when NXDOMAIN?

I would much prefer lazy loaded DNS if its feasible - will solve this for good.

**Comment by dnwe** [comment]
Still an issue I believe

**Comment by howardjohn** [comment]
Set `dnsRefreshRate: 60s` (or higher) in to control the refresh rate of DNS on NXDOMAIN. Not sure this is actually a great state, looking into how to improve it, but for now that should settle things.
