### ISSUE TITLE
Error on service IP resolution from VM in multi-network installation

### ISSUE THREAD

**Issue by pedro-tramontin** [istio/istio#35614]
### Bug Description

Followed the installation guide on https://istio.io/latest/docs/setup/install/virtual-machine/ and when running `curl` from the virtual machine it tries to reach the service using k8s internal IP instead of the `eastwestgateway` external ip.

```
$ curl -v helloworld.sample.svc:5000/hello
*   Trying 100.68.255.18:5000...
* TCP_NODELAY set
* Connected to helloworld.sample.svc (100.68.255.18) port 5000 (#0)
> GET /hello HTTP/1.1
> Host: helloworld.sample.svc:5000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 241
< content-type: text/plain
< date: Thu, 14 Oct 2021 15:37:10 GMT
< server: envoy
< 
* Connection #0 to host helloworld.sample.svc left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435588:SSL routines:OPENSSL_internal:CLIENTHELLO_TLSEXT 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT
```

```
$ kubectl get service helloworld -n sample
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
helloworld   ClusterIP   100.68.255.18   <none>        5000/TCP   19h
```

```
$ kubectl get service istio-eastwestgateway -n istio-system
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                                  PORT(S)                                                           AGE
istio-eastwestgateway   LoadBalancer   100.67.217.216   a39c3b3f23d064affa54f65c62c61b33-0000000000.eu-central-1.elb.amazonaws.com   15021:32382/TCP,15443:32560/TCP,15012:31304/TCP,15017:30364/TCP   19h
```

### Version

```prose
$ istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (5 proxies), 1.11.0 (1 proxies)
$ kubectl version --short
Client Version: v1.16.3
Server Version: v1.20.5
```

### Additional Information

The cluster was installed using kops and is inside of AWS.

[bug-report.tar.gz](https://github.com/istio/istio/files/7347535/bug-report.tar.gz)

**Comment by howardjohn** [comment]
> it tries to reach the service using k8s internal IP instead of the eastwestgateway external ip.

Unless you saw more info, such as envoy access logs, I don't see anyhting to suggest this. Curl will always show the IP of the DNS resolution, which will be captured and translated by envoy. So the curl logs do not indicate it did not go to the e/w external ip.

**Comment by howardjohn** [comment]
I think the TLS error is a red herring perhaps. See `[C113] connect timeout` in the logs.

Sounds like maybe they are not reachable.

make sure you followed the multi-network steps in the doc - in particular setting VM_NETWORK
