### ISSUE TITLE
proposal: make istio more friendly with Percentage Blue Green deployments 

### ISSUE THREAD

**Issue by sschepens** [istio/istio#35611]
**Describe the feature request**
At Mercadolibre we use Blue Green deployments with percentage traffic shifting to newer versions. This means we have the two versions up and running and gradually shift traffic to the newer version until it reaches 100% of the traffic, and only then we terminate the older version. We can expand more on why we do this if desired.
We also have use cases where a single service can be exposed in multiple VirtualServices and some cases where this could even scale to hundreds. We can also expand more on this.

Given this use case, currently in Istio, we would need to update all those VirtualServices specifying the traffic percentages to the given subsets, and do this for every step of the deployment where we progress the traffic shift. Doing this is cumbersome and requires lots of API calls to do.

Traffic Shifting between versions of a service is conceptually part of routing and makes sense to have it in VirtualService, but we think it generally makes sense to handle traffic shifting between versions of a service as a whole. If a services is exposed in even two VirtualServices it is kind of weird to be updating both at a time or have VirtualServices routing different weights to different versions.
So, we think, Istio should provide a more straight forward approach to shift traffic between multiple versions (subsets) of the same service.

**Describe alternatives you've considered**
We've thought a while about this and considered this could be probably implemented within `DestinationRule`, this is were subsets are specified, and subsets could be accompanied with their weight or percentage of traffic.
This would work by having VirtualServices targeting the entire service (not specifying individual subsets), and then having Istio notice this and generating a weighted clusters configuration to the subsets with the configurations specified in the `DestinationRule`.
If the `DestinationRule` does not contain traffic percentages or the `VirtualService` is targeting subsets, then current behaviours can be maintained, and so, backwards compatibility.

This approach seems pretty straight forward, but is probably using `DestinationRule` for things that it's not meant to be doing, as per the documentation, `DestinationRule` applies *after* traffic routing has occurred. But it might be tolerable, since `DestinationRule` also defines the targets (subsets) of routes.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by aweis89** [comment]
Have you evaluated rollout tools that integrate with Istio to do much of what you described like [Argo Rollouts](https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/) for example

**Comment by sschepens** [comment]
I was thinking of another Idea around this Issue using Envoy's Runtime Layers.

Envoy has the concept of Runtime Layers which can provide runtime values for thinks like traffic percentages, and this are provided through a separate XDS API.
We could expose in Istio a way to generate runtime values for traffic percentages, and be able to reference those values from a VirtualService. With this approach we would be able to reference the same Runtime Values from multiple Virtual Services and update the values of traffic routing without ever touching Virtual Services.

This seems like a good way to separate responsabilities, but it would involve adding a new Istio API for generating Runtime Values and modifying VirtualService to be able to reference Runtime Values. This could eventually prove useful for other features as well.

@howardjohn

**Comment by sschepens** [comment]
> Ok. Thanks for the details. Now I understand this better. So every time you want traffic shifting to happen in your proposal you update the Destination Rule with changed weights (if provided at subsets) and you are expecting Istio to update the corresponding Virtual Service or change routes with weighted clusters?

Yes, precisely


>  Not sure subsets in DR to add traffic shifting properties is the right approach? But I do not have any good alternative other than doing via updating VS with right weights?

Yes, I know it's probably not the right approach, but it seems the more straight forward. The other approach I mentioned about using Runtime Features could prove useful too and not messing with DR.

> Is your concern Istio route update scalability? I think we did similar large route updates for knative scenarios - @howardjohn has idea about knative scale.

We have 2 possible concerns:
- Our first and top concern is API Server scalability, since each deployment would trigger updates through lots of VirtualServices simultaneously, and several times in a row each time we want to update weights.
- Secondly, Route update scalability could be a concern, but it wouldn't be resolved with the DR approach I mentioned first. If we were to use Runtime Features, then this concern could be mitigated, because a change in weights would not trigger a change in Routes.

Apart from those concerns, it seems Istio is missing some concepts for handling traffic to a destination as a whole and also this types of Blue Green deployments.

Specifying weights in VirtualServices is good and provides lots of functionality but requires "manual" updates. When deploying a service progressively changing weights, you would want all routes pointing to that service to reflect the same weights at the same time and manage the service as a whole, no matter the amount of VirtualServices it is routed from.

If you take the example of Argo, it needs to be specified which VirtualService to update when performing a rollout, it doesn't even seem to provide support for updating multiple VirtualServices, which seems kind of restrictive. If we were to need to update multiple VS, then we would need to perform multiple rollouts or again, manually change them.

Instead, with our proposed approach, Argo could be able to just receive the DR (if that were the case) and don't even care what VS the services is routed from.

**Comment by howardjohn** [comment]
FWIW I think the disconnect is the vast majority of users have 1 or 2
(ingress + mesh) VS per service which is why this hasn't come up before.

**Comment by ramaraochavali** [comment]
> Secondly, Route update scalability could be a concern, but it wouldn't be resolved with the DR approach I mentioned first. If we were to use Runtime Features, then this concern could be mitigated, because a change in weights would not trigger a change in Routes.

Does Envoy have run time values for traffic weights already?  or are you proposing we add that support in routing components of Envoy?

**Comment by ramaraochavali** [comment]
nvm, looks like Envoy has that support already https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/traffic_splitting#traffic-splitting-across-multiple-upstreams

**Comment by sschepens** [comment]
Yes, Envoy already supports that, we're just setting a fixed value for the runtime feature probably.

We would probably need to add a Istio Resource for defining Runtime Values and be able to reference them from Route weights as well as a default value as we do today.

**Comment by sschepens** [comment]
@ramaraochavali @howardjohn what do you think of these proposals, could this be viable? should other people be involved in this discussion?

**Comment by sschepens** [comment]
@howardjohn @ramaraochavali We've found that it's possible to delegate routes to another VirtualService, that basically allows what we are proposing here.

We can create a VirtualService which only defines routes with weights for the service, and then just make every other VirtualServices delegate to this one.

**Comment by ramaraochavali** [comment]
@sschepens Cool. Thank you for the update. Would it be possible to share your VS and Delegate example so that any one coming to look at this can use it?
