### ISSUE TITLE
istio-policy-bot is closing valid bug reports

### ISSUE THREAD

**Issue by murphye** [istio/istio#35633]
### Bug Description

Please see this bug that I opened https://github.com/istio/istio/issues/33649

Other people chimed in and stated that they ran into this issue as well. Yet the issue was closed automatically by istio-policy-bot. This is is very unfortunate because it's a valid bug report and still needs to be fixed.

I would suggest changing istio-policy-bot to not automatically close Bug reports. Feature Requests might be a different matter.

Also, as the original bug reporter, I cannot reopen it myself.

### Version

```prose
N/A
```

**Comment by howardjohn** [comment]
There are a lot of opinions on stale bots and how they should work, etc. I like the wording on Kubernete's, which goes something like "Thanks for the bug report. Unfortunately, the maintainers don't have the bandwidth to address this issue". In particular, this applies here: see https://github.com/istio/istio.io/pull/10420.

**Comment by murphye** [comment]
@howardjohn Great point (i.e. deprecation of the Istio Operator that you linked to). As such, I will close this issue.
