### ISSUE TITLE
provider a http3 example in examples

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35638]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**
provider a http3 example in examples
**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by su225** [comment]
@howardjohn - Is Wiki page enough or does it need a documentation page?

**Comment by ldemailly** [comment]
Happy to see a wiki or blog or anything about h3 support in istio?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Experimental-QUIC-and-HTTP-3-support-in-Istio-gateways

**Comment by ldemailly** [comment]
awesome thanks!
