### ISSUE TITLE
connection refused ~ istio 1.9.0

### ISSUE THREAD

**Issue by blessedwithsins** [istio/istio#35640]
### Bug Description

I'm getting a connection refused while using a sample deployment and service and accessing it via istio-ingressgateway Load Balancer external IP. 

pigaur@DESKTOP-U5QGI09:~$ kubectl -n istio-system get po,svc
NAME                                       READY   STATUS    RESTARTS   AGE
pod/istio-egressgateway-65b9c8b54f-dk6pl   1/1     Running   0          13m
pod/istio-ingressgateway-56d9b7fdb-tsc6z   1/1     Running   0          13m
pod/istiod-89dc6db9c-pfjb6                 1/1     Running   0          13m

NAME                           TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                                                                      AGE
service/istio-egressgateway    ClusterIP      10.0.226.71   <none>          80/TCP,443/TCP,15443/TCP                                                     13m
service/istio-ingressgateway   LoadBalancer   10.0.173.71   20.98.177.170   15021:32472/TCP,80:31590/TCP,443:31554/TCP,31400:31319/TCP,15443:32594/TCP   13m
service/istiod                 ClusterIP      10.0.83.242   <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                                        13m
pigaur@DESKTOP-U5QGI09:~$

pigaur@DESKTOP-U5QGI09:~$ kubectl -n default get po,svc
NAME                              READY   STATUS    RESTARTS   AGE
pod/hello-world-85c8685dd-6vzrs   2/2     Running   0          69s

NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/hello-world   ClusterIP   10.0.190.248   <none>        80/TCP    69s
service/kubernetes    ClusterIP   10.0.0.1       <none>        443/TCP   2m52s
pigaur@DESKTOP-U5QGI09:~$

pigaur@DESKTOP-U5QGI09:~$ istioctl -n istio-system pc routes istio-ingressgateway-56d9b7fdb-tsc6z
NOTE: This output only contains routes loaded via RDS.
NAME        DOMAINS     MATCH                  VIRTUAL SERVICE
http.80     *           /*                     hello-world.default
            *           /healthz/ready*
            *           /stats/prometheus*
pigaur@DESKTOP-U5QGI09:~$

pigaur@DESKTOP-U5QGI09:~$ kubectl get vs -A
NAMESPACE   NAME          GATEWAYS      HOSTS   AGE
default     hello-world   ["gateway"]   ["*"]   2m23s
pigaur@DESKTOP-U5QGI09:~$

pigaur@DESKTOP-U5QGI09:~$ kubectl get svc -A
NAMESPACE      NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                      AGE
default        hello-world            ClusterIP      10.0.190.248   <none>          80/TCP                                                                       15m
default        kubernetes             ClusterIP      10.0.0.1       <none>          443/TCP                                                                      17m
istio-system   istio-egressgateway    ClusterIP      10.0.226.71    <none>          80/TCP,443/TCP,15443/TCP                                                     32m
istio-system   istio-ingressgateway   LoadBalancer   10.0.173.71    20.98.177.170   15021:32472/TCP,80:31590/TCP,443:31554/TCP,31400:31319/TCP,15443:32594/TCP   32m
istio-system   istiod                 ClusterIP      10.0.83.242    <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                                        32m
kube-system    kube-dns               ClusterIP      10.0.0.10      <none>          53/UDP,53/TCP                                                                7d1h
kube-system    metrics-server         ClusterIP      10.0.251.10    <none>          443/TCP                                                                      7d1h
pigaur@DESKTOP-U5QGI09:~$ curl -v 20.98.177.170
*   Trying 20.98.177.170:80...
* TCP_NODELAY set
* connect to 20.98.177.170 port 80 failed: Connection refused
* Failed to connect to 20.98.177.170 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 20.98.177.170 port 80: Connection refused
pigaur@DESKTOP-U5QGI09:~$
[yaml.zip](https://github.com/istio/istio/files/7358849/yaml.zip)

https://github.com/tetratelabs/istio-training/blob/main/labs/3-gateways.md

### Version

```prose
pigaur@DESKTOP-U5QGI09:~$ istioctl version
client version: 1.9.1
control plane version: 1.9.0
data plane version: 1.9.0 (4 proxies)
pigaur@DESKTOP-U5QGI09:~$ getmesh istioctl version
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (4 proxies)
pigaur@DESKTOP-U5QGI09:~$ kubectl version --short
Client Version: v1.22.0
Server Version: v1.20.9
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
pigaur@DESKTOP-U5QGI09:~$
```

### Additional Information

pigaur@DESKTOP-U5QGI09:~$ istioctl bug-report

Target cluster context: istio

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-10-17 10:28:25.9798187 +0530 IST

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.9.0", GitRevision:"b63e1966c245924b10a0915a671a656540ed7a45", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.9.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.9.0}

Fetching proxy logs for the following containers:

default/hello-world/hello-world-85c8685dd-6vzrs/istio-proxy
default/hello-world/hello-world-85c8685dd-6vzrs/svc
istio-system/istio-egressgateway/istio-egressgateway-65b9c8b54f-dk6pl/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-56d9b7fdb-tsc6z/istio-proxy
istio-system/istiod/istiod-89dc6db9c-pfjb6/discovery

Fetching Istio control plane information from cluster.

The following fetches are still running:
  kubectl describe pods -n istio-system
  ProxyGet default/hello-world-85c8685dd-6vzrs:clusters
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,monitoringdashboards.monitoring.kiali.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  ProxyGet istio-system/istio-egressgateway-65b9c8b54f-dk6pl:clusters
  ProxyGet istio-system/istio-ingressgateway-56d9b7fdb-tsc6z:clusters
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml
  PodExec istio-system/istiod-89dc6db9c-pfjb6/discovery:pilot-discovery request GET debug/cdsz

Running istio analyze on namespace istio-system.
Running istio analyze on namespace default.

Creating an archive at /home/pigaur/bug-report.tgz.
Cleaning up temporary files in /tmp/bug-report.
Done.
pigaur@DESKTOP-U5QGI09:~
[bug-report.zip](https://github.com/istio/istio/files/7358845/bug-report.zip)
$

**Comment by f3man** [comment]
The same behavior. I installed Istio using helm chart, right now I want to use Kubernetes Ingress without Istio Gateway but 
```bash
> curl -v istio-ingress.istio-ingress
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.0.67.49:80...
* connect to 10.0.67.49 port 80 failed: Connection refused
* Failed to connect to istio-ingress.istio-ingress port 80: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to istio-ingress.istio-ingress port 80: Connection refused
```
@blessedwithsins btw, it was a little bit difficult to read your issue, maybe if you format and structure it, then probably it will be solved faster

**Comment by zirain** [comment]
are you free to run the command as following, and share the output:
```bash
kubectl logs istiod-89dc6db9c-pfjb6 -nistio-system 
```

**Comment by zirain** [comment]
> @zirain
> 
> ```
> 2022-01-04T14:29:25.270367Z     info    ads     XDS: Pushing:2022-01-04T14:29:25Z/54 Services:13 ConnectedEndpoints:1  Version:2022-01-04T14:29:25Z/54
> 2022-01-04T14:29:25.270695Z     info    ads     CDS: PUSH for node:istio-ingress-5bd77ffbdf-2dlr2.istio-ingress resources:19 size:17.3kB cached:18/18
> 2022-01-04T14:29:25.270733Z     info    ads     LDS: PUSH for node:istio-ingress-5bd77ffbdf-2dlr2.istio-ingress resources:0 size:0B
> 2022-01-04T14:33:07.801325Z     info    Sidecar injection request for istio-ingress/istio-ingress-786f556bf-***** (actual name not yet known)
> 2022-01-04T14:33:10.106129Z     info    ads     ADS: new connection for node:istio-ingress-786f556bf-fwqh6.istio-ingress-387
> 2022-01-04T14:33:10.106625Z     info    ads     CDS: PUSH request for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:19 size:17.3kB cached:18/18
> 2022-01-04T14:33:10.119658Z     info    ads     EDS: PUSH request for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:18 size:4.0kB empty:0 cached:18/18
> 2022-01-04T14:33:10.141839Z     info    ads     LDS: PUSH request for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:0 size:0B
> 2022-01-04T14:33:11.653598Z     info    ads     CDS: PUSH for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:19 size:17.3kB cached:18/18
> 2022-01-04T14:33:11.653740Z     info    ads     EDS: PUSH for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:18 size:4.0kB empty:0 cached:18/18
> 2022-01-04T14:33:11.653791Z     info    ads     LDS: PUSH for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:0 size:0B
> 2022-01-04T14:33:11.810382Z     info    ads     Push debounce stable[68] 2 for config ServiceEntry/istio-ingress/istio-ingress.istio-ingress.svc.cluster.local: 100.12262ms since last change, 150.294583ms since last push, full=false
> 2022-01-04T14:33:11.810502Z     info    ads     XDS: Incremental Pushing:2022-01-04T14:29:25Z/54 ConnectedEndpoints:2 Version:2022-01-04T14:29:25Z/54
> 2022-01-04T14:33:16.709096Z     info    ads     ADS: "172.16.0.142:44454" istio-ingress-5bd77ffbdf-2dlr2.istio-ingress-386 terminated rpc error: code = Canceled desc = context canceled
> 2022-01-04T14:36:53.618603Z     info    ads     Push debounce stable[69] 1 for config VirtualService/istio-ingress/istio-vs: 100.368158ms since last change, 100.367858ms since last push, full=true
> 2022-01-04T14:36:53.619569Z     info    ads     XDS: Pushing:2022-01-04T14:36:53Z/55 Services:13 ConnectedEndpoints:1  Version:2022-01-04T14:36:53Z/55
> 2022-01-04T14:36:53.620120Z     info    ads     CDS: PUSH for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:19 size:17.3kB cached:15/18
> 2022-01-04T14:36:53.620317Z     info    ads     LDS: PUSH for node:istio-ingress-786f556bf-fwqh6.istio-ingress resources:0 size:0B
> ```
> 
> **Note**: I've just added virtual service and gateway but anyway it doesn't work. It looks like it needs a sidecar, but for me now the way with just simple ingress is preferred

I have check all the output file, but found no error there, suspect that something wrong with you ELB?

**Comment by zirain** [comment]
If there's something wrong with gateway or vs, there should contains some `NR` access log in ingressgateway pod.
