### ISSUE TITLE
istio-proxy(envoy) memory leak

### ISSUE THREAD

**Issue by liuxu623** [istio/istio#35644]
### Bug Description

istio-proxy memory leak

### Version

```prose
istio version: 1.10.3
envoy version: 4b528a87271e841bd64daf841a1a384ed4fcac68/1.18.4-dev/Clean/RELEASE/BoringSSL
```

### Additional Information

![image](https://user-images.githubusercontent.com/9653438/137664333-263197d3-3189-45ad-8b4a-d95c96fbfb90.png)

![wecom-temp-0f78d01afc13ffb8c03f9587ac23483b](https://user-images.githubusercontent.com/9653438/137664426-f2ae3474-d5b1-404a-8a5c-4a43ef56f1d5.png)

[profile001.pdf](https://github.com/istio/istio/files/7361601/profile001.pdf)

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
What does /clusters look like? Seems like most of the memory is in original dst, maybe either your app is keeping connection open to growing number if connections or envoy is not freeing then somehow

**Comment by liuxu623** [comment]
> What does /clusters look like? Seems like most of the memory is in original dst, maybe either your app is keeping connection open to growing number if connections or envoy is not freeing then somehow

@howardjohn There are only 21 svc in cluster，and this app request many outside cluster ip via PassthroughCluster, but app doesn't keep connections open.

**Comment by liuxu623** [comment]
@howardjohn https://gist.github.com/liuxu623/c5dff6014b2218c10ea334253fa40312

**Comment by howardjohn** [comment]
Ok so it only has 39 active hosts, definitely shouldn't use that much
memory. Sounds like it may be a classic memory leak rather than holding
onto the ephemeral hosts too long. Likely we will need to get some Envoy
experts (of which I am not) involved

**Comment by liuxu623** [comment]
I can use a simple client reproduce this BUG.

**Comment by liuxu623** [comment]
@howardjohn Sorry, I forgot to disable keep alive

```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	hosts := []string{
		"1.117.136.170",
		"175.24.155.92",
		"150.158.223.124",
		"42.192.253.145",
		"42.192.63.186",
		"1.15.158.157",
		"81.69.154.12",
		"1.117.136.250",
		"150.158.218.24",
		"81.69.166.240",
	}

	t := http.DefaultTransport.(*http.Transport).Clone()
	t.DisableKeepAlives = true
	c := &http.Client{Transport: t}

	for {
		for port := 8000; port < 8100; port++ {
			for _, host := range hosts {
				c.Get(fmt.Sprintf("http://%s:%d", host, port))
				log.Println(fmt.Sprintf(" Get http://%s:%d", host, port))
			}
		}
	}
}
```

**Comment by mrkm4ntr** [comment]
I think this feature might resolve this. https://github.com/envoyproxy/envoy/pull/17577

**Comment by Umenezumi** [comment]
How is it finally solved?
