### ISSUE TITLE
Isotope clients should use client side keep-alive

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#35677]
https://github.com/istio/tools/tree/master/isotope/service

We have observed that when isotope is deployed as a "tcp" service by declaring the port as tcp, we see an enormous "new tcp connection" creation rate. This should be fixed.
Additionally if we can use a service like mysql it would be even better a last mile tcp service.

**Comment by mandarjog** [comment]
cc @richardwxn

**Comment by howardjohn** [comment]
its _supposed_ to https://github.com/istio/tools/blob/ba5896b1eb6542688ff18c70559dbc7e4c2344ce/isotope/service/pkg/srv/executable.go#L92-L95. Not sure if it works

**Comment by richardwxn** [comment]
Do we need to use ioutil.ReadAll(response.Body) for all response? Seems like it is called for error case now only

**Comment by howardjohn** [comment]
I don't think you need to since recent golang versions? I could be wrong. if we do, you can use `io.Discard` though

**Comment by richardwxn** [comment]
I am not sure either. yep I think we can use io.Discard to see whether it can fix the problem
