### ISSUE TITLE
Support for applying Request Authentication to specific routes

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#35698]
Currently if we apply RequestAuthentication (JWT) to Ingress, it applies to all routes because we match with any [prefix](https://github.com/istio/istio/blob/c017654753cd8f4254abbe0567ff9c728d2034d2/pilot/pkg/security/authn/v1beta1/policy_applier.go#L295)

However, for Ingress it is desirable to scope it to certain routes so that only services that need JWT validation gets that feature. 

The request is to support this requirement rule in Istio
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-requirementrule

Alternative:

Envoy filter to apply this rule but this seems generic enough to add it to JWTRules.

**Comment by ramaraochavali** [comment]
@yangminzhu WDYT?

**Comment by yangminzhu** [comment]
thanks for the notice.

Do you see any issues for RA applying to all routes? By default it only validates JWT if it exists and will not do anything if it doesn't have any JWT. If so, why do we want it to be specific route?

**Comment by yangminzhu** [comment]
I think @howardjohn has done some investigations for a different way to attach RA or AuthZ to the new gateway-api, might be related here.

**Comment by ramaraochavali** [comment]
@yangminzhu Thank you. I did not know that JWT filter is a no-op if JWT does not exist.  It may be fine then

Will wait for @howardjohn's reply though

**Comment by howardjohn** [comment]
I did only look at authz. Does envoy support jwt at the route level even?

**Comment by howardjohn** [comment]
Oh nevermind I see there is a match.

IMO duplicating the matching in the filter is not a great design for this particular use case and will lead to mismatches, complexity, etc. Better would be to bind to a route which already has (much richer) matching. Authz does allow this

**Comment by ramaraochavali** [comment]
> IMO duplicating the matching in the filter is not a great design for this particular use case and will lead to mismatches, complexity, etc. Better would be to bind to a route which already has (much richer) matching. Authz does allow this.

Are you suggesting some thing similar to this https://github.com/istio/api/blob/master/security/v1beta1/authorization_policy.proto#L323?

**Comment by ramaraochavali** [comment]
Ok. That  makes sense to attached JWT rules to VS

**Comment by chinaran** [comment]
> Ok. That makes sense to attached JWT rules to VS

+1
