### ISSUE TITLE
helm install doesn't work at all

### ISSUE THREAD

**Issue by d02540315** [istio/istio#35692]
### Bug Description

Hi,
![image](https://user-images.githubusercontent.com/5162421/138174713-f8963646-d90e-493b-b96e-0c0e377fb64a.png)

By following the doc here: https://github.com/istio/istio/tree/master/manifests/charts/base, but helm install doesn't work at all. The chart seems cannot be found.

### Version

```prose
$ istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (8 proxies)
```

### Additional Information

![image](https://user-images.githubusercontent.com/5162421/138174924-1ae5f9f2-b72e-44ca-8343-ff81f60f7c03.png)

**Comment by AndreyRomanchev** [comment]
Same issue with gateway installation.
@howardjohn if you look into helm values from istio/gateway you will get some default values which helm generates with new release.
```helm show values istio/gateway --devel```
Nothing similar to actual values like https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml

**Comment by howardjohn** [comment]
You are lookingat the wrong chart, should be looking at https://github.com/istio/istio/tree/master/manifests/charts/gateway

**Comment by AndreyRomanchev** [comment]
Wow, ok, my bad, sorry.
Does this mean that gateways/istio-ingress is obsolete?

**Comment by MaksatKK** [comment]
Hi, have same problem in terraform helm provider. Solved by specifying "devel = true" and changing chart name from "istio/base", "istio/istiod" to "base", "istiod". 

version - 1.12.0

![image](https://user-images.githubusercontent.com/20191189/144610992-659b5811-6058-4f09-ad54-277ea37deb85.png)

**Comment by howardjohn** [comment]
You shouldn't need `devel` now that 1.12.0 was released. But also probably
shouldn't hurt

**Comment by batazor** [comment]
@howardjohn I'm still getting messages like:

```bash
$> helm show values istio/gateway
Error: failed to download "istio/gateway"

$> elm show values istio/base   
Error: failed to download "istio/base"
```

**Comment by howardjohn** [comment]
did you add the repo and run `helm repo update`?maybe check `helm repo ls`

**Comment by batazor** [comment]
@howardjohn Yes, I looked it up, there was an old repository

```
https://storage.googleapis.com/istio-release/releases/1.5.4/charts/
```

**Comment by northonheld** [comment]
For me it also worked when I left the chart name only base. Please, is it possible to update some documentation with this information? I think more people will have the same doubt
![Screen Shot 2022-02-09 at 00 20 06](https://user-images.githubusercontent.com/19438736/153115787-5b14cd7d-2c1f-4ea5-b00b-a6652f448982.jpg)
.

**Comment by howardjohn** [comment]
What doc do you expect to be updated? The name of the chart is "base", and as far as I know is not documented as istio-base anywhere...?

**Comment by northonheld** [comment]
> What doc do you expect to be updated? The name of the chart is "base", and as far as I know is not documented as istio-base anywhere...?

This documentation https://istio.io/latest/docs/setup/install/helm/ It speaks only in istio/base. And that's confusing. I was trying to put the chart name as istio/base and not just base. Please, if there is other documentation indicating only the name "base" could you show me?

**Comment by howardjohn** [comment]
Helm charts are namespaces by repo. There is a repo - "istio" and a chart name - "base". In helm it's referenced as istio/base. In terraform it looks like your don't refer to a repo by name but rather by url, but it's the same thing really.

**Comment by northonheld** [comment]
> Helm charts are namespaces by repo. There is a repo - "istio" and a chart name - "base". In helm it's referenced as istio/base. In terraform it looks like your don't refer to a repo by name but rather by url, but it's the same thing really.

Ok, thank you very much for your explanation. I really appreciate it.

**Comment by tirelibirefe** [comment]
Error: could not download chart: chart "istio-official/base" version "1.23.3" not found in https://istio-release.storage.googleapis.com/charts repository

**Comment by howardjohn** [comment]
> `Error: could not download chart: chart "istio-official/base" version "1.23.3" not found in https://istio-release.storage.googleapis.com/charts repository`

`helm template istio/base --version 1.23.3` works for me. Did you run `helm repo update`?
