### ISSUE TITLE
Raw VM support

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#357]

**Comment by rozhok** [comment]
Does this feature mean that we won't need k8s to operate?

**Comment by ldemailly** [comment]
in 0.2 you will still need k8s but not in 0.3

**Comment by rstml** [comment]
@ldemailly is there already issue for that? was wondering about implementation details.

**Comment by ldemailly** [comment]
I don't think we have setup the detailed issues/epics for 0.3 (as we're working on 0.2)

but the plans are fairly simple so let me create one and link it here

**Comment by sakshigoel12** [comment]
@costinm @ldemailly anything blocking the release here?

**Comment by ldemailly** [comment]
I think we're good to go (we will continuously improve doc and scripts as we get feedback)
