### ISSUE TITLE
Automatic injection (webhook) not working

### ISSUE THREAD

**Issue by overip** [istio/istio#3570]
Is this a BUG or FEATURE REQUEST?:
BUG
Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?:
yes
Bug:
Y

What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details

istioctl version : 0.5.0
kubectl version : 1.9.3

istioctl version : 0.5.1
kubectl version : 1.9.3

Is Istio Auth enabled or not ?
Did you install istio.yaml, istio-auth.yaml....
Not enabled. I installed istio using istio.yaml

What happened:
Sidecar injection is installed without error, but when I deploy a container, the sidecar does not get automatically injected.

What you expected to happen:
Sidecar injection should be successful, and I am supposed to see the sidecar deployed.

How to reproduce it:
On AWS :
Install Kubernetes 1.9.3 using the official tutorial.
Download and apply istio.yaml
Generate cert with : ./install/kubernetes/webhook-create-signed-cert.sh \ --service istio-sidecar-injector \ --namespace istio-system \ --secret sidecar-injector-certs
Apply configmap : kubectl apply -f install/kubernetes/istio-sidecar-injector-configmap-release.yaml
Add caBundle : cat install/kubernetes/istio-sidecar-injector.yaml | \ ./install/kubernetes/webhook-patch-ca-bundle.sh > \ install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
Apply sidecar : kubectl apply -f install/kubernetes/istio-sidecar-injector-with-ca-bundle.yaml
Label default namespace: kubectl label namespace default istio-injection=enabled
Deploy test app: kubectl apply -f samples/sleep/sleep.yaml 
Check that the sidecar is deployed: kubectl get pod
The sidecar is not deployed as showed by the output of the last command.

Feature Request:
N

Describe the feature:

**Comment by sdake** [comment]
I can only duplicate this if the instructions are not followed.  For example, I deploy with kubeadm which in the default settings does not set the requirements
```
 Specifically, verify that the kube-apiserver process has the admission-control flag set with the MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission controllers added and listed in the correct order.
```

From the automatic sidecar documentation.

**Comment by ayj** [comment]
@overip, can you confirm that the cluster was created with admission controllers configured as noted in the docs? It would also be good to verify that the sidecar-injector pod is started before created the sample pod. The default webhook fails open which means injection may be bypassed if the injector pod isn't available (yet). This issue is addressed by https://github.com/istio/istio/pull/3724

**Comment by overip** [comment]
That fixed my problem, thank you.

**Comment by fudali113** [comment]
May I ask how you solved it?
I didn`t understand the content of [issue#3724](https://github.com/istio/istio/pull/3724)
@overip

**Comment by rahulm95** [comment]
@fudali113  While creating the cluster, you need to set the flags MutatingAdmissionWebhook, ValidatingAdmissionWebhook to true.
