### ISSUE TITLE
vm support: VM health checks do not work for those VMs that are not using auto-registration

### ISSUE THREAD

**Issue by yskopets** [istio/istio#35702]
### Bug Description

As of `Istio 1.11`, VM health checks only work for those VMs that use auto-registration.

If a VM has been added to the mesh without using auto-registration, health checks sent by the VM get ignored.

Specifically, the following error message appears in the log of `istiod` when the VM sends health check update:

```shell
error	wle	unable to derive WorkloadEntry for health update for my-vm.bookinfo
```

IIUC, the error originates at [these lines](https://github.com/istio/istio/blob/65df68a0d0c8dbe6c70c1fd73a2f46bab53be3cb/pilot/pkg/controller/workloadentry/workloadentry_controller.go#L410-L419):

```go
// QueueWorkloadEntryHealth enqueues the associated WorkloadEntries health status.
func (c *Controller) QueueWorkloadEntryHealth(proxy *model.Proxy, event HealthEvent) {
	// we assume that the workload entry exists
	// if auto registration does not exist, try looking
	// up in NodeMetadata
	entryName := autoregisteredWorkloadEntryName(proxy)
	if entryName == "" {
		log.Errorf("unable to derive WorkloadEntry for health update for %v", proxy.ID)
		return
	}
```

Could you please clarify whether health checks for VMs that are not using auto-registration will be supported in future versions of Istio?

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.0 (1 proxies), 1.11.4 (2 proxies)

$ kubectl version --short
Client Version: v1.19.1
Server Version: v1.21.5-gke.1300
```

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by yskopets** [comment]
@hzxuzhonghu Please see a proposed PR to add this feature - #35702
