### ISSUE TITLE
multi-network: use custom IP for NodePort gateway

### ISSUE THREAD

**Issue by Tristan971** [istio/istio#35707]
**Describe the feature request**
Assuming a multi-primary multi-network mesh, with a network topology as follows:

![istio-multinet-nodeport drawio](https://user-images.githubusercontent.com/875533/138339294-fbf051b2-e051-4330-9aa9-aa5029d7a948.png)

One might work on baremetal without access to LoadBalancer type services (whether the usual cloud-provider-based ones or alternatives like MetalLB). Thus using NodePort as service type for the east-west gateways.

However there doesn't appear to be a way to override the "remote" IP of the east-west gateways, which in this case other clusters need to be able to route traffic across network boundaries.

I raise this issue after a short exchange with @stevenctl on the Slack's #multi-cluster channel.
There he suggested there is a good chance that even manually setting the Service's ExternalIPs field on the eastwest gateway 
service would not necessarily work as Istio might prefer the Node IP in all cases where NodePort service type is used.

> I tried this out unsuccessfully, albeit I'm not experienced enough with Istio to be sure the lack of eastwest traffic using the ExternalIPs field isn't due to some other misconfiguration of mine...

That also begs a similar question around which of the node's IPs would even be chosen, in case a node has multiple and the "default" k8s one is not the one remote clusters can access. (which is also one reason I can't "just" expose a node publicly reliably either in this case)

It would seem like a similar problem has been solved with the `networking.istio.io/gatewayPort` annotation for the announced port (although I was unable to find any documentation about this annotation), and it'd be great if one of:
- `networking.istio.io/gatewayAddress` (ideally supporting multiple IPs or a hostname but a single IP would be a good start)
- `Service#ExternalIPs`

Was supported on the eastwest gateway services as "hard" overrides to what address remote clusters should use to route eastwest traffic.

**Describe alternatives you've considered**

A few alternatives exist:

Maintaining a precise network topology using the `meshNetworks` configmap key:
- this is somewhat difficult/tedious to use properly and keep in sync
- this is also discouraged in the (spare) bits of documentation on the topic, partially from being helm-passthrough dependent (afaik) and somewhat inelegant in comparison of the "self-announcing" way

Using some kind of "manual" LoadBalancer Service faking a cloud provider's:
- I'm sure it exists although I'm not aware of any such solution
- It seems like a lot of ceremony for the intended end-goal

Using MetalLB:
- Requires some level of BGP capacity where deployed
- One might also very much not want to directly expose all of the worker nodes ports directly (since a few common things tend to run on host network and firewalling worker nodes is error-prone and generally not really worth it vs isolating the network altogether)

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I added "docs" as affected since at the very least the documentation becomes very sparse for any use-case without access to LoadBalancer-type services.

**Comment by stevenctl** [comment]
Seems like this should be closed then?
