### ISSUE TITLE
Evaluate whether an expression cache would be valuable in Mixer

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#3572]
Mixer evaluates a fair number of expressions for every incoming requests. The result of expression evaluation is fully determined based on the incoming set of attributes. We could therefore construct a cache of {attribute set->expression result} in order to avoid evaluating these expressions at all in common cases.

Is there enough evaluation of identical expressions for this to be worth it? Is the work done during evaluation significant enough to warrant a cache at all? Does expression evaluation play a significant enough role in our overall execution time to warrant investments here?

Perhaps we can assess whether expression caching is worthwhile on a per-expression basis at config time. Complex expressions would be worth it, simple expressions could be evaluate every time.

Anyway, lots of fun topics to explore.

**Comment by ozevren** [comment]
Just for attributes, I am worried that the cost of the cache itself will be within the same ballpark of evaluating the attributes themselves.

Perhaps a better caching strategy is for {attr -> instance} given instances are a pure function of expression results (and the current config). Do we have a bug for that?

**Comment by geeknoid** [comment]
I agree that the overhead of forming a cache key and doing the cache lookup may in fact make caching here not worth it. There are variations to consider. For example, perhaps we consider the relative complexity of expressions at config time and then decide up front on a case-by-case basis which expressions would have a cache in front of them and which wouldn't.

I just opened #3623 to track having a cache for instances. I don't know how effective that would be though. How often are the exact same instances produced?
