### ISSUE TITLE
Pod to pod traffic classified as Passthrough Cluster even if destination_workload is a non-unknown name

### ISSUE THREAD

**Issue by MugenTwo** [istio/istio#35726]
### Bug Description

Continuing the discussion that I had in Kiali's GItHub forum: https://github.com/kiali/kiali/discussions/4454

I have a Spring Boot Admin Server pod doing direct requests to pods (e.g. health checks) and these requests are being classified as PassthroughCluster even when Istio seems to have info about the connection (destination_workload).

Istio is sending the correct **destination_workload** ("o-services" in the image attached). But, the **destination_service_name** is being sent as PassthroughCluster which then translates to an unnecessary node and a lot more of edges in the graph view of Kiali.
![kiali-a](https://user-images.githubusercontent.com/17546545/138714939-65b83ae8-ef0d-4618-bcf5-d292fbed7bd6.png)

Is this perhaps an intended functionality? What do you think the telemetry should look like when not sending requests to a service but instead going directly to a pod?

I understand that Istio is a "Service" mesh but I think it's interesting to address these kind of situations as they are common use cases when there is a client-side load balancing (e.g. Ribbon) or when using Spring Boot Admin Server.

And as it currently stands, it is very hard to understand the graph in Kiali as, for example, Spring Boot Admin Server has a direct interaction with the a lot pods without going through a K8s Service or a VirtualService. 

For example:
1. It is hard to understand which connection is unhealthy in the graph.
2. When you apply a hide filter on Spring Boot Admin Server in Kiali, you can still see the PassthroughCluster. And if you hide the PassthroughCluster you might hide unrelated connections that are actually coming from an external connection.

### Version

```prose
➜  ~ istioctl version
client version: 1.11.4
control plane version: 1.10.3
data plane version: 1.10.3 (93 proxies)
➜  ~ istioctl version --short
client version: 1.11.4
control plane version: 1.10.3
data plane version: 1.10.3 (93 proxies)
```

**Comment by bianpengyuan** [comment]
This is intended behavior. You can reduce the edge by disabling host header fallback at outbound with https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics, which will stop using pod ip as destination service, but instead just use `unknown`.

**Comment by MugenTwo** [comment]
Hi @bianpengyuan ! Thanks for the answer! I've communicated it with Kiali folks (in the same thread as the one I've linked), suggesting to them that this could be better represented with a new arrow color because unknown or PassthroughCluster is not really ideal to see in a graph for these kind of scenarios.

**Comment by bianpengyuan** [comment]
Ok, looks like Kiali is opening an enhancement for this. Close since this works as intended. Thanks!
