### ISSUE TITLE
IstioOperator is not in client-go

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#35736]
### Bug Description

It is not possible to use client-go to easily access IstioOperator resources.

The IstioOperator resource is defined in https://github.com/istio/istio/blob/f6b648fff750beeff9aa19acc5d43f1242ab3b67/operator/pkg/apis/istio/v1alpha1/operator_crd.pb.go#L28-L39

It is not in istio/api, so I can not generate client in client-go.

PS: the proto file of operator_crd can not find.

### Version

```prose
latest version
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by vicoooo26** [comment]
The current DeepCopy implementation of IstioOperator does not work perfect.
You can turn to these two issues [25584](https://github.com/istio/istio/issues/25584), [24829](https://github.com/istio/istio/issues/24829) and this closed pr [209](https://github.com/istio/client-go/pull/209) for more information.
