### ISSUE TITLE
Set concurrency of Istio components

### ISSUE THREAD

**Issue by necatican** [istio/istio#35751]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We want to be able to set the concurrency of ingress-gateway. 

**Describe alternatives you've considered**
We can either use Kustomize or override the manifests folder to set the concurrency. However, both of these methods are just workarounds.

**Affected product area (please put an X in all that apply)**

- [ ] Docs
- [x] Installation
- [x] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Multi Control Plane

**Additional context**
We should be able to pass the `--concurrency` flag to ingress-gateway [args](https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L108).  [Istio proxy](https://github.com/istio/istio/blob/8ce0defcc905873dadf3fa1d8c3f3629cd39895c/pilot/cmd/pilot-agent/main.go#L66) supports this feature. 

In theory, by setting `meshConfig.defaultConfig.concurrency`, we should be able to set the concurrency for every Istio component.

This is a simple fix, and we've came up with two solutions.
1. Use`meshConfig.defaultConfig.concurrency` value in ingress-gateway. This might introduce some unwanted side effects.
```yaml
        {{- if .Values.meshConfig.defaultConfig.concurrency}}
          - --concurrency={{ .Values.global.proxy.concurrency }}
        {{- end }}
```

2. Use `gateways.istio-ingressgateway.concurrency` to separate the config from other components. This is more flexible and will not include any breaking changes.
```yaml
        {{- if $gateway.concurrency }}
          - --concurrency={{ $gateway.concurrency }}
        {{- end }}
```

@Dentrax

**Comment by eliavem** [comment]
Hi @Dentrax, I have tested with proxyv2 1.13-alpha. I modified istio ingress concurrency through annotation and also through mesh config. Both ways seem to modify ingress concurrency. Is there something I'm missing? 

<img width="899" alt="Screen Shot 2021-11-04 at 1 34 47 PM" src="https://user-images.githubusercontent.com/64979576/140421663-4abb2d90-547a-4285-b8d1-c7d51f534a3a.png">

**Comment by Dentrax** [comment]
> Hi @Dentrax, I have tested with proxyv2 1.13-alpha. I modified istio ingress concurrency through annotation and also through mesh config. Both ways seem to modify ingress concurrency. Is there something I'm missing? 

>  Hi! Thanks for the feedback. We are currently using `proxyv2/1.8.5`. I am not sure whether it's due to version or the way we are passing it wrong. Do you mind share the instructions you followed so we can compare the differences and check if what we are doing wrong.

**Comment by eliavem** [comment]
I have installed Istio locally on Minikube.

Modify Mesh Config: 
1. `istioctl install --set profile=minimal --set meshConfig.defaultConfig.concurrency=4`

2. Then I install Ingress and other apps. All get modified with the concurrency I specify 

Modify only ingress workload:
1. `istioctl install --set profile=minimal`

2. Add annotation to ingress deployment 
<img width="511" alt="Screen Shot 2021-11-04 at 3 37 48 PM" src="https://user-images.githubusercontent.com/64979576/140429928-d0243304-8781-4491-aba3-20032a45265e.png">

I have also tried this with istio/proxyv2:1.11.3

**Comment by linsun** [comment]
Hi @eliavem thanks for trying this!  Could you also try setting it as a pod annotation, e.g. proxy.istio.io/config: 'concurrency: 5' and check if the generated deployment/pod yaml has concurrency configured properly in the proxyv2 container?  Changing meshConfig is applying to every single proxy in the mesh, which would not be what you wanted most times if you just want to change it on the ingress gateway, which is why @necatican opened this.

It is possible this may be fixed in newer Istio, if so, we could close this issue.

**Comment by eliavem** [comment]
@linsun under "Modify only ingress workload" I show how to do it through annotations. In config_dump, the concurrency get changed only for ingress pod

**Comment by linsun** [comment]
Ah thank you @eliavem, I missed that.  I think this issue can be safely closed as it is fixed in newer Istio.
