### ISSUE TITLE
Istio dual-stack support at ingress

### ISSUE THREAD

**Issue by umeshbhandari** [istio/istio#35781]
**### Kubernetes are supporting the dual-stack:: 
https://kubernetes.io/docs/concepts/services-networking/dual-stack/**

We also need a dual-stack support for **Istio ingress traffic** in Kubernetes dual-stack clusters.
Currently, IPV6 or IPV4 is only supporting
Internal traffic handled by Istio is still single-stack using the K8s default family (the one you get if the ipFamily is not explicitly specified in the manifest).

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Dual Stack

**Expected behavior**
_The stats listener should listen on both IPv4 and IPv6 in a dual-stack environment_

**K8s dual-stack**
The service can be specified to support dual-stack traffic to the istio-ingressgateway with two IP's at LoadBalance i.e. one IPV4 and other one IPV6

apiVersion: v1
kind: Service
metadata:
  name: istio-dual
  namespace: istio-system
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
  type: LoadBalancer

**Comment by jacob-delgado** [comment]
This is currently being worked on and will be presented to various groups soon. There is no ETA for when it will be completed. Included is a reference implementation of a working system in Istio 1.9.

[config_dump.json.zip](https://github.com/istio/istio/files/8137576/config_dump.json.zip)

**Comment by sronanrh** [comment]
Is there any update on the target release for Dual Stack Ingress support?

**Comment by zhlsunshine** [comment]
Hi @sronanrh, you can use the experimental branch [here](https://github.com/istio/istio/tree/experimental-dual-stack) for your dual stack support. For master branch, I think you can focus on this issue: https://github.com/istio/istio/issues/40394

**Comment by zhlsunshine** [comment]
There is a [PR#42712](https://github.com/istio/istio/pull/42712) for ingress gateway support got merged

**Comment by howardjohn** [comment]
close per https://github.com/istio/istio/pull/42712. Thanks!
