### ISSUE TITLE
no kind "Gateway" is registered for version "networking.istio.io/v1beta1" in scheme

### ISSUE THREAD

**Issue by zerzhir** [istio/istio#35796]
### Bug Description

k8s version： v1.22.2
istio version: 1.11.4

when I apply gateway, gateway created but not work,
kubectl logs gateway/XXXX report the error:

error: no kind "Gateway" is registered for version "networking.istio.io/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

### Version

```prose
# istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (2 proxies)

# kubectl version --short
Client Version: v1.22.2
Server Version: v1.22.2

# helm version --short
v3.7.0+geeac838
```

**Comment by howardjohn** [comment]
`kubectl logs gateway/` is not a valid command. You can only get logs from pods.

**Comment by hzxuzhonghu** [comment]
This is a misuse of kubectl cmd, and kubectl error log is not obvious.
