### ISSUE TITLE
arm64 architecture missing from ingress and egress gateway deployment manifest

### ISSUE THREAD

**Issue by gpsingh-1991** [istio/istio#35794]
### Bug Description

The arm64 CPU architecture is missing in the list of architectures provided in node affinity for ingress and egress gateway deployments. This makes the ingress and egress gateway pods stuck in the pending state because the node affinity condition does not match. The pods report following error:

'0/1 nodes are available: 1 node(s) didn''t match Pod''s node affinity/selector.'

Here is the describe output from one of the pods:

`kubectl  describe pod -n istio-system istio-ingressgateway-8f568d595-pqn88
Name:           istio-ingressgateway-8f568d595-pqn88
Namespace:      istio-system
Priority:       0
Node:           <none>
Labels:         app=istio-ingressgateway
                chart=gateways
                heritage=Tiller
                install.operator.istio.io/owning-resource=unknown
                istio=ingressgateway
                istio.io/rev=default
                operator.istio.io/component=IngressGateways
                pod-template-hash=8f568d595
                release=istio
                service.istio.io/canonical-name=istio-ingressgateway
                service.istio.io/canonical-revision=latest
                sidecar.istio.io/inject=false
Annotations:    prometheus.io/path: /stats/prometheus
                prometheus.io/port: 15020
                prometheus.io/scrape: true
                sidecar.istio.io/inject: false
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/istio-ingressgateway-8f568d595
Containers:
  istio-proxy:
    Image:       docker.io/istio/proxyv2:1.10.3
    Ports:       15021/TCP, 8080/TCP, 8443/TCP, 31400/TCP, 15443/TCP, 15090/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
      --serviceCluster
      istio-ingressgateway
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      10m
      memory:   40Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                   third-party-jwt
      PILOT_CERT_PROVIDER:          istiod
      CA_ADDR:                      istiod.istio-system.svc:15012
      NODE_NAME:                     (v1:spec.nodeName)
      POD_NAME:                     istio-ingressgateway-8f568d595-pqn88 (v1:metadata.name)
      POD_NAMESPACE:                istio-system (v1:metadata.namespace)
      INSTANCE_IP:                   (v1:status.podIP)
      HOST_IP:                       (v1:status.hostIP)
      SERVICE_ACCOUNT:               (v1:spec.serviceAccountName)
      CANONICAL_SERVICE:             (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:            (v1:metadata.labels['service.istio.io/canonical-revision'])
      ISTIO_META_WORKLOAD_NAME:     istio-ingressgateway
      ISTIO_META_OWNER:             kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
      ISTIO_META_MESH_ID:           cluster.local
      TRUST_DOMAIN:                 cluster.local
      ISTIO_META_UNPRIVILEGED_POD:  true
      ISTIO_META_ROUTER_MODE:       standard
      ISTIO_META_CLUSTER_ID:        Kubernetes
    Mounts:
      /etc/istio/config from config-volume (rw)
      /etc/istio/ingressgateway-ca-certs from ingressgateway-ca-certs (ro)
      /etc/istio/ingressgateway-certs from ingressgateway-certs (ro)
      /etc/istio/pod from podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m5v48 (ro)
      /var/run/secrets/tokens from istio-token (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
      limits.cpu -> cpu-limit
      requests.cpu -> cpu-request
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  true
  ingressgateway-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-certs
    Optional:    true
  ingressgateway-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-ca-certs
    Optional:    true
  kube-api-access-m5v48:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  50s (x3 over 2m1s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector.`

### Version

```prose
istioctl  version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (2 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by howardjohn** [comment]
We don't publish arm64 images so I would not expect the deployment to claim arm64 is supported?

**Comment by gpsingh-1991** [comment]
I see arm64 related tar files available. What are those for? Does that only depend on istioctl? If yes, is the target cluster supposed to be running only amd64, s390x and ppc64le architectures?

**Comment by howardjohn** [comment]
Yeah it's for istioctl only

We only publish amd64 so I don't know why those other architectures are there tbh

**Comment by gpsingh-1991** [comment]
Is there a doc somewhere in this repository which has all these details related to hardware requirements?

**Comment by zackzhangkai** [comment]
@gpsingh-1991 In the fact, maybe next release will add the node affinity/selector `beta.kubernetes.io/arch:arm64`, Refer https://github.com/istio/istio/pull/35648. 

In addition, you can set this in the operator cr, such as :


```bash
$ kubectl -n istio-system get iop -oyaml 
...
spec:
    components:
      ingressGateways:
      - enabled: true
        k8s:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - arm64
                    - amd64
                weight: 2
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - arm64
                    - amd64
```

**Comment by gpsingh-1991** [comment]
Hi @zackzhangkai , thank you for the work around. I already applied this when I got stuck here but, the arm64 tar in release is misleading or incomplete without this change being present there.

**Comment by wind57** [comment]
@zackzhangkai that was already merged, so it might come in the next release cycle? do you happen to know?

**Comment by howardjohn** [comment]
Adding this change is not likely to help users beyond niche cases - this
does NOT add support for arm64 images in Istio's release which is another
effort. Just wanted to clarify.

**Comment by wind57** [comment]
I see! thank you for the clarification.
