### ISSUE TITLE
bug reporter / troubleshooter

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#358]
It would be nice to have a `istioctl debug` for instance that would query versions and environment and settings of all components to generate information to help troubleshoot user issues (or even auto pre post/populate in issues/issues/new)

**Comment by ldemailly** [comment]
cc @mandarjog

**Comment by ldemailly** [comment]
starting point: for istioctl version 
after printing its own version it should try to print kubernetes, api server, pilot and mixer versions (would serve as a basic check those exist too)

**Comment by ldemailly** [comment]
can be contributed any time, doesn't hold up the 0.2 release

**Comment by ldemailly** [comment]
https://github.com/istio/istio/blob/master/bin/istio-proxy-cfg.py
is part of it.
We should start by including it in the release docs and documenting how to use it

also related #2751

**Comment by yusuoh** [comment]
Can we continue to rely on the insecure port (8080) of pilot to get the proxy config in the future? Or will we only allow mTLS port to be open later?

**Comment by ldemailly** [comment]
should be mtls only eventually

**Comment by yusuoh** [comment]
Then we need to add MTLS support to istio-proxy-config.py and generate a client cert from the CA for debugging purpose.

**Comment by ldemailly** [comment]
ideally we'd have a authz'ed end point (ie through ingress, mtls aware, access to pilot etc)

**Comment by ayj** [comment]
> after printing its own version it should try to print kubernetes, api server, pilot and mixer versions (would serve as a basic check those exist too)

Related: https://github.com/istio/istio/issues/2491

**Comment by ayj** [comment]
closing in favor of https://github.com/istio/istio/issues/5308

**Comment by ldemailly** [comment]
in theory we should keep the oldest issue but ok ;-)
