### ISSUE TITLE
Released Istio source codes looks invalid

### ISSUE THREAD

**Issue by AndreyRomanchev** [istio/istio#35807]
### Bug Description

I've downloaded istio source code from https://github.com/istio/istio/archive/refs/tags/1.11.4.tar.gz and it doesn't look like it's code from 1.11.4. Looking at helm charts it's version is 1.1 (there are still galley mentions for example).
Then I've downloaded source code from https://github.com/istio/istio/archive/refs/tags/1.9.8.tar.gz and it's the same file.
Here are md5sums
25cdefab2931d42a44dbb89362f74a90  1.11.4.tar.gz
25cdefab2931d42a44dbb89362f74a90  1.9.8.tar.gz

### Version

```prose
No version
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
The helm charts are versioned by the release system, not in the source code. This is part of our release process to ensure that release versions and source code are decoupled.

Helm charts should always be used from the release tar.gz files, NOT the source. Or in 1.12+, we publish real helm repos: https://artifacthub.io/packages/helm/istio-official/gateway

**Comment by AndreyRomanchev** [comment]
Let's forget about helm, it was just an example.

Just download https://github.com/istio/istio/archive/refs/tags/1.11.4.tar.gz and look into code. It's 3 years old code.

**Comment by howardjohn** [comment]
Woah. weird....

I think thats 100% github generated, so we may need to pull in github support

**Comment by howardjohn** [comment]
We do publish them ourselves at https://storage.googleapis.com/istio-release/releases/1.11.4/sources.tar.gz btw

**Comment by howardjohn** [comment]
Created github ticket 1380213. I do not think I can make it public though but will relay any information

**Comment by howardjohn** [comment]
I think it's fixed now, will verify later when I am at a computer

**Comment by AndreyRomanchev** [comment]
I just checked, looks good now.

**Comment by howardjohn** [comment]
Closing as fixed. I am quite curious if the fix for this on Github side caused https://github.com/github/feedback/discussions/8149 :stuck_out_tongue: .

tl;dr we had a branch named `refs` which caused issues. Thanks for the report!
