### ISSUE TITLE
Locality load balancing lost effectiveness while no service associated with the pod

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#35808]
### Bug Description

Locality load balancing lost effectiveness while no service associated with the pod.

### Version

```prose
client version: 1.10.2
istiod version: 1.10.2
istiod version: 1.10.2
istiod version: 1.9.5
data plane version: 1.10.2 (_ proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by cocotyty** [comment]
Because of this:
https://github.com/istio/istio/blob/a434853bb1cf7c9f2597bf7b4a2980846c57c6c1/pilot/pkg/xds/ads.go#L599

I think we can set nodeName on proxy's metadata.

And we can use the follow code to get proxy's locality without associated a service: 

https://github.com/istio/istio/blob/a434853bb1cf7c9f2597bf7b4a2980846c57c6c1/pilot/pkg/serviceregistry/kube/controller/controller.go#L882

**Comment by cocotyty** [comment]
@howardjohn

**Comment by hzxuzhonghu** [comment]
Istio requires a service selecting the pod, not just locality lb. Without service, we will miss half telemetry capability

**Comment by cocotyty** [comment]
> Istio requires a service selecting the pod, not just locality lb. Without service, we will miss half telemetry capability

Some kind of workload don't need a service, like a cronjob.

**Comment by howardjohn** [comment]
I do agree but it is a documented requirement/limitation of Istio: https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements.

IMO it should be improved but that is how it is for now.

**Comment by cocotyty** [comment]
> I do agree but it is a documented requirement/limitation of Istio: https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements.
> 
> IMO it should be improved but that is how it is for now.

You are right.
I created a PR for this issue.
https://github.com/istio/istio/pull/35868
