### ISSUE TITLE
meshConfig.accesLogFormat does not respect Yaml multiline parsing with Folded Style (no interior line breaks)

### ISSUE THREAD

**Issue by boeboe** [istio/istio#35812]
### Bug Description

Consider the following log format configuration:

    meshConfig:
      accessLogEncoding: TEXT
      accessLogFile: /dev/stdout
      accessLogFormat: >
        {
          "authority":"%REQ(:AUTHORITY)%",
          "bytes_received":"%BYTES_RECEIVED%",
          "bytes_sent":"%BYTES_SENT%",
          "connection_termination_details":"%CONNECTION_TERMINATION_DETAILS%",
          "downstream_local_address":"%DOWNSTREAM_LOCAL_ADDRESS%",
          "downstream_peer_cert_v_end":"%DOWNSTREAM_PEER_CERT_V_END%",
          "downstream_peer_cert_v_start":"%DOWNSTREAM_PEER_CERT_V_START%",
          "downstream_remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%",
          "downstream_tls_cipher":"%DOWNSTREAM_TLS_CIPHER%",
          "downstream_tls_version":"%DOWNSTREAM_TLS_VERSION%",
          "duration":"%DURATION%",
          "hostname":"%HOSTNAME%",
          "istio_policy_status":"%DYNAMIC_METADATA(istio.mixer:status)%",
          "method":"%REQ(:METHOD)%",
          "path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol":"%PROTOCOL%",
          "request_duration":"%REQUEST_DURATION%",
          "request_id":"%REQ(X-REQUEST-ID)%",
          "requested_server_name":"%REQUESTED_SERVER_NAME%",
          "response_code":"%RESPONSE_CODE%",
          "response_code_details":"%RESPONSE_CODE_DETAILS%",
          "response_duration":"%RESPONSE_DURATION%",
          "response_tx_duration":"%RESPONSE_TX_DURATION%",
          "response_flags":"%RESPONSE_FLAGS%",
          "route_name":"%ROUTE_NAME%",
          "start_time":"%START_TIME%",
          "trace_id":"%REQ(x-b3-traceid)%",
          "upstream_cluster":"%UPSTREAM_CLUSTER%",
          "upstream_host":"%UPSTREAM_HOST%",
          "upstream_local_address":"%UPSTREAM_LOCAL_ADDRESS%",
          "upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "upstream_transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%",
          "user_agent":"%REQ(USER-AGENT)%",
          "x_forwarded_for":"%REQ(X-FORWARDED-FOR)%"
        }

According to the YAML specs (https://yaml.org/spec/1.2.2/#813-folded-style), this should result in interior line breaks being stripped out, so one has a valid and single line JSON for fluent-bit (or other logstashers) forwarding.

However, when this configuration is applied, the resulting YAML modifier `>` is replaced by `|`, causing new lines to be injected, breaking the log parsing.

    meshConfig:
      accessLogEncoding: TEXT
      accessLogFile: /dev/stdout
      accessLogFormat: |
        {
          "authority":"%REQ(:AUTHORITY)%",
          "bytes_received":"%BYTES_RECEIVED%",
          "bytes_sent":"%BYTES_SENT%",
          "connection_termination_details":"%CONNECTION_TERMINATION_DETAILS%",
          "downstream_local_address":"%DOWNSTREAM_LOCAL_ADDRESS%",
          "downstream_peer_cert_v_end":"%DOWNSTREAM_PEER_CERT_V_END%",
          "downstream_peer_cert_v_start":"%DOWNSTREAM_PEER_CERT_V_START%",
          "downstream_remote_address":"%DOWNSTREAM_REMOTE_ADDRESS%",
          "downstream_tls_cipher":"%DOWNSTREAM_TLS_CIPHER%",
          "downstream_tls_version":"%DOWNSTREAM_TLS_VERSION%",
          "duration":"%DURATION%",
          "hostname":"%HOSTNAME%",
          "istio_policy_status":"%DYNAMIC_METADATA(istio.mixer:status)%",
          "method":"%REQ(:METHOD)%",
          "path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol":"%PROTOCOL%",
          "request_duration":"%REQUEST_DURATION%",
          "request_id":"%REQ(X-REQUEST-ID)%",
          "requested_server_name":"%REQUESTED_SERVER_NAME%",
          "response_code":"%RESPONSE_CODE%",
          "response_code_details":"%RESPONSE_CODE_DETAILS%",
          "response_duration":"%RESPONSE_DURATION%",
          "response_tx_duration":"%RESPONSE_TX_DURATION%",
          "response_flags":"%RESPONSE_FLAGS%",
          "route_name":"%ROUTE_NAME%",
          "start_time":"%START_TIME%",
          "trace_id":"%REQ(x-b3-traceid)%",
          "upstream_cluster":"%UPSTREAM_CLUSTER%",
          "upstream_host":"%UPSTREAM_HOST%",
          "upstream_local_address":"%UPSTREAM_LOCAL_ADDRESS%",
          "upstream_service_time":"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "upstream_transport_failure_reason":"%UPSTREAM_TRANSPORT_FAILURE_REASON%",
          "user_agent":"%REQ(USER-AGENT)%",
          "x_forwarded_for":"%REQ(X-FORWARDED-FOR)%"
        }

The work-around now is to collapse all of this into one line and use escape characters, but this is hard to read, maintain and error prone. Also, one needs to manually add a new line `\n` character at the end.

    meshConfig:
      accessLogEncoding: TEXT
      accessLogFile: /dev/stdout
      accessLogFormat: "{ \"authority\":\"%REQ(:AUTHORITY)%\", \"bytes_received\":\"%BYTES_RECEIVED%\", \"bytes_sent\":\"%BYTES_SENT%\", \"connection_termination_details\":\"%CONNECTION_TERMINATION_DETAILS%\", \"downstream_local_address\":\"%DOWNSTREAM_LOCAL_ADDRESS%\", \"downstream_peer_cert_v_end\":\"%DOWNSTREAM_PEER_CERT_V_END%\", \"downstream_peer_cert_v_start\":\"%DOWNSTREAM_PEER_CERT_V_START%\", \"downstream_remote_address\":\"%DOWNSTREAM_REMOTE_ADDRESS%\", \"downstream_tls_cipher\":\"%DOWNSTREAM_TLS_CIPHER%\", \"downstream_tls_version\":\"%DOWNSTREAM_TLS_VERSION%\", \"duration\":\"%DURATION%\", \"hostname\":\"%HOSTNAME%\", \"istio_policy_status\":\"%DYNAMIC_METADATA(istio.mixer:status)%\", \"method\":\"%REQ(:METHOD)%\", \"path\":\"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\", \"protocol\":\"%PROTOCOL%\", \"request_duration\":\"%REQUEST_DURATION%\", \"request_id\":\"%REQ(X-REQUEST-ID)%\", \"requested_server_name\":\"%REQUESTED_SERVER_NAME%\", \"response_code\":\"%RESPONSE_CODE%\", \"response_code_details\":\"%RESPONSE_CODE_DETAILS%\", \"response_duration\":\"%RESPONSE_DURATION%\", \"response_tx_duration\":\"%RESPONSE_TX_DURATION%\", \"response_flags\":\"%RESPONSE_FLAGS%\", \"route_name\":\"%ROUTE_NAME%\", \"start_time\":\"%START_TIME%\", \"trace_id\":\"%REQ(x-b3-traceid)%\", \"upstream_cluster\":\"%UPSTREAM_CLUSTER%\", \"upstream_host\":\"%UPSTREAM_HOST%\", \"upstream_local_address\":\"%UPSTREAM_LOCAL_ADDRESS%\", \"upstream_service_time\":\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\", \"upstream_transport_failure_reason\":\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\", \"user_agent\":\"%REQ(USER-AGENT)%\", \"x_forwarded_for\":\"%REQ(X-FORWARDED-FOR)%\" }\n"

### Version

```prose
All
```

**Comment by howardjohn** [comment]
> However, when this configuration is applied, the resulting YAML modifier > is replaced by |, causing new lines to be injected, breaking the log parsing.

Any YAML modifications must be K8s doing this afaik.

IMO the fix here is to insert a newline if there isn't one present on Istiod side. Its never(?) relevant to not have a newline, and its annoying to have to add + easy to make mistakes. WDYT?

**Comment by boeboe** [comment]
Hi @howardjohn , thanks for your response. I did a quick verification to see if K8s is able to handle this Yaml parsing nuance, and from the below result, I seem to believe it does.

    # cat configmap-test.yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-yaml
    data:
      test1.properties: >
        here we should not
        see new lines being
        injected
      test2.properties: |
        here we should see
        new lines being
        injected

    # kubectl apply -f configmap-test.yaml
    configmap/test-yaml created

    #  kubectl get cm test-yaml -o yaml
    apiVersion: v1
    data:
      test1.properties: |
        here we should not see new lines being injected
      test2.properties: |
        here we should see
        new lines being
        injected
    kind: ConfigMap
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","data":{"test1.properties":"here we should not see new lines being injected\n","test2.properties":"here we should see\nnew lines being\ninjected\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test-yaml","namespace":"default"}}
      creationTimestamp: "2021-11-01T20:13:14Z"
      name: test-yaml
      namespace: default
      resourceVersion: "734501"
      uid: 2c43e118-a9c1-4061-8a51-d71734125671


Is it possible something goes wrong in the Yaml parsing in between the IstioOperator Object being applied and the Istio ConfigMap containing the result?

**Comment by howardjohn** [comment]
> Is it possible something goes wrong in the Yaml parsing in between the IstioOperator Object being applied and the Istio ConfigMap containing the result?

Ah, that is plausible. Lots of marshalling an unmarshalling to get there..

What is the exact flow? Are you using the in cluster operator, `istioctl install`, etc?

Regardless of this i ithink we should still make the format code insert a newline. But we may need to do that _and_ fix some other yaml thing in the operator

**Comment by boeboe** [comment]
Hi John,

I use `kubectl apply -f istiologconfig.yaml` to apply my log configuration GitOps style.

    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata: 
      name: istiologconfig
      namespace: istio-system
    spec:
      meshConfig:
        accessLogEncoding: TEXT
        accessLogFile: /dev/stdout
        accessLogFormat: >
          my
          multiline
          stuff ..

As to the extra new line, this is indeed also an issue, but a separate one. Shall I create a dedicated issue, or is this report enough to cover both issues and trigger some yaml magic review?
