### ISSUE TITLE
Gateway authorization enforcement

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#35815]
Gateway API is the future core Istio API. We'd like to support a mode where most of Istio APIs is implemented by gateway proxies. However, authorization checks assume existence of the server-side sidecars since they are expressed in terms of the destination workload labels. In order to support this minimal Gateway API + authorization API implementation, we want to be able to enforce the authorization checks on the gateways rather than the server-side sidecars.

Assuming workloads accept traffic only from gateways, the server-side sidecars can be safely replaced by gateway authorization checks. The network isolation can be done via a lower-level network policy.

In order to achieve this, gateway Envoys need to take into account the endpoint labels to select the policies. This likely requires HTTP filters on the upstream clusters.

@yangminzhu @mandarjog

**Comment by yangminzhu** [comment]
Today the authorization policy already supports to be enforced on gateway Envoys in its inbound filters, of course the gateway Envoy is selected by workload labels and not via the k8s gateway-api.

Is this issue about extending the k8s gateway-api to support attaching authorization policy? Or is this for extending the Envoy to support RBAC filter on upstream cluster in addition to the inbound filter?

**Comment by kyessenov** [comment]
@yangminzhu 

For the first point, I see a problem with that since it leaks the implementation details of gateway API. I don't think user needs to be aware of workload labels for the gateway proxy in order to express an authorization policy. In theory, gateways may run outside the cluster.

For the second point, the issue is supporting Istio RBAC in gateway-only mode. If all traffic goes through gateway, including in-cluster traffic, running a sidecar is an overkill. I imagine Envoy needs to be extended because as you say, policy needs to apply after cluster endpoint selection.
