### ISSUE TITLE
High memory consumption of sidecar

### ISSUE THREAD

**Issue by xiangtianyu** [istio/istio#35828]
### Bug Description

When i used istio in my k8s clusters,the memory consumption of istio sidecar is very high.Sometimes it can be about 400m,500m.My cluster have about 2000 pods and i need some solutions to reduce the memory level.

### Version

```prose
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 

Client Version: v1.18.17
Server Version: v1.18.17
```

**Comment by howardjohn** [comment]
https://karlstoney.com/2020/10/03/istio-at-scale-sidecar/ may help
