### ISSUE TITLE
Support CNAMES with DNS Proxy

### ISSUE THREAD

**Issue by joberdick-rcd** [istio/istio#35837]
**Describe the feature request**
When using DNS proxy features:
ISTIO_META_DNS_CAPTURE: "true"
ISTIO_META_DNS_AUTO_ALLOCATE: "true"

CNAME records are not being followed down to the IP. With the current behavior, every hostname behind the CNAME alias has to be added to service entries. This is not practical in many cases because the names behind CNAME records are commonly dynamic and sometimes not predictable. Which is the reason for the CNAME to begin with. 

I am purposing that the DNS proxy feature follows the chain of resolved names until it reaches an IP. This allows for a single service entry that will follow whatever changes in DNS occur. We lock down egress and require all external endpoints to be defined. We will not be able to adopt DNS proxy in current state even though we really want the benefits of TCP VIP's. 

**Describe alternatives you've considered**
NA
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Consider use cases such as AWS RDS MySQL or any other managed service that has CNAMES.

**Comment by howardjohn** [comment]
Can you should an example response with and without the proxy to illustrate this? I thought we are returning the DNS responses as is for upstream queries so I am not quite sure what change is required?

**Comment by joberdick-rcd** [comment]
@howardjohn after further investigation, this issue does accurately describe the issue. Will open a new case if needed.
