### ISSUE TITLE
Can no longer build some Istio binaries on a Mac (istio-cni, istio-iptables)

### ISSUE THREAD

**Issue by ericvn** [istio/istio#35831]
### Bug Description

It appears that https://github.com/istio/istio/pull/35360 has made some changes that now prevent builds from completing error free when using a Mac. The VS Code editor also shows the same 3 errors:
```
# istio.io/istio/tools/istio-iptables/pkg/capture
tools/istio-iptables/pkg/capture/run.go:357:15: undefined: netlink.RuleAdd
tools/istio-iptables/pkg/capture/run.go:376:17: undefined: netlink.SCOPE_HOST
tools/istio-iptables/pkg/capture/run.go:377:17: undefined: unix.RTN_LOCAL
```

Note that the other `build` binaries do seem to build OK.

### Version

```prose
Current commit, 0baff96984f6f7114e2de9763114b757678ca90d, on the `master` branch.
```

**Comment by esnible** [comment]
I am having the same problem.  It is the same if I use `BUILD_WITH_CONTAINER=1 make istioctl`.

**Comment by therealmitchconnors** [comment]
I am able to work around this problem by running the build inside of `sudo make shell`, with the home, hub, and tag env vars persisted.

**Comment by ericvn** [comment]
@esnible I think istioctl will be built even though the error appears (I think only the istio-iptables and istio-cni executables aren't).

I'm not sure if @therealmitchconnors suggestion will work, since you'll still be trying to build the Darwin version of istio-iptables which I would think would fail. If you set TARGET_OS=linux, then you are causing the linux version of the executables to be built so if you don't need the darwin version, you can could use that.
