### ISSUE TITLE
Allow individual api group and version for each config resource kind in Pilot config store

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3586]
Currently all CRDs in Pilot share the same IstioAPIGroup: config.istio.io and IstioAPIVersion: v1alphav2

In this PR, we allow each resource kind to be able to define their own config group with a common suffix istio.io and version.

This allows

- each feature to advance API versions at different pace.
- the CRD group name to be reverse order mapping to proto package, as suggested in istio/api#343
- separate public/internal storage of CRDs #3457

**Comment by xiaolanz** [comment]
Given this is a config model change and deep refactor, the work is split into steps to avoid overly large PRs 

- [ ] Add Group/Version per each schema. 
- [ ] Change crd/Client to becomes a wrap of clientsets, each for one apiversion. 
- [ ] Update config store to identify schema by group version type instead of type. 

Not until the last step is done, Pilot still continue to work with one config.istio.io and same version.

**Comment by ayj** [comment]
This is mostly done. The only remaining API resources in `config.istio.io` are Mixer policy and the HTTPSpec and QuotaSpec for mixerclient.

**Comment by ozevren** [comment]
It makes much more sense to do this when Galley becomes the default config ingestion pipeline. Creating new API Group handlers, and deprecating old ones is trivial in Galley, but it is complicated for each component.

**Comment by ozevren** [comment]
Closing this: The current Galley + MCP architecture makes it obsolete.
