### ISSUE TITLE
istioctl operator dump has no watchedNamespaces flag provided

### ISSUE THREAD

**Issue by fatalc** [istio/istio#35864]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

```sh
$ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (1 proxies)
```

```sh
istioctl operator init --watchedNamespaces=istio-system
```

has flag `--watchedNamespaces` provided and set the default value "istio-system"

```sh
istioctl operator dump
```

has no flag `--watchedNamespaces` provided, and the default value of watchedNamespaces is "",it's cause all namespaces watched.

It cause the init and dump command has inconsistent behavior.

**Describe alternatives you've considered**

- Simplely add a flag `watchedNamespaces` like the init command.
- The `init` and `dump`subcommands should share flags related to `operatorCommonArgs`[operator-init.go#L43](https://github.com/istio/istio/blob/master/operator/cmd/mesh/operator-init.go#L43).  Could we create a common flagset for init and dump commands instead.

The second alt may be better.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I'd open a PR to improve this after a alt decided.

**Comment by kebe7jun** [comment]
See https://github.com/istio/istio/issues/35485, it is already implemented, 1.12 will include this feature.
