### ISSUE TITLE
Istio 1.11.4 [Smart DNS]  Smart DNS Proxy is breaking dns resolution  in  istio-proxy

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#35901]
### Bug Description

Smart DNS Proxy is breaking dns resolution on istio-proxy

![image](https://user-images.githubusercontent.com/19339970/140328480-ee8581c4-cda1-48e1-b1e1-1e26f2bdabdf.png)

### Version

```prose
➜  debug-istio-vm istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (12 proxies), 1.11.0 (2 proxies)
```

### Additional Information

see https://github.com/istio/istio/issues/31295

**Comment by howardjohn** [comment]
The DNS proxy doesn't/shouldn't impact requests coming from istio-proxy at all.
