### ISSUE TITLE
istio-cni plugin fails when installing Istio with non-root user

### ISSUE THREAD

**Issue by johnma14** [istio/istio#35902]
### Bug Description

For users who build their own Istio images  with non-root user, Istio fails to install when CNI plugin is enabled. 

In 1.11, as part of the beta graduation of [Istio CNI plugin](https://github.com/istio/istio/issues/24416], a new feature was added to [enable CNI plugin to send logs to the CNI container](https://github.com/istio/istio/pull/33926). It creates a hostPath volume to write the logs at `/var/run/istio-cni` which requires root privileges. Since this is a hostPath volume, it is created when the pod comes up and before the app containers start running these non-root  images. This directory is created by the root user and owned by root:root with default permission of 755 [`rwxr-xr-x 1 root root  log.sock`].

From the Kubernetes docs about [hostPaths](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath):

> The files or directories created on the underlying hosts are only writable by root. You either need to run your
process` as root in a privileged Container or modify the file permissions on the host to be able to write to a 
hostPath volume.

When the install-cni container starts with the non-root user, it tries to start the UDS log server at `/var/run/istio-cni` directory which is owned by the root user and fails because it does not have sufficient permissions to write to log.sock

Two approaches I tried that worked - In [daemonset.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/templates/daemonset.yaml) :

1. **Explicitly set the securityContext in the install-cni container to run as the root user.**
    ~~~
        securityContext:
            runAsUser: 0
    ~~~
2. **Create initContainers to chown (from root:root -> root:1337) and chmod (user in the group 1337 can rwx/775) the hostPath mount point.**
    ~~~
     initContainers:
        - name: istio-volume-permissions-chown
          image: busybox
          command: ["/bin/chown","-R", "root:1337" , "/var/run/istio-cni"]
          volumeMounts:
            - name: cni-log-dir
              mountPath: /var/run/istio-cni
        - name: istio-volume-permissions-chmod
          image: busybox
          command: ["/bin/chmod","-R","775", "/var/run/istio-cni"]
          volumeMounts:
            - name: cni-log-dir
              mountPath: /var/run/istio-cni
      ~~~

### Version

```prose
- istioctl version: 

client version: 1.12-dev
control plane version: 1.12-dev-8a03c8529b90e382984f65fe43cc14ec2e831948
data plane version: 1.12-dev (1 proxies)
```

### Additional Information

The istio-cni pod fails with CrashLoopBack and logs from the pod shows:

~~~
2021-10-29T23:57:06.541652Z     info    CNI install configuration:
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName:
ChainedCNIPlugin: true
CNINetworkConfigFile:
CNINetworkConfig: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "__LOG_UDS_ADDRESS__",
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system" ]
  }
}
CNIEnableReinstall: true
LogLevel: warn
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile:
SkipTLSVerify: false
K8sServiceProtocol:
K8sServiceHost: 10.96.0.1
K8sServicePort: 443
K8sNodeName: istio-cni-node-4mndd
UpdateCNIBinaries: true
SkipCNIBinaries: [[]]
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock

2021-10-29T23:57:06.541829Z     info    CNI race repair configuration:
Enabled: true
RunAsDaemon: true
NodeName: tryma1.fyre.ibm.com
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg:
InitExitCode: 126
LabelSelectors:
FieldSelectors:

Error: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
2021-10-29T23:57:06.541721Z     info    ControlZ available at 127.0.0.1:9876
2021-10-29T23:57:06.542352Z     info    Start a UDS server for CNI plugin logs
2021-10-29T23:57:06.542487Z     error   Failed to start up UDS Log Server: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
Usage:
  install-cni [flags]
  install-cni [command]
~~~

**Comment by howardjohn** [comment]
Why does it work in CI? Are you using a custom securityContext and/or image that changes the user?

@bianpengyuan

**Comment by johnma14** [comment]
@howardjohn yes we are building our own images, including the [cni images] (https://github.com/istio/istio/blob/master/cni/deployments/kubernetes/Dockerfile.install-cni) using a non-root user with no custom security context.

The fact that this component needs root privileges for the logging feature seems to break atleast 2 use cases - users who build their own images with non-root users and those who use restrictive PSP's like those mentioned in [34905](https://github.com/istio/istio/issues/34905) and [35387](https://github.com/istio/istio/issues/35387). A possible solution to address both these use cases would be to make this an optional feature and if enabled, to always run the install-cni container as a root user.

**Comment by howardjohn** [comment]
ACK. Seems like some images set `USER 1337:1337` but not all which would explain it.

**Comment by johnma14** [comment]
@howardjohn true. Plus the istio-cni is the only component that creates these hostPath volumes, so we cannot really change permissions on these directories from the app containers.

**Comment by bianpengyuan** [comment]
You can disable the feature by setting `LOG_UDS_ADDRESS` env to an empty string at CNI DaemonSet, which should unblock your CNI daemonset from starting. Although the volume will still be mounted unnecessarily, so we need to make it configurable via helm charts.

**Comment by howardjohn** [comment]
@bianpengyuan maybe this is why openshift needed `privileged`? In the current state we do not set `securityContext` at all. This means the user (and therefor whether we are root) can change. In this issue, its because distroless runs as UID 1337 and ubuntu runs as UID 0 by default. In the openshift case, it could be because openshift assigns a random UID if not specified (I think).

The best practice is to fully specify all fields in the securityContext to be explicit. In this case, it seems like that should be to run as root - or we need a workaround to allow not running as root?

**Comment by bianpengyuan** [comment]
Yeah make sense to make it running as root explicitly. Actually I am curious how would custom build with non-rooot user id work.. even without the log volume, the CNI daemonset still needs to access the cni binary host path, which can only be accessed by root?

**Comment by johnma14** [comment]
@bianpengyuan I noticed that as well. There are other hostPath volumes that we use. I am not sure what kind of access is required for those paths (is just read access enough). In the case of the log volume, it manifested as a problem because we are trying to create a UDS log server against this directory which requires write access.

**Comment by bianpengyuan** [comment]
> I am not sure what kind of access is required for those paths (is just read access enough)

CNI needs to write to the other host path. It copies the CNI binary to it, which is core of CNI daemonset function.

Was this ever work for  you with different user?

**Comment by johnma14** [comment]
@bianpengyuan this is something new we are testing, so no we haven't run the CNI plugin before as a non-root user.
