### ISSUE TITLE
Adding Datadog distributed tracing docs

### ISSUE THREAD

**Issue by Fadyazmy** [istio/istio#35907]
Hello! I'm a PM at Datadog, and I'm looking to extend the [Distributed Tracing](https://istio.io/latest/docs/tasks/observability/distributed-tracing/) docs to include instructions on how to enable the Datadog integration.

Are there any requirements that we should take into consideration before creating a PR?

**Comment by Fadyazmy** [comment]
Closing this issue as it's the wrong repo (sorry!)

**Comment by ceastman-r7** [comment]
@Fadyazmy Did you update the distributed tracing doc for datadog? I am looking to integrate istio into datadog but the blogs I have found so far are pretty out of date: https://www.datadoghq.com/blog/how-to-monitor-istiod/
