### ISSUE TITLE
User Experience: Istio on EKS without AWS VPC CNI

### ISSUE THREAD

**Issue by sedflix** [istio/istio#35917]
**Describe the feature request**
This is a request/discussion on improving the user experience of using istio on EKS without AWS VPC CNI.
We have to run istiod in host networking mode because EKS doesn't allow CNI to be installed on master nodes [Details](https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks). Now this results in several problems, 
1. istio-cni and istiod can't run in their default configuration as they have same monitoring port
2. changing default monitoring port and its repercussion are not documented

We should maybe have a profile for aws+custom-cni.
TODO: add more problems

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
> We have to run istiod in host networking mode because EKS doesn't allow CNI to be installed on master nodes

This seems suspicious. I am not an EKS expert but. I don't think everyone on EKS is running istiod in host network?

Running in host network is a very bad idea if it can be avoided.

**Comment by howardjohn** [comment]
TBH I would sooner deploy a simple proxy that is on hostnetwork and forwards requests to Istiod running in non-hostnetwork than run it in hostNetwork. But you are free to run it there if you want. I do not think we should encourage it officially though.

**Comment by sedflix** [comment]
@howardjohn thanks for the reply

> edit: oh maybe its only with calico
EKS doesn't allow running CNI on master nodes. If we are creating a different subnet with a CNI for our worker nodes(which we often seem to do on using a CNI), our master nodes won't be able to reach our worker nodes and hence webhooks don't work. We have only tried using calico but the problem seems more generic because of EKS limitation. 

Quote from the [calico docs](https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks):
> Calico networking cannot currently be installed on the EKS control plane nodes. As a result the control plane nodes will not be able to initiate network connections to Calico pods. (This is a general limitation of EKS’s custom networking support, not specific to Calico.
Quote from [AWS Docs](https://aws.github.io/aws-eks-best-practices/reliability/docs/networkmanagement/#cni-custom-networking):
> EKS managed node groups currently don’t support custom networking option
I still could be wrong about the problem being generic with respect to EKS rather than calico.


> Running in host network is a very bad idea if it can be avoided 
I totally agree and I would love to avoid it. 

> simple proxy that is on hostnetwork and forwards requests to Istiod running in non-hostnetwork than run it in hostNetwork
This seems like a good idea.


The idea of this issue is to provide a blog or something as a starting point for EKS + Custom Networking setup rather than a cycle of facing issues -> debugging them -> facing more issues.

**Comment by howardjohn** [comment]
https://medium.com/@denisstortisilva/kubernetes-eks-calico-and-custom-admission-webhooks-a2956b49bd0d is basically what I was thinking with the proxy

**Comment by sedflix** [comment]
@howardjohn thanks for this blog. seems really amazing.

**Comment by luispabon** [comment]
Anybody actually managed to get the proxy mentioned on that blog working? The main problem is that the webhook's service name is basically hardcoded:

![image](https://github.com/istio/istio/assets/6388823/dba1b242-932b-4e81-9231-15bf19dc1b1c)

I'm trying to avoid reaching for kustomize basically as it would complicate our helmfile set up.
