### ISSUE TITLE
version 1.9.9 use wrong validatingwebhookconfigurations istiod-istio-system

### ISSUE THREAD

**Issue by YonkaFang** [istio/istio#35937]
### Bug Description

I performed the following steps:

1. install istio 1.11.4 with command: `./bin/istioctl install --set revision=1-11-4 --set components.pilot.k8s.resources.requests.cpu=50m --set components.pilot.k8s.resources.requests.memory=300Mi`
2. install istio 1.9.9 with cmd: `./bin/istioctl install --set profile=minimal --revision=1-9-9 --set revision=1-9-9 --set components.pilot.k8s.resources.requests.cpu=50m --set components.pilot.k8s.resources.requests.memory=300Mi`
3. then I see a `validatingwebhookconfigurations` with name `istiod-istio-system` while I guess the corrent name should be `istio-validator-1-9-9-istio-system` and it points to the wrong service `istiod.istio-system`. So it causes the configuration creation to fail because the validation is sent to an invalid service and does not work properly.

Detailed content is as below:

```sh
kubectl -n istio-system get mutatingwebhookconfigurations.admissionregistration.k8s.io
NAME                            WEBHOOKS   AGE
istio-sidecar-injector-1-11-4   2          74m
istio-sidecar-injector-1-9-9    1          40m

kubectl -n istio-system get validatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                  WEBHOOKS   AGE
istio-validator-1-11-4-istio-system   2          72m
istiod-istio-system                   1          44m
```

```yaml
    service:
      name: istiod
      namespace: istio-system
      path: /validate
      port: 443
```

### Version

```prose
./bin/istioctl version
client version: 1.9.9
istiod version: 1.11.4
istiod version: 1.9.9
data plane version: 1.11.4 (1 proxies)
kubectl version --short
Client Version: v1.20.4
Server Version: v1.20.4
```

**Comment by dddddai** [comment]
I guess it's because the `ValidatingWebhookConfiguration` name is different in v1.11.4 and v1.9.9

In v1.9.9, its name is [`istiod-xxx`](https://github.com/istio/istio/blob/1.9.9/manifests/charts/base/templates/validatingwebhookconfiguration.yaml#L5) while in v1.11.4 it's [`istio-validator-xxx`](https://github.com/istio/istio/blob/1.11.4/manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml#L5)

**Comment by Kyslik** [comment]
I can't find this in https://istio.io/latest/news/releases/1.11.x/announcing-1.11.4/ we got burned a little.

**Comment by YonkaFang** [comment]
maybe the different `rev` args confused me.
