### ISSUE TITLE
Problem with disabling tracing

### ISSUE THREAD

**Issue by xiaoyaozi5566** [istio/istio#35935]
### Bug Description

I want to disable the distributed tracing in istio-proxy. I was using helm chart to install istio control plane. In the istio-discovery `values.yaml`, I made the following change
```
tracer: ""
```
I thought this would disable injecting tracing related feature into the sidecar proxy. But when I start the application pod, I got the following error in the istio control plane log

> error    Pod injection failed: failed to run injection template: could not parse configuration values: unknown value "" for enum v1alpha1.Tracer

I know `""` is not part of the `Tracer` enum, so I must be doing something wrong here. But this [PR](https://github.com/istio/istio/pull/34419) seems to suggest the `tracer` variable can have a value outside of `(zipkin, lightstep, datadog, stackdriver)`. What is the right way to disable tracing? Thanks!

### Version

```prose
1.11.4
```

**Comment by howardjohn** [comment]
I think it has to be specifically `none`. This is an artifact of the helm install having less validation than `istioctl install` so its not rejected until later unfortunately..

**Comment by xiaoyaozi5566** [comment]
Thank you very much @howardjohn ! That solves the issue. I was looking at https://istio.io/latest/about/faq/distributed-tracing/#disabling-tracing but I didn't find clear instructions on how to disable tracing. Wouldn't know that I need to specify `none` until you told me. Kinda of wish the documentation can include this..
