### ISSUE TITLE
api update workflow: vendor/ should not prune istio.io/api to save a step

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3593]
if we don't prune istio.io/api _and_ we make the bot auto update vendor/ too and not just the lock (if and only if the tests pass) then we could save a step in api changes

cc @hklai @costinm

**Comment by hklai** [comment]
Seems obsolete since vendor is in istio/istio. Please reopen if this is still applicable.

**Comment by ldemailly** [comment]
we still have to move api inside istio as shriram signed up to do some months ago but that can be tracked elsewhere indeed
