### ISSUE TITLE
apiserver.TestEvents is flakey

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#35936]
### Bug Description

this test fails periodically, and tests functionality not used outside galley.  It is about to be removed, but is impacting the PR which enables its removal.  Skipping.

### Version

```prose
master
```

**Comment by howardjohn** [comment]
I am almost certain this is due to not using our pkg/kube which has some workarounds for fake informers being inherently flaky. Glad the code is removing soon :-)
