### ISSUE TITLE
istioctl upgrade: consolidate with install

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35951]
Currently, upgrade has a few issues:

* Calls to github external - this breaks MANY users
* Unclear when/why to use it vs `install`, given `install` can upgrade and is declarative. Especially with revisions
* Gives bad advice, such as no skip level upgrades.
* Detects future version using `tag`, which may be a random string. `install` has a different method
* Output formatting is very inconsistent with `install` and less polished
* Doesn't actually add any useful checks over `install` other than showing a diff of changes.
* Diff logic is flaky, due to defaulting values you often get false positives.
* Has custom wait logic (`waitUpgradeComplete`). Not sure why this is needed when `install` already has very robust waiting.

I propose we rework it.

Changes I would make:
* Deprecate `upgrade` (but do not remove), make it an alias for `install --show-diff`
* Remove the entire existing `upgrade` path (since its not an alias for `install`)
* Add `--show-diff` option to `install`. This follows the current diff logic for `upgrade`, but should NOT pull from github.com. Instead, create a function to fetch the `installed-state` from the cluster. Also make sure we hit the right code paths to resolve the defaulting issues.

**Comment by therealmitchconnors** [comment]
I like this idea, but istioctl commands not nested under experimental require a a deprecation schedule.  We can deprecate in 1.13, and remove (or make a breaking redirect) in a later release.  I don't recall off the top of my head how many releases we have to follow for deprecation.

**Comment by howardjohn** [comment]
I am not suggesting removal. Rather make `upgrade` and alias for `install
--show-diff` or similar, which does very similar steps as today, although
likely with some beneficial implementation differences (ex. read from
cluster instead of github, but give the same result to the user in the end)

**Comment by linsun** [comment]
It is not obvious to users to run istioctl install to perform upgrades. Could we still keep istioctl upgrade but reusing the same code from istioctl install when makes sense?

**Comment by howardjohn** [comment]
Yes that is my recommendation. upgrade ad an alias for install

**Comment by hanxiaop** [comment]
Should we reopen this? Currently the upgrade command is exactly the same as install command with no additional checks(The description shows `The upgrade command is an alias for the install command that performs additional upgrade-related checks.`), the `--show-diff` flag hasn't been implemented yet.
