### ISSUE TITLE
Increase IL evaluator cache efficiency by normalizing expressions

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#3596]
From istio/mixer/pkg/il/evaluator/evaluator.go, in the getOrCreateCacheEntry function:

// TODO: add normalization for exprStr string, so that 'a | b' is same as 'a|b', and  'a == b' is same as 'b == a'

**Comment by geeknoid** [comment]
Within the context of the runtime2 effort, we should statically be observing like expressions and coallessing them such that the IL is in memory once. This will:

- Improve CPU cache efficiency
- Improve Mixer cache efficiency, the same cache can be used for all like expressions.
- Save a bit of memory

**Comment by ozevren** [comment]
That particular comment will no longer apply after switch to runtime2, but the general problem still applies. I think we can perform the following:

- Compare the incoming strings, with whitespace trimming. This is pretty much what the current code does, and is likely to catch the low-hanging fruits.
- Compare the expression tries for structural equivalency. This should be relatively straightforward to implement, and should capture cases where a basic text-based diffing fails.
- Normalize and prune the expression trees (i.e. normalize the order of (unordered) binary operators, prune expression tree & remove dead code etc.). Combined with structural equivalency, this should cover bulk of the work.

We probably should do this as part of/after CEL integration.
