### ISSUE TITLE
RBAC: access denied even though valid JWT is given

### ISSUE THREAD

**Issue by vaporpin** [istio/istio#35973]
### Bug Description

Hi, I tried to protect the gateway with auth policy, RequestAuthentication and AuthorizationPolicy, shown below. I sent a valid JWT, however RBAC is still shown. Thank you for your advice. (*note, all dashes became bullet points, not sure how to stop the conversion)

apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.6/security/tools/jwt/samples/jwks.json"

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]

When I curl the endpoint, I got 

*   Trying 35.127.145.71...
* TCP_NODELAY set
* Connected to iris.test.35.127.145.71.nip.io (35.127.145.71) port 80 (#0)
> POST /v1/models/iris/infer HTTP/1.1
> Host: iris.test.35.127.145.71.nip.io
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRIRmJwb0lVcXJZOHQyenBBMnFYZkNtcjVWTzVaRXI0UnpIVV8tZW52dlEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ2ODU5ODk3MDAsImZvbyI6ImJhciIsImlhdCI6MTUzMjM4OTcwMCwiaXNzIjoidGVzdGluZ0BzZWN1cmUuaXN0aW8uaW8iLCJzdWIiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyJ9.CfNnxWP2tcnR9q0vxyxweaF3ovQYHYZl82hAUsn21bwQd9zP7c-LS9qd_vpdLG4Tn1A15NxfCjp5f7QNBUo-KC9PJqYpgGbaXhaGx7bEdFWjcwv3nZzvc7M__ZpaCERdwU7igUmJqYGBYQ51vr2njU9ZimyKkfDe3axcyiBZde7G6dabliUosJvvKOPcKIWPccCgefSj_GNfwIip3-SsFdlR7BtbVUcqR-yv-XOxJ3Uc1MI0tz3uMiiZcyPV7sNCU4KRnemRIMHVOfuvHsU60_GhGbiSFzgPTAa9WTltbnarTbxudb_YEOx12JiwYToeX0DCPb43W1tzIBxgm8NxUg
> Content-Length: 178
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 178 out of 178 bytes
< HTTP/1.1 403 Forbidden
< content-length: 19
< content-type: text/plain
< date: Tue, 09 Nov 2021 10:25:51 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 0
< 
* Connection #0 to host iris.test.35.127.145.71.nip.io left intact
RBAC: access denied* Closing connection 0

### Version

```prose
version 1.9.0
```

**Comment by yangminzhu** [comment]
could you try to follow the troubleshooting guide https://istio.io/latest/docs/ops/common-problems/security-issues/#authorization-is-too-restrictive-or-permissive and see if it helps?
