### ISSUE TITLE
Helm Charts

### ISSUE THREAD

**Issue by InTheCloudDan** [istio/istio#3597]
Documentation at: https://github.com/istio/istio/tree/master/install/kubernetes/helm is not clear that you need to run updateVersions.sh before trying to install the helm chart. Without that you run into:

```                                                                                 
Error: render error in "istio/charts/zipkin/templates/service.yaml": template: istio/charts/zipkin/templates/service.yaml:11:18: executing "istio/charts/zipkin/templates/service.yaml" at <.Values.service.type>: can't evaluate field type in type interface {}
```

Documentation is also wrong for enabling RBAC: https://github.com/istio/istio/tree/master/install/kubernetes/helm#rbac It is now enabled by default. So if you want to run without it need to set it to false

**Comment by linsun** [comment]
close this as this is now moved to istio.io -- ttps://preliminary.istio.io/docs/setup/kubernetes/helm-install.html
