### ISSUE TITLE
Evaluating an attribute not in the request's context should return a zero value, not an error

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3598]
@ZackButcher commented on [Mon Feb 27 2017](https://github.com/istio/old_mixer_repo/issues/285)

Today if you try to call the mixer without specifying all of the attributes required to satisfy all expression evaluated at runtime the call will fail. This is because we return errors when we evaluate expressions that contain attributes that are not in the request's attribute bag. Rather than failing the evaluation, we should return a zero value instead so that we can always continue with reasonable values at runtime.

@mandarjog points out that some of the cases aren't straightforward: e.g. what's the zero value of an email?

---

@kyessenov commented on [Mon Feb 27 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-282827775)

I think it would wise to never throw errors in expressions (think mysql, jquery, etc). It's up to you to assign values to undefined expressions such as 1/0 or empty email address.

---

@mandarjog commented on [Mon Feb 27 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-282859187)

I agree that a *user* should never see a 500 because something could not be evaluated.

We could start with -- in case of an error Expression gets its baseTypes' default value.
We could let the user specify an alternate value, in case of an evaluation failure. 

---

@ldemailly commented on [Tue Oct 03 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-333872073)

I agree the | "unknown" needed all over isn't right

---

@RoeyMaor commented on [Tue Oct 03 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-334060829)

The problem is that for many VALUE_TYPEs default value literals cannot be created. perhaps the approach should be the same as with the "ip" function defined here: https://github.com/istio/mixer/blob/535eb564667cef6aed334cb4f5e967a104768387/pkg/expr/func.go that allows creating IP_ADDRESS literals from strings. Maybe part of the solution is to define similar functions for the other VALUE_TYPEs that allow to create literals, that way we don't enforce "weird" zero values on the user and give him the option to use whatever values it wishes, 
and he might even choose to use those not as default values, but as the actual values for testing. Another discussion is whether These "new" string->value_type_literal functions should crash when the string given as input doesn't match their logical type format ("istio.io" as email, "42" as a timestamp, etc)
regardless of this, indeed when no default value is stated, there should be a warning rather than an error

---

@mandarjog commented on [Wed Oct 04 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-334165676)

Forcing the user to give default value for an expression is similar to forcing a user to catch an exception. It is explicit and there are no surprises.

`ip` or other type conversion functions let you specify a typed default values, including create a typed literal. We are adding all those shortly, however that does not address the usability issue.

If that is turned into a warning, the

re: Crashing, Mixer should never crash because of user input. However evaluation may fail. 
Typing error of the kind you suggest are caught during validation stage. These do not result in runtime errors.

We can add `missingAttributePolicy` as separate settings for `{report, check} X {predicate, mapping}`. 
I wonder how UX would be when things don't work as expected.

---

@ldemailly commented on [Wed Oct 04 2017](https://github.com/istio/old_mixer_repo/issues/285#issuecomment-334335204)

IMO it's not similar because the compiler doesn't tell you you should catch said exception
the default/least surprise (and smallest config input/least inconvenience to authors) 
is to have 1 or 2 level of default (per type and optional per attribute) and only throw if specifically asked to throw vs the other way around (ie a `throw_if_nil(attribute.foo)`)

**Comment by wora** [comment]
I worked on proto3, gRPC and Google APIs, and contributed to many design decisions there. Based on our experience working with many APIs, I highly recommend Mixer to use `proto3` default semantics, e.g. every attribute has default value of `0`, `'"`, `[]`, or `{}`.

The reason is that mixer client and mixer will always be out of sync in practice, and there is no way to tell the difference. Using proto3 natural defaults is the simplest and safest choice, because all proto3 based APIs work this way.

When we designed proto3, we had a decade of production experience with proto2. The proto3 default value semantics match the real world much better than proto2. Nowadays, thousands of products are using proto3 based APIs, and this design decision stands well in the real world.

**Comment by mandarjog** [comment]
We can stick to proto3 defaults.
However the default values may not be valid or reasonable, as mixer has more data types than proto3 elementary types.
Like we said before there is no reasonable default for data type email_address. 

The current mixer protocol has ability to detect presence even though it is proto3. That is why we have the | operator which selects the first “present” attribute.

It puts the onus on the operator to explicitly provide default values at the point of use.

**Comment by ldemailly** [comment]
having to sprinkle `| "unknown"`all over  is quite a sign that something is wrong, don't you agree?

because some type don't have a good default (btw empty is a fine default for an email) doesn't mean every single rule/line needs to have one specified or risk an error

**Comment by wora** [comment]
I totally agree with Laurent.

After working with thousands of proto APIs, I am pretty confident that we
don't need default or presence in general. Developers are just fine without
them.

If you let operators choose their defaults, each one will choose something
different. No one can ensure another person's config. Why empty string is
not good enough for email address? Does anyone want to learn how to spell
"unknown" in Korean?

Mixer will be far better off if we remove presence entirely and force
everyone to use proto3 defaults. 2% people will be upset, but the global
consistency and simplicity will pay off hugely.

**Comment by ldemailly** [comment]
If it is solved/fixed mark it as fixed/closed (which pr or doc) - I haven't looked at mixer rules recently so happy to know if `| "unknown"` aren't needed anymore ? if it's ongoing/future leave it open until it is fixed?

at minimum I would think the samples still need cleanup ?
https://github.com/istio/istio/search?q=%60%7C+%22unknown%22&unscoped_q=%60%7C+%22unknown%22

**Comment by kyessenov** [comment]
It's going to take longer to finish than stale bot waits for. But it's on the roadmap I think.

**Comment by ldemailly** [comment]
I let the stale bot closes a lot of valid issues in hope maybe the team would look at the effect of that bot... but couldn't resist reopening this one. I don't think issues should be closed just because they are on the roadmap... but then again I disagree with a lot of how the project has been driven.

**Comment by douglas-reid** [comment]
This was a valid concern. Improvements here would have made the lives of operators better.

But, there is no progress being made here, and work is shifting to the new architecture -- implying changes in config models, etc. As a result, this request for enhancement has been overcome by events. I'm going to close this issue.

We can revisit this in the context of any CEL-based tooling we build for future Istio extensions.
