### ISSUE TITLE
Patch EDS type Clusters

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#35981]
### Bug Description

When using `EnvoyFilters` to patch `Cluster's transport_socket.tls`, if the Cluster type is EDS, patch is not working. 
patching EDS type clusters only works with `DestinationRule API`. 

### Version

```prose
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (4 proxies)
```

**Comment by GregHanson** [comment]
@Arsen-Uulu Can you provide a sample EnvoyFilter you are trying to apply - using either the sleep or httpbin sample applications?
