### ISSUE TITLE
Test that istioctl kube-inject works without access to the cluster

### ISSUE THREAD

**Issue by frankbu** [istio/istio#36000]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

This is a followup to #35746.

`istioctl kube-inject` should work without access to the cluster, i.e. using an XDS address (which may be an east-west gateway or an external istiod) and a root cert from a file. The current integration test (`TestKubeInject`) gets the cert needed to access istiod by reading the value in the cluster's webhook.

In a CI/CD system we may not provide access to the cluster's webhooks. `istioctl` would run with a KSA with minimal RBAC permissions - just deploy in a specific namespace and nothing else.

`istioctl` should work, but we need to test it this way.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Isn't that just 

```
  # Use kube-inject based on captured configuration
  istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml \
    --injectConfigFile /tmp/inj-template.tmpl \
    --meshConfigFile /tmp/mesh.yaml \
    --valuesFile /tmp/values.json
```

?

I assumed this had unit tests but maybe not

**Comment by frankbu** [comment]
@howardjohn Yes, that's the idea, but unless I've missed it, I don't think we have an integration test that tests it that way. The current external control plane test is close, but it "cheats" be reading the caBundle from the webhook, which it has access to in the integration test env.

**Comment by howardjohn** [comment]
I don't think we need an integration test to test code that has no network
dependencies. It's just a unit test which we do have?

**Comment by frankbu** [comment]
Actually, the URL and certs that `istioctl kube-inject` uses are not command args, but are rather set using environment variables or values in `$HOME/.istioctl/config.yaml` (which can also be changed via env var `ISTIOCONFIG=my-istioctl-config.yaml`). Specifically, the `ISTIOCTL_XDS_ADDRESS` and `ISTIOCTL_CERT_DIR` [environment variables](https://istio.io/latest/docs/reference/commands/istioctl/#envvars).

Setting the xds address is tested when running the current istioctl-kubeinject integration test [setup here](https://github.com/istio/istio/blob/c299498b663e7a882ce481eb51201c42d5978b47/pkg/test/framework/components/istio/operator.go#L941), but I don't believe there is any test that istioctl works with a configured cert dir value.
