### ISSUE TITLE
Enable more istiod remote security tests

### ISSUE THREAD

**Issue by frankbu** [istio/istio#36002]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Most of the security tests have been enabled to run with an external control plane, but #35599 has disabled some that were failing. Most of the skipped tests are failing because they need a customized istiod configuration, but the test assumes it's customizing a default primary cluster install.

We should look at these skipped tests and decide whether or not there is value in running them with an external control plane and for any that do we will need to modify the test to recognize when it is running with an external control plane topology and update the external control plane configuration appropriately.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ericvn** [comment]
Pointer to the current job history: https://prow.istio.io/job-history/gs/istio-prow/pr-logs/directory/integ-security-istiodremote-tests_istio?buildId=
