### ISSUE TITLE
About mutli prometheus pods cooperation

### ISSUE THREAD

**Issue by rtttech** [istio/istio#36018]
Is there any cooperation mechanism between  prometheus pods if there are many of them in istio-system namespace for large scale scene. Do they just do the same metric collection  job periodicly without splitting the job?

**Comment by bianpengyuan** [comment]
The prometheus yaml shipped with Istio is just a demo and It is out of Istio scope to make it work at production scale. You should look for guidelines from prometheus community how to split scraping and do federate, and I am sure there are plenty blog post outside about this. Thanks!
