### ISSUE TITLE
Pilot queue optimization / review

### ISSUE THREAD

**Issue by costinm** [istio/istio#3601]
queue.Run code seems very dangerous/strange:
- seem to spin in a for loop - protected only by the rate limiter for events. 
- if item.handler() fails - it'll go in a loop, and worse will sleep - preventing processing of other events.

**Comment by sdake** [comment]
I've found the part of the cache recompute to be extremely expensive in BuidIngressRoutes() in terms of object conversion from YAML/JSON as it relates to garbage collection with a large number of endpoints (1000) and ingress routes (50).  The cache clears on https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/discovery.go#L505 come in at a high rate (~200 events from Envoy for 1k endpoints).  The hot event is https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/discovery.go#L697.

**Comment by costinm** [comment]
Is this with the new env variable to squash ? If you tune it to larger
values - it become bearable.

As we move to v2 and grpc, we can do a much better caching, 99% of the
listeners/clusters are the same
for all endpoints ( the 'out' ), each workload has just 1 'unique'
cluster/listener per port it exposes. In addition,
we can keep the endpoint-specific listener/cluster in a static config,
maybe generated (for faster/safer startup),
since v2 can combine static and dynamic configs. So not very worried about
that, and probably little value
to optimize v1/json further, if the squash does its job.

However this bug is about the queue.go and Run method - which seems to be
spinning, if you set the
throttle to 0 it gets into loop. There is no mutex or channel waiting for
events, it was relying on the event throttle.

We probably need to separate workload ( endpoint / EDS ) processing - as
part of the EDSv2 (which is very
important for multicloud) from the config queue (routes, services, etc) -
but until it happens the queue is
pretty central.

**Comment by ldemailly** [comment]
subscribe

**Comment by sdake** [comment]
Re reporting in this issue, @ldemailly requested I do that here.  Re squash env variable, I was using an older master and haven't tried that.  I considered a solution similar to that when looking at the general problem.  I'll try out squash with larger values - agree seems little point in optimizing v1 beyond getting it functional.

Re v2 and grpc, perhaps this has been discussed and you sort of implied this was viable in your response.  Why not build the response cache (similar to what you propose) dynamically and incrementally?  The current design is throwing away a lot of information in the events received from the service registries.  Do you know if there is enough information in the various events to incrementally compute the mesh and dynamically build and manage the response cache?  Anyway, didn't mean to ninja your bug id :)

**Comment by costinm** [comment]
On Tue, Feb 20, 2018 at 3:39 AM, Steven Dake <notifications@github.com>
wrote:

> Re reporting in this issue, @ldemailly <https://github.com/ldemailly>
> requested I do that here. Re squash env variable, I was using an older
> master and haven't tried that. I considered a solution similar to that when
> looking at the general problem. I'll try out squash with larger values -
> agree seems little point in optimizing v1 beyond getting it functional.
>
> Re v2 and grpc, perhaps this has been discussed and you sort of implied
> this was viable in your response.
>
We must move to v2 ( with or without grpc ) because v1 is deprecated and
lacks some P0 features ( SNI in particular ).
It is also push-based - so we can deliver changes immediately, even without
short refresh interval.



> Why not build the response cache (similar to what you propose) dynamically
> and incrementally?
>

I think it is built incrementally in v1 - but 99% of the content is shared
across all sidecars, the responses are almost
identical for each envoy.

LDS,CDS,RDS only change when new configs ( including Service ) are pushed -
they should be pretty stable, so
could have pretty large refresh with push, and the numbers will not be huge
( 10k rules/services ? ). I personally
don't think it's worth optimizing them much, or they'll need a per-sidecar
cache. But would be happy to see
others have fun with it, if it's kept readable :-)

For EDS - and workload (and clusters) starting and stoping - yes, I think
that's the critical part, and building
them incrementally is probably one of the first steps.


> The current design is throwing away a lot of information in the events
> received from the service registries. Do you know if there is enough
> information in the various events to incrementally compute the mesh and
> dynamically build and manage the response cache?
>
IMO with v2 we'll not need a cache ( as in 'keep the full response for a
request' ), as long as we keep pre-computed
pieces in proto format in the structs. I haven't spent too much looking at
LDC/CDS/RDS events - since I don't expect
really large numbers or high rate of change - but for EDS pretty sure the
events allow incremental event processing,
and we may be able to deliver the endpoint only to sidecars that need it
(at least assuming some small changes
in envoy).



> Anyway, didn't mean to ninja your bug id :)
>
As long as it's not slack :-)

I personally prefer email - but issues are fine too, there is an archive
and it's slightly on subject.

**Comment by rshriram** [comment]
fixed with ADS and more optimizations from costin
