### ISSUE TITLE
How to customize your own ingressgateways

### ISSUE THREAD

**Issue by peixiaoqing** [istio/istio#36046]
istio version：`1.11.4`
Demand background：Due to many projects, the built-in istio-ingressgateway may not meet the needs, so
 1. Create a new namespace; 
 2. Create a custom ingressgateway in the new space; 
 3. Use this ingressgateway;

Hello, developer, I encountered a problem in creating a new custom ingressgateways. According to the official document https://istio.io/latest/docs/setup/additional-setup/customize-installation/ Configure gateways, I can’t create a custom one ingressgateway, is there a complete creation document or a complete example for reference?

The yaml file I wrote in accordance with the official document is:
The path is: `manifests/profiles/cust.yaml`
![image](https://user-images.githubusercontent.com/35130532/141426770-43cb8384-06f7-42e1-87ce-67fefa1428e0.png)

The creation command is: `istioctl install -f cust.yaml`
Error message: Error: generate config: validation errors (use --force to override):
unknown field "customgateway-ingressgateway" in v1alpha1.GatewaysConfig
![image](https://user-images.githubusercontent.com/35130532/141427140-8ff257d2-1312-4e46-a8e9-8787d947c7d9.png)

**Comment by offSwitch** [comment]
read this
https://istio.io/v1.5/docs/reference/config/installation-options/#gateways-options

**Comment by howardjohn** [comment]
One limitation of the `values` is it can only apply to all gateways. I recommend following https://istio.io/latest/docs/setup/additional-setup/gateway/  which gives some alternatives (tl;dr one IstioOperator per gateway)

**Comment by peixiaoqing** [comment]
> 阅读这个 https://istio.io/v1.5/docs/reference/config/installation-options/#gateways-options



> 阅读这个 https://istio.io/v1.5/docs/reference/config/installation-options/#gateways-options

Thanks for answering, I have found the most suitable solution https://cloud.ibm.com/docs/containers?topic=containers-istio-custom-gateway Thanks again

**Comment by peixiaoqing** [comment]
> 的一个限制`values`是它只能适用于所有网关。我建议遵循https://istio.io/latest/docs/setup/additional-setup/gateway/ 这提供了一些替代方案（tl;dr 每个网关一个 IstioOperator）

Thanks for answering, I have found the most suitable solution https://cloud.ibm.com/docs/containers?topic=containers-istio-custom-gateway Thanks again

**Comment by howardjohn** [comment]
Sounds like its resolved by ^. Thanks
