### ISSUE TITLE
Problems connecting to Pilot after upgrading 1.10 to 1.11

### ISSUE THREAD

**Issue by brgsousa** [istio/istio#36050]
### Bug Description

After upgrading from Istio 1.10.2 and k8s 1.20.6 to Istio 1.11.4 and k8s 1.21.5 , ingressgateway pods started logging "gRPC config stream closed: 14" errors many times. I know it may indicate problems connecting to Pilot but I don't know what. Gateways often take a long time to start and stay in a healthy state, something about 5 or 10 minutes.
Errors:
```
2021-11-12T07:47:35.817174Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T07:47:56.284345Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T07:48:17.831940Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T07:48:40.136767Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T07:49:02.302485Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T07:49:29.052264Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
2021-11-12T08:17:14.389642Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:
2021-11-12T08:46:07.376008Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:
2021-11-12T08:46:27.568230Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.96.93.192:15012: i/o timeout"
```

I have installed Istio using these parameters:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
            patches:
            - path: kind
              value: DaemonSet
            - path: spec.strategy
            - path: spec.updateStrategy
              value:
                rollingUpdate:
                  maxUnavailable: 50%
                type: RollingUpdate
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        env:
          ISTIO_META_HTTP10: '1'
    pilot:
      env:
        PILOT_HTTP10: '1'
```

Outputs for the commands below are attached:
kubectl get configmap -n istio-system -o jsonpath={.data.mesh} istio > meshconfig.yaml
[meshconfig.yaml.txt](https://github.com/istio/istio/files/7527282/meshconfig.yaml.txt)
kubectl logs -n istio-system -l app=istiod --tail=100000000 > istiod.log
[istiod.log.txt](https://github.com/istio/istio/files/7527283/istiod.log.txt)
kubectl -n istio-system get IstioOperator installed-state -o yaml > istio-operator.yaml
[istio-operator.yaml.txt](https://github.com/istio/istio/files/7527289/istio-operator.yaml.txt)

### Version

```prose
# istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (15 proxies)
# kubectl version --short
Client Version: v1.21.5
Server Version: v1.21.5
# helm version --short
v3.7.1+g1d11fcb
```

**Comment by howardjohn** [comment]
io timeout generally means network connectivity issues but in this case it does work eventually... can you curl istiod without issue (try port 443 since it is http instead of gRPC)?

**Comment by brgsousa** [comment]
@howardjohn thank you for replying. I tried this:
```
istio-proxy@istio-ingressgateway-mg67v:/$ while sleep 1; do curl -sS istiod.istio-system:15014/version; echo ""; done
curl: (28) Failed to connect to istiod.istio-system port 15014: Connection timed out

curl: (28) Failed to connect to istiod.istio-system port 15014: Connection timed out

curl: (28) Failed to connect to istiod.istio-system port 15014: Connection timed out

1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
curl: (28) Failed to connect to istiod.istio-system port 15014: Connection timed out

1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean
curl: (28) Failed to connect to istiod.istio-system port 15014: Connection timed out

1.11.4-9f6f03276054bb62a1b745630322314ef14969e8-Clean    
```


```
kubectl describe service istiod -n istio-system
Name:              istiod
Namespace:         istio-system
Labels:            app=istiod
                   install.operator.istio.io/owning-resource=unknown
                   install.operator.istio.io/owning-resource-namespace=istio-system
                   istio=pilot
                   istio.io/rev=default
                   operator.istio.io/component=Pilot
                   operator.istio.io/managed=Reconcile
                   operator.istio.io/version=1.11.4
                   release=istio
Annotations:       <none>
Selector:          app=istiod,istio=pilot
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.93.192
IPs:               10.96.93.192
Port:              grpc-xds  15010/TCP
TargetPort:        15010/TCP
Endpoints:         10.244.1.24:15010,10.244.2.190:15010
Port:              https-dns  15012/TCP
TargetPort:        15012/TCP
Endpoints:         10.244.1.24:15012,10.244.2.190:15012
Port:              https-webhook  443/TCP
TargetPort:        15017/TCP
Endpoints:         10.244.1.24:15017,10.244.2.190:15017
Port:              http-monitoring  15014/TCP
TargetPort:        15014/TCP
Endpoints:         10.244.1.24:15014,10.244.2.190:15014
Session Affinity:  None
Events:            <none>
```

Cluster was working fine before upgrade... What kind of network connectivity issues could it be?

**Comment by howardjohn** [comment]
Interesting... maybe something on the node is using a bunch of CPU or something and its getting really throttled?

I would maybe try a similar test with two non-istio pods (say curl + httpbin or similar). If it fails there it would be a pretty clear indication its not Istio specific (unless Istio is the thing using a lot of CPU and causing throttling...)

**Comment by brgsousa** [comment]
I tried looking for a pod using a bunch of CPU but didn't find any.... Check the output from k9s (pods) and lens (nodes)
![k9s](https://user-images.githubusercontent.com/11218051/141524176-a386ac59-53e9-4dd9-9231-c77e91c2bbda.png)
![lens](https://user-images.githubusercontent.com/11218051/141524195-26997281-ebc1-4f7a-a79f-78a32372405c.png)

I tried testing communication between two non-istio pods (using _while sleep 1; do curl -sS another-non-istio-pod; echo ""; done_) but it works fine.

**Comment by howardjohn** [comment]
Ok... very odd. Istiod is basically just serving a very basic golang http server there, so nothing special. Aside from load on the node/network/CPU, I can't see any reason it would intermittently refuse connections.

**Comment by brgsousa** [comment]
Could it be related to the fact that my ingress gateway is deployed as daemonset or that my egress gateway has 2 replicas?

**Comment by brgsousa** [comment]
Another observation is that that problem only occurs when the pod is in the same node and istiod pod:
![image](https://user-images.githubusercontent.com/11218051/142642209-3ab87709-dd5e-41b3-ae81-c301f145e151.png)

**Comment by brgsousa** [comment]
I upgraded k8s from 1.21.5 to 1.21.7 (using flannel 0.14.0) but the issue remains.

Also... On another namespace, I have just tried (as a test) one pod communicating with another pod in the same node and it works fine.

**Comment by brgsousa** [comment]
Still in namespace istio-system the communication problem exists between kiali and prometheus as well . If I start kiali and prometheus on same node, they won't communicate with each other:
`[kiali@kiali-d85cc8859-jpqgl kiali]$ curl http://prometheus.istio-system:9090/api/
v1/status/flags
curl: (7) Failed to connect to prometheus.istio-system port 9090: Connection timed out`
![image](https://user-images.githubusercontent.com/11218051/142665751-3fdd1adc-03ec-4aac-bf08-e81656836ea7.png)

But if I force them to be on different nodes, it works:
`[kiali@kiali-d85cc8859-jpqgl kiali]$ curl http://prometheus.istio-system:9090/api/v1/status/flags
{"status":"success","data":{"alertmanager.notification-queue-capacity":"10000","alertmanager.timeout":"","config.file":"/etc/config/prometheus.yml","enable-feature":"","log.format":"logfmt","log.level":"info","query.lookback-
delta":"5m","query.max-concurrency":"20","query.max-samples":"50000000","query.timeout":"2m","rules.alert.for-grace-period":"10m","rules.alert.for-outage-tolerance":"1h","rules.alert.resend-delay":"1m","scrape.adjust-timestam
ps":"true","storage.exemplars.exemplars-limit":"0","storage.remote.flush-deadline":"1m","storage.remote.read-concurrent-limit":"10","storage.remote.read-max-bytes-in-frame":"1048576","storage.remote.read-sample-limit":"500000
00","storage.tsdb.allow-overlapping-blocks":"false","storage.tsdb.max-block-duration":"1d12h","storage.tsdb.min-block-duration":"2h","storage.tsdb.no-lockfile":"false","storage.tsdb.path":"/data","storage.tsdb.retention":"0s"
,"storage.tsdb.retention.size":"0B","storage.tsdb.retention.time":"15d","storage.tsdb.wal-compression":"true","storage.tsdb.wal-segment-size":"0B","web.config.file":"","web.console.libraries":"/etc/prometheus/console_librarie
s","web.console.templates":"/etc/prometheus/consoles","web.cors.origin":".*","web.enable-admin-api":"false","web.enable-lifecycle":"true","web.external-url":"","web.listen-address":"0.0.0.0:9090","web.max-connections":"512","
web.page-title":"Prometheus Time Series Collection and Processing Server","web.read-timeout":"5m","web.route-prefix":"/","web.user-assets":""}}`
![image](https://user-images.githubusercontent.com/11218051/142666184-ba7a9f5e-27f9-4d83-8dd1-bbaa33c5be78.png)

**Comment by howardjohn** [comment]
Given kiali + prometheus are not using anything istio specific, i suspect
this is a lower level Kubernetes networking issue

**Comment by brgsousa** [comment]
@howardjohn , you are right. But the weird thing is that the problem only occurs with pods inside "istio-system" namespace

**Comment by brgsousa** [comment]
I figured out what was missing: 
```
modprobe br_netfilter
echo "br_netfilter" >> /etc/modules-load.d/modules.conf
```

At same point, I restarted those nodes and br_netfilter didn't load up automatically. Now that it is written in  /etc/modules-load.d/modules.conf , it does apply on boot.

Thank you for your support.
