### ISSUE TITLE
Too many default metrics in envoy

### ISSUE THREAD

**Issue by Stono** [istio/istio#36051]
### Bug Description

Hi, 
"back in the day" there was a lot of noise/junk metrics being exported from the sidecar.  All this adds up to:

- increased memory footprint of the sidecar
- increased scrape duration & data transfer to prometheus

Particularly "at scale".

Stats inclusion matches were added (https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats), and many default metrics that weren't considered essential were removed which helped a lot, but I feel like there's slowly more junk creeping back in that isn't "essential", https://github.com/istio/istio/issues/36049 as an example of what i'm seeing in 1.12.

However pre 1.12, I still think there's _loads_ of stuff that surely isn't essential, for example in this output [prometheus.txt](https://github.com/istio/istio/files/7527885/prometheus.txt), which was generated with:

```
      proxyStatsMatcher:
        inclusionSuffixes:
        - outlier_detection.ejections_active
        - upstream_cx_active
        - upstream_cx_total
```

We have loads of `envoy_cluster_http2.*` metrics, `envoy_server_.*` stuff, `envoy_listener_manager` and `envoy_cluster_manager` type histogram buckets.  Are they really all required?

Considering the work that went into getting the amount of metrics exposed by the sidecar right down, are there any tests tracking that it doesn't regress (like all those additional ones in 1.12)?

> Note including more Envoy stats might increase number of time series collected by prometheus significantly. Care needs to be taken on Prometheus resource provision and configuration to reduce cardinality.

https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

### Version

```prose
1.12-beta2
```

**Comment by howardjohn** [comment]
We should at the very least have a test that captures the set of metrics we expose to make sure we are conscious of changes. Maybe its not strictly related to this issue though
