### ISSUE TITLE
EDS missing endpoints after resource changed

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#36056]
### Bug Description

 Hello everyone!
 I'm opening this issue as I noticed what seems to be some misbehaviour in the EDS.
 In particular, I noticed that if you change the label to a pod after it has been created it will not be taken into consideration when building the endpoints.
 This will result in 503 errors as I have a "subset" in the DestinationRule that is supposed to match that specific label.
 
 I managed to reproduce the issue with Istio 1.11.4 and Istio 1.12-beta2

 The step to reproduce it are quite easy:

 0. Download the yaml manifests which you can find here: [yaml_resources.zip](https://github.com/istio/istio/files/7529010/yaml_resources.zip)
 1. Install Istio with controller + Ingress Gateway
 2. Deploy httpbin.yaml that comes with podapp=httpbin label by default
 3. Wait for httpbin to be ready.
 4. Apply the broken=httpbin label to the httpbin podapp via `kubectl label pod HTTPBIN_POD_NAME broken=httpbin`
 5. Deploy vs_dr.yaml (note that the file includes a gw as well, sorry for the misleading name) and check the endpoints in the gateway (**only endpoints for podapp are available**)
 ```ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.63.31.6:8443                  HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
172.17.0.12:44134                HEALTHY     OK                outbound|44134||tiller-deploy.kube-system.svc.cluster.local
172.17.0.2:53                    HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
172.17.0.2:9153                  HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
172.17.0.5:4443                  HEALTHY     OK                outbound|443||metrics-server.kube-system.svc.cluster.local
172.17.0.6:8080                  HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.6:8443                  HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.6:15021                 HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.7:80                    HEALTHY     OK                outbound|8000|podapp|httpbin.default.svc.cluster.local
172.17.0.7:80                    HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
172.17.0.8:15010                 HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
172.17.0.8:15012                 HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
172.17.0.8:15014                 HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
172.17.0.8:15017                 HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
unix://./etc/istio/proxy/XDS     HEALTHY     OK                xds-grpc
```

 6. You can confirm that things are not working by making a `curl GATEWAY_URL/status/200 -i` and `curl GATEWAY_URL/status/201 -i`. Only the first one will work as that is handled by the "podapp" subset. The status/201 request that is handled by the "broken" subset label is returning 503 instead of 201.
 6. Restart the controller and check the endpoints again. You will find soon enough that both the one for "podapp" and "broken" are present now. Note that restarting the ingress-gateway will not yield to any improvement (only the restarting of the controller will do).
 `curl GATEWAY_URL/status/201 -i` will now return the expected 201 status code and not 503.
  ```
ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.63.31.6:8443                  HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
172.17.0.12:44134                HEALTHY     OK                outbound|44134||tiller-deploy.kube-system.svc.cluster.local
172.17.0.2:53                    HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
172.17.0.2:9153                  HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
172.17.0.3:15010                 HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
172.17.0.3:15012                 HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
172.17.0.3:15014                 HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
172.17.0.3:15017                 HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
172.17.0.5:4443                  HEALTHY     OK                outbound|443||metrics-server.kube-system.svc.cluster.local
172.17.0.6:8080                  HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.6:8443                  HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.6:15021                 HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
172.17.0.7:80                    HEALTHY     OK                outbound|8000|broken|httpbin.default.svc.cluster.local
172.17.0.7:80                    HEALTHY     OK                outbound|8000|podapp|httpbin.default.svc.cluster.local
172.17.0.7:80                    HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
unix://./etc/istio/proxy/XDS     HEALTHY     OK                xds-grpc
```

 **Note that the issue does not appear if the label is added before the Istio controller is even started.**

### Version

```prose
$ istioctl version
client version: 1.12.0-beta.2
control plane version: 1.12.0-beta.2
data plane version: 1.12.0-beta.2 (1 proxies)
$ kubectl version --short
Client Version: v1.18.2
Server Version: v1.20.2
$ helm version --short
v3.4.0+g7090a89
```

### Additional Information

 [bug-report.zip](https://github.com/istio/istio/files/7529029/bug-report.zip)

**Comment by LithiumSR** [comment]
Here are the yaml manifests that you can use to reproduce the issue on your own
[yaml_resources.zip](https://github.com/istio/istio/files/7529010/yaml_resources.zip)

**Comment by dddddai** [comment]
Hi, in your deployment you specified:
```yaml
annotations:
    sidecar.istio.io/inject: "false"
```
which means the sidecar would not be injected, I guess you misconfigured the deployment?
But anyway I did reproduce this though the sidecar is injected

**Comment by LithiumSR** [comment]
Hey!
Yes, the inject=false was intentional, I wanted to take the sidecar out of the picture as I already reproduced the issue with it injected.
Also, I tested your WIP PR and I can confirm that the issue is no longer present.

Thank you for looking into it

**Comment by hzxuzhonghu** [comment]
@dddddai @LithiumSR trying to understand the scenario, when pod label changed, the endpoints will be updated, right?

So istio eds will be refreshed, as no serviceentry is used, how could this happen?

**Comment by LithiumSR** [comment]
I may be wrong, but I don't think ServiceEntry is required for this scenario.
The usage and definition of subsets in the VS and DR respectively is responsible for firing up the EDS.

Just to recap the scenario, what I did in the example was:
1. Create Service and Deployment for httpbin (I used an httpbin without sidecar but that does not influence the outcome)
2. Create GW for httpbin and create VS and DR.
VS specify two URI matched by regexes each of one handled by a different subset.
Subsets are specified in the DR and depends on the httpbin labels.
One subset uses a label that was defined in the pod template of the deployment, the other subset a label that is not yet found in the httpbin pod
3. Dynamically add the label required for the other subset to work.

**Observed outcome**: The added label is not taken into consideration by Istio if it was running before the new label was applied. Consequently, all the requests that match the subset which relies on that label are failing.

I realized from the discussion in the @dddddai's PR that this very peculiar use-case is not supported (and it's also a bad-practice). Nonetheless, if it does not require too much work to support (and if does not impact other use-cases), I think it would be nice to have supported.

**Comment by hzxuzhonghu** [comment]
Catched up now. I can hardly imagine the real use case. Can you provide some ones, and we can trade off?

**Comment by emike922** [comment]
I do not know specifics about this particular case, will leave that to @LithiumSR, but asking generally:

What can or do we know about the requirements and circumstances that applications/developers using or migrating to Istio are subject to?
There may be actual technical reasons requiring them to dynamically (re)label pods (maybe custom leader election schemes?). Or it may be historically how the application has been designed. Or they could be simply unaware of better solutions...

Whatever the case may be, should we not leave that decision/flexibility to the application if possible?
And even if considered a bad practice, it might allow them to adopt a more suitable solution at their own pace rather than being barred from using Istio until that time?

**Comment by LithiumSR** [comment]
Hello @hzxuzhonghu 
Sorry for the late reply.
In my case "dynamic" labeling would come in handy for the a pseudo-stateful server that comes with a somewhat-legacy logic.
In particular, I have that some specific labels are dynamically applied to each server pod during their lifecycle and those labels are used to help in routing the traffic between the clients and the server instances.

Based on the situation the client is provided with a label that acts like a marker to route its request to the desired server pod.
Given the nature of the labels those cannot be decided beforehand and applied directly via the pod-template of the deployment.

Obviously, this logic can not work properly if the Istio does not fire the EDS update each time the labels are changed.

I know that it is a very peculiar use case... Regardless of that, firing an EDS update after label changes still sounds like the correct behavior to have.
