### ISSUE TITLE
make the sum of weights across destinations configurable.

### ISSUE THREAD

**Issue by ryan4yin** [istio/istio#36069]
**Describe the feature request**

>The proportion of traffic to be forwarded to the service version. (0-100). Sum of weights across destinations SHOULD BE == 100. If there is only one destination in a rule, the weight value is assumed to be 100.

configurable `weight_total` is useful, we need a more fine-grained control over the canary release, e.g. `weight_total=1000`.

the limit `weight_total=100` is not enough for us.

related issue: https://github.com/istio/istio/issues/18213
related docs: [VirtualService - HTTPRouteDestination](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
It would probably be ideal to just not require summing to 100? Then you can put something like `weight=2; weight=1`.

**Comment by ryan4yin** [comment]
@howardjohn yeah, I think it's reasonable and meets our needs.

**Comment by hzxuzhonghu** [comment]
I agree requiring total weight = 100 is a little bad. But not sure i understand a more fine-grained weight control. I am seeing no much diff between 1% and 0.1% in real case.

**Comment by prabhu-mannu** [comment]
1% and 0.1% makes huge difference in high traffic applications/services, we ended up using haproxy for few of our applications to active 0.01%, it has proven very useful for us.
Removing constraint that total needs to be 100 would help, or rising the maximum value to 1000 would be also help.

**Comment by ryan4yin** [comment]
> 1% and 0.1% makes huge difference in high traffic applications/services, we ended up using haproxy for few of our applications to active 0.01%, it has proven very useful for us. Removing constraint that total needs to be 100 would help, or rising the maximum value to 1000 would be also help.

agree with this

**Comment by hzxuzhonghu** [comment]
Make sense, got it

**Comment by hzxuzhonghu** [comment]
Great weaken the validation is permitted according to https://github.com/istio/api/blob/master/GUIDELINES.md

**Comment by fatedier** [comment]
@hzxuzhonghu Is there any plan to support it in the code?

**Comment by hzxuzhonghu** [comment]
Sorry for forget it, will do that.
