### ISSUE TITLE
Unable to configure TLS origination with postgres

### ISSUE THREAD

**Issue by iprasla** [istio/istio#36093]
### Bug Description

This issue is opened in reference to https://github.com/istio/istio/issues/29761. There were not any clear instructions on how to reopen the issue therefore I am opening this issue to get some activity on this issue.

### Version

```prose
istioctl version --remote
client version: 1.6.7
control plane version: 1.7.3-asm.6
data plane version: 1.7.3-asm.6 (17 proxies)

kubectl version --short
Client Version: v1.18.3
Server Version: v1.17.13-gke.2001
```

**Comment by howardjohn** [comment]
This is working as expected. Postgres does not use TLS, it uses STARTTLS.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/33345 see also

**Comment by ceastman-ibm** [comment]
@iprasla for now the service entry protocol needs to be TCP not TLS for connecting to a postgresql backend.
