### ISSUE TITLE
FR: support global  HTTP idleTimeout config

### ISSUE THREAD

**Issue by zxh326** [istio/istio#36099]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
The default `idleTimeout` is 1 hour, with the default keep-alive value of many other languages or web frameworks, it is relatively large. This may cause some connection termination problems. I need to modify the idleTimeout values of many services to avoid this. 

Can we provide a global configuration, such as adding to [meshConfig](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.pb.go)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs 
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
@zxh326 did you mean idle_timeout on [tcp_proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto)

**Comment by zxh326** [comment]
> @zxh326 did you mean idle_timeout on [tcp_proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto)

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout

**Comment by zirain** [comment]
> > @zxh326 did you mean idle_timeout on [tcp_proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto)
> 
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout

right now you can config this via [destination-rule](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings)

what your need is an global IdleTimeout config override this maybe default value keep 1h?

**Comment by zirain** [comment]
> > @zxh326 did you mean idle_timeout on [tcp_proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto)
> 
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout

please take a look at this PR https://github.com/istio/api/pull/879
