### ISSUE TITLE
istio-cni-node used too much memory

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#36108]
### Bug Description

istio-cni-node used too much memory because of repair controller.

Every istio-cni-node used nearly 9GB memory in my cluster.

Maybe we can move repair controller to istiod ?

### Version

```prose
$ istioctl version
client version: 1.11.4
istiod version: 1.10.2
istiod version: 1.10.2
istiod version: 1.10.2
istiod version: 1.11.4
istiod version: 1.11.4
istiod version: 1.11.4
istiod version: 1.11.4
istiod version: 1.11.4
data plane version: 1.11.4 (5564 proxies), 1.10.2 (399 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cocotyty** [comment]
@howardjohn

**Comment by howardjohn** [comment]
wow. Why is it so much? I thought we were only watching pods on the same node (ie up to 110 max).

cc @bianpengyuan @stewartbutler

**Comment by bianpengyuan** [comment]
Looks like the node name is never used to filter..

**Comment by bianpengyuan** [comment]
@cocotyty does the memory grow over time? If so it is very likely that this is caused by the queue backlog.

**Comment by cocotyty** [comment]
![image](https://user-images.githubusercontent.com/2241753/142148322-c9a411e3-4f40-4a98-83e3-86df9dd687ce.png)
@bianpengyuan 
top in a new pod.

**Comment by bianpengyuan** [comment]
Ok, it is relatively small comparing to 9G, but 0.7G is still bigger than I would expect with a new pod. Would be nice if you can try out https://github.com/istio/istio/pull/36109 and see if that can improve or not.

**Comment by cocotyty** [comment]
> Ok, it is relatively small comparing to 9G, but 0.7G is still bigger than I would expect with a new pod. Would be nice if you can try out #36109 and see if that can improve or not.

I add an env "REPAIR_FIELD_SELECTORS=spec.nodeName=xxx" to the pod.

![image](https://user-images.githubusercontent.com/2241753/142156577-92c8a3a1-92de-4af6-b72b-937d0ccaffcb.png)
