### ISSUE TITLE
Mysql behind NLB with proxy-protocol hangs

### ISSUE THREAD

**Issue by liorfranko** [istio/istio#36104]
### Bug Description

I'm deploying an Ingress-gw, behind an NLB (type IP) with proxy-protocol enabled.
I already worked with AWS on solving their "Lazy headers" issue when working with NLB and proxy-protocol and verified it using tcpdump.
https://engineering.nanit.com/how-to-scale-your-cluster-to-over-2000-nodes-on-aws-eks-2aa604367104
I set the following on the NLB:
`proxy_protocol_v2.client_to_server.header_placement=on_first_ack`
When I open a connection to the NLB I see the 3-way handshake reaches directly the Envoy without hanging on the NLB and waiting for data.
But I see it's hanging on the Envoy and waiting for data.
The way I tested it was by running telnet to the NLB, waiting for a couple of seconds for the "Server Greeting", typing a letter, and pressing "Enter" after each letter.

telnet memsql-test.tcp01-lb.ua-dev.us-east-1.ironsrc.mobi 3306
Trying 10.191.37.20...
Connected to memsql-test.tcp01-lb.ua-dev.us-east-1.ironsrc.mobi.
Escape character is '^]'.
d
f
J
5.7.32�OkdEym7J��!�rDj7x6){my!^mysql_native_passwordConnection closed by foreign host.

Client IP: 10.200.25.225
NLB IP: 10.191.37.20
Envoy IP: 10.191.39.30
MySQL IP: 10.191.12.5

Here is a packet capture was taken on the client showing the traffic from the client to the NLB:
![client -  nlb](https://user-images.githubusercontent.com/20726865/142039688-0645638a-012a-4de2-ba2f-fbf17a03bd25.png)

Here is a packet capture was taken on the K8S node showing the traffic from the NLB to the Envoy and from the Envoy to the MySQL.
![nlb -  envoy -  mysql](https://user-images.githubusercontent.com/20726865/142039692-0c818209-06be-444b-bd4c-81ad7a0f889e.png)

You can see that the NLB forwards the TCP 3-way handshake packets immediately.
The Envoy waits for data to be sent from the client, and only after I generated some data the Envoy open the connection to MySQL.
This behavior doesn't work with MySQL clients, as the client hangs once the 3-way handshake is done for the "Server Greeting"

To support proxy-protocol I added EnvoyFilter:
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: tcp01-lb`

Please assist.

### Version

```prose
istioctl version
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (13 proxies)

kubectl version --short
Client Version: v1.18.9-eks-d1db3c
Server Version: v1.20.7-eks-d88609
```

**Comment by howardjohn** [comment]
I didn't have a chance to look at this closely, but please take a look at https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols if you have not.

**Comment by liorfranko** [comment]
The service port is 3306 so I should have no problem.
But I also explicitly configuring it to TCP or MySQL:
```
istioctl x describe pod tcp01-lb-86f7b54796-j4hpn.istio-ingress
Pod: tcp01-lb-86f7b54796-j4hpn.istio-ingress
   Pod Ports: 3306 (istio-proxy), 15090 (istio-proxy)
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: tcp01-lb.istio-ingress
   Port: tcp 3306/TCP targets pod port 3306


istioctl x describe pod tcp01-lb-86f7b54796-j4hpn.istio-ingress
Pod: tcp01-lb-86f7b54796-j4hpn.istio-ingress
   Pod Ports: 3306 (istio-proxy), 15090 (istio-proxy)
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: tcp01-lb.istio-ingress
   Port: mysql 3306/MySQL targets pod port 3306
Skipping Gateway information (no ingress gateway pods)
```


With both configs, I see the same issue.

**It's important to say that when I remove the proxy_protocol filter the issue is resolved.**

**Comment by howardjohn** [comment]
proxy_protocol filter has the same issues as the server first protocols
described above, I would assume (although I am not 100% sure as its not a
part of Istio core.). You cannot sniff traffic with server first protocols

**Comment by liorfranko** [comment]
So it's Envoy's limitation of running a server first protocol while enabling proxy_protocol filter?
There's nothing to do, right?
