### ISSUE TITLE
bug-report: --include is not honored

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36105]
This is currently only applying to ProxyGet stuff. We still fetch all pods in all namespaces, and run analyzer in all namespaces.

The GetClusterResources has no timeout. In large clusters, we have seen this spend literally hours to complete. The code here is also inefficient, as its doing N queries for pods instead of one large query. Likely we will need to do this anyways with --include, but if we are doing all namespaces we should just do one query

https://github.com/istio/istio/blob/8a49d0bb3f7c3b7b0c23efbf9c8699394d005181/tools/bug-report/pkg/cluster/cluster.go#L72

**Comment by howardjohn** [comment]
This is also super wasteful because we do this then also later do `kubectl get --all-namespace pods,<a bunch of other stuff`. We don't need to fetch the same info twice

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/36255
