### ISSUE TITLE
TLS1.3 does not work with istio1.7.6

### ISSUE THREAD

**Issue by chiranjeevi-nokia** [istio/istio#36113]
### Bug Description

 Our applicaiton installed on kubernetes cluster / Openstack environment with istio 1.7.6 in two labs (sourcelab and destinationlab)

In destination lab, ingress gateway (signlling gw ) configured with TLS1.3. in sourcelab, below envoyfilter is added with destination rule. 

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
name: cnsbatest2-csd-nservice-route-destinationrule
namespace: csd
spec:
host: csd-nservice.ns1.svc.cluster.local
trafficPolicy:
loadBalancer:
simple: ROUND_ROBIN
tls:
mode: SIMPLE
connectionPool:
http:
http1MaxPendingRequests: 2500
http2MaxRequests: 2500
tcp:
maxConnections: 10
—
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
name: scp-ef
namespace: csd
spec:
configPatches:

applyTo: CLUSTER
match:
cluster:
portNumber: 8080
service: csd-nservice.ns1.svc.cluster.local
context: SIDECAR_OUTBOUND
patch:
operation: MERGE
value:
transport_socket:
typed_config:
'@type': type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
common_tls_context:
tls_params:
tls_maximum_protocol_version: TLSv1_2
tls_minimum_protocol_version: TLSv1_3
TLS handshake is not happening between labs. Ciphers used are:

 

      - TLS_AES_256_GCM_SHA384

      - TLS_CHACHA20_POLY1305_SHA256

      - TLS_AES_128_GCM_SHA256

      - TLS_AES_128_CCM_8_SHA256

      - TLS_AES_128_CCM_SHA256

### Version

```prose
istio 1.7.6
helm3
```

**Comment by howardjohn** [comment]
There have been a number of fixes in this exact area, and 1.7 is EOL for a long time. I strongly recommend upgrading. https://istio.io/latest/news/support/announcing-1.7-eol-final/
