### ISSUE TITLE
deploy istiod and istio ingress gateway on vm

### ISSUE THREAD

**Issue by rtttech** [istio/istio#36129]
Is it possible to deploy istiod and istio ingress gateway on virtual machine?

**Comment by howardjohn** [comment]
Its possible but its not an official supported/tested/documented method. https://blog.howardjohn.info/posts/local-gateway/ and https://github.com/howardjohn/local-istio-development discuss this a bit.

**Comment by rtttech** [comment]
@howardjohn Thank you very much！
