### ISSUE TITLE
Istio proxy blocks traffic for stateful application with headless service

### ISSUE THREAD

**Issue by eliavem** [istio/istio#36136]
### Bug Description

Hi, I am running two stateful applications in my cluster: zookeeper and solr. Solr service is a `headless service with a selector`. Traffic for Zookeeper works fine. However, request for solr fails with a `404` and `NR`. The request from solr is as pod.service. For testing requests, `exec into solr-0 container` then make request `http://solr-1.solr-svc:8983/<some_path>`. 

### Version

```prose
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3
```

**Comment by eliavem** [comment]
@howardjohn this is the config_dump for solr-0 [config_dump.json.zip](https://github.com/istio/istio/files/7566509/config_dump.json.zip)

**Comment by howardjohn** [comment]
That seems ... odd? There is nothing about solr-1 or zookeeper there at all. A full `istioctl bug-report` may be useful to capture more info about your config

**Comment by eliavem** [comment]
Ok this is interesting. I see a lot of Info [IST0118], could this issue be related to https://github.com/istio/istio/issues/35429?

[bug-report.zip](https://github.com/istio/istio/files/7566702/bug-report.zip)

**Comment by eliavem** [comment]
Hi @linsun, we just tested by naming it as  <protocol>[-<suffix>], and it does fix the issue. Headless services faces a similar issue as ExternalNames
