### ISSUE TITLE
Propose disable PILOT_ENABLE_SERVICEENTRY_SELECT_PODS

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#36131]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

So far have never heard users who depend on this feature. 
The motivation is: pod is the most frequently changed resource in k8s, and mostly it is also with the biggest number.  It will waste istio cpu/mem when no use.  Making it disabled by default can achieve the best.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by dddddai** [comment]
Agree, if user don't need this feature, it may unnecessarily cost significant memory cos there could be a large amount of pods

**Comment by sschepens** [comment]
We're actually using this feature, maybe it's not the correct approach but we're using it for two reasons:
- Migration of VM workloads to pods, having a service consisting of both VMs and Pods. This case is actually explicitly specified in the documentation. https://istio.io/latest/docs/reference/config/networking/service-entry/
- Services spanning multiple k8s clusters. Is there a better way of handling this case? Also Services require allocation of IP addresses which we don't much like and limits scalability.

**Comment by sschepens** [comment]
@hzxuzhonghu i'm not sure I understand, i was under the impression that k8s Services only select Pods.

case 2: what i mean is that k8s Services allocate a ClusterIP which is not really necessary in a Service Mesh and just limits scalability, we don't really need or want to allocate ClusterIPs. I don't know what's the status of Headless Services in Istio and if they're recommended or not.

**Comment by hzxuzhonghu** [comment]
Service can select both pod and workloadentry

In istio we use the clusterIP as well, just for DNS resolve. in theory the IP ranges is limited, but in reality I think it is big enough to support large scalability.

For headless service, I guess there is a gap now, headless service has  ORIGINAL_DST cluster, but the  DNS resolution can not cover workloadentry. I am not thinking about this thoroughly  though

**Comment by hzxuzhonghu** [comment]
@howardjohn

**Comment by howardjohn** [comment]
I am not sure we should do this. Just because you haven't heard of users using it doesn't mean it isn't used; we don't have any reliable mechanism to tell how often feature flags are used. In this case, since its on by default, we definitely wouldn't be able to tell. So i'd worry we are breaking compatibility because something might not be used, when we do not know. Instead it may be ideal to optimize it.

Using Service is generally better but doesn't work for all cases as SE is more flexible

**Comment by hzxuzhonghu** [comment]
ok
