### ISSUE TITLE
gRPC Proxyless Service Mesh example fails with "http filters list is empty" error

### ISSUE THREAD

**Issue by kameshraj** [istio/istio#36150]
### Bug Description

I am trying to run gRPC Proxyless Service Mesh example as described in this [blog post](https://istio.io/latest/blog/2021/proxyless-grpc/). 

The echo server starts up fine.  I am at the subsection [Test the gRPC resolver](https://istio.io/latest/blog/2021/proxyless-grpc/#test-the-grpc-resolver) and the `grpcurl` command fails with "http filters list is empty" error

```
grpcurl -plaintext -d '{"url": "xds:///echo.echo-grpc.svc.cluster.local:7070", "count": 5}' :17171 proto.EchoTestService/ForwardEcho | jq -r '.output | join("")'  | grep Hostname
Handling connection for 17171
ERROR:
  Code: Unknown
  Message: 5/5 requests had errors; first error: rpc error: code = Unavailable desc = name resolver error: http filters list is empty
```

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (4 proxies)

$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.22.3
```

### Additional Information

$ istioctl bug-report

Target cluster context: xds-test

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-11-18 16:47:47.601422981 -0800 PST

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.11.4", GitRevision:"9f6f03276054bb62a1b745630322314ef14969e8", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.11.4"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.11.4}

Fetching proxy logs for the following containers:

echo-grpc/echo-v1/echo-v1-66db8875b5-x694t/app
echo-grpc/echo-v1/echo-v1-66db8875b5-x694t/istio-proxy
echo-grpc/echo-v2/echo-v2-95df65fdf-lmkpn/app
echo-grpc/echo-v2/echo-v2-95df65fdf-lmkpn/istio-proxy
istio-system/istio-egressgateway/istio-egressgateway-756d4db566-ftsfw/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-8577c57fb6-vwph6/istio-proxy
istio-system/istiod/istiod-5847c59c69-q78g7/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /media/ssd/v-source/3p/istio/samples/grpc-echo/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by kameshraj** [comment]
bumped gRPC logging level and got below messages


2021-11-19T00:42:30.546317Z     info    Creating Server with config:
Ports:                 [0xc0005ee5a0 0xc0005ee5f0 0xc0005ee640 0xc0005ee690 0xc0005ee6e0 0xc0005ee730]
BindIPPortsMap:        map[]
BindLocalhostPortsMap: map[]
Metrics:               15014
TLSCert:               /cert.crt
TLSKey:                /cert.key
Version:               v1
UDSServer:
Cluster:
IstioVersion:

Listening HTTP/1.1 on 18080
Listening HTTP/1.1 on 3333
Listening HTTP/1.1 on 8080
2021-11-19T00:42:30.546966Z     info    endpoint        Listening GRPC (over xDS-configured mTLS) on 17070
2021-11-19T00:42:30.547006Z     info    endpoint        Using xDS for serverside gRPC on 17070
2021/11/19 00:42:30 INFO: [xds] [xds-server 0xc0000ce910] Created xds.GRPCServer
2021/11/19 00:42:30 INFO: [xds] [xds-server 0xc0000ce910] xDS credentials in use: true
2021-11-19T00:42:30.547149Z     info    endpoint        Listening GRPC on 17171
Listening TCP on 19090
2021/11/19 00:42:30 INFO: [core] Channel Created
2021/11/19 00:42:30 INFO: [xds] [xds-server 0xc0000ce910] Serve() passed a net.Listener on [::]:17070
2021/11/19 00:42:30 INFO: [xds] [xds-bootstrap] xds: using bootstrap file with name "/var/lib/istio/data/grpc-bootstrap.json"
2021/11/19 00:42:30 INFO: [core] original dial target is: "[::]:17171"
2021-11-19T00:42:30.547477Z     info    endpoint        ready for TCP endpoint [::]:19090
2021/11/19 00:42:30 INFO: [xds] [xds-bootstrap] Bootstrap content: {
  "xds_servers": [
    {
      "server_uri": "unix:///etc/istio/proxy/XDS",
      "channel_creds": [
        {
          "type": "insecure"
        }
      ],
      "server_features": [
        "xds_v3"
      ]
    }
  ],
  "node": {
    "id": "sidecar~172.17.0.7~echo-v1-66db8875b5-x694t.echo-grpc~echo-grpc.svc.cluster.local",
    "metadata": {
      "ANNOTATIONS": {
        "inject.istio.io/templates": "grpc-agent",
        "kubectl.kubernetes.io/default-container": "app",
        "kubectl.kubernetes.io/default-logs-container": "app",
        "kubernetes.io/config.seen": "2021-11-19T00:42:24.525019075Z",
        "kubernetes.io/config.source": "api",
        "prometheus.io/path": "/stats/prometheus",
        "prometheus.io/port": "15020",
        "prometheus.io/scrape": "true",
        "proxy.istio.io/config": "{\"holdApplicationUntilProxyStarts\": true}",
        "proxy.istio.io/overrides": "{\"containers\":[{\"name\":\"app\",\"image\":\"gcr.io/istio-testing/app:latest\",\"args\":[\"--metrics=15014\",\"--port\",\"18080\",\"--tcp\",\"19090\",\
"--xds-grpc-server=17070\",\"--grpc\",\"17070\",\"--grpc\",\"17171\",\"--port\",\"3333\",\"--port\",\"8080\",\"--version\",\"v1\",\"--crt=/cert.crt\",\"--key=/cert.key\"],\"ports\":[{\"conta
inerPort\":17070,\"protocol\":\"TCP\"},{\"containerPort\":17171,\"protocol\":\"TCP\"},{\"containerPort\":8080,\"protocol\":\"TCP\"},{\"name\":\"tcp-health-port\",\"containerPort\":3333,\"pro
tocol\":\"TCP\"}],\"env\":[{\"name\":\"INSTANCE_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.podIP\"}}},{\"name\":\"GRPC_GO_LOG_SEVERITY_LEVEL\",\"value\":\
"info\"},{\"name\":\"GRPC_GO_LOG_VERBOSITY_LEVEL\",\"value\":\"99\"},{\"name\":\"GRPC_TRACE\",\"value\":\"all\"}],\"resources\":{},\"volumeMounts\":[{\"name\":\"kube-api-access-wgg66\",\"rea
dOnly\":true,\"mountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\"}],\"startupProbe\":{\"tcpSocket\":{\"port\":\"tcp-health-port\"},\"timeoutSeconds\":1,\"periodSeconds\":10,\"succ
essThreshold\":1,\"failureThreshold\":10},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\",\"securityContext\":{\"runA
sUser\":1338,\"runAsGroup\":1338}}]}",
        "sidecar.istio.io/status": "{\"initContainers\":null,\"containers\":[\"app\",\"istio-proxy\"],\"volumes\":[\"istio-xds\",\"istio-data\",\"istio-podinfo\",\"istio-token\",\"istiod-ca-
cert\"],\"imagePullSecrets\":null,\"revision\":\"default\"}"
      },
      "APP_CONTAINERS": "app",
      "CLUSTER_ID": "Kubernetes",
      "ENVOY_PROMETHEUS_PORT": 15090,
      "ENVOY_STATUS_PORT": 15021,
      "GENERATOR": "grpc",
      "INSTANCE_IPS": "172.17.0.7",
      "INTERCEPTION_MODE": "REDIRECT",
      "ISTIO_PROXY_SHA": "istio-proxy:ed148b62dfb0dc79adc8c8573ced4806883389c0",
      "ISTIO_VERSION": "1.11.4",
      "LABELS": {
        "app": "echo",
        "pod-template-hash": "66db8875b5",
        "version": "v1"
      },
      "MESH_ID": "cluster.local",
      "NAME": "echo-v1-66db8875b5-x694t",
      "NAMESPACE": "echo-grpc",
      "OWNER": "kubernetes://apis/apps/v1/namespaces/echo-grpc/deployments/echo-v1",
      "PILOT_SAN": [
        "istiod.istio-system.svc"
      ],
      "POD_PORTS": "[{\"containerPort\":17070,\"protocol\":\"TCP\"},{\"containerPort\":17171,\"protocol\":\"TCP\"},{\"containerPort\":8080,\"protocol\":\"TCP\"},{\"name\":\"tcp-health-port\"
,\"containerPort\":3333,\"protocol\":\"TCP\"}]",
      "PROV_CERT": "var/run/secrets/istio/root-cert.pem",
      "PROXY_CONFIG": {
        "binaryPath": "/usr/local/bin/envoy",
        "concurrency": 2,
        "configPath": "./etc/istio/proxy",
        "controlPlaneAuthPolicy": "MUTUAL_TLS",
        "discoveryAddress": "istiod.istio-system.svc:15012",
        "drainDuration": "45s",
        "holdApplicationUntilProxyStarts": true,
        "parentShutdownDuration": "60s",
        "proxyAdminPort": 15000,
        "serviceCluster": "istio-proxy",
        "statNameLength": 189,
        "statusPort": 15020,
        "terminationDrainDuration": "5s",
        "tracing": {
          "zipkin": {
            "address": "zipkin.istio-system:9411"
          }
        }
      },
      "PROXY_VIA_AGENT": true,
      "SERVICE_ACCOUNT": "default",
      "WORKLOAD_NAME": "echo-v1"
    },
    "locality": {},
    "UserAgentVersionType": null
  },
  "certificate_providers": {
    "default": {
      "plugin_name": "file_watcher",
      "config": {
        "certificate_file": "/var/lib/istio/data/cert-chain.pem",
        "private_key_file": "/var/lib/istio/data/key.pem",
        "ca_certificate_file": "/var/lib/istio/data/root-cert.pem",
        "refresh_interval": "900s"
      }
    }
  },
  "server_listener_resource_name_template": "xds.istio.io/grpc/lds/inbound/%s"
}

ADS
***
2021/11/19 00:42:30 INFO: [xds] [xds-client 0xc000a96200] ADS request sent: {                                                                                                     [1270/18918]
  "node": {
    "id": "sidecar~172.17.0.7~echo-v1-66db8875b5-x694t.echo-grpc~echo-grpc.svc.cluster.local",
    "metadata": {
        "ANNOTATIONS": {
              "inject.istio.io/templates": "grpc-agent",
              "kubectl.kubernetes.io/default-container": "app",
              "kubectl.kubernetes.io/default-logs-container": "app",
              "kubernetes.io/config.seen": "2021-11-19T00:42:24.525019075Z",
              "kubernetes.io/config.source": "api",
              "prometheus.io/path": "/stats/prometheus",
              "prometheus.io/port": "15020",
              "prometheus.io/scrape": "true",
              "proxy.istio.io/config": "{\"holdApplicationUntilProxyStarts\": true}",
              "proxy.istio.io/overrides": "{\"containers\":[{\"name\":\"app\",\"image\":\"gcr.io/istio-testing/app:latest\",\"args\":[\"--metrics=15014\",\"--port\",\"18080\",\"--tcp\",\"190
90\",\"--xds-grpc-server=17070\",\"--grpc\",\"17070\",\"--grpc\",\"17171\",\"--port\",\"3333\",\"--port\",\"8080\",\"--version\",\"v1\",\"--crt=/cert.crt\",\"--key=/cert.key\"],\"ports\":[{\
"containerPort\":17070,\"protocol\":\"TCP\"},{\"containerPort\":17171,\"protocol\":\"TCP\"},{\"containerPort\":8080,\"protocol\":\"TCP\"},{\"name\":\"tcp-health-port\",\"containerPort\":3333
,\"protocol\":\"TCP\"}],\"env\":[{\"name\":\"INSTANCE_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.podIP\"}}},{\"name\":\"GRPC_GO_LOG_SEVERITY_LEVEL\",\"val
ue\":\"info\"},{\"name\":\"GRPC_GO_LOG_VERBOSITY_LEVEL\",\"value\":\"99\"},{\"name\":\"GRPC_TRACE\",\"value\":\"all\"}],\"resources\":{},\"volumeMounts\":[{\"name\":\"kube-api-access-wgg66\"
,\"readOnly\":true,\"mountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\"}],\"startupProbe\":{\"tcpSocket\":{\"port\":\"tcp-health-port\"},\"timeoutSeconds\":1,\"periodSeconds\":10,
\"successThreshold\":1,\"failureThreshold\":10},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\",\"securityContext\":{
\"runAsUser\":1338,\"runAsGroup\":1338}}]}",
              "sidecar.istio.io/status": "{\"initContainers\":null,\"containers\":[\"app\",\"istio-proxy\"],\"volumes\":[\"istio-xds\",\"istio-data\",\"istio-podinfo\",\"istio-token\",\"isti
od-ca-cert\"],\"imagePullSecrets\":null,\"revision\":\"default\"}"
            },
        "APP_CONTAINERS": "app",
        "CLUSTER_ID": "Kubernetes",
        "ENVOY_PROMETHEUS_PORT": 15090,
        "ENVOY_STATUS_PORT": 15021,
        "GENERATOR": "grpc",
        "INSTANCE_IPS": "172.17.0.7",
        "INTERCEPTION_MODE": "REDIRECT",
        "ISTIO_PROXY_SHA": "istio-proxy:ed148b62dfb0dc79adc8c8573ced4806883389c0",
        "ISTIO_VERSION": "1.11.4",
        "LABELS": {
              "app": "echo",
              "pod-template-hash": "66db8875b5",
              "version": "v1"
            },
        "MESH_ID": "cluster.local",
        "NAME": "echo-v1-66db8875b5-x694t",
        "NAMESPACE": "echo-grpc",
        "OWNER": "kubernetes://apis/apps/v1/namespaces/echo-grpc/deployments/echo-v1",
        "PILOT_SAN": [
              "istiod.istio-system.svc"
            ],
        "POD_PORTS": "[{\"containerPort\":17070,\"protocol\":\"TCP\"},{\"containerPort\":17171,\"protocol\":\"TCP\"},{\"containerPort\":8080,\"protocol\":\"TCP\"},{\"name\":\"tcp-health-port
\",\"containerPort\":3333,\"protocol\":\"TCP\"}]",
        "PROV_CERT": "var/run/secrets/istio/root-cert.pem",
        "PROXY_CONFIG": {
              "binaryPath": "/usr/local/bin/envoy",
              "concurrency": 2,
              "configPath": "./etc/istio/proxy",
              "controlPlaneAuthPolicy": "MUTUAL_TLS",
              "discoveryAddress": "istiod.istio-system.svc:15012",
              "drainDuration": "45s",
              "holdApplicationUntilProxyStarts": true,
              "parentShutdownDuration": "60s",
              "proxyAdminPort": 15000,
              "serviceCluster": "istio-proxy",
              "statNameLength": 189,
              "statusPort": 15020,
              "terminationDrainDuration": "5s",
              "tracing": {
                    "zipkin": {
                          "address": "zipkin.istio-system:9411"
                        }
                  }
            },
        "PROXY_VIA_AGENT": true,
        "SERVICE_ACCOUNT": "default",
        "WORKLOAD_NAME": "echo-v1"
      },
    "locality": {

    },
    "userAgentName": "gRPC Go",
    "userAgentVersion": "1.42.0",
    "clientFeatures": [
      "envoy.lb.does_not_support_overprovisioning"
    ]
  },
  "resourceNames": [
    "xds.istio.io/grpc/lds/inbound/[::]:17070"
  ],
  "typeUrl": "type.googleapis.com/envoy.config.listener.v3.Listener"
}
2021/11/19 00:42:30 INFO: [xds] [xds-client 0xc000a96200] ADS response received, type: type.googleapis.com/envoy.config.listener.v3.Listener
2021/11/19 00:42:30 INFO: [xds] [xds-client 0xc000a96200] ADS response received: {
  "versionInfo": "2021-11-19T00:42:24Z/5",
  "resources": [
    {
      "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
      "name": "xds.istio.io/grpc/lds/inbound/[::]:17070",
      "address": {
        "socketAddress": {
          "address": "::",
          "portValue": 17070
        }
      },
      "filterChains": [
        {
          "filters": [
            {
              "name": "inbound-hcmplaintext",
              "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              }
            }
          ],
          "name": "inbound-plaintext"
        }
      ]
    }
  ],
  "typeUrl": "type.googleapis.com/envoy.config.listener.v3.Listener",
  "nonce": "0h0cHPkixhg=62421f69-b670-4c79-aa83-305833068b07",
  "controlPlane": {
    "identifier": "{\"Component\":\"istiod\",\"ID\":\"istiod-5847c59c69-q78g7\",\"Info\":{\"version\":\"1.11.4\",\"revision\":\"9f6f03276054bb62a1b745630322314ef14969e8\",\"golang_version\":
\"go1.16.9\",\"status\":\"Clean\",\"tag\":\"1.11.4\"}}"
  }
}

error
***
2021/11/19 00:42:30 INFO: [xds] [xds-client 0xc000a96200] Resource with name: xds.istio.io/grpc/lds/inbound/[::]:17070, type: *envoy_config_listener_v3.Listener, contains: {
  "name": "xds.istio.io/grpc/lds/inbound/[::]:17070",
  "address": {
    "socketAddress": {
      "address": "::",
      "portValue": 17070
    }
  },
  "filterChains": [
    {
      "filters": [
        {
          "name": "inbound-hcmplaintext",
          "typedConfig": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          }
        }
      ],
      "name": "inbound-plaintext"
    }
  ]
}
2021/11/19 00:42:30 WARNING: [xds] [xds-client 0xc000a96200] Sending NACK for response type: ListenerResource, version: 2021-11-19T00:42:24Z/5, nonce: 0h0cHPkixhg=62421f69-b670-4c79-aa83-305
833068b07, reason: error parsing "" response: resource "xds.istio.io/grpc/lds/inbound/[::]:17070": network filters {[]} had invalid server side HTTP Filters {[]}: http filters list is empty
2021/11/19 00:42:30 WARNING: [xds] [xds-server-listener 0xc0008e8380] Received error for resource "xds.istio.io/grpc/lds/inbound/[::]:17070": network filters {[]} had invalid server side HTT
P Filters {[]}: http filters list is empty

**Comment by stevenctl** [comment]
This was fixed in https://github.com/istio/istio/pull/35844. Can you try upgrading to Istio 1.12? I'll try to get the control plane fix backported to 1.11

**Comment by kameshraj** [comment]
Tested this with Istio 1.12 and I don't see the error and it working now.

Although I noticed the requests are not distributed to server and the response is coming back from just 1 server.

The original issue reported is fixed, I will close it

**Comment by m9rco** [comment]
Is there a demo I can try to run ? @kameshraj
