### ISSUE TITLE
PILOT_ENABLE_ISTIO_TAGS doesn't seem to work

### ISSUE THREAD

**Issue by Stono** [istio/istio#36152]
### Bug Description

We se `PILOT_ENABLE_ISTIO_TAGS=false` on `istiod`, but I still see istio related tags in spans, for example:

<img width="621" alt="Screenshot 2021-11-19 at 08 16 59" src="https://user-images.githubusercontent.com/1486729/142588943-3a3c02b9-0f7c-410d-8c97-7599362a0cb2.png">

So I don't believe this is working as expected?

### Version

```prose
1.11 + 1.12
```

**Comment by Stono** [comment]
Ahh this looks to just be for `istio.` tags https://github.com/istio/istio/pull/28801 

Is there any way to remove the envoy ones?

**Comment by douglas-reid** [comment]
@Stono we don't have a way to strip the envoy tags at the moment. as i understand it, we'd need to add that functionality into envoy itself: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#what-data-each-trace-contains.
