### ISSUE TITLE
Security: External Authorization (Stable Release ETA)

### ISSUE THREAD

**Issue by JJRdec** [istio/istio#36158]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Not so much a feature request - more a clarification .

I'm wondering is there any indication on when External Authorization (used with AuthorizationPolicy) feature will be stable. 
https://istio.io/latest/docs/releases/feature-stages/#security-and-policy-enforcement

Find the specific features I'm interested in used [here.](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Thank you in advance 👍

**Comment by yangminzhu** [comment]
The external authz feature has been graduated to alpha in 1.12, I will update the documentation as well.

We are working to graduate the feature to more stable stage later but currently I do no have a concrete timeline for stable graduation but I think it should happen in 2022.

**Comment by ericvn** [comment]
Just reiterating, but https://github.com/istio/enhancements/blob/master/features.yaml#L251-L252 shows Alpha status and no known date yet for promotion to Beta.

**Comment by JJRdec** [comment]
@yangminzhu Any update on a timeline for this?

**Comment by westwind-sc** [comment]
@ericvn and @yangminzhu, https://github.com/istio/enhancements/blob/master/features.yaml#L251-L252 said next `nextExpectedPromotion: "1.14"`, as 1.15 already released, and 1.16 is coming soon.
Could you help to take a look and check whether ok to promote it in 1.16?

Note: I try reopen this issue, but it seems we do not have permission to reopen it. Sorry for comments on closed PR.
