### ISSUE TITLE
Add Istio-Operator to the new Helm chart repository

### ISSUE THREAD

**Issue by tafkam** [istio/istio#36157]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Add the istio-operator Helm charts to the new chart repository announced in 1.12

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shivanshu1333** [comment]
Can I pick this up?
It looks like a good first issue to me.
If yes, istio members kindly assign this to me :)

**Comment by howardjohn** [comment]
This was intentionally left out, as we are promoting a limited set of helm charts that we can commit to stable support as a project. The operator falls outside of that scope for helm, and is generally discouraged.

Above is the consensus from the Environments working group. My own opinion is that it does not make sense to have a helm chart to install 1 Deployment (istio-operator) that then turns around and (using Helm!) installs 1 more Deployment (istiod). All the effort spent in step (1) could have just as easily installed Istiod directly and skipped a ton of complexity. Operators made sense when istio had 12 Deployments, and when they are adding value on top (prometheus operator); neither of these are true for Istio today.

**Comment by tafkam** [comment]
This reads like the Istio Operator is deprecating out at some time in the far future. I was under the impression Istio Operator is internally using istioctl with the IstioOperator API manifest to install Istio components. Using gitops workflows with the Istio Operator had the charm to use the first class IstioOperator API without any manual istioctl steps. I'm not sure how moving from first-class API to juggling three different Helm charts for CRDs, Istiod and several gateways will improve on the experience.

**Comment by howardjohn** [comment]
We do not intend to remove it as we don't want to introduce churn for users. However, we don't believe it is the best way to deploy Istio today.

https://www.solo.io/blog/configuration-as-data-gitops-and-controllers-its-not-simple-for-multi-cluster/ is a great discussion about GitOps + operator.

Gateways are moving to a new model as part of the new gateway-api.org https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment. That leaves only Istiod

**Comment by tafkam** [comment]
I agree there are many intricacies using gitops together with operators. But beside the technical details there are also some organizational and environmental factors to consider.
Having k8s gateways on the horizon is a nice outlook, but still unclear (at least for me) how this will unfold.

I guess I will have to reevaluate the method of installing Istio. Moving away from the IstioOperator API gives me a bad tummy feeling though. Have you considered supporting helm charts installing IstioOperator manifests with istioctl in a helm hook job (this would mitigate the risk of permanently running a high privileged operator)? 
Maybe another way out of that dilemma is using multiple istioctl binary versions as custom tooling with custom config management plugins in ArgoCD.

Closing this issue though, since this is not gonna be resolved. Thanks for your effort @howardjohn!

**Comment by howardjohn** [comment]
If you like to use the IstioOperator then by all means keep using it. We
are explicitly not intending to remove it/make it harder to use. We just
are not prioritizing efforts to improve its usage much and do not want to
accidentally push users towards it when it otherwise doesn't make sense.
