### ISSUE TITLE
serviceCluster behaviour change in 1.12

### ISSUE THREAD

**Issue by Stono** [istio/istio#36162]
### Bug Description

Historically the `serviceCluster` on istio-proxy correlated to the span name (see https://github.com/istio/istio/issues/12644#issuecomment-973867802)

However since upgrading to 1.12, this no longer seems to be the case:

<img width="209" alt="142591824-a445a7cb-cc49-40f4-9071-7426e7486d40" src="https://user-images.githubusercontent.com/1486729/142664917-231a6fc2-4498-42a1-b07f-abb283cc1fde.png">

<img width="413" alt="142591849-53ed12cd-7f92-46e7-9317-03b1d742a9d8" src="https://user-images.githubusercontent.com/1486729/142664925-b48cb1b7-736c-491b-b5c3-22073cc2269b.png">

So this feels like a regression.

@howardjohn pointed towards https://github.com/istio/istio/pull/35625 as a potential cause?

### Version

```prose
1.12
```

**Comment by douglas-reid** [comment]
@kyessenov thoughts here?  it looks you moved control over configurability in https://github.com/istio/istio/pull/32407.

**Comment by Stono** [comment]
Ah so serviceCluster is no longer used?  How would I go about controlling the service name in spans now then?

**Comment by douglas-reid** [comment]
@howardjohn @Stono wdyt about supporting something like this (as a workaround for setting proxyconfig annotations on each pod, etc.): https://github.com/istio/istio/compare/master...douglas-reid:experiment-service-cluster?expand=1 ?

**Comment by kyessenov** [comment]
We're trying to remove customization via templates (envoy and pod templates) and use actual API for such customizations. Doesn't ProxyConfig.serviceCluster work for you? That field is still honored I think. It can be injected as an annotation and probably migrate to a separate API later.

**Comment by Stono** [comment]
@kyessenov I get that - but it certainly feels like this has been removed and an alternative isn't really there (or it isn't clear to me what to do).  

We could go and add that annotation to all of our workloads I suppose, but we're talking 500+ of them, previously this was nicely handled by the injector and dynamically (in our case) set to the app label by doing (`--serviceCluster {{ index .ObjectMeta.Labels `app` }}"`).

@douglas-reid not sure what your PR shows, I don't know golang really and don't have context of the code base :)

**Comment by kyessenov** [comment]
The default service tag is `app.namespace`. Is the namespace creating the problem for you? Could you use custom tags on tracing spans to set the service name? Service cluster is really an Envoy implementation details that does not fit well with istio.

**Comment by Stono** [comment]
hey @kyessenov - so I totally agree, we've bound to serviceCluster which is an implementation detail in order to set the span name - see https://github.com/istio/istio/issues/12644.  Yes, we don't want namespace, at AT we have a single service per namespace so we just end up with all spans being `app.app` effectively, which is just noisy:

![Screenshot 2021-11-22 at 07 40 11](https://user-images.githubusercontent.com/1486729/142821915-69abddb0-c62a-4316-ab73-666eaecd4b3b.png)

I will have a play with a custom tag but it isn't clear to me what the name of the tag needs to be to override the service name?

**Comment by Stono** [comment]
So I'm struggling to get this to work, i'm doing the following:
```
      tracing:
        custom_tags:
          service:
            environment:
              name: ISTIO_META_WORKLOAD_NAME
```

But it has no effect (i've restarted the workloads).

I found this issue: https://github.com/jaegertracing/jaeger/issues/936, which seems to imply that setting the `service` will have no effect on `process.serviceName`

**Comment by Stono** [comment]
I attempted to override the serviceName:

```
      tracing:
        custom_tags:
          process.serviceName:
            environment:
              name: ISTIO_META_WORKLOAD_NAME
```

But that just gives me a tag:

![Screenshot 2021-11-22 at 08 19 36](https://user-images.githubusercontent.com/1486729/142826798-77870570-884f-4866-aed0-ce62d2256ff4.png)

So yeah I am pretty stuck.

**Comment by douglas-reid** [comment]
> @douglas-reid not sure what your PR shows, I don't know golang really and don't have context of the code base :)

@Stono, I was playing around with setting a global serviceCluster field with a go-template string. so, install with `{{ .Labels.app }}` similar to your suggestion above.

**Comment by Hronom** [comment]
And what we should do to change `service.name`?

**Comment by Hronom** [comment]
Seems like this is the answer https://discuss.istio.io/t/change-tracing-service-name/10255/2
Inspired by this guide https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/

**Comment by Hronom** [comment]
In version `1.19.4` this is what works for me https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-TracingServiceName
