### ISSUE TITLE
External tracing.zipkin.address results in requests with host=zipkin

### ISSUE THREAD

**Issue by jwineinger** [istio/istio#36166]
### Bug Description

We've been migrating from a cluster.local zipkin collector to one behind an ELB so that in a multi-cluster scenario, our traces are unified. However, when we made that change, we found that we got no traces from istio into it. After some debugging, we found the ELB logs that the host of the request is being set to just "zipkin" instead of the FQDN of the address we configured, and so the request was being rejected. ELB log exerpt:
```
"POST https://zipkin:443/api/v2/spans HTTP/1.1"
```

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/zipkin.proto#config-trace-v3-zipkinconfig
shows a `collector_hostname` field with the following description:
> (string) Optional hostname to use when sending spans to the collector_cluster. Useful for collectors that require a specific hostname. Defaults to collector_cluster above.

Here is the tracing config from one of our proxies:
```json
"tracing": { 
  "http": { 
    "name": "envoy.tracers.zipkin",
    "typed_config": { 
      "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
      "collector_cluster": "zipkin",
      "collector_endpoint": "/api/v2/spans",
      "trace_id_128bit": true,
      "shared_span_context": false,
      "collector_endpoint_version": "HTTP_JSON"
    } 
  } 
}
```

As you can see, collector_hostname is not set, so I assume that from the description in the envoy docs that it will just use the collector_cluster as the hostname, which is "zipkin".

I would expect that the tracer.zipkin.address would be the hostname, or that there is a configuration option that I can use to force it to be so. 

To temporarily workaround this issue, we had to configure the system ingress behind the ELB to accept a "zipkin" hostname, which feels quite odd. 

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.3
data plane version: 1.11.3 (132 proxies)

$ kubectl version --short
Client Version: v1.20.4-dirty
Server Version: v1.20.7-eks-d88609
```

**Comment by zirain** [comment]
@jwineinger did you change the tracing address in MeshConfig

**Comment by zirain** [comment]
Refer to  [envoy_bootstrap.json](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap.json), maybe we need a PR to fix this.

you can try something as following:
- use a custom bootstrap to override, see more detail [here](https://github.com/istio/istio/blob/55d72c192c62ed3c9b2537168d13dd004e5e2bfd/manifests/charts/istiod-remote/files/injection-template.yaml#L280)
- use [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo) to applies the patch to bootstrap configuration.
- use [otel-collector](https://github.com/open-telemetry/opentelemetry-collector)  as a transit

**Comment by zirain** [comment]
@jwineinger seems this was fixed in https://github.com/istio/istio/pull/36277

**Comment by jwineinger** [comment]
Excellent. I see a PR to cherry pick it into a 1.11 release as well.  I do think we may try otel-collector anyway, because we're evaluating different trace backends and that seems to be a easy way to switch between them.

**Comment by zirain** [comment]
> Excellent. I see a PR to cherry pick it into a 1.11 release as well. I do think we may try otel-collector anyway, because we're evaluating different trace backends and that seems to be a easy way to switch between them.

agree!

BTW, can we close the issue?
