### ISSUE TITLE
investigate/follow vgo vs dep

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3619]
look into

https://sdboyer.io/blog/vgo-and-dep/
https://research.swtch.com/vgo-intro

thanks @jwendell for the find

**Comment by jmuk** [comment]
I spent a few hours for this today, I see lots of troubles actually, like:
- vgo makes lots of github API requests, which quickly exceeds the free quota for the scale of istio repository. For now, it needs to add an auth info to work with github API with larger quota.
- vgo works incorrectly on some dependencies which stopped working. This could be bypassed by adding `replace` rules, but it's a bit annoying.
- still failed to build pilot-discovery here, and the error message is still puzzling to me

These are just my notes. I believe they will be resolved very soon, but I guess such note would be still helpful for someone who wants to try it out.

**Comment by jmuk** [comment]
additional note:
- finally found that the error happens on analyzing `bitbucket.org/ww/goautoneg`, it seems `vgo` does not deal with bitbucket repos correctly
- this happens automatically since `vgo` analyzes gopkg.lock files, and this dependency appears in `k8s.io/cluster-registry`

**Comment by ldemailly** [comment]
vgo in theory is the future so we should keep this open
