### ISSUE TITLE
0.2 Config related work/changes (istioctl, api, validation,...)

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#362]
This is the high level epic for the work we need to do to implement Galley (the config API).
It will spread multiple repos. 
Add existing issues to this epic to help with tracking.

**Comment by ldemailly** [comment]
> geeknoid removed this from the Istio 0.2 milestone

@geeknoid ?

**Comment by kyessenov** [comment]
We're sort of blocked across the block on galley (alpha) for 0.2, aren't we?

**Comment by geeknoid** [comment]
An epic is not tied to a date. It's a feature area.

Individual issues within an epic can be tied to dates and milestones.

**Comment by ldemailly** [comment]
The galley repo is the feature, we decided to use epic to track the 0.2 P0s

**Comment by geeknoid** [comment]
Labels are what we're using to track priorities.

**Comment by Disturbing** [comment]
Are there any tasks on this one? Guessing in other repros?  I'd like to "follow" and see if it's going to make the 0.2 release.

**Comment by ldemailly** [comment]
@Disturbing if you install zenhub you will see all the issues/tasks attached to this epic
Also there is a repo for galley https://github.com/istio/galley
Lastly a document was reviewed today : https://groups.google.com/forum/#!topic/istio-dev/Mz2GFFKPKjk

**Comment by sakshigoel12** [comment]
This is mainly for Galley. Not applicable anymore
