### ISSUE TITLE
Apply error

### ISSUE THREAD

**Issue by SchramMichiel** [istio/istio#36206]
### Bug Description
(mk alias for micro8ks.kubectl)
mk apply -f https://github.com/istio/istio/blob/release-1.12/samples/addons/prometheus.yaml will generate the error :
error parsing https://github.com/istio/istio/blob/release-1.12/samples/addons/prometheus.yaml: error converting YAML to JSON: yaml: line 141: mapping values are not allowed in this context

### Version

```prose
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (8 proxies)

(using microk8s)
Client Version: v1.22.3-3+9ec7c40ec93c73
Server Version: v1.22.3-3+9ec7c40ec93c73
```

**Comment by bianpengyuan** [comment]
Should apply the raw content link https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/prometheus.yaml. Closing since this is an user error. Thanks!
