### ISSUE TITLE
MTLS encryption is not working with default configuration

### ISSUE THREAD

**Issue by RM250702** [istio/istio#36219]
### Bug Description

installed with helm charts
Istio version 1.11.3
side car injection enabled namespace wide for all the pods
Peer authentication is enabled as STRICT.
Rabbitmq cluster is also installed in the same namespace and has side car injected
FLOW SCENARIO.
Simulator (creates fake transactions that will be sent to the pod in the istio enabled cluster and this pod will forwards the traffic to rabbitmq pods).
CURRENT RESULTS.
using ksniff and wireshark to sniff the tcpdump.
also, the same plain text is seen when i ran sudo tcpdump command in istio-proxy sidecar.
![github_issue](https://user-images.githubusercontent.com/76467939/142996053-14d58c67-b6e5-4b75-8f34-694c6ec12199.PNG)

### Version

```prose
istioctl version
client version: 1.12.0
control plane version: 1.11.3
data plane version: 1.11.3 (12 proxies)
kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-
```

**Comment by incfly** [comment]
Might be due to some config causing traffic sent via passthrough cluster? Check access log on both sides?

**Comment by zirain** [comment]
can your share the accesslog?
