### ISSUE TITLE
invalid bearer token, token audiences ["kubernetes.svc.default"] is invalid for the target audiences ["istio-ca"]

### ISSUE THREAD

**Issue by dishant-jeeves** [istio/istio#36221]
### Bug Description

Isito Proxy not Starting up and Istiod is thowring following errors
```
2021-11-23T11:27:19.413494Z	error	ads	Failed to authenticate client from 100.111.217.36:56330: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "Kubernetes": the service account authentication returns an error: [invalid bearer token, token audiences ["kubernetes.svc.default"] is invalid for the target audiences ["istio-ca"]]
2021-11-23T11:27:19.602164Z	warn	serverca	Authentication failed for 100.125.178.36:39742: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT from cluster "Kubernetes": the service account authentication returns an error: [invalid bearer token, token audiences ["kubernetes.svc.default"] is invalid for the target audiences ["istio-ca"]].
```
[istiod-6f8886544d-2lr2w.log](https://github.com/istio/istio/files/7587594/istiod-6f8886544d-2lr2w.log)

### Version

```prose
kubectl version: 

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
```

istio version: 1.10.5
```


### Additional Information

_No response_

**Comment by emmanuelstroem** [comment]
We're experiencing the same on GKE with this:
```
invalid bearer token, token audiences ["https://container.googleapis.com/v1/projects/{{PROJECT}}/locations/{{REGION}}/clusters/{{GKE-CLUSTER}}"] is invalid for the target audiences ["istio-ca"]
```

**Comment by howardjohn** [comment]
> We're experiencing the same on GKE with this:

I think this is entirely different and your installation is setup to use Mesh CA but is somehow using Citadel

For the original issue: what is `kubernetes.svc.default`? That doesn't make much sense - it should be `kubernetes.default.svc`. I strongly suspect that your kubernetes cluster is misconfigured. Likely `--service-account-issuer=kubernetes.svc.default`. I suspect that in addition you are not using third party jwt tokens (https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens); using that would also likely fix this.

**Comment by Birdrock** [comment]
@howardjohn Thanks for that tip. I believe it is the case that it is configured for first party jwt tokens. I'm familiar with the product @dishant-jeeves is using and have provided instructions on Slack to update the configuration. Hopefully we'll have a good result! Cheers.

**Comment by drpdishant** [comment]
@howardjohn  I confirm it has been resolved on my end Thanks @Birdrock for help, we can close this.

**Comment by howardjohn** [comment]
Thanks everyone

**Comment by longpi1** [comment]
> @howardjohn Thanks for that tip. I believe it is the case that it is configured for first party jwt tokens. I'm familiar with the product @dishant-jeeves is using and have provided instructions on Slack to update the configuration. Hopefully we'll have a good result! Cheers.

I also encountered this problem. Do you have a link for the latest configuration on Slack?

**Comment by SpectralHiss** [comment]
I seem to be mysteriously hitting this issue on an Openshift dedicated cluster deployed on GCP, is the istio-ca claim done automatically for all GCP workloads through metadata server somehow? @howardjohn
