### ISSUE TITLE
x-b3 headers not appearing in the response

### ISSUE THREAD

**Issue by mvkrishna86** [istio/istio#36224]
### Bug Description

When I enabled tracing in istio, its adding x-b3-traceid, x-b3-spanid and other headers to the incoming request. And as the request is coming through AWS ALB, it is also adding X-Amzn-Trace-Id. I could see all these headers, in in the application, istio proxy container and able to print in the access log.
But these are not returned to the user, I didnt apply any envoy filters and not removed any headers in the virtual service also.
Can someone help me to find out where the headers could be removed?

### Version

```prose
Using istio image 1.11.0 image in k8s.

vamsikrishnam@NHHYDL-00217:~$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.2-eks-0389ca3
```

**Comment by bianpengyuan** [comment]
Does your application populate tracing context: https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation

**Comment by mvkrishna86** [comment]
Yes @bianpengyuan, I am able to see the headers in accesslogs and the same is seen in Tempo/Grafana also.

**Comment by bianpengyuan** [comment]
So your app is copying headers, and in access log, you are able to see x-b3 in response header (`%RESP(X-B3-TRACEID)%` etc)?

**Comment by mvkrishna86** [comment]
With below EnvoyFilter, I dont see any headers related to x-b3-*.
But with `context: SIDECAR_INBOUND`, I could see all the headers. Does it mean that the headers are not being sent by application itself?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cdm-outbound-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: qa3-nsl-cdm
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |-
              function envoy_on_request(request_handle)
                  local amazonTraceId = request_handle:headers():get("x-amzn-trace-id")
                  local xb3traceid = request_handle:headers():get("x-b3-traceid")
                  local path = request_handle:headers():get(":path")
                  local headers = request_handle:headers()
                  for key, value in pairs(headers) do
                    request_handle:logWarn(key);
                    request_handle:logWarn(value);
                  end
              end
              function envoy_on_response(response_handle)
                  local amazonTraceId = response_handle:headers():get("x-amzn-trace-id")
                  local xb3traceid = response_handle:headers():get("x-b3-traceid")
                  local path = response_handle:headers():get(":path")
                  local headers = response_handle:headers()
                  for key, value in pairs(headers) do
                    response_handle:logWarn(key);
                    response_handle:logWarn(value);
                  end
              end
```

**Comment by mvkrishna86** [comment]
I tried printing %RESP(X-B3-TRACEID)% in logs. Thats getting printed as null.
Can you suggest how to propagate it in response headers.

**Comment by bianpengyuan** [comment]
I think It is behavior of your own app. Your app needs to copy over trace context headers from request header to the response header if you want those headers to appear in response.
