### ISSUE TITLE
istio/pilot

### ISSUE THREAD

**Issue by drgray20** [istio/istio#36229]
Hi please Help.
I'm trying to find the istio github repo for istio/pilot
The only one is see is the archived repo

**Comment by howardjohn** [comment]
This is the repo.

**Comment by drgray20** [comment]
oh thank you we'll have to point out update bot to this repo then.
Also could you help me find pkg versions? i'm trying to locate the version of jwt-go used.

**Comment by howardjohn** [comment]
It's in the go.mod

**Comment by drgray20** [comment]
Thank you again.
