### ISSUE TITLE
'Chiron' MeshConfig.Certificates broken on 1.22+

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36231]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate

This is always using signerName="" which fails on K8s 1.22+.

IMO this API should be deprecated but open to suggestions here.

cc @shankgan @lei-tang @jacob-delgado

**Comment by zirain** [comment]
Not stale

**Comment by lei-tang** [comment]
MeshConfig.Certificates is used to configure the provisioning of DNS certificates (details in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate). DNS certificates are used in scenarios such as a webhook server.

**Comment by shankgan** [comment]
Not sure if we should re-open this. Should we use this issue to track deprecation of the API @lei-tang

**Comment by lei-tang** [comment]
It sounds good to me to use either this issue or an issue on https://github.com/istio/api/issues to discuss the deprecation of the API.

**Comment by hzxuzhonghu** [comment]
Opened a pr https://github.com/istio/api/pull/2392 to do this
