### ISSUE TITLE
Can virtual-service and destination-rule support `workloadSelector` field?

### ISSUE THREAD

**Issue by machine3** [istio/istio#36240]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
Could you provide more details about your use case?

**Comment by zirain** [comment]
@machine3 do you mean [WorkloadSelector ](https://github.com/istio/api/blob/67f86871f2a5cf898efdcd0802322fb31235e9b7/networking/v1alpha3/envoy_filter.proto#L849) on   virtualservice?

**Comment by machine3** [comment]
@zirain yes

**Comment by machine3** [comment]
@bianpengyuan 
1. The configured grayscale is issued, and it will take effect in some data plane instances first, and the full amount will be issued after the verification is passed.
2. Different clients need different vs configuration, and if you use one copy, it will be redundant.

**Comment by bianpengyuan** [comment]
This was discussed before at https://github.com/istio/istio/issues/7794 and https://github.com/istio/istio/issues/29434

**Comment by MengJiapeng** [comment]
以下为自动回复    您好，您的邮件我已收到，我会尽快给您回复！
