### ISSUE TITLE
Adding request_operation as the default tag for envoy telemetry.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [istio/istio#36248]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The Envoy sidecar Prometheus endpoint does not use request_operation (ie endpoint url?) as the dimension for the request metrics. I believe it's way more useful that the current dimension of the http_protocol which is added by default.

**Describe alternatives you've considered**
There seems to be an alternative to setup the request_operation of operationId dimensions: 
https://istio.io/latest/docs/reference/config/proxy_extensions/attributegen/#PluginConfig
which require fragile envoy proxy setup which can break with upgrades
or which seems to be a newer way:
https://preliminary.istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

Which I was trying to follow to customize istiod with I install with helm.  The extraTag seems like it would be available if specified: https://github.com/istio/istio/blob/master/pkg/bootstrap/config.go#L171

but when I try to override the HELM values for istiod version 1.11:

```
meshConfig:
  enableTracing: true
  extraStatTags: request_operation
```

it does not seem to take effect on the injected envoy proxy Prometheus stats.  

Do I still need to do those operator overrides mentioned in the customize doc?  What's they reference to the request operation, "detination.path"?   Where is the collection of all possible objects available documented?

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by mikhail-khodorovskiy** [comment]
This may or may not be related to having the operation dimension in the metrics:  we export traces to datadog using HELM istiod override:
```
global:
  proxy:
    tracer: "datadog"
```
and they come with the operation of "envoy.proxy" instead of the path:

![Screen Shot 2021-11-24 at 9 42 02 AM](https://user-images.githubusercontent.com/44823822/143289133-41ebebf2-874b-4a8c-96fc-c4f8feeb36fc.png)

**Comment by bianpengyuan** [comment]
You will need to follow the metric customization doc to set expression for the tag, e.g. request.path, as documented here: https://preliminary.istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values.

We cannot add the operation or path to the metric by default because its cardinality is very likely unbounded and would cause too many prometheus time series being generated. Mesh admin has to consider whether it makes sense to add the dimension based on their apps behavior, and potentially use classification to reduce tag cardinality as needed: https://preliminary.istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

**Comment by mikhail-khodorovskiy** [comment]
Your answer makes sense.  We will put off adding the operation id dimension due the concerns you mentioned.   
The per-endpoint information the developers may be able to get through the Datadog exporting tracing info but right now operation name is "envoy.proxy" and the http path is not available as part of the information in the trace table.  Any guesses on how the operation name in the screen shot I've added above can become the operation id?  Is that related to the same metrics customization you mentioned?

**Comment by bianpengyuan** [comment]
I am not familiar with data dog, not sure where is that origin operation name from, but definitely has nothing to do with the metrics customization.

**Comment by douglas-reid** [comment]
@mikhail-khodorovskiy the full set of tracing attributes should be available. This includes the HTTP request path, etc.  See: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#what-data-each-trace-contains. [Datadog documentation](https://www.datadoghq.com/blog/istio-datadog/) suggests that reasonable span names should also be used in their tools. Perhaps it is worth filing an issue with Datadog for exploration?

Closing, as there does not seem to be further action. Please re-open as necessary.
