### ISSUE TITLE
Source service not being set for metrics/logs.

### ISSUE THREAD

**Issue by jeffmendoza** [istio/istio#3624]
I'm seeing this in the 0.6.0-pre 2/19 and 2/20 [daily builds](http://gcsweb.istio.io/gcs/istio-prerelease/daily-build/).

This is what Prometheus shows:
![metrics-unknown](https://user-images.githubusercontent.com/771387/36452239-99fd3180-1648-11e8-82a1-0fb2e9a8a7c6.png)

Here is a [Mixer log](https://gist.github.com/jeffmendoza/f4cb8844dd7ff53bcbd1b4c527ea0fe0) with `log_output_level=debug`

**Comment by jeffmendoza** [comment]
cc @mandarjog @nmnellis @douglas-reid

**Comment by mandarjog** [comment]
Thanks for the bug report, I am investigating.

**Comment by mandarjog** [comment]
hi @jeffmendoza can you do the following
`kubectl --namespace istio-system delete rules kubeattrgenrulerule`

and see if that changes anything?  I suspect that the kubenv config is the issue.

**Comment by jeffmendoza** [comment]
The rule was deleted, and same behavior

Tail of the log now:
https://gist.github.com/jeffmendoza/989cc8532764436f91eea769e4354991

**Comment by mandarjog** [comment]
Hey Jeff, it looks like this log only contains traffic sent by `request.useragent             : Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GoogleSecurityScanner; go/SecopsSecurityScan 1.337)
`
As far as I can see, no traffic reached the backend. If you can access /productpage it would be great.

**Comment by jeffmendoza** [comment]
Sorry about that, I restarted mixer and got a fresh log: https://gist.github.com/jeffmendoza/702e27918f83012ad03b03c3a8cb87d8

This is what I have after deleting the kubeattrgenrulerule
```
$ kubectl --namespace istio-system get rules
NAME       AGE
promhttp   21h
promtcp    21h
stdio      21h
```

**Comment by mandarjog** [comment]
Hey Jeff, can you try with the latest build?  Several PR have merged in last couple of days. I don’t see it in my testing. It also means we should have a test for this :-)

**Comment by mandarjog** [comment]
Your logs from yesterday look good, after k8senv adapter is removed. You still can’t see info in Prometheus ?

**Comment by jeffmendoza** [comment]
Hi @mandarjog, I'm not at work today/tomorrow, so unfortunately I can't. My setup was GKE 1.9, Apply istio-auth.yaml and ptomethus.yaml from the release tarball, then use ./bin/istioctl kube-inject to apply the bookshelf.yaml. Nothing else. I was using the "TESTONLY" tarball as mentioned [here](https://github.com/istio/istio/wiki/Daily-builds). If that is working for you, sounds good.

**Comment by jeffmendoza** [comment]
Tested the latest build `0.6.0-pre20180226-09-15-06` and source service is working well.
