### ISSUE TITLE
Istio 1.12 install on GKE displays error failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found

### ISSUE THREAD

**Issue by rubans** [istio/istio#36265]
### Bug Description

Running istioctl install --set profile=demo -y 

Seems to give a load of related to : 
ruban_siva@cloudshell:~ (safe-10723777)$ istioctl install --set profile=demo -y
✔ Istio core installed                
2021-11-25T17:47:19.163888Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.229916Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.268664Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.310016Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.524317Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.585655Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.631226Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.671009Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.721323Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.772799Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.826457Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
2021-11-25T17:47:19.886374Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
✘ Istiod encountered an error: failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/metadata-exchange-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.6": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.7": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.8": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found

I can however see pods and services running so not sure what specifically is the issue.
ruban_siva@cloudshell:~ (safe-10723777)$ kubectl -n istio-system get all
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-egressgateway-59c6bd6db4-gczqj    1/1     Running   0          11m
pod/istio-ingressgateway-78cc8f99ff-mt5ch   1/1     Running   0          11m
pod/istiod-8d4f5cc85-wl6x2                  1/1     Running   0          11m

NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                                                                      AGE
service/istio-egressgateway    ClusterIP      10.28.8.173    <none>           80/TCP,443/TCP,15443/TCP                                                     11m
service/istio-ingressgateway   LoadBalancer   10.28.0.226    35.242.131.114   15021:31236/TCP,80:31486/TCP,443:30692/TCP,31400:31989/TCP,15443:30804/TCP   11m
service/istiod                 ClusterIP      10.28.13.150   <none>           15010/TCP,15012/TCP,443/TCP,15014/TCP                                        11m

Can you assist pls?

### Version

```prose
ruban_siva@cloudshell:~ (safe-10723777)$ istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (2 proxies)
ruban_siva@cloudshell:~ (safe-10723777)$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zackzhangkai** [comment]
It really occured sometimes.

```
[root@k8s-node-1 ~]# istioctl version
client version: 1.10.0
control plane version: 1.11.3
data plane version: 1.11.3 (1 proxies)

[root@k8s-node-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by howardjohn** [comment]
I am a bit confused - you said 1.12 in the title but are using and installing 1.8?

**Comment by rubans** [comment]
@howardjohn sorry, I meant was reproducible on both 1.12 and 1.8. 
I tried using helm and istioctl install methods and get the same error effectively.

**Comment by rubans** [comment]
> It really encountered sometimes.
> 
> In the first time, said istiod service not exist.
> 
> ```
> ✘ Istiod encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-metadata-exchange-1.9: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-stats-filter-1.10: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> failed to update resource with server-side apply for obj EnvoyFilter/istio-system/tcp-stats-filter-1.11: Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=10s: service "istiod" not found
> ```
> 
> Then `kubectl get svc,deploy,pod -n istio-system`, there was no problem.But cannot find envoyfilter.
> 
> Then rollout restart istio operator deployment, it would be ok.
> 
> ```
> [root@k8s-node-1 ~]# istioctl version
> client version: 1.10.0
> control plane version: 1.11.3
> data plane version: 1.11.3 (1 proxies)
> 
> [root@k8s-node-1 ~]# kubectl version
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> ```

I did as you suggested perform the rollout but not seeing anything different when I run :
kubectl get svc,deploy,pod -n istio-system
How can I verify all the resources are expected to run are running?
problem with this is that I get the original error every time and when I run helm status, it will say install failed so it's an issue.
