### ISSUE TITLE
Unable to switch to in-cluster kubeconfig when empty value is passed

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#3626]
I was trying to create an Istio kubernetes crd client using the `NewClient`
[API](https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L120) from the Istio package and found that passing an empty `kubeconfig` value always returns an error instead of switching to in-cluster config.

```go
  import (
    "fmt"

    "istio.io/istio/pilot/pkg/config/kube/crd"
    "istio.io/istio/pilot/pkg/model"
  )

  c, err := crd.NewClient("", model.ConfigDescriptor{model.RouteRule})
  if err != nil {
    fmt.Printf("NewClient returns error when empty string is passed: %s\n", err)
  }
```

Based on the comment above the [API](https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L120) passing an empty value for `kubeconfig` should result in switching to in-cluster kubernetes config which is different than the behavior I'm observing.

Inspecting the code for the helper utility `ResolveConfig` in the [serviceregistry kube package](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/client.go#L40) I think that the resolution logic might be incorrect.

The `ResolveConfig` function checks for existence of a empty string named kubeconfig file which will always fails and incorrectly assigns the default config (`user's Home Dir + /.kube/config`) file which will not exist for in-cluster configuration.
Below is the snippet from the `ResolveConfig` utility function which does the incorrect assignment:

```go
	if kubeconfig == "" {
		usr, err := user.Current()
		if err == nil {
			defaultCfg := usr.HomeDir + "/.kube/config"
			_, err := os.Stat(kubeconfig)
			if err != nil {
				kubeconfig = defaultCfg
			}
		}
	}
```

Note the `stat` on `kubeconfig` instead of `defaultCfg` and the assignment to `kubeconfig` on non-nil error.

If going forward the only way to switch to an in-cluster client is to provide a kube config file with no data (which currently works) it would be helpful if the documentation is updated to reflect it.

**Comment by rshriram** [comment]
fixed recently by @GregHanson .. Please try again and let us know if the issue persists
