### ISSUE TITLE
Istio 1.12.0 sidecarInjectorWebhook.enableNamespacesByDefault does not work as expected

### ISSUE THREAD

**Issue by veichtj** [istio/istio#36261]
### Bug Description

After upgrading from istio 1.11.4 to istio 1.12.0 the sidecar injection seems not to work like before. 
We are using the `enableNamespacesByDefault:true` option to force sidecar injection without labelling certain namespaces. However after the upgrade to 1.12.0 this option seems to be no longer available? The webhooks config does not consider that flag any longer.
Also the release notes do not mention this, and there is no hint on a migration path?

Can you please clarify if this is expected behaviour or a bug? 

### Version

```prose
istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (2 proxies)
kubectl version --short
Client Version: v1.22.2
Server Version: v1.19.15
```

**Comment by cnvergence** [comment]
On install with default `istioctl install` it also seems to happen.
https://github.com/istio/istio/issues/36258

**Comment by Monkeyanator** [comment]
FYI @cnvergence's PR [here](https://github.com/istio/istio/pull/36260) should fix the issue.

**Comment by linsun** [comment]
Yes, thank you @cnvergence!  Note: For 1.12, the PR needs to be cherrypicked to release-1.12 branch.

**Comment by cnvergence** [comment]
Ah, right, thanks for preparing the cherrypick PR :)

**Comment by veichtj** [comment]
@Monkeyanator - thx for the update, I will watch for the related issue and close this one
