### ISSUE TITLE
Fallback Certificate

### ISSUE THREAD

**Issue by prary** [istio/istio#36264]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Is it possible to use fallback certificate secret with ingress gateway?
We use contour as ingress controller in out kubernetes cluster and we have istio running with ingress gateway.
We want https traffic to passthrough contour to istiogateway and  istiogateway should terminate tls connection using fallback Certificate. Is there a way where we can use fallback certificate just like contour does https://projectcontour.io/docs/v1.19.1/config/tls-termination/#fallback-certificate

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
There is no native 'fallback certificate'. But if you want to. match an empty SNI you can set the hostname to `*` which would accommodate the use case on the doc you linked?
