### ISSUE TITLE
Add a support for deploying multiple ingress/egress gateways using helm charts

### ISSUE THREAD

**Issue by anannaya** [istio/istio#36267]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is already supported? It's not clear what the request is
Take a look at https://istio.io/latest/docs/setup/additional-setup/gateway/

**Comment by anannaya** [comment]
official helm charts does loop around the k8s objects(deploy/service) to create a multiple gateways.  Anyway i managed implement that in helm charts.

**Comment by howardjohn** [comment]
That is not the right direction IMO. Different gateways should be different helm deployments with distinct release names that drive the application name. Creating two applications with a single helm chart is an anti pattern

**Comment by anannaya** [comment]
Paas it's a valid requirement to install multiple gateways. Anyway thank you so mu so much answering the queries.

**Comment by howardjohn** [comment]
I agree, by doing `helm install gw-1; helm install gw-2`. Not a single
release with multiple Deployments
