### ISSUE TITLE
Istio to support Ingressgateway listener to bind on non-0.0.0.0 IP address

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#36282]
(This is used to request new product features, please visit https://discuss.istio.io for questions on using Istio)

**Describe the feature request**
Istio release-1.10 introduced the bind field in Gateway object, related code is here:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/gateway.go#L81-L84

It looks promising to bind on non-0.0.0.0 IP address but according to the doc, this bind is not available to external gateway clients:
```
The ip or the Unix domain socket to which the listener should be bound to. Format: x.x.x.x or unix:///path/to/uds or unix://@foobar (Linux abstract namespace). When using Unix domain sockets, the port number should be 0. This can be used to restrict the reachability of this server to be gateway internal only. This is typically used when a gateway needs to communicate to another mesh service e.g. publishing metrics. In such case, the server created with the specified bind will not be available to external gateway clients.
```
We tried to create below gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
    bind: 172.10.0.8
EOF
```

But got problem
2021-11-02T02:08:21.528433Z	warn	ads	ADS:LDS: ACK ERROR xxxxx Internal:Error adding/updating listener(s) 172.10.0.8_8080: cannot bind '172.10.0.8:8080': Address already in use

Here is an explanation for this error: https://stackoverflow.com/a/14388707

So not sure if upstream is going to support this feature in the future and what's the consideration? And actually Envoy supports to bind on non-0.0.0.0 IP address.

Currently the problems we are facing with the wildcard address listener are:
1. SNI mandatory, if the client doesn't support SNI it will get TLS handshake error.
2. Port Protocol conflict. If one user creates a HTTPS gateway on port 8082 and another user creates a gateway on 8082 but protocol is HTTP, then the latter one won't work.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Does your pod have multiple IPs for this use case? Or how exactly does this work?

**Comment by shonecyx** [comment]
Thanks @howardjohn for you reply. 

In our use case, we have the micro services in mesh. For example we'll create 1k Gateway, 1k VirtualService and 1k Service in the same mesh and there is one host match route in each VirtualService to route traffic to one backend service. However for each Gateway, we'll create a Gateway service with dedicated VIP and those dedicated VIP will serve the ingress traffic from external.

So we got this problem, for those 1k VIPs since envoy is listening on 0.0.0.0 not the actual VIP, Istio does the gateway merge which caused the issues like I mentioned:

1. Client SNI mandatory but we do have some clients don't support SNI.
2. Port protocol conflict since envoy doesn't support different protocols on same listener.
3. Idle timeout for downstream connections is not configurable at VIP level and we do have different services need different Idle timeout for downstream connections.

I would like to know if upstream has the plan to extend gateway bind field for this purpose or what is the consideration to not support, thanks in advance.

**Comment by howardjohn** [comment]
I don't think that is possible from a Kubernetes perspective, ignoring Istio/Envoy constraints. For example, I created a service with IP `10.96.216.160`

Then try to bind to this service IP in the pod:
```
$ nc -l -p 444 -s 10.96.216.160
nc: bind: Address not available
```

Its *Virtual* IP address. Kubernetes will redirect it to <Pod IP>:<Target Port>. If the pod is not bound to <Pod IP> (or 0.0.0.0 which is a wildcard so includes it), then it would not accept any traffic from the service.

**Comment by howardjohn** [comment]
If you want to do this you would need 1 unique target port per Service I think

**Comment by shonecyx** [comment]
@howardjohn 

In our case, we are using IPVS IPIP tunnel as the L4 loadbalancer which will route traffic to IngressGateway pod through IPIP tunnel, hence the VIPs are configured in IngressGateway pod tun0 interface:

```
tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.0.0.1/32 scope global tunl0
       valid_lft forever preferred_lft forever
    inet 10.0.0.2/32 scope global tunl0
       valid_lft forever preferred_lft forever
    inet 10.0.0.3/32  scope global tunl0
       valid_lft forever preferred_lft forever
    inet 10.0.0.4/32  scope global tunl0
```

So in the gateway pod, we'll be able to create a listener and bind to this VIP. And apart for tun0, we can also configure the VIP to ingress gateway pod loopback interface if it's not IPIP tunnel, so there is no gap from Kubernetes perspective based on our implementation.

In our frontend service, we are using Contour as the control plane for the Envoy edge and we got same problem and we extend IngressRoute to support bind listener to different VIP for different IngressRoute:

```
apiVersion: contour.ufes.io/v1beta1
kind: IngressRoute
metadata:
  name: gateway-443
  namespace: ns
spec:
  http_connection_manager:
    idle_timeout: 600s
    stat_prefix: ingress_http
    use_remote_address: true
  listener:
    bind: 10.0.0.1
    port:
      number: 443
```
So in the edge envoy config dump, we can see there are multiple listeners bind to different VIPs:

```
--
    {
     "name": "gw/gw-1-443",
     "active_state": {
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "gw/gw-1-443",
       "address": {
        "socket_address": {
         "address": "10.0.0.1",
         "port_value": 80
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
--
    {
     "name": "gw/gw-2-443",
     "active_state": {
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "gw/gw-2-443",
       "address": {
        "socket_address": {
         "address": "10.0.0.2",
         "port_value": 443
        }
       },
       "filter_chains": [
        {
         "filters": [
```

That why we are looking for similar capability in Istio.

**Comment by shonecyx** [comment]
>If you want to do this you would need 1 unique target port per Service I think

@howardjohn that's a workaround but doesn't work for all use cases. Currently we are migrating VIPs from hardware loadbalancer to IPVS + Istio,  existing micro-services VIPs with ports are widely being used by many clients, so if we have to assign unique port to different gateway, then all clients need to change their code.

Another workaround is that we can have same gateway port for different VIPs, but in the gateway service we'll allocate a different target port(like the kubernetes service node port), so we'll need a target port allocate mechanism but that's also not elegant if we have multiple mesh clusters.

**Comment by howardjohn** [comment]
I see, thanks for the explanation.

So looking at the error again, we actually are not rejecting it at all - its failing due to `cannot bind '172.10.0.8:8080': Address already in use`

In my cluster this ends up creating a listener like
```
       "address": {
        "socket_address": {
         "address": "10.244.0.88",
         "port_value": 8080
        }
       },
```

Which seems the same as contour.

Do you have this IP set multiple times maybe so its conflicting?

**Comment by shonecyx** [comment]
Thanks @howardjohn, I just tried the gateway `bind` option and it's now working. I can see the listener for this VIP in envoy config dump but looks like it's still SNI mandatory since there is `filter_chain_match`. Does it mean there is no way to disable SNI unless we set a `*` in the gateway host? With individual listener, we are able the configure the wildcard server name for each VIP/listener to achieve this.
```
    {
     "name": "10.0.0.1_8443",
     "active_state": {
      "version_info": "2021-12-02T04:45:15Z/359950",
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "10.0.0.1_8443",
       "address": {
        "socket_address": {
         "address": "10.0.0.1",
         "port_value": 8443
        }
       },
       "filter_chains": [
        {
         "filter_chain_match": {
          "server_names": [
           "abc.example.com"
          ]
         },
```

**Comment by shonecyx** [comment]
@howardjohn  Probably for security concern, we won't issue cert with wildcard host in the SNI although here the cert SNI can be non-wildcard.

BTW good to know the gateway `bind` is working. Is this field designed to support the multiple listener case? And at least this feature works for below to issues:

1. Port protocol conflict
2. Idle timeout for downstream connections per listener

**Comment by howardjohn** [comment]
Certificate SAN and SNI do not need to be identical. You can have a cert
for `foo.example.com` and have the gateway match `*`. If you are
already distinguishing by IP instead of SNI/Host then seems reasonable to
use `*`.

> Is this field designed to support the multiple listener case

It was original added mostly to support localhost bind. I think your case
is quite unique in Kubernetes, but glad it works as well...

**Comment by shonecyx** [comment]
Thanks @howardjohn for you comments, closing this issue now as already supported.
