### ISSUE TITLE
Support delta xds in adsc

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#36297]
ADSC is heavily depended by xds tests, but it only works in sotw mode now, so we donot have any complete ut for delta xds.

**Comment by howardjohn** [comment]
I have a client here: https://github.com/howardjohn/pilot-load/blob/master/adsc/delta.go

It has a lot of bugs :-)

**Comment by hzxuzhonghu** [comment]
Good, do you have bandwidth on it?

**Comment by howardjohn** [comment]
Probably not any time soon

**Comment by hzxuzhonghu** [comment]
Still lack delta in adsc

**Comment by howardjohn** [comment]
I've been working on this 15min here and there for a few months. Not a high priority but if anyone else is thinking about picking this up please talk to me first so we are on the same page

**Comment by tanujd11** [comment]
Hi @howardjohn , I would like to work on this if it is not close to completion. It will be great if you can point me to work that you have done. Thanks.

**Comment by howardjohn** [comment]
https://github.com/howardjohn/istio/tree/adsc/v2-delta. And we basically have a rust version in https://github.com/istio/ztunnel/blob/master/src/xds/client.rs

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/48031

**Comment by hanxiaop** [comment]
> #48031

Didn't realize we had an issue and that someone is already working on it... I noticed the recent delta xDS issue and thought we could support delta adsc for commands. So I was trying to start working on this.

**Comment by hzxuzhonghu** [comment]
@hanxiaop I donot think anyone is working on it now. Just refer to the draft implement from @howardjohn

**Comment by hanxiaop** [comment]
> @hanxiaop I donot think anyone is working on it now. Just refer to the draft implement from @howardjohn

Thanks, I'm going to have a look.

**Comment by tonya11en** [comment]
Is there still anything that needs to be done here after https://github.com/istio/istio/pull/48031 merged?

**Comment by hanxiaop** [comment]
> Is there still anything that needs to be done here after #48031 merged?

Maybe tests that can relay delta adsc. I think this can be closed for now.
