### ISSUE TITLE
Add support for gRPC probe

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36314]
Our probe rewrite needs to handle https://github.com/kubernetes/enhancements/issues/2727

**Comment by dddddai** [comment]
Hello @howardjohn, are we gonna rewrite the original probe to http probe, or just rewrite the port/service and introduce a grpc server in `pilot-agent`?

**Comment by howardjohn** [comment]
Hmm good question.. Is the gRPC always the standard GRPC health service? Or. somehow allows custom services?

I am leaning towards rewrite it to http. It doesn't really matter to users what the protocol to the agent is, just what protocol we use when forwarding which will of course be gRPC?

**Comment by dddddai** [comment]
Thanks for your reply!
> Is the gRPC always the standard GRPC health service? Or. somehow allows custom services?

Yes it must be a standard GRPC health service, please refer to [k8s doc](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#probe-check-methods)

> I am leaning towards rewrite it to http. It doesn't really matter to users what the protocol to the agent is, just what protocol we use when forwarding which will of course be gRPC?

Agree, I'm trying to implement it

**Comment by howardjohn** [comment]
Ack, thanks for the info. I would lean towards rewriting to http o
probe and then the agent forwarding as gRPC. That seems simplest to me and
should not have negative side effects for users
