### ISSUE TITLE
TestShouldSkip test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36317]
This is because `shouldSkip` is doing order-dependant iteration over a map which is nondeterministic. I think this is a bug in the code, not just the tests.

**Comment by zhlsunshine** [comment]
Hi @howardjohn,  I was following the description of [definition SelectionSpec](https://github.com/istio/istio/blob/8b2ae9448c29cb8926999b2e3c187f3cb579e1b3/tools/bug-report/pkg/config/config.go#L28) when implementing shouldSkip.
Beside `Exclusions have a higher precedence than inclusions`,  I noticed from examples that there should be an order from namespace to label or annotation.  Does it make sense?
