### ISSUE TITLE
Content-Type Header empty for prometheus metric request on istio-gateways

### ISSUE THREAD

**Issue by markuslackner** [istio/istio#36330]
### Bug Description

The "Content-Type" header for prometheus metrics scrape on istio gateways is empty on port 15020

```
❯ kubectl exec istio-ingressgateway-7bdfb4cf6b-5fcjh -- curl -v localhost:15020/stats/prometheus
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:15020...
* TCP_NODELAY set
* Connected to localhost (::1) port 15020 (#0)
> GET /stats/prometheus HTTP/1.1
> Host: localhost:15020
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type:
< Date: Wed, 01 Dec 2021 19:24:06 GMT
< Transfer-Encoding: chunked
<
{ [44090 bytes data]
```

This problem is only on port 15020 on all gateways (egress and ingress). The "content-type" header is set correctly 

* on sidecar envoys port 15020
* on gateway pods port 15090 (only envoy metrics)

Tested on different installations (istio 1.12.0 on kind, istio 1.11.4 on VMWare PKS).  The [specification](https://prometheus.io/docs/instrumenting/exposition_formats/#basic-info) does demand a "content-type" header.

### Version

```prose
❯ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (3 proxies)
❯ kubectl version --short
Client Version: v1.21.3
Server Version: v1.21.1
```

**Comment by davidmortiz** [comment]
I'd like to take a stab at this if nobody minds

**Comment by markuslackner** [comment]
I started looking into this but would appreciate help! I think the error is in this if block:

https://github.com/istio/istio/blob/409ccf1422a6843b4776fa5a99e1be91a49481b4/pilot/cmd/pilot-agent/status/server.go#L462

```
	var format expfmt.Format
	if s.prometheus != nil {
		var contentType string
		url := fmt.Sprintf("http://localhost:%s%s", s.prometheus.Port, s.prometheus.Path)
		if application, contentType, err = s.scrape(url, r.Header); err != nil {
			log.Errorf("failed scraping application metrics: %v", err)
			metrics.AppScrapeErrors.Increment()
		}
		format = negotiateMetricsFormat(contentType)
	}
```
`format` is only set if application metrics are available.

**Comment by davidmortiz** [comment]
This change fixes it https://github.com/istio/istio/compare/master...davidmortiz:istio-36330?expand=1

Just working on a test

**Comment by zirain** [comment]
I think this's fixed by https://github.com/istio/istio/pull/36371
