### ISSUE TITLE
Installing with istioctl requires writing files to /tmp

### ISSUE THREAD

**Issue by vojtechmasa** [istio/istio#36333]
### Bug Description

We have a cluster-wide policy to use read only filesystem in all pods. We are installing Istio from a pod. It seems like after upgrading from 1.11.4 to 1.12.0, istioctl requires writing files to /tmp:

```
istioctl install -f - --readiness-timeout 1200s --skip-confirmation

Error: failed to apply tag manifests to cluster: failed creating manifest file: failed creating temp file for manifest: open /tmp/revision-tag-manifest-2520553774: read-only file system
```

We use Istio operator. Is there a way to prevent installer from laying down the temp file?
We did not experience that behavior with Istio 1.11.4.

### Version

```prose
% ./istioctl version

client version: 1.12.0
control plane version: 1.11.4
data plane version: 1.11.4 (1 proxies)

% kubectl version --short
Client Version: v1.21.5
Server Version: v1.19.11
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Comment by Monkeyanator** [comment]
The root cause is here https://github.com/istio/istio/blob/master/istioctl/pkg/tag/generate.go#L305, we render the templates and then apply them through our client for the default tag. I'm sure there's a way to do this in memory, but I'm not seeing examples of it in our codebase and would need to look more into it.

**Comment by vojtechmasa** [comment]
Thanks for the update. Do you guys plan to "fix" it? If so, would you have an idea about the timeline? I was thinking we could mount a Kubernetes volume to `/tmp` as a workaround.

**Comment by vojtechmasa** [comment]
@Monkeyanator is there possibly a plan to fix this? We need to mount writable volume to /tmp to workaround this issue. Thanks.
