### ISSUE TITLE
Aws eks can't access rds when istio is enable 

### ISSUE THREAD

**Issue by DreamerLeon** [istio/istio#36359]
### Bug Description

My rds and eks in same vpc's different private subnet , my application can't access mysql rds, Error info is `lookup rds-xxx.example.com\n: no such host`. , But when I login to pod and execute  `nslookup rds-xxx.example.com`,Domain can be resolved, I also try to create a external service or service entry , Nothing changed, My application still can't resolve rds domain but  `nslookup rds-xxx.example.com` working fine 

### Version

```prose
$ client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (2 proxies)

$ kubectl version
Client Version: v1.22.3
Server Version: v1.21.2-eks-06eac09
```

**Comment by DreamerLeon** [comment]
Networking config error

**Comment by ramaraochavali** [comment]
@DreamerLeon did it work for you? We are also trying to access RDS and getting 
139939434719120:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1493:SSL alert number 40

suspecting some thing with SNI based on https://stackoverflow.com/questions/53965049/handshake-failure-ssl-alert-number-40

Did you have to set SNI?

**Comment by DreamerLeon** [comment]
> 

Can't connect db directly , Create a service

**Comment by ramaraochavali** [comment]
Sorry. Did not understand. We have created service entry - are you referring to some other service?

**Comment by DreamerLeon** [comment]
@ramaraochavali Create a Kube Service, you need install istio-ingress and istio-egress
