### ISSUE TITLE
Did anyone successfully build istio/proxy on RHEL 7 x86_64?

### ISSUE THREAD

**Issue by choppspavan** [istio/istio#36354]
Hi ,

I am just trying to understand , is anyone successfull in building istio/proxy using source code on RHEL 7 x86_64 , if so can you pass any document/blog references to do it. I found out in the forums most of them talk about building on ubuntu .

Thanks,
Pavan

**Comment by bianpengyuan** [comment]
Probably would be easier to build with docker container: `docker run -u <your-user-id> -it -v $(pwd):/work gcr.io/istio-testing/build-tools-proxy:master-2021-11-22T20-08-26 -- bash` where $(pwd) is your istio/proxy folder. Then inside container, run `make build_envoy` under `/work`. Then you should be able to find proxy binary under `/work/bazel-bin/src/envoy`.

**Comment by choppspavan** [comment]
Thanks for the response , I am trying to build (istio-proxy-release 1.6 source code) using the above docker procedure that you mentioned.Hitting the below issue.

export PATH=/usr/lib/llvm-9/bin:/usr/lib/llvm/bin:/usr/local/go/bin:/gobin:/usr/local/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CC=clang CXX=clang++ && bazel  build  --config=libc++ //...
Putting child 0x1904650 (build) PID 3167 on the chain.
Live child 0x1904650 (build) PID 3167
INFO: Analyzed 212 targets (0 packages loaded, 0 targets configured).
INFO: Found 212 targets...
ERROR: Process exited with status 1
ERROR: /work/tools/docker/BUILD:35:1 Process exited with status 1
INFO: Elapsed time: 0.965s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
Reaping losing child 0x1904650 PID 3167
Makefile.core.mk:68: recipe for target 'build' failed
make: *** [build] Error 1
Removing child 0x1904650 PID 3167 from chain.
build-tools:/work#

**Comment by bianpengyuan** [comment]
Then you will need to use the docker image corresponding to 1.6 branch: https://github.com/istio/proxy/blob/release-1.6/Makefile#L37

**Comment by choppspavan** [comment]
Still facing the same issue with the image pointed above image.

Note: The container using ubuntu where our requirement was on RHEL . Anyway we are not succesfull in building the container.
build-tools:/work# make
Building with your local toolchain.
export PATH=/usr/lib/llvm-9/bin:/usr/lib/llvm/bin:/usr/local/go/bin:/gobin:/usr/local/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CC=clang CXX=clang++ && bazel  build  --config=libc++ //...
2021/12/06 06:29:17 Downloading https://releases.bazel.build/2.2.0/release/bazel-2.2.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed 212 targets (740 packages loaded, 37007 targets configured).
INFO: Found 212 targets...
ERROR: Process exited with status 1
ERROR: /work/tools/docker/BUILD:35:1 Process exited with status 1
INFO: Elapsed time: 213.352s, Critical Path: 0.16s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
Makefile.core.mk:68: recipe for target 'build' failed
make: *** [build] Error 1
build-tools:/work#

pchoppak-mac:proxy-release-1.6 pchoppak$ docker images -a
REPOSITORY                               TAG                               IMAGE ID       CREATED         SIZE
gcr.io/istio-testing/build-tools-proxy   release-1.6-2020-11-13T15-30-50   7af103d82bc0   12 months ago   4.63GB

**Comment by bianpengyuan** [comment]
Not sure.. the log message does not provide any useful debug information.

> Note: The container using ubuntu where our requirement was on RHEL 

I see, you are actually not just looking for a way to build the image, but has to build it on RHEL. I am not sure then. Looks like upstream envoy also do not have official support for this yet: https://github.com/envoyproxy/envoy/issues/16867

**Comment by choppspavan** [comment]
Thanks for your earlier replies, aren't they any references to build on RHEL? Like mentioning about the pre requisities required to build from istio-proxy or some docker container using rhel.

**Comment by bianpengyuan** [comment]
@choppspavan I don't know of any guide on that.. Probably better to ask upstream at Envoy (there is nothing special about building istio proxy comparing to building upstream envoy).

**Comment by huanghuangzym** [comment]
i rebuild a centos7 build image and success to build envoy 1.18

**Comment by sebastiantoaderness** [comment]
> i rebuild a centos7 build image and success to build envoy 1.18

Can you provide details on how you managed this?
