### ISSUE TITLE
Cannot connect to cloudsql

### ISSUE THREAD

**Issue by domcar** [istio/istio#36383]
### Bug Description

Some service cannot establish a connection to cloudsql (gcp) when Istio Sidecar is enabled, the error that I see in the logs is:

`Error creating bean with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection`

So I guess there is a problem when reaching the cloudsql.

I don't have any special Istio configuration, i simply deployed it and was testing on some services

### Version

```prose
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (12 proxies)

I deployed istio 1.12.0 with helm chart
```

### Affected product area

- [X] Networking

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by domcar** [comment]
so, apparently the issue is solved if I add a serviceEntry with the IP of the cloudSql. 
Can anyone explain me if this is how it is supposed to be? As far as I could tell from the documentation, a serviceEntry is an optional step to add some external service to the internal Istio service registry. If not, can you point me to the right documentation explaining this?

**Comment by bianpengyuan** [comment]
You should not need to define service entry if you are using allowany mode. Get a bug report from your cluster would help diagnose: https://istio.io/latest/docs/releases/bugs/#kubernetes-cluster-state-archives

**Comment by domcar** [comment]
Hello @bianpengyuan thanks for you reply, I'm uploading a the report
[bug-report.tar.gz](https://github.com/istio/istio/files/7666450/bug-report.tar.gz)

**Comment by bianpengyuan** [comment]
Looks like there are some internal services with protocol of unspecified protocol, and lead to traffic to external service failed. It should work if you specify the protocol (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection) for services with port 5432 and 443 (which I believe is the port used for google cloudsql?). You can read istioctl analyze result to find those services which needs to have protocol specified.

@howardjohn curious, do we always have this problem (an auto port would cause traffic to external services with the same port forwarded wrongly).

**Comment by howardjohn** [comment]
Specifically ExternalName. See https://github.com/istio/istio/pull/36323

**Comment by bianpengyuan** [comment]
Ah I see I did not notice that there is an externalname service with same unnamed port 5432. Then I think you just need to add the protocol to 5432 port at `cibo/postgres-service`.

**Comment by domcar** [comment]
Hi, i added the name to the service port:
```
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: ExternalName
  ```
  but this didn't help, without a serviceEntry I can't reach the cloudsql.
I also checked other services that use port 5432 and they all have a protocol and name specified

**Comment by bianpengyuan** [comment]
See https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

**Comment by bianpengyuan** [comment]
Also please note you will need to use either https or tls for externalname service. tcp won't work.

**Comment by domcar** [comment]
Thank you very much, this solved the issue, but I must say this was to me really unexpected that a service configured in another namespace where no mesh part is running, is having such an impact.
Anyway I'll close the issue
