### ISSUE TITLE
Pod can't connect to VirtualService 

### ISSUE THREAD

**Issue by prateek1192** [istio/istio#36393]
I am getting an error which Indicates that there is no virtual service with such a name 

```! Causing: unirest.shaded.org.apache.http.conn.HttpHostConnectException: Connect to tc3ebc2a4.c1c-routing.svc.cluster.local:80 [tc3ebc2a4.test-namespace.svc.cluster.local/172.20.68.120] failed: Connection refused (Connection refused)
! 	at unirest.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
```

But when I look up the virtual services, I can see that it exists.

``` 
bash-5.1$ kubectl get svc -n test-namespace
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
tc3ebc2a4                  ClusterIP   172.20.68.120    <none>        80/TCP              3d3h1
```

I have tried looking into the istio-proxy sidecar pod for the outbound log message to get more insight but I couldnt find anything there. What can be my possible directions be to find out if its a Istio bug or a configuration issue.

**Comment by bianpengyuan** [comment]
Can you provide more info? Like your virtual service config, and access log https://istio.io/latest/docs/tasks/observability/logs/access-log/ or proxy debug log: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2
