### ISSUE TITLE
Do not keep connections alive for intercepted health probes.

### ISSUE THREAD

**Issue by flatmap13** [istio/istio#36390]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

It appears that Istio currently keeps connections alive when intercepting health probes (readiness and liveness). Kubelet does not keep connections alive for such health probes. Thus behavior of health probes changes in very subtle ways when the sidecar is injected. For example, when the connections are kept alive, idle timeouts can occur leading to sporadic 503 responses sent to Kubelet.

**Describe alternatives you've considered**

No sensible alternatives come to mind.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
I remember we intended to reuse the connection.

>when the connections are kept alive, idle timeouts can occur leading to sporadic 503 responses sent to Kubelet.

The probe is periodic, i am not sure i understand the idle timeout leading to sporadic 503
