### ISSUE TITLE
 Extended `istioctl x metrics`:  Exact and fuzzy queries metrics resouce

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#36428]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Extend the istioctl experimental metrics command to allow batch query by to specify some filter flags

*Background*
The experimental metrics command was added to istioctl to provide a simple CLI-based dashboard for interacting with Istio metrics. It provides a workload-level monitoring of one or more workloads, and must specify correct workloads name.

*Requirements*

- Provides a user-friendly and flexible function for querying workload metrics
- Support query to specify workload
- Support query specified service
- Support batch query specified namespace
- Supports queries to precisely specify the original workload to the target workload
- Supports batch queries for workloads that precisely specify the original namespace to the target namespace

design doc： https://docs.google.com/document/d/1ATp4qCHktncfAFjH_S9yWm9dGxI_aXHN2cw1AD4kveQ/edit?usp=sharing

**Comment by nicole-lihui** [comment]
Does anyone have some thoughts? @istio/wg-policies-and-telemetry-maintainers

**Comment by douglas-reid** [comment]
@nicole-lihui have you seen https://github.com/istio/istio/issues/24309 ?  It links to a RFC doc on improvements.

**Comment by nicole-lihui** [comment]
> @nicole-lihui have you seen #24309 ? It links to a RFC doc on improvements.
@douglas-reid 

I did not seen before, but this RFC doc with my idea coincides with mine.
I want to be able to participate in the improvements of this feature，how do I begin to share code? 
I maybe  directly to implement code ? Or need to provide a design documents?

**Comment by douglas-reid** [comment]
@nicole-lihui it would be great to have a fuller design doc, first (just to speed up the code reviews). doesn't have to be super long, just enough to specify the full set of improvements/additions. From there, we can jump directly in to PRs.

**Comment by nicole-lihui** [comment]
@douglas-reid Here's a simple design doc.

https://docs.google.com/document/d/1ATp4qCHktncfAFjH_S9yWm9dGxI_aXHN2cw1AD4kveQ/edit?usp=sharing

**Comment by zirain** [comment]
not stale
