### ISSUE TITLE
Use network metadata exchange for both L4 and L7

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#36420]
Header based http metadata exchange is less ideal because it is not efficient and could leak intra mesh information (https://github.com/istio/istio/issues/35283, https://github.com/istio/istio/issues/17635). As an alternative we can use network metadata exchange for both L4 and L7, which is more efficient (will exchange only once at beginning of connection), and will only exchange when both sides are inside the mesh.

https://github.com/istio/istio/pull/36341 is a prototype of this, which includes the following changes:
* At dataplane, update mx filter to take any istio ALPN protocols (https://github.com/bianpengyuan/proxy/commit/d44f9e292db789083a3ba8aee4771b136c33ea29) and do not rely on `h2` for codec selection (https://github.com/bianpengyuan/envoy/commit/91f5a723ce76c9f938a3da95e1701941a2ca6c2b, a better/proper change would be to ignore non-standard alpn for codec selection).
* Use Istio http ALPNs at http filter chain downstream TLS context https://github.com/istio/istio/pull/36341/files#diff-547581377ac62ee4adeea2cc06a827ace1829134c3c2037c089e6c8d1e0dc320

A very preliminary performance measurement shows a bit latency improvement:
<img width="2465" alt="P50 latency" src="https://user-images.githubusercontent.com/34738376/145101241-600d62e9-b856-469f-93e8-a819624364ce.png">
<img width="2459" alt="P90 latency" src="https://user-images.githubusercontent.com/34738376/145101248-f0f9d39a-e4d0-4a76-9fb7-f85fa23f8637.png">

Considering performance improvement is not much, we probably should table this for now to wait for HBONE, instead of deepen the ALPN hack. Open this issue to record the prototype work, in case we need a metadata leak solution before HBONE lands.

cc @kyessenov @mandarjog @lambdai

**Comment by kyessenov** [comment]
You are right about the efficiency. The main problem with TCP MX is interoperability, really, and it's a hard to draw network perimeter around Istio-only endpoints.
HBONE has its own set of challenges because of tunneling (e.g. separate tunnel per source) so it's not immediately more efficient.

**Comment by howardjohn** [comment]
If we move to TCP, do we lose the ability to do MX for Envoy -> Envoy when not using mTLS? Does that work with HTTP today?

It is an edge case for sure.

**Comment by bianpengyuan** [comment]
> If we move to TCP, do we lose the ability to do MX for Envoy -> Envoy when not using mTLS? Does that work with HTTP today?

Right, if we are going to do this, we will make it an option, with default still being HTTP + TCP. If user want to avoid header leak to outside of the mesh and confident mTLS is used everywhere, they can turn the option on.

**Comment by kyessenov** [comment]
TCP metadata exchange should not be applied when Envoy acts like a gateway for different sources. So as long as we respect that, it's safe to just use TCP metadata.

**Comment by bianpengyuan** [comment]
> Could we also do TCP if we use mTLS and fallback to HTTP when its plaintext? So we get the current functional behavior but optimized performance in the mesh?

Yeah I think that's possible, although the performance improvement seems to be quite small. I think a stronger motivator would be avoiding header leaking, which will not be solved by this approach.

**Comment by howardjohn** [comment]
Given the directional move to HBONE, seems like this is probably close-able? @kyessenov @keithmattix @zirain ?

**Comment by keithmattix** [comment]
+1 to closing

**Comment by zirain** [comment]
+1 to closing
