### ISSUE TITLE
Access log include virtual service's namespace

### ISSUE THREAD

**Issue by max0ne** [istio/istio#36424]
**Describe the feature request**
Our company run multi-tenant clusters, using namespace as tenant boundaries. We'd like to be able to filter istio ingress gateway's access logs using namespace as an attributes. However currently we don't see this as an option.

I see istio access logs are coming from [Envoy's access logs](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage), and at this level the concept of k8s namespace is already stripped away. I'd imagine this will require using Envoy's Dynamic Metadata, but I'm not so familiar with this part. If someone could help me with some pointers, I'd love to create a PR

**Describe alternatives you've considered**
I can't find anyway to workaround this.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
When you say filter do you mean like "include logs for requests to foo namespace but not bar"? Or something else?

**Comment by max0ne** [comment]
@howardjohn 
> When you say filter do you mean like "include logs for requests to foo namespace but not bar"?
yes exactly

**Comment by howardjohn** [comment]
Ok. We don't have anything merged yet but I believe @douglas-reid is doing some work that would allow this in 1.13 (hopefully). Basically will allow filtering access logs using CEL requests, which could certainly do this

**Comment by max0ne** [comment]
> Ok. We don't have anything merged yet but I believe @douglas-reid is doing some work that would allow this in 1.13 (hopefully). Basically will allow filtering access logs using CEL requests, which could certainly do this

I'm not sure that'll satisfy our need. Currently the JSON structure of access log looks something like:

```json
{
    "requestMethod": "GET",
    "requestUrl": "/foo/bar",
    "status": 200
}
```

We'd like to have virtual service's namespace included in access log:

```diff
{
    "requestMethod": "GET",
    "requestUrl": "/foo/bar",
    "status": 200,
+   "namespace": "foo"
}
```

The filtering will be done in our external logging system

**Comment by howardjohn** [comment]
Ah, I see. You can already customize the format (
https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format),
the tricky part is getting the namespace. I think CLUSTER_METADATA can get
this info but would need to try it out

**Comment by hzxuzhonghu** [comment]
@zirain may have some investigation

**Comment by douglas-reid** [comment]
@max0ne how do you current ingest the generated access logs?

**Comment by douglas-reid** [comment]
@howardjohn i think there is a slight ugliness with using CLUSTER_METADATA, as services is a list.

For instance:

- `accessLogFormat: "[%START_TIME%] %PROTOCOL% %RESPONSE_CODE% %CLUSTER_METADATA(istio:services)%\n"`

produces results like:

```
[2021-12-08T19:02:18.796Z] HTTP/1.1 200 [{"namespace":"default","host":"ratings.default.svc.cluster.local","name":"ratings"}]
[2021-12-08T19:02:20.658Z] HTTP/1.1 200 [{"name":"ratings","namespace":"default","host":"ratings.default.svc.cluster.local"}]
```

But trying with `istio:services:namespace` results in: `[2021-12-08T18:59:35.449Z] HTTP/1.1 200 -`

**Comment by max0ne** [comment]
@douglas-reid thanks, this gives us a good direction.

> @max0ne how do you current ingest the generated access logs?

We ingest all container logs of ingress gateway pods, with [vector](https://vector.dev/) and [humio](https://www.humio.com/). It's pretty flexible we can do some post processing on the logs to extract the namespace from that list

> %CLUSTER_METADATA(istio:services)%

I put this into accessLogFormat field but it got rejected:

```
k get iop default -oyaml | grep -a2 accessLogFormat
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: |
      [%START_TIME%] %PROTOCOL% %RESPONSE_CODE% %CLUSTER_METADATA(istio:services)%
    defaultConfig:
```


```
2021-12-08T20:01:12.441687Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Not supported field in StreamInfo: CLUSTER_METADATA(istio:services)
0.0.0.0_80: Not supported field in StreamInfo: CLUSTER_METADATA(istio:services)
```

**Comment by douglas-reid** [comment]
@max0ne which version of Istio are you using?  i was testing with `1.11.4`.

Yeah, i was thinking that whatever is extracting logs may be able to augment the data with other known metadata.

**Comment by max0ne** [comment]
We're using `1.9.6`

**Comment by max0ne** [comment]
@douglas-reid 
I think with istio `1.9.6`, envoy is on `v1.17.1`, `CLUSTER_METADATA` is not available yet.

**Comment by max0ne** [comment]
I tried using `%UPSTREAM_CLUSTER%` log key, it logs something like
```
outbound|80||podinfo1.blargh.svc.cluster.local
```

which I can parse the namespace from, I'll take this as a workaround. We'll move to `CLUSTER_METADATA(istio:services)` after istio upgrade, thanks @douglas-reid !
