### ISSUE TITLE
Documentation for "policy and telemetry features" outdated?

### ISSUE THREAD

**Issue by yuzhouliu9** [istio/istio#36435]
### Bug Description

The Istio docs for Concepts -> Traffic Management -> Sidecars has the following paragraph:
https://istio.io/latest/docs/concepts/traffic-management/#sidecars

_"You can specify that you want a sidecar configuration to apply to all workloads in a particular namespace, or choose specific workloads using a workloadSelector. For example, the following sidecar configuration configures all services in the bookinfo namespace to only reach services running in the same namespace and the Istio control plane (**currently needed to use Istio’s policy and telemetry features**):"_

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: bookinfo
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

**Do we still need to include the Istio control plane namespace (e.g. istio-system/*) for Istio's policy and telemetry features?**

If I understand correctly, Mixer was used to provide policy and telemetry, but that is deprecated and was moved into the envoy proxy.
From old istio v1.6, Sidecar reference https://istio.io/v1.6/docs/reference/config/networking/sidecar/:
_"For example, add host istio-system/istio-telemetry.istio-system.svc.cluster.local if telemetry is enabled, istio-system/istio-policy.istio-system.svc.cluster.local if policy is enabled, or add istio-system/* to allow all services in the istio-system namespace. **This requirement is temporary and will be removed in a future Istio release.**"_

But in latest docs Sidecar reference, there is no longer mention of need to include istio-system for policy and telemetry.
So I'm wondering if it's still required. If not, then https://istio.io/latest/docs/concepts/traffic-management/#sidecars should be updated.

### Version

```prose
istio.io/latest/docs
```

**Comment by howardjohn** [comment]
It should no longer be required. And we should update the docs.

**Comment by zirain** [comment]
> It should no longer be required. And we should update the docs.

By default, envoy report trace to `zipkin.istio-system`, we should remind end-users in this scenario.

**Comment by howardjohn** [comment]
i think that cluster is part of bootstrap  though. However, any extension
providers will need to be taken into account. Maybe we should do that
automatically though...

**Comment by zirain** [comment]
> 

that would be a trick like `mesh` Gateway in VirtualService, and seems non-const.

**Comment by yuzhouliu9** [comment]
I'm confused.

My original question was:
> Do we still need to include the Istio control plane namespace (e.g. istio-system/*) for Istio's policy and telemetry features?

To which @howardjohn replied:
> It should no longer be required. And we should update the docs.

But the docs update was
https://github.com/istio/istio.io/pull/10587/files#diff-e4e9e2ab753066efb664791ebc4e5014ba9fea0d88f0fbfd324a3f78cb5a3a02R599
> to only reach services running in the same namespace and the Istio control plane (needed by Istio’s egress and telemetry features):

I would have thought that the istio control plane was not needed at all?
