### ISSUE TITLE
Istio document inconsistency between english and chinese locales

### ISSUE THREAD

**Issue by dheerajjoshim** [istio/istio#36430]
### Bug Description

Mixer strategy and Telemetry section under Reference section of the document is missing for the default locale. However `zh` locale has this section.

Is this section missing from the default locale or it is present somewhere else? 

Document with zh locale
<img width="1680" alt="istiozhlocale" src="https://user-images.githubusercontent.com/943733/145165320-cdb24930-a258-4b2d-98a0-2a3004fc18b9.png">

Document with en locale
<img width="1680" alt="istioenlocale" src="https://user-images.githubusercontent.com/943733/145165367-8b6135b4-d924-4a77-9cb9-c19ec7e76c3a.png">

### Version

```prose
$ istioctl version
client version: istio-release-1.11.4
control plane version: istio-release-1.11.4
data plane version: 1.11.4 (7 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected product area

- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by kebe7jun** [comment]
The Chinese documentation is still translated based on version 1.9.3 and may be behind the current version.
I will fix it.
