### ISSUE TITLE
DNS lookup in an init container fails with istio-cni and smart DNS proxying

### ISSUE THREAD

**Issue by rvennam** [istio/istio#36453]
### Bug Description

When using Istio CNI and ISTIO_META_DNS_CAPTURE, my application **init** containers are not able to talk to external endpoints. For example, when my init container tries to curl www.httpbin.org, I get `Could not resolve host: www.httpbin.org`

With ISTIO_META_DNS_CAPTURE turned OFF, it can resolve fine and I would just need to set `excludeOutboundIPRanges` annotation to the IP of httpbin.org to get around the envoy sidecar that isn't running yet.

With ISTIO_META_DNS_CAPTURE turned ON, the dns capture is redirecting the dns lookup in the init container to the sidecar which isn't running yet. 

### Version

```prose
istioctl version
client version: 1.11.4
control plane version: 1.12.1
data plane version: 1.12.1 (2 proxies)

kubectl version --short
Client Version: v1.20.4-dirty
Server Version: v1.21.1+a620f50 (openshift)
```

### Additional Information

[cni-bug-report.tar.gz](https://github.com/istio/istio/files/7685866/cni-bug-report.tar.gz)

**Comment by bianpengyuan** [comment]
This is a tricky one, I don't see an easy way around this. Seems like no easy way to selectively enable DNS capture only for proxy at CNI. At least we will need to add a document note about this limitation.

**Comment by howardjohn** [comment]
Not much we can do here until we fix the underlying issue I think (https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers)

**Comment by nrjpoddar** [comment]
Agree @bianpengyuan. Any workarounds you all can think of? If the init container is started with specific UUID can it bypass traffic redirection?

**Comment by bianpengyuan** [comment]
Yeah indeed update init container user id to 1337 would work around this. We can also document this. Actually this is "better" than the existing work around because this would allow only init container to skip capture. I will add this to the doc.
