### ISSUE TITLE
WasmPlugin: Is this new feature only support the proxy-go sdk?

### ISSUE THREAD

**Issue by leyao-daily** [istio/istio#36451]
I deploy a wasm filter as the rate_limit example based on tinygo and proxy-wasm-go-sdk. It works.
But when I compile the /envoy/example/wasm-cc/envoy_filter_http_wasm_example.cc and use the same dockerfile to build its oci docker image. And deploy it to the sidecar.

But it doesn't work.
Is this new feature only support go wasm?

**Comment by howardjohn** [comment]
It shouldn't matter what SDK it is written in, the end result should be a generic WASM bytecode which Envoy runs. So its likely some other issue.
