### ISSUE TITLE
e2e-suite-rbac-auth ImagePullBackOff when presubmit isn't finished

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3645]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3643/e2e-suite-rbac-auth/869/

```
I0221 08:54:30.035] po/istio-ca-7f657f7646-q7wf5        0/1       ImagePullBackOff   0          4s        10.28.28.64   gke-istio-e2e-rbac-rotat-default-pool-708ea9ff-f0tv
I0221 08:54:30.035] po/istio-ingress-76b9fd8d44-qhjbh   0/1       ImagePullBackOff   0          5s        <none>        gke-istio-e2e-rbac-rotat-default-pool-708ea9ff-fc2r
I0221 08:54:30.035] po/istio-mixer-659dbd68ff-vp9dg     1/3       ImagePullBackOff   0          14s       10.28.26.66   gke-istio-e2e-rbac-rotat-default-pool-708ea9ff-s5bx
I0221 08:54:30.035] po/istio-pilot-67f4fc6b8f-w7qlv     0/2       ImagePullBackOff   0          5s        10.28.24.85   gke-istio-e2e-rbac-rotat-default-pool-708ea9ff-mhxz
```
happened on https://github.com/istio/istio/pull/3643#issuecomment-367257399

any way to declare the dependency in prow so there are no false alarm like this ?

**Comment by cmluciano** [comment]
Any progress here @hklai ?

Would we like to fail fast if we detect that we are in this state?

**Comment by hklai** [comment]
e2e-suite-rbac-auth runs in postsubmit automatically and it only runs after unit tests are done (and with all images created). I believe that dependency is taken care of.

In this case, I suppose e2e-suite-rbac-auth is triggered manually in #3643, as it does not automatically run in presubmit anymore.

AFAICT the job "correctly" failed with some image not found error. The alternative is to not run the job at all, if presubmit has failed, but I am not sure if it is better. /retest" is not exactly an interactive command and one may end up wondering why the job does not run.

**Comment by hklai** [comment]
Yup.
