### ISSUE TITLE
TestQueueCancelSync failed on circleci for a doc PR

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3646]
https://circleci.com/gh/istio/istio/34674
https://github.com/istio/istio/pull/3622

**Comment by GregHanson** [comment]
@jmuk https://github.com/istio/istio/pull/3468 made some changes to the quest_test.go file,  any chance some of these changes could be introducing test inconsistencies?

**Comment by GregHanson** [comment]
Specific unit test in mixer that is failing in mixer/pkg/config/store/queue_test.go

```
=== RUN   TestQueueCancelSync
--- FAIL: TestQueueCancelSync (0.00s)
	queue_test.go:154: Got 10.Handler.ns, Want empty
```

**Comment by jmuk** [comment]
I changed a bit, but it shouldn't change the logic -- basically it's just context -> channel. Does this fail always or is it a flake?

**Comment by ldemailly** [comment]
looks more like a flake but still would be good to not have it break randomly (not rely on time ? or have more margin or a few retries?)

**Comment by jmuk** [comment]
agreed. I wanted to make sure my new thing didn't change something unexpectedly. will look into.
