### ISSUE TITLE
How often is a CSR created when using Chiron?

### ISSUE THREAD

**Issue by wimo7083** [istio/istio#36467]
I'm having a bit of a difficult time understanding the documentation for [Custom CA Integration using Kubernetes CSR](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/).

> When the workloads are deployed, above, they send CSR Requests to Istiod which forwards them to the Kubernetes CA for signing. 

All of these actions would involve the same cluster:
- If multiple deployments use the same serviceaccount, will it issue a CSR for each?
- If a deployment has a replica of more than 1, will it issue a CSR for each replica?
- If a pod is migrated to a different node will it issue a CSR for each action?

Is there a metric for how many CSR have been created which could help expose these answers?

**Comment by howardjohn** [comment]
I believe this would be unique for every pod. Its retriggered once 50% of cert lifetime is passed.
