### ISSUE TITLE
WorkloadEntry accompanied by ServiceEntry giving "STRICT_DNS cluster without endpoints" error

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#36468]
### Bug Description

I have created a  following WorkloadEntry and ServiceEntry
```---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name:  my-app
  namespace: my-namespace
spec:
  serviceAccount: vm-workload
  address:  myapp.example.com
  labels:
    app: myapp

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: my-app
  namespace: my-namespace
spec:
  hosts:
  - myapp.my-namespace.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
    targetPort: 8003
  resolution: DNS
  workloadSelector:
    labels:
      app: myapp
```
After checking pilot logs 
I see 
```"STRICT_DNS cluster without endpoints outbound|443||myapp.my-namespace.svc.cluster.local found while pushing CDS"```

I thought that WorkloadEntry should provide Endpoints.

### Version

```prose
istio 1.11.0
kubernetes 1.19
```

**Comment by bianpengyuan** [comment]
I can reproduce. When creating WE before SE, it won't be selected.

**Comment by Arsen-Uulu** [comment]
@bianpengyuan Thank you for your quick reply, is there any workarounds? 

I just added the ServiceEntry with endpoints and removed WorkloadEntry, I still get the same error.

**Comment by bianpengyuan** [comment]
It works for me if ServiceEntry is created before WorkloadEntry.

**Comment by Arsen-Uulu** [comment]
so workaround is to create ServiceEntry then WorkloadEntry?

**Comment by Arsen-Uulu** [comment]
@bianpengyuan  Thank you

**Comment by Arsen-Uulu** [comment]
Workaround didn't work for me

**Comment by bianpengyuan** [comment]
> Workaround didn't work for me

@Arsen-Uulu did you create them together by one kube create? That might not work. What works for me is to create the ServiceEntry, wait a bit, then create the WorkloadEntry.

**Comment by Arsen-Uulu** [comment]
@bianpengyuan Thanks it works. 

is there a reason I don't see a cluster for my workloadEntry when I use istioctl proxy-config cluster, but I see route for it? 
and route is configured to take me to outbound|myworkloadentry|443.
