### ISSUE TITLE
Failure to patch WebhookConfigurations results in a loop that takes down ETCD...

### ISSUE THREAD

**Issue by diranged** [istio/istio#36478]
### Bug Description

We recently were doing some work to swap out our Istio Root CAs on ~9 clusters. Out of 9 clusters, we seem to have run into a situation on ~5 of them where the `istiod` pods got into a nasty loop that hammered our Kubernetes API services and ultimately took down ETCD.  On one cluster in particular it took the entire cluster down for ~2hr until Amazon intervened and was able to bring the systems back up.

When we looked into the logs, we found our `istiod` pods emitting hundreds of thousands of lines like this:

```
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.699128Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail,resourceVersion=340044615)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.701195Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod (failurePolicy=Fail,resourceVersion=340044616)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.735744Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail,resourceVersion=340044618)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.739005Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod (failurePolicy=Fail,resourceVersion=340044619)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.762429Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail,resourceVersion=340044622)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.765209Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail,resourceVersion=340044621)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.783321Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod (failurePolicy=Fail,resourceVersion=340044623)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.821306Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail,resourceVersion=340044626)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.821748Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail,resourceVersion=340044625)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.854003Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod (failurePolicy=Fail,resourceVersion=340044628)"}
2021-12-08 16:18:49	
{"level":"info","time":"2021-12-09T00:18:49.857455Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod-istio-system (failurePolicy=Fail,resourceVersion=340044629)"}
```

with lines like this intermixed in:
```
{"level":"error","time":"2021-12-09T14:04:30.946561Z","scope":"validationController","msg":"Failed to update validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail, resourceVersion=285059577): Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"istio-validator-istio-system\": the object has been modified; please apply your changes to the latest version and try again"}
```

Once we discovered this root cause on one cluster, we scanned our other clusters and based on log-volume alone we have found a series of log patterns like this:

![image](https://user-images.githubusercontent.com/768067/145688088-a2f6d279-fec6-429b-b771-e001b1d52d77.png)
![image](https://user-images.githubusercontent.com/768067/145688095-39918829-5107-44a1-aaed-eb22baf4c4b7.png)
![image](https://user-images.githubusercontent.com/768067/145688106-18ac4d70-3727-4dd9-a4db-2936b35f4d6b.png)

It does seem that killing the `istiod` pods and restarting them resolves the issue.. but I am wondering if the fix in 
 https://github.com/istio/istio/pull/35243 is either not in Istio 1.12 ... or somehow is not complete and is not totally resolving the issue?

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.12.0
data plane version: 1.12.0 (35 proxies)
$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.21.2-eks-0389ca3
```

### Additional Information

I have collected a bug-report - but i cannot share it publicly. I would be willing to share it privately with the development team though. Please reach out and I can do that.

**Comment by howardjohn** [comment]
So I think the backoff might only be for failures - in your case it is successfully patching. But then something triggers it to patch again, which it does so immediately.

I assume that trigger is another instance patching a different config. The expectation is that each instance should have the same desired state.

Is it possible some istiod instances have a different view of the desired CA cert to patch which leads to this? I recall some PRs to ensure the webhook patch gets updated with can cert changes but not sure which version it is in

**Comment by hzxuzhonghu** [comment]
We should make use of leader election to eliminate such erros `Failed to update validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail, resourceVersion=285059577): Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"istio-validator-istio-system\": the object has been modified; please apply your changes to the latest version and try again"}`

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/35243 - This is the relevant PR that introduced exponential backoff to cover for scenarios where muliple Istiod instances are competing with each other with inconsistent certs. But in your case it seems to be successfully patching - Did you check what is triggering this change?

Also as mentioned in the other PR - leader election is not an option here because of revisions.

**Comment by diranged** [comment]
@ramaraochavali I dug through the logs a bit - but never found the cause for the updating. What I thought was particularly interesting was that it was the same revisions of the istiod replicaset that were running.. its not like we were running two istiod releases or something.

Given that this happened when we were switching the CA bundles around - it seems clear that was the cause .. but I don’t know how we got into that state.

I am surprised leader-election is not used here. Was that just a simple oversight, or is there a technical reason why that can’t be used?

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/35243#issuecomment-921943208 - see comments from below on why leader election was not implemented. But probably we can add leader election per revision @howardjohn @Monkeyanator WDYT?

**Comment by diranged** [comment]
While you work on implementing control in the pilot process - I was thinking that another way to protect against this was with a FlowSchema. What do you think? Could the Operator install FlowSchemas as well to make sure that that Istio never overloads the API servers?

**Comment by diranged** [comment]
> [#35243 (comment)](https://github.com/istio/istio/pull/35243#issuecomment-921943208) - see comments from below on why leader election was not implemented. But probably we can add leader election per revision @howardjohn @Monkeyanator WDYT?

That was my first thought too - leader election per revision seems reasonable.

**Comment by Monkeyanator** [comment]
So the issue seems like replica A sees one CA bundle, replica B sees another. When A updates the mutating webhook, B is notified, notices the CA bundle doesn't match its own, patches the webhook, then A is notified, and so on so forth...

Having a  form of leader election where a single replica from each revision wins makes sense. Had an attempt to do that here, some more discussion included: https://github.com/istio/istio/pull/35281. To be honest I'm not super clear on why we didn't go forward with it

**Comment by bianpengyuan** [comment]
@diranged I assume you are using plugin certs? Root cause is that one of the replicas restarts and loads the new certs, which causes the different view. This should be avoidable if you set `AUTO_RELOAD_PLUGIN_CERTS` to true. It's available at 1.12: https://github.com/istio/istio/blob/release-1.12/pilot/pkg/features/pilot.go#L547

**Comment by diranged** [comment]
> 



> @diranged I assume you are using plugin certs? Root cause is that one of the replicas restarts and loads the new certs, which causes the different view. This should be avoidable if you set `AUTO_RELOAD_PLUGIN_CERTS` to true. It's available at 1.12: https://github.com/istio/istio/blob/release-1.12/pilot/pkg/features/pilot.go#L547

@bianpengyuan We are actually not using that setting..

**Comment by bianpengyuan** [comment]
@diranged Yeah this should be preventable by turning this feature on.

**Comment by Minh-Ng** [comment]
> AUTO_RELOAD_PLUGIN_CERTS

@bianpengyuan actually this env var doesn't affect ROOTCA, so original problem from swapping out ROOTCA wouldn't have been solved with this env var on (this issue still happens on 1.18.x btw). that being said looks like https://github.com/istio/istio/pull/47063 just landed and should help out on this note.
