### ISSUE TITLE
Support cluster active health check

### ISSUE THREAD

**Issue by ethanhanjiahao** [istio/istio#36477]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We use envoy as router gateway，but istio  api does not support active health check configuration.
Is there any other way  to config active health check for upstream cluster.  
Envoy upstream health check is https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#envoy-v3-api-msg-config-core-v3-healthcheck-httphealthcheck

**Describe alternatives you've considered**
Is there any other way  to config active health check for upstream cluster.  

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X  ] Virtual Machine
[ ] Multi Control Plane

**Comment by bianpengyuan** [comment]
This is tracked at https://github.com/istio/istio/issues/10537 and you can find a EnvoyFilter example at https://github.com/istio/istio/issues/10537#issuecomment-555548652. You can track that issue instead and probably add your use case there if it is different from the ones mentioned.

**Comment by bianpengyuan** [comment]
Close as a dup for #10537 thanks!
