### ISSUE TITLE
TestEndpointsDeduping flake (regerssion)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36503]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1470570742142734336

Can reproduce locally

**Comment by howardjohn** [comment]
Regression from 1.12, marking as release blocker

**Comment by howardjohn** [comment]
Root cause is fe69479b63ac4e27c8a55955e2f7943309117320, found by git bisect:

```
good=6aa1f8a274
bad=55d72c192c

cat <<'EOF' > /tmp/bisect.sh
go test -c -race ./pilot/pkg/serviceregistry -o flaker.test || exit 1
p=`pwd`
cd pilot/pkg/serviceregistry
stress -max-runs 1000 -p 64 $p/flaker.test -test.v -test.run ^TestEndpointsDeduping$
EOF

chmod +x /tmp/bisect.sh
git bisect start
git bisect good $good
git bisect bad $bad
git bisect run /tmp/bisect.sh
```

**Comment by hzxuzhonghu** [comment]
Sorry i missed it. It does not occur recently https://testgrid.k8s.io/istio_istio_postsubmit#unit-tests_istio_postsubmit

**Comment by howardjohn** [comment]
Likely just because of low load during holidays? I can reproduce easily with https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes

**Comment by hzxuzhonghu** [comment]
Good, will investigate tomorrow

**Comment by hzxuzhonghu** [comment]
serviceregistry_test.go:1003: retry.UntilSuccessOrFail: timeout while waiting after 144 attempts, 0/2 successes (last error: wanted [1.2.3.4:80 2.3.4.5:80] got [1.2.3.5:80 2.3.4.5:80]. All endpoints: map[outbound|80||service.namespace.svc.cluster.local:[1.2.3.5:80 2.3.4.5:80] outbound|90||service.namespace.svc.cluster.local:[]])
 
really weird, i got `1.2.3.5:80`

**Comment by hzxuzhonghu** [comment]
Figured out the cause, ConfigGenTest runs the registries, but some registry, here it is kube-controller has been run before, so it runs twice.

```
func (f *ConfigGenTest) Run() {
	go f.Registry.Run(f.stop)
```

**Comment by howardjohn** [comment]
I think Steven has a PR for that

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/batch/unit-tests_istio/1526230213174759424 still failing?

**Comment by howardjohn** [comment]
1.14: 9611 runs so far, 0 failures (100.00% pass rate). 6.520596888s avg, 17.557555219s max, 3.423240211s min
master: 2883 runs so far, 19 failures (99.35% pass rate). 6.024354286s avg, 10.316067891s max, 3.313710611s min

**Comment by howardjohn** [comment]
Bisect blames b51fa21636a72f9bf023b53b14231ebd0dcb1f7b
