### ISSUE TITLE
Implement EnvoyFileAccessLogProvider.logFormat

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36513]
https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyFileAccessLogProvider

Currently this is merged in the API but not implemented in Istiod

**Comment by howardjohn** [comment]
@zirain you sent some great PRs in this area recently if you are interested in working on this and/or https://github.com/istio/istio/issues/36514

**Comment by zirain** [comment]
@howardjohn ok, I will take a look at this.

**Comment by zirain** [comment]
@howardjohn are you free to reviews https://github.com/istio/istio/pull/36604?
