### ISSUE TITLE
Istio unable to handle special characters in query params

### ISSUE THREAD

**Issue by kutsav** [istio/istio#36511]
### Bug Description

While receiving special characters in query parameters, istio throws 400 "Bad Request" error and the request never reached backend. 
For example, if I do something like: curl https://www.example.com/userInfo?name=utsavña, request fails with HTTP 400.

Any pointers on how i can bypass this?

### Version

```prose
Istio version: 1.8.1
```

**Comment by howardjohn** [comment]
I can confirm this still occurs on master as well. Only for HTTP 1.1. This is due to Envoy impementation, which is tracked here: https://github.com/envoyproxy/envoy/issues/12073
