### ISSUE TITLE
add env to enable preStop which ensure sidecar exit after app

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#36517]
we already add env `holdApplicationUntilProxyStarts` to ensure sidecar start before app. shall we add another env to ensure sidecar exit after app?
something like :

```
          "lifecycle": {
            "preStop": {
              "exec": {
                "command": ["/bin/sh", "-c", "while [ $(netstat -plunt | grep tcp | egrep -v 'envoy|pilot-agent'' | wc -l | xargs) -ne 0 ]; do sleep 1; done"]
              },
            },
          },
```

is the preStop script applicable for every app? or some app need custom preStop?

**Comment by bianpengyuan** [comment]
As far as I know, this setting takes advantage of an implementation detail (container start in order), which does not apply to container stop: https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74

**Comment by zhongfox** [comment]
@bianpengyuan seems this does't depend on k8s containers stop order. yes k8s send stop signal to containers in parallel.

from k8s doc:
「PreStop hooks are not executed asynchronously from the signal to stop the Container; the hook must complete its execution before the TERM signal can be sent. If a PreStop hook hangs during execution, the Pod's phase will be Terminating and remain there until the Pod is killed after its terminationGracePeriodSeconds expires」

so we can use PreStop of sidecar to wait user container stop first (the above script check if there is any other listening ports beside envoy and pilot-agent ).

**Comment by howardjohn** [comment]
There is no need to us preStop for this, the agent can do any logic it needs directly in the container. There was already a recent PR in master to do this natively

**Comment by zhongfox** [comment]
@howardjohn cool, looking forward, can you please send me that PR? thanks.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/35059
