### ISSUE TITLE
when add dimensions in istio-control/istio-discovery helm chart, some errors occurred while getting the prometheus metrics

### ISSUE THREAD

**Issue by gsgs-libin** [istio/istio#36520]
version: 1.11.4
I deploy istio with helm. when i add dimensions in file(istio-1.11.4/manifests/charts/istio-control/istio-discovery/values.yaml):

```shell
telemetry:
  enabled: true
  v2:
    # For Null VM case now.
    # This also enables metadata exchange.
    enabled: true
    metadataExchange:
      # Indicates whether to enable WebAssembly runtime for metadata exchange filter.
      wasmEnabled: false
    # Indicate if prometheus stats filter is enabled or not
    prometheus:
      enabled: true
      # Indicates whether to enable WebAssembly runtime for stats filter.
      wasmEnabled: false
      # overrides stats EnvoyFilter configuration.
      configOverride:
        gateway:
          disable_host_header_fallback: true
          metrics:
            - dimensions:
                request_host: request.host
                request_method: request.method
                source_cluster: node.metadata['CLUSTER_ID']
              tags_to_remove:
                - connection_security_policy
                - destination_app
                - destination_canonical_revision
                - destination_canonical_service
                - destination_principal
                - destination_service_name
                - destination_service_namespace
                - destination_version
                - response_flags
                - source_app
                - source_canonical_revision
                - source_canonical_service
                - source_principal
                - source_version
```

1. when add "request_method: request.method" , the metrics in prometheus will be three "istio_requests_total" like this.
![image](https://user-images.githubusercontent.com/22513159/146173603-79290f71-e43d-446d-9029-b7117eb28abe.png)

but istio_requests_total has no method field.

2. when remove "request_method: request.method", the metrics in prometheus will be only one "istio_requests_total"

**Comment by bianpengyuan** [comment]
You will need to add extra tags to the configuration as well, see step 2 here https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics. Note you will need to restart your proxy in order to make extra tag to work.

**Comment by gsgs-libin** [comment]
> You will need to add extra tags to the configuration as well, see step 2 here https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics. Note you will need to restart your proxy in order to make extra tag to work.

thank you, it takes effect. i add annotations "sidecar.istio.io/extraStatTags: request_method" in gateway-ingress .
But there is one more question，I initially added it this way, but it didn't work。
```shell
- name: ISTIO_METAJSON_ANNOTATIONS
       value: |
          {"sidecar.istio.io/extraStatTags":"request_method"}
```

**Comment by bianpengyuan** [comment]
That is an undocumented approach, which I wouldn't be surprised if no longer working... It would be better to follow the doc, thanks!

**Comment by bianpengyuan** [comment]
I am going to close this issue since the question has been answered and solution works. Thanks!
