### ISSUE TITLE
sidecar injector template has no separate resources for init container

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#36522]
### Bug Description

`istio-sidecar-injector` configmap values has separate section for `proxy_init` image and resources

```
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "statusPort": 15020,
          "tracer": "zipkin"
        },
        "proxy_init": {
          "image": "proxyv2",
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "10m",
              "memory": "10Mi"
            }
          }
        },
```

template uses `proxy_init.proxy` which is correct, check `.Values.global.proxy_init.image` in below snippet

```
          initContainers:
          {{ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) `NONE` }}
          {{ if .Values.istio_cni.enabled -}}
          - name: istio-validation
          {{ else -}}
          - name: istio-init
          {{ end -}}
          {{- if contains "/" (annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy_init.image) }}
            image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy_init.image }}"
          {{- else }}
            image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
          {{- end }}
```

but the resources arent used from `proxy_init` block, instead it come from  `proxy.resources`, see `{{- if .Values.global.proxy.resources }}`, instead it should be `{{- if .Values.global.proxy_init.resources }}`
 
```
        resources:
        {{- if or (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPULimit`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemoryLimit`) }}
          {{- if or (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) }}
            requests:
              {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -}}
              cpu: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` }}"
              {{ end }}
              {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) -}}
              memory: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` }}"
              {{ end }}
          {{- end }}
          {{- if or (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPULimit`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemoryLimit`) }}
            limits:
              {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPULimit`) -}}
              cpu: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPULimit` }}"
              {{ end }}
              {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemoryLimit`) -}}
              memory: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemoryLimit` }}"
              {{ end }}
          {{- end }}
        {{- else }}
          {{- if .Values.global.proxy.resources }}
            {{ toYaml .Values.global.proxy.resources | indent 6 }}
          {{- end }}
        {{- end }}
```

issue: setting mesh level resources for istio-proxy sidecar also applies to init container, init container doesnt use this much of resources but requests way higher resources to k8, so k8 need to find worker node having enough space that satisfies "istio-init + istio-proxy + app" resources.

```
  values:
      proxy:
        resources:
          limits:
            cpu: "2000m"
            memory: "1200Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
```

### Version

```prose
istio `1.11.4` version
```

**Comment by dddddai** [comment]
> init container doesnt use this much of resources but requests way higher resources to k8, so k8 need to find worker node having enough space that satisfies "istio-init + istio-proxy + app" resources.

Not really, please refer to [k8s doc](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources)
The effective request/limit depends on `max(istio-init, sum(istio-proxy,app))`, so it doesn't consume more resources actually

**Comment by linsun** [comment]
Hi @infa-ddeore - please let us know if you agree with @dddddai 's assessment above. I believe it is easier for users when we don't expose a separate config for init container (less configurations!).

**Comment by howardjohn** [comment]
> The effective request/limit depends on max(istio-init, sum(istio-proxy,app)), so it doesn't consume more resources actually

+1, this change was very intentional based on this. There is no reason to artificially restrict istio-init resources since we know it will always be lower than `sum(istio-proxy,app)`. This had a huge performance improvement in init container time when we made this change.,

**Comment by infa-ddeore** [comment]
thanks for the clarification, earlier i thought effective request/limit is `sum(istio-init,istio-proxy,app)`
