### ISSUE TITLE
Base img  for istio-proxy upgrade from ubuntu 18.04 to 22.04, istio-init failed with sidecar injected pod

### ISSUE THREAD

**Issue by mayyyyying** [istio/istio#36569]
Hi there,

I am upgrading base img for istio from ubuntu 18.04 to 22.04 recently, And there is an issue with the sidecar injected pod when upgraded to ubuntu 22.04 as base img, listed as below, anyone has any similar experience before?  any suggestion would be really helpful. 

Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=true
ISTIO_META_DNS_CONNTRACK_ZONE=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=true
DNS_SERVERS=[10.4.0.10],[]

Writing following contents to rules file:  /tmp/iptables-rules-1639738197984108017.txt903669333
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 53 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -p tcp --dport 53 -d 10.4.0.10/32 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j RETURN
-A OUTPUT -p udp --dport 53 -m owner --gid-owner 1337 -j RETURN
-A OUTPUT -p udp --dport 53 -d 10.4.0.10/32 -j REDIRECT --to-port 15053
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1639738197984108017.txt903669333
iptables-restore v1.8.7 (nf_tables):
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: RULE_APPEND failed (Invalid argument): rule in chain PREROUTING
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file or directory): table nat
line 29: TABLE_ADD failed (No such file
iptables-save
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
panic: exit status 4

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x29bd450, 0x1a9a486, 0x10, 0xc0000e5080, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:42 +0x9c
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000939d78, 0x1, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:780 +0x386
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000939d78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:787 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000939d78)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:567 +0x23e5
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x2975b80, 0xc000674c00, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:63 +0x165
github.com/spf13/cobra.(*Command).execute(0x2975b80, 0xc000674b00, 0x10, 0x10, 0x2975b80, 0xc000674b00)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2975e00, 0x41af01, 0x0, 0x0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:338 +0x31

**Comment by howardjohn** [comment]
> I am upgrading base img for istio from ubuntu 18.04 to 22.04 recently

Is this a VM? Or a custom docker image build? Seems like you are using nftables instead of iptables (in recent ubuntu `iptables` is an alias for nftables)

**Comment by howardjohn** [comment]
```
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

is probably what you want btw

**Comment by mayyyyying** [comment]
It is a custom docker image build. and the above two command did the job. Thanks a lot.

**Comment by howardjohn** [comment]
Great, closing this as it is resolved and does not impact our releases
