### ISSUE TITLE
net.ipv4.ip_unprivileged_port_start sysctl problem

### ISSUE THREAD

**Issue by nadihagh** [istio/istio#36560]
hi
I installed istio with helm chart
when I install gateway chart I get this and stuck on ContainerCreating:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.ipv4.ip_unprivileged_port_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown

I tried running this command on a node in which gateway initialized on:
sysctl net.ipv4.ip_unprivileged_port_start=80
again I got this:
sysctl: cannot stat /proc/sys/net/ipv4/ip_unprivileged_port_start: No such file or directory

kubernetes version: v1.22.4
all of my nodes are centos 7

**Comment by howardjohn** [comment]
Are your nodes running 1.22 as well? or just the api server and nodes are older versions?

**Comment by howardjohn** [comment]
Per https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls I would expect this to be ok on 1.22.

**Comment by nadihagh** [comment]
I updated kernel version to 5.4 and this solved the issue
my previous kernel version was 3.10
