### ISSUE TITLE
WasmPlugin: How to add insecure-registry to fetch the wasm binary

### ISSUE THREAD

**Issue by leyao-daily** [istio/istio#36571]
In my WasmPlugin, my oci url is point to an address which need to be added as a insecure-registry. And when I add it to host docker, I can pull the image, But when I apply this WasmPlugin CR, the istio-proxy will throw a error:
`x509: certificate signed by unknown authority`

Is there anything wrong with my configuration?

**Comment by bianpengyuan** [comment]
Can you provide a bit more detail about your config here? Hope to take a look at what exactly is the oci uri you are using.

**Comment by leyao-daily** [comment]
@bianpengyuan  url: oci://registry.fi.intel.com/leyao/envoy-modsecurity-wasm-plugin:0.1.0

**Comment by leyao-daily** [comment]
And does WASMPLUGIN work for istio-system/istio-ingressgateway?

**Comment by bianpengyuan** [comment]
We will need an option to agent to skip verify insecure, similar to https://github.com/google/go-containerregistry/blob/main/cmd/crane/cmd/root.go#L68

Yes, see example at https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/

**Comment by poussa** [comment]
Another way is to teach the agent the CA who signed the registry certificate. That is, somehow let envoy know that it trust the signing CA. Using insecure option is just saying I don't care who signed it.

**Comment by bianpengyuan** [comment]
@poussa I did not try, but would it just work if you mount the root cert to `/etc/ssl/certs` at Istio proxy?

**Comment by leyao-daily** [comment]
Will this be developed as a new feature in the future to accepte insecure repo?

**Comment by bianpengyuan** [comment]
Yeah I will add an env variable to the istio agent to allow pulling from insecure repo.

**Comment by hzxuzhonghu** [comment]
It looks kubelet does not check the ca, should we allow insecure by default?

**Comment by bianpengyuan** [comment]
> It looks kubelet does not check the ca, should we allow insecure by default?

@hzxuzhonghu  Are you sure? That seems unlikely to me... And is that is not clear, we are actually talking about pull with TLS but private CA, not pull with plain text.

**Comment by hzxuzhonghu** [comment]
@bianpengyuan I am wrong, i looked at the code of kubelet, actually it calls the `CRI`. So should look at CRI implementation. And i go through docker/moby repo, looks MTLS by default.

**Comment by bryanwux** [comment]
@bianpengyuan  Are you working on this right now?

**Comment by bianpengyuan** [comment]
> @bianpengyuan Are you working on this right now?

Nope, please feel free to take over. Thanks!
