### ISSUE TITLE
Application Init container "excludeOutboundPorts" not working in istio 1.11 version

### ISSUE THREAD

**Issue by vijay-dcrust** [istio/istio#36575]
### Bug Description

Application init container is losing all the traffic even though I have configured excludeOutboundPorts in my IstioOperator spec. This was working with 1.10.5 but not working with 1.11.1 or 1.11.5.

The init container wont be able to communicate with other services and hence pod cant be started.

I am using istio cni
I am using istiooperator to install the IstioOperator spec.

Anyone facing the same issue?

### Version

```prose
Client Version: v1.22.2
Server Version: v1.20.7-eks-d88609
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by howardjohn** [comment]
Can you check the logs from the CNI node and see what iptables rules are applied?

**Comment by bianpengyuan** [comment]
Also is there any chance that the init container calls other services with hostname AND you enabled DNS proxy? https://github.com/istio/istio/issues/36453

**Comment by vijay-dcrust** [comment]
Hi @bianpengyuan Yes it was due to DNS proxy issue. I tried changing the user ID as a workaround and was able to resolve.
Thanks for pointing to the cause.

But I am wondering why the dns is working in 1.10 and not in 1.11.

**Comment by bianpengyuan** [comment]
> But I am wondering why the dns is working in 1.10 and not in 1.11.

1.10 CNI does not do anything actually when you turned on DNS proxy, i.e. the dns query is not intercepted but go directly to dns server. In 1.11, CNI adds support for DNS proxy and this issue surfaces.

**Comment by bianpengyuan** [comment]
Close this since this is a dup of #36453. thanks!
