### ISSUE TITLE
istio ingress gateway nodeport problem

### ISSUE THREAD

**Issue by nadihagh** [istio/istio#36574]
unfortunately we cannot use Loadbalancer type in our cluster, we have to use NodePort,
we have installed ingress gateway with helm chart but the port specified in NodePort(http2:80►31031 - https:443►31032) is not accessible via some of the cluster nodes while NodePort(status-port:15021►31637) is accessible via all nodes,
there is no active firewall on the nodes

kubernetes cluster version: 1.22.4
istio version: 1.12.1

**Comment by howardjohn** [comment]
The port 80 vs port 15021 should not behave any differently assuming you have config's setup for port 80. Can you send traffic to all of the istio-ingress pod IPs directly?

**Comment by nadihagh** [comment]
unfortunately I can't. Because I'm sending traffic from firewall directly. I need to have static IP and port to route to.

**Comment by nadihagh** [comment]
found it,
if the name of service is other than istio-ingressgateway it won't work,
just reinstalled with that name it worked
there was nothing to do with NodePort or any other thing

**Comment by Sovenique** [comment]
Same happens for 1.17.3 istio/ingress, any updates on this?
