### ISSUE TITLE
Create e2e tests for the multi-cluster scenario  

### ISSUE THREAD

**Issue by john-a-joyce** [istio/istio#3657]
https://github.com/istio/istio/pull/2880 introduced the ability for Istio to connect to multiple Kubernetes clusters to get service registry information.   That PR did not add any e2e test cases for the scenario.   This issue to track the addition of e2e tests for that scenario.

**Comment by sdake** [comment]
Create multicluster YAMLs for functional automated testing: https://github.com/istio/istio/pull/4869

**Comment by john-a-joyce** [comment]
This issue was resolved by a series of PRs.  The last one being:  https://github.com/istio/istio/pull/5503
Also includes:  https://github.com/istio/istio/pull/5099, https://github.com/istio/istio/pull/4815
