### ISSUE TITLE
Does istio timeout response support modification?

### ISSUE THREAD

**Issue by Yinlia0** [istio/istio#36587]
I added a timeout in the virtual service, and I found that the status code in response to my client was 504
The page is returned as upstream request timeout. Can I change the returned content or status code. Does istio support it?
Turned over the official website and did not find the relevant configuration
Thanks for help

istio version ： 1.12.1

**Comment by howardjohn** [comment]
A custom response is not currently supported

**Comment by Yinlia0** [comment]
> 当前不支持自定义响应

Thanks for your answer
I saw that the response header can be modified through the envoy filter
Are there any plans to add related programs in the future?
