### ISSUE TITLE
TestQuotaCache failed on circleci for an unrelated change

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#3660]
flaky unit test in mixer/test/client/quota_cache/quota_cache_test.go

```
--- FAIL: TestQuotaCache (3.10s)
	setup.go:253: Stats http_mixer_filter.total_remote_check_calls does not match. Expected vs Actual: 2 vs 3
FAIL
FAIL	istio.io/istio/mixer/test/client/quota_cache	3.111s
```

https://circleci.com/gh/istio/istio/35235?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by GregHanson** [comment]
cc @mandarjog

**Comment by douglas-reid** [comment]
@JimmyCYJ can you take a look at this failure ?

**Comment by JimmyCYJ** [comment]
@douglas-reid No problem. Thanks for letting me know.
