### ISSUE TITLE
Support jaeger in agent mode?

### ISSUE THREAD

**Issue by ErikXu** [istio/istio#36603]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I wonder whether istio can integrate with jaeger using daemonset or sidecar agents. There is lacking introduction in documentation. Thanks!

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
@ErikXu can you share more details?

**Comment by ErikXu** [comment]
@zirain As I know jaeger provides agent or agentless pattern to receive traces.
Jaeger recommends the client sending traces to agent insead of sending to collector directly.
https://www.jaegertracing.io/docs/1.29/architecture/#components

I might send traces to agent by setting `--set values.meshConfig.defaultConfig.tracing.zipkin.address=localhost:5778` and deploying agents as sidecar. But the resource usage might be too large.

I want to deploy the agent as daemonset,  while I don't know how to set the `zipkin address` to make istio to send traces to node IP + port

**Comment by bianpengyuan** [comment]
You can set `$(HOST_IP):5778` as zipkin address. Istio will automatically convert it to the actual host IP.

**Comment by ErikXu** [comment]
Cool, I will try and feed it back ASAP.

**Comment by ErikXu** [comment]
I've tried and found there is another problem. The jaeger agent only supports UDP protocol. I know it's mainly jaeger's problem, but is it possible to let istio to send the traces using UDP?

**Comment by bianpengyuan** [comment]
I guess no, since envoy only treat jaeger as a zipkin compatible backend, and I don't think there is a way to configure zipkin tracer at envoy to use UDP? https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/zipkin.proto

**Comment by ErikXu** [comment]
Ok, thanks all the same!
