### ISSUE TITLE
Add concurrency configuration to driver.Envoy

### ISSUE THREAD

**Issue by b-irwin** [istio/istio#36601]
**Describe the feature request**
My team would like to use the envoye2e/driver testing framework to confirm that concurrent HTTP Requests function as properly. This is currently not possible as driver.Envoy hard-codes the argument ["--concurrency", "1"]. It would be very helpful if driver.Envoy had a Concurrency field, which assumes concurrency of 1 when not set, and uses the assigned concurrency value when greater than 0.

**Describe alternatives you've considered**
There is currently no simple work around for this. My team forked driver.Envoy to a local copy so we could change the hard-coded value.
One reasonable alternative implementation is to remove the --concurrency flag. Then developers can control how many threads envoy utilizes by changing their docker configuration. But, I think being explicit about it in the interface is preferable.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
In production, envoy will generally be run with a much higher concurrency value than 1 (often the default). We generally prefer to write tests that are as close to a production environment as reasonble.

**Comment by bianpengyuan** [comment]
Feel free to make a PR to make that configurable.

**Comment by zirain** [comment]
https://github.com/istio/proxy/pull/3638

**Comment by b-irwin** [comment]
https://github.com/istio/proxy/pull/3648
