### ISSUE TITLE
How does Istio proxy routing works?

### ISSUE THREAD

**Issue by VitaliiDobrovolskyi** [istio/istio#36629]
I'm trying to understand, how does Istio proxy handle the incoming and outgoing traffic, where the Istio proxy terminates mTLS (on which stage), on which port? Why does port 15020 (merged metrics) available with HTTP outside the mesh mTLS (strict) and not available inside mesh but the other ports (15021, 15090) are available?

Versio: Istio-1.12.0

I investigated some parts, but still no answer. Jimmysong drew a good traffic routing scheme, here is the link [https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210818.png](url). But it seems to not work like it drawn by Jimmysong.

It should intercept and redirect all unknown traffic on port 15006 (except ports 22, 15008, 15020, 15021, 15090), but I don't see anything.
-P PREROUTING ACCEPT -c 2386 143232
-P INPUT ACCEPT -c 2387 143292
-P OUTPUT ACCEPT -c 11424 1120628
-P POSTROUTING ACCEPT -c 11846 1145948
-N ISTIO_INBOUND
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-N ISTIO_REDIRECT
-A PREROUTING -p tcp -c 2384 143040 -j ISTIO_INBOUND
-A OUTPUT -p tcp -c 988 59280 -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -c 0 0 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -c 1 60 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -c 0 0 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -c 2380 142800 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -c 2 120 -j RETURN
-A ISTIO_INBOUND -p tcp -c 1 60 -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -c 1 60 -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -c 58 3480 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -c 0 0 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -c 0 0 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -c 508 30480 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -c 0 0 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -c 0 0 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -c 0 0 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -c 0 0 -j RETURN
-A ISTIO_OUTPUT -c 422 25320 -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -c 422 25320 -j REDIRECT --to-ports 15001

I managed to identify only outgoing traffic from the application container to another application container. But what next?
-A ISTIO_OUTPUT -c **422 25320** -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -c **422 25320** -j REDIRECT --to-ports 15001

I see traffic only inside INPUT and OUTPUT chains
Chain INPUT (policy ACCEPT 24057 packets, 48M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 22547 packets, 68M bytes)
 pkts bytes target     prot opt in     out     source               destination

I didn't find the information in the documentation it is totally unclear. Now it looks like - traffic came and then it is a "black magic".

I would like to know the flow of the traffic. Could you please provide this information?

**Comment by zirain** [comment]
here is  [Ports used by Istio](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio)

**Comment by VitaliiDobrovolskyi** [comment]
> here is [Ports used by Istio](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio)

Thanks! Of course I read this, but ports description doesn't  explain routing inside the envoyproxy container. At what routing stage mTLS appeared? At what routing stage mTLS terminated? How does the external traffic routed?

**Comment by zirain** [comment]
> > here is [Ports used by Istio](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio)
> 
> Thanks! Of course I read this, but ports description doesn't explain routing inside the envoyproxy container. At what routing stage mTLS appeared? At what routing stage mTLS terminated? How does the external traffic routed?

maybe this's what you need https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/#before-you-begin

**Comment by VitaliiDobrovolskyi** [comment]
Thank you @zirain. Could you please describe this scheme? https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210818.png

In addition, could you explain why I'm not catching the traffic on the iptables rule below?
-A ISTIO_IN_REDIRECT -p tcp -c **1 60** -j REDIRECT --to-ports 15006

**Comment by VitaliiDobrovolskyi** [comment]
At least, I would like to get confirmation if this routing scheme is correct https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210818.png

**Comment by zirain** [comment]
> At least, I would like to get confirmation if this routing scheme is correct https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210818.png

the link is broken, can you describe your question with more detail, it's too board for me.

**Comment by VitaliiDobrovolskyi** [comment]
<img width="1579" alt="istio-proxy-jimmysong" src="https://user-images.githubusercontent.com/73239726/148055196-a63e1b77-42f7-4b46-a07a-8f1e1a19af61.png">

**Comment by VitaliiDobrovolskyi** [comment]
@zirain can you see the scheme?

**Comment by zirain** [comment]
> @zirain can you see the scheme?

refer to 
![image](https://user-images.githubusercontent.com/4354057/148058065-9e1e0c02-af8c-4f79-ad6c-057dbede0b48.png)

I think it's not a good idea to put that pic here

**Comment by VitaliiDobrovolskyi** [comment]
Here's the article link https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/
Maybe it would be helpful.
