### ISSUE TITLE
Unable to remove server header response

### ISSUE THREAD

**Issue by dbali07** [istio/istio#36626]
### Bug Description

Hi all,

I am trying to remove or hide the “istio-envoy” from the response header but what I've tried so far doesn't seem to be having any results.

——> This config (and many more - some also from this thread https://github.com/istio/istio/issues/13861 ) returns errors:

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dgp-headerstrip-server
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          server_header_transformation: PASS_THROUGH
 
When I apply the newly created file, the errors are of this type: 

I1223 18:03:32.347587   33672 request.go:665] Waited for 1.198594007s due to client-side throttling, not priority and fairness, request: GET:https://026CA8B82C146D1315E40DD5AF108640.gr7.eu-central-1.eks.amazonaws.com/apis/kubeflow.org/v1alpha1?timeout=32s
Error from server: error when creating "remove-server-header.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: can't unmarshal Any nested proto *v2.HttpConnectionManager: unknown field "server_header_transformation" in v2.HttpConnectionManager

(same thing for v3)

——> This config, worked:

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hcm-tweaks
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          xff_num_trusted_hops: 5
          max_request_headers_kb: 90

Without errors when I run kubectl apply:

 kubectl apply -f remove-server-header.yaml
envoyfilter.networking.istio.io/hcm-tweaks created

but still returns server: Istio-envoy

Any ideas/thoughts?

Thanks in advance,
D.

### Version

```prose
No istioctl version. Istio installation is older (1.3)

Kubectl version:
 kubectl version --short
Client Version: v1.22.2
Server Version: v1.18.20-eks-8c579e
```

**Comment by zirain** [comment]
@dbali07 what's the istio version?

**Comment by dbali07** [comment]
1.3

**Comment by zirain** [comment]
refer to https://istio.io/latest/docs/releases/supported-releases/ , 1.3 is no longer supported

**Comment by dbali07** [comment]
Ok thanks. 

Just out of curiosity. Is this the reason why this isn't working? I mean due to istio's version? 

I'm just asking so that I don't spend any more time on it if there is no point of anything working due to it's version.

**Comment by zirain** [comment]
> Ok thanks.
> 
> Just out of curiosity. Is this the reason why this isn't working? I mean due to istio's version?
> 
> I'm just asking so that I don't spend any more time on it if there is no point of anything working due to it's version.

IMHO, 
```
xff_num_trusted_hops: 5
max_request_headers_kb: 90
```

this configs seems not design for remove any ` response header`

**Comment by dbali07** [comment]
Ok. Thanks again :)
