### ISSUE TITLE
Istio starts terminating during prestop hook

### ISSUE THREAD

**Issue by rittneje** [istio/istio#36631]
### Bug Description

We know that there is an existing bug in Istio where the sidecar starts terminating immediately, because there is no concept of dependencies between containers during shutdown. This in turn leads to some downtime during scaledown and rollout.

As a workaround, we tried adding a prestop hook to our main container, so that it could shut down cleanly before the sidecar receives SIGTERM.

However, what we observed is that requests during the prestop hook execution still fail. My assumption is the sidecar observes the pod enter the terminating state, and prematurely starts terminating connections.

Connections must not be terminated or otherwise prevented until the sidecar itself receives SIGTERM.

### Version

```prose
$ istioctl version
client version: 1.10.5
control plane version: 1.10.5
data plane version: 1.10.5 (31 proxies)

$ kubectl version --short
Client version: v1.19.15
Server version: v1.19.13-eks-8df270
```

**Comment by hzxuzhonghu** [comment]
@rittneje https://github.com/istio/istio/pull/36633

**Comment by hzxuzhonghu** [comment]
This is because pod termination process is like:

kubelet execute the same container kill procedure for all the containers concurrently. 

1. run prestop hook
2. send SIGTERM
3. SIGKILL if container does not exit after a duration(can be configured, 30s default)

**Comment by rittneje** [comment]
To me the Kubernetes docs imply that pre-stop hooks will be invoked (and completed) prior to SIGTERM. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

Also, I am wondering if we can simplify all of this by having the sidecar host a listener, perhaps a Unix domain socket. At startup my container will connect to that listener, and close this connection after graceful cleanup (or just let the kernel do it). Meanwhile, when the sidecar receives SIGTERM, it closes this listener, then waits for all of those connections to close, and only then does it start draining envoy. This I think will keep things very simple in my container. I won't need to rely on pre-stop hooks, and Istio won't need to guess when my container is done.

**Comment by hzxuzhonghu** [comment]
We are already doing similar work.

**Comment by rittneje** [comment]
Is there a PR or something I can track for that? Is there any ETA in terms of the release schedule?

**Comment by rittneje** [comment]
@hzxuzhonghu I've seen lots of references to different environment variables and such to essentially control how long the sidecar will wait to drain Envoy. However, ultimately they are all predicated on guessing when the main container is finished. What I am proposing above with the UDS does not involve any such guessing, and thus will be much more useful.

**Comment by hzxuzhonghu** [comment]
There is also /quitquitquit that you can call, it is same to send SIGTERM, which is intended for jobs

**Comment by rittneje** [comment]
Can you elaborate on that? Is /quitquitquit an executable within the sidecar container? How and when would I call it?
