### ISSUE TITLE
Implement OpenTelemetry Access Log

### ISSUE THREAD

**Issue by zirain** [istio/istio#36637]
Currently [OpenTelemetry (gRPC) Access Log](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto#opentelemetry-grpc-access-log) was added to envoy.

After a quick look at the API, I think this is easier than [gRPC Access Log Service (ALS)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/grpc/v3/als.proto) for end-uses when someone want to control output format.

I'm plan to add a basic implement in 1.13, here is a draft API design [otel provider](https://github.com/istio/api/pull/2175).

@howardjohn @douglas-reid WDYT?

**Comment by howardjohn** [comment]
I don't know much about this space so I would defer to @douglas-reid, but it seems reasonable to me

**Comment by douglas-reid** [comment]
Adding an OTel provider seems reasonable. The only bump in the road may be if providers move out to their own API.

**Comment by zirain** [comment]
> Adding an OTel provider seems reasonable. The only bump in the road may be if providers move out to their own API.

do we need to wait OTEL logging spec go to v1.0.0?

**Comment by douglas-reid** [comment]
> do we need to wait OTEL logging spec go to v1.0.0?

i don't think so. i think it makes sense to try to add the provider and see if there is any pushback at this point. my draft proposal for a providers API hasn't moved along yet, so now would be the time to add new providers.

**Comment by zirain** [comment]
@douglas-reid can you take a look at https://github.com/istio/api/pull/2175?
