### ISSUE TITLE
[Question] Asynchronous external authentication & tracing

### ISSUE THREAD

**Issue by philschmid** [istio/istio#36666]
Hello 🙋🏻‍♂️, 

I read through the documentation of `Security` and `Observability` but could find an answer i am looking for. I know that it is possible to use `external` authentication. 

My Question: Is it possible to add "asynchronous" external authentication or tracing/logging. What i mean by that is that Istio forwards the request to the service already and starts the authentication simultaneously. If the authentication fails istio returns a 401 if it fails istio returns a 200.
I ask for this since my API authentication is online and needs to gather external information, which is costly that way we could save already a lot of time and it is not a problem to throw the request away if the user provides a false authentication. 

I addition to this I am curious if istio enables some kind of asynchronous logging, meaning each incoming request, which was successfully resolved is passed into service to gather metrics, information about the response like length etc.

**Comment by bianpengyuan** [comment]
Authn should always be synchronous. The async check you described basically means no auth. You should add a cache layer instead if the external auth service is slow.

All istio/envoy logging and metrics are async, including istio metrics, envoy access log, or any other envoy telemetry integration mechanism like gRPC access log services.
