### ISSUE TITLE
Add mechanism to sleep before envoy drain starts

### ISSUE THREAD

**Issue by rittneje** [istio/istio#36660]
**Describe the feature request**

Because Kubernetes is a distributed system, it can take some time after a pod starts terminating before other resources notice and take appropriate action, such as the pod getting deregistered from the service endpoints list. Consequently, best practice is to sleep some arbitrary amount of time after receiving SIGTERM before actually starting cleanup, in order to avoid any interruption.

However, this is not currently possible with Istio, because the sidecar always terminates Envoy immediately. This means any new connections that come in during this window get rejected anyway.

Please add a configuration option (istio-proxy env var?) to specify how long to wait after receiving SIGTERM and _before_  initiating the Envoy drain. Perhaps this can replace `MINIMUM_DRAIN_DURATION`?

**Describe alternatives you've considered**

If #36640 is done then this shouldn't be necessary.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
> it can take some time after a pod starts terminating before other resources notice and take appropriate action, such as the pod getting deregistered from the service endpoints list.

You mean there is some other components watching pod terminating and send api call to it?

**Comment by rittneje** [comment]
It is handled automatically by the control plane or something like that. We don't do anything specifically for it.

**Comment by howardjohn** [comment]
terminationDrainDuration does this exact if I understand right. Default is 5s

**Comment by rittneje** [comment]
@howardjohn No, `terminationDrainDuration` is applied _after_ Envoy starts draining.

https://github.com/istio/istio/blob/cdd7cf9dea6eb0c5e583920f30a94543a453d706/pkg/envoy/agent.go#L139
https://github.com/istio/istio/blob/cdd7cf9dea6eb0c5e583920f30a94543a453d706/pkg/envoy/agent.go#L162

**Comment by howardjohn** [comment]
Ah right. What is the problem with drain? It's supposed to be graceful (ie send `connection: close` header, not termination of connection)?

**Comment by rittneje** [comment]
What we are observing is during the "graceful" drain, new inbound/outbound connections will fail, resulting in errors. In particular, ingress-nginx starts returning sporadic 502s.

**Comment by howardjohn** [comment]
100% of them? or only some?

If 100% it seems definitely a bug. Plausibly a bug regardless

**Comment by rittneje** [comment]
It is not all of them. And I don't know that much about the internals of nginx in terms of its connection management logic.

Also, as I mentioned [here](https://github.com/istio/istio/issues/36640#issuecomment-1003064422) I do not understand the point of draining Envoy during shutdown at all. Shouldn't you just wait for the main container to close all of its connections of its own accord?

**Comment by howardjohn** [comment]
Yes, which we have an experimental option for. But it's brand new and
untested in production environments.

But draining is still useful to have clients gracefully exit rather than
have the tcp connection closed,for http

**Comment by rittneje** [comment]
Which option are you referring to? If you mean `terminateOnZeroActiveConnections`, that is also applied after draining Envoy, so the same issue will result.

> But draining is still useful to have clients gracefully exit rather than have the tcp connection closed,for http

What I believe you are saying here is that what the Envoy drain is intended to do is set the `connection: close` header so the client knows to redial (and presumably connect to some other pod). Because of the latency in terms of the service endpoints list updating, this should not happen immediately upon SIGTERM, or else it is possible for the client to end up redialing the exact same pod. (And the latency is even worse for the public-facing AWS NLB.)

Another thing I will point out is that Envoy will drain connections for `drainDuration`, which defaults to 45s. So if you specify `terminationDrainDuration` that is > 45s, it won't have the desired effect unless you update `drainDuration` to match. This should be clearly mentioned in the Istio docs.

Furthermore, the Istio docs say "On receiving SIGTERM or SIGINT, istio-agent tells the active Envoy to start draining, preventing any new connections and allowing existing connections to complete." If this statement is true, that would explain why we are seeing sporadic failures during graceful drain. If you sleep long enough for the load balancer to deregister the pod first, then it shouldn't matter that new inbound requests will fail.

From the code I see istio-proxy is supposed to tell Envoy only to drain the inbound listeners, which is good. I think perhaps part of the issue in play here may be that when ingress-nginx receives connections, they are not coming through istio-proxy, so they don't count. That means that `exitOnZeroActiveConnections` will not be especially helpful. in that situation. I see no way out of this other than the UDS we've been discussing

**Comment by rittneje** [comment]
@howardjohn It seems to me that even if you add a UDS (or similar) to synchronize the main container, adding a sleep before starting the drain is necessary unless the main container can be relied upon to set the `Connection: close` header. Right now our only option is to add a sleep manually via the sidecar template, which is not ideal. As such, would you be okay with adding another configuration option named `SHUTDOWN_GRACE_PERIOD` or something?

**Comment by howardjohn** [comment]
If the main container sets `Connection: close` I don't think it will even
be propagated to clients, regardless of shutdown.

I would think most users would want these headers added by envoy
immediately when SIGTERM is hit. This should not break any traffic but
start shifting it to other containers immediately. Then when the app shuts
down we can immediately exit?

**Comment by rittneje** [comment]
> This should not break any traffic but start shifting it to other containers immediately.

This is not entirely true. From what I understand, it can take some time for the Service to deregister the pod, until which other pods might continue to connect to the terminating one. Since this happens in parallel to your pod receiving SIGTERM, you are supposed to wait some time before actually initiating shutdown. Consequently, it would be desirable to wait some time before istio-proxy starts sending back `Connection: close` or else there is some possibility the client will reconnect to you anyway.

Regardless, I am still unclear what the behavior of Envoy is during graceful draining. From what I can tell, istio-proxy sends `POST /drain_listeners?inboundonly&graceful`. According to the [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-drain), the listeners will not be closed until _after_ the drain. 

> When draining listeners, enter a graceful drain period prior to closing listeners.

However, the [Istio docs](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig) for `terminationDrainDuration` imply that new connections will be prevented _during_ the drain. 

> On receiving SIGTERM or SIGINT, istio-agent tells the active Envoy to start draining, preventing any new connections and allowing existing connections to complete.

Which of these two statements is correct?

**Comment by howardjohn** [comment]
I think the Istio doc is outdated, it used to work this way then we added
the `graceful` part

**Comment by rittneje** [comment]
@howardjohn According to the Envoy devs, new connections stop being accepted at the _start_ of the graceful drain, which contradicts their own documentation. https://github.com/envoyproxy/envoy/issues/19369

If this is true, then the proposed sleep is required to avoid downtime.

**Comment by gyz2009** [comment]
The same error occurred in 1.6 and 1.10, when Pod entered Terminate, it would continue to receive requests, so there would be 503 error. The same error occurred when SLEEP was added to Prestop. It seems that EDS did not update.

**Comment by rittneje** [comment]
@gyz2009 What is EDS?

**Comment by rittneje** [comment]
ping @howardjohn

**Comment by howardjohn** [comment]
I am not sure the expectation? I thought the concern was based on https://github.com/istio/istio/issues/36660#issuecomment-1006733647, which was later refuted by https://github.com/envoyproxy/envoy/issues/19369#issuecomment-1028140920.

if we are already gracefully (ie accept new connections, tell existing connections to close) draining, what more do we want?

**Comment by rittneje** [comment]
Yeah, I got confused by their contradictory responses I guess.

We can leave this unless they later conclude that it actually does close the listeners immediately.
