### ISSUE TITLE
Istio ingress will silently ignore the mesh config if installed to any namespace other than istio-system

### ISSUE THREAD

**Issue by farcaller** [istio/istio#36670]
### Bug Description

Based on the suggested setup from [Installing Gateways](https://istio.io/latest/docs/setup/additional-setup/gateway/) if the gateway is installed to the namespace istio-ingress it will still try to look up the istio config at `cm/istio`. However, the istio configmap still resides in namespace istio-system and thus the ingress will boot up without the mesh config (as the config map is set to optional), thus ignoring settings like e.g. tracing options.

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (18 proxies)
$ kubectl version --short
Client Version: v1.21.1+k3s1
Server Version: v1.21.1+k3s1
$ # no helm used, deployed via the operator
```

### Additional Information

istioctl bug-report is irrelevant to the bug as this is a helm chart configuration issue.

**Comment by bianpengyuan** [comment]
Are you sure the setting is ignored? If gateway is deployed in namespaces other than istio-system with namespace injection, mesh config will be injected via PROXY_CONFIG env var.

**Comment by farcaller** [comment]
Yep. Here's the config dump of the ingress when config isn't present:

![image](https://user-images.githubusercontent.com/693/147783344-364254bf-1602-4729-8781-cd5bf4d409b3.png)

to me it looks like the defaults coming from here? https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh.go#L54

**Comment by bianpengyuan** [comment]
How do you deployed the gateway exactly and what is your gateway deployment look like?

**Comment by farcaller** [comment]
I have the following snippet in my `IstioOperator` resource:

```js
    spec: {
      profile: 'default',
      components: {
        cni: {
          enabled: true,
        },
        ingressGateways: [
          {
            enabled: true,
            name: 'istio-ingressgateway',
            namespace: 'istio-ingress',
            k8s: {
              service: {
                externalTrafficPolicy: 'Local',
              },
            },
          },
        ],
      },
```

The `istio-ingress` is created with `istio-injection=enabled`.

**Comment by farcaller** [comment]
Only the following env vars are present on the ingress:

```
    Environment:
      JWT_POLICY:                   third-party-jwt
      PILOT_CERT_PROVIDER:          istiod
      CA_ADDR:                      istiod.istio-system.svc:15012
      NODE_NAME:                     (v1:spec.nodeName)
      POD_NAME:                     istio-ingressgateway-865d6cbccb-swbpb (v1:metadata.name)
      POD_NAMESPACE:                istio-ingress (v1:metadata.namespace)
      INSTANCE_IP:                   (v1:status.podIP)
      HOST_IP:                       (v1:status.hostIP)
      SERVICE_ACCOUNT:               (v1:spec.serviceAccountName)
      ISTIO_META_WORKLOAD_NAME:     istio-ingressgateway
      ISTIO_META_OWNER:             kubernetes://apis/apps/v1/namespaces/istio-ingress/deployments/istio-ingressgateway
      ISTIO_META_MESH_ID:           cluster.local
      TRUST_DOMAIN:                 cluster.local
      ISTIO_META_UNPRIVILEGED_POD:  true
      ISTIO_META_CLUSTER_ID:        Kubernetes
```

**Comment by farcaller** [comment]
I guess it's because ingresses specifically disallow injection? https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L45

**Comment by bianpengyuan** [comment]
Do you set values to enable gateway injection following the doc https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway?

```
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
```

**Comment by farcaller** [comment]
...

I sure should have done something better with my time than trying to tinker with service meshes one day before the year ends.

That was indeed it, thanks!
