### ISSUE TITLE
Istio rewrites HTTP probes incorrectly

### ISSUE THREAD

**Issue by rittneje** [istio/istio#36684]
### Bug Description

We are deploying ingress-nginx inside an Istio-enabled namespace. The pod spec includes the annotation `traffic.sidecar.istio.io/includeInboundPorts: ""`, and does NOT include any `sidecar.istio.io/rewriteAppHTTPProbers` annotation. We have included liveness and readiness probes for our container.

```yaml
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

However, the actual pod spec shows this:
```yaml
      livenessProbe:
        httpGet:
          path: /app-health/nginx-ingress-controller/livez
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /app-health/nginx-ingress-controller/readyz
          port: 15020
          scheme: HTTP
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
```

Furthermore, these probes aren't equivalent.

Using the original health check:
```
# curl http://10.0.223.91:10254/healthz -v
*   Trying 10.0.223.91:10254...
* TCP_NODELAY set
* Connected to 10.0.223.91 (10.0.223.91) port 10254 (#0)
> GET /healthz HTTP/1.1
> Host: 10.0.223.91:10254
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sun, 02 Jan 2022 18:34:12 GMT
< Content-Length: 2
< 
* Connection #0 to host 10.0.223.91 left intact
ok
```

Using the rewritten health check:
```
# curl http://10.0.223.91:15020/app-health/nginx-ingress-controller/readyz -v
*   Trying 10.0.223.91:15020...
* TCP_NODELAY set
* Connected to 10.0.223.91 (10.0.223.91) port 15020 (#0)
> GET /app-health/nginx-ingress-controller/readyz HTTP/1.1
> Host: 10.0.223.91:15020
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sun, 02 Jan 2022 18:34:55 GMT
< Content-Length: 0
< 
* Connection #0 to host 10.0.223.91 left intact
```

You will notice that the latter is missing the response body.

### Version

```prose
$ istioctl version
client version: 1.10.5
control plane version: 1.10.5
data plane version: 1.10.5 (31 proxies)

$ kubectl version --short
Client version: v1.19.15
Server version: v1.19.13-eks-8df270
```

**Comment by rittneje** [comment]
I get the feeling that the default value for `sidecarInjectorWebhook.rewriteAppHTTPProbe` was flipped from `false` to `true` at some point, but I can find no mention of this in the release notes. For reference, the current documentation for [IstioOperator](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/) still links to the 1.5 [Helm installation options](https://istio.io/v1.5/docs/reference/config/installation-options/) for the `values` field, and there it shows the default value is `false`.

Regardless, that does not explain why the response body is lost.

**Comment by howardjohn** [comment]
rewriteAppHTTPProbe has been `true` for at least a year or so, not sure the exact version that enabled it. Body is intentionally not included, it is not needed for probes as only the response code is used.

**Comment by rittneje** [comment]
I think it makes sense for it to default to `true` in the common case. However, the rewrite is superfluous when the port in question is not being intercepted. In any case, since this was missed, can a note be added to the 1.13 upgrade notes, as well as backported to all the other relevant upgrade notes?

>  Body is intentionally not included, it is not needed for probes as only the response code is used.

Seems like a strange optimization to me, since Istio usually strives for full transparency. Probably doesn't matter too much unless kube logs the response body, or something else tries to issue the probes, but still.

**Comment by howardjohn** [comment]
I think adding a release note in 1.13 will add confusion, we add notes only
for the version that introduced the change. If we missed that in 1.5 or 1.6
or so when we released them that is unfortunate - I would suggest a PR to
only those versions but I think the archives are frozen (not 100% sure).

**Comment by rittneje** [comment]
The problem with that is that anyone who has already upgraded is unlikely to ever look back at the old upgrade notes, so they won't see it. Would it really be that confusing to say something to the effect of "As of Istio 1.X, by default pod liveness and readiness probes will be rewritten to be proxied through the sidecar. Use the `sidecar.istio.io/rewriteAppHTTPProbers: "false"` pod annotation to disable this behavior per pod. This item was originally missing from the Istio 1.X upgrade notes."
