### ISSUE TITLE
Auto Notification of new Istio release or patching security fix of supported release

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#36689]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We are building cluster using Kubernetes and Istio as control plane and we are finding it difficult to update or upgrade istio releases. One problem is 1) Updating istio in cluster for a critical security fix 2) Upgrade to new version of Istio when existing version is not supported or when new release is available.
Questions:
1) How clients of istio will get notified about new releases or security fix for version they are using? Is there is any auto notification system?
2) What are the guidelines to keep istio in cluster updating with security or critical bug fixes?
It is a security concern if we don't pick security fixes for the istio version we are using in cluster. Suggest us way to keep cluster updated with Istio.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[X ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)** X

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
Istio release and cve patch will be notified at multiple places: Istio slack announcement channel, istio discuss forum (https://discuss.istio.io/c/announcements/5), and istio.io news which you can subscribe with rss. The recommendation is always upgrading Istio ASAP when a security fix release is available, or is there some other guidelines you are looking for?

**Comment by keerthig9** [comment]
1) How to update Istio for same version to pick security/bug fixes? As multiple istio components will be already deployed in cluster, how do we bring patched istio to cluster? Can you share instructions how to do?

2) Is Istio component safe to upgrade to next version in production clusters with high traffic?

**Comment by bianpengyuan** [comment]
See istio upgrade guide: https://istio.io/latest/docs/setup/upgrade/

And yes, it is safe to upgrade Istio with live traffic.

**Comment by bianpengyuan** [comment]
> How to update Istio for same version to pick security/bug fixes

And to clarify, any bug fixes and security fixes will be shipped with a new version of Istio.

**Comment by keerthig9** [comment]
> > How to update Istio for same version to pick security/bug fixes
> 
> And to clarify, any bug fixes and security fixes will be shipped with a new version of Istio.

with minor version release?

**Comment by keerthig9** [comment]
> https://discuss.istio.io/c/announcements/5

IS it possible to enable email notification when new release available? and if yes, how?

**Comment by bianpengyuan** [comment]
Yeah you can turn on email subscription at istio forum.

**Comment by keerthig9** [comment]
One more question: For bug fixes/security issues, Do you patch all supported versions at that time?

**Comment by bianpengyuan** [comment]
Yes

**Comment by bianpengyuan** [comment]
Actually we have a complete doc about this: https://istio.io/latest/docs/releases/security-vulnerabilities/#public-disclosure
