### ISSUE TITLE
Istio should exit immediately during shutdown if envoy exits

### ISSUE THREAD

**Issue by rittneje** [istio/istio#36686]
**Describe the feature request**

If envoy exits after istio-proxy receives SIGTERM (perhaps because someone sends /quitquitquit to it), then istio-proxy should exit immediately.

Currently it will get stuck in `Agent.terminate`.
1. If `exitOnZeroActiveConnections` is true, then it will keep polling the number of active connections. Since this will fail, it will return -1 all the time, which will cause it to loop infinitely until the pod termination grace period expires.
2. If `exitOnZeroActiveConnections` is false, then it will pointlessly keep waiting until the `terminationDrainDuration` expires.

To fix this, it must pull from `a.statusCh` and take appropriate action.

If this is fixed, then use cases like ingress-nginx that cannot rely on `exitOnZeroActiveConnections` can at least issue /quitquitquit just before exiting to abort the `terminationDrainDuration` sleep prematurely.

**Describe alternatives you've considered**

None

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
Are you asking if `/quitquitquit` should forcefully exit? If yes - I think that is fair given that it is currently only used in Jobs. But if it is used else where, we can also add `/quitquitquit?shutdownImmediate` .

**Comment by rittneje** [comment]
No, I'm saying right now there is arguably a bug if envoy exits for any reason while istio-proxy is in the middle of shutdown (in `Agent.terminate`).

Also, I think you may have misunderstood. I am referring to the [envoy endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--quitquitquit). From what I understand, istio-proxy itself also has a `/quitquitquit` endpoint that causes it to send SIGTERM to itself, but that is separate.

**Comment by hzxuzhonghu** [comment]
I get to understand the issue, it is a potential race here, let me file a fix

**Comment by rittneje** [comment]
@ramaraochavali It seems the istio-policy-bot needs you to do something else.

**Comment by ramaraochavali** [comment]
no stale

**Comment by rittneje** [comment]
@howardjohn This is not stale.

**Comment by zirain** [comment]
no stale

**Comment by hzxuzhonghu** [comment]
Is anyone working on this?
