### ISSUE TITLE
CA certificate do not match even after restarting Istio pod.

### ISSUE THREAD

**Issue by brahankv** [istio/istio#36687]
### Bug Description

Encountered x509 certificate error while side loading. Followed the troubleshooting,
https://istio.io/latest/docs/ops/common-problems/injection/#x509-certificate-related-errors

The certificates do not match even after restart of Istio pod.

$ kubectl -n istio-system get secret istiod-service-account-token -o jsonpath='{.data.root-cert\.pem}' | md5sum
d41d8cd98f00b204e9800998ecf8427e  -

$ kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml -o jsonpath='{.webhooks[0].clientConfig.caBundle}' | md5sum
6c06e4e908c93fc254458e27f46d4d43  -

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (2 proxies)

$ kubectl version --short
Client Version: v1.20.14
Server Version: v1.20.14
```

**Comment by howardjohn** [comment]
That troubleshooting doc is definitely wrong. I think its a legacy from Istio ~1.4 or so. It should match the istio-ca-secret and/or istio-root-cert secret I think (not at computer so I may be slightly off on the names)

**Comment by bianpengyuan** [comment]
@brahankv the command at doc has been updated. Please try it out again and see if the cert are the same. If yes, there is probably something else which will need more info for debugging.

**Comment by brahankv** [comment]
@bianpengyuan, Now the certificates match but still getting certificate error while the job/pod created. 

```
$ kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml -o jsonpath='{.webhooks[0].clientConfig.caBundle}' | md5sum
6c06e4e908c93fc254458e27f46d4d43  -

$ kubectl -n istio-system get configmap istio-ca-root-cert -o jsonpath='{.data.root-cert\.pem}' | base64 -w 0 | md5sum
6c06e4e908c93fc254458e27f46d4d43  -

Events:
  Type     Reason        Age                      From            Message
  ----     ------        ----                     ----            -------
  Warning  FailedCreate  119s (x1906 over 2d15h)  job-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": x509: certificate signed by unknown authority
```
Please let me know if any other info is required for debugging.

**Comment by bianpengyuan** [comment]
Does call from your API server go through a http proxy or get redirected to some external server?

**Comment by brahankv** [comment]
It is a single node K8S cluster and have http proxy for external access.

**Comment by bianpengyuan** [comment]
Probably try what suggested at https://github.com/istio/istio/issues/5828#issuecomment-417402719

**Comment by brahankv** [comment]
Thanks. After updating no_proxy, the certificate issue was resolved.
