### ISSUE TITLE
Is "bazel-bin/src/envoy/envoy" the binary that was built to be used as istio-proxy ?

### ISSUE THREAD

**Issue by choppspavan** [istio/istio#36692]
Hi ,

We are trying to build istio-proxy from the source code after pulling the code from "https://github.com/istio/proxy" .

a. git checkout -b release-1.6. (We require 1.6 to be build)
b. And installed required prerequisites.
c. cd proxy
d. make
e. make build_envoy

After the above ran successful , we can see the executable below got generated and build messages shown succesfull.

proxy/bazel-bin/src/envoy/envoy

a. Can we assume that we build properly?
b. Would there be any other executable get generate ?
c. Is the "proxy/bazel-bin/src/envoy/envoy" expected binary to be build ?

Thanks,
Pavan

**Comment by bianpengyuan** [comment]
There are also several wasm binaries. You can look at the commands that are executed at istio proxy postsubmit which pushes the needed binaries to GCS bucket: https://prow.istio.io/view/gs/istio-prow/logs/release_proxy_release-1.6_postsubmit/1329618154929786880. Specifically look for the make command executed there.

**Comment by choppspavan** [comment]
Thanks for your reply and the quick response..will check that..

**Comment by choppspavan** [comment]
I am getting segmentation fault with the built envoy .Can you help here?
bash-4.2# ./envoy --version
Segmentation fault
bash-4.2# pwd
/proxy/bazel-bin/src/envoy
bash-4.2# ls -lrt
total 1466852
drwxr-xr-x 6 root root       4096 Jan  4 11:03 http
-r-xr-xr-x 1 root root     323043 Jan  4 11:05 envoy-2.params
drwxr-xr-x 7 root root       4096 Jan  4 11:06 tcp
-r-xr-xr-x 1 root root        208 Jan  4 11:07 envoy_tar.args
drwxr-xr-x 3 root root       4096 Jan  4 11:07 _objs
-r-xr-xr-x 1 root root 1167647992 Jan  4 11:08 envoy
bash-4.2#

**Comment by zirain** [comment]
> I am getting segmentation fault with the built envoy .Can you help here? bash-4.2# ./envoy --version Segmentation fault bash-4.2# pwd /proxy/bazel-bin/src/envoy bash-4.2# ls -lrt total 1466852 drwxr-xr-x 6 root root 4096 Jan 4 11:03 http -r-xr-xr-x 1 root root 323043 Jan 4 11:05 envoy-2.params drwxr-xr-x 7 root root 4096 Jan 4 11:06 tcp -r-xr-xr-x 1 root root 208 Jan 4 11:07 envoy_tar.args drwxr-xr-x 3 root root 4096 Jan 4 11:07 _objs -r-xr-xr-x 1 root root 1167647992 Jan 4 11:08 envoy bash-4.2#

need more info, os、arch etc.

**Comment by choppspavan** [comment]
Here is the info , i am trying to build envoy .

bash-4.2# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
bash-4.2# uname -a
Linux a7477a64df7b 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2#

**Comment by zirain** [comment]
> Here is the info , i am trying to build envoy .
> 
> bash-4.2# cat /etc/os-release NAME="Oracle Linux Server" VERSION="7.9" ID="ol" ID_LIKE="fedora" VARIANT="Server" VARIANT_ID="server" VERSION_ID="7.9" PRETTY_NAME="Oracle Linux Server 7.9" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:oracle:linux:7:9:server"
> 
> bash-4.2# uname -a Linux a7477a64df7b 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux bash-4.2#

did the `make build_envoy` completed correct?
as I can remember, envoy support Ubuntu officially in 1.6.

**Comment by choppspavan** [comment]
Yes received successful image.

**Comment by choppspavan** [comment]
I assume people succesfully built(istio-proxy and envoy) binaries on top of RHEL . Please correct me if my understanding is wrong.

**Comment by zirain** [comment]
> I assume people succesfully built(istio-proxy and envoy) binaries on top of RHEL . Please correct me if my understanding is wrong.

If you just want to build an binary,  use [docker](https://www.envoyproxy.io/docs/envoy/latest/start/docker) is better choice.

**Comment by choppspavan** [comment]
Thanks for your patience and the responses.
a. Our requirement was to build istio-proxy and envoy from source code on top of RHEL . And I am stuck at the below steps.

1. Sucessfully built envoy binary but facing segmentation fault when trying to run the executable.
2. I dint see any separate istio-proxy binary generated after I ran (make and make build_envoy from source code).

It would be really helpful if you can throw some help/pointers in the above issues.

**Comment by choppspavan** [comment]
Ok for debian platform, I see there is one "istio-proxy" is being packaged as part of this target (https://github.com/istio/proxy/blob/release-1.6/tools/deb/BUILD) . So I thought , it might be available for RHEL too.

**Comment by zirain** [comment]
> Ok for debian platform, I see there is one "istio-proxy" is being packaged as part of this target (https://github.com/istio/proxy/blob/release-1.6/tools/deb/BUILD) . So I thought , it might be available for RHEL too.

this [vm doc](https://istio.io/v1.6/docs/setup/install/virtual-machine/#configure-the-virtual-machine) may give you some help.

**Comment by choppspavan** [comment]
I built using "make build_envoy_tsan" target , that seem to resolve the issue and I can see no longer segmentation fault . Is it correct ?

bash-4.2# bazel-bin/src/envoy/envoy --version

bazel-bin/src/envoy/envoy  version: 4dc5fec0086ad5c00dba0b397c71ef523424ded5/1.14.5-dev/Modified/DEBUG/BoringSSL

bash-4.2#

**Comment by zirain** [comment]
> I built using "make build_envoy_tsan" target , that seem to resolve the issue and I can see no longer segmentation fault . Is it correct ?
> 
> bash-4.2# bazel-bin/src/envoy/envoy --version
> 
> bazel-bin/src/envoy/envoy version: 4dc5fec0086ad5c00dba0b397c71ef523424ded5/1.14.5-dev/Modified/DEBUG/BoringSSL
> 
> bash-4.2#

@kyessenov maybe you know the diff between `make build_envoy_tsan` and `make build_envoy` and why there's no longer segmentation fault.
