### ISSUE TITLE
Get all the VIPs of a service entry through MCP over xds

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#36694]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Get all the VIPs of a service entry through MCP over xds.

Currently, MCP over xds assumes the request comes from the data plane and only add the service VIP of the same cluster to the response of the request.  [the current implementation](https://github.com/istio/istio/blob/fef0938eb0570d81cfc0a7c6a877c7f0f7315603/pilot/pkg/model/service.go#L744)

[Aeraki](https://github.com/aeraki-framework/aeraki) is using MCP over xds to fetch the service registry from Istio. Aeraki runs on the control plane and needs all the VIPs. 

**Describe alternatives you've considered**
Deploying an Aeraki instance in each cluster could be an alternative solution. However, I prefer using the same deploy mode as Istiod since they're both in the control plane.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[*] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by costinm** [comment]
Sounds very reasonable. Main concern is the protocol - the quick solution would be to use a node metadata to indicate the node is a 'controller', and we may start with that.

However there is a larger issue - we may need to have some better filtering. One option is to treat the resource name as a URL, i.e. use query parameters. It is backward compatible to add this, and may allow per-resource filtering. For example we may want only resources from a namespace, or from a namespace + all imported/visible resources, or from specific clusters. 
MCP over XDS is supposed to be aligned with K8S API semantically, so it makes sense to provide at least the same granularity that K8S provides, plus the cross cluster option.

**Comment by zhaohuabing** [comment]
Related Aeraki issue: https://github.com/aeraki-framework/aeraki/issues/149

**Comment by zhaohuabing** [comment]
> Sounds very reasonable. Main concern is the protocol - the quick solution would be to use a node metadata to indicate the node is a 'controller', and we may start with that.
> 

It seems that there's no appropriate place in MetaData for this, should we add a new "controller" node type here to indicate this xds client is actually a "controller"?  https://github.com/istio/istio/blob/ba7a7795adc2bddc1d6989395fc9414db8142e15/pilot/pkg/model/context.go#L741

**Comment by costinm** [comment]
Sounds reasonable. 

Another approach is to add a setting to istiod with the service account of the controller. This is better in some ways - we may want to lock down untrusted pods from getting full config, and allow-list controllers.

But we can start with a label.

**Comment by huanghuangzym** [comment]
istio now support multi vip in serviceentry only in tcp proxy
