### ISSUE TITLE
istioctl replace results in an error, while create followed by delete works.

### ISSUE THREAD

**Issue by hklai** [istio/istio#3669]
A bug was reported by https://groups.google.com/forum/#!topic/istio-dev/Ek8kZBuyGg8

when i execute the following script, it got following
    istioctl replace -f samples/bookinfo/kube/route-rule-reviews-v3.yaml
    Error: revision is required
 but i can execute following scripts and it can be working ok
        istioctl delete routerule reviews-default -n default
	istioctl create -f samples/bookinfo/kube/route-rule-reviews-v3.yaml

**Comment by esnible** [comment]
This is working for me using master.  Closing.
