### ISSUE TITLE
Unify xds proxy and sds client tls config setting

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#36709]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Currently the the grpc dial options they are using are built similarly, which is very duplicate, so we should merge them. 
And by doing this, it will be helpful for maintenance.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
In theory they could share the same connection as well. Although it only works in some subset of cases so probably super complex

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/42720
