### ISSUE TITLE
traffic being handles by nginx-ingress with an istio sidecar only works with virtual services when the ingress definition is set to port 80

### ISSUE THREAD

**Issue by bob-walters** [istio/istio#36705]
### Bug Description

**Note: Completely revised this description on Jan-8-2021 to better focus on the behavior which may constitute a bug**

I am seeing inconsistencies in the way Virtual Service port configurations work when the service is behind an nginx-ingress which might indicate a bug.  (I.e. definitely seems counter-intuitive.)

The github project at https://github.com/bob-walters/nginx-istio provides some files to reproduce this.  (And full details of the config I used to create this behavior)

Was able to get Virtual Services to successfully route traffic arriving at an nginx-ingress controller by using an approach suggested:
* The Ingress definition for the hosts uses the `nginx.ingress.kubernetes.io/upstream-vhost:` annotation to set the host header to the long version of a K8s service name.
* The associated Virtual Service declares that same value for it's 'hosts'
* The virtual service is in the same namespace as the Ingress definition.

With that configuration, the virtual service applies to the inbound traffic correctly.   If I inspect the proxy config with `istioctl proxy-config routes -n ingress ingress-nginx-v4-controller-558d4d674f-2gxv5 --name 9898 -o json` I can see that the virtual service is in place for the port that traffic is being routed to.

However, if I pursue the approach of not using the `upstream-vhost` header because I don't want the Host header to be modified by Nginx during its forwarding of traffic, something counter-intuitive (a possible bug) happens:
* I remove the `nginx.ingress.kubernetes.io/upstream-vhost:` annotation.  Thus the host will contain the requested FQDN.
* I alter the Virtual Service definition to no longer be based on `hosts` corresponding to a K8s service, but rather on the FQDN which the requests are being sent to.  (E.g. podinfo.localhost.com)   The virtual service should still apply.

Result: The routing only works in this case if I also set the Ingress to route the traffic to port 80 of the K8s service.  If I route the traffic to the port of the K8s service the virtual service does not apply.  (Routing goes to the K8s service.)  Checking the proxy-config shows that the virtual service is in place for port 80 only.

That in itself may be expected behavior because the default port that istio may handle for a Virtual Service with corresponding service definition in K8s might default to 80.  (true?)

However, if I then configure an explicit port (9898) in the http routes of the virtual service (per the Ingress and Virtual service configs in https://github.com/bob-walters/nginx-istio/tree/main/didnt_work), corresponding to the route that the Ingress is sending the traffic to (9898), I still do not see the virtual service applied.  No configuration seems to take effect (per proxy-config for port 9898) - this approach to routing seems to be forcing the traffic to be on port 80 for some reason.

Is this an error on my part where some Service definition for the FQDN is required, and the Virtual Service cannot simply be defined for the requested FQDN the way that it can be for a gateway?

### Version

```prose
$ istioctl version
client version: 1.11.3
control plane version: 1.12.1
data plane version: 1.12.1 (7 proxies)
(⎈ |docker-desktop:default)Mac-mini:nginx-istio bobw$ kubectl --version short
Error: unknown flag: --version
See 'kubectl --help' for usage.
(⎈ |docker-desktop:default)Mac-mini:nginx-istio bobw$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.2
```

### Additional Information

$ istioctl bug-report

Target cluster context: docker-desktop

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2022-01-04 21:16:46.411405 -0500 EST

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.1", GitRevision:"88902a51acfb0383809608ccff169319560f768c", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.1}
[bug-report.tar.gz](https://github.com/istio/istio/files/7811634/bug-report.tar.gz)

Fetching proxy logs for the following containers:

default//hello-kubernetes/hello-kubernetes
default/default-podinfo-v2/default-podinfo-v2-6d8ccc8d4d-qjf45/istio-proxy
default/default-podinfo-v2/default-podinfo-v2-6d8ccc8d4d-qjf45/podinfo
default/default-podinfo/default-podinfo-868fdf8cb5-gq5vq/istio-proxy
default/default-podinfo/default-podinfo-868fdf8cb5-gq5vq/podinfo
default/podinfo-v1/podinfo-v1-6b8898549c-qdr75/istio-proxy
default/podinfo-v1/podinfo-v1-6b8898549c-qdr75/podinfo
default/podinfo-v2/podinfo-v2-f5cb48c4d-tbtbk/istio-proxy
default/podinfo-v2/podinfo-v2-f5cb48c4d-tbtbk/podinfo
flux/helm-operator/helm-operator-6854cb98fb-wg2ff/flux-helm-operator
ingress/ingress-nginx-v4-controller/ingress-nginx-v4-controller-78f7cddd9f-bxvm6/controller
ingress/ingress-nginx-v4-controller/ingress-nginx-v4-controller-78f7cddd9f-bxvm6/istio-proxy
ingress/ingress-nginx-v4-default-backend/ingress-nginx-v4-default-backend-6dd6fcddcb-4jdv2/ingress-nginx-default-backend
ingress/ingress-nginx-v4-default-backend/ingress-nginx-v4-default-backend-6dd6fcddcb-4jdv2/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-8c48d875-c9nxz/istio-proxy
istio-system/istiod/istiod-58d79b7bff-jjg56/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0103] (Pod hello-kubernetes.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Info [IST0102] (Namespace flux) The namespace is not enabled for Istio injection. Run 'kubectl label namespace flux istio-injection=enabled' to enable it, or 'kubectl label namespace flux istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service hello-kubernetes.default) Port name  (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Creating an archive at /Users/bobw/workspaces/labs/nginx-istio/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/00/7jsdj21j52scjw0c8jrmbrv40000gq/T/bug-report.
Done.

**Comment by bianpengyuan** [comment]
Proxy access log from istio sidecar of nginx will be helpful to tell how routing was performed: https://istio.io/latest/docs/tasks/observability/logs/access-log/

**Comment by bob-walters** [comment]
I just updated the description because I was able to get this form of routing to work with one configuration, and focus more clearly in on a configuration which should work (at least intuitively), and thus might evidence of a bug in the way that configuration is handled.  It could very possibly be an error on my part.

**Comment by bianpengyuan** [comment]
Yeah the host of virtual service for mesh gateway needs to match service from service registry. The fact that it works for port 80 is because there is some service in your registry that has port 80.

**Comment by bob-walters** [comment]
If that is the case, then why doesn't it work when there is a K8s service with port 9898 running and the routing done by Ingress is to port 9898?  That would appear to satisfy the same criteria.  Not also that even when the Virtual Service definition includes specific port criteria (9898) and that is the port the Ingress is routing to, it still fails to take effect.  Would a ServiceEntry address the issue?  I.e. creating one as if I intended on sending traffic to that Service so that I can in turn route traffic going to it as well?

**Comment by bianpengyuan** [comment]
Actually, sorry I was wrong at https://github.com/istio/istio/issues/36705#issuecomment-1008228254. This is actually a bug that it works for 80: https://github.com/istio/istio/issues/33760 VirtualService should always match on services exists in service registry.

**Comment by bianpengyuan** [comment]
And yeah define a ServiceEntry should work and you can select pods with `workloadSelector` at ServiceEntry.
