### ISSUE TITLE
 Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=30s": Address is not allowed

### ISSUE THREAD

**Issue by pluksha** [istio/istio#36702]
### Bug Description

HI!
We have EKS v1.19 cluster in AWS in the VPC CIDR 20.0.0.0/16 with 2 subnets: 20.0.1.0/24, 20.0.2.0/24
Since we reached limit of free IPs for nodes, podes in those subnets (20.0.1.0/24, 20.0.2.0/24) we created a new VPC CIDR (100.64.0.0/16) and configured EKS to use the pods' IPs from the new CIDR - following the article https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/
The issue is that once we do all that above the istio-operator, istiod, isito-ingressgateway pods up and running with the IPs from the subnets from the new CIDR (100.64.0.0/16) all the containers are failing with the error:
`Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=30s": Address is not allowed`

### Version

```prose
kubectl version --short
Client Version: v1.19.12
Server Version: v1.19.13-eks-8df270

"istio-operator" version 1.9.2
```

### Additional Information

`Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=30s": Address is not allowed`

**Comment by lllsJllsJ** [comment]
@pluksha 
I have face similar issue.
Do you find how to solve?

**Comment by pluksha** [comment]
Hi!
Yes, try to restart EKS control nodes - see
https://www.reddit.com/r/kubernetes/comments/dsj5on/address_is_not_allowed_when_deploying_metrics/

—
Regards,

Pavel Luksha

Devops Engineer, Klika Tech, Inc.

Mobile: +48 572 443 350

Email: ***@***.***

www.klika-tech.com


NOTICE: This email may contain confidential and privileged material for the
sole use of the intended recipient(s). Any review, use, distribution or
disclosure by others is strictly prohibited. If you are not the intended
recipient (or authorized to receive for the recipient), please contact the
sender by reply email and delete all copies of this message.
