### ISSUE TITLE
Headless services issues in multi-cluster multi-network

### ISSUE THREAD

**Issue by Champ-Goblem** [istio/istio#36733]
We have recently created a multi-cluster primary-remote multi-network setup with Istio to provide connectivity from services in the primary cluster to the remote for stateful workloads such as mysql, postgres and mongodb. So far we have been successful in getting services on the remote cluster to connect to these stateful applications via the usual kubernetes ClusterIP service. 

This works fine when there is only 1 replica of the above services running, what we are having trouble with is connecting to a headless service across the cluster boundary when running multi-replica instances. 

We have attempted the fix provided in #32515 but this is limited to single-network multi-cluster setups, which unfortunately we are not able to make use of due to cross cloud-provider communication. 

Are there any know solutions to resolve headless service DNS in a cluster for primary-remote and primary-primary, multi-network setups?

Issue #33070 stated that they were able to resolve the DNS of a headless service by running the Istio DNS proxy via the `ISTIO_META_DNS_CAPTURE = true` flag. On Istio version 1.11.5 we enabled DNS proxying for both clusters but were still unable to resolve headless service DNS of both forms:1

- `<headless-svc>.<ns>.svc.cluster.local`
- `<pod>.<headless-svc>.<ns>.svc.cluster.local`

It looked like DNS proxying was somewhat working as we could resolve clusterIP services in the other cluster, without a “fake” service being created on the remote cluster. 

The documentation for DNS proxying does not have much detail in regards to the setup for multi-cluster applications, but it does talk a lot about using service entries. Is it the case we need to create service entries for each of the pods in the headless service to fix DNS resolution? and if this is the case are there any examples of this we can refer to?

**Comment by bianpengyuan** [comment]
It is a known limitation that headless does not work across multi networks. Even we were able to resolve the headless name, the routing destination information will still get lost when pass through the cross network gateway.

**Comment by Champ-Goblem** [comment]
Okay, thank you for the answer

**Comment by DamianFekete** [comment]
Story related to https://github.com/istio/istio/pull/32515 (_allow resolving same-network cross-cluster headless services_), but for multi-network: https://github.com/istio/istio/issues/38327 (_Make headless services work across multi-network gateways_)

(Just linking stories as it is hard to see what works and what not, while browsing the documentation, current Github issues.)
