### ISSUE TITLE
External Traffic is not flowing via EGRESS GATEWAY

### ISSUE THREAD

**Issue by Achari-Sumanth** [istio/istio#36745]
### Bug Description

Traffic from our micro service to external service is not flowing via egress gateway.

Our app will be running inside kubernetes cluster with istio-injection enabled. The microservice makes an external request to our host machine (The external service will be running on port 5020 of host machine) [Request by microservice: "http://192.168.1.9:5020/politics/latest" ], here 192.168.1.9 is my host system IP.

[EGRESS_GATEWAY.txt](https://github.com/istio/istio/files/7832578/EGRESS_GATEWAY.txt)

In kiali dashboard, The traffic to external service(ie, logs-svc) is not passing via egress gateway. It is directly flowing from microservice to logs-svc(external service). I need to forward that traffic to egress gateway.

### Version

```
isitoctl version 
client version : 1.12.1
control plane version : 1.12.1
data plane version: 1.12.1(5 proxies)
kubectl version --short
Client Version:v1.22.4
Server Version:v1.22.5+k3s1
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

- [ ] 

- [ ] 

- [ ] 

- [ ] - [ ] Upgrade

- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by bianpengyuan** [comment]
The config is badly formatted. Please correct the format for easy checking.

**Comment by Achari-Sumanth** [comment]
Please verify the EGRESS_GATEWAY.txt file, which is formatted correctly.

**Comment by bianpengyuan** [comment]
The virtual service should match on port 5020 instead of 80 for mesh gateway.

> can you please share any code format to deploy egress gateway which is running as an external service on rest API.

Sorry I don't follow your ask.

**Comment by Achari-Sumanth** [comment]
Yeah i've changed the port and deployed , even though the traffic is not flowing out from the egress gateway and it's showing some unkonwn. please refer to the screenshot below.

[EGRESS_GATEWAY.txt](https://github.com/istio/istio/files/7832790/EGRESS_GATEWAY.txt)


![IstioDashboard](https://user-images.githubusercontent.com/64124889/148635418-22f2779a-c54d-4d34-be5d-a5b6bfb37ac6.PNG)

**Comment by bianpengyuan** [comment]
Envoy access log from the sidecar proxy and egress gateway will be more useful to understand what happened. https://istio.io/latest/docs/tasks/observability/logs/access-log/
