### ISSUE TITLE
gRPC probe test failure

### ISSUE THREAD

**Issue by dddddai** [istio/istio#36757]
Found the error in the tests of 7c6403332f5044f78d8f541ce983066c8357bd90:
```
2022-01-08T03:07:36.412524Z	error	tf	1 error occurred:
error validating data: ValidationError(Deployment.spec.template.spec.containers[1].readinessProbe): 
unknown field "grpc" in io.k8s.api.core.v1.Probe;
if you choose to ignore these errors, turn validation off with --validate=false: 
```
I was thinking it's because the k8s version is lower than 1.23, but the error is still present in [integ-k8s-123_istio_postsubmit](https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-123_istio_postsubmit/1479643587678310400)
I guess we missed some config of the tests?

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
So for the others we need to skip it for old version for sure.

For 1.23 we are using 1.23.0-rc.0. IRC they renamed the field very close to release, maybe we do not have the patch. I will update it

**Comment by howardjohn** [comment]
even with the skip fix it is not enough, it will not gracefully ignore the `FeatureGate` it does not understand. So need a different config file for 1.23 :-(

**Comment by dddddai** [comment]
I see, do you mean something like [this](https://github.com/dddddai/istio/commit/fdf8f3b2c45bb902c8ae879d7cddbf22e7692acd)?
Then [update the config](https://github.com/dddddai/test-infra/commit/7fa6c87f4a70ec834be00b1cf05d1a28772d19d5) in test-infra?

**Comment by howardjohn** [comment]
exactly, thanks!!

**Comment by dddddai** [comment]
No problem :)
