### ISSUE TITLE
How can I get the sidecar duration metric?

### ISSUE THREAD

**Issue by penghuazhou** [istio/istio#36769]
**Describe the feature request**
How can I get the sidecar duration metric?

**Describe alternatives you've considered**
istio_request_duration_milliseconds is contain sidecar duration and workload duration when reporter is source? 

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by zirain** [comment]
do you mean sidecar setup duration?

**Comment by penghuazhou** [comment]
The time it takes for the traffic to enter the sidecar to the time when the traffic leaves the sidecar

for example below，it take 3s for serviceB sidecar.
![image](https://user-images.githubusercontent.com/13001038/148899263-1203dce1-5866-46b6-8639-8ed4fcf7e9be.png)

**Comment by zirain** [comment]
AFAIK, there is no exists metric for this, @douglas-reid do you anything else?
Right now you can get some duration like `%REQUEST_TX_DURATION%`  `%RESPONSE_TX_DURATION%` from access log. full doc is [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators).

**Comment by douglas-reid** [comment]
@zirain while i believe there is are detailed raw timing info available within the proxy, i'm not aware of any direct exposure of pure proxy latency numbers being exposed (relatedly, there are not internal Envoy trace spans emitted). typically, when measuring introduced latency of adding a proxy for perf reasons, frameworks have run tests with and without proxies to get those numbers.

**Comment by penghuazhou** [comment]
What diffrent from %REQUEST_TX_DURATION% and %RESPONSE_DURATION%?

**Comment by penghuazhou** [comment]
@zirain，REQUEST_TX_DURATION、RESPONSE_TX_DURATION is always 0 when I press the side car.

![image](https://user-images.githubusercontent.com/13001038/149305215-283c4317-a75e-486e-8814-108ef1039842.png)

`{"route_name":"default","upstream_cluster":"inbound|1028||","upstream_host":"172.22.128.148:1028","downstream_peer_cert_v_end":null,"upstream_local_address":"127.0.0.6:46603","authority":"bservice:1028","connection_termination_details":null,"method":"POST","start_time":"2022-01-13T09:39:03.388Z","request_tx_duration":0,"downstream_tls_cipher":null,"bytes_sent":2,"request_id":"32eabc95-7d78-9e98-9ce4-954305168d9e","bytes_received":1007,"downstream_tls_version":null,"response_flags":"-","path":"/","protocol":"HTTP/1.1","hostname":"bservice-6f5757bd47-cfhw6","request_duration":0,"trace_id":"2014dda7794d74c4d03de3323263e1db","requested_server_name":null,"response_duration":159,"response_tx_duration":0,"downstream_remote_address":"172.22.128.55:39220","downstream_peer_cert_v_start":null,"istio_policy_status":null,"upstream_service_time":"159","response_code":200,"downstream_local_address":"172.22.128.148:1028","response_code_details":"via_upstream","duration":159}`

**Comment by penghuazhou** [comment]
@zirain can you help me ?

**Comment by zirain** [comment]
`%REQUEST_TX_DURATION%` works fine on my env
```yaml
accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %REQUEST_TX_DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
```

```console
[2022-02-09T09:23:14.534Z] "GET /ip HTTP/1.1" 200 - via_upstream - "-" 0 28 2 2 "-" "curl/7.81.0-DEV" "3cc9fa08-6453-4255-b50f-2d997fe35aa0" "httpbin:8000" "10.244.0.99:80" outbound|8000||httpbin.default.svc.cluster.local 10.244.0.100:40898 10.96.198.0:8000 10.244.0.100:36412 - default
[2022-02-09T09:23:43.787Z] "GET /ip HTTP/1.1" 200 - via_upstream - "-" 0 28 6 5 "-" "curl/7.81.0-DEV" "487d3a2b-15e9-42f1-9fbb-b98685e327fa" "httpbin:8000" "10.244.0.99:80" outbound|8000||httpbin.default.svc.cluster.local 10.244.0.100:42038 10.96.198.0:8000 10.244.0.100:36810 - default

```

**Comment by penghuazhou** [comment]
@zirain, you envoy verion is? 

<img width="717" alt="image" src="https://user-images.githubusercontent.com/13001038/153352740-3791d2ad-b43b-4840-8f94-fdec7e7b8b7d.png">

**Comment by zirain** [comment]
> 

I'm running on istio master branch

```console
root@istiodev:~# k exec -it httpbin-74fb669cc6-6kbp9 -cistio-proxy -- envoy --version

envoy  version: 9385dadba5de0f4018434b5552ab35e68678caed/1.22.0-dev/Clean/RELEASE/BoringSSL

```

**Comment by penghuazhou** [comment]
thanks

**Comment by zirain** [comment]
@penghuazhou can we close this issue?
