### ISSUE TITLE
routing to chaos testing config

### ISSUE THREAD

**Issue by politrons** [istio/istio#36771]
I'm reading `traffic management` documentation https://istio.io/latest/docs/concepts/traffic-management/ and also use `istio` for `chaos testing` https://developers.redhat.com/blog/2018/04/10/istio-chaos-engineering#never_gonna_give_you_up 

I know we can use some headers value to routing traffic for `A B testing`, but what I would like to know, is if I can do the same to return an error in one service or make a delay, as the istio chaos testing provide.

So I can end up making request with header `request-type:chaos`, and for those we will apply the chaos testing yaml config, but not for the rest of request

**Comment by zirain** [comment]
please checkout https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPFaultInjection

**Comment by politrons** [comment]
Thanks, what I really need to know if is possible, is do like the _**CorsPolicy**_ does which is apply the HttpFaultInjection only to some requests that contains a specific header https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy

Do you know any example doc that I can refer to? 

Regards
