### ISSUE TITLE
tcpdump: Couldn't change ownership of savefile

### ISSUE THREAD

**Issue by jingslunt** [istio/istio#36784]
version 1.12 
```
istio-proxy@gg-5c45cfddf-6d76l:/dev$ sudo tcpdump -nn -c 400000 -w nework.cap tcp
tcpdump: Couldn't change ownership of savefile
```

**Comment by zirain** [comment]
> version 1.12
> 
> ```
> istio-proxy@gg-5c45cfddf-6d76l:/dev$ sudo tcpdump -nn -c 400000 -w nework.cap tcp
> tcpdump: Couldn't change ownership of savefile
> ```

you'd better ssh to the node, enter to ns then tcpdump

**Comment by jingslunt** [comment]
> > version 1.12
> > ```
> > istio-proxy@gg-5c45cfddf-6d76l:/dev$ sudo tcpdump -nn -c 400000 -w nework.cap tcp
> > tcpdump: Couldn't change ownership of savefile
> > ```
> 
> you'd better ssh to the node, enter to ns then tcpdump

AKS login ssh fail 
```
kubectl debug node/aks-qwworker-11984806-vmss000009 -it --image=mcr.microsoft.com/aks/fundamental/base-ubuntu:v0.0.1
```

**Comment by Mingmingge** [comment]
@jingslunt it's a bug of 'tcpdump' maybe. see [this](https://bugzilla.redhat.com/show_bug.cgi?id=1015767).

**Comment by jingslunt** [comment]
> tcpdump: Couldn't change ownership of savefile
@Mingmingge It works for me .
```
sudo su -
cd /dev/
cp -a /usr/sbin/tcpdump .
./tcpdump -nn -c 400000 -w istio_proxy_dump.cap tcp and host  
```
