### ISSUE TITLE
Deterministic route names in Envoy when using Gateway API to allow patching

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#36790]
**Describe the feature request**
Patching envoy config at a particular HTTP route level requires matching over a route's name ([EnvoyFilter_RouteMatch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-RouteMatch)). With VirutalService, we can give a name to the route, but such provision is not present for Gateway API's HTTPRoute resource, which makes sense. Istio could potentially add a deterministic name using matching criteria. For example, a route with a match on the `GET` method and `/getToy` path could have a name: `GET/getToy`.

**Describe alternatives you've considered**
An alternative solution would be to allow matching over other fields as well instead of just a route name inside the EnvoyFilter resource.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
I am aware that on the creation of HTTPRoute, Istio internally creates a VirtualService where the name can be injected.

cc @maleck13

**Comment by hzxuzhonghu** [comment]
We can generate a name by some rules internnally, but it is not a good practice for enduser to be aware of istio inner implement.
Prefer to add name to gateway-apis.

cc @howardjohn

**Comment by howardjohn** [comment]
I thought there was a name in the gateway API? Maybe it was not added but
definitely discussed and I think a good addition for other reasons as well.
