### ISSUE TITLE
Metadata exchange double injected causing disruption

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#36796]
### Bug Description

When user upgrade control plane in place from 1.11 to 1.12, since 1.12 control plane injects tcp metadata exchange filter regardless of the version, 1.11 proxy will have TCP Mx filter double injected. When a double injected 1.11 talks to 1.12 proxy (which only have one tcp mx injected), the metadata will leak to the application, because metadata will be sent twice by 1.11 proxy, but only one chunk of metadata will be drained by the 1.12 peer.

### Version

```prose
1.12
```

**Comment by bianpengyuan** [comment]
cc @rolandkool

**Comment by hzxuzhonghu** [comment]
How does that happen?

**Comment by bianpengyuan** [comment]
If the cluster is upgraded from 1.11 to 1.12, 1.11 proxy will be injected twice: one from EnvoyFilter and one from istiod.

**Comment by hzxuzhonghu** [comment]
Thanks, understood

**Comment by hzxuzhonghu** [comment]
Curious, didn't we test upgrade when 1.12 released
