### ISSUE TITLE
How Istio handles DDOS attacks?

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#36798]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
1) How to handle DDOS attacks at Istio control plane? When we have multiple services in cluster and if one service receive more traffic, Istio control plane can get throttled causing harm for other services in same cluster. How to we avoid traffic for one service effecting others as they share same control plane.

2) How to implement Throttling protection? Means, reasonable amount of hits per service are performed and accepted by service. Anything above this threshold should be rejected. How to implement this?

Please share examples how this can be achieved.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ X] Multi Cluster
[ X] Virtual Machine
[ X] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
> When we have multiple services in cluster and if one service receive more traffic

Traffic to the service does not impact the control plane at all

You can configured `PILOT_MAX_REQUESTS_PER_SECOND` env var on Istiod to control rate limit of t he control plane.

**Comment by keerthig9** [comment]
Thanks for the reply. I want to understand solution for DDOS traffic at ingress gateway. 

1) When we get robot traffic for one service, ingress will get overloaded which cause availability issue for all services in cluster. How can we protect ingress gateway from DDOS attacks?

2) What are the Throttling mechanism's issue support?

**Comment by keerthig9** [comment]
Ping

**Comment by bianpengyuan** [comment]
see https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/

**Comment by keerthig9** [comment]
> see https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/

I see we can limit requests per minute for a service, What other configuration Istio supports? like,
1) Can we limit number of concurrent connections from a single IP address?
2) Is it possible to throttle requests based on specific headers?

**Comment by bianpengyuan** [comment]
Those should all available with envoy rate limit filter and service, you can refer to envoy's doc on this.
