### ISSUE TITLE
【istio】send JVM metrics to Collector fail

### ISSUE THREAD

**Issue by NataShare** [istio/istio#36793]
### Bug Description

The POD whose traffic is taken over by sidecar sends GRPC protocol to the service (Skywalking OAP) that is not taken over by Sidecar, but outputs HTTP protocol after Sidecar.  
Sidecar接管流量的pod,向没有sidecar接管的服务（skywalking oap）发送了grpc协议，但经过sidecar后输出了http协议;

### Version

```prose
istio-1.4.10
Skywalking oap 8.8.1
Skywalking agent --->  Skywalking oap  grpc protocol
```

### Additional Information

Skywalking agent --->  Skywalking oap  grpc protocol

**Comment by howardjohn** [comment]
> istio-1.4.10

This has been out of support for over 2 years. Can you upgrade to Istio 1.12 and open again if you still see issues?
