### ISSUE TITLE
Analyze Envoy 1.21 release notes for breaking changes or changes we need

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36808]
https://github.com/envoyproxy/envoy/blob/1091423999411cbab985e0b4cd3253d8715dc71e/docs/root/version_history/current.rst

cc @lambdai

**Comment by howardjohn** [comment]
My thoughts: overall no real action needed

* http: envoy will now proxy 102 and 103 headers from upstream, though as with 100s only the first 1xx response headers will be sent. This behavioral change by can temporarily reverted by setting runtime guard envoy.reloadable_features.proxy_102_103 to false.

Given our previous issues around this may be worth investigating but likely is safe

* perf: added support for Perfetto performance tracing.

Could be interesting feature to add when we are profiling, but no immediate action needed

* stateful session http filter: added :ref:`stateful session http filter <config_http_filters_stateful_session>`.

Could be useful option in DestinationRule

* tls: :ref:`match_subject_alt_names <envoy_v3_api_field_extensions.transport_sockets.tls.v3.CertificateValidationContext.match_subject_alt_names>` has been deprecated in favor of the :ref:`match_typed_subject_alt_names <envoy_v3_api_field_extensions.transport_sockets.tls.v3.CertificateValidationContext.match_typed_subject_alt_names>`.

Should migrate but not time sensitive. Probably better to wait so we don't need split branches for old code

**Comment by stevenctl** [comment]
@lambdai  @yangminzhu can you confirm that we are safe here?

**Comment by lambdai** [comment]
Useful access log:
http: added timing information about upstream connection and encryption establishment to stream info. These can currently be accessed via custom access loggers.

There is risky configuration via EnvoyFilters
* router: added support for the [:ref:`config_http_conn_man_headers_x-forwarded-host`](https://github.com/envoyproxy/envoy/blob/1091423999411cbab985e0b4cd3253d8715dc71e/docs/root/version_history/current.rst#id75) header. 

May impact istio sidecar API user who overrides existing listeners (I didn't test)
* listener: fixed issue where more than one listener could listen on the same port if using reuse port, thus randomly accepting connections on different listeners. This configuration is now rejected.


Istio users who upgrade skipping one version need to look at the of of the long changes list [here](https://github.com/envoyproxy/envoy/blob/1091423999411cbab985e0b4cd3253d8715dc71e/docs/root/version_history/current.rst#removed-config-or-runtime)

**Comment by yangminzhu** [comment]
the ext_authz changes looks good to me, they are mostly just bug fixes.
