### ISSUE TITLE
1.13 blocker: update centos LLVM to v12

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36811]
https://github.com/istio/proxy/pull/3657 blocked I assume because of https://github.com/istio/tools/blob/6678e77714f10fcdcc875547feff812e3952deaf/docker/build-tools/Dockerfile.centos#L32 is too old.

The getenvoy sources for llvm are no longer updated

**Comment by stevenctl** [comment]
We will have to build this ourselves. I have a build running on a relatively beefy GCE instance. When that finishes I will push to istio-testing storage bucket and publish instructions in tools repo.

**Comment by ericvn** [comment]
This should now be fixed.
