### ISSUE TITLE
 Issue with high CPU usage by istiod pods at K8s cluster with big number of pods

### ISSUE THREAD

**Issue by Dima-Diachenko** [istio/istio#36827]
### Bug Description

Hi guys! I hope you can help me with this... any recommendations will be useful!

We using Istio in Azure Kubernetes Service, deployed by Helm. 

I detected periodical _`Readiness probe fails`_ for **istiod**- pods. I dived into this and observed strange things. I will provide you with more details. 
Usually, all looks good:
```
kubectl top po -n istio-system -l app=istiod --sort-by=cpu                                     

NAME                     CPU(cores)   MEMORY(bytes)
istiod-5bf667fdf-f8wck   173m         1754Mi
istiod-5bf667fdf-2rw5s   168m         1203Mi
istiod-5bf667fdf-h8j2d   159m         2257Mi
istiod-5bf667fdf-pmsnq   148m         1210Mi
istiod-5bf667fdf-gqtmp   78m          2041Mi
istiod-5bf667fdf-9mxdk   73m          2347Mi
istiod-5bf667fdf-m5ql7   23m          2469Mi
```
 But one time per approx 5-7 minutes we have a huge CPU usage increasing by **pilot-discovery** process inside **istiod** pods to ~500% in each pod: 

```
NAME                     CPU(cores)   MEMORY(bytes)
istiod-5bf667fdf-pmsnq   5601m        2299Mi
istiod-5bf667fdf-gqtmp   5359m        3132Mi
istiod-5bf667fdf-m5ql7   5348m        3603Mi
istiod-5bf667fdf-9mxdk   5283m        3473Mi
istiod-5bf667fdf-h8j2d   5016m        3426Mi
istiod-5bf667fdf-f8wck   4739m        2908Mi
istiod-5bf667fdf-2rw5s   4680m        2349Mi
```
Limits for these pods are not specified. We used this autoscale config:
```   
 pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 10
```
In "normal" mode, HPA kept 3-4 replicas but increased the number to 10 (maximum). Almost every pod eats >4000m CPU. So I set a number of replicas to fixed 7. Does not matter. After the CPU over-usage is finished it drops not-needed replicas. 

Here are logs of the **isiod** pods - I found a lot of similar following stings:
```
# I replaced pod names by <some-node> placeholder
{"level":"info","time":"2022-01-13T17:30:10.409853Z","scope":"ads","msg":"EDS: PUSH request for node:<some-node>-5858d7b455-tpc8q.int2 resources:757 size:275.3kB empty:0 cached:757/757"}
{"level":"info","time":"2022-01-13T17:30:10.475309Z","scope":"ads","msg":"LDS: PUSH request for node:<some-node>-5858d7b455-tpc8q.int2 resources:424 size:1.2MB"}
{"level":"info","time":"2022-01-13T17:30:10.484795Z","scope":"ads","msg":"NDS: PUSH request for node:<some-node>5858d7b455-tpc8q.int2 resources:1 size:70.6kB"}
{"level":"info","time":"2022-01-13T17:30:10.962285Z","scope":"ads","msg":"RDS: PUSH request for node:<some-node>-5858d7b455-tpc8q.int2 resources:251 size:882.7kB"}
{"level":"info","time":"2022-01-13T17:30:11.392550Z","scope":"ads","msg":"ADS: \"10.11.3.196:46610\" <some-node>-7ddc8c9fc5-96tfh.int2-260 terminated rpc error: code = Canceled desc = context canceled"}
{"level":"info","time":"2022-01-13T17:30:16.295609Z","scope":"ads","msg":"ADS: new connection for node:<some-node>-1.staging-463"}
{"level":"info","time":"2022-01-13T17:30:16.334903Z","scope":"ads","msg":"CDS: PUSH request for node:<some-node>-1.staging resources:786 size:806.8kB"}
{"level":"info","time":"2022-01-13T17:30:16.339184Z","scope":"ads","msg":"EDS: PUSH request for node:<some-node>-1.staging resources:757 size:275.3kB empty:0 cached:757/757"}
{"level":"info","time":"2022-01-13T17:30:16.394637Z","scope":"ads","msg":"LDS: PUSH request for node:<some-node>-1.staging resources:424 size:1.2MB"}
{"level":"info","time":"2022-01-13T17:30:16.398387Z","scope":"ads","msg":"NDS: PUSH request for node:<some-node>-1.staging resources:1 size:70.6kB"}
```
or from another pod:
```
{"level":"info","time":"2022-01-13T17:44:08.617668Z","scope":"ads","msg":"ADS: new connection for node:<some-node>-5bbd8f7bd5-5944n.dev10-3162"}
{"level":"info","time":"2022-01-13T17:44:08.658817Z","scope":"ads","msg":"CDS: PUSH request for node:<some-node>-5bbd8f7bd5-5944n.dev10 resources:785 size:805.6kB"}
{"level":"info","time":"2022-01-13T17:44:08.662979Z","scope":"ads","msg":"EDS: PUSH request for node:<some-node>-5bbd8f7bd5-5944n.dev10 resources:756 size:275.1kB empty:0 cached:756/756"}
{"level":"info","time":"2022-01-13T17:44:08.720455Z","scope":"ads","msg":"LDS: PUSH request for node:<some-node>-5bbd8f7bd5-5944n.dev10 resources:423 size:1.2MB"}
{"level":"info","time":"2022-01-13T17:44:08.725569Z","scope":"ads","msg":"NDS: PUSH request for node:<some-node>-5bbd8f7bd5-5944n.dev10 resources:1 size:70.5kB"}
{"level":"info","time":"2022-01-13T17:44:09.251447Z","scope":"ads","msg":"RDS: PUSH request for node:<some-node>-5bbd8f7bd5-5944n.dev10 resources:250 size:882.1kB"}
{"level":"info","time":"2022-01-13T17:44:10.084486Z","scope":"ads","msg":"ADS: new connection for node:<some-node>-78747fd85-xx6bk.staging-3163"}
{"level":"info","time":"2022-01-13T17:44:10.118314Z","scope":"ads","msg":"CDS: PUSH request for node:<some-node>-78747fd85-xx6bk.staging resources:785 size:805.6kB"}
{"level":"info","time":"2022-01-13T17:44:10.121358Z","scope":"ads","msg":"EDS: PUSH request for node:<some-node>-78747fd85-xx6bk.staging resources:756 size:275.1kB empty:0 cached:756/756"}
{"level":"info","time":"2022-01-13T17:44:10.138475Z","scope":"ads","msg":"ADS: \"10.11.16.86:47952\" <some-node>f9dc7789-zfz62.int2-2972 terminated rpc error: code = Canceled desc = context canceled"}
{"level":"info","time":"2022-01-13T17:44:10.168960Z","scope":"ads","msg":"LDS: PUSH request for node:<some-node>-78747fd85-xx6bk.staging resources:423 size:1.2MB"}
{"level":"info","time":"2022-01-13T17:44:10.171915Z","scope":"ads","msg":"NDS: PUSH request for node:<some-node>-78747fd85-xx6bk.staging resources:1 size:70.5kB"}
{"level":"info","time":"2022-01-13T17:44:10.569892Z","scope":"ads","msg":"RDS: PUSH request for node:<some-node>-78747fd85-xx6bk.staging resources:250 size:881.7kB"}
```
Sometimes present ` terminated rpc error: code = Canceled desc = context canceled ` errors but not much. 
 
So it’s PUSH of LDS, RDS, EDS, CDS, etc actions but with a big data size (at about 1MB).

Can this be related to the number of pods that we run? Because we have 1550+? Or can be the root cause in a big number of the namespaces? Or is it expected behavior and such more CPU/RAM use is OK (but how to handle it)? 

I'm ready to answer any questions and provide any info. Will be very appreciative for help! 
Thanks in advance!

### Version

```prose
k version --short
Client Version: v1.23.1
Server Version: v1.21.7

istioctl version
client version: 1.12.1
control plane version: 1.11.2
data plane version: 1.11.2 (1545 proxies)
```

**Comment by bianpengyuan** [comment]
Sidecar resource will be helpful: https://karlstoney.com/2020/10/03/istio-at-scale-sidecar/ Although it is seems unexpected that 1500 proxies will cause such high CPU usage. What happens in your cluster every 5-7 minutes? service update or any resource update?

**Comment by bianpengyuan** [comment]
It would be great if you collect CPU profile from one of the istiod pod during peak for analysis: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#cpu

**Comment by Dima-Diachenko** [comment]
@bianpengyuan , thanks for your attention! Sorry for the delay in answer. 

> ... What happens in your cluster every 5-7 minutes? service update or any resource update?

I thought about it. Nothing special from the services side. 
But We have a lot of deployments, a few hundred releases each day (this is dev K8s cluster), and execution of the cronjob every ~10 minutes. 50% pods deploying with istio injection. 
Want to clarify - does deployment of the pods without `sidecar.istio.io/inject=true` affect the **istiod**? 

> It would be great if you collect CPU profile from one of the **istiod** pod during peak for analysis: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#cpu

Sure thing! I took 3 profiles while CPU peeks were observed. You can find results [here](https://github.com/Dima-Diachenko/share).

One more question please - I read about concurrency setting on proxy - maybe it can help in my case?

**Comment by Dima-Diachenko** [comment]
And can I ask does istio 1.12 release has some improvements in performance for such case? Is it makes sense to do an update (since we use 1.11now)?

**Comment by bianpengyuan** [comment]
Looks like most of time is spend at route. Probably you have a large set of virtual services? And upgrading to 1.12 would actually help since we added rds cache: https://github.com/istio/istio/pull/34243.

> Want to clarify - does deployment of the pods without sidecar.istio.io/inject=true affect the istiod?

Yeah, it could, but number of pods is not the dominator in your case.

**Comment by Dima-Diachenko** [comment]
@bianpengyuan thank you again! 
So, in my case I should:
- Implement sidecars
- Update to 1.12

I think I got answers to my question. Thank you for your support, I'll close my issue.
