### ISSUE TITLE
Configure Istio to accept HTTP 1.0 Request

### ISSUE THREAD

**Issue by danilorsilva** [istio/istio#36837]
Hello, i am trying to config ISTIO to HTTP 1.0 requests without success.

Istio version: 1.11.2

What i try to do:

gateways:
  istio-ingressgateway:
    env:
      ISTIO_META_HTTP10: '"1"'

Any can help me please?

**Comment by bianpengyuan** [comment]
If you check env var of ingressgateway, was `ISTIO_META_HTTP10` added there? Also does `HTTP10` present in the gateway config dump? kubectl exec $POD -c istio-proxy -- curl 'localhost:15000/config_dump' > config_dump.json

**Comment by danilorsilva** [comment]
I will check it and let you know @bianpengyuan , thank you so much.

**Comment by danilorsilva** [comment]
I have checked the dump and i see "\"1\"", so i removed a extra "" and everything works fine"

Before:
env:
ISTIO_META_HTTP10: '"1"'

After:
env:
ISTIO_META_HTTP10: "1"

Thanks @bianpengyuan ! I only found this because of dump! Thanks!
