### ISSUE TITLE
readiness probe failed

### ISSUE THREAD

**Issue by bahmanbs** [istio/istio#36856]
### Bug Description

Name:         istio-ingressgateway-65866cff67-tl8qf
Namespace:    istio-system
Priority:     0
Node:         node1/**********
Start Time:   Mon, 17 Jan 2022 16:50:36 +0330
Labels:       app=istio-ingressgateway
              chart=gateways
              heritage=Tiller
              install.operator.istio.io/owning-resource=unknown
              istio=ingressgateway
              istio.io/rev=default
              operator.istio.io/component=IngressGateways
              pod-template-hash=65866cff67
              release=istio
              service.istio.io/canonical-name=istio-ingressgateway
              service.istio.io/canonical-revision=latest
              sidecar.istio.io/inject=false
Annotations:  cni.projectcalico.org/containerID: 0b214410cd7d9747c1d4422c0fe6751b8a73dbd652f1021f74aa296e4166b0da
              cni.projectcalico.org/podIP: 10.233.90.11/32
              cni.projectcalico.org/podIPs: 10.233.90.11/32
              kubectl.kubernetes.io/restartedAt: 2022-01-17T16:20:36+03:00
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/inject: false
Status:       Running
IP:           10.233.90.11
IPs:
  IP:           10.233.90.11
Controlled By:  ReplicaSet/istio-ingressgateway-65866cff67
Containers:
  istio-proxy:
    Container ID:  containerd://00bb121020510767383d94779ee9320cef13cf48e02d0f46f56d2645ecda5175
    Image:         docker.io/istio/proxyv2:1.12.1
    Image ID:      docker.io/istio/proxyv2@sha256:4704f04f399ae24d99e65170d1846dc83d7973f186656a03ba70d47bd1aba88f
    Ports:         15021/TCP, 8080/TCP, 8443/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
    State:          Running
      Started:      Mon, 17 Jan 2022 16:50:37 +0330
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                   third-party-jwt
      PILOT_CERT_PROVIDER:          istiod
      CA_ADDR:                      istiod.istio-system.svc:15012
      NODE_NAME:                     (v1:spec.nodeName)
      POD_NAME:                     istio-ingressgateway-65866cff67-tl8qf (v1:metadata.name)
      POD_NAMESPACE:                istio-system (v1:metadata.namespace)
      INSTANCE_IP:                   (v1:status.podIP)
      HOST_IP:                       (v1:status.hostIP)
      SERVICE_ACCOUNT:               (v1:spec.serviceAccountName)
      ISTIO_META_WORKLOAD_NAME:     istio-ingressgateway
      ISTIO_META_OWNER:             kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
      ISTIO_META_MESH_ID:           cluster.local
      TRUST_DOMAIN:                 cluster.local
      ISTIO_META_UNPRIVILEGED_POD:  true
      ISTIO_META_CLUSTER_ID:        Kubernetes
    Mounts:
      /etc/istio/config from config-volume (rw)
      /etc/istio/ingressgateway-ca-certs from ingressgateway-ca-certs (ro)
      /etc/istio/ingressgateway-certs from ingressgateway-certs (ro)
      /etc/istio/pod from podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w2wbq (ro)
      /var/run/secrets/tokens from istio-token (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  true
  ingressgateway-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-certs
    Optional:    true
  ingressgateway-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-ca-certs
    Optional:    true
  kube-api-access-w2wbq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  113s                 default-scheduler  Successfully assigned istio-system/istio-ingressgateway-65866cff67-tl8qf to node1
  Normal   Pulled     113s                 kubelet            Container image "docker.io/istio/proxyv2:1.12.1" already present on machine
  Normal   Created    113s                 kubelet            Created container istio-proxy
  Normal   Started    113s                 kubelet            Started container istio-proxy
  Warning  Unhealthy  74s (x22 over 112s)  kubelet            Readiness probe failed: Get "http://10.233.90.11:15021/healthz/ready": dial tcp 10.233.90.11:15021: connect: connection refused

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
data plane version: none
```

### Additional Information

✔ Istio core installed                                                                                                                 
✔ Istiod installed                                                                                                                     
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
  Deployment/istio-system/istio-ingressgateway (containers with unready status: [istio-proxy])
- Pruning removed resources                                                                                                            Error: failed to install manifests: errors occurred during operation

when installing istio using istioctl install this error was happened

how to solve it?

**Comment by zirain** [comment]
can you share logs from `istiod` and `ingressgatway` pod?

**Comment by bahmanbs** [comment]
i removed the cluster installed by <b>kubespray</b> and installed it using <b>kubeadm</b> again, now everything works.
probably that issue was made by kubespray
