### ISSUE TITLE
Support to disable traffic for WorkloadEntry

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#36865]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
WorkloadEntry can be used to represent external mesh VIP and select by ServiceEntry. There are some user cases that we need to disable traffic to a WorkloadEntry:
1. On purpose region/az exit, for example we need to disable the traffic to a specific VIP(WorkloadEntry) in one region/az.
2. AZ failover/Disaster recover. Let's say if all the backend servers behind a external VIP go down, we need to disable the traffic to that VIP(WorkloadEntry).

The capability to disable VIP traffic is very important for the traffic management, while currently Workload spec doesn't support based on current spec and there are some options for that:
1. Disable WorkloadEntry traffic if its weight is 0. As per upstream, the endpoint minimum weight should be 1 https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto,  so Istio will configure weight 1 for the Endpoint if the WorkloadEntry weight is 0, we can leverage on this 0 weight and set the corresponding lbEndpoint HealthStatus to be `HealthStatus_UNHEALTHY` to achieve  this. 
```
// GetLoadBalancingWeight returns the weight for this endpoint, normalized to always be > 0.
func (ep *IstioEndpoint) GetLoadBalancingWeight() uint32 {
	if ep.LbWeight > 0 {
		return ep.LbWeight
	}
	return 1
}

```
2. Introduce a new filed `adminState` in WorkloadEntry, it will also set the corresponding lbEndpoint HealthStatus to be `HealthStatus_UNHEALTHY`
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details-svc
spec:
  serviceAccount: details-legacy
  address: 2.2.2.2
  adminState: Down
  labels:
    app: details-legacy
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Curious why do you create WLE then

**Comment by howardjohn** [comment]
Why not just delete it?

**Comment by shonecyx** [comment]
> Why not just delete it?

@howardjohn  The intention to disable traffic(for region exit) and delete WLE is different although we can leverage deleting WLE to achieve this.  
Envoy supports to disable an Endpoint in a Cluster through HealthStatus, that's why the minimum load_balancing_weight is 1.  Also in hardware loadbalancers we have the capability to disable VIP traffic not by deleting it. 

Introducing a new filed `adminState` looks like to be more elegant which exactly captures this intention.

**Comment by hzxuzhonghu** [comment]
The original semantic is to allow not explicitly specify weight, just like k8s endpoint api semantic.
There are some workarounds can be used atm, such as
1.  You can change the labels not to be selected
2.  Make use of subsets, and only transport traffic to one subset.

**Comment by shonecyx** [comment]
> The original semantic is to allow not explicitly specify weight, just like k8s endpoint api semantic. There are some workarounds can be used atm, such as
> 
> 1. You can change the labels not to be selected
> 2. Make use of subsets, and only transport traffic to one subset.

@hzxuzhonghu The weight is good if we want to route different ratio of traffic to different endpoints and Envoy also supports it in the Endpoing `load_balancing_weight`. The problem is the semantic of weight 0 is ambiguous between the weighted base routing and the WLE.

We can have some workaround for this as you mentioned above, or even create an annotation like `wle.istio.io/adminState: Down"  and implement this in house, but I believe this is a valid/common request since from Envoy perspective it's supported, just need to support it in control plane.

**Comment by hzxuzhonghu** [comment]
The tricky point is we did not require user must provide a non zero weight. To elaborate a little bit, we used proto3, which does not support pointer api type, so we could not distinguish 0 or unset.

**Comment by shonecyx** [comment]
> The tricky point is we did not require user must provide a non zero weight. To elaborate a little bit, we used proto3, which does not support pointer api type, so we could not distinguish 0 or unset.

@hzxuzhonghu  Then looks like option 2 is better, introduce the new filed `adminState: Down/Up` in WLE doesn't need to differentiate 0 or unset and it aligns with Envoy LbEndpoint `health_status` .

**Comment by hzxuzhonghu** [comment]
The option 2 is based on VS and DestinationRule's subset. What do you mean by `new filed adminState: Down/Up in WLE `

**Comment by sudhi-vm** [comment]
Since the intention is to set the HealthStatus of the endpoint, perhaps the field name `HealthStatus` in `WorkloadEntry` is more appropriate. The proposal is to introduce this new field and set the `health_status` of the endpoint.

**Comment by shonecyx** [comment]
A new field healthStatus in WorkloadEntry is also good. 
@hzxuzhonghu  The intention of this field is to allow admin to manage the heath status of a WorkloadEntry. For example we can temporarily mark the WLE unhealthy for maintenance or disable traffic to that WLE without deleting it.

**Comment by shonecyx** [comment]
Thanks @howardjohn, this is like the active health check and I think it's coupled with WorkloadGroup readinessProbe. And we are looking for a capability that we can both leverage on readinessProbe and on-demand mark a WLE unhealthy.

I created another issue try to describe it as a common requirement.

**Comment by shonecyx** [comment]
Istio does support to mark WLE unhealthy and the contract is WLE annotation

proxy.istio.io/health-checks-enabled: "true"
And manipulate WLE healthy status to be False:

status:
  conditions:
  - lastProbeTime: "2019-12-26T22:06:34Z"
    lastTransitionTime: "2019-12-26T22:06:34Z"
    message: 'Code 500: VIP Unhealthy'
    reason: unhealthy
    status: "False"
    type: Healthy
It's decoupled with readinessProbe and we can have external controller to mark the status unhealthy to disable traffic or do readiness check.
