### ISSUE TITLE
TestRefreshAndPurge failed in circleci for an unrelated change

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#3686]
flaky unit test in mixer/adapter/list/list_test.go

```
=== RUN   TestRefreshAndPurge
--- FAIL: TestRefreshAndPurge (0.00s)
	env.go:97: Fetching list from http://127.0.0.1:33171
	env.go:97: Installing updated list with 1 entries
	env.go:97: Purging list due to inability to refresh it in time
	env.go:97: Fetching list from http://127.0.0.1:33171
	list_test.go:555: Got success, expected error
```

https://circleci.com/gh/istio/istio/35394

**Comment by GregHanson** [comment]
cc @mandarjog

**Comment by mandarjog** [comment]
Also found here.  https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3931/istio-unit-tests/1455/

**Comment by cmluciano** [comment]
I've tried reproducing this locally a few times and it passed every time. I also don't see it highlighted in the build insights in circle.
