### ISSUE TITLE
Is istioctl precheck messages [IST-0136] valid?

### ISSUE THREAD

**Issue by haani-niyaz** [istio/istio#36860]
### Bug Description

While upgrading istio from v1.11 to v1.12 the following `IST-0136` info message is displayed:

```
traffic.sidecar.istio.io/excludeInboundPorts  is part of an alpha-phase feature and may be incompletely supported.
traffic.sidecar.istio.io/includeInboundPorts  is part of an alpha-phase feature and may be incompletely supported.
traffic.sidecar.istio.io/includeOutboundIPRanges  is part of an alpha-phase feature and may be incompletely supported.
sidecar.istio.io/interceptionMode  is part of an alpha-phase feature and may be incompletely supported.
```

The settings appear to be present in v1.9, v1.10 and v1.11 but is only flagged in the `istioctl x precheck` for v1.12.

The docs for code says:

> The Istio team recommends using this analysis to be aware of your use of Alpha maturity features before moving workloads to production clusters.

https://istio.io/latest/docs/reference/config/analysis/ist0136/

The annotations were never explicitly set but the default value is applied to every sidecar proxy. 

I assume it can be ignored and the precheck reports all alpha features (even the ones set by default)? 

This [issue](https://github.com/istio/istio/issues/30405) suggests it was removed from the `istioctl analyze` output.

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
```

**Comment by howardjohn** [comment]
cc @therealmitchconnors 

This can be ignored in this case. I thought we filtered out default things,but perhaps not (or there is some issue)
