### ISSUE TITLE
Can't exclude inbound/outbound port on virtual machines

### ISSUE THREAD

**Issue by fiftoine** [istio/istio#36870]
### Bug Description

I have VMs that need to join a mesh but once I install the istio sidecar RPM (alongside istio files output from the istioctl workloadentry configure command) I directly loose SSH connection on the VM.

I know that you can exclude inbound/outbound ports from sidecar using annotations on PODs.

But there is no way to set those on VMs

Using Helm charts (from the github repo) to install Istio

### Version

```prose
$ istioctl version
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (14 proxies)
$ kubectl version --short
Client Version: v1.15.3
Server Version: v1.21.2-eks-06eac09
```

**Comment by howardjohn** [comment]
You can set `ISTIO_LOCAL_EXCLUDE_PORTS`. But port 22 is already excluded by default

**Comment by fiftoine** [comment]
Reading the code of the istioctl x workload entry configure command, it overrides the exluded ports and there is no way to set customize them

https://github.com/istio/istio/blob/master/istioctl/cmd/workload.go#L334-L343
