### ISSUE TITLE
plese provide security CVE's and Release details to github's release page

### ISSUE THREAD

**Issue by nobletrout** [istio/istio#36872]
**Describe the feature request**
the easiest way to track new releases in a normalized way for opensource products is to leverage github's RSS feeds for releases, like this:

`https://github.com/istio/istio/releases.atom`

However, the istio releases only contain a link to a blog post discussing the release, and morever it sometimes requires even further clickthrough's to find CVE's or assorted security bulletins related to releases.

Please include changelog and highlights for isitio releases in the git released tag.

**Describe alternatives you've considered**
I've tried looking through the istio.io repo to see if it's easily tracked for this information, but unfortunately due to the structure of the site, it's not feasible looking.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
We do publish security builtin on https://github.com/istio/istio/security/advisories now. These can be watched, although not sure about a RSS feed.

One thing I was not clear on is why clicking a link in the description is an issue? This is common in many open source projects.

**Comment by nobletrout** [comment]
I'm trying to setup a common notification feed of my most critical assets and am leveraging RSS feeds for github releases as a  means of a quick single source of data to take action.

for example, check out grafanan's releases:

https://github.com/grafana/grafana/releases

if you are using slack, you can easily subscribe to new releases and quickly see if there are any security concerns

**Comment by howardjohn** [comment]
We do report them on https://github.com/istio/istio/security/advisories. Is that not accessible through any feeds?
