### ISSUE TITLE
Istio operator is broken with access denied

### ISSUE THREAD

**Issue by jackalsh** [istio/istio#36886]
### Bug Description

In the new 1.12.1 Istio version deployed with Control Plane CR there are missing role.
Probably related to new Wasm API added. 

istiod pods are unable to start with following error:
` error    watch error in cluster Kubernetes: failed to list *v1alpha1.WasmPlugin: wasmplugins.extensions.istio.io is forbidden: User "system:serviceaccount:istio-system:istiod-service-account" cannot list resource "wasmplugins" in API group "extensions.istio.io" at the cluster scope`

Following fixes the issue:
Manually adding the rule to istiod-istio-system ClusterRole.
`rules:
  - verbs:
  - get
  - list
  - watch
  - update
  - patch
apiGroups:
  - extensions.istio.io
resources:
  - wasmplugins`

Reference: https://github.com/istio/istio/blob/32abef6667f8a6a70d92caaea71f07e33235885c/manifests/charts/base/files/gen-istio-cluster.yaml#L6397

As I understand this role is deprecated, so you probably need to add it here: https://github.com/istio/istio/blob/32abef6667f8a6a70d92caaea71f07e33235885c/manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml#L12

### Version

```prose
All Istio tools of version 1.12.1. Latest released version at this point.
```

**Comment by jackalsh** [comment]
Just figured out that new version was released today 1.12.2.
However, this bug is not fixed there as well

**Comment by bianpengyuan** [comment]
We should have the needed cluster role at https://github.com/istio/istio/blob/32abef6667f8a6a70d92caaea71f07e33235885c/manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml#L23. Would you mind to give more details on how you perform install exactly and what does your ControlPlane resource look like?

**Comment by dsielert** [comment]
I received this error as well installing istio with istioctl and trying to change options after installation..

**Comment by bianpengyuan** [comment]
@dsielert is this transient? What does the `istiod` clusterrole look like?
