### ISSUE TITLE
feat: support additional label to distinguish clusters/meshes besides standard labels

### ISSUE THREAD

**Issue by Xunzhuo** [istio/istio#36909]
**Describe the feature request**

In multi-clusters and multi-meshes scenarios, to distinguish mesh/cluster, additional labels are useful.

Scenario like this:

![image](https://user-images.githubusercontent.com/48784001/150326298-b2caa736-71c0-40ea-8b9c-4c38dfa14c6b.png)

If I use one prometheus to recieve metrics from a couple of meshes/clusters, metrics will be mixed up together.

**Describe alternatives you've considered**

ADD two labels:
+ cluster: the unique user cluster id
+ mesh: the unique mesh id

**Affected product area (please put an X in all that apply)**

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

- [x] Multi Cluster
- [ ] Virtual Machine
- [x] Multi Control Plane

**Comment by Xunzhuo** [comment]
Thanks @zirain , this should work, we can also add additional labels in stats filter. There are many ways to make this happen. But I am just proposing these labels to be a standard.

**Comment by bianpengyuan** [comment]
At least for cluster, I think we should already have destination and source cluster as first class labels? https://istio.io/latest/docs/reference/config/metrics/#labels

**Comment by Xunzhuo** [comment]
True, but I do not know if source/destination cluster is a unique id? And how about for istio control plane, it seems like missing that dimension.

**Comment by bianpengyuan** [comment]
> True, but I do not know if source/destination cluster is a unique id?

It is the same cluster ID you specified via the mesh config.

> how about for istio control plane, it seems like missing that dimension.

How would you like to label control plane metrics with cluster? It is normal that a control plane could serve multiple clusters.

**Comment by Xunzhuo** [comment]
> How would you like to label control plane metrics with cluster? It is normal that a control plane could serve multiple clusters.
In some scenarios, one prometheus will serve multi-control-plane, if we do not have label like `mesh id`, how do we distinguish the metrics from which control-plane exactly?

**Comment by bianpengyuan** [comment]
Do you deploy control plane at different namespaces? you can probably distinguish with pod namespace labels, which should be added by default when prometheus scrapes.

**Comment by Xunzhuo** [comment]
Control plane deploys in different clusters with the same namespace and separate with the user cluster in different VPCs.

**Comment by bianpengyuan** [comment]
Probably distinguish with pod labels? IIRC prometheus will automatically attach pod labels to the scraped time series.
