### ISSUE TITLE
Provide the ability to load tls cert volume and parameters for the pilot deployment for pilot.

### ISSUE THREAD

**Issue by SpectralHiss** [istio/istio#36916]
**Describe the feature request**
Need to be able to add extraVolumes, extraVolumemounts and arguments to pilot when using the helm chart installation. (also within Redhat Service Mesh context which leverages that).
This is to load a certificate to pilot from different Kubernetes secrets (one for tls cert and one for a root of trust certificate).

This could work for example with keys:
"pilot.extraVolumes"
"pilot.extraVolumeMounts"
and 
"pilot.extraArgs"

These will be loaded as expected as many other charts typically do.

**Describe alternatives you've considered**
It is not possible for us to use overlays or the IstioOperator in this context, this is what we'd typically do in vanilla istio installations, for example: https://github.com/cert-manager/istio-csr/blob/main/hack/istio-config-1.10.0.yaml

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This is for adding support for a certificate solution to RedHat ServiceMesh, their operator leverages the helm installation method but we have no way to set required flags.

Happy to go for an alternative or direct approach to load these arguments, but I think these should be generally useful, also can submit a PR with what should be a relatively straightforward implementation.

**Comment by keithmattix** [comment]
+1 this is a blocker for my org because [istio-csr](https://github.com/cert-manager/istio-csr) depends on this functionality to use cert-manager as a CA instead of Citadel

**Comment by SpectralHiss** [comment]
The approach changed after deliberation with @costinm to now load from the default location,
new PR with the details (still WIP): https://github.com/istio/istio/pull/39375
