### ISSUE TITLE
tcp probes being rewritten as http probes

### ISSUE THREAD

**Issue by Sabyasachi2k** [istio/istio#36941]
### Bug Description

So we have TCP startup probe for our deployment and it is being rewritten as a http probe with a random url to hit. this is causing our apps to be shutdown and restarted continuosly

here it is on the deployment level
startupProbe:
          failureThreshold: 3
          tcpSocket:
            port: 3306
          timeoutSeconds: 3
          periodSeconds: 10
          initialDelaySeconds: 10

being rewritten on the pod level as

startupProbe:
          failureThreshold: 3
          http:
            path: /<random path>
            port: 15020
          timeoutSeconds: 3
          periodSeconds: 10
          initialDelaySeconds: 10

we have the following annotations
  sidecar.istio.io/rewriteAppHTTPProbers": "true"

If I make it explicitly false
then the tcp trace is preserved but now the readiness and liveliness fail because the rewrite is not done!!

### Version

```prose
istio version: 1.12.2

kubectl version
Client Version: v1.21.5
Server Version: v1.20.11-gke.1300
```

**Comment by bianpengyuan** [comment]
The path is not random, it should be rewritten to `/app-health/<container-name>/startupz`, which will be handled by istio proxy. Do you trim the url path when creating the issue? Or is it really rewritten to `/` at your pod?

**Comment by Sabyasachi2k** [comment]
you are right it does get written to that specific URL.  I had given the angular placeholder without the code markup and it was truncated. so the behaviour is expected and internally it tries to connect to the specific port via tcp as given in the config?

**Comment by bianpengyuan** [comment]
Yeah it is expected, istio-proxy will perform the same tcp start up check as kubelet, and pass the result back to kubelet. If you think it is not because of your app, the log from istio proxy container might be useful to diagnose.
