### ISSUE TITLE
X-Forwarded-Client-Cert not showing up in ingressgateway debug logs

### ISSUE THREAD

**Issue by pitiwari** [istio/istio#36980]
I am trying to enable X-Forwarded-Client-Cert  but i cant see it in ingressgateway logs. I can see X-Forwarded-Client-Cert  in the logs of the application service but there subject name is name is not there so debugging that by seeing what did  ingressgateway got in the request. Is there any specific setting i need to do for X-Forwarded-Client-Cert to appear in ingressgateway logs ?  

istioctl version --remote
client version: 1.11.4
control plane version: 1.12.2
data plane version: 1.12.2 (20 proxies), 1.11.4 (3 proxies)

**Comment by bianpengyuan** [comment]
You can customer access log as needed with either telemetry api or mesh config: https://istio.io/latest/docs/tasks/observability/logs/access-log/#using-telemetry-api Does this fit your need?

**Comment by pitiwari** [comment]
> You can customer access log as needed with either telemetry api or mesh config: https://istio.io/latest/docs/tasks/observability/logs/access-log/#using-telemetry-api Does this fit your need?


access logs are enabled but value of X-Forwarded-Client-Cert is showing as "-" , after enabling debug logs in gw i see this header is not there and thats why its value is coming as "-". Trying to find out if any special configuration is needed for X-Forwarded-Client-Cert  to show up in the debug logs of the gw, other x-forwarded-for* headers are there in the debug logs

**Comment by bianpengyuan** [comment]
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/

**Comment by pitiwari** [comment]
thanks for quick reply. Is any specific istio version is needed ?. I tried using yml from the link but getting error like this 
kubectl apply -f cert_fwd.yaml -n istio-system
error: error when retrieving current configuration of:
Resource: "install.istio.io/v1alpha1, Resource=istiooperators", GroupVersionKind: "install.istio.io/v1alpha1, Kind=IstioOperator"
Name: "", Namespace: "istio-system"
from server for: "cert_fwd.yaml": resource name may not be empty

yaml

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      gatewayTopology:
        forwardClientCertDetails: ALWAYS_FORWARD_ONLY

**Comment by pitiwari** [comment]
i was able to add via envoyFilter but still i dont see x-forwarded-client-cert in the debug logs of the ingressgateway 

here is the filter, do u se anything wrong ?

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"name":"test-filter","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"NETWORK_FILTER","match":{"context":"ANY","listener":{"filterChain":{"filter":{"name":"envoy.filters.network.http_connection_manager"}}}},"patch":{"operation":"MERGE","value":{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","access_log":[{"name":"envoy.file_access_log","typed_config":{"@type":"type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog","format":"[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% %DOWNSTREAM_PEER_SUBJECT%\n","path":"/dev/stdout"}}]}}}}]}}
  creationTimestamp: "2022-01-23T00:32:09Z"
  generation: 8
  name: test-filter
  namespace: istio-system
  resourceVersion: "23358678"
  uid: ce328c62-6531-4414-ab37-b38966ff2f24
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.file_access_log
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              format: |
                [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% "%DYNAMIC_METADATA(istio.mixer:status)%" "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% %DOWNSTREAM_PEER_SUBJECT% "%REQ(X-Forwarded-Client-Cert)%"
              path: /dev/stdout
          forwardClientCertDetails: ALWAYS_FORWARD_ONLY
          set_current_client_cert_details:
            cert: true
            chain: false
            dns: true
            subject: true
            uri: true

**Comment by bianpengyuan** [comment]
> thanks for quick reply. Is any specific istio version is needed ?. I tried using yml from the link but getting error like this
> 
> kubectl apply -f cert_fwd.yaml -n istio-system error: error when retrieving current configuration of: Resource: "install.istio.io/v1alpha1, Resource=istiooperators", GroupVersionKind: "install.istio.io/v1alpha1, Kind=IstioOperator" Name: "", Namespace: "istio-system" from server for: "cert_fwd.yaml": resource name may not be empty
> 
> yaml
> 
> apiVersion: install.istio.io/v1alpha1 kind: IstioOperator spec: meshConfig: defaultConfig: gatewayTopology: forwardClientCertDetails: ALWAYS_FORWARD_ONLY

You should not apply the IstioOperator resource directly to your cluster. You should feed that to the istioctl install command you use when you install Istio.

**Comment by pitiwari** [comment]
thanks

**Comment by pitiwari** [comment]
enabling mtls fixed the issue. Closing this
