### ISSUE TITLE
Use multiple istio gateways as ingress controllers 

### ISSUE THREAD

**Issue by yogeshramesh1995** [istio/istio#37006]
i am using istio version 1.10.3 installed using istio operator, i want to use multiple istio-gateways as ingress controllers, I am able to select a gateway to be used as the ingress controller by changing the global mesh config in the istio operator manifest:

 `meshConfig:
    ingressControllerMode: STRICT
    ingressService: istio-external-ingressgateway
    ingressClass: istio
    ingressSelector: istio-external-ingressgateway`
    
I am trying to figure out how to select multiple gateways to be used as ingress controllers, I am not able to find any documentation regarding the same, is this possible ?  if so can anybody please help me achieve this, thank you

**Comment by howardjohn** [comment]
You would need to use two different Istio control plane installations.

It is *strongly* recommended not to dothis, and instead use the Gateway API which handles this much more simply

**Comment by yogeshramesh1995** [comment]
@howardjohn thank you for the response. 

I believe we will have to create new objects like HTTP route, tls route, etc for us to be able to use the gateway api's more efficiently. I was trying to see if we can retain our existing ingress objects and create a new gateway class, gateway and have the gateway work with the existing ingress objects, is this possible?

**Comment by hzxuzhonghu** [comment]
I would suggest use native istio api instead of k8s gateway-apis atm. Native istio API is more mature, vice versa the latter could change frequently.
