### ISSUE TITLE
Istio DestinationRule maxConnections

### ISSUE THREAD

**Issue by dawo0od** [istio/istio#37009]
### Bug Description

Actually this is an inquiry not a bug. 

Regarding DestinationRule maxConnections , as per my understanding it is maximum number of connections to a service. and any excess connection will be pending in a queue and will not lead to opening the circuit. Please correct if I'm wrong.

Could you please also let me know if maxConnection represents maximum connections for k8s service or for a single pod ? (For example if I have configured maxConnections as 200 and I have 2 pods , then each pod will have max 200 connection at a certain time.)

### Version

```prose
istio version : 1.9
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by bianpengyuan** [comment]
The excess connection won't be in a pending queue. It will just failed fast. See envoy circuit breaker document for definitive behavior definition: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking.

> Could you please also let me know if maxConnection represents maximum connections for k8s service or for a single pod ? (For example if I have configured maxConnections as 200 and I have 2 pods , then each pod will have max 200 connection at a certain time.)

Each client pod will get max 200 connections to the upstream service.

**Comment by dawo0od** [comment]
@bianpengyuan I have tested the same myself , when 200 maxConnections are configured and I'm initiating 500 maxConnections it is not failing fast or open the circuit. It is still handling all the requests but in different time frame.

**Comment by dawo0od** [comment]
> Each client pod will get max 200 connections to the upstream service.

Yes for the client pod it will get max 200 connections. What about upstream pods ?  If I have 2 upstream PODs each one will still handle 200 concurrent connection ?

**Comment by hzxuzhonghu** [comment]
DR connection pool only works on client, not server side

**Comment by dawo0od** [comment]
@hzxuzhonghu So if I'm configuring 200 maxConnections on my server side that means that each client will able to pass only 200 concurrent connection and whatever exceeding this number will be queued from client side. Please correct if I'm wrong.

**Comment by dawo0od** [comment]
> @hzxuzhonghu So if I'm configuring 200 maxConnections on my server side that means that each client will able to pass only 200 concurrent connection and whatever exceeding this number will be queued from client side. Please correct if I'm wrong.

Let's assume that "service 1" is calling "service 2" , and I have 200 maxConnections configured for "service 2" DR. 

What will be rules applied in the above case ?

**Comment by hzxuzhonghu** [comment]
Please read about the doc, in your casem the DR mainly work on `service 1`

**Comment by dawo0od** [comment]
@hzxuzhonghu I've tried the below scenario myself :

I have 3 client PODs and 1 server POD with maxConnections 5 configured.

I have 3 active connections (1 connection for each client POD) and 10 requests per connection. 

The result is as below :

Client 1

----------START BATCH----------
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.045260190963745
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.055057048797607
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.069271087646484
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.074933528900146
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.075678586959838
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.080535650253295
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.078705310821533
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.072443962097167
**STATUS: 200, START: 12:48:20, END: 12:48:25, TIME: 5.101719617843628
STATUS: 200, START: 12:48:20, END: 12:48:25, TIME: 5.101463794708252**

Client 2

----------START BATCH----------
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.031870126724243
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.039080142974853
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.052941799163818
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.055186986923217
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.058765411376953
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.062105894088745
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.064795494079589
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.064253568649291
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.064253568649901
**STATUS: 200, START: 12:48:20, END: 12:48:25, TIME: 5.065257787704468**

Client 3

----------START BATCH----------
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.060233116149902
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.067852497100830
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.065126895904541
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.060657978057861
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.063534021377563
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.072394609451293
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.072262525558471
STATUS: 503, START: 12:48:20, END: 12:48:20, TIME: 0.073269128799438
**STATUS: 200, START: 12:48:20, END: 12:48:25, TIME: 5.097288608551025
STATUS: 200, START: 12:48:20, END: 12:48:25, TIME: 5.089052915573120**


As you see above 2 requests from 1st client succeeded , 1 from 2nd client and 1 from 3rd client (Total is 5) which is the maximum connections configured.

Based on my testing this means that upstream service will accept maximum 5 connections. Below is a link explaining the same in scenario #3 which I tested.
https://tech.olx.com/demystifying-istio-circuit-breaking-27a69cac2ce4 


Your feedback is highly appreciated :)

**Comment by dawo0od** [comment]
Any update here please ?

**Comment by ramaraochavali** [comment]
What you found is what is expected - when you apply circuit breaker limits they are applied to both client and server - So here the maxConnections is applied at both client pod and server pod.

**Comment by idouba** [comment]
maxConnections in DR both apply to outbound traffic and inbound traffic for the specified server. As s1 calls s2, configuring 100 maxConnections for s2.
s1 pods num | s1 sidecar   injected | s2 pods num | s2 sidecar   injected | maxConnections
-- | -- | -- | -- | --
1 | Yes | 1 | Yes | 100
1 | Yes | 1 | Yes | 100
1 | No | 1 | Yes | 100
1 | Yes | 1 | No | 100
2 | Yes | 1 | Yes | 100
2 | Yes | 1 | No | 200
