### ISSUE TITLE
Is there a way to test that grpc-web routes are reaching the right services?

### ISSUE THREAD

**Issue by ds0nt** [istio/istio#37005]
For instance, we have some web apps that will call grpc-web endpoints. In case we misconfigure a route, or grpc service, we won't know until we try the web API and see it failing.

Is there an easy way to verify that the grpc-services are reachable via the web without tacking on exposed healthcheck services, or adding ping methods to every service?

**Comment by bianpengyuan** [comment]
Probably traffic mirror is what you are looking for? https://istio.io/latest/docs/tasks/traffic-management/mirroring/
