### ISSUE TITLE
Check client certificate common name on the ingress gateway with mutual tls

### ISSUE THREAD

**Issue by cybercleric** [istio/istio#37011]
Hi!
I need to organize client authentication on ingress when installing mutual tls between the client and ingress.
I want to check the CN of the client certificate. And skip the client only if the CN matches what I expected.
Is it possible to implement this by means of Istio?
Perhaps it's worth looking at subjectAltNames in the Gateway manifest? But I can't find an example of using this function.

**Comment by johnzheng1975** [comment]
Not sure https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ is useful for you. Just FYI

**Comment by EKovtun** [comment]
Thank you, John, I know about this, but there is nothing there that would solve my question.

> Not sure https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ is useful for you. Just FYI

**Comment by howardjohn** [comment]
I think https://istio.io/latest/docs/reference/config/security/authorization-policy/ `prinicples` will work.

**Comment by cybercleric** [comment]
I managed to solve this problem through a EnvoyFilter and regex matching

[envoyfilter-ingress.txt](https://github.com/istio/istio/files/8571629/envoyfilter-ingress.txt)
