### ISSUE TITLE
Using tls in gateway, is it necessary to put cerificate/privatekey in k8s secrets? Thanks

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#37013]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Using tls in gateway, is it necessary to put cerificate/privatekey in k8s secrets? Thanks
You know, put cerificate/privatekey in k8s secrets is not securer, easy to be disclose.
Relate docs: `https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/`
Related command: `kubectl create -n istio-system secret tls httpbin-credential --key=httpbin.example.com.key --cert=httpbin.example.com.crt`

**Describe alternatives you've considered**
Any workaround like
1. Put formal certificate in AWS loadbalancer
2. Change CA to my own CA (or istio root CA), which is useful in whole cluster.
3. Get new certificate (generated by istio or others) and put in istio ingressgateway.

Thus, I need not real certificate/privatekey in k8s secrets.

Not sure it works, please suggest. Thanks.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
actually, you can unload your certs on aws loadbalancer

**Comment by hzxuzhonghu** [comment]
If you want to do tls termination in ingress gateway, you'd better to make use of sds, which requires storing certs in k8s secret

**Comment by johnzheng1975** [comment]
> actually, you can unload your certs on aws loadbalancer

This is what I did now, can work but not nice.

**Comment by johnzheng1975** [comment]
> If you want to do tls termination in ingress gateway, you'd better to make use of sds, which requires storing certs in k8s secret

for storing certs in k8s secrets, is this cert must be a **real** cert/private key of our website? or we can use a mock cert/privatekey ?

**Comment by hzxuzhonghu** [comment]
The real key/cert

**Comment by johnzheng1975** [comment]
> The real key/cert

oh.  my goodness.
 
Thanks for your answer. @hzxuzhonghu 
Is it possible to implement my requirement 
1. Not put real key/cert in k8s secrets
2. tls between loadbalancer and ingressgateway.

**Comment by ramaraochavali** [comment]
even if you have certs as file mounted as volume mounts of pod, Istio sends them via SDS

**Comment by johnzheng1975** [comment]
Thanks @ramaraochavali .

I think there may two shortage for "put real certificate in k8s secrets", please let me know whether I am correct.
1. many people has rights to access k8s secrets.
So, they will get the certificate. right?
2. In some case,  dev/qa/stg/prod domain may has same certificate. So the dev env k8s admin can get the **prod domain certificate** in dev env k8s, right?
Thanks.

**Comment by ramaraochavali** [comment]
> many people has rights to access k8s secrets.
So, they will get the certificate. right?

Possible

> In some case, dev/qa/stg/prod domain may has same certificate. So the dev env k8s admin can get the prod domain certificate in dev env k8s, right?

I do not know this is how people use it mostly.

@howardjohn might have better insights here

**Comment by howardjohn** [comment]
Generally you should put all of the ingress stuff in a secure namespace that only admins have access to. Using same cert for all envs sounds a bit suboptimal from this security standpoint.

If you don't want to use this you can ways terminate TLS in a cloud load balancer

**Comment by hzxuzhonghu** [comment]
I am not sure if there is safer and standard store in cloud-native scope, if there is, I think we can also support the industry-standard way.

**Comment by johnzheng1975** [comment]
Appreicate for discussion.  @howardjohn @ramaraochavali  @hzxuzhonghu 

Below is implemented in another our project currently, 
1. Put domain certificate in AWS application load balancer.
2. From AWS alb to nginx-ingress-controller, using tls. The cert in nginx-ingress-controller is a servicename.namespacename certficate, not real domain certificate. (managed by cert-manager)
![image](https://user-images.githubusercontent.com/17720035/152684113-0c48f02b-35ce-4129-9739-05d079bb561a.png)

This is safe for domain certificate. 
Is it possible for istio support similar way currently?  Thanks very much.

**Comment by johnzheng1975** [comment]
> Generally you should put all of the ingress stuff in a secure namespace that only admins have access to. Using same cert for all envs sounds a bit suboptimal from this security standpoint.
> 
> If you don't want to use this you can ways terminate TLS in a cloud load balancer

@howardjohn , one confirm, thanks.
If terminate TLS in a cloud load balancer, is it a way to make the requests between _**cloud load balancer**_ with **_istio ingressgateway_** be **_tls_**?

**Comment by hzxuzhonghu** [comment]
>Is it possible for istio support similar way currently? Thanks very much.

AFAIK, certmanager is an operator, it signs   certificate  with third party issuer, and still store it in k8s secret. So it does not help the authz issue you faced.

**Comment by hzxuzhonghu** [comment]
>If "terminate TLS in a cloud load balancer" as you mentioned, is it a way to make the requests between cloud load balancer with istio ingressgateway be tls?

It depends on the cloud lb you use.

**Comment by johnzheng1975** [comment]
> > Is it possible for istio support similar way currently? Thanks very much.
> 
> AFAIK, certmanager is an operator, it signs certificate with third party issuer, and still store it in k8s secret. So it does not help the authz issue you faced.

Thanks. The certmanager here is just generate cert for servicename.namespacename of nginx-ingress-controller. 
This is acceptable since it will not let out domain cert. (.gramma.hpoxxxd.io), right?

**Comment by johnzheng1975** [comment]
> > If "terminate TLS in a cloud load balancer" as you mentioned, is it a way to make the requests between cloud load balancer with istio ingressgateway be tls?
> 
> It depends on the cloud lb you use.
Thanks @hzxuzhonghu.
The loadbalancer support https to k8s node, but it need one cert exists in ingress gateway. am I right?

**Comment by johnzheng1975** [comment]
> > Thanks. The certmanager here is just generate cert for servicename.namespacename of nginx-ingress-controller.
> 
> It can be _literally_ anything. Most cloud load balancers do not verify it at all. It can be an expired, self-signed cert for `example.com`. I have a WIP to make this easier: #36922

@howardjohn , Thanks a lot for your contribute.
Yes, put cert inside k8s is not the best practice for me. No matter put in k8s secrets or mount files.
Your PR is what I needed.

How to use this then?
For example If user set **tls: mode** to **BUILDIN** (add a new item for mode), istio will create a certificate for all domain "*". Then aws application load balancer will connect it with https?

```
$ cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: BUILDIN
      # credentialName: httpbin-credential # remove
    hosts:
    - httpbin.example.com
EOF
```

**Comment by johnzheng1975** [comment]
Before you contribute go online, I will implement like: https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/

**Comment by johnzheng1975** [comment]
After testing, it works! 
https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/
Just as @howardjohn  said, the aws load balancer did not verify at all, I change change to other self-signed cert for httpbin.example.com or helloworld-v1.example.com. I did not realize this before. 
This makes my requirements so easy to implement.

**Comment by johnzheng1975** [comment]
My question to AWS support:
Will application load balancer check the cert when its target group protocal is HTTPS?
As below target group, the alb is created in eks.
arn:aws:elasticloadbalancing:us-west-2:xxxxx:targetgroup/k8s-istiosys-istioing-a0b8758b05/rrrrrrr
The backend service is istio ingress gateway.
I found:
No matter which cert I put in istio gateway, the connection is always fine.
Its real domain is test.hpbp.io, but it still works when I change cert to other self-signed cert for httpbin.example.com or helloworld-v1.example.com.
So, I guess the load balancer(application load balancer) do not check the cert domain at all. Even fine when it is overdue?
I want to confirm this, thus I can design my solution on my project.

The answer from AWS support:
[https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-routing-configuration](https://protect-us.mimecast.com/s/PuovCn5XpXTm1BWNnTP9BFt?domain=docs.aws.amazon.com)
If a target group is configured with the HTTPS protocol or uses HTTPS health checks, the TLS connections to the targets use the security settings from the ELBSecurityPolicy-2016-08 policy. The load balancer establishes TLS connections with the targets using certificates that you install on the targets. The load balancer does not validate these certificates. Therefore, you can use self-signed certificates or certificates that have expired. Because the load balancer is in a virtual private cloud (VPC), traffic between the load balancer and the targets is authenticated at the packet level, so it is not at risk of man-in-the-middle attacks or spoofing even if the certificates on the targets are not valid.
