### ISSUE TITLE
adding headers to request headers

### ISSUE THREAD

**Issue by pitiwari** [istio/istio#37036]
### Bug Description

I am trying to put DOWNSTREAM_PEER_SUBJECT value into new header and forward it to next hop but its not working since DOWNSTREAM_PEER_SUBJECT is not part of request headers. I can see DOWNSTREAM_PEER_SUBJECT in access logs via other EnvoyFilter. Any suggestions how to extract DOWNSTREAM_PEER_SUBJECT in envoyfilter? This is how the filter looks 

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
  name: lua-filter
  namespace: istio-system
  resourceVersion: "24022983"
  uid: f86043e6-c17a-4988-9f56-b621c1234c7e
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
                request_handle:headers():add("customer-id", "alice")
                headers = request_handle:headers()
                request_handle:headers():add("authority", request_handle:headers():get(":authority"))
                headervalue = request_handle:headers():get("x-forwarded-client-cert")
                request_handle:headers():add("roku_xfcc", headervalue)
                headervalue = request_handle:headers():get("downstream_peer_subject")      ------------> getting null here
                request_handle:headers():add("downstream_peer_subject", headervalue)
                request_handle:logCritical("test1: "..request_handle:headers():get("x-forwarded-client-cert"))
                request_handle:logCritical("test2: "..request_handle:headers():get("downstream_peer_subject"))
                request_handle:logCritical("test3: "..request_handle:headers():get(":authority"))
            end
  workloadSelector:
    labels:
      istio: ingressgateway

**Comment by zirain** [comment]
try this code:
```lua
request_handle:headers():replace(":authority", new_autho)
```

**Comment by pitiwari** [comment]
thanks i updated the issue with more details. seems like for xfcc u need not to put : and that did the trick. Now trying to see how to extract downstream_peer_subject

**Comment by pitiwari** [comment]
found the way request_handle:streamInfo():downstreamSslConnection():subjectPeerCertificate()
