### ISSUE TITLE
istio-cni : memory leak in repair 

### ISSUE THREAD

**Issue by sedflix** [istio/istio#37039]
### Bug Description

We observed that most of the pods in some of our eks clusters and some pods in other eks clusters were using memory in the range of 7GB. These pods were of Istio CNI Daemon Set.

On initial debugging, where we turned on the debug logs other istio-cni-pods using controlZ, we saw the only thing that the pod was doing was running a repair loop and its memory would keep on increasing, and forcing garbage collection wouldn't reduce the memory.  We disabled the repair loop manually and saw that that memory consumption was under control even after two days.

---

I wanted to profile memory of istio-cni while keeping the repair feature on to figure out where the leak is happening. I wasn't able to find any resource to profile memory in isito-cni.  From what I can see, pprof server is not running in normal istio-cni distribution.

### Version

```prose
$ istioctl version
client version: 1.10.0
control plane version: 1.11.3
data plane version: 1.11.3 (1096 proxies)

$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.5-eks-bc4871b
```

### Additional Information

```
istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2022-01-27 11:35:08.77283 +0530 IST
```

**Comment by bianpengyuan** [comment]
The high memory usage has been fixed at 1.11.5 release.

**Comment by binboum** [comment]
We see the same thing, even on the latest releases, since 1.11

**Comment by bianpengyuan** [comment]
@binboum what release are you on?

**Comment by binboum** [comment]
We have small environments, but we go from a very linear thing that never exceeds 100MB, to non-linear consumption that sometimes exceeds 400MB.

1.12.2

![image](https://user-images.githubusercontent.com/11870307/151456571-cb1ae0aa-12f3-463b-9d56-d79df3cfb0f2.png)

1.10.0
![image](https://user-images.githubusercontent.com/11870307/151456642-f4182ae7-8d3a-4ab2-a983-dac63a7705e5.png)

**Comment by bianpengyuan** [comment]
@binboum we combined repair container and install container to one container (install-cni) at 1.11, so if you are only comparing memory usage of install-cni container that might explain it.

**Comment by sedflix** [comment]
@bianpengyuan can you point to the PR for this fix?
I wasn't able to find it in release notes.

**Comment by bianpengyuan** [comment]
https://github.com/istio/istio/pull/36109 Should have added a release note for it. Sorry about that.

**Comment by sedflix** [comment]
@bianpengyuan thank you so much for this.
