### ISSUE TITLE
Change dynamically created virtualservice host from "*" to mydomain.

### ISSUE THREAD

**Issue by ashissharma97** [istio/istio#37043]
Hi,
I am using istio as part of Kubeflow deployment and I have enabled TLS to the ingress while enabling I have changed hosts from "asterisk" to "mydomain.com" now we have CRD which dynamically creates virtual-service and the host of that service is "asterisk" which should be "mydomain.com". Can anybody help me to change this?

Thanks

**Comment by bianpengyuan** [comment]
Can you give more details what did you change?

**Comment by bianpengyuan** [comment]
> we have CRD which dynamically creates virtual-service and the host of that service is "asterisk" which should be "mydomain.com"

I don't quite understand this in your OP. what is creating virtual service?

**Comment by ashissharma97** [comment]
In Kubeflow we have a resource i.e. Jupyter Notebook when we create a new notebook from UI a new pod will be created and a virtual service attached to that pod the hosts of this virtual service is "asterisk" because of this I'm not able to access the notebook I'm getting "/[path] is not valid page" in the dashboard.

**Comment by ashissharma97** [comment]
Okay, thanks for your response.
Closing the issue
