### ISSUE TITLE
Istio Operator Errors on Numeric Canary Revision

### ISSUE THREAD

**Issue by twa16** [istio/istio#37055]
### Bug Description

The istio-operator will give a cryptic error when the "revision" is set to a value that can be parsed as a numeric value. It still occurs when the value is quoted.
The error we saw was: 
`2022-01-27T20:22:26.000333Z	error	klog	k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.IstioOperator: failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Status: Spec: unmarshalerDecoder: json: cannot unmarshal number into Go value of type string, error found in #10 byte of ...|e":true}}},"status":|..., bigger context ...|td-configcheck"]}]}],"rewriteAppHTTPProbe":true}}},"status":{"componentStatus":{"Base":{"status":"HE|..`

Setting the revision to a value that could not be parsed as a number fixes the issue. For example "1" will cause the error but "1-1" will not. It being unset also does not trigger issue.

### Version

```prose
> kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.5+rke2r2

Using operator version 1.11.3
```

**Comment by lcopi** [comment]
I also see this if I add a selector block to the service in the iop definition. In my case the revision is not numerically parseable. If I manually patch the iop in the environment it is fine, but if I apply it with `kubectl apply` I hit this error

**Comment by litong01** [comment]
Can you try a newer version and see if same error occurs? John is also working on a PR to rework protobuf, that might potentially fix this issue if it is still happening in the latest release. Release 1.11.x is a bit old, support for it will run out end of march 2022. Please try a newer version and update the results here. Thanks.

**Comment by litong01** [comment]
@twa16 I've looked into this. This actually is a bit difficult to fix, Istio assumed that revision has to be a string, but some of the unmarshal code takes number as well, then later some code will try to coerce it to string which will fail. This problem also exists when you simply use istioctl to install a revisioned control plane with a numeric number as revision. I suggest we document this or maybe add a revision validator so this fails fast.
