### ISSUE TITLE
Probes intended for proxyless gRPC can break other setups

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#37056]
When `GRPC_XDS_BOOTSTRAP` is set we perform probes to make sure the certs exist. 

The certs are expected to be at `OUTPUT_CERT_DIR/...`. 

At some point we set a default value for the `GRPC_XDS_BOOTSTRAP` so that agent would always generate the bootstrap, and applications could just use it if they wanted. 

We either need to:

* Require enabling this check explicitly
* Make the assumed location of certs more intelligent 

cc @howardjohn

**Comment by stevenctl** [comment]
https://istio.slack.com/archives/GHKNPELMS/p1643312321979929

**Comment by stevenctl** [comment]
Basically this issue makes it so readiness fails when `OUTPUT_CERTS` is set but we don't write the expected files there.

**Comment by stevenctl** [comment]
@howardjohn 

There are a lot of paths in this part of the code.. do you know off the top of your head a scenario where `OUTPUT_CERTS` is set, but we don't care that the certs aren't output? 

This failure will only occur if `OUTPUT_CERTS != ""`

**Comment by howardjohn** [comment]
pkg/istio-agent/README.md could be useful if you haven't seen it. Do you
know *why* they are not written? Doesn't that mean we never fetched any
certs? That seems odd.
