### ISSUE TITLE
release-builder or docker.save local builds fail on release-1.13 and master branches

### ISSUE THREAD

**Issue by ericvn** [istio/istio#37069]
### Bug Description

I believe the docker build v2 work is causing some issues while trying to do release-builder builds locally.

Trying the command in the README works on the release-1.12 branch but fails on newer branches.

```
2022-01-28T14:39:07.101176Z	info	Running command: docker buildx bake -f /tmp/istio-release/work/src/istio.io/istio/out/linux_amd64/dockerx_build/docker-bake.json all
[+] Building 0.0s (0/0)
error: Docker exporter feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
Error: exit status 1
make[1]: *** [tools/istio-docker.mk:379: dockerx.save] Error 255
make[1]: Leaving directory '/tmp/istio-release/work/src/istio.io/istio'
Error: failed to build: failed to build Docker: failed to create istio docker archives: exit status 2
exit status 1
```

### Version

```prose
master and release-1.13 branches
```

**Comment by ericvn** [comment]
Note that `make docker.save` (command used in release-builder) fails in the istio/istio repo as well.

**Comment by howardjohn** [comment]
Need to create a docker builder. It's probably not specific to Mac? We have code somewhere to do it but it's probably not triggered as a dependency for docker.save - likely a simple fix

**Comment by ericvn** [comment]
I believe the docker builder is created, I may be that the Mac version doesn't support tar file generation. `make docker` works in istio/istio to generate images. `make docker.save` fails.Possibly the builder create can be tweaked.

**Comment by howardjohn** [comment]
I think that's just how docker works? Even on linux

**Comment by ericvn** [comment]
Good to know Linux also seems to have a default builder that's using the non-default driver.

**Comment by ericvn** [comment]
I might look at checking if the current builder driver is docker-container in the case of a .save and dump a message to create a builder..

**Comment by howardjohn** [comment]
createBuildxBuilderIfNeeded in docker-builder/main.go is supposed to do it.
Does it not work?

**Comment by ericvn** [comment]
We don't create a build instance if CI is not set: https://github.com/istio/istio/blob/master/tools/docker-builder/main.go#L122

This change would be more of a check if the current builder is OK. Maybe something like: `docker buildx ls | grep "*" | grep docker-container` although I'm not sure if * would be somewhere else besides the current builder.

**Comment by ericvn** [comment]
Also noted, that the .save isn't used very much. The thing that raised the issue here is release-builder uses it, so running that locally would cause an issue.

**Comment by howardjohn** [comment]
Ah. Maybe if CI, create (like today). Else, just warn and tell them how to create..?

**Comment by eeliu** [comment]
I met this problem when compiling

![image](https://github.com/istio/istio/assets/27064129/b043a3c2-5f0c-4d37-bf68-8506a89407ac)

the solution is very easy 

$ docker buildx create --driver-opt network=host,image=gcr.io/istio-testing/buildkit:v0.11.0 --name container-builder --driver docker-container --buildkitd-flags="--debug" --use

> This hint is too implicit.
