### ISSUE TITLE
Verify Istio HA setup

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3706]
istio should be able to support HA setup with multiple zones, with replica of system components and workloads. 

However, the setup hasn't been tested. We need to 

- [x] Do a manual test on 0.7 and make sure it works.

- [ ] Write an automation test.

**Comment by ldemailly** [comment]
Eventually we want a multi zone, multi cluster version of
https://github.com/istio/istio/tree/master/tools#istio-load-testing-user-guide

**Comment by yusuoh** [comment]
The first step is to have a HA deployment and get it tested. It will also be useful for us to achieve a smooth upgrade process.

**Comment by ldemailly** [comment]
yes I think generating yamls with minimal HA would be super useful

**Comment by costinm** [comment]
Helm already supports replica counts. I asked for few changes to
multicluster setup so default can also be set ( user just need to add
clusters and secrets)

**Comment by ldemailly** [comment]
re AZ, looks like it's not there yet:
https://groups.google.com/d/msg/istio-users/y7mcC76Adyc/L9Mh-LTAAAAJ

**Comment by xiaolanz** [comment]
@ayj has tried a setup with replica pilots in one zone/cluster

**Comment by yusuoh** [comment]
Manually tested Istio with HA settings (setting replicas=4 for pilot,mixer,ingress) on GKE regional and multi-zone clusters (3 zones, 2 nodes per zone). Seems to be working well. I think we should add the HA yaml to the to e2e tests.

**Comment by mandarjog** [comment]
I am adding helm charts to create separate check and report mixer clusters, that should be ready for this fix it next week.

**Comment by ldemailly** [comment]
the AZ keeps erroring out for me so I'm surprised you got it working, without mtls maybe ?

**Comment by liamawhite** [comment]
AZ failing won't actually cause issues it will just increase latency due to requests going between datacenters.
