### ISSUE TITLE
flagger doesnt support name in services.match

### ISSUE THREAD

**Issue by pitiwari** [istio/istio#37062]
### Bug Description

i am trying to add name to match for flagger but getting yaml error, after researching online seems like only uri is supported as part of match. Pasting part of yaml below. If anybody was able to get it working please let me know

apiVersion: flagger.app/v1beta1
kind: Canary
spec:
targetRef:
apiVersion: apps/v1
kind: Deployment
service:
match:
- uri:
prefix: /
name: test-name

from this link "Flagger doesn't have support for multiple matches, the service.match only accepts URIs matches for all ports" seems like name is not supported

https://github.com/fluxcd/flagger/issues/434

### Version

```prose
ptiwari@C02GF1X6ML85 dev % istioctl version
client version: 1.11.4
control plane version: 1.12.2
data plane version: 1.12.2 (12 proxies), 1.11.5 (21 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
Flagger is not part of Istio and this seems to be purely a flagger concern. Is there any Istio changes needed?

**Comment by pitiwari** [comment]
ok i got your point. I listed here if others faced the same issue and how they resolved it, will post it in flagger github

**Comment by howardjohn** [comment]
Great, thanks for the info. We try to keep the github issues to Istio bugs, so I will close this, but feel free to ask in slack/stackoverflow/discuss.istio.io to get help from other users. Thanks!
