### ISSUE TITLE
multiple match in HTTP_ROUTE

### ISSUE THREAD

**Issue by pitiwari** [istio/istio#37072]
### Bug Description

I have a working EnvoyFilter which used HTTP_ROUTE but i want this to be applied to 2 different routes depending on routeConfiguration name or match. Is it doable ?

  - applyTo: HTTP_ROUTE
    match:
      routeConfiguration:
        name: https.443.test1
    patch:
      operation: MERGE

  want something like this 

  - applyTo: HTTP_ROUTE
    match:
      routeConfiguration:
        name: https.443.test* or name: https.443.test1 | https.443.test2 or ability to specify 2 matches and have the same patch applied
    patch:
      operation: MERGE

### Version

```prose
platform % istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (8 proxies), 1.12.2 (3 proxies)
```

**Comment by howardjohn** [comment]
You should need to make 2 patches. If that is tedious I recommend some higher level templating like helm
