### ISSUE TITLE
"SSL_ERROR_SYSCALL" "X closed the connection" When using TLS/HTTPS in the istio-ingress gateway

### ISSUE THREAD

**Issue by bellis-ai** [istio/istio#37078]
### Bug Description

When trying to configure the simplest of TLS configurations in the latest version of istio's ingress gateway, all HTTPS connections fail.

<details>
<summary>Here's an example if you're trying to do HTTPS over the domain "test.localhost"</summary>

If you're using the browser, you'd be getting a bunch of pages like "It looks like test.localhost closed the connection". 
![image](https://user-images.githubusercontent.com/98726210/151738318-f00a8f0d-be2d-4e6c-bd16-a076806d5c42.png)

If you're using curl, you'll get errors like 
```
`* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to test.localhost:443
```

If you're just testing it with OpenSSL, you'll get a blank response with no cert info, such as 
```
CONNECTED(00000003)
>>> ??? [length 0005]
    16 03 01 01 2d
>>> TLS 1.3, Handshake [length 012d], ClientHello
    01 00 01 29 03 03 d3 bb 39 ba 75 17 d0 29 08 7c
    07 00 79 f6 d8 a4 a2 34 b9 b6 7c a1 bc 62 20 1c
    68 8e 0b 48 5f 56 20 97 7b 73 5f b7 08 7d 8f 0e
    b1 46 92 7b ca 84 5e af 5d e1 3d 13 ca 4c 2d 48
    66 54 11 c6 9a 6f 2a 00 3e 13 02 13 03 13 01 c0
    2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00
    9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0
    14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00
    3c 00 35 00 2f 00 ff 01 00 00 a2 00 00 00 13 00
    11 00 00 0e 74 65 73 74 2e 6c 6f 63 61 6c 68 6f
    73 74 00 0b 00 04 03 00 01 02 00 0a 00 0c 00 0a
    00 1d 00 17 00 1e 00 19 00 18 00 23 00 00 00 16
    00 00 00 17 00 00 00 0d 00 2a 00 28 04 03 05 03
    06 03 08 07 08 08 08 09 08 0a 08 0b 08 04 08 05
    08 06 04 01 05 01 06 01 03 03 03 01 03 02 04 02
    05 02 06 02 00 2b 00 05 04 03 04 03 03 00 2d 00
    02 01 01 00 33 00 26 00 24 00 1d 00 20 aa 67 bc
    7d fe 61 9a 78 c4 73 58 36 40 e5 b6 9e 9f b4 a7
    80 78 3f 4a 76 e0 05 18 03 d4 5c 64 02
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 306 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
</details>

I have spent ALL DAY scouring the internet for this error. There are multiple issues with similar error behaviors, but each individual issue was attributed to misconfiguration of the TLS info or gateway domains.

Here is a repo containing all the code to easily reproduce this error from scratch using minikube and some copy-paste:
https://gitlab.com/bellis3/istio-ssl-debug

If I misconfigured something let me know... but I used a very very similar variation of this code on istio 1.8.6 (changed a bit to account for how `istio-ingress` was named `istio-ingressgateway`). Did something break with TLS recently?

### Version

```prose
istioctl
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (2 proxies)

kubectl
Client Version: v1.21.3
Server Version: v1.21.2

helm
v3.6.3+gd506314
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by bellis-ai** [comment]
I want to guess it's not SNI related because I set the Gateway and Virtual service hosts to equal ["*"]

**Comment by bianpengyuan** [comment]
For Istio Gateway API, TLS key cert has to be at the same namespace as the gateway proxy (i.e. istio-system in your case).

**Comment by bellis-ai** [comment]
Ah, so that's why I've been so confused. I did that once before and it didn't work. Drove me crazy. 

Turns out in the documentation for the helm charts, it tells you to deploy the gateway proxy in a completely separate namespace (istio-ingress) instead of istio-system. (https://istio.io/latest/docs/setup/install/helm/)

Upon moving the secret to istio-ingress, it worked
