### ISSUE TITLE
Remove or enable `PILOT_ENABLE_DESTINATION_RULE_INHERITANCE` by default

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37095]
Looking into cleaning up feature flags. This has been around, off by default for 1 year. We should move it forward or remove it

**Comment by GregHanson** [comment]
New design doc: [here](https://docs.google.com/document/d/1TkIiovpPLwd-JQ_zKA1Fhy5MVGW3dQKtNwOlFTCKb_Y/edit#)
