### ISSUE TITLE
automate benchmarking

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#371]
we need to be able to continuously check and regress benchmarking

a starting point would be 2 VMs, one running fortio load tester and one running envoy+mixer+fortio echo servers

like
https://github.com/istio/istio/blob/master/devel/README.md#collection-of-scripts-and-notes-for-developing-for-istio

**Comment by ayj** [comment]
Is this addressed by https://ibmcloud-perf.istio.io/regpatrol and https://fortio.istio.io?

cc @ldemailly @suryadu

**Comment by ldemailly** [comment]
Partially, @rkpagadala is working on the fortio automation, it's not there yet

**Comment by ldemailly** [comment]
Pretty much done: https://fortio-daily.istio.io/ 

Just need to add periodic  auto refresh to avoid needing pod restarts

**Comment by ldemailly** [comment]
https://github.com/istio/fortio/pull/244 and https://github.com/istio/admin-sites/pull/69 are the last steps fortio side

@rkpagadala can you link the script that runs for every daily that populates/pushes that data ?

**Comment by rkpagadala** [comment]
https://github.com/istio-releases/daily-release/blob/master/prow/daily-perf-tests.sh

**Comment by hklai** [comment]
Now that we run perf tests everyday, I assume this can be closed now. Please reopen if you think otherwise.
