### ISSUE TITLE
secretcache.go:L676 never cleanup from file certs

### ISSUE THREAD

**Issue by sailingalone** [istio/istio#37119]
https://github.com/istio/istio/blob/96bee97a7e7e09605018e65b0d39b3c822b7965a/security/pkg/nodeagent/cache/secretcache.go#L658-L660

BUT:
https://github.com/istio/istio/blob/96bee97a7e7e09605018e65b0d39b3c822b7965a/security/pkg/nodeagent/cache/secretcache.go#L676

L676 never be  executed?

**Comment by ramaraochavali** [comment]
Not sure I understand. The first if returns false if the event is Remove and so comes down and executes 676. Are you asking the same question?

**Comment by sailingalone** [comment]
sorry，Not noticed the outermost  "!"
