### ISSUE TITLE
Require to build Istio/Proxyv2 and Istio/Pilot using FIPS mode . 

### ISSUE THREAD

**Issue by choppspavan** [istio/istio#37118]
Hi All,
We are planning to build the envoy using "--define boringssl=fips" from istio/proxy source code (https://github.com/istio/proxy)
Then use the envoy built and create images of Istio/Proxyv2  and Istio/Pilot using the approach https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxyv2 and https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.pilot .

If we do the above ,can we say our Istio/Proxyv2  and Istio/Pilot images are FIPS enabled ? or are there any other steps to perform .

**Comment by howardjohn** [comment]
That is all that is needed to build boringssl in FIPS-compliant mode. See https://github.com/istio/istio/issues/11723 for more info. Thanks!

**Comment by ceastman-r7** [comment]
@choppspavan Will these have a docker tag indicating they are fips enabled? or is there a process to verify the docker image is running in fips mode?

**Comment by choppspavan** [comment]
@ceastman-r7 When I built envoy in fips-mode , i can see it displayed the version as fips enabled.
/usr/local/bin/envoy --version
/usr/local/bin/envoy  version: e6f45abcf874983fbff384459d70b28c072f68b5/1.20.1/Clean/RELEASE/BoringSSL-FIPS

**Comment by choppspavan** [comment]
@ceastman-r7 Just ran with the option "--define boringssl=fips" mentioned in envoy documentation to build envoy. Then packaged using the docker files to build pilot-agent and pilot-discovery (with boring crypto go to make it fips compliant) as mentioned in my initial description .

**Comment by jeesmon** [comment]
In case anyone looking for steps: https://gist.github.com/jeesmon/00f479a896548aadc0b32ae184890b4e
