### ISSUE TITLE
"requested_server_name":null in access logs for https requests

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#37124]
### Bug Description

curl https://www.google.com from within a pod that has an istio sidecar.

The expectation is that requested_server_name would equal www.google.com

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (11 proxies)

Client Version: v1.22.5
Server Version: v1.21.5-eks-bc4871b
```

### Additional Information

[curl-deployment-54dd7cb66d-vsb2w istio-proxy] {"bytes_sent":20060,"upstream_transport_failure_reason":null,"user_agent":null,"upstream_cluster":"PassthroughCluster","connection_termination_details":null,"response_code_details":null,"duration":181,"x_forwarded_for":null,"response_flags":"-","authority":null,"request_id":null,"start_time":"2022-02-02T15:01:00.936Z","path":null,"route_name":null,"upstream_service_time":null,"response_code":0,"downstream_remote_address":"192.168.97.149:41446","requested_server_name":null,"upstream_local_address":"192.168.97.149:41448","protocol":null,"method":null,"downstream_local_address":"172.217.14.228:443","upstream_host":"172.217.14.228:443","bytes_received":848}

**Comment by ceastman-r7** [comment]
This appears to happen due to a lack of a service entry for www.google.com. I just added the following:
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ingress-www.google.com
  namespace: istio-system
spec:
  hosts:
    - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL

and now the istio-proxy log looks like:
[curl-deployment-54dd7cb66d-vsb2w istio-proxy] {"downstream_local_address":"142.251.33.68:443","response_code_details":null,"user_agent":null,"bytes_received":848,"x_forwarded_for":null,"protocol":null,"upstream_transport_failure_reason":null,"upstream_local_address":"192.168.97.149:60998","duration":104,"downstream_remote_address":"192.168.97.149:50070","upstream_host":"142.250.69.196:443","response_code":0,"connection_termination_details":null,"response_flags":"-","path":null,"route_name":null,"request_id":null,"authority":null,"start_time":"2022-02-02T15:14:39.601Z","method":null,"upstream_service_time":null,"bytes_sent":20048,"upstream_cluster":"outbound|443||www.google.com","requested_server_name":"www.google.com"}

**Comment by howardjohn** [comment]
I think this is expected. Envoy will not sniff the TLS packets unless configured, and for passhthrough traffic we do not configure it to do so since it can break some traffic

**Comment by ceastman-r7** [comment]
I changed the outbound traffic policy to REGISTRY_ONLY but still get an empty requested_server_name:

{"protocol":null,"upstream_host":null,"user_agent":null,"upstream_service_time":null,"path":null,"downstream_remote_address":"192.168.97.149:45188","bytes_received":0,"downstream_local_address":"142.251.33.100:443","bytes_sent":0,"response_code_details":null,"connection_termination_details":null,"response_code":0,"method":null,"start_time":"2022-02-02T17:03:59.750Z","route_name":null,"x_forwarded_for":null,"upstream_local_address":null,"request_id":null,"upstream_transport_failure_reason":null,"requested_server_name":null,"response_flags":"UH","duration":0,"authority":null,"upstream_cluster":"BlackHoleCluster"}

**Comment by howardjohn** [comment]
I would not expect REGISTRY_ONLY to make it better - in fact its worse since it will reject the traffic

**Comment by ceastman-r7** [comment]
Might be better if I present the problem to see if there is a different solution.

Team is installing istio, before they switch the outbound traffic policy to registry only they need to create a set of service entries that the service mesh is allowed to connect to. How can the team develop this list?

**Comment by olddriver4** [comment]
> 我认为这是意料之中的。除非配置，否则 Envoy 不会嗅探 TLS 数据包，对于直通流量，我们不会将其配置为这样做，因为它会破坏一些流量

Hi, How to get it without setting serviceentry?
