### ISSUE TITLE
cABundle not getting updated in MutatingWebhookConfiguration 

### ISSUE THREAD

**Issue by anannaya** [istio/istio#37120]
### Bug Description

I am using cert-manager for certificate management,  Basically namespace sidecars not getting created due to cert isssue.
logs at namespace level

2m35s       Warning   FailedCreate   replicaset/ccbu-example-chart-57774df797           Error creating: Internal error occurred: failed calling webhook "rev.namespace.sidecar-injector.istio.io": Post "https://istiod-1-12-2.istio-system.svc:443/inject?timeout=10s": x509: certificate signed by unknown authority

logs at istiod layer

{"level":"info","time":"2022-02-02T11:19:35.694669Z","msg":"http: TLS handshake error from 10.15.0.59:57904: remote error: tls: bad certificate"}

### Version

```prose
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (2 proxies)


Client Version: v1.20.0
Server Version: v1.19.15-eks-9c63c4
```

**Comment by bianpengyuan** [comment]
Is there any root cert update, or it does not work as fresh install?

**Comment by anannaya** [comment]
No changes in root certificate, one weird behaviour is we are using spinnaker to deploy istio which actually does versioning for configmaps namely istio-1-12-2-vOO1 and sidecar-injextion-1-12-2-v001 once I disable the versioning everything seems to be working.  But this  versioning used to work for istio 1-9-3 . Could you give me some clue why this strange behaviour?

**Comment by anannaya** [comment]
@bianpengyuan  Could you pls help me to understand , where these are referenced apart from ingress gateway deployment.

**Comment by bianpengyuan** [comment]
So there are multiple version/revision installed in your cluster? Need to check if istiod has any log about failing to update webhook certs.

**Comment by anannaya** [comment]
Yes multiple versions of configmap. My question where in helm chart we reference the istiod configmap name ?

**Comment by bianpengyuan** [comment]
> My question where in helm chart we reference the istiod configmap name ?

Not sure I follow your question..

**Comment by anannaya** [comment]
How does istiod knows the configmap name ?

**Comment by bianpengyuan** [comment]
It is passed in as `REVISION` env variable at istiod.

**Comment by anannaya** [comment]
I think thats a problem,  For 1-9-3  there exists a  configmap mount to istiod deployment , spinnaker manages those configmap versioning to k8s controller objects.  Now the volume and configmap no longer exists in 1-12-2 thats causing the issue for me.  Looks the configmaps are read by istiod programmatically.  Could you pls confirm this behaviour .
`
        volumeMounts:
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/token
        
      - configMap:
          defaultMode: 420
          name: istio-1-9-3-v006
        name: config-volume
`

**Comment by ceastman-r7** [comment]
@anannaya I am running into the same issue. I am trying to use spinnaker to install istio.

**Comment by ceastman-r7** [comment]
In my kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml caBundle is completely missing:
  clientConfig:
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443

**Comment by anannaya** [comment]
@ceastman-r7  use the spinaker annotation to disable the versioning for configmap and sidecar injection .that would fix the issue

**Comment by ceastman-r7** [comment]
Yep that fixed it for me

{{- if not .Values.global.omitSidecarInjectorConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    'strategy.spinnaker.io/versioned': 'false'  

but now the istio helm charts are different from the public so every new version of istio have to make these updates.

**Comment by ceastman-r7** [comment]
Does spinnaker change the name of anything else besides configmaps and secrets?

**Comment by anannaya** [comment]
@ceastman-r7  I am aware of only these 2.

**Comment by ceastman-r7** [comment]
I am going to look into updating the helm charts so we can add these annotations to a values override file instead of changing the helm chart itself.
