### ISSUE TITLE
Please rename EnvoyFilter to EnvoyPatch

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#37140]
[EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) is a powerful resource allowing very custom configurations that are not possible using other abstractions from Istio.

The name EnvoyFilter gives you the impression that it allows you to add/configure an Envoy filter (like [envoy.filters.http.adaptive_concurrency](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/adaptive_concurrency/v3/adaptive_concurrency.proto#extension-envoy-filters-http-adaptive-concurrency)), which is true but it also allows you to add/configure [other things](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo). 

What's common among all of its use cases? it allows you to patch certain sections of the Envoy configuration. It's pretty common during a call to confuse EnvoyFilter resource with an actual Envoy filter and then you have to clarify afterward (or by adding "patch" in every reference to it).

Abstraction-wise, it's pretty solid but I guess the name can be improved.

Cheers.

**Comment by howardjohn** [comment]
I agree but the amount of pain to rename an API is *extremely* high. I would rather it be named `FooBar` than rename it, personally :-)

**Comment by howardjohn** [comment]
BTW the history here is it used to only insert filters not patch things

**Comment by rahulanand16nov** [comment]
I understand the difficulty in renaming an API but who knows the frustration of referring it causes enough motivation to justify this change someday. `ctrl+shift+h` worth a try?

**Comment by howardjohn** [comment]
It will not be enough justification unfortunately. I don't mean to be dismissive, but we are committed to backwards compatibility and this is something we will never do. Thanks for the feedback though!
