### ISSUE TITLE
Istio sidecar is not supported on GKE AutoPilot

### ISSUE THREAD

**Issue by thiagogcm** [istio/istio#37150]
### Bug Description

I can't get Istio proxy to work on GKE AutoPilot.

Using the Bookinfo sample:
`Error creating: admission webhook "policycontrollerv2.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-default-linux-capabilities]":["linux capability 'NET_ADMIN' on container 'istio-init' not allowed; Autopilot only allows the capabilities: 'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT,SYS_PTRACE'. Requested by user: 'system:serviceaccount:kube-system:replicaset-controller', groups: 'system:serviceaccounts,system:serviceaccounts:kube-system,system:authenticated'."]}`

when I try to enable CNI, I get:
```
✔ Istio core installed                                                                                                                                                    
✔ Istiod installed                                                                                                                                                        
  Processing resources for CNI, Ingress gateways.                                                                                                                         2022-02-03T16:58:49.429339Z	error	installer	failed to update resource with server-side apply for obj DaemonSet/istio-system/istio-cni-node: admission webhook "policycontrollerv2.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume cni-bin-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'.","hostPath volume cni-net-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'.","hostPath volume cni-log-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'."]}
✘ CNI encountered an error: failed to update resource with server-side apply for obj DaemonSet/istio-system/istio-cni-node: admission webhook "policycontrollerv2.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume cni-bin-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'.","hostPath volume cni-net-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'.","hostPath volume cni-log-dir in container install-cni is accessed in write mode; disallowed in Autopilot. Requested by user: 'thiago.moura@sensedia.com', groups: 'system:authenticated'."]}
✔ Ingress gateways installed                                                                                                                                              
- Pruning removed resources

Error: failed to install manifests: errors occurred during operation
```

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (1 proxies)

Client Version: v1.23.3
Server Version: v1.21.6-gke.1500
```

**Comment by bianpengyuan** [comment]
cc @ostromart @maasen

**Comment by aeciopires** [comment]
+1

**Comment by linsun** [comment]
per John's comment

**Comment by stenio123** [comment]
Hi @howardjohn can you please confirm that this error/security feature is only addressed in the ASM "rapid" channel as of Dec 30 2022, or if it is also address in the "regular"?

I followed the link, it is a blog post from Feb 9th, 2022 stating that autopilot now supports ASM. It does say that this was only available for the "Rapid" channel, and eventually would be expanded to "regular" and "stable". Checking the [ASM Channel Release Notes](https://cloud.google.com/service-mesh/docs/release-notes) it states that GKE Autopilot is generally available for "rapid" and "release" channels as of Sept 8th, 2022.

However when I try this deployment with the "regular" channel, I still get the above mentioned error. Only when I switch to "rapid" does it work.

Is this situation being tracked separately, or is only the fact of an ASM version being supported by Autopilot enough?

**Comment by howardjohn** [comment]
I believe it should work on regular as well. Might be best to open a Google support ticket which will give us access to debug things. Feel free to tell support to direct it to me.

If not send me the project number on slack maybe? 

cc @ZhengzheYang

**Comment by stenio123** [comment]
Thanks for the quick response! I am working on a merge/refresh of the GKE PCI DSS Blueprint and the Anthos PCI DSS Blueprint, will use rapid for now as I document the steps and when I create the support ticket will point that out. Hoping to get the first pass done by next week! :-D

**Comment by Savostov-Arseny** [comment]
NET_ADMIN capability can be allowed in GKE Autopilot.

`gcloud container clusters update $CLUSTER_NAME --workload-policies=allow-net-admin`

> Available on new and upgraded existing clusters running GKE version 1.27 and later.
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security#security-measures
