### ISSUE TITLE
istio-proxy standard metrics response_code is showing false positives (i.e. 500, 0, 524, etc)

### ISSUE THREAD

**Issue by dapus123** [istio/istio#37163]
### Bug Description

We have a k8s cluster deployed to our environment and istio is used as service mesh on a kyma-project flavor.

istio-proxy image version:
eu.gcr.io/kyma-project/external/istio/proxyv2:1.11.4-distroless

Expected: 
All response codes should be taken into consideration properly and no false positive

Actual:
```istio_requests_total{response_code="0",reporter="destination",source_workload="ory-oathkeeper",source_workload_namespace="kyma-system",source_principal="spiffe://cluster.local/ns/kyma-system/sa/oathkeeper-maester-account",source_app="unknown",source_version="unknown",source_cluster="Kubernetes",destination_workload="xxx",destination_workload_namespace="app-namespace",destination_principal="spiffe://cluster.local/ns/app-name/sa/serverless-function",destination_app="unknown",destination_version="unknown",destination_service="cx.x.svc.cluster.local",destination_service_name="xx",destination_service_namespace="app-namespace",destination_cluster="Kubernetes",request_protocol="http",response_flags="DC",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="oathkeeper",destination_canonical_service="xx",source_canonical_revision="latest",destination_canonical_revision="latest"}` 20```

### Version

```prose
helm version --short
v3.7.1+g1d11fcb

kubectl version --short
Client Version: v1.22.2
Server Version: v1.20.7

istio-proxy:
eu.gcr.io/kyma-project/external/istio/proxyv2:1.11.4-distroless
```

**Comment by howardjohn** [comment]
What makes you think these are false positives? Is it possible you legitimately have failed requests and just were not aware until Istio metrics showed these? Note retries are enabled by default

**Comment by dapus123** [comment]
@howardjohn - in my example reponse_code="0" - is a false positive, and I remember I had 524 - which is a AWS CloudFlare  "524 gateway Timeout Error is a Cloudflare-specific HTTP status code", even though we are on Azure

**Comment by douglas-reid** [comment]
Prior discussion: https://github.com/istio/istio/issues/31136, in particular, see [comment](https://github.com/istio/istio/issues/31136#issuecomment-788206211).

**Comment by zirain** [comment]
closed as duplicate https://github.com/istio/istio/issues/31136
