### ISSUE TITLE
istio-1.11.6-osx-arm64.tar.gz not working in mac m1

### ISSUE THREAD

**Issue by javixeneize** [istio/istio#37165]
### Bug Description

I have read about compatibility issues in the past with Mac M1 devices, as in ticket #29596 (https://github.com/istio/istio/issues/29596)

I am trying to install istio in my mac m1 (https://github.com/istio/istio/releases/download/1.11.6/istio-1.11.6-osx-arm64.tar.gz) and it is having the issue other users were describing (https://github.com/istio/istio/issues/30829). It gets stuck when creating ingress and egress during install (istioctl install --set profile=demo -y)

- Processing resources for Egress gateways, Ingress gateways. Waiting for Deployment/istio-system/istio-egressgateway, Deployment/istio-system/istio-ingressgateway

Is this still a problem in Mac M1 devices? Any workaround?

Thanks

### Version

```prose
istioctl version
client version: 1.11.6
control plane version: 1.11.6
data plane version: none

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/30829#issuecomment-813074958

Only arm client (istioctl) is supported, not running on arm machine

**Comment by javixeneize** [comment]
Thanks. Is there any workaround to make istio work in minikube in a m1, although its not an official solution released by istio?

**Comment by SubiyaCryolite** [comment]
If its of any help I am able to get istio-1.13.0-beta.1 to install on my M1 Pro, however Envoy proxy injection fails for all projects, even the demos.

**Comment by tjblackheart** [comment]
Works using this spec (thanks @morlay!) :

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  # see https://github.com/istio/istio/issues/21094 and https://github.com/querycap/istio
  hub: docker.io/querycapistio
```

`istioctl install -y -f querycapistio.yaml`

**Comment by shivanshu1333** [comment]
Do we have official full support of istio (and envoy) for M1 now, any updates? cc: @javixeneize @howardjohn

**Comment by howardjohn** [comment]
No

**Comment by manishshanker** [comment]
Is there any plan to do this? As more people buy Mac M1 and want to run it on a kubernetes cluster locally to play around, this Is going to become an issue. Will be great to see this resolved. Of all the tools I am using, and there are quite a few, only Istio is playing up on Mac M1 and not getting installed.

**Comment by howardjohn** [comment]
This is tracked in https://github.com/istio/istio/issues/21094. There are plans and its currently a pretty high priority

**Comment by vince-0202** [comment]
I have the same problem(M1 + MiniKube),How is Istio supporting M1 now

**Comment by wtfiwtz** [comment]
@vince-0202 follow the instructions on https://github.com/querycap/istio for now. You shouldn't need to do the change for 'affinity' on the latest versions.

**Comment by howardjohn** [comment]
Duplicate of https://github.com/istio/istio/issues/36762, see https://github.com/istio/istio/issues/36762#issuecomment-1205370603 for latest status
