### ISSUE TITLE
specifying passphrase for the cert key

### ISSUE THREAD

**Issue by pitiwari** [istio/istio#37176]
### Bug Description

i have a cert for which key has passphrase. When i am trying to do kubectl create secret. I am seeing error below, is there any way to specify passphrase for the key ? 

gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load private key from <inline>, Cause: error:09000068:PEM routines:OPENSSL_internal:BAD_PASSWORD_READ

command is like this 

kubectl create secret generic test--from-file=tls.key=stg.key --from-file=tls.crt=stg.crt  --from-file=ca.crt=stg.crt.ca -n test

### Version

```prose
istioctl version
client version: 1.11.4
control plane version: 1.12.2
data plane version: 1.12.2 (20 proxies), 1.11.5 (12 proxies)
```

**Comment by howardjohn** [comment]
Its supported in Envoy it looks like (https://github.com/envoyproxy/envoy/pull/5175) but not Istio

**Comment by liminw** [comment]
This is related to k8s secret support. I found this old issue https://github.com/kubernetes/kubernetes/issues/53100. It seems that k8s does not support loading a key with passphrase to a secret. As a workaround, you can use unencrypted key instead.
