### ISSUE TITLE
Add a new approach for CA integration through the Envoy SDS API.

### ISSUE THREAD

**Issue by maxlambrecht** [istio/istio#37183]
**Describe the feature request**

Add a new approach for CA integration through the Envoy SDS API.

Please see [RFC: Istio CA integration through Envoy SDS](https://docs.google.com/document/d/1zJP6QJukLzckTbdY42ZMLkulGXz4gWzH9SwOh4xoe0A/edit?usp=sharing)

**Describe alternatives you've considered**

The alternative that has been considered is fetching the workload identity materials through the _istio-agent_ calling a [SPIFFE Workload API](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_API.md) implementation; this would require adding a new path to the _istio-agent_ Secrets Manager logic.

These ideas were discussed at Networking WG Meeting on [Nov 11, 2021](https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#heading=h.6wqx1ytjoh28). 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
@johnzheng1975 I guess this is what you want
