### ISSUE TITLE
Overriding includeInboundPorts during istiod deployment doesn't reflect when .Values.istio_cni.enabled

### ISSUE THREAD

**Issue by anastasiagrinman** [istio/istio#37185]
### Bug Description

I can confirm that on tag version 1.12.2, the annotation "traffic.sidecar.istio.io/includeInboundPorts" doesn't get override values from values.yaml  when setting  .Values.istio_cni.enabled.
So in cni plugin logs the parameter is get:  INBOUND_PORTS_INCLUDE=* and the override values is not reflected.

In injection-template.yaml and gen-istio.yaml there is:
traffic.sidecar.istio.io/includeInboundPorts: "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` `*` }}",

### Version

```prose
1.12.2
```

**Comment by anastasiagrinman** [comment]
Any progress on this ticket?

**Comment by bianpengyuan** [comment]
This was fixed at 1.12.2: https://github.com/istio/istio/blob/af0d66fd0aa363e9a7b0164f3a94ba36252fe60f/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L21

Are you sure you upgrade Istio properly, that the sidecar injection template is also updated to 1.12.2?
