### ISSUE TITLE
Upgrading Istio

### ISSUE THREAD

**Issue by Stono** [istio/istio#3720]
Hey, 
Following on from the request from @nmittler on our call this week, I'm raising this issue to talk about how we (AutoTrader) handle releases of istio at the moment, and also to talk about how we can minimise the risk of unexpected outages whilst upgrading between istio versions. 

I appreciate that this project is young, we haven't hit a major version release yet and backwards compatibility is not really supported (or expected).  However for those of us who I would consider "early adopters" of istio at an enterprise level, we could do with a little more support to enable us to effectively adopt your product at this early stage, to facilitate (ideally) zero downtime upgrades.

My intention is to use this issue to document our experiences going through Istio version updates, so we can continually learn and fine tune that process to ideally get to a point which doesn't (frankly) terrify me :-)

As a starter for ten, I thought you may be interested to see how we currently do istio releases :-) 

## generate-istio.rb
We use [this script](https://gist.github.com/Stono/73c4528a5c3497bbdba3747c7d39fba6) to download a given version of istio, the script then does the following actions:

  - Separates out the `istio-auth.yaml`, relevant addons and injector configuration into multiple helm charts (istio, istio-crd, istio-prometheus, istio-grafana, istio-jaeger).  
  - When creating the individual files, it makes certain AutoTrader specific modifications for example, adding the standard helm chart labels, making all services internal (10.x) ip's, editing the injector config, ignoring some bits we're not interested in, etc.

## chart vendor/custom
When `generate-istio.rb` runs, it puts all of the "vendor" templates into `chart-name/templates/vendor`, this is because each chart also has `chart-name/templates/custom`, which is where we put custom manifests associated with the given product.  For example; on prometheus, grafana and jaeger we have custom ingress definitions which we wouldn't ever submit back to you as pull requests because they're very unique to us.

## install-istio.sh
We then use [this script](https://gist.github.com/Stono/90991972655fe54edbd8fac2cee49f5d) to actually install each helm chart in order, and also to do the manual tasks associated with setting up the istio sidecar injector

As all of the above is stored under git, what we're effectively able to do is run `generate-istio.rb <version>` to re-template all of these charts and clearly see with a `git-diff` what has changed.  From that we attempt to infer what <might> break.  And herein is the problem, usually we miss something.

## What this ends up looking like.
This is me going from `0.5.0`, to `0.5.1`, using this script:

```
❯ ./generate-templates.rb
Istio version (0.5.1): 0.5.1
Ignoring istio/templates/vendor/namespace/istio-system.yaml
writing istio/templates/vendor/rbac/role/istio-pilot-istio-system.yaml
writing istio/templates/vendor/rbac/role/istio-sidecar-injector-istio-system.yaml
writing istio/templates/vendor/rbac/role/istio-mixer-istio-system.yaml
writing istio/templates/vendor/rbac/role/istio-ca-istio-system.yaml
writing istio/templates/vendor/rbac/role/istio-sidecar-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-pilot-admin-role-binding-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-sidecar-injector-admin-role-binding-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-ca-role-binding-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-ingress-admin-role-binding-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-sidecar-role-binding-istio-system.yaml
writing istio/templates/vendor/rbac/role-binding/istio-mixer-admin-role-binding-istio-system.yaml
writing istio/templates/vendor/configmap/istio-mixer.yaml
writing istio/templates/vendor/service/istio-mixer.yaml
writing istio/templates/vendor/service-account/istio-mixer-service-account.yaml
writing istio/templates/vendor/deployment/istio-mixer.yaml
writing istio/templates/vendor/custom-resources/rules.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/attributemanifests.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/circonuses.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/deniers.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/fluentds.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/kubernetesenvs.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/listcheckers.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/memquotas.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/noops.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/opas.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/prometheuses.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/rbacs.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/servicecontrols.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/stackdrivers.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/statsds.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/stdios.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/apikeies.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/authorizations.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/checknothings.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/kuberneteses.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/listentries.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/logentries.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/metrics.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/quotas.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/reportnothings.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/servicecontrolreports.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/tracespans.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/serviceroles.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/servicerolebindings.config.istio.io.yaml
writing istio-crd/templates/vendor/attributemanifest/istioproxy.yaml
writing istio-crd/templates/vendor/attributemanifest/kubernetes.yaml
writing istio-crd/templates/vendor/stdio/handler.yaml
writing istio-crd/templates/vendor/logentry/accesslog.yaml
writing istio-crd/templates/vendor/rule/stdio.yaml
writing istio-crd/templates/vendor/metric/requestcount.yaml
writing istio-crd/templates/vendor/metric/requestduration.yaml
writing istio-crd/templates/vendor/metric/requestsize.yaml
writing istio-crd/templates/vendor/metric/responsesize.yaml
writing istio-crd/templates/vendor/metric/tcpbytesent.yaml
writing istio-crd/templates/vendor/metric/tcpbytereceived.yaml
writing istio-crd/templates/vendor/prometheus/handler.yaml
writing istio-crd/templates/vendor/rule/promhttp.yaml
writing istio-crd/templates/vendor/rule/promtcp.yaml
writing istio-crd/templates/vendor/kubernetesenv/handler.yaml
writing istio-crd/templates/vendor/rule/kubeattrgenrulerule.yaml
writing istio-crd/templates/vendor/kubernetes/attributes.yaml
writing istio/templates/vendor/configmap/istio.yaml
writing istio/templates/vendor/custom-resources/destinationpolicies.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/egressrules.config.istio.io.yaml
writing istio/templates/vendor/custom-resources/routerules.config.istio.io.yaml
writing istio/templates/vendor/service/istio-pilot.yaml
writing istio/templates/vendor/service-account/istio-pilot-service-account.yaml
writing istio/templates/vendor/deployment/istio-pilot.yaml
Ignoring istio/templates/vendor/service/istio-ingress.yaml
writing istio/templates/vendor/service-account/istio-ingress-service-account.yaml
Ignoring istio/templates/vendor/deployment/istio-ingress.yaml
writing istio/templates/vendor/service-account/istio-ca-service-account.yaml
writing istio/templates/vendor/deployment/istio-ca.yaml
writing istio-grafana/templates/vendor/service/grafana.yaml
Ignoring istio-grafana/templates/vendor/deployment/grafana.yaml
writing istio-prometheus/templates/vendor/configmap/prometheus.yaml
writing istio-prometheus/templates/vendor/service/prometheus.yaml
Ignoring istio-prometheus/templates/vendor/deployment/prometheus.yaml
writing istio-prometheus/templates/vendor/service-account/prometheus.yaml
writing istio-prometheus/templates/vendor/rbac/role/prometheus.yaml
writing istio-prometheus/templates/vendor/rbac/role-binding/prometheus.yaml
writing istio/templates/vendor/service/istio-sidecar-injector.yaml
writing istio/templates/vendor/service-account/istio-sidecar-injector-service-account.yaml
writing istio/templates/vendor/deployment/istio-sidecar-injector.yaml
writing manual/istio-sidecar-injector.yaml
```

As you can see, I'm then able to go an have a look at the diff and validate the changes
```
❯ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   istio-crd/Chart.yaml
	modified:   istio-grafana/Chart.yaml
	modified:   istio-jaeger/Chart.yaml
	modified:   istio-prometheus/Chart.yaml
	modified:   istio/Chart.yaml
	modified:   istio/templates/vendor/deployment/istio-ca.yaml
	modified:   istio/templates/vendor/deployment/istio-mixer.yaml
	modified:   istio/templates/vendor/deployment/istio-pilot.yaml
	modified:   istio/templates/vendor/deployment/istio-sidecar-injector.yaml
	modified:   manual/istio-sidecar-injector-configmap-release.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	istio-prometheus/templates/vendor/rbac/
	istio-prometheus/templates/vendor/service-account/
```

And if I'm happy with it, we do the helm deploy:
```
❯ helm ls
istio                     	8       	Sat Feb 17 17:50:37 2018	DEPLOYED	istio-0.5.1                          	istio-system
istio-crd                 	8       	Sat Feb 17 17:50:39 2018	DEPLOYED	istio-crd-0.5.1                      	istio-system
istio-grafana             	8       	Sat Feb 17 17:50:40 2018	DEPLOYED	istio-grafana-0.5.1                  	istio-system
istio-jaeger              	8       	Sat Feb 17 17:50:43 2018	DEPLOYED	istio-jaeger-0.5.1                   	istio-system
istio-prometheus          	4       	Sat Feb 17 17:50:42 2018	DEPLOYED	istio-prometheus-0.5.1               	istio-system
```

## Suggestions
A great start would be "upgrade notes" between versions, making it very clear what breaking changes you're aware of in that releases and any **manual steps** that would be required in order to effect an upgrade.  

It would also be great to have some way of sanity testing the installation, we're getting to the point where we may write a suite of black box tests to validate the installation, but that feels like something you probably already do and could expose for people to validate their own installations?

I'm totally open to other ideas :-)

**Comment by yusuoh** [comment]
Hi Karl, Thanks for raising the issue.

We have an e2e upgrade test and we are going to add it to release qualification tests soon.
https://github.com/istio/istio/tree/master/tests/e2e/tests/upgrade

For each release, we will run the upgrade tests against a list of old versions and record the results. And if there is any upgrade failure or workaround needed, we will also document those breaking changes.

I am going to add more documents to explain the upgrade process and publish the test results. Please feel free to let me know if there's any other missing stuff.

**Comment by Stono** [comment]
Sounds like a great start!  I will keep you updated with how my upgrades go and any issues that I encounter.

Ideally I'd like to get to 3 or 4 successive releases without issue before I'm happy to "go to prod" with istio.

**Comment by Stono** [comment]
Hey!
As promised, this was my experience going from `0.5.1` to `0.6.0`.  I appreciate that some of the issues here may be helm related, but as helm is going to be a lot of peoples primary way of handling the deployments I figured it's good to talk holistically about my experience here.

Firstly, I ran the scripts I've referenced above and generated [this diff](https://github.com/istio/istio/files/1785047/0.5.1-0.6.0.txt) for the changes that affected us, nothing untoward stood out so I decided to run the helm upgrade.

```
Error: UPGRADE FAILED: no CustomResourceDefinition with the name "v1alpha2routerules.config.istio.io" found
```

This didn't really make sense, as it did exist.  So I had to take manual intervention and delete the resource.  I rolled back the failed helm deployment, then did helm upgrade again:

```
Error: UPGRADE FAILED: no CustomResourceDefinition with the name "apikeys.config.istio.io" found
```

Now, in the diff I noticed:
```
-  name: apikeys.config.istio.io
+  name: apikeies.config.istio.io
```

Guessing this was some how related, so I went down the route of manually deleting this too.

However this third rollback resulted in helm being in a broken state (no valid deployed releases) so the next deployment failed with:

```
Error: UPGRADE FAILED: "istio" has no deployed releases
```

Argh!

At this point I decided to do `helm delete --purge istio` to get rid of it and do a fresh deployment.

```
Release "istio" does not exist. Installing it now.
[debug] CHART PATH: /ciagents/pipelines/helm-platform-istio/istio

Error: release istio failed: customresourcedefinitions.apiextensions.k8s.io "destinationrules.config.istio.io" already exists
```

Some legacy artifacts were left behind by helm it seems... so I purged once again, and this time manually deleted the `istio-system` namespace.

```
[go] Task: ./install.sh dev.yamltook: 22.718s
[go] Current job status: passed
```

Joy!  Helm deployed... however none of our services could now communicate.  After some digging we realised this was because:

  - We had deleted istio (which uses mutual tls and a self signed CA)
  - Reinstalled istio
  - Recreated all the pods so they're injected with 0.6.0
  - However they were using secrets generated by the old self signed CA.

So we ended up writing a script to 'clean remove' istio, and all the secrets:

```
#!/bin/bash

echo "Deleting istio components..."
array=( istio istio-crd istio-grafana istio-prometheus istio-jaeger )
for i in "${array[@]}"
do
 	echo " - Removing: $i"
	helm del --purge $i
done

echo "Removing all custom resource definitions..."
kubectl get crd | grep -i istio | awk '{print $1}' | xargs -n 1 kubectl delete crd

echo "Deleting istio namespace..."
kubectl delete --cascade namespace istio-system

echo "Removing all istio secrets..."
kubectl get secrets --all-namespaces | grep "istio\." | awk '{print "kubectl delete secret -n "$1" "$2}' | bash -

echo "Removing mutating webhook stuff..."
kubectl delete MutatingWebhookConfiguration istio-sidecar-injector
```

After this, we did **another** installation, which worked and our services were back online.  

Our learnings from this were:

  - Helm for some reason doesn't clean up resources properly
  - Helm gets into a messed up state if you rollback a deployment which was a rollback of a previously failed deployment (will make a more tangible example and raise with helm directly)
  - Sidecars don't validate their outgoing certificate against the istio ca, to rotate if needed (what happens when the main CA rotates after 1 year?)

Not a fun experience :-)

**Comment by yusuoh** [comment]
Thanks for sharing the experience. I think we should have some e2e tests for Helm install/upgrade/rollback. Currently we only test the canonical k8s yaml files.

**Comment by nmittler** [comment]
@costinm FYI

**Comment by Stono** [comment]
FYI we also recently got burned by this https://github.com/kubernetes/helm/issues/3668.  I don't know if you plan to make helm your "primary" method of deploying your product, if you do it might be worth giving consideration to the fact that in some ways you'd be tying yourself to the reliability of that product too.

**Comment by nmittler** [comment]
@costinm @ldemailly @hklai 

Do we know what caused this upgrade problem? Was it documented in the release?

**Comment by Stono** [comment]
We should have any historical logs etc if there is anything you want me to grab, let me know.

**Comment by ldemailly** [comment]
I don't know that we have a test of upgrade with 0 downtime yet, @yusuoh would know

**Comment by Stono** [comment]
> Afaik while we do our best to not break upgrades from monthly to monthly, it's not a requirement yet, probably only post 0.8(lts) will it be.

^^ Just to be clear, I know/expect this.  I'm just documenting all of my experiences for verbosity.

**Comment by ldemailly** [comment]
@Stono your report is very much appreciated

It's actually not expected that 0.6 proxy wouldn't talk to 0.7 control plane

When you say 30s outage, do you mean because it took you 30s to upgrade the apps, or it resolve itself after 30s (0.6 envoy to 0.7 control plane)

**Comment by munrodg** [comment]
Closing due to staleness, please reopen if this remains an issue.
