### ISSUE TITLE
Renaming base chart as istio base

### ISSUE THREAD

**Issue by anastasiagrinman** [istio/istio#37205]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Rename Istio base chart name to istio-base

**Describe alternatives you've considered**
The chart name cannot have "base" name, since there a lot of base projects and the chart needs to be defined as an base with istio context.
ref: https://artifacthub.io/packages/helm/istio-official/base

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Why not? When you install you use `helm install istio/base`. It seems redundant to put Istio twice. Everything is namespaced so I don't see any reason to prefix things with Istio?

**Comment by rimusz** [comment]
I think it makes sense to rename it to `Istio-base` as usually all of us have many helm repos for our use, so the helm chart should be named properly as well, we cannot only really on helm repo local name, which can be anything.

**Comment by howardjohn** [comment]
I am still not seeing the issue. When you install it you can name it whatever you want including istio-base
