### ISSUE TITLE
Provide easy mechanism to override envoy runtime flags in bootstrap

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37202]

**Comment by hzxuzhonghu** [comment]
Once i got a requirement implementing RTDS, but i rejected it as it is not a common case. Not sure how is this like

**Comment by howardjohn** [comment]
My plan was just allow env var to set bootstrap ones. Not sure we need full rtds?

**Comment by ramaraochavali** [comment]
Given the number of runtime variables that we add are few, I think adding them as env var is fine. We may not need full rtds (which might require api to configure etc...)

**Comment by howardjohn** [comment]
https://github.com/istio/api/pull/2239
