### ISSUE TITLE
telemetryz debug endpoint always returns nothing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37218]
Because all fields are non-exported, json will not show them.

I don't know what we can really show that is better anyways though - the known resource types can already be seen with configz

**Comment by douglas-reid** [comment]
I forget what the thought was when we created this endpoint.  Was it to show effective config for a resource?

**Comment by zirain** [comment]
> I forget what the thought was when we created this endpoint. Was it to show effective config for a resource?

Is there anything concerns if we make telemetryz exported?
