### ISSUE TITLE
Can I use istio_request_duration_milliseconds_count instead of istio_requests_total for metrics query?

### ISSUE THREAD

**Issue by chinaran** [istio/istio#37226]

**Comment by howardjohn** [comment]
Both metrics can be used for different types of query. Depends what you are trying to lookup

**Comment by chinaran** [comment]
@howardjohn Thanks for your reply.
I found that the labels and value of istio_request_duration_milliseconds_count and istio_requests_total are almost the same.
Before, I used istio_requests_total to query the number of requests, rps. Use istio_request_duration_milliseconds_count to query the average response time.
Now, I want to query only using istio_request_duration_milliseconds_count, so the code is more uniform and the storage of prometheus is reduced.

**Comment by bianpengyuan** [comment]
I think it will work. Easy way to verify is probably put two queries / graph side by side, and make sure they work are the same for your use case.
