### ISSUE TITLE
bug-report: support distroless

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37235]
We should make sure bug-report works well with distroless. This may mean gracefully disabling some info, or switching the method we use to extract it, etc

**Comment by RaghavRoy145** [comment]
I would like to take this task up as a first time contribution here if there's still a need for this. I've already started going over relevant code for this, and any inputs are probably very useful!

**Comment by howardjohn** [comment]
Sure, the code is under `tools/bug-report`. You can install like https://istio.io/latest/docs/ops/configuration/security/harden-docker-images/ then run `istioctl bug-report` and I suspect a lot of things will sell

**Comment by howardjohn** [comment]
I can't think of any good ways to execute those without baking the functionality into `pilot-agent` (wedo have `pilot-agent request` as a locked down `curl` equiviilent, so its not unprecedented... but probably not worth it). For ad-hoc usage users could use ephemeral containers but that will be too expensive to do for a large number I suspect.

**Comment by cebernardi** [comment]
Could the ephemeral container option be a `istioctl` feature, but only enabled if the users explicitly ask for it?

Like, in case of distroless, `istioctl bug-report` doesn't execute the identified failing checks, and notify the users that there is the option to re-run the checks with an ephemeral container?

**Comment by howardjohn** [comment]
I feel like running ephemeral is too invasive - not worth it. I would rather just skip the checks. They are the least useful ones anyways really

**Comment by cebernardi** [comment]
thank you for your input.

Would you see a warning to the users ("this check has been skipped") or a silent skip? 

Is there any ongoing activity on this issue? I can see a closed PR above

**Comment by howardjohn** [comment]
hmm, missed the above PR. One note on it is we already fetch the Pod specs, so looking up the IstioOperator and deployment is costly and not accurate - we can look at the pod image directly. That may not be 100% accurate if they use custom images, so we can just match the error "netstat not found" (or whatever it is) and ignore it probably.

I don't mind warning or silently ignore
