### ISSUE TITLE
Unbalanced load balancing

### ISSUE THREAD

**Issue by ggeighty8** [istio/istio#37231]
### Bug Description

Hi,

We have 6 replicas of a service running behind istio in an EKS cluster. We are noticing that the APIs are getting routed to one of the 6 replicas a lot more than the other 5, like 70% of an API is landing on one of the replicas and the other 30% on the remaining 5. I do understand that the routing will not happen uniformly but the deviation we are seeing here is significant.

We did try and debug the routing as per the instructions provided in https://www.youtube.com/watch?v=FbYBO7Pi2d8 but could not find anything wrong.

Kindly let us know any further steps that we can take here and also any more info I can furnish that might be helpful.

Regards
Yasha C

### Version

```prose
$ istioctl version
client version: 1.12.2
control plane version: 1.11.4
data plane version: 1.11.4 (60 proxies)

$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.5-eks-bc4871b

$ helm version --short
v3.6.3+gd506314
```

### Additional Information

In the following pic, we can see that one of the replicas got almost 10 times more request than the other:

<img width="744" alt="Screenshot 2022-02-09 at 5 20 13 PM" src="https://user-images.githubusercontent.com/7677904/153196081-f14518b6-1c0f-4546-8760-2dd70f0c1ce8.png">

Destination rule:
```apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    argocd.argoproj.io/instance: a-service
  name: a-service
  namespace: ns
spec:
  host: a-service.ns.svc.cluster.local
  subsets:
    - labels:
        version: stable
      name: stable
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 1000ms
        maxConnections: 400
        tcpKeepalive:
          interval: 75s
          time: 60m
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      baseEjectionTime: 5m
      consecutive5xxErrors: 0
      consecutiveGatewayErrors: 10
      interval: 30s

**Comment by ramaraochavali** [comment]
Looks like they are being distributed as per locality. Please refer to https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting

**Comment by ggeighty8** [comment]
Thanks @ramaraochavali. We are not using LocalityLoadBalancerSetting specifically and all our pods run on AWS us-west-2 region. Is there a chance that there are some default values that are getting used here?

**Comment by ggeighty8** [comment]
Thanks, @ramaraochavali. I tried searching through the docs and this fact is not quite apparent. Can the document please be updated to explicitly mention that LocalityLoadBalancerSetting is enabled by default?
