### ISSUE TITLE
On multi-primary clusters, istiod cannot push svc‘s endpoints which is for a pod not be injection in another cluster

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#37258]
### Bug Description

On a multi-primary clusters if a pod not be injected, it will be not be discovered on another cluster.

Actually I'm not sure it is a bug. But I can not found any information about this situation on document. May be some configuration can help me fix it.

In the cluster where the service is located, the endpoint can be found on sidecar.
```
$ .istioctl/bin/istioctl pc endpoint helloworld-v2-76bb75f77c-d9xhc.core | grep helloworld-v2.sample.svc.cluster.local
172.22.55.132:5000               HEALTHY     OK                outbound|5000||helloworld-v2.sample.svc.cluster.local
```
In another cluster, the endpoint can not be found on sidecar. But the cds can be found.
```
$ KUBECONFIG=.kube/another-cluster.yaml .istioctl/bin/istioctl pc endpoint xxx | grep helloworld-v2.sample.svc.cluster.local

$  KUBECONFIG=.kube/another-cluster.yaml .istioctl/bin/istioctl pc cluster xxx | grep helloworld-v2.sample.svc.cluster.local
helloworld-v2.sample.svc.cluster.local                         5000      -          outbound      EDS              global.default
```

### Version

```prose
$ .istioctl/bin/istioctl version
client version: 1.11.5
istiod version: 1.11-dev
istiod version: 1.11-dev
pilot version: 1.10-dev
data plane version: 1.11.5 (366 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [x] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
This is intended IFF they are in different *networks*, not just clusters. This is because we require mtls to traverse the east-west gateway

**Comment by Patrick0308** [comment]
Thanks @howardjohn. I get it
