### ISSUE TITLE
how to split the traffic with no of connection

### ISSUE THREAD

**Issue by rampatnaik** [istio/istio#37262]
### Bug Description

Hello

I am using istio 1.12 

Can you guide me how can I split the traffic base on no of connection ..

In virtual service I cannot find any clue 

### Version

```prose
Client Version: v1.19.2
Server Version: v1.20.12-gke.1500

helm  : v3.7.2+g663a896
```

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/? If that is not what you are looking for please provide more details.
