### ISSUE TITLE
RequireMultiPrimary skips too many tests

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#37265]
#35599 added this skip (originally called `RequireLocalControlPlane`) with the plan that we'd unskip pretty quickly and make istiodless the default. 

We're currently in a state where we've removed coverage on things that do work with primary-remote (in-cluster istiod). Since that is the flavor of primary remote that we're shipping, we should recover this test coverage (only skip under istiodless job). 

cc @nmittler @frankbu

**Comment by frankbu** [comment]
Sounds like all we want is for this function to return false if any of the clusters are !primary AND !istiodless. Is that right?

Btw, why has it been renamed to `RequireMultiPrimary()` ... that seems to imply that it requires multiple clusters and would return false if we have a single cluster topology (one primary cluster), but that returns true. Shouldn't it be named `RequireAllPrimary()` instead?

**Comment by nmittler** [comment]
@stevenctl is there any test at this point that wouldn't work with primary-remote?

**Comment by nmittler** [comment]
not stale
