### ISSUE TITLE
Update go-control-plane to master

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#3728]
Please update the library to the latest. There's been major refactoring of the protos that need to be taken care of.

**Comment by kyessenov** [comment]
cc @ldemailly for vendor assistance.
waiting for some in-progress PRs to be merged before doing this.

**Comment by ldemailly** [comment]
in progress in control-plane ? or here ? which?

**Comment by kyessenov** [comment]
@gnirodi has some in-flight PR. the in-flight PR in control-plane is not
changing package names. we need to get through package name change since it
was the last promised breaking change.

**Comment by costinm** [comment]
Kuat - I believe Gautam is mostly ready, so early next week you can upgrade.

**Comment by rshriram** [comment]
obsolete
