### ISSUE TITLE
Allow RequestAuthentication policy to require a set of JWT claims

### ISSUE THREAD

**Issue by barbaramcinnes** [istio/istio#37294]
**Describe the feature request**

RequestAuthentication policies allow us to apply JWT validation rules when a jwt is presented to a workload - this includes checking exp claim if present.  If no exp claim is present however, the token is considered valid (assuming all other checks pass).  It would be very useful to be able to prescribe a set of claims that must be present in the token as part of the RequestAuthentication policy. This will mean that a jwt validation policy can be applied at a namespace/mesh level and kept consistent across services. 

**Describe alternatives you've considered**

The documented approach to this is to use a RequestAuthorization policy in combination with the RequestAuthentication policy.  There you can add conditions such as:

```
   when:
   - key: request.auth.claims[exp]
     values: ["*"]
```

to require certain claims.  This is awkward, as the jwt policy is spread out over two different places. What's more, it prevents the jwt validation policy from being applied at a namespace or mesh level.  Each service is likely to have a custom RequestAuthorization policy to define specific endpoint restrictions.  If any one ALLOW rule matches a request it will be allowed because of authorization policy rules.  This means parts of the jwt policy now need repeated in each service's own authorization policy, redefining it multiple times and making it more likely that a mistake will be made.

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

This is not a request to match on specific values.  It is just about requiring that a certain claim is present (regardless of value).  For example, requiring exp claim will force an expiry check in the authentication policy instead of accepting tokens missing exp claim. Our services currently require sub and exp claims be present in any token.  We would like to move our token validation in to istio, but to do so will require us to spread these rules over each service's RequestAuthorizartion policies.  This is not easy to maintain or to enforce.

**Comment by barbaramcinnes** [comment]
sorry to see that his has closed: this is the reason we have decided not to use istio for our jwt authorization policies.

**Comment by keithmattix** [comment]
Not stale

**Comment by keithmattix** [comment]
On substance, can you explain why utilizing AuthorizationPolicies and RequestAuthentication is a blocker for your use case? AuthorizationPolicy is the central authz policy object in Istio and combining it with RequestAuthentication is an established pattern. Am I correct in understanding that combining the two results in the enforcement you want?

**Comment by barbaramcinnes** [comment]
> On substance, can you explain why utilizing AuthorizationPolicies and RequestAuthentication is a blocker for your use case? AuthorizationPolicy is the central authz policy object in Istio and combining it with RequestAuthentication is an established pattern. Am I correct in understanding that combining the two results in the enforcement you want?

Hi @keithmattix We've moved on from this now and will not be using Istio to do our jwt enforcement. I've outlined the reasons pretty clearly in the issue description above so don't have much more to add, except I don't think it's a workable approach in practice. Hope this helps!
