### ISSUE TITLE
Document bug : x-forwarded-client-cert-headers matrix needs an update

### ISSUE THREAD

**Issue by gowrisankar22** [istio/istio#37292]
### Bug Description

As per the document default config is `SANITIZE` but configuration for the `x-forwarded-client-cert-headers` after the installation is set to `SANITIZE_SET`. 

This has been set from the gateway component. 
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/gateway.go#L610

Official document:
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers

We have to adjust the document accordingly. 

### Version

```prose
istioctl version                     
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (31 proxies)
```

### Additional Information

```
istioctl pc listeners istio-ingressgateway-8566bc5bdb-wmfts.istio-system -o json | grep forwardClientCertDetails 
                            "forwardClientCertDetails": "SANITIZE_SET",
                            "forwardClientCertDetails": "SANITIZE_SET",
                            "forwardClientCertDetails": "SANITIZE_SET"
```

**Comment by howardjohn** [comment]
Thanks, I think the doc is just copy+pasted from Envoy which has a different default
