### ISSUE TITLE
[Testing] Make all telemetry tests support multiple clusters

### ISSUE THREAD

**Issue by nmittler** [istio/istio#37308]
### Bug Description

This is just for the telemetry tests.

There are a ton of tests that are currently skipped when running in multicluster mode. We need to identify and fix any tests that are skipped when using multiple clusters.

Some things to search for:

- `RequireSingleCluster`, `RequireMultiPrimary` ... both should be removed.
- `.IsMulticluster()` identifies some call sites that are multicluster-specific

### Version

```prose
NA
```

**Comment by douglas-reid** [comment]
@zirain do you think you'd have any time to look into this?

**Comment by zirain** [comment]
I will take a look at this next week.
