### ISSUE TITLE
Vendor from the gometalinter.v2 build image for stable linter tests

### ISSUE THREAD

**Issue by myidpt** [istio/istio#3731]
Our linter tests fail due to gometalinter.v2 download timeout:

+ go get -u gopkg.in/alecthomas/gometalinter.v2
package gopkg.in/alecthomas/gometalinter.v2: unrecognized import path "gopkg.in/alecthomas/gometalinter.v2" (https fetch: Get https://gopkg.in/alecthomas/gometalinter.v2?go-get=1: dial tcp 45.33.37.13:443: i/o timeout)
Makefile:269: recipe for target 'lint' failed
make: *** [lint] Error 1

https://circleci.com/gh/istio/istio/36525?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

We should vendor the gometalinter.v2 build images (or via other similar ways) to make sure our linter tests are stable.

**Comment by hklai** [comment]
@ldemailly any idea why it is currently not vendored?

**Comment by ldemailly** [comment]
it used to be a while ago, I think it got lost in the circleci/makefile shuffle

**Comment by cmluciano** [comment]
@hklai @costinm Any ideas if this is still relevant?
