### ISSUE TITLE
Pilot root CA file change does not update sidecar mutatingwebhook caBundle

### ISSUE THREAD

**Issue by SpectralHiss** [istio/istio#37315]
### Bug Description

When using istio-csr as the identity solution for istio, we disable citadel and load the TLS cert for pilot as well as the root of trust CA from a [configmap](https://github.com/cert-manager/istio-csr/blob/43131ddc7a9d13c86ff21a98b6c55e45c160fec5/hack/istio-config-1.10.0.yaml#L52) .

The current logic for Webhookpatcher and the backing Watcher seems to be notified of filesystem changes through an [istiodCertWatcher](https://github.com/istio/istio/blob/2a5e10406d790acba2e054bf3f0d83dfd7f0e97f/pilot/pkg/bootstrap/sidecarinjector.go#L96) keycertbundle.watcher.
This watcher seems to not have implemented looking at CA file but only at key and cert, forcing a restart of pilot for the caBundle to be correct and causing a lot of confusion with "unknown certificate authority" error.
This can manifest to users, if upgrading to use istio-csr from self-signed or external "plug-in" CA or if doing a break-glass root rotation (which requires a brief period of having both roots eg: https://blog.christianposta.com/diving-into-istio-1-6-certificate-rotation/).

There is a TODO note which demonstrates that support for the ca syncing was always lacking in the webhook patcher  (since that block initialises the watcher the patcher subscribes to):
https://github.com/istio/istio/blob/2a5e10406d790acba2e054bf3f0d83dfd7f0e97f/pilot/pkg/bootstrap/certcontroller.go#L228

Bear in mind our requirement are a little unusual,  we can easily just add logic under that block to watch the CAFile on disk, but one has to remember that in our scenario we have citadel off with ENABLE_CA_SERVER=false. 
So we need to ensure that all other CA methods are not inadvertently affected by this change as well.
I will submit a tentative PR to address above issue.

The wider issue that would be great to solve on top of this one is automatic re-issuance of certificate for sidecars themselves when CA changes either when detected through this path or through a change in the plugin-in ("cacerts" method) thus making the CA mechanisms truly extensible and great to operate but that can be the subject of another PR :)

### Version

```prose
tested on latest istio 1.12.4
and kind environment 1.21
```

**Comment by bianpengyuan** [comment]
> The wider issue that would be great to solve on top of this one is automatic re-issuance of certificate for sidecars themselves when CA changes either when detected through this path or through a change in the plugin-in ("cacerts" method) thus making the CA mechanisms truly extensible and great to operate but that can be the subject of another PR :)

Curious, in your case, isn't re-issuance of workload cert controlled by cert manager instead of istio?
