### ISSUE TITLE
Istio-cni pod fails to start UDS Log Server

### ISSUE THREAD

**Issue by rhrazdil** [istio/istio#37323]
### Bug Description

Hello, I'm hitting the same issue as described here: https://github.com/istio/istio/issues/35902

The istio-cni-node daemon set is running as root:
```
kind: DaemonSet
metadata:
  name: istio-cni-node
.......
spec:
      containers:
      - command:
        - install-cni
......
        securityContext:
          privileged: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
```

I've tried setting the `securityContext.privileged:` to `true`, and which helped.

### Version

```prose
$ istioctl version
client version: 1.13.0
control plane version: 1.13.0
data plane version: 1.13.0 (2 proxies)

$ kubetl version
Client Version: v1.22.6
Server Version: v1.22.6

$ cat /etc/redhat-release 
CentOS Stream release 8
```

### Additional Information

```
2022-02-14T15:43:02.206502Z	info	CNI install configuration: 
CNINetDir: /etc/cni/multus/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName: 
ChainedCNIPlugin: false
CNINetworkConfigFile: 
CNINetworkConfig: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "debug",
  "log_uds_address": "__LOG_UDS_ADDRESS__", 
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system" ]
  }
}
CNIEnableReinstall: true
LogLevel: warn
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile: 
SkipTLSVerify: false
K8sServiceProtocol: 
K8sServiceHost: 10.96.0.1
K8sServicePort: 443
K8sNodeName: istio-cni-node-6wdxz
UpdateCNIBinaries: true
SkipCNIBinaries: []
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock

2022-02-14T15:43:02.206523Z	info	CNI race repair configuration: 
Enabled: true
RunAsDaemon: true
NodeName: node01
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg: 
InitExitCode: 126
LabelSelectors: 
FieldSelectors: 

2022-02-14T15:43:02.206541Z	info	ControlZ available at 127.0.0.1:9876
2022-02-14T15:43:02.206645Z	info	Start a UDS server for CNI plugin logs
2022-02-14T15:43:02.206914Z	error	Failed to start up UDS Log Server: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
Error: failed to create UDS listener: failed to listen on unix socket "/var/run/istio-cni/log.sock": listen unix /var/run/istio-cni/log.sock: bind: permission denied
```

**Comment by howardjohn** [comment]
Are you on openshift or just centos nodes? Its plausible where we said "openshift needs privileged" we should have instead said "centos does"

**Comment by howardjohn** [comment]
I would not recommend a PodSecurityPolicy given they are deprecated. We should configure the Pod spec to use the minimal set of permissions - which we have mostly done in most areas, but plausible we have missed some places.

cc @bianpengyuan @jtrbs

**Comment by rhrazdil** [comment]
I see, thanks!

I checked the 1.10 release, and in this version, I **don't** see the following line in `install-cni` container:
```
2022-02-14T15:43:02.206645Z	info	Start a UDS server for CNI plugin logs
```
So this seems to be the new functionality, that requires root privileges.

**Comment by hzxuzhonghu** [comment]
Why startting a log server in CNI? Which component would send log to it?

**Comment by howardjohn** [comment]
Without it, the actual iptables setup code we run just goes to kubelet log.
This allows it to be seen with `kubectl log` on the CNI daemonset

**Comment by eadasiak** [comment]
Would it be possible to add an option to disable the UDS log server so that the CNI plugin can run as unprivileged?  I can live with the iptables setup code in the kubelet logs if it means I can run it without the elevated privileges.

**Comment by kushagraj81** [comment]
Hi @howardjohn 
I am facing the same issue with cni daemonset on seLinux, Is there any fix for this other than making privilege: true in securityContext?

**Comment by howardjohn** [comment]
@kushagraj81 can you open a new issue with info about the version you are on

**Comment by howardjohn** [comment]
Thanks @kushagraj81 . I think this is the same as https://github.com/istio/istio/issues/53849#issuecomment-2504678135, lets merge to that issue?

**Comment by kushagraj81** [comment]
Yeah, Sure
