### ISSUE TITLE
Better support ExternalName

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37331]
Example config:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: b-ext
  namespace: echo
spec:
  ports:
  - name: tcp
    port: 80
    targetPort: 18080
  type: ExternalName
  externalName: b.echo.svc.cluster.local
```

Kubernetes behavior: `b-ext` creates a CNAME record for `b`. Port is not relevant.

Istio (today): Create a DNS cluster for each port, which ends up resolving to Cluster IP. Match on Host header (http), SNI (tls), or just port (TCP) (meaning it captures all traffic on that port).

Issues:
* Port matters in Istio but not Kubernetes
* We get minimal functionality because we only have the cluster IP. No load balancing, auto mtls, etc

Proposal option 1: just add additional matchers to existing Service definitions. For example, above we would add a match for `b-ext` everywhere we match for `b`. This works for HTTP and TLS; for TCP it is already not needed as it works today (envoy will see traffic to `b` and `b-ext` as the same). If there was no Service/ServiceEntry defined at all for the target `externalName`, then we would end up just passing through.
Pros: simple and efficient to implement.
Pros: Behaves identically to Kubernetes.
Cons: cannot use ExternalName service to apply different policy to different resources (subset replacement)

Proposal option 2: create new listeners/routes/clusters for the Service. Instead of making a DNS cluster, create and EDS cluster and resolve the `externalName` in the control plane (not literally a DNS lookup, but make it an alias). If no ports are defined, inherent from the referenced Service. If ports are defined, we should probably use them.
Pros: allows override policy (subset replacement)
Cons: more expensive due to additional XDS config
Cons: only works for HTTP, unless we do DNS auto allocation

Past issues:
* https://github.com/istio/istio/issues/31640
* https://github.com/istio/istio/issues/30547
* https://github.com/istio/istio/issues/29846
* https://github.com/istio/istio/issues/24886
* https://github.com/istio/istio/issues/23463
* https://github.com/istio/istio/issues/20703
* https://github.com/istio/istio/issues/13479

**Comment by howardjohn** [comment]
note: knative uses ExternalName but I think it doesn't actually matter in this case. For mesh they override it with VS, and for non-mesh none of this applies.

**Comment by costinm** [comment]
IMO the safest path is for Service.ExternalName to behave exactly like in K8S if there is no Istio-specific config.

If Istio config is defined - VirtualService, ServiceEntry, etc - we treat it as source of truth, like any istio config.
Otherwise - we should not interfere, use pass-through mode - like we would do if the external service would be directly 
called.

This creates one slight problem -  if the target is a Cluser VIP of type TCP, we would intercept it and apply the LB and other policies associated with the service, but it should be equivalent with 'no istio present'. For HTTP - it would not match and fallback to pass-through. If users have STRICT mode or want this to use Istio configs - they can use ServiceEntry,etc.

**Comment by jacob-delgado** [comment]
I read over both this and the PR. I think this is the proper way to fix these issues. This could break some people, but being more opinionated for this is fine as it would help adoption.

I see this as more of an item for people migrating from vanilla K8s onto Istio. When a user is able to get all of their services having a sidecar then VirtualService/ServiceEntry should be the ideal way for them to configure their system and costin's approach of Istio being the source of truth is the best way forward. Istio being inconsistent with how vanilla K8s handles this make this more difficult for them to adopt Istio.

I'm not too familiar with how this affects Ingress.

**Comment by idouba** [comment]
Any update on this?

**Comment by hzxuzhonghu** [comment]
Option1 is not consistent with ServiceEntry, we donot respect the external name at all during the match.

Option 2:  resolve the externalName is too costy, and it is too costy, and in some env, controlplane can not access outside, may not be able to resolve.

We could not make a breaking change for externalname service ports。 We have documented its ports are required for istio.
IMO, we can just allocate an ip for b-ext.echo.svc.cluster.local, and everything else works as DNS typed SE.

```
// apiVersion: networking.istio.io/v1beta1
// kind: ServiceEntry
// metadata:
//   name: external-svc-dns
// spec:
//   hosts:
//   - foo.bar.com
//   location: MESH_EXTERNAL
//   ports:
//   - number: 80
//     name: http
//     protocol: HTTP
//   resolution: DNS
//   endpoints:
//   - address: us.foo.bar.com
//     ports:
//       http: 8080
//   - address: uk.foo.bar.com
//     ports:
//       http: 9080
//   - address: in.foo.bar.com
//     ports:
//       http: 7080
```

**Comment by PetrMc** [comment]
is there a solution for https://istio.io/latest/docs/setup/install/multicluster/primary-remote/ and AWS EKS. As EKS doesn't provide IP for services. The injection on remote cluster fails with:
```
Warning  FailedCreate  3s (x11 over 8s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject/cluster/remote-istio-2/net/network1?timeout=10s": unsupported service type "ExternalName"
```
the service that is created:
```
$ kubectl get svc -n istio-system 
NAME     TYPE           CLUSTER-IP   EXTERNAL-IP                                                               PORT(S)             AGE
istiod   ExternalName   <none>       aa1c4672f10b146f8b78403f68cb4715-1959791052.us-east-1.elb.amazonaws.com   15012/TCP,443/TCP   10m
```

**Comment by howardjohn** [comment]
@PetrMc I think that is a complete different issue; this is about how we proxy traffic to ExternalName services. That seems like a legit issue though, but probably worth opening a new issue. I am not personally familiar with that codepath

**Comment by hzxuzhonghu** [comment]
>Warning  FailedCreate  3s (x11 over 8s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject/cluster/remote-istio-2/net/network1?timeout=10s": unsupported service type "ExternalName"

This is the error from kube-apiserver, webhook doesn't support external name type service

**Comment by PetrMc** [comment]
Thanks @hzxuzhonghu - can you think of different approach (access Istio control plane using different address)

@howardjohn - it seems that to get __Primary Remote__ working on EKS - the architecture changes would required. I'll create a PR to update the doc.


Thanks @hzxuzhonghu. Could you think of any alternative approach? For instance, accessing the Istio control plane using a different way not a k8s service? 

@howardjohn, It appears that in order to enable the __Primary Remote__ feature on EKS, there's a need for architectural adjustments. I'll be working on a pull request to update the documentation to mention EKS limitation.

**Comment by hzxuzhonghu** [comment]
If you take a look at k8s mutatingwebhookConfiguration api, there is a `WebhookClientConfig.URL`, which can be used instead of `WebhookClientConfig.Service`.

**Comment by hzxuzhonghu** [comment]
But i do remember in istio we do reconcile mutatingwebhookconfiguration, so not sure whether it works
