### ISSUE TITLE
Readiness probe failed and Reflector ListAndWatch failed

### ISSUE THREAD

**Issue by 1511563371** [istio/istio#37340]
### Bug Description

[##  istioctl install --set profile=demo -y  $$]

✔ Istio core installed
✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
  Deployment/istio-system/istiod (containers with unready status: [discovery])
✘ Egress gateways encountered an error: failed to wait for resource: resources n                                                     ot ready after 5m0s: timed out waiting for the condition
  Deployment/istio-system/istio-egressgateway (container failed to start: Contai                                                     nerCreating: )
✘ Ingress gateways encountered an error: failed to wait for resource: resources                                                      not ready after 5m0s: timed out waiting for the condition
  Deployment/istio-system/istio-ingressgateway (container failed to start: Conta                                                     inerCreating: )
- Pruning removed resources                                                                                                          Error: failed to install manifests: errors occurred during operation

[##  kubectl get pod -n istio-system  $$]
istio-egressgateway-6d8f7f46d8-ccs55    0/1     ContainerCreating   0          6m58s
istio-ingressgateway-8596f578fd-hz484   0/1     ContainerCreating   0          6m58s
istiod-57c6d96b9d-nxg4b                 0/1     Running             0          11m

[-------------------------------------------istiod isntall problem-------------------------------------------------------------------------]

[##  kubectl describe pod istiod-57c6d96b9d-nxg4b  -n istio-system   $$]

Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  14m                 default-scheduler  Successfully assigned istio-system/istiod-57c6d96b9d-nxg4b to node2
  Normal   Pulled     14m                 kubelet            Container image "docker.io/istio/pilot:1.10.5" already present on machine
  Normal   Created    14m                 kubelet            Created container discovery
  Normal   Started    14m                 kubelet            Started container discovery
  Warning  Unhealthy  4m (x200 over 13m)  kubelet            Readiness probe failed: Get "http://192.168.104.5:8080/ready": dial tcp 192.168.104.5:8080: connect: connection refused

[##  kubectl logs istiod-57c6d96b9d-nxg4b  -n istio-system   $$]

2022-02-15T14:05:21.783061Z     info    FLAG: --appNamespace=""
2022-02-15T14:05:21.783094Z     info    FLAG: --caCertFile=""
2022-02-15T14:05:21.783098Z     info    FLAG: --clusterID="Kubernetes"
2022-02-15T14:05:21.783101Z     info    FLAG: --clusterRegistriesNamespace="istio-system"
2022-02-15T14:05:21.783102Z     info    FLAG: --configDir=""
2022-02-15T14:05:21.783104Z     info    FLAG: --ctrlz_address="localhost"
2022-02-15T14:05:21.783112Z     info    FLAG: --ctrlz_port="9876"
2022-02-15T14:05:21.783116Z     info    FLAG: --domain="cluster.local"
2022-02-15T14:05:21.783117Z     info    FLAG: --grpcAddr=":15010"
2022-02-15T14:05:21.783120Z     info    FLAG: --help="false"
2022-02-15T14:05:21.783122Z     info    FLAG: --httpAddr=":8080"
2022-02-15T14:05:21.783124Z     info    FLAG: --httpsAddr=":15017"
2022-02-15T14:05:21.783127Z     info    FLAG: --keepaliveInterval="30s"
2022-02-15T14:05:21.783129Z     info    FLAG: --keepaliveMaxServerConnectionAge="30m0s"
2022-02-15T14:05:21.783131Z     info    FLAG: --keepaliveTimeout="10s"
2022-02-15T14:05:21.783132Z     info    FLAG: --kubeconfig=""
2022-02-15T14:05:21.783135Z     info    FLAG: --kubernetesApiBurst="160"
2022-02-15T14:05:21.783138Z     info    FLAG: --kubernetesApiQPS="80"
2022-02-15T14:05:21.783140Z     info    FLAG: --log_as_json="false"
2022-02-15T14:05:21.783142Z     info    FLAG: --log_caller=""
2022-02-15T14:05:21.783144Z     info    FLAG: --log_output_level="default:info"
2022-02-15T14:05:21.783145Z     info    FLAG: --log_rotate=""
2022-02-15T14:05:21.783147Z     info    FLAG: --log_rotate_max_age="30"
2022-02-15T14:05:21.783149Z     info    FLAG: --log_rotate_max_backups="1000"
2022-02-15T14:05:21.783151Z     info    FLAG: --log_rotate_max_size="104857600"
2022-02-15T14:05:21.783153Z     info    FLAG: --log_stacktrace_level="default:none"
2022-02-15T14:05:21.783157Z     info    FLAG: --log_target="[stdout]"
2022-02-15T14:05:21.783159Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2022-02-15T14:05:21.783160Z     info    FLAG: --monitoringAddr=":15014"
2022-02-15T14:05:21.783162Z     info    FLAG: --namespace="istio-system"
2022-02-15T14:05:21.783165Z     info    FLAG: --networksConfig="/etc/istio/config/meshNetworks"
2022-02-15T14:05:21.783169Z     info    FLAG: --plugins="[ext_authz,authn,authz]"
2022-02-15T14:05:21.783201Z     info    FLAG: --profile="true"
2022-02-15T14:05:21.783217Z     info    FLAG: --registries="[Kubernetes]"
2022-02-15T14:05:21.783220Z     info    FLAG: --resync="1m0s"
2022-02-15T14:05:21.783222Z     info    FLAG: --secureGRPCAddr=":15012"
2022-02-15T14:05:21.783225Z     info    FLAG: --tls-cipher-suites="[]"
2022-02-15T14:05:21.783227Z     info    FLAG: --tlsCertFile=""
2022-02-15T14:05:21.783229Z     info    FLAG: --tlsKeyFile=""
2022-02-15T14:05:22.089354Z     info    klog    Config not found: /var/run/secrets/remote/config
2022-02-15T14:05:22.097478Z     info    initializing mesh configuration ./etc/istio/config/mesh
2022-02-15T14:05:52.099037Z     info    klog    Trace[1969285722]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167 (15-Feb-2022 14:05:22.098) (total time: 30000ms):
Trace[1969285722]: [30.000971553s] [30.000971553s] END
2022-02-15T14:05:52.099086Z     error   klog    k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
2022-02-15T14:06:23.623497Z     info    klog    Trace[157366741]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167 (15-Feb-2022 14:05:53.622) (total time: 30000ms):
Trace[157366741]: [30.000945026s] [30.000945026s] END
2022-02-15T14:06:23.623565Z     error   klog    k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
2022-02-15T14:06:56.085820Z     info    klog    Trace[314959718]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167 (15-Feb-2022 14:06:26.085) (total time: 30000ms):
Trace[314959718]: [30.000371106s] [30.000371106s] END
2022-02-15T14:06:56.085861Z     error   klog    k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
2022-02-15T14:07:30.262991Z     info    klog    Trace[1078488231]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167 (15-Feb-2022 14:07:00.262) (total time: 30000ms):
2022-02-15T14:19:15.256502Z     error   klog    k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout

---[
note : 10.96.0.1:443 is ClusterIP for k8s Service,which belongs namepace default.
here it is:

[root@master1 ~]# kubectl get service -n default
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   
]

[-------------------------------------------ingressgateway isntall problem---------------------------------------------]

[##  kubectl describe pod istio-ingressgateway-8596f578fd-hz484  -n istio-system   $$]

Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    58m                  default-scheduler  Successfully assigned istio-system/istio-ingressgateway-8596f578fd-hz484 to node3
  Warning  FailedMount  56m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-data podinfo istio-ingressgateway-service-account-token-kbm42 istio-envoy ingressgateway-ca-certs ingressgateway-certs istiod-ca-cert istio-token config-volume]: timed out waiting for the condition
  Warning  FailedMount  53m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo ingressgateway-ca-certs istio-data ingressgateway-certs config-volume istiod-ca-cert istio-ingressgateway-service-account-token-kbm42 istio-envoy istio-token]: timed out waiting for the condition
  Warning  FailedMount  51m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-token istio-data ingressgateway-certs istio-ingressgateway-service-account-token-kbm42 istio-envoy config-volume podinfo ingressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  49m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy podinfo istio-token istio-ingressgateway-service-account-token-kbm42 config-volume ingressgateway-ca-certs istiod-ca-cert istio-data ingressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  47m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-envoy ingressgateway-certs istio-token podinfo config-volume istio-data ingressgateway-ca-certs istio-ingressgateway-service-account-token-kbm42]: timed out waiting for the condition
  Warning  FailedMount  44m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo istio-token config-volume istio-data ingressgateway-ca-certs istio-ingressgateway-service-account-token-kbm42 istiod-ca-cert ingressgateway-certs istio-envoy]: timed out waiting for the condition
  Warning  FailedMount  42m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo istio-envoy istio-data istio-token ingressgateway-certs ingressgateway-ca-certs config-volume istiod-ca-cert istio-ingressgateway-service-account-token-kbm42]: timed out waiting for the condition
  Warning  FailedMount  40m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-ca-certs istio-token ingressgateway-certs istio-ingressgateway-service-account-token-kbm42 config-volume istiod-ca-cert istio-data istio-envoy podinfo]: timed out waiting for the condition
  Warning  FailedMount  39m (x17 over 58m)   kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  3m8s (x25 over 38m)  kubelet            (combined from similar events): MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found

[--------------------------------------------egressgateway isntall problem---------------------------------------------]

Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    62m                   default-scheduler  Successfully assigned istio-system/istio-egressgateway-6d8f7f46d8-ccs55 to node3
  Warning  FailedMount  60m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-egressgateway-service-account-token-fbhsh istiod-ca-cert istio-token config-volume egressgateway-certs istio-data podinfo istio-envoy egressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  58m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy istiod-ca-cert istio-token istio-data egressgateway-ca-certs podinfo istio-egressgateway-service-account-token-fbhsh config-volume egressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  56m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo config-volume istio-data egressgateway-certs istio-egressgateway-service-account-token-fbhsh istio-token egressgateway-ca-certs istiod-ca-cert istio-envoy]: timed out waiting for the condition
  Warning  FailedMount  53m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[egressgateway-ca-certs config-volume istio-token egressgateway-certs istio-envoy istiod-ca-cert podinfo istio-egressgateway-service-account-token-fbhsh istio-data]: timed out waiting for the condition
  Warning  FailedMount  51m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-token podinfo istio-envoy config-volume istio-egressgateway-service-account-token-fbhsh istiod-ca-cert egressgateway-certs egressgateway-ca-certs istio-data]: timed out waiting for the condition
  Warning  FailedMount  49m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-data podinfo egressgateway-certs istio-token egressgateway-ca-certs istio-egressgateway-service-account-token-fbhsh config-volume istio-envoy]: timed out waiting for the condition
  Warning  FailedMount  47m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-token egressgateway-ca-certs config-volume istiod-ca-cert istio-data egressgateway-certs istio-egressgateway-service-account-token-fbhsh istio-envoy podinfo]: timed out waiting for the condition
  Warning  FailedMount  44m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istio-token istio-data podinfo egressgateway-certs egressgateway-ca-certs istio-envoy istiod-ca-cert istio-egressgateway-service-account-token-fbhsh]: timed out waiting for the condition
  Warning  FailedMount  7m48s (x33 over 62m)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  115s (x21 over 42m)   kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-token podinfo egressgateway-certs egressgateway-ca-certs istiod-ca-cert istio-egressgateway-service-account-token-fbhsh istio-envoy config-volume istio-data]: timed out waiting for the condition

### Version

```prose
istioctl version
client version: 1.10.5
control plane version: 1.10.5
kubectl version --short
Client Version: v1.20.9
Server Version: v1.20.9
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by 1511563371** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1511563371** [comment]
> Contributor
+++ To solve the problem 【Get "[https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0](https://10.96.0.1/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0)】
+++ I change the kube-proxy mode from iptables to IPVS

+++ To solve the problem【Get "http://192.168.104.5:8080/ready": dial tcp 192.168.104.5:8080: connect: connection refused】
+++ I change the deplyment file (deployment/istiod ) where I delete the rediness probe

&&&  so I wanna ask the status   followed is healthy???  &&&
【（kubectl describe pod istiod-5549b6fc5-8pzzg -n istio-system）
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  89m   default-scheduler  Successfully assigned istio-system/istiod-5549b6fc5-8pzzg to node3
  Normal  Pulled     89m   kubelet            Container image "docker.io/istio/pilot:1.13.0" already present on machine
  Normal  Created    89m   kubelet            Created container discovery
  Normal  Started    89m   kubelet            Started container discovery】

**Comment by bianpengyuan** [comment]
Deleting readiness prober is not fixing the problem. Your istiod is still not ready to serve because it cannot access API server and get necessary info to do the work.

**Comment by 1511563371** [comment]
> Deleting readiness prober is not fixing the problem. Your istiod is still not ready to serve because it cannot access API server and get necessary info to do the work.
【1】
>> kubectl describe pod istiod-7d7466f66f-pmx7x -n istio-system
>> result 
--------------------------------------------------------------------------------------------
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  27m                    default-scheduler  Successfully assigned istio-system/istiod-7d7466f66f-pmx7x to k8snode2
  Normal   Pulled     27m                    kubelet            Container image "docker.io/istio/pilot:1.13.0" already present on machine
  Normal   Created    27m                    kubelet            Created container discovery
  Normal   Started    27m                    kubelet            Started container discovery
  Warning  Unhealthy  2m13s (x500 over 27m)  kubelet            Readiness probe failed: Get "http://192.168.185.194:8080/ready": dial tcp 192.168.185.194:8080: connect: connection refused


----------------------------------------------------------------------------------------------------------
【2】
>>  kubectl logs  istiod-7d7466f66f-pmx7x -n istio-system
>>result

2022-02-22T16:34:05.585553Z	error	klog	k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout

----------------------------------------------------------------------------------------------------
【3】
>> cat /etc/kubernetes/kubelet.conf | grep server

>> result 
server: https://k8smaster1:6443

--------------------------------------------------------------------------------------------------
【4】  address1 : 10.96.0.1:443;  address2 : 192.168.185.194:8080/ready;  address3 : k8smaster1(192.168.80.221)
>>  all operations in Node1

[root@k8snode1 hadoop]# curl -v  10.96.0.1:443
* About to connect() to 10.96.0.1 port 443 (#0)
*   Trying 10.96.0.1...
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.96.0.1:443
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< 
Client sent an HTTP request to an HTTPS server.
* Closing connection 0


[root@k8snode1 ]# curl -v  192.168.185.194:8080/ready
* About to connect() to 192.168.185.194 port 8080 (#0)
*   Trying 192.168.185.194...
* 拒绝连接
* Failed connect to 192.168.185.194:8080; 拒绝连接
* Closing connection 0
curl: (7) Failed connect to 192.168.185.194:8080; 拒绝连接



[root@k8snode1  ]# curl -v k8smaster1:6443
* About to connect() to k8smaster1 port 6443 (#0)
*   Trying 192.168.80.221...
* Connected to k8smaster1 (192.168.80.221) port 6443 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: k8smaster1:6443
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< 
Client sent an HTTP request to an HTTPS server.
* Closing connection 0





=============================================
so ,where is my fault???
----------------------------
base point 

 uname -r
3.10.0-1160.el7.x86_64

k8s Version   1.20.9 ;docker  Vsersion:20.10.12

IPVS is my kubeproxy mode 


------------------------------
so what is the probelm ????
------------------------------

**Comment by 1511563371** [comment]
The problem is solved

**Comment by HtForBetterLife** [comment]
> The problem is solved

hi, @1511563371 , how do you solve the problem?  I'm facing the same thing.
