### ISSUE TITLE
Issue with the Machine learning application which is written in python. connection timeout retries and internal server error 

### ISSUE THREAD

**Issue by sachinpal0064** [istio/istio#37343]
Hi,

we are getting connection timeout retries and internal server error when we are calling the one service to another service which is connected to mongodb using istio. but it is working fine when we are deploying with NodePort in services

Could you please help me because we are not able to find exact issue.

**Comment by zirain** [comment]
@sachinpal0064 can you share more details about your service topo?

**Comment by sachinpal0064** [comment]
we have 10 microservice in python.
1.workbenchapi
2.imageclasification_api
3.objectdetection_api
4.handwritenRecognition_api
5.ICMM ui
6.icmm_backend
7.mongodb
8.tabledetection_api
9.pdfocrExtraction_api
10.albert_api
now when calling the from workbench_api to 
2.imageclasification_api
3.objectdetection_api
4.handwritenRecognition_api
then getting 200 response means working fine.

but when we are calling the service from workbench to  icmm_backend which is connected to mongodb then getting connection time and some times internel server error

**Comment by zirain** [comment]
where is the mongodb? also deployed in the same cluster?
we need configdump and logs from the `icmm_backend`  sidecar proxy
https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2
