### ISSUE TITLE
More matching options for RouteMatch in EnvoyFIlter

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#37346]
**Describe the feature request**
Right now, to match over a specific route in EnvoyFilter using [RouteMatch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-RouteMatch), you can only use `name`. This works fine when using VirtualService to generate route configuration in the Envoy since it allows us to give a unique `name` to use in the EnvoyFilter. But that's not the case for Gateway API's HTTPRoute (currently being worked on https://github.com/istio/istio/issues/36790) or K8s Ingress resource, which makes matching patching dependent on which networking objects are used (not ideal).

I want to put forth a request for more matching options in EnvoyFilter_RouteMatch like `prefix` or `path` ([List of possibilities](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch))

**Describe alternatives you've considered**
We have thought of using Envoy's xDS API to cover our use cases but are unsure about the interaction between Istio and another controller.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
We are trying to add [ratelimits](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction) at the route-level.

**Comment by howardjohn** [comment]
I am a bit concerned by the stability of this. Would prefer to get `name` into HTTPRoute or come up with another similar stable identifier

**Comment by rahulanand16nov** [comment]
Do you think starting with `path` first to see if it will actually cause any problem? If not, we can try to add different options later. 

If there are multiple matching routes with specified `path`, then a patch should be applied to all of them. I would love to know why you think there is a stability concern.

**Comment by howardjohn** [comment]
I feel very uncomfortable matching on path. It tightly couples things and
we actually transform users intended path into different Envoy paths in
some cases, so it will not work well
