### ISSUE TITLE
Support more layers in the OCIArtifactImage format of wasm image.

### ISSUE THREAD

**Issue by johnlanni** [istio/istio#37347]
https://github.com/istio/istio/blob/9b3cecdc96db7250d1fef6a7d6e0669622b7e59b/pkg/wasm/imagefetcher.go#L274

I think the number of layers should be greater than or equal to 2 instead of the limit of 2. 

This artifact image specification should support possible future layers extensions, such as layer that specify plugin's metadata information.

**Comment by bianpengyuan** [comment]
> This artifact image specification should support possible future layers extensions, such as layer that specify plugin's metadata information.

I think you can add arbitrary metadata to the config layer? If it does not work for some reason, we'd need to extend the spec as @zirain pointed out.

**Comment by johnlanni** [comment]
![image](https://user-images.githubusercontent.com/6763318/154182466-df845326-bed7-4aea-b597-6c202542ebde.png)
@bianpengyuan @zirain But the config layer in this spec is used for wasm runtime config. Maybe the spec needs to be modified, but the spec has no limit to only 2 layers, so I think the restrictions on istio should be relaxed.

**Comment by bianpengyuan** [comment]
I think we should not assume spec support abitrary number of layers > 2, otherwise it would be hard to extend. I think for now the best approach is to use the existing config layer to carry your own metadata, or update the spec to support arbitrary metadata as a third layer.
