### ISSUE TITLE
Missing LABELS metadata regression in istio 1.12

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37362]
https://github.com/istio/istio/commit/fa03b30370ba489f78c5fd6b1094c2875f20c749 introduced a small regression in the handling of proxy.Metadata.Labels. We have two ways to get the labels today:
* XDS meta LABELS sets it statically
* ^ is missing, we fetch from Kubernetes

The problem is that we only fetch from k8s if the labels is not set. but here: https://github.com/istio/istio/commit/fa03b30370ba489f78c5fd6b1094c2875f20c749#diff-69a5c353ed87ca4dc51349c2e950da8e0514e36dbf46aa47ce39574ee1a19befR607 we unconditionally set it

**Comment by hzxuzhonghu** [comment]
What does it miss, isn't labels set there?

**Comment by howardjohn** [comment]
The problem is augment labels gets proxy.Metadata.Labels passed to it. This is nil. Then it assigns proxy.Metadata.Labels the result (non nil).

Later in the code, we do `if proxy.Metadata.Labels == nil { fetch labels from Kubernetes pod spec }`. Now this code can never occur

**Comment by hzxuzhonghu** [comment]
From `s.computeProxyState(proxy, nil)` the labels are set

**Comment by hzxuzhonghu** [comment]
And also from agent side, we have  mounted pod labels, and in theory metadata must have labels. That means fallback can not happen for pod at all.

**Comment by howardjohn** [comment]
It is possible we just say all this info must be present in metadata only
and is never fetched from pods...
