### ISSUE TITLE
How to add the custom headers pod via the ingress gateway service? 

### ISSUE THREAD

**Issue by rameshar16** [istio/istio#37375]
Hi All,

Is it possible to add custom headers to the request at istio-ingress-gateway level?

Thanks and Regards.
Ramesh

**Comment by zirain** [comment]
add a `envoy.lua` filter via EnvoyFilter?

**Comment by ramaraochavali** [comment]
https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L808 - use this to add headers. Example https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L744

**Comment by zirain** [comment]
closed this as it's fixed, feel free to reopen it.
