### ISSUE TITLE
Provide an option to avoid webhook injector to override the manual injected config

### ISSUE THREAD

**Issue by yusuoh** [istio/istio#3738]
When people use kubectl to manually inject sidecar into deployment with a different config (e.g. during upgrade process), it will be overridden by webhook injector, which is problematic or at least confusing.

We should provide a option to disable that behavior. Unless the user explicitly change that option, the manual injected config should not be overridden.

**Comment by ayj** [comment]
Do we expect users to mix manual and automatic injection in the same namespace? How would that work when we start auto-upgrading proxies?

**Comment by yusuoh** [comment]
I think there might be some situation when people what to override the sidecar config for some specific deployment in the same namespace. For auto-upgrade, if the user only want to upgrade envoy proxy, they can skip the manual injection. But if the whole sidecar agent need to be upgraded, we still need to manually update the deployment.

**Comment by costinm** [comment]
Yes, absolutely - users can kube-inject or use their own custom sidecar configs. 

But we do have a way to handle this - the annotation  to exclude the pod from auto-injection.
Can we just document it better ? 

For auto-update: I assume it'll be an update of the binary (the docker), but any settings the
user has can be preserved ( for the release backward compat time).
