### ISSUE TITLE
envoy consume high memory but heap profiler can't report cause

### ISSUE THREAD

**Issue by nonumber1989** [istio/istio#37396]
### Bug Description
1. some application's sidecar consume high memory (300M+)
![sidecar-consumption](https://user-images.githubusercontent.com/4054215/154390697-46987a7c-ebb2-480c-b0fa-d10bb4b18b45.png)
![top](https://user-images.githubusercontent.com/4054215/154391151-b662dc9d-75db-4c4b-9043-974988810e9a.png)
![memory](https://user-images.githubusercontent.com/4054215/154391013-5444b84d-46c8-4f48-a6ba-ddd550fcd750.png)
    ` {
     "allocated": "253959744",
     "heap_size": "262422528",
     "pageheap_unmapped": "0",
     "pageheap_free": "761856",
     "total_thread_cache": "3565136",
     "total_physical_bytes": "266485760"
    }
`
2. dump heap follow [Analyzing Istio Performance](https://github.com/istio/istio/wiki/Analyzing-Istio-Performance),use pprof to analysis ,but can't found high memory consumption 
![pprof](https://user-images.githubusercontent.com/4054215/154390959-c4b2567a-edb8-4dea-9607-f4e7b13860ad.png)

### Version

```prose
control plane:
$ istioctl version
client version: 1.10.4
control plane version: 1.10-dev-b166f0c30252e24cd97a424835556dc4b7de7b25
data plane version: none
$ kubectl version --short
Client Version: v1.18.9
Server Version: v1.18.9

data plane:
$ istioctl version
client version: 1.10.4
control plane version: 1.10-dev-b166f0c30252e24cd97a424835556dc4b7de7b25
data plane version: 1.10-dev (150 proxies)
$ kubectl version --short
Client Version: v1.18.1
Server Version: v1.18.1
```

### Additional Information
1. netstat -a , find about 100 UDS 
[netstat.txt](https://github.com/istio/istio/files/8085015/netstat.txt)
2. curl localhost:15000/clusters ,localhost:15000/listeners. normal
[clustersAndListeners.txt](https://github.com/istio/istio/files/8085019/clustersAndListeners.txt)
3. the pprof file
[profile.pb.gz](https://github.com/istio/istio/files/8085023/profile.pb.gz)
4. not all my application occur this problem
5. use  primary-remote deployment model

**Comment by lujiajing1126** [comment]
Also suffer this issue.

We're using istio `1.13.4`.

**Comment by caoyukun0430** [comment]
Hi Did you tried with options "pprof --alloc_space"? https://www.neteye-blog.com/2019/06/go-pprof-how-to-understand-where-there-is-memory-retention/ it has different outputs for me than default in_space ones.
Also using "-c dbg" when building envoy gives you the binary named "envoy.full" that contains more info. https://github.com/envoyproxy/envoy/blob/main/bazel/README.md

**Comment by JinVei** [comment]
Seem like have the same problem. 

In my case, envoy has unexpected high memory usage, and the memory usage shown from pprof is much less than the one from top.
- memory metrics
```
istio-proxy@xxx:/$ curl localhost:15000/memory
{
 "allocated": "14768816",
 "heap_size": "166338560",
 "pageheap_unmapped": "73752576",
 "pageheap_free": "9420800",
 "total_thread_cache": "14163152",
 "total_physical_bytes": "95993856"
}
```

- alloc_space
![4E6DA12B-CD6D-496E-99AD-52DCDBF093E1](https://user-images.githubusercontent.com/21029925/189874338-c64559e3-6f06-4d3a-addb-fb81eebd0b82.png)

- inuse_space
![4EA85776-63CC-4B4B-AFCF-20D4BD854688](https://user-images.githubusercontent.com/21029925/189874341-f7d8f96c-988b-4a41-963b-ab1993b22ae1.png)


> Hi Did you try with options "pprof --alloc_space"? https://www.neteye-blog.com/2019/06/go-pprof-how-to-understand-where-there-is-memory-retention/ it has different outputs for me than default in_space ones. Also using "-c dbg" when building envoy gives you the binary named "envoy.full" that contains more info. https://github.com/envoyproxy/envoy/blob/main/bazel/README.md FYI [envoyproxy/envoy#21923](https://github.com/envoyproxy/envoy/issues/21923)

**Comment by zhaohuabing** [comment]
I ran into the same issue, pprof show much less memory than actual usage.

We need to reopen this issue.

**Comment by zhaohuabing** [comment]
Heap profiler doesn't dump a snap-shot of the current memory of a process, instead, it just tracks memory allocation such as malloc, calloc, realloc, or, new. So what we see in pprof is the allocated history of each method, the size is not the same as the current memory hold by a process.
