### ISSUE TITLE
Traffic test framework improvements

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37391]
A common pattern for tests is:
* Apply some config
* Run some requests and verify things

This works ok currently but I think it can be improved. Often we want to vary over a variety of different things: the source workload, the dest workload, ports. The "workload agnostic" handles the first 2, but not the latter, and lead to slow tests: https://github.com/istio/istio/issues/33335. Hand-written tests are almost guaranteed to either have less coverage than we want or be inefficient; its quite tricky to write an optimal test today.

One trick we can use is to have config templatized, and then inspect which vars are used in the template. From there, we can derive the optimal running order, rather than always running in the same order. `dest/src/port` may be optimal in some cases, while `port/src/dest` in others, for example.

Returning TrafficTestCase as a list also brings some complexity to the usage. It would be preferred to pass in the test context to functions and let them execute directly.

An example of what I tests should look like: <TODO>

**Comment by nmittler** [comment]
@howardjohn Could you provide some basic examples to help illustrate some possible desired usage scenarios?

**Comment by howardjohn** [comment]
Some examples:

Test all combinations of traffic across all ports.
```go
t.RunTraffic(Args{
  Name: "baseline",
  Ports: AllPorts,
})
// Implicit: Source=AllSources, Dest=AllDests, Checker=checkOK
```

Test inserting a header
```go
t.RunTraffic(Args{
  Name: "insert header",
  Port: HTTP,
  Config: `
kind: VirtualService
name: {{.DstSvc}}
spec:
  host: {{.DstSvc}}
  http: addHeader: foo=bar
`,
  Checker: check.Header("foo", "bar)
})
```

**Comment by zirain** [comment]
did you set `EnableRedisFilter `?

https://github.com/istio/istio/blob/47260b9cd90073a5de70258dec253505329a45d1/pilot/pkg/features/pilot.go#L131

**Comment by howardjohn** [comment]
Not sure the relationship to redis..?

**Comment by zirain** [comment]
> Not sure the relationship to redis..?

I post a replay on wrong issue.

**Comment by nmittler** [comment]
@howardjohn after working on some of the security tests, I think I see a pattern that might help a bit. This is based on what I did [here](https://github.com/istio/istio/pull/37358/files#diff-0f16a2d643db272673a7f852fff9448c43c60fc41b09fd9106e67e9e58b3b3d8R61).

```golang
type CallCustomizer func(t TestContext, from Instance, to Instances, opts *CallOptions)

type Case struct {
  Name: string
  Customize: CallCustomizer 
}

t.WithConfig(`
kind: VirtualService
name: {{.DstSvc}}
spec:
  host: {{.DstSvc}}
  http: addHeader: foo=bar
`).RunTraffic([]Case{
  {
    Name: "insert header",
    Customize: func(t TestContext, from Instance, to Instances, opts *CallOptions) {
      opts.Check: check.RequestHeader("foo", "bar)
    }
  })
```

**Comment by nmittler** [comment]
@howardjohn proposed solution in https://github.com/istio/istio/pull/38620

**Comment by nmittler** [comment]
@howardjohn I think this has basically landed at this point. Should we close this or are there other changes you'd like to see?
