### ISSUE TITLE
Redis stopped working after changing mTLS mode to STRICT

### ISSUE THREAD

**Issue by xiaoyaozi5566** [istio/istio#37423]
### Bug Description

I deployed a redis cluster with 3 sentinels and 3 redis servers, with this [redis-operator](https://github.com/spotahome/redis-operator). I enabled sidecar injection so every pod is running with a sidecar proxy to provide mTLS communication
```
redisoperator-5b569cb4cf-vb7pk              2/2     Running     1          125m
rfr-redisfailover-0                         2/2     Running     0          124m
rfr-redisfailover-1                         2/2     Running     0          124m
rfr-redisfailover-2                         2/2     Running     0          124m
rfs-redisfailover-5c9cc77b98-5rk5z          2/2     Running     0          124m
rfs-redisfailover-5c9cc77b98-jjmst          2/2     Running     0          124m
rfs-redisfailover-5c9cc77b98-zgxfc          2/2     Running     0          124m
```
The redis master node shows replication is working as expected
```
/data $ redis-cli info replication
# Replication
role:master
connected_slaves:2
slave0:ip=127.0.0.6,port=6379,state=online,offset=105967,lag=1
slave1:ip=127.0.0.6,port=6379,state=online,offset=105967,lag=1
master_replid:0b4e101d255fe607e463d1c9adc3dd9242fbd443
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:106104
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:106104
```
I was using the PERMISSIVE mTLS mode. Now I want to enforce strict mTLS, so I changed the peerathentication to STRICT mTLS mode. After the mode has changed, the replicas couldn't talked to each other anymore
```
/data $ redis-cli info replication
# Replication
role:master
connected_slaves:0
master_replid:0b4e101d255fe607e463d1c9adc3dd9242fbd443
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:971030
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:971030
```
My question is: why would the STRICT mTLS mode break the replicas' communication? I thought since each pod has a sidecar proxy, all the communication between them should already be done in mTLS. Changing the mode to STRICT mTLS mode shouldn't affect anything, right? Unless Redis servers do some plaintext communication that bypass the sidecar proxy, I really couldn't figure out why the STRICT mode is breaking the redis communication. Did I misunderstand the STRICT vs PERMISSIVE mode?

### Version

```prose
1.12.1
```

**Comment by howardjohn** [comment]
Check the access logs on client, it will show if the request is passed through or not. It depends on how redis sends the request - right now our matching logic is not perfect but it should be possible to get it working

**Comment by xiaoyaozi5566** [comment]
> Did you apply DestinationRule to enforce mTLS at client side as well? I guess redis server just uses pod ip to communicate with each other, and I think auto mTLS would not work that case.

There is no client involved, the problem is between redis replicas. I don't think redis server uses pod ip to communicate, because in the replication information
> slave0:ip=127.0.0.6,port=6379,state=online,offset=105967,lag=1

The ip of the slave is `127.0.0.6`, which I believe is the istio sidecar proxy ip. So this seems to suggest the replication is done through the sidecar proxy. However, when I turned the mode to STRICT mTLS, the replication is broken somehow.

**Comment by xiaoyaozi5566** [comment]
> Check the access logs on client, it will show if the request is passed through or not. It depends on how redis sends the request - right now our matching logic is not perfect but it should be possible to get it working

```
1:M 18 Feb 2022 17:36:02.393 * Replica 127.0.0.6:6379 asks for synchronization
1:M 18 Feb 2022 17:36:02.393 * Full resync requested by replica 127.0.0.6:6379
1:M 18 Feb 2022 17:36:02.393 * Replication backlog created, my new replication IDs are '24b91d805e53ec113b9e880926850b207c12557a' and '0000000000000000000000000000000000000000'
1:M 18 Feb 2022 17:36:02.393 * Starting BGSAVE for SYNC with target: disk
1:M 18 Feb 2022 17:36:02.393 * Background saving started by pid 305
305:C 18 Feb 2022 17:36:02.396 * DB saved on disk
305:C 18 Feb 2022 17:36:02.396 * RDB: 0 MB of memory used by copy-on-write
1:M 18 Feb 2022 17:36:02.457 * Replica 127.0.0.6:6379 asks for synchronization
1:M 18 Feb 2022 17:36:02.457 * Full resync requested by replica 127.0.0.6:6379
1:M 18 Feb 2022 17:36:02.457 * Waiting for end of BGSAVE for SYNC
1:M 18 Feb 2022 17:36:02.490 * Background saving terminated with success
1:M 18 Feb 2022 17:36:02.490 * Synchronization with replica 127.0.0.6:6379 succeeded
1:M 18 Feb 2022 17:36:02.491 * Synchronization with replica 127.0.0.6:6379 succeeded
```
This is log from master node with PERMISSIVE mode. We can see the Synchronization is requested from `127.0.0.6`, which I think is istio sidecar.

**Comment by bianpengyuan** [comment]
Interesting. So replicas ip is detected automatically at master, and master just uses local envoy IP (127.0.0.6) because that is what the upstream IP it sees. I suspect that sync does not work either even with permissive, since master essentially is talking to itself instead of replicas. So I think we need to solve the issue about source ip detection first.. see https://github.com/hzxuzhonghu/istio-demo/tree/main/istiocon-2021/tcp/inner-cluster for example about how to use TPROXY to preserve original source IP, and the corresponding presentation https://events.istio.io/istiocon-2021/sessions/preserve-original-source-address-within-istio/.

**Comment by xiaoyaozi5566** [comment]
Under PERMISSIVE mode the redis cluster works as expected. In our system we have other applications communicating with redis to store session tokens. The data is correctly replicated over the 3 replicas. It has been working for us for a long time, until I changed the mTLS mode to STRICT recently.

**Comment by bianpengyuan** [comment]
Can you get envoy access log from proxy when it works with permissive? That would give better idea how replication is done: https://istio.io/latest/docs/tasks/observability/logs/access-log/

**Comment by xiaoyaozi5566** [comment]
> due to known limitation

Hey @bianpengyuan, could you elaborate the known limitation? Is the request encrypted only when the destination is a fqdn instead of an ip?

I tried enabling access logs with the [Telemetry API](https://istio.io/latest/docs/tasks/observability/logs/access-log/#using-telemetry-api). However, I don't see any access logs printed on the redis sidecar proxies. I can see my web servers sidecar proxies printing access logs when I navigate through my UI, so access logs seem to be enabled. Does access log print every request? I saw the istio proxies of some other services in my system (such as zookeeper, kafka, mongodb) also don't print any access logs. I'm wondering if 1. some requests are not being printed? or 2. requests don't go through proxies at all (but we saw the source address was `127.0.0.6`)? I'm a bit confused now..

**Comment by bianpengyuan** [comment]
> could you elaborate the known limitation? Is the request encrypted only when the destination is a fqdn instead of an ip?

It will not be automatically encrypted (i.e. auto-mtls https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/) if the request is sending to a pod ip. You can make it work by either using service name as host header and setting LB policy to original dst with Destination rule, or enable strict mTLS at client side via DestinationRule.
