### ISSUE TITLE
Enable DNS Proxy without the need of restarting pods 

### ISSUE THREAD

**Issue by SantiMunoz** [istio/istio#37428]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently to enable the DNS Proxy in Istio we need to apply the following configuration in the IstioOperator:
```yaml
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
And after it we need to restart the pods in order to get it applied. 
In the scenario where we are enabling the feature in an existing cluster with hundreds of pods is very painful to trigger a restart/redeploy in all of them just to get this feature applied.

I would like to request to be able to enable the DNS proxy feature in runtime without the need of restarting the pods.

**Describe alternatives you've considered**
As far as I understand currently the variables `ISTIO_META_DNS_CAPTURE` and `ISTIO_META_DNS_AUTO_ALLOCATE` are injected under the proxy's environment variable `PROXY_CONFIG`, and that's the main reason it requires the restart.

It would be better if this could be dynamically configured in runtime.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Just want to be realistic - this is extremely unlikely to happen since we need to configure iptables which only can run on the pod startup.

Also things like upgrades also require restarts, so if you aren't willing to restart your pods you may want to consider how you are going to address CVEs, etc.

**Comment by SantiMunoz** [comment]
Got it, I understand your point, it's a pity it can't be implemented in runtime. Thanks anyway for the clarification, I will close the request
