### ISSUE TITLE
Failing to fetch jwks when first request fails

### ISSUE THREAD

**Issue by Kronmannen** [istio/istio#37456]
### Bug Description

**Descibe the bug**
We have an issue using the jwksUri in the Request Authentication resource. When we deploy to new environment istiod tries to get the jwks before our authentication service that hosts the jwks is up. This leads to istiod failing to fetch the jwks from our authentication service and in turn use a cached empty jwk to distribute to the envoy sidecars. This means all jwt validation will fail until the istiod successfully fetches the jwk from the jwksUri and that takes at best 20 minutes but usually more. Istiod keep failing to send the requests even after the authentication service is up with the error shown in the log below.

```
2022-02-18T11:36:54.335425Z error model Failed to fetch public key from "{jwksuri}": Get "{jwksuri}": dial tcp: lookup ... on 10.43.0.10:53: no such host
2022-02-18T11:36:54.335484Z error model Failed to fetch jwt public key from issuer "https://authentication.pr-7419.tst.iasystemet.se/", jwks uri "{jwksuri}": Get "{jwksuri}": dial tcp: lookup curity-runtime.ia-pr-7419-authentication.svc on 10.43.0.10:53: no such host
2022-02-18T11:36:54.335585Z error model Failed to fetch jwt public key from issuer "https://authentication.pr-7419.tst.iasystemet.se/", jwks uri "{jwksuri}": empty public key found in cache
```

How can we configure istiod to retry to get the jwks?

### Version

```prose
Istio version:
/usr/local/bin/pilot-discovery version
version.BuildInfo{Version:"1.11.0", GitRevision:"57d639a4fd19ee8c3559b9a4032f91e4d23c6f14", GolangVersion:"go1.16.7", BuildStatus:"Clean", GitTag:"1.11.0"}

kubectl version --short
Client Version: v1.21.0
Server Version: v1.20.5
```

**Comment by aryan16** [comment]
Currently number of retries in istiod is 0 for fetching publick key from `JWKSURI`. There are 2 ways you can resolve this - 
1) Add a check in your code to check the status of your jwt-server, once it is ready then only try to add the policy. This will resolve the issue in which istiod is not able to find out jwt-server.
2) You can modify the no of retry in istiod pilot code which is currently 0. https://github.com/istio/istio/blob/master/pilot/pkg/model/jwks_resolver.go#L250

**Comment by yangminzhu** [comment]
I think you can configure the `PilotJwtPubKeyRefreshInterval` to a lower value here: https://github.com/istio/istio/blob/58bf51baa71909c1b16a90d7d5acaf5b2c499a9a/pilot/pkg/features/pilot.go#L497

Also I think we should probably increase the number of retries in istiod to some value larger than 0 now, @aryan16
