### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by ls-2018** [istio/istio#37450]
### Bug Description

ons last.
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.6.8 TARGET_ARCH=x86_64 sh -
durning
```
[root@k8s-master01 istio-1.6.8]# kubectl apply -f samples/addons
serviceaccount/grafana created
configmap/grafana created
service/grafana created
deployment.apps/grafana created
configmap/istio-grafana-dashboards created
configmap/istio-services-grafana-dashboards created
deployment.apps/jaeger created
service/tracing created
service/zipkin created
clusterrole.rbac.authorization.k8s.io/kiali-operator created
serviceaccount/kiali-operator created
clusterrolebinding.rbac.authorization.k8s.io/kiali-operator created
deployment.apps/kiali-operator created
serviceaccount/prometheus created
configmap/prometheus created
service/prometheus created
deployment.apps/prometheus created
unable to recognize "samples/addons/kiali.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "Kiali" in version "kiali.io/v1alpha1"
unable to recognize "samples/addons/prometheus.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "samples/addons/prometheus.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
[root@k8s-master01 istio-1.6.8]# kubectl rollout status deployment/kiali -n istio-system
Error from server (NotFound): deployments.apps "kiali" not found
```

### Version

```prose
[root@k8s-master01 istio-1.6.8]# istioctl version
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (9 proxies)
[root@k8s-master01 istio-1.6.8]# kubectl version --short
Client Version: v1.22.0
Server Version: v1.22.0
```

### Additional Information

[root@k8s-master01 istio-1.6.8]# istioctl bug-report

Target cluster context: kubernetes-admin@kubernetes

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system,kube-public,kube-node-lease,local-path-storage }
end-time: 2022-02-20 00:12:41.362377288 +0800 CST

Cluster endpoint: https://apiserver.cluster.local:6443
CLI version:
version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"go1.17.5", BuildStatus:"Clean", GitTag:"1.12.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.2}

Fetching proxy logs for the following containers:

dapr-system//dapr-placement-server-0/dapr-placement-server
dapr-system/dapr-dashboard/dapr-dashboard-8664d5c45f-sxdlf/dapr-dashboard
dapr-system/dapr-operator/dapr-operator-58b9d5fd59-tcbmj/dapr-operator
dapr-system/dapr-sentry/dapr-sentry-858fddc4f7-t2g28/dapr-sentry
dapr-system/dapr-sidecar-injector/dapr-sidecar-injector-7497b7945-59xvz/dapr-sidecar-injector
default/details-v1/details-v1-79c697d759-6fqkc/details
default/details-v1/details-v1-79c697d759-6fqkc/istio-proxy
default/productpage-v1/productpage-v1-65576bb7bf-8h5w5/istio-proxy
default/productpage-v1/productpage-v1-65576bb7bf-8h5w5/productpage
default/prometheus/prometheus-65f4d4f5bd-xhshv/istio-proxy
default/prometheus/prometheus-65f4d4f5bd-xhshv/prometheus-server
default/prometheus/prometheus-65f4d4f5bd-xhshv/prometheus-server-configmap-reload
default/ratings-v1/ratings-v1-7d99676f7f-stmv9/istio-proxy
default/ratings-v1/ratings-v1-7d99676f7f-stmv9/ratings
default/reviews-v1/reviews-v1-987d495c-zqjwq/istio-proxy
default/reviews-v1/reviews-v1-987d495c-zqjwq/reviews
default/reviews-v2/reviews-v2-6c5bf657cf-p5ns5/istio-proxy
default/reviews-v2/reviews-v2-6c5bf657cf-p5ns5/reviews
default/reviews-v3/reviews-v3-5f7b9f4f77-hr56j/istio-proxy
default/reviews-v3/reviews-v3-5f7b9f4f77-hr56j/reviews
istio-system/grafana/grafana-b7f8b6585-wwkcr/grafana
istio-system/istio-egressgateway/istio-egressgateway-c9cbbd99f-28qh6/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-7c8bc47b49-9hnsh/istio-proxy
istio-system/istiod/istiod-765596f7ff-6nrrz/discovery
istio-system/jaeger/jaeger-7bdfbf5977-trz9w/jaeger
istio-system/kiali-operator/kiali-operator-55c7bb84bb-rzh8v/operator

Fetching Istio control plane information from cluster.
Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace dapr-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace dapr-system istio-injection=enabled' to enable it, or 'kubectl label namespace dapr-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service dapr-system/dapr-api) Port name  (port: 80, targetPort: 6500) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service dapr-system/dapr-dashboard) Port name  (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service dapr-system/dapr-placement-server) Port name api (port: 50005, targetPort: 50005) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service dapr-system/dapr-placement-server) Port name raft-node (port: 8201, targetPort: 8201) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service dapr-system/dapr-sentry) Port name  (port: 80, targetPort: 50001) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service dapr-system/dapr-webhook) Port name  (port: 443, targetPort: 19443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/grafana) Port name service (port: 3000, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/kiali-operator-metrics) Port name cr-metrics (port: 8686, targetPort: 8686) doesn't follow the naming convention of Istio port.
Creating an archive at /root/istio-1.6.8/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by howardjohn** [comment]
Why are you setting ISTIO_VERSION=1.6.8? That would install 1.6 Istio which is many years old and won't run on modern Kubernetes deployment

**Comment by ls-2018** [comment]
I operated according to the command of the version specified on the official website. After changing to the new version, I confirmed that it was good to use.However, I also recommend that official documentation be updated with the latest version.
[https://istio.io/latest/docs/setup/getting-started/](https://istio.io/latest/docs/setup/getting-started/)

**Comment by howardjohn** [comment]
Oh it's an example. We should fix it to always use the latest version though

**Comment by ls-2018** [comment]
thanks
