### ISSUE TITLE
enable overriding envoy_bootstrap_tmpl.json location

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#3745]
envoy_bootstrap_tmpl.json is used to generate sidecar envoy configuration. 

There should be a way to override path to envoy_bootstrap_tmpl.json(ie. way to provide custom template) - https://github.com/istio/istio/blob/master/pkg/bootstrap/bootstrap_config.go#L32

This is in favor to running envoy in non-kube plain VM.

**Comment by ZackButcher** [comment]
Do you want to be able to override the template, or just provide custom config? I believe you can provide a custom boot strap config via the [`CustomConfigFile`](https://github.com/istio/api/blob/9d978d76653da8b7b4bd6421b7e8f9925d8c79ea/mesh/v1alpha1/config.proto#L112-L114) option. The comment implies it's only used in front of Mixer/Pilot, but [looking at the code](https://github.com/istio/istio/blob/1bef28bf40cf4d3ffa9f8c162c24020369d84401/pilot/pkg/proxy/envoy/v1/watcher.go#L303-L329) I don't think that's the case.

If you want to be able to control the full template (but still accept the same parameters as the original template) then we can take your PRs.

**Comment by mandarjog** [comment]
Just added a similar comment to the linked PR. --custom-config-file should work, it is already part of the proto.

**Comment by kidiyoor** [comment]
I believe CustomConfigFile is meant to override the template completely. There should be a way for users to provide customized template in a not hardcoded path.  

I think we should use this new parameter to replace the bootstrap template in mixer and pilot rather than replacing ```/var/lib/istio/envoy/envoy_bootstrap_tmpl.json``` during docker build.

**Comment by andraxylia** [comment]
customConfigFile allows to use a different template file that must exist already in the image.

How do we solve the problem of building with a different envoy bootstrap file?

**Comment by andraxylia** [comment]
Also, how do we customize for sidecars also?

**Comment by andraxylia** [comment]
@kidiyoor do you have a PR or has this been worked on?

**Comment by andraxylia** [comment]
We could use an environment variable in the Dockerfile, pointing to the template to be used when the image is built. There is currently a var ISTIO_BOOTSTRAP, but this allows overriding when the bootstrap file is already present in the container's filesystem.

**Comment by andraxylia** [comment]
not stale
