### ISSUE TITLE
Why Istio proxy on Azure needs access to metadata/instance ?

### ISSUE THREAD

**Issue by anastasiagrinman** [istio/istio#37466]
### Bug Description

When running on Azure cluster, istio proxy tries to reach metadata instance api but failed on timeout since we restrict this access by global Network Policy.
This is the warning output that shown on istio-proxy container:
"HTTP request failed: Get \"http://169.254.169.254/metadata/instance?api-version=2019-08-15\": context deadline exceeded (Client.Timeout exceeded while awaiting headers"
Could not unmarshal response: unexpected end of JSON input:"

The question is where the fact that istio-proxy get timeout from metadata will affect on istio runtime on AKS cluster?

### Version

```prose
istio installed by helm chart version 1.12.2
```

### Additional Information

On other cloud providers istio doesn't reach metatada server.

**Comment by howardjohn** [comment]
It is used to fetch the zone/region for locality load balancing and telemetry

**Comment by anastasiagrinman** [comment]
Thanks for sharing the information!
In case it's missing, how istio will lack functioning? in which area/s?
And also why on other cloud provider this fetch is absent?

**Comment by howardjohn** [comment]
Ir occurs on AWS and GCP as well

**Comment by anastasiagrinman** [comment]
And how it affects on istio functionality? In case it get's timeout from metadata

**Comment by petermajoq** [comment]
@howardjohn We also have the question what happens when the IMDS `metadata/instance` is not reachable. I could not find anything in the documentation concerning this.

**Comment by keithmattix** [comment]
The main affected features are locality load balancing and telemetry

**Comment by zirain** [comment]
yeah, I think we hided most of the logs(it's in debug level now) to reduce confusion, if it's still there, please report.
