### ISSUE TITLE
WASM: config image pull interval

### ISSUE THREAD

**Issue by daixiang0** [istio/istio#37463]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I test it at local, the time that Istio proxy pull newer image is different, sometimes spend half an hour, sometimes spend 10 mins, looks like a random behavior.

I do not find any doc for its certain value, I think it would be better to make it configurable.

If I miss anything important, please tell me.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
there're two solution:
1. add a env(like `WASM_INSECURE_REGISTRIES` do) via `MeshConfig.ProxyMetadata`
2. make this configurable in `WasmPlugin` 

@bianpengyuan WDYT?

**Comment by bianpengyuan** [comment]
Currently the image pulling happen on every listener update. We will implement pull policy to if not present, which should suffice what most people want (i.e. only pull once for the whole pod lifecycle).

**Comment by daixiang0** [comment]
@bianpengyuan can I check the timing of the listener update? I want a certain value for pull interval, it helps for end users. If only pull once, the remaining update of WASM image would lack. Now, the random interval is not acceptable for end users.

**Comment by bianpengyuan** [comment]
I think you should always tag your image differently if there is any change. You can specify `sha256` (https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#WasmPlugin) + IfNotPresent pull policy (Note this is not yet implemented) if you really want to use the same image url for different images.

**Comment by daixiang0** [comment]
The case is that users always want to use the latest version.

**Comment by bianpengyuan** [comment]
IMO I don't think it is good approach to let proxy pull new images whenever it is available in an uncontrolled way. If you are absolutely sure this is what you want, I think we can add an env variable to pilot-agent which will could set expiry for cached Wasm modules.

**Comment by zirain** [comment]
> IMO I don't think it is good approach to let proxy pull new image whenever it is available in an uncontrolled way. If you are absolutely sure this is what you want, I think we can add an env variable to pilot-agent which could set expiry for cached Wasm modules.

maybe we need a config like `imagePullPolicy: Always`

**Comment by daixiang0** [comment]
Now we have it.

> > IMO I don't think it is good approach to let proxy pull new image whenever it is available in an uncontrolled way. If you are absolutely sure this is what you want, I think we can add an env variable to pilot-agent which could set expiry for cached Wasm modules.
> 
> maybe we need a config like `imagePullPolicy: Always`

My key concern is pull/sync interval.

**Comment by zirain** [comment]
@daixiang0 as https://github.com/istio/istio/pull/39212 is merged, do you still need this?

**Comment by daixiang0** [comment]
Looks good, close it :)
