### ISSUE TITLE
How to build istio/proxy part 2

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#37471]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Not sure why https://github.com/istio/istio/issues/28476 was closed, was there an actual document created?

this seemed to complete successfully but where is the istio/proxy image/executable afterwards?

cd /root/go/src/istio.io/
git clone https://github.com/istio/proxy.git

cd proxy
docker run -it -w /work -v $PWD:/work gcr.io/istio-testing/build-tools-proxy:master-latest bash
make

in addition how would you build the istio/proxy with a custom envoy image (that was built with fips module)?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
The binary will be under `bazel-bin/sre/envoy`.

**Comment by bianpengyuan** [comment]
You can search for `ISTIO_ENVOY_LOCAL` at istio/istio code base and see how to build with your local Envoy.

**Comment by ceastman-r7** [comment]
After the "make" finished there was nothing in that directory:

[1251/1251] AR obj/libwee8.a
/home/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/sandbox/processwrapper-sandbox/1/execroot/io_istio_proxy
Target @com_googlesource_chromium_v8//:build up-to-date:
  bazel-bin/external/com_googlesource_chromium_v8/libwee8.a
INFO: Elapsed time: 1847.914s, Critical Path: 1842.76s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
build-tools:/work# ls -al bazel-bin/src/envoy
ls: cannot access 'bazel-bin/src/envoy': No such file or directory

**Comment by bianpengyuan** [comment]
You should call `make build_envoy`

**Comment by ceastman-r7** [comment]
@bianpengyuan What if the make build_envoy fails?

ERROR: /home/.cache/bazel/_bazel_root/1e0bb3bee2d09d2e4ad3523530d3b40c/external/envoy/source/common/common/BUILD:469:17: Compiling source/common/common/shared_token_bucket_impl.cc failed: (Exit 1): clang failed: error executing command /usr/lib/llvm/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' ... (remaining 121 argument(s) skipped)

**Comment by bianpengyuan** [comment]
Depends on what is your error? I don't see any error details in your pasted log.

**Comment by ceastman-r7** [comment]
false alarm, the bazel error above was due to low disk space.

**Comment by ceastman-r7** [comment]
I am going to use the fips images that tetrate.io provides, it is challenging trying to build istio and its related components. 

but for future developers the building process should be documented better.

**Comment by Pawan-Bishnoi** [comment]
Thanks @bianpengyuan 
`make build_envoy `works!

> The binary will be under bazel-bin/sre/envoy.

Did you mean `bazel-bin/envoy` ?
```
build-tools:/work# ls
BUGS-AND-FEATURE-REQUESTS.md  CONTRIBUTING.md  Makefile.core.mk       SUPPORT.md  bazel-bin	  bazel-work	common-protos  go.mod  prow	src
BUILD			      LICENSE	       Makefile.overrides.mk  WORKSPACE   bazel-out	  buf.gen.yaml	envoy.bazelrc  go.sum  scripts	test
CODEOWNERS		      Makefile	       README.md	      bazel	  bazel-testlogs  common	extensions     out     source	testdata

build-tools:/work# ls bazel-bin
_objs  **envoy**  envoy-2.params  envoy.runfiles  envoy.runfiles_manifest  extensions  external  source  src

build-tools:/work# ls bazel-bin/src
istio
```

**Comment by qudongfang** [comment]
Thanks, that's very helpful.

I made an `istio-proxy` image with a customized envoy build.

Here is how I did it for future reference

- https://gist.github.com/qudongfang/ae9db604635110265e100a48118ac7ef
- https://gist.github.com/qudongfang/ada7e66bf84f94595341687f7becc692

**Comment by gangmuk** [comment]
> Thanks, that's very helpful.
> 
> I made an `istio-proxy` image with a customized envoy build.
> 
> Here is how I did it for future reference
> 
> * https://gist.github.com/qudongfang/ae9db604635110265e100a48118ac7ef
> * https://gist.github.com/qudongfang/ada7e66bf84f94595341687f7becc692

Hi thanks for sharing the references. can I ask what the istio-proxy.dockerfile is for?
