### ISSUE TITLE
docker image of Gateway chart seems wrong

### ISSUE THREAD

**Issue by ku524** [istio/istio#37482]
https://github.com/istio/istio/blob/155b8a42f4687af1244187b258ea4affc6cd7122/manifests/charts/gateway/templates/deployment.yaml#L46

The docker image of gateway chart is 'auto'. What is auto? I can't find it in docker hub.
It seems wrong, because the other chart `ingress-gateway` has istio/proxyv2.
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L95

Is this `gateway` chart deprecated, and I should use `ingress-gateway`?

**Comment by howardjohn** [comment]
This is expected. At runtime it is injected with the correct version based on the control plane configuration

**Comment by ku524** [comment]
oh, thanks. I will test it and report it!

**Comment by tcheronneau** [comment]
Hey I just hit the issue while trying to install it. 
My deployment is trying to pull an image called auto. 
Maybe I'm missing something to make the injection works ?

**Comment by howardjohn** [comment]
Did you set istio-injection=disable on the namespace maybe?

**Comment by tcheronneau** [comment]
Wow you were fast ! 
And you totally nailed it thanks 👍

**Comment by as01p** [comment]
I have the same problem
1- installing chart  istio-base
2- installing chart istiod I set  hub: docker.io/istio    in the chart values
3- create a ns istio-ingress, like mentionne in the doc
4- kubectl label namespace istio-ingress istio-injection=enabled 
5- installing chart helm install istio-ingressgateway -n istio-ingress
image auto ...Error: ImagePullBackOff
I use fluxcd and I do not want to fetch and modify the charts, then push on local repo, I missed something ?

**Comment by ku524** [comment]
@as01p 
I did it too, and my problem has been solved. Can you check envoy injection works at general pod?

**Comment by ku524** [comment]
Hello, @howardjohn 
I found it works in the namespace where `istio-injection=enabled`.
But I have one more question about this. I intended to make cluster-wide ingress gateway, So I used istio-system namespace.

1. istio-system also should have istio-injection=enabled?
2. Or It is not recommended to use gateway in istio-system namespace?

Thank you!

**Comment by as01p** [comment]
Thank you Howard, I prefer not using istio at all

**Comment by as01p** [comment]
I'll step forward and try linkerd

**Comment by howardjohn** [comment]
Ok, enjoy. I don't think it's a particular constructive comment.

Since this original issue was resolved Ill close the issue.
