### ISSUE TITLE
Istio operator has performance issue with a lot of IOP

### ISSUE THREAD

**Issue by JonathanLachapelle** [istio/istio#37489]
### Bug Description

We have a multi-tenant EKS cluster in EKS which has one IOP per application per ingress and one IOP per application per egress.

With around 150 applications, it’s about 300 IOP.

The issue is when the operator gets killed, it need to reconcile every IOP after restart.

Each reconcile takes around 1.5 minutes, so any changes apply after an operator restart will take 450 minutes before it get applied.

Would it be possible to improve this situation? 

Maybe have parallel processing for the operator or maybe have a choice to reconcile or not after the operator restart.

Thank you

### Version

```prose
istioctl version
Client version: 1.11.4
Control plane version: 1.11.4
Data plane version: 1.11.4 (1234 proxies)

kubectl version —-short
Client Version: v1.2.0.11
Server Version: v1.2.0.11-eks-f17b81
```

**Comment by Pawan-Bishnoi** [comment]
I felt the need for parallelisation in Istio-operator too.
Are you using Istioctl or istio-operator?

Looks like the guideline is to move [away from istio-operator](https://istio.io/latest/docs/setup/install/operator). Not sure if moving to istioctl helps with this situation.

> Use of the operator for new Istio installations is discouraged in favor of the [Istioctl](https://istio.io/latest/docs/setup/install/istioctl) and [Helm](https://istio.io/latest/docs/setup/install/helm) installation methods. While the operator will continue to be supported, new feature requests will not be prioritized.

**Comment by JonathanLachapelle** [comment]
Hi, we are using istio operator
