### ISSUE TITLE
istioctl analyze should complain about conflicting VS hosts on gateways other than "mesh" too 

### ISSUE THREAD

**Issue by rsalmond** [istio/istio#37500]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

istioctl analyze reports [this error](https://istio.io/latest/docs/reference/config/analysis/ist0109/) when users apply multiple VS's that have ambiguous / conflicting host matches, but only when those VS's are associated with the "mesh" gateway. Applying VS's with conflicting host matches on a named gateway is not reported.

**Describe alternatives you've considered**

debugging manually, like a sucker

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

In the below example, whichever VS gets applied first wins and the conflict is not reported.

```
$ cat r.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: red
spec:
  hosts:
  - lab16.classroom.superorbital.io
  gateways:
  - prism-gateway
  http:
  - route:
    - destination:
        host: red

$ cat b.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blue
spec:
  hosts:
  - lab16.classroom.superorbital.io
  gateways:
  - prism-gateway
  http:
  - route:
    - destination:
        host: blue

$ k get vs
NAME   GATEWAYS            HOSTS                                 AGE
blue   ["prism-gateway"]   ["lab16.classroom.superorbital.io"]   13m
red    ["prism-gateway"]   ["lab16.classroom.superorbital.io"]   13m

$ ./istioctl version
client version: 1.13.1
control plane version: 1.12.1
data plane version: 1.12.1 (3 proxies)

$ ./istioctl analyze

✔ No validation issues found when analyzing namespace: red.
```

**Comment by hanxiaop** [comment]
See https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services

**Comment by rsalmond** [comment]
> See https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services

I _think_ you're trying to point me to this detail

> In other words, there is no guaranteed order of evaluation for rules across the fragment configurations

If so, my concern is not the fact that "the first resource wins", but rather that regardless of which resource is applied first, `istioctl analyze` fails to report a conflict that it _does_ report if these VS's had been applied to the `mesh` gateway. To be more specific, it is inconsistent that we report this as a configuration problem in one circumstance but not the other.
