### ISSUE TITLE
Default Envoy WASM log level is not INFO

### ISSUE THREAD

**Issue by daixiang0** [istio/istio#37509]
### Bug Description

Default Envoy WASM log level is not INFO, all logs from `LOG_INFO` cannot see. Logs from `LOG_WARN` can see.

### Version

```prose
$ istioctl version
client version: 1.14
control plane version: 1.14
data plane version: 1.14 (4 proxies)
$ kubectl version --short
Client Version: v1.19.1
Server Version: v1.19.1
```

### Affected product area

- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by bianpengyuan** [comment]
Wasm runtime inherit the same log level from the Envoy host, and Istio uses warn as the default log level for envoy.

**Comment by daixiang0** [comment]
That makes sense, is there any docs for it? I am confused about it for a while.

**Comment by bianpengyuan** [comment]
I don't think we documented this anywhere since it is kind of implementation details. If you can find a good place to add this information, it would be great to make this more visible.

**Comment by daixiang0** [comment]
It is better to document things that end users can see, the log level is import for end-users, and INFO level is more common I think.

**Comment by bianpengyuan** [comment]
I don't think we'd want user to care about the envoy level logging :) I don't have much context on why it is default warning, probably INFO level is still too noisy.

**Comment by daixiang0** [comment]
That is the question.

**Comment by zirain** [comment]
the default value of sidecar is ` - --proxyComponentLogLevel=misc:error`
