### ISSUE TITLE
Circuit Breaker force on/off

### ISSUE THREAD

**Issue by iljun** [istio/istio#37518]
hi contributors
I'm very interested in the Istio circuit breaker, and I have one question, so I registered issue.

My question is, is there a function that allows developers/operators to force circuit breakers on/off?

**Comment by howardjohn** [comment]
There is not currently a mechanism to do this, if I understand the request. minHealthPercent will automatically kick in if enough hosts are evicted though. Otherwise, you would need to modify the destination rule to remove the circuit breaker.

**Comment by iljun** [comment]
> There is not currently a mechanism to do this, if I understand the request. minHealthPercent will automatically kick in if enough hosts are evicted though. Otherwise, you would need to modify the destination rule to remove the circuit breaker.

Thank you for your answer 🙇
