### ISSUE TITLE
Deployments are failed with istio-sidecar injection after Istio Upgrade 

### ISSUE THREAD

**Issue by Sunil-Jacob** [istio/istio#37512]
### Bug Description

Hi Team, 
We were running Istio 1.11.1 and recently upgraded to 1.12.2 by following the Istio documentation as below:
[Istio Canary Upgrade](https://istio.io/latest/docs/setup/upgrade/canary/#before-you-upgrade)

The upgrade was successful. To delete the old control plane , I did the command as below:

`kubectl delete deploy istiod -n istio-system` 

After the same when helm deployment was done, getting the below error:
``cannot patch "inventory" with kind VirtualService: Internal error occurred: failed calling webhook "validation.istio.io": Post "[https://istiod.istio-system.svc:443/validate?timeout=10s](https://istiod.istio-system.svc/validate?timeout=10s)": no endpoints available for service "istiod"``

I feel the cleaning up did not happen correctly. It would be great, if some can help me on this.

### Version

```prose
$ istioctl version
client version: 1.12.2
istiod version: 1.12.2
pilot version: 1.11.1
data plane version: 1.12.2 (43 proxies)

$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.20.12-gke.1500

 ~ helm version --short
v3.6.3+gd506314
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Additional Information

After the same when helm deployment was done, getting the below error:
``cannot patch "inventory" with kind VirtualService: Internal error occurred: failed calling webhook "validation.istio.io": Post "[https://istiod.istio-system.svc:443/validate?timeout=10s](https://istiod.istio-system.svc/validate?timeout=10s)": no endpoints available for service "istiod"``

**Comment by howardjohn** [comment]
cc @Monkeyanator

**Comment by Sunil-Jacob** [comment]
Hi Team, It would be great if we can get some insight into this

**Comment by AlexDHoffer** [comment]
This is a lot like my issue https://github.com/istio/istio/issues/37545 It seems like the validating webhook doesn't get created. In my case, it doesn't update the version of it to 1.12.2 which makes me think the Operator simply does not interact with it at all

**Comment by Sunil-Jacob** [comment]
Agreed @AlexDHoffer . The workaround was to add below code:

```
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: 15017
  selector:
    app: istiod
    istio.io/rev: 1-12-2
```

**Comment by AlexDHoffer** [comment]
@Sunil-Jacob That doesn't do anything for me. Would you mind telling/showing me what validating webhook(s) that gives you? I am ultimately confused what webhook(s) I should even be expecting for this to yield.

**Comment by Sunil-Jacob** [comment]
@AlexDHoffer Below is the configuration for the latest istio 1-12-2

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"istiod","istio.io/rev":"1-12-2","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.12.2","release":"istio"},"name":"istio-validator-1-12-2-istio-system"},"webhooks":[{"admissionReviewVersions":["v1beta1","v1"],"clientConfig":{"caBundle":"","service":{"name":"istiod-1-12-2","namespace":"istio-system","path":"/validate"}},"failurePolicy":"Ignore","name":"rev.validation.istio.io","objectSelector":{"matchExpressions":[{"key":"istio.io/rev","operator":"In","values":["1-12-2"]}]},"rules":[{"apiGroups":["security.istio.io","networking.istio.io","telemetry.istio.io","extensions.istio.io"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["*"]}],"sideEffects":"None"}]}
  creationTimestamp: "2022-02-21T06:54:24Z"
  generation: 41
  labels:
    app: istiod
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: istiod
    istio.io/rev: 1-12-2
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.2
    release: istio
  name: istio-validator-1-12-2-istio-system
  resourceVersion: "122708118"
  uid: b5c1876f-bb49-4dfe-ba44-f490ae111a05
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0t...
    service:
      name: istiod-1-12-2
      namespace: istio-system
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.validation.istio.io
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - 1-12-2
  rules:
  - apiGroups:
    - security.istio.io
    - networking.istio.io
    - telemetry.istio.io
    - extensions.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

**Comment by Sunil-Jacob** [comment]
@AlexDHoffer Did you find any workaround?

**Comment by AlexDHoffer** [comment]
@Sunil-Jacob I'm on the Operator upgrade path, upgrading from a pretty old version (1.8.2). That old version didn't have a 'Revision' set. I was able to fix the webhook misbehavior by doing a full delete of the old Operator and then re-installing with the new version. Upgrading in-place doesn't seem to really work, it leaves a bunch of stuff lying around for me.

**Comment by Sunil-Jacob** [comment]
@AlexDHoffer If I understand, you have deleted the old operator, instead of upgrading it. Oh that's cool.
I was doing `canary` upgrade.

**Comment by AlexDHoffer** [comment]
@Sunil-Jacob That is correct, I was not able to upgrade via canary without it leaving behind a bunch of resources, even after erasing the old operator/profile.
