### ISSUE TITLE
change to flags broke bookInfo e2e tests

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3751]
#3740 has broken bookInfoTests

https://github.com/istio/istio/pull/3740#issuecomment-368193556

**Comment by ldemailly** [comment]
it also broke on circleci, strangely though only later:

istio-mixer-3733898352-x5k5v           2/3       CrashLoopBackOff   3          1m

https://circleci.com/gh/istio/istio/36755
vs
https://circleci.com/gh/istio/istio/36971

@costinm any idea why it failed only later and not on the pr itself ?

**Comment by mattdelco** [comment]
My casual observation has led me to think that Prow tests using changes in the current PR while CircleCI doesn't.  So, someone can break CircleCI in a PR but still pass the tests in that PR (while subsequent PRs will then experience the breakage).

**Comment by ldemailly** [comment]
if that’s the case, that’s sounds like a terrible flaw that needs fixing

**Comment by costinm** [comment]
Bookinfo is run in the periodic task in master. I don't think it's that terrible, but working as intended - not everything can and needs to be found in pre-submit. As long as bugs are found and fixed - we can 
have master broken for few hours. We had 2 releases that were broken and passing all tests - that's 
far more terrible -).

**Comment by ldemailly** [comment]
the build which failed on circle after the facts is e2esimple
which failed later... unless I am mistaken... (bookinfo one failed on prow right away)
