### ISSUE TITLE
pilot-agent shouldn't output to stdout when --log_rotate <string> is given

### ISSUE THREAD

**Issue by qudongfang** [istio/istio#37521]
## What do I want to achieve and why

- access_log in a separate log file
- pilot-agent log in another log file

so that 
- we can do proper logrotate on VM(now 2 process writing to the same file)
- forward the logs to different indexes/categories

## Current status

Both envoy and the pilot-agent are redirecting stdout to the same file `${ISTIO_LOG_DIR}/istio.log`

At the same time, the pilot-agent has some logroate options.
The pilot-agent log goes to both `${ISTIO_LOG_DIR}/istio.log` and `${ISTIO_LOG_DIR}/pilot-agent.log` when we set the `ISTIO_AGENT_FLAGS=--log_rotate ${ISTIO_LOG_DIR}/pilot-agent.log `

https://github.com/istio/istio/blob/e7eceaa771e51f4f9867bd90c00c14e634c48ef4/tools/packaging/common/istio-start.sh#L144-L145

### Version

```prose
➜ istioctl version
client version: 1.12.2
control plane version: 1.11.6
data plane version: 1.11.6 (56 proxies), 1.11.0 (8 proxies)

➜ kubectl version --short
Client Version: v1.23.1
Server Version: v1.21.5-eks-bc4871b
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Comment by bianpengyuan** [comment]
We can probably add a proxyLogPath arg to agent to control envoy log output path.

**Comment by bianpengyuan** [comment]
@zirain would you like to take a stab at this?

**Comment by zirain** [comment]
let me take a look.

**Comment by zirain** [comment]
IIRC, there's a PR was sent by me, but not merged.

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/28257

**Comment by zirain** [comment]
@qudongfang maybe  you can try OpenTelemetry Provider https://github.com/istio/istio/pull/37203

**Comment by bianpengyuan** [comment]
Any reason not to reopen it? I think the use case here is VM, where output log to different files make sense.

**Comment by zirain** [comment]
some discussion here https://github.com/istio/istio/issues/36193

**Comment by zirain** [comment]
I open that PR because one of our user want forward to a single file, another fluent sidecar will transfer the log to ES.
After upgraded to istio v1.8, `HttpGrpcLogProvider` with custom receiver in OTel-collector make this function is unnecessary.
In the future, we will use `OTel Log Prvider` to replace `HttpGrpcLogProvider`.

**Comment by zirain** [comment]
> Any reason not to reopen it? I think the use case here is VM, where output log to different files make sense.

@howardjohn WDYT?

**Comment by qudongfang** [comment]
Any suggestions on how to do plain `logrotate` on **VM**?
I got a script to re-open the logs, it doesn't work

```
#!/usr/bin/env bash
set -e

for pid in $(ps -u istio-proxy -o pid=); do
    /bin/kill -SIGUSR1 "$pid"
done
```
