### ISSUE TITLE
auto allocate ip not safe

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#37537]
It is from this failure https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37536/unit-tests_istio/1497099945239384064

I come to think it is not safe to allocate IP for service when `updateServices`. Cause it is async triggered.

**Comment by hzxuzhonghu** [comment]
xds generator is using the allocatedip, while the serviceentry handler can update this value at any time. The result is terrible.

**Comment by hzxuzhonghu** [comment]
@ramaraochavali I think this is a regression from https://github.com/istio/istio/issues/37537

**Comment by ramaraochavali** [comment]
All service already has lock when updateService is called
