### ISSUE TITLE
Failed ： istioctl isntall  --set profile=demo

### ISSUE THREAD

**Issue by 1511563371** [istio/istio#37531]
### Bug Description

Istiod : Readiness probe failed
Ingress gateways,Egress gateways  cannot create pod

### Version

```prose
istioctl version
istioctl 1.13.0

kubectl version --short
Client Version: v1.21.10
Server Version: v1.21.10
```

### Additional Information

my kubernetes cluster model:
Master Node: master1,master2
Work Node: node1, node2
--------------------------------------

cluster model create by  
 kubeadm init --apiserver-advertise-address 192.168.80.221 --image-repository registry.aliyuncs.com/google_containers --kubernetes-version v1.21.10 --pod-network-cidr  "192.168.0.0/16"   --service-cidr  "10.96.0.0/12"  --control-plane-endpoint "k8smaster1" 

k8s CNI is calico 

-----------------------------------

**Comment by zirain** [comment]
can you shared more info?
any log from istiod and also `kubectl describe rs -nistio-system  <istio-ingressgatew-xxxxx replace with the real name>`

**Comment by 1511563371** [comment]
Infomation More：
【1】[root@k8smaster1 istio-1.13.0]# kubectl describe pod istiod-7586c7dfd8-4qtjk  -n istio-system

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  25m                  default-scheduler  Successfully assigned istio-system/istiod-7586c7dfd8-4qtjk to k8smaster2
  Normal   Pulling    25m                  kubelet            Pulling image "docker.io/istio/pilot:1.13.0"
  Normal   Pulled     24m                  kubelet            Successfully pulled image "docker.io/istio/pilot:1.13.0" in 1m0.599004058s
  Normal   Created    24m                  kubelet            Created container discovery
  Normal   Started    24m                  kubelet            Started container discovery
  Warning  Unhealthy  35s (x481 over 24m)  kubelet            Readiness probe failed: Get "http://192.168.137.65:8080/ready": dial tcp 192.168.137.65:8080: connect: connection refused


【2】 [root@k8smaster1 istio-1.13.0]# kubectl describe pod istio-ingressgateway-dc9c8f588-rwzbd  -n istio-system


Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    21m                   default-scheduler  Successfully assigned istio-system/istio-ingressgateway-dc9c8f588-rwzbd to k8snode2
  Warning  FailedMount  19m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-ca-certs kube-api-access-tl7sr istio-envoy istio-data config-volume podinfo ingressgateway-certs istiod-ca-cert istio-token]: timed out waiting for the condition
  Warning  FailedMount  16m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-token kube-api-access-tl7sr podinfo istiod-ca-cert istio-envoy config-volume ingressgateway-certs ingressgateway-ca-certs istio-data]: timed out waiting for the condition
  Warning  FailedMount  14m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-data istio-envoy config-volume ingressgateway-certs ingressgateway-ca-certs istiod-ca-cert istio-token podinfo kube-api-access-tl7sr]: timed out waiting for the condition
  Warning  FailedMount  12m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[kube-api-access-tl7sr istiod-ca-cert istio-token podinfo ingressgateway-ca-certs istio-envoy config-volume istio-data ingressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  9m56s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert ingressgateway-certs kube-api-access-tl7sr istio-data podinfo istio-envoy config-volume istio-token ingressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  7m40s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-certs ingressgateway-ca-certs istiod-ca-cert istio-envoy istio-token kube-api-access-tl7sr config-volume istio-data podinfo]: timed out waiting for the condition
  Warning  FailedMount  5m23s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istio-token ingressgateway-ca-certs istio-envoy istio-data ingressgateway-certs kube-api-access-tl7sr podinfo istiod-ca-cert]: timed out waiting for the condition
  Warning  FailedMount  3m7s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-certs podinfo ingressgateway-ca-certs kube-api-access-tl7sr istiod-ca-cert istio-data istio-envoy config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  2m41s (x17 over 21m)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  39s (x2 over 49s)     kubelet            (combined from similar events): MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found


【3】root@k8smaster1 istio-1.13.0]# kubectl describe pod istio-egressgateway-6cf5fb4756-p4bzf  -n istio-system

Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    21m                 default-scheduler  Successfully assigned istio-system/istio-egressgateway-6cf5fb4756-p4bzf to k8snode1
  Warning  FailedMount  19m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert egressgateway-ca-certs config-volume istio-data kube-api-access-hlnk6 istio-envoy istio-token podinfo egressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  17m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo egressgateway-ca-certs kube-api-access-hlnk6 istio-envoy istiod-ca-cert istio-token istio-data config-volume egressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  15m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[egressgateway-certs istiod-ca-cert istio-token istio-data egressgateway-ca-certs istio-envoy podinfo kube-api-access-hlnk6 config-volume]: timed out waiting for the condition
  Warning  FailedMount  12m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[egressgateway-ca-certs kube-api-access-hlnk6 istiod-ca-cert config-volume istio-token egressgateway-certs istio-data istio-envoy podinfo]: timed out waiting for the condition
  Warning  FailedMount  10m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo kube-api-access-hlnk6 istiod-ca-cert istio-envoy config-volume istio-token istio-data egressgateway-certs egressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  8m22s               kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-token istio-data istio-envoy config-volume egressgateway-ca-certs podinfo egressgateway-certs kube-api-access-hlnk6]: timed out waiting for the condition
  Warning  FailedMount  6m6s                kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy istiod-ca-cert kube-api-access-hlnk6 istio-data podinfo egressgateway-certs egressgateway-ca-certs config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  3m50s               kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istio-data egressgateway-certs istiod-ca-cert podinfo kube-api-access-hlnk6 istio-envoy istio-token egressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  93s                 kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy istiod-ca-cert egressgateway-certs egressgateway-ca-certs kube-api-access-hlnk6 istio-token podinfo config-volume istio-data]: timed out waiting for the condition
  Warning  FailedMount  78s (x18 over 21m)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found



> can you shared more info? any log from istiod and also `kubectl describe rs -nistio-system <istio-ingressgatew-xxxxx replace with the real name>`

【More Details】
Infomation More：
【1】[root@k8smaster1 istio-1.13.0]# kubectl describe pod istiod-7586c7dfd8-4qtjk  -n istio-system

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  25m                  default-scheduler  Successfully assigned istio-system/istiod-7586c7dfd8-4qtjk to k8smaster2
  Normal   Pulling    25m                  kubelet            Pulling image "docker.io/istio/pilot:1.13.0"
  Normal   Pulled     24m                  kubelet            Successfully pulled image "docker.io/istio/pilot:1.13.0" in 1m0.599004058s
  Normal   Created    24m                  kubelet            Created container discovery
  Normal   Started    24m                  kubelet            Started container discovery
  Warning  Unhealthy  35s (x481 over 24m)  kubelet            Readiness probe failed: Get "http://192.168.137.65:8080/ready": dial tcp 192.168.137.65:8080: connect: connection refused


【2】 [root@k8smaster1 istio-1.13.0]# kubectl describe pod istio-ingressgateway-dc9c8f588-rwzbd  -n istio-system


Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    21m                   default-scheduler  Successfully assigned istio-system/istio-ingressgateway-dc9c8f588-rwzbd to k8snode2
  Warning  FailedMount  19m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-ca-certs kube-api-access-tl7sr istio-envoy istio-data config-volume podinfo ingressgateway-certs istiod-ca-cert istio-token]: timed out waiting for the condition
  Warning  FailedMount  16m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-token kube-api-access-tl7sr podinfo istiod-ca-cert istio-envoy config-volume ingressgateway-certs ingressgateway-ca-certs istio-data]: timed out waiting for the condition
  Warning  FailedMount  14m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-data istio-envoy config-volume ingressgateway-certs ingressgateway-ca-certs istiod-ca-cert istio-token podinfo kube-api-access-tl7sr]: timed out waiting for the condition
  Warning  FailedMount  12m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[kube-api-access-tl7sr istiod-ca-cert istio-token podinfo ingressgateway-ca-certs istio-envoy config-volume istio-data ingressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  9m56s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert ingressgateway-certs kube-api-access-tl7sr istio-data podinfo istio-envoy config-volume istio-token ingressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  7m40s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-certs ingressgateway-ca-certs istiod-ca-cert istio-envoy istio-token kube-api-access-tl7sr config-volume istio-data podinfo]: timed out waiting for the condition
  Warning  FailedMount  5m23s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istio-token ingressgateway-ca-certs istio-envoy istio-data ingressgateway-certs kube-api-access-tl7sr podinfo istiod-ca-cert]: timed out waiting for the condition
  Warning  FailedMount  3m7s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[ingressgateway-certs podinfo ingressgateway-ca-certs kube-api-access-tl7sr istiod-ca-cert istio-data istio-envoy config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  2m41s (x17 over 21m)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
  Warning  FailedMount  39s (x2 over 49s)     kubelet            (combined from similar events): MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found


【3】root@k8smaster1 istio-1.13.0]# kubectl describe pod istio-egressgateway-6cf5fb4756-p4bzf  -n istio-system

Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    21m                 default-scheduler  Successfully assigned istio-system/istio-egressgateway-6cf5fb4756-p4bzf to k8snode1
  Warning  FailedMount  19m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert egressgateway-ca-certs config-volume istio-data kube-api-access-hlnk6 istio-envoy istio-token podinfo egressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  17m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo egressgateway-ca-certs kube-api-access-hlnk6 istio-envoy istiod-ca-cert istio-token istio-data config-volume egressgateway-certs]: timed out waiting for the condition
  Warning  FailedMount  15m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[egressgateway-certs istiod-ca-cert istio-token istio-data egressgateway-ca-certs istio-envoy podinfo kube-api-access-hlnk6 config-volume]: timed out waiting for the condition
  Warning  FailedMount  12m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[egressgateway-ca-certs kube-api-access-hlnk6 istiod-ca-cert config-volume istio-token egressgateway-certs istio-data istio-envoy podinfo]: timed out waiting for the condition
  Warning  FailedMount  10m                 kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[podinfo kube-api-access-hlnk6 istiod-ca-cert istio-envoy config-volume istio-token istio-data egressgateway-certs egressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  8m22s               kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-token istio-data istio-envoy config-volume egressgateway-ca-certs podinfo egressgateway-certs kube-api-access-hlnk6]: timed out waiting for the condition
  Warning  FailedMount  6m6s                kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy istiod-ca-cert kube-api-access-hlnk6 istio-data podinfo egressgateway-certs egressgateway-ca-certs config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  3m50s               kubelet            Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istio-data egressgateway-certs istiod-ca-cert podinfo kube-api-access-hlnk6 istio-envoy istio-token egressgateway-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  93s                 kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-envoy istiod-ca-cert egressgateway-certs egressgateway-ca-certs kube-api-access-hlnk6 istio-token podinfo config-volume istio-data]: timed out waiting for the condition
  Warning  FailedMount  78s (x18 over 21m)  kubelet            MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found

**Comment by zirain** [comment]
this might be the root cause:
```
Warning FailedMount 78s (x18 over 21m) kubelet MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
```
please verify is that configmap exists in istio-system namespace, also you can check is there anything wrong in istiod pod

**Comment by 1511563371** [comment]
【The problem is solved】

**Comment by mpuertao** [comment]
@1511563371  Hello, how to solve the problem? helpme please
