### ISSUE TITLE
Disable inbound/outbound proxy 

### ISSUE THREAD

**Issue by fz197** [istio/istio#37530]
Is there a way to disable only inbound or outbound traffic proxy? Will manually change the iptables rule work?

Thanks in advance!

**Comment by bianpengyuan** [comment]
See Sidecar API: https://istio.io/latest/docs/reference/config/networking/sidecar you can specify capture mode node to disable proxy on one direction.

**Comment by fz197** [comment]
Great! Thanks for the pointer!

**Comment by fz197** [comment]
Thanks again. I tried the below code but it looks like it didn't work. Am I missing anything? 

```apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: default
spec:
  egress:
      captureMode: NONE
      hosts:
      - "*/*"

**Comment by bianpengyuan** [comment]
Actually, I think I probably misunderstood your question. What you are looking for is probably `traffic.sidecar.istio.io/excludeInboundPorts` and `traffic.sidecar.istio.io/excludeOutboundPorts` to disable traffic capturing: https://istio.io/latest/docs/reference/config/annotations/

**Comment by fz197** [comment]
Awesome! Thanks!
