### ISSUE TITLE
Clusterregistry UX and security

### ISSUE THREAD

**Issue by costinm** [istio/istio#3756]
Most urgent fix is moving the config to a k8s 'secret', and mounting it in the templates ( with optional = true). It's probably best if a default value is chosen, like the other secret files used by Istio, and at startup 
pilot checks for the existence of the file, so user doesn't have to modify flags, just create the secret file.
(since the file includes private keys and other secrets)

Second issue is that for the 'primary' k8s we should use the in-cluster config (at least by default). The typical deployment will be Pilot in the 'primary' cluster, and we don't want to require user to deal with the primary cluster secrets. This will also simplify the installation - user will just need to add a config with the 
'additional' clusters and their secrets, and on restart pilot will start monitoring them. 

Finally, I think I understand why the pilot address is there, and we may use it in future - but we could
also simplify the code and assume that in the mesh there is a primary cluster, and that's the default config. When we switch the the real cluster registry (probably after 1.0) - we can revisit.

**Comment by sdake** [comment]
I think the first issue is resolved by @sbezverk 's https://github.com/istio/istio/pull/4706

Agree re second issue, and in an older rev of 4706, I thought this was resolved, but I could be mistaken.

Note you mentioned when we switch in the "real cluster registry post 1.0" - Today we are using the cluster registry in the implementation.  See:
https://github.com/istio/istio/blob/master/pilot/pkg/config/clusterregistry/conversion.go#L31

Is what your proposing here to remove L31 (and associated related implementation) and to simply implement a data structure that stores only the things we need?  FWIW, I think that is warranted in this case and switching to cluster registry once it becomes beta or stable makes more sense to me than the current implementation.  The current cluster registry is in the process of a rewrite: see https://github.com/kubernetes/cluster-registry/issues/215.

**Comment by sdake** [comment]
cc @john-a-joyce 
cc @sbezverk
