### ISSUE TITLE
Istio pod cannot connect to another pod by gRPC

### ISSUE THREAD

**Issue by politrons** [istio/istio#37569]
I´m having problems to understand why my `istio `pod service is not able to connect by `gRPC `to another pod.

I can see the communication from pod A y able to reach `envoy sidecar proxy of B`, but this one never route the request to the service container.

Here the log from the envoy sidecar of B

`[2022-02-26T01:04:14.736Z] "- - -" 0 - "-" "-" 954 899 1007 - "-" "-" "-" "-" "127.0.0.1:9100" inbound|9100|test-service|sygdc-bld.svc.cluster.local 127.0.0.1:35656 192.168.1.217:9100 192.168.30.240:39062 outbound_.9100_._.sygdc-bld.svc.cluster.local -`

I tried to make a curl form the service A to service B and I´m able to pass through the envoy sidecar of B, but when I try by gRPC I got stuck in proxy sidecar.

Any idea what to look?

**Comment by bianpengyuan** [comment]
What is the error log you see at client? I think we will need trace or debug level log from envoy proxy to get more clue: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

**Comment by politrons** [comment]
Thanks, finally the issue was not related with this
