### ISSUE TITLE
30 second gRPC config update during istio-proxy startup

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#37587]
### Bug Description

I'm seeing extremely long (2 minutes) sidecar initialization times in a Kubernetes environment with ~800 Envoy clusters being added by CDS. This is a multi-cluster, single network topology. I worked with @howardjohn to troubleshoot, and we took the following actions:
- try out a nightly version of the sidecar (no change - still 2 minutes until "Envoy proxy is ready")
- After seeing `2022-02-25T22:38:50.154526Z     debug   envoy config    gRPC config update took 32421 ms!` in the logs as well as a 50ms duration per Envoy cluster update, we tried bumping the sidecar CPU to an insane amount: 2000m request and 4000m limit on a GCP n2-standard-8 (init time halfed to ~1 min but still took 33361ms for the gRPC config update and a 40ms update time)

CDS duration log example:
```
4590-2022-02-25T22:38:45.254754Z        debug   envoy upstream  cds: add/update cluster ...
4591-2022-02-25T22:38:45.300338Z        debug   envoy upstream    upstream filter #0:
4592-2022-02-25T22:38:45.300371Z        debug   envoy upstream      name: istio.metadata_exchange
```

cc @brandonlbarrow @justinb-shipt

### Version

```prose
client version: 1.11.2
control plane version: 1.12.3
data plane version: 1.14-alpha.bb637511f12309b07fc648a339db6a06bbbf8f22 (2 proxies), 1.12.3 (3 proxies)

kubectl version
Client Version: v1.19.7
Server Version: v1.21.6-gke.1500
```

### Additional Information

I can Slack DM someone more detailed logs, but will not post them in a public GitHub

**Comment by howardjohn** [comment]
cc @lambdai

**Comment by lambdai** [comment]
Update:

@keithmattix  mentioned the 1.14-dev build helped, likely the https://github.com/envoyproxy/envoy/pull/19971

The current a huge observable is the dns timing out and the proxy waited for successful dns resolve result
