### ISSUE TITLE
istio_requests_total missing - traffic not routed through the istio sidecar

### ISSUE THREAD

**Issue by dragosrosculete** [istio/istio#37585]
Hi,

So I am trying to understand why this is happening.
My test is with simple nginx deployment and I am not seeing metrics from istio_requests_total  in the sidecar logs.

This is the yaml I am using:

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: nginx
>   namespace: test
> spec:
>   selector:
>     matchLabels:
>       app: nginx
>   replicas: 2 
>   template:
>     metadata:
>       annotations:
>         traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
>       labels:
>         app: nginx
>         sidecar.istio.io/inject: "true"
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:1.14.2
>         ports:
>           - name: web
>             containerPort: 80
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: nginx
>   namespace: test
> spec:
>   ports:
>     - protocol: TCP
>       name: web
>       port: 80
>   selector:
>     app: nginx
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: nginx-external
>   namespace: test
> spec:
>   hosts:
>   - "nginx.eks.devops.secret.com"
>   gateways:
>   - istio-system/istio-ingressgateway-external
>   http:
>   - match:
>     - uri:
>         prefix: /
>     route:
>     - destination:
>         host: nginx.test.svc.cluster.local
>         port:
>           number: 80
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: nginx-internal
>   namespace: test
> spec:
>   hosts:
>   - "nginx.internal.eks.devops.secret.com"
>   gateways:
>   - istio-system/istio-ingressgateway-internal
>   http:
>   - match:
>     - uri:
>         prefix: /
>     route:
>     - destination:
>         host: nginx.test.svc.cluster.local
>         port:
>           number: 80

The sidecar is inject and I am able to see other metrics in there.
I have other java applications that are deployed and those do write metrics for istio_requests_total and I can see the requests passing through the sidecar.

After a lot of debugging I found what might be the issue but I don't understand why.
By default Istio comes with MutualTLS 
After applying this destinationRule I could see logs and requests going through the sidecar and getting istio_requests_total 

> ---
> apiVersion: networking.istio.io/v1beta1
> kind: DestinationRule
> metadata:
>  name: nginx
>  namespace: test
> spec:
>  host: nginx.test.svc.cluster.local
>  trafficPolicy:
>    tls:
>      mode: DISABLE

Why is this only happening on this nginx deployment example or on another image that I've tested "containous/whoami" but on my other java applications it works fine ?

**Comment by zirain** [comment]
why did you set this `traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0`?

**Comment by dragosrosculete** [comment]
I had to add that for some of my applications to be able to communicate to external DB's  . Couldn't find any other way.

It does not impact our test however. We can remove that annotation and the behaviour remains the same.
