### ISSUE TITLE
TestFileSecrets test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37592]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1498362808511762432

**Comment by howardjohn** [comment]
@ramaraochavali this is a real bug, can you take a look? The problem is we have two different methods of handling add and remove. In tests we do "add; Remove; add". Its not always processed in order

**Comment by ramaraochavali** [comment]
Sure

**Comment by ramaraochavali** [comment]
@howardjohn TBH, I did not fully understand the problem but thought you were referring to what I did in https://github.com/istio/istio/pull/37656 . Can u please explain more, if that is not the case?

**Comment by ramaraochavali** [comment]
@howardjohn Can you please expand more on the issue ^^ - was my understanding correct that it is a test bug?

**Comment by howardjohn** [comment]
I think it's a real bug. the problem is we may do an add+remove+add of a file. This is perfectly valid and has a defined ordering (ie we did these actions in sequence in single thread).The result should be we are watching the cert

But then in the agent we are handling adds and removes in seperately in different threads. So it turns out we may process them in order "add, add, remove". This ends up NOT watching the cert

**Comment by ramaraochavali** [comment]
I see. Now I get it. Let me try to fix it.
