### ISSUE TITLE
Memory leak in the Istio sidecar proxy

### ISSUE THREAD

**Issue by darshanpatel29** [istio/istio#37605]
### Bug Description

We have been running Istio sidecar proxies that are consistently leaking memory over the span of a few days (as shown in the chart that uses `container_memory_working_set_bytes`)

<img width="1597" alt="Screen Shot 2022-02-28 at 11 01 42 AM" src="https://user-images.githubusercontent.com/46955482/156067608-c1893d08-9f96-463f-9fd6-fcefcbadd910.png">

We have observed this across many different services. This issue may be related to #33073

The memory profiling (inuse-space and inuse-objects) for the istio-proxy as instructed on [this page](https://github.com/istio/istio/wiki/Analyzing-Istio-Performance) looks like this -

![heap_profile_inuse_space](https://user-images.githubusercontent.com/46955482/156458291-62605800-415c-4326-899c-fd34aeb1cad1.gif)
![heap_profile_inuse_objects](https://user-images.githubusercontent.com/46955482/156458284-f10c486c-8026-46a5-9be8-bbc77d75f97e.gif)

I can provide any other details if you need them.

### Version

```prose
$ istioctl version  
client version: 1.13.1  
control plane version: 1.9.8  
data plane version: 1.9.8 (340 proxies), 1.8.5 (14 proxies), 1.9.6 (27 proxies), 1.8.6 (9 proxies)
```

**Comment by taitelman** [comment]
https://github.com/istio/istio/issues/38716

**Comment by taitelman** [comment]
yes, I can confirm that even istio 1.13.2 is leaking badly not only in istiod but also in the the sidecars as well for example few observations:
first: istio-init container may use over 979MB (yes 1GB+) 
2nd: istio-proxy container will work normally for a day (i.e. 40MB in istio 1.11) and then suddenly, out of the blue (on Saturday 3AM where there is no traffic) will jump to 230MB.
below is the graph of the istio-proxy container only: (app container is 15MB flat)
![c-700e9b33-b4d8-4eb4-a62b-784131703262-srvapi-7f66886987-qwqh5 memory](https://user-images.githubusercontent.com/8079496/167298416-7201fdda-71bf-4bb5-ae5e-dca305828388.png)


3rd: istio-proxy container in some cases doesn't stop at 230MB (same deployment as 2nd case just different pod) it keeps spiking to 600MB (just before it reaches the  ```sidecar.istio.io/proxyRamLimit``` and then K8s kills it as expected):
![c-700e9b33-b4d8-4eb4-a62b-784131703262-srvapi-7f66886987-st4rp memory](https://user-images.githubusercontent.com/8079496/167298405-c966e319-e32e-424b-a9f3-5ceed3246ab7.png)

I will start collecting heap dumps via pprof.
but what I suspect is tons of warning in the istio-proxy container about :
```
 xdsproxy	upstream [number] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
```
I have a hunch it is connected.
```
tmp$ kubectl top po -n istio-system
NAME                                                  CPU(cores)   MEMORY(bytes)   
grafana-69ccf87b97-5tw99                              2m           54Mi            
istio-egressgateway-547466949-hhsft                   13m          727Mi           
istio-egressgateway-547466949-hzxqk                   18m          732Mi           
istiod-58cc96df76-6dbxf                               486m         4957Mi          
istiod-58cc96df76-82w2w                               1122m        1175Mi          
istiod-58cc96df76-8w8gd                               835m         1031Mi          
istiod-58cc96df76-bxctw                               57m          3538Mi          
istiod-58cc96df76-h2vff                               90m          3467Mi          
istiod-58cc96df76-k6dlz                               78m          4120Mi          
istiod-58cc96df76-vjqth                               29m          1812Mi          
istiod-58cc96df76-vvkl8                               77m          4249Mi          
istiod-58cc96df76-wlvtj                               735m         1173Mi          
istiod-58cc96df76-xvzqk                               1060m        1028Mi          
jaeger-7d656bc7c6-zsz8j                               3m           24Mi            
lon04-public-custom-ingressgateway-688ffb66b8-4n7sd   15m          768Mi           
lon04-public-custom-ingressgateway-688ffb66b8-9w5dw   21m          823Mi           
lon04-public-custom-ingressgateway-688ffb66b8-krhs7   21m          832Mi           
lon04-public-custom-ingressgateway-688ffb66b8-p75hn   22m          825Mi           
lon04-public-custom-ingressgateway-688ffb66b8-zqng5   20m          830Mi           
lon05-public-custom-ingressgateway-8497d4d6df-4dv47   20m          767Mi           
lon05-public-custom-ingressgateway-8497d4d6df-kml5k   18m          818Mi           
lon05-public-custom-ingressgateway-8497d4d6df-v8tk7   22m          820Mi           
lon05-public-custom-ingressgateway-8497d4d6df-w6g8t   21m          815Mi           
lon05-public-custom-ingressgateway-8497d4d6df-zb6cq   22m          819Mi           
lon06-public-custom-ingressgateway-785b5f45f8-8h76q   13m          768Mi           
lon06-public-custom-ingressgateway-785b5f45f8-d5xdz   38m          818Mi           
lon06-public-custom-ingressgateway-785b5f45f8-g656v   14m          816Mi           
lon06-public-custom-ingressgateway-785b5f45f8-rg2pv   16m          810Mi           
lon06-public-custom-ingressgateway-785b5f45f8-vw4rq   37m          828Mi 
```

**Comment by hzxuzhonghu** [comment]
> 3rd: istio-proxy container in some cases doesn't stop at 230MB (same deployment as 2nd case just different pod) it keeps spiking to 600MB (just before it reaches the sidecar.istio.io/proxyRamLimit and then K8s kills it as expected):

About this, can you check if there is go routing leak.

**Comment by hzxuzhonghu** [comment]
You can also tune `PILOT_MAX_REQUESTS_PER_SECOND`

**Comment by taitelman** [comment]
so yesterday I added PILOT_MAX_REQUESTS_PER_SECOND=50 ( default was 25).
lets see if that helps a bit.

@[hzxuzhonghu](https://github.com/hzxuzhonghu) how do you test for go route leak ? url ?
the heap dump of 10 minutes show very little:
![image](https://user-images.githubusercontent.com/8079496/167369433-1e2296ca-aae6-4c4f-b43c-1b70a272eec4.png)

**Comment by hzxuzhonghu** [comment]
Golang pprof can see go routines, istiod provided it. You can google it

**Comment by taitelman** [comment]
so you want to run pprof on the istiod (isn't that covered in https://github.com/istio/istio/issues/38716 ?) . not on the istio sidecar ?

**Comment by hzxuzhonghu** [comment]
>so you want to run pprof on the istiod (isn't that covered in https://github.com/istio/istio/issues/38716 ?) . not on the istio sidecar ? 

Sorry, should be istio-proxy, it expose 15020 to serve debug/pprof

**Comment by taitelman** [comment]
![image](https://user-images.githubusercontent.com/8079496/167558768-b6047a26-5c12-4c75-a097-241bdd0ac1d9.png)

**Comment by taitelman** [comment]
the nice thing about istio-proxy container violent start: it comes with CPU spike:
![image](https://user-images.githubusercontent.com/8079496/167583615-61f316c9-5d37-4697-b2c4-d582d09394ee.png)
and the memory graph:
![image](https://user-images.githubusercontent.com/8079496/167583693-ff61a89f-59bc-4ffc-9897-4afc070f3601.png)

I believe the same happens during istio-init

**Comment by taitelman** [comment]
another thought: maybe istio `1.13.2` isn't compatible with my K8s version `1.20.15_1578` . maybe that's the source for the leak ? although no errors on istio logs everything works as expected for several hours.

**Comment by taitelman** [comment]
memory leak was produced also in smaller cluster with:
```
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (4908 proxies)
```

**Comment by taitelman** [comment]
k. once I set the ```PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING=false``` I saw a huge effect on the istiod  network connections count:
![image](https://user-images.githubusercontent.com/8079496/168609532-a033c412-1d57-469d-a9c8-84528979781e.png)
at 4:15 you can see the istiod discovery container dropped its connections from 2500 to 10X less.

**Comment by taitelman** [comment]
dup of https://github.com/istio/istio/issues/38716

**Comment by ldemailly** [comment]
> ```
> $ istioctl version  
> client version: 1.13.1  
> control plane version: 1.9.8  
> data plane version: 1.9.8 (340 proxies), 1.8.5 (14 proxies), 1.9.6 (27 proxies), 1.8.6 (9 proxies)
> ```

That's ancient and a mix of 1.8, 1.9 with 1.13, is that even supported ? I don't think you can jump 5 major versions at once?


> memory leak was produced also in smaller cluster with:
> 
> ```
> client version: 1.13.3
> control plane version: 1.13.3
> data plane version: 1.13.3 (4908 proxies)
> ```

ok that's better (maybe try 1.13.4?) but "smaller" cluster with 5k pods isn't exactly "small"? (not to say it should leak but it's certainly a very high use case)

**Comment by howardjohn** [comment]
For those following along - since I got confused by this as well - there are two distinct folks having issues, and fairly different. IMO this issue is about the latter, since the original issue is too old (ie the one with 1.13 and a sudden spike).

**Comment by taitelman** [comment]
just an update: the issue is not solved. for now I just keep my dataplane small and it minimizes the chances of memory leak.

**Comment by Umenezumi** [comment]
Hi, have you solved this problem recently?

**Comment by taitelman** [comment]
no. didn't have time to dig deeper.
I only mitigated the time window of the proxy container restart , so customer will not "feel" the istio-proxy being disconnected .
that's poor men solution but I'm ok with that.

**Comment by Umenezumi** [comment]
> no. didn't have time to dig deeper.

Again, this issue is beyond my capabilities and I plan to replace it with container management for cloud services

**Comment by rafaelsierra** [comment]
We have faced exactly the same issue and found that the issue was that we were overriding connections on our application side without properly closing it.

It seems that Istio holds those connections open forever (or until it consumes all available memory and dies).

Making sure we closed all the connections on the application side seems to have solved it.

Is it possible to set idle read/write timeouts?

**Comment by hzxuzhonghu** [comment]
Yes, there are options on r/w timeout and also on connection max idle time

**Comment by owais** [comment]
We are still experiencing this issue in all our clusters. We've since then upgraded from 1.9 to 1.18 and there has been no change in this behavior. Almost all services exhibit the same issue. Can we please re-open this? Happy to share any debugging info that could be useful to figure this out.

**Comment by owais** [comment]
Note that I'm talking about the original issue reported here, not the other comment about istio-init consuming too much memory. We are seeing a slow but constant increase in memory on high traffic pods. Sidecar memory goes from 100-200mb to 1-2GB over the course of a few days and eventually results in the pod getting OOM killed. 

Below a chart showing the memory consumption for one of the affected pods. Pod started on 25th Oct with 14% (of 1Gb) memory consumption and today sits at ~60%. In a few more days, it'll result in the pod getting killed once the mem crosses the configured limit of 1GB. We have other cases where this increases much faster. It looks like it the rate of increase is proportional to the traffic.

**Comment by Umenezumi** [comment]
> Note that I'm talking about the original issue reported here, not the other comment about istio-init consuming too much memory. We are seeing a slow but constant increase in memory on high traffic pods. Sidecar memory goes from 100-200mb to 1-2GB over the course of a few days and eventually results in the pod getting OOM killed.
> 
> Below a chart showing the memory consumption for one of the affected pods. Pod started on 25th Oct with 14% (of 1Gb) memory consumption and today sits at ~60%. In a few more days, it'll result in the pod getting killed once the mem crosses the configured limit of 1GB. We have other cases where this increases much faster. It looks like it the rate of increase is proportional to the traffic.

same like me

**Comment by zirain** [comment]
reply on closed issue without any data won't help, please kindly fire an new issue and share the detail.

**Comment by owais** [comment]
The issue could be opened up with all data collected so far available but it's fine. I'll open a new one and copy over all data we've shared so far.

**Comment by owais** [comment]
Opened a new issue: https://github.com/istio/istio/issues/48028
