### ISSUE TITLE
istio-1.10.4 - warning envoy config StreamAggregatedResources gRPC config stream closed: 14, transport is closing

### ISSUE THREAD

**Issue by zohebs341** [istio/istio#37623]
### Bug Description

Our production workloads are running as a pod in Azure AKS with istio sidecars.

Frequently we are getting below message in istiod logs.

info ads ADS: "xxxxxx:43082" sidecar~x.x.x..200~pod~namespace.svc.cluster.local-65053 terminated rpc error: code = Canceled desc = context canceled

From Application Pod Log: 2022-02-28T03:42:35.901363Z warning envoy config StreamAggregatedResources gRPC config stream closed: 14, transport is closing

And in AKS Nodes, I can see below logs.

controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
AKS Version: 1.21.7

Istio Image - docker.io/istio/proxyv2:1.10.4-distroless
Vesion - 1.10.4 

### Version

```prose
istio version - 1.10.4

Kubernetes Version Details:

Client Version: v1.22.0
Server Version: v1.21.7

Helm 3
```

### Additional Information

From Application Pod Log: 2022-02-28T03:42:35.901363Z warning envoy config StreamAggregatedResources gRPC config stream closed: 14, transport is closing

**Comment by zirain** [comment]
IIRC, the connection will rebuild every 30 minutes.

**Comment by zohebs341** [comment]
@zirain Thanks for your quick response. I just wanted to know more details about it.

As we have more than 200+ Pods with istio sidecars, for all 200 pods the same error will occur?

How about network disconnection? How long it will take to rebuild a new connection.

Do we need to upgrade it to a specific version to avoid this rebuild or is there any mitigation for now?

**Comment by zirain** [comment]
> @zirain Thanks for your quick response. I just wanted to know more details about it.
> 
> As we have more than 200+ Pods with istio sidecars, for all 200 pods the same error will occur?
> 
> How about network disconnection? How long it will take to rebuild a new connection.
> 
> Do we need to upgrade it to a specific version to avoid this rebuild or is there any mitigation for now?

normally, the connection will timeout ervery 30 minutes, and rebuild immidetily.

after this PR https://github.com/istio/istio/pull/36764, you can use `IstiodConnectionErrors` metrics to find out is there really something error.

**Comment by zohebs341** [comment]
@zirain Thanks for sharing the info. Is below error from AKS Node is related to the same connection rebuild(every 30 mins) - Istio

As this error is repetitive, in AKS Nodes.

Error From AKS Node:
kubelet[2981]: I0307 07:03:24.616019 2981 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

**Comment by gabrielfreire** [comment]
Istio 1.10.0 gateway and virtual services work until the following message, then it stops working unless i restart the istio-ingressgateway deployment

```
2022-08-09T08:46:52.789115Z warning envoy config StreamAggregatedResources gRPC config stream closed: 14, transport is closing
--
Tue, Aug 9 2022 9:46:53 am | 2022-08-09T08:46:53.191486Z info xdsproxy connected to upstream XDS server: istiod.istio-system.svc:15012
```

Does anyone know why ?
