### ISSUE TITLE
`make istioctl` failing on main branch on a Mac

### ISSUE THREAD

**Issue by ericvn** [istio/istio#37625]
### Bug Description

I'm running into an issue with building on a Mac. Investigation ongoing.

### Version

```prose
`master` branch
```

**Comment by ericvn** [comment]
Likely related to a change to `github.com/containernetworking`?

**Comment by ericvn** [comment]
Maybe related to changes in https://github.com/istio/istio/pull/37166

**Comment by ericvn** [comment]
`GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /work/out/darwin_amd64/ ./cni/cmd/istio-cni` is the failure. trying to cross-compile the code to MacOS results in no Go files.

**Comment by howardjohn** [comment]
Need to do similar to what we did with the iptables packages probably
