### ISSUE TITLE
Gateway deployment controller - do not use injection

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37626]
Currently the Gateway Deployment controller (which creates Deployment from k8s Gateway) relies on injection. This is not ideal since injection is complex, may not be available in all environments, adds more failure points. Meanwhile, the same thing injecting is the one creating deployments.

We should look into just pre-injecting the deployment.

Changes needed
* Make injection support Deployments (via library, no need to expose externally)
* On each reconcile, take the base deployment and ''inject'' it. if there are changes, send to the cluster as usual.
* If there were changes Kubernetes will do a rolling restart

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale

**Comment by jewertow** [comment]
Wasn't it done in #43369?

**Comment by howardjohn** [comment]
Yep, thanks!
