### ISSUE TITLE
Fix base image builds to use consistent name (or make auto-merge)

### ISSUE THREAD

**Issue by ericvn** [istio/istio#37635]
### Bug Description

When the periodic job builds a new base image, it uses a different PR name for each new PR so we end up building new image and PR each day until one of the PRs is merged. 

The release-builder code does not use the same pr-creator that `automator` uses so there isn't a way to verify the existing image exists. Either we need to update to use pr-creator, or add some additional logic.

A second option would be to mark the PRs as `auto-merge` so they merge automatically preventing multiple PRs.

### Version

```prose
Releases that automatically build new base images (1.12+).
```

**Comment by howardjohn** [comment]
I don't think we should rely on auto-merge, can we de-dupe the PRs?
