### ISSUE TITLE
Why must Pilot be able to reach every network endpoint?

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#3764]
I was perusing the Pilot `envoy/v2/mesh.go` code and saw a comment [here](https://github.com/istio/istio/blob/ef3ebcd6fab87196bc3aecc68b4e1aa4c543c9a6/pilot/pkg/proxy/envoy/v2/mesh.go#L772) that

> The network address of the endpoint must be accessible from Pilot.

What is the rationale for this?  Is the plan for Pilot to do active health-checking of network endpoints? 

What if network policy prevents Pilot from reaching the destination?  I believe we have use cases where certain services should only be reachable by a single, explicitly-allowed client application, which are declared using fine-grained policy whitelists and enforced at layer 3.

**Comment by ldemailly** [comment]
Good catch. The comment is misleading- I think it’s about multi cluster and about whether an endpoint is on the correct network (local vs remote) not actual connection from pilot but whether the sidecar will be able to talk to this pilot.

Gautham can you clarify ?

Thanks,

Laurent

**Comment by costinm** [comment]
It's the reverse - the endpoints must be able to reach (some) pilot, for
the obvious reasons.


Costin

On Sun, Feb 25, 2018 at 12:37 PM, Laurent Demailly <notifications@github.com

**Comment by andraxylia** [comment]
That file is gone.
