### ISSUE TITLE
Deprecate Telemetry EnvoyFilters

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#37645]
Since now we have first class Telemetry API and implementation, we should remove all EnvoyFilters. The requirements here is that 

1. Deprecation should not cause disruption to the user's telemetry collection (i.e. no gap in telemetry collection, and no double collection).
2. User should be able to preserve their helm values configuration.

At 1.14 and 1.15 release (since we support skip version upgrade), we will warn about deprecation of [telemetry helm values](https://github.com/istio/istio/blob/a9a00a506dc576190f16e7cb515a2fe4281eee53/manifests/charts/istio-control/istio-discovery/values.yaml#L142) at istioctl, as well as at the istio.io upgrade guide. A migration tool will be provided, which converts helm values to Telemetry config object, and user can apply those Telemetry APIs as a replacement. To cope with the state that both EnvoyFilter and Telemetry APIs are present, we will make Istiod ignore Telemetry EnvoyFilters with well known names (e.g. stats-1.14) if the Telemetry config with the wanted name generated by the migration tool presents. As a clean up, user can optionally remove all stale EnvoyFilters.

At 1.16 release, telemetry values will just be ignored and EnvoyFilters will be removed from Istio installation, and the aforementioned Telemetry API check logic will also be cleaned up.

cc @howardjohn @douglas-reid let me know if you think this is reasonable, or should we invent something more automatic (Although I am bit worried that it will be very fragile..). 

cc @Xunzhuo let me know if you want to take a stab at this.

**Comment by bianpengyuan** [comment]
One thing worth mentioning is that we also have access log policy at values API, which is not included at Telemetry API yet. Not sure how many people are using it, but to have a water proof migration experience, we probably should add it into the Telemetry API.

**Comment by howardjohn** [comment]
IMO the basic (`enabled` ) we should auto migrate. We don't want 100% of users to need to migrate if possible. I had a WIP of this from like a year ago but cannot find it. I don't think its super hard though - we can configure mesh config (which is controlled in helm) to set default provider as prometheus for metrics if they have the flag enabled or similar. Discussed a bit in https://docs.google.com/document/d/1FMvwyoooGeiACf9b7R0A6iJyB6ZuiP7hv5-XDmXtHLo/edit#heading=h.dtchy4gy4o02

**Comment by bianpengyuan** [comment]
Yeah, agree. the default should be automated. Although I think the same hack to ignore EnvoyFilter will also be needed for this case?

**Comment by howardjohn** [comment]
Yeah we should probably still have it. We already added for MX I think?

**Comment by bianpengyuan** [comment]
Yeah, it is basically the same logic.

**Comment by bianpengyuan** [comment]
> access log policy is only really supported by the Stackdriver extension at the moment. We need work to make it more universal. Moving to using envoy.common.access_log_hint instead of istio.access_log_policy might be a way forward (along with corresponding control plane work to set access logging filters).

Yeah that sounds reasonable. Then we can make it a common property at Telemetry API instead of just SD option.

**Comment by zirain** [comment]
let's start from add new options in `telemetry` like `metadataExchange` do
`https://github.com/istio/istio/blob/6b60a3b53e169d58a5dffef9f53a98429240a6f2/manifests/charts/istio-control/istio-discovery/values.yaml#L150 

keep that be `false` until everything is ready for production(maybe at 1.16,1.17)?

**Comment by bianpengyuan** [comment]
> let's start from add new options in telemetry like metadataExchange

Not sure I follow what's proposed here.. could you elaborate a bit?

**Comment by zirain** [comment]
@bianpengyuan my thought is:
1. Add `telemetry.deprecateEnvoyfilter: false` in `values.yaml` at 1.14?
1. If `telemetry.deprecateEnvoyfilter==true` we should create `Telemetry` instead of `EvnoyFilter`, in this caes, we can allow user begin to test.
1. At 1.16(maybe later) switch `telemetry.deprecateEnvoyfilter` default to `true`
1. Remove all `Envoyfilter` related codes\yamls at 1.17?

**Comment by bianpengyuan** [comment]
> Add telemetry.deprecateEnvoyfilter: false in values.yaml at 1.14?

No I don't think we should add yet another option. Should just warn at istioctl based install if user specify any of the option there. I think it will be really hard to generate Telemetry API Config from helm values, especially we need to cover the case of Helm based install. Instead I think we can just have a offline tool to do the conversion, and focusing on making the transition smooth at control plane.

**Comment by Xunzhuo** [comment]
Hi @bianpengyuan, thanks for inviting me, I am happy to help in this task :)

**Comment by howardjohn** [comment]
>  Should just warn at istioctl based install if user specify any of the option there.

When you say warn, are we talking about just the default `telemetry.enabled=true`? Or the (uncommon) customization stuff?

It doesn't seem great to require all users to migrate for the simple enabled=true.

**Comment by zirain** [comment]
we can add some warn message via istioctl(etc. `analyze` command), what about the people install istio with helm?

**Comment by bianpengyuan** [comment]
> When you say warn, are we talking about just the default telemetry.enabled=true? Or the (uncommon) customization stuff?

only when user sets customized stuff.

> we can add some warn message via istioctl(etc. analyze command), what about the people install istio with helm?

Yeah, they will need to look at upgrade notes. Also looks like helm support deprecation support via Notes.txt and jsonschema: https://helm.sh/docs/faq/changes_since_helm2/#validating-chart-values-with-jsonschema. Maybe we can explore that path as well.

**Comment by howardjohn** [comment]
@zirain are you interested in working on this?

**Comment by Xunzhuo** [comment]
I can work on this in the next months @howardjohn , can this task be assigned this to me ?

**Comment by zirain** [comment]
> @zirain are you interested in working on this?

do we need promote `Telemetry` to beta?  that would be helpful to fix https://github.com/istio/istio/issues/37751.

**Comment by howardjohn** [comment]
This is done
