### ISSUE TITLE
Can we change istio installation strategy: Using helm for production, thanks

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#37649]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Can we change istio installation strategy: Using helm for production, thanks

From istio 1.0 to 1.5, I am using helm to install istio, since it is mainly suggested for production usage.
https://istio.io/v1.4/docs/setup/install/
This is great and very easily to integrate with flux2/ kustomize  

However, helm is not suggested from 1.6 for production usage, and still in alhpa status in istio 1.13.
 
Can I suggest to change istio installation strategy: Support helm as main installation way for production.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Please let me know your schedule or strategy, thanks

**Comment by howardjohn** [comment]
We are working on promoting it to beta. It's 99% done, mostly just updating the docs

**Comment by howardjohn** [comment]
If you like helm yes. Helm and Istioctl install are equally recommended
based on your preferences

**Comment by johnzheng1975** [comment]
That's pretty cool.
Thanks a lot. @howardjohn
