### ISSUE TITLE
Telemetry API: Consider adding Traffic Direction selection to Access Logging (and Tracing)

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#37665]
**Describe the feature request**

In the original Telemetry API proposals, there were designs for a generic `TelemetryRuleMatch` message that could live inside each domain type (metrics, access logs, tracing) and would allow tailoring of behavior based on the following attributes:
- traffic direction
- protocol
- target port

This was rejected and dropped from the initial API surface during API review. Subsequently, the `metrics` component of the API adopted a similar notion for `traffic_direction` with [`WorkloadMode`](https://istio.io/latest/docs/reference/config/telemetry/#WorkloadMode) inside of a [`MetricSelector`](https://istio.io/latest/docs/reference/config/telemetry/#MetricSelector).

There is no existing way to turn on/off logging (and/or tracing) for a workload based on traffic direction.  Access logging  (and, hopefully soon, Tracing) do provide filtering of behavior based on CEL expressions. Unfortunately, there is no Envoy attribute that covers traffic direction at the moment.

It would be useful to add a `LogSelector` message to the `AccessLogging` message that would allow matching based on traffic direction. The `LogSelector` message could be expanded to support `protocol` and other match criteria in future iterations.

**Describe alternatives you've considered**

- Add Envoy attributes for `traffic_direction` and use CEL filtering support instead. This would require Envoy-level changes and (potentially) push requirements for non-Envoy consumers of the Telemetry API to produce a similar attribute. In the original design proposal, there was a clear preference expressed for having both a structured way and an expression-based approach for this behavior.

**Affected product area (please put an X in all that apply)**

[ X ] Extensions and Telemetry
[ X ] User Experience

cc: @kyessenov @rolandkool @zirain @howardjohn

**Comment by zirain** [comment]
+1 for add `traffic_direction`
In most cases, user will not set 100% sampling in the env, the cost of networking、cpu、storage is expensive.
if there's something wired, we can change the tracing filter do capture what we really want.
I hope telemetry will enable us do something like this:
```yaml
# some special rul
- traffic_direction: OUTBOUND
  url:
    prefix: /foo
  sampling: 100%
# the default rule
- url:
    prefix: /
  sampling: 1%
```

**Comment by zirain** [comment]
@douglas-reid seems we can close this now?

**Comment by douglas-reid** [comment]
Yes. We need to write some integration tests using this functionality (iirc), but I think we can close.
