### ISSUE TITLE
docs - traffic mgmt - protocol selection - gRPC Web error

### ISSUE THREAD

**Issue by rsalmond** [istio/istio#37664]
### Bug Description

This [docs page](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) contains a table which indicates several protocols which need an environment variable set in order to use them despite being experimental.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/4367945/156425772-27ef6d07-5a5f-4fbc-8aa6-ccda41931d9d.png">

The linked document shows corresponding environment variables for enabling experimental protocol support for:

 * `PILOT_ENABLE_MONGO_FILTER`
* `PILOT_ENABLE_MYSQL_FILTER`
* `PILOT_ENABLE_REDIS_FILTER`

But nothing for gRPC Web.

I suspect that either the table is wrong and gRPC Web should not be listed there, or there is an environment variable missing from the [pilot-discovery env-vars table](https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars).

### Version

```prose
n/a
```

**Comment by zirain** [comment]
I think the docs need be updated.
