### ISSUE TITLE
RDS cache assertion failure 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37709]
https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1499541196886773760/artifacts/pilot-a1082c1b2930451fa875cc0f3/TestTraffic/_test_context/istio-state1044077535/primary-0/istiod-74cdd8db54-vzp7k_discovery.previous.log

cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
a new failure?

**Comment by howardjohn** [comment]
Yeah this was from today. Haven't had a chance to look at it yet

**Comment by hzxuzhonghu** [comment]
OK, will look into it

**Comment by hzxuzhonghu** [comment]
It looks the virtualhosts are not sorted, out of order

**Comment by howardjohn** [comment]
I see. So that should not actually impact real users much, right? Its in one of the lists that order does not matter in envoy (?)

**Comment by howardjohn** [comment]
Same issue in https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1499627745921994752/artifacts/pilot-endpointslice-056847cd01a/_suite_context/istio-state-1862642344/primary-0/istiod-5b7c67974c-tnn8t_discovery.previous.log

and https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1499759856070955008/artifacts/pilot-endpointslice-681a485a20c/_suite_context/istio-state-2853821471/primary-0/istiod-5b7c67974c-2m72j_discovery.previous.log

So this is either a regression OR caused by the go 1.18 upgrade

**Comment by howardjohn** [comment]
It might be real bug since https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-istiodless-mc_istio_postsubmit/1499589787684704256 and https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-istiodremote-mc_istio_postsubmit/1499577121645793280 also fail for similar reasons

and https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37708/integ-distroless_istio/1499793968668348416

could also be related to the push context change I made

**Comment by howardjohn** [comment]
@hzxuzhonghu my theory was the recent change with push context broke because we still set PushTime to `now()` but used old push context. I changed that in https://github.com/istio/istio/pull/37732, but still seems to have some issues...

**Comment by hzxuzhonghu** [comment]
Sorry i am ooo last three days, trying to  catch up

**Comment by howardjohn** [comment]
last update is I think this is broken by https://github.com/istio/istio/pull/37604, and we reverted it. Hoping that https://github.com/istio/istio/pull/37800 fixes both problems. Will run that in tests many times before merging to make sure

**Comment by hzxuzhonghu** [comment]
The log shows the two vhosts are not same, the vs only applied to one vhost.  So I suspect it is something about vhost cache.  NO evidence yet

**Comment by hzxuzhonghu** [comment]
The assertion failure is not 100 %, right?

**Comment by howardjohn** [comment]
Not 100% but frequent. But i haven't  seen since https://github.com/istio/istio/pull/37604 revert, so I think that was buggy
