### ISSUE TITLE
replace Pilot's test server with Fortio

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3771]
investigate replacing by fortio

**Comment by ldemailly** [comment]
fortio has had grpc echo since day one :)

try for instance:

fortio grpcping -grpc-secure fortio.istio.io:443

**Comment by kyessenov** [comment]
The client needs to be replaced as well. Is there an output that's machine
readable?

**Comment by ldemailly** [comment]
yes `fortio load -json` or `fortio curl -json` or even better don't use a seperate binary but use the library from the test code directly like
https://github.com/istio/istio/blob/release-0.5/tests/e2e/tests/mixer/mixer_test.go#L494-L508

**Comment by ldemailly** [comment]
fortio does not have (yet) websocket though

**Comment by ldemailly** [comment]
see https://docs.google.com/document/d/1JjwL79T1Bpk0LiWJrAgS_HaPZtGQa00mL4TcjiPrA4U/edit

@kimikowang
