### ISSUE TITLE
duplicate hosts across service entries leads to passing NACKed config to envoy

### ISSUE THREAD

**Issue by ilackarms** [istio/istio#37725]
### Bug Description

when configuring a service entry with a host that matches an existing k8s service host: 
this error shows on istiod, and the proxy receiving the config will not boot/accept initial config from istiod.

```
-03-03T23:16:10.601392Z     info    ads     Push Status: {
    "pilot_duplicate_envoy_clusters": {
        "outbound_.9080_._.details.bookinfo.svc.cluster.local": {
            "proxy": "istio-ingressgateway-7cc585b9c-6nt4w.istio-system",
            "message": "Duplicate cluster outbound_.9080_._.details.bookinfo.svc.cluster.local found while pushing CDS"
        },
        "outbound|9080||details.bookinfo.svc.cluster.local": {
            "proxy": "productpage-v1-65c96b7dbf-2v8f8.bookinfo",
            "message": "Duplicate cluster outbound|9080||details.bookinfo.svc.cluster.local found while pushing CDS"
        }
    }
```

istiod should probably detect these configs and prevent them from making it to the proxy

### Version

```prose
client version: 1.10.3
control plane version: 1.10.3
data plane version: none
```

**Comment by howardjohn** [comment]
That error you posted is not a NACK. Can you post the actual NACK log?

Also your version is EOL. It's very possible this was fixed already as it sounds tami

**Comment by jmunozro** [comment]
I've reproduced this issue in 1.12.2:

**Comment by ramaraochavali** [comment]
Do you mean this error 

```
 ads     Push Status: {
    "pilot_duplicate_envoy_clusters": {
        "outbound|15443||k8s-istiosys-ingressg-0f69a51607-2c85dfeccf496a11.elb.eu-central-1.amazonaws.com": {
            "proxy": "productpage-v1-6b746f74dc-ghw7b.default",
            "message": "Duplicate cluster outbound|15443||k8s-istiosys-ingressg-0f69a51607-2c85dfeccf496a11.elb.eu-central-1.amazonaws.com found while pushing CDS"
        }
    }
}
```

We just log that but we do not send duplicate clusters to Envoy so it should not lead to NACK.

**Comment by ramaraochavali** [comment]
Also please note, envoy does not reject the request if there are duplicate clusters/listeners. It processes the other clusters

**Comment by jmunozro** [comment]
It doesn't break anything, but the sidecar is only aware of ONE of the ips:

**Comment by ilackarms** [comment]
just as a note, for my original issue I misinterpreted the log as a NACK, it may have been a red herring for another issue

**Comment by ramaraochavali** [comment]
Can you explain what is your goal here? Why do you want to k8s host in SE hosts?
