### ISSUE TITLE
Remove Response Headers at Istio Virtualservice

### ISSUE THREAD

**Issue by rameshar16** [istio/istio#37726]
Hi All,
I am trying to remove the response header from the request by removing the response header filed at Istio virtual service level. But, it is not working, and seeing the request.

Below code mentioned in virtualservice.
`  http:
      - headers:
          request:
            set:
              test: "true"
          response:
            remove:
              - test
              - arbitrary`
              
Thanks and Regards,
Ramesh

**Comment by bianpengyuan** [comment]
You can check config dump to see if virtual service applied properly in your case: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2 Note in case this is the case, virtual service takes effect at client side sidecar or the ingressgate way.

**Comment by rameshar16** [comment]
Hi @bianpengyuan,
Thank you for sharing the troubleshooting document.
It is working as expected now.

Thanks and Regards,
Ramesh
