### ISSUE TITLE
TestEdsCache is flaky

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#37756]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/37722/unit-tests_istio/1499786654670393344/build-log.txt

**Comment by ramaraochavali** [comment]
@howardjohn could this be related to push context change? I am seeing this since two days?

**Comment by howardjohn** [comment]
Probably so, need to look into it

**Comment by howardjohn** [comment]
I don't think it is, I can reproduce with and without it

**Comment by howardjohn** [comment]
1.13: `1053 runs so far, 0 failures (100.00% pass rate). 4.69240598s avg, 6.792750143s max, 1.860541828s min`
master: `522 runs so far, 2 failures (99.62% pass rate). 4.825105477s avg, 10.393853101s max, 2.02398546s min`

**Comment by howardjohn** [comment]
Some findings is in master the update is a full push but in 1.13 its a incremental push. IDK why this results in the bug though. I think the diff occurs when we reflect.DeepEquals the services, but its unclear why right now. related to auto alloc

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
// to make sure the eds update run in serial to prevent stale ones can override new ones
	// There are multiple threads calling edsUpdate.
	// If all share one lock, then all the threads can have an obvious performance downgrade.
	edsQueue queue.Instance
