### ISSUE TITLE
configured mcp server then ingressgateway can’t listen 8080 port

### ISSUE THREAD

**Issue by justworld** [istio/istio#37758]
Hello, I'm trying to use mcp server, but there are some problems. here are my steps:
1. install istio with command: istioctl install --set profile=demo
![image](https://user-images.githubusercontent.com/12166589/156885856-8310fe9e-4dd0-42e0-a05e-08539a574ced.png)
2. apply gateway with command: kubectl apply -f gateway.yaml
![image](https://user-images.githubusercontent.com/12166589/156886682-8e41e4ff-1a83-43e4-a9f4-074ebf9bd89a.png)
ingressgateway pod is listening 8080 port.
![image](https://user-images.githubusercontent.com/12166589/156886001-8e19c1fd-3f43-4c05-86ba-f603ebf687fe.png)
3. edit istio configmap to add mcp server: kubectl edit cm istio -n istio-system
![image](https://user-images.githubusercontent.com/12166589/156886704-5ea96d72-7541-436f-99b1-0f2873f05527.png)
![image](https://user-images.githubusercontent.com/12166589/156886711-35cc93c7-e5cc-4fb8-9f81-bdcea4ae6a8f.png)
4. delete istiod pod to restart istiod: kubectl delete pod istiod-f886b87d7-wz77d -n istio-system
but now ingressgateway pod can't listen 8080 port
![image](https://user-images.githubusercontent.com/12166589/156886323-1899d0bf-a81b-4f95-a9ec-acd8d0f6405b.png)

### Version

```prose
istioctl version:
client version: 1.11.6
control plane version: 1.11.6
data plane version: 1.11.6 (2 proxies)

k8s version:
Client Version: v1.18.6
Server Version: v1.18.20
```

**Comment by howardjohn** [comment]
I think you may have told it to use ONLY the mcp server. Add k8s:// to the config sources to also keep reading from the cluster

**Comment by justworld** [comment]
> I think you may have told it to use ONLY the mcp server. Add k8s:// to the config sources to also keep reading from the cluster

yes, it worked
