### ISSUE TITLE
Enable ExternalProviders after Istio installed

### ISSUE THREAD

**Issue by vsabella** [istio/istio#37764]
In our team, Istio is configured and deployed via Helm in our cluster, including our ingress gateways. We want to add an externalProvider for Virtual Servic

Our team wants to add an external authorizer ([Istio / External Authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/)) but the steps require you to edit the mesh config (or add an annotation to the ingressgateway pod)

Is there a way to do this dynamically / via CRD? It’s difficult for us to manage this at installation time due to how our environments are set up.

**Comment by zirain** [comment]
is this https://docs.google.com/document/d/1WDKX-Rk_FYD2L8Ner_w7kic93ZUMPvyG84ymcZZ9BGY/edit#heading=h.4ou224hj4hil what you're look for?

**Comment by howardjohn** [comment]
Its not really clear to me how a CRD is different from a configmap? They are both just kubernetes resources you can modify with `kubectl apply`, `kubectl edit`, or any other tools

**Comment by zirain** [comment]
> Its not really clear to me how a CRD is different from a configmap? They are both just kubernetes resources you can modify with `kubectl apply`, `kubectl edit`, or any other tools

I have talk about this with @douglas-reid , here's my thought:
1. `struct` vs `unstruct`
2. with `ConfigMap`, you need mount them and add some filewatch, then ummarshal the configmap content to a struct.

**Comment by howardjohn** [comment]
> with ConfigMap, you need mount them and add some filewatch, then ummarshal the configmap content to a struct.

We already do this for mesh config -- its completely dynamic. its not actually a filewatch but a ConfigMap watch but same effect.

struct vs unstruct seems unrelated to the problems faced by the original issue?

**Comment by howardjohn** [comment]
you can do `kubectl apply ` with a configmap representing the mesh config.
The fact we generate a non empty mesh config in install is largely to
support legacy install flags - it can just as easily be empty/not exist and
fully configured by an external configmap

**Comment by douglas-reid** [comment]
> you can do `kubectl apply ` with a configmap representing the mesh config. The fact we generate a non empty mesh config in install is largely to support legacy install flags - it can just as easily be empty/not exist and fully configured by an external configmap

Sure. We can accomplish the same goal in a number of ways. But having an external CRD that doesn't mix a bunch of unrelated concepts is *arguably* a better user experience (as evidenced by the original request). obviously, that can be too much for everything, but for certain things (like external auth providers), it _feels_ like maybe support external config is more natural.

Imagine if Istio just supported something like: https://www.getambassador.io/docs/edge-stack/latest/topics/running/services/auth-service/. We wouldn't even have to define the CRD (or install it by default). Obviously, referencing such a config might require expansion of the Istio Auth API surface, but that shouldn't be too challenging.

Ultimately (not related directly to this request), we have to decide if we want to keep putting new configuration support in MeshConfig or support external configuration at some point too.
