### ISSUE TITLE
1.9.3 to 1.13.1 upgrade breaking the ingress endpoints reachability 

### ISSUE THREAD

**Issue by anannaya** [istio/istio#37806]
### Bug Description

After 1.9.3 to 1,13.1 upgrade application endpoint are failing due to SSL error
out of  10 times 4 times i am getting the ssl error

`curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.`

### Version

```prose
1.13.1
```

**Comment by anannaya** [comment]
Gateway 
`
spec:
  selector:
    istio: ingressgateway-vpc
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP2
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      credentialName: star-ciscoccservice-com-certs
      mode: SIMPLE
      minProtocolVersion: TLSV1_2
  - hosts:
    - '*'
    port:
      name: tcp
      number: 31400
`

I dont have sidecar enabled for servcice i.e MTLS is disabled for that service .

**Comment by anannaya** [comment]
@howardjohn  Thanks for responding 
One intresting thing is we have 3 gateways out of which one gateway has the issue (appx 4/10 requests failure)  
VPC gateway enabled using `service.beta.kubernetes.io/aws-load-balancer-internal: "true" ` annotations
[bug-report.tar.gz](https://github.com/istio/istio/files/8207728/bug-report.tar.gz)

attached bug report

**Comment by anannaya** [comment]
@howardjohn  The issue with CLB nodes under us-east-1c not routing the outgoing packets.  After the worker  Nodes restart
under us-east-1c solved the issue.  Thanks for the help.

confusion was .. Ingress gateway logs shows 200

**Comment by Jeffrey-Du** [comment]
@anannaya Hi, I have the same problem, my case is use Loadbalancer for ingressgateway Service through NLB, and when I change the selector to do version switching, the target groups appears unhealthy, but then the proxy Readiness shows 200. I can solve the problem after restarting the ingressgateway Deployment, but I am not sure what the cause is, have you found the cause? Thank you.
