### ISSUE TITLE
Go process no symbol table was detected

### ISSUE THREAD

**Issue by Karthikeyanraman94** [istio/istio#37805]
Hi Team,

We were not able to monitor the istio ingress gateway with the help of dynatrace operator, upon checking further we can see that the issue is due to 
**Activation of deep monitoring was unsuccessful**
**Dynatrace OneAgent wasn't able to activate deep monitoring for this Go process because no symbol table was detected.** 

https://www.dynatrace.com/support/help/shortlink/go-known-limitations#applications-must-contain-a-symbol-table

Applications must contain a symbol table
OneAgent relies on the information stored in the application binary file's symbol table. By default, Go generates a symbol table into the application binary, but this can be suppressed by command line parameters or external tools like strip.

and builds and runs applications on the fly. Because the output application file is temporary—the file is deleted automatically after the app termination—the application binary contains no symbol table. Thus, OneAgent cannot monitor an application that was generated with the go run <application> command.

**Comment by howardjohn** [comment]
We strip it by default. What are you trying to monitor? Note most of the stuff the gateway does is C++ code

**Comment by Karthikeyanraman94** [comment]
Suppressing the symbol doesn't allow dynatrace to monitor the Golang apps, their performance, their service calls etc

This is the update we got from dynatrace consultant
[Applications must contain a symbol table](https://www.dynatrace.com/support/help/shortlink/go-known-limitations#applications-must-contain-a-symbol-table). By default, Golang adds a symbol table, it could have been either suppressed with the Go build flags
go build -ldflags "-s -w"
or the resulting binary was stripped with an external cmd tool like strip.


if this can't be resolved by Istio Team, At least can we get pointed to the istio gateway docker file

**Comment by ericvn** [comment]
As John stated, we do strip the symbol table as part of the build. See https://github.com/istio/istio/blob/master/Makefile.core.mk#L258.

**Comment by howardjohn** [comment]
I am curious why you care about running this tool here. The go program is
just a tiny helper, the real work occurs in envoy
