### ISSUE TITLE
istioctl kube-inject does not respect proxyconfig custom resource

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#37801]
### Bug Description

istioctl kube-inject does not respect proxyconfig custom resource.

### Version

```prose
istio 1.13 and master
```

**Comment by irisdingbj** [comment]
@Monkeyanator  Any plan to support this? Thanks!

**Comment by zirain** [comment]
@irisdingbj can you share more details? do you mean `sidecar.istio.io/proxyCPU` ?

**Comment by irisdingbj** [comment]
> @irisdingbj can you share more details? do you mean `sidecar.istio.io/proxyCPU` ?

It is about the custom resource proxyconfigs.networking.istio.io which is introduced recently

**Comment by irisdingbj** [comment]
There are two cases here:
1.  depoyment has namespace defined -- this will be fixed via https://github.com/istio/istio/pull/38288
2.  deployment has no namespace defined -- Need to add namespace parameter for `istioctl kube-inject`

**Comment by irisdingbj** [comment]
@therealmitchconnors @esnible @howardjohn @hzxuzhonghu 

if the deployment has no namespace defined, there is current no way to find the related proxy-config .  Shall we add `namespace` parameter to `istioctl kube-inject --namespace` to support this?
