### ISSUE TITLE
Traffic outside the service mesh still send to Terminating pod which caused 503

### ISSUE THREAD

**Issue by suninuni** [istio/istio#37821]
### Description

- serviceA does not inject istio-proxy, and serviceB injects istio-proxy.
- When serviceB is rolling update, requests from serviceA still send to serviceB's Terminating pod which got 503 `upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111`.

### Tried

- serviceB has readinessProbe, so when pod change to Terminating, I can‘t found it in service endpoints.
- If serviceB not inject istio-proxy, NO 503 requests.
- If serviceA inject istio-proxy, NO 503 requests.(P.S. `defaultHttpRetryPolicy.attempts` is 0)
- Add `preStop` for istio-proxy https://github.com/istio/istio/issues/7136#issuecomment-743697302, no effects.

So I'm guessing that the problem might be on the istio-cni.

### Version

```prose
$ istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (78 proxies)
$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
$ calico-node -v
v3.15.4
```

**Comment by howardjohn** [comment]
Istio doesn't control which pod the client sends a request to. So if this is breaking there are two possibilities I can think of:
1. envoy sidecar makes the connection keep alive better, so client keeps open connection longer. this is not likely
2. envoy shuts down too quickly for your app. Default is 5s so try changing the termination drain duration https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

**Comment by suninuni** [comment]
> Istio doesn't control which pod the client sends a request to. So if this is breaking there are two possibilities I can think of:
> 
> 1. envoy sidecar makes the connection keep alive better, so client keeps open connection longer. this is not likely
> 2. envoy shuts down too quickly for your app. Default is 5s so try changing the termination drain duration https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

Thanks for your reply.

> envoy shuts down too quickly for your app

I have tried set `preStop: sleep 10` to my app container which is no effect.

According to the access log for serviceB's istio-proxy after the serviceB pod change to `0/1 Terminating`:

- If serviceA inject istio-proxy, there will no access log expected few requests from readness probe. In this situation, reqeusts from serviceA will be route by envoy according to the xDS rules.
- If serviceA not inject istio-proxy, there will output access log until pod's ready status change to `0/2` which will close to a minute. In this situation, reqeusts from serviceA will be route by kube-proxy which including the iptables rules created by istio-cni.

So I think istio-cni did not handle the iptables rules correctly at this time which cauesed reqeusts from outside still send to Terminating pod.

**Comment by howardjohn** [comment]
istio CNI doesn't impact kube proxy at all or impact any traffic on that case. If new *connections* (not requests - kube proxy only routes at connection level) are sent to the pod after termination that is either a bug in kube proxy or not waiting long enough (since then update that the endpoint is removed isn't instant).

**Comment by howardjohn** [comment]
btw the sleep 10 on your app doesn't impact how long istio proxy sleeps for. It is always 5s unless configured otherwise

**Comment by suninuni** [comment]
> how long istio proxy sleeps for

Actually istio proxy will sleep until app killed according to the changes below.

```
        lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "curl -X POST localhost:15000/drain_listeners?inboundonly; while [ $(netstat -plunt | grep tcp | grep -v envoy | grep -v pilot-agent | wc -l | xargs) -ne 0 ]; do sleep 1; done"]          
```


> Add preStop for istio-proxy https://github.com/istio/istio/issues/7136#issuecomment-743697302, no effects.

But it looks like this configuration is duplicated with the termination drain duration, I will try to remove this lifecycle.

Thanks for your reply, I will update after test.

**Comment by suninuni** [comment]
I found out that the root cause was `keepAlive` was set in serviceA‘s code. 

Although I don't know why there is no 503 requests when serviceB doesn't inject the istio proxy.

related with https://github.com/istio/istio/issues/33466#issuecomment-863988971, FYI.

**Comment by howardjohn** [comment]
It's possible svc b closes connections more aggressively than envoy does

**Comment by grantkl** [comment]
> I found out that the root cause was `keepAlive` was set in serviceA‘s code.
> 
> Although I don't know why there is no 503 requests when serviceB doesn't inject the istio proxy.
> 
> related with [#33466 (comment)](https://github.com/istio/istio/issues/33466#issuecomment-863988971), FYI.

@suninuni Do you have any details on this? We're seeing something similar in our setup.
