### ISSUE TITLE
Support Cert rotation for Control plane certificates signed by Kubernetes signer 

### ISSUE THREAD

**Issue by shankgan** [istio/istio#37838]
Istio provides several options for signing control plane certs to ensure that TLS communication from data-plane/webhooks to control plane works. 

Of these options, two of them - 
https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/server.go#L997
https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/server.go#L1003

that leverage the Kubernetes CSR API to get certificates signed using an K8s signer do not appear to have any mechanism to rotate the control plane certs (Not data plane mtls certs) close to expiry. This would need to be implemented. When leveraging Istiod CA, this is already being handled.

For long lived installations, this would effectively break webhooks and xDS unless the control plane is restarted.

**Describe alternatives you've considered**
Not using the K8s signer to sign control plane certificates

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by shankgan** [comment]
cc @myidpt

**Comment by lei-tang** [comment]
An alternative to rotating the control plane cert is to request a certificate with a long life time (e.g., 10-year). The certs signed by original k8s signers have a long life time (e.g., 10-year) and thus the rotation is not really needed. When switching to newer k8s signers, the control plane can request a cert with a long life time to avoid rotations, which simplifies  the implementation and reduces overhead and latency of requesting a new cert.
