### ISSUE TITLE
Istio envoy wrong metrics when using multiple replicas

### ISSUE THREAD

**Issue by stevalla** [istio/istio#37834]
### Bug Description

Hello,

I've noticed some strange behaviour of the counter metrics of Istio envoys when using mulitple replicas for a service.

### Environment
I have an application running in my cluster (the [the Google Online Boutique](https://github.com/GoogleCloudPlatform/microservices-demo)) with one pod for each service, and a generator which generates a constant load over the application using [Locust](https://locust.io/). The generator only communicates with the frontend service of the application. 

In the cluster we have also Prometheus installed which monitors application metrics using those provided by Istio envoys such as `istio_requests_total` from which we compute the throughput of the service with the Prom query: 
`sum(rate(istio_requests_total{job=~"envoy-stats", reporter="destination", destination_service_namespace="test", destination_service_name="ak-frontend"}[1m]))`.

![Environment](https://user-images.githubusercontent.com/32373697/157470796-cbf1770c-21e4-4a7b-a393-d1ba268bccc2.png)

We are interested in monitoring the e2e throughput seen by both: the Locust load generator, and the Istio envoy of the frontend service. 

### Problem
Using a single replica for each service everything works like a charm. I got more or less the same number of requests per second using both istio metrics and locust metrics, which are ~ 5 req/s.

The problem comes when I scale the frontend service up to 2 replicas. While the throughput seen from Locust metrics does not change (its as before ~ 5 req/s), the throughput seen from Istio metrics starts to increase indefinitely. But the pods does not have an increase on load so the requests does not increase, which suggest that Locust is right in this case; even bacause, [the Little Law](https://en.wikipedia.org/wiki/Little%27s_law) computed from the Istio metrics is not valid.

### Evidence
![Locust load generator throughput](https://user-images.githubusercontent.com/32373697/157470021-e76b5d76-56e1-4e1c-9bb9-c095145ab100.png)
![Frontend applicatoin throughput](https://user-images.githubusercontent.com/32373697/157471956-d51abe79-1305-4bd8-80cc-4fb040c7cf46.png)

In the two images we are comparing the throughput computed with the Locust metrics (first chart) with the one computed from the Istio metrics (second chart). As you can see, in the second chart the throughput is stable for a wile, and at some point starts to increase indefinitely. That was the point where I scaled the frontend service up to 2 replicas.

Making some debug I notice that the metric `istio_requests_total` starts to be resetted in the same time I scale up the service, as shown in the chart below:

![istio_requests_total counter](https://user-images.githubusercontent.com/32373697/157475381-d6724bfc-3e75-4d1d-824c-5ca3467fb2cb.png)

 

### Version

```prose
$ istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (14 proxies)

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.21.5-eks-bc4871b

$ helm version --short
v3.8.0+gd141386
```

**Comment by howardjohn** [comment]
any chance envoy is crashing or something? I don't think metrics should be removed in normal circumstances
