### ISSUE TITLE
how reslove

### ISSUE THREAD

**Issue by ylmcr7** [istio/istio#37847]
![image](https://user-images.githubusercontent.com/63889450/157569669-9b9bac87-dfb3-4d49-8d5a-ffd8f59ed55b.png)

**Comment by zirain** [comment]
do you have prometheus in the same cluster with kiali?
try to run `kubectl apply -f samples/addon/prometheus.yaml`

**Comment by ylmcr7** [comment]
> 

where url samples/addon/prometheus.yaml?
could you  give me
