### ISSUE TITLE
Make the istio-cni daemonset optional

### ISSUE THREAD

**Issue by elukey** [istio/istio#37855]
Hi folks!

**Describe the feature request**
At Wikimedia we have several on premise Kubernetes clusters, and one of them is dedicated to host the Kserve stack for Machine Learning (that includes istio and knative-serving). We are currently using only the ingress gateway, but we'd like to enable the use of the istio-proxy sidecars via the CNI component provided by Istio. We are currently managing/deploying Istio via `istioctl`, version 1.9.5.
We also use Calico to manage several networking aspects of our pods, and we use their CNI component, deployed via a special Debian package to the Kubernetes nodes, and configured via Puppet (we use it in all our production infrastructure). As far as I can see in Istio the CNI component can be deployed only via the related Daemonset, that requires high privileges (like the hostPath volumes capability) to deploy binaries and injecting configurations on the Kubernetes nodes, and we'd prefer to avoid it if possible. I am opening this issue to ask if it is possible to add an extra feature to the `istioctl` specs to allow a minimal configuration for Values.istio_cni.enabled, to offload the deployment of binaries and config to the user, tuning only the k8s annotations to be injected in various pods. Not sure if this is possible, so I am asking guidance from your side :) 

**Describe alternatives you've considered**
We have tried to deploy the istio-cni and istio-iptables binaries + /etc configurations (chained plugin config with calico) manually, but pods are not created with the istio-proxy sidecar due to missing annotations.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Is it possible to just set Values.istio_cni.enabled=true but not deploy the cni helm chart?

**Comment by howardjohn** [comment]
I think you can just do ^. If not, PRs to make that work would be appreciated
