### ISSUE TITLE
Envoy metrics for HTTP includes a stat_prefix configured by Istio

### ISSUE THREAD

**Issue by SantiMunoz** [istio/istio#37856]
### Bug Description

The HTTP Envoy metrics generated by the istio proxy, under the path `/stats/prometheus`, return the http metrics with the following format: `envoy_http_stats_<metric name>`, where `stats` is a `stat_prefix` configured by Istio. More information about this metrics format in the [official Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats).

On the other side, for the Cluster metrics Istio is not injecting any `stat_prefix`. Which is not consistent with the HTTP ones.

This `stat_prefix` is breaking integrations like the [Datadog one](https://docs.datadoghq.com/integrations/envoy/?tab=containerized#data-collected), where they expect the metrics to have the format `envoy_http_<metric name>`, without any prefix.

From the Istio documentation I can't find any way to overwrite this value. 

### Version

```prose
➜  ~ istioctl version
client version: 1.12.2
control plane version: 1.13.2
➜  ~ kubectl version --short
Client Version: v1.20.1
Server Version: v1.20.14
```

**Comment by zirain** [comment]
looks like it comes from 
https://github.com/istio/istio/blob/2a38aca26bf6d41dbd93ff9f3089eb1918d69a6e/tools/packaging/common/envoy_bootstrap.json#L469

**Comment by SantiMunoz** [comment]
Is there any way to overwrite that?

**Comment by ecliptik** [comment]
Similar issue, we're attempting to enable gzip compression for prometheus_stats, and I have it working it has to listen on a different port, otherwise the custom bootstrap filter configuration is ignored.

**Comment by zirain** [comment]
@SantiMunoz I can reproduce any metric with `envoy_http_stats_`, can you share more details about this?

**Comment by SantiMunoz** [comment]
@zirain you are correct, Istio is generating the metrics with the format `envoy_http_stats_`, as expected from the bootstrap configuration you mention.

The problem is with the Datadog integration, that doesn't expect the `stats` prefix and discard all these metrics.
From the istio side I don't see any solution as this prefix is required by the envoy filter, so I will Datadog to update their integration and accept these metrics.
