### ISSUE TITLE
Egress error for www.google.com only - Connection reset by peer

### ISSUE THREAD

**Issue by NComandini** [istio/istio#37853]
### Bug Description

I'm trying to configure some egress rules and I'm a little bit disappointed around my situation.
I'm facing a connection reset by peer only for www.google.com URL.
I have a similar behavior for www.bing.com

If I use the host https://google.com, the redirect works fine to https://www.google.com
`
kubectl exec sleep-5ff889c8cf-z9hj2 -n external -c 
sleep -- curl -sSL -o /dev/null -D - https://www.google.com
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.google.com:443 
command terminated with exit code 35
`

After the configuration of the outboundTrafficPolicy mode to REGISTRY_ONLY, I've created the following serviceentry objects:
`
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: external
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
`
petstore serviceentry
`
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: petstore
  namespace: external
spec:
  hosts:
  - petstore.swagger.io
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
`
The petstore access is working as expected.
Petstore request in istio-proxy access log :
`
[2022-03-10T09:15:59.538Z] "- - -" 0 - "-" "-" 938 7561 1173 - "-" "-" "-" "-" "3.217.118.159:443" outbound|443||petstore.swagger.io 10.73.32.220:35924 3.217.118.159:443 10.73.32.220:35922 petstore.swagger.io
`

Googles requests in istio-proxy access log : 
`
[2022-03-10T09:14:22.528Z] "- - -" 0 NR "-" "-" 0 0 16 - "-" "-" "-" "-" "-" - - 74.125.24.147:443 10.73.32.220:38302 - -
[2022-03-10T09:15:35.638Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 142.251.10.105:443 10.73.32.220:56528 - -
[2022-03-10T09:15:39.683Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 172.253.118.147:443 10.73.32.220:45404 - -
`
I tried to change protocol HTTPS by TLS but nothing change.
Thank you for you help.

### Version

```prose
istioctl version
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (3 proxies)

kubectl version --short
Client Version: v1.18.2-0-g52c56ce
Server Version: v1.19.15-eks-9c63c4

helm version --short
v3.7.2+g663a896
```

### Additional Information

Here my command to install pilot:
`
istioctl install --set profile=minimal -y --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY --set meshConfig.accessLogFile=/dev/stdout
`

Deployment of multiples gateways:

`
helm install -n external istio-ingress-ext manifests/charts/gateways/istio-ingress --set "gateways.istio-ingressgateway.name=istio-ingressgateway-ext,gateways.istio-ingressgateway.labels.istio=istio-ingressgateway-ext"
helm install -n external istio-egress-ext manifests/charts/gateways/istio-egress --set "gateways.istio-egressgateway.name=istio-egressgateway-ext,gateways.istio-egressgateway.labels.istio=istio-egressgateway-ext"
`

**Comment by howardjohn** [comment]
Istio 1.6 is almost 2 years EOL. Please upgrade and re-open if you still have issues
