### ISSUE TITLE
Request for clarification - Discovery selector and sidecar injection webhook

### ISSUE THREAD

**Issue by SpectralHiss** [istio/istio#37859]
Hey,

Just wanted to clarify if it makes sense that currently if a pod is not included in discovery through some discovery selector exclusion (for example using NotIn), if by mistake the namespace still has istio-injection=enabled it will be part of the mesh and be injected.

I am not sure if this would ever be a desired situation, I expected the istiod to reject the creation or do a noop injection , unless I am confused about how this feature is intended to be used.

**Comment by howardjohn** [comment]
It is expected, discovery selector just includes which pods/services are used for service discovery. Injection is orthogonal. You could inject a pod not included in discovery, although it would be odd
