### ISSUE TITLE
Question about failover sample with multiple clusters

### ISSUE THREAD

**Issue by quzhixue-Kimi** [istio/istio#37850]
hi there,
After reviewing the doc via https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/failover/
There is one concern that I would like to ask as below:

As described in the doc, there are three regions with four zones. (region1.zone1, region1.zone2, region2.zone3 and region3.zone4)

loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failover:
          - from: region1        // here is the source service
            to: region2            // here is the failover service (target service) 

A. I wonder if the service in region1.zone1 was down and, failover to the same region with the different zone (region1.zone2). Should it be:
failover:
          - from: region1.zone1       
            to: region1.zone2         

B. If the service in region1.zone1 was down and, failover to the region2.zone3 or region3.zone4, Should it be:
failover:
          - from: region1.zone1       
            to: region2.zone3        // failover to region2.zone3 or region3.zone4

It is appreciated that you may provide feedback.

Sorry for your inconvenience.
BR
Kimi

**Comment by hzxuzhonghu** [comment]
The localityLB failover support explicitly failover to region, the az failover is implicitly by default.

**Comment by quzhixue-Kimi** [comment]
Hi there,

Thank you for your feedback.

Will you please explain more detail about the code section as below:
...
failover:
- from: region1
   to: region2
...

In the doc, there are lots of steps:

Next, trigger a failover to region1.zone2. To do this, you [drain the Envoy sidecar proxy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining#draining) for HelloWorld in region1.zone1:

$ kubectl --context="${CTX_R1_Z1}" exec \
  "$(kubectl get pod --context="${CTX_R1_Z1}" -n sample -l app=helloworld \
  -l version=region1.zone1 -o jsonpath='{.items[0].metadata.name}')" \
  -n sample -c istio-proxy -- curl -sSL -X POST 127.0.0.1:15000/drain_listeners

Call the HelloWorld service from the Sleep pod:
$ kubectl exec --context="${CTX_R1_Z1}" -n sample -c sleep \
  "$(kubectl get pod --context="${CTX_R1_Z1}" -n sample -l \
  app=sleep -o jsonpath='{.items[0].metadata.name}')" \
  -- curl -sSL helloworld.sample:5000/hello
Hello version: region1.zone2, instance: helloworld-region1.zone2-86f77cd7b-cpxhv

What I could not understand is that in the sample code as below, if the region1 is down, should the region2(region2.zone3) receive the request?
failover:
- from: region1
   to: region2

Why region1.zone2 receive the request and send the response?


Sorry for your inconvenience
BR
Kimi

**Comment by hzxuzhonghu** [comment]
https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting-Failover Hope it is clear

**Comment by quzhixue-Kimi** [comment]
Thank you for your feedback.
