### ISSUE TITLE
Integration Tests: Use common set of apps across all suites

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#37864]
The networking tests use a common set of deployments for all their tests:

https://github.com/istio/istio/blob/030131e63b26a366492dd3efb9c5faee39048687/tests/integration/pilot/common/apps.go#L37

Advantages:

* We can use apps.All + echotest to get the matrix of different types of workloads (pods, VMs, headless, statefulset).
* Set up at suite-level, saves time setting-up and tearing down per-test.

I took a quick look at some security tests, and I see that they may have some special requirements at deploy-time:

1. Setting IncludeExtAuthz on the echo.Config
2. Testing across namespaces; the common apps have 2 namespaces, but one is for an "external" service.
3. Pods/services a to f; the common apps have a to c. 

The work here is likely going to involve baking these requirements into our common test deployment, but we probably
want to avoid making it too big. Maybe we need to avoid needing a-f and rewrite the tests so they work with a-c. *Instead of deploy a bunch of apps with a bunch of configs, and test: apply config, test, repeat.*

**Comment by nmittler** [comment]
WRT the security tests having so many deployments (`a to f`): this is because they currently apply a bunch of config and then test a bunch of combinations. It would probably be better to just apply config per destination instead.

**Comment by nmittler** [comment]
not stale
