### ISSUE TITLE
WorkloadEntry not updated when labels are changed on a VM

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#37868]
### Bug Description

When labels for a VM workload in the mesh are changed by updating the `ISTIO_METAJSON_LABELS=` setting, these new labels are not propagated to the WorkloadEntry. This is the case when the istio proxy is restarted and boots up pretty quickly.
If the istio proxy is stopped, the WorkloadEntry is purged automatically and istio proxy is started up again, the new WorkloadEntry does contain the updated labels.

This also applies to the `istio-locality` label that add the `locality` configuration on the WorkloadEntry.

### Version

```prose
Version 1.12.2 ASM
```

**Comment by hzxuzhonghu** [comment]
WLE labels can not be updated on the fly.

**Comment by hzxuzhonghu** [comment]
More discussions can refer to https://github.com/istio/istio/pull/36078
