### ISSUE TITLE
StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data

### ISSUE THREAD

**Issue by thennetirajesh** [istio/istio#37875]
Description:-

After upgrading istio from 1.10.4 to 1.11.8 noticed below message 

**warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:** 

K8's Version:  1.20.11

The  warning is occurring every 5-10min once 

<html>
<body>

Mar 11, 2022 @ 21:31:43.221 | 2022-03-11T16:01:43.221304Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:
-- | --

  | Mar 11, 2022 @ 21:31:31.361 | 2022-03-11T16:01:31.361690Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:30:13.460 | 2022-03-11T16:00:13.459965Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:29:42.890 | 2022-03-11T15:59:42.890340Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:27:50.359 | 2022-03-11T15:57:50.359354Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:27:24.130 | 2022-03-11T15:57:24.130159Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:27:21.334 | 2022-03-11T15:57:21.334777Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

  | Mar 11, 2022 @ 21:27:04.486 | 2022-03-11T15:57:04.486210Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:

</body>
</html>

**Comment by howardjohn** [comment]
This is expected. It's logged when the proxy establishes a new connection to the control plane, which happens regularly to help with load balancing.

The error log is somewhat confusing, in 1.13 it is improved

**Comment by thennetirajesh** [comment]
Hi @howardjohn,

We have upgraded Istio to 1.11.8, and from the logs continuously  we could see below  error message [tcp [::]:15020: use of closed network connection]
can please review and suggest 

<html>
<body>


May 7, 2022 @ 01:39:48.608 | message:2022-05-07T05:39:48.605936Z error accept **tcp [::]:15020: use of closed network connection** log.offset:1,827,300 log.file.path:/logs/32d5744045a7faacd8df217b3c1ddd23c874b6e82e7705f271797b1c8b838eed/32d5744045a7faacd8df217b3c1ddd23c874b6e82e7705f271797b1c8b838eed-json.log @version:1 container.image.name:istio/proxyv2:1.11.8 container.id:32d5744045a7faacd8df217b3c1ddd23c874b6e82e7705f271797b1c8b838eed container.runtime:docker kubernetes.container.name:istio-proxy kubernetes.container.image:istio/proxyv2:1.11.8 
-- | --



</body>
</html>
