### ISSUE TITLE
Enabling DNS proxy feature cause istio-init to crash - Istio 1.13.2

### ISSUE THREAD

**Issue by c0ffeec0der** [istio/istio#37885]
### Bug Description

1. Deploy istio with

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"

2. Run any pod with sidecar and below error occurs

2022-03-12T09:09:14.390209Z	info	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=true
INVALID_DROP=

2022-03-12T09:09:14.390250Z	info	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=true
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[10.96.0.10],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
EXCLUDE_INTERFACES=

2022-03-12T09:09:14.390447Z	info	Writing following contents to rules file: /tmp/iptables-rules-1647076154390301110.txt2245582807
* raw
-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
-A OUTPUT -p udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2
-A OUTPUT -p udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1
-A OUTPUT -p udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2
-A OUTPUT -p udp --dport 53 -d 10.96.0.10/32 -j CT --zone 2
-A PREROUTING -p udp --sport 53 -d 10.96.0.10/32 -j CT --zone 1
COMMIT
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 53 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -p tcp --dport 53 -d 10.96.0.10/32 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j RETURN
-A OUTPUT -p udp --dport 53 -m owner --gid-owner 1337 -j RETURN
-A OUTPUT -p udp --dport 53 -d 10.96.0.10/32 -j REDIRECT --to-port 15053
COMMIT
2022-03-12T09:09:14.390475Z	info	Running command: iptables-restore --noflush /tmp/iptables-rules-1647076154390301110.txt2245582807
2022-03-12T09:09:14.391690Z	error	Command error output: xtables parameter problem: unknown option "--zone"
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
2022-03-12T09:09:14.391725Z	error	Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1647076154390301110.txt2245582807, exit status 2

### Version

```prose
- istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (1 proxies)

- kubectl version --short,
Client Version: v1.22.5
Server Version: v1.22.5
```

### Additional Information

Since the analysis report does not capture error in istio-init, it is excluded below

---

Target cluster context: docker-desktop

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-03-12 18:11:21.279153105 +0700 +07

Cluster endpoint: https://kubernetes.docker.internal:6443
CLI version:
version.BuildInfo{Version:"1.13.2", GitRevision:"91533d04e894ff86b80acd6d7a4517b144f9e19a", GolangVersion:"go1.17.8", BuildStatus:"Clean", GitTag:"1.13.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.13.2", GitRevision:"91533d04e894ff86b80acd6d7a4517b144f9e19a", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.13.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.13.2}

**Comment by c0ffeec0der** [comment]
Hello,

OS: windows 11 WSL2 Ubuntu 20.04.4 LTS
Kernel Version: 5.10.60.1-microsoft-standard-WSL2

The error is similiar with [11778](https://discuss.istio.io/t/istio-dns-proxying-cause-iptable-error/11778). The difference is that I ran on WSL2 Ubuntu 20.04.4 LTS

I have tried with running the pod

        securityContext:
          capabilities:
            add:
             - ALL

It is still error.  [11778](https://discuss.istio.io/t/istio-dns-proxying-cause-iptable-error/11778) ran success with linux. So i guess this is due to kernel? Even if i switch from docker desktop to microk8s won't make a difference..

**Comment by c0ffeec0der** [comment]
I believe that's tried in [11778](https://discuss.istio.io/t/istio-dns-proxying-cause-iptable-error/11778)

**Comment by howardjohn** [comment]
Can you run `lsmod | grep nf`? Both from WSL2 and from within the docker-desktop VM (tbh not sure if this is possible, I have never used docker desktop). If you can't do it in the docker desktop VM directly, then run a `privileged: true` pod.

You changed the security context to add `ADD: all`. Can you also add `privileged: true`?

Can you try `modprobe nf_conntrack`?

Can you try directly running `iptables -t raw -A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1`? If it works you can remove the rule by switching the `-A` to `-D`.

The above will help debug this I think. Unfortunately don't know anyone with a windows machine to try it myself

**Comment by c0ffeec0der** [comment]
1) lsmod | grep nf (from WSL 2)
> nothing shows up
https://unix.stackexchange.com/questions/594470/wsl-2-does-not-have-lib-modules
Quote: The base WSL2 kernel does not allow modules to be loaded

2) lsmod | grep nf (from Docker desktop VM) 
> docker run k8s.gcr.io/kube-proxy:v1.22.5 lsmod | grep nf
nothing shows up, as expected related to point 1 result

3) You changed the security context to add ADD: all. Can you also add privileged: true?
With
                "name": "istio-init",
                "securityContext": {
                    "allowPrivilegeEscalation": true,
                    "capabilities": {
                        "add": [
                            "NET_ADMIN",
                            "NET_RAW"
                        ],
                        "drop": [
                            "ALL"
                        ]
                    },
                    "privileged": true,
                    "readOnlyRootFilesystem": false,
                    "runAsGroup": 0,
                    "runAsNonRoot": false,
                    "runAsUser": 0
                },
				
Result 
2022-03-14T17:24:26.702174Z info Running command: iptables-restore --noflush /tmp/iptables-rules-1647278666702005344.txt662603755
2022-03-14T17:24:26.800052Z error Command error output: xtables other problem: line 2 failed
2022-03-14T17:24:26.800071Z error Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1647278666702005344.txt662603755, exit status 1

This looks related to point 5 and 6 error

4) modprobe nf_conntrack
> modprobe: FATAL: Module nf_conntrack not found in directory /lib/modules/5.10.60.1-microsoft-standard-WSL2
Related to point 1

5) Run : iptables -t raw -A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
> owner: Could not determine whether revision 1 is supported, assuming it is.
owner: Could not determine whether revision 1 is supported, assuming it is.
CT: Could not determine whether revision 1 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 1 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied

6) iptables -t raw -D OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
> owner: Could not determine whether revision 1 is supported, assuming it is.
owner: Could not determine whether revision 1 is supported, assuming it is.
CT: Could not determine whether revision 1 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 2 is supported, assuming it is.
CT: Could not determine whether revision 1 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied

Question: while the use of nf_conntrack in WSL2 is not clear yet. However deploying pod with istio-init without dns proxy works. The module nf_conntrack should not be a problem? But it is on file permission for "Fatal: can't open lock file /run/xtables.lock: Permission denied"?

Fyi the permission is as follow:
-rw------- 1 root root 0 Mar 14 23:11 ./mnt/wsl/docker-desktop-data/tarcache/entries/docker.tar/a240ec231e698cacc75453b5ceea32f823132781122aba668b6376b4d23b0ad3/containers/services/docker/rootfs/run/xtables.lock

Does native linux xtable file in the container have the same permission? Any advice?

**Comment by howardjohn** [comment]
AFAIK `nf_conntrack` is only used for the `-j CT --zone` part. For the `Permission denied` you may just need `sudo`

**Comment by howardjohn** [comment]
iptables version should not be relevant, I think this is due to the kernel modules not being applied. I am a bit confused why the kernel is `/lib/modules/5.10.60.1-microsoft-standard-WSL2` - I thought docker desktop was running a real Linux VM (like on OSX)? is it using the WSL2 VM?

**Comment by c0ffeec0der** [comment]
I think so that docker desktop use WSL2 VM. However using hypervisor VM as in [11778](https://discuss.istio.io/t/istio-dns-proxying-cause-iptable-error/11778) doesn't work either ..; but I can't test this in my system as i need to change a lot of settings to use hypervisor VM

So the conclusion is that it won't work in WSL2 due to kernel issue; unknown in Hypervisor. It'll work on native linux kernel..

**Comment by c0ffeec0der** [comment]
@howardjohn I was able to create custom kernel for WSL2, initially I thought enabling CONFIG_NF_CONNTRACK_ZONES would make running 

`iptables -t raw -A OUTPUT -p udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1`

error free. However, I am still getting the same error..

Would you know which kernel config to switch on so that this command works?

**Comment by c0ffeec0der** [comment]
I think I got it working..

Kernel config

```
CONFIG_NF_CONNTRACK_ZONES=y
CONFIG_NETFILTER_XT_TARGET_CT=y
```

Add below for labeling

`CONFIG_LOCALVERSION="-k8s-optimized-WSL2"`

IstioOperator

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  values:
    global:
      proxy:
        privileged: true
```

Closing this. Many Thanks @howardjohn !

**Comment by howardjohn** [comment]
Nice! Do you still need `privileged`?

**Comment by c0ffeec0der** [comment]
Hi @howardjohn, I am not experimenting around istio at the moment. But, yes. If remember correctly, it won't work without 'privileged'.

`  values:
    global:
      proxy:
        privileged: true`

**Comment by thesuperzapper** [comment]
For anyone coming across this, please show your support on the issue to enable `CONFIG_NF_CONNTRACK_ZONES` and `CONFIG_NETFILTER_XT_TARGET_CT` in the WSL Kernel by default:
- https://github.com/microsoft/WSL/issues/8153

**Comment by davidshen84** [comment]
I gave up a long time ago. I just build my own wsl kernels now. It is very
easy.
