### ISSUE TITLE
Need info on one rule added to iptable

### ISSUE THREAD

**Issue by vorishirne** [istio/istio#37890]
```
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
```

So far I can translate this rule, it says 
If destination is in some loopback interface, but not localhost, owner is envoy, then treat the rule as Inbound traffic, not output traffic.

**Comment by howardjohn** [comment]
Consider: Pod x-pod-1 and x-pod-2 with Service x selecting them

In `x-pod-1`, I call `curl x`. 

These rules ensure this request goes out the outbound path, then in the inbound path when we send to `x-pod-1` (ourself). This ensures policy application is consistent when we call ourself and other pods in the same service

**Comment by vorishirne** [comment]
Amazing, thanks. Just one small thing.
What would be the destination in that case, if not ! -d 127.0.0.1/32

**Comment by vorishirne** [comment]
@howardjohn pls give the info. I am on my roadmap to be a contributor in istio on the istio-agent side.

**Comment by vorishirne** [comment]
@howardjohn The wikis here are outdated, I want to update them, need your permission for that being accepted and your help in above question.
https://github.com/istio/istio/wiki/Proxy-Redirection 
https://github.com/istio/istio/wiki/Control-and-Data-flow-through-Envoy

**Comment by zirain** [comment]
> @howardjohn The wikis here are outdated, I want to update them, need your permission for that being accepted and your help in above question. https://github.com/istio/istio/wiki/Proxy-Redirection https://github.com/istio/istio/wiki/Control-and-Data-flow-through-Envoy

would be better add a doc on istio.io?
