### ISSUE TITLE
Istio not giving metrics like istio_requests_total, istio_request_duration_milliseconds

### ISSUE THREAD

**Issue by doverk96** [istio/istio#37911]
Hey,
Have deployed a httpbin and sleep application, manually injected sidecar in httpbin, but am not getting standard metrics like istio_request_duration_milliseconds or any other istio_* metrics.
Any thing that can get me these metrics?

**Comment by zirain** [comment]
- do you send any request from `sleep` to `http`?
- is there any `stats-*` envoyfilter in your `rootNamespace`?

**Comment by doverk96** [comment]
Yes, Using this command
`kubectl exec deploy/sleep -- curl localhost:8000/headers`
and it gives me response with display headers.
Filters are present in istio-system namespace

**Comment by zirain** [comment]
I'm not sure why you do this, looks like you send any request throught `istio-proxy`.
you can following this [demo](https://istio.io/latest/docs/examples/bookinfo/), and verify is everything ok?
