### ISSUE TITLE
[multi-cluster] istiod doesn't refresh kubeconfig from istio-remote-secret-XXX properly

### ISSUE THREAD

**Issue by apolovov** [istio/istio#37925]
### Bug Description

* The kubeconfig uses Bearer token, which I refresh with my custom controller.
* When the token is fresh — everything is fine.
* When I preventively issue the new token — everything is fine, but I see the old token in logs from remote cluster.
* When the old token expires — I see the "the server has asked for the client to provide credentials" errors from istiod and 401 errors on a remote cluster. But there are also success logs with fresh token. And the istiod control-plane works fine.
* Ater restarting the istiod pod, everything comes back to normal.

### Version

```prose
# istioctl version
client version: 1.11.2
control plane version: 1.10.1
data plane version: 1.10.1 (5 proxies)

# kubectl version --short
Client Version: v1.21.9
Server Version: v1.21.9
```

**Comment by hzxuzhonghu** [comment]
I remember talked about this with @irisdingbj . could not remember have we fixed it or not

**Comment by irisdingbj** [comment]
Yes, https://docs.google.com/document/d/1gzO8H4vkwsxzBnzE3NRAc6o4Kk_FC3lqYwpw8wEC6r8/edit#heading=h.xw1gqgyqs5b is a reference for this issue but no implementaion as far as I know

**Comment by zirain** [comment]
> Yes, https://docs.google.com/document/d/1gzO8H4vkwsxzBnzE3NRAc6o4Kk_FC3lqYwpw8wEC6r8/edit#heading=h.xw1gqgyqs5b is a reference for this issue but no implementaion as far as I know

can you make this doc public?

**Comment by apolovov** [comment]
Does [this PR](https://github.com/istio/istio/pull/39367) fixes the problem?
