### ISSUE TITLE
mention log_output_level flag in istioctl help

### ISSUE THREAD

**Issue by rittneje** [istio/istio#37938]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

istioctl supports a `--log_output_level` flag to control the logging level of its various components. This flag is very useful for troubleshooting when istioctl is misbehaving. However, it is not documented in `istioctl -h` or `istioctl help`.

**Describe alternatives you've considered**

n/a

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Does `--log_output_level=all:debug` not work? They SetOutputLevel overrides those?

**Comment by rittneje** [comment]
We can try that. However, that flag is not mentioned in the output from `istioctl help`.

**Comment by litong01** [comment]
@howardjohn @rittneje the --log_output_level=all:debug does work, it will make `istioctl` show a lot of information.

**Comment by rittneje** [comment]
Yes we were able to use it successfully. For this reason I've changed the request to instead document this flag.

**Comment by hanxiaop** [comment]
@rittneje The flag is not shown because it prints several lines with many scopes. See https://github.com/istio/istio/issues/22061. There's a command `istioctl options` that can see all of these global flags. I think the point may become that users are not awaring of using this command. Maybe adding a more detailed command could be better?

**Comment by rittneje** [comment]
@hanxiaop Personally, I don't understand why `istioctl help` arbitrarily prints some of the global flags (e.g., `--context`), and `istioctl options` prints the rest of them. Fundamentally, the documentation ought to be internally consistent, and put them all in a singular location.

In addition to that, `istioctl help` should definitely explicitly refer to `istiotctl options`. That is a fairly non-standard way to document flags (other than `kubectl` I don't know of any application that does that), so as it stands it is extremely unlikely that most developers will ever see that documentation. Also, to be frank, I don't understand what the motivation is for not simply including _all_ flags under `istioctl help`, regardless of whether they are global.

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/38236.
