### ISSUE TITLE
Istio not generating standard prometheus metrics

### ISSUE THREAD

**Issue by doverk96** [istio/istio#37934]
Hi, 
I have httpbin and sleep services, printing access logs to stdout but am not Able to get any standard metrics starting with istio_requests_* on checking localhost:15000/stats/prometheus inside Istio-proxy container of httpbin pod.
@zirain Hope here we can continue.
Also, stats filter is present in config_dump

**Comment by doverk96** [comment]
How can I check which filter out of 
```
stats-filter-1.10
stats-filter-1.13
stats-filter-1.9
``` 
is being used for my sidecars ?
As am able to see access logs on sidecar, but no standard metrics.

**Comment by douglas-reid** [comment]
Do you have a 1.13 sidecar ?  IIRC, you were building/installing from `master`, which will give you 1.14.X sidecars. There shouldn't be much difference between the filters, so you can copy and paste and update the version regex in the filter themselves.

Alternatively, you can delete all of the EnvoyFilters and make sure that `MeshConfig.defaultProviders.metrics` includes `prometheus`.

**Comment by doverk96** [comment]
Thank you very much @douglas-reid  @zirain , Metrics are now coming, stats filter version was missing.
Thanks for handling my annoying messages here.

**Comment by zirain** [comment]
> Do you have a 1.13 sidecar ? IIRC, you were building/installing from `master`, which will give you 1.14.X sidecars. There shouldn't be much difference between the filters, so you can copy and paste and update the version regex in the filter themselves.
> 
> Alternatively, you can delete all of the EnvoyFilters and make sure that `MeshConfig.defaultProviders.metrics` includes `prometheus`.

maybe it's time to move to code, just like the `mx` filter

**Comment by doverk96** [comment]
@zirain Can you help to find out if there is any such setting/label through which we can enable automatic sidecar injection for a particular deployment inspite of enabling it at namespace level.
Am aware that manually it can be done using istioctl Kube-inject deployment.yaml but it will be a challenge do it for all existing and upcoming deployments.

**Comment by harsh4870** [comment]
@doverk96  could you please share your **istio** configmap for ref ? 

i tried same: `MeshConfig.defaultProviders.metrics `and deleted filters but the ingress and egress pod started crashing due to configmap issue.

**Comment by danhngo-lx** [comment]
> Thank you very much @douglas-reid @zirain , Metrics are now coming, stats filter version was missing.
Hi @doverk96, can you tell what did you do to fix stats filter version missing?
