### ISSUE TITLE
server-side apply detection logic does not work for upgraded clusters

### ISSUE THREAD

**Issue by rittneje** [istio/istio#37946]
### Bug Description

The server-side apply detection logic for istioctl only works for newly created 1.18 clusters. It doesn't work for clusters that were upgraded.

https://github.com/istio/istio/blob/dac4c97a792a6fc362165b6385429413d90793f1/operator/pkg/helmreconciler/reconciler.go#L251-L258

Our server does support server-side apply. But because the kube-system namespace was created under an older cluster version, it does not have the `managedFields` field.

This is partially the cause of #37912, due to an inconsistency between client- and server-side apply I filed here: https://github.com/kubernetes/kubernetes/issues/108708

### Version

```prose
$ istioctl version
client version: 1.11.6
control plane version: 1.11.6
data plane version: 1.11.6 (129 proxies)

$ kubectl version --short
Client Version: v1.20.15
Server Version: v1.20.11-eks-f17b81
```

**Comment by howardjohn** [comment]
Tricky! Wonder what a better option is
@richardwxn ?

**Comment by rittneje** [comment]
Another option is to only use SSA (unconditionally?) for 1.22+, since this is when it became generally available, especially because 1.20 has the bug I mentioned.

**Comment by rittneje** [comment]
@howardjohn Please remove the stale label.

**Comment by howardjohn** [comment]
I would just add `if > 22 { return true }` with a comment about why, to https://github.com/istio/istio/blob/71ea0bdf1cfc5e9d9918094368525dbedee453fc/operator/pkg/helmreconciler/reconciler.go#L247.

**Comment by Pawan-Bishnoi** [comment]
I can pick this.

**Comment by zirain** [comment]
@Pawan-Bishnoi  assign to you.
