### ISSUE TITLE
Can istio-proxy add optional secret reference in Headers.HeaderOperations

### ISSUE THREAD

**Issue by jimlindeman** [istio/istio#37983]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently the Headers.HeaderOperations definition in https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations only allows one to set or add static 'visible' header values with the "set" and "add" keywords.  I'd like to have an optional "addSecret" and "setSecret" keywords where we reference a secret value instead of providing the value of the header.  This is for the use-case where we want to ensure outgoing traffic to a specific external URL has a header identifying the caller is from this specific Istio namespace and not have to expose the secret value in the virtual-service definition.

**Describe alternatives you've considered**
For now, we're stuck with having to put the secret value in the virtual service definition, which isn't as protected in our RBAC as secrets are.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
So we would read it from a Kubernetes Secret?

Would there be concerns if this was visible in plaintext in the envoy configuration?

**Comment by jimlindeman** [comment]
Right, idea is to read the value from a kubernetes secret.  If the secret was visible in plaintext from envoy configuration isn't ideal, but its still better than what we have now since we use flux to copy in our Istio configuration files from a github repository.  So in that repo we'd have to go through crazy hoops like https://fluxcd.io/docs/guides/sealed-secrets/ to avoid having it plaintext in the repo and we're not even sure that will work to write to non-secret type resources.

**Comment by jimlindeman** [comment]
Other dev-ops developers just pointed out to me that we could also benefit from having configmap references supported for the header values too.  Certain header values need to be communicated to multiple apps and configmaps entries are good for "store once, use multiple places" settings.

**Comment by jimlindeman** [comment]
Yes, we're already using helm template to generate our Istio resources, we just currently don't have a clean way to sync the setting between our consumer/producer apps as they're managed by separate git-ops repos (our own refactoring required but doable). 

Regarding gateway-api.org... is that just for virtual-service-gateway type replacement or would that also apply to egress flows?  The doc examples so far seem to only describe ingress flow use-cases.

**Comment by howardjohn** [comment]
It's mostly focused on Ingress but only because that has been the first
priority - it does support egress use cases and in the future will be made
more prominent

**Comment by jimlindeman** [comment]
Okay, for now we'll just track this in  http://gateway-api.org/ if it will have requirements for secret fetching (and its own obfuscation for secret-fetched values).
