### ISSUE TITLE
Creating duplicate service entry with same hostname and address consequences

### ISSUE THREAD

**Issue by kanurag94** [istio/istio#37981]
### Bug Description

Istio allows duplicate configuration service entries to be created.
For eg. I have a host `www.google.com` and IP `10.0.0.0` and I create two service entries for the same called `se-1` and `se-2`. This is valid and everything works. However, when I delete `se-2`, and try to curl the service, I get `UH: envoy upstream	no healthy host for HTTP connection pool`.

From `istioctl proxy-status`, `istioctl pc listeners pod_name` and dns resolution from pod everything is in sync. To make `se-1` fully functional again, I have to make some updates to it. Say I add an annotation `abc: xyz` and voila communication works.

The resolution can be to not allowing duplicate service entry or to fix this flow itself.

### Version

```prose
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (56 proxies)
Client Version: v1.21.3
Server Version: v1.20.7
```

**Comment by hzxuzhonghu** [comment]
Are the two se in same namespace?

**Comment by kanurag94** [comment]
@hzxuzhonghu Yes, both are in same namespace.

**Comment by hzxuzhonghu** [comment]
@kanurag94 can you please test with  #37994

**Comment by kanurag94** [comment]
@hzxuzhonghu Thanks for picking this up so fast. I will update after testing

**Comment by kanurag94** [comment]
Tested, this fixes the issue.Thanks @hzxuzhonghu
