### ISSUE TITLE
sni missing in ssl_context for egress envoy conf

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3799]
https://github.com/envoyproxy/envoy/issues/2670#issuecomment-368723660

that would explain some issue with reaching some https services

**Comment by ldemailly** [comment]
@aaronjwood can you check the setup you get from pilot with your egress?

**Comment by ldemailly** [comment]
well it's not set:
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/testdata/cds-ssl-context.json.golden#L101

**Comment by ldemailly** [comment]
issue is what to do for wildcard

**Comment by vadimeisenbergibm** [comment]
@ldemailly 
> issue is what to do for wildcard, but we can at least solve the plain case
I would consider solving the issue for the common case. If some feature will work without wildcard, but will fail with wildcard, it will create unnecessary confusion.

**Comment by vadimeisenbergibm** [comment]
@aaronjwood Istio Egress was working for HTTP/HTTPS starting from Istio 2.0.

**Comment by aaronjwood** [comment]
@vadimeisenbergibm thanks. Due to the empty ssl context what I'm trying to do should still break in the latest version then, right?

**Comment by ldemailly** [comment]
if your target server requires sni to be set yes it will fail until we fix it

> If some feature will work without wildcard, but will fail with wildcard, it will create unnecessary confusion.

@vadimeisenbergibm I disagree - it's better to have 1 imperfect solution than 0 solution, ie confusion or faq/limitation is better than "does not work at all" when there is an easy solution for all non wildcard egress
(and yes I think envoy should do the automatic support I suggested too but that will take longer)

**Comment by vadimeisenbergibm** [comment]
@ZackButcher @ldemailly We should check where to fix this. Egress Rules will be replaced by External Services cc @ijsnellf .

**Comment by ldemailly** [comment]
@vadimeisenbergibm do you think you can make the quick workaround soonish -  for 0.7 ?

**Comment by vadimeisenbergibm** [comment]
@ldemailly what is the planned date for 0.7?

**Comment by costinm** [comment]
How about check if it works with external service, and fix it there ?
We plan to deprecate alpha1 around 0.8.

**Comment by ldemailly** [comment]
March 14 freeze

**Comment by vadimeisenbergibm** [comment]
@ijsnellf (cc @costinm @ldemailly ) could you please consider to fix this issue for External Services?

**Comment by andraxylia** [comment]
Need to check this with the egress Gateway.

**Comment by rshriram** [comment]
fixed a while ago.
