### ISSUE TITLE
istio-1.10.4 -->  "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: no such host

### ISSUE THREAD

**Issue by zohebs341** [istio/istio#38004]
### Bug Description

We are using Azure AKS 1.21.7 for prod workloads.

We have istio-proxy sidecar for all prod pods. We are getting the below error in our application pod. CoreDNS, Application pods, istio-system pods all are up and running. But still why we are getting DNS-related errors.

Error from actual/app pod: Error connecting to node my-release-kafka-2.my-release-kafka-headless.kafka:9092 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: my-release-kafka-2.my-release-kafka-headless.kafka

Error from istio-proxy for the same pod:

warning envoy config StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: no such host

### Version

```prose
istio version - 1.10.4

Azure AKS - 1.21.7
```

**Comment by howardjohn** [comment]
Does your pod configure the `dnsPolicy` field perhaps?

**Comment by zohebs341** [comment]
@howardjohn Thanks for your response.

Yes in pod configuration, I can see "dnsPolicy: ClusterFirst". 

I just restarted the application pod and it's working fine without connectivity errors. Is istio-proxy using cache DNS entries?

I've verified CoreDNS pod, it is working and able to resolve hosts. But I suspect, istio-proxy is using cached DNS entries and trying to resolve with old pod entries.

**Comment by howardjohn** [comment]
Istio doesn't do anything particular with DNS, so any issues in this regard are likely lower level Kubernetes platform issues

**Comment by zohebs341** [comment]
Restarting application pod worked. Will check with Microsoft as well on this. Like why after restarting pod, it worked. We haven’t done any changes to coredns pod. We are using 1.10.4 istio version.

In istio docs, they are talking about DNS:

Starting with Istio 1.8, the Istio agent on the sidecar will ship with a caching DNS proxy, programmed dynamically by Istiod. Istiod pushes the hostname-to-IP-address mappings for all the services that the application may access based on the Kubernetes services and service entries in the cluster. DNS lookup queries from the application are transparently intercepted and served by the Istio agent in the pod or VM. If the query is for a service within the mesh, irrespective of the cluster that the service is in, the agent responds directly to the application. If not, it forwards the query to the upstream name servers defined in /etc/resolv.conf.

**Comment by howardjohn** [comment]
That is not enabled by default and doesn't impact DNS requests from the
istio-proxy (only from the user app)

**Comment by zohebs341** [comment]
@howardjohn Thanks for sharing details and insights on this.
