### ISSUE TITLE
VM tests: refactor which OS's we tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38009]
Currently:

- ubuntu_xenial
- ubuntu_bionic
- ubuntu_focal
- debian_9
- debian_10
- centos_8
- centos_7

problem: we do not have full coverage of new versions, but adding a bunch of new ones will bloat things
proposal: carefully craft the set we use to maximise coverage will reducing tests

Proposal:

- ubuntu_xenial # test oldest ubuntu, ensure old GLIBC works
- ubuntu_jammy # test latest ubuntu
- debian_11 # test one debian, xenial covers older ones
- centos_8_stream # test latest centos
- centos_7 # test old centos (old GLIBC)

This drops us from 7 -> 5 cases while expanding the coverage (IMO - a bit subjective)

**Comment by howardjohn** [comment]
@ericvn @stevenctl any concern?

**Comment by mayyyyying** [comment]
> 

Hi Howard,

Do we have any plan to use the ubuntu jammy instead of focal as the base image, because there are bunch of VUL in focal, or did we already tested the latest ubuntu jammy can be safely upgraded from focal? any concern about this upgrading?
