### ISSUE TITLE
Log shows PassthroughCluster but there is a service entry for it

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#38018]
### Bug Description

I have the following service entry:
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kafka
  namespace: istio-system
spec:
  hosts:
  - kafka
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 9092
    protocol: TCP
  resolution: NONE

but when I look at the -c istio-proxy logs I still connections that are going to port 9092 getting sent to "upstream_cluster":"PassthroughCluster"

The concern is that when I change the outbound traffic policy to REGISTRY_ONLY that these connections will start failing.

### Version

```prose
istioctl version
client version: 1.12.1
control plane version: 1.12.4
data plane version: 1.12.4 (14 proxies)

% kubectl version --short
Client Version: v1.22.5
Server Version: v1.20.11-eks-f17b81
```

**Comment by hzxuzhonghu** [comment]
It is expected, as the resolution is NONE.

**Comment by nielsole** [comment]
I ran into this today. It seems DestinationRules do not apply when `resolution: NONE`. This is rather unfortunate because my expectation was that all it would do is set Originaldst on the cluster, not remove the cluster altogether.
