### ISSUE TITLE
The helm chart got some breaking changes and unconventional

### ISSUE THREAD

**Issue by longkai** [istio/istio#38016]
### Bug Description

The official helm chart break into three charts, base, istiod and gateway and it's fine since it's more modular.

However, the [doc](https://istio.io/latest/docs/setup/install/helm/) says we must install one at a time. Sometimes most people want a single install operation, but it's still fine.

The biggest problem is that the gateway installation:

- install on the `istio-ingress` namespace, this usually in the `istio-system` and many doc still reference that ns.
- the release name is `istio-ingress` and it turns out the final `metadata.name` is ingress, thus in the gateway the use must ref the selector as `istio: ingress` which is different in many samples like [bookinfo](https://github.com/istio/istio/blob/master/samples/bookinfo/networking/certmanager-gateway.yaml#L8) which is the classic `istio: ingressgateway`. It's confuse for a beginner.
- in my case, I compose the three as helm dependencies and install on same namespace. However the gateway install always fail since the [hardcode auto image](https://github.com/istio/istio/blob/0fb9e6f274272cc77d0d5a49d6ed1ff10edc7b20/manifests/charts/gateway/templates/deployment.yaml#L46). Since the gateway must install after istiod is ready. I have to delete gateway deployment than upgrade helm release. Can the image as helm Values with default `auto` value? By the way, the default value contains `sidecar.istio.io/inject: "true"` indicate we don't need to label the ns auto-injected.
- lastly, some `metadata.name` like gateway not respect the helm common standard.

So, I am not sure I point out the problems clearly. The helm chart instillation is more welcome in deployment k8s apps. In fact, I found the istio operator using helm rendering manifest to do its job. How should we make the istio chart more accessible and conventional?

I would happy send a PR.

### Version

```prose
helm version: v3.8.0+gd141386
chart version: 1.13.2
```

**Comment by howardjohn** [comment]
I'm not sure why it's a concern that the namespace and name and label are expected to be the same indefinitely. Do you expect that Kubernetes apps all are installed in the default namespace, are named "test" and have "app: test", so that docs on kubernetes.io match? Of course not. It's expected that Kubernetes users understand how resource names, namespaces, and label selectors work and how they interact.

The bookinfo sample is just that - a sample. It cannot be expected to work with every gateway install because gateways can have whatever labels a user needs. Similarly, when kubernetes.io gives sample Services on their docs, it cannot be expected that the service will work with your app out of the box without modifying

**Comment by howardjohn** [comment]
> lastly, some metadata.name like gateway not respect the helm common standard

can you elaborate?

**Comment by longkai** [comment]
like [this one](https://github.com/istio/istio/blob/0fb9e6f274272cc77d0d5a49d6ed1ff10edc7b20/manifests/charts/gateway/templates/_helpers.tpl#L2), the release name equals to `RELEASE-NAME` which is too implicit. The helm `metadata.name` usually comes with a full name idea, like [bitnami](https://github.com/bitnami/charts/blob/d2104f1420f411677bb7d40732263986c478e387/bitnami/common/templates/_names.tpl#L21) does.

Since we are NOT NEW to istio, this breaking change is fine. I learn from the booking sample and still takes me a while to figure out why the helm installation not work. Maybe is not friendly but that's perfectly fine if the user didn't use helm.

The **most important** thing for this chart is don't [hardcode the auto image](https://github.com/istio/istio/blob/0fb9e6f274272cc77d0d5a49d6ed1ff10edc7b20/manifests/charts/gateway/templates/deployment.yaml#L46) if the user install the two components in the same namespace.

> in my case, I compose the three as helm dependencies and install on same namespace. However the gateway install always fail since the [hardcode auto image](https://github.com/istio/istio/blob/0fb9e6f274272cc77d0d5a49d6ed1ff10edc7b20/manifests/charts/gateway/templates/deployment.yaml#L46). Since the gateway must install after istiod is ready. I have to delete gateway deployment than upgrade helm release. Can the image as helm Values with default auto value? By the way, the default value contains sidecar.istio.io/inject: "true" indicate we don't need to label the ns auto-injected.
