### ISSUE TITLE
No Trace Service And No Prometheus Service Data like "istio_request_*" when I deploy istio by Helm

### ISSUE THREAD

**Issue by liaozhenlin** [istio/istio#38017]
### Bug Description

Hello,everyone! I am in trouble ! Although I researched for two weeks but  I can not solve it.

Description:
The question is  that I can not seen any service build by istio data When I explore Jaeger UI .
And also I can not found metrics like "istio_request_*" in prometheus.  

Install Step :
   1. kubectl create namespace cloudos-mesh
   2. helm install istio-base -n cloudos-mesh mainfests/charts/base
   3. helm install istiod -n cloudos-mesh mainfests/charts/istio-control/istio-discpvery
   4. I deploy jaeger with yaml（in file : samples/addons/jaeger.yaml） 
  
The first Problem:
when I dump the envoy config by "kubectl exec -itn {namespace} {pod} -c istio-proxy  -- curl localhost:15000/config_dump"
I can see some config related to trace like:
 "tracing:" {
    "http":{
     "name":"envoy.tracers.zipkin",
     ****,
         "collector_cluster":"zipkin",
          "collector_endpoint":"api/v2/spans",
    ****
   } 
}

The Second Problem:
I can see  "stats-filter-1.13" and "tcp-stats-filter-1.13"" with resource envoy-filter . And proxyVersion is match 1.13.*

Last: 
I verified that the traffic management and security function are OK .
But when I test Simplify observability , there is "No Trace Service And No Prometheus Service Data like "istio_request_*" when I deploy istio by Helm".

When I seen log from istio-proxy container like，there is no special error .

How can I further determine it ?

### Version

```prose
istio version : 
https://github.com/istio/istio/releases/tag/1.13.2
https://github.com/istio/istio/releases/tag/1.13.0

my Artifacts:
https://gcsweb.istio.io/gcs/istio-release/releases/1.13.2/
https://gcsweb.istio.io/gcs/istio-release/releases/1.13.0/

[root@lightpaas001 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

[root@lightpaas001 ~]# nerdctl version
Client:
 Version:       v0.17.0
 Git commit:    9ec475aeb69209b9b2a3811aee0923e2eafd1644
Server:
 containerd:
  Version:      v1.6.0
  GitCommit:    39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e
```

### Additional Information

There has some bugfix related , but I can not found Solution。

about trace :
https://github.com/istio/istio/issues/32026
https://github.com/istio/istio/issues/32044
https://github.com/istio/istio/issues/31802

about envoy service Service-level metrics
https://github.com/istio/istio/issues/37911 and son on

**Comment by zirain** [comment]
can you share you config_dump?

**Comment by liaozhenlin** [comment]
Thanks for reply. Because of some security considerations，we work in remote desktop .So  it is difficult to copy my config_dump file to local computer system . And In the remote desktop we can not browse the Internet . 

Can you ask me how to find out if there is a problem with the configuration？mabey some help document about envoy configration.

**Comment by zirain** [comment]
check  `istio.stats` filter exists by running this cmd  `istioctl pc l -oyaml <your_pod_name>  | grep "istio.stats"`

**Comment by liaozhenlin** [comment]
I can not use istioctl  cmd . Because I installed Istio via Helm v3 .
Follow your advice， I dumped the config by cmd "kubectl exec -itn {namespace} {pod} -c istio-proxy -- curl localhost:15000/config_dump" .
And I can not found any words like "istio.stats".  Mabey there is something wrong with it ?

**Comment by liaozhenlin** [comment]
Hi,my good friend zirain.
Now I did an test, I create the crd with named "envoyfilter" by cmd "kubectl create -f -n {myAppNamespaces} stats-filter-1.13"
Then I can seen istio_requests_total from the uri "ip:15020/stats/prometheus".
I will studied it In-depth. But Why we need create “stats-filter-1.13‘’ every namespace .

**Comment by zirain** [comment]
> helm install istiod -n cloudos-mesh mainfests/charts/istio-control/istio-discpvery
why did you install istiod in `cloudos-mesh` namespace? did you the rootNamespaces?

**Comment by liaozhenlin** [comment]
I solved this problem “No Prometheus Service Data like "istio_request_*"”  by set the rootNamespace with value "cloudos-mesh".
It is my mistake that  I didn't change the meshConfig  when I chance the rootNamespace to "cloudos-mesh". （the default value rootNamespace is empty in helm value,so I ignore it）

**Comment by liaozhenlin** [comment]
But I still not sure how to make the jaeger work fine. Can you  give me some suggestions ?

**Comment by zirain** [comment]
> But I still not sure how to make the jaeger work fine. Can you give me some suggestions ?

1. make your install jeager correctly, [here](https://github.com/istio/istio/blob/master/samples/addons/jaeger.yaml) is the sample yaml
2. check your tracing setting
3. check the connection between you sidecar and jeager pod, you can change the log level of envoy by `istioctl log`

**Comment by liaozhenlin** [comment]
Hi,zirain.
I did some research on envoy and jaeger .Now I found something strange.
I can seen the static_resources and tracing configration like bellows:

tracing:
  http:
    name: envoy.traces.zipkin
    typed_config:
      collector_cluster: zipkin
      collector_endpoint: "/api/v2/spans"
...

static_resources:
...
  clusters:
  - name: zipkin
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: zipkin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address: { socket_address: { address: zipkin.cloudos-mesh.svc, port_value: 9411 } }

But I can not found any listen filters about tracing ,Is this a problem? 
I have no method to set the listen filters.

**Comment by zirain** [comment]
you can run `istioctl pc l <your_pod_name> --port <the_port> -oyaml | grep tracing -A 20 ` to check is the tracing config on listener is normal or not.

**Comment by liaozhenlin** [comment]
I can not seen any listener about tracing.There are only two listeners ,usage for stat/prometheus and /health/ready .
What can I do next ? Mabey I define a envoyfilter for jaeger ?

**Comment by zirain** [comment]
seems you did not install istio correctly, please checkout this [doc](https://istio.io/latest/docs/setup/install/helm/)

**Comment by liaozhenlin** [comment]
I do not know why . My Istio works fine except jaeger. 
I can seen every metrics with kiali board except jaeger. Also, The function of Traffic Management And Security looks available.
And I checked every step when install istio with Helm.
There may be a configuration problem somewhere,but I don't know exactly where the problem It .

**Comment by liaozhenlin** [comment]
I do some test like bellow,but there is still no trace service with jaeger UI. Through I can seen Provider when I dump my config_dump.
meshConfig:
  extensionProviders:
  - name: "traces-tempo-zipkin"
    zipkin:
      service: "tempo-tempo-distributed-distributor.tempo.svc.cluster.local"
      port: 9411
  defaultProviders:
    tracing:
    - traces-tempo-zipkin

**Comment by liaozhenlin** [comment]
Thanks for you help.
I Solved this problem with telemetry api.
But I still don't know weather Is it necessary to use telemetry api.

**Comment by zirain** [comment]
so you jaeger is deploy with service `zipkin.cloudos-mesh.svc.cluster.local`
if you do not change the configmap(named `istio`), the default value of `zipkin.istio-system`, that maybe the root cause.

**Comment by zirain** [comment]
you can try configs as following:
https://github.com/istio/istio/blob/5496a6e710a8e10419df203e4d5985ec1ef13c5a/manifests/charts/istio-control/istio-discovery/templates/configmap.yaml#L23

**Comment by liaozhenlin** [comment]
This value is set correctly.
I will close this question now , due to lack of sufficient information.
If anyone has the same problem,I will reopen this issue.
