### ISSUE TITLE
istioctl install error, report configmap "istio-ca-root-cert" not found

### ISSUE THREAD

**Issue by dale1202** [istio/istio#38022]
### Bug Description

i command: ./bin/istioctl install --set profile=demo -y.  to install istio, but failed.
the info is : Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition

**i look at the kubelet log:** 
Couldn't get configMap istio-system/istio-ca-root-cert: configmap "istio-ca-root-cert" not found

### Version

```prose
istioctl version: 1.13.0
kubectl version: v1.23.5
kube-server version: v1.23.5
```

**Comment by howardjohn** [comment]
you should look at the Istiod pod logs

**Comment by dale1202** [comment]
@howardjohn thank you，from looking at the log，i found the connection to svc is time out,  i fix it by change the svc configure。
