### ISSUE TITLE
Requests to headless service do not reach all clusters

### ISSUE THREAD

**Issue by nmittler** [istio/istio#38023]
### Bug Description

This was discovered while working on https://github.com/istio/istio/pull/37914 (logs are [here](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37914/integ-security-multicluster_istio/1505217295117455360)). 

The new authz test fails to reach headless service workloads in all clusters. When sent from `primary` and `remote` clusters, all requests seem to stay within the origin cluster. However when sent from the `cross-network-primary`, all clusters appear to be reached properly (test passes).

### Version

```prose
head
```

**Comment by nmittler** [comment]
@stevenctl @howardjohn is this a known issue? Any thoughts?

**Comment by stevenctl** [comment]
Headless should be okay. I wouldn't actually expect multi network at all.

Also with authz, I don't think the callers original identity is propagated. The request will take on the gatways identity (I think)

**Comment by howardjohn** [comment]
For multi network the original identity is used, it doesn't terminate TLS.

How does headless work? We have DNS proxy enabled?

**Comment by nmittler** [comment]
> How does headless work? We have DNS proxy enabled?

DNS capture is enabled by default in the tests. I've confirmed in the [test logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/37914/integ-security-multicluster_istio/1505217295117455360/artifacts/security-authz-78fc99308c494617/TestAuthz_Principal/_test_context/istio-state1917001027/primary/istiod-675c8c5bf-rc4hx_discovery.log)

> For multi network the original identity is used, it doesn't terminate TLS.

Right, that explains why multi-network works ... but why single network doesn't is still a mystery.
