### ISSUE TITLE
uninject should remove labels

### ISSUE THREAD

**Issue by j2gg0s** [istio/istio#38026]
### Bug Description

kube-inject add label `security.istio.io/tlsMode` and kube-uninject did not remove it.
So, after uninject, pod with sidecar communicate with pod wihout sidecar by tls.

### Version

```prose
client version: 1.13.2
control plane version: 1.13.2
```

### Additional Information

$ k get -n istio-example deployments/details-v1 -o json | jq '.spec.template.metadata.labels'
{
  "app": "details",
  "version": "v1"
}
$ k get -n istio-example deployments/details-v1 -o yaml | istioctl kube-inject -f - | istioctl x kube-uninject -f - | grep tlsMode
        security.istio.io/tlsMode: istio

**Comment by xichengliudui** [comment]
I can try to fix it
