### ISSUE TITLE
Remove k8s certificates.k8s.io/v1beta1 since k8s has support certificates.k8s.io/v1 from v1.19

### ISSUE THREAD

**Issue by Chen-Xintong** [istio/istio#38025]
**Describe the feature request**

I found that Kubernetes has supported certificates.k8s.io/v1 from v1.19 version and The certificates.k8s.io/v1beta1 API version of CertificateSigningRequest is no longer served as of v1.22. And all existing persisted objects are accessible via the new API, links [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/). So the old version of v1beta1 seems to be no longer needed, because even if there is a k8s certificate object for v1beta1, it can still be accessed by v1's API.

**Describe alternatives you've considered**

Found that only chiron use both v1 and v1beta1 API. And [33983](https://github.com/istio/istio/pull/33983) has already incorporated v1, so just need to remove all v1beta1 related codes.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
We still support older Kubernetes so we need both versions until we drop 1.19 support

**Comment by Chen-Xintong** [comment]
> We still support older Kubernetes so we need both versions until we drop 1.19 support

Okay, got it.
