### ISSUE TITLE
A pod restart will trigger a repeat execution of init-container, which may fail.

### ISSUE THREAD

**Issue by believening** [istio/istio#38036]
> I realize what @rshriram pasted is not the first crash.
> 
> The latter crash would have another error due to iptables-restore is recreating a chain using `-N ISTIO_REDIRECT`
> 
> ```
> iptables-restore --noflush /tmp/iptables-rules-1576593759910205399.txt865603595
> iptables-restore: line 2 failed
> ```
> 
> head 2 lines
> 
> ```
> line1: * nat
> line2: -N ISTIO_REDIRECT
> ```

In some edge scenarios, [a pod restart will cause init-container to execute repeatedly](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior), when a custom chain including ISTIO_REDIRECT already exists and init-container will fail because we didn't clean up the previous rules.

How we handle these scenarios? thx

_Originally posted by @believening in https://github.com/istio/istio/issues/19380#issuecomment-1072234350_

**Comment by howardjohn** [comment]
when a pod restarts its in a new environment, istio-init runs fine. The only known cases I have seen this issue occur is if you do `docker rm image istio-init` or similar on the node.

**Comment by believening** [comment]
> when a pod restarts its in a new environment, istio-init runs fine. The only known cases I have seen this issue occur is if you do `docker rm image istio-init` or similar on the node.

In the scenario I encountered, both the business container and sidecar container may have stopped and for sure the init container was gc'd, which caused the pod to restart and the init container to re-execute. Maybe I should first troubleshoot why the business container and sidecar container quit.

Thanks a lot, I will close this issue
