### ISSUE TITLE
undocumented breaking change when going from 1.11.5 to 1.12.x

### ISSUE THREAD

**Issue by jack-evans** [istio/istio#38044]
### Bug Description

My team utilise the istio-operator as our way of managing istio on our clusters. I recently upgraded from 1.11.5 to 1.12.x, for which we have the following instructions to generate the yaml to install the operator and its dependencies on our clusters:

```bash
helm3 template manifests/charts/istio-operator/ \
  --set hub=gcr.io/istio-release \
  --set tag=<version> \
  --set enableCRDTemplates=true \
  --set operatorNamespace=istio-operator \
  --set istioNamespace=istio-system \
  --set-string podAnnotations."sidecar\.istio\.io/inject"=false
```

I found that when I did this for Istio release at 1.12, the istio-operator namespace was no longer generated for you, it was expected that as the end user you would have to create it. While we are happy to do that, I couldn't find it in any of the release notes/changelog for 1.12, I also searched the release notes between the version we were running (1.11.5) to 1.12.5 and couldn't see any mention of the change which is to me quite clearly a breaking change. I can see the PR went in here https://github.com/istio/istio/pull/30741 and has a label `release-notes-none` which doesnt seem right.

### Version

```prose
N/A - as mentioned above the version was from 1.11.5 to 1.12.x
```

**Comment by js-timbirkett** [comment]
This is one of the reasons that putting namespaces in helm charts is a **REALLY REALLY** bad idea. There's only one thing that's worse than putting it into the chart in the first place... removing it later on! Applying the change which would delete the operator could potentially destroy all of the operator managed deployments such as Istio and any gateways causing lovely big outages for everyone... Great stuff.

The other issue with this change is that users that created the Helm release in one namespace, for example: `kube-system`,  and the operator in another with something like: `operatorNamespace: istio-operator` is that, with the changes in #30741 the istio-operator now wants to deploy to the Helm release namespace 🤦 - there's no way to override the behaviour... perhaps coalesce, or a small template function would have been useful here. 

Time and time again, Istio release these sorts of breaking changes with little thought to the end-user. It's like you assume that everyone is installing on a fresh cluster every time or that "just remove it and reinstall it" is a legitimate solution to every problem.
