### ISSUE TITLE
add default container annotation when there are multiple containers

### ISSUE THREAD

**Issue by fatedier** [istio/istio#38060]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
From injection template:

```
{{- if eq (len $containers) 1 }}
kubectl.kubernetes.io/default-logs-container: "{{ index $containers 0 }}",
kubectl.kubernetes.io/default-container: "{{ index $containers 0 }}",
{{ end }}
```

Now it only add default container annotation if ` len($containers)` is 1.

Pod with multiple containers won't add these annotations and istio-proxy will be the default container.

Can we also add default container annotations when `len($containters) > 1` if there are no user specified annotations?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Which one would you pick as the default container if there are multiple?

**Comment by fatedier** [comment]
From kubectl https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/exec/exec.go#L49

```
# Get output from running the 'date' command from pod mypod, using the first container by default
kubectl exec mypod -- date
```
It seems that kubectl will choose the first container. It's always istio-proxy container now.

**Comment by linsun** [comment]
Seems a reason req, feel free to submit a PR.

**Comment by howardjohn** [comment]
> It seems that kubectl will choose the first container. It's always istio-proxy container now.

Sure.. but if there are 2 other app containers, how do we know which one to make 'default'?

**Comment by fatedier** [comment]
@howardjohn We can use the logic from [kubectl](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go#L56)

```go
func FindOrDefaultContainerByName(pod *v1.Pod, name string, quiet bool, warn io.Writer) (*v1.Container, error) {
	var container *v1.Container

	if len(name) > 0 {
		container, _ = FindContainerByName(pod, name)
		if container == nil {
			return nil, fmt.Errorf("container %s not found in pod %s", name, pod.Name)
		}
		return container, nil
	}

	// this should never happen, but just in case
	if len(pod.Spec.Containers) == 0 {
		return nil, fmt.Errorf("pod %s/%s does not have any containers", pod.Namespace, pod.Name)
	}

	// read the default container the annotation as per
	// https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2227-kubectl-default-container
	if name := pod.Annotations[DefaultContainerAnnotationName]; len(name) > 0 {
		if container, _ = FindContainerByName(pod, name); container != nil {
			klog.V(4).Infof("Defaulting container name from annotation %s", container.Name)
			return container, nil
		}
		klog.V(4).Infof("Default container name from annotation %s was not found in the pod", name)
	}

	// pick the first container as per existing behavior
	container = &pod.Spec.Containers[0]
	if !quiet && (len(pod.Spec.Containers) > 1 || len(pod.Spec.InitContainers) > 0 || len(pod.Spec.EphemeralContainers) > 0) {
		fmt.Fprintf(warn, "Defaulted container %q out of: %s\n", container.Name, AllContainerNames(pod))
	}

	klog.V(4).Infof("Defaulting container name to %s", container.Name)
	return &pod.Spec.Containers[0], nil
}
```

1. If there are already default containter name annotation, do nothing.
2. If there are multiple containters, make `pod.Spec.Containers[0]` the default one before inject istio-proxy container.

**Comment by zirain** [comment]
sound good to keep same behaivor with kubelet
