### ISSUE TITLE
istio with tcp service

### ISSUE THREAD

**Issue by kittisuw** [istio/istio#38084]
### Bug Description

As I was installed Istio 1.31.1 with HTTP protocol service can communicate normally. But I got a problem about the client can't communicate with NATS or Redis. I think NATS and Redis communicate with TCP protocol. pls advise me If need more action.

NAT installation : https://github.com/pires/kubernetes-nats-cluster

### Version

```prose
ISTIO_VERSION=1.13.1
Kubernetes version = v1.23.4
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
see https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols
