### ISSUE TITLE
istio-inject fails with unknown field "mixerCheckServer"

### ISSUE THREAD

**Issue by pmichali** [istio/istio#3811]
When trying to run apply the bookinfo app, I see this error. A simplified case:

$ istioctl kube-inject -f samples/sleep/sleep.yaml
Error: failed to convert to proto. unknown field "mixerCheckServer" in v1alpha1.MeshConfig

I'm using latest from master, pulled today, 151c69e, but have seen this yesterday as well.

**Comment by mandarjog** [comment]
Can you confirm that you are using `istioctl` that came with the build?
run `make istioctl` just to be sure and retry.

**Comment by pmichali** [comment]
Ah! I had originally used the Getting Started notes, and that had me add to my path the istioctl for 0.5.1. Following the dev instructions, I rebuilt everything, but didn't realize it was pointing to this older version still.

I adjusted path to point to ~/go/out/linux_amd64/release/ area for this.

**Comment by mandarjog** [comment]
If this still does not work, please re-open the issue. Thanks.

**Comment by marcelomrwin** [comment]
I'm facing the same issue. I have downloaded istio 0.5.1 from github for mac os-x

**Comment by mandarjog** [comment]
Please use the latest istioctl release.
