### ISSUE TITLE
Documentation for disconnected/offline install?

### ISSUE THREAD

**Issue by catherinelam** [istio/istio#38127]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Could someone please point me to documentation for the offline / disconnected install of Istio, if it is possible?
**Describe alternatives you've considered**
I've googled
**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
try `istioctl install --set hub=<your_private_hub>`

**Comment by laurecs** [comment]
I also need this. Is there any documentation? 

I have used the “**istioctl generate manifest > generated-manifest.yml**” to save the installation files, I have replaced the 3 images (proxy, pilot, prometheus) with my images hosted in AWS ECR and applied the file with kubectl. I should mention that “istioctl apply manifest” times out for some reason. I have also created the “istio-system” namespace manually before installation. 

There is no istio-egressgateway with the default profile. Is the egress gateway not needed if I need to expose an application?
The NLB is created with 4 listeners (80, 443, 15443, 15021) but I can connect only to 15201, the others refuse the connection. Hence only the 15021 target group is healthy, the other 3 are not.

**Comment by laurecs** [comment]
> try `istioctl install --set hub=<your_private_hub>`

Can you expand on this? Does it mean that we need a private Helm repository?

**Comment by zirain** [comment]
nop, for istio part, you just need a private docker registry.
components like `prometheus` `grafana` are not part of istio, you should install them correctly if you want use them in production.
yaml in samples folder is not for production.

**Comment by willzhang** [comment]
> 尝试`istioctl install --set hub=<your_private_hub>`

But the problems is where are the image lists for istio,  if there have no image lists , what images should push to your private hub?

**Comment by zirain** [comment]
normally, istio publish four images: `pilot` `provyv2` `operator` `istioctl`, all images can be fetched by running `docker pull istio/<image_name>:<release_tag>`.

```console
docker pull istio/pilot:1.14.1
1.14.1: Pulling from istio/pilot
d5fd17ec1767: Already exists 
94afd92b4d95: Pull complete 
41e1fe774550: Pull complete 
4275e868ae57: Pull complete 
ba8af42ce310: Pull complete 
c3efeee803ac: Pull complete 
Digest: sha256:1e7b63c09af457b93c17d25ef4e6aee96b5bb95f087840cffd7c4bb2fe8ae5c6
Status: Downloaded newer image for istio/pilot:1.14.1
docker.io/istio/pilot:1.14.1
```
