### ISSUE TITLE
case insensitive matching of paths in AuthorizationPolicy

### ISSUE THREAD

**Issue by gaurav517** [istio/istio#38139]
I would like to deny any request to `.*/internal/.*` in case insensitive way. Could not find an option to specify case insensitive comparison. I saw in doc [an envoy filter for case insensitive comparison](https://istio.io/latest/docs/ops/best-practices/security/#customize-your-system-on-path-normalization) for paths but that uses Lua and doc does not recommend using Lua filters. Is there an equivalent example in WASM?

Also not sure whether regex is supported for paths? 

Thanks a lot.

**Comment by yangminzhu** [comment]
The case insensitive matching is not supported in authorization policy. This should be doable in WASM but I do not have example for it.
