### ISSUE TITLE
istioctl analyze: showing invalid error on release 1.13.2

### ISSUE THREAD

**Issue by soumyaparui** [istio/istio#38148]
### Bug Description

On the same cluster when running same command 
`istioctl analyze -A`

When the istioctl version is 1.13.2 it is showing the following as a error in the result:
`Error [IST0101] (Gateway istio-system/istio-ingressgateway) Referenced selector not found: "istio=ingressgateway"`

But when istioctl version is 1.12.2 it not showing anything as such.

Upon manual verification of the cluster the error looks to invalid. And all traffic are working fine in the cluster.

Upon verification of one of the gateway pod I can see the label:
```
$ kubectl describe pod istio-ingressgateway-abcd -n istio-system
Labels:       
              istio=ingressgateway
```
Also Istioctl validate does not seems to show any issues:
```
kubectl get gw istio-ingressgateway -n istio-system -o yaml | istioctl validate -f –
kubectl get deployments -o yaml -n istio-system | istioctl validate -f –
kubectl get services -o yaml -n istio-system | istioctl validate -f –
kubectl get pods -o yaml -n istio-system | istioctl validate -f –
```

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (9 proxies)

$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.9
```

### Additional Information

Related to:
https://github.com/istio/istio/issues/36160

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by soumyaparui** [comment]
Even I am getting invalid error on authorizationpolicy:
Error [IST0101] (AuthorizationPolicy sample-namespace/sample-authorizationpolicy) Referenced namespace not found: "sample-namespace"

**Comment by zirain** [comment]
seems related to https://github.com/istio/istio/issues/38636.

**Comment by zirain** [comment]
looks like a regression from https://github.com/istio/istio/pull/35764. the revision is const to `default`.
https://github.com/istio/istio/pull/38467 do not fix all.

**Comment by zirain** [comment]
prev fix has regression

**Comment by soumyaparui** [comment]
This issue still exists in 1.13.4 release as well.

**Comment by simonpie** [comment]
I have the exact same problem : 

```
[Ananke:: 16:37:12] [../Kubernetes/Canari/test1] > istioctl analyze -A | grep -i Error                            
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.13/docs/reference/config/analysis for more information about causes and resolutions.
Error [IST0101] (Gateway istio-gateways/gateway-for-all-apis) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway istio-gateways/gateway-for-services) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway istio-squelette/httpbin-gateway) Referenced selector not found: "istio=ingressgateway"
Error [IST0101] (Gateway test-automatique/test-automatique-gateway) Referenced selector not found: "app=istio-ingressgateway"
[Ananke:: 16:37:53] [../Kubernetes/Canari/test1] > kc get pods -n istio-gateways --show-labels
NAME                                    READY   STATUS    RESTARTS   AGE   LABELS
istio-ingressgateway-6899b77bd4-kj976   1/1     Running   0          55d   app=istio-ingressgateway,istio.io/rev=1-13-2,istio=ingressgateway,pod-template-hash=6899b77bd4,service.istio.io/canonical-name=istio-ingressgateway,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-ingressgateway-6899b77bd4-kzwbr   1/1     Running   0          20d   app=istio-ingressgateway,istio.io/rev=1-13-2,istio=ingressgateway,pod-template-hash=6899b77bd4,service.istio.io/canonical-name=istio-ingressgateway,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
[Ananke:: 16:38:05] [../Kubernetes/Canari/test1] > kc version                                 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
[Ananke:: 16:39:22] [../Kubernetes/Canari/test1] > istioctl version                   
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (110 proxies)
[Ananke:: 8:48:24] [../Kubernetes/Canari/test1] > 
 ```

**Comment by aadhik** [comment]
Canary Upgrade fails due to this error , I testing even by patching the label from istio=ingressgateway to istio=istio-ingressgateway , still get the same error
 Referenced selector not found: "istio=istio-ingressgateway"
Error: Analyzers found issues when analyzing namespace: istio-system.
See https://istio.io/v1.13/docs/reference/config/analysis for more information about causes and resolutions.

**Comment by zirain** [comment]
not stale

**Comment by Atinlay** [comment]
We also get this error in 1.14.3

**Comment by simon-anz** [comment]
I think I have the same issue.  Does istioctl assume PILOT_SCOPE_GATEWAY_TO_NAMESPACE=true ?
https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway

eg:
```
❯ istioctl version
client version: 1.15.0
control plane version: 1.14.4-asm.0
data plane version: 1.14.4-asm.0 (51 proxies)

❯ istioctl analyze -A | head
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.15/docs/reference/config/analysis for more information about causes and resolutions.
...
Error [IST0101] (Gateway platform-apm/platform-apm-ingress-gateway) Referenced selector not found: "istio=ingressgateway"
...

❯ k get gateway -n platform-apm platform-apm-ingress-gateway -o yaml | yq .spec.selector
istio: ingressgateway

❯ k get pod -A -l istio=ingressgateway
NAMESPACE      NAME                                   READY   STATUS    RESTARTS   AGE
istio-system   istio-ingressgateway-c8776d664-4vpzp   1/1     Running   0          47h
istio-system   istio-ingressgateway-c8776d664-b6266   1/1     Running   0          47h
istio-system   istio-ingressgateway-c8776d664-czkjs   1/1     Running   0          47h
istio-system   istio-ingressgateway-c8776d664-k7zh6   1/1     Running   0          4m16s
istio-system   istio-ingressgateway-c8776d664-q6j77   1/1     Running   0          4m16s
```

**Comment by simon-anz** [comment]
It looks like the list of pods that the Gateway (in my example above) is checking does NOT include pods in istio-system namespace (I added some debug output)

https://github.com/istio/istio/blob/master/pkg/config/analysis/analyzers/gateway/gateway.go#L71
 
Digging...

**Comment by morremeyer** [comment]
This is not stale.

Having a bot attempting to close unresolved issues will only create notification spam and/or lead to multiple issues being created for the same problem.

**Comment by StianOvrevage** [comment]
This is still an issue on 1.15.3

**Comment by StianOvrevage** [comment]
Go away, bot :)

**Comment by nmnellis** [comment]
@therealmitchconnors it appears that something in this PR broke the store of PODs https://github.com/istio/istio/pull/35764 
so far it looks like the /v1/pod query grabs all pods but filters them somewhere down to only the kube-system ones

**Comment by nmnellis** [comment]
the issue lies here https://github.com/istio/istio/blob/1.13.0/pilot/pkg/config/kube/arbitraryclient/client.go#L345
the `if cl.objectInRevision(cfg) {` is filtering the pods too much

**Comment by nmnellis** [comment]
@howardjohn if i remove this line it works but it looks like that will cause a ton of unintended consequences, https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crdclient/client.go#L411

Any idea how we can not filter the gateway pods (they dont have revision labels) for istioctl analyze

how i installed the gateway

```
helm install istio-ingressgateway istio/gateway \
  -f cluster1-ingress-values.yaml \
  --namespace istio-ingress \
  --version $ISTIO_VERSION \
  --create-namespace  \
  --set revision=$ISTIO_REVISION \
  --set name=istio-ingressgateway-${ISTIO_REVISION}

```

**Comment by morremeyer** [comment]
@nmnellis I think you need to set the lifecycle/staleproof label to stop the bot fighting you (and to stop it from spamming all of us).

**Comment by nmnellis** [comment]
ill leave it closed, i have a fix that will allow you to set the revision which should merge today

**Comment by avistech** [comment]
This is still an issue on 1.16.2. Can we safely ignore it ?

**Comment by aryan16** [comment]
any updates on this one?

**Comment by hanxiaop** [comment]
@zirain Are you still working on this?

**Comment by hanxiaop** [comment]
Can anyone provide the Gateway resource that will cause `ReferencedNotFound` error?

**Comment by zirain** [comment]
no, but I recall someone send another PR about this.

**Comment by nmnellis** [comment]
Are you using revisions? I recently added a --revision flag that fixes this error.

https://github.com/istio/istio/pull/42435

**Comment by hanxiaop** [comment]
It seems that https://github.com/istio/istio/issues/44430 is related to this. Please check if the ingressgateway is installed with a revision; if so, use the `--revision` flag.

**Comment by hanxiaop** [comment]
I think this is actually fixed by https://github.com/istio/istio/pull/46241.

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/46241
