### ISSUE TITLE
Debugging istio's source code

### ISSUE THREAD

**Issue by 4br3mm0rd** [istio/istio#38151]
### Bug Description

Hi,

I am trying to debug istio's source code in order to understand some of the stuff that happens at the startup of the pilot program. In order to do that, I follow the great explanations from this page:  https://github.com/istio/istio/wiki/Using-the-Code-Base#building-the-code

The problem is when I run the following command in order to actually load the built programs into a container:
`go run ./istioctl/cmd/istioctl install` The containers are downloaded from the internet instead of being loaded from the built sources.

I am using minikube with docker and everything is running on my local machine. I tried loading the built images into minikube by running `minikube image load localhost:5000/pilot` (for all images). I even tried to rename the images as gcr.io/istio-testing/xxx

I see that the containers do not include the debug information that I need. Also, according to [this tutorial](https://github.com/istio/istio/wiki/Remote-Debugging) I should have the entrypoint in istiod being Delve which is not the case.

I also tried pushing the containers to a local registry. The problem is that in order for minikube to access the images, I need either to load them, or to set the docker-env variables for minikube, which seems to break the build process (the make command returns an error related to docker).

Do you have any idea how I could debug the source of istio with minikube?

Thank you very much,

4br3mm0rd

### Version

```prose
go run ./istioctl/cmd/istioctl version
client version: unknown
control plane version: 1.14
data plane version: 1.14-alpha.bd9f6a272c89db54cf08404bca1c86d68f59feba (1 proxies)
```

**Comment by GregHanson** [comment]
if the `eval $(minikube docker-env` command is causing problems, you can always push the images to docker hub instead of trying to use the local ones.  
```
make build
make docker HUB=<your_docker_id> TAG=latest
make docker.push HUB=<your_docker_id> TAG=latest
Istioctl install --set hub=<your_docker_id> set tag=latest
```
As for the Delve tutorial, I am not sure when that last time these steps were tested and if there are any known issues with those steps on Mac

**Comment by 4br3mm0rd** [comment]
> if the `eval $(minikube docker-env` command is causing problems, you can always push the images to docker hub instead of trying to use the local ones.

This worked perfectly thank you :) 



> When doing dev, I also use KinD which allows me to easily push docker images to with the labels that I like to the cluster so that I do not have to deal with keep pushing dev images to a repo. I’ve also developed these scripts to help me doing the development. The two scripts that I have are here https://github.com/litong01/multicluster-istio/tree/main/dev. One is to build the images and label them as I wish, the other one is to upload the image to the KinD cluster so that your istio deployment can stay as is. Minikube can do push images to its clusters as well, you probably just need to change the script a bit to push your dev image to Minikube cluster, then you do not need to change how to deploy istio.

Wow, this looks amazing! I'll give it a look!

I'll give a look on how to add Minikube support in the next weeks if I find time. Thank you for your answers!
