### ISSUE TITLE
a lot of linter errors from envoy/v2/mesh

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3818]
result from bin/linter.sh  Please fix

pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (interfacer)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (interfacer)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (structcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (structcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: unused struct field could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (structcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (unconvert)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (maligned)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (maligned)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (unconvert)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (maligned)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (interfacer)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (unconvert)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (unconvert)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (interfacer)
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (maligned)
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (structcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Metadata) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Metadata) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:938:14:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (varcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:915:14:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Metadata (varcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: unused variable or constant could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (varcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of: (megacheck)
pilot/pkg/proxy/envoy/v2/mesh.go:70:9:error: error return value not checked (could not import github.com/envoyproxy/go-control-plane/api (cannot find package "github.com/envoyproxy/go-control-plane/api" in any of:) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (varcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:40:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (structcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:475:11:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (structcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:475:11:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:40:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:5:error: unused struct field invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (structcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:5:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (varcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:40:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (varcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:474:5:error: error return value not checked (invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint) (errcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:475:11:error: unused variable or constant invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (varcheck)

**Comment by loewenstein** [comment]
@xiaolanz I just tried `make lint` and `bin/linters.sh` (couldn't find `bin/linter.sh`) on todays master and don't get any complaints.

```
$ make lint
...
+ echo 'Running gometalinter ....'
Running gometalinter ....
+ gometalinter.v2 --config=./lintconfig_base.json ./...
+ echo 'gometalinter OK'
gometalinter OK
+ echo 'Running gometalinter on adapters ....'
Running gometalinter on adapters ....
+ pushd mixer/tools/adapterlinter
~/workspace/go/src/istio.io/istio/mixer/tools/adapterlinter ~/workspace/go/src/istio.io/istio
+ go install .
+ popd
~/workspace/go/src/istio.io/istio
+ gometalinter.v2 --config=./mixer/tools/adapterlinter/gometalinter.json ./mixer/adapter/...
+ echo 'gometalinter on adapters OK'
gometalinter on adapters OK
```

Picking the first complaint from your list and checking manually: `eb` is of type `*LbEndpoint` (`Endpoint` is an alias for `LbEndpoint`) and `LbEndpoint` is a struct with field `Endpoint`.
```
pilot/pkg/proxy/envoy/v2/mesh.go:686:24:error: invalid operation: ep (variable of type *Endpoint) has no field or method Endpoint (interfacer)
```
I suppose this is no issue with current master.
