### ISSUE TITLE
Some CRD not cleaned-up after uninstall

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3819]
$ kubectl get crd 
NAME                                                      AGE
enduserauthenticationpolicyspecbindings.config.istio.io   6d
enduserauthenticationpolicyspecs.config.istio.io          6d
gateways.config.istio.io                                  6d
httpapispecbindings.config.istio.io                       6d
httpapispecs.config.istio.io                              6d
quotaspecbindings.config.istio.io                         6d
quotaspecs.config.istio.io                                6d

**Comment by diemtvu** [comment]
These configs are created by pilot for each Istio configs. I guess we will need a script to know what CRD are added and issue corresponding k8s delete command. + @xiaolanz

**Comment by xiaolanz** [comment]
It's intentional that we don't remove crds after uninstall. 

CRDs are registered in cluster scope. We cannot deregister these CRDs programmatically because it affects other test instances on shared cluster.
