### ISSUE TITLE
How can I get istio-proxy stat when triggering circuit breaker?

### ISSUE THREAD

**Issue by bochengdong** [istio/istio#38193]
### Bug Description

I am using the istio 1.13.2 to test the function of circuit breaker with fortio step by step according to the [document](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/).But I get nothing when I run kubectl exec "$FORTIO_POD" -c istio-proxy -- pilot-agent request GET stats | grep httpbin | grep pending.I feel confused about it. Is there any other settings about fortio or istio? And I find the value of upstream_rq_pending_overflow is 0.

![image](https://user-images.githubusercontent.com/32670362/161002357-dc6b64c2-da5b-4397-b805-7104030d5720.png)
![image](https://user-images.githubusercontent.com/32670362/161002449-a405701b-d9c6-41e7-832d-dde6fc70d424.png)

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (13 proxies)
$ kubectl version --short
Client Version: v1.23.1
Server Version: v1.23.1
```

**Comment by zirain** [comment]
most of those are gauge metric, can you run the following command and watch the output in another shell?
`kubectl exec "$FORTIO_POD" -c fortio -- /usr/bin/fortio load -c 2 -qps 0 -t 10m -loglevel Warning http://httpbin:8000/get`

**Comment by bochengdong** [comment]
> 


![image](https://user-images.githubusercontent.com/32670362/162343930-e3ce8ad0-1f0b-444f-9330-46a98157f907.png)
![image](https://user-images.githubusercontent.com/32670362/162343941-ee0106cb-4d24-433f-b0e1-a6df0200f967.png)

**Comment by bochengdong** [comment]
@zirain 
![image](https://user-images.githubusercontent.com/32670362/162344053-805209be-f707-4219-b9ef-1b03e7409df4.png)
![image](https://user-images.githubusercontent.com/32670362/162344065-d26a8415-fd9e-4184-a862-f545d769ea68.png)
I don't know how to check. Please help me
