### ISSUE TITLE
http: proxy error: dial tcp: lookup prometheus on 10.254.0.2:53: dial udp 10.254.0.2:53: i/o timeout

### ISSUE THREAD

**Issue by fatg1988** [istio/istio#382]
https://istio.io/docs/tasks/installing-istio.html
kubectl apply -f install/kubernetes/addons/prometheus.yaml
kubectl apply -f install/kubernetes/addons/grafana.yaml
grafana can't data
k8s
1 master  2 node 
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

![default](https://user-images.githubusercontent.com/3365952/26923296-435de444-4c74-11e7-9ab2-6b2f9333bd18.png)

**Comment by skymeyer** [comment]
Seems this target only became available for me after deploying an application and make a request to it (i.e. the bookinfo one).

**Comment by andraxylia** [comment]
The Prometheus adapter in mixer is started only after relevant traffic is received. It is only then the mixer opens its port 42422, which is the Prometheus target.

The error above seemed to imply you could not access Prometheus, not that Prometheus could not scrape mixer.

If all is good now, please close the issue.
