### ISSUE TITLE
`golint` is deprecated. Replace with `revive`

### ISSUE THREAD

**Issue by ericvn** [istio/istio#38201]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

From the linting logs:
```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
```
**Describe alternatives you've considered**

The accepted replacement for glint seems to be reviewing as noted.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I found one nolint: golint in `release-builder` and a number of them in `istio`.
I did to a quick sniff test. Even replacing `nolint: golint...` with `nolint: golint, revive...` (temporarily just add `revive` and remove `golint`   after the common-files are updated), there are a number of other failures noted in istio/istio and possible the other repos.

Once given the go-ahead I think the remaining changes can be made in the repos, the changes checked in, common-files updated, and then the nolint:golint removed.

**Comment by zirain** [comment]
@ericvn I think it's ok to close this, WDYT?

**Comment by ericvn** [comment]
Yes. The only thing we might want to do, but not sure, would be to remove the `nolint: golint` tag now that the build-tools are updated.

**Comment by zirain** [comment]
> Yes. The only thing we might want to do, but not sure, would be to remove the `nolint: golint` tag now that the build-tools are updated.

I forgot that, will do that tomorrow.

**Comment by zirain** [comment]
closed as everything might be ok now.
