### ISSUE TITLE
Istio build is failing

### ISSUE THREAD

**Issue by NishikantThorat** [istio/istio#38216]
### Bug Description

For master(https://github.com/istio/istio.git), build is failing.

Build error,
```
real	3m4.528s
user	10m34.319s
sys	0m54.207s
GOOS=linux GOARCH=ppc64le LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /home/jenkins/workspace/istio/istio/out/linux_ppc64le/ -tags=agent ./pilot/cmd/pilot-agent

real	0m13.954s
user	0m21.933s
sys	0m1.965s
make: *** No rule to make target '/home/jenkins/bin/go-junit-report', needed by 'racetest'.  Stop.
```

Changes in Makefile.core.mk causing failure,
Ref: https://github.com/istio/istio/commit/3ee65f7bbbae662e9ff4183262bd1d677caed86c#diff-662262a00ad44baa70fb14405b688c43143c3b4635ff8766030dd34b328f8306L459

### Version

```prose
$ istioctl  version
1.14-dev
```

**Comment by ericvn** [comment]
I haven't seen this failure. Normally I think I would see /work directories so are you using BUILD_WITH_CONTAINER=0? I see a different file warning there.

**Comment by NishikantThorat** [comment]
Thanks Eric. Here is what I tried,
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)   _( Note: Inside container(registry.access.redhat.com/ubi8:e28dbb5d0617) )_
# uname -m
ppc64le
# export BUILD_WITH_CONTAINER=0
# git clone https://github.com/istio/istio.git
# cd istio
# go install github.com/jstemmer/go-junit-report@latest
# make
```
I was able to built istio with same steps, before mentioned commit. I don't have good understanding on commit, but following fix works for me on latest codebase,
```
# git diff Makefile.core.mk
diff --git a/Makefile.core.mk b/Makefile.core.mk
index 6a2f2cbd60..4296497ca7 100644
--- a/Makefile.core.mk
+++ b/Makefile.core.mk
@@ -444,6 +444,10 @@ istioctl-install-container: istioctl

 JUNIT_REPORT := $(shell which go-junit-report 2> /dev/null || echo "${ISTIO_BIN}/go-junit-report")

+${ISTIO_BIN}/go-junit-report:
+       @echo "go-junit-report not found. Installing it now..."
+       unset GOOS && unset GOARCH && CGO_ENABLED=1 go get -u github.com/jstemmer/go-junit-report
+
 # This is just an alias for racetest now
 test: racetest ## Runs all unit tests
```

Kindly let me know, if there is any amiss from my end.

**Comment by ericvn** [comment]
You set `export BUILD_WITH_CONTAINER=0` which means you are not using the Istio build environment. Note that is set to one in the Makefile overrides.

**Comment by ericvn** [comment]
More testing shows that we shouldn't need to add the snippet back in. One just needs to make sure go-junit-report is available where you are running the test (it is in the build container and thus should installed locally if not using the build container).

`go install github.com/jstemmer/go-junit-report@latest` does that for me (I have go  version 1.18 installed). After running the command, you should have a copy of `go-junit-report`:
```
which go-junit-report 
/Users/ericvn/work/go/bin/go-junit-report
```
Noting that it is in my $GO_PATH/bin directory.

Looking at your message, would you verify that `go-junit-report` is in the appropriate directory.:
```
ls $GOPATH/bin/go-junit-report
/Users/ericvn/work/go/bin/go-junit-report
```

**Comment by NishikantThorat** [comment]
With appropriate directory, able to complete the build. Thanks @ericvn !!
```
...
?       istio.io/istio/tools/istio-iptables/pkg/cmd     [no test files]
ok      istio.io/istio/tools/istio-iptables/pkg/config  0.003s
?       istio.io/istio/tools/istio-iptables/pkg/constants       [no test files]
ok      istio.io/istio/tools/istio-iptables/pkg/dependencies    0.003s
?       istio.io/istio/tools/istio-iptables/pkg/log     [no test files]
?       istio.io/istio/tools/istio-iptables/pkg/testing/data    [no test files]
?       istio.io/istio/tools/istio-iptables/pkg/testing/maintest        [no test files]
ok      istio.io/istio/tools/istio-iptables/pkg/validation      0.003s
```

Seems like target removed from _Makefile.core.mk_ in mentioned commit, but call to target is still there.

**Comment by ericvn** [comment]
Sounds like we have 2 choices (besides doing nothing):
1. Add the code back in, but need to change it to do a `go install go-junit-report` as `go get` won't actually create the binary (if using Go 1.18). This isn't needed in the normal build as the binary is already installed in the build container. A negative for doing this is that we are modifying the host and this may not be desired.
2. Update the code to tell the developer to install `go-junit-report` and exit. This would be no different than requiring the local build environment to be correct.
