### ISSUE TITLE
EnvoyFilter are not automatically applied to ingressgateway after upgrading Istio

### ISSUE THREAD

**Issue by willtn** [istio/istio#38214]
### Bug Description

We have several EnvoyFilter removed whenever we upgrade Istio. In this report, we upgraded Istio from 1.10.6 to 1.12.2. The filters were not automatically applied to ingressgateway. In order to recover the filters, we performed `kubectl apply $ENVOY_FILTER.yaml` manually.

Here's one of the EnvoyFilter.

```apiVersion: networking.istio.io/v1alpha3
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: session-validator-filter
spec:
  workloadSelector:
    labels:
      gateway: id-ingressgateway
  configPatches:
    # All requests should be sent to sesssion-validator to check (metadata: disable=false)
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "istio.stats"
      patch:
        operation: INSERT_BEFORE
        value:
          name: axon.sessionvalidator.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inline_code: |-
              function envoy_on_request(request_handle)
                request_handle:streamInfo():dynamicMetadata():set("axon.sessionvalidator.ext_authz", "disable", false)
              end

    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                # Put sessionvalidator before istio.stats to ensure there is no DDoS
                name: "istio.stats"
      patch:
        operation: INSERT_BEFORE
        value:
          name: axon.sessionvalidator.ext_authz
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz"
            grpc_service:
              envoy_grpc:
                cluster_name: CHANGE-ME
                authority: CHANGE-ME
              timeout: 5s
            failure_mode_allow: true
            transport_api_version: V3
            # Filter is enabled for all requests.
            # requests want to be opted-out can explicitly set `disable: true` in axon.sessionvalidator.ext_authz metadata.
            filter_enabled_metadata:
              filter: "axon.sessionvalidator.ext_authz"
              path:
              - key: "disable"
              value:
                bool_match: false
```

Here's the expected result and the actual result when inspecting the listener configuration of ingressgateway. Notice the actual result is missing several filters, comparing to the expected result.
```
$ istioctl proxy-config listener -n istio-system $INGRESSGATEWAY_POD -o json | yq eval -P -
```

Actual result: [actual-result.yaml.txt](https://github.com/istio/istio/files/8396505/actual-result.yaml.txt)
Expected result: [expected-result.yaml.txt](https://github.com/istio/istio/files/8396506/expected-result.yaml.txt)

### Version

```prose
$ istioctl version
client version: 1.12.2
control plane version: 1.13.2
data plane version: 1.13.2 (8 proxies)

$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.9
```

### Additional Information

[before-apply_bug-report.tar.gz](https://github.com/istio/istio/files/8395994/before-apply_bug-report.tar.gz)

[after-apply_bug-report.tar.gz](https://github.com/istio/istio/files/8395996/after-apply_bug-report.tar.gz)

**Comment by zirain** [comment]
is your envoyfilter right? I can only find following from istiod-5c54b6b49b-kfrnf configz

![image](https://user-images.githubusercontent.com/4354057/161239203-f9108ac1-024e-4284-9ded-0c065a32dc0f.png)

**Comment by vsabella** [comment]
@zirain I believe so - We see this filter go away on upgrade but its there when we downgrade.

> is your envoyfilter right? I can only find following from istiod-5c54b6b49b-kfrnf configz
> 
> ![image](https://user-images.githubusercontent.com/4354057/161239203-f9108ac1-024e-4284-9ded-0c065a32dc0f.png)

**Comment by vsabella** [comment]
@willtn any thoughts? Do you need additional data from us
