### ISSUE TITLE
Adopt efficient path based routing in Istio

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38222]
https://github.com/envoyproxy/envoy/issues/18148#event-6348368516

This is useful for more efficient implementation of Ingress and k8s Gateway.

How I would implement it:
* https://github.com/istio/istio/blob/e11efc56130c1be35649b18b7eda6707aef35759/pilot/pkg/config/kube/gateway/conversion.go#L1057 remove this conversion, and the same one on the Ingress code
* For the internally generated VirtualServices, add an annotation indicating we should use PathPrefix mode.
* In the VS -> XDS Route code, add a version check. If >=1.14, set path_prefix. If old, add the same regex hack

**Comment by fatedier** [comment]
Can we support it in VirtualService too?

**Comment by SpecialYang** [comment]
Can we upgrade this feature to VirtualService api? This is effecient prefix path routing for gateway cases.

@howardjohn @hzxuzhonghu
