### ISSUE TITLE
CentOS 8 and variants do not work on VMs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38224]
We had tests for CentOS 8 VMs for a while, but they didn't work. When we fixed them to actually run CentOS, they started failing immediately.

The issue stems to the iptables rules; CentOS 8 doesn't seem to have any way to use iptables-legacy, and I couldn't find any way to enable the kernel modules which *maybe* would make it work with nftables.

cc some redhat folks @jwendell @dgn

**Comment by jewertow** [comment]
Keep it open. I will take a look at this problem.

**Comment by jewertow** [comment]
Keep it open.

**Comment by V-know** [comment]
I fixed the this by loading iptables modules with commands as below:
```
modprobe ip_tables
modprobe iptable_filter
```
CentOS 8 don't load them by default, so we should load it mannuly.

It works well for me.

You can put the two commands at the end of file `/etc/rc.local`, your server will load it once you server resetared.

**Comment by howardjohn** [comment]
Should be fixed now with https://github.com/istio/istio/pull/50927.
