### ISSUE TITLE
Publish "latest" / "master" or "daily" helm charts to helm chart repository

### ISSUE THREAD

**Issue by bryankaraffa** [istio/istio#38237]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently only official releases have helm charts published:
[istio/gateway](https://artifacthub.io/packages/helm/istio-official/gateway) [[rss](https://artifacthub.io/api/v1/packages/helm/istio-official/gateway/feed/rss)]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/1490015/161617528-dd9d4315-bd39-4329-934e-eb5096bd3a20.png">

Recently there was a change that affected both the application, as well as the helm charts ( https://github.com/istio/istio/pull/37947 ).  We can pull/test those changes to the application by updating the docker tag references using the values [`image.hub=gcr.io/istio-testing` and `image.tag=latest`.  We cannot simply update the "version" for the helm release to use latest in a similar way and that would be a convenient way to use the latest versions of the helm charts and test these changes before the next major release.

As example, this https://github.com/istio/istio/issues/38217#issuecomment-1086049901 issue/resolution could be mitigated if we had convenient access to latest helm chart

Edit:  Perhaps the frequency of commits is too high and so a "daily" build would be more appropriate..

**Describe alternatives you've considered**
Currently the only method to get latest helm chart is to clone the istio/istio repo locally, and use a local reference for the helm chart source.  Using local reference for helm chart is not ideal because with the local path reference it's not easily reproducible on colleagues workstations or CI/CD systems.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
closed as https://github.com/istio/istio/issues/38217#issuecomment-1092094929
