### ISSUE TITLE
External MTLS failure only logs at "debug" level

### ISSUE THREAD

**Issue by alexlo03** [istio/istio#38235]
### Bug Description

Hello, thanks for your help.

We recently had an Istio Mesh (client) to Site (server) MTLS connection break (due to certificate expiration... 👎 ) - when debugging it was difficult to tell what was happening, in part because Istio does not log the TLS error except at the "debug" level which is the most verbose level. 

For some outbound connections (say, to random internet services) this level of logging makes sense. For a more "important" Mesh connection, it would be great to have additional signal here.

Maybe related:
https://github.com/istio/istio/issues/29565

Thanks!

### Version

```prose
$ ./istioctl version
client version: 1.10.5
control plane version: 1.10.5
data plane version: 1.10.5 (xxx proxies)

$ kubectl version --short
Client Version: v1.20.8-dispatcher
Server Version: v1.20.15-gke.1000
```

**Comment by GregHanson** [comment]
@alexlo03 do you have a sample of the envoy logs in question? depending on the envoy logger responsible for the error message, we may be able to increase the log level by default.

you can also gain a little more information about the secrets a particular sidecar in istio has by using Istioctl:
```
$ istioctl pc secrets <pod_name>
RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
default           Cert Chain     ACTIVE     true           174510444586381482569817763392997774250     2022-04-07T14:42:03Z     2022-04-06T14:40:03Z
ROOTCA            CA             ACTIVE     true           130271220344334042409162471246382559920     2032-04-03T14:40:44Z     2022-04-06T14:40:44Z
```

**Comment by zirain** [comment]
@alexlo03 maybe [this](https://github.com/istio/istio/pull/37372) can give some help.

**Comment by GregHanson** [comment]
ok, my main concern was that the certificate expired error was not getting reported in access logs, but that is not the case
```
    "response_code_details": "upstream_reset_before_response_started{connection_failure,TLS_error:_268436501:SSL_routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_EXPIRED}",
...
...
    "upstream_transport_failure_reason": "TLS error: 268436501:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_EXPIRED",
```
Does the metric zirain linked above provide what you need - or what what behavior are you looking for?

**Comment by alexlo03** [comment]
Definitely the error is in the logs. This issue is that "error is only visible in loglevel=debug, the most verbose logging level which we don't have on all the time"

We will look into tracking that metric, I don't think it is in our release (1.10)

**Comment by howardjohn** [comment]
I am not sure what you mean it's only in the debug log? It seems it's also in the access logs (as in your snippet "accessLogFile (w/ JSON)")

**Comment by alexlo03** [comment]
Hi, sorry- my expectations are probably incorrect here. Presently we have neither accessLogFile or loglevel=debug on all the time. At loglevel=warning we were unable to figure out what was happening.

I guess the issue is "not seeing MTLS expiry at loglevel=warning with no accessLogFile", if that is more or less expected that's fine, and I'm happy to close.

**Comment by howardjohn** [comment]
I would expect it in access logs. A failed mTLS request is not much
different than any other failed request, which would similarly fall under
access logs category.

Note that with the recent Telemetry API there is a log filter so you could
log errors only in the access logs

**Comment by alexlo03** [comment]
Cool thanks all we'll be improving our posture

**Comment by GregHanson** [comment]
The Telemetry filter mentioned above: [link](https://istio.io/latest/docs/reference/config/telemetry/#AccessLogging-Filter)
