### ISSUE TITLE
getServiceAccountSecret assumes auto-created service account token secrets

### ISSUE THREAD

**Issue by liggitt** [istio/istio#38246]
### Bug Description

[getServiceAccountSecret](https://github.com/istio/istio/blob/5fd92a170f500462bb6ffd1d9462d6592968cd9a/istioctl/pkg/multicluster/remote_secret.go#L234) assumes 1) secret-based tokens will always be created for service accounts, and 2) a manually provided secret name will be referenced from the service account

Neither of those assumptions are universally correct.

In 1.21+ secret-based tokens are no longer used for mounting into pods (ephemeral time-limited tokens are).

In 1.24+, secret-based tokens are no longer auto-created by default for new service accounts.

Using ephemeral time-bound tokens is preferred in 1.21+ (see the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API) if possible.

If a secret-based token is still desired, one can be [created manually](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token), but will not be referenced from the service account's .secrets list. If a secret name is explicitly provided to istioctl, it should be validated by looking at the type (`kubernetes.io/service-account-token`) and the `kubernetes.io/service-account.name` annotation (should match the service account name)

### Version

```prose
n/a
```

**Comment by liggitt** [comment]
cc @monkeyanator

**Comment by stevenctl** [comment]
cc @costinm 

Thanks for reporting!

**Comment by howardjohn** [comment]
@stevenctl how come our CI didn't capture this? Or did it? We do test 1.24 - but possibly a build before the changes described here
