### ISSUE TITLE
Allow the gateway helm chart to override lifecycle settings set at the mesh global config

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#38245]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Update the gateway helm chart to allow the lifecycle section be overridden 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I have the following currently set for the istiod helm install:
global:
  proxy:
    lifecycle:
      preStop:
        exec:
          command:
            - sh
            - -c
            - echo "Stopping container in 30 seconds...">/proc/1/fd/1 && sleep 30
      postStart:
        exec:
          command:
          - pilot-agent
          - wait

but i need the ability to override the preStop section due to aws nlb update speed with the following:

          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - echo "Stopping container in 300 seconds...">/proc/1/fd/1 ; sleep 300

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ is the way to do this
