### ISSUE TITLE
Multicluster Installation is not working due to authentication errors

### ISSUE THREAD

**Issue by headsha** [istio/istio#38258]
### Bug Description

Hello!
I had followed https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/ to configure the multi cluster setup.
Also configured cacerts for cluster1 and cluster2 , by following the steps mentioned in  https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/?_ga=2.176137186.1580396703.1649064168-393612529.1641549472#plug-in-certificates-and-key-into-the-cluster 

istio-eastwestgateway and istio-ingressgateway pods in the remote cluster (cluster2) seems to be in not ready state.

```
 kubectl get po -n istio-system --context $cluster2
NAME                                    READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-9cddfcb-g2ssn   0/1     Running   0          16h
istio-ingressgateway-5747c7d8-ccjm6   0/1     Running   0          16h
istiod-c6d67744-9dq89                 1/1     Running   0          16h
```
Ingress pod logs(cluster2) reports the following error repeatedly :
```
info    xdsproxy        connected to upstream XDS server: istiod-remote.istio-system.svc:15012
2022-04-06T07:50:08.228707Z     warn    xdsproxy        upstream [1683] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
```

Istiod pod (cluster1) reports the following error repeatedly: 
```
Failed to authenticate client from 10.178.0.74:56260: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client
```

Both clusters support third party service account tokens
```
kubectl --context $cluster1 get --raw /api/v1 | jq '.resources[] | select(.name | index("serviceaccounts/token"))'
{
    "name": "serviceaccounts/token",
    "singularName": "",
    "namespaced": true,
    "group": "authentication.k8s.io",
    "version": "v1",
    "kind": "TokenRequest",
    "verbs": [
        "create"
    ]
}
```
(cluster1 is a GKE cluster and cluster2 is AKS)
Istio Version: 1.13.2

Is there anything that I'm missing here? 
Any help would be appreciated .
Thanks in advance! :) 

### Version

```prose
istioctl version 
client version: 1.13.2
control plane version: 1.13.2
data plane version: none
kubectl version --short
Client Version: v1.23.3
Server Version: v1.20.15-gke.1000
```

**Comment by litong01** [comment]
@headsha can you post the errors why gateway pod are not up running? can you post the `kubectl describe` command result here?

**Comment by zirain** [comment]
can you share logs from istiod and ingressgateway pod?

**Comment by headsha** [comment]
> can you share logs from istiod and ingressgateway pod?

Ingress pod logs(cluster2) reports the following error repeatedly :
```
info    xdsproxy        connected to upstream XDS server: istiod-remote.istio-system.svc:15012
2022-04-06T07:50:08.228707Z     warn    xdsproxy        upstream [1683] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
```

Istiod pod (cluster1) reports the following error repeatedly: 
```
Failed to authenticate client from 10.178.0.74:56260: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client
```

**Comment by songweirong19931020** [comment]
Dude, did you solve it? I had the same problem as you.

**Comment by songweirong19931020** [comment]
ingressgateway pod is not ready, wtf!!!!

**Comment by 13567436138** [comment]
I had the same problem，how to solve
