### ISSUE TITLE
Mixer should handle (not-)caching of ephemeral attributes

### ISSUE THREAD

**Issue by ozevren** [istio/istio#3825]
Mixer currently keeps track of attributes that are referenced, so that Proxy can create cache keys based on that.

Attributes such as context.time is problematic with the current approach. Unlike APA, which ends up creating new attributes based on incoming attributes, some of the attributes like context.time is based only on ambient context within Mixer. 

Incorporating these attributes in a cache key is problematic. On one hand, if they get incorporated, it will cause a cache-miss for sure (as Proxy doesn't have this attribute). On the other hand, if they don't get incorporated, then any expression that depends on these highly ephemeral values can easily end up poisoning the cache (e.g. if a match condition depends on context.time, then it is probably not a good idea to cache its result in the proxy).

It might be prudent to signal to the Proxy that the result of the operation should simply be not cached when such attributes are referenced.

**Comment by mandarjog** [comment]
If config uses request.time it should just work. We have defined other time functions like time-of-day, hours, mins, day-of-week
day-of-month etc but have not implemented them.
These functions based on request.time will automagicLly work.

I suspect the current use case is on the report path.

**Comment by ozevren** [comment]
Yes, for attributes/values that originate (or derived) from proxy, the correctness semantics will be preserved. However, even then, it probably doesn't make sense to have them cached for nonce values such as request.time.

**Comment by douglas-reid** [comment]
@bianpengyuan can you take a look at what is required to close this out please?

**Comment by bianpengyuan** [comment]
I think context.time is added by proxy instead of mixer right? https://github.com/istio/proxy/blob/4cfa354bbeb42ae67c3c634e19ad01a54339cb3a/src/istio/control/tcp/attributes_builder.cc#L74

To my knowledge, mixer does not add any new attributes except output from APA, and right now mixer would not add attributes from APA into cache key. Did I miss something?

**Comment by ozevren** [comment]
This was a long time ago, so my mental model for this has rotted a bit.

Mixer sends a list of used/not-used attribute list back to proxy, so that proxy can construct a cache. However, context.time is essentially a nonce. Creating a cache key wit it doesn't make sense. I am not sure if there are other attributes with similar problems.

**Comment by bianpengyuan** [comment]
There are several other attributes  share the similar problems, and yeah it does not make sense to include those attributes into check cache key. But from the other hand I don't think we can just exclude them from cache key, which could cause unexpected cache hit if those attributes are actually the key factor for policy check success/failure. 

So either we disable cache if those attributes are referenced (which needs some mechanism to label attributes ephemeral), or just keep the behavior as what it is now (cache miss every time).

**Comment by ozevren** [comment]
It is not only cache miss though. If we're putting in entries into the
cache with ephemeral key values, then it maybe reducing the cache
utilization.

**Comment by bianpengyuan** [comment]
Good point! So the work item would be: mark all ephemeral check attributes in attributesmanifest, then let mixer avoid generating cache reference if they are involved.

**Comment by mandarjog** [comment]
Attribute tracking is only done by the protobag. This contains whatever was sent by the proxy.
If an attribute was sent by proxy and used in mixer it will be recorded.

Are we seeing context.time being marked as used? Otherwise I don’t think this problem is exists anymore.

**Comment by douglas-reid** [comment]
I don't think there is any further work planned around this issue. It will disappear in the new extensions architecture. Closing.
