### ISSUE TITLE
Istio Helm charts cannot be fetched

### ISSUE THREAD

**Issue by ppodgorsek** [istio/istio#38268]
### Bug Description

When following the official documentation to install Istio via Helm (https://istio.io/latest/docs/setup/install/helm/), the URL mentioned in the documentation (https://istio-release.storage.googleapis.com/charts) returns the following message:

    <Error>
        <Code>NoSuchKey</Code>
        <Message>The specified key does not exist.</Message>
        <Details>No such object: istio-release/charts</Details>
    </Error>

What is the correct URL one should use? Could the documentation be updated accordingly please?

### Version

```prose
N/A
```

**Comment by ericvn** [comment]
The documented steps work for me:
```
helm repo add istio https://istio-release.storage.googleapis.com/charts                                     
"istio" has been added to your repositories
```
You are correct in that if you just open the address in the browser, you see the error message.

**Comment by ppodgorsek** [comment]
I am trying to automate my Kubernetes setup via Ansible.

When adding the repo, I am getting the following error:

> Error: looks like "https://istio-release.storage.googleapis.com/charts" is not a valid chart repository or cannot be reached: open /home/runner/.cache/helm/repository/istio-index.yaml: no such file or directory"

I am wondering how Helm can know what repo to install if the URL cannot be fetched.

**Comment by ppodgorsek** [comment]
I managed to reproduce this issue outside of Ansible by upgrading Helm to version 3.8.1:

> $ helm version
> version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
> 
> $ helm repo add istio https://istio-release.storage.googleapis.com/charts
> Error: looks like "https://istio-release.storage.googleapis.com/charts" is not a valid chart repository or cannot be reached: open /home/runner/.cache/helm/repository/istio-index.yaml: no such file or directory

**Comment by ppodgorsek** [comment]
I eventually found where the error was coming from, it was between the chair and the screen... :D

The `~/.cache/` folder had somehow been changed to belong to a different user, hence preventing any cache files to be written there by the correct user.
