### ISSUE TITLE
istio-proxy kills coredns

### ISSUE THREAD

**Issue by bitva77** [istio/istio#38269]
### Bug Description

Have like 30 `ServiceEntries`.

Have a pod that does nothing.  literally just sits there.  When it's outside the mesh, there is no network traffic at all.  Nothing.  Because the container does squat.  I run tcpdump and there's nothing but normal arp requests.

Put that pod in the mesh and all of a sudden it starts to do DNS lookup on all those `ServiceEntries`, rolling though all the search domains.  Constantly.  tcpdump shows nothing but DNS.  Constantly.

Now have like 500 pods in the mesh and all of them behave the same way.

Now we have coredns maxing out CPU constantly and spanning like 10 instances because of HPA and yeah....because istio-proxy is constantly looking up all the domain in the ServiceEntries.

This title sounds similar but I'm not sure:  https://github.com/istio/istio/issues/38102

If it wasn't for HPA on coredns we'd literally have Istio DoS'ing coredns.

### Version

```prose
istiod:  1.13.2
helm 3.x
Kubernetes: 1.21
```

**Comment by howardjohn** [comment]
Not a complete answer but https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/dns/ may help understand why a bit

**Comment by bitva77** [comment]
Thanks.  Yeah, I'm thinking it's this:

https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/dns/#proxy-dns-resolution

What a weird thing for the proxy to do.

`This happens even if the proxy never sends any requests to these applications.`

Why in tarnations would it do that?  smh

**Comment by howardjohn** [comment]
See https://github.com/envoyproxy/envoy/issues/20562

**Comment by steeling** [comment]
@howardjohn reading up a bit on this, and fairly behind so please excuse any ignorant questions :)

But would it not be feasible to do the DNS resolution in the istio control plane and push down the IP address to the sidecars via xds, so we don't run into this O(NXM) problem?

**Comment by steeling** [comment]
Yes I agree that would be desired. Hopefully they implement something like that.

Do you know if the current setup is prone to this issue? https://github.com/kubernetes/kubernetes/issues/76517 We've seen some instances of a single DNS pod getting hammered

**Comment by kyessenov** [comment]
On-demand DNS lookup should really be using DFP, not a static cluster. I think it's intentional that Envoy resolves DNS pro-actively for a cluster. It's meant to be used with high-capacity DNS-based load balancers (CloudFlare or AWL).

**Comment by steeling** [comment]
@kyessenov that would require a modification to the current API `ServiceEntry` to distinguish if it's an HTTP request correct?

That would probably catch a vast majority of cases
