### ISSUE TITLE
connectTimeout in the configMap does not take effect

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3826]
I tried to change the connectTimeout from the default 1000ms to a larger value by changing the configMap value, but this has no effect.

#kubectl get configmap istio -n istio-system -oyaml | grep connect
    # Edit this list to avoid using mTLS to connect to these services.
      # TCP connection timeout between Envoy & the application, and between Envoys.
      connectTimeout: 10s

This is what Pilot generates in CDS, connectTimeout is still 1000ms
clusters": [
   {
    "name": "in.8079",
    "connect_timeout_ms": 1000,
    "type": "static",
    "lb_type": "round_robin",
    "hosts": [
     {
      "url": "tcp://127.0.0.1:8079"
     }
    ],
    "features": "http2"
   },
   {
    "name": "in.8080",
    "connect_timeout_ms": 1000,
    "type": "static",
    "lb_type": "round_robin",
    "hosts": [
     {
      "url": "tcp://127.0.0.1:8080"
     }
    ]
   },

**Comment by ayj** [comment]
Is the issue that Pilot doesn't use the configmap at all, or that it doesn't detect the change w/o restarting the pod?

**Comment by andraxylia** [comment]
Operator error: the connectTimeout must be changed at the top level of the configMap. There is a "default" block containing a connectTimeout which has no effect, it must be removed from the config.

**Comment by ldemailly** [comment]
is there a follow up for that ^
