### ISSUE TITLE
Pod http traffic is redirected to local pod instead of target pod (Prometheus => Pod:15090/stats/prometheus)

### ISSUE THREAD

**Issue by motmot80** [istio/istio#38272]
### Bug Description

# Reproduction steps:
1. Install **istio** on "istio-system" namespace
2. Install **kiali-operator** and **kiali-cr** on "istio-system" namespace
3. Create a "sample" namespace
4. Activate proxy-injection label on "sample" namespace
5. Deploy some **workload samples** within the "sample" namespace
6. Create a "prometheus" namespace
7. Activate proxy-injection label on "prometheus" namespace
8. Install a **prometheus system** within "prometheus" namespace (f.e. prometheus-operator)

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: any-istio-sidecars
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      security.istio.io/tlsMode: 'istio'
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus 
```
9. Configure **kiali-cr** to use the **prometheus system** as source

# Expected:
Kiali is showing traffic from "sample" and "prometheus" namespace.

# Actual:
Kiali is showing traffic from "prometheus" namespace only.

# Analysis:
When disabling the proxy-injection on "prometheus" namespace everything works as expected. We can add more namespaces and they were shown in kiali. So we deep dived into the prometheus stats to find out why the stats were missing when istio is enabled on the prometheus namespace. We saw that all sidecar envoy targets were successfully scraped and we could find the different pod envoy-http-prom pod scrapes in our promehteus results. 

**BUT** no matter what scrape we are looking at every istio scrape value was the same except the properties which pod was scraped.
Tunneling into the non-prometheus pods to the http-envoy-prom we are seeing different values.

So we opened up a shell on the **prometheus** pod to a pod in the "sample" namespace (172.17.0.7) to simulate what the prometheus pod gets from the target pods and did a 

`wget <target-pod-ip>:15090/stats/prometheus`

the scrape result was the one from the prometheus-http-envoy-prom itself not the one from the target pod!!!
We tried different target pods in every time we ended getting the local http-envoy-prom result not the remote one:

![grafik](https://user-images.githubusercontent.com/1308503/162062153-569eba85-2a6a-489b-a838-990b77dc2a06.png)

Seems to us like istio is misleading the pod-2-pod traffic in this case. 
But it should be possible to include prometheus itself into the mTLS service mesh and to get metrics out of its istio-sidecar container. 

We are very grateful for any help or workaround.

Thanks in advance and best regards
Thomas

### Version

```prose
istio version (helm chart):
v1.13.2

kiali version:
v1.48.0

prometheus version:
prometheus-operator 0.54.0

kubectl version(s):
minikube: v1.23.3
RKE: v1.19
AKS: v1.20.10
```

**Comment by zirain** [comment]
can you share the config dump of prometheus pod after (8)?
BTW, why do you need (9)?

**Comment by motmot80** [comment]
@zirain 
(9) We would like to integrate Prometheus into the service mesh, too (security & traffic analysis)
We found out that there's a special configuration in the istio HELM template for the http-envoy-prom port:

https://github.com/istio/istio/blob/5955f705e20d29dd590cc11e1423e71db9dd822d/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L89

(8) prometheus config (deleted non sidecar scrape configs)

PodMonitor for prometheus operator:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-system-istio-sidecars
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      security.istio.io/tlsMode: 'istio'
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
```
Resulting config:
```
Prometheus
    Alerts
    Graph
    Status
    Help
    Classic UI

Configuration 

global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/monitoring-prometheus
    prometheus_replica: prometheus-monitoring-prometheus-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: monitoring-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http-web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      namespaces:
        own_namespace: false
        names:
        - monitoring
rule_files:
- /etc/prometheus/rules/prometheus-monitoring-prometheus-rulefiles-0/*.yaml
scrape_configs:
- job_name: podMonitor/istio-system/istio-system-istio-sidecars/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /stats/prometheus
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_security_istio_io_tlsMode, __meta_kubernetes_pod_labelpresent_security_istio_io_tlsMode]
    separator: ;
    regex: (istio);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: http-envoy-prom
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: istio-system/istio-system-istio-sidecars
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-envoy-prom
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true

```

**Comment by zirain** [comment]
what is the difference between (7) and (9)?

**Comment by motmot80** [comment]
My fault - I deleted (9).

**Comment by motmot80** [comment]
We tried setting the `enablePrometheusMerge` which results in not setting the annotations. 
But this did not change the roundtrip on the prometheus pod to himself on port 15090.

**Comment by motmot80** [comment]
@douglas-reid Thanks for the info. So we'll try to attach the prometheus from outside. 

Even knowing this fact I think it isn't obvious that you should NOT include prometheus into the service mesh and use the mentioned "workaround".

Did we miss the documentation concerning this recommendation? 
If not - maybe its possible to mention this limitation in the docs.

Maybe here: https://istio.io/latest/docs/ops/integrations/prometheus/ ?

Just because I'm curious is it because the client traffic is istio-proxied but the server traffic isn't?

**Comment by douglas-reid** [comment]
@motmot80 It is documented, but perhaps not directly enough or with enough emphasis. On the page you reference, you can find: "However, the sidecar should not intercept requests for Prometheus because Prometheus’s model of direct endpoint access is incompatible with Istio’s sidecar proxy model."

That likely isn't clear enough.

If you have suggestions for better wording, warnings, etc., please send them (bonus points if they come in the form of docs PR).

Having a better way to handle prom + mTLS, especially for the Operator use cases, would be ideal. Running a sidecar just to get the istio-certs is cumbersome and potentially problematic (like with using default injection). @myidpt or @yangminzhu may be able to talk through any plans or options in this space.

**Comment by zirain** [comment]
> We tried setting the `enablePrometheusMerge` which results in not setting the annotations. But this did not change the roundtrip on the prometheus pod to himself on port 15090.

there's a traffic issue with 15090, it will always access `127.0.0.1:15000` if the pod is injected.

> We tried setting the enablePrometheusMerge which results in not setting the annotations.
But this did not change the roundtrip on the prometheus pod to himself on port 15090.

this's wired, it's enabled by default.

**Comment by zirain** [comment]
right now 15090 listen on `0.0.0.0`, how about change to POD_IP?

@douglas-reid @howardjohn @hzxuzhonghu WDYT?

**Comment by hzxuzhonghu** [comment]
Reasonable

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/36040 discusses this thoroughly, would suggest we follow there
