### ISSUE TITLE
Tuning options for larger deployments

### ISSUE THREAD

**Issue by costinm** [istio/istio#3828]
For tracking: we need to document and add more options for replica counts, throttle, refresh delays, etc.
This is targeted for the helm-based install, and 0.7

**Comment by sakshigoel12** [comment]
@ is this ready for 0.8 release?

**Comment by sakshigoel12** [comment]
@Rigdon do you need some specific options ?

**Comment by smawson** [comment]
Closing since I think we added this stuff already to the helm charts.
