### ISSUE TITLE
istiod helm chart: add affinity and tolerations

### ISSUE THREAD

**Issue by jgournet** [istio/istio#38319]
**Describe the feature request**
Currently, we can set "nodeSelector" on the istiod helm chart, but we cannot add tolerations.
=> in our system, the "cluster" nodes have taints, and we'd like to have istiod to run on those system nodes.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
did you still working on https://github.com/istio/istio/pull/38318?

**Comment by jgournet** [comment]
No: looks like it's more complicated than I thought :/ So I closed it and hope that someone can do it properly.

**Comment by zirain** [comment]
ok, I'll take a look at this later.

**Comment by zirain** [comment]
@jgournet I think https://github.com/istio/istio/pull/37513 added those, anything I missed?

**Comment by jgournet** [comment]
@zirain :
https://github.com/istio/istio/pull/37513 did add affinity and tolerations into the deployment file, but did not add them in the values.yaml file, making them not usable (as far as I know ?)

I then tried to add them into the values.yaml file in my PR, but tests started failing - that's where I stopped
