### ISSUE TITLE
IngressGateway require TLS secret to be present in Gateway namespace

### ISSUE THREAD

**Issue by prary** [istio/istio#38323]
**Describe the feature request**
Gateway object requires TLS secret and expects that secret to be in Ingress Gateway namespace deployed. 
In a multi-tenent env access to Ingressgateway namespace can't be given. There should be a way by which Gateway pods can read secret from the user namespace. 
**Describe alternatives you've considered**
The way contour solve, gateway should read secrets from the user namespace.
**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is supported via https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/ and will likely not be supported in the Istio Gateway API.

There is lots of discussion in https://github.com/istio/istio/issues/14598, lets consolidate there
