### ISSUE TITLE
Updates to common-files with transferring registry credentials for Mac users.

### ISSUE THREAD

**Issue by ericvn** [istio/istio#38326]
**Describe the feature request**

The current script simply copies credentials from a json file into the config.json file, expecting Mac developers to uncheck a preference so Docker places the credentials in that file. The preference is no longer available and by default Docker places them in the keystore. See: https://github.com/istio/istio/wiki/Preparing-for-Development-Mac

Update the script to check for creds in the plaintext-passwords.json file and if they don't exist, try and get them from the keystore. Then pass those to the build container. Is is likely less secure to pass these in a environment variable, so need to come up with something more secure. Also, just placing the encoded credentials on disk is not likely a good solution, although not worse than requiring the devs to have them there now.

Finally, remove the credsStore line in the container's config.json so commands do try using the host key store:
```
Error: build pilot: error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ericvn** [comment]
Still like to fix this.

**Comment by hanxiaop** [comment]
not stale

**Comment by ericvn** [comment]
I haven't seen this being an issue with others recently and thus will close.
