### ISSUE TITLE
istioctl command to set replica set of istiod and istio-ingressgateway 

### ISSUE THREAD

**Issue by hugo-zhang-uipath** [istio/istio#38341]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Not sure if we already have this feature. The pain point for me is, when I use istioctl install, I can only get one pod of
istiod and one pod of istio-ingressgateway. And as I look into the istio manifest yaml file ( istioctl manifest generate > ./istio-manifest.yaml ). It has the PDB (podDisruptionBudget) set to minAvailable = 1. 

This could cause failure when I try to upgrade K8S cluster (in my case I use AKS). The node are not able to be drained cause it needs at least one istiod pod in the cluster. 

**Describe alternatives you've considered**
What I use to resolve this problem is to manually modify the replica set in the file to 2, and add pod affinity to let these pods locate in different nodes. However, these are the manual steps.

If there is a istioctl command of any other way that I can just tell istio to create replica set and affinity. That will be great.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
for replica https://github.com/istio/istio/blob/d84ad0c8236b780a398b348174dff2828cfae39e/manifests/profiles/default.yaml#L126

affinity will be enabled when v1.13.3 landing? https://github.com/istio/istio/pull/37513

**Comment by zirain** [comment]
try `istioctl install --set values.pilot.replicaCount=2`, but you'd better use with an `IstioOperator` config file like https://istio.io/latest/docs/setup/install/istioctl/#install-istio-using-the-default-profile
