### ISSUE TITLE
Need Travis enablement for Power(ppc64le) 

### ISSUE THREAD

**Issue by NishikantThorat** [istio/istio#38386]
**Feature request**
We need Power support for few istio components(istio/ istio-operator/ istio-proxy/ istio-api) by enabling Travis CI. Could you please help/ guide us in the same? @ericvn and team, any help/ guidance is highly appreciated. 

**Alternatives considered**
We tried setting up Jenkin on local setup, but we don't have product understanding to fix each failures and get it supported on Power. If this get handled by maintainer like currently getting handled for other arch, that will be great help.

**Affected product area**
[x] Installation
[x] Test and Release

**Comment by howardjohn** [comment]
I don't understand. We don't use Travis CI at all?

**Comment by NishikantThorat** [comment]
> I don't understand. We don't use Travis CI at all?

@howardjohn: I tried to locate _.travis.yaml_ but not found any for mentioned repos. I can see "https://prow.istio.io" from commit checklist, but no power builds there.

**Comment by howardjohn** [comment]
We don't use Travis CI
