### ISSUE TITLE
Add hostname to blackhole log entries

### ISSUE THREAD

**Issue by nobletrout** [istio/istio#38397]
**Describe the feature request**
Add what host if available to the BlackHole log

**Describe alternatives you've considered**
installing tcpdump on my docker container and inspecting DNS traffic

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
When examining logs of containers after enabling REGISTRY_ONLY egress routing, it's very frustrating to see entries like this:

`[2022-04-15T00:25:20.722Z] "- - -" 0 UH - - "-" 0 0 8 - "-" "-" "-" "-" "-" BlackHoleCluster - 209.85.200.95:443 10.100.14.30:36098 - -`

If the last resolved hostname or known hostname is known (via SNI peeking or something else) then it should show up in at least the first log entry so that I can say to developers "you need to allow XYZ host in your serviceentries"

Thanks guys!

**Comment by howardjohn** [comment]
Due to server first protocols we cannot really TLS sniff safely in this case which may make this pretty hard to implement

**Comment by nobletrout** [comment]
thanks for the response.
So in my instance, we're setting up REGISTRY_ONLY routing, and if the correct service entries don't exist, we see that log entry. When we provide the correct service entry, then the traffic gets routed correctly. There must be some interception in istio that indicates the hostname that client is connecting to that makes this decision appear in the log, and so it stands to evidence that at least the request must sniffable in some way (SNI/DNS/something).

**Comment by howardjohn** [comment]
Hypothetically in some cases it could and in some it can't (in how istio works today). Because it can get blackholed at different points in the processing - some before SNI is read. it used to never until recent versions which was fixed recently, so if you are on an older version an upgrade may fix it

**Comment by nobletrout** [comment]
Have you got a version number and above it works in? I'd rather not disclose what version we are on. thanks :)

**Comment by howardjohn** [comment]
I don't. This is an open source project, if you can't provide something as basic as a version number then I wouldn't expect help.
