### ISSUE TITLE
get rid of generated files in istio/istio: step 1 - generated html files

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3839]
generated files shouldn't be mixed with source code - at least for the main repo (proto/pb files in istio/api being an exception for now; until they move to vendor) 

follow up on 
https://github.com/istio/istio/pull/3635#discussion_r170146793

**Comment by geeknoid** [comment]
Since the move from Bazel, Mixer has checked in generated source files. That's unlikely to change any time soon given current build technology.

**Comment by costinm** [comment]
Agree with 'not changing any time soon' - or at least post 1.0.
Checking in .go files is common practice in go and we should continue, but for .html and other
release artifacts - I think we can generate them from the release or make (as they already are) and 
no need to check in.

**Comment by ldemailly** [comment]
this is specifically about html

@geeknoid  what necessitates those html to be checked in in istio/istio ?

**Comment by geeknoid** [comment]
This is the way things have been setup. There's likely nothing inherent that needs those files to be there, except additional processes to produce those files independently of the .pb.go files.

Aside from aesthetics, is this causing some actual real problem for developers or customers?
'

**Comment by ldemailly** [comment]
in addition to the aesthetics, like any generated files checked in, they get out of sync
it's another thing that needs to be checked/kept in sync and makes diff reviews bigger than they should

**Comment by geeknoid** [comment]
The .html files are updated along with the .pb.go files, so they're tied at the hip and will not get out of sync.
