### ISSUE TITLE
Pod healthchecks & resource request/limits

### ISSUE THREAD

**Issue by lachie83** [istio/istio#384]
I would like to update the k8s manifests to include healtchecks and resource requests and limits. Can you provide any insights into the default values?

**Comment by rshriram** [comment]
we don't have health checks for pilot and mixer.. need to add one.. (cc @kyessenov @ijsnellf @GregHanson @douglas-reid @ZackButcher ). As for resource limits, neither of them are tremendous CPU/memory hogs. That said, we haven't profiled it enough to identify the exact limits.

**Comment by ZackButcher** [comment]
I filed https://github.com/istio/mixer/issues/1095 to track this in Mixer.

**Comment by linsun** [comment]
we may have to defer this to 0.3, any objections?

**Comment by lachie83** [comment]
No objections here. We need to establish a baseline before we draw hard lines. It might be worth adding requests so that the kubernetes scheduler can make sure that there is at least that much room to run. I could also make these configurable in the helm chart so folks can experiment.

**Comment by ldemailly** [comment]
Some values were set in 0.8, there is a follow up in #6229

will close this for now and the run book / scaling doc is part of the swat team deliverables for 1.0
