### ISSUE TITLE
Grafana AddOn Duplicate Port

### ISSUE THREAD

**Issue by craigb-zencore** [istio/istio#38407]
### Bug Description

The Deployment of the Grafana AddOn has a duplicate port and thus not able to be deployed.

https://github.com/istio/istio/blob/master/samples/addons/grafana.yaml

We are using GCP Anthos Config Manager for our clusters and this is the error we receive. 
.spec.template.spec.containers[name="grafana"].ports: duplicate entries for key [containerPort=3000,protocol="TCP"] 

snippet from container definition in the deployment:
ports:
            - name: service
              containerPort: 3000
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP

### Version

```prose
istioctl version
client version: 1.12.2-asm.0
control plane version: 1.12.4
data plane version: 1.12.4-asm.1 (44 proxies)

kubectl version --short
Client Version: v1.21.4
Server Version: v1.21.9-gke.1002
```

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/36183#pullrequestreview-812754403
