### ISSUE TITLE
proxy: auto sync envoy files

### ISSUE THREAD

**Issue by lambdai** [istio/istio#38406]
When proxy is built via bazel, envoy is a major and volatile dependency.
Per bazel rule, the dependencies (mostly WORKSPACE file) of dependencies is not auto imported.
https://docs.bazel.build/versions/main/external.html#transitive-dependencies

It means proxy need to upgrade the WORKSPACE accordingly, and the WORKSPACE referenced functions, definitions, datafiles, etc

Ideally we sync the envoy base, and maintain a small patch. 

The patch bundle is located at https://github.com/istio/proxy/tree/master/bazel

The sync execution script is https://github.com/istio/proxy/blob/master/scripts/update_envoy.sh

We need to organize better and reduce the manual sync

**Comment by zirain** [comment]
not stale

**Comment by zirain** [comment]
xref: https://github.com/istio/proxy/pull/5093
