### ISSUE TITLE
istioctl install --set configure is installing profile again

### ISSUE THREAD

**Issue by rogerex** [istio/istio#38414]
### Bug Description

When trying to configure an existing istio in k8s, command is trying to install everything again:
`istioctl install --set meshConfig.defaultConfig.tracing.zipkin.address=my-server.svc:9411
This will install the Istio 1.13.2 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) `

### Version

```prose
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (48 proxies)
----
Client Version: v1.19.1
Server Version: v1.22.6
```

**Comment by zirain** [comment]
the defaule value of profile is `default`, you'd install via an `IstioOperator`  config file with `istioctl install -f <istiooperator.yaml>`

**Comment by rogerex** [comment]
Same result using istio operator yml file
`istioctl install -f istio-operator.yml` 
`This will install the Istio 1.13.2 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N)`

**Comment by zirain** [comment]
are the pods re-install ?

**Comment by rogerex** [comment]
Only istio ingress
`istio-ingressgateway-f8bddc7bd-xcbdq   1/1     Running   0              10h`
I did 2 times this operation already and I did not get broken my env again, maybe we should change the message when configuring
