### ISSUE TITLE
EnvoyFIlter listener math support multi-port numbers

### ISSUE THREAD

**Issue by YanwxTech** [istio/istio#38412]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, only a single port number is supported for envoyfilter listener matching. If multi-port numbers use the same filter config, I need to configure one for each port number. Use envoy.extensions.filters.http.lua.v3.Lua to extend envoyfilter, each file has a lot of duplicates, only the ports are different.

**Describe alternatives you've considered**
The alternative is to support referencing lua code as a data source, and only one lua code needs to be written.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by howardjohn** [comment]
If we are going to do this we should make it generic to EnvoyConfigObjectMatch being a repeated value

**Comment by howardjohn** [comment]
I don't think we have plans to extend this
