### ISSUE TITLE
Seems Istio metrics does not include liveness/ readiness

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#38426]
### Bug Description

Seems Istio metrics does not include liveness/ readiness. This is not friendly with flagger.
Is the liveness/ readiness checking sending from inject proxy? why it is not showed in metrics? 
Or any parameter to include these part metrics.

Thanks.

### Version

```prose
Istio 1.13.2
k8s 1.22
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by johnzheng1975** [comment]
Use below to query prometheus:
sum(rate(istio_requests_total{reporter="source",destination_workload_namespace=~"onecloud-dev",destination_canonical_service="golang-try02-quickstart-primary",response_code!~"5.*"}[1m]))

If I call the health, in the **injected istio-proxy**，the upper return value is **0**.
```
istio-proxy@golang-try02-quickstart-primary-6f77877f8-sbgsw:/$ curl localhost:8080/ping -v
< HTTP/1.1 200 OK
```

If I call the health, **from other pods**，the upper return value is **not 0**.
```
root@nginx:/# curl golang-try02-quickstart.onecloud-dev/ping
< HTTP/1.1 200 OK
```

**Comment by howardjohn** [comment]
Calls in localhost if the proxy container do not get proxied at all so that is expected. Kubernetes health checks are also intentionally not included in metrics

**Comment by johnzheng1975** [comment]
Got it. thanks.
