### ISSUE TITLE
[Multi-Cluster Discovery] Pilot Starts Regardless of Failure to Load Multi-Cluster Context

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#38440]
### Bug Description

Background:
- Rolling out a canary version update from 1.10.3 (with XDS_PROXY disabled) to 1.12.4 (with XDS_PROXY enabled)
- Encountered a scenario where 1.12.4 control planes eventually get into a state where they push empty endpoints to proxies. Restarting Istiod-1-12-4 mitigates the issue but it is not clear how to discern a cluster that truly has no healthy endpoints from one that has healthy endpoints but is encountering a bug.
- Running a multi-cluster setup with one local cluster and ~20-40 remote clusters being managed and setup via istio-remote-secret-. It previously appeared that this but only occurs when network connectivity is lost between the control plane and remote api server. We then encountered this bug when remote cluster count via istiod_managed_clusters{cluster_type="remote"} remains steady over the past 7d window.
- 1.12.4 pilots running in the same cluster with the same remote secrets setup can have different state. Since this bug is non-deterministic we have observed one affected pilot with the same remote cluster count missing all endpoints for a given remote cluster in localhost:8080/debug/endpointz while another pilot with the same setup will return the expected endpoints from the remote cluster when checking the debug endpoint.
- We have a test workload that is restarted every 10 minutes and should generate an EDS PUSH as such; however, it seems that the remote cluster is no longer watched at all.

```
EDS: PUSH request for node:<POD_NAME>.<NAMESPACE_NAME> resources:200 size:<SIZE>kB empty:4 cached:<N-4>/<N>
```

Update:
It turns out this issue actually occurs on pilot start and is related to multi-cluster secret loading. Affected pilots are timing out while establishing communication to a remote API server and yet are still marked as healthy and never try to load the cluster context.
```
failed creating config configStore for cluster <CLUSTER_NAME> context deadline exceeded
```

This causes incorrect/asymmetric routes to be pushed to be pushed depending on which pilot a proxy connects to. It seems that a pilot should not be able to start without completely loading any multi-cluster configurations.

### Version

```prose
$ istioctl-1.12.4 version
client version: 1.12.4
istiod version: 1.12.4
$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.20.15-gke.1000
```

**Comment by Minh-Ng** [comment]
Found in 1.9.4 change notes:
```
Fixed istiod never becoming ready when it fails to read resources from clusters configured via remote secrets. After a timeout configured by PILOT_REMOTE_CLUSTER_TIMEOUT (default 30s), istiod will become ready without syncing remote clusters. The stat remote_cluster_sync_timeouts will be incremented when this occurs. ([Issue #30838](https://github.com/istio/istio/issues/30838))
```
along with https://github.com/istio/istio/issues/30838

Although it is not clear having asymmetric pilots is a better state at least the behavior is configurable. Two other issues have come to light as a result.

1) Multi-cluster state is not auto-recovering. When connecting to a remote cluster it is not retried at any point in time and requires a pilot restart to converge on the expected state.
2) The istiod_managed_clusters and debug endpoint /debug/clusterz marks remote clusters as "synced" even when a timeout has occurred. https://github.dev/istio/istio/blob/1.12.4/pkg/kube/multicluster/secretcontroller.go#L137

**Comment by hzxuzhonghu** [comment]
@stevenctl

**Comment by stevenctl** [comment]
This behavior is intentional. The assumption was that istiod should only block startup for the "local" cluster/kube client.

If the clients for the remote clusters can't be created or we fail to sync with their apiserver, we wait up to PILOT_REMOTE_CLUSTER_TIMEOUT and after that the server marks itself as ready. This avoids the connectivity to one cluster completely blocking istiod startup across clusters.

There may be an improvement we can make here to fine tune this a bit.

**Comment by hzxuzhonghu** [comment]
Are these two issues exist?

>1. Multi-cluster state is not auto-recovering. When a timeout occurs connecting to a remote cluster it is not retried at any point in time and requires a pilot restart to converge on the expected state.
>2. The istiod_managed_clusters and debug endpoint /debug/clusterz marks remote clusters as "synced" even when a timeout has occurred. https://github.dev/istio/istio/blob/1.12.4/pkg/kube/multicluster/secretcontroller.go#L137

**Comment by Minh-Ng** [comment]
Yeah its understood the behavior is intentional, but as described in the above post, its really unscrupulous default behavior especially for meshes which operate replicas across clusters. Especially once connectivity is restored in a network partition there is no convergence upon the expected state. 

The second point is that debugging the behavior is not so clear other than going back to the logs and finding that a multi-cluster secret was not loaded. The managed cluster count does not decrease and additionally the debug endpoint shows a "hacky" synced state when that is clearly not the case.

> Found in 1.9.4 change notes:
> 
> ```
> Fixed istiod never becoming ready when it fails to read resources from clusters configured via remote secrets. After a timeout configured by PILOT_REMOTE_CLUSTER_TIMEOUT (default 30s), istiod will become ready without syncing remote clusters. The stat remote_cluster_sync_timeouts will be incremented when this occurs. ([Issue #30838](https://github.com/istio/istio/issues/30838))
> ```
> 
> along with #30838
> 
> Although it is not clear having asymmetric pilots is a better state at least the behavior is configurable. Two other issues have come to light as a result.
> 
> 1. Multi-cluster state is not auto-recovering. When a timeout occurs connecting to a remote cluster it is not retried at any point in time and requires a pilot restart to converge on the expected state.
> 2. The istiod_managed_clusters and debug endpoint /debug/clusterz marks remote clusters as "synced" even when a timeout has occurred. https://github.dev/istio/istio/blob/1.12.4/pkg/kube/multicluster/secretcontroller.go#L137

**Comment by Minh-Ng** [comment]
> Are these two issues exist?
> 
> > 1. Multi-cluster state is not auto-recovering. When a timeout occurs connecting to a remote cluster it is not retried at any point in time and requires a pilot restart to converge on the expected state.
> > 2. The istiod_managed_clusters and debug endpoint /debug/clusterz marks remote clusters as "synced" even when a timeout has occurred. https://github.dev/istio/istio/blob/1.12.4/pkg/kube/multicluster/secretcontroller.go#L137

I'm happy to file a separate issue for cataloguing if it helps.

**Comment by stevenctl** [comment]
>  Especially once connectivity is restored in a network partition there is no convergence upon the expected state.

@hzxuzhonghu looks like we totally swallow errors that occur during init 

https://github.com/istio/istio/blob/53ae9db2d3595aa31d170d134701f6a05319fc3a/pkg/kube/multicluster/secretcontroller.go#L366-L369

I think we should bubble this error up to get it to retry. But I guess we need to make sure 1. we don't block the queue and 2. we don't retry over and over too quickly. 

if err {
  (or just time.After)
  delayQueue.Add(30 seconds, fn () { add back to controller queue )
}  


WDYT?

**Comment by hzxuzhonghu** [comment]
make sense
