### ISSUE TITLE
perhaps we can discuss the conditions for initializing the kubeclient ?

### ISSUE THREAD

**Issue by believening** [istio/istio#38444]
https://github.com/istio/istio/blob/5645dec7fbb67e3ef0bb68a0a074fdbd0b6b98d0/pilot/pkg/bootstrap/server.go#L573

In our scenario, we need to deploy istio in a k8s cluster and get the configuration objects including all istio crd from an mcp server by configuring MeshConfig.ConfigSources . In addition microservices deployed in the same k8s cluster will register themselves with other service registry instead of using the k8s native service, and we will set --registries to "". At this point, pilot will not initialize the kubeclient, but we do need it, for example we need mutatingwebhook to inject sidecar.

Perhaps we can discuss the conditions for initializing the kubeclient.

**Comment by believening** [comment]
Creating a kubeclient is a relatively early action in the timeline. Currently, istio relies on the value of PilotArgs and the MeshConfig parsed from PilotArgs.MeshConfigFile to determine if a kubeclient needs to be created, and potentially on the runtime context including environment variables.

I found the [issue12126](https://github.com/istio/istio/issues/12126) while looking for information about istio without k8s, and combined with the description in the istio about page: [Istio's control plane runs on Kubernetes](https://istio.io/latest/about/service-mesh/#what-is-istio), is there almost no scenario where it doesn't depend on a kubeclient?

**Comment by believening** [comment]
In addition, panic is triggered when there is no kubeclinet and SHARED_MESH_CONFIG is set and an existing PilotArgs.MeshConfigFile is specified. I am using version 12.0.

https://github.com/istio/istio/blob/2f645a7c4411159121cc43aafbc45f7a3e02101d/pilot/pkg/bootstrap/mesh.go#L58-L67
https://github.com/istio/istio/blob/2f645a7c4411159121cc43aafbc45f7a3e02101d/pkg/kube/configmapwatcher/configmapwatcher.go#L59

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x237a3e2]

goroutine 1 [running]:
istio.io/istio/pkg/kube/configmapwatcher.NewController({0x0, 0x0}, {0xc00000a0ce, 0xc}, {0xc00007a103, 0x13}, 0xc00151c480)
        istio.io/istio/pkg/kube/configmapwatcher/configmapwatcher.go:60 +0x2e2
istio.io/istio/pkg/config/mesh/kubemesh.AddUserMeshConfig({0x0, 0x0}, {0x335ee70, 0xc0014e10e0}, {0xc00000a0ce, 0xc}, {0x2e4d3c5, 0x4}, {0xc00007a103, 0x13}, ...)
        istio.io/istio/pkg/config/mesh/kubemesh/watcher.go:74 +0x117
istio.io/istio/pilot/pkg/bootstrap.(*Server).initMeshConfiguration(0xc000eead00, 0xc000a60840, {0x33bac38, 0xc0007ef530})
        istio.io/istio/pilot/pkg/bootstrap/mesh.go:68 +0x634
istio.io/istio/pilot/pkg/bootstrap.NewServer(0xc000a60840, {0x0, 0x0, 0x0})
        istio.io/istio/pilot/pkg/bootstrap/server.go:237 +0xb45
istio.io/istio/pilot/cmd/pilot-discovery/app.newDiscoveryCommand.func2(0xc000ee8f00, {0xc0008a4180, 0x8, 0x8})
        istio.io/istio/pilot/cmd/pilot-discovery/app/cmd.go:92 +0x4e
github.com/spf13/cobra.(*Command).execute(0xc000ee8f00, {0xc0008a4100, 0x8, 0x8})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ee8c80)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        istio.io/istio/pilot/cmd/pilot-discovery/main.go:27 +0x25
```

**Comment by hzxuzhonghu** [comment]
good catch, there is a conflict, i think no test capture this either

**Comment by believening** [comment]
Unfortunately this issue was closed automatically. I'll add a few more things.

We also use istio as ca in our scenario, which means that the root certificates generated by istio need to be spread to the cluster, which is the responsibility of the namespacecontroller. Unfortunately, the namespacecontroller is started as part of the k8s service controllers, which is not started due to the parameter configuration `--registries=""` .

``` golang
// https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/server.go#L1086
func (s *Server) initControllers(args *PilotArgs) error {
        // ...
	if err := s.initServiceControllers(args); err != nil {
        // ...
}

// https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/servicecontroller.go#L52
func (s *Server) initServiceControllers(args *PilotArgs) error {
        // ...
	for _, r := range args.RegistryOptions.Registries {
                // ...
		case provider.Kubernetes:
			if err := s.initKubeRegistry(args); err != nil {
				return err
			}
        // ...
}

// https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/servicecontroller.go#L86
func (s *Server) initKubeRegistry(args *PilotArgs) (err error) {
        // ...
	s.multiclusterController.AddHandler(kubecontroller.NewMulticluster(args.PodName,
                // ...
		s.shouldStartNsController(),
        // ...
}
```

Shouldn't we separate namespacecontroller from k8s-service-controllers? For config and service, the pilot does "discovery", and for sidecar-inject or proliferation root certificates, the pilot does "management".

**Comment by believening** [comment]
In addition, a logical error:

- `isCADisabled()` retrun `true`, ` shouldStartNsController()` return `true`
- `features.PilotCertProvider == constants.CertProviderKubernetes`, `isCADisabled()` retrun `true`
- `features.PilotCertProvider == constants.CertProviderKubernetes `, ` shouldStartNsController()` return false

```
func (s *Server) shouldStartNsController() bool {
	if s.isCADisabled() {
		return true
	}
	if s.CA == nil {
		return false
	}

	// For Kubernetes CA, we don't distribute it; it is mounted in all pods by Kubernetes.
	if features.PilotCertProvider == constants.CertProviderKubernetes {
		return false
	}
	// For no CA we don't distribute it either, as there is no cert
	if features.PilotCertProvider == constants.CertProviderNone {
		return false
	}

	return true
}

// isCADisabled returns whether CA functionality is disabled in istiod.
// It returns true only if istiod certs is signed by Kubernetes or
// workload certs are signed by external CA
func (s *Server) isCADisabled() bool {
	if s.RA == nil {
		return false
	}
	// do not create CA server if PilotCertProvider is `kubernetes` and RA server exists
	if features.PilotCertProvider == constants.CertProviderKubernetes {
		return true
	}
	// do not create CA server if PilotCertProvider is `k8s.io/*` and RA server exists
	if strings.HasPrefix(features.PilotCertProvider, constants.CertProviderKubernetesSignerPrefix) {
		return true
	}
	return false
}
```

**Comment by believening** [comment]
> Unfortunately this issue was closed automatically. I'll add a few more things.
> 
> We also use istio as ca in our scenario, which means that the root certificates generated by istio need to be distributed to the cluster, which is the responsibility of the namespacecontroller. Unfortunately, the namespacecontroller is started as part of the k8s service controllers, which is not started due to the parameter configuration `--registries=""` .
> 
> ```go
> // https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/server.go#L1086
> func (s *Server) initControllers(args *PilotArgs) error {
>         // ...
> 	if err := s.initServiceControllers(args); err != nil {
>         // ...
> }
> 
> // https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/servicecontroller.go#L52
> func (s *Server) initServiceControllers(args *PilotArgs) error {
>         // ...
> 	for _, r := range args.RegistryOptions.Registries {
>                 // ...
> 		case provider.Kubernetes:
> 			if err := s.initKubeRegistry(args); err != nil {
> 				return err
> 			}
>         // ...
> }
> 
> // https://github.com/istio/istio/blob/bb781decd5dbb2492bd0b90bd6b0273fba8c0b0e/pilot/pkg/bootstrap/servicecontroller.go#L86
> func (s *Server) initKubeRegistry(args *PilotArgs) (err error) {
>         // ...
> 	s.multiclusterController.AddHandler(kubecontroller.NewMulticluster(args.PodName,
>                 // ...
> 		s.shouldStartNsController(),
>         // ...
> }
> ```
> 
> Shouldn't we separate namespacecontroller from k8s-service-controllers? For config and service, the pilot does "discovery", and for sidecar-inject or proliferation root certificates, the pilot does "management".

[pr 40555](https://github.com/istio/istio/pull/40555) showed an experimental implementation that pilot does "management" for sidecar-inject and proliferation root certificates.
