### ISSUE TITLE
Support in-mesh url in JwksUri

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#38469]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In the current version of Istio the istiod is not istio-injected and hence cannot connect to in-mesh URL for retrieving jwks (e.g. ServiceEntry host or service available in another cluster that is in the same mesh). I would like to know whether it is feasible to support this use case.

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
To workaround this issue (connecting to in-mesh URL for retrieving jwks), I am trying the following solutions:
- create a proxy pod in the same cluster where the istiod control plane sits, let the pod proxy the jwks endpoint in mesh
- expose the jwks endpoint in a Gateway in the control plane cluster

Any suggestion on the best practice to achieve this?

**Comment by ramaraochavali** [comment]
If you are using RequestAuthentication, you can set `PILOT_JWT_ENABLE_REMOTE_JWKS ` https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars to true and configure a mesh cluster. Then Istio proxy connects to that cluster via mesh. Istiod does not get key in that case.

https://github.com/istio/istio/blob/3df2ccf2552374d6e7efa9f9a11c714d78bbc2a7/tests/integration/security/testdata/requestauthn/remote.yaml.tmpl - see this example

**Comment by ethernoy** [comment]
@ramaraochavali Thx for your prompt reply! have a follow-up question: the jwks provider in my setup is not sitting in the same cluster as the ingress gateway, the consumer of the jwks. To access the jwks provider, the request needs to have a special header which is normally assigned in a virtual service. In this case, how should I configure the ingress gateway to connect to this remote jwks provider using in mesh url and with setup in the virtual service?

**Comment by ramaraochavali** [comment]
> I have tried to create a virtual service matching the host of the jwks provider, but the ingress gateway seems does not make use of the virtual service when connecting to the provider on its own.

Yes. Ingress gateway does not use virtual service when connecting to mesh cluster. It just makes call to that cluster. We can not add any special headers. I can not think of any better solution for your usecase.

**Comment by ramaraochavali** [comment]
> From my testing, seems the istio-proxy container does not refer to virtual service when connecting to in-mesh jwks url, but does refer to the same virtual service when serving downstream application. 

I meant in the context of remote jwks invocation via mesh cluster, it doest not use virtual service. It is a direct call.

**Comment by ethernoy** [comment]
> > From my testing, seems the istio-proxy container does not refer to virtual service when connecting to in-mesh jwks url, but does refer to the same virtual service when serving downstream application.
> 
> I meant in the context of remote jwks invocation via mesh cluster, it doest not use virtual service. It is a direct call.

I have configured Istio successfully following your advice. Thank you so much for your help!

**Comment by Hronom** [comment]
For those who appear here - set `PILOT_JWT_ENABLE_REMOTE_JWKS` to `true` helped to resolve the issue.
https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars
