### ISSUE TITLE
Add support for TCP_USER_TIMEOUT socket options for envoy clusters

### ISSUE THREAD

**Issue by adams-shaun** [istio/istio#38476]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The motivating factor is well described in https://github.com/istio/istio/issues/33466

The issue described above and what we have experienced relates to gRPC streaming workloads.  When envoy is proxying a connection and the upstream host dies ungracefully (could be OOM, segfault, node power down, whatever) and envoy has written unACK'd data to the socket, many platform kernels will begin TCP retransmission steps which could leave the socket (to a dead endpoint) open for ~15 minutes.  There is a good writeup on this here: https://www.evanjones.ca/tcp-connection-timeouts.html

https://github.com/istio/istio/issues/33466#issuecomment-863988971 states that application-level pings (such as H2 ping) should be implemented to detect half-closed connections.  This type of configuration needs to be implemented on both the client and server side (grpc-go servers will by default only allow one such request per 5 minute period) and may not be feasible for all users.

In our particular use case, gRPC traffic is originating from the sidecar proxy (for example https://github.com/envoyproxy/envoy/blob/1575185d14abc3bc508ce5a6ba45422393322551/source/extensions/access_loggers/grpc/grpc_access_log_impl.h).  On ungraceful termination of the upstream endpoint, we have observed the sockets to remain open for ~15 minutes which results in a large amount of data accumulating in send buffers that is eventually lost.  In some scenarios, this can result in the proxy sidecar being OOM killed.

The TCP_USER_TIMEOUT socket option works well for limiting retransmission times.  Envoy has a rudimentary API for setting this option:

```apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sampleoptions
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        name: "outbound|12345||foo.ns.svc.cluster.local"
    patch:
      operation: MERGE
      value:
        upstream_bind_config:
          source_address:
            address: "0.0.0.0"
            port_value: 0
            protocol: TCP
          socket_options:
          - name: 18
            int_value: 10000
            level: 6
```

I would like to propose extending the istio/api to provide a more usable interface for this option.  For example:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  tcp:
    tcpKeepAlive:
    tcpUserTimeout: <Duration>
```

If there is some general agreement on this, I would be happy to open the PRs for istio/api and istio/istio.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jacob-delgado** [comment]
Another option would be for us to change these options (or add an environment variable) for HTTP and/or GRPC connections.

**Comment by hzxuzhonghu** [comment]
https://postgrespro.com/list/thread-id/2521183   [Wrong configuration of tcp_user_timeout can terribly affects tcp_keepalives mechanism]

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/issues/40397

**Comment by labilezhu** [comment]
I get much meaningful info from this issue. Thanks. But I have a small question here:

I think what you are talking about is TCP `Half-Open` connections. Not `Half-Closed` connections. I am sorry, maybe I am just a nerd. 

What I ref:
- https://en.wikipedia.org/wiki/TCP_half-open
- https://www.excentis.com/blog/tcp-half-close-cool-feature-now-broken
- [TCP/IP Illustrated Vol1]
