### ISSUE TITLE
Istio-operator not working on Mac m1

### ISSUE THREAD

**Issue by vince-0202** [istio/istio#38471]
### Bug Description

I try to install istio on my mac m1 by istio-operator,but it doesn't seems to work.

![Snipaste_2022-04-20_15-50-50](https://user-images.githubusercontent.com/48322565/164179071-e5e96932-bf64-4022-874c-9bf047f2c07f.jpg)
![Snipaste_2022-04-20_15-51-37](https://user-images.githubusercontent.com/48322565/164179109-1dc59bb1-4936-40ed-be1c-b1ae671e0b26.jpg)

And I can't open the log of istio-operator.

![Snipaste_2022-04-20_15-57-47](https://user-images.githubusercontent.com/48322565/164183779-30fcf64e-50be-4c3b-9a64-491fd347766e.jpg)

### Version

```prose
% istioctl version
no running Istio pods in "istio-system"
1.12.4
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by vince-0202** [comment]
> arm 上支持 istioctl，但 arm 集群上不支持 istio。支持有望很快到来。有关一些讨论，请参阅#36762。

Thanked your replay.
Hope to use istio on M1 soon

**Comment by zirain** [comment]
you can try https://github.com/querycap/istio, but I'm not 100% it will work.

**Comment by vince-0202** [comment]
> you can try https://github.com/querycap/istio, but I'm not 100% it will work.

Thx , i will try

**Comment by EamonKeane** [comment]
Confirm querycap istio builds works for me. An option in conjunction with `capistio`, `kind` and `docker-for-mac` is to add this patch so ingress/egress gateways get scheduled.

`kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "kubernetes.io/arch=amd64"`
