### ISSUE TITLE
Default config should intercept only cluster traffic, and not intercept egress traffic

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3849]
If kube-apiserver can expose an API so we can programmatically obtain
--service-cluster-ip-range (ServiceClusterIPRange) and --cluster-cidr  (ClusterCIDR), we can have the automatic injection call that API and inject the correct includeIPRanges.

At a minimum, Istio should document clearly what users need to do to disable interception of egress traffic.

**Comment by ayj** [comment]
Disabling interception of egress traffic is documented at https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly. It includes specific instructions to find the ServiceClusterIPRange and ClusterCIDR for IBM, GKE, and ACS.

If we can assume ServiceClusterIPRange and ClusterCIDR are fairly static, we can patch them into the injection template ConfigMap when Istio is installed.

**Comment by ldemailly** [comment]
would help/fix #1422
see also now #3876

**Comment by andraxylia** [comment]
The kube APIs are not available.

Related to #6146
