### ISSUE TITLE
Add HA configuration for sidecar injector webhook 

### ISSUE THREAD

**Issue by ayj** [istio/istio#3850]
All Istio components should have HA configuration including cpu/memory request/limits. The sidecar injector webhook is no different, as it sits in the pod creation path. Unavailability of the webhook delays creation of new pods. 

1) increase the number of replicas. This could be configurabled (via helm or `istioctl gen-deploy`). 

2) set cpu/memory request/limits for the sidecar injector pod to minimize wasted resources, particularly if webhook is highly replicated.

**Comment by ostromart** [comment]
This issue is alive and well, working its way up the pipeline.
