### ISSUE TITLE
Expose the op_timeout setting for the envoy.extensions.filters.network.redis_proxy.v3.RedisProxy filter

### ISSUE THREAD

**Issue by diranged** [istio/istio#38500]
**Describe the feature request**

Currently the `op_timeout` setting [is hard-coded to 5s](https://github.com/istio/istio/blob/f72bf28a23033983912c0facb705d83019fa3aef/pilot/pkg/networking/core/v1alpha3/networkfilter.go#L41-L42). By hard-coding this setting, it cannot be overridden with an `EnvoyFilter` (https://github.com/istio/istio/issues/38501), and yet it can also not be adjusted by the user.

Please implement a setting so that we can adjust this timeout in some way. I don't know where it should be configurable - but even in the simplest way, configuring it at the `istiod` level as an environment variable would be acceptable to us. We want to lower it to 500ms, not 5s.

**Describe alternatives you've considered**

I wanted to use an EnvoyFilter to patch this.. but it turns out that when Golang merges the pre-built filter and then my custom filter, the numbers are _added_ together. See https://github.com/istio/istio/issues/38501 for details.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
hardcode is bad, but redis support is leak in Istio. maybe add a `NodeMetadata`?
@howardjohn WDYT?
