### ISSUE TITLE
Dangerous global variable usage in istioctl

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38503]
Istioctl is full of global variables for things like kubeconfig, etc. This has caused a variety of issues in the past like:
* multiple calls to istioctl re-using the wrong variables between calls
* Parallel calls causing race conditions
* **connecting to users real clusters and performing mutation actions against their real cluster** in unit tests

As well as just generally being a bad practice.

We should refactor this a bit to follow best practices and avoid global mutable state.

**Comment by hanxiaop** [comment]
I think this can be closed. Most of the refactor work in the istioctl package is done. There may still be some work to do, but it won't relate to this issue.
