### ISSUE TITLE
cluster dropdown in Grafana Dashboard for multicluster

### ISSUE THREAD

**Issue by venkatk-25** [istio/istio#38525]
**Describe the feature request**
We have istio installed across multiple clusters in a multi-priomary setup and have configured prometheus according to [monitoring-multicluster-prometheus](https://istio.io/latest/docs/ops/configuration/telemetry/monitoring-multicluster-prometheus/). to aggregate in a central prometheus.

The default istio dashboards do not have the dropdown at cluster level and they seem to be built for a single cluster, which makes it very difficult to drill down to a single cluster for visualizing/debugging.

Istio already has cluster label attached to each metrics. It would be nice if we can add source and destination cluster labels in all relevant dashboards since we already have those labels for metrics, so it is easier to monitor/drill down to specific cluster.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by venkatk-25** [comment]
@zirain Are you planning to implement this ?

**Comment by zirain** [comment]
feel free to take over, I may be very busy in May.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/39081
