### ISSUE TITLE
Start Istio-proxy in the Docker which is running in the VM

### ISSUE THREAD

**Issue by vince-0202** [istio/istio#38521]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I want start Istio-proxy in the docker which is running in the VM，So that ,i can perform a health check on istio-Proxy by Docker.
Is it only allow directly start the the process of istio-proxy?I can't  get help in [istio.io ](https://preliminary.istio.io/latest/zh/docs/setup/install/virtual-machine/)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Comment by howardjohn** [comment]
You can run in a container and many do. However, we don't have official docs/testing/support for this so you will be a bit on the bleeding edge

**Comment by zirain** [comment]
there are some chinese doc in [huaweicloud](https://support.huaweicloud.com/bestpractice-asm/asm_bestpractice_0007.html) or [alicloud](https://help.aliyun.com/document_detail/214104.htm?spm=a2c4g.11186623.0.0.3500551e9L8BRD#task-2070460), hope those can give you some help.
