### ISSUE TITLE
istio-proxy sds  failed to warn certificate x509: certficate signed by unknown authority

### ISSUE THREAD

**Issue by spwangxp** [istio/istio#38541]
### Bug Description

environment：
  cluster 1 ---> external cluster
  cluster 2 ---> remote cluster
in single net

cluster 1 istiod in ns external-istiod 
cluster 2 deployed sleep app in ns sample
they all mount the same  root-ca.pem produced by the [script](https://github.com/istio/istio/blob/b55bf1a7debc0ce0081e91ad25694e839737512b/tools/certs/Makefile.selfsigned.mk), 
cacert secret are mounted by two cluster, kube-apiserver

injection works well:
cluster 2 (kube-apiserver(injection))--->cluster 1 svc(nodePort) ---> cluster 1 istiod
the sleep app in cluster 2 is inject correctly by cluster 1. 
```sh
[root@master0 ~]# kubectl -n sample get po
NAME                             READY   STATUS    RESTARTS   AGE
helloworld-v1-776f57d5f6-cr98b   1/2     Running   0          42h
sleep-557747455f-fchqr           1/2     Running   0          43m
```
but as shown above, the sidecar istio-proxy cannot running, no matter if i disabled the PeerAuthentication in ns external-istiod(cluster1, cluster2)
istio-proxy logs 
![image](https://user-images.githubusercontent.com/24298044/164955094-cef3229c-595e-488b-95a3-1dc105946059.png)

### Version

```prose
[root@w istio-remote]# istioctl version
client version: 1.12.6
control plane version: 1.11.3
data plane version: 1.11.3 (1 proxies)
[root@w istio-remote]# kubectl version --short --context=local(external-cluster)
Client Version: v1.19.8
Server Version: v1.19.8
[root@w istio-remote]# kubectl version --short --context=k8s-17-77(remote cluster)
Client Version: v1.19.8
Server Version: v1.19.8
```

**Comment by yhuanghamu** [comment]
@lei-tang @shankgan Could you take a look?

**Comment by lei-tang** [comment]
Which installation guide did you use to install and configure your mesh?

**Comment by spwangxp** [comment]
[install guide](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#before-you-begin)
[cert generate guide](https://preliminary.istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)

step 1: generate certs based on [cert generate guide]
```shell
certs/
├── cluster1
│   ├── ca-cert.pem
│   ├── ca-key.pem
│   ├── cert-chain.pem
│   └── root-cert.pem
├── cluster2
│   ├── ca-cert.pem
│   ├── ca-key.pem
│   ├── cert-chain.pem
│   └── root-cert.pem
├── makefile # is istio official makefile
│   ├── common.mk
│   ├── Makefile.k8s.mk
│   └── Makefile.selfsigned.mk
├── mtls.yaml
├── root-ca.conf
├── root-cert.csr
├── root-cert.pem
├── root-cert.srl
└── root-key.pem
```

step 2: mount certs/cluster1 cert for both `remote-cluster` and `external-cluster`, make sure it trust by all kube-apiserver( that's why sidecar injection succeed).
no matter if i mount cluster 2/**pem   or cluster1/**pem to remote-cluster actually, so just mount the same certs  cluster1/**pem in both cluster for simplifies.
```shell
kubectl --context=${EXTERNAL_CLUSTER_CONTEXT} create secret generic cacerts -n external-istiod --from-file=certs/cluster1/ca-cert.pem --from-file=certs/cluster1/ca-key.pem --from-file=certs/cluster1/root-cert.pem --from-file=certs/cluster1/cert-chain.pem

# create ns  sample  for test first
kubectl --context=${REMOTE_CLUSTER_CONTEXT} create secret generic cacerts -n sample--from-file=certs/cluster1/ca-cert.pem --from-file=certs/cluster1/ca-key.pem --from-file=certs/cluster1/root-cert.pem --from-file=certs/cluster1/cert-chain.pem
```

step 3:  follow the picture( in the install guide), but i skipped create `gw, dr, vs` to expose istiod in `external-cluster`, but expose istiod by change the  svc istiod to `NodePort`. btw, u should make the `mutatingwebhookconfigurations`  is right in both cluster, so sidecar inject succeed in `remote-cluster` by `external-cluster`. 
```shell
service:
  ports:
  - name: status-port
    nodePort: 31021
    port: 15021
    targetPort: 15021
  - name: tls-xds
    nodePort: 31012
    port: 15012
    targetPort: 15012
  - name: tls-webhook
    nodePort: 31017
    port: 15017
    targetPort: 15017
  type: NodePort
```
![image](https://user-images.githubusercontent.com/24298044/165425459-00dd8473-4935-4c73-b8c9-531b068e5fcf.png)

**Comment by spwangxp** [comment]
the error log in istio-proxy seems reported by https://github.com/istio/istio/blob/125f7ab997982bb0306c57f7858a855223e9abb1/security/pkg/nodeagent/caclient/providers/citadel/client.go#L108

**Comment by lei-tang** [comment]
For diagnosis purpose, if you only follow the [install guide](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#before-you-begin), will the problem occur?

**Comment by spwangxp** [comment]
yes, and the sidecar will not be inject.

**Comment by lei-tang** [comment]
Thanks for the clarification! When you only follow the [install guide](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#before-you-begin), at which step do you encounter the problem? 
cc @frankbu

**Comment by spwangxp** [comment]
thx for your patience, @lei-tang @yhuanghamu 
would you take a look on this?   @frankbu
when  i deploy an sample app in remote-cluster,  the remote-cluster kube-apiserver cannot connect to the istiod which in external-cluster

**Comment by spwangxp** [comment]
i've tried the [guide](https://preliminary.istio.io/latest/docs/setup/install/multicluster/primary-remote/), failed too. compared the arch with the install guide shown above, it's so similar, but according https://github.com/istio/istio/issues/27420, it's still unresolved, is
anything i missed?

test on the original cluster showed in `Version`
