### ISSUE TITLE
Can't get the target port from the serviceentry generated by the xds api generator

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#38554]
### Bug Description

Can't get the target port from the service entry generated by the xds API generator. The target port is not set in the code.

https://github.com/istio/istio/blob/b55bf1a7debc0ce0081e91ad25694e839737512b/pilot/pkg/serviceregistry/serviceentry/conversion.go#L118

### Version

```prose
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (1 proxies), 1.10-dev (3 proxies), 65536.65536.65536 (1 proxies)

The latest version has this issue as well.
```

**Comment by zhlsunshine** [comment]
Hi @zhaohuabing, according to the comment, do you have any idea about the PR [here](https://github.com/istio/istio/pull/38634#discussion_r860913433)?
