### ISSUE TITLE
Support default empty jwks list when fail to accessing jwksUri

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#38551]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

the [JWTRule](https://istio.io/latest/docs/reference/config/security/jwt/#JWTRule) API of Istio enables istiod to grab remote jwks. However if the remote endpoint is not available when istiod starts and then an istio-injected pod using this JWTRule starts, the mentioned istio-proxy in the istio-injected pod fails to start with following error:

![image](https://user-images.githubusercontent.com/15870761/165071245-85bb5610-43e5-47ce-8a45-4696e6a3c8f3.png)

I guess this is because istiod cachees an invalid jwks response and tried to push this jwks to the proxy. There are nevertheless use cases that istio needs to be available before the jwks provider is available.

I suggest we add a field in JWTRule API that configures istiod to populate an empty jwks value if the jwks endpoint returns invalid result and there is no valid jwks in the cache.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I am happy to submit PR if somebody can briefly instruct me on where to do the modification :)

**Comment by howardjohn** [comment]
Is the expectation that you just stop authenticating?

**Comment by howardjohn** [comment]
Any update on the usage?

**Comment by howardjohn** [comment]
Right now we don't have enough to proceed on this, please feel free to re-open if there is some more information. Thanks!
