### ISSUE TITLE
telemetry api datadog configuration missing service name

### ISSUE THREAD

**Issue by BradErz** [istio/istio#38573]
### Bug Description

According to https://buf.build/envoyproxy/envoy/file/main:envoy/config/trace/v3/datadog.proto#L29 the `service_name` field of the datadog tracing provider must be configured. Otherwise the configuration will fail and new pods using the proxy will refuse to start with this error:
```
ADS:LDS: ACK ERROR istio-gateway-qkhm8.istio-system-2422 Internal:Error adding/updating listener(s) 0.0.0.0_32010: Proto constraint validation failed (DatadogConfigValidationError.ServiceName: value length must be at least 1 characters): collector_cluster: "outbound|8126||dd-agent.kube-system.svc.cluster.local"
```

It seems this is where we are currently creating the configuration for the datadog config:
https://github.com/istio/istio/blob/aeb0876637bfb819344d0ced3b822aa35cc7f5e8/pilot/pkg/networking/core/v1alpha3/tracing.go#L257-L262

And the `ServiceName` is not being set. 

It is quite strange that the datadog provider requires the service name to be set here as it seems the other providers do not actually seem to require this?

I assume we should use the same logic from here to set the `ServiceName`?
https://github.com/istio/istio/blob/aeb0876637bfb819344d0ced3b822aa35cc7f5e8/pkg/bootstrap/config.go#L307-L337

I guess the other solution would simply be allow the user to set this value when configuring the telemetry api? But it doesn't seem great to have to do that from a user experience as you would have to create a new resource for every deployment to set the service name correctly in the traces.

Im open to working on this issue and fixing it but would require some direction on what we would like to do and how. 

### Version

```prose
➜  istioctl version
kubectl version --shortclient version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (28 proxies)
➜ kubectl version --short
Client Version: v1.23.6
Server Version: v1.21.5-eks-bc4871b
```

### Additional Information

I cant include the output of the bug report but here you can find the relevant config and error log
```yaml
values:
  meshConfig:
    defaultProviders:
      tracing:
      - datadog
      extensionProviders:
      - datadog:
          port: 8126
          service: dd-agent.kube-system.svc.cluster.local # from reading the code i cant specify $(HOSTIP) here? :cry:
```

The logs from pilot show:
```
ADS:LDS: ACK ERROR istio-gateway-qkhm8.istio-system-2422 Internal:Error adding/updating listener(s) 0.0.0.0_32010: Proto constraint validation failed (DatadogConfigValidationError.ServiceName: value length must be at least 1 characters): collector_cluster: "outbound|8126||dd-agent.kube-system.svc.cluster.local"
```

**Comment by BradErz** [comment]
It seems like the skywalking envoy plugin is much smarter in the scenario where this value isn't specified?
https://github.com/envoyproxy/envoy/blob/03f23769d19e1baaf37fe52dcfe3f840429f9d06/api/envoy/config/trace/v3/skywalking.proto#L39-L44

Maybe its the datadog plugin in envoy which we should look at instead of this?

**Comment by eduardobaitello** [comment]
Is it possible to configure Datadog using `extensionProviders`, but using `$(HOSTIP)` instead of a service?

It seems best suited when running the agents as a Daemonset.

**Comment by zirain** [comment]
<img width="927" alt="image" src="https://github.com/istio/istio/assets/4354057/d4a27e3c-de5f-446a-bd26-89834a251ae2">
