### ISSUE TITLE
How can we get observability about ratelimiting ?

### ISSUE THREAD

**Issue by vk-98** [istio/istio#38590]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I am looking forward to having some visibility of the metric/logs the rate-limiting (https://github.com/envoyproxy/ratelimit) service is generating. Is there any way we can look into the rate-limiting more clearly?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
can you share more details about what you want?

**Comment by vk-98** [comment]
The Rate Limit Service(https://github.com/envoyproxy/ratelimit) generates some metrics based on domain and descriptors(https://github.com/envoyproxy/ratelimit#:~:text=rate%20limiting%20result.-,Statistics,-The%20rate%20limit). I am looking for if we are somehow able to use these metrics to form some dashboard. I am not very much sure, how we can do this.

**Comment by zirain** [comment]
https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#local-rate-limit

![image](https://user-images.githubusercontent.com/4354057/180588410-12f1ccc2-2fc9-4148-8385-86981f5a57ba.png)
