### ISSUE TITLE
istioctl install generates bad validatingwebhookconfiguration

### ISSUE THREAD

**Issue by frankbu** [istio/istio#38599]
### Bug Description

Installing a gateway using an empty profile [like this](https://istio.io/latest/docs/setup/install/external-controlplane/#enable-gateways) on a config cluster (with an external control plane) creates a `istiod-default-validator` `ValidatingWebhookConfiguration` using the injection URL (`<external-host>/inject/cluster=...`), instead of the validation URL (`<external-host>/validate`) for the `clientConfig.url`.

I think there are two problems here:

1. Creating a gateway using an empty profile should not trigger webhook generation.
2. The webhook needs to use the proper URL for the validator.

### Version

```prose
1.13.2
```

**Comment by litong01** [comment]
@frankbu struggled with this problem for quite few days myself. could not figure out why it does that. I had to generate the manifest then use `kubectl` to install, then it will be ok.
