### ISSUE TITLE
How can we configure route based local rate limiting with Istio?

### ISSUE THREAD

**Issue by vk-98** [istio/istio#38640]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
do you read this https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#local-rate-limit?

**Comment by vk-98** [comment]
Yeah I have read this, but this not covering the configuration to local rate limit based on routes.

**Comment by zirain** [comment]
right now, there's no first class API to do this.

**Comment by vk-98** [comment]
But it's mentioned here https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#:~:text=Alternatively%2C%20you%20can%20restrict%20it%20to%20a%20specific%20route. That this can be done.

Also, Is there any way to define the config for envoy like this https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#:~:text=Alternatively%2C%20you%20can%20restrict%20it%20to%20a%20specific%20route. via Istio?

**Comment by zirain** [comment]
you can use EnvoyFilter do that, not first class API .
