### ISSUE TITLE
Facing Connectivity issues in GRPC Calls ( Upstream connect error or disconnect/reset before headers ) after adding istio as sidecar

### ISSUE THREAD

**Issue by Avani231194** [istio/istio#38665]
Error : 

`\\"message\\\":\\\"14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: remote refused stream reset\\\",\\\"code\\\":14,\\\"metadata\\\":{},\\\"details\\\":\\\"upstream connect error or disconnect/reset before headers. reset reason: remote refused stream reset\\\"}\"}"}`

****Flow :**
App  1  --> Istio SideCar --> ALB ( TLS ) --> Istio SideCar ( App 2 ) --> App 2 

We tried couple of other flows as mentioned below, but facing the same issue.

App  1   --> ALB ( TLS ) --> Istio SideCar ( App 2 ) --> App 2 
App  1   -->  Istio SideCar --> ALB ( TLS )  --> App 2 

Tried to take TCP Dump on app, and we noticed at the time of issue there are some FIN packages that are being sent.

We are facing this issue only with GRPC calls.

**Below is the service file for reference :**

`  ports:
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001`

Istio Version: 1.9.2

**Comment by highwayliu** [comment]
i have met the same issue too.

**Comment by highwayliu** [comment]
你好，我是刘海伟，QQ 806864128，1310627032，微博 http://weibo.com/1688577641是华南理工09网络工程的学生，你的来信我已收到！请放心！！！

**Comment by highwayliu** [comment]
你好，我是刘海伟，QQ 806864128，1310627032，微博 http://weibo.com/1688577641是华南理工09网络工程的学生，你的来信我已收到！请放心！！！
