### ISSUE TITLE
istio/tools/setup_run and update_all out of date

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#3868]
Both scripts contain references to bazel artifacts.

**Comment by ldemailly** [comment]
yes, thanks ! I haven't had a chance to update the VM based scripts since bazel/mono repo changes broke them as I switched focus on K8s testing with the new script

Automation would help keep both set working

**Comment by ldemailly** [comment]
this came back as one of the swat team potential work items (to test on VMs also in addition to GKE/Blue)
