### ISSUE TITLE
Istio is not supported for ARM Architecturem Installation via helm fails

### ISSUE THREAD

**Issue by kadursandy** [istio/istio#38697]
I am using OCI(Oracle Cloud Infra) with OKE(Oracle Kubernestes engine) Deployed with 1.25 K8S version with 3 worker nodes with ARM processor/architecture. Each worker node has 6 ocpu and 96 GB memory. Not able to install Istio v1.13.3 chart version. 
The Istio pod goes to "CrashLoopBackoff".

steps to reproduce:
Login to K8S bastion host to connect to Kube cluster.
1. K8s installed with v1.25 (3 worker nodes with ARM based archi/processor)
2. configure kubectl, helm > 3.6
3. $ helm repo add istio https://istio-release.storage.googleapis.com/charts
$ helm repo update
$ kubectl create namespace istio-system
$ helm install istio-base istio/base -n istio-system
$ helm status istio-base
$ helm get all istio-base
$ helm install istiod istio/istiod -n istio-system --wait

From Istio community came to know there is no ARM based support. PLease correct me if my undertanding is not correct.

Events Message: "failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get [pods.metrics.k8s.io](http://pods.metrics.k8s.io/))"  --- unable to get cpu metrics ....not sure how to proceed with installation , is Istio Architecture specific

Kuberntes deployment with helm charts are affected. K8S version with lower works properly. Please suggest how to proceed. 
Error: pod/istiod-xxxxxxxxxxxx-xxxxxxx   0/1     CrashLoopBackOff

[ X] Docs
[X] Installation
[ X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by ericvn** [comment]
Currently, there is no ARM support for the Istio images. That support is coming. There are some earlier issues with additional information.

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/26652. thanks

**Comment by kadursandy** [comment]
Please let us know when there is official support for arm64? OCI OKE supports both arm64, x86_64(intel). There is a need for us to use arm64.
