### ISSUE TITLE
Resolve 1.14 regressions

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38694]
The following PRs have merged and introduced regressions. Creating a tracker issue with release blocker priority.

* [x] https://github.com/istio/istio/pull/38499
* [x] https://github.com/istio/istio/pull/38659. REVERT: https://github.com/istio/istio/pull/38863
* [x] https://github.com/istio/istio/issues/38676

**Comment by vikaschoudhary16** [comment]
As per our offline discussion, summarized [here](https://github.com/istio/istio/pull/38499#discussion_r863303031) for others, #38499 could be excluded from the above list. I am working on adding integration tests as well.

**Comment by lei-tang** [comment]
@vikaschoudhary16 As https://github.com/istio/istio/pull/38499 could be excluded from the above list, can you cross it off by clicking the mark on the left?

**Comment by vikaschoudhary16** [comment]
#38499 is reverted from the release branch, [release-1.14] Revert #38499 and #38702 . I am not able to click the box in the description.

**Comment by lei-tang** [comment]
Thank you, Vikas! I have clicked the box in the description.
