### ISSUE TITLE
Istiod memory leak with 1.13.3

### ISSUE THREAD

**Issue by JeffreyWa** [istio/istio#38716]
### Bug Description

Istiod memory and cpu consumption are growing continuously.
% k top po -n istio-system
NAME                                     CPU(cores)   MEMORY(bytes)
authservice-0                            1m           6Mi
cluster-local-gateway-64f58f66cb-vz2pd   27m          84Mi
istio-egressgateway-5c597cdb77-jdhv6     25m          70Mi
istio-ingressgateway-8d7d49b55-fjvvx     28m          76Mi
istiod-54c54679d7-9559c                  2826m        6149Mi

top - 00:46:48 up 14:45,  0 users,  load average: 3.43, 2.59, 2.91
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.9 us,  0.6 sy,  0.0 ni, 85.7 id,  0.0 wa,  0.0 hi,  0.4 si,  0.4 st
MiB Mem : 128845.1 total, 110897.2 free,   8045.7 used,   9902.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 119708.5 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                               
    1 istio-p+  20   0   10.1g   5.2g  66572 S 165.8   4.1   1413:06 pilot-discovery                                                                                                                       
   39 istio-p+  20   0    6104   3288   2776 R   0.3   0.0   0:00.01 top                                                                                                                                   
   29 istio-p+  20   0    2616    604    528 S   0.0   0.0   0:00.01 sh                                                                                                                                    
   35 istio-p+  20   0    2616    104      0 S   0.0   0.0   0:00.00 sh                                                                                                                                    
   36 istio-p+  20   0    4248   3552   2952 S   0.0   0.0   0:00.00 bash                                                                                                                                  

### Version

```prose
k8s version: 1.21.1
istio version: 1.13.3
kubeflow version: 1.5.0
```

**Comment by JeffreyWa** [comment]
BTW, I am testing in lab env. So there isn't traffic from outside.

**Comment by JeffreyWa** [comment]
k top po -n istio-system
NAME                                     CPU(cores)   MEMORY(bytes)
authservice-0                            1m           6Mi
cluster-local-gateway-64f58f66cb-vz2pd   21m          83Mi
istio-egressgateway-5c597cdb77-jdhv6     22m          71Mi
istio-ingressgateway-8d7d49b55-fjvvx     28m          77Mi
istiod-54c54679d7-9559c                  2044m        11428Mi

**Comment by howardjohn** [comment]
Can you get a heap profile? https://github.com/istio/istio/wiki/Analyzing-Istio-Performance? Maybe CPU as well since it looks high

**Comment by JeffreyWa** [comment]
[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz](https://github.com/istio/istio/files/8628356/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz)
[pprof.pilot-discovery.samples.cpu.002.pb.gz](https://github.com/istio/istio/files/8628359/pprof.pilot-discovery.samples.cpu.002.pb.gz)

**Comment by hzxuzhonghu** [comment]
How many services/pods do you have:?

**Comment by hzxuzhonghu** [comment]
seems it is related to status reporter @therealmitchconnors

**Comment by JeffreyWa** [comment]
Just installed kubeflow, no any other workloads.

**Comment by JeffreyWa** [comment]
k get po -n kubeflow
NAME                                                         READY   STATUS    RESTARTS   AGE
admission-webhook-deployment-7df7558c67-fr4ck                1/1     Running   0          40h
cache-deployer-deployment-6f4bcc969-pcssb                    2/2     Running   1          42h
cache-server-575d97c95-fnm9z                                 2/2     Running   0          42h
centraldashboard-79f489b55-mb5cb                             2/2     Running   0          42h
jupyter-web-app-deployment-5886974887-2n7gg                  1/1     Running   0          42h
katib-controller-58ddb4b856-9khm5                            1/1     Running   0          40h
katib-db-manager-d77c6757f-j7ckd                             1/1     Running   0          40h
katib-mysql-7894994f88-s824p                                 1/1     Running   0          40h
katib-ui-f787b9d88-nfhhw                                     1/1     Running   0          40h
kserve-models-web-app-5c64c8d8bb-rqhl4                       2/2     Running   0          40h
kubeflow-pipelines-profile-controller-5965fc757d-dshtn       1/1     Running   0          40h
metacontroller-0                                             1/1     Running   0          42h
metadata-envoy-deployment-7b847ff6c5-pwnrn                   1/1     Running   0          42h
metadata-grpc-deployment-f8d68f687-6wbxr                     2/2     Running   1          42h
metadata-writer-78fc7d5bb8-swgvs                             2/2     Running   1          40h
minio-5b65df66c9-mvptx                                       2/2     Running   0          40h
ml-pipeline-7bb5966955-hgdn6                                 2/2     Running   0          42h
ml-pipeline-persistenceagent-87b6888c4-df8xk                 2/2     Running   0          40h
ml-pipeline-scheduledworkflow-665847bb9-64fz7                2/2     Running   0          42h
ml-pipeline-ui-554ffbd6cd-gsm96                              2/2     Running   0          40h
ml-pipeline-viewer-crd-68777557fb-6sdrd                      2/2     Running   1          42h
ml-pipeline-visualizationserver-66c54744c-bl42d              2/2     Running   0          42h
mysql-f7b9b7dd4-tlzvr                                        2/2     Running   0          40h
notebook-controller-deployment-7474fbff66-6rmc6              2/2     Running   1          42h
profiles-deployment-5cc86bc965-kqlqc                         3/3     Running   1          40h
tensorboard-controller-controller-manager-5cbddb7fb5-p6brf   3/3     Running   2          40h
tensorboards-web-app-deployment-7c5db448d7-kg9kb             1/1     Running   0          40h
training-operator-6bfc7b8d86-29kk2                           1/1     Running   6          40h
volumes-web-app-deployment-87484c848-xm9nk                   1/1     Running   0          40h
workflow-controller-5cb67bb9db-9sxgb                         2/2     Running   2          42h

**Comment by hzxuzhonghu** [comment]
You can disable `PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING` in istiod, seems this is the cause

**Comment by JeffreyWa** [comment]
Below was the state after disabled this env-var and restarted the pod. Let's wait and see the subsequent result.
 
k top po -n istio-system
NAME                                     CPU(cores)   MEMORY(bytes)
authservice-0                            1m           6Mi
cluster-local-gateway-64f58f66cb-vz2pd   19m          83Mi
istio-egressgateway-5c597cdb77-jdhv6     16m          71Mi
istio-ingressgateway-8d7d49b55-fjvvx     19m          79Mi
istiod-594c55457-62m67                   347m         121Mi

**Comment by JeffreyWa** [comment]
No, my cluster has a low and stable workload, therefore, high CR churn rate is not the case. 
As a matter of fact, when I followed @hzxuzhonghu suggestion and disabled PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING, thing seems coming back to normal. 
So I am a little bit curious--Given it seems this issue has been reported in [Istio 1.6](https://github.com/istio/istio/issues/24521). Why is it still stubborn in Istio 1.13.3?

**Comment by taitelman** [comment]
yes, I can confirm that even istio 1.13.2 is leaking.
few observations:
first: istio-init container may use over 979MB (yes 1GB+) 
2nd: istio-proxy container will work normally for a day (i.e. 40MB) and then suddenly, out of the blue (on Saturday 3AM where there is no traffic) will jump to 230MB
![c-700e9b33-b4d8-4eb4-a62b-784131703262-srvapi-7f66886987-qwqh5 memory](https://user-images.githubusercontent.com/8079496/167298416-7201fdda-71bf-4bb5-ae5e-dca305828388.png)


3rd: istio-proxy container in some cases doesn't stop at 230MB (same pod as 2nd case) it keep spiking to 600MB (before it reaches the  ```sidecar.istio.io/proxyRamLimit``` I set and then crash)
![c-700e9b33-b4d8-4eb4-a62b-784131703262-srvapi-7f66886987-st4rp memory](https://user-images.githubusercontent.com/8079496/167298405-c966e319-e32e-424b-a9f3-5ceed3246ab7.png)

**Comment by nirvanagit** [comment]
Any updates on this one? Is this fixed in the latest version?

**Comment by howardjohn** [comment]
I think we should but would be great if we got someone to verify it fixes the real-world issue (and not just the microbenchmarks)

**Comment by nirvanagit** [comment]
Trying to understand, is memory leak not easily reproducible in a production cluster running 1.13?

**Comment by ramaraochavali** [comment]
> I think we should but would be great if we got someone to verify it fixes the real-world issue (and not just the microbenchmarks)

We are planning to verify that this week. I will update you on the issue.

**Comment by howardjohn** [comment]
@ramaraochavali did it fix? should we backport?

**Comment by ramaraochavali** [comment]
@howardjohn This did help but with RDS Cache the growth is still high. So we had to disable RDS cache.
