### ISSUE TITLE
unknown field "telemetry" in v1alpha1.globalconfig in istio 1.11

### ISSUE THREAD

**Issue by anuraagkonda** [istio/istio#38737]
Hi team,

We are trying to disable the telemetry for istio service mesh. We are following the example given in this repo here 
https://github.com/istio/istio/blob/release-1.11.7-patch/manifests/profiles/default.yaml. 
However the telemetry term is not known to global config. I also tried to see if there is a charts/global.yaml for istio 1.11 but couldn't find it in the repo.

Are there any current workarounds available to disable the telemetry using istiooperator cro ?

**Comment by dhawton** [comment]
https://github.com/istio/istio/blob/release-1.11.7-patch/manifests/profiles/default.yamll#L138 has a demo of how to configure telemetry (spec.values.global.telemetry). A small note, 1.11 is EOL as of March 25.

**Comment by anuraagkonda** [comment]
Tried the same configuration and it is working as expected. This could be a space error which cause the issue earlier.
