### ISSUE TITLE
istio.io is down

### ISSUE THREAD

**Issue by dehoward** [istio/istio#38736]
### Bug Description

![image](https://user-images.githubusercontent.com/52973358/166818144-e1f9df9f-4b6f-4b68-8fe5-3649298e76da.png)

reposting here for visibility ([original issue](https://github.com/istio/istio.io/issues/11270))

### Version

```prose
site
```

**Comment by howardjohn** [comment]
As far as we know this was a netlify outage that is resolved and we cannot control, so I think there is no action here. Thanks for reporting!
