### ISSUE TITLE
make the gateway chart behave like the gateways/istio-ingress chart

### ISSUE THREAD

**Issue by daveoy** [istio/istio#38735]
### Bug Description

im finding beetween the gateway chart and the gateways/istio-ingress chart the resulting deployed objects differ considerably. 

using the gateway chart the deployments dont start, complaining of missing sysctl values. even swapping out the securityContext and containerSecurityContext values in the gateway chart with those from a working deployment under the gateways/istio-ingress chart doesn't result in a deployment that can bind to ports 443 and 80 on the scheduled node.

really what im after is the ability to set `externalIPs` for the ingressgateway service. the Gateway chart exposes this but the gateways/istio-ingress chart does not. unless you can point me in the direction of a way to have this set in the gateways/istio-ingress chart?

### Version

```prose
istio-release 1.13.2
kubernetes 1.23
```

**Comment by morremeyer** [comment]
This is still an open issue. Can a team member please unstale it?

**Comment by zirain** [comment]
for people want to customize helm chart:
https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by daveoy** [comment]
Thanks for the doc link, I'll accept that the official answer from Istio is to use a post renderer which I noted in my PR for this issue is actually the way I worked around this shortcoming in the chart in the first place.

You're good to close this out and thanks again.

**Comment by morremeyer** [comment]
I agree with @daveoy when it comes to customized configuration.

However, in our case, using an Ingress Gateway as a Gateway is something very standard in Istio implementations and should in my opinion be supported by the official charts.

**Comment by zirain** [comment]
there're some contexts for this:
https://github.com/istio/istio/issues/39079#issuecomment-1135133605 

https://github.com/istio/istio/issues/39180#issuecomment-1142441351

if you really want something supported by official, you can write a design doc(like [this](https://docs.google.com/document/d/1qknaZqXItogEmROVnQD61144pEW1X47bEQraI5D52uY/edit?resourcekey=0-wHAgrakvVaMcnBm40bKuSg#heading=h.xw1gqgyqs5b)), come to join the WG meeting, share you ideas with the community.

**Comment by morremeyer** [comment]
@zirain Thanks for the input! I'll check those out. If the current policy is „the charts are what they are“, we'll likely look into creating our own chart.
