### ISSUE TITLE
Jaeger MTLS Mode for Apps outside the mesh

### ISSUE THREAD

**Issue by anders-swanson** [istio/istio#38755]
### Bug Description

In my cluster I have Istio, Jaeger (Jaeger must run in the mesh for security reasons), and Apps both inside and outside the Mesh. Istio should be configurable such that traces sent from:
1. Apps within the mesh
2. Apps outside the mesh
3. The Envoy sidecars themselves

As far as I know this is impossible. I have tried the following configuration:

- Jaeger in the mesh
- Istio configured to use Jaeger with ISTIO_MUTUAL tls settings
- PeerAuthentication PERMISSIVE specifically for Jaeger workloads
- PeerAuthentication is STRICT for all other mesh workloads.

With this configuration, apps inside and outside the mesh can send traces to Jaeger, which is great! However, now the traces from Envoy fail. I suspect this is a bug with Envoy/Istio, specifically the client that is trying to send traces from Envoy - PERMISSIVE MTLS for Jaeger should not break tracing from Envoy. 

Secondary to this, Envoy logging for tracing appears to be nonexistent. Setting the Envoy log level to debug provided no additional information on traces.

### Version

```prose
Istio/Istioctl : 1.11.4
K8s/Kubectl: 1.22
```

**Comment by anders-swanson** [comment]
Hi @sereneshikari , I haven't tried this setup recently, but if I remember correctly it was very similar to the ALPN filters as described here: https://github.com/istio/istio/issues/38720

**Comment by sereneshikari** [comment]
Thanks @anders-swanson, appreciate it!
