### ISSUE TITLE
[thrift][rds]Dose istio have any plan on support thrift rds?

### ISSUE THREAD

**Issue by pyrl247** [istio/istio#38786]
Since envoy1.22 release ,thrift-proxy support [trds](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/thrift_proxy/v3/thrift_proxy.proto#extensions-filters-network-thrift-proxy-v3-trds).Does istio have any plan on managing thrift traffic?

**Comment by howardjohn** [comment]
There are no current plans. https://github.com/aeraki-mesh/aeraki third party project does manage it
