### ISSUE TITLE
issue triage workflow - triaging process

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3879]
1. for new issue, we need to let people give their best guess on area, priority, and maybe initial assignment - to help pre-triage
1. we need to know which issues has been fully triaged and not yet - ie if the input is accepted and settled
1. we need to know which release an issue is targeted for
1. (optional) we need to know if an issue is actively worked on vs in a queue
1. we need all this with minimal extra work / trashing in github changes, notification etc, in particular no mass update of existing issues

most tracking system have an "accepted" field for the last point, as well as separate fields the owners set from fields the submitter sets

ideas welcome!

**Comment by sakshigoel12** [comment]
Jasmine might be the best person to define this in detail once she is back but here are my thoughts:
1. Agree and that is encouraged in bug template. Additionally, we could also have **on-call add area labels** as apart of pre-triage? Anything more we can do here?
2. Maybe we can add one more label (yes :( but github doesn't have a great interface) (**kind/triaged**?). 
3. We have **"Releases" field** which should be used. 1 month buckets are decent size to have high confidence on what is accomplishable so we should only add items that have **high confidence to land or which block the release**. It should not be wish list of items. 
4. Unfortunately, github seems to not have differentiated between assigned and accepted. So maybe we **use assigned for the ones assignee has accepted to finish in next 3 months**?

Another issues I think we need to fix is -- granularity. We probably need highlevel epics for each feature in go/istio-schedule that can explain users what all needs to complete to consider a feature done. 

Additionally, nice to have would be a bot to nag people to triage issues and add all the correct labels. I know k8s has this but we would need eng-prod bandwidth to implement one for us.

**Comment by ldemailly** [comment]
stale bot, the real mvp :)
[more seriously it's quite sad to see all those issues getting auto closed whether or not they are resolved]
