### ISSUE TITLE
EnvoyFilterUsesReplaceOperation new flaky test

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#38806]
Root cause https://github.com/istio/istio/pull/38389

Examples https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1523665851696287744

See https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes

**Comment by nmittler** [comment]
Ah, you beat me to it. Can we roll back for now?

**Comment by howardjohn** [comment]
Still broken with https://github.com/istio/istio/pull/38862
