### ISSUE TITLE
Helm multicluster deployment artifacts missing on ArtifactHub

### ISSUE THREAD

**Issue by lucarmcarlos** [istio/istio#38811]
### Bug Description

Some properties are needed by multicluster deployment and the gateway chart published doesn't support it, but the chart under gateways directory on GitHub supports. 

Some examples are injectionTemplate and global.network properties that are required for multicluster and the existing chart doesn't support.

It would be nice to have ingress-gateway chart on ArtifactHub 

### Version

```prose
Latest
```

**Comment by howardjohn** [comment]
Multinetwork is supported: https://artifacthub.io/packages/helm/istio-official/gateway#multi-network-vm-gateway.

Injection template is not needed as its the only method for that chart.

istio-ingressgateway chart is the legacy chart and intentionally not published.
