### ISSUE TITLE
Ingress gateway and Egress gateway pod are consuming too much memory

### ISSUE THREAD

**Issue by JonathanLachapelle** [istio/istio#38827]
### Bug Description

We have a large mesh with a lot of applications and a lot of ingress gateway and egress gateway.

For all the envoy proxy sidecar we use the sidecar ressource to restrict the mesh to only what's needed so the size of each envoy proxy is around 55meg, not too bad.

For all of our ingress and egress pods, the size is around 500 meg per pod. We have around 600 of these in our cluster, it's quite big.

Is there any way to restrict the size of the mesh for these like we do the envoy proxy in the sidecar?

If not any other way to optimise the memory consumption in a large mesh?

Thank you

### Version

```prose
Istioctl version
client version: 1.13.3
control plane version: 1.12.6
data plane version: 1.12.6 (2247 proxies)

kubectl version
Client Version: v1.22.5
Server Version: v1.21.9-eks-0d102a7
```

**Comment by JonathanLachapelle** [comment]
> this may give you some help https://istio.io/latest/docs/reference/config/networking/sidecar/?

This seem to address only sidecar attached to workload, I want to optimise istio ingress gateway and egress gateway.

Thank you

**Comment by zirain** [comment]
> > this may give you some help https://istio.io/latest/docs/reference/config/networking/sidecar/?
> 
> This seem to address only sidecar attached to workload, I want to optimise istio ingress gateway and egress gateway.
> 
> Thank you

https://github.com/istio/istio/blob/5a65f434fa472d34945ab3f65e65e2c7172af4a2/pilot/pkg/features/pilot.go#L82 you can try this if you have some issue with too much cluster
