### ISSUE TITLE
Envoy sidecar intercepting TCP traffic

### ISSUE THREAD

**Issue by juicemia** [istio/istio#38820]
### Bug Description

We have a service that accepts connections over TCP on port 3310 (without TLS). One day connections to it started getting severed.

Our solution ended up being to stand up a duplicate of the service, using the same Terraform, in a different workspace. After looking at the Envoy configurations for both services to compare them, we noticed a slightly different listener configuration.

In the pod that's working, we see an Envoy listener with the following `filterChainMatch`:

```
                "filterChainMatch": {
                    "destinationPort": 3310,
                    "transportProtocol": "raw_buffer"
                },
```

However, the one that's broken is missing it.

In the logs for the sidecar that's acting up, we see this log whenever we try interacting with the service over TCP:

```
{"path":null,"authority":null,"protocol":null,"upstream_local_address":null,"response_code":0,"user_agent":null,"response_flags":"NR","start_time":"2022-05-06T16:24:07.719Z","method":null,"upstream_host":null,"requested_server_name":null,"grpc_status":null,"hostname":"my-service","message":"0 - --","severity":"INFO"}
```

It seems like Envoy is trying to apply a listener filter that it shouldn't be.

We have no clue why one would be missing that rule while the other has it, when they're both deployed using the same exact manifests, just in different namespaces.

We don't know how Istio generates this config so we don't know which resources to check for changes.

### Version

```prose
$ istioctl version
client version: 1.9.8
control plane version: 1.8.6
data plane version: 1.8.6 (75 proxies)
```

```
➜  ~ k version --short
Client Version: v1.23.6
Server Version: v1.20.15-gke.3400
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```
```


### Additional Information

_No response_

**Comment by vikaschoudhary16** [comment]
these configs are sent by istiod to envoys over xds. istiod maintains cache of the state as well. could be some issue due to which older envoy may have stale configs.
you can try using `istioctl ps <pod> -n <ns>` command to check the staleness. At the end, try restarting application pod, that would make kind of force resync of configs.

**Comment by juicemia** [comment]
Running that command gives the following:

```
istioctl ps service.ns -n ns
Clusters Match
Listeners Match
Routes Match (RDS last loaded at Mon, 09 May 2022 10:03:12 EDT)
```

> these configs are sent by istiod to envoys over xds.

What combination of Istio resources generate listener configs?
