### ISSUE TITLE
locality use

### ISSUE THREAD

**Issue by WangChao0326** [istio/istio#38823]
### Bug Description

We are currently using the locality feature for nearby access. For the test environment, there will be many sub-environments. We regard the sub-environments as regions, and different sub-environments are regarded as different regions. This allows priority access to the same sub-environment. 
But now there is a need to specify the sub-environment of the request to a service through the URL from http request, such as http://XXX?subenv=XXX, the subenv of queryString to specify the sub-environment of the request.
If the current traffic rules are not changed , what features does istio have to do?

### Version

```prose
。
```

**Comment by hzxuzhonghu** [comment]
Guess you wanto route to specific env services by query param. One way is to define subsets of different envs with DestinationRule, and then you specify a VirtualService to route traffic to whatever destination you want.

**Comment by WangChao0326** [comment]
We want to specify the client's region based on the request, such as queryString，not the region where the client is actually located。I didn't find the relevant usage on the doc，Is there any way for istio to do this?
