### ISSUE TITLE
Remove deprecated remote profile

### ISSUE THREAD

**Issue by frankbu** [istio/istio#38832]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The remote profile has been deprecated since 1.10 so we should remove it now.

Should also check for use of the remote profile in `istioctl x precheck`. Alternatively, maybe we should add a check in `istioctl install/generate` when it detects an error because a profile does not exist, if the profile is the `remote` profile generate a warning (instead of an error), and use the default profile instead (which is equivalent).

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by AndreaM12345** [comment]
steps:
1) remove the remote.yaml profile from the repo
2) check for instances in the code referring to remote.yaml and change that to external.yaml for the profile... this should already be done
3) update docs to say use external - should already be done
4) add to the precheck to see they have a remote profile in the iop
5) add to analyze to see if they have a remote profile in the iop
6) upgrade notice saying its getting removed

**Comment by xichengliudui** [comment]
I will submit a PR tomorrow
