### ISSUE TITLE
fatal error message during make build

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#38847]
### Bug Description

`fatal` message gets logged during `make build` commands but does not appear to impact end result.

```bash
2022-05-11T13:19:12.981380Z	info	Running make: pilot-agent pilot-discovery init
GOOS=linux GOARCH=amd64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /home/gregory_hanson_solo_io/go/src/istio.io/istio/out/linux_amd64/ -tags="agent" ./pilot/cmd/pilot-agent
fatal: No names found, cannot describe anything.

real	0m3.178s
user	0m4.240s
sys	0m0.814s
GOOS=linux GOARCH=amd64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /home/gregory_hanson_solo_io/go/src/istio.io/istio/out/linux_amd64/ -tags="" ./pilot/cmd/pilot-discovery
fatal: No names found, cannot describe anything.

real	0m9.125s
user	0m9.343s
sys	0m1.576s
```

Message comes from `common/scripts/report_build_info.sh` specifically the `git describe --tags` command:
```bash
% git describe --tags
fatal: No names found, cannot describe anything.
```

Message appears on both Mac and Debian envs.  The output is supposed to be used by common/scripts/gobuild.sh - so the output from command appears to silently breaking some other function or is no longer used.

Adding `--always` flag to command does resolve the `fatal` message in both environments, but not sure if the command needs to be fixed or removed;

```bash
% git describe --tags --always
1c61a7bf2e
```

### Version

```prose
latest master
```

**Comment by howardjohn** [comment]
This is just on master branch? Did you shallow clone or something perhaps?

Adding always does seem reasonable

**Comment by ericvn** [comment]
The value is setting this variable: https://github.com/istio/pkg/blob/master/version/version.go#L28.

Setting this to the shortened commit if there is no tag makes sense. I believe this tag is only used within the istioctl command, namely istioctl version.
