### ISSUE TITLE
Uninstall Istio doesn't clean up properly

### ISSUE THREAD

**Issue by frankbu** [istio/istio#38855]
### Bug Description

The current [documented uninstall instructions](https://istio.io/latest/docs/setup/getting-started/#uninstall) do not delete the `istiod-default-validator` webhook that was created by `istioctl install`. The document should be changed to use some proper recommended command(s), but it's unclear what that should be.

1. We could change it to `istioctl x uninstall --revision=default`,  which works, but using an experimental command as the "proper" recommended way to uninstall seems bad. Maybe it's time to promote uninstall?
2. The current instructions use `manifest generate | kubectl delete` followed by `istioctl tag remove default`, presumably to remove the webhooks, but it currently only removes the injection webhook. Maybe that's a bug in `istioctl tag remove`?
3. Manually clean up resources that are not handled by the commands. Doesn't seem like the best option, but we would seem to need to figure out what the recommendation is for users that are not using istioctl (e.g. helm), which might require some manual steps anyway?

### Version

```prose
1.13
```

**Comment by frankbu** [comment]
This should be applied more generally to all the docs: https://github.com/istio/istio.io/pull/11281#issuecomment-1126202799

**Comment by vyom-soft** [comment]
I also see the same behaviour. I  did uninstall of Istio 1.13.3. Then after reinstalling and executing the 
$istio-1.13.3 istioctl verify-install
1 Istio control planes detected, checking --revision "default" only
Error: could not overlay user config over base: json merge error (unable to find api field in struct meshConfigExtensionProvider for the json field "envoyOtelAls") for base object:

Thank you

**Comment by frankbu** [comment]
Fixed by https://github.com/istio/istio.io/pull/11707
