### ISSUE TITLE
Add `kubernetes.io/hostname` as internal label for use in locality load balancing

### ISSUE THREAD

**Issue by rjhuijsman** [istio/istio#38852]
In https://github.com/istio/istio/issues/38693 @howardjohn proposed:
> * Setup locality LB with failoverPriority (istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting) for the Gateway [...] to ensure same-node is preferred.

This turns out to be trickier than expected; one has to set the `topology.istio.io/subzone` label to contain a node-specific name (= make it identical to [`kubernetes.io/hostname`](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname)) so that `topology.istio.io/subzone` can then be used in `failoverPriority`.

This has some drawbacks:
1. It's not exactly self-documenting that "subzone" can be taken to mean "node".
1. You have to not only set the `topology.istio.io/subzone` label on every node, you also have to create automation to keep `topology.istio.io/subzone` in sync with `kubernetes.io/hostname` as nodes join the cluster.
1. It's unclear whether users will always be able to set `topology.istio.io/subzone`. They may not have permissions to add node labels. Or they may already be using `topology.istio.io/subzone` for something else.

Instead, we could add [`kubernetes.io/hostname`](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname) (or a new label like `topology.istio.io/node` mapping to that) to the list of ["labels which have special semantic meaning"](istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting) in `failoverPriority`. The advantages:
1. It becomes self-documenting that the locality load balancer can prioritize same-node localities.
1. Users don't need to write any additional code to use same-node-locality load balancing.
1. Users don't need special permissions to use same-node-locality in load balancing.
1. Subzone remains available to represent things like "rack", "group of nearby servers", ...

We discussed this in the WG meeting today and @howardjohn also saw benefits for such a label beyond locality load balancing, e.g. in use cases like "this traffic may for security reasons only ever be routed to the local node". @howardjohn perhaps you can serialize your thoughts on that here?

The consensus in the WG meeting today was that this was a feature worth implementing. @howardjohn may also be able to provide guidance on what such a change would entail?

**Comment by rjhuijsman** [comment]
I definitely would still like to see this feature, and the WG agreed back in May. Perhaps @howardjohn could share his thoughts about these questions from https://github.com/istio/istio/issues/38852#issue-1232919933:

> We discussed this in the WG meeting today and @howardjohn also saw benefits for such a label beyond locality load balancing, e.g. in use cases like "this traffic may for security reasons only ever be routed to the local node". @howardjohn perhaps you can serialize your thoughts on that here?
> 
> The consensus in the WG meeting today was that this was a feature worth implementing. @howardjohn may also be able to provide guidance on what such a change would entail?

**Comment by howardjohn** [comment]
I think just https://github.com/istio/istio/blob/fcfbad7ff2b126d53aa91bc2ea7a33e2a972ba5d/pilot/pkg/serviceregistry/util/label/label.go#L33 needs to be changed... although in practice something else may come up making it more challenging.

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
afaik this is done now
