### ISSUE TITLE
Sidecar not using TLS through to mongoDB

### ISSUE THREAD

**Issue by pinimac** [istio/istio#38866]
### Bug Description

Hello,

We are facing a traffic issue, as you know Istio using a sidecar running beside POD.

The Istio sidecar(Envoy-PROXY) needs to catch the traffic form the micro service and to convert from unsecured to secured using the NameSpace certificate 

For this method  configured four kinds of APIs Please see below:

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: PERMISSIVE
----
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: spec:
  exportTo:
  - .
  host:  subsets:
{{- range .ports }}  
  - name: {{ $val.name }}-{{ .port }}-{{ (split "." ($val.host | lower) )._0 }}-subset
    trafficPolicy:
      portLevelSettings:
      - port:
          number: {{ .port }}
        tls:
          caCertificates: /etc/certs/ca/tls.crt
          clientCertificate: /etc/certs/{{ $val.secret | replace "-certs" "" }}/tls.crt
          privateKey: /etc/certs/{{ $val.secret | replace "-certs" "" }}/tls.key
          mode: MUTUAL
------
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $val.name }}-{{ $Values.env.ENV }}-{{ (split "." ($val.host | lower) )._0 }}
spec:
  hosts:
  - {{ $val.host }}
{{- if eq (printf "%s" (index $val.ports 0).protocol | lower ) "tcp" }}
  tcp:
{{- else }}
  http:
{{- end }}  
{{- range $val.ports }}
  - match:
    - sourceLabels:
        {{ $val.name }}: "true"
      port: {{ .portHttp }}
    route:
    - destination:
        host: {{ $val.host }}
        port:
          number: {{ .port }}
        subset:

----
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ $val.name }}-{{ $Values.env.ENV }}-{{ (split "." ($val.host | lower) )._0 }}
spec:
  hosts:
  - {{ $val.host }}
{{- if eq (printf "%s" $val.resolution) "NONE" }}
  addresses:
{{- toYaml $val.addresses | nindent 2 }}
{{- end }}
  location: MESH_EXTERNAL
  ports:
{{- range $val.ports }}    
  - name: {{ $val.name }}-{{ .port }}
    number: {{ .port }}
    protocol: {{ .protocol | lower}}
{{- if and (eq (printf "%s" .protocol | lower ) "https") (ne .portHttp .port) }}
  - name: {{ $val.name }}-http-{{ .port }}
    number: {{ .portHttp }}
    protocol: HTTP
{{- end }}
{{- end }}
  resolution: {{ default "DNS" $val.resolution }}
-----

### Version

```prose
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (14 proxies)

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-1-21", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2022-01-22T01:16:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aryan16** [comment]
can you share the proxy logs ?

**Comment by CCVIII** [comment]
Please see the log and pictures from the issue  attached
![mongo_Pic](https://user-images.githubusercontent.com/70690880/168152849-43c55b1e-4846-4adb-a9f7-5845f038a0ae.png)
![mongo2](https://user-images.githubusercontent.com/70690880/168152863-df9a9942-a61d-4333-9bcf-eb2900b2f9f0.png)
[init.txt](https://github.com/istio/istio/files/8681987/init.txt)
[istio-proxy.txt](https://github.com/istio/istio/files/8681988/istio-proxy.txt)
[sms.txt](https://github.com/istio/istio/files/8681989/sms.txt)

**Comment by aryan16** [comment]
can you explain what exactly you are trying to do here ?

**Comment by CCVIII** [comment]
> can you explain what exactly you are trying to do here ?

I'm trying to change the traffic to mTLS with istio proxy and connect to MongoDB with certificate.

**Comment by aryan16** [comment]
So basically you want to connect to mongo db from envoy and you are not seeing TLS traffic in this process ?

**Comment by CCVIII** [comment]
Correct, if you'll see the four yaml up, I've configured Service Entry, Destination Role, Virtual Service, and Peer Authentication.

Can you elaborate on Istio proxy behavior or maybe the configuration up is not correct?

I've installed the demo profile and I tried with default.

**Comment by aryan16** [comment]
I don't see the destination service information in Destination Rule, can you try to add that. It should ideally work, envoy with sidecar will always send the tls traffic until mtls is not disabled specifically using some destination rule or some peer auth policy.

**Comment by pinimac** [comment]
I want to be clear, I'm using the same configuration in Istio 1.5.2 K8s 1.19 without any issue.

The issue appear when I installed a new K8s v1.21.5  cluster with a new Istio 1.13.3.

in the Destination Rule, I've configured the MongoDB URL.

is I need to change the configuration or can you provide a better method to connect to external MongoDB using Istio TLS method.

**Comment by aryan16** [comment]
you can try to do one thing, rn in the destination rule `MUTUAL` mode is set to `portLevelSetting`, can you try to do it for every request something like ```trafficPolicy:
    tls:
      mode: MUTUAL```
