### ISSUE TITLE
Inbound traffic 50% showing pods as failed

### ISSUE THREAD

**Issue by salimuddin87** [istio/istio#38870]
When I open kiali and check the overview of pods
![image](https://user-images.githubusercontent.com/3928368/168082509-4a9d493d-b872-4935-8e99-73e0fa733c18.png)

I ran some test and i am able to pass through traffic but don't know why it is in failed states. Also I have noticed that we are getting junk container logs like:
`E0512 12:37:21.090316457      27 http_server_filter.cc:236]  GET request without QUERY

E0512 12:37:26.090310277      27 http_server_filter.cc:236]  GET request without QUERY

E0512 12:37:31.090274914      27 http_server_filter.cc:236]  GET request without QUERY

E0512 12:37:36.090237529      27 http_server_filter.cc:236]  GET request without QUERY`

istio version: 1.13.3
kiali plugin: 1.13.3
kubectl : 1.21

**Comment by zirain** [comment]
by default istio enable prometheus merge, prometheus will scrape with `/stats/prometheus` on port 15020, can you verify the annotations of the error pod.

**Comment by salimuddin87** [comment]
> by default istio enable prometheus merge, prometheus will scrape with `/stats/prometheus` on port 15020, can you verify the annotations of the error pod.

I have not added any annotation on the erroring pod.

**Comment by salimuddin87** [comment]
How can I change prometheus scrape from http to grpc?
