### ISSUE TITLE
Don't trigger pushes when updating K8s service annotations not releated to istio

### ISSUE THREAD

**Issue by fatedier** [istio/istio#38896]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When I add annotation `a: b` to a K8s service, pilot will trigger ADS pushes to all clients.

I think it's unnecessary to trigger pushes if the updated annotations are not releated to istio.

Otherwise, batch updates on service annotations will make the pilot consume more CPU.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Right, we have done similar optimize before for other resources. And I think we need to know your use case to make sure this case is common.

**Comment by ramaraochavali** [comment]
@fatedier Any update on usecase?

**Comment by fatedier** [comment]
@ramaraochavali The root cause is that xds config generating takes up a lot of resources. And in my environment, service annotations change(some app meta info like owner, team, etc.) will always trigger full pushes that not necessary.

I'm not sure if it's possible to avoid unnecessary config generating by filtering out unconcerned K8s resources changes.
