### ISSUE TITLE
Where is the HTTP handler for DiscoveryService?

### ISSUE THREAD

**Issue by NeGnail** [istio/istio#3889]
I can see the following code, but the comments indicate that these routes are just for testing. So where is the actual route used?

` // Register adds routes a web service container. This is visible for testing purposes only.
func (ds *DiscoveryService) Register(container *restful.Container) {
	ws := &restful.WebService{}
	ws.Produces(restful.MIME_JSON)

	// List all known services (informational, not invoked by Envoy)
	ws.Route(ws.
		GET("/v1/registration").
		To(ds.ListAllEndpoints).
		Doc("Services in SDS"))`

**Comment by ijsnellf** [comment]
@NeGnail: it's the next one down. `"/v1/registration/{%s}`

Also, this is a question not an issue. Please ask in https://groups.google.com/forum/#!forum/istio-users

**Comment by NeGnail** [comment]
@ijsnellf You mean this path is actually used, not for testing. "/ v1 / registration / {} % s"

But I've seen a line of comments on this method, and I understand that it means that all the paths in this method are for testing. “Register adds routes a web service container. This is visible for testing purposes only.”
