### ISSUE TITLE
[install primary-remote on the same network] east-west gateway do not have LoadBalances

### ISSUE THREAD

**Issue by fdsaggaw** [istio/istio#38908]
The cluster do not support the type of LoadBalance, how the remote cluster connect to primary cluster's east-west gateway

**Comment by zirain** [comment]
maybe NodePort type service

**Comment by fdsaggaw** [comment]
> maybe NodePort type service

I have replaced LoadBalance with NodePort and config "remotePilotAddress" as cluster's IP in cluster2.yaml,but it can't use the nodePort when  run "istioctl install -f cluster2.yaml". It use the targetPort.
