### ISSUE TITLE
Support additional containers in gateway Helm chart

### ISSUE THREAD

**Issue by gjacquet** [istio/istio#38912]
**Describe the feature request**

There are some use cases where it would be useful to run a sidecar container along with the gateway main container.

Gateways chart supports it (https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L72) however the gateway chart to deploy a single gateway does not allow defining any additional containers.

**Describe alternatives you've considered**

While there are plenty of other way to get this done (forking the chart, using an admission controller etc), adding the option in this chart would be the most convenient.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
See https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/; I don't think we can reasonable expose every single possible API field in the gateway.
