### ISSUE TITLE
proxyless gRPC: certs not refreshed

### ISSUE THREAD

**Issue by costinm** [istio/istio#38923]
### Bug Description

I ran a long-running test, after 1 day it stopped working with TLS cert problems - the cert doesn't seem to be refreshed.

With envoy, the refresh happens as result of envoy calls to SDS, for proxyless we use files which are created accidentally 
as the 'startup optimization'.

Also:
- several CA options will not work ( like CSI-provided certs )
- the location is non-standard - files should be created in /var/run/workload-certificates, if they don't exist ( so in case a CSI 
provider is used we don't need the agent )
- we should not start the SDS server in the first place - not used, may have extra security risks
- the list of CA roots from Istio MeshConfig sent via ProxyConfig doesn't seem to work as expected either.
- the code dealing with certs is also over complex 

Proposed long term fix:
- recommended: use a CSI provider and 'agentless' - the location of the files should be /var/run/workload-certificates.
- provide a small dependency-free library as fallback - with implementations in different languages - to create the files. Apps running in environments without a workload provider can use it at startup and for periodic refresh
- provide a binary that does the same and may either refresh or be exec-ed periodically, for languages we don't have a native
cert provisioning.
- the bootstrap generator can also be moved to the library, removing the need for the full pilot-agent (except in cases where
auth requires the XDS proxy ).
 

### Version

```prose
master
```

**Comment by costinm** [comment]
@sanjaypujare

**Comment by sanjaypujare** [comment]
do not close.

**Comment by sanjaypujare** [comment]
@costinm should this be reopened and resolved properly?
