### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by liubq919** [istio/istio#38932]
## 1.12.7 upgrade to 1.13.3
    istioctl install --set profile=demo -y
    ps: defaut config without any changes

<hr>
the new istiod container fails to start:
`panic: assignment to entry in nil map

goroutine 128 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*endpointSliceController).newEndpointBuilder(0xc000dc55c0, 0xc0036f7f80)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointslice.go:356 +0xc8
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*endpointSliceController).updateEndpointCacheForSlice(0xc000dc55c0, {0xc0018bac30, 0x25}, {0x3389840, 0xc003068068})
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointslice.go:239 +0x48d
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*endpointSliceController).buildIstioEndpoints(0xc000dc55c0, {0x3389840, 0xc003068068}, {0xc0018bac30, 0x25})
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointslice.go:216 +0x45
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.updateEDS(0xc0007802c0, {0x38da8c0, 0xc000dc55c0}, {0x3389840, 0xc003068068}, 0x0)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go:106 +0x2ae
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.processEndpointEvent(0xc0007802c0, {0x38da8c0, 0xc000dc55c0}, {0xc001442b87, 0x7}, {0xc001442b60, 0xb}, 0xc00052c601, {0x3389840, 0xc003068068})
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go:66 +0x76
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*endpointSliceController).onEvent(0xc000dc55c0, {0x3389840, 0xc003068068}, 0x1)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/endpointslice.go:122 +0x258
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).syncEndpoints(0xc0007802c0)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:834 +0x155
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).SyncAll(0xc0007802c0)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:774 +0x194
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Run(0xc0007802c0, 0xc0000d0cc0)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/controller.go:851 +0x19c
created by istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Run
	istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:333 +0x5d
`

### Version

```prose
$  istioctl version
8 errors occurred:
	* error port-forwarding into istio-system.istiod-7ccf6888cd-f8qjk: the server is currently unable to handle the request (get pods istiod-7ccf6888cd-f8qjk:15014)
	* error exec'ing into istiod-7ccf6888cd-f8qjk discovery container: error exec'ing into istio-system/istiod-7ccf6888cd-f8qjk discovery container: unable to upgrade connection: container not found ("discovery")
	* error port-forwarding into istio-system.istiod-7ccf6888cd-h8z9t: the server is currently unable to handle the request (get pods istiod-7ccf6888cd-h8z9t:15014)
	* error exec'ing into istiod-7ccf6888cd-h8z9t discovery container: error exec'ing into istio-system/istiod-7ccf6888cd-h8z9t discovery container: unable to upgrade connection: container not found ("discovery")
	* error port-forwarding into istio-system.istiod-7ccf6888cd-jz4tf: the server is currently unable to handle the request (get pods istiod-7ccf6888cd-jz4tf:15014)
	* error exec'ing into istiod-7ccf6888cd-jz4tf discovery container: error exec'ing into istio-system/istiod-7ccf6888cd-jz4tf discovery container: unable to upgrade connection: container not found ("discovery")
	* error port-forwarding into istio-system.istiod-7ccf6888cd-ksmgn: the server is currently unable to handle the request (get pods istiod-7ccf6888cd-ksmgn:15014)
	* error exec'ing into istiod-7ccf6888cd-ksmgn discovery container: error exec'ing into istio-system/istiod-7ccf6888cd-ksmgn discovery container: unable to upgrade connection: container not found ("discovery")


2022-05-16T12:13:05.617678Z	error	klog	an error occurred forwarding 35231 -> 15014: error forwarding port 15014 to pod ca758dbbe5ee8b8f3f22fbee394f7b296108d0ccc4a334b940896cce843ed537, uid : unable to do port forwarding: socat not found
2022-05-16T12:13:05.618335Z	error	klog	lost connection to pod
1.13.3

$ kubectl version --short
Client Version: v1.23.0
Server Version: v1.21.7
```

**Comment by hzxuzhonghu** [comment]
I can imagine a pod can have empty label when created by hand.  Not sure how is your case and also do you create endpointslice by hand? If not, how can we reproduce

**Comment by liubq919** [comment]
any pods that with sidecar injected enabled has 2 labels: app and version. 
use istio since version 0.6 and is already running in production for serveral years( no manual chages in any env).
any additional info you need?

**Comment by hzxuzhonghu** [comment]
Can you show the pod yaml, especially the metadata?

**Comment by liubq919** [comment]
which pod? istiooperator?

**Comment by hzxuzhonghu** [comment]
From the stack, i can not say which pod, but at least one pod has no labels.

**Comment by hzxuzhonghu** [comment]
I remember there was one similar issue reported, and we do not understand the case, so we did nothing for it.

**Comment by liubq919** [comment]
https://github.com/istio/istio/pull/37497
this issue?

**Comment by liubq919** [comment]
the errors i got in istiod pod is as same as in https://github.com/istio/istio/pull/37497.

**Comment by hzxuzhonghu** [comment]
Yes, it is. Just I still did not figure out my question, how pod without labels can be selected by a service.
