### ISSUE TITLE
 Failed calling webhook "validation.istio.io"

### ISSUE THREAD

**Issue by thennetirajesh** [istio/istio#38930]
Description : 
`<html>
<body>

00:10:24.457 | message:BaseOperation::provision Error: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": no endpoints available for service "istiod" Error: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": no endpoints available for service "istiod" at KubernetesServiceImpl.raiseKubernetesError (/app/dist/api/services/basis/kubernetesService.js:327:21) at KubernetesServiceImpl.<anonymous> (/app/dist/api/services/basis/kubernetesService.js:1043:22) at Generator.throw (<anonymous>) at rejected
-- | --

</body>
</html>

Istio Version : 1.11.8
K8's Verstion : 1.21.9

HPA's

![image](https://user-images.githubusercontent.com/85360813/168553128-f4ae82e9-b143-4f3f-90d9-6e6976d041f6.png)

We are seeing the below error regularly, could you please suggest
<html>
<body>

May 16, 2022 @ 00:10:24.456 | message:Error: "Internal error occurred: failed calling webhook \"validation.istio.io\": Post \"https://istiod.istio-system.svc:443/validate?timeout=10s\": no endpoints available for service \"istiod\"" Error: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": no endpoints available for service "istiod" at KubernetesServiceImpl.raiseKubernetesError (/app/dist/api/services/basis/kubernetesService.js:327:21) at KubernetesServiceImpl.<anonymous> (/app/dist/api/services/basis/kubernetesService.js:1043:22) at Generator.throw (<anonymous>) at rejected (/app/dist/api/services/basis/kubernetesService.js:15:65) at runMicrotasks (<anonymous>) at processTicksAndRejections 
-- | --

</body>
</html>

**Comment by hzxuzhonghu** [comment]
Istiod is not ready, you can check the istiod log

**Comment by thennetirajesh** [comment]
From the Grafana dashboard, we could see HPAs scaling up/down the Istiod pod.
Even though there are two istiod pods that will be running state, and when HPA  scales up the new pods the new request is going to the new pod even though the pod is not in the ready state, hence we are seeing the above error message.

Can you suggest how to proceed further.
