### ISSUE TITLE
sample sleep pod in Init:CrashLoopBackOff state

### ISSUE THREAD

**Issue by vyom-soft** [istio/istio#38940]
### Bug Description

Hello,
I installed istio as instructed https://istio.io/latest/docs/setup/install/istioctl/
And trying to do initial deployment with the sleep example https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
Label the default namespace with istio-injection=enabled is set.

Unfortunately the sleep pod is in Init:CrashLoopBackOff state. 
I also see:
$istio-1.13.3 istioctl verify-install
1 Istio control planes detected, checking --revision "default" only
Error: could not overlay user config over base: json merge error (unable to find api field in struct meshConfigExtensionProvider for the json field "envoyOtelAls") for base object:

I am not sure where I went wrong. Any input please. 
Thank you

### Version

```prose
$istio-1.13.3 istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (2 proxies)
```

**Comment by vyom-soft** [comment]
Update: Just for the next steps I uninstalled istio  & reinstall so that I can again try the example with out that verify error
 $istioctl verify-install. (as above)

**Following the below sequence Uninstall.**
kubectl delete -f samples/addons
istioctl manifest generate --set profile=demo | kubectl delete --ignore-not-found=true -f -
istioctl tag remove default
istioctl x uninstall --revision=default (https://github.com/istio/istio/issues/38855) (kubectl get validatingwebhookconfiguration)

kubectl delete namespace istio-system
kubectl label namespace default istio-injection-

**Install istio istio-1.13.3** 
$istioctl install --set profile=demo -y
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Installation complete                                                                                                                                                                           Making this installation the default for injection and validation.

**Now if you run the**   **$istioctl verify-install**. **Again the same error persisted.** 

**To get rid of this verify-install error, **I performed istio upgrade**** 
1) istioctl x precheck
2) istioctl upgrade
This will install the Istio 1.13.3 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
- Pruning removed resources                                                                                                                                                                   Removed PodDisruptionBudget:istio-system:istio-egressgateway.
  Removed Deployment:istio-system:istio-egressgateway.
  Removed Service:istio-system:istio-egressgateway.
  Removed ServiceAccount:istio-system:istio-egressgateway-service-account.
  Removed RoleBinding:istio-system:istio-egressgateway-sds.
  Removed Role:istio-system:istio-egressgateway-sds.
✔ Installation complete                                                                                                                                                                     Making this installation the default for injection and validation.

**$istioctl verify-install**. is happy now (it does various verification)
 ~ istioctl verify-install
1 Istio control planes detected, checking --revision "default" only
✔ ClusterRole: istiod-istio-system.istio-system checked successfully
✔ ClusterRole: istio-reader-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istio-reader-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-istio-system.istio-system checked successfully
✔ ServiceAccount: istio-reader-service-account.istio-system checked successfully
✔ Role: istiod-istio-system.istio-system checked successfully
✔ RoleBinding: istiod-istio-system.istio-system checked successfully
✔ ServiceAccount: istiod-service-account.istio-system checked successfully
✔ CustomResourceDefinition: wasmplugins.extensions.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: destinationrules.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: envoyfilters.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: gateways.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: proxyconfigs.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: serviceentries.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: sidecars.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: virtualservices.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: workloadentries.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: workloadgroups.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: authorizationpolicies.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: peerauthentications.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: requestauthentications.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: telemetries.telemetry.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: istiooperators.install.istio.io.istio-system checked successfully
✔ HorizontalPodAutoscaler: istiod.istio-system checked successfully
✔ ClusterRole: istiod-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRole: istiod-gateway-controller-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-gateway-controller-istio-system.istio-system checked successfully
✔ ConfigMap: istio.istio-system checked successfully
✔ Deployment: istiod.istio-system checked successfully
✔ ConfigMap: istio-sidecar-injector.istio-system checked successfully
✔ MutatingWebhookConfiguration: istio-sidecar-injector.istio-system checked successfully
✔ PodDisruptionBudget: istiod.istio-system checked successfully
✔ ClusterRole: istio-reader-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istio-reader-clusterrole-istio-system.istio-system checked successfully
✔ Role: istiod.istio-system checked successfully
✔ RoleBinding: istiod.istio-system checked successfully
✔ Service: istiod.istio-system checked successfully
✔ ServiceAccount: istiod.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.11.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.11.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.12.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.12.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.13.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.13.istio-system checked successfully
✔ ValidatingWebhookConfiguration: istio-validator-istio-system.istio-system checked successfully
✔ HorizontalPodAutoscaler: istio-ingressgateway.istio-system checked successfully
✔ Deployment: istio-ingressgateway.istio-system checked successfully
✔ PodDisruptionBudget: istio-ingressgateway.istio-system checked successfully
✔ Role: istio-ingressgateway-sds.istio-system checked successfully
✔ RoleBinding: istio-ingressgateway-sds.istio-system checked successfully
✔ Service: istio-ingressgateway.istio-system checked successfully
✔ ServiceAccount: istio-ingressgateway-service-account.istio-system checked successfully
Checked 15 custom resource definitions
Checked 2 Istio Deployments
✔ Istio is installed and verified successfully.

TODO: I will try that sleep example again and update.

**Comment by vyom-soft** [comment]
Here are the files
[sleep-pod.yaml.txt](https://github.com/istio/istio/files/8706343/sleep-pod.yaml.txt)
[sleep-dployment.txt](https://github.com/istio/istio/files/8706382/sleep-dployment.txt)
[sleep-pd-describe.txt](https://github.com/istio/istio/files/8706438/sleep-pd-describe.txt)

OS: RHEL 8
k8s: Kubespray 
MetalLB

**Comment by vyom-soft** [comment]
> kubectl logs POD -c istio-init
Please see the same. Thank you in advance. 
[sleep-pod-istio-init-log.txt](https://github.com/istio/istio/files/8717501/sleep-pod-istio-init-log.txt)

**Comment by vyom-soft** [comment]
> 
Please see the fresh log.
[istio-init.log](https://github.com/istio/istio/files/8718482/istio-init.log)

**Comment by EamonKeane** [comment]
I've tested this locally and I believe it was due to some automation that assumes the demo profile uses the open telemetry collector. There is a separate sample to install open telemetry (samples/open-telemetry/otel.yaml - note this sample also has a docker tag 0.38.0 that doesn't exist). 

This addition was added in 1.13.3 by this commit:

https://github.com/istio/istio/commit/b70734d0558b13e15879ebb9847e7e9529bcb83a

I would suggest removing the 4 lines adding an otel config to the demo profile. The

**Comment by zirain** [comment]
there're two problem here
1. istio-init run fail
1. istioctl verify-install run fail when profile is `demo`

(1) seems relate to arm64
(2) root case is `strategicpatch.StrategicMergePatch`
