### ISSUE TITLE
"holdApplicationUntilProxyStarts" annotation doesn't seem to work reliably

### ISSUE THREAD

**Issue by va7ish** [istio/istio#38945]
### Bug Description

using Ghz gRPC performance tool in a proxy-less mode (xds:/// endpoint) the annotation proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}' doesn't work reliably to prevent the tool from starting before the bootstrap file is fully rendered. In result the ghz tool fails with the following message:
-------------------
failed to build resolver: xds: failed to create xds-client: xds: failed to read bootstrap file: xds: Failed to read bootstrap config: open /etc/istio/proxy/grpc-bootstrap.json: no such file or directory
-------------------

Adding manual delay before starting Ghz client solves the problem. 

### Version

```prose
client version: 1.13.3
control plane version: 1.13.1
data plane version: 1.13.1-asm.1 (3 proxies)
```

**Comment by va7ish** [comment]
@sanjaypujare Please assign to the right person

**Comment by sanjaypujare** [comment]
Thanks for filing the issue, @va7ish .

@costinm could you take this or assign it to the right person (since I don't have the privs to do it)?

**Comment by costinm** [comment]
Fixed in master.

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/38837

**Comment by sanjaypujare** [comment]
> Fixed in master.

Which Istio version will have the fix?
