### ISSUE TITLE
helm chart for release version install failed for missing named template in _helpers.tpl partial files

### ISSUE THREAD

**Issue by morvencao** [istio/istio#3895]
**env:**
```
centos: 7.2
istio version: 0.6.0
kubenetes version: v1.9.1
```

**install command:**
```
helm install --debug --dry-run --name istio --namespace istio-system istio-0.6.0/install/kubernetes/helm/istio
```

**problem:**
```
[debug] Created tunnel using local port: '60884'

[debug] SERVER: "127.0.0.1:60884"

[debug] Original chart version: ""
[debug] Key="/var/lib/helm/key.pem", Cert="/var/lib/helm/cert.pem", CA="/var/lib/helm/ca.pem"

[debug] CHART PATH: /root/istio-0.6.0/install/kubernetes/helm/istio

Error: render error in "istio/charts/pilot/templates/serviceaccount.yaml": template: istio/charts/pilot/templates/serviceaccount.yaml:5:20: executing "istio/charts/pilot/templates/serviceaccount.yaml" at <{{template "pilot.se...>: template "pilot.serviceAccountName" not defined
```

While install from source code, it's all right:
```
helm install --debug --dry-run --name istio --namespace istio-system istio/install/kubernetes/helm/istio
[debug] Created tunnel using local port: '46249'

[debug] SERVER: "127.0.0.1:46249"

[debug] Original chart version: ""
[debug] Key="/var/lib/helm/key.pem", Cert="/var/lib/helm/cert.pem", CA="/var/lib/helm/ca.pem"

[debug] CHART PATH: /root/istio/install/kubernetes/helm/istio

NAME:   istio
REVISION: 1
RELEASED: Fri Mar  2 02:40:42 2018
CHART: istio-0.6.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
...
```

**Comment by sdake** [comment]
A patch has merged post 0.6.0 which removes serviceAccountName from most of the code base (including pilot's serviceaccount).  Is there any chance you can try master?

Thanks
-steve

**Comment by wwadge** [comment]
Just happened to try this. Master looks fine now.

**Comment by morvencao** [comment]
Thanks @sdake for your reply.
As @wwadge mentioned, master works fine.

**Comment by Rigdon** [comment]
This seems to be the case. None of the `_helpers.tpl` files appear to be present in either the releases or daily builds.

**Comment by sdake** [comment]
@morvencao I'm not sure I follow.  The versions are defined in the Chart.yaml files: e.g.
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/Chart.yaml
and also the subcharts:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/Chart.yaml

A sed of `version: 0.5.0` to latest version should work in the release scripts.  That sed logic is not integrated into updateVersions.sh.  We want to get rid of updateVersions not expand it.  Would it make more sense to put this version changing logic in the release scripts themselves?

Cheers
-steve

**Comment by morvencao** [comment]
@sdake The issue is that some partial files for helm chart are missing in release version, while they actually exist in master branch. Have checked the **updateVersion.sh**, no logic to ignore or remove the partial files like **_helpers.tpl**. 
Is there other release script besides **updateVersion.sh**, I can't get any from doc.

**Comment by Rigdon** [comment]
Bumping this again. The _helpers files in the helm directory are still missing in the most [recent daily build arch-specific tarballs ](https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180319-09-15/istio-0.7.0-pre20180319-09-15-linux.tar.gz) but are present in the [source tarball](https://storage.googleapis.com/istio-prerelease/daily-build/0.7.0-pre20180319-09-15/source.tar.gz) so it seems that whatever is packaging the nightlies seems to be removing these files.

**Comment by christian-posta** [comment]
yah -- i saw this too just now. sent a fix in, hopefully corrects itself for next nightly? not sure if 0.7.0 is built from master or not..

**Comment by Amey-D** [comment]
I see a similar symptom with istio v0.7.1 on osx w/ kubectl client version v1.9.3 and server version v1.9.6-gke.0:

```
$ helm install --debug --dry-run istio --name istio --namespace istio-system
[debug] Created tunnel using local port: '55735'

[debug] SERVER: "127.0.0.1:55735"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/amey/work/istio/istio-0.7.1/install/kubernetes/helm/istio

Error: render error in "istio/charts/security/templates/serviceaccount.yaml": template: istio/charts/security/templates/serviceaccount.yaml:6:21: executing "istio/charts/security/templates/serviceaccount.yaml" at <{{template "security...>: template "security.name" not defined
```

AFAICT v0.7.1 does not include the fix (see https://github.com/istio/istio/blob/0.7.1/release/create_release_archives.sh does not include *.tpl files).

When can we expect this fix to be available in a release version?  If there is a plan for v0.7.2 can we please backport the patch in `release-0.7` branch asap?

**Comment by morvencao** [comment]
+1 
/cc @gyliu513

**Comment by mandarjog** [comment]
@hklai 0.7 does not include pr #4467 that fixes directly helm driven operations. it should be as easy cherry pick.

**Comment by hklai** [comment]
@mandarjog and folks.  0.7.1 was already cut, released, and announced.

Neither this or #4467 has the **kind/blocking release** label, so this was not included in 0.7.1, and it was not on our radar in the past couple weeks. In future, please make sure to add the label if you intend to include a particular fix.

PTAL at the release process https://github.com/istio/istio/tree/master/release#istio-release for reference.

Given that 0.8.0 is only a couple weeks away, and 0.7.1 is not an LTS, there is no plan to cut 0.7.2.

Is there a workaround? Maybe we should add that to release notes.

**Comment by gregdurham** [comment]
I was able to work around this by cloning the repo, and copying the tpl files to the correct locations in my download of the installer. This accompanies by the workaround in https://github.com/istio/istio/issues/4701 allowed me to provision 0.7.1 via helm.

**Comment by sdake** [comment]
@hklai I reviewed @christian-posta 's patch and had (incorrectly) believed it was in 0.7.  Completely my fault.  I will take care to mark these critical problems as release/blocking during the review process.

**Comment by hklai** [comment]
@sdake thanks!

And since there is a workaround, perhaps it should be documented in https://github.com/geeknoid/istio.github.io/blob/master/_about/notes/0.7.md?

**Comment by linsun** [comment]
cc @geeknoid yes, unfortunately, this means 0.7.1 helm chart is broken... I had thought the .tpl files are packaged in 0.7.1 too.

**Comment by linsun** [comment]
I submitted a PR earlier: https://github.com/istio/istio.github.io/pull/1144

@hklai if we ever spin a 0.7.x build, would be great to pick up the fix from  #4467

**Comment by Disturbing** [comment]
@hklai  -- This issue still exists in 0.7.1.

Works great on master, but now 0.7.x so far following helm install instructions.  Would expedite a 0.7.2 release as a new comer like me had a blocker with the basic helm install instructions :(.

**Comment by hklai** [comment]
Please follow the workaround as suggested in 0.7 release notes.
https://preliminary.istio.io/about/notes/0.7.html

There is no plan for 0.7.2. 0.8.0 is on the way and we need to make sure helm works there. +@linsun
