### ISSUE TITLE
can't visit from vm node to pods in istio based on kubernetes whitout static route  manually configure

### ISSUE THREAD

**Issue by xiyanxiyan10** [istio/istio#38958]
### Bug Description

based on istio vm node support, the vm node can't route packet success without static route configured。 
- I deploy a istio cluster based on kubernetes。
- Then Add vm node into istio cluster。
- Deploy a test deployment on kubernetes。
- Visit from vm node to deployment's pods success。
```
[root@k8s115 ~]# curl -v  helloworld.sample.svc:5000/hello
* About to connect() to helloworld.sample.svc port 5000 (#0)
*   Trying 10.233.29.233...(this is virtual address)
* Connected to helloworld.sample.svc (10.233.29.233) port 5000 (#0)
> GET /hello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: helloworld.sample.svc:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 60
< server: envoy
< date: Tue, 17 May 2022 01:44:17 GMT
< x-envoy-upstream-service-time: 153
<
Hello version: v1, instance: helloworld-v1-5b75657f75-v6vcq
* Connection #0 to host helloworld.sample.svc left intact
```
5. but there is a promble, the http packet can't route success without static route。because the vm node did not know the virtual address where to route to，
I must add the static route in vm node 
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.16.1    0.0.0.0         UG    100    0        0 ens33
10.233.0.0      192.168.16.113  255.255.0.0     UG    0      0        0 ens33  (Here is the route I add，tell where the packet to virtual address route to) 
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.16.0    0.0.0.0         255.255.255.0   U     100    0        0 ens33         
```
6. Is there any way to learn the route dynamic?
7. It seems that there is a way based on bgp, but need to configure the router devices，Is there a  solution to solve this with no need to configure the router devices。 

### Version

```prose
[root@ks113 ~]# istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (4 proxies), 1.10.0 (1 proxies)
```

**Comment by howardjohn** [comment]
If you cannot reach pod IPs directly from the VM, you should follow the multi-network instructions in https://istio.io/latest/docs/setup/install/virtual-machine/#prepare-the-guide-environment
