### ISSUE TITLE
mismatch doc and api design

### ISSUE THREAD

**Issue by zirain** [istio/istio#38968]
### Bug Description

on hold https://github.com/istio/istio.io/pull/11313

the imageType field of ProxyConfig is mismatch.
![image](https://user-images.githubusercontent.com/4354057/168830909-f41114bd-62f4-4704-8695-8732e2cddba2.png)

https://istio.io/latest/docs/reference/config/networking/proxy-config/#ProxyImage

IMO, `image.type` is better than `image.imageType`, I prefer to change the api.
@douglas-reid @howardjohn @mandarjog, WDYT?

**Comment by xichengliudui** [comment]
/assign
wait for confirmation

**Comment by xichengliudui** [comment]
ping

**Comment by douglas-reid** [comment]
@zirain i don't know this to be the case here, but i've seen field names like `type` be avoided in the past in case that leads to funny issues in code generation.

**Comment by zirain** [comment]
> @zirain i don't know this to be the case here, but i've seen field names like `type` be avoided in the past in case that leads to funny issues in code generation.

if it's reasonable, let's just correct the doc now.

**Comment by zirain** [comment]
@xichengliudui would you like to send a PR to fix the doc in istio/api repo?

**Comment by xichengliudui** [comment]
> 

sure, I'll submit the pr
