### ISSUE TITLE
Release 1.13.4 "istioctl analyze" started showing invalid warning messages

### ISSUE THREAD

**Issue by soumyaparui** [istio/istio#38986]
### Bug Description

"istioctl analyze" command in the latest istio release 1.13.4 started showing some strange warning messages:
`2022-05-18T02:32:02.542574Z     warn     core/v1/Namespace resource [/sample-namespace] could not be found`

This was not there in previous releases.

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.13.2
data plane version: 1.13.2 (10 proxies)
$ kubectl version --short
Client Version: v1.22.0
Server Version: v1.22.6
```

**Comment by soumyaparui** [comment]
@zirain You may have a look

**Comment by zirain** [comment]
prev PR has regression, it's reverted.

**Comment by dimitarshenkov** [comment]
same istiod v1.14.1

**Comment by GregHanson** [comment]
@zirain still in 1.14.2

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/40184, will land in next minor release.
