### ISSUE TITLE
CDS and EDS will be partially lost when the network connection from istiod to  remote APIServer is abnormal

### ISSUE THREAD

**Issue by miaoyq** [istio/istio#38988]
### Bug Description

We recreate the `istiod` pods when the network connection from `istiod` to  remote `APIServer` is abnormal, two minutes later, we let the network connection returned to normal, the CDS and EDS of ingressgateway will be partially lost.

- Before reconnecting from `istiod` to remote `APIServer`, the `CDS`of ingressgateway is as follows:
```
$ istioctl pc c istio-ingressgateway-5d5b776b7b-pq76c.istio-system
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                        -         -          -             STATIC
agent                                                   -         -          -             STATIC
details.default.svc.cluster.local                       9080      -          outbound      EDS
hpa-metrics-service.kube-system.svc.cluster.local       443       -          outbound      EDS
istio-crd.istio-system.svc.cluster.local                61011     -          outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local     80        -          outbound      EDS
istiod-1-12-6.istio-system.svc.cluster.local            443       -          outbound      EDS
istiod-1-12-6.istio-system.svc.cluster.local            15012     -          outbound      EDS
istiod-1-12-6.istio-system.svc.cluster.local            15014     -          outbound      EDS
kube-dns.kube-system.svc.cluster.local                  53        -          outbound      EDS
kubernetes.default.svc.cluster.local                    443       -          outbound      EDS
metrics-service.kube-system.svc.cluster.local           443       -          outbound      EDS
productpage.default.svc.cluster.local                   9080      -          outbound      EDS
prometheus_stats                                        -         -          -             STATIC
ratings.default.svc.cluster.local                       9080      -          outbound      EDS
reviews.default.svc.cluster.local                       9080      -          outbound      EDS
sds-grpc                                                -         -          -             STATIC
xds-grpc                                                -         -          -             STATIC
zipkin                                                  -         -          -             STRICT_DNS
zipkin.istio-system.svc.cluster.local                   9411      -          outbound      EDS
```

- After reconnecting from `istiod` to remote `APIServer`, the `CDS` of ingressgatewayis as follows:
```
istioctl pc c istio-ingressgateway-5d5b776b7b-pq76c.istio-system
SERVICE FQDN                             PORT     SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                         -        -          -             STATIC
agent                                    -        -          -             STATIC
kubernetes.default.svc.cluster.local     443      -          outbound      EDS
prometheus_stats                         -        -          -             STATIC
sds-grpc                                 -        -          -             STATIC
xds-grpc                                 -        -          -             STATIC
zipkin                                   -        -          -             STRICT_DNS
```

### Version

```prose
$ istioctl version                                                                
client version: 1.9.4
control plane version: 1.12.6
data plane version: 1.12.6 (7 proxies)
$ kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.20.6-tke.17
```

### Additional Information

$ istioctl bug-report

Target cluster context: cls

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2022-05-18 10:24:21.069784 +0800 CST

The following Istio control plane revisions/versions were found in the cluster:
Revision 1-12-6:
no running Istio pods in "istio-system"

The following proxy revisions/versions were found in the cluster:

Fetching proxy logs for the following containers:

default/details-v1/details-v1-c5d4c46c5-6jvpc/details
default/details-v1/details-v1-c5d4c46c5-6jvpc/istio-proxy
default/productpage-v1/productpage-v1-558d748d94-8wcbc/istio-proxy
default/productpage-v1/productpage-v1-558d748d94-8wcbc/productpage
default/ratings-v1/ratings-v1-5cd5486d45-vgx7c/istio-proxy
default/ratings-v1/ratings-v1-5cd5486d45-vgx7c/ratings
default/reviews-v1/reviews-v1-566bcb47c4-xc5qc/istio-proxy
default/reviews-v1/reviews-v1-566bcb47c4-xc5qc/reviews
default/reviews-v2/reviews-v2-848dd747c5-d6cjp/istio-proxy
default/reviews-v2/reviews-v2-848dd747c5-d6cjp/reviews
default/reviews-v3/reviews-v3-5947f7b997-r7c2l/istio-proxy
default/reviews-v3/reviews-v3-5947f7b997-r7c2l/reviews
istio-system/istio-ingressgateway/istio-ingressgateway-5d5b776b7b-pq76c/istio-proxy
prom-0u3pw1a1/proxy-agent/proxy-agent-8597d5fff6-krjbm/proxy-agent

Fetching Istio control plane information from cluster.

The following fetches are still running: 
  kubectl get --all-namespaces logconfigs.cls.cloud.tencent.com,podmonitors.monitoring.coreos.com,probes.monitoring.coreos.com,prometheuses.monitoring.coreos.com,prometheusrules.monitoring.coreos.com,servicemonitors.monitoring.coreos.com,tkeserviceconfigs.cloud.tencent.com,volumesnapshotclasses.snapshot.storage.k8s.io,volumesnapshotcontents.snapshot.storage.k8s.io,volumesnapshots.snapshot.storage.k8s.io -o yaml

Running istio analyze on namespace default.
Running istio analyze on namespace istio-system.

**Comment by howardjohn** [comment]
Do you have logs from Istiod on restart? This should not happen, so definitely a bug if it is

**Comment by miaoyq** [comment]
[2022-05-19T08.log](https://github.com/istio/istio/files/8727633/2022-05-19T08.log)
@howardjohn I tried to use the master branch to test and found the same problem.

**Comment by miaoyq** [comment]
https://github.com/istio/istio/blob/b0509f84d135a9853f01161aa205ebf71422d744/pkg/kube/multicluster/secretcontroller.go#L349:L353

**Comment by miaoyq** [comment]
@howardjohn Maybe we should have a retry when the callback is return error. 

https://github.com/istio/istio/blob/b0509f84d135a9853f01161aa205ebf71422d744/pkg/kube/multicluster/secretcontroller.go#L349:L353

**Comment by howardjohn** [comment]
Ah this is for multicluster?

**Comment by miaoyq** [comment]
@howardjohn yes

**Comment by hzxuzhonghu** [comment]
This is because cluster adding will be tried only once, when the connection to remote kube-apiserver failed, then we will miss the remote cluster. 

Looks the fault radius is very large

**Comment by hzxuzhonghu** [comment]
I think this is fixed by https://github.com/istio/istio/pull/40542
