### ISSUE TITLE
Envoy response code not as expected with AuthorizationPolicy applied for GRPC services

### ISSUE THREAD

**Issue by priyanka-operant** [istio/istio#38984]
### Bug Description

Trying to get AuthorizationPolicy and RequestAuthentication to work as per https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#require-a-valid-token
for a GRPC service.

For an HTTP service, Envoy responds with 403 Forbidden for an empty token as expected. However for a GRPC service, Envoy responds with 200 OK and no response flags nor erroneous GRPC response status like UNAUTHENTICATED / code: 16.

Here are the access logs from the proxy:
`
"POST /hipstershop.CheckoutService/PlaceOrder HTTP/2" 200 - rbac_access_denied_matched_policy[ns[dev]-policy[valid-authentication-control-checkoutservice-ajroh]-rule[0]] - "-" 0 0 0 - "-" "grpc-go/1.22.0" "4aaa6619-efa5-4aca-8704-728f5babb5de" "checkoutservice:5050" "-" inbound|5050|| - 192.168.49.253:5050 192.168.54.40:58958 outbound_.5050_._.checkoutservice.dev.svc.cluster.local -
`

I'd like to keep track of requests with invalid tokens for GRPC requests as well, but for that to happen, the response status should be something that helps differentiate from successful responses.

### Version

```prose
istioctl version 
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (16 proxies)
Kubernetes version: v1.21.9-eks-0d102a7
```

**Comment by howardjohn** [comment]
gRPC always returns 200: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

**Comment by tannguyen244** [comment]
@howardjohn How to fix it, This is confuse for information in access log.
