### ISSUE TITLE
Unable to install multi-cluster on Rancher RKE - Wrong API endpoint used by Istiod?

### ISSUE THREAD

**Issue by mfornasa** [istio/istio#38997]
### Bug Description

I am installing Istio multi-cluster following the [Primary-Remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote/)  documentation. I have two cluster:
* `cluster1` is a RKE cluster
* `cluster2` is K3S cluster

I executed the procedure described [here](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/) for sharing certificates between the two cluster.

However, `istiod` on `cluster1` fails to contact cluster API, resulting in logs like the following ones:

```
2022-05-18T13:46:04.736437Z	error	kube	failed to list CRDs: Get "https://rancher.[REDACTED IP ADDRESS].sslip.io/k8s/clusters/c-m-zpsxvqgp/apis/apiextensions.k8s.io/v1/customresourcedefinitions": x509: certificate signed by unknown authority
```

and failures in authenticating the remote cluster:
```
2022-05-18T11:06:02.723850Z	error	ads	Failed to authenticate client from 10.42.2.6:48166: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "k3s": Post "https://rancher.[REDACTED IP ADDRESS].sslip.io/k8s/clusters/c-m-zpsxvqgp/apis/authentication.k8s.io/v1/tokenreviews": x509: certificate signed by unknown authority

```

One problem is that the server answering at `https://rancher.[REDACTED IP ADDRESS].sslip.io` does have a a self-signed cert, and I can not change that on my target environment. Also, I am not sure why istio is trying to reach the Rancher upstream server API endpoint instead of accessing it locally using the API  service endpoint (which should work thanks to the `ca.crt` injected by Kubernetes at runtime).

So I have two questions:

* Is it possible to add a root ca somewhere in order for the connection to happen correctly with a self-signed cert?
or
* Is it possible to configure the API endpoint used by istio?

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (2 proxies)

$ kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.9
```

**Comment by howardjohn** [comment]
This is cluster1 trying to connect to cluster1's control plane? Or cross-cluster?

Same cluster should use the in-cluster endpoint/ca cert

**Comment by mfornasa** [comment]
I think that the errors are caused by istiod on cluster1 trying to connect to Kubernetes API on cluster1 (proxied by the endpoint on the upstream Rancher cluster)
