### ISSUE TITLE
Explain/reconcile mixer policies vs. proxy destination policies

### ISSUE THREAD

**Issue by frankbu** [istio/istio#39]
Our current top level architecture doc (https://github.com/istio/istio/blob/master/ARCHITECTURE.md) says "The proxy delegates policy decisions to the mixer ...", but we also have a couple of policies (load balancing policy and circuit breakers) that the proxy (envoy) handles on its own. These two are, in fact, already supported by `istioctl create destination-policy`. 

We need to figure out and then document how these two kinds of policies are different and why they are handled differently.

First thing we need to understand is why they are named as they are and come up with clear definitions. I can sort of imagine a definition for "destination policy" as something like "a policy that is executed at the destination of a service request". On the other hand, I'm not sure what the definition of "mixer policy" would/should be. In fact, what is the definition of "mixer" itself, and is mixer the best name for it?

**Comment by frankbu** [comment]
From slack conversation, distinguishing characteristics:

1. mixer policy comes first in a chain of policies that proxies apply so it takes priority
2. All policies at the mixer can be restricted to a specific source/destination pair. On the other hand, destination policies apply irrespective of the source, e.g., load balancing.

Suggestion to rename `destination-policy` to `destination-rule` to avoid confusion caused by overloaded word "policy".

**Comment by kyessenov** [comment]
Regarding #2, the difference is that Mixer policies are complex and can apply to a set of source-destination pairs based on properties of the source, destination, or the connection. Route rule apply to a specific source-destination pair, destination rule applies to a specific destination.

**Comment by rshriram** [comment]
Thsi has been fixed.
