### ISSUE TITLE
how can I check wasm plugin‘s logs？’

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39020]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
how can I check wasm plugin‘s logs？’
**Describe alternatives you've considered**
how can I check wasm plugin‘s logs？’
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
if you are talking about log like the following code do, it will send to stdout by default, you can check them by `kubectl logs <POD> -cistio-proxy`
https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/6240ca76120709132cc33281bd2d0f29dd8cb0e4/examples/http_headers/main.go#L88

**Comment by 13567436138** [comment]
thanks
