### ISSUE TITLE
istio-proxy connection refused for healthchecks

### ISSUE THREAD

**Issue by chriskim06** [istio/istio#39036]
### Bug Description

we're seeing connection refused in the istio-proxy logs for the rewritten healthchecks when trying to make the request to the application container.

```
2022-05-19T18:38:54.317530Z     error   Request to probe app failed: Get "http://100.119.2.105:19222/status": dial tcp 127.0.0.6:0->100.119.2.105:19222: connect: connection refused, original URL path = /app-health/borrower-sync/livez
app URL path = /status
2022-05-19T18:38:56.425320Z     error   Request to probe app failed: Get "http://100.119.2.105:19222/status": dial tcp 127.0.0.6:0->100.119.2.105:19222: connect: connection refused, original URL path = /app-health/borrower-sync/readyz
app URL path = /status
```
we have other services in the namespace and on the same node that are passing their proxy rewritten healthchecks fine. i tried looking for other issues but everything i saw was related to the ingressgateway and didn't see anything that really matched the issue we're seeing.

### Version

```prose
$ istioctl version
client version: 1.11.5
istiod version: 1.10.6
istiod version: 1.10.6
istiod version: 1.11.5
istiod version: 1.11.5
istiod version: 1.11.5
istiod version: 1.11.5
data plane version: 1.11.5 (247 proxies)
```

**Comment by howardjohn** [comment]
Are you sure your application itself is healthy? Can you try `curl http://100.119.2.105:19222/status` and `curl http//localhost:19222/status` from within the app container?

**Comment by teebu** [comment]
I'm having the same issue.

```
curl http://localhost:3000/api/relay/healthcheck/ready/ -> works
curl http://10.244.17.40:3000/api/relay/healthcheck/ready/ -> connection refused (pods ip)
```

**Comment by teebu** [comment]
The confusing part for me was it was serving perfectly fine (knative serving) just the readiness/liveness probe couldn't connect using the pod's ip.

**Comment by abhibhosale05** [comment]
> I'm having the same issue.
> 
> ```
> curl http://localhost:3000/api/relay/healthcheck/ready/ -> works
> curl http://10.244.17.40:3000/api/relay/healthcheck/ready/ -> connection refused (pods ip)
> ```
> 
> i dont see the pod ip on netstat list.
> 
> I figured out my problem. The service I was using was only listening to (127.0.0.1) localhost. I had to bind it to `0.0.0.0` ip so it listens to everything.

Hello, I am also this issue, can you please explain more about solution.

**Comment by teebu** [comment]
In my case, the service I had, was setup to only listen to 127.0.0.1. I had to modify the configuration to listen on 0.0.0.0 instead.

**Comment by teebu** [comment]
It doesn't matter the service, any service. In my case I was trying to setup sentry-relay.

**Comment by abhibhosale05** [comment]
Got it. Thank you.

**Comment by akashjain971** [comment]
@howardjohn we are facing the same issue since migrating from 1.20.2 to 1.23.3.
We have some services listening on localhost and their health checks are failing post upgrade.
We have tried configuring the Sidecar as mentioned in the docs but no luck.

The service are exposing port 8090.

```
    - name: ISTIO_KUBE_APP_PROBERS
      value: '{"/app-health/app/readyz":{"httpGet":{"path":"/health/full","port":8443,"scheme":"HTTPS"},"timeoutSeconds":2}}'
```

Error in proxy.
```
error	Request to probe app failed: Get "https://10.168.175.107:8443/health/full": dial tcp 127.0.0.6:0->10.168.175.107:8443: connect: connection refused, original URL path = /app-health/app/readyz
```

Sidecar resource configured.
```
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: test
spec:
  workloadSelector:
    labels:
      app: test
  ingress:
  - port:
      number: 8090
      protocol: TCP
      name: tcp
    defaultEndpoint: 127.0.0.1:8090
```

**Comment by howardjohn** [comment]
You need REWRITE_PROBE_LEGACY_LOCALHOST_DESTINATION. The Sidecar only impacts the non-healthcheck stuff
