### ISSUE TITLE
cluster VIPs are not correctly updated when a multi-cluster Service stub is removed

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#39039]
### Bug Description

Cluster VIPs can get into an incorrect state when multi-cluster Service stub resources are removed.

To reproduce:
1. Set Up two clusters: one local and one remote with DNS proxy enabled
2. Set up a Service example.example-namespace.svc.cluster.local in remote
3. Set up a Service example.example-namespace.svc.cluster.local in local
4. Check the debug endpoint for a control plane in local cluster at /debug/endpointz. Look for clusterVIPs for hostname example.example-namespace.svc.cluster.local.
5. Perform a DNS lookup on a pod in remote cluster and note the clusterIP returned
6. Remove the Service from remote cluster
7. Check the debug endpoint for a control plane in local cluster at /debug/endpointz. Look for clusterVIPs for hostname example.example-namespace.svc.cluster.local. Note that the removed clusterIP still exists just as in the result of 4.
8. Perform a DNS lookup on a pod in remote cluster and note the clusterIP returned is the same as 5.
9. Restart the local cluster control plane pods. 
11. Check the debug endpoint for a control plane in local cluster at /debug/endpointz. Look for clusterVIPs for hostname example.example-namespace.svc.cluster.local. Note that the clusterIP returned in 5 is no longer present.
12. Perform a DNS lookup on a pod in remote cluster and note the clusterIP returned is no longer the same as 5. It is now the clusterIP of the local cluster.

Expected Behavior:
It is expected that the cluster registry is updated when the remote services are removed. Otherwise incorrect routing may occur when a new Service is created with the old clusterIP. A restart should not be required to get the control plane in a correct state.

### Version

```prose
tested on istio 1.12.4/1.12.5
```

**Comment by hzxuzhonghu** [comment]
This is a bug if as described

**Comment by hzxuzhonghu** [comment]
I have reproduced,  thanks for the info
