### ISSUE TITLE
Istio Version 1.10.4 - HTTP/1.1"" 0 DC downstream_remote_disconnect

### ISSUE THREAD

**Issue by zohebs341** [istio/istio#39037]
### Bug Description

We are using Istio Version 1.10.4 and Azure AKS Version 1.21.7

We are getting below error in production, looks like the destination pod is responding lately which is causing this error.

Is there any default timeout for HTTP requests/responses in Istio?? As in our case, we are getting below error even if the response time is >2sec.

Full Error:

POST /xyz/abc HTTP/1.1"" 0 DC downstream_remote_disconnect - ""-"" 515 0 4969 - ""

### Version

```prose
Istio Version 1.10.4 and Azure AKS Version 1.21.7
```

**Comment by zohebs341** [comment]
@howardjohn Will you be able to assist me on this?

Error Log from Istio proxy - "POST /abc/true HTTP/1.1" 502 - via_upstream -

and sometimes 0 DC downstream_remote_disconnect. But when I checked, pods are up and running both source/destionation pods, and no pod restarts as well.

**Comment by howardjohn** [comment]
It means your client closed the conntection.. you probably need to debug your client

**Comment by zohebs341** [comment]
@howardjohn Thanks for your response. Our flow is like MicroserviceA --> Kong --> Istio --> MicroserviceB
Now here, you mean to say MicroserviceA is closing the connection(Source/Downstream)?

**Comment by howardjohn** [comment]
Istio doesn't know anything about MicroserviceA; Kong is closing it.
