### ISSUE TITLE
Getting different results with Helm x Istioctl installation

### ISSUE THREAD

**Issue by epomatti** [istio/istio#39049]
I'm following [this guide](https://istio.io/latest/docs/setup/install/helm/) to have Istio installed with Helm. As stated by the documentation:

> The Helm charts used in this guide are the same underlying charts used when installing Istio via [Istioctl](https://istio.io/latest/docs/setup/install/istioctl/) or the [Operator](https://istio.io/latest/docs/setup/install/operator/).

So one should expect the same results, regardless of the installation method. However, I get different results.

### Istioctl Installation

```sh
$ istioctl install
This will install the Istio 1.13.4 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
Making this installation the default for injection and validation.
```
```
$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   11m
istio-system      Active   10m
kube-node-lease   Active   11m
kube-public       Active   11m
kube-system       Active   11m

$ kubectl get services -n istio-system
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   10.99.102.87     <pending>     15021:32491/TCP,80:30454/TCP,443:32766/TCP   2m26s
istiod                 ClusterIP      10.109.226.198   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        2m38s
```

### Helm Installation

Following the exact steps in the [Helm guide](https://istio.io/latest/docs/setup/install/helm/):

```sh
# 1. Create a namespace istio-system for Istio components:
kubectl create namespace istio-system

# 2. Install the Istio base chart which contains cluster-wide resources used by the Istio control plane:
helm install istio-base istio/base -n istio-system

# 3. Install the Istio discovery chart which deploys the istiod service:
helm install istiod istio/istiod -n istio-system --wait

# 4. (Optional) Install an ingress gateway:
kubectl create namespace istio-ingress
kubectl label namespace istio-ingress istio-injection=enabled
helm install istio-ingress istio/gateway -n istio-ingress --wait
```

```
$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   33m
istio-ingress     Active   27m
istio-system      Active   27m
kube-node-lease   Active   33m
kube-public       Active   33m
kube-system       Active   33m

$ kubectl get services -n istio-ingress
NAME            TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                                      AGE
istio-ingress   LoadBalancer   10.0.78.127   20.245.4.2    15021:32346/TCP,80:30528/TCP,443:31973/TCP   26m

$ kubectl get services -n istio-system
NAME     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                                 AGE
istiod   ClusterIP   10.0.31.65   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP   28m
```

### Differences

There are two differences in behavior:

1. Helm creates two namespaces called `istio-system` and `istio-ingress`, whereas Instioctl installs everything under `istio-system`.
2. Helm installs service `istio-ingress`, while Instioctl installs service `istio-ingressgateway`.

Can someone help understand what the issue is here?

**Comment by MaratSaidov** [comment]
@ericvn the problem is still relevant, needs the support.

**Comment by ericvn** [comment]
Hopefully, someone will investigate this soon.

**Comment by zirain** [comment]
seems like https://github.com/istio/istio.io/pull/11734, will investigate next week.

**Comment by frankbu** [comment]
> There are two differences in behavior:
>
> 1. Helm creates two namespaces called `istio-system` and `istio-ingress`, whereas Instioctl installs everything under `istio-system`.
> 2. Helm installs service `istio-ingress`, while Instioctl installs service `istio-ingressgateway`.

Difference 2 is fixed by https://github.com/istio/istio.io/pull/11734.

Difference 1 is because the gateway is being installed using the default profile in the above `istioctl` command, which is not the recommended approach. If the minimal profile is used, instead, and then the gateway installed separately as recommended at the top of [this document](https://istio.io/latest/docs/setup/additional-setup/gateway/), then it would be the same as helm.
