### ISSUE TITLE
Various WASM test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39063]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1527648505185701888

https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc_istio_postsubmit/1527635431762432000

https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc_istio_postsubmit/1527648505345085440

Seem to be from recent WASM PRs

**Comment by ingwonsong** [comment]
First issue should be cleared by #39071

**Comment by ingwonsong** [comment]
The flakes in Second/Third are gone by https://github.com/istio/istio/issues/39063

**Comment by ingwonsong** [comment]
After merging the integration test back, there is no flakiness yet.
