### ISSUE TITLE
Allow to configure LoadBalancerClass for service in gateway helm chart

### ISSUE THREAD

**Issue by Legion2** [istio/istio#39079]
**Describe the feature request**
I want to set the `spec.loadBalancerClass` of the Service in the gateway helm chart, see [Specifying class of load balancer implementation](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class).

**Describe alternatives you've considered**
Use annotations on the Service to select load balancer implementation.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
The AWS Load Balancer Controller supports this field to select the load balancer controller instead of the in-tree controller. The `spec.loadBalancerClass` field was added in kubernetes v1.22.

**Comment by howardjohn** [comment]
We cannot add an option for every single field in Kubernetes to the charts. If you want to configure advanced fields, i recommend following steps like https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/
