### ISSUE TITLE
Blue/Green Deployment ENABLE_MULTICLUSTER_HEADLESS

### ISSUE THREAD

**Issue by jmajoor** [istio/istio#39093]
I have a blue/green deployment and I need to make sure that pods in the blue version only communicate with other pods in the blue version and the same for green. This was not a problem on version 1.10 as we used headless services for this and those stayed within the cluster. 

However with version 1.13 it seems that `ENABLE_MULTICLUSTER_HEADLESS` is by default enabled and this will totally break our deployment. I am not even sure `ENABLE_MULTICLUSTER_HEADLESS` is by default enabled either, as the pilot documentation claims the default is false and the operator documentation claims the default is true.

My question is where in my istio operator yaml file do I need to specify this?

**Comment by howardjohn** [comment]
values.pilot.env.ENABLE_MULTICLUSTER_HEADLESS="false" will do it

**Comment by jmajoor** [comment]
Thanks.  Maybe you can help me out how to find this configuration setting. The documentation always confuses me.
`values` as far as I know, are basically helm chart values, but helm chart values are still in alpha state and the documentation links to the 1.5 version of istio.

Is using `values` better than for example `components.pilot.k8s.env` or is `values` the only / best way to do this?

**Comment by howardjohn** [comment]
Its the same thing, I just remember the `values` syntax off hand and not the `components.` one :-)

**Comment by jmajoor** [comment]
Thanks again.
