### ISSUE TITLE
Make ingress/egress service names configurable

### ISSUE THREAD

**Issue by lachie83** [istio/istio#391]
It currently looks like the service name that the ingress/engress proxies are looking for is derived from the arguments passed from to the container runtime. This yields the expectation that istio-ingress/istio-egress k8s services must exist. Can you either LMK how to configure these names or make them configurable?

https://github.com/istio/istio/blob/master/install/kubernetes/istio-auth-with-cluster-ca.yaml#L213
```
        args: ["proxy", "egress", "-v", "2"]
```

**Comment by andraxylia** [comment]
Those are just the arguments with which the proxy is started, to tell its role. 
If you are asking about the istio-egress service name, it can be changed from the yaml files. 
Is this an issue or a question? If question, I encourage you to post questions to istio-dev mailing list.

**Comment by lachie83** [comment]
From the log files I see the following. I assume that the `--service-cluster istio-proxy` is the kubernetes service name it's expecting to see. Is that correct?
```
I0608 21:32:04.006228       1 watcher.go:154] Envoy command: [-c /etc/envoy/envoy-rev1.json --restart-epoch 1 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster istio-proxy --service-node egress]
```
If I change the service name from isitio-egress to something else then I see this behavior when running through https://istio.io/docs/tasks/egress.html
```
root@sleep-1345314204-pq1r2:/# curl http://externalbin/headers
no healthy upstream
```
If I recreate the istio-egress service on kubernetes then things work again. 

Happy to move this over to the istio-dev mailing list.

**Comment by andraxylia** [comment]
If you get no healthy upstream, it's a valid issue.

It is not related to "--service-cluster istio-proxy", this is an Envoy specific config. BTW, Envoy's cluster is a different concept than k8s cluster.

"--service-cluster <string>
(optional) Defines the local service cluster name where Envoy is running"

**Comment by lachie83** [comment]
Okay let me keep digging into my stack here to figure what's breaking

**Comment by ijsnellf** [comment]
@lachie83: You can set the egress address via the egressProxyAddress field in the service mesh: https://istio.io/docs/reference/config/service-mesh.html

The name of the ingress service in Kubernetes should not matter for the rest of the Istio components.

**Comment by ldemailly** [comment]
closing this but please reopen (in https://github.com/istio/issues/issues ) if needed
