### ISSUE TITLE
Prevent the pilot from pushing to gateway proxies when private services are created

### ISSUE THREAD

**Issue by henrysecond1** [istio/istio#39110]
**Describe the feature request**

We would like to prevent the pilot from pushing to gateway proxies when services are created with annotation `networking.istio.io/exportTo: ~`.

Our cluster a huge churn rate of k8s services, and that services don’t need istio. We used `Sidecar` CRD and `networking.istio.io/exportTo: ~` annotation to not affect any other services using istio. However, the above options do not prevent pushes to gateway proxies. As a result, we experienced high CPU usage on gateway proxies due to a lot of pushes (even if there is no need to push)

I tested two methods to solve this issue. 
Both methods seem to work fine, but I’m not sure if there is anything that I’ve not considered.

1. Filter service with `networking.istio.io/exportTo: ~` to not be discovered by pilot (https://github.com/henrysecond1/istio/commit/c158cd161a1191b1c59892d7c7123c0611420e49)

2) Check dependency of gateway proxies (https://github.com/henrysecond1/istio/commit/81ab458c194a5764bc20d38d9c3091c18057f3ef)

Any help or advice would be greatly appreciated.

**Describe alternatives you've considered**

- `Sidecar` CRD - only works for sidecar proxies, not gateway proxies
- `discoverySelector` - we can’t entirely exclude namespaces from discovery, so it was not our option. If there is a service-level discovery selector, it would be great.
- `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` - AFAIK,  this option can’t prevent push operations. Only the cluster size of gateway proxies decreases.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
After a first look, i think `Check dependency of gateway proxies` looks better

**Comment by hzxuzhonghu** [comment]
@henrysecond1 Please file a pr

**Comment by howardjohn** [comment]
Off the top of my head it seems like we should be able to optimize PILOT_FILTER_GATEWAY_CLUSTER_CONFIG to not push as well perhaps?

We do need some other fixes to make that config safe though

**Comment by henrysecond1** [comment]
> Off the top of my head it seems like we should be able to optimize PILOT_FILTER_GATEWAY_CLUSTER_CONFIG to not push as well perhaps?

Thank you for the opinion and I agree with that. If the pilot pushes to gateway proxies only when it's necessary, our problem will be solved. Our method is a kind of workaround

**Comment by dclendenan** [comment]
@hzxuzhonghu  can you please clarify why you think the `Check dependency of gateway proxies` option was preferred here?  If `None Instance` services are [visible to no one](https://github.com/istio/istio/blob/990ae1d76932dafc3afb0eae50f6d40875bcb6ce/pkg/config/visibility/visibility.go#L32-L33), why is there a push for them to any other Mesh components?
