### ISSUE TITLE
Routing to original DC after a failover hop

### ISSUE THREAD

**Issue by Purushotham233** [istio/istio#39111]
**Describe the feature request**
Routing to original DC after the failover for one hop in a Call-graph.

**Detailed:**
As per the below service graph, we like to get the RED traffic back to DC1 after ServiceB. We are looking for the ability/configurations to make the proxy at Service-B do the following:

1. Remember the source-DC(say origin-DC) of the downstream call
2. Tie/Relate the corresponding upstream calls resulting due to the downstream calls.
3. **Prefer calling the upstream systems in the origin-DC instead of local-DC.**

By default Service-B in DC2 would make all upstream calls to Service-C in the same DC i.e., DC2.

![Helios_with_Istio_issue](https://user-images.githubusercontent.com/5907779/170421956-8d0df2bf-e9f6-4ea7-b5a1-44101a9a10ac.png)

**Motivation:**
Lesser capacity requirement.

With the above capability, after the ServiceB failure in DC1, only ServiceB in DC2 needs to scale-out for 100% traffic. All the upstream systems further in the chain(i.e., Service C onwards) can remain the same without having to scale-out.

**Describe alternatives you've considered**
Could not find a solution supporting this traffic routing requirement.

**Affected product area (please put an X in all that apply)**
None of the below. It affects the Capacity footprint.
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Currently our infrastructure is primarily in our Private DC and in the process of hybrid journey.

**Comment by hzxuzhonghu** [comment]
isn't locality failover work for you?

**Comment by Purushotham233** [comment]
@hzxuzhonghu 
Thanks for the reply. I have updated the pic above to explain our query better. PTAL.

If you see this is achievable with locality failover, request you to explain it little further.

**Comment by ivpr** [comment]
@hzxuzhonghu When Service B in DC2, as a part of handling the call received from Service A in DC1, calls Service C, it should prefer Service C endpoints in DC1 instead of Service C endpoints in DC2 while still having the ability to failover to Service C in DC2 incase the pods are unhealthy in DC1. 
Essentially in the envoy configuration for a pod of Service B in DC2, Service C endpoints in DC1 should have priority 0 and Service C endpoints in DC2 should have priority 1

Can this be achieved with locality failover? 

PS: We can identify the call that came from Service A in DC1 using some header(eg: x-preferred-region: DC1) and Service B can pass along the header while making the upstream call to Service C. We can a VirtualService and a Destination Rule subset to have different trafficPolicies based on x-preferred-region header

**Comment by hzxuzhonghu** [comment]
Unless serviceB is stateful and pass some attributes of DC1/DC2 when calling Service C, otherwise I can not think of a way achieving your requirement. Locality failover does not satisfy here

**Comment by Purushotham233** [comment]
@hzxuzhonghu 
Service-A(i.e., first hop in the call graph) can add a header `x-preferred-region: DC1`. And other services in the call-graph can pass on the header as is in the upstream calls. 

Will this be sufficient for Istio to prefer the endpoints in the desired order?
> Unless serviceB is stateful and pass some attributes of DC1/DC2 when calling Service C, otherwise I can not think of a way achieving your requirement. Locality failover does not satisfy here

**Comment by hzxuzhonghu** [comment]
You still need to label Service C differently, then you can make use vs HTTP match :
-   x-preferred-region: DC1
     destination:  
           subset: dc1

**Comment by Purushotham233** [comment]
Yes. Using http-match in VirtualService, the requests destined to Service-C can be forked and subjected to DC specific subsets.

While defining the subsets we ran into challenges. How to define the subset (say for DC1) that does the following:
1. Prefer the endpoints of DC1.
2. If DC1 endpoints are down/does-not-exist then use other endpoints.

**Comment by Purushotham233** [comment]
Came across Envoy's [LoadBalancer subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) that can solve this use-case. However the same is not supported by Istio yet.

@hzxuzhonghu Kindly share your comments.

**Comment by howardjohn** [comment]
Currently we have:
```
failoverPriority:
- "topology.istio.io/network"
- "topology.kubernetes.io/region"
- "topology.kubernetes.io/zone"
- "topology.istio.io/subzone"
```


I think what we can add is ability to specify explicit value

```
subset: west
  failoverPriority:
  - "topology.kubernetes.io/region=us-west"
```

Then in VS you can match `my-header: send-to-west` and send to `subset: west`. How you get that header is up to you - you could have all requests from West add the header and propogate it, etc.

So the only change to Istio would be adding the ability to add `=explicit value` to `failoverPriority`.

**Comment by Purushotham233** [comment]
@howardjohn 

Currently our infra is spread across three regions/data-centers. DCI, DC2 are private. DC3 is public. 

The desired failover policy is 
- DC1 fails-over to DC3(public)
- DC2 fails-over to DC3(public)
- DC3 fails-over to DC1 or DC2

So essentially there are 2 capabilities needed:
1. failover as per the desired policy.
2. Route to origin DC for subsequent upstream calls.

The solution based on failoverPriority achieve cap-2. Can we solve for cap-1 as well?
> So the only change to Istio would be adding the ability to add =explicit value to failoverPriority.


Alternatively, a solution based on istio's failover  where cap-1 is readily possible. And add a provision to override the priority0 region which is local by default. 

> In the context of all there DCs.
>  subset: DC1
>      priority0: DC1.    (New Optional paramaeter)
>      failover:
>         - from: DC2
>            to: DC3
>         - from: DC3
>            to: DC3

Kindly share your views and comments. Thank you.

**Comment by howardjohn** [comment]
I think there are two ways we could tweak the API to support this, and one not-great way you could do it yourself today.

1. API Tweak 1 - allow failoverPriorities to take a k=v, not just k.
Usage:
```
subset: dc3
failoverPriority:
  - "topology.kubernetes.io/region=dc1"
  - "topology.kubernetes.io/region=dc2"
```
2. API tweak 2 - allow `failover` and `failoverPriorities` to work together, replacing `failover` to mean "from this region to this region" to "from this <top failoverPriority label> to this <top failoverPriority label>". I don't love this idea
3. Existing option. Essentially hack (1), and create a node label per DC. Then you would configure
```
subset: dc3
failoverPriority:
  - "topology.kubernetes.io/region-dc1"
  - "topology.kubernetes.io/region-dc2"
```

and on the nodes label each like `topology.kubernetes.io/region-dc1: true` or whatever

**Comment by Purushotham233** [comment]
@howardjohn 
Not able to see how Tweak-1(using region label twice) could meet the requirements. Please help me understand if I am missing something here.

For subset: dc3, desired priority order of endpoint is
- priority-0: dc3 (i.e., subset respective endpoints)
- priority-1: any.

As per the below failoverPriority no endpoints will match both labels. No there wont be any priority-0 endpoints. priority-1 would be dc1 endpoints.
```subset: dc3
failoverPriority:
  - "topology.kubernetes.io/region=dc1"
  - "topology.kubernetes.io/region=dc2"
```

However with Tweak-1 support, on the lines of Tweak-3, I think we could use the below config.
<img width="1425" alt="Screenshot 2022-08-11 at 10 53 17 PM" src="https://user-images.githubusercontent.com/5907779/184196778-a149bcfc-caf7-4f5a-9733-10b4018f11d8.png">

**Comment by costinm** [comment]
What if you have DC3 also making same calls - with same requirement that second call goes to DC3 if source was in DC3 ?

I assume most real prod users have multiple regions for reliability - having just 2 and the clients in only one is hopefully not common.

Would a runtime (request) hint work better ? With the added header based you can target any individual endpoint, per request - but some similar header can hint or influence following requests. Would require few lines of code for the user ( or some wasm ), but you can probably implement any policy without complex configs.
