### ISSUE TITLE
Intermittent Gaps in metrics of Istio sidecar for application

### ISSUE THREAD

**Issue by doverk96** [istio/istio#39139]
Placing label: sidecar.istio.io/inject=true on deployment, exposes metrics like istio_request_duration_milliseconds_sum, istio_request_duration_milliseconds_count and using Prometheus+Grafana, we have built a dashboard on it.
Suddenly, we are observing intermittent gaps in this dashboard, metrics are just not coming for a duration of time and then again they start coming. This is happening regularly now.

On inspecting application pods, have observed that sidecar **istio-proxy** is getting killed with Reason: OOMKilled - exit code: 137. 

Could this be the issue for metrics not coming or is there any other way to debug this ?
If OOM killing of container is the issue, can you help us with the memory and cpu requirements of istio-proxy sidecar container ?

**Comment by doverk96** [comment]
@douglas-reid

**Comment by douglas-reid** [comment]
If the sidecar proxy is indeed getting killed, that would explain the gap in metrics. 

The general guidelines are: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/#cpu-and-memory

**Comment by howardjohn** [comment]
Closing as is this is stale and without followup
