### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [istio/istio#39155]
### Bug Description

At:
https://github.com/istio/istio/blob/34d88379deaabc35231463663ac3738c5fff37a6/cni/pkg/taint/taintcontroller.go#L57-L63

Within the loop for `for _, config := range ts.configs {`, variable `config` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec). 
The function closure refers to free variable `config` such that it is using the address `&config`:  
```
func(options *metav1.ListOptions) {
				options.LabelSelector = config.LabelSelector
}
```
This closure is embedded in an object returned by `buildPodController()`, and then appended to `c.podController`, which escapes the loop:
https://github.com/istio/istio/blob/34d88379deaabc35231463663ac3738c5fff37a6/cni/pkg/taint/taintcontroller.go#L66-L67

Hence, all instances of `&config` (and `&config.LabelSelector`) within the loop may refer to the last configuration updated by the loop. As a consequence, `c.podController` may hold multiple instances of the same `&config.LabelSelector`, while its intention is to use the different configurations.

Here function `buildPodController()` stores the function closure into a `Store`, which will be appended to `c.podController`:
https://github.com/istio/istio/blob/34d88379deaabc35231463663ac3738c5fff37a6/cni/pkg/taint/taintcontroller.go#L82-L83
```
func buildPodController(..., source cache.ListerWatcher) cache.Controller {
        tempstore, tempcontroller := cache.NewInformer(source, ...)
        return tempcontroller
}

func NewInformer(lw ListerWatcher, ...) (Store, Controller) {
        return clientState, newInformer(lw, objType, resyncPeriod, h, clientState, nil)
}

func newInformer(lw ListerWatcher, ...) Controller {
        cfg := &Config{
                ListerWatcher:    lw,
        }
        return New(cfg)
}
```

For example, suppose `ts.configs` contains {c1, c2, c3}, then finally `c.podController` will look like:
```
c.podController = { 
    &controller{
	config: Config{
	    ListerWatcher:   func(options *metav1.ListOptions) { options.LabelSelector = c3.LabelSelector },
        }
    },
    &controller{
	config: Config{
	    ListerWatcher:   func(options *metav1.ListOptions) { options.LabelSelector = c3.LabelSelector },
        }
    },
    &controller{
	config: Config{
	    ListerWatcher:   func(options *metav1.ListOptions) { options.LabelSelector = c3.LabelSelector },
        }
    },  
 }
```

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

A fix is to avoid storing the address of the shared variable config:
```
	for _, config := range ts.configs {
                label := config.LabelSelector  // avoid sharing
		podListWatch := cache.NewFilteredListWatchFromClient(
                         ...
			func(options *metav1.ListOptions) {
				options.LabelSelector = label
			},
		)
```

**Found by static analyzer #deepgo.**

### Version

```prose
Most recent version.
```

**Comment by howardjohn** [comment]
@stewartbutler is this code still in use? Seems like a pretty critical bug

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/39977
