### ISSUE TITLE
External Authorization (custom policy) (Beta ETA)

### ISSUE THREAD

**Issue by JJRdec** [istio/istio#39169]
Hi there,

Can you give me a timeline for when the External Authorization feature will graduate to Beta or assurance that the feature is still progressing?

We are planning on using Istio service mesh with the External Authorization feature in production in Q3. There is a level of urgency to this as we will need to look at alternative solutions. 

Many thanks in advance :) 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by aryan16** [comment]
We are planning to move it to beta in Q3.

**Comment by howardjohn** [comment]
closing as this is answered
