### ISSUE TITLE
Ingressgateways not coming up on istio >= 1.11 with a lot of certificates

### ISSUE THREAD

**Issue by donbowman** [istio/istio#39167]
### Bug Description

the #37272 issue was closed as completed, but the problem remains, and its a complete blocker with no workaround.

we are blocked from upgrading istio 1.10 to later, the later versions just won't come online.

See #37272 for the details

### Version

```prose
Below is the working version, later versions show the problem

istioctl version
client version: 1.10.6
control plane version: 1.10.6
data plane version: 1.10.6 (103 proxies)
```

**Comment by howardjohn** [comment]
What do the istiod logs show? In the previous issue you mentioned 'nothing interesting' but there was really more like _nothing at all_ related to secrets - which there would be even on success?

**Comment by jamiechapmanbrn** [comment]
I've attached full logs for istiod and istio-ingressgateway.
[istiod_logs.txt](https://github.com/istio/istio/files/8800039/istiod_logs.txt)
[istio_gateway_logs.txt](https://github.com/istio/istio/files/8800040/istio_gateway_logs.txt)

**Comment by klarose** [comment]
FWIW, I asked about this in the Envoy slack, and a user there pointed me to https://github.com/envoyproxy/envoy/issues/19774. I'm pretty sure we tested against a version with this fix. @jamiechapmanbrn can you confirm? I'm not sure if those logs you attached contain the fix for that linked issue. If they don't, it may be worth repeating the test against a version which does, gathering the logs from it.

**Comment by howardjohn** [comment]
Is it _never_ coming up? I can almost reproduce and logs looks similar, but I end up with it becoming ready in about 4min for 2k secrets. Which is obviously unacceptable speed - just curious if you see the same. Working on some ideas to improve it

**Comment by howardjohn** [comment]
We need an Envoy side fix I think. I opened https://github.com/envoyproxy/envoy/issues/21518 which also has a WIP change which brought startup from 4min to 4s for my test.

**Comment by jamiechapmanbrn** [comment]
For us it's never coming up. If I left it for hours it would just sit there, no new logs or any indication of life.
Occasionally, one will come up. For example if istiod restarted recently or I restart it while an istio-ingressgateway is trying to start they seem to come up, or if I restart istio-ingressgateway multiple times it might come up once.

**Comment by jamiechapmanbrn** [comment]
> FWIW, I asked about this in the Envoy slack, and a user there pointed me to [envoyproxy/envoy#19774](https://github.com/envoyproxy/envoy/issues/19774). I'm pretty sure we tested against a version with this fix. @jamiechapmanbrn can you confirm? 

I tested the upgrade with 1.13.4, As far as I'm aware that includes this fix.

As far as numbers, I hit this with 170 gateways,virtualservices and certificates.

**Comment by howardjohn** [comment]
Fixed by https://github.com/envoyproxy/envoy/pull/21600. Thank you for the report!
