### ISSUE TITLE
source.user attribute (mTLS auth principal) has incorrect value 

### ISSUE THREAD

**Issue by liminw** [istio/istio#3917]
When I was testing Bookinfo sample with Istio 0.5 release, I found that "source.user" attribute for requests calling "productpage" service was set to "cluster.local/ns/istio-system/sa/default". However, it is the ingress service that calls "productpage" service, and Ingress service is deployed with "istio-ingress-service-account". So we expect "source.user" being set to "cluster.local/ns/istio-system/sa/istio-ingress-service-account", instead of "cluster.local/ns/istio-system/sa/default". 

In addition, after I upgraded to Istio 0.6 release, "source.user" becomes an empty string, which is obviously wrong. This is completely breaking Istio RBAC and any authorization system on Mixer because the auth principal is missing.

**Comment by douglas-reid** [comment]
We need an e2e test case that is validating this use case as well.

**Comment by liminw** [comment]
Actually, after debugging (with help from @qiwzhang and @ldemailly), we found that for Istio 0.6 release, source.user is set to "cluster.local/ns/istio-system/sa/default" for all mesh services except Ingress. For Ingress service, "source.user" was set to empty, which was expected. I slightly changed RBAC policy and it works now. 

The reason I only see empty value for "source.user" in 0.6 Istio is that, from 0.6 release, Ingress starts calling Mixer. Before that, Ingress does not call Mixer. 

Now the only issue left is ingress service identity is set to  "cluster.local/ns/istio-system/sa/default", rather than the Ingress service account. Is that expected?

**Comment by liminw** [comment]
This is the set of attributes for "productpage" service. Note that source.serviceAccount is istio-ingress-service-account, but source.user is set to cluster.local/ns/istio-system/sa/default. 

2018-03-03T00:50:13.516954Z     debug   Attribute Bag: 
connection.mtls               : true
context.protocol              : http
destination.ip                : [0 0 0 0 0 0 0 0 0 0 255 255 10 8 1 14]
destination.labels            : {destination.labels map[pod-template-hash:1658261386 version:v1 app:productpage] 0xc420ddb380}
destination.service           : productpage.default.svc.cluster.local
destination.uid               : kubernetes://productpage-v1-5b9d6b57db-6mxnd.default
request.headers               : {request.headers map[user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 upgrade-insecure-requests:1 :path:/productpage cache-control:max-age=0 x-b3-sampled:1 accept-encoding:gzip, deflate accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 x-forwarded-for:10.8.2.1 accept-language:en-US,en;q=0.9 x-ot-span-context:460857f3adf33548;460857f3adf33548;0000000000000000 x-envoy-internal:true x-b3-spanid:460857f3adf33548 :authority:35.202.47.142 x-b3-traceid:460857f3adf33548 x-request-id:e459734f-e7bb-9b7f-a01f-d3c8228fa1a9 x-forwarded-proto:http content-length:0 :method:GET] 0xc420ddb380}
request.host                  : 35.202.47.142
request.method                : GET
request.path                  : /productpage
request.scheme                : http
request.time                  : 2018-03-03 00:50:13.512687487 +0000 UTC
request.useragent             : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
source.ip                     : [10 8 2 17]
source.port                   : 36988
source.uid                    : kubernetes://istio-ingress-7bb5cf4c4c-s8p9c.istio-system
source.user                   : cluster.local/ns/istio-system/sa/default
---
destination.namespace         : default
destination.serviceAccount    : bookinfo-productpage
source.labels                 : map[istio:ingress pod-template-hash:3661790707]
source.namespace              : istio-system
source.service                : istio-ingress.istio-system.svc.cluster.local
source.serviceAccount         : istio-ingress-service-account

**Comment by myidpt** [comment]
Yes, I think the source.user is incorrect here. Thanks for digging into this. Will look into it.

**Comment by wattli** [comment]
This is fixed in https://github.com/istio/istio/pull/4115

**Comment by ldemailly** [comment]
it will auto close when that PR merges
