### ISSUE TITLE
istio ingress helm chart needs more variables/extensibility

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#39180]
**Describe the feature request**

Need to be able to specify more settings for the ingress deployement istio chart

Specifically we need to change:

```json
{ "spec": { "template": { "spec": { "terminationGracePeriodSeconds" ...
```
and
```json
{ "spec": { "template": { "spec": {"containers":
            [ { "name": "istio-proxy", "lifecycle": { "preStop": ...
```

But having generic placeholder in each section, like there is already for instance
```
{{ toYaml $gateway.additionalContainers | indent 8 }}
```
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L90-L269

would allow customization/extensibility without having to change/patch/fork the chart to support everything possible to change in a k8s object

**Describe alternatives you've considered**

We're using  `kubectl patch deployment` as a helmfile post sync but that cause 2 RS and churn

note: I may be missing an easier option

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

ps: I wonder if additionalContainers can be used to do what we need by cheating on the annotation

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/39079#issuecomment-1135133605

**Comment by ldemailly** [comment]
Ah interesting / thanks @zirain ! so https://docs.solo.io/gloo-edge/latest/installation/gateway/kubernetes/helm_advanced/ suggests to use `helm --post-renderer` with a kustomize script (I wonder if helm can maybe just use `kubectl apply -k` come to think of it)

helmfile doesn't support this yet out of the box (https://github.com/roboll/helmfile/issues/1530) but might be able to use `--args` (tbd)

All this being said; while I agree you can't have istio support every single possible change

- lifecycle hooks are key to errorless upgrades
- there are already a million variables so we could have 2 or 3 more
- but then maybe _instead_ we can have just a block in each main section for extensions ? (that won't help for some cases like overrides of hardcoded items but ...)
-

**Comment by howardjohn** [comment]
We talked about this in WG meeting last week (https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit#heading=h.h29v64lpb3bi), consensus was to push for last-mile customizations for these use cases in most cases

**Comment by eytanhanig** [comment]
@howardjohn I can appreciate that the Istio team has other priorities and adding values ad hoc make not be realistic. Were Istio users to open PRs adding new variables to the Helm charts/values files ourselves, would the team be willing to review and approve them?

**Comment by howardjohn** [comment]
No, its not about reviews, but ongoing maintenance and complexity (both for maintainers _and users_). There is little point to having a helm chart that simply re-names and re-orders every field of the Kubernetes API - if that is desired, just creating a Deployment from scratch would be sufficient.

**Comment by apj0nes** [comment]
@howardjohn I get what you are saying, but would you be open to a PR adding the ability to specify `terminationGracePeriodSeconds`? I feel it is a common enough use case that users running Istio behind an AWS NLB/ALB would want to change this value, the default 30s is often too short.
