### ISSUE TITLE
Test Failure: security/tests/integration/certificateRotationTest

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#3919]
From: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3913/istio-presubmit/6070/

```
I0302 22:34:20.343] 2018-03-02T22:34:20.341870Z	error	failed to create test namespace: failed to create a role (error: failed to create role (error: roles.rbac.authorization.k8s.io "istio-ca-role" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["update"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]}] user=&{istio-prow-test-job@istio-testing.iam.gserviceaccount.com  [system:authenticated] map[authenticator:[GKE]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]))
I0302 22:34:20.344] 2018-03-02T22:34:20.341877Z	error	test environment creation failure
I0302 22:34:20.344] FAIL	istio.io/istio/security/tests/integration/certificateRotationTest	2.535s
E0302 22:34:20.355] Build failed
I0302 22:34:20.355] process 509 exited with code 1 after 15.7m
E0302 22:34:20.355] FAIL: istio-presubmit
```

**Comment by xiaolanz** [comment]
failed on master: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3916/istio-presubmit/6066/

**Comment by myidpt** [comment]
This is RBAC permission error in the testing cluster.
@chxchx Hi Charles, has the testing cluster been modified today?

**Comment by myidpt** [comment]
The test seems to fail earlier than today. Previously it was not executed because another test TestSample2 failed before it. This is exposed after the TestSample2 test was fixed.

**Comment by chxchx** [comment]
I am not sure if this PR https://github.com/istio/test-infra/pull/722/ is relevent here but this is the most recent change we made to the test cluster today. @sebastienvas is more knowledgeable about this change. 

I also notice that we are not running security e2e test in postsubmit, which is a missing signal on master. If that is needed I am happy to do it

**Comment by myidpt** [comment]
Thanks @chxchx I think this failure *may not* start from today.
I ran the test in the Kubernetes alpha cluster, and the test passed.
Is it possible the issue is due to the cluster is not K8s alpha cluster?

**Comment by chxchx** [comment]
Yes all testing clusters are using alpha features. Quoting Seb, the admin of the clusters, from the slack oncall channel, "I can reproduce the issue (referring to https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3913/istio-presubmit/6070/) locally as well, so it is probably not a prow issue".

**Comment by sebastienvas** [comment]
@myidpt  please use gcloud config unset container/use_client_certificate and create a new 1.9 cluster from GKE and check again. We created the cluster this morning and it is using 1.9.3.

**Comment by sebastienvas** [comment]
If we need to rollback to 1.9.2 we can do that, but you need to tell me.

**Comment by myidpt** [comment]
Thanks for the info, @sebastienvas. I will test with K8s 1.9.3, and see possible solutions first. I will let you know if we need to rollback.

**Comment by myidpt** [comment]
I think we are missing the command to bind the runner (possibly istio-prow-test-job@istio-testing.iam.gserviceaccount.com) to the cluster-admin role:
kubectl create clusterrolebinding istio-testing-admin-binding --clusterrole=cluster-admin --user= istio-prow-test-job@istio-testing.iam.gserviceaccount.com
I have tested this rolebinding solves the problem on my cluster.

**Comment by myidpt** [comment]
@sebastienvas @chxchx Shall I update this file https://github.com/istio/test-infra/blob/master/scripts/update-e2e-cluster.sh to add this command?

**Comment by sebastienvas** [comment]
is this the same as https://github.com/istio/istio/blob/master/prow/cluster_lib.sh#L46 ?

**Comment by myidpt** [comment]
@sebastienvas Yes, it is.

**Comment by sebastienvas** [comment]
This is still happening.

**Comment by myidpt** [comment]
This issue is now fixed.
