### ISSUE TITLE
Status block for WASMPlugin resource

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#39193]
**Describe the feature request**
WASMPlugin resource allows injecting wasm modules using an OCI image. We have created a resource that uses `WASMPlugin` but a status of whether an image was pulled or not or any similar issue that can be bubbled up to the main resource using status block of `WasmPlugin` would be nice.

**Describe alternatives you've considered**
Not sure about the alternatives.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Would be tough since it's pulled by many unprivileged proxies vs Pod which is pulled by 1 privilege component (Kubelet).

**Comment by rahulanand16nov** [comment]
Maybe I am not following it correctly but the current use case we are targeting is:
- `WasmPlugin` targets ingress gateway pod (in gateway's namespace + labels).
- Third-party controller will fetch the status block of `WasmPlugin` to check if the gateway has the extension up and running.

Will this use case come under kubelet pulling?

**Comment by howardjohn** [comment]
A single wasmplugin will apply to >1 pods. So how do you say its been pulled? If it's been pulled once? If it has on every pod?

It's not an impossible problem but its far more. difficult than Pod status.

**Comment by ingwonsong** [comment]
What about using `istio_agent_wasm_remote_fetch_count` metric? https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/
