### ISSUE TITLE
multicluster can not loadbalance between clusters??

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39203]
### Bug Description

[root@localhost multicluster]# istioctl pc endpoint -n istio-system istio-ingressgateway-78595756f4-cx5np|grep productpage
172.20.1.18:9080                 HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local
192.168.229.101:15443            HEALTHY     OK                outbound|9080||productpage.istio.svc.cluster.local

there has two productpage endpoint,but cann't load balance between them?

### Version

```prose
[root@localhost multicluster]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (9 proxies)

[root@localhost multicluster]# kubectl version --short
Client Version: v1.23.1
Server Version: v1.23.1
```

### Additional Information

[cluster1-bug-report.tar.gz](https://github.com/istio/istio/files/8803574/cluster1-bug-report.tar.gz)
[cluster2-bug-report.tar.gz](https://github.com/istio/istio/files/8803577/cluster2-bug-report.tar.gz)

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by 13567436138** [comment]
@jamtur01

**Comment by hzxuzhonghu** [comment]
Absolutely it can balance between any endpoints.

**Comment by 13567436138** [comment]
but actually It can‘t  I use locality loadblancing，it shows outlier detection fail

**Comment by 13567436138** [comment]
if I don't config health_checks in cluster,It will always mean that endpoint is health??

**Comment by 13567436138** [comment]
@howardjohn  boss come and have a look

**Comment by jamtur01** [comment]
@13567436138 Please stop @'ing unrelated folks. It's rude and unnecessary.
