### ISSUE TITLE
Improvements to Istio Multicluster Automation and Documentation for large multi-cluster architectures

### ISSUE THREAD

**Issue by nea1** [istio/istio#39207]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The current [Multicluster tooling](https://istio.io/latest/docs/setup/install/multicluster/) works great if a handful of clusters are being meshed together; however the current model does not appear suitable for scaling when the number of workloads and/or clusters becomes large. 

For example if we have 50 clusters containing say ~200 workloads each; then in a multi-primary model each istiod will be watching and maintaining endpoints for 50 * 200 = 10,000 workloads. Most of these entries are likely _not_ required, as it is highly unlikely that every cluster's set of workloads requires to connect to every other (remote) workload.

Setting up and managing the secrets for [endpoint discovery](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/#enable-endpoint-discovery) in this model is also tedious; with 50 * 50 = 2500 remote secrets having to be installed and managed.

Feature request:
- Provide a way of setting up and managing multicluster meshes that are suitable to high cluster/high workload architectures
- For example:
  - Provide a mechanism to restrict what workloads are shared to what clusters e.g. if cluster1's "httpbin" service is only called from a handful of workloads in cluster41; then it is very expensive for all other 48 istiods to watch for and maintain endpoint information on httpbin, and for all workloads in these clusters to be aware of the remote httpbin (and other) endpoints.
  - Alternatively provide the ability to manually add endpoints for just the services required (in this case not using or restricting the automated endpoint discovery)

**Describe alternatives you've considered**

Manually setting up just the service to service connections that are required, with automated endpoint discovery switched off. We have achieved this by creating the following in the downstream cluster: 
- a Kubernetes `Service` (with the same name and namespace as the upstream service, so that the SNI value matches what is required on the upstream cluster for AUTO_PASSTHROUGH) 
- an associated Kubernetes `Endpoint` (referencing the upstream cluster's eastwest gateway NLB IPs)
- an Istio `DestinationRule` targetting the above service to upgrade the connection to use ISTIO_MUTAL. 

Is this the correct approach if not relying on automated endpoint discovery? This is currently undocumented, so for example should/could ServiceEntries be used instead of Services? If so how does DNS resolution work? How about WorkloadEntries (I see these in the logs when automated endpoint discovery is used)? Could documentation be added to describe the canonical approach to multicluster if automated service discovery is not a suitable solution?

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by litong01** [comment]
@nea1 not sure if I fully understand your scenarios but I feel if your workloads do not need to have full access to each other, these workloads seem to me should be naturally divided into different meshes, cluster secrets should only be placed in the ones need the secrets. Say if a service need to access 3 other services in 3 different clusters, then these 4 clusters make a small mesh, secrets should be only be placed in these 4 clusters (multi primary case), not other 46 clusters (to your example above). I feel that your example indicated one big mesh, vs what you like to have is multiple smaller meshes?

**Comment by nea1** [comment]
@litong01 The diagram below shows a super scaled down version of the issue I'm trying to describe (4 clusters instead of 40+)! The point is that the vast majority of service calls happen within each cluster (only the apps highlighted in green are called cross-cluster); however we still want to benefit from multicluster mesh features on those cross cluster calls i.e. MTLS & workload authorization, locality based load balancing & failover, kube dns style short hostnames etc. 

If we look at "cluster 1" it only _needs_ to know about _app-h_ in cluster 3 and _app-l_ in cluster 4. However with the current automation it knows and watches for _every_ service in cluster 3 and _every_ service in cluster 4  - i.e. it only needs to know about 2, but it is watching 7 (and telling all the local sidecar proxies about these 7). With these numbers this obviously isn't an issue, but this doesn't scale when we talk about the numbers above - 10s of clusters running 100s of apps per cluster - at some point istiod and/or the sidecars would be overwhelmed. 

So in these large scale scenarios where the cross cluster calls are known ahead of time what I'm looking for is a way of scoping down the endpoint discovery to _only the workloads that are needed to be called from other clusters._ For example perhaps a workload could be annotated with it's dependencies (i.e. upstreams) and then the local istiod just watches and adds these to it's registry?
![endpoint-discovery-scaling](https://user-images.githubusercontent.com/4982750/173113397-3649aaed-aea5-47c8-b168-1cb2f352dd56.png)

**Comment by litong01** [comment]
@nea1 Thanks for your information. sorry for the delays in response, I was on vacation. Now I understand what you really meant. You like to have the capability for an Istiod instance (DS) to watch only selected (marked with annotations maybe) services instead of all the services in a remote cluster. Is that accurate?

**Comment by litong01** [comment]
@nea1 can you take a look at this and see if that solves your issue? https://istio.io/latest/blog/2021/discovery-selectors/

**Comment by litong01** [comment]
@nea1 did you look into the article that I suggested above? it seems to me that should solve your issue.
