### ISSUE TITLE
Listeners stuck warming in Delta XDS CI

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39209]
https://storage.googleapis.com/istio-prow/logs/integ-security-multicluster_istio_postsubmit/1531624978833739776/artifacts/security-authz-f93e4215f5684783/_suite_context/echo1-3-78501-state-2018355442/primary/delta-v1-64cdc6cdd-wdx28_proxy-config.json

https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster_istio_postsubmit/1531624978833739776

Pod never becomes ready due to stuck _listeners_. Seems like https://github.com/istio/istio/issues/38709 but listeners instead of clusters.

**Comment by hzxuzhonghu** [comment]
Seems all the failures are from multicluster cases?

**Comment by howardjohn** [comment]
it's only on the new authz test which deploys more workloads than any existing suite. So I'm guessing that with multicluster just makes it larger scale and triggers it, not multicluster specific. Just a guess though

**Comment by howardjohn** [comment]
I believe its due to https://github.com/grpc/grpc-go/issues/5393 but not confirmed.

**Comment by howardjohn** [comment]
good idea let me try it tomorrow. Easy to reproduce by running the integration test setup but with 8 namespaces instead of one. Ran on my desktop in kind

**Comment by howardjohn** [comment]
One example that could trigger it (there are more):

1. xdsproxy Sends() a few messages which fill up Istiod's reqCh
2. xdsproxy upstream.Send() is slow for various reasons
3. Envoy sends 10 XDS requests. filling up the reqCh (blocked by Send())
4. xdsproxy stops calling upstream.Recv since its blocked on pushing to reqCh.
5. Because of (4), Istiod Send() blocks
6. Because of (5) and (1), Istiod no longer calls Recv()
7. Because of (6), (2) never completes

Result: complete deadlock.

This is only one possibly trigger, we can get into the state in plenty of different ways

**Comment by howardjohn** [comment]
![PXL_20220606_202534211](https://user-images.githubusercontent.com/623453/172242832-cbe8ed32-2cad-4164-bf3d-947265e951fe.jpg)

**Comment by hzxuzhonghu** [comment]
>Envoy sends 10 XDS requests. filling up the reqCh (blocked by Send())


How could this happen?  In theory, Envoy sends at most CDS/EDS?LDS/RDS/ECDS(not simultaneously), and xds_proxy can send health check, nds, pcds at beginning

**Comment by howardjohn** [comment]
> > Envoy sends 10 XDS requests. filling up the reqCh (blocked by Send())
> 
> How could this happen? In theory, Envoy sends at most CDS/EDS?LDS/RDS/ECDS(not simultaneously), and xds_proxy can send health check, nds, pcds at beginning

Just one example: https://github.com/envoyproxy/envoy/pull/21600

The other is if we send a push for 1 listener then 2 then 3 then 4 etc. We will get an rds request for each.

**Comment by hzxuzhonghu** [comment]
>The other is if we send a push for 1 listener then 2 then 3 then 4 etc. We will get an rds request for each.

Seems envoy should request with the newest listener. If the request has been sent to xds_proxy and buffered,  I think with https://github.com/istio/istio/pull/39309 it can be resolved, one point is we should better increase the recvChan size. In theory it does not need to be too much
