### ISSUE TITLE
istio authz policy using k8s labels when SPIFFE is not avalible

### ISSUE THREAD

**Issue by liyihuang** [istio/istio#39206]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

hope istio can support the k8s label/attribute based authz policy when SPIFFE is not avalible. I undestand istio is using SPIFFE as much as possible for the authz policy. However, SPIFFE might not work in some cases. For example, when we need to perform the egress authz policy and using the HTTPS from the workload. we will lose the ability to have the SPIFEE to limit the traffic from NS or workload. hope istio can have the ability to track k8s label and the IP address mapping and update the authz policy dynamically

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Why do you lose SPIFFE for egress?

**Comment by liyihuang** [comment]
please correct me if I'm wrong. I'm trying use the egress gateway and authz policy(limiting certain pod or certain NS can talk to external traffic) for HTTPS traffic(https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic). when workload pod init the TLS connection to Internet service( for example goolge.com), it's just one TLS connection from workload pods to the destination(no MTLS within the mesh, egress gateway is just doing the TLS passthrough). In this setup, I dont have the SPIFFE information for me to configure the authz policy to limit the service account/namespace.

**Comment by howardjohn** [comment]
`workload -- TLS --> sidecar -- mTLS+TLS --> egress -- TLS --> upstream`

Is what you want. This can be done by using ISTIO_MUTUAL gateway. The docs on egress are notoriously in need of some improvements

**Comment by liyihuang** [comment]
got it. I was under impression that mTLS+TLS is not supported for some reason. I think I can tweak https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/ to have the mTLS on top of the TLS.


one last question, does istio have a plan to support the k8s label-based authz policies in the future? I can see it's pretty common in most of network policy provider(like calico, cilium)

**Comment by liyihuang** [comment]
I dont see a technical reason but have seen people who don't have the proper service account setup or would like to move from network policy to istio authz. label based authz will be easier for them to migrate or start.

**Comment by nauticalmike** [comment]
@howardjohn why is it that when originating https traffic like [this](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic) authz policies don't work? 
I mean a simple DENY policy lets https traffic trough: 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: external-deny-developers-google-com
spec:
  # allow-list for the identities that can call the host
  action: DENY
  rules:
  - from:
    - source:
        namespaces: ["otherns"]
    to:
    - operation:
        hosts:
        - developers.google.com
```

When modifying the gateway from the example above to use ISTIO_MUTUAL, I get an SSL error:

```
kubectl exec $SLEEP_POD1 -it -- curl -kI https://developers.google.com
curl: (56) OpenSSL SSL_read: error:1409445C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required, errno 0
command terminated with exit code 56
```

and I don't see any activity on the egress logs but I see the listener and seems to be correct, isn't?

```
istioctl pc listener istio-egressgateway-66fdd867f4-s4xmn.istio-system
ADDRESS PORT  MATCH                      DESTINATION
0.0.0.0 8443  SNI: developers.google.com Route: https.443.https-port-for-tls-origination.istio-google-egressgateway.istio-system
0.0.0.0 15021 ALL                        Inline Route: /healthz/ready*
0.0.0.0 15090 ALL                        Inline Route: /stats/prometheus*
```

```
istioctl pc endpoint sleep-557747455f-hqmr6 --cluster "outbound|443|google|istio-egressgateway.istio-system.svc.cluster.local"
ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
192.168.84.87:8443     HEALTHY     OK                outbound|443|google|istio-egressgateway.istio-system.svc.cluster.local
```

The objective is to achieve `workload -- TLS --> sidecar -- mTLS+TLS --> egress -- TLS --> upstream` and control outbound access with authz policies, for this I have two sleep svc, one in default and another on the `otherns` ns, here the config:

```apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - developers.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: http
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-google-egressgateway
spec:
  selector:
    istio: egressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - developers.google.com
    tls:
      mode: ISTIO_MUTUAL
---
# Routes internal outbound traffic to the egress gateway using Istio's mTLS
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-google
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: google
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-google-through-egress-gateway
spec:
  hosts:
  - developers.google.com
  gateways:
  - istio-google-egressgateway
  - mesh
  # route HTTP traffic to developers.google.com through the egress gateway for the entire mesh
  tls:
  - match:
    - gateways:
      - mesh # apply to sidecars in the mesh
      port: 443
      sniHosts:
      - developers.google.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: google
        port:
          number: 443 
  # at the egress gateway, route developers.google.com to the real destination outside the mesh
  - match:
    - gateways:
      - istio-google-egressgateway
      port: 443
      sniHosts:
      - developers.google.com
    route:
    - destination:
        host: developers.google.com
        port:
          number: 443
      weight: 100
---

Any idea on what's wrong?

**Comment by vikaschoudhary16** [comment]
>When modifying the gateway from the example above to use ISTIO_MUTUAL, I get an SSL error:

you should add a destination rule as well for starting tls from the client proxy. you just changed egress gateway to expect mtls traffic but client is sending plain text
