### ISSUE TITLE
mac productivity

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3921]
- [ ] make should build everything (once, not again if nothing changed) such as it's usable:
- [ ] istioctl native
- [ ] mixer, pilot,... native
- [ ] docker images
- [ ] optionally native proxy, ...
- [ ] run tests locally / native
- [ ] run tests on minikube
- [ ] run test on a cluster

once we get some/all of this - check it doesn't regress through #576

**Comment by ldemailly** [comment]
part of it started in #3080

**Comment by hklai** [comment]
I think this has been solved by both mac compilation fix and https://github.com/istio/istio/blob/master/tests/e2e/README.md#using-a-local-vm
