### ISSUE TITLE
helm istio-official gateway Labels/Slectors. Referenced selector not found

### ISSUE THREAD

**Issue by dimitarshenkov** [istio/istio#39221]
### Bug Description

Hi I have installed helm/istio-official/gateway 1.14.0-beta.1  and 1.13.3
with additional  label in values.yaml.
labels:
  access: private

![image](https://user-images.githubusercontent.com/99493924/171411522-7518af2b-6856-4d08-a0ee-c9881d5cc796.png)
labels appear only on the svc not on the pod
![image](https://user-images.githubusercontent.com/99493924/171411981-0e66e703-36da-4286-8d57-10ff1645ab6a.png)
![image](https://user-images.githubusercontent.com/99493924/171412301-ba0cc63a-9c67-4da7-abce-e2aa3490ec3c.png)

![image](https://user-images.githubusercontent.com/99493924/171412359-a828d413-73f9-4372-a094-5a730a314e02.png)
![image](https://user-images.githubusercontent.com/99493924/171430829-2dcf3f59-3d90-40c6-960d-a6a96d5084b6.png)

Its not applied to all resources that's why  Can't expose except with default labels 

### Version

```prose
kubectl version --short
Client Version: v1.20.4
Server Version: v1.22.6-eks-14c7a48
helm version --short
v3.4.0+g7090a89
```

**Comment by howardjohn** [comment]
Looks like only the `istio` and `app` labels will be included. Not sure that is a great design but it is configurable at least..

**Comment by dimitarshenkov** [comment]
> Looks like only the `istio` and `app` labels will be included. Not sure that is a great design but it is configurable at least..

![image](https://user-images.githubusercontent.com/99493924/171442700-14ec70dc-845e-40e9-82b5-441852b8a48a.png)
Looks they are not configurable

**Comment by howardjohn** [comment]
It is configurable, its just Kubernetes does not allow mutating them once they are set. nothing we can do about that..

**Comment by dimitarshenkov** [comment]
@howardjohn Thanks a lot for the help its working !
