### ISSUE TITLE
meshConfig: need to create secrets in a different gateway namespace

### ISSUE THREAD

**Issue by shreyasrk** [istio/istio#39254]
### Bug Description

We have a setup where istio-ingress is installed in a separate namespace and `istiod` runs in another namespace. The requirement is to connect istio-gateway to a Load Balancer with TLS. 

On inspecting the spec, we observe that the DNS certificate gets installed in `istiod` namespace. We'd like this certificate to be installed in the namespace where istio-ingress is installed. 

Inference - The `certificate` parameter of `meshConfig` needs to have an additional field `secretNamespace` so that Istio can install the certificate into the namespace as per the value.

References:
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Certificate
https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/

### Version

```prose
$ istioctl version
1.13.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.8.1", GoVersion:"go1.17.5"}
```

**Comment by howardjohn** [comment]
I **_strongly_** recommend using cert-manager and not this feature. This was never intended to be used in this way. I have been meaning to try to get it deprecated for a long time which this just reminded me of.

**Comment by vikaschoudhary16** [comment]
Also this feature does not work(broken) on k8s 1.22+ `kubernetes.io/legacy-unknown` is not accepted as signer name and hence it becomes mandatory to use external CA post 1.22

**Comment by howardjohn** [comment]
This feature has been deprecated
