### ISSUE TITLE
multi-cluster: istiod repeatedly fails to patch configmap

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#39257]
```
2022-06-01T06:17:40.048065Z	error	klog	error retrieving resource lock istio-system/istio-namespace-controller-election: configmaps "istio-namespace-controller-election" is forbidden: User "system:serviceaccount:istio-system:istio-reader-service-account" cannot get resource "configmaps" in API group "" in the namespace "istio-system"
```

We enabled "external istiod" flag by default, so we'll try to win leader locks and patch webhooks/etc:

[#39189 ](https://github.com/istio/istio/pull/38283)

But the permissions are still conditional:

https://github.com/istio/istio/blob/12f5ad29c4b83898077902f3e63826d2dd8d7d6f/manifests/charts/istiod-remote/templates/reader-clusterrole.yaml#L45-L55

We should either:
* Always give permission, rely on leader elect to prevent the wrong istiod doing the patching
* Conditionally try to participate in this patching based on some metadata in the remote-secret or a label on the istio-system namespace (some per-cluster metadata that indicates primary, remote, istiodless-remote, etc.)
* Auto-detect the cluster-type somehow? 
* Fail closed on forbidden

**Comment by frankbu** [comment]
@stevenctl I was on vacation last week but had started #39151 to address this issue. PTAL.
