### ISSUE TITLE
Add `route_name` to traces

### ISSUE THREAD

**Issue by dasch** [istio/istio#39265]
**Describe the feature request**

In the access logs, I can see the `route_name` for a request, but this field is not available in traces. Since traces are the primary unit of observability for us, being able to filter and group by this field in our graphs would be _very_ helpful, especially as we start looking into taking more advantage of the route concept.

**Describe alternatives you've considered**

Just look at the logs – but we need to sample these pretty heavily, and they're less well-integrated into our workflows.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I'm using Datadog to ingest the traces.

**Comment by zirain** [comment]
istio data-plane is built on envoy, which support multi [Custom Tag](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#envoy-v3-api-field-type-tracing-v3-customtag-metadata) in tracing.

IMHO, maybe you need request this feature from the upstream community.

**Comment by zirain** [comment]
IIRC, route name not exits in metadata.
