### ISSUE TITLE
503 error when calling service by external ip from within mesh with LB proxy protocol enabled

### ISSUE THREAD

**Issue by rahimalizada** [istio/istio#39287]
### Bug Description

Enabling proxy protocol in a load balancer (Digitalocean) and adding an Envoy filter as described in https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client results in 503 error (for http traffic) when trying to access the service by it external dns address from within the cluster.

- external network -> call to http(s)://public.service.domain -> OK
- pod in mesh -> call to http://service.namespace.svc.cluster.local -> OK
- pod in mesh -> call to http(s)://public.service.domain -> ERROR

### Version

```prose
istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (12 proxies)

kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.8
```

**Comment by tabed23** [comment]
Any solution to this issue?
