### ISSUE TITLE
Test Failure (istio-postsubmit): pilot/pkg/config/kube/crd::TestControllerEvents

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#3929]
See: https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/1050

```
I0303 01:00:26.052] --- FAIL: TestControllerEvents (80.97s)
I0303 01:00:26.052] 	kubernetes.go:225: Failed to satisfy function
I0303 01:00:26.052] FAIL
I0303 01:00:26.054] FAIL	istio.io/istio/pilot/pkg/config/kube/crd	108.656s
```

**Comment by douglas-reid** [comment]
This continues to be an issue: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3950/istio-unit-tests/1447/

**Comment by douglas-reid** [comment]
@kyessenov can you take a look at this issue ?

**Comment by douglas-reid** [comment]
Assigning to @xiaolanz, as she appears to be last person to potentially have touched this code.

**Comment by xiaolanz** [comment]
Working on it. It looks like the timeout can be handled in better ways.

**Comment by xiaolanz** [comment]
still failing regularly ...

**Comment by ZackButcher** [comment]
The real problem with this test is that it talks to a real kube API server. It should not be a unit test since it has external dependencies.

**Comment by ZackButcher** [comment]
@kyessenov can you take a look at this as well please? These tests should be updated to use an in-memory fake, or similar. Right now the fact that they push config to external k8s API server to ensure that basic code invariants hold is way over the top.

**Comment by xiaolanz** [comment]
@ZackButcher most of the crd/ controller "unit" tests are against a real API server. This is partially because there is no good way to setup a testing apis.  
We have a in-memory variation under memory/

**Comment by xiaolanz** [comment]
I increase timeout to 1min in #4148 to see if it helps.

**Comment by kyessenov** [comment]
Unfortunately, k8s does not have a mock for controllers/informers. If you can find a way, please do, but we need to test against the real k8s behavior, not the mocked one as defined by our memory mock.

**Comment by kyessenov** [comment]
@ZackButcher pilot e2e is also a golang unit test right now. You can tag/labels it as depending on k8s if you wish.

**Comment by kyessenov** [comment]
By the way, why is this suddenly breaking? The code is almost a year old, yet just started causing problem?

**Comment by xiaolanz** [comment]
I made some changes to the code recently, making it available for different apigroupverisons.

**Comment by mandarjog** [comment]
@xiaolanz can you check if this test started failing after the api group version changes.
It increases the number of informers, so perhaps it is related.

Can we remove it from unit test and make it part of e2e?

**Comment by xiaolanz** [comment]
recent failures were all timeout. I will see how it goes after i increased the timeout. The build was hectic last night so my PR was reverted.  Thanks @mandarjog for taking care of it.

**Comment by ZackButcher** [comment]
It likely never flakes on a local run (I haven't seen it fail locally) because the k8s API server you're talking to has no load on it, so it responds in a timely manner. I've only seen it fail on Prow, which has a relatively high rate of churn on the k8s API server.

**Comment by xiaolanz** [comment]
maybe #4273 can help with this when it's in.
