### ISSUE TITLE
Access logging extensions are documented, but not valid.

### ISSUE THREAD

**Issue by nairb774** [istio/istio#39324]
### Bug Description

Per the 1.13 documentation, there is support for the `envoyHttpAls` extension provider, but when attempting to configure it on 1.13.4, it fails validation with the following warning:

> 2022-06-07T16:10:44.067663Z	warn	validation	found invalid extension provider (can be ignored if the given extension provider is not used): invalid extension provider access-log: unsupported provider: &{service:"access-log.local" port:9999 log_name:"access-log-grpc" additional_request_headers_to_log:"x-request-id" additional_request_headers_to_log:"accept" additional_request_headers_to_log:"content-type" additional_request_headers_to_log:"content-length" additional_response_headers_to_log:"date" additional_response_headers_to_log:"server" additional_response_headers_to_log:"content-type" additional_response_headers_to_log:"content-length" } of type *v1alpha1.MeshConfig_ExtensionProvider_EnvoyHttpAls

Looking in the 1.13.4 code, it looks like the validation logic for `envoyHttpAls`, `envoyTcpAls`, and `envoyOtelAls` is missing: https://github.com/istio/istio/blob/1.13.4/pkg/config/validation/extensionprovider.go#L196-L219

Looking in the 1.14.0 code, it looks like the validation logic for `envoyHttpAls`, and `envoyTcpAls`is missing: https://github.com/istio/istio/blob/1.14.0/pkg/config/validation/extensionprovider.go#L209-L234

Looking at more code, it looks like this might just be a bug in the validation, rather than a missing implementation, that is resulting in a misleading warning message.

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (377 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.20.15-eks-14c7a48
WARNING: version difference between client (1.24) and server (1.20) exceeds the supported minor version skew of +/-1

No Helm (Istio Operator at 1.13.4)
```

**Comment by zirain** [comment]
v1.13 validation should be fixed by https://github.com/istio/istio/pull/39054, and will landing in v1.13.5.

**Comment by zirain** [comment]
this's a missing implementation, I will send a PR to fix it ASAP.
IMHO, people should use `envoyOtelAls` in the future, anything suggestions about it, please let me know.
