### ISSUE TITLE
Misleading source IP preservation docs for Digitalocean DOKS

### ISSUE THREAD

**Issue by rahimalizada** [istio/istio#39321]
### Bug Description

The documentation at https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client lists DO DOKS load balancer as a `Network `load balancer type and suggests that setting `externalTrafficPolicy: Local` for an ingress gateway will preserve the source IP, but DO documentation for DOKS LB https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#external-traffic-policies-and-health-checks states that 

> Because DigitalOcean load balancers [terminate client connection requests with proxy](https://kubernetes.io/docs/tutorials/services/source-ip/#cross-platform-support), setting externalTrafficPolicy to Local does not preserve the client source IP address. If your service requires retaining the request’s original IP address, see [Preserving Client Source IP Address](https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#preserving-client-source-ip-address).

### Version

```prose
istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (12 proxies)

kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.8
```

**Comment by howardjohn** [comment]
DOKS is no longer listed, thanks
