### ISSUE TITLE
Configuring `:authority` header in the grpc request

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#39355]
I have a wasm module that initiates a gRPC call by specifying an upstream name which is in the format `outbound|port|subset|svc-FQDN`.

When making the connection, Envoy translates the cluster name into the `:authority` header if override is not provided. Since the cluster name format doesn't follow the authority header specification, a lot of http2 implementations are rejecting gRPC requests from `istio-proxy`. we bypass this hurdle by adding a new cluster using `EnvoyFilter` with a name that is compliant with the specification but it's just a temporary fix and feels this should be fixed upstream.

Does Istio allow this override? If not, can we make a change so that it's configurable through some resource?

Envoy allows override in the gRPC config: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice-envoygrpc

**Comment by fmcato** [comment]
Facing the same issue here, tried with 1.14.2 and 1.15.0
