### ISSUE TITLE
Evaluate tests/integration frameworks

### ISSUE THREAD

**Issue by costinm** [istio/istio#3936]
We have 3 frameworks, or 2 too many. 
The tests/integration has not been used much and doesn't appear to have many tests - if any test
is found it can be converted to e2e. 

While the framework is good and useful - we can't afford so many.

**Comment by ldemailly** [comment]
I'm have on my list to evaluate and so does Nate. Let's not delete yet

**Comment by hklai** [comment]
I assume this is part of the bigger test overhaul effort.

To be precise, I think we have two integration test frameworks (yutong's and the one in proxy) and two e2e test framework (pilot and tests/integration), no? Integration and e2e serve different purposes and we should not move integration tests to e2e blindly.

**Comment by hklai** [comment]
#4545 is the superset of this, so I am closing this.

Please add your ideas in #4545 going forward.
