### ISSUE TITLE
Extract 'install istio' from e2e test into separate util, add to istioctl

### ISSUE THREAD

**Issue by costinm** [istio/istio#3937]
The e2e framework installs istio ( using some code in framework ), and waits for it to be ready,
with ability to grab logs and debug info.

It will be useful to move this to istio/pkg/install directory, and have it called from istioctl. 
Once this is done, it can be called by the makefile as a separate step, and used in common for
setting up for pilot integration and e2e - and as a general debugging tool.

The part getting the logs and status could be called 'istioctl dumpsys' - with option to grab logs/status
from istio-system or specific namespaces.

**Comment by ldemailly** [comment]
it's really just take one of the istio*.yaml with some substitution for tags/hubs/...

but having a #358 in istioctl would be nice - not sure either of those are small enough for fixit - seems like new features to me (though new testing features are ok I think)

**Comment by costinm** [comment]
Discussed in Env WG - it appears even during normal installation the CRD creation may not be ready by the time CRs are used, and it is common to see pilot/galley failing to start few times before certs are ready.

Since we have the code already - and has been tested for a long time - it makes sense to prioritize moving the code into the istioctl, and including the steps as optional parts of the install with helm template
or trough other means. Helm install 2.10 appears to have built-in wait.
