### ISSUE TITLE
[release-1.13] TestClusterLocal failure

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#39400]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39292/integ-pilot-multicluster_istio_release-1.13/1535083150256902144

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39397/integ-pilot-multicluster_istio_release-1.13/1535080363812982784

**Comment by howardjohn** [comment]
This is fixed on master
