### ISSUE TITLE
Move pilot/proxy/envoy/v1/mock to serviceregistry/memory, add handlers

### ISSUE THREAD

**Issue by costinm** [istio/istio#3941]
The mock is used in few tests, implements model.ServiceDiscovery. 
1. Should be next to the other registries.
2. Needs a couple of /debug/registry... http handlers, to allow a test program to modify the registry
3. Should be called 'memory' (or similar) - it is not a mock. 

We also need a helper to populate the memory registry and cause 'invalidation' events, to simplify
testing the EDS/CDS updates and make them more deterministic.

**Comment by ymesika** [comment]
Updated in #6277
