### ISSUE TITLE
Istio helm chart ingress to create loadbalancer

### ISSUE THREAD

**Issue by takealookatme** [istio/istio#39426]
Currently I am using custom chart with operator approach and I in the process of using community chart a, would like to know if we have any ingress for Ingress-gaetway to create alb in AWS.

In current custom chart I have ingress in kubernetes which is creating aws alb when I create a custom resource ingress. If we already have this feature available in community chart can some one please suggest me where I can refer to.

thanks in advance ..

**Comment by howardjohn** [comment]
I don't know of any. https://cloud.google.com/architecture/exposing-service-mesh-apps-through-gke-ingress provides some thorough docs on doing it in GKE which may help though

**Comment by takealookatme** [comment]
Thanks for your comments. We are looking something similar in AWS. I can add a ingress and get the things working for now/
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/

**Comment by howardjohn** [comment]
Closing as this is answered. thanks!
