### ISSUE TITLE
Rename the user jason in Bookinfo example

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#3945]
Following https://github.com/istio/istio.github.io/pull/1035/files/ce336d1d49f9c815932736dc3069eeec47f9ad12..9fd83e411e78fd7d2da44cfa032fc622545f94a5#r172068387,
> Maybe use a name other than jason, since it gets confusing relative to json IMO.

I would consider to use `tester`, or `JohnDoe`.

**Comment by douglas-reid** [comment]
shall we replace it with "freddy" ?

**Comment by rshriram** [comment]
Its too late to change now.. its out in th web..
