### ISSUE TITLE
[Proxy] gRPC client cancellation shows up as "UNKNOWN" in istio metrics

### ISSUE THREAD

**Issue by AnnieSH** [istio/istio#39469]
### Bug Description

When a client cancellation occurs:
- Expected: `istio_requests_total` reports it as gRPC status 1 (CANCELLED)
- Actual: `istio_requests_total` reports it as gRPC status 2 (UNKNOWN)

To replicate:
- Send a gRPC request with a low timeout (eg 0.00001s) such that it always times out and cancels.

We see that 2 is the default status
https://github.com/istio/proxy/blob/d0d8b48184224d5b9eaa845d5c9b34336036c909/extensions/common/context.cc#L409 

It shows up as cancelled in our application metrics, but it could be from istio sending a cancel to the application.
Is this expected behaviour or a bug?

### Version

```prose
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.20.15-eks-a64ea69

$ istioctl version
client version: 1.14.1
control plane version: 1.8.2
data plane version: 1.8.2 (16 proxies)
```

**Comment by howardjohn** [comment]
the timeout is in your client app? I'm not sure if the client cancel would ever propogate to the server so envoy may not see it. Just a guess - would. need to verify in the spec

**Comment by AnnieSH** [comment]
To clarify, the cancelled metric shows up in our server application metrics and `istio_request_total` reports it as unknown, so the request seems to be propagating up.

Yeah the timeout is in the client, it was the simplest way to replicate a client cancellation and the issue. I sent the test request using grpcui/grpcurl.

**Comment by howardjohn** [comment]
Ah got it. Thanks.

Do you see OK on success? Or is everything unknown?

**Comment by howardjohn** [comment]
@ramaraochavali any idea?

**Comment by ramaraochavali** [comment]
No idea. @douglas-reid may have some idea?

**Comment by douglas-reid** [comment]
@kyessenov you've looked at gRPC status most recently. any thoughts on this issue?

**Comment by kyessenov** [comment]
I have no idea how gRPC client/server propagate timeout. Envoy just reports whatever is in the HTTP trailer I think. Since it's the client timeout, I think Envoy just never sees it.
