### ISSUE TITLE
Pull WASM plugins from Google Container Registry using Workload Identity?

### ISSUE THREAD

**Issue by stellirin** [istio/istio#39462]
Can Istio take advantage of Workload Identity to pull WASM plugins as OCI images from Google Container Registry?

When running inside GCP it's typically enough to grant the Service Account `roles/storage.objectViewer` on the underlying Storage Bucket that backs the registry.

GCR is [explicitly mentioned](https://istio.io/latest/blog/2021/wasm-api-alpha/#image-fetcher-in-istio-agent) in the blog announcement, but so far I was not able to make this work for Istio. Any links to examples for such a configuration would be appreciated.

**Comment by howardjohn** [comment]
cc @igsong

**Comment by ingwonsong** [comment]
@stellirin As mentioned in [the announcement](https://istio.io/latest/blog/2021/wasm-api-alpha/#future-work-and-looking-for-feedback), Istio 1.12 does not support the private repository. 
From Istio 1.14, it is supported via `ImagePullSecret` field of `WasmPlugin`. 

After getting a [json key file](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key) from GCP, you can create a secret using this command.
```
kubectl create secret docker-registry <secret-name> -n <namespace>\
  --docker-server=gcr.io \
  --docker-username=_json_key \
  --docker-password="$(cat <key-file-path>)" \
  --docker-email=<some-email>
```
Then, fill `imagePullSecret` with `secret-name`.

**Comment by stellirin** [comment]
Thank you for the detailed responses. I upgraded our clusters this week to 1.14 and wanted to investigate this new functionality. For now we'll probably stay with our existing solution (internal http server) as it's generally our policy to avoid SA keys for use within GCP.

**Comment by howardjohn** [comment]
Does
https://github.com/google/go-containerregistry/blob/623023e6c2442f4f29dfaee5334fa5e0c125cc3b/cmd/krane/main.go#L52
do what we want?

BTW, in the meantime you could always run some OCI proxy doing the auth, or
a local caching registry, etc. Not trivial but would work around the
limitations

**Comment by ingwonsong** [comment]
@howardjohn Yes. That would be the native support for GCR. (as well as ECR & ACR).
Do you think it worth to support them?

**Comment by ingwonsong** [comment]
Hmm.. my misread again. it should work. I will try to test it. Thanks @howardjohn
