### ISSUE TITLE
wasm: pre-check a Wasm module before distributing it

### ISSUE THREAD

**Issue by ingwonsong** [istio/istio#39471]
In current implementation, all the checks regarding Wasm module happen on each `istio-agent` side. 
If we conduct such checks before distributing it, it helps to reduce the effect of wrong configuration.

In details, following checks may be possible in advance, but not limited.

* Validity of the given URL
* Checksum
* ImagePullSecret

Validation hook seems to be the right place to implement this.

This idea came from https://github.com/istio/istio/issues/38989 and https://github.com/istio/istio/issues/39193.

[X] Extensions and Telemetry
[X] User Experience

**Comment by zirain** [comment]
so you want to validate those on istiod(wehhook etc.)?

**Comment by howardjohn** [comment]
I don't think we should do anything involving pulling the binary. We can validate the schema (eg the URL is the shape of a URL), but not much else. This is the same as Kubernetes does with images?

**Comment by ingwonsong** [comment]
That's true. 
BTW, my point is that users seems to be hard to recognize their mistake.
Will think about the way to utilize metrics or istioctl as well.
