### ISSUE TITLE
Telemetry access logging: add cache

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39472]
In the old style access logs, we had caching of the generated config. In Telemetry, we lost this.

In real prod clusters, we saw 50% of Istiod CPU spent just on this part. It would be good to add a cache here.

I did some initial work here but got distracted. I might be able to complete but if anyone else wants to pick it up, even better.

**Comment by zirain** [comment]
I will take a look this.

**Comment by zirain** [comment]
> In real prod clusters, we saw 50% of Istiod CPU spent just on this part. It would be good to add a cache here.

can you share more details about this? what the cluster's size? how many workloads? how many telemetry resources in the clusters?

`buildAccessLogFromTelemetry` take 50% if istio beyond my unstanding.

**Comment by zirain** [comment]
if you change provider from `envoy-json` to `envoy`, still have the same cpu cost?

**Comment by zirain** [comment]
A long-term goal is [ecds: add support for access log extensions](https://github.com/envoyproxy/envoy/issues/12893)

**Comment by howardjohn** [comment]
Cache done in https://github.com/istio/istio/pull/39751, followup in https://github.com/envoyproxy/envoy/issues/12893 for long term
