### ISSUE TITLE
some requests go PassthroughCluster although others go through the mesh

### ISSUE THREAD

**Issue by turbotankist** [istio/istio#39480]
### Bug Description

We have two services. One sends requests to another.
Most of requests work right and go trough the Mesh. but some of them don't.
there are two exactly the same requests but with different result
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/9462236/174089150-80d4681c-b776-4478-9a58-c78f65c9c014.png">
The services use sidecars  configuration but I checked it 100 time - there is no conflicts.
 I did a tcpdump for one of services and I had seen that requests have the same http headers and body. Just one packet was transmitted to the istio-proxy over loopback and second packet was transmitted directly to the receiving service IP.

The http-client is python/httpx/asyncio and it get an exception with "httpx.RemoteProtocolError: Server disconnected without sending a response." when the issue trigger. I tried to set mtl_mode to PERMISSIVE and the exception went away but requests still go trough the Mesh and PassthroughCluster at the same time.

### Version

```prose
istioctl version
client version: 1.10.4
control plane version: 1.12.8
data plane version: 1.12.8 (179 proxies)

kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.12-eks-a64ea69
```

**Comment by howardjohn** [comment]
can you clarify what you mean by "Just one packet was transmitted to the istio-proxy over loopback"? Preferably in the form of two `curl ...` requests showing the working vs not working

**Comment by howardjohn** [comment]
Why do you have it set at all? On all recent versions there is no timeout which is the only safe option.

The reason is that any slow connection may hit the timeout and then we cannot identify traffic

**Comment by turbotankist** [comment]
Thank you, I will switch off it
