### ISSUE TITLE
helm.go:84: [debug] admission webhook "validation.istio.io" denied the request: error decoding configuration: invalid character 's' looking for beginning of value

### ISSUE THREAD

**Issue by rameshar16** [istio/istio#39496]
Hi All, I am seeing the below issue while installing/upgrading the helm chart. Please help me on fixing the issue.

Error: INSTALL FAILED: failed to create resource: admission webhook "validation.istio.io" denied the request: error decoding configuration: invalid character 's' looking for beginning of value helm.go:84: [debug] admission webhook "validation.istio.io" denied the request: error decoding configuration: invalid character 's' looking for beginning of value

Thanks and Regards,
Ramesh

**Comment by howardjohn** [comment]
can you show the output of `helm template` or add `--debug` so it shows the yaml?

**Comment by rameshar16** [comment]
Hi @howardjohn,
The issue has been fixed. The issue was with the incorrect data type.
Thanks and Regards.
Ramesh

**Comment by howardjohn** [comment]
It would be useful to give more details so others can fix this on their own, or we can improve our code.
