### ISSUE TITLE
Circuit breaker per user

### ISSUE THREAD

**Issue by jyotipatel** [istio/istio#39504]
Granular circuit breaker based on URL parameter or header. Similar to rate limit using envoy sidecar.

**Affected product area (please put an X in all that apply)**

[ X] Networking
[ X] Performance and Scalability

**Additional context**
It would be amazing to break the circuit for just one user if the downstream returns 5xx for that particular user instead of the full service. If there is any alternative with istio please guide me.

**Comment by jyotipatel** [comment]
Thanks for the response @howardjohn . But this option is not feasible for us as we have a large number of users.

**Comment by ramaraochavali** [comment]
> It would be amazing to break the circuit for just one user if the downstream returns 5xx for that particular user instead of the full service. If there is any alternative with istio please guide me.

Circuit breakers are not meant to restrict calls from single user in general. They are generally a way to protect the service from all clients. If you want user specific, I think rate limiting is the option. Is there a problem in using rate limiting option?

Can you explain more about your use case on why you want to break circuit per user and which circuit you want to break?

**Comment by jyotipatel** [comment]
Use case: Assume multiple users sharing an environment. If any issue comes up on a particular user side due to a faulty configuration, this might bring down the whole backend. Thus, instead of breaking the circuit for all the users we want to block this user's requests only after a number of failures. Because other users can be served easily if this user's requests are not reaching the backend anymore.

**Comment by ramaraochavali** [comment]
> Ratelimter doesn't take into account the failure counts. We want to break the circuit for this user after a failure threshold.

Circuit breaker does not take failure threshold. It breaks based on max requests/connections/pending requests.

**Comment by jyotipatel** [comment]
@ramaraochavali thanks. I think the use case I am talking about can not be supported by istio at this point of time. 
Is there a way to return 5xx instead of ejecting the host when the consecutive5xxErrors are breached?

**Comment by ramaraochavali** [comment]
> I think the use case I am talking about can not be supported by istio at this point of time.
Is there a way to return 5xx instead of ejecting the host when the consecutive5xxErrors are breached?

yes. That is what local origin errors do that I linked above. It only ejects host if there is a connection issue to the host rather than on return code

> One more question regarding the same, can I use outlier detection for a service entry? what happens in that case? Any requests going to this service entry will fail?

Any request going that service entry wont fail - if the service backed by service entry has 4 nodes, one of them would be ejected based on consecutive 5xx

**Comment by jyotipatel** [comment]
> 
> yes. That is what local origin errors do that I linked above. It only ejects host if there is a connection issue to the host rather than on return code
Got it, thanks. I will explore this one.

> Any request going that service entry wont fail - if the service backed by service entry has 4 nodes, one of them would be ejected based on consecutive 5xx
What if the service entry is just an external dns address which is pointing to an outside load balancer?

**Comment by ramaraochavali** [comment]
> What if the service entry is just an external dns address which is pointing to an outside load balancer?

If the DNS resolves to a single IP - yes. all requests will fail.

**Comment by jyotipatel** [comment]
yes, thanks for the responses.
