### ISSUE TITLE
Upgrade to apiextensions v1

### ISSUE THREAD

**Issue by videlanicolas** [istio/istio#39509]
### Bug Description

The beta CustomResourceDefinition API (`apiextensions.k8s.io/v1beta1`) has been [deprecated](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#:~:text=The%20beta%20CustomResourceDefinition%20API%20(apiextensions.k8s.io/v1beta1)) in Kubernetes 1.22 in favour of `apiextensions.k8s.io/v1`.

This makes istio fail when deployed: https://github.com/selkies-project/selkies/issues/53

We should update https://github.com/istio/operator/blob/master/deploy/crds/istio_v1alpha1_istiooperator_crd.yaml to use the v1 API.

### Version

```prose
$ istioctl version
no running Istio pods in "istio-system"
1.13.3
$ istioctl version --short
no running Istio pods in "istio-system"
1.13.3
```

**Comment by litong01** [comment]
@videlanicolas I've been using k8s v1.23.x for awhile, I am not seeing the errors that you are seeing. I looked at the link you have above, but could not figure out what steps that you were taking to install istio. Please detail the steps here so that I can try to reproduce the error.

**Comment by videlanicolas** [comment]
Disregard this issue, I realized that Istio operator has archived that repo and has now moved on to this repo. Selkies is using the old archived repo, which means they are getting the v1beta1 API instead of the V1 app.

Thanks for the reply!
