### ISSUE TITLE
Auto-registered workloadentry is using the private IP address of the VM in the cloud

### ISSUE THREAD

**Issue by dingjianrui** [istio/istio#39519]
### Bug Description

I follow the guide here: [https://istio.io/v1.13/docs/setup/install/virtual-machine/](url) join the VM to the Istio mesh (both Kubernetes and VM are deployed in Azure cloud), once I start the Istio agent in the VM, one WorkloadEntry is created automatically, but unfortunately the address of the WorkloadEntry is the private IP address of the VM, since the VM and the Kubernetes cluster are not in the same private network, services on the VM cannot be accessed by the application in the Kubernetes cluster.
Question:
Is there a way to specify the public IP address of the VM while I starting the Istio agent (sidecar) in the VM?

### Version

```prose
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.0 (1 proxies), 1.13.4 (3 proxies)

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.6
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [X] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
I think there is a flag on the `istioctl` command to register a workload. On my phone currently but I can look it up later.

**Comment by hzxuzhonghu** [comment]
You can also setup the env `INSTANCE_IP` with the IP you want, this will take preference

**Comment by dingjianrui** [comment]
> I think there is a flag on the `istioctl` command to register a workload. On my phone currently but I can look it up later.

@howardjohn  thanks for your feedback, use the flag "externalIP" in the command "istioctl x workload entry configure" fixed this issue.

@hzxuzhonghu , the environment settings is mapped to "ISTIO_SVC_IP", I'm not sure where to configure the "INSTANCE_IP", but thank you all the same.

Right now the Workload Entry is up and running with the external IP, I also exposed the workload entry with a Kubernetes service. Apps from the VM can access the services in the Kubernetes without any issue through the eastwest gateway, but Apps from Kubernetes cannot access to the Apps in the VM. besides exposing the workload entry by kubernetes service, is there any additional steps I missed here ?

thanks.

**Comment by hzxuzhonghu** [comment]
INSTANCE_IP can be set in vm, so it is the first IP in proxy.IPAddressed, which will be used to autoregister

>but Apps from Kubernetes cannot access to the Apps in the VM.

First, you need to make sure VM app is reachable without istio.

**Comment by dingjianrui** [comment]
> INSTANCE_IP can be set in vm, so it is the first IP in proxy.IPAddressed, which will be used to autoregister
> 
> > but Apps from Kubernetes cannot access to the Apps in the VM.
> 
> First, you need to make sure VM app is reachable without istio.

Hi @hzxuzhonghu , I can access the app in the VM via public network with/without the Istio proxy running inside, but I cannot access the apps in the VM from any pod, and the return code is 503, error message is "upstream connect error or disconnect/reset before headers. reset reason: connection failure".

thanks.

**Comment by dingjianrui** [comment]
Hi @hzxuzhonghu , If I use the traffic policy of "DestinationRule" to disable the mTLS for the service provided by the VM, then I can access the VM services from a pod without any issue, but the envoy proxy deployed in the VM suppose to support both mTLS and non-mTLS by default, and I cannot found any flag can be used to control the mTLS behaviors of the VM envoy proxy while i using the command "istioctl x workload entry configure" to generate the config for the VM envoy proxy. @howardjohn can you please share some insights here ? many thanks.

**Comment by hzxuzhonghu** [comment]
From your desc, i doubt there is something missing to configure. Maybe you need to verify if the VM application secret is loaded well

**Comment by dingjianrui** [comment]
> From your desc, i doubt there is something missing to configure. Maybe you need to verify if the VM application secret is loaded well

Hi @hzxuzhonghu , thanks for you feedback, I think the mTLS is managed by the envoy proxy deployed in the VM, from app point of view the mTLS session between the sidecar is transparent, I think I need to check the mTLS settings of the proxy in the VM, but no idea how to verify this, it will be great if you can share some insights, thanks.

**Comment by hzxuzhonghu** [comment]
envoy configdump can show the certs pushed to vm, analysis can be tricky because you have to look into both client and server side tls setting

**Comment by dingjianrui** [comment]
I'd like to close this issue since the Workload Entry IP address can be configured.
