### ISSUE TITLE
Egress rate limit: e2e test

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3952]
Egress rate limit is missing e2e tests.

1. Add an egress service for e2e tests  (like egress routing test)
2. Add rate limit and ensure it is adhered to.

**Comment by cmluciano** [comment]
Confirming should this be in `test/e2e/tests/mixer/mixer_test.go` or `mixer/test/e2e` ?

**Comment by ozevren** [comment]
This sounds like it should be test/e2e/...

**Comment by cmluciano** [comment]
Reassigning to Piotr based on feedback on the WG call today
