### ISSUE TITLE
can istio support only one direction traffic hijack?

### ISSUE THREAD

**Issue by beck917** [istio/istio#39530]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Can istio support one direction traffic hijack?
During we inject istio on gray stage, We need only hijack inbound traffic.

I konw the iptables shell can do this, but the inject webhook has some parameters to support this feature?

**Describe alternatives you've considered**
1. add some parameters on the global.yaml like includeIPRanges or some else
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by fatedier** [comment]
https://istio.io/latest/docs/reference/config/annotations/#:~:text=traffic.sidecar.istio.io/includeOutboundIPRanges

**Comment by beck917** [comment]
> https://istio.io/latest/docs/reference/config/annotations/#:~:text=traffic.sidecar.istio.io/includeOutboundIPRanges

thx, this is what i wanted
