### ISSUE TITLE
Does serviceEntry have the mechanism to find the liveness of external service ?

### ISSUE THREAD

**Issue by luowendi** [istio/istio#39531]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

The situation is like this：
        we want to use some external services to provide some functions to the Istio cluster, but we don't know whether Istio supports some detection mechanisms for external services or not? If some external services are down, can Istio remove these services  or find them in time? Similar to heartbeat detection, can some fusing parameters be set?

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by luowendi** [comment]
> This is supported, Istio use passive healthcheck. if one server instance failed, it will retry another one.
Thanks for your kindest reply. Can you provide me with some references or links about the passive healthcheck? I really want to know the details about this part.

**Comment by hzxuzhonghu** [comment]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#outlier-detection  

and https://istio.io/latest/docs/concepts/traffic-management/#retries
