### ISSUE TITLE
CNI chart GKE check using deprecated Helm .Capabilities.KubeVersion.GitVersion object

### ISSUE THREAD

**Issue by michaelvl** [istio/istio#39534]
### Bug Description

In this PR https://github.com/istio/istio/pull/37872 the check for using HPA v2 was updated to:

```
{{- if (semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion)}}
```

The `GitVersion` parameter is part of Helm2 built-in objects (https://v2.helm.sh/docs/chart_template_guide/#built-in-objects) and no longer supported in Helm3 (https://helm.sh/docs/chart_template_guide/builtin_objects/). The check should be rewritten to use `KubeVersion.Minor` instead.

### Version

```prose
Chart versions 1.14.1

helm version --short                                                                   │
v3.8.2+g6e3701e
```

### Additional Information

See also https://pkg.go.dev/helm.sh/helm/v3/pkg/chartutil#KubeVersion.GitVersion

Workflows using helm template or kustomize with helmChartInflationGenerator will be hit by this since only KubeVersion can be specified to the template operation.

**Comment by MichaelVL** [comment]
As a side-note. Workflows using helm template or kustomize with helmChartInflationGenerator will be hit by this since only KubeVersion can be specified to the template operation.

**Comment by howardjohn** [comment]
.Capabilities.KubeVersion.GitVersion seems to work for me on v3.8.2. It is just deprecated, not removed. Is there anything actually broken by this?

**Comment by howardjohn** [comment]
I am fine with changing it though, just trying to understand.

**Comment by MichaelVL** [comment]
True, if you deploy directly from Helm to a Kubernetes cluster, then `GitVersion` may be set even in never Helm. However, there are workflows that apply post processing to the Kubernetes YAML before deploying to a cluster - also know as the 'Helm chart last mile modifications'. Such modifications could be to validate the YAML against policies using OpenPolicyAgent, sealing secrets etc. A little more information can be found here: https://github.com/MichaelVL/helm2yaml

Such workflows may start from a Helm chart and render the chart using variations of `helm template`. A typical workflow may use `kustomize` for this and the `helmChartInflationGenerator`: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#field-name-helmchartinflationgenerator

An example could be to add custom labels to the Istio gateway PODs, which can be referenced from Istio Gateway resources. The gateways chart supports custom labels on the gateway Deployment resource, but not the gateway PODs, hence one will have to resort to post processing to add such labels. A way to do this would be with `kustomize`, e.g. the following `kustomization.yaml` file that specifies that the gateway chart should be rendered for Kubernetes 1.22 and have additional labels added:

```
helmChartInflationGenerator:
- chartName: gateway
  chartRepoUrl: https://istio-release.storage.googleapis.com/charts
  chartVersion: 1.14.1
  releaseName: public-gateway
  extraArgs:
   - --kube-version
   - "1.22"
commonLabels:
  scope: public
```

Running `kustomize` with:

```
kustomize build --enable-helm .
```

Produces a HPA of `v2` even if a version `v2beta2` was expected as that would be compatible with Kubernetes 1.22:

```
...
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
...
```

This was with Helm 3.8.2 and kustomize 4.5.2.

Interestingly I also tried the following two commands:

```
helm template gateway istio/gateway --version 1.14.1 --kube-version 1.22
helm template gateway istio/gateway --version 1.14.1 --kube-version 1.24
```

And they do produce the expected HPA versions - `v2beta2` and `v2` respectively! This is somewhat strange and may be a result of this 'grey area' of deprecated capability fields.

I will investigate kustomize further as it seems to handle Helm differently than the 'vanilla' commands shown above.

Still it may be a good idea to implement the chart conditionals based on non-deprecated capability fields.

**Comment by MichaelVL** [comment]
I found this - the `extraArgs` field in the kustomize `HelmChartInflationGenerator` are now ignored due to security: https://github.com/kubernetes-sigs/kustomize/pull/3784

This explains the discrepancy between templating the chart with kustomize and helm.

It also changes this issue from a bug into a minor recommendation for using `KubeVersion.Minor` instead of `GitVersion` however, since Helm seem to map `--kube-version` arguments into internal `GitVersion` parameters (probably for backward compatibility) I think this is a minor issue.

**Comment by matb4r** [comment]
I think it should be reopened. And also it is a good first issue

**Comment by sergiomcalzada** [comment]
same here, facing same issue after upgrading Kubernetes can't make any change to istio due to this values

**Comment by howardjohn** [comment]
FWIW we only use Capabilities.KubeVersion.GitVersion now, on master to:
* Detect GKE
* Detect 1.22+ - this can be removed, we only support 1.22+ now

Unfortunately if the recommendation is to go from GitVersion to `MinorVersion`, the 'detect GKE' will not work. A GKE cluster looks like:
```
  "serverVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.1-gke.1016000",
    "gitCommit": "c3b21d0babc669ed89916a4920873bc3d5e7e1d3",
    "gitTreeState": "clean",
    "buildDate": "2024-01-19T09:31:23Z",
    "goVersion": "go1.21.6 X:boringcrypto",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
```

**Comment by michaelvl** [comment]
An option could be to keep the auto-detect based on `.Capabilities.KubeVersion.GitVersion`, but use the existing `cniBinDir` value in the auto-detect:

```
# existing values.yaml
defaults:
  cni:
    cniBinDir: "" # Auto-detected based on version; defaults to /opt/cni/bin.
```

change it to:

```
# new values.yaml
defaults:
  cni:
    cniBinDir: /opt/cni/bin
```

and change the auto-detect in the cni chart to something like:

```
# manifests/charts/istio-cni/templates/daemonset.yaml
{{- $defaultBinDir :=
    (.Capabilities.KubeVersion.GitVersion | contains "-gke") | ternary
      "/home/kubernetes/bin"
      .Values.defaults.cni.cniBinDir    # Use default from values.yaml
}}
```

and then document, that if one is using a render approach, then for GKE `cniBinDir` must be set to `/home/kubernetes/bin`. Since such rendering for GKE is already broken AFAICT this is not worse than before but will make rendering possible.

**Comment by michaelvl** [comment]
After looking at it a little more, a solution might also be to:

1. Change the cni chart to always simply use `cniBinDir` without any logic
2. Remove the GKE auto-detect
3. Add a GKE profile - similar to `manifests/charts/istio-cni/files/profile-openshift.yaml`

This would make GKE support less magic, but also less automatic.

**Comment by howardjohn** [comment]
> An option could be to keep the auto-detect based on

I think this is functionally equivalent to what we have now, albiet a bit simpler. Later we have `{{ .Values.cni.cniBinDir | default $defaultBinDir | quote }}` which I think makes it equivalent to your changed `$defaultBinDir := ...`?

> After looking at it a little more, a solution might also be to:

What problem does this solve exactly? For environments where GitVersion cannot be used, won't it just always not contain '-gke' and they will need to manually set it? If we do this, it would just break users where it does work?

Is that accurate, or does using GitVersion fail hard in these cases?

Or is this an attempt to "always succeed or always fail" vs "sometimes it works..."?

**Comment by michaelvl** [comment]
The former solution would mean that with tooling where one cannot control `GitVersion` and only `KubeVersion` can be used (and thus the GKE magic does not work), one can still configure the CNI bin dir through explicit configuration.

The latter solution removes the unique GKE solution and brings all 'environment types' on the same level. Its true that this will require current users of the GKE magic to choose a dedicated GKE profile instead and this could be seen as a regression.

> Is that accurate, or does using GitVersion fail hard in these cases?

Instead of guessing what we are trying to solve - maybe @sergiomcalzada or @matb4r could clarify.

**Comment by howardjohn** [comment]
> The former solution would mean that with tooling where one cannot control `GitVersion` and only `KubeVersion` can be used (and thus the GKE magic does not work), one can still configure the CNI bin dir through explicit configuration.

`{{ .Values.cni.cniBinDir | default $defaultBinDir | quote }}` which we have currently should allow that already, no?

**Comment by michaelvl** [comment]
@howardjohn yes, you are right. Lets hear if @sergiomcalzada or @matb4r can elaborate on how it broke for them

**Comment by sergiomcalzada** [comment]
Hi,
the problem here is supporting old kubernetes versions. After upgrading to kubernetes +1.23 we weren't able to change anything at istio level

This PR [#49332](https://github.com/istio/istio/pull/49332/files) seems to remove compatibility and fix the issue

```
{{- if (semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion)}}
```

**Comment by howardjohn** [comment]
Removed one of them, but the CNI one is still there.

fyi @bleggett since you were looking at auto-detect

**Comment by bleggett** [comment]
Yeah that's for https://github.com/istio/istio/issues/51121

A better CNI check would likely live outside of the Helm `GitVersion` detection anyway - as explained here it's not ideal.

**Comment by bleggett** [comment]
FWIW https://github.com/istio/istio/pull/54141 introduces a new mechanism for this that deprecates the use of the `GitVersion` field, but leaves the `GitVersion` based mode in place as a fallback.

So when/if `GitVersion` is actually removed, we can remove it from our chart, since we have another pathway for this.
