### ISSUE TITLE
slow start not take effect when container restart or inPlaceUpdate

### ISSUE THREAD

**Issue by bboshiZ** [istio/istio#39532]
### Bug Description

When the pod restarts, its meta information remains unchanged (ip etc.),  changes in eds data send by istio to envoy is the "healthStatus",  HealthStatus_UNHEALTHY send to envoy
```
// core.HealthStatus_HEALTHY --> core.HealthStatus_UNHEALTHY
HealthStatus_HEALTHY HealthStatus = 1
HealthStatus_UNHEALTHY HealthStatus = 2
```

when pod become ready， pod HealthStatus_HEALTHY send to envoy
envoy will not set the pod into slowstart mode

### Version

```prose
$istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (3 proxies)
```

**Comment by ramaraochavali** [comment]
Sorry the description is not clear.

Are you saying Istio sends endpoint health status correctly to Envoy when container restarts but Envoy does not put it in slow start mode?

**Comment by bboshiZ** [comment]
when I change the pilot code, config the UnHealthy pod not send to envoy. 
https://github.com/istio/istio/blob/release-1.14/pilot/pkg/xds/endpoint_builder.go#L304

```
			if ep.EnvoyEndpoint == nil {
				ep.EnvoyEndpoint = buildEnvoyLbEndpoint(ep)
			}
```
to

```
			if ep.EnvoyEndpoint == nil && ep.HealthStatus == model.Healthy {
				// if ep.EnvoyEndpoint == nil {
				ep.EnvoyEndpoint = buildEnvoyLbEndpoint(ep)
			}

```

build pilot-discovery and update istiod-1-14-0 deploy.
then  kill the istio-proxy contaier in one service pod, when pod get ready, it will in slow start mode


But this  modification is inappropriate

**Comment by ramaraochavali** [comment]
Ok. I will take a look.

**Comment by bboshiZ** [comment]
perhaps，related to this. when add the debug code
https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/eds.cc#L129
```
void EdsClusterImpl::BatchUpdateHelper::updateLocalityEndpoints(
    const envoy::config::endpoint::v3::LbEndpoint& lb_endpoint,
    const envoy::config::endpoint::v3::LocalityLbEndpoints& locality_lb_endpoint,
    PriorityStateManager& priority_state_manager, absl::flat_hash_set<std::string>& all_new_hosts) {
  const auto address = parent_.resolveProtoAddress(lb_endpoint.endpoint().address());
  // When the configuration contains duplicate hosts, only the first one will be retained.
  const auto address_as_string = address->asString();
  if (all_new_hosts.count(address_as_string) > 0) {
    return;
  }


  // debug
  const auto tmpSourceTime =  parent_.time_source_.systemTime();
  const auto ts = std::abs(static_cast<int>(
      std::chrono::duration_cast<std::chrono::seconds>(tmpSourceTime.time_since_epoch()).count()));


  ENVOY_LOG(error, "slow-strt-test updateLocalityEndpoints: ip:{},status:{},ts:{}",
    address_as_string,lb_endpoint.health_status(),ts);

 // debug

  priority_state_manager.registerHostForPriority(lb_endpoint.endpoint().hostname(), address,
                                                 locality_lb_endpoint, lb_endpoint,
                                                 parent_.time_source_);
  all_new_hosts.emplace(address_as_string);
}
```

get  logs
```
slow-strt-test updateLocalityEndpoints: ip:10.22.1.163:8080,status:1,ts:1655808065
slow-strt-test updateLocalityEndpoints: ip:10.22.5.243:8080,status:1,ts:1655808065
slow-strt-test updateLocalityEndpoints: ip:10.22.6.32:8080,status:2,ts:1655808065
```
the parent_.time_source_ is the same for all endpoint,  status:2  represent unhealth

when pod become ready, get logs
```
slow-strt-test updateLocalityEndpoints: ip:10.22.1.163:8080,status:1,ts:1655811740
slow-strt-test updateLocalityEndpoints: ip:10.22.5.243:8080,status:1,ts:1655811740
slow-strt-test updateLocalityEndpoints: ip:10.22.6.32:8080,status:1,ts:1655811740
```

host.creationTime() may be same, not sure

**Comment by howardjohn** [comment]
isn't this intended? if a pod has a small blip in readiness we don't want it to warm up again?

**Comment by bboshiZ** [comment]
> isn't this intended? if a pod has a small blip in readiness we don't want it to warm up again?

readiness blip lead to not warm up ,this is ok. 
Another scenario is, we use cloneset manage pod in k8s.  when update image, pod inPlaceUpdate. not  warm up too

**Comment by howardjohn** [comment]
How can you in place update an image in kubernetes? Pod.spec.container.image is immutable

**Comment by bboshiZ** [comment]
> How can you in place update an image in kubernetes? Pod.spec.container.image is immutable

warme up is needed by the program,  like jvm.  warme up would be better as long as it start up, no matter from crash or image update

**Comment by howardjohn** [comment]
if you want graceful up+down of a service then you shouldn't hot-swap out the image. Aside from that being a bad practice (IMO), it kills the graceful readiness probing and termination that Kubernetes and Istio provide.

IMO this is a Kruise issue, not an Istio one.

**Comment by bboshiZ** [comment]
> Ah my bad, I forgot image _is_ mutable.
> 
> If you want a new pod make a new pod IMO. Otherwise, its the same workload and shouldn't be re-warmed.

we will think about that.  Anyway, thank you
