### ISSUE TITLE
Add tests for GenCertFromCSR

### ISSUE THREAD

**Issue by myidpt** [istio/istio#3954]
https://github.com/istio/istio/blob/672018b1ce8c7299940f3197ca85f4e9936a3e1e/security/pkg/pki/util/generate_cert_test.go#L191

**Comment by myidpt** [comment]
@incfly Assign this to you. Please let me know if you need any help.

**Comment by incfly** [comment]
After briefly scanning, I think we can call GenCertFromCSR() with specific parameter (request/signKey/ttl/isCA), and check whether returned cert respects those parameter. One or more test cases w/ different parameter should be good enough. Is there any other particular logic we want to cover?

wdyt? @myidpt
