### ISSUE TITLE
Use the underlying Kubernetes system to handle oci images for WASM OCI Plugins

### ISSUE THREAD

**Issue by jonathanvila** [istio/istio#39552]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In order to pull and use the wasm oci images, use the kubernetes underlying system that will check first in the local cluster image registry and depending on the imagepull policy will go to the remote registry to pull it if it doesn't exist locally

**Describe alternatives you've considered**
* current approach with remote repositories, but it doesn't cover the internet disconnected clusters 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
WASM plugins

**Comment by howardjohn** [comment]
This is one of those things that would be amazing if we could do it, but.. I don't know any way to do it without mounting the node docker/containerd/etc socket which is incredibly insecure
