### ISSUE TITLE
Fix Istio/proxy circleci build failure

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#3956]
Istio/proxy circleci build fails, and below is the error message. 

ERROR: error loading package '': Encountered error while reading extension file 'bazel/go_proto_library.bzl': no such package '@com_lyft_protoc_gen_validate//bazel': Error cloning repository: ssh://git@github.com/lyft/protoc-gen-validate.git: Algorithm negotiation fail caused by ssh://git@github.com/lyft/protoc-gen-validate.git: Algorithm negotiation fail caused by Algorithm negotiation fail

ERROR: error loading package '': Encountered error while reading extension file 'bazel/go_proto_library.bzl': no such package '@com_lyft_protoc_gen_validate//bazel': Error cloning repository: ssh://git@github.com/lyft/protoc-gen-validate.git: Algorithm negotiation fail caused by ssh://git@github.com/lyft/protoc-gen-validate.git: Algorithm negotiation fail caused by Algorithm negotiation fail

INFO: Elapsed time: 3.544s

FAILED: Build did NOT complete successfully (0 packages loaded)

Makefile:53: recipe for target 'deb' failed
make: *** [deb] Error 1

**Comment by lizan** [comment]
fixed
