### ISSUE TITLE
 Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) 

### ISSUE THREAD

**Issue by thennetirajesh** [istio/istio#39573]
Hi Colleagues,

While upgrading Istio from 1.11.8 to 1.12.8 we are seeing the below error message, 

**15:26:20 WARNING: Istio control planes installed: 1.11.8, 1.11.8.
15:26:20 WARNING: A newer installed version of Istio has been detected. Running this command will overwrite it.
15:26:21 Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
15:26:21 Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
15:26:21 Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/sidecar-injector.istio.io]. This may cause injection to occur twice.
15:26:21 Build step 'Execute shell' marked build as failure**

Kubernet version : 1.21.10
Istio Version : 1.11.8 

Kindly suggest to us how to proceed further.

**Comment by anders-swanson** [comment]
Also observed when upgrading from Istio 1.10.4 to 1.13.2. Workaround was to delete the mutating webhook configuration and retry the upgrade.
