### ISSUE TITLE
Improve security test coverage

### ISSUE THREAD

**Issue by wattli** [istio/istio#3957]
Currently it's below 70%, need improvement.

**Comment by wattli** [comment]
https://codecov.io/gh/istio/istio

**Comment by incfly** [comment]
@wattli, the codecov link seems to show the overall code coverage, not specific for security.

Also, how can we find the code path not test-covered, any links/tools? Also, wondering how to choose what test cases, based on the importance?

**Comment by wattli** [comment]
It used to have detailed coverage, let me check with relevant person.

**Comment by wattli** [comment]
https://codecov.io/gh/istio/istio @incfly , it's back to normal now.

**Comment by wattli** [comment]
it's 76% now
