### ISSUE TITLE
Failed to mount NFS volume with Istio mTLS enabled

### ISSUE THREAD

**Issue by Yiadh** [istio/istio#39578]
### Bug Description

I have 2 VMs (nfs client and nfs server) that has been integrated into the Istio service mesh (Control Plane running in kubernetes). Unfortunately the nfs mount does not work when the istio-proxy is running either at the client side or the server side. The mount command hangs for few minutes then it returns only the error `Connection reset by peer`

### Version

```prose
$ istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (3 proxies)
$ kubectl version --short
Client Version: v1.21.5
Server Version: v1.22.4
```

**Comment by howardjohn** [comment]
Can you give more info? Logs? config you have? https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols may be applicable - I am not sure if NFS is or not
