### ISSUE TITLE
Separate tests into different suites based on WG-owned tests

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#3958]
Based on ideas from https://docs.google.com/document/d/1wpSUSuTjNP95jL2WuQ4sMO4v7tt1U0Gabw4xlAqHCH0/ this issue would cover 

- Splitting out e2es to better determine what failed and allow the ability to run only certain suites locally
- Provide WG owned dashboards to track flakiness/general test health 
  -[ k8s SIG-Network e2e example](https://k8s-testgrid.appspot.com/sig-network-gce#Summary)

Steps:
- [ ] Review k8s framework setup to see how we can re-use the same istio setup for multiple runs
- [ ] Split auth tests & other special environments into separate setup suites 
- [ ] Create spreadsheet with WG owned tests
- [ ] Decorate tests and separate into separate suites with relevant framework setup
- [ ] Update testgrid to organize WG tests into different dashboards

**Comment by xiaolanz** [comment]
Need a bit of context on the work. Is there a existing model we want to follow (references)? What's coming out this? Does it help with better triaging? or solving some specific problems today?

**Comment by cmluciano** [comment]
@xiaolanz Added more context in description

**Comment by cmluciano** [comment]
Tests should be [populated](https://k8s-testgrid.appspot.com/istio) now by related PRs, closing this issue for now
