### ISSUE TITLE
Cant Upload files larger than 2Gi Via Istio Gateway.  

### ISSUE THREAD

**Issue by mitunmbj** [istio/istio#39580]
We have deployed a file upload API in a Kubernetes cluster, and we are able to upload files larger than 2GB using the regular Kubernetes service via port-forwarding. But when we tried to upload through the Istio gateway in place, we are unable to do so. We can only upload files up to 2GB through the Istio gateway. Any suggestions?

Istio version: 1.13.2

**Comment by howardjohn** [comment]
Lets track as part of https://github.com/istio/istio/issues/24370, general big file handling. thanks

**Comment by jadhavnitind** [comment]
@mitunmbj Could you please elaborate more on this. I am also trying to upload larger file through Istio gateway but by default that is not allowing more than 20 MB. When I try to upload 30MB+ file it gives  413 Request Entity Too Large / 413 payload too large. I have tried istio envoyfilter `maxRequestBytes: 54000000 #204800000` with larger size but that is not working. Could you please let me know what you have done to upload 2GB file?
Istio version: 1.13.1
