### ISSUE TITLE
DNSProxying support parallel queries to all upstream nameservers

### ISSUE THREAD

**Issue by fatedier** [istio/istio#39598]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I enabled DNSProxying in istio and it will forward external domain queries to upstream nameservers in sequence and fall to the next after one times out.

Can we support parallel queries optional? It will improve performance and reliability of DNS lookups for us.

I see these is already a TODO [comment](https://github.com/istio/istio/blob/master/pkg/dns/client/dns.go#L388). I can contribute to this feature if you think it's no problem.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
Sure
