### ISSUE TITLE
Istio Custom resources with status gives `observedGeneration` values in `string` and not in `int64`

### ISSUE THREAD

**Issue by sylvainOL** [istio/istio#39605]
### Bug Description

Istio Custom resources with a status (at least `EnvoyFilter` and `Gateway`) can set an `observedGeneration` value. in kstatus spec (used by Istio as far as I understand), it's supposed to be `int64`.

But istio gives it as string and other tools (like flux)à are messing with it :

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  creationTimestamp: "2022-05-11T07:49:54Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: homer-user
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: homer
  namespace: homer-user
  resourceVersion: "40444600"
  uid: 29816ee8-2cb0-4e55-b651-e577708972ce
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 8080
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
                request_handle:headers():remove("X-Auth-Request-Access-Token")
            end
  workloadSelector:
    labels:
      app.kubernetes.io/name: homer
status:
  observedGeneration: "1"
```

result with flux:

```
Health check failed after 10m0.011944018s, timeout waiting for: [EnvoyFilter/homer-user/homer status: 'Unknown': looking up status.observedGeneration from resource: .status.observedGenera
tion accessor error: 1 is of the type string, expected int64]
```

### Version

```prose
$ istioctl version
client version: 1.12.7
control plane version: 1.14.1
data plane version: 1.12.2 (25 proxies), 1.14.1 (33 proxies)

$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.9+rke2r1
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/8975041/bug-report.tar.gz)

**Comment by howardjohn** [comment]
@therealmitchconnors

**Comment by howardjohn** [comment]
type is defined as:

```
 108   │           status:
 109   │             type: object
 110   │             x-kubernetes-preserve-unknown-fields: true
```

But I don't see where _we_ would set that as a string. Is it possible something else is?

**Comment by sylvainOL** [comment]
I'm not sure from where it comes but I do see that here : 
https://github.com/istio/api/blob/master/meta/v1alpha1/status.gen.json#L97-L100

**Comment by sylvainOL** [comment]
and according to https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/gateway/conditions.go#L165, it's an `metav1.condition` struct and according to its type, it' an int64 (https://github.com/kubernetes/apimachinery/blob/v0.24.2/pkg/apis/meta/v1/types.go#L1488)

**Comment by dar-plus** [comment]
Hi. Faced this problem too. As I see in the field writes "plot-discovery"

**Comment by hrvatskibogmars** [comment]
Anyone managed to get some workaround around this when using flux & Istio? I am getting the same errors but for VirtualService.

**Comment by sylvainOL** [comment]
Hello, I think the issue is on Istio and not elsewhere @howardjohn and I still have the issue :(

**Comment by solidDoWant** [comment]
@howardjohn can this issue be reopened? Here is the specific code path that is causing the problem in the latest release[^1]:

- **`(*IstioCondition).MarshalJSON`** — [`istio/api` @ `a0e4e1c` · `meta/v1alpha1/status_json.gen.go:21-24`](https://github.com/istio/api/blob/a0e4e1cbfcc5e8cd8fc141108d16173aa07db04e/meta/v1alpha1/status_json.gen.go#L21-L24)
  - delegates to `StatusMarshaler.MarshalToString(this)`, where [`StatusMarshaler = &jsonpb.Marshaler{}`](https://github.com/istio/api/blob/a0e4e1cbfcc5e8cd8fc141108d16173aa07db04e/meta/v1alpha1/status_json.gen.go#L32)
  - ↳ **`(*jsonpb.Marshaler).MarshalToString`** — [`golang/protobuf` @ `v1.5.4` · `jsonpb/encode.go:78`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L78)
    - ↳ **`(*jsonpb.Marshaler).marshal`** — [`jsonpb/encode.go:86`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L86)
      - ↳ **`(*jsonWriter).marshalMessage`** — [`jsonpb/encode.go:131`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L131)
        - ↳ **`(*jsonWriter).marshalField`** — [`jsonpb/encode.go:390`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L390)
          - ↳ **`(*jsonWriter).marshalValue`** — [`jsonpb/encode.go:421`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L421)
            - ↳ **`(*jsonWriter).marshalSingularValue`** — [`jsonpb/encode.go:514`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L514)
              - type-switches on `v.Interface().(type)` at [`jsonpb/encode.go:535`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L535)
              - ↳ **`case int64, uint64:`** — [`jsonpb/encode.go:548-550`](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/jsonpb/encode.go#L548-L550) — **offending statement:**
                ```go
                case int64, uint64:
                    w.write(fmt.Sprintf(`"%d"`, v.Interface()))
                    return nil
                ```

The `fmt.Sprintf("%d", …)` wraps the integer in JSON quotes, producing the literal token `"4"` instead of `4`. This is causing kstatus-based tools that check `status.observedGeneration` (such as Flux CD) to be unable to determine what version has been reconciled.

[^1]: Full disclosure: this is LLM generated/formatted, but I manually checked the full call chain and it looks accurate to me.
