### ISSUE TITLE
VM workload in multi-network environment cannot handle mTLS request from pods in the same mesh

### ISSUE THREAD

**Issue by dingjianrui** [istio/istio#39603]
### Bug Description

Current Status:

1. VM installed in the Multi-network environment.
2. VM workload entry was automatically registered in the cluster, and the probe status of the workload entry is Heathy.
3. Certificates in the VM(/etc/certs) are all verified without any issue. (otherwise I think the mTLS cannot work from VM to pod)
4. From the VM, I can access the service in the Kubernetes cluster via mTLS without any issue. (X-Forwarded-Client-Cert header attached)
5. From Pod, I can access the workload in the VM through http.

Issue:
I cannot access the workload in the VM If I don't use the DestinationRule to disable the mTLS for the workload in the VM.
tried to use the openssl connect from pod to the workload in VM, i got the error information below:

`openssl s_client -showcerts -connect forum.forum-services:80

139632157787456:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
139632157787456:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111`

### Version

```prose
istioctl version:
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (4 proxies), 1.13.0 (1 proxies)

kubectl version short:
Client Version: v1.24.0
Server Version: v1.22.6
```

**Comment by aryan16** [comment]
can you check whether the sidecar is there on the vm workloads or not ?

**Comment by howardjohn** [comment]
Closing as there is no response
