### ISSUE TITLE
Specify sidecar resource percentage parameters  like "sidecar.istio.io/resourcePercentage"

### ISSUE THREAD

**Issue by beck917** [istio/istio#39601]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In istio, we only can specify the absolute value such as "sidecar.istio.io/proxyCPU" or others like cpulimit or memory parameters.

it's good, but sometime we want set the sidecar container request and limit according to the main container resource.

for example, the knative app had this feature, they use "queue.sidecar.serving.knative.dev/resourcePercentage" to specify the sidecar container resourse.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
IMO this is not something that is generally safe/a good idea, and adds a lot of complexity were we aleady have complex logic. I would recommend customizing on a per-pod basis like https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection or annotation. This could be done automagically in your own CI/CD pipeline if needed
