### ISSUE TITLE
Unable to use workloadSelector for e.g. DestinationRule

### ISSUE THREAD

**Issue by MaciekLeks** [istio/istio#39609]
### Bug Description

I follow every thread of the point embedding of DestinationRules, so how happy I was when finally I found:
- abbility to use SDS (`credentialName`) in TLS section
and
- `workloadSelector` section 

First I've tried workloadSelector with istio 1.13.3, then with 1.14.1 but all the time I get:
`error validating data: ValidationError(DestinationRule.spec): unknown field "workloadSelector" in io.istio.networking.v1beta1.DestinationRule.spec; if you choose to ignore these errors, turn validation off with --validate=false`

After digging into the CRDs that's true. There is no workloadSelector in my CRDs defs inside my cluster. Then I built own release of istio based on the istio master. Yep, in the istio 1.15.x there is `workloadSelector` and it works.

So, the question is:
- According to the [doc](https://istio.io/latest/docs/reference/config/networking/destination-rule/) does istio support workloadSelector for DestinationRule in v1.14.1? If yes, that means we have a bug, if not, shouldn't the doc be aligned with the real state of the release?

 

### Version

```prose
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (NNN proxies)
```

### Additional Information

Before I got to the documentation, I found [this issue](https://github.com/istio/istio/issues/36240)

**Comment by 0ff** [comment]
We've updated from istio 1.13.1 to 1.14.3 and the issue went away. It seems the CRD was included in the 1.14.x release, but only if you install the CRDs manually (as is described in the Upgrade Guide for helm).
