### ISSUE TITLE
kubernetesenv adapter no longer running for context.protocol == tcp

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#3962]
Verified in manual testing that TCP calls are no longer resulting in the APA for kubernetes.

We need to add new rules to config to enable that behavior (and verify in tests).

**Comment by cmluciano** [comment]
@douglas-reid Does https://github.com/istio/istio/pull/3994 close this?

**Comment by douglas-reid** [comment]
@cmluciano yes. This should be resolved now.
