### ISSUE TITLE
reorg Telemetry e2e tests

### ISSUE THREAD

**Issue by zirain** [istio/istio#39623]
logging e2e mixed with other tests in `stats/prometheus`, it's odd, let's do something to improve it.

**Comment by howardjohn** [comment]
One thing to note is that each new test suite adds 2-3minutes. So it's recommended to only split them if they have different install values. 

We can rename it of course

**Comment by zirain** [comment]
there's not existing suite for logging and WasmPlugin, those tests are put in `stats/prometheus/nullvm/accesslogs_test.go` and `stats/prometheus/wasm/imagepullpolicy_test.go`

we may need two suites for those, but that will cost more time for e2e tests.

**Comment by howardjohn** [comment]
The only reason to make more suites is if they need different Istio
installations. Unlikely normal packages it's not just organization - there
is a huge cost. If there are distinct features they can be split into
files, functions, etc.

Ideally there would be one suite

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/39687#issuecomment-1197526728

reorg telemetry e2e tests:
```
telemetry/
|-- v2/
|-- api/
|-- policy/
```
