### ISSUE TITLE
Enable Outlier Detection Log Through Helm Charts

### ISSUE THREAD

**Issue by dallasanta** [istio/istio#39635]
**Describe the feature request**

Outlier Detection log was once part of the Helm charts (https://github.com/istio/istio/issues/18555) but this change ended up not making to the istiod charts (https://github.com/istio/installer/pull/606). In that implementation the property was called "outlierLogPath".

The feature requested would be a new property to be added to the IstioOperator model, so that the outlier detection log can be set up.

It could be applied to the following components:
* Proxy Injection Template
* Ingress Gateway Deployment

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
I take a review at the codes, it's lost from the beginning.
there's two options:
1. add `outlierLogPath` like https://github.com/istio/istio/pull/19117
2. fix this [TODO](https://github.com/istio/istio/blob/176d90c4e14c1628c12a2b0b925ceefdf82136a3/pkg/envoy/proxy.go#L44), move `outlierLogPath` to `MeshConfig` and we can config it via `ProxyConfig`, 

cc @howardjohn , WDYT?

**Comment by chinaran** [comment]
+1
