### ISSUE TITLE
Legacy usage of "label: istio-protocol: TCP" from Mixer configs

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#3963]
Lots of mixer config relies on YAML stanzas that include:

```
labels:
  istio-protocol: TCP
```

This should be removed in favor of:

```
match: context.protocol == "tcp"
```

in rules.

**Comment by kyessenov** [comment]
To clarify, the issue is that there is always some default label (HTTP in this case), and that cannot be overridden by a match clause. The work around is to explicitly add a label for TCP. Either allowing match to override the label, or getting rid of labels is fine with me.

**Comment by ozevren** [comment]
Adding some context:
https://github.com/istio/istio/issues/2139
https://github.com/istio/istio/blob/b6fa713dc8356cb49bbc1bda37f2fd9b5bce1e31/mixer/pkg/runtime/routing/table.go#L98
https://github.com/istio/istio/blob/b6fa713dc8356cb49bbc1bda37f2fd9b5bce1e31/mixer/pkg/runtime/dispatcher/dispatcher.go#L239

**Comment by kyessenov** [comment]
`istio-protocol` label no more.
