### ISSUE TITLE
IST0109 incorrectly firing

### ISSUE THREAD

**Issue by Stono** [istio/istio#39634]
### Bug Description

Given a VirtualService in several namespaces:

- platform-dashboard-mk2
- skippr
- shippr-cli-api

All of which have:

```
exportTo:
- their-namespace (eg skippr)
```

Then the following rule fires:

```
Error [IST0109] (VirtualService platform-dashboard-mk2/github) The VirtualServices platform-dashboard-mk2/github,skippr/github,shippr-cli-api/github associated with mesh gateway define the same host */github.atcloud.io which can lead to undefined behavior. This can be fixed by merging the conflicting VirtualServices into a single resource.
```

However changing the `exportTo` to `.`, "fixes" it.

I don't really see the difference between using `.` and explicitly defining the namespace.

### Version

```prose
1.14.1
```

**Comment by howardjohn** [comment]
Likely the issue is exportTo a specific namespace was added later and the check wasn't updated

**Comment by Stono** [comment]
@howardjohn https://github.com/istio/istio/issues/39629 is probably similar 👍
