### ISSUE TITLE
Pilot allocates large amounts of memory due to JSON parsing

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio#3965]
During performance testing we learned that Pilot performs a large amount of allocations to parse JSON k8s API objects into protobuf structs at runtime. Under some conditions we saw Pilot allocate as much as 52GB over 20 seconds, with JSON parsing unmarshalling contributing the lion's share.

**Comment by costinm** [comment]
We have better solution for alpha3 and ADS - no longer critical, the number of calls has already reduced.
