### ISSUE TITLE
Build issue in proxy

### ISSUE THREAD

**Issue by VivekSubr** [istio/istio#39686]
### Bug Description

There's a build failure in istio proxy with -Wall and -Werror

./extensions/common/istio_dimensions.h:60:39: error: unnecessary parentheses in declaration of 'connection_security_policy' [-Werror=parentheses]
   60 | #define DEFINE_FIELD(name) std::string(name);

Changing this to #define DEFINE_FIELD(name) std::string name;

should fix this.

### Version

```prose
not required
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
Feel free to fix the warning at istio/proxy!
