### ISSUE TITLE
0.6.0 broken on minikube and docker on Mac OS X

### ISSUE THREAD

**Issue by theganyo** [istio/istio#3968]
(The following works on 0.5.1)
Starting from a clean Kubernetes env (on either Minikube or Docker), running: 
```
kubectl apply -f istio/install/kubernetes/istio.yaml
kubectl apply < (istioctl kube-inject -f istio/samples/helloworld/helloworld.yaml) 
```
Will not create a running example. A curl command to the app will yields:
```
➜  helloworld curl localhost/hello -v
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /hello HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Mon, 05 Mar 2018 19:18:59 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers
```
Pilot / discover logs contain:
```
2018-03-05T19:24:22.706913Z	warn	unable to retrieve region label for pod: helloworld-v1-6bb5f94f57-n5597
2018-03-05T19:24:22.789701Z	warn	unable to retrieve region label for pod: helloworld-v2-6d4b75d655-jbrvw
```
The helloworld / istio-proxy logs repeatedly have:
```
[2018-03-05 21:04:43.970][14][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
```
The ingress has:
```
[2018-03-05T20:35:09.394Z] "GET /hello HTTP/1.1" 503 UF 0 57 2 - "192.168.65.3" "curl/7.54.0" "bb76d67a-43d8-9661-bf82-bc215d4a3677" "localhost" "10.1.0.100:5000"
```

**Comment by secat** [comment]
I am encountering exactly the same problem starting with istio version 0.6.0. 

It was working fine with istio version 0.5.1 on minikube 0.25.0.

**Comment by secat** [comment]
@theganyo as a suggestion, I propose to change the issue title to `0.6.0 broken on minikube/docker for mac` in order to be more explicit.

**Comment by theganyo** [comment]
Sure. AFAIK, there's no current way to run on Mac... but better to be narrowly scoped.

**Comment by theganyo** [comment]
Another note: On minikube, I used the start command `minikube start --vm-driver=hyperkit --extra-config=apiserver.Admission.PluginNames="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"`.

**Comment by ldemailly** [comment]
```
[2018-03-05 21:04:43.970][14][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
```

is/was 2 issues:

a) CA and Pilot taking a while to propagate and pick up certs (delay to come up issue)

b) port issues (permanent failure/never works)

my understanding is b) is not an issue in 0.6.0

can you confirm the issue persists for you ?

**Comment by secat** [comment]
@ldemailly I confirm that on my side the issue persists and that the ingress pod outputs indefinitely:
```
[2018-03-13 19:22:45.278][15][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
```

**Comment by ldemailly** [comment]
@secat how did you install 0.6.0 exactly ?

**Comment by secat** [comment]
@ldemailly finally I was able to make it work. I am using the helm chart located in `github.com/istio/istio/install/kubernetes/helm`. I deleted my minikube machine and started a fresh one.

It is now working on my side.

**Comment by ldemailly** [comment]
good to know but just so you know,
up until 0.6 and tbd in 0.7 only istio*yaml from the release tar are the tested/working istio install.

**Comment by theganyo** [comment]
Wait. Just so I understand: The solution is to use the helm chart that isn't supported?

**Comment by ldemailly** [comment]
until we declare that it does work, which we have not as far as I know, the solution is to not use helm

**Comment by theganyo** [comment]
But this issue wasn't opened for helm. This was the command:
`kubectl apply -f istio/install/kubernetes/istio.yaml`

**Comment by ldemailly** [comment]
that's why I asked "how did you install 0.6.0 exactly ?" 

I guess your issue and @secat got mixed, my bad.

so, can you repro failing to install 0.6.0 / lds not coming up ?

**Comment by theganyo** [comment]
I've reinstalled and restarted completely from scratch and now it doesn't reappear. Frustrating. The only thing I hadn't done was reinstall before... so now I can't say what might have changed to cause the issue. Ok, I'm closing.
