### ISSUE TITLE
Istiod cannot respond to the update of sidecar CRD

### ISSUE THREAD

**Issue by lxv458** [istio/istio#39681]
### Bug Description

I create several sidecar CRDs for corresponding services to control the services they could access directly.

At the beginning, everything goes well.

However, after a series of operations, maybe including add/delete services, updating service protocol, add/remove clusters, create serviceEntry, create sidecar for serviceEntry, etc, I found that the sidecar CRD cannot work, which means that I insert/delete a host of spec.ingress.hosts of service productpage, but the envoy of productpage has not adapt to this change (I have checked by `istioctl pc ep` cmd and `kubectl logs productpage -c istio-proxy`).

I have no idea if it's caused by istiod which didn't receive the update event or caused by envoy which didn't load config correctly.

Here is the sidecar CRD of productpage.
```shell
spec:
  egress:
    - hosts:
        - default/kubernetes.default.svc.cluster.local
        - default/reviews.default.svc.cluster.local
        - default/details.default.svc.cluster.local
        - default/nginx.default.svc.cluster.local
        - istio-system/*
        - kube-system/coredns.kube-system.svc.cluster.local
        - kube-system/kube-dns.kube-system.svc.cluster.local
  workloadSelector:
    labels:
      app: productpage
```
Here is the sidecar CRD of serviceEntry.
```shell
spec:
  egress:
    - hosts:
        - default/abcd.default.svc.cluster.local
        - default/kubernetes.default.svc.cluster.local
        - istio-system/*
        - kube-system/coredns.kube-system.svc.cluster.local
        - test/tomcat-test.test.svc.cluster.local
  workloadSelector: {}
```

### Version

```prose
# istioctl version
client version: 1.8.4
control plane version: 1.8-dev-398fa9e29dd8f6a14a4c43e5665374cb3952dda5
data plane version: none
# kubectl version --short
Client Version: v1.19.10
Server Version: v1.19.10-r0-22.3.0.B003
```

**Comment by zirain** [comment]
`workloadSelector: {}` this will fall back to namespace level selector

**Comment by howardjohn** [comment]
Istio 1.8 is very very EOL https://istio.io/latest/news/support/announcing-1.8-eol/. Please reopen if you can reproduce on newer versions
