### ISSUE TITLE
When using EnvoyFilter INSERT_BEFORE to add an http subfilter,  expect provide the de-duplication capability of the filters

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#39685]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

If two different users define two envoyfilter, adding the same http subfilter.

I hope Istio can provide the filter de-duplication capability to ensure that only one of them takes effect after all EnvoyFilter is added. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
IMO, this is not the right behavior. Imagine a user wants to insert two lua filters but they do different tasks.

**Comment by zengyuxing007** [comment]
> 

@hzxuzhonghu Thanks for your reply,the  scenario you mentioned may indeed also have

so,  maybe we can provide a new configuration parameter under envoyfilter and decide whether to de-duplicate based on this parameter

**Comment by hzxuzhonghu** [comment]
Looks not grace, the graceful way maybe comparing two patches, and ignore one if they are equal. Didn't think much, not sure how much the cost and whether it is worth it. All in all this is a user's fault.

**Comment by zengyuxing007** [comment]
Maybe add a global feature switch like PILOT_ENABLED_ENVOYFILITER_DE_DUPLICATION  and then just exclude the lua filter.

Because the other envoy native  filters logic is fixed, there should not be a need to apply multiple duplicate filters in one request

**Comment by howardjohn** [comment]
Envoyfilter is break glass configuration. Its users responsibility to use it correctly. IMO this is not desired.
