### ISSUE TITLE
Istio ProxyConfig CR still effective after being deleted

### ISSUE THREAD

**Issue by yokoyang** [istio/istio#39684]
### Bug Description

Create the ProxyConfig CR as follows, then restart the pod under the demo namespace, and see from the istio-proxy log that the concurrency is set to 5. Then delete the demo-namespace-proxyconfig or set the spec field to empty. After the demo namespace has no ProxyConfig CR, the expected behavior is that concurrency should revert to the default value of 2. But still 5.

```
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: demo-namespace-proxyconfig
  namespace: demo
spec:
  concurrency: 5
```

Troubleshooting found that the following code of EffectiveProxyConfig will overwrite mc.DefaultConfig after execution, because mergeWithPrecedence uses pointer copying when merging. After the merge ends, it will affect the incoming mc.DefaultConfig. After deleting the ProxyConfig CR or setting the field to empty, the value in mc.DefaultConfig is set to the last value, which is 5 in the example. 

```
// Merge the proxy config from default config.
effectiveProxyConfig = mergeWithPrecedence(mc.GetDefaultConfig(), effectiveProxyConfig)
```
pilot/pkg/model/proxy_config.go

```
		if pcs[i].GetConcurrency() != nil {
			merged.Concurrency = pcs[i].GetConcurrency()
		}
		if pcs[i].GetImage() != nil {
			merged.Image = pcs[i].GetImage()
		}
```

I make a PR here: https://github.com/istio/istio/pull/39683

### Version

```prose
both in istio 1.13 and 1.14

kubernetes version 1.22
```

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/40494
