### ISSUE TITLE
some tests involving mixer hit the 8k go routines limit

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3969]
#3948 and #3789

a 8192 limit should not trigger and removing the test or the limit isn't how that should be addressed

ie: how did it happen/why / fix the leak without removing the test or the limit

**Comment by ozevren** [comment]
As stated previously, the issue is with the test. The test should be fixed so as not to leak things. I believe the previous bug already covers this? https://github.com/istio/istio/issues/3789?
