### ISSUE TITLE
TCP Traffic not always routed to correct namespace/subdomain

### ISSUE THREAD

**Issue by boocup** [istio/istio#39701]
### Bug Description

i am not 100% sure this is a bug as i may just be missing something on the implementation. when using multiple namespaces, all of which use the same port. incoming traffic will stick with the first one connected even when trying to disable the connection and connect to a different namespace/subdomain.

subdomain1.domain.com:5591  ----> TCP connection internet endpoint 
subdomain2.domain.com:5591  

attempt to switch to subdomain2 fails. 

subdomain1.domain.com:5591  
subdomain2.domain.com:5591  ----> TCP connection internet endpoint attempted, but doesn't work

Traffic is not routed unless I manually change to unique ports via kubectl edit....

subdomain1.domain.com:5592
subdomain2.domain.com:5591  ----> TCP connection internet endpoint works now.

So, it is almost as if istio ignores the subdomain for TCP and just relies on unique ports. 

Gateway and VirtualService info in 'Additional Info' section.

### Version

```prose
[opc@tf4-operator ~]$ kubectl version --short
Client Version: v1.21.6+2.el8
Server Version: v1.22.5
[opc@tf4-operator ~]$ 
[opc@tf4-operator ~]$ helm version --short
v3.6.3+g809dabc
```

### Additional Information

not using istioctl

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: infra
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-06-22T12:19:56Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingressgateway
  namespace: istio-system
  resourceVersion: "7317"
  uid: 
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: ingress-cert
      mode: SIMPLE
  - hosts:
    - '*'
    port:
      name: tcp
      number: 5591
      protocol: TCP

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: examplename
    meta.helm.sh/release-namespace: examplens
  creationTimestamp: "2022-06-29T14:28:06Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingress
  namespace: examplenamespace
  resourceVersion: "3178035"
  uid: 
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - subdomain1.domain.com
  http:
  - match:
    - uri:
        exact: /connect-server
    name: cs
    route:
    - destination:
        host: primary
        port:
          number: 4444
  - match:
    - uri:
        prefix: /
    name: secondary
    route:
    - destination:
        host: secondary
        port:
          number: 8080
  tcp:
  - match:
    - port: 5591
    route:
    - destination:
        host: primary
        port:
          number: 5591

**Comment by howardjohn** [comment]
For TCP there is no "host" to match on so we only have port which leads to conflicts here
