### ISSUE TITLE
Unable to use boolean JWT claims

### ISSUE THREAD

**Issue by Stono** [istio/istio#39703]
### Bug Description

I have a jwt from keycloak, where the claim is a boolean type:

<img width="539" alt="Screenshot 2022-06-29 at 20 31 37" src="https://user-images.githubusercontent.com/1486729/176520571-74b081e5-ca0f-49be-bf94-8434e4e4eace.png">

And I'm trying to check that:
```
    - key: request.auth.claims[email_verified]
      values:
      - true
```

But I get: 

```
Error: UPGRADE FAILED: cannot patch "oauth" with kind AuthorizationPolicy: AuthorizationPolicy.security.istio.io "oauth" is invalid: spec.rules.when.values: Invalid value: "boolean": spec.rules.when.values in body must be of type string: "boolean"
```

Doing as a string, doesn't work.

### Version

```prose
1.14.1
```

**Comment by Waddah-Ahmad** [comment]
I have the same issue too

**Comment by thadamski** [comment]
I have this issue as well, is there any workaround at the moment?

**Comment by c-fteixeira** [comment]
> Note only support claim of type string or list of string

[ref](https://istio.io/latest/docs/reference/config/security/conditions/) > `request.auth.claims`

**Comment by keithmattix** [comment]
Actually, just noticed the ref; that's the correct conclusion for this
