### ISSUE TITLE
flake 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#39727]
TestGatewayConformance/HTTPRouteSimpleSameNamespace/Simple_HTTP_request_should_reach_infra-backend 

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39688/integ-pilot_istio/1542679350015430656 

TestNormalization/Base/a 
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39688/integ-security-istiodremote_istio/1542679358819274752

**Comment by howardjohn** [comment]
First one: https://github.com/kubernetes-sigs/gateway-api/issues/1242

secnond one https://github.com/istio/istio/issues/39747. 

Lets track in those. Thanks!!
