### ISSUE TITLE
Ability to forward specific JWT claims as HTTP Headers

### ISSUE THREAD

**Issue by Stono** [istio/istio#39724]
**Describe the feature request**

I would really like to be able to map specific JWT claims to specific HTTP headers, for example; `email` to `x-auth-email`.

I know that you can currently forward the JWT to the client, but that's suboptimal because:

- They still need to parse a JWT, and understand the structure of the JWT
- The JWT contains loads of stuff they don't care about, this bloats HTTP headers

**Describe alternatives you've considered**

I've achieved this with an EnvoyFilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-jwt-headers
  namespace: istio-system
  annotations:
    name: Add JWT Headers
    description: If the istio JWT filter was used, as there are email and name claims - then add them as auth headers.
spec:
  priority: -1
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: 'envoy.filters.network.http_connection_manager'
              subFilter:
                name: 'envoy.filters.http.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            '@type': 'type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua'
            inlineCode: |
              function envoy_on_request(request_handle)
                local function isempty(s)
                  return s == nil or s == ''
                end

                local meta = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.jwt_authn")
                if not isempty(meta) then
                  local claims = meta["https://my-oidc"]
                  if not isempty(claims) then
                    local email = claims["email"]
                    local user = claims["name"]
                    if not (isempty(email) and isempty(user)) then
                      request_handle:headers():add("x-auth-email", email)
                      request_handle:headers():add("x-auth-user", user)
                    end
                  end
                end
              end
```

But I worry about anything I build with an EnvoyFilter will one day just break.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by aryan16** [comment]
Currently we don't support adding jwt-filter to header via our reqAuth API. It's still in plan and our team is working on this. As an alternative for now there are several ways to fulfill this requirement - 

1) Envoy Lua Filter- I think you have already used it
2) You can add header via virtual service as well - 
The following is an example virtual service for copying the "group" claim to the "x-istio-jwt-group" header:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - headers:
      request:
        set:
          # Copy the group claim to the x-istio-jwt-group header
          x-istio-jwt-group:
            '%DYNAMIC_METADATA(["istio_authn", "request.auth.claims", "group"])%' ```

3) WASM Filter - https://github.com/mandarjog/proxy/tree/jwt_header_19/extensions/jwt_header

But there are few limitations in these solution, based on my understanding the approach with Lua filter one is most used solution as of now.  We will be adding a permanent fix for this request in our `ReqAuth` api to support this feature soon.

**Comment by Stono** [comment]
@aryan16 thanks for the response!  I wasn't aware that I could use a VirtualService; that actually fits our deployment pattern better than using EnvoyFilters!  Thanks a lot for the heads up on that one.  Looking forward to it being a first class citizen too.

**Comment by Stono** [comment]
@aryan16 i can't get the VirtualService option to work at all!  Are you sure that syntax is correct?  Please can you check my EnvoyFilter and show a comparable example for `email`?

**Comment by aryan16** [comment]
I am testing the virtual service solution, will give you an update on this soon. Meanwhile you can refer this for envoy filter - https://gist.github.com/inaiat/63a7525dbcf7c8824e7dc1a58927c0ef which uses `email` in the claims
one more reference link - https://github.com/istio/istio/issues/35108#issuecomment-916547087

**Comment by Stono** [comment]
Yip the EnvoyFilter approach works for sure, i'd just rather use the VirtualService if possible!  Thanks

**Comment by aryan16** [comment]
One clarification - the example I attached in the above comment is specifically for “group” claim, if the name is different you should add that. The limitations of virtual service is that it can only handle string values in claim, can’t support nested claims.

**Comment by Stono** [comment]
@aryan16 yes i changed the `VirtualService` to target the email claim.  Doesn't work! :)

**Comment by Tsingshen** [comment]
From https://github.com/tetratelabs/proxy-wasm-go-sdk/, and some other's work, this is now work for me.
You can try it https://github.com/tetratelabs/proxy-wasm-go-sdk/.

**Comment by aryan16** [comment]
It is not working with virtual service because we would require to have an ingress gateway. If your traffic is coming from ingress gateway and you have an jwt policy on gateway, it should be able to attach the header. This is only happening with ingress gateway becuase we can apply reqAuth policy to outbound for ingress whereas for sidecars we only apply to inbound. Anyway we will have this feature supported in our first class apis, it's good to wait for some time if this is not a blocker.

**Comment by Stono** [comment]
Hello
This was referenced in the 1,17 release notes but it is still open?
