### ISSUE TITLE
Append revision to istio-ca-root-cert

### ISSUE THREAD

**Issue by arkodg** [istio/istio#39739]
**Describe the feature request**
Most resources created by istio (or deployed along side it) have the istio revision appended to its name.
Consider doing the same for `istio-ca-root-cert` configmap that is created in every user namespace in the cluster
https://github.com/istio/istio/blob/1fd3cf1b91dbd34b8c6af4c9922a50649ed46088/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go#L35
Related https://github.com/istio/api/pull/2212#discussion_r828176899
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Revisions are expected to be in the same root of trust

**Comment by arkodg** [comment]
* @howardjohn that makes sense, looking at https://github.com/istio/istio/blob/222c91496e655cd54fcabbb7e927de5b4f3b5d5d/pilot/pkg/bootstrap/server.go#L943 (should I update the docs in https://istio.io/latest/docs/setup/upgrade/canary/#control-plane to highlight that both the Istiods must be in the same ns / have the same host string to make that an explicit requirement ?)
* this issue is slightly unrelated to ^, appending the revision to the configmap name ensures that each istiods does not contend with the other to create the same resource with the same name in a newly created namespace
* this also helps with cleaning up all istio resources, related https://github.com/istio/istio/issues/38497

**Comment by howardjohn** [comment]
I am not sure the relation to DNS names and the configmap? The istiods will not have the same host string -- the revision is part of the service. 

> this issue is slightly unrelated to ^, appending the revision to the configmap name ensures that each istiod does not contend with the other to create the same resource with the same name in a newly created namespace

we have leader election for that

**Comment by howardjohn** [comment]
This is working as intended
