### ISSUE TITLE
can not access grpc server with upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","grpc_status":14}

### ISSUE THREAD

**Issue by lw2331985** [istio/istio#39758]
### Bug Description

I have deployed one grpc server to the k8s in docker desktop and used istio as external LoadBalancer..
But I can not send request the grpc server..  I tried istio gateway+virtual service and istio ingress controller + k8s ingress.
All get the same error.  But if using port-forward to the service and access directly, it works.
Do you have any advise? Thanks

The log in my client:

>   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
>     raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111"
> 	debug_error_string = "{"created":"@1656829243.695862000","description":"Error received from peer ipv6:[::1]:80","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","grpc_status":14}" 

The output of "get all -n istio-system"

> NAME                                        READY   STATUS    RESTARTS   AGE
> pod/istio-egressgateway-59d4c446df-xj2nk    1/1     Running   0          91m
> pod/istio-ingressgateway-67d6475549-85ckn   1/1     Running   0          91m
> pod/istiod-544bd8d6bc-prv2s                 1/1     Running   0          91m
> 
> NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
> service/istio-egressgateway    ClusterIP      10.105.205.57    <none>        80/TCP,443/TCP                                                               91m
> service/istio-ingressgateway   LoadBalancer   10.109.231.223   localhost     15021:31834/TCP,80:31524/TCP,443:32037/TCP,31400:30109/TCP,15443:30839/TCP   91m
> service/istiod                 ClusterIP      10.109.252.249   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        91m
> 
> NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/istio-egressgateway    1/1     1            1           91m
> deployment.apps/istio-ingressgateway   1/1     1            1           91m
> deployment.apps/istiod                 1/1     1            1           91m
> 
> NAME                                              DESIRED   CURRENT   READY   AGE
> replicaset.apps/istio-egressgateway-59d4c446df    1         1         1       91m
> replicaset.apps/istio-ingressgateway-67d6475549   1         1         1       91m
> replicaset.apps/istiod-544bd8d6bc                 1         1         1       91m

The output of "istioctl proxy-config all istio-ingressgateway-67d6475549-85ckn -n istio-system"

> SERVICE FQDN                                                           PORT      SUBSET     DIRECTION     TYPE           DESTINATION RULE
> BlackHoleCluster                                                       -         -          -             STATIC
> agent                                                                  -         -          -             STATIC
> cert-manager-webhook.cert-manager.svc.cluster.local                    443       -          outbound      EDS
> cert-manager.cert-manager.svc.cluster.local                            9402      -          outbound      EDS
> grpc-flow0-predictor-default.default.svc.cluster.local                 80        -          outbound      EDS
> grpc-kagent.default.svc.cluster.local                                  80        -          outbound      EDS
> istio-egressgateway.istio-system.svc.cluster.local                     80        -          outbound      EDS
> istio-egressgateway.istio-system.svc.cluster.local                     443       -          outbound      EDS
> istio-ingressgateway.istio-system.svc.cluster.local                    80        -          outbound      EDS
> istio-ingressgateway.istio-system.svc.cluster.local                    443       -          outbound      EDS
> istio-ingressgateway.istio-system.svc.cluster.local                    15021     -          outbound      EDS
> istio-ingressgateway.istio-system.svc.cluster.local                    15443     -          outbound      EDS
> istio-ingressgateway.istio-system.svc.cluster.local                    31400     -          outbound      EDS
> istiod.istio-system.svc.cluster.local                                  443       -          outbound      EDS
> istiod.istio-system.svc.cluster.local                                  15010     -          outbound      EDS
> istiod.istio-system.svc.cluster.local                                  15012     -          outbound      EDS
> istiod.istio-system.svc.cluster.local                                  15014     -          outbound      EDS
> kserve-controller-manager-metrics-service.kserve.svc.cluster.local     8443      -          outbound      EDS
> kserve-controller-manager-service.kserve.svc.cluster.local             8443      -          outbound      EDS
> kserve-webhook-server-service.kserve.svc.cluster.local                 443       -          outbound      EDS
> kube-dns.kube-system.svc.cluster.local                                 53        -          outbound      EDS
> kube-dns.kube-system.svc.cluster.local                                 9153      -          outbound      EDS
> kubernetes.default.svc.cluster.local                                   443       -          outbound      EDS
> prometheus_stats                                                       -         -          -             STATIC
> sds-grpc                                                               -         -          -             STATIC
> xds-grpc                                                               -         -          -             STATIC
> zipkin                                                                 -         -          -             STRICT_DNS
> 
> ADDRESS PORT  MATCH DESTINATION
> 0.0.0.0 8080  ALL   Route: http.8080
> 0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
> 0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
> 
> NAME          DOMAINS                        MATCH                  VIRTUAL SERVICE
> http.8080     kagent-default.example.com     /*                     kagent-vs.default
>               *                              /healthz/ready*
>               *                              /stats/prometheus*
> 
> RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
> default           Cert Chain     ACTIVE     true           208755158203983183521281378457375741729     2022-07-04T04:56:57Z     2022-07-03T04:54:57Z
> ROOTCA            CA             ACTIVE     true           309110882139930430915266329701137923657     2032-06-30T04:56:07Z     2022-07-03T04:56:07Z

My deploy and svc yaml

> apiVersion: v1
> kind: Service
> metadata:
>   name: grpc-kagent
>   labels:
>     app: kagent
>     service: kagent
> spec:
>   ports:
>   - name: grpc
>     port: 80
>     targetPort: 9000
>     protocol: TCP
>   selector:
>     app: kagent
>   type: ClusterIP  
> ---
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: grpc-kagent
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: kagent
>       version: v1
>   template:    
>     metadata:
>       labels:
>         app: kagent
>         version: v1
>     spec:
>       containers:
>       - image: docker.io/lw233/kagent
>         imagePullPolicy: Always
>         name: grpc-kagent
>         ports:
>         - containerPort: 9000
>           protocol: TCP
>           name: grpc
 
The gateway and virtual service yaml

> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: kagent-gateway
> spec:
>   selector:
>     istio: ingressgateway # use Istio default gateway implementation
>   servers:
>   - port:
>       number: 80
>       name: grpc
>       protocol: GRPC
>     hosts:
>     - "kagent-default.example.com"
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: kagent-vs
> spec:
>   hosts:
>   - "kagent-default.example.com"
>   gateways:
>   - kagent-gateway
>   http:
>   - match:
>     - uri:
>         prefix: /
>     route:
>     - destination:
>         port:
>           number: 80
>         host: grpc-kagent.default.svc.cluster.local

In this mode, the logs in istio-ingressgateway-67d6475549-85ckn shows

> [2022-07-03T06:20:43.568Z] "POST /inferences.Inferences/CreateInferences HTTP/2" 200 URX via_upstream - "-" 5 0 93 92 "192.168.65.3" "grpc-python/1.47.0 grpc-c/25.0.0 (osx; chttp2)" "e5b64c5b-d5db-90d5-9ac7-05d94ebe910b" "kagent-default.example.com" "10.1.0.16:9000" outbound|80||grpc-kagent.default.svc.cluster.local 10.1.0.8:48500 10.1.0.8:8080 192.168.65.3:55808 - -

The logs in the sidecar shows

> [2022-07-03T06:20:43.573Z] "POST /inferences.Inferences/CreateInferences HTTP/2" 200 UF upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111} - "-" 5 0 0 - "192.168.65.3" "grpc-python/1.47.0 grpc-c/25.0.0 (osx; chttp2)" "e5b64c5b-d5db-90d5-9ac7-05d94ebe910b" "kagent-default.example.com" "10.1.0.16:9000" inbound|9000|| - 10.1.0.16:9000 192.168.65.3:0 outbound_.80_._.grpc-kagent.default.svc.cluster.local default
> [2022-07-03T06:20:43.612Z] "POST /inferences.Inferences/CreateInferences HTTP/2" 200 UF upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111} - "-" 5 0 0 - "192.168.65.3" "grpc-python/1.47.0 grpc-c/25.0.0 (osx; chttp2)" "e5b64c5b-d5db-90d5-9ac7-05d94ebe910b" "kagent-default.example.com" "10.1.0.16:9000" inbound|9000|| - 10.1.0.16:9000 192.168.65.3:0 outbound_.80_._.grpc-kagent.default.svc.cluster.local default
> [2022-07-03T06:20:43.660Z] "POST /inferences.Inferences/CreateInferences HTTP/2" 200 UF upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111} - "-" 5 0 0 - "192.168.65.3" "grpc-python/1.47.0 grpc-c/25.0.0 (osx; chttp2)" "e5b64c5b-d5db-90d5-9ac7-05d94ebe910b" "kagent-default.example.com" "10.1.0.16:9000" inbound|9000|| - 10.1.0.16:9000 192.168.65.3:0 outbound_.80_._.grpc-kagent.default.svc.cluster.local default

The ingress class and ingress yaml

> apiVersion: networking.k8s.io/v1
> kind: IngressClass
> metadata:
>   labels:
>     app.kubernetes.io/component: controller
>   name: istio
>   annotations:
>     ingressclass.kubernetes.io/is-default-class: "true"
> spec:
>   controller: istio.io/ingress-controller
> 
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: grpc-kagent
> spec:
>   ingressClassName: istio
>   rules:
>   - host: kagent-default.example.com
>     http:
>       paths:
>       - backend:
>           service:
>             name: grpc-kagent
>             port:
>               number: 80
>         path: /
>         pathType: Prefix

In this mode, the logs in istio-ingressgateway-67d6475549-85ckn shows

> [2022-07-03T06:00:49.378Z] "POST /inferences.Inferences/CreateInferences HTTP/2" 200 UF,URX upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111} - "-" 5 0 61 - "192.168.65.3" "grpc-python/1.47.0 grpc-c/25.0.0 (osx; chttp2)" "16bb6b5e-9ed0-95ad-b041-1f1e204ffb03" "kagent-default.example.com" "10.1.0.15:9000" outbound|80||grpc-kagent.default.svc.cluster.local - 10.1.0.8:8080 192.168.65.3:62916 - -

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (3 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.1
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by lw2331985** [comment]
My bad. It's bug in my image.

**Comment by wang-xiaowu** [comment]
> My bad. It's bug in my image.

hi, can u tell the reason of the bug?
