### ISSUE TITLE
give endpoint a name,then envoyfilter applyto endpoint ,select the endpoint,so we can config endpoint!

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39762]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
give endpoint a name,then envoyfilter applyto endpoint ,select the endpoint,so we can config endpoint!
**Describe alternatives you've considered**
I want to config endpoint's metadata
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is not something we plan on doing
