### ISSUE TITLE
Root Namespace ServiceEntry exportTo not work

### ISSUE THREAD

**Issue by chinaran** [istio/istio#39770]
According to doc: https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry
<img width="985" alt="image" src="https://user-images.githubusercontent.com/3775544/177168664-e57936f3-084b-4ebf-84ad-9f2f7ec900d2.png">
But when I deploy a ServiceEntry at istio-system, and set exportTo []{"some-ns"}, it still export to all namespaces.

**Comment by dddddai** [comment]
I can't reproduce this

**Comment by chinaran** [comment]
@dddddai thank you for your reply.
My case is that:
a serviceentry: hosts is demo.com. exportTo ns-1.
a virtual service A: match mesh traffic and route to egressgw-1.ns-1,
a virtual service B: match egressgw-1.ns-1 and route to demo.com,
so if I access demo.com from the s-2.ns-2 service, it is still successful.
This is normal, because the demo.com is finally accessed by the egressgw-1.ns-1, and there is no problem with exportTo visibility. I misunderstood it.
