### ISSUE TITLE
Clarification on 1.8 to 1.10 Direct Upgrades Announcement

### ISSUE THREAD

**Issue by bdschaap** [istio/istio#39786]
It was previously [announced](https://istio.io/latest/blog/2021/direct-upgrade/) that Istio 1.8 to 1.10 direct upgrades were supported.  Can I take this to mean that similar scenarios such as upgrading from 1.10.x to 1.12.x are also supported using the same approach?  What about any arbitrary version newer than the version I currently have in production?  Perhaps with the stipulation that the cluster is on a [supported version](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases) of K8s.

**Comment by ericvn** [comment]
From https://istio.io/latest/docs/setup/upgrade/canary/:

```
When using revision-based upgrades jumping across two minor versions is supported (e.g. upgrading directly from version 1.8 to 1.10). This is in contrast to in-place upgrades where it is required to upgrade to each intermediate minor release.
```

**Comment by bdschaap** [comment]
Much appreciated!  I see that the docs were updated in the Istio 1.11.x release.
