### ISSUE TITLE
installing envoy proxy along with windows containers

### ISSUE THREAD

**Issue by grk-pancham** [istio/istio#39788]
We have added windows node group in our Kubernetes cluster and started to deploy windows server applications in it. We are trying to deploy Istio envoy proxy along with the windows containers in windows node group. when we enabled the istio sidecar injection for the windows application namespace the the envoy proxy sidecar fails to come up saying the image is not supported. I guess the image we are using is a linux based image. how do we run windows based envoy proxy sidecar for windows namespace ? is this process documented ? 
We have Istio running on our linux nodes and we want to extend to support windows server application on windows node groups.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/27893

Its not suppotred
