### ISSUE TITLE
Init-container cannot able to access external resources in ISTIO strict mode

### ISSUE THREAD

**Issue by mohammadsuha** [istio/istio#39793]
i am trying to do some setup by connecting to external service from init-container but i am unable connect to external service in ISTIO strict mode but able to do when ISTIO mode is off.

i found out ISTIO CNI so i want to know whether ISTIO CNI will help to resolve the issue?

https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

in above document it says there are 3 ways we can do it

i want to know whether those 3 ways actually work to resolve the issue?

**Comment by howardjohn** [comment]
Yes, the documentation is correct. The CNI does not resolve the issue - the mitigations there work for both CNI and non-CNI, and the issue impacts CNI and non-CNI (although slightly differently)

**Comment by mohammadsuha** [comment]
if i specify sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0" in the deployment yaml file as below

spec:
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0

will it help to connect to external service from init-container?

if yes will it effect the traffic from the main container?

will it loosen the security in main container?
