### ISSUE TITLE
Set the Seccomp profile

### ISSUE THREAD

**Issue by hottea773** [istio/istio#39791]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

It is good practice to [Restrict a Container's Syscalls with seccomp](https://kubernetes.io/docs/tutorials/security/seccomp/). To do this one sets the `seccompProfile` field on the Pod's `securityContext`. Most container runtimes provide a sane set of default syscalls that are allowed or not, and these can be called using `RuntimeDefault`. 

I'd propose that Istio should set the `RuntimeDefault` for all pods it creates (`istiod` being the one I'm especially interested in).
It should also allow over-riding the `securityContext` of every pod and container it creates.

**Describe alternatives you've considered**

You could just make the `securityContext`s configurable.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
> Most container runtimes provide a sane set of default syscalls that are allowed or not, and these can be called using RuntimeDefault.

My main concern is about the set of container runtimes that are _not_ sane, and by adding RuntimeDefault we end up breaking them. That may be a small/empty set though

**Comment by hottea773** [comment]
Yeah, TBH I have no idea about that. We've been running on AKS (Azure) using the deprecated, but settable, annotation and it works, not that that's a great deal of info.

**Comment by ingwonsong** [comment]
@howardjohn what about adding `seccompProfile.type = RuntimeDefault` to ingress or egress gateway?

In other words, istio dataplane itself is working with `seccompProfile.type = RuntimeDefault`?

**Comment by howardjohn** [comment]
> [@howardjohn](https://github.com/howardjohn) what about adding `seccompProfile.type = RuntimeDefault` to ingress or egress gateway?
> 
> In other words, istio dataplane itself is working with `seccompProfile.type = RuntimeDefault`?

I don't think its possible for anyone to say that anything can work with `RuntimeDefault` because, IIUC, `RuntimeDefault` means "whatever the platform decided". They could decide to give no syscalls to any process -- obviously we would not meet that.

**Comment by ingwonsong** [comment]
ah.. yes.. it is correct. anyway thanks!
