### ISSUE TITLE
need "tiny istio footprint" install option (was bookinfo demo doesn't run on GKE free tier / 503 errors)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#398]
a user was using a GKE free tier and reported getting 503 errors

asking for their `kubectl get pods` 
```
reviews-v1-2536835021-n0m2b      2/2       Running   0          3h
reviews-v2-3299280847-9tg1l      0/2       Pending   0          3h
reviews-v3-4061726673-3wppp      0/2       Pending   0          3h
```
v2 and v3 couldn't get scheduled:
```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  10m           4s              40      default-scheduler                       Warning         FailedScheduling        No nodes are available that match all of the following predicates:: Insufficient cpu (4).
```
We need to adjust what we request - probably lowering Pilot and the monitoring, so it all fits

**Comment by ldemailly** [comment]
in the meantime I asked the customer to drop zipkin and servicegraph to see if it then goes through

**Comment by ldemailly** [comment]
that was the first thing I asked on the mailing list, they do have 4

the workaround I suggested, to drop zipkin and servicegraph made it work, we should minimally document and ideally tweak our quota requirements to make it fit

**Comment by linsun** [comment]
there is already docs for 4 nodes for GKE.  is there anything else for this?

**Comment by ldemailly** [comment]
yes we sadly need more than 4 if you install everything afaik - we need at least some FAQ and/or some tuning

**Comment by ldemailly** [comment]
not blocking the relase

**Comment by costinm** [comment]
Obsolete.

**Comment by ldemailly** [comment]
well it's not - I think we need an "istio-tiny" yaml that has some istio on tiny footprint

**Comment by costinm** [comment]
I really don't think this is a priority or required for 1.0. 
Bookinfo is a sample app - I doubt it should even be included in the release, we're not shipping a demo
and I don't think we should spend additional time on it.

We can discuss if shipping 1.0 requires bookinfo or we can have a smaller sample - but optimizing
bookinfo is the last thing we need...

**Comment by ldemailly** [comment]
I updated the summary, this isn't about bookinfo and having people able to give istio a try with a minimum requirements is helpful for adoption, we can talk with PMs if we disagree on usefulness

**Comment by ldemailly** [comment]
Still needed (helm values for smallest footprint)
