### ISSUE TITLE
RBAC Policy Debug?

### ISSUE THREAD

**Issue by ade90036** [istio/istio#39802]
I'm trying to debug an RBAC permission issue which I'm causing by experimenting a new configuration. 

The reason i'm doing this is because there is not enough documentation that covers certain aspects / best practices to layer `AuthorizationPolicy` in a microservice when you have multiple namespace, multiple application (and on top you have `ingres-gateway` with a `CUSTOM` policy connected to an external identity service)

So i have a top level `AuthorizationPolicy` at the gateway and then one per namespace and inside each namespace i have per application / workload. I'm following this approach so that different team only need to configure their workload `AuthorizationPolicy` and not mess around the other policies from other namespace / workloads.

Coming back to what i'm seeing `RBAC: access denied` : I did found an interesting article based on Istio 1.4 where you can login `http://localhost:9876/scopez/` and enable `rbac` logging so i can see where in the envoy logs which policy has failed, however this is not an option anymore.

Is there an alternative to achieve this in the latest ISTIO?

Maybe this should be a specific tutorial on how do debug general authentication / authorization message, one that is kept up to date with the latest release?

Also, if the general error message came back with more contextual information like, what policy ultimately caused the DENY either via
- _a propper response BODY in JSON_  
-  _extra headers_

It would SAVE a tremendous amount of time especially if you start consider scenarios which is not your standard product / review demo, where you have 50+ workloads. 

Regards

Andrea

**Comment by ade90036** [comment]
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (5 proxies)

**Comment by ade90036** [comment]
I did find an interesting tutorial around `Dry-Run` which solves what i was trying to do.

**Comment by howardjohn** [comment]
Closing as ^ answers this and there is no followup
