### ISSUE TITLE
ServiceEntry-created clusters are not matched in IPv6

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#39800]
### Bug Description

Hello everyone,
I think I found an issue with Istio 1.14.1 that is affecting connectivity to external services.
When SE are used in IPv6 to connect to external services, it seems that the requests are going into the BlackHoleCluster as they are not able to match the expected cluster.

The steps to reproduce are as follow:

0. Setup IPv6 KinD cluster or use another IPv6 cluster
1. Install Istio 1.14.1 with `istioctl install --set profile=demo --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY`
2. Deploy secrets for nginx via  `kubectl create secret tls nginx-server-certs --cert=nginx.example.com.crt --key=nginx.example.com.key -n istio-system`
3. Deploy nginx configmap via `kubectl create configmap nginx-configmap --from-file=nginx.conf=nginx_http_https.conf -n istio-system`
4. Label istio-system with istio-injection=enabled using `kubectl label ns istio-system istio-injection=enabled`
5. Deploy Sleep with sidecar `kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml -n istio-system`
6. Deploy nginx without sidecar `kubectl apply -f nginx_http_https_no_sidecar.yaml -n istio-system`
7. Get the podIP from `kubectl get pod $NGINX_POD -n istio-system --output=yaml`
8. Replace "NGINX_IP" in se.yaml with the pod ip you retrieved earlier and apply it `kubectl apply -f se.yaml -n istio-system`.
9. From the sleep container execute `curl https://nginx.example.com --max-time 5 --resolve nginx.example.com:443:[YOUR_NGINX_IP] -k`
It will fail with SSL_ERROR_SYSCALL. 
With the help of the sidecar lgos and you can verify that it did not match the nginx cluster and therefore it went to the blackhole.
```[2022-07-06T09:00:57.041Z] "- - -" 0 UH - - "-" 0 0 13 - "-" "-" "-" "-" "-" BlackHoleCluster - [fd00:10:244::8]:443 [fd00:10:244::f]:51048 - -```
This steps does not fail on IPv4.
10. Try the same curl request from a sleep container without sidecar and everything will work as expected.

I'm attaching the resources needed to execute the aforementioned steps [resources.zip](https://github.com/istio/istio/files/9053374/resources.zip)

### Version

```prose
Istioctl:
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (3 proxies)

Kubectl:
Client Version: v1.20.1
Server Version: v1.21.1
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9053341/bug-report.tar.gz)

**Comment by LithiumSR** [comment]
After testing for a while, I managed to find out that this issue was introduced with the deprecation of "envoy.reloadable_features.listener_wildcard_match_ip_family"
in Envoy

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, I have tried to reproduce this issue both in `release-1.14` and `master` branch, however, I can not reproduce it. Besides that, I also checked code from Istio, and there is no place to set the runtime guard: `envoy.reloadable_features.listener_wildcard_match_ip_family`, and this feature gate is just a temporary protection for backward compatibility. Here are some related issues and PRs:
https://github.com/envoyproxy/envoy/pull/16914
https://github.com/envoyproxy/envoy/issues/19507
https://github.com/envoyproxy/envoy/pull/19669

Hope it helpful!

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, after some investigation, I also find out the root cause from Istio side, and submitted a PR for this issue. Please refer to [here](https://github.com/istio/istio/pull/39986) for more detail information.

**Comment by LithiumSR** [comment]
Hello @zhlsunshine 
Sorry if I respond only now but I had some days off.
Thank you for the PR, I will test it from my side to check if there are any regressions and let you know 👍

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, sure, good luck!

**Comment by LithiumSR** [comment]
Hi @zhlsunshine.
I can confirm that your changes are fixing the issue and I did not notice any regression while testing.

Thank you :)
