### ISSUE TITLE
istio-discovery helm chart appears to be ignoring proxy_init resources

### ISSUE THREAD

**Issue by e1ven** [istio/istio#39820]
### Bug Description

The values file for the helm chart [allows you to specify the resources that should be used for the init container](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L371).

This value appears to be ignored, in favor of using the [proxy resources](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L350)

It looks like what may be happening is that the [same resources template](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L23) as the sidecar [is called](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml#L385).

This template appears to only use `.Values.global.proxy.resources`, and will not respect `.Values.global.proxy_init.resources`

### Version

```prose
This appears in the `master` branch.
Testing with chart version 1.13.4
kubectl Client Version: v1.23.0
Applying the chart using argo-cd v2.4.3, but it appears to be unrelated to the installation method.
```

**Comment by howardjohn** [comment]
This is working as intended but we should. update the docs / hide /remove the field.
