### ISSUE TITLE
Prow Shows Irrelevant `hack/e2e.go` under Failed Test Cases

### ISSUE THREAD

**Issue by chxchx** [istio/istio#3982]
Istio now has junit results on Prow. It shows command like `go run hack/e2e.go -v --test --test_args=‘--ginkgo.focus=istio\.io\/istio\/pilot\/pkg\/config\/kube\/crd\sTestControllerCacheFreshness$` under each failed test case, which is a message that does not apply to istio. We use a recent fork of Prow from k8s and this message does not apply to istio and is misleading to the istio developers. Looking forward to removing or customizing it.

**Comment by hklai** [comment]
Obsolete. Closing.
