### ISSUE TITLE
Cross cluster calls do not work with istio multi cluster with Multi Primay multi network

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [istio/istio#39843]
### Bug Description

I tried configuring istio mutli cluster by following instructions for Multi primary multi network as is. Clusters are on AKS and istio version 1.12.2

All the pre-requisites and configurations are done as mentioned. However cross cluster calls always fail with error "Could not resolve host". I am using the helloworld and sleep apps for verification given in istio documentation. istioctl remote-clusters does show the right cluster name with status as synced. Can you point me to what could be causing this issue?

### Version

```prose
istioctl version
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (4 proxies)
kubectl version --short
Client Version: v1.22.2
Server Version: v1.22.6
```

**Comment by hzxuzhonghu** [comment]
Does helloworld services only  reside in one cluster, and if so, maybe you do not enable DNS proxy.

**Comment by SoujanyaMangipudi** [comment]
@hzxuzhonghu we have helloworld and sleep services deployed to both clusters (Same as mentioned in the instructions). Trying to hit helloword service of different cluster errors out always. Also can you elaborate what you mean by enabling DNS proxy? Are you referring to step of exposing local services behind east west gateway?

**Comment by SoujanyaMangipudi** [comment]
turns out this issue was due to incorrect configuration. We had to set multicluster enabled to true in istiooperator resources and then the URL started getting resolved.

**Comment by jjluUp** [comment]
I have another question, expose all services (*.local) on the east-west gateway in both clusters(I was following the instructions as is), but useless, the eastwest gateway service of type NodePort
![image](https://user-images.githubusercontent.com/48275582/178906488-99a99feb-2852-42a6-86c6-436c24ab53a4.png)
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
    - hosts:
        - '*.local'
      port:
        name: tls
        number: 15443
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH

**Comment by hzxuzhonghu** [comment]
@[SoujanyaMangipudi](https://github.com/SoujanyaMangipudi) Can you check if your kube-dns work? DNS resolve in your case is not handled by istio dns proxy.
