### ISSUE TITLE
Unable to configure accessLogEncoding as JSON in telemetry configuration

### ISSUE THREAD

**Issue by ramanujadasu** [istio/istio#39845]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Unable to configure accessLogEncoding as JSON in telemetry configuration
Configuration details:

**IstioOperator yaml file for default or minimal profile:**

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
….
spec:
  …
  meshConfig:
    accessLogEncoding: JSON/TEXT
    accessLogFile: /dev/stdout

**Telemetry yaml file:**
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  ...  
  name: mesh-default
  namespace: istio-system
  resourceVersion: "425415"
  uid: 0e51a869-20d4-4a95-8021-dcbd51a5251c
spec:
  accessLogging:
  - disabled: false
  - filter:
      expression: response.code != 200
  - providers:
    - name: envoy

Could you please verify and help me to resolve this issue as soon as possible. If providing guidance, i will contribute the implementation for this task.

**Describe alternatives you've considered**
No alternative for telemetry accessLogEncoding as JSON configuration

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (3 proxies)
$ kubectl version --short
Client Version: v1.22.5
Server Version: v1.23.4

References:
https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-all.gen.yaml#L6210
https://istio.io/latest/docs/reference/config/telemetry/#AccessLogging

**Comment by zirain** [comment]
it's work as expected, you should config them on `Mesh.ExtensionProvider`, then refenerce them in `Telemetry` or `defaultProviders`, [here] is a demo.

**Comment by ramanujadasu** [comment]
Thanks @zirain , i will test

**Comment by ramanujadasu** [comment]
@zirain, JSON logs are working before telemetry configuration. After telemetry configuration, it is overriding TEXT format automatically.

Could you please try and confirm,  after telemetry configuration. Are able to see JSON format logs?
     
Reference:
![image](https://user-images.githubusercontent.com/5461660/179215025-14612bfb-92db-486f-a3e2-372d5c75b37b.png)

**Comment by zirain** [comment]
if you're using my demo config, you should change ther provider name in telemetry to `file-log`

**Comment by zirain** [comment]
BTW, we're trying to fix https://github.com/istio/istio/issues/39468

**Comment by ramanujadasu** [comment]
Thanks @zirain , 
After your inputs, its working as expected. With bellow comments closing this issue.


Sample telemetry configuration:

apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  #selector:
  #  matchLabels:
  #    service.istio.io/canonical-name: httpbin
  # no selector specified, applies to all workloads in the namespace
  accessLogging:
    #- match:
    #    mode: "CLIENT_AND_SERVER"
    - disabled: false
      providers:
        #- name: envoy
        - name: file-log
      filter:
        expression: response.code != 200
