### ISSUE TITLE
How could I set oap.envoy.als.enabled on a exist skywalking oap?

### ISSUE THREAD

**Issue by stevenlii** [istio/istio#39856]
I have installed skywalking  without set oap.envoy.als.enabled=true, how could I set oap.envoy.als.enabled on a exist skywalking oap?
and configuration: SW_ENABLE_UPDATE_UI_TEMPLATE also confused me. 
```
helm install 8.1.0 skywalking -n istio-system \
  --set oap.env.SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS=mx-mesh \
  --set oap.env.SW_ENVOY_METRIC_ALS_TCP_ANALYSIS=mx-mesh \
  --set fullnameOverride=skywalking \
  --set oap.envoy.als.enabled=true
```

 istioctl version 1.11
kubectl v1.21.8

**Comment by zirain** [comment]
I think this's something related to skywalking community, you should open ticket in https://github.com/apache/skywalking
