### ISSUE TITLE
Multiple rollouts causing 503 errors since istio 1.14.0

### ISSUE THREAD

**Issue by nuttmeister** [istio/istio#39870]
Running k8s `1.22` on `AWS EKS` using AMI `ami-0fd784d3523cda0fa` (lastest AMI in eu-west-1 as of this writing).

Versions not working:
- `1.14.0`
- `1.14.1`

Versions working:
- `1.13.5 and older`

We have a deployment setup that is maybe not typical that has started to fail after updating to `1.14.0` and later `1.14.1`.
We have a process that needs to run quite long after receiving SIGTERM (up towards 300s) so we have set both `terminationGracePeriodSeconds` on the pod and `terminationDrainDuration` on the proxy sidecar.

Due to this long delay and using rollouts where we replace one pod at a time and deployments through gitops we can have multiple deploys rolling out at the same time (new one replacing the one currently being rolled out).

This shouldn't be an issue and have worked up until now. When these circumstances occurs, that a new rollout gets triggered before a previous rollout has completely finished replacing the original deployment the draining sidecar proxy will start receiving traffic that, for obvious reasons, will cause `503 upstream connect error or disconnect/reset before headers` error on the sidecar proxy since it's draining.

I did some testing on this and it seems to be to be related to the new `LEAST_REQUEST` load balancing default in `1.14.x` that is causing it. Because if I add a `DestinationRule` and specify `ROUND_ROBIN` it works. However I only ran the test 5 times before having to take vacation. So could be I was just lucky on those times and it worked. But doubt it, since this error is quite easy to reproduce.

I tried to simply go back to using `ROUND_ROBIN` as the default for this using the env variable described in the release notes of `1.14.0` that is `ENABLE_LEGACY_LB_ALGORITHM_DEFAULT` set to `true`, but that didn't work.
I think it only switches to the old default if there is a `DestinationRule` defined  and still uses the new algo if there is no `DestinationRule`. This is however just my guess, I didn't have time to debug this more in-depth before leaving.

Since we have services that doesn't have a `DestinationRule` configured on them we instead opted for rollbacking to `1.13.5` and it now works as intended again.

Sorry for the rather lack luster Issue report here - vacation got in the way but will try and get some time and do more proper debugging to see what is going on exactly.

For testing and examples how to reproduce I put my rather lack-luster tests here:
https://github.com/nuttmeister/istio-multi-deploy-test

**Comment by hzxuzhonghu** [comment]
Maybe related to SendUnhealthy endpoints  FYI    https://github.com/istio/istio/issues/39825

**Comment by yichouchou** [comment]
wow,thank you for what u do,i found it did't work and feel puzzled.

**Comment by howardjohn** [comment]
fixed via https://github.com/istio/istio/pull/39834
