### ISSUE TITLE
find and run http 1.1 and 2.0 compliance tests

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3987]
We need to find some http 1.1 and 2.0 compliance tests to run through our sidecar setup and ensure both the client side and server side of the sidecar at least respect the specs and help improve the reliability of the http applications they wrap rather than degrade it.

context: 
https://github.com/envoyproxy/envoy/issues/2066
https://github.com/envoyproxy/envoy/issues/2715

(would solve https://github.com/istio/fortio/issues/38 too)

**Comment by PiotrSikora** [comment]
(I'm slowly working on this...)

**Comment by ldemailly** [comment]
poke
