### ISSUE TITLE
instructions to install correctly istio on a kubernetes cluster

### ISSUE THREAD

**Issue by ntonx** [istio/istio#39884]
I have tried to **_install Istio on a distribuited manner_**, I mean, I have install **k8s** using kubeadm on three servers (**_1 master and 2 workers A & B_**, using the comand `kubeadm init` (in the master) & `kubeadm join` (in the workers))

After that, I download the Istio binary on the master and executed the command "`istioctl install --set profile=demo -y`", 

If I execute "install --set profile=demo -y" without making changes in demo.yaml, istiocd go to one worker and ingressgateway or egressgateway goes to other worker and **_istio is not installed sucessfully._**

when i make some changes in demo.yaml file in order to send all the Istio's components to the k8's worker A , Istio is installed successfully but when I execute the bookinfo demo, the problem is that services that are deployed on the worker B (that does not contain Istio's elements) are not deployed sucessfully or are not discovered by the services deployed on A, 

what's the correct way to install Istio on this scenario?

I use Centos 7

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", Platform:"linux/amd64"}

istioctl version:
1.12.8

**Comment by zirain** [comment]
> when i make some changes in demo.yaml file in order to send all the Istio's components to the k8's worker A , Istio is installed successfully but when I execute the bookinfo demo, the problem is that services that are deployed on the worker B (that does not contain Istio's elements) are not deployed sucessfully or are not discovered by the services deployed on A,

looks like you have some trouble with network traffic across node?

**Comment by howardjohn** [comment]
That is how kubernetes is expected to work
