### ISSUE TITLE
Istio 1.14.1 doesn't support statefulset headless services

### ISSUE THREAD

**Issue by asad-awadia** [istio/istio#39886]
### Bug Description

There are tonnes of tickets and comments around the poor support for statefulset headless services - no idea if it works or just got closed

When I scale my stateful set to have 2 replicas - pod 1 can resolve pod 0's dns but pod 0 cannot resolve pod 1's dns?

Why would that be? is it because pod 0 existed when pod 1 was created but not vice versa?

Is there anything specific that needs to be done to support this use case?

### Version

```prose
istio: `1.14.1`


k8s
Client Version: v1.23.6
Server Version: v1.21.12-eks-a64ea69
```
```


### Additional Information

_No response_

**Comment by hzxuzhonghu** [comment]
By default, istio does not intercept udp dns resolve.

**Comment by asad-awadia** [comment]
@hzxuzhonghu even if we have capture dns set to true?

**Comment by hzxuzhonghu** [comment]
There is good explanation here https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/

**Comment by asad-awadia** [comment]
@hzxuzhonghu is a service entry not created until the pod comes up healthy?

**Comment by hzxuzhonghu** [comment]
what do you mean?

**Comment by asad-awadia** [comment]
@hzxuzhonghu will the dns of pod 1 be resolvable from pod 0 - if pod 1 has not come up healthily?

**Comment by howardjohn** [comment]
Stateful sets should work out of the box. We would need more info to know what is going on .How can we reproduce?
