### ISSUE TITLE
Design docs workflow (proposal/discussion)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#399]
This came up in #383 

I propose we have the (finalized) design docs in github - either in this repo or better under https://istio.io/docs/

During design discussions on the istio-dev@ mailing list we can use google docs links that are shared to whoever gets the link - or just have PRs and reviews / discussions on the doc in .md format ?

**Comment by geeknoid** [comment]
We had a consensus decision that driving substantial design discussions through GitHub issues is unpleasant. We don't want to do that.

I believe we also talked about using markdown files, but they're also unpleasant and inefficient for anything substantial. Google Docs provides a much better workflow, with commenting, editable drawings, table of contents, etc. Of course, you can do all this in markdown and GH, but you really can't compare usability and efficiency of the two approaches.

All right, so given the above, then we're firmly in the camp of using Google Docs for any substantial design doc authoring. We keep those in Team Drive and have a simple process to grant read and write access to the Team Drive. That leaves two points open:

- Do we need/want to snapshot "finalized" Google docs into GitHub?
- Are design docs appropriate for istio.io?

I don't see the benefit of creating snapshots in GH. Why do you think this would be desirable?

And regarding istio.io, I don't believe design documents are appropriate for istio.io in their raw form. istio.io is really a user portal, not a developer portal.

**Comment by ldemailly** [comment]
Thanks for the comment - I meant doc PR and not issue - but drawings etc are indeed painful.

The reason I would put the docs in a folder on the website is so they can be visible without a request access step - the source are readily available to anyone, so probably should the design docs, with low friction

we could make world viewable or commentable docs like
https://docs.google.com/document/d/1M-KMt5_TLq984F8MqVRcmXfEHS1EWvmCpFkdQbYFwsQ/edit?usp=sharing
(need to create the doc with personal account)

I think it's useful to have a directory of the past designs though

so maybe we can share world readable a full folder:
https://drive.google.com/drive/folders/0B2ROy-EaSsxiNWY1S2dyeGwtS0E?usp=sharing
(I wonder if there are limits on how many people can view etc)

maybe we need a dev portal if we can't get github alone to work

**Comment by ldemailly** [comment]
cc @linsun who was wondering about similar questions

and closing this unless someone wants to reopen
