### ISSUE TITLE
can we add a feature like kubectl get all to get all resource in istio

### ISSUE THREAD

**Issue by xiayanzheng** [istio/istio#39906]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
can we add a feature like kubectl get all to get all resource in istio

**Describe alternatives you've considered**
istioctl get all

**Affected product area (please put an X in all that apply)**

[ x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
`kubectl get istio-io` already does this

**Comment by howardjohn** [comment]
Its a builtin feature of k8s by the `category` field on CRD
