### ISSUE TITLE
"response_code" and "response_code_class" in envoy stats tags 

### ISSUE THREAD

**Issue by Shuanglu** [istio/istio#39903]
### Bug Description

- Issue: 
I'm checking the metrics of the envoy in istio but found the tag 'response_code' seems to be missing. 

- Investigation:
There is a regex to match the 'response_code' but it looks like there is an addtional `\\.` in the [expression](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap.json#L48) `"regex": "(response_code=\\.=(.+?);\\.;)|_rq(_(\\.d{3}))$",`
Also the 'response_code_class' matches the whole status code and remove the 'xx' from the metrics name which could be a conflict with the 'response_code' one. The same metrics name but have two different group of tags. Probably something like `_rq_(\\d)xx$` could be better? 
  ```
  # TYPE envoy_cluster_upstream_rq counter
  envoy_cluster_upstream_rq{service="downstream-v2",envoy_response_code="200",cluster_name="xds-grpc",envoy_cluster_name="xds-grpc"} 1
  envoy_cluster_upstream_rq{service="downstream-v2",response_code_class="2xx",cluster_name="xds-grpc",envoy_cluster_name="xds-grpc"} 1
  ``` 

- Expected 
envoy metrics have the tag 'response_code' and 'response_code_class'

### Version

```prose
client version: 1.14.1
control plane version: 1.13.4
data plane version: 1.13.4 (2 proxies)

Client Version: v1.23.4
Server Version: v1.20.10
```

**Comment by zirain** [comment]
related to https://github.com/envoyproxy/envoy/issues/22591
