### ISSUE TITLE
Allow option to disable zipkin calls when tracing is enabled

### ISSUE THREAD

**Issue by jjchambl** [istio/istio#39912]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Zipkin was removed from our k8s clusters, but there is currently no way for us to remove reference to it from our Istio ConfigMaps without disabling tracing altogether. The failed calls to zipkin result in an excessive amount of error logs (I'm assuming the calls are retried in the event of failure). We would like an additional option added to the Istio configuration to enable tracing headers, but disable sending traces to zipkin.

**Describe alternatives you've considered**
We have explored sending the traces to Datadog, but 1) this would add to our networking costs, and 2) many of our applications send these headers through to Datadog already in their own logs, so the calls would be redundant.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jjchambl** [comment]
> 

That's correct. I considered opening this as a bug as we do not have zipkin in our istio install, but it attempts to send the trace regardless.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/34217 allows this

**Comment by zirain** [comment]
@howardjohn I think https://github.com/istio/istio/pull/34217 did not fix this, `GetEffectiveTemplatePath` will return default tracing with zipkin configuration.

**Comment by howardjohn** [comment]
It did at one point... maybe it regressed

**Comment by jjchambl** [comment]
Will need to check this with my team (am currently on parental leave), but I'm gathering it's possible the linked issue does not resolve my report?

**Comment by melichron** [comment]
Any instrustuctions didn't works for me, but after all I disabled zipkin by explicity add podAnnotation to every pod with sidecar and istio gateways:
```
        podAnnotations:
          proxy.istio.io/config: |
            tracing: {}
```
That will overwrite any upstream settings.
