### ISSUE TITLE
Adding custom metrics generating a new weird metrics name

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#39932]
### Bug Description

We are trying to expose custom metrics in Istio with this configuration
```
apiVersion: install.istio.io/v1alpha3
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      extraStatTags:
        - test
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    # test: request.method
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    # test: request.method
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                - dimensions:
                    # test: request.method
```

after we deploy with istioctl
```
istioctl upgrade -f cluster.yaml --force --skip-confirmation
```

we found out that metrics are changing from
```
# TYPE istio_requests_total counter
istio_requests_total
```

to 
```
# TYPE test___GET___istio_requests_total counter
test___GET___istio_requests_total
```

This will automatically resolve when we roll out and restart the sidecar/gateway.
we suspect that this is because of bootstrap config is not being updated.

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (3 proxies)
kubectl version --short
Client Version: v1.21.7
Server Version: v1.23.6+k3s1
```

**Comment by fatedier** [comment]
Maybe you can first add extraStatTags in meshConfig, then rollout restart all your pods to update bootstrap config.

Finally, add telemetry configOverride.

**Comment by zufardhiyaulhaq** [comment]
Hi @fatedier, yes we actually do that and it works now. but it's not ideal.

**Comment by douglas-reid** [comment]
@zufardhiyaulhaq this is a limitation of introducing new labels with Istio/Envoy unfortunately. your guess about bootstrap is correct.

there are some ways to work around having to add the tags to your meshconfig, but they are a bit more involved -- and use the off-by-default bootstrap discovery service. there is an integration test demonstrating EnvoyFilters to add new dimensions here: https://github.com/istio/istio/blob/b26ae0e867fe7a6e44765cf319fd1dc36b07eea3/tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go#L120-L213

**Comment by iPapanya** [comment]
the same problem

but we has another problem - we don't want to add extra tags for every deployment. We add add on several using pod annotations. And with other pods we have the same problem - they are producing metrics with weird names instead of defaults

**Comment by iPapanya** [comment]
how can I add new dimensions only on specific deployments?

**Comment by zufardhiyaulhaq** [comment]
Thanks @douglas-reid, we will keep with the standard way of exposing custom metrics.

@iPapanya you must have Istio v1.12, in 1.12, we introduce a new object called Telemetry, I believe this object can help to expose custom metrics per deployment.

**Comment by zufardhiyaulhaq** [comment]
Let me close this ticket.

**Comment by iPapanya** [comment]
Thanks, @zufardhiyaulhaq!
But we steel have a problem: we have added 2 metrics in global mesh (request_method and request_operation from istio docs) and add both of them in extraStatTags.
And for several deployments we have added Telemetry with extra metric (request_urlpath) as it described in https://istio.io/latest/docs/reference/config/telemetry/. It starts generate weird metrics name until we have added annotation in deployment "sidecar.istio.io/extraStatTags: request_urlpath". Weird metrics name disappeared, but now at each request we have two metrics: one with request_urlpath and another one without. And also istioctl x precheck said 'Annotation "sidecar.istio.io/extraStatTags" is part of an alpha-phase feature and may be incompletely supported.'

client version: 1.12.1
control plane version: 1.13.8
data plane version: 1.13.8 (266 proxies)

**Comment by zirain** [comment]
Telemetry cannot work with envoyfilter way

**Comment by iPapanya** [comment]
> Telemetry cannot work with envoyfilter way

@zirain 
Telemetry resource is not the same when I use telemetry mesh wide?

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/39772#issuecomment-1287244040
