### ISSUE TITLE
Workload doesn't trust additional root certificates provided in caCertificates under meshConfig

### ISSUE THREAD

**Issue by Ser87ch** [istio/istio#39935]
### Bug Description

We have multiple Kubernetes cluster set up with Istio mesh under one root certificate. We're working on a way to be able to rotate the root certificate, so clusters with intermediate certificate issues by the old root and clusters with intermediate certificate issues by the old new one are able to communicate. According to [Global Mesh Options](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) `caCertificates` property is exactly what we need:
> The extra root certificates for workload-to-workload communication.

But once we set everything up workload-to-workload doesn't work. Although it worked when root certificate between clusters was the same.

### To reproduce
I've created two clusters with plugged in certificates as described in [Plug in CA Certificates](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/) with two different roots. I added a deployment in each cluster. I set up ServiceEntry and DestinationRule in the cluster-1 to enable a pod to communicate to the cluster-2's pod. I also updated meshConfig in both clusters to contain another one's root certificate in the caCertificates property using IstioOperator as described in [Global Mesh Options](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    caCertificates:
    - pem: |-
        -----BEGIN CERTIFICATE-----
        %another cluster root cert%
        -----END CERTIFICATE-----
```
After setup curl from the first cluster pod to the second cluster pod fails with:
```
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56
```
Whereas when I have the same setup but both clusters using the same root, it works.

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (2 proxies)
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liminw** [comment]
@shankgan Please take a look.

**Comment by shankgan** [comment]
this capability is hidden behind two flags - one in Istiod the other on the proxy

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      env:
        ISTIO_MULTIROOT_MESH: true
  meshConfig:
    defaultConfig:
      proxyMetadata:
        PROXY_CONFIG_XDS_AGENT: "true"
   meshConfig:
      caCertificates:
      - pem: |-
          -----BEGIN CERTIFICATE-----
          %another cluster root cert%
          -----END CERTIFICATE-----

**Comment by Ser87ch** [comment]
Thanks, it worked. Should these flags be mentioned in the documentation though?

**Comment by shankgan** [comment]
Since these are environment variables, not sure where to document them. Possibly, we should default these flags to always on and remove them eventually. No use in having them off afaik

**Comment by devshah1** [comment]
@shankgan Running into the same issue, however I'm stuck while trying to securely pass the another cluster's root cert to `caCertificates.pem` property above. Injecting the secret via volumes is out of the question since support for that is still in [alpha](https://github.com/istio/istio/commit/efc551e33f93c9e4f7241caa49100ea89ecfb56e). Can you please advise?

**Comment by Ser87ch** [comment]
We use Terraform to install Istiod Helm chart.
Additional configuration incl. certificates  is set in meshConfig https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L199 from the Helm chart properties. Additional certificates are passed as a Terraform module variables.

**Comment by devshah1** [comment]
Thanks for the reply, wish we were using terraform. We use flux in combination with kustomize instead so trying to figure out if I can apply a patch for the `caCertificates` property in `values.yaml` from a secret.

**Comment by yankunsam** [comment]
Has anyone encountered this problem before?
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE
```
