### ISSUE TITLE
Not all remote clusters have reachable Kiali instances

### ISSUE THREAD

**Issue by grhovo** [istio/istio#39962]
### Bug Description

Hi team, I am facing issues trying to use Istio Multicluster version with Kiali.

I am getting following error:
Context menus are disabled for remote cluster nodes if a Kiali instance is not discovered, or if the remote Kiali is not configured with an external URL.

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/37000448/179521199-739aa789-ec75-48ca-8ab1-987fded4e4a1.png">

I have tried the following suggestion: https://github.com/kiali/kiali/issues/4670 and added web_fqdn & web_schema. But still getting same issue. Please help with this. 

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (1 proxies)

kubectl version --short
Client Version: v1.23.0
Server Version: v1.19.16-eks-de875a99

helm version --short
v3.8.1+g5cb9af4
```

**Comment by howardjohn** [comment]
Please file in https://github.com/kiali/kiali
