### ISSUE TITLE
sidecar config with workload selector is not applied to root namespace

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#39989]
### Bug Description

I am trying to setup the mTLS termination at sidecar using the sidecar API use case according to the newly introduced feature in istio 1.13 based on https://github.com/istio/istio/pull/36210  and came around the following limitation:

When installing the example mentioned [here](https://github.com/istio/api/blob/master/networking/v1alpha3/sidecar.proto#L404) in `istio-system` namespace(instead of prod-us1 namespace as in the example), which is the default rootNamespace in my deployment, the workload selector in the sidecar configuration doesn’t become effective. This seems to be due to the specific behaviour of the sidecar API in rootNamespace, see Note 2 on https://istio.io/latest/docs/reference/config/networking/sidecar/

[Note2](https://github.com/istio/api/blob/master/networking/v1alpha3/sidecar.proto#L57)

This means in the end, the entire use case becomes ‘invalid’ for the rootNamespace.
Is this limitation of sidecar API intentional? This makes the TLS termination at sidecar solution unusable for us.

The below code seems to be the relevant area which checks if rootNamespace sidecar config has a workloadSelector or not:
https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1637

### Version

```prose
istioctl version : 1.14.1
kubectl version: 1.23.1
```

**Comment by kfaseela** [comment]
cc @shriramsharma

**Comment by sschepens** [comment]
`PeerAuthentication` policies have the same issue, when configuring a selector on the root namespace they stop working across all namespaces.

**Comment by howardjohn** [comment]
> when configuring a selector on the root namespace they stop working across all namespaces.

WorkloadSelector is not supposed to apply to all namespaces. IIUC @kfaseela is saying its not working _at all_?

**Comment by kfaseela** [comment]
> > when configuring a selector on the root namespace they stop working across all namespaces.
> 
> WorkloadSelector is not supposed to apply to all namespaces. IIUC @kfaseela is saying its not working _at all_?

yes @howardjohn, looks like sidecar api with workloadSelector does not get effective in istio-system namespace at all. Something related seems to be present in the code comment here: https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1637

Any reason why such a restriction is present? Is this something that can be changed?

**Comment by shriramsharma** [comment]
hey @howardjohn , the issue is not with the `workloadSelector` field. 
I think what @kfaseela is trying to say is that currently the way it is coded [here](https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1637),  a sidecar config can `only` be applied to the `root namespace` if it **does not** contain the `workloadSelector` field. 

Due to this restriction, they cannot use the TLS/mTLS termination feature on the sidecar proxy. 

Can you please provide some historical context as to why this restriction was added?
