### ISSUE TITLE
Update istio control plane and minimize the number of service restarts

### ISSUE THREAD

**Issue by qRainBirdp** [istio/istio#39991]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

We are using istio version 1.6.6 in our production environment for a long time.We want to update it to version 1.12.8 by canary.But we have a service has been injected with many devices connected.When we upgrade a version we have to restart all the services for sidecar to update.At this point the concurrent pressure from device reconnections can overwhelm our servers.Update one by one slowly waiting for the device to connect will bring a long downtime.
According to the documentation I need to restart all services at least three times.Can there be some kind of update that only reboots once?

**Describe alternatives you've considered**
I have tried to update directly to version 1.12.8.But I got these errors:

> 2022-07-19T01:22:29.994098Z     error   installer       failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.10-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

> 2022-07-19T01:22:30.042608Z     error   installer       failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.11-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

> 2022-07-19T01:22:30.070783Z     error   installer       failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.12-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

> ✘ Istiod encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.10-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

> failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.11-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

> failed to update resource with server-side apply for obj EnvoyFilter/istio-systemats-filter-1.12-1-12-8: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager
        * Envoy filter: subfilter match requires filter match with envoy.http_connection_manager

I tried to update to 1.8.6 first and uninstall the control plane of 1.6.6.Then I was able to update to version 1.12.8 and no errors were reported(Not tried in production environment).But this still requires two reboots and may have unknown errors.

So is there a less frequent and safe way to update istio?

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Comment by qRainBirdp** [comment]
> maybe you can disabled the webhook during upgrading?

How to disable webhook, will it affect the sidecar of existing services?

**Comment by zirain** [comment]
> > maybe you can disabled the webhook during upgrading?
> 
> How to disable webhook, will it affect the sidecar of existing services?

find out by running `kubectl get MutatingWebhookConfiguration`

**Comment by qRainBirdp** [comment]
> 



> > > maybe you can disabled the webhook during upgrading?
> > 
> > 
> > How to disable webhook, will it affect the sidecar of existing services?
> 
> find out by running `kubectl get MutatingWebhookConfiguration`

I got these:
agent-injector-webhook-ambassador   
cert-manager-webhook                
istio-sidecar-injector              
pod-identity-webhook                
rancher-monitoring-admission        
vpc-resource-mutating-webhook       

Should I delete one of them? Or should I change the configuration of one of them?

**Comment by zirain** [comment]
`istio-sidecar-injector` is the one istio used.

**Comment by qRainBirdp** [comment]
> kubectl get MutatingWebhookConfiguratio

Still the same error.
We've decided to update the version in batches. Anyway thanks a lot!
