### ISSUE TITLE
Unable to Access Flux pods via Istio Ingress - UF,URX upstream_reset_before_response_started{connection_failure}

### ISSUE THREAD

**Issue by praseed44** [istio/istio#40006]
Hi,

We have Istio 1.12.4 version installed using Operator in Azure Kubernetes Service. Flux is also deployed into AKS using helm charts. Created Virtual Service to expose flux clusters-service via Istio Ingress Gateway and running into error - **_503 UF,URX upstream_reset_before_response_started{connection_failure}_**

Port-forwarding works OK to the service locally to access the UI of Flux. However, the issue is only while trying to access the UI over Istio Ingress. The request is reaching gateway pod and it looks like gateway is unable to communicate to upstream due to some connectivity issue. Tried a curl request from gateway and it is not able to reach flux service on port 8000. However, the upstream flux pods are working Ok and service is also available with 8000 port configured. 

Flux pods do not have Istio sidecar by default. As part of troubleshooting the issue, manually injected sidecar as well without any luck. Curl request from the istio-proxy(in the app) is able to access the flux service on localhost, though.

Any inputs on this would be appreciated. Also, please let us know if there are any areas to be checked further.

**Comment by praseed44** [comment]
This is resolved after creating a network policy. Not an issue at Istio side.

**Comment by mark8s** [comment]
@praseed44 istio network policy ? can you give a rough outline？
