### ISSUE TITLE
istio-cni should hold pod(job) until istio-cni is ready

### ISSUE THREAD

**Issue by lizzzcai** [istio/istio#40008]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I know istio-cni can handle race condition [here](https://preliminary.istio.io/latest/docs/setup/additional-setup/cni/#race-condition-mitigation), however for job it will be failed unless user having retry logic. However, retry logic may need the job to be `idempotent`.

istio-cni should be ready first before any pod(job) with istio-proxy in a newly provisioned node, or pod(job) with istio-proxy should `hold` until istio-cni ready.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
we are using `istio-cni` and when we try to deploy a workflow (kind of like a job), and it is scheduled to a newly provisioned node, the pod from the workflow starts `earlier` than the istio-cni daemonset. In this case, the `istio-validation` sidecar return `connection refused` error and the workflow failed.

error:
```
2022-07-14T09:19:10.571793Z	info	in new validator: 100.96.78.4
2022-07-14T09:19:10.571856Z	info	Listening on 127.0.0.1:15001
2022-07-14T09:19:10.572042Z	info	Listening on 127.0.0.1:15006
2022-07-14T09:19:10.572160Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
2022-07-14T09:19:11.572446Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
2022-07-14T09:19:12.572625Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
2022-07-14T09:19:13.572818Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
2022-07-14T09:19:14.572998Z	error	Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
2022-07-14T09:19:15.572535Z	error	validation timeout
```

start time of the pod on the newly provisioned node:
```
➜  intprod git:(master) ✗ kubectl get po -A -owide | grep ip-10-250-6-203.eu-central-1.compute.internal
kube-system                 apiserver-proxy-97f6g                                             2/2     Running           0          2m32s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 calico-node-fx5sm                                                 1/1     Running           0          2m32s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 csi-driver-node-pbmjz                                             3/3     Running           0          2m32s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 egress-filter-applier-qnsp9                                       1/1     Running           0          2m33s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 istio-cni-node-4lbv5                                              1/1     Running           0          2m32s   100.96.78.3      ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 kube-proxy-nodes-basic-v1.21.14-h4bct                             2/2     Running           0          2m32s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 node-exporter-gjr52                                               1/1     Running           0          2m33s   10.250.6.203     ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
kube-system                 node-problem-detector-qnwwv                                       1/1     Running           0          2m33s   100.96.78.5      ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
promtail                    promtail-service-rnzdb                                            2/2     Running           0          66s     100.96.78.6      ip-10-250-6-203.eu-central-1.compute.internal     <none>           <none>
rg-49xxxxxxxxca        e502exxxxxxxx07606                                       0/3     Init:Error        0          3m49s   100.96.78.4      ip-10-250-6-203.eu-central-1.compute.internal     <none>
```

as you can see, the pod `e502exxxxxxxx07606` is running for `3m49s `while the istio-cni is `2m32s`, so it is started earlier than the istio-cni.

**Comment by howardjohn** [comment]
Kubernetes doesn't provide a mechanism to do this

**Comment by lizzzcai** [comment]
> Kubernetes doesn't provide a mechanism to do this

Hi @howardjohn , is there any workaround for this? or I have to add retry logic in the job? Thanks.

**Comment by zirain** [comment]
mark you pod not injected ?

**Comment by lizzzcai** [comment]
> mark you pod not injected ?

Hi @zirain , unfortunately we cannot disable the istio injection for the job. This issue mainly happens for job which has a very light-weighted image. By the way is it possible to exclude pod (job) by the label from istio-cni and use a standard way of `istio-init` for these kinds of special pods?

**Comment by ahmadsayed** [comment]
One more comment from my side on the same issue , we started to observe this directly after upgrading from 1.9 to 1.11, do you think it is related to this upgrade, is there any changes on istio-cni and istio-validation that might cause this.

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/40303, etc for more info.
