### ISSUE TITLE
default tag is assumed to exist

### ISSUE THREAD

**Issue by ostromart** [istio/istio#40018]
### Bug Description

https://github.com/istio/istio/blob/master/operator/cmd/mesh/install.go#L205-L215 requires default webhook to exist which should not be assumed.
This breaks downstream tests. It seems to be introduced in https://github.com/istio/istio/pull/39674.

### Version

```prose
master
```

**Comment by Monkeyanator** [comment]
Reverted the culprit PR in https://github.com/istio/istio/pull/40050 to be safe. I think the old behavior is WAI but will take another look
