### ISSUE TITLE
istio-proxy intercepts traffic for local pod (hairpin connection) traffic regardless of includeInboundPorts and includeOutboundIPRanges

### ISSUE THREAD

**Issue by paebersold** [istio/istio#40058]
### Bug Description

We are running prometheus and istio on k8s.  We have setup the integration between the two as per https://istio.io/latest/docs/ops/integrations/prometheus/ (option 2).  However for traffic from a prometheus pod to itself (ie prometheus monitoring itself) istio-proxy intercepts the traffic and drops it.  This means the usual service discovery scrape endpoint that is discovered can't be used.

* Pod annotations of include/exclude
    traffic.sidecar.istio.io/excludeInboundPorts: "15020"
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 169.254.169.254/32
    traffic.sidecar.istio.io/includeInboundPorts: ""
    traffic.sidecar.istio.io/includeOutboundIPRanges: ""

* Pod ip is 10.17.97.7

* Attempt to connect to 10.17.97.7 on port 9090 to query metrics
$ kubectl -n monitoring exec -it prometheus-k8s-0 -c prometheus /bin/sh

/prometheus $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if23: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9001 qdisc noqueue 
    link/ether 46:ef:f8:e5:3c:d0 brd ff:ff:ff:ff:ff:ff
    inet 10.17.97.7/32 scope global eth0
       valid_lft forever preferred_lft forever

/prometheus $ telnet 10.17.97.7 9090
Connected to 10.17.97.7
GET /metrics HTTP/1.0
Connection closed by foreign host

* istio-proxy logs

{"start_time":"2022-07-21T05:36:34.452Z","requested_server_name":null,"route_name":null,"authority":null,"upstream_service_time":null,"span_id":null,"response_code":0,"request_id":null,"response_flags":"NR","downstream_local_address":"10.17.97.7:15090","upstream_cluster":null,"duration":0,"downstream_remote_address":"10.17.97.7:36268","connection_termination_details":null,"path":null,"x_forwarded_for":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"bytes_received":0,"response_code_details":"filter_chain_not_found","referrer":null,"bytes_sent":0,"upstream_host":null,"method":null,"trace_id":null,"protocol":null,"user_agent":null}
{"bytes_received":0,"upstream_local_address":null,"route_name":null,"upstream_service_time":null,"user_agent":null,"connection_termination_details":null,"trace_id":null,"upstream_cluster":null,"response_code_details":"filter_chain_not_found","path":null,"method":null,"response_flags":"NR","bytes_sent":0,"authority":null,"upstream_transport_failure_reason":null,"request_id":null,"start_time":"2022-07-21T05:36:43.116Z","span_id":null,"downstream_remote_address":"10.17.97.7:42480","duration":0,"upstream_host":null,"referrer":null,"protocol":null,"x_forwarded_for":null,"requested_server_name":null,"downstream_local_address":"10.17.97.7:9090","response_code":0}
{"requested_server_name":null,"upstream_cluster":null,"protocol":null,"response_code":0,"upstream_local_address":null,"request_id":null,"authority":null,"upstream_service_time":null,"method":null,"upstream_host":null,"response_code_details":"filter_chain_not_found","route_name":null,"start_time":"2022-07-21T05:37:04.606Z","downstream_remote_address":"10.17.97.7:38102","path":null,"trace_id":null,"upstream_transport_failure_reason":null,"referrer":null,"bytes_received":0,"bytes_sent":0,"span_id":null,"user_agent":null,"downstream_local_address":"10.17.97.7:15090","duration":501,"response_flags":"NR","x_forwarded_for":null,"connection_termination_details":null}
{"downstream_local_address":"10.17.97.7:9090","requested_server_name":null,"response_code_details":"filter_chain_not_found","trace_id":null,"upstream_transport_failure_reason":null,"protocol":null,"bytes_received":0,"user_agent":null,"x_forwarded_for":null,"route_name":null,"downstream_remote_address":"10.17.97.7:43834","response_flags":"NR","connection_termination_details":null,"duration":3,"path":null,"response_code":0,"upstream_host":null,"upstream_service_time":null,"bytes_sent":0,"upstream_cluster":null,"method":null,"start_time":"2022-07-21T05:37:13.114Z","referrer":null,"request_id":null,"upstream_local_address":null,"authority":null,"span_id":null}

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (560 proxies)
$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.21.12-eks-a64ea69
```

**Comment by howardjohn** [comment]
Oof, nice find. we have some special rules for the hairpin so it must be applied before the opt-out
