### ISSUE TITLE
Every stats scraping will create big temporary bytes slices

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#40092]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When the size of envoy metrics is big,  every stats scraping will create a big temporary bytes slice. This puts pressure on the golang gc.
see `allocate_space` profiler graph:
![image](https://user-images.githubusercontent.com/5486149/180741118-fcd31e1b-e68a-454b-85cc-78a8d3c00bf6.png)
file: [profile (2).pb.gz](https://github.com/istio/istio/files/9179697/profile.2.pb.gz)

One alternative solution:
Using a global stats bytes buffer. And reseting buffer on beginning of the pilot-agent scrap requests.  If the size of metrics becomes smaller, we truncate the buffer on the end of scrap requests.   Protect global stats bytes buffer access by a mutex.

Pros:
    1.  Avoids frequent object creation.
Cons:
    1. No concurrent data access.
    2. Not release buffer if never be scraped.
    
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Do you have inuse profile?

**Comment by hzxuzhonghu** [comment]
we can make use of sync.Pool for this case

**Comment by Patrick0308** [comment]
`inuse_space` profile :
 ![image](https://user-images.githubusercontent.com/5486149/180763663-424fda3e-1d56-4dd0-92a6-9f9fc802eb24.png)

**Comment by Patrick0308** [comment]
> we can make use of sync.Pool for this case

@hzxuzhonghu  I tested sync.pool.  It's not so good. The buffer always be collected by the garbage when scraping metrics every 60s.

**Comment by Patrick0308** [comment]
> Cons:
> 1. No concurrent data access.
> 2. Not release buffer if never be scraped.

I think I can accept these two disadvantages. Because the metrics are regularly scraped always.

**Comment by Patrick0308** [comment]
use `io.Copy` maybe better.  Only when format is OpenMetrics, it will create temporary byte slice.
