### ISSUE TITLE
How to block Pod to Pod communication using Istio Service Mesh with in a namepsace

### ISSUE THREAD

**Issue by rameshar16** [istio/istio#40110]
Hi All,
I have a use case to block the traffic between the one APP A pod to APP B pod with in a namespace. Is this feature available in Istio? Please advise on this.

Thanks in advance...

Thanks and Regards,
Ramesh

**Comment by hobbytp** [comment]
Do you mean you want to block traffic from pod-a1 from APP A which includes pod-a1/a2/a3 to pod-b1 from APP B which includes pod-b1/b2/b3? 

If that is the case, I know one way but it is only for debug or trouble shooting instead of productive env. And if APP A or APP B is statefulset, the configuration will be simpler.

use "kubectl patch" to add different labels for these pods first (note: it will not restart pod), and then use VS, DR, and sourceLabels and subset to separate the traffic and weight ( from source label to dest label, the weight = 0). 
```bash
kubectl -n hobby patch pod productpage-v1-d474cb699-md92w --patch-file prod-k8s-patch-normal.yaml
kubectl -n hobby patch pod productpage-v1-d474cb699-m9pvf --patch-file prod-k8s-patch-debug.yaml
#----prod-k8s-patch-normal.yaml----
metadata:
  labels:
    app: productpage
    normal: normal
#---------------------------------
#----prod-k8s-patch-debug.yaml----
metadata:
  labels:
    app: productpage
    debug: debug
#--------------------------------- 
```

**Comment by zirain** [comment]
@rameshar16 is [authorization-policy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) what you want?

**Comment by rameshar16** [comment]
> @rameshar16 is [authorization-policy](https://istio.io/latest/docs/reference/config/security/authorization-policy/) what you want?

@zirain Yes, I am looking for similar policies but I do not see an option to block the ingress traffic of POD with Istio authorization policies.

**Comment by rameshar16** [comment]
> Do you mean you want to block traffic from pod-a1 from APP A which includes pod-a1/a2/a3 to pod-b1 from APP B which includes pod-b1/b2/b3?
> 
> If that is the case, I know one way but it is only for **debug or trouble shooting** instead of productive env. And if APP A or APP B is statefulset, the configuration will be simpler.
> 
> use "kubectl patch" to add different labels for these pods first (note: it will not restart pod), and then use VS, DR, and sourceLabels and subset to separate the traffic and weight ( from source label to dest label, the weight = 0).
> 
> ```shell
> kubectl -n hobby patch pod productpage-v1-d474cb699-md92w --patch-file prod-k8s-patch-normal.yaml
> kubectl -n hobby patch pod productpage-v1-d474cb699-m9pvf --patch-file prod-k8s-patch-debug.yaml
> #----prod-k8s-patch-normal.yaml----
> metadata:
>   labels:
>     app: productpage
>     normal: normal
> #---------------------------------
> #----prod-k8s-patch-debug.yaml----
> metadata:
>   labels:
>     app: productpage
>     debug: debug
> #--------------------------------- 
> ```

Hi @hobbytp , yes, we are looking for this solution for production deployment.

**Comment by aryan16** [comment]
I think it’s a proper usecase for istio authz policies, could you please elaborate more on how you can’t use existing authz policies?

**Comment by aryan16** [comment]
Sorry my bad I misunderstood the question, Normal authz won’t work in this scenario. Probably you need to add separate labels to the pods and then you can use authz on that.

**Comment by howardjohn** [comment]
^
