### ISSUE TITLE
Authorization header forwarding

### ISSUE THREAD

**Issue by vmasyagin** [istio/istio#40112]
Good afternoon. I tried to repeat the functionality of https://istio.io/latest/docs/tasks/security/authentication/jwt-route/. Everything works, but only if I disable authorization on the service. Tell me, please, is it possible to forward the Authorization header in a request for a specific service?

In the above example, the nttpbin api is not closed by authorization.

**Comment by aryan16** [comment]
IIUC you wanna do the claim based routing in the presence of auth and send the authz header back in response ??

**Comment by vmasyagin** [comment]
> IIUC you wanna do the claim based routing in the presence of authz policy and send the authz header back in response ??

Yes, at the level of the application itself, I also have restrictions on roles from the token. So yes, I need to save this token.

**Comment by aryan16** [comment]
Authz should work with claim based routing, could you please share you policies and VS spec ?

**Comment by aryan16** [comment]
and you can forward the token using by setting this in you ReqAuth Policy -`forwardOriginalToken`

**Comment by vmasyagin** [comment]
Sorry for the long reply, was unavailable. In this case, I have not yet used RequestAuthentication. Thanks a lot! I'll try using RequestAuthentication.

**Comment by vmasyagin** [comment]
Everything worked out. Thank you very much again! I think we can close the issue.
