### ISSUE TITLE
istio.io/istio/security/cmd/flexvolume/driver coverage dropped from 65 to 40 %

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#4013]
-istio.io/istio/security/cmd/flexvolume/driver:65 [67.6]
+istio.io/istio/security/cmd/flexvolume/driver:40 [42.7]

https://circleci.com/gh/istio/istio/41713#artifacts/containers/0

**Comment by wattli** [comment]
Thanks for opening this, i will fix

**Comment by wattli** [comment]
istio/security/cmd/flexvolume/driver is deprecating, will delete.

**Comment by incfly** [comment]
This has been deleted.
