### ISSUE TITLE
Metrics for circuit breaker outlier detection

### ISSUE THREAD

**Issue by reda-ayoub** [istio/istio#40143]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Expose metrics about the number of pods evicted when the circuit breaker is triggered using outlier detection. I see that there is already a metric exposed when the connectionPool option is used istio_requests_total{response_code="503", response_flags="UO"}

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by zirain** [comment]
can you share more details?

**Comment by Danial968** [comment]
Think this would be a good feature as well. Currently there isn't a metric that tells us when the circuit breaker for outlier detection trips.

Closest metric I can get is istio_requests_total{response_code="503", response_flag="UH"}. But that label "response_flag" with value "UH" is not unique to outlier detection being the cause of the issue.

I think what OP is requesting would be that the metrics for outlier detection will have the same metrics when the circuit breaker trips based on the connection pool, so it's response_flag is "UO" as well.

**Comment by Danial968** [comment]
So I was snooping around the istio-proxy prometheus metrics endpoint, /stats/prometheus. It already exposes the metric. 
`envoy_cluster_outlier_detection_ejections_enforced_total{cluster_name="outbound|8000||httpbin.qa.svc.cluster.local"} 1
`

Think this might be useful to monitor for the outlier detection.

My current Istio version was outdated, updating it to ver 1.15.0 made the metric available.

**Comment by reda-ayoub** [comment]
@Danial968 I just upgraded istio to 1.15.0 but I still don't see those metrics. Is there any special config that you used in order to enable the outlier detection?

**Comment by Danial968** [comment]
@reda-ayoub Don't think I used any special config, just did a fresh install in a test cluster. I checked the metric by port forwarding the istio-proxy's metric endpoint. http://localhost:15090/stats/prometheus
