### ISSUE TITLE
istio.io/istio/mixer/adapter/circonus coverage dropped from 68 to 63 %

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#4014]
https://circleci.com/gh/istio/istio/41713#artifacts/containers/0
- istio.io/istio/mixer/adapter/circonus:66 [68.9]		
+istio.io/istio/mixer/adapter/circonus:61 [63.9]

**Comment by sebastienvas** [comment]
I changed to use atomic mode. Maybe that s the issue ? It does not look like some test cases failed, which would be a valid reason.

Another issues is that the test is random and does not provide consistent code coverage.

**Comment by sebastienvas** [comment]
Also, codecov.io does not provide this level of customization for variable code coverage, that is why wew are using 2% less than actual coverage in the tool. We can close this for now, but we should look follow up the variability of this coverage.

**Comment by douglas-reid** [comment]
coverage appears vastly improved. closing.
