### ISSUE TITLE
istio-init always crashloops if restarted by restart-policy due to erros

### ISSUE THREAD

**Issue by ssuvasanth** [istio/istio#40169]
### Bug Description

istio-init crashloops on restart if a failure has occurred after iptables rules are applied ( completely or partially ).

This is because we try to reapply the same set of rules that may have succeeded before and we get 'table/chain already exists' kind of errors which causes the istio-init to crashloop.
This issue was noticed while working on https://github.com/istio/istio/issues/39963.

So, we intend to run `istio-clean-iptables` before applying any rules in istio-init to start from a consistent iptables state instead of applying over what was applied on the previous run which leads to istio-init crashloop. `(PR to follow)`

### Version

```prose
Istio version: 1.14.2

$ kubectl version --short
Client Version: v1.20.5
Server Version: v1.21.5

Tested on kubenetes 1.23 as well.
```

### Additional Information

~~This issue is not seen on istio versions till `1.11.x` but only on the later versions.
This can be explained because till `1.11.x` `ip -6 addr add` command was used to assign ipv6 IP to loopback interface and seems to have got moved to capture package later and started using netlink package.~~

**Comment by howardjohn** [comment]
Cleaning rules is not acceptable, it will result in traffic breakage/security vulnerability during the downtime. I think we will need another solution

**Comment by ssuvasanth** [comment]
Okay, will explore generating iptables-save and then comparing it with rules generated for iptables-restore and modifying before restoring.

But, isn't istio-init expected to run once and isn't it the first container to come up even before the application container in the pod. So, how would it affect the traffic when the application container has not started because init container failed? Please correct me if I am wrong.

Isn't the trade-off to clean iptables acceptable as istio-init container would always run before everything else and always alone in a pod when it runs? Looking forward to hearing further.

**Comment by howardjohn** [comment]
There are cases where its re-run mid lifecycle. VMs are a major one, but
there is a k8s "feature"/bug that reruns init-containers during the pod
lifecycle if the docker image is removed.

**Comment by ssuvasanth** [comment]
Got it. Thanks. 
I will explore other options.

**Comment by ssuvasanth** [comment]
Going to try the following approach:
1. Run iptables-save first to get the current state of the iptables
2. Perform a set minus (A-B) with 'A' being the istio-generated rules that need to be applied and 'B' being the current iptables state obtained by running iptables-save. ( Intention is to ignore the lines which are already applied)
3. Apply the resultant set of rules using iptables-restore

@howardjohn , please let me know if you have any thoughts on this approach.
