### ISSUE TITLE
Response_code= 0 and Response_flag= DC

### ISSUE THREAD

**Issue by deepishsh** [istio/istio#40207]
### Bug Description

I am using IKP and have hosted a API inside that .Request is coming from outside to ingress gateway then ingress gateway is sending the request to istio proxy and istio proxy routing it to service(api container) as per the istio architecture.

Now Service(api container) is routing the application to backend and processing is succesfull in backend.They sent back the sucess response with status code 200.and container logs also showing that he sent back the sucess 200 but the istio proxy logs havenot received 200 for that and they are receiving 

response_code=0
response_flag=DC

DC means downstream connection termination 
but why it is termination the connection in between - this issue is comming intermediately like after 5000 request it is coming sometime  after 5 days and so on.Please suggest the way forward in this 

### Version

```prose
istio version 17
```

**Comment by deepishsh** [comment]
So if we assume the application api container is closing the connection in between - but any way to debug under what condition it is closing the connection

As the cases where Response code 0 and response flag DC happen is the ideal time where in 10 seconds only 1 request came so no issue that much traffic in that time or the requests are overloded 

 and is there any retry we can do from container to the istio in case DC . We donot want to retry the request as it can send the duplicate transaction or in some case if the retry happen and the end user get timeout due to delay but the istio keep retrying the number of times and make the transaction sucessfull in api container but consumer get that it is timeout

**Comment by howardjohn** [comment]
Please upgrade if you want support from the community. Thanks! https://istio.io/latest/news/support/announcing-1.7-eol-final/
