### ISSUE TITLE
Http2 loadbalancing not working

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#40213]
### Bug Description

We have http2 traffic coming in through istio ingress gateway and getting routed to our service.

Initially we have 1 istio ingress gateway pod and everything is fine and when load increases the autoscaler scales up the ingress gateway pod to 2.
But even if the second pod comes up it doesn't take any http2 traffic from client and only the first one continues to take all http2 load.  Seems the http2 persistent connections are made between the first pod and all traffic is flowing there.

How can we make the request level load balancing happen here , rather than connection level which is happening today.

Our gateway

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: shared-istio-gateway
    meta.helm.sh/release-namespace: sps-ig2
  creationTimestamp: "2022-07-29T13:43:10Z"
  generation: 4
  labels:
    app.kubernetes.io/component: Ingress-Egress-and-LoadBalancers
    app.kubernetes.io/instance: shared-istio-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: shared-istio-gateway
    app.kubernetes.io/part-of: NCC
    app.kubernetes.io/version: 22.7.1-80
    chart: shared-istio-gateway-22.7.1-80
    heritage: Helm
    namespace: sps-ig2
    release: shared-istio-gateway
  name: shared-istio-gateway
  namespace: sps-ig2
  resourceVersion: "39314270"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/sps-ig2/gateways/shared-istio-gateway
  uid: bc755e11-3f47-4b2a-86a5-570f7f6e4c35
spec:
  selector:
    istio: istio-system
  servers:
  - hosts:
    - nc0231-tls.dyn.nesc.nokia.net
    port:
      name: http2-0
      number: 8082
      protocol: HTTP2
    tls:
      httpsRedirect: false  
```

Please note that we have a gateway object in different namespace binding to gateway pods in istio-system namespace.

virtual service is as follows

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: ig-chf-routing
    meta.helm.sh/release-namespace: sps-ig2
  creationTimestamp: "2022-07-29T13:41:07Z"
  generation: 2
  labels:
    app.kubernetes.io/component: Charging
    app.kubernetes.io/instance: ig-chf-routing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chf-routing
    app.kubernetes.io/part-of: NCC
    app.kubernetes.io/version: 22.7.1-80
  name: chf-routing-charging-vrs
  namespace: sps-ig2
  resourceVersion: "39368897"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/sps-ig2/virtualservices/chf-routing-charging-vrs                                                                  
  uid: ae718ef8-d416-48e8-bdcc-e51a418da433
spec:
  gateways:
  - shared-istio-gateway
  hosts:
  - nc0231-tls.dyn.nesc.nokia.net
  - nc0231-oam.dyn.nesc.nokia.net
  - nc0231-prov.dyn.nesc.nokia.net
  http:
  - match:
    - uri:
        prefix: /npcf-smpolicycontrol
    - uri:
        prefix: /nfmgmt
    - uri:
        prefix: /nchf-spendinglimitcontrol
    - uri:
        prefix: /nchf-convergedcharging
    - uri:
        prefix: /npcf-am-policy-control
    - uri:
        prefix: /npcf-ue-policy-control
    - uri:
        prefix: /rest-services
    - uri:
        prefix: /nchf-proxy-request
    route:
    - destination:
        host: ig-charging-service
        port:
          number: 8081
```

### Version

```prose
istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (12 proxies

 kubectl version --short
Client Version: v1.21.10
Server Version: v1.21.10
```

**Comment by howardjohn** [comment]
The client determines load balancing. If you want clients (outside the mesh) to balance load to your ingressgateways, you either need to make them smarter, put an intermediate layer, or have a mechanism to tell the clients to close the connection and retry.

**Comment by arunpmohan** [comment]
Thanks @howardjohn . So for http2 traffic do you mean that the client has to some how stop and reconnect when autoscaling of ingress gateway pods happen ?

**Comment by howardjohn** [comment]
Ingress gateway will load balance between ingrss gw and your workload. It sounds like you want to load. balance between client and ingress gw.

fundamentally the client must be the thing providing load balancing. So you can insert middle boxes that add load balancing for lower layers but at some point you will still have uneven load if the client doesn't do it.

**Comment by arunpmohan** [comment]
ok make sense. For http1 client is making separate connections and hence autoscaled ingress pods do get the new request automatically without any special load balancing in front of ingress gw, but i guess for http2 this wont work then as connections are persistent.

**Comment by arunpmohan** [comment]
What happens if we use http2 streaming ? Will ingress gw still balance http2 streamed connections to new pods which scale up ?

**Comment by howardjohn** [comment]
No, streams are stateful. That is impossible for a proxy to do.

**Comment by hzxuzhonghu** [comment]
We can close it as http2 uses long running connections
