### ISSUE TITLE
Client-specific TrafficPolicy configuration support

### ISSUE THREAD

**Issue by masquee** [istio/istio#40219]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

`TrafficPolicy` can currently be configured in the `DestinationRule` and will **take effect for all client sidecar**. If some clients need to adjust the `TrafficPolicy` settings, such as `ConnectionPoolSettings`, how to support this feature?

There is a scenario where, for example, the default `http1MaxPendingRequests` is configured in the `DestinationRule` via `ConnectionPoolSettings`, and **this default value is appropriate for most clients. But a small number of clients can tolerate more requests pending.**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
If you put the same DR in the client namespace, it should take precedence. or you can also use workloadSelector to scope further (only in newer Istioversion)

**Comment by masquee** [comment]
> 

Thanks, I'll try it.

**Comment by masquee** [comment]
> If you put the same DR in the client namespace, it should take precedence. or you can also use workloadSelector to scope further (only in newer Istioversion)

Thanks, I'll try it.
