### ISSUE TITLE
The parameter of additionalContainers for gateways is always defined after container of istio-proxy

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#40239]
### Bug Description

The installation templates of In/Egress gateway under the directory of `manifests/charts/gateways` has a parameter named `additionalContainers` which is used for user to add additional container with In/Egress gateway.
However,  `additionalContainers` can only be added after `istio-proxy`. And the problem is that the user may want to add additional container before or after `istio-proxy`.

So the solution may be that splitting `additionalContainers` into `preAdditionalContainers` and `postAdditionalContainers`, and the changes, such as in `manifests/charts/gateways/istio-ingress/templates/deployment.yaml` will look like below:

```
......
      containers:
{{- if $gateway.preAdditionalContainers }}
{{ toYaml $gateway.preAdditionalContainers | indent 8 }}
{{- end }} 
        - name: istio-proxy
......
{{- if $gateway.postAdditionalContainers }}
{{ toYaml $gateway.postAdditionalContainers | indent 8 }}
{{- end }} 
......
```

### Version

```prose
$ istioctl version
client version: 1.14
control plane version: 1.14
data plane version: 1.14
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.21.1
```

### Additional Information

None

**Comment by howardjohn** [comment]
Curious, why do you care about container order? 99% of the time it doesn't actually matter

**Comment by irisdingbj** [comment]
In some cases, postStart hook is used in the first container within the pod.  In this case, container sequence in pod spec matters.

**Comment by howardjohn** [comment]
Strongly recommend https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/, this is too obscure of a use cases to introduce complexity

**Comment by zhlsunshine** [comment]
Hi @howardjohn, thanks for your recommendation above, I have read it and this blog can tell me how to add properties for the helm template, but we need to update the `containers` section of the helm template and make sure that the `additionalContainers` can not always be after the `istio-proxy`. Moreover, this method only support installing the Istio via helm, and it does not work for user who want to install via istioctl.

Another reason for this change is that if it supports parameter of `additionalContainers`, these additional containers may be pre or post of `istio-proxy`. And I also will change Egressgateway as well.

**Comment by zhlsunshine** [comment]
Hi @howardjohn, I understand your concern about this change may block the user, so how about change it like this:

```
......
      containers:
{{- if $gateway.preAdditionalContainers }}
{{ toYaml $gateway.preAdditionalContainers | indent 8 }}
{{- end }} 
        - name: istio-proxy
......
{{- if $gateway.additionalContainers }}
{{ toYaml $gateway.additionalContainers | indent 8 }}
{{- end }} 
......
```
Let's keep the `additionalContainers` as before and add a new parameter `preAdditionalContainers` for it. Then there will be no block for user. Does it make sense?

**Comment by howardjohn** [comment]
`istioctl` already has another method: https://istio.io/latest/docs/setup/additional-setup/customize-installation/#advanced-install-customization.

The environments working group has already agreed that we are not going to make changes like this to the helm chart. It doesn't matter that one person has a valid use case for adding new settings --- we get an issue like this 2-3 times per week. if we said "yes" to all of them, soon the helm chart would be 2000 lines long.

The right way to do this is following the docs above. We will not accept any changes like this to the helm chart.

**Comment by zhlsunshine** [comment]
okay, thanks @howardjohn for your reply, I will have a try for the method you mentioned above.
