### ISSUE TITLE
EgressRules are namespaced, but applied globally

### ISSUE THREAD

**Issue by terinjokes** [istio/istio#4026]
EgressRules are created in specific namespaces, rather than being namespace-less resources, but they currently apply globally. This is confusing to users who believe these rules are scoped to their namespace.

For example, one team creating an EgressRule. Other teams end up, unknowingly, using that egress, but don't notice because things seem to be working. If that first team decides they no longer need that rule, and they delete it, every other team is now unable to communicate to that external system.

Istio version: 0.5.1

**Comment by terinjokes** [comment]
Assuming per-namespace behavior is desirable, it looks like this can be added to Pilot with a little bit of work:

1. Expand node.Proxy to store the namespace (parse it from the Domain field, if neccessary)
1. Modify Pilot's `buildEgressTCPListeners` and `buildEgressHTTPRoutes` to skip over EgressRules not defined in the service's namespace.
1. The rest of xDS continues operating without knowing EgressRules were skipped.

**Comment by terinjokes** [comment]
I gave implementing this a shot as described above, filtering out egress rules from other namespaces before passing the config slice to the conflict rejection and it seems to work.

If this is a direction your interested in, I'm happy to start working towards upstreaming.

**Comment by terinjokes** [comment]
It looks like EgressRules are being phased out, and replaced with ExternalService + DestinationRule, which look to exhibit these same problems.

**Comment by andraxylia** [comment]
@rshriram can you please comment?

**Comment by rshriram** [comment]
Service entries do not respect namespaces. Google.com is visible everywhere. Whether it’s accessible from a pod is a question of policy. By confining service entries to namespaces, you get into the problem of defining some default global namespace applicable everywhere, as well as resolving conflicts when same service entry is present in both namespaces but with different settings, etc.

**Comment by rshriram** [comment]
I suggest using istio RBAC or mixer policies to restrict the namespaces that are allowed to talk to a service entry.

**Comment by ymesika** [comment]
Should we update validation to deny `ServiceEntry` with non-default namespace?

**Comment by terinjokes** [comment]
If these apply across namespaces, why are the CRDs defined to be namespace scoped instead of cluster scoped.

**Comment by andraxylia** [comment]
k8s require any resource to be created in a namespace. CRD is like any type of k8s resource. The meaning and application for that resource is not enforced.

**Comment by terinjokes** [comment]
@andraxylia Resources can be cluster-scoped or namespace-scoped. EgressRules and the replacement networking APIs are namespace-scoped despite taking effect globally.

This leads users (like me as the OP here) assuming this is a bug in Istio, and these resources are supposed to only effect single namespaces, just like any other type of K8S resource.

@rshriram This might be true now, with the newer APIs and resources, but EgressRules were the sole way at the time this ticket was created. I expected, since they were namespace-scoped, to work similarly to Kubernetes's NetworkPolicies, only allowing egress to where EgressRules were defined in that namespace.

@kyessenov Thanks. I'm glad it's on the radar to fix.

**Comment by andraxylia** [comment]
@terinjokes you are right, thanks for correcting me. There is a "scope" field which can be set to Namespaced or Cluster. I did a quick search and all of our CRDs are Namespaced. This issue makes sense, we should change the scope to all APIs that we mean to be cluster scope.

**Comment by sbgreene1307** [comment]
Restricting an Egress (or later an ExternalService) to apply only to traffic out of a specific namespace makes sense in the use case where I have namespaces for my different environments (prod, stage, e2e, sandbox, etc). I don't want the pods in my e2e namespace to have any access at all to the external services backing my prod namespace. The different namespaces run against different environments of my third party dependencies. 

It seems from the comments that istio won't implement the namespace restriction on egresses, so do I have to do this thru RBAC?
