### ISSUE TITLE
Rewrite URL in Envoy rate limit.

### ISSUE THREAD

**Issue by thaida2110** [istio/istio#40264]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I want to show custom message instead of 429 Too many requet error.
**Describe alternatives you've considered**
Can we redirect to other page? 
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
IIRC, what's you want is not supported by neither [local_rate_limit](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter) or [global_rate_limit](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter), current envoy only support `request_headers_to_add_when_not_enforced` or `response_headers_to_add` in [local_rate_limit](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#extensions-filters-http-local-ratelimit-v3-localratelimit).

**Comment by thaida2110** [comment]
Hi Zirain,

Thanks for your comment.
