### ISSUE TITLE
Istio config to support global scope

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4027]
CRD-based implementation can provide only namespace scope (with proper ACL). We need a way to define config at a broader scope (cluster and/or mesh)

**Comment by diemtvu** [comment]
Bring this up again as we need it for https://github.com/istio/istio/issues/4861, and for authZ policy.

A solution for now is using a special namespace (e.g `istio-system`, though configurable via command line flag). Configs in that namespace can use full qualified domain name (FQDN), so can affect services on all other namespaces.

**Comment by diemtvu** [comment]
Should we go ahead and use `istio-global` namespace to hold *global* policies/configs (and advice customers to not run jobs in that namespace to avoid misuses).

Also, should we enforce this on similar policy, like destination rule (i.e destination rule for host "*" in namespace `foo` is for all services in `foo` only, but in namespace `istio-global` is for all services).

/cc @geeknoid 
/cc @louiscryan

**Comment by ayj** [comment]
Authentication specific tracking issue - https://github.com/istio/istio/pull/6159

**Comment by ozevren** [comment]
@liminw @diemtvu the verbiage on this issue indicates this as a general istio-wide problem, whereas the issue is assigned to you folks. 

What is the concrete deliverable here? Are you planning to switch to global-scoped CRDs for security related configuration?

**Comment by ozevren** [comment]
If the scope is only for security related CRDs, then we should update the title.

**Comment by diemtvu** [comment]
https://github.com/istio/istio/pull/6159 attempt to add new CRD kind specifically for authn policy.

On the other hand, I hope framework can do something more consistent across all other configs type. For example, it can create twin CRDs, one in namespace scoped and one in cluster scoped so we don't have to do so case by case. Being said that, not every configs need 'global' config concept, so I'm ok with close this one for now.
