### ISSUE TITLE
istiod only deal with the stable namespace istio crd，such as istio-system

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#40316]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

istiod supports crd strategies such as vs, dr, gateway, se, etc. that only process the specified namespace, similar to the function of `meshConfig.discoverySelectors`.

for `meshConfig.discoverySelectors`.

```
**Added** Specify `meshConfig.discoverySelectors` to dynamically restrict the set of namespaces for Services, Pods, and Endpoints that istiod processes when pushing xDS updates to improve performance on the data plane.
```
istiod deal with the istio crd for namespace AAA if we want to it only watch namespace AAA istio crd.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Previous issues

https://github.com/istio/istio/issues/36627

https://github.com/istio/istio/issues/35092

**Comment by tanjunchen** [comment]
https://discuss.istio.io/t/istiod-only-listens-to-the-specified-namespace-istio-crd/13595   for   discuss.istio.io

**Comment by irisdingbj** [comment]
https://istio.io/latest/docs/reference/config/networking/sidecar/  
https://istio.io/latest/docs/ops/best-practices/traffic-management/#cross-namespace-configuration

Try to above to see whether this solves your issue.

**Comment by irisdingbj** [comment]
@kfaseela This is another request from community for multiple istiod in one cluster.

**Comment by tanjunchen** [comment]
According to the https://istio.io/latest/docs/setup/install/external-controlplane/ installation documentation, we are able to deploy istiod in an external k8s cluster, which is suitable for hosting the control plane in an external k8s cluster.
However, the above external control plane cannot handle the following scenarios:
1、In a k8s cluster, the external control plane does not support istiod hosting multiple users such as user A, user B, and user C at the same time.
2、In a k8s cluster, istiod in external-istiod-A and external-istiod-B cannot handle the same CRD of user cluster A and user cluster B. 

<img width="683" alt="image" src="https://user-images.githubusercontent.com/19339970/185756165-9c85a098-79c5-4194-8b62-168c5fefea4f.png">


scenario：
1、In a multi-tenant scenario, istiod of multiple users is deployed in a k8s, and the istio crd between users cannot affect each other.
2、In a large k8s cluster(1000node+), user A uses test-A-dev as the development env and test-A-test as the test env, But user B uses test-B-dev as the development denv and test-B-test as the test env. user A only wants to watch the crd in the test-A-dev and test-A-test namespaces, while user B only wants to watch the crd in the test-B-dev and test-B-test namespaces. istiod is not supported now. Does the istio community support istiod only listening to the crd under the specified namespace? 
3、istiod supports the specified namespace, and then combined with the external control plane, it can achieve istiod multi-tenancy. As follows:
![image](https://user-images.githubusercontent.com/19339970/185756286-52e121b5-6aab-4d45-93c3-7dcc824b794b.png)

**Comment by frankbu** [comment]
IIUC, this and the several other issues that are referenced in the comments would all be satisfied by a simple mechanism to support multi-tenancy within a cluster. Istio already has several mechanisms (revisions, sidecars, authorization, discoverySelectors) that can be used, in combination, to scope multiple Istio tenants in a cluster, but it seems like a complicated way to achieve a pretty simple requirement.

Wouldn't it make sense to just introduce a proper tenant concept for this? For example, `mesh.tenantSelector` which istiod uses as a top-level filtering mechanism for finding the subset of namespaces it's managing?

btw, this would also fix [the messy problem](https://github.com/istio/istio/issues/37674#issuecomment-1064343398) with current default webhook management (cc @Monkeyanator).

**Comment by kfaseela** [comment]
> IIUC, this and the several other issues that are referenced in the comments would all be satisfied by a simple mechanism to support multi-tenancy within a cluster. Istio already has several mechanisms (revisions, sidecars, authorization, discoverySelectors) that can be used, in combination, to scope multiple Istio tenants in a cluster, but it seems like a complicated way to achieve a pretty simple requirement.
> 
> Wouldn't it make sense to just introduce a proper tenant concept for this? For example, `mesh.tenantSelector` which istiod uses as a top-level filtering mechanism for finding the subset of namespaces it's managing?
> 
> btw, this would also fix [the messy problem](https://github.com/istio/istio/issues/37674#issuecomment-1064343398) with current default webhook management (cc @Monkeyanator).

I have tried to put together somewhat similar proposal in an RFC here, hoping to discuss in WG meeting sometime soon: https://docs.google.com/document/d/1y4liRJbQW0NCMeQtqMma46flVqs-izV1/edit?usp=sharing&ouid=105743966233121608166&rtpof=true&sd=true

**Comment by kfaseela** [comment]
@tanjunchen : https://github.com/istio/istio/pull/36639 has been merged. You can close this issue, if this PR solves your requirement.

**Comment by tanjunchen** [comment]
@kfaseela  Is there a image to test? I can go test it.I will close this if it solves my requirement。
