### ISSUE TITLE
How to get real ip when accessing the service by NodePort

### ISSUE THREAD

**Issue by 362475097** [istio/istio#40317]
I deploy Traefik in istio. Traefik has injected envoy. Traefik is exposed by NodePort and externalTrafficPolicy is Local.

When I accessing the service by Traefik, get client ip is ‘127.0.0.6’. It seems that the request is intercepted by envoy before reach the Traefik, and envory forward  request to Traefik by using it's local ip '127.0.0.6'. So Traefik  get real ip is '127.0.0.6'.

My question is how to get real clien ip when using Traefik  in istio?

**Comment by stevenkitter** [comment]
anybody can solve this problem??

**Comment by hzxuzhonghu** [comment]
ptal https://events.istio.io/istiocon-2021/slides/b6p-PreserveOriginalAddress-ZhonghuXu.pdf
