### ISSUE TITLE
Pull access denied, authorization failed When trying to apply istio-ingressgateway

### ISSUE THREAD

**Issue by Winston-DucPham** [istio/istio#40355]
I run 
kubectl apply -n ingress-gateway \
  -f samples/gateways/istio-ingressgateway
and got the result: "Failed to pull image "auto": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/auto:latest": failed to resolve reference "docker.io/library/auto:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed"

Is anyone know how to fix this ?

**Comment by zirain** [comment]
what are you trying to do? which doc you are following? what's the istio version you?

**Comment by Winston-DucPham** [comment]
I'm following this doc https://cloud.google.com/service-mesh/docs/downloading-istioctl. using the version istio-1.14.1-asm.3-linux-amd64. I'm trying to create an ingress gateway in my kubenets cluster

**Comment by ericvn** [comment]
The docs you are using is for Anthos Service Mesh which is a product built on Istio. You would need to ask Google about this issue as it's not an issue in the base Istio open source.

**Comment by howardjohn** [comment]
The issue is caused by not having injection enabled though fwiw. But agree with ^
