### ISSUE TITLE
VirtualService timeout is 10s,but P9999  latency is very large.

### ISSUE THREAD

**Issue by 17733101396** [istio/istio#40356]
### Bug Description

![image](https://user-images.githubusercontent.com/40567659/183582755-71321fc1-7ea5-4c16-a0a8-9bc05919bf60.png)

istio-ingressgateway  log :

log_response_flags:DC
status:0
request_length:0
upstream_response_time:null
version:HTTP/1.1
request_time:902796

### Version

```prose
$ istioctl version
1.12.4
$ kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.20.11-aliyun.1
$ helm version --short
v3.6.1+g61d8e8c
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by 17733101396** [comment]
modify Affected product area

**Comment by masquee** [comment]
How is your histogram bucket configured?
