### ISSUE TITLE
Istio Goes down if Cluster Loses Single node

### ISSUE THREAD

**Issue by michaelschem** [istio/istio#40365]
### Bug Description

I'm a bit new to Istio so I may have setup my cluster incorrectly, but we have a cluster that loses worker nodes every so often (we are moving away from this service provider for this reason), but I'd still like to harden Istio from going down when we a kube node.  The problem seems to be that if the node dies that Istio has created the ingress gateway on, the services goes down until that node comes back up.  Is there a way to scale the ingress gateway and give an affinity so it doesn't get scheduled on the same node, that way if we lose a kube worker node, we don't lose all our services on that gateway.  I've also thought about adding two gateways, but then they'd have different IPs and I'd have to deal with that upstream (not the end of the world I guess), but was hoping Istio had a solution to this.

### Version

```prose
$ istio-1.13.1/bin/istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (24 proxies)
$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.23.8
```

**Comment by zirain** [comment]
you may need this https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

**Comment by Minh-Ng** [comment]
Istio ingressgateways are just pods. You can scale replicas/use HPA and add affinity/tolerations as needed

**Comment by michaelschem** [comment]
ok, so I tried that with the following:

```
hpaSpec:
  minReplicas: 2
```

but if I unplug any of my cluster's worker nodes, the services is still unavailable.

Is this because of the istiod perhaps? Can I scale that?
