### ISSUE TITLE
Memory leak in case of errors during tls connection

### ISSUE THREAD

**Issue by kinash000** [istio/istio#40381]
### Bug Description

app -> sidecar -> egress-gw -> kafka

Egress gateway works in TLS termination mode using DestinationRule (https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/):
[destinationrule-egress-kafka-dr.txt](https://github.com/istio/istio/files/9299343/destinationrule-egress-kafka-dr.txt)

For example, if the kafka server is unavailable and ssl connections fail, sidecar will increase the number of open connections and there will be a memory leak.

Number of connections based on sidecar envoy statistics:
reporter=.=source;.;source_workload=.=workload;.;source_workload_namespace=.=namespace;.;source_principal=.=unknown;.;source_app=.=workload;.;source_version=.=tag-3075;.;source_canonical_service=.=workload;.;source_canonical_revision=.=tag-3075;.;destination_workload=.=unknown;.;destination_workload_namespace=.=unknown;.;destination_principal=.=unknown;.;destination_app=.=unknown;.;destination_version=.=unknown;.;destination_service=.=egress-svc.namespace.svc.cluster.local;.;destination_service_name=.=egress-svc.namespace.svc.cluster.local;.;destination_service_namespace=.=unknown;.;destination_canonical_service=.=unknown;.;destination_canonical_revision=.=latest;.;request_protocol=.=tcp;.;response_flags=.=-;.;connection_security_policy=.=unknown;.;_istio_tcp_connections_**closed**_total: **4**

reporter=.=source;.;source_workload=.=workload;.;source_workload_namespace=.=namespace;.;source_principal=.=unknown;.;source_app=.=workload;.;source_version=.=tag-3075;.;source_canonical_service=.=workload;.;source_canonical_revision=.=tag-3075;.;destination_workload=.=unknown;.;destination_workload_namespace=.=unknown;.;destination_principal=.=unknown;.;destination_app=.=unknown;.;destination_version=.=unknown;.;destination_service=.=egress-svc.namespace.svc.cluster.local;.;destination_service_name=.=egress-svc.namespace.svc.cluster.local;.;destination_service_namespace=.=unknown;.;destination_canonical_service=.=unknown;.;destination_canonical_revision=.=latest;.;request_protocol=.=tcp;.;response_flags=.=-;.;connection_security_policy=.=unknown;.;_istio_tcp_connections_**opened**_total: **8099**

sidecar memory utilization:
<img width="1143" alt="Снимок экрана 2022-08-10 в 13 06 50" src="https://user-images.githubusercontent.com/22095634/183884472-b66808b6-35a1-4928-9128-70c55e0fb83d.png">

Trying to set the idle timeout does not help.

### Version

```prose
Istio 1.6.14
```

**Comment by kyessenov** [comment]
there's a memory leak in ORIGINAL_DST implementation. is this the same issue?

**Comment by howardjohn** [comment]
> Istio 1.6.14

https://istio.io/latest/news/support/announcing-1.6-eol/. 2 years end of life, please upgrade and re-open if its still happening.
