### ISSUE TITLE
validationMessages level return wrong

### ISSUE THREAD

**Issue by Encounter77** [istio/istio#40380]
### Bug Description

i use `kubectl get vs xxx -n xxx -o json`, find `level` return `3`, is different from the official description.

```
"status": {
	"validationMessages": [
		{
			"documentation_url": "https://istio.io/v1.11/docs/reference/config/analysis/ist0101/?ref=status-controller",
			"level": 3,
			"type": {
				"code": "IST0101"
			}
		},
		{
			"documentation_url": "https://istio.io/v1.11/docs/reference/config/analysis/ist0101/?ref=status-controller",
			"level": 3,
			"type": {
				"code": "IST0101"
			}
		}
	]
}
```
**why level field is integer?**

### Version

```prose
kubernates version: 1.18.10
istio version: 1.11.8
```

### Additional Information

reference
- https://istio.io/latest/docs/ops/diagnostic-tools/istioctl-analyze/#enabling-validation-messages-for-resource-status
- https://istio.io/latest/docs/reference/config/istio.analysis.v1alpha1/#AnalysisMessageBase-Level

**Comment by howardjohn** [comment]
Does it occur on newer versions? I recall fixing similar
