### ISSUE TITLE
customize fsGroup in injected sidecar

### ISSUE THREAD

**Issue by tareqhs** [istio/istio#40395]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Allow setting fsGroup injected init container and sidecar. Currently the user 1337:1337 is hardcoded in the template. It also overrides the pod-level securityContext fsGroup.

**Describe alternatives you've considered**
Duplicate the whole sidecar template into the `IstioOperator` spec, modify the hardcoded user and group IDs, and use the duplicate template instead of the built-in one via `defaultTemplates` config. This is very bad as it required syncing the duplicate template everytime we upgrade even the patch version of istio. Also this is ugly as our custom values are bloated with ~500 lines of configuration, unnecessarily.

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
We have many deployment with specially configured `securityContext` that contains `runAsUser` and `runAsGroup` values different from istio's 1337. The difference in user and group ID trigger's the built-in modification of ownership and permissions on the whole file system tree inside the mounted volumes. this causes two issues:
1. very long delays and I/O overhead during pod startup (large file system)
2. some tools break due to strict rules and file permissions

the only solution to avoid this behavior in kubernetes is to set `fsGroupChangePolicy: OnRootMismatch`, but istio's different user ID cause this to not work and still modify the whole file system.
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
Note: we can't use istio's user ID of 1337 in our security context.

**Comment by howardjohn** [comment]
On k8s 1.22+ we don't inject this at all. Re you on an older version or have somehow disabled this?

**Comment by tareqhs** [comment]
hi @howardjohn,
in my k8s 1.22 cluster the fsGroup in pod-level securityContext is injected. the webhook even overrides fsGroup if it exists in the original pod spec.
i got it work by setting the env var `ENABLE_LEGACY_FSGROUP_INJECTION` in istiod to `false` explicitly.

since i am pretty sure user ID and group ID compatibility are important for other scenarios in istio, i'm thinking this feature is still needed. do you agree?

**Comment by howardjohn** [comment]
fsGroup injection is only for legacy k8s versions. Running the container
with uid/gid != fsGroup at pod level.

**Comment by artem-nefedov** [comment]
`fsGroup: 1337` is still being injected on EKS 1.22 (currently latest on AWS) with Istio 1.14.3, unless we explicitly specify `ENABLE_LEGACY_FSGROUP_INJECTION=false`

**Comment by howardjohn** [comment]
It depends on the install mechanism; not all of them auto detect. Currently
jsut `istioctl install`. https://github.com/istio/istio/pull/40549 adds
support for `helm install`

**Comment by artem-nefedov** [comment]
@howardjohn In our case, it's installed by istio-operator. Is that not the same as `istioctl install`?

**Comment by howardjohn** [comment]
That should do it, but possibly there are bugs

**Comment by kfaseela** [comment]
> `fsGroup: 1337` is still being injected on EKS 1.22 (currently latest on AWS) with Istio 1.14.3, unless we explicitly specify `ENABLE_LEGACY_FSGROUP_INJECTION=false`.
> 
> Would be great if someone could comment if this is a bug, or if it actually needs to be injected there for some reason.

Hello @artem-nefedov : The default value of ENABLE_LEGACY_FSGROUP_INJECTION is true until 1.14. See https://istio.io/latest/docs/reference/commands/pilot-discovery/ environment variables section. An attempt to change the default value to false is in progress. See https://github.com/istio/istio/pull/40531 . There are some more issues yet to be fixed, once done we will try to make it available on 1.15. Until then you will have to explicitly set the env variable to false.
