### ISSUE TITLE
flake: TestStackdriverRbacTCPDryRun/NoAlpn

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#40407]
### Bug Description

Asan test flake:
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_proxy/4005/test-asan_proxy/1557480910071271424/build-log.txt

### Version

```prose
latest
```

**Comment by kyessenov** [comment]
cc @douglas-reid if you have time to digest the test logs

**Comment by howardjohn** [comment]
This is removed
