### ISSUE TITLE
HTTP2 \ gRPC metrics

### ISSUE THREAD

**Issue by alkarp** [istio/istio#40408]
### Bug Description

I've been looking for any HTTP2 \ gRPC specific metrics exposed by the istio ingress gateway and istio-proxy sidecars, wasn't able find any:
- the `envoy_cluster_http2_*` doesn't seem to reflect current state: `envoy_cluster_http2_streams_active` always shows 1 while there are certainly more active streams, `envoy_cluster_http2_pending_send_bytes` and `envoy_cluster_http2_outbound_flood` while I'm getting logs for "response_code_details":"http2.outbound_frames_flood" events;
- the `istio_request_messages_total` and `istio_response_messages_total` are not exposed on the metrics endpoint at all (while tons of other HTTP metrics are exposed as expected);

Is this a bug or there there is any additional undocumented configuration required on the istio \ envoy part to get subject exposed?

### Version

```prose
$ istioctl version
client version: 1.11.3
control plane version: 1.13.5
data plane version: 1.13.5 (12 proxies)
$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.22.11
```

**Comment by howardjohn** [comment]
There are no http2 specific metrics, just the standard HTTP ones - istio_requests_total, etc

**Comment by a-candiotti-pvotal** [comment]
I have the same pb as @alkarp, I have grpc traffic initiated by a service in a cluster and going through an egress gateway to a service outside of it, everything is working is fine but I never see the metrics "istio_response_messages_total" appear.

At first I thought about the sampling rate but generating a lot of traffic does not change anything.
