### ISSUE TITLE
ratelimit - Deployment Strategy Type - Recreate to RollingUpdate

### ISSUE THREAD

**Issue by zohebs341** [istio/istio#40422]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

I've followed official documentation to implement the rate limit. 
URL: https://github.com/istio/istio/blob/release-1.14/samples/ratelimit/rate-limit-service.yaml

Feature request: Change deployment strategy from "Recreate" to "RollingUpdate".

**Describe the feature request**

For rate-limit deployment, the strategy being used is "Recreate". If we can use "RollingUpdate", we can achieve things without downtime. As whenever we modify ratelimit configmap, we have to restart pods. If the deployment strategy is "RollingUpdate" then we don't need downtime approvals, justifications etc. We can easily go with rollout restart.

Considering Banking and Financial sectors, we cannot delete pods or it's difficult to get approvals for pod deletion/downtime even for min/secs. If we can change strategy to "RollingUpdate" as requested above, then no worries on approvals and it will be seemless.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
that's an example, we use that for e2e test.

**Comment by zohebs341** [comment]
@zirain Thanks for your response.

As a user, I can change it to "RollingUpdate" right? Even from Kubernetes point of view, RollingUpdate can help us.

**Comment by howardjohn** [comment]
Its just a sample, you can do whatever you want to it. Their is no expectation samples/ is for production.

**Comment by zohebs341** [comment]
@zirain @howardjohn Thanks for your confirmation.
