### ISSUE TITLE
Disable leader election

### ISSUE THREAD

**Issue by fanminshi** [istio/istio#40427]
**Describe the feature request**

I am working on running k8s on edge device. One of the goal is to reduce writes to etcd as much as I can. In return, this will also reduce disk write. I noticed that the following PUT are going into etcd.

(Captured over 8 minutes)
```
73 /registry/configmaps/app-ingress/istio-namespace-controller-election
73 /registry/configmaps/app-ingress/istio-leader
73 /registry/configmaps/app-ingress/istio-gateway-status-leader
73 /registry/configmaps/app-ingress/istio-gateway-deployment-leader 
```

I would like to disable those leader election leases writes in istio. Currently, it seems like those parameter are hard coded.

https://github.com/istio/istio/blob/53eef240ecb2c81eca120db55ba14dbe14718b75/pilot/pkg/leaderelection/leaderelection.go#L207

I would like to add a feature flag to disable the leader election.

**Describe alternatives you've considered**

Instead of disable the leader election. We can also make the leader-election parameters tunable. However, this seems more work than just to disable leader election for my use-case

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Do you want to disable leader election or customize interval?

If it is disable leader election, there can be a race when multiple istiod running

**Comment by fanminshi** [comment]
I want to disable the leader election. 

`If it is disable leader election, there can be a race when multiple istiod running`
does istiod need to be run on all nodes? And what's the race condition?

kube-scheduler has this feature.
```
--leader-elect     Default: true
--
  | Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
```

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler

**Comment by hzxuzhonghu** [comment]
IIRC, kubescheduler has this option to allow disable leader election when one instance run

**Comment by fanminshi** [comment]
`IIRC, kubescheduler has this option to allow disable leader election when one instance run`
if I have a multi-node setup, does istiod need to run on all nodes? I know I can still run one stance of kubescheduler in mulit-node setup if i don't care about HA.

**Comment by hzxuzhonghu** [comment]
Istiod does not need to run on all nodes.  I think we can provide such option.

**Comment by fanminshi** [comment]
@hzxuzhonghu sounds good. I can put a PR for this since this should be a quite simple change.

**Comment by hzxuzhonghu** [comment]
Awesome, thank you

**Comment by fanminshi** [comment]
@hzxuzhonghu I am digging into the code. is this the place that i need to disable the leader-election? https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L259

**Comment by hzxuzhonghu** [comment]
Also in pilot/pkg/bootstrap/configcontroller.go
