### ISSUE TITLE
ansible installer (for openshift) needs to create proper service account names for 0.6.0

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#4043]
I wrote a PR to fix this (see PR  #4020) but I am documenting the issue here with the workaround until that PR is merged. Once that PR is merged, this issue can be closed.

If you try to install 0.6.0 on OpenShift using the ansible scripts, the grafana and prometheus pods fail to start with the following errors:

The log from the grafana pod:

```
chown: changing ownership of '/data/grafana': Operation not permitted
chown: changing ownership of '/var/log/grafana': Operation not permitted
```

The log from the prometheus pod:

```
level=error ts=2018-03-06T17:41:54.607556011Z caller=main.go:323 msg="Opening storage failed" err="mkdir data/: permission denied"
```

The problem is the names of the system accounts have changed. In order to get the installation to fully work, after you run the ansible playbook command you must run these following 4 commands. Once the pods are re-created things will work:

```
oc adm policy add-scc-to-user anyuid -z grafana -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc delete pods --selector=app=grafana -n istio-system
oc delete pods --selector=app=prometheus -n istio-system
```

**Comment by hklai** [comment]
Since https://github.com/istio/istio/pull/4020 has been merged, I think we can just close this.
