### ISSUE TITLE
ansible installer does not install jaeger when requested

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#4044]
Passing this environment to the ansible installer:

```
{
  "cluster_flavour": "ocp",
  "istio": {
    "release_tag_name": "",
    "delete_resources": true,
    "dest": "/tmp/istio",
    "jaeger": true,
    "samples": ["bookinfo"]
  }
}
```

Notice the jaeger property is set to true. As per https://github.com/istio/istio/tree/master/install/ansible where it says:

```
An example of an invocation where we want to deploy Jaeger instead of Zipkin would be:
   ansible-playbook main.yml -e '{"istio": {"jaeger": true}}'
```

I expect Jaeger to be installed and not Zipkin. However, after running the  playbook, zipkin is installed, and jaeger is not:

```
$ oc get pods --selector=app=zipkin -n istio-system
NAME                      READY     STATUS    RESTARTS   AGE
zipkin-3088650775-j2vbl   1/1       Running   0          14m
$ oc get pods --selector=app=jaeger -n istio-system
No resources found.
```

**Comment by jmazzitelli** [comment]
Looks like this is simply a documentation issue. The jaeger setting has been moved to the addons section, but the docs do not reflect that change from this commit: https://github.com/istio/istio/commit/8d888ea2e7b0ba390e6e07c26bdd3876621e0d98

**Comment by hklai** [comment]
Looks like it has been fixed. Closing.
