### ISSUE TITLE
What commands can I use to build sidecar image and istioctl based on my local envoy source code

### ISSUE THREAD

**Issue by He-Jingkai** [istio/istio#40454]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I'm trying to build sidecar and istioctl based on my local envoy source code. I'm wondering what command I can use to build them. I used `--override_repository=envoy=PATH/TO/ENVOY` to build executable file of envoy proxy based on local envoy source code. However, I don't know what command I can use to build docker image and kubectl based on the executable file(or the source code).

Thank you very much for answering my question.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X ] Test and Release
[ ] User Experience
[ X ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
check `download_wasm_if_necessary` function in `bin/init.sh`

**Comment by ericvn** [comment]
`make istioctl` will build the binary.`make docker` will build a set of docker images. istio/istio/bin/init.sh is the code that downloads Envoy to be used in the image. You will want to use your build.

**Comment by He-Jingkai** [comment]
> `make istioctl` will build the binary.`make docker` will build a set of docker images. istio/istio/bin/init.sh is the code that downloads Envoy to be used in the image. You will want to use your build.

@ericvn @zirain 
So if I want to use mu own envoy build, the only way is to upload it to a website and change the url to my own url? Is there any alternative method so that I can use my build directly without uploading and downloading?

**Comment by zirain** [comment]
just copy your binary to `out/linux_amd64/envoy`

**Comment by He-Jingkai** [comment]
Thank you very much!  @ericvn @zirain

**Comment by emilykmarx** [comment]
Thank you for this! Just to add for anyone else finding this -- depending on your build config it may be `out/linux_amd64/release/envoy` rather than `out/linux_amd64/envoy`
