### ISSUE TITLE
MaxRetries What is the default value

### ISSUE THREAD

**Issue by zgqqiang** [istio/istio#40489]
https://github.com/istio/istio/blob/e1f63e8ce82e3bad28c2bb0a87f4bc7ffefac1b9/pilot/pkg/networking/core/v1alpha3/cluster.go#L62

The annotation value is 3, and the code value is math.maxuint32？

**Comment by ramaraochavali** [comment]
Which annotation value is 3? This is circuit breaker limit for max retries and by default is not enforced.
