### ISSUE TITLE
Mixer might be missing incoming config change events from ApiServer

### ISSUE THREAD

**Issue by ozevren** [istio/istio#4048]
We had two cases reported where it looked like Mixer might be somehow missing config change events when listening to ApiServer. One event was an external reported issue, where during the upgrade from 0.5.0 -> 0.5.1 the attribute manifest information in the running Mixer was lost, even though the resource was as expected. The restart of Mixer fixed the issue. In a separate case, it looked like the rules were not being populated correctly. In both cases, we don't have a definitive root cause.

The current suspicion is a lost config change event while listening to ApiServer events. The mitigation is to specify a resync period in the go-client Informer, which will republish all listened-to resources again.

The downside of the resync period is, the current code will trigger a config change in the absence of level-triggering, thus causing the dispatcher to be renewed at every resync period. The config code can be updated to handle the case.

**Comment by ayj** [comment]
level-triggered k8s controllers helps mitigate this problem (see https://speakerdeck.com/thockin/edge-vs-level-triggered-logic).

**Comment by douglas-reid** [comment]
Is this the sort of thing we build a test for?

**Comment by ozevren** [comment]
@ayj Updated the wording to capture level-triggering.
@douglas-reid Not sure what you mean by that? Chatted with @mandarjog a bit on this yesterday. It is plausible that the loss is actually not originating in the Mixer code, but in the incoming event stream somehow. This is hard to write tests for.

**Comment by douglas-reid** [comment]
@ozevren that sorta addresses my question. I was wondering if it is possible to build a test that would capture this or not.
