### ISSUE TITLE
sidecar.istio.io/inject annotation vs label: undocumented difference in behavior

### ISSUE THREAD

**Issue by cavedon** [istio/istio#40512]
### Bug Description

I have configured my namespace not to auto-inject the istio-proy sidecar.
If I set `sidecar.istio.io/inject: "true"` as **label** in the pod spec template, the sidecar is injected.
If I set `sidecar.istio.io/inject: "true"` as **annotation**  in the pod spec template, the sidecar is not injected.

https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/, https://istio.io/v1.13/blog/2019/data-plane-setup/, and https://istio.io/latest/docs/ops/common-problems/injection/ only talks about the `sidecar.istio.io/inject:` **annotation**, while https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/ only talks about  `sidecar.istio.io/inject:` **label**.

Why the difference in behavior? I believe it needs to be explained in some documentation...

### Version

```prose
% kubectl version --short
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.8

Istio version: 1.14.1
```

**Comment by howardjohn** [comment]
The short answer: just only use the label and pretend the annotation doesn't exist.

The annotation can only opt out, cannot opt in due to k8s limitations

**Comment by howardjohn** [comment]
Fixed in https://github.com/istio/istio.io/pull/11744

**Comment by umi0410** [comment]
Just for someone who might still uses an old istio version, `sidecar.istio.io/inject` label has been supported since `v1.11`
It's written in [the v1.11 release announcement](https://istio.io/latest/news/releases/1.11.x/announcing-1.11/#updates-to-revision-and-tag-deployments).
