### ISSUE TITLE
istio-ingress gateway: Logs are not sufficient to analyse the issue

### ISSUE THREAD

**Issue by hariyada** [istio/istio#40516]
### Bug Description

Hi All

I am using istio ingress gateway in my service for exposing endpoints to outside world.

**istio version :1.11.7**

**Problem :**
From one of the client i am invoking the exposed endpoint and the connection is getting broken to the server.
 Client claims that the server is closing the connection, In order to investigate i turned on debug level logging on istio ingress gateway and received the following logs, **the below logs are not sufficient to analyse the issue**, any other way to find detailed logs
```
{"level":"debug","time":"2022-08-16T11:06:52.178952Z","scope":"envoy filter","msg":"tls:onServerName(), requestedServerName: 5303eeb0-fa62-43a8-a8a1.tn.mydomain.com"}
{"level":"debug","time":"2022-08-16T11:06:52.179010Z","scope":"envoy conn_handler","msg":"[C1187] new connection from 10.250.15.219:61887"}
{"level":"debug","time":"2022-08-16T11:06:52.214612Z","scope":"envoy connection","msg":"[C1187] remote close"}
{"level":"debug","time":"2022-08-16T11:06:52.214628Z","scope":"envoy connection","msg":"[C1187] closing socket: 0"}
{"level":"debug","time":"2022-08-16T11:06:52.214650Z","scope":"envoy connection","msg":"[C1187] SSL shutdown: rc=0"}
```
GatewayConfiguration:

    - hosts:
        - '*.tn.mydomain.com'
      port:
        name: https-xsuaa-st-simple
        number: 2443
        protocol: HTTPS
      tls:
        cipherSuites:
          - AES128-GCM-SHA256
          - AES256-GCM-SHA384
          - DHE-RSA-AES128-GCM-SHA256
          - DHE-RSA-AES128-SHA256
          - DHE-RSA-AES256-GCM-SHA384
          - DHE-RSA-AES256-SHA256
          - ECDHE-ECDSA-AES128-GCM-SHA256
          - ECDHE-ECDSA-AES128-SHA256
          - ECDHE-ECDSA-AES256-GCM-SHA384
          - ECDHE-ECDSA-AES256-SHA384
          - ECDHE-ECDSA-CHACHA20-POLY1305
          - ECDHE-RSA-AES128-GCM-SHA256
          - ECDHE-RSA-AES128-SHA256
          - ECDHE-RSA-AES256-GCM-SHA384
          - ECDHE-RSA-AES256-SHA384
          - ECDHE-RSA-CHACHA20-POLY1305
          - EDH-RSA-DES-CBC3-SHA
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        credentialName: amqp-tls-secret
        minProtocolVersion: TLSV1_2
        mode: SIMPLE

 

### Version

```prose
1.11.7
```

**Comment by howardjohn** [comment]
Seems like the client is closing the connection, I am not sure envoy can give more logs here if you are already on trace logs?
