### ISSUE TITLE
Should we allow all cors preflight request in authorization policy by default?

### ISSUE THREAD

**Issue by imuxin** [istio/istio#40540]
**Describe the feature request**
Since we have enabled BypassCorsPreflight in JWT policy by default （pr: https://github.com/istio/istio/pull/36981), jwt auth info can be used as requestPrincipals in authorization policy. jwt_authn fields of cors preflight request will be empty, people could forget add policy to allow cors preflight request.
So should we allow all cors preflight request in authorization policy by default?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
IMO we should not automatically insert bypasses into authz policy. It is too easy to unintentionally expose more than expected. We should be secure by default and not implicitly open holes in the policy
