### ISSUE TITLE
Enable specific stats for a subset of pods?

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#40554]
### Bug Description

Not sure if this is a bug or feature request, maybe just a discussion.

We sometimes have the need to enable a lot of specific stats on Envoy for some low-level debugging.
However, there doesn't seem to be a good way to do this in Istio without applying it globally to the whole mesh (which would be impractical).

What we are doing today is that we use the Istio annotation for Envoy statistics as documented here on the specific pods we need them to apply:
https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/

```
sidecar.istio.io/statsInclusionPrefixes
sidecar.istio.io/statsInclusionRegexps
sidecar.istio.io/statsInclusionSuffixes
```

Going forward those annotations seem to be deprecated:
https://istio.io/latest/docs/reference/config/annotations/

Is there another way to enable this? A custom bootstrap might be the solution, but that is heavy surgery,

At a minimum, having the ability to setup different stats for Gateways and mesh sidecars would be a huge help already.

### Version

```prose
istio 1.14.1
```

### Additional Information

N/A

**Comment by zirain** [comment]
try [ProxyConfig](https://istio.io/latest/docs/reference/config/networking/proxy-config/) with custom `selector`

**Comment by bvandewalle** [comment]
Thanks @zirain , that seems to solve it! Closing this ticket
