### ISSUE TITLE
Change logging levels for pilot-agent on the fly

### ISSUE THREAD

**Issue by timonwong** [istio/istio#40560]
Currently, there is no way I can find to change pilot-agent logging levels (like ctrlz in pilot, operator, etc..). Am I missing something?

And also I'd like to add ControlZ interface to pilot-agent if it's reasonable.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
IIRC, you can use `values.global.logging.level`

**Comment by timonwong** [comment]
> IIRC, you can use `values.global.logging.level`

Can this change logging levels dynamically (without recreate pod?)

**Comment by zirain** [comment]
nop, it's design for install.
