### ISSUE TITLE
circuit breaker does not work as expected

### ISSUE THREAD

**Issue by h9ing** [istio/istio#40576]
### Bug Description

HI,  I want to learn how does Circuit Breaker work.
It looks different than I expected.

(I have asked questions in istio discuss, but have not gotten answer yet.)

---

I have only one httpbin pod, and I use 2 difference client (C1 & C2) to call httpbin. 

Step:
1. C1 call httpbin/status/502 3 times, then next time I got 503. 
I think Circuit Breaker was working.

2. C2 to call httpbin/status/200 immediately. 
I expected to get http status 503 response, but I got 200.

3. C1 called httpbin/status/200 again, I still got 503.
Circuit Breaker was still working.

I expected that if Circuit Breaker is open, then any client call it will got http status code 503.
But it doesn't look like that. The other client can still get response.

Have I done something wrong?
Or where can I find more detail?

Thank you!

### Version

```prose
istioctl version:
client version: 1.14.3
control plane version: 1.13.1
data plane version: 1.13.1 (15 proxies)

kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.22.11

helm version
v3.8.2+g6e3701e
```

### Additional Information

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{},"name":"httpbin","namespace":"circuit-breaking"},"spec":{"host":"httpbin","trafficPolicy":{"connectionPool":{"http":{"http1MaxPendingRequests":1,"maxRequestsPerConnection":1},"tcp":{"maxConnections":1}},"outlierDetection":{"baseEjectionTime":"3m","consecutive5xxErrors":1,"interval":"1s","maxEjectionPercent":100}}}}
  creationTimestamp: "2022-08-17T10:51:24Z"
  generation: 8
  name: httpbin
  namespace: circuit-breaking
  resourceVersion: "1323732"
  uid: d3d9e6a5-a62f-4132-b615-ad18fc0c4fa8
spec:
  host: httpbin
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 10
      tcp:
        maxConnections: 100
    outlierDetection:
      baseEjectionTime: 20s
      consecutive5xxErrors: 3
      interval: 5s
      maxEjectionPercent: 100
      minHealthPercent: 0

### Affected product area

- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by ramaraochavali** [comment]
Is C1 and C2 are clients with mesh proxy?

**Comment by h9ing** [comment]
> Is C1 and C2 are clients with mesh proxy?

HI @ramaraochavali , Yes! They are all with mesh proxy.

And I tested different situations and got difference results.

## 1
C1 & C2 use postman to call httpbin via ingress gateways. (They are not with mesh proxy.)
If C1 triggered circuit breaker and got 503, C2 would block by circuit breaker and got 503 too.
If C2 triggered circuit breaker and got 503, C1 would block by circuit breaker and got 503 too.

**circuit breaker seems to be working fine!**

## 2
C1 used postman to call httpbin via ingress gateways.(not with mesh proxy.)
C2 was client with mesh proxy.

If C1 triggered circuit breaker and got 503, C2 would still get 200.
If C2 triggered circuit breaker and got 503, C1 would still get 200.

**circuit breaker seems to not work as expected.**

**Comment by ramaraochavali** [comment]
What you are describing is expected behaviour. The circuit breaker ejects hosts based on consecutive 5xx on the client proxy (Ingress or mesh sidecar)

**Comment by h9ing** [comment]
I see! Thank you for your explanation. 😀
