### ISSUE TITLE
Add Kubernetes Recommended Labels to Istio Helm Charts

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#40573]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Kubernetes has a list of recommended labels to be added to resources <https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/>. It would be great if we can add these labels to all resources in istio helm chart as an improvement on standardization.

The current istio helm charts does not introduce the said labels:
![image](https://user-images.githubusercontent.com/15870761/185782818-5e59b46e-5489-40e5-a1e1-ccd78ca24c54.png)

I am happy to submit a PR for this.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
can be done by helm as well https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/
