### ISSUE TITLE
Documentation on Istio Federation with SPIRE on multiple mesh 

### ISSUE THREAD

**Issue by SoulKyu** [istio/istio#40589]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Actually their is no good documentation / example that permit to create a multi-mesh communication with Spire and Istio.
The scope would be to have 2 différentes meshs and to use Spire federation_with to permit communication with another mesh.
I try to setup and it's very confused.

**Describe alternatives you've considered**
Trying to fetch information on many other documentation which is actually not an easy tasks.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane
[X] Multi Meshes

**Additional context**
The context would be this : 

Two cluster (cluster-a and cluster-b) which are on two differents meshes on two differents trust domain (cluster-a.istio.mesh and cluster-b.istio.mesh). 
Having 2 spire server for each cluster configured to federate on each other
Configure Istio to use spire as CA.
Be able to communicate between each cluster using MTLS.

**Comment by sudeeptoroy** [comment]
I agree the documentation is not great here, i am ready to work with anyone to get this out. I have a working config here: https://github.com/sudeeptoroy/spirefed. I hope this helps for now.
