### ISSUE TITLE
HTTP2 on the mesh for HTTP/1.1 upstream destination?

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#40604]
Is there a way to configure Istio to use HTTP2 for communication between the sidecars EVEN if the services are not able to consume HTTP2 yet?

Basically something like this:

```Client <---http/1.1--> Istio-gateway <-- http2 --> Istio-Sidecar <--http/1.1-->Upstream service.```

[This should work with the right configuration on Envoy I believe](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades). Is there any way to configure this on Istio?

I believe that the `h2UpradePolicy` only works if the Upstream service is also able to consume http2, isn't?

We are trying to solve a corner-case where we are getting hit by a very large amount of new connections and requests at the same time on our gateways. Because of HTTP/1.1 HoL blocking limitations, the Gateway opens a large amount of new connections to the istio-sidecar in order to multiplex all the new requests. All those new connections coming up at once create some instability on the sidecar for a couple seconds (to process the high cost of new connection establishment). HTTP2 would solve this but our upstream service doesn't seem to accept it yet.

### Version

```prose
istiod 1.14.3
```

**Comment by chirauki** [comment]
> I believe that the h2UpradePolicy only works if the Upstream service is also able to consume http2, isn't?

That depends on the configuration for your service I think. I tested with bookinfo, and if I only enable `h2UpradePolicy`, all works OK. I can see the gateway gets `http/1.1` requests, sends `http2` requests to the sidecar, and the sidecar sends `http/1.1` to the application again.

gateway:
```
[2022-10-17T10:46:02.324Z] "GET /productpage HTTP/1.1" 200 - via_upstream ...
```

sidecar:
```
[2022-10-17T10:57:22.835Z] "GET /productpage HTTP/2" 200 - via_upstream ...
```

app:
```
INFO:werkzeug:127.0.0.6 - - [17/Oct/2022 10:57:22] "GET /productpage HTTP/1.1" 200 -
```

A wireshark capture on the `productpage` container shows the same:

![image](https://user-images.githubusercontent.com/1199619/196161060-87b5f6cc-43f0-4bae-be11-eb3946a70c4c.png)

Note that, by default, bookinfo services [are configured with `http/1.1`](https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml#L298) as the port name of the service is named `http`. If I change the port name to `http2` in the `productpage` service, then the traffic breaks.

gateway:
```
[2022-10-17T11:03:37.314Z] "GET /productpage HTTP/1.1" 502 - via_upstream ...
```

sidecar:
```
[2022-10-17T11:03:37.315Z] "GET /productpage HTTP/2" 502 UPE upstream_reset_before_response_started{protocol_error} - ...
```

app:
```
ERROR:werkzeug:127.0.0.6 - - [17/Oct/2022 11:03:16] code 505, message Invalid HTTP version (2.0)
INFO:werkzeug:127.0.0.6 - - [17/Oct/2022 11:03:16] "PRI * HTTP/2.0" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -`
```

So, it seems that `productpage` does not support `http2`, but even with `h2UpradePolicy` set to `UPGRADE`, the traffic flows as long as the destination service is correctly configured.

**Comment by bvandewalle** [comment]
Thanks for the context and trying it out @chirauki 

I was not able to make this work when trying it on my app. Let me give it another try. Which version of istio are you using here?

**Comment by chirauki** [comment]
I don’t have the test instance anymore but I believe it was 1.14.
