### ISSUE TITLE
Single Rate limit bucket with weighted request to consume tokens. 

### ISSUE THREAD

**Issue by arvindmaan** [istio/istio#40608]
Hi Everyone

I have one query related local rate limit. We have a use case where different APIs holds different response/processing time. For example Bulk APIs vs Single Item API .
We want to utilise local rate limit , one way is having different token buckets with respect to APIs and let them get processed independently.
However as we can’t guarantee incoming traffic ratio ( Bulk APIs calls vs Light calls) we may end up in situation where one bucket is exhausted and other one still active.
I am looking for alternative Option where same bucket can be leveraged for multiple APIs and we can assign weights to APIs path . For example:
Say we have 100 Tokens , Assign weights to APIs :
API v1 weight → 1
API v2 weight → 2

On invocation of v1 light weight API Single token should be consumed on the other hand on invocation of v2 API 2 tokens would be consumed.Can we achieve something similar where same bucket can be shared across APIs with different token consumption rate?

**Comment by zirain** [comment]
IIRC, local ratelimit do not support this scenario, maybe you should use global ratelimit with a custom RLS.
