### ISSUE TITLE
Make certificate subject adjustable with indentifiable information

### ISSUE THREAD

**Issue by tabnul** [istio/istio#40615]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We use Istio with AWS ACM PCA.
AWS ACM PCA has a limitation where it doesn't log the SAN Attributes of a certificate, only the subject and some other metadata.
Istio certificate subjects are empty (O=) , meaning that the created certificates are unidentifiable when the CA would be audited.
It would be very nice to have an option that sets the subject of the certificates, preferably with a value comparable to the SPIFFE uri, so that it is clear  where the  certificate came from.
I do understand this is an ACM PCA limitation, and we have submitted a feature request.

**Describe alternatives you've considered**
There is an alternative where you'd modify cert requests with Open Policy Agent, which would be a very ugly workaround.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
source https://github.com/cert-manager/istio-csr/issues/168

**Comment by hzxuzhonghu** [comment]
I guess you are saying the selfsigned CA,  by default the subject is not empty, it is `cluster.local`

**Comment by tabnul** [comment]
> I guess you are saying the selfsigned CA, by default the subject is not empty, it is `cluster.local`

We use AWS Private CA, with istio-csr , cert-manager and the AWS issuer.

**Comment by hzxuzhonghu** [comment]
IC

**Comment by boeboe** [comment]
Any progress?

**Comment by dondsouza** [comment]
Hello, we are integrating istio with Venafi TPP using certmanager and certmanager-istio-csr; and we are facing the same issue. The policies on Venafi TPP dont allow for the Subject name to be empty. So, it would be great if this enhancement can be accepted.

**Comment by boeboe** [comment]
Related to https://github.com/istio/istio/issues/42114 and https://github.com/istio/istio/issues/7153

**Comment by howardjohn** [comment]
Lets consolidate this in https://github.com/istio/istio/issues/42114, lots of discussion there already
