### ISSUE TITLE
How to get istio version using istio-client?

### ISSUE THREAD

**Issue by shumintao** [istio/istio#40628]
How to get istio version using istio-client? 

` import istio "istio.io/client-go/pkg/clientset/versioned"`

```go
func createKubeConfig(path string) func(t *testing.T) {
	return func(t *testing.T) {
		cc, err := NewClientFromLocalPath(path)
		assert.NoError(t, err)

		info, err := cc.kubeClient.Discovery().ServerVersion()
		assert.NoError(t, err)

		t.Log(info)
	}
}
```

**Comment by howardjohn** [comment]
You can see how this is done in https://github.com/istio/istio/blob/master/istioctl/cmd/version.go. There is no standardized way as part of client-go, however.

**Comment by shumintao** [comment]
> You can see how this is done in https://github.com/istio/istio/blob/master/istioctl/cmd/version.go. There is no standardized way as part of client-go, however.

Thank you very much, this can also get the istio version.
