### ISSUE TITLE
Provide advanced telemetry config to avoid high cardinality

### ISSUE THREAD

**Issue by rgaoistheone** [istio/istio#40622]
**Describe the feature request**
We are using transcoder for frontend and backend to communicate ,and for the proto definition like below will introduce high cardinality in metrics.(we've enabled request_path in telemetry configs)
```
option (google.api.http) = {
      post: "/something/v1alpha1/{item=items/*}:checkStatus"
      body: "*"
    };
```
So I'm curious if there's any configs available for such case? Like in nginx metrics `nginx_ingress_controller_request_duration_seconds_bucket` the path field is exposed like `path="/something(/|$)(.*)"`

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
maybe this will help you https://github.com/istio/istio/pull/40503
