### ISSUE TITLE
HTTP 2 incomplete request body

### ISSUE THREAD

**Issue by anuragagarwal561994** [istio/istio#40630]
### Bug Description

Tomcat Version: 9.0.65 with h2 upgrade protocol

We are using Ingress Gateway which is receiving traffic from downstream as HTTP 1.1

mTLS is disabled everywhere.

We have created a destination rule to a service which is having appProtocol as http2, protocol as tcp.

Istio Version: 1.13.3

Ingress to the pod is not via istio-proxy

We are receiving traffic as http2 but the issue that I am seeing is that while fetching the post body, we are not receiving full data. The json is breaking in between.

The weird part is, this is happening in 25% cases for 75% of the case things are working properly end to end.

I have tried to change multiple things, but nothing worked. Do we know how can we trace this and get to know the exact issue?

### Version

```prose
client version: 1.14.3
control plane version: 1.13.3
data plane version: 1.13.3 (83 proxies)
```

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/wiki/Troubleshooting-Istio for enabling debug/trace logs, may give more info.

**Comment by anuragagarwal561994** [comment]
@howardjohn I tried to reproduce the issue on my local with a load tester.

I used h2load to generate load. I gave my application excessive load that my local machine can't really handle.

I ran the test on 2 setups:

1. Ingress gateway to application
2. Ingress gateway to sidecar to application 

In both of these setups I observed something that the setup was running fine without errors but when I used to kill the setup in middle it sends empty or partial request bodies to application.

So I am assuming here that when the downstream is closing connection (which is sending traffic in http 1.1) this must be happening and because of this downstream is getting 502 UPE and because of that it is closing connections further connections hence making the problem worse.

In case when I am directly supplying the load to my application this issue is not happening.

Is there a possible reason why this is happening and how to resolve this?

**Comment by anuragagarwal561994** [comment]
I haven't seen any such issue happening for outbound requests.

I am making http 1.1 calls to the proxy and proxy is upgrading them to http 2.

I can't see any issues in the upstream services and this setup is currently running in production.

Hence I suspect something to do with ingress gateway

**Comment by anuragagarwal561994** [comment]
@howardjohn did you get time to look into this. Seems like another critical bug.

**Comment by howardjohn** [comment]
@anuragagarwal561994 it does seem fairly critical, but I want to be upfront and fail fast - I won't have time to look into this

**Comment by anuragagarwal561994** [comment]
@howardjohn anywhere I can help with this?
