### ISSUE TITLE
Ability to merge instead of override of global sidecar config with namespace specific sidecar config

### ISSUE THREAD

**Issue by Purushotham233** [istio/istio#40645]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
A default Sidecar config is provided in the istio root namespace. A Sidecar specified at namespace level override the global config completely. With this behaviour there is no proivision for the Cluster/Mesh administrator to add some common parameters.

Need a way to specify common parameter like default white-listed namespaces for all namespaces in a k8s-cluster.

**Describe alternatives you've considered** 1.13.5

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
This is a kind of common requirement,  other similar requirement is for DR merge.

**Comment by howardjohn** [comment]
What setting do you want to override?

**Comment by Purushotham233** [comment]
In the mesh there are some services dubbed platform services that are used by many other application services.

As a cluster/mesh administrator, need a way to globally white-list all the platform-services hosts in the mesh-level egress config. 
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
spec:
  egress:
  - hosts:
    - ./*
    - istio-system/*
    - platform-svc-1-ns/*
    - platform-svc-2-ns/*
    - default/kubernetes.default.svc.cluster.local
```

Currently we do this in the root-namespace sidecar config(w/o selector). But when the application services have to make any further customisation a sidecar config in the workload namespace is provided. With this global sidecar config is ignored. 

**Can think below 2 ways to achieve this behaviour:**
1. Merge global sidecar config with namespace-level sidecar config. 
2. These default whitelisted egress host can be added to sidecar via mutation while creating the config. Istiod can do similar to the way it mutates the pods.

**Comment by howardjohn** [comment]
IMO this is best handled by CI/CD type systems, helm, etc.

With merging its hard because then what if we have a specific use case where we need to actually deny some of these? Or if we don't notice the default, we set `egress.hosts: ~` (import nothing) and then suddenly get a bunch of imports that we don't expect.

**Comment by therealmitchconnors** [comment]
Here is an example of a MutatingWebhook which applies kustomize templates, and should be capable of this: https://github.com/sbueringer/kustomize-webhook .  I'm sure other solutions exist as well.

**Comment by Purushotham233** [comment]
Thanks for the inputs. Will proceed in one of the suggested approaches.

Agreed this particular requirement can be looked at more of customisation to the k8s declarations(Sidecar) and the istio components doesn't necessarily have to be concerned/ involved.
