### ISSUE TITLE
Support for x-forwarded-host header

### ISSUE THREAD

**Issue by msonnleitner** [istio/istio#40669]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Envoy supports the x-forwarded-host header, however it has to be explicitly activated according to its [docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-host): 

Envoy updates the :authority header if a host rewrite option (one of host_rewrite_literal, auto_host_rewrite, host_rewrite_header, or host_rewrite_path_regex) is used and appends its original value to x-forwarded-host if append_x_forwarded_host is set.

According to my tests, this header is not set when using Istio.

Is this something that could be supported in Istio?

**Describe alternatives you've considered**

Adding that header hard-coded in a VirtualService.
Writing an EnvoyFilter to change the route configuration or to append the host header to x-forwarded-host.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by nick4fake** [comment]
Wow, just noticed this is not an existing feature. Is there a way to get original gateway host in headers?

**Comment by msonnleitner** [comment]
> @msonnleitner In your alternatives considered, you have "Writing an EnvoyFilter to change the route configuration or to append the host header to x-forwarded-host." Were you able to get this working? Could you possibly share your EnvoyFilter for this?

No, for my use case, adding the header in a VirtualService was fine for me. Didn't try the Envoy Filter.
