### ISSUE TITLE
Sudden maximum CPU usage for istio pilot

### ISSUE THREAD

**Issue by Freakazoid182** [istio/istio#40671]
### Bug Description

I am running into an issue where I have `istiod` pods suddenly increasing to the maximum CPU limit. Regardless on how high I set the CPU limit on the pod, it increases to 100% of the CPU limit. It then also seems that updates to the istio service mesh are not propagated anymore when it's in this state, as if the pilot process is stuck in a loop or blocking.

Deleting the pod, which of course starts a new pod, resolves the issue for a while, but it will eventually get into this broken state again. It normally takes a couple of hours, sometimes a day or so. It's not clear what is triggering the event. It has happened on times where I was not doing any updates on the mesh.

As seen on this screenshot, the CPU usage suddenly spikes to the limit, and stays there:

![image](https://user-images.githubusercontent.com/5238563/186902882-213b582e-5c06-48f4-ab1b-75a1d26a1860.png)

I've ran a CPU profile task using `go tool pprof -http=:8888 localhost:8080/debug/pprof/profile` which resulted in the following graphviz output:

![image](https://user-images.githubusercontent.com/5238563/186903259-b4fb2364-e01f-4552-84df-29801a793814.png)

This result doesn't tell me a lot. I'm not sure how to proceed further investigating this behavior. I'm not seeing any error logs on the pilot container.

Are there any other logs or tools I should be looking at?
I hope someone can help me with this, and I'm happy to provide more information if necessary.

### Version

```prose
Istio version: 1.14.3
```

**Comment by ramaraochavali** [comment]
Did you enable `PILOT_ENABLE_ANALYSIS` to true?

**Comment by howardjohn** [comment]
Already fixed in https://github.com/istio/istio/pull/40595, just not merged.

**Comment by Freakazoid182** [comment]
We had `PILOT_ENABLE_ANALYSIS` set to `true` indeed. Thank you for fixing the issue!
