### ISSUE TITLE
Was the response data hijacked after ProductPage requested Reviews?

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#40670]
Was the response data hijacked after ProductPage requested Reviews? Does the response data go directly to ProductPage, or is it hijacked to Envoy? Looking at the iptable rules, I feel that it is hijacked to 15001,15001 how to handle the response data, I do not understand.

**Comment by zirain** [comment]
please checkout this blogs about how istio work: https://www.solo.io/blog/istios-networking-in-depth/
blogs in chinese: https://cloudnative.to/blog/istio-traffic-management-series-service-management-concept-theory/

**Comment by liuqi-sun** [comment]
> please checkout this blogs about how istio work: https://www.solo.io/blog/istios-networking-in-depth/ blogs in chinese: https://cloudnative.to/blog/istio-traffic-management-series-service-management-concept-theory/

That's not my concern. I'm concerned with iptables.

**Comment by liuqi-sun** [comment]
Another question, when I access www.google.com through curl in Sidecar pod, is traffic hijacked to 15001? If so, what did Envoy do?
