### ISSUE TITLE
remotePilotAddress has issue with multi cluster 

### ISSUE THREAD

**Issue by sumpf** [istio/istio#40691]
Hi, there.

istio version: istio-1.14.3
As I have private test environment with LXD, I installed two kubernete clusters and expose istio-eastwestgateway as NodePort.
and I set remotePilotAddress: 192.168.0.21:31361 like this and try to install istio in cluster2 but failed with error message. 

######### error message : "192.168.0.21:31361": must be a valid IP address ###############

it seems example for multi cluster does not support to add port at the end of line. 
is there a way to work around to test multicluster?
error message : "192.168.0.21:31361": must be a valid IP address

I followered this example.
https://istio.io/latest/docs/setup/install/multicluster/primary-remote/

01:02:14 ubuntu@project2-ops1 istio-1.14.3 → istioctl install --context="${CTX_CLUSTER2}" -f ./cluster2.yaml
This will install the Istio 1.14.3 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
- Processing resources for Istio core.                                                                                                                                2022-08-29T04:15:44.985462Z     error   installer       failed to update resource with server-side apply for obj Endpoints/istio-system/istiod-remote: Endpoints "istiod-remote" is invalid: [subsets[0].addresses[0].ip: Invalid value: "192.168.0.21:31361": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "192.168.0.21:31361": must be a valid IP address]

**Comment by zirain** [comment]
`remotePilotAddress` should not contains port, the port number is const to 15012.

if you're running test, suggest to use kind.

**Comment by sumpf** [comment]
@zirain, thanks for reply. I see I can only put ip addr. Then is it ok to use host ip addr instead for I dont have eastwest loadbalance ip addr. And what it means to use kind?

**Comment by zirain** [comment]
project kind https://kind.sigs.k8s.io/

**Comment by sumpf** [comment]
thanks zirain for your help!
