### ISSUE TITLE
Missing information about istio metrics labels available

### ISSUE THREAD

**Issue by ragovi** [istio/istio#40693]
### Bug Description

With telemetry v2, the procedure to augment/customize istio metrics has changed. Before v2 it was needed to alter EnvoyFilters, now it's done by [modifying the operator](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/).

In either case, with telemetry v1 or telemetry v2, there's no official information about the extra labels that you can add to the standard metrics.
There are examples in blogs mentioning [destination_ip](https://istio.io/v1.13/blog/2019/monitoring-external-service-traffic/), [destination_port, or request_host](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/), and a[ list of default metrics and labels](https://istio.io/latest/docs/reference/config/metrics/), but I cant find docs about supported (and working) extra labels.

- Is destination_ip or destinations_port for PassThrouhgCluster supported if you add the extra label for ` tcp_connections_closed_total`? This is important to observe external TCP traffic.
- Is there a list of supported extra labels for existing metrics in v1 and/or v2?
- I've tried the procedure for v2 with some labels found in examples or blogs. Some of them work as expected (destinations_port), other don't (destination_ip and request.host always informed as "unknown" in ` tcp_connections_closed_total`)

Thanks!

### Version

```prose
ISTIO_VERSION=1.9.9
```

### Affected product area

- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
1.9.9 is EOL

there's doc about metrics here https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/.

**Comment by ragovi** [comment]
Thanks zirian,

But in that link, there is no information about the extra labels available, regardless of the istio version.
Can you please answer the questions, for any istio non-EOL version you prefer?

**Comment by zirain** [comment]
https://istio.io/latest/docs/releases/supported-releases/

**Comment by ragovi** [comment]
Thanks again zirian.

Can you point to the documentation about supported labels for istio metrics, for any of the supported releases?
Is destination_ip label (used in the examples from istio blogs) supported for metric tcp_connections_closed_total in istio 1.12 or newer? 
Is destination_port label (used in the examples from istio blogs) supported for metric tcp_connections_closed_total in istio 1.12 or newer?

**Comment by zirain** [comment]
try the following, not 100% sure
```
destination_ip: string(upstream.address)
destination_port: string(upstream.port)
```
