### ISSUE TITLE
Multi-Cloud

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#407]
This Epic encompasses all Multi-Environment Istio capabilities. (see vocabulary: https://goo.gl/An5Qg2)
Among others:

- Istio running in Raw VM that join a cluster (implemented - v0.2)
- Istio running in a "cluster" entirely composed of Raw VMs
- Istio running on multiple K8s clusters from same Environment
- Istio running on multiple K8s clusters in multiple Environments

**Comment by ldemailly** [comment]
environments tag already existed with 9 tasks so deleting the "new" one to have only one

not sure if prefixing labels with istio- inside the istio repo makes sense?

**Comment by loewenstein** [comment]
I just tried to access the vocabulary document above and access seems to be restricted.
I requested access. However as I already requested access to other design documents with no response yet I thought I'd ask here as well.

**Comment by andraxylia** [comment]
Are you a member of istio-dev@googlegroups.com ? All docs are in the community drive, accesible to istio-dev.

**Comment by loewenstein** [comment]
No, I wasn't. Thanks.

**Comment by howardjohn** [comment]
All issues resolved, no updates for 1year, closing
