### ISSUE TITLE
Gateway conformance: support GatewaySecretMissingReferencedSecret

### ISSUE THREAD

**Issue by frankbu** [istio/istio#40714]
### Bug Description

Currently GatewaySecretMissingReferencedSecret is skipped because we need to implement support for checking if a referenced secret exists. Maybe move secrets into GatewayContext/PushContext?

### Version

```prose
latest
```

**Comment by dddddai** [comment]
I'm thinking how to update gateway status when the referenced secret is added/deleted, I haven't figured out a good way to do this... And HTTPRoute has the same problem(updating status on backend updates)

**Comment by dddddai** [comment]
@howardjohn Should we update gateway status when the referenced secret is added/deleted? It's a bit tricky since secret changes don't trigger full push, and the gateway controller has no chance to reconcile
