### ISSUE TITLE
Istiod starts accepting requests before it enables HTTP2

### ISSUE THREAD

**Issue by qfel** [istio/istio#40720]
### Bug Description

It appears istiod starts accepting request before it enables HTTP2 support. This causes a (usually short) time window during which HTTP2 requests fail due to protocol mismatch.

 - We start listening in [serveHTTP in NewServer](https://github.com/istio/istio/blob/ddb839267d020c528ace957a33bd7fbf0cd093ac/pilot/pkg/bootstrap/server.go#L1285)
 - Start updates the handler [to support H2](https://github.com/istio/istio/blob/ddb839267d020c528ace957a33bd7fbf0cd093ac/pilot/pkg/bootstrap/server.go#L478)
 - Start is called after NewServer
 - Ergo between NewServer and Start, requests will be accepted but not failed

Note that I've seen this (possibly) happen via HTTP2 webhook requests, even though the code seems to associate this with gRPC. Also the issue may not be relevant in K8s (due to readiness checks) but on platforms where the only signal accepted is the port listener, this can cause an issue.

### Version

```prose
The issue exists at least in master.
```

**Comment by hzxuzhonghu** [comment]
How do you access istiod?  We have a readiness  probe, before it is ready, sidecar can not connect to istiod by k8s service.

**Comment by qfel** [comment]
Cloud Run service (the only readiness it supports is "the port is open")

**Comment by hzxuzhonghu** [comment]
I think there can be case a port is listened without serving any http
