### ISSUE TITLE
Envoy Lua filter with http call doesn't work

### ISSUE THREAD

**Issue by desperateBob** [istio/istio#40726]
### Bug Description

Hi.

I'am writing an Envoy filter with lua script which should make a http call to internal service. It's the part of the work to improve development process: I need to pass correct http header to each request on dev cluster in order to send a traffic to correct Telepresence intercept.

But I stuck with the configuration of envoy filter. According to Istio documentation article https://istio.io/latest/docs/reference/config/networking/envoy-filter/ (2nd example), cluster should be configured in order to make an http call from lua.
I configured my cluster similar to the cluster in the example, but script threw an error `script log: [string \"function envoy_on_request(request_handle)...\"]:3: http call cluster invalid. Must be configured"`. 
I thought that I'm missing something and decided to check a filter from the Istio documentation as it is: it throws the same error as above.

My filter for the reference:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-custom-header
  namespace: dna
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_FIRST
        value: # lua filter specification
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                // get eventId from path
                ...
                local headers, body = request_handle:httpCall(
                    "lua_cluster",
                    {
                      [":method"] = "GET",
                      [":path"] = "/token?eventId="..eventId,
                      [":authority"] = "lua_cluster"
                    },
                    "",
                    5000)
                  // set data from body into request header
              end
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value:
          name: "lua_cluster"
          type: STRICT_DNS
          connect_timeout: 1s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: lua_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: "dna.service.com"
                          port_value: 443
```

So http calls from lua in envoy filter do not work.
If I'm missing something, please let me know.

Thanks.

### Version

```prose
Istio: 
1.11.4

K8s:
Client Version: v1.21.2
Server Version: v1.21.13-eks-84b4fe6
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
The `lua_cluster` in your example doesn't exist. In the doc it does

**Comment by desperateBob** [comment]
@howardjohn Thank you for your response.
Do you mean, that cluster configuration is invalid or cluster should be created somewhere else?
Sorry, that example - is my last attempt to make it works.

I've just tried with the exact config for cluster section as in the doc - the same error unfortunately:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-custom-header
  namespace: dna
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_FIRST
        value: # lua filter specification
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                // get eventId from path
                ...
                local headers, body = request_handle:httpCall(
                    "lua_cluster",
                    {
                      [":method"] = "GET",
                      [":path"] = "/token?eventId="..eventId,
                      [":authority"] = "lua_cluster"
                    },
                    "",
                    5000)
                  // set data from body into request header
              end
    # The second patch adds the cluster that is referenced by the lua code
    # cds match is omitted as a new cluster is being added
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value: # cluster specification
          name: "lua_cluster"
          type: STRICT_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: lua_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: "internal.org.net"
                          port_value: 8888
```

**Comment by desperateBob** [comment]
@howardjohn Hi. Can you please help me to understand what's wrong with my configuration in the above comment?

**Comment by desperateBob** [comment]
Solved this issue: was a problem with configuration, not a bug.
Command ` istioctl pc clusters` is very helpful to check if the cluster exists.

**Comment by pavan612** [comment]
Hi @desperateBob Can you let us know what you had done, we had follow the same config getting status code 503 in lua filter while calling httpCall.

**Comment by pavan612** [comment]
Hi @desperateBob Can you let us know what you had done, we had follow the same config getting status code 503 in lua filter while calling httpCall.

**Comment by vladfr** [comment]
@pavan612 "lua_cluster" needs to be defined in Envoy as a cluster.

**Comment by ivanmds** [comment]
You can use the destinationRule instead envoy cluster. See this example:

kind: ServiceEntry
apiVersion: networking.istio.io/v1beta1
metadata:
  name: externalhttps-se
  namespace: istio-system
spec:
  hosts:
    - externalhttps.domain.com
  ports:
    - number: 443
      protocol: HTTPS
      name: http
      targetPort: 443
  resolution: DNS
  
  
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: externalhttps-dr
  namespace: istio-system
spec:
  host: externalhttps.domain.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: externalhttps.domain.com



apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: externalhttps-ef
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: curity-ingress
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          defaultSourceCode:
            inlineString: |
              function envoy_on_request(request_handle)

                local resp_headers, resp_body = request_handle:httpCall(
                  "outbound|443||externalhttps.domain.com", 
                  {
                    [":method"] = "GET",
                    [":path"] = "/",
                    [":authority"] = "externalhttps.domain.com"
                  }, 
                  nil,
                  5000)
                
              end

**Comment by ivanmds** [comment]
You can use the destinationRule instead envoy cluster. See this example:

```kind: ServiceEntry
apiVersion: networking.istio.io/v1beta1
metadata:
  name: externalhttps-se
  namespace: istio-system
spec:
  hosts:
    - externalhttps.domain.com
  ports:
    - number: 443
      protocol: HTTPS
      name: http
      targetPort: 443
  resolution: DNS
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: externalhttps-dr
  namespace: istio-system
spec:
  host: externalhttps.domain.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: externalhttps.domain.com
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: externalhttps-ef
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: curity-ingress
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          defaultSourceCode:
            inlineString: |
              function envoy_on_request(request_handle)

                local resp_headers, resp_body = request_handle:httpCall(
                  "outbound|443||externalhttps.domain.com", 
                  {
                    [":method"] = "GET",
                    [":path"] = "/",
                    [":authority"] = "externalhttps.domain.com"
                  }, 
                  nil,
                  5000)
                
              end
```
