### ISSUE TITLE
XDS cache impacts propagation delay

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#40744]
### Bug Description

This is more of a performance issue rather than a bug.

We notice that turning on xds cache helps with cpu, but impacts propagation delay a lot due to cache locking. We conducted the following tests:

# setup
Control plane:
- 1 istiod pod 
- memory 26 G, cpu 10 cores

Data plane:
- 50 services and 500 pods
- and we mimic changes by pod rotation (roughly 5 pods rotated every 10 seconds) and istio config change (one virtual service routing change randomly per 5 seconds)

# results
I got the following results:
- When we have **all cache enabled** (default), the proxy convergence time (pilot_proxy_convergence_time) was on average 2.9s for P90, and 4.26s for P99.
- **Disable CDS cache alone**, the proxy convergence time was on average 2.1s for P90, and 3s for P99.
- **Disable both CDS and RDS cache** (with this [change](https://github.com/istio/istio/pull/40719) patched), the proxy convergence time was on average 0.94s for P90, and 2.55s for P99. Some CPU throttling occurs so I think if more CPU is given, propagation delay (especially P99) should further improve.
- **Disable all cache**, the proxy convergence time was on average 0.85s for P90, and 2.39s for P99. CPU throttling was heavier than previously as expected.

I also enabled the mutex profile in a custom istiod build and saw 70% of time (209s out of 300s) was spent on waiting for lock for lruCache in the default case (all cache enabled):
<img width="777" alt="Screen Shot 2022-08-29 at 10 49 20 AM" src="https://user-images.githubusercontent.com/55459889/187754608-392fd152-93ca-4a87-a648-10330f914efd.png">

# proposal
I think for the short term, we should fix this bug to allow users to opt out RDS caching properly: https://github.com/istio/istio/pull/40719
For the longer term, is there any work planned for improving the xds caching? Some ideas:
- Cache per xds type. Right now seems like all xds calculation uses the same cache, separating out might help with lock contention
- Explore high concurrency lru caches (for example https://github.com/karlseguin/ccache), or other cache options

### Version

```prose
Istio 1.13.5
```

**Comment by hzxuzhonghu** [comment]
I could not understand `Disable ` will cause pilot_proxy_convergence_time down. Could you elaborate a little bit more

**Comment by hzxuzhonghu** [comment]
@yingzhuivy can you retest with the above patch if possible

**Comment by hzxuzhonghu** [comment]
I think purely use Rlock can not help much. Mostly the lock conflict can be from the `Add` can hold the lock for too long

**Comment by ramaraochavali** [comment]
> I think for the short term, we should fix this bug to allow users to opt out RDS caching properly

I agree with this. RDS cache in general uses significant memory

> Cache per xds type. Right now seems like all xds calculation uses the same cache, separating out might help with lock contention

Not sure if this really help. Because just using CDS did not significantly improve.

> Explore high concurrency lru caches (for example https://github.com/karlseguin/ccache), or other cache options

This may be better.

I think the problem is Add holds on to it for too long as @hzxuzhonghu . But after initial cache is populated this should not be issue. Is this happening in case where the enpoints are constantly changing?

**Comment by yingzhuivy** [comment]
> > I think for the short term, we should fix this bug to allow users to opt out RDS caching properly
> 
> I agree with this. RDS cache in general uses significant memory
> 
> > Cache per xds type. Right now seems like all xds calculation uses the same cache, separating out might help with lock contention
> 
> Not sure if this really help. Because just using CDS did not significantly improve.

You mean just disable CDS? It's still 0.8s improvement for P90, disable RDS also gives another 1.2s improvement.

> 
> > Explore high concurrency lru caches (for example https://github.com/karlseguin/ccache), or other cache options
> 
> This may be better.
> 
> I think the problem is Add holds on to it for too long as @hzxuzhonghu . But after initial cache is populated this should not be issue. Is this happening in case where the enpoints are constantly changing?

In my testing I have a deployment restarted every 10 seconds, so endpoints are constantly changing. But the hit ratio remains pretty high during my testing, above 95%, so most of the calls are Gets.

**Comment by hzxuzhonghu** [comment]
Not exactly, restarting the deployment triggers all  xDS cache ops: clear/add/get

**Comment by hzxuzhonghu** [comment]
Anyone is investigating on this

**Comment by yingzhuivy** [comment]
> Anyone is investigating on this

I'm not actively working on this, since the debounce part is more problematic for us at the moment and I'm working on that. I feel this cache lock issue is not a simple problem, and we probably want to explore some more performant caching options, maybe we need some design doc?

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by howardjohn** [comment]
How can mutex.unlock possibly be so slow? I get a slow lock, but this is **unlock**. I have never been able to recreate anything like that. Is  it possible there is something obscure going on here like a fork of Go, a non-standard OS that is slow at doing atomic operations, etc? Corruption of the profile?

**Comment by howardjohn** [comment]
@yingzhuivy any chance you have had a chance to try it in 1.18, which has https://github.com/istio/istio/pull/43524? If not, would be great to try it out

**Comment by yingzhuivy** [comment]
> @yingzhuivy any chance you have had a chance to try it in 1.18, which has #43524? If not, would be great to try it out

this is awesome, thanks! will definitely try out when we upgrade to 1.18, still on 1.15 now unfortunately :(

**Comment by hzxuzhonghu** [comment]
not stale
