### ISSUE TITLE
Istio Demo application is carching on M1 Mac

### ISSUE THREAD

**Issue by rajeshtg78git** [istio/istio#40741]
Hi Team 

I am using M1 mac with Docker Desktop and Minikube . 
 minikube start --memory=4096MB --cpus=4

Docker Desktop set with 
CPU : 8 , Memory : 9 GB , Swap : 2 GB, Disk Image : 120 GB .
The istio version is using is following 

` $ istioctl version
client version: 1.15.0-rc.0
control plane version: 1.15.0
data plane version: 1.15.0-rc.0 (8 proxies)
 ~ 

While following this link https://istio.io/latest/docs/setup/getting-started/ , I am seeing rating application is always crashing and seeing this in logs 

JVMDUMP032I JVM requested Java dump using '/opt/ibm/wlp/output/defaultServer/javacore.20220831.170442.1.0002.txt' in response to an event
JVMDUMP010I Java dump written to /opt/ibm/wlp/output/defaultServer/javacore.20220831.170442.1.0002.txt
0000000000A76A00: Object neither in heap nor stack-allocated in thread Equinox start level thread - Equinox Container: 04cf5760-c44e-4505-9f4d-c5cbfedba786
0000000000A76A00: O-Slot=0000000000A7EA18
0000000000A76A00: O-Slot value=000000400CCF96D0
0000000000A76A00: PC=000000400ED7498B
0000000000A76A00: framesWalked=8
0000000000A76A00: arg0EA=0000000000A7EA28
0000000000A76A00: walkSP=0000000000A7E968
0000000000A76A00: literals=0000000000000010
0000000000A76A00: jitInfo=0000004072F83A38
0000000000A76A00: method=00000000009BACB0 (org/eclipse/osgi/container/ModuleResolver$ResolveProcess.filterProviders(Lorg/osgi/resource/Requirement;Ljava/util/List;Z)Ljava/util/List;) (JIT)
0000000000A76A00: stack=0000000000A78108-0000000000A7F1D0
0000000000A76A00: Object neither in heap nor stack-allocated in thread Equinox start level thread - Equinox Container: 04cf5760-c44e-4505-9f4d-c5cbfedba786
0000000000A76A00: O-Slot=0000000000A7EA20
0000000000A76A00: O-Slot value=0000000000000001
0000000000A76A00: PC=000000400ED7498B

**Comment by hanxiaop** [comment]
See https://github.com/istio/istio/issues/40794

**Comment by zirain** [comment]
duplicate with https://github.com/istio/istio/issues/40794
