### ISSUE TITLE
 how use destination rule in istio ingress gateway without sidecar?

### ISSUE THREAD

**Issue by ggjjlldd** [istio/istio#40755]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
if I only use istio ingress gateway without sidecar, can I have circuit breaking ? how use destination rule in istio ingress gateway?

**Describe alternatives you've considered**
I want use circuit breaking without sidecar.
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
No

**Comment by howardjohn** [comment]
Yes, circuit breaking applies to client config so you just use normally
