### ISSUE TITLE
Handshake failed when run istio on virtual machine

### ISSUE THREAD

**Issue by funlake** [istio/istio#40751]
This is not really a bug, since i tried same thing on my local vm / k8s  and it wokred.

doc : https://istio.io/latest/docs/setup/install/virtual-machine/  
Controlplane network path is  :  istio on vm(pilot-agent & envoy) -> [ eastwest gateway -> istiod ( on k8s )   ]
I always got handshake failure online, from tcpdump grabbed packet  i saw that pilot-agent on vm always tried to handshaked with istiod on k8s with tlsv1 version , but this was tlsv1.3 on my local machine

So i wonder if i can force pilot-agent to use  tlsv1.2+ to do the handshaking with istiod?

### Version

```prose
istio : 1.12.2
kuberentes : 1.17.4
```

**Comment by funlake** [comment]
Log on vm showed:

failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: read tcp vm's ip:6852-> eastwestgatewayip:15012: read: connection reset by peer"

**Comment by funlake** [comment]
More info : when skip east west gateway and directly connected to istiod's node port, it worked,and package showed that handshake with tlsv1.3 protocol

**Comment by hzxuzhonghu** [comment]
tls.Config.MinVersion = 1.12 in istio

**Comment by funlake** [comment]
@hzxuzhonghu  you mean like this?if so then still  no luck for me .
`apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istiod-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
  - hosts:
    - '*'
    port:
      name: tls-istiod
      number: 15012
      protocol: tls
    tls:
      minProtocolVersion: TLSV1_2
      mode: PASSTHROUGH
  - hosts:
    - '*'
    port:
      name: tls-istiodwebhook
      number: 15017
      protocol: tls
    tls:
      mode: PASSTHROUGH`

**Comment by funlake** [comment]
This is not istio's problem,tried it on another k8s cluster and it worked

**Comment by hzxuzhonghu** [comment]
What's the cause
