### ISSUE TITLE
istio operator crashes continuously when installed in istio-system namespace

### ISSUE THREAD

**Issue by satyakrish** [istio/istio#40765]
### Bug Description

We have been using aks version 1.21.14 and istio verision 1.11.0 till now and in our deployment terraform scripts we have istio operator installed to istio-system namespace, and there is no watched namespace configured meaning by default istio-system namespace will be watched.

We did not have any issues so far.

Now we in  our new cluster deployments we are using aks to version 1.22.6, 1.23.8, 1.24.3 different clusters... and we are trying to use istio 1.14.3 (same behavior seen in 1.12.0 onwards ) 

But this  time istio operator deployment fails and the pod crashes continuoulsy and quickly that there is no time to get logs from the pod as it gets terminated and a new pod is launched and this cycle keeps repeating.

When we changed the namespace used to install istio-operator to something other that istio-system deploymetn was successful

Is this behavior expected?

### Version

```prose
istioctl versionclient version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (1 proxies)


Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-15T05:51:30Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zirain** [comment]
@satyakrish I can't reproduce this with istioctl 1.14.3

```
root@ecs-zirain:~# k get po -nistio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-74bfd5fdc5-f6hk5   1/1     Running   0          39s
istio-operator-6957f749c7-598tm         1/1     Running   0          75s
istiod-677675c567-45d4x                 1/1     Running   0          49s
root@ecs-zirain:~# k get iop -nistio-system
NAME       REVISION   STATUS    AGE
eastwest              HEALTHY   66s
root@ecs-zirain:~# istioctl version
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (1 proxies)
```

can you share istio-operator's crash logs:
```console
kubectl logs -l name=istio-operator -nistio-system (-p)
```

**Comment by satyakrish** [comment]
A I mentioned in the description, when the deployment fails and the pod crashes continuously and quickly that there is no time to get logs from the pod as it gets terminated and a new pod is launched and this cycle keeps repeating.

But looking at your kubectl pods output i compared with mine. So in our setup we have istio cni , so for istiod we have set `"istio_cni.enabled=true" . When this value is true im seeing the above behavior where deploying operator to istio-system crashes continuosly.

When e set `"istio_cni.enabled=false" , deployment of operator to istio-system works fine. But we need this to be enabled for functioning of istio-cni.  Can you pls check this out . 
e also have clusters deployed with istio version 12 having operator in istio-system namespace, so wee need a way to upgrade them (fyi all of them have istio_cni.enabled=true

```
resource "helm_release" "istiod" {
  depends_on = [
    null_resource.helm_repo,
    helm_release.istio_base,
    helm_release.istio_cni
  ]

  name      = "istiod"
  namespace = var.istio_namespace

  chart           = "istio-${local.istio_version}/manifests/charts/istio-control/istio-discovery"
  cleanup_on_fail = true
  force_update    = false
  timeout         = var.timeout

  set {
    name  = "istio_cni.enabled"
    value = "false"
  }

}
```

**Comment by zirain** [comment]
sorry for the late, following is my reproduce steps:

1. install istio-operator in `istio-system`

```console
istioctl-1.14.3 operator init --operatorNamespace istio-system
```

2.  create iop with cni enabled

```
cat <<EOF | kubectl apply -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
EOF
```

3, watch pods

```
kubectl get po -nistio-system -w

istio-cni-node-bkwzm                    1/1     Running   0          91s
istio-ingressgateway-575d6f5b7d-scxvf   1/1     Running   0          38s
istio-operator-6957f749c7-g6qx8         1/1     Running   0          6m43s
istiod-644b755854-f49sj                 1/1     Running   0          43s
```

I didn't seem anything wrong
