### ISSUE TITLE
Add Label to differentiate between namespace label and istio revision

### ISSUE THREAD

**Issue by zbintliff** [istio/istio#40782]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
With the introduction of [istio release labels](https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels-experimental) it allows us to have a `stable` or a `1-12` label which then point to `1-12-5` revision.  In a scenario where we upgrade from `1-12-4` to `1-12-5` we update stable and will slowly rollout deploys to update the sidecar.

However we are looking for ways to easily identify which pods are still using the *old* reference of stable. It would be great if the mutating webhook added the istio rev to the pod so we can easily tell. 

In other words, we will look at namespace to see which tag/label is used (`stable`, `1-12`) but the pods will also have meaningful information on which version of istio control plane it is actually connected to.

**Describe alternatives you've considered**
Right now we are describing pod and parsing the version from the istio-proxy image label. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
We use to add `istio.io/rev`. The problem we had is that if you end up putting it in matchLabels and its mutated during the pod creation, it no longer matches the label, and you quickly end up with 1000s of pods and kill your cluster. The obvious thing to do is just not use it in matchLabels, but we can't enforce or detect that, and the impact is huge if you do mess up.

We _could_ have defined a new label and added that, but chose against it. What we do have is the annotation:

```
sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
```

This allows querying for all pods in the revision, but its an annotation not a label so you do not have the convenience of `-l rev=default` or whatever for queries

**Comment by zbintliff** [comment]
Thanks for the fast response! 

Your comment made me realize we had 1-12 and 1-12-5 control plane revisions installed so while i found `sidecar.istio.io/status` it only said `1-12` making me think it was the tag/label.  I was able to confirm that this value is correct in other pods. This can be closed. Thank you.

**Comment by zbintliff** [comment]
SO just to confirm. If the istio tag is `1-12` and points to `1-12-5` then we expect that annotiation to have `1-12-5` on it?

**Comment by howardjohn** [comment]
Yep
