### ISSUE TITLE
Bookinfo Reviews Pods Crash on Apple M1

### ISSUE THREAD

**Issue by marrem** [istio/istio#40794]
### Bug Description

On an MacBook Pro (16-inch, 2021)
I have run both Docker Desktop and colima (https://github.com/abiosoft/colima#readme). In both I ran the 'getting started' project.

Installing istio on the cluster: OK
Setting istio injection on namespace: OK
Deploying the 'bookstore' deployment: OK
Associated gateway: OK
'Bookstore': reachable from within pod: OK
'Bookstore': reachable from host (via istio ingress): OK

<img width="1145" alt="afbeelding" src="https://user-images.githubusercontent.com/2941173/188321720-37d18390-0017-49ae-ae5e-0556c1f2110c.png">

However the 'review' section doesn't work.

When I display the logs I get:

-v1

```
$ kubectl logs reviews-v1-7598cc9867-qchsb

Launching defaultServer (WebSphere Application Server 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on IBM J9 VM, version 8.0.6.16 - pxa6480sr6fp16-20200902_01(SR6 FP16) (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/20.0.0.6/lafiles/en.html
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=000000400A92FCF0 Handler2=000000400B0622F0 InaccessibleAddress=0000000200000001
RDI=000000000000000D RSI=00000000FF9FFDA8 RAX=00000000E0020578 RBX=0000000000000002
RCX=00000000084ACF00 RDX=00000000084ACF00 R8=0000000091DC77CD R9=0000000008967E00
R10=00000000E040F030 R11=00000000E040EFC8 R12=00000000E040EFC8 R13=00000000E040F030
R14=0000000000000004 R15=00000000E0229328
RIP=0000000200000001 GS=0000 FS=0000 RSP=00000000088C10D8
EFlags=0000000000000212 CS=0033 RBP=00000000088AEB00 ERR=0000000000000004
TRAPNO=FFFFFFFFFFFFFFFF OLDMASK=0000000000000000 CR2=0000000200000001


*** Invalid JIT return address 0000000000000000 in 00000000088B6608

15:23:34.274 0x88b6300    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1565: ((0 ))
```

-v2

```
$ kubectl logs reviews-v2-6bdd859457-99rrw

Launching defaultServer (WebSphere Application Server 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on IBM J9 VM, version 8.0.6.16 - pxa6480sr6fp16-20200902_01(SR6 FP16) (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/20.0.0.6/lafiles/en.html


*** Invalid JIT return address 00000000FFD49C10 in 0000000000A69608

15:25:48.136 0xa69300    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1565: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/09/04 15:25:48 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/ibm/wlp/output/defaultServer/core.20220904.152548.1.0001.dmp' in response to an event
JVMDUMP010I System dump written to /opt/ibm/wlp/output/defaultServer/core.20220904.152548.1.0001.dmp
0000000000A69300: Object neither in heap nor stack-allocated in thread Equinox start level thread - Equinox Container: a52def9c-52ea-4356-9f0b-4231c048b060
```

-v3

```
$ kubectl logs reviews-v3-6c98f9d7d7-l5zbz

Launching defaultServer (WebSphere Application Server 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on IBM J9 VM, version 8.0.6.16 - pxa6480sr6fp16-20200902_01(SR6 FP16) (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/20.0.0.6/lafiles/en.html
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml


*** Invalid JIT return address 0000000000B16C00 in 0000000000A6D308



*** Invalid JIT return address 0000000000B1C300 in 0000000000A5DE08

15:21:47.675 0xa6d000    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1565: ((0 ))
15:21:47.675 0xa5db00    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1565: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/09/04 15:21:47 - please wait.
```

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (8 proxies)


$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.23.6+k3s1
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Additional Information

$ istioctl bug-report

Target cluster context: colima

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-09-04 17:45:56.546288 +0200 CEST

Cluster endpoint: https://127.0.0.1:6443
CLI version:
version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"go1.19", BuildStatus:"Clean", GitTag:"1.15.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.0}

Fetching proxy logs for the following containers:

istio-system//svclb-istio-ingressgateway-hzdnm/lb-tcp-15021
istio-system//svclb-istio-ingressgateway-hzdnm/lb-tcp-15443
istio-system//svclb-istio-ingressgateway-hzdnm/lb-tcp-31400
istio-system//svclb-istio-ingressgateway-hzdnm/lb-tcp-443
istio-system//svclb-istio-ingressgateway-hzdnm/lb-tcp-80
istio-system/istio-egressgateway/istio-egressgateway-5988d765d6-qtnbr/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-576c469c96-259mx/istio-proxy
istio-system/istiod/istiod-6df799468c-zc827/discovery
istiotut/details-v1/details-v1-7f4669bdd9-67gd2/details
istiotut/details-v1/details-v1-7f4669bdd9-67gd2/istio-proxy
istiotut/productpage-v1/productpage-v1-5586c4d4ff-spw84/istio-proxy
istiotut/productpage-v1/productpage-v1-5586c4d4ff-spw84/productpage
istiotut/ratings-v1/ratings-v1-6cf6bc7c85-2wjqz/istio-proxy
istiotut/ratings-v1/ratings-v1-6cf6bc7c85-2wjqz/ratings
istiotut/reviews-v1/reviews-v1-7598cc9867-qchsb/istio-proxy
istiotut/reviews-v1/reviews-v1-7598cc9867-qchsb/reviews
istiotut/reviews-v2/reviews-v2-6bdd859457-99rrw/istio-proxy
istiotut/reviews-v2/reviews-v2-6bdd859457-99rrw/reviews
istiotut/reviews-v3/reviews-v3-6c98f9d7d7-l5zbz/istio-proxy
istiotut/reviews-v3/reviews-v3-6c98f9d7d7-l5zbz/reviews

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /Users/marc_p/bug-report.tar.gz.

NOTE: I created a separate namespace 'istiotut' (tutorial) in which I enabled Istio injection.

**Comment by howardjohn** [comment]
Not all of the samples have been migrated to support multi-arch yet

**Comment by howardjohn** [comment]
actually we sent the code changes to do it but didn't publish new images. I'll do that next week and maybe you can verify it fixes the issue

**Comment by marrem** [comment]
Thanks. I haven't had time yet to verify if it works now with the dedicated arm images. But I saw that some x86 images did work, with a qemu_x86 that somehow spun up automatically in 'colima' or 'docker desktop' 's kubernetes environment. But for some odd reason the ibm jvm refused to run inside this emulation. Strange, because other parts of the application did work even though they were x64 images as well.

**Comment by howardjohn** [comment]
Yeah IME the emulation is decent but not perfect. A java app may be pushing
it's limits.

Istio itself had the same issue under emulation (for the iptables config)

**Comment by rdgoite** [comment]
I'm currently exploring Istio and I'm also experiencing the same issues on my Apple M1 environment.

@howardjohn I've been trying to find the source code for the reviews service (actually bookinfo in general). Is that available somewhere? Where are we in terms of the multi-arch support you mentioned?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/tree/master/samples/bookinfo/src

If you use the 1.17.0 images it _should_ work (https://github.com/istio/istio/pull/40825). LMK if not

**Comment by ericvn** [comment]
As John mentioned I think if you use the latest in the 1.15 or main branches, it should work. 1.15.1 should be the first release with it built in.

**Comment by rdgoite** [comment]
Sorry, I'm not quite sure where these versions are referenced. The latest tag in the repo seems to be 1.15.0. `downloadIstio` script doesn't recognise either 1.15.1 or 1.17.0. Is the `master` branch at 1.17.0?

**Comment by ericvn** [comment]
Master branch will become 1.16.0 in the future. If you want an actual release with this support, you'll need to wait for 1.15.1. You could however clone the istio/istio repository and deploy using the master and 1.15 branches now, but that does require a little more than just downloading the actual release tar files.

**Comment by howardjohn** [comment]
The "1.15" and "1.17" are unrelated versions btw. One is the Istio version
and one is the bookinfo version, which are decoupled

**Comment by rdgoite** [comment]
I see. Thanks for clarifying. The images in `master` (db584568822c8a4ed4de2ca997d3e12e60eae15b) seem to be working without any problems so far on my local M1 env.

**Comment by marrem** [comment]
> https://github.com/istio/istio/tree/master/samples/bookinfo/src
> 
> If you use the 1.17.0 images it _should_ work (#40825). LMK if not

I have edited the `samples/bookinfo/platform/kube/bookinfo.yaml` replacing the image tags `1.16.4` by `1.17.0`.

After redeploying:

```
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-698b5d8c98-fgxc4      2/2     Running   0          97s
ratings-v1-5967f59c58-9jwp5      2/2     Running   0          97s
productpage-v1-bf4b489d8-jsrwv   2/2     Running   0          97s
reviews-v1-9c6bb6658-qkbc4       2/2     Running   0          97s
reviews-v2-8454bb78d8-l9p8m      2/2     Running   0          97s
reviews-v3-6dc9897554-mxbbj      2/2     Running   0          97s
```

That looks better.

Let's look at the webpage:

<img width="1254" alt="afbeelding" src="https://user-images.githubusercontent.com/2941173/190900930-0ae5990a-a5f6-45f3-bc7a-a3d6cdb77c9a.png">

Yep it all works. Thanks. Have the k8s deployment files been updated. I.e. should I update the 'samples' folder?

**Comment by howardjohn** [comment]
The files have been updated in `master` and `release-1.15`. So I think this is reoslved, thanks for verifying!
