### ISSUE TITLE
istioctl v1.15 execute invalid

### ISSUE THREAD

**Issue by niutendo** [istio/istio#40798]
### Bug Description

We corrent use isito v1.12.1 and eks v1.21.13.

We want to upgrade istio version to 1.15, but we have promble to execute istioctl.

"Error: create Kubernetes client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### Version

```prose
$isitoctl version 
exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
1.15.0

$istioctl install --set profile=demo -y
Error: create Kubernetes client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

$kubectl version --short
Client Version: v1.22.13            //I changed '1.19 1.21 1.22' ,is same
Server Version: v1.21.13-eks-84b4fe6
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by a7i** [comment]
Solution: update the AWS CLI and run `aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION`
