### ISSUE TITLE
Support short hosts like <service name>.<namespace> in virtual service and destination rules

### ISSUE THREAD

**Issue by DanielYWoo** [istio/istio#40819]
**Describe the feature request**
We have 40+ clusters and the FQDN is `<service name>.<namespace>.svc.<cluster-id>.<company suffix>`.

The problem is, we have duplicated configurations across all clusters, e.g., to call the `billing` service, I will have the different virtual service configurations in each cluster:
- billing.financial.datacenter001.mycompany.com
- billing.financial.datacenter002.mycompany.com
- billing.financial.datacenter003.mycompany.com
- ....

To avoid the duplication by using a single set of configuration, I hope I can call the billing service with `billing.financial` instead of FQDN which is different in every data center. However, currently the virtual services match either the `<service name>`, or the whole FQDN, with the `<service name>.<namespace>` format, it reports error like 
```
❯ istioctl  analyze --all-namespaces
Error [IST0101] (VirtualService financial/billing) Referenced host not found: "billing.financial"
```
I hope we can use short host names like `<service name>.<namespace>` in destination rules and virtual services.

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I understand the concern - its very valid - but I don't think this can happen. Extending the `<service name>` is already buggy because we cannot tell if they wanted the literal hostname (doesn't need `.`s, for example `localhost` is common) or the short name. With a `.` we cannot tell at all.

In http://gateway-api.org/ we have switched to using direct references to Service instead of implicit hostname matching which resolves this

**Comment by DanielYWoo** [comment]
Understood and close it. My solution would be use tools to generate the YAML files instead of manually maintaining them.

> http://gateway-api.org/

When I first read the document of Istio I feel the same, using hostname is a little wild and error-prone. Is Istio moving towards this new standard?

**Comment by howardjohn** [comment]
We will/have adopt the APIs, but not remove the existing ones. Also mesh
support for gateway-api is still experimental - rapidly in development
currently.

so its a bit early, but yes that is the long term plan
