### ISSUE TITLE
TestXdsProxyStatus test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#40824]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/40808/integ-pilot-istiodremote_istio/1567164950667857920

Conerning log: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/40808/integ-pilot-istiodremote_istio/1567164950667857920/artifacts/pilot-83229990ba474abda24d3c607/TestXdsProxyStatus/_test_context/istio-state2624545497/externalistiod-1/istiod-5cf7f9bd6b-tdwtr_discovery.log seems we have some endless loop with no backoff maybe?

**Comment by ingwonsong** [comment]
seems to be resolved. close.
