### ISSUE TITLE
Mechanism in Istiod to detect degradation of k8s control-plane and throttle/disable propogation of endpoints status changes

### ISSUE THREAD

**Issue by Purushotham233** [istio/istio#40820]
Before introducing istio in our stack, we had run into the sceanario explained https://github.com/kubernetes/kubernetes/issues/105617 and had introduced workaround to isolate work-loads from control-plane outages.

With istio the earlier work-arounds are not suitable any more and we trying to solve for the same scenario.  

**Describe the feature request**
A dynamic flag(without having to recreate istiod pods) when 
- enabled makes istiod to propogate not-ready endpoints to both new and existing proxies.
- disabled makes istiod to clear not-ready endpoints from existing proxies and stop using them for new proxies.

**Describe alternatives you've considered**
From our explorations, discovered istiod flag `PILOT_SEND_UNHEALTHY_ENDPOINTS` allows to consider not-ready endpoints. But it is an environment variable so enable/disable of the flag needs istiod to get recreated. This wont be an option when k8s control-plane is degraded.

**Affected product area (please put an X in all that apply)**
Not sure of the right classification here.
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I understand the use case but IMO the complexity and risk of dynamically changing flags is too high. Restarting Istiod is low cost.

Would it have helped in this specific obscure issue - probably. But its **so** niche and high risk that it doesn't seem compelling to me

**Comment by howardjohn** [comment]
^ was for dynamic flags.

If we want specifically a "panic mode" then that should be something that is configured to automatically apply IMO (at some threshold, etc); not a manual action
