### ISSUE TITLE
custom Eastwestgateway's gatewayIP 

### ISSUE THREAD

**Issue by supershll** [istio/istio#40846]
I know that eastwestgateway's gatewayPort default is 15443, and it can be customed by `networking.istio.io/gatewayPort` label  
why eastwestgateway's gatewayIP has no similiar way to do this?

My scenario is that I have two physical k8s clusters, and I can only expose services through `NodePort` .  At this time, I cannot set the IP of the physical node to externalIP , because this will cause the node to be inaccessible.
Maybe there are other scenarios, I think there should be a mode where the `gatewayIP` can be customized
[] Installation
[] Multi Cluster

**Comment by hzxuzhonghu** [comment]
What's your use case? Cannot be inferred from service lb IP?

**Comment by hzxuzhonghu** [comment]
Donot you have an lb to proxy cluster ingress traffic?

**Comment by supershll** [comment]
We'd better not expect what the user has to have?
Just like we don't expect the user to have to be able to set the `gatewayPort` to 15443 , right?

**Comment by hzxuzhonghu** [comment]
Nope, they have differences. We allow customizing port because fixed port may not work for VM deployed gw.

However, the IP address is already inferred from Node or Loadbalancer type service

**Comment by supershll** [comment]
> Nope, they have differences. We allow customizing port because fixed port may not work for VM deployed gw.
> 
> However, the IP address is already inferred from Node or Loadbalancer type service

My opinion is different, my opinion is: I can make an `IP:port ` point to the eastwestgateway **by any way** , and **this way should not be decided by Istio** .   Currently,  `port`  can be  customized , but `IP` can't, in my understanding, it's not free enough to do here

**Comment by boeboe** [comment]
Please re-open. The use case is obvious. If the VM cannot access the VM Gateway through the IP address defined in the service `status.loadBalancer.ingress.ip` field and set by the LB controller, the VM onboarding breaks.

**Scenarios:**

1. Lack of LoadBalancer integration, where people typically go for NodePort. This is common in on premises deployments.
2. A VMGateway LB IP that is not directly reachable from the VM (NAT, private LB behind another network device, etc). This is common in cloud deployments with private LBs.

**Comment by liuxuzxx** [comment]
Now I want to use Linkerd2 to communicate across k8s clusters. I see a service that supports the LoadBalance type. Is this a necessary condition? If the current cluster only supports the form of NodePort, is it also possible?
