### ISSUE TITLE
Questions about pilot discovery

### ISSUE THREAD

**Issue by GOVYANSONG** [istio/istio#40867]
I am trying to build a docker image for istio/pilot-discovery component and plans to run it with docker-compose. I want to know if:

1. pilot-discovery can be used outside the context of kubernetes?
2. if yes to #1, where can i find more info on how to set the options for pilot-discovery, mesh config, mesh networking etc.?

thanks.

**Comment by howardjohn** [comment]
It's very uncommon to run Istio entirely outside of Kubernetes without at least an api-server to store config. It is possible though: https://blog.howardjohn.info/posts/local-gateway/

**Comment by GOVYANSONG** [comment]
Instead of using latest image gcr.io/istio-testing/pilot:latest or istio/pilot:1.15.0-debug@sha256:0db0d47671b03387667d5bc8583dff59ccd64a6dd67b3641a319d6638e1e2eed, i switched to istio/pilot:1.14.3-debug, now pilot-discovery service started successfully.
