### ISSUE TITLE
Upstream `experimental-ambient` branches to `master`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#40879]
This issue tracks work needed to upstream ambient to the master branch. This issue will be completed once all ambient code is in `master` (across the various repos), but behind feature flags, and the `experimental-ambient` branches are retired.

**Plan of action**

We will port the branch to `master` in a series of a few large commits. This avoids 1 giant mega-commit that cannot be reviewed, but saves time completely decomposing things.

These will be roughly:
* [x] Ztunnel: its already its own repo, so minimal changes needed except to integrate with common infra. https://github.com/istio/test-infra/pull/4575
* [x] API: 1 PR for the new API additions. https://github.com/istio/api/pull/2674
* [x] Security: PR to introduce the new node authz controller: https://github.com/istio/istio/pull/43288
* [x] Ztunnel helm charts: PR to import, and minor operator changes required: https://github.com/istio/istio/pull/43365
* [x] Gateway API deployment controller: PR to import the changes to not use injection https://github.com/istio/istio/pull/43369
* [x] Tests: 1 PR to introduce ambient tests and associated test framework changes: https://github.com/istio/test-infra/pull/4580 https://github.com/istio/istio/pull/43405
* [x] CNI: 1 PR to merge in the new ambient redirection logic from the CNI: https://github.com/istio/istio/pull/43382
* [x] istioctl: 1 PR to merge in new istioctl commands https://github.com/istio/istio/pull/43409
* [x] XDS: 1 (large) PR to merge in the new controllers and XDS generation logic (part 1: https://github.com/istio/istio/pull/43414) part2: https://github.com/istio/istio/pull/43422

**Reviewer guide**

It is suggested that reviewers treat these PRs differently than normal, as the code has already been reviewed. PRs _should_ be thoroughly reviewed for risk to non-ambient users, ensuring any new/risky/expensive code is disabled by default. However, code quality comments, nit picks, or even bugs in ambient code should **not** block a merge; modifying these PRs will be high cost and lead to a 3-way drift from master, experimental-ambient, and the PR. Instead, these comments should be turned into issues to complete following the merge.

Release notes will not be added for any PR. Instead, they will be written holistically for the ambient feature in 1.18 at a later point.

**Comment by zirain** [comment]
link to https://github.com/istio/istio/issues/40973#issuecomment-1246294878

**Comment by zirain** [comment]
link to https://github.com/istio/istio/issues/41008#issuecomment-1248773554

**Comment by howardjohn** [comment]
I don't think we need to track every deficit in ambient here; the goal here is to get it merged behind a feature flag in `master`, not to solve all issues. Calico, IPv6, etc will not block upstreaming

**Comment by ramaraochavali** [comment]
As long as nothing gets executed unless we enable a flag - I think it is reasonable to upstream and iterate rather than having continuous back and forth merges.
