### ISSUE TITLE
SECRET_TTL rotation policy for DR scenarios

### ISSUE THREAD

**Issue by sathuish** [istio/istio#40872]
I've set the secret time limit to three days (SECRET_TTL=3d). It works perfectly in that the workload certificates are rotated after they expire; however, in DR testing scenarios, if the certificate was rotated two days ago and the master nodes are down today, we only have a one-day grace period, so the application will not be accessible if we are unable to bring the DC up within one day. Is it possible to rotate the certificate at regular intervals even if the certificate lifetime has not been reached?

For example, if I set SECRET TTL=3d, the workload certificate should be rotated every day and have a lifetime of three days from the time it was rotated.

client version: 1.9.5
control plane version: 1.12.4
data plane version: 1.12.4

**Comment by howardjohn** [comment]
Its already configured to renew at 50% of the lifetime

**Comment by sathuish** [comment]
But I have to rotate the certificate every day. Does SECRET_GRACE_DURATION work?

**Comment by howardjohn** [comment]
No, that has been removed.

**Comment by sathuish** [comment]
Thank you Howard
