### ISSUE TITLE
cross-eastwestgateway  TLS error 33554536

### ISSUE THREAD

**Issue by J-lena** [istio/istio#40891]
### Bug Description

Using istio's muticluster with different network , I deploy a helloworld-v1 in one cluster and helloworld-v2 in other cluster, and i  use virtualservice to control the traffic always to cluster1 . but i get errors like this

![image](https://user-images.githubusercontent.com/97420104/189265914-2c432698-336a-4552-8621-fbf024956d8a.png)

 here is my config. 
gateway
![image](https://user-images.githubusercontent.com/97420104/189265660-aa8a47b0-24b8-48ea-b5e3-1bfc873aab1f.png)
Virtualservice
![image](https://user-images.githubusercontent.com/97420104/189265771-d37d1329-73fa-4703-8b1d-b8e182164faf.png)
Destinationrule
![image](https://user-images.githubusercontent.com/97420104/189269613-a235af2d-180a-4602-90cb-b6cff27a1184.png)

### Version

```prose
client version: 1.12.4
control plane version: 1.12.4
data plane version: 1.12.4 (6 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
how did you install multicluster, especial how did install cacerts?

**Comment by J-lena** [comment]
> 
follow this guide to install. and two clusters share the same certs .
https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

if i remove the destination and virtualservice,  everything is fine, curl test is success

**Comment by zirain** [comment]
can you share the logs and config_dump from pod and eastwest-gateway?

**Comment by J-lena** [comment]
[gateway_config_dump.txt](https://github.com/istio/istio/files/9532443/gateway_config_dump.txt)
[curlpod_config_dump.txt](https://github.com/istio/istio/files/9532444/curlpod_config_dump.txt)
pod logs
![image](https://user-images.githubusercontent.com/97420104/189275716-fa970dbb-ad9b-4606-8df1-e1651a04a048.png)
eastwest-gateway logs
![image](https://user-images.githubusercontent.com/97420104/189275839-bb38782e-36e6-4777-96b0-acefd0791d2d.png)

**Comment by zirain** [comment]
do you have service helloworld.sample  in cluster1?

**Comment by zirain** [comment]
are you running a multi-primary demo?

**Comment by J-lena** [comment]
> are you running a multi-primary demo?

yes

**Comment by zirain** [comment]
I think you should apply vs and dr in both two clusters

**Comment by J-lena** [comment]
my client pod is in cluster one , why vr and dr is needed  in another cluster ? can you show me a example? thank you

**Comment by zirain** [comment]
cause you're running multi-primary

**Comment by zirain** [comment]
when apply dr/vs in cluster1, the traffic send to cluster2's eastwest gateway(which show no_filter_chain in accesslog).
