### ISSUE TITLE
Can't build istioctl for MacOS anymore

### ISSUE THREAD

**Issue by ajhall** [istio/istio#40890]
### Bug Description

When I run `BUILD_WITH_CONTAINER=0 make istioctl` on MacOS, the build quickly fails, saying:

```
Downloading envoy: https://github.com/istio/proxy/releases/download/1.0.2/istio-proxy-1.0.2-macos.tar.gz to /Users/andy.hall/Scratch/istio/out/darwin_arm64/release/envoy-1.0.2
curl: (22) The requested URL returned error: 404
```

I tried building https://github.com/istio/istio/tree/1.15.0 and the [current head of the `master` branch](https://github.com/istio/istio/commit/76ff6b45bcf8ada3dacd2a4fa8fa824a75afd694) and got the same result. This worked fine just a few days ago on [September 6th](https://github.com/macports/macports-ports/pull/15961/checks) when I submitted [an update to the MacPorts port](https://github.com/macports/macports-ports/pull/15961) of istioctl.

The problem is that https://github.com/istio/proxy/releases/download/1.0.2/istio-proxy-1.0.2-macos.tar.gz seems to be missing. I don't see any releases at all on [istio/proxy/releases](https://github.com/istio/proxy/releases), but I do see ([in the Wayback Machine](https://web.archive.org/web/20200916121147/https://github.com/istio/proxy/releases/tag/1.0.2)) that there used to be a 1.0.2 release that had that file. The [live version of that same link](https://github.com/istio/proxy/releases/tag/1.0.2) is just a tagged commit with no file attached.

## Build logs
```
$ BUILD_WITH_CONTAINER=0 make istioctl
TARGET_OUT=/Users/andy.hall/Scratch/istio/out/darwin_arm64 ISTIO_BIN=/Users/andy.hall/go/bin GOOS_LOCAL=darwin bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
Skipping envoy debug. Set DEBUG_IMAGE to download.
~/Scratch/istio/out/linux_arm64/release ~/Scratch/istio
Downloading envoy: https://storage.googleapis.com/istio-build/proxy/envoy-alpha-d81804c50e60d7ae17f3802006d76c24c98f2c5f-arm64.tar.gz to /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy-d81804c50e60d7ae17f3802006d76c24c98f2c5f

real    0m1.577s
user    0m0.566s
sys     0m0.124s
Copying /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy-d81804c50e60d7ae17f3802006d76c24c98f2c5f to /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy
~/Scratch/istio
~/Scratch/istio/out/linux_arm64/release ~/Scratch/istio
Downloading envoy: https://storage.googleapis.com/istio-build/proxy/envoy-centos-alpha-d81804c50e60d7ae17f3802006d76c24c98f2c5f.tar.gz to /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy-centos-d81804c50e60d7ae17f3802006d76c24c98f2c5f

real    0m1.563s
user    0m0.509s
sys     0m0.106s
Copying /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy-centos-d81804c50e60d7ae17f3802006d76c24c98f2c5f to /Users/andy.hall/Scratch/istio/out/linux_arm64/release/envoy-centos
~/Scratch/istio
~/Scratch/istio/out/darwin_arm64/release ~/Scratch/istio
Downloading envoy: https://github.com/istio/proxy/releases/download/1.0.2/istio-proxy-1.0.2-macos.tar.gz to /Users/andy.hall/Scratch/istio/out/darwin_arm64/release/envoy-1.0.2
curl: (22) The requested URL returned error: 404
Unexpected failure
make: *** [/Users/andy.hall/Scratch/istio/out/darwin_arm64/istio_is_init] Error 1
```

### Version

```prose
Attempted:
https://github.com/istio/istio/tree/1.15.0
https://github.com/istio/istio/commit/76ff6b45bcf8ada3dacd2a4fa8fa824a75afd694
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
actually, we never release proxy binary for macos, can you try without `BUILD_WITH_CONTAINER=0 ` ?

**Comment by ajhall** [comment]
It fails the same way if I leave `BUILD_WITH_CONTAINER` unset:
```
$ TAG=1.15.0 VERSION=1.15.0 make istioctl
fatal: detected dubious ownership in repository at '/work'
To add an exception for this directory, call:

        git config --global --add safe.directory /work
TARGET_OUT=/work/out/darwin_arm64 ISTIO_BIN=/gobin GOOS_LOCAL=darwin bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
Skipping envoy debug. Set DEBUG_IMAGE to download.
/work/out/darwin_arm64/release /work
Downloading envoy: https://github.com/istio/proxy/releases/download/1.0.2/istio-proxy-1.0.2-macos.tar.gz to /work/out/darwin_arm64/release/envoy-1.0.2
curl: (22) The requested URL returned error: 404

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

real    0m0.219s
user    0m0.044s
sys     0m0.006s
Unexpected failure
make[1]: *** [Makefile.core.mk:160: /work/out/darwin_arm64/istio_is_init] Error 1
make: *** [istioctl] Error 2
```

Here are the lines in init.sh that reference this URL:
https://github.com/istio/istio/blob/a7ff324b9979e02eb9049004eefd9d5776ae0ce2/bin/init.sh#L70-L71
https://github.com/istio/istio/blob/a7ff324b9979e02eb9049004eefd9d5776ae0ce2/bin/init.sh#L177-L180

**Comment by zirain** [comment]
cc @ericvn

**Comment by ericvn** [comment]
I can recreate. Will have to figure out why the release is no longer there. @howardjohn may have some ideas.

**Comment by ericvn** [comment]
This binary predates my involvement, and I believe there are later Mac binaries being built we might be able to use instead.

**Comment by howardjohn** [comment]
Did running with envoy-1.0.2 ever really work? That is like years old...

**Comment by ericvn** [comment]
I don't think anyone actually ran the binary that was downloaded, at least I didn't. It's just a needed dependency for the build and they pulled in an old one (was likely current at the time). I suspect that any binary would do.

**Comment by ericvn** [comment]
As far as I can tell, there is a way to install a current binary on the Mac using `brew` but that probably isn't easy to do within the make file.  If we can't respect the release binary, what about placing a copy in gcs somewhere that we can curl instead of the proxy release tar. We could add automation to try and keep it up to date with what's in `brew` or likely we just need a copy we can download and up to date doesn't matter (we had been using 1.0.2).

**Comment by howardjohn** [comment]
If its not istio-proxy envoy from `master` it seems not useful? Since it
won't run istio?

 Does it even run? Can we just replace it with an empty file?

**Comment by ajhall** [comment]
I did notice while I was troubleshooting this that I could just plug in some other URL or comment out parts of `init.sh` and the rest of the build would run fine. I was only focused on building `istioctl`, though, and I don't have any context for why that binary was ever necessary in the output of the Mac build.

**Comment by ericvn** [comment]
istioctl doesn't need the envoy binary for building, so commenting out the download would be fine.

I'm not sure that the binary is actually used for anything useful and a simple empty binary would likely suffix.

**Comment by zirain** [comment]
Only istioctl should be build for macos, `pilot-agent` and `pilot-discovery` should build for linux(their will be used for docker image)

**Comment by ericvn** [comment]
At one point, people ran the binaries on their Macs AFAIK. We do build Linux flavors of the various binaries on the Mac to support building Linux container images.

**Comment by ericvn** [comment]
So #40912 (and cherry-picks) should fix this issue in the 1.13+ release branches. The quick work-around s to just use the Linux Istio built Envoy binary as a place holder. A further change could be to use a passed in `ISTIO_ENVOY_NATIVE_PATH` which points to a `brew` installed Envoy binary. It still isn't the Istio built version, but some things might work better.

**Comment by ajhall** [comment]
Thanks! I was able to build 1.15 after applying the patch from #40912.

**Comment by ericvn** [comment]
Since 1.12 is EOL, I don't think we would cut a new release there, and that's why I didn't cherry-pick the fix to that branch. 1.13 and 1.14 just had patch versions released so I would expect another in 3-4 weeks (1.13 should just before it goes EOL).
