### ISSUE TITLE
Got error running ambient demo 

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#40900]
### Bug Description

I’m following this guide(https://istio.io/latest/blog/2022/get-started-ambient/) to try ambient mode. But got the below error:

kubectl exec deploy/sleep -- curl -s http://istio-ingressgateway.istio-system/productpage
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 22%

There're warning in ztunnel log:
  ~ k -n istio-system logs ztunnel-xsxt6 --tail 2
Defaulted container “istio-proxy” out of: istio-proxy, istio-init (init)
2022-09-09T16:06:12.503951Z	warning	envoy config	StreamSecrets gRPC config stream to sds-grpc closed: 2, failed to generate secret for spiffe://cluster.local/ns/default/sa/bookinfo-ratings~ratings-v1-754f9c4975-lwm8h~5c874f24-6836-446b-97e2-7bb58eb8dbbe: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: fetch platform credential: could not create a token for spiffe://cluster.local/ns/default/sa/bookinfo-ratings/&BoundObjectReference{Kind:Pod,APIVersion:v1,Name:ratings-v1-754f9c4975-lwm8h,UID:5c874f24-6836-446b-97e2-7bb58eb8dbbe,}: serviceaccounts “bookinfo-ratings” is forbidden: User “system:serviceaccount:istio-system:ztunnel” cannot create resource “serviceaccounts/token” in API group “” in the namespace “default”
2022-09-09T16:06:12.503704Z	info	ads	ADS: “@” ztunnel-xsxt6.istio-system-681 terminated

All ambient components are up and running:

➜  ~ k -n istio-system get pod
NAME                                    READY   STATUS    RESTARTS   AGE
istio-cni-node-7nnns                    1/1     Running   0          33m
istio-cni-node-9blbb                    1/1     Running   0          33m
istio-cni-node-mjxfg                    1/1     Running   0          33m
istio-ingressgateway-6d84bf949c-75h87   1/1     Running   0          33m
istiod-546f8d6f66-v5rxv                 1/1     Running   0          34m
ztunnel-9d57r                           1/1     Running   0          34m
ztunnel-fvpjx                           1/1     Running   0          34m
ztunnel-txth2                           1/1     Running   0          34m
➜  ~ k get pod
NAME                                                  READY   STATUS    RESTARTS   AGE
bookinfo-productpage-waypoint-proxy-5964bdd4b-jgcqx   1/1     Running   0          11m
details-v1-7d88846999-zckgp                           1/1     Running   0          21m
kubernetes-proxy-75bf6fbbcb-cxvhx                     1/1     Running   0          80m
kubernetes-proxy-75bf6fbbcb-pqcxl                     1/1     Running   0          78m
notsleep-7b574d696b-mrj6f                             1/1     Running   0          50m
productpage-v1-5f578dd9b7-tpnpp                       1/1     Running   0          21m
ratings-v1-754f9c4975-lwm8h                           1/1     Running   0          21m
reviews-v1-69865ff55-lj5sp                            1/1     Running   0          21m
reviews-v2-789d584fbf-qbrxv                           1/1     Running   0          21m
reviews-v3-64f8b69f99-t9529                           1/1     Running   0          21m
sleep-7fbb55b6f5-q65sx                                1/1     Running   0          50m
➜  ~ k get gw
NAME               AGE
bookinfo-gateway   22m
➜  ~ k get vs
NAME       GATEWAYS               HOSTS   AGE
bookinfo   [“bookinfo-gateway”]   [“*”]   23m

### Version

```prose
➜  ~ istioctl version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (4 proxies)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
What environment? is it on kind?

**Comment by zhaohuabing** [comment]
No, it's a standard k8s

➜  ~ kubectl version -oyaml
clientVersion:
  buildDate: "2022-05-03T13:46:05Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-04-19T03:56:15Z"
  compiler: gc
  gitCommit: 79b517faeb244730136bef57c694da493a413bf9
  gitTreeState: clean
  gitVersion: v1.22.5-tke.1
  goVersion: go1.16.15
  major: "1"
  minor: 22+
  platform: linux/amd64

WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

**Comment by zhaohuabing** [comment]
kubelet location and command parameters:
ubuntu@VM-1-16-ubuntu:~$ ps -ef |grep kubelet
root       14829       1  2 Sep09 ?        00:16:41 /usr/bin/kubelet --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/cluster-ca.crt --cloud-config=/etc/kubernetes/qcloud.conf --cloud-provider=external --cluster-dns=172.16.253.175 --cluster-domain=cluster.local --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --eviction-hard=nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,memory.available<100Mi --fail-swap-on=false --feature-gates=CSIMigration=true,CSIMigrationQcloudCbs=true --hostname-override=10.0.1.16 --image-pull-progress-deadline=10m0s --kube-reserved=cpu=100m,memory=1024Mi --kubeconfig=/etc/kubernetes/kubelet-kubeconfig --max-pods=61 --network-plugin=cni --non-masquerade-cidr=0.0.0.0/0 --pod-infra-container-image=uswccr.ccs.tencentyun.com/library/pause:latest --provider-id=qcloud:///150001/ins-okrqu3ay --read-only-port=0 --register-schedulable=true --register-with-taints=tke.cloud.tencent.com/uninitialized=true:NoSchedule --runtime-request-timeout=15m --serialize-image-pulls=false --v=2

**Comment by cobb-tx** [comment]
me too. i tested this demo in minikube

**Comment by zhaohuabing** [comment]
The easiest way to run ambient is a kind cluster in an Ubuntu host. I've
already got it running.

**Comment by tragiclifestories** [comment]
can this be reopened? I'm trying to test this against a run-of-the-mill k8s cluster running in a cloud service (digitalocean if that matters, their managed offering). I get the same error in the `kubectl exec` calls (`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 22`) but I can't see any warnings in the ztunnel logs - it seems to have happily created the spiffe stuff.

**Comment by tragiclifestories** [comment]
```yaml
clientVersion:
  buildDate: "2022-09-21T14:25:45Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-08-17T18:47:37Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: linux/amd64

```

**Comment by tragiclifestories** [comment]
And in fact I notice that the error only occurs when hitting the product page through the ingress gateway host:

```sh
kubectl exec deploy/sleep -- curl -s http://istio-ingressgateway.istio-system/productpage | head -n1
```

But there's no error output in the ingress gateway logs either.
