### ISSUE TITLE
IPv6: Envoy bootstrap template JSON file

### ISSUE THREAD

**Issue by pmichali** [istio/istio#4098]
The tools/deb/envoy_bootstrap_tmpl.json file contains the IPv4 localhost address (127.0.0.1). For IPv6, this needs to be "::1".  More importantly, a mechanism is needed to allow this to be configurable, based on whether the cluster is running in IPv4 or IPv6 mode.

Note: this affects three golden master files in tests.

**Comment by john-a-joyce** [comment]
We hope to ask new Istio developers to start working on this shortly, but also open to anyone else via the help wanted label.
