### ISSUE TITLE
EKS Pod Identity is not working when holdApplicationUntilProxyStarts is enabled 

### ISSUE THREAD

**Issue by abebars** [istio/istio#40993]
### Bug Description

When `holdApplicationUntilProxyStarts` is set to `true` we notice that containers can't start, and the replica controller is erroring out reading the Service Token, which is handled by https://github.com/aws/amazon-eks-pod-identity-webhook

```replicaset-controller  Error creating: Pod "test-75b47b98d9-hfdhm" is invalid: [spec.containers[2].volumeMounts[2].mountPath: Invalid value: "/var/run/secrets/eks.amazonaws.com/serviceaccount": must be unique, spec.initCo │
│ ntainers[0].volumeMounts[2].mountPath: Invalid value: "/var/run/secrets/eks.amazonaws.com/serviceaccount": must be unique]
```

Once `holdApplicationUntilProxyStarts` is set to `false` , the pods are starting as expected. Did anyone see something like this before?

### Version

```prose
$ istioctl version                                                                                                                                                                                  
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (22 proxies)
$ kubectl version --short                                                                                                                                                                           
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.22.11-eks-18ef993
```

**Comment by howardjohn** [comment]
I think its a bug in the AWS webhook would be my first guess. It probably incorrectly inserts the same thing 2x

**Comment by abebars** [comment]
> I think its a bug in the AWS webhook would be my first guess. It probably incorrectly inserts the same thing 2x

Thanks, Just linked an issue there as well; looking to get more understanding on how to prevent this from happening

**Comment by infa-ddeore** [comment]
we have same issue for some k8 pods only, any known fix for this available?
