### ISSUE TITLE
IPv6: Envoy Pilot JSON

### ISSUE THREAD

**Issue by pmichali** [istio/istio#4099]
The pilot/docker/envoy_pilot.json file sets the localhost address to 127.0.0.1, and any address to 0.0.0.0. For IPv6, these need to be [::1] and [::], respectively. More importantly, there needs to be a way to make this configurable, based on whether the cluster is operating in IPv4 or IPv6 mode.

**Comment by tiswanso** [comment]
marking this not stale since it's still an issue
