### ISSUE TITLE
dotvix fails when application name has `-` in it

### ISSUE THREAD

**Issue by debianmaster** [istio/istio#410]
when you have `-`  in  application name Ex:-   `product-page` instead of `productpage`  dotviz fails to load with a javascript error.

**Comment by ldemailly** [comment]
I suppose we can somehow escape app name and aren't (or it's a bug in dotvix)

**Comment by debianmaster** [comment]
@ldemailly is this handled in 0.2 by any chance?

**Comment by ldemailly** [comment]
sorry I don't know - but please test it/find out and ideally fix it or give details if it still doesn't work
