### ISSUE TITLE
IPv6: Wildcard and localhost constants

### ISSUE THREAD

**Issue by pmichali** [istio/istio#4100]
In pilot/pkg/proxy/envoy/v1/resources.go the constants for WIldcardAddress and LocalhostAddress are set to 0.0.0.0 and 127.0.0.1, respectively. For IPv6, these need to be [::] and [::1], respectively.

More importantly, the selection should be configurable based on whether the cluster is operating in IPv4 or IPv6 mode.

Note: this affects numerous golden master files for unit tests.

**Comment by spikecurtis** [comment]
It is extremely desirable to not make the operator configure IPv6 support explicitly.

For example, if WildcardAddress is used to bind, binding to [::] on Linux will also accept IPv4 connections.

**Comment by pmichali** [comment]
> On Mar 9, 2018, at 1:09 PM, Spike Curtis <notifications@github.com> wrote:
> 
> It is extremely desirable to not make the operator configure IPv6 support explicitly.
> 
> 
Absolutely! I was hoping there would be a way to infer the IP mode and then configure these settings implicitly, and not by having a knob to select the mode.


> For example, if WildcardAddress is used to bind, binding to [::] on Linux will also accept IPv4 connections.
> 
> 
If IPv6 addresses will work for IPv4 as well, then that would be great.

I guess we need to verify that, both with IPv6 address for any address and local host, and for configurations where the user does not have IPv6 enabled on the host (sysctl).

Regards,

PCM

**Comment by pmichali** [comment]
Two concerns to consider...

If IPv6 is not configured on the system, I'm guessing that using IPv6 addresses will fail.

Kubernetes currently infers the IP mode from the cluster CIDR and API address, however, once we get to dual-stack, that will no longer work and I suspect some form of "IP mode" configuration would be needed.

**Comment by spikecurtis** [comment]
I think the answer here depends on what these constants are being used for. This might require chasing through code paths. I think in most cases, we can handle v4 and v6 simultaneously. This helps future proof systems for dual stack.

For example, if they're being used to bind sockets, we might try binding both v6 and v4. As long as at least one succeeds, we assume success and carry on. (But log failure at WARN level?)

Validating that the source of a connection is local? Check both v4 and v6 cases.

etc.

**Comment by john-a-joyce** [comment]
We hope to ask new Istio developers to start working on this shortly, but also open to anyone else via the help wanted label.
