### ISSUE TITLE
Readiness probe failed when auto injected an sidecar and opened mtls STRICT mode

### ISSUE THREAD

**Issue by saoDiSengTank** [istio/istio#41010]
### Bug Description

I am trying to open mtls for my pods, but after mtls set to STRCT, my pod start failed, so i checked the pod start flow and found out that , the ReadinessProbe failed , then the container crashed off.

I googled that and confirmed the reason , that is Kubelet probes request will be rejected if the istio proxy sidecar is injected into the POD and mTLS is enabled because kubelet is not part of the service mesh and does not have a TLS certificate accepted by istio proxy.

At the same time , i got some solutions :
1. Disable mTLS for the health probe port.
2. Use a Liveness Command Instead.
3. Disable liveness probes.
But to be honest, none of them is a good fit for me.

Do we have some other solutions ?

### Version

```prose
istioctl version
  client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
  control plane version: 0.0.0
  data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (1 proxies)
```

**Comment by howardjohn** [comment]
I think there is some confusion here... are you intentionally using ambient mesh (an extremely experimental work in progress feature)? Since you mentioned sidecars I am a bit confused.

Anyhow what you read in Google is not quite accurate, see https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/

**Comment by saoDiSengTank** [comment]
Hi @howardjohn , thanks for your response and your link is very helpful for me.
I followed the steps and finally fixed most of my issues except below one scenario .
1. At first , i use rewriteAppHTTPProbers annotation to rewrite the probe path.
<img width="493" alt="Screen Shot 2022-09-26 at 14 38 09" src="https://user-images.githubusercontent.com/102742059/192209302-ebcc5cd1-a31a-4109-b8a8-d3e6f4fc7d8d.png">
2. Then my HTTP probe path switched .
Before :
<img width="379" alt="Screen Shot 2022-09-26 at 14 39 50" src="https://user-images.githubusercontent.com/102742059/192209666-0b4d1fb5-cc38-455d-8b2c-b0e0e395b737.png">
After:
<img width="420" alt="Screen Shot 2022-09-26 at 14 40 15" src="https://user-images.githubusercontent.com/102742059/192209695-74c8e931-c954-4e23-b8c0-ba6f64ac32d6.png">
It made my probe check succeed and there is no problem.
4. Issue scenario.
    But at the same time , i used some labels which used to auto-inject another image that also using readinessProbe and livenessProbe.
Labels used to inject container:
<img width="482" alt="Screen Shot 2022-09-26 at 14 50 31" src="https://user-images.githubusercontent.com/102742059/192211471-55a9dea2-ef96-4812-8c4e-5bd30157c415.png">
   After my pod stared , the label contexts framed will be detected and a new image will be injected .

The readinessProbe and livenessProbe in new image.
<img width="420" alt="Screen Shot 2022-09-26 at 14 40 15" src="https://user-images.githubusercontent.com/102742059/192210565-0aec95e4-702e-4fda-b415-f924cdae6fdf.png">

Both of the two Probes are not rewritten like screenshot 2 and 3 shows.

I not sure if i missed some configurations ?

**Comment by howardjohn** [comment]
You are using ambient mesh though. 

1. Ambient mesh is a highly experimental prototype. Don't use it other than for experiments.
2. Ambient mesh doesn't do probe rewrites

**Comment by saoDiSengTank** [comment]
Hi @howardjohn 
If i am using Ambient mesh that does't do probe rewrites , why is the probe i added in deployment(not injected) be rewrote? But the probes injected from outside remains unchanged ?

**Comment by saoDiSengTank** [comment]
Hi @howardjohn , i just checked the order of them and confirmed that the probes are injected after istio .
Thank you very much!
