### ISSUE TITLE
IPv6: Bookinfo sample app

### ISSUE THREAD

**Issue by pmichali** [istio/istio#4101]
This sample app uses 0.0.0.0 as the bind address. For IPv6, this needs to be "::". The setting should be configurable, based on whether the cluster is operating in IPv4 or IPv6 mode.

It also would be nice to enhance build_push_update_images.sh so that it can push to a different docker registry for development work, instead of docker.io/istio.

**Comment by john-a-joyce** [comment]
We hope to ask new Istio developers to start working on this shortly, but also open to anyone else via the help wanted label.
