### ISSUE TITLE
Istio external authorization with envoyExtAuthzHttp returns 403 when http server pod is deleted or created

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [istio/istio#41023]
### Bug Description

Istio external authorization with `envoyExtAuthzHttp` returns 403 when http server pod is deleted or created. We have configured `CUSTOM` `AuthorizationPolicy` with http server added to envoyExtAuthzHttp under extension providers in mesh config. The server itself is a deployment running behind a service. This setup works as expected. However, during continuous load if any of the http server pods are scaled up or down, we start seeing 403 errors. Correspondingly also found `downstream_remote_disconnect` errors in istio ingress gateway rbac logs. http server has the right readiness probe and terminationduration defined. Any pointers of what the issue is and how to debug this further?

### Version

```prose
istioctl version
client version: 1.12.2
control plane version: 1.13.4
data plane version: 1.13.4 (22 proxies)
kubectl version --short
Client Version: v1.22.2
Server Version: v1.24.0
```

**Comment by vaibhavkumbhar1** [comment]
@SoujanyaMangipudi  did you find any solution for the above issue?
