### ISSUE TITLE
Where are numTrustedProxies stored in istio resource?

### ISSUE THREAD

**Issue by tan5o** [istio/istio#41024]
[In the official documentation](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#example-using-x-forwarded-for-capability-with-httpbin), you can find the following manifest and command to set numTrustedProxies using IstioOperator.

```
$ cat <<EOF > topology.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
EOF
$ istioctl install -f topology.yaml
```

It is important to understand how cloud server maintenance and operations can be affected.
I have investigated what effect on k8s resource the above istioctl install operation causes.
However, the result of the investigation was only a change in IstioOperator annotation, and no change was observed before or after istioctl install.

So, I have two questions.

* What annotations on pods and deployments are affected if I set numTrustedProxies and istioctl install?
* After setting numTrustedProxies, what is the best process to revert back to the situation before setting them (i.e., to a situation without numTrustedProxies)?

Best regards.

**Comment by howardjohn** [comment]
Its the `istio` configmap.

> After setting numTrustedProxies, what is the best process to revert back to the situation before setting them (i.e., to a situation without numTrustedProxies)?

`istioctl install` is declarative, so the approach should be to run the same install but without it set

**Comment by tan5o** [comment]
@howardjohn 

Thank you for your reply!

Finally I found it! Thank you so much.

```
kubectl edit configmap istio -n istio-system

piVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      gatewayTopology:
        numTrustedProxies: 2
```

I am more familiar with istio. Thank you very much.

I note my understanding. Is the following understanding correct?

* The numTrustedProxies stored in istio's ConfigMap is given to the ingressgateway when the ingressgateway is built ([by this code](https://github.com/istio/istio/blob/ec750d5d1e7127bb69feca899b60eb1d2071023e/pilot/pkg/networking/core/v1alpha3/gateway.go#L622)), so when the numTrustedProxies is updated, the ingressgateway must also be restarted.

*  The ingressgateway specifies the location of trusted IPs in the X-forwarded-for by passing numTrustedProxies to the envoy filter xff_num_trusted_hops. (by [this code](https://github.com/istio/istio/blob/f8baff38c9b4129c0a6a1b24e31881f90a2c11e6/pilot/pkg/xds/lds.go#L78) and [this code](https://github.com/envoyproxy/envoy/blob/a06001ce26a3ebbcb4c861d4fd94fe7267a2ac07/source/common/http/utility.cc#L660))

Best, regards.

**Comment by howardjohn** [comment]
Yep, you got it

**Comment by tan5o** [comment]
Thank you very much!
It was interesting to learn more about istio.
I will close the issue now that it is resolved.

Best regards,

**Comment by vitalii-buchyn-exa** [comment]
Hello community,

Sorry for a postmortem question, but i wonder if setting `numTrustedProxies` spec affects a `use_remote_address` parameter for `http_connection_manager`, since in the [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for) it says `use_remote_address` should be set to true and we do set it to true in envoyfilter

Thank you!

**Comment by ramaraochavali** [comment]
Yes. For gateway `use_remote_address` is set to true
