### ISSUE TITLE
IPv6: Helloworld sample app

### ISSUE THREAD

**Issue by pmichali** [istio/istio#4102]
This app binds to address 0.0.0.0. For IPv6, this needs to bind to "::". More importantly, this should be configurable, based on whether the cluster is operating in IPv4 or IPv6 mode.

**Comment by ldemailly** [comment]
we could replace it by fortio which has bind address options

**Comment by john-a-joyce** [comment]
We hope to ask new Istio developers to start working on this shortly, but also open to anyone else via the help wanted label.

**Comment by ldemailly** [comment]
for reference on how to change port binding addr with fortio:

https://github.com/fortio/fortio#change-the-port--binding-address
https://github.com/fortio/fortio#using-the-tcp-proxy-servers-feature
