### ISSUE TITLE
Ingress-nginx and istio with TCP connections

### ISSUE THREAD

**Issue by aleshaczech** [istio/istio#41033]
Hi,

I am using `ingress-nginx` v1.3.0 (installed with Helm chart v4.2.3) as a load balancer on DigitalOcean's Kubernetes. In the Kubernetes cluster, I am running `istio` v1.15.0 service mesh. The mesh runs with peer authentication mTLS mode set to "STRICT".

I was able to successfully connect nginx with istio service mesh for HTTP/HTTPS traffic, but I didn't find a way how to do the same for TCP traffic.

nginx by defaults sends all traffic directly to the K8s pods (Pod IP/port), which leads to downstream Envoy sending the traffic to the upstream pod through the `PassthroughCluster`. The traffic is captured by the upstream Envoy, however, it's not mTLS encrypted and upstream Envoy will drop the traffic:

> [2022-09-17T19:28:09.649Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.0.175:9000 10.244.2.246:44402 - -

A simple visualisation would be like this:

```
<nginx> -> <downstream envoy> -> [pod ip] -> <upstream envoy> -> (traffic dropped, filter_chain_not_found)
```

Using annotations and a few `Host` header tweaks (as described in [an issue I opened in the ingress-nginx project](https://github.com/kubernetes/ingress-nginx/issues/9060)), it's possible to convince nginx to use the K8s services endpoints for the traffic, which works well with istio/Envoy:

```
<nginx> -> <downstream envoy> -> [service ip] -> <k8s service> -> <upstream envoy> -> <target pod>
```

I wasn't, however, able to find similar solution for TCP traffic. In `ingress-nginx` configuration, TCP routing is not defined in an `Ingress` object, therefore it's not possible to use the aforementioned annotations. According to one of the replies in https://github.com/kubernetes/ingress-nginx/issues/9060, such configuration indeed is not possible.

Given that nginx will always send the TCP traffic to the pod IP, I was trying to find a solution on istio side, namely to convince istio to encrypt the traffic even when nginx connects directly to the pod. This would be the desired state:

```
<nginx> -> <downstream envoy> -> [pod ip] -> <upstream envoy> -> <target pod>
```

I tried `ServiceEntry`, but so far to no success (but I am no expert in istio, it's possible that I have not found the right way). Is there any way how to achieve the desired encryption pod-pod?

I think my request might be related to https://github.com/istio/istio/issues/3398.

Thank you!

**Comment by howardjohn** [comment]
The only way to do this is to create a headless service for the `target pod`. This results in Istio creating a listener per-pod IP (which is really expensive!).

Or follow https://github.com/istio/istio/issues/36596 which will make this work automatically (but it is a ways off)
