### ISSUE TITLE
Need more contextual attributes to distinguish calling contexts

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#4103]
Scenarios:
- `client` v. `server` (for client-side checks/reports)
- `ingress` v. `in-mesh` (v. `egress`)

cc: @geeknoid @mandarjog

**Comment by douglas-reid** [comment]
@kyessenov think we are in a position to close this out now?

**Comment by kyessenov** [comment]
Done using `context.reporter.local` boolean.
