### ISSUE TITLE
TerminationDrainDuration can't be set less than 1s

### ISSUE THREAD

**Issue by fatedier** [istio/istio#41046]
### Bug Description

Update `meshConfig.defaultConfig.terminationDrainDuration = 500ms`

Check injected env `PROXY_CONFIG`:

```
"terminationDrainDuration\":\"5.500s\"
```

Got the incorrect value.

I think the releated code is https://github.com/istio/istio/blob/master/pilot/pkg/model/proxy_config.go#L136

`proto.Merge` merge two durations with `Seconds` and `Nanos` separately.

### Version

```prose
latest version
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
this seems due to proto merge stuff
IIRC, @howardjohn know more

**Comment by ramaraochavali** [comment]
We have to use `[merge.Merge()](https://github.com/istio/istio/blob/master/pkg/proto/merge/merge.go#L66)` instead of `proto.Merge` to handle duration merge properly.
