### ISSUE TITLE
Add podLabels to Gateway Helm Chart

### ISSUE THREAD

**Issue by blhagadorn** [istio/istio#41057]
**Describe the feature request**

Add podLabels to Gateway Helm chart, for just adding labels to the pods (not the Deployment)

**Describe alternatives you've considered**

Kustomize, forking the chart

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

The gateway helm chart doesn't expose `podLabels` like `istiod` does:

Gateway:
https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml

IstioD:
https://github.com/istio/istio/blob/9ff1e2a02722f013d5ec063bd27459a78acef711/manifests/charts/istio-control/istio-discovery/values.yaml#L71
https://github.com/istio/istio/blob/9ff1e2a02722f013d5ec063bd27459a78acef711/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L47-L49

**Comment by blhagadorn** [comment]
That's definitely one way to do it, would it be okay to add to the helm chart as well?

**Comment by blhagadorn** [comment]
Since it's already in the other helm chart, I think it would bring parity by adding it to the helm chart. What do you think?

**Comment by afk42** [comment]
Hi,
May I ask why this wasn't accepted and merged into the project?
This is some feature that I could really use since I need to add these podLabels due to some internal implementations which I have no control over and we are not currently using Kustomize.
As refereed, this type of configuration is already possible on istio-discovery, so is it also possible to have the same here?

Thanks.

**Comment by magdalenakuhn** [comment]
> Hi @blhagadorn , May I ask why this wasn't accepted and merged into the project? This is some feature that I could really use since I need to add these podLabels due to some internal implementations which I have no control over and we are not currently using Kustomize. As refereed, this type of configuration is already possible on istio-discovery, so is it also possible to have the same here?
> 
> Thanks.

Having the same issue! Is there any chance we can expose podLabels as value?
