### ISSUE TITLE
istioctl generates segment violation when parsing proxy.istio.io/config of grpc-echo sample

### ISSUE THREAD

**Issue by intel-dlanders** [istio/istio#41059]
### Bug Description

After starting kubernetes and installing istio 1.15.0 via istioctl, I attempt to [work through the grpc-echo sample](https://istio.io/latest/blog/2021/proxyless-grpc/#deploy-the-application). After creating the name space, I attempt to manually inject istio using istioctl but a SIGSEGV is generated.

\# istioctl kube-inject -f istio-1.15.0/samples/grpc-echo/grpc-echo.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo-grpc
  labels:
    app: echo
spec:
  selector:
    app: echo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 18080
  - name: grpc
    port: 7070
    targetPort: 17070
  - name: tcp
    port: 9090
    targetPort: 19090
\---
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x242f742]

goroutine 1 [running]:
istio.io/istio/pkg/config/mesh.ApplyProxyConfig({0xc000e7aff0, 0x2b}, 0x3360398?)
        istio.io/istio/pkg/config/mesh/mesh.go:144 +0x42
istio.io/istio/pkg/kube/inject.IntoObject({0x394bc60, 0xc0006e3020}, 0xc0006e32f0, {{0x0?, 0xc0006e38f0?}, 0xc0002cbb00?, 0xc0006e3740?}, {0x0, 0x0}, 0x0, ...)
        istio.io/istio/pkg/kube/inject/inject.go:749 +0xb2d
istio.io/istio/pkg/kube/inject.IntoResourceFile({0x394bc60, 0xc0006e3020}, 0xc0015e2200?, {{0x0?, 0xc001dbfba0?}, 0xc0002cbb00?, 0xc0006e3740?}, {0x0, 0x0}, 0x0, ...)
        istio.io/istio/pkg/kube/inject/inject.go:561 +0x387
istio.io/istio/istioctl/cmd.injectCommand.func1(0xc000f71b80?, {0xc000be2560?, 0x0?, 0x2?})
        istio.io/istio/istioctl/cmd/kubeinject.go:619 +0x468
github.com/spf13/cobra.(*Command).execute(0xc000f71b80, {0xc000be2540, 0x2, 0x2})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f71900)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd

github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xdc

[grpc-echo.yaml.txt](https://github.com/istio/istio/files/9602691/grpc-echo.yaml.txt)

### Version

```prose
# istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (2 proxies)
# kubectl version --short
Client Version: v1.22.12
Server Version: v1.22.14
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9602694/bug-report.tar.gz)
[grpc-echo.yaml.txt](https://github.com/istio/istio/files/9602717/grpc-echo.yaml.txt)

**Comment by my-git9** [comment]
It looks like it's because of these two lines:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/76980726/191143245-544a4a9f-fe81-4f61-87d5-d2f7be868737.png">

**Comment by hanxiaop** [comment]
This will be fixed when https://github.com/istio/istio/pull/40778 get merged.

**Comment by intel-dlanders** [comment]
So, while I wait for this fix to get merged, is there a workaround? If the issue is a null meshConfig, can I create a simple meshConfig that will allow the code to work? What would that look like?
Thanks
