### ISSUE TITLE
Ingress gateway ignores new endpoins

### ISSUE THREAD

**Issue by fl64** [istio/istio#41050]
### Bug Description

**Initial Condition:**
Two clusters with the same cluster.local domain. The clusters have isito v1.13.7 installed. Multicluster has been configured.
Cluster A has a prober, which periodically accesses the echo service in cluster B.
Cluster B has an echo service consisting of two replicas.

**The problem:** when new endpoints are added, traffic is not routed to them from the pod istio ingress gateway.

**Order of reproduction of the problem:**
1. We deploy the echo app. All requests form prober to echo app are evenly distributed between pods by istio ingress gateway(Figure 1)
![istio-gw-1](https://user-images.githubusercontent.com/2950658/191019075-8c87ee86-7408-4b1f-9098-e90946e3b2df.jpg)
**Figure 1.**
2. Let’s delete the echo-aaa pod. A new pod echo-ccc will be created. The list of endpoints on the istio ingress gateway will be updated. But the traffic only goes to the echo-bbb pod (Figure 2).
![istio-gw-2](https://user-images.githubusercontent.com/2950658/191019097-618522b7-05b6-4835-b787-0a5b7dae229a.jpg)
**Figure 2.**
3. Let’s restart the ingress gateway pod, the traffic is evenly distributed between the echo pods (Figure 3).
![istio-gw-3](https://user-images.githubusercontent.com/2950658/191019124-76ba6919-467b-4d0c-a0dd-f56cf6bcbbfb.jpg)
**Figure 3.**

### Version

```prose
istioctl version               
client version: 1.13.7
control plane version: 1.13.7
data plane version: 1.13.7 (4 proxies)

kubectl version --short 
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.21.14
```

### Additional Information

IOPs for A and B Clusters
https://gist.github.com/fl64/21b1ae8594df3556b0f2fa0f521b19ce
```

**Comment by hzxuzhonghu** [comment]
What lb policy do you set? Better provide the gateway configdump

**Comment by fl64** [comment]
LB policy is default.
GW configdump is here: https://gist.github.com/fl64/21b1ae8594df3556b0f2fa0f521b19ce#file-ingressgw-configdump-yaml

**Comment by hzxuzhonghu** [comment]
Is it because of connection reuse? The two requests goes to the same echo-server.

**Comment by fl64** [comment]
But this situation is not reproduced when we deploy the prober to the same cluster where the echo application is located. Even after recreating one of the application-echo pods, the traffic is evenly distributed.

**Comment by hzxuzhonghu** [comment]
This is only my guess, for multi cluster gateway, gateway will lb the HTTP requests as TCP. So would you try more requests?

**Comment by fl64** [comment]
I added another prober to cluster A and the requests started coming in on the pod, which was restarted.
I found a workaround for this case. In cluster A in the namespace prober create a DestinationRule:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo-deploy
spec:
  host: echo-deploy.echo.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
```

And it seems that https://github.com/istio/istio/pull/39765 may help to solve my problem.
Thank you for your assistance!

**Comment by hzxuzhonghu** [comment]
Yes, right, it is the connection reuse, lol
