### ISSUE TITLE
istio 1.15 breaks lua filter custom response headers

### ISSUE THREAD

**Issue by klarose** [istio/istio#41068]
### Bug Description

We use a lua filter to do some simple custom authentication. Part of that flow involves setting some custom headers in response to a request. E.g.

```
              headers = {
                  [":status"] = "302",
                  ["location"] = redirect_url,
              }

              request_handle:respond(headers, "")
```

This has broken after upgrading to istio 1.15 from 1.12.5: no headers other than the status are actually sent back in the response. Some brief searching came up with this:

https://github.com/envoyproxy/envoy/issues/22401

So, it looks like the issue has been fixed. It'd be nice if this could make it into a minor release of wherever the bug was first introduced.

### Version

```prose
client version: 1.10.6
control plane version: 1.15.0
data plane version: 1.15.0 (42 proxies)
```

```
Client Version: v1.25.0
Server Version: v1.22.12-gke.500
```
```


### Additional Information

_No response_

**Comment by zirain** [comment]
https://github.com/istio/proxy/pull/4066/files has been sync to proxy@release-1.15

so it will be fixed in next minor release of v.1.15
cc @istio/release-managers-1-15

**Comment by klarose** [comment]
To help anyone

> https://github.com/istio/proxy/pull/4066/files has been sync to proxy@release-1.15
> 
> so it will be fixed in next minor release of v.1.15 cc @istio/release-managers-1-15

Awesome, thanks.
