### ISSUE TITLE
Istio Ambient does not work with kind cluster on OS X with ARM architecture chips (M1, M2)

### ISSUE THREAD

**Issue by digitalsanctum** [istio/istio#41098]
### Bug Description

Following the steps from the Istio blog post "[Get Started with Istio Ambient Mesh](https://istio.io/latest/blog/2022/get-started-ambient/)" fails. The failure occurs for both `istioctl` and `helm`

### Version

`istioctl version` output:

```
0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
```

`kubectl version --short` output:

```
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.25.0
```

### Additional Information

I've confirmed the same steps from the blog post are successful on OS X and Linux with Intel chips.

Suggest that the blog post be updated with a warning about this bug until this is fixed.

**Comment by ericvn** [comment]
The readme was recently updated, https://github.com/istio/istio/pull/41096, to mention that this is a known issue.
