### ISSUE TITLE
How to refused connections when upstream is unavailable?

### ISSUE THREAD

**Issue by suninuni** [istio/istio#41090]
When upstream is starting and the service port is unavailable, request will be refused like after without istio-proxy.

![image](https://user-images.githubusercontent.com/7345529/191477422-6878fc1e-ffb8-4ea4-bb24-f14e332e54ef.png)

But after inject with istio-proxy, the request changes to 503, this will affect the behavior of the client.

```
*   Trying 10.32.5.135:8080...
* TCP_NODELAY set
* Connected to 10.32.5.135 (10.32.5.135) port 8080 (#0)
> GET /ping HTTP/1.1
> Host: 10.32.5.135:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 145
< content-type: text/plain
< date: Wed, 21 Sep 2022 09:40:25 GMT
< server: istio-envoy
< 
* Connection #0 to host 10.32.5.135 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111
```

Is there any possible to refused connections when upstream is unavailable?

**Comment by howardjohn** [comment]
No, this would require Istio determining the upstream _before_ accepting the connection, which it cannot do currently
