### ISSUE TITLE
should -vmodule=rbac,3 be -vmodule=rbac=3 ?

### ISSUE THREAD

**Issue by jwfang** [istio/istio#411]
see it here:
https://github.com/istio/istio/blob/ba9faeb4e539626c38e305a50efc4f665bd919aa/install/kubernetes/istio-rbac-beta.yaml#L2

but from glog comment:

> //	-vmodule=""
> //		The syntax of the argument is a comma-separated list of pattern=N,
> //		where pattern is a literal file name (minus the ".go" suffix) or
> //		"glob" pattern and N is a V level. For instance,
> //			-vmodule=gopher*=3
> //		sets the V level to 3 in all Go files whose names begin "gopher".

**Comment by jwfang** [comment]
i also found it should be --vmodule instead of -vmoudule , with  **two '-'**

BTW: i was using kargo, with default images be quay.io/coreos/hyperkube:v1.6.4_coreos.0.

**Comment by linsun** [comment]
we no longer use this file istio-rbac-beta.yaml in istio.io for 0.2.

**Comment by linsun** [comment]
i dont have a kube env right now to try this.  this is a debug option that is not exposed to our users in our cloud.  I don't think it is exposed for GKE either.   I propose to defer this.
