### ISSUE TITLE
Allow Override retry backoff per route

### ISSUE THREAD

**Issue by sumitaneja** [istio/istio#41107]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

Istio uses default backoff of 25ms+ and no way to override. 
Request to allow backoff override based on Route. See: https://discuss.istio.io/t/override-retry-backoff/13736

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Currently you can use envoy filter to override it
