### ISSUE TITLE
can not Cross-Cluster Load Balancing? always got v1, cannot got v2.

### ISSUE THREAD

**Issue by conquerorAlex** [istio/istio#41104]
### Bug Description

Following the guide ["Install Multi-Primary on different networks"](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network) in the istio documentation. But cannot Cross-Cluster Load Balancing. And try to trace the problem according [Troubleshooting Multicluster](https://istio.io/latest/docs/ops/diagnostic-tools/multicluster/), and execute command "istioctl --context $CTX_CLUSTER1 proxy-config endpoint sleep-dd98b5f48-djwdw.sample | grep helloworld
", found cluster1 endpoint ip and cluster2 eastwestgate ip. such as follow:

![image](https://user-images.githubusercontent.com/45348944/191669680-012c4434-01a7-49fb-b2d1-4c8a060862bf.png)

### Version

```prose
root@ubuntu-18:/home/istio/istio-1.14.0# istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (4 proxies)
root@ubuntu-18:/home/istio/istio-1.14.0# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Additional Information

kind v0.14.0 go1.18.2 linux/amd64

**Comment by conquerorAlex** [comment]
![image](https://user-images.githubusercontent.com/45348944/191666757-f0fff4cc-0bd9-4250-b74c-e26f30fd8574.png)
![image](https://user-images.githubusercontent.com/45348944/191666791-c2a405b9-f796-49e5-900c-043448a7c39f.png)
![image](https://user-images.githubusercontent.com/45348944/191666895-31227cd4-9d5d-4009-8442-3c531981bac2.png)
![image](https://user-images.githubusercontent.com/45348944/191666934-7df402a1-6bc8-4916-91cb-0d95ba53f280.png)

**and istiod logs as follow:**
![image](https://user-images.githubusercontent.com/45348944/191667139-a3287842-f066-4e52-852c-255efaee65de.png)
![image](https://user-images.githubusercontent.com/45348944/191667235-6a001739-51ec-4590-ab29-339256055efd.png)

**Comment by conquerorAlex** [comment]
![image](https://user-images.githubusercontent.com/45348944/191669098-2e4e5577-10ce-4f30-8fc7-7018adfbbe82.png)

always got v1 version, can not got v2

**Comment by conquerorAlex** [comment]
kubeconfig already use container IP. as follow
root@ubuntu-18:/home/istio/istio-1.14.0# kubectl get secret -n istio-system istio-remote-secret-cluster1 -ojson
{
    "apiVersion": "v1",
    "data": {
        "cluster1": "YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNdmFrTkRRV1ZoWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplVTFFYTNoUFZFRXlUVlJGZUU5R2IxaEVWRTE1VFVScmVFNXFRVEpOVkVWNFQwWnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVFc5MUNpOWpjMEoxWjNFNE1uQlVObFJZVDJoa2NHUmxPRElyY0RoNk1Ia3JkRzAyVWtwNVpGSjFRelJVTjFaeFlYcDBWMHRuT0RWUE9GWTNWalJoV0RadlRGSUtXREExUWtKQ04xRjBOVVJST0ZScmEySndVbUV6U0hoNVNFTklkRzlWZFhCUGFHWlBiM2gxUmpsb2VWcHZLMGN3TmlzNUwwUnBhQ3RrZGtwb1RtVlpkZ3BEU0c5a1VtNTZVSG95WWxWUlkwdDJiV3Q0WmtKU1IyZzJhMFF4WVhsSUwyNVBlSGxzTVVsQ09HZGxjMUJSVVU4M2NUVldLMGRGWmxVNGFtdFRPVGxTQ21wSVJYWkxOSHB6ZFV0R1NrdzVWV1Z5THpsS2VHZzRVMHdyUlZWcFdVSldTamxQZW1FNVIyTjZNR016TjB4MVUyMVdkbmRuZWs4MEx6ZGlOR2RtTmt3S2VWUmhNbWh4YUVGR05tTTVRMkV5YkdzMFpITkRjbU5wYnpRcmNEZG1lR3B0T1ZFMWMyVkJTU3Q0V1dWMlpIZG9ibkIxVm5oelEyNU5iV2xCVTNadFZnbzBWblp6Y2tWbFdreG9MM0Y1WkVaWlpXOXJRMEYzUlVGQllVNWFUVVpqZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWk9abmgwT1VNNE5HVnBXRXR6YUZOWFMyUjBUbmw1WlRkTWMxTk5RbFZIUVRGVlpFVlJVVThLVFVGNVEwTnRkREZaYlZaNVltMVdNRnBZVFhkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCVFU1TVVIZ3JWbmhGVEhwTEwzcFZOSGMzZEFvck9TdDZWM1JPT1c5UlpuQjVXR3BQUlhVdlMxRTBZMlZHYldoRFpGZHhkVGw1VTFweVNrbFBkM0oxYkhVeWJXeDFWWE50Wmt4WmJIbzFSR1V4ZDJvM0NqWjNaMHBJYjNKckt6Y3dXRXAxYlVSeWIxUkxTRWhEVWtOVVZuRndka2tyU1RkTmRHZG9iWEpSVG1oMFRqbDRlVTF4WjNOTkt6ZEJXVFpNTlhOM2RWb0tZekI1VEZjNFYzcERkMjUyY0UxdFNrTkJNVkJIZWl0aGVUUnZRbFpwYlhKcE1UVm1OMGhvUzFGRE1GSlNRMUZhV0U5R1JWUlVSSEY0Wm1abGJERTVVUXBvYkVoNlZIbDFMM0Y0VGk5WVdWRm5WaTlVT0hKME16WnJXRWRETDNBcldITmpkV1Z4WlVvdmQwcGtjVGx2WVZCb1YyTlVUR2d5UlRGdllUSkNkVVIyQ2t4ME5FZHdObW92VjJaa1owMWtPRUUwYURCbVNsZGtjbTlGUnpsQk5WZFNiR2hSVEZaaGNsUnpSMFU1YmtwV1NXWmhWaTlpVVV0U2FIUjRVakYyTTJZS2JsVkZQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBzZXJ2ZXI6IGh0dHBzOi8vMTkyLjE2OC45Ni4yOjY0NDMKICBuYW1lOiBjbHVzdGVyMQpjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogY2x1c3RlcjEKICAgIHVzZXI6IGNsdXN0ZXIxCiAgbmFtZTogY2x1c3RlcjEKY3VycmVudC1jb250ZXh0OiBjbHVzdGVyMQpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGNsdXN0ZXIxCiAgdXNlcjoKICAgIHRva2VuOiBleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SWw5eVVIQktTMFpZZUVKR2JrMUJPR1p3WjJRek1YUlZUbk5XZGpCclFVZEpabXBPWjA5eVZYcHFOMEVpZlEuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSnBjM1JwYnkxemVYTjBaVzBpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pYVhOMGFXOHRjbVZoWkdWeUxYTmxjblpwWTJVdFlXTmpiM1Z1ZEMxcGMzUnBieTF5WlcxdmRHVXRjMlZqY21WMExYUnZhMlZ1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1semRHbHZMWEpsWVdSbGNpMXpaWEoyYVdObExXRmpZMjkxYm5RaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lJNFpUZGpNek0yTUMweVlUazNMVFEyTVRJdE9EbG1NQzFqTURGbFpUWmhZakJpTnpjaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhWE4wYVc4dGMzbHpkR1Z0T21semRHbHZMWEpsWVdSbGNpMXpaWEoyYVdObExXRmpZMjkxYm5RaWZRLnFhU1VEMFFVdkdGLU1NUUtEMldHM3dmMzUwRkRVZUY0Ukp3aHBVaDRIaFFfeDgyeW1DeTh2WnJhX25uVkJNOGZLZ01zRURhQVIzM0Q1Y2ZneTdmNW1GSzVwVmtwT21HX3RWeU1yZmZTYlNER3Z5VUR2cWlZNXN6bi1qQnhfNWtqVlVINGd5dUFGaWxGMVpDbVhuZjdPaEdlYldCU1ozaHVNZXZDOEFyTFRydDk5Y2ttc3oxWUdfbUMwSkhhdFhPbFB0S3F4YWpCQ0xKSEJFOERvVGNFemU5aDEzdERBZGtGUjkwY25ma2tUU0RyTTlJNUpxREpHaHQzU0s0aGJQZjFjX2dqcmNYQWF2SnVfUDRkNG14M2Y2MXhOTUFPaUlyeFhkRkhKZzA1UTZhNWFiZ18yYWtuYlM1cjBzX0FNZmROQU02YUhZTzVDazRYTmlEd2FGcTlSZwo="
    },
    "kind": "Secret",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Secret\",\"metadata\":{\"annotations\":{\"networking.istio.io/cluster\":\"cluster1\"},\"creationTimestamp\":null,\"labels\":{\"istio/multiCluster\":\"true\"},\"name\":\"istio-remote-secret-cluster1\",\"namespace\":\"istio-system\"},\"stringData\":{\"cluster1\":\"apiVersion: v1\\nclusters:\\n- cluster:\\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3hPVEEyTVRFeE9Gb1hEVE15TURreE5qQTJNVEV4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTW91Ci9jc0J1Z3E4MnBUNlRYT2hkcGRlODIrcDh6MHkrdG02Ukp5ZFJ1QzRUN1ZxYXp0V0tnODVPOFY3VjRhWDZvTFIKWDA1QkJCN1F0NURROFRra2JwUmEzSHh5SENIdG9VdXBPaGZPb3h1RjloeVpvK0cwNis5L0RpaCtkdkpoTmVZdgpDSG9kUm56UHoyYlVRY0t2bWt4ZkJSR2g2a0QxYXlIL25PeHlsMUlCOGdlc1BRUU83cTVWK0dFZlU4amtTOTlSCmpIRXZLNHpzdUtGSkw5VWVyLzlKeGg4U0wrRVVpWUJWSjlPemE5R2N6MGMzN0x1U21Wdndnek80LzdiNGdmNkwKeVRhMmhxaEFGNmM5Q2EybGs0ZHNDcmNpbzQrcDdmeGptOVE1c2VBSSt4WWV2ZHdobnB1VnhzQ25NbWlBU3ZtVgo0VnZzckVlWkxoL3F5ZEZZZW9rQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOZnh0OUM4NGVpWEtzaFNXS2R0Tnl5ZTdMc1NNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTU5MUHgrVnhFTHpLL3pVNHc3dAorOSt6V3ROOW9RZnB5WGpPRXUvS1E0Y2VGbWhDZFdxdTl5U1pySklPd3J1bHUybWx1VXNtZkxZbHo1RGUxd2o3CjZ3Z0pIb3JrKzcwWEp1bURyb1RLSEhDUkNUVnFwdkkrSTdNdGdobXJRTmh0Tjl4eU1xZ3NNKzdBWTZMNXN3dVoKYzB5TFc4V3pDd252cE1tSkNBMVBHeitheTRvQlZpbXJpMTVmN0hoS1FDMFJSQ1FaWE9GRVRURHF4ZmZlbDE5UQpobEh6VHl1L3F4Ti9YWVFnVi9UOHJ0MzZrWEdDL3ArWHNjdWVxZUovd0pkcTlvYVBoV2NUTGgyRTFvYTJCdUR2Ckx0NEdwNmovV2ZkZ01kOEE0aDBmSldkcm9FRzlBNVdSbGhRTFZhclRzR0U5bkpWSWZhVi9iUUtSaHR4UjF2M2YKblVFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\\n    server: https://**192.168.96.2:6443**\\n  name: cluster1\\ncontexts:\\n- context:\\n    cluster: cluster1\\n    user: cluster1\\n  name: cluster1\\ncurrent-context: cluster1\\nkind: Config\\npreferences: {}\\nusers:\\n- name: cluster1\\n  user:\\n    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il9yUHBKS0ZYeEJGbk1BOGZwZ2QzMXRVTnNWdjBrQUdJZmpOZ09yVXpqN0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcmVhZGVyLXNlcnZpY2UtYWNjb3VudC1pc3Rpby1yZW1vdGUtc2VjcmV0LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImlzdGlvLXJlYWRlci1zZXJ2aWNlLWFjY291bnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4ZTdjMzM2MC0yYTk3LTQ2MTItODlmMC1jMDFlZTZhYjBiNzciLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aXN0aW8tc3lzdGVtOmlzdGlvLXJlYWRlci1zZXJ2aWNlLWFjY291bnQifQ.qaSUD0QUvGF-MMQKD2WG3wf350FDUeF4RJwhpUh4HhQ_x82ymCy8vZra_nnVBM8fKgMsEDaAR33D5cfgy7f5mFK5pVkpOmG_tVyMrffSbSDGvyUDvqiY5szn-jBx_5kjVUH4gyuAFilF1ZCmXnf7OhGebWBSZ3huMevC8ArLTrt99ckmsz1YG_mC0JHatXOlPtKqxajBCLJHBE8DoTcEze9h13tDAdkFR90cnfkkTSDrM9I5JqDJGht3SK4hbPf1c_gjrcXAavJu_P4d4mx3f61xNMAOiIrxXdFHJg05Q6a5abg_2aknbS5r0s_AMfdNAM6aHYO5Ck4XNiDwaFq9Rg\\n\"}}\n",
            "networking.istio.io/cluster": "cluster1"
        },
        "creationTimestamp": "2022-09-22T02:51:46Z",
        "labels": {
            "istio/multiCluster": "true"
        },
        "name": "istio-remote-secret-cluster1",
        "namespace": "istio-system",
        "resourceVersion": "339033",
        "uid": "fe71ecb3-03a0-4cee-a588-4e223aac3488"
    },
    "type": "Opaque"
}

**Comment by conquerorAlex** [comment]
strange!!! While "istioctl proxy-config endpoint" got another cluster eastwestgateway external ip, but dns in pod "sleep"  in local cluster is still the same as service ip of "hello world v1" in local cluster. 

![image](https://user-images.githubusercontent.com/45348944/191883814-2a8ab41d-bb60-495e-a42e-ab300db71fb1.png)

**Comment by hzxuzhonghu** [comment]
This is intended: cluster workload will resolve a service to its local cluster ip.

**Comment by conquerorAlex** [comment]
@hzxuzhonghu already following the guide ["Install Multi-Primary on different networks"](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network) in the istio documentation, but still got v1 only. And pods running successfully as u can see above. Do u know why sleep cannot loadbalance to v2?

**Comment by john-a-joyce** [comment]
I am hitting this same issue in a slightly different configuration.    My differences are that I am using multi-primary on the same network and I have set the two clusters up so the pods and svcs have IP reachability across the clusters (what the istio community likes to call a "flat" network).   Other differences are that I am using 1.16 (I also tried this on the ambient image).  I also see that the loadbalancing will never cross cluster boundaries.    I will provide some details in a separate comment.

**Comment by john-a-joyce** [comment]
For this case I added a V1 and V2 pod to the first cluster to check both intra and inter cluster load balancing
```console
kubectl get pods -n sample -o wide
NAME                             READY   STATUS    RESTARTS   AGE    IP            NODE                     NOMINATED NODE   READINESS GATES
helloworld-v1-776f57d5f6-xb9xv   2/2     Running   0          19h    10.240.0.8    cluster1-control-plane   <none>           <none>
helloworld-v2-54df5f84b-p2mb7    2/2     Running   0          75m    10.240.0.11   cluster1-control-plane   <none>           <none>
sleep-784d69f945-nptlx           2/2     Running   0          145m   10.240.0.10   cluster1-control-plane   <none>           <none>
```
```console
kubectl get pods -n sample -o wide --context=kind-cluster2
NAME                            READY   STATUS    RESTARTS   AGE   IP           NODE                     NOMINATED NODE   READINESS GATES
helloworld-v2-54df5f84b-2lnrz   2/2     Running   0          19h   10.241.0.8   cluster2-control-plane   <none>           <none>
sleep-784d69f945-z87wh          2/2     Running   0          19h   10.241.0.9   cluster2-control-plane   <none>           <none>
```
```console
kubectl get svc -n sample 
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
helloworld   ClusterIP   10.96.225.213   <none>        5000/TCP   19h
sleep        ClusterIP   10.96.170.170   <none>        80/TCP     19h
```
From the next command we can see the endpoints from both clusters have all been learned and distributed via xDS. 
```console
 ./bin/istioctl proxy-config endpoints sleep-784d69f945-nptlx.sample | grep hello
10.240.0.11:5000                                        HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.240.0.8:5000                                         HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.241.0.8:5000                                         HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
The next command shows the cluster endpoints should be via EDS NOTE: not via DNS or via the svc IP
```console
./bin/istioctl proxy-config clusters sleep-784d69f945-nptlx.sample | grep hello
helloworld.sample.svc.cluster.local                     5000      -          outbound      EDS              
./bin/istioctl proxy-config routes sleep-784d69f945-nptlx.sample | grep hello
5000                                                          helloworld, helloworld.sample + 1 more...           /*
```
Below is the logs from the sleep container with access logging turned on and the capture of the curl just below.  It suggests that that envoy is not sending to one of the endpoints in the xDS cluster but instead sending it to the kubernetes service IP.  
```console
kubectl exec -it sleep-784d69f945-nptlx -n sample -c sleep -- curl -sS helloworld.sample:5000/hello
Hello version: v1, instance: helloworld-v1-776f57d5f6-xb9xv
kubectl logs sleep-784d69f945-nptlx -c istio-proxy -n sample | tail -2
[2022-11-21T17:48:30.965Z] "GET /hello HTTP/1.1" 200 - via_upstream - "-" 0 59 138 138 "-" "curl/7.86.0-DEV" "acd117b4-97ac-4b1d-872e-3cb4dc24caca" "helloworld:5000" "10.240.0.11:5000" outbound|5000||helloworld.sample.svc.cluster.local 10.240.0.10:53880 10.96.225.213:5000 10.240.0.10:47246 - default
2022-11-21T17:55:50.357799Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
```
The below command shows the helloworld pod on the 2nd cluster is reachable if using the direct address.
```console
kubectl exec -it sleep-784d69f945-nptlx -n sample -c sleep -- curl -sS 10.241.0.8:5000/hello
Hello version: v2, instance: helloworld-v2-54df5f84b-2lnrz
```

**Comment by john-a-joyce** [comment]
So if this is working as designed I would ask as few questions.  

- Has this been a recent behavior change?  It's been a long time since I tested but I don't believe it always worked this way. 
- What config or commands can I use to show the actual routing the Envoy will use.   Just dumping the proxy config info would indicate that the loadbalancing should be between all the endpoints.  Is there any indication at the config level to show that the packet will be directed to the cluster svc. 
- If the consensus is the controlplane and dataplane is acting as designed, then the documentation is broken as the cluster cluster load balancing doesn't work for at least 2 supported topologies.

**Comment by hzxuzhonghu** [comment]
@john-a-joyce Do you setup locality failover or something else?

Better if you can provide complete configdump on CDs and eds

**Comment by john-a-joyce** [comment]
[envoy_config_dump.tar.gz](https://github.com/istio/istio/files/10078036/envoy_config_dump.tar.gz)

**Comment by john-a-joyce** [comment]
@hzxuzhonghu - sorry I most have corrupted the file when I tarred it.  Anyway, I double checked things and found the reason there was not load balancing across the clusters is I did not properly set up a common chain of trust.   Once I fixed that I was able to properly load balance across the clusters.    Since the original submitter was going through gateways its not obvious if his issue is the same.   

There were two things that threw me off.     
1.  All the endpoints were showing "healthy" via the proxy config command .  If envoy was not able to send to some of the endpoints I thought it might show a different status.  
2. I was able to curl across cluster boundaries when using the IP address of the remote pods - but after turning on more debugs. I saw that was working because it was going through the passthrough cluster in envoy.  As I understand it, that will use http without TLS between the two proxies so common trust would not be required.   

At this point WRT to my comments on this issue I don't see the need for any changes to code or documentation.

**Comment by XWTiger** [comment]
`[root@test-1-master-3 istio-1.16.2]# ./bin/istioctl --context=$CTX_CLUSTER2  proxy-status   | grep hello
helloworld-v2-5cc6945c4-rllmm.sample                   cluster2     SYNCED     SYNCED     SYNCED     SYNCED       NOT SENT     istiod-599fb7f4cd-s5vv2     1.16.2
[root@test-1-master-3 istio-1.16.2]# ./bin/istioctl --context=$CTX_CLUSTER2  proxy-config endpoints helloworld-v2-5cc6945c4-rllmm.sample   | grep hello
10.233.67.6:5000                                        HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.233.67.8:5000                                        HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
`
Above results  all are ok,  the result at below  is empty  
./bin/istioctl proxy-config routes sleep-f797465db-qhmjs.sample | grep hello
