### ISSUE TITLE
CircuitBreaking - Outlier detection to detect custom http codes also(such as 429/400)

### ISSUE THREAD

**Issue by ankitdiscovery** [istio/istio#41105]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I am using micorservices pattern deployed in cloud with istio service mesh. i was exploring the circuit breaker supports given by istio. Outlier detection is way to solve my problem but i see that it trip/take actions only with gateway error code[502-504]. How can i configure it to eject the pod if my service starts throwing some other code such as 429(too many requests) or any other error codes.

**Comment by zirain** [comment]
https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry

**Comment by ankitdiscovery** [comment]
@zirain  i want my serviceA to stop calling the serviceB (if serviceB gives 429) for some sleep window.

**Comment by GregHanson** [comment]
@ankitdiscovery does this work for you in HTTPRetry?
>retryOn: Specifies the conditions under which retry takes place. One or more policies can be specified using a ‘,’ delimited list. If retry_on specifies a valid HTTP status, it will be added to retriable_status_codes retry policy. See the retry policies and gRPC retry policies for more details.

You may not be able to explicitly say not to retry on 429, but you can select from a list of retry other policies here:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on

I don't think the existing CircuitBreaker logic available in envoy has the ability to specify a particular return code for immediately ejecting an endpoint:
https://www.envoyproxy.io/docs/envoy/v1.23.1/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-msg-config-cluster-v3-outlierdetection

**Comment by ankitdiscovery** [comment]
@GregHanson You are right, HTTPRetry not gonna work for that usecase.
Also since we have a limited to trip circuit based on 5xx codes only , so i am thinking of returning some 5xx code instead of 429 (too many requests) from application, Although that is not something standard/advisable way. But it will buy some time for application pod to cool down and cleanup their existing work before getting added back to pool again.

**Comment by GregHanson** [comment]
marking as resolved
