### ISSUE TITLE
"TLS handshake error" issue after Istio update 1.13.7 -> 1.14.4

### ISSUE THREAD

**Issue by Dima-Diachenko-work** [istio/istio#41138]
### Bug Description

Hello Istio team!
Guys... I need your support. :)

I had the `1.13.7` Istio version and everything works pretty well. Thank you for your product!

But after an update to `1.14.4` infrastructure services that use their own TLS certs start to get errors, for example - Hashicorp Vault (deploy via [operator](https://artifacthub.io/packages/helm/banzaicloud-stable/vault-operator)) :

Here is what I got from the external domain:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/104848965/191946939-02dd9f8d-5f25-4d5c-ac57-da4fad219cc9.png">
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

Vault logs at request:
```
{"@level":"info","@message":"http: TLS handshake error from 127.0.0.6:43441: EOF","@timestamp":"2022-09-23T11:01:26.713985Z"}
{"@level":"info","@message":"http: TLS handshake error from 127.0.0.6:46761: EOF","@timestamp":"2022-09-23T11:01:33.592837Z"}
{"@level":"info","@message":"http: TLS handshake error from 127.0.0.6:41147: EOF","@timestamp":"2022-09-23T11:01:33.620804Z"}
```

Istio-proxy (sidecar) log:
[istio-proxy.log](https://github.com/istio/istio/files/9633049/istio-proxy.log)
Nothing interesting except TLS errors and 503 error code due to this.

I read the release notes and changes and tried to fix them by adding to:
  - kind: Gateway
  ```
  tls:
    ... 

    mode: SIMPLE
    minProtocolVersion: TLSV1_2
    maxProtocolVersion: TLSV1_2
  ```
  - kind: IstioOperator
  ```
  spec:
    ...

    meshConfig:
      meshMTLS:
        minProtocolVersion: TLSV1_2
  ```
*(with different min/max versions combinations)*

But this doesn't want to work. 

We use CloudFlare *proxied* NS record, but I'm sure that this is important (since at 1.13.7 and lower Istio versions all work OK). 
If I disable TLS from the Vault configs - it works without error. And services that DON'T use their own TLS available and working. But what to do with it?..

I read carefully the change notes to 1.14.x - and it's probably related to the TLS work (since you added [support for configuring the TLS version](https://istio.io/latest/news/releases/1.14.x/announcing-1.14/#add-support-for-configuring-the-tls-version-for-istio-workloads)). But I don't know how to handle it. 

Honestly, I tried everything that I could find and it all not helped.
Plus the same issue I got with [RabbitMQ](https://artifacthub.io/packages/helm/bitnami/rabbitmq) self-hosted deployment that we use, maybe something else. 

All hope for your recommendations. Maybe you are in the context of the changes. Thanks in advance!

### Version

*This is a test cluster where I reproduced the issue.*
- Istio
```
istioctl version
client version: 1.15.0
control plane version: 1.14.4
data plane version: 1.14.4 (9 proxies)
```
- K8s
```
kubectl version --short 
Client Version: v1.22.6
Server Version: v1.23.8
```
```
### Additional Information

I'm ready to provide any additional info or logs if you will require something.

**Comment by howardjohn** [comment]
Might be https://github.com/istio/istio/issues/40680. What is the exact flow of traffic/TLS? Seems like your app is handling TLS and istio is also adding mTLS on top of that, is that right?

**Comment by Dima-Diachenko-work** [comment]
hi @howardjohn ,
sorry for the delay with answer. 

I can't say precisely what traffic it is, just default TLS config that uses Hashicorp Vault from[ this self-hosted deployment ](https://artifacthub.io/packages/helm/banzaicloud-stable/vault-operator). 
You are right about adding mTLS on top of the application traffic. I read https://github.com/istio/istio/issues/40680 and I think that that could be it.

**Comment by Dima-Diachenko-work** [comment]
One more question please - could we handle this issue with EnvoyFilter like in this example https://github.com/istio/istio/issues/24619#issuecomment-675463009

**Comment by howardjohn** [comment]
Its not going to be something we can debug unless we know the flow of the request. Like `client --> TLS --> Gateway (terminate TLS) ---> plaintext over MTLS ---> sidecar (terminate mtls) ---> plaintext` or something.

**Comment by Dima-Diachenko-work** [comment]
You are almost right with your description of the scheme:
> `client --> TLS --> Gateway (terminate TLS) ---> plaintext over MTLS ---> sidecar (terminate mtls) ---> plaintext`

But in the end I would add clarification (as I understood it):

> `....... - sidecar (terminate mtls) ---> working on SIMPLE TLS mode` (using certificate provided by service, in our case its Vault).  
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vault
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  host: vault
  trafficPolicy:
    tls:
      mode: SIMPLE
```


And @howardjohn can I ask you about https://github.com/istio/istio/issues/40680#issuecomment-1256372749 - maybe you could say ETA for some fix in this issue? Probably makes sense to wait for it?

**Comment by howardjohn** [comment]
`....... - sidecar (terminate mtls) ---> working on SIMPLE TLS mode` is not the case. TLS can only be originated for outbound traffic, not inbound traffic.

If you are applying that rule, you are actually saying

`client --> TLS --> Gateway (terminate TLS) ---> SIMPLE tls ---> sidecar (passthrough) ---> tls to app`
