### ISSUE TITLE
istio egressgateway unable to populate endpoints

### ISSUE THREAD

**Issue by kalyanteja19** [istio/istio#41140]
### Bug Description

In order to enable external service (abc.com) access through egress, service entry and virtual service has been created.

But endpoints not populated into egress issue.

Can you please help me to get this endpoints populated without restarting istio egress gateway.

Below analysis has been done.

1. Checked if there is duplicate host --> no duplicate entries
2. Checked istiod logs ---> No errors logs related to abc.com
3. But when we run the below commands, endpoints are not registered for abc.com
istioctl pc endpoints istio-egressgateway-xxxxxxx-xxxxx.istio-system

Can you please help me to get this endpoints populated without restarting istio egress gateway.

Please be noted that by restarting the istio egressgateway, it was able to populate endpoints few times in the past. We need permanent workaround or solution for this issue, as we dont do restart istio egress on prod instances

### Version

```prose
istioctl version                                                                                                                                                                      ─╯
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (234 proxies)

kubectl version --short                                                                                                                                                                ─╯
Client Version: v1.23.8
Server Version: v1.23.8
```

**Comment by kalyanteja19** [comment]
@howardjohn @ZhengzheYang , Kindly assist on this issue

**Comment by GregHanson** [comment]
@kalyanteja19 can you share the Gateway and VirtualService you are using? 

Also, If you check the `listener` or `route` output from istioctl (depending on if traffic is HTTP or TLS), do you see the hostname/SNI name for the ServiceEntry in the output? If not, the VS and Gateway selector may not be matching the egress gateway you are attempting to apply routing rules to.
```
istioctl pc listener|route  istio-egressgateway-xxxxxxx-xxxxx.istio-system
```

**Comment by hzxuzhonghu** [comment]
It is also related to service resolution type. So, please show the ServiceEntry definition

**Comment by kalyanteja19** [comment]
> 

@hzxuzhonghu @GregHanson 

Thank you. But hostname does show up in the listeners and route also properly added.

Due to urgency, I have restarted egress gateway pod, then endpoints were added and issue no longer exists. Service resolution has been mentioned as DNS.

Kindly suggest the debugging steps in these type of scenarios.

**Comment by kalyanteja19** [comment]
No response on this and nothing found, hence closed
