### ISSUE TITLE
Istio `crdclient` is not resilient to removed API versions

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#41146]
Currently we check if a resource exists by looking at the CRD name: https://github.com/istio/istio/blob/79559c87b3ab3dd899690f9e2ab5ddd72afe489f/pilot/pkg/config/kube/crdclient/client.go#L170

This has the group + name, but not the version.

If the CRD exists, we watch that resource. This will block startup until the watch is synced.

An issue can occur if a version is removed. For instance, if gateway-api were to remove (or mark `served: false`) the `v1alpha2` HTTPRoute. The check would find the CRD exists, and attempt to watch it. However, the API server would not serve it, so the watch would fail. This would result in Istiod never starting up.

The end result is that any CRD version removal can result in an Istiod outage.

The alternative, of course, is not that much better - we would end up not watching a resource we wanted to because we are using the wrong version.

**Comment by hzxuzhonghu** [comment]
Good catch. curious why does it need to specify the version served false rather than removing it from the versions list?
