### ISSUE TITLE
An error occurred trying to build istio

### ISSUE THREAD

**Issue by MaiM1ng** [istio/istio#41157]
### Bug Description

I was recently trying to compile the Isito source code. I git the master branc and run the make init and make docker commands, but an error occurred.
The error is shown below
I cannot locate the location and cause of the error, please give me some advice

```Shell
 => CACHED [app_sidecar_debian_11-default 2/9] COPY certs/                           /var/lib/istio/                               0.0s
 => CACHED [app_sidecar_debian_11-default 3/9] COPY certs/default/                   /var/run/secrets/istio/                       0.0s
 => ERROR [app_sidecar_debian_11-default 4/9] COPY amd64/istio-sidecar.deb  /tmp/istio-sidecar.deb                                 0.0s
------
 > [app_sidecar_debian_11-default 4/9] COPY amd64/istio-sidecar.deb  /tmp/istio-sidecar.deb:
------
ERROR: failed to solve: failed to compute cache key: "/amd64/istio-sidecar.deb" not found: not found
2022-09-25T17:55:11.249974Z	info	build complete	runtime=48.887230332s
Error: exit status 1
make: *** [docker] Error 255
```

### Version

```prose
istio version 1.16
```

**Comment by ericvn** [comment]
Using my dev machine, an Intel MacBook Pro, I just moved to the latest commit and did a `make clean init docker` and it completed successfully.

I see the fpm command and it's output:
```
Created package {:path=>"/work/out/linux_amd64/release/istio-sidecar.deb"}
```

You might verify that you have enough resources to do a build and you might make sure the your environment is pruned, cache cleaned up. I have a 16 GB Docker Desktop configured.

**Comment by MaiM1ng** [comment]
I checked the log carefully and found that DPKG was missing because I was using CentoS7 system. I need to work hard to learn more
Thanks to Ericvn for your reply.
