### ISSUE TITLE
Metrics on remote cluster health status/reachability

### ISSUE THREAD

**Issue by qudongfang** [istio/istio#41173]
**Describe the feature request**

What do you think about having a metric to show if the remote cluster is reachable or not? something like 

```
# HELP istiod_managed_cluster_healthy Healthy status of a cluster managed by istiod
# TYPE istiod_managed_cluster_healthy gauge
istiod_managed_cluster_healthy{cluster_type="remote", cluster_id="foobar"}        1
```

**Describe alternatives you've considered**

In the event of a wrong remote secret or networking issue,  Isitod might not be able to reach a remote cluster.
We're alerting on the error logs at the moment.

It would be great if we can have some metrics which is better for alerting.

```
2022-09-20T10:47:27.850653Z	error	Adding cluster_id from secret=kube-1-us-east-1-aws-cloud-dev: istio-system/istio-remote-secrets 1 error occurred:
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

Related PR:

- https://github.com/istio/istio/pull/40542

**Comment by hellorill** [comment]
This info available in /debug/clusterz (15014), but metrics would be useful.
`[{"id":"test1","secretName":"istio-system/istio-clustermesh-test1","syncStatus":"synced"},{"id":"test2","secretName":"istio-system/istio-clustermesh-test2","syncStatus":"synced"}]`

+1

**Comment by zirain** [comment]
does `istiod_managed_clusters` enough for your case?
```
# HELP istiod_managed_clusters Number of clusters managed by istiod
# TYPE istiod_managed_clusters gauge
istiod_managed_clusters{cluster_type="local"} 1
istiod_managed_clusters{cluster_type="remote"} 1
```

**Comment by qudongfang** [comment]
> does `istiod_managed_clusters` enough for your case?
> 
> ```
> # HELP istiod_managed_clusters Number of clusters managed by istiod
> # TYPE istiod_managed_clusters gauge
> istiod_managed_clusters{cluster_type="local"} 1
> istiod_managed_clusters{cluster_type="remote"} 1
> ```

It helps a bit, but we still don't know which remote cluster(s) is problematic with this mertic.

Also, with time, we may have more clusters, we cannot actually set an alert with something like `istiod_managed_clusters{cluster_type="remote"} == 10`.

It would be great if we could have a per remote cluster health status metric with the cluster_id as a tag/dimension.

**Comment by zirain** [comment]
which type of metric you expected to be? guage?

**Comment by qudongfang** [comment]
> which type of metric you expected to be? guage?



Yes, gague as proposed in this issue description(metric name and dimensions to be decided)

```
# HELP istiod_managed_cluster_healthy Healthy status of a cluster managed by istiod
# TYPE istiod_managed_cluster_healthy gauge
istiod_managed_cluster_healthy{cluster_type="remote", cluster_id="foobar"}        1
```

**Comment by zirain** [comment]
how would you handle with unhealthy cluster?
IIRC, if a cluster join into mesh and then removed later, is there a memory leak?

**Comment by zirain** [comment]
as talked on slack, there's nothing we should do for now.
feel free to reopen if you have furthre concerns
