### ISSUE TITLE
AWS ELB HTTPS Listener Stopped Working in Version 1.15.x

### ISSUE THREAD

**Issue by akefirad** [istio/istio#41196]
### Bug Description

Upgrading from version 1.14.x to 1.15.x seems to break HTTPS connectivity between AWS ELB (of `istio-ingressgateway` service). I'm not entirly sure if this is a misconfiguration on my side or something is broken. I couldn't find anything in the docs. Apologies in advance if this is not a bug.

1. The istio is deployed using `istioctl manifest generate -f override.yaml` (maintained by ArgoCD). The content of override.yaml file is:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz/ready
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: >-
              arn:aws:acm:eu-central-1:123456789012:certificate/<uuid>
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

2. Deploying the above for version 1.14.x creates an AWS ELB instance that responds with:

```
$ http --verify false https://aws-elb-id.eu-central-1.elb.amazonaws.com
HTTP/1.1 404 Not Found
content-length: 0
date: Tue, 27 Sep 2022 13:39:18 GMT
server: istio-envoy # <--- THIS!
```

3. Upgrading to version 1.15.x creates an AWS ELB instance that responds with:

```
$ http --verify false https://aws-elb-id.eu-central-1.elb.amazonaws.com
HTTP/1.1 408 REQUEST_TIMEOUT
Connection: Close
Content-Length: 0
```

4. Removing `ssl-cert` and `ssl-ports` service annotations would resolve the issue. (However this changes the protocol on the ELB to TCP and is not a solution really!)

### Version

```prose
$ istio version
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (2 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

The above would work in a clean istio installation. But I can also confirm that in our real cluster it's the same. Also the istio stack works as expected as long as you call the service direclty (using kubectl port-forward). Let me know if there's any more information I need to provide.

**Comment by jpke** [comment]
Running into this also. Confirmed istio ingressgateway service is reachable via the https nodeport of its service via `curl -Ik -H "Host: <some hostname configured in istio>" https://<node ip>:<istio ingressgateway https nodeport>`.

Maybe also relevant, we're using the ssl healthcheck of the classic load balancer. This fails after upgrading to istio 1.15.1. Switching to tcp healthcheck allows instances to become healthy again, but lb returns 408.

**Comment by akefirad** [comment]
That's right, mine didn't have that issue since our health check is on HTTP. And it seems the setup doesn't have any issue on HTTP (and or TCP) protocol.

**Comment by akefirad** [comment]
Just as an update, configuring the ELB listener to talk to Istio on HTTP, everything works as expected. But not on HTTPS.

**Comment by ragboy** [comment]
Is this listed as a known issue anywhere? Is there any resolution to this?

**Comment by cmcbugg** [comment]
> Just as an update, tried with version 1.16, same issue. Also configuring the ELB listener to talk to Istio on HTTP, everything works as expected. But not on HTTPS.

@akefirad did you ever find a resolution to this issue with 1.15 and the ELB HTTPS listener?

**Comment by JonKusz** [comment]
I recently experienced a similar issue when using an AWS classic load balancer, with SSL health checks against the nodePort of the `istio-ingressgateway` `Service`. The solution in my case was to explicitly set the supported `cipherSuites` in the `Gateway` resources, as mentioned in this [issue](https://github.com/istio/istio/issues/42648#issuecomment-1436729958), allowing the load balancer health checks to pass, restoring functionality.

[Istio Gateway cipherSuites reference.](https://istio.io/latest/docs/reference/config/networking/gateway/#:~:text=No-,cipherSuites,-string%5B%5D)
