### ISSUE TITLE
Add metadata to WorkloadEntry

### ISSUE THREAD

**Issue by masquee** [istio/istio#41201]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Envoy supports  metadata on [LbEndpoint](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-lbendpoint), but Istio's API seems has no correspending config.

This feature is needed because we are considering using Envoy's Subset Load Balancing.

**Describe alternatives you've considered**
No alternatives have been thought of so far

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Not sure how you register WorkloadEntry, using istio auto registration or manually by some other tools.
If it is by istio auto, you can set different subset labels with different WorkloadGroup. For manually registered, it is possible to set different labels too.

**Comment by masquee** [comment]
@hzxuzhonghu  manually registered. Seems WorkloadEntry labels will not transfrom to endpoint metadata.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/8470824/192744921-a354df85-b7d5-44ea-898a-be081ce04eec.png">

**Comment by masquee** [comment]
For example, I want config endpoint metadata as below used for envoy load balancer

<img width="576" alt="image" src="https://user-images.githubusercontent.com/8470824/192746331-144b4a74-2154-416b-8ac5-45a8c967ab74.png">

**Comment by hzxuzhonghu** [comment]
If you mean these metadata, why donot you specify subsets with destinationrule

**Comment by masquee** [comment]
> If you mean these metadata, why donot you specify subsets with destinationrule

We need Envoy's **Subset Load Balancing**, see  https://github.com/envoyproxy/envoy/blob/main/source/docs/subset_load_balancer.md

In short, if we use destinationrule, we have to keep changing destinationrule. @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
kind of remember there was already an issue discussing this. If so, please not open duplicate issues. Move talking there

**Comment by masquee** [comment]
I found this issue but alreay closed: https://github.com/istio/istio/issues/33896

**Comment by masquee** [comment]
Even if it is not used to support Subset Load Balancing, I think it is useful to add metadata to WorkloadEntry, because Envoy has many extended features that can be implemented based on metadata. **Some configurations can be patched through Istio EnvoyFilter, but  it is impossible to patch each endpoint the metadata**.
