### ISSUE TITLE
http.* Envoy metrics are not exposed correctly by prometheus when enabled

### ISSUE THREAD

**Issue by dmarkwat** [istio/istio#41206]
### Bug Description

Apologies for the lengthy bug report but this took a bit to get through to the end.

Questions are in the Summary & quick repro is at the end.

### Summary
Some of the tag matchers in the bootstrap statsConfig (specifically [these two](https://github.com/istio/istio/blob/54aa1b4ea6e2c12a7e78614d05b7d6afc4c09300/tools/packaging/common/envoy_bootstrap.json#L55-L62)) do not appear to have the correct regex matching and generate prometheus metrics with labels embedded in their names when they should be removed. This presents problems in many observability services ($$$, primarily) and OSS alternatives such as prometheus since there's an explosion of metric names and labels are no longer available to make aggregating across them easy.
This was resolved by creating a custom image with the correct bootstrap configuration, but questions remain as to why it was fully necessary (if it was indeed necessary) and if there's anything can be done to either patch istio or otherwise make this easier in the future (see questions).

Questions (substantiated and explained by next section):
- are [these regex patterns](https://github.com/istio/istio/blob/02bea7d38d063d541fb97dc4c18bde86ac8fbb6f/tools/packaging/common/envoy_bootstrap.json#L55-L62) indeed no longer correct?
  - if so, should they be either a) updated to better reflect the values now presented by istio as `stat_prefix` (detailed above, but quick link [here](https://github.com/istio/istio/blob/02bea7d38d063d541fb97dc4c18bde86ac8fbb6f/pilot/pkg/networking/core/v1alpha3/listener.go#L1350)), or b) should they simply be removed as the `http.*` metrics aren't enable by default?
- is there a preferred or better approach I should have followed and should follow the next time around?
- would StatConfig have worked in this case (and I just stopped short of success without this fuss)?

### Lengthy explanation
This was discovered when enabling extra metrics via `proxyStatsMatcher` (config found [here](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/)) to expose [tracing metrics](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats#tracing-statistics) but applies to anything found under the [envoy http connection manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats), `http.*`,  and listener-http stats, `listener.<stat_prefix>.http.*`.

This is a sample of the emitted metrics given the config, `'meshConfig.defaultConfig.proxyStatsMatcher.inclusionRegexps[0]=^http.*'`.
What envoy emitted:
```
http.InboundPassthroughClusterIpv4.tracing.client_enabled
http.inbound_0_0_0_0_80.tracing.client_enabled
```
What istio exposed via prometheus:
```
envoy_http_InboundPassthroughClusterIpv4_tracing_client_enabled{} 0
envoy_http_inbound_0_0_0_0_80_tracing_client_enabled{} 0
```
What I expected from prometheus:
```
envoy_http_tracing_client_enabled{http_conn_manager_prefix="InboundPassthroughClusterIpv4"} 0
envoy_http_tracing_client_enabled{http_conn_manager_prefix="inbound_0_0_0_0_80"} 0
```

What envoy emits as the `stat_prefix` and what the bootstrap `stats_config.stats_tags[]` are configured to remove and add as tags do not match, as shown by the example.

After following the guidance laid out in the [envoy doc for stats_tags](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#envoy-v3-api-msg-config-metrics-v3-tagspecifier), I tracked down the source of `stat_prefix` within istio and found that according to the code, [the regex will never practically match anything istio generates](https://github.com/istio/istio/blob/02bea7d38d063d541fb97dc4c18bde86ac8fbb6f/pilot/pkg/networking/core/v1alpha3/listener.go#L1350) (need to follow the code slightly beginning at this point) that I can see. Based on the [git blame for the two lines](https://github.com/istio/istio/blame/54aa1b4ea6e2c12a7e78614d05b7d6afc4c09300/tools/packaging/common/envoy_bootstrap.json#L55-L62) I linked above and the [doc istio publishes on stats it enables envoy to emit by default](https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/), my suspicion is that this may once have worked but no longer does and went unnoticed as `http conn manager` isn't part of that default list.

Regardless, I set off to find a solution, creating a new `stat_prefix` regex to extract the values as istio is configuring them, which I generalized best I could to encompass existing vocabulary while not boxing out future possible changes ([regex examples](https://regex101.com/r/YA7AeZ/1)):
```
http\.(([a-zA-Z0-9-]*?_(?:[.0-9]*|[\[\]_aAbBcCdDeEfF0-9]*)*?_[0-9]*?|[a-zA-Z0-9_-]*?)\.)
```

I got this to work by patching the existing template file and creating a custom image based on istio/proxyv2, pegged to the versions I worked with, ranging from 1.10 to 1.15. I then simply provided this new hub + tag to `istioctl` to generate my manifests and come to the expected result.

However, I tried a number of paths prior to this with no success:
- `EnvoyFilter` by modifying the `BOOTSTRAP` config
  - didn't work: can't `MERGE` the list with the same name bc envoy rejects the duplicate entries
  - workaround exists: simply name it something else...but then there's duplicates trying to perform the same function which is certainly not ideal
  - (tangentially, this was not a straight line: `BOOTSTRAP` EnvoyFilters need to be enabled via env var, [BOOTSTRAP_XDS_AGENT](https://github.com/istio/istio/blob/6b9ff67b4fd297523d29485e4d1288ad216cc7d6/manifests/profiles/preview.yaml#L13-L14) which afaict isn't documented anywhere -- certainly not in the [EnvoyFilter reference](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) 😢)
- use `meshConfig.defaultConfig.extraStatTags`
  - ran afoul of the simple issue that the bootstrap config doesn't allow this config the expressiveness to extract tags from the name directly, [per here](https://github.com/istio/istio/blob/54aa1b4ea6e2c12a7e78614d05b7d6afc4c09300/tools/packaging/common/envoy_bootstrap.json#L71-L76), and so wasn't useful
- use [StatsConfig](https://istio.io/latest/docs/reference/config/proxy_extensions/stats/)
  - semantics were unclear, and risked spending more time on this than I could at the time
  - would this have been a viable solution?

### Quick repro
This is for istio 1.15 but the process is nearly identical for 1.10 through 1.15:
- change the Dockerfile `FROM` command to match the correct istio version
- change the curl URL for the bootstrap config file

(I did this end to end and it worked so 🤞 it does for anyone else too)

```zsh
# needed colima bc I'm on an ARM chip and istio 1.10 doesn't ship with an arm build (where I started);
# for posterity, colima uses qemu and made sane emulation of the environments possible;
# it's easy and it works: who can argue at that point?
# `brew install colima`
colima start --arch x86_64

# install and expose the http metrics
istioctl install \
  --set components.pilot.k8s.resources.requests.memory=256Mi \
  --set 'meshConfig.defaultConfig.proxyStatsMatcher.inclusionRegexps[0]=^http.*'

# envoy metrics + grep for http
kubectl exec -n istio-system \
  deployment/istio-ingressgateway \
  -- curl http://localhost:15000/stats | grep '^http\.'

# prometheus + grep for http
kubectl exec -n istio-system \
  deployment/istio-ingressgateway \
  -- curl http://localhost:15090/stats/prometheus | grep '^envoy_http_'

# get the bootstrap file for istio 1.15
curl -L https://raw.githubusercontent.com/istio/istio/1.15.1/tools/packaging/common/envoy_bootstrap.json \
  -o envoy_bootstrap_tmpl.json

# patch in the diff
cat <<'EOF' | patch envoy_bootstrap_tmpl.json
--- /dev/stdin	2022-09-28 16:50:49.000000000 -0600
+++ ./envoy_bootstrap_tmpl.json	2022-09-28 16:47:22.000000000 -0600
@@ -54,11 +54,11 @@
       },
       {
         "tag_name": "http_conn_manager_listener_prefix",
-        "regex": "^listener(?=\\.).*?\\.http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
+        "regex": "^listener(?=\\.).*?\\.http\\.(([a-zA-Z0-9-]*?_(?:[.0-9]*|[\\[\\]_aAbBcCdDeEfF0-9]*)*?_[0-9]*?|[a-zA-Z0-9_-]*?)\\.)"
       },
       {
         "tag_name": "http_conn_manager_prefix",
-        "regex": "^http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
+        "regex": "^http\\.(([a-zA-Z0-9-]*?_(?:[.0-9]*|[\\[\\]_aAbBcCdDeEfF0-9]*)*?_[0-9]*?|[a-zA-Z0-9_-]*?)\\.)"
       },
       {
         "tag_name": "listener_address",

EOF

# build an image, quick and dirty
cat <<EOF > istio-patched.Dockerfile
# 1.15.1
FROM docker.io/istio/proxyv2@sha256:4a05f7289bf612d43167ec74c35d0968fa17a50bdf2b8b5023c263b6aab6c5fd
COPY envoy_bootstrap_tmpl.json ./var/lib/istio/envoy/envoy_bootstrap_tmpl.json
EOF

# push not required if using colima -- update for your needs
docker build -t docker.io/doesnotmatter/proxyv2:1.15.1 -f istio-patched.Dockerfile .

# set the global tag for all the proxies, gateways but skips pilot
istioctl install \
  --set tag=1.15.1 \
  --set hub=docker.io/doesnotmatter \
  --set components.pilot.hub=docker.io/istio \
  --set components.pilot.tag=1.15.1 \
  --set components.pilot.k8s.resources.requests.memory=256Mi \
  --set 'meshConfig.defaultConfig.proxyStatsMatcher.inclusionRegexps[0]=^http.*'

# envoy + grep: should look same as before
kubectl exec -n istio-system \
  deployment/istio-ingressgateway \
  -- curl http://localhost:15000/stats | grep '^http\.'

# prometheus + grep: notice the label and updated metric names!
kubectl exec -n istio-system \
  deployment/istio-ingressgateway \
  -- curl http://localhost:15090/stats/prometheus | grep '^envoy_http_'
```

### Version

```prose
$ istioctl version
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (2 proxies)
$ kubectl version --short
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.23.6+k3s1

# These are from my reproducibility environment, but are reflective of live envs I work with in both istio and k8s versions, apart from the use of k3s (in colima)
```

**Comment by zirain** [comment]
> didn't work: can't MERGE the list with the same name bc envoy rejects the duplicate entries 

this will be fixed in next release, linked to upstream change https://github.com/envoyproxy/envoy/pull/23024

**Comment by parkedwards** [comment]
i'm experiencing the same thing -- actually, I was a little less thorough than @dmarkwat, as I only toyed with `inclusionPrefixes` and `inclusionSuffixes`, as well as experimented with setting `inboundClusterStatName` / `outboundClusterStatName`

However, it remains that the resulting envoy stats -> prometheus metrics show a crazy fan-out.  Most time series that get created in Prometheus have network-specific labels embedded into the metric name, which adds to sprawl and generally makes it hard to aggregate on these values (which really should be labels).  I didn't even bother with the regexp route, which based on OP's experience, doesn't work.

![image](https://user-images.githubusercontent.com/19556538/207994784-259d74d4-a0f2-438d-9ed3-db3b7eaa8866.png)

and it's not really clear form the documentation if this is a (1) configuration problem, where we need to set some custom `stat_prefix` or (2) an issue with how istio parses envoy stats and creates telemetry
