### ISSUE TITLE
Ambient: no iptables rules generated in bridge network

### ISSUE THREAD

**Issue by imroc** [istio/istio#41217]
### Bug Description

install-cni will not apply iptables rules if kubernetes uses bridge network, error log in install-cni:
```log
2022-09-29T12:07:54.733529Z	error	ambient	Failed to get device for ztunnel ip: no routes found	type=add
```

### Version

```prose
build with latest commit on experimental-ambient branch: https://github.com/istio/istio/commit/842fef276777d9c9ea7eb9864047c48df9b6f06f
```

**Comment by imroc** [comment]
# Root Cause

The error log corresponds to this line of code: https://github.com/istio/istio/blob/842fef276777d9c9ea7eb9864047c48df9b6f06f/cni/pkg/ambient/informers.go#L216

The key point is here: https://github.com/istio/istio/blob/842fef276777d9c9ea7eb9864047c48df9b6f06f/cni/pkg/ambient/net.go#L180

```go
	routes, err := netlink.RouteListFiltered(
		netlink.FAMILY_V4,
		&netlink.Route{Dst: &net.IPNet{IP: net.ParseIP(ip), Mask: net.CIDRMask(32, 32)}},
		netlink.RT_FILTER_DST)
```

Use `netlink.RouteListFiltered` to filter route, the returned `routes` will always be empty if it's bridge network.

For instance:
1. podCidr on node A is `172.29.0.0/24`
2. ztunnel pod allocated ip with `172.29.1.6`
3. install-cni got ztunnel pod ip on node A (`172.29.1.6`), find the device name that could route to that ip.
4. Use `netlink.RouteListFiltered`  to filter route, filter is `172.29.1.6/32`, the closest match is `172.29.0.0/24`, but `netlink.RouteListFiltered` uses the exact match, so no route will be returned, then return error "no routes found".

## How to Fix

Use this to filter route:
```go
	routes, err := netlink.RouteGet(net.ParseIP(ip))
```

Will submit a PR to fix it.

**Comment by imroc** [comment]
@dhawton

**Comment by dhawton** [comment]
Unfortunately, bridged networking goes well beyond just getting ztunnel's IP and won't work with the redirection code as it exists today. We're working on a much larger fix.

**Comment by imroc** [comment]
Got it, looking forward to the larger fix.

**Comment by imroc** [comment]
I'm curious why the bridged networking won't work with the redirection code as exists today, it should make no difference from the packet route path. What is the core reason and what is the idea of "the larger fix", maybe I can help.

@dhawton @howardjohn
