### ISSUE TITLE
Istiod causes a full push when you use custom-metrics based autoscaling (frequent annotation changes on a service)

### ISSUE THREAD

**Issue by treyhyde** [istio/istio#41222]
### Bug Description

I get near constant pushes to proxies, full and partial.
Istiod is pretty much pegged at 60MB/s 24/7 on a ~88 proxy cluster causing significant egress/ingress charges in AWS (cross az)

```
2022-09-29T17:29:43.741620Z	info	ads	Push debounce stable[11041] 2 for config ServiceEntry/xxx/some-service: 100.886166ms since last change, 100.888961ms since last push, full=true
```

The services that spam that debounce log line are most frequently those associated with metrics based autoscaling. (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#container-resource-metrics)

The HPA frequently annotates the services with the current values via the following annotations.
```
autoscaling.alpha.kubernetes.io/behavior
autoscaling.alpha.kubernetes.io/current-metrics
autoscaling.alpha.kubernetes.io/metrics
```

current-metrics, contains... the current metrics, which are evaluated and annotated very frequently.   This action appears to cause a full push even if endpoints/replicas have not changed.

### Version

```
client version: 1.15.0
control plane version: 1.15.1
data plane version: 1.15.1 (88 proxies)
```

**Comment by treyhyde** [comment]
@howardjohn Did I capture our conversation accurately?

**Comment by treyhyde** [comment]
Related to #38896

**Comment by howardjohn** [comment]
Not stale, marking as help wanted
