### ISSUE TITLE
Istioctl Manifest Generate Not Generating K8s 1.25 Compatible Manifest

### ISSUE THREAD

**Issue by diarmuidie** [istio/istio#41220]
### Bug Description

We install Istio by first generating a YAML manifests using `istioctl manifest generate` and then applying that to the cluster.

When running `istioctl manifest generate` to generate the manifest files for installing Istio it does not include the Kubernetes 1.25 compatible resources (HorizontalPodAutoscaler autoscaling/v2 and PodDisruptionBudget policy/v1) (added in https://github.com/istio/istio/pull/39895) instead it generates a manifest with resources that are no longer present in Kubernetes 1.25 (autoscaling/v2beta1 and policy/v1beta1)

As far as I can tell there is no way to tell the generate command what version of Kubernetes is being targeted by the manifests.

### Version

```prose
$ istioctl version
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (2 proxies)

$ kubectl version
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.22
```

**Comment by hanxiaop** [comment]
This https://github.com/istio/istio/pull/40548 has been merged, and you'll be able to use cluster settings with the new flag.
