### ISSUE TITLE
Colleagues, good afternoon, I often catch these errors in istio-sidecar

### ISSUE THREAD

**Issue by selfing12** [istio/istio#41246]
### Bug Description
I did not add any additional settings to istio for the rate limit. istio 1.15

warn xdsproxy upstream [63] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline

warning envoy config StreamAggregatedResources gRPC config stream closed: 8, request rate limit exceeded: rate: Wait(n=1) would exceed context deadline (previously 14, error reading from server: EOF since 0s ago)

### Version

```prose
istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (291 proxies)

kubectl version --short
Client Version: v1.21.8
Server Version: v1.21.8
```

**Comment by howardjohn** [comment]
XDS connections are limited to 25 new connections/second. If you want more than that for massive scaling burst you can set PILOT_MAX_REQUESTS_PER_SECOND, or scale up more istiod instances. But typically 25 has been shown to be ideal. It will retry

**Comment by selfing12** [comment]
PILOT_MAX_REQUESTS_PER_SECOND add variable where and where?
can you please tell me the location?
@howardjohn

**Comment by selfing12** [comment]
```
2022-10-03T21:16:55.251110Z	warn	xdsproxy	upstream [21] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
2022-10-03T21:16:55.251580Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 8, request rate limit exceeded: rate: Wait(n=1) would exceed context deadline (previously 14, connection error: desc = "transport: Error while dialing dial tcp 10.234.36.188:15012: connect: connection refused" since 0s ago)
2022-10-03T21:16:55.251681Z	error	xdsproxy	upstream [21] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF
```
Errors come in a bunch, adding a variable to the pilot will fix the problems?

**Comment by selfing12** [comment]
> > ```
> > 2022-10-03T21:16:55.251110Z	warn	xdsproxy	upstream [21] terminated with unexpected error rpc error: code = ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
> > 2022-10-03T21:16:55.251580Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 8, request rate limit exceeded: rate: Wait(n=1) would exceed context deadline (previously 14, connection error: desc = "transport: Error while dialing dial tcp 10.234.36.188:15012: connect: connection refused" since 0s ago)
> > 2022-10-03T21:16:55.251681Z	error	xdsproxy	upstream [21] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ошибки приходят кучей, добавление переменной в пилот исправит проблемы?@howardjohn
> 
> @selfing12У меня такая же проблема, вы смогли ее решить?

I managed to solve the problem by adding the PILOT_MAX_REQUESTS_PER_SECOND variable to the deployment istiod with a value of 100, but sometimes errors still pop up.

**Comment by michelec1000** [comment]
@howardjohn thanks for the clarity, just out of curiosity, the error log
`error	xdsproxy	upstream [21] send error for type url type.googleapis.com/envoy.config.cluster.v3.Cluster: EOF`
did not arise from the rate limit?
