### ISSUE TITLE
consistentHash minimumRingSize must be integer

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#41256]
### Bug Description

minimumRingSize is [uint64](https://github.com/istio/api/blob/1.14.4/networking/v1alpha3/destination_rule.pb.go#L1951), which [when encoded would be a string](https://github.com/protocolbuffers/protobuf/issues/2679).
However, the DestinationRule CRD [only allows integer](https://github.com/istio/istio/blob/1.14.4/manifests/charts/base/crds/crd-all.gen.yaml#L333) which results in our encoded istio manifests failed to be applied.

```
ValidationError(DestinationRule.spec.trafficPolicy.portLevelSettings[0].loadBalancer.consistentHash.minimumRingSize): invalid type for io.istio.networking.v1beta1.DestinationRule.spec.trafficPolicy.portLevelSettings.loadBalancer.consistentHash.minimumRingSize: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false : exit status 1
```

Does it make sense to change the CRD to allow both integer and string, something like the following:
```
  minimumRingSize:
    anyOf:
      - type: integer
      - type: string
    x-kubernetes-int-or-string: true
```

I can make the change if this makes sense. I think we should change for all uint64 types.

### Version

```prose
1.14
```

**Comment by howardjohn** [comment]
So protobuf itself accepts string or int in this case? That is unexpected... if so I suppose we should make our CRD match it..

**Comment by yingzhuivy** [comment]
> So protobuf itself accepts string or int in this case? That is unexpected... if so I suppose we should make our CRD match it..

looks like so, I tested changing the crd definition to allow both int and string. And the istio generated envoy config looks the same when minimumRingSize is set as string and as int.

**Comment by hzxuzhonghu** [comment]
@howardjohn It seems we can update the cue-gen to change all uint64 or int64 type to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#intorstring


And can use similar tag as preserveUnknownFields `// +cue-gen:XXX:preserveUnknownFields:fieldB,fooBaz.qux.[].value` to explicitly declare which field to be `intOrString`

`// +cue-gen:XXX:intOrString:fieldB,fooBaz.qux.[].value`

**Comment by hzxuzhonghu** [comment]
And @jasonwzm implemented preserveUnknownFieldVisitor, we can implement a `intOrStringFieldVisitor` to update the schema

**Comment by howardjohn** [comment]
Why do we need preserveUnknownFields for intorstr?

I am pretty sure its valid to change a proto type from int64 to int32, maybe we could just drop it? unless we think users are using too large numbers I guess

**Comment by hzxuzhonghu** [comment]
>Why do we need preserveUnknownFields for intorstr?


We donot need it, I just take it as an example to refer

**Comment by howardjohn** [comment]
I see, seems reasonable if it works. We will need to make sure both int and string are correctly unmarshalled by Istiod.

otherwise we can move to 32bit and ban 64bit everywhere?

**Comment by mk2taiga** [comment]
I have created a new Issue. Ref: https://github.com/istio/api/issues/3445

When will this issue be resolved?
