### ISSUE TITLE
Support multiple scraping endpoints in Metrics Merging

### ISSUE THREAD

**Issue by wentwog** [istio/istio#41276]
**Describe the feature request**
Istio has Metrics Merging feature: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging
Currently it supports scraping metrics from just one app container.
We have a case when we have more than one container exposing metrics in a pod behind Istio.

**Describe alternatives you've considered**
Alternative is not to use the Metrics Merging, let Prometheus to scrape the container's endpoints directly, but then you have to add Istio sidecar to Prometheus, if your apps are behind strict mTLS - https://istio.io/latest/docs/ops/integrations/prometheus/#option-2-customized-scraping-configurations

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by georgiiturevich-uw** [comment]
There was a PR which suggested  a possible solution https://github.com/istio/istio/pull/34558

**Comment by xvzf** [comment]
Hey

Can we bring this up again?

**Comment by zirain** [comment]
I'd like to wait for https://github.com/prometheus/prometheus/issues/3756.

**Comment by kaiohenricunha** [comment]
For anyone landing here looking for a workaround: I built a lightweight sidecar that scrapes all container `/metrics` endpoints over localhost (bypassing mTLS), merges them with `origin_container` labels, and re-exposes on a single port for Istio to pick up.

Works under `STRICT` mTLS — tested in CI with a multi-container pod + istio-proxy.

https://github.com/kaiohenricunha/metrics-aggregator

**Comment by kaiohenricunha** [comment]
Update for anyone landing here: Istio 1.31 added native multi-target metrics merging via `prometheus.istio.io/scrape-targets`.

A pod can now declare multiple `port:path` targets, which `istio-agent` scrapes and merges into the existing `:15020/stats/prometheus` endpoint.

Implemented in #59567 via #59924, #59925, and #60468.

Release notes:
https://istio.io/latest/news/releases/1.31.x/announcing-1.31/change-notes/#telemetry
