### ISSUE TITLE
AuthorizationPolicy

### ISSUE THREAD

**Issue by Waddah-Ahmad** [istio/istio#41290]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
hello
I noticed while I'm setting the AuthorizationPolicy files that 
 when:
      - key: request.auth.claims[is_streamer]
        values: [\"true\" , "hi"] 
    or
values: [true]  [this one gives errors] [boolean value not accepted]
or values: ["true" ] 
not matching my label in jwt token which is 
{******************  
"email": "xx@gmail.com",
  "is_streamer": true,
****************}
in case I tried to do it with the email field , it works
so the issue: NOT ABLE TO MATCH WITH JWT LABEL WITHOUT [double quote , ("")]
thanks for your time

**Comment by aryan16** [comment]
sorry I didn't understand your question, are you not able to use boolean jwt claim in authz policy ?
