### ISSUE TITLE
The creation of the agent's SDS server is non-deterministic if SPIRE and Istio are started by helm

### ISSUE THREAD

**Issue by KenHuffmanAtNice** [istio/istio#41308]
### Bug Description

The istio-agent/agent.go code checks whether the security.WorkloadIdentitySocketPath exists before starting the Istio SDS server to create that socket.

When using helm to install Istio and SPIRE, the order in which SPIRE and Istio are started is non-deterministic, so this may cause the Istio agent to incorrectly create the socket if SPIRE is started after Istio.

There should be some sort of optional explicit configuration that inhibits the startup of the SDS server by agent.go even when that socket doesn’t yet exist because SPIRE hasn't gotten around to it. 

### Version

```prose
istioctl version: 1.14.3
kubectl Server Version: v1.22.13-eks-15b7512
```

**Comment by KenHuffmanAtNice** [comment]
This is coding change for the solution which adds an optional flag to disable Istio's creation of the socket

[](https://github.com/istio/istio/compare/master...KenHuffmanAtNice:istio-istio:master)

**Comment by zirain** [comment]
seems reasonable, can you raise a PR?

**Comment by KenHuffmanAtNice** [comment]
> seems reasonable, can you raise a PR?

https://github.com/istio/istio/pull/41440

**Comment by KenHuffmanAtNice** [comment]
The PR has been closed without merging. I have a better solution that does not require Istio modifications. We had success adding an initContainer with an k8s.overlay in the IstioOperator. The `mountPath` and `CHECK_FILE` should match where the workload-socket is being mounted by the existing patch for SPIRE.

    ingressGateways:
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: spec.template.spec.initContainers
                value:
                  - name: wait-for-spire-socket
                    image: busybox:1.28
                    volumeMounts:
                      - name: workload-socket
                        mountPath: /run/secrets/workload-spiffe-uds
                        readOnly: true
                    env:
                      - name: CHECK_FILE
                        value: /run/secrets/workload-spiffe-uds/socket
                    command:
                      - sh
                      - "-c"
                      - |-
                        echo `date -Iseconds` Waiting for: ${CHECK_FILE}
                        while [[ ! -e ${CHECK_FILE} ]] ; do
                          echo `date -Iseconds` File does not exist: ${CHECK_FILE}
                          sleep 15
                        done
                        ls -l ${CHECK_FILE}
