### ISSUE TITLE
Sidecar service cache consistent behavior

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#41319]
Istio has an inner SidecarScope  struct, it contains both services slice and map. 
```
type SidecarScope struct {
        ...
	// Union of services imported across all egress listeners for use by CDS code.
	services           []*Service
	servicesByHostname map[host.Name]*Service
        ....
}
```

1. For services with same hostname residing in different namespace(service entry defined in two namespaces), it may pick an arbitrary one.  This has caused issue https://github.com/istio/istio/issues/40952, because DestinationRule selecting is also related to service and proxy namespace.

**Question:  should we keep services in different namespaces?**

2. There is a inconsistent behavior for explicitly defined sidecar and no sidecar, we are merging ports of services  for the former, while the latter not.  FYI https://github.com/istio/istio/blame/cd553aeecbf5052a00885424bfff1deca7f29ac0/pilot/pkg/model/sidecar.go#L310-L330

**Question: should we merge ports for default sidecarScope build?**

**Comment by therealmitchconnors** [comment]
Appears to be related to https://github.com/istio/istio/pull/41062
