### ISSUE TITLE
Gatetway labels and selector can't be override using helm install 

### ISSUE THREAD

**Issue by rgaoistheone** [istio/istio#41320]
### Bug Description

I'm not sure if here is the right place to ask but I ran into some issue when trying to install istio ingressgateway using helm.
Like any other helm  package , i just ran 
`helm diff upgrade istio-ingressgateway istio/gateway -f values.yaml --allow-unreleased`
values.yaml
```
labels:
  app: ""
  istio: ""
  network-type: internet
```
After I ran diff , I noticed that the deployment and service selector didn't change.
```
spec:
+   selector:
+     matchLabels:
+       app: istio-ingressgateway
+       istio: istio-ingressgateway
```
Then I take a look at [https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/_helpers.tpl#L44](url). There is no merge/ add for Values.labels definitions. So just curious if this is by design like that and how to config a gateway with custom labels?  For now I just add a few lines like 
```
{{- define "gateway.selectorLabels" -}}
{{- if hasKey .Values.labels "app" }}
{{- with .Values.labels.app }}app: {{.|quote}}
{{- end}}
{{- else }}app: {{ include "gateway.name" . }}
{{- end }}
{{- if hasKey .Values.labels "istio" }}
{{- with .Values.labels.istio }}
istio: {{.|quote}}
{{- end}}
{{- else }}
istio: {{ include "gateway.name" . | trimPrefix "istio-" }}
{{- end }}
{{- range $key, $val := .Values.labels }}
{{- if not (or (eq $key "app") (eq $key "istio")) }}
{{ $key | quote }}: {{ $val | quote }}
{{- end }}
{{- end }}
{{- end }}
```

Any ideas?

### Version

```prose
helm version --short                                                                                                             
v3.6.3+gd506314
```

**Comment by zirain** [comment]
recommend use https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/#using-helm-with-kustomize-to-post-render-istio-charts

**Comment by zirain** [comment]
I write a simple demo https://github.com/zirain/playground/tree/master/istio/kustomize

**Comment by zirain** [comment]
please feel free to reopen if you have further questions.
