### ISSUE TITLE
Allow `%REQUESTED_SERVER_NAME%` to be set in `tunnel.targetHost`

### ISSUE THREAD

**Issue by jewertow** [istio/istio#41342]
**Background context**

Currently field `tunnel.targetHost` in a destination rule must be a valid FQDN. This implies that every external service which requires tunneling needs its own destination rule. It would be helpful making it possible to define single tunneling destination rule for all services.

**Requested solution**

This could be accomplished by allowing to set `%REQUESTED_SERVER_NAME%` in `tunnel.targetHost`, which automatically deduce host name from SNI.

**Backward compatibility**

As I mentioned, currently field `tunnel.targetHost` must be a valid FQDN, so there is no risk that introducing a special value will break already used configurations.

**Alternatives**

I don't see any alternative to solve this problem internally. If it comes to the API, we may also introduce a dedicated field to [TunnelSettings](https://istio.io/latest/docs/reference/config/networking/destination-rule/#TrafficPolicy-TunnelSettings), but I doubt that it would actually be better.

**Disadvantages**

`%REQUSTED_SERVER_NAME%` works only for TLS traffic, so it might be considered as a drawback, but I doubt that unecrypted traffic is widely used in production, if there is any at all...

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jewertow** [comment]
@howardjohn @costinm WDYT?

**Comment by ramaraochavali** [comment]
I think it is very reasonable as many of the tunneling use cases are TLS and most probably will have SNI. Do we have validation for FQDN/IP?

**Comment by jewertow** [comment]
> Do we have validation for FQDN/IP?

Yes, we do. This is the only thing we would need to change to enable this feature. And I guess comments for `TunnelSettings.targetHost` in istio/api.

**Comment by kfaseela** [comment]
This seems to be a reasonable improvement on the tunneling configuration. We are also looking into possibilities of using tunneling, and saving the number of DRs will be definitely useful. I believe this works well together with the auto_sni feature which we are already using!
