### ISSUE TITLE
pilot agent and istiod (and probably any other istio go based process) needs to set GOMAXPROCS to ~ cpu request/limit (x2?)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#41351]
### Bug Description

pilot agent and istiod (and probably any other istio go based process) needs to set GOMAXPROCS to ~ cpu request or limit (x2?)

we observed that the bigger the nodes the larger number of os threads in pilot-agent, it doesn't use the concurrency that the side car (envoy) itself is using/calculating resulting in extra resources consumed an inefficiencies on large nodes

note that it'd be nice for go to do that on it's own, for k8s to communicate somehow the request/limit to all go pods so as to not have to fix that for every single go deployment but that's likely not happening anytime soon, so in mean time we need to set GOMAXPROCS

Note: not sure if it should be 1x or 2x request (or max(limit, request) if either is set) rounded up to at least 1 or 2

At minimum it needs to be a big warning in the doc so it's to be set by users (but I think it should be set at same value as the request or limit in the charts and/or use a variable/same variable as for side car)

### Version

```prose
1.13.8 but same
```

**Comment by hzxuzhonghu** [comment]
make sense, https://github.com/uber-go/automaxprocs seems a good tool

**Comment by hobbytp** [comment]
agree, our company also set this value long ago in our other go products.

**Comment by ldemailly** [comment]
>  make sense, https://github.com/uber-go/automaxprocs seems a good tool

thanks for this pointer, while the perf section of the readme is useful to confirm it's a necessary change; the implementation. seems rather involved as well as relying (if I read it correctly) on cgroup limits which may or not be set - it's not uncommon to set say request at 1 vCPU and no limit - for which you'd want really the GOMAXPROCS to be 2 and not 192 when running on a 192 core machine with an hpa.

So I'd recommend we just set it to 2 (and btw maybe change istiod's default setting of 0.5 core request -> 1)

**Comment by ldemailly** [comment]
I verified that automaxprocs doesn't work if you don't have a limit (which given CPU is elastic and that cgroups throttling is actually expensive is not an uncommon setup) - so I recommend we just  set a reasonable value (2 or 4) and document it's important to keep it in sync with requests/limits/hpa

**Comment by ldemailly** [comment]
this is quite important

**Comment by 4wdonny** [comment]
bumping this, as I think we've been affected by the lack of this being set properly

**Comment by ldemailly** [comment]
I think I saw some new code about this somewhere but not sure

**Comment by zirain** [comment]
linked to https://github.com/istio/istio/pull/46253
