### ISSUE TITLE
Readiness probe failed Get "http://10.244.0.22:15020/app-health/xxxxxx/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by mark8s** [istio/istio#41366]
Hello everyone, I have a question. I just ran into a problem, my business container couldn't start after injecting the sidecar, it kept showing as CrashLoopBackOff .

Then I look at the pod details and it shows the following:

```shell
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  17m (x272 over 177m)    kubelet  Readiness probe failed: Get "http://10.244.0.22:15020/app-health/xx-controller/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Pulling    12m (x49 over 5h40m)    kubelet  Pulling image "registry.cn-shenzhen.aliyuncs.com/xx/xx-controller:v1.11.2"
  Warning  BackOff    2m19s (x564 over 168m)  kubelet  Back-off restarting failed container
```

I don't know how this works? What is the detection mechanism of the probe? Do I need to troubleshoot this?

My environment is istio 1.11.5

Can anyone help me?

**Comment by mark8s** [comment]
shit！ After I adjust the timeout of the probe, it seems to be solved.. .  But I still don't know how it works. . .

**Comment by DSP-doublehappy111** [comment]
I have met the same question several weeks ago. k8s default probe 1s. When the business volume in the cluster is high, the 1S is too late to respond, and Probe will think that it is unreachable, which will cause pod crash. You can set a opportune second. This  may not be a problem related to istio.

**Comment by mark8s** [comment]
@DSP-doublehappy111 Thanks, I temporarily solved it after I increased the probe detection time yesterday.
