### ISSUE TITLE
Support restricted VPCs on GCP

### ISSUE THREAD

**Issue by willowmck** [istio/istio#41370]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Users of [Private Google Access](https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity) will encounter issues in determining the Zone and Region of the platform as GCP support currently only supports the public-facing APIs.  See [this line of code](https://github.com/istio/istio/blob/81b063a771d5661125c41ad3552fa2d826fd4ffc/pkg/bootstrap/platform/gcp.go#L329) which hard codes the API.

This request is to provide a flag for restricted access to instead call the restricted APIs instead of the public APIs.  This would also require credentials required to access the restricted API.  

**Describe alternatives you've considered**
n/a

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
@willowmck is it possible to provide some examples for this? do you expect users to configure Istio with the required credential for private google access?

@howardjohn do you know if there is already a workaround for this?

Thanks!

**Comment by ckpklos** [comment]
@willowmck, is there a need for it? I'm using restricted VIP for GoogleApis + GKE and never had any issues. I use DNS to redirect *.googleapis.com and gcr.io to restricted IP range. https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity

**Comment by howardjohn** [comment]
This check is not even supposed to run on Kubernetes so I think the real root cause is the IsKubernetes() check is giving incorrect results?

**Comment by willowmck** [comment]
> @willowmck, is there a need for it? I'm using restricted VIP for GoogleApis + GKE and never had any issues. I use DNS to redirect *.googleapis.com and gcr.io to restricted IP range. https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity

Seems like a decent workaround to this problem.  Thanks!

**Comment by willowmck** [comment]
> 

Could be how this particular customer has modified their OpenShift installation.  They have a lot of security features turned on.  I can check what options they are using.

**Comment by willowmck** [comment]
They have now reported seeing the same problem with sidecar injection in that it times out waiting to get the GCP region.  Would setting `readiness.status.sidecar.istio.io/periodSeconds` to something long (e.g. 300) possibly help?

**Comment by linsun** [comment]
I think periodSeconds means: ```                    description: How often (in seconds) to perform the probe.
```

I'd recommend specify a higher value for failureThreshold. ```
                    description: Minimum consecutive failures for the probe to be
                      considered failed after having succeeded.```

**Comment by howardjohn** [comment]
Any option that makes the probe just allow >300s before a pod is ready seems bad. You don't want pods to take 300s to start.

**Comment by linsun** [comment]
yep, my thought as well @howardjohn! unfortunately, our doc isn't too clear, i had to research to find out exactly what `periodSeconds` means. I'll submit a doc PR.

**Comment by howardjohn** [comment]
cc @aryan16
