### ISSUE TITLE
istio-ca-root-cert not being created

### ISSUE THREAD

**Issue by sschepens** [istio/istio#41389]
### Bug Description

We're using External Cluster and recently upgraded to Istio 1.15.0 and started using `discoverySelectors` to limit the namespaces being discovered by Istio.

It now appears that Istio is not creating `istio-ca-root-cert` in new namespaces (it still remains created in old namespaces).

I don't know if this could be related to https://github.com/istio/istio/pull/41198 or if this is another issue related to `discoverySelectors` or 1.15.0

### Version

```prose
1.15.0
```

**Comment by kfaseela** [comment]
@irisdingbj any idea about this issue? just asking since External Clusteres were mentioned. @sschepens this has nothing to do with https://github.com/istio/istio/pull/41198

**Comment by sschepens** [comment]
@hzxuzhonghu do you know how I can get about at debugging this? I can't find any relevant logs

**Comment by sschepens** [comment]
I can only find the log "starting namespace controller for cluster " for the local cluster 🤔

**Comment by sschepens** [comment]
Hmm ok, it seems that we now have to annotate namespaces on remote clusters `$ kubectl annotate namespace external-istiod "topology.istio.io/controlPlaneClusters=${REMOTE_CLUSTER_NAME}" --context="${CTX_SECOND_CLUSTER}"`

I could not find any of this in the Release Notes, isn't this a breaking change?

**Comment by hzxuzhonghu** [comment]
cc @frankbu

**Comment by kfaseela** [comment]
@sschepens : is this related? https://github.com/istio/istio.io/pull/12097

**Comment by sschepens** [comment]
@kfaseela nope, doesn't seem related
