### ISSUE TITLE
NR filter_chain_not_found error with set host in gateway, with wildcard works fine.

### ISSUE THREAD

**Issue by gawsoftpl** [istio/istio#41380]
### Bug Description

I have a problem with Istio. When I install istioctl in kind or in minikube I always receive the below error when I try to connect with tls.

```
kubectl logs -n istio-system istio-ingressgateway-75f744967f-7r68j

[2022-10-12T05:43:16.541Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 1 - "-" "-" "-" "-" "-" - - 172.17.0.4:8443 172.17.0.1:35812 - -
[2022-10-12T05:43:40.630Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 1 - "-" "-" "-" "-" "-" - - 172.17.0.4:8443 172.17.0.1:35934 - -
[2022-10-12T05:43:46.927Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 1836 - "-" "-" "-" "-" "-" - - 172.17.0.4:8443 172.17.0.1:62931 - -
[2022-10-12T05:43:52.426Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 785 - "-" "-" "-" "-" "-" - - 172.17.0.4:8443 172.17.0.1:19021 - -

```
For reproduce error please use tutorial from istio website:
https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

This don't work
```yml
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpbin.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpbin-credential
      mode: SIMPLE
```

but when I change hosts in gateway to wildcard everything works fine
```yml
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpbin-credential
      mode: SIMPLE
```

Probably something is wrong with SNI, but I don't know what.

### Version

```prose
Istioctl
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (1 proxies)

Kubectl
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by gawsoftpl** [comment]
I resolved this by fix curl command:

```sh
curl -vk -HHost:httpbin.example.com --resolve "httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST" \
 "https://httpbin.example.com:$SECURE_INGRESS_PORT/status/418"
```

Error was because when run command with curl I have to use --resolve parameter.

**Comment by howardjohn** [comment]
Great!
