### ISSUE TITLE
Feature Request: Istio injection emit failed event in case of port collision 

### ISSUE THREAD

**Issue by SerenaTiede-Zen** [istio/istio#41388]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Istio admission webhook detects if a pod is using the the same ports as envoy proxy as seen [here](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio) prior to adding the side car to the given pod. Personally I would prefer to have the webhook ignore the pod and emit a failed injection event in the workload, so as a cluster admin I can follow up with the team.

**Describe alternatives you've considered**

Writing an Open Policy Agent (OPA) rule to block workloads that would result in a port collision. This works for my company since we have robust OPA infrastructure but for the broader community it would be nice to have this baked into the admission webhook logic.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Logs from the envoy proxy when there was contention for port 15001

```
{"level":"warn","time":"2022-09-23T04:35:40.617804Z","msg":"Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 146 successful, 0 rejected; lds updates: 0 successful, 145 rejected"}
{"level":"warn","time":"2022-09-23T04:35:42.621101Z","msg":"Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 146 successful, 0 rejected; lds updates: 0 successful, 145 rejected"}
{"level":"warning","time":"2022-09-23T04:35:43.127043Z","scope":"envoy config","msg":"error adding listener: 'virtualOutbound' has duplicate address '0.0.0.0:15001' as existing listener"}
{"level":"warning","time":"2022-09-23T04:35:43.129493Z","scope":"envoy config","msg":"gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualOutbound: error adding listener: 'virtualOutbound' has duplicate address '0.0.0.0:15001' as existing listener\n"}
```

**Comment by howardjohn** [comment]
This is impossible to do correctly. containerPort is essentially meaningless and has no relationship to what ports a pod actually binds to

**Comment by SerenaTiede-Zen** [comment]
> This is impossible to do correctly. containerPort is essentially meaningless and has no relationship to what ports a pod actually binds to

Yeah that was my fear. I know there's nothing stoping a pod from binding to a port not declared in containerPort. My question is using containerPort be good enough signal to noise ratio for most users?

**Comment by howardjohn** [comment]
Skipping injection is IMO a worse default for users anyways. Something
enforcing security policies shouldn't be fail open

**Comment by SerenaTiede-Zen** [comment]
Just getting back to this, I'll close this since I agree in the general case the current behavior is desirable. Also not a lot of people would run into this issue, and I have a decent-ish mitigation in place.
