### ISSUE TITLE
Allow setting response code when  `httpsRedirect: true` on Gateway

### ISSUE THREAD

**Issue by karlschriek** [istio/istio#41386]
This feature request is essentially the same as https://github.com/istio/istio/issues/15292#issuecomment-1184366786, which was in my opinion erroneously closed (I tried to revive it a few months ago, with no luck), since I am fairly certain it was actually asking for an implementation on the _Gateway_ resource, whereas the PRs that supposedly solved it dealt with VirtualService. I am inferring this from the fact that it refers specifically to `httpsRedirect` which is a field that can be set on a Gateway resource.

As per the docs (https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) setting  `httpsRedirect: true` on a Gateway will _always_ return a 301. This is problematic since the 301 will in many cases (although it depends on the interpretation of the client) change a POST to a GET. Being able to force this code to for example 308 would ensure that the original method continues to be used.

(Here is a pretty good experience-based write-up of what is happening here: https://rtfm.co.ua/en/http-redirects-post-and-get-requests-and-lost-data/) 

I would like to be able to set something like `httpsRedirectCode: 308` on the Gateway. Alternatively, if I am missing something and this is actually already supported somehow, please could this be documented somewhere?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jorgeperezc** [comment]
Hello @karlschriek,

I was also in your same situation and to get that behavior I defined two separate gateway resources for HTTP and HTTPS communication. And exactly the same for the virtualservices resources. In the virtualservice attached to the gateway for HTTP communication I directly specify redirect with status 308.

Something like that:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway
  namespace: config
spec:
  gateways:
  - gateway-http
  hosts:
  - "*"
  http:
  - name: xx
    redirect:
      redirectCode: 308
      scheme: https
```


The logical thing as you mention is that it could be defined in the gateway resource.

Regards, 
Jorge

**Comment by LS80** [comment]
@karlschriek Could you reopen the issue?
