### ISSUE TITLE
DNS optimized environments cannot work with the services ending with .svc:

### ISSUE THREAD

**Issue by eminaktas** [istio/istio#41396]
### Bug Description

Some Istio service addresses are defined like this example `istiod.istio-system.svc:15012`. However, this service cannot be resolved if your pod's `resolv.conf` is optimized as in the example below.

```bash
search svc.<cluster-name>
nameserver *omitted*
options ndots:2
```

Istio should only provide the service name with this format `<service-name>.<service-namespace>` to remove the confusion.

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.8.5
data plane version: 1.8.5 (31 proxies)
$ kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.20.7
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by saltbo** [comment]
ndots default is 5, for default, with .svc is better.

you can customizing the installation configuration

https://istio.io/latest/docs/setup/additional-setup/customize-installation/

**Comment by eminaktas** [comment]
> ndots default is 5, for default, with .svc is better.
> 
> you can customizing the installation configuration
> 
> https://istio.io/latest/docs/setup/additional-setup/customize-installation/

Yes, `ndots` option is 5 by default. But that doesn't mean having .svc is better. Because the search option comes like this by default.

```
search <namespace>.svc.<cluster-name> svc.<cluster-name> <cluster-name>
```

This means that the query can be resolved on the third try. So, removing the .svc part will make it better since it will be resolved on the second try.


> Resolver queries having fewer than ndots dots (default is 1) in them will be attempted using each component of the search path in turn until a match is found.
[resolv.conf(5)](https://man7.org/linux/man-pages/man5/resolv.conf.5.html)

**Comment by hzxuzhonghu** [comment]
sg, i forget why it svc was there. @costinm

**Comment by costinm** [comment]
Sorry, missed that. We add '.svc' beacause just podname.namespace may conflict with naming for pod, etc.

We don't use .svc.cluster.local because the last part can be customized by user ( there is an option somewhere, and in some cases it is good to do so if using a real DNS and real certs - for example prod.example.com ). We do support both .svc.cluster.local and .svc and svc.namespace in most configs, this is mostly about the certificate issued to istiod.
