### ISSUE TITLE
Warning | when PSP (Pod Security Policy) applied to Istio 

### ISSUE THREAD

**Issue by yugandhar-btc** [istio/istio#41402]
### Bug Description

Could you please help me, what would be the changes required in [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) as per the latest Kubernetes versions (from v.21+)

When I applied [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) for ISTIO pods it give me Warning

![image](https://user-images.githubusercontent.com/69250111/195558090-f1192f2f-2e27-417f-a30c-cf92261739eb.png)

### Version

```prose
Client Version: v1.23.4
Server Version: v1.22.12-gke.1200
```

**Comment by hzxuzhonghu** [comment]
PSP is a k8s resource not istio, and it is warned by k8s.  You should upgrade the version accordingly

**Comment by yugandhar-btc** [comment]
@hzxuzhonghu Can you please look in [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) as it is written Based on https://github.com/istio/istio/issues/6806#issuecomment-406230278

**Comment by hzxuzhonghu** [comment]
please file a request to upgrade it in that repo.

**Comment by yugandhar-btc** [comment]
@hzxuzhonghu is it same Repo https://github.com/istio/istio/issues/6806#issuecomment-406230278

**Comment by hzxuzhonghu** [comment]
I cannot understand  why https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml apply with warning has anything todo with istio

**Comment by yugandhar-btc** [comment]
@hzxuzhonghu this  is our Repo  https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml and [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) was written based on the https://github.com/istio/istio/issues/6806#issuecomment-406230278 (which is istio Repo) and we are facing Warn when we applied to  pod_security_policy-istio.yaml.

**Comment by hzxuzhonghu** [comment]
you can just upgrade the version for psp, so what would you want from istio?

**Comment by yugandhar-btc** [comment]
i have changed the version and applied from policy/v1beta1 to policy/v1

**error: unable to recognize "pod_security_policy-istio.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1"**

**Comment by hzxuzhonghu** [comment]
https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by yugandhar-btc** [comment]
@hzxuzhonghu we have that URL, and we are not expecting URL form you
