### ISSUE TITLE
Need precommit (or similar) check for dashboards

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#4142]
We should automatically have the `fix_datasources.sh` script run for all updates to the dashboards.

cc: @jeffmendoza

**Comment by jeffmendoza** [comment]
Sounds good, I will check the latest Grafana version to see if the script is still needed first.

**Comment by jeffmendoza** [comment]
I checked the latest version and it sill requires the script to go from export to provisioning, so I'll move forward with the check.

#4254
