### ISSUE TITLE
Istio Operator Image Size = 0 Bytes

### ISSUE THREAD

**Issue by mxkmp** [istio/istio#41432]
I currently try to install the Istio Operator with Version 1.15.2 inside of our cluster, but if I try to fetch it it does not work for the tag 1.15.2. I looked into and it appears that the image size is equals 0 bytes -> https://console.cloud.google.com/gcr/images/istio-release/global/operator@sha256:d1e6a703203cc02f063624325025ac858f0c73ed49d268d421f7ac2187e5675e/details

**Comment by zirain** [comment]
try `docker pull istio/operator:1.15.2`?

**Comment by mxkmp** [comment]
Works thanks!
