### ISSUE TITLE
Intermittent 503 errors due to connection being terminated between Istio-proxy sidecar and app container.

### ISSUE THREAD

**Issue by sugunmachipeddy** [istio/istio#41443]
### Bug Description

We have a production cluster running Kubernets v1.21 with Istio 1.13.5 as our service mesh. Many of our API’s with istio sidecars enabled are experiencing intermittent 503 errors with a response of ‘upstream connect error or disconnect/reset before headers. reset reason: connection termination’ .  Looking at the Istio proxy as well as the APP logs, the connection between the istio proxy and app container seems to be terminating for some reason. The App container receives and processes the request,  but istio-proxy fails to register the response. It records the response code as HTTP Code 0 and the remaining header values as NULL. This results in cascading 503 errors on our LoadBalancer. There seems to be a pattern in the occurrence of these 503 errors. They happen at approximate intervals of 10-20 mins.

 

### Version

```prose
$ kubectl version --short
Client Version: v1.20.4
Server Version: v1.21.14-gke.2700

$ istioctl version
istiod version: 1.12.5
istiod version: 1.13.5
data plane version: 1.13.5 (1508 proxies), 1.12.5 (35 proxies)
```

### Additional Information

In the past, we have also tried increasing the `keepaliveMaxServerConnectionAge` to 12h, but that did not resolve the issue. We also looked at the tcpdump of both the istio proxy and app container which were not conclusive enough, In the timeframe of the 503 errors, we found errors such as ‘tcp acked unseen segment, tcp port numbers reused and tcp retransmission for packets’. But, these errors occur when there are no 503 errrors as well.

**Comment by razorsk8jz** [comment]
We have also seen this same issue using istio 1.15.3 and 1.16.2

**Comment by echoava** [comment]
we also seen this issue using istio.1.16. Can we reopen ? Thanks
