### ISSUE TITLE
TestVerifyCert fails

### ISSUE THREAD

**Issue by wattli** [istio/istio#4144]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/4066/istio-unit-tests/1885/

The certs are expired, we need certs with much longer lifetime, e.g. 100 years or something.

https://github.com/istio/istio/blob/d59633bc0bd33315900631ac84d13bf28ad3a5e4/security/pkg/pki/util/verify_cert_test.go#L152

**Comment by wattli** [comment]
https://github.com/istio/istio/pull/4152#pullrequestreview-102787113 disabled that test, we will add it back with a fix

**Comment by incfly** [comment]
Reopen to add add the test back.
