### ISSUE TITLE
Call ConvertToSidecarScope function with multiple goroutines

### ISSUE THREAD

**Issue by wulianglongrd** [istio/istio#41453]
**Describe the feature request**

Reduce the time consumption of the `initSidecarScopes` function.

**Describe alternatives you've considered**

In our production environment, we found that it takes about 25 seconds for configuration changes to take effect, which is mainly consumed in `initSidecarScopes` calling the `ConvertToSidecarScope` function repeatedly. I read the code of the `ConvertToSidecarScope` function, which is only used for data conversion, and it looks like it's safe to call it concurrently using multiple goroutines. So, is it suitable to use multiple goroutines for concurrent processing?

Concurrent processing will bring more cpu and memory consumption, in exchange for the configuration to take effect sooner, it is worthwhile in our usage scenario.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Great you catch the bottleneck, curious what is the scale in your env

**Comment by 12345XXX** [comment]
ConvertToSidecarScope seems to occupy a lot of CPU. We have observed that it will occupy about 2 cores in our scenario. In a large-scale scenario, will multiple goroutines occupy all the CPU?

**Comment by ramaraochavali** [comment]
How many sidecars do you have?

**Comment by zirain** [comment]
this would be helpful with lazyxds project like [slime lazyload](https://github.com/slime-io/slime/blob/master/staging/src/slime.io/slime/modules/lazyload/README.md) and [aeraki lazyxds](https://github.com/aeraki-mesh/lazyxds)

**Comment by wulianglongrd** [comment]
@hzxuzhonghu @ramaraochavali  vs 1600+, dr 4800+, se 220+, sidecar 4000+. vs/dr/sidecar both have 4 namespaces, se has only one default namespace. This is a small part of our business, and we are preparing for growth in the next six months.

**Comment by sschepens** [comment]
I'm not thinking specifically about delta, I just said it because delta works that way.
 
 What I mean is that we could only just process diffs (deltas) of change and not just reprocess everything on every single change.

**Comment by howardjohn** [comment]
We already do that at a more granular level (if NO sidecars change we don't
recompute it), so it is certainly plausible

**Comment by yingzhuivy** [comment]
+1 we saw the same issue, we have more than 10k sidecars and it took roughly 30s to compute the sidecar scope, causing the init context time to be larger than 30s and hence propagation delay > 30s. I tried compute the sidecar scopes with 10 workers (we have 32cores) on our dev box and it can reduce the init context time to 5s.

**Comment by wulianglongrd** [comment]
This year, we have made some performance optimizations to the `ConvertToSidecarScope` function (#47637, #47845, #46043, #47812). But currently in our production environment, this function is still the biggest performance bottleneck. It has been reopened to explore other optimization ideas.

**Comment by sschepens** [comment]
@wulianglongrd have you tried my PR https://github.com/istio/istio/pull/47221 ? Made a huge impact for us

**Comment by wulianglongrd** [comment]
> @wulianglongrd have you tried my PR #47221 ? Made a huge impact for us

not yet, will take a look, thanks.

**Comment by wulianglongrd** [comment]
fixed by #48461
