### ISSUE TITLE
configure max_ejection_time in outlier detection check

### ISSUE THREAD

**Issue by ankitdiscovery** [istio/istio#41455]
While using outlier detection i found out the behaviour of `baseEjectionTime` , which can extend its value up to `maxEjectionTime` (which is 5 m default value). what if this 5 minutes value of ejectionTIme is not suitable for a use case .how can i custom configure this `maxEjectionTime` in destinatioRule  up to 1m?

**Comment by salehsedghpour** [comment]
Currently, there is no `maxEjectionTime` (Check #30602).

Also by checking the envoy documentation we can see that:

> `maxEjectionTime` is defined as the maximum time that a host is ejected for and  If it is not specified, the default value (300000ms or 300s) or base_ejection_time value is applied, whatever is larger.

I hope this could help you

**Comment by ankitdiscovery** [comment]
right @salehsedghpour . i also found that currently there is no such configuration .
Just curious , how this problem is being currently solved ( to lower maxEjectionTime value less than 5 m).

**Comment by ramaraochavali** [comment]
if you want to change maxEjectionTime, you have to do using an Envoy filter
