### ISSUE TITLE
how to disable debug interface of pilot-agent

### ISSUE THREAD

**Issue by zgyn76** [istio/istio#41457]
### Bug Description

For istiod, i can set env var "ENABLE_DEBUG_ON_HTTP" to "true" to enable debug interface.
why isn't there a similar env var for pilot-agent?

### Version

```prose
istio control-plane 1.13.8
istio data-plane 1.13.8
```

**Comment by zirain** [comment]
should we provide option to disable debug interface on pilot-agent
@istio/wg-security-maintainers WDYT?

**Comment by howardjohn** [comment]
Why?

**Comment by zgyn76** [comment]
> Why?

For security concerns. 
I've noticed that it is recommended to set the parameter ENABLE_DEBUG_ON_HTTP to false for production. Maybe this is for security(?).
Some debug interfaces of pilot-agent are consistent with those of istiod, such as pprof. So, is it necessary to disable the debug interface of pilot-agent for production?
