### ISSUE TITLE
Restrict secrets to root and gateway namespace

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#41469]
**Describe the feature request**

As of istio 1.14, all serviceAccounts used by Istio get a ClusterRole that grants them access to ALL secrets on the cluster:

(definition on the ClusterRole `istiod-istio-system` and versionned equivalent: `istiod-clusterrole-1-14-istio-system`)
```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
```

I believe that the only access to secret that is required are the certificates/TLS secrets for IngressGateways (and some extra secrets on `istio-system`). 
In a lot of cases, the ingress certificates/TLS is scoped to a single namespace (for example we use a specific namespace for all our gateways and all associated secrets). 

I would suggest that we add an extra-parameter to the profile that would scope the secrets to a list of namespaces.If the list is empty, only istio-system permissions would be given.

If that parameter is not defined, the default would be to still grant secret read to the whole cluster.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
In some case istiod needs to fetch secret from all namespaces, like sidecar ingress tls

**Comment by hzxuzhonghu** [comment]
This is not possible, in sidecar ingress case, istiod need to fetch secrets referenced by sidecars, which can be distributed in any namespace
