### ISSUE TITLE
istio-performance-dashboard: 11829 grafana dashboard not visible under https://grafana.com/orgs/istio/dashboards

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#41471]
### Bug Description

Still mentioned with the others on https://github.com/istio/istio/blob/master/samples/addons/README.md#grafana

and https://github.com/istio/istio/blob/master/prow/release-commit.sh#L87

yet gone from grafana (the others are fine)

### Version

```prose
1.14.5 but n/a
```

### Additional Information

 https://grafana.com/grafana/dashboards/7645/revisions now redirects to https://grafana.com/grafana/dashboards/7645-istio-control-plane-dashboard/?tab=revisions and is fine but not 11829 ( https://grafana.com/grafana/dashboards/11829/revisions )

also missing from https://grafana.com/orgs/istio/dashboards

**Comment by ldemailly** [comment]
looks like a bug in the grafana UI / redirect logic and attribution because
```
curl -v --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://grafana.com/api/dashboards/11829/revisions/137/download
```

still works and gets 1.14.5 version

**Comment by zirain** [comment]
it seems ok now?

**Comment by ldemailly** [comment]
Yes, I think John fixed it, thanks!
