### ISSUE TITLE
couldn't install istio using helm

### ISSUE THREAD

**Issue by MerNat** [istio/istio#41479]
### Bug Description

I've simply followed the instruction on installing using helm.

The first command was successfully executed. but the second one `helm install istiod istio/istiod -n istio-system --wait
` won't execute with an error of unknown field.

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(EnvoyFilter.spec): unknown field "priority" in io.istio.networking.v1alpha3.EnvoyFilter.spec
```

### Version

```prose
Kubernetes version:
Client Version: v1.20.2
Server Version: v1.22.13

helm version:
v3.7.0+geeac838
```

**Comment by sforce100** [comment]
I've similar problem.....
`helm install istiod istio/base -n istio-system` success.
`helm install istiod istio/istiod -n istio-system` failure.
**error message**
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "istiod-clusterrole-istio-system" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istiod"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
```

**version**
Kubernetes install by rke, rke version 1.3.15

**Comment by dhawton** [comment]
> I've similar problem..... `helm install istiod istio/base -n istio-system` success. `helm install istiod istio/istiod -n istio-system` failure. **error message**
> 
> ```
> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "istiod-clusterrole-istio-system" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istiod"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
> ```
> 
> **version** Kubernetes install by rke, rke version 1.3.15
> 
> ### install by istioctl failure too
> **error message**
> 
> ```
> ✔ Istio core installed
>   Processing resources for Istiod. Waiting for Deployment/istio-system/istiod                                                                       
> ✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
>   Deployment/istio-system/istiod (container failed to start: CrashLoopBackOff: back-off 2m40s restarting failed container=discovery pod=istiod-6dd4f55ddb-hrktz_istio-system(a6775add-bdd3-45d5-94d1-03bdc1144308))
> ```

Yours is different. From the error, it looks like istio was previously installed without helm and you're trying to install over it using helm. istioctl install can you look at why istiod is failing to start and crashing?

**Comment by MerNat** [comment]
@dhawton for that issue, you can simply delete the existing clusterrole and clusterrolebinding objects of istio (i.e. on your case istiod-clusterrole-istio-system) before installing using helm.

**Comment by MerNat** [comment]
By the way, it's better to install istio using `istioctl` as it seems installing it using helm has some issue. it has worked perfectly once installed using istioctl.

**Comment by dhawton** [comment]
> @dhawton for that issue, you can simply delete the existing `clusterrole` and `clusterrolebinding` objects of istio (i.e. on your case `istiod-clusterrole-istio-system`) before installing using helm.

No. See https://istio.io/latest/docs/setup/install/helm/#migrating-from-non-helm-installations

**Comment by dhawton** [comment]
> By the way, it's better to install istio using `istioctl` as it seems installing it using helm has some issue. it has worked perfectly once installed using istioctl.

I wasn't able to replicate the issue you ran across following the Helm install docs and it looks like the docs test passed as well. Wonder if a `helm repo update` is needed?

**Comment by alicyn** [comment]
I am having the same problem. I already tried `helm repo update`. Did anyone solve this issue?

**Comment by MerNat** [comment]
> I am having the same problem. I already tried `helm repo update`. Did anyone solve this issue?

You can use `istioctl` to install istio.

**Comment by alicyn** [comment]
@MerNat I need to use helm to manage our Istio production deployments, so trying to install istioctl on AKS was a difficult option.

I just upgraded my helm client to version `3.10` and now it installs istiod perfectly without any errors. So I believe it was a version mismatch between Helm and the latest Istio charts. I hope this saves someone hours of searching for a solution.
