### ISSUE TITLE
AuthorizationPolicy  TCP Source control

### ISSUE THREAD

**Issue by Allengf** [istio/istio#41486]
**Describe the feature request**
I want to pass AuthorizationPolicy control  tcp flow source，Because the kitex framework is used, the proxyless mode used

**Describe alternatives you've considered**
The following example，source configuration will affect  ALLOW Strategy

**Additional context**

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tcp-policy
  namespace: proxyless
spec:
  selector:
    matchLabels:
      app: kitex-server
      version: v1
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/proxyless/sa/client-v1"]
    to:
    - operation:
        ports: ["8888"]

**Comment by hzxuzhonghu** [comment]
What do you want?

**Comment by Allengf** [comment]
@hzxuzhonghu I add  from.source.principals  to this AuthorizationPolicy，But did not take effect

**Comment by hzxuzhonghu** [comment]
What is kitex? Does it support this?

**Comment by Allengf** [comment]
@hzxuzhonghu  ByteDance open source framework，It is still in the early stage and is not supported. It is proxyless model
https://www.cloudwego.io/zh/docs/kitex/overview/

**Comment by Allengf** [comment]
I want to partially install sidecar， Management through istio tcp
NetworkPolicy
today，I found that my needs can also be realized through NetworkPolicy.

**Comment by mark8s** [comment]
If you need to use source.principals , maybe you need to set mtls. @Allengf

**Comment by howardjohn** [comment]
This has been answered and no followups for 6mo,closing
