### ISSUE TITLE
make push should always use linux

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4154]
GOOS=linux should be hardcoded for the docker push task until we properly support MacOS

**Comment by ldemailly** [comment]
yes there is really no point at all to build docker images that aren't using linux binaries

**Comment by ldemailly** [comment]
related pr #3080

**Comment by cmluciano** [comment]
The complication here is that the ca_cert will be compiled for linux, but will be executed on MacOS.

```
~/.gocode/bin/generate_cert --key-size=2048 --out-~/.gocode/out/darwin_amd64/release/docker_temp/istio_ca.crt \
                    --out-priv=~/.gocode/out/darwin_amd64/release/docker_temp/istio_ca.key --organization="k8s.cluster.local" \
                    --self-signed=true --ca=true
/bin/bash: ~/.gocode/bin/generate_cert: cannot execute binary file
```

**Comment by cmluciano** [comment]
@istio/reviewers-istio-security Can we use openssl as we do for the [webhook](https://github.com/istio/istio/blob/master/install/kubernetes/webhook-create-signed-cert.sh)

**Comment by ldemailly** [comment]
it's the more global issue; that we should never put linux binaries in mac PATH 

we just need to build everything that is ran locally (istioctl, tests etc...) without any hack to the env vars

and everything that ends up in a docker image with GOOS=linux

**Comment by ldemailly** [comment]
#2594

**Comment by mattdelco** [comment]
As for static, afaict go always build statically regardless of the request--I didn't test this on Windows [yet] but I know I tested on Linux and I think at one point I also tried on Mac and saw the same result.  E.g. on Linux:
<pre>
ldd $(make where-is-out)/istioctl
	not a dynamic executable
ldd $(make where-is-out)/istioctl-linux
	not a dynamic executable
</pre>

**Comment by ldemailly** [comment]
bin/gobuild.sh is sort of an abomination that should only be used for docker (if at all)

**Comment by mattdelco** [comment]
Well, you've probably seen my past efforts to get rid of bash scripts to consolidate into make, and I wouldn't mind getting rid of gobuild.sh but I do encounter resistance from people who are basically more comfortable with bash than they are with make.

**Comment by cmluciano** [comment]
Should this issue remain open if specifying the GOOS is similar to a protection mechanism?

**Comment by hklai** [comment]
@kimikowang isn't this something you had already done?

**Comment by tiswanso** [comment]
Any workaround to get through `make push` on OSX?

**Comment by hklai** [comment]
Have you tried "GOOS=linux make push" ?

**Comment by ldemailly** [comment]
we should really consider making the macos user experience first class citizen - including creating docker image with linux binaries - without needing any tweak or multiple make invocations with different variables set

**Comment by hklai** [comment]
How about the following?

make clean
GOOS=linux make docker
GOOS=linux make push

**Comment by mattdelco** [comment]
The version of the Makefile at head doesn't have any explicit dependencies set up for generate_cert and its make clean won't touch what's in go/bin so if you're in a directory like go/src/istio.io/istio then you'd have to "rm ../../../bin/generate_cert" and then the next invocation of make should build a OS-native version of the executable.

**Comment by tiswanso** [comment]
@mattdelco -- Thanks!  That was it.
Steps I did that worked:
```
rm $GOPATH/bin/generate_cert
GOOS=linux make docker
GOOS=linux make push
```
