### ISSUE TITLE
Need test mechanism to start multiple Pilot instances and have some evicted from cluster

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#4155]
Would help with dashboard testing, but also seems useful for testing failures in HA scenarios, etc.

**Comment by andraxylia** [comment]
This is a dup of #2506

**Comment by douglas-reid** [comment]
No. That is complimentary, but I need a way to evict Pilots during a test as well.

**Comment by andraxylia** [comment]
You can use k8s to increase/decrese the number of pods.
