### ISSUE TITLE
Helm install regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#41593]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-124_istio_postsubmit/1583551167684677632
https://prow.istio.io/view/gs/istio-prow/logs/integ-distroless_istio_postsubmit/1583536805376954368
https://prow.istio.io/view/gs/istio-prow/logs/integ-cni_istio_postsubmit/1583536823324381184

Not sure what happened here, but something broke recently

**Comment by zirain** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41611/integ-helm_istio/1584601142795440128

istio-discovery install timeout

**Comment by howardjohn** [comment]
I think we need to dump the logs of these components like we do for other tests. Presumably its not starting/getting ready for some reason?

**Comment by zirain** [comment]
dump the state of all releases in istio-system namespace?

**Comment by zirain** [comment]
another case: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/41651/integ-helm_istio/1585546320192475136

**Comment by howardjohn** [comment]
Weird one! https://prow.istio.io/view/gs/istio-prow/logs/release_istio_postsubmit/1588586579218141184

`2022-11-04T18:00:35.392138Z	info	Check failed: check HelmChartVersions failed: exit status 127`

Basically helm is just exiting with no stdout, etc for no reason...

**Comment by howardjohn** [comment]
We have been seeing (rarely) the same with `kind` for ~ever.

Example: https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-multicluster_istio_postsubmit/1583294207907336192#1:build-log.txt%3A2998-3001

```
+ kind export kubeconfig --name=primary
+ cleanup_kind_clusters
+ echo 'Test exited with exit code 127.'
Test exited with exit code 127.
```

**Comment by zirain** [comment]
seems this's fixed.
