### ISSUE TITLE
istio-sidecar.deb for arm64

### ISSUE THREAD

**Issue by h0tbird** [istio/istio#41595]
**Describe the feature request**
Not much to say here other than I would like the `arm64` build for the `istio-sidecar.deb` package.
I don't see any artefact published that works for this architecture:
<img width="339" alt="Screenshot 2022-10-22 at 18 15 41" src="https://user-images.githubusercontent.com/417440/197349878-c2808395-8357-453d-9379-e71d0e62efe8.png">

**Describe alternatives you've considered**
Build it myself.

**Affected product area (please put an X in all that apply)**

[x] Installation
[x] User Experience

**Affected features (please put an X in all that apply)**

[x] Virtual Machine

**Additional context**
```
ubuntu@virt-01:~$ curl -LO https://storage.googleapis.com/istio-release/releases/1.15.2/deb/istio-sidecar.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.8M  100 38.8M    0     0  3587k      0  0:00:11  0:00:11 --:--:-- 3435k
ubuntu@virt-01:~$ sudo dpkg -i istio-sidecar.deb
dpkg: error processing archive istio-sidecar.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 istio-sidecar.deb
```

**Comment by zirain** [comment]
https://github.com/istio/release-builder/pull/1155 miss deb/rpm? cc @howardjohn

**Comment by h0tbird** [comment]
Wow thank you, that was fast! 🚀

I guess release `1.15.3` will be the first one to produce the artefacts below?
- `istio-sidecar-arm64.deb`
- `istio-sidecar-arm64.rpm`

**Comment by zirain** [comment]
won't make 1.15.3 (already built) but it'll be there for 1.15.4
