### ISSUE TITLE
Is it possible to disable control plane mertics?

### ISSUE THREAD

**Issue by LiamLea** [istio/istio#41604]
**Describe the feature request**
There are many [control plance metrics](https://istio.io/latest/docs/concepts/observability/#control-plane-metrics) which are useless for me, so i want to find a way to disable them. Disabling telemetry does not work for this. 
The reason i want to disable them is that there too many pods in my cluster so that prometheus consumes many memory.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
IMO, it's not a good practice to disable metrics without memory issue.
you should drop them during scraping

**Comment by LiamLea** [comment]
> IMO, it's not a good practice to disable metrics without memory issue. you should drop them during scraping

Thanks! I think i can drop metrics using metric_relabel_configs in prometheus.
