### ISSUE TITLE
Optimize the performance of model.HashCode

### ISSUE THREAD

**Issue by wulianglongrd** [istio/istio#41603]
**Describe the feature request**
Optimize the performance of model.HashCode

**Describe alternatives you've considered**
[xxhash.Sum](https://github.com/cespare/xxhash) is faster than md5.Sum. The model.HashCode function currently uses md5.Sum. Is there any hidden danger in replacing it with xxhash.Sum?

Below is a benchmark comparison：
```code
$ go test -bench="HashCode$" -test.benchmem
goos: darwin
goarch: amd64
pkg: istio.io/istio/pilot/pkg/model
cpu: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
BenchmarkHashCode/small_string-4             3947338           346.5 ns/op        16 B/op          1 allocs/op
BenchmarkHashCode/middle_string-4            2696684           491.7 ns/op        16 B/op          1 allocs/op
BenchmarkHashCode/long_string-4              1415818           721.0 ns/op       160 B/op          3 allocs/op

BenchmarkXxHashCode/small_string-4          10877007           105.9 ns/op        16 B/op          1 allocs/op
BenchmarkXxHashCode/middle_string-4          5099265           251.1 ns/op       128 B/op          2 allocs/op
BenchmarkXxHashCode/long_string-4            3158840           454.4 ns/op       288 B/op          2 allocs/op
PASS
ok      istio.io/istio/pilot/pkg/model  16.045s
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
seems reasonable on the surface

**Comment by wulianglongrd** [comment]
hello @howardjohn @hzxuzhonghu 

Why don't we just use string as the key for `sc.configDependencies` map ? This also saves two hash calculations (one for the key used to construct the `sc.configDependencies` map, and another for the map's key when `DependsOnConfig` compares). 

I wrote a benchmark comparing the performance when using md5.Sum/xxhash.Sum/string as the `sc.configDependencies` 
 map key. The conclusion is that using string is more performant. 

I would like to ask, is there any special purpose to use uint64 as the key of `sc.configDependencies` map? If not, I will submit a PR.

thanks.

below is the performance comparison of current istio's md5.Sum and using string as key([benchmark link](https://github.com/wulianglongrd/samples)):
```code
$ benchstat md5.txt str.txt
name      old time/op    new time/op    delta
100-4        387µs ±24%     116µs ±15%  -69.98%  (p=0.008 n=5+5)
1000-4      4.22ms ±18%    0.92ms ±54%  -78.21%  (p=0.008 n=5+5)
10000-4     32.5ms ±23%     6.1ms ±45%  -81.16%  (p=0.008 n=5+5)
100000-4     289ms ±17%      83ms ±67%  -71.21%  (p=0.008 n=5+5)
200000-4    773ms ±109%     169ms ±46%  -78.20%  (p=0.008 n=5+5)

name      old alloc/op   new alloc/op   delta
100-4       51.1kB ± 0%    47.2kB ± 0%   -7.63%  (p=0.008 n=5+5)
1000-4       529kB ± 0%     500kB ± 0%   -5.52%  (p=0.008 n=5+5)
10000-4     5.15MB ± 0%    4.81MB ± 0%   -6.63%  (p=0.008 n=5+5)
100000-4    50.8MB ± 0%    46.8MB ± 0%   -7.83%  (p=0.008 n=5+5)
200000-4     102MB ± 0%      94MB ± 0%   -7.83%  (p=0.008 n=5+5)

name      old allocs/op  new allocs/op  delta
100-4          802 ± 0%       402 ± 0%  -49.88%  (p=0.008 n=5+5)
1000-4       8.00k ± 0%     4.00k ± 0%  -49.99%  (p=0.008 n=5+5)
10000-4      80.0k ± 0%     40.0k ± 0%  -50.00%  (p=0.008 n=5+5)
100000-4      800k ± 0%      400k ± 0%  -50.00%  (p=0.008 n=5+5)
200000-4     1.60M ± 0%     0.80M ± 0%  -50.00%  (p=0.008 n=5+5)
```

**Comment by hzxuzhonghu** [comment]
Great work, I can see both use uint64, so the collision possibility is same?

**Comment by wulianglongrd** [comment]
> Great work, I can see both use uint64, so the collision possibility is same?

The idea I started with was to replace istio's current md5.Sum with xxhash.Sum64, which are both uint64 and the collision probability seems to be the same.

Later tests found that it is faster to [use `string` directly as the key ](https://github.com/wulianglongrd/samples/blob/main/mapKeyCompare.go#L50)of the `sc.configDependencies` (the full spelling of `sc` is SidecarScope) map. so, I would like to confirm whether there are any known problems using this method. If not, I will submit a PR.

**Comment by ramaraochavali** [comment]
> Why don't we just use string as the key for sc.configDependencies map 

Which string do you want to have? If it is configKey it used to take lot of memory. That is why we switched to hashing.

For history,
https://github.com/istio/istio/pull/22667 is the original PR that added config dependencies (note ConfigKey is the key there)
https://github.com/istio/istio/pull/25532 fixed the memory issue caused by config keys.

So I think we can not go back to string unless you have a better idea here.

**Comment by wulianglongrd** [comment]
> > Why don't we just use string as the key for sc.configDependencies map
> 
> Which string do you want to have? If it is configKey it used to take lot of memory. That is why we switched to hashing.
> 
> For history, #22667 is the original PR that added config dependencies (note ConfigKey is the key there) #25532 fixed the memory issue caused by config keys.
> 
> So I think we can not go back to string unless you have a better idea here.

thanks @ramaraochavali , i get it.
