### ISSUE TITLE
istioctl uninstall --purge  failed

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#41607]
### Bug Description

istio 1.13.3
![image](https://user-images.githubusercontent.com/48784730/197519978-c35d72b3-d9d6-4d80-9904-db907fceae5f.png)

### Version

```prose
root@ubuntu:/home/lq/work/istio# istioctl version
no running Istio pods in "istio-system"
1.13.3

root@ubuntu:/home/lq/work/istio# kubectl version --short
Client Version: v1.23.6
Server Version: v1.23.3
```

**Comment by zirain** [comment]
`istioctl x uninstall --purge`

**Comment by liuqi-sun** [comment]
> 
Thank you, but some cm and ca are not deleted.
![image](https://user-images.githubusercontent.com/48784730/197663832-fb32e48a-dc04-42b4-80e4-ab262fdbdec5.png)

**Comment by zirain** [comment]
I think this's expected 

keep `istio-ca-root-cert` will be useful if you have injected pods and reinstall istio
`*-leader` are used for leader election
