### ISSUE TITLE
Publish helm chart for ztunnel

### ISSUE THREAD

**Issue by ChrisJBurns** [istio/istio#41615]
### Bug Description

I install Istio via Helm. I cannot seem to install Ambient Mesh with Helm? Is it a different setup or is it just an increment in a specific version?

### Version

```prose
Kubernetes: v1.23.12
```

**Comment by linsun** [comment]
Did you get it working?  Would love for folks to post instructions!

**Comment by ChrisJBurns** [comment]
@linsun  I eventually asked on [Slack](https://istio.slack.com/archives/C041EQL1XMY/p1667228907885479) and got some responses. The TL;DR is basically that it's on an ambient branch but I don't think it's available publicly yet through the Chart repository. I could be wrong though (I hope I am :) )

**Comment by linsun** [comment]
Yeah, i don't expect us to publish chart for the branch. You could still install it using Helm working with your local checked out dir, no?  That is what i meant.

**Comment by ChrisJBurns** [comment]
@linsun  Ahh I see. I haven't tried that yet, I use Flux for my cluster deployments, so I'll have to clone down the Chart and give it a try

**Comment by amolvgaikwad** [comment]
is ambient mesh available with helm chart ?

**Comment by pisces-period** [comment]
It seems that Istio now has an [official Chart for ztunnel deployment](https://artifacthub.io/packages/helm/istio-official/ztunnel).

Also, since v1.18.0, the CNI chart [now allows you to enable Ambient](https://artifacthub.io/packages/helm/istio-official/cni/1.18.0).

**Comment by howardjohn** [comment]
The published charts are for the beta+ stability charts, so until ztunnel
reaches that state it will likely not be published.
