### ISSUE TITLE
why did istio remove header prefix with x-？

### ISSUE THREAD

**Issue by ggjjlldd** [istio/istio#41639]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
why did istio remove header prefix with x-？
I add header x-qltest in ingress filter, when response come, it is not found.
**Describe alternatives you've considered**
I add header x-qltest in ingress filter, when response come, it is not found. But i need this header.
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x ] Networking
[ x] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[x ] Virtual Machine
[ x] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This needs more detail. Istio doesn't arbitrarily remove headers so you much have some broken configuration or are triggering some weird edge case.
