### ISSUE TITLE
how can I write ext-authz envoyfilter, that request with /header url to send auth server, other url not send?

### ISSUE THREAD

**Issue by ggjjlldd** [istio/istio#41640]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
how can I write ext-authz envoyfilter, that request with /header url to send auth server, other url not send?
I write ext-authz envoyfilter, But request path is header should be send to auth server, other not, how can i write?
**Describe alternatives you've considered**
how can I write ext-authz envoyfilter, that request with /header url to send auth server, other url not send?
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[x ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by escoffier** [comment]
refer to this: [Envoy Per-Route Configuration](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#per-route-configuration)
