### ISSUE TITLE
Upgrade the gzip version to V1.12 in All Istio docker images.

### ISSUE THREAD

**Issue by kenny-tan** [istio/istio#41641]
**Hi Community,**
To mitigate the existing High security Risk, Would you please help to upgrade the gzip version to V1.12 in All Istio docker images?

**Background:**
As our standard, We had Aqua scanning on istio:1.15.1, from which one high vulnerability was raised as screenshot below, and version is 1.12.(currently version is 1.10) was recommended by Aqua.  
 
![image](https://user-images.githubusercontent.com/84892451/197923168-de3a4daa-bf49-40de-80c9-fb7508b436c7.png)

**Hands-on fix Steps:**
Per our hands-on practice, it is definitely able to be fixed as below.
1.	Apt-get install method is failed, because can't found the gzip 1.12 version in source repo.
2.	Find the gzip_1.12_ubuntu1_64.deb from https://launchpad.net/ubuntu/+source/gzip/1.12-1ubuntu1/+build/24287309/+files/gzip_1.12-1ubuntu1_amd64.deb
3.	Download the deb file and upload to a Ali Cloud OSS Bucket that can be curl or wget in Dockerfile when docker build
4.	Edit the Dockerfile for ISTIO-BASE as below, then rebuild the ISTIO-BASE image. Here customize the Image name xxxxxxx/istio-base:0.0.2. 
 
![image](https://user-images.githubusercontent.com/84892451/197923231-c0f7e3fc-f4a0-42c4-8ba5-4c350ae9ed62.png)

5.	Edit the Dockerfile for istio-pilot and istio-proxyv2 images on base of upper customized istio-base images (xxxxxxx/istio-base:0.0.2.). Then rebuild the relative images. 

```
# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=debug

# Version is the base image version from the TLD Makefile
# ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=debug
FROM xxxxxxx/istio-base:0.0.2 as debug

# The following section is used as base image if BASE_DISTRIBUTION=distroless
# This image is a custom built debian11 distroless image with multiarchitecture support.
# It is built on the base distroless image, with iptables binary and libraries added
# The source can be found at https://github.com/istio/distroless/tree/iptables
# This version is from commit a8b3fb577adb785211ce704fdf892983fc268b11.
FROM gcr.io/istio-release/iptables@sha256:4be99c4dbc0a158fc4404d66198bf18f321292ffeff55201e9c8fa518a54b81e as distroless

# This will build the final image based on either debug or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION:-debug}

WORKDIR /

ARG proxy_version
ARG istio_version
ARG SIDECAR=envoy

# Copy Envoy bootstrap templates used by pilot-agent
COPY envoy_bootstrap.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json
COPY gcp_envoy_bootstrap.json /var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json

# Install Envoy.
ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/${SIDECAR} /usr/local/bin/${SIDECAR}

# Environment variable indicating the exact proxy sha - for debugging or version-specific configs
ENV ISTIO_META_ISTIO_PROXY_SHA $proxy_version
# Environment variable indicating the exact build, for debugging
ENV ISTIO_META_ISTIO_VERSION $istio_version

ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/pilot-agent /usr/local/bin/pilot-agent

COPY stats-filter.wasm /etc/istio/extensions/stats-filter.wasm
COPY stats-filter.compiled.wasm /etc/istio/extensions/stats-filter.compiled.wasm
COPY metadata-exchange-filter.wasm /etc/istio/extensions/metadata-exchange-filter.wasm
COPY metadata-exchange-filter.compiled.wasm /etc/istio/extensions/metadata-exchange-filter.compiled.wasm

# The pilot-agent will bootstrap Envoy.
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
```

**Result:**
After recompile the istio-pilot and istio-proxyv2 image, The high security Risk was mitigated finally.
 
![image](https://user-images.githubusercontent.com/84892451/197923694-9b386d78-0612-4844-a507-6fcf4a0f1e0a.png)

**Comment by ymesika** [comment]
Or simply change the base image of the istio-base to `ubuntu:kinetic` (now stable release) which already includes the gzip 1.12.
