### ISSUE TITLE
Problem about ledger put and delete

### ISSUE THREAD

**Issue by shirleyyLi** [istio/istio#41655]
### Bug Description

https://github.com/istio/istio/blob/master/pilot/pkg/status/distribution/ledger.go
I am testing this two function tryLedgerPut and tryLedgerDelete. And here is my UT.
```
func TestTryLedgerPutAndDelete(t *testing.T) {
	RegisterTestingT(t)
	ledger := ledger.Make(time.Minute)
	resources := []config.Config{
		{
			Meta: config.Meta{
				Namespace:  "default",
				Name:       "foo",
				Generation: 1,
			},
		},
		{
			Meta: config.Meta{
				Namespace:  "default",
				Name:       "bar",
				Generation: 2,
			},
		},
		{
			Meta: config.Meta{
				Namespace:  "alternate",
				Name:       "boo",
				Generation: 3,
			},
		},
	}
	var result []string
	for _, res := range resources {
		tryLedgerPut(ledger, res)

		r, err := ledger.Get(res.Key())
		if err != nil {
			t.Errorf("ledger get %s error %v", res.Key(), err)
		}
		result = append(result, r)
	}

	Expect(result[0]).To(Equal("1"))
	Expect(result[1]).To(Equal("2"))
	Expect(result[2]).To(Equal("3"))

	tryLedgerDelete(ledger, resources[0])
        time.Sleep(2 * time.Minute)
	result1, err := ledger.Get(resources[0].Key())
	if err != nil {
		t.Errorf("ledger get %s error %v", resources[0].Key(), err)
	}
	Expect(result1).To(Equal(""))
}
```
Test Results
```
=== RUN   TestTryLedgerPutAndDelete
    ledger_test.go:57: 
        Expected
            <string>: 1
        to equal
            <string>: 
--- FAIL: TestTryLedgerPutAndDelete (0.00s)
```
It shows that the last line `Expect(result1).To(Equal(""))` is failed.
I noticed that there is the retention time when making a new ledger. In this UT I set it to 1m. So I wait for 2m after deleting the resource.  But it is still remain after 2m. I think this is a bug.   

 After digging into the code，I think the problem is in https://github.com/istio/pkg/blob/61b8dab4d52953dff14cd50ffab46fbf66c4ff2f/ledger/ledger.go#L64.
We should use `[][]byte{coerceKeyToHashLen(key)}` instead of `[][]byte{[]byte(key)}`, which means that function Put and Delete has the same key.

Did I miss something？ What was the original implementation for?

### Version

```prose
control plane version: 1.15
```

**Comment by hzxuzhonghu** [comment]
@therealmitchconnors

**Comment by therealmitchconnors** [comment]
Sorry for the long delay.  You are correct that this is a bug.  I have been working to refactor this code to solve this and many other issues, but have been unsuccessful so far.  A pull request as you outlined would be welcome.

**Comment by shirleyyLi** [comment]
@therealmitchconnors Thanks for your response. I've created a pull request to fix this.

**Comment by howardjohn** [comment]
This code has been removed
