### ISSUE TITLE
pod dont enable sidecar

### ISSUE THREAD

**Issue by liyin37** [istio/istio#41653]
### Bug Description

when I install istio in new version，install command：
istioctl install --set profile=demo -y
![image](https://user-images.githubusercontent.com/42507175/198203573-53bf0cd8-2697-459d-be8c-d7405643b66b.png)

then  I  install a deployment，the POD dont up，error  is:
Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": context deadline exceeded
![image](https://user-images.githubusercontent.com/42507175/198203773-2812ed26-61c6-4210-b404-d62204612e2d.png)

### Version

```prose
$ istioctl version
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (2 proxies)

$ kubectl version --short
Client Version: v1.22.14
Server Version: v1.22.14
```

**Comment by zirain** [comment]
any logs from istiod pod?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecar-injection
