### ISSUE TITLE
Forced to recreate istio gateways migrating to the istio helm chart 

### ISSUE THREAD

**Issue by jdamata** [istio/istio#41675]
My current installation of istio was done via the istio operator. I am working on migrating this to the istio helm charts being built in this repo.

In the gateway chart, we strip out any labels that are not app or istio: https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/_helpers.tpl#L31

This is problematic for me since there are other selector labels on the existing deployed gateways. Is it possible to work around this without deleting the deployments? Would we be ok with adding another helm chart variable for extra selector labels and iterating over it here: https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/_helpers.tpl#L31 ? I'm willing to open a PR for this or any other suggestion.

**Comment by jdamata** [comment]
I was able to get around this via helmfile/strategicMergePatches (kustomize) but i am still very much interested in supporting this somehow in the gateway helm chart

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/39180#issuecomment-1142441351

https://github.com/istio/istio/issues/39079#issuecomment-1135133605
