### ISSUE TITLE
When is the version with http3 support expected to be released?

### ISSUE THREAD

**Issue by LinXiaoJian** [istio/istio#41676]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Experimental-QUIC-and-HTTP-3-support-in-Istio-gateways

Already supported experimentally. For production ready, likely a long time.

**Comment by ldemailly** [comment]
Any updates on this? full support for 1.17 would be great?

**Comment by kyessenov** [comment]
@ldemailly h3 in Envoy doesn't implement mTLS properly. See https://github.com/envoyproxy/envoy/issues/23809.
I'd consider that as a blocker for in-mesh transport.

**Comment by ldemailly** [comment]
Thanks - So you mean it'd work today for the ingress as long as the service itself isn't side car injected? (ie no mtls ingress to service) - Would that be all the way h3 or h3 ends at ingress and then h2 to svc?

**Comment by kyessenov** [comment]
Yeah, h3 within the mesh is not mutually authenticated (despite saying so in the config).  Regular TLS on ingress is production ready in Envoy, but not easily exposed in Istio APIs.

**Comment by howardjohn** [comment]
h3 to ingress only, h2 internally. That is the only thing implemented in Istio today

**Comment by ldemailly** [comment]
it'd be nice to make the ingress support 'official' rather than just experimental though?
