### ISSUE TITLE
VirtualService have the validationMessages

### ISSUE THREAD

**Issue by loxiaopohaiol** [istio/istio#41693]
### Bug Description

My kuberntes version is v1.22.15, and istio version is 1.15.1.  I create a DestinationRule for test:
![image](https://user-images.githubusercontent.com/48348273/198941065-431c7941-5bf6-4792-a86c-d56f510cc6d4.png)
which have the subsets v1 and v2, then I create a VirtualService:
![image](https://user-images.githubusercontent.com/48348273/198941290-9c2defc1-25ec-4a8d-86f0-aa4eb47eeea9.png)
but the VirtualService has the error message:
![image](https://user-images.githubusercontent.com/48348273/198941445-f14562a1-0c95-4254-b59a-f287d6ed694b.png)
but when I access my pod throught the virtualservice ,it's normal.
And when I delete the "subset:v1" in the virtualservice, the validationMessages is disappeared, when I add the "subset:v1" the validationMessages is appeared, Why does this happen？
my istio proxy-config cluster have the version info：
![image](https://user-images.githubusercontent.com/48348273/198942309-9035ca77-975e-494a-8b81-764cd382e4ee.png)

### Version

```prose
istio version is 1.15.1
```

**Comment by escoffier** [comment]
Run command: istioctl analyze.  The output has the detail of configuration errors.

**Comment by loxiaopohaiol** [comment]
> istioctl analyze

I run this command in the appeared the error virtualservice's namespace, but no error:
![image](https://user-images.githubusercontent.com/48348273/199153749-1f945187-edb6-4ae8-b060-2615923b8ccd.png)
