### ISSUE TITLE
operator: disable URLFetcher

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#41704]
The Operator currently has a way to fetch charts from arbitrary URLs. This has minimal use now that `istioctl upgrade` is removed. Instead, we should deprecate this as it adds complexity and is not particularly secure.

This is simple to do, but we will need a 1 release deprecation period probably

cc @zirain @ramaraochavali and others to make sure no one is actually using this?

**Comment by zirain** [comment]
I never realized that existed

**Comment by ramaraochavali** [comment]
We are not using that either
