### ISSUE TITLE
Please provide values for helm installations of addons. 

### ISSUE THREAD

**Issue by st33v** [istio/istio#41703]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

I'd love it if the add ons [here](https://github.com/istio/istio/tree/master/samples/addons) included the values.yaml for each add-on so that I could use helm to deploy these instead of configs that were dumped out of helm and applied directly. Clearly, these add-ons were produced by helm, so what values were passed TO helm to generate these in the first place? How were these samples created?

**Describe alternatives you've considered**

I don't see an alternative to having the 'real' original values.yaml for grafana, kiali, prometheus, etc. The documentation does not fully cover the installation of the add-on's using helm... only the sample yamls that helm created and stored in the istio project. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
You can see in `manifests/addons`.

Note these are _samples_. If you are looking for a production ready install, these aren't it - see the projects install docs which all have prod ready documentation.

For example, none have persistent storage.

**Comment by st33v** [comment]
thanks @howardjohn that's exactly what I was looking for.
