### ISSUE TITLE
[Question]: Why istio tags are not prefixed with a `v`

### ISSUE THREAD

**Issue by FrimIdan** [istio/istio#41702]
### Bug Description

Is there a reason why istio tags are not prefixed with a `v`?

The reason why I'm asking is that when a go program imports istio repo go.mod will show pseudo-version that starts with v0.0.0
```
istio.io/istio v0.0.0-20220308185742-91533d04e894
```

That result with a false positive finding when using [grype](https://github.com/anchore/grype) for example.
More info can be found [here](https://github.com/anchore/grype/issues/972)

### Version

```prose
N/A
```

**Comment by kzantow** [comment]
Adding a little more context here from the aforementioned Grype issue:

From what I can tell, it looks like Istio versions are used for 2 purposes:
* Istio releases
* Using Istio as a go module

From the perspective of the first purpose of Istio releases, the choice of version is obviously up to the project and of course just fine as things stand today.

However, from the perspective of a using Istio as a _go module_, the tags do not conform to the format `go mod` is expecting, resulting in the aforementioned pseudo-versions being included, which seems incorrect in this context.

I wonder if a possible solution is to generate _two_ tags for each release, one of which is prefixed with `v` so using Istio as a go module works properly for that set of users.

**Comment by howardjohn** [comment]
Legacy :-)

istio/istio is not produced as a library that is expected to be imported fwiw, much like kubernetes/kubernetes. So publishing a semver would be misleading; we have zero compatibility guarantees.

**Comment by FrimIdan** [comment]
And still, kubernetes/kubernetes is using semver :) 
https://github.com/kubernetes/kubernetes/tree/v1.25.3

FYI, there are some utils pkg in istio that we found useful - It will be nice to add a `v` tag with a disclaimer that istio/istio have zero compatibility guarantees.

**Comment by howardjohn** [comment]
Kubernetes did it before go modules were a thing.

The only real Istio go module is https://github.com/istio/client-go/ which does have a `v` tag
