### ISSUE TITLE
Incorrect version of dependent package prometheus

### ISSUE THREAD

**Issue by lockdown56** [istio/istio#41713]
### Bug Description

reports an error: 
go: github.com/ionos-cloud/sdk-go/v6@v6.0.5851: invalid version: unknown revision v6.0.5851  

this package dependent on prometheus, but the sdk-go/v6@v6.0.5851 no longer exists

### Version

```prose
seems like all versions
```

**Comment by howardjohn** [comment]
Reports that when you do what...?

**Comment by howardjohn** [comment]
Anyhow, we cannot actually upgrade prometheus unless the github.com/envoyproxy/go-control-plane releases a new version since it forces us to downgrade.
