### ISSUE TITLE
JWKS key parse issue

### ISSUE THREAD

**Issue by Gourav2912** [istio/istio#41729]
### Bug Description

RequestAuthentication policy is unable to parse the KEY coming from below urls

https://cxone.staging.niceincontact.com/auth/jwks
https://cxone.niceincontact.com/auth/jwks

Error received is 
**envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Provider 'origins-0' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error**

istio version :- 1.14.1
We have checked issue is same in latest version as well.

### Version

```prose
istio : 1.14.1
```

**Comment by dhawton** [comment]
The message mentions `local jwks` instead of remote. Can you share the config?

**Comment by ramaraochavali** [comment]
@dhawton from request authentication, we get the public key (in Istiod) and convert it to local jwks. So we always configure envoy to use local jwks
@yangminzhu  might know more about the parse error issue

**Comment by Gourav2912** [comment]
Just to add a note istio works well with key coming from https://cxone.test.niceincontact.com/auth/jwks

**Comment by Gourav2912** [comment]
@yangminzhu By any chance did u get root cause?

**Comment by xiangZgnaix** [comment]
I've also encountered this issue, and got this fellow errors:

`gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Provider 'origins-0' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error`

How can I config the local jwks?  @ramaraochavali

**Comment by xiangZgnaix** [comment]
> @yangminzhu By any chance did u get root cause?

Hello, have you figured it out. Same issue, need some help~

**Comment by ramaraochavali** [comment]
> How can I config the local jwks?

Use this
https://github.com/istio/api/blob/master/security/v1beta1/jwt.proto#L102
