### ISSUE TITLE
Align metrics to follow Prometheus best practices

### ISSUE THREAD

**Issue by kdarw** [istio/istio#41735]
**Describe the feature request**
Istio metrics names shall be aligned to Prometheus Best Practices, like getting zero errors from promtool for the exposed metrics
see Prometheus documentation: https://prometheus.io/docs/practices/naming/#metric-and-label-naming

for example, see below issues reported from promtool check for istiod and ingressGateway
[istio_metrics_promtool_check.txt](https://github.com/istio/istio/files/9978875/istio_metrics_promtool_check.txt)
[istioGateways_metrics_promtool_check.txt](https://github.com/istio/istio/files/9921577/istioGateways_metrics_promtool_check.txt)

Main promtool findings:
- counter metrics should have "_total" suffix
- metric names should not contain abbreviated units
- no help text
- non-counter metrics should not have "_total" suffix
- non-histogram and non-summary metrics should not have "_count" suffix
- use base unit "seconds" instead of "days"
- use base unit "seconds" instead of "milliseconds"

Request for further improvements on Istio metrics:
- Lengthy metrics names SHOULD be avoided. Maximum 40-50 characters.
   Lengthy names are more difficult to memorize, recognize and to present to users in dashboards
   example: metrics with more than 50 characters:
   - pilot_conflict_outbound_listener_http_over_current_tcp
   - pilot_conflict_outbound_listener_tcp_over_current_http 
   - pilot_conflict_outbound_listener_tcp_over_current_tcp
   - istio_agent_pilot_conflict_outbound_listener_http_over_current_tcp 
   - istio_agent_pilot_conflict_outbound_listener_tcp_over_current_http 
   - istio_agent_pilot_conflict_outbound_listener_tcp_over_current_tcp

- A metric SHALL have less than 10 labels
   In scenarios with lots of metrics and labels, the compute resource impact becomes significant. 
   It is therefore important to not overuse labels (see also [https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels).](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels)
   example: istio_requests_total with more than 30 labels

- Metrics that are reported related to istio overload situations SHALL include label 'cause=congestion'

**Describe alternatives you've considered**
No alternatives 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kfaseela** [comment]
A similar request in envoy has been discussed and I see some possible approaches suggested there. Wanted to know if something similar is possible on istio side as well .  https://github.com/envoyproxy/envoy/issues/22130#issuecomment-1194436091 

The comment says "Could we put that translation mechanism into the Prometheus sink code, as an off-by-default option? Why would a third process be needed? Of course we might not be able to augment the system with help-text for every stat. But changing some units (and their corresponding values) seems feasible (though potentially adding significant CPU cost to an already-costly sink)."

@zirain @lei-tang any suggestions?

**Comment by zirain** [comment]
users can drop/relabel when prometheus scraping

**Comment by howardjohn** [comment]
IMO offering even the ability to change the schema is harmful; we lose the
fact that istio_requests_total (and similar) mean the same thing for every
Istio user. This breaks integrations, docs, shared knowledge, etc

**Comment by lei-tang** [comment]
I concur that these are APIs. If they need to be changed, the procedure of deprecating APIs should be followed.

**Comment by howardjohn** [comment]
I agree we should do this moving forward (for new metrics) but since this is a breaking API change we will not proceed

**Comment by keithmattix** [comment]
+1 IF a breaking change to metrics has to happen, it should start and end with OTEL convention compliance IMO
