### ISSUE TITLE
Warn on `istioctl install` when the version is EOL

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#41747]
Strawman implementation:

* Before we ship a release, guess when we will EOL it (this is generally known, but in theory we can change the EOL so its not perfect)
* In istioctl. add `if today > EOL date { warn }`
* In helm, NOTES.txt can do the same thing

The reason we guess the EOL is because we don't want to do a dynamic internet lookup. Because we might be wrong, we may want to say something like "Warning: may be installing an EOL version: see istio.io/support for supported releases" or something, rather than "You **are** installing a EOL version"

cc @therealmitchconnors

**Comment by zufardhiyaulhaq** [comment]
Hi @howardjohn can you assign this to me?
