### ISSUE TITLE
Circleci fails due to RBAC error namespace empty

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#4175]
https://circleci.com/gh/istio/istio/46044

Generated yaml file is broken, istio-pilot-admin-role-binding- shoud contain the namespace

Erom server for: "/tmp/istio.e2e.780711191/yaml/istio.yaml": resource name may not be empty
Error from server (Invalid): error when creating "/tmp/istio.e2e.780711191/yaml/istio.yaml": ClusterRoleBinding.rbac.authorization.k8s.io "istio-pilot-admin-role-binding-" is invalid: subjects[0].namespace: Required value

**Comment by rkpagadala** [comment]
fixed by https://github.com/istio/istio/pull/4173
