### ISSUE TITLE
Can I configure notPrincipals on istio-ingressgateway?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#41754]
Hi everyone, I have a small question. I want to know if I can configure AuthorizationPolicy to restrict a certain port of istio-ingressgateway to only be accessed by a certain service. Like the following:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: istio-ingressgateway-ap
 namespace: istio-system
spec:
 selector:
   matchLabels:
     app: istio-ingressgateway
 action: DENY
 rules:
 - from:
   - source:
       notPrincipals: ["cluster.local/ns/default/sa/a-sa"]
   to:
   - operation:
       ports: ["7575"]
```

My expectation is that only a service under the default namespace can access port 7575 of istio-ingressgateway. But when I apply this configuration, I still get a permission error:

```
E1102 12:15:45.007566       ] rpc error: code = PermissionDenied desc = RBAC: access denied
E1102 12:15:55.019612       ] rpc error: code = PermissionDenied desc = RBAC: access denied
E1102 12:15:55.020170       ] rpc error: code = PermissionDenied desc = RBAC: access denied
E1102 12:16:05.011519       ] rpc error: code = PermissionDenied desc = RBAC: access denied
E1102 12:16:15.006897       ] rpc error: code = PermissionDenied desc = RBAC: access denied
```

My feeling is that istio-ingressgateway can't recognize notPrincipals , so it should not be able to access port 7575 at this time.

Is there anyone who knows about this? Hope to get your help.

**Comment by hzxuzhonghu** [comment]
How does your service access ingressgateway, could not be via istio mtls. So I guess this is because gateway can not get the principal of client

**Comment by mark8s** [comment]
@hzxuzhonghu Thank you for your reply. I use the gateway accessed by ingressgateway IP:7575 because I have opened port 7575 on istio-ingressgateway. I also thought that ingressgateway could not recognize the principal of client.
