### ISSUE TITLE
Restrict permissions to istio-token in istio-proxy

### ISSUE THREAD

**Issue by fusidic** [istio/istio#41768]
**Describe the feature request**
As of istio 1.14, we run istio-proxy as `istio-proxy:istio-proxy`. And `istio-token` is mounted with permission `644`, which risks being acquired by `other` users.
```bash
[istio-proxy@test-6b67c54678-l49j8 /]$ ll /run/secrets/tokens/..data/
total 4
-rw-r--r-- 1 root root 934 Nov  3 08:48 istio-token
```
Is there anyway to restrict the permission of `istio-token` without setting fsgroup? Fsgroup may breaks Pod's securityContext sometimes.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I believe K8s doesn't really allow this, let me know if there is a way.

Either way - does it really matter? Its a container, there isn't going to be any users other than istio-proxy which needs to read it.
