### ISSUE TITLE
Cannot shorten metric interval

### ISSUE THREAD

**Issue by ryota2425** [istio/istio#41763]
### Bug Description

I would like to visualize in detail the amount of TCP traffic. I would like to see the change at least every second, but I cannot visualize it, it shows every 15 seconds.

Although the scraping interval for prometheus is changed to 1s, the metrics change only every 15s.
Any solutions?

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/29476187/199677575-1aef4033-3096-45f7-860b-57c0e98c1cb0.png">

### Version

```prose
$ istioctl version
client version: 1.16-alpha.a19b2ac8af3ad937640f6e29eed74472034de2f5
control plane version: 1.15.2
data plane version: 1.15.2 (10 proxies)

$ kubectl version --short
Client Version: v1.23.13
Server Version: v1.23.13
```

**Comment by kyessenov** [comment]
This is inherent to the design of Wasm and TCP MX. Wasm runs a single global timer so what you see is that ticker. TCP MX requires bytes to be sent first so we can't register the connection open immediately, so it waits 15s to check again.

**Comment by kyessenov** [comment]
I think with the new tighter implementation  for native stats we can probably report it much faster. The focus was just compatibility. Let's leave this as a feature request.

cc @zirain

**Comment by zirain** [comment]
FYI: https://github.com/istio/api/pull/2539

cc @kyessenov

**Comment by kyessenov** [comment]
@zirain This is different from histogram. This is referring to the delay in reporting in TCP metrics because of global timer in Wasm.

**Comment by zirain** [comment]
> @zirain This is different from histogram. This is referring to the delay in reporting in TCP metrics because of global timer in Wasm.

how can you configure this after switch to native stats?

**Comment by zirain** [comment]
@ryota2425 here is a workaround, edit the envoyfilter as follow:

![image](https://user-images.githubusercontent.com/4354057/200113007-47dc34e0-a65a-40d4-aa82-fb88a1865b0e.png)

**Comment by kyessenov** [comment]
@zirain The new stats filter uses a per-worker timer. So it's bound to the connection rather than one big timer for all connections. So it'll be less bumpy. I was also suggesting to emit stats as soon as bytes are sent/read instead of timer.

5s is reasonable.

**Comment by kyessenov** [comment]
@zirain Should that be a telemetry API option?

**Comment by zirain** [comment]
I think it should be, let's support this as part of v1.17, WDYT?

**Comment by ryota2425** [comment]
> @ryota2425 here is a workaround, edit the envoyfilter as follow:
> 
Thanks for the advices.
 I was able to get detailed TCP metrics.

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/29476187/200543132-78677950-1396-45a0-adcc-7f4f5fd5e0f4.png">

It would be useful to have an API option so that users can check the data in detail.

**Comment by zirain** [comment]
plan to add an option in Telemetry API
