### ISSUE TITLE
Why is the istio gateway upgraded in place when the istio official canary upgrades the control plane?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#41762]
Hi everyone, I have a question. I have a question when I refer to the istio canary upgrade? Why upgrade the gateway to the latest version at one time when upgrading, so there will be no problem? Documentation address: https://istio.io/latest/docs/setup/upgrade/canary/

After performing a control plane upgrade:

```
 $ kubectl get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-eastwestgateway-6dc476d9d-l75qm   1/1     Running   0          114m
istio-ingressgateway-b99548bf5-9xlvc    1/1     Running   0          114m
istiod-1-15-2-5b89689d96-vv5zd          1/1     Running   0          114m
istiod-6d65977984-vpl6t                 1/1     Running   0          23h
```

In my understanding, gateways should be similar to business services, and should be selectively upgraded, not updated to the latest version at one time.

Do you know why bro? Will there be any problems with updating the gateway in place?

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/gateway/#upgrading-gateways

**Comment by mark8s** [comment]
@howardjohn tks!!!
