### ISSUE TITLE
Can we define IP:Port format in Istio Gateway config

### ISSUE THREAD

**Issue by VarunTyagi86** [istio/istio#41774]
### Bug Description

Previously i had defined IP:Port in my istio gateway defintion under hosts. It was working fine and istio was not complaining. Now we reinstall the same version of istio but now it is throwing error configuration is invalid.

upgrade.go:434: [debug] warning: Upgrade "release-cicd-gw" failed: failed to replace object: admission webhook "validation.istio.io" denied the request: configuration is invalid: 3 errors occurred:
14:43:08      * domain name "xxx.xxx.70:31382" invalid (label "70:31382" invalid)
14:43:08      * domain name "xxx.xxx.104:31382" invalid (label "104:31382" invalid)
14:43:08  	* domain name "xxx.xxx.71:31382" invalid (label "71:31382" invalid)

Please let us know if IP:Port is allowed under hosts in gateway configuration

### Version

```prose
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (34 proxies)

Client Version: v1.21.2
Server Version: v1.22.15
```

**Comment by howardjohn** [comment]
I don't think this was ever allowed; likely if it worked before somehow the validation webhook was not running properly...?
