### ISSUE TITLE
Support configuring TLS min/max version and elliptic curves

### ISSUE THREAD

**Issue by jewertow** [istio/istio#41772]
**Describe the feature request**

Some companies have very strict security policies for the TLS settings they use in their systems. These policies applies also to SDS and webhook listeners exposed by istiod, but currently it's possible to configure only TLS [ca](https://github.com/istio/istio/blob/9e80784e1c17c970b7a50dbc47887bc3598afd55/pilot/cmd/pilot-discovery/app/cmd.go#L172), [cert](https://github.com/istio/istio/blob/9e80784e1c17c970b7a50dbc47887bc3598afd55/pilot/cmd/pilot-discovery/app/cmd.go#L174), [key](https://github.com/istio/istio/blob/9e80784e1c17c970b7a50dbc47887bc3598afd55/pilot/cmd/pilot-discovery/app/cmd.go#L176) and [cipher suites](https://github.com/istio/istio/blob/9e80784e1c17c970b7a50dbc47887bc3598afd55/pilot/cmd/pilot-discovery/app/cmd.go#L178).
There is no option to specify TLS min/max version and elliptic curves, so I would like to add 3 additional arguments for these parameters: `--tls-min-version`, `tls-max-version` and `tls-ecdh`.

This may be important especially for users who need [Support For Extended TLS Settings](https://github.com/istio/istio/issues/41645).

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
--tls-min-version, tls-max-version should be possible now

**Comment by jewertow** [comment]
I'm closing as we decided on the community call today.
