### ISSUE TITLE
mtls addition to istio dashboard broke e2e_dashboard test

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#4178]
Leads to issues:

```
--- FAIL: TestDashboards/Istio (0.06s)
    	dashboard_test.go:96: For Istio, checking 24 queries.
    	dashboard_test.go:118: Expected a metric value for 'round(sum(irate(istio_request_count{source_service=~"istio-ingress.*",source_version=~"unknown",destination_service=~"echosrv.*",destination_version=~"v1.*",connection_mtls="true"}[1m])), 0.001)', found no samples: model.Vector{}
```

Previously: this log was:

```
--- PASS: TestDashboards/Istio (0.09s)
    	dashboard_test.go:96: For Istio, checking 22 queries.
```

Fix is to remove `connection_mtls=\"(true|false)"` from query string (to allow for both auth and non-auth envs).

cc: @JimmyCYJ

**Comment by charleslieferando** [comment]
@douglas-reid  does this mean istio dashboard is broken in 0.6.0? Since I updated, I cannot see any metrics on the istio dashboard but the mixer and pilot dashboards work fine.

**Comment by douglas-reid** [comment]
@charleslieferando no. it means that a PR that went in during the last week broke the e2e tests that were added this last week as well.

The e2e_dashboard tests (and a series of recent fixes related to data quality, etc.) confirm working behavior of the dashboards moving forward.

Have you tried running from a recent daily (https://github.com/istio/istio/wiki/Daily-builds)?  If you are still having issues, please file a separate issue to track.
