### ISSUE TITLE
Some Questions About the Fault Tolerance Mechanism of VirtualService

### ISSUE THREAD

**Issue by feimeng1029** [istio/istio#41787]
After configuring the virtualservice, if 100% of the traffic points to subset1 and the endpoints of subset1 are unhealthy, what configuration allows the traffic to automatically request the endpoints of subset2。

istio verison 1.9.2
envoy version 1.17
k8s verison 1.20

**Comment by hzxuzhonghu** [comment]
Istio makes use of  weighted clusters to represent different subsets, currently it is not viable with VS setting to do failover between subsets.

**Comment by feimeng1029** [comment]
Is there any solution or configuration to solve this problem?

> Istio makes use of weighted clusters to represent different subsets, currently it is not viable with VS setting to do failover between subsets.
