### ISSUE TITLE
Support the secrets in non ingress gateway namespace

### ISSUE THREAD

**Issue by liyihuang** [istio/istio#41794]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Let's say I have ingress(where we have the ingress pod running), app1(app1 running ), and app2(app2 running) namespaces. we can configure the gateway resource in app1 and app2, even if we have the ingress pod running in the ingress namespace. However, we still have to put the app1 and app2 gateway TLS secrets in the ingress namespace. If we want the app1 and app2 namespace admin to manage the gateway resource themselves, it will be very challenging since they can't put the TLS secerts in the app1/app2 namespace

I hope we can have another env var or additional logic within istio to scan the secrets in the same namespace with the gateway resource(I believe nginx is doing it this way) so we don't have to put all the secrets in the same namespace with the ingress pod.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/14598
