### ISSUE TITLE
Will workloadInstancesIPsByName cause memory leak? It seems that it has never been released

### ISSUE THREAD

**Issue by karlhjm** [istio/istio#41824]
https://github.com/istio/istio/blob/4c9775258bb08ecc103d4ac5c0894dd1c3a08375/pilot/pkg/serviceregistry/kube/controller/controller.go#L1150-L1170

Why do we only clean up "workloadInstancesByIP" and ignore "workloadInstancesIPsByName"? Are there any other considerations

**Comment by hzxuzhonghu** [comment]
These code has been refactorred, what version is it?

**Comment by karlhjm** [comment]
> These code has been refactorred, what version is it?

This structure still exists in version 1.13

**Comment by karlhjm** [comment]
> These code has been refactorred, what version is it?

the structure 'workloadInstancesIPsByName' exists from 1.7 to 1.13

**Comment by howardjohn** [comment]
Sounds like it's already been fixed then...?

**Comment by dhawton** [comment]
Has been refactored since. Back in Feb this PR got merged: https://github.com/istio/istio/pull/37129 so it should be part of 1.14+
