### ISSUE TITLE
Use ISTIO-Ingressgateway external IP

### ISSUE THREAD

**Issue by poinsetta789** [istio/istio#41830]
### Bug Description

URGENT HELP---When we started with ISTIO 2 years ago, we were able to use the external IP of the 'ingress-gateway' as the IP we point to to connect to all of our AKS cluster pods where all of our microservices are running. Sometime ago, it no longer works and we now have to point our APIM gateway to the individual IP for each pod. We also used to use KIALI which allows us to manage the weighted load balancing with this '1' external IP. Since we lost the ability to use '1' IP to point to, we also have challenges with using HPA and liveness probe. We are in process of deploying the HPA for all of our pods and cannot because of this limitation. Can anyone help us with this problem. How are other customers of ISTIO able to connect to multiple pods without having having to point to individual pod's IP? We need to have the 'IP persistence'. Everytime our pod goes down we have to update the IP in the API Gateway. Please help. Any help would greatly help us tremendously!! We are currently using AKS cluster version 1.22.6 and ISTIO 1.13. We are about to upgrade to 1.23 AKS and ISTIO 1.15.

### Version

```prose
$ istioctl version
client version: 1.14.4
control plane version: 1.13.1
data plane version: 1.13.1 (108 proxies)
```

**Comment by rudy500** [comment]
Hi, 

I think your problem goes through this inside the operator manifest:

![imagen](https://user-images.githubusercontent.com/49110698/200574831-9c8dda27-2ac8-41a9-91ff-765e73d34c31.png)

as you can see there I pass a variable where I declare the global ip that I will always use in that gateway, then with sed I assign it by substitution at the bash level, but you can do it in the way that is convenient for you in your pipeline.

best regards

**Comment by keithmattix** [comment]
Hi @poinsetta789,

Are you still experiencing this issue? istio-ingressgateway is usually deployed as a Kubernetes Service with type: `Loadbalancer` and the cloud provider provides the IP address. Is that not happening in your case?
