### ISSUE TITLE
Leverage circleci API to retrigger suspected flakes

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4184]
Look through [circleci API](https://circleci.com/docs/api/v1-reference/) to see if it’s possible to retry only
failed suites like we do for prow

**Comment by cmluciano** [comment]
looks like we can accomplish this with 

```
curl -X POST https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/:build_num/retry?circle-token=:token
```

**Comment by cmluciano** [comment]
@istio/reviewers-istio-release Do we just need to add a script under https://github.com/istio/test-infra/blob/master/prow/config.yaml ?

**Comment by cmluciano** [comment]
cc @hklai

**Comment by cmluciano** [comment]
@costinm

**Comment by sebastienvas** [comment]
I think It is a little more complicated that this, I think the right approach would be to update [Prow trigger plugin](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/trigger/ic.go) to look for jobs that starts with circleci and then use the circle API to trigger them. Can every body retrigger a job ?

**Comment by cmluciano** [comment]
We should have the same permissions as the prow plugin. Do you know if that currently limits retest to org members?

**Comment by hklai** [comment]
To make sure I understand the intent, is this supposed to make circle ci respond to "/retest"?

Flake or not it is a judgement made by the dev, but the bot, right?

**Comment by cmluciano** [comment]
Yes that is correct @hkai . I foresee it being used to retry a suspected flaky run.

**Comment by cmluciano** [comment]
Closing for now since this seems like a feature that most use the web-ui for
