### ISSUE TITLE
On Oracle Linux Server 8.5: istio pods crash with Failed to execute: iptables-restore 

### ISSUE THREAD

**Issue by sankarpn** [istio/istio#41874]
### Bug Description

Installed istio version 1.15.3
Deployed WebLogic Kubernetes Operator(https://github.com/oracle/weblogic-kubernetes-operator) with istio injection enabled.

The istio-init pod keeps crashing with this error.

`[opc@operator0 weblogic-kubernetes-operator]$ k logs -n ns-yotaci pod/weblogic-operator-54b5f5bcd9-shclg -c istio-init
2022-11-08T22:47:59.763888Z     info    Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=

2022-11-08T22:47:59.763928Z     info    Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
HOST_NSENTER_EXEC=false
EXCLUDE_INTERFACES=

2022-11-08T22:47:59.764080Z     info    Writing following contents to rules file: /tmp/iptables-rules-1667947679763963201.txt1138827592
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2022-11-08T22:47:59.764111Z     info    Running command: iptables-restore --noflush /tmp/iptables-rules-1667947679763963201.txt1138827592
2022-11-08T22:47:59.766102Z     error   Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
2022-11-08T22:47:59.766116Z     error   Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1667947679763963201.txt1138827592, exit status 2
[opc@operator0 weblogic-kubernetes-operator]$ cat /tmp/iptables-rules-1667947679763963201.txt1138827592
cat: /tmp/iptables-rules-1667947679763963201.txt1138827592: No such file or directory
`

### Version

```prose
bin/istioctl x precheck
  bin/istioctl install --set profile=demo --set values.global.imagePullSecrets[0]=docker-istio-secret --set meshConfig.enablePrometheusMerge=false -y
  bin/istioctl verify-install
  bin/istioctl version

Thank you for installing Istio 1.15.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/SWHFBmwJspusK1hv6
1 Istio control planes detected, checking --revision "default" only
✔ ClusterRole: istiod-istio-system.istio-system checked successfully
✔ ClusterRole: istio-reader-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istio-reader-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-istio-system.istio-system checked successfully
✔ ServiceAccount: istio-reader-service-account.istio-system checked successfully
✔ Role: istiod-istio-system.istio-system checked successfully
✔ RoleBinding: istiod-istio-system.istio-system checked successfully
✔ ServiceAccount: istiod-service-account.istio-system checked successfully
✔ CustomResourceDefinition: wasmplugins.extensions.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: destinationrules.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: envoyfilters.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: gateways.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: proxyconfigs.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: serviceentries.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: sidecars.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: virtualservices.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: workloadentries.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: workloadgroups.networking.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: authorizationpolicies.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: peerauthentications.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: requestauthentications.security.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: telemetries.telemetry.istio.io.istio-system checked successfully
✔ CustomResourceDefinition: istiooperators.install.istio.io.istio-system checked successfully
✔ ClusterRole: istiod-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRole: istiod-gateway-controller-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istiod-gateway-controller-istio-system.istio-system checked successfully
✔ ConfigMap: istio.istio-system checked successfully
✔ Deployment: istiod.istio-system checked successfully
✔ ConfigMap: istio-sidecar-injector.istio-system checked successfully
✔ MutatingWebhookConfiguration: istio-sidecar-injector.istio-system checked successfully
✔ PodDisruptionBudget: istiod.istio-system checked successfully
✔ ClusterRole: istio-reader-clusterrole-istio-system.istio-system checked successfully
✔ ClusterRoleBinding: istio-reader-clusterrole-istio-system.istio-system checked successfully
✔ Role: istiod.istio-system checked successfully
✔ RoleBinding: istiod.istio-system checked successfully
✔ Service: istiod.istio-system checked successfully
✔ ServiceAccount: istiod.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.13.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.13.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.14.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.14.istio-system checked successfully
✔ EnvoyFilter: stats-filter-1.15.istio-system checked successfully
✔ EnvoyFilter: tcp-stats-filter-1.15.istio-system checked successfully
✔ ValidatingWebhookConfiguration: istio-validator-istio-system.istio-system checked successfully
✔ Deployment: istio-ingressgateway.istio-system checked successfully
✔ PodDisruptionBudget: istio-ingressgateway.istio-system checked successfully
✔ Role: istio-ingressgateway-sds.istio-system checked successfully
✔ RoleBinding: istio-ingressgateway-sds.istio-system checked successfully
✔ Service: istio-ingressgateway.istio-system checked successfully
✔ ServiceAccount: istio-ingressgateway-service-account.istio-system checked successfully
✔ Deployment: istio-egressgateway.istio-system checked successfully
✔ PodDisruptionBudget: istio-egressgateway.istio-system checked successfully
✔ Role: istio-egressgateway-sds.istio-system checked successfully
✔ RoleBinding: istio-egressgateway-sds.istio-system checked successfully
✔ Service: istio-egressgateway.istio-system checked successfully
✔ ServiceAccount: istio-egressgateway-service-account.istio-system checked successfully
Checked 15 custom resource definitions
Checked 3 Istio Deployments
✔ Istio is installed and verified successfully
client version: 1.15.3
control plane version: 1.15.3
data plane version: 1.15.3 (2 proxies)
Istio installation is SUCCESS
Http2 NodePort Service is listening on port [31353], stderr = + version=1.15.3



[opc@operator0 weblogic-kubernetes-operator]$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.5+1.el8
Kustomize Version: v4.5.4
Server Version: v1.24.5+1.el8
```

### Additional Information

[opc@operator0 weblogic-kubernetes-operator]$ /tmp/it-testsresults/workdir/istio-1.15.3/bin/istioctl bug-report

Target cluster context: kubernetes-admin@kubernetes

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-11-08 23:00:40.630519476 +0000 UTC

Cluster endpoint: https://10.0.1.3:6443

CLI version:
version.BuildInfo{Version:"1.15.3", GitRevision:"bc21f4628d31fe5380569db6fa0e73517d956a0d", GolangVersion:"go1.19.2", BuildStatus:"Clean", GitTag:"1.15.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.3", GitRevision:"bc21f4628d31fe5380569db6fa0e73517d956a0d", GolangVersion:"go1.19.2", BuildStatus:"Clean", GitTag:"1.15.3"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.3}

Fetching proxy logs for the following containers:

cert-manager/cert-manager-cainjector/cert-manager-cainjector-8676c4b7-t5jgq/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-557fb758cf-97q44/cert-manager-webhook
cert-manager/cert-manager/cert-manager-646dddd544-ct7pz/cert-manager-controller
default//dnsutils/dnsutils
istio-system/istio-egressgateway/istio-egressgateway-665b687df7-7xrst/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-588f7b8b9-lbztl/istio-proxy
istio-system/istiod/istiod-78b5786ddb-jgzwm/discovery
kubernetes-dashboard/kubernetes-dashboard/kubernetes-dashboard-57c84984cd-jlvpp/kubernetes-dashboard
ns-webhook/weblogic-operator-webhook/weblogic-operator-webhook-6d5d7c4bcd-c4779/weblogic-operator-webhook
ns-yotaci/weblogic-operator/weblogic-operator-54b5f5bcd9-shclg/istio-proxy
ns-yotaci/weblogic-operator/weblogic-operator-54b5f5bcd9-shclg/weblogic-operator

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0103] (Pod default/dnsutils) The pod default/dnsutils is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kubernetes-dashboard) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kubernetes-dashboard istio-injection=enabled' to enable it, or 'kubectl label namespace kubernetes-dashboard istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace ns-fepiqv) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ns-fepiqv istio-injection=enabled' to enable it, or 'kubectl label namespace ns-fepiqv istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace ns-webhook) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ns-webhook istio-injection=enabled' to enable it, or 'kubectl label namespace ns-webhook istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service kubernetes-dashboard/kubernetes-dashboard) Port name  (port: 443, targetPort: 8443) doesn't follow the naming convention of Istio port.
Creating an archive at /home/opc/sankar/weblogic-kubernetes-operator/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by sankarpn** [comment]
Also see these errors in kubelet logs

`Nov 08 22:29:51 master0 kubelet[49626]: I1108 22:29:51.888728   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:29:51 master0 kubelet[49626]: E1108 22:29:51.889495   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:30:04 master0 kubelet[49626]: I1108 22:30:04.889098   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:30:04 master0 kubelet[49626]: E1108 22:30:04.889652   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:30:17 master0 kubelet[49626]: I1108 22:30:17.888990   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:30:17 master0 kubelet[49626]: E1108 22:30:17.889288   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:30:29 master0 kubelet[49626]: I1108 22:30:29.888992   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:30:29 master0 kubelet[49626]: E1108 22:30:29.889279   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:30:40 master0 kubelet[49626]: I1108 22:30:40.889077   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:30:40 master0 kubelet[49626]: E1108 22:30:40.889423   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:30:51 master0 kubelet[49626]: I1108 22:30:51.889547   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:30:51 master0 kubelet[49626]: E1108 22:30:51.890340   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:31:04 master0 kubelet[49626]: I1108 22:31:04.889701   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:31:05 master0 kubelet[49626]: I1108 22:31:05.118063   49626 scope.go:110] "RemoveContainer" containerID="9453d31596f69703eb456dbf2e1e9357415b206d4bb3b049c0cc9bcb5c29ee6b"
Nov 08 22:31:05 master0 kubelet[49626]: I1108 22:31:05.118630   49626 scope.go:110] "RemoveContainer" containerID="f0cd584794350f56d023f4b7d7fc26a57c4712485af8f7dc22c9cb80ca5a2aba"
Nov 08 22:31:05 master0 kubelet[49626]: E1108 22:31:05.119006   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:31:06 master0 kubelet[49626]: I1108 22:31:06.120948   49626 scope.go:110] "RemoveContainer" containerID="f0cd584794350f56d023f4b7d7fc26a57c4712485af8f7dc22c9cb80ca5a2aba"
Nov 08 22:31:06 master0 kubelet[49626]: E1108 22:31:06.121223   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:31:17 master0 kubelet[49626]: I1108 22:31:17.888609   49626 scope.go:110] "RemoveContainer" containerID="f0cd584794350f56d023f4b7d7fc26a57c4712485af8f7dc22c9cb80ca5a2aba"
Nov 08 22:31:17 master0 kubelet[49626]: E1108 22:31:17.889127   49626 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=install-cni pod=istio-cni-node-r24ss_istio-system(8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6)\"" pod="isti>
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.351043   49626 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"cni-log-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-log-dir\") pod \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\" (UID: \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\") "
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.351716   49626 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-5nhhw\" (UniqueName: \"kubernetes.io/projected/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-kube-api-access-5nhhw\") pod \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\" (UID: \"8b68ef30-b2f4-4d04-a>
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.352307   49626 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"cni-net-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-net-dir\") pod \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\" (UID: \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\") "
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.351261   49626 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-log-dir" (OuterVolumeSpecName: "cni-log-dir") pod "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6" (UID: "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6">
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.352401   49626 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-net-dir" (OuterVolumeSpecName: "cni-net-dir") pod "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6" (UID: "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6">
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.354234   49626 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"cni-bin-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-bin-dir\") pod \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\" (UID: \"8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6\") "
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.354293   49626 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-bin-dir" (OuterVolumeSpecName: "cni-bin-dir") pod "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6" (UID: "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6">
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.358782   49626 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-kube-api-access-5nhhw" (OuterVolumeSpecName: "kube-api-access-5nhhw") pod "8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6" (UID: "8b68ef30-b2f4-4d0>
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.454725   49626 reconciler.go:384] "Volume detached for volume \"cni-log-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-log-dir\") on node \"master0\" DevicePath \"\""
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.454763   49626 reconciler.go:384] "Volume detached for volume \"kube-api-access-5nhhw\" (UniqueName: \"kubernetes.io/projected/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-kube-api-access-5nhhw\") on node \"master0\" DevicePath \"\""
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.454772   49626 reconciler.go:384] "Volume detached for volume \"cni-net-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-net-dir\") on node \"master0\" DevicePath \"\""
Nov 08 22:31:23 master0 kubelet[49626]: I1108 22:31:23.454779   49626 reconciler.go:384] "Volume detached for volume \"cni-bin-dir\" (UniqueName: \"kubernetes.io/host-path/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6-cni-bin-dir\") on node \"master0\" DevicePath \"\""
Nov 08 22:31:24 master0 kubelet[49626]: I1108 22:31:24.151255   49626 scope.go:110] "RemoveContainer" containerID="f0cd584794350f56d023f4b7d7fc26a57c4712485af8f7dc22c9cb80ca5a2aba"
Nov 08 22:31:25 master0 kubelet[49626]: I1108 22:31:25.892195   49626 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6 path="/var/lib/kubelet/pods/8b68ef30-b2f4-4d04-a93c-2d7bd22e4ae6/volumes"
`

**Comment by howardjohn** [comment]
Your cluster must meet these requirements: https://istio.io/latest/docs/setup/platform-setup/prerequisites/

**Comment by Tarasovych** [comment]
Same issue here with Oracle 8.6 image
