### ISSUE TITLE
Support AKS for ambient

### ISSUE THREAD

**Issue by zioproto** [istio/istio#41917]
### Bug Description

Installing Istio Ambient in AKS, as soon as the namespace is label istio.io/dataplane-mode=ambient the Pods lose all the connectivity.

I tracked down the problem to the geneve tunnel between the Kubernetes node and the ztunnel pod to be broken.

Doing a `tcpdump` in the `ztunnel` pod on interface `eth0` I see geneve traffic coming in, where the source IP address is the IP address of the Kubernetes node. In this example 10.240.0.4 is the IP address of the kubernetes node and 10.240.0.52 is the IP address of the `ztunnel` pod:

```
root@ztunnel-f4d6p:/# tcpdump -i eth0 -n udp
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
21:01:14.807437 IP 10.240.0.4.61534 > 10.240.0.52.6081: Geneve, Flags [none], vni 0x3e9: ARP, Request who-has 192.168.127.2 tell 192.168.127.1, length 28
21:01:15.834678 IP 10.240.0.4.61534 > 10.240.0.52.6081: Geneve, Flags [none], vni 0x3e9: ARP, Request who-has 192.168.127.2 tell 192.168.127.1, length 28
```

The traffic is not passed to the geneve interface `istioin` because the geneve tunnel is setup incorrectly:

The `ztunnel` initContainer has this code:

https://github.com/istio/istio/blob/23bfa062c7107a45e6b863c9f976cf1fd22f7e26/manifests/charts/ztunnel/templates/daemonset.yaml#L116-L125

There is a problem with the line:
```
HOST_IP=$(ip route | grep default | awk '{print $3}')
```

In Microsoft Azure AKS `HOST_IP` will always get the value 169.254.1.1

Example routing table inside the `ztunnel` pod:

```
root@ztunnel-f4d6p:/# ip route
default via 169.254.1.1 dev eth0 proto static
169.254.1.1 dev eth0 proto static scope link
192.168.126.0/30 dev pistioin proto kernel scope link src 192.168.126.2
192.168.127.0/30 dev pistioout proto kernel scope link src 192.168.127.2
```

The script should be portable to detect the `HOST_IP` correctly on different Kubernetes platforms

### Version

```prose
go run ./istioctl/cmd/istioctl version
client version: unknown
control plane version: 1.17
data plane version: 1.17-dev (3 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.2
```

**Comment by zioproto** [comment]
I confirm I was able to make it work on AKS using `HOST_IP` passed from the environment in the init container like it is already defined:

https://github.com/istio/istio/blob/23bfa062c7107a45e6b863c9f976cf1fd22f7e26/manifests/charts/ztunnel/templates/daemonset.yaml#L217-L220

So what I did was just deleting line 118 from my daemonSet.

https://github.com/istio/istio/blob/23bfa062c7107a45e6b863c9f976cf1fd22f7e26/manifests/charts/ztunnel/templates/daemonset.yaml#L117-L119

`kubectl edit ds ztunnel -n istio-system` and I deleted the line:
```
HOST_IP=$(ip route | grep default | awk '{print $3}')
```

Looking at the existing if block:
```
{{- if not (.Capabilities.KubeVersion.GitVersion | contains "-eks") }}
```
I understand probably the same workaround is for EKS.

I am currently installing doing:
```
go run ./istioctl/cmd/istioctl install  --set hub=$HUB --set tag=$TAG --set profile=ambient -y
```
I am looking at:
https://helm.sh/docs/chart_template_guide/builtin_objects/

but I dont know how to figure out what is my value for `.Capabilities.KubeVersion.GitVersion`

Is it the same value as this ?
```
kubectl version -o json | jq  .serverVersion.gitVersion
"v1.25.2"
```

If it is I have "v1.25.2" and I have nothing AKS specific to use in the if condition.

**Comment by 4c74356b41** [comment]
I tried with a blank template and for me `.Capabilities.KubeVersion.GitVersion` resolves to `v1.24.0` so yeah, not sure how to check if we are running on AKS. but using the same fix doesnt work for me. even if I hardcode `host_ip`. can you share the command you used to create your cluster?

**Comment by zioproto** [comment]
I created the cluster from the Azure Portal, I just selected Azure CNI and I kept all the default options. I used 2 nodes `Standard_DS2_v2`.

After I patched the `ztunnel` daemonSet I also restarted all the `istio-cni-node` pods:
```
 kubectl delete pods -n istio-system -l k8s-app=istio-cni-node
```

What do you mean exactly for " doesnt work for me" ? What exactly is not working ?

The way I am testing is creating a pod:
```
kubectl run -ti --rm netshoot --image=nicolaka/netshoot /bin/bash
```

Then from this pod I try to curl externally, like:
`curl 1.1.1.1`

Or I try to curl to other Pods in the same namespace.

I see the traffic going though the `ztunnel` pod in the same node as the `netshoot` pod.

Could you please share how you are testing ? thanks

**Comment by 4c74356b41** [comment]
I'm testing using this blog post: https://istio.io/latest/blog/2022/get-started-ambient/

```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f https://raw.githubusercontent.com/linsun/sample-apps/main/sleep/sleep.yaml
kubectl apply -f https://raw.githubusercontent.com/linsun/sample-apps/main/sleep/notsleep.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl label namespace default istio.io/dataplane-mode=ambient
```
everything works fine before I run the last command. I can access bookinfo application using ingress gateway. as soon as I label it - things stop working. i did try deleting all the pods in the `istio-system` namespace. didn't help.

i just tried curling from a pod in the default namespace - it times out

**Comment by zioproto** [comment]
Hello,
I installed bookinfo and it works for me,

I tried doing a curl from a Pod inside the same namespace with:
```
curl -s http://istio-ingressgateway.istio-system/productpage
```

and also it works using the public IP address of the istio-ingressgateway from outside of the cluster.

Can you share the the script of the initContainer of your ztunnel daemonSet ? you can pull it out of the cluster like this:

```
kubectl get ds ztunnel -n istio-system -o json | jq -r '.spec.template.spec.initContainers[0].command[2]'
```

and also the `env` part:
```
 kubectl get ds ztunnel -n istio-system -o json | jq -r '.spec.template.spec.initContainers[0].env'
```

thanks

**Comment by zioproto** [comment]
@4c74356b41 here my full example:

Create the AKS cluster
```
az aks create \
--location eastus \
--name ambient \
--resource-group ubuntu22 \
--network-plugin azure \
--kubernetes-version 1.25.2 \
--node-vm-size Standard_DS2_v2 \
--node-count 2
```

Install istio Ambient:
```
az aks get-credentials --resource-group ubuntu22 --name ambient
export TAG=ambient
export HUB=zioproto
# I already compiled at commit 23bfa062c7107a45e6b863c9f976cf1fd22f7e26
go run ./istioctl/cmd/istioctl install  --set hub=$HUB --set tag=$TAG --set profile=ambient -y
```

Edit the DaemonSet:
```
kubectl edit ds ztunnel -n istio-system
```

remove the line:
```
HOST_IP=$(ip route | grep default | awk '{print $3}') 
```
and save

restart the istio-cni pods:

```
 kubectl delete pods -n istio-system -l k8s-app=istio-cni-node
```

Install bookinfo and label the namespace for Ambient:
```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f https://raw.githubusercontent.com/linsun/sample-apps/main/sleep/sleep.yaml
kubectl apply -f https://raw.githubusercontent.com/linsun/sample-apps/main/sleep/notsleep.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl label namespace default istio.io/dataplane-mode=ambient
```

Everything is working as expected after these steps. In the `ztunnel`pods I also see the log lines with the requests to the bookinfo application.

**Comment by zioproto** [comment]
@howardjohn I see in commit b2e658b58cae8c6c399f4e3f7da79a1a5742fae0 you removed specific profiles for AWS and GKE in favour of "autodetect". I am not really sure how to autodetect AKS here. What is the plan here to support multiple managed Kubernetes platforms ? thanks

**Comment by zioproto** [comment]
For AWS I understand you are using the helm built-in `(.Capabilities.KubeVersion.GitVersion | contains "-eks")` for the `ztunnel` daemonSet template. This is because the EKS clusters return a string that contains "eks".

How are you autodetecting GKE ? I dont understand from the code.

**Comment by howardjohn** [comment]
I think its also `.Capabilities.KubeVersion.GitVersion | contains "-gke"`?

**Comment by zioproto** [comment]
OK. I understand now that for the `ztunnel` the gke autodetection is not needed: 

https://github.com/istio/istio/blob/23bfa062c7107a45e6b863c9f976cf1fd22f7e26/manifests/charts/ztunnel/templates/daemonset.yaml#L117-L119

but I found the `.Capabilities.KubeVersion.GitVersion | contains "-gke"` elsewhere in the code.

The problem I have is that AKS does not add any `-aks` string to the `GitVersion:"v1.23.12"` so I dont have anything to match against in the Git Version.

I also looked into `Capabilities.APIVersions` but there is not any AKS specific one that I can match against to autodetect.

**Comment by zioproto** [comment]
It seems this platform detection based on `GitVersion` is very fragile for AWS EKS:
https://github.com/aws/containers-roadmap/issues/1404

**Comment by howardjohn** [comment]
Looks like they reverted it specifically because it broke folks doing what we do above, which gives me some confidence it will work? Worst case if they change it we could modify the logic. I don't see any other mechanism to detect it

**Comment by 4c74356b41** [comment]
other option would be to have a value for this? because it looks like as it is today you cant detect AKS which is top 3 managed kubernetes out there

**Comment by howardjohn** [comment]
We can have an explicit option but on platforms that detect we should as well. I am almost certain that most AKS users will try to install it without the flag, it will fail, and then they will be confused. So auto-detection is critical.

**Comment by 4c74356b41** [comment]
but you dont have a way to autodetect azure?

**Comment by zioproto** [comment]
I am trying to autodetect AKS in this way:

```
{{- if and (not (.Capabilities.KubeVersion.GitVersion | contains "-eks")) (not (lookup "apps/v1" "DaemonSet" "kube-system" "azure-ip-masq-agent")) }}
            HOST_IP=$(ip route | grep default | awk '{print $3}')
{{- end }}
```

But it does not work because this lookup function:
`{{ (lookup "apps/v1" "DaemonSet" "kube-system" "azure-ip-masq-agent") }}`

is returning **always** an empty map: `map[]`

This is probably an helm bug because the DaemonSet actually exists.

```
kubectl get ds -n kube-system azure-ip-masq-agent
NAME                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
azure-ip-masq-agent   2         2         2       2            2           <none>          96m
```

To debug the template I tried in the folder `manifests/charts/ztunnel` to run helm directly:
```
helm install test .
```

Any other ideas on how to detect AKS ?

**Comment by 4c74356b41** [comment]
@zioproto keep in mind you need to actually install the chart to test this, doing `helm template` won't evaluate `lookup` function. ie your example works fine for me.

**Comment by zioproto** [comment]
I am on this helm version:
```
 helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```

Are you on the same ?

Also, when we install with `istioctl`, is it equivalent to `helm install` or to `helm template` ? I mean, can we call the `lookup` function when installing the chart using `istioctl` ?

**Comment by 4c74356b41** [comment]
i'm using some old helm, like 3.8.x, but that was that for ages. as for the istioctl, sorry, i dont know.

**Comment by howardjohn** [comment]
I don't think doing a `lookup` is appropriate in our install

**Comment by SkyfireFrancisZ** [comment]
not Alpha blocking

**Comment by keithmattix** [comment]
Looking into this

**Comment by bleggett** [comment]
Reopening - haven't tested this yet, but it should fix.

**Comment by zioproto** [comment]
Hello. I tested at commit 76c45169acca08dad4599171265a7ae0dab2ea40 and I confirm that the istio ambient installation is successfull on AKS with the latest changes.

Details of how I tested are published here: https://gist.github.com/zioproto/4d4e58b8ae6135b335d2fdef3df90875

**Comment by PaleHazy** [comment]
@zioproto Thank you! 
```
service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /productpage
```

was the secret sauce for me
