### ISSUE TITLE
newJwksResolverWithCABundlePaths in istio/pilot/pkg/model/jwks_resolver.go is unsafe

### ISSUE THREAD

**Issue by bochengchu** [istio/istio#41938]
In https://github.com/istio/istio/blob/791648f73e05ab85cb358a56d81c244da489b466/pilot/pkg/model/jwks_resolver.go#L170,
it uses TLS with `InsecureSkipVerify: true` which may have security issue.

**Comment by hzxuzhonghu** [comment]
fixed by #41930
