### ISSUE TITLE
DialOptions skips verifying certificates

### ISSUE THREAD

**Issue by bochengchu** [istio/istio#41937]
In https://github.com/istio/istio/blob/ebec74767feb6a34397ee6f23b3b2a2dc4c7c6ec/istioctl/pkg/xds/client.go#L102-L110,
DialOptions uses TLS with `InsecureSkipVerify: true`, which may have security issues.

**Comment by hzxuzhonghu** [comment]
Istio-agent already verify, this function is used only by istioctl, so looks good.
