### ISSUE TITLE
Duplicate property definition in CustomResourceDefinition requestauthentications.security.istio.io 

### ISSUE THREAD

**Issue by cache-sk** [istio/istio#41944]
### Bug Description

In [crd-all.gen.yaml](https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-all.gen.yaml#L6618) is defined k8s custom resource of kind RequestAuthentication

This resource have two properties - `jwks_uri` and `jwksUri` which seams as duplicate.

Is this correct?

Both are generated as `jwksUri` in java with openapi generator and it is obviously a conflict.

//EDIT

Same situation is with [virtualservices.networking.istio.io](https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-all.gen.yaml#L4704) where is defined `mirror_percent` and `mirrorPercent`, generated to conflict in java.

### Version

```prose
current master branch, direct link in description

label in k8s deployment says cloudfoundry.org/istio_version=1.13.4; deployed version have same duplicity
```

**Comment by howardjohn** [comment]
It's intended due to some legacy backwards compatibility
