### ISSUE TITLE
daily builds: confusing timestamps (still)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4194]
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/

last release dir is 0.7.0-pre20180309-09-15-15/

can we
a) drop the last -15 (assuming this is seconds ?) we aren't going to make more than 1 daily per minute (would be less confusing as 0.7.0-pre20180309-0915 )
b) when I click; https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.7.0-pre20180309-09-15-15/
all the timestamps are
09 Mar 2018 10:06:18

yet when I look inside the tar:

-rw-r--r--  0 releng releng      739 Mar  9 01:19 istio-0.7.0-pre20180309-09-15-15/istio.VERSION

what happened between 1:19 and 9:15 ? and what happened between 9:15 and 10:06 ?

Can we please make sure the daily show up as we talked about before 9a PST (ideally at 8a pst)

**Comment by hklai** [comment]
Release started at 9:15AM GMT, and took around an hour to complete and copy to GCS (hence around 10:06).

When you open the tarball locally, the 1am time is local time. =)
https://savvytime.com/converter/gmt-to-pst/mar-9-2018/9am

**Comment by ldemailly** [comment]
k then gcs web should show timestamp in the browser's timezone - or label clearly as GMT :-) 

can we still drop the seconds ?

I'll add the gmt thing to the wiki for now
