### ISSUE TITLE
Migrating CA Certificates

### ISSUE THREAD

**Issue by georgew5656** [istio/istio#41993]
I'm running into the CA validation issue described in: https://github.com/istio/istio/issues/38049

The deployment is on a EKS cluster with proxy containers.

The root certs I was using were generated with openssl 2.8.x using SHA1.

I'm trying to figure out the best way to migrate this cert to SHA2 without having to restart all the pods in the cluster to grab the new certificate. Is there anyway I could do something with a cert chain to get this to work?

**Comment by cheskayang** [comment]
@georgew5656 running into the same issue when upgrading istio to a newer version
did you manage to find a way to migrate the cert with minimal impact? TY
