### ISSUE TITLE
the env variable ISTIO_DELTA_XDS not take affect

### ISSUE THREAD

**Issue by whalecold** [istio/istio#42002]
### Bug Description

I add the env variable ISTIO_DELTA_XDS to the pilot-discovery by the [document](https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars), but it not take affect in actually. The api_type in the BootstrapConfigDump config is `GRPC`, but `DELTA_GRPC ` is expected.

```
"dynamic_resources": 
{
    "lds_config":{
        "ads":{

        },
        "initial_fetch_timeout":"0s",
        "resource_api_version":"V3"
    },
    "cds_config":{
        "ads":{

        },
        "initial_fetch_timeout":"0s",
        "resource_api_version":"V3"
    },
    "ads_config":{
        "api_type":"GRPC",
        "grpc_services":[
            {
                "envoy_grpc":{
                    "cluster_name":"xds-grpc"
                }
            }
        ],
        "set_node_on_first_message_only":true,
        "transport_api_version":"V3"
    }
}
```

### Version

```prose
client version: 1.15.3
control plane version: 1.15
data plane version: 1.15.3 (4 proxies), 1.14.3 (3 proxies)
```

**Comment by zirain** [comment]
do you set `proxyMetadata` in meshconfig or via ProxyConfig/annotation?

**Comment by whalecold** [comment]
> do you set `proxyMetadata` in meshconfig or via ProxyConfig/annotation?

I don't set proxyMetadata in the configmap of `isito`,  i try it and it is successful.  I think the env variable alse should take affect.
