### ISSUE TITLE
GenCSRTemplate

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#42004]
I changed the Organization and CommonName fields, but they were not in the generated certificate.As follows:

![image](https://user-images.githubusercontent.com/48784730/201892201-bf89e528-8aa3-47ac-9882-35521be02759.png)

The Subject field in the certificate is still the URI in the Subject Alternative Name. As follows:
![image](https://user-images.githubusercontent.com/48784730/201892712-9474e19d-8c00-48d3-b260-190423541a36.png)

Please help me, thank you

**Comment by chaunceyjiang** [comment]
Can you give me a minimum reproduce step?

**Comment by liuqi-sun** [comment]
> Can you give me a minimum reproduce step?

It's easy
1. Set IsDualUse to true
2. Modify the GenCSRTemplate function as shown in the image above
3. Configure istio-sidecar-injector cm to set env OUTPUT_CERTS

**Comment by howardjohn** [comment]
This is the template - Istio only extracts certain fields from it, it doesn't allow arbitrary CSRs.

**Comment by liuqi-sun** [comment]
> This is the template - Istio only extracts certain fields from it, it doesn't allow arbitrary CSRs.
thank you.
 I can't find the relevant logic in istiod source code, can you tell me which file? In addition, I modified the URI of CSR, but the URI in the generated certificate remains unchanged. Will istiod rewrite the URI in the certificate?

**Comment by liuqi-sun** [comment]
> This is the template - Istio only extracts certain fields from it, it doesn't allow arbitrary CSRs.
![image](https://user-images.githubusercontent.com/48784730/202088042-ded31717-2e73-413a-8426-37fbdba84398.png)

As shown in the figure above, the URI and Subject in the generated certificate should be caller.Identities?

**Comment by howardjohn** [comment]
Yes. See https://github.com/istio/istio/issues/42114 for FR for customization
