### ISSUE TITLE
numTrustedProxies set per istio ingress gateway

### ISSUE THREAD

**Issue by jdomag** [istio/istio#42001]
I have couple of ingress gateways serving traffic for different use cases  - some gateways terminates SSL and are exposed in AWS via NLB (passthru), some of them are exposed via ALB that terminates SSL. Those two use cases require setting different value of `numTrustedProxies` for each gateway, however the documentation says it's a global parameter. Would be nice to be able to set in `components.ingressGateways` 

[ ] Ambient
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by zirain** [comment]
I think ProxyConfig would help https://istio.io/latest/docs/reference/config/networking/proxy-config/

**Comment by jdomag** [comment]
> I think ProxyConfig would help https://istio.io/latest/docs/reference/config/networking/proxy-config/

How could it help exactly? Does it expose `numTrustedProxies`? Even so it's still a workaround and not a solution.

**Comment by howardjohn** [comment]
this is already supported and documented: https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-network-topologies

**Comment by nick4fake** [comment]
@howardjohn How exactly does it help? There is no example or reference to ProxyConfig , so even while it is supported extending docs might be helpful

**Comment by YvesEarnix** [comment]
@howardjohn 
Seem to be not working for Istio Waypoint Gateway.
Follow configuration have no impact
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: waypoint
spec:
  gatewayClassName: istio-waypoint
  infrastructure:
    annotations:
      proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 }}'
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
