### ISSUE TITLE
Connection Reset after upgrading Istio

### ISSUE THREAD

**Issue by azharudheen** [istio/istio#42013]
### Bug Description

We are using Istio on our Azure Kubernetes Cluster. Our applications are deployed in Java 11 (spring boot).
We recently upgraded from Istio 1.12 to 1.15. And right after the upgrade has been done, we started seeing random TCP Connection reset errors for the calls made to external services (backends) from the application in the cluster. The connection reset errors are random and are getting resolved once we restart the application pod or as soon as we reapply the default EnvoyFilters. We are not sure why this keeps happening.

Error message: 
com.sun.xml.ws.client.ClientTransportException: HTTP transport error: javax.net.ssl.SSLException: Connection reset
	at com.sun.xml.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:132)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:223)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:145)

### Version

```prose
$ istioctl version                     
client version: 1.15.3
control plane version: 1.15.1
data plane version: 1.15.1 (184 proxies)

$ kubectl version --short

Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.3
```

**Comment by mauro770** [comment]
Hello @azharudheen , have you found the root-cause of this problem? I'm experiencing the same problem but in my case is:

- Outgoing connections from the cluster to another cluster accessing through the Istio Gateway (not sure this is related to Istio though, we have to check the underlying infra)
- Incoming connections from another Spring boot app.

I'm running Istio 1.15.2
