### ISSUE TITLE
When upgrading the control plane, upgrade the istio gateway at the same time. Is this suitable for the production environment?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42027]
Hello everyone, I have a question.

Recently, I was researching the canary upgrade of istio, and I have a doubt. In the official document https://istio.io/latest/docs/setup/upgrade/canary/, when upgrading the control plane, it also upgrades the istio-ingressgateway. Now I want to know whether to do so Reasonable? Is this a reasonable upgrade process?

The original text is as follows:
```
Unlike istiod, Istio gateways do not run revision-specific instances, but are instead in-place upgraded to use the new control plane revision.
```

I was wondering if anyone has done this?

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/gateway/ is recommended
