### ISSUE TITLE
Out-of-proc adapters

### ISSUE THREAD

**Issue by guptasu** [istio/istio#4202]
Design
https://docs.google.com/document/d/1TTyL9Fpfrvk5grhYgsjoASVXFQTRCI2YOesrzA6fqkQ/edit#

Updated IBP definition
https://docs.google.com/document/d/1Fic1Mgp0W5Sxhd0BxAFOc82DbSYWTsYpi5P-pv8ZjSQ/edit?ts=5a99d7ae#

@douglas-reid @geeknoid @mandarjog @ozevren  FYI

**Comment by douglas-reid** [comment]
All issues in this epic have been closed. I'm going to close this epic. We should open individual issues for testing and documentation gaps moving forward.
