### ISSUE TITLE
Allow individual api group and version for each config resource in Mixer

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4203]
- [ ] Mixer CRD client change, if needed to allow watch for different apiVersions.

- [ ] istioctl change to handle Mixer configs. Currently istioctl treates mixer configs as untyped "other" config and assume them all live in config.istio.io/v1alpha2.

**Comment by geeknoid** [comment]
Here's a doc describing our plans around proto package naming, including in particular Mixer's stuff. 

One change we want to do relative to what's in this doc is that we are fine calling the Mixer API "v1" instead of "v1beta"

**Comment by cmluciano** [comment]
@xiaolanz Currently Mixer crds are [hardcoded](https://github.com/istio/istio/blob/master/mixer/pkg/config/crd/store.go#L37-L38) to watch for all known types under config.istio.io/v1beta1. Most of the changes have been made for updating the APIs to the desired protos. 

We still need to make sure that the [hardcoded apiGroupVersion](https://github.com/istio/istio/blob/master/mixer/pkg/config/crd/store.go#L151) is a list , but I'm not sure how we safely start watching for new API groups without updating the CRDs in tandem. Is there a sequence of events that you are following for the Pilot updates?

**Comment by cmluciano** [comment]
cc @jmuk to be sure I am referring to the correct crd pieces of mixer

**Comment by cmluciano** [comment]
cc @mandarjog @ozevren

**Comment by cmluciano** [comment]
@mandarjog Do we want to switch to a static list instead of building at startup time? I know we were considering this for the adapters.

**Comment by cmluciano** [comment]
@geeknoid mentioned that @mandarjog has started working on his already and it should be assigned to him

**Comment by mandarjog** [comment]
@cmluciano I have not started work on this :-(  I don;t think I have band width for next two weeks.
It would be great if you can pick it up. Thanks.

**Comment by cmluciano** [comment]
@ozevren Are you still working on this?

**Comment by ozevren** [comment]
No (also, this is somewhat trivial to do in Galley, so I am thinking that we probably solve this there).

**Comment by cmluciano** [comment]
ok should we just close this?
