### ISSUE TITLE
Is there a way to forward the istio access logs collected by opentelemetry to prometheus?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42048]
Hi guys, I have a question and I hope someone can help me.

That's it, I'm learning about sending Envoy's access logging to opentelemetry today. I have configured it according to the configuration on the official website: https://istio.io/v1.13/docs/tasks/observability/logs/otel-provider/ up. My configuration is like this:

```
extensionProviders:
    -name: otel
      envoyOtelAls:
        service: opentelemetry-collector.istio-system.svc.cluster.local
        port: 4317
    defaultProviders:
      accessLogging:
      -envoy
      -otel
```
And I can see the log output in opentelemetry-collector:

```
2022-11-17T12:21:02.776Z DEBUG loggingexporter/logging_exporter.go:82 ResourceLog #0
Resource SchemaURL:
Resource labels:
     -> log_name: STRING(otel_envoy_accesslog)
     -> zone_name: STRING()
     -> cluster_name: STRING(productpage.bookinfo)
     -> node_name: STRING(sidecar~10.244.0.24~productpage-v1-7dd6c669bd-tg6m5.bookinfo~bookinfo.svc.cluster.local)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-11-17 12:21:01.586953 +0000 UTC
Severity:
Body: [2022-11-17T12:21:01.586Z] "GET /reviews/0 HTTP/1.1" 200 - via_upstream - "-" 0 375 95 94 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64 ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "1829f1ea-38bf-4c47-8bf6-984747d75cc0" "reviews:9080" "10.244.0.23:9080" outbound|9080in||foviews. .svc.cluster.local 10.244.0.24:38712 10.96.175.154:9080 10.244.0.24:39010 - default

```
Now, I have a few questions:
1. Can I forward these logs to prometheus? If so, how should I configure it?

2. Do I need to forward to prometheus? What is the difference between Envoy's access logging and the envoy logs already collected in Prometheus? ?

I hope someone who knows can answer these questions for me. thanks.

**Comment by zirain** [comment]
> Can I forward these logs to prometheus? If so, how should I configure it?

prometheus is an monitoring system, how will it handle accesslog?

normally, accesslogs will send to es/loki.

**Comment by zirain** [comment]
I'm wokring on istio with LGTM stack, but still WIP
you can see the demo configuration here: https://github.com/zirain/playground/tree/master/istio/lgtm-stack

**Comment by mark8s** [comment]
@zirain ok, thank you, your reply is very helpful to me~

**Comment by zirain** [comment]
I'd close this issue first, feel free to reopen.
