### ISSUE TITLE
Expose retry budget configuration via DestinationRule

### ISSUE THREAD

**Issue by quraynai** [istio/istio#42065]
**Describe the feature request**
We need `retry_budget` configurable via DestinationRule
https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers-thresholds-retrybudget

**Describe alternatives you've considered**
Due to we cannot configure this via DestinationRule at the moment. We were trying to configure it via EnvoyFilter instead.
The problem we found is Istio already has default circuitBreakers as below.
```
"circuit_breakers": {
  "thresholds": [
  {
    "max_connections": 4294967295,
    "max_pending_requests": 4294967295,
    "max_requests": 4294967295,
    "max_retries": 4294967295,
    "track_remaining": true
  }
  ]
},
```
With the operation that EnvoyFilter support for cluster at the moment we cannot replace default thresholds (ADD, REMOVE, MERGE)

The only way we can have retry_budget configured is we need to
- Remove default cluster
- Add cluster config manually

This is kinda troublesome due to we have to manage cluster config by ourselves and we cannot use DestinationRule as well

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by quraynai** [comment]
Used to saw someone raise this issue.
https://github.com/istio/istio/issues/27419

Not sure we support this yet.

**Comment by howardjohn** [comment]
lets track in https://github.com/istio/istio/issues/27419. thanks

**Comment by kaiburjack** [comment]
Looks like this is now supported with DestinationRule.
See:
- https://istio.io/latest/docs/reference/config/networking/destination-rule/#TrafficPolicy-retry_budget
- https://istio.io/latest/news/releases/1.27.x/announcing-1.27/change-notes/#traffic-management:~:text=Added%20support%20of%20retry%20budget%20in%20DestinationRule%20resources.
