### ISSUE TITLE
Update dnsRefreshRate default value in Istio doc

### ISSUE THREAD

**Issue by srmars** [istio/istio#42075]
In Global Mesh Options Istio document the default value for dnsRefreshRate is 5s but it the code, can see that its increase to 60s.

Default 5s in latest doc - https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
Default 60s in mesh.go - https://github.com/istio/istio/blob/master/pkg/config/mesh/mesh.go

Requesting to update dnsRefreshRate  to 60s in the latest document if this is a valid request.

**Comment by ymesika** [comment]
Thanks, It's a valid request.
Will you PR the istio.io or would you like me to do it?

**Comment by sri53** [comment]
@ymesika Created PR - https://github.com/istio/istio.io/pull/12265

**Comment by sri53** [comment]
@ymesika Kindly take this change forward.

**Comment by ymesika** [comment]
This specific part in the doc is auto-generated from the API proto definitions.
Modifying https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L304 will also update istio.io.

**Comment by ymesika** [comment]
Pushed a PR for this
