### ISSUE TITLE
mTLS  

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#42079]
When setting the client sidecar tls mode  to MUTUAL by destinationrule, I configure clientCertificate, caCertificates, and privateKey as private. However, the tls configuration of the server sidecar is still the default and ROOTCA certificates generated by SDS. In my opinion, root certificate verification fails as a result. Therefore, how to configure the security policy of the server-side sidecar?
The client sidecar configuration is as follows：
![image](https://user-images.githubusercontent.com/48784730/202946662-9e1fcdee-f32a-4434-8b06-0f9715919979.png)
The server sidecar configuration is as follows：
![image](https://user-images.githubusercontent.com/48784730/202946262-5cc0d50b-7a45-4bd2-84fc-53463fb40ccf.png)

**Comment by howardjohn** [comment]
You are looking at the listener. Dest rule configures cluster

**Comment by liuqi-sun** [comment]
> You are looking at the listener. Dest rule configures cluster

I see what you're saying.
I mean, the certificate in the Dest rule is generated by a third party ca, server sidecar authentication is still the ROOTCA certificate generated by istitio. This is not correct. The tls handshake failed. How do I configure the root certificate for server sidecar? PeerAuthentication CR cannot modify the root certificate but only the tls mode
