### ISSUE TITLE
where can I find the logs of istio-cni and how can I config the log level of istio-cni

### ISSUE THREAD

**Issue by jkhe-hub** [istio/istio#42077]
**Describe the feature request**
I'm trying to analysis an error related with istio-cni. I have tried `journalctl -xefu kubelet` but there isn't any istio-cni log such as what `log.Infof` , `fmt.Printf`and `log.Errorf` output. Where can I find the logs of istio-cni and how can I config the log level of istio-cni? 
Thank you.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ X ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ X ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ymesika** [comment]
When you enable Istio CNI there is a daemonset that launches an istio-cni pod on each node in your istio namespaces.
The `kubectl logs` of that pod will provide you the log.
If you wish to change the level you can do so with [component logging](https://istio.io/latest/docs/ops/diagnostic-tools/component-logging). The relevant scope here is `install`.
