### ISSUE TITLE
Kubeflow_istio_ issue

### ISSUE THREAD

**Issue by vamshikrishna9999** [istio/istio#42082]
### Bug Description

I was trying to install kubeflow version v1.5.0 on OpenShift cluster. I have deployed all the components of Kubeflow then pods should be in running state so some're up and when it comes to Istio-init is not able to running state due to error Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1669007447751581007.txt771627809, exit status 2.

### Version

```prose
kubeflow version: v1.5.0
Kubernetes platform: OpenShift
version:4.10
```

### Additional Information

2022-11-21T05:10:47.751488Z info Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=
2022-11-21T05:10:47.751537Z info Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
EXCLUDE_INTERFACES=
2022-11-21T05:10:47.751753Z info Writing following contents to rules file: /tmp/iptables-rules-1669007447751581007.txt771627809
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT

**Comment by ymesika** [comment]
Did you configure the OpenShift according to: https://istio.io/latest/docs/setup/platform-setup/openshift/

**Comment by vamshikrishna9999** [comment]
Yes I configured the same and still pods are crashing due to Istio sidecar.

**Comment by vamshikrishna9999** [comment]
Still it is not resloved...
can anyone suggest how to resolve this issue ?
