### ISSUE TITLE
some questions for DeltaAggregatedResources

### ISSUE THREAD

**Issue by yanbuduo** [istio/istio#42109]
> hello, i try to send a delta grpc request to istiod in my program, but  got response with full rusources, and the Resource.Version was not set in response, this confuses me....    How to use this interface(DeltaAggregatedResources ) correctly?

> istio version:
> client version: 1.14.1
> control plane version: 1.14.1
> data plane version: 1.14.1 (1 proxies),  (1 proxies)

> **---test code:**
> func send() {
>           ................
>           .................
>          if c.grpcConn, err = nets.GrpcConnect(ads.Clusters[0].Address[0]); err != nil {
> 			return fmt.Errorf("ads grpc connect failed, %s", err)
> 		}
> 	c.client = service_discovery_v3.NewAggregatedDiscoveryServiceClient(c.grpcConn)
> 	// DeltaAggregatedResources() is supported from istio-1.12.x
> 	c.stream, err = c.client.DeltaAggregatedResources(c.ctx)
> 	if err != nil {
> 		return fmt.Errorf("ads StreamAggregatedResources failed, %s", err)
> 	}
> 	if err = c.stream.Send(newDeltaAdsRequest(resource_v3.ClusterType, nil)); err != nil {
> 		return fmt.Errorf("ads subscribe failed, %s", err)
> 	}
> }
> 
> 
> func newDeltaAdsRequest(typeUrl string, names []string) *service_discovery_v3.DeltaDiscoveryRequest {
> 	var subNames [] string
> 	subNames = append(subNames, "outbound|9080|v1|reviews.default.svc.cluster.local")
> 	var resourcesVersion = make(map[string]string)
> 	if names != nil {
> 		for _, r := range names {
> 			resourcesVersion[r] = "v0"
> 		}
> 	}
> 	return &service_discovery_v3.DeltaDiscoveryRequest{
> 		TypeUrl:                 typeUrl,
> 		**ResourceNamesSubscribe:  subNames,** ==>sub one cluster resource 
> 		InitialResourceVersions: resourcesVersion,
> 		ResponseNonce:           "",
> 		ErrorDetail:             nil,
> 		Node:                    config.getNode(),
> 	}
> }
> 

> **there some logs in istiod, receive Delta Request:**
> 
> 
> 2022-11-22T08:44:30.938262Z	debug	delta	Unauthenticated XDS: xxxxx:46142
> 2022-11-22T08:44:30.939000Z	warn	model	Istio Version is not found in metadata for default, which may have undesirable side effects
> 2022-11-22T08:44:30.939153Z	info	delta	ADS: new delta connection for node:default-1038
> 2022-11-22T08:44:30.939172Z	debug	delta	ADS: got Delta Request for: type.googleapis.com/envoy.config.cluster.v3.Cluster
> 2022-11-22T08:44:30.939183Z	debug	delta	ADS:CDS: INIT/RECONNECT default-1038 
> 2022-11-22T08:44:30.939866Z	info	delta	CDS: PUSH request for node:default resources:29 size:29.2kB cached:26/26 filtered:0 nonce:lgQ5NdgYDgQ=66fb5050-21c6-405c-8495-4d12504f20b0 version:2022-11-22T08:42:16Z/23
> 2022-11-22T08:44:30.956827Z	debug	delta	ADS: got Delta Request for: type.googleapis.com/envoy.config.cluster.v3.Cluster
> 2022-11-22T08:44:30.956871Z	debug	delta	ADS:CDS: ACK  default-1038 lgQ5NdgYDgQ=66fb5050-21c6-405c-8495-4d12504f20b0
>

**Comment by yanbuduo** [comment]
the DeltaDiscoveryRequest was set like this, but get a full resource 

return &service_discovery_v3.DeltaDiscoveryRequest{
		TypeUrl:                 typeUrl,
		ResourceNamesSubscribe:  subNames, 
		InitialResourceVersions: resourcesVersion,
		ResponseNonce:           "",
		ErrorDetail:             nil,
		Node:                    config.getNode(),
	}

**Comment by howardjohn** [comment]
Istio doesn't currently support non wildcard requests for CDS and LDS as envoy doesn't make these. Qhatbis the use case
