### ISSUE TITLE
Istio Operator pod keeps restarting after installation

### ISSUE THREAD

**Issue by benjaminxie** [istio/istio#42126]
### Bug Description

I'm installing Istio via `$ istioctl operator init` and then applying the following yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
```
The issue is that there are no resources deployed to the istio-system namespace. Looking at the istio-_operator_ namespace, I see that the pod for the istio-operator deployment keeps restarting. Here is a copy of its logs
```
2022-11-22T17:51:24.446771Z     info    ControlZ available at 127.0.0.1:9876
2022-11-22T17:51:24.446849Z     info    Leader election cm: istio-operator-lock
2022-11-22T17:51:24.543633Z     info    Creating operator metrics exporter
2022-11-22T17:51:24.543806Z     info    Registering Components.
2022-11-22T17:51:24.544500Z     info    installer       Adding controller for IstioOperator.
2022-11-22T17:51:24.544613Z     info    installer       Controller added
2022-11-22T17:51:24.544633Z     info    Starting the Cmd.
2022-11-22T17:51:24.635750Z     info    klog    attempting to acquire leader lease istio-operator/istio-operator-lock...
2022-11-22T17:51:46.507624Z     info    klog    successfully acquired lease istio-operator/istio-operator-lock
2022-11-22T17:53:46.743599Z     fatal   Manager exited non-zero: failed to wait for istiocontrolplane-controller caches to sync: timed out waiting for cache to be synced
```

I see that #40376 has similar logs but unlike that issue I am not upgrading Istio. **Edit:** Also, I am installing a later version.

### Version

```prose
$ istioctl version
no running Istio pods in "istio-system"
1.14.0

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.25.2
```

### Additional Information

$ istioctl bug-report

Target cluster context: connect-dr

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-11-22 17:56:48.691475836 +0000 UTC

Cluster endpoint: https://connect-dr-connect-dr-b5198e-503accf6.hcp.southcentralus.azmk8s.io:443
CLI version:
version.BuildInfo{Version:"1.14.0", GitRevision:"3aa487bb6ec8cb8bb7c736423f3a4857d1a81263", GolangVersion:"go1.18.2", BuildStatus:"Clean", GitTag:"1.14.0"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:

Fetching proxy logs for the following containers:

istio-operator/istio-operator/istio-operator-556444dfb5-zfkcl/istio-operator

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-operator istio-injection=enabled' to enable it, or 'kubectl label namespace istio-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /home/connect-dr/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by sereneshikari** [comment]
@benjaminxie , I see that you're trying to use Istio `1.14.0` on a `1.25` Kubernetes cluster and according to the [release notes](https://istio.io/latest/news/releases/1.14.x/announcing-1.14/):
> Istio `1.14.0` is officially supported on Kubernetes versions `1.21` to `1.24`.

@zirain, could this be the reason for the error that we're seeing?

**Comment by bhaskar-reddy** [comment]
I too am seeing same issue, but with istio v1.15.3 on kubernetes v1.20.9. According to [Istio official support](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases) document: 

> `Supported Kubernetes Versions | 1.22, 1.23, 1.24, 1.25`
> `Tested, but not supported | 1.16, 1.17, 1.18, 1.19, 1.20, 1.21`

The istio-operator pod in istio-operator namespace keeps restarting with status CrashLoopBackOff. Logs for istio-operator show:
> Trace[1209089971]: "DeltaFIFO Pop Process" ID:<namespace-1>/<deployment-1>,Depth:896,Reason:slow event handlers blocking the queue (06-Dec-2022 02:51:33.597) (total time: 100ms):
> Trace[1333856946]: "DeltaFIFO Pop Process" ID:<namespace-2>/<deployment-2>,Depth:5032,Reason:slow event handlers blocking the queue (06-Dec-2022 02:52:24.003) (total time: 193ms):

before crashing with below message

> Manager exited non-zero: failed to wait for istiocontrolplane-controller caches to sync: timed out waiting for cache to be synced

Wondering if there is an alternate setting to be able to still go ahead with the installation.

**Comment by gbvikas** [comment]
facing similar issue with GKE 1.25 and Istio operator 1.13.0

**Comment by gbvikas** [comment]
Works fine with GKE 1.24 and Istio operator 1.13.0
