### ISSUE TITLE
Configuration changes require Istio GW restart

### ISSUE THREAD

**Issue by videlov** [istio/istio#42133]
**Describe the feature request**

Currently changing mesh configuration (e.g. `numTrustedProxies` in `gatewayTopology`) does not take effect in a running Istio GW proxy. See:
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#example-using-x-forwarded-for-capability-with-httpbin

After step 1 we need to restart all Istio gateways. This is quite inconvenient in a production environment.
The reason is that the configuration is read just once on a proxy start:
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/app/cmd.go#L113

Annotation approach do not work at all, also with a restart:
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-network-topologies

Could you please provide an automated way for this configuration settings to be applied without restarting the GW pod. The `ConfigMap` is already mounted and up-to-date on the filesystem:
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L237

**Describe alternatives you've considered**
When we rollout mesh configuration changes we need to tell the customer to manually restart Istio ingress, which is very unusual and inconvenient.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Yes, this is documented https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

`Note: fields in ProxyConfig are not dynamically configured; changes will require restart of workloads to take effect.

`
