### ISSUE TITLE
Is it possible to use some more generalized names for  Istio to support Proxyless mode?

### ISSUE THREAD

**Issue by chickenlj** [istio/istio#42131]
Many names are bonded to `grpc`, which I think is not general enough for there are many data plane components that might want to support Proxyless Mesh.

For example, would `inject.istio.io/templates: proxyless-agent` be better than `inject.istio.io/templates: grpc-agent`?

**Comment by hzxuzhonghu** [comment]
You can specify arbitrary name for `inject.istio.io/templates`, it is not enum

**Comment by robberphex** [comment]
I agree that proxyless should have a vendor-neutral template name.

We could add `inject.istio.io/templates: proxyless` to istio, and let other workload read/subscribe with their method, built-in sdk, agent, etc.

@hzxuzhonghu What do you think?

**Comment by hzxuzhonghu** [comment]
I am not sure i understand what does sdk want to get from template. And it must read from template?
