### ISSUE TITLE
`ProxyConfig` should support everything that pod annotation `proxy.istio.io/config` supports

### ISSUE THREAD

**Issue by yogeshgadge** [istio/istio#42138]
Ran into this issue where I wanted to add traceId to istio-proxy sidecar logs where I would affect the logFormat to utilize `x-b3-traceId` as an example. Our enterprise teams are a bit reluctant to this change as it is a mesh wide change and it would affect other teams (and workloads in their namespaces).

Another example is the defaulting a certain CPU/Memory request limits by workload identifying patterns within a namespace.

Today it leaves me with only 2 options:-

1) Global MeshConfig: 
Making this change enterprise wide with meshConfig - currently not an option for us as it affects many teams. And what one team wants for the `istio-proxy` to do although logging traceId should be no brainer. However they are not able to add/remove fields but rather need to do a full copy of the default log formats and add/remove to that.

2) Down to the pod annotation `proxy.istio.io/config` option: 
Add `proxy.istio.io/config` and other annotations to every pod specs which is really ugly

`        
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "30m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
        readiness.status.sidecar.istio.io/initialDelaySeconds: "125"
`

I cannot wait to make it more ugly by adding the big long access `logFormat` :)

** Proposal/request/question**:  

Have ProxyConfig support these configuration because it is just that "proxy" "config". Let things merge just as they do like `concurrency` etc.

Why can't [proxy-config](https://istio.io/latest/docs/reference/config/networking/proxy-config/#ProxyConfig) support everything that `proxy.istio.io/config` ?

**Alternative**

Ugly alternatives.
 
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Currently, [ProxyConfig](https://istio.io/latest/docs/reference/config/networking/proxy-config/#ProxyConfig) is applied during bootstrap.

**Comment by yogeshgadge** [comment]
So mesh needs to be restarted to get its effects even if is in another namespace?

I guess how or rather when would a global mesh configs gets merged with a proxy config in a different namespace for a the istio-proxy side car in that namespace to gets the merged config.
