### ISSUE TITLE
multicluster/multi-primary istiod error could not get cluster kube client

### ISSUE THREAD

**Issue by realabja** [istio/istio#42144]
### Bug Description

I have followed instruction and created the cacert and istio-remote-secret and installed istiooperator. but taking a a look at istiod logs in cluster1. I see the error below

`error    ads    Failed to authenticate client from : Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster1's kube client
`

I tested the remote-secrets and could read from api server.
Is this error means cacerts are not configured correctly? Is there anything else that could be misconfigured other than that?

### Version

```prose
istioctl version --context=cluster1
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.15.3 (3 proxies), 1.16.0 (52 proxies)
istioctl version --context=cluster2
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (5 proxies)
```

**Comment by zirain** [comment]
[please check you have ](https://istio.io/latest/docs/setup/install/multicluster/primary-remote/#attach-cluster2-as-a-remote-cluster-of-cluster1)

**Comment by realabja** [comment]
Hi all, I found out that using kubenet and on top of an azure vnet does not count as same network. I used multicluster mode with multiple networks and it worked
