### ISSUE TITLE
circleci: history of a specific build ?

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4214]
Can you document in the excellent [wiki](https://github.com/istio/istio/wiki/Working-with-CircleCI) or elsewhere to your choosing how in the ui do I find the history of a specific build (e.g. e2e-simple or any other really)

In prow it's faily easy and it's very useful to try to find when a given build started to fail etc

So far I navigate to https://circleci.com/gh/istio/istio/tree/master
and then use browser search and page down and it's quite slow and cumbersome with all the builds mixed up

cc @hklai

**Comment by costinm** [comment]
CircleCI has an API, and the build results can be updated. 

The test and release team will need to prioritize this work, and find someone to work on it.

**Comment by hklai** [comment]
I suppose https://k8s-testgrid.appspot.com/istio-daily had solved this need. =)
