### ISSUE TITLE
correct wasm cache file expiry policy

### ISSUE THREAD

**Issue by johnlanni** [istio/istio#42154]
### Bug Description

The wasm cache file will be marked as stale and deleted if it has not been accessed for the default 24 hours, even if it is still in use.

https://github.com/istio/istio/blob/ec750d5d1e7127bb69feca899b60eb1d2071023e/pkg/wasm/options.go#L25

https://github.com/istio/istio/blob/47f0678388b1bb6c3f33c4eb6d9394c37192fbd1/pkg/wasm/cache.go#L402-L442

If no ECDS request triggers access for 24 hours, and then istio pushes a new LDS response to envoy, envoy will send NACK with this message:

```text
gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /var/lib/istio/data/xxxx.wasm
```

### Version

```prose
istio version: latest
```

**Comment by zirain** [comment]
cc @ingwonsong

**Comment by johnlanni** [comment]
https://github.com/istio/istio/pull/42167/files#diff-b4b9abc466fa6e7cad54037be486711eda1582c289c1dcbdd13aebd776442f5cL420

@zirain Why not check the module used here?

**Comment by zirain** [comment]
if a module removed, but then bring back in 24h?

**Comment by johnlanni** [comment]
> istio/pkg/wasm/cache.go

https://github.com/istio/istio/blob/b53eff4eb810b5739143e848c25aa0927cfadb5f/pkg/wasm/cache.go#L60

I'm just confused that this usingModules field is not used when purging the cache, how does it keep the cache in use?

**Comment by zirain** [comment]
seems I made a mistake, forgot to commit local changes

**Comment by zirain** [comment]
@johnlanni we need figure out one way to get all using modules, before https://github.com/envoyproxy/envoy/issues/20086 fixed, seems the only is get from pilot debug endpoint `/debug/config_dump?type=ecdsz&proxyID=<podname.namespace>`

**Comment by johnlanni** [comment]
> @johnlanni we need figure out one way to get all using modules, before [envoyproxy/envoy#20086](https://github.com/envoyproxy/envoy/issues/20086) fixed, seems the only is get from pilot debug endpoint `/debug/config_dump?type=ecdsz&proxyID=<podname.namespace>`

or maybe we can parse it from the LDS response?

**Comment by zirain** [comment]
> > @johnlanni we need figure out one way to get all using modules, before [envoyproxy/envoy#20086](https://github.com/envoyproxy/envoy/issues/20086) fixed, seems the only is get from pilot debug endpoint `/debug/config_dump?type=ecdsz&proxyID=<podname.namespace>`
> 
> or maybe we can parse it from the LDS response?

IIRC, LDS response only contains ecds resource name.

**Comment by ingwonsong** [comment]
(Sorry for super late response)

Yes. LDS response only contains ECDS reference (resource name).

**Comment by johnlanni** [comment]
Maybe we can use resource name as the cache key?

**Comment by johnlanni** [comment]
Or create a reference relationship between the resource name and the cache. Because we can only find out which modules are in use from the response of LDS.

**Comment by zirain** [comment]
FYI: https://github.com/envoyproxy/envoy/pull/23902 is merged

**Comment by ingwonsong** [comment]
@johnlanni 
Did you encounter this situation in real cluster?
In normal setting, Istiod will disconnect ADS connection for each 30 min, and reconnect.
So, ECDS will be delivered again at least, for each 30 min.

Is there another path reaching to the error?

**Comment by ingwonsong** [comment]
@zirain 
How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer.
Then, if there is no ECDS, no purging will happen.

**Comment by zirain** [comment]
> @zirain How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer. Then, if there is no ECDS, no purging will happen.

unlike LDS, a new ECDS do not contains all modules every time.

IMO, we need https://github.com/envoyproxy/envoy/pull/23902 become stable, WDYT?

**Comment by johnlanni** [comment]
> @johnlanni Did you encounter this situation in real cluster? In normal setting, Istiod will disconnect ADS connection for each 30 min, and reconnect. So, ECDS will be delivered again at least, for each 30 min.
> 
> Is there another path reaching to the error?

Yes, we encounter this in real cluster, It seems that the reconnection mechanism doesn't work. Can you tell me which parameter or code logic controls this mechanism?

**Comment by johnlanni** [comment]
> > @zirain How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer. Then, if there is no ECDS, no purging will happen.
> 
> unlike LDS, a new ECDS do not contains all modules every time.
> 

Could you tell me when this will happen? Did you mean the delta-xDS?

**Comment by zirain** [comment]
> 

yes, demo output can be found [here](https://github.com/envoyproxy/envoy/issues/20086#issuecomment-1333086917), still contains some issue.

**Comment by zirain** [comment]
> > > @zirain How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer. Then, if there is no ECDS, no purging will happen.
> > 
> > 
> > unlike LDS, a new ECDS do not contains all modules every time.
> 
> Could you tell me when this will happen? Did you mean the delta-xDS?

IIRC, LDS is kind of Stow, if a listener contains ecds,  a single ECDS request will send to xds server.

**Comment by ingwonsong** [comment]
> > > @zirain How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer. Then, if there is no ECDS, no purging will happen.
> > 
> > 
> > unlike LDS, a new ECDS do not contains all modules every time.
> 
> Could you tell me when this will happen? Did you mean the delta-xDS?



> > > > @zirain How about purging unused wasm binaries when a new ECDS comes, instead of triggering it by timer. Then, if there is no ECDS, no purging will happen.
> > > 
> > > 
> > > unlike LDS, a new ECDS do not contains all modules every time.
> > 
> > 
> > Could you tell me when this will happen? Did you mean the delta-xDS?
> 
> IIRC, LDS is kind of Stow, if a listener contains ecds, a single ECDS request will send to xds server.

Yes. ECDS is similar with RDS and EDS in SotW xDS. They are not deleted in Envoy even if some of entries are not shown in a push. It means that Istiod can send just a portion of ECDS. So, some call it "incremental".

**Comment by zirain** [comment]
> > @johnlanni Did you encounter this situation in real cluster? In normal setting, Istiod will disconnect ADS connection for each 30 min, and reconnect. So, ECDS will be delivered again at least, for each 30 min.
> > Is there another path reaching to the error?
> 
> Yes, we encounter this in real cluster, It seems that the reconnection mechanism doesn't work. Can you tell me which parameter or code logic controls this mechanism?

cc @ingwonsong , we need double check this.

**Comment by johnlanni** [comment]
BTW, the current implementation seems to push all resources in one ECDS response.

https://github.com/istio/istio/blob/32afc27ea91ef68e4e5f0ee3dd47d0aedfba35f1/pilot/pkg/networking/core/v1alpha3/extension_config_builder.go#L27

**Comment by ingwonsong** [comment]
> cc @ingwonsong , we need double check this.
> if ECDS is cached, there's no ECDS request after reconnect to xds server?

IIRC, no. ECDS request will be triggered by references in LDS.

**Comment by ingwonsong** [comment]
@johnlanni can you provide your configuration regarding WasmPlugin API?

**Comment by ingwonsong** [comment]
@kyessenov Hi Kuat, do you have any insight?

**Comment by kyessenov** [comment]
ECDS is a separate stream and new LDS will not trigger ECDS update if the resource is already loaded. So yeah, I can see that there's a problem with cache expiry in the agent.

ECDS subscriptions are owned by listeners, so you'd need to query to find if they are in use. Alternatively, just don't use files and inline the bytes (but that will increase memory use).

**Comment by zirain** [comment]
https://github.com/envoyproxy/envoy/pull/23902 can be used for v1.17, still need a mechanism for v1.16

**Comment by johnlanni** [comment]
> ECDS is a separate stream and new LDS will not trigger ECDS update if the resource is already loaded. So yeah, I can see that there's a problem with cache expiry in the agent.
> 
> ECDS subscriptions are owned by listeners, so you'd need to query to find if they are in use. Alternatively, just don't use files and inline the bytes (but that will increase memory use).

+1 cc @ingwonsong 

I would like to know which option controls the behavior of `Istiod disconnect ADS connection for each 30 min`, could you tell me?

**Comment by zirain** [comment]
![image](https://user-images.githubusercontent.com/4354057/205622724-739f10ec-753c-4f35-9211-18e5b79517d1.png)

**Comment by johnlanni** [comment]
@zirain  Thanks, I confirmed that this parameter is not set in my deployment.

**Comment by ingwonsong** [comment]
@zirain I think if we check the expiry on each ECDS push instead of a timer event, we can avoid this situation if the Wasm is configured with WasmPlugin API (not EnvoyFilter). It is because that current implementation pushes all the wasm configurations, if they are configured by WasmPlugin API, as @johnlanni mentioned.

https://github.com/istio/istio/blob/32afc27ea91ef68e4e5f0ee3dd47d0aedfba35f1/pilot/pkg/networking/core/v1alpha3/extension_config_builder.go#L32

WDYT?

**Comment by kyessenov** [comment]
You can also try xDS TTL here to maintain "freshness" of resources. This is a new use case for TTL so would be good to test it well first.

**Comment by ingwonsong** [comment]
@kyessenov Ah.. that's good idea.

**Comment by zirain** [comment]
> If no ECDS request triggers access for 24 hours, and then istio pushes a new LDS response to envoy, envoy will send NACK

cc @ingwonsong , the question is no ECDS before wasm file removed.

**Comment by ingwonsong** [comment]
Yes. 
If TTL is shorter than 24h, Envoy will stop to use the previous Wasm configuration, and will make an ECDS request.
So, ECDS response will be delivered again before purging always.

**Comment by ingwonsong** [comment]
Of course, this is just theoretical. we need to do some experiments.

**Comment by zirain** [comment]
@ingwonsong @johnlanni 
FYI, https://github.com/istio/istio/pull/42365 is merged, we can get all ecds configurations by running `istioctl pc ecds`

**Comment by ingwonsong** [comment]
> ECDS is a separate stream and new LDS will not trigger ECDS update if the resource is already loaded. So yeah, I can see that there's a problem with cache expiry in the agent.

QQ: @kyessenov when an ADS connection is re-established, should Envoy need to make a ECDS request again even though the resource is already loaded? Without that, Envoy will not get any pushes from xDS server even if there are some further updates.

**Comment by ingwonsong** [comment]
I made several experiments and ECDS was sent to Istiod always when ADS connection is re-established.
Istio Agent successfully updated the last access time, so that Wasm module was not purged.

So, I think we may need to suspect the other causes.

@johnlanni Can you replay the error somehow?

**Comment by johnlanni** [comment]
> @zirain Thanks, I confirmed that this parameter is not set in my deployment.

@ingwonsong Yes, the problem occurs only when the parameter `keepaliveMaxServerConnectionAge` is not set. But I think this caching mechanism should not depend on this parameter.

**Comment by ingwonsong** [comment]
Ah.. yes. I missed your comment.
If you don't set `keepaliveMaxServerConnectionAge`, it will be infinity IIRC.

**Comment by zirain** [comment]
not stale

**Comment by zirain** [comment]
not stale
