### ISSUE TITLE
rootNamespace is set to null in helm install

### ISSUE THREAD

**Issue by fatedier** [istio/istio#42155]
### Bug Description

![image](https://user-images.githubusercontent.com/7346661/203900815-18b738ab-698a-4cb0-9184-3cf80e6c002c.png)

https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/configmap.yaml#L10

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/7346661/203901003-f61fe4bb-da81-432f-8afc-18c4b56dc9c5.png">

When I upgrade my helm version, I found that rootNamespace changed from `istio-system` to `null`. Is that expected?

It's `null` in values.yaml and helm doesn't render it to `.Values.global.istioNamesapce`.

### Version

```prose
istio v1.16.0
helm v3.10.2
```

**Comment by fatedier** [comment]
Releated helm issue: https://github.com/helm/helm/issues/9587

**Comment by fatedier** [comment]
Default is `istio-system`. What if `.Value.global.istioNamespace` is not `istio-system`?

**Comment by howardjohn** [comment]
Ah didn't realize that was broken too. thanks
