### ISSUE TITLE
Direct communication between pods on the same node fails when using ambient

### ISSUE THREAD

**Issue by jkhe-hub** [istio/istio#42163]
### Bug Description

When using the ambient mode, the following error occurs on communication between pods on the same node, and the communication between pods between different nodes has not yet found problems.
```sh
# sh in pod which ip is 10.244.0.3
$ curl http://10.244.0.2
curl: (56) Recv failure: Connection reset by peer
```
The following is the log of the ztunnel pod on the node, but I did not find any exceptions
```
[2022-11-25T12:04:28.870Z] "- - -" 0 UF,URX - - "-" 0 0 2002 - "-" "-" "-" "-" "10.244.0.2:15088" outbound_pod_local_tunnel_clus_spiffe://cluster.local/ns/default/sa/default - 10.244.0.2:80 10.244.0.3:50834 - - outbound capture listener
[2022-11-25T12:04:28.870Z] "- - -" 0 UF,URX - - "-" 0 0 2002 - "-" "-" "-" "-" "10.244.0.2:15088" outbound_pod_local_tunnel_clus_spiffe://cluster.local/ns/default/sa/default - 10.244.0.2:80 10.244.0.3:50834 - - capture outbound pod (no waypoint proxy)
```
The target pod(10.244.0.2) didn't receive the request.

I know the information above may be too little to solve this bug, but I don't know what other information to provide. So if you need me to provide more logs or information, please just reply.

### Version

```prose
$ ./istioctl version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (5 proxies)

$ kubectl version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.4
```

**Comment by jk-he** [comment]
I used `tcpdump -i eth0` to capture packets in the ztunnel pod of this node, but I did not find the processed packets sent by ztunnel. Is this a problem ztunnel proxy or configuration xds distributed?

**Comment by linsun** [comment]
Can you pls retry using the new ztunnel?

**Comment by howardjohn** [comment]
Ithink this is obsolete now, please re-open if you see it with new ztunnel
