### ISSUE TITLE
CR is sometime ignored when controller is deployed with enhanced resource scoping feature

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#42173]
### Bug Description

Hello everyone,
While I was tinkering with the new enhanced resource scoping feature of Istio 1.16.0 I noticed one issue.
I suspect that there is a race condition which leads to some custom resources to be ignored under certain circumstances.
So far, I managed to pinpoint the issue to this scenario:
1. Create istio-system namespace without any label
2. Do in parallel:
    - Deploy of Istio controller with ENABLE_ENHANCED_RESOURCE_SCOPING=true in istio-system. Use discovery selector match-labels on "test=true"
    - Deploy of Istio Ingress GW in istio-system
    - Deploy of EF on listener to add socket options to GW listener (I have an EnvoyFilter but I presume it can be reproduced with other CR too).
    - Label istio-system namespace with the same selector we use in Istio discovery selector config ("test=true")
3. After the parallel steps have ended, deploy a GW CR just to trigger the creation of the listeners in proxies.
4. If you are unlucky you end up with a deployment where the EF CR was ignored. ingressgw proxy-config did not receive socket_options patch.
I have verified that:
    - Restarting the IngressGW deployment does not fix the issue.
    - Restarting the controller will fix the issue and the socket options patch will now be applied 
correctly to the gw listener.
    - Triggering a full-push does not fix the issue.
    -  Removing and reapplying the CR fixes the issue

Controller log:  [log_controller2.log](https://github.com/istio/istio/files/10104613/log_controller2.log)

Keep in mind that if the namespace is already labelled before the deployment took place or if the enhanced resource scoping feature is disabled then the issue will not be there.

I'm trying to come up with some easy steps/script to reproduce it, but it is taking some time. I will add the steps asap.
In the meantime, I'm opening this issue to see if someone already has any idea on what is going on here.

### Version

```prose
client version: 1.15.3
control plane version: 1.16
data plane version: 1.16.0 (1 proxies)

kubectl version --short
Client Version: v1.19.2
Server Version: v1.25.2
```

**Comment by kfaseela** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I can see after L606, you deleted and reapply the envoyfilter again, it did trigger full push.

But before that, i donot see any log for this envoyfilter like L607(Handle event delete for configuration networking.istio.io/v1alpha3/EnvoyFilter/istio-system/istio-ingressgateway-keepalive-options), not sure why.

**Comment by dddddai** [comment]
I suspect it's because the discovery controller [does not trigger events for CRs](https://github.com/istio/istio/blob/1.16.0/pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go#L134-L135)?

> I can see after L606, you deleted and reapply the envoyfilter again, it did trigger full push.

Maybe the full push is triggered by other resources that does not affect LDS(i.e. `ldsNeesPush=false`)

**Comment by hzxuzhonghu** [comment]
Yeah Right, before the envoyfilter was filterred out, so no log about it at all.

**Comment by hzxuzhonghu** [comment]
I have know the root cause, when the discovery selector changed or the namespace changed, it only trigger full push with Service updated, so we do not update envoyfilter index.

**Comment by LithiumSR** [comment]
Thank you both for the solution.
I have used a build with the proposed fix included and the issue is no longer reproducible 👍

**Comment by hzxuzhonghu** [comment]
good to know

**Comment by kfaseela** [comment]
Thanks a lot @hzxuzhonghu :)
