### ISSUE TITLE
isto kube-inject breaking k8s.svc

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio#422]
After injecting via istioctl kube-inject, the existing application which was using kube api internally is getting unable to to connect to `10.0.1.1:443` ( which is the `default.svc`), all inbound/outbound urls are routed via proxy. 

The same application works without this error before kubernetes-inject. 

Why is this behaviour ?

**Comment by kalantar** [comment]
I am also seeing this. My application is written in _go_ and has the following dependency in our `glide.yaml`:

    - package: k8s.io/client-go
      version: 1.5.1
      subpackages:
      - 1.5/kubernetes
      - 1.5/pkg/api
      - 1.5/pkg/api/resource
      - 1.5/pkg/api/unversioned
      - 1.5/pkg/api/v1
      - 1.5/pkg/apis/batch/v1
      - 1.5/pkg/apis/extensions/v1beta1
      - 1.5/pkg/labels
      - 1.5/pkg/util/intstr
      - 1.5/rest

**Comment by frankbu** [comment]
This may be a pod startup order/timing issue that should be dealt with in the app.
See related discussion here: https://groups.google.com/forum/#!topic/istio-users/euWH-cieiOc

**Comment by ldemailly** [comment]
the bigger issue here is auth/mtls which is probably why you can't talk to k8s api server if you turned auth on. Closing for  https://github.com/istio/pilot/issues/1015
