### ISSUE TITLE
Add an integration test for authz policy port match using waypoint proxy

### ISSUE THREAD

**Issue by linsun** [istio/istio#42208]
### Bug Description

Following up https://github.com/istio/istio/issues/41204 and https://github.com/istio/istio/pull/41491, we need an integration test to automate the scenario.

### Version

```prose
master
```

**Comment by dhawton** [comment]
Blocked by #42243 due to the echo services utilizing port 80

**Comment by linsun** [comment]
Holding off on this as it could be solved by #42033

**Comment by dhawton** [comment]
Cannot be solved by #42033 as we're not sandwiching. Original implementation is being reverted. Conversation: https://github.com/istio/istio/pull/42768#discussion_r1067580705

**Comment by SkyfireFrancisZ** [comment]
plan to re-work the integration tests to only test L4, instead of going through ingress gateway

**Comment by SkyfireFrancisZ** [comment]
CI failing, running test locally passes.  Will attempt to turn on debug logging in CI.

**Comment by dhawton** [comment]
@howardjohn and I have both run the integration tests locally and are both unable to establish the reason they fail in prow but not when we run them locally (tested within Kind built with `./prow/integ-suite-kind.sh` and against a GKE cluster). After discussing with @linsun, we decided to split the PRs.
