### ISSUE TITLE
Allow customisation of webhook port

### ISSUE THREAD

**Issue by stevehipwell** [istio/istio#42217]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I'd like to be able to customise the webhook port exposed by Istiod, more specifically I'd like to be able to do this via the Istio operator.

**Describe alternatives you've considered**
n/a

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
There is a common pattern to run all webhooks on port `10250` which enables a simpler security posture and this is what we're trying to do here.

**Comment by stevehipwell** [comment]
Could one of the Istio team take a look at this and maybe suggest the changes required? I assume it'd need a change to the Istiod chart to enable customisation and then a change to the operator CRD to support passing in the new value.

**Comment by keithmattix** [comment]
Not  stale

**Comment by hanxiaop** [comment]
I think this can be done with https://istio.io/latest/docs/setup/additional-setup/customize-installation/. You can specify the Istiod args for which port to be exposed for webhook injection and validation, and revise the service as well.

**Comment by stevehipwell** [comment]
@hanxiaop could you be more specific as I've not found anything to cover this in the docs and based on the Istiod Helm chart the port is static.

https://github.com/istio/istio/blob/737a52d7fe28ab5137440590d17289c104c79693/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L118

**Comment by hanxiaop** [comment]
> @hanxiaop could you be more specific as I've not found anything to cover this in the docs and based on the Istiod Helm chart the port is static.
> 
> https://github.com/istio/istio/blob/737a52d7fe28ab5137440590d17289c104c79693/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L118

Yes it's static in the chart, but can be overlaied during the installation. You can apply a patch which changes `15017` to `10250`. Also you need to input one more arg to the pilot `--httpsAddr=:10250` to specify the port for injection.
