### ISSUE TITLE
Enable extensibility into waypoint proxy

### ISSUE THREAD

**Issue by linsun** [istio/istio#42223]
**Describe the feature request**

In Istio sidecar, we have EnvoyFilters to enable users to perform extensibility when Istio doesn't provide API to do certain things, for example, rate limiting, or proxy protocol or access log format for a given workload etc.

We'll need similar extensibility for the waypoint proxy.  One possible idea is to enable users to apply envoyfilter for waypoint proxy.

Chatting with @stevenctl earlier, waypoint proxy may already have some support for envoyfilter?  Would appreciate you adding some context here.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by stevenctl** [comment]
The existing implementation re-uses a lot of our existing xDS generation.

I think they'd be more unstable than they already are though..

**Comment by linsun** [comment]
Note: there is also #42337 which is allowing users to easily extend waypoint using Wasm.  This WI is more for advanced users/vendors who don't necessarily using Wasm or need to tweak some envoy configs.

**Comment by GregHanson** [comment]
Have verified several different EnvoyFilters are still behaving as expected.  Assuming producer only waypoint proxy, the main difference is the old style `workloadSelector`'s no longer works:
```
  workloadSelector:
    labels:
      app: helloworld
```
and has to now use the waypoint proxy label as selector
```
  workloadSelector:
    labels:
      ambient-proxy: helloworld-waypoint-proxy
```
`context: ANY` as well as `context: SIDECAR_INBOUND` work for waypoint proxy

**Comment by SkyfireFrancisZ** [comment]
Please add automated test coverage.
