### ISSUE TITLE
"warmupDurationSecs" property of DestinationRule is not working as per expectation

### ISSUE THREAD

**Issue by suyash-gogte-discovery** [istio/istio#42236]
### Bug Description

We have java based microservice, hence we are interested in using "warmupDurationSecs" property of DestinationRule which is introduced in version 1.14. Below  is DestinationRule

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    meta.helm.sh/release-name: xxx-xx
    meta.helm.sh/release-namespace: xxx-xxx
  creationTimestamp: "2022-12-01T06:48:33Z"
  generation: 1
  labels:
    Name: xxx-xxx
    app: xxx
    app.kubernetes.io/instance: xxx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: xxx
    app.kubernetes.io/version: 0.25.0
    helm.sh/chart: xxx-0.1.0
    version: 0.25.0
  name: xxx
  namespace: xxx
  resourceVersion: "7171516"
  uid: f16eda4f-05cd-43de-8928-76471113213f
spec:
  host: xxx
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      warmupDurationSecs: 423s

initially there was only one pod, and after few mins we added one more using "kubectl scale deployment" command. But
once the 2nd pod became ready , it immediately started receiving requests. We checked with below command
"istioctl x describe pod <new-pod> " , we can see "destinationrule" and "virtualservice" in summary. But when we checked our metrics as shown below, we noticed traffic did not increase gradually for new pod. Can you help us ?
<img width="1104" alt="Screenshot 2022-12-01 at 12 42 29 PM" src="https://user-images.githubusercontent.com/91048059/204989172-86854a0b-62a4-4a8f-9076-32371f33c118.png">

we logged into istio side car container of that newly added pod and checked below
curl 0.0.0.0:15000/config_dump| grep -A 5 -B 5 "slow_start_config" . We can see

      "round_robin_lb_config": {
       "slow_start_config": {
        "slow_start_window": "423s"
       }
      }
     },
     "last_updated": "2022-12-01T06:54:58.192Z"

We are using 
istio version : 1.15.3

please let us know if you need any additional details

### Version

```prose
$ istioctl version
client version: 1.15.3
control plane version: 1.15.3
data plane version: 1.15.3 (23 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by ramaraochavali** [comment]
> it immediately started receiving requests

Are you saying it received same requests as the other pod or few requests?

**Comment by suyash-gogte-discovery** [comment]
@ramaraochavali no it received different requests ...
but the problem is , as per "warmupDurationSecs" property, as shown in above screenshot, pod became ready at 6.55.20 and it immediately started receiving traffic. Whereas warm up duration is given as "423" secs. As per my understanding, it should gradually increase traffic for first 423secs. Like 10% in first 40 secs then 20% in 80secs, then 30% in 120 secs and so on till it reaches 423s.

**Comment by ramaraochavali** [comment]
yes. That is how it is expected to work https://www.envoyproxy.io/docs/envoy/v1.24.0/intro/arch_overview/upstream/load_balancing/slow_start.html?highlight=slow%20start%20mode

**Comment by kashyap-aman-discovery** [comment]
@ramaraochavali 
As @suyash-gogte-discovery mentioned as soon as Pod#2 started, it received the same number of requests as Pod #1 i.e. the traffic was distributed among Pod#1 and Pod#2 equally, which is not the expected behaviour right. 

Since, We have configured warmupDurationSecs as 423 sec. We were expecting that Pod#2 will receive 10% of the traffic for the first 40 sec, which would be increased to 20% traffic in next 80sec and so on till it reaches 423 sec.

**Comment by ramaraochavali** [comment]
Correct. It should not send traffic equivalent to the newly created pod.  Can you share the kubernetes endpoint object for this service when podB starts and also /clusters output?

**Comment by NihalGoel** [comment]
Ran into the same issue, I set the warmupDurationSecs to 600 seconds and we see that if we create new endpoint via scaling the deployment, then the warmup effect does take place however if create endpoints via new deployments, the warmup doesn't take effect 
![image](https://user-images.githubusercontent.com/8469698/208077731-cf996355-f7a8-4520-a5e7-c8bcc6109f4c.png)

The red line in the graph is a newly added pod via scaling and the traffic rises slowly however right after that we do a new deployment and you can clearly see that traffic added to these new pods (turqious and green lines) rises sharply despite the warmup still being 600 seconds

**Comment by ramaraochavali** [comment]
I think [slow start mode](https://docs.google.com/document/d/1NiG1X0gbfFChjl1aL-EE1hdfYxKErjJ2688wJZaj5a0/edit) uses time biased weighted routing and is more suitable for auto scale kind of use cases.  In new deployment, what is the time diff between new pods coming up?

**Comment by NihalGoel** [comment]
The new pods usually take about 60-70 seconds from to initialize and be ready. 
Our use case is actually not only for auto-scaling scenarios but also for new deploments and restarts for which the property doesn't seem to be taking effect.

**Comment by ramaraochavali** [comment]
> Our use case is actually not only for auto-scaling scenarios but also for new deploments and restarts for which the warmupDurationSeconds property doesn't seem to be taking effect.

In the new deployments what is your expectation when all pods are new?

**Comment by NihalGoel** [comment]
In new deployments I would expect that the traffic to the pods rise slowly over the warmup duration. So if I set the `warmupDurationSeconds` to 10 minutes as I do in the above graph, I should see the traffic increase as represented by the red line and not the light blue or green line. Interestingly the `warmupDurationSeconds` prop does take effect if you scale up a pod (which is what the red line represents)

**Comment by ramaraochavali** [comment]
if your clients are sending requests and if all pods are relatively new - how do we gradually send?

**Comment by NihalGoel** [comment]
The old pods terminate after the new pods are ready. So i would either expect the overflowing requests to still go to the old pods for the warmup duration or result in a timeout. Especially if you read the property description ` If set, the newly created endpoint of service remains in warmup mode starting from its creation time for the duration of this window and Istio progressively increases amount of traffic for that endpoint instead of sending proportional amount of traffic ` would imply that even for newly created pods this should happen
https://istio.io/v1.14/docs/reference/config/networking/destination-rule/#LoadBalancerSettings

**Comment by ramaraochavali** [comment]
> So i would either expect the overflowing requests to still go to the old pods for the warmup duration which should be kept alive for that period OR the overflowing requests to timeout. 

That is not how it works. The host weight is [calculated](https://github.com/envoyproxy/envoy/blob/008c6d7b3cb4239607d68a4578d45f386c9c6775/source/common/upstream/load_balancer_impl.cc#L941) based on how much time it is in slow start window and appropriately weights are calculated. If all of the hosts are in slow start mode, they will receive almost similar amount of load.

Istio can not keep pods alive by itself. 

>  Especially if you read the property description If set, the newly created endpoint of service remains in warmup mode starting from its creation time for the duration of this window and Istio progressively increases amount of traffic for that endpoint instead of sending proportional amount of traffic would imply that even for newly created pods this should happen

I would take the blame for the docs :-) . Let me clarify it. I will push a PR to update docs soon to avoid this confusion.

**Comment by NihalGoel** [comment]
Okay, thanks for clarifying :)

**Comment by hanxiaop** [comment]
not stale

**Comment by ramaraochavali** [comment]
I clarified the docs here https://github.com/istio/api/pull/2612 - So nothing else is pending on this.

@hanxiaop Can I close this?

**Comment by hanxiaop** [comment]
@ramaraochavali Sorry I didn't see that. I think we can close this issue.

**Comment by ramaraochavali** [comment]
No problem. Sorry - I should have cross referenced this. Thank you
