### ISSUE TITLE
Secure GRP Server of Pilot is not started, despite serving certificates have been provided

### ISSUE THREAD

**Issue by siiimooon** [istio/istio#42249]
### Bug Description

The certificate loading approach introduced by https://github.com/istio/istio/issues/36916 does not trigger initialisation of the secure gRPC (discovery) server of Pilot.

Proposed solution: https://github.com/istio/istio/pull/42248

### Version

```prose
kubectl version --short
Server Version: v1.23.12

helm chart version
istiod: 1.16.0
```

### Additional Information

Log entry from discovery component of Istio control plane (despite ca crt, tls crt, and tls key is present at default locations - and are picked up by the server at :443):
`The secure discovery service is disabled`

Source code reference: https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/server.go#L733

**Comment by Artiax** [comment]
Can see this change has been pulled into 1.17, is it likely to come out as part of a patch on 1.16? It's currently affecting us after switching to Helm for deployment.

**Comment by CheyenneForbes** [comment]
> Can see this change has been pulled into 1.17, is it likely to come out as part of a patch on 1.16? It's currently affecting us after switching to Helm for deployment.

I second making a 1.16 patch

**Comment by Artiax** [comment]
@CheyenneForbes, we're using the following kustomize postrenderer to work around it for the time being:
`patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: istiod
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--caCertFile=/var/run/secrets/istiod/ca/root-cert.pem"`
