### ISSUE TITLE
Waypoint Proxy: authority header error lacks port in certain circumstances

### ISSUE THREAD

**Issue by dhawton** [istio/istio#42243]
### Bug Description

Follow up to #41491

If you specify an AuthorizationPolicy with port 80, and the scheme is http, the authority header will not have a port listed. The same behavior exists for port 443 when the scheme is https.

This prevents the Envoy rule from matching:
```json
"header": {
    "name": ":authority",
    "suffix_match": ":80"
}
```

Because of this, `RBAC: access denied` will always occur when the service is accepting connections on port 80 regardless if the AuthorizationPolicy wants to allow it.

### Version

```prose
Latest experimental-ambient
```

**Comment by dhawton** [comment]
Given the L4 RBAC design for ztunnel, this is being put on hold pending that design and implementation as well as what impact the sandwich approach will have.

**Comment by SkyfireFrancisZ** [comment]
we do need to fix this since we are not going down the Sandwich route.

**Comment by dhawton** [comment]
This path has some issues pursuing as commented in #42768 . Need to approach in a different way. Going to reopen the original issue and discuss
