### ISSUE TITLE
Mixer should only trace requests if the current request is sampled

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#4227]
At present Mixer add spans to every request, with effective 100% sampling rate.
Mixer should not sample any requests, It should only add spans for requests that have been sampled by the fronting envoy.

**Comment by douglas-reid** [comment]
@mandarjog https://github.com/istio/istio/blob/master/pkg/tracing/config.go#L75 is a good place to start fixing.

**Comment by douglas-reid** [comment]
Not stale. PR pending. Attention will return to this issue shortly.

**Comment by douglas-reid** [comment]
I believe this issue is now resolved for 1.1 and moving forward.
