### ISSUE TITLE
How to separate the multi ingress gateway in a cluster when using multi cluster discovery

### ISSUE THREAD

**Issue by dearboll23** [istio/istio#42283]
Hi team, I have two environments (staging and demo) running in two clusters, each environment contains services in both clusters (called pci and nonpci cluster). I've setup the MultiCluster/MultiNetwork mode for cluster service discovery. I also set up both Ingress gateways for each environment, coz the traffic from different environments looks the same. I hope all the traffic cross the clusters from staging could reach the Ingress gateways for staging, but when I use `istioctl pc endpoints pod-a.staging | grep service` I could see both the Ingress gateways' external Ip. How can I separate the two env from the Ingress gateways? I try to use the label `topology.istio.io/network` or `topology.istio.io/cluster` but the Istiod would have a default clusterId and networkId.

**Comment by hzxuzhonghu** [comment]
maybe you can try enable `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`

**Comment by hzxuzhonghu** [comment]
>"If enabled, Pilot will send only clusters that referenced in gateway virtual services attached to gateway"
