### ISSUE TITLE
local ratelimit stat metrics not have cluster_name  information?

### ISSUE THREAD

**Issue by HailiangChang** [istio/istio#42296]
### Bug Description

Description:

when using global ratelimit and local ratelimit, the stat metrics are deffirent.
global ratelimit:
envoy_cluster_ratelimit_ok{app="reviews", cluster_name="inbound|9080||", hskp_io_parent_workload_name="reviews-v1", instance="10.244.30.37:15020", job="kubernetes-pods", namespace="ratelimit", pod="reviews-v1-844c9b6c77-82b52", pod_template_hash="844c9b6c77", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="reviews", service_istio_io_canonical_revision="v1", version="v1"}
envoy_cluster_ratelimit_ok{app="ratings", cluster_name="outbound|9080||productpage.ratelimit.svc.cluster.local", instance="10.244.30.16:15020", job="kubernetes-pods", namespace="ratelimit", pod="ratings-v1-557bcd6d57-67z2m", pod_template_hash="557bcd6d57", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="ratings", service_istio_io_canonical_revision="v1", version="v1"}

cluster_name="inbound|9080||"
cluster_name="outbound|9080||productpage.ratelimit.svc.cluster.local"
there have cluster_name labels ,which can separate inbound and outbound requests.

loca ratelimit:
envoy_ratelimit_http_local_rate_limit_ok{app="ratings",instance="10.244.30.46:15020", job="kubernetes-pods", namespace="ratelimit", pod="ratings-v1-557bcd6d57-xqxvm", pod_template_hash="557bcd6d57", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="ratings", service_istio_io_canonical_revision="v1", version="v1"}
there not find cluster_name, then cannot separate inbound and outbound requests.

how to set cluster_name for local ratelimit stat metrics?

### Version

```prose
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.14.1 (3 proxies), 1.16.0 (12 proxies)
```

**Comment by zirain** [comment]
linked upstream issue https://github.com/envoyproxy/envoy/issues/24346
