### ISSUE TITLE
ISTIO_META_DNS_AUTO_ALLOCATE does not work from Virtual Machines

### ISSUE THREAD

**Issue by jcam** [istio/istio#42297]
### Bug Description

When creating multiple ServiceEntry items that use the same port, istio will often incorrectly map one service to another's IP addresses. ISTIO_META_DNS_AUTO_ALLOCATE avoids this by setting up a fake IP for routing through.
This does not appear to have any effect from virtual machines running the istio sidecar

curl requests still go to the original IP address, and the services still get mixed up when multiple mesh external service entries are defined for a single given port number (443, for example)

### Version

```prose
$ istioctl version
client version: 1.15.3
istiod version: 1.13.2
istiod version: 1.15.3
data plane version: 1.13.2 (12 proxies), 1.15.0 (2 proxies), 1.15.3 (5 proxies)

$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.23.13-eks-fb459a0

$ helm version --short
v3.8.1+g5cb9af4
```

**Comment by hzxuzhonghu** [comment]
Have you enable ISTIO_META_DNS_CAPTURE?

FYI https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/

**Comment by jcam** [comment]
Hi! Yes, sorry to give a little more background:

I have approximately 130 pods running on kubernetes in a few different istio-enabled namespaces, each of which have this configured in ProxyConfig:
    ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    ISTIO_META_DNS_CAPTURE: "true"

I then have around 30 different ServiceEntry rules for MESH_EXTERNAL endpoints in those namespaces. Maybe 90% of those are on port 443.

I am then able to set PeerAuthentication to STRICT and outboundTrafficPolicy to REGISTRY_ONLY on the Sidecar, which has the benefit of both keeping the mesh extremely secure, in that only specifically tagged outbound targets are allowed, and showing all outbound traffic going to specific tagged endpoints on the Kiali automatically generated service graphs.

When I make the same settings on the VM namespace, it doesn't work as expected. The DNS capture and auto-allocate doesn't appear to happen the way it does for pods. Outbound DNS requests for non-mesh endpoints still do their own DNS lookup, and routing has the same problems that non-captured DNS had before DNS capture/auto-allocate, i.e. if there are a dozen ServiceEntries all using port 443, if the outbound request doesn't have proper SNI tagging / isn't HTTPS, it will end up hitting the wrong external service's IP address.

As an example, here's a test request to google, but it is ending up hitting an amazon S3 server instead of google:

$ curl -k **_https://www.google.com_**
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message><Endpoint>**_www.google.com.s3.us-east-2.amazonaws.com_**</Endpoint><Bucket>www.google.com</Bucket><RequestId>M9QTX0M0E2AN1N3Z</RequestId><HostId>0Yv1s4SkRx6rzSwyBUxeX9aDZ3N8Kh6N7aWxma7Z8u30N8RvZCeBHEgWeUw/s+Cf/ECXX+j7mNk=</HostId></Error>

**Comment by jcam** [comment]
Yes it does work from a pod.

One thing that might be related: the dns capture on my cluster is configured through a networking.istio.io/v1beta1 -ProxyConfig... Perhaps the VM proxy can't read it?

**Comment by jcam** [comment]
Answering my own question: yes that was most of the problem. adding the DNS_AUTO_ALLOCATE option to the cluster.env file on the VM caused it to change the DNS value as expected. I am still seeing some weirdness, but this issue is resolved as a problem between the keyboard and the chair.
It might be useful to document somewhere that envoy configurations on the VM *can't* read from a ProxyConfig or cluster wide proxy setting and are only loaded from that cluster.env
