### ISSUE TITLE
Document is wrong: canary pod will not have label `istio.io/rev=canary`

### ISSUE THREAD

**Issue by j2gg0s** [istio/istio#42290]
### Bug Description

When we upgrade istio to 1.16.0, we find our canary pod did not have label `istio.io/rev=1-16-0`.

```bash
➜  istio git:(de18d65f90) istioctl proxy-status | grep rank
rank-default-c8978f6b4-wqsnc.dev                       Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-16-0-776f86bb6d-hc4nt     1.16.0
➜  istio git:(de18d65f90) k get pods -n dev -l istio.io/rev=1-16-0
No resources found in dev namespace.
➜  istio git:(de18d65f90) k get ns dev -L istio.io/rev
NAME   STATUS   AGE     REV
dev    Active   3y23d   1-16-0
```

The sidecar template also have not related code.
https://github.com/istio/istio/blob/release-1.6/manifests/charts/istiod-remote/files/injection-template.yaml
However gateway template have this label, istio.io/rev

### Version

```prose
istioctl version
client version: 1.16.0
istiod version: 1.16.0
istiod version: 1.16.0
pilot version: 1.14.1
pilot version: 1.14.1
pilot version: 1.14.1
```

**Comment by howardjohn** [comment]
where is the doc that says this? it used to be added but was removed a while back due to issues

**Comment by j2gg0s** [comment]
@howardjohn 

Sorry, i forget to link document

https://istio.io/latest/docs/setup/upgrade/canary/#data-plane
```
For example, the following command will show all the pods using the canary revision:

$ kubectl get pods -n test-ns -l istio.io/rev=canary
```

**Comment by j2gg0s** [comment]
@howardjohn Do we need to modify the document?
