### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by stellanhaglund** [istio/istio#423]
Hi I did a test with a simple c++ container that creates a jwt token and a nodejs container that requests that token over grpc and if I run it without istio I get these values

note I also log the time it took to get the token back
```
request: 0.785ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.668ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.932ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.797ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.816ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.763ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.663ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.670ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 1.168ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 2.656ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 0.730ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
```

but if I do the the same thing with the proxy injected in the pod I get these values

```
request: 197.925ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 5.163ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 4.968ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 78.588ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 6.597ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 76.763ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 6.717ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 175.892ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 72.513ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 6.641ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
request: 10.100ms
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJ7XCJuYW1lXCI6XCJ3b3JsZFwifSIsInN1YiI6InVzZXIiLCJpc3MiOiJtYWRmIn0.LKlO9AT7VHLMiCuA2UDYEss4fFQ0Wv_pKB_rw7NQcUQ
```

sometimes up to 300-500ms which seems like quite a big performance difference
is this something that something that is expected or is this bad?

I'm running the cluster inside minikube

**Comment by ZackButcher** [comment]
Take any performance measurements with a grain of salt this early in the project's life: we've not spent any time on performance yet, and there's _a lot_ of low hanging fruit for us to harvest.

The 300-500ms latencies are likely due to some lazy initialization performed in the request path in Mixer. This initialization occurs any time it receives a new config, including at startup (like I said, lots of low hanging fruit). Outside of those outliers, the variance you're seeing still strikes me as odd. If you run with Zipkin in your cluster the traces could help diagnose where the latency is coming from. Note that today Mixer doesn't have tracing so we don't have the full story (Mixer tracing is next on my list of things to do).

**Comment by ldemailly** [comment]
I've run some performance test and I get a median time under 5000 http1.1 requests/second with proxy around 2ms (albeit in ideal/minimalistic situation) - so I'm surprised about your numbers
(this is excluding an initial "warm up" request) which should be better as grpc should be more efficient for multiple requests than http1.1

Can you run more load and make sure each instance is warm enough to not get paged out etc?

**Comment by stellanhaglund** [comment]
The test i did was basically running the request inside a setInterval on the node side once per second. so there was a constant connection and even if I looked at the logs a few minutes later the results where very similar.

So it doesn't seem likely it was because it wasn't warm?

I'm not sure now that I think about it if I used the debug proxy or the production proxy, I will have to come back on that.
I guess there's some differences between them.

**Comment by stellanhaglund** [comment]
maybe there is no other proxy than the debug proxy? I can't see anything other in the install files. maybe I'm confusing it with the container names i got when I tried it using helm.

**Comment by ldemailly** [comment]
debug image just means it includes more tools

on the other hand we don't produced optimized images but that's what I use for my tests (built from source)

I added https://github.com/istio/istio/issues/426 to provide optimized images

**Comment by ldemailly** [comment]
closing this now - please reopen (in https://github.com/istio/issues/issues ) if needed
