### ISSUE TITLE
Design waypoint enablement strategy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42309]
Currently, waypoint is enabled by using a forked Gateway API type. Using a fork is definitely not viable.

We either need to come up with our own type or modify the upstream API to support our needs. The current fork is to allow 0 listeners.

size: M, type: design

**Comment by therealmitchconnors** [comment]
Can you provide context on what type is forked and why?

**Comment by howardjohn** [comment]
It's Gateway to allow empty `listeners`. I have a PR. to the gateway API to allow it but I am not confident it will be merged

**Comment by howardjohn** [comment]
Possible upstream solution: https://github.com/kubernetes-sigs/gateway-api/pull/1596

**Comment by howardjohn** [comment]
Fixed, we use upstream API now
