### ISSUE TITLE
Design scalable waypoint XDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42308]
Currently, the XDS of the waypoint is not very scalable. We have excessive per-workload listeners, multiple listener hops, etc.

This issue tracks optimizing the XDS. [Stevens doc](https://docs.google.com/document/d/12y-4cINekkxTqKdUnUEWyiSfCRLUF4kFC7LQkYMR6bQ/edit?usp=sharing) for doing the same for ztunnel can be referenced

Conceptually, we want the following logic:

**Listen on Port 15008**:
  * Terminate TLS. Verify the cert based on CA and trust domain, but nothing further.

  * Next, match the authority:
    * Case `VIP:VIP_PORT` -> Goto VIP
    * Case `Pod_IP:*` -> Goto Pod
    * unmatched -> 404

**VIP**:
  * If HTTP (sniffed or declared), parse HTTP
  * For each request (HTTP) or connection (TCP):
    * Trigger "Service" level policies
    * Select a single endpoint (pod) using configured LB policy
    * Goto PodKnownPort

**Pod**:
  * If HTTP (sniffed or declared), parse HTTP (can be skipped if done already)
  * For each request (HTTP) or connection (TCP):
    * Trigger "Pod" level policies applying to this port
    * Send HBONE request to `Pod_IP:Port`

---

What we actually have:

`Listener:inbound_CONNECT_originate`:
  * Terminate TLS. Verify the cert based on CA and trust domain, but nothing further.
  * A big inline route with `:authority` matches:
    * Case `VIP:VIP_PORT` -> internal vip:port cluster -> internal vip:port listener
    * Case `Pod_IP:KNOWN_PORT` -> Goto Pod:Port
    * unmatched -> 404. Note: we 404 on `Pod_IP:UnknownPort`

`internal vip:port listener`:
  * Same logic as "VIP" above, logically.
  * This is implemented by sending to a cluster for our VIP
  * That cluster has EDS resources pointing to internal pod clusters
  * internal pod clusters point to a single internal pod:port listener

`internal pod:port listener`:
  * Same logic as "VIP" above, logically.
  * Sending to HBONE is done by sending to an internal cluster `inbound_CONNECT_originate` with `endpoint_id` set to our `pod:port`

A single request will flow through:
* `inbound_CONNECT_terminate` listener
* `to-internal-vip` cluster
* `internal-vip` listener
* `vip` cluster
* `pod` listener
* `pod` cluster
* `inbound_CONNECT_originate` listener
* `inbound_CONNECT_originate` cluster

So we have 4 Cluster/listener pairs per request

---

Problems with this approach:
* High overhead of listeners and clusters
* Listener/Cluster per pod scales poorly, especially without delta
* Route entry per pod scales poorly
* Behavioral issue: cannot implement pod passthrough, as endpoint_id requires a hardcoded port. We need an "original dst" endpoint_id (https://github.com/istio/istio/issues/42637)
* Typically, all pods in the same service are going to have the same RBAC (and others) policy. However, we duplicate it everywhere

---

Ideas:

* Switch to delta XDS; ensure we have support in the control plane to incrementally send only relevant Clusters/Listeners on a pod update. (https://github.com/istio/istio/issues/42457)
* Switch inbound_CONNECT_terminate to VHDS. Ensure we have support in the control plane to incremental send only relevant VHDS on a pod update
* Switch RBAC, and possibly other policies, to use ECDS. Use a single shared ECDS resource when the *set* of policies is the same
  * Note: this is not granular. Envoy sees all authz policies as one resource, so if Pod1 has [a,b] and Pod2 has [b,c] they cannot share.
* Somehow make endpoint_id dynamic... Not sure how

**Comment by linsun** [comment]
Can you replace with the right link to @stevenctl 's doc?

**Comment by stevenctl** [comment]
Updated

**Comment by kyessenov** [comment]
Can we move this discussion into a doc? I think the issue is being edited so it's difficult to follow the changes.

**Comment by howardjohn** [comment]
Forgot about this and wrote a new issue with more recent info, so lets consolidate there https://github.com/istio/istio/issues/43130
