### ISSUE TITLE
go-junit-report breaks in Go1.10

### ISSUE THREAD

**Issue by chxchx** [istio/istio#4230]
The go test -v output now includes PAUSE and CONT status update lines to mark when parallel tests pause and continue. The Junit XML parser we have been using https://github.com/jstemmer/go-junit-report does not handle PAUSE and CONT, reporting false positive failure results if test cases pause, switch to another test case, and come back.

For example, https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/1168 reports 7 failures but the log https://storage.googleapis.com/istio-prow/istio-postsubmit/1168/build-log.txt shows only 4 (search `--- FAIL:`).

EDIT: The log actually shows 6 failures (see @mattdelco comments below) and searching `--- FAIL:` left out failures from calling `t.Panicf()`.

Options are
* we fix go-junit-report ourselves (if you don't know what spaghetti code means, take a look)
* we wait for a community fix
* we make a new parser based on the new `go test -json` streams.

**Comment by ldemailly** [comment]
also file an issue with the package we use ?

possibly relevant: https://github.com/jstemmer/go-junit-report/issues/66
(ie switch to json)

**Comment by ldemailly** [comment]
ps: please remember to add labels and assignment etc

**Comment by chxchx** [comment]
That issue to go-junit-report was filed after I talked to the k8s people. 

Yeah, I was still on working on the issue and was just about to add the labels and stuff. Thanks!

**Comment by mattdelco** [comment]
So I wondered before on how go-junit-report handles parallelism, and AFAICT the answer seems to be that it doesn't.  It mostly just searches on the RUN/PASS/FAIL lines, so it just ignores the CONT / PAUSE lines.  The golang commit I saw that added CONT/PAUSE just added additional logging lines and that's all.  So, go-junit-report could start to use CONT/PAUSE to help demux the interleaved log messages, but by itself it doesn't seem to me that CONT/PAUSE introduced any problems.

As a sidebar, it doesn't look like the tests I saw in postsubmit opt-in to parallelism (e.g., "make test" doesn't seem to leverage the GOTEST_PARALLEL variable that sets "-test.parallel=4").  So, where does the parellelism come from? AFAICT it's from these lines:
<pre>broker/pkg/platform/kube/crd/client_test.go:	t.Parallel()
pilot/pkg/serviceregistry/kube/controller_test.go:	t.Parallel()
pilot/pkg/config/kube/crd/client_test.go:	t.Parallel()
</pre>
and to opt-out of this you'd have to set "-p 1" (which some tests do [hat tip to GOTEST_P]).

I counted 6 failures, which is closer to junit total of 7 than the other estimate of 4.

this one is straightforward:
<pre>
=== RUN   TestNetworkFailure
--- FAIL: TestNetworkFailure (121.35s)
</pre>
but then the next one is trickier:
<pre>
=== RUN   TestControllerCacheFreshness
=== PAUSE TestControllerCacheFreshness
=== CONT  TestControllerCacheFreshness
=== RUN   TestControllerCacheFreshness
--- PASS: TestControllerCacheFreshness
</pre>
notice that the first instance of the test didn't stop before the next instance started.  It could've been a second instance starting up in parallel, (if golang allows such a thing), but shortly before the 2nd "RUN" there's a panic:
<pre>
I0312 20:14:14.739] panic: send on closed channel
I0312 20:14:14.740] 
I0312 20:14:14.741] goroutine 468 [running]:
I0312 20:14:14.743] istio.io/istio/pilot/test/mock.CheckCacheEvents.func1(0x13433ac, 0xb, 0xc420cf9540, 0xd, 0x133abdb, 0x2, 0xc420622cc0, 0xc, 0xc420622cd0, 0x10, ...)
I0312 20:14:14.744] 	/home/bootstrap/go/src/istio.io/istio/pilot/test/mock/config.go:501 +0x86
I0312 20:14:14.749] istio.io/istio/pilot/pkg/config/kube/crd.(*controller).RegisterEventHandler.func1(0x1313a20, 0xc42043a000, 0x0, 0x0, 0x0)
I0312 20:14:14.749] 	/home/bootstrap/go/src/istio.io/istio/pilot/pkg/config/kube/crd/controller.go:154 +0x2ad
I0312 20:14:14.750] istio.io/istio/pilot/pkg/serviceregistry/kube.(*ChainHandler).Apply(0xc420199d00, 0x1313a20, 0xc42043a000, 0x0, 0x1c15280, 0x1c15280)
I0312 20:14:14.752] 	/home/bootstrap/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/queue.go:144 +0x82
I0312 20:14:14.761] istio.io/istio/pilot/pkg/serviceregistry/kube.(*ChainHandler).Apply-fm(0x1313a20, 0xc42043a000, 0x0, 0x2, 0x2)
I0312 20:14:14.765] 	/home/bootstrap/go/src/istio.io/istio/pilot/pkg/config/kube/crd/controller.go:127 +0x48
I0312 20:14:14.766] istio.io/istio/pilot/pkg/serviceregistry/kube.(*queueImpl).Run(0xc4206ec2d0, 0xc4204ba300)
I0312 20:14:14.768] 	/home/bootstrap/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/queue.go:124 +0x172
I0312 20:14:14.772] created by istio.io/istio/pilot/pkg/config/kube/crd.(*controller).Run
I0312 20:14:14.779] 	/home/bootstrap/go/src/istio.io/istio/pilot/pkg/config/kube/crd/controller.go:172 +0x68
I0312 20:14:14.779] FAIL	istio.io/istio/pilot/pkg/config/kube/crd	153.027s
</pre>
similar for this one:
<pre>
=== RUN   TestIstioConfig
=== PAUSE TestIstioConfig
=== CONT  TestIstioConfig
=== RUN   TestIstioConfig
--- PASS: TestIstioConfig (0.00s)
</pre>
the only one that got mis-attributed was this one:
<pre>
=== RUN   TestControllerClientSync
--- PASS: TestControllerClientSync
=== RUN   TestControllerClientSync
=== PAUSE TestControllerClientSync
=== CONT  TestControllerClientSync
--- PASS: TestControllerClientSync (0.00s)
</pre>
the last 2 were straightforward:
<pre>
=== RUN   TestLRUEvicter
--- FAIL: TestLRUEvicter (0.01s)
=== RUN   TestTTLEvicter
--- FAIL: TestTTLEvicter (0.01s)
</pre>

**Comment by sigma** [comment]
I think the issue is about more than that:

```
$  curl -s --compressed https://storage.googleapis.com/istio-prow/istio-postsubmit/1168/build-log.txt | ag TestIstioConfig
I0312 20:12:04.504] === RUN   TestIstioConfig
I0312 20:12:25.049] === PAUSE TestIstioConfig
I0312 20:13:49.905] === CONT  TestIstioConfig
I0312 20:15:01.770] === RUN   TestIstioConfig
I0312 20:15:01.770] --- PASS: TestIstioConfig (0.00s)
```

It turns out that the first `TestIstioConfig` (the one in `istio.io/istio/pilot/pkg/config/kube/crd`) never reported a status at all, while the second one (in `istio.io/istio/pilot/pkg/config/memory`) did.
No matter how broken the parsing is, that's gonna be an issue.

**Comment by chxchx** [comment]
@sigma The `TestIstioConfig` in `istio.io/istio/pilot/pkg/config/kube/crd` did report failure through `t.Panicf()` (See https://github.com/istio/istio/blob/master/pilot/test/mock/config.go#L521). Still, as @mattdelco pointed out, the parser misattributes `TestControllerClientSync` as failure, and the reason is unclear. The immediate mitigation would be to disable the parallel execution through `-p 1`. This issue pertains to the postsubmit and the potential performance overhead has limited effect on developers.

**Comment by sigma** [comment]
What I mean is that the first test, even if it panic'd, did not get a proper test status assigned to it, therefore was considered as a failure by `go-junit-report` (fail is the initial state for any test).

As for `TestControllerClientSync`, I do believe the issue is possibly the same and Matt just missed a log line:

```
$  curl -s --compressed https://storage.googleapis.com/istio-prow/istio-postsubmit/1168/build-log.txt | ag TestControllerClientSync
I0312 20:11:26.899] === RUN   TestControllerClientSync
I0312 20:11:26.914] --- PASS: TestControllerClientSync (0.01s)
I0312 20:13:03.020] === RUN   TestControllerClientSync
I0312 20:13:20.199] === PAUSE TestControllerClientSync
I0312 20:13:20.241] === CONT  TestControllerClientSync
I0312 20:15:01.838] === RUN   TestControllerClientSync
I0312 20:15:01.839] --- PASS: TestControllerClientSync (0.00s)
```

This time there are actually 3 tests of the same name, and the second one didn't report a status either.
To me it seems like the fact that `TestIstioConfig` actually failed might be coincidental in that case.

Also note that while `TestControllerClientSync` didn't panic in an obvious way, there's no trace of cleanup for the corresponding namespace `istio-test-kfczh`, so it still doesn't look like it completed properly either.

**Comment by mattdelco** [comment]
If go handles parallelism by doing threads in one process, rather than separate processes, then a panic in one test would be enough to kill off the others as well.  If it's handled by a parent process launching child processes, then I suppose the parent could still terminate the tests by immediately killing the children (though in that case I'd have higher expectations for golang to report failure for tests).

Anyway, is there an issue filed for the panic?  I wasn't sure if the backtrace was enough for someone to root-cause the issue.

**Comment by sigma** [comment]
yep, you're right. Parallel tests are implemented as goroutines, and those 3 tests were the only ones still in flight at the time of the panic. So that seems to be a convincing explanation.

**Comment by mattdelco** [comment]
I made a PR to go-junit-report to add support for CONT/PAUSE.  It was merged so if we update to the latest go-junit-report then it should be okay to re-enable parallelism.

**Comment by ldemailly** [comment]
thx @mattdelco !
