### ISSUE TITLE
Enable some filtering mechanism when using `AUTO_PASSTHROUGH` TLS mode in gateway

### ISSUE THREAD

**Issue by shivanshu1333** [istio/istio#42304]
**Describe the feature request**
Right now `AUTO_PASSTHROUGH` do not require an associated VirtualService to map from the SNI value to service in the registry (more details in docs [here](https://istio.io/latest/docs/reference/config/networking/gateway/))

Using `AUTO_PASSTHROUGH` creates huge number of envoy cluster configurations which is equivalent to the the number of kubernetes services present in the cluster.
Depending on the use case these much envoy cluster configurations are not required and are redundant for the end user. There should be some filtering mechanism available to control the number of generated envoy cluster configurations.

One use case could be, generating these envoy cluster configurations for some specific services.
For reference, consider these generated envoy cluster configs when using `AUTO_PASSTHROUGH`
```
SERVICE FQDN                                                                   	PORT 	SUBSET 	DIRECTION 	TYPE       	DESTINATION RULE
BlackHoleCluster                                                               	-    	-      	-         	STATIC
agent                                                                          	-    	-      	-         	STATIC
outbound_.15010_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15012_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15014_._.istiod-stable.istio-system.svc.cluster.local                	-    	-      	-         	EDS
outbound_.15021_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.15021_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local   	-    	-      	-         	EDS
outbound_.15443_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.15443_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local   	-    	-      	-         	EDS
                               ...
                               ...
                               ...
outbound_.18080_._.external-ratelimit-server.default.svc.cluster.local         	-    	-      	-         	EDS
outbound_.18443_._.echo-gateway.echo-7-79306.svc.cluster.local                 	-    	-      	-         	EDS
outbound_.18443_._.external-ratelimit-server.default.svc.cluster.local         	-    	-      	-         	EDS
outbound_.443_._.echo-gateway.echo-7-79306.svc.cluster.local                   	-    	-      	-         	EDS
outbound_.443_._.httpbin-gateway.httpbin-gateway-2-22729.svc.cluster.local     	-    	-      	-         	EDS
outbound_.443_._.istiod-stable.istio-system.svc.cluster.local                  	-    	-      	-         	EDS
outbound_.443_._.kubernetes.default.svc.cluster.local                          	-    	-      	-         	EDS
outbound_.5000_._.helloworld.echo-7-79306.svc.cluster.local                    	-    	-      	-         	EDS        	dr-ew-helloworld-echo-7-79306-svc-cluster-local.echo-7-79306
prometheus_stats                                                               	-    	-      	-         	STATIC
sds-grpc                                                                       	-    	-      	-         	STATIC
xds-grpc                                                                       	-    	-      	-         	STATIC
zipkin                                                                         	-    	-      	-              STRICT_DNS
```
In reality there would be many more such configurations (depending on the no of k8s services, which can be huge), but my use case here is to use only `outbound_.5000_._.helloworld.echo-7-79306.svc.cluster.local`, so having others in not beneficial and is redundant.

**Describe alternatives you've considered**
There are no alternatives right now other than not using `AUTO_PASSTHROUGH` at all, but using `AUTO_PASSTHROUGH` simplifies a few things, and hence having this filtering option will make it easier to use.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
This would need API level changes, not just implementation, to configure which services should be "multi-network". its feasible but not just an internal optimization
