### ISSUE TITLE
Define, document, and test a concrete migration path from sidecar to ambient

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42316]
While we have done some work to support a migration, we don't have a concrete plan for the steps
a user will need to/be able to take. This includes migrating from non-CNI or istio CNI, etc

size: L, type: design

**Comment by dgn** [comment]
Reopening as we still don't have this documentation.

**Comment by fjglira** [comment]
This makes sense to be added directly to the istio.io page. Would it be better to add the issue there? I can assign it to myself and start adding documents, and discuss the best way to implement this.

**Comment by howardjohn** [comment]
The next step here is not an istio.io page, though I agree its the right final step. But we need to decide how the migration will work, and if there are code changes needed to support this.
