### ISSUE TITLE
Add XDS benchmarks for ambient

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42315]
`pilot/pkg/xds/bench_test.go` has benchmark tests for XDS generation. These are important tests to track control plane
performance (and data plane, to some extent).

We should add tests for both waypoints and ztunnels.

size: S, type: implementation

**Comment by howardjohn** [comment]
This is fairly non-trivial until we impleented support for ServiceEntry since the benchmarks assume istio config

**Comment by hanxiaop** [comment]
not stale
