### ISSUE TITLE
Complete on-demand XDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42314]
Currently, we have some WIP on-demand XDS implementation in the ztunnel and Istiod.
This issue tracks completion.

* Istiod: On connect, subscribe to node-local pod info immediately
* ztunnel: add full e2e testing

size: , type:

**Comment by linsun** [comment]
> Istiod: On connect, subscribe to node-local pod info immediately 

You mean when ztunnel is connected, it subscribes to node-local pod info immediately from Istiod?

**Comment by hzxuzhonghu** [comment]
How does ztunnel express its own address or unique id to tell istiod to know which node it resides? If ztunnel direct connect to istiod, it is not a matter. But it could be through a gateway.

**Comment by howardjohn** [comment]
NODE_NAME is already part of metadata

**Comment by hzxuzhonghu** [comment]
great downward api support node name
