### ISSUE TITLE
primary-remote on multiple network,  remote istio-eastwestgateway pod failed to create because failed to call webhook 

### ISSUE THREAD

**Issue by lazywhite** [istio/istio#42327]
### Bug Description

follow this tutorial https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/
failed to create istio-system/deployment/istio-eastwestgateway

```
k describe -n istio-system rs istio-eastwestgateway-6b644b6dc4

Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  75s (x18 over 12m)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "object.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject/cluster/cluster2/net/network2?timeout=10s": x509: certificate signed by unknown authority

```

primary cluster info
```
root@kvm3:~# k get -n istio-system service istio-eastwestgateway 
NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                                                           AGE
istio-eastwestgateway   LoadBalancer   11.43.157.123   192.168.122.231   15021:41891/TCP,15443:30572/TCP,15012:35297/TCP,15017:32030/TCP   119m
root@kvm3:~# k get node -o wide 
NAME   STATUS   ROLES                  AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kvm3   Ready    control-plane,master   24h   v1.24.4+k3s1   192.168.122.57   <none>        Ubuntu 20.04.5 LTS   5.4.0-131-generic   containerd://1.6.6-k3s1

```

remote cluster info
```
root@kvm4:~# k get -n istio-system svc
NAME                    TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)                                                           AGE
istiod                  ClusterIP      12.43.14.181   <none>            15012/TCP,443/TCP                                                 94m
istio-eastwestgateway   LoadBalancer   12.43.221.45   192.168.122.220   15021:36723/TCP,15443:34277/TCP,15012:30421/TCP,15017:47268/TCP   94m
root@kvm4:~# k get node  -o wide
NAME   STATUS   ROLES                  AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kvm4   Ready    control-plane,master   24h   v1.24.4+k3s1   192.168.122.58   <none>        Ubuntu 20.04.5 LTS   5.4.0-128-generic   containerd://1.6.6-k3s1

```

### Version

```prose
root@kvm3:~/istio-1.16.0# istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (2 proxies)
root@kvm3:~/istio-1.16.0# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.4+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.4+k3s1
```

### Additional Information

Target cluster context: cluster1

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-12-07 14:38:42.19975771 +0800 CST

Cluster endpoint: https://192.168.122.57:6443
CLI version:
version.BuildInfo{Version:"1.16.0", GitRevision:"8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783", GolangVersion:"go1.19.3", BuildStatus:"Clean", GitTag:"1.16.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.0", GitRevision:"8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.0}

Fetching proxy logs for the following containers:

istio-system/istio-eastwestgateway/istio-eastwestgateway-6d4b46d958-fn96v/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-5d74d64857-zcvcl/istio-proxy
istio-system/istiod/istiod-c754cbc9-rjjjv/discovery
metallb-system//speaker-ggjch/speaker
metallb-system/controller/controller-6c58495cbb-bzpc6/controller

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace aseit-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace aseit-system istio-injection=enabled' to enable it, or 'kubectl label namespace aseit-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace metallb-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace metallb-system istio-injection=enabled' to enable it, or 'kubectl label namespace metallb-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service metallb-system/webhook-service) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Creating an archive at /root/istio-1.16.0/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by zirain** [comment]
remote should connect to `istiod-remote.istio-system.svc`, seems you miss something.

**Comment by hzxuzhonghu** [comment]
Do you use same CA cert in the two clusters?

**Comment by lazywhite** [comment]
> Do you use same CA cert in the two clusters?

because this is a primary remote model so we don't need intermediate CA.
But I have also tried it, still the same error

**Comment by 13567436138** [comment]
I face the same error，how to solve

**Comment by 13567436138** [comment]
I solved by setting webhook caBundle

**Comment by MazenElzanaty** [comment]
Having the same issue on 1.17

**Comment by leandroberetta** [comment]
Hi, I'm having the same issue too.

I followed the instructions for primary remote with different networks and also followed the "Before you begin" instructions, specifically where certifiates are configured, so both clusters have a "cacerts" secret (I'm not sure this is a requisite for the remote cluster).

After installing the Istio resources on the remote clusters (with remote profile), I can see that the MutatingWebhookConfiguration does not have any caBundle configured on the clientConfiguration of the webhooks. 

I fixed this for now, adding the same caBundle from cluster 1 (the primary), I used the following commands to do this as a workaround:

```
CA_BUNDLE=$(kubectl get secret cacerts -n istio-system --context ${CTX_CLUSTER1} -o jsonpath={.data."ca-cert\.pem"})

kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-sidecar-injector -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"rev.namespace.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-sidecar-injector -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"rev.object.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-sidecar-injector -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"namespace.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-sidecar-injector -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"object.sidecar-injector.istio.io\"}]}"

kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-revision-tag-default -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"rev.namespace.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-revision-tag-default -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"rev.object.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-revision-tag-default -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"namespace.sidecar-injector.istio.io\"}]}"
kubectl patch mutatingwebhookconfigurations.admissionregistration.k8s.io -n istio-system istio-revision-tag-default -p "{\"webhooks\":[{\"clientConfig\":{\"caBundle\":\"${CA_BUNDLE}\"},\"name\":\"object.sidecar-injector.istio.io\"}]}"

```

It seems that when installing Istio resources on cluster 2, the installer needs to use some secret with the required CA (could it be from the cacerts secret?).
