### ISSUE TITLE
Apply new tracing address without redeploy applications

### ISSUE THREAD

**Issue by suxiaoxiaomm** [istio/istio#42328]
Hi, 
My project is switching our tracing backend now. So I changed meshConfig 's tracing address setting.

However, I notice that this new address doesn't get propagated to istio-proxy of my applications.
Only when I restarted one of the application pod, which restarts the istio-proxy sidecar, that makes this new address takes affect.

Is there a way to apply this change without redeploy my application?

Appreciate your help!

**Comment by howardjohn** [comment]
If you use the new Telemetry API it might https://istio.io/latest/docs/tasks/observability/telemetry/ (I am not an expert, not 100% sure).

**Comment by zirain** [comment]
> If you use the new Telemetry API it might https://istio.io/latest/docs/tasks/observability/telemetry/ (I am not an expert, not 100% sure).

yes, Telemetry API will, if not, there must be a bug.

**Comment by howardjohn** [comment]
Telemetry API solves this
