### ISSUE TITLE
failed to generate secret for ROOTCA x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jalOO7** [istio/istio#42323]
## Description
Hello,
I am deploying Vault as CA with cert-manager-istio-csr. Unfortunately and i am facing an issue with all the envoy sidecar proxies. They don't start and they are showing the below error in the logs : 
**failed to generate secret for ROOTCA: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"'**

## Cert-manager and Vault deployment 
I followed this tutorial https://medium.com/everything-full-stack/how-to-integrate-vault-as-external-root-ca-with-cert-manager-istio-csr-and-istio-7684baa369db

## version
**Istio:**
1.15
**Kubectl:**
Client Version: v1.25.
Server Version: v1.24.6
**Helm:**
v3.10.0+gce66412

## Logs and troubleshooting
I have  added log obtained- by doing port-forwarding on port 15000 of the sidecar envoy proxy 
[config_dump.zip](https://github.com/istio/istio/files/10171134/config_dump.zip)

I have also noticed when doing kubectl port forwarding that : http://localhost:15000/certs give an empty list:

![certs](https://user-images.githubusercontent.com/25010913/206048204-7a74fef5-e3bf-4fa3-973e-406d83d95595.png)
My guess is that the sidecar proxy is throwing the error "  x509: certificate signed by unknown authority" because of missing CA in the expected path but I checked the istio-ca-root-cert configmap, it's present and filled with the right CA information. 

Do you have any idea on the possible causes of the issue I am having? Thanks.

**Comment by hzxuzhonghu** [comment]
I guess the rootca does not match what istio-csr uses, can you check it

**Comment by jalOO7** [comment]
You pointed to the right problem. It's fixed now. Thanks a lot !

**Comment by kuberkaul** [comment]
@jalOO7 what was the solution ?
