### ISSUE TITLE
Consistent release filenames

### ISSUE THREAD

**Issue by IzhakJakov** [istio/istio#42338]
Is it possible to have `istio-1.16.0-osx-amd64.tar.gz` instead of **OR** in addition to `istio-1.16.0-osx.tar.gz` ?

This would be consistent with the filenames of other releases.

**Comment by IzhakJakov** [comment]
Any comments or thought regarding this question?

**Comment by IzhakJakov** [comment]
Thank you!

**Comment by ericvn** [comment]
https://github.com/istio/release-builder/pull/1560

**Comment by IzhakJakov** [comment]
Thank you!

**Comment by IzhakJakov** [comment]
Actually I just tried [1.19.0-alpha.1](https://github.com/istio/istio/releases/tag/1.19.0-alpha.1) and [1.18.1](https://github.com/istio/istio/releases/tag/1.18.1).  Both still **missing** `...-osx-amd64.tar.gz`.
Not sure if this change just need some time to go into production.

**Comment by ericvn** [comment]
The new artifacts will appear in the 1.19 builds (starting with alpha.2) as that is where the PR was merged. It was not cherry-picked back to 1.18.

**Comment by ericvn** [comment]
@IzhakJakov You can look at https://github.com/istio/istio/releases/tag/1.19.0-beta.0 to verify. Thanks.

**Comment by IzhakJakov** [comment]
Perfect! Thank you :)
