### ISSUE TITLE
IngressGateway not in root namespace can't read meshConfig from ConfigMap

### ISSUE THREAD

**Issue by j2gg0s** [istio/istio#42331]
### Bug Description

1. canary upgrade istio from 1.14 to 1.16, and set new istio.io/rev=1-16-0
```istioctl install -r 1-16-0 -f test-istiod.yaml```
2. k label ns ingress-istio istio.io/rev=1-16-0,istio-injection-
3. restart our ingress gateway in namesapce ingress-istio
4. ingress gateway still connect to old istiod, 
because we don't have configmap/istio-1-16-0 in namespace ingress-istio,
and ingress gateway will not be injected

Is this what we expect? I'm not sure

### Version

```prose
client version: 1.16.0
istiod version: 1.16.0
istiod version: 1.16.0
pilot version: 1.14.1
```

**Comment by howardjohn** [comment]
This is WAI, follow https://istio.io/latest/docs/setup/additional-setup/gateway/ to use the new(er) install method which doesn't have this issue since it is not based on configmap reading.
