### ISSUE TITLE
Need a design doc for ambient multicluster multi-network

### ISSUE THREAD

**Issue by linsun** [istio/istio#42334]
**Describe the feature request**

Particularly for multi-network, some challenges outlined in https://github.com/istio/istio/issues/41375 from the initial investigation.

Also worth covering if multi-primary or primary-remote multicluster are valid patterns for ambient and what it would look like for single primary for ambient.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Design doc: https://docs.google.com/document/d/1MCRZWvlbZS6DLn5N4pD9ww2O-fL7jzi9-l0cWbqH1kk/edit.

Note: I would expect that we approve that (or similar), but do not actuallyimpement for ~6 months while we focus on the core.

**Comment by howardjohn** [comment]
Closing in favor of https://github.com/istio/istio/issues/41375
