### ISSUE TITLE
shorten reviewers list names - all get truncated to "Reviewers - istio..."

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4234]
trying to find which list makes me getting some review requests on a given PR

For instance:
https://github.com/istio/istio/pull/1963

![screen shot 2018-03-12 at 7 06 49 pm](https://user-images.githubusercontent.com/3664595/37318601-a6e936ce-2628-11e8-9abc-4f23b27be04d.png)

I can't tell because all I see is "Reviewers - istio..."

**Comment by geeknoid** [comment]
All these teams were deleted...
