### ISSUE TITLE
Ambient support for AWSCloud

### ISSUE THREAD

**Issue by linsun** [istio/istio#42340]
We want to ensure ambient works not only on google cloud but also another major cloud, like AWS

**Comment by linsun** [comment]
not stale

**Comment by linsun** [comment]
We have done some testing with AWS Cloud with latest work from Solo - https://github.com/istio/istio/issues/48212

**Comment by linsun** [comment]
This should be resolved, please try latest master or release 1.21 build, or wait for the official 1.21 release.  see https://github.com/istio/istio/issues/48212.  cc @liwenwu@amazon.com

**Comment by linsun** [comment]
Sorry, just got confirmation from Eric that the change is not in beta 0 yet, but should be in -beta.1 since it was merged after beta.0 was released. I expect that the new build will be available in a day or 2.

**Comment by howardjohn** [comment]
This is presumed solved with recent changes. If there are any issues detected, please open an issue. Thanks!
