### ISSUE TITLE
Need design for replacing exportTo in sidecars

### ISSUE THREAD

**Issue by linsun** [istio/istio#42344]
Today in Istio, users can specify exportTo on k8s services to indicate the scope for the services.

Users can also specify exportTo on Istio networking resources such as VS or SE to define the scope of the Istio resources.

We need to figure out the story for this in ambient, do we continue to support the same semantics? If not, what is the equivalent?

**Comment by zengyuxing007** [comment]
In the current istio implementation, the scope granularity defined by exportTo can only be defined to namespace granularity, in the actual production environment, often want to control to the workload level granularity, hope to conside this requirement,thanks

**Comment by linsun** [comment]
I am not sure if this is still needed for ambient given in ambient, you can explicitly bind configuration to its waypoint.  Services without any exportTo are not avail to all waypoints, only to the waypoint for one or more given service(s).

**Comment by linsun** [comment]
Closing this as this is no longer needed with destination oriented waypoint.
