### ISSUE TITLE
Unable to preserve source IP 

### ISSUE THREAD

**Issue by shabbiervempalli-yti** [istio/istio#42359]
### Bug Description

Hi Team,
We are trying to whitelist few public ip's so that only these ip's can be accessing our services  over the internet
to achieve this we follwed below steps
https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/
created envoy filter and authorization policy still we cant able to preserve public IP 

### Version

```prose
1.13
```

**Comment by zirain** [comment]
1.3? https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases

**Comment by shabbiervempalli-yti** [comment]
> 1.3? https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases

version 1.13

**Comment by shabbiervempalli-yti** [comment]
changed external traffic to Local in gateway
