### ISSUE TITLE
implement ServiceInternalTrafficPolicy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42377]
,currently we ignore it

**Comment by howardjohn** [comment]
be cautious of https://github.com/kubernetes/kubernetes/pull/113363

**Comment by hzxuzhonghu** [comment]
Node local seems not perfect, it means if no local host endpoints found the traffic will be dropped

**Comment by howardjohn** [comment]
I agree but its part of the core Service spec now. I think its mostly used for daemonsets

**Comment by hzxuzhonghu** [comment]
right, mostly for performance.  I guess no failover because that iptables can not do that.
