### ISSUE TITLE
Unable to configure custom pilot cert provider via Helm

### ISSUE THREAD

**Issue by hazim1093** [istio/istio#42382]
### Bug Description

We are using helm to install Istio with [Custom CA Integration using Kubernetes CSR](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s). 

We specify the CA Cert via meshConfig and set custom pilot cert provider (as in the guide). 
While setting custom pilot cert provider via `global.pilotCertProvider`, It will remove the volume mount for `istio-ca-root-cert` from the [injection template](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L469), which is still required in this case. 

As a workaround, we can leave the `global.pilotCertProvider` to its default value of `istiod` and explicitly specify the env var `PILOT_CERT_PROVIDER`. In this case, helm complains since the environment variable is [already specified in the deployment](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L127), and overriding it results in multiple environment variables with the same key ([issue](https://github.com/helm/helm/issues/6002)). 

A possible solution could be to remove the if statement for mounting `istio-ca-root-cert` and mount it as optional. A similar change was implemented in istiod but not in the injection templates https://github.com/istio/istio/pull/39375 . 

Would be happy to create a pull request if this is the preferred way forward

### Version

```prose
$ istioctl version                                                                             
client version: 1.15.2
control plane version: 1.15.3
data plane version: 1.15.3 (12 proxies)

$ kubectl version --short  
Client Version: v1.23.1
Server Version: v1.23.11-gke.300

$ helm version 
v3.6.3 via helm-controller v0.14.0 (flux)
```

**Comment by keithmattix** [comment]
cc @jaellio
