### ISSUE TITLE
DISABLE tls for specific SNI in DR, helpful in the case of double tls

### ISSUE THREAD

**Issue by shivanshu1333** [istio/istio#42393]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I'm encountering a case where I hit double TLS when using `PASSTHROUGH` at the gateway. To overcome this, I intend to DISABLE tls using DR for particular SNIs. But it looks like this is not possible when I set tls mode as `DISABLE`, it's disabled for all, not for specific SNI.

It'd be nice to DISABLE tls for specific SNIs.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
You can match with VS on the SNI and send to a different DR config
