### ISSUE TITLE
accessLogFile is ignored by Istio

### ISSUE THREAD

**Issue by Krast76** [istio/istio#42399]
### Bug Description

I try to write istio-gateway access-logs into a files.

I set this on my (helm) values for istiod : 

```
meshConfig:
     accessLogFile: "/var/log/istio/envoy_access.log"
     accessLogFormat: "{\"timestamp\":%START_TIME%, \"method\": %REQ(:METHOD)%, \"bytes_send\": %BYTES_SENT%, \"bytes_received\": %BYTES_RECEIVED%}\n"
```

On gateway pods the accessLog is well formatted but logs are not written on the filesystem.

To figure out why my settings got ignored I've tried to debug it with istioctl : 

I got this Envoy configuration from one of gateway pods  (with this command :  ` istioctl proxy-config listener istio-gateway-6658ddbc66-zdxwp -o json`):

```
                            "accessLog": [
                                {
                                    "name": "envoy.access_loggers.file",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                        "path": "/dev/stdout",
                                        "logFormat": {
                                            "textFormatSource": {
                                                "inlineString": "{\"timestamp\":%START_TIME%, \"method\": %REQ(:METHOD)%, \"bytes_send\": %BYTES_SENT%, \"bytes_received\": %BYTES_RECEIVED%}\n"
                                            }
                                        }
                                    }
                                }
                            ],
```
I think it's a bug because accessLogFormat but accessLogFile not.

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.12.8
data plane version: 1.12.8 (34 proxies)
$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.21.13
```

**Comment by howardjohn** [comment]
Istio 1.12 is EOL. I would recommend upgrading and seeing if its still present. If it is, post the full `istio` configmap

**Comment by zirain** [comment]
please upgrade to a [supported release](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases) and retry.

**Comment by bochengchu** [comment]
I am able to reproduce this issue in Istio 1.16.1
It looks like Envoy has problem opening the file. The `error_state` has something like:
`
"access_log": [
        {
         "name": "envoy.access_loggers.file",
         "filter": {
          "response_flag_filter": {
           "flags": [
            "NR"
           ]
          }
         },
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
          "path": "/tmp/envoy.log",
          "log_format": {
           "text_format_source": {
            "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
           }
          }
         }
        }
       ]
      },
      "last_update_attempt": "2023-01-06T08:10:12.931Z",
      "details": "unable to open file '/tmp/envoy.log': Read-only file system"
`

**Comment by howardjohn** [comment]
@bochengchu that seems a different issue (which is expected - you need to use a writeable directory, /tmp is readonly). In the original case their config had a different path but envoy shows ` "path": "/dev/stdout",`
