### ISSUE TITLE
Switch LB algorithm to LEAST_REQUEST on older versions

### ISSUE THREAD

**Issue by arnoldyahad** [istio/istio#42396]
### Bug Description

following this: 
https://github.com/istio/istio/pull/37220/files

i would like to be able to change the load balancing method on earlier versions, is it possible? (through istio operator or envoyfilters? 

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.9.0
data plane version: 1.9.0 (65 proxies)
```

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings

We won't do anything else for old versions. Please upgrade, using 1.9.0 is a very unsafe idea...
