### ISSUE TITLE
istio-proxy sidecar slow to drain on SIGTERM

### ISSUE THREAD

**Issue by alexlo03** [istio/istio#42408]
### Bug Description

Thanks in advanced 🙏 

# Background
We have recently updated our mesh to have

```
    defaultHttpRetryPolicy:
      retryOn: connect-failure,refused-stream
```

To prevent non-idempotent retries.

# Problem

We are now seeing cases where a pod responds UNAVAILABLE in the case where the Envoy is up but the serving container is down (due to pod shutdown for upgrade/deployment).

The SIGTERM signals hit the containers at similar times (within 1-2ms), but Envoy-proxy takes a long time from SIGTERM to actually log that it is draining, even though `--drain-strategy immediate` is passed to Envoy.

It appears Envoy handles signals asynchronously:

> So the reason is that dispatcher handles signals asynchronously. it generates event to dispatch the queue and then returns so that the following signals can be handled
> https://github.com/envoyproxy/envoy/issues/15467#issuecomment-804237539

so it seems there is unpredictable duration between the kernel sending SIGTERM and when envoy decides to deal with it.

From "Agent draining Proxy" (SIGTERM)
To "Envoy proxy is NOT ready: server is not live, current state is: DRAINING" (our only signal that the Envoy is in fact draining)

We see delays of more than 1s.

Here is a sanitized example:

<img width="904" alt="istio-sigterm-issue" src="https://user-images.githubusercontent.com/1072146/207136542-e2a6e7a9-6599-417d-ac98-f8204d2fbd4f.png">

This violates our expectations: we would like the istio-proxy to go into DRAINING really "immediately"

# Solutions

We are unsure how to best approach - we can see two avenues:

1. Slower workload binary shut down: Artificially slow down the SIGTERM to binary shutdown in our containers by 1s or 2s - then it would shut down after istio-proxy has gone into draining mode.
Pros: in our control
Cons: total hack

2. Earlier term to Istio-proxy: Kubernetes pre-shutdown hook to do TERM against istio-proxy earlier
https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--drain_listeners?graceful
https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace
Pros: probably the "complete solution"
Cons: should be implemented by Istio? ALSO: Would this also terminate the Forward proxy for downstream requests from the workload while it is still operating? The istio-proxy is both the reverse and forward proxy for the workload.

3. Something else?

Thank you!

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.15.1
data plane version: 1.15.1 (xxx proxies)

$ kubectl version --short
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.22.15-gke.100
```
```


### Additional Information

_No response_

**Comment by howardjohn** [comment]
There should be no expectation that in a distributed system anything happens immediately. The solution is to have your app continue handling requests, you shouldn't exit on immediate SIGTERM. You would have the same issue without Istio

**Comment by alexlo03** [comment]
Thanks- 100% - draining is entirely up to the mesh. Sorry for the noise.
