### ISSUE TITLE
Consider cleaning up event handlers on controller shutdown

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42409]
Since https://github.com/kubernetes/kubernetes/pull/111122, we can drop handlers from informers. We might consider using this.

main benefit is with leader-elected ones, which shutdown and then can resume later. I think today we leak handlers. Others are probably not benefit and just introduce risk, since we only stop them when the entire process is shutting down anyways

**Comment by hzxuzhonghu** [comment]
Let me take a look

**Comment by hzxuzhonghu** [comment]
Sum up of all usage of leader election:

- [ ] [multi cluster namespace controller](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L283-L293)
- [ ] [serviceexport controller](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L324-L339)
- [ ] [ingress status syncer](https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/configcontroller.go#L102-L123)
- [ ] [gateway status controller](https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/configcontroller.go#L168-L180)
- [ ] [gateway deployment controller](https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/configcontroller.go#L188-L200)
- [ ] [istio analyze controller](https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/configcontroller.go#L297-L304)
- [ ] [istio status controller](https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/configcontroller.go#L333-L340)

**Comment by hzxuzhonghu** [comment]
They are not quite similar, will resolve them one by one

**Comment by hzxuzhonghu** [comment]
All these are done
