### ISSUE TITLE
Clarifications regarding VM integration

### ISSUE THREAD

**Issue by shashankram** [istio/istio#42402]
Hi, I am trying the VM integration with Istio and have a few points that need further clarification to understand better how Istio support different network models.

Based on https://istio.io/latest/docs/setup/install/virtual-machine/:
1. What do the environment variables `VM_NETWORK` and `CLUSTER` signify in https://istio.io/latest/docs/setup/install/virtual-machine/#prepare-the-guide-environment? These get fed to IstioOperator and istioctl for installing the control plane. I don't see guidance on what these should be set to and their impact on integrating VMs, specifically for the different network models (single and multi network).
2. Given the [VM onboarding doc](https://istio.io/latest/docs/setup/install/virtual-machine/) suggest to install Istio control plane and east-west gateway with different parameters/config depending on the network model, is it currently possible for Istio to integrate with VMs belonging to both directly and unconnected networks using a shared control plane and east-west gateway? If yes, what are the instructions to do so?
3. There are a lot of manual steps involved in integrating VMs. Is there a plan to automate some of these to simplify onboarding?

Thanks

**Comment by stevenctl** [comment]
1. `CLUSTER` names the cluster. By default cluster's have a name `Kubernetes`. It's best practice to give clusters a name. In the case the mesh is expanded to multi-cluster, this is important. 

`VM_NETWORK` isn't used in the IstioOperator but for the VM bootstrap. It tells the control plane what network connectivity expectations the VM expects. 

2. The east-west gateway is ~always used for discovery/to access the control plane. That `VM_NETWORK` decides whether traffic is direct to Pod or VM IP (same network), or if traffic goes through the gateway (different networks)

3. I don't think anyone is actively working on this. Contributions are always welcome. I think for the most part we expect that different organizations will have much of their own preferred tooling to automate the setup of virtual machines. What istio exposes should remain flexible to help ease that process.

**Comment by shashankram** [comment]
> 1. `CLUSTER` names the cluster. By default cluster's have a name `Kubernetes`. It's best practice to give clusters a name. In the case the mesh is expanded to multi-cluster, this is important.
> 

I wasn't sure if the `CLUSTER` referenced a k8s cluster or was it something pertaining to where the VM may be running. Can this be set to an arbitrary name?

> `VM_NETWORK` isn't used in the IstioOperator but for the VM bootstrap. It tells the control plane what network connectivity expectations the VM expects.
> 

In the multi-network demo, this is set to `vm-network`. Is this meant to be a user-defined value, or is it meant to be hardcoded to `vm-network`? What's the significance with respect to the naming?

> 2. The east-west gateway is ~always used for discovery/to access the control plane. That `VM_NETWORK` decides whether traffic is direct to Pod or VM IP (same network), or if traffic goes through the gateway (different networks)
> 3. I don't think anyone is actively working on this. Contributions are always welcome. I think for the most part we expect that different organizations will have much of their own preferred tooling to automate the setup of virtual machines. What istio exposes should remain flexible to help ease that process.

Thanks for clarifying the current state of this feature.

**Comment by stevenctl** [comment]
The `CLUSTER` is more relevant for the control plane/east west gateway setup. It should just denote what cluster the VM uses for discovery/what cluster the gateway lives in and of course which cluster the CP is running in. 

`vm-network` is an arbitrary example value. It can be anything.

**Comment by shashankram** [comment]
@stevenctl Does the WorkloadEntry|Group resource need to be manually applied on the cluster? I don't see this requirement mentioned in https://istio.io/latest/docs/setup/install/virtual-machine/, but don't see a `WorkloadEntry/WorkloadGroup` resource created on the cluster.

**Comment by stevenctl** [comment]
`WorkloadGroup` is intended to:

1. Configure a "template" for WorkloadEntries that are created via auto-registration
2. Configure health-check probes

We also happen to use it to give istioctl a basic set of information to generate the bootstrap files to be placed on the VM. 

> are the docs accurately reflecting the default workflow

Yes, but I can understand why this is confusing. 

I think we can promote auto registration. It's definitely not "experimental" anymore.

**Comment by shashankram** [comment]
Got it, thanks.

The current default seems more like "autoregistration" as it doesn't require applying the workloadgroup.yaml, hence the confusion.
