### ISSUE TITLE
istioctl pc workload improvement suggestions

### ISSUE THREAD

**Issue by linsun** [istio/istio#42410]
I don't think the return of this cmd is entirely correct, surprised to see istiod and other ztunnels, along with a few pods I don't expect the ztunnel manage, for example: helloworld-v1.

```
 go run istioctl/cmd/istioctl/main.go proxy-config workload ztunnel-rjkbb.istio-system
NAME                                      NAMESPACE    IP          NODE                  PROTOCOL
helloworld-v1-cross-node-55446d46d8-6hzbj default      10.244.2.10 ambient-worker        HBONE
helloworld-v2-same-node-65bd845857-5rxs9  default      10.244.1.6  ambient-worker2       HBONE
istiod-747687bbb6-h6hc4                   istio-system 10.244.1.2  ambient-worker2       TCP
sleep-66b946687b-6cwfw                    default      10.244.1.7  ambient-worker2       HBONE
sleep2-7886c67bf8-7gmfq                   default      10.244.2.11 ambient-worker        TCP
swiss-army-knife-58c658bdfb-8mrrq         default      10.244.2.12 ambient-worker        HBONE
ztunnel-2gkvn                             istio-system 10.244.0.5  ambient-control-plane TCP
ztunnel-fx8ls                             istio-system 10.244.2.3  ambient-worker        TCP
ztunnel-rjkbb                             istio-system 10.244.1.3  ambient-worker2       TCP
```

**Comment by linsun** [comment]
@GregHanson opened this, not urgent when you have some time.

**Comment by howardjohn** [comment]
it is correct, these are the workloads ztunnel knows about. It knows about pods even not in the mesh

**Comment by howardjohn** [comment]
Protocol=TCP (indirectly) means it's not captured

**Comment by linsun** [comment]
Thanks John! is there any value to display istiod and ztunnels given they are system pods? I think i have a few other pods in kube-system and local-path-storage that were ignored in the return.

**Comment by howardjohn** [comment]
The command is meant to display the config of the proxy. Since the proxy has config for kube-system it should be displayed IMO. It would be far more confusing to _not_ display info the proxy knows about.

Note proxy-config is a low level debugging tool.

**Comment by linsun** [comment]
Another issue i noticed with the config dump is that the info returned is stale. I think this is probably more important. for example, after I label my namespace for ambient, i am not seeing sleep or HW displayed as HBONE **IF I did config dump before i label the namespace for ambient**.  

```
go run istioctl/cmd/istioctl/main.go proxy-config workload $ZTUNNEL.istio-system
NAME                                      NAMESPACE          IP         NODE                  PROTOCOL
coredns-6d4b75cb6d-2rmrg                  kube-system        10.244.0.2 ambient-control-plane TCP
coredns-6d4b75cb6d-q86k8                  kube-system        10.244.0.3 ambient-control-plane TCP
helloworld-v1-cross-node-55446d46d8-vrbmx default            10.244.2.4 ambient-worker        TCP
helloworld-v2-same-node-65bd845857-b6zwh  default            10.244.1.4 ambient-worker2       TCP
istio-ingressgateway-8494dc7655-zpgp4     istio-system       10.244.2.3 ambient-worker        TCP
istiod-747687bbb6-5f8bw                   istio-system       10.244.1.2 ambient-worker2       TCP
local-path-provisioner-9cd9bd544-lzwx6    local-path-storage 10.244.0.4 ambient-control-plane TCP
sleep-66b946687b-ckfr7                    default            10.244.1.5 ambient-worker2       TCP
ztunnel-6fg5r                             istio-system       10.244.2.2 ambient-worker        TCP
ztunnel-shjbb                             istio-system       10.244.0.5 ambient-control-plane TCP
ztunnel-w7q9w                             istio-system       10.244.1.3 ambient-worker2       TCP
```

It works fine if I didn't do config dump before adding to ambient.

**Comment by linsun** [comment]
> The command is meant to display the config of the proxy. Since the proxy has config for kube-system it should be displayed IMO. It would be far more confusing to _not_ display info the proxy knows about.
> 
> Note proxy-config is a low level debugging tool.

Could be useful to have a filter for system pods. Similar as how users can filter to see only HBONE protocol.

**Comment by linsun** [comment]
> Another issue i noticed with the config dump is that the info returned is stale. I think this is probably more important. for example, after I label my namespace for ambient, i am not seeing sleep or HW displayed as HBONE **IF I did config dump before i label the namespace for ambient**. Is there a refresh flag? I'd assume it should always return the latest info.
> 
> ```
> go run istioctl/cmd/istioctl/main.go proxy-config workload $ZTUNNEL.istio-system
> NAME                                      NAMESPACE          IP         NODE                  PROTOCOL
> coredns-6d4b75cb6d-2rmrg                  kube-system        10.244.0.2 ambient-control-plane TCP
> coredns-6d4b75cb6d-q86k8                  kube-system        10.244.0.3 ambient-control-plane TCP
> helloworld-v1-cross-node-55446d46d8-vrbmx default            10.244.2.4 ambient-worker        TCP
> helloworld-v2-same-node-65bd845857-b6zwh  default            10.244.1.4 ambient-worker2       TCP
> istio-ingressgateway-8494dc7655-zpgp4     istio-system       10.244.2.3 ambient-worker        TCP
> istiod-747687bbb6-5f8bw                   istio-system       10.244.1.2 ambient-worker2       TCP
> local-path-provisioner-9cd9bd544-lzwx6    local-path-storage 10.244.0.4 ambient-control-plane TCP
> sleep-66b946687b-ckfr7                    default            10.244.1.5 ambient-worker2       TCP
> ztunnel-6fg5r                             istio-system       10.244.2.2 ambient-worker        TCP
> ztunnel-shjbb                             istio-system       10.244.0.5 ambient-control-plane TCP
> ztunnel-w7q9w                             istio-system       10.244.1.3 ambient-worker2       TCP
> ```
> 
> It works fine if I didn't do config dump before adding sleep or hw to ambient.

May be related to label ambient after pods are deployed.

**Comment by howardjohn** [comment]
We don't have the same filter for sidecars is my main concern.

>  the info returned is stale. 

Interesting, would be good to check if its an issue with istioctl or ztunnel. Probably ztunnel

**Comment by linsun** [comment]
I deleted sleep and hw and redeployed it, now I am getting dups in config dump:

```
go run istioctl/cmd/istioctl/main.go proxy-config workload $ZTUNNEL2.istio-system
NAME                                      NAMESPACE    IP         NODE                  PROTOCOL
helloworld-v1-cross-node-55446d46d8-dztgx default      10.244.2.5 ambient-worker        HBONE
helloworld-v1-cross-node-55446d46d8-vrbmx default      10.244.2.4 ambient-worker        HBONE
helloworld-v2-same-node-65bd845857-b6zwh  default      10.244.1.4 ambient-worker2       HBONE
helloworld-v2-same-node-65bd845857-gmlqg  default      10.244.1.6 ambient-worker2       HBONE
istio-ingressgateway-8494dc7655-zpgp4     istio-system 10.244.2.3 ambient-worker        TCP
istiod-747687bbb6-5f8bw                   istio-system 10.244.1.2 ambient-worker2       TCP
sleep-66b946687b-9n8nf                    default      10.244.1.7 ambient-worker2       HBONE
ztunnel-6fg5r                             istio-system 10.244.2.2 ambient-worker        TCP
ztunnel-shjbb                             istio-system 10.244.0.5 ambient-control-plane TCP
ztunnel-w7q9w                             istio-system 10.244.1.3 ambient-worker2       TCP
 ~/go/src/istio.io/istio/ [experimental-ambient+] go run istioctl/cmd/istioctl/main.go proxy-config workloads --file ztunnel-config.json
 ~/go/src/istio.io/istio/ [experimental-ambient+] k get pod
NAME                                        READY   STATUS    RESTARTS   AGE
helloworld-v1-cross-node-55446d46d8-dztgx   1/1     Running   0          3m34s
helloworld-v2-same-node-65bd845857-gmlqg    1/1     Running   0          3m34s
sleep-66b946687b-9n8nf                      1/1     Running   0          3m34s
```

**Comment by GregHanson** [comment]
Resolved by https://github.com/istio/istio/pull/42682 and https://github.com/istio/istio/pull/42547
