### ISSUE TITLE
metric "istio_requests_total" got a peak and then recovered

### ISSUE THREAD

**Issue by vvxxvvxx** [istio/istio#42419]
### Bug Description

At some point, the result from metric `istio_requests_total` got a peak (width of the peak is about 30s), and then recovered to its original value right away. You could see from below, from many istio proxies of different pods, the metric `istio_requests_total` result all got the peak at the same time and then recovered. The pod instances were the same instances. they were not restarted.

Do you know why the istio requests number got increased and decreased to the original value? 

![image](https://user-images.githubusercontent.com/48271609/207269470-b3822a9d-a41e-4103-8835-7e72d5c18034.png)

same if using metric `istio_request_duration_milliseconds_count`.
![image](https://user-images.githubusercontent.com/48271609/207270154-0dd7aec7-6f00-4bb5-a3d1-6cb6bf6122c1.png)

### Version

```prose
1.15.3
```

**Comment by howardjohn** [comment]
Are you sure its not just weird aggregation math from Prometheus ? or was istio-proxy returning a higher value?

**Comment by vvxxvvxx** [comment]
> Are you sure its not just weird aggregation math from Prometheus ? or was istio-proxy returning a higher value?

It's a raw result from istio_requests_total. and this metric is a counter, why does it have a peak for a counter?

**Comment by howardjohn** [comment]
The question really is whether the graph is wrong or whether Istio *actually* reported that giant number. If it's the former there isn't much we can do from Istio..

**Comment by vvxxvvxx** [comment]
> The question really is whether the graph is wrong or whether Istio _actually_ reported that giant number. If it's the former there isn't much we can do from Istio..

no aggregation for  istio_requests_total (that shoot label is a label we added to the raw metric to indicate from which cluster)..

**Comment by howardjohn** [comment]
That doesn't mean the graph is accurate, it could just as easily be a bug in grafana graphing. Not trying to shift blame here but it seems more plausible given graphs commonly have artifacts like this (never seen this one particularly, but similar).

Maybe you can zoom in on the timeframe and turn off all the smoothing etc (so it shows raw data points)?

**Comment by vvxxvvxx** [comment]
Hi @howardjohn, I chose one specific destination_service and zoom in (the peak happened at around 13:50 13th of Dec 2022 my time). you could see the graph below. this peak happened on almost all the services at the same time.

![image](https://user-images.githubusercontent.com/48271609/207503772-e9a6959c-5bd5-401a-8674-74cf98e00b9f.png)
