### ISSUE TITLE
Helm deployment of Istio ingress gateway does not provide a way to configure gateway's TLS certificate Subject/CommonName

### ISSUE THREAD

**Issue by shabharg** [istio/istio#42414]
### Bug Description

**Istio (v1.16.0) deployment is done via helm charts** as per the documentation:
https://istio.io/latest/docs/setup/install/helm/

Istio Helm charts repo location v1.16.0: 
https://istio-release.storage.googleapis.com/charts

```
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
kubectl create namespace istio-system
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod -n istio-system --wait
kubectl create namespace istio-ingress
kubectl label namespace istio-ingress istio-injection=enabled
helm install istio-ingress istio/gateway -n istio-ingress --wait
```

After the deployment completes, connect to the ingress-gateway LoadBalancer IP and dump the certificate subject using openssl command. The TLS certificate Subject is empty. With mutual TLS STRICT mode enabled will make the external TLS clients to fail to connect to ingress gateway as follows:
```
$ curl --cert client.crt --key client.key --cacert cacert.crt https://10.14.33.0:<portNo>/
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.

$ kubectl get svc -n istio-ingress
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                  AGE
istio-ingress   LoadBalancer   10.11.11.16   10.14.33.0    443:31015/TCP   38m
$ 
$ openssl s_client -connect 10.14.33.0:<portNo>
$ openssl s_client -connect 10.4.233.0:9527 2>/dev/null | grep -A24 'Server certificate' 
Server certificate
-----BEGIN CERTIFICATE-----
MIIDZDCCAkygAwIBAgIQDXNt1KGajOgCpaRMT3BdPzANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIyMTIxMzA0NDQ1MloXDTIyMTIx
NDA0NDY1MlowADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANna4yn1
V1sAdiXZW5UKMcCbm3MV9EpnR81o4DMCvufq1O7Aq+CIPdfOoRme3Li6Pxt29Xxe
SRTF1/D5Ls2zsC6VW6qFfVVr5naTmCOhWWANiLEpz7xYtpYwzFVe5oFD8owW8GZv
Jb7pSREojafm7dxF2Irv56qn5NQK7B4RIhZhzY3tAqsZ0TMQQmvDlzU2GixUNScf
UWzhElzvTR02AcGFSAFwY9A8W6mIKz49mY02eal6FRLoxP70NjTzL7He00mN39mM
h9uKWf3dEbbZNILC1E91EiGqE0xjjEpd7y0iUaIjIMp5kkEV2qXe01PnNmU/tpcl
XbWIfVvrjZGKcekCAwEAAaOBwTCBvjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAU
kwRiTP7Zc2bSgSNNzFF6hrASKc4wXgYDVR0RAQH/BFQwUoZQc3BpZmZlOi8vY2x1
c3Rlci5sb2NhbC9ucy9wdWxzYXIvc2EvcHVsc2FyLXNuLXBsYXRmb3JtLXN0cmVh
bW5hdGl2ZS1jb25zb2xlLWFjY3QwDQYJKoZIhvcNAQELBQADggEBALY5lTxrnqKl
at2WUXp/QykDERCBwUR5V9JLjs9GHcuy8LYFjc8NxbA2l4tW3SIWe4wqpYy4gE/t
Yt6kwPvqw00DwwpfYBanIqqcu4SvppNKLKXuK0HisLhKQ5YEE1d/IGF8CZbnmzAo
NJ+9MIU4v7ZRw1Qn66IfBosfKZ3IIzcoP7KwVeDix2f/7SmwjjE+7A+56gnf8EHo
Fa9LW6oWR+fm+MrQan0kciXAVScNaMfiFiOXHu+9ShAiYueAH6OcKBwBxG4YmXrp
WHZYZ/AHjSVE4jo7YmR2ulkooiN2n0yIm2cy5JeqIp6TZZFI3mKMbrtukvqKuotV
GAlA7jsF1Yk=
-----END CERTIFICATE-----
subject=
issuer=/O=cluster.local
---
```

Notice the "subject=" is empty and not populated. There has to be a way to specify the host value of the ingress gateway TLS certificate when deployed with helm charts.

Searched all the documentation to configure hostname on the istio (v1.16.0) ingress-gateway when deployed with helm charts and there is no way to specify the hostname on the TLS certificate of istio-ingress-gateway.

### Version

```prose
$ kubectl version --short
Client Version: v1.23.10
Server Version: v1.23.10
$ helm version --short
v3.7.1+g1d11fcb
$
```

### Additional Information

The deployment solely uses helm charts for istio/base, istio/istiod and istio/gateway (for ingress-gateway). 
**The deployment does not use istioctl**

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
TLS is configured using a `Gateway` object. This is done _after_ installing. https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

**Comment by shabharg** [comment]
Thanks for looking. The provided link does not point to the helm chart installation way.

Installation using Helm chart is key for automated deployment and ISTIO adoption.

Is there an agreement, this is a gap with the current ingress-gateway helm chart installation with "Gateway" object?
