### ISSUE TITLE
[Version 1.16.x] The "istio_requests_total" metric is not exposed.

### ISSUE THREAD

**Issue by Myeongseok-Kim** [istio/istio#42428]
### Bug Description

I have 2 k8s clusters. 
I am running istio with the same config on 2 clusters.(Install with istio-operator)
When upgrading istio version from 1.15.3 to 1.16.1 on 2 clusters, "istio_requests_total" metric is not appearing on 1 cluster.
Downgrading to version 1.15.3 exposes metrics again.

### Version 1.15.3
- All metrics are available.
![image](https://user-images.githubusercontent.com/54100684/207312240-2386631e-1dd9-4b28-9723-955d32b745b6.png)

### Version 1.16.1 (Version 1.16.0 is also)
![image](https://user-images.githubusercontent.com/54100684/207315140-e3953fb4-a824-4126-92c3-d91e017f5c1f.png)

![image](https://user-images.githubusercontent.com/54100684/207315745-1305e17e-d01b-4b2d-b2b7-8a98a0ab1531.png)

### Version

```prose
#istioctl version                                                                                                                                                   
client version: 1.15.3
control plane version: 1.16.1
data plane version: 1.15.3 (30 proxies), 1.16.1 (4 proxies)

#kubectl version --short                                                                                                                                             
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.22.15-eks-fb459a0
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/10217692/bug-report.tar.gz)

**Comment by zufardhiyaulhaq** [comment]
@Myeongseok-Kim I think you need traffic to get `istio_requests_total`, did you already test calling your service via the new gateway in 1.16?

**Comment by Myeongseok-Kim** [comment]
@zufardhiyaulhaq Yes, I am using curl to keep calling it.
It keeps calling in the process of upgrading from 1.15.3 to 1.16.x version.
When the upgrade is complete and the istio version is 1.16.x, the "istio_requests_total" metric will disappear.

![image](https://user-images.githubusercontent.com/54100684/207469985-b7e7d7bf-5278-4b43-a004-0798f6a641e9.png)
![image](https://user-images.githubusercontent.com/54100684/207470064-b2176dae-e47c-42b4-970c-bb291b1d2831.png)

**Comment by zirain** [comment]
you directly change the image version without `istioctl upgrade/install`?

**Comment by Myeongseok-Kim** [comment]
> you directly change the image version without `istioctl upgrade/install`?
> 
> if so, you should check the EnvoyFilter in istio-system, like following
> 
> ```
>     - applyTo: HTTP_FILTER
>       match:
>         context: SIDECAR_OUTBOUND
>         proxy:
>           proxyVersion: '^1\.16.*'
>         listener:
>           filterChain:
>             filter:
>               name: "envoy.filters.network.http_connection_manager"
>               subFilter:
>                 name: "envoy.filters.http.router"
> ```


I upgraded using istio-operator.
When I checked the envoy filter, I found that the filter below does not exist.
stats-filter-1.16
stats-filter-1.17

After adding the envoy filter it works fine.
Thanks for your help.
