### ISSUE TITLE
 Using CNAME records on DNS to map traffic to Istio ingress

### ISSUE THREAD

**Issue by arshiamalek** [istio/istio#42434]
We have a cluster running on GCP, with Istio ingress set up on it.

We are currently in a process of adding a DNS record to map from `example.site2.com` to `example.site1.com`. We have setup the gateway currently withe following config:

```
  Hosts:
      *.example.site1.com
    Port:
      Name:      https-wc
      Number:    443
      Protocol:  HTTPS
    Tls:
      Credential Name:  ingressgateway-wc-certs
      Mode:             SIMPLE
    Hosts:
      example.site1.com
    Port:
      Name:      https-base
      Number:    443
      Protocol:  HTTPS
```

We currently have an **_A record_** which is mapping `*.example.site1.com `to the ingress external IP address. Our intention is to map all traffic from `example.site2.com` to `example.site1.com`. Currently we get an NR (Not DestinationRule or VirtualService) error when visiting `example.site2.com`. Is this achievable?

**Comment by howardjohn** [comment]
*.example.site1.com doesn't match example.site2.com nor example.site1.com. not sure if that matches your real world usage though or just a mistake on example?

NR means either the request SNI or Host header isn't matching though, would be good to double check if the client were the host header to site1. I suspect most won't with a CNAME

**Comment by arshiamalek** [comment]
> *.example.site1.com doesn't match example.site2.com nor example.site1.com. not sure if that matches your real world usage though or just a mistake on example?
> 
> NR means either the request SNI or Host header isn't matching though, would be good to double check if the client were the host header to site1. I suspect most won't with a CNAME

@howardjohn No the current setup is the same as above with the wild cards and without the wild cards.  Not sure if this is possible at all with Istio? Basically using one domain to setup Istio and then using a CNAME record to map another domain to the original one (`example.site1.com` in our case).

**Comment by howardjohn** [comment]
The approach is fundamentally flawed. Its not an Istio issue.

Consider a dns record like so:

```
;; ANSWER SECTION:
cname.howardjohn.info.  29      IN      CNAME   blog.howardjohn.info.
blog.howardjohn.info.   59      IN      A       130.211.40.235
```

A client request:
```
$ curl https://cname.howardjohn.info -v
*   Trying 130.211.40.235:443...
* Connected to cname.howardjohn.info (130.211.40.235) port 443 (#0)
curl: (60) SSL: no alternative certificate subject name matches target host name 'cname.howardjohn.info'
``

If we ignore the TLS error (maybe you have a wildcard cert, so it works for your case):

```
$ curl https://cname.howardjohn.info -vk
* Trying 130.211.40.235:443...
* Connected to cname.howardjohn.info (130.211.40.235) port 443 (#0)

> GET / HTTP/2
> Host: cname.howardjohn.info
> user-agent: curl/7.86.0
> accept: */*
```

You can see in the request, everything is "cname.howardjohn.info". The istio ingress will not see anything about "site1" in your case.

You need to actually match against the names that *clients will use*. This is fundamentally how HTTP and TLS work, not Istio specific.

**Comment by arshiamalek** [comment]
Thanks for your explanation @howardjohn - I understand the behaviour and issue now

So I believe the only way to overcome this is to define a virtual service for `example.site2.com` which maps to the correct service on the cluster? (Assuming that `example.site2.com` has valid certs)

**Comment by howardjohn** [comment]
Yes
