### ISSUE TITLE
Istio ConsistentHash load balancing with http cookie and multi-cluster service mesh does not work

### ISSUE THREAD

**Issue by aeidt4** [istio/istio#42432]
### Bug Description

We have a multi-primary cluster service mesh and have a destination rule to route traffic to a pod based on the JSESSIONID cookie. When the pods in one cluster are shutdown the following error is given when the request lands on the cluster without the pods:
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer

Istio: 1.14.1

### Version

```prose
[root@docker-build aeidt4]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (4 proxies)
```

**Comment by hzxuzhonghu** [comment]
Need more info like what is the traffic flow like : from ingress gateway or eeast-west traffic?

What is the underlying network: flat or non flat?

**Comment by aeidt4** [comment]
east west gateway is used for cross cluster traffic. Requests for the app running in pods comes into the ingress gateway, service mesh then routes the traffic to the cluster that has running pods for that application. We can see the traffic coming into cluster 1 (deployment exists but no running pods) but it does not get routed to cluster 2 pods.
If we remove the following from the destination rule on cluster 1 then all traffic is correctly routed to cluster 2.

consistentHash:
        httpCookie:
          name: JSESSIONID
          ttl: 0s
