### ISSUE TITLE
TestXdsProxyStatus flake: race condition in connection

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42448]
Example failure: https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-istiodremote_istio_postsubmit/1603073904690073600

What happens is we  connect right when the envoy disconnects:
```
2022-12-14T17:12:24.206075Z	info	ads	ADS: "10.10.0.1:46877" a-v1-b586f6cd6-pq4k6.echo-2-70070-9 terminated
2022-12-14T17:12:24.237223Z	info	ads	ADS: new connection for node:test-1.default-39
2022-12-14T17:12:24.237314Z	info	ads	istio.io/debug/config_dump failed: config dump could not find connection for proxyID "a-v1-b586f6cd6-pq4k6.echo-2-70070"
```

So we miss it.

Two issues:
1. This happens in the first place
2. When it does, istioctl just waits forever. It should get an error from istiod and fail-fast.

https://storage.googleapis.com/istio-prow/logs/integ-pilot-istiodremote_istio_postsubmit/1603073904690073600/artifacts/pilot-66ca573e3ac14f99892a261d1/TestXdsProxyStatus/_test_context/istio-state3616665471/externalistiod-1/istiod-57f56bf68d-bf68n_discovery.log

**Comment by howardjohn** [comment]
cc @ingwonsong

**Comment by ingwonsong** [comment]
> 1. This happens in the first place

Can you explain a bit more? I could not understand.

**Comment by howardjohn** [comment]
I mean this probably should be fixed so we don't have the race condition? or at least it should be transparently retried or something

**Comment by hzxuzhonghu** [comment]
Is it the test or pilot itself race

**Comment by hanxiaop** [comment]
not stale

**Comment by howardjohn** [comment]
afaik not fixed
