### ISSUE TITLE
istioctl manifest: override default k8s version per Istio version

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42441]
We have code that detects k8s version and mutates helm charts. Without `--cluster-specific`, we fallback to helm DefaultCapabilities in `istioctl manifest`: https://github.com/helm/helm/blob/3636f6824757ff734cb265b8770efe48c1fb3737/pkg/chartutil/capabilities.go#L34-L41

We should define this ourself. The helm actually does this, just only in the binary, not the library: https://github.com/helm/helm/issues/11639

Example issue caused by this: https://github.com/istio/istio/issues/42423

---

Proposal:

* Define "min supported version" constant on each release
  * Min is used, instead of max, since its less likely to break things
* Override DefaultCapabilities to use this

**Comment by zufardhiyaulhaq** [comment]
@howardjohn can you provide an example code that is using the helm library?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/81640140d93c25d9e68271b5c8ea17db17b2c1c8/operator/pkg/helm/helm.go#L113
