### ISSUE TITLE
Need config dump for xDS workload resources from Istiod perspective

### ISSUE THREAD

**Issue by linsun** [istio/istio#42443]
**Describe the feature request**

During discussion of https://github.com/istio/istio/issues/42410, we realized what ztunnel knows may be out of date from what Istiod control plane knows and sends. Unfortunately, there is no easy way to dump the config from istiod. We should at least provide some way for us to easily troubleshoot the prob.

**Describe alternatives you've considered**

view workload xDS from control plane: curl localhost:8080/debug/ambientz  on istiod pod shows very limited data, e.g. not showing if hbone is supported.

**Affected product area (please put an X in all that apply)**

[ x ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
cc @howardjohn if you want to add anything

**Comment by howardjohn** [comment]
Just would add it should be added to the /config_dump interface, not a new one. The idea is to make that support all types. We can probably have it detect the types based on the client (we know its ztunnel, use workload)

**Comment by GregHanson** [comment]
WDS added to configdump for ztunnel proxies in https://github.com/istio/istio/pull/42547
