### ISSUE TITLE
Move waypoints to Delta XDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42457]
This involves two parts:
* Just flipping the switch and making things work
* Actually optimizing things to incrementally update

**Comment by howardjohn** [comment]
part 1 is done, but we need second aspect

**Comment by keithmattix** [comment]
Not stale

**Comment by hanxiaop** [comment]
not stale

**Comment by hzxuzhonghu** [comment]
should be finished since we all moved toward delta xds

**Comment by howardjohn** [comment]
We are missing the "Actually optimizing things to incrementally update" part. But i will open a new issue
