### ISSUE TITLE
"istio-cni": netplugin failed

### ISSUE THREAD

**Issue by suhasagasthya** [istio/istio#42485]
### Bug Description

On the recent OKD release, istio sidecar injection is failing on CNI with the below error (attached logs at the end). This issues started to occur from OKD release - 4.11.0-0.okd-2022-12-02-145640 only. 
Istio was working fine on the previous version - 4.11.0-0.okd-2022-11-19-050030

We are using Istio along with the default Openshift-SDN networking. Istio is an operator based install using istioctl operator init and the control-plane is configured using the IstioOperator Object

Config - 

> apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: openshift
  values:
    gateways:
      istio-ingressgateway:
        runAsRoot: true
    global:
      imagePullPolicy: Always
    sidecarInjectorWebhook:
      neverInjectSelector:
      - matchExpressions:
        - key: openshift.io/deployer-pod-for.name
          operator: Exists
    cni:
      psp_cluster_role: enabled
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      chained: false
      excludeNamespaces:
        - istio-system
        - kube-system
  components:
    base:
      enabled: true
    cni:
      enabled: enabled
      namespace: kube-system
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.hostNetwork
                  value: true
                - path: spec.template.spec.dnsPolicy
                  value: ClusterFirstWithHostNet
                - path: spec.template.spec.containers.[name:istio-proxy].securityContext.privileged
                  value: true
                - path: spec.template.spec.containers.[name:istio-proxy].securityContext.allowPrivilegeEscalation
                  value: true
          nodeSelector:
            kubernetes.io/nodetype: istio-ingress
          hpaSpec:
            maxReplicas: 2
            minReplicas: 2
          service:
            ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 80
            - name: https
              port: 443
              targetPort: 443
            - name: tcp-istiod
              port: 15012
              targetPort: 15012
            - name: tls
              port: 15443
              targetPort: 15443
            - name: rsync
              port: 873
              targetPort: 8773
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 2
            minReplicas: 2
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2

Observations - 
1. The CNI based istio sidecar injection fails with this permission denied error on invoking the iptables-restore command
2. The sidecar istio-init without using CNI works fine, but as expected this required privileged access on the openshift project that the sidecar injection is enabled on. 

Affected istio versions - 
All the way from 1.13.2 to 1.16.1, i tried upgrading istio versions but that initial version was not the cause of CNI netplugin failing. 

Logs - 
`(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_nginx-test-86cc9b4bd9-qq7b6_suhas-playground_fa85a3f5-84df-4b1b-9b1b-058c0d222c60_0(180efa9d049ff2e60f5f808f17be5194722448bccb0f0e26569e5d2aad2b9fce): error adding pod suhas-playground_nginx-test-86cc9b4bd9-qq7b6 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [suhas-playground/nginx-test-86cc9b4bd9-qq7b6/fa85a3f5-84df-4b1b-9b1b-058c0d222c60:istio-cni]: error adding container to network "istio-cni": netplugin failed: "{"level":"info","time":"2022-12-16T07:20:29.481660Z","msg":"istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:nginx-test-86cc9b4bd9-qq7b6 K8S_POD_NAMESPACE:suhas-playground K8S_POD_INFRA_CONTAINER_ID:180efa9d049ff2e60f5f808f17be5194722448bccb0f0e26569e5d2aad2b9fce}"}n{"level":"info","time":"2022-12-16T07:20:29.497535Z","msg":"============= Start iptables configuration for nginx-test-86cc9b4bd9-qq7b6 ============="}n{"level":"info","time":"2022-12-16T07:20:29.497727Z","msg":"Istio iptables environment:nENVOY_PORT=nINBOUND_CAPTURE_PORT=nISTIO_INBOUND_INTERCEPTION_MODE=nISTIO_INBOUND_TPROXY_ROUTE_TABLE=nISTIO_INBOUND_PORTS=nISTIO_OUTBOUND_PORTS=nISTIO_LOCAL_EXCLUDE_PORTS=nISTIO_EXCLUDE_INTERFACES=nISTIO_SERVICE_CIDR=nISTIO_SERVICE_EXCLUDE_CIDR=nISTIO_META_DNS_CAPTURE=nINVALID_DROP=n"}n{"level":"info","time":"2022-12-16T07:20:29.497772Z","msg":"Istio iptables variables:nPROXY_PORT=15001nPROXY_INBOUND_CAPTURE_PORT=15006nPROXY_TUNNEL_PORT=15008nPROXY_UID=1337nPROXY_GID=1337nINBOUND_INTERCEPTION_MODE=REDIRECTnINBOUND_TPROXY_MARK=1337nINBOUND_TPROXY_ROUTE_TABLE=133nINBOUND_PORTS_INCLUDE=*nINBOUND_PORTS_EXCLUDE=15020,15021,15090nOUTBOUND_OWNER_GROUPS_INCLUDE=*nOUTBOUND_OWNER_GROUPS_EXCLUDE=nOUTBOUND_IP_RANGES_INCLUDE=*nOUTBOUND_IP_RANGES_EXCLUDE=nOUTBOUND_PORTS_INCLUDE=nOUTBOUND_PORTS_EXCLUDE=15020nKUBE_VIRT_INTERFACES=nENABLE_INBOUND_IPV6=falsenDNS_CAPTURE=falsenDROP_INVALID=falsenCAPTURE_ALL_DNS=falsenDNS_SERVERS=[],[]nOUTPUT_PATH=nNETWORK_NAMESPACE=/var/run/netns/607ac6a4-3a5d-4ec8-90d9-ce2fe8c43ce3nCNI_MODE=truenHOST_NSENTER_EXEC=falsenEXCLUDE_INTERFACES=n"}n{"level":"info","time":"2022-12-16T07:20:29.497854Z","msg":"Writing following contents to rules file: /tmp/iptables-rules-1671175229497830041.txt1486128977n* natn-N ISTIO_INBOUNDn-N ISTIO_REDIRECTn-N ISTIO_IN_REDIRECTn-N ISTIO_OUTPUTn-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURNn-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001n-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006n-A PREROUTING -p tcp -j ISTIO_INBOUNDn-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURNn-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURNn-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURNn-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECTn-A OUTPUT -p tcp -j ISTIO_OUTPUTn-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURNn-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURNn-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECTn-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURNn-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURNn-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECTn-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURNn-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURNn-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURNn-A ISTIO_OUTPUT -j ISTIO_REDIRECTnCOMMIT"}n{"level":"info","time":"2022-12-16T07:20:29.497884Z","msg":"Running command: iptables-restore --noflush /tmp/iptables-rules-1671175229497830041.txt1486128977"}n{"level":"error","time":"2022-12-16T07:20:29.499676Z","msg":"Command error output: xtables other problem: Permission denied"}n{"level":"error","time":"2022-12-16T07:20:29.499693Z","msg":"Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1671175229497830041.txt1486128977, exit status 1"}n"`

### Version

```prose
➜ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (4 proxies)

➜ kubectl version
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2568+56584349e9412b-dirty", GitCommit:"56584349e9412bc46cae8fe3107cae21eb7cb69a", GitTreeState:"dirty", BuildDate:"2022-11-09T10:38:57Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}

➜ oc version
Client Version: v4.2.0-alpha.0-1570-g3c85519
Kustomize Version: v4.5.4
Server Version: 4.11.0-0.okd-2022-12-02-145640
Kubernetes Version: v1.24.0-2568+56584349e9412b-dirty

The worker nodes are running FCOS - 
OSTREE_VERSION='411.36.202212021443-0'
Fedora release 36 (Thirty Six)
Fedora release 36 (Thirty Six)

sh-5.2# iptables -V
iptables v1.8.7 (nf_tables)

sh-5.2# iptables-restore -V
iptables-restore v1.8.7 (nf_tables)

Node Kernel Version - 6.0.10-200.fc36.x86_64
cri-o://1.24.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by Unfaced85** [comment]
Thanks for reporting, we encountered the same issue when upgrading OKD from Version 4.11-2022-10-28 to 4.11-2022-12-02

Our Error looks like this: 

`(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_athena-ecds-8c45f8fdf-nhzdx_prod01-ecds_8e88b33f-1d01-43fa-8374-ad7bc14bae3a_0(3623cba36a0d1e81959386400a3db1516736d585111de356f6ce8785d713d907): error adding pod prod01-ecds_athena-ecds-8c45f8fdf-nhzdx to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [prod01-ecds/athena-ecds-8c45f8fdf-nhzdx/8e88b33f-1d01-43fa-8374-ad7bc14bae3a:v2-3-istio-cni]: error adding container to network "v2-3-istio-cni": netplugin failed: "{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.949799Z\",\"msg\":\"istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:athena-ecds-8c45f8fdf-nhzdx K8S_POD_NAMESPACE:prod01-ecds K8S_POD_INFRA_CONTAINER_ID:3623cba36a0d1e81959386400a3db1516736d585111de356f6ce8785d713d907}\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.966929Z\",\"msg\":\"============= Start iptables configuration for athena-ecds-8c45f8fdf-nhzdx =============\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.967171Z\",\"msg\":\"Istio iptables environment:\\nENVOY_PORT=\\nINBOUND_CAPTURE_PORT=\\nISTIO_INBOUND_INTERCEPTION_MODE=\\nISTIO_INBOUND_TPROXY_ROUTE_TABLE=\\nISTIO_INBOUND_PORTS=\\nISTIO_OUTBOUND_PORTS=\\nISTIO_LOCAL_EXCLUDE_PORTS=\\nISTIO_EXCLUDE_INTERFACES=\\nISTIO_SERVICE_CIDR=\\nISTIO_SERVICE_EXCLUDE_CIDR=\\nISTIO_META_DNS_CAPTURE=\\nINVALID_DROP=\\n\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.967222Z\",\"msg\":\"Istio iptables variables:\\nPROXY_PORT=15001\\nPROXY_INBOUND_CAPTURE_PORT=15006\\nPROXY_TUNNEL_PORT=15008\\nPROXY_UID=1000940001\\nPROXY_GID=1000940001\\nINBOUND_INTERCEPTION_MODE=REDIRECT\\nINBOUND_TPROXY_MARK=1337\\nINBOUND_TPROXY_ROUTE_TABLE=133\\nINBOUND_PORTS_INCLUDE=*\\nINBOUND_PORTS_EXCLUDE=15090,15021,15020\\nOUTBOUND_OWNER_GROUPS_INCLUDE=*\\nOUTBOUND_OWNER_GROUPS_EXCLUDE=\\nOUTBOUND_IP_RANGES_INCLUDE=*\\nOUTBOUND_IP_RANGES_EXCLUDE=\\nOUTBOUND_PORTS_INCLUDE=\\nOUTBOUND_PORTS_EXCLUDE=15020\\nKUBE_VIRT_INTERFACES=\\nENABLE_INBOUND_IPV6=false\\nDNS_CAPTURE=true\\nDROP_INVALID=false\\nCAPTURE_ALL_DNS=true\\nDNS_SERVERS=[],[]\\nOUTPUT_PATH=\\nNETWORK_NAMESPACE=/var/run/netns/928bb619-f9dc-45d5-884a-a007c00e0be7\\nCNI_MODE=true\\nEXCLUDE_INTERFACES=\\n\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.967310Z\",\"msg\":\"Writing following contents to rules file: /tmp/iptables-rules-1671611976967286129.txt748662832\\n* nat\\n-N ISTIO_INBOUND\\n-N ISTIO_REDIRECT\\n-N ISTIO_IN_REDIRECT\\n-N ISTIO_OUTPUT\\n-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN\\n-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001\\n-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006\\n-A PREROUTING -p tcp -j ISTIO_INBOUND\\n-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN\\n-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT\\n-A OUTPUT -p tcp -j ISTIO_OUTPUT\\n-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN\\n-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -p tcp ! --dport 53 -m owner --uid-owner 1000940001 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --uid-owner 1000940001 -j RETURN\\n-A ISTIO_OUTPUT -m owner --uid-owner 1000940001 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1000940001 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -p tcp ! --dport 53 -m owner ! --gid-owner 1000940001 -j RETURN\\n-A ISTIO_OUTPUT -m owner --gid-owner 1000940001 -j RETURN\\n-A ISTIO_OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 15053\\n-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\\n-A ISTIO_OUTPUT -j ISTIO_REDIRECT\\n-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1000940001 -j RETURN\\n-A OUTPUT -p udp --dport 53 -m owner --gid-owner 1000940001 -j RETURN\\n-A OUTPUT -p udp --dport 53 -j REDIRECT --to-port 15053\\nCOMMIT\\n* raw\\n-A OUTPUT -p udp --dport 53 -m owner --uid-owner 1000940001 -j CT --zone 1\\n-A OUTPUT -p udp --sport 15053 -m owner --uid-owner 1000940001 -j CT --zone 2\\n-A OUTPUT -p udp --dport 53 -m owner --gid-owner 1000940001 -j CT --zone 1\\n-A OUTPUT -p udp --sport 15053 -m owner --gid-owner 1000940001 -j CT --zone 2\\n-A OUTPUT -p udp --dport 53 -j CT --zone 2\\n-A PREROUTING -p udp --sport 53 -j CT --zone 1\\nCOMMIT\"}\n{\"level\":\"info\",\"time\":\"2022-12-21T08:39:36.967353Z\",\"msg\":\"Running command: nsenter --net=/var/run/netns/928bb619-f9dc-45d5-884a-a007c00e0be7 -- iptables-restore --noflush /tmp/iptables-rules-1671611976967286129.txt748662832\"}\n{\"level\":\"error\",\"time\":\"2022-12-21T08:39:36.969371Z\",\"msg\":\"Command error output: xtables other problem: Permission denied\"}\n{\"level\":\"error\",\"time\":\"2022-12-21T08:39:36.969394Z\",\"msg\":\"Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1671611976967286129.txt748662832, exit status 1\"}\n"`

Any Input we can give helping resolve this issue please contact me, thanks

**Comment by Unfaced85** [comment]
Meanwhile we found out this is related to SELinux on the OKD Worker Nodes. if you do not have a production Cluster, you can try this workaround: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/nodes/working-with-nodes#nodes-nodes-kernel-arguments_nodes-nodes-jobs

and set enforce=0 to set SELinux into permissive mode. This makes istio working again.

Still we are not sure if this is an issue due to a new flag in okd that istio needs to use or a bug in the new OKD Version.

**Comment by ormergi** [comment]
Hello, at [Kubevirt](https://github.com/kubevirt/kubevirt) CI we encounter similar errors on k8s-1.26 cluster with CentOS 9 Stream nodes (20221129.1).

Istio sidecar injection fail due to the mentioned error where istio-cni cannot access the iptables-rules temp file,
the full error can be found here 
https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.26-sig-network/1608395056304099328/artifacts/k8s-reporter/11_events.log

The nodes audit log shows the following denail message: 
```
$ sudo ausearch -i | grep -C 5 /tmp/iptables-rules-1671979149256747547.txt2829298292 
...
----
type=PROCTITLE msg=audit(12/25/2022 14:39:09.258:5494) : proctitle=iptables-restore --noflush /tmp/iptables-rules-1671979149256747547.txt2829298292 
type=SYSCALL msg=audit(12/25/2022 14:39:09.258:5494) : arch=x86_64 syscall=openat success=no exit=EACCES(Permission denied) a0=AT_FDCWD a1=0x7ffcc75c5b46 a2=O_RDONLY|O_CLOEXEC a3=0x0 items=0 ppid=149418 pid=149433 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=iptables-restor exe=/usr/sbin/xtables-nft-multi subj=system_u:system_r:iptables_t:s0 key=(null) 
type=AVC msg=audit(12/25/2022 14:39:09.258:5494) : avc:  denied  { open } for  pid=149433 comm=iptables-restor path=/tmp/iptables-rules-1671979149256747547.txt2829298292 dev="vda1" ino=532379 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=file permissive=0 
----
```

Istio Operator CR:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
  hub: quay.io/kubevirtci
  profile: demo
  values:
    cni:
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: debug
      privileged: true
    global:
      jwtPolicy: first-party-jwt
status:
  componentStatus:
    Base:
      status: HEALTHY
    Cni:
      status: HEALTHY
    EgressGateways:
      status: HEALTHY
    IngressGateways:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY
```

K8S version k8s-1.26
Nodes OS:  CentOS 9 Stream nodes (20221129.1)
Istio version: 1.15.0

**Comment by luksa** [comment]
I believe this is the same SELinux issue we're seeing on RHEL9. In our case, `iptables-restore` is not allowed to read files in `/tmp`. The audit log show the following:
```
type=AVC msg=audit(1671679231.719:78743): avc:  denied  { open } for  pid=703303 comm="iptables-restor" path="/tmp/iptables-rules-1671679231719103294.txt128242135" dev="vda1" ino=535228 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=file permissive=0
```

I'll submit a fix shortly.

**Comment by ormergi** [comment]
@luksa thanks for fixing this :) 
When we will be able to consume this fix?

**Comment by Unfaced85** [comment]
would also like to know this - we are using istio via operator version 2.3 at the moment

**Comment by luksa** [comment]
@ormergi The fix is currently only in the current master branch, so should be released in Istio 1.18. 

@Unfaced85 in OSSM, we are back-porting this fix to 2.3.3.

**Comment by Unfaced85** [comment]
Thank you very much

**Comment by ormergi** [comment]
Thank you @luksa :slightly_smiling_face:

**Comment by Unfaced85** [comment]
@luksa do you have a rough estimate when we can expect OSSM 2.3.3? Do not want to pressure anyone, but for planning purposes it would be good to know, thank you.

**Comment by luksa** [comment]
@Unfaced85 it's already in the pipeline, so you can expect it next week, I think.

**Comment by douggutaby** [comment]
Hi,

The latest release is still 1.17.2. Will it be in the next latest release?

Thanks
