### ISSUE TITLE
CircuitBreaker -connectionpool maxConnection limit to destination and service client

### ISSUE THREAD

**Issue by ankitdiscovery** [istio/istio#42484]
i have istio service mesh with envoy proxy running as sidecar with each pod. with destinationrule below config
`    connectionPool:
      http:
        http1MaxPendingRequests: 1
      tcp:
        maxConnections: 5`

as per istio doc these limit are for service level but i could see after scaling less throttling happening.
lets suppose we have 4 replicas(pod ) of destination service total connections should be (4*5 =20 total connection to destination service).
is my understanding correct ?

and secondly, same connection limit should be applied to client poxy also ? i.e max 5 connection to destination service ?

**Comment by hzxuzhonghu** [comment]
duplicate with https://github.com/istio/istio/issues/42490
