### ISSUE TITLE
prometheus.yaml and servicegraph.yaml is missing in istio master branch

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#4248]
prometheus.yaml and servicegraph.yaml is missing in istio master branch.
However, the document still ask customers to use, as below
In https://istio.io/docs/tasks/telemetry/querying-metrics.html, use command
kubectl apply -f install/kubernetes/addons/prometheus.yaml

In https://istio.io/docs/tasks/telemetry/servicegraph.html, use command
kubectl apply -f install/kubernetes/addons/servicegraph.yaml

**Comment by mattdelco** [comment]
There's two possible answers, though I don't know which is more relevant for these docs: 1) the pages first say to install istio, so the files should be present in the tar files in a release on github, vs. 2) if you're building from source then the yaml files are generated by release/updateVersion.sh (easiest thing to run is "make generate_yaml" to create the files).

**Comment by johnzheng1975** [comment]
Correct, I find these files are in gitignore file. We should not add it manually.
They will be generated automatically by updateVersion.sh
