### ISSUE TITLE
Client-side authz

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#42497]
Istio defines authorization rules to be workload-bound, in the sense that the policy enforcement happens _after_ the load balancing decision (e.g. by a client sidecar). This is implemented by scoping policies to the pods during configuration generation, by checking the workload selector against the server sidecar.

With Waypoints, both load balancing and authorization must happen in the same proxy. A naive approach is to chain two filter chains for the load balancer (client) and the authorization (server) using internal listeners. That leads to an explosion of config because every virtual "workload" forces config to grow with mesh size rather than user config size.

A smarter approach is to push the workload selector into the policy itself, and then applying RBAC after the upstream host selection is done. That eliminates the need for a virtual "workload" listener, and drastically reduces the size of the base config (xDS is roughly the size of user config). The work is to enrich Envoy RBAC to support "workload selection" in the conditions and add an option to wait for the host selection before applying the RBAC.

**Comment by howardjohn** [comment]
This generally makes sense to me, but I would note there are a few other APIs that have similar workload selector and associated implications: ReqAuthn, WasmPlugin, and Telemetry. Not sure exactly what that will mean

**Comment by hzxuzhonghu** [comment]
Several questions
1.  With selector in policy, when will waypoint cal the target workload which a policy applies, on demand or using event trigger(this could be costy)
2. What will the selector based on? labels, names or something else.

IMO we can move this complex computing to control plane, while keep data plane lighter weight. 
Not sure if we can make use of a mechanism like ECDS here

**Comment by kyessenov** [comment]
@hzxuzhonghu 

1. I imagine envoy would not forward the request when policy applies (but still keep the endpoint in its pool). How it's done is not clear yet, but we'd need some way to bind labels to endpoints in EDS and some way to match policies against endpoint labels.

2. Istio authz allows arbitrary labels beyond just namespace. It's not expensive to match labels but it's costly to propagate those labels to the data plane. Istio doesn't put all pod labels anywhere in xDS at the moment.

I don't think it's that difficult to implement label in matching in Envoy (it already has subset matching via labels). But adding labels to xDS is a novel capability, which we need to decide on a method if we want to make any progress for this issue.
