### ISSUE TITLE
Istio sidecar for Pod with hostNetwork enabled

### ISSUE THREAD

**Issue by Yiadh** [istio/istio#42508]
In my k8s cluster there is a Pod (prometheus/node-exporter) that uses **hostNetwork** to collect metrics from a node. The same Pod sends collected data to Prometheus, which is a part of Istio service mesh. The service mesh requires all traffic to be secured by mTLS (we do not want to make any excuses).

Since the node-exporter uses hostNetwork it does not have a sidecar injected and it cannot take advantage of Istio mTLS.

I am wondering if I can enforce sidecar injection to node-exporter, so the traffic towards Istio service mesh is secured by mTLS without disrupting host network ?

```
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (188 proxies)

$ kubectl version --short
Client Version: v1.24.7
Kustomize Version: v4.5.4
Server Version: v1.24.7
```

**Comment by howardjohn** [comment]
We don't currently have a way to do this
