### ISSUE TITLE
Injecting lua scripts in istio-proxy container for envoy

### ISSUE THREAD

**Issue by argeualcantara** [istio/istio#4250]
[FEATURE REQUEST]
Currently the solution proposed [here](https://github.com/mandarjog/istioluawebhook) doesn't have a generic way to inject scripts inside the istio-proxy container.

Here's the problem contextualization: 

* I create a `default.lua` script that has envoy's on request and on response method signatures.
* The default script requires other files from a given path
* I need to download all the scripts (filters and libs) in the pod in order to run the `default.lua` with success

Current workaround:

* The function's bodies call another method that comes from the imported scripts. They're implemented by who will deploy the service (in this case me) and I had to add it to my namespace in a configmap.

This solution is not generic and adds complexity to the deployment. We were wondering what can be a good solution and have this suggestion:

* Create a init container that loads all the scripts that are required on the `default.lua` dynamically.
  * The init container is also responsible for mounting the scripts on a shared volume so istio-proxy container can get them.
* The script's URLs can be defined by env variables. (possibly github or http endpoint)
* The `default.lua` script will run the code from these mounted files.

1 - What you guys think about this?
2 - Is there any other way to get the scripts inside istio-proxy container?
3 - Do you guys see any other alternative or is anyone else working on this?
I'm more than willing to contribute and help you guys.

**Comment by mandarjog** [comment]
I like the idea of init container, however any change in the lua scripts would require restarting the pod which is not acceptable in many cases.

Config map mounts work well. They can be made part of the standard deployment. And updated are available to all pods dynamically.

**Comment by argeualcantara** [comment]
@mandarjog I tried chaging the header value in the configmap but the changes did't take effect

**Comment by nmnellis** [comment]
why not compress/generate the scripts into a single file that get injected into the sidecar? are these lua scripts overly large?

**Comment by argeualcantara** [comment]
@nmnellis, this is a possible solution, but does not solve the problem of getting the changes from the configmap without killing the pod, I was also thinking of creating another container which would check for changes in the configmap and force envoy to restart with changes done to the lua file

**Comment by nmnellis** [comment]
why use configmaps at all? the entire lua script can be provided inline within the envoy configuration.

**Comment by mandarjog** [comment]
Your scrip May have ‘requires’ that include local scripts.

You use config maps to provide seldom changing libraries. Use the filter to provide changeable scripts.

Even if you just change config maps, you need to force a change thru the script for envoy to reload files. So using config maps is still useful but is not a complete solution.

**Comment by argeualcantara** [comment]
@mandarjog How do I "force a change thru the script" because I did a change in the file inside the container but they didn't take effect.

**Comment by ZackButcher** [comment]
@rshriram I thought you were working on the design for Lua filter config specifically?

I'm planning to open source a simple xDS proxy server to allow custom Envoy config injection, as a replacement for the webhook based impl we shipped in 0.7. That at least partially addresses this use case, though I thought we wanted to address Lua specifically with first class support in Istio CRDs?
