### ISSUE TITLE
503 Upstream/Downstream error

### ISSUE THREAD

**Issue by chandukotagiri1992** [istio/istio#42525]
We are facing the 503 upstream/downstream connect reset error intermintelly for past few weeks,

![image](https://user-images.githubusercontent.com/83627564/208680221-128f672a-ded3-4592-85e3-ecf9b3e8ed4b.png)

![image](https://user-images.githubusercontent.com/83627564/208680520-8d7083b0-7151-42ac-8e6f-3a4899bbfe37.png)

Kubeflow version : 1.4.1
Azure Kubernetes Version : 1.21
Istio Version : 1.9
Knative version : v0.22.1

**Comment by hzxuzhonghu** [comment]
1.9 is EOL

**Comment by chandukotagiri1992** [comment]
Kubeflow version : 1.6.x
Azure Kubernetes Version : 1.24
Istio Version : 1.14
Knative version : v0.22.1

Even we are facing the same issue with above versions.

**Comment by neilcampbe11** [comment]
@chandukotagiri1992 Hi,

Did you manage to resolve this? I think I might have a similar issue.
