### ISSUE TITLE
mounting of /tmp by security driver causing make test to fail

### ISSUE THREAD

**Issue by john-a-joyce** [istio/istio#4252]
While trying to run "make test" on my local system the tests are not running properly due to lack of space. 
Getting numerous errors of the type:  "write /tmp/go-build095530034/b510/vet.cfg: no space left on device".  Notably when I change the size of the mounted partition in this line:
https://github.com/istio/istio/blame/master/security/cmd/flexvolume/driver/driver.go#L105
the tests executed without the "out of space" errors.   A couple other notable points.  
- Others in my group can run the tests just fine from the same code base, although their environments are different. 
- The /tmp partition is left mounted at the end of running "make test" on my system while I believe it should be unmounted by the driver.go code. 
- Before running the tests /tmp is not specifically mounted 
- Ubuntu release:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
- K8s version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by john-a-joyce** [comment]
cc @wattli

**Comment by wattli** [comment]
Thanks for filing this issue, @saurabh do you want to take a look at this issue? And I believe you are mount the driver to another dir, right?

**Comment by qiujian16** [comment]
get the same error when run make test

**Comment by saumoh** [comment]
i'll take a look at this today.

**Comment by saumoh** [comment]
@wattli We should not be actually executing a `mount`.
Prior to the revert of https://github.com/istio/istio/pull/3999
the test were written to mock the exec command(s). These tests should be changed to do that.
Please see as a [here]( https://github.com/colabsaumoh/istio/blob/4b2662f080892c69a172b42150fea7512dc8084c/security/cmd/flexvolume/driver/driver_test.go#L57) and [here](https://github.com/colabsaumoh/istio/blob/4b2662f080892c69a172b42150fea7512dc8084c/security/cmd/flexvolume/driver/driver_test.go#L47) for samples of how the tests were initially written.

**Comment by 249043822** [comment]
I still got such problem, the newest master branch, as after make done, my os /tmp become 8K

Filesystem      Size  Used Avail Use% Mounted on
/dev/vda3        45G   23G   20G  54% /
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G   54M  1.8G   3% /dev/shm
tmpfs           1.9G  187M  1.7G  10% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/vda1       2.0G  178M  1.7G  10% /boot
/dev/vda2        86G   61M   82G   1% /home
tmpfs           380M   12K  380M   1% /run/user/42
tmpfs           380M     0  380M   0% /run/user/0
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/5ec1f886-2b47-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/kube-dns-token-2zqvl
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/043bea5f-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/043bea5f-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-mixer-service-account-token-hpg9t
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/0fa84b82-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-pilot-service-account-token-bs9ph
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/0fa84b82-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/0fb18e8c-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-ingress-service-account-token-zz6vh
tmpfs           1.9G     0  1.9G   0% /var/lib/kubelet/pods/0fb18e8c-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/ingress-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/0fb18e8c-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/10c8fe19-2b4a-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/istio-ca-service-account-token-n9d28
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/b44c689e-2b70-11e8-93a4-fa163e7ca972/volumes/kubernetes.io~secret/prometheus-token-8n76l
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/02ef257e-2b71-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/grafana-token-lm7qq
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/00db79d9-2be4-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/default-token-7rbbp
tmpfs           1.9G   40K  1.9G   1% /var/lib/kubelet/pods/1996d16d-2cd3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~empty-dir/istio-envoy
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/1996d16d-2cd3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/1996d16d-2cd3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/default-token-6wjfm
tmpfs           1.9G   40K  1.9G   1% /var/lib/kubelet/pods/7a5f57d7-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~empty-dir/istio-envoy
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/7a5f57d7-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/7a5f57d7-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/default-token-6wjfm
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/7ac7034a-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   40K  1.9G   1% /var/lib/kubelet/pods/7ac7034a-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~empty-dir/istio-envoy
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/7ac7034a-2cde-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/default-token-6wjfm
tmpfs           1.9G   32K  1.9G   1% /var/lib/kubelet/pods/1dd5f54e-2dc3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~empty-dir/istio-envoy
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/1dd5f54e-2dc3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/istio-certs
tmpfs           1.9G   12K  1.9G   1% /var/lib/kubelet/pods/1dd5f54e-2dc3-11e8-93a5-fa163e7ca972/volumes/kubernetes.io~secret/default-token-6wjfm
tmpfs           8.0K  8.0K     0 100% /tmp


# istio.io/istio/broker/pkg/model/osb
write /tmp/go-build925507610/b304/_testmain.go: no space left on device
FAIL    istio.io/istio/broker/pkg/model/osb [setup failed]
# istio.io/istio/broker/pkg/platform/kube/crd
write /tmp/go-build925507610/b305/_testmain.go: no space left on device
FAIL    istio.io/istio/broker/pkg/platform/kube/crd [setup failed]
go build istio.io/istio/broker/cmd/shared: write /tmp/go-build925507610/b053/importcfg: no space left on device
go build istio.io/istio/vendor/istio.io/api/broker/dev: write /tmp/go-build925507610/b120/importcfg: no space left on device
go build istio.io/istio/broker/pkg/testing/mock/proto: write /tmp/go-build925507610/b137/importcfg: no space left on device
go build istio.io/istio/vendor/github.com/gorilla/mux: write /tmp/go-build925507610/b055/importcfg: no space left on device
FAIL    istio.io/istio/broker/pkg/controller [build failed]
FAIL    istio.io/istio/broker/pkg/model/config [build failed]
# istio.io/istio/broker/pkg/testing/util
compile: writing output: write $WORK/b306/_pkg_.a: no space left on device
make[1]: *** [broker-test] Error 2
go test  ./galley/...
write /tmp/go-build978900040/b001/vet.cfg: no space left on device
make[1]: *** [galley-test] Error 1
bin/gobuild.sh /root/go/out/linux_amd64/release/pilot-agent istio.io/istio/pkg/version ./pilot/cmd/pilot-agent

real    0m1.116s
user    0m0.978s
sys     0m0.276s
go test -p 1  ./pilot/...
# istio.io/istio/pilot/pkg/bootstrap
write /tmp/go-build182506727/b480/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/bootstrap [setup failed]
# istio.io/istio/pilot/pkg/config/aggregate
write /tmp/go-build182506727/b481/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/aggregate [setup failed]
# istio.io/istio/pilot/pkg/config/clusterregistry
write /tmp/go-build182506727/b482/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/clusterregistry [setup failed]
# istio.io/istio/pilot/pkg/config/kube/crd
write /tmp/go-build182506727/b483/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/kube/crd [setup failed]
# istio.io/istio/pilot/pkg/config/kube/ingress
write /tmp/go-build182506727/b484/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/kube/ingress [setup failed]
# istio.io/istio/pilot/pkg/config/memory
write /tmp/go-build182506727/b485/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/memory [setup failed]
# istio.io/istio/pilot/pkg/config/monitor
write /tmp/go-build182506727/b486/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/config/monitor [setup failed]
# istio.io/istio/pilot/pkg/kube/admit
write /tmp/go-build182506727/b488/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/kube/admit [setup failed]
# istio.io/istio/pilot/pkg/kube/inject
write /tmp/go-build182506727/b490/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/kube/inject [setup failed]
# istio.io/istio/pilot/pkg/model
write /tmp/go-build182506727/b491/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/model [setup failed]
# istio.io/istio/pilot/pkg/networking/v1alpha3
write /tmp/go-build182506727/b497/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/networking/v1alpha3 [setup failed]
# istio.io/istio/pilot/pkg/proxy
write /tmp/go-build182506727/b498/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/proxy [setup failed]
# istio.io/istio/pilot/pkg/proxy/envoy/v1
write /tmp/go-build182506727/b499/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/proxy/envoy/v1 [setup failed]
# istio.io/istio/pilot/pkg/proxy/envoy/v1/mock
write /tmp/go-build182506727/b500/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/proxy/envoy/v1/mock [setup failed]
# istio.io/istio/pilot/pkg/proxy/envoy/v2
write /tmp/go-build182506727/b501/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/proxy/envoy/v2 [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/aggregate
write /tmp/go-build182506727/b502/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/aggregate [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry
write /tmp/go-build182506727/b503/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/consul
write /tmp/go-build182506727/b504/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/consul [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/eureka
write /tmp/go-build182506727/b505/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/eureka [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/external
write /tmp/go-build182506727/b506/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/external [setup failed]
# istio.io/istio/pilot/pkg/serviceregistry/kube
write /tmp/go-build182506727/b507/_testmain.go: no space left on device
FAIL    istio.io/istio/pilot/pkg/serviceregistry/kube [setup failed]
write /tmp/go-build182506727/b001/vet.cfg: no space left on device
go build istio.io/istio/pilot/pkg/proxy: write /tmp/go-build182506727/b194/importcfg: no space left on device
go build istio.io/istio/pkg/bootstrap: write /tmp/go-build182506727/b215/importcfg: no space left on device
go build istio.io/istio/pkg/util: write /tmp/go-build182506727/b217/importcfg: no space left on device
FAIL    istio.io/istio/pilot/cmd/pilot-agent [build failed]
# istio.io/istio/vendor/code.cloudfoundry.org/copilot
compile: writing output: write $WORK/b331/_pkg_.a: no space left on device
go build istio.io/istio/vendor/k8s.io/ingress/core/pkg/ingress/status: write /tmp/go-build182506727/b410/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/kube/admit: write /tmp/go-build182506727/b426/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/proxy/envoy/v1/mock: write /tmp/go-build182506727/b428/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry: write /tmp/go-build182506727/b453/importcfg: no space left on device
go build istio.io/istio/vendor/github.com/hashicorp/go-rootcerts: write /tmp/go-build182506727/b458/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/kube/inject: write /tmp/go-build182506727/b463/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/config/monitor/fakes: write /tmp/go-build182506727/b487/importcfg: no space left on device
write /tmp/go-build182506727/b489/vet.cfg: no space left on device
write /tmp/go-build182506727/b169/vet.cfg: no space left on device
go build istio.io/istio/pilot/pkg/networking: write /tmp/go-build182506727/b492/importcfg: no space left on device
go build istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/http/fault/v2: write /tmp/go-build182506727/b494/importcfg: no space left on device
go build istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/config/filter/network/redis_proxy/v2: write /tmp/go-build182506727/b495/importcfg: no space left on device
go build istio.io/istio/pilot/pkg/networking/plugins/mixer: write /tmp/go-build182506727/b496/importcfg: no space left on device
write /tmp/go-build182506727/b327/vet.cfg: no space left on device
go build istio.io/istio/vendor/github.com/golang/sync/errgroup: write /tmp/go-build182506727/b509/importcfg: no space left on device
go build istio.io/istio/vendor/github.com/gorilla/websocket: write /tmp/go-build182506727/b510/importcfg: no space left on device
go build istio.io/istio/pilot/test/grpcecho: write /tmp/go-build182506727/b511/importcfg: no space left on device
go build istio.io/istio/pilot/test/eurekamirror: write /tmp/go-build182506727/b512/importcfg: no space left on device
go build istio.io/istio/pilot/test/util: write /tmp/go-build182506727/b514/importcfg: no space left on device
go build istio.io/istio/pilot/tools: write /tmp/go-build182506727/b517/importcfg: no space left on device
make[1]: *** [pilot-test] Error 2
make[1]: Leaving directory `/root/go/src/istio.io/istio'
make: *** [test] Error 2

**Comment by wattli** [comment]
We actually don't need this driver.go any more, i will clean it up.

**Comment by wattli** [comment]
@incfly fyi

**Comment by john-a-joyce** [comment]
Is there any fix in progress for this issue?  Unfortunately after pulling master in the last few days my prior workarounds of unmounting and setting a larger size don't work reliably and I am totally blocked from making progress on any other issues.

**Comment by wattli** [comment]
https://github.com/istio/istio/pull/6305, done.
