### ISSUE TITLE
Liveness Readiness failing in istio with load increase

### ISSUE THREAD

**Issue by ankitdiscovery** [istio/istio#42542]
### Bug Description

we have services pods running with envoy as sidecar in istio service mesh. with increase in load we see below error frequently however resources utilisation for our main application container and istio container is well within limit. we have istiod(control planed ) well scaled in advanced too. 

what could be bottleneck here ?  Also how can these Liveness configs be controlled at istio side (if that helps)? 

```
39m         Warning   Unhealthy                 pod/xcoder-fe-dep23-c1-649df958d8-mspsn                     Readiness probe failed: HTTP probe failed with statuscode: 503
39m         Warning   Unhealthy                 pod/xcoder-fe-dep23-c1-649df958d8-mspsn                     Readiness probe failed: Get "http://10.52.102.200:15021/healthz/ready": dial tcp 10.52.102.200:15021: connect: connection refused
39m         Warning   Unhealthy                 pod/xcoder-fe-dep23-c1-649df958d8-mspsn                     Readiness probe failed: Get "http://10.52.102.200:15021/healthz/ready": dial tcp 10.52.102.200:15021: connect: invalid argument
39m         Warning   Unhealthy                 pod/xcoder-fe-dep23-c1-649df958d8-mspsn                     Liveness probe failed: Get "http://10.52.102.200:15020/app-health/xcoder-fe-dep23-c1/livez": dial tcp 10.52.102.200:15020: connect: invalid argument
39m         Warning   Unhealthy                 pod/xcoder-fe-dep23-c1-649df958d8-mspsn                     Readiness probe failed: Get "http://10.52.102.200:15020/app-health/xcoder-fe-dep23-c1/readyz": dial tcp 10.52.102.200:15020: connect: invalid argument
```

### Version

```prose
istio version- 1.14.5
```

**Comment by howardjohn** [comment]
"invalid argument" implies an issue on Kubelet side. Not sure what would cause that, the connect() syscall is failing entirely??

**Comment by howardjohn** [comment]
maybe out of ephemeral source ports but I would expect that to have a different error

**Comment by skundudtc** [comment]
@howardjohn 

Above error is coming when we added the annotation `sidecar.istio.io/rewriteAppHTTPProbers: "false"`

Without the annotation we are getting **context deadline exceeded (Client.Timeout exceeded while awaiting headers)**

**Comment by howardjohn** [comment]
Given ita failing either way I still don't think it means Istio is at fault.. for example with my ephemeral port exhaustion idea, this would happen 2x faster with Istio since the same dst port is used.
