### ISSUE TITLE
Make a better way to check local components are available

### ISSUE THREAD

**Issue by yutongz** [istio/istio#4255]
Currently the example components in integration test framework are using dummy sleep to prepare readiness. We should have a better way to check availability.

Based on the doc: https://docs.google.com/document/d/1-wNg8iLegc6Y30oVK15RTf0mwaj2H_Ik5JV1YoMOJo0/edit#heading=h.b4g68nknmjjj

**Comment by hklai** [comment]
Obsolete. Closing.
