### ISSUE TITLE
Helm: Promote to Beta - Status

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#42565]
This issues is just used to track the status of pending activities needed to promote Helm to Beta.
Reference: https://github.com/istio/enhancements/blob/master/features/helm-installation.md

After a discussion with @jacob-delgado , the following items still need to be completed to have the promotion.

- [x] [Update helm integration tests](https://github.com/istio/istio/pull/42559)
- [x] [Use helm repo based install/upgrade in integration tests](https://github.com/istio/istio/pull/42864)
- [x] [Enable Helm Linting](https://github.com/istio/installer/pull/426)
- [X] [Documentation for advanced helm chart customization](https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/)
- [x] [Document about the attributes in values.yaml](https://github.com/istio/istio.io/pull/12476)

**Comment by howardjohn** [comment]
> Add documentation for tarball helm downloads and changes to gateway to use those tarballs

Not sure what this is, especially if `helm repo` is on the only supported option?

> Document some of the important attributes in values.yaml 

maybe we can have all of them..? or just link to https://artifacthub.io/packages/helm/istio-official/istiod?modal=values

**Comment by kfaseela** [comment]
> > Add documentation for tarball helm downloads and changes to gateway to use those tarballs
> 
> Not sure what this is, especially if `helm repo` is on the only supported option?
> 
Makes sense. Will not document about the tarball option.

**Comment by keithmattix** [comment]
>  Make targets to build the latest tarballs along with the release

What exactly is required for this task?

**Comment by kfaseela** [comment]
> > Make targets to build the latest tarballs along with the release
> 
> What exactly is required for this task?

@keithmattix we were trying to optimize the helm integration tests for upgrade scenarios which currently uses tarballs. So everytime a release is made, we manually upload the newer tarballs. But I think the way forward is to get rid of the tarballs fully, and promote repo based install. I am currently trying to use `--version` argument and modify the upgrade tests. If that works, this subtask for tarballs may not be needed, and will remove

**Comment by keithmattix** [comment]
Cool, thanks for the update! Let me know if there's anything o can do to help get the Helm charts to beta!

**Comment by nshankar13** [comment]
@kfaseela @howardjohn thanks for all of the great work on this. Is there currently a way to install istio via helm in a non-default namespace (outside of istio-system), or do we have to generate the manifests with the edited namespaces ourselves, and install via `kubectl apply -f`?

**Comment by kfaseela** [comment]
> @kfaseela @howardjohn thanks for all of the great work on this. Is there currently a way to install istio via helm in a non-default namespace (outside of istio-system), or do we have to generate the manifests with the edited namespaces ourselves, and install via `kubectl apply -f`?
> 
> `helm install istio-base istio/base -n kube-system --set namespace=kube-system --set values.global.istioNamespace=kube-system`
> 
> Gives the following error:
> 
> `Error: INSTALLATION FAILED: namespaces "istio-system" not found`

will check this and get back to you

**Comment by kfaseela** [comment]
@nshankar13 : replace `values.global.istioNamespace` with `global.istioNamespace` and it should work.

helm install istio-base istio/base -n ns-1 --set namespace=ns-1 --set global.istioNamespace=ns-1  --create-namespace

**Comment by nshankar13** [comment]
@kfaseela thanks, that worked!
