### ISSUE TITLE
Some sub-folders into "samples" are empty

### ISSUE THREAD

**Issue by calogxro** [istio/istio#42579]
### Bug Description

Release 1.16.1 linux amd64.
Some sub-folders into "samples" are empty.

For example, compare https://github.com/istio/istio/tree/1.16.1/samples/bookinfo/src/details
with the same folder into
https://github.com/istio/istio/releases/download/1.16.1/istio-1.16.1-linux-amd64.tar.gz

### Version

```prose
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (9 proxies)
$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

**Comment by howardjohn** [comment]
The release strips out some types of files intentionally

**Comment by calogxro** [comment]
Ok, I thought it was due to an error.
I was following the getting started guide and I expected to find that files there. 
I thought the sample application would not have worked, but I now realize that it works anyway because services images are pulled from Docker Hub. 
I'm going to close this issue. Thanks.
