### ISSUE TITLE
DestinationRule not exported to all namespaces

### ISSUE THREAD

**Issue by fluzzykitten** [istio/istio#42570]
### Bug Description

DestinationRules in the `istio-system` namespace are correctly exported to all namespaces, but the same DestinationRules in other namespaces, do not appear to get exported to all namespaces.

We would like to put all our common istio configurations (serviceEntries, VirtualServices, destinationRules, and gateways) into one namespace for easy management. From our understanding, it should work, and it sorta does. For example, when we deploy all 4 to the `istio-system` namespace, every namespace correctly routes with the configs and everything works. But when we move the 4 configs to a new namespace that we’ve called `istio-config`, things break, and we a “NC” when trying to connect to the service. We’ve found in troubleshooting that we can move the ServiceEntry, VirtualService, and gateway to the `istio-config` namespace but leave just the “destinationRule” in the `istio-system` namespace, and everything continues to work. But when we move the destinationRule from `istio-system` to `istio-config` with the other configuration files, all other namespaces break. Here is our broken configuration:
 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: agent-1
  namespace: istio-config
spec:
  hosts:
    - agent-1.example.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS
  exportTo:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-agent-1
  namespace: istio-config
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 22
        name: ssh
        protocol: TLS
      hosts:
        - "agent-1.example.com"
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-agent-1
  namespace: istio-config
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  exportTo:
    - "*"
  subsets:
    - name: agent-1
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 22
            tls:
              mode: ISTIO_MUTUAL
              sni: agent-1.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: agent-1
  namespace: istio-config
spec:
  exportTo:
    - "*"
  hosts:
    - "agent-1.example.com"
    - "agent-1"
  gateways:
    - mesh
    - istio-egressgateway-agent-1
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: agent-1
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway-agent-1
          port: 22
      route:
        - destination:
            host: agent-1.example.com
            port:
              number: 22
          weight: 100
 
---
```
 
Again, the fix is to change the destination rule to:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-agent-1
  namespace: istio-system
spec:
```

But the docs say we should be able to use any namespace when using the ExportTo: "*". Thanks for the help! =)

https://istio.io/latest/docs/reference/config/networking/destination-rule/#DestinationRule

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (10 proxies)
$ kubectl version --short
Client Version: v1.23.13
Server Version: v1.23.14+rke2r1
```

**Comment by howardjohn** [comment]
DR can only impact hosts in their own namespace, or override hosts for proxies in their namespace. Allowing a completely unrelated ns to override settings for everyone else would be a security issue.

**Comment by fluzzykitten** [comment]
But the documentation:
https://istio.io/latest/docs/reference/config/networking/destination-rule/#DestinationRule

Says that you can use the `exportTo` on the DestinationRule to export it to any or all namespaces:
```
exportTo: A list of namespaces to which this destination rule is exported. The resolution of a destination rule to apply to a service occurs in the context of a hierarchy of namespaces. Exporting a destination rule allows it to be included in the resolution hierarchy for services in other namespaces. This feature provides a mechanism for service owners and mesh administrators to control the visibility of destination rules across namespace boundaries.
```

**Comment by howardjohn** [comment]
exportTo * is the default and follows the semantics I listed. Other
settings are for restricting that even further.

**Comment by fluzzykitten** [comment]
Right... so, you agree that there is a bug. It should work, since I'm explicitly saying the same as the default, which is to export to all namespaces.

**Comment by howardjohn** [comment]
It exports to all namespaces following the semantics I mentioned. All namespaces have access to it but chose not to do anything with it since it's not applicable.

**Comment by fluzzykitten** [comment]
I don't understand what you're saying. It sounds like you're saying it should be possible, which is also what the docs say, but you're not telling me what I'm doing wrong in the config. 

Furthermore, this bug sometimes works and sometimes not work. As I mentioned in the post, a pod in namespace `separate-namespace` has access to the Destination rule with `exportTo: "*"` when it exists in the `istio-system` namespace, but with the same DestinationRule same settings, a pod in namespace `separate-namespace` does not have access to the same Destination rule when it exists in `istio-config`, or `demo`, or `namespace2`, or any other namespace, despite the DestinationRule being exported to all namespaces. Which is why this is a bug. Unless you see an error in my configuration, it should work the same in any namespaces, not just the namespace with the Istio Operator.

**Comment by howardjohn** [comment]
See https://istio.io/latest/docs/ops/best-practices/traffic-management/#cross-namespace-configuration. exportTo can _further_ restrict that for values other than `*`. But it cannot widen it.

**Comment by fluzzykitten** [comment]
Thanks for sending that link. It would've been nice if at some point you actually said the problem, which was the lookup path, not a configuration problem. TL;DR for those who don't want to read through link attached, the reason global destination rules work in `istio-system` and not other namespaces is because:
```
You can avoid this problem by creating the destination rule in the same namespace as the corresponding service, default in this example. It would then get applied to requests from clients in any namespace. You can also move the destination rule to the istio-system namespace, the third namespace on the lookup path, although this isn’t recommended unless the destination rule is really a global configuration that is applicable in all namespaces, and it would require administrator authority.
```
https://istio.io/latest/docs/ops/best-practices/traffic-management/#cross-namespace-configuration
