### ISSUE TITLE
"mixer_check_server" is required to be a static cluster

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4257]
Report:
i am using a istio-proxy fork where all i did was update the base Envoy from Feb27 -> March 8.
With Pilot `0.6.0` I see a crash in Envoy with the message:
`[2018-03-14 04:57:59.104][83][warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: gRPC client cluster 'mixer_check_server' is not static`
A quick scan of the code in Pilot seems to indicate this is the related code:
`https://github.com/istio/istio/blob/5e563993a6fce04a81ac3bb82736fc0731eb88c2/pilot/pkg/proxy/envoy/v1/route.go#L519`

The client for mixer seems to require static clusters.

**Comment by saumoh** [comment]
hey @mandarjog @qiwzhang  are u planning to crud this file:
`https://github.com/istio/istio/blob/master/tools/deb/envoy_bootstrap_tmpl.json`
and/or are there other places where this needs to be changed.
As soon as you fix this i will hit this crash for my changes...therefore asking :-)
