### ISSUE TITLE
NR filter_chain_not_found

### ISSUE THREAD

**Issue by jeenadeepak** [istio/istio#42587]
### Bug Description

I am facing error while adding domain name in Gateway host, it is working for wildcard, but for domain name it is showing error: filter_chain_not_found

Configuration:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "istio-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  \- port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    \- "jenkins.shared.huru.co"
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins
spec:
  gateways:
  \- jenkins-gw
  hosts:
  \- jenkins.shared.huru.co
  http:
  \- match:
    \- uri:
      prefix: /
    route:
    \- destination:
        host: jenkins.jenkins.svc.cluster.local
        port:
          number: 8080

**ERROR**:
Istio-gateway-log:

2022-12-27T22:07:16.522359Z	info	Envoy proxy is ready
2022-12-27T22:07:16.558143Z	info	envoy upstream	cds: add 21 cluster(s), remove 5 cluster(s)
2022-12-27T22:07:16.560269Z	info	envoy upstream	cds: added/updated 0 cluster(s), skipped 21 unmodified cluster(s)
[2022-12-27T22:08:14.102Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.1.117.166:443 10.1.115.148:1544 - -
[2022-12-27T22:08:14.258Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.1.117.166:443 10.1.94.166:30120 - -

### Version

```prose
version: 1.16.1
```

### Additional Information

 istioctl bug-report -n jenkins

Target cluster context: arn:aws:eks:me-central-1:365834278172:cluster/shared-eks

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-12-27 22:15:43.943685601 +0000 UTC

Cluster endpoint: https://3ED77DBA7E1D7564F9661FB88AD66EDC.gr7.me-central-1.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.16.0", GitRevision:"8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783", GolangVersion:"go1.19.3", BuildStatus:"Clean", GitTag:"1.16.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.1", GitRevision:"tetratefips-v0-bcb41746650e2eb3d8d0aa7624a3a1ca80b6fec0", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.1-tetratefips-v0, 1.15.3-tetratefips-v0}

Fetching proxy logs for the following containers:

cert-manager//cert-manager-csi-driver-9xtgt/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-9xtgt/liveness-probe
cert-manager//cert-manager-csi-driver-9xtgt/node-driver-registrar
cert-manager//cert-manager-csi-driver-z6wkg/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-z6wkg/liveness-probe
cert-manager//cert-manager-csi-driver-z6wkg/node-driver-registrar
cert-manager/cert-manager-cainjector/cert-manager-cainjector-86f7f4749-g4zqk/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-66c85f8577-zt5bz/cert-manager-webhook
cert-manager/cert-manager/cert-manager-7d57b6576b-4ltk4/cert-manager-controller
istio-system//istio-cni-node-7qvw5/install-cni
istio-system//istio-cni-node-qn775/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-685fcc78c-2h5bj/istio-proxy
istio-system/istiod/istiod-54bcb75b55-gzh7d/discovery
jenkins//jenkins-0/config-reload
jenkins//jenkins-0/istio-proxy
jenkins//jenkins-0/jenkins
jfrog//jfrog-artifactory-jcr-0/artifactory
jfrog//jfrog-artifactory-jcr-0/istio-proxy
jfrog//jfrog-artifactory-oss-0/artifactory
jfrog//jfrog-artifactory-oss-0/istio-proxy

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0105] (Pod jfrog/jfrog-artifactory-jcr-0) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: containers.istio.tetratelabs.com/proxyv2:1.15.3-tetratefips-v0; injection configuration image: containers.istio.tetratelabs.com/proxyv2:1.16.1-tetratefips-v0). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod jfrog/jfrog-artifactory-oss-0) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: containers.istio.tetratelabs.com/proxyv2:1.15.3-tetratefips-v0; injection configuration image: containers.istio.tetratelabs.com/proxyv2:1.16.1-tetratefips-v0). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service jenkins/jenkins-agent) Port name agent-listener (port: 50000, targetPort: 50000) doesn't follow the naming convention of Istio port.
Creating an archive at /home/ec2-user/git/infra/terraform/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.
[ec2-user@ip-10-1-1-140 terraform]$ istioctl bug-report -n jenkins

Target cluster context: arn:aws:eks:me-central-1:365834278172:cluster/shared-eks

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-12-27 22:17:22.184852012 +0000 UTC

Cluster endpoint: https://3ED77DBA7E1D7564F9661FB88AD66EDC.gr7.me-central-1.eks.amazonaws.com

CLI version:
version.BuildInfo{Version:"1.16.0", GitRevision:"8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783", GolangVersion:"go1.19.3", BuildStatus:"Clean", GitTag:"1.16.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.1", GitRevision:"tetratefips-v0-bcb41746650e2eb3d8d0aa7624a3a1ca80b6fec0", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.1-tetratefips-v0}

Fetching proxy logs for the following containers:

cert-manager//cert-manager-csi-driver-9xtgt/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-9xtgt/liveness-probe
cert-manager//cert-manager-csi-driver-9xtgt/node-driver-registrar
cert-manager//cert-manager-csi-driver-z6wkg/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-z6wkg/liveness-probe
cert-manager//cert-manager-csi-driver-z6wkg/node-driver-registrar
cert-manager/cert-manager-cainjector/cert-manager-cainjector-86f7f4749-g4zqk/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-66c85f8577-zt5bz/cert-manager-webhook
cert-manager/cert-manager/cert-manager-7d57b6576b-4ltk4/cert-manager-controller
istio-system//istio-cni-node-7qvw5/install-cni
istio-system//istio-cni-node-qn775/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-685fcc78c-2h5bj/istio-proxy
istio-system/istiod/istiod-54bcb75b55-gzh7d/discovery
jenkins//jenkins-0/config-reload
jenkins//jenkins-0/istio-proxy
jenkins//jenkins-0/jenkins
jfrog//jfrog-artifactory-jcr-0/artifactory
jfrog//jfrog-artifactory-jcr-0/istio-proxy
jfrog//jfrog-artifactory-oss-0/artifactory
jfrog//jfrog-artifactory-oss-0/istio-proxy

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service jenkins/jenkins-agent) Port name agent-listener (port: 50000, targetPort: 50000) doesn't follow the naming convention of Istio port.
Creating an archive at /home/ec2-user/git/infra/terraform/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

ISTIO namespace log:
 istioctl bug-report -n istio-system

Target cluster context: arn:aws:eks:me-central-1:365834278172:cluster/shared-eks

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-12-27 22:18:56.495281432 +0000 UTC

Cluster endpoint: https://3ED77DBA7E1D7564F9661FB88AD66EDC.gr7.me-central-1.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.16.0", GitRevision:"8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783", GolangVersion:"go1.19.3", BuildStatus:"Clean", GitTag:"1.16.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.1", GitRevision:"tetratefips-v0-bcb41746650e2eb3d8d0aa7624a3a1ca80b6fec0", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.1-tetratefips-v0}

Fetching proxy logs for the following containers:

cert-manager//cert-manager-csi-driver-9xtgt/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-9xtgt/liveness-probe
cert-manager//cert-manager-csi-driver-9xtgt/node-driver-registrar
cert-manager//cert-manager-csi-driver-z6wkg/cert-manager-csi-driver
cert-manager//cert-manager-csi-driver-z6wkg/liveness-probe
cert-manager//cert-manager-csi-driver-z6wkg/node-driver-registrar
cert-manager/cert-manager-cainjector/cert-manager-cainjector-86f7f4749-g4zqk/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-66c85f8577-zt5bz/cert-manager-webhook
cert-manager/cert-manager/cert-manager-7d57b6576b-4ltk4/cert-manager-controller
istio-system//istio-cni-node-7qvw5/install-cni
istio-system//istio-cni-node-qn775/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-685fcc78c-2h5bj/istio-proxy
istio-system/istiod/istiod-54bcb75b55-gzh7d/discovery
jenkins//jenkins-0/config-reload
jenkins//jenkins-0/istio-proxy
jenkins//jenkins-0/jenkins
jfrog//jfrog-artifactory-jcr-0/artifactory
jfrog//jfrog-artifactory-jcr-0/istio-proxy
jfrog//jfrog-artifactory-oss-0/artifactory
jfrog//jfrog-artifactory-oss-0/istio-proxy

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service jenkins/jenkins-agent) Port name agent-listener (port: 50000, targetPort: 50000) doesn't follow the naming convention of Istio port.
Creating an archive at /home/ec2-user/git/infra/terraform/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by kushalg-1212** [comment]
complete version check

**Comment by deepakjeena** [comment]
@kushalg-1212 : 
version: 1.16.1

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni is likely

**Comment by howardjohn** [comment]
Answered above and no followups so I'll close this for now
