### ISSUE TITLE
Add affinity rules to the istio-cni helm chart

### ISSUE THREAD

**Issue by bcarlock-emerge** [istio/istio#42588]
There are a few situations where Istio CNI should not be deployed to every node, namely virtual nodes from systems like admiralty. I propose the addition of affinity rules to the istio-cni helm chart to allow the configuration of anti-affinity rules for these situations.

Forking the chart myself, generating k8s artifacts and then applying manual changes

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

I'd be happy to make the contribution myself, but I'm not really sure how to get involved.

**Comment by keithmattix** [comment]
Fixed by $42038
