### ISSUE TITLE
Service appProtocol supported values deviate from documented Kubernetes recommendations

### ISSUE THREAD

**Issue by jstangroome** [istio/istio#42615]
### Bug Description

[Istio explicit protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection) documentation specifies that the `appProtocol` property on a Kubernetes `Service` can be one of approximately ten supported values, e.g. `http`, `https`, `tcp`, when used with Istio for traffic management.

However, the [Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) for the same `appProtocol` property states:
>Values should either be [IANA standard service names](https://www.iana.org/assignments/service-names) or domain prefixed names such as `mycompany.com/my-custom-protocol`.

While several of the Istio-supported protocol values are IANA standard service names, e.g. `http`, `redis`, and `mysql`, several others are not:

- `http2`: not an IANA standard service name
- `grpc` and `grpc-web`: not IANA names
- `mongo`: the IANA name is `mongodb`
- `tcp`: not an IANA service name
- `tls`: not an IANA name

To mitigate future compatibility issues, it may be prudent to align Istio's use of the `appProtocol` property with the Kubernetes documentation. For example, `tcp` could become `istio.io/tcp`.

I imagine the current values would continue to be honored by Istio for backward compatibility, but new naming conventions would be encouraged.

### Version

```prose
istio 1.16
```

**Comment by howardjohn** [comment]
There has been some discussion in Kubernetes about this as well, as ~everyone is doing this. cc @robscott
