### ISSUE TITLE
waypoint: ignore/use delegated identity from hairpin requests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42640]
Istiod side of https://github.com/istio/ztunnel/issues/73

When we hairpin a request, it will be over HBONE. But it will have the source identity of <something> (or maybe we can present no client cert?). We need to make sure this identity isn't used.

Note, per https://github.com/istio/ztunnel/issues/73#issuecomment-1370129811, we don't need delegated identity for now... just to skip the identity

**Comment by jaellio** [comment]
@howardjohn Is this issue still valid?

**Comment by howardjohn** [comment]
Not 100% sure but I believe so
