### ISSUE TITLE
How to overwrite namespace default stable tag istio injection with canary tag in deployment

### ISSUE THREAD

**Issue by anup1384** [istio/istio#42654]
### Bug Description

I have Istio 1.12.0 running with a stable tag and I have upgraded my istio version to 1.13.9 with canary tag. The default tag is mapped with 1.12.0 and added to the namespace.

Now I want to overwrite the namespace injection with the canary tag in the deployment for one application.

Note- I have tried to add pod label istio.io/rev: canary in deployment but couldn't get success, still picked the stable tag 1.12.0 which comes from namespace injection.

Is there any way to overwrite the injection based on labels or annotation?

istioctl tag list output 

TAG     REVISION NAMESPACES
canary  1-13-9   bookinfo
default 1-12-0   dev
stable  1-12-0

### Version

```prose
$istioctl version                                                    kube pplus-nonProdEksCluster
 client version: 1.13.9
 istiod version: 1.12.0
 istiod version: 1.13.9
pilot version: 1.12.0
data plane version: 1.12.0 (116 proxies), 1.13.9 (1189 proxies)
$ kubectl version --short
Client Version: v1.23.4
Server Version: v1.22.15-eks-fb459a0
```

**Comment by howardjohn** [comment]
see https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

Note namespace takes precedence over pod
