### ISSUE TITLE
TestCheckReportDisable fails

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4265]
https://circleci.com/gh/istio/istio/48740?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by qiwzhang** [comment]
Most likely related to the recent change https://github.com/istio/istio/pull/4073

When wait for TcpPort,  it will send Mixer a Check call,  it will mess up Check count.

**Comment by kyessenov** [comment]
I'll let you developers more knowledgeable in this to design a fix. For
now, disabling.
