### ISSUE TITLE
MetricDefinition test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42661]
Test reverted in https://github.com/istio/istio/pull/42659

Example failure: https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-istiodremote_istio_postsubmit/1610365286957977600

cc @zirain @kyessenov

**Comment by zirain** [comment]
there's bug in the implement of metric definition

**Comment by kyessenov** [comment]
Can't reproduce locally, if someone can get debug/trace logs, would help narrow it down.

**Comment by zirain** [comment]
@kyessenov I also cannot reproduct in local, maybe related to pods with multi protocols/ports?

**Comment by kyessenov** [comment]
Asan on CI:
==27==ERROR: AddressSanitizer: container-overflow on address 0x608002f145b0 at pc 0x55d9223e32cc bp 0x7f2cc281a1a0 sp 0x7f2cc281a198
READ of size 8 at 0x608002f145b0 thread T7
[2023-01-19T20:44:30.449Z] "GET /custom_path HTTP/1.1" 0 DC downstream_remote_disconnect - "-" 0 0 5784 - "-" "Go-http-client/1.1" "d0ea0cba-2856-4dd1-97f9-7699f38772d6" "server.echo-2-57872.svc.cluster.local" "10.244.0.31:8090" outbound|80||server.echo-2-57872.svc.cluster.local 10.244.0.32:36306 10.96.11.141:80 10.244.0.32:42620 - default
#0 0x55d9223e32cb  (/usr/local/bin/envoy+0x139252cb) /usr/lib/llvm/bin/../include/c++/v1/utility:447
#1 0x55d92240a17e  (/usr/local/bin/envoy+0x1394c17e) source/extensions/filters/http/istio_stats/istio_stats.cc:430
#2 0x55d9223e0f1a  (/usr/local/bin/envoy+0x13922f1a) source/extensions/filters/http/istio_stats/istio_stats.cc:703
#3 0x55d9223d5a78  (/usr/local/bin/envoy+0x13917a78) source/extensions/filters/http/istio_stats/istio_stats.cc:838
#4 0x55d9223d694c  (/usr/local/bin/envoy+0x1391894c) source/extensions/filters/http/istio_stats/istio_stats.cc:?
#5 0x55d92d6feac9  (/usr/local/bin/envoy+0x1ec40ac9) external/envoy/source/common/http/filter_manager.h:669
#6 0x55d92d6fceae  (/usr/local/bin/envoy+0x1ec3eeae) external/envoy/source/common/http/conn_manager_impl.cc:281
#7 0x55d92d70ace7  (/usr/local/bin/envoy+0x1ec4cce7) external/envoy/source/common/http/conn_manager_impl.cc:1662
#8 0x55d92d709856  (/usr/local/bin/envoy+0x1ec4b856) external/envoy/source/common/http/conn_manager_impl.cc:463
#9 0x55d92d6facee  (/usr/local/bin/envoy+0x1ec3ccee) external/envoy/source/common/http/conn_manager_impl.cc:529
#10 0x55d92d70b571  (/usr/local/bin/envoy+0x1ec4d571) external/envoy/source/common/http/conn_manager_impl.cc:491

**Comment by kyessenov** [comment]
Fix https://github.com/istio/proxy/pull/4361.
