### ISSUE TITLE
VALIDATION_WEBHOOK_CONFIG_NAME env variable getting ignored

### ISSUE THREAD

**Issue by venkatk-25** [istio/istio#42681]
### Bug Description

We have observed that VALIDATION_WEBHOOK_CONFIG_NAME env which is documented is not actually getting ignored in the code.

https://github.com/istio/istio/blob/3fcff36ddc5e69ed20755c6385d44eb1a0e50505/pilot/pkg/features/pilot.go#L451-L452
While the code here checks for the env variable here
https://github.com/istio/istio/blob/89c548304627c7a2bed1216ce2b180560a8d5a67/pilot/pkg/bootstrap/validation.go#L42-L49

The actual code which patches validationWebhook uses label selector instead and the VALIDATION_WEBHOOK_CONFIG_NAME is ignored

https://github.com/istio/istio/blob/89c548304627c7a2bed1216ce2b180560a8d5a67/pkg/webhooks/validation/controller/controller.go#L203

### Version

```prose
1.15
```

**Comment by hzxuzhonghu** [comment]
The patch logic is right, it is intended to reconfile all the config that is used. 

`VALIDATION_WEBHOOK_CONFIG_NAME ` env functions not as described

**Comment by venkatk-25** [comment]
@hzxuzhonghu agree patch logic works perfectly,

I am mainly pointing to issue in docs and the inconsistent condition in code here, 
https://github.com/istio/istio/blob/89c548304627c7a2bed1216ce2b180560a8d5a67/pilot/pkg/bootstrap/validation.go#L42 

To satisfy condition we should provide name of webhook, the patch logic is selecting webhook based on label selector and tge name is actually not used.

It was misleading, we had a requirement of naming the webhook with custom name, which led us to this.

**Comment by wulianglongrd** [comment]
I think `ValidationWebhookConfigName` should be renamed to a switch. And I think using label can works well (ValidatingWebhookConfiguration CR add `istio.io/rev: canary` and istiod `export Revision=canary` ? ).

**Comment by hzxuzhonghu** [comment]
@Monkeyanator @howardjohn We need a fix here

**Comment by hzxuzhonghu** [comment]
>I think ValidationWebhookConfigName should be renamed to a switch

You mean as a bool value?  Seems reasonable.

**Comment by wulianglongrd** [comment]
yes, defined as a bool value.

**Comment by venkatk-25** [comment]
@wulianglongrd  Doc would have been more iformative if the label to be applied(istio.io/rev: <revision> ) for *ValidationWebhookConfig*  is mentioned

closing the issue
