### ISSUE TITLE
Decide on using  uber/atomic vs golang standard atomic package

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#42693]
There was a discussion in https://github.com/open-telemetry/opentelemetry-collector/issues/5200

The conclusion is that golang atomic pkg has some bugs https://pkg.go.dev/sync/atomic@master#pkg-note-BUG

So OTEL chooses the uber atomic rather than golang standard.

I think istio should consider unify atomic across the repo

**Comment by howardjohn** [comment]
I didn't look into them enough to have a strong opinion but IMO the bugs are not relevant to us, we only support 64 bit linux
