### ISSUE TITLE
Questions about CaptureTLS and RestoreTLS

### ISSUE THREAD

**Issue by yuri-lcy** [istio/istio#42694]
When using ambient, I saw that there are RestoreTLS and CaptureTLS filters in the listener configuration of Envoy, but I didn’t find any information about these two filters. If you know, please help answer the role of these two filters. Thank you Reply

**Comment by yuri-lcy** [comment]
Is there any time to help answer. @howardjohn

**Comment by kyessenov** [comment]
These are deleted, check the latest commit.
