### ISSUE TITLE
Got 503 when access bookinfo productpage on IBM Bluemix Container Service

### ISSUE THREAD

**Issue by Linda009** [istio/istio#427]
I got 503 when run _curl -o /dev/null -s -w "%{http_code}\n" http://${GATEWAY_URL}/productpage_

I can see the ingress address, shown as the same in svc istio-ingress
```
# kubectl get ingress -o wide
NAME      HOSTS     ADDRESS          PORTS     AGE
gateway   *         169.xx.xx.xxx   80        2d
# kubectl get svc istio-ingress
NAME            CLUSTER-IP   EXTERNAL-IP      PORT(S)                      AGE
istio-ingress   10.10.10.6   169.xx.xx.xxx    80:30835/TCP,443:30012/TCP   2d
# export GATEWAY_URL=169.xx.xx.xxx:80
```
nothing in the log of productpage container `kubectl logs productpage-v1-3210513262-nr4gm productpage`

I verified that the product page can be shown in the browser when use port-forward and access with url http://localhost:9080/productpage

What might be the issue? Thanks.

**Comment by Linda009** [comment]
move to issues repo.

**Comment by yiakwy** [comment]
I have the similar problem. The sample does not work in my MacOS kubectl with gcloud env
