### ISSUE TITLE
Limit tls packet size 

### ISSUE THREAD

**Issue by vguar** [istio/istio#42701]
### Bug Description

Hello,

I try to report old Nginx configuration “[nginx.ingress.kubernetes.io/proxy-buffer-size:](http://nginx.ingress.kubernetes.io/proxy-buffer-size:) ‘3k’” to my Istio config.

I’ve create an Envoy Filter like this :

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bufferlimit-istio
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        per_connection_buffer_limit_bytes: 3000  
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        per_connection_buffer_limit_bytes: 3000

But it doesn’t work.

Can you confirm me that configuration is good or not ?

Thx.

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (3 proxies)

kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.22.15
```

**Comment by hzxuzhonghu** [comment]
You can confirm it by looking up generated xds with `istioctl` command

**Comment by howardjohn** [comment]
GitHub issues are for tracking bugs and feature requests. Help like this may be better suited for slack, etc
