### ISSUE TITLE
413 Payload too large response from envoy

### ISSUE THREAD

**Issue by danilina-wsib** [istio/istio#4271]
Hi,

I am uploading files to an API endpoint (POST request) with Istio 0.6

I see 413 Payload too large error in the envoy log, while my application endpoint is not hit at all (it does validate Content-length header)

Is there any way to adjust the setting to set the max request bytes in Envoy?

Thank you,
Alex

**Comment by linsun** [comment]
One way to adjust is via the new pilot webhooks that is made avail in 0.6:  https://github.com/mandarjog/istioluawebhook

**Comment by linsun** [comment]
BTW, I had a test case to reproduce this issue and I was able to fix it by creating this web hook:  

https://github.com/linsun/istioluawebhook by configuring the soft watermark to be a lot larger than the default.  cc @PiotrSikora

**Comment by cmluciano** [comment]
upstream envoy issue https://github.com/envoyproxy/envoy/issues/2919

**Comment by cmluciano** [comment]
cc @douglas-reid @geeknoid @kyessenov @lizan

**Comment by cmluciano** [comment]
I tried this out in IBM Cloud with k8s 1.9 and Istio 0.7.1 using  https://github.com/rayh0001/gs-spring-boot-docker. This is now working.

Steps to replicate:
 - edit https://github.com/rayh0001/gs-spring-boot-docker/blob/master/service-deployment-istio.yaml#L89 & https://github.com/rayh0001/gs-spring-boot-docker/blob/master/service-deployment-istio.yaml#L69 to use 0.7.1
- edit https://github.com/rayh0001/gs-spring-boot-docker/blob/master/front-door-ingress.yaml#L25 & https://github.com/rayh0001/gs-spring-boot-docker/blob/master/front-door-ingress.yaml#L16 with your subdomain returned from `bx cs cluster-get YOURCLUSTERHERE`

- deploy new istio version
```shell
wget https://github.com/istio/istio/releases/tag/0.7.1
tar -xvf istio-0.7.1-linux.tar.gz
cd istio-0.7.1 
kubectl create -f ./install/kubernetes/istio.yaml
```
- create secret for fd-ingress
```
kubectl get secret YOURCLUSTERNAMEHERE -o yaml | sed 's/default/istio-system/g' | kubectl -n istio-system create -f -
```
- edit https://github.com/rayh0001/gs-spring-boot-docker/blob/master/front-door-ingress.yaml#L26 with the secretname that you just created 

- deploy demos
```shell
kubectl create -f service-deployment-istio.yaml
kubectl create -f istio-gateway.yaml
kubectl create -f front-door-ingress.yaml
```

- create 1MB test file
```shell
dd if=/dev/zero of=output.file bs=1024 count=1024
```

- test if file can be sent to example service
```
curl -svo /dev/null -F 'file=@output.file' MYCLUSTERNAME.us-east.containers.mybluemix.net/scan -H 'transactionId: 11111' -H 'Cache-Control: no-cache'
```

- expected output indicating success
```
*   Trying 169.x.x.x...
* Connected to MYCLUSTERNAME.us-east.containers.mybluemix.net (169.x.x.x) port 80 (#0)
> POST /scan HTTP/1.1
> Host: MYCLUSTERNAME.us-east.containers.mybluemix.net
> User-Agent: curl/7.47.0
> Accept: */*
> transactionId: 11111
> Cache-Control: no-cache
> Content-Length: 1048779
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------fdfa83f004eccb35
> 
< HTTP/1.1 100 Continue
} [155 bytes data]
< HTTP/1.1 200 OK
< Date: Mon, 02 Apr 2018 18:12:31 GMT
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 7
< x-envoy-upstream-service-time: 187
< Connection: Keep-Alive
< 
{ [7 bytes data]
* Connection #0 to host MYCLUSTERNAME.us-east.containers.mybluemix.net left intact

```
