### ISSUE TITLE
ztunnel has dangerous preStop hook

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42730]
https://github.com/istio/istio/blob/55192ffa740736d565063627b6bcb8dd70e7c628/manifests/charts/istio-cni/templates/daemonset.yaml#L158

This is good for the last replica, but can break if we have multiple replicas (rolling restart). We need a hitless solution

**Comment by howardjohn** [comment]
@dhawton any ideas?

**Comment by howardjohn** [comment]
fyi the issue is _moving_ but still remains in https://github.com/istio/istio/pull/43578#discussion_r1117291332

**Comment by keithmattix** [comment]
Not stale
