### ISSUE TITLE
Need a doc plan for ambient alpha

### ISSUE THREAD

**Issue by linsun** [istio/istio#42750]
cc @howardjohn @SkyfireFrancisZ - we 'll need to discuss if and what to update in istio.io.

**Comment by howardjohn** [comment]
IMO for now we should just have a section dedicated to ambient, do not touch other docs. Within that we can have:

* Intro
* Comparison to non-ambient
* Install/migrating
* Some ambient-specific tasks

**Comment by howardjohn** [comment]
I think some others are working on this along with @linsun but I don't know your github IDs, so assigned to just Lin for now

**Comment by howardjohn** [comment]
Base structure:


# Ambient mesh

New top level page under "Operations"

Main page has a quick introduction, pulling content from the original blog. Should be ~1 page, other pages will go into details

## Getting Started

*Huge* warning about alpha quality. I would phrase this as:

> Ambient mesh is currently at [alpha](https://istio.io/latest/docs/releases/feature-stages/) feature status. 
> Please ensure you fully understand all implications of this before using ambient mesh.
> While many other Istio features start as "alpha" and progress unchanged to "beta" and "stable", giving a false sense of stability, ambient mesh is *truly* alpha quality.
> There are a variety of known gaps in security, performance, and stability. There are *planned breaking changes* which will have no smooth migration path.
> **Use at your own risk.**

Platform requirements (kind or a few others only for now)

Install steps (istioctl install --profile ambient)

## Usage guide

Go through a few tasks... I'd imagine something like:


* Deploy bookinfo *first*
* Deploy ambient
* Show we have mTLS via logging and metrics (kiali?? or maybe just grafana)
* Deploy L4 authz, show something getting denied
* Deploy a waypoint, show we are now getting L7 attributes (in metrics perhaps) out of the box
* Deploy some standard bookinfo things, like a traffic split

## Architecture

Discuss the core architecture. Node proxy and waypoint, producer side routing, etc

### Differences from sidecar architecture

Deep dive into differences

### Traffic routing

Deep dive into how traffic flows through the system; "life of a packet".

### Security

Deep dive into security model. We have a blog with a lot of this content already

**Comment by howardjohn** [comment]
Blog posts:
* Announcing ambient mesh alpha (need owner)
* Ztunnel focus blog (Lin and John)
* Designing ambient for scalability (John) (also submitted as istioday talk)
* Producer oriented routing (need owner)

We have 8 weeks until kubecon and at least 4 blogs there, I think we should do roughly 1 every 2 weeks to keep a steady steam coming.

The alpha announcement should be a bit later so we can stabilize more and finish the docs mentioned above

**Comment by linsun** [comment]
I'll add myself to producer oriented routing - already has something started for that.  I can also work with whoever (@justinpettit ?) on the announcing alpha blog.  I think have a stream of blogs leading up to KubeCon EU is a great idea!!

**Comment by linsun** [comment]
Additional work following what @howardjohn outlined earlier:

1. Add ambient profile: https://istio.io/latest/docs/setup/additional-setup/config-profiles/
2. Update architecture to add ambient: https://istio.io/latest/docs/ops/deployment/architecture/
3. Describe why & when ambient makes sense? When sidecar makes sense? Feels we need to add ambient under Concepts somewhere.
4. Update to concepts to incorporate ambient.
5. Existing tasks - do we need to mention which ones work for ambient (or not)?

Also, should we have all ambient stuff only under operations? or should we have our existing install etc doc updated?

**Comment by howardjohn** [comment]
In alpha it's not ready to permeate through all of these docs IMO. Eventually I agree

**Comment by linsun** [comment]
> In alpha it's not ready to permeate through all of these docs IMO. Eventually I agree

ok that is fair and will save some time for now

**Comment by kfaseela** [comment]
If anyone has not already taken, I can add the content for Getting started section. @linsun let me know, if that is okay.

**Comment by linsun** [comment]
> If anyone has not already taken, I can add the content for Getting started section. @linsun let me know, if that is okay.

That is great. I was planning to update the get started blog but maybe just need to update it to point to the official get started documentation page.

**Comment by howardjohn** [comment]
I think we should:
* Make a doc. We can use most of the same content as the blog but update it.
* Add a note to the top of the old blog and point to the new doc. We can keep the old content, just say its obsolete?
* Post a short blog announcing "ambient upstream in 1.18.0-alpha, try it in <doc>"

**Comment by linsun** [comment]
How about we add a dedicated section for ambient under operations? @howardjohn @kfaseela 

-Operations
--Ambient
---Get Started
---User Guide (could be merged w/ Get Started initially?)
---Architecture

**Comment by kfaseela** [comment]
> How about we add a dedicated section for ambient under operations? @howardjohn @kfaseela
> 
> -Operations --Ambient ---Get Started ---User Guide (could be merged w/ Get Started initially?) ---Architecture

i think john already added the skeleton yesterday : https://github.com/istio/istio.io/pull/12760

**Comment by linsun** [comment]
> > How about we add a dedicated section for ambient under operations? @howardjohn @kfaseela
> > -Operations --Ambient ---Get Started ---User Guide (could be merged w/ Get Started initially?) ---Architecture
> 
> i think john already added the skeleton yesterday : [istio/istio.io#12760](https://github.com/istio/istio.io/pull/12760)

Ok good, seems to be exactly same as what i have too.

**Comment by whitneygriffith** [comment]
If not already taken, I am happy to work on the following tasks for the usage guide:

- Deploy bookinfo first
- Deploy ambient
- Show we have mTLS via logging and metrics (kiali?? or maybe just grafana)

**Comment by linsun** [comment]
https://github.com/istio/istio/issues/43576 contains a link to our get started doc - we had to get this out asap so we could get the ambient upstream merge announcement out.

Would love your contribution on other items @whitneygriffith!

**Comment by irisdingbj** [comment]
Do we need a blog post about our eBPF redireciton support? If so we are willing to write one @howardjohn @linsun

**Comment by linsun** [comment]
@irisdingbj that is a great idea to cover this feature! would love to see a blog post around that. @howardjohn and I and others can help review it.  I'm hoping it would cover:
1. why ebpf redirect?
2. how to enable this in ambient
3. any performance gains

**Comment by justinpettit** [comment]
> I'll add myself to producer oriented routing - already has something started for that. I can also work with whoever (@justinpettit ?) on the announcing alpha blog. I think have a stream of blogs leading up to KubeCon EU is a great idea!!

Yeah, I'd be interested in working on the alpha announcement blog.  I can take the lead, if you like.

**Comment by linsun** [comment]
> > I'll add myself to producer oriented routing - already has something started for that. I can also work with whoever (@justinpettit ?) on the announcing alpha blog. I think have a stream of blogs leading up to KubeCon EU is a great idea!!
> 
> Yeah, I'd be interested in working on the alpha announcement blog. I can take the lead, if you like.

Sorry, we kinda worked on it as you were on vacation: https://istio.io/latest/blog/2023/ambient-merged-istio-main/

**Comment by hzxuzhonghu** [comment]
Not valid, there is a beta plan

**Comment by kfaseela** [comment]
can we close this then?

**Comment by hzxuzhonghu** [comment]
i think we can
