### ISSUE TITLE
Support `appProtocol` field in IstioOperator ServicePort

### ISSUE THREAD

**Issue by glindstedt** [istio/istio#42759]
**Describe the feature request**

Support the `appProtocol` field in [ServicePort](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#ServicePort) to match the k8s api: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#serviceport-v1-core

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Today when we install istio in our GKE clusters using the `IstioOperator` CRD we add a `cloud.google.com/app-protocols` annotation to the ingress gateway service using `serviceAnnotations` to signal to the GCP load balancer that it should speak `HTTP/2` to it.

We are now experimenting with using the Gateway API instead of an Ingress resource to manage the LB that points to this service, but the docs mention that annotations are no longer supported in the Gateway API controller, and that one should use the `appProtocol` field instead:
https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#requirements

The proto models that istio uses does not have this field currently, so attempting to install an `IstioOperator` with this set on the ports results in this error:
```
Error: generate config: error unmarshaling JSON: while decoding JSON: unknown field "appProtocol" in istio.operator.v1alpha1.ServicePort
```

**Comment by zirain** [comment]
fixed by https://github.com/istio/api/pull/2627
