### ISSUE TITLE
Destinationrule clientTLSSettings TLS SIMPLE stops working from Istio v1.14 onward

### ISSUE THREAD

**Issue by nathluu** [istio/istio#42790]
### Bug Description

After upgrading Istio from v1.13.8 to 1.14.3, destinationrule used to originate TLS connection to the upstream endpoint stops working.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-dst-rule
spec:
  exportTo:
  - "istio-system"
  host: nginx.apps.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
```
`istioctl bug-report` produced below error log says it needs caCertificates but that field is optional as mentioned in istio document https://istio.io/v1.14/docs/reference/config/networking/destination-rule/#ClientTLSSettings
```bash
Running istio analyze on all namespaces and report as below:
Analysis Report:
Error [IST0128] (DestinationRule apps/nginx-dst-rule) DestinationRule apps/nginx-dst-rule in namespace apps has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: nginx.apps.svc.cluster.local
```

### Version

```prose
$ istioctl version
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (2 proxies)
$ kubectl version --short
Client Version: v1.22.11
Server Version: v1.22.11
```

### Additional Information

Below is the full bug report
[bug-report.tar.gz](https://github.com/istio/istio/files/10403272/bug-report.tar.gz)

To reproduce the issue please follow the guideline here https://github.com/nathluu/istio-upgrade-test.
It will work with istio v1.13.8 but not for v1.14 onward.

**Comment by GregHanson** [comment]
1. What does the K8S Service spec look like for the ports exposed by nginx service in apps namespace?
2. Is the nginx service port 443 listening for/expecting https/tls? 
3. Looking at the istio/istio-system/istiod-XXXX/debug/configz from your bug report, I see you have a DestinationRule, VirtualService and Gateway.  The Gateway has port 443 exposed to ingress traffic and authenticates with gw-credentials, this https connection is terminated at the ingress gateway, and sends traffic to the nginx service via the defined behavior in the VirtualService.  The DestinationRule says that traffic to host `nginx.apps.svc.cluster.local` should initiate a new TLS connection when sending traffic to nginx. If the nginx sidecar is not configured to expect encrypted traffic (steps [here](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)), undefined behavior may occur.
```
  {
    "kind": "DestinationRule",
    "apiVersion": "networking.istio.io/v1alpha3",
    "metadata": {
      "name": "nginx-dst-rule",
      "namespace": "apps",
      "resourceVersion": "1187",
      "creationTimestamp": "2023-01-12T14:45:12Z",
      "annotations": {
        "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-dst-rule\",\"namespace\":\"apps\"},\"spec\":{\"exportTo\":[\"istio-system\"],\"host\":\"nginx.apps.svc.cluster.local\",\"trafficPolicy\":{\"tls\":{\"mode\":\"SIMPLE\"}}}}\n"
      }
    },
    "spec": {
      "exportTo": [
        "istio-system"
      ],
      "host": "nginx.apps.svc.cluster.local",
      "trafficPolicy": {
        "tls": {
          "mode": "SIMPLE"
        }
      }
    }
  },
  {
    "kind": "Gateway",
    "apiVersion": "networking.istio.io/v1alpha3",
    "metadata": {
      "name": "nginx-gw",
      "namespace": "apps",
      "resourceVersion": "1171",
      "creationTimestamp": "2023-01-12T14:45:05Z",
      "annotations": {
        "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.istio.io/v1beta1\",\"kind\":\"Gateway\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-gw\",\"namespace\":\"apps\"},\"spec\":{\"selector\":{\"app\":\"istio-ingressgateway\"},\"servers\":[{\"hosts\":[\"nginx.tmanet.com\"],\"port\":{\"name\":\"http\",\"number\":80,\"protocol\":\"HTTP\"},\"tls\":{\"httpsRedirect\":true}},{\"hosts\":[\"nginx.tmanet.com\"],\"port\":{\"name\":\"https\",\"number\":443,\"protocol\":\"HTTPS\"},\"tls\":{\"credentialName\":\"gw-credential\",\"mode\":\"SIMPLE\"}}]}}\n"
      }
    },
    "spec": {
      "selector": {
        "app": "istio-ingressgateway"
      },
      "servers": [
        {
          "hosts": [
            "nginx.tmanet.com"
          ],
          "port": {
            "name": "http",
            "number": 80,
            "protocol": "HTTP"
          },
          "tls": {
            "httpsRedirect": true
          }
        },
        {
          "hosts": [
            "nginx.tmanet.com"
          ],
          "port": {
            "name": "https",
            "number": 443,
            "protocol": "HTTPS"
          },
          "tls": {
            "credentialName": "gw-credential",
            "mode": "SIMPLE"
          }
        }
      ]
    }
  },
  {
    "kind": "VirtualService",
    "apiVersion": "networking.istio.io/v1alpha3",
    "metadata": {
      "name": "nginx-vs",
      "namespace": "apps",
      "resourceVersion": "1172",
      "creationTimestamp": "2023-01-12T14:45:05Z",
      "annotations": {
        "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.istio.io/v1beta1\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"nginx-vs\",\"namespace\":\"apps\"},\"spec\":{\"gateways\":[\"nginx-gw\"],\"hosts\":[\"nginx.tmanet.com\"],\"http\":[{\"route\":[{\"destination\":{\"host\":\"nginx\",\"port\":{\"number\":443}}}]}]}}\n"
      }
    },
    "spec": {
      "gateways": [
        "nginx-gw"
      ],
      "hosts": [
        "nginx.tmanet.com"
      ],
      "http": [
        {
          "route": [
            {
              "destination": {
                "host": "nginx",
                "port": {
                  "number": 443
                }
              }
            }
          ]
        }
      ]
    }
  }
```

**Comment by GregHanson** [comment]
I do see a TLS context in the config_dump for `outbound|443||nginx.apps.svc.cluster.local` cluster, so ingress gateway is configured to send TLS to nginx service

**Comment by GregHanson** [comment]
If possible, please try to reproduce with istio 1.15 or later.  Istio 1.14 and 1.13 has reached end of life

**Comment by nathluu** [comment]
Hi @GregHanson,
Thank you for looking into the issue. I've already tested with all istio version v1.14, v1.15, and v1.16 but it still does not work. I opened the issue for v1.14 as it is the version issue that was found first.

**Comment by nathluu** [comment]
An update:
The same error message from `istioctl bug-report` on istio v1.13.8 but the destinationrule works.
```bash
Error [IST0128] (DestinationRule apps/nginx-dst-rule) DestinationRule apps/nginx-dst-rule in namespace apps has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: nginx.apps.svc.cluster.local
```

**Comment by hzxuzhonghu** [comment]
BTW the report is not right, should be updated

```
	// OPTIONAL: The path to the file containing certificate authority
	// certificates to use in verifying a presented server certificate. If
	// omitted, the proxy will not verify the server's certificate.
	// Should be empty if mode is `ISTIO_MUTUAL`.
	CaCertificates string `protobuf:"bytes,4,opt,name=ca_certificates,json=caCertificates,proto3" json:"ca_certificates,omitempty"`
```

**Comment by nathluu** [comment]
Hi @hzxuzhonghu,

The report was generated by executing the command `istioctl bug-report`.  Which information is not correct? Could u help to point out?

**Comment by GregHanson** [comment]
@nathluu I think he was referring to the `Error` "report" returned by istioctl - that it was  incorrectly reporting an invalid error

**Comment by hzxuzhonghu** [comment]
Yes, i will file a patch to fix the `istioctl bug-report` error

**Comment by aarthi85** [comment]
With reference to this link, https://preliminary.istio.io/latest/docs/reference/config/analysis/ist0128/  
Do we need to specify cacertificates in the destination rule, even if the traffic policy for TLS is set to "SIMPLE"?  Can you please clarify?


We have a ngnix service in kubernetes V1.22 and this service is configured to expect TLS connection at 443 port. We have a destination rule defined for that ngnix service host with traffic policy set to TLS and the TLS mode is set to "Simple", which requires the client to connect without server certificate validation. From the envoy side car logs, the connection to the ngnix service is successfully happening, only if we remove our destination rule. With the existence of our destination rule, no connection has been made to the ngnix service. Can we please get some help to proceed further? We observe this behavior starting with istio 1.14 and above versions.

Thank you for your time.

**Comment by hzxuzhonghu** [comment]
>Do we need to specify cacertificates in the destination rule, even if the traffic policy for TLS is set to "SIMPLE"? Can you please clarify?

It depends, if your app does need to verify server, you can leave it empty

>We have a ngnix service in kubernetes V1.22 and this service is configured to expect TLS connection at 443 port. We have a destination rule defined for that ngnix service host with traffic policy set to TLS and the TLS mode is set to "Simple", which requires the client to connect without server certificate validation. From the envoy side car logs, the connection to the ngnix service is successfully happening, only if we remove our destination rule. With the existence of our destination rule, no connection has been made to the ngnix service. Can we please get some help to proceed further? We observe this behavior starting with istio 1.14 and above versions.

If your client has already made https request to nginx service, you cannot set tls in DestinationRule, which will make tls over tls. It fails for sure.

**Comment by aarthi85** [comment]
Thank you @hzxuzhonghu 

But, the same configuration works fine with istio 1.13 and it doesn't work from istio 1.14 version onward. Can you confirm, if this is the change made from Istio 1.14 version onward?

Thank you

**Comment by aarthi85** [comment]
Hi,

I get this below error in the ingress gateway logs 
"GET / HTTP/2" 503 UC upstream_reset_before_response_started{connection_termination} 

I have the kubernetes service with the following port configuration:
ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443

Gateway terminates the SSL and my virtual service route is the following:
http:
  - match:
    - port: 443
    route:
    - destination:
        host: my-host
        port:
          number: 443

I have no destination rule configured. 
The istio version is 1.16.1

Can anyone please help?

Thank you

**Comment by hzxuzhonghu** [comment]
>Gateway terminates the SSL 

If your kubernetes service "my-host" 443 port is listening on https, you should setup a destinationrule to indicate tls origination from gateway, otherwise gateway will send plaintext to "my-host".

**Comment by aarthi85** [comment]
I applied the following destination rule for my-host:

spec:
  host: my-host
  trafficPolicy:
    tls:
      mode: SIMPLE

Still, I see the same error in my ingress gateway pod logs

GET / HTTP/2" 503 UC upstream_reset_before_response_started{connection_termination} 

Inside my pod, I can access my service without any error, curl http://my-host:443 ---> This is successful.
But, when I try to access using curl -k https://virtual-service-url ---> I get this error "upstream connect error or disconnect/reset before headers. reset reason: connection termination"

Can you please help?

Thank you.

**Comment by nathluu** [comment]
Hi @hzxuzhonghu, @GregHanson,

By setting istio-proxy logging to DEBUG level following this guide https://discuss.istio.io/t/enable-envoy-debugging/7005
Below are the logs I got from istio ingress gateway pod. It says that the sidecar of nginx pod requires ingress gateway to send the client certificate. 
Do you know if any default behavior to enforce mTLS between sidecars for istio >= 1.14?


':status', '503'
'content-length', '95'
'content-type', 'text/plain'
'date', 'Tue, 31 Jan 2023 11:27:00 GMT'
'server', 'istio-envoy'

2023-01-31T11:27:00.522131Z	debug	envoy http2	[C302] stream 23 closed: 0
2023-01-31T11:27:00.522137Z	debug	envoy http2	[C302] Recouping 0 bytes of flow control window for stream 23.
2023-01-31T11:27:00.522315Z	debug	envoy wasm	wasm log stats_outbound stats_outbound: [extensions/stats/plugin.cc:677]::report() metricKey cache hit , stat=12
2023-01-31T11:27:00.522328Z	debug	envoy wasm	wasm log stats_outbound stats_outbound: [extensions/stats/plugin.cc:677]::report() metricKey cache hit , stat=6
2023-01-31T11:27:00.522332Z	debug	envoy wasm	wasm log stats_outbound stats_outbound: [extensions/stats/plugin.cc:677]::report() metricKey cache hit , stat=10
2023-01-31T11:27:00.522335Z	debug	envoy wasm	wasm log stats_outbound stats_outbound: [extensions/stats/plugin.cc:677]::report() metricKey cache hit , stat=14
**2023-01-31T11:27:00.522356Z	debug	envoy pool	[C405] client disconnected, failure reason: TLS error: 268436572:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED 33554464:system library:OPENSSL_internal:Broken pipe**
2023-01-31T11:27:00.522364Z	debug	envoy pool	invoking idle callbacks - is_draining_for_deletion_=false
2023-01-31T11:27:00.522411Z	debug	envoy pool	[C405] destroying stream: 0 remaining
[2023-01-31T11:27:00.375Z] "GET / HTTP/2" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 0 95 4 - "10.244.0.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0" "ec7bf189-4d82-48a7-b7ff-7533252ae686" "nginx.tmanet.com" "10.244.0.18:8443" outbound|8443||nginx.apps.svc.cluster.local 10.244.0.17:40242 10.244.0.17:8443 10.244.0.1:46092 nginx.tmanet.com -

**Comment by nathluu** [comment]
After disabling sidecar injection for the application pod, my setup can work again. So I am not sure if this is the feature or a bug introduced from v1.14 that forces all connections between envoys (ingress gateway <---> istio-proxy, istio-proxy <---> istio-proxy) must be mutual.

**Comment by GregHanson** [comment]
seems like this might be related to https://github.com/istio/istio/issues/42790, which fixes a regression introduced post 1.14

**Comment by keithmattix** [comment]
May also be related to #40680

**Comment by arjun-beathi** [comment]
[45259](https://github.com/istio/istio/issues/45259#issuecomment-1610019639)
This might help if anybody still looking for a workaround.
