### ISSUE TITLE
Cluster role istio-pilot missing permissions

### ISSUE THREAD

**Issue by dhawal55** [istio/istio#428]
I get the below error when trying to access the sample service via ingress:
`error updating ingress rule: User "system:serviceaccount:my-namespace:istio-ingress-service-account" cannot update ingresses.extensions/status in the namespace "my-namespace". (put ingresses.extensions gateway)`

Please add access to `ingresses/status` resource to `istio-pilot` clusterrole.

**Comment by ldemailly** [comment]
not sure if this is still an issue or not, @kyessenov would know as permissions changed recently

**Comment by linsun** [comment]
@dhawal55 could you try this with the latest 0.2 RC?  I didn't hit this issue myself.   Pls reopen if you hit it, many thanks.
