### ISSUE TITLE
TestDeltaEDS  flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#42801]
TestDeltaEDS 
{Failed      delta_test.go:127: received unexpected removed eds resource []
info	controllers	stopped	controller=gateway class
info	controllers	stopped	controller=ingress
info	kube	Controller terminated
info	Registry Aggregator terminated}

**Comment by howardjohn** [comment]
regression since #42687

**Comment by howardjohn** [comment]
will take a look tomorrow
