### ISSUE TITLE
Add DestinationRule ConsistentHashLB.RingHash.maximumRingSize

### ISSUE THREAD

**Issue by kevin-shelaga** [istio/istio#42806]
**Describe the feature request**

It would be helpful to be able to set the maximum ring size for ringhash loadBalancing. 

In my particular scenario I need to be able to set a minimum and maximum of 1 to send all traffic to 1 pod out of N pods. 

**Describe alternatives you've considered**

EnvoyFilter

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB-RingHash

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-ringhashlbconfig

**Comment by howardjohn** [comment]
I don't understand the use case. You want all traffic to go to 1 pod in a service?

**Comment by kevin-shelaga** [comment]
Correct @howardjohn. This is to support cert manager http01 challenges with multiple domains where many challenges pods(like me per domain) are spun up. If you send all traffic to a single pod then domain 1 will succeed and be removed, and so on. The tricky part is the challenge must receive a 200 several times in a row, which it won't get with all pods in the pool on pods to send traffic.

**Comment by howardjohn** [comment]
Can you not hash based on some attribute in the acme request? `maximumRingSize=1` feels like the wrong way to solve this problem

**Comment by kevin-shelaga** [comment]
I don't believe so. I'm open to suggestions though. In another envoy based product I set the min/max to 1 and this did the job. Theres no way for me to know ahead of time where to send the requests and the very inelegant solution was to send all the traffic to 1 pod at a time until the challenge succeeds.

**Comment by kevin-shelaga** [comment]
Would like to add here it's best practice to set min and max according to the envoy docs https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash
