### ISSUE TITLE
From app pod to postgres stateful set pod we are not able to connect

### ISSUE THREAD

**Issue by Rachitmehrotra** [istio/istio#42827]
### Bug Description

Hello Team 
From Application pod we are not able to connect posgres stateful set, both are in same mesh and same namespace.

istioctl version:   1.11.0
kubectl version --short
Client Version: v1.21.14
======================================================
psql -h postgres -p 5432 -U postgres -d noname -c  "select 1";
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
===================================================
but if  remove db from mesh it started working, can someone help me here 

### Version

```prose
kubectl version --short
Client Version: v1.21.14

istioctl version:   1.11.0

istio version 1.15.3
```

**Comment by hzxuzhonghu** [comment]
What is your k8s service yaml? maybe you met protocol selection: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection

**Comment by prakashP786** [comment]
@hzxuzhonghu 

We tried tweaking the service based on recommendations from various article. 
This is the latest one:
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - name: database        #tried other options like http/tcp/tls
      appProtocol: https    
      #protocol: TCP             #removed this
      port: 5432


Thanks.

**Comment by hzxuzhonghu** [comment]
@prakashP786 You should rename `database` to have a protocol prefix like `https-database`

**Comment by prakashP786** [comment]
@hzxuzhonghu We tried changing that but wasn't able to connect. We changed the peerAuthetication to mtls PERMISSIVE and it's working now. Though this is not what we wanted.

**Comment by hzxuzhonghu** [comment]
pasted wrong link above, should be [Server First Protocol can not use tls](https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols)  

Change the port name will resolve
