### ISSUE TITLE
Envoy container prevents job from ending

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#42824]
Hi,

I am running jobs with istio, when my job is complete, my job container is marked as completed, but the envoy container stays up and prevents the job from completing.

I saw a few examples of how to solve this issue, like overriding the command and killing Envoy with the /quitquitquit endpoint, but this is only a workaround, and I am looking for a better way.

any advice?

Thanks!

**Comment by ymesika** [comment]
There is a long discussion about this here: https://github.com/istio/istio/issues/11659
I believe the `/quitquitquit` call at the end of the job is still the way to go although it looks like a workaround.

**Comment by hzxuzhonghu** [comment]
No progress in Kubernetes https://github.com/kubernetes/kubernetes/issues/25908

**Comment by howardjohn** [comment]
dupe of https://github.com/istio/istio/issues/11659
