### ISSUE TITLE
Outdated jaeger integration config at https://istio.io/latest/docs/ops/integrations/jaeger/

### ISSUE THREAD

**Issue by RaiAnandKr** [istio/istio#42838]
### Bug Description

https://istio.io/latest/docs/ops/integrations/jaeger/ says 
```
Once Jaeger is installed, you will need to point Istio proxies to send traces to the deployment. 
This can be configured with --set values.global.tracer.zipkin.address=<jaeger-collector-address>:9411 
at installation time. See the ProxyConfig.Tracing for advanced configuration such as TLS settings.
```

but then the istioctl command itself indicates that the above config is outdated:
```
$ istioctl manifest apply --set values.global.tracer.zipkin.address=jaeger-collector.observability:9411
! values.global.tracer.zipkin.address is deprecated; use meshConfig.defaultConfig.tracing.zipkin.address instead
```

I know we are now recommending the Telemetry API to configure tracing. Should we update https://istio.io/latest/docs/ops/integrations/jaeger/ to either mention `meshConfig.defaultConfig.tracing.zipkin.address` or the Telemetry API?

### Version

```prose
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (9 proxies)

$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.13
```

**Comment by zirain** [comment]
In my plan, we will mark all these deprecated after Telemetry promoted to beta.

**Comment by zirain** [comment]
yes, it would be nice if you can send a PR update page https://istio.io/latest/docs/ops/integrations/jaeger/
