### ISSUE TITLE
Egress tls origination does not work as described

### ISSUE THREAD

**Issue by sourabhdug** [istio/istio#42836]
### Bug Description

This article describes configuring egress tls https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/

That doesn't seem to work however, this does:

https://istio.io/v1.1/docs/examples/advanced-gateways/egress-tls-origination/

### Version

```prose
kubernetes:
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
helm:
v3.10.3+g835b733
I don't have istioctl setup I installed istiod and istio-ingress gateways using this article:
https://istio.io/latest/docs/setup/install/helm/
```

**Comment by howardjohn** [comment]
We need more deytails on what "doesn't work" means

**Comment by peterj** [comment]
FYI, I went through the latest docs with Istio 1.16.1 and it worked fine.
