### ISSUE TITLE
Error while listing IstioOperator CRs

### ISSUE THREAD

**Issue by odira1** [istio/istio#42847]
`Error: error while listing IstioOperator CRs: error while converting to IstioOperator CR - istio-system/installed-state: could not unmarshal: error unmarshaling JSON: while decoding JSON: unknown field "policy" in istio.operator.v1alpha1.IstioComponentSetSpec`

Got the above errror while checking the revision list with: 
`./istio-1.15.4/bin/istioctl x revision list`

Any reason why this happens on istio-1.15.4 but not in the prior versions i have used?

**Comment by zirain** [comment]
assume you're using a newer istioctl with an old istio?
