### ISSUE TITLE
connection_security_policy: set to `mutual_tls` when using HBONE

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#42853]
Today, Server sets `connection_security_policy=mutual_tls` and client `connection_security_policy=unknown` on a given mTLS request (both are unknown for plaintext).

This is a bit confusing, IMO. Users likely expect symmetry, and may incorrectly think traffic is plaintext.

Digging up history, I found a few explanations that this just an implementation limitation and/or that it is intentional, because the client does not know the server verified the TLS.

IMO, with HBONE, we should change to setting this on both client and server side. As far as implementation limitation, I think this is gone now - this is far simpler since we know HBONE will _always_ have `mutual_tls`, so its not even really dynamic at the cluster level.

As far as "we don't know the server verified" - I do not think this is super convincing in the context of HBONE. It is true, but so is the inverse - as a server we do not even know a client verified our certificate, either. Likely `TLS` would have been a more appropriate name, but the ship has sailed. For HBONE, it is part of the 'spec' that both sides should authenticate, so I think its reasonable to trust that the other end is correctly implementing the spec.

cc @kyessenov @zirain

**Comment by linsun** [comment]
Agree this is super confusing and would be good to update if there is no major concerns.

**Comment by kyessenov** [comment]
@howardjohn HBONE is not a special protocol. It's built on top of standards, and last time I've looked, it still inter-operates with the standard protocols outside Istio. The protocol specification does not indicate that the server passes on the server validation bit back to the client. We can't assume that just because something run on a special port means it's secure.

**Comment by howardjohn** [comment]
> but that's meaningless unless you can certify it.

The current `mutual_tls` is just as meaningless. It is impossible to know as a client _or_ server if the other end is verifying things properly. So the logic seems inconsistent; by the logic that we cannot be sure we ought to always put `unknown`.

I think that is pedantic in a way that doesn't suit users well to display `unknown`.; users would rather have "_probably_ mutual_tls unless you have a dumb client that decided not to verify even though they should be" be `mutual_tls` than `unknown`. We can document this niche caveat

**Comment by howardjohn** [comment]
Mutual TLS means the server and client _mutually_ verify each other. Its not just "Server verifies client" in any definition I have found. Given this is impossible to verify for either end, that leaves us two options IMO:

1. Do not report mTLS status at all
2. Report mTLS, with the caveat that each reporter is only _certain_ of half of the claim

**Comment by kyessenov** [comment]
The difference is that by default, all TLS clients verify and TLS servers do not. It's possible to make clients skip verification, but no software is shipped with that as default AFAIK. The opposite is not true for the server verification.

**Comment by howardjohn** [comment]
All software that participates in the mesh does. We can even check if the server requested a client cert if we really want to be extra safe

**Comment by howardjohn** [comment]
This was implemented for ztunnel L4 telemetry, but envoy remains the same

**Comment by linsun** [comment]
Should this be closed? I'm seeing source has mtls as security policy, for example:

istio_tcp_connections_closed_total{reporter="source",source_workload="sleep",source_canonical_service="sleep",source_canonical_revision="latest",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/sleep",source_app="sleep",source_version="latest",source_cluster="Kubernetes",destination_service="unknown",destination_service_namespace="unknown",destination_service_name="unknown",destination_workload="helloworld-v2-same-node",destination_canonical_service="helloworld",destination_canonical_revision="v2",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/helloworld",destination_app="helloworld",destination_version="v2",destination_cluster="Kubernetes",request_protocol="tcp",response_flags="-",connection_security_policy="mutual_tls"} 3

**Comment by howardjohn** [comment]
Its implemented on ztunnel but not envoy

**Comment by LazarenkoA** [comment]
I'm sorry, I ran into the same situation, I read your discussion, I didn't understand what needs to be done in the end to fix the metrics?

**Comment by LazarenkoA** [comment]
@howardjohn ?
