### ISSUE TITLE
Istio sample/helloworld images update

### ISSUE THREAD

**Issue by abasitt** [istio/istio#42855]
Sample app Helloworld images are 6 years old and the existing images don't have IPv6 listener so it doesn't work with IPv6 and dual stack testing. 
The IPv6 fixed was done [here](https://github.com/istio/istio/pull/37224) but the images are not updated. I created updated images with this fix and tested in both IPv4 and IPv6 cluster and it works.

I can create a PR to update the docker file, what's the process of pushing updated images ? Thank you.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by zirain** [comment]
> what's the process of pushing updated images?

I'm also interesting, @ericvn can you share the details?

**Comment by ericvn** [comment]
The process for BookInfo I in the Readme, and we could maybe follow something close to that here (if it's not already explicitly called out). Normally we ask the person who wants to update the image, to first build them (need to verify if a builder is available) and test them. If that works, we have one of the few who can actually push docker.io images do a build and push. The originator then varies that those images are good and finally updates the yaml to point to the new images.

**Comment by abasitt** [comment]
Thank you @ericvn for the explanation.

**Comment by abasitt** [comment]
fixed by https://github.com/istio/istio/pull/42874
