### ISSUE TITLE
Gateway helm chart doesn't support envFrom

### ISSUE THREAD

**Issue by Levarix** [istio/istio#42860]
**Describe the feature request**
The Gateway helm chart doesn't support to use envFrom

**Describe alternatives you've considered**
It's problematic to safely pass env vars via `env:` please add envFrom for loading envs directly from kubernetes secrets.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by cnvergence** [comment]
Hey @Levarix, could https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/ also be helpful for you?
I assume you want to pass some sensitive gateway env vars from the Kubernetes secret, right?

**Comment by Levarix** [comment]
API_AUTHENTICATION_PRIVATE_KEY

**Comment by Levarix** [comment]
and others env vars which can be passed by envFrom instead of env...

**Comment by Levarix** [comment]
I've tried to pass this env var from secret manager directly to values.yml by terraform template, but there is a problem with spaces/tabs, even if I code in base64 earlier. So I want to store the secret in Kubernetes secret in correct format and pass directly via envFrom. That will be much better.

**Comment by Levarix** [comment]
@cnvergence what is the status?

**Comment by cnvergence** [comment]
PR was not accepted, as there are other favorable methods of adding this functionality
https://github.com/istio/istio/pull/42915#issuecomment-1410559529
