### ISSUE TITLE
Fault injection on a VirtualService for ServiceEntry effecting all namespaces 

### ISSUE THREAD

**Issue by veerendra2** [istio/istio#42862]
### Bug Description

Fault injection on a VirtualService in a namespace for a ServiceEntry is effecting all namespaces 

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.15.0
data plane version: 1.15.0 (128 proxies)

$ kubectl version --short
become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.23.13-eks-fb459a0
```

### Additional Information

Created `ServiceEntry`
```
$ k get se -n istio-system -o yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    annotations:
      meta.helm.sh/release-name: istio-external-services
      meta.helm.sh/release-namespace: istio-system
    generation: 12
    labels:
    name: httpbin.org
    namespace: istio-system
  spec:
    exportTo:
    - .
    - default
    hosts:
    - httpbin.org
    location: MESH_EXTERNAL
    ports:
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
    resolution: DNS
kind: List
metadata:
  resourceVersion: ""
```
Created a `VirtualService` in `default` namespace pointing to above `ServiceEntry` external service `httpbin.org` with fault
```
$ k get vs httpbin.org -n default -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 1
  name: httpbin.org
  namespace: default
spec:
  gateways:
  - mesh
  hosts:
  - httpbin.org
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: httpbin.org
``` 
The fault injection should only effect in `default` namespace. But when I `curl httpbin.org` in a pod in other namespace, I see `fault filter abort`
```
$ k exec -it my-pod /bin/sh -n my-project
/ # curl httpbin.org
fault filter abort/ #
```

**Comment by howardjohn** [comment]
This seems expected to me. You can add virtual services for arbitrary domains, so the fact it doesn't match the ServiceEntry due to exportTo=. is not relevant

**Comment by veerendra2** [comment]
Hello, I update the `ServiceEntry`(Removed `exportTo=.`)
```
$ k get se httpbin.org -n istio-system -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    meta.helm.sh/release-name: istio-external-services
    meta.helm.sh/release-namespace: istio-system
  creationTimestamp: "2021-10-07T13:54:56Z"
  generation: 14
  labels:
    app.kubernetes.io/managed-by: Helm
  name: httpbin.org
  namespace: istio-system
  resourceVersion: "746446477"
  uid: c6a84209-7c20-42b1-b789-ea60b08aa1b7
spec:
  exportTo:
  - default
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
    targetPort: 443
  resolution: DNS
```
I still see `fault filter abort`
```
$ k exec -it my-pod /bin/sh -n my-project
/ # curl httpbin.org
fault filter abort/ # exit
```

**Comment by howardjohn** [comment]
Right, I am saying the VS will always apply. Why do you think it should not?

**Comment by veerendra2** [comment]
The VS is created in `default` namespace. I was excepted to see faults in `default` namespace(Correct me if I'm wrong) only not in other(`my-project`) namespace, since I have not created any VS pointing to SE

**Comment by hzxuzhonghu** [comment]
Since your ServiceEntry in istio-system and only exported to `default` ns, so your pod in `my-project` should not see the service defined by SE.  Not to mention vs takes effect.

**Comment by veerendra2** [comment]
Sorry, I didn't mention that I have also tested WITHOUT `exportTo`(i.e. `If no namespaces are specified then the service is exported to all namespaces by default.` from [here](https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry)), I still see same
```
$ k get se httpbin.org -n istio-system -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    meta.helm.sh/release-name: istio-external-services
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: httpbin.org
  namespace: istio-system
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
    targetPort: 443
  resolution: DNS

$ k exec -it my-pod /bin/sh -n my-project
/ # curl httpbin.org
fault filter abort/ #
/ #
/ # exit

```

**Comment by hzxuzhonghu** [comment]
This is expected. The vs bind to a service takes effect on all the callers

**Comment by hzxuzhonghu** [comment]
But there is  workaround, you can set ExportTo on `VS`, then this will only take effect on specified namespaces

**Comment by veerendra2** [comment]
Thanks, I understood now. Is there any way to set this behaviour at cluster level? I mean, when I fault injects rules on `VirtualService` I don't want dev using Kubernetes platform, changing `VirtualService` settings to bypass(At least that is my use case).

Or I can change default behaviour, `ExportTo` always set to namespace that is where `Virtualservice` is created?
