### ISSUE TITLE
Istio tcp connectTimeout is not working

### ISSUE THREAD

**Issue by Asisranjan** [istio/istio#42885]
### Bug Description

when server shutdown abruptly using reboot -f, I have observed the tcp connection is not closing at istio-proxy. Due to this, the request to server is sent and wait till request time out. However the expectation is to detect connection close and return connect timeout after time out happen based on the value setting in destination rule connectTimeout.

dr
---
spec:
  host: 1.2.3.4.8500.HOST
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 400ms
        maxConnections: 10
    loadBalancer:
      simple: ROUND_ROBIN

When target (1.2.3.4) is rebooted forcefully, the connection to this from  istio-proxy is in ESTABLISHED state. Then when consumer sending request, the istio-proxy is forwarding same to target and wait till http timeout as per the value set in VS (2.9s). But the expectation is istio-proxy detects it early and  timeout /response early 
vs
----
spec:
  gateways:
  - mesh
  hosts:
  - 1.2.3.4.8500.HOST
  http:
  - match:
    - gateways:
      - mesh
      port: 8500
    route:
    - destination:
        host: 1.2.3.4.HOST
        port:
          number: 8500
    timeout: 2.9s

### Version

```prose
version.BuildInfo{Version:"istio-release-1.7.6", GitRevision:"74a8d16a80064245a7e31cc884cb6e6e02b08777-dirty", GolangVersion:"go1.14.7", BuildStatus:"Clean", GitTag:"1.7.6"}
```

**Comment by howardjohn** [comment]
1.7 is like 2 years end of life. Can you test on a modern version? This code has changed substantially. Thanks
