### ISSUE TITLE
workload certificate extend rotation period

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#42887]
Hi, 

I activated mtls in my cluster, one of my micro services usually connect to a redis server, and every hour I am getting
```Socket closed unexpectedly```

I did some digging and I believe that the workload certificate managed by istio is rotating every hour, and that what causing envoy to drop the connection.

How can I extend the rotation time, and what is the maximum time it can be scaled? 

If I am wrong please give me any suggestion to solve this issue.

Thanks!

**Comment by howardjohn** [comment]
It should be every 12hr, see SECRET_TTL

**Comment by Rez0k** [comment]
> It should be every 12hr, see SECRET_TTL

Can you be more precise? where SECRET_TTL defined? configmap / secret

If it really set to 12 hours do you have an idea why my issue is happening?

**Comment by howardjohn** [comment]
Its an env var in the proxy container. I don't know why you see that as there is not much info here, but it seems unlikely to be cert rotation

**Comment by Rez0k** [comment]
> Its an env var in the proxy container. I don't know why you see that as there is not much info here, but it seems unlikely to be cert rotation

This env var doesn't exist in my proxy sidecar, how can i inject this env var?
some configmap in istio-system I guess?

btw, thanks for the quick response

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig see proxyMetadata. Note 24hr is the default (my 12hr comment is because it is rotated 50% of the way through)
