### ISSUE TITLE
Istio Ingress-gw not releasing memory after load get released from cluster

### ISSUE THREAD

**Issue by rakanay** [istio/istio#42881]
### Bug Description

I observed after istio upgraded to 1.14.5 , ingress-gw pods not releasing memory after the load.
We have done load test and ingress-gw pods scaled up. But when load test completed and application pods came down, i don't see ingress-gw releasing memory , hence these pods not scaling down.

### Version

```prose
Istio 1.14.5
```

**Comment by rakanay** [comment]
we added PILOT_ENABLE_RDS_CACHE: false and PILOT_ENABLE_XDS_CACHE: false, after checking few issue reports.
still this is not helping.

**Comment by hzxuzhonghu** [comment]
It is not related to istiod envs. Assume it is envoy memory growing. There is an issue https://github.com/istio/istio/issues/30504 reporting it is metrics cause the leak. 
And there are many other issues by searching memory leak, and the reason could be different

**Comment by rakanay** [comment]
@hzxuzhonghu  thanks for your help, but this issue https://github.com/istio/istio/issues/30504 report doesn't clarify anything.
Do you know the resolution for this issue.

**Comment by hzxuzhonghu** [comment]
Sorry not this one, you can search. There is a one, a user has set unbounded metrics
