### ISSUE TITLE
make on Linux fails because of mixer test TestRollingWindowAlgorithm

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#4291]
--- FAIL: TestRollingWindowAlgorithm (0.00s)
	redisquota_integration_test.go:202: **Executing test case 'Request 30 when 50 is available'**
	integration.go:171: fail to new mixer: unable to setup monitoring: unable to listen on socket: listen tcp :9093: bind: address already in use
FAIL

**Comment by mangchiandjjoe** [comment]
Integration test framework is using default port numbers
APIPort:                       9091,
MonitoringPort:                9093,
If integration tests run in parallel, it will cause port number conflicts.

**Comment by mangchiandjjoe** [comment]
@guptasu Could you please take a look? Test frame work can use dynamic port numbers.

**Comment by guptasu** [comment]
fixed
