### ISSUE TITLE
Best practice question: TLS Gateway + Cert Manager voids Cert Manager Namespace policy

### ISSUE THREAD

**Issue by fouadsemaan** [istio/istio#42927]
Cert Manager: 1.11.0
Istio: 1.16.0
K8S: 1.23.7

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[x ] Developer Infrastructure

In various examples where we have a cert manager policy per namespace, the examples that we have seen so far to setup TLS for the gateway involved creating the certificate in the ingress namespace otherwise the ingresscontroller cannot read the generated secret containing the cert details. Example: https://istio.io/latest/docs/ops/integrations/certmanager/

In a multi tenant cluster, are we to deploy the istio ingress controller in every tenant namespace? What is the best practice? There is an advantage in having one ingress controller in the istio ingress namespace as it can handle X numbers of hosts but ran into a wall as soon as we integrated it with cert manager.

We have two competing paradigms where one resource is compressed to one namespace and the other rather making it a matter of policy to restrict usage/access to individual namespaces.

There are options and I wanted to explore best practices from a security standpoint.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/gateway/ describes some deployment models. For the namespace issue, though, see https://github.com/istio/istio/issues/14598 for some more discussion
