### ISSUE TITLE
Ignore HTTP Host header when appProtocol is http

### ISSUE THREAD

**Issue by rittneje** [istio/istio#42930]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

We are using Istio to provide mTLS between the various pods of our cluster. We now have a requirement to restrict one of the urls for one of our services (let's call it `backendApp`) such that it can only be accessed by ingress-nginx.

To do this, we created an AuthorizationPolicy to deny all requests to that url when the source principal is not ingress-nginx's service account. This also necessitated setting the `appProtocol` to `http` for the `backendApp`'s Service.

Upon doing this, ALL the requests to `backendApp` from ingress-nginx started failing, regardless of which url they were for. Testing revealed that it was because by default, ingress-nginx just forwards the Host header as-is, meaning it was set to our cluster's public hostname, instead of `backendApp`'s internal hostname. Somehow, the Host header being set properly is important to the sidecar for `appProtocol: http`.

The reason I'm filing this issue is that behavior is not desirable, nor does it appear to be documented anywhere.

**Describe alternatives you've considered**

There is a way to configure ingress-nginx to override the Host header on the outbound request. However, having to remember to set it for all services is cumbersome, especially because if you don't it leads to unclear errors.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#http describes this

**Comment by rittneje** [comment]
@howardjohn Thanks, I was unable to find that page myself.

That said, I still don't think using the Host header makes any sense. It should be contingent upon the IP that was originally dialed.
1. If I dial the IP of a specific pod, then all HTTP requests should go to that pod. It would be extremely confusing and unexpected for Istio to send it anywhere else.
2. If I dial the IP of a Service, then Istio should load balance across the pods within the Service.

In neither case should it care about the Host header.

**Comment by howardjohn** [comment]
I agree and have been working to change this behavior actually but it's
quite difficult to change behavior in a product due to backwards compat and
it hasn't been too priority so far.

**Comment by rittneje** [comment]
@howardjohn The current behavior is completely unexpected and undesirable. It is really a bug that has already caused us major headache, and will continue to do so. Please re-open this issue.

**Comment by howardjohn** [comment]
It's a duplicate of https://github.com/istio/istio/issues/36596,forgot to link - thanks for the reminder.

This is not a bug. It's an intentional design decision that is documented. We *might* add the ability to change it as tracked in that issue.

**Comment by rittneje** [comment]
@howardjohn It is a "bug" (or misfeature) because Istio claims to be a drop-in service mesh. However, due to mishandling of the HTTP Host header and ignoring the dialed IP, it is not and requires application-level changes to function properly.

**Comment by howardjohn** [comment]
Whatever you want to call it doesn't change what I mentioned above. Like I said - I completely agree with you that the behavior is not correct, but it's also a massive project to change (not to mention backwards compatibility makes it near impossible to change). In ambient mesh the behavior I'd already as you expect

**Comment by rittneje** [comment]
> not to mention backwards compatibility makes it near impossible to change

Why is this the case? I would expect the legacy behavior to go behind some flag and then get dropped in some future version of Istio. Then for each HTTP request the sidecar receives:
- if the legacy flag is set, then use the Host header
- else use the dialed IP

Are you saying that even that change is too complicated? Or is there more going on?

**Comment by howardjohn** [comment]
Sounds easy in concept, hard in implementation. Anyhow this is all tracked and has a design doc linked in the issue above.
