### ISSUE TITLE
istiod helm chart is missing a configuration for topologySpreadConstraints

### ISSUE THREAD

**Issue by oddur** [istio/istio#42938]
**Describe the feature request**
The helm chart for istiod does not allow configuring topologySpreadConstraints for the istiod pods.  Installing a high availability control plane is easier when spreading istiod instances across nodes and zones.  

I suggest copying the way this is done for the gateways in that helm chart. 

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by yitingdc** [comment]
fixed in https://github.com/istio/istio/pull/45175
