### ISSUE TITLE
istio-cni -- Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by Rachitmehrotra** [istio/istio#42940]
### Bug Description

Hello team 
i have tried istio-1.13.7 and istio 1.15.3 but my istio-cni daemonsets are giving warning " Readiness probe failed: HTTP probe failed with statuscode: 503 ". Though its not restating the pods but still in kubectl get events we 
I have not seen any issue related to this but not sure why I am getting this readiness warning.
Is this is known issue ?

### Version

```prose
kubectl version --short
Client Version: v1.21.14

istioctl version:   1.11.0

istio version 1.15.3
```

### Additional Information

kubectl get events -n spyder

LAST SEEN   TYPE      REASON                    OBJECT                                MESSAGE
31m         Warning   Unhealthy                 pod/istio-cni-node-4b756              Readiness probe failed: HTTP probe failed with statuscode: 503
7m3s        Warning   Unhealthy                 pod/istio-cni-node-6hqx2              Readiness probe failed: HTTP probe failed with statuscode: 503
6m45s       Warning   Unhealthy                 pod/istio-cni-node-6vgxh              Readiness probe failed: HTTP probe failed with statuscode: 503
2m51s       Warning   Unhealthy                 pod/istio-cni-node-6vxrg              Readiness probe failed: HTTP probe failed with statuscode: 503
77s         Warning   Unhealthy                 pod/istio-cni-node-bd5b2              Readiness probe failed: HTTP probe failed with statuscode: 503
5m11s       Warning   Unhealthy                 pod/istio-cni-node-bdjmp              Readiness probe failed: HTTP probe failed with statuscode: 503
2m17s       Warning   Unhealthy                 pod/istio-cni-node-bnwtl              Readiness probe failed: HTTP probe failed with statuscode: 503
79s         Warning   Unhealthy                 pod/istio-cni-node-c64m2              Readiness probe failed: HTTP probe failed with statuscode: 503
61s         Warning   Unhealthy                 pod/istio-cni-node-ccrsl              Readiness probe failed: HTTP probe failed with statuscode: 503
4m31s       Warning   Unhealthy                 pod/istio-cni-node-cgxfh              Readiness probe failed: HTTP probe failed with statuscode: 503
3m56s       Warning   Unhealthy                 pod/istio-cni-node-crz6n              Readiness probe failed: HTTP probe failed with statuscode: 503
3m16s       Warning   Unhealthy                 pod/istio-cni-node-csnw2              Readiness probe failed: HTTP probe failed with statuscode: 503
97s         Warning   Unhealthy                 pod/istio-cni-node-d8xl2              Readiness probe failed: HTTP probe failed with statuscode: 503
8m4s        Warning   Unhealthy                 pod/istio-cni-node-fd25b              Readiness probe failed: HTTP probe failed with statuscode: 503
2m16s       Warning   Unhealthy                 pod/istio-cni-node-fs6z5              Readiness probe failed: HTTP probe failed with statuscode: 503
3m2s        Warning   Unhealthy                 pod/istio-cni-node-gvmqc              Readiness probe failed: HTTP probe failed with statuscode: 503
68s         Warning   Unhealthy                 pod/istio-cni-node-kphdx              Readiness probe failed: HTTP probe failed with statuscode: 503
5m22s       Warning   Unhealthy                 pod/istio-cni-node-m2rfj              Readiness probe failed: HTTP probe failed with statuscode: 503
39m         Warning   Unhealthy                 pod/istio-cni-node-mb5gm              Readiness probe failed: HTTP probe failed with statuscode: 503
57s         Warning   Unhealthy                 pod/istio-cni-node-mhm5b              Readiness probe failed: HTTP probe failed with statuscode: 503
2m37s       Warning   Unhealthy                 pod/istio-cni-node-nghds              Readiness probe failed: HTTP probe failed with statuscode: 503
8m40s       Warning   Unhealthy                 pod/istio-cni-node-nhddg              Readiness probe failed: HTTP probe failed with statuscode: 503
3m54s       Warning   Unhealthy                 pod/istio-cni-node-ps7hj              Readiness probe failed: HTTP probe failed with statuscode: 503
4m17s       Warning   Unhealthy                 pod/istio-cni-node-q794g              Readiness probe failed: HTTP probe failed with statuscode: 503
5m6s        Warning   Unhealthy                 pod/istio-cni-node-s9689              Readiness probe failed: HTTP probe failed with statuscode: 503
52s         Warning   Unhealthy                 pod/istio-cni-node-sbn52              Readiness probe failed: HTTP probe failed with statuscode: 503
16s         Warning   Unhealthy                 pod/istio-cni-node-sbq9f              Readiness probe failed: HTTP probe failed with statuscode: 503
6m42s       Warning   Unhealthy                 pod/istio-cni-node-sz7xv              Readiness probe failed: HTTP probe failed with statuscode: 503
4m52s       Warning   Unhealthy                 pod/istio-cni-node-t876l              Readiness probe failed: HTTP probe failed with statuscode: 503
96s         Warning   Unhealthy                 pod/istio-cni-node-tnvzk              Readiness probe failed: HTTP probe failed with statuscode: 503
2s          Warning   Unhealthy                 pod/istio-cni-node-tqnsf              Readiness probe failed: HTTP probe failed with statuscode: 503
3m31s       Warning   Unhealthy                 pod/istio-cni-node-vffsz              Readiness probe failed: HTTP probe failed with statuscode: 503
2m1s        Warning   Unhealthy                 pod/istio-cni-node-vlzjb              Readiness probe failed: HTTP probe failed with statuscode: 503
5m57s       Warning   Unhealthy                 pod/istio-cni-node-vqg6j              Readiness probe failed: HTTP probe failed with statuscode: 503
6m23s       Warning   Unhealthy                 pod/istio-cni-node-vr2td              Readiness probe failed: HTTP probe failed with statuscode: 503
2m22s       Warning   Unhealthy                 pod/istio-cni-node-wdv6m              Readiness probe failed: HTTP probe failed with statuscode: 503
96s         Warning   Unhealthy                 pod/istio-cni-node-x7v8x              Readiness probe failed: HTTP probe failed with statuscode: 503
118s        Warning   Unhealthy                 pod/istio-cni-node-xfqgv              Readiness probe failed: HTTP probe failed with statuscode: 503
2m46s       Warning   Unhealthy                 pod/istio-cni-node-xpswc              Readiness probe failed: HTTP probe failed with statuscode: 50

**Comment by dhawton** [comment]
istioctl version:   1.11.0

I'd recommend bumping your istioctl version to match the version you're trying to install. What are the logs from the istio-cni-node pods saying?

**Comment by howardjohn** [comment]
Needs logs and recent version then we can help more. Thanks
