### ISSUE TITLE
Error creating sidecar proxy for pods in remote cluster in Primary-Remote istio Multicluster Setup

### ISSUE THREAD

**Issue by hafeez134** [istio/istio#42942]
Hi,

I am trying to setup Primary-Remote istio Multicluster Setup following the documentation of istio multiclter on AWS EKS:

https://istio.io/latest/docs/setup/install/multicluster/primary-remote/

However, when the pods in the remote cluster are starting up, the istio side car container is not coming up and I am getting the below error when I describe the replica set. Error: 

"13m         Warning   FailedCreate        replicaset/sample-77d6f96495   Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://xyz.us-west-2.elb.amazonaws.com:15017/inject/cluster/cluster2/net/common-network?timeout=10s": x509: certificate is valid for istiod.istio-system.svc, istiod-remote.istio-system.svc, istio-pilot.istio-system.svc, not xyz-2122434418.us-west-2.elb.amazonaws.com"

xyz-2122434418.us-west-2.elb.amazonaws.com is the load balancer dns name of the Gateway which was provisioned in Primary Cluster (to expose the control plane)

When the sidecar is provisioned, the istiod (in primary cluster) is logging the below error msg:

"info    http: TLS handshake error from 10.0.3.182:44892: remote error: tls: bad certificate"

10.0.3.182 is the Pod IP of the eastwest gateway which is provisioned in primary cluster.

I checked the root certs from Mutatingwebhook both in Primary and remote clusters and those certs seems to be the same. So my guess is, the certs is not the issue here.

Any help in resolving this issue will be appreciated. Thanks a lot !

Thanks,
Hafeez

**Comment by hzxuzhonghu** [comment]
how do you create the mutatingwebhookconfiguration? For aws case, i think you should not depend on istio to self sign cert.

**Comment by hzxuzhonghu** [comment]
Almost forget there is an env `ISTIOD_CUSTOM_HOST` that allows setting custom host
