### ISSUE TITLE
Can't install istio via helm chart without sidecar injection

### ISSUE THREAD

**Issue by lmyslinski** [istio/istio#42954]
### Bug Description

I'm trying to setup Istio on EKS without sidecar injection, but the Helm chart does not support that option. I've tried setting
`podAnnotations.sidecar.istio.io/inject=false` on the Helm chart, but that doesn't work. The docs don't mention on how to achieve this either.

When I install istio via `istioctl install -y` it gets installed correctly without the injection, so the cluster is definitely fine. Any tips on how to achieve the same behaviour via helm?

I'm trying to install `1.16.1` on k8s 1.24.8 via `terraform-helm`:

```
resource "helm_release" "istio_base" {
  count      = 1
  name       = "istio-base"
  repository = var.istio_helm_chart_repo
  chart      = "base"
  version    = var.istio_helm_chart_version
  namespace  = var.istio-namespace

  values = [
    yamlencode(var.base_settings)
  ]

}

resource "helm_release" "istiod" {
  depends_on = [
    helm_release.istio_base
  ]
  count      = 1
  name       = "istio-istiod"
  repository = var.istio_helm_chart_repo
  chart      = "istiod"
  version    = var.istio_helm_chart_version
  namespace  = var.istio-namespace

  values = [
    yamlencode(var.istiod_settings)
  ]

}

resource "helm_release" "istio_ingressgateway" {
  depends_on = [
    helm_release.istiod
  ]
  count      = 1
  name       = "istio-gateway"
  repository = var.istio_helm_chart_repo
  chart      = "gateway"
  version    = var.istio_helm_chart_version
  namespace  = var.istio-namespace

  set {
    name  = "securityContext.fsGroup"
    value = 1337
  }

  set {
    name  = "securityContext.runAsGroup"
    value = 1337
  }

  set {
    name  = "securityContext.runAsNonRoot"
    value = true
  }

  set {
    name  = "securityContext.runAsUser"
    value = 1337
  }

#   set {
#     name  = "podAnnotations.sidecar.istio.io/inject"
#     value = "false"
#   }

}
```

### Version

```prose
Helm version v3.7.2+g663a896

Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.8-eks-ffeb93d
```

**Comment by howardjohn** [comment]
I think `global.operatorManageWebhooks=true` will do it

**Comment by lmyslinski** [comment]
@howardjohn I've just tried that via `helm install istio-ingressgateway istio/gateway -n istio-ingress --set global.operatorManageWebhooks=true` to no avail - the ingress replicate set still has `sidecar.istio.io/inject=true` which results in 

```
  Warning  FailedCreate  0s    replicaset-controller  Error creating: Internal error occurred: failed calling webhook "object.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": context deadline exceeded
  ```

**Comment by lmyslinski** [comment]
I've also tried manually labeling both istio namespaces with `disabled` and it still doesn't work:

```
NAME              STATUS   AGE   ISTIO-INJECTION
default           Active   23h
istio-ingress     Active   22m   disabled
istio-system      Active   18h   disabled
```

**Comment by lmyslinski** [comment]
That however results in the gateway image name staying as `auto` - overriding it manually via `global.proxy.image` has no effect.

**Comment by lmyslinski** [comment]
Even once I modify the control plane installation and the config map has the correct value:

```
        "proxy": {
          "autoInject": "enabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "enableCoreDump": false,
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "holdApplicationUntilProxyStarts": false,
          "image": "docker.io/istio/proxyv2:1.16.1",
          ...

```
The gateway still has the `auto` image set

**Comment by lmyslinski** [comment]
I've tried using both `--set global.proxy.image=x` and `--set values.global.proxy.image=y` on all 3 charts (base, istiod, gateway) and still no success. Is it documented anywhere how this should work?

**Comment by howardjohn** [comment]
Its a value on the istiod install, not the gateway

**Comment by howardjohn** [comment]
operatorManageWebhooks I mean

**Comment by lmyslinski** [comment]
> operatorManageWebhooks I mean

That does work on `istiod` but it still doesn't solve the problem with the gateway. There is now `sidecar.istio.io/inject=false` on `istiod` pods, but istio gateway pod still has `inject=true` and it fails due to lack of auto image with 

```
  Warning  Failed     103s (x4 over 3m12s)  kubelet            Failed to pull image "auto": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/auto:latest": failed to resolve reference "docker.io/library/auto:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  ```

**Comment by howardjohn** [comment]
istio/gateway image requires injection, you have to use the older chart to use gateway without it. see charts/gateways/istio-ingressgateway

**Comment by lmyslinski** [comment]
There is no such chart available. I've checked the entire helm repo all the way back to 1.12:

```
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
istio/istiod 	1.16.0       	1.16.0     	Helm chart for istio control plane
istio/base   	1.16.0       	1.16.0     	Helm chart for deploying Istio cluster resource...
istio/cni    	1.16.0       	1.16.0     	Helm chart for istio-cni components
istio/gateway	1.16.0       	1.16.0     	Helm chart for deploying Istio gateways
```

`helm search repo istio ingressgateway` also turns up empty

**Comment by howardjohn** [comment]
We do not publish it to the helm repo, - because its the legacy chart -  its only in the release tar.gz.

Note we do have some plans to support non-legacy install that also doesn't use injection but don't yet have that in store

**Comment by lmyslinski** [comment]
Ok, I've fallen back to using `istioctl` in that case. I should've went with that route from the start, more hacky but took less than 2 minutes:

```
resource "null_resource" "istio" {
  provisioner "local-exec" {
    command = "istioctl install -y"
  }
}
```

**Comment by howardjohn** [comment]
Thanks for the update. I think this is resolved now and working as implemented for now. Note we are looking into improving this long term with the gateway-api

**Comment by filipisaci** [comment]
I only allow port allow port TCP 15017 and its works.

# Security group of eks cluster
CLUSTER_SG="sg-xxx"
NODE_SG="sg-yyy"

# Add inbound rule to TCP port 15017
aws ec2 authorize-security-group-ingress \
  --group-id $NODE_SG \
  --protocol tcp \
  --port 15017 \
  --source-group $CLUSTER_SG \
  --description "Istio webhook from EKS control plane"
