### ISSUE TITLE
Operation cannot be fulfilled on validatingwebhookconfigurations "istio-validator-istio-system"

### ISSUE THREAD

**Issue by videlov** [istio/istio#42987]
### Bug Description

As part of Kyma installation, we install Istio in our managed k8s clusters. For quite some time we get alerts that are fired because of errors in the `istiod` pods.

Currently I could reproduce the issue with Istio 1.16.1 on a kubernetes-1.25.4 cluster on GCP.

 There were similar issues already reported, but somehow it did not get solved, acknowledged or prioritised. The errors we get are:
```
2023-01-25T15:57:37.606056Z	error	validationController	Failed to update validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail, resourceVersion=131167): Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io "istio-validator-istio-system": the object has been modified; please apply your changes to the latest version and try again
2023-01-25T15:57:37.606156Z	error	klog	Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io "istio-validator-istio-system": the object has been modified; please apply your changes to the latest version and try again
```

Issue happens on our multi-AZ (multi-node) k8s clusters where have `istiod` deployment scaled to 2.

You can easily reproduce it, by installing Istio via `istioctl`, scale the `istiod` deployment with replicas=2 and reinstall Istio with `istioctl`. Problem appears to be related to concurrency when both pods are starting and trying to update `validatingwebhookconfigurations`, a race issue.

https://github.com/istio/istio/blob/f6d7bf648e571a6a523210d97bde8b489250354b/pkg/webhooks/validation/controller/controller.go#L434

This issue is not critical and may be considered with medium priority, but we think you should prioritise it and fix it. Many thanks in advance.

### Version

```prose
❯ istioctl version
1.16.1

❯ kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.4
```

**Comment by howardjohn** [comment]
Do you get an error log or genuine  issue in the system?

Software that is behaving correct has errors; as far as I know Istio is tolerant to these errors so this seems at worst a poor logging scope (error instead of warning)? Is that accurate

**Comment by videlov** [comment]
To your first question: no. This is just an error log in the `istiod` pod logs that is triggering alerts.

We may assume that if it is concurrency issue, it is not really critical since the resource being applied it is the same in the end. In the end it is more or less poor logging scope. You can evaluate if it could be more dangerous in certain cases if applied at the same time from two+ pods.

You should at least keep an eye on this one and prioritise it in your backlog.
