### ISSUE TITLE
Passing in two istioclient Gateway structs to k8s.io/apimachinery/pkg/api/equality/ semantic DeepEquals method causes panic

### ISSUE THREAD

**Issue by knelson7** [istio/istio#43001]
### Bug Description

I have been trying to upgrade istio.io/client-go from version 1.13.9 to 1.14.0 but it causes a panic when testing this piece of code. https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L195. It panics after line 215, if equality.Semantic.DeepEqual(existing, obj). 
To simplify the code, I created a new golang project with a single method that produces the same error and output. 

import (
	istioclient "istio.io/client-go/pkg/apis/networking/v1alpha3"
	"k8s.io/apimachinery/pkg/api/equality"
)

func TestSemanticDeepEquals(t *testing.T) {
	gw1 := istioclient.Gateway{}
	gw2 := istioclient.Gateway{}
	equality.Semantic.DeepEqual(gw1, gw2)
}

Here is the stacktrace that gets printed:
panic: an unexported field was encountered, nested like this:  [recovered]
        panic: an unexported field was encountered, nested like this: int32 [recovered]
        panic: an unexported field was encountered, nested like this: v1alpha3.Gateway -> int32 [recovered]
        panic: an unexported field was encountered, nested like this: v1alpha3.Gateway -> v1alpha3.Gateway -> int32

goroutine 1 [running]:
k8s.io/apimachinery/third_party/forked/golang/reflect.makeUsefulPanic({0x102a0b020?, 0x14000295a40?, 0x140000021a0?})
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:96 +0x138
panic({0x1029c2f00, 0x1400012ab40})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:890 +0x258
k8s.io/apimachinery/third_party/forked/golang/reflect.makeUsefulPanic({0x102a15640?, 0x14000295b48?, 0x140000021a0?})
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:96 +0x138
panic({0x1029c2f00, 0x1400012ab28})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:890 +0x258
k8s.io/apimachinery/third_party/forked/golang/reflect.makeUsefulPanic({0x10298b2c0?, 0x14000295b50?, 0x140000021a0?})
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:96 +0x138
panic({0x1029c2f00, 0x1400012ab10})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:890 +0x258
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.deepValueEqual(0x102a15640?, {0x10298b2c0?, 0x14000295b50?, 0x1?}, {0x10298b2c0?, 0x14000295d10?, 0x200255248?}, 0x2f?, 0x1, 0x2)
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:257 +0x1268
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.deepValueEqual(0x102a0b020?, {0x102a15640?, 0x14000295b48?, 0x10276effc?}, {0x102a15640?, 0x14000295d08?, 0x140002cf7f0?}, 0x27?, 0x1, 0x1)
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:206 +0x12e8
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.deepValueEqual(0x8700000102e934b0?, {0x102a0b020?, 0x14000295a40?, 0x2829?}, {0x102a0b020?, 0x14000295c00?, 0x1400026d4a0?}, 0x1400026d4a0?, 0x1, 0x0)
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:206 +0x12e8
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.deepEqual(0x102a0b020?, {0x102a0b020?, 0x14000295a40?}, {0x102a0b020?, 0x14000295c00?}, 0xc0?)
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:289 +0x2c8
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.DeepEqual(...)
        /Users/ksnelson/go/src/github.com/testDeepEqual/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:273
main.main()
        /Users/ksnelson/go/src/github.com/testDeepEqual/main.go:11 +0xd4

Upon looking at the comparison between version 1.13.9 to 1.14.0 I've seen that similar changes were made to the Authorization Policy and Gateway DeepCopy / DeepCopyObject methods, but I can't figure out specifically why the error is happening or how I'm supposed to fix it. 

### Version

```prose
client version: v1.14.0
Client Version: v1.21.0
Server Version: v1.21.1
```

**Comment by howardjohn** [comment]
This is because Istio types use protobuf, for which reflect.DeepEqual is invalid.

The only options I see are:
- you might be able to modify the global equality thing like equality.Semantic.AddFunc then pass a function using proto.Equal
- Convince the upstream to use some other method for equality (likely doing effectively the same as above)

**Comment by howardjohn** [comment]
I don't think there is anything we can do per https://github.com/istio/istio/issues/43001#issuecomment-1404567641
