### ISSUE TITLE
waypoint: authorization selector

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43009]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kyessenov** [comment]
Ref: #42961

**Comment by linsun** [comment]
Is this done already?  Feels we have this selector in alpha.

**Comment by keithmattix** [comment]
This is being done via targetRefs now
