### ISSUE TITLE
Is it possible to create AuthorizationPolicy in one namespace and target workload from another workspace?

### ISSUE THREAD

**Issue by gitanuj** [istio/istio#43027]
Acc to documentation AuthorizationPolicy scope (target) is determined by “metadata/namespace” which is where the resource is created in.

I have a scenario where I have an **ingress-gateway deployed in namespace1** and **VirtualService (along with Service) deployed to namespace2**. Now **I want to create my Service's AuthorizationPolicy in namespace2** but it only works if I create in namespace1.

I want all my **service related resources in namespace2** and **infra resources in namespace1** but currently that seems impossible. Is there any recommendation on how to achieve this separation with ingress-gateway?

**Comment by howardjohn** [comment]
This is not possible

**Comment by hzxuzhonghu** [comment]
AuthorizationPolicy can only work for workloads in any namespaces when it resides in root namespace. The root namespace by default is `istio-system`
