### ISSUE TITLE
doc generation seems to be trimming the first character when concatenating lines.

### ISSUE THREAD

**Issue by guptasu** [istio/istio#4302]
generated doc is 
_Contains inferred type information about specific instance of ‘metric’ template. This is passed to nfrastructure backends during configuration-time through InfrastructureBackend.CreateSession._

**Notice** the spelling of `nfrastructure`
for proto that looks like:
```
/* Contains inferred type information about specific instance of 'checknothing' template. This is passed to
infrastructure backends during configuration-time through [InfrastructureBackend.CreateSession][TODO: Link to this fragment]. */
message Type {
  
}


```

**Comment by guptasu** [comment]
Seems to be an issue only when using multi line comments.

**Comment by geeknoid** [comment]
I'll look into this, but the usual form for such comments in protos would be using // comments. Evidence suggests (looking at istio.io) that // comments work correctly and don't cause truncation.

**Comment by geeknoid** [comment]
Fixed by [this commit](https://github.com/istio/tools/commit/4f1b1663863b7cb619c4a273c495718286d48820).

**Comment by guptasu** [comment]
@geeknoid thanks and you are right in protos `//` is the common form of comment.
