### ISSUE TITLE
prometheus.TestReport failure. monitoring port in use

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4303]
https://circleci.com/gh/istio/istio/50077?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
 test files]
=== RUN   TestReport
--- FAIL: TestReport (0.01s)
	integration.go:171: fail to new mixer: unable to setup monitoring: unable to listen on socket: listen tcp :9093: bind: address already in use
.
.
.
=== RUN   TestServerInst_Close
--- PASS: TestServerInst_Close (0.00s)
FAIL
FAIL	istio.io/istio/mixer/adapter/prometheus	0.256s
?   	istio.io/istio/mixer/adapter/prometheus/config	[no test files]
```

**Comment by mandarjog** [comment]
The actual failure is in `prometheus_integration_test.go.`

**Comment by kyessenov** [comment]
Thanks. Then it's a dupe of #4309 ?

**Comment by mandarjog** [comment]
#4309 is about a different port, and used a different mechanism to create listeners. 
This one is amount Mixer's own port.

**Comment by cmluciano** [comment]
@mandarjog Is this related to failures in #4506 failures ?

**Comment by douglas-reid** [comment]
@cmluciano to my understanding, the two test issues are distinct with different failure conditions.

**Comment by douglas-reid** [comment]
Closing, as I see the following in the commit history: `Use dynamically assigned port for Prometheus integration tests (#4312)`
