### ISSUE TITLE
Ability to add Volumes and VolumeMounts into Istio Gateway Container

### ISSUE THREAD

**Issue by ChrisJBurns** [istio/istio#43044]
I am following the [SPIRE example](https://github.com/istio/istio/tree/master/samples/security/spire) for integrating with Istio and when it comes to adding the overlay to add the volume and volume mounts to the Gateway, I'm unable to do it.

A bit of context, I don't install Istio with `istioctl`, it's all automated via Flux (GitOps) using the IstioBase, IstioD and Istio Gateway charts and it has worked great so far - however I'm unable to add the overlays as there doesn't seem to be the `values` available under the Istio Gateway Chart. On closer look, I can see that all we're doing is adding volumes and volumeMounts to the Gateway container, which got me thinking about just being able to add them through normal values when the Helm Chart is installed.

I can add this, it shouldn't be too much effort, but just wanted to float this as an option so that folks who are installing and configuration SPIRE and Istio in the same way, don't run into this problem. The changes would be [done here](https://github.com/istio/istio/blob/e2d1da734ca56fe5a06b78c4fd418bb0a14acf45/manifests/charts/gateway/templates/deployment.yaml#L29).

**Comment by zirain** [comment]
https://github.com/istio/istio/issues/39180#issuecomment-1142441351

can you try with [customize-installation-helm](https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/)?

**Comment by hebin-huang** [comment]
I have the same situation. If Istio-gateway helm Chart can provide the option, it will help us much better.

**Comment by keithmattix** [comment]
> https://github.com/istio/istio/issues/39180#issuecomment-1142441351
> 
> 
> 
> can you try with [customize-installation-helm](https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/)?

I'll echo @zirain's comment above and ask if there's a reason this won't work for you?

**Comment by ChrisJBurns** [comment]
So we don't modify the charts locally, we install Istio via the Helm Chart using FluxCD. We've tried to use Flux in order to patch the deployment but no luck. So I thought adding the option of being able to add volumes via the Chart would be a useful feature to add instead of trying to add them via patches
