### ISSUE TITLE
Zipkin cluster not loaded automatically when using Telemetry API

### ISSUE THREAD

**Issue by Stono** [istio/istio#43043]
### Bug Description

Not sure if this is a bug bug, or just a UX change that caught me out, so thought i'd raise it here.

I'm currently trying to move to the Telemetry API / CRDs (eg taking it out of meshConfig and using the first class API).

I noticed that after doing so, I had a bunch of Sidecars with stale `lds`. Also; one of them restarted and couldn't come up because of it.

Looking at the logs I go:

```
{"level":"warning","time":"2023-01-29T10:46:07.476805Z","scope":"envoy config","msg":"gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_9255: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\n0.0.0.0_80: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\n0.0.0.0_9121: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\n0.0.0.0_9600: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\n0.0.0.0_9198: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\nvirtualInbound: envoy.tracers.zipkin: unknown cluster 'outbound|9411||zipkin.istio-system.svc.cluster.local'\n"}
```

The service did have a `Sidecar` resource, but it didn't specify `zipkin.istio-system.svc.cluster.local`.  So it looks like when you use the older telemetry configuration eg (`tracing.zipkin.address`) in `meshConfig`, then sidecars get populated with that cluster automatically in additional to whatever is in the workloads `Sidecar`.

However now that i've switched to the Telemetry API, eg:

```
    extensionProviders:
    - name: zipkin
      zipkin:
        service: zipkin.istio-system.svc.cluster.local
        port: 9411
        maxTagLength: 1024
```

And in the CRD:
```
  tracing:
  - providers:
    - name: zipkin
```

That's no longer the case.

I've worked around this by adding `isito-system/zipkin.istio-system.svc.cluster.local` to the `Sidecar` resource of the affected workloads explicitly, but it certainly feels like a "gotcha" when migrating across.

Personally it feels like the older behaviour is better, and the clusters specified in the Telemetry config should just get loaded automatically.

### Version

```prose
1.16.1
```

**Comment by Stono** [comment]
cc @douglas-reid

**Comment by zirain** [comment]
this works as expected, unlike `MeshConfig`, `Telemetry API` use eds to discover cluster.

**Comment by Stono** [comment]
Well I mean I'd suggest it doesn't work as expected from an end users perspective?

I believe minimising complexity / easing operation is pretty important. Or at least documenting the change to aid users migrating.

**Comment by zirain** [comment]
> I believe minimising complexity / easing operation is pretty important. Or at least documenting the change to aid users migrating.

yes, the doc need improve.

**Comment by Stono** [comment]
Another way to look at it is perhaps to provide the same behaviour as before (from a users perspective).  If they globally configure something like this maybe just globally add it to the clusters the Sidecars get?

**Comment by Stono** [comment]
I just knocked together a quick blog post detailing my migration btw if it helps with any docs: https://karlstoney.com/2023/01/30/upgrading-to-telemetry-api/

**Comment by zirain** [comment]
great! would you like to contribute that as part of official doc/blog?

**Comment by ChrisJBurns** [comment]
@Stono  You're the MVP with that Article :) I've been scouring the Istio docs for a while, and it's not immediately obvious what the _exact_ required code changes are to enable tracing. I've managed to use your example and just slot in jaeger as opposed to the zipkins address and it works like a charm. But appreciated.
