### ISSUE TITLE
Applied istio peer authentication STRICT policy, 502 bad gateway error in the browser

### ISSUE THREAD

**Issue by npravi2003** [istio/istio#43056]
### Bug Description

When Istio Peer Authentication STRICT mode applied, getting 502 bad gateway error in the browser where as same application works with Peer Authentication PERMISSIVE mode.  Is there anything else am i missing to configure for STRICT mode ?  

My environment details.
Istio 1.16.1
AWS EKS 1.24
AWS ALB Ingress Controller v2.4.5 
AWS Application Load balancer ingress

### Version

```prose
kubectl version --short
Client Version: v1.20.0
Server Version: v1.24.8-eks-ffeb93d
```

**Comment by howardjohn** [comment]
Need more details. Are you doing ALB -> Pod with STRICT? ALB doesn't speak mtls so that is expected

**Comment by npravi2003** [comment]
Thanks for your response.  traffic flow is  AWS ALB --> AWS ec2-Instance --> K8s-Service -->K8s Pod

**Comment by howardjohn** [comment]
if you are in STRICT mTLS then it only accepts requests with mTLS. So the ALB/AWS ec2 instance probably don't so they are rejected.

**Comment by howardjohn** [comment]
You can follow https://cloud.google.com/architecture/exposing-service-mesh-apps-through-gke-ingress. Note this is for GKE but the same applies to AWS
