### ISSUE TITLE
Ingress gateway caches waypoint IP during create/delete 

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#43054]
### Bug Description

As part of debugging https://github.com/istio/istio/issues/42866, https://github.com/istio/istio/pull/43012 eventually results in requests succeeding and the correct EDS info in place - BUT there is a 5-10 second window right after deploying a new waypoint where the ingress gateway will attempt to use a stale waypoint IP (the IP of an old waypoint from my delete/recreate tests).  This stale IP does not appear in the ingress gateway `:15000/config_dump?include_eds=true`

1. waypoint was deployed, ingress -> httpbin requests working
2. waypoint deleted, ingress -> httpbin requests still working
3. new waypoint created, brief window where ingress gateway attempts to use step 1's original IP

### Version

```prose
latest experimental-ambient branch
```

**Comment by GregHanson** [comment]
debugging discussion: https://istio.slack.com/archives/C049TCZMPCP/p1675099198271749

**Comment by GregHanson** [comment]
wrote a script for re-creating issue: https://gist.github.com/GregHanson/ef3e168e36573c8db365795abc5776ff

I think this is an ordering of events bug with regards to when a waypoint is added/deleted and the ordering of XDS and WDS events get pushed to tunnels and gateways/sidecars.

The script above captures a config_dump, the `istioctl pc endpoint` output for ingress gateway, and the `/debug/ambientz` output from istiod.  You can see that the workloads information is correct from istiod, but searching for the waypoint IP in the generated dumps.json file, still contains references to the old Waypoint IP in delete cases

**Comment by GregHanson** [comment]
also, as @kyessenov suggested, increasing `TerminationDrainDuration` to something like 120 seconds to allow waypoints to drain connections before deleting, does sometime impact the config_dump output (such as httpbin endpoint clusterLoadAssignment pointing to the correct/incorrect IP) - but does NOT resolve the problem

**Comment by kyessenov** [comment]
A possible cause is that internal listeners don't propagate the drain signal correctly. I'd hope that an internal connection to tunnel listener is closed when upstream waypoint drains, which in turn signals EDS pool with that internal connection to release a host, but maybe something it preventing it.

**Comment by kyessenov** [comment]
Similar things can happen on waypoint. ztunnel must properly terminate connection on receiving GOAWAY for waypoint to exit cleanly. I suspect because of L4 nature, we're missing GOAWAY signal somewhere.

**Comment by howardjohn** [comment]
Is the expectation that on GOAWAY ztunnel immediately closes the connection?

Should see if there is explicit recommendation for GOAWAY+HTTP2 CONNECT if so

**Comment by kyessenov** [comment]
I don't think GOAWAY means stop receiving data. It means stop accepting new streams and is a signal for server maintenance: https://httpwg.org/specs/rfc9113.html#GOAWAY.

For ztunnel to close its active streams, it needs to signal its clients as well for those connections. For example:

sidecar -> ztunnel -> waypoint
1. Waypoint sends GOAWAY.
2. ztunnel stops opening new streams to waypoint.
3. ztunnel propagates GOAWAY for connections to sidecar.
4. ztunnel waits for sidecar to close.
5. ztunnel closes its streams to waypoint.
6. waypoint can finally exit.
