### ISSUE TITLE
Are there any concerns of setting `reinvocationPolicy: IfNeeded ` in `istio-sidecar-injector`?

### ISSUE THREAD

**Issue by LittleWat** [istio/istio#43074]
Hello! I am a beginner at Istio.

We want to add the annotation like the below to pods automatically using our mutating webhook:

```yaml
sidecar.istio.io/userVolume: |-
  [
    {"name": "certs", "secret": {"secretName": "certs"}},
  ]
sidecar.istio.io/userVolumeMount: |-
  [
    {"name": "certs", "mountPath":"/etc/certs",  "readonly":true}
  ]
```

The name of our mutating webhook starts with `0-` to be called earlier than the `istio-sidecar-injector` webhook.
- ref: [Is there a way to change the triggering order of Mutating Webhooks? : kubernetes](https://www.reddit.com/r/kubernetes/comments/g864zf/is_there_a_way_to_change_the_triggering_order_of/)

It worked as expected, however, relying on the fact that k8s invokes the webhooks in alphabetic order is relying on an implementation detail that could change in future versions, and if this ever breaks it will be pretty hard to debug.

So we are considering setting `reinvocationPolicy: IfNeeded ` in `istio-sidecar-injector`. 
Do you have any concerns for this?

Thanks in advance!

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental may be easier mechanism to achieve this goal 

@ramaraochavali I think you looked into this?

**Comment by LittleWat** [comment]
Thank you for your quick reply! I didn't know the `custom-templates` feature and it looks really useful!

Sorry for asking again, but is it possible to apply this `custom-templates` for only the filtered namespace?
This annotation will be necessary for the limited namespace, and we want to filter that.

**Comment by howardjohn** [comment]
Per namespace no, only globally or per pod. zbut you could have it globally apply and then have the filtering logic in the template perhaps.

**Comment by LittleWat** [comment]
I see, I will investigate how to have the filtering logic in the template. Thanks!!

**Comment by ramaraochavali** [comment]
Yeah, while it is annoying to rely on k8s internal for some use cases (we had to just do the same in our use case), there is no option. But in you can try with filtering in templates.
