### ISSUE TITLE
IPv6 proxy protocol fails

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43070]
https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1620477646561349632

cc @bleggett 

Note: we only run a subset of IPv6 tests in presubmit but all of them in postsubmit which could explain why its only now failing

**Comment by bleggett** [comment]
I'll take a look - these tests are only testing PROXY proto IPv4 anyway.

Ok reverting in the meantime if `master` needs to be kept green.

**Comment by howardjohn** [comment]
The test framework allows skipping on IPv6  as well if we want to do that

**Comment by bleggett** [comment]
https://github.com/istio/istio/pull/43072 should do it, my mistake, should have considered that.
