### ISSUE TITLE
Install command using the script doesn't work any more

### ISSUE THREAD

**Issue by SylajaK** [istio/istio#43081]
Under https://istio.io/latest/docs/setup/getting-started/#download, the following command no longer works. It used to work earlier, but something has been broken in the previous release so it doesn't work any more.

$ curl -L https://istio.io/downloadIstio | sh -

Could you please fix this so that we can use this command again?

curl -sL https://istio.io/downloadIstioctl | sh -
Downloading istioctl-1.16.1 from https://github.com/istio/istio/releases/downloa                                                                             d/1.16.1/istioctl-1.16.1-linux-amd64.tar.gz ...
istioctl-1.16.1-linux-amd64.tar.gz download complete! 

Although a message is displayed that the file is downloaded, the file is not visible. Something is broken at your end.
$ tar -xvf istioctl-1.16.1-linux-amd64.tar.gz
tar: istioctl-1.16.1-linux-amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
$ find istioctl-1.16.1-linux-amd64.tar.gz
find: 'istioctl-1.16.1-linux-amd64.tar.gz': No such file or directory

**Comment by ericvn** [comment]
It looks like the `rm` was added a long time ago in https://github.com/istio/istio/pull/23191.

**Comment by hanxiaop** [comment]
Looks like you are using 
`curl -sL https://istio.io/downloadIstioctl | sh -` instead of 
`curl -L https://istio.io/downloadIstio | sh -`

See [this](https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/#install-hahahugoshortcode-s2-hbhb), it will download `istioctl` to `.istioctl`

**Comment by hanxiaop** [comment]
Closed since it's working as expected. Feel free to reopen it if you need more info.

**Comment by orfeas-k** [comment]
Hey I 've bumped on the same thing (Ubuntu 22.04) and cannot find a way to run this successfully.

```
$ curl -sL https://istio.io/downloadIstioctl | sh -

Downloading istioctl-1.19.3 from https://github.com/istio/istio/releases/download/1.19.3/istioctl-1.19.3-linux-amd64.tar.gz ...
tar (child): /tmp/istioctl.lUpOSx/istioctl-1.19.3-linux-amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
istioctl-1.19.3-linux-amd64.tar.gz download complete!
mv: cannot stat '/tmp/istioctl.lUpOSx/istioctl': No such file or directory

Add the istioctl to your path with:
  export PATH=$HOME/.istioctl/bin:$PATH 

Begin the Istio pre-installation check by running:
	 istioctl x precheck 

Need more information? Visit https://istio.io/docs/reference/commands/istioctl/ 
```
