### ISSUE TITLE
show the relationship between Istio Proxy and Envoy in doc?

### ISSUE THREAD

**Issue by zirain** [istio/istio#43086]
istio's data plane related on upstream project https://github.com/envoyproxy/envoy, istio cut branch after envoy released.
Should istio point out the relationship on this page https://istio.io/latest/docs/releases/supported-releases/?

| Istio version | Envoy release |
| ------------- | ------------- |
| 1.17          | 1.25          |
| 1.16          | 1.24          |
|1.15               |               1.23|

cc @howardjohn @lei-tang @ericvn WDYT?

**Comment by howardjohn** [comment]
Seems reasonable to me

**Comment by lei-tang** [comment]
Sounds good to me too.
