### ISSUE TITLE
Build istio/proxy failed in linux

### ISSUE THREAD

**Issue by RunlinXiao** [istio/istio#43087]
Hi, when I run `make build` under the tag 1.16.2 of istio/proxy, I encounter the following problems in different situation:

1. Run make-build directly
ubuntu@ip-10-1-13-15:~/runlin/proxy$ sudo make build
/bin/bash: line 1: clang++: command not found
echo clang
clang
echo clang++
clang++
export PATH=/usr/lib/llvm-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CC=clang CXX=clang++ &&
bazel build --config=libc++ //...
INFO: Repository local_config_cc instantiated at:
/DEFAULT.WORKSPACE.SUFFIX:509:13: in
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl:183:16: in cc_configure
Repository rule cc_autoconf defined at:
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl:143:30: in
ERROR: An error occurred during the fetch of repository 'local_config_cc':
Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
cc = find_cc(repository_ctx, overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
auto_configure_fail(msg)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /DEFAULT.WORKSPACE.SUFFIX:509:13: fetching cc_autoconf rule //external:local_config_cc: Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125, column 33, in cc_autoconf_impl
configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 349, column 17, in configure_unix_toolchain
cc = find_cc(repository_ctx, overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 314, column 23, in find_cc
cc = _find_generic(repository_ctx, "gcc", "CC", overriden_tools)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 310, column 32, in _find_generic
auto_configure_fail(msg)
File "/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
INFO: Repository com_google_absl instantiated at:
/home/ubuntu/runlin/proxy/WORKSPACE:71:19: in
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:192:21: in envoy_dependencies
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:648:26: in _com_google_absl
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:30:23: in external_http_archive
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in
INFO: Repository com_google_protobuf_protoc_linux_x86_64 instantiated at:
/home/ubuntu/runlin/proxy/WORKSPACE:71:19: in
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:194:25: in envoy_dependencies
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:768:30: in _com_google_protobuf
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy/bazel/repositories.bzl:30:23: in external_http_archive
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
/root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in
ERROR: /root/.cache/bazel/_bazel_root/be4dc5ab53cdb7a33977de3d680ca317/external/com_github_google_flatbuffers/BUILD.bazel:82:10: @com_github_google_flatbuffers//:flatc depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: Analysis of target '//extensions/common:node_info_fbs' failed; build aborted:
INFO: Elapsed time: 0.257s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 7 targets configured)
Fetching repository @go_sdk; starting
make: *** [Makefile.core.mk:84: build] Error 1
^^ echo $CC and echo $CXX is both empty

2. [when using Clang/LLVM 15.0.5 in Makefile (tags/1.16.2)](https://github.com/istio/proxy/blob/master/Makefile.core.mk#L35) (echo $CC is empty, echo $CXX is empty) will give same error ^^^ (either correct your path or set the CC environment variable)

3. when using Clang/LLVM 15.0.5 (echo $CC is /usr/bin/gcc-11, echo $CXX is /usr/bin/g++-11)

echo /usr/bin/gcc-11
/usr/bin/gcc-11
echo /usr/bin/g++-11
/usr/bin/g++-11
export PATH=clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 &&
bazel build //...
INFO: Build options --action_env, --define, and --linkopt have changed, discarding analysis cache.
INFO: Analyzed 180 targets (1012 packages loaded, 52935 targets configured).
INFO: Found 180 targets...
WARNING: cleared convenience symlink(s) bazel-bin, bazel-testlogs because their destinations would be ambiguous
ERROR: /home/ubuntu/runlin/proxy/extensions/access_log_policy/config/v1alpha1/BUILD:26:14: Generating proto_library //extensions/access_log_policy/config/v1alpha1:access_log_policy_config_proto failed: (Exit 1): protoc.exe failed: error executing command (from target //extensions/access_log_policy/config/v1alpha1:access_log_policy_config_proto) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe '--cpp_out=bazel-out/k8-fastbuild/bin' ... (remaining 4 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto: warning: directory does not exist.
Could not make proto path relative: extensions/access_log_policy/config/v1alpha1/access_log_policy_config.proto: No such file or directory
INFO: Elapsed time: 16.165s, Critical Path: 0.09s
INFO: 11 processes: 9 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
make: *** [Makefile.core.mk:84: build] Error 1

Would appreciate any help!

**Comment by HOchacha** [comment]
How does it works? Could you explain why the version is the problem?

**Comment by zirain** [comment]
I think the key point is the version of Clang/LLVM, I can build proxy Ubuntu 22.04.
