### ISSUE TITLE
 envoy_on_request(request_handle)..."]:9: bad argument #2 to 'httpCall' (table expected, got string)

### ISSUE THREAD

**Issue by smakintel** [istio/istio#43088]
### Bug Description

I'm trying to make simple API call to another service in same cluster in istio mesh environment.

<html>
<body>

2023-02-02T06:43:08.708795Z error envoy lua script log: [string "function envoy_on_request(request_handle)..."]:9: bad argument #2 to 'httpCall' (table expected, got string)
--
Thu, Feb 2 2023 2:43:08 pm | 2023-02-02T06:43:08.710302Z warning envoy lua script log: envoy_on_response

</body>
</html>

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reporter-lua
  namespace: abccompany-center
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: abccompany-center-reporter
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
           function envoy_on_request(request_handle)
             -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
             request_handle:headers():add("nxl-authorization", "Bearer kava")

              local headers, body = request_handle:httpCall(
              "lua_cluster",
              {
                [":method"] = "POST",
                [":path"] = "/",
                [":authority"] = "nxlpep.abccompany-cloudaz-control-center.svc.cluster.local"  
              },
              "hello world",
              5000)

              if headers[":status"] ~= "200" then
                request_handle:logErr("Auth failed: status=" .. headers[":status"] )
                -- request_handle:respond({[":status"] = headers[":status"]}, response_body  )
                return
              end 
           end
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value: # cluster specification
        name: "lua_cluster"
        type: STRICT_DNS
        connect_timeout: 2s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: lua_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: "nxlpep.abccompany-center.svc.cluster.local"
                    port_value: 80
 ```

### Version

```prose
**ISTIO**
client version: 1.13.1
control plane version: 1.11.4
data plane version: 1.11.4 (15 proxies)

----------------- KUBECTL -------------
Client Version: v1.23.0
Server Version: v1.20.15-eks-fb459a0
```

**Comment by smakintel** [comment]
Argument 2 is already in table format, not sure why it is keep complaining

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reporter-lua
  namespace: abccompany-center
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: abccompany-center-reporter
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
           function envoy_on_request(request_handle)
             -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
             request_handle:headers():add("nxl-authorization", "Bearer kava")

              local headers, body = request_handle:httpCall(
              "lua_cluster",
              {
                [":method"] = "POST",
                [":path"] = "/",
                [":authority"] = "nxlpep.abccompany-cloudaz-control-center.svc.cluster.local"  
              },
              "hello world",
              5000)

              if headers[":status"] ~= "200" then
                request_handle:logErr("Auth failed: status=" .. headers[":status"] )
                -- request_handle:respond({[":status"] = headers[":status"]}, response_body  )
                return
              end 
           end
  # The second patch adds the cluster that is referenced by the lua code
  # cds match is omitted as a new cluster is being added
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value: # cluster specification
        name: "lua_cluster"
        type: STRICT_DNS
        connect_timeout: 2s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: lua_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: "nxlpep.abccompany-center.svc.cluster.local"
                    port_value: 80

**Comment by zengyuxing007** [comment]
This EnvoyFilter configuration is not a problem, it is possible that your new configuration did not take effect.

You can use "curl localhost:15000/config_dump" to see the actual configuration
