### ISSUE TITLE
Why restarting Pods is necessary to reload files mounted in `istio-proxy`?

### ISSUE THREAD

**Issue by LittleWat** [istio/istio#43092]
Hello! I am a beginner at Istio. Sorry to ask a question again. 🙇 

Our pods use the annotation like the below, and `DestinationRule`,  cert-manager's`Certificate` to set up  mTLS.

```yaml
sidecar.istio.io/userVolume: |-
  [
    {"name": "certs", "secret": {"secretName": "certs"}},
  ]
sidecar.istio.io/userVolumeMount: |-
  [
    {"name": "certs", "mountPath":"/etc/certs",  "readonly":true}
  ]
```

I wanted to update the certificate.
About one minutes after I updated the commonName of the certificate,  the certificate of `istio-proxy` was also updated according to the following log: 

```log
2023-02-01T07:27:52.012169Z	info	cache	event for file certificate /etc/certs/tls.crt : REMOVE, pushing to proxy
2023-02-01T07:27:52.012222Z	info	ads	XDS: Incremental Pushing:0 ConnectedEndpoints:4 Version:
2023-02-01T07:27:52.012484Z	info	cache	adding watcher for file certificate /etc/certs/tls.crt
2023-02-01T07:27:52.012502Z	info	cache	read certificate from file	resource=file-cert:/etc/certs/tls.crt~/etc/certs/tls.key
```

I confirmed that the commonName of the cert is updated by running `$ cat etc/certs/tls.crt` in `istio-proxy`.

However, the app seemed to keep using the old cert. I thought so, because the change of the commonName should make the app fail but it continued to succeed.

After restarting the pod using `$ kubectl rollout restart` command, the app failed. This means the app reloaded the new cert.

So my question is why restarting the pod is necessary to reload the file(certificate) mounted in `istio-proxy`?

I thought restarting was not necessary when the certificate of `istio-proxy` is updated.

I may not have done enough research, but if you have any ideas as to why, I would appreciate it if you could share them with us!

**Comment by hzxuzhonghu** [comment]
```
However, the app seemed to keep using the old cert. I thought so, because the change of the commonName should make the app fail but it continued to succeed.
```

you can confirm by checking the secret that envoy loaded by `istioctl pc secret podname`

**Comment by howardjohn** [comment]
I think changing the secret doesn't close existing connections that were established with the old cert. you can kind of force this with https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-TCPSettings maxConnectionDuration

**Comment by LittleWat** [comment]
@howardjohn Thank you for your reply!! Ah, that makes sense!

I am so sorry, but please let me ask another question. 🙇‍♂️ 

As another experiment, I tested certificate expiration and renewal.

I set the Certificate property as follows:

```yaml
duration: 1h
renewBefore: 30m
```

I checked the certificate Secret content, and found that `to Date` - `from Date` was set to two hours

After I left it for a while(more than 11 hours), I checked the kafka client app and istio-proxy log.

- the istio-proxy logs
  - the istio updates the mounted secret every 30 minutes.
- the kafka client (producer) app logs
 - it has been producing the message successfully without any message loss for more than 11 hours. (This is different from what I expected)
 
 
`$ kubectl describe pods` command showed that no events occurred.

I thought that the app would keep using the old cert, and when the cert expired, the app got errors.
But the result was different. The app kept publishing & consuming messages successfully.

If you have any ideas about the cause of this, I would appreciate you sharing them with us. 🙇‍♂️

**Comment by hzxuzhonghu** [comment]
Same as described by @howardjohn , the old connection is there, your client is using it. And the tls handshake happens on connection established not on each request.

**Comment by LittleWat** [comment]
@hzxuzhonghu Thank you for your additional comment! So what will happen when the certificate is expired and updated?
I thought that the connection between the client and the kafka would be lost, but it was kept as described above. 🤔

**Comment by hzxuzhonghu** [comment]
I am not very familiar with kafka sdk, wondering if there is a way to detect there

**Comment by howardjohn** [comment]
Most applications check the certificate during handshake only, they do not continually check

**Comment by LittleWat** [comment]
Thank you for your kind replies! 

> Most applications check the certificate during handshake only, they do not continually check
I see! You are right! 
I disabled the renewal of the certificate and tested how it works. It kept producing/consuming messages even after it expired. After restarting the pod, it failed.

I could know the certificate behavior in detail! Thank you so much for your help!!
