### ISSUE TITLE
Can change istio-proxyv2 access log's START_TIME value according to timezone?

### ISSUE THREAD

**Issue by ningyougang** [istio/istio#43091]
Below red box part is  `START_TIME` , the whole record is an access log
![image](https://user-images.githubusercontent.com/11749867/216264182-b6bc7acc-47ea-4e21-b0c4-ddce238b0dc3.png)

I want istio access log's `START_TIME` value can be changed according to pod's timezone, e.g.
* if change TZ to Asia/Shanghai, `START_TIME` will use `CST` time.
*  if change TZ to Asia/Seoul, `START_TIME` will use `KST` time.

But it seems it doesn't support, my test as below
After installed `tzdata` package to corresponding istio-proxyv2 image, now can configure any timezone using below `TZ` env, e.g.
```
- name: TZ
   value: Asia/Shanghai
```
I tried `Asia/Shanghai`, `Asia/Seoul` ,  `America/New_York` , above `START_TIME` still uses `UTC` value.

There has any method to change istio-proxyv2 access log's `START_TIME ` value according to `TZ`?

**Comment by zirain** [comment]
AFAIK, `%START_TIME %` do not supprt that ENV.

BTW, you can easy to transform it in ETL flow(e.g. logstash etc).

**Comment by ningyougang** [comment]
@zirain got your point, thanks

**Comment by ningyougang** [comment]
@zirain , not through logstash, when the log generated in pod's istio-proxyv2 container‘s file, there has any method to change the `START_TIME` according to different `TZ` or other configuration?

**Comment by zirain** [comment]
AFAIK, no.

you can open a ticket in envoy repo, there're guys know envoy better than me.

**Comment by ningyougang** [comment]
@zirain thanks, i think it is better to keep original raw logs using `UTC`(due to it is a standard timestamp), when store the logs to other places, we can convert as you said.

I will close.
