### ISSUE TITLE
Add windows VM to istio mesh

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#43106]
Hello,

I am using aws and I have some windows vms that I want to add to my istio mesh.
Why? I want to be able to connect to pods via kubernetes services.

I found this guide: https://istio.io/latest/docs/setup/install/virtual-machine/#configure-the-virtual-machine

But this guide is for linux VMS, my question is: can I add windows VMS to istio mesh? if yes, how?

I thought about running a wsl on my windows but if possible I prefer a more "clean" solution.

**Comment by keithmattix** [comment]
Istio does not support Windows containers or VMs at the moment

**Comment by howardjohn** [comment]
Tracked in https://github.com/istio/istio/issues/27893
