### ISSUE TITLE
Enable AUTO_RELOAD_PLUGIN_CERTS by default

### ISSUE THREAD

**Issue by linsun** [istio/istio#43104]
### Bug Description

This was introduced 18 months ago, had been used by many folks. time to enable this by default.

Please comment if you have any objections!

### Version

```prose
1.15
```

**Comment by hzxuzhonghu** [comment]
We donot support root cert reload, so i am not sure what's the use case to reload others

**Comment by linsun** [comment]
It is fairly common to reload intermediate certs.
