### ISSUE TITLE
test flaky: TestUDSLog

### ISSUE THREAD

**Issue by zirain** [istio/istio#43115]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43112/unit-tests-arm64_istio_release-1.15/1621336048955035648
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43112/unit-tests-arm64_istio_release-1.15/1621341252853174272

**Comment by hzxuzhonghu** [comment]
Seen same failure recently

**Comment by zirain** [comment]
from [test grid], it failed rarely, and very hard to reproduce from CI and local dev machine.

**Comment by hzxuzhonghu** [comment]
potential race

**Comment by hanxiaop** [comment]
Still exists https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/43041/unit-tests-arm64_istio/1622863632800944128

**Comment by hanxiaop** [comment]
I see this again https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44865/unit-tests-arm64_istio/1663105072843722752

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46107/unit-tests-arm64_istio/1683312960258183168

**Comment by hzxuzhonghu** [comment]
See the flake again

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/51725/unit-tests-arm64_istio_release-1.21/1805800942696665088

**Comment by howardjohn** [comment]
I fixed this I think, the last link is on 1.21, its only fixed on master.
