### ISSUE TITLE
Implement new optimized waypoint XDS following recent design decisions

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43130]
With the decision to attach policy at the waypoint level rather than to workloads, we need to rework the XDS.

Requirements (details of the XDS are loose requirements, we can do more optimal approaches if they are known):

**Decap listener terminating HBONE**

We need to accept two types of traffic:

VIP has `:authority=VIP:PORT`. We match each port and forward to a listener for the vip_port.

Pod IP traffic has `:authority=POD:*`. We need to allow arbitrary ports. This should forward to "pod listener"

Unknown traffic must be rejected (with 404).

Ideally these routes can be independently updated to make cheap updates on pod scale up or down (VHDS or SRDS), but its reasonable to elide this for the short term.

**VIP listener**

This will apply the policy attached to waypoint. This should include all "workload selection" type policies scoped with parentRef=waypoint, and routes applying to the VIP (note: routing logic should already be fine as imlpemented).

Note the parentRef part will need API changes. In the (very) short term, I think we can decouple the API changes from implementation and just match only namespace policies or with the waypoint label or similar. This is not meant to be something we ship, just to decouple API work from XDS impl.

Because policy is the same across all these listeners, we may consider some sharing mechanism like ECDS, but this is not a top priority

**Pod listener**

This could be one-per-pod, but ideally we consolidate these to at least 1-per-SA. This applies the same policy as above (but no custom routes).

**Clusters**

We need to support a few cases for outbound traffic:

* Send to upstream workload in the mesh. if this was from a VIP, this is load balanced; direct pod listener will always be the same IP.
  We need to validate the SAN. Ideally, we have the exact SAN validated, either by per-IP san validation or multiple clusters per possible SAN (note: this list is likely small; there are typically few SAs per namespace). For a SA scoped waypoint, there is only one SA which simplifies things
* Send to upstream workload *not* in the mesh. We have cases where ztunnel is partially enabled (multi cluster, on boarding, etc). We need to make sure we send to those as plaintext
* Send to workloads in other trust domains ("outbound"). These can be in mesh (route points to another namespace) or out of mesh (route points to example.com).

**Comment by howardjohn** [comment]
@kyessenov I assigned to you as I knew you were already working on this, but that doesn't necessarily means its expected for you to do _all_ of this. We can likely split up parts, especially the API changes

**Comment by kyessenov** [comment]
This is already done for single-SA #42961 with lots of gaps. I think you are entirely missing telemetry above, BTW.

The important protocol question remains about "unknown" pod IPs. I discussed this with @costinm , and I think we should support the following delegation extension in waypoints:

```
Server TLS: Waypoint_SA
CONNECT Pod_IP:Port HTTP/1.1
Host: Pod_IP:Port
X-Validate-SA: Pod_SA
```

This request assumes certain trust to delegate SA verification to the backend, so it can be used to and from waypoints.

On receiving this request, Waypoint can do one of the two things:

1. Establish connection to `Pod_IP:15008`, verify server identity to be `Pod_SA`.
2. Establish connection to any ztunnel SA, continue delegation of SA verification.

Option 1 is best for the passthrough traffic. Option 2 is best for load-balanced traffic since it allows multiplexing over TLS.

**Comment by howardjohn** [comment]
Feel free to add missing areas, very likely there are some and others we will find as we test more.

Agree we need to settle the "unknown" pod IPs question. At this moment, I am not comfortable will a passthrough mechanism but we should discuss more.

**Comment by kyessenov** [comment]
@howardjohn Yes, and I suspect the above is not implementable in xDS without some additional Envoy extensions., so there'll be a lot of derivative upstream work.

**Comment by costinm** [comment]
Not sure what unknown pod IP means, but we need to be very careful with
trusting any client data. It is trouble enough to deal with IP reuse.


We should assume any client capable of redirecting to waypoint can also
follow the rest of the protocol - even if not using ztunnel or ptr-ds.

**Comment by kyessenov** [comment]
@costinm Unknown pod IP means an IP in the namespace without a service, e.g. a Job or a StatefulSet.

We'd like to avoid having a set of IPs be used to drive authn/authz decisions IMHO, and not having a dedicated xDS for this list is also a plus. So for per-namespace waypoint gateway we have only a couple of options:

1. Waypoint only verifies backend SA is in the same namespace as waypoint.
2. Waypoint has to validate a specific SA sent as part of the request (the above).

The more I think about it, (1) might be the best we can do. Any workload in the namespace can pretend to be a waypoint by taking its SA, so there should be no expectation of granularity better than namespace with namespace waypoints.

**Comment by costinm** [comment]
On Fri, Feb 3, 2023 at 4:16 PM Kuat ***@***.***> wrote:

> @costinm <https://github.com/costinm> Unknown pod IP means an IP in the
> namespace without a service, e.g. a Job or a StatefulSet.
>
We have at least 2 options for those - the existing one ( not ideal or
scalable, but works ), and grouping them by 'canonical service'
or service account in a 'virtual' service using ztunnel port. The later
doesn't require any major change in envoy, just Istiod
pretending there is a service ( by SA), and using the header-based session
routing with few adjustments.



> We'd like to avoid having a set of IPs be used to drive authn/authz
> decisions IMHO, and not having a dedicated xDS for this list is also a
> plus. So for per-namespace waypoint gateway we have only a couple of
> options:
>
>    1. Waypoint only verifies backend SA is in the same namespace as
>    waypoint.
>    2. Waypoint has to validate a specific SA sent as part of the request
>    (the above).
>
> The more I think about it, (1) might be the best we can do. Any workload
> in the namespace can pretend to be a waypoint by taking its SA, so there
> should be no expectation of granularity better than namespace with
> namespace waypoints.
>
I don't think (2) is viable - or anything based on 'part of the request'.

And 1 is a given - a waypoint for a namespace will verify SA for workloads
in the same namespace, we no longer have cross-namespace issues.
It still need to follow 'secure naming' and DestinationRule/etc that may
define custom SANs. I.e. just the same as current Istio Cluster works.

We should start a separate discussion about Job/StatefulSet - I personally
think the existing one-listener-per-IP is not efficient but may be
ok for a v1 ambient. But we should prioritize creating a cluster by SA ( or
canonical service if it's more granular ). All Jobs/StatefulSets
will have a ztunnel port open - we don't really need a Service object to
create a Cluster.

**Comment by howardjohn** [comment]
@kyessenov I want to clarify the types of traffic:

1. Traffic to a VIP 'in scope' for the waypoint
2. Traffic to a pod IP 'in scope' for the waypoint
3. Traffic to any other IP

'In scope' means in the namespace or SA the waypoint runs for.

(3) must be blocked. (2) includes pods that have a Service -- they can still be accessed directly even if they have a Service.

While I agree SA granularity is *less* clear than NS, it's still important. "Create a pod" is not the only way to access a token; using SA scoping prevents lateral movement. Even for "Create a pod", more sophisticated users have checks outside of k8s RBAC preventing this (CI/CD, Gatekeeper, etc). So I wouldn't like to wholesale decide that SA granularity isn't an important aspect, at least without a clearly made tradeoff with the complexity it brings to implement.

**Comment by howardjohn** [comment]
I would think an option to have a list of IPs in the HBONE RDS, pointing to a Pod listener (per SA) pointing to a HBONE encap (per SA) is plenty scalable for v1 and meets the requirements. We then have O(pods) vhosts, O(SA) listeners and O(SA) clusters. Only the first is concerning to me, and that can improved with VHDS or SRDS in a followup.

If this isn't viable, can you clarify why not? Is it not correct, not scalable, etc?

**Comment by costinm** [comment]
Agreed, but 2 also includes pods that don't have a service - Job,
StatefulSet, Pod that isn't selected.

And I also agree that we can scale just enough with what we do now for the
stateful set. I'm not sure how 'one listener per SA' will
work - can you do 'original dst' based on the ztunnel header? If yes, it's
the same as what I was suggesting, i.e. have one listener and
cluster per SA. ( forget about per canonical service, probably not needed ).

(3) - yes, any dest IP MUST be a pod (or WorkloadEntry) in the same
namespace.

**Comment by costinm** [comment]
Also - for implementation, I think we should prioritize what we can do with
current envoy or minimal changes, so we can get v1 ambient shipped.

After that we can optimize - we are not bound to the first impl.

**Comment by kyessenov** [comment]
Using RDS to push routes based on IP is basically like having a service for every workload IP.  None of the xDS systems scale to that level of granularity or behave correctly (e.g. I'm not sure how to handle IP reuse or draining). Routes are generally a config plane domain, not subject to load balancing decisions.

@costinm I don't think it's enough to ship whatever is implementable, the goal is to get it to scale. I'm fine shipping RDS way for now, but it's a pretty serious flaw, that's coming from Istio, and we're explicitly trying to fix the mistakes we made (e.g. one listener per IP).

Do we know pod CIDR range? We can really just filter pods by CIDR and rely on SAN to filter namespaces.

**Comment by kyessenov** [comment]
@howardjohn I agree that SA is important, but once a user opts into waypoint that's per namespace, it's increasingly hard to enforce SA-based policies. We can't easily express a destination principal in authz anymore, for example. So if we can't differentiate SA within namespaces for authz in the waypoints, perhaps, we shouldn't treat all SAs as interchangeable in the waypoint, and only validate namespaces.

**Comment by costinm** [comment]
What is wrong with creating a fake service ( by service account ) for all
workloads in the namespace ?

**Comment by costinm** [comment]
CIDR is not viable - each node gets a CIDR, IPs are re-allocated. So an IP
may now be a pod in namespaceA, 1 min later a pod in namespaceB. At least
with IPv4.

That's why including the pod name in the PTR-DS and checking it ( at some
point - not blocker IMO) is good.

**Comment by howardjohn** [comment]
Each IP forming a vhost is pretty small if we can update vhosts independently. We serve 10k routes in gateways today, that is order of magnitude more than expected IP in a namespace and with Delta updates it shouldn't be a big issue imo. This feels like a problem we can implement now and optimize in 2024

**Comment by costinm** [comment]
Agreed. And for Waypoint we can start using delta, lower risks.

**Comment by kyessenov** [comment]
@costinm That's sort of why I don't like IP in the routes. We cannot promise that a route update arrives in time before IP churns. So at the very least we need to push SA or a pod name for extra validation per route (and run a risk of denying valid requests), and also re-validate on the upstream regardless of the route. Yes, we can scale Envoy with VHDS or what not, but can you say the same for nginx or other proxies?

For alpha, let's continue using IP filtering with RDS (and maybe push SA as well with it). But we have to have general upstream SAN validation in place, and re-evaluate it for beta.

**Comment by costinm** [comment]
Agree with most of what you say. 

Note that PTR-DS and XDS are not part of the protocol or required for ambient. Nginx can use something else, or they can use XDS. 

Still - protocol should include all info, not only IP. And in some cases all we have is the IP from capture - and something needs to tell us (or nginx) where to send, direct to pod, or waypoint, east west or egress gw. Few cases can be handled via CIDR and routing, but given how IPs are allocated to pods and nodes - at least 'next hop' is needed. If we get next hop - we can also get pod name, sa and maybe a bit more.

**Comment by SkyfireFrancisZ** [comment]
PR out for review.

**Comment by kyessenov** [comment]
The main PR to re-organize xDS was merged: https://github.com/istio/istio/pull/42961.

The next step is to restore authz, which I'll work on (discussed this with John): https://github.com/istio/istio/issues/43009. We'll use waypoint workload selectors until Istio APIs are changed.

There are also a couple of follow-up issues that I want to fix:
* add HTTP direct listener for direct pod access;
* add HTTP telemetry on that listener;
* fix baggage propagation (I think it suffers from hashing issue like connect authority).

**Comment by SkyfireFrancisZ** [comment]
mostly done, need to close up a few loose ends.

**Comment by keithmattix** [comment]
Not stale unless @SkyfireFrancisZ tells me otherwise
