### ISSUE TITLE
istio-gateway https node port not working when using AWS ELB HTTPS listener

### ISSUE THREAD

**Issue by edgan** [istio/istio#43141]
### Bug Description

&nbsp;&nbsp;I have tried to get `istio-gateway` and a AWS ELB HTTPS listener using an `ACM` certificate for the SSL certificate. We originally were going to do the standard `cert-manager` setup with `LetsEncrypt` SSL certificates, but we will be recreating the clusters so often we will likely run into `LetsEncrypt`'s rate limits. Note this all worked with `cert-manager` instead of `ACM` for SSL certificates.

&nbsp;&nbsp;I tried 1.14.6 and 1.14.0, because of #41196. It didn't seem to help.

&nbsp;&nbsp;The issue seems to revolve around the node port. Going to method 1 and 2 vs 3, it seems like `istio-gateway` assumes you are going to do `HTTPS to HTTPS` not `HTTPS to HTTP`. Hence the connection of the HTTPS listener on the ELB to the `https` node port in all cases. This is less than ideal, because `HTTPS to HTTPS` then requires setting up a self-signed certificate to make that work. Alternatively I could use `cert-manager` to generate a SSL certificate to replace the self-signed certificate, but that brings even more complexity on top of an extremely complex setup. It would be nice if `Method 1` just worked, and that would require `istio-gateway` to point the ELB HTTPS listener at the `http2` node port.

&nbsp;&nbsp;We are trying to use `istio-gateway` as our ingress controller, because we are already using `istio` for our service mesh. But if I can't get this working we are going to have to switch to something else.

The chain of the HTTP(S) flow:
1. Browser, works
2. Route53 zone entry via `external-dns`, works
3. ELB load balancer created via `aws-cloud-controller-manager` and connected to the `service`, works
4. Node port on the `service`, either doesn't work or partially works
5. The `service` of the application behind `istio-gateway`, works
6. The `pod` of the application behind the application `service`, works

Method 1:
HTTPS listener to HTTP 
1. The HTTPS listener on the ELB points at the `https` node port on the Kubernetes `service`.
3. The node port for `https` isn't listening. As in trying to form a TCP connection to it gets a `connection refused`.

Service addition:
```
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789123:certificate/af8519ac-a4ad-11ed-b9df-0242ac120003
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
```

Method 2:
HTTPS listener to HTTPS
1. The HTTPS listener on the ELB points at the `https` node port on the Kubernetes `service`.
2. The node port for `https` isn't listening. As in trying to form a TCP connection to it gets a `connection refused`.

Service addition:
```
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789123:certificate/af8519ac-a4ad-11ed-b9df-0242ac120003
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
```

Method 3:
HTTPS listener to HTTPS and a self-signed SSL certificate configured
1. The HTTPS listener on the ELB points at the `https` node port on the Kubernetes `service`.
2. The node port for `https` is listening. As in trying to form a TCP connection to it gets an connection.
7. But trying to connect to the `https` node doesn't actually make you a SSL connection as confirmed by use `openssl s_client -connect ip:port`

Service addition:
```
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789123:certificate/af8519ac-a4ad-11ed-b9df-0242ac120003
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
```

### Version

```prose
1.16.2
1.16.1
1.14.6
1.14.0
```

### Additional Information

Recent like issue:
#41196 

Related issue from `2018` that talks about how to configure for this idea:
https://github.com/istio/istio/issues/6566

Self-signed certificate instructions:
https://github.com/aws-samples/eks-alb-istio-with-tls#generate-self-signed-tls-certificates

Service yaml:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gateway
    meta.helm.sh/release-namespace: istio-system
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789123:certificate/af8519ac-a4ad-11ed-b9df-0242ac120003
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https    
  creationTimestamp: "2023-02-03T20:24:05Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway
    app.kubernetes.io/version: 1.16.2
    helm.sh/chart: gateway-1.16.2
    istio: gateway
  name: gateway
  namespace: istio-system
  resourceVersion: "6701"
  uid: e57e5c84-ba2c-4a67-9cb1-bab09ce8ae89
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.4.201
  clusterIPs:
  - 10.43.4.201
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 32461
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 32299
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https     <---------
    nodePort: 31672 <---------
    port: 443       <---------
    protocol: TCP   <---------
    targetPort: 443 <---------
  selector:
    app: gateway
    istio: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: fb31f1c84ba2c4a679cb1bab09ce8ae8-1861145214.us-east-1.elb.amazonaws.com
```

VirtualService yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server
  namespace: argocd
spec:
  hosts:
  - "*"
  gateways:
  - argocd-server-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
```

Gateway yaml:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"argocd-server-gateway","namespace":"argocd"},"spec":{"selector":{"istio":"gateway"},"servers":[{"hosts":["argocd.acme.com"],"port":{"name":"https","number":443,"protocol":"HTTPS"},"tls":{"credentialName":"argo-tls","mode":"SIMPLE"}},{"hosts":["argocd.acme.com"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2023-02-03T20:24:12Z"
  generation: 1
  name: argocd-server-gateway
  namespace: argocd
  resourceVersion: "1117"
  uid: 5dc9a1c7-a22f-4908-aa4f-b12e044ee425
spec:
  selector:
    istio: gateway
  servers:
  - hosts:
    - argocd.acme.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls-secret
      mode: SIMPLE
  - hosts:
    - argocd.acme.com
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Comment by Ishujeet** [comment]
@howardjohn  I am also facing the same. I have tried
`Disable SNI matching in the Gateway by setting the hosts field to *` still ssl is failing. LoadBalancer not doing any tls termination. I am using Azure L4 LoadBalancer.
