### ISSUE TITLE
Invalid alpha3 rule breaking the entire mesh (for example by generating invalid MTLS settings)

### ISSUE THREAD

**Issue by costinm** [istio/istio#4314]
Update: the original bug was fixed by making the alpha3 rule valid. What remains is adding back
the original invalid rule as a regression, and fixing the code to not generate invalid MTLS settings
(ignore the rule).

This seems to be the only alpha3 test failing right now - and only in MTLS.

A bit hard to figure out from logs - to repro I suggest running only that test (commenting out all other route tests), and check the sidecar output. 

Traced it down to: 
```
 Offending document key: #/ssl_context/verify_subject_alt_name
[2018-03-16 00:52:08.052][17][warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: tcp proxy: unknown cluster 'out.orig-dst-cluster-tcp' in TCP route
[2018-03-16 00:52:09.015][17][warning][upstream] external/envoy/source/common/upstream/cds_subscription.cc:67] cds: fetch failure: JSON at lines 494-507 does not conform to schema.
 Invalid schema: #/definitions/ssl_context/properties/verify_subject_alt_name
 Schema violation: type
 Offending document key: #/ssl_context/verify_subject_alt_name
```

Which in turn corresponds to:

```
  {
    "name": "out.v2.pilot-auth-test.svc.cluster.local|grpc",
    "service_name": "v2.pilot-auth-test.svc.cluster.local|grpc",
    "connect_timeout_ms": 5000,
    "type": "sds",
    "lb_type": "round_robin",
    "ssl_context": {
     "cert_chain_file": "/etc/certs/cert-chain.pem",
     "private_key_file": "/etc/certs/key.pem",
     "ca_cert_file": "/etc/certs/root-cert.pem",
     "verify_subject_alt_name": null
    },
    "features": "http2"
   },

```

For reference the rule is: 

v1alpha3/rule-regex-route.yaml.tmpl

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default-route
spec:
  hosts:
    - c
  http:
    - match:
      - headers:
          foo:
            regex: "b.*"
        source_labels:
          version: v1
      route:
      - destination:
          name: c
          subset: v2
        weight: 100
    - route:
      - destination:
          name: v2
        weight: 100

```

**Comment by costinm** [comment]
+Louis - I think the rule itself is invalid - "destination: name: v2" should be name: "c" and subset. 

But I think this but raises a much bigger issue - if we send any invalid config to Envoy the entire cluster will fail, in this case the invalid cluster prevents loading the entire CDS. 
We need to add more 'invalid config' tests - and maybe for 0.8 add some pilot-side validation (at least it will be better with the proto-based v2 - but even there we should do additional checks).

**Comment by wattli** [comment]
@costinm, could you provide more steps to reproduce or error link? So I can investigate more? The first impression is verify_subject_alt_name = null seems not right, and it's generated by pilot.

**Comment by vadimeisenbergibm** [comment]
I wonder if this is related: ci/circleci e2e-pilot-auth fails on an empty PR https://github.com/istio/istio/pull/4321 on v1alpha3 route rules test.

**Comment by ijsnellf** [comment]
Thanks for diagnosing this @costinm. I created a fix for the badly defined config: https://github.com/istio/istio/pull/4327

@vadimeisenbergibm: yes, it _should_ be causing failures in circleci as well.

**Comment by wattli** [comment]
@ijsnellf, thanks for the fix, can we mark this as closed now?

**Comment by costinm** [comment]
@ijsnellf  Thanks for the fix - but that's just hiding 2 much bigger problems. 

Can you add back the (broken) rule first, so we can repro the 2 problems:
1. In some cases we seem to generate spiffee = null - not clear what and how, but we need to find the correct value.
2. Null should never be generated - it makes the entire CDS invalid and nothing will work in the mesh until the rule is removed.

To reproduce: just apply the (broken) rule, and watch for CDS, in an auth-enabled cluster.

**Comment by costinm** [comment]
@mandarjog

**Comment by wattli** [comment]
This seems to be a v1 issue, and is this still happening? @ZackButcher
