### ISSUE TITLE
Reference Envoy version in Istio release note

### ISSUE THREAD

**Issue by HenryYanTR** [istio/istio#43140]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Envoy is the critical data plane component for Istio. Envoy changes directly impact application at runtime. Currently it's difficult (although not impossible) for track the version of Envoy proxy being used by each Istio releases, hence it's difficult to plan/track the impact of Istio upgrade caused by Envoy change.

**Describe alternatives you've considered**
Suggest reference Envoy version in Istio upgrade note, and promote user awareness of potential impacts caused by Envoy upgrade.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
please checkout https://github.com/istio/istio.io/pull/12579

**Comment by ericvn** [comment]
Closed by https://github.com/istio/istio.io/pull/12579. Please re-open if more info is needed. We also had https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#what-envoy-version-is-istio-using in the past.
