### ISSUE TITLE
Sidecar HBONE: disable metadata exchange

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43161]
Currently we still use MX for these, which is not desired

**Comment by howardjohn** [comment]
cc @kyessenov. Naively, seems like we need to be able to selectively enable it per endpoint instead of per cluster. Unless we already have that with alpn negotiation and we just have some mismatch there

**Comment by kyessenov** [comment]
No, you are right, we should always disable MX when using HBONE. Is the problem a mixed cluster, with some internal (tunnel) endpoints and some real endpoints?

ALPN negotiation should in theory work since HBONE is plaintext in the context of this upstream cluster. MX checks for its ALPN string to do anything.

**Comment by howardjohn** [comment]
I don't think it's mixed but our code doesn't differentiate anyways. Let me check what's going on with ALPN.

Does ALPN impact the http mx as well? That is what I was seeing, not the TCP one which would have completely broken the tratfic

**Comment by kyessenov** [comment]
HTTP MX doesn't check for ALPN (or TCP MX), and is known to leak headers everywhere.
It's inherently per downstream, so it would be a new rewrite to apply it as an upstream HTTP filter.

**Comment by keithmattix** [comment]
Not stale

**Comment by kyessenov** [comment]
Maybe, I don't quite understand which MX and where it's used. This might be referring to sidecars sending MX headers to ambient, which is yet another category for https://github.com/istio/api/pull/2910/files. Per earlier discussion, if a cluster is mixed with ambient and non-ambient endpoints, there's not much we can do.

**Comment by howardjohn** [comment]
The issue, iirc, is we add the HTTP MX headers to the inner payload of the HBONE request. Like the work in https://github.com/istio/api/pull/2910/files we can probably add logic in the proxy to not do this if we are going to tunnel it anyways. I don't think we need an API for that, just the proxy side to check the tunnel metadata

**Comment by howardjohn** [comment]
Isn't Greg's PR checking endpoint metadata? If not, then I agree that may be problematic

**Comment by kyessenov** [comment]
No, downstream filters only see clusters, upstream filters see endpoints. We can refactor it to be upstream filter but it adds to the scope.
