### ISSUE TITLE
Improve prow-presubmit test: ./tests/integration/example/integration.sh

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#4317]
This test is dangerous if run locally. It does a git reset --hard, a clone of istio/proxy and possibly other things.

**Comment by ldemailly** [comment]
improve, not remove

**Comment by sebastienvas** [comment]
Yeah I don't understand why we should remove this. This test is running in memory and have the right arguments to be in presubmit. The fact we do git reset --hard needs to be fixed, and the fact that its not using the right config needs also to be fixed proxy developers.

**Comment by sebastienvas** [comment]
Assigning @qiwzhang to find an owner to fix this

**Comment by yutongz** [comment]
Yes, I agree we shouldn't use "git reset". I will fix this specific part. But it's not the key reason for the test failure. Someone need to figure it out :) 
/assign @yutongz

**Comment by qiwzhang** [comment]
This test is using a envoy_config means for manual test.   Since we (proxy developers) did not do manual test for a long time, it was outdated. 

1) This test is using "git clone" latest proxy to get the config and start_envoy script.  this may post some problems.  should it get the version pointed by $PROXY_SHA?  Should these two files merge into istio repo?

2) If the config is used by istio pre-submit test,  should proxy also test it in its pre-submit to make sure it will not break?

I think the owner of this test not longer works for Istio any more.  We need new owner of this integration test.

**Comment by yutongz** [comment]
@qiwzhang if proxy folks don't use those scripts/config, I am happy to have them in istio/istio.

@hklai would be the onwer of this integration test, so please keep him in the loop.

**Comment by qiwzhang** [comment]
We only use them for manual test occasionally. @yutongz

**Comment by sebastienvas** [comment]
I think we still need of way to start all the components in memory such that we can quick integration testing. I think @qiwzhang 's point is valid: We should also have this being testing in proxy presubmit. I think there is another issue about this.

**Comment by yutongz** [comment]
These tests require mixer binary which takes around 5 mins to build. It's going to be a pain for proxy folks to have this in presubmit.

I think the possible solution could be one of the following:
1. Move those scripts/config into istio/istio. When you need to do manual test (assuming not often), you can checkout from istio/istio.
2. Keep them in proxy. And test them against these integration tests in proxy-postsubmit.

**Comment by wattli** [comment]
Agree with Laurent, we can't disable some test because they are not stable. Because it will be harder and harder to bring it back. Unless we really don't need them.

**Comment by ldemailly** [comment]
the rest of the makefile already downloads envoy binary so it should use that and not clone proxy

**Comment by ldemailly** [comment]
and btw the test was very stable, it's been green for months, it only broke because of an api change in envoy config (change which could be hit by customers https://github.com/istio/proxy/issues/1210 - I hope not)

**Comment by yutongz** [comment]
We do use the downloaded envoy binary here https://github.com/istio/istio/blob/master/tests/integration/example/integration.sh#L34, the problem is the start_envoy script

**Comment by ldemailly** [comment]
let's move (/copy for now if needed) start_envoy to istio/istio

**Comment by qiwzhang** [comment]
+1 for copy them over to Istio.
