### ISSUE TITLE
leader election: not grabbing locks fast enough

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43171]
When a leader exits, configmap looks like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"","holderKey":"","leaseDurationSeconds":1,"acquireTime":"2023-02-06T23:36:20Z","renewTime":"2023-02-06T23:36:20Z","leaderTransitions":0}'
  creationTimestamp: "2023-02-06T23:34:43Z"
  name: istio-ambient-controller
  namespace: istio-system
  resourceVersion: "299266"
  uid: 5122813f-327a-451f-bc84-d071d9489797
```

This *should* be grabbed immediately, but it isn't. I think it may be a bug in our holderKey fork

**Comment by hzxuzhonghu** [comment]
how do you see it is not grabbed immediately

**Comment by howardjohn** [comment]
just restart istiod and see it takes about 15s. At one point it was instant (since the old one drops it when it shuts down),so seems like a regression. I didn't have a chance to look into detail

**Comment by hzxuzhonghu** [comment]
Do you stop istiod violently so that it has no chance to release the leader. other I could not reproduce in 1.16.1

https://github.com/istio/istio/blob/0c8164f2dc0f7f405fd6036614ca8c11a4452f7e/pilot/pkg/leaderelection/k8sleaderelection/leaderelection.go#L309-L311

**Comment by howardjohn** [comment]
No it was released. Ill play around with it more today

**Comment by howardjohn** [comment]
I think what happens is on rolling restart:

* 0s: new pod starts, tries to grab lock. It is locked for ~15s. Sleep for 15s
* 1s: old pod shuts down, loses lock
* 15: new pod wakes up, grabs lock

Not sure we can do anything since it doesn't have a watch (just does Get). but also its not a major concern

**Comment by keithmattix** [comment]
Would it be worth doing a backoff with a 15s upper bound for grabbing the lock?

**Comment by howardjohn** [comment]
Maybe, I guess that would add a few extra requests on each pod startup but no more after, and optimize for the case of scale down + scale up quickly. I wouldn't mind the change but also don't think its worth the effort really. Note we use a small fork of client-go library, so we can make arbitrary changes like this but we do diverge further if we do so

**Comment by keithmattix** [comment]
Mmm yeah that's a good point. Yeah it's probably not worth it; the edge cases of config drift in that 15s gap without a leader are probably few

**Comment by hzxuzhonghu** [comment]
By default each client retries to get the lock every ttl/4, which is 7.5s. Not sure how 15s occurs

**Comment by howardjohn** [comment]
I just guessed it was 15s, good to know it's even shorter
