### ISSUE TITLE
Handle split services in waypoint

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43189]
Service A selects 4 pods:
* Pod HasWaypoint
* Pod HasZtunnel
* Pod HasHboneSidecar
* Pod HasNone

I make a call from a pod in the mesh to "A".

Option 1: all requests go to waypoint, waypoint sends to all 4 pods
Option 2: all requests go to waypoint, waypoint sends to HasWaypoint, HasZtunnel, HasHboneSidecar (no plaintext)
Option 3: all requests go to waypoint, waypoint sends to HasWaypoint
Option 4: 25% of requests go to waypoint, rest go direct. Requests to the waypoint all go to HasWaypoint
Option 5a, 5b: 25% of requests go to waypoint, rest go direct. At waypoint, we pick option 1 or 2 

I prefer 1 or 4. We currently implement 5a which I think is definitely not good.

Based on some analysis only 0.1% of services are split across service accounts so I think this is pretty niche

**Comment by kyessenov** [comment]
Need to consider option of pod having a sidecar that speaks HBONE.

**Comment by howardjohn** [comment]
@kyessenov good call, updated it but it didn't introduce new options - let me know if you think there should be other

**Comment by kyessenov** [comment]
I don't think waypoints should send to "none". It's too high of a risk to accidentally de-classify encrypted traffic in transit, and "Service" is not a good traffic perimeter IMHO. Imagine creating a service that overlaps just one waypoint endpoint, and then relaying all traffic outside unencrypted using routing rules.

**Comment by howardjohn** [comment]
Well its still un-encrypted before you add that 1 waypoint endpoint, right?

But I do think we should do option (4) which does have the same behavior of not sending to "none" in this case. Not if I had a VS that explicitly routed to another service, that still could be plaintext (could be example.com, for example) - this issue is only talking about a single service that is "split" rather than a route splitting between two distinct services.

**Comment by kyessenov** [comment]
Yes, but the expectation is that waypoint existence is an authorization enforcement feature. We cannot rely on routing to enforce authz within waypoint, because in practice, all traffic from the waypoint could be sent to one unencrypted endpoint if it exists, given appropriately crafted routing rules. That means any endpoint in waypoint that is not HBONE or ztunnel (for L4 policy) has to be carefully reviewed. I'd rather not invite the problem to begin with, since it's enough issues with the egress traffic.

**Comment by kyessenov** [comment]
I don't have a strong preference, as long as the backend is HBONE and has some clear expectations about the next hop authz. I think it could be valuable to send and fail in some cases, to support eventually consistent or dis-connected models.

**Comment by howardjohn** [comment]
fixed https://github.com/istio/istio/pull/43190
