### ISSUE TITLE
GKE - error fetching GCP Metadata on cluster with Workload Identity

### ISSUE THREAD

**Issue by MaciekLeks** [istio/istio#43185]
### Bug Description

After upgrading from 1.14.1 to 1.16.1 istio sidecars raise this error:
```
2023-02-07T18:51:49.920633Z    warn    Error fetching GCP Metadata property gcp_gce_instance_created_by: metadata: GCE metadata "instance/attributes/created-by" not defined               │
│ 2023-02-07T18:51:49.920905Z    warn    Error fetching GCP Metadata property gcp_gce_instance_template: metadata: GCE metadata "instance/attributes/instance-template" not defined          │
│ 2023-02-07T18:51:49.921070Z    warn    Error fetching GCP Metadata property gcp_gce_instance: metadata: GCE metadata "instance/name" not defined                
```

When I look at my metadata I can see only these one:
```
istio-proxy@monitor-g-logging-int-56dd5d595-2rjwh:/$ curl -L -H "Metadata-Flavor:Google" http://169.254.169.254/computeMetadata/v1/instance
attributes/
hostname
id
service-accounts/
zone
istio-proxy@monitor-g-logging-int-56dd5d595-2rjwh:/$ curl -L -H "Metadata-Flavor:Google" http://169.254.169.254/computeMetadata/v1/instance/attributes
cluster-location
cluster-name
cluster-uid 
```

this topic is related to:
[Protecting cluster metadata](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata) but in case of Workload Identity the metadata concealment can't work at the same time.

### Version

```prose
client version: 1.16.1
control plane version: 1.16.1
```

### Additional Information

[source code with the errror](https://github.com/istio/istio/blob/master/pkg/bootstrap/platform/gcp.go)

The question is: Either this metadata were never been downloaded by istio and only now istio informs it better or someting has changed between 1.14.1->1.16.1?

**Comment by howardjohn** [comment]
I think this is only supposed to run OFF Kubernetes. So might be a bug

**Comment by howardjohn** [comment]
@aryan16

**Comment by taisph** [comment]
> ```
> 2023-02-07T18:51:49.920633Z    warn    Error fetching GCP Metadata property gcp_gce_instance_created_by: metadata: GCE metadata "instance/attributes/created-by" not defined               │
> │ 2023-02-07T18:51:49.920905Z    warn    Error fetching GCP Metadata property gcp_gce_instance_template: metadata: GCE metadata "instance/attributes/instance-template" not defined          │
> │ 2023-02-07T18:51:49.921070Z    warn    Error fetching GCP Metadata property gcp_gce_instance: metadata: GCE metadata "instance/name" not defined                
> ```

FWIW, I'm getting these warning with Istio 1.14.6 on GKE.

**Comment by CroutonDigital** [comment]
same error 
2023-04-26T14:18:00.408813Z	info	starting Http service at 127.0.0.1:15004
2023-04-26T14:18:00.412706Z	warn	Error fetching GCP Metadata property gcp_gce_instance_created_by: metadata: GCE metadata "instance/attributes/created-by" not defined
2023-04-26T14:18:00.415341Z	warn	Error fetching GCP Metadata property gcp_gce_instance: metadata: GCE metadata "instance/name" not defined
2023-04-26T14:18:00.415391Z	warn	Error fetching GCP Metadata property gcp_gce_instance_template: metadata: GCE metadata "instance/attributes/instance-template" not defined

**Comment by xbglowx** [comment]
Still an issue for us.

**Comment by howardjohn** [comment]
Broke in https://github.com/istio/istio/pull/40105. Not really "broken", just now logs errors that can happen in expected cases
