### ISSUE TITLE
Special headers were removed

### ISSUE THREAD

**Issue by ggmr2212** [istio/istio#43224]
### Bug Description

When we enable istio on eks we have a lot of HTTP 400 errors to some services. Reviewing all the request we are receiving errors with messages like: XXX_HEADER was not provided.  

No.	Time	Source	Destination	Protocol	Length	Info
1763	78.858481	172.30.129.227	172.30.129.42	HTTP/JSON	1860	HTTP/1.1 400 Bad Request , JavaScript Object Notation (application/json)

<img width="859" alt="image" src="https://user-images.githubusercontent.com/68156776/217693772-30fed5e2-27b9-4751-83b9-df8c9c4b4b12.png">

All is working normally when we disable sidecar injection.
### Version

```prose
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (16 proxies)

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.14-eks-ffeb93d
```

### Additional Information

[](url)
[bug-report.tar.gz](https://github.com/istio/istio/files/10691757/bug-report.tar.gz)

**Comment by hzxuzhonghu** [comment]
maybe because ` Envoy will normalize the header keys to be all lowercase. `

**Comment by kyessenov** [comment]
Envoy sanitizes some headers (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing). Do you have URI that is sent by the client?

**Comment by howardjohn** [comment]
Right now we don't have enough to proceed on this, please feel free to re-open if there is some more information. Thanks!
