### ISSUE TITLE
Fault Injection not reflected in reports to Mixer from Envoy

### ISSUE THREAD

**Issue by tanshungang** [istio/istio#4323]
for example by bookinfo applications:
productpage\reviews\details\ratings are microservices of bookinfo.
If productpage call details by: http://details.****.com/details/0, and I set a abort httpfault(http status code is set 503), so productpage will receive 503 from details when it calls http://details.****.com/details/0, but, at this time, there is no metric data about this infomation when i query from prometheus.

this case is a normal case？

**Comment by douglas-reid** [comment]
@tanshungang Right now, reporting to Mixer happens server-side, after the request passes through the mixer client filter on the proxy. What I believe you have discovered (and which I have also seen in passing when testing other features) is that the fault injection filters preempt (if you will) the mixer client filter, resulting in no server-side reporting happens.

There are a few things in the works that should help address this issue, including support for client-side reporting to Mixer.

In the meantime, we need to troubleshoot and identify if we can get server-side reporting working for such scenarios (as the lack of reporting is definitely surprising in a bad way).

I'm gonna update the issue description to reflect the broader issue.

cc: @mandarjog, @bianpengyuan, @qiwzhang

**Comment by mandarjog** [comment]
I suspect that the fault filter is being called before mixer filter on the server side.
I will investigate.

**Comment by douglas-reid** [comment]
@mandarjog I did some more investigation this morning. Faults are injected client-side. This would explain why Mixer never sees this information, as there is no client-side reporting.

**Comment by tanshungang** [comment]
@douglas-reid  this issue is a bug or it is normal function?

**Comment by douglas-reid** [comment]
@tanshungang We intend to support metrics reporting for fault injection scenarios. The current implementation, however, does not support client-side reporting.

Client-side reporting has been a long-standing feature request, one that we've committed to supporting. Work is already underway to provide it in support of a couple of other goals. There is a related issue for tracking the new work here: https://github.com/istio/istio/issues/4647.

**Comment by douglas-reid** [comment]
client-side reporting was added to Istio and should now reflect fault injections.
