### ISSUE TITLE
ztunnel: allow proxy config via configmap

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43248]
Ztunnel code allows reading proxy config from file. However, the k8s manifests don't actually load this. We should, using a distinct configmap from Istiod's

**Comment by hzxuzhonghu** [comment]
The ProxyConfig API is not very suitable for ztunnel, should design a new one to work on ztunnel?  It should be static configuration, which can be loaded during ztunnel bootstrap.

**Comment by howardjohn** [comment]
It is not `ProxyConfig` CRD being read but configmap, just like `istio` configmap read by istiod today. We already have support for reading this in the ztunnel code, just don't expose it in helm

**Comment by hzxuzhonghu** [comment]
That makes sense
