### ISSUE TITLE
ambient: report proper version in Dockerfile.ztunnel

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43249]
We currently stick ISTIO_VERSION and PROXY_SHA in the image. But it is the envoy sha, which is not relevant.

I think ztunnel already knows its own SHA so not sure its super relevant to include it. Istio_version is useful though

**Comment by hzxuzhonghu** [comment]
I am not sure why proxySHA be reported, we use istio_version to check compatibility between control plane and dataplane.
