### ISSUE TITLE
ambient: investigate if hostNetwork is needed for CNI

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43246]
Currently we change the CNI to use `hostNetwork`. We did NOT do this for cni on master. We need to investigate what to do here - can we go without it, should we turn it on for ambient only, always on, etc.

Note: you can execute in the host network even without `hostNetwork: true` with enough privileges.

**Comment by howardjohn** [comment]
Did a bit of research, we definitely need host network *access*. We could do a trick to nsenter into the host though - I had a good way to do it but forgot how (maybe it was just mounting /var/blah/blah/netns... I recall it being more clever though).

The reason to NOT use hostNetwork was/is to avoid port conflicts, etc occurring.

IMO it would be good to be able to avoid host net to deal with these conflicts

**Comment by keithmattix** [comment]
@howardjohn was this ever resolved?

**Comment by howardjohn** [comment]
No

**Comment by bleggett** [comment]
Is there actually a functional privilege difference between running in the host network namespace from the start, versus `nsenter`ing the host network namespace later?

I don't think there is, really?

**Comment by howardjohn** [comment]
I don't think it lowers privileged but we do have ports for readiness, metrics, etc.
