### ISSUE TITLE
waypoint: allow more customization

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43258]
Common annotations like `sidecar.istio.io/agentLogLevel` do not work. We should add support. This is based on the template

**Comment by hzxuzhonghu** [comment]
so the `sidecar.istio.io/agentLogLevel` annotation is from gateway and will be added to waypoint pod, right?

**Comment by howardjohn** [comment]
maybe... I am not quite sure. But we should have some way to configure these types of things for debugging

**Comment by hanxiaop** [comment]
Are we still using the `sidecar.istio.io` prefix annotation names for the waypoint pod?

**Comment by kyessenov** [comment]
Waypoints are dynamically created so we'd need a different user API than pod annotations.
