### ISSUE TITLE
ambient: support full Telemetry for waypoint

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43250]
See https://github.com/istio/istio/blob/827473641d1dcc0029e8e9c96f80a0d184b6888e/pilot/pkg/model/telemetry.go#L873 currently we hardcode config. We should allow the customized config

**Comment by kyessenov** [comment]
Besides the basic configuration, there are some missing features:
* tracing open/close spans don't make sense in the waypoint;
* stackdriver doesn't have destination metadata;
* direct pod traffic doesn't emit telemetry.

**Comment by keithmattix** [comment]
Not stale
