### ISSUE TITLE
waypoint controller: use proper Gatewayclass logic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43264]
Today we assume well-known class name, we should actually read GatewayClasses like in the ingress controller

**Comment by hzxuzhonghu** [comment]
What to get from the gatewayclass? If it is just to read the const controller name `istio-xxx`, seems no diff from now

**Comment by howardjohn** [comment]
I am working on this and consolidate the waypoint and ingress Gateway controllers to one

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/43319
