### ISSUE TITLE
Envoy on VM: broken DNS

### ISSUE THREAD

**Issue by pkovtunov** [istio/istio#43276]
### Bug Description

I'm using istio-sidecar on a VM to create an outbound mesh expansion - now it's just a simple test setup and it worked fine for months.
Since several weeks, the DNS routing on the envoy-enabled VM breaks and all outgoing DNS requests fail - like host resolution for Puppet master server, log upload to ES, 2FA for SSH with a callback towards LDSP server ... etc

Only the K8S internal DNS works, so I can resolve the internal names (e.g. prometheus.gocdmaster-acdc-helper on K8S cluster)

It seems that the lookup table is empty, though the log message confirms that it's been populated.

```
/var/log/istio/istio.log:2023-02-10T15:31:05.064094Z	debug	dns	updated lookup table with 216 hosts
/var/log/istio/istio.log:2023-02-10T15:32:59.032485Z	debug	dns	updated lookup table with 216 hosts
/var/log/istio/istio.log:2023-02-10T15:33:52.999359Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=c5ee8e8b-6d37-4a38-99b0-27714862d537
/var/log/istio/istio.log:2023-02-10T15:33:52.999680Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=2b8508b2-acb0-4d32-aeda-8ed178c26387
/var/log/istio/istio.log:2023-02-10T15:33:54.856185Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=3c5cf403-b168-4ae0-b0db-9b801210bfba
/var/log/istio/istio.log:2023-02-10T15:33:54.856488Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=4d3f539e-f8c0-4010-a93c-a94694450118
/var/log/istio/istio.log:2023-02-10T15:33:55.619298Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=b4ecd1de-588d-4037-9131-2dfc70f8808e
/var/log/istio/istio.log:2023-02-10T15:33:55.619538Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=dc1217e0-6037-48b1-8053-f2a13d0f8013
/var/log/istio/istio.log:2023-02-10T15:33:56.265126Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=00ec32f7-ec7e-48bc-98b0-e71b8e822f81
/var/log/istio/istio.log:2023-02-10T15:33:56.265361Z	debug	dns	dns request for host "www.google.de." before lookup table is loaded	protocol=udp edns=false id=8420e073-96f9-4479-8e62-9144b675685a
/var/log/istio/istio.log:2023-02-10T15:34:04.775900Z	debug	dns	dns request for host "acdc-pcms-qa-bap01.server.lan." before lookup table is loaded	protocol=udp edns=false id=98bc3060-774d-49a5-9301-1b04f13a96ee
/var/log/istio/istio.log:2023-02-10T15:34:04.775970Z	debug	dns	dns request for host "acdc-pcms-qa-bap01.server.lan." before lookup table is loaded	protocol=udp edns=false id=5943a517-98dc-49e8-9ad6-7010f77d29b1
/var/log/istio/istio.log:2023-02-10T15:34:04.776109Z	debug	dns	dns request for host "acdc-pcms-qa-bap01.server.lan." before lookup table is loaded	protocol=udp edns=false id=42d55dd0-ea4e-4a96-918b-a826ce9828cd
```

### Version

```prose
$ istioctl version

client version: 1.15.4
control plane version: 1.15.4
data plane version: 1.15.4 (146 proxies), 1.14.5 (1 proxies)

$ kubectl version --short

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.16
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Additional Information

istio.log output, DNS init part:

istio.log:  ISTIO_META_DNS_CAPTURE: "true"
istio.log:2023-02-09T15:41:09.951328Z	debug	dns	initialized DNS	search=[server.lan] servers=[172.19.254.1:53 172.19.255.1:53]
istio.log:2023-02-09T15:41:09.951425Z	info	dns	Starting local udp DNS server on 127.0.0.1:15053
istio.log:2023-02-09T15:41:09.951676Z	info	dns	Starting local tcp DNS server on 127.0.0.1:15053

In the istio logs I can see the failing DNS requests towards our company DNS server:

2023-02-09T14:52:36.379875Z	info	dns	upstream failure: read udp 10.90.21.220:54366->172.19.254.1:53: i/o timeout
2023-02-09T14:52:36.380005Z	info	dns	upstream failure: read udp 10.90.21.220:47191->172.19.254.1:53: i/o timeout
2023-02-09T14:52:36.381199Z	info	dns	upstream failure: read udp 10.90.21.220:40380->172.19.254.1:53: i/o timeout
2023-02-09T14:52:36.381271Z	info	dns	upstream failure: read udp 10.90.21.220:38023->172.19.254.1:53: i/o timeout
2023-02-09T14:52:36.381309Z	info	dns	upstream failure: read udp 10.90.21.220:36115->172.19.254.1:53: i/o timeout
2023-02-09T14:52:36.381342Z	info	dns	upstream failure: read udp 10.90.21.220:35367->172.19.254.1:53: i/o timeout

Also further debug output regarding DNS resolution:

;; QUESTION SECTION:
;acdc-deploytest-istio-qa-bs01.server.lan.	IN	 A
	protocol=udp edns=false id=497ecf56-c4af-4df8-b5e0-3ee376f4cce2
2023-02-09T15:33:26.212260Z	debug	dns	dns request for host "acdc-deploytest-istio-qa-bs01.server.lan." before lookup table is loaded	protocol=udp edns=false id=497ecf56-c4af-4df8-b5e0-3ee376f4cce2
2023-02-09T15:33:26.212553Z	debug	dns	request ;; opcode: QUERY, status: NOERROR, id: 33513
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

istio.log:2023-02-09T15:41:21.518781Z	debug	dns	dns request for host "www.google.com." before lookup table is loaded	protocol=udp edns=false id=4cc5f68c-f2ce-44ce-965b-0715117599cf

**Comment by Christoph-Raab** [comment]
Colleague here, want to add istio dns proxying isn't enabled by default but on a per sidecar base. Disabling istio dns proxying on the machine fixes the issue, so the problem must be related to that.

Also calling the health endpoint `curl localhost:15021/healthz/ready -I` returns `200 OK`.

**Comment by pkovtunov** [comment]
Sorry for sorry for inconvenience, we had a misconfigured iptable rule on our side, which caused this behavior

**Comment by adammallo** [comment]
I hope you are still receiving updates on this. Any chance you can clue me in on how you fixed this? I think I am seeing a very similar issue and I am going to go check my iptables but I wanted to ask here as well. Thanks for any information.

**Comment by Christoph-Raab** [comment]
Hi @adammallo 

the problem was related to our host based firewall. We had to make sure that incoming DNS traffic and also the ISTIO traffic is explicitly allowed.
