### ISSUE TITLE
Upgrading to istio 1.15 causes mutatingwebhookconfiguration to not be patched with the caBundle

### ISSUE THREAD

**Issue by dwj300** [istio/istio#43320]
### Bug Description

We are upgrading from istio 1.14.5 to 1.15.5 and just ran into an issue using an external control plane cluster. In 1.14, we do not set the `topology.istio.io/controlPlaneClusters` annotation on the istio-system namespace of our workload clusters. However, istio 1.15 seems to require it, as of https://github.com/istio/istio/pull/39406. I know istio 1.15 is going to be EOL soon, but would you consider adding this requirement to the upgrade notes? Customers who upgrade from to future versions are likely to hit this as well.

### Version

```prose
istio 1.15.5
k8s 1.23
```

**Comment by howardjohn** [comment]
cc @frankbu

**Comment by dwj300** [comment]
Also, we've found that if the namespace isn't annotated when istiod starts up, it will never reconcile until we restart istiod. I saw a code comment about changing to a namespace watcher, any update on that fix?

**Comment by S-Chan** [comment]
https://github.com/istio/istio/pull/39639/files#diff-8a4e243b3a9e04bfce52e390205058235db27c5319f6582d3be963fc5d533e63R334 seems to be the faulty diff

**Comment by dwj300** [comment]
> https://github.com/istio/istio/pull/39639/files#diff-8a4e243b3a9e04bfce52e390205058235db27c5319f6582d3be963fc5d533e63R334 seems to be the faulty diff

Right, good point.
```
			if !found {
				return true // true by default if unannotated
			}
```
this "backwards compatible" part was removed.

**Comment by frankbu** [comment]
@dwj300 Is this what you're looking for? https://github.com/istio/istio.io/pull/12663

IIUC this is a one time problem for external control plane. After 1.15 the annotation MUST be there. Unfortunately nobody has had the time to work on the namespace controller (it's a pretty big job) so you need to restart istiod or detach/reattach the remote cluster.

**Comment by frankbu** [comment]
btw, defaulting to true is a problem when there are multiple control plane in a multicluster environment. They all want to see the endpoints on every other cluster, but not manage the webhook etc., unless selected.

**Comment by dwj300** [comment]
> @dwj300 Is this what you're looking for? [istio/istio.io#12663](https://github.com/istio/istio.io/pull/12663)

This is a good start, but I'm asking for something slightly stronger, specifically that it is a breaking change. In addition, this annotation doesn't exist anywhere else in the docs, so it would be nice if there was a reference elaborating on the possible values, etc.

**Comment by frankbu** [comment]
@dwj300 It isn't a breaking change if you follow the upgrade note we're adding now.

It is documented along with all Istio annotations: https://istio.io/latest/docs/reference/config/annotations/
