### ISSUE TITLE
Config dump doesn't print out addresses properly

### ISSUE THREAD

**Issue by linsun** [istio/istio#43335]
Either the addresses field or waypoint addresses field:

```
k exec -it deploy/istiod -n istio-system -- curl "localhost:15014/debug/config_dump?proxyID=ztunnel-974pt.istio-system" | jq
{
  "configs": [
    {
      "@type": "type.googleapis.com/istio.workload.Workload",
      "name": "helloworld-istio-waypoint-559d7b6fdc-wnts7",
      "namespace": "default",
      "address": "CvQCDA==",
      "serviceAccount": "helloworld-istio-waypoint",
      "node": "ambient-worker",
      "canonicalName": "helloworld-istio-waypoint",
      "canonicalRevision": "latest",
      "workloadName": "helloworld-istio-waypoint"
    },
    {
      "@type": "type.googleapis.com/istio.workload.Workload",
      "name": "helloworld-v1-cross-node-55446d46d8-dgqfz",
      "namespace": "default",
      "address": "CvQCCA==",
      "serviceAccount": "helloworld",
      "waypointAddresses": [
        "CvQCDA=="
      ],
      "node": "ambient-worker",
      "canonicalName": "helloworld",
      "canonicalRevision": "v1",
      "workloadName": "helloworld-v1-cross-node",
      "virtualIps": {
        "10.96.32.10": {
          "ports": [
            {
              "servicePort": 5000,
              "targetPort": 5000
            }
          ]
        }
      }
    },
```

**Comment by howardjohn** [comment]
Technically it is printing it "correctly",just not in a human readable form :-) but this is how proto encodes []byte

**Comment by hanxiaop** [comment]
Since the field is type []byte, it will be automatically converted to base64 encoding during serialization. I think one of the  possible effort we can do may be to parse the address before printing the JSON to make it human-readable after decoding, unlike the current value `CvQCDA==`, which is still unreadable even after decoding. However, it's still not very useful or straightforward.

**Comment by howardjohn** [comment]
I think we would have to maintain a fork of the API that is everything the same but not `[]byte` which is a bit excessive for just a debug API imo

**Comment by linsun** [comment]
Does anyone know a simple tool to manually decode this?  I tried 

```
echo "CvQBCQ==" | base64 --decode

�	%
```

**Comment by howardjohn** [comment]
you can pass it to hexdump but then you get hex encoding which is still somewhat tricky. Not sure a tool that will display bytes as decimal. probably a small bit of python could do it

**Comment by kyessenov** [comment]
don't use JSON? prototext is better for bytes.

**Comment by howardjohn** [comment]
```
$ echo "CvQBCQ==" | base64 --decode | python3 -c 'import sys; print(".".join([str(x) for x in sys.stdin.buffer.read()]))'
10.244.1.9
```

**Comment by kyessenov** [comment]
I'm not sure about using bytes for the encoding. It sounds like a bad idea in retrospect. First, it doesn't allow a better "key", e.g. pod ID. Second, IPs are architecture dependent, and these appear to be little endian right now - and hopefully stay that way on ARM/x86.

**Comment by keithmattix** [comment]
Not stale
