### ISSUE TITLE
Integration test framework improvement 

### ISSUE THREAD

**Issue by yutongz** [istio/istio#4333]
We still need to do some more improvement on integration framework (tests/integration) to make it more useful and easy to adopt.

--- 18.03.16
- [ ] Eliminate the use of the entry [script](https://github.com/istio/istio/blob/master/tests/integration/example/integration.sh), i.e. move component related parts into specific components
- [ ] Upload logs as artifacts when running in CI
- [ ] Add entry to download mac envoy binary for local development
- [ ] Fix dummy wait in component readiness
- [ ] Migrate some mixer tests into this framework https://github.com/istio/istio/tree/master/mixer/test/client

**Comment by yutongz** [comment]
fyi @hklai and let me know if you have more in your mind.

**Comment by hklai** [comment]
Obsolete in favor of the SWAT team work.
