### ISSUE TITLE
istio stopped working after AKS cluster update from 1.15 to 1.23

### ISSUE THREAD

**Issue by tashsc** [istio/istio#43348]
### Bug Description

We have a aks clusters, I managed to upgrade that from 1.15 to 1.23. After that, our istio stopped working. We will need to upgrade it as well. Currently it's on version 1.5.0, we need to upgrade it to the latest supported version. we can't skip one minor version. i.e. we can't upgrade from 1.50. to 1.7.0 without upgrade to 1.6.0 first.

 as we can't skip one minor version. i.e. we can't upgrade from 1.50. to 1.7.0 without upgrade to 1.6.0 first.

### Version

```prose
1.50
```

**Comment by tashsc** [comment]
Help with suggestions please

**Comment by keithmattix** [comment]
Istio 1.5 is _very_ old (almost 3 years)...it certainly doesn't have support for Kubernetes v1.23 (per the chart on [this](https://istio.io/latest/docs/releases/supported-releases/) page. At this point, depending on your setup; you may be better of spinning up a new cluster and migrating workloads there to minimize downtime.

**Comment by tashsc** [comment]
create a cluster and migrate is too much work. how could we upgrade istio to the version that support k8s 1.23?

**Comment by keithmattix** [comment]
It really depends on the specifics of how your Istio installation. I'll point out that the initial situation you're describing is outside the scope of both Kubernetes and Istio support guidelines, so there's going to be a nontrivial amount of work required regardless. One option is to turn of STRICT mTLS if you have it enabled, uninstall istio, and re-install a newer version.

**Comment by tashsc** [comment]
ok. Thanks for the response. It helps alot.
what's the best way to migration current istion configuration and to the new version if we are going to uninstall old version.
We have istion-ingress-gateway, how could we export the existing cert and re-import that after install new version of istio
