### ISSUE TITLE
Print bootstrap in pilot-agent

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4334]
As part of logging "refactor", we've lost logs about the start-up bootstrap config. This makes is impossible to diagnose user issues: https://github.com/istio/issues/issues/169,  https://github.com/istio/issues/issues/173, as well as the recent cert straggler issues. Please bring back the log that printed the bootstrap config.

**Comment by nmittler** [comment]
The bootstrap config logging was restored a while back.  Closing.
