### ISSUE TITLE
Ability to control trace ID length on Zipkin

### ISSUE THREAD

**Issue by Stono** [istio/istio#43359]
**Describe the feature request**
The envoy configuration for `type.googleapis.com/envoy.config.trace.v3.ZipkinConfig` allows you to configure `trace_id_128bit`, which in istio defaults to true.

I'd like to be able to control this to set it to false, so that traceid's generated by istio align with traceid's generated from some of our other systems (64 bit).

Guessing it'd need to be an option on https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-ZipkinTracingProvider

**Describe alternatives you've considered**

None, i don't see a way that I can control this other than using an EnvoyFilter to inject the tracer directly myself which seems counter-productive to the 1st class API.

There's also talk of doing custom bootstrap here: https://github.com/istio/istio/issues/37517, but again that seems a bit of a hammer for something that should now be configurable via the telemetry api?  I did give it a go... but it didn't seem to work anyway.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: istio-system
data:
  custom_bootstrap.json: |
    "tracing": {
      "http": {
        "name": "envoy.tracers.zipkin",
        "typed_config": {
          "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
          "collector_cluster": "zipkin",
          "collector_endpoint": "/api/v2/spans",
          "trace_id_128bit": false,
          "shared_span_context": false,
          "collector_endpoint_version": "HTTP_JSON"
        }
      }
    }
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
@zirain

**Comment by zirain** [comment]
will take a look tomorrow

**Comment by Bconteh** [comment]
@Stono did you managed to get this working? we're using istio asm-1.21 but our traces are still 128bits even though we've configured the bootstrap settings to `trace_id_128bit: false`

**Comment by Bconteh** [comment]
@zirain setting the `enable64bitTraceId: true` under zipkin provider settings doesn't seems to be working for us. Any clue how to set this up to have 64bits traceid from envoy proxy in AKS istio addon (asm-v1-21)?

**Comment by zirain** [comment]
Please contact your cloud vendor first, make sure they didn't change anything.

If they didn't change anything, please open another ticket to share the reproduce steps.
