### ISSUE TITLE
Ambient access logging to match current 1.16.2+ Istio capabilities

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#43376]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
With regards to access logging for Ambient, can we have this same functionality? https://github.com/istio/istio/issues/41964

basically the ability to have access logs only for exceptions? Like status code => 400, BlackHoleCluster or PassthroughCluster

[X] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kyessenov** [comment]
I think this is straightforward as long as the filtering is not based on workload labels.

**Comment by ceastman-r7** [comment]
Here is the current telemetry filter I use for access logs:

spec:
  accessLogging:
  - filter:
      expression: 'response.code >= 400 || xds.cluster_name == ''BlackHoleCluster''
        ||  xds.cluster_name == ''PassthroughCluster'' '
    providers:
    - name: locallog

This reduced the amount of access logs generated by 99% which in turn reduced the load on our logging platform.

**Comment by kyessenov** [comment]
Passthrough cluster might be trickier to accomplish since gateways represent a collection of workloads (some potentially without services). We don't propagate a bit saying "this pod:port is part of a VIP:port balancing pool".

**Comment by ceastman-r7** [comment]
Without the Passthrough cluster how would someone know what service entries need to be created to avoid requests going to the BlackHole cluster? I assume that with ambient we will still have the ability to have an outbound traffic policy.

**Comment by kyessenov** [comment]
There are two things here. 

* Accessing IPs that are outside the cluster is in the domain of ztunnel by default. Ztunnel doesn't have the capability to filter based on CEL, so you'd need to use Envoy on the datapath.

* Waypoints today are defined per service account (or several of them), they are not meant for outbound traffic.

I think the right thing is to route through egress gateways from ztunnel for service entries. I don't think it's agreed upon yet.

cc @costinm

**Comment by ceastman-r7** [comment]
Will the ztunnel have the ability to block outbound traffic (ips outside the cluster) ? to force everything through the istio egress gateway?

**Comment by ceastman-r7** [comment]
what is Istiod PTR-DS?

**Comment by kyessenov** [comment]
@costinm This isn't about the format of the logging - I think everyone agrees that we'll eventually use OTel. This is about filtering logs at the source because they are too expensive to process and store.

PTR DS is a service that does lookup based on the destination IP. Instead of static routes, proxy would contact a control plane to receive a decision when a connection is open.

**Comment by ceastman-r7** [comment]
@kyessenov With that envoy PR you helped me with my company is able to reduce our istio-proxy access log generation by 99%

**Comment by costinm** [comment]
Kuat - agreed. Question is who does the filter/aggregation/dispatching. We want to keep ztunnel simple - and otel agent is largely intended for this. 

My thinking is to defer to otel libraries and agent/collector, and not duplicate such configs in ztunnel. We need some enable/disable flag, but hopefully not more.

**Comment by kyessenov** [comment]
@costinm 

Why is it better to run a separate service just to filter logs? I can see that as a shortcut, but regardless of how OTel collector runs (managed or user-deployed), we're not addressing the log ingestion costs with this approach. It adds costs to datapath too since at a high rate, the log egress can be enormous.

I think it's very reasonable for ztunnel to sample logs. Always emitting "denied" or "explicitly allowed" entries is a simple feature request to maintain compatibility with Istio.

For egress gateway and waypoint, the work is really about better nomenclature (instead of cluster names, we should have a more reliable signal).

**Comment by costinm** [comment]
PTR-DS is a new XDS resource ( like LDS, RDS, etc ) that act like DNS PTR - you use an IP as lookup key, and get back the name and other information about the pod or service. 

Istio captures by IP address ( iptables, etc) - and this is the simplest/fastest way to get the server's SAN and if it needs a waypoint in ambient, or it needs to be redirected to an east-west gateway for multi-network or egress gateway.

In 'secure networks' PTR-DS can also get information about the client ( name, namespace, labels, etc ) - without requiring in-band metadata exchange (Baggage header). "Secure" means the network guarantees the client IP can't be forged - wireguard/IPSec or most VPCs.

**Comment by costinm** [comment]
@kyessenov running a separate service _just_ to filter logs is not better.

The collector is typically a per-node pod, just like ztunnel - so localhost traffic - that does far more than filter. It can transform logs/traces/metrics, send to multiple destinations, handle different authentication requirements and protocols - without ztunnel and each app emitting OTel having to link in all the code and define APIs for it.

Sampling logs, aggregating logs ( 'entry repeated 10 times'), throttling, selective dropping ( send errors before traces ) are all complex things that should not be duplicated/reimplemented in ztunnel. All this could be implemented in collector ( they don't have everything yet - but the main interfaces are there ) and shared by all apps producing metrics/traces/logs in
the node.

And it allows us to avoid work and bike-shedding on APIs for all those things :-)

**Comment by costinm** [comment]
https://opentelemetry.io/docs/collector/ - but other implementations and collectors are possible too.

**Comment by kyessenov** [comment]
@costinm Understood, but this is basically telemetry Mixer and we know that at some point, it won't scale without better client sampling. AFAIK OTLP used by Envoy in Google sending to Google is also sampling.

**Comment by costinm** [comment]
Yes, sampling is going to be needed at some point. But it's not quite mixer - we did a lot of custom compression and it had few other problems. 

For external authz we had the same worry that will be a repeat of mixer, but so far the simpler protocol seems to be ok.

We'll see - for the high cardinality metrics we don't have so many options, and we know current solution is not sustainable.
