### ISSUE TITLE
envoy: disable HTTP sniffing with HTTP authz policies

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43387]
(Not sure if this applies to sidecars, needed for waypoints)

When we detect HTTP policies enforced, we should enforce HTTP traffic (on that port or globally) and disable sniffing. This simplifies datapath logic for the common case.

CC @aryan16 @howardjohn

**Comment by howardjohn** [comment]
On surface I think this makes sense but we need some more info on the behavior I think. If its all L7 its easier, but with a mix of L4 and L7 it gets tricky?

1. ALLOW L7 + ALLOW L7 => always use HTTP
2. ALLOW L7 + ALLOW L4 => ? sniff ? TCP can pass
3. ALLOW L4 + DENY L7 => ?always use HTTP? if it was TCP we would have to deny all

**Comment by kyessenov** [comment]
I don't think any user would understand anything beyond "If I write an L7 policy, then it's L7 traffic". Trying some complicated overriding logic that L4 or L7 take priority depending on the action is super-confusing.

**Comment by howardjohn** [comment]
I can see that argument, but at the same time would any user expect that adding a policy "ALLOW POST requests" actually means all traffic is denied (because we had TCP ALLOW rules, we send TCP traffic, and the new rule forces us to HTTP)?

**Comment by kyessenov** [comment]
No that would be surprising. I feel like this is an artificial problem - there is a clear intent that ports have protocols. If someone writes an L7 policy for port X, then that port speaks HTTP. If an L7 policy has no port selector, then the service should be only HTTP (so allowing TCP traffic would be a mistake).

**Comment by howardjohn** [comment]
I think the main concern is that users are not necessarily writing policies for ports - they can be writing policies for a whole namespace even
