### ISSUE TITLE
Prometheus merging metrics results in "expected timestamp or new record, got "MNAME""

### ISSUE THREAD

**Issue by fbongiovanni29** [istio/istio#43403]
### Bug Description

When setting `prometheus.istio.io/merge-metrics: "true"` on certain pods we are getting `expected timestamp or new record, got "MNAME"` when looking at the pod target and it is unable to scrape it.

This happens intermittently and at times the target is up. It also happens to multiple services.

### Version

```prose
$ istioctl version
client version: 1.17.0
control plane version: 1.10-alpha.fd053c6165d21105d66dac6e3d0649db2dde5b86
data plane version: 1.10-alpha.fd053c6165d21105d66dac6e3d0649db2dde5b86 (26 proxies)
$ kubectl version --short
Client Version: v1.21.14
Server Version: v1.22.16-eks-ffeb93d
```

**Comment by howardjohn** [comment]
any chance you could actually show the contents of the scrape? otherwise may be hard to debug this.

Also, the version you are on is long EOL, worth trying to upgrade. This code has changed a bit since then.

**Comment by fbongiovanni29** [comment]
Sorry, I'm unable to share the contents of the scrape as it contains proprietary metrics. We are soon moving to 1.16 but we would like to identify what the issue is before upgrading so we're certain it doesn't pop up again

**Comment by howardjohn** [comment]
Open source is a two way street. If you are unable to provide information and unwilling to upgrade, we are unable/unwilling to help.

**Comment by fbongiovanni29** [comment]
I understand, I wish I was able to share more information but cannot due to company restrictions. I will update with any successes I have

**Comment by fbongiovanni29** [comment]
It appeared to be the same issue [here](https://github.com/istio/istio/issues/33474) and upgrading to 1.16 has resolved it. Thanks
