### ISSUE TITLE
ztunnel iptables redirection should be done in the CNI, not the daemonset

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#43411]
**Describe the feature request**
Currently, the iptables redirection for ztunnel is being done in the ztunnel daemonset initContainer. This should instead be done in code so that tests can be applied and future updates can be smoother. Additionally, this refactor would allow for more robust platform detection (not just KubeVersion hacks) fixing #41917

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by bleggett** [comment]
Linking https://github.com/istio/istio/issues/43243 as tangentally related to this

**Comment by bleggett** [comment]
Will open a PR for these changes once https://github.com/istio/istio/pull/42372 is merged - I'm building off of that since some of the stuff added there is also useful for the iptables side of things and generally cleaning up the CNI plugin a bit.

**Comment by bleggett** [comment]
@keithmattix Now that https://github.com/istio/istio/pull/43578 is merged, can you test on your end and see if that fixes the AKS issue in https://github.com/istio/istio/issues/41917?

I think it will but you can probably try it faster than I can.

**Comment by keithmattix** [comment]
Thanks a bunch @bleggett will test  early next week and let you know

**Comment by bleggett** [comment]
AKS support has been tested by @zioproto https://github.com/istio/istio/issues/41917#issuecomment-1446272260

Seems good, so closing this as done - if there are other issues or we find followups we can raise them as bugs.
