### ISSUE TITLE
ambient: review all new names/APIs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43437]
Can we add a TODO list of bug to track reviewing/changing all user-visible names ? 

I don't want to delay this PR - it is a merge - but the review criteria in an experimental branch is slightly different from the review on main - that's why it's experimental. I expect code has been tested and reviewed for functionality, and it is off by default - but we got into a lot of problems by
reviewing APIs and names as 'experimental/alpha' and then having to move them to beta/stable
due to backwards compat.

_Originally posted by @costinm in https://github.com/istio/istio/pull/43422#discussion_r1109988500_

**Comment by GregHanson** [comment]
@howardjohn @costinm is this item just a general tracker for the work?  Or should we list modified/new items in this issue as part of tracking?

**Comment by howardjohn** [comment]
We should list all the names here and then review IMO

**Comment by GregHanson** [comment]
just starting a list

Labels/Annotations:
 - gateway.istio.io/managed
 - istio.io-gateway-controller
 - istio.io-mesh-controller
 - istio.io/mesh-controller
 - istio.io/gateway-name
 - istio.io/for-service-account
 - istio.io/dataplane-mode
 - gateway.istio.io/name-override
 - gateway.istio.io/service-account
 - ambient.istio.io/redirection

Values:
 - Gateway.Spec.GatewayClassName: istio-waypoint
 - istio.io/dataplane-mode=ambient
 - profile=ambient
 - ambient.istio.io/redirection: true|false

Commands:
 - istioctl proxy-config workloads
 - istioctl x waypoint <apply|generate>

ztunnel API's:
 - :15000/config_dump
 - :15000/logging
 - :15000/quitquitquit
 - :15000/debug/pprof/profile
 - :15000/debug/gprof/profile
 - :15000/debug/gprof/heap
 - :15020/metrics
 - :15021/healthz/ready

**Comment by costinm** [comment]
Thanks for starting the list. We should also add the header names - and maybe put it in a doc so we can have comments ? Or a wiki / file in a table where we can also indicate some stability, expected changes and basic info ? 

I know that we always say "everything is alpha/meshconfig/env, may change so no need to worry about consistency/bikeshding/etc" - but in reality we almost never changed anything from alpha to beta and stable in any API, and we are stuck with a huge hidden and inconsistent API surface. 

Let's wait for the TOC decision on what ambient means - and adjust the names to match, and also select a small subset that we believe we can support long term. For example on the ztunnel API - last 2 are used from external systems, but the internal debug probably not and we may want to turn it off in a prod system ( or maybe like kubelet require authentication to use it). 

Any chance we can add an experimental- prefix to names and some flag to ignore all experimental in prod by default, with some way to have exceptions ? If 'simpler will be part of ambient definition - we really need to minimize this list.

**Comment by howardjohn** [comment]
100% agree. I opened https://github.com/istio/istio/issues/43614 to make sure we don't forget. I am a bit worried about us making quick shortcut APIs and getting stuck with them

**Comment by ymesika** [comment]
I think it's also worth mentioning to our users that L4 metrics will be available from Ztunnel for **any** type of traffic.
This is new behavior as sidecar are emitting metrics depending on the protocol type. I.e. if it's HTTP the L4 metrics are not emitted (`istio_tcp_`....).

**Comment by hanxiaop** [comment]
not stale

**Comment by keithmattix** [comment]
Not stale

**Comment by hanxiaop** [comment]
not stale

**Comment by howardjohn** [comment]
Most work now is really just moving them into istio/api
