### ISSUE TITLE
gateway deployment controller: skip un-owned types

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43439]
If the deployment, service, SA, etc already exists but without the `gateway.istio.io/managed` label, we should not overwrite it. User is controlling it.

**Comment by costinm** [comment]
And we should not delete either if Gateway is removed :-)

**Comment by costinm** [comment]
Also: should the label value include the revision or tag ? I don't remember if in Gateway we can put the rev tag and how it interacts, a doc would be good.
