### ISSUE TITLE
graceful shutdown for ambient

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43442]
Normally, graceful shutdown is executed with the cooperation of the global load balancer (in k8s, this would be endpointslices that are updated with "unready" endpoints).

This becomes problematic with the transparent CONNECT proxies on the datapath:.

Case 1.
A sidecar outbound connecting to `podIP:15008` that is redirected to Envoy waypoint implicitly. When the waypoint needs to go into maintenance mode, there's no signal from the load balancer to re-connect to obtain a new waypoint on the datapath.

Case 2:
We can use `GOAWAY` frames to signal to the client that the upstream is not ready. However, neither ztunnel nor internal listener correctly propagate it:

- a) Encap internal listener will attempt to re-connect but it will not signal downstream to re-establish a connection. For example, a VIP L7 pool will continue using the h2 stream to the degraded connection, since it doesn't propagate GOAWAY through the internal socket.
- b) The problem is worse with multiplexed ztunnels. Whenever an upstream connection signal GOAWAY, it cannot propagate this signal to the individual downstream h2 streams using this upstream connection, it has to send GOAWAY connection-wide. That will also drain unrelated streams to different destinations. This seems like a fundamental flaw with the tunneling protocol, since we cannot take out individual streams.

**Comment by hanxiaop** [comment]
not stale
