### ISSUE TITLE
limit streams per tunnel connection

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43443]
Envoy implementation is limited by the fact that internal listeners handle streams on the same worker as the tunnel listener. Therefore, we cannot handle a very large number of streams on a single tunnel.

We should ensure that we set a low max number of streams (~100 as a first estimate).

**Comment by keithmattix** [comment]
Not stale

**Comment by GregHanson** [comment]
not stale

**Comment by bleggett** [comment]
So in https://github.com/istio/ztunnel/pull/931

we added a pooling impl that considers streamcount-per-conn as criteria for starting a new connection, and exposes a ztunnel env var `POOL_MAX_STREAMS_PER_CONNECTION` to control that (which currently defaults to 100).

Our waypoint config is still hardcoded at 100 streams-per-conn though, which makes customizing `POOL_MAX_STREAMS_PER_CONNECTION` on the ztunnel side to a number higher than 100 a bad idea if you are using waypoints: https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/listener_waypoint.go#L112

I think this will be mooted by sandwiching, however.

**Comment by howardjohn** [comment]
What is left to do here? We already set to 100

**Comment by bleggett** [comment]
Likely nothing beyond documenting/remembering that setting `POOL_MAX_STREAMS_PER_CONNECTION` in ztunnel to > 100 is a bad idea and will break things.
