### ISSUE TITLE
istio as forward proxy from external to external

### ISSUE THREAD

**Issue by waheedshahani** [istio/istio#43460]
I have a use case where external clients (not in k8s) connect to apache forward proxy in k8s cluster which then further tunnels traffic to outside world. 
External client --> K8S Forward proxy --> Internet

My goal is to get rid of apache and use istio natively in k8s to allow external client to connect (forward proxy using HTTP connect method) and tunnel them to outside. I have tried many different variants of configs which I picked from here and there but nothing seems to work. 

Any help or idea would be appreciated. tried slack but no luck hence opening an issue.

**Comment by hzxuzhonghu** [comment]
FYI #37968 added support for tunnel

**Comment by waheedshahani** [comment]
> FYI #37968 added support for tunnel

It looks to me that PR covers the use case where traffic is originating from service mesh itself. In my use case traffic is supposed to originate from outside of cluster and uses istio as proxy.
