### ISSUE TITLE
Getting error during helm install task with the gateway and virtual service version 

### ISSUE THREAD

**Issue by sahilvarmacsi** [istio/istio#43482]
### Bug Description

##[error]Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1"]

I tried v1aplha3 and v1beta1 and also v1 but always getting this issue in the pipeline 

### Version

```prose
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    istio: {{ .Values.ingressgateway.name}}-gateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  {{ .Values.app.name }}-virtualservice
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.app.name }}-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: {{ .Values.app.name }}-service
        port:
          number: {{ .Values.port }}
```

**Comment by zirain** [comment]
did you install CRD and CR in same chart?

**Comment by sahilvarmacsi** [comment]
> did you install CRD and CR in same chart?

This task used to work for me with the same code and suddenly it stopped working. 
Can you please let me know how to do it?

**Comment by hanxiaop** [comment]
CRDs needs to be installed prior to the CRs. Can you check if they have been correctly installed?

**Comment by sahilvarmacsi** [comment]
Istio has been correctly installed on the aks cluster. I have verified that. I have upgraded the repo just now as well

**Comment by wulianglongrd** [comment]
incorrect api version. want `networking.istio.io/v1` but got `networking.istio.io/v1alpha3`.

**Comment by wulianglongrd** [comment]
check the crd installed use `kubectl describe crd gateways.networking.istio.io | grep 'API Version'`

**Comment by sahilvarmacsi** [comment]
> check the crd installed use `kubectl describe crd gateways.networking.istio.io | grep 'API Version'`

got it like this : 
API Version:  apiextensions.k8s.io/v1
    API Version:  apiextensions.k8s.io/v1
    API Version:  apiextensions.k8s.io/v1
    
    
    I am getting error even when I am using v1

**Comment by sahilvarmacsi** [comment]
> kubectl describe crd gateways.networking.istio.io | grep 'API Version'

It is also not editable. Do you know how we can reinstall this particular CRD

**Comment by sahilvarmacsi** [comment]
> > kubectl describe crd gateways.networking.istio.io | grep 'API Version'
> 
> It is also not editable. Do you know how we can reinstall this particular CRD
I am getting the stored version in the CRD as below: 
  storedVersions:
  - v1alpha3

**Comment by wulianglongrd** [comment]
sorry, misread, what I said above is wrong.

**Comment by wulianglongrd** [comment]
sorry, misread, what I said above is wrong. `kubectl describe crd gateways.networking.istio.io | grep Name` may be useful (eg. check `gateway` crd version).

the definition of crd is under the `istio/manifests/charts/base/crds/` directory of the source code

**Comment by sahilvarmacsi** [comment]
> sorry, misread, what I said above is wrong. `kubectl describe crd gateways.networking.istio.io | grep Name` may be useful (eg. check `gateway` crd version).
> 
> the definition of crd is under the `istio/manifests/charts/base/crds/` directory of the source code

I deleted and reinstalled , but i am still facing the same issue

**Comment by sahilvarmacsi** [comment]
The above issue has been fixed. The fix was that in the main branch the gateway file had the version v1 and I was trying to change the version to one of the v1alpha3 and v1beta1 to fix the issue in one the child branches and it was somehow pointing to the main branch. I changed the version to v1alpha3 on main branch it got fixed. Closing this issue
