### ISSUE TITLE
Envoy crashed after C++ WasmPlugin loaded

### ISSUE THREAD

**Issue by jian1106** [istio/istio#43484]
* system: macOS 13.2 (Intel Chip)
 * kubernetes cluster: docker-desktop 4.16.2 with kubernetes
    * kubectl client version: 1.25.4
    * kubectl server version: 1.24.2
 * istioctl version: 1.15.5
 * pilot image: istio/pilot:1.15.5
 * proxy image: istio/proxyv2:1.15.5
 * envoy version: aed172a7bd0b71db7121840c84b97855fb418381/1.23.4-dev/Clean/RELEASE/BoringSSL (run envoy --version inside istio-proxy container)

The detail steps and files can be found in [my github repository](https://github.com/jian1106/wasm-plugin-demo#readme).
Did i do something wrong?

Envoy logs:
```
2023-02-21T04:22:09.098282Z	info	wasm	fetching image jian1106/wasm-demo from registry index.docker.io with tag 0.0.1
2023-02-21T04:22:11.821890Z	critical	envoy backtrace	Caught Segmentation fault, suspect faulting address 0x7f55ace41000
2023-02-21T04:22:11.821931Z	critical	envoy backtrace	Backtrace (use tools/stack_decode.py to get line numbers):
2023-02-21T04:22:11.821935Z	critical	envoy backtrace	Envoy version: aed172a7bd0b71db7121840c84b97855fb418381/1.23.4-dev/Clean/RELEASE/BoringSSL
2023-02-21T04:22:11.828385Z	info	ads	ADS: "@" productpage-v1-66756cddfd-whs2c.default-1 terminated
2023-02-21T04:22:11.828409Z	error	Envoy exited with error: signal: segmentation fault
2023-02-21T04:22:11.828437Z	info	ads	ADS: "@" productpage-v1-66756cddfd-whs2c.default-2 terminated
```

I have also tried [proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) and resulted similar errors.

**Comment by zirain** [comment]
cc @kyessenov

**Comment by kyessenov** [comment]
Maybe try a newer version? It would help to run with asan or dbg build, e.g. 
```
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-$SHA.tar.gz
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-$SHA.dwp
```

(dwp file must be in the same directory as binary). SHA is any SHA from istio/proxy.

**Comment by jian1106** [comment]
Thanks for your replying.  
#### New Versions
I have tried istio 1.16.3 and 1.17.0. Both of them are stuck at `fetching image` and wasm plugin is not loaded.
1. Istio version 1.16.3
Envoy Version:
```
05baa6869b0a1e7d761fc2770b8f556755ca5b73/1.24.3-dev/Clean/RELEASE/BoringSSL
```
Envoy Logs:
```
info	wasm	fetching image jian1106/wasm-demo from registry index.docker.io with tag 0.0.2
```
2. Istio version 1.17.0
Envoy Version:
```
077e651879170a2c6d3e0b4026057a15abe150bf/1.25.2-dev/Clean/RELEASE/BoringSSL
```
Envoy Logs:
```
info	wasm	fetching image jian1106/wasm-demo from registry index.docker.io with tag 0.0.3
```
#### About asan and dbg builds
All links are returned 404.
1. . branch release-1.15
The commit is https://github.com/istio/envoy/commit/0952f68250f14f051b43cc87ae6f61a17bf9470a
```bash
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-0952f68250f14f051b43cc87ae6f61a17bf9470a.tar.gz
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-0952f68250f14f051b43cc87ae6f61a17bf9470a.dwp
```
2. branch release-1.16
The commit is https://github.com/istio/envoy/commit/35b56432218e70fb8b0ebd9ebb847b58ebf692d5
```bash
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-35b56432218e70fb8b0ebd9ebb847b58ebf692d5.tar.gz
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-35b56432218e70fb8b0ebd9ebb847b58ebf692d5.dwp
```
3. branch release-1.17
The commit is https://github.com/istio/envoy/commit/2e58bc95ea56c6d7c5c1126fa7379974f8413c1a
```bash
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-2e58bc95ea56c6d7c5c1126fa7379974f8413c1a.tar.gz
wget https://storage.googleapis.com/istio-build/proxy/envoy-asan-2e58bc95ea56c6d7c5c1126fa7379974f8413c1a.dwp
```

**Comment by kyessenov** [comment]
Most likely the crash is https://github.com/envoyproxy/envoy/issues/25052. It looks like the wasm image cannot be pulled for some reason (maybe some credentials missing?)

**Comment by kyessenov** [comment]
BTW the SHA should be istio/proxy not envoy.

**Comment by jian1106** [comment]
This problem only seems to occur on my macOS computer, when I follow these steps on another Windows computer ( Docker-Desktop + WSL2) or on my colleague's macOS computer, the problem goes away.

**Comment by zirain** [comment]
@jian1106 M1 mac?

**Comment by jian1106** [comment]
@zirain No, it was an Intel Hackintosh ( with case sensitive APFS disk). 🤣  Also tested on M1 & M2 and resulted to OK.
