### ISSUE TITLE
istio pods do not handle error conditions well

### ISSUE THREAD

**Issue by ingshtrom** [istio/istio#435]
I've seen several instances where various istio pods require restarting (I kill the active pod and let ReplicationSets create a new one) because something was not as it should be.

Take, for example, the numerous issues with RBAC and ClusterRoleBinding issues (there are several tickets for this). If istio-ingress or istio-egress get into that state where it doesn't have the correct permissions to perform an action it will continue retrying to do the operation. That's fine and dandy except that once I add the permission to Role or create a ClusterRoleBinding instead of a RoleBinding, then I have to restart the pod in order for it to take effect. 

The same situation happens if istio-ingress doesn't generate the correct files on startup. It keeps retrying, not finding those resources (`istioconfigs.istio.io` andn `istioconfig`). I have to restart the pod in order for it to create those resources.

The most recently display of this lack of error handling was shown to me after a full cluster meltdown. I'm still investgating the core issue (https://github.com/coreos/tectonic-forum/issues/152), but essentially all of the pods/services/deployments/ingresses/etc were restarted and once that happened `istio-ingress` was no longer able to access `istio-pilo`, thus it couldn't set the correct load balancer for the istio ingress in the BookInfo sample. All I did was restart the `istio-ingress` service and it was fixed.

This last one makes me think maybe it's more of a problem with Kubernetes not refreshing the DNS within the pods/containers, so hitting `http://istio-pilot` continually results in timeouts or econnrefused.

Is this know? I'm also new to Kubernetes so forgive me if some of my assumptions/comments are naive.

Thank you for istio, though! When I do get it working, it is AMAZING!

**Comment by ldemailly** [comment]
access to pilot doesn't go through ingress so that seems odd

if you have a simple repro sequence and specific details that would be appreciated,
can you file those in
https://github.com/istio/issues/issues

the soon to come 0.2 release should also make things a lot smoother than 0.1.6 was

(will close this in the meantime)
