### ISSUE TITLE
ambient: remove special test framework flag

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43508]
The special mode makes it harder to run the test in all scenarios (postsubmit, etc)

**Comment by keithmattix** [comment]
Can you (or someone else) provide some background on why the flag was added in the first place before I just remove it and potentially break something?

**Comment by keithmattix** [comment]
not stale

**Comment by pegasas** [comment]
I create a PR add flags into integration test README.md https://github.com/istio/istio/pull/46708
to make this question clear.

**Comment by stevenctl** [comment]
Reopening since the fix was reverted. I can't really merge that until it wouldn't break postsubmit. The problem is, it ends up revealing a real caching bug.
