### ISSUE TITLE
Support traffic mirroring < 1%

### ISSUE THREAD

**Issue by dwj300** [istio/istio#43511]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
For many of the other percent fields in istio, we use percentage as a floating point to permit small percentages. https://github.com/istio/istio/pull/16939 added mirror_percent as a UInt, making it impossible to mirror less than 1% even though Envoy supports down to 1 / 1e6. Would it be reasonable for me to create a mirror_percentage field for this and deprecating mirror_percent? See https://github.com/istio/istio/issues/14437

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
There already is a mirror_percentage which is a float?

**Comment by dwj300** [comment]
Oops, was reading stale docs. https://istio.io/latest/docs/reference/config/networking/virtual-service/#Percent is indeed a float. Thanks!
