### ISSUE TITLE
ebpf redirection follow ups

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#43525]
Some follow ups: 

- [X]  Minimize vmlinux.h
- [ ]  IPv6 support
- [ ] other CNI support( calico ebpf, cilium)
- [ ]  move /sys/fs/bpf  ahead of time and fall back if  bpf is not supported on host

**Comment by irisdingbj** [comment]
cc @PlatformLC @howardjohn @bleggett

**Comment by bleggett** [comment]
A few more (maybe more long term, but before this is considered non-experimental)

[ ] We need to settle on an LTS kernel version range we are willing to sign up to support and test against - and if the lower bound ends up being 5.x.x we should make use of newer/better/faster eBPF kernel APIs present in those kernels.

[ ] `app_info` map (and hardcoded pod limits) isn't actually necessary IMO and can be removed with some tweaks to the progs/by making use of the kernel FIB table.


The IPv6 support for eBPF specifically is part of the larger ticket https://github.com/istio/istio/issues/41008 for enabling IPv6 for the ambient feature specifically.

**Comment by bleggett** [comment]
Another thing I just realized - current eBPF CNI impl only works for CNIs that use `veths`

IIRC there are some that do not use `veths` and we would fail there.

That _might_ be fine, since I think the majority of the CNI stuff we care about do use `veths` and we can just support those.

**Comment by bleggett** [comment]
not stale
