### ISSUE TITLE
Istio egressgateway 16.1 TLS_error:_33554536:system_library:OPENSSL_internal:Connection_reset_by_peer

### ISSUE THREAD

**Issue by psandhu79** [istio/istio#43540]
### Bug Description

I followed this example 
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

Everything works as expected however for one of the 3rd party api servers i connect to through the egress-gateway i get the following error 

"upstream_transport_failure_reason":"TLS_error:_33554536:system_library:OPENSSL_internal:Connection_reset_by_peer",

almost the same as this issue #39077 

the server in question i had previous issues with as well when using this config 

[previous egress gateway setup with ngnix sni proxy](https://istio.io/v1.4/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy)

I had the following options for ngnix sni proxy to make it work with the 3rd party api gateway 

          proxy_ssl_name $host;
          proxy_http_version 1.1;
          proxy_ssl_server_name on;

However since switching to the preferred method it stopped working again 

### Version

```prose
client version: 1.9.1
control plane version: 1.16.1
data plane version: 1.16.1 (206 proxies)

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.9-gke.2000
```

**Comment by psandhu79** [comment]
Turned on debug but cannot see obvious error

jsonPayload: {
level: "debug"
msg: "[C82494][S12470871001166590339] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer"
scope: "envoy router"

If i exec into the egressgateway and curl the site curl -vvI https://dev.example.com

it gets all the TLS information ok

**Comment by liykfrank** [comment]
I'm experiencing the same issue. 
It seems something wrong in TLS handshake. The server hello is missing. server side always return a Reset after client hello
![image](https://user-images.githubusercontent.com/26363251/220922426-ece3004c-c7ba-414e-8811-4d332256f18a.png)

**Comment by psandhu79** [comment]
looking in the trace logs the only thing i see wrong is 
[C87372] ssl error occurred while read: WANT_READ

**Comment by GregHanson** [comment]
Was this working in a previous istio version or is 1.16.1 the first time you hit this problem?  Also for TLS debugging you may need to turn on `trace` level logging in order to capture more of the error.

you may also want to check https://github.com/istio/istio/issues/42790 and https://github.com/istio/istio/issues/40680 to see if it's related

**Comment by psandhu79** [comment]
So I managed to fix it by looking this issue #32907 

i had to add the bold text

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-ext
spec:
  host: echo.dev.xxx
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE # initiates HTTPS when accessing echo.dev.xxx
        **sni: echo.dev.xxx**
```

Why some of the destination rules worked and this one didnt not sure.

**Comment by liykfrank** [comment]
In my case, it's caused by [ECDSA certificates P-384 was not supported by Envoy by default](https://github.com/envoyproxy/envoy/issues/10855).
So we have to enable P-384 with a EnvoyFilter
`              
         common_tls_context:

                tls_params:

                  ecdh_curves: 

                    - P-384`

**Comment by ldemailly** [comment]
@liykfrank thx, and you didn't hit the "only p256" exception that seems to be in the code?
