### ISSUE TITLE
Istio Helm charts should not assume that the release is in the istioNamespace

### ISSUE THREAD

**Issue by keithmattix** [istio/istio#43569]
### Bug Description

The Istio manifests often reference `Release.Namespace` in [chart templates](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml#L5). However, in these cases, the assumption is being made that the Helm release namespace is the same as the `global.istioNamespace`. Users may want to install the Helm release in a different namespace, so templates should use `global.istioNamespace` instead.

### Version

```prose
N/A
```

**Comment by howardjohn** [comment]
hmm, it seems very inconsistent as-is. I assume its totally broken if they are not the same today? is that accurate?

**Comment by keithmattix** [comment]
Yeah pretty much

**Comment by martynd** [comment]
To focus on the question asked in the prior PR (https://github.com/istio/istio/pull/43572#issuecomment-1454180031)
Use cases involving subcharts are ones which I think would most benefit from changes similar to those mentioned here (there is no way to override the release namespace of subcharts if they use `.Release.Namespace` exclusively). Having the ability to do this would also make it easier to work in line with istio best practices relating to separation of gateways and istiod as well.

Limiting the scope of an example scenario to Istio components, a simple example could be an Istio chart comprised of 3 subcharts (described below). This would allow for a single self contained release which handles the different components with the overlapping global values kept together and keeps it manageable as a single entity

The hypothetical chart could contain 3 subcharts:
 - base
 - istiod
 - gateway
- (kiali might be a good example for a non istio component that would fit with being in a subchart alongside istiod)

As the namespace used on resources is fixed to the `Release` value it means whatever you do the gateway will always be hard tied to the same namespace as istiod. If it was overridable on a per component level, it would then be trivial to have the release namespace be `istio-system`, while having the gateway install into `istio-ingress` while also keeping everything else closer together (It would even allow the values to align more with the IstioOperator spec)


To simplify the size/scope of proposed changes mentioned in the PR, the changes could be limited in scope to the secondary components. Istiod/Istio-remote and all directly associated resources would still then be tied to the release namespace

For completeness however, a similar scenario which would benefit from it also being overridable on Istiod + friends would be if the same example chart was itself used as a subchart. In this scenario the release namespace might be entirely unrelated to istio but then can be overridden back to istio-system when it runs the subchart of the combined istio components

**Comment by keithmattix** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale
