### ISSUE TITLE
Fix warnings generated from istioctl analyze

### ISSUE THREAD

**Issue by linsun** [istio/istio#43589]
### Bug Description

```
istioctl analyze
Warning [IST0108] (Deployment default/bookinfo-productpage-istio-waypoint) Unknown annotation: istio.io/for-service-account
Warning [IST0108] (Pod default/bookinfo-productpage-istio-waypoint-66f9db6966-ghzhz) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/bookinfo-productpage-istio-waypoint-66f9db6966-ghzhz) Unknown annotation: istio.io/for-service-account
Warning [IST0108] (Pod default/details-v1-7d4d9d5fcb-s2ljz) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/notsleep-bb6696574-jsb9g) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/productpage-v1-7b4dbf9c75-9tv67) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/ratings-v1-85cc46b6d4-ws8hv) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v1-777df99c6d-wxw2s) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v2-cdd8fb88b-x5gq8) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v3-58b6479b-h76r4) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/sleep-5644bdc767-zv4l9) Unknown annotation: ambient.istio.io/redirection
```

Might be good to update this message too that we ask user either label for sidecar or ambient.

```
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
```

### Version

```prose
1.18-dev
```

**Comment by linsun** [comment]
cc @GregHanson if you have bandwidth

**Comment by GregHanson** [comment]
will do - was wondering if there were any analyze additional messages we should generate for ambient

**Comment by hanxiaop** [comment]
The annotations depend on those listed in https://github.com/istio/api/blob/master/annotation/annotations.yaml. I believe they will become recognizable once we include them in the YAML.

**Comment by GregHanson** [comment]
collecting a list of all items here https://github.com/istio/istio/issues/43437

**Comment by GregHanson** [comment]
@howardjohn based on https://github.com/istio/istio/issues/43614, it seems like https://github.com/istio/api/pull/2695 is premature - should I limit the new labels I'm adding in the istio/api PR to just the offending ones from analyze?  Or should find a way to keep the changes to `istioctl` code until ambient naming/api concerns are addressed?

**Comment by hanxiaop** [comment]
> should I limit the new labels I'm adding in the istio/api PR to just the offending ones from analyze

I think we should filter out those that were not added by users. Currently, the result is full of 'Unknown annotation' messages.

**Comment by GregHanson** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
> I'm getting the same warning after installing the bookinfo app
> 
> ```
> $ istioctl analyze
> Warning [IST0108] (Pod bookinfo/details-v1-698d88b-bpmjl) Unknown annotation: istio.io/rev
> Warning [IST0108] (Pod bookinfo/productpage-v1-675fc69cf-ddh2z) Unknown annotation: istio.io/rev
> Warning [IST0108] (Pod bookinfo/ratings-v1-6484c4d9bb-m4nv8) Unknown annotation: istio.io/rev
> Warning [IST0108] (Pod bookinfo/reviews-v1-5b5d6494f4-5nvxr) Unknown annotation: istio.io/rev
> Warning [IST0108] (Pod bookinfo/reviews-v2-5b667bcbf8-5m5hm) Unknown annotation: istio.io/rev
> Warning [IST0108] (Pod bookinfo/reviews-v3-5b9bd44f4-xnk7g) Unknown annotation: istio.io/rev
> ```

This is not a related problem. `istio.io/rev` should be a known annotation. Which version of istioctl are you using?

**Comment by aruntomar** [comment]
> > I'm getting the same warning after installing the bookinfo app
> > ```
> > $ istioctl analyze
> > Warning [IST0108] (Pod bookinfo/details-v1-698d88b-bpmjl) Unknown annotation: istio.io/rev
> > Warning [IST0108] (Pod bookinfo/productpage-v1-675fc69cf-ddh2z) Unknown annotation: istio.io/rev
> > Warning [IST0108] (Pod bookinfo/ratings-v1-6484c4d9bb-m4nv8) Unknown annotation: istio.io/rev
> > Warning [IST0108] (Pod bookinfo/reviews-v1-5b5d6494f4-5nvxr) Unknown annotation: istio.io/rev
> > Warning [IST0108] (Pod bookinfo/reviews-v2-5b667bcbf8-5m5hm) Unknown annotation: istio.io/rev
> > Warning [IST0108] (Pod bookinfo/reviews-v3-5b9bd44f4-xnk7g) Unknown annotation: istio.io/rev
> > ```
> 
> This is not a related problem. `istio.io/rev` should be a known annotation. Which version of istioctl are you using?

I'm on the following version 
```$ istioctl version
client version: 1.16.1
control plane version: 1.20.0
data plane version: 1.20.0 (7 proxies)
```

**Comment by aruntomar** [comment]
Upgrading istioctl version solved the warning. 
```
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (7 proxies)
```

```
$ istioctl analyze

✔ No validation issues found when analyzing namespace: bookinfo.
```
Previously, I had installed istio from my linux package manager. Normally it's frequently updated and has the latest versions. But in this specific case, it was 1.16, but the latest was 1.20. And i guess, that was somehow throwing that warning.  Thank you for the help.

**Comment by hanxiaop** [comment]
> Upgrading istioctl version solved the warning.
> 
> ```
> $ istioctl version
> client version: 1.20.0
> control plane version: 1.20.0
> data plane version: 1.20.0 (7 proxies)
> ```
> 
> ```
> $ istioctl analyze
> 
> ✔ No validation issues found when analyzing namespace: bookinfo.
> ```
> 
> Previously, I had installed istio from my linux package manager. Normally it's frequently updated and has the latest versions. But in this specific case, it was 1.16, but the latest was 1.20. And i guess, that was somehow throwing that warning. Thank you for the help.

Yeah we have fixed several analysis issues in different versions, so it's always good to use the latest istioctl versions.

**Comment by linsun** [comment]
@hanxiaop are the issues reported here all fixed? Let me know - i can try latest code base

**Comment by aruntomar** [comment]
yes. this issue can be closed.

**Comment by hanxiaop** [comment]
> @hanxiaop are the issues reported here all fixed? Let me know - i can try latest code base

This has been fixed, I'll close the issue.
