### ISSUE TITLE
Istio create fails because "default" namespace doesn't exist?

### ISSUE THREAD

**Issue by ingshtrom** [istio/istio#436]
Like the title says, `istioctl create -f samples/apps/bookinfo/route-rule-all-v1.yaml -v 9999` fails with the following output: 
![image](https://user-images.githubusercontent.com/571756/27638946-d2fea25a-5be2-11e7-9a60-35182f0672f0.png)

It seems like probably a kubernetes problem, but since I ran `istioctl create` and not `kubectl create`, I figured I would check here first. 

The namespace definitely exists: 
![image](https://user-images.githubusercontent.com/571756/27639001-fdefa1c6-5be2-11e7-9029-8513ee65cc0f.png)

I am using Tectonic v1.6.4 which uses upstream Kubernetes v1.6. In the past, I've had trouble using Tectonic-based Kubernetes clusters because the authentication scheme is different, but this doesn't look to be the same issue.

Here is a tail of `kube-apiserver` logs. The reason I include these is because it doesn't seem like I should be receiving these messages, based on what I've read, but I'm new to Kubernetes so I figure the more information the better: 
![image](https://user-images.githubusercontent.com/571756/27639147-60dccc1e-5be3-11e7-8cc5-55095b77c3c2.png)
 
Thanks

**Comment by dtzar** [comment]
It appears that istio MUST be installed into the default namespace.  I install Istio into a different namespace and when I try to do a `kube-inject` it fails stating that it must be present there.  This would have been good to know - maybe I missed it but I didn't  see this anywhere in the documentation.  I would imagine this is resolved once #146 is implemented.

```
kubectl apply -f <(istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml) --namespace demodev
Error: Istio configuration not found. Verify istio configmap is installed in namespace "default" with `kubectl get -n default configmap istio`
error: no objects passed to apply
```

**Comment by lookuptable** [comment]
@dtzar `istioctl` tries to read the configmap from the `default` namespace unless otherwise specified. You can parse the non-default namespace to istioctl like this:
`kubectl apply -f <(istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml --namespace demodev) --namespace demodev
`

**Comment by dtzar** [comment]
Thanks for the tip @lookuptable - this worked.  That said, as a note to anyone else playing with Istio deployed to namespaces outside of *default* - in its current state:

- when you do a `kube-inject` it references the `istio.default` secret which will only exist in the namespace where Istio is installed. So you can't install your application to a namespace other than where it is installed unless you recreate the secrets in that namespace also (not sure if this would even be supported and pretty sure isn't documented).
- `istioctl kube-inject -f sample.yaml -o sample-with-inject.yaml` will actually complete without error if you installed Istio to a namespace other than default, BUT the sample-with-inject.yaml file will be entirely blank.  When you use the --namespace switch with it where Istio resides the file will be properly generated.
