### ISSUE TITLE
Proxy version regex/prefix is too wide

### ISSUE THREAD

**Issue by sukolenvo** [istio/istio#43602]
### Bug Description

There are several places in the code (eg [here](https://github.com/istio/istio/blob/master/pilot/pkg/model/envoyfilter.go#L58-L76) and [here](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml#L2356)) that use following style regex for version matching: `^1\.6.*`, `^1\.16.*`. 

This regex generates unwanted matches. E.g version string `1.60`, `1.60.1` is matched by regex `^1\.6.*` and version `1.161` is matched by regex `^1\.16.*`.

### Affected user group
During upgrade process outdated envoy filters are not removed by automatically (at least GKE, have not check other installation types), hence filters accumulate over time. This filters don't cause any problems (yet) because they don't match proxy version. For example here is list of filters in one of our clusters.
```bash
$ kubectl get envoyfilter -n istio-system | grep stats-filter
stats-filter-1.10            536d
stats-filter-1.11            330d
stats-filter-1.12            330d
stats-filter-1.13            330d
stats-filter-1.6             2y77d
stats-filter-1.7             2y77d
stats-filter-1.8             2y77d
stats-filter-1.9             536d
tcp-stats-filter-1.10        536d
tcp-stats-filter-1.11        330d
tcp-stats-filter-1.12        330d
tcp-stats-filter-1.13        330d
tcp-stats-filter-1.6         2y77d
tcp-stats-filter-1.7         2y77d
tcp-stats-filter-1.8         2y77d
tcp-stats-filter-1.9         536d
```
Therefore there is a risk that for many users when istio proxy v1.60 is deployed, it will be patched both by stats-filter-1.6 and stats-filter-1.60.

### Improvements
1. Regex can be updated to `^1\.19(\..+)?` to have correct matching;
2. Proxy match function can be updated to have safer prefix match logic (exact string match or require dot after prefix)https://github.com/istio/istio/blob/a4565e895f4797aea46010266aa610a630decc43/pilot/pkg/model/envoyfilter.go#L146
3. Alert user of outdated filters during upgrade process or in docs (maybe already done?).

### Notes
I've noticed performance notice in code, I have not measured performance impact of proposed steps from _improvements_ section (based on my limited understanding of code it look good, would be nice if somebody better familiar with codebase could confirm this code is not executed in some critical "hot" spot) https://github.com/istio/istio/blob/a4565e895f4797aea46010266aa610a630decc43/pilot/pkg/model/envoyfilter.go#L114-L116

I would like to help with PR for (1) and (2) steps from _improvements_ if needed, not sure what is the best way around (3).

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (74 proxies)
$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.14-gke.1800
```

**Comment by howardjohn** [comment]
We are about to remove this code anyway so if it will only break during version 1.40 (~6 years) I think we will be fine with no action. Or is there risk before then?

**Comment by sukolenvo** [comment]
You are right, it's not gonna cause any issues in the nearest future. I just spotted the problem while working on other tasks and thought I would report so we can keep track of it.
