### ISSUE TITLE
CNI plugin does not clean up ambient node rules on uninstall

### ISSUE THREAD

**Issue by bleggett** [istio/istio#43601]
### Bug Description

When doing an `istioctl uninstall --purge`, the CNI plugin does not clean up any of the ambient networking configs it creates - because node-level `cleanup` function is not actually invoked on ambient CNI server termination.

While testing https://github.com/istio/istio/pull/43578 I noticed this, but it seems to predate those changes - I suspect the CNI plugin was _never_ properly running its own cleanup routines on termination, and the inclusion of the `preStop` hook with duplicated cleanup logic in the helm chart was masking this.

### Version

Current `master` with ambient profile.

**Comment by dhawton** [comment]
This should be handled by the daemonset when it terminates instead of the plugin.

**Comment by bleggett** [comment]
> This should be handled by the daemonset when it terminates instead of the plugin.

Why?

**Comment by bleggett** [comment]
Right - I'm misusing my terminology - the CNI plugin installer runs and exits - I'm talking about the ambient CNI long-running server itself. 

`cni/pkg/ambient/server.go` - it is not cleaning up when it is stopped, that's the bug.

**Comment by bleggett** [comment]
Should be fixed with #43641
