### ISSUE TITLE
Prevent ossification of ambient 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43614]
In ambient, we have made a lot of design decisions, from behaviors, APIs, headers, etc. All of this is "alpha". Given the size and scope of these changes, and that we probably only have one opportunity to "get it right", it's critical that we can make the right decisions.

IMO, this can only reasonably done through iteration. Theoretically the feature progression between alpha beta stable provides this. In practice, things have been historically locked in after the first alpha release (1.18 for ambient).

To avoid this, we should make explicit measures to avoid ossification in ambient so that we have flexibility to make required changes.

Ideas:
* prefix APIs with experimental-
* Very very clear, alarms blaring, warning documentation
* Following above, make uses explicitly acknowledge the alpha style in ambient??
* Vague idea - intentionally make breaking changes. This is likely only useful if we remain in alpha for  a long time without any natural changes. This is a bit like the Google SRE trick or intentional downtime when exceeding SLOs.

cc @costinm

**Comment by costinm** [comment]
I think most impact will be to have alpha/experimental off by default, with narrow opt-in ( workload ) and clear experimental- prefix.

We can also have an install mode that clearly indicates it's experimental and unsupported and allows broader use for testing.

**Comment by costinm** [comment]
It may ne better to identify first what we do want to treat as stable:
- api - K8S Gateway seems clear, a subset of Istio beta APIs ( authz, etc ) - when applied to a gateway
- an narrow subset of api that apply to ztunnel
- default protocol based on h2 and a subset of headers
- MCS API if we can finish enabing it
- ???

I think most install options, labels, annotations are to be treated as experimental - for a long time we had the goal to either promote to CRD and  beta or deprecate. That probably won't work for sidecar/original Istio, but may work for ambient if we start right.

**Comment by GregHanson** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale
