### ISSUE TITLE
Pilot: Cleanup old references to Istio Service

### ISSUE THREAD

**Issue by rshriram** [istio/istio#4361]
Existing code in pilot/pkg/model refers to v1alpha1 version of IstioService for converting from the Mixer representation of service to routing's representation of service. 
These references occur in model/config.go in HTTPApiSpecByDestination, QuotaSpecByDestination, EndUserAuthenticationPolicyByDestination, etc. 

v1alpha3 has no notion of Istio service.  So the logic above has to be changed.
Assigning it to some folks that I think are responsible for this piece of code. If someone else is responsible, please reassign.

**Comment by diemtvu** [comment]
This will be replaced by authentication policy. We will leave EUA as is for now, and it can be removed together with v1 when the time come. Hopefully we have working authN policy by then.

**Comment by diemtvu** [comment]
Mentioned functions have been switched to use ServiceInstance or service name (string).
