### ISSUE TITLE
Support both istio.io/rev=canary and istio-injection=enabled in a namespace

### ISSUE THREAD

**Issue by jas063** [istio/istio#43621]
My use case is to use  `istio-injection=enabled` label across all namespaces to inject the sidecars and if later while upgrading istio if any issue occurs then change the label of that namespace to previous revision like `istio.io/rev=1.16`

Is it possible to use either `istio.io/rev=1.17` label or `istio-injection=enabled` label in a namespace to inject the sidecar?

I could only use `istio.io/rev=1.17` label or `istio-injection=enabled` across all namespaces but not combination of both.

**Comment by howardjohn** [comment]
Yes, you can have some namespaces with istio.io/rev=1.17 and some with istio-injection=enabled. Note you cannot set BOTH of these on one namespace since its conflicting
