### ISSUE TITLE
Document how to use helm to install istio plus cni module

### ISSUE THREAD

**Issue by cdm-arm** [istio/istio#43632]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
1. Add a per installation method guide to the CNI installation like it is eg. done at https://istio.io/latest/docs/setup/additional-setup/gateway/. This to allow a working setup of cni for helm users.
2. In addition it would be cool to add some generic hint on how to figure out the cni-bin dir. For people new to the material it's hard to figure out that this can be most likely determined on a node like this:
```
worker:/# ps -ef | grep cni
root      1234  4321  4 Feb17 ?        10:59:12 kubelet --cni-bin-dir=/var/vcap/jobs/kubelet/packages/cni/bin --container-runtime=docker --docker=unix:///var/vcap/sys/run/docker/docker.sock --docker-endpoint=unix:///var/vcap/sys/run/docker/docker.sock --event-qps=0 --kubeconfig=/var/vcap/jobs/kubelet/config/kubeconfig --network-plugin=cni --pod-infra-container-image=registry.tkg.vmware.run/pause:3.2 --root-dir=/var/vcap/data/kubelet --cloud-provider=vsphere --config=/var/vcap/jobs/kubelet/config/kubeletconfig.yml --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
root     11189 10309  0 15:26 pts/0    00:00:00 grep --color=auto cni
root     28818 28790  0 Feb21 ?        00:02:01 install-cni --log_output_level=default:info
```

**Describe alternatives you've considered**
Dropping the flux compliant deployment of istio via helm charts.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Multiple issues point to https://istio.io/latest/docs/setup/additional-setup/cni/ and state that his is the complete setup guide on how to get CNI running. The problem is that there is only a guide on how to use istioctl to get it running. Usage of the helm chart that are now no longer marked as experimental in the docs is not covered. Some issues also point to the cni helm chart at https://artifacthub.io/packages/helm/istio-official/cni which neither explains how to get it running.
Amending a otherwise working istio helm installation with a ```helm install istio-cni istio/cni -n kube-system``` or a ```helm install istio-cni istio/cni -n istio-system```are not enough to get cni working.

**Comment by aek-arm** [comment]
See for example https://github.com/istio/istio/issues/39527#issuecomment-1437219451

**Comment by bhavyastar** [comment]
Hey @zirain, I would like to work on this Issue!! Happy to help if you could assign this to me!

**Comment by hamishforbes** [comment]
Took me ages to figure this out as well...

Thee CNI setup doc (https://istio.io/latest/docs/setup/additional-setup/cni/) just needs to have a paragraph somewhere near the top that says "if using helm you must set `values.istio_cni.enabled` on the istiod chart too"

The only place it's mentioned is under *Upgrade* and then it's in a roundabout way without actually mentioning helm, just that the value needs to be set (via IstioOperator in the example)

**Comment by aek-arm** [comment]
Another problem is that the often referred helm chart does not even list anything cgi related:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/80111669/224254536-d74846ff-89e1-4a74-96f2-d279efbca2ae.png"> 
Guess adding it to the default values with a false value would also help.

**Comment by bhavyastar** [comment]
Thanks for all of the suggestions. I will soon create a Pull request and if I need any help will definitely let you know.

**Comment by SebTardif** [comment]
Not seeing that istio_cni is a variable when asking the helm of istiod also got me in the wrong direction. This bug report clarified what are the expectations so now I know what to search to find that hidden doc -> https://github.com/istio/istio/blob/da6178604559bdf2c707a57f452d16bee0de90c8/manifests/charts/README-helm3.md

**Comment by funkypenguin** [comment]
Just another weary traveler, who also discovered that `istio_cni.enabled` is entirely missing from the helm chart! I'll submit a PR to address this shortly...
