### ISSUE TITLE
Make port 15006 configurable

### ISSUE THREAD

**Issue by edubonifs** [istio/istio#43655]
Hi, 

We are hitting some problems when we have some managed cloud services which also exports the same ports as Istio do. For example, Azure's managed redis requires ports from 15000-15009 to be open. This is causing problems with duplicated addresses in Istio when we want to create a serviceEntry exposing the same ports for example.

I have seen that some ports are configurable from Istio side, I would suggest that also port 15006 is configurable and not hard coded. I think this could avoid some problems of duplicated ports that is causing problems also on envoy side.

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
> Azure's managed redis requires ports from 15000-15009 to be open

cc @keithmattix can you confirm this?

**Comment by edubonifs** [comment]
![image (2)](https://user-images.githubusercontent.com/60875825/222105608-e94f0269-99cf-4bae-97c6-c40dde50ac9c.png)

**Comment by edubonifs** [comment]
Hi, here you have Azure statement in docs, I think not only port 15006 but we will have problems with more ports from 15000 to 15019

**Comment by keithmattix** [comment]
Yep, thanks for raising this @edubonifs. This is something we were generally aware of, but hadn't heard of a ton of cases yet. Based on the TODO @zirain linked, it seems like there's a desire to make these ports configurable? Is there an existing issue somewhere?

**Comment by keithmattix** [comment]
Yes, thanks for the fix @zirain! I agree with @costinm it seems that we may need to make all ports configurable long-term, but this is a good start
