### ISSUE TITLE
Support multiple key-value pairs for same type meshConfigExtensionProvider

### ISSUE THREAD

**Issue by rbisecke** [istio/istio#43669]
Currently, all of the meshConfigExtensionProvider are single one-offs, given that they can only exist as a single field in the meshConfigExtensionProvider: [merge_iop.go#L168](https://github.com/istio/istio/blob/9d658a994b82e86827a32489e718845e43f30508/operator/pkg/util/merge_iop.go#L168). I have a use case for the different AuthorityPolicy CRDs to use a different `EnvoyExtAuthzHTTP` but only one can exist at a time right now, even if it has a unique name. The `meshConfigExtensionProvider` struct can be updated to instead use `map[key] EnvoyExtAuthzHTTP` where the name is key. This would allow multiple of them to exist and able to be used in the mesh without error.

**Comment by zirain** [comment]
can you share more details about your nstallation (with istioctl or IstioOperator), a demo iop file would be better.

**Comment by hanxiaop** [comment]
Do you want to use different providers for the same workload? I think even it's possible to specify different `EnvoyExtAuthzHTTP ` providers, the current limitation is one workload can only have one provider. Check this for more info https://github.com/istio/istio/issues/34041.

**Comment by rbisecke** [comment]
Ya, this can be marked as a duplicate of that open issue. Thanks for the reference. Will post any further discussion there.

**Comment by hanxiaop** [comment]
Closed as a dup of https://github.com/istio/istio/issues/34041
