### ISSUE TITLE
Playbook should be extended to allow to install Web Hook

### ISSUE THREAD

**Issue by cmoulliard** [istio/istio#4366]
Current istio ansible playbook doesn't install `web hooks` as described within the doc - see [https://istio.io/docs/setup/kubernetes/sidecar-injection.html](url) - `installing the Web Hook`

Playbook should be extended to allow to install it

**Comment by metacosm** [comment]
Proper link: http://istio.io/docs/setup/kubernetes/sidecar-injection.html

**Comment by ayj** [comment]
Is this still necessary with https://github.com/istio/istio/pull/4466?

**Comment by ostromart** [comment]
Seems to be stale, closing.
