### ISSUE TITLE
MCS: use endpoint subsetting

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43671]
Currently we make a cluster for clusterset.local and for cluster.local. We may consider using a shared cluster/EDS, and pick the local subset using https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets.

This needs more discussion before implementation, this is just an idea at this point.

**Comment by keithmattix** [comment]
This sounds right; I'm curious if trustDomain alias would be helpful in improving the MCS experience

**Comment by howardjohn** [comment]
I'm not sure the relationship? Do you mean some sort of trust domain per cluster, etc?

**Comment by keithmattix** [comment]
I don't know how trustDomainAlias is represented in Envoy config, but I assume it's some kind of extra SAN matcher; if there are two separate Envoy clusters, my guess is both clusters get both trustDomains? And then with a shared cluster, they'd definitely get both trustDomains right? I'm just thinking through the general cluster.local vs. clusterset.local problem; maybe there's a better issue for thta

**Comment by howardjohn** [comment]
Its a SAN matcher in clsuter, yes. But the clsuterset.local and cluster.local would have the same config. Unless we decided we allow different config for them

**Comment by hanxiaop** [comment]
not stale
