### ISSUE TITLE
Autoscaling k8s cluster while preserving source client ip 

### ISSUE THREAD

**Issue by triptesh1212** [istio/istio#43684]
### Bug Description

Hi Community, 
     We are trying to understand this behaviour of "preserving the original source ip address of client" in case where the Kubernetes cluster can autoscale in the runtime. We are using AWS Cluster with "nlb" Load Balancer and have set the "externalTrafficPolicy" to "local" at istio-ingress service, according to the following documentation. (https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client)

When the cluster autoscale and adds a new node to the cluster, we observed that it does not get added to the load balancer target group. We waited for more than an hour but still the target group does not reflect the new node.
However, in case of "externalTrafficPolicy" as "Cluster", it gets added to the target group of the load balancer within few mins.

We are of the opinion that this could be a bug and needs to be fixed.

Thanks,
Triptesh

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (2 proxies)

kubectl version --short
Client Version: v1.21.0
Server Version: v1.25.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by subhankarc** [comment]
@bleggett @howardjohn could you please throw some light on this behaviour ?

**Comment by bleggett** [comment]
@subhankarc This is, IMO, purely a problem between AWS's NLB implementation and Kubernetes' `externalTrafficPolicy` setting. If this doesn't work, it's between Kube and AWS, and Istio isn't directly involved.

See: https://github.com/kubernetes/cloud-provider-aws/issues/87

I would take this up with AWS.

**Comment by subhankarc** [comment]
Hi @bleggett ,

We checked the behaviour on Azure as well. The behaviour seems to be similar. I would raise an issue on the cloud-provider-aws to see if the Kube and loadbalancer behavour together has anything to do with it.

**Comment by subhankarc** [comment]
added https://github.com/kubernetes/cloud-provider-aws/issues/575

**Comment by hzxuzhonghu** [comment]
It seems  not related to istio.
