### ISSUE TITLE
Istio Build Error on Mac: 

### ISSUE THREAD

**Issue by TiwariAjay123** [istio/istio#43689]
### Bug Description

While building the Istio from the source I am getting following error:
ERROR: /private/var/tmp/_bazel_ajaytiwari/a062094a096e494df315bac67b9fc6d9/external/envoy/contrib/network/connection_balance/dlb/source/BUILD:27:27: Compiling contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @envoy//contrib/network/connection_balance/dlb/source:connection_balancer) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' ... (remaining 149 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/envoy/contrib/network/connection_balance/dlb/source/connection_balancer_impl.cc:3:10: fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
INFO: Elapsed time: 318.909s, Critical Path: 14.35s
INFO: 608 processes: 9 internal, 599 darwin-sandbox.
FAILED: Build did NOT complete successfully
make: *** [build] Error 1

### Version

```prose
go version
go version go1.20.1 darwin/amd64
```

**Comment by ericvn** [comment]
I have no issues building Istio on my Mac. Looking at your message, it seems like you are trying to build the proxy in istio/proxy?

**Comment by ericvn** [comment]
Actually, pulling the latest Istio commit, I do have a build error on my Mac:
```
github.com/containernetworking/plugins/pkg/ns: build constraints exclude all Go files in /go/pkg/mod/github.com/containernetworking/plugins@v1.2.0/pkg/ns
```

**Comment by keithmattix** [comment]
This may be related to #43578. There's some Linux-only stuff in the CNI code now. I'm getting build errors in my IDE now as well

**Comment by bleggett** [comment]
The linux-only stuff was always there, but we included do-nothing stubs that would get built on non-Linux platforms, which would allow macOS builds.

Those builds (at least the CNI) would be functionally useless if you built them on macOS as a result, but it wouldn't error out.

**Comment by bleggett** [comment]
Whichever one broke it, the right fix is to not build the CNI plugin at all non-Linux - it has always been Linux specific and should not be built on macOS.

**Comment by ericvn** [comment]
@bleggett I see you assigned this one to yourself. I was going to add a stub for the redirection-server.go change, but If you want to get this working, I will. let you.

**Comment by bleggett** [comment]
@ericvn yeah sorry - grabbed this because I removed the stubs and we had this discuss in https://github.com/istio/istio/pull/43578 - so it's my problem :D

**Comment by TiwariAjay123** [comment]
Ok Thanks Folks. So the way I see it I should try building in container by following: (make shell/BUILD_WITH_CONTAINER=1 make build). till the time the issue is fixed. I will wait for do-nothing stub fix.
