### ISSUE TITLE
Pod updates do not impact EndpointShardz

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43694]
EndpointShards includes info from pods, but is not updated on pod change. For the most part ,this is ok... most of the fields are immutable anyways. However, labels can change. If a pod dynamically changes its labels, it is NOT seen in the EndpointShardz, which may impact DR subsetting

fyi @ramaraochavali @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
This is because we do not support label updates originally. Later I added labels update for proxy, this is to do that for endpoints. 

I think it is a little similar as waypoint update

**Comment by ramaraochavali** [comment]
Is pod dynamic label update a common use case - I am not saying we should not fix this, but just asking

**Comment by hzxuzhonghu** [comment]
It can be updated by CI/CD, not very rare.

**Comment by hanxiaop** [comment]
not stale

**Comment by hzxuzhonghu** [comment]
cc @dddddai this issue is just  what you asked

**Comment by howardjohn** [comment]
This impacts ambient fairly severely. A pod can dynamically be added or removed from ambient, which requires us to switch the endpoint to enable or disable HBONE

**Comment by howardjohn** [comment]
I had a fix in https://github.com/istio/istio/pull/50323/files#diff-aad0a6de97a6c10ad212a2089a5b9f2abae57a8b2e5f6d0ee2c8761d1fec61ccR56, but I think its not quite right. The fix should not be scoped to ambient ideally.

**Comment by hzxuzhonghu** [comment]
There is not a very perfect way to do this imo. For a proxy, it constructs metata with its lables. This is really a static ones, but later a user can change that label. Now we donot support update the labels to proxy.  This will greatly increase pilot load even if do that for pure endpoints
