### ISSUE TITLE
What are the advantages and disadvantages between ambient mesh and sidecar mode？

### ISSUE THREAD

**Issue by jkhe-hub** [istio/istio#43708]
Ambient mesh is a very good architecture. What trade-offs did the development team make between the sidecar mode and ambient mesh? Why didn't istio initially use the ambient mesh architecture but use the sidecar mode?

**Affected product area (please put an X in all that apply)**

[X] Ambient
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
please check out the blog: https://istio.io/latest/blog/2022/introducing-ambient-mesh/
