### ISSUE TITLE
Why doesn't istio support query parameter prefix matching for route?

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#43710]
In fact, envoy supports query parameter prefix matching for route. 
Should we add this feature into istio VirtualService?
![image](https://user-images.githubusercontent.com/33012260/222323654-91a7ed58-f670-4cc0-932f-7b88a4937372.png)

I'm glad to open a pr to implement it if this proposal is agreed.
cc @howardjohn @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I am ok to support query param prefix match as headers
