### ISSUE TITLE
Istio integration tests have istio-system namespace hardcoded. 

### ISSUE THREAD

**Issue by nshankar13** [istio/istio#43717]
### Bug Description

Some tests in `./tests/integration` in the Istio repo assume that Istio control plane components have been installed in the `istio-system` namespace. For instance, `routing.go` and `ingress_test.go` create gateway resources with the namespace set to `istio-system`, and the `webhook_test` appends `-istio-system` to the validating webhook name. 

The tests should use the SystemNamespace variable with the istioNamespace passed in as a CLI flag, and use this throughout the tests when validating or creating resources. 

### Version

```prose
1.17.0 and above.
```

**Comment by keithmattix** [comment]
@linsun @howardjohn tagging you two for context based on the [git blame](https://github.com/istio/istio/blame/643ad650ffde9c104e7ec009f4cf0d592fce666d/pkg/test/framework/components/istio/flags.go#L23) and associated PRs. Is there a reason the SystemNamespace integration test flag is deprecated? Seems like that flag would be an appropriate fix for this issue

**Comment by howardjohn** [comment]
I think there was an IstioNamespace: https://github.com/istio/istio/commit/ec8795e9149ac64c24fb7c6aa30604b524ac3629#diff-d7056021981aac5e200da79f489587f44c6743620cc5e8b793558fd99914729eR116-R117 that was preferred. This was back before istiod, when we had like 8 namespaces for the 8 components, so  single "system namespace" was deprecated; there wasn't one single namespace.

**Comment by keithmattix** [comment]
Gotcha...so can we un-deprecate that flag and wire it up in tests? Or should we explore a different direction? We'd love to be able to use the existing test suite instead of basically rewriting it all
