### ISSUE TITLE
istio1.17.1 generate istio-token using kube-root-ca.crt  not istio-ca-root-cert causing multicluster can not communicate

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#43716]
### Bug Description

istio1.17.1 generate istio-token using kube-root-ca.crt  not istio-ca-root-cert causing multicluster can not communicate

![image](https://user-images.githubusercontent.com/31508490/222438760-fbbdcbe1-a9f2-4f12-9e0a-0f88f6f288ac.png)
![image](https://user-images.githubusercontent.com/31508490/222438829-2bb24b02-b1a3-4b54-b0e8-d14cfee80638.png)

I compared the token from test sa to istio sa，the istio-token kid is the same，this show，it is from kube-root-ca.crt

### Version

```prose
istio 1.17.1
k8s 1.26.1
```

**Comment by howardjohn** [comment]
I am notsure I understand. Tokens do not use CA certs  for generation

what components are failing?

Please give more info

**Comment by 13567436138** [comment]
Istio-token kid need ca

**Comment by 13567436138** [comment]
sidecar authenticate fail

**Comment by 13567436138** [comment]
maybe this is because of k8s 1.26.1

**Comment by johnma14** [comment]
@istio/wg-security-maintainers can you take a look at this as well. Thanks.

**Comment by lei-tang** [comment]
cc @aryan16

**Comment by Stono** [comment]
Hello, i don't know if it helps or not but I'm on kubernetes `1.24.9` with istio `1.17.1` and my tokens look OK?

<img width="590" alt="Screenshot 2023-03-08 at 15 00 34" src="https://user-images.githubusercontent.com/1486729/223748349-087e2b8e-5068-4250-9db9-85e5e47a713c.png">

This is from the account token in the workload namespace

**Comment by 13567436138** [comment]
@lei-tang can anybody take a look at this?

**Comment by liwenhao0810** [comment]
Don't have context on this, @shankgan might have some insights.

**Comment by jaellio** [comment]
I'll work on reproing this and share the steps here.

**Comment by 13567436138** [comment]
thanks

**Comment by jaellio** [comment]
@13567436138 I have a few questions:
1. Have you been able to replicate this error in previous Istio releases?
2. Did the same cluster configuration work with previous versions of Istio? 
3. Can you expand on what you mean by "generate istio-token"? 

Thanks!

**Comment by 13567436138** [comment]
I tried istio 1.13.3 also cert problem.I think this is k8s problem ,not istio problem.

I am not sure ,if this important:
```
✘ Istiod encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
  Processing resources for Egress gateways, Ingress gateways.                                                                                                                      2023-03-16T09:18:45.532430Z	error	installer	failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
2023-03-16T09:18:48.042441Z	error	installer	failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-egressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
✘ Egress gateways encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-egressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
- Pruning removed resources                                                                                                                                                        2023-03-16T09:19:00.826071Z	warn	installer	retrieving resources to prune type autoscaling/v2beta1, Kind=HorizontalPodAutoscaler: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1" not found
2023-03-16T09:19:01.541220Z	warn	installer	retrieving resources to prune type policy/v1beta1, Kind=PodDisruptionBudget: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1" not found

```

**Comment by jaellio** [comment]
From a quick glance, this issue might be related: https://github.com/istio/istio/issues/42423. Seeing the same error for the PodDistributionBudget.

**Comment by 13567436138** [comment]
the error is from 1.13.3,my k8s is 1.26.1
the logs said cert problem,can not authenticated

**Comment by 13567436138** [comment]
@johnma14 what is istio ca role play in istio token generation

**Comment by 13567436138** [comment]
@jaellio

**Comment by 13567436138** [comment]
desc = request authenticate failure
2023-03-20T16:40:41.828245Z	warn	sds	failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure
2023-03-20T16:40:51.879091Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
2023-03-20T16:40:51.935677Z	warn	xdsproxy	upstream [9] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
2023-03-20T16:40:51.952324Z	warning	envoy config external/envoy/source/common/config/grpc_stream.h:163	StreamAggregatedResources gRPC config stream to xds-grpc closed: 16, authentication failure	thread=14
2023-03-20T16:40:52.423288Z	warn	sds	failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure

**Comment by 13567436138** [comment]
henticator KubeJWTAuthenticator: could not get cluster cluster2's kube client
2023-03-20T16:47:58.125016Z	error	ads	Failed to authenticate client from 10.1.1.178:47740: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client
2023-03-20T16:47:58.573425Z	error	ads	Failed to authenticate client from 10.1.1.178:47744: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client

**Comment by jaellio** [comment]
> @13567436138 I have a few questions:
> 
> 1. Have you been able to replicate this error in a previous Istio releases?
> 2. Did the same cluster configuration work with previous versions of Istio?
> 3. Can you expand on what you mean by "generate istio-token"?
> 4. How many control planes do you have?
> 5. Can you describe your configuration?
> 6. Are your clusters in the same network?
> 
> Thanks!

@13567436138 I need more context to resolve or replicate this issue. Can you answer the unanswered questions from the quoted text above?

1. Are the above logs from the ingressgateway? Are they the envoy logs from a data plane application?

These two issues might be related to the errors you are encountering here:
- https://github.com/istio/istio/issues/38258
- https://github.com/istio/istio/issues/42144

**Comment by 13567436138** [comment]
istioctl x create-remote-secret \
    --kubeconfig /root/.kube/159config \
    --name=cluster2 | \
    kubectl apply -f - --kubeconfig /root/.kube/147config

**Comment by 13567436138** [comment]
after add this it's ok
