### ISSUE TITLE
telemetry: per request opt-out

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43730]
As part of ambient, it was raised that Waypoints and Server Sidecars may report duplicate telemetry for the same request. To avoid this, we need a mechanism to opt-out telemetry per request. This could be used, for example, to also de-duplicate source and destination telemetry and cut on telemetry costs.

This has some downstream project ramifications if there is an expectation of complete telemetry from Istio.

**Comment by jshaughn** [comment]
This is still important imo, don't close it policy-bot.

**Comment by howardjohn** [comment]
Based on the recent changes to waypoint telemetry, is this still needed?
