### ISSUE TITLE
override istio metrics for a group of metrics

### ISSUE THREAD

**Issue by zhangbo1882** [istio/istio#43745]
There are several istio metrics. 
My requirement is that for metrics istio_requests_total, I want to keep tag response_code, remove tag response_flags.
For other metrics, I want to remove the tag  both response_code and response_flags.
It seems that there is no easy way to achieve that except I configure it for each metrics one by one.
Is it possilbe to enhance the field name from string to a string list so that we can easily define a override operation for a group of metrics instead of one metrics.
```
message MetricConfig {
  // (Optional) Collection of tag names and tag expressions to include in the
  // metric. Conflicts are resolved by the tag name by overriding previously
  // supplied values.
  map<string, string> dimensions = 1;

  // (Optional) Metric name to restrict the override to a metric. If not
  // specified, applies to all.
  string name = 2;

  // (Optional) A list of tags to remove.
  repeated string tags_to_remove = 3;

  // NOT IMPLEMENTED. (Optional) Conditional enabling the override.
  string match = 4;
}
```

**Comment by zhangbo1882** [comment]
@zirain do you think is it resonable to add the enhance ? If yes, I can help create a PR.

**Comment by zirain** [comment]
IMHO, it's not a good idea, if you want to change `MetricConfig`. It's a user face API, but we can do something on Telemetry API.
