### ISSUE TITLE
use standard Envoy interval reporting for telemetry

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#43763]
Envoy has added a standard `access_log_flush_interval` feature to access logs. We should remove custom Istio code duplicating this feature and switch to the upstream way - this will help eventual transition to the standard OTLP and telemetry sinks.

A possible issue is that TCP stats sets it to 15s, but the envoy option applies to all sinks at the same time.

**Comment by kyessenov** [comment]
cc @zirain @lei-tang

**Comment by Kaushal28** [comment]
@kyessenov, I would like to contribute here, could you please provide me with some more details if you have or any entry point in Istio code from where I can start?

**Comment by zengyuxing007** [comment]
buffer_flush_interval ?  this parameter should probably be placed under the Provider associated with the log

**Comment by zirain** [comment]
@kyessenov do you means `access_log_flush_interval` on [TcpProxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto.html)

**Comment by kyessenov** [comment]
@zirain Yeah, and there is another one for HTTP after https://github.com/envoyproxy/envoy/pull/25824. I think it's better than having our stats filters doing the same thing.

**Comment by zirain** [comment]
are you talking about promte [tcp_reporting_duration](https://github.com/istio/proxy/blob/1aed48c51a1daba7af03a25da22b1e5764b44866/source/extensions/filters/http/istio_stats/config.proto#L104) to upstream and resue it?

**Comment by kyessenov** [comment]
We don't need to implement upstream - it's done by others. We should align our APIs to upstream better - so that the reporting duration is consistent across all sinks. E.g. the same reporting duration knos applies for OTel, stats, etc.

**Comment by zirain** [comment]
make senses

**Comment by kyessenov** [comment]
This is future looking, for Otel.
