### ISSUE TITLE
 *v1.Deployment: deployments.apps is forbidden: User \"system:serviceaccount:istio-system:istiod\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope

### ISSUE THREAD

**Issue by eyltl** [istio/istio#43772]
kuberenties version 1.23
istio version 1.16.3 , installed by Helm.
i can see the following error logs on istiod pod
{"level":"error","time":"2023-03-05T16:33:05.966311Z","scope":"klog","msg":"k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User \"system:serviceaccount:istio-system:istiod\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"}

PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER is set to 'False'
based on the following: the permissions will not be created if "PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER" set to false. 
https://github.com/istio/istio/blob/e2cbf58dfc649fe21bc414b76405ac246ed40d73/manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml#L123

it well understood why i am getting forbidden, but why its trying ? its should be like this?
no issues, everything works as expected, trying to understand if the error log.

**Comment by howardjohn** [comment]
Can you give more info? I installed with `--set values.pilot.env.PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER=false` and it worked fine.

**Comment by eyltl** [comment]
The chart and the images were upgraded from 1.12.8 
The errors are in the logs of istiod
Not understand why its trying to lis deployments if PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER was set to false

**Comment by howardjohn** [comment]
Can you explain how you installed?

**Comment by eyltl** [comment]
@howardjohn did u had the chance to check it?
i was try to uninstall and reinstall once again. and the error still ON.

**Comment by eyltl** [comment]
thanks,
i was able reproduce it, when enableAnalysis is set to true, i am getting the permission error

can you try to add 
istiod:
  enableAnalysis: true

**Comment by howardjohn** [comment]
Ah that would explain it.

Although you should have the `istiod-gateway-controll` clusterrole created that allows that, unless you explicitly turned it off with PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER=false

**Comment by eyltl** [comment]
yes, i am using PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER=false
