### ISSUE TITLE
Cannot Establish RMI connection between services in istio

### ISSUE THREAD

**Issue by Omar-El** [istio/istio#43827]
i have a kubernetes cluster where istio is deployed with a bunch of services, but i can't seem to establish a communication between two particular pods using RMI protocol, both pods have an istio sidecar injected.

`apiVersion: v1`
`kind: Service`
`metadata:`
  `name: service-1`
  `namespace: test`
`spec:`
  `ports:`
  `- name: rmi-port`
    `port: 10022`
    `targetPort: 10022`
    `appProtocol: tcp`
  `selector:`
  `  app: svc-1`
  `type: ClusterIP`

`apiVersion: v1`
`kind: Service`
`metadata:`
  `name: service-2`
  `namespace: test`
`spec:`
  `ports:`
  `- name: rmi-port`
    `port: 10021`
    `targetPort: 10021`
     `appProtocol: tcp`
  `selector:`
  `  app: svc-2`
  `type: ClusterIP`

in this example service-2 is the initiator of the request and tries to connect to service-1 on port 10022, but i always get the following error :

`java.net.SocketException: Connection reset - java.rmi.ConnectIOException : error during JRMP connection establishment`

it should be mentioned that the communication occurs if i tried to remove the envoy proxy from the pod starting the request. i also noticed that the envoy proxy logs generate "BlackHoleCluster" whenever i make the rmi request to service-1

![image](https://user-images.githubusercontent.com/37773673/223734151-5d86789b-8513-4a02-8bc0-01e16322631e.png)

**Version**
istio 1.14.3

**Comment by Omar-El** [comment]
any news about this issue please ?

**Comment by zirain** [comment]
can you share the output of `istioctl bug-report` if possible?
