### ISSUE TITLE
how to install istio egress gateway with helm chart

### ISSUE THREAD

**Issue by aparnavodapalli** [istio/istio#43826]
We have installed istio with helm chart from. https://istio-release.storage.googleapis.com/charts.
There is no description, how to install egress gateway with Helm in istio documentation. It has documentation to install egress gateway only with IstioOperator and with istioctl.
Can you please help?

**Comment by zirain** [comment]
can you try with https://istio.io/latest/docs/setup/additional-setup/gateway/?

**Comment by howardjohn** [comment]
it is described here https://artifacthub.io/packages/helm/istio-official/gateway

An egress gateway is no different than ingres except you *probably*don't want a LoadBalancer

**Comment by JWebDev** [comment]
Hi. I have the same question. I've been googling for a few hours now and came across this question. If someone is reading, can you please help organize the information?

I only need the Egress Gateway.

The documentation here describes that you can install it through the operator and using the command line.
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/
Is it impossible to install the egress gateway with helm? The installation assumes that the operator is used, although other parts of the documentation say not to use the operator as it is deprecated.

1. I found this chart and as far as I understood from what I read, is it both ingress and egress in one chart? https://artifacthub.io/packages/helm/istio-official/gateway

2. All documentation regarding egress states that search for egress-gateway under this way `kubectl get pod -l istio=egressgateway -n istio-system`. But after installing the chart above, there is only gateway one pod.

3. In this chart https://artifactthub.io/packages/helm/istio-official/gateway almost nothing is said about egress. Only one line. And this is total unclear.

4. Very incomprehensible documentation, especially for how to install it all. Mixed with outdated documentation.

5. So, how can I install egress-gateway in Kubernetes with Helm? I still haven't figured it out. Only with `istioctl`?

Thanks

**Comment by holotrack** [comment]
@howardjohn sorry but still can not figure out how to install it with helm chart. When I add additional "service" field in values.yaml this want to chan ge my ingress gateway config to clusterip not to create additional gateway egress and I need both of them. Can you more detailed explain how to handle it?
