### ISSUE TITLE
Client generated X-Request-Id will not be used with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by Crazyigor1987** [istio/istio#43833]
### Bug Description

We use externalTrafficPolicy: Local on the Ingress Service on our Istio to pass the external IP address to the applications and thus also operate IP address-based authorisation policies.  But now we have noticed that this setting overwrites the X-Request-ID what the client sends us. Here is an example of what I mean:

**externalTrafficPolicy: Local**

test@test:~# curl "https://istio.test.de/test.php" -H "x-request-id: _a8919b1a-aab6-4d87-a18f-b83d8a3119b4_"
host: istio.test.de
user-agent: curl/7.68.0
accept: */*
x-request-id: _d5c1471c-dd94-42d7-9ae4-b2a0a8b19cfe_
x-forwarded-for: 88.99.21.21
x-forwarded-proto: https
x-envoy-external-address: 88.99.21.21
x-envoy-attempt-count: 1
x-forwarded-client-cert: By=spiffe://cluster.local/ns/test/sa/default;Hash=4ece64dec47cb89505335f236a17de9943509f64b8f6191155c4929f3467a8bd;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
x-b3-traceid: 2919d6ba729ab5a5807bd8d52797268e
x-b3-spanid: ec9bd2de7a438719
x-b3-parentspanid: 807bd8d52797268e
x-b3-sampled: 0

**externalTrafficPolicy: Cluster**

test@test:~# curl "https://istio.test.de/test.php" -H "x-request-id: _a8919b1a-aab6-4d87-a18f-b83d8a3119b4_"
host: istio.test.de
user-agent: curl/7.68.0
accept: */*
x-request-id: _a8919b1a-aab6-4d87-a18f-b83d8a3119b4_
x-forwarded-for: 10.224.0.8
x-forwarded-proto: https
x-envoy-attempt-count: 1
x-envoy-internal: true
x-forwarded-client-cert: By=spiffe://cluster.local/ns/test/sa/default;Hash=4ece64dec47cb89505335f236a17de9943509f64b8f6191155c4929f3467a8bd;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
x-b3-traceid: 204a4a7161736f9c4461e8671b2dae0d
x-b3-spanid: 0afb935d29288547
x-b3-parentspanid: 4461e8671b2dae0d
x-b3-sampled: 0

### Version

```prose
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (144 proxies)

kubectl version --short
Client Version: v1.20.7
Server Version: v1.25.5
```

**Comment by hanxiaop** [comment]
IIRC this is the known behavior. If you use `externalTrafficPolicy: Local`, the `x-request-id` will be overwritten.

**Comment by hanxiaop** [comment]
FYI: https://github.com/istio/istio/issues/10875

**Comment by Crazyigor1987** [comment]
Thanks @hanxiaop 
The setup with an envoyfilter in your linked issue looks like a workaround instead of a bugfix. I'll leave this issue open.

**Comment by zirain** [comment]
duplicate with https://github.com/istio/istio/issues/10875
