### ISSUE TITLE
ServiceEntry deletion - endpoints are not getting updated when multiple service entries with same hostname are present

### ISSUE THREAD

**Issue by ivpr** [istio/istio#43853]
### Bug Description

When multiple service entries are created with same hostname, on deletion of 1 service entry, the corresponding endpoints of the deleted service entry are not getting removed.

**Steps to reproduce**
Create SE1
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-10-47-1-179
spec:
  addresses:
    - 10.47.1.179
  endpoints:
    - address: 10.47.1.179
      ports:
        tcp-80: 80
  hosts:
    - test123
  location: MESH_EXTERNAL
  ports:
    - name: tcp-80
      number: 80
      protocol: http
  resolution: STATIC 
```
Create SE2 with same hostname
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-10-83-48-10    
spec:
  addresses:
    - 10.83.48.10
  endpoints:
    - address: 10.83.48.10
      ports:
        tcp-80: 80
  hosts:
    - test123
  location: MESH_EXTERNAL
  ports:
    - name: tcp-80
      number: 80
      protocol: http
  resolution: STATIC 
```
Check endpoints
```
$ istioctl pc endpoints sleep-77ffc8f959-cfvjb --cluster "outbound|80||test123"
ENDPOINT           STATUS      OUTLIER CHECK     CLUSTER
10.47.1.179:80     HEALTHY     OK                outbound|80||test123
10.83.48.10:80     HEALTHY     OK                outbound|80||test123
```
Delete SE1
```
$ k delete se egress-10-47-1-179 
```
Check endpoints where the old IP 10.47.1.179 is still present even after deletion of corresponding service entry
```
$ istioctl pc endpoints sleep-77ffc8f959-cfvjb --cluster "outbound|80||test123"
ENDPOINT           STATUS      OUTLIER CHECK     CLUSTER
10.47.1.179:80     HEALTHY     OK                outbound|80||test123
10.83.48.10:80     HEALTHY     OK                outbound|80||test123 
```

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.15.3
data plane version: 1.15.3
```

### Additional Information

Based on the code, the issue is present in the current master as well. 
Relevant previous code fix which solve for deletion of endpoints only if all service entries are deleted for the same hostname - https://github.com/istio/istio/pull/37994

**Comment by ivpr** [comment]
@hzxuzhonghu Can you please have a look since you may the context on this issue.

**Comment by hzxuzhonghu** [comment]
sure

**Comment by GregHanson** [comment]
`resolution: STATIC ` means the endpoints are going to be listed in the XDS Cluster object instead of EDS, so it sounds like a CDS push isn't getting triggered on the ServiceEntry delete
