### ISSUE TITLE
TestKeyCertBundleRotator failed racetest

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4385]
Run racetest failure. 

go test -v -run TestKeyCertBundleRotator ./security/pkg/caclient/... -race

=== RUN   TestKeyCertBundleRotator
2018-03-20T05:49:10.665500Z     info    Will rotate key and cert in 300ms.
2018-03-20T05:49:10.967753Z     info    Retrieve new key and certs.
2018-03-20T05:49:10.967879Z     info    Successfully retrieved new key and certs.
2018-03-20T05:49:10.967974Z     info    Will rotate key and cert in 300ms.
==================
WARNING: DATA RACE
Read at 0x00c42011a220 by goroutine 6:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).GetAllPem()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:35 +0x40
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:134 +0x1d44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42011a220 by goroutine 7:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).VerifyAndSetAll()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:51 +0xa8
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:87 +0x325

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 7 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c42011a240 by goroutine 6:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).GetAllPem()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:35 +0x52
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:134 +0x1d44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42011a240 by goroutine 7:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).VerifyAndSetAll()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:52 +0xeb
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:87 +0x325

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 7 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c42011a258 by goroutine 6:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).GetAllPem()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:35 +0x64
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:134 +0x1d44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42011a258 by goroutine 7:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).VerifyAndSetAll()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:53 +0x134
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:87 +0x325

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 7 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c42011a200 by goroutine 6:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).GetAllPem()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:35 +0x75
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:134 +0x1d44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42011a200 by goroutine 7:
  istio.io/istio/security/pkg/pki/util/mock.(*FakeKeyCertBundle).VerifyAndSetAll()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/pki/util/mock/fakekeycertbundle.go:50 +0x66
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:87 +0x325

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 7 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
2018-03-20T05:49:11.167536Z     info    Retrieve new key and certs.
2018-03-20T05:49:11.167629Z     info    Successfully retrieved new key and certs.
2018-03-20T05:49:11.167721Z     info    Will rotate key and cert in 300ms.
2018-03-20T05:49:11.472994Z     info    Retrieve new key and certs.
2018-03-20T05:49:11.473159Z     info    Successfully retrieved new key and certs.
2018-03-20T05:49:11.473232Z     info    Will rotate key and cert in 300ms.
2018-03-20T05:49:11.672479Z     info    Will rotate key and cert in 1h0m0s.
==================
WARNING: DATA RACE
Read at 0x00c420060338 by goroutine 6:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Stop()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:98 +0x48
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:132 +0x1d2a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c420060338 by goroutine 10:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:61 +0x8a

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 10 (running) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
2018-03-20T05:49:12.176306Z     info    Will rotate key and cert in 0s.
2018-03-20T05:49:12.176389Z     info    Retrieve new key and certs.
==================
WARNING: DATA RACE
Read at 0x00c42021c0f8 by goroutine 6:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Stop()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:98 +0x48
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:132 +0x1d2a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42021c0f8 by goroutine 11:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:83 +0x53f

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 11 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
2018-03-20T05:49:12.176864Z     info    Will rotate key and cert in 0s.
2018-03-20T05:49:12.176922Z     info    Retrieve new key and certs.
==================
WARNING: DATA RACE
Read at 0x00c42021c1b8 by goroutine 6:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Stop()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:98 +0x48
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:132 +0x1d2a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c

Previous write at 0x00c42021c1b8 by goroutine 12:
  istio.io/istio/security/pkg/caclient.(*keyCertBundleRotatorImpl).Start()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator.go:89 +0x418

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:921 +0x206
  main.main()
      istio.io/istio/security/pkg/caclient/_test/_testmain.go:46 +0x1d3

Goroutine 12 (finished) created at:
  istio.io/istio/security/pkg/caclient.TestKeyCertBundleRotator()
      /Users/xiaolan/go/src/istio.io/istio/security/pkg/caclient/keycertbundlerotator_test.go:119 +0x1c09
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
--- FAIL: TestKeyCertBundleRotator (1.51s)
        testing.go:699: race detected during execution of test
FAIL
FAIL    istio.io/istio/security/pkg/caclient    1.599s
testing: warning: no tests to run
PASS
ok      istio.io/istio/security/pkg/caclient/grpc       1.097s [no tests to run]
?       istio.io/istio/security/pkg/caclient/grpc/mock  [no test files]
?       istio.io/istio/security/pkg/caclient/mock       [no test files]

**Comment by myidpt** [comment]
Thanks for the report. This is useful test result. I will take a look.

**Comment by xiaolanz** [comment]
blocking #4235
