### ISSUE TITLE
Automatic sidecar injection get ignored, it get self removed from namespace.

### ISSUE THREAD

**Issue by vyom-soft** [istio/istio#43861]
### Bug Description

After doing installation via Helm, istio v 1.17.1

I see 
`2023-03-09T13:23:40.224184Z	info	Sidecar injection request for my-dev/dev-be-api-process-55bf56977b-***** (actual name not yet known).`

The istio sidecar injection is not working. I am not sure whether Helm installation is doing all correct. 
I am on bare metal Kubespray K8 cluster v 1.24.6

### Version

```prose
1.17.1
```

### Additional Information
```
After enabling the automatic sidecar injection on custom namespace, it vanishes itself after some minutes.

➜  ~ kubectl -n istio-system exec istiod-584b74f7f9-bx5mz -- curl 'localhost:8080/debug/config_dump?proxyID=POD_NAME.POD_NAMESPACE'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Proxy not connected to this Pilot instance. It may be connected to another instance.
100    85  100    85    0     0   145k      0 --:--:-- --:--:-- --:--:-- 85000
```
[istiod.log](https://github.com/istio/istio/files/10934775/istiod.log)

[meshconfig.log](https://github.com/istio/istio/files/10934790/meshconfig.log)

**Comment by howardjohn** [comment]
"name not known yet" is not an issue, that is just how Kubernetes works. Its not clear what is "not working" here?

**Comment by vyom-soft** [comment]
> > "name not known yet" is not an issue, that is just how Kubernetes works. Its not clear what is "not working" here?
> 
> Thank you. I have updated the issue, When Istio is installed and sidecar is enabled. (The injection)It self vanishes from the respective namespace. The sidecar is enabled only default namespace, for other namespace it removes itself. Any direction where should I look for this behaviour.

The problem is that if the Namespce is created with FluxCD which was in my case.  The sidecar injection get removed by FluxCD automatically ?.  So I removed the Namespace creation from it. Now the sidecar enable stays on the namespace.

**Comment by vyom-soft** [comment]
Bur now I see another issue
status:
  conditions:
    - lastTransitionTime: '2023-03-10T10:15:06Z'
      message: >-
        Internal error occurred: failed calling webhook
        "namespace.sidecar-injector.istio.io": failed to call webhook: Post
        "https://istiod.istio-system.svc:443/inject?timeout=10s": context
        deadline exceeded
      reason: FailedCreate
      status: 'True'
      type: ReplicaFailure
  observedGeneration: 1
  replicas: 0

**Comment by vyom-soft** [comment]
I am closing this.

**Comment by vyom-soft** [comment]
In the Istio documentation it must be stated that sidecar injection if should be take care of. If the Namespace creation is automated. Example via FluxCD.  Because it is **declarative** creation of Namespace & not **imperative**. Hence the injection is wiped off by Fluxcd.
