### ISSUE TITLE
Ambient ebpf redirection with calico cni not working via ingress gateway

### ISSUE THREAD

**Issue by AndreaM12345** [istio/istio#43871]
### Bug Description

Used these instructions https://github.com/istio/istio/tree/master/cni/pkg/ebpf to test out the user of ebpf redirection as a way to avoid the iptable configuration done by calico cni that would cause ambient mesh not to work on a cluster that uses calico cni.  

Using the standard calico cni that is iptables based.

Brought on the cluster and installed istio using the 1.18.0-alpha.0 tag but made adjustments to enable ebpf by modifying the ambient profile so that it looks like

```
  values:
    pilot:
      env:
        # Setup more secure default that is off in 'default' only for backwards compatibility
        VERIFY_CERTIFICATE_AT_CLIENT: "true"
        ENABLE_AUTO_SNI: "true"

        PILOT_ENABLE_HBONE: "true"
        CA_TRUSTED_NODE_ACCOUNTS: "istio-system/ztunnel,kube-system/ztunnel"
        PILOT_ENABLE_AMBIENT_CONTROLLERS: "true"
    cni:
      logLevel: info
      privileged: true
      ambient:
        enabled: true
        redirectMode: "ebpf"
```
Ran the debug steps mentioned in https://github.com/istio/istio/tree/master/cni/pkg/ebpf  and saw correct behavior

To test followed the tests suggested in https://istio.io/latest/blog/2022/get-started-ambient/

I saw that before adding the default namespace to the ambient mesh everything was good.  After adding the default namespace to the ambient mesh I saw that while the following curls within the mesh worked
```
$ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1
<!DOCTYPE html>
$ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/ | head -n1
<!DOCTYPE html>
```

Curl through the ingress gateway failed.
```
$ kubectl exec deploy/sleep -- curl -s http://istio-ingressgateway.istio-system/productpage | head -n1
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 22
```

Any thoughts on what might be happening?

### Version

```prose
istioctl version
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (4 proxies)


kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.6+IKS
```

### Additional Information

istioctl bug-report

Target cluster context: istio-ambient1
Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-03-09 17:03:02.628166 -0600 CST

Cluster endpoint: xxxxx
CLI version:
version.BuildInfo{Version:"1.18.0-alpha.0", GitRevision:"05c3497f08ff7d9a34527582bb7ccc1fd1f029c8", GolangVersion:"go1.20.1", BuildStatus:"Clean", GitTag:"1.18.0-alpha.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.18.0-alpha.0", GitRevision:"05c3497f08ff7d9a34527582bb7ccc1fd1f029c8", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.18.0-alpha.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.18.0-alpha.0}

Fetching proxy logs for the following containers:

default/details-v1/details-v1-5ffd6b64f7-pvbnt/details
default/notsleep/notsleep-6d6c8669b5-xcgm8/notsleep
default/productpage-v1/productpage-v1-8b588bf6d-2dqtn/productpage
default/ratings-v1/ratings-v1-5f9699cfdf-tqz88/ratings
default/reviews-v1/reviews-v1-569db879f5-h99fv/reviews
default/reviews-v2/reviews-v2-65c4dc6fdc-5fqsj/reviews
default/reviews-v3/reviews-v3-c9c4fb987-mr6vv/reviews
default/sleep/sleep-7b85956664-j5ddq/sleep
istio-system//istio-cni-node-6kfd2/install-cni
istio-system//istio-cni-node-9nv4c/install-cni
istio-system//istio-cni-node-qgdgn/install-cni
istio-system//ztunnel-m87lr/istio-proxy
istio-system//ztunnel-n22tn/istio-proxy
istio-system//ztunnel-z7kmn/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-cb4d6fd7-xwpjm/istio-proxy
istio-system/istiod/istiod-7596fdbb4c-cv2wl/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0108] (Pod default/details-v1-5ffd6b64f7-pvbnt) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/istio-cni-node-6kfd2) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/istio-cni-node-9nv4c) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/istio-cni-node-qgdgn) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/istiod-7596fdbb4c-cv2wl) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/notsleep-6d6c8669b5-xcgm8) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/productpage-v1-8b588bf6d-2dqtn) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/ratings-v1-5f9699cfdf-tqz88) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v1-569db879f5-h99fv) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v2-65c4dc6fdc-5fqsj) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/reviews-v3-c9c4fb987-mr6vv) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod default/sleep-7b85956664-j5ddq) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/ztunnel-m87lr) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/ztunnel-n22tn) Unknown annotation: ambient.istio.io/redirection
Warning [IST0108] (Pod istio-system/ztunnel-z7kmn) Unknown annotation: ambient.istio.io/redirection

Creating an archive at /Users/andreama/istio-1.17.1a/istio-1.18.0-alpha.0/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/gb/x5mjgl250pj1r_scbfbf88sm0000gp/T/bug-report.
Done.

**Comment by PlatformLC** [comment]
@AndreaM12345, pod to pod within the mesh is OK with ebpf+calico, but access to ingress gateway failed, am I right?

**Comment by irisdingbj** [comment]
> @AndreaM12345, pod to pod within the mesh is OK with ebpf+calico, but access to ingress gateway failed, am I right?

yes, this is the case

**Comment by PlatformLC** [comment]
Just tried in my local environment, it worked as expected. Any configuration missed, gateway or virtualservice?

**Comment by PlatformLC** [comment]
With offline debugging, we succeeded to make it work by correcting `<POD_CIDR>` mentioned in https://github.com/istio/istio/tree/master/cni/pkg/ebpf .
