### ISSUE TITLE
Improve istioctl analyze to help diagnose TLS certificate issues

### ISSUE THREAD

**Issue by SJrX** [istio/istio#43891]
I spent a few hours trying to debug why https wasn't working on a new istio deployment, it was actually quite subtle because I would just get a connection reset errors, and logging on the gateway didn't really tell me anything. I walked through a ton of guides, and bug reports, and tried tweaking logging but essentially I was doing the following:

1. Declaring a new gateway and istio-ingressgateway in a brand new namespace, called `home-assistant`
2. Had secrets declared in `home-assistant`.

Curl would give me:
```
curl: (35) Recv failure: Connection reset by peer
```

There were no warnings in `istioctl analyze` , and I followed all the troubleshooting steps including here: https://istio.io/latest/docs/ops/common-problems/network-issues/.

I don't remember exactly how I got there, but eventually I got to looking at the logs of `istiod` (I think) and eventually saw that the default service account in the namespace couldn't read the secret, and that it was being filtered.

Anyway some ways that istioctl analyze could help, might be the following:

1. If on any istio-gateway there is a secret in status `WARMING` or valid cert is false, it would be nice if istioctl analyze told me this was a problem. 
2. Maybe a harder ask (and would depend on permissions), logging, but for the Gateway, look at the ingress gateway that is being selected, and validate that the service account being used has permission to read it, that would be good.
   * Maybe that's too complicated, and that should just be a trouble shooting step here (https://istio.io/latest/docs/ops/common-problems/network-issues/#tls-configuration-mistakes 

[ ] Ambient
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
IMO analysis involves analyzing configurations to identify any incorrect Istio-related configurations that users may not be aware of. The scenario you described sounds more like debugging processes, which would be better suited for a debug session in the documentation.

**Comment by SJrX** [comment]
Sure, I don't feel too strongly either way. However I think that istioctl analyze will tell you if you have configured your gateway to use a credential that doesn't exist, and so it is still a configuration issue if you configure the gateway to use a credential that the ingress doesn't have access to.

**Comment by GregHanson** [comment]
> 1. If on any istio-gateway there is a secret in status WARMING or valid cert is false, it would be nice if istioctl analyze told me this was a problem.

@hanxiaop if `istioctl analyze` isn't picking up on this, it probably should

Going further, might be good if analyze also caught expired certs too, or potentially warning if exp is within a month

**Comment by hanxiaop** [comment]
> 

Yes I agree this is useful. I was not sure about checking the permissions of reading secrets.

**Comment by hanxiaop** [comment]
@SJrX 1.18.0 release is out. Can you try `istioctl analyze` to see if it helps?

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/43921
