### ISSUE TITLE
Identify requests coming from external meshes and enforce AuthorizationPolicies at Gateway level

### ISSUE THREAD

**Issue by mauro770** [istio/istio#43906]
# Objective
Identify requests coming from external meshes and enforce AuthorizationPolicies at Gateway level.
# Context
I'm currently investigating and doing my first tests with multiclusters deployments for the company I work for. Our scenario has a couple of constraints that condition the architecture to implement:
- High availability: We can't, by any means, risk to have issues because the istio-proxies running in one cluster cannot contact the istiod in another.
- Large scale: Our clusters run thousands of containers in hundreds of namespaces. Therefore, we must control the amount of unnecessary updates the proxies receive and the control-plane is listening for.
- Locality Load Balancing: Our clusters are not always geographically close, also, we already have lots of services deployed in the same namespace that are repeated among clusters. So, by default, the traffic that goes from service A to service B should always go to pods of service B running in the same cluster than service A, unless configured otherwise.
- Different networks: We've a hybrid cloud scenario and, although there are ways for the pods to see a unified network, a priori we cannot ensure there will be no repeated IPs between clusters.

Considering all those premises and a couple more, after reading lots of documentation, we resolved that the most suitable deployment model for our scenario would be a multimesh-multicluster-multinetwork deployment. Each kubernetes cluster will have its own istiod running and this will only be connected to the API server of its home cluster. Also, each cluster will have its own Istio Gateway to receive traffic from others.

<p align="center">
<img src="https://user-images.githubusercontent.com/17919402/224803833-194e6d39-7ba6-42fb-a0e2-3154b0002b06.jpeg" width="700"/>
</p>

# Requirement
One of the features we need to provide is the ability to recognize the source meshID of a request when this arrives to another mesh, in order to:
- Metrics correlation: Link the outgoing request in the source cluster with the incoming request in the destination cluster in our metrics.
- Access-Control: Enforce AuthorizationPolicies at the Gateway level in order to control which external mesh services are able to query a particular internal endpoint.

# Some ideas/thoughts
## Metrics correlation
For this, the main limitation is the fact that the Istio Gateway doesn't present metrics for incoming requests, only outgoing. Nevertheless, at least for this we can rely on the `request_id` header and maybe track it with tracing in the future. I also thought about configuring the Gateway entry as `PASSTHROUGH` instead of `ISTIO_MUTUAL` in order to check if that way I would see the `source_cluster` tag of the metric generated by the destination pod with the name of the actual source cluster but, I always see the destination cluster in that field (I assume the pod always see the Istio Gateway as the request source).
I also explored the possibility of using the `destination/source_principal` tags but the value in those is always `spiffe://cluster.local/ns/istio-ingress/sa/istio-ingress`. I think this is related to the `trustDomain` field hardcoded to `cluster.local` in the helm chart we use for deployment:
https://artifacthub.io/packages/helm/istio-official/istiod/1.15.2?modal=template&template=configmap.yaml
(I could override it but I'm not sure if that was on purpose).

## Access-Control
In regards to the enforcement of AuthorizationPolicies to allow/deny requests from external clusters, I don't see any metadata I could use in the policy to properly match with external requests of a particular mesh. So far, the only solutions we came-up to overcome this are:
- IP-based AuthorizationPolicies: It will work in general but doesn't scale much and they will be tied to the actual IP range each cluster is assigned (that might change in the future).
- Custom meshID header: We thought about enforcing a global configuration to stamp each request with a header containing the meshID value of the corresponding mesh and then use this header as match in AuthorizationPolicies. The problems I see with this are: 
    - We would be introducing a very custom configuration.
    - It is a parameter that can probably be overriden at the namespace level with an EnvoyFilter or VirtualService.

# Question
Do you have any idea about how to achieve these objectives apart from the options I mentioned?
I thank you in advance for any help/suggestion/idea you may have. Also, please, don't hesitate to ask me for more information if I'm missing some detail you consider important.

**Comment by keithmattix** [comment]
One small clarification on this point:

> the istio-proxies running in one cluster cannot contact the istiod in another.

The istio-proxies **do not** communicate with the istiods in other clusters. From the deployment models [docs](https://istio.io/latest/docs/ops/deployment/deployment-models/#endpoint-discovery-with-multiple-control-planes):

> To enable endpoint discovery for a cluster, an administrator generates a remote secret and deploys it to each primary cluster in the mesh. The remote secret contains credentials, granting access to the API server in the cluster. The control planes will then connect and discover the service endpoints for the cluster, enabling cross-cluster load balancing for these services.

With this in mind, it sounds like multicluster, single mesh may be a more appropriate topology for you?

**Comment by mauro770** [comment]
Thank you for your input @keithmattix . According to that same document, the istio-proxies [can communicate with an istiod running in another cluster](https://istio.io/latest/docs/ops/deployment/deployment-models/#control-plane-models) (primary/remote cluster). When I said:
> the istio-proxies running in one cluster cannot contact the istiod in another.

I was mainly referring to that possible configuration, which is not convenient for our use-case.

On the other hand, regarding the singlemesh-multicluster approach, there are 2 main drawbacks for us:
- That will merge the endpoints of services with the same name running under the same namespace in both cluster by default. This is not possible for us since deployments of the same app running in different clusters usually will not be able to attend the same request. Also, the clusters are not always close to each other, so some requests would have unnecessary delay.
- Our clusters are quite big, with thousands of services. An istiod consuming the information of services running in an external cluster will start consuming resources and injecting configurations into the proxies that are not necessary.

**Comment by Kavinraja-G** [comment]
Hi @mauro770 @keithmattix -- I was looking into the same setup for my use-case too. I have few questions:
1. How are you handing the automation for remote-secrets in all the controlplane clusters? Is there any Istio recommended way to do this? All I can see in docs is to use the `istioctl create-remote-secret` which uses the SA token
2. How to handle the root CAs? I hope you need to have the same root CA to be deployed in all the clusters to enable the communication. Can we able to make use cert-manager with this approach?

**Comment by mauro770** [comment]
@Kavinraja-G I'm not working on this anymore (I changed jobs). Sorry for not being of much help.
