### ISSUE TITLE
Not getting any grpc metrics in prometheus

### ISSUE THREAD

**Issue by a-candiotti-pvotal** [istio/istio#43908]
### Bug Description

Here is my topology:

   - a grpc service entry for a service 'A' outside the kubernetes cluster
   - an egress gateway that forwards traffic to it
   - a service 'B' that connect to this grpc service 'A' through the egress gateway and receives messages from it

Everything is working fine, communication wise, the execution works but I don’t see the istio_request_messages_total, istio_response_messages_total metrics in prometheus.

I can see in Kiali that the request are identified as grpc.
I can see requests (using istio_requests_total) going from the service and going to the egress gateway and then from the gateway to the external service in prometheus. They have a request_protocol set at "grpc".

The ports are all using proper protocol naming convention as far as I know.

### Version

```prose
istioctl version:

client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1
---

kubectl version --short:
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.24.10+k3s1

---
helm version --hort:
v3.11.1+g293b50c
```

### Additional Information

I can't provide the bug-report as it would give a lot of information on our internal architecture but i can procur detailed informations on demand.

**Comment by pre** [comment]
Could this be related to the port `15020` vs `15090` issue https://github.com/istio/istio/issues/39535 ?

In Pod annotations there's `prometheus.io/port: "15020"` but it only works for scraping from `localhost`. 
Only port `15090` is available from the outside of the Pod's localhost. 

I'm trying to understand why this is so - I have the same problem with scraping the metrics.

**Comment by a-candiotti-pvotal** [comment]
@pre I don't think so, most metrics are present.

The only one not present are istio_response_messages_total and istio_request_messages_total.

**Comment by zirain** [comment]
https://github.com/istio/proxy/pull/4547

**Comment by jaybhamad** [comment]
> Could this be related to the port `15020` vs `15090` issue #39535 ?
> 
> In Pod annotations there's `prometheus.io/port: "15020"` but it only works for scraping from `localhost`. Only port `15090` is available from the outside of the Pod's localhost.
> 
> I'm trying to understand why this is so - I have the same problem with scraping the metrics.
> 
> ie try `curl service-name:15020/stats/prometheus` vs. `curl localhost:15020/stats/prometheus` - only the latter works. However, same query will work to port `15090` both in localhost and from the outside of the Pod.
