### ISSUE TITLE
service entry tolerate unready endpoint

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#43909]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
k8s service has this publishNotReadyAddresses feature which allows an endpoint to be created even if the pod is not ready. can we support the same feature for service entry selecting pods?

**Describe alternatives you've considered**
no alternative

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by fantapsody** [comment]
Hi @yingzhuivy , has this feature been implemented? The issue was closed as completed but not linked to any PRs and I didn't find related configurations in the document.

**Comment by yingzhuivy** [comment]
> Hi @yingzhuivy , has this feature been implemented? The issue was closed as completed but not linked to any PRs and I didn't find related configurations in the document.

I don't think so. Please create another issue
