### ISSUE TITLE
Conflicted MutatingWebhookConfigration blocks non-revisioned istioctl upgrade

### ISSUE THREAD

**Issue by cnvergence** [istio/istio#43932]
### Bug Description

Failed `istioctl install` can result in a conflicted MutatingWebhookConfigration state when the installation of manifests will return an error, this only applies to the non-revisioned installation. This error will block every `istioctl install/upgrade`.
```bash
Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
```
Earlier this conflict did not happen, because the tagged webhook was removed before helm manifests installation every `istioctl install` execution, but it also caused sidecar injection downtime: https://github.com/istio/istio/issues/40134.

One idea for the fix could be to bring this back, but additionally, check if the default one is deactivated, before doing any removal. I will start draft PR.

Another would be to consider changing the default injector configuration in the istio-discovery Helm chart.
A related issue with the difference between webhook configurations - https://github.com/istio/istio/issues/42826.

**Steps to reproduce**

1. Run a clean Istio installation  with `istioctl install`
```bash
 kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io  
NAME                                            WEBHOOKS   AGE
istio-revision-tag-default                      4          10m
istio-sidecar-injector                          4          10m
```
istio-sidecar-injector should contain deactivated MutatingWebhookConfiguration.
```bash
...
  name: object.sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
...
```

3. Run Istio upgrade with a wrong configuration, e.g bad image name. `istioctl install -f fault-iop.yaml`
istio-sidecar-injector will be now updated, but is not deactivated
```bash
...
  name: object.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
...
```
4. Run Istio upgrade again with a correct configuration `istioctl install`.
Every istioctl install will now fail with a following message:
```bash
 Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

To restore the upgrade process, the user needs to manually delete the default tagged webhook.

### Version

```prose
istioctl-17 version
client version: 1.17.0
control plane version: 1.17.0
```

**Comment by lupindeterd** [comment]
hi,

Is there a workaround for this bug? What version did it start to appear? We're on v1.16.3 and  this appears on a new install. I can't do the workaround suggested by OP since we're running multiple meshes on different namespaces in a single cluster, so the first mesh seems to install fine but when the install runs on the second mesh/namespace it fails with ``Webhooks overlaps error`` due to a webhook that exist in the first mesh. We don't have this issue on v1.14.6.

**Comment by cnvergence** [comment]
hi @lupindeterd, It started to appear from 1.15
I wonder if you could use different tags for your different meshes within that cluster
https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels

**Comment by cnvergence** [comment]
Istioctl upgrade unblocked by this PR: 
https://github.com/istio/istio/pull/48147
