### ISSUE TITLE
Random infrequent URX/connection failures talking to external endpoints after adding proxy sidecars

### ISSUE THREAD

**Issue by nberkley-gp** [istio/istio#43938]
### Bug Description

We're in the process of rolling out sidecars to or existing clusters, and we're seeing a small single digit percentage of our requests to endpoints outside the mesh (via the Passthrough cluster) get connection errors for no discernible reason. Trace logs on an impacted pod show the connection just immediately close after it starts opening with no indication as to why.

These failures do not happen when the sidecar is not present, so it's definitely Istio/Envoy related.

### Version

```prose
➜  ~ istioctl version
client version: 1.17.1
control plane version: 1.15.0
data plane version: 1.15.0 (377 proxies)
➜  ~ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.24.9
```

### Additional Information

I can't feasibly do the redactions that would be necessary to post the bug-report output, so just collecting the relevant bits (happy to collected targeted data if I left out something):

- Analyze has no notes for the impacted namespaces.
- All the filter chains and such are default.
- Stats for the PassthroughCluster (Note that these seem to get replaced/reset every few seconds)
```
PassthroughCluster::observability_name::PassthroughCluster
PassthroughCluster::default_priority::max_connections::4294967295
PassthroughCluster::default_priority::max_pending_requests::4294967295
PassthroughCluster::default_priority::max_requests::4294967295
PassthroughCluster::default_priority::max_retries::4294967295
PassthroughCluster::high_priority::max_connections::1024
PassthroughCluster::high_priority::max_pending_requests::1024
PassthroughCluster::high_priority::max_requests::1024
PassthroughCluster::high_priority::max_retries::3
PassthroughCluster::added_via_api::true
PassthroughCluster::44.205.215.82:443::cx_active::0
PassthroughCluster::44.205.215.82:443::cx_connect_fail::1
PassthroughCluster::44.205.215.82:443::cx_total::78
PassthroughCluster::44.205.215.82:443::rq_active::0
PassthroughCluster::44.205.215.82:443::rq_error::0
PassthroughCluster::44.205.215.82:443::rq_success::0
PassthroughCluster::44.205.215.82:443::rq_timeout::0
PassthroughCluster::44.205.215.82:443::rq_total::77
PassthroughCluster::44.205.215.82:443::hostname::PassthroughCluster44.205.215.82:443
PassthroughCluster::44.205.215.82:443::health_flags::healthy
PassthroughCluster::44.205.215.82:443::weight::1
PassthroughCluster::44.205.215.82:443::region::
PassthroughCluster::44.205.215.82:443::zone::
PassthroughCluster::44.205.215.82:443::sub_zone::
PassthroughCluster::44.205.215.82:443::canary::false
PassthroughCluster::44.205.215.82:443::priority::0
PassthroughCluster::44.205.215.82:443::success_rate::-1
PassthroughCluster::44.205.215.82:443::local_origin_success_rate::-1
```
- [netstat](https://github.com/istio/istio/files/10974894/netstat.txt)
- [prometheus with metrics every other target workload filtered out](https://github.com/istio/istio/files/10975018/prometheus.txt)
- [trace logs around a failure (C425 and C426 are the connections for the failed request)](https://github.com/istio/istio/files/10975037/logs.txt)

**Comment by GregHanson** [comment]
@nberkley-gp `PassthroughCluster` is a general cluster added to sidecars for traffic considered "not inside the mesh", and the settings on it are not optimized since it does not know what kind of traffic to expect.  If you defined a ServiceEntry for the traffic in question, do you see a drop in the URX/connection failures?

**Comment by nberkley-gp** [comment]
Defining a ServiceEntry does seem to significantly reduce the frequency (possibly eliminates it entirely? I saw one instance of it during my test, but it seemed to correspond to a general latency spike so I suspect something else was afoot with that one)

So what's the difference between the passthrough cluster and more well defined clusters that would cause connection failures of all things?

**Comment by jbilliau-rcd** [comment]
This is happening to us as well. Here is an example of it working (thousands of times previously and thousand of times after) with a break in the middle:

<img width="1479" alt="image" src="https://github.com/istio/istio/assets/69006307/3f07427d-691f-47d0-8532-6e96fb0a83eb">

If we search through Splunk across our org for past 3 days, I show 3 million UF URX errors talking to external endpoints. No pattern seemingly, it's affecting onprem URL's, AWS URL's, DB URL's, etc. These are all endpoints our applications have `ServiceEntries` for. Some wildcard with *resolution: none*, others explicitly with *resolution: DNS*.

No idea if these are retried by Istio and invisible to the user/application or a huge cause for concern.

We are running EKS 1.24 across the board with Istio 1.15.7.

**Comment by GregHanson** [comment]
@jbilliau-rcd since the original issue seems to have been linked to traffic using PassthroughCluster, you have a ServiceEntry defined and traffic is routed through the desired cluster based on the access logs.  I would open a separate issue for your errors

**Comment by jneese** [comment]
I am also experiencing this issue.

**Comment by nielsole** [comment]
Check if the problem goes away if the clients disable connection reuse. Last I checked (>1y), Envoy doesn't always close connections to the client if the upstream goes away and if your clients do not reresolve DNS after TTL expires, ORIGINAL_DST load balancing on the sidecar will mean that if your upstream service changed IP addresses you will see 503 coming from the sidecar indefinitely.

**Comment by nielsole** [comment]
https://github.com/envoyproxy/envoy/issues/19458

**Comment by jbilliau-rcd** [comment]
I think @nielsole  is onto something here....we had our devs disable Istio, and they still got connection resets in their app. Turns out it was keep alive related....they fixed it, turned back on Istio, and the URX errors went away.

**Comment by owais** [comment]
@GregHanson do we really need to define service entry for every single external endpoint? What does passthrough cluster do differently that causes random connection drops? Our mesh is set to ALLOW_ANY so we expect istio to let external or unknown calls go through as is. However, we are seeing random disconnections with the passthrough cluster for external calls. The external IPs aren't even changing and are static for weeks if not months.

We had a similar issue before in a different cluster but that was related istio killing idle connections every hour. We disabled that behavior and the issue went away. This time however, it is dropping connection more randomly without any apparent time pattern. The disconnections don't happen when sidecar is removed or the outgoing port is excluded.
