### ISSUE TITLE
Ambient IptablesMode 

### ISSUE THREAD

**Issue by yuri-lcy** [istio/istio#43942]
### Bug Description

The iptables command is not case-sensitive, and the code here keeps returning error, causing chains to be added repeatedly.
it has no effect on traffic connectivity.

![image](https://user-images.githubusercontent.com/114134743/225201425-d29fbd7b-3129-4f79-b6d8-fd6c96809cd1.png)
![image](https://user-images.githubusercontent.com/114134743/225201466-9730b331-2e09-4817-803c-165e61b681ab.png)

### Version

```prose
master branch
```

**Comment by howardjohn** [comment]
cc @dhawton
