### ISSUE TITLE
istio watch another k8s cluster make one node of kafka can not work normally

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#43944]
### Bug Description

we have two k8s cluster, in the following we use v1 and v2 to represent them. We make v1's istio to watch v2's istio, one node of kafka can not work normally, client throw timeout exception.We remove v1's watch to v2, kafka work normally.

some informathin about istio and configuration of kafka for this two cluster.

v1: 
istio: version is 1.4.7, install by istioctl

kafka: there are seven service about kafka, namely kafka-1, kafka-2, kafka-3, kafka-4, kafka-5, kafka-6 and kafka-headless. Endpoint is similar, endpoint for kafka-headless is write five hostname which is the same with kafka 1-5.

v1 endpoint.yaml:
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-euw1-headless
  namespace: base-service
subsets:
\- addresses:
  \- hostname: kafka-euw1-1
      ip: 1
  \- hostname: kafka-euw1-2
       ip: 2
  \- hostname: kafka-euw1-3
      ip: 3
  \- hostname: kafka-euw1-4
    ip: 4
  \- hostname: kafka-euw1-5
    ip: 5
  ports:
  \- name: tcp-kafka
    port: 9092
    protocol: TCP

apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-euw1-6
  namespace: base-service
subsets:
\- addresses:
  \- ip: 6
  ports:
  \- name: tcp-kafka
    port: 9092
    protocol: TCP
  \- name: tcp-prometheus
    port: 9090
    protocol: TCP
  \- name: node-exporter
    port: 9100
    protocol: TCP

v2: 
istio version is 1.16.2, install by istioctl

kafka: there are seven service about kafka, namely kafka-1, kafka-2, kafka-3, kafka-4, kafka-5, kafka-6 and kafka-headless. Different from v1, endpoint for kafka-headless is write six hostname, the extra one is kafka-6.

v2 endpoint.yaml:
`apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-euw1-headless
  namespace: base-service
subsets:
\- addresses:
  \- hostname: kafka-euw1-1
    ip: 1
  \- hostname: kafka-euw1-2
    ip: 2
  \- hostname: kafka-euw1-3
    ip: 3
  \- hostname: kafka-euw1-4
    ip: 4
  \- hostname: kafka-euw1-5
    ip: 5
  \- hostname: kafka-euw1-6
    ip: 6
  ports:
  \- name: tcp-kafka
    port: 9092
    protocol: TCP

apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-euw1-6
  namespace: base-service
subsets:
\- addresses:
  \- ip: 6
  ports:
  \- name: tcp-kafka
    port: 9092
    protocol: TCP
  \- name: tcp-prometheus
    port: 9090
    protocol: TCP
  \- name: node-exporter
    port: 9100
    protocol: TCP
`

we make v1's istio to watch v2's istio, then kafka-6 can not work normally, client throw timeout exception when send event to kafka. We remove v1's watch to v2, kafka-6 work normally.  

Kafka server find some data package which size is 200-300M, server seems unable to parse, from the monitoring, the node traffic drops to zero and CPU is completely idle 

Client use service kafka 1-3 to ask kafka.

we can not find error log from pilot, buthowever the following logs were found about pilot_conflict_outbound_listener_tcp_over_current_tcp:
"xx.xx.xx.xx:9092": {
                "proxy": "test-7fd9f8c768-nnhqb.cloud",
                "message": "Listener=xx.xxx.xx.xx:9092 AcceptedTCP=kafka-euw1-headless.base-service.svc.cluster.local RejectedTCP=kafka-euw1-6.base-service.svc.cluster.local TCPServices=1"
            }

### Version

```prose
v1:
istioctl version:
client version: 1.4.7
control plane version: 1.4.7
data plane version: 1.4.7 (826 proxies)

kubectl version --short:
Client Version: v1.20.0
Server Version: v1.20.15-eks-fb459a0

v2:
istio version:
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (2 proxies)

kubectl version --short:
Client Version: v1.20.0
Server Version: v1.24.10-eks-48e63af
```

**Comment by howardjohn** [comment]
Istio 1.4 is 3 years EOL. Please upgrade and if you have issues and we will get back to you

**Comment by id-id-id** [comment]
来信已收到，祝好！
