### ISSUE TITLE
Handle workloadentries with overlapping IP and network

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#43950]
Tested with control plane built from `master` (single instance, KinD) and some VMs running zTunnel. I didn't set `INSTANCE_IP` so they all connected with `1.1.1.1`

I spun up three "vms" (docker containers) and it resulted in three WorkloadEntries:

```
❯ k -n vm-test get we
NAME         AGE   ADDRESS
s1-1.1.1.1   44s   1.1.1.1
s2-1.1.1.1   43s   1.1.1.1
s3-1.1.1.1   42s   1.1.1.1
```

After removing all the VMs 

```
❯ k -n vm-test get we
NAME         AGE   ADDRESS
s1-1.1.1.1   13m   1.1.1.1
s3-1.1.1.1   13m   1.1.1.1
```

The two stale entries did not have their disconnect time marked:

```
      istio.io/autoRegistrationGroup: s3
      istio.io/connectedAt: "2023-03-15T20:27:35.549053068Z"
      istio.io/workloadController: istiod-66cc75c9dc-4l8l4
```

First guess is that something is keyed on IP only instead of IP + some unique node ID stuff (i.e. auto-register group)

**Comment by stevenctl** [comment]
Istiod logs showing the disconnects. 

```
2023-03-15T20:34:21.802032Z     info    delta   ADS: "10.244.2.4:49076" .vm-test-95 terminated
2023-03-15T20:34:21.804838Z     info    delta   ADS: "10.244.2.4:54864" .vm-test-93 terminated
2023-03-15T20:34:21.805043Z     info    delta   ADS: "10.244.2.4:54868" .vm-test-94 terminated
```

10.244.2.4 is the east-west gateway.

**Comment by shashankram** [comment]
> Right.. but if somehow this does happen we should handle it better than we do today with multiple workload entries or workloadentries that are never cleaned up.

I think it would be nice to make the behavior deterministic -  either this configuration needs to be supported, or not. If this isn't supported, I'd prefer to detect this in Istiod and log an error instead of changing the code to support a scenario that's not meant to be supported.
