### ISSUE TITLE
Explore 1.27 IpAddress API

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43952]
There is now an IPAddress API in k8s. We should explore how or if we should use this in Istio.

One possible idea is persisting the auto-allocated service entry IP addresses.

This is still alpha so we can't _depend_ on it for a while, but worth exploring

cc @ramaraochavali @costinm @hzxuzhonghu @keithmattix

**Comment by keithmattix** [comment]
Linking the referenced GEP: https://github.com/kubernetes/enhancements/issues/1880

**Comment by hzxuzhonghu** [comment]
Great if can be used in istio, currently based on hash can have conflict

**Comment by hzxuzhonghu** [comment]
learned about that, it is to create a `IPAddress` object for each IP it allocated. It do not expose a way for other controller to require an IP.  I am not sure should we create do IP allocating like like it using IPAddress. If so it looks like no diff for us to create a svc placeholder for SE directly.

**Comment by hanxiaop** [comment]
not stale

**Comment by howardjohn** [comment]
One area it can be used is to do AutoAllocation for ServiceEntry. This basically allows k8s to allocate us an IP and we persist it into the cluster. Avoids ~all our issues with autoallocation I think

**Comment by hzxuzhonghu** [comment]
no stale
