### ISSUE TITLE
Istio should have port annotation to specify L7 protocols over TCP ports

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4395]
We had experienced issue when port name "grpc" is used, Istio treats it as HTTP/2 instead of "tcp". Then it failed to accept HTTPS traffic. 
       {
                "name": "grpc",
                "nodePort": 32075,
                "port": 443,  -> "tcp"
                "protocol": "TCP",
                "targetPort": 11006
            },   

> Automatically determining that the traffic is HTTP is an invalid assumption and I would suggest that a kubernetes service that is marked tcp should always be tcp, regardless of the name. If someone wants a tcp service to be handled as an HTTP service, an annotation should be required.

**Comment by kyessenov** [comment]
Joy, most of istio features rely on the assumption that the traffic is
HTTP. If we treat everything as just TCP, then there wouldn't be many
features left. Are you looking for an override that does not use the port
name?

**Comment by xiaolanz** [comment]
Updated the comment into "quotes". I agree that by assuming HTTP, we derives attributes for Mixer to use. First this has to be better documented. 

Second, we should have a better way to specify protocols than encoding into names.

**Comment by kyessenov** [comment]
Joy, this issue has a long history. K8s makes it difficult to annotate
fields deep in the spec.

**Comment by xiaolanz** [comment]
Kuat, it would be great if you can link this to some previous discussions. 

At this time, it's fair for us just improve the documentation.

**Comment by mandarjog** [comment]
I am adding this to Troubleshooting guide.

**Comment by sakshigoel12** [comment]
@mandarjog were you able to add this to the Troubleshooting guide? Can you link it here and close this issue

**Comment by howardjohn** [comment]
We are moving to a model where declaring protocol is not required, and if it is it is done explicitly in Sidecar. See https://github.com/istio/istio/pull/15802 and [better default networking](https://docs.google.com/document/d/12Z_oFCFn3_rTWbQsuR1GmjU5_WZVkBTJwFpFMx802Ns/)
