### ISSUE TITLE
Make Client/Server TLSSettings ca secret name configurable in credentialName support

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#43966]
**Describe the feature request**

The current credentialName support says "The secret (of type generic) should contain the following keys and values: key: <privateKey> and cert: <serverCert>. For mutual TLS, cacert: <CACertificate> can be provided in the same secret or a separate secret named <secret>-cacert."
eg: https://preliminary.istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings

In certain scenarios, there are external components creating these secrets following certain naming conventions, and it becomes difficult to adhere to the "-cacert" naming convention. Is it possible to make this configurable, by adding an additional "caSecret" field in TLSSettings?

**Describe alternatives you've considered**

If we use filemount based solution for TLSSettings, it has the flexibility to use any name for ca secrets. But this is a very complex configuration, and credentialName is the better solution.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
@costinm any thoughts?

@kfaseela curious if you expect to have 1:1 caSecret with credentialName? Or a common secret you use as caSecret for many configs

**Comment by jaellio** [comment]
I'm not very familiar with this area at all, but I did a little digging. In cases where we're looking for secrets with the `-cacert` suffix it looks like we also look for certs without the suffix (and therefore support ca secrets that don't use the suffix). I'm not positive if this is true for all scenarios.

**Comment by costinm** [comment]
What are the conventions used by the CA providers you use ? I would rather add logic to detect - like we do in agent for the workload identity ( UDS, old location, new location and names, GKE-style names ). 

Most users configuring DR will probably not know what the CA that happens to be used will be ( DR may be written in a CI-CD and deployed in multiple clusters using different CA providers, etc). And it's confusing and painful for users to do something we can easily automate.

I don't think there are more than 3-4 naming conventions.

**Comment by howardjohn** [comment]
Might be too far out but https://github.com/kubernetes/kubernetes/pull/113218 is the proper way to do this. 1.27 alpha

**Comment by costinm** [comment]
I'm also ok with a common secret used for caSecret - but I would also base it on auto-detection and following the naming conventions of different platforms instead of user doing the work. 

I don't think that K8S PR is the 'proper way' for us - but it is something we certainly should detect and use if it is there. 
If someone can start a wiki page with the different CA solutions that work with Istio ( CertManager, etc) and what formats/setups they use - it would likely be very helpful to troubleshoot and make sure the code can detect them.

And if a new CA wants to integrate - maybe they can look at the list and pick an already used scheme...

**Comment by kfaseela** [comment]
> @costinm any thoughts?
> 
> @kfaseela curious if you expect to have 1:1 caSecret with credentialName? Or a common secret you use as caSecret for many configs

@howardjohn  We support configuring multiple root CA certs in a single caSecret. So it is not necessarily a 1:1 relation. As it can be a single secret with a specific name, we cannot fulfil the <secret-cacert> naming convention. Different client/server certs are stored in corresponding secrets. We cannot for each of them create additional caSecret following naming convention. Each would have the same content and multiply the number of caSecrets. At the same time, we cannot have a single global caSecret name for all the usecases, as there are separate caSecrets created by different entities depending upon the scenario.

**Comment by costinm** [comment]
How custom is the name you use ? Is it a major / common provider ? I think having a couple names - and some Secret labels if possible - would work.

There is also the Gamma Binding that can be used to link the Secret.

As John mentioned, this is an API for K8S to define across everything - not something that only Istio would know about or define API for.

**Comment by Yngeaux** [comment]
> How custom is the name you use ? Is it a major / common provider ? I think having a couple names - and some Secret labels if possible - would work.
> 
> There is also the Gamma Binding that can be used to link the Secret.
> 
> As John mentioned, this is an API for K8S to define across everything - not something that only Istio would know about or define API for.

We use a common CA cert to verify server certs by clients in the mesh (note: servers are outside the mesh, but in the cluster). It is stored in a secret using an internal name, not related to a major/common provider. We would like to specify that secret name in the Destination Rule. With current implementation we can only use secret with the specific naming convention (<credentialName-cacert>). Solution could be to either configure the CA cert secret name in the DR or to pre-define the CA cert secret name (or label) and let Istio detect it.
We have however also the use case where we connect to servers outside of the cluster and in that case we need to use a different CA cert stored in another secret. How to handle that with an auto-detect implementation?

**Comment by kfaseela** [comment]
> Thanks for your feedback. I see that CA Certificates for workload to workload communication can be configured in mesh config as described [here](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-CertificateData). As I understand we could add another MeshConfig option for egress communication, where we specify the CA certificates to be used at client side in the mesh? Similar we could do for ingress connections? At the same time we will keep the current implementation of DR and Gateway, where CA cert can be added by using the 'credentialName' and corresponding naming convention with -cacert suffix.

I think it is difficult to make such traffic distinctions in the API. I got same comments from @ramaraochavali and @hzxuzhonghu while implementing ecdhCurves support. In this case, we need ways to distinguish two different types of external traffic - one towards a service within cluster, but outside Istio Mesh, and the second one is external to the cluster. It gets difficult to have such fine tuned parameters in MeshConfig, because Rama was also mentioning that we don't want to distinguish traffic like that in the code. 

@costinm The problem here is DR/Gateway already was supporting any names for ca secrets previously with fileMount option. And we were already using it. But now, when we want to migrate to credentialName support, we are not able to easily migrate because it requires us to recreate all the caSecrets with the specified naming convention.

**Comment by kfaseela** [comment]
@costinm would it be okay to have a configured common CA secret name which we can fall back to, if there is no user specified one in the Client/Server TLS settings, or when there is no CA secret available with -cacert suffix?

**Comment by costinm** [comment]
I don't see why not. We have a hardcoded secret for the root ca, another for intermediate certs, we hardcode the per-namespace replica.
