### ISSUE TITLE
Why not requeue when ReconcileIstioOperator reconcile failed

### ISSUE THREAD

**Issue by txlong2012slug** [istio/istio#43961]
Why not requeue when err is not nil or status is v1alpha1.InstallStatus_ERROR?

https://github.com/istio/istio/blob/bfd87df8b8f5d30a9e261bfabb5ccfcfa24d9f6c/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L398

**Comment by txlong2012slug** [comment]
When ingressgateway pod cannot connect to istiod after 5 minutes, ingressgateway IstioOperator will be set v1alpha1.InstallStatus_ERROR forerver, even though ingressgateway connect to istiod in the future.

**Comment by hanxiaop** [comment]
You can set the wait timeout to be larger than 5mins

**Comment by hanxiaop** [comment]
https://github.com/istio/istio/blob/0c51455500c2c001402212327c8622fe91a21a1f/operator/pkg/helmreconciler/reconciler.go#L108-L121
