### ISSUE TITLE
V0.7 is not backward compatible with V0.6

### ISSUE THREAD

**Issue by myidpt** [istio/istio#4398]
Some skew tests are failing (using V0.7 control plane with V0.6 data plane):
https://github.com/istio-releases/daily-release/pull/465
We need to fix this before V0.7 release.

**Comment by chxchx** [comment]
A potential fix https://github.com/istio-releases/daily-release/pull/476

**Comment by myidpt** [comment]
Now I can reproduce the error seen in https://github.com/istio-releases/daily-release/pull/465. The error happens when the control plane is deployed by istio-auth.yaml in V0.7.0 candidate, with the modification that Istio ingress uses Envoy image V0.6.0.

In this case, the Istio ingress will fail talking to Pilot, seeing the following error endlessly:
```
[2018-03-21 05:08:37.869][48][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-03-21 05:08:39.507][48][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2018-03-21 05:08:41.075][48][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
...
```

This is error is only seen on ingress Envoy, not Mixer Envoy or Pilot Envoy.

I have also tested V0.7.0 control plane (V0.7.0 ingress) + V0.6.0 data plane (bookinfo), the productpage was loaded successfully.

So I think the only issue is that Ingress V0.6.0 is incompatible with Pilot V0.7.0. If the data plane is deployed through istio-auth.yaml, this issue may not be visible to customers. This issue is visible only if the customers deploy the control plane components separately.

**Comment by wattli** [comment]
Oliver, thanks for the investigation, i think we should modify the skew test to keep ingress with v0.7

**Comment by myidpt** [comment]
Yes. I agree.
@chxchx Could you modify the skew test to only test based on old Envoy for the data plane not control plane?

**Comment by hklai** [comment]
So this is not release blocking. =)

**Comment by myidpt** [comment]
Digged a little more in this with Mandar. The issue is that Pilot's Envoy does not expose the 15005 port:
```
# cat envoy_pilot_auth.json
{
  "listeners": [
   {
    "address": "tcp://0.0.0.0:15003",
    "name": "tcp_0.0.0.0_15003",
    "filters": [
     {
      "type": "read",
      "name": "tcp_proxy",
      "config": {
       "stat_prefix": "tcp",
       "route_config": {
        "routes": [
         {
          "cluster": "in.8080"
         }
        ]
       }
      }
     }
    ],
    "ssl_context": {
     "cert_chain_file": "/etc/certs/cert-chain.pem",
     "private_key_file": "/etc/certs/key.pem",
     "ca_cert_file": "/etc/certs/root-cert.pem",
     "require_client_certificate": true
    },
    "bind_to_port": true
   }
  ],
...
```

**Comment by myidpt** [comment]
Close this issue since the case should not happen in a legitimate upgrade process.
