### ISSUE TITLE
Kubernetes Gateway API single deployment

### ISSUE THREAD

**Issue by nbjohnson** [istio/istio#43992]
Currently I can deploy a single istio ingressgateway deployment and then have multiple isto gateway configurations use that single ingress deployment using a selector. In the new Kubernetes Gateway API it wants to deploy a separate deployment per gateway config. I don't want that many ingressgateway deployments. I noticed there is an option for [manual deployments](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment) which I tested, but that errored out due to my existing istio ingressgateway and the kubernetes gateway configuration not being in the same namespace `failed to assign to any requested addresses: hostname not found in namespace "namespace1" but it was found in namespace(s) "namespace2"`.

I would like to be able to use a single ingress gateway deployment for many kubernetes gateway configurations that are in different namespaces. Is this configuration possible? Or am I stuck between 1. an ingress deployment in every namespace or 2. all my kubernetes gateway configs must be in the same namespace as the istio ingressgateway deployment?

**Comment by howardjohn** [comment]
This is not possible. They must be in the same namespace. However, the routes can be in other namespaces.
