### ISSUE TITLE
Getting And Error While Upgrading Istio

### ISSUE THREAD

**Issue by vbtadmin** [istio/istio#44005]
### Bug Description

I am getting below error while upgrading istio version to 1.16, can you please review and help me.

Error: UPGRADE FAILED: template: istiod/templates/telemetryv2_1.18.yaml:2:17: executing "istiod/templates/telemetryv2_1.18.yaml" at <include "prometheus" .>: error calling include: template: no template "prometheus" associated with template "gotpl"

### Version

```prose
istio version: 1.16
```

**Comment by zirain** [comment]
where did you get your istioctl? build from master branch?

**Comment by zirain** [comment]
please get target istioctl from github release or [istio.io](https://istio.io/latest/docs/setup/getting-started/#download)

BTW, it's a bug, but should be fixed with latest commit from master.

**Comment by vbtadmin** [comment]
Would you please suggest me the latest release that i can refer

**Comment by vbtadmin** [comment]
Can i use release-1.16, and take the reference from there ?

**Comment by howardjohn** [comment]
Installing from git is not supported. Please follow https://istio.io/latest/docs/setup/install/.

**Comment by vbtadmin** [comment]
Actually we  are referring to the same config which you have in git repo, so eariler config was old and now to upgrade the eks version we need to upgrade istio as well

**Comment by zirain** [comment]
use `curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.16.3 TARGET_ARCH=x86_64 sh -`

**Comment by howardjohn** [comment]
> Actually we are referring to the same config which you have in git repo, so eariler config was old and now to upgrade the eks version we need to upgrade istio as well

Again, **DO NOT USE GIT** for install. See https://istio.io/latest/docs/setup/install/. If you use git it will result in using the non-release images.
