### ISSUE TITLE
Istio itself should be deployed in Dual Stack mode if Dual Stack is enabled when user deploy the Istio

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#44017]
### Bug Description

As the Dual Stack feature is supported as experimental status feature since 1.17, however, the Istio itself is still deployed in the single stack even if the Dual Stack is enabled by user.
IMO, we should make Istio deployed in Dual Stack as well if user definitely enabled it like this.  And this issue should be part of #40394 as well.

### Version

```prose
$ ./istio-1.17.1/bin/istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (11 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.6+k3s1
```

**Comment by jorhett** [comment]
@zhlsunshine @Xunzhuo seems like this is still an active need, no?  I just lost hours banging my head up against the wall on this...

**Comment by zhlsunshine** [comment]
@jorhett, Yeah, I think it's stale, we need to keep it here.

**Comment by zhlsunshine** [comment]
Thanks @jacob-delgado,  close this issue!
