### ISSUE TITLE
ztunnel log printing order problem

### ISSUE THREAD

**Issue by yuri-lcy** [istio/istio#44018]
### Bug Description

When using ambient's version 2022.9, I found that ztunnel's logs are printed in this order:
**outbound tunnel -> outbound capture listener -> capture outbound (no waypoint proxy)**

![image](https://user-images.githubusercontent.com/114134743/226510121-970d31b1-937d-4c04-8a38-22ee827b7bf3.png)

But in reality, the order of execution of the listener should be like this:
**outbound capture listener -> capture outbound (no waypoint proxy) -> outbound tunnel**
It looks like there is a problem.

### Version

```prose
2022.9 version ambient
```

**Comment by hanxiaop** [comment]
See https://preliminary.istio.io/latest/blog/2023/rust-based-ztunnel/, Ztunnel is now implemented based on Rust. Please try the new version to see if you have more questions.

**Comment by GregHanson** [comment]
You can grab a `1.18.-` build from our [daily builds](https://gcsweb.istio.io/gcs/istio-build/dev/) or you can build directly from master branch in the istio/istio repo
