### ISSUE TITLE
istio-proxy has no envoy extensibility

### ISSUE THREAD

**Issue by jiayoukun** [istio/istio#44025]
I see that there is no support and documentation for envoy expansion under the proxy project. Is this something that needs to be added? Or do you already implement envoy extensions? Waiting for your answer?
If the implementation does not need to be added, I can support the direction of the code and documentation.

**Comment by zirain** [comment]
proxy has a config for enable extensions, you can find it [here](https://github.com/istio/proxy/blob/master/bazel/extension_config/extensions_build_config.bzl).
what's your real question?

**Comment by jiayoukun** [comment]
Yes, I've seen this part of the code. But how do you use it? Is there no documentation?
I tried to use @envoy//contrib/exe: enel-static but it compiled incorrectly.

**Comment by jiayoukun** [comment]
> proxy has a config for enable extensions, you can find it [here](https://github.com/istio/proxy/blob/master/bazel/extension_config/extensions_build_config.bzl). what's your real question?
Yes, I've seen this part of the code. But how do you use it? Is there no documentation?
I tried to use @envoy//contrib/exe: enel-static but it compiled incorrectly.
