### ISSUE TITLE
Kubernetes Gateway Status Improvements

### ISSUE THREAD

**Issue by danehans** [istio/istio#44035]
**Describe the feature request**
Currently, a Kubernetes Gateway reports "Ready=false" and "Programmed=false" if an external load balancer IP/hostname is unassigned. The dependent resources, e.g. Deployment, of the Gateway have been configured so the Gateway should report "Programmed=true". Additionally, a load balancer Service also creates a `ClusterIP` that should be surfaced in Gateway status addresses field.

**Describe alternatives you've considered**
- Allow a Kubernetes Gateway to support additional [Service types](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types). This will require Istio to support customizing the Gateway infrastructure by supporting GatewayClass [parameters](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.ParametersReference) or resolving https://github.com/kubernetes-sigs/gateway-api/pull/1757.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by frankbu** [comment]
> In https://github.com/istio/istio/pull/43975 I am dropping Ready since we cannot correctly implement it

@howardjohn Does that mean we need to change all the docs that are currently waiting for ready condition? e.g.
```
kubectl wait -n istio-ingress --for=condition=ready gateways.gateway.networking.k8s.io gateway
```

**Comment by howardjohn** [comment]
Yes we should be using programmed I think. However its plausible the spec itself will change, see https://github.com/kubernetes-sigs/gateway-api/issues/1832.
