### ISSUE TITLE
Secure cookies with istio

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#44051]
I had a bug in my application, cookies were not sent back to the client (simple auth proccess) after implementing istio.
This didn't happen before.

After debug I solved this issue by sending the cookies with unsecure format.

I want to understand why this is happenning only with istio (my guess is that traffic is being passed as http to envoy proxy or the ingress-gateway or both without https that allow secure cookies).

Can I solve this and if yes, how?
 
Another question: mtls is enabled in the cluster, is it possible that when I send unsecure cookies, the mtls pass them as secure to the client?

The flow of a request in the application: Client -> AWS LB -> ingress-gateway -> pod

Sample code (if relevant):
```
  const app = Fastify()
  app.register(fastifyCookie, {
    secret: "<secret>",
    hook: 'onRequest'
  })

  app.register(fastifySession, {
    secret: `<secret>`,
    cookie: {
        secure: false
    }
  })
```

I had to change secure to false

**Comment by SpecialYang** [comment]
Does your client use HTTPS？ If the secure flag of cookie is true, the client should send https subrequest, otherwise the browser will not send request with this cookie.

**Comment by Rez0k** [comment]
> Does your client use HTTPS？ If the secure flag of cookie is true, the client should send https subrequest, otherwise the browser will not send request with this cookie.

My application flow before istio:
Client (with https) -> AWS ELB (performing ssl termination) -> pod

My application flow after istio:
Client (with https) -> AWS ELB (performing ssl termination) -> ingress gateway (mtls enabled) -> envoy sidecar proxy -> pod

Before istio this worked as expected, after implementing istio the traffic is being passed as http somewhere inside the cluster and the cookie is being stripped away.

What can I do to fix that, without any code changes?

**Comment by Rez0k** [comment]
Any update?

**Comment by hanxiaop** [comment]
IIUC I think you need to configure the AWS ELB not to terminate ssl, and instead configure it in istio ingress gateway to handle the tls termination.

**Comment by hanxiaop** [comment]
https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

**Comment by Rez0k** [comment]
> IIUC I think you need to configure the AWS ELB not to terminate ssl, and instead configure it in istio ingress gateway to handle the tls termination.

I fixed this issue based on what you said and this article
https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/
