### ISSUE TITLE
Using envoy, during slow start phase, adding a new pod causes a brief surge of traffic for old pods within the slow start window

### ISSUE THREAD

**Issue by BruceMa29** [istio/istio#44088]
*Title*: *During slow start phase, adding a new pod causes a brief surge of traffic for old pods within the slow start window*

*Description*:
We discovered this issue during our load testing process. During the startup process, adding a new pod causes a brief surge of traffic for old pods within the slow start window. However, when adding two or more pods, this phenomenon does not occur.

we use DestinationRule，warmupDurationSecs is set 120s， The QPS (Queries Per Second) during load testing was 500.

Below is the traffic monitoring chart during the load testing process.

![image](https://user-images.githubusercontent.com/63951257/227185437-f7d6bfce-c983-40ee-8309-9cfce27544ae.png)

*Question*:

Why is there a surge in traffic and can this phenomenon be avoided?

**Comment by ramaraochavali** [comment]
Thanks for raising it in Envoy https://github.com/envoyproxy/envoy/issues/26290 - Let us wait to hear feedback there.
