### ISSUE TITLE
Allow multiple service entries with identical hostname

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#44084]
**Describe the feature request**
In my project, I am asked to connect multiple external service registries to istiod. However, these registries may contain services with identical host name, which poses a challenge as [the current servicenentry controller implementation](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/controller.go) assume only one service entry per host name.

I believe this issue can be resovled by following a similar approach by how Istio handles multiple Kubernetes services existing in multiple clusters. By adapting the serviceentry implementation to accommodate for these multiple external service registries, we can ensure the successful integration of all services into istiod.

**Describe alternatives you've considered**
A standalone component can be added to pull services from multiple external service registries and merge identical host names into a single entry before sending to Istio. However, this approach may introduce coupling among the service registries, which can make the system harder to manage and scale. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I don't feel great about even more complex service merging logic. We already do it in 3-4 place and its super inconsistent, undocumented, and untested

**Comment by zhaohuabing** [comment]
Maybe we can try to converge the merging mechanism of both the service and service entry and make it consistent across all the places?

@howardjohn Do you have suggestions on solving the hostname conflicts?

**Comment by howardjohn** [comment]
Hostname conflict in Service is only relevant across clusters so it's a bit
different (since hostname is derived from name)

**Comment by SpecialYang** [comment]
When Istio connects to two different MCP servers, it may receive two ServiceEntry resources from these two MCP servers individually. If hostnames of these two ServiceEntry resources are same, the later incomming ServiceEntry will override the previous one. But we expect to merge their static enpoints which are all used to serve.

So can we just merge these ServiceEntry resources which comes from different mcp servers?

**Comment by howardjohn** [comment]
Why is this not handled already by https://github.com/istio/istio/blob/f54a3d4582013c55f8154c43ace0ec79234ddab7/pilot/pkg/serviceregistry/aggregate/controller.go#L244?

**Comment by hzxuzhonghu** [comment]
Merging two objects is very tricky, especially service entry. We cannot do this without a clear proposal.
