### ISSUE TITLE
Images shouldn't have "imagePullPolicy: Always" should be "IfNotPresent"

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#441]
Images shouldn't have "imagePullPolicy: Always" should be "IfNotPresent"

**Comment by gyliu513** [comment]
Duplicate with https://github.com/kubernetes/charts/issues/1368

**Comment by ldemailly** [comment]
not. exactly a duplicate as the source is here

**Comment by gyliu513** [comment]
Wow, I see, thanks ;-)
