### ISSUE TITLE
EKS cluster with Calico networking webhooks are not reachable if not running in NodePort

### ISSUE THREAD

**Issue by ranga543** [istio/istio#44122]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

Provide option to allow users to provide webhook proxy service name and namespace when installing via Helm for base and istiod charts

**Comment by zirain** [comment]
IMO, `NodePort` is not recommended in Production. I do not think we should provide things in official helm chart.

Special use case can try with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by ranga543** [comment]
Yeah, that's why we need to have an option to allow users to have proxy service which might be running in different namespace as different service in same cluster.

**Comment by oxr463** [comment]
@ranga543 how can I reproduce?

**Comment by ranga543** [comment]
This can be closed, since we can use kustomization to modify specific resource before helm do actual installation. [https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/](https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/)
