### ISSUE TITLE
istio_{request,response}_message_count metrics are absent

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#44144]
There's a regression in Istio 1.17 with missing gRPC count metrics. It appears Kiali strongly depends on them. FR is to bring them back.

@zirain @jshaughn

**Comment by jshaughn** [comment]
Yes, Kiali uses these metrics to let gRPC users visualize their traffic when using long-running requests.  In this situation messages are much more reflective of traffic than requests.  Here is a snippet from the Kiali Graph page showing the various ways users can visualize traffic:

![image](https://user-images.githubusercontent.com/2104052/228369245-58d1ca94-912c-42bf-bbeb-a2f1cf03e81f.png)

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/44094? cc @kyessenov

**Comment by kyessenov** [comment]
@zirain No, that PR is for *Envoy* grpc stats, the linked PR fixes it for *Istio* grpc stats.

**Comment by zirain** [comment]
reopen, should add test for this.

**Comment by whitneygriffith** [comment]
Yes, I am working on an integration test for this now

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/44231
