### ISSUE TITLE
Validation endpoint downtime during restart/upgrade

### ISSUE THREAD

**Issue by calikonur** [istio/istio#44157]
### Bug Description

Hi,
I think I may have found  a problem which happens during restart/upgrade of istiod deployment.
Basically, when I restart/upgrade /validate endpoint is affected by some downtime.
From what I see this has led, in my cluster, to custom resources not being validated by istiod during upgrade, which in turn led to the failure of the "helm upgrade" command.
It seems that the downtime is very short but that can occasionally lead to failures when I upgrade with telemetry enabled (due to EnvoyFilters being deployed).
Sadly, I cannot give the steps to reproduce the "helm upgrade failure" but I can provide some steps to show the downtime validate endpoint is affected by:

1. Deploy istio 1.17.1
2. Deploy a fortio pod which is out of the mesh in a namespace named "test" and start sending request to the "/validate" endpoint of istiod from fortio pod using following command: `fortio load -k -t 0 -allow-initial-errors -c 20 -qps 200 https://istiod.istio-system.svc.cluster.local:443/validate`
3. While requests are being sent, restart/upgrade istiod using following command: `kubectl rollout restart deployment istiod -n istio-system`
4. Wait until the new istiod pod is running again and stop the fortio. You should see some "connection refused" log messages as follows:

> 09:11:41 W http_client.go:795> [5] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [16] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [7] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 E http_client.go:653> [5] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [0] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [13] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [11] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [12] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [3] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [2] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [15] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [18] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [19] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [6] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 E http_client.go:653> [4] Unable to TLS connect to 10.96.114.63:443 : dial tcp 10.96.114.63:443: connect: connection refused
> 09:11:41 W http_client.go:795> [7] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [17] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [10] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [9] Non ok http code 400 (HTTP/1.1 400)
> 09:11:41 W http_client.go:795> [8] Non ok http code 400 (HTTP/1.1 400)
> 

Is that downtime expected behavior of istiod? Is there a way to overcome the occasionally failures when deploying CRs as part of the upgrade procedure.
Thank you in advance

### Version

```prose
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (1 proxies)
$ kubectl version --short
Client Version: v1.20.1
Server Version: v1.24.7
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11100383/bug-report.tar.gz)

**Comment by hanxiaop** [comment]
I think downtime is expected since you are doing the upgrading. You can try to set the rolling update strategy to see if it helps.

**Comment by calikonur** [comment]
Hi @hanxiaop,

I believe this issue happens because istiod is being classified as Ready although it is not completely ready. Unfortunately, rolling update strategy is also not solving this problem.

The important problem with this issue is that when we try to upgrade with telemetry enabled the patch for EnvoyFilter fails because validation endpoint on istiod is not ready yet. It leads to following error during rollout restart.

`Error: UPGRADE FAILED: cannot patch "stats-filter-1.9" with kind EnvoyFilter: Internal error occurred: failed calling webhook "rev.validation.istio.io": Post "https://istiod.istio-system.svc/validate?timeout=10s": EOF`

I think this should not be the default behavior, what do you think?

**Comment by hanxiaop** [comment]
You may try to edit the validation webhook's `failurePolicy` from `Fail` to `Ignore` before performing the upgrade?

**Comment by howardjohn** [comment]
this is unexpected. we should be Ready only when we are actually ready.

**Comment by hanxiaop** [comment]
> I feel like your suggestion is a workaround rather than a permanent solution. This problem will occur every time I would like to upgrade the istiod's future versions as well. With your workaround, suggested steps needs to be performed when istiod upgrade takes place and this can be painful in a long term.
> Instead, we should have a permanent solution for this issue, so that the issue does not persist anymore.
> Please let me know your thoughts about this.

Yes it's unexpcted. I looked through the code, and it looks like there could be a time when the server is marked as ready, but the validationController is not ready yet. I'm going to look into it and find a solution.

**Comment by kfaseela** [comment]
thanks @hanxiaop ! I was about to start working on this, but since you have already picked up, I am not looking into it, Thanks for the help! this seems to be relevant code area : https://github.com/istio/istio/blob/60de11172fff06106503c07a0194d1d70e1609dc/pilot/pkg/bootstrap/webhook.go#L87

**Comment by hanxiaop** [comment]
@kfaseela Sorry I just saw the issue and didn't realize someone is working on this. If you've already got any ideas feel free to unassign me and finish your work. Or I can finish and notify you to review my logics.
