### ISSUE TITLE
Large scale of mesh control plane performance issue

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#44163]
### Bug Description

Any suggestions/best practice for solving the Istio control plane and data plane scalability issue? 

In our production cluster there will be 100k Pods(with sidecar injected) and 20k services, 10k vs/gw in the mesh and we got control plane issues like xds(mainly rds) push latency even envoy main thread cpu utilization high issue.
There are restrictions like istiod cpu/memory, xds config size, push latency and even gateway envoy main thread, ingressgw cpu/bandwidth etc.  As of now there are some draft ideals:

1. Enhance control plane performance by leveraging delta xds push or xds-relay?

2. Enable both control plane and data plane sharding, it will spilt the cluster into multiple mesh based on different discoverySelector, but this is going to bring challenge to enable mesh traffic.

### Version

```prose
istio 1.17
```

**Comment by hzxuzhonghu** [comment]
On demand xds  pluse delta is the most ideal for this case. Unfortunately it is not here. 

We can use `sidecar` to manually tell istio the demaning services of a sidecar proxy atm.

**Comment by shonecyx** [comment]
Thanks @hzxuzhonghu.

We already configured the `sidecar` with egress hosts `- ~/*` to trim the sidecar configure significantly and current we didn't enable much east-west traffic.

However the concern here is not the sidecar but the istiod and ingressgw with large cluster.  In our case most servicea are http/https and due to micro-service, we have thousands of ingress(envoy listeneres)/vs/svc in the mesh. 

1. ​​Delta xDS supported https://github.com/istio/istio/issues/31638 . In our performance tests, we are seeing high XDS push latencies contributed mainly by RDS (for our VirtualService specs). ​​ BTW I don't have permission to see this doc, is there plan to continue implement the on demand xds pluse delta in upstream?
2. xDS cache: ​​https://github.com/istio/istio/issues/26732. It seems to me it's the trade-off memory for time by the cache, I understand it will help for the xds push latency but could cause memory overhead/oom for large scale of mesh.
3. Xds-relay: Caching, aggregation, and relaying for xDS compliant clients and origin servers: https://github.com/envoyproxy/xds-relay (seems dead).
