### ISSUE TITLE
Istio sidecars flood CoreDNS because of ExternalName services

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#44169]
Knative creates K8s Services of type=ExternalName

This seems to cause problems for Istio - more details here: https://github.com/knative/serving/issues/12917

Are there any recommendations?

**Comment by fatedier** [comment]
Does this [configuration parameter](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#:~:text=No-,dnsRefreshRate,-Duration) help?

**Comment by dprotaso** [comment]
It seems like we added ports to our `ExternalName` service as a potential work around to

https://github.com/istio/istio/issues/23463

related: https://github.com/istio/istio/issues/37331

I'm curious if we still need this wokaround - I saw this was merged https://github.com/istio/istio/pull/21987

**Comment by howardjohn** [comment]
The 5s isn't accurate as a default anyways anymore, now the ttl of the dns server is respected which is 30s or 60s (I forget) in coredns defaults

**Comment by hzxuzhonghu** [comment]
60s bye default, which can be changed by updating meshConfig.DnsRefreshRate

**Comment by dhumphries-sainsburys** [comment]
We have seen this also resulting in 80k/s requests hitting coredns.
