### ISSUE TITLE
Contents of cni config is being set to size 0 in case of ungraceful shutdown

### ISSUE THREAD

**Issue by noah8713** [istio/istio#44167]
### Bug Description

We have seen recent issues where k8s nodes are ungracefully marked down e.g. during scenarios like physical switch maintenance. During this scenario we found after the node is back up online, cni config contents are 0. This causes install-cni to fail too as file is empty and also failure on containerd and dependency components. We use chained CNI.

```
            # Deploy as a standalone CNI plugin or as chained?
            - name: CHAINED_CNI_PLUGIN
              value: "true"
```

After doing some tests with both SIGTERM/SIGKILL, enabled containderd logs and checked.
```
DEBU[2023-03-28T09:51:21.340156088-07:00] ignore event from cni conf dir: "/etc/cni/net.d/tessnet.conflist.tmp.959517671": CREATE
DEBU[2023-03-28T09:51:21.340242813-07:00] ignore event from cni conf dir: "/etc/cni/net.d/tessnet.conflist.tmp.959517671": CHMOD
DEBU[2023-03-28T09:51:21.340332544-07:00] receiving change event from cni conf dir: "/etc/cni/net.d/tessnet.conflist.tmp.959517671": RENAME
DEBU[2023-03-28T09:51:21.340588551-07:00] ignore event from cni conf dir: "/etc/cni/net.d/tessnet.conflist": CREATE
DEBU[2023-03-28T09:51:21.340681489-07:00] receiving change event from cni conf dir: "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig": REMOVE

```
Seems for clean up part https://github.com/istio/istio/blob/master/cni/pkg/install/install.go#L143 , can we see for any window of improvement for sigterm? Not sure if its already reported or its more on containerd or node fsnotify event issue for sigterm.

It mostly on nodes like hadoop/big data which are disk heavy we see this once in a while. 
Impact is post node reboots, existing pods cannot come up due to empty cni config.

### Version

```prose
#istioctl version --short
client version: 1.10.4
control plane version: 1.10-dev
data plane version: 1.10-dev (18 proxies)

kubectl version --short
Client Version: v1.20.0
Server Version: v1.18.8-419+xxx
```

**Comment by howardjohn** [comment]
Does this reproduce on 1.17? 1.10 is EOl and I thik there have been some changes around here

**Comment by noah8713** [comment]
Thanks @howardjohn .Didn't try that ; can explore with kind as even in 1.10 its not easily reproducible. Only major change I see is fsnotify fix for install-cni https://github.com/istio/istio/pull/34710 . OVerall there are too many changes as per commits. We can explore that with 1.17. Just that wanted to ensure if its something not on k8s cni vs just istio issue!
