### ISSUE TITLE
Change eastwest-gateway from L4 proxy to L7 proxy on multi-network.

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#44178]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We want to change eastwest-gateway from L4 proxy to L7 proxy on multi-networks.
There are some reasons.
1. L7 traffic statistics. 
2. Request observability. We want to see the latency between networks on trace.
3. Better request loadbalancer with long-lived connection. Some issues mention this problem.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[-] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[-] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
>
> L7 traffic statistics.
> Request observability. We want to see the latency between clusters on trace.

It seems these are supported on multicluster.

**Comment by howardjohn** [comment]
This essentially breaks zero trust (and authz policies and telemetry) as the network gateway becomes a Mitm to all traffic crossing network boundaries.

Its something we might enable but will never be the default option IMO.

**Comment by Patrick0308** [comment]
> > L7 traffic statistics.
> > Request observability. We want to see the latency between clusters on trace.
> 
> It seems these are supported on multicluster.
@howardjohn On multicluster , we can't see eastwest gateway on trace. And we don't know latency between eastwest gateway and client on another cluster

**Comment by howardjohn** [comment]
Not to be pedantic, but just so everyone is on the same page, this is a _multi network_ issue, not a general _multi cluster_ issue.

**Comment by Patrick0308** [comment]
@howardjohn Yeah, you are right. It's a multi network issue.

**Comment by shlomobielak** [comment]
Wondering if this will solve our GRPC issue where calls are not distributed evenly or logically. Most likely pinned.

**Comment by Patrick0308** [comment]
> Wondering if this will solve our GRPC issue where calls are not distributed evenly or logically. Most likely pinned / long lived.

@shlomobielak Yeah. It's can be completely solved. Now you can setting maxRequestPerConnection to mitigate pinned connection.

**Comment by ivantrips** [comment]
> Yeah. It's can be completely solved. Now you can setting maxRequestPerConnection to mitigate pinned connection.

This is only true if you make an specific number of requests on a timeframe like every second, but if you exceed that number of request set in `maxRequestPerConnection` you will get rate limited so 50% of your requests will fail

**Comment by Patrick0308** [comment]
> Its something we might enable but will never be the default option IMO.
@howardjohn About how does control panel know eastwest gateway is on L7 not L4, do you have any idea? Maybe adding a field on proxyConfig?

**Comment by ivantrips** [comment]
> Why getting rate limited? It should be using a new connection to send requests.

I tested this trying to Load Balance connections between two clusters in a multi-network / multi-primary setup, for a single RPC per second it looked like it solved the issue but taking a deeper look into the [docs](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings) when we specify connectionPoolSettings like envoy `maxRequestPerConnection` is a circuit breaker, which caused a lot of traffic to be rate limited in a threshold

**Comment by eitah** [comment]
My company also needs this feature. @ivantrips and @stevenctl spoke at Kubeconf 2023 about this.

**Comment by stevenctl** [comment]
To make the eastwest gateway support L7 features it needs to see things at the request level. The functionality requested in this issue can be provided by a standard _ingress_ gateway without passthrough. 

This comes with a couple caveats:

* Istio's automatic service discovery doesn't support this today
* You'd need to do something like create a ServiceEntry in the client cluster pointing to the gateway of the server cluster
* Largest issue: server now verifies the gateway's identity instead of the client

It really feels like waypoints would help with this.

```
network 1            network 2

client ->  gateway -> waypoint -> server
```

**Comment by hzxuzhonghu** [comment]
>client ->  gateway -> waypoint -> server

Yeah, this topology can solve L7.  But adding an additional hop.

Referring to this idea, if we have east-west gateway per service, we can achieve the same result

**Comment by ivantrips** [comment]
Thank you @stevenctl  and @hzxuzhonghu 
i would like to think about the gateway per service too

**Comment by hzxuzhonghu** [comment]
You mean eat-westgateway act also as watpoint, i think this may make sense

**Comment by Patrick0308** [comment]
@hzxuzhonghu Maybe we should reopen this issue?

**Comment by viko97-a12** [comment]
We have uneven traffic distrubution between EKS and on-prem Kubernetes cluster. Also we have VMs in the setup and they talk to the east-west gateway and when using GRPC protocol for communication between VM app and k8s app, we see only 1 pod takes all of the traffic instead of all of them. When services communicating in the same cluster, we don't see issue, the grpc load-balancing is OK. 

I see that the issue comes from this cross-network gateway as the mode is AUTO_PASSTHROUGH and it loadbalances on TCP. 

Is there a permanent solution about this?
