### ISSUE TITLE
Test or pre-submit check to make sure types.go is consistent with output from generate_config_crd_types.go

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4418]
This is to make sure:
- No manual inputs are allowed.
- Any change in tools or the model config would be reflect correctly (e.g https://github.com/istio/istio/pull/4246 was missing the change in https://github.com/istio/istio/pull/4305 for the script)

**Comment by ozevren** [comment]
@diemtvu Can we close this? Is this still applicable?

**Comment by ozevren** [comment]
I think there is already a linter for this
bin/check_pilot_codegen.sh

If you think this is still applicable, please reopen.
