### ISSUE TITLE
Istio Standard metrics drill down to pod name

### ISSUE THREAD

**Issue by cathchu** [istio/istio#44196]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, I believe it's only possible to evaluate standard Istio metrics down to the service/ canonical service level (ex: istio_request_duration_milliseconds).  

Identifying the specific pod affected will allow more granular troubleshooting and rolling up latency per pod, rather than service. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Prometheus adds the pod name  when it scrapes a metric
