### ISSUE TITLE
istio.io/istio/tests/e2e/tests/dashboard.TestDashboards/Istio TestDashboards flaky

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4420]
see errors: https://k8s-gubernator.appspot.com/build/istio-prow/e2e-cluster_wide-auth/1128

**Comment by xiaolanz** [comment]
Still failing. https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1156

**Comment by douglas-reid** [comment]
Something is causing Mixer not to load the prometheus adapter:
```
I0322 04:10:25.886] 2018-03-22T04:10:25.885710Z	info	Running command kubectl exec -n dashboard-test-11b6cd385b804048af8d44 echosrv-deployment-55f9467f7b-ss5bj -c echosrv -- /usr/local/bin/fortio curl http://istio-mixer.dashboard-test-11b6cd385b804048af8d44:42422/metrics
I0322 04:10:26.510] 2018-03-22T04:10:26.510411Z	info	Command output: 
I0322 04:10:26.511] 04:10:26 E http_client.go:566> Read error &{{0xc42027e280}} {10.23.250.234 42422 } 0 : read tcp 10.20.1.21:47606->10.23.250.234:42422: read: connection reset by peer
```

**Comment by douglas-reid** [comment]
@xiaolanz the latest link you posted doesn't appear to have recent code changes (ie., there are no `waiting for Mixer to be configured...` log lines and all of the failings appear entirely related to infrastructure issues.
