### ISSUE TITLE
gRPC config stream closed: 8, request rate limit exceeded

### ISSUE THREAD

**Issue by gudipudipradeep** [istio/istio#44200]
### Bug Description

ResourceExhausted desc = request rate limit exceeded: rate: Wait(n=1) would exceed context deadline
StreamAggregatedResources gRPC config stream closed: 8, request rate limit exceeded: rate: Wait(n=1) would exceed context deadline (previously 14, error reading from server: EOF since 1s ago

### Version

```prose
C:\istio-1.15.1\bin>istioctl version --remote
client version: 1.15.1
control plane version: 1.14.3
data plane version: 1.12.3 (250 proxies)
```

### Additional Information

"exception":"Grpc.Core.RpcException: Status(StatusCode=\"Unavailable\", Detail=\"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111\")\n

**Comment by howardjohn** [comment]
This is expected if there happens to be a sudden surge of requests to Istiod control plane.

If you see it excessively, it may be a sign of an issue. please include more info.

**Comment by gudipudipradeep** [comment]
Please let me know what information I can add. This is happening still we aren't sure.. any hard limit with istio to extend the value. 

Please guide me how we can debug this issue future.

**Comment by wulianglongrd** [comment]
@gudipudipradeep this error is that the connection of the sidecar to the istiod is limited.

if a large number of sidecars concurrently connect to istiod may trigger istiod limit (default is 25 QPS), this kind of error usually recovers quickly. You can update the limit value by `PILOT_MAX_REQUESTS_PER_SECOND`, see here:
https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars

**Comment by gudipudipradeep** [comment]
"no healthy upstream" getting this issue while request from other container to access grpc request. but when we did port-forward it is working as expected.
 how to debug this issue to understand where was the issue..

**Comment by wulianglongrd** [comment]
> "no healthy upstream" getting this issue while request from other container to access grpc request. but when we did port-forward it is working as expected. how to debug this issue to understand where was the issue..

it may be that no healthy endpoint, retrieve xds config use `istioctl proxy-config ...`

https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-proxy-config-endpoint

**Comment by gudipudipradeep** [comment]
we are getting different different issue suddenly with istio, few micro services are working few showing some different issues.
`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111`

How to deep dive this kind of issue to trace in istio porxy logs.
 can we see inbound and outbound traffic via istio..? Please suggest me how we can see inbound and out bound traffic in istio-proxy

**Comment by gudipudipradeep** [comment]
Any live traffic debugging for inbound and outbound in istio-proxy pod or in between pods or in name space like that

**Comment by wulianglongrd** [comment]
not familiar with envoy(istio-proxy), I think you can go to envoy repo to ask, you can also join slack to ask questions. there are many experienced people there.  https://istio.io/latest/get-involved

**Comment by howardjohn** [comment]
Closing as the original issue was addressed and there hasn't been followup. Thanks!
