### ISSUE TITLE
If there is a problem with istio-proxy, how to fallback?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#44263]
I am inquiring about a solution. If you know how to solve it and are willing to share your solution ideas with me, thank you very much~

This is the case, if my business service is connected to the service grid, if one day the istio-proxy (sidecar) has a problem and hangs up, causing the business to fail to run normally, how can I fallback? Is there a way to ignore sidecar errors without restarting the business service container, just like the direct connection mode?

**Comment by zirain** [comment]
you can try to offload the iptables rule.
IMO, it's not part of this project's goal.

**Comment by mark8s** [comment]
@zirain Ok, I understand that this is not the original intention of the project, but I think this may be a very practical solution. It would be best if friends with relevant experience can answer.

**Comment by peterj** [comment]
I don't think there's an easy way to achieve. But, I am not familiar with your scenario where restarting the pods would not work, especially when you have multiple replicas of your pods running. I am not a math person, but the probability of all Envoy proxy instances failing at the same time in all replicas is probably quite low. 

I guess one of the solutions is to run multiple replicas to minimize the risk of this happening.

**Comment by mark8s** [comment]
@peterj thank you for your reply
