### ISSUE TITLE
configure istio.stats in envoyfilter

### ISSUE THREAD

**Issue by yankunsam** [istio/istio#44273]
### Bug Description

I want to disable istio_request_total metric for a specific service in envoyfilter, but it always report message like these:
```
	warn	ads	ADS:LDS: ACK ERROR client-grpc-6fbd669b7b-7jbn8.default-5 Internal:Error adding/updating listener(s) 0.0.0.0_8080: Didn't find a registered implementation for name: 'istio.stats'
```

### Version

```prose
1.10.2
```

### Additional Information

Is it possible to disable some metric in envoyfilter?

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by peterj** [comment]
What does your EnvoyFilter look like?

**Comment by yankunsam** [comment]
@peterj 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-metrics
  namespace: default
spec:
  workloadSelector:
    labels:
      app: client-grpc
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: MERGE
      value:
        name: istio.stats
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"
          # "@type": "type.googleapis.com/udpa.type.v1.TypedStruct"
          type_url: "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm"
          # "type_url": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm"
          value:
            config:
              root_id: "stats_outbound"
              vm_config:
                runtime: "envoy.wasm.runtime.null"
                vm_id: "stats_outbound"
                code:
                  local:
                    inline_string: "envoy.wasm.stats"
              configuration:
                "@type":  "type.googleapis.com/google.protobuf.StringValue"
                "value": |
                  {
                   "metrics": [
                     {
                       "drop": "true",
                       "name": "requests_total"
                       "debug": "true"
                     }
                   ]
                  }
                # "{\"metrics\":[{\"drop\":true,\"name\":\"requests_total\"}]}"
```

**Comment by peterj** [comment]
Which version of Istio are you using? I tried with 1.18 and I don't see any error in istiod. Also, your `typed_config` should look like this:

```
        typed_config:
          "@type": "type.googleapis.com/udpa.type.v1.TypedStruct"
          type_url: "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"

```

**Comment by yankunsam** [comment]
@peterj Have you tried metrics be dropped?

**Comment by zirain** [comment]
1.10 is too old, please upgrade to [supported release](https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases).

please do not edit envoyfilter directly if you're not familiar with it.

use IstioOperator/Telemetry API is recommended.

https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

https://preliminary.istio.io/latest/docs/tasks/observability/metrics/telemetry-api/

**Comment by yankunsam** [comment]
@zirain  1. We use Telemetry v2, so Telemetry API not work as document says. 2. I just to want to remove metric so some services, not global, so IstioOperator can't.

**Comment by zirain** [comment]
Telemetry v2 use to distinguish from Mixer(Telemetry v1).

[Telemetry API](https://istio.io/latest/docs/tasks/observability/telemetry/) enables flexible configuration of [metrics](https://istio.io/latest/docs/tasks/observability/metrics/), [access logs](https://istio.io/latest/docs/tasks/observability/logs/), and [tracing](https://istio.io/latest/docs/tasks/observability/distributed-tracing/).

**Comment by yankunsam** [comment]
> Telemetry v2 use to distinguish from Mixer(Telemetry v1).
> 
> [Telemetry API](https://istio.io/latest/docs/tasks/observability/telemetry/) enables flexible configuration of [metrics](https://istio.io/latest/docs/tasks/observability/metrics/), [access logs](https://istio.io/latest/docs/tasks/observability/logs/), and [tracing](https://istio.io/latest/docs/tasks/observability/distributed-tracing/).

so I can use Telemetry API with Telemetry v2?

**Comment by zirain** [comment]
sure

**Comment by yankunsam** [comment]
> sure

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: remove-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - disabled: true
          match:
            metric: ALL_METRICS
            mode: CLIENT_AND_SERVER
```
not work for me, metrics are still generated.

**Comment by zirain** [comment]
do you disabled the EnvoyFilter way?
https://preliminary.istio.io/latest/docs/tasks/observability/metrics/telemetry-api/#before-you-begin

**Comment by yankunsam** [comment]
I have try to disable v2, and works just now. So I can't use Telemetry API with Telemetry v2.

**Comment by yankunsam** [comment]
@zirain When I disable v2, it means no envoyfilter stats, But can I still use other Envoyfilter? like Lua script, nothing about metric。

**Comment by zirain** [comment]
> 

yes，it removes `tcp-stats-*` and `stats-*`

**Comment by yankunsam** [comment]
thanks @zirain
