### ISSUE TITLE
Error running iptables-nft command: protocol not supported

### ISSUE THREAD

**Issue by peterj** [istio/istio#44274]
### Bug Description

CNI plugin fails to set up the iptables/interfaces in ambient mode (built with changes up to commit g rev-parse 82c35a1db946a9db6df1b68d523182cb8247d094)

```
Error running command iptables-nft: iptables/1.8.7 Failed to initialize nft: Protocol
```

More details in the log.
[cnilog.txt](https://github.com/istio/istio/files/11172305/cnilog.txt)

### Version

```prose
$ g rev-parse master
82c35a1db946a9db6df1b68d523182cb8247d094

$ go run ./istioctl/cmd/istioctl version
client version: unknown
control plane version: 1.18-dev
data plane version: 1.18-dev (1 proxies)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
https://superuser.com/a/1599411 possibly? need reboot?

**Comment by peterj** [comment]
it works with the exact same Kind cluster using released 18 alpha build. I can try on a non-kind cluster, but it’s odd why one build would require a reboot, the other wouldn’t.

**Comment by howardjohn** [comment]
ok that would be weird. Just seems to be the only explanation for "protocol
not supported"
