### ISSUE TITLE
Umbrella issue for application liveliness and readiness probes

### ISSUE THREAD

**Issue by ayj** [istio/istio#4429]
Application liveliness and readiness probes don't work out-of-the-box with Istio in all configurations.

* Readiness probes fails on container init with default envoy config until Pilot provides dynamic config.
* Liveliness and readiness probes with mTLS fail if the probe port is shared with the service port.
* Liveliness and readiness probes are subject to mixer policy checks and telemetry reporting. 

Some of this is documented on https://istio.io (see https://istio.io/help/faq/security.html#k8s-health-checks). Other solutions are captured in github issues, e.g. https://github.com/istio/istio/issues/1194#issuecomment-367379499.

Here's a snapshot of issues related to application liveliness and readiness probes:

* https://github.com/istio/istio/issues/1194 - Omitting listener for management address
* https://github.com/istio/istio/issues/1422 - need to not break non istio traffic (and be able to selectively intercept or not some services/namespaces/pods/...)
* https://github.com/istio/istio/issues/1425 - Envoy active health checks
* https://github.com/istio/istio/issues/1467 - Incomplete tests: Add liveness and readiness probes to proxies and discovery services
* https://github.com/istio/istio/issues/1985 - Postgres Kubernetes Helm chart fails with Envoy... 
* https://github.com/istio/istio/issues/2628 - Liveness Readiness Probe Istio
* https://github.com/istio/istio/issues/2808 - Add Mixer Check support for health-checks
* https://github.com/istio/istio/issues/4363 - pilot: default passthrough listener/cluster
* https://github.com/istio/istio/issues/4345 - Replace httpGet with exec during Kube-inject 
* https://github.com/istio/istio/issues/3519 - Customer pain points meta issue  (see Readiness / Liveness probes)

It would be good to reference this umbrella issue for any new liveliness/readiness probe issue to avoid dups. It would also be nice to have the full list of workarounds documented on https://istio.io

**Comment by wattli** [comment]
I am actively working on this. Seems mostly it's about the documentation for what we can support in 1.0

**Comment by F21** [comment]
Are there still any plans to support liveness probes with mTLS enabled or is it a wontfix?

**Comment by thockin** [comment]
Chiming in from the other side of the fence - this seems particularly problematic to me.  We have spent a lot of energy telling Kubernetes users that they should all be using readiness and liveness probes.  I feel like there should really be a transparent "fast path" for this that doesn't require users to create additional resources nor to disable mTLS.  Am I asking for too much?

**Comment by wattli** [comment]
@incfly , can we mark this as fixed?

**Comment by incfly** [comment]
https://github.com/istio/istio/issues/9150 covers k8s prober for liveness and readiness health check, which I is this umbrella bug about mostly.

However when I read the bug more closely, it seems like we would like to include more than that:
>  * Readiness probes fails on container init with default envoy config until Pilot provides dynamic config

Also I didn't follow through each individual bug listed in the description. Defer to @ayj to clarify the scope, to see if this bug has more stuff to do beyond #9150

**Comment by 4c74356b41** [comment]
this is about a year old? any chance it gets into 1.1.0? or is it even going to get released at all?

**Comment by 4c74356b41** [comment]
so is this released or what @andraxylia
