### ISSUE TITLE
Handle long cluster names

### ISSUE THREAD

**Issue by rshriram** [istio/istio#4430]
our current cluster name length is hardcoded to 189 characters or such. This suffices for most situations, but every now and then, someone's deployment sees a lot of segfaults because they use very long names for their service or subset.

We need to handle this case when building cluster names and more importantly, be able to detect that we are parsing a plain vs condensed cluster name in the EDS requests.

The old solution of SHA256 ing the entire name is not acceptable in practice as it makes all metrics (from envoy) and hence the dashboards unreadable. We need to find an alternative solution that preserves the readability of the dashboards.

cc @costinm

**Comment by kyessenov** [comment]
To be clear, the only way around this is by hashing. We just need to teach
the dashboards to recover the human readable names.

**Comment by ZackButcher** [comment]
Related, I also have use cases from customers to support non-DNS (RFC 1035) conformant names (e.g. names that contain UTF8/non-ascii characters).

IMO we shouldn't be performing any validation on names that users give us (so long as Envoy can support routing it). What are the limitations in Envoy today w.r.t. name-matching for selecting filter chains and matching inside of the HTTP filter, etc?

**Comment by rshriram** [comment]
It’s mainly chars accepted by statsd
