### ISSUE TITLE
Does sidecar not support vcl connections in Envoy's conrib?

### ISSUE THREAD

**Issue by jiayoukun** [istio/istio#44308]
Does sidecar not support vcl connections in Envoy's conrib? I tried to add sidecar to vcl. After adding the configuration of vcl, sidecar becomes unavailable to the grpc configured by istiod. Have you encountered this problem?
Looking for an answer? thank you

**Comment by zirain** [comment]
most of extensions in contrib are ignored in istio proxy's ci.

**Comment by zirain** [comment]
you can find the configuration [here](https://github.com/istio/proxy/blob/master/bazel/extension_config/extensions_build_config.bzl).

**Comment by jiayoukun** [comment]
> you can find the configuration [here](https://github.com/istio/proxy/blob/master/bazel/extension_config/extensions_build_config.bzl).

I have used this part, I compiled istio-proxy separately and added vcl of envoy's contrib, but sidecar's "envoy.extensions.upstreams.http.v3. HttpProtocolOptions" filter seems to conflict with the "envoy.extensions.vcl.vcl_socket_interface" filter. It seems to be invalid in the grpc of downlink xds.
