### ISSUE TITLE
Need Istio Secrets API and/or mechanism

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4431]
Mixer adapters need to access credentials for the backends they interact with. 

At the moment, credentials need to be specified in the clear within an adapter config CRD. This is not acceptable from a security perspetive.

We therefore need a **platform-neutral** way for adapters to gain access to secrets.

**Comment by kyessenov** [comment]
dupe of https://github.com/istio/api/issues/161?

**Comment by geeknoid** [comment]
Dupe of #4434
