### ISSUE TITLE
Select Gateway from Gateway API as main gateway for IngressClass

### ISSUE THREAD

**Issue by JuniorJPDJ** [istio/istio#44313]
I'm trying to migrate advanced haproxy config file to kubernetes native approach.
Gateway API experimental and istio seems to be enough to fulfill my needs.
I'm using some legacy helm charts and services using `Ingress` resources, so I need ingress controller too, some in dynamic way, so I can't just create `HTTPRoute`s in separate resources which would do the same as helm-prepared `Ingress`.

istio seemed to be ideal way for handling both cases but...

I cannot specify gateway to be used for ingress controller.
Ideal way would be to create `IngressClass` resource which would have some annotation used to select which Gateway should handle ingress, but other way would be cool too.

The case is similar to multiple ingress-nginx deployments on one cluster, each watching for other `IngressClass`es and listening on other IPs or even subnets.

I dived into some issues like this one: #22400 and saw `mesh.ingressService` config option, which would be a good start for me, but I failed to setup it with Gateway API - I've deployed no istio-legacy Gateway.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ has settings for `Ingress` like you found - but not `Gateway`.

`Gateway API` works a bit differently. By default there will be one `istio` GatewayClass. Each Gateway you create refers to that. The HTTPRoutes refer to the Gateway.

If you want 2 different load balancer deplomyents/IP, you can create multiple Gateway's, both pointing to the `istio` GatewayClass.

See https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/ if you haven't already

**Comment by howardjohn** [comment]
So you want to use the same Service/Deployment for `Ingress` and `Gateway`? is that right?

If so you can do it, just set `ingressService` to the same one you created by the Gateway?

**Comment by JuniorJPDJ** [comment]
That's right.
I tried and it seems not to work - LoadBalancer doesn't even get an IP address.

**Comment by JuniorJPDJ** [comment]
Nvm, it was namespace problem - gateway is in another namespace than the rootNamespace.

Ingress now has IP address but traffic is not being routed.
