### ISSUE TITLE
How to support the same service having both IP endpoints and domain name endpoints

### ISSUE THREAD

**Issue by masquee** [istio/istio#44327]
I have a service where **some of the endpoints are pods within the cluster (accessible via IP),** and **some endpoints are not in the current cluster and can only be accessed via domain name**. 

However, when I looked at the ServiceEntry configuration in Istio, I found that only one type of `Resolution` can be set: `STATIC` or `DNS`.  How can this problem be solved? 

Envoy itself support this situation where each cluster can set its own `type`. 

I also considered using multiple ServiceEntries to distinguish between them, configuring both `DNS` and `STATIC` ServiceEntries for the same service. But in this case, can a subset in DestinationRule select endpoints from two ServiceEntries? Or is there any other alternative solution?

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is not currently possible
