### ISSUE TITLE
Our defaults should be to fail close when calls to Mixer.Check fail

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4432]
RIght now, proxy is configured by default to fail open on calls to Mixer.Check. For security reasons, it should be failing close by default.

**Comment by kyessenov** [comment]
conflicts with https://github.com/istio/istio/pull/4376

**Comment by loewenstein** [comment]
The PR actually moved to https://github.com/istio/istio/pull/4456

**Comment by kyessenov** [comment]
mixer check is always fail_closed as of few weeks ago.
