### ISSUE TITLE
Basic auth for the telemetry backend is missing

### ISSUE THREAD

**Issue by rpuserh** [istio/istio#44335]
### Bug Description

Basic auth for the telemetry backend is missing

### Version

```prose
istioctl version
client version: 1.17.2
control plane version: 1.17.1
data plane version: 1.17.1 (2 proxies)

# kubectl version --short 
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.24.6
```

### Additional Information

I'm running Grafana tempo on different k8s Cluster and ingress has basic auth.
Now I want to send traces to tempo however there is no configuration for basic auth 
[Document reference](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing-Zipkin) has no option for any auth

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
IIRC, Istio/Envoy does not support tempo, are you using OpenTelemetry collector?

**Comment by rpuserh** [comment]
I found this for otlp in [docs](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-OpenTelemetryTracingProvider) and this has no option to set basic auth.
What will be the recommendation to write into Tempo if using OpenTelemetry collector is the best option I don't see [basic auth ](https://opentelemetry.io/docs/collector/configuration/#exporters) for exporters

**Comment by rpuserh** [comment]
If authentification is not supported what will be solution ?

**Comment by zirain** [comment]
for now, I would say istio send tracing to agent collector, and then transfer to another gateway collector?

**Comment by rpuserh** [comment]
Was able To solve problem using Open Telemetry collector.

**Comment by CODY-RAY** [comment]
@rpuserh reopen this please. 
this is something istio should document/add to the crd if it is not already supported
