### ISSUE TITLE
Some AuthorizationPolicy configurations do not work as expected. 

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#44348]
### Bug Description

In my environment, an egress gateway is defined and two ports, 80 and 443, are bound, corresponding to the http and tls protocols respectively。

It also defines that VirtualSerices forwards http requests for external services to port 80 and https requests to port 443 of this egress gateway.

As above these are only background introduction, not the focus。

The point is, I'm encountering a strange problem with AuthorizationPolicy on the egress gateway。

My requirement: block httpbin requests using http post。 So I defined the yaml as follows:

```yaml
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: sleep-a-egress-www-httpbin-org
  namespace: istio-system
spec:
  action: DENY
  rules:
    - to:
        - operation:
            hosts:
            - www.httpbin.org
            - httpbin.org
            methods:
              - POST
      from:
        - source:
            namespaces: ["mytest"]
  selector:
    matchLabels:
      istio: egressgateway-a
```

Then I used the following command to verify the effect。
```shell
kubectl -n mytest exec deployment/sleep-a -- curl -s -w"%{http_code}\n" -o /dev/null  http://www.httpbin.org
200

kubectl -n mytest exec deployment/sleep-a -- curl -s -w"%{http_code}\n" -o /dev/null  http://www.httpbin.org -X POST
403
```
Meets expectations. but  when I tried to request https://www.httpbin.org,  a strange problem has occurred:

```shell
kubectl -n mytest exec deployment/sleep-a -- curl -s -w"%{http_code}\n" -o /dev/null  https://www.httpbin.org
000
command terminated with exit code 35
```

The log corresponding to the gateway is as follows:
```shell
2023-04-12T06:54:52.549540Z     debug   envoy filter    [C77357] new tcp proxy session
2023-04-12T06:54:52.549574Z     debug   envoy filter    [C77357] Creating connection to cluster outbound|443||www.httpbin.org
2023-04-12T06:54:52.549617Z     debug   envoy misc      Allocating TCP conn pool
2023-04-12T06:54:52.549638Z     debug   envoy pool      trying to create new connection
2023-04-12T06:54:52.549645Z     debug   envoy pool      creating a new connection (connecting=0)
2023-04-12T06:54:52.549681Z     debug   envoy connection        [C77358] connecting to 34.235.32.249:443
2023-04-12T06:54:52.549742Z     debug   envoy connection        [C77358] connection in progress
2023-04-12T06:54:52.549759Z     debug   envoy conn_handler      [C77357] new connection from 172.16.0.198:44846
2023-04-12T06:54:52.762637Z     debug   envoy connection        [C77358] connected
2023-04-12T06:54:52.762683Z     debug   envoy pool      [C77358] attaching to next stream
2023-04-12T06:54:52.762686Z     debug   envoy pool      [C77358] creating stream
2023-04-12T06:54:52.762711Z     debug   envoy filter    [C77357] TCP:onUpstreamEvent(), requestedServerName: outbound_.444_._.istio-egressgateway-a.istio-system.svc.cluster.local
2023-04-12T06:54:52.763058Z     debug   envoy rbac      checking connection: requestedServerName: outbound_.444_._.istio-egressgateway-a.istio-system.svc.cluster.local, sourceIP:172.16.0.198:44846, directRemoteIP: 172.16.0.198:44846,remoteIP: 172.16.0.198:44846, localAddress: 172.16.0.245:444, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/mytest/sa/default, dnsSanPeerCertificate: , subjectPeerCertificate: , dynamicMetadata:
2023-04-12T06:54:52.763084Z     debug   envoy rbac      enforced denied, matched policy ns[istio-system]-policy[sleep-a-egress-www-httpbin-org]-rule[0]
```

This Authorizationpolicy blocks outbound tls requests. This does not match the expected。https requests are treated as tcp requests and should not be affected by the configuration as above.

I checked the configDump for the egress gateway and found that the configuration has an amplification effect。

![image](https://user-images.githubusercontent.com/370590/231374148-297acceb-f733-47c9-bc46-2fb22b85ef4a.png)

This should be a bug.

A workaround solution is to use the semantics of "ALLOW"

```yaml
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: sleep-a-egress-www-httpbin-org
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
            - www.httpbin.org
            - httpbin.org
            notMethods:
              - POST
      from:
        - source:
            namespaces: ["mytest"]
  selector:
    matchLabels:
      istio: egressgateway-a
```

### Version

```prose
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (9 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
This is working as intended IIUC and is documented: https://istio.io/latest/docs/reference/config/security/authorization-policy/

'When this rule is applied to TCP traffic, the method field (as will all HTTP based attributes) cannot be processed. For a DENY rule, missing attributes are treated as matches. This means all TCP traffic on port 8080 would be denied in the example above. If we were to remove the ports match, all TCP traffic would be denied. As a result, it is recommended to always scope DENY policies to a specific port, especially when using HTTP attributes [Authorization Policy for TCP Ports](https://istio.io/latest/docs/tasks/security/authorization/authz-tcp/).'

**Comment by zengyuxing007** [comment]
> This is working as intended IIUC and is documented: https://istio.io/latest/docs/reference/config/security/authorization-policy/
> 
> 'When this rule is applied to TCP traffic, the method field (as will all HTTP based attributes) cannot be processed. For a DENY rule, missing attributes are treated as matches. This means all TCP traffic on port 8080 would be denied in the example above. If we were to remove the ports match, all TCP traffic would be denied. As a result, it is recommended to always scope DENY policies to a specific port, especially when using HTTP attributes [Authorization Policy for TCP Ports](https://istio.io/latest/docs/tasks/security/authorization/authz-tcp/).'


The current implementation does correspond to the documentation.

As described in the documentation above, when the rule is applied to TCP traffic, the configuration containing HTTP attributes is implicitly removed, thus widening the scope of impact。This does not meet the expectations of users。 

Because multiple matches under a single RULE are “AND” relationships, and the user is also known that the HTTP attribute will fail under Tcp, it might be better to make the whole rule (including HTTP attributes) not valid for TCP traffic。

**Comment by howardjohn** [comment]
> The current implementation does correspond to the documentation.

What part is inconsistent? You are describing "HTTP rule means all traffic is denied", which is what the document is intending to say.
