### ISSUE TITLE
Design for safely manipulating secrets

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4434]
@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/api/issues/161)

@ayj commented on [Wed Jun 14 2017](https://github.com/istio/galley/issues/18)

Galley needs a solution to allow producers and consumers of Istio configuration to manipulate references to secrets. The secrets themselves should not be stored in Galley.

---

@ayj commented on [Fri Jun 16 2017](https://github.com/istio/galley/issues/18#issuecomment-309142464)

@istio/auth-hackers, @wenchenglu

---

@ldemailly commented on [Fri Jun 16 2017](https://github.com/istio/galley/issues/18#issuecomment-309171480)

> The secrets themselves should not be stored in Galley.

where then / why not?

shouldn't they just be protected ?

---

@myidpt commented on [Fri Jun 16 2017](https://github.com/istio/galley/issues/18#issuecomment-309189496)

Are they K8s secrets? Can you be more specific about manipulating the references to secrets? Does it grant producers/consumers permissions to access the secrets or something else?

---

@ayj commented on [Fri Jun 16 2017](https://github.com/istio/galley/issues/18#issuecomment-309194683)

From [Proposal: Galley (Istio Configuration)](https://docs.google.com/document/d/13UqmYpEjNGT2xucIgWaTQIQUgQuAASeIdm8Ks3zp5Fk/edit#bookmark=id.s027slt4cgqr):

> The Istio configuration model may include secrets which need to be stored in a secured vault and not the configuration storage. The configuration component should support the notion of secrets as a first class thing and provide necessary APIs to enable producers and consumers of Istio configuration to handle references to secrets.

In particular, its desirable to avoid re-inventing a secret store and instead use an existing system, e.g. https://www.vaultproject.io, k8s secrets. Istio configuration resources would reference secrets in these stores without storing the secrets themselves in Galley. For example, 

- Mixer needs secure credentials to program backend infrastructure. 
- Operator (producer) creates Istio configuration along with reference to secure credentials.
- Mixer (consumer) uses the secret reference to get the actual secret via the secret store. Mixer can then program the backend infrastructure with corresponding configuration. 

Galley would not be responsible for managing permission model of secrets.

---

@ldemailly commented on [Mon Jun 19 2017](https://github.com/istio/galley/issues/18#issuecomment-309467629)

There is a bootstrap issue there and I don't think we can avoid managing secret as that's core to the functionality of Istio - but happy to be shown we don't.

also if we have a seperate secret store (is it in auth?) we need an implementation for rawvm and hybrid

---

@wenchenglu commented on [Mon Jun 19 2017](https://github.com/istio/galley/issues/18#issuecomment-309525671)

There are different types of secrets we need to manage:
(1) key/cert for establishing mTLS for service-to-service auth
(2) credentials (api key, jwt, auth token, username/password, etc.) to access backends or remote services

Is this issue mostly about the case (2)? I agree that Vault is a good option considering its popularity as a secret store. For case (1), Vault is optional since key/cert can be stored in local memory of each node. We can still use Vault + PKI backend as CA, which is not mainly for secret storage in this case though.

---

@myidpt commented on [Mon Jun 19 2017](https://github.com/istio/galley/issues/18#issuecomment-309534905)

So if the configuration is just a reference, Galley is not able to verify if the producer really has permission to access the secret, right? After the operator writes the secret in Vault, how does the operator grant permission to Mixer/service to access the secret?

---

@sakshigoel12 commented on [Wed Aug 16 2017](https://github.com/istio/galley/issues/18#issuecomment-322938632)

Is this for 0.2 or 0.3?

---

@wenchenglu commented on [Wed Aug 16 2017](https://github.com/istio/galley/issues/18#issuecomment-322938783)

not 0.2

---

@costinm commented on [Tue Aug 29 2017](https://github.com/istio/api/issues/161#issuecomment-325878356)

K8S has a secrets storage API - not perfect, but AFAIK they are improving it ( and I understand it may also have a Vault plugin at some point ). 
Also using Vault directly as CA or secret store was discussed. 

Do we need anything else ?

**Comment by ozevren** [comment]
I don't think this is still relevant.
