### ISSUE TITLE
Create InstanceMsg from yaml

### ISSUE THREAD

**Issue by guptasu** [istio/istio#4435]
Given template descriptor and instance config yaml, create Assembler during config time. An assembler is a processor that can create bytes during runtime.

**Comment by guptasu** [comment]
This Issue to not to make calls, it is just to create bytes. Therefore does not include any gRPC stuff

**Comment by guptasu** [comment]
@mandarjog the prototype we worked on is here:
https://github.com/guptasu/istio/tree/jsonToProtoBinary/mixer/cmd/genericGRPC

**Comment by mandarjog** [comment]
resolved.
