### ISSUE TITLE
Gateway not getting listed (istio classic)

### ISSUE THREAD

**Issue by vyom-soft** [istio/istio#44354]
### Bug Description

Hello,
I followed the Create a gateway [(bookinfo istio-classic)](https://istio.io/latest/docs/examples/bookinfo/)
It got installed under default NS. 
When I try to list the Gateway it is not found.?  I do not understand why the Gateway is not getting listed.

`kubectl get gateway`  shows nothing

On the other hand the Gatway API variant, shows that the Gateway is present.

### Version

```prose
➜  ~ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (10 proxies)

➜  ~ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
I think this is really a k8s issue that Istio happens to be impacted by. Basically there are two "gateway" defined by 2 CRDs. kubectl has some logic to pick which one. I don't know the logic but it seems to prefer the Gateway API one.

To work around this you can use the short name (which happens to not conflict with the other one) `kubectl get gw` or the fully qualified name: `kubectl get gateways.networking.istio.io`

**Comment by vyom-soft** [comment]
> I think this is really a k8s issue that Istio happens to be impacted by. Basically there are two "gateway" defined by 2 CRDs. kubectl has some logic to pick which one. I don't know the logic but it seems to prefer the Gateway API one.
> 
> To work around this you can use the short name (which happens to not conflict with the other one) `kubectl get gw` or the fully qualified name: `kubectl get gateways.networking.istio.io`

Yep it works!!
@howardjohn Thank you for the information. It is good to know that there are work around.
