### ISSUE TITLE
Randomly facing 503 - 'Upstream_reset_before_response_started{connection_termination}' in our environments.

### ISSUE THREAD

**Issue by divyashreedhar** [istio/istio#44350]
### Bug Description

We are randomly facing 503 - 'Upstream_reset_before_response_started{connection_termination}' in our environments.

Istio details
-------------
Istio Version : 1.12.1
Istio install method: istioctl
Istio profile : demo

Debugs were enabled in the istio layer for more clarity.
Logs are as attached :

This is not specific to any application and is seen for many of the applications.
Please help suggest on the possible root causes and suggestions to resolve the issue.

Regards
Divyashree

### Version

```prose
Istio version
1.12.1

Kubernetes
Client : v1.20.10
Server : v1.21.14-eks
```

### Additional Information

Please find attached the debug logs from istio.
![Upstream_Reset](https://user-images.githubusercontent.com/130554088/231423014-594da940-81b0-4482-be0a-7b19b833c220.png)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by cf1998** [comment]
I also encountered this problem, how to solve it?

**Comment by hanxiaop** [comment]
What's your Istio version? 1.12.1 is too old and no longer being supported. Try to upgrade Istio to see if it helps.
