### ISSUE TITLE
Verifying signature with Cosign v2 fails due to Transparency Log

### ISSUE THREAD

**Issue by Logankwb** [istio/istio#44362]
### Bug Description

Version 2 of Cosign enables its "Transparency Log" feature by default. Using Cosign to verify Istio images returns the following error:

```shell
# cosign verify --key "https://istio.io/misc/istio-key.pub" istio/pilot:1.17.0
Error: no matching signatures:
signature not found in transparency log
main.go:69: error during command execution: no matching signatures:
signature not found in transparency log
```

I'm guessing signing the latest Istio images with Cosign v2 would push the signature to the transparency log.

Also the image referred to on the website appears to have moved (I'm happy to raise this on the istio.io repo):
```shell
# ./cosign-binary verify --key "https://istio.io/misc/istio-key.pub" gcr.io/istio-release/pilot:1.17.0
Error: image tag not found: GET https://gcr.io/v2/istio-release/pilot/manifests/1.17.0: MANIFEST_UNKNOWN: Failed to fetch "1.17.0" from request "/v2/istio-release/pilot/manifests/1.17.0".
main.go:69: error during command execution: image tag not found: GET https://gcr.io/v2/istio-release/pilot/manifests/1.17.0: MANIFEST_UNKNOWN: Failed to fetch "1.17.0" from request "/v2/istio-release/pilot/manifests/1.17.0".
```

### Version

```prose
# cosign version
GitVersion:    v2.0.1
GitCommit:     8faaee4d2b5f65678eb0831a8a3d5990a0271d3a
GitTreeState:  clean
BuildDate:     2023-04-06T19:10:33Z
GoVersion:     go1.20.3
Compiler:      gc
Platform:      linux/amd64
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
The missing gcr.io/istio-release/pilot:1.17.0 was a one-of, 1.17.1 and all other versions are present on gcr.io. Not sure about the rest

**Comment by howardjohn** [comment]
cc @stewartbutler @jacob-delgado

**Comment by howardjohn** [comment]
It would be nice to backfill if its feasible. If not forward fix.

So I guess - whatever we can :-)

**Comment by ericvn** [comment]
I see the version mentioned is `1.17.0` which I think failed the signing step in some fashion. However, I think `1.17.1` should be OK, although I haven't verified.

One other difference might be cosign versions. `release-1.17` build-tools has 1.13.1 while the main brach has 2.0.1. I think the only change was adding a `-y` to skip prompts.

**Comment by ericvn** [comment]
For the 1.18 builds (now from the main branch for a few more day(s)), I hopefully fixed with a change in release-builder as we were incorrectly not signing due to a command error: https://github.com/istio/release-builder/pull/1455

**Comment by ericvn** [comment]
@stewartbutler I only know of the logs in prow, which is where I found the 1.18 issue.
