### ISSUE TITLE
Add a switch in ExternalIstiod mode to determine whether to add configCluster to the multicluster

### ISSUE THREAD

**Issue by devincd** [istio/istio#44368]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When I install Istio with an External Control Plan. https://istio.io/latest/docs/setup/install/external-controlplane/

I found the following issues:

- The `external_cluster` cluster will create an `istio-ca-root-cert `configMap in each namespace, but when I deploy istiod for multiple tenants in the `external_cluster` cluster, it seems to not work properly,because the `istio-ca-root-cert` configMap is modified as Istiod of different tenants is created.
- Istiod will automatically discover endpoints in the `external_cluster` cluster, but I only want istiod to discover endpoints in the `remote_cluster`.

When I looked at the code, I found that `configCluster` is currently added to the multicluster by default, which causes the above two unexpected phenomena.
https://github.com/istio/istio/blob/master/pkg/kube/multicluster/secretcontroller.go#L173

Can we add a switch in ExternalIstiod mode to determine whether to add configCluster to the multicluster?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
@frankbu

**Comment by hzxuzhonghu** [comment]
Serveral questions:

>The external_cluster cluster will create an istio-ca-root-cert configMap in each namespace, but when I deploy istiod for multiple tenants in the external_cluster cluster, it seems to not work properly,because the istio-ca-root-cert configMap is modified as Istiod of different tenants is created.

Assume the config cluster is `external_cluster ` here. How could different tenenants not interfere with each other when they have different configs? 


In istio we have a `--kubeconfig` arg, i think you can use it to point to the configcluster isolated from other tenants

**Comment by devincd** [comment]
> Assume the config cluster is external_cluster  here. How could different tenenants not interfere with each other when they have different configs?

Configure different configSources(MCP) for each tenant in `istio configMap`.

**Comment by devincd** [comment]
When I create an external Istiod in Cluster-A without adding any remote clusters yet, the external Istiod will automatically add all services and endpoints in Cluster-A. This is not the result I expect. I only want the external Istiod to manage services and endpoints in remote clusters.

**Comment by hzxuzhonghu** [comment]
> In istio we have a --kubeconfig arg, i think you can use it to point to the configcluster isolated from other tenants

Hope this can help

**Comment by devincd** [comment]
> When I create an external Istiod in Cluster-A without adding any remote clusters yet, the external Istiod will automatically add all services and endpoints in Cluster-A. This is not the result I expect. I only want the external Istiod to manage services and endpoints in remote clusters.

> In istio we have a --kubeconfig arg, i think you can use it to point to the configcluster isolated from other tenants

When I use `--kubeconfig`, The external Istiod in Cluster-A logs the following errors:
```
Error from server (Forbidden): deployments.apps is forbidden: User "dev" cannot list resource "deployments" in API group "apps" in the namespace "default"
```

Because the kubeconfig does not have access to the default namespace in cluster-A, but the external Istiod still tries to access it, causing many errors to occur, which is not what is expected.

**Comment by devincd** [comment]
cc @frankbu @howardjohn

**Comment by hzxuzhonghu** [comment]
So this is just permission issue, can you give it enough permission to do that

**Comment by devincd** [comment]
If I given sufficient permissions, the external Istiod will automatically add all services and endpoints in Cluster-A.

>When I create an external Istiod in Cluster-A without adding any remote clusters yet, the external Istiod will automatically add all services and endpoints in Cluster-A. This is not the result I expect. I only want the external Istiod to manage services and endpoints in remote clusters.

**Comment by hzxuzhonghu** [comment]
Not sure i can folow you,  i suggested you pass the kubeconfig of a remote cluster(the config cluster you choose), in your case this is not the cluster istiod deployed.
