### ISSUE TITLE
Custom access_logs in Istio

### ISSUE THREAD

**Issue by Ayaz-Tanzeem** [istio/istio#44367]
I am using Istio 1.17. I want to edit the log format according to my requirements. How can I do this?

I tried to edit IstioOperator accordingly, but it didn't work.
I tried a lot of things suggested by ChatGPT. But none of those work.
I tried using EnvoyFilter, but that also didn't work.

@GregHanson

**Comment by zirain** [comment]
https://istio.io/latest/docs/tasks/observability/logs/access-log/
https://istio.io/latest/docs/tasks/observability/logs/telemetry-api/

**Comment by Ayaz-Tanzeem** [comment]
Thanks, but this does not explain how can I use custom log format.

**Comment by hanxiaop** [comment]
The links provided are instructions on how to use custom access logs. Use either MeshConfig or Telemetry API.

**Comment by zirain** [comment]
This's more like a question, not a real issue.
I'd like close this first, feel free to reopen if you have further question.

**Comment by Ayaz-Tanzeem** [comment]
Yes, this can be closed. Actually, I did manage to use custom format. But for that, I had to reinstall Istio. I still don't know how can I change the log format whenever I want. Can someone please explain to me.

**Comment by zirain** [comment]
unneeded to uninstall istio, just change values in `MeshConfig`.
