### ISSUE TITLE
Failed to informer *v1.CustomResourceDefinition

### ISSUE THREAD

**Issue by 371873574** [istio/istio#44387]
### Bug Description

error info:
W0414 10:19:58.598657       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1.CustomResourceDefinition: Get "https://10.233.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?limit=500&resourceVersion=0": dial tcp 10.233.0.1:443: connect: connection refused
E0414 10:19:58.598866       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: Get "https://10.233.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?limit=500&resourceVersion=0": dial tcp 10.233.0.1:443: connect: connection refused   
================================
When the Golang program starts, an error will be reported in the init method by executing the informer CustomiResourceDefinition, which uses the cluster mode
Will the occurrence of this problem be related to the startup sequence of the istiosidecar

But the k8s pod informer I opened at the same time, there was no problem

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (3 proxies)
kubectl version --short
Client Version: v1.23.10
Server Version: v1.23.10
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Yes, this can be related to the injection. The traffic may be received without the proxy being ready.

**Comment by hanxiaop** [comment]
Have you set `readinessProbe `?

**Comment by hzxuzhonghu** [comment]
You may need to enable `holdApplicationUntilProxyStarts` feature

**Comment by 371873574** [comment]
> Have you set `readinessProbe `?

no

**Comment by 371873574** [comment]
> You may need to enable `holdApplicationUntilProxyStarts` feature

Thank you, but I tried. This won't do

**Comment by 371873574** [comment]
@istio-policy-bot help

**Comment by 371873574** [comment]
> Have you set `readinessProbe `?

help

**Comment by hanxiaop** [comment]
> > Have you set `readinessProbe `?
> 
> help

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ Try to set `readinessProbe ` for your app, and i think the error will be avoided.

**Comment by 371873574** [comment]
> > > Have you set `readinessProbe `?
> > 
> > 
> > help
> 
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ Try to set `readinessProbe ` for your app, and i think the error will be avoided.


This is quite troublesome, and you still need to modify the code. Does isto support configuration and allow isto proxy to run before the business container
