### ISSUE TITLE
For  "istioctl pc route xxx " ,  add the vhostName field to the command output

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#44413]
**Describe the feature request**

"**vhost name**"  is very important in certain usage scenarios, such as the semantics of the [Envoyfilter patch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-VirtualHostMatch)

And the name of the virtual host is determined by the program, it is not easy to know the name of the virtual host in complex cases, such as the case of route merging under multiple domains under the gateway 

**Describe alternatives you've considered**

Add a column "VHOST NAME" to the output

**Affected product area (please put an X in all that apply)**

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
Finished by https://github.com/istio/istio/pull/44414
