### ISSUE TITLE
Question: What is the state of the MCS (Multi Cluster Services) implementation?

### ISSUE THREAD

**Issue by andrwca** [istio/istio#44415]
Hi,

Is there a central location which tracks the state/progress of adoption of the MCS (Multi-cluster services) KEP?

The KEP I refer to is:

https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api

I've seen some documents and issues, which describe some progress, including:

Istio RFC 'Istio and MCS':
https://docs.google.com/document/d/1K8hvQ83UcJ9a7U8oqXIefwr6pFJn-VBEi40Ak-fwQtk

Issues tracking phase 1 and 2:
https://github.com/istio/istio/issues/29383
https://github.com/istio/istio/issues/29385

Specifically, I'd like to understand:

- Is this still an active area of development and on a road map to be completed?
- If it is an active area, are there any documents describing what features are available for alpha/beta testing?
- In the Istio RFC 'Istio and MCS' document, it mentions multi-network support. Is this still on a road map?

Apologies if I'm missing some documentation somewhere.

Thanks,

Andy

**Comment by howardjohn** [comment]
It has stagnated for a bit but seems to be picking up some momentum recently, although nothing concrete yet so I don't have much more info than that.

**Comment by andrwca** [comment]
Thanks, I appreciate the update!

**Comment by david-martin** [comment]
After a few different talks at kubecon EU earlier in the year talking about gateway api and sig-multicluster crossover, we're very interested in this capability in Istio.

Here's 1 of those talks https://www.youtube.com/watch?v=jd66OMad6TU&list=PLj6h78yzYM2PyrvCoOii4rAopBswfz1p7&index=105&pp=iAQB

**Comment by hzxuzhonghu** [comment]
By default, istio have a view of all clusters service, it means without MCS service discovery is available.

If you have set cluster local services, mcs can be used with istio.

**Comment by david-martin** [comment]
> istio have a view of all clusters service

Does this require istio to be running on every cluster?

**Comment by hzxuzhonghu** [comment]
Not a must. There is a mulcuster model called `primary-remote`. FYI https://istio.io/latest/docs/setup/install/multicluster/primary-remote/

**Comment by howardjohn** [comment]
> Hi, will mTLS work when using mutli cluster services? I noticed that whenever my mTLS mode is STRICT, connection fails even though the communicating pods in both clusters have the istio proxy enabled. (See full description here: https://stackoverflow.com/questions/76858998/how-to-enable-mtls-with-multicluster-service-on-gke)
> 
> PS: I am using Anthos Service Mesh, Managed Dataplane and Both clusters are in a fleet.

MCS is not enabled by default so Istio is probably not aware this is going to another pod in the cluster. From its POV its the same as if it went to example.com or whatever. Unknown traffic will passthrough which is probably what you see

**Comment by azunna1** [comment]
> > Hi, will mTLS work when using mutli cluster services? I noticed that whenever my mTLS mode is STRICT, connection fails even though the communicating pods in both clusters have the istio proxy enabled. (See full description here: https://stackoverflow.com/questions/76858998/how-to-enable-mtls-with-multicluster-service-on-gke)
> > PS: I am using Anthos Service Mesh, Managed Dataplane and Both clusters are in a fleet.
> 
> MCS is not enabled by default so Istio is probably not aware this is going to another pod in the cluster. From its POV its the same as if it went to example.com or whatever. Unknown traffic will passthrough which is probably what you see

I have multicluster service discovery enabled on the fleet so i'm a bit confused here. Give gke's implementation of MCS, with istio/anthos service mesh will the proxy sidecars be able to recognize that the traffic is coming form a pod that's part of the mesh even if the pod is in another cluster? 
For example in cluster A i have mTLS strict and an Auth Policy whitelist for pods in namespace A and C, if i make a request from pod A, namespace A to Pod B namespace B  it works fine as communication is established using mTLS and Pod A is authorized via the auth policy whitelist.
The question here now is if in cluster B, i want to communicate with service B, i export service B. I have pod C in cluster B which is also part of the mesh, but for some reason pod C traffic to service B traffic is denied by the strict mTLS policy. Additionally, with the authorization policy applied on namespace B in cluster A, the sidecar proxy does not recognize that the traffic is coming a whitelisted namespace, albeit from another cluster.

**Comment by howardjohn** [comment]
No, the GKE MCS is orthogonal to Istio's MCS.
