### ISSUE TITLE
Please publish "supported releases" information in a structured format (JSON, XML, YAML, RDFa, etc)

### ISSUE THREAD

**Issue by mindcrime** [istio/istio#44426]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I would like to see the Istio team publish the "supported releases" matrix, as seen in an HTML table here:

https://istio.io/latest/docs/releases/supported-releases/

as a structured file format (I don't really care what format, any of JSON, XML, YAML, etc would be fine I think) at a well known URL. This would allow us to easily import that information into a local database, where we would want to use it to help ensure that Istio versions are kept current and compatible, especially in the face of automatic upgrades of, eg AKS clusters.

**Describe alternatives you've considered**

We could scrape the page linked above and parse the data out of the HTML, but web scraping is notoriously brittle, as people who author web pages are not typically thinking about having any sort of "contract" with consumers who consume the page by scraping it. So pages tend to get reorganized, restyled, etc. in ways to break scrapers. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

N/A

**Comment by mindcrime** [comment]
Just to add another thought to this: another cool way to handle this might be with embedded RDFa. 

https://rdfa.info/
https://www.w3.org/TR/rdfa-primer/
https://en.wikipedia.org/wiki/RDFa

Then the endpoint could stay the same, but anybody trying to extract the compatibility matrix in a structured form would have a consistent way to do that without relying on css selectors, or arbitrary whims of the HTML layout.

**Comment by keithmattix** [comment]
https://github.com/istio/enhancements/blob/master/features.yaml is probably what you're looking for

**Comment by mindcrime** [comment]
> https://github.com/istio/enhancements/blob/master/features.yaml is probably what you're looking for

Thanks, that does look interesting and potentially useful, but in a different context.  For now, unless I'm missing something, that's not quite what I had in mind. I just want the matrix mapping Istio versions to the corresponding supported AKS versions, in some (any) structured format so it will be easy to import and use programmatically.

**Comment by mindcrime** [comment]
@keithmattix  - That said, you inspired me to dig deeper into the Istio repo(s) and I think I did actually find what I was looking for. It seems like the compatibility matrix is here in yaml format:

https://github.com/istio/istio.io/blob/master/data/compatibility/supportStatus.yml

I think this is exactly what I need.  I'll try to verify that everything I need is there, and if it is I can close this issue.

**Comment by keithmattix** [comment]
Ah yes i misread your initial issue. Glad you found what you're looking for though!

**Comment by ericvn** [comment]
I was going to ask if the work in https://github.com/istio/istio.io/pull/12834 didn't satisfy what you were looking for.

**Comment by mindcrime** [comment]
> I was going to ask if the work in [istio/istio.io#12834](https://github.com/istio/istio.io/pull/12834) didn't satisfy what you were looking for. We did cherry-pick that back to release-1.17 so it is used by istio.io as well as preliminary.istio.io

Yep, that looks like exactly what I need. I just wasn't aware that that existed when I first opened this.
