### ISSUE TITLE
Handle Envoy 1.26 breaking changes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44422]
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.26/v1.26.0

need to analyze and mitigate any changes

**Comment by howardjohn** [comment]
istio/proxy master already tracks envoy's master branch.

but in general you can override it with
`--override_repository=envoy=/path/to/envoy`

**Comment by ajpauwels** [comment]
So just to clarify:

1. Clone istio/proxy
2. Run `make build` (I'm running it with BUILD_WITH_CONTAINER=1)
3. Extract resulting envoy binary and use it with the Dockerfile at istio/istio:pilot/docker/Dockerfile.proxyv2
4. Push resulting proxyv2 image and override it in istio helm charts

Thanks for your help!

**Comment by howardjohn** [comment]
* Extensions moving/off by default: we should have updated all these
* validate_upstream_headers - we should see what changed. Users can set the flag if needed, but we probably want a release note.
* x-envoy-auth-failure-mode-allowed added when FailOpen is used on CUSTOM AuthorizationPolicy

**Comment by keithmattix** [comment]
Should we scrub that last header for requests outside of the mesh?

**Comment by howardjohn** [comment]
I think that is for sending to the ext_authz server which already has plenty of headers and doesn't need to be (and should not be) transparent?
