### ISSUE TITLE
source.principal attribute changed to null when upgraded to 1.17.2

### ISSUE THREAD

**Issue by JiaxingSong** [istio/istio#44432]
### Bug Description

After upgraded to istio 1.17.2, I found the source.principal attribute become empty when using AuthorizationPolicy and the request carrying a client certifacte with mTLS enabled on peer authutication.

According to the  public doc: https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source, this attribute should be identity dervied from peer certificate. In 1.16.4, the attribute is a valid identity, seems a breaking change?

### Version

```prose
istioctl version
client version: 1.12.5
control plane version: 1.17.2
data plane version: 1.17.2

kubectl version --short
Client Version: v1.22.1
Server Version: v1.24.9
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
cc @kyessenov may be from the new authn filter?

**Comment by kyessenov** [comment]
Can you elaborate where you see `source.principal` becoming empty? We have regression integration tests for authz policy. Does your client cert have multiple SANs?

**Comment by JiaxingSong** [comment]
> Can you elaborate where you see `source.principal` becoming empty? We have regression integration tests for authz policy. Does your client cert have multiple SANs?

I have an authz policy to check `source.principal`:

  - when:
    - key: source.principal
      notValues: ["*"]

In 1.16.4 this condition denied, in 1.17.2 it allows, and yes client cert have multiple SANs. @kyessenov

**Comment by kyessenov** [comment]
@JiaxingSong Right, the issue is the multiple SAN - SPIFFE is very clear about it, and that's not allowed "An X.509 SVID MUST contain exactly one URI SAN, and by extension, exactly one SPIFFE ID". There was a change in 1.17 to be stricter about it - otherwise, we were getting audit logs for a different principal than what authz policies used.
