### ISSUE TITLE
How to control isto proxy to run before the business container

### ISSUE THREAD

**Issue by 371873574** [istio/istio#44448]
### Bug Description

W0420 10:11:30.838973       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: failed to list *v1.CustomResourceDefinition: Get "https://10.233.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?limit=500&resourceVersion=0": dial tcp 10.233.0.1:443: connect: connection refused
E0420 10:11:30.839114       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: Get "https://10.233.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?limit=500&resourceVersion=0": dial tcp 10.233.0.1:443: connect: connection refused

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (3 proxies)
kubectl version --short
Client Version: v1.23.10
Server Version: v1.23.10
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
I'm not sure I understand the question just based on the title and logs. Usually, adding more information in the description will help you get faster responses; could you describe the scenario please?

**Comment by hzxuzhonghu** [comment]
please donot open duplicate issue

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/44387
