### ISSUE TITLE
TestReconnect failed race test

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4445]
https://circleci.com/gh/istio/istio/54399

==================
WARNING: DATA RACE
Write at 0x000002c0f760 by goroutine 56:
  istio.io/istio/pilot/pkg/proxy/envoy/v2.ldsPushAll()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds.go:166 +0x227
  istio.io/istio/pilot/pkg/proxy/envoy/v2.EdsPushAll()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:395 +0x34
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestReconnect()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds_test.go:78 +0x1b4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d

Previous read at 0x000002c0f760 by goroutine 322:
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).endpoints()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:122 +0x4f
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamEndpoints()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/eds.go:370 +0x604
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2._EndpointDiscoveryService_StreamEndpoints_Handler()
      /go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/eds.pb.go:253 +0xd2
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1052 +0x1298
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1146 +0x12f8
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:637 +0xac

Goroutine 56 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:824 +0x564
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1063 +0xa4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1061 +0x4e1
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:978 +0x2cd
  main.main()
      _testmain.go:46 +0x22a

Goroutine 322 (running) created at:
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:635 +0xb8
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:387 +0x1416
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:419 +0x648
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:633 +0x16e
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:590 +0x53
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:598 +0x34
==================
2018-03-21T22:48:54.335944Z	info	EDS RES for sidecar~a~b~c-2 "127.0.0.1:48006" clusters [hello.default.svc.cluster.local|http], Response: 
version_info:"2" resources:<type_url:"type.googleapis.com/envoy.api.v2.ClusterLoadAssignment" value:"\n$hello.default.svc.cluster.local|http\022;\n\r\022\013zone/region\022\024\n\022\n\020\n\016\022\01010.1.1.0\030P0\001\022\024\n\022\n\020\n\016\022\01010.1.1.1\030P0\001" > type_url:"type.googleapis.com/envoy.api.v2.ClusterLoadAssignment" nonce:"2-2018-03-21 22:48:54.335371795 +0000 UTC m=+6.059857169" 

--- FAIL: TestReconnect (5.47s)

**Comment by xiaolanz** [comment]
block #4235

**Comment by ostromart** [comment]
Another change made it in before PR above that also fixes this issue.

**Comment by xiaolanz** [comment]
@ostromart can you reference to the other PR here? Thanks

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/4475
