### ISSUE TITLE
EnvoyFilter not generating the config for RouteMatch with dynamic_metadata

### ISSUE THREAD

**Issue by gupta-deeptig** [istio/istio#44460]
### Bug Description

I want to add routing rules in HTTP router filter so we can forward traffic to a cluster based on custom data ( which is set by a custom http-filter as a metadata in the stream). This works in envoy using the following config:

```routes:
               - match:
                   prefix: "/test-domain-2"
                   dynamic_metadata:
                     filter: envoy.filters.http.router
                     path:
                       key: clientId
                     value:
                       string_match:
                         prefix: client1
                 route:
                   cluster: client1-gateway-upstream-domain1
               - match:
                   prefix: "/test-domain-2"
                   dynamic_metadata:
                     filter: envoy.filters.http.router
                     path:
                       key: clientId
                     value:
                       string_match:
                         prefix: client2
                 route:
                   cluster: client2-gateway-upstream-domain1
```

Trying to generate this using EnvoyFilter in Istio fails with error:
```
kubectl apply -f ./temp_test.yaml
Error from server: error when creating "./temp_test.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: json: cannot unmarshal object into Go value of type []json.RawMessage
```

EnvoyFilter

- applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            name: "hello.test:443"
      patch:
        operation: INSERT_FIRST
        value:
          name: "r-cl2"
          match:
            prefix: "/test-domain-2"
            case_sensitive: false
            dynamic_metadata:
              filter: envoy.filters.http.router
              path:
                key: clientId
              value:
                string_match:
                  prefix: client2
          route:
            cluster: outbound|443|client2|hello.test

istioctl validate -f ./temp_test.yaml
"./temp_test.yaml" has warnings: 
	* EnvoyFilter/istio-ingress/hello-test-cert-http: Envoy filter: unknown field "dynamic_metadata" in envoy.config.route.v3.RouteMatch

Tried after removing the metadata part and the route gets added.

Is dynamic_metadata match in EnvoyFilter not supported? Anything i am missin here?

### Version

```prose
client version: 1.10.0
control plane version: 1.17.2
data plane version: 1.17-dev (1 proxies)

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
Please refer https://istio.io/latest/docs/reference/config/networking/envoy-filter/ for correct format

**Comment by gupta-deeptig** [comment]
> Please refer https://istio.io/latest/docs/reference/config/networking/envoy-filter/ for correct format

Yes, that’s where I started. The route insertion works fine without the “dynamic metadata” part added in the match and fails when I add this

**Comment by gupta-deeptig** [comment]
looks like a json conversion thing..This worked..

```
dynamic_metadata:
              - filter: envoy.filters.http.router
                path:
                  - key: clientIdentity
                value:
                  string_match:
                    prefix: client1
```
