### ISSUE TITLE
Add integration test for ambient eBPF redirection

### ISSUE THREAD

**Issue by PlatformLC** [istio/istio#44466]
Add integration test for ambient eBPF redirection

**Comment by bleggett** [comment]
Pref would be to do what @PlatformLC already mentioned in #44435 

- Re-run the existing ambient integ suite with a different install config, as a separate Prow job, via an additional `istio.test` flag.

We might want to redo some of the `istio.test` flags a bit - we have `istio.test.cni` (which assumes iptables) and `istio.test.ambient`

Could add something like `istio.test.ambientebpf` as a new/additional flag, or we could rework `istio.test.cni` to be something like `istio.test.cni = ebpf` and `istio.test.cni = iptables`

**Comment by PlatformLC** [comment]
@bleggett How about using an ENV variable (e.g.` AMBIENT_REDIRECT_MODE="ebpf"`) to detect ebpf or iptables desired instead of test flag?  
With this, we could leverage most existing cases and just need prow job file to add specific env variable.

**Comment by bleggett** [comment]
> @bleggett How about using an ENV variable (e.g.` AMBIENT_REDIRECT_MODE="ebpf"`) to detect ebpf or iptables desired instead of test flag? With this, we could leverage most existing cases and just need prow job file to add specific env variable.

Either would work, I don't have much of a preference. A CLI flag is a little more explicit and obvious and would also allow reusing existing use cases.

**Comment by keithmattix** [comment]
Not stale
