### ISSUE TITLE
Internal service registries are not updated when a cluster disconnects

### ISSUE THREAD

**Issue by andrwca** [istio/istio#44467]
### Bug Description

Hi,

We've got a use case, where clusters are dynamically added and removed within a mesh. Within these clusters, we expect to name services uniquely to avoid load balancing. (We need to aggregate data from all services within a mesh, rather than load balance between them.)

We're at the point where our clusters can be added dynamically, and the services on remote clusters can be called successfully. 

The problem we have is when a cluster is removed and disconnected from the mesh.

In this case, we expect the services on the removed clusters to be removed from the internal service registry and synced between Pilot and Envoy. This would allow a remaining cluster to know that the services on the disconnected cluster are no longer available.

Instead, we find that Pilot isn't notified of the disconnected cluster, and consequently the services on that disconnected cluster are still in the internal service registry.

The problem is that the internal service registry appears to be the only place we can get a list of available services across the whole mesh, and we use this information as a list of data sources.

To recreate this, you can connect two clusters (east and west) following the Istio multi-cluster, multi-network documentation and enabling [DNS proxying](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/). In east, add and expose a service. Note that in west, this service can be seen using:

```istioctl proxy-config endpoints <pod>```

Disconnect east and re-run the command. Note that the endpoint is still present.

Would this be a missing feature or an issue? (Apologies if I've filed this in the wrong area!)

Or if there's a way to enable disconnected cluster notification/handling, that'd be perfect.

In terms of work arounds, we're considering extending our own operator to run health checks on connected clusters to identify when a cluster is disconnected, and force an update of the service registry ourselves.

It looks like this could work, but would you recommend other options?

Thanks a lot,

Andy

### Version

```prose
> istioctl version
client version: 1.17.2
control plane version: 1.17.1
data plane version: 1.17.1 (2 proxies)

> kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.24.10

>  helm version --short
v3.11.3+g3232493
```

### Additional Information

Target cluster context: REDACTED

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-04-21 07:10:51.204960373 +0000 UTC

Cluster endpoint: REDACTED
CLI version:
version.BuildInfo{Version:"1.17.2", GitRevision:"3e857775086a061d12ee445f32a0b35ea17c8488", GolangVersion:"go1.20.2", BuildStatus:"Clean", GitTag:"1.17.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.17.1", GitRevision:"7d6d2adacf8dcee110a48450d537f8ad26c7225f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.1}

Fetching proxy logs for the following containers:

gatekeeper-system/gatekeeper-audit/gatekeeper-audit-584d598c78-76vrr/gatekeeper-audit-container
gatekeeper-system/gatekeeper-controller/gatekeeper-controller-8684d59cc8-dp89x/gatekeeper-controller-container
gatekeeper-system/gatekeeper-controller/gatekeeper-controller-8684d59cc8-zgnh7/gatekeeper-controller-container
istio-system/istio-ingressgateway/istio-ingressgateway-78f764f86c-cl7gt/istio-proxy
istio-system/istiod/istiod-679bbcf55-rss78/discovery
sample/sleep/sleep-54bd49b487-zrhdv/istio-proxy
sample/sleep/sleep-54bd49b487-zrhdv/sleep

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace gatekeeper-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace gatekeeper-system istio-injection=enabled' to enable it, or 'kubectl label namespace gatekeeper-system istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /workspaces/mesh-connect/mesh-connect-operator/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

Additional details available on request.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Just to be clear, what exactly is "disconnect" here? Remove the kubeconfig Secret?

**Comment by andrwca** [comment]
@howardjohn, fair question and sorry for the delay! 

In our scenario, we're following the multi-primary and multi-network scenario. In this case, each cluster is in it's own disconnected network until we peer the networks together. Once peered, we can create remote secrets and join them, access each others services, etc.

Disconnect is when we remote the peering between the networks, so simulate a cluster leaving the network entirely. The kubeconfig secret will will be present on both clusters.

Does that help?

**Comment by howardjohn** [comment]
From Istio perspective, if you just remove network access the cluster is not removed. Its just not reachable, which is seen as a transient error that is retried. Istio is designed to be resilient to transient control plane errors and will retain the last known state. If you want to remove the cluster you should tell Istio by removing the kubeconfig

**Comment by andrwca** [comment]
Got it. I appreciate our scenario is a little niche and your explanation makes sense. It sounds like our approach to add our own cluster health monitoring and updating the kubeconfig secret is the best way forward.
