### ISSUE TITLE
[Ansible Installer] Bookinfo is not working with TLS

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#4447]
## Summary 
- After Cloning 

``git clone https://github.com/istio/istio``

and executing playbook:

``ansible-playbook main.yml -e '{"istio": {"release_tag_name": "0.6.0", "auth": true, "delete_resources": true, "addon": ["grafana", "prometheus", "jaeger"], "samples": ["bookinfo"]}}``

after product page pod came up well
![image](https://user-images.githubusercontent.com/2313749/37744508-4ac477c8-2d4e-11e8-84c3-55997a1140e7.png)

``oc describe deployment productpage-v1``

> Name:                   productpage-v1
Namespace:              bookinfo
CreationTimestamp:      Wed, 21 Mar 2018 18:42:07 -0300
Labels:                 app=productpage
                        version=v1
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"name":"productpage-v1","namespace":"booki...
Selector:               app=productpage,version=v1
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:       app=productpage
                version=v1
  Annotations:  sidecar.istio.io/status={"version":"1e8f480eee0d2c455cb96c4acc9a723ca2b4bff32a7837e65787a5ef6853c820","initContainers":["istio-init","enable-core-dump"],"containers":["istio-proxy"],"volumes":["istio-...
  Init Containers:
   istio-init:
    Image:      docker.io/istio/proxy_init:0.6.0
    Port:       <none>
    Args:
      -p
      15001
      -u
      1337
    Environment:        <none>
    Mounts:             <none>
   enable-core-dump:
    Image:      alpine
    Port:       <none>
    Command:
      /bin/sh
    Args:
      -c
      sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c unlimited
    Environment:        <none>
    Mounts:             <none>
  Containers:
   productpage:
    Image:              istio/examples-bookinfo-productpage-v1:1.5.0
    Port:               9080/TCP
    Environment:        <none>
    Mounts:             <none>
   istio-proxy:
    Image:      docker.io/istio/proxy:0.6.0
    Port:       <none>
    Args:
      proxy
      sidecar
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      productpage
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15003
      --discoveryRefreshDelay
      1s
      --zipkinAddress
      zipkin.istio-system:9411
      --connectTimeout
      10s
      --statsdUdpAddress
      istio-mixer.istio-system:9125
      --proxyAdminPort
      15000
      --controlPlaneAuthPolicy
      MUTUAL_TLS
    Environment:
      POD_NAME:          (v1:metadata.name)
      POD_NAMESPACE:     (v1:metadata.namespace)
      INSTANCE_IP:       (v1:status.podIP)
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
  Volumes:
   istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
   istio-certs:
    Type:       Secret (a volume populated by a Secret)
    SecretName: istio.default
    Optional:   true
Conditions:
  Type          Status  Reason
  Available     True    MinimumReplicasAvailable
OldReplicaSets: productpage-v1-394065063 (1/1 replicas created)
NewReplicaSet:  <none>
Events:         <none>

but I didn't get any response:

![image](https://user-images.githubusercontent.com/2313749/37744910-99780040-2d50-11e8-893c-7a31fcf99d04.png)

**Comment by gbaufake** [comment]
Any news on this issue?

**Comment by hhovsepy** [comment]
Problem still happening with Istio 0.8.0

**Comment by hhovsepy** [comment]
any news on this issue?

**Comment by knrc** [comment]
@hhovsepy We have managed to get this deployed both with and without mTLS, the confusing aspect is likely the separate gateway/virtualservice needed to expose the productpage since that is in a separate directory (routing) if using v1alpha3.  It is documented however perhaps this can be consolidated/simplified for 1.0 with the removal of Ingress etc.
