### ISSUE TITLE
Always encounter 401 Unauthorized error message when validating ingress routing based on JWT claims

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#44488]
### Bug Description

I followed the documentation [here](https://istio.io/latest/docs/tasks/security/authentication/jwt-route/#validating-ingress-routing-based-on-jwt-claims), and I still encountered the `401 Unauthorized Error` even after I set the `TOKEN_GROUP` based on the doc.
And the outputs, including the error message, are below:

```
$ TOKEN_GROUP=$(curl https://raw.githubusercontent.com/istio/istio/release-1.17/security/tools/jwt/samples/groups-scope.jwt -s) && echo "$TOKEN_GROUP" | cut -d '.' -f2 - | base64 --decode -
$ {"exp":4685989700,"foo":"bar","iat":1532389700,"iss":"testing@secure.istio.io","sub":"testing@secure.istio.io"}
$ curl -s -I "http://$INGRESS_HOST:$INGRESS_PORT/headers" -H "Authorization: Bearer $TOKEN_GROUP"
HTTP/1.1 401 Unauthorized
www-authenticate: Bearer realm="http://10.0.2.15:32063/headers", error="invalid_token"
content-length: 50
content-type: text/plain
date: Mon, 24 Apr 2023 10:52:36 GMT
server: istio-envoy
```

Similar error message when checking end-user authentication based on [doc](End-user authentication). Moreover, I doubt that there may be the same error for request authentication policy that requires end-user JWT for the ingress gateway.

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (2 proxies)

$ kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by aryan16** [comment]
can you share the spec of ReqAuth policies which you applied. And, please check the Istiod logs as well.

**Comment by zhlsunshine** [comment]
Hi @aryan16, I followed the doc and no any extra or custom activity. You may reproduce it easily by following the doc.

**Comment by bochengchu** [comment]
I followed the doc and it works well for me.

**Comment by aryan16** [comment]
@zhlsunshine we have e2e tests successfully running for this feature as well. Please double check your configs, there should be something wrong with that.
e2e tests - https://github.com/istio/istio/blob/master/tests/integration/pilot/common/routing.go#L3283

**Comment by zhlsunshine** [comment]
Hi @aryan16, I am still focusing on reproducing this bug, I will close this issue if it's okay. thanks!
