### ISSUE TITLE
Outlier detection interval not working as expected in Istio traffic policy configuration

### ISSUE THREAD

**Issue by BharathKumarRavichandran** [istio/istio#44493]
### Bug Description

Hi folks!

We are planning to use outlier detection in traffic policy, but the interval field does not seem to be working as expected. The definition of the interval is the time interval between ejection sweep analysis, which means unhealthy hosts are ejected if the number of 5xx errors is greater than the configured consecutive 5xxErrors value consecutively when the sweep analysis is performed after the current interval. This is what we expected.

Our configuration:
```
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 60s
      consecutive5xxErrors: 2
      interval: 60m
      maxEjectionPercent: 100
```

Expected:
We've set the interval to 60 minutes, which we believe means that as long as the 5xx errors occur within that interval, the host won't be ejected. Technically, ten or more consecutive 500 can be made definitely within the 60m if the calls are made with an interval of 1 second. 

Observations:
However, when we tested the policy by sending four consecutive 5xx errors with a one-second gap between them, the host was ejected. We expected that the interval would allow for more than four consecutive 5xx errors to occur before the host would be ejected.

We believe it is an issue, if not can you clarify the definition of the interval field and whether our understanding is correct?

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.16-dev
data plane version: 1.16-dev (44 proxies)

$ kubectl version --short
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by ramaraochavali** [comment]
That interval is mostly used for "uneject" - brining service back to load balancer after base ejection time is over. Host is ejected immediately after it hits the consecutive5xx count.

**Comment by BharathKumarRavichandran** [comment]
Thank you! So, will the circuit be closed after the total baseEjectionTime + interval? I don't really understand the role of interval here. 

Also, this was not specified anywhere in the docs. As per the docs, we thought interval was only used for sweep analysis. I think the doc needs an update -> https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection

**Comment by ramaraochavali** [comment]
> So, will the circuit be closed after the total baseEjectionTime + interval

The interval is used mainly to see if after base ejection time to see if the host can be brought back (if all requests are successful during the ejection period)

**Comment by BharathKumarRavichandran** [comment]
You mean, during the ejection period, even though we get 503 since the host is ejected, Istio still makes the call and keeps track of the responses that it will use during the interval after the ejection period?

**Comment by ramaraochavali** [comment]
I meant the "interval" is used in the following cases
- For some type of ejection (like success rate based ejections that Envoy supports), whether to eject a host or not . For ejections like consecutive5xx the host is ejected immediately. For success rate based ejections, the host would be ejected at that interval if it meets the criteria
- Once a host is ejected, to check whether ejection interval is passed and if yes, to uneject the host.

**Comment by BharathKumarRavichandran** [comment]
I'm more interested in knowing about the second case. As far as I understand, Istio will eject the host as soon as the consecutive5xxErrors value is hit. Then once base ejection time is passed, it will uneject the host. Can you explain more about where the interval is used here? I think I didn't get it.

**Comment by ramaraochavali** [comment]
> Then once base ejection time is passed, it will uneject the host.

This wont happen immediately when base ejection time is passed. The check is done at interval to see if the host has passed ejection time. Please refer here https://github.com/envoyproxy/envoy/blob/bc1d7d442c833e29f3cb849af5ee9c469be1f08c/source/common/upstream/outlier_detection_impl.cc#L746 for more details on what is done on interval

**Comment by BharathKumarRavichandran** [comment]
Thank you very much for your time. We validated the above, and it is working as explained in your comment.
