### ISSUE TITLE
Existing pods cannot be added to the ambient mesh network

### ISSUE THREAD

**Issue by yuri-lcy** [istio/istio#44494]
### Bug Description

Uninstall ambient, then reinstall ambient, the previous pod cannot be added to the mesh network.
Because when the ambient is uninstalled, the pod annotations[ambient.istio.io/redirection] has not been changed, it is still enabled. This led to an error in the logic of the judgment in this place, and it was skipped directly.

![image](https://user-images.githubusercontent.com/114134743/233928647-78cdf6e2-73b9-4d16-be4c-ccdffb91f999.png)

If this is a bug, can you assign this issue to me and I'll try to fix it.

### Version

```Text
master ambient mode
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
I think https://github.com/istio/istio/pull/44276 handles this

**Comment by taoyuanyuan** [comment]
I have the same problem, and I do it temporarily. 
```
kubectl annotate notsleep-6d6c8669b5-rkjhp ambient.istio.io/redirection-
```
