### ISSUE TITLE
failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/

### ISSUE THREAD

**Issue by krishnasingh1818** [istio/istio#44507]
### Bug Description
We are trying to uprade istio after upgrading aks.  Things are working fine but when we navigate to istio-operator it status is show as "error" and inside yml it says below error about hpa  and v2beta1.  When we generate the manifest it generates yml properly with autoscaling/v1
istioctl manifest generate > 1.yaml 
![image](https://user-images.githubusercontent.com/10679463/234112020-0152a401-e0b0-44c9-8d45-d0ba4956bcfe.png)

```
     status: HEALTHY                                                                                                                              │     IngressGateways:                                                                                                                            
│       error: 'failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway:               │         no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"'                                                         
│       status: ERROR 

                                                                                                                            
│     Pilot:                                                                                                                                      │       error: 'failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod:                             
│         no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"'                                                         │       status: ERROR                                                                                                                             
│   status: ERROR
```

> 

### Version

```Text
istioctl 1.17.2

kubectl 
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.25.6

helm version
3.11.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Which operator version are you using? It should match the Istio version you want to upgrade to.

**Comment by krishnasingh1818** [comment]
we did istio operator init to 1.17.2 and it shows on that version. all stuff seem working but istio operator status is showing "error"
![image](https://user-images.githubusercontent.com/10679463/234693152-796289c2-b1c2-4dcf-a5aa-142be3bedb51.png)
and describe shows this.
![image](https://user-images.githubusercontent.com/10679463/234693209-15c025aa-fa02-41f4-976f-199d6dd48b09.png)

**Comment by stevehipwell** [comment]
We're also seeing this issue.

**Comment by stevehipwell** [comment]
It looks like the docs are missing `global.autoscalingv2API`, but we also had to switch the HPA pattern we were using which I haven't seen specific documentation for.

**Comment by krishnasingh1818** [comment]
Did anyone able to find fix for this case ? pls share details if there any fix or workaround of this issue.

**Comment by hanxiaop** [comment]
Can you provide the iop setting?

**Comment by krishnasingh1818** [comment]
> 



> Can you provide the iop setting?

could u pls advice where to find those ? thank you !

**Comment by slucheninov** [comment]
[Solution](https://github.com/istio/istio/issues/41262#issuecomment-1434662662)

**Comment by neno13453** [comment]
Same issue here. We tried Istio v1.17.2 and v1.18.2 both not working on Kubernetes v1.26
`19:57:37  - Processing resources for Istiod.2023-08-17T12:57:36.436071Z	error	installer	failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"`
