### ISSUE TITLE
TestStackdriverHTTPAuditLogging test flake (regression?)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44503]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44497/integ-telemetry-mc_istio/1650530573908709376

I have seen 3 failures this week, seems a new flake.

cc @zirain @kyessenov @lei-tang

**Comment by kyessenov** [comment]
There's been no changes to stackdriver in the last few months. It might be a flake, but not because of stackdriver.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44501/integ-telemetry-mc_istio/1650564904064651264 is another example. Definitely a regression from some source. Marking as 1.18 release blocker

**Comment by zirain** [comment]
I canot recall any changes related to stackdriver, after quick look at logs, seems related something about network?
```
common.go:392:   for label "labels.source_canonical_service", wanted "clt-cross-network-primary" but got "clt-remote"
    common.go:392:   for label "labels.source_app", wanted "clt-cross-network-primary" but got "clt-remote"
    common.go:392:   for label "labels.source_workload", wanted "clt-cross-network-primary-v1" but got "clt-remote-v1"
    common.go:392:   for label "http.RequestUrl", wanted "http://srv.istio-echo-1-79432.svc.cluster.local/foo" but got "http://srv.istio-echo-1-79432.svc.cluster.local/bar"
```

**Comment by howardjohn** [comment]
seems to be calm now with https://github.com/istio/istio/pull/44639
