### ISSUE TITLE
istioctl kube-inject donot support helm variable

### ISSUE THREAD

**Issue by aimuke** [istio/istio#4451]
We use helm to manage our app. Can kube-inject supports helm?

There are some variables in deployment as below:
````
containers:
   - args:
     image: {{ .Values.image.consul }}
````

When we use istioctl kube-inject on this deployment, there will be an error as : 
````
Error: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {{".Values.image.consul":interface {}(nil)}
````

Will kube-inject support helm and variables?

**Comment by yusuoh** [comment]
We have a helm chart for automatic sidecar injection, which supports parameterized image.

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/sidecar-injector/templates/configmap.yaml

I think you can create the configmap with your custom settings. istioctl will use the configmap to inject sidecar proxy.

**Comment by ayj** [comment]
We don't have any plans to support running `kube-inject` over helm templates.
