### ISSUE TITLE
telemetry: move to OpenTelemetry lib

### ISSUE THREAD

**Issue by zirain** [istio/istio#44513]
[opencensus-go](https://github.com/census-instrumentation/opencensus-go) announced for deprecated for a long time, should Istio move to use OpenTelemetry lib?

see project status [here](https://github.com/open-telemetry/opentelemetry-go#project-status)

cc @howardjohn @lei-tang @kyessenov

**Comment by lei-tang** [comment]
Yes, Istio should move to use OpenTelemetry lib.

**Comment by howardjohn** [comment]
Please benchmark before we commit. Istiod metrics used to use 25% of total CPU due to poor implementation

**Comment by kyessenov** [comment]
@lei-tang Does otel-go support stackdriver export? That was the primary reason for using opencensus without an exporter.

@howardjohn Was that a fundamental issue with cardinality or poor implementation?

**Comment by lei-tang** [comment]
For tracing: https://pkg.go.dev/go.opentelemetry.io/otel/exporter/trace/stackdriver.

For metrics: https://pkg.go.dev/go.opentelemetry.io/otel/exporter shows the support for Prometheus, but not for stackdriver.

**Comment by kyessenov** [comment]
Right, @lei-tang - I agree that we want to remove an opencensus dependency, but we should make sure we can ingest it. Prometheus or otel collectors are not free to run.

**Comment by zirain** [comment]
cc @kyessenov https://github.com/open-telemetry/opentelemetry-go/blob/main/example/opencensus/main.go

**Comment by howardjohn** [comment]
> Was that a fundamental issue with cardinality or poor implementation?

@kyessenov it was just bad implemention, both in opencensus and our own usage.

**Comment by kyessenov** [comment]
@zirain This is different - this is OpenCensus protocol export to an OpenCensus collector. The problem is that Google doesn't use prometheus for metrics, so Google maintainers should make sure that metrics are still available via otel SDK - whatever that means.

**Comment by zirain** [comment]
OpemTelemetry is the next major version of OpenCensus, I believe it's supported.
I donot know the details about how Google use it, will this be a block for changing the implement of `istio.io/pkg/monitoring`?
