### ISSUE TITLE
Ztunnel hairpinning to waypoint - wrong identity initiated

### ISSUE THREAD

**Issue by yuval-k** [istio/istio#44530]
### Bug Description

Scenario:
when pod not in the mesh connects to a pod in the mesh and the mesh pod  has a waypoint.

What happens:
- Destination ztunnel hairpins and connects to the waypoint
- ztunnel tries to connect to the waypoint using the source pod identity.
- istiod refuses to sign the cert, as the source pod is not in the destination ztunnel's node
 
As the istiod behaviour is correct, we shouldn't have the destination ztunnel try to initiate connections on behave of the source pod's identity.

It should probably use the destination pod's service account, as the destination ztunnel represents the server, not the client. The problem with that, is that the waypoint will see the client's identity as destination's pod identity, where it should address this as coming from an unknown identity (as the source pod is not in the mesh).

Perhaps when hair-pinning we should do a plain tcp proxy to the waypoint (instead of mTLS)?

### Version

```Text
1.18.0-alpha.0
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
Is this still occurring? This seems tricky because the current documentation on the waypoint says that ALL connections to the waypoint are under mTLS. I'm wary of the ztunnel presenting untrusted traffic as trusted...should L7 policies just only apply for tunneled traffic?

**Comment by linsun** [comment]
Steven is writing a short doc on this, plan to present soon

**Comment by stevenctl** [comment]
https://docs.google.com/document/d/1uM1c3zzoehiijh1ZpZuJ1-SzuVVupenv8r5yuCaFshs/

**Comment by keithmattix** [comment]
Consensus from 09/06 Ambient meeting: Hairpinning will be done via Plain H2 TLS on outbound leg (no srcid), HBONE on inbound leg (zt dstID) -> effectively Option 3 from the [ztunnel hairpinning doc](https://docs.google.com/document/d/1uM1c3zzoehiijh1ZpZuJ1-SzuVVupenv8r5yuCaFshs/edit)

**Comment by linsun** [comment]
Hi @yuval-k @stevenctl @keithmattix @louiscryan @howardjohn saw this issue in drive ambient to beta doc - is this issue still relevant with network policy enforcing traffic going to waypoint and decline unknown identity?

**Comment by howardjohn** [comment]
This will be fixed by removing hairpinning as part of https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit#heading=h.er7ajjjlw2f3 I think?

**Comment by ilrudie** [comment]
https://github.com/istio/ztunnel/pull/913 removed hairpin
