### ISSUE TITLE
istio-sidecar：loadbalance type service，why request is pass through sidecar

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#44555]
I have a question。I have a micro-service，it's servcie type is loadbalance and set istio-inject true for namesoace. When i use loadbalance url which is show in service.yaml status.loadBalancer.ingress.hostname to request my service，i can see a inbound log in istio-proxy。

service.yaml:
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app.kubernetes.io/name: test
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxx.com

istio-proxy log：
"POST /v1/event HTTP/1.1" 200 - via_upstream - "-" 68534 90 976 461 "-" "-" "-" "xxx.com" "xx.xx.xx.xx:8080" inbound|8080|| 127.0.0.6:39539 xx.xx.xx.xx:8080 xx.xx.xx.xx:42041 - default

istio version: 1.16.2
k8s version: 1.24

question:
why my request is use loadbalance url  but it pass through sidecar?

**Comment by howardjohn** [comment]
My understanding is the flow is 

`client --LoadBalancer hostname for "test"--->test-sidecar --->test pod`

?

And you are wondering why test-sidecar captures it? If so, that is just how Istio works, all traffic to a pod hits the sidecar

**Comment by id-id-id** [comment]
来信已收到，祝好！

**Comment by id-id-id** [comment]
Judging from the current performance in istio 1.16.2 the flow look likes 
client --LoadBalancer hostname for "test"--->test-sidecar --->test pod

I am upgrading isito version recently， from 1.4.7 to 1.16.2.  In istio 1.4.7, the same request look like not passthrough sidecar, i can not find inbound log in istio-envoy. I want to know when was this different introduced.

**Comment by howardjohn** [comment]
Long ago we changed to capture all traffic instead of inly some ports

**Comment by id-id-id** [comment]
all traffic include hostport？  I define a  hostport for test， i use node ip and hostport to request test, i find this request is capture by sidecar.

Can i find some message from istio relase about change capture all traffic instead if inly some ports

**Comment by howardjohn** [comment]
If you look through the ~4 year. old release notes you'll find it.

**Comment by zirain** [comment]
IIRC, it's changed before v1.8

**Comment by id-id-id** [comment]
we use LoadBalancer hostname for "test" to request test and find in response header upppercase has been changed to lowercase in istio 1.16.2 like X-token is changed to x-token， but in 1.4.7 that‘s not happen.  Does this performance associate with the change of istio capture all traffic?

**Comment by zirain** [comment]
>  in response header upppercase has been changed to lowercase in istio 1.16.2 like X-token is changed to x-token

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#http-1-1-header-casing

**Comment by id-id-id** [comment]
I know envoy filter will change header casing. Just because the same request is different in different istio versions, I want to confirm the reason for the difference.  Can I assume that this difference is caused by  capture all traffic instead of inly some ports mentioned earlier
