### ISSUE TITLE
RouteRule resolution bugs

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4457]
A number of route rule bugs reported:

Precedence issue:
https://groups.google.com/d/msg/istio-users/zSSmxn-MyHk/umwKzF2hAgAJ
https://groups.google.com/d/msg/istio-users/kUwYJ-1Da5I/YsxEGl5WAgAJ

Matcher issue:
https://groups.google.com/d/msg/istio-users/GH5VpYag_m8/JepDgoXlAQAJ

**Comment by andraxylia** [comment]
They can be fixed in the alpha3 version only, but we must tests these specific use cases.

**Comment by Dmitry1987** [comment]
@andraxylia I have an issue created earlier too, it is here  https://github.com/istio/issues/issues/237

**Comment by ZackButcher** [comment]
Given we've sunset the v1alpha1 APIs and they will be removed in our next release, I don't think we'll be fixing this. Part of the reason we introduced VirtualService (which is essentially an aggregated RouteRule) is to avoid these sticky issues relating to precedence and plumbing it through Pilot's config gen.
