### ISSUE TITLE
istio.io/istio/tests/e2e/tests/upgrade.TestUpgrade failure

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4459]
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/1128

It seems never passing yet.

**Comment by yusuoh** [comment]
CC @chxchx

**Comment by yusuoh** [comment]
Seems to be failing on this line. Maybe we should increase the time for waiting for pods to be reloaded.

I0322 16:49:49.528] 2018-03-22T16:49:49.528013Z	error	Failed to upgrade sidecars.. Error can't get all pods running

**Comment by yusuoh** [comment]
#4472

**Comment by yusuoh** [comment]
The test is passing now. 

https://k8s-testgrid.appspot.com/istio#e2e-suite-rbac-auth
