### ISSUE TITLE
Wrong destination_service_name in metrics proxyv2 1.17.0

### ISSUE THREAD

**Issue by alt-dima** [istio/istio#44602]
### Bug Description

Hello!
After update Istio from 1.16.4 to 1.17.0 I do see, that `destination_service_name` in the proxyv2 metrics was changed. It affects Kiali service map.

We use ServiceEntry with hosts like `*.example.service.consul` with WorkloadSelector points (by labels) to the original service `example`

In proxyv2 ver 1.16.4 `destination_service_name` was = `*.example.service.consul`
In proxyv2 ver 1.17.0 `destination_service_name` = `*` (for all the services!)

If I start some pod with proxyv2 ver 1.16.4 (and istio CP 1.17.0), then metrics (for this pod) goes back to normal.
v.1.16.4
![image](https://user-images.githubusercontent.com/91941355/234820943-a6b7c320-60d9-4ed5-927f-113e62fbed43.png)
v.1.17.0
![image](https://user-images.githubusercontent.com/91941355/234820978-d121514d-0d40-49cc-ad0e-e2362fb16c61.png)

### Version

```Text
istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.16.4 (1 proxies), 1.17.2 (306 proxies)

kubectl version --short
Client Version: v1.23.17
Server Version: v1.24.10-eks-48e63af

helm charts
istio-base 1.17.2
istiod 1.17.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by alt-dima** [comment]
Probably it maybe related to Envoy (in proxyv2) update to 1.25.
But i can't find in the code where metrics are being populated.

As I see, bootstrap (metrics config) was not changed in 1.16>1.17

**Comment by zirain** [comment]
cc @kyessenov related to the refactor of stats filter?

**Comment by kyessenov** [comment]
Yeah, probably. Will look into it.

**Comment by kyessenov** [comment]
Can you dump your EDS please with `config_dump?include_eds=y`? I think we set "name"  in "istio.services" metadata to be FQ which is why the difference happens.

**Comment by alt-dima** [comment]
Checked (1.16.4 vs 1.17.2) it is the same
![image](https://user-images.githubusercontent.com/91941355/234957332-1fa9c9d5-6c97-488c-9bff-e8ced14537f9.png)
probably thats why `destination_service="*.billing-payment-service.service.consul"` but `destination_service_name="*"`
![image](https://user-images.githubusercontent.com/91941355/234957595-c19242ab-7508-4f59-83b4-78a5e4155e8a.png)

**Comment by alt-dima** [comment]
Sadly destination_service_name being used in Kiali and this how it looks like
![2023-04-27_21-30_1](https://user-images.githubusercontent.com/91941355/234958765-b239c93e-82f0-4eb9-9ada-94ac4f8cd00a.png)
![2023-04-27_21-30](https://user-images.githubusercontent.com/91941355/234958771-a9c8e9a7-fbd1-4ee2-9173-775581d1f148.png)
