### ISSUE TITLE
PILOT_ENABLE_STATUS causes excessive Istiod pushes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44613]
Each time we update the status, we trigger a push, causing excessive CPU usage

**Comment by keithmattix** [comment]
I may be misremembering, but isn't there a function that strips unnecessary fields before computing the push context? Could this be solved by just adding Status to that set?

**Comment by hanxiaop** [comment]
IIRC the status manager is frequently updated with unnecessary updates, I'll check it.

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale
