### ISSUE TITLE
Serve Istio CA as SPIFFE trust bundle

### ISSUE THREAD

**Issue by akevdmeer** [istio/istio#44629]
Istio supports retrieving SPIFFE trust bundles through `spiffeBundleUrl` in the mesh config, but does not offer a means to serve its CA as a trust bundle.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
cc @costinm @shankgan

**Comment by costinm** [comment]
+1

Also as well known jwk ( we may as well, in some cases we'll sign JWTs)

**Comment by keithmattix** [comment]
Not stale
