### ISSUE TITLE
TestAutoregistrationLifecycle test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44640]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44637/unit-tests-arm64_istio/1652049625789501440

**Comment by hanxiaop** [comment]
Still have test flake https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/45800/unit-tests-arm64_istio/1676413422809387008

**Comment by keithmattix** [comment]
Still seeing this on master

**Comment by howardjohn** [comment]
caused by #44709

**Comment by howardjohn** [comment]
Still broken. Going to revert the PR\

https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1727891160262774784

**Comment by howardjohn** [comment]
@stevenctl there is a merge conflict. Can you revert or fix the flake?

**Comment by stevenctl** [comment]
Will fix it today

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/47946/unit-tests-arm64_istio/1729648420215328768
