### ISSUE TITLE
DiscoverySelectors updates are broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44675]
Example test that fails:

```go

func TestNamespaceControllerDiscovery(t *testing.T) {
	test.SetForTest(t, &features.EnableEnhancedResourceScoping, true)
	client := kube.NewFakeClient()
	t.Cleanup(client.Shutdown)
	watcher := keycertbundle.NewWatcher()
	caBundle := []byte("caBundle")
	watcher.SetAndNotify(nil, nil, caBundle)
	meshWatcher := mesh.NewTestWatcher(&meshconfig.MeshConfig{
		DiscoverySelectors: []*metav1.LabelSelector{{
			MatchLabels: map[string]string{"kubernetes.io/metadata.name": "selected"},
		}},
	})
	discoveryNamespacesFilter := filter.NewDiscoveryNamespacesFilter(
		kclient.New[*v1.Namespace](client),
		meshWatcher.MeshConfig.DiscoverySelectors,
	)
	nc := NewNamespaceController(client, watcher, discoveryNamespacesFilter)
	stop := test.NewStop(t)
	client.RunAndWait(stop)
	go nc.Run(stop)
	retry.UntilOrFail(t, nc.queue.HasSynced)

	expectedData := map[string]string{
		constants.CACertNamespaceConfigMapDataName: string(caBundle),
	}
	createNamespace(t, client.Kube(), "not-selected", nil)
	createNamespace(t, client.Kube(), "selected", nil)
	expectConfigMap(t, nc.configmaps, CACertNamespaceConfigMap, "selected", expectedData)
	expectConfigMapNotExist(t, nc.configmaps, "not-selected")

	discoveryNamespacesFilter.SelectorsChanged([]*metav1.LabelSelector{{
		MatchLabels: map[string]string{"kubernetes.io/metadata.name": "not-selected"},
	}})
	expectConfigMap(t, nc.configmaps, CACertNamespaceConfigMap, "not-selected", expectedData)
	expectConfigMapNotExist(t, nc.configmaps, "selected")
}
```

There is no mechanism for discovery filter to signal changes. Instead, it is deeply coupled with kube controller. I think the whole interface needs to be reworked:

```go
type DiscoveryFilter interface {
  NamespaceFiltered(string) bool
  // Helper function for above to make calling easier
  ObjectFiltered(metav1.Object) bool
  AddHandler(func(namespace string))
}
```

The DiscoveryFilter itself should take in a mesh watcher and namespace informer instead of NamespaceCreated/SyncNamespaces/SelectorsChanged.

In kclient when we register an `ObjectFilter`, we should add a handler. This will be:

```go
filter.AddHandler(func (ns string) {
for _, item := range client.List(ns, klabels.Everything()) {
  if filter.NamespaceFiltered(ns) {
    CallHandlers(item, Delete)
  else {
    CallHandlers(item, Add)
  }
}
})
```

Note: we need to handle https://github.com/kubernetes/kubernetes/issues/117706

**Comment by hzxuzhonghu** [comment]
It need a refactor

**Comment by howardjohn** [comment]
One issue is we need to have the filter synced before we start running the informer. Otherwise we process everything and then _hopefully_ eventually remove it correctly. This is tricky with our current implementation, as we build all our informers (including the filter) then RunAndWait them all. With SharedInformerFactory its hard to start just a single informer - technically we can call Run() on the individual informer, but then it will not be registered with the factory and we will get spurious log of `The sharedIndexInformer has started, run more than once is not allowed`. Additionally, factory.Shutdown() will be broken since it won't properly wait for the informer.

We have a similar concern with https://github.com/istio/istio/pull/44145 in CRD watcher. In that case, its less-bad - its just a tiny performance cost and slight complexity if CRD is synced later (compared to here, where it may be massive cost).

if we consider both together, we end up with:


```mermaid
graph BT
  CRDWatcher
  NamespaceFilter
  ConfigClient--Depends-->CRDWatcher
  ConfigClient--Depends-->NamespaceFilter
  KubeController--Depends-->NamespaceFilter
```

Logically I think that leads to two approaches:
* Start CRD and namespace informers first and wait for them. This means we need to start them before we create **any** other informers. Possibly this is done in the kube.NewClient itself to make it easy to pass this around + impossible to mess up.
* Create all the informers as we do, but find a way to run only CRD + Namespace first (likely need upstream PR, or fork SharedInformerFactory). Then run the rest.
  * Note: I think this is kind of risky as we actually call RunAndWait multiple times due to case where we lazy-load informers (leader election, etc). Note: those cases are already broken by https://github.com/kubernetes/kubernetes/issues/117869, worked around in https://github.com/istio/istio/pull/44145 with locking.

In both cases, we serialize our startup to block on CRD+Namespaces syncing before anything else starts up. This isn't great... I think we could optimize it so that we do not block on Namespace if there is no discovery selector set (note: we will still watch the Namespace, just not block everything else on it. So if they later set a discoverySelector we can handle it). For CRD we can probably just not block at all, the cost of lazy-loading it is very very tiny.

So I guess my conclusion is:

* Very early, Create and Run (without wait) namespace + CRD informers.
* Block on namespace filter IFF a discovery filter is set
* Startup the rest of things as is

In addition, I think some major refactoring of the discovery selector is needed.

wdyt @hzxuzhonghu ? I think this mostly aligns with what you had done in https://github.com/istio/istio/pull/44551/ (which I didn't fully understand at the time), with the main different that we only `Wait` on it if a discovery filter is set

**Comment by hzxuzhonghu** [comment]
Good elaboration, agreed

**Comment by ramaraochavali** [comment]
+1. Agree with the approach
