### ISSUE TITLE
Additional RouteRules breaks previous rule with lower precedence

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#4468]
@Dmitry1987 commented on [Sun Mar 11 2018](https://github.com/istio/issues/issues/237)

**Is this a BUG or FEATURE REQUEST?:**
BUG
**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
yes, didn't find this combination of rules like mine in other issues
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version:  0.6.0
kubectl version:  client 1.9.2 / server 1.8.3
```

**Is Istio Auth enabled or not ?**
no auth

**What happened**:
Have 3 deployments (v1/v2/v3), istio-ingress (working),
setting default rule works (route all to v1), adding http header based rule works (if i use the header it routes me to v2) **but v1 gets broken.** 

Somehow new rules cancel basic default rule. Adding 3rd rule works,(also by host header), v3 gets displayed if proper header passed.  But default rule doesn't work (if no headers passed - should go to v1).  

If I delete rule 2 and 3 (host match rules) suddenly default rule starts working and i get v1.

**What you expected to happen:**
All 3 work by precedence, the host matching ones get higher precedence numbers.

**How to reproduce it:**
1. Simple K8s cluster on AWS, istio with no auth. 
2. Some demo app deployments added, and service with name "website" that points to them.
each deployment has labels "app=website" and "version=v1" (v2/v3).
3. I used 'istioctl kube-inject -f file1 -o file2'  and kubectl-creating the file2.  
4. Route rules added with istioctl, first default rule (works) then second one (works too but breaks the 1st):
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: website-canary
  namespace: default
  resourceVersion: "48278"
spec:
  destination:
    name: website
  match:
    request:
      headers:
        version:
          exact: v2
  precedence: 2
  route:
  - labels:
      version: v2
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: website-default
  namespace: default
  resourceVersion: "48257"
spec:
  destination:
    name: website
  precedence: 1
  route:
  - labels:
      version: v1

```

same with rule 3, it works showing v3 when i use the right headers. so v2 and v3 both work and v1 remains broken(requests with no header at all, get 404 instead v1), but if i delete routes 2 and 3, then v1 suddenly gets back to work (requests with no header go to v1 container normally)

**Feature Request:**
N

Maybe I just miss something, but maybe it's kind of bug.
Thanks

---

@bobbytables commented on [Tue Mar 13 2018](https://github.com/istio/issues/issues/237#issuecomment-372880976)

I have this same exact issue. Here's what I discovered:

The route table for the Envoy ingress gets updated just fine with both the RouteRule + IngressRules.

However, the `CDS` endpoint of Pilot shows my cluster for my ingress with no route rule disappears and only my cluster for the one that has a specific `RouteRule` applied exists.

My guess is that the consolidation that occurs to render the CDS endpoint is breaking because of a routerule being added and skipping the rest of the clusters that also need to be added.

Pilot logs show no errors either for this.

---

@bobbytables commented on [Tue Mar 13 2018](https://github.com/istio/issues/issues/237#issuecomment-372883881)

Based on this comment, I'm guessing this is the cause: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/config.go?utf8=%E2%9C%93#L614-L618

`IngressRule`'s aren't added as a `v1alpha1` RouteRule, but when you add a `RouteRule` type, the default adds the new API version / group. Hence, when the CDS endpoint only has the RouteRule type instead.

---

@Dmitry1987 commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-372961384)

Oh my, that means it wont work?  Is there a solution to use several RouteRules with ingress?

---

@kyessenov commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373100845)

cc @ZackButcher @ijsnellf : could please take a look? sounds like something is amiss in the ingress config generation. Redirect as appropriate.

---

@bobbytables commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373101081)

This is how I was able to break this: https://youtu.be/R0D1UQdPSsE

* Have a k8s ingress rule pointing to a service
* CDS endpoint for ingress looks fine
* Add RouteRule for original destination, old ingress rule vanishes from CDS

---

@bobbytables commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373103488)

I should add that the Ingress rule _does_ have prefix matcher. IE: (`path: /.*`)

---

@Dmitry1987 commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373183215)

hehe @bobbytables thanks for sharing. a "video bug report" could be feature request to GitHub :) , they don't develop much lately, GitHub remains the same as 5 years ago, it's about time to add some fresh ideas :)  with a "video diff" function, now that sounds modern ;)

---

@Dmitry1987 commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373183835)

I'm new to istio, would never find that bug reason myself  :+1: 
Can I submit a PR to solve this?  I know golang. If someone will just point me to the right files, I can work on this bug

---

@ZackButcher commented on [Wed Mar 14 2018](https://github.com/istio/issues/issues/237#issuecomment-373207765)

I'm taking a look at this now. Will be happy to give pointers to fix it once it's been root caused @Dmitry1987.

---

@bobbytables commented on [Fri Mar 16 2018](https://github.com/istio/issues/issues/237#issuecomment-373750990)

Any status on this?

---

@Dmitry1987 commented on [Wed Mar 21 2018](https://github.com/istio/issues/issues/237#issuecomment-375143154)

thanks @ZackButcher let me know if I can help

**Comment by bobbytables** [comment]
Is this being worked on? This bug makes RouteRules + Ingress unusable in production environments.

**Comment by avalcepina** [comment]
@bobbytables you can take a look at my last comment on [https://github.com/istio/issues/issues/260](https://github.com/istio/issues/issues/260), you might find it helpful in the meantime

**Comment by ldemailly** [comment]
subset of #4457

**Comment by bmarshall13** [comment]
I've run into a bug that that looks like this, at least superficially.
I have 2 k8s ingress resources with several path prefix matches each. Each of those path prefixes has a few route rules with different precedences.

Sometimes the ordering of the routes in the ingress envoy proxy is wrong.

I've tracked down the cause, at least in my case:
1 - For each ingress rules, get the list of applicable routes, correctly ordered by precedence: 
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/ingress.go#L88

I don't have any host matches, so these rules get appended to the "*" vhost list: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/ingress.go#L118

If there are no overlapping paths, the list is now ordered correctly. (This is my case)

2 -  The routes are re-sorted to account for overlapping paths:
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/ingress.go#L125
and
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v1/ingress.go#L135

sort.Sort() is not stable, so since the only sort key is the path, there is no guarantee that the sorting by precedence is preserved. 

I think those can just be changed to sort.Stable() to fix this. For all routes that have the exact path prefix, the precedence ordering will be maintained.

@ZackButcher does this agree with what you've found?

**Comment by ZackButcher** [comment]
Yup I think that's correct. However, we've essentially frozen Envoy v1/Istio v1alpha1 development and are focusing on getting out Envoy v2/Istio v1alpha3 APIs out the door for 0.8. Fortunately v1alpha3 APIs shouldn't suffer from this problem as we've eliminated rule precedence: all `match` conditions from a single host are part of a single config document, so we just generate routes/matches in the order they appear in the config document.
