### ISSUE TITLE
Support setting SetMutexProfileFraction via an environment variable

### ISSUE THREAD

**Issue by dwj300** [istio/istio#44688]
**Describe the feature request**
Call `runtime.SetMutexProfileFraction()` based on an env var. We find the pprof endpoints extremely useful, and have investigated some recent performance regressions using it. However, we can't profile mutexes without this runtime setting.

**Describe alternatives you've considered**
1. According to https://github.com/golang/go/issues/23401, Google runs most Go servers in production with 1%. We'd be fine with a constant 1%.
2. Fork istio: This is not ideal. We'd be more than happy to upstream the change, but don't want to have to cary a patch.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Similar to https://github.com/kubernetes/kubernetes/issues/61125

**Comment by howardjohn** [comment]
What is the current state? It doesn't work at all? Or it is doing 100% and you want less? I had thought i had used the mutex profile before without issue

**Comment by dwj300** [comment]
Without setting `runtime.SetMutexProfileFraction()`, the pprof mutex profile is a no-op. See https://pkg.go.dev/net/http/pprof#hdr-Usage_examples. By default, the value is 0%.
