### ISSUE TITLE
istio-proxy don't respect ProxyConfig terminationDrainDuration 30s

### ISSUE THREAD

**Issue by chuong-ts** [istio/istio#44690]
### Bug Description

I am trying to change the default `terminationDrainDuration` from 5s to 30s. However, I do not see the change appearing because the proxy logs are saying:

```
2023-05-01T18:25:20.227362Z	info	Agent has successfully terminated
2023-05-01T18:25:20.227349Z	info	Envoy aborted normally
2023-05-01T18:25:20.227143Z	warn	Aborting proxy
2023-05-01T18:25:20.227079Z	info	There are no more active connections. terminating proxy...
2023-05-01T18:25:20.155936Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2023-05-01T18:25:19.220727Z	info	Checking for active connections...
2023-05-01T18:25:18.156447Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2023-05-01T18:25:16.156685Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2023-05-01T18:25:14.220630Z	info	Agent draining proxy for 5s, then waiting for active connections to terminate... <- still default 5s
2023-05-01T18:25:14.219331Z	info	Agent draining Proxy
2023-05-01T18:25:14.219319Z	info	Status server has successfully terminated
```
My helm chart config:
```
meshConfig:
    defaultConfig:
      terminationDrainDuration: 30s
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
```

My proxy config_dump:
```
kubectl exec my-service-7d846b757c-nh4cn -c istio-proxy -- pilot-agent request GET config_dump |grep -i terminationDrainDuration
       "terminationDrainDuration": "30s"
```
My all config_dump:

```
kubectl exec my-service-7d846b757c-nh4cn  -c istio-proxy -- pilot-agent request GET config_dump
....
"PROXY_CONFIG": {
       "serviceCluster": "istio-proxy",
       "drainDuration": "45s",
       "tracing": {
        "zipkin": {
         "address": "jaeger-jaeger-operator-jaeger-collector.tracing:9411"
        }
       },
       "statNameLength": 189,
       "binaryPath": "/usr/local/bin/envoy",
       "controlPlaneAuthPolicy": "MUTUAL_TLS",
       "concurrency": 2,
       "statusPort": 15020,
       "configPath": "./etc/istio/proxy",
       "terminationDrainDuration": "30s",
       "discoveryAddress": "istiod.istio-system.svc:15012",
       "parentShutdownDuration": "60s",
       "proxyAdminPort": 15000,
       "proxyMetadata": {
        "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"
       }
      }
....
```
The config  `terminationDrainDuration: 30s` already appeared in my config_dump but as you can see in the logs above. It's still default 5s for draining....
Question:
- What is wrong with my config and how to change to default terminationDrainDuration from 5s -> whatever I want

### Version

```Text
istioctl version
client version: 1.17.2
control plane version: 1.15.2
data plane version: 1.15.2 (20 proxies)

kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.25.8-gke.500

helm version --short
v3.8.2+g6e3701e
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Hmm, this all looks right from config perspective. Will need to take another look.

Note 1.15 is EOL; it's plausible this has been fixed since then

**Comment by chuong-ts** [comment]
> Hmm, this all looks right from config perspective. Will need to take another look.
> 
> Note 1.15 is EOL; it's plausible this has been fixed since then

let me test with one more scenario by removing:         `EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'`

**Comment by howardjohn** [comment]
oh if you have that set then it intentional iirc, it waits 5s for any new
open connections (takes some time to tell clients to stop) then terminates
when there are no connections

**Comment by chuong-ts** [comment]
Hi @howardjohn, I was able to identify the root cause. The source code (https://github.com/istio/istio/blob/fb5353b54abb148156851d4e1b60aedcc8aa264f/pkg/envoy/agent.go#L136) makes it very clear. If we enable the EXIT_ON_ZERO_ACTIVE_CONNECTIONS which means we skip the terminationDrainDuration, we should use the MINIMUM_DRAIN_DURATION instead. The valid config must be:
```
meshConfig:
    defaultConfig:
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
        MINIMUM_DRAIN_DURATION: '30s'
```

**Comment by Samjin** [comment]
MINIMUM_DRAIN_DURATION will be executed first, then it'll check active connection and exit when it becomes 0. 
Why do you even need to set a static 30s before dynamic connection check? Why not just set to 0, and have `EXIT_ON_ZERO_ACTIVE_CONNECTIONS ` to determine when to shutdown the istio proxy sidecar?

**Comment by Samjin** [comment]
@chuong-ts 
MINIMUM_DRAIN_DURATION will be executed first, then it'll check active connection and exit when it becomes 0.
Why do you even need to set a static 30s before dynamic connection check? Why not just set to 0, and have EXIT_ON_ZERO_ACTIVE_CONNECTIONS  to determine when to shutdown the istio proxy sidecar?
