### ISSUE TITLE
performance issues in 1.16.3 : pilot-agent consumes more memory in idle condition and cpu consumption is also more under load 

### ISSUE THREAD

**Issue by komalarg2010** [istio/istio#44691]
### Bug Description

Upgrading from Istio 1.11.4 to 1.16.3 

There are two performance issues observed: 
1. Single pod load tests consumes more cpu 
- in 1.11.4 , our pod with application + istio-proxy containers were able to take upto 4K of requests 
- in 1.16.3, same application version +  new istio-proxy  is able take 2.6K - then we start seeing 504 and 503 errors. (x-envoy-overload) observed 
- Post this, OOM observed. Caused by issue 2 
 Please note: In both tests, there is no change to the configuration nor application - only istio version change. 

2. pilot-agent consumes more memory in idle condition. 
- Top out shows higher memory consumption for pilot agent process - **this is under no load**
- 'top' output from pod with istio-proxy in 1.16.3  - **4873m**
```
Mem: 29369288K used, 3354908K free, 340952K shrd, 261684K buff, 12888644K cached
    CPU:  5.3% usr  3.2% sys  0.0% nic 89.7% idle  0.1% io  0.9% irq  0.5% sirq
    Load average: 4.62 4.62 3.72 3/3806 45
      PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
       25     1 1337     S     220m  0.6   4  0.0 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev.json --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --local-addres
        1     0 1337     S    4873m 15.2  10  0.0 /usr/local/bin/pilot-agent proxy sidecar --domain manoj.svc.cluster.local --proxyLogLevel=warning --proxyComponentLogLevel=misc:error --log_ou
       39     0 1337     S     1320  0.0   8  0.0 sh
       45    39 1337     R     1296  0.0  12  0.0 top
```
-

Ran 2.6K load on both 1.11.4 and 1.16.3 and collected logs and attached. 
[bug-report.tar_2.6K_1.16.3.gz](https://github.com/istio/istio/files/11370415/bug-report.tar_2.6K_1.16.3.gz)
[bug-report.tar_2.6K_1.11.4.gz](https://github.com/istio/istio/files/11370418/bug-report.tar_2.6K_1.11.4.gz)

-  'top' output from pod with istio-proxy in Istio1.11.4 - **200m** 
```
Mem: 63920572K used, 67697348K free, 151268K shrd, 28623688K buff, 23363540K cached
      CPU:  0.4% usr  0.2% sys  0.0% nic 99.2% idle  0.0% io  0.0% irq  0.0% sirq
      Load average: 1.44 1.28 1.47 2/2384 34
        PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
          1     0 1337     S     764m  0.5  30  0.0 /usr/local/bin/pilot-agent proxy sidecar --domain csd.svc.cluster.local --proxyLogLevel=debug --proxyComponentLogLevel=misc:d
         13     1 1337     S     200m  0.1  30  0.0 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --pare
         28     0 1337     S     1280  0.0   6  0.0 sh
         34    28 1337     R     1260  0.0  30  0.0 top
```

### Version

```Text
$ istioctl version
client version: 1.16.3
control plane version: istio
data plane version: 1.16.3 (33 proxies)
$ kubectl version --short
Client Version: v1.21.14
Server Version: v1.21.14
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
I don't think using VSZ is a good measurement. That includes things paged out to disk, etc.
