### ISSUE TITLE
grpcgen: inconsistent behavior with nil Service

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44701]
https://github.com/istio/istio/blob/a902592004731b312c48c2503695e9c1939c0e14/pilot/pkg/networking/grpcgen/cds.go#L106

Here we allow missing svc. But later we assume its there and can get a nil pointer derefernce. 

We should probably not generate a Cluster without a service. If we do, we should do it consistently. cc @costinm @stevenctl

**Comment by costinm** [comment]
Not sure what is best behavior if user attempts to make a request to an unknown destination. If it was not .cluster.local we would do a passthrough with DNS resolution. Maybe we can do the same here ?

We do support modes where istiod is not watching all namespaces - so may not know about everything.
