### ISSUE TITLE
Grafana dashboards are referencing old metric names

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#44735]
### Bug Description

The following metric has been changed
from
istio_request_duration_seconds_bucket
to
istio_request_duration_milliseconds_bucket

looks like this metric changed names in 2021: https://github.com/istio/istio/issues/31516

it affects the following dashboards:
grafana dashboard id 7630 = istio-workload-dashboard
grafana dashboard id 7636 =istio-service-dashboard
grafana dashboard id 7639 = istio-mesh-dashboard

### Version

```Text
istio versions since early 2021.
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ceastman-r7** [comment]
<img width="1792" alt="Screenshot 2023-05-03 at 11 25 26 AM" src="https://user-images.githubusercontent.com/97614291/235994587-d7d96ca7-a1af-4590-801a-4d5c4321a1ed.png">

this seems to affect the bottom three panels that are showing "no data"

**Comment by howardjohn** [comment]
hmm we are supposed to have a test for this. TestDashboard. wonder where it went wrong.

**Comment by ceastman-r7** [comment]
actually it looks like the dashboard panels have an OR for the prometheus query to account for the old and new metric name but neither is showing any data. I checked prometheus and I see metrics for the millisecond bucket.

**Comment by zirain** [comment]
After a long time, I think it's good to remove the obsolated metrics.
