### ISSUE TITLE
Deprecation announcement: OpenCensus sunset on 7/31

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#44743]
This is an early announcement that Istio will be removing OpenCensus support shortly due to [sunsetting on 7/31](https://opentelemetry.io/blog/2023/sunsetting-opencensus/#:~:text=Compatibility%20specification%204.-,What%20to%20Expect%20After%20July%2031st%2C%202023,found%20will%20not%20be%20patched.).

This will impact any usage of OpenCensus or StackDriver in tracing, logging, or metrics. The current plan is to use OpenTelemetry exporters in Envoy with the OpenTelemetry collector to match the capabilities.

**Comment by howardjohn** [comment]
Can we:

* Update https://github.com/istio/istio/blob/a284d5803649c047f72ad1f5525f40adbbed2341/operator/pkg/apis/istio/v1alpha1/validation/validation.go#L91 for istioctl
* Update manifests/charts/istio-control/istio-discovery/templates/NOTES.txt for helm
* Include a notice in 1.18 release notes

Thanks

**Comment by howardjohn** [comment]
I think its fine to say "migrate to open telemetry/other modes" or something? We have to tell the users something - we cannot just tell them to not use telemetry anymore

**Comment by howardjohn** [comment]
Depends what you mean by supporting OpenTelemetry. its a massive project with at least ~5 components relevant to Istio. Can you expand a bit?

The answer is probably mostly "yes", though

**Comment by zirain** [comment]
> > Depends what you mean by supporting OpenTelemetry. its a massive project with at least ~5 components relevant to Istio. Can you expand a bit?
> > The answer is probably mostly "it is planned but not done"
> 
> Hi, we are just looking for the distributed tracing support. I suppose when OpenCensus is removed, the support for "traceparent", "tracestate" headers will not be supported anymore.

it's supported since v1.16, see https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-OpenTelemetryTracingProvider

**Comment by zirain** [comment]
xref: https://github.com/istio/istio/pull/45341
