### ISSUE TITLE
use leases instead of configmaps for leader election

### ISSUE THREAD

**Issue by juliantaylor** [istio/istio#44756]
istio appears to still use configmaps for leader elections which causes a lot of writes into configmaps:

```
$ kubectl get cm -A -w
Mai 04 11:46:59 istio-system                                  istio-namespace-controller-election                                0      72d
Mai 04 11:46:59 istio-system                                  istio-leader                                                       0      72d
Mai 04 11:47:02 istio-system                                  istio-gateway-deployment-leader                                    0      72d
Mai 04 11:47:02 istio-system                                  istio-gateway-status-leader                                        0      72d
Mai 04 11:47:06 istio-system                                  istio-leader                                                       0      72d
Mai 04 11:47:06 istio-system                                  istio-namespace-controller-election                                0      72d
Mai 04 11:47:10 istio-system                                  istio-gateway-deployment-leader                                    0      72d
Mai 04 11:47:10 istio-system                                  istio-gateway-status-leader                                        0      72d
```

kubernetes has a special object for this since quite a while, the leases:
https://kubernetes.io/docs/concepts/architecture/leases/

Using these objects would make it simpler to find the leader and are used by most other components using leaders, e.g.

```
$ kubectl -n kube-system get leases
NAME                                           HOLDER                                                                            AGE
external-attacher-leader-rbd-csi-ceph-com      csi-rbdplugin-provisioner-6669846f59-llz7c                                        72d
```

Imo it is worthwhile to switch to leases for consistency alone with other systems but also we observed frequent configmap watch resets in our applications which are mainly caused by istio updating them so often. As configmaps are also watched from all kubelets too this could have practical performance implications though we have not done any measurements.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

```
$ istioctl version
client version: 1.16.3
control plane version: 1.16.4
data plane version: 1.16.4 (203 proxies)

**Comment by howardjohn** [comment]
The only way to migrate from configmap to lease is to use a MultiLock which does both at once. This is 2x as expensive. You can only switch to using only Lease once all old versions using ConfigMap are gone. Unfortunately, Istio has basically arbitrary version skew support due to canaries, so there isn't really a safe end point.

Additionally, we use a fork of the leaderelection library that doesn't really support Lease. We could probably make it work if we needed, though.

**Comment by juliantaylor** [comment]
it is not 2x as expensive in terms of the full cluster, you additionally update leases which are intended to be volatile resources only watched by few services, this is less expensive than modifying configmaps which are intended to not be very frequent changing resources watched by every single kubelet.

**Comment by howardjohn** [comment]
Perhaps not 2x, but its strictly more load, no? There is no exit path off of configmaps given our canary upgrade support

**Comment by juliantaylor** [comment]
Sure `x + 1 > x` but if this matters depends on the size of `x`.
Now if changing it is worth the complexity of a the transition it also depends on `x` and I do not have data on this but based on the linker pull you attempted to get rid of leader election fully, so there appears to be some concern about this already.

Maybe its worthwhile to check if the k8s apiserver does treat objects different depending on their expected modification frequency. Glancing logfiles the watch resets were much more common than I expected around every 30 or so seconds in one of our smallest ~10 node clusters which indicates it retains less history on them but I haven't checked anything proper after identifying istio as the source.

**Comment by hzxuzhonghu** [comment]
Kubernetes upgrade faced the same tansition, worth to take a look at it

**Comment by howardjohn** [comment]
Yeah that is what the multi lock solves but I think they have a smaller
bound on version skew since they don't have canary upgrade mechanism like
Istio

**Comment by MohaPress** [comment]
It is possible to start using leases for leader election only for kubernetes versions > 1.14. However, it will not work for old kubernetes version. I suggest to simply rewrite the old deprecated ConfigMapsLock resourcelock and use it only for old versions.

**Comment by AlianBenabdallah** [comment]
It is possible to start using leases for leader election only for kubernetes versions > 1.14. However, it will not work for old kubernetes version. I suggest to simply rewrite the old deprecated ConfigMapsLock resourcelock and use it only for old versions.

**Comment by howardjohn** [comment]
We don't support Kubernetes 1.14. The issue is upgrades from old versions. We cannot simply switch or the old and new version will both win.

**Comment by keithmattix** [comment]
Not stale

**Comment by caozhuozi** [comment]
Not stale
