### ISSUE TITLE
Add Strict-Transport-Security header for tls httpsRedirect on Gateway answer

### ISSUE THREAD

**Issue by adrianiacobghiula** [istio/istio#44754]
**Describe the feature request**
On the Gateway one can configure httpsRedirect send a 301 redirect. Adding to this response the header Strict-Transport-Security
to inform browsers that the site should only be accessed using HTTPS

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Describe alternatives you've considered**

Modifying the response in the VirtualService <- but the request only reaches the VS only if the request is already https

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Per the spec this header actually must be served once connecting over HTTPS. It's ignored over HTTP. So seems like we can't do this, and putting it in virtual service would work? wdyt?

The link you added is what described this
