### ISSUE TITLE
integ-telemetry-mc TestAccessLogsMode test flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#44759]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/44755/integ-telemetry-mc_istio/1654049957650370560

<html>
<body>

api: TestAccessLogsMode/server expand_less | 1m25s
-- | --
{Failed      accesslogs_test.go:297: expected logs but got err: timeout while waiting after 361 attempts (last error: expected client logs false but got 36)}

</body>
</html>

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry_istio_postsubmit/1669359696512815104
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc_istio_postsubmit/1669368953887002624

**Comment by zirain** [comment]
I will take a look at this
