### ISSUE TITLE
Disable Graceful Shutdown

### ISSUE THREAD

**Issue by priscofarina** [istio/istio#44761]
While discussing the following scenario [here](https://github.com/istio/istio/issues/43596#issuecomment-1534203267)
I start thinking that in my case, and so maybe it could be useful also to others, could be more useful to have the graceful shutdown feature disabled more than enabled in order to be able to accept requests we would like to manage while the main application is dying.

**Describe the feature request**
Disable the functionality of Graceful shutdown in order to be managed only from the application side

**Describe alternatives you've considered**
Another way could be having a graceful shutdown feature enabled as it is and having some kind of configuration on the endpoints we still want to manage from the application point of view.
Imagine the application is configured in the following way:

```
/endpoint1
/endpoint2
/endpoint3
```
while the SIGTERM is intercepted we just want to block any requests towards:
```
/endpoint1
/endpoint2
```
and not towards :

```
/endpoint3
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
If we disable graceful shutdown that means we will instantly terminate and all traffic will be blocked. It does not make it managed by the application - no traffic would get to the application as it would all be redirected to the sidecar which would have stopped running

**Comment by priscofarina** [comment]
sorry, I think we can close this issue.
Thank you for the explanation.
