### ISSUE TITLE
Ambient CNI informer seems to get spurious EventDelete

### ISSUE THREAD

**Issue by bleggett** [istio/istio#44762]
### Bug Description

In this function: https://github.com/istio/istio/blob/master/cni/pkg/ambient/informers.go#L82 I have noticed (via the addition of debug logging) that weirdly, we can get spurious EventDeletes for ztunnel pods during _creation_ even if the pod is _not_ being deleted or rescheduled.

The spurious EventDeletes will have a nil `event.Old` - "normal" EventDeletes from a real ztunnel pod deletion will not - current code will implicitly ignore the former case, but it still seems strange.

### Version

```Text
Current `master` as of 5/4/2023
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/73c4ea182b611bb54c10ac4c5cc4cf30f84f6588/cni/pkg/ambient/informers.go#L74 would give no Old which seems like a bug (with no impact, as far as I can tell). 

doesn't explain spurious though

**Comment by dddddai** [comment]
When a ztunnel spins up, istio-cni will reconcile all pods on the node
https://github.com/istio/istio/blob/05580f5d5e248a9aa46079909661837089a6c1a5/cni/pkg/ambient/server.go#L252

and trigger delete events for pods without ambient enabled
https://github.com/istio/istio/blob/05580f5d5e248a9aa46079909661837089a6c1a5/cni/pkg/ambient/informers.go#L73-L78

Not sure why we need this

**Comment by bleggett** [comment]
@dddddai ah that's it. Also not sure. We don't AFAICT, that seems like junk events.

**Comment by bleggett** [comment]
This has no functional impact but it is confusing and does cause potentially-unnecessary ztunnel reconciliation checks, so PR'd a tiny fix.
