### ISSUE TITLE
Installing Ambient Mesh with Helm on GKE Error

### ISSUE THREAD

**Issue by Spittal** [istio/istio#44769]
### Bug Description

Hello, I've recently been messing around with installing `1.18.0-beta.0` components with Helm on a Google Kubernetes Engine cluster running Dataplane V2. For the most part all of this is working with the exception of the `istio-cni` component, when installing it throws the following error

```
Helm release "kube-system/istio-cni" failed to initialize completely.
Use Helm CLI to investigate.: failed to become available within allocated timeout.
Error: Helm Release kube-system/istio-cni: cannot patch "istio-cni-node" with kind DaemonSet: DaemonSet.apps "istio-cni-node" is invalid: spec.template.spec.containers[0].volumeMounts.mountPropagation: Forbidden: Bidirectional mount propagation is available only to privileged containers
```

### Reproduction
This is fairly easy to replicate. Boot up the default configuration (Dataplane v2 is default as of writing) of a GKE cluster then run.

`kubectl create namespace istio-system`

`helm install istio-base istio/base -n istio-system --version=v1.18.0-beta.0 --wait`

`helm install istio-cni istio/cni -n kube-system --version=v1.18.0-beta.0 --set cni.cniBinDir=/home/kubernetes/bin --set cni.ambient.enabled=true --set cni.ambient.redirectMode=ebpf --wait`

This is where it fails with the above error.

### Additional info
I've been tinkering with the install using different parameters and it seems this error is related to `--set cni.ambient.redirectMode=ebpf`. As expected from reading the error if you install with `--set cni.privileged=true` the install is successful. However, there is no `ztunnel` pod.

This report was first reported on the [istio slack organization](https://istio.slack.com/archives/C049TCZMPCP/p1683224728545349)

### Version

```Text
### Istio Version
client version: 1.18.0-beta.0
control plane version: 1.18.0-beta.0
data plane version: 1.18.0-beta.0 (1 proxies)

### Kubernetes Version
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.7-gke.1000

### Helm Version
v3.10.3+g835b733
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by PlatformLC** [comment]
For the log you hit, you may try with `--set cni.privileged=true`, i.e.
`helm install istio-cni istio/cni -n kube-system --version=v1.18.0-beta.0 --set cni.cniBinDir=/home/kubernetes/bin --set cni.ambient.enabled=true --set cni.ambient.redirectMode=ebpf   --set cni.privileged=true --wait`.

However, as John mentioned in slack, GKE dataplanveV2 is not supported yet for now
