### ISSUE TITLE
bug-report: json log lines can be excluded

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44788]
`getTimeRange` attempts to filter on time. This doesn't take JSON format into account, leading to missing logs

**Comment by howardjohn** [comment]
Specifically I mean when `--log_as_json` is used

**Comment by iyear** [comment]
/assign

So directly ignore json log lines? Or unmarshal json to fields we need?

**Comment by howardjohn** [comment]
TBH the whole parsing seems a bit unneeded, we could probably remove it (note: I am saying that without a lot of research). But either way, we must see the json lines. Currently we lose all the logs if users use json.

I don't mean to gate keep this at all but, I believe someone has already started work on this so want to make sure we don't duplicate efforts

**Comment by howardjohn** [comment]
@syw14 is working on this
