### ISSUE TITLE
Gateway API: RequestRedirect filter to https adds 80 port when not specified

### ISSUE THREAD

**Issue by JuniorJPDJ** [istio/istio#44798]
### Bug Description

My HTTPRoute is defined with this yaml:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble-ui-https-redirect
  namespace: kube-system
spec:
  hostnames:
  - hubble.X
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: istio-system
    sectionName: http-0
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 301 
      type: RequestRedirect
```

But then istio response is like that:

```
$ curl -v http://hubble.X
*   Trying 192.168.64.203:80...
* Connected to hubble.X (192.168.64.203) port 80 (#0)
> GET / HTTP/1.1
> Host: hubble.X
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< location: https://hubble.X:80/
< date: Sat, 06 May 2023 23:55:00 GMT
< server: istio-envoy
< content-length: 0
< 
* Connection #0 to host hubble.X left intact
```

So it tries to redirect to https on port 80 (same port as incomming request?) which is obviously wrong.

Even better - when I specify:
```
    - requestRedirect:
        scheme: https
        statusCode: 301
        port: 443
```

Which I'm not supposed to do, istio adds port to the location header:

```
$ curl -v http://hubble.X
*   Trying 192.168.64.203:80...
* Connected to hubble.X (192.168.64.203) port 80 (#0)
> GET / HTTP/1.1
> Host: hubble.X
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< location: https://hubble.X:443/
< date: Sat, 06 May 2023 23:57:39 GMT
< server: istio-envoy
< content-length: 0
< 
* Connection #0 to host hubble.X left intact
```

And it's not supposed to do so according to the docs: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRequestRedirectFilter (port section)

### Version

```Text
client version: 1.16.1
control plane version: 1.17.2
data plane version: 1.17.2 (2 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
The spec on this has changed multiple times in the past few weeks and continues to change. As has the implementation to keep up with these changes in Istio 1.18.

That being said even in the latest iterations of the spec and Istio implementation the first one goes to port 80. Which is kind of confusing, so that may change as well - but has not yet.

**Comment by howardjohn** [comment]
This is fixed in https://github.com/istio/istio/pull/44817 / https://github.com/kubernetes-sigs/gateway-api/pull/1880/files

**Comment by JuniorJPDJ** [comment]
How cool! Thank you very much.

Anyway there's second issue here - port is pushed to Location header when it shouldn't be (it's default for the protocol).
This is the case in last example of my issue.

**Comment by JuniorJPDJ** [comment]
I probably just don't understand why it should fix also the second issue.
Anyway it's good to see it's fixed if you say it is ;)

This was fast one!

**Comment by howardjohn** [comment]
I think the 2nd one is actually already fixed, just not in a released
version yet. So not exactly in that PR

**Comment by alextricity25** [comment]
To confirm, has this fix made it into a release?
