### ISSUE TITLE
Tracing decorator for the server-side sidecar

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4479]
The inbound HTTP routes currently ignores the client routing used to address it:
- listener on port POD_PORT
- routes on virtual host "*", sent passthrough

What tracing decorator should we insert here?

@rshriram thinks that we should attempt to infer all the ways the client address the workload, and insert a routing table analogous to the virtual services, and use the virtual service name as the decorator.

I think that inferring the server settings from the client settings is fundamentally fragile, and we should use the workload ID as the decorator.

Let's resolve this once and for all.

cc @louiscryan

**Comment by rshriram** [comment]
We are no longer using decorators based on virtual service names.
