### ISSUE TITLE
Websocket upgrade server setting

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4480]
Another instance where the server-side envoy attempts to guess the client-side envoy settings: websocket upgrade flag. The code tries to enumerate all routes that _may_ lead to the server-side envoy, and then apply the flag if it finds any that require websockets. This seems fragile (coordination between client and service side envoys is impossible, server may not guess client correctly).

cc @louiscryan

**Comment by rshriram** [comment]
Yep..
