### ISSUE TITLE
will istio have to notify every Ztunnel and waypoint in ambient mode when even just a new service added into cluster

### ISSUE THREAD

**Issue by jingb** [istio/istio#44803]
As described in the title. 
In my opinion, cause the istio use iptable technology to redirect traffic. When there is a new service A being added to the cluster, all the ztunnel and waypoint in the cluster have to update the configuration, cause they need to know the new serviceA's traffice rule. 
And the sidecar mode also has this issue right? Is this recognition correct?

**Comment by howardjohn** [comment]
Yes. But it has nothing to do with iptables specifically - the iptables is static. But the proxy (envoy/ztunnel) do have config about each service.
