### ISSUE TITLE
Ingress gateways and  Istiod install failed

### ISSUE THREAD

**Issue by huayangchan** [istio/istio#44819]
chy@DESKTOP-KHAQ8FT:~/src/istio-1.10.6$ minikube start --memory=5120 --cpus=4
😄  minikube v1.30.0 on Ubuntu 20.04
✨  Automatically selected the docker driver. Other choices: none, ssh

🧯  The requested memory allocation of 5120MiB does not leave room for system overhead (total system memory: 5941MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=5120mb'

📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.26.3 preload ...
    > preloaded-images-k8s-v18-v1...:  38.64 MiB / 397.02 MiB  9.73% 4.47 MiB p🎉  minikube 1.30.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.30.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

    > preloaded-images-k8s-v18-v1...:  397.02 MiB / 397.02 MiB  100.00% 4.07 Mi
    > index.docker.io/kicbase/bui...:  373.53 MiB / 373.53 MiB  100.00% 478.97
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase-builds:v0.0.38-1680381266-16207, but successfully downloaded docker.io/kicbase/build:v0.0.38-1680381266-16207 as a fallback image
🔥  Creating docker container (CPUs=4, Memory=5120MB) ...
🌐  Found network options:
    ▪ http_proxy=http://xxxxx8080
❗  You appear to be using a proxy, but your NO_PROXY environment does not include the minikube IP (192.168.49.2).
📘  Please see https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/ for more details
    ▪ https_proxy=http://xxxxx:8080
    ▪ no_proxy=xxxxxx
❗  Image was not built for the current minikube version. To resolve this you can delete and recreate your minikube cluster using the latest images. Expected minikube version: v1.29.0 -> Actual minikube version: v1.30.0
❗  This container is having trouble accessing https://registry.k8s.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...
    ▪ env HTTP_PROXY=http://xxxxx:8080
    ▪ env HTTPS_PROXY=http://xxxxx:8080
    ▪ env NO_PROXY=xxxxx
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

chy@DESKTOP-KHAQ8FT:~/src/istio-1.10.6$ istioctl install
This will install the Istio 1.10.6  profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
  Processing resources for Istiod.
2023-05-09T03:46:58.889394Z     error   installer       failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
2023-05-09T03:46:58.905010Z     error   installer       failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
✘ Istiod encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Processing resources for Ingress gateways.
2023-05-09T03:46:59.150598Z     error   installer       failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
  Processing resources for Ingress gateways.
2023-05-09T03:46:59.750073Z     error   installer       failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istio-ingressgateway: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Pruning removed resources
2023-05-09T03:47:00.349972Z     warn    installer       retrieving resources to prune type autoscaling/v2beta1, Kind=HorizontalPodAutoscaler: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1" not found
2023-05-09T03:47:00.950478Z     warn    installer       retrieving resources to prune type policy/v1beta1, Kind=PodDisruptionBudget: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1" not found
Error: failed to install manifests: errors occurred during operation

chy@DESKTOP-KHAQ8FT:~/src/istio-1.10.6$ istioctl version
client version: 1.10.6
control plane version: 1.10.6
data plane version: 1.10.6 (1 proxies)

when i install istio, Istio core install sucessfully ,but Ingress gateways and  Istiod install failed. how to solve it?

**Comment by hanxiaop** [comment]
The istioctl is too old. Try upgrade istioctl and do installation again.
