### ISSUE TITLE
Locality affinity support

### ISSUE THREAD

**Issue by costinm** [istio/istio#4481]
Edit: outcome of discussion in slack:

In EDS code, we will maintain a per zone EDS, where all endpoints in local zone will get 75% traffic and those in remote zones will get rest 25%.

Configuration considerations:

**EDS Configuration**

- Supplying of core.Locality in LocalityLbEndpoints.
- Setting of load_balancing_weight field

**CDS Common LB Configuration**

- Locality_weighted_lb_config enabled

------------------------------------------------------------------------------------

I don't think it ever worked fully in v1 - but for multi-cluster it'll be important to get it right.
Few notes:
- existing code to get the AZ from node annotations seems ok, but need to reduce logging ( some clusters don't support this, no need to be so verbose )
- for clusters without node annotations, in a multi-cluster env, it should be possible to get the zone from the cluster config, and maybe default to the custer name

In eds.go we'll need to group the endpoints by zone, and return each list separately, and set the zone
in each set.

**Comment by costinm** [comment]
+sdake - if you have some bandwidth for the multi-cluster parts ( or the entire thing ).

**Comment by kyessenov** [comment]
Locality LB endpoints are somewhat orthogonal to cluster zones in Envoy.
PTAL
https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/endpoint/endpoint.proto#L6
3

**Comment by rshriram** [comment]
None of this will work until we sort out how to update the service zone of the proxy with mTLS enabled. We need to restart Envoy with the appropriate service zone since we don’t have access to the pod’s az during startup. Alternatively, we invest time in making that piece dynamic in Envoy.

**Comment by costinm** [comment]
Regarding AZ-on-startup - it's orthogonal, I have some other work in progress that will cover this (with agent making an explicit MTLS + gRPC call to pilot, it can get AZ and other data ). 

This issue is specifically for fixing the EDS result - need to group the endpoints by locality, and pass
the right locality.

**Comment by costinm** [comment]
Also: it is already possible to configure the sidecars with an explicit zone, without having to get it from pilot.
It works in many cases where you control how you deploy.

**Comment by liamawhite** [comment]
> Also: it is already possible to configure the sidecars with an explicit zone, without having to get it from pilot.

That is true, but how would a user go about configuring an explicit zone?

>This issue is specifically for fixing the EDS result - need to group the endpoints by locality, and pass
the right locality.

I'm not sure I understand correctly. You wan't to do some additional explicit locality filtering in pilot based on the endpoint region/zone?

**Comment by costinm** [comment]
For explicit zone config: the CI/CD + kube-inject or webhook can add it using a custom template for injection.In a multi-cluster mode each cluster will have a separate webhook and may have a separate template. 

But this bug is not about filtering or fancier config: it's about how we generate the EDS config, and checking it works. Envoy expects to see a list of LocalityLbEndpoints, each with a locality and a list of endpoints in that  locality. Right now we return a list of LocailtyLbEndpoints each with a single endpoint, and with the zone repeated in each. To fix this we need to sort/group the endpoints - should be relatively simple. Testing it - with some form of zone config - is the tricky part.

**Comment by liamawhite** [comment]
I understand now. Just reading through the docs I think this actually may be instead of setting `--service-zone`?

> zone
(string) Defines the local service zone where Envoy is running. Though optional, it should be set if discovery service routing is used and the discovery service exposes zone data, either in this message or via --service-zone. The meaning of zone is context dependent, e.g. Availability Zone (AZ) on AWS, Zone on GCP, etc.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-locality

**Comment by sdake** [comment]
@costinm apologies I missed the assignment of this issue (~3 weeks ago).  Overflowing in github email :(  I will have some time to work on this in the coming few weeks.

@liamawhite want to join forces, or going to handle on your own?

Cheers
-steve

**Comment by liamawhite** [comment]
Happy to join forces. Let me know when you have some time to work on it.

**Comment by sdake** [comment]
@liamawhite I suspect I will be consumed until 0.8 is branched doing what I can to get 0.8 ready to go, after which I will have time available.  I think the branch is at end of week.

Do you have any specific task list in mind?

Cheers
-steve

**Comment by costinm** [comment]
I think for 0.8 we need to confirm envoy is ok with what we send - i.e. the
repeated list of
one locality + one endpoint, instead of the grouped format.
And to test it actually works - for that we need 2 clusters with a service
with at least 2 endpoints
in each cluster.  I would be happy with a manual test for 0.8 - setting up
the environment is tricky
and still in flux.

We can optimize/refine after 0.8.

**Comment by costinm** [comment]
Anyone has time for this in the next 3 days ? I guess testing may be more time consuming then 
actually grouping the endpoints by zone and implementing the optimization. 

If nobody else volunteers I can take it (probably on Fri)

**Comment by liamawhite** [comment]
Design Doc is [here](https://docs.google.com/document/d/17TVN-GUWLAuM-YHPd561qMQOXCaSMQ51wcQEkxvvW9U/edit). Discussions ongoing.

**Comment by costinm** [comment]
Setting it for 1.0 - I think it's required.

**Comment by bjhaid** [comment]
@liamawhite I am interested in reading the design doc but google tells me it's not publicly available, do I need to belong to some mailing list to read it or it's really not for public consumption....

**Comment by munnerz** [comment]
> In EDS code, we will maintain a per zone EDS, where all endpoints in local zone will get 75% traffic and those in remote zones will get rest 25%.

I wonder if the 75/25 split is configurable? We would like to adjust these parameters to better suit our orgs requirement.

Thanks!

**Comment by liamawhite** [comment]
@munnerz There's no reason we can't do this, we just need to work out the best place to expose it to users. It will probably initially be a mesh wide configuration variable though.

@bjhaid Not sure why you can't see it, let me do some investigation

**Comment by cainelli** [comment]
What's the status of this? I went through some issues, documentation and discussions and is not clear if we can achieve Locality Weighted Load Balancing or something similar somehow.

btw I'm also interested in reading the design doc above and meeting notes but have no access.

**Comment by liamawhite** [comment]
This has not yet been prioritised, but I will take a look if more people are interested in this. It will not be in by 1.1 though.

**Comment by cainelli** [comment]
Thank you @liamawhite. Is there a recommended way to preferably route traffic within the same availability zone? I've scratched the code base and saw that ServiceInstances have AvailabilityZone but it was unclear if it can be used to achieve this.

I know we can workaround this with DestinationRules but was wondering if there is a better approach.

**Comment by liamawhite** [comment]
The availability zone fields are not configured properly in Envoy yet so won't do it for you. 

I think you could probably do this with DestinationRules but that would be pretty horrible, I can't think of a better approach right now though.

**Comment by mumoshu** [comment]
Hey! I have an use-case enabling zone-aware load-balancing towards hosts outside of the mesh. Would this issue relate to that, too?

My initial guess is that I'd need to add a kind of `zone` field to the [ServiceEntry.Location](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-Location) type, consuming the zone value from it, configure Envoy accordingly via EDS.

**Comment by Stono** [comment]
Hey
Just wanted to rekindle this issue a bit, we're *super* interested in zone aware routing both from a performance and cost optimisation perspective.  

It'd be great to see some traction?

**Comment by liamawhite** [comment]
Discussions are currently underway on how we can implement this efficiently. Could everyone who is interested please go into a bit more detail on their use cases? This will allow us to better understand what things need to be made configurable.

**Comment by Stono** [comment]
Happily, 
So we run in GKE/GCP are for availability reasons run our cluster across three availability zones.    We make use of affinity rules to ensure latency sensitive applications are co-located (node, and zonal) but we also then distribute those instances across AZ's for BCP reasons.  So for example;

```
Zone A
  - App 1
  - App 2

Zone B
  - App 1
  - App 2
```

etc....

We quite simply want to keep the traffic between App1 and App2 within the same zone *where possible*, unless the zonal instance of an app was offline or a circuit breaker was firing.

This:

  - Reduces latency
  - Reduces cost (zonal egress charges)

My use case doesn't really require much configuration, just simple prefer the same zone, where possible.

**Comment by cainelli** [comment]
We have a similar use case described above. However, we still also need to prioritize traffic within the same availability zone for things running outside Kubernetes, such as databases. We have an in-house solution for this ATM that integrates with our former 'service mesh' solution but deprecating this custom stuff would be great.

Also, we have concerns of unbalanced deployments across the cluster potentially overload some service instances more than others if the weight criteria are purely AZ-based. Having the weight defined by node, AZ and something else like load(# of requests) could be one way to go, and if is possible to add such metrics to the equation, latency could also be an alternative and ~my guess~ would make things easier for this particular issue - It would try to prioritize traffic to the shortest distance, but when some service instance on the shortest network route is taking long to respond (in case of being overloaded) it would shift traffic to others responding faster.

Well, in any case, I really appreciate you guys are starting to talk about this again 💯

**Comment by liamawhite** [comment]
@Stono @cainelli @munnerz @mumoshu @bjhaid 

Hopefully, you can all see this design doc. I will be presenting it in the networking group later this evening but I believe the locality affinity section covers your use cases.

https://docs.google.com/document/d/1ALscYDDeYuhxiS-DWogDSEHThIDON2J_I88AQYtf9Xw/edit?usp=sharing

**Comment by dwradcliffe** [comment]
What's the status here? It looks like a PR may have been merged then reverted?

**Comment by mumoshu** [comment]
@dwradcliffe Hey! My understanding is that this is mostly coming to v1.1.

The only missing feature would be `Targeted Locality Weighting (Locality Weighted Load Balancing)` for cluster-internal traffic. For egress traffic, it is already implemented in #11381.

See @liamawhite's comment at https://github.com/istio/istio/pull/11381#issuecomment-468397227 for more context.

**Comment by liamawhite** [comment]
This will be experimental in 1.1 and off by default behind an env var. See https://github.com/istio/istio.io/pull/3593 for more details.

All features should be there but have not been extensively tested. The aim is to do this over the course of 1.1.x releases and then turn it on by default.

**Comment by howardjohn** [comment]
This has been release in 1.1. If there are any issues please open a new issue.

See https://istio.io/help/ops/traffic-management/locality-load-balancing/ for docs.
