### ISSUE TITLE
404 response when K8s ingress is set with `path: "/*" pathType: ImplementationSpecific`

### ISSUE THREAD

**Issue by aryan16** [istio/istio#44811]
### Bug Description

When user sets rules in K8s ingress with `path: "/*", pathType: ImplementationSpecific`, Istio messes up in routing and returns 404. 
If we change config to use ` path: "/", pathType: Prefix`, it works.

### Version

```Text
1.14 and above
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
@keithmattix this is the bug we had discussed

**Comment by keithmattix** [comment]
I believe @jaellio fixed this in 1.18

**Comment by keithmattix** [comment]
Fixed by #44898
