### ISSUE TITLE
Multicluster with istio 

### ISSUE THREAD

**Issue by omar-triguii** [istio/istio#44826]
### Bug Description

I have an Aks cluster and a local kind cluster. when creating remote secret in Aks cluster. I check Aks IstioD logs I get:
![carbon (13)](https://github.com/istio/istio/assets/75097067/2d0db209-577c-4561-a1a8-0caf1c5ded46)
So that I only get one direction communication. that means local cluster could trust and send traffic to Aks and not viceversa.

### Version

```Text
istioctl version 1.17.2
Client Version: v1.26.3
Kustomize Version: v4.5.7
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
Your kind cluster is not exposed to the public internet (notice the localhost IP address: 127.0.0.1). There is no way for AKS (or anything on the internet really) to talk to your local kind cluster using that ip address. Consider using something like https://ngrok.com/ to expose your kind cluster

**Comment by omar-triguii** [comment]
> Your kind cluster is not exposed to the public internet (notice the localhost IP address: 127.0.0.1). There is no way for AKS (or anything on the internet really) to talk to your local kind cluster using that ip address. Consider using something like https://ngrok.com/ to expose your kind cluster

**Comment by omar-triguii** [comment]
I did link kind cluster to rancher with a public apiserver url. and i get : failed creating config configstore for the local cluster. tls failed to verify certificate x509: certificate signed by unknown authority.

**Comment by keithmattix** [comment]
Take a look at the docs around the multicluster [trust models](https://istio.io/latest/docs/ops/deployment/deployment-models/#identity-and-trust-models). You can't just use the default certificates created by each individual mesh; you have to provide each Istio control plane with certificates that have a common root of trust

**Comment by omar-triguii** [comment]
I did follow istio official docs. it provides : https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
I did the same thing between both Aks cluster and it works.
