### ISSUE TITLE
Citadel should log when it mints a certificate

### ISSUE THREAD

**Issue by dwj300** [istio/istio#44830]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We'd like to add some logging to the `ca.sign()` method (https://github.com/istio/istio/blob/5fe8306c154cb265dcf867cae7cf6d71a1765b76/security/pkg/pki/ca/ca.go#LL415C2-L415C13) using the existing pkiCaLog logger. Mostly just creating this issue to ensure there is no opposition before we make the change.

We had an incident where we needed to identify which proxies renewed their certificates during a specific time window, but couldn't find any existing logging in istiod.

**Describe alternatives you've considered**
Looking at the proxy logs. We'd prefer something central.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by keithmattix** [comment]
This feels more appropriate as a Prometheus metric; have you considered that approach?

**Comment by dwj300** [comment]
> This feels more appropriate as a Prometheus metric; have you considered that approach?

@keithmattix, the cardinality would be much too high.

**Comment by zhaohuabing** [comment]
We're facing the same situation when trying to track cert generation for compliance requirements.
