### ISSUE TITLE
Analysis: analyze file is not working if same resource exists in cluster

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#44844]
### Bug Description

To reproduce:

If we have:
```yaml
root@xp:~# kubectl get gw bookinfo-gateway -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2023-05-09T07:17:52Z"
  generation: 1
  name: bookinfo-gateway
  namespace: default
  resourceVersion: "623063"
  uid: 17f16ec3-a6a1-4cb9-b218-ee46176065aa
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

Then we analyze with `istioctl analyze a.yaml` when `a.yaml` is:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9999
      name: http
      protocol: HTTP
```

It won't report any error messages.

If set `--use-kube=false`, it will report the message since no same resource exists in cluster.

I think this should be a regression after refactoring the galley code

### Version

```Text
master branch
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by CrazyCry** [comment]
We also encountered the same problem. This problem still exists in 1.17.2. Although the official document mentions "allowing you to catch problems before you apply changes to a cluster", it is only for resources that do not exist in the cluster. If the resource has modification, it is undetectable, I hope the official can fix this problem in the next version

**Comment by hanxiaop** [comment]
This issue will be fixed by https://github.com/istio/istio/pull/44865

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale
