### ISSUE TITLE
Istio Logging enhancements

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#4484]
At present mixer (et al) logging is an all or nothing affair. Enabling level=`debug` creates a torrent of logs. 

- [x] Ensure that `debug` only applies to istio component. It should not apply to dependencies like `client-go` which adds to log noise
- [x] Create a special category for (safe) attribute logging
- [ ] Start time per component / package log level
- [x] Runtime per component / package log level. Thru /admin/logging interface?
- [ ] Per request debug enablement. Debug is enabled when a certain header is present or `x-request-id` contains a certain field.

**Comment by geeknoid** [comment]
I want to add a general notion of log areas. Areas will be registered at startup for a process and the user will be able to list areas and enable/disable different areas.

**Comment by ldemailly** [comment]
Thanks for this follow up on #2400

**Comment by geeknoid** [comment]
@mandarjog 

Regarding your list item:

    Start time per component / package log level

So how about:

- pkg/log emits a log message at level "Info" to the default logging scope when it is first initialized. This would be the first entry in the log and effectively represents component start time.

- pkg/log emits a log message at level "info" to the default logging scope whenever any scope's logging level or stack trace level is changed. We could also output a message to the affected scope, but I don't think that's necessary.

This means that if there is some high-frequency logic that enables/disables logging scope dynamically, it would cause noise in the logs. I don't really expect this to be a problem.

WDYT?

**Comment by mandarjog** [comment]
My intent behind that item was we should be able to set a component to "debug" level at start, using commandline params like glog or similar.

I think component start times can be emitted (at INFO) by the component itself when it starts.

**Comment by ldemailly** [comment]
not stale
