### ISSUE TITLE
Use Protobuf format for Kubernetes API

### ISSUE THREAD

**Issue by sschepens** [istio/istio#44848]
**Describe the feature request**
Kubernetes supports protobuf format for API requests. Though it's mostly used for intra-cluster components communications it could bring huge performance benefits on multi-cluster scenarios or when there is lots of resources and changes.

According to the [proposal](https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/protobuf.md):

> Experiments have demonstrated a 10x reduction in CPU use during serialization and deserialization, a 2x reduction in size in bytes on the wire, and a 6-9x reduction in the amount of objects created on the heap during serialization.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
We have already merged support for this on the master branch

**Comment by sschepens** [comment]
@howardjohn excellent!
