### ISSUE TITLE
istio get config from remote istio

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#44863]
We have two k8s, k8s1 and k8s2,  both with istio deployed and istio version is 1.16.2. and  two service name A and B, service A in k8s1, service B in k8s2, both service with sidecar.  We use istioctl create-remote-secret  to make this two k8s to get each other's api permission so that B can use serviceA.namespace.svc.cluster.lcoal to request A.

We set virtualservice in k8s1 for service A by subset to make different request to different version of service A. This rule in k8s1 can work normally, but request from service B in k8s2 doesn't follow the rules of subset.

We use istioctl to check cluster for serviceA.namespace.svc.cluster.lcoal, there is no subset lable.

We want to know how can we get the route config from another istio

**Comment by hanxiaop** [comment]
It looks like you are following the multi-primary deployment model, and for this model, clusters have their own control planes and operates independently. When you try to apply traffic policies you should create the polices to the cluster where the traffic originates.

**Comment by hanxiaop** [comment]
FYI https://istio.io/latest/docs/ops/deployment/deployment-models/

**Comment by id-id-id** [comment]
I have import service.yaml、vs/yaml and dr.yaml of service A in k8s1 which is only deployed in k8s1  into k8s2, and  service B in k8s2 request to service A by serviceA.namespace.svc.cluster.local,  but envoy log like that:
debug	envoy filter	cannot find cluster outbound|8850|blue|serviceA.namespace.svc.cluster.local

blue is my subset lable.

I use istioctl to check， cluster named outbound|8850|blue|serviceA.namespace.svc.cluster.local doesn't exist.  

Why i import rule config to k8s2 but istio can not generate cluster with subset lable？

**Comment by id-id-id** [comment]
is there any method to ensure atomicity of push rule config to multi cluster?

**Comment by hanxiaop** [comment]
> is there any method to ensure atomicity of push rule config to multi cluster?

Maybe things like gitops?
