### ISSUE TITLE
istio-proxy websocket log configuration error

### ISSUE THREAD

**Issue by KKHYeon** [istio/istio#44864]
### Bug Description

I set the pod's annotations as `sidecar.istio.io/componentLogLevel: conn_handler:debug,mongo:debug,websocket:debug`. However, I encountered an error saying `error: invalid component specified 'websocket'.`
I'm curious about the reason, as it seems logging is possible based on the following document: https://github.com/envoyproxy/envoy/blob/main/source/common/common/logger.h.

### Version

```Text
$ istioctl version
client version: 1.15.4
control plane version: 1.15.4
data plane version: 1.15.4 (20 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
it's introduced by https://github.com/envoyproxy/envoy/pull/22542, should be envoy v1.24.

base on https://istio.io/latest/docs/releases/supported-releases/#supported-envoy-versions
I think it's avaiable in istio v1.16.

**Comment by hanxiaop** [comment]
You can try `istioctl pc log <podname>` to see a list of available loggers for the proxy
