### ISSUE TITLE
deploymentcontroller: support per-pod proxyconfig

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44878]
Currently we just use the global default https://github.com/istio/istio/blob/e2a88e9c44db1488fc76b1a50d2030dfc7046095/pilot/pkg/config/kube/gateway/deploymentcontroller.go#L399.

I would say we may consider intentionally not handling it for annotations, but at least the real ProxyConfig CRD should probably be supported

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/44916
