### ISSUE TITLE
Configure cluster panic threshold for circuit breaking

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#4488]
We should be able to tune the cluster panic threshold through DestinationPolicy/Rules. This config has been exposed in Envoy here: 

https://github.com/envoyproxy/envoy/issues/2463

This would allow us to tune how much of the load balancing pool can become unhealthy before we panic, including allowing all of it to become unhealthy.

**Comment by metacosm** [comment]
@christian-posta do you think it's possible to change the Envoy configuration directly for now? If yes, how?

**Comment by christian-posta** [comment]
Yah... there is a way i think. Pilot exposes the way to enrich/change the xDS json/yaml that gets shipped to the Envoy proxy. We'd need to add this config to that. 

See this doc and the --webhookEndpoint setting. 

I'll try to write docs/examples on this. We can use that as a workaround until we properly enable this configuration setting.

**Comment by mandarjog** [comment]
Here is an example of webhook.

**Comment by knrc** [comment]
https://github.com/istio/istio/pull/9176

**Comment by liamawhite** [comment]
I believe this has been added.

**Comment by metacosm** [comment]
> I believe this has been added.

Has this been documented? If yes, where?

**Comment by liamawhite** [comment]
https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#OutlierDetection under `minHealthPercent`

The functionality should be in the 1.1 release.

**Comment by dkrieger** [comment]
does this not warrant a bump to a new networking version? I was confused to see errors when trying to use this feature w/ Istio 1.0.6
