### ISSUE TITLE
Unexpected routing behavior with long-lived connections with headless services

### ISSUE THREAD

**Issue by perlow** [istio/istio#44886]
### Bug Description

The setting is as follows:
- A headless service for a statefulset that exposes a GRPC endpoint.
- The client connecting to the service is using a pod-level DNS address to talk to a specific logical pod in the service (representing for example a particular partition of the service's cache).
- The client is using a GRPC ManagedChannel which maintains one or more long-lived HTTP/2 connections.
- A pod is deleted and then replaced in the statefulset (such as during a rolling update).

The desired behavior is
- After the pod is deleted, requests on the channel should immediately return UNAVAILABLE as there is no backing pod to handle the request.
- When the new pod is created, requests should then be routed to the new pod at the same logical hostname based on istio/envoy logic of basing the destination on the authority header and ignoring the original IP specified by the client.

The actual behavior is
- After the pod is deleted, requests take 30 seconds and then istio/envoy returns an error.
- It appears that under the hood, traffic continues being routed to the dead pod on the original IP address.
- This behavior will continue indefinitely until the client manually terminates the GRPC ManagedChannel and creates a new one where DNS is re-resolved.

Discussions related to this are at
- https://istio.slack.com/archives/C37A4KAAD/p1683825839435839
- https://stackoverflow.com/questions/65661273/istio-keeps-using-deleted-pod-ip
- @howardjohn referenced https://github.com/envoyproxy/envoy/issues/19458 as a related issue

### Version

```Text
$ istioctl version
1.17.2

$ kubectl version --short
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.24.10-eks-48e63af

$ helm version --short
v3.11.2+g912ebc1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by perlow** [comment]
For those who run into the issue, creating a ServiceEntry for each replica and then referencing it addresses the problem. Here is an example from our code base


```
{{/*
This works around istio bug https://github.com/istio/istio/issues/44886.
*/}}

{{- $replicaCount := .Values.backend.replicaCount | default 1 | int }}
{{- $outer := . -}} # Save scope
{{- range $index := until $replicaCount }}
{{- with $outer -}}  # Restore scope
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name:  {{ include "nd-common.fullname" . }}-backend-shard-{{ $index }}
spec:
  hosts:
    - {{ include "nd-common.fullname" . }}-backend-shard-{{ $index }}.{{ include "nd-common.fullname" . }}-backend
  location: MESH_INTERNAL
  ports:
    - number: {{ .Values.global.config.grpcPort }}
      name: grpc
      protocol: GRPC
  resolution: STATIC
  workloadSelector:
    labels:
      app.kubernetes.io/component: backend
      {{- include "nd-common.selectorLabels" $ | nindent 6 }}
      statefulset.kubernetes.io/pod-name: {{ include "nd-common.fullname" . }}-backend-{{ $index }}
---
{{- end }}
{{- end }}

```

**Comment by howardjohn** [comment]
I think the ideal solution would be https://github.com/envoyproxy/envoy/issues/17726 + https://github.com/envoyproxy/envoy/issues/15750. but needs changes in Envoy

**Comment by howardjohn** [comment]
Also ambient would not have this problem due to differences in its implementation I believe. Need to double check ztunnel handles it properly though

**Comment by keithmattix** [comment]
Not stale

**Comment by diranged** [comment]
Can this be reopened?

**Comment by hanxiaop** [comment]
not stale
