### ISSUE TITLE
Istioctl connect to the istio-pilot service and report 404

### ISSUE THREAD

**Issue by fogongzi** [istio/istio#449]
When I use istioctl command by --kube=false the response is 404. The details are as follows:
root@kube-master:/software/kubernetes/istio-0.1.6# istioctl --kube=false --configAPIService="http://10.71.156.230:31611" -v=999 version
I0705 15:51:27.390952   16515 loader.go:354] Config loaded from file /root/.kube/config
istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1

apiserver version:

I0705 15:51:27.397642   16515 proxy.go:74] curl -X GET  "http://10.71.156.230:31611/version" 
I0705 15:51:27.397695   16515 proxy.go:187] /version Response 404 Body:  404 page not found
**Error: /version status 404**

The http://10.71.156.230:31611 refers to the service istio-pilot:8081 by NodePort, so how can I solve the problem?

**Comment by ayj** [comment]
Can you access istio-pilot's `health` endpoint, e.g. `curl http://10.71.156.230:31611/health"`? Otherwise, you may need to double check your configuration re: Address and NodePort for istio-pilot.

**Comment by fogongzi** [comment]
@ayj ,Thanks for your reply. I find http://10.71.156.230:31611/v1alpha1/version  is good and return:
{
  "version": "0.1.6",
  "revision": "dab2033",
  "branch": "release-0.1",
  "user": "jenkins",
  "host": "ubuntu-16-04-build-12ac793f80be71",
  "golang_version": "go1.8.1"
 }
So I think there may be a bug (I am sorry that I can not make sure that). Because I install rbac istio  by "istio-rbac-beta.yaml", but when I  curl http://10.71.156.230:31611/v1beta1/version , it also returns 404, so I have to install rbac istio  by "istio-rbac-alpha.yaml" and it works well with route limition function. In a word the istioctl command uses v1alpha1 version default and seems not to support v1beta1 version.

**Comment by ldemailly** [comment]
going to close this assuming you resolved it since, if not please open a new issue in
https://github.com/istio/issues/issues
