### ISSUE TITLE
IPv6 Gateway API broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44900]
https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1657093301104283648

Since https://github.com/istio/istio/commit/cfec09f824814c4537e257af26ecc2db85cedde0

**Comment by howardjohn** [comment]
Fix in https://github.com/kubernetes-sigs/gateway-api/pull/2024

Skip in https://github.com/istio/istio/pull/44920

**Comment by keithmattix** [comment]
@howardjohn i think your fix made it to 0.7.0 release. Can we close this/remove the skip?

**Comment by howardjohn** [comment]
We should try to remove the skip

**Comment by keithmattix** [comment]
I'll give it a try
