### ISSUE TITLE
Website fallback

### ISSUE THREAD

**Issue by danvy** [istio/istio#44901]
### Discussed in https://github.com/istio/istio/discussions/44603

<div type='discussions-op-text'>

<sup>Originally posted by **danvy** April 27, 2023</sup>
Hosting a website on k8s with Istio has different requirements than web services.
Istio documentation says that it's up to the app to deal with unavailable services aka error 503.
https://istio.io/latest/docs/concepts/traffic-management/#working-with-your-applications
This is not possible for websites as the client (web browser) is not under our control.
We have to provide fallback content to serve the user browser with proper message.
How could I do that with Istio ?
I tried using a virtual service with route destination of 100% for the main service and 0% for the fallback. Once the main service is down, 503 is returned.
What is the best practice for this use case ?</div>

**Comment by keithmattix** [comment]
I think this may be a limitation of Envoy because it's a proxy not a web server
