### ISSUE TITLE
Mount key cert files to workload via FlexVolumeDriver

### ISSUE THREAD

**Issue by incfly** [istio/istio#4491]
Step 2 for #4190 

The end result is to make key-cert visible from workload pod via flexvolume drive. NodeAgent will writes key/cert to different path, say, /host/driver/sa1. And we use `istioctl kube-inject` to mount /host/driver/sa1 to a /etc/certs/ for the workload.

Note that we have to make different workload (same identity) share the key cert, but that should be fine.

This work will be abandoned once we have SDService available. 

@myidpt @wattli

**Comment by wattli** [comment]
obsolete as we are not going with flexvolume any more.
