### ISSUE TITLE
PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND default value changed from false to true

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#44912]
I find that proxy environment PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND default value is changed to true. Why was this change introduced. And I  find my servcie listener config shows that the filter type is changed from envoy.config.filter.network.tcp_proxy.v2.TcpProxy to envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager, it seems concern with PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND.

service.yaml:
`apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  ports:
  - nodePort: 32572
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxx`

**Comment by hzxuzhonghu** [comment]
That was long history, please see the release note
