### ISSUE TITLE
Ignore the changes of "status.conditions" in `svc` during service registration.

### ISSUE THREAD

**Issue by miaoyq** [istio/istio#44923]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, any changes in the `conditions` field in `k8s svc` triggers istiod to push XDS to the data plane, which is unnecessary. Frequent changes in `conditions` will result in increased resource consumption by istiod, which is something that users do not want to see.

**Describe alternatives you've considered**
We should ignore the changes of "status.conditions" in `svc` during service registration.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Currently we donot use service conditions, so make sense
