### ISSUE TITLE
Derive ISTIO_VERSION from binary

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44937]
Currently we set this in the dockerfile. The issue is this is not used outside of docker (VMs). So we set it in istio-start.sh, but it doesn't update.

The binary knows its own version, so I think we can just read that. Just needs some plumbing. For backwards compat we can still use the var if its there, but not set it in istio-start or dockerfile.

**Comment by cebernardi** [comment]
Is the ask to populate [this](https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L567) with the Istio version from [here](https://github.com/istio/istio/blob/master/pkg/version/version.go#L40)?

If the above assumption is correct, would [this](https://github.com/istio/istio/blob/master/pkg/istio-agent/agent.go#L229) a good place to plumb? 

From what you're writing, it seems the desired behaviour is that if the env var is there, it will override the binary version?

**Comment by howardjohn** [comment]
Yep! We will just need to make sure to remove it from https://github.com/istio/istio/blob/cb9484509e160280ce3c5da7b6a48a914d07a65c/pilot/docker/Dockerfile.proxyv2#L39 or we will always have the env var and it will override.

To give env var precedence we will just need to set it here: https://github.com/istio/istio/blob/bd9e52d05817b03b9811a761a818b2e76d356018/pkg/bootstrap/config.go#L534, before L543 where the env var is read I think (might be a bit more complicated in practice)

**Comment by cebernardi** [comment]
Can I give it a go?

**Comment by howardjohn** [comment]
sounds great!

**Comment by cebernardi** [comment]
should we close this?

**Comment by howardjohn** [comment]
Yep, thanks!
