### ISSUE TITLE
update cacerts secret can not update new certificate to istio-proxy ?

### ISSUE THREAD

**Issue by CoffeeHi** [istio/istio#44932]
### Bug Description
Hi guys,

Currently there is one istio mesh deployed in our cluster without customized CA, and after running several days later, we decide to update to new CA generated by us instead of istio itself, we have deployed the gateway, virtualservice, etc., 

then we followed [plugin-ca-cert](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/) guide to create a `cacerts` secret in istio-system namespace, istiod pods are also in istio-system namespace, there are no cacerts secret before, and then we found it's fine for a while , but unfortunately we met the istio ingress gateway error shows 

```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

I think it's ingress gateway pods had already updated certificates but application pods had not updated yet that caused this issue, is it correct ?

Restarting the application pod helps, but Im confused whether istio can deal with this case automatically ?  Will istio update the new certificate from old CA generations to new CA generations smoothly ?

### Version

```Text
% istioctl version
client version: 1.14.3
control plane version: 1.16
data plane version: 1.15.3 (31 proxies), 1.16-dev (102 proxies)

% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
This is not supported yet, FYI https://github.com/istio/istio/issues/30947

**Comment by ro-distefano** [comment]
Are there any updates on this issue? Restarting the application pod causes downtime; is there a better solution available nowadays?
