### ISSUE TITLE
short names(non FQDN) are not allowed

### ISSUE THREAD

**Issue by letdosomething** [istio/istio#44954]
### Bug Description

![problem](https://github.com/istio/istio/assets/57476984/cd85d4e4-a298-45ba-9cad-9aa6c4ffad5e)

For gateway and virtual service, hosts must use FQDN. However, when migrating from the native k8s ingress nginx, there is no such restriction on host. I would like to ask if there is any solution to this problem because there are already hundreds of services that request in this way with host + short name, and it is not practical to modify them all.

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (17 proxies)
$ kubectl version --short
Client Version: v1.24.4-tke.6
Kustomize Version: v4.5.4
Server Version: v1.24.4-tke.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by letdosomething** [comment]
https://github.com/istio/istio/issues/22533 This issue discusses a matter, but I did not see the final solution.

**Comment by letdosomething** [comment]
I just want to access the service using curl -H 'host: xxxx'

**Comment by sfc-gh-stopchiy** [comment]
In our company, we also use short names for internal apps, which are managed in the /etc/hosts file. Currently, we are in the process of migrating all internal apps to Kubernetes with Istio, and we have encountered an issue where short links do not work. Is it possible to implement a feature to support short links?

**Comment by hanxiaop** [comment]
Have you tried k8s gateway? Gateway allows shortname https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by hanxiaop** [comment]
> > Have you tried k8s gateway? Gateway allows shortname https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/
> 
> No, I haven't tried it yet. Thanks for information I'll try it, but we have already implemented a lot of things with regular Istio Gateway

I think this won't affect the existing logic and can coexist to handle features like short names. By the way Istio is encouraging the use of Gateway API and is trending toward making it the default option. See the notes at https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/.

**Comment by mk01** [comment]
in case particular gateway accepts * as hosts, one could do something like this (although I would be very cautious as istio will merge all virtual services having * and having virtual services with overlapping match statements or conflicting destinations could have adverse effects)

```
spec:
  gateways:
  - ingress-gateway
  hosts:
  - '*'
  http:
  - match:
    - authority:
        exact: simple-hostname
      port: 80
    route:
    - destination:
        host: backend.namespace.svc
        port:
          number: 80
```
