### ISSUE TITLE
Health checks are not appropriate

### ISSUE THREAD

**Issue by GokulakrishnanP027** [istio/istio#44963]
It would be nice if "/ready" [path](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--ready) is available in general purposes like kubernetes readiness and liveness probes?

Because currently it is now only allowed in admin interface and only be accessed within container. 

Actual issue: Health checks are not appropriate. We enabled "/healthz/ready" probes from ALB to proxy. If we set proxy as a draining mode, ALB still sending traffic to DRAINING mode pods because "/healthz/ready" receives 200 OK.

Solution: Would be nice if we can see the current status of pod like as admin interface like "/ready", we can do the better health check and send traffic appropriately. Also, make available of "[healthcheck/fail](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--healthcheck-fail)" for public with basic-auth/header check. So we can use this as PreStopHook in kubernetes for graceful shutdown.

**Comment by howardjohn** [comment]
We explicitly don't expose Envoy's `/ready` since it doesn't correlate to whether the sidecar is ready. So using that would be 1 step forward, 2 steps back.

Why are you draining with healthcheck/fail instead of just sending a SIGTERM? Istio can be configured to wait longer from SIGTERM to exit with terminationDrainDuration.

**Comment by GokulakrishnanP027** [comment]
But, it is inappropriate health checks

Example: If k8s ApiServer sends SIGTERM to kill the container and healthChecks were still 200 OK. It should be service available though?

[step 1] Initially, it is in the LIVE state.
$ curl http://localhost:15000/ready 
LIVE
$ curl http://localhost:15021/healthz/ready -w '%{http_code}'
200

[step 2] call /healthcheck/fail and endpoint /ready show 503 DRAINING 
$ curl http://localhost:15000/healthcheck/fail -X POST
OK
$ curl http://localhost:15000/ready -w '%{http_code}'
DRAINING
503

[step 3] but /healthz/ready show 200 response
$ curl http://localhost:15021/healthz/ready -w '%{http_code}'
200

So, if the endpoint shows 200, our loadbalancer still sends the traffic to 'DRAINING' mode container?
