### ISSUE TITLE
Ingress non functional

### ISSUE THREAD

**Issue by sakethkumardamera** [istio/istio#44972]
Hi All,

We have a successful ISTIO setup using istioctl with 1.2.1 version. We would now like to give a try with helm way of installation and followed the below steps from the documentation:
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod -n istio-system --wait
helm install istio-ingress istio/gateway -n istio-system --wait

Then deployed the http bin and tried the testing  from both CURL and browser as outlined in the below example.
Used the istio gateway.

My loadbalancer has a public ip address on an azure kubernetes private Cluster, i did verdify NSG and can see the three ports that are added 15021, 80 and 443 are allowed from internet to the public ip. When ever i hit the URL with port and URI as headers, i see the following exception in browser(This site can’t be reached), and the logs has not received any hit.

If am doing something wrong, can someone please help me out

**Comment by howardjohn** [comment]
I think there may be some missing info in this? You said "i see the following exception" but there is nothing about an exception. Can you post the configuration you used as well?

**Comment by sakethkumardamera** [comment]
Hi Howard,

This is what i see, when i hit the public ip address, **This site can’t be reached**.
My kubernetes version is 1.25.5 and i have not used any overrides, just ran the above commands.

**Comment by sakethkumardamera** [comment]
Hi Keith,
Thanks for getting back to me:
curl -s -I -HHost:httpbin.example.com "http://20.XXX.20.132:80/delay", have not received any response
if i hit using this URL: http://20.xxx.20.132:80/headers, This site can’t be reached  20.XXX.20.132 took too long to respond.
the 20.xxx.xxx.xxx is not my private range for sure and in the azure portal being displayed as an public ip address.
Unfortunately i dont have access to any public cluster, and finally if i use my old version with the same virtual service and gateway am getting the response.

**Comment by sakethkumardamera** [comment]
This is my VS and GW yaml snippet:
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /headers
    route:
    - destination:
        port:
          number: 8000
        host: httpbin

**Comment by sakethkumardamera** [comment]
my http service snippet:apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80

**Comment by sakethkumardamera** [comment]
If am missing something, please let me know, any help is greatly appreciated, as am now totally stuck

**Comment by sakethkumardamera** [comment]
my gateway values.yaml file content:
# Name allows overriding the release name. Generally this should not be set
name: ""
# revision declares which revision this gateway is a part of
revision: ""

replicaCount: 1

kind: Deployment

rbac:
  # If enabled, roles will be created to enable accessing certificates from Gateways. This is not needed
  # when using http://gateway-api.org/.
  enabled: true

serviceAccount:
  # If set, a service account will be created. Otherwise, the default is used
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set, the release name is used
  name: ""

podAnnotations:
  prometheus.io/port: "15020"
  prometheus.io/scrape: "true"
  prometheus.io/path: "/stats/prometheus"
  inject.istio.io/templates: "gateway"
  sidecar.istio.io/inject: "true"

# Define the security context for the pod.
# If unset, this will be automatically set to the minimum privileges required to bind to port 80 and 443.
# On Kubernetes 1.22+, this only requires the `net.ipv4.ip_unprivileged_port_start` sysctl.
securityContext: ~
containerSecurityContext: ~

service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  annotations: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""
  externalIPs: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Pod environment variables
env: {}

# Labels to apply to all resources
labels: {}

# Annotations to apply to all resources
annotations: {}

nodeSelector: {}

tolerations: []

topologySpreadConstraints: []

affinity: {}

# If specified, the gateway will act as a network gateway for the given network.
networkGateway: ""

imagePullSecrets: []

**Comment by keithmattix** [comment]
The selector for the ingress gateway changes between istioctl and helm installation methods; you can't just use the same Gateway resource. Check the labels of the ingressgateway deployment, specifically the `istio:` label. That should match the selector in the Gateway. Since you said the request works with the same `Gateway` resource, I bet the issue is your selector

**Comment by sakethkumardamera** [comment]
Hi Keith,

Thanks for helping me out, the below is the deploy file of istio-ingress, the istio label is set to *ingress*:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: istio-ingress
    meta.helm.sh/release-namespace: istio-system
  creationTimestamp: "2023-05-22T14:52:25Z"
  generation: 1
  labels:
    app: istio-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/version: 1.16.4
    helm.sh/chart: gateway-1.16.4
    istio: ingress
  name: istio-ingress
  namespace: istio-system
  resourceVersion: "18078668"
  uid: a179a440-ef65-4c22-afb4-f6530061cdd6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingress
      istio: ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: istio-ingress
        istio: ingress
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: auto
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      serviceAccount: istio-ingress
      serviceAccountName: istio-ingress
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-22T14:52:31Z"
    lastUpdateTime: "2023-05-22T14:52:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-22T14:52:25Z"
    lastUpdateTime: "2023-05-22T14:52:31Z"
    message: ReplicaSet "istio-ingress-54464bcb87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by sakethkumardamera** [comment]
The below is my gateway files:
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"httpbin-gateway","namespace":"istio-system"},"spec":{"selector":{"istio":"ingress"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2023-05-18T10:40:52Z"
  generation: 2
  name: httpbin-gateway
  namespace: istio-system
  resourceVersion: "18384078"
  uid: 1fb2a2ab-e22f-434b-8a03-c66fc46c91b8
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP

**Comment by sakethkumardamera** [comment]
The below is my virtual service:
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"httpbin","namespace":"istio-system"},"spec":{"gateways":["httpbin-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/headers"}}],"route":[{"destination":{"host":"httpbin","port":{"number":8000}}}]}]}}
  creationTimestamp: "2023-05-18T10:40:52Z"
  generation: 1
  name: httpbin
  namespace: istio-system
  resourceVersion: "15916786"
  uid: 85a4692d-0c0b-435f-abaa-7c82ec8106cc
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000

**Comment by sakethkumardamera** [comment]
I can see the selector is same
if am going wrong anywhere, please let me know, i think only the ingress is having a problem, any help is greatly appreciated

**Comment by sakethkumardamera** [comment]
This is my Loadbalancer service yaml file:
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"httpbin","service":"httpbin"},"name":"httpbin","namespace":"istio-system"},"spec":{"ports":[{"name":"http","port":8000,"targetPort":80}],"selector":{"app":"httpbin"}}}
    creationTimestamp: "2023-05-18T10:32:46Z"
    labels:
      app: httpbin
      service: httpbin
    name: httpbin
    namespace: istio-system
    resourceVersion: "15913643"
    uid: 635046df-624c-48f8-89da-518501366753
  spec:
    clusterIP: 10.xxx.xxx.51
    clusterIPs:
    - 10.xxx.xxx.51
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 80
    selector:
      app: httpbin
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: istio-ingress
      meta.helm.sh/release-namespace: istio-system
    creationTimestamp: "2023-05-23T04:23:26Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: istio-ingress
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: istio-ingress
      app.kubernetes.io/version: 1.16.4
      helm.sh/chart: gateway-1.16.4
      istio: ingress
    name: istio-ingress
    namespace: istio-system
    resourceVersion: "18389938"
    uid: 943d83d3-b2e0-4cbd-839d-fb11586b2f8e
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.xxx.xxx.100
    clusterIPs:
    - 10.xxx.xxx.100
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: status-port
      nodePort: 32251
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 30938
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30619
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: istio-ingress
      istio: ingress
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 20.xxx.xxx.61
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: istiod
      meta.helm.sh/release-namespace: istio-system
    creationTimestamp: "2023-05-22T14:26:28Z"
    labels:
      app: istiod
      app.kubernetes.io/managed-by: Helm
      install.operator.istio.io/owning-resource: unknown
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      release: istiod
    name: istiod
    namespace: istio-system
    resourceVersion: "18068666"
    uid: 186b2eb7-7c2c-4f41-9226-d6904b9d34d2
  spec:
    clusterIP: 10.xxx.xxx.23
    clusterIPs:
    - 10.xxx.xxx.23
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc-xds
      port: 15010
      protocol: TCP
      targetPort: 15010
    - name: https-dns
      port: 15012
      protocol: TCP
      targetPort: 15012
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: 15017
    - name: http-monitoring
      port: 15014
      protocol: TCP
      targetPort: 15014
    selector:
      app: istiod
      istio: pilot
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}

**Comment by keithmattix** [comment]
The formatting on your manifests makes it difficult to tell what the exact configuration is; could you use code blocks:
```
Surround this with 3 back ticks
```

Or upload the redacted manifests

**Comment by sakethkumardamera** [comment]
Thanks Keith, doing a fresh install solved the problem for me. I really appreciate you for taking your time to help me out
