### ISSUE TITLE
merge istio.io/pkg into istio.io/istio/pkg

### ISSUE THREAD

**Issue by zirain** [istio/istio#44991]
came from https://github.com/istio/istio/pull/44981#issuecomment-1553748861

cc @howardjohn @jacob-delgado

**Comment by howardjohn** [comment]
There is some usage beyond istio/istio. bots uses log,env,cache,ctrlz. release-builder uses log. tools uses log. istio.io uses log.

Probably if we want to do this we can come up with a solution for log (https://github.com/istio/istio/issues/44683) then would be fine. maybe copy some functions into bots if needed, not a huge concern to have a little bit of copying for non-critical code

**Comment by costinm** [comment]
Even if there is usage beyond istio/istio - we can keep the old code as is ( but deprecated ).

Yes, big +1 - there is no point in Istio defining its own separate logging / metrics / etc API. 

We should also switch to slog when it becomes available, etc.

**Comment by zirain** [comment]
everything is done, feel free to reopen if I miss somehting.

**Comment by zirain** [comment]
sync https://github.com/istio/pkg/pull/813
