### ISSUE TITLE
proxy: init container cannot manipulate iptables with selinux enforcing

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4500]
When selinux is enforcing withing RHEL, the iptables rules do not appear properly setup when the init container runs. 

> First error first time the init container is run: `iptables: No chain/target/match by that name.`
Second error (and forever after) the init container is run: `iptables: Chain already exists`

with selinux set to enforcing, the following error appears

```
`type=AVC msg=audit(1521747498.758:3677): avc:  denied  { module_request } for  pid=486 comm="iptables" kmod="ipt_REDIRECT" scontext=system_u:system_r:svirt_lxc_net_t:s0:c388,c684 tcontext=system_u:system_r:kernel_t:s0 tclass=system`
```

istio version: 0.6.0
OS: RHEL 7.4
Environment:  OpenShift Origin 3.9 rc / kube 1.9

**Comment by cmluciano** [comment]
Possibly related issues:

https://github.com/istio/issues/issues/34
https://github.com/istio/issues/issues/172
https://github.com/istio/istio/issues/1435

**Comment by cmluciano** [comment]
FWIW upstream k8s discussion on NET_ADMIN policy https://github.com/kubernetes/kubernetes/issues/55435#issuecomment-366703250

**Comment by thoraxe** [comment]
```
oc version
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://176.126.88.38:8443
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
```

Also
```
selinux-policy-3.13.1-166.el7_4.9.noarch
selinux-policy-targeted-3.13.1-166.el7_4.9.noarch
iptables-1.4.21-18.3.el7_4.x86_64
iptables-services-1.4.21-18.3.el7_4.x86_64
```

And
```
Linux openshift-93d9.rhpds.opentlc.com 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thoraxe** [comment]
Command to launch some things:

```
export ISTIO_HOME=/opt/lab/istio-0.6.0
export PATH=${PATH}:${ISTIO_HOME}/bin
export LAB_HOME=/opt/lab/istio-lab-summit-2018
oc new-project foo
oc adm policy add-scc-to-user privileged -z default -n foo
oc apply -f <(istioctl kube-inject -f ${LAB_HOME}/src/customer/src/main/kubernetes/Deployment.yml)
```

https://github.com/jamesfalkner/istio-lab-summit-2018/blob/master/src/customer/src/main/kubernetes/Deployment.yml is the referenced source file. `istioctl` is injecting the sidecar and init.

**Comment by cmluciano** [comment]
@thoraxe For version  v3.9.0-alpha.3+78ddc10 is this something that one would have to download and start for the Openshift repo? It doesn't look like I can launch that with minishift.

**Comment by thoraxe** [comment]
This more or less gets you there...

```
OC_VERSION="v3.9.0-alpha.3"
GIT_STRING="-78ddc10"
wget https://github.com/openshift/origin/releases/download/$OC_VERSION/openshift-origin-server-$OC_VERSION$GIT_STRING-linux-64bit.tar.gz
tar -xzvf openshift-origin-server-$OC_VERSION$GIT_STRING-linux-64bit.tar.gz
mv openshift-origin-server-v3.9.0-alpha.3-78ddc10-linux-64bit/oc /usr/bin
restorecon -rv /usr/bin
oc cluster up --public-hostname="$LC_MYIP" \
  --routing-suffix="$LC_MYIP.xip.io" \
  --use-existing-config \
  --host-data-dir=/var/lib/origin/openshift.local.data

cd /opt/lab/istio-0.6.0
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin developer
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system
oc adm policy add-scc-to-user anyuid -z grafana -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc create -f install/kubernetes/istio.yaml
oc project istio-system
oc expose svc istio-ingress
oc apply -f install/kubernetes/addons/prometheus.yaml
oc apply -f install/kubernetes/addons/grafana.yaml
oc apply -f install/kubernetes/addons/servicegraph.yaml
oc expose svc servicegraph
oc expose svc grafana
oc expose svc prometheus
oc process -f https://raw.githubusercontent.com/jaegertracing/jaeger-openshift/master/all-in-one/jaeger-all-in-one-template.yml | oc create -f -
```

**Comment by cmluciano** [comment]
great! And just to be sure that I run under the exact conditions, are you docker or CRI-O and can you list the version of these?

**Comment by thoraxe** [comment]
```
$ rpm -qa | grep docker
docker-common-1.13.1-53.git774336d.el7.x86_64
docker-1.13.1-53.git774336d.el7.x86_64
docker-rhel-push-plugin-1.13.1-53.git774336d.el7.x86_64
docker-client-1.13.1-53.git774336d.el7.x86_64
```

Sorry about that. Good point.

**Comment by thoraxe** [comment]
The deployment in my examples/reproducer uses images that are not public, but are built onto the host.

https://github.com/jamesfalkner/istio-lab-summit-2018

If you clone this repo and then install Maven and Java:

```
cd
curl -sL http://apache.mirrors.tds.net/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz | (cd ~; tar -xvzf -)
yum install java-1.8.0-openjdk-devel
export PATH=${PATH}:${HOME}/apache-maven-3.5.3/bin
```

Then you can run the build script:

```
/path/to/repo/clone/scripts/build-images.sh
```

This will result in the various images being locally available in the Docker daemon image cache.

**Comment by cmluciano** [comment]
Ok just tried this out with the same settings on RHEL with Selinux 

```
sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

I get the following error when I try to launch the sleep pod 

```
  Warning  FailedCreate  47s (x15 over 2m)  replicaset-controller  Error creating: pods "sleep-68c6b77b6-" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1337: must be in the ranges: [1000070000, 1000079999]]
```

I'm not sure if this is a red herring or not since it may suggest that my project doesn't have the correct Openshift settings.

**Comment by thoraxe** [comment]
Yup. now do:

`grep deni /var/log/audit/audit.log` and you'll see an AVC denial.

Then `setenforce=0` and try again.

**Comment by cmluciano** [comment]
I have a few results after more testing and found a few issues:

## Sidecar defaults
In our docs we mention several ways of injecting the sidecar but the logic and instructions do not inherently require someone to use the [istio-inject configmap](https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl). During setup we recommend bootstrapping Istio with `kubectl apply -f ./install/kubernetes/istio.yaml` . I think this  yields the very minimum settings required for the sidecar [here](https://github.com/istio/istio/blob/release-0.6/install/kubernetes/templates/istio-config.yaml.tmpl). A file injected manually with istioctl will default to these settings and the template will not fill in the correct NET_ADMIN privileges. 

**Possible options for sidecar docs:** 

- Highlight the need for adding the istio-sidecar-injector-release.yaml file from the setup instructions and using the configMap option for manual injection
- Add the release.yaml to the istio.yaml in place of the current default settings

## Privilege settings

The release configmap only adds minimal NET_ADMIN securityContext settings for the init container but this is either not enough for SeLinux/AppArmor or there is a subtle bug in our [prepare_proxy.sh script](https://github.com/istio/istio/blob/master/pilot/docker/prepare_proxy.sh).

** Possible problems **

- The release configmap sets the run user for the proxy as [1337](https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl#L16-L17) but we do not create that user except in the case of the [proxy debug container](https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.proxy_debug#L14-L17)
  - We either need to remove the -u setting for init and fall back to whatever the default is for the proxy_init or add the logic to the init container that we have in proxy
  - If we truly do add these settings, we may need to consider adding additional CAP settings to allow the container to manage user settings
- If I use the debug settings and then delete the sleep sample and restart it with the release settings, everything passes successfully. 
  - This makes me think we are doing more than manipulating iptables rules in the release init container

**Comment by cmluciano** [comment]
cc @ayj @costinm ^

**Comment by ayj** [comment]
> A file injected manually with istioctl will default to these settings and the template will not fill in the correct NET_ADMIN privileges.

By default istioctl uses the embedded configuration template defined in https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/mesh.go. The `injectConfigMapName` and `injectConfigFile` flags override these defaults. The former configmap flag would typically be set to `istio-inject` (which corresponds to the [sidecar injection configmap](https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl) and not `istio` (which corresponds to the overall mesh configuration).

> Highlight the need for adding the istio-sidecar-injector-release.yaml file from the setup instructions and using the configMap option for manual injection.

It seems reasonable to install the injection configmap by default. It doesn't have any affect if the sidecar injector itself isn't installed.

> Privilege settings

See https://github.com/istio/istio/blob/master/pilot/doc/proxy-redirection-configuration.md for some background information on use of UID for network capture via iptables.

**Comment by thoraxe** [comment]
So apparently part of the issue is that SELinux prevents containers from causing kernel modules to be loaded, and using iptables (within a container?) ends up requiring the ipt_REDIRECT module, which can't be loaded.

Setting SELinux to permissive I guess allows the container to cause this module to be loaded, because subsequently enforcing and then re-attempting the init container works. Presumably because the kernel module then is loaded.

I haven't tested/looked at this myself, yet. But Dan Walsh suggested that's what's happening.

**Comment by cmluciano** [comment]
@ayj @costinm What do you think we should do with this? Is this an issue that only affects SeLinux/AppArmor usage?

**Comment by thoraxe** [comment]
So the issue is actually somewhat different than what I think we originally expected.

```
oc adm policy add-scc-to-user privileged -z default -n foo
```

This sets the default SA to be able to use the privileged SCC. But the key word here is `able`. It doesn't mean `will`. When `istioctl` is used to inject the sidecar, it does so. However it does not correctly add an explicit `privileged` requirement (with 0.6) for the sidecar. It also doesn't declare what caps (eg: `NET_ADMIN`) the sidecar needs.

So, while the issue only manifests with SELinux + `istioctl` injection, it's still actually an issue regardless. SELinux is ultimately preventing the "accidental" situation.

If you run with SELinux enforcing and correctly require `privileged` for the sidecar then you actually end up with a privileged sidecar, which is allowed to load the modules, which makes everything work AOK.

As a side note, OpenShift is looking at admission controller-based auto-injection of the sidecar on pods with specific annotations. With a "properly" (I don't say that to be mean) written sidecar that explicitly requires `privileged` everything works happily on SELinux enforcing systems.

Not sure if this helps advance the issue. IMO the actual problem is that `istioctl` injection doesn't create a properly defined sidecar with the right privs.

**Comment by cmluciano** [comment]
still relevant and awaiting review in #6487

**Comment by justinmoninger** [comment]
I have a similar issue, was this ever addressed?
