### ISSUE TITLE
how can we implement security header with envoyfilter on gateway level, please suggest.

### ISSUE THREAD

**Issue by 1a2k3m** [istio/istio#45016]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
Examples are: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#configuration and https://istio.io/latest/docs/reference/config/networking/envoy-filter/. Combine the gateway and envoy lua examples should work.
