### ISSUE TITLE
unsupported service type "ExternalName"

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#45014]
When i followed the steps in  [Install Primary-Remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote). and it look like install success.
 When trying to create a deployment in the remote cluster it fails when trying to create a sidecar container in the pod with the following error.

Failed calling webhook, failing closed [namespace.sidecar-injector.istio.io](http://namespace.sidecar-injector.istio.io/): failed calling webhook “[namespace.sidecar-injector.istio.io](http://namespace.sidecar-injector.istio.io/)”: failed to call webhook: Post “[https://istiod.istio-system.svc:443/inject/cluster/cluster2/net/network1?timeout=10s](https://istiod.istio-system.svc/inject/cluster/cluster2/net/network1?timeout=10s)”: unsupported service type “ExternalName”

I don’t understand why it says: unsupported service type “ExternalName”. I use K8s 1.24, istio 1.16.4

**Comment by zirain** [comment]
I don't think `HookClient` support ExternalName type service.
IIRC, istio use headless service in docs.

**Comment by id-id-id** [comment]
> I don't think `HookClient` support ExternalName type service. IIRC, istio use headless service in docs.

I have follow [Install Primary-Remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote) and I use eks，Loadbalance type service import to eks，it will create a  clb.

I set remotePilotAddress: xxx.ap-southeast-1.elb.amazonaws.com and use istioctl install to install in remote cluster, it seems that istio install a externalName type service name istiod in istio-system

**Comment by zirain** [comment]
IIRC, in primary-remote mode, there's istiod deploy in remote cluster response for validating webhook, discovery address will be overwrited to istiod-remote.istio-system.svc.

**Comment by id-id-id** [comment]
> IIRC, in primary-remote mode, there's istiod deploy in remote cluster response for validating webhook, discovery address will be overwrited to istiod-remote.istio-system.svc.

There is no istiod in remote cluster,  in [Install Primary-Remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote).  cluster2 is remote cluster, and istiooperator.yaml as follow,
![image](https://github.com/istio/istio/assets/49929614/f4b6e172-7b10-4948-bf33-06b2b924ea94)

I find profile remote in istio-1.16.4/mainfest/profile, it will not install istiod and ingress-gateway in remote cluster
![image](https://github.com/istio/istio/assets/49929614/97e35b1b-9e68-4008-80ed-672789443c3e)

**Comment by zirain** [comment]
I find the root cause:

https://github.com/istio/istio/blob/86184316a9c7cdd488d34f01279ea73ffb13812b/manifests/charts/istiod-remote/templates/services.yaml#L22

cc @frankbu , please take a look.

**Comment by id-id-id** [comment]
I have also try to change istiod service from externalName to headless， and  use clb's ip、istod pod ip in primary cluster which set in endpoint, But it show's
Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": Address is not allowed

**Comment by id-id-id** [comment]
I change the operator.yaml， set injectURL: https://xxx.com:443/inject, and then I create a pod with sidecar, error message show：
Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://xxx.com:443/inject?timeout=10s": context deadline exceeded:Deployment does not have minimum availability.

istiod in primary culster is ok，and I can send request in another pod in remote cluster to istiod in primary cluster using command "curl -k https://xxx.com:443/inject". Log in istiod is :
error no body found

**Comment by ramaro-meli** [comment]
same issue here following the tutorial, trying to do it on AWS and also replaced the remotePilotAddress with the load balancer fqdn

**Comment by id-id-id** [comment]
来信已收到，祝好！

**Comment by PetrMc** [comment]
seeing the same - any solutions or workarounds any one found?
