### ISSUE TITLE
Bad interaction between Tomcat Tribes and istio for headless service

### ISSUE THREAD

**Issue by thomas-z-meyer-db** [istio/istio#45021]
### Bug Description

We deploy distributed webapp on Tomcat on k8s and use DNSMembershipProvider (https://github.com/apache/tomcat/blob/main/java/org/apache/catalina/tribes/membership/cloud/DNSMembershipProvider.java) via k8s headless service to establish Tomcat session replication.

Problems seems to arise when doing an rolling upgrade, the new Tomcat pods seems to receive strange stray traffic from old Tomcat Tribes IPv4 addresses from isito.

It feels like, that some book keeping in istio fails to update all IPv4 address for headless service while doing a rolling update.

We did mitigate the problem for now by using Recreate strategy which seems to work with istio but gives short downtime while upgrading workload versions.

### Version

```Text
$ kubectl version --short
Client Version: v1.23.0
Server Version: v1.24.11-gke.1000

istio version sidecar:
gcr.io/gke-release/asm/proxyv2:1.15.7-asm.8-distroless
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Its a bit hard to help here without more explanation of the traffic flow as we (or at least, I) am not familiar with Tomcat. What is the client and server doing, and what is experiencing the error?

**Comment by thomas-z-meyer-db** [comment]
Hi, thanks for looking into this. I'll add a bit more details here the next days.
But generally the Tomcat Tribes finds all Tomcat members that should be part of the cluster and establish TCP communication on port 4000+ between all members of the cluster.

**Comment by thomas-z-meyer-db** [comment]
when running with two fresh pods, both members will see each other:

Replication member added:[org.apache.catalina.tribes.membership.MemberImpl[tcp://240.4.193.36:4000,240.4.193.36,4000, alive=-1, securePort=-1, UDP Port=-1, id={-47 48 -89 -22 63 -34 48 -18 23 94 -82 -21 -103 94 -85 119 }, payload={}, command={}, domain={}]]

Replication member added:[org.apache.catalina.tribes.membership.MemberImpl[tcp://240.4.193.179:4000,240.4.193.179,4000, alive=-1, securePort=-1, UDP Port=-1, id={48 16 61 127 91 123 31 41 49 109 -120 47 64 124 -42 -109 }, payload={}, command={}, domain={}]]

After a rolling update the tribes will start to log to receive invalid packets which looks like coming from previous deployment pod's ip addresses, I need to configure DEV and reproduce then I'll add details here
