### ISSUE TITLE
Use SHARED_MESH_CONFIG in e2e suite if specified. 

### ISSUE THREAD

**Issue by nshankar13** [istio/istio#45023]
**Describe the feature request**

E2E Test Suite should use `SHARED_MESH_CONFIG` when making changes to Istio MeshConfig / ConfigMap, if specified. 

Currently, the testing framework [patches the default](https://github.com/istio/istio/blob/1c70653e0eec55aed47674590767cd2dd4e8ff64/pkg/test/framework/components/istio/configmap.go#L207-L217) ConfigMap when making changes to the MeshConfig. However, in environments / setup that use the `SHARED_MESH_CONFIG`, users may want the test framework to patch the local shared ConfigMap instead. This can be specified using a [flag](https://github.com/istio/istio/blob/master/pkg/test/framework/components/istio/flags.go) `ex: --use-shared-mesh-config` when running the testing command. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Just curious, if there are 2 configmaps why does it matter which is patched?

**Comment by nshankar13** [comment]
@howardjohn for instance, external / hosted control plane setups, to better mimic user flow. Or other setups where default ConfigMap may not be directly accessible or modifiable to user.

**Comment by mikemorris** [comment]
Should this be closed as implemented in #46074?

**Comment by nshankar13** [comment]
@mikemorris yes, will do.
