### ISSUE TITLE
Telemetry: configure tracing to remove certain default tags

### ISSUE THREAD

**Issue by zohar-arista** [istio/istio#45031]
**Describe the feature request**
The zipkin traces emitted via the Istio Sidecars by default have many tags. According to https://istio.io/latest/docs/reference/config/telemetry/#Tracing, currently there is an option to add more custom tags, but no option to customize/remove certain default ones. We are wondering if it's possible to add this functionality?

**Describe alternatives you've considered**
We have tracing disabled globally with only a couple of services overriding this. Still, we are seeing that having all of the default tags can really load our ElasticSearch backend. This is a real blocker for us from onboarding the rest of our k8s apps onto the mesh since we would like to support global tracing by default.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by imnmo** [comment]
@RaiAnandKr is that the issue is going to be fixed in the Envoy where it generates those tags. In istio we have a feature https://istio.io/latest/docs/reference/config/telemetry/#Tracing-CustomTag but _only_ for adding. So, this is not an existing feature in Telemetry API

can we close this issue if not relevant

**Comment by zohar-arista** [comment]
Hi @imnmo, you may close it, thanks.
