### ISSUE TITLE
GAMMA: remove requirement for ReferenceGrant

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#45056]
Required by https://github.com/kubernetes-sigs/gateway-api/pull/2029

**Comment by hzxuzhonghu** [comment]
I donot find out api change.

 https://github.com/kubernetes-sigs/gateway-api/blob/4738c6c6e981d4a0e38c8c6120dc0198e4128351/apis/v1beta1/shared_types.go#L149-L154
