### ISSUE TITLE
Allow to control tracing decision via Telemetry API

### ISSUE THREAD

**Issue by p-v-a** [istio/istio#45075]
**Describe the feature request**
At the moment there is no way to defer tracing decision to allow downstream to control it. With random sampling rate set to 0%, Istio inserts "x-b3-sampled: 0" header, thus disarming application tracing downstream. Suggestion is to implement defer sampling state as per https://github.com/openzipkin/b3-propagation#sampling-state, i.e. add an option to control headers if Istio decides not to sample.

**Describe alternatives you've considered**
There is no alternative, except disabling tracing all together.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
@p-v-a are you talking about tail sampling?

**Comment by zirain** [comment]
I'm not sure if that avaliable for envoy, cc @kyessenov do you have a certain answer.

**Comment by p-v-a** [comment]
@kyessenov any updates on this one?
