### ISSUE TITLE
Envoy filter with REMOVE operator doesn't follow config patch order

### ISSUE THREAD

**Issue by psinghal20** [istio/istio#45089]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In our setup, we wanted to manipulate the order of certain custom filters we added in the filter chains. To re-order the filters, we created EnvoyFilters with two config patches:

1. Patch to delete the existing filter
2. Patch to re-insert the filter in the correct order

Expected behavior:
Correct ordering of filter

Observed behavior:
The filter is only deleted and not re-inserted at the correct position.

After taking a look into the code, I found that we handle the filter removal after processing all the patches in an envoy filter. This leads to the re-inserted filter getting deleted. Code ref: [listener_patch.go](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go#L233-L242)

The documentation mentions that all the patches part of a filter are applied in order. According to documentation, this envoy filter should work as expected.

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.17.2-9da3bf6ae4
data plane version: 1.17.2-9da3bf6ae4 (9 proxies)
```

```
$ k version --short
Client Version: v1.22.5
Server Version: v1.23.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zhaohuabing** [comment]
@psinghal20 Can you use REPLACE operation instead?
