### ISSUE TITLE
Istio Ambient Ztunnel not working with custom  root CA

### ISSUE THREAD

**Issue by nabbdl** [istio/istio#45102]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We deployed ISTIO Ambient using the following command 
According to the following [documentation ](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)we created the **cacerts** secret
**./istioctl install --set profile=ambient**.
the mesh has been activated in the default namespace using the label 
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-05-24T06:22:19Z"
  labels:
    istio.io/dataplane-mode: ambient
    kubernetes.io/metadata.name: default
  name: default
```
We then tested the connectivity between 2 pods on the same node which work fine 
```
ztunnel-ppbkd istio-proxy 2023-05-24T14:38:09.436578Z  INFO outbound{id=bd14b3817fb180844f406ddf22fc9211}: ztunnel::proxy::outbound: proxying to 10.20.129.70:9080 using node local fast path
ztunnel-ppbkd istio-proxy 2023-05-24T14:38:09.436969Z  INFO outbound{id=bd14b3817fb180844f406ddf22fc9211}: 
ztunnel::proxy::outbound: complete dur=489.707µs
```

We tested using 2 pods on different nodes and we hit the certificate issue 
```
ztunnel-ppbkd istio-proxy 2023-05-24T14:38:34.880224Z  INFO outbound{id=dc060faa8c5de3671f0584c862202db7}: ztunnel::proxy::outbound: proxy to 10.20.128.129:9080 using HBONE via 10.20.128.129:15008 type Direct
ztunnel-87qj8 istio-proxy 2023-05-24T14:38:34.888218Z  WARN ztunnel::hyper_util: TLS handshake error: tls handshake error: Failure(MidHandshakeSslStream { stream: SslStream { stream: PollEvented { io: Some(TcpStream { addr: [::ffff:10.20.128.129]:15008, peer: [::ffff:10.20.129.68]:33495, fd: 21 }) }, ssl: Ssl { state: "TLS 1.3 server read_client_certificate", verify_result: X509VerifyResult { code: 65, error: "Invalid certificate verification context" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 268436504, library: "SSL routines", function: "OPENSSL_internal", reason: "TLSV1_ALERT_UNKNOWN_CA", file: "../ssl/tls_record.cc", line: 594, data: "SSL alert number 48" }]))) } })
```
We also validated that the root ca is correctly mounted on the ztunnel pods
` k -n istio-system exec -it ztunnel-9k777 -- curl https://istiod.istio-system.svc:15012 --cacert ./var/run/secrets/istio/root-cert.pem`

The certificates works perfectly using a sidecar deployment.

### Version

```Text
./istioctl version
client version: 1.18.0-beta.1
control plane version: 1.18.0-beta.1
data plane version: 1.18.0-beta.1 (6 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.9
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by jaellio** [comment]
I can take a look into this

**Comment by jaellio** [comment]
@nabbdl Are you still experiencing this error? I was unable to replicate the error using the steps you provided. I installed istio with the ambient profile in a kind cluster with 3 nodes (1 control plane and 2 worker nodes). Prior to installing istio, I created a cacerts Secret using the linked instructions. I deployed an httpbin pod in node A and sleep pods in nodes A and B. I was able to exec into both sleep pods in both nodes and curl the httpbin pod. Am I missing a step?

**Comment by nabbdl** [comment]
@jaellio  I tested it using the RC release. I have to give it a try with the latest release and I'll let you know. Which version did you use for your test ?

**Comment by jaellio** [comment]
@nabbdl I used v1.18.0-alpha

**Comment by nabbdl** [comment]
@jaellio I also enabled the Ambient Mesh using the label on the Namespace : 
kubectl label namespace default istio.io/dataplane-mode=ambient .
 Are you seeing any traffic in the Ztunnels containers ?
Just to be more specific on what we have done, we followed the documentation regarding the certificates just to see what is expected in the cacerts secrets but we are using our own PKI and certificates are not generated using the provided scripts. Our cacerts is working using a non-ambient Istio deployment.

**Comment by jaellio** [comment]
Yes, I was seeing traffic in the Ztunnel containers. And yes, I followed the same steps. Were you able to try this again with the latest release?

**Comment by nabbdl** [comment]
Hello @jaellio. It works now with version 1.18.0.
I'm closing the issue
