### ISSUE TITLE
Outlier Detection: Pods are not getting ejected at once

### ISSUE THREAD

**Issue by BharathKumarRavichandran** [istio/istio#45128]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi folks!

We are using outlier detection in the traffic policy of Istio in production. We have three replicas of hello-world deployment managed by Knative serving, running in a namespace. We have the below outlier detection configured for the host - `hello-world-kl49t-00008`. 

Pods:
```
NAME                                                              READY   STATUS    RESTARTS   AGE
hello-world-kl49t-00008-deployment-58ccfkxb   3/3     Running   0          16m
hello-world-kl49t-00008-deployment-58cfgn27   3/3     Running   0          16m
hello-world-kl49t-00008-deployment-58clqsnl   3/3     Running   0          16m
```

Our configuration:
```
  host: hello-world-kl49t-00008
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 60s
      consecutive5xxErrors: 5
      interval: 20s
      maxEjectionPercent: 100
```

Observations:
We can see the pods are getting ejected one by one. That is, we see the ejection only after around fifteen 5xx calls. Is this the expected behavior?

Expected:
We expected the pods to get ejected after five 5xx calls as per the configuration.

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.16-dev
data plane version: 1.16-dev (44 proxies)

$ kubectl version --short
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by Pawan-Bishnoi** [comment]
`consecutive5xxErrors: 5` is per host.

So _a given host_ is ejected from client's pool only if **it** returns 5 consecutive 5xx to the client.

**Comment by BharathKumarRavichandran** [comment]
Thank you. We assumed that five is for all three replicas. Is each replica treated as a separate host?

**Comment by hzxuzhonghu** [comment]
yes, https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#outlier-detection

**Comment by BharathKumarRavichandran** [comment]
Thanks for confirming. We verified it and it is working as explained, hence closing this.
