### ISSUE TITLE
discoverySelector should also limit gateway deployment controller

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#45137]
when ENABLE_ENHANCED_RESOURCE_SCOPING = true, discoverySelector should also take effect on gateway deployment controller.

**Comment by hzxuzhonghu** [comment]
@howardjohn It seems crd namespace filter is broken by #44145

**Comment by howardjohn** [comment]
We should add tests, or it will keep getting broken. I will take a look, but can you or @kfaseela work on adding test coverage for this feature?

**Comment by hzxuzhonghu** [comment]
Yeah, i will take a deep look

**Comment by hzxuzhonghu** [comment]
@kfaseela What does this address mean? 
https://github.com/istio/istio/blob/35a63bf00851ab49a8c5ed22fc4cdf08a01ed6e6/tests/integration/pilot/multiplecontrolplanes/main_test.go#L223

**Comment by hzxuzhonghu** [comment]
I think i have found out the cause. It is that in the tests one control plane have revusion: user-group-1 set, while the SE does not have revision set, so the case (https://github.com/istio/istio/blob/35a63bf00851ab49a8c5ed22fc4cdf08a01ed6e6/tests/integration/pilot/multiplecontrolplanes/main_test.go#L204-L207) passsed even without namespace filter

**Comment by hzxuzhonghu** [comment]
Need to fix both crd client and the tests

**Comment by kfaseela** [comment]
@hzxuzhonghu I tried putting the revision to SE, but still the test passes. Did I miss anything? https://github.com/istio/istio/pull/45156/files

**Comment by hzxuzhonghu** [comment]
PTAL https://github.com/istio/istio/pull/45181, i guess it is because after SE created, it has not take effect yet before we run the 1st test case

**Comment by hzxuzhonghu** [comment]
Gateway part has not been resolved

**Comment by hanxiaop** [comment]
not stale
