### ISSUE TITLE
samples: build and publish istio/examples-helloworld-v1

### ISSUE THREAD

**Issue by jewertow** [istio/istio#45143]
Implementation of `istio/examples-helloworld-v1` was recently updated to support IPv6, but the image was not built and published and therefore it still does not work on IPv6 clusters.

```
docker run istio/examples-helloworld-v1 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Could someone from maintainers build and publish this image?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by jewertow** [comment]
@ericvn can you help?

**Comment by howardjohn** [comment]
I just did it, in https://github.com/istio/istio/pull/45149. lmk if you have issues please

**Comment by ericvn** [comment]
I believe this issue is complete in the main branch via https://github.com/istio/istio/pull/45149. Please reopen this issue if there is still an issue.
