### ISSUE TITLE
mTLS Testing tutorial

### ISSUE THREAD

**Issue by overip** [istio/istio#4514]
I was trying to test the mTLS following the tutorial here https://istio.io/docs/tasks/security/mutual-tls.html
The problem is in "Step 4" of the "Testing the authentication setup" part, in which you are supposed to log into the productpage proxy and send requests to another service, for example, details using curl. Curl is not installed in the proxy, and its filesystem is read only, so you can't just log into the proxy container and install curl.

Thanks

**Comment by jsenon** [comment]
Do we update documentation /cc @ayj, do we add curl into istio-proxy image ? or do we have to use istio-proxy:debug ? /cc @ldemailly

**Comment by ldemailly** [comment]
#4384

**Comment by wattli** [comment]
I will add a note in that page

**Comment by wattli** [comment]
curl is expensive, i add a note to that page about how to specify proxy_debug

**Comment by ldemailly** [comment]
> curl is expensive

in what way(s) ?

(I know we want to ultimately support native http health checks well, yet in the meantime curl is a practical solution, no ?)

@wattli  we can't ask production use cases to use proxy_debug

**Comment by wattli** [comment]
https://github.com/istio/istio.github.io/pull/1097

**Comment by wattli** [comment]
@ldemailly , this thread is not about health check or production use case. It's about https://istio.io/docs/tasks/security/mutual-tls.html does not work.

**Comment by ldemailly** [comment]
yes you're right, for that it is fine
(though we should anyway add curl but we can revert the doc later/once we do)

thanks!

**Comment by wattli** [comment]
PR is merged, and will be visible on istio.io in 0.7 release
