### ISSUE TITLE
Istio 1.16.4 returning GRPC Unavailable instead of deadline exceeded

### ISSUE THREAD

**Issue by bhavaniMiro** [istio/istio#45141]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Context: We are upgrading from Istio `1.14.1` to `1.16.4` in all our k8s clusters. While this version is soon going to be out of scope for support (June 2023), we're working our way up the revisions. In the service mesh, we have a microservice that issues outbound GRPC requests to our monolith (outside EKS). There is a valid service entry for this monolith but no virtual service.

The microservice has historically managed its own GRPC backoff and retry behaviour and set deadlines without using any Istio config to do so. (Nothing configured explicitly in terms of CRDs / no config for Envoy Route objects). These outgoing requests contain a  `grpc timeout` header (set to 150ms)  and the service gracefully deals with deadline exceeded errors (GRPC status code 4). 

Upon moving to Istio 1.16.4, we noticed a low volume of errors where when a deadline is reached, the Istio sidecar proxy reports: `UT upstream request timeout`  with a `GRPC Unavailable` (status code (14)) error.  This unexpected change correlates with the upgrade:

Digging further:
* [This commit](https://github.com/istio/istio/pull/42049/files#diff-b2f924815daf6eb7b30db8abf1ee1defd28b61effd0e9902834249f355bc001bL1081-R1082) moved away from using `maxStreamDuration` to `maxGrpcTimeout` exclusively and got picked up in our upgrade.
* However, as a result of this move - there seems to be a side effect on how global timeouts are configured. If I'm reading this correctly, we're now going down [this](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L141) branch in envoy itself where the global timeout is being set to whatever is in the header (150ms). With Istio `1.14.1` (via `maxStreamDuration` and `GrpcTimeoutHeaderMax` set to 0) the global timeout would have been left as is (0ms) . 
* Consequently, this now non-zero global timeout is probably also surfacing the `UT upstream request timeout` [here](https://github.com/envoyproxy/envoy/blob/v1.24.5/source/common/router/router.cc#L923-L924) even in the case of some real spotty upstreams.

Perhaps this is more nuanced for our use case but by switching to `maxGrpcTimeout` - this seems to complicate how a microservice can be on the service mesh _and_ manage its own GRPC timeouts. 

As a workaround, we can use EnvoyFilters to keep `maxStreamDuration`, but just wondering if this is norm now.

### Version

```Text
1.16.4
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
cc @ramaraochavali
