### ISSUE TITLE
make WorkloadEntry address optional

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#45161]
Allow setting only Network (and optionally Weight) on WorkloadEntry to manually register cross-network workloads without secret reading. We won’t need the actual address.

https://docs.google.com/document/d/1q9k_8FK49u2-yMCRVPcINWco-0QRjreVp5V-U4gweSE/edit?resourcekey=0-a3ZnyKPJ-r-LH6l3GkbRsg#heading=h.lgufgrw83iky

**Comment by kdorosh** [comment]
@stevenctl can we add a link to the PR here?

still working on some corner cases, e.g. SE selects WE and addresses expecting to be present
