### ISSUE TITLE
Use gateway resource to represent remote e/w gateways

### ISSUE THREAD

**Issue by linsun** [istio/istio#45172]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Per @stevenctl 's doc to this Wed's WG meeting which was directionally approved at the meeting:

https://docs.google.com/document/d/1GdCjGvlDdDsVtDSiyo7MXz0mdx9ekgF7AoHP34yUwuI/edit

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kdorosh** [comment]
@stevenctl going to update the istio docs with GatewayAPI rather than script. deployment part has worked for a while (undocumented) and the discovery part will be up for implementation after

**Comment by kdorosh** [comment]
resolved by https://github.com/istio/istio/pull/45342
