### ISSUE TITLE
Identify WIs needed to drive dual stack to alpha

### ISSUE THREAD

**Issue by linsun** [istio/istio#45171]
**Describe the feature request**

Dual stack is experimental atm, we need to evaluate to move it to next phase (which is alpha), starting with sidecars first.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kdorosh** [comment]
@ilrudie is looking to start this (hopefully) around EOD

**Comment by ilrudie** [comment]
https://github.com/istio/enhancements/blob/master/features/dual-stack-support.md has a list of items needed for alpha and beyond

**Comment by linsun** [comment]
Need to understand if supporting upstream MC is important for Solo.

Single cluster works pretty well for dual stack.

**Comment by linsun** [comment]
Prep for demo tmr, spent time to help GM platform with their ipv6 issue.

Pushed a PR for upstream to make one of our sample easier with ipv6.

**Comment by linsun** [comment]
did a good demo/q + a this morning.  looking into answers for some questions

**Comment by kdorosh** [comment]
friday demoed this, seems like possible CP bugs in configuring the dual stack dataplane. digging into and debugging further, generally seems to work. will need more docs for alpha

**Comment by kdorosh** [comment]
yesterday began looking at why behavior of dual stack is different (sometimes auto downgrade to ipv4 and sometimes it wont). may be worth asking in `#dual-stack` community slack channel

**Comment by kdorosh** [comment]
spent more time yesterday working on hostname lookup in ztunnel, and then john approved and it merged before feedback was addressed, but it was entirely nits.

**Comment by kdorosh** [comment]
yesterday reached out to the community about some of the aforementioned outstanding questions. tried testing locally on kind, ran into issues that at face value look like istio-init failing on ipv6 (kind-net cni seems at fault. if calico replacement used then things work fine)

may need to open an issue with kind itself
