### ISSUE TITLE
istiod to support auto reload istiod-service-account-token after k8s CA renew

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#45184]
We are using first-party-jwt for authentication:

      - name: JWT_POLICY
        value: first-party-jwt

It will actually load the token created by k8s sa controller and init the kubeclient. However since our k8s root CA expired and after rotated the k8s root ca the secret `istiod-service-account-token-8pwxx` for service account `istiod-service-account` got updated but istiod/kubeclient doesn't reload the token for the istio ca:

https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/istio_ca.go#LL152C28-L152C38
```
token, err := os.ReadFile(getJwtPath())
```
And kubeclient is init during bootstrap: https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/server.go#L546
```
s.kubeClient, err = kubelib.NewClient(kubelib.NewClientConfigForRestConfig(s.kubeRestConfig))

```
We got error like below in istiod, basically it's control plane outage and have to recreate the istiod pods to recover:
```
2023-05-29T07:02:58.769875Z	warn	serverca	Authentication failed for 10.0.0.1:36802: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT from cluster "Kubernetes": Post "[https://192.168.0.1:443/apis/authentication.k8s.io/v1/tokenreviews](https://192.168.0.1/apis/authentication.k8s.io/v1/tokenreviews)": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes-certs").
2023-05-29T07:02:58.867460Z	error	ads	Failed to authenticate client from 10.0.0.2:42422: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "Kubernetes": Post "[https://192.168.0.1:443/apis/authentication.k8s.io/v1/tokenreviews](https://192.168.0.1/apis/authentication.k8s.io/v1/tokenreviews)": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes-certs")
```
Got error in the code here https://github.com/istio/istio/blob/master/security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go#L153 due to the istio kubeclient doesn't reload the jwt token and k8s ca cert, it failed to authenticate the client request against the k8s apiserver.
```
reviewRes, err := kubeClient.AuthenticationV1().TokenReviews().Create(context.TODO(), tokenReview, metav1.CreateOptions{})
if err != nil {
  return nil, err
}
```
So although kubernetes updates the ca.crt under /var/run/secrets/[kubernetes.io/serviceaccount](http://kubernetes.io/serviceaccount), the kubeclient in istiod doesn't dynamically reload the new CA and token which causes issue.

**Describe alternatives you've considered**
Better istiod can auto reload the jwt token and k8s ca certs after rotation, so we don't have to restart the istiod pods for the k8s cert rotation.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shonecyx** [comment]
fixed by https://github.com/istio/istio/pull/42237/files

**Comment by howardjohn** [comment]
Why use 1p jwt? It is insecure and deprecated since Kubernetes 1.12(!!). We are considering removing it as well.

I am pretty sure client-go does not  handle CA rotating, you need restart. Even in core: https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/. 

Also it has nothing to do with the jwt token afaik?

**Comment by shonecyx** [comment]
Thanks @howardjohn. We'll consider to change to 3p jwt since we are upgrading both istio and k8s version.

Although jwt token is not related with this particular error which is due to kubeclient doesn't handle k8s ca rotation,  the jwt token is loaded by istio_ca during the bootstrap and since it's not dynamicly loaded, I think it would be broken as well, although restart istiod can cover both.

Not sure if there is plan to support the dynamic k8s ca rotation, there are some other cases ca/cert rotation covered like https://github.com/istio/istio/pull/42237, better we can cover the k8s ca rotation as well.

**Comment by howardjohn** [comment]
> Although jwt token is not related with this particular error which is due to kubeclient doesn't handle k8s ca rotation, the jwt token is loaded by istio_ca during the bootstrap and since it's not dynamicly loaded, I think it would be broken as well, although restart istiod can cover both.

Its just looked at once to determine if 1p or 3p jwt. Not used beyond that.

> Not sure if there is plan to support the dynamic k8s ca rotation

AFAIK there is not _even in Kubernetes core_. So I am not sure why Istio would do this -- everything else in the cluster needs to restart, so spending effort making it seemless in Istio is a waste IMO

**Comment by shonecyx** [comment]
Thanks @howardjohn. Then we'll need build some automation/pipeline for our k8s cluster root ca rotation and automatically restart whatever needed.
