### ISSUE TITLE
Forward traces from application

### ISSUE THREAD

**Issue by frzifus** [istio/istio#45220]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

It would be nice to be able to report traces of an application directly to envoy and forward them to the same datastore. This would remove the need for a jaeger collector or open telemetry sidecar.

Kuma does something similar with metrics:
https://kuma.io/docs/2.2.x/policies/traffic-metrics/#expose-metrics-from-applications

**Describe alternatives you've considered**
Deploy a sidecar that reports to the same datastore.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Kuma does it with _metrics_ - not traces. Istio does this as well: https://istio.io/latest/docs/ops/integrations/prometheus.

Its not clear how we can actually do this for traces which are push based, unless we become a full on trace-proxy. Which means we are basically re-inventing otel sidecar?

**Comment by frzifus** [comment]
> Kuma does it with metrics - not traces. Istio does this as well: https://istio.io/latest/docs/ops/integrations/prometheus.

Right, this request is about traces. 

> Its not clear how we can actually do this for traces which are push based, unless we become a full on trace-proxy. Which means we are basically re-inventing otel sidecar?

I agree, it would be a kind of trace-proxy. I would not call it a re-invention of the otel sidecar. The otel collector does a number of things such as enriching the data with attributes, removing sensitive information or authenticating to the datastore. Some of these steps are not necessary if, for example, you are using auto-instrumentation. In this case, the Otel Sidecar is often only there to write information to the datastore. In such scenarios it would be handy if Envoy could manage the forwarding of this information.

**Comment by howardjohn** [comment]
what exactly do you need it to do though? Istio is already forwarding *all* network traffic including  traces

**Comment by frzifus** [comment]
An endpoint on the sidecar that accepts traces and sends them to the datastore configured in the sidecar. So that the application / sdk does not have to worry about authentication etc.

**Comment by howardjohn** [comment]
But that is exactly what the otel sidecar does, a bit worried we would be duplicating everything that does (but probably worse)

**Comment by zirain** [comment]
Istio supports agent mode collector, IMO that's enough for most. do you have special use case?

**Comment by frzifus** [comment]
> But that is exactly what the otel sidecar does, a bit worried we would be duplicating everything that does (but probably worse)

The OTEL Collector does more. It can be used to translate protocols, e.g. from zipkin to otel or vice versa. You can apply some filters, attach or drop labels, control sampling, handels auth and so on. But if you use e.g. Java Auto Instrumentation, the otel collector often simply forwards the messages. 

In this example the otel-collector and Enovy1 would both report traces that belong to each other into tempo. But the otel-collector and Envoy1 would carry the credentials to authenticate against tempo. Since envoy would simply forward all messages. If the destination for the traces reported from enovy changes, the application would still report them to the old destination. 

```mermaid
graph TD;
    App1--zipkin-->otel-collector;
    otel-collector--"zipkin"--> Envoy1;
    Envoy1--"forwarding zipkin"-->tempo;

    App2-- zipkin -->Envoy2;
    Envoy2 --zipkin-->tempo;
```

What I am looking for is what App2 does. It reports traces to Enovy2 (maybe localhost:1234) and envoy takes care.

> Istio supports agent mode collector, IMO that's enough for most. do you have special use case?

Could you share a link to the details? Went to the documentation and couldnt find something like this.

**Comment by frzifus** [comment]
thx, let me check and come back to you.
