### ISSUE TITLE
Allow providers to be defined using Service/ServiceEntry

### ISSUE THREAD

**Issue by costinm** [istio/istio#45247]
**Describe the feature request**

Right now all 'providers' are defined in MeshConfig - which effectively means they must be configured by the mesh admin 
at install / upgrade time and have a per-istiod revision scope ( each revision must define them, they apply to all workloads using that revision).  

In many cases - OTel destination, external Authz service - it is desirable to have a different granularity ( per namespace)
and allow namespace administrator to define the provider without reinstalling Istiod. 

The 'providers' are usually regular services - internal or external - that are translated into Envoy clusters and used
by envoy filters. Some providers have extra config - which would require some proper CRD and are out of scope for this.

The proposal is to use a specific label for each provider that corresponds to a service - for example:

istio.io/provider: grpcAuthz  - to define a service that can be used for external authz.

Istiod will select all Service/ServiceEntry with this label and make them available to workloads in same 
namespace. If they are defined in istio-system - they can be merged with the providers in MeshConfig. 

The provider name would match with the Service or ServiceEntry name. 

**Describe alternatives you've considered**

An alternative is to just allow external authz or telemetry to specify a FQDN:port as provider name, 
and resolve it to a cluster (and corresponding Service / ServiceEntry ). 
 
This is simpler - the extra label is intended mostly to allow OPA or other policies to control the definition
of providers, if the mesh admin needs that. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
A few comments/concerns.

**Provider types**

I did an exercise of looking through the providers. We currently have 14.

3 types do not reference a service at all (prom, stdout log, stackdriver)
The other 11 all reference a service and _all_ have custom configuration. I subjectively decided 7 of these were probably typically not set, while 3 very likely were set by users (and I guess I didn't have an opinion on 1...).

**Service attachment**

A provider is actually a Service+port pair, I think we are missing the port in this proposal.

**Namespace scope**

I am concerned with only "same namespace" or "istio-system". The majority of users are going to have telemetry services in a dedicated namespace (`monitoring`, `open-telemetry`, whatever). This is not supported by this proposal as far as I can tell - or worse, leads to people deploying in `istio-system` which is a Bad Idea.

**Comment by costinm** [comment]
The 3 without service are out of scope, and I don't see any harm in just having them available by default so they can be referred. The extension providers I'm most interested in is OTel and authz. Quite a few follow the same pattern as otel, and can work with the defaults - we will need to find some place for the extra config, either by extending the API or having some 'policy attachment'. 

Another thing the 11 have in common is that they don't allow the typical configs we have for Services - and I am not entirely sure that if they point to a K8S Service, the normal DestinationRule/etc configs will apply. 

For port - we can relax the validation on provider name. The 'alternative' is to just allow FQDN:port when the defaults can be used.

For namespace scope: 'same namespace' is at least better than 'global per istiod revision' that we have now. What I mean by 'same namespace' is that the owner of the namespace can defines where telemetry goes for that namespace - 
it can be a ServiceEntry where you can use any hostname (egress) but I think we also allow destinations in other namespaces. 

The goal is to move from a 'global install option' to a 'namespace owner controls telemetry/authz/etc for that namespace'. There are other options to do this - but the ServiceEntry + DestinationRule allows taking advantage of the
current settings. 

Someone proposed recently an 'external Gateway' resource that represents a Gateway we don't provision but treat it as a gateway - we can use a similar model too. 

I'm not very attached to using Service/ServiceEntry - my goal is to find an alternative to the global/install only scope, 
and a way to be able to apply the normal Istio ( or Gateway) policies to all providers that have an address.

**Comment by costinm** [comment]
BTW - it is also fine to leave the telemetry as a 'mesh admin / global option' that namespace owners have no control over ( except by running their own code to generate telemetry ). 

I was trying to use an external authz provider - which is possible as namespace admin using an EnvoyFilter. Unfortunately it has a lot of other options.  Maybe Kuat's "constrained envoy filters" would be a better option.

**Comment by costinm** [comment]
@kyessenov

**Comment by costinm** [comment]
I think mixing authz and telemetry under one concept of "provider" is a pretty bad API, and most of the providers are telemetry and may actually not be so bad as install options. We can wait a bit for OTel protocol adoption to pick up - 
if we end up with Otel collector becoming most common, it will make the other providers obsolete. Also I don't think Ztunnel will support all the providers - most likely will be prom + otel only.

I opened this bug with Authz in mind - how to allow an app to select a custom ext-authz endpoint, and while 
defaults may work for what I was trying - there are a lot of important options there ( which headers to pass, etc). 
And since this is very envoy specific - your approach of 'constrained envoy filter' seems a much better option.

I think the only remaining request for this bug is to see if we can have DestinationRule, ServiceEntry, etc apply to 
whatever hostname is selected for a provider. The providers generate clusters - we should be able to apply 
the configs to most of them. That includes using Hbone if the telemetry service is using ambient for example.

**Comment by kyessenov** [comment]
Even if we use EnvoyFilter, we need good guidance for concrete issues with the way Istio generates xDS:
- Stable names for the "generated" clusters, services or service entries. We need a stable naming alias to refer to them. Since some of these are also programmed (tunneling, SDS), it's preferred to re-use existing clusters than add another one.
- Scoping the clusters to the clients. We need a controlled way to push ServiceEntries/Services/providers only to those clients that need them.

**Comment by costinm** [comment]
Yes, agreed. But it may not be so urgent for telemetry, things may sort themselves out naturally. OTel collector can run as daemon set and doesn't need a lot of settings, prometheus is not a real provider anyways - and the rest may just go away or be handled by otel collector. So out of the 14 providers - we may be left with very little in the telemetry side.

Ok, will close this - but please add ext-authz to the list of EnvoyFilters we may want to 'constrain' and move out of 
mesh config.

**Comment by howardjohn** [comment]
> I think the only remaining request for this bug is to see if we can have DestinationRule, ServiceEntry, etc apply to
whatever hostname is selected for a provider. The providers generate clusters - we should be able to apply
the configs to most of them. That includes using Hbone if the telemetry service is using ambient for example.

We already do this
