### ISSUE TITLE
Usability: Base chart name can be an issue for local helm chart repositories

### ISSUE THREAD

**Issue by fsniper** [istio/istio#45256]
The chart `istio/base` makes sense in the context of istio helm repositories. However some organizations choose to setup their helm repos to hold upstream helm chart for different purposes. 

If a organization wants the helm chart in their repositories this can cause a name conflict, or inaccuracy of the name to define what this package is about. 

E.g. : `my-upstream-repo/base` would not make sense. 

An alternative could be adding `istio-` prefix to the base helm chart name.

[ ] Ambient
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by howardjohn** [comment]
Why not `my-upstream-repo/istio/base`?

**Comment by howardjohn** [comment]
Actually realizing that may only work with OCI registries?

**Comment by fsniper** [comment]
I think you are right. It would not work on non OCI repos.
