### ISSUE TITLE
Deploy Mixer Custom Adapter Instuctions Not Working

### ISSUE THREAD

**Issue by jmiller-boundless** [istio/istio#4530]
Followed instructions located at
https://github.com/istio/istio/blob/master/mixer/doc/deploy-mixer-with-custom-adapter.md
to deploy a custom Mixer adapter.  Running **_bazel run //mixer/docker:mixer_** from istio.io/istio directory returns _**ERROR: The 'run' command is only supported from within a workspace.**_

Adding an empty "WORKSPACE" file and rerunning the command just yields:
**_ERROR: Skipping '//mixer/docker:mixer': no such package 'mixer/docker': BUILD file not found on package path_**

There is no MAKEFILE in the Mixer directory and it is not clear which target in root MAKEFILE is appropriate for just deploying a Docker container with Mixer alone??

Bazel version info:

Build label: 0.11.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 07:48:23 +50148 (1520362424903)
Build timestamp: 1520362424903
Build timestamp as int: 1520362424903

**Comment by christian-posta** [comment]
Unfortunately, it looks like this doco is out of date. 

See here for how mixer gets built:

https://github.com/istio/istio/blob/master/Makefile#L342

See this file for how the docker images get built:

https://github.com/istio/istio/blob/master/tools/istio-docker.mk

**Comment by douglas-reid** [comment]
@jmiller-boundless I'm sorry you ran into this. When we moved off of bazel, those instructions were not updated, as there was a large amount of churn and little desire to fight that churn via docs. Things have settled down more reasonably now, and we will be updating those docs in short order (with any luck).

**Comment by jmiller-boundless** [comment]
Thanks christian-posta.  We followed these steps and are now checking to see if it worked:
1)Created an istio.io directory under $GOPATH/src
2)Cloned https://github.com/istio/istio into that directory
3)Ran "dep ensure" to make sure we had the correct GO dependency versions of everything
4)Followed the instructions in https://github.com/istio/istio/blob/master/mixer/doc/adapter-development-walkthrough.md and validated locally 
5)Added the istio-docker.mk file to the istio.io/istio directory
6)Built the docker image by calling make docker.mixer
7)Pushed the image to our container registry using our usual methods
8)Edit our Mixer deployment configuration to reference the image in our container registry

Do the above steps sound correct?  The first Makefile you referred to uses "gobuild.sh" but I am not sure if that is necessary if go build and go install steps from the development walkthrough do the trick?

**Comment by mandarjog** [comment]
`istio-docker.mk` should already be included in the top level makefile.
`bin/gobuild.sh` ensures correct platform and it also creates a fully static binary so it would be better if you use it.

**Comment by jmiller-boundless** [comment]
Ok, before running make docker.mixer I am running the following to compile from the istio.io/istio directory:
bin/gobuild.sh ~/go/bin/mixs pkg/version ./mixer/cmd/mixs
If that seems correct I will go ahead and close the issue and hopefully it will help other folks who get stuck before the documentation gets updated

**Comment by douglas-reid** [comment]
@jmiller-boundless can you try the steps in https://github.com/istio/istio/pull/4561 ? I'd like to have validation that they work for others too.

**Comment by vinayvenkat** [comment]
Hi guys, 
I followed this guide and everything worked. However it seems that it does not complete the story and might be missing some parts or making assumptions about next steps. 

I think it would be good to add the following:

- explicitly state the deployment of Istio and talk about both scenarios. 
   i.e when istio has not been deployed already and when istio has already been deployed (which I believe is referenced in the statement that "if mixer has already been deployed ... ".

- additionally, information on how to query the logs to confirm the invocation of the adapter would be an additional great value add. 

Thoughts? @douglas-reid 
Thanks.

**Comment by douglas-reid** [comment]
@vinayvenkat I think all of this may now be obsolete. We recently added support for out-of-process Mixer adapters to Istio. Your suggestions are probably better applied to the docs being developed to support that use case, as that is the next step in the evolution of custom adapter support in Mixer.

cc: @guptasu who is developing those docs as we exchange these messages.

**Comment by vinayvenkat** [comment]
@douglas-reid Thanks for the response. If thats the case what is the recommended development and testing framework for someone trying to develop, integrate and test custom adapters? Also are you suggesting that I cannot use the in-built adapter approach for testing purposes? 

@guptasu : Do you have any recommendations on how I can build and test my custom adatper.

Thanks in advance.

**Comment by guptasu** [comment]
Hi @vinayvenkat 

Here are two examples of testing your custom adapters 
1. for in-built compiled in adapters: write integration test
sample 1: https://github.com/istio/istio/blob/master/mixer/adapter/prometheus/prometheus_integration_test.go
sample 2: 
https://github.com/istio/istio/blob/master/mixer/adapter/list/list_integration_test.go
sample 3:
https://github.com/istio/istio/blob/master/mixer/adapter/redisquota/redisquota_integration_test.go

2. For out-of-process Mixer adapters: write same integration test like in-proc
sample 1: 
https://github.com/istio/istio/blob/master/mixer/test/prometheus/prometheus_integration_test.go

sample 2:
https://github.com/istio/istio/blob/master/mixer/test/listbackend/list_integration_test.go

Regarding how to write an out-of-proc adapter (a.k.a gRPC adapter) here is the first doc that is still under development
https://github.com/istio/istio/wiki/gRPC-Adapter-Walkthrough

**Comment by guptasu** [comment]
@douglas-reid @vinayvenkat the documentation for gRPC adapters is done (I have requested for review):
https://github.com/istio/istio/wiki/Out-Of-Process-gRPC-Adapter-Dev-Guide
This contains link to the walk through on how to create a sample gRPC adapter.

Let me know if anything is wrong.
