### ISSUE TITLE
Provide direct support for country code headers 

### ISSUE THREAD

**Issue by gurbachan-singh** [istio/istio#45306]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [ ] This is not a question about how to use Istio

### Bug Description

Can you guys help us to implement country code headers in the the Istio 

Nginx has a module called GeoIP that allows setting a country code header based on the source IP address. We currently in the process of migrating from Nginx to istio and don't see this functionality parity. We do take certain actions based on the IP address such as country blocking, localization / translation of some content, specific content based on country, policies, etc. 

### Version

```Text
Isito version : 1.11.2 & 1.15.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by kanurag94** [comment]
IMO, this could be possible through writing your own extension where you call an external service once the request comes and provide `X-Forwarded-For` header to the same. The service returns back with some response which you use to set headers. Envoy filters and Lua extensions are your way to go.

**Comment by ramaraochavali** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/geoip_filter - may be of interest
