### ISSUE TITLE
Slow to recover WorkloadEntry when cleaned up by ownerRef

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#45329]
If the WorkloadGroup for an auto-registered WorkloadEntry is deleted, the WorkloadEntry is automatically deleted due to the OwnerRef. 

If the WorkloadGroup is re-created, it can take up to 30 mins (by default) for the WorkloadEntry to be recreated by the proxy reconnecting and triggering that flow. 

Possible solutions:
* User manually restarts the proxy/connection to control plane
* #45328 don't use the ownerRef to begin with. The WorkloadEntry fail its next reconnection and the workload entry will eventually expire (1 hour+). The WorkloadEntry will be recreated quickly after the WorkloadGroup is re-added. 
* #45209 immediately force disconnect the proxy so it retries aggressively. The WorkloadEntry will be recreated quickly after the WorkloadGroup is re-added. 
* #44709 immediately re-create the WorkloadEntry for connected proxies when a WorkloadGroup is re-added.

**Comment by stevenctl** [comment]
Created this tracking issue to get agreement on what to do here.
I don't feel strongly one way or another, but my preference is that the contract of WorkloadGroup + connection = WorkloadEntry. If that means proxies require WorkloadGroup to be connected I'm pretty OK with that. 


cc @howardjohn @costinm @hzxuzhonghu @shashankram

**Comment by shashankram** [comment]
> Created this tracking issue to get agreement on what to do here. I don't feel strongly one way or another, but my preference is that the contract of WorkloadGroup + connection = WorkloadEntry. If that means proxies require WorkloadGroup to be connected I'm pretty OK with that.
> 
> cc @howardjohn @costinm @hzxuzhonghu @shashankram

I like this contract, though would like to understand the impact on performance and complexity in the control plane to book-keep this. If this ends up adding a fair bit of complexity and impacts performance negatively, a simpler solution such as not cleaning up WE's via OwnerRef might be worth considering.

We do need a mechanism to ensure we don't need to mutate a fleet of VMs to recover from this scenario.

**Comment by hzxuzhonghu** [comment]
Get to know what you mean `slow`. 

>If the WorkloadGroup for an auto-registered WorkloadEntry is deleted, the WorkloadEntry is automatically deleted due to the OwnerRef.

If we donot want WLG to be deleted by accident, there maybe approach adding a finalizer to WLG, and this is widely used in `cluster-api` project.

If it is intended to delete the WLG, i have no idea why expect WLG->WLE to be recreated

**Comment by shashankram** [comment]
> Get to know what you mean `slow`.
> 
> > If the WorkloadGroup for an auto-registered WorkloadEntry is deleted, the WorkloadEntry is automatically deleted due to the OwnerRef.
> 
> If we donot want WLG to be deleted by accident, there maybe approach adding a finalizer to WLG, and this is widely used in `cluster-api` project.
> 
> If it is intended to delete the WLG, i have no idea why expect WLG->WLE to be recreated

Users may create/delete a resource. We shouldn't build the control plane with the assumption that the WG can't be deleted. Control plane should be resilient to this versus needing users to restart a fleet of VMs individually.

We need to determine the contract for autoregistered WE as described in https://github.com/istio/istio/issues/45329#issuecomment-1580252768

**Comment by costinm** [comment]
Resilience is exactly the reason why deleting a WG should not result in all
the VMs breaking at the same time.

**Comment by hzxuzhonghu** [comment]
I mean if it is by accident, who create WLG should protect it from being deleted by accident, finalizer is a good way

**Comment by shashankram** [comment]
Given we want to improve resiliency and ensure stale WEs are removed, can we do the following:
1. Delete autoregistered WEs upon corresponding proxy disconnect after a reasonable duration since a disconnect 
2. GC autoregistered WEs using OwnerRef associated with Istiod deployment/pod instead of WG

This way, as long as the proxy has the necessary config and certs to connect, it can. If the VM is removed, Istiod will eventually delete the corresponding WE. If Istiod is deleted, all autoregistered WEs will be deleted. And most importantly, deleting a WG has no effect on autoregistered WEs.

**Comment by costinm** [comment]
AFAIK 'stale WE' should be removed anyways - based on connection timestamp,
etc. I thought we have this already, it was part of the design and I think
I reviewed some of the code. Not only on disconnect ( plus the interval we
have to avoid churn ) - but also in startup of istiod, to deal with cases
where istiod
crashes or fails to clean.

IMO we need to stay in the middle and avoid both extremes - I think it is
bad to auto-disconnect all VMs if the WG is removed by accident, but it is
also bad to allow new connections from VMs without a WG. The WG acts as a
permission for auto-registration, we don't want to allow VMs to
register arbitrarily.

It is unfortunate that we use WG as an authz policy - I wish we had a
proper RBAC granting the SA on the VM permission to create WE in the
namespace, with an agent on the VM that is more aligned with the VM
lifetime, and a kubeconfig in the VM that would also simplify getting the
certs. I suppose this can still be implemented independently, may be worth
having some example in istio-ecosystem...

**Comment by hzxuzhonghu** [comment]
>It is unfortunate that we use WG as an authz policy

This is to register WLE, if we donot need auto register feature, this is not a must

**Comment by stevenctl** [comment]
Finalizer actually seems pretty reasonable to me. If a WG is in finalizing state, refuse new connections. Eventually the WG gets deleted when all the proxies disconnect and their WEs expire. 

I don't actually know and don't see anything with a quick search saying cancelling a finalizer is valid.

**Comment by howardjohn** [comment]
Sorry to bikeshed but I think finalizers always lead to a **terrible** user experience. There is nothing more frusterating than `kubectl delete namespace` getting blocked. The description on https://github.com/ibuildthecloud/finalizers is much more polite than what I say every time a project has broken finalizers (which happens very often...) :slightly_smiling_face: . I would rather do almost anything but finalizers

**Comment by stevenctl** [comment]
RE: Authz

The group gates discoverability. Not discovery. The proxy could get rid of it's AUTOREGISTER_GROUP meta and still receive xDS. 

The check we have is a protection against user error since we depend on ordering.

**Comment by stevenctl** [comment]
A reason we don't have any user reports for this could be that it resolves itself _somewhat_ quick (if you consider 30-60 minutes quick). Roughly the time someone might spend before posting something, then it resolves it self.

**Comment by shashankram** [comment]
> This leads me to believe #44709 was the right choice after all. The contract is "connection + group" not "_new_ connection".

+1 based on reasoning. It seems like a simple fix which would significantly improve the UX when WGs are removed and recreated, either accidentally by the user or in test scenarios involving a lot of WGs churning.

**Comment by hzxuzhonghu** [comment]
WLG + proxy connection leads to WLE register, now we set WLE's ownerref to the WLG. Ideally we should set connection as another owner, but unfortunately there is no such API for connection.

The problemis :if WG is deleted accidently, the WLEs are automatically deleted, but once WLG is recreated again, the WLEs cannot recover until proxy reconnects maybe delay 30min.

Proposed solution: How about recording the connections from proxies that need autoRegistration, and handle WLG create event, when a WLG created, we cam search for the connections, and register WLEs immediately.

**Comment by costinm** [comment]
Agree with John finalizer is worst option.

For a product focused on security - we have a pretty poor design and review
process on our own security. Auto registration allows anyone with a JWT or
cert to create pod-equivalents with arbitrary IP which receive traffic for
services. Only thing that can be trusted from client is the signed jwt or
cert - anything else is completely untrustable.

The primary purpose of WG is to restrict what can be registered - what SA (
which hopefully is checked against the cert), labels are allowed. Deleting
a WG should prevent new registration - just like removing an authz prevents
new connections, but doesn't close existing ones.

I am ok with deleting the WE when WG is deleted - or with keeping them.
What concerns me is abruptly closing the connections, but if we can confirm
we have good test coverage for exponential backoff and all affected VMs
reconnecting at once is safe - maybe it's fine. I have seen (or caused :-)
prod outages by disconnecting lots of clients at once - but with much
larger scale. Like security, we do too little prod robustness review on our
features and rarely consider larger scale.

But we can't prevent an user for causing an outage if they insist on
deleting WG - there are 100s of other ways to cause outages if user
insists.

**Comment by stevenctl** [comment]
WDYT about just making the CP quickly re-add the WorkloadEntries when the resource is re-added? @costinm

**Comment by costinm** [comment]
Adding WE when a WG is created is an interesting idea. It solves the accidental deletion with lower risks, and matches behavior with Service delete and recreate ( for endpoints).

I assume it would not be re-create - but create too ?

The main purpose of WE is to sync endpoints - original impl used Endpoints object, it had some problems which are mostly addressed now with EndpointSlices. So having a behavior similar to ES is not bad.

**Comment by shashankram** [comment]
> I assume it would not be re-create - but create too ?

Seems reasonable. @stevenctl do you a problem with auto-creating WEs from WGs for autoregistered proxies that are connected?

**Comment by stevenctl** [comment]
> Adding WE when a WG is created is an interesting idea. It solves the accidental deletion with lower risks, and matches behavior with Service delete and recreate ( for endpoints).

Well, that was the original approach I took. I just updated the PR #44709
