### ISSUE TITLE
Istiod not applying config changes from configmap until manually restarted

### ISSUE THREAD

**Issue by artrojort** [istio/istio#45340]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello

When updating Istio configmap values (in this case updating traceparent entry for log format), changes are not picked up by the Istiod agent.

**What we have tried:**
1. Modify Istio confimap `kubectl edit configmap istio`
2. Enter new value for entry 

**What we expected to happen:**
Istio proxy logs to reflect new config

**What actually happened:**
Istiod doesn't reflect new config, new traces were still not available in logs produced by istio proxy

### Version

```Text
$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.6

$ helm version --short
v3.10.2+g50f003e
```

### Additional Information

Current workaround we found was manually deleting Istiod pods which made the new pods come up with the updated configmap values

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
can you show exactly what field you were setting? It's not super clear to me.

Note anything under `defaultConfig` is not dynamic - istiod will update it dynamically but proxy pods need to restart

**Comment by praveenjindal62** [comment]
We made a change as below. Added a new entry in `accessLogFormat`.  

```
mesh: |-
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: |
      {
        <added a new entry here>
      }
```

We had to do a restart of istiod, before pilot could pick up new change and start including newly added entry in istio-proxy logs. 

Is this expected ? Or we should have given more time to istiod to automatically apply changes to all the pilot?

**Comment by zirain** [comment]
I don't think so, can you check istiod's logs, maybe there's a unmarshal issue.

**Comment by praveenjindal62** [comment]
I'll try to create this and get back

**Comment by praveenjindal62** [comment]
It is working for us, I might have missed something last time and thought it is not working. Issue can be closed. Thanks for all your help and clarification.
