### ISSUE TITLE
Question: Why does the changes of VirtualService effect the LDS?

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#45347]
When only the resource VirtualServices changes, istiod will trigger LDS push. 
Do we really need to push LDS? Or Maybe I miss something.

**Comment by wulianglongrd** [comment]
At least outbound LDS depends on VS, such as the `tcp_proxy` filter depends on VS.tcp

**Comment by SpecialYang** [comment]
> At least outbound LDS depends on VS, such as the `tcp_proxy` filter depends on VS.tcp

But, if I only care about VS.http, do we still need to rebuild LDS and trigger push?

**Comment by ramaraochavali** [comment]
There is no such fine grained control whether the modified VS has http or tcp only and then decide to build LDS or not. We will have to look at previous config and current config and decide whether the new one needs LDS push or not.

**Comment by SpecialYang** [comment]
> There is no such fine grained control whether the modified VS has http or tcp only and then decide to build LDS or not. We will have to look at previous config and current config and decide whether the new one needs LDS push or not.

Got it. Thanks.
