### ISSUE TITLE
Support AWS ECR Pull Through Cache

### ISSUE THREAD

**Issue by jwenz723** [istio/istio#45365]
**Describe the feature request**

I would like to request that official istio release container images be pushed/published to an image registry which is supported by [AWS ECR Pull Through Cache](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html?icmpid=docs_ecr_hp-registry-private). AWS ECR Pull Through Cache currently only supports the following public image registries:

* Amazon ECR Public
* Quay
* Kubernetes (registry.k8s.io)

https://github.com/istio/istio/issues/31296 mentions the https://istio.io/latest/blog/2020/docker-rate-limit/ blog post which describes that istio consumers can pull from the gcr.io/istio-release mirror. This indicates that istio is currently supporting publishing new images to both gcr.io and docker.io. So a 3rd registry could in theory be supported.

The kubernetes project images are migrating away from gcr.io and into registry.k8s.io, see [here](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/). Maybe it makes sense for istio to do the same? I'm not sure if istio images would be allowed to be pushed to that particular registry. If not, then Amazon ECR Public or Quay would both be viable options.

**Describe alternatives you've considered**

Currently my team has a manual way of copying images into our private AWS ECR registry. See `Additional context` below.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

My company has a policy enforced on our various kubernetes clusters that disallows the consumption of container images which exist in public image registries. We've built automation to copy the istio images from docker.io/istio into our private AWS ECR registry. Currently we do this by essentially running `docker pull`, `docker tag`, and then `docker push`. This means that if we want to deploy a new version of istio into our clusters we have to do the following:

1. Trigger our automation to copy the new image tag.
2. Update our kubernetes manifests to consume the new image tag.

With AWS ECR Pull Through Cache feature we would be able to eliminate step number 1. The new image tag would be copied automatically into our private ECR registry at the time when they are pulled by our kubernetes clusters.

**Comment by zirain** [comment]
cc @ericvn

**Comment by howardjohn** [comment]
Istio cannot publish to k8s.io.

Historically hosting on AWS has been very challenging for the project from an infrastructure perspective, but this may be a bit easier with the CNCF move. But this would likely require someone investing many hours into making this work and footing the bill ~indefinitely before this would be feasible.
