### ISSUE TITLE
Support integration/e2e tests on local machines

### ISSUE THREAD

**Issue by hklai** [istio/istio#4536]
Context: https://goo.gl/2DPP5o

Figure out and document the steps to run integration/e2e tests using a local cluster (e.g. using Docker on mac/windows, and possibly minikube on linux similar to circleci), instead of having to set up GCP and GKE.

**Comment by hklai** [comment]
Discussed a few options today and @louiscryan suggested starting with https://github.com/flix-tech/vagrant-kubernetes, which is an easier solution to templatise.

Current plan:
@kimikowang will try it out on mac, and @JimmyCYJ will try it out on linux.
In the mean time @gargnupur is going to figure out setting up local docker registry.

We will regroup next Monday to share findings.

**Comment by kimikowang** [comment]
I am testing the vagrant vm on Mac, but got stuck at the kube-dns brought-up loop in `vg-01-repartioton.sh`.  @JimmyCYJ How is your test on Linux? Does everything work well?

**Comment by JimmyCYJ** [comment]
I have the same issue, and I tried several fixes but could not solve it.

**Comment by JimmyCYJ** [comment]
@kimikowang could you try this example?
https://github.com/pires/kubernetes-vagrant-coreos-cluster

It works on my personal desktop (Ubuntu 16.04). I simply run sudo USE_KUBE_UI=true vagrant up. 
I get some issues when I run this example in my office workstation, and I am trying to fix.
I am not sure if it works on Mac.

**Comment by kimikowang** [comment]
Thanks @JimmyCYJ , let me try to give it a shot.

**Comment by JimmyCYJ** [comment]
@kimikowang for https://github.com/flix-tech/vagrant-kubernetes, I tried 1.10.0 and 1.9.0 on Ubuntu 16.04, and they failed at different steps.

**Comment by kimikowang** [comment]
@JimmyCYJ I have no luck in bring up the coreos vm onMac. It stops at booting stage.

**Comment by JimmyCYJ** [comment]
@kimikowang There is a trouble shooting section in https://github.com/pires/kubernetes-vagrant-coreos-cluster#troubleshooting. Does it help?

**Comment by kimikowang** [comment]
@JimmyCYJ Unfortunately no, the problem is at the ssh process to the vm. This seems to be a well-known issue for vagrant, and it seems to be problems with VirtualBox or MacOS. Most of people solved the problem simply by upgrading VB or Mac to latest version. I did that already, but no help.

**Comment by JimmyCYJ** [comment]
@kimikowang Could you copy and paste parts of the output from your terminal?

**Comment by kimikowang** [comment]
Just created an issue under the flux-tech repo: https://github.com/flix-tech/vagrant-kubernetes/issues/12

**Comment by JimmyCYJ** [comment]
Filed an issue under pires/kubernetes-vagrant-coreos-cluster: https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/293

**Comment by JimmyCYJ** [comment]
Filed an issue on missing .kube/config file.
https://github.com/flix-tech/vagrant-kubernetes/issues/13

**Comment by ldemailly** [comment]
see https://github.com/istio/istio/issues/593#issuecomment-324404846 for issues with the previous incantation of the process (though then at least there was a way, albeit undocumented, to run 1 e2e tests multiple times; I'm looking forward to getting back to oct17 state and better)

**Comment by gargnupur** [comment]
@ldemailly : our current test setup looks like should not suffer from issues mentioned in https://github.com/istio/istio/blob/vagrant-kubernetes-istio/vagrant-kubernetes-istio/RunTestOnHost/README.md
You should be able to run 1 e2e test multiple times..

**Comment by ldemailly** [comment]
it wasn't k8s fault but mostly ours

**Comment by gargnupur** [comment]
This is completed, so closing...

**Comment by hklai** [comment]
To summarize, we have provided two options to run E2E tests on dev machines. The instructions are included in the revamped E2E testing guide at https://github.com/istio/istio/tree/master/tests/e2e.

If you encounter any problem, feel free to ping this issue or contact @gargnupur and me directly.
