### ISSUE TITLE
I must be missing something very very simple ...

### ISSUE THREAD

**Issue by dwgillies-bluescape** [istio/istio#45384]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

I have properly set up istio sidecar injection and the correct prometheus scrape annotations for my cluster.  I have verified that istdio-proxy is correctly merging metrics and serving them on port 15020.  However, there is no endpoint for 15020 in my istio-proxy pod.

By default the istio sidecar injector hardcodes the 15090 endpoint port, not 15020.  When I have done everything necessary to get the data on port 15020, why does the sidecar injector open up port 15090 instead?  

This is frustrating.  I found a number of workarounds - hand edit the istio-sidecar-injector configmap to set containerPort: 15020 (L346), mark up every single deployment to export the 15020 endpoint, or create a weird specialized enhancement template from terraform and load it after terraform helm installs the istio-sidecar-injection configmap, which would be a hassle. 

I feel like there must a flag somewhere to fip the port as a simple last step - and if not - why not add such a flag?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
When you say "However, there is no endpoint for 15020 in my istio-proxy pod." do you mean it's not listening there at all? Or it's just not in the containerPort part of pod spec?

The latter should not matter for most cases - it's not expected to be present
