### ISSUE TITLE
TCPDump not working when Istio set with global proxy privileged as true

### ISSUE THREAD

**Issue by anandseshan** [istio/istio#45383]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio was upgraded from 1.14 to 1.16.5 with global.proxy.privileged to true. In the istio operator the proxy shows as privileged true where I can't generate tcp dump in the istio-ingressgateway.

istio-proxy@istio-ingressgateway-544dbb94c5-5k6kl:/$ tcpdump -s 0 -vvv -w /capture.cap
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)

Istio Operator:

     proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ''
        excludeInboundPorts: ''
        excludeOutboundPorts: ''
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: true
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        statusPort: 15020
        tracer: zipkin

Istio-ingressgateway:

           failureThreshold: 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

### Version

```Text
$ istioctl version                                                                    
client version: 1.17.3
control plane version: 1.16.5
data plane version: 1.14.0 (10 proxies), 1.16.5 (6 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.9
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by rokkiter** [comment]
You can refer to this issue
https://github.com/istio/istio/issues/30982

**Comment by MaciekLeks** [comment]
.

> 

...and to store your pcap to a file you must set `sidecar.istio.io/enableCoreDump: "true"` to make the istio-proxy container file system writtable.

**Comment by howardjohn** [comment]
What is the full install settings and methods? There are quite a few ingrss install methods

**Comment by anandseshan** [comment]
@howardjohn, I used istioctl to install the mesh. I found an alternative where after install with privileged as true and manually changed the privileged value under security context in ingress gateway deployment.yaml. It finally worked and I could do packet capture. Thanks everyone for quick support.
