### ISSUE TITLE
Copy request query param to header

### ISSUE THREAD

**Issue by thinkingmik** [istio/istio#45390]
Hi!

It is possible to modify the incoming request for copy a querystring param to an header?

For example, from a request:
```
GET /api/sample?token=xxx
```
and have an outgoing call like:
```
GET /api/sample?token=xxx
Authorization: bearer xxx
```

Thanks.

**Comment by peterj** [comment]
I don't think copying is possible with the VirtualService. 

You can match on the query string, and you can set/add/remove headers, but you can't copy the value from the query param to the header.

**Comment by wulianglongrd** [comment]
Is it used for jwt AuthZ ? If so, use `fromParams`.
https://istio.io/latest/docs/reference/config/security/jwt/

**Comment by thinkingmik** [comment]
Thanks
