### ISSUE TITLE
ambient index service handling optimize

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#45403]
handleService is very unefficient

1. it is called on every service event
2. it is selecting all correslated pods and maintain the indexer of pod, this is the  most critical part, which can be improved
3. maintain service indexer

coarse thought: at least we can check service ip, label selector, etc to simplify processing

**Comment by howardjohn** [comment]
Can we hold on the optimizations? We are in the process of refactoring everything anyways so it will be wasted effort. See https://github.com/istio/istio/pull/44201

**Comment by hzxuzhonghu** [comment]
Yes, can be done when ambient is beta
