### ISSUE TITLE
not able to write to hostpath /etc/ambient-config/config.json.tmp in Bottlerocket os in EKS 

### ISSUE THREAD

**Issue by AyushSolanki158** [istio/istio#45400]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

this issue is related to bug [#45304](https://github.com/istio/istio/issues/45304) the Bottlerocket OS that we are using in AWS EKS  is quite secure and doesn't allow access to write in /etc dir but allows access for /var and /opt according to [OS-Doc](https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md#stateless-tmpfs-for-etc) ,  but in istio-cni helm chart  the hostpath is hard-coded (line 185 in   [CNI-daemonset.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/templates/daemonset.yaml)  ) .

please could we add hostpath variable in CNI chart values to replace this hostpath value. 

### Version

```Text
$ istioctl version
1.18.0-rc.0
$ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.25.9-eks-0a21954
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
I see that #45404 was merged; can we close this issue?

**Comment by AyushSolanki158** [comment]
Sure, #45405 should solve the file access issue , still facing the GitRepository failure may be istio was not able to configure iptables on host with Bottlerocket os in EKS. Will test and try to identify the exact issue.
