### ISSUE TITLE
Can't define the format of Istio application logs

### ISSUE THREAD

**Issue by NoamGaloz** [istio/istio#45406]
Can't find a way to define the format of Istio application logs. 
log example: '2023-06-11T12:21:03.475919Z	info	installer	Watching a change for istio resource: istio-system/istio-ingressgateway'.
It seems like Istio provides a way to define the desired format of the access log only.

**Comment by kfaseela** [comment]
cc @zirain

**Comment by zirain** [comment]
@NoamGaloz  do you means log from istiod?

**Comment by NoamGaloz** [comment]
Also from istio-ingressgateway.

istio-ingressgateway logs example -
![image](https://github.com/istio/istio/assets/84265700/30050889-47d2-4355-97b6-d1ba491af87e)

istiod logs example -
![image](https://github.com/istio/istio/assets/84265700/7dd1eb31-06c2-4f01-a0e0-9b7dbf364678)

**Comment by howardjohn** [comment]
This is working as expected. You can use json or plaintext but not otherwise customize any formating. Unlikely access logs, application logs are not key-value pairs so having custom format is less meaningful there?

**Comment by howardjohn** [comment]
Ah saw on slack you want json. `.Values.global.logAsJson=true` can do this

**Comment by GregHanson** [comment]
marking resolved
