### ISSUE TITLE
Wrong route configuration when multi-level wildcards are used

### ISSUE THREAD

**Issue by leosarra** [istio/istio#45415]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone,
I encountered an issue while tinkering with SE and VS resources that uses wildcards.
I noticed that under certain configuration I can end up with an incorrect route being generated.

Here are some steps to reproduce (archive with the CRs: [resources.tar.gz](https://github.com/istio/istio/files/11723372/resources.tar.gz)):
- Install Istio (I used 1.17.2)
- Deploy Sleep with sidecar in istio-system
```
kubectl label ns istio-system istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml -n istio-system
```
- Deploy a SE with "host: *.hello.test.abc.example.com" host and one with  "host: *.abc.example.com"
You can use the resources inside my zip and deploy them with `kubectl apply -f serviceentries/ -n istio-system`
- Deploy two VS, one for each host. Those VS needs to define a route to the respective wildcard host.
You can deploy my two VS using `kubectl apply -f virtualservices/ -n istio-system`
- Check the configdump and you will notice that the *.abc.example.com virtual host ended up with a route to *.hello.test.abc.example.com instead of the route to *.abc.example.com.
```
{
     "version_info": "2023-06-12T12:47:43Z/11",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "443",
      "virtual_hosts": [
       {
        "name": "*.abc.example.com:443",
        "domains": [
         "*.abc.example.com"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|443||*.hello.test.abc.example.com",
           "timeout": "15s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,reset,unavailable,cancelled,resource-exhausted",
            "num_retries": 3,
            "per_try_timeout": "15s",
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
              }
             }
            ],
            "host_selection_retry_max_attempts": "5"
           },
           "max_grpc_timeout": "15s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/virtual-service/vs1"
            }
           }
          },
          "decorator": {
           "operation": "*.hello.test.abc.example.com:443/*"
          },
          "name": ".https-port"
         }
        ],
        "include_request_attempt_count": true
       },
```

I suspect that this issue originates from the fact that the wildcard *.abc.example.com of the SE matches the wildcard in the VSs.
Is this the intended behavior? Can something be done to support this multi-level wildcard scenario?

### Version

```Text
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (2 proxies)
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11723350/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by LithiumSR** [comment]
@howardjohn Do you know if this interaction between multi-level wildcards in SE and VS is by-design or if the scenario is not currently supported?

**Comment by kfaseela** [comment]
cc @ramaraochavali

**Comment by ramaraochavali** [comment]
Based on how [name matching](https://github.com/istio/istio/blob/8652668835700c4e278dac4437a9e736602bc559/pkg/config/host/name.go#L37) works - It is possible to get the routes generated like that as *.hello.test.abc.example.com matches with *.abc.example.com

**Comment by KasperDeng** [comment]
Is it possible to improve the matching mechanism of Name? 
Currently selecting the HTTP route (or virutalService) by checking the wcSvcHosts with the first one matching with the wildcard host. There is possible that *.hello.test.abc.example.com will match *.abc.example.com. It is unwanted route. 

Recommended to enhance the checking of wildcard host if there is multiple wildcard matching, use the Fully Equal instead of matching the 1st one. 

Welcome for further discussion and comments. 
Thanks.

BTW, in current situation, any possible workaround for it? Can add addresses associated with that ServiceEntry for differentiation instead of decorator of the existing service? Because in such case, wildcard host and port cannot be the factor for discrimination. But filling addresses is bad for usability, especially there are abundant of external hosts to be registered.

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/issues/26715 - I think this is similar issue?

**Comment by KasperDeng** [comment]
#26715 was an issue related to routing from gateway to internal services, it was inbound traffic related. It looks that there is a work around to splitting the gateway into separated resources can handle it.
But for this case, it is outbound traffic related. The service entries ware already two for each routing domain, but the wildcard will cause some overlapping.
I agree that it is some general issue of routing mechanism for wildcard host, both for inbound and outbound.

**Comment by ramaraochavali** [comment]
If I understand, gateway API matching also works similar to how Istio is implemented. @howardjohn Is that correct?

**Comment by howardjohn** [comment]
This does seem wrong if I understand. We said `match *.hello.test.abc.example.com ` and now `foo.abc.example.com` would match

**Comment by ramaraochavali** [comment]
> This does seem wrong if I understand. We said match *.hello.test.abc.example.com  and now foo.abc.example.com would match

I did not understand - Are you saying what we have is correct? IMO what we have is correct and rejects `*.hello.test.abc.example.com` and `foo.abc.example.com` wont match.

**Comment by howardjohn** [comment]
@ramaraochavali 

My understanding:

* Those two **should not** match
* From the issue, it sounds like they are matching unexpectedly? I did not verify it myself, though

**Comment by ramaraochavali** [comment]
Ok. I think they wont match based on code atleast. I also have n't verified my self.

**Comment by ramaraochavali** [comment]
But I think the problem is with both wild cards - for example "*.hello.test.abc.example.com" and *.abc.example.com" - it matches. That is what this issue is talking about.

**Comment by keithmattix** [comment]
> This does seem wrong if I understand. We said match *.hello.test.abc.example.com and now foo.abc.example.com would match

It's the inverse no? A SE for `*.abc.example.com` is matching a VS for `*.hello.test.abc.example.com`. This would be correct if we didn't have another SE that had a more specific host match.

**Comment by ramaraochavali** [comment]
yes. I think that is the problem.

**Comment by keithmattix** [comment]
This gets interesting then because that means the host matching for a particular set of config is now stateful, i.e. dependent upon otherwise irrelevant configuration in the cluster. I'm sure it can be done, but not sure how to do so without major changes to the data model

**Comment by keithmattix** [comment]
FYI I believe I have a fix for this; testing now

**Comment by kfaseela** [comment]
> FYI I believe I have a fix for this; testing now

Thanks @keithmattix

**Comment by keithmattix** [comment]
@LithiumSR when you look at your istiod control plane metrics, do you see a non-zero value for pilot_vservice_dup_domain?

**Comment by LithiumSR** [comment]
Thank you a lot @keithmattix 👍 
Tomorrow I will verify the PR and let you know if everything works from my side
