### ISSUE TITLE
Metrics: export metrics to determine the number of inflight requests 

### ISSUE THREAD

**Issue by zohar-arista** [istio/istio#45425]
**Describe the feature request**
Using the [standard metrics exported by Istio](https://istio.io/latest/docs/reference/config/metrics/), we have been able to monitor and visualize service/workload traffic, latency, and error rates for our mesh applications. Another metric we would like to monitor through Istio standard metrics that currently doesn't seem to be implemented is "inflight" requests (i.e. requests that have been started but not yet handled). Would it be possible to include counters for requests started/handled so we could determine the current number of inflight requests for our applications?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/issues/23672
