### ISSUE TITLE
Not able to install istio in different namespace using istioctl binary

### ISSUE THREAD

**Issue by parshva-shah-dsw** [istio/istio#45429]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are trying to install istio in different namespace and not in the default (istio-system).
Any idea how we can install istio in different namespace using istioctl binary.
Using below flag we are not able to change the namespace :-
--istioNamespace string   Istio system namespace (default "istio-system")

<img width="758" alt="image" src="https://github.com/istio/istio/assets/117802398/f7d3bde8-3b43-49aa-8524-de222eeb72d8">

### Version

```Text
[azureuser@EV-Usecase-Sim-1 ~]$ istioctl version
no running Istio pods in "istio-system"
1.16.2
[azureuser@EV-Usecase-Sim-1 ~]$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.10
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
can you try with `--set values.global.istioNamespace`?

**Comment by parshva-shah-dsw** [comment]
Thanks @zirain it worked
