### ISSUE TITLE
Pod couldn't create with injector

### ISSUE THREAD

**Issue by seaurching** [istio/istio#45433]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Name:           test-6c87565878
Namespace:      kube-public
Selector:       kubepi.org/name=test,pod-template-hash=6c87565878
Labels:         kubepi.org/name=test
                pod-template-hash=6c87565878
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/test
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  kubepi.org/name=test
           pod-template-hash=6c87565878
  Containers:
   ngin:
    Image:        harbor.xpaas.lenovo.com/qiqisa/nginx:v1.18.1
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason            Age                   From                   Message
  ----     ------            ----                  ----                   -------
  Normal   SuccessfulCreate  30m                   replicaset-controller  Created pod: test-6c87565878-rc5t7
  Warning  FailedCreate      26s (x18 over 8m27s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.earth-mesh-system.svc:443/inject?timeout=10s": context deadline exceeded

### Version

```Text
# istioctl version
no running Istio pods in "istio-system"
1.17.2
# kubectl version --short
Client Version: v1.23.16-dirty
Server Version: v1.23.16
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11733671/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by seaurching** [comment]
There Is the response for other namespace that not enabled inject
<img width="1422" alt="2023-06-13214938" src="https://github.com/istio/istio/assets/7349963/a7dfecf3-01cb-4b5c-b3e9-cd8c26fd26de">

**Comment by fatedier** [comment]
You should check if your istiod pods are normal.

**Comment by seaurching** [comment]
> You should check if your istiod pods are normal.

normal running

**Comment by hanxiaop** [comment]
Check the connection between Istiod and api-server. The problem could be related to network issues. Also, check if the kube-apiserver has any logs related to the injector MutatingWebhookConfiguration.
