### ISSUE TITLE
helm - termination grace period

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#45434]
Hi,

I want to increase the termination grace period of the ingress gateway in order to give my traffic enough time to drain
I created a PR to fix this issue in the gateway helm chart.
https://github.com/istio/istio/pull/45431

Is there a way to override the default termination grace period (30 seconds) without this PR?

maybe I should not change this? what will happend to a request when the ingress gateway pod is terminating (due to hpa or other reasons) and the request is still in progress?

last question, according to your upgrade guide (helm), in order to upgrade istio I first need to apply the crds yaml files and after that upgrade the istio base chart with skip crds.
my question is: the crds are already in the istio base chart so why applying them seperatly and not just upgrading istio base with the crds?
![image](https://github.com/istio/istio/assets/23296337/e09b4d75-dda0-4f36-8de9-9d50395984a2)

**Comment by jacob-delgado** [comment]
I think you can use https://istio.io/latest/docs/setup/additional-setup/customize-installation/ to accomplish this using helm. Have you tried it?

**Comment by Rez0k** [comment]
> I think you can use https://istio.io/latest/docs/setup/additional-setup/customize-installation/ to accomplish this using helm. Have you tried it?

I will check it out. Thanks!
