### ISSUE TITLE
traffic mangement not working on different deployments models of istio for multi-clusters setup

### ISSUE THREAD

**Issue by rohanlucifer** [istio/istio#45447]
Hello there,
so i am using kubectl version as
``` 
Client Version: v1.23.4
Server Version: v1.25.6+k3s1
```
```
using istio-version as 1.17.1
```
## primary-remote
I did tried the primary-remote deployments model, followed as the guide
while verifying the installation the helloworld version=v1 is working fine while the helloworld version=v2 deployments is not in ready state as i check the logs of replicasets for version=v2 it says it couldnt find the crds, as i have to install the operator

## multi-primary
I  tried the multi-primary deployments model, followed as the guide, installed istio-operator in both clusters, while verifying the installation
the helloworld version=v1 and helloworld version=v2 are working fine but as per the guide

### if i run this command
``` 
kubectl exec --context="${CTX_CLUSTER1}" -n sample -c sleep \
    "$(kubectl get pod --context="${CTX_CLUSTER1}" -n sample -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')" \
    -- curl -sS helloworld.sample:5000/hello
```

**Comment by mark8s** [comment]
@ericvn Have you solved this problem now? I have the same problem as you. I think istio should have changed its strategy. In the previous version 1.11, the default was to poll access instances in multiple clusters, but it seems that this is no longer the case.

**Comment by mark8s** [comment]
@rohanlucifer Have you solved this problem now? I have the same problem as you. I think istio should have changed its strategy. In the previous version 1.11, the default was to poll access instances in multiple clusters, but it seems that this is no longer the case.

**Comment by mark8s** [comment]
@rohanlucifer I solved it, my problem was caused by not configuring root ca.

**Comment by rohanlucifer** [comment]
@mark8s i did configure CA from the official documentation but didnt work as per the guide
https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
can you provide me documentation that you have done for multicluster setup
