### ISSUE TITLE
Support object label selector for istioctl analyze

### ISSUE THREAD

**Issue by fatedier** [istio/istio#45458]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Releated to https://github.com/istio/istio/issues/27772

If users use Helm as their application deployment tool, Helm will use secrets as the default storage [doc](https://helm.sh/docs/faq/changes_since_helm2/#secrets-as-the-default-storage-driver)

This will result in a large number of secrets in the cluster, and since it stores chart values, the content is usually very large.

`istioctl analyze` during the initialization phase, it will wait to synchronize all the secrets, but these objects are useless for analysis. If there are too many secrets, it will not only affect the analysis time but may also cause kube-apiserver to fail to synchronize completely.

I want to add a new "resource-filters" parameter so that users can filter out specific objects using a label selector. [doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api) kube-apiserver will not send these objects content to client.

Example:

`istioctl analyze -A -F "Secret owner!=helm"`

In my testing environment, in a scenario with over 2000 secrets, the execution time of `istioctl analyze -A` has been reduced from 8s to 1.2s.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by fatedier** [comment]
> The filter idea sounds good to me. We may need to polish the flag usage a little bit, since -F maybe stands for force or file. It seems like you have already implemented the code, would you like to share it?

OK. I will submit a PR later.

**Comment by howardjohn** [comment]
We should just filter automatically. We already do in the main code:

```
pilot/pkg/credentials/kube/secrets.go
83-     // Its also likely users have started to use random types and expect them to continue working.
84-     // This makes the assumption we will never care about Helm secrets or SA token secrets - two common
85-     // large secrets in clusters.
86-     // This is a best effort optimization only; the code would behave correctly if we watched all secrets.
87-     fieldSelector := fields.AndSelectors(
88:             fields.OneTermNotEqualSelector("type", "helm.sh/release.v1"),
89-             fields.OneTermNotEqualSelector("type", string(v1.SecretTypeServiceAccountToken))).String()
90-     secrets := kclient.NewFiltered[*v1.Secret](kc, kclient.Filter{
91-             FieldSelector: fieldSelector,
92-     })
93-
```
