### ISSUE TITLE
Unable to connect to external service

### ISSUE THREAD

**Issue by Ayaz-Tanzeem** [istio/istio#45454]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am trying to configure istio to connect to a service running outside my k8s mesh. I configured a service entry and a virtual service for the same. But I am unable to connect to it

### Version

```Text
istioctl version 
1.17
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Can you provide the configs you have? Otherwise it's hard to debug the issue.

**Comment by Ayaz-Tanzeem** [comment]
This is my serviceEntry

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: consul-media-service
spec:
  hosts:
  - consul-media-service
  exportTo:
  - "*"
  addresses:
  - 172.10.17.101
  ports:
  - number: 8105
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  
  
  This is my virtualService
  apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: media-service
spec:
  hosts:
  - test-host.net
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /media-service-test/
    rewrite:
      uri: /
    route:
    - destination:
        host: consul-media-service
        port:
          number: 8105

test-host.net is the host name which is being used to allow traffic to istio mesh.




This is the test-gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: istio-system
  annotations:
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - test-host.net
    
    
    Services inside the mesh are working fine and I can access them from browser, but thats not the case with the only externa service
