### ISSUE TITLE
ambient namespace default dataplane mode does not work

### ISSUE THREAD

**Issue by kdorosh** [istio/istio#45461]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

adding this code to the end of this [function](https://github.com/istio/istio/blob/eea7717d0043b3782515b2eeda57c21c5baeba55/pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go#L426):

```golang
	// ensure labeling the namespace with dataplane mode works
	controller.client.Kube().CoreV1().Namespaces().Create(context.Background(), &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{Name: "ns1", Labels: map[string]string{"istio.io/dataplane-mode": "none"}},
	}, metav1.CreateOptions{})
	assertEvent("cluster0//v1/pod/ns1/name1", "cluster0//v1/pod/ns1/name2")
	assert.Equal(t,
		controller.ambientIndex.Lookup("testnetwork/127.0.0.1")[0].GetWorkload().TunnelProtocol,
		workloadapi.TunnelProtocol_NONE)

	controller.client.Kube().CoreV1().Namespaces().Update(context.Background(), &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{Name: "ns1", Labels: map[string]string{"istio.io/dataplane-mode": "ambient"}},
	}, metav1.UpdateOptions{})
	assertEvent("cluster0//v1/pod/ns1/name1", "cluster0//v1/pod/ns1/name2")
	assert.Equal(t,
		controller.ambientIndex.Lookup("testnetwork/127.0.0.1")[0].GetWorkload().TunnelProtocol,
		workloadapi.TunnelProtocol_HBONE)
```

should pass, but it does not. we do have event handlers already hooked up for namespace events [here](https://github.com/istio/istio/blob/eea7717d0043b3782515b2eeda57c21c5baeba55/pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go#L92), looks like we just need to pass the namespace through so any changes there can be reflected by ambient resources.

### Version

```Text
istio as of 924183d1d937c6546c7b4ed56d8693b94e449a34
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
This is WAI. Its not supposed to look at the namespace. The CNI looks at the namespace and updates the annotation on the pods, rather than the controller trying to guess what the CNI _will_ do

**Comment by kdorosh** [comment]
ah ok, that makes sense. we can close this
