### ISSUE TITLE
TestGatewayHostnames test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#45488]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1669396541095284736

**Comment by rokkiter** [comment]
This seems to be an occasional problem. Is there any way to reproduce it? It cannot be reproduced in my test pr

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests-arm64_istio_postsubmit/1687558326579105792. seems rare but still occurs

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1689702988458758144

**Comment by ymesika** [comment]
I noticed a related fix in #47389.
@howardjohn I guess it resolves this?

**Comment by hanxiaop** [comment]
> I noticed a related fix in #47389. @howardjohn I guess it resolves this?

I think this has been fixed; I've only seen it recently in the release-1.20 branch.

**Comment by hanxiaop** [comment]
> > I noticed a related fix in #47389. @howardjohn I guess it resolves this?
> 
> I think this has been fixed; I've only seen it recently in the release-1.20 branch.

It looks like it's already in release-1.20... Maybe I remembered it incorrectly.
