### ISSUE TITLE
Distribute config to Envoy proxy

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#455]
Some config, such as rate limiting, have to go to Envoy proxy.  This issue needs to
1) Define what kind of config Envoy proxy will support
2) How these config will be distributed to Envoy proxy, ideally without restart Envoy.

It can start with rate limiting config.

**Comment by ldemailly** [comment]
I'm confused about what this is (everything envoy needs is provided through pilot afaik)

closing but please open a pilot/ issue if needed
