### ISSUE TITLE
Issues with achieving multicluster communication with istio

### ISSUE THREAD

**Issue by bashlion** [istio/istio#45539]
Hello Team,
I have been trying to achieve multi cluster communication by following the below link:
https://istio.io/latest/docs/setup/install/multicluster/multi-primary/

I am able to follow the entire document to the word but still not able to get through. My response is only coming from v1 or v2 but not from both:

istio-control:~ # kubectl exec --context="${CTX_CLUSTER2}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER2}" -n sample -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-79d5467d55-z79fr
istio-control:~ # kubectl exec --context="${CTX_CLUSTER2}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER2}" -n sample -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-79d5467d55-z79fr
istio-control:~ # kubectl exec --context="${CTX_CLUSTER2}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER2}" -n sample -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-79d5467d55-z79fr
istio-control:~ # kubectl exec --context="${CTX_CLUSTER2}" -n sample -c sleep     "$(kubectl get pod --context="${CTX_CLUSTER2}" -n sample -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')"     -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-79d5467d55-z79fr
istio-control:~ #

I am using RKE2 version 1.24.9 and istio version 1.18 with calico cni

I have 2 single node clusters acting as 2 individual clusters. Both clusters are on the same private network. 

I have used metallb as LB and the entire setup inon vmware.

Is there anything i need to do extra then in the documentation or there is something i am missing. Please guide.

**Comment by hanxiaop** [comment]
Have you configured trust in before you begin? https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/

**Comment by hanxiaop** [comment]
You may use `istioctl pc endpoint` to check if the endpoint has been registered

**Comment by bashlion** [comment]
> Have you configured trust in before you begin? https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/

Yes we had configured it.

**Comment by bashlion** [comment]
> You may use `istioctl pc endpoint` to check if the endpoint has been registered

Endpoint is registered but i will still check and get back :) Thanks and apologies for the delayed response quite busy these days
