### ISSUE TITLE
Gateway Helm Chart should accept proxy image value

### ISSUE THREAD

**Issue by jrdelarosa8** [istio/istio#45531]
**Describe the feature request**

In order to support working with signed images, the Gateway Helm Chart should accept a proxy image value parameter. Otherwise,  the Sigstore Policy Controller returns:

`failed to create resource: admission webhook "policy.sigstore.dev" denied the request: validation failed: invalid value: auto must be an image digest: spec.template.spec.containers[0].image]`

**Describe alternatives you've considered**

Running Istio with unsigned images is not an option I'd like to pursue.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I'd like to compose the proxy image value from:
- Registry name (docker.io)
- Image name (proxyv2)
- Image tag (1.15.4)
- Image digest (sha256:015aq3...)

**Comment by hanxiaop** [comment]
The gateway chart is for auto-injection, and the pod image will be automatically updated. It looks like the validation error is not from the Istio side, I suggest you to try other gateway installation methods.

**Comment by keithmattix** [comment]
Is the sigstore policy controller a validating webhook? It appears that sigstore's controller is running before Istio's mutating webhook injects the actual gateway image

**Comment by howardjohn** [comment]
looks like it's running on the deployment not the pod

**Comment by keithmattix** [comment]
Good catch. @jrdelarosa8 can you configure your sigstore controller to watch pods and not deployments? It's actually a more secure approach

**Comment by alxivanov** [comment]
https://github.com/sigstore/policy-controller/issues/1388
