### ISSUE TITLE
sidecar envoy cpu is too high,but it has few requests

### ISSUE THREAD

**Issue by jaywlm** [istio/istio#45548]
istio version: v1.9
k8s: 1.17.9

sidecar pprof
-----
      flat  flat%   sum%        cum   cum%
     210ms 22.58% 22.58%      210ms 22.58%  Envoy::Stats::ThreadLocalStoreImpl::counters
     150ms 16.13% 38.71%      150ms 16.13%  writev
      90ms  9.68% 48.39%       90ms  9.68%  Envoy::Stats::ThreadLocalStoreImpl::gauges
      80ms  8.60% 56.99%       80ms  8.60%  X509_get0_notAfter
      70ms  7.53% 64.52%       70ms  7.53%  readv
      60ms  6.45% 70.97%       60ms  6.45%  Envoy::Stats::ThreadLocalStoreImpl::textReadouts
      60ms  6.45% 77.42%       60ms  6.45%  epoll_wait
      20ms  2.15% 79.57%       20ms  2.15%  _IO_vfprintf
      20ms  2.15% 81.72%       20ms  2.15%  asn1_utctime_to_tm
      10ms  1.08% 82.80%       30ms  3.23%  ASN1_TIME_diff

**Comment by zirain** [comment]
can you check the count of stats on your sidecar?

```
kubectl exec -it <your_pod> [-n ns]  -c istio-proxy -- curl 127.0.0.1:15000/stats/prometheus | wc -l
```

**Comment by jaywlm** [comment]
$ curl -s localhost:15000/stats/prometheus | wc -l
997

**Comment by zirain** [comment]
your pprof shows stats cost cpu, but count seems not that much

**Comment by jaywlm** [comment]
yes, High cpu usage occurred suddenly.

**Comment by howardjohn** [comment]
Istio version 1.9 is many years EOL. Please upgrade before filing issues. See https://istio.io/latest/docs/releases/supported-releases/
