### ISSUE TITLE
 How is istio-peer-exchange ALPNgenerated?

### ISSUE THREAD

**Issue by liuqi-sun** [istio/istio#45541]
I find that the ALPN sent by the client sidecar is istio-HTTP /1.1, istio, and http/1.1, but not istio-peer-exchange.As shown in the picture below:
![image](https://github.com/istio/istio/assets/48784730/05e6036e-5db5-40e2-bb84-e1ca58cda98f)

I found that the cluster is configured with alpnProtocols. What is the use of alpnProtocols?As shown in the picture below:
![image](https://github.com/istio/istio/assets/48784730/9987bbf9-2595-4d4c-85c7-cb82b0e93391)

In what scenarios is an istio-peer-exchange ALPN sent?

I hope you can help me. Thank you

**Comment by hzxuzhonghu** [comment]
It is a customized application protocol, which is hard coded in istio code

**Comment by hzxuzhonghu** [comment]
pilot/pkg/networking/core/v1alpha3/listener.go#L95
```
	mtlsTCPWithMxcALPNs = []string{"istio-peer-exchange", "istio"}

```
