### ISSUE TITLE
istio-proxy causing error log noise when Pod is beeing terminated. "accept tcp :15020: use of closed network connection"

### ISSUE THREAD

**Issue by isaac88** [istio/istio#45547]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone,
I noticed that when the istio-proxy is being drain/terminated it is showing the error below:

`accept tcp :15020: use of closed network connection`

That error log is quite noisy since it's happening all the time when a pod is being drain/terminated.

I've tried several proxy.istio.io/config in order to try to give more time to drain properly all the connections, without any luck. Also, I've tried the latest version (1.18.0) and it is still happening.

Do you know if that error message should be considered as error since it's happening always?
What is the impact of that error?

### Version

```Text
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1
$  kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.13-eks-0a21954
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
There is no impact other than noisy logs I think. in other parts of code we suppress this

**Comment by florianmutter** [comment]
I think this message should be removed. It reads like there is a problem but there isn't. This costs time to investigate and setup rules to ignore the log message

**Comment by florianmutter** [comment]
This is not fixed yet. Could we re-open the issue?

**Comment by vikblom** [comment]
I had a look to see if I could reproduce this issue. It appears with 1.20.2 but not with master. Seems like it has been address in istio/istio#47226.

See [./pilot/cmd/pilot-agent/status/server.go#L401](https://github.com/istio/istio/blob/3639a4f44f5f8ae0057b81a9004d3209acc0f6e6/pilot/cmd/pilot-agent/status/server.go#L401).
