### ISSUE TITLE
dual stack proxy config missing a svc IP in virtualHost domains list

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#45557]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

**This is a fail closed situation: traffic which should be allowed is being denied***

In dual stack k8s svcs get assigned an IPv4 and an IPv6 address. Only 1 of those addresses is being populated into the domains list in the routes. This has some effects on things like AuthorizationPolicy where they won't be applied correctly to the missing IP which is flowing through a passthrough. Not exhaustively tested but in my first quick check it did fail shut at least denying traffic that should have been allowed.

The IP Family address which get's populated is the one which appears first in the list.

**abbreviated proxy-config route & k8s svc:**
```shell
❯ istioctl pc routes sleep-9454cc476-jrgnj.default --name 8000 -ojson
[
    {
        "name": "8000",
        "virtualHosts": [
            {
                "name": "httpbin.httpbin.svc.cluster.local:8000",
                "domains": [
                    "httpbin.httpbin.svc.cluster.local",
                    "httpbin.httpbin",
                    "httpbin.httpbin.svc",
                    "[fd00:10:96::bc57]"
                ],
REMAINDER OMITTED FOR BREVITY...

❯ k get svc -n httpbin httpbin -o yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
    service: httpbin
  name: httpbin
  namespace: httpbin
spec:
  clusterIP: fd00:10:96::bc57
  clusterIPs:
  - fd00:10:96::bc57
  - 10.96.19.25
  ipFamilies:
  - IPv6
  - IPv4
REMAINDER OMITTED FOR BREVITY...
```

### Version

```Text
❯ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (7 proxies)

❯ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.3

FWIW this behavior has also been observed on multiple Istio 1.17 versions
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
How does this impact authz? authz is applied before route?

**Comment by ilrudie** [comment]
I'll have to dive deeper to answer that. The failure is repeatable though and testing (locally) with an istiod image built from #45564 it's being applied like I would expect now.

**Comment by howardjohn** [comment]
It would be good to provide some info (maybe privately, just in case). This should not happen

**Comment by ilrudie** [comment]
Happy to. It's nearly 7:00 here though and I need to step away. Maybe after the WG meetings tomorrow we could huddle for 15 and I'll demo it.

**Comment by ilrudie** [comment]
Near as I can surmise the failure mechanism is:

1. client-side route doesn't match due to the missing IP; traffic sent as passthrough without mTLS identity
2. server-side rbac uses source identity; doesn't match the passthrough traffic which lacks identity
3. traffic matches no allow policy and is **denied**

rbac=trace logs from destination sidecar proxy
```logs
# WITHOUT FIX
❯ k logs -n httpbin deploy/httpbin -c istio-proxy --since=1m -f
2023-06-21T18:55:09.386258Z	debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:114	checking request: requestedServerName: , sourceIP: 10.244.254.195:57164, directRemoteIP: 10.244.254.195:57164, remoteIP: 10.244.254.195:57164,localAddress: 10.244.46.5:80, ssl: none, headers: ':authority', '10.96.19.25:8000'
':path', '/status/200'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/8.1.2'
'accept', '*/*'
'allowed', 'true'
'x-forwarded-proto', 'http'
'x-request-id', 'd8f0c092-4a51-4cbc-a5b3-59fd7804c7bb'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '02be9f8237cbe1904dd18fbdc6741aad'
'x-b3-spanid', '4dd18fbdc6741aad'
'x-b3-sampled', '0'
, dynamicMetadata: 	thread=42
2023-06-21T18:55:09.386296Z	debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:158	enforced denied, matched policy none	thread=42

# STARTING ISTIOD WITH CODE FIX
2023-06-21T18:56:43.367842Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
2023-06-21T18:56:52.591234Z	debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:114	checking request: requestedServerName: outbound_.8000_._.httpbin.httpbin.svc.cluster.local, sourceIP: 10.244.254.195:33256, directRemoteIP: 10.244.254.195:33256, remoteIP: 10.244.254.195:33256,localAddress: 10.244.46.5:80, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/default/sa/sleep, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', '10.96.19.25:8000'
':path', '/status/200'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/8.1.2'
'accept', '*/*'
'allowed', 'true'
'x-forwarded-proto', 'http'
'x-request-id', 'c7934267-28fc-460b-ab0c-5fc37fc03839'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '33d8d37e7455c876313dd86e2676d6c3'
'x-b3-spanid', '313dd86e2676d6c3'
'x-b3-sampled', '0'
'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/httpbin/sa/httpbin;Hash=f5fa6425b5d033a35ff5777645796c6dc4d783cfcdf7578b68f28102024294ee;Subject="";URI=spiffe://cluster.local/ns/default/sa/sleep'
, dynamicMetadata: 	thread=43
2023-06-21T18:56:52.591275Z	debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:154	enforced allowed, matched policy ns[httpbin]-policy[httpbin]-rule[0]	thread=43
```

**Comment by dhawton** [comment]
More complicated than originally thought. Multiple code paths which need different conversions.

**Comment by kdorosh** [comment]
PR is up for review
