### ISSUE TITLE
ambient: traffic passing through istio-gateway does not gain TLS communication

### ISSUE THREAD

**Issue by nak3** [istio/istio#45551]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

* Traffic from/to istio-gateway from/to app does not gain mTLS communication.
* More specifcally one of curl commands from sleep in [this docs](https://istio.io/latest/docs/ops/ambient/getting-started/#addtoambient) is not displayed as encrypted.

#### 1. Deploy Istio with the steps in [this docs](https://istio.io/latest/docs/ops/ambient/getting-started).

Note: I used __Istio APIs__ instead of __Gateway API__.

#### 2. Adding your application to ambient

In [the section "Adding your application to ambient"](https://istio.io/latest/docs/ops/ambient/getting-started/#addtoambient), it has a curl command from sleep to `$GATEWAY_HOST/productpage` as:

```
$ kubectl exec deploy/sleep -- curl -s "http://$GATEWAY_HOST/productpage" | grep -o "<title>.*</title>"
```

However, it is not encrypted in Kiali display. 

Please refer to this image:

![image](https://github.com/istio/istio/assets/2138339/406951ae-4502-4209-ac42-f3e316c662e8)

The path `sleep-latest -> istio-ingressgatewy -> productpage` is not encrypted. Actually the image "Kiali dashboard" in the docs also not encrypted.

### Additional note:

* Other two commands below have no problem.

```
$ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | grep -o "<title>.*</title>"
$ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/ | grep -o "<title>.*</title>"
```

* Adding istio-system ns into ambient stops working the traffic.

```
$ kubectl label namespace istio-system istio.io/dataplane-mode=ambient
$ kubectl exec deploy/sleep -- curl -s "http://$GATEWAY_HOST/productpage" 
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

### Version

```Text
$ istioctl version
client version: 1.19-alpha.8601b0908c15acf9b9c7decdaf80f8a447f835f3
control plane version: 1.19-alpha.8601b0908c15acf9b9c7decdaf80f8a447f835f3
data plane version: 1.19-alpha.8601b0908c15acf9b9c7decdaf80f8a447f835f3 (4 proxies)
```

Only monitoring tools are 1.18 installed via the following commands.

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/prometheus.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/kiali.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/jaeger.yaml
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
I vaguely recall this was a Kiali bug but cannot find the reference

**Comment by nak3** [comment]
Thank you! I'm asking Kiali team if anyone can comment here - https://istio.slack.com/archives/CJVRXB09F/p1687311811339699
