### ISSUE TITLE
Not able to lauch istio-operator and ingressgateway with private image repo

### ISSUE THREAD

**Issue by ankitmahajan507** [istio/istio#45571]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have launched an istio cluster via helm charts and flux. Images were being pulled from docker. Now want to change the hub from docker.io to Azure ACR so that image from private repo is being pulled.

In the istio control plane yaml, i have changed the hub to private one and given the image pull secret in values.global.imagepullsecret.

By giving this config, i am able to pull the images for istiod pods. But this config is not working for istio-operator pod and ingressgateway pods.

I tried to provide support in chart of gateway & operator for incorporating image pull secret but that is not working

Is the support available for pulling the image for these 2 depoyments?

Request you to please provide a way around on this.

### Version

```Text
$kubectl version --short
Client Version: v1.23.0
$helm version --short
v3.8.0+gd141386
Istio chart version
1.15.3
1.11.1
```

### Additional Information

Already added in description

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Have you tried `.Values.imagePullSecrets` for those two?

**Comment by ankitmahajan507** [comment]
Yes. It is not working. Also i am not able to see any support of imagepullsecret for operator and gateway deployment in template/deployment file.

**Comment by hanxiaop** [comment]
Can you check if the service account is correctly configured with imagePullSecrets?

**Comment by hanxiaop** [comment]
They are set in the service account rather than the deployment
