### ISSUE TITLE
Schema validation error: "http3-post-connect-failure" is not a valid retryOn policy

### ISSUE THREAD

**Issue by shardulsrivastava** [istio/istio#45605]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istioctl analyze complains that `http3-post-connect-failure` is not a valid retryOn policy. I am using Istio 1.17.2 and that uses Envoy 1.24.5 version  and as per the docs, it supports a valid retry policy `http3-post-connect-failure`

https://www.envoyproxy.io/docs/envoy/v1.24.5/configuration/http/http_filters/router_filter#x-envoy-retry-on.

However istioctl complains that it's not a valid policy, I can see that it's not in the list of the supported policies:

https://github.com/istio/istio/blob/1.18.0/pkg/config/validation/validation.go#L96-L116.

### Version

```Text
istioctl version 
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (4124 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by shardulsrivastava** [comment]
I can contribute to the fix if that's okay.

**Comment by howardjohn** [comment]
yes sounds great. I think it's  a new addition to envoy

**Comment by howardjohn** [comment]
actually... we don't support http3 requests so not sure this makes sense?

**Comment by hzxuzhonghu** [comment]
We can do this until http3 is supported for east-west traffic
