### ISSUE TITLE
Turn down or down-scope policy bot

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#45604]
Currently, https://github.com/istio/bots/ is mostly unmaintained. Since its inception, many of the same features have become integrated into other things we use (prow, github, cncf, devstats, etc).

We should consider if it is still holding its weight, and whether some functionality can be removed -- or even the whole deployment.

**Current features:**

* Auto labelling issue based on regex - I think github has native support
* Boilerplate removal (edit issues to remove junk) - Could just not do it, or use a GH action perhaps
* Nags - not useful, should remove
* Label syncer - https://github.com/kubernetes/test-infra/blob/master/label_sync/main.go can do it
* Lifecycle bot - standard github stalebot probably could do it, or we could use Kubernetes' perhaps
* Milestones - can probably just be done by humans?
* Welcome - prow can do this (or remove it): https://pkg.go.dev/github.com/abayer/test-infra/prow/plugins/welcome
* Storing things in spanner (more info below)

**Commands**

Server - handles github webhook to do the various things above

**Spanner**

In spanner we recreate GH events into a spanner schema. This is pretty heavyweight. While it has possible use, I don't think we actually _are_ using it.

As part of the CNCF we are now on https://istio.teststats.cncf.io/. This is also what is used for steering elections, etc. We also keep our own mapping of user -> company, which CNCF handles as well (and probably better, our file is 2 years out of date).

TBH I have used this [before](https://blog.howardjohn.info/posts/pr-approvers/), but I am not sure its worth the effort to maintain.

If we need new views of data, the devstats folks are open to adding new pages.

**Comment by hanxiaop** [comment]
not stale

**Comment by ShadowJonathan** [comment]
How ironic.
