### ISSUE TITLE
Can Istio Ingress Gateway run on host network?

### ISSUE THREAD

**Issue by gitanuj** [istio/istio#45610]
Istio Ingress Gateway pods also rely on injection to populate config for envoy pods. However there's explicit deny rules for automatic and manual injection if hostNetwork=True.

I understand that Istio relies on iptable changes to intercept traffic when running as a sidecar. But does it rely on any iptable changes for running as ingress gateway?

I have a scenario where I want to run AWS NLB in IP mode and send traffic directly to Istio Ingress Gateway pods (to avoid unnecessary node hops). I'm trying to do this without AWS CNI and exploring if I can just run the gateway pods on host network so that they are addressable directly by the NLB.

**Comment by howardjohn** [comment]
Should work fine
