### ISSUE TITLE
istioctl proxy-config routes will not dump rds

### ISSUE THREAD

**Issue by vaxilicaihouxian** [istio/istio#45649]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`istioctl proxy-config all $pod -o json` will not dump rds config.
<img width="784" alt="image" src="https://github.com/istio/istio/assets/8603593/e5fb15ba-8428-4b1b-a71e-0f24157091ae">
there is no `dynamic_route_configs`

### Version

```Text
istiod 1.13.2
istioctl 1.13.9
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
1.13 is EOL. Can you try if new istioctl version have this problem?

**Comment by zirain** [comment]
BTW, you should check the different between istioctl and `curl 127.0.0.1:15000/configdump`

**Comment by GregHanson** [comment]
@vaxilicaihouxian I think John is on the right track - is this for a ingress/egress gateway pod? They will have empty RDS unless you have a VirtualService created for that gateway

**Comment by vaxilicaihouxian** [comment]
I found there is dynamic_route_configs now. I didn't change anything.Just close it.
