### ISSUE TITLE
Istio-proxy should retry retriable/recoverable requests to ext-auth-server

### ISSUE THREAD

**Issue by alsterg** [istio/istio#45657]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have a Istio/Oauth2proxy/Keycloak setup, whereby a prober probes a protected service every 1m. We observed a race condition due to this timeout (https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/http/server.go#L189C42-L189C59) which kicks in because the prober doesn't close the connections. What seems to be happening is that due to synchronicity, the time expires while the http request is in flight, thus a FIN is sent, but the http request is already gone, thus oauth2-proxy has to respond with a RST.

This is an example of a retriable/recoverable request (the connection has been lost). However istio-proxy doesn't do retries on requests to ext-authn-server.

![image](https://github.com/istio/istio/assets/6640287/ee41171b-1a54-44a6-91db-5234630d7fc1)

### Version

```Text
$ istioctl version
client version: 1.16.0
control plane version: 1.15.7
data plane version: 1.15.7 (263 proxies)
```

### Additional Information

- oauth2-proxy:v7.4.0

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ramaraochavali** [comment]
How are you configuring ext authz filter for oauth2? If you are configuring via Envoy filter, please add retry policy to [grpc service](https://www.envoyproxy.io/docs/envoy/v1.26.2/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice-envoygrpc)

**Comment by alsterg** [comment]
I'm using [MeshConfig.ExtensionProvider.EnvoyExternalAuthorizationHttpProvider](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider) and it doesn't seem to support a retry policy. The link you provided seem to imply direct control of Envoy's config, but I'm using the higher-level integration of Istio (https://istio.io/latest/blog/2021/better-external-authz/).
