### ISSUE TITLE
Analyze has parse error for empty resource

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#45653]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

There's a situation that manifests are like:
```
apiVersion:
...
---
# only some comments
---
...
```

Analyze will report errors like:
```
error processing out/temp.yaml[4]: unable to parse resource with no group, version and kind
```

There may be situations where configs are temporarily disabled with #, and the analyzer should not report a parsing error for the empty resource.

### Version

```Text
master
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
not stale

**Comment by nicole-lihui** [comment]
I'd like to fix that

**Comment by nicole-lihui** [comment]
fixed in https://github.com/istio/istio/pull/49018
