### ISSUE TITLE
Updates needed to update envoy/go-control-plane

### ISSUE THREAD

**Issue by ericvn** [istio/istio#45662]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The automated job to update the envoy/go-control-plane has been failing for the last month:
```
tests/integration/pilot/forwardproxy/cert_gen.go:1: : # istio.io/istio/tests/integration/pilot/forwardproxy
tests/integration/pilot/forwardproxy/envoy_config_generator.go:74:9: unknown field DnsCacheConfig in struct literal of type "github.com/envoyproxy/go-control-plane/envoy/extensions/clusters/dynamic_forward_proxy/v3".ClusterConfig
tests/integration/pilot/forwardproxy/envoy_config_generator.go:156:7: unknown field DnsCacheConfig in struct literal of type "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/dynamic_forward_proxy/v3".FilterConfig (typecheck)
```
Their https://github.com/envoyproxy/go-control-plane/commit/1d66c35686b880d7fa07c79750994e2c112199f1 commit updated `envoy/extensions/clusters/dynamic_forward_proxy/v3/cluster.pb.go` and we will need some changes to match those.

### Version

```Text
main branch
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
> The automated job to update the envoy/go-control-plane has been failing for the last month:



Is it not reporting to slack?

**Comment by kyessenov** [comment]
https://github.com/envoyproxy/go-control-plane/pull/723 is probably important for istio.
