### ISSUE TITLE
Ambient integration with Kiali

### ISSUE THREAD

**Issue by linsun** [istio/istio#45676]
Opening an issue to track necessary ambient integration with Kiali, a few things I noticed when viewing ambient workloads from Kiali UI:

- missing sidecars are flagged as warning. While this is useful for sidecars, may not be useful for ambient without sidecars.
- would we show L4 data plane components - ztunnels?
- would we show L7 data plane components - waypoints?

Also from @costinm: making sure Kiali is well integrated with OpenTelemetry and is on board with Istio ( and proxyless gRPC and other native-support telemetry ) generating metrics with OTLP and the common semantic conventions.

**Comment by jshaughn** [comment]
Hi @linsun ,  thanks for opening this on the Istio side.  On the kiali side we also have https://github.com/kiali/kiali/issues/5476 for reference.  It's a high-level epic where we track some tasks and have discussion about Ambient support.

We have spent a bit of time on Ambient but are also waiting for the dust to settle some, and for users to start providing feedback on Kiali behavior with Ambient.  Here is a blog about some of initial initial support https://medium.com/kialiproject/kiali-support-for-istio-ambient-mesh-alpha-7f91ea8c6f54.

> missing sidecars are flagged as warning. While this is useful for sidecars, may not be useful for ambient without sidecars.

We agree that it's not useful to flag missing sidecars for ambient-enabled namespaces.  In the blog you can see how we are migrating to "out of mesh" warnings.  We have more to do here.

> would we show L4 data plane components - ztunnels?
> would we show L7 data plane components - waypoints?

We have added some labeling for ztunnel components, and also have added waypoints to our list view.    As for metrics in general, we're following the discussion here https://github.com/istio/istio/issues/42320 and also evaluating things as the metrics emerge.  The L4 TCP metrics are showing up in the graph as the ztunnel is generating those familiar metrics.  Although, the L4 metric reporting is now more complete, you don't have TCP or HTTP, you get TCP and HTTP, so currently you will see multiple edges for the different protocols, for a single HTTP request.

We welcome ideas and reports in the Kiali github Discussions and Issues!

**Comment by jshaughn** [comment]
We can probably let the bot close this one, please direct Ambient+Kiali issues to Kiali directly, unless it's directly related to support for Kiali on the Istio side.
