### ISSUE TITLE
Validated istio on ppc64le cluster.

### ISSUE THREAD

**Issue by Swapnali911** [istio/istio#45672]
Hi All,

Can someone suggest how I can create images for https://github.com/istio/istio and use the same to validate istio on a ppc64le cluster

I tried to build images using docker.push with BUILD_WITH_CONTAINER=0, but the images created are not ppc64le but amd64.

cc : @istio-testing @istio-policy-bot

**Comment by hzxuzhonghu** [comment]
ppc64 is not supported as proxy is not built for this arch now.

**Comment by Swapnali911** [comment]
@hzxuzhonghu Could you please let me know how to build containerized proxy for ppc64le. Thanks.

**Comment by zirain** [comment]
> @hzxuzhonghu Could you please let me know how to build containerized proxy for ppc64le. Thanks.

first you'd make sure https://github.com/envoyproxy/envoy is ready for ppc64le.
