### ISSUE TITLE
Standardize naming between release artifacts

### ISSUE THREAD

**Issue by slimm609** [istio/istio#45677]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Currently there is a delta between the naming of the artifacts. 

all names are from the 1.18.0 release page. https://github.com/istio/istio/releases/download/1.18.0/

- istio-1.18.0-linux-amd64.tar.gz
- istio-1.18.0-linux-arm64.tar.gz
- istio-1.18.0-osx-arm64.tar.gz
- istio-1.18.0-osx.tar.gz

The osx tar for amd64 for does include an architecture but all others do.  This is the case for both `istio` and `istioctl`.

To align the naming so that `istio-1.18.0-osx.tar.gz` becomes `istio-1.18.0-osx-amd64.tar.gz`

### Version

```Text
All versions up to 1.18.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ericvn** [comment]
Duplicate of https://github.com/istio/istio/issues/42338

**Comment by ericvn** [comment]
https://github.com/istio/release-builder/pull/1560
