### ISSUE TITLE
istio-injection causes PodInitializing over 1 minute

### ISSUE THREAD

**Issue by ricosega** [istio/istio#45699]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

when istio-injection is enabled the containers in the pods takes a lo to of time to start, between 30 seconds and 60, the behavior is the following:
- Apply helm install or upgrade.
- Creates a deployment.
- Pod starts but it stucks in PodInitializing.
  - istio-init does it job fast.
   - istio-proxy and the rest of the containers stuck in PodInitializing.
   - At some point Istio-proxy starts.
   - Suddenly all the rest start at the same time.

if I set the istio-injection is disabled the containers initialize instantly.

### Version

```Text
istioctl version
client version: 1.17.2
control plane version: 1.17.3
data plane version: 1.17.3 (35 proxies)

kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.2-eks-c12679a
```

### Additional Information

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-06-28 11:00:20.647462891 +0200 CEST

Cluster endpoint: https://whatever.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.17.2", GitRevision:"3e857775086a061d12ee445f32a0b35ea17c8488", GolangVersion:"go1.20.2", BuildStatus:"Clean", GitTag:"1.17.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.17.3", GitRevision:"61a081630d1bcc705e22b674e7f2fab7be3f16df", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.3"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.17.3", GitRevision:"61a081630d1bcc705e22b674e7f2fab7be3f16df", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.3"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.3}

Fetching proxy logs for the following containers:

backend/k8s-connector/k8s-connector-597d5ccb54-kzwl8/istio-proxy
backend/k8s-connector/k8s-connector-597d5ccb54-kzwl8/k8s-connector
backend/mnovaweb-backend/mnovaweb-backend-7c85c8bd9f-wf6l5/istio-proxy
backend/mnovaweb-backend/mnovaweb-backend-7c85c8bd9f-wf6l5/mnovaweb-backend
crossplane/crossplane-rbac-manager/crossplane-rbac-manager-75d7794899-r8tkr/crossplane
crossplane/crossplane-rbac-manager/crossplane-rbac-manager-75d7794899-r8tkr/istio-proxy
crossplane/crossplane/crossplane-645c84895-xczhn/crossplane
crossplane/crossplane/crossplane-645c84895-xczhn/istio-proxy
crossplane/provider-aws-iam-09f2fb02dd6e/provider-aws-iam-09f2fb02dd6e-544f986f6c-rw6c2/istio-proxy
crossplane/provider-aws-iam-09f2fb02dd6e/provider-aws-iam-09f2fb02dd6e-544f986f6c-rw6c2/provider-aws-iam
crossplane/provider-aws-s3-a417213f8dcd/provider-aws-s3-a417213f8dcd-587b4c5b5b-9lwf9/istio-proxy
crossplane/provider-aws-s3-a417213f8dcd/provider-aws-s3-a417213f8dcd-587b4c5b5b-9lwf9/provider-aws-s3
crossplane/upbound-provider-family-aws-cc8e3a928026/upbound-provider-family-aws-cc8e3a928026-66b6f7746d-6kkld/istio-proxy
crossplane/upbound-provider-family-aws-cc8e3a928026/upbound-provider-family-aws-cc8e3a928026-66b6f7746d-6kkld/provider-family-aws
eks-system/aws-load-balancer-controller/aws-load-balancer-controller-6cdd9fdb85-lx88k/aws-load-balancer-controller
eks-system/aws-load-balancer-controller/aws-load-balancer-controller-6cdd9fdb85-lx88k/istio-proxy
eks-system/aws-load-balancer-controller/aws-load-balancer-controller-6cdd9fdb85-wt4gx/aws-load-balancer-controller
eks-system/aws-load-balancer-controller/aws-load-balancer-controller-6cdd9fdb85-wt4gx/istio-proxy
eks-system/cert-manager-cainjector/cert-manager-cainjector-744bb89575-vrbsw/cert-manager-cainjector
eks-system/cert-manager-cainjector/cert-manager-cainjector-744bb89575-vrbsw/istio-proxy
eks-system/cert-manager-webhook/cert-manager-webhook-759d6dcbf7-frnr8/cert-manager-webhook
eks-system/cert-manager-webhook/cert-manager-webhook-759d6dcbf7-frnr8/istio-proxy
eks-system/cert-manager/cert-manager-69cdc85fc8-cvsxd/cert-manager-controller
eks-system/cert-manager/cert-manager-69cdc85fc8-cvsxd/istio-proxy
eks-system/cluster-autoscaler/cluster-autoscaler-76c945c949-v9798/aws-cluster-autoscaler
eks-system/cluster-autoscaler/cluster-autoscaler-76c945c949-v9798/istio-proxy
eks-system/external-secrets-cert-controller/external-secrets-cert-controller-c744b7bf4-nvx5x/cert-controller
eks-system/external-secrets-cert-controller/external-secrets-cert-controller-c744b7bf4-nvx5x/istio-proxy
eks-system/external-secrets-webhook/external-secrets-webhook-7bfbd4d5b5-b2l6w/istio-proxy
eks-system/external-secrets-webhook/external-secrets-webhook-7bfbd4d5b5-b2l6w/webhook
eks-system/external-secrets/external-secrets-597bf767d-rnwdm/external-secrets
eks-system/external-secrets/external-secrets-597bf767d-rnwdm/istio-proxy
eks-system/kubernetes-dashboard/kubernetes-dashboard-6c66697bf7-jk6dn/kubernetes-dashboard
eks-system/metrics-server/metrics-server-58dc6b545d-pj9nk/istio-proxy
eks-system/metrics-server/metrics-server-58dc6b545d-pj9nk/metrics-server
flux-system/helm-controller/helm-controller-8f776c546-c9s59/manager
flux-system/kustomize-controller/kustomize-controller-7b44d694bf-fhg4m/manager
flux-system/notification-controller/notification-controller-54f4c79-r4tsj/manager
flux-system/source-controller/source-controller-754685488b-7kgqp/manager
frontend/mnovaweb-ui/mnovaweb-ui-6f9bfd4c65-dlspv/istio-proxy
frontend/mnovaweb-ui/mnovaweb-ui-6f9bfd4c65-dlspv/mnovaweb-ui
istio-system//istio-ingressgateway-9x9hm/istio-proxy
istio-system//istio-ingressgateway-h8dr2/istio-proxy
istio-system//istio-ingressgateway-jv2bg/istio-proxy
istio-system/istiod/istiod-6669f6968b-97hxw/discovery
istio-system/istiod/istiod-6669f6968b-nvch4/discovery
keycloak//keycloak-0/istio-proxy
keycloak//keycloak-0/keycloak
logshippers//filebeat-8kgsg/filebeat
logshippers//filebeat-8kgsg/istio-proxy
logshippers//filebeat-gt262/filebeat
logshippers//filebeat-gt262/istio-proxy
logshippers//filebeat-qmj8s/filebeat
logshippers//filebeat-qmj8s/istio-proxy
custom-operator/custom-operator/custom-operator-744566d456-ljrdc/istio-proxy
custom-operator/custom-operator/custom-operator-744566d456-ljrdc/kube-rbac-proxy
custom-operator/custom-operator/custom-operator-744566d456-ljrdc/manager
monitoring//ecmanaged-agent-lqcw5/ecmanaged-agent
monitoring//ecmanaged-agent-lqcw5/istio-proxy
monitoring//ecmanaged-agent-mkzmr/ecmanaged-agent
monitoring//ecmanaged-agent-mkzmr/istio-proxy
monitoring//ecmanaged-agent-vbbkk/ecmanaged-agent
monitoring//ecmanaged-agent-vbbkk/istio-proxy
monitoring/ecmanaged-agent-metrics-server/ecmanaged-agent-metrics-server-fb8ddf479-grm4f/ecmanaged-agent
monitoring/ecmanaged-agent-metrics-server/ecmanaged-agent-metrics-server-fb8ddf479-grm4f/ecmanaged-agent-k8s-parser
monitoring/ecmanaged-agent-metrics-server/ecmanaged-agent-metrics-server-fb8ddf479-grm4f/istio-proxy
oauth2-proxy//oauth2-proxy-redis-master-0/istio-proxy
oauth2-proxy//oauth2-proxy-redis-master-0/redis
oauth2-proxy//oauth2-proxy-redis-replicas-0/istio-proxy
oauth2-proxy//oauth2-proxy-redis-replicas-0/redis
oauth2-proxy//oauth2-proxy-redis-replicas-1/istio-proxy
oauth2-proxy//oauth2-proxy-redis-replicas-1/redis
oauth2-proxy//oauth2-proxy-redis-replicas-2/istio-proxy
oauth2-proxy//oauth2-proxy-redis-replicas-2/redis
oauth2-proxy/oauth2-proxy/oauth2-proxy-c7fb6b59d-ksjbg/istio-proxy
oauth2-proxy/oauth2-proxy/oauth2-proxy-c7fb6b59d-ksjbg/oauth2-proxy

Fetching Istio control plane information from cluster.

The following fetches are still running: 
  ProxyGet custom-operator/custom-operator-744566d456-ljrdc:memory
  ProxyGet monitoring/ecmanaged-agent-lqcw5:memory

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0117] (Deployment eks-system/cert-manager-cainjector) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment eks-system/cert-manager) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment crossplane/crossplane-rbac-manager) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment monitoring/ecmanaged-agent-metrics-server) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment eks-system/external-secrets-cert-controller) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment eks-system/external-secrets) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0117] (Deployment custom-operator/custom-operator) No service associated with this deployment. Service mesh deployments must be associated with a service.
Warning [IST0127] (AuthorizationPolicy gr9873da48-d1cd-4a7d-81ea-5fa24cdd9958/gr9873da48-d1cd-4a7d-81ea-5fa24cdd9958) No matching workloads for this resource with the following labels: 
Warning [IST0127] (AuthorizationPolicy grb1ab679b-8175-44ac-8e38-bdf77c312735/grb1ab679b-8175-44ac-8e38-bdf77c312735) No matching workloads for this resource with the following labels: 
Warning [IST0129] (DestinationRule eks-system/kubernetes-dashboard) DestinationRule eks-system/kubernetes-dashboard in namespace eks-system has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: kubernetes-dashboard.eks-system.svc.cluster.local at port number:443
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace flux-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace flux-system istio-injection=enabled' to enable it, or 'kubectl label namespace flux-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service eks-system/aws-load-balancer-webhook-service) Port name webhook-server (port: 443, targetPort: webhook-server) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service crossplane/crossplane-webhooks) Port name  (port: 9443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service monitoring/ecmanaged-agent) Port name  (port: 18186, targetPort: 18186) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service eks-system/external-secrets-webhook) Port name webhook (port: 443, targetPort: 10250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/nlb) Port name  (port: 3389, targetPort: 3389) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service crossplane/provider-aws-iam-09f2fb02dd6e) Port name  (port: 9443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service crossplane/provider-aws-s3-a417213f8dcd) Port name  (port: 9443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service crossplane/upbound-provider-family-aws-cc8e3a928026) Port name  (port: 9443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0135] (Pod eks-system/kubernetes-dashboard-6c66697bf7-jk6dn) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Creating an archive at /home/ricosega/istio-1.17.2/bin/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ramaraochavali** [comment]
istio proxy initializatoin may take time depending on the size of k8s cluster.

**Comment by ricosega** [comment]
@ramaraochavali  its a 3 node cluster and not loaded at all:
```
NAME                                            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node1                                                        76m          1%     2611Mi                    38%       
node2                                                       121m         3%     1647Mi                    24%       
node3                                                       331m         8%     4260Mi                    63%  
```

**Comment by keithmattix** [comment]
The proxy initialization scales on the number of services and workloads in the cluster; not necessarily node utilization

**Comment by markspitz15** [comment]
I have a similar issue, how can I improve this times? PodInitzializing state could take even more than a minute in my case. Without injection on the namespace the pod get Running state in less than 5 sec.
Even if I scale deployment fro 0 to 1, Pod takes about a minute to be on Running status :/

**Comment by ricosega** [comment]
@keithmattix I don't think the cluster is overloaded neither by resources nor workloads/services.
```
[$] k get svc -A --no-headers | wc -l
29

[$] k get po -A --no-headers | wc -l
56
```

**Comment by howardjohn** [comment]
> Creating an archive at /home/ricosega/istio-1.17.2/bin/bug-report.tar.gz.

This file is the important part, you just posted the log of the thing generating the bug-report. It will be hard to help without more info

**Comment by ricosega** [comment]
Hi @howardjohn, that tar.gz contains sensible information. What should I share exactly? Or what I have to check related to slowness in initialization of the proxies?

**Comment by howardjohn** [comment]
The logs of the proxy container of the pod would be a good start. And events on the pod

**Comment by ricosega** [comment]
I have been checking and the problem is not consistent, sometimes istio-injection is not enabled and the pods also hangs in PodInitializing, must be related to something else so I close the ticket.

**Comment by ReggieCarey** [comment]
I see this behavior on just 1 namespace in my cluster.  If i disable istio injection, it proceeds to start.  Otherwise none of the pods run and remain pending forever.  

Of course when I try to get logs, I get

Failed to load logs: container "istio-init" in pod "ray-kuberay-worker-staticgroup-nfbn7" is waiting to start: PodInitializing
Reason: BadRequest (400)
