### ISSUE TITLE
HOST_IP variable interpolation broken in ingress gateways when using BOOTSTRAP_XDS_AGENT=true

### ISSUE THREAD

**Issue by jlawrienyt** [istio/istio#45720]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have configured our Istio gateways with the Datadog tracer; however we noticed that while the trace context was getting updated (indicating Envoy was producing a new child span), the spans were never getting delivered to the Datadog agent on the node.  When looking at the Envoy configuration of a live instance, we see that the address of the `datadog_agent` cluster was set to the string `$(HOST_IP)`.  The Envoy sidecar containers managed using the same Istio configuration do not exhibit the same issue, i.e. they have the IP address of the host node set as the address for the `datadog_agent` cluster.

Whittling down our IstioOperator config, I was able to determine that the bug presents itself only when `BOOTSTRAP_XDS_AGENT=true`.  When the pilot agent generates the envoy config locally, it works fine.  

I'm attaching a shell script which demonstrates the behavior in a local kind cluster.   We also observe the bug in all of our EKS clusters (where we run k8s 1.23.17 and istio 1.16.1).
[bug-demo.sh.zip](https://github.com/istio/istio/files/11900048/bug-demo.sh.zip) (sample usage: `./bug-demo.sh create bad`)

### Version

```Text
❯ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)
❯ kubectl version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.24.15
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11900096/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Just curious, is this still needed if you make the datadog service internalTrafficPolicy to local? Maybe we can make that the recommended option for the future

**Comment by jlawrienyt** [comment]
I did try configuring the Datadog service DNS name as the tracer's address, and even though internalTrafficPolicy is set to local on the service, it doesn't seem like Envoy is honoring that.  I was seeing spans being sent to non-local nodes when generating traffic through the gateway.

**Comment by howardjohn** [comment]
I don't think envoy can not honor it, it would be up to kube-proxy. I could be wrong though. Depends how the config is envoy setup exactly

**Comment by zirain** [comment]
I think with Telemetry API istio support internalTrafficPolicy `Local`.

**Comment by jlawrienyt** [comment]
Maybe it's a versioning issue?  We're running EKS 1.23 and I don't see a mention of the feature in Amazon's release announcements until [1.26](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/) (and admittedly I'm not familiar with how the the rollout of these types of features in k8s usually works).
