### ISSUE TITLE
Ambient does not work with Azure Networking Policy

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#45760]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

1. I first create an AKS cluster with `az aks create -g <resource-group-name> -n <cluster-name> --network-plug azure --network-policy azure  -c 3` and connect to it `az aks get-credentials -g <resource-group-name> -n <cluster-name>`
2. Deploy the sample `samples/tcp-echo/tcp-echo.yaml` and `samples/sleep/sleep.yaml` apps.
Note: I added the `spec.template.spec.nodeName` field of the deployments to make sure the deployments went to different nodes.
3. Install istio with ambient `istioctl install --set profile=ambient` and apply label the default namespace `kubectl label namespace default istio.io/dataplane-mode=ambient`
4. We apply the following rule
```yaml
# allow-nothing.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: default
spec:
  action: DENY
  rules:
  - {}
```
with `kubectl apply -f allow-nothing.yaml`.
5. We can still successfully connect from `sleep` to `tcp-echo`:
```bash
$ k exec -it deploy/sleep -- nc tcp-echo 9000
hi
hello hi
```
even though we tried to block all tcp traffic in the default namespace.
However, if we create the cluster without the `--network-policy azure` argument, traffic is blocked.

My hunch is that this has to do with the order in which IPTables rules are applied since Azure network policy and Ambient both work with iptables.
In the cluster with the Azure network policy, you can reinstall Ambient and reapply the authorization policy/redeploy echo and sleep, to toggle whether the `allow-nothing` authorization policy blocks traffic.

Also, note that I'm talking about the Azure network policy **not the Azure CNI**.

### Version

```Text
$ istioctl version
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (4 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
Server Version: v1.25.6
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
Hmm if the only issue is with AuthorizationPolicy rules, I wouldn't expect iptables to be the issue since those are only used for traffic capture to the ztunnel. Are there logs that point you to iptables being the cause?

**Comment by Stevenjin8** [comment]
> Hmm if the only issue is with AuthorizationPolicy rules, I wouldn't expect iptables to be the issue since those are only used for traffic capture to the ztunnel. Are there logs that point you to iptables being the cause?

The problem seems to be that traffic is not getting routed through the ztunnels at all. On the cluster where authorization policies are enforced I'll get this log if I have an authorization policy

```
2023-06-30T22:47:55.069358Z  INFO inbound{id=ddf5eb325a78791d68b5e5963fb77f44 peer_ip=10.224.0.41 peer_id=spiffe://cluster.local/ns/default/sa/sleep}: ztunnel::proxy::inbound: RBAC rejected conn=10.224.0.41(spiffe://cluster.local/ns/default/sa/sleep)->10.224.0.73:9000
```

or this log if I don't have any policies

```
2023-06-30T22:48:31.096947Z  INFO inbound{id=71ed1caaf436e6a060c540253ad52a80 peer_ip=10.224.0.41 peer_id=spiffe://cluster.local/ns/default/sa/sleep}: ztunnel::proxy::inbound: got CONNECT request to 10.224.0.73:9000
```

However, I don't see anything like that in the cluster where policies aren't enforced.
