### ISSUE TITLE
ambient workload uid may be reused with StatefulSets

### ISSUE THREAD

**Issue by yuval-k** [istio/istio#45789]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

While reviewing ambient code, I noticed that currently ambient generates UUID for its workloads like so:

https://github.com/istio/istio/blob/85a5b19061fdd24f9284b188a053237044d17d03/pilot/pkg/serviceregistry/kube/controller/ambientindex.go#L86

This means that pods with with the same name have the same UID.

A scenario that breaks this assumption is StatefulSets, where created pods have stable names.
For example, if some one edits a service account on a StatefulSet, the generated UID will be the same, even though the security properties of the pod has changed. 

I'm wondering if this can cause any issues (might this prevent the new pod spec from being propagated to ztunnel?)

cc @kdorosh 

### Version

```Text
current master (85a5b19061fdd24f9284b188a053237044d17d03)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
I don't _think_ it causes issues. The old key was IP which had far more re-use.

**Comment by kdorosh** [comment]
I think it can, and the old format can. but only in very contrived situations. but i think we should still solve for this and fix it, especially given how quick and easy the fix is

**Comment by howardjohn** [comment]
What is the fix? The UID is not intended or needed to be unique across time?

**Comment by kdorosh** [comment]
we could just use the k8s resource UID + section-name. and possibly choose to append it to something more human-readable that's prefixed

**Comment by kdorosh** [comment]
I looked over all the cases ztunnel uses UID in the codebase (there are not many) and none of them look like potential sources of race conditions across request path and istiod communication. So I actually think this is fine (for now, since we don't need it)
