### ISSUE TITLE
ambient: app pod's readinessProbe cannot work when ambient is installed via manifests

### ISSUE THREAD

**Issue by nak3** [istio/istio#45781]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

* When ambient is installed via `istioctl manifest generate`, app pod's readinessProbe cannot work.
* `istioctl install` works so it is a problem of `istioctl manifest generate`.
* I know that `istioctl manifest generate` is not recommended but we need to use it - e.g. https://github.com/knative/serving/pull/14103

### 1. Deploy Istio w/ ambient via `istioctl manifest generate`.

```
$ kubectl create ns istio-system
$ kubectl label namespace default istio.io/dataplane-mode=ambient

$ istioctl manifest generate --set profile=ambient  | kubectl apply -f -

$ sleep 3
$ kubectl -n istio-system wait --timeout=300s --for=condition=Available deploy --all
```

### 2. Deploy httpbin with readinessProbe

* httpbin is from `samples/httpbin/httpbin.yaml` with `readinessProbe`

```
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kong/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
        readinessProbe:
          periodSeconds: 1
          httpGet:
            scheme: HTTP
            port: 80
EOF
```

### 3. readinessProbe never success

```
$ kubectl get pod
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-849568d64c-8ljsn   0/1     Running   0          2m3s

$ kubectl describe pod httpbin-849568d64c-8ljsn
   ... snip ...
  Normal   Created    97s                 kubelet            Created container httpbin
  Normal   Started    97s                 kubelet            Started container httpbin
  Warning  Unhealthy  97s                 kubelet            Readiness probe failed: Get "http://10.244.1.3:80/": read tcp 10.244.1.1:52974->10.244.1.3:80: read: connection reset by peer
  Warning  Unhealthy  77s (x20 over 96s)  kubelet            Readiness probe failed: Get "http://10.244.1.3:80/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

* When namespace does not have `istio.io/dataplane-mode=ambient`, the readinessProbe works so ambient makes this failure. 
* Again, `istioctl install` works so `istioctl manifest generate` makes the failure.

### Version

```Text
$ istioctl version
client version: 1.19-alpha.fd63c3e0ec2dbb38667466d68cc8a075d39ac7da
control plane version: 1.19-alpha.fd63c3e0ec2dbb38667466d68cc8a075d39ac7da
data plane version: 1.19-alpha.fd63c3e0ec2dbb38667466d68cc8a075d39ac7da (3 proxies)
```
```


### Additional Information

_No response_

### Affected product area

- [X] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
I cannot reproduce this in my environment. Ambient traffic works fine with the `istioctl manifest generate` components. Including the bug report or some components' logs may be helpful.

**Comment by nak3** [comment]
> Ambient traffic works fine with the istioctl manifest generate components

The issue is not normal traffic but probe traffic. And our CI and I can produce the issue when the pod is deployed in the order `istio-cni-node` -> `ztunnel`.

> Including the bug report or some components' logs may be helpful.

What logs do you want to see, istio- cni or ztunnel? Ambient prints a lot of false postive error...
