### ISSUE TITLE
istio 1.18.0 upgrade/scratch deployment  breaks the all application reachability 

### ISSUE THREAD

**Issue by anannaya** [istio/istio#45799]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

 I trying to upgrade the istio with canary procedure , Now i have a both the versions of controlplane and ingress running. I have properly configured the service and gateway to point to 1.13.2 ingress gateway pods(before upgrade) . Now after upgrade none of the apps are reachable , 
 
 ELB apps not reachable 
 ALB apps says 502 bas gateway. 
 
 Internal within k8s service reachability works, Only external access via gateway is broken.
 
 ```
 k get po -n istio-system
NAME                                              READY   STATUS    RESTARTS   AGE
istio-ingressgateway-1-18-0-6bfbbbc647-bnllz      1/1     Running   0          36s
istio-ingressgateway-66645554d4-sv2hd             1/1     Running   0          7h38m
istio-ingressgateway-alb-1-18-0-67c59fd9c-nhf5q   1/1     Running   0          34s
istio-ingressgateway-alb-69c57f75c8-nfsls         1/1     Running   0          7h38m
istiod-1-13-2-5b7574489d-k2prm                    1/1     Running   0          8h
istiod-1-18-0-568b9cd57d-ncd4x                    1/1     Running   0          38s
jaeger-585bdbb6dc-m8xd4                           1/1     Running   0          41s
kiali-ffbb9f565-hxtjg                             1/1     Running   0          39s
 ```

### Version

```Text
client version: 1.13.1
control plane version: 1.13.2
data plane version: 1.13.2 (3 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
It is recommended to upgrade within 2 minor versions. There might be changes breaking backward compatibilities. I think you can examine the components' logs, and also try to enable debug log of the proxy to see if there are issues.

**Comment by anannaya** [comment]
@hanxiaop THanks for responding,  I haven't upgraded to newer version yet, You can see from above Both the control plane(istio +ingress) versions are running.   And the dataplane is still running with 1-13-2 version .   I did enable the debug logs ,i don't see the packets arriving at the ingress gateway pods itself .  Is there any upgrade envoyfilter causing the issue ?
```
 k get envoyfilter -n istio-system
NAME                                AGE
accesslog-settings                  10h
cccbufferlimit                      10h
security-by-default-header-filter   10h
stats-filter-1.11-1-13-2            4d20h
stats-filter-1.12-1-13-2            4d20h
stats-filter-1.13-1-13-2            4d20h
stats-filter-1.16-1-18-0            10h
stats-filter-1.17-1-18-0            10h
stats-filter-1.18-1-18-0            10h
tcp-stats-filter-1.11-1-13-2        4d20h
tcp-stats-filter-1.12-1-13-2        4d20h
tcp-stats-filter-1.13-1-13-2        4d20h
tcp-stats-filter-1.16-1-18-0        10h
tcp-stats-filter-1.17-1-18-0        10h
tcp-stats-filter-1.18-1-18-0        10h
```

**Comment by anannaya** [comment]
This is weird for old pods also listeners are missing , Any clue how to rectify this ?
```
(base) istio ananayak(k8s: staging-eks) $ istioctl proxy-config listeners istio-ingressgateway-66645554d4-bj855.istio-system --port 8443
ADDRESS PORT MATCH DESTINATION
(base) istio ananayak(k8s: anand-eks) $ istioctl proxy-config listeners istio-ingressgateway-66645554d4-bj855.istio-system --port 8443
ADDRESS PORT MATCH DESTINATION
(base) istio ananayak(k8s: anand-eks) $ istioctl proxy-config listeners istio-ingressgateway-66645554d4-bj855.istio-system --port 8080
ADDRESS PORT MATCH DESTINATION
```

**Comment by anannaya** [comment]
@hanxiaop  I deployed the istio 1.18.0 from scratch as well, I see the same issue .
```
(base) istio ananayak(k8s: anand-eks) $ istioctl proxy-status
NAME                                                          CLUSTER       CDS        LDS        EDS        RDS          ISTIOD                             VERSION
istio-ingressgateway-1-18-0-6bfbbbc647-h7ccc.istio-system     anand-eks     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-1-18-0-568b9cd57d-m8wkj     1.18.0
(base) istio ananayak(k8s: anand-eks) $
```
