### ISSUE TITLE
Use `PodPreset` to inject sidecar and init container

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#458]
The Kubernetes is working on a project which want to [use `PodPreset` to inject sidecar and init container](https://github.com/kubernetes/kubernetes/issues/43874) , istio can leverage this to inject sidecar and init container to deployment.

Just trace the issue here, and we can start this once https://github.com/kubernetes/kubernetes/issues/43874 finished.

**Comment by andraxylia** [comment]
We investigated this option and we decided not to use PodPreset for istio.

**Comment by gyliu513** [comment]
@andraxylia can you please show more detail for how to inject init-container and sidecar container to deployment? Using `istioctl` really bring some trouble to integrate Kubernetes with istio.

**Comment by andraxylia** [comment]
Istioctl kube-inject is the current way of injecting containers. Can you details the troubles into istio-users mailing list?

For next release, we plan to support transparent injection via extensible admission controllers, not via the PodPreset.

**Comment by gyliu513** [comment]
Sure, I will move to istio-users mail list, thanks @andraxylia

**Comment by warmchang** [comment]
PR is in process: https://github.com/kubernetes/kubernetes/pull/71479
