### ISSUE TITLE
Uninstall istio revision with istioctl -f will remove other ingress

### ISSUE THREAD

**Issue by bright-ren** [istio/istio#45805]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I installed istio 1.17.3 with istioctl with minimal profile and revision, and then install several ingressgateway with empty profile in different yaml file and separate namespaces. When I want to canary upgrade istio, and uninstall istiod 1.17.3 only and leave those ingressgateway unchanged, I tried several ways,  none of them worked for me, everytime it will remove entire istiod and all ingressgateways.
istioctl uninstall -f xxx.yaml  ，yaml file is the same file when install minimal profile with revision。

### Version

```Text
istioctl version
client version:1.17.3
istiod version:1.17.3
data plane version: 1.17.3(3 proxies)

kubectl version --short
client version:1.23.8
istiod version:1.25.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Do your other ingress have `metadata.name` set? I think without that the tool cannot differentiate the two installs.

Although if it didn't, I would have expected the install of the other to remove ("prune") the other..

**Comment by bright-ren** [comment]
> remove

Yes，every ingress has different metadata.name. but it seems all resource including separate installed ingress will be removed。
I also tried istioctl uninstall --revision 1-17-3， but got the same result。

**Comment by hanxiaop** [comment]
not stale

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/47961
