### ISSUE TITLE
XDS communication uses GRPC compression

### ISSUE THREAD

**Issue by wulianglongrd** [istio/istio#45801]
I haven't tested how much performance benefit can be brought by turning on compression at various sizes of XDS, but when XDS is large ([>4MB](https://github.com/istio/istio/blob/2a1a725154f0d6552e6f8e85976fd59c7fe80ee1/pilot/pkg/xds/monitoring.go#L179)), turning on compression may improve the performance of XDS communication (just a guess), such as pilot-discovery  and pilot-agent communication.

It looks like istio doesn't support XDS(grpc) compression yet.

Has anyone done related tests? thanks.

**Comment by howardjohn** [comment]
I worry this would be adverse on CPU usage. Would be interested to see tests.

**Comment by kyessenov** [comment]
Compression helps with minimizing the bytes sent but probably hurts the latency since Envoy no has to decompress in addition to processing of xDS. Unless you have some poor connectivity to the server, it's not going to help.

**Comment by frittentheke** [comment]
@kyessenov  @howardjohn  any chance this issue could be reopened?
Compression, especially when choosing the right algo is VERY VERY cheap on modern CPUs.
Kindly see my related post in Slack at https://istio.slack.com/archives/C37A4KAAD/p1775137646406619

**Comment by frittentheke** [comment]
Thanks @wulianglongrd @zirain!
What is your opinion on a PR adding (optional) compression to the XDS messages then?
In our mesh we observe multi-megabyte sized LDS messages at a high rate causing terabytes of control-plane traffic per day.

**Comment by frittentheke** [comment]
unstale
