### ISSUE TITLE
istio.io/istio/tests/e2e/tests/dashboard TestDashboards is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#4581]
Two consecutive daily release tests:

Failed: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/486/daily-e2e-rbac-auth-default/433

Passed: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/485/daily-e2e-rbac-auth-default/432

**Comment by douglas-reid** [comment]
a recent PR should have addressed this issue. there were two issues:

1. A change to service naming for Mixer actually broke the tests.
1. The mixer proxy was starting, but was not ready to receive traffic before the test sent traffic, resulting in no Report()s successfully being sent to Mixer for the duration of the tests.

Both should have been addressed by the latest PR.

Please reopen if the issue persists.
