### ISSUE TITLE
Configuring ports for inbound and outbound traffic via annotations can supported in the form of port ranges.

### ISSUE THREAD

**Issue by believening** [istio/istio#45810]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Configuring ports for inbound and outbound traffic via annotations can supported in the form of port ranges.

Both linux iptables and istio-iptables support configuring port ranges (e.g. `10000:20000`), but the inject validator only supports single ports separated by commas.

For exclude scenarios in particular, there is a general requirement in our practice.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

How the Inject Validator validates ports:
https://github.com/istio/istio/blob/6c56df453d13aedc48019da5fc74362746e6fcd6/pkg/kube/inject/validate.go#L159-L184

**Comment by howardjohn** [comment]
What do you need this for?

**Comment by believening** [comment]
We have hundreds of ports that do not expect to be intercepted

**Comment by believening** [comment]
@howardjohn anything new？
