### ISSUE TITLE
Ambient controller is prone to race conditions

### ISSUE THREAD

**Issue by nmittler** [istio/istio#45816]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I discovered this while working on https://github.com/istio/istio/pull/45797. The `AmbientController` and `AmbientIndex` both access the fields of`AmbientIndex` directly and manually lock/unlock its mutex in each case. This approach is very fragile and will certainly be the source of race conditions going forward unless we refactor the code. 

One thing that might help is if we force the `AmbientController` to access the `AmbientIndex` only through an interface that properly locks the internal data structures. Care will obviously have to be taken to make sure that the controller doesn't have to needlessly lock/unlock when operating in tight loops, etc. 

### Version

```Text
head
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
Good catch; IMO we should tackle this fairly soon
