### ISSUE TITLE
Support AWS IMDSv2 Tokens

### ISSUE THREAD

**Issue by adam-bloom** [istio/istio#45825]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Istio currently relies on IMDS v1 for AWS bootstrapping. If IMDSv2 is required, istio will fail to bootstrap. This is handled automatically by the AWS SDKs, but since the EC2 metadata calls do not use the AWS SDKs, this logic needs to be updated separately.

See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html and 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-v2-how-it-works.html

The fix should probably behave similarly to the SDKs, in that it tries to get a token, and falls back to not using a token if the token fetch fails.

We are looking at requiring IMDSv2 and noticed the istio calls in the metadata v1 logs (seen with https://github.com/aws/aws-imds-packet-analyzer/tree/main)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Updates needed in: https://github.com/istio/istio/blob/master/pkg/bootstrap/platform/aws.go

Also see https://github.com/istio/istio/pull/37873/, which switched to manually calling IMDS endpoints instead of relying on the AWS SDK to do so. The SDK has logic for handling IMDSv2 already. Reverting this change is another valid solution.

**Comment by adam-bloom** [comment]
see https://github.com/istio/istio/issues/42965 for previous report

**Comment by gabrielguernikatdiscovery** [comment]
We are having the same issue. We want to disable IMDSv1 for security reasons, but Istio does not support IMDSv2. Is there a timeline to get this supported?

**Comment by zirain** [comment]
I will take a look at this.

**Comment by saiharshitachava** [comment]
I still see IMDSV1 calls made from pilot agent even after upgrading istio to 1.19 
[2024-03-14 06:52:28,363] [WARNING] IMDSv1(!) (pid:25866:pilot-agent argv:podname:reviews-v2-74f8d795f4-56dv8) called by -> (pid:24955:containerd-shim argv:podname:reviews-v2-74f8d795f4-56dv8) -> (pid:1:systemd argv:/usr/lib/systemd/systemd --switched-root --system --deserialize 21) Req details: GET / HTTP/1.1, Host: 169.254.169.254, User-Agent: gcloud-golang/0.1, Accept-Encoding: gzip,

**Comment by zirain** [comment]
> @zirain I still see IMDSV1 calls made from pilot agent even after upgrading istio to 1.19 [2024-03-14 06:52:28,363] [WARNING] IMDSv1(!) (pid:25866:pilot-agent argv:podname:reviews-v2-74f8d795f4-56dv8) called by -> (pid:24955:containerd-shim argv:podname:reviews-v2-74f8d795f4-56dv8) -> (pid:1:systemd argv:/usr/lib/systemd/systemd --switched-root --system --deserialize 21) Req details: GET / HTTP/1.1, Host: 169.254.169.254, User-Agent: gcloud-golang/0.1, Accept-Encoding: gzip,

what's the version of sidecar?

**Comment by zirain** [comment]
or do you have same suitation with https://github.com/istio/istio/pull/46312#discussion_r1286088598?

**Comment by saiharshitachava** [comment]
@zirain I may be having the same issue mentioned in this comment 
proxyv2:1.19.0 is the version 

So Im assuming these v1 calls are safe to ignore ?Like the calls coming from gcloud-golang agent?

**Comment by saiharshitachava** [comment]
@zirain  sorry but is this gcloud event still good ?Will istio work fine even with this post IMDSv2 enabled ?

**Comment by zirain** [comment]
From the last report, this will worked on nodes with IMDSv2 enabled only on AWS.
If you find another issue, please kindly fire an new ticket.
