### ISSUE TITLE
istioctl bug-report --include AND/OR logic

### ISSUE THREAD

**Issue by abasitt** [istio/istio#45839]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am using istioctl bug-report and want to include two namespace e.g. istio15, istio17. As per the istioctl help it should work with below command.

## istioctl bug-report help which says ns1 OR ns2
istioctl bug-report --help
bug-report selectively captures cluster information and logs into an archive to help diagnose problems.
Proxy logs can be filtered using:
  --include|--exclude ns1,ns2.../dep1,dep2.../pod1,pod2.../lbl1=val1,lbl2=val2.../ann1=val1,ann2=val2.../cntr1,cntr...
where ns=namespace, dep=deployment, lbl=label, ann=annotation, cntr=container

The filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...'
The log will be included only if the container matches at least one include filter and does not match any exclude filters.
All parts of the filter are optional and can be omitted e.g. ns1//pod1 filters only for namespace ns1 and pod1.
All names except label and annotation keys support '*' glob matching pattern.

e.g.
--include ns1,ns2 (only namespaces ns1 and ns2)
--include n*//p*/l=v* (pods with name beginning with 'p' in namespaces beginning with 'n' and having label 'l' with value beginning with 'v'.)

## istioctl actual command which is taking AND logic instead of OR.

istioctl bug-report --include istio15,istio17

Target cluster context: kind-single-cl01-ipv4

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: { Namespaces: istio15 } AND { Namespaces: istio17 }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-05 23:16:57.027155578 -0700 PDT

In my understanding either help is wrong or the command itself should take the logic of OR instead of AND. on the namespace OR make more sense.

### Version

```Text
client version: 1.18.0
istiod version: 1.15.6
istiod version: 1.17.2
data plane version: 1.15.6 (1 proxies), 1.17.2 (3 proxies)
----
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
The OR means you can specify only one namespace instead of two, which is the correct description.

`--include istio15,istio17` means you want to include two namespaces instead of istio15 OR istio17 (which also doesn't make sense).
From the help message you pasted, it also shows `e.g.
--include ns1,ns2 (only namespaces ns1 and ns2)`.

**Comment by hanxiaop** [comment]
See https://github.com/istio/istio/blob/75b1937619a59cf2d352b4f6cb17236a50404de1/tools/bug-report/pkg/config/config.go#L37-L77 as an example.

**Comment by abasitt** [comment]
@hanxiaop thank you for sharing more details.

below line is also part of the --help
The filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...' if i am reading either this or the earlier line you shared, i am interpreting it as OR logic for namespace :D

IMO it make sense to have the option of including multiple namespaces. e.g. the best example would be I am asking a user to send a bug-report for ns istio15 and istio-sytem namespaces. currently the user have to run this separately and i initially thought it could be combine in one command with OR logic

**Comment by hanxiaop** [comment]
@abasitt Isn't it including both namespaces' info if you specify them together in the command? I thought I was.

**Comment by hanxiaop** [comment]
I'll double check it, this may be a bug. Thanks for sharing.

**Comment by abasitt** [comment]
It doesn't work. Thanks for the help :)

## for single namespace it works
istioctl bug-report --include foo

Target cluster context: kind-single-cl01-ipv4

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30

> include: { Namespaces: foo }

exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-06 00:32:41.465731397 -0700 PDT



Cluster endpoint: https://127.0.0.1:36911
CLI version:
version.BuildInfo{Version:"1.18.0", GitRevision:"697f4ff0fe6ee531bbd4f5f2a6b4b1f302c955a8", GolangVersion:"go1.20.4", BuildStatus:"Clean", GitTag:"1.18.0"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:


Fetching proxy logs for the following containers:

foo/sleep/sleep-9454cc476-qt2lg/istio-proxy
foo/sleep/sleep-9454cc476-qt2lg/sleep

## for two namespaces, it doesn't work
istioctl bug-report --include foo,bar

Target cluster context: kind-single-cl01-ipv4

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
`include: { Namespaces: foo } AND { Namespaces: bar }`
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-06 00:33:06.625643703 -0700 PDT



Cluster endpoint: https://127.0.0.1:36911
CLI version:
version.BuildInfo{Version:"1.18.0", GitRevision:"697f4ff0fe6ee531bbd4f5f2a6b4b1f302c955a8", GolangVersion:"go1.20.4", BuildStatus:"Clean", GitTag:"1.18.0"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:


Fetching proxy logs for the following containers:



Fetching Istio control plane information from cluster.
