### ISSUE TITLE
Feature: Expose client_go metrics

### ISSUE THREAD

**Issue by grzesuav** [istio/istio#45845]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I would like to see `client_go` metrics exported by `istiod`
**Describe alternatives you've considered**
N/A
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Client go exposes metrics related to API server connectivity (requests rate etc) which are not exported by istiod

**Comment by zirain** [comment]
can you share more details? which kind of metrics you need?
BTW there's a PR about queue metric: https://github.com/istio/istio/pull/45734

**Comment by grzesuav** [comment]
@zirain I mostly care about https://github.com/kubernetes/client-go/blob/master/tools/metrics/metrics.go

**Comment by zirain** [comment]
I don't know how to expose those things, maybe you can share your idea?

**Comment by tehlers320** [comment]
> I don't know how to expose those things, maybe you can share your idea?

you have to follow this
https://github.com/kubernetes-sigs/controller-runtime/blob/17893a8fae1e32209b8c8caa52f2ae6b32d6f6de/pkg/metrics/client_go_adapter.go#L42

these are disabled by upstream by default because of high cardinality which can blow away prometheus storage sometimes. 

What are you looking into specifically the latency one rarely seems to be of use, at least for us.

**Comment by zirain** [comment]
As the link said, it's deprecated for a long time, so I wouldn't it's a common use case for now.

maybe you can share more details about why you need this, let's find out if there's another way to achieve.

**Comment by grzesuav** [comment]
@zirain I need to check istiod incluence on API server, it can be enabled similar to  like https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/metrics/client_go_adapter.go#L43
