### ISSUE TITLE
init container run many times and exit with 1

### ISSUE THREAD

**Issue by kingsqv** [istio/istio#4585]
The init container run first time  eveyting  will running  normal。The iptables rules successful addition。
 But after a time  the init container Started time changed ，it  executed again ，and the  iptables rules alreday does exist 。so the init container exit with 1 for error iptables:Chain already exists 。then everything running also normal but  kubctl get po  display error: 
kubectl get po |grep ops-plat
smdev-ops-platform-6c4f559d9c-bfvvx                               0/2       Init:CrashLoopBackOff   0          34m

Who can give me some advice。
istio version 0.5.1
k8s version 1.8.4

The first time ouput  for init container 
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ IP_RANGES_INCLUDE=
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ ENVOY_PORT=15001
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ ENVOY_UID=1337
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ IP_RANGES_INCLUDE=172.0.0.0/8
+ getopts :p:u:e:i:h opt
+ [[ -z 15001 ]]
+ [[ -z 1337 ]]
+ iptables -t nat -N ISTIO_REDIRECT -m comment --comment istio/redirect-common-chain
+ iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001 -m comment --comment istio/redirect-to-envoy-port
+ iptables -t nat -A PREROUTING -j ISTIO_REDIRECT -m comment --comment istio/install-istio-prerouting
+ iptables -t nat -N ISTIO_OUTPUT -m comment --comment istio/common-output-chain
+ iptables -t nat -A OUTPUT -p tcp -j ISTIO_OUTPUT -m comment --comment istio/install-istio-output
+ iptables -t nat -A ISTIO_OUTPUT -o lo '!' -d 127.0.0.1/32 -j ISTIO_REDIRECT -m comment --comment istio/redirect-implicit-loopback
+ iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN -m comment --comment istio/bypass-envoy
+ iptables -t nat -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN -m comment --comment istio/bypass-explicit-loopback
+ IFS=,
+ '[' 172.0.0.0/8 '!=' '' ']'
+ for cidr in '${IP_RANGES_INCLUDE}'
+ iptables -t nat -A ISTIO_OUTPUT -d 172.0.0.0/8 -j ISTIO_REDIRECT -m comment --comment istio/redirect-ip-range-172.0.0.0/8
+ iptables -t nat -A ISTIO_OUTPUT -j RETURN -m comment --comment istio/bypass-default-outbound
+ exit 0

After a time the init container run again and exit 1 
istio-init:
    Container ID:  docker://b37369b393e2ce6392b7b7f19ce2447fe17a7091b32eaf28e1de180367f31d52
    Image:         sunquan/intio-init:10
    Image ID:      docker-pullable://sunquan/intio-init@sha256:092cf4f726bc0b063be7bb9256c851dd1b55082dc9e4ef803b1ee60c62a6c026
    Port:          <none>
    Args:
      -p
      15001
      -u
      1337
      -i
      172.0.0.0/8
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 28 Mar 2018 09:07:16 +0800
      Finished:     Wed, 28 Mar 2018 09:07:17 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>

This the script output
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ IP_RANGES_INCLUDE=
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ ENVOY_PORT=15001
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ ENVOY_UID=1337
+ getopts :p:u:e:i:h opt
+ case ${opt} in
+ IP_RANGES_INCLUDE=172.0.0.0/8
+ getopts :p:u:e:i:h opt
+ [[ -z 15001 ]]
+ [[ -z 1337 ]]
+ iptables -t nat -N ISTIO_REDIRECT -m comment --comment istio/redirect-common-chain
iptables: Chain already exists.

istio version 0.5.1
k8s version 1.8.4

**Comment by infa-ddeore** [comment]
@kingsqv did you find any solution for this?
