### ISSUE TITLE
envoy exited: signal: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ningyougang** [istio/istio#45850]
### Description

Send http request to istio-proxy with high TPS(e.g. 20K+), Istio-proxy pod restarted.
After found the istio-proxy log, found below critical error log
```
Envoy exited with error: signal: segmentation fault (core dumped)
```

Under low TPS, has no problem.

### Version

```Text
istio-proxy: 1.17.2
```

**Comment by howardjohn** [comment]
Just this single log line is not going to help much. However, per our security policy we request any crash logs are reported privately first. Can you send an email to https://istio.io/latest/docs/releases/security-vulnerabilities/#reporting-a-vulnerability with the full log? Thanks!
