### ISSUE TITLE
Add hostname package as a dependency for the VM istio-sidecar packages

### ISSUE THREAD

**Issue by shashankram** [istio/istio#45866]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The init script (istio-start.sh) uses the hostname command which isn't always installed in certain distros (e.g. CentOS 8).

### Version

```Text
n/a
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/45867
