### ISSUE TITLE
Missing cross namespace gateway coverage

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#45865]
https://github.com/istio/istio/blob/ccf69848e840062fecefa225d4f6b4b3744cd23d/tests/integration/pilot/gateway_test.go#L251 is meant to test a credential in another namespace. However, its actually deployed to istio-system. All the tests pass, though, so there is either a bug or we are not testing it properly.

We should fix it to deploy into the correct namespace and make sure we have test covage.

**Comment by dfz2019** [comment]
Hey @howardjohn is there any help needed for this issue?

**Comment by howardjohn** [comment]
Yes! It would be great to get someone to look into this. Feel free to start working on it if you are interested

**Comment by ofey404** [comment]
Should this issue be closed? Since #46313 has fixed it.
