### ISSUE TITLE
DNS resolution for pod hostnames

### ISSUE THREAD

**Issue by nmittler** [istio/istio#45895]
Ambient currently just sets the workload hostname directly from the pod [hostname field](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/ambientindex.go#L744). This is incorrect, as the hostname field is optional and if set, is usually a short hostname (not an FQDN).

The [k8s DNS docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) describe possible FQDNs for pods:

* **`pod-ip`.`namespace`.pod.`cluster-domain`**: Generated for all pods. Pod IP is in the form `1-2-3-4`. Istio just passes it through to k8s. Not sure there is much use for this host in the wild ... if the client already has the IP, why would they need DNS?
  * **Proposal: pass through to k8s**
* **`pod-ip`.`service-name`.`namespace`.svc.`cluster-domain`**: Generated for a pod when selected by a service. Proposal is the same as the one above, for the same reason:
  * **Proposal: pass through to k8s**
* **`spec.hostname`.`spec.subdomain`.`namespace`.svc.`cluster-domain`**: When sub domain field is set. This is [supported by Istio](https://github.com/istio/istio/blob/d8b21e02e754b6e93bf259ff7e226fafaa9c16d3/pkg/dns/server/name_table.go#L77) and should also be supported by Ambient.
  * **Proposal: implement in Ambient**

It should be noted that neither Istio nor k8s address the issue of duplicate pod hostnames across multiple clusters. To address this, there has been discussion within K8s MCS regarding the introduction of a cluster ID and incorporating it into pod FQDNs. We should follow up with k8s to see if there is any update there. 

**Describe alternatives you've considered**
NA

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by nmittler** [comment]
Thanks, John. I've updated the description ... PTAL

**Comment by howardjohn** [comment]
New description lgtm

**Comment by nmittler** [comment]
@howardjohn given that pod hostnames are fundamentally cluster-local in k8s, should we just accept that and use the key "cluster-id/pod-hostname" in ambient?

**Comment by howardjohn** [comment]
This is for on-demand? or something else? I thought the plan was to worry about on-demand for DNS later?

**Comment by nmittler** [comment]
@howardjohn

> This is for on-demand? or something else? I thought the plan was to worry about on-demand for DNS later?

No, not related to on-demand ... it's just regarding how to serve DNS for workload hostnames, where there may be duplicates across the mesh.

**Comment by howardjohn** [comment]
Why do we need a new key? the key for workload is already unique across clusters

**Comment by nmittler** [comment]
The key for DNS is just hostname, which isn't guaranteed to be unique across clusters.

**Comment by howardjohn** [comment]
Sorry I don't get it. Why does the XDS key matter here? Or by "key" do you not meant the XDS key?

We can have 2 Workloads with distinct keys but the same `hostname`. The DNS logic will just need to handle that and pick an appropriate one?

**Comment by nmittler** [comment]
> The DNS logic will just need to handle that and pick an appropriate one?

This is exactly what I'm suggesting in https://github.com/istio/istio/issues/45895#issuecomment-1627363516

**Comment by howardjohn** [comment]
I am confused about " should we just accept that and use the key "cluster-id/pod-hostname" in ambient?" though, which seems to suggest we change the key for workloads in the XDS?

**Comment by nmittler** [comment]
ah right ... so I added an additional index by hostname for workloads. However, it's likely error-prone in its current form since pod hostnames are only guaranteed to be unique within a cluster (not globally unique). So we need to fix that. Does that clarify?
