### ISSUE TITLE
Istio CNI may loop-install

### ISSUE THREAD

**Issue by costinm** [istio/istio#45906]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I was checking the CNI logs - it appears that re-install happens frequently, based on Installer.sleepCheckInstall(ctx context.Context) which adds a Watcher on the files.

The watcher is watching the binaries, CNI Net dir and the service account file. Based on the frequency of "Detected changes, attempting reinstall", the service account file is refreshed (new tokens) and that results in a full reinstall, to copy the new token file.

That's a bit inefficient - but there is a big risk that if other CNI plugin is also doing something like that - they'll loop with each other. It's also noisy and miss-leading - it should be a 'refreshing k8s token' log (or no log at all, it's a routine event).

### Version

```Text
Master
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Just be to clear, its only when the SA is refreshed, right? Which is at most once per hour? There was an issue where it infinitely looped immediately, but this was fixed this a while back: #44543

**Comment by costinm** [comment]
In my logs - it was only when the SA was refreshed, however the code as written will loop if any other CNI controller with similar code was installed. 

The code is checking the timestamps and config files ( AFAIK ) - and re-installs if it detects anything changed from what it expects. If a second CNI controller was installed (for example for another mesh, or a forked version of istio-cni used by a vendor, or someone reusing our code) - they will each attempt to replace the other. 

Not a problem if istio-cni is the only CNI with such aggressive code.

**Comment by bleggett** [comment]
The looping scenarios should be fixed with

- https://github.com/istio/istio/pull/46048
- https://github.com/istio/istio/pull/46366

since we noticed that as well.

> Not a problem if istio-cni is the only CNI with such aggressive code.

I know I'm preaching to the choir here so this is mostly for future issue-spelunkers, but Cilium and other things have similar logic. If we intend to install ourselves as a plugin on a node we can't assume we are 

- The only plugin
- The last/final plugin

or we have a bug that could easily either render the node unusable or be an open vector for CVEs.
