### ISSUE TITLE
After Istio 1.18.0, using the legacy stats EnvoyFilters will result in CPU and memory spikes

### ISSUE THREAD

**Issue by krisztianfekete** [istio/istio#45921]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After 1.18 switched to [native stats](https://github.com/istio/istio/pull/41991), you should stop using EnvoyFilters to customize telemetry as these will result in CPU and memory spikes.

In the logs, you will see `Unable to create Wasm HTTP filter`, and listener rejected entries too.
This should be mentioned at https://istio.io/latest/news/releases/1.18.x/announcing-1.18/upgrade-notes/.

Here you can see the spikes and warnings disappeared after I removed my filter. 
![image](https://github.com/istio/istio/assets/103492698/8b5fce96-032f-46c4-b9b0-1c73fdb786ca)

### Version

```Text
Istio 1.18.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by kyessenov** [comment]
EnvoyFilter had a version check that would stop it from applying on 1.18. Did you write the EnvoyFilter yourself?

**Comment by krisztianfekete** [comment]
Yes, and I think this is/was quite common for users who started out earlier. E.g. before Telemetry API you couldn't alter metrics any other way.
