### ISSUE TITLE
Possible limit on number of Envoy to Pilot connections 

### ISSUE THREAD

**Issue by costinm** [istio/istio#4593]
Found this in master, but likely to affect 0.7 as well.

To repro, need to have > 101 envoy clusters (running few pilot e2e tests with skip_cleanup and in different namespaces can produce this). Then exec in a proxy container and check localhost:15000/stats, look for "xds-grpc::x.x.x.x:15010::rq_active::NNN", and chck if NNN is ~same with number of clusters and not 100 or 101. Rq_Active should be the same with the number of out clusters.
(curl localhost:15000/clusters |grep added_via_api::true |wc)

Alternatively set a cluster with >100 services, and check that each service gets endpoints (i.e. works).
Worth trying this with MTLS and control plane auth enabled, but I've seen it with mtls disabled as well. 
Didn't get a chance to try it on 0.7 yet.

It's likely to be a setting in envoy config, hopefully just a false alarm.

(envoy clusters == number of services and port combinations, 50 services with 3 ports = 150 out clusters )

**Comment by hklai** [comment]
Any more update?
Is this really 0.7.0 release blocking?

**Comment by ldemailly** [comment]
I think it's fine if there isn't a regression from 0.6
for 0.8 we need to spend more time with scaling characterization (and error handling as this shouldn't fail without some clear message about the failure)

if we have a quick repro and quick fix we can make 0.7.1 too while we work on getting 0.8.0 stable

**Comment by costinm** [comment]
Adding few more people. 

I created  >1000 clusters, and it seems to reproduce the problem - envoy only fetches 100 clusters.

Looking at stats: 

cluster.xds-grpc.internal.upstream_rq_200: 100
cluster.xds-grpc.internal.upstream_rq_2xx: 100
cluster.xds-grpc.internal.upstream_rq_503: 10824
cluster.xds-grpc.internal.upstream_rq_5xx: 10824
cluster.xds-grpc.upstream_cx_tx_bytes_total: 131054
cluster.xds-grpc.upstream_rq_200: 100
cluster.xds-grpc.upstream_rq_2xx: 100
cluster.xds-grpc.upstream_rq_503: 10824
cluster.xds-grpc.upstream_rq_5xx: 10824
cluster.xds-grpc.upstream_rq_active: 1024
cluster.xds-grpc.upstream_rq_pending_overflow: 10824
cluster.xds-grpc.upstream_rq_total: 1024


cluster.outbound|http||vm-385.istio-test.svc.cluster.local.update_success: 3
..
cluster.outbound|http||vm-94.istio-test.svc.cluster.local.update_success: 0


curl localhost:15000/stats  |grep update_success |grep -v ": 0" |wc
103

curl localhost:15000/stats  |grep update_success |grep ": 0" |wc
1527

**Comment by costinm** [comment]
For v2 this is worse - since CDS is fetched first, then 100 EDS - LDS  never appears to make it to pilot
(with <100 services there are LDS logs ).

It sounds like a setting - 100 is the default max requests per TCP connection in HTTP2.

Options: 
- revert EDSv2 in 0.7 - we're back to number of services  * endpoints QPS. 
That requires just changing from GRPC to REST_LEGACY in the bootsrap

- wait until we find the magic setting to allow more grpc/h2 requests 

Note this is only investigating EDSv2 limits - @rkpagadala  is looking at the limits on the pilot
tcp proxy (used for TLS istio-on-istio), which may also have a similar limit on TCP connections (1024)

**Comment by hklai** [comment]
did 0.6 support that scale before (>100 clusters)? 

At the moment it does not look like this is a critical problem (as defined in https://github.com/istio/istio/tree/master/release#critical-bug-definition), and I don't think we need to  block the release for this.

We should, however, add this to the release notes as a known issue.

**Comment by ldemailly** [comment]
nice find!

**Comment by PiotrSikora** [comment]
@htuch it looks that gRPC async client doesn't queue nor retry requests when it cannot establish new stream (e.g. when it exceeds `SETTINGS_MAX_CONCURRENT_STREAMS`)? Any quick and obvious fix?

**Comment by rshriram** [comment]
is this occurring with envoy in front of Pilot? or is this between envoy and standalone pilot? 

You also need to bump max parallel retries to upstream server. Defaults to 3.

**Comment by costinm** [comment]
It's for the envoy in front of (each) app. They get a CDS response, with ~1500 services, and create one 'monitor' grpc request for each service. First 100 are fine. I can use /debug/edsz?push=1 to push - and 
tcpdump and logs show the 100 clusters get their endpoints. 

I suspect it's a setting somewhere - but not sure what. Normal h2 is to open a new tcp socket.
There is only one TCP socket between pilot and the sidecar.

This is with MTLS of, so envoy goes directly to pilot.

**Comment by kyessenov** [comment]
Are you sure it's not a bug in your management server? 503 might be a response due to failure to update the config maybe?

**Comment by ldemailly** [comment]
s/with MTLS of/without MTLS/ (or with MTLS off)

**Comment by costinm** [comment]
MTLS is off. And for 99 connections all worked fine. 

It seems increasing the max_streams on golang side solves the problem, so at least envoy respects the 
settings frame and the server-side value. Still a single TCP connection, but now it seems to get all clusters, should be a one-line fix.

Will look a bit at the settings for circuit breaking for the MTLS case tomorrow.

**Comment by costinm** [comment]
Turns out Envoy docs do mention in the circuit breaking section that H2 will only use a single TCP connection, so any GRPC or H2 server behind an envoy must set max streams and not rely on multiple TCP connections. 

I don't think this matches the h2 standard - and will likely affect many other applications planning to use
either h2 or grpc with envoy as a server. While GRPC makes it easy to set max streams - not sure how
all other languages and libraries can do this.

**Comment by PiotrSikora** [comment]
@ldemailly Done.

**Comment by htuch** [comment]
If you want to scale, you should either do ADS or https://github.com/envoyproxy/envoy/issues/2943.
