### ISSUE TITLE
Gateway helm chart - no option to set terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#45946]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
`terminationGracePeriodSeconds` option can't be set in [current gateway chart](https://github.com/istio/istio/tree/master/manifests/charts/gateway) 

**Describe alternatives you've considered**
No alternative except manually editing generated template

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
`terminationGracePeriodSeconds` setting needs changes if `preStop` hook has `sleep` for more than 30 seconds

**Comment by hanxiaop** [comment]
IIRC there's a PR already tried to fix this

**Comment by hanxiaop** [comment]
FYI https://github.com/istio/istio/pull/45431

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/46023
