### ISSUE TITLE
TestIngressController failing presubmit

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4596]
[prow build](https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/1362)

snippet
```
I0328 06:53:15.231] === RUN   TestIngressController
I0328 06:53:15.231] 2018-03-28T06:53:15.231473Z	info	Ingress controller watching namespaces "test"
I0328 06:53:18.232] --- FAIL: TestIngressController (3.00s)
I0328 06:53:18.233] 	controller_test.go:210: timeout waiting to receive expected rule count 5, actually received 0
```

**Comment by costinm** [comment]
I don't know much about it - seems to be environment specific, someone who can debug on prow needs to take a look, from the logs I can't guess what is wrong

**Comment by hklai** [comment]
The prow link points to a postsubmit run.
Anyhow, the test had been moved to e2e already, and I suppose this does not matter any more.
https://github.com/istio/istio/pull/4510

It has not been run in postsubmit for a few days.
https://k8s-testgrid.appspot.com/istio#istio-postsubmit&include-filter-by-regex=ingress&show-stale-tests=
