### ISSUE TITLE
sidecar can Automatic reporting tcp protocal? like mysql or other database?

### ISSUE THREAD

**Issue by njfanxun** [istio/istio#45964]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
I tried http, grpc sevice，Automatic reporting by sidecar and istio telemetry crd。but，mysql pod  sidecar didn't work。
Whether all tcp services do not support？still need some configuration？

**Comment by zirain** [comment]
https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols

**Comment by njfanxun** [comment]
> https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols

I feel like this has nothing to do with what I'm talking about. I declare it as mysql through the appProtocol, and I can already connect to the database through the sidecar.
