### ISSUE TITLE
Dual stack sidecar not listening on correct IP for readiness check.

### ISSUE THREAD

**Issue by cehoffman** [istio/istio#45970]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The issue is the pod never becomes ready because the proxy container's readiness probe fails due to connection refused. The reason the connection is refused is because envoy is not listening on the default IP of the pod. In my cluster the dual stack step lists the PodCIDRs with IPv6 first and IPv4 second. Thus the default IP for all Pods is the IPv6 address.

The envoy configuration in the proxy has the readiness probe endpoint configured to only listen on IPv4.

```
        "address": {
           "socket_address": {
             "protocol": "TCP",
             "address": "0.0.0.0",
             "port_value": 15021
           }
        },
```

Searching through the generated bug-report didn't see anywhere that reported the above configuration. In fact it looks like the system thinks there should be something listening on the IPv6 address at port 15021. However netstat in the bug-report confirms nothing is.

Netstat shown here for easy of reference.

```
$ netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 127.0.0.1:15004         0.0.0.0:*               LISTEN      1/pilot-agent
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      29/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      29/envoy
tcp6       0      0 :::15006                :::*                    LISTEN      29/envoy
tcp6       0      0 :::15006                :::*                    LISTEN      29/envoy
tcp6       0      0 :::15001                :::*                    LISTEN      29/envoy
tcp6       0      0 :::15001                :::*                    LISTEN      29/envoy
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
tcp6       0      0 :::9002                 :::*                    LISTEN      -
tcp6       0      0 :::9000                 :::*                    LISTEN      -
tcp6       0      0 :::9001                 :::*                    LISTEN      -
```

I installed istio using the Helm method as described in the docs since operator is discouraged and I don't like/want to use istioctl for manifest generation since it adds extra steps for GitOps maintenance for upgrades with ArgoCD. I am using the following charts and configuration.

## base:1.18.0

```yaml
base:
  validateGateway: true
```

## istiod:1.18.0

```yaml
global:
  logAsJson: true
  proxy:
    componentLogLevel: "misc:trace" # I tried getting more logs from the proxy, but changing this didn't produce any logs
pilot:
  env:
    ISTIO_DUAL_STACK: "true"
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_AGENT_DUAL_STACK: "true"
istio_cni:
  enabled: true
```

## cni:1.18.0

```yaml
```

## gateway:1.18.0

```yaml
env:
  ISTIO_DUAL_STACK: "true"
```

### Version

```Text
$ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (8 proxies)
$ kubectl version --short
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.27.3
$ helm version --short
v3.11.2+g912ebc1
```

### Additional Information

Target cluster context: admin@nxl

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-12 05:35:07.232862 -0500 CDT

Cluster endpoint: https://nxl.ceh.im:6443
CLI version:
version.BuildInfo{Version:"1.18.0", GitRevision:"697f4ff0fe6ee531bbd4f5f2a6b4b1f302c955a8", GolangVersion:"go1.20.4", BuildStatus:"Clean", GitTag:"1.18.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.18.0", GitRevision:"697f4ff0fe6ee531bbd4f5f2a6b4b1f302c955a8", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.18.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.18.0}

Fetching proxy logs for the following containers:

argocd/argocd-applicationset-controller/argocd-applicationset-controller-7786cb7547-8s8sv/argocd-applicationset-controller
argocd/argocd-dex-server/argocd-dex-server-58574dff5f-ddm2z/dex
argocd/argocd-notifications-controller/argocd-notifications-controller-7764bb774d-b7n28/argocd-notifications-controller
argocd/argocd-redis-ha-haproxy/argocd-redis-ha-haproxy-7c477cd9bd-9n7kx/haproxy
argocd/argocd-redis-ha-haproxy/argocd-redis-ha-haproxy-7c477cd9bd-glsnj/haproxy
argocd/argocd-redis-ha-haproxy/argocd-redis-ha-haproxy-7c477cd9bd-r6fj2/haproxy
argocd/argocd-repo-server/argocd-repo-server-5689479566-474tr/argocd-repo-server
argocd/argocd-repo-server/argocd-repo-server-5689479566-gwsdr/argocd-repo-server
argocd/argocd-server/argocd-server-646b4b54d9-r7vgq/argocd-server
bookinfo/details-v1/details-v1-59d9c6b59d-b4krq/details
bookinfo/details-v1/details-v1-59d9c6b59d-b4krq/istio-proxy
bookinfo/productpage-v1/productpage-v1-664d44d68d-ltq8f/istio-proxy
bookinfo/productpage-v1/productpage-v1-664d44d68d-ltq8f/productpage
bookinfo/ratings-v1/ratings-v1-844796bf85-lmfg8/istio-proxy
bookinfo/ratings-v1/ratings-v1-844796bf85-lmfg8/ratings
bookinfo/reviews-v1/reviews-v1-5cf854487-qzcnq/istio-proxy
bookinfo/reviews-v1/reviews-v1-5cf854487-qzcnq/reviews
bookinfo/reviews-v2/reviews-v2-955b74755-cwhfp/istio-proxy
bookinfo/reviews-v2/reviews-v2-955b74755-cwhfp/reviews
bookinfo/reviews-v3/reviews-v3-797fc48bc9-ff5bj/istio-proxy
bookinfo/reviews-v3/reviews-v3-797fc48bc9-ff5bj/reviews
bookinfo/tcp-echo/tcp-echo-5dd5786b4f-7x8sl/istio-proxy
bookinfo/tcp-echo/tcp-echo-5dd5786b4f-7x8sl/tcp-echo
cert-manager/cert-manager-cainjector/cert-manager-cainjector-d49fbbd7-j4d7g/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-5557b7b99d-wg42p/cert-manager-webhook
cert-manager/cert-manager/cert-manager-7fbf5bd9b8-gkqnf/cert-manager-controller
istio-ingress/istio-ingress/istio-ingress-68558ccf44-9qqxw/istio-proxy
istio-system/istiod/istiod-6746d9bdcd-f26zj/discovery
metallb-system/controller/controller-7bfbddb7f6-lggvk/controller
metallb-system/speaker/speaker-f6q9z/frr
metallb-system/speaker/speaker-f6q9z/frr-metrics
metallb-system/speaker/speaker-f6q9z/reloader
metallb-system/speaker/speaker-f6q9z/speaker
metallb-system/speaker/speaker-l5qcc/frr
metallb-system/speaker/speaker-l5qcc/frr-metrics
metallb-system/speaker/speaker-l5qcc/reloader
metallb-system/speaker/speaker-l5qcc/speaker
metallb-system/speaker/speaker-nbdhs/frr
metallb-system/speaker/speaker-nbdhs/frr-metrics
metallb-system/speaker/speaker-nbdhs/reloader
metallb-system/speaker/speaker-nbdhs/speaker
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gdcnx/csi-attacher
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gdcnx/csi-cephfsplugin
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gdcnx/csi-provisioner
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gdcnx/csi-resizer
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gdcnx/csi-snapshotter
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gtl5s/csi-attacher
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gtl5s/csi-cephfsplugin
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gtl5s/csi-provisioner
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gtl5s/csi-resizer
rook-ceph/csi-cephfsplugin-provisioner/csi-cephfsplugin-provisioner-645b765b47-gtl5s/csi-snapshotter
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-9g6tt/csi-cephfsplugin
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-9g6tt/driver-registrar
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-sqhzc/csi-cephfsplugin
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-sqhzc/driver-registrar
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-ws2q6/csi-cephfsplugin
rook-ceph/csi-cephfsplugin/csi-cephfsplugin-ws2q6/driver-registrar
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-7ttd2/csi-attacher
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-7ttd2/csi-provisioner
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-7ttd2/csi-rbdplugin
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-7ttd2/csi-resizer
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-7ttd2/csi-snapshotter
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-mdhvw/csi-attacher
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-mdhvw/csi-provisioner
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-mdhvw/csi-rbdplugin
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-mdhvw/csi-resizer
rook-ceph/csi-rbdplugin-provisioner/csi-rbdplugin-provisioner-745d56cbd5-mdhvw/csi-snapshotter
rook-ceph/csi-rbdplugin/csi-rbdplugin-ggdv7/csi-rbdplugin
rook-ceph/csi-rbdplugin/csi-rbdplugin-ggdv7/driver-registrar
rook-ceph/csi-rbdplugin/csi-rbdplugin-pwtk9/csi-rbdplugin
rook-ceph/csi-rbdplugin/csi-rbdplugin-pwtk9/driver-registrar
rook-ceph/csi-rbdplugin/csi-rbdplugin-t49nf/csi-rbdplugin
rook-ceph/csi-rbdplugin/csi-rbdplugin-t49nf/driver-registrar
rook-ceph/rook-ceph-mds-ceph-a/rook-ceph-mds-ceph-a-59fbf8b6cc-wxrnt/mds
rook-ceph/rook-ceph-mds-ceph-b/rook-ceph-mds-ceph-b-54c5448b95-zhbfc/mds
rook-ceph/rook-ceph-mgr-a/rook-ceph-mgr-a-79b695989-f64zs/mgr
rook-ceph/rook-ceph-mgr-a/rook-ceph-mgr-a-79b695989-f64zs/watch-active
rook-ceph/rook-ceph-mgr-b/rook-ceph-mgr-b-7bc8849cd5-sqwm5/mgr
rook-ceph/rook-ceph-mgr-b/rook-ceph-mgr-b-7bc8849cd5-sqwm5/watch-active
rook-ceph/rook-ceph-mon-g/rook-ceph-mon-g-58568b5954-rdwq8/mon
rook-ceph/rook-ceph-mon-h/rook-ceph-mon-h-7cfc87fc55-s5sxf/mon
rook-ceph/rook-ceph-mon-i/rook-ceph-mon-i-85fc5b47f6-nt8tr/mon
rook-ceph/rook-ceph-operator/rook-ceph-operator-674579d89b-9xjwp/rook-ceph-operator
rook-ceph/rook-ceph-osd-0/rook-ceph-osd-0-56747d9795-bw72w/osd
rook-ceph/rook-ceph-osd-1/rook-ceph-osd-1-74c467647d-dgjhb/osd
rook-ceph/rook-ceph-osd-10/rook-ceph-osd-10-56c5f8c598-xw87h/osd
rook-ceph/rook-ceph-osd-11/rook-ceph-osd-11-6c45c7d5dd-vtq8k/osd
rook-ceph/rook-ceph-osd-12/rook-ceph-osd-12-6cfc555598-8swqj/osd
rook-ceph/rook-ceph-osd-13/rook-ceph-osd-13-74b4d6f6cf-p9xxk/osd
rook-ceph/rook-ceph-osd-14/rook-ceph-osd-14-d6486cfd8-4g8gn/osd
rook-ceph/rook-ceph-osd-15/rook-ceph-osd-15-6d576546db-m2g82/osd
rook-ceph/rook-ceph-osd-16/rook-ceph-osd-16-7d97889b58-dzcvf/osd
rook-ceph/rook-ceph-osd-17/rook-ceph-osd-17-6485446f7-vnb4j/osd
rook-ceph/rook-ceph-osd-2/rook-ceph-osd-2-6cd666558c-fwffr/osd
rook-ceph/rook-ceph-osd-3/rook-ceph-osd-3-68f4448fbb-qj6gc/osd
rook-ceph/rook-ceph-osd-4/rook-ceph-osd-4-7657c46f9-2tkbc/osd
rook-ceph/rook-ceph-osd-5/rook-ceph-osd-5-69b7d89857-m65sc/osd
rook-ceph/rook-ceph-osd-6/rook-ceph-osd-6-86bf99c9dd-bxw27/osd
rook-ceph/rook-ceph-osd-7/rook-ceph-osd-7-6d8bd798d4-86zxf/osd
rook-ceph/rook-ceph-osd-8/rook-ceph-osd-8-84b785899c-6r2tw/osd
rook-ceph/rook-ceph-osd-9/rook-ceph-osd-9-76ff9b8545-rf6s8/osd
rook-ceph/rook-ceph-tools/rook-ceph-tools-57d5446cf5-2phg4/rook-ceph-tools
shares/samba/samba-2p6jw/samba
shares/samba/samba-4gqs5/samba
shares/samba/samba-jxrzh/samba

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace argocd) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argocd istio-injection=enabled' to enable it, or 'kubectl label namespace argocd istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-ingress) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-ingress istio-injection=enabled' to enable it, or 'kubectl label namespace istio-ingress istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace k8s-nxl) The namespace is not enabled for Istio injection. Run 'kubectl label namespace k8s-nxl istio-injection=enabled' to enable it, or 'kubectl label namespace k8s-nxl istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace metallb-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace metallb-system istio-injection=enabled' to enable it, or 'kubectl label namespace metallb-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace rook-ceph) The namespace is not enabled for Istio injection. Run 'kubectl label namespace rook-ceph istio-injection=enabled' to enable it, or 'kubectl label namespace rook-ceph istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace shares) The namespace is not enabled for Istio injection. Run 'kubectl label namespace shares istio-injection=enabled' to enable it, or 'kubectl label namespace shares istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service argocd/argocd-applicationset-controller) Port name metrics (port: 8080, targetPort: metrics) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-applicationset-controller) Port name webhook (port: 7000, targetPort: webhook) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-dex-server) Port name metrics (port: 5558, targetPort: 5558) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-metrics) Port name metrics (port: 8082, targetPort: 8082) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-notifications-controller-metrics) Port name metrics (port: 9001, targetPort: 9001) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-repo-server) Port name metrics (port: 8084, targetPort: 8084) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-repo-server) Port name server (port: 8081, targetPort: 8081) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service argocd/argocd-server-metrics) Port name metrics (port: 8083, targetPort: 8083) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service shares/samba) Port name smb (port: 445, targetPort: 445) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service metallb-system/webhook-service) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Creating an archive at /Users/cehoffman/Projects/personal/nxl/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/c1/vtyp485126q7r541p93229vc0000gn/T/bug-report.
Done.

[bug-report.tar.gz](https://github.com/istio/istio/files/12027032/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by jacob-delgado** [comment]
I'll look into this. Dual-stack with IPv6 preferred addressing is a case we don't usually check for in the code.

**Comment by leosarra** [comment]
I think the fix for this issue was merged by @kfaseela .
If that's the case then the issue can be closed

**Comment by kfaseela** [comment]
https://github.com/istio/istio/pull/47022 fixes this
