### ISSUE TITLE
Disable CNI ambient controller by default

### ISSUE THREAD

**Issue by costinm** [istio/istio#45989]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Starting an issue for tracking and to get feedback. 

In ambient we have a CNI controller that watches namespaces/pods and if ambient is added, will move existing pods to ambient by intercepting. This seems like a very good tool for migrations - but the behavior is actually very dangerous:
- all existing connections will be interrupted - and not clear if either side will be notified ( the packets go to ztunnel )
- production systems generally don't want an entire namespace to be suddenly moved and broken at once.

In addition the code is slightly different from regular CNI - just a quick review showed only one pod IP is intercepted ( vs all ), and likely there are other differences. 

Error handling is also tricky - failure to setup interception at startup results in pod not starting, but the controller can't do much. 

The proposal here is to turn it off by default until it is in a production-usable state - and ideally focus on this after we have ambient released, or maybe leave it to vendors or advanced users. This will reduce the risks and testing surface for ambient too.

Or we might just fully drop it  (or move to an ecosystem repo) - allowing us to simplify some of the code, it seems there is quite a bit of complexity to bolt this functionality and reuse code. CNI is quite sensitive and simplifying it would be a good benefit. 

### Version

```Text
latest
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by bleggett** [comment]
> In ambient we have a CNI controller that watches namespaces/pods and if ambient is added, will move existing pods to ambient by intercepting. This seems like a very good tool for migrations - but the behavior is actually very dangerous:
> 
>     * all existing connections will be interrupted - and not clear if either side will be notified ( the packets go to ztunnel )
> 
>     * production systems generally don't want an entire namespace to be suddenly moved and broken at once.
> 

Agree and FTR [wrote up a proposal outlining the ways in which the CNI controller _could/should_ do this stuff intelligently with revisions](https://docs.google.com/document/d/1qcgffUGLmK6qnoHy0rcDfbMrr1fKfcWZZQ7JJO3zi1o/edit?usp=sharing&resourcekey=0-qS576ANmdsq0ZqK3w_4YXg), but at this time there's not an appetite for SxS ztunnel, which is a prereq for doing this intelligently.

> Error handling is also tricky - failure to setup interception at startup results in pod not starting, but the controller can't do much.

We will never be able to do a lot about that specifically due to how CNI plugins work, but I don't think it's such a bad thing since it does prevent traffic leakage - generally agree tho.

> The proposal here is to turn it off by default until it is in a production-usable state - and ideally focus on this after we have ambient released, or maybe leave it to vendors or advanced users. This will reduce the risks and testing surface for ambient too.
> Or we might just fully drop it (or move to an ecosystem repo) - allowing us to simplify some of the code, it seems there is quite a bit of complexity to bolt this functionality and reuse code. CNI is quite sensitive and simplifying it would be a good benefit.

Most of the mess in the CNI comes from attempts to create abstractions for logic that only one thing ever actually uses - makes it far more complex than it needs to be.

I'm not fond of it as it sits either but I'm not sure it's less production-ready than the rest of ambient. It's certainly the most complex part of ambient outside of ztunnel and the control plane as it sits. I don't really have a horse in this race. 

I wouldn't object to:

- Splitting ambient CNI and sidecar CNI machinery into separate components/containers (they really aren't compatible/not much is effectively sharable)
- Moving CNI to an external repo
- Disabling by default

**Comment by costinm** [comment]
To be clear - not suggesting to change anything about ambient CNI ( in this context ).

Just the 'migration controller' that doesn't actually implement normal CNI plugin, but does things differently (and uniquely - it is not a supported CNI mechanism). 

I forgot to mention - this cam also remove a bunch of permissions from istio-cni daemon set and it wouldn't have to run in host network.

**Comment by bleggett** [comment]
> To be clear - not suggesting to change anything about ambient CNI ( in this context ).
> 
> Just the 'migration controller' that doesn't actually implement normal CNI plugin, but does things differently (and uniquely - it is not a supported CNI mechanism). 
> 
> I forgot to mention - this cam also remove a bunch of permissions from istio-cni daemon set and it wouldn't have to run in host network.
> 
> 

It would change ambient rather drastically tho, no? 

It would take us from a model where pods were moved in and out of ambient capture by labelling to a model where each and every workload pod had to be recycled to move in and out of ambient.

At the very least that's a poorer tirekicking experience.

**Comment by costinm** [comment]
Re maintainership - I don't think that's an issue, the design is a bigger problem ( operationally - i.e. from a SRE perspective), as well as priority - it is not required and there are plenty of things blocking the beta. If people have time - would be much better for the next few months to work on that, there are quite a few other things ( alternative protocols,
etc) that we delayed until after 1.0 to better focus. 

In the 'demo' profile we can keep the flag on - my concern is that a user installing Ambient 1.0 ( or whatever we call the first production-ready ambient release) should only have features that are production-ready and beta+ - at least in the 
official release that we ship.

**Comment by bleggett** [comment]
> It is a poorer demo experience maybe - but I hope we all understand it is not suitable for production - either migration or operations. The breaking of all connections ( probably silently, which is the worst ) is a huge red flag and while complex solutions may exist - we don't have them now. 

Fair, and I absolutely agree - that's why, as mentioned, I previously called out the ways in which the current CNI approach is operationally lacking and outlined several solutions in that RFC doc. The lack of operational controls is an issue.

> And having a demo where we show this migration - and then tell users 'wait, don't use this in any prod ' doesn't make sense. The error handling ( a pod may or may not be intercepted ) is another huge red flag for any security user. In production - when we ship beta - ambient will work like any other CNI provider, at startup - and it is hard enough to make this mode work reliably and safely. Inventing a new post-startup CNI is cool - and maybe some vendors can provide and maintain such a feature, but I think OSS should be boring and simple in the most critical step in istio pod lifecycle. In any case - this bug is about 'off by default' when we ship Ambient beta, and clear warnings on the flag that 'not suitable for prod, demo only, don't ask for support if you use this option'.

If there's a desire to make it off by default due to lack of production readiness, no issues with that. That's at best a short term fix tho.

**Comment by costinm** [comment]
Thanks - will put together a PR to add an option, with off by default.

We can discuss longer term plans separately - I strongly believe the 'core'
functionality of ambient interception should move into upstream CNI
providers, to guarantee compatibility/non-conflicting with their
implementation and changes - and consistency with other meshes. And for
CNI providers that don't provide this - a very minimal and clean 'fallback'
CNI for new and no-legacy users is best.

The controller is primarily for migrations - which is a very tricky
problem, and may benefit from being part of a separate set of tools
focused on migrations - I hope we agree that for a user who has migrated to
ambient or is using 'on by default' or has a CNI that
handles interception - there is no use for having the controller. Also
migration is a very complicated business with significant costs (
watching resources, higher permissions, etc), and some users may just do
clean installs first and no live migrations.

So splitting up the current mixed package may be the best - this is not a
'monolith vs microservices' argument, but about
a super-hard to upgrade and super-high permission component ( the core CNI
) that may have a much longer upgrade
cycle staying separate from a high-velocity and complex code for migration.
I would go even one step further and
also split the 'classic'/boring iptables from eBPF ( I don't think any user
would have both ).

Not sure if conditional compilation or separate directories - given that
ambient doesn't support the annotations and may
eventually be on by default it may be worth having it as a super-clean
ambient-only CNI without the legacy.

**Comment by costinm** [comment]
As an update: it turns to be a bit more difficult than it seems, the 'migration controller' is also involved in setting up the node interception.

**Comment by bleggett** [comment]
> As an update: it turns to be a bit more difficult than it seems, the 'migration controller' is also involved in setting up the node interception.

Yes, the ambient-specific interception logic would have to move into the CNI plugin proper, out of the controller.

That should be possible (plugin already has its own iptables/kube client infrastructure), but will take a bit of doing.
