### ISSUE TITLE
Prow wiki does not work

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#45985]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

There are a few things wrong with the [Working with Prow](https://github.com/istio/istio/wiki/Working-with-Prow) section of the wiki. 

First, the instructions to install `mkpod`, `phaino` ,and `mkpj` don't work. You can't install executables using `go get` in as of [Go 1.18](https://go.dev/doc/go-get-install-deprecation). Further `go install` doesn't work either because of the replace directives in the `go.mod` file. I installed these executables from source, and I'm not sure if there is another way to do so.

Some other minor enhancements:
* mention that pods from `mkpj` need nodes labeled with `test: testing-pool`.
* mention that pods from `mkpj` require certain service accounts to run
* redirect the output of the `mkpod` example to a `pod.yaml`, much like the in the `mkpj` example.
* reference [`prow/config/jobs/README.md`](https://github.com/istio/test-infra/blob/master/prow/config/jobs/README.md)
* include instructions on how to retrieve artifacts
* mention `make gen` somewhere since we need that to actually generate the configurations.

I'm happy to work on these, just not sure how to proceed given that much of this lives on the wiki.

### Version

```Text
-
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ericvn** [comment]
I'm not sure if members get the authority to update the wikis, but I suspect not (members have triage ability). If you have the ability, you can certainly update it. Otherwise, if you can find a maintainer to work with who can help with the updates, that works as well.

**Comment by Stevenjin8** [comment]
Fixed
