### ISSUE TITLE
Istiod never becomes ready when sidecar injection is disabled

### ISSUE THREAD

**Issue by arsenetar** [istio/istio#45990]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Upgraded Istio from 1.16.5 to 1.17.3 and now istiod no longer becomes ready.  Upon further inspection istiod is outputting:
`warn	sidecar injector is not ready`, which when looking into the code is due to the combined readiness endpoint.  Our Istio is configured with injection disabled, so this should not be part of the readiness check.

It appears the changes in: https://github.com/istio/istio/commit/b0ed8cb185c27fcd9bc008c0f04f84f6120d1805, did not either:
1. Conditionally add the probe
2. Set the probe to ready if injection was not enabled when `Server.initSidecarInjector()` exits early due to injection not being enabled/configured.

I would propose adding the readiness to true within `Server.initSidecarInjector()` on early exit as that should catch the various (non-error) reasons why injection may not be enabled without duplicating logic.

### Version

```Text
istioctl version     
client version: 1.18.0
control plane version: 1.16.5 (note this is last ready version not the version with the issue)
data plane version: 1.17.3 (6 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by arsenetar** [comment]
This change https://github.com/coreweave/istio/commit/a454ceb7f11d25418d186f5118002298a4bd2c4e should fix the issue, I will likely open a PR after verifying.

**Comment by hzxuzhonghu** [comment]
Thanks for investigating, welcome to fix
