### ISSUE TITLE
Add a new CRD to specify NetworkGateway 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#45994]
Currently we have many ways to set network agteway address:

1. meshNetworks
2. loadbalancer k8s service
3. k8s service nodeport

Onging ones:

1. gateway resource https://github.com/istio/istio/pull/45342
2. external address k8s svc annotation https://github.com/istio/istio/pull/45903

These capabilities are very separate, I am thinking we should have a global API, which can provide all the above capabilities.

I can file a proposal if possible.

**Comment by hzxuzhonghu** [comment]
cc @howardjohn @ramaraochavali @stevenctl

**Comment by stevenctl** [comment]
Gateway API is extensible enough. I'd be surprised if we need to move again.

**Comment by hzxuzhonghu** [comment]
How could gateway api enough to express node port svc?

**Comment by hzxuzhonghu** [comment]
And i donot think it has a field to express network id. https://github.com/istio/istio/pull/45342 watches gateway from all the clusters, while that may require users to set separately. 

Currently it is far from satisfying istio cases
```
type GatewayAddress struct {
	// Type of the address.
	//
	// +optional
	// +kubebuilder:default=IPAddress
	Type *AddressType `json:"type,omitempty"`

	// Value of the address. The validity of the values will depend
	// on the type and support by the controller.
	//
	// Examples: `1.2.3.4`, `128::1`, `my-ip-address`.
	//
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	Value string `json:"value"`
}
```

**Comment by hzxuzhonghu** [comment]
not stale
