### ISSUE TITLE
Small problem with the samples doing the "Setup/Getting started"

### ISSUE THREAD

**Issue by 1majom** [istio/istio#45999]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In the [Open the application to outside traffic part of the Getting started page](https://istio.io/latest/docs/setup/getting-started/#ip) there's a small problem.

When running the `istioctl analyze` command it gives the "IST0104" warning code. Because the sample file uses port 8080, but [according to the reference](https://istio.io/latest/docs/reference/config/analysis/ist0104/) "a default IngressGateway is only open on ports 80, 443, 31400, and 15443." This way the tutorial would not go on easily for new comers.

### Version

```Text
$ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (8 proxies)
$ kubectl version
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ericvn** [comment]
I saw something similar, and possibly fixed by https://github.com/istio/istio/pull/45943.

**Comment by 1majom** [comment]
Oh okay.  Thanks!
