### ISSUE TITLE
Place to keep envoy-facing APIs

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4599]
We need a place for Istio-specific envoy API (include those that are not planned for upstream). In the recent PR (https://github.com/istio/api/pull/415), we put it under envoy folder in API repo, but there are concerns that it might cause confusion. Before that, there are few others (mixer filter, jwt filter) that are kept in less obvious folder structure.

Alternative option is having this under proxy, but will need build infra and dependency changes in order to use it.

**Comment by andraxylia** [comment]
@diemtvu please label the areas for new issues.

**Comment by ZackButcher** [comment]
So my stance on this is as follows: these protos should live beside their implementations for now, in istio/proxy. If/when they move upstream we can import them from envoyproxy/data-plane-api; till then all Envoy specific C++ code and its configuration should live together in istio/proxy.

**Comment by ZackButcher** [comment]
@geeknoid @rshriram @louiscryan @frankbu as the main people maintaining the istio/api repo, opinions here w.r.t. where this type of config should live?

**Comment by geeknoid** [comment]
I agree with Zack. Stuff in istio/api is about programming Istio components and not about how Istio talks to with external components.

So let's put this kind of stuff in istio/proxy instead.
