### ISSUE TITLE
Istio Upgrade path from 1.17.1 to 1.18

### ISSUE THREAD

**Issue by VarunTyagi86** [istio/istio#46026]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have Istio 1.17.1 running and we would like to upgrade to latest stable Istio version 1.18.0.

I would like to know if we can upgrade from 1.17.1 to 1.18.0 or firstly we need to upgrade from 1.17.1 -> 1.17.3 -> 1.18.0 .

Please guide us what will be the upgrade path. 

### Version

```Text
istioctl version 1.17.1
```

### Additional Information

NA

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
You go directly. See https://istio.io/latest/docs/setup/upgrade/canary/#before-you-upgrade which explains this
