### ISSUE TITLE
wasmplugin: Image pull retry if any issue hits

### ISSUE THREAD

**Issue by MengjiaLiang** [istio/istio#46033]
**Describe the feature request**
We've seen the issue that seems the wasm plugin doesn't have any retry mechanism if the image pull failed.
I didn't find any retry logic in https://github.com/istio/istio/blob/master/pkg/wasm/imagefetcher.go and https://github.com/istio/istio/blob/master/pkg/wasm/cache.go

The retry is a good feature that helps deal with cases like image pull failure due to rate-limiting from the container registry.

**Affected product area (please put an X in all that apply)**
[ x] User Experience

**Comment by zirain** [comment]
if there's a rate limit, retry seems not work in a short time.

**Comment by ramaraochavali** [comment]
yeah if it is already rate limited, immediate retries would put additional pressure. Adding a retry here means, we would delay sending the rewritten config to Envoy.

**Comment by MengjiaLiang** [comment]
Yeah. I think the `retry` here means a retry mechanism with retries and delays in a specific time window. A single retry definitely won't help on this.

Some observation from our side is we have a CI pipeline that deploys 50+ helm charts and 100+images during the process. For all other components, the image-pull failure due to the rate-limiting from the registry will be mitigated after a few minutes due to the retry mechanism. But the wasmplugin image pull failure will not be mitigated and hence break the CI job
