### ISSUE TITLE
Loose CNI for ambient

### ISSUE THREAD

**Issue by costinm** [istio/istio#46032]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Reviewing the CNI code, there are a couple of potential issues ( some have TODOs - but not clear they're tracked):
- ztunnel is identified as 'any pod with a label app=ztunnel' - any pod can set this label. There is no check on namespace or service account - unless I miss something it seems pretty easy for a random user to take over ztunnel
- the logic is waiting for ztunnel to be ready before setting up the node iptables - and it does cleanup when it is not ready.
Instead it should block traffic when ztunnel is not ready, and prevent the start of any pod that requires ztunnel until ztunnel becomes ready. 

I think the correct logic is:
- istio cni plugin to fail any pod that requires ambient until ztunnel is ready ( so it can be tried on a working node )
- plugin should check namespace and name of the pod, and if it is ztunnel: enable the node rules and apply the 
ztunnel pod rules using the normal plugin process ( no need for the installer to watch or run with elevated permissions)
- plugin should set 'block' rules when ztunnel pod stops ( it does get called on delete ) unless a newer pod starts

### Version

```Text
latest
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
That first bullet point coincides with some of the impersonation prevention work @jaellio is going to be working on. @costinm can you link to some code snippets where you see the ztunnel labeling assumption?

**Comment by costinm** [comment]
https://github.com/istio/istio/blob/f94f0b68d814312fbd8ada557bdcd5ace58f4758/cni/pkg/ambient/podutil.go#L67

called from https://github.com/istio/istio/blob/f94f0b68d814312fbd8ada557bdcd5ace58f4758/cni/pkg/ambient/informers.go#L105 - to mark a pod as the new ztunnel pod and redirect everything to it 

as well as https://github.com/istio/istio/blob/f94f0b68d814312fbd8ada557bdcd5ace58f4758/cni/pkg/ambient/informers.go#L89 to exclude a pod from interception.

**Comment by costinm** [comment]
I can send a PR - or defer to @jaellio, I am waiting for a conclusion on what namespace to use for ztunnel ( since simplest fix is to also check the namespace of the pod ), also waiting for people more familiar with the code to confirm, I may have missed some other checks.
