### ISSUE TITLE
Seeing few seconds of downtime during ingress gateway canary upgrade.

### ISSUE THREAD

**Issue by anannaya** [istio/istio#46052]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Seeing few seconds of downtime during ingress gateway canary upgrade.
```
kubectl patch -n istio-system service istio-ingressgateway -p '{"spec":{"selector":{"istio.io/rev": "1-17-4"}}}'
kubectl patch -n istio-system gateway default-gateway  --type=merge -p '{"metadata":{"labels":{"istio.io/rev": "1-17-4"}},"spec":{"selector":{"istio.io/rev": "1-17-4"}}}'
kubectl patch -n istio-system service istio-ingressgateway-alb -p '{"spec":{"selector":{"istio.io/rev": "1-17-4"}}}'
kubectl patch -n istio-system gateway default-gateway-alb  --type=merge -p '{"metadata":{"labels":{"istio.io/rev": "1-17-4"}},"spec":{"selector":{"istio.io/rev": "1-17-4"}}}'
istioctl x revision tag set prod-stable --revision 1-17-4 --overwrite --skip-confirmation
```

### Version

```
client version: 1.17.4
control plane version: 1.17.4
data plane version: 1.17.4 (29 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by ksubrmnn** [comment]
Can you add more info? Which doc are you following to upgrade? Can you provide more details about istio's initial state? At which point does the outage occur? Logs would also be helpful

**Comment by anannaya** [comment]
@ksubrmnn  Thanks for responding , I did test in-place ingress upgrade as well Seeing this error ALB gateways. Downtime is around 50sec , i can see "response_code_details: route_not_found" error . 

Does RDS sync needs more time during the upgrade? 
We use a umbress helm chart where gateways and istiod part of single chart , which is upgraded together .

**Comment by anannaya** [comment]
I figure out the issue , We are loosing the listeners for sometime when we update `istio.io/rev` labels in the istio gateways. 
Thats weird behaviour .  Anyway i removed the label for gateways which makes my ZERO downtime during the upgrade/Fallback.
