### ISSUE TITLE
 webhook is not ready, retry","controller":"validation"

### ISSUE THREAD

**Issue by sakumar6** [istio/istio#46065]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio 1.18 

Istiod pod are filled with error:
`{"level":"info","time":"2023-07-18T22:45:23.289400Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:45:23.289424Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=66176) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:45:23.289436Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 10): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:46:14.498054Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:46:14.498076Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=66176) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:46:14.498089Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 11): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:47:14.507087Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:47:14.507131Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=66176) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:47:14.507140Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 12): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:48:14.516201Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:48:14.516226Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=66176) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:48:14.516236Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 13): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:49:14.523174Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:49:14.523208Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=66176) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:49:14.523218Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 14): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:49:33.394815Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid rejected for the wrong reason: Internal error occurred: failed calling webhook \"validation.istio.io\": failed to call webhook: Post \"https://istiod.istio-system.svc:443/validate?timeout=10s\": Address is not allowed"}
{"level":"info","time":"2023-07-18T22:49:33.401791Z","scope":"validationController","msg":"Successfully updated validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore,resourceVersion=67761)"}
{"level":"error","time":"2023-07-18T22:49:33.401820Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 15): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:49:33.406344Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:49:33.406359Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=67761) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:49:33.406367Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 16): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:50:14.534917Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:50:14.534941Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=67761) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:50:14.534951Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 17): webhook is not ready, retry","controller":"validation"}
{"level":"info","time":"2023-07-18T22:51:14.546440Z","scope":"validationController","msg":"Not ready to switch validation to fail-closed: dummy invalid config not rejected"}
{"level":"info","time":"2023-07-18T22:51:14.546466Z","scope":"validationController","msg":"validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=67761) is up-to-date. No change required."}
{"level":"error","time":"2023-07-18T22:51:14.546475Z","scope":"controllers","msg":"error handling /istiod-default-validator, retrying (retry count: 18): webhook is not ready, retry","controller":"validation"}`

I have already tried with `HostNetwork=true/false`, I am getting this error.

tried running:
```
kubectl get --raw /metrics | grep apiserver_admission_webhook_rejection_count   

apiserver_admission_webhook_rejection_count{error_type="calling_webhook_error",name="namespace.sidecar-injector.istio.io",operation="CREATE",rejection_code="400",type="admit"} 168
```

### Version

```Text
client version: 1.18.1
control plane version: 1.18.0-solo-fips
data plane version: 1.18.0-solo-fips (2 proxies)istioctl bug-report                                                                                                                                                                                                  <aws:cu_manowar_dev>

Target cluster context: *****-s01150

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-07-18 16:03:34.218446 -0700 PDT



Cluster endpoint: **************eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.18.1", GitRevision:"b39cf40807721c60f7b29e3106e37faa5e5dbac7", GolangVersion:"go1.20.6", BuildStatus:"Clean", GitTag:"1.18.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.18.0-solo-fips", GitRevision:"39989454c4589a430f5b70a861f98bf424d12d18", GolangVersion:"go1.20.5 X:boringcrypto", BuildStatus:"Clean", GitTag:"1.18.0-solo-fips"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.18.0-solo-fips", GitRevision:"39989454c4589a430f5b70a861f98bf424d12d18", GolangVersion:"go1.20.5 X:boringcrypto", BuildStatus:"Clean", GitTag:"1.18.0-solo-fips"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.18.0-solo-fips}


Fetching proxy logs for the following containers:

istio-system/istio-cni-node/istio-cni-node-6hvz9/install-cni
istio-system/istio-cni-node/istio-cni-node-jm4dk/install-cni
istio-system/istio-cni-node/istio-cni-node-wxvfv/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-74cd6b99c4-2trs8/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-74cd6b99c4-6bqgs/istio-proxy
istio-system/istiod/istiod-7b556cd665-w4pbm/discovery
istio-system/istiod/istiod-7b556cd665-wszhd/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0117] (Deployment istio-system/istio-ingressgateway) No service associated with this deployment. Service mesh deployments must be associated with a service.
Info [IST0102] (Namespace bar) The namespace is not enabled for Istio injection. Run 'kubectl label namespace bar istio-injection=enabled' to enable it, or 'kubectl label namespace bar istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /Users/sakumar/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/5y/5py24npj2k18ws5mjj3qtg1w0000gp/T/bug-report.
Done
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
It seems like the apiserver has rejected the config, and this could be network issues. Is your apiserver able to reach to Istiod?

**Comment by dabmajor** [comment]
@sakumar6 , was this the host network value of istio? I am getting the same error as you

**Comment by apryiomka** [comment]
What is the solution, i am having the same problem. I did set `hostNetwork: true` in the deployment, but it didn't help

**Comment by apryiomka** [comment]
@sakumar6 , how do you set hostNetwork value? I am running in EKS and having exactly the same problem. The istiod is in a ready state though, but the log is filled wit the same error.

**Comment by hanxiaop** [comment]
The log indicates the webhook is not ready since it cannot get the expected response. There should be something blocking the traffic like firewalls. Also, check if there are any useful logs from the api-server.

**Comment by dzamoyoni** [comment]
@hanxiaop am getting the same error. On the api-server am getting this error: 'Failed calling webhook, failing open rev.validation.istio.io: failed calling webhook "rev.validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": Service Unavailable'.

**Comment by duckboy81** [comment]
> In my case, my cluster was managed by Terraform, using the AWS EKS Blueprints module. From previous versions of this module, it included default security group rules to allow all node-to-node communication. This changed in recent versions, and required explicit extension of the default minimum rules.
> 
> This caused my pods, using the VPC-CNI plugin, to not be able to connect to `15017` on the Istiod pod. This was solved by adding an explicit entry to allow all node-to-node communication. Alternatively, you could open just the one port as well.

If you manually create a cluster and node group, EKS will just create security groups with open node-to-node communication. Therefore, you could consider modifying your EKS module in terraform to just let EKS handle security group creation:

```
  # Let AWS set the default security group
  create_cluster_security_group = false
  create_node_security_group = false
```

**Comment by jameswu1991** [comment]
anyone else coming across this thread trying to get this working on eks with terraform, you might find this example helpful

https://github.com/aws-samples/istio-on-eks/blob/main/terraform-blueprint/ambient/main.tf#L86-L103

**Comment by itsmenewbie03** [comment]
To a future poor lost soul like I am now, if you're on EKS you can do the command

1. Get Source Group
```sh
aws eks describe-cluster --name <your-cluster-name> --query "cluster.resourcesVpcConfig.clusterSecurityGroupId" --output text
```
2. Get Group ID
```sh
aws ec2 describe-instances \
  --filters "Name=tag:eks:cluster-name,Values=<your-cluster-name>" \
  --query "Reservations[*].Instances[*].SecurityGroups[*].GroupId" \
  --output text
```
3. Allow Port 15017
```sh
aws ec2 authorize-security-group-ingress \
  --group-id <your-worker-node-sg> \
  --protocol tcp \
  --port 15017 \
  --source-group <your-cluster-sg> 
```
4. Allow Port 15012
```sh
aws ec2 authorize-security-group-ingress \
  --group-id <your-worker-node-sg> \
  --protocol tcp \
  --port 15012 \
  --source-group <your-cluster-sg>
```

**Comment by rklhui** [comment]
I am not running istio on EKS. I faced the same problem, but after I updated the security group of the k8s master to allow 15017 **egress** with the k8s subnets as destination, it finally works.
