### ISSUE TITLE
circuit_breakers stats not working

### ISSUE THREAD

**Issue by RicHincapie** [istio/istio#46075]
Hi.
Using Istio 1.17.2 with Kubernetes 1.24 I have activated circuit_breakers [stats](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#circuit-breakers-statistics) at Istio cm in istio system with: 
```
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*circuit_breakers.*"
```
Then followed the official [tutorial](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/) to open the circuit. While `outlier_detection` stats work well, I was not able to make the `circuit_breakers` stats to indicate anything. It stays at 0 all the time, indicating the circuit is closed.

**Outlier stats (see panel title for query)**
![Screenshot from 2023-07-13 17-58-56](https://github.com/istio/istio.io/assets/56096791/3bd67109-e322-4051-86fa-ecc7b24b3dca)

**Circuit breaker stats**
![Screenshot from 2023-07-13 17-59-07](https://github.com/istio/istio.io/assets/56096791/ef6a9477-4470-4d0b-b545-f02025fb641a)

I thought it may be because the tutorial creates the failures through connection pool settings, so I implemented a small failing microservice that returns 500 for 70% of requests. Although the result is the following:
```
Sockets used: 10000 (for perfect keepalive, would be 10)
Uniform: false, Jitter: false, Catchup allowed: true
IP addresses distribution:
10.96.175.254:8000: 10000
Code 503 : 10000 (100.0 %)
Response Header Sizes : count 10000 avg 0 +/- 0 min 0 max 0 sum 0
``` 
*Notice the buggy microservice's responses are 500, not 503 as in fortio's summary*

The circuit_breaking stats remain stale while the outlier_detection ones still work:
![Screenshot from 2023-07-18 14-49-29](https://github.com/istio/istio.io/assets/56096791/e96b0567-16f4-4749-bde2-12e7aef2a184)

![Screenshot from 2023-07-18 14-46-35](https://github.com/istio/istio.io/assets/56096791/d6751a68-a487-45cf-bba6-20f3a438c86b)

Not sure how to get this metrics to work or if it is some bug.

**Comment by hzxuzhonghu** [comment]
cc @zirain

**Comment by zirain** [comment]
did you try this: https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking

**Comment by RicHincapie** [comment]
Hi, sure. It is the base of my exercise.
In the case you referenced, only upstream_rq_pending_overflow in the CB
stats has responded, which does not indicates the CB is open, but the
"Number of remaining pending requests until the circuit breaker reaches its
concurrency limit".
No circuit_breaking stat respondes as if the CB is open, and the examples
states it should stay open for 3 minutes.

**Comment by zirain** [comment]
I konw little about circuit breaking, for me the mechanism works good, maybe you can look for help in envoy's repo.
