### ISSUE TITLE
How to handle EKS gateway External Endpoint to get static IP for cross cluster communication

### ISSUE THREAD

**Issue by apurvisri** [istio/istio#46079]
Hi everyone!
During istio mesh setup when we use AWS cloud provider, we are getting ELB as endpoint for gateway services. Issue is ELB is not having constant IPs as its a classic Load Balancer to be shared among different clusters or cloud providers  outbound rule for cross cluster communication to happen.
So how we can achieve constant connection of EKS with different clusters with ELB as external endpoint, or to get a static IP for EKS also that can be shared to outbound rule of other cloud providers.

**Comment by howardjohn** [comment]
I believe in AWS usually there is a hostname instead of IP that is stable?
