### ISSUE TITLE
Istio CDS cache -- false cache hits with multiple gateway proxies

### ISSUE THREAD

**Issue by saiskee** [istio/istio#46081]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

the [CDS cache](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster_cache.go#L36) currently does not take into account the proxy ID that cached clusters have been translated for. This is an issue, because different proxies may require different config per cluster, for example for a gateway proxy to Ambient mesh, clusters in CDS may require a hbone transport socket match, while another gateway proxy may not require this. 
An invalid cache hit in this case would serve up the wrong translated cluster.

### Version

```Text
istioctl version
client version: 1.19.0-alpha.1
control plane version: 1.19-dev
data plane version: 1.19-alpha.2f6945a0f14980ddf5b3d0d7ec34bbfa911ffca2 (10 proxies)

kubectl version --short
Client Version: v1.26.5
Kustomize Version: v4.5.7
Server Version: v1.26.4
```

### Additional Information

Proposed solutions: 
- Including the proxy ID in the CDS cluster cache, or including a `hboneEnabled`field. The latter would prevent cache bloat.

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Not including the ID is intentionally - the cache is basically useless if we do that. But we should add others as needed.

I thought we disabled the cache for ambient.. maybe I am mistaken

**Comment by hzxuzhonghu** [comment]
You are right, we donot enable cache for ambient/hbone

**Comment by hzxuzhonghu** [comment]
This is a good incent, but too early  to consider cache for ambient

**Comment by kdorosh** [comment]
we ran into this debugging an ambient installation of istio; i think it is on by default AFAICT:

https://github.com/istio/istio/blob/b3ee7139ff94db5f4e7f05f3493f191e1e19e06c/pilot/pkg/networking/core/v1alpha3/cluster.go#L369-L371

we reproduced this on latest istio as well as versions older than https://github.com/istio/istio/pull/45811, so while that might appear related i don't think it is the cause

@saiskee we didn't have a custom override to enable the CDS cache in our installation right? as far as i remember, we installed mostly default ambient

**Comment by kdorosh** [comment]
> Not including the ID is intentionally - the cache is basically useless if we do that. But we should add others as needed.

my idea was to just include `ambient.enabled` in the cache key for all existing xds caches

**Comment by stevenctl** [comment]
The only thing I see that disables caching for ambient is for EDS cache

https://github.com/istio/istio/blob/42d94a074f1c64ba849ed333588d42e39e1de9d2/pilot/pkg/xds/endpoint_builder.go#L313-L318

It should be enough to include the proxies "hbone enabled" in cache keys I think.
