### ISSUE TITLE
Enable Mixer to influence routing decisions

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4611]
Right now, Mixer is always invoked by the server sidecar. This means that Mixer is unable to influence routing decisions.

What I'm imagining is a model where Mixer.Check is invoked by the client proxy. Mixer.Check returns some attributes which are interpreted by the proxy and are made available as inputs to the downstream routing process.

This could get fancier with more effort. If the client is going to call Mixer.Check, then perhaps we can remove the call to Mixer.Check that the server is doing. That is, trust the clients to have done this. Thus, in the same way as Istio distributes routing decisions to clients, we would be distributing auth checks to clients as well. So long as we control all the proxies in the mesh, we're golden.

If the above requires too much trust, we could have Mixer stamp out a voucher of sorts that it returns to the client. The client sidecar can present that voucher to the server sidecar, proving that it has called Mixer for the current request. The server sidecar could verify this voucher locally without calling down to Mixer again.

Anyway, optimizing away the second call to Mixer.Check is just that, an optimization. The important part is to allow Mixer to affect routing.

**Comment by qiwzhang** [comment]
Required MixerFilter changes for this:
1) add/update some HTTP headers from Check.response from mixer
2) clear route table cache to force Envoy to re-calculate route. 

The issue is:  per-route config may mess up.   Initial route is A,  we are using config A from route A to generate attributes and call mixer,  then the route may change to B after calling Mixer,  config B from route B is not used.

**Comment by rshriram** [comment]
I don't think you should force recomputation of the routes.. Instead, you just need the ability to set the upstream cluster for a route. In other words, the mixer chooses the destination for a request, instead of simply adding more headers and allowing the sidecar to choose the route (which leads to the confusion @qiwzhang points out).

Simple use cases could include mixer decoding tokens/cookies, and based on userIDs, it could pick out a backend version (test/non test), premium or non premium, etc. Since we have standardized on the cluster name in pilot ( outbound|portName|subset|hostname ), the mixer can easily generate the cluster names with little effort.

**Comment by costinm** [comment]
Well, we have a new set of names - I don't think they're 'standardized', we
will need to discuss this.
Using standard DNS names for cluster names, or maybe DNS-SD ( which has a
nice scheme _tcp._port.name...)
seem cleaner options.

I'm a bit concerned about the complexity - server validating that the
client called and passed the right attributes
is very tricky. I certainly hope this is post 1.0 :-)

For ingress/gateway - I think it will be very useful to be able to get back
routing or additional info from mixer,
but it's a simpler case, the call is still from the server.

Costin

**Comment by geeknoid** [comment]
Shriram, I worry about the model you recommend since it would lead to an
inconsistent story for the user. Who wins, Mixer-provided destination or
operator-specified routing rules? Can Mixer override any routing rule just
by returning a magic value? This doesn't seem clean.

I would rather leverage the attribute model we've got. It's clean and
composable and puts the operator in full control. We have Mixer return new
attributes to the proxy, and the proxy inserts these into its pipeline.
Routing rules can then match against these attributes. I know routing rules
don't support this yet, but I think we must get to that point soon. We want
to be able to do routing decisions based on JWT decoding and API decoding
too, and those two decoders emit attributes. So you'd end up with something
like:

JWT Decode -> API Decode -> Mixer.Check -> Route Evaluation

Each of the first three steps augment the set of attributes available and
the route evaluation phase can take these into consideration.

**Comment by jon-whit** [comment]
If I'm not mistaken, the topic of this discussion is something that we are currently in need of. We'd like the ability to make an access control decision at the sidecar level that influences if the route to the backend is sent through or not.

Here's our ideal scenario...
1. Store a mapping between users and the roles the user has been granted in an IAM service.
2. Use Mixer to get the permissions associated with the subjects roles at request time. It won't be common for the permissions included in a role to change, so this is a great candidate for second level caching in Mixer.
3. Conditionally route to a service if and only if the subject of the request has the correct permissions to perform the requested actions (GET, PUT, POST, DELETE) on that service path.

The RBAC adapter is a great example of how we may achieve this, but it doesn't quite solve the scenario above.

Thoughts?

**Comment by kyessenov** [comment]
I'm adding routing directive to mixer adapters (post 1.0).

**Comment by kyessenov** [comment]
Not stale.

**Comment by geeknoid** [comment]
@kyessenov Is this functionality totally done? Do we have docs?

**Comment by kyessenov** [comment]
@geeknoid 
Header editing functionality is implemented. There is a developer guide here:
https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide
and reference documentation (https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/) based on the proto declarations.

The issue, however, is about influencing the routing decisions. This has been somewhat controversial. It is possible to influence the routing by editing headers, but that has not been clearly surfaced on purpose. Do we want documentation for the latter?

**Comment by geeknoid** [comment]
OK, I thought we had gone ahead with the route directive support. Given that it's not there, I wouldn't spend any time documenting how to modify headers to affect routing, lets leave that for the reader.

We'll probably revisit this strategy within the V2 context.

**Comment by kyessenov** [comment]
@geeknoid it's there and works in practice. There's been requests for this feature from various parties, so I'd keep the users in the loop in case it goes away (e.g. @theganyo ). I'm fine leaving it in this state until v2.
