### ISSUE TITLE
Allow Mixer to edit request headers

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4613]
We should enable Mixer adapters to produce edits to request headers. This would enable a bunch of API management scenarios which we cannot easily target at the moment.

**Comment by douglas-reid** [comment]
By edits, do we mean strictly insert new headers, or modify/delete existing headers, or both?

**Comment by mandarjog** [comment]
It should be add / remove / update

**Comment by douglas-reid** [comment]
Is this a dup of #2706 ?

**Comment by geeknoid** [comment]
Yep, dup of #2706
