### ISSUE TITLE
Consider adding support for an optional attribute that lets Mixer adapters inspect portions of the request payload

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4614]
A few API management scenarios can be enabled efficiently if we enable Mixer adapters to observe a portion of message payload. For example, looking at the first 100 bytes of each messages.

Imagine we introduce a new attribute (request.payload). If Galley detects that Mixer rules are consuming this attribute, it programs Envoy to generate this attribute and send it down to Mixer. The payload could be set to a fixed amount (100 bytes) or can perhaps be configurable on a per-service basis.

Adapters could receive this attribute, observe the payload, and produce a yay/nay response.

**Comment by douglas-reid** [comment]
@geeknoid what are the considerations for caching in such scenarios?

**Comment by geeknoid** [comment]
If we treat the payload as any other attributes, we'll get normal caching semantics. So if Envoy has already seen the payload, it can answer the check request from cache.

If the payload is highly variable, then it will definitely kill the cache's efficiency. This is why I said "optional" in the title :-). This is a case where Galley will be of value. Based on the actual attributes consumed by Mixer, Galley can program the sidecar to only send the specific necessary attributes automatically, thus improving cachability and reducing the overhead of Check calls.

For simple cases, it should (I think) also be possible to create an in-proxy Lua script to look at the payload there locally. This Mixer adapter is useful when the data needs to be shipped to some backend that has more elaborate requirements.
