### ISSUE TITLE
intermittent latency issue, fix after istiod and istio-ingress pod restart

### ISSUE THREAD

**Issue by Sumit0789** [istio/istio#46186]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

getting latency issues intermittently, fixed after pod istiod and istio-ingress pod restart.

### Version

```Text
istioctl version
client version: 1.17.3
control plane version: 1.18.0

Client Version: v1.24.14
Kustomize Version: v4.5.4
Server Version: v1.24.15-eks-a5565ad

v3.11.0+g472c573
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by Sumit0789** [comment]
<img width="449" alt="Screenshot 2023-07-26 at 2 12 43 PM" src="https://github.com/istio/istio/assets/111736044/46d288dc-0cfc-4d07-a533-fd81b1b109fd">

**Comment by zirain** [comment]
if restart of ingressgateway fixed, most likely cause of huge mount of metrics? can you check that?

**Comment by Sumit0789** [comment]
@zirain how can I check ?

**Comment by zirain** [comment]
`istioctl x es <pod_name> -o prom | grep istio| wc -l`

**Comment by Sumit0789** [comment]
for external gateway

istioctl x es istio-ingressgateway-external-5bd8c4cd68-lxvct -o prom -n istio-system | grep istio| wc -l
2150

for internal gateway

istioctl x es istio-ingressgateway-internal-b556f84fd-57zrk -o prom -n istio-system | grep istio| wc -l
1078

**Comment by zirain** [comment]
these numbers seems ok now, maybe stats isn't the root cause.

**Comment by Sumit0789** [comment]
@zirain  how can be debug further ?
