### ISSUE TITLE
Validationcontroller log spams in the istio pod of external control plane

### ISSUE THREAD

**Issue by qianwens** [istio/istio#46189]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I created an external control plane cluster following this doc https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/

I want to set the config cluster in the external control plane cluster so I updated the install file as below:
cat <<EOF > external-istiod.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  profile: empty
  meshConfig:
    rootNamespace: external-istiod
    defaultConfig:
      discoveryAddress: $EXTERNAL_ISTIOD_ADDR:15012
      proxyMetadata:
        XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
        CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
  components:
    pilot:
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.volumes[100]
            value: |-
              name: config-volume
              configMap:
                name: istio
          - path: spec.template.spec.volumes[100]
            value: |-
              name: inject-volume
              configMap:
                name: istio-sidecar-injector
          - path: spec.template.spec.containers[0].volumeMounts[100]
            value: |-
              name: config-volume
              mountPath: /etc/istio/config
          - path: spec.template.spec.containers[0].volumeMounts[100]
            value: |-
              name: inject-volume
              mountPath: /var/lib/istio/inject
        env:
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: EXTERNAL_ISTIOD
          value: "true"
        - name: LOCAL_CLUSTER_SECRET_WATCHER
          value: "true"
  values:
    global:
      caAddress: $EXTERNAL_ISTIOD_ADDR:15012
      istioNamespace: external-istiod
      operatorManageWebhooks: true
      meshID: mesh1
      configValidation: true
      configCluster: true
EOF

After I installed the external control plane with istioctl install -f command, I checked the istio pod log but it is full of validationcontroller log as below, but I cannot figure out what is the problem with the validation controller:
9:30:48.378689ZinfovalidationControllerSuccessfully updated validatingwebhookconfiguration istio-validator-external-istiod (failurePolicy=Fail,resourceVersion=865253)
2023-07-26T09:30:48.378746ZinfovalidationControllervalidatingwebhookconfiguration istio-validator-external-istiod (failurePolicy=Fail, resourceVersion=865253) is up-to-date. No change required.

I created a remote cluster but the istio proxy failed start with error:
replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.external-istiod.svc:443/inject/clus
ter/qw-cluster1/net/network1?timeout=10s": x509: certificate signed by unknown authority

### Version

```Text
1.18.1
1.18.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Have you configued the certs correctly in two clusters? If yes, you may check if the MutatingWebhookConfiguration is correct.

**Comment by hanxiaop** [comment]
> I checked that the cabundle in MutatingWebhookConfiguration is emply so I manually add the cabundle and the pod can start now. The question is why the certs not installed in the remote cluster automatically. 

I think this should relate to the wrong config setup, which leads to the webhook incorrectly updated(miss the caBundle).

>  Besides, I am trying to set the config cluster in the external control plane cluster instead of the remote cluster, I want to know if this can work and is there any tutorial to setup the external control plane cluster with the configcluster enabled in it?

If you do not have the apiserver, how can you store the config? Or IIUC is this the primary remote topology?

**Comment by hanxiaop** [comment]
FYI https://istio.io/latest/docs/setup/install/multicluster/primary-remote/
