### ISSUE TITLE
query from prometheus,  the response_code is not normal, eg: 123941048

### ISSUE THREAD

**Issue by tanshungang** [istio/istio#4618]
here is detail information from prometheus:
request_count{destination_service="productpage.istio-test.svc.cluster.local",destination_version="v3",instance="172.6.19.207:42422",istio="mixer",job="kubernetes-service-endpoints",kubernetes_name="istio-mixer",kubernetes_namespace="istio-system",response_code="123941048",source_service="productpage.istio-test.svc.cluster.local",source_version="v3"}

and you see, the destination_service is same with source_service, and the response_code="123941048" is not normal. why ?

PS:   my istio version is 0.4.0

**Comment by douglas-reid** [comment]
@tanshungang I believe this issue has been addressed in subsequent versions of Istio. There was a small regression in the proxy filter code that was providing uninitialized values for response codes on occasion. I highly suggest upgrading to a more recent release of Istio to avoid experiencing the issue.

One small difference you may notice immediately is that `request_count` is now `istio_request_count`.
