### ISSUE TITLE
AWS Network Load Balancer annotations for target type "IP" for Istio Service Mesh Setup

### ISSUE THREAD

**Issue by apurvisri** [istio/istio#46221]
Hello,

I am using a network load balancer in the Istio Service Mesh setup in the EKS cluster. I want to use the target type "IP".

I am referring to the below AWS document for the same reason and the below annotations referred to in the document, but it's not generating any type of load balancer and leaving the service's external IP status as "Pending".

https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html

annotations:-

service.beta.kubernetes.io/aws-load-balancer-type: "external"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"

Also, from one of the old Istio blogs: - https://istio.io/v1.14/blog/2018/aws-nlb/

I was using the below annotation, but it is always giving me NLB as target type "Instance":

service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

Please suggest what annotations should be used to get a network loadbalancer with target type "IP" for the AWS cloud provider for the Istio service mesh setup.

**Comment by hzxuzhonghu** [comment]
You may ask AWS for support to get quick response

**Comment by pseudonator** [comment]
Definitely not an Istio related question but these annotations do work if you have configured the out of tree controller.
