### ISSUE TITLE
istio cni with standalone mode causes sidecar pods eviction

### ISSUE THREAD

**Issue by noah8713** [istio/istio#46234]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
While running istio cni is standalone mode with istio 1.17, we see  pods with istio injection namespaces being evicted when node is rebooted. 

**Describe alternatives you've considered**
Part of https://github.com/istio/istio/pull/33944 since  cni pod doesnt run with `hostnetwork=true`, it is expected k8s/kubelet will treat it as a regular less privileged pod. This causes it to run in any random order. As a result sidecar pods if they come up before cni pods will be evicted as an expected behavior https://istio.io/latest/docs/setup/additional-setup/cni/#race-condition--mitigation . However mass reboots of system during operating system upgrades, etc on the nodes will cause too many pods to evict which will cause user experience degradation. This also causes too much churn rate and load on k8s and istio control plane and evicted pods will be rescheduled and needs to be recreated/rescheduled. 

Is there any better suggestion apart from re-running ds with `hostnetwork=true` which will ensure istio-cni pod is always started before application pods ?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

istio version: 1.17.2
k8s version v1.18.8-438

**Comment by noah8713** [comment]
cc @bianpengyuan @howardjohn

**Comment by hzxuzhonghu** [comment]
I think we set ` priorityClassName: system-node-critical` for istio-cni

**Comment by minghuiyuan** [comment]
For some cases, priorityClassName is the happening when the pods' scheduling. For this case, the node's restarting  or other actions which make node's restarting, the pods are not recheduling in short time(<15mins). 

The startup order may be the key to solve such issues. If there is one feature can config the pods start order in one node by kubelet, it will solve such cases.

**Comment by howardjohn** [comment]
> Part of https://github.com/istio/istio/pull/33944 since cni pod doesnt run with hostnetwork=true, it is expected k8s/kubelet will treat it as a regular less privileged pod.

I don't think hostNetwork == run first? Or does it?

**Comment by hzxuzhonghu** [comment]
Why not file a issue to kubernetes to support startup pods obeying the priority orders

**Comment by noah8713** [comment]
> don't think hostNetwork == run first? Or does it?

There is no specific code ref in k8s for ensuring this will be first. Its just reduces the chances in general that it goes into running state faster compared to other pod which has multiple containers and images to download.

**Comment by howardjohn** [comment]
I am not sure why hostnetwork would make a pod start faster. It still has
to download images

**Comment by noah8713** [comment]
>I am not sure why hostnetwork would make a pod start faster. It still has
to download images

Overall doesnt need to get ip/route address from any centralized system and saves some network configs to avoid making it slow and can go into ready state faster.

**Comment by noah8713** [comment]
>Why not file a issue to kubernetes to support startup pods obeying the priority orders

Yeah need to follow that with k8s to see if priority scheduling can be enabled or supported in general!

**Comment by noah8713** [comment]
For now we have enabled hostnetwork=true for istio-cni for istio 1.17 till upstream k8s priority startup feature is available. and we dont see pod eviction issues any more. Chances of eviction is expected in corner case vs mass eviction.
