### ISSUE TITLE
migrate security policy to v1

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#46259]
Security policy API has graduated in 1.17,  but the istio repo is still using beta API.

**Comment by howardjohn** [comment]
Istio repo is also using networking v1alpha3 :slightly_smiling_face:.

I was just thinking it may be time to put some effort into moving though. Strictly speaking, its less compatible to use the new versions.

Assuming we never remove old versions (which we have never done in Istio history -- in theory you could fork the CRD and remove them, though), users either have `[beta]` or `[beta,v1]`. So 100% support `beta`.

In practice I am not really sure how you are going to get 1.16 CRDs with Istiod 1.19, though, so may be worth moving at this point.

IMO this is not the same as Kubernetes APIs. Kubernetes both removes old versions (so we _have_ to move) and doesn't have the same schema for the different versions (so we may need to move to adopt new features).
