### ISSUE TITLE
e2e pilot failing postsubmit, possible prow issue

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4625]
[example failure from prow](https://storage.googleapis.com/istio-prow/pull/istio_istio/4605/istio-pilot-e2e/5026/build-log.txt)

I have tested this locally and I'm unable to replicate the errors that prow is erroring on.

snippet
```
I0329 15:37:23.404] 2018-03-29T15:37:23.400690Z	error	missing pod names for app "d"
I0329 15:37:23.404] 2018-03-29T15:37:23.400693Z	error	missing pod names for app "d"
I0329 15:37:23.404] 2018-03-29T15:37:23.400697Z	info	Istio RBAC: request for {dst:b src:a path:/ expect:200} (attempt 89)
I0329 15:37:23.404] 2018-03-29T15:37:23.400701Z	error	missing pod names for app "a"
I0329 15:37:23.404] 2018-03-29T15:37:23.400728Z	info	Istio RBAC: request for {dst:b src:d path:/ expect:200} (attempt 89)
I0329 15:37:23.404] 2018-03-29T15:37:23.400734Z	error	missing pod names for app "d"
I0329 15:37:23.404] 2018-03-29T15:37:23.400740Z	info	Istio RBAC: request for {dst:d src:b path:/ expect:200} (attempt 89)
I0329 15:37:23.404] 2018-03-29T15:37:23.400745Z	error	missing pod names for app "b"
I0329 15:37:23.404] 2018-03-29T15:37:23.400751Z	info	Istio RBAC: request for {dst:d src:c path:/ expect:200} (attempt 89)
I0329 15:37:23.404] 2018-03-29T15:37:23.400754Z	error	missing pod names for app "c"
I0329 15:37:23.404] 2018-03-29T15:37:23.400760Z	info	Istio RBAC: request for {dst:a src:b path:/xyz expect:403} (attempt 89)
I0329 15:37:23.405] 2018-03-29T15:37:23.400766Z	error	missing pod names for app "b"
```

**Comment by hklai** [comment]
It seems to have started failing for all PRs in the last few days.
https://prow.istio.io/?job=istio-pilot-e2e

And it does not run in postsubmit so it's harder to figure out the culprit. 

@sebastienvas  could you take a look?

**Comment by cmluciano** [comment]
Possibly related https://github.com/istio/istio/pull/4466

**Comment by cmluciano** [comment]
I missed that part @sebastienvas . I wonder if locally it does not use the injector?

**Comment by sebastienvas** [comment]
@yusuoh the sidecar is crashing when running the pilot e2e on a 1.9 gke cluster. Can you try to reproduce it and root cause ?

**Comment by yusuoh** [comment]
We need to make some change in pilot_test.go to handle sidecar injection when the option is enabled. I will take a look.

**Comment by yusuoh** [comment]
#4650

**Comment by cmluciano** [comment]
Fixed by https://github.com/istio/istio/pull/4650
