### ISSUE TITLE
Ambient Mode - Can docker swarm support be revisited now?

### ISSUE THREAD

**Issue by dazinator** [istio/istio#46280]
**Describe the feature request**

Some work was done a while ago https://github.com/istio/istio/issues/7777

Swarm is very much lacking good mTLS solutions, the main blocker for getting things like `Istio` running on swarm in the past has been swarm's lack of support for sidecar containers / pods.

However given the new [ambient](https://istio.io/v1.15/blog/2022/introducing-ambient-mesh/) mode, a side car is no longer used.
Instead it looks to me like the "side car" has now just become another "service" in terms of how it could be scheduled and scaled on swarm.

It seems like this should change things. I would love for this to be expolored by someone with the smarts.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
I agree with John, this is not a priority for Istio at the moment. If you have any integration ideas, feel free to share.

**Comment by dazinator** [comment]
I am not an expert either and I sense there wont be any momentium on this. However just wanted to respond to this:

> ztunnel daemonset node component to capture all the traffic

Swarm has the concep of `global` services, which I think mirrors the K8's concept of a daemonset - i.e a service that will be placed on every node including any new nodes that you add (with optional placement constraints).

If that was some sort of Istio proxy, then it seems to me that given it would be running on each node, it should be addressable somehow. Some ideas:

1. Istio proxy deployed as a global service, publishes a port on the host. Swarm services that need to send traffic through istio can therefore, instead of directly addressing the other service via its name on the swarm overlay network, address the Istio proxy using `host.docker.internal:[ISTIO PORT]`.
2. I am not great at networking but it seems to me like you'd want to avoid the above publishing of a port. So another idea is this:

  - Deploy Istio as a `global` swarm service, with a `local` docker network called `Istio`. This means each node would have it's own docker network called `Istio-Local`.
  - Swarm services that need to send traffic through Istio, can add the `external` docker network named `Istio-Local` to their compose files, allowing them to see the Istio proxy service local to the node they are running on. They can then send traffic to the Istio service proxy instead of straight to the target service.
