### ISSUE TITLE
kind ingress seems not working

### ISSUE THREAD

**Issue by gigi206** [istio/istio#46281]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have installed istio with ArgoCD (helm charts) whith charts: base, istiod in namespace istio-system
And the chart gateway in namespace istio-ingress

I follow the documentation: https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/
And create the 2 resources:
```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: istio
  rules:
  - host: httpbin.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 8000
```

```
$ kubectl get ing -n test
NAME    CLASS   HOSTS                       ADDRESS   PORTS   AGE
httpbin   istio        httpbin.example.com                        80      16h

$ kubectl get ingressclasses
NAME    CONTROLLER                    PARAMETERS   AGE
istio        istio.io/ingress-controller      <none>               16h
nginx      k8s.io/ingress-nginx             <none>               5d15h
```

If I use the nginx ingressclass, I obtain an external address.

Note that istio works well with Gateway API CRDs or with istio CRDs but not with the builtin ingress. 

```
$ kubectl get svc,pod -l istio=ingress -A
NAMESPACE       NAME                    TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)                                      AGE
istio-ingress   service/istio-ingress   LoadBalancer   10.43.231.75   192.168.122.204   15021:30591/TCP,80:31052/TCP,443:30297/TCP   2d4h

NAMESPACE       NAME                                 READY   STATUS    RESTARTS   AGE
istio-ingress   pod/istio-ingress-7c9c597ccb-l57lc   1/1     Running   0          4h9m

$ kubectl get no
NAME     STATUS   ROLES                       AGE     VERSION
k8s-m1   Ready    control-plane,etcd,master   5d16h   v1.26.6+rke2r1
```

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (9 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.6+rke2r1
Kustomize Version: v4.5.7
Server Version: v1.26.6+rke2r1

$ helm version --short
v3.12.2+g1e210a2
```

### Additional Information

$ istioctl bug-report

Target cluster context: default

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-08-02 13:30:23.629776049 +0000 UTC

Cluster endpoint: https://127.0.0.1:6443
CLI version:
version.BuildInfo{Version:"1.18.2", GitRevision:"0183f2886bc078e8df4d6bbd21fa452a3a23481d", GolangVersion:"go1.20.6", BuildStatus:"Clean", GitTag:"1.18.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.18.2", GitRevision:"0183f2886bc078e8df4d6bbd21fa452a3a23481d", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.18.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.18.2}

Fetching proxy logs for the following containers:

argo-cd/argo-cd-argocd-applicationset-controller/argo-cd-argocd-applicationset-controller-6779b67c4f-dxjrc/applicationset-controller
argo-cd/argo-cd-argocd-dex-server/argo-cd-argocd-dex-server-6dbc49444b-j9ts4/dex-server
argo-cd/argo-cd-argocd-notifications-controller/argo-cd-argocd-notifications-controller-6cc89bf787-xbv7c/notifications-controller
argo-cd/argo-cd-argocd-redis/argo-cd-argocd-redis-6d886b4d7-wp9dh/redis
argo-cd/argo-cd-argocd-repo-server/argo-cd-argocd-repo-server-86d679b8bb-wwghl/repo-server
argo-cd/argo-cd-argocd-server/argo-cd-argocd-server-6bd76d46fb-9rtp6/server
bookinfo/details-v1/details-v1-7745b6fcf4-ffdwg/details
bookinfo/details-v1/details-v1-7745b6fcf4-ffdwg/istio-proxy
bookinfo/productpage-v1/productpage-v1-6f89b6c557-9ghrg/istio-proxy
bookinfo/productpage-v1/productpage-v1-6f89b6c557-9ghrg/productpage
bookinfo/ratings-v1/ratings-v1-77bdbf89bb-tmsnr/istio-proxy
bookinfo/ratings-v1/ratings-v1-77bdbf89bb-tmsnr/ratings
bookinfo/reviews-v1/reviews-v1-667b5cc65d-xptvp/istio-proxy
bookinfo/reviews-v1/reviews-v1-667b5cc65d-xptvp/reviews
bookinfo/reviews-v2/reviews-v2-6f76498fc8-dgg56/istio-proxy
bookinfo/reviews-v2/reviews-v2-6f76498fc8-dgg56/reviews
bookinfo/reviews-v3/reviews-v3-5d8667cc66-lv246/istio-proxy
bookinfo/reviews-v3/reviews-v3-5d8667cc66-lv246/reviews
cert-manager-system/cert-manager-cainjector/cert-manager-cainjector-79f5dbffcf-nhblj/cert-manager-cainjector
cert-manager-system/cert-manager-webhook/cert-manager-webhook-77b984cc67-c6h9q/cert-manager-webhook
cert-manager-system/cert-manager/cert-manager-54b54d4947-dqsnh/cert-manager-controller
external-dns-system/external-dns/external-dns-5787777cb8-cw8q6/external-dns
ingress-nginx/ingress-nginx-controller/ingress-nginx-controller-b8sfm/controller
istio-cni/istio-cni-node/istio-cni-node-h2mc4/install-cni
istio-ingress/http-gateway-istio/http-gateway-istio-7859857bfb-jp2f5/istio-proxy
istio-ingress/istio-ingress/istio-ingress-7c9c597ccb-l57lc/istio-proxy
istio-system/istiod/istiod-758754dcd5-rrt97/discovery
kubevip-system/kube-vip-ds/kube-vip-ds-4pp69/kube-vip
longhorn-system/csi-attacher/csi-attacher-785fd6545b-bl8dn/csi-attacher
longhorn-system/csi-attacher/csi-attacher-785fd6545b-k7fgr/csi-attacher
longhorn-system/csi-attacher/csi-attacher-785fd6545b-pnccl/csi-attacher
longhorn-system/csi-provisioner/csi-provisioner-8658f9bd9c-7wz6b/csi-provisioner
longhorn-system/csi-provisioner/csi-provisioner-8658f9bd9c-ght7x/csi-provisioner
longhorn-system/csi-provisioner/csi-provisioner-8658f9bd9c-v4l75/csi-provisioner
longhorn-system/csi-resizer/csi-resizer-68c4c75bf5-78wjg/csi-resizer
longhorn-system/csi-resizer/csi-resizer-68c4c75bf5-pjqjh/csi-resizer
longhorn-system/csi-resizer/csi-resizer-68c4c75bf5-wrbsz/csi-resizer
longhorn-system/csi-snapshotter/csi-snapshotter-7c466dd68f-nktdg/csi-snapshotter
longhorn-system/csi-snapshotter/csi-snapshotter-7c466dd68f-tq9sb/csi-snapshotter
longhorn-system/csi-snapshotter/csi-snapshotter-7c466dd68f-v5z28/csi-snapshotter
longhorn-system/engine-image-ei-74783864/engine-image-ei-74783864-88ztj/engine-image-ei-74783864
longhorn-system/longhorn-csi-plugin/longhorn-csi-plugin-4k8ld/longhorn-csi-plugin
longhorn-system/longhorn-csi-plugin/longhorn-csi-plugin-4k8ld/longhorn-liveness-probe
longhorn-system/longhorn-csi-plugin/longhorn-csi-plugin-4k8ld/node-driver-registrar
longhorn-system/longhorn-driver-deployer/longhorn-driver-deployer-8657b87cf9-kl2wc/longhorn-driver-deployer
longhorn-system/longhorn-manager/longhorn-manager-vwbdz/longhorn-manager
longhorn-system/longhorn-ui/longhorn-ui-74966dd455-mzswh/longhorn-ui
longhorn-system/longhorn-ui/longhorn-ui-74966dd455-vt8mx/longhorn-ui
metallb-system/metallb-controller/metallb-controller-58c5997556-ccv5w/controller
metallb-system/metallb-speaker/metallb-speaker-m6p9z/frr
metallb-system/metallb-speaker/metallb-speaker-m6p9z/frr-metrics
metallb-system/metallb-speaker/metallb-speaker-m6p9z/reloader
metallb-system/metallb-speaker/metallb-speaker-m6p9z/speaker
nginx-gateway/nginx-gateway-nginx-kubernetes-gateway/nginx-gateway-nginx-kubernetes-gateway-798d56d69f-kwksc/nginx
nginx-gateway/nginx-gateway-nginx-kubernetes-gateway/nginx-gateway-nginx-kubernetes-gateway-798d56d69f-kwksc/nginx-gateway
powerdns-system/powerdns/powerdns-6b7cb5bccb-w5pcl/powerdns
prometheus-stack/prometheus-stack-grafana/prometheus-stack-grafana-775c9cbf77-thv2g/grafana
prometheus-stack/prometheus-stack-grafana/prometheus-stack-grafana-775c9cbf77-thv2g/grafana-sc-dashboard
prometheus-stack/prometheus-stack-grafana/prometheus-stack-grafana-775c9cbf77-thv2g/grafana-sc-datasources
prometheus-stack/prometheus-stack-kube-prom-operator/prometheus-stack-kube-prom-operator-66758f956d-wbf2k/kube-prometheus-stack
prometheus-stack/prometheus-stack-kube-state-metrics/prometheus-stack-kube-state-metrics-5ccb5d475-qlhrb/kube-state-metrics
prometheus-stack/prometheus-stack-prometheus-node-exporter/prometheus-stack-prometheus-node-exporter-qgrgr/node-exporter
test/httpbin/httpbin-5c5944c58c-d77b5/httpbin
test/httpbin/httpbin-5c5944c58c-d77b5/istio-proxy

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace argo-cd) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argo-cd istio-injection=enabled' to enable it, or 'kubectl label namespace argo-cd istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace cert-manager-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager-system istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace external-dns-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace external-dns-system istio-injection=enabled' to enable it, or 'kubectl label namespace external-dns-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace gateway-api-controller) The namespace is not enabled for Istio injection. Run 'kubectl label namespace gateway-api-controller istio-injection=enabled' to enable it, or 'kubectl label namespace gateway-api-controller istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace ingress-nginx) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ingress-nginx istio-injection=enabled' to enable it, or 'kubectl label namespace ingress-nginx istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-cni) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-cni istio-injection=enabled' to enable it, or 'kubectl label namespace istio-cni istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kubevip-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kubevip-system istio-injection=enabled' to enable it, or 'kubectl label namespace kubevip-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace longhorn-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace longhorn-system istio-injection=enabled' to enable it, or 'kubectl label namespace longhorn-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace metallb-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace metallb-system istio-injection=enabled' to enable it, or 'kubectl label namespace metallb-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace nginx-gateway) The namespace is not enabled for Istio injection. Run 'kubectl label namespace nginx-gateway istio-injection=enabled' to enable it, or 'kubectl label namespace nginx-gateway istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace powerdns-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace powerdns-system istio-injection=enabled' to enable it, or 'kubectl label namespace powerdns-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace prometheus-stack) The namespace is not enabled for Istio injection. Run 'kubectl label namespace prometheus-stack istio-injection=enabled' to enable it, or 'kubectl label namespace prometheus-stack istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service argo-cd/argo-cd-argocd-applicationset-controller) Port name webhook (port: 7000, targetPort: webhook) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/csi-attacher) Port name dummy (port: 12345, targetPort: 12345) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/csi-provisioner) Port name dummy (port: 12345, targetPort: 12345) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/csi-resizer) Port name dummy (port: 12345, targetPort: 12345) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/csi-snapshotter) Port name dummy (port: 12345, targetPort: 12345) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service ingress-nginx/ingress-nginx-controller-metrics) Port name metrics (port: 10254, targetPort: metrics) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service ingress-nginx/ingress-nginx-controller) Port name 22-tcp (port: 22, targetPort: 22-tcp) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/longhorn-admission-webhook) Port name admission-webhook (port: 9502, targetPort: admission-wh) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/longhorn-backend) Port name manager (port: 9500, targetPort: manager) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/longhorn-conversion-webhook) Port name conversion-webhook (port: 9501, targetPort: conversion-wh) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service longhorn-system/longhorn-recovery-backend) Port name recovery-backend (port: 9503, targetPort: recov-backend) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service metallb-system/metallb-webhook-service) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service powerdns-system/powerdns-webserver) Port name  (port: 8081, targetPort: dns-webserver) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus-stack/prometheus-stack-kube-prom-alertmanager) Port name reloader-web (port: 8080, targetPort: reloader-web) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus-stack/prometheus-stack-kube-prom-prometheus) Port name reloader-web (port: 8080, targetPort: reloader-web) doesn't follow the naming convention of Istio port.
Creating an archive at /root/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by makarov-roman** [comment]
It's not working for me either. It seems like istio-gateway do not create listeners based on ingress, but it works with gw+vs, and Ingress even starts working if you create gw+vs for another app inside the cluster which uses the same port. Because it creates listener inside ingress.
I've checked with `lsof -i` inside istio-ingress pod

**Comment by gigi206** [comment]
If I install istio with `istioctl` (operator) it works.
I don't know why it doesn't work if I install with helm (different namespaces).

**Comment by makarov-roman** [comment]
@gigi206 check ingress-gateway name and selector on gw/ingress

**Comment by gigi206** [comment]
After some tests, it seems there are 2 things that are harcodeded and leads that the ingress doesn't work:
* namespace: if the gateway is installed in a different namespace of `istio-system`
* labels: install helm chart without set `labels.istio=ingressgateway`
Could you fix this issue ?

**Comment by gigi206** [comment]
Not fixed

**Comment by gigi206** [comment]
Thank you for your reply:
https://artifacthub.io/packages/helm/istio-official/istiod?modal=values&path=pilot.env
This means adds to `values.yaml` helm file ?:
```yaml
pilot:
  env:
  - K8S_INGRESS_NS: myingress
```

**Comment by AlexDexsoon** [comment]
> Thank you for your reply: https://artifacthub.io/packages/helm/istio-official/istiod?modal=values&path=pilot.env This means adds to `values.yaml` helm file ?:
> 
> ```yaml
> pilot:
>   env:
>   - K8S_INGRESS_NS: myingress
> ```

It's a map, so you don't need "-"

```
pilot:
  env:
    K8S_INGRESS_NS: myingress
```

**Comment by gigi206** [comment]
Thank you @AlexDexsoon, now it works :+1:
