### ISSUE TITLE
istioctl wait for waypoint pod to become Ready

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#46297]
**Describe the feature request**

Should `istioctl x waypoint apply` command wait for the deployment/pod to become ready?  Or perhaps a new `--wait` flag that toggles the feature?  

It seems like most use case for this immediately follow the command with a kubectl wait anyways:
https://github.com/istio/istio/blob/master/tests/integration/ambient/bookinfo_test.go#L314

**Affected product area (please put an X in all that apply)**

[ X ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Comment by hanxiaop** [comment]
I prefer adding a new flag to make it explicitly wait instead of having unexpected delays. Also, the old apply logic without wait is similar to kubectl.

**Comment by hanxiaop** [comment]
I'm wondering that since the generated configs and waypoint controllers are all owned by us, should `wait` be ready when the pod is ready, or the synchronization status should be ready as well?

**Comment by GregHanson** [comment]
@hanxiaop with https://github.com/istio/istio/pull/46500, the waypoint logic is looking to get its address from Gateway object rather than the K8S service.  So I think we should transition away from checking for the pod/deployment

**Comment by hanxiaop** [comment]
> @hanxiaop with #46500, the waypoint logic is looking to get its address from Gateway object rather than the K8S service. So I think we should transition away from checking for the pod/deployment

Thanks for the info, sounds great

**Comment by ilrudie** [comment]
Is this still in scope of the L4 ambient beta being discussed?

**Comment by hanxiaop** [comment]
> Is this still in scope of the L4 ambient beta being discussed? Seems like we can drop that label

I think we can drop the label.
