### ISSUE TITLE
Failed to pull image "auto" for istio-gateway pods

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [istio/istio#46307]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi

I am seeing below error on all the istio gateway pod when installing istio-gateway chart via argocd -

```
Failed to pull image "auto": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/auto:latest": failed to resolve reference "docker.io/library/auto:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

I understand from this [issue](https://github.com/istio/istio/issues/35789) that "auto" is just a placeholder and is replaced by the proxy image and we need to follow correct order to install the charts. So for that I have added sync-wave to all the three charts that I am installing -

chart         wave
base ->         0
istiod ->        1
gateway ->   2 

But this somehow still not solves the problem, can you suggest me how I can fix the dependency problem? There are few options mentioned in the [issue thread](https://github.com/istio/istio/issues/35789#issuecomment-1590255809) I mentioned before, but I am looking for a proper solution from istio team to fix this.

Thanks

### Version

```Text
istioctl version
client version: 1.17.2
control plane version: 1.17.5
data plane version: 1.17.5 (11 proxies)
```

```
istioctl version
client version: 1.17.2
control plane version: 1.17.5
data plane version: 1.17.5 (11 proxies)
```

```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.27.3-eks-a5565ad
```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by sharoncr1** [comment]
I'm facing the same issue. 

I need to use WASM plugin along with Istio. For that I need to enable sidecar injection on Istio gateway running on my `istio-system` namespace. 

For this, I labelled istio-system namespace with `istio-injection=disabled` (I know this sounds counter-intuitive but, https://github.com/istio/istio/issues/7404#issuecomment-808994329)

Then I tried deploying Istio gateway using `helm install istio-ingressgateway istio/gateway -n istio-system`. In this case, gateway pod is not starting up giving the error when described the pod. 

Istio is working totally fine if that namespace doesn't have that label. But I'm won't be able to use WASM plugin then.

**Comment by hanxiaop** [comment]
Have you deployed the gateway after Istiod is ready?

**Comment by hanxiaop** [comment]
Have you deployed the gateway after Istiod is ready?

**Comment by ardenpdev** [comment]
I was seeing the same issue when upgrading from Istio v1.17.2 with AKS version 1.26 to Istio v1.18.5. 

The issue was only with the Istio Gateways, all the labels were correct.

It turns out it was due an improper patch of the ConfigMap for the istio-sidecar-injector which was overriding the data.config. Once fixed, it started appropriately injecting the global.hub and proxyv2 images.

**Comment by cccsss01** [comment]
I'm experiencing this issue as well though the information here isn't quite helping me solve it

**Comment by hanxiaop** [comment]
Looks like the proxy image was not rendered correctly. Do you have any additional settings related to the proxy image, such as image, tag, etc...?

**Comment by hanxiaop** [comment]
See 

https://github.com/istio/istio/blob/ef8bfe6fae1952787e05a7a7080511995d613075/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L90-L94

**Comment by cccsss01** [comment]
Had to set the revision , this resolved it.

**Comment by lhy9816** [comment]
I saw two gateway-related charts in the manifests folders, which are istio/manifests/charts/gateways and istio/manifests/charts/gateway. I was using the second chart because it is recommended by the installation guide. What are the differences between these two charts?
