### ISSUE TITLE
1.17.2 is using envoy from Istio's org

### ISSUE THREAD

**Issue by itsLucario** [istio/istio#46311]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are on the path of upgrading Istio to 1.17.2 and made this observation.

1.17.2 uses envoy from Istio's org but the rest of all past and future versions use envoy from envoy proxy org.
https://github.com/istio/proxy/blob/1.17.2/WORKSPACE#L39-L45

Also, we see the checks have failed for the release
<img width="904" alt="image" src="https://github.com/istio/istio/assets/20811782/692371d0-0a56-4bc6-8938-3e550cc5d0f0">

Another thing that was concerning to us was Istio envoy mentioned that "it's used for testing and dev process" not sure how this got into the release.
<img width="339" alt="image" src="https://github.com/istio/istio/assets/20811782/a0cabf0d-218c-48ee-9c78-986aab260273">

Can someone please clarify if 1.17.2 which contains an envoy from Istio org is stable to use? 

### Version

```Text
Istio 1.17.2
K8s 1.23.17


istioctl version
client version: 1.17.2
control plane version: 1.17-0d1df
data plane version: 1.13-c0e5f3 (1 proxies), 1.17-0d1df (99 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.23.17-eks-a5565ad
WARNING: version difference between client (1.26) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
cc @jacob-delgado

**Comment by ericvn** [comment]
Jacob mentioned above can explain this in more detail, but 1.17.2 is a security release where we built the release privately. After we publish the release, the code used is moved into the public repositories. Since we can't merge the Envoy changes back into Envoy's repos (they do as part of there publish), we put them into istio/envoy so others can recreate the build. You would see similar behavior with our last security release as well.

**Comment by zirain** [comment]
the wrong pr number easily misunderstood

**Comment by itsLucario** [comment]
Alright! That makes sense. Thanks @ericvn 

One more thing. 
- With proxy release 1.17.5 looks like only the SHA bump was done and SHA256 is left out resulting in a checksum fail.
- The SHA doesn't belong with envoyproxy org but belongs to Istio's envoy. (Looks like it needs the org change)

1.17.5 - https://github.com/istio/proxy/tree/1.17.5

**Comment by jacob-delgado** [comment]
1.17 is now EOL with the latest release.
