### ISSUE TITLE
istio-proxy is missing some envoy extensions since 1.18.0

### ISSUE THREAD

**Issue by mhyllander** [istio/istio#46321]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We use the Envoy oauth2 HTTP filter in one of our ingress gateways. The oauth2 configuration is applied using EnvoyFilter. Since 1.18.0, istio-proxy cannot load the listener configuration and logs this error:

```
2023-08-04T09:48:42.435939Z     warning envoy config external/envoy/source/common/config/grpc_subscription_impl.cc:128  gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Didn't find a registered config subscription factory implementation for name: 'envoy.config_subscription.filesystem'
```

### Version

```Text
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (68 proxies)

Client Version: v1.24.10
Kustomize Version: v4.5.4
Server Version: v1.25.6
```

### Additional Information

I think the cause is that some code was moved to extensions between Envoy 1.25.7 (istio 1.17.3) and 1.26.0 (istio 1.18.0). 

https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.26/v1.26.0.html

> build: Moved the REST and filesystem config subscripton code into extensions. If you use them for config updates and override extensions_build_config.bzl you will now need to include them explicitly.

There's a new [section of extensions](https://github.com/envoyproxy/envoy/blob/b1ea06265c05799f4750f577090d2a33d5829fd8/source/extensions/extensions_build_config.bzl#L452-L465) in envoy/source/extensions/extensions_build_config.bzl which is not included in [proxy/bazel/extension_config/extensions_build_config.bzl](https://github.com/istio/proxy/blob/master/bazel/extension_config/extensions_build_config.bzl). Probably extensions_build_config.bzl needs to be reviewed.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
cc @zirain

**Comment by mhyllander** [comment]
I should have linked to https://github.com/istio/proxy/blob/1.18.2/bazel/extension_config/extensions_build_config.bzl (the file in the 1.18 branch). It looks like the missing extensions have been added to the master branch.

**Comment by zirain** [comment]
let me check

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/proxy/pull/4871

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/proxy/pull/4871
