### ISSUE TITLE
Require customer to register external service for JwksURI manually

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4633]
Background: for JWT authentication, envoy needs to talk to external service to fetch public key. In early implementation, pilot implicitly generates the outbound cluster for the JwksURI (https://github.com/istio/istio/pull/4343/files). Intentionally, they have a distinguishable prefix ("jwt."), as oppose to "out." for regular cluster.

This approach simplify customer involvement (they simply needs to config authN policy), but may create duplicates clusters, and not align well with other config external service, destination rule etc.

There are few options to handle this:

1. Instead of adding cluster directly, pilot will inject 'external service' instead, and have clusters generated as regular clusters for external services. From user point of view, they will need to setup policy only.

2. User need to define external service explicitly, in order to make authN policy to work. Customers will need to submit at least two configs: one is authn policy itself, one (or more) for external service for each of the JwksURI, and maybe also destination rule (for TLS setting). We also need to review ACL model to be sure no one can change the external service / destination configs in the way that might the policy enforcement.

3. (depend on other authn policy plan). One plan for authN policy is to have JWT definition in a separate config (CRD), and authN policy simply refers to them. With this structure, external service can/should be registered when changing JWT configs (which should be fairly infrequent), but policy changes don't have to do it. This is a long term change, and might not be feasible before v2 release (anytime now)

4. Others...

**Comment by diemtvu** [comment]
+ @rshriram @louiscryan @qiwzhang @liminw

**Comment by diemtvu** [comment]
@louiscryan, @wenchenglu  Can you give some suggestion which direction we should go? Thanks.

**Comment by wenchenglu** [comment]
seems like option 1 will provide the best user experience. Is it doable in pilot? @louiscryan @costinm

**Comment by diemtvu** [comment]
Another option is having pilot to fetch the public keys (content of the web address pointed by JwksUri) and set that to the jwt filter config. 
This will remove the need to define a outbound clusters for JwksURIs, but add complexity to pilot to fetch (and cache) data from external sources.

**Comment by rshriram** [comment]
The reason I suggested explicitly adding external services was because it offers a lot of benefits: users can define custom certs to talk to these jwks servers, add circuit breakers, etc. also, the APIs offered by these external services (eg googleapis.com) are likely to be used for other things as well, in addition to jwks
