### ISSUE TITLE
istio experimental-dual-stack tcp route bug

### ISSUE THREAD

**Issue by chenbo90** [istio/istio#46346]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

when i use experimental-dual-stack branch code and i apply a gateway and virtualservice. but this is all for tcp route。if i apply this before install istio. istio start is wrong. check log of istiod ，there is wrong log: "**terminal filter named envoy.filters.network.tcp_proxy of type envoy.filters.network.tcp_proxy must be the last filter in a network filter chain**"。and i dont use apply envoyfilter。according to this message ,we could know there is the wrong filter chain order。And i can not find where is the wrong code。

### Version

```Text
we use yaml to apply ,not use istioctl .
kubectl version 
Client Version: v1.23.6
Server Version: v1.23.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
cc @zhlsunshine

**Comment by zhlsunshine** [comment]
Thanks @zirain !
Hi @chenbo90, could you please have a try for master branch instead of the `experimental-dual-stack branch` and let's see the result?

**Comment by chenbo90** [comment]
we use release 1.17.1 branch, in the same enviroment,and open the dual_stack, it is ok。we use nginx to test, apply two service , one is ipv4,and one is [ipv6,ipv4]。we find only nginx service is [ipv6,ipv4],it is wrong. @zhlsunshine 

> Thanks @zirain ! Hi @chenbo90, could you please have a try for master branch instead of the `experimental-dual-stack branch` and let's see the result?

**Comment by zhlsunshine** [comment]
> we use release 1.17.1 branch, in the same enviroment,and open the dual_stack, it is ok。we use nginx to test, apply two service , one is ipv4,and one is [ipv6,ipv4]。we find only nginx service is [ipv6,ipv4],it is wrong. @zhlsunshine
> 
> > Thanks @zirain ! Hi @chenbo90, could you please have a try for master branch instead of the `experimental-dual-stack branch` and let's see the result?

@chenbo90, sorry I do not understand what's wrong with your use case, could you please describe more detail about your use case, including how do you install the Istio and your services?  Thanks!

**Comment by chenbo90** [comment]
> > we use release 1.17.1 branch, in the same enviroment,and open the dual_stack, it is ok。we use nginx to test, apply two service , one is ipv4,and one is [ipv6,ipv4]。we find only nginx service is [ipv6,ipv4],it is wrong. @zhlsunshine
> > > Thanks @zirain ! Hi @chenbo90, could you please have a try for master branch instead of the `experimental-dual-stack branch` and let's see the result?
> 
> @chenbo90, sorry I do not understand what's wrong with your use case, could you please describe more detail about your use case, including how do you install the Istio and your services? Thanks!

step1: we apply a nginx service ,and nginx ipFamilyPolicy is PreferDualStack。
step2: we apply a gateway and virtualservice with tcp route. 
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ttt
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: tcp
      number: 80
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ttt
spec:
  gateways:
  - ttt
  hosts:
  - "*"
  tcp:
  - route:
    - destination:
        host: nginx-dual
        port:
          number: 8000
---

step3: we start to deploy istio。it is failed. 
---
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-58bb5745f4-2m2nx    1/1     Running   0          2d4h
istio-ingressgateway-7655675c76-zl8cc   0/1     Running   0          2d4h
istiod-76b5b96bdb-t9dv4                 1/1     Running   0          2d4h
---

check the ingressgateway log:
---
2023-08-09T05:31:33.822393Z     warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Error: terminal filter named envoy.filters.network.tcp_proxy of type envoy.filters.network.tcp_proxy must be the last filter in a network filter chain.
::_8080: Error: terminal filter named envoy.filters.network.tcp_proxy of type envoy.filters.network.tcp_proxy must be the last filter in a network filter chain.
---

and istiod log is:
---
2023-08-09T05:31:33.822929Z     warn    ads     ADS:LDS: ACK ERROR istio-ingressgateway-7655675c76-zl8cc.istio-system-207 Internal:Error adding/updating listener(s) 0.0.0.0_8080: Error: terminal filter named envoy.filters.network.tcp_proxy of type envoy.filters.network.tcp_proxy must be the last filter in a network filter chain.
::_8080: Error: terminal filter named envoy.filters.network.tcp_proxy of type envoy.filters.network.tcp_proxy must be the last filter in a network filter chain.
---

**Comment by zhlsunshine** [comment]
Hi @chenbo90,  one more question: how did you deploy the Istio? Such as the deployment yaml and deployment command line
