### ISSUE TITLE
ISTIO - tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by lukaszoo** [istio/istio#46350]
Istiod Image: istio/pilot:1.17.1

Hi,
my istiod service try to veryfie certs form keycloak, but failed with following error:
error   model   Failed to fetch public key from "https://keycloak.XXX/auth/realms/stokrotka/protocol/openid-connect/certs": Get "https://keycloak.XXX/auth/realms/stokrotka/protocol/openid-connect/certs": tls: failed to verify certificate: x509: certificate signed by unknown authority

Same configuration on different environment working fine.

Additionally I add cert in configmap: pilot-jwks-extra-cacerts with root cert.

How to check what cert istiod use to verify token?

**Comment by zirain** [comment]
with self-signed certs?

**Comment by lukaszoo** [comment]
yes

**Comment by hzxuzhonghu** [comment]
should be fixed by https://github.com/istio/istio/pull/45746
