### ISSUE TITLE
Ambient mesh compatibility issues with k8s + ipvs

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#46354]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

xref: https://github.com/istio/ztunnel/issues/621

In a k8s cluster with ipvs turned on （(ambient mesh using iptables mode), L7 traffic route control(virtualservice) seems not work. because ipvs converts the request's destination ip to a pod ip in advance.

Detail： The kube-proxy ipvs bind the ClusterIPs to kube-ipvs0 interface. The ClusterIPs will add into local route table which has more priority than ztunnel rules. lead to ClusterIPs traffics cannot hijack to ztunnel .
```shell
0:	from all lookup local <--- ipvs clusterips in local
100: from all fwmark 0x200/0x200 goto 32766
101: from all fwmark 0x100/0x100 lookup 101
102: from all fwmark 0x40/0x40 lookup 102
103: from all lookup 100
```

###  Solution

We can modify the existing matcher_tree rules （main_internal listener)  to perform another route matching based on virtualhost for all HTTP/ gRPC requests. This can solve the compatibility issue with IPVS. If this solution is feasible, I am glad to submit the corresponding code.

### Version

```Text
# ./istioctl version
client version: 1.18.2
control plane version: 1.18-dev
data plane version: 1.18.2 (10 proxies)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by irisdingbj** [comment]
@zengyuxing007 Thanks for submitting the issue and possible fix.  Has ztunnel been skipped totally in IPVS mode?

**Comment by zengyuxing007** [comment]
> 

@irisdingbj  ztunnel not been skipped, the request still goes through ztunnel, but the destination IP of the connect request in HBONE does not match expectations.

I will submit a PR later,  thanks~
