### ISSUE TITLE
istio multi-cluster deployment mode problem

### ISSUE THREAD

**Issue by mark8s** [istio/istio#46353]
Hello everyone, I would like to ask you a question.

I am currently experiencing istio multi-cluster deployment. The document I refer to is: https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

I have done all the steps except not configuring CA for both clusters at the same time.

Then I deployed a HelloWorld service in both clusters, the reference document is: https://istio.io/latest/docs/setup/install/multicluster/verify/

I can also find the endpoint of the helloworld instance in another cluster in any cluster:

as follows:

```shell
$ istioctl pc endpoint helloworld-v2-54df5f84b-2fwc4 -n default | grep hello
10.10.13.112:15443 HEALTHY OK outbound|5000||helloworld.default.svc.cluster.local
10.36.0.2:5000 HEALTHY OK outbound|5000||helloworld.default.svc.cluster.local
```

But when I access helloworld in sleep pod, it cannot access another cluster's instance. why is that?
```
➜ samples kubectl exec -it sleep-78c4d568b7-rq56c sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ $ for i in `seq 20`;do curl -sS helloworld.default:5000/hello;done
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
Hello version: v2, instance: helloworld-v2-54df5f84b-2fwc4
/$
```

Is this a feature of istio itself? That is, the services of another cluster cannot be accessed by default, and the services of the current cluster are given priority?

My istio version is 1.14.6：

```shell
istioctl version
client version: 1.14.6
control plane version: 1.14.6
data plane version: 1.14.6 (3 proxies)
```

**Comment by hzxuzhonghu** [comment]
>Is this a feature of istio itself? That is, the services of another cluster cannot be accessed by default, and the services of the current cluster are given priority?

Do you have outlier detection set for helloworld? If no, then no priority loadbalancing set.

**Comment by abasitt** [comment]
What do you mean by this ?

>  I have done all the steps except not configuring CA for both clusters at the same time.

configuring common CA is mandatory for it to work. https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

**Comment by mark8s** [comment]
@abasitt  ok, let me try

**Comment by mark8s** [comment]
It's my own problem, I don't have root ca configured.
