### ISSUE TITLE
network gateway is racy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46361]
I assume from #46088, maybe older

https://github.com/istio/istio/blob/e85b5e02fa3cbfbea9a031b560b0bf413188afc6/pilot/pkg/model/network.go#L164 lock is not enough, we fetch old GW on L161 and then can set them after if we are calling reload() concurrently.

**Comment by hzxuzhonghu** [comment]
IMO, should be fixed now

**Comment by howardjohn** [comment]
TestMeshNetworking

**Comment by keithmattix** [comment]
Does #46620 fix this?
