### ISSUE TITLE
Update istiod to use targetRef instead of workloadSelector

### ISSUE THREAD

**Issue by MorrisLaw** [istio/istio#46360]
Find where workloadSelector is used (explicitly or implicitly) and add checks for the existence of a targetRef. Defaulting to the current label selector if targetRef doesn't exist for the policy.

Be sure to review and replace any use of workloadSelector with targetRef in the following files:
- [ ] [cluster_waypoint.go](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go)
- [ ] [listener_waypoint.go](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener_waypoint.go)
- [ ] [waypoint.go](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/waypoint.go)
- [ ] [waypoint_test.go](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/waypoint_test.go)

**Comment by whitneygriffith** [comment]
An example of what we are aiming to accomplish is seen in authentication.go where, [getConfigsForWorkload ](https://github.com/istio/istio/blob/master/pilot/pkg/model/authentication.go#L219) helper function is defined and used to get [JWT ](https://github.com/istio/istio/blob/master/pilot/pkg/model/authentication.go#L196) policies

**Comment by keithmattix** [comment]
RBAC (and policy enforcement in general) is a listener concern in Envoy, so you probably won't find examples in cluster code. Look at this line in [listener_waypoint.go](https://github.com/istio/istio/blob/5e5abd2e99a18f0c41c4c44e8198a27756f4115f/pilot/pkg/networking/core/v1alpha3/listener_waypoint.go#L358). If you look into that authZ builder data structure, you'll find a call to [`ListAuthorizationPolicies`](https://github.com/istio/istio/blob/master/pilot/pkg/model/authorization.go#L87) where you see the label matching logic occur

**Comment by whitneygriffith** [comment]
@MorrisLaw you mentioned to default to the current label selector if targetRef doesn't exist for the policy. But, in the [API Docs ](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.8nuwse76cdev) say that _Waypoint proxies will not respect label selectors, even if they match._

Is the not respecting label selectors in scope/still planned? 

If it is, are we defaulting to label selectors to maintain backward compatibility with non Ambient work streams? How can we maintain backward compatibility and still not respect label selectors for Ambient? 

I am thinking: 

```
if targetRef
    apply policy 
else if targetRef does not exist & it's ambient mode 
    skip policy enforcement
else 
    use label selector
```

**Comment by whitneygriffith** [comment]
> @MorrisLaw you mentioned to default to the current label selector if targetRef doesn't exist for the policy. But, the [API Docs ](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.8nuwse76cdev) say _Waypoint proxies will not respect label selectors, even if they match._
> 
> Is the not respecting label selectors in scope/still planned?
> 
> If it is, are we defaulting to label selectors to maintain backward compatibility with non Ambient work streams? How can we maintain backward compatibility and still not respect label selectors for Ambient?
> 
> I am thinking:
> 
> ```
> if targetRef
>     apply policy 
> else if targetRef does not exist & it's ambient mode 
>     skip policy enforcement
> else 
>     use label selector
> ```

For authorization policy, we have decided that if it’s a valid policy missing targetRef in the same or root namespace, we will apply the config. Future work will check for auth policies that are intended for zTunnel and skip applying those configs to the waypoint.

**Comment by keithmattix** [comment]
Closing in favor of #46847 #46846, #46845, #46844
