### ISSUE TITLE
Unable to inject sidecar to Istio-ingressgateway

### ISSUE THREAD

**Issue by sharoncr1** [istio/istio#46385]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying out WASM extension along with Istio.

For this, I need to do Istio sidecar injection to ingress gateway pod. 

For this, I labelled istio-system namespace with `istio-injection=disabled` (I know this sounds counter-intuitive but, https://github.com/istio/istio/issues/7404#issuecomment-808994329). I had already found that ingress gateway deployment's container template already has container level label to enable sidecar injection. So I believe, adding this label to namespace and installing ingress gateway should do what I need.

Then I tried deploying Istio gateway using `helm install istio-ingressgateway istio/gateway -n istio-system` (Istio base and istiod charts are already deployed and working fine). In this case, gateway pod is not starting up giving the following error when described the pod  : 

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m48s                   default-scheduler  Successfully assigned istio-system/istio-ingressgateway-778d69499b-zpgdc to ip-10-0-102-161.ec2.internal
  Normal   Pulling    7m26s (x4 over 8m47s)   kubelet            Pulling image "auto"
  Warning  Failed     7m26s (x4 over 8m47s)   kubelet            Failed to pull image "auto": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/auto:latest": failed to resolve reference "docker.io/library/auto:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     7m26s (x4 over 8m47s)   kubelet            Error: ErrImagePull
  Warning  Failed     7m2s (x6 over 8m46s)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m38s (x21 over 8m46s)  kubelet            Back-off pulling image "auto"
```

Istio ingress gateway is working totally fine if that namespace doesn't have that label. But the sidecar won't be running alongside the gateway container. 

### Version

```Text
➜  ~ istioctl version
client version: 1.10.6
control plane version: 1.18.0

➜  ~ kubectl version --short
Client Version: v1.24.0
Server Version: v1.27.3-eks-a5565ad

➜  ~ helm version --short
v3.10.3+g835b733
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
This is the expected behavior since you did `istio-injection=disabled`. If you disable the namespace injection explicitly, the injection won't occur. However if you didn't set the namespace injection label, the injection will occur. It's mentioned in https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#deploying-an-app

**Comment by sharoncr1** [comment]
@hanxiaop Injection won't occur if `istio-injection` label is absent  on the namespace and it's present and enabled on the container spec. 

You can simply try this by creating `istio-system` namespace without any label and deploying Istio and gateways using helm to that namespace. You can see `sidecar.istio.io/inject: "true"` on gateway deployment template spec. However, istio-sidecar won't be injected in the gateway pod. 

As per https://github.com/istio/istio/issues/7404#issuecomment-808994329, we need to both to selectively enable sidecars on specific pods. 

I think Istio's mutating webhook is trying to inject the sidecar in my setup, but giving issues due to `auto` image being literally  handled by kubernetes.

You can easily reproduce this issue using following steps : 
1. Create namespace `istio-system`. Label it with `kubectl label namespace istio-system istio-injection=disabled`
2. Deploy istio-base helm charts to that namespace
3. Deploy istiod helm chart to that namespace
4. Deploy istio gateway helm chart to that namespace

Now check if gateway pod is coming up.

**Comment by sharoncr1** [comment]
@hanxiaop 

Just now I noticed that Istio sidecar and Istio ingress gateway shares the same image. 

I was just looking at the number of containers in the pod to verify if sidecar has been injected.

Does that mean Istio ingressgateway won't have two containers in it even if the injection is working fine?

**Comment by hanxiaop** [comment]
@sharoncr1 Gateway injection uses a different template from sidecar injection. See https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml

**Comment by sharoncr1** [comment]
Thanks @hanxiaop My goal is anyway working now and I'm closing this ticket. 

However I believe this issue still exists. Having `istio-injection=disabled` label on `istio-system` namespace can break gateway pod when installed using Helm.

**Comment by janekmichalik** [comment]
@sharoncr1 were you able to inject the sidecar or not?
