### ISSUE TITLE
 Is it normal that clusterLoadAssignment.endpoints info is nil when calling eds of istiod-service ？

### ISSUE THREAD

**Issue by supercharge-xsy** [istio/istio#46382]
firstly version info
```
istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (10 proxies),  (1 proxies)
```

 I'm having a problem when subscribe to the xds configuration from istiod, I found that the eds information of istiod-svc is different from other services. This is the eds-resource push information I received in my log:

```
for istiod:
[type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment]:{cluster_name:\"outbound|15012||istiod.istio-system.svc.cluster.local\"}

other svc：
[type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment]:{cluster_name:\"outbound|9080|v3|reviews.default.svc.cluster.local\" endpoints:{locality:{} lb_endpoints:{endpoint:{address:{socket_address:{address:\"192.168.11.250\" port_value:9080}}} health_status:HEALTHY metadata:{filter_metadata:{key:\"envoy.transport_socket_match\" value:{fields:{key:\"tlsMode\" value:{string_value:\"istio\"}}}} filter_metadata:{key:\"istio\" value:{fields:{key:\"workload\" value:{string_value:\"reviews-v3;default;reviews;v3;Kubernetes\"}}}}} load_balancing_weight:{value:1}} load_balancing_weight:{value:1}}}

```
The difference is that the EDS information of other services contains the endpoints field, but istiod-svc does not. 
is this normal?

**Comment by howardjohn** [comment]
Probably it has 0 endpoints in kubernetes? you can check with `kubectl get endpoints`

**Comment by supercharge-xsy** [comment]
@howardjohn 
There are endpoints in the environment.

[root@k8s-control ~]# kubectl get svc -n istio-system
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
istiod                 ClusterIP      10.96.33.115    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        

[root@k8s-control ~]# kubectl get endpoints -n istio-system
NAME                   ENDPOINTS                                                                    AGE
istiod                 192.168.11.223:15012,192.168.11.223:15010,192.168.11.223:15017 + 1 more...   280d
