### ISSUE TITLE
Update on conformance testing

### ISSUE THREAD

**Issue by zachmandeville** [istio/istio#46383]
I am curious if there is a status update on a conformance test suite for istio, similar to the K8s conformance project.
I saw there are previous, closed issues related to conformance(#14887), but the conformance tests were removed(https://github.com/istio/istio/pull/23541).   I am interested to see if tools built for  k8s conformance([apisnoop](https://apisnoop.cncf.io)) could be extended to help with Istio's test suites.

**Comment by howardjohn** [comment]
There hasn't been any movement since 2019 until a few weeks ago where it was brought up again. There is no current decision on what will happen there, though
