### ISSUE TITLE
Update release-1.17 to latest client-go v0.26.x

### ISSUE THREAD

**Issue by liggitt** [istio/istio#46396]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases shows 1.17.x is still supported

https://github.com/istio/istio/blob/release-1.17/go.mod#L97 still uses client-go v0.26.0

`k8s.io/client-go` [v0.26.0, v0.26.3) was impacted by a regression in discovery client behavior. See https://github.com/kubernetes/kubernetes/issues/118361#issuecomment-1579198407 for details

Please update the release-1.17 branch to the latest k8s.io/client-go v0.26.x tag to ensure the discovery client works properly

### Version

```Text
n/a
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by liggitt** [comment]
cc @apelisse @seans3

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio/pull/46397 so closing.
