### ISSUE TITLE
Why does istio need to use SPIRE?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#46409]
Hi everyone, I have a question. My question is just like the title, why does istio need to use SPIRE?

(1) What benefits does SPIRE bring to Istio? When should it be used?

(2) Have you used SPIRE in the production environment? What is the deployment architecture like? I feel more intrusive and feel that it will cause some chain problems.

(3) Must SPIRE be used in multi-cluster and multi-grid? For more safety and convenience?

Hope someone can help me answer.

**Comment by howardjohn** [comment]
Istio does not need SPIRE, and most Istio users do not use SPIRE. You _can_ use it with Istio, but I have not done so so I cannot answer much beyond that.

**Comment by mark8s** [comment]
@howardjohn tks~
