### ISSUE TITLE
with multiple pods up and running in ingressgateway replicas, only 1 pod is really serving the request? 

### ISSUE THREAD

**Issue by liyong-li** [istio/istio#46416]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

with multiple pods up and running in ingressgateway replicas, only 1 pod is really serving the request? 
We defined 5 pods in istio-ingressgateway deployment, and they are all up and running, but seems like only 1 pod is really serving the inbound requests. 

### Version

```Text
release: istio
    app.kubernetes.io/version: 2.3.2-1-4
    app.kubernetes.io/component: istio-ingress
    maistra-version: 2.3.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by liyong-li** [comment]
is it because the requests will be only routed to 2nd ingressgateway if 1st replica reach cpu% 80%?

**Comment by howardjohn** [comment]
Getting traffic _to_ the ingressgateway is outside of Istio's scope. Typically this is the k8s cloud provider that handles the LoadBalancer service. Depending on what they do, and what your clients do may impact this.

For example, a typical implementation will just do a L3 proxy. if a client opens a single connection and sends lots of requests on it, those wil all go to the same Isiot-ingress

**Comment by liyong-li** [comment]
added annotations to the route definition, problem is resolved now.
