### ISSUE TITLE
Difference in load distribution between gateway and an in-cluster pod

### ISSUE THREAD

**Issue by kpharasi** [istio/istio#46427]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are seeing a difference in the load distribution across the replicas associated with a deployment when the calls are made from a Pod inside the same cluster as compared to the ingress gateway. 

Note:
- The ingress gateway is running in `AUTO_PASSTHROUGH` mode
- The load-balancing strategy in the destination rule for the destination service is set to `LEAST_REQUEST`

**Calls to the destination service through the gateway:**

<img width="1506" alt="image" src="https://github.com/istio/istio/assets/14312926/fad74c1a-0d5b-4970-8984-2e4c5d73c65c">

**Calls to the destination service from a pod inside the cluster:**

![image](https://github.com/istio/istio/assets/14312926/ec259402-7937-4e6d-a397-baad944c183c)

### Version

```Text
Kubernetes: v1.23

Istio: v1.17
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
auto_passthrough is tcp level load balancing not http so this is not particularly unexpected

**Comment by kpharasi** [comment]
@howardjohn Got it. Thanks for the quick response.

- Is there a way of achieving a more even load distribution using the `AUTO_PASSTHROUGH` mode? 
- If not, what would be the recommendation if we want to achieve a better load distribution? Use something other than the passthrough mode?

**Comment by nirvanagit** [comment]
Hi @howardjohn, thanks for the quick response. Had a follow up - is there any configuration we can do to have a good balance with AUTO_PASSTHROUGH / PASSTHROUGH?

**Comment by howardjohn** [comment]
Not really, it is fundamental to how multinetwork works

**Comment by nirvanagit** [comment]
Does it help to tune the tcp connection params like max connection duration?
