### ISSUE TITLE
make dns ttl  configurable

### ISSUE THREAD

**Issue by rokkiter** [istio/istio#46449]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

DNS TTL is used to cache records in DNS. It does not have a value suitable for all usage scenarios. The current situation is that its default value is 30s and cannot be modified by users. I think there is value in making it configurable

https://github.com/istio/istio/blob/2ef6d79ee993039721e5f151b4250016da26ca0e/pkg/dns/client/dns.go#L86

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
What is the value in configuration here

**Comment by rokkiter** [comment]
I'm very sorry, my description in the issue may be misleading, the value is defaultTTLInSeconds that be set in const, the relevant code is posted in the description, I think defaultTTLInSeconds can be exposed for users to configure, and we can Set a default value if not configured by the user

**Comment by rokkiter** [comment]
As mentioned in the description, different cache time requirements for dns may be different. Some users may have a lot of pressure on the dns server and want a longer TTL time. Some users do not have the pressure on the dns server but want the application to be more secure higher accuracy, they would expect a shorter TTL time.

**Comment by rokkiter** [comment]
Secondly, I did not search for information about defaultTTLInSeconds in the documentation, and users cannot know that default ttl is in isito unless they pass through the source code

**Comment by howardjohn** [comment]
> As mentioned in the description, different cache time requirements for dns may be different. Some users may have a lot of pressure on the dns server and want a longer TTL time. Some users do not have the pressure on the dns server but want the application to be more secure higher accuracy, they would expect a shorter TTL time.

The TTL time is not for requests to the upstream DNS server, but to the local agent DNS server. I don't see a use case for that being customized. I don't think the local agent server, which serves a single pod, is going to be overwhelmed.
