### ISSUE TITLE
Istio errors in AWS eks when aws multus cni is used.

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#46451]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Environment : AWS EKS.

IN our environment we are using aws multus cni and our pods have multiple ip addressed.
But when istio is enabled pods remain in init 0/2 status.  If i disable istio then pods do come up and multiple nics get attached.

Pod status
========

ss7fep0-0                                                         0/2     Init:0/1           0                61m

Pod describe shows this 
==================
`
Normal   AddedInterface          2m8s                   multus             Add eth0 [16.0.1.41/32] from aws-cni
 Normal   AddedInterface          2m7s                   multus             Add eth0 [16.0.3.155/32] from aws-cni
 Normal   AddedInterface          2m6s                   multus             Add eth0 [16.0.2.242/32] from aws-cni
 Normal   AddedInterface          2m5s                   multus             Add eth0 [16.0.3.95/32] from aws-cni
 Warning  FailedCreatePodSandBox  110s (x2071 over 51m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4292f2321caaf689b54dcc5b90250d20026864fc9c3e08754fa1cbbf4403db02": plugin type="istio-cni" name="istio-cni" failed (add): netplugin failed: "{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.129139Z\",\"msg\":\"istio-cni CmdAdd config: &{NetConf:{CNIVersion:0.3.1 Name:k8s-pod-network Type:istio-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:<nil>} RuntimeConfig:<nil> RawPrevResult:<nil> PrevResult:0xc000aec8f0 LogLevel:debug LogUDSAddress:/var/run/istio-cni/log.sock Kubernetes:{K8sAPIRoot: Kubeconfig:/etc/cni/net.d/ZZZ-istio-cni-kubeconfig InterceptRuleMgrType: NodeName: ExcludeNamespaces:[kube-system istio-system] CNIBinDir:/opt/cni/bin} HostNSEnterExec:false}\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.129185Z\",\"msg\":\"istio-cni CmdAdd previous result: &{1.0.0 [{Name:eni67853d63736 Mac: Sandbox:} {Name:eth0 Mac: Sandbox:/var/run/netns/cni-1948e674-c659-5b3f-c8e2-d5b8c4d7497b} {Name:dummy67853d63736 Mac:0 Sandbox:0}] [{Interface:0xc000beb718 Address:{IP:16.0.3.227 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.129194Z\",\"msg\":\"istio-cni cmdAdd args: K8S_POD_INFRA_CONTAINER_ID=4292f2321caaf689b54dcc5b90250d20026864fc9c3e08754fa1cbbf4403db02;K8S_POD_UID=fdf6ab80-2450-40de-90d8-b33498341611;IgnoreUnknown=1;K8S_POD_NAMESPACE=ig1;K8S_POD_NAME=ss7fep0-0\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.129220Z\",\"msg\":\"istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:ss7fep0-0 K8S_POD_NAMESPACE:ig1 K8S_POD_INFRA_CONTAINER_ID:4292f2321caaf689b54dcc5b90250d20026864fc9c3e08754fa1cbbf4403db02}\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.129705Z\",\"msg\":\"istio-cni set up kubernetes client with kubeconfig /etc/cni/net.d/ZZZ-istio-cni-kubeconfig\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142824Z\",\"msg\":\"Inspecting pod ig1/ss7fep0-0 container ss7fep0\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142840Z\",\"msg\":\"Inspecting pod ig1/ss7fep0-0 container istio-proxy\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142886Z\",\"msg\":\"Pod ig1/ss7fep0-0 info: \\n  Init Containers: [istio-validation]\\n  Containers: [ss7fep0 istio-proxy]\\n  Labels: map[app:ss7fep0-ss7fep0 controller-revision-hash:ss7fep0-5dfdb7b9ff prometheus:mtls_disable security.istio.io/tlsMode:istio service.istio.io/canonical-name:ss7fep0-ss7fep0 service.istio.io/canonical-revision:v1 spsResourceType:fep0 statefulset.kubernetes.io/pod-name:ss7fep0-0 version:v1]\\n  Annotations: map[checksum/fep0-config:1266724e03398d28a2e773b34669b741bb0b41c99ae25f1e70d8c27c48a8fc49 k8s.v1.cni.cncf.io/network-status:[{\\n    \\\"name\\\": \\\"aws-cni\\\",\\n    \\\"interface\\\": \\\"dummy67853d63736\\\",\\n    \\\"ips\\\": [\\n        \\\"16.0.3.227\\\"\\n    ],\\n    \\\"mac\\\": \\\"0\\\",\\n    \\\"default\\\": true,\\n    \\\"dns\\\": {}\\n}] k8s.v1.cni.cncf.io/networks-status:[{\\n    \\\"name\\\": \\\"aws-cni\\\",\\n    \\\"interface\\\": \\\"dummy67853d63736\\\",\\n    \\\"ips\\\": [\\n        \\\"16.0.3.227\\\"\\n    ],\\n    \\\"mac\\\": \\\"0\\\",\\n    \\\"default\\\": true,\\n    \\\"dns\\\": {}\\n}] kubectl.kubernetes.io/default-container:ss7fep0 kubectl.kubernetes.io/default-logs-container:ss7fep0 prometheus.io/path:/stats/prometheus prometheus.io/port:15020 prometheus.io/scrape:true sidecar.istio.io/inject:true sidecar.istio.io/interceptionMode:REDIRECT sidecar.istio.io/rewriteAppHTTPProbers:true sidecar.istio.io/status:{\\\"initContainers\\\":[\\\"istio-validation\\\"],\\\"containers\\\":[\\\"istio-proxy\\\"],\\\"volumes\\\":[\\\"workload-socket\\\",\\\"credential-socket\\\",\\\"workload-certs\\\",\\\"istio-envoy\\\",\\\"istio-data\\\",\\\"istio-podinfo\\\",\\\"istio-token\\\",\\\"istiod-ca-cert\\\"],\\\"imagePullSecrets\\\":null,\\\"revision\\\":\\\"default\\\"} traffic.sidecar.istio.io/excludeInboundPorts:2905,15020 traffic.sidecar.istio.io/excludeOutboundPorts:2905 traffic.sidecar.istio.io/includeInboundPorts:* traffic.sidecar.istio.io/includeOutboundIPRanges:*]\\n  Envs: map[CA_ADDR:cert-manager-istio-csr.cert-manager.svc:443 HOST_IP: INSTANCE_IP: ISTIO_META_APP_CONTAINERS:ss7fep0 ISTIO_META_CLUSTER_ID:Kubernetes ISTIO_META_INTERCEPTION_MODE:REDIRECT ISTIO_META_MESH_ID:cluster.local ISTIO_META_OWNER:kubernetes://apis/apps/v1/namespaces/ig1/statefulsets/ss7fep0 ISTIO_META_POD_PORTS:[\\n    {\\\"name\\\":\\\"sctp-fep0ext\\\",\\\"containerPort\\\":2905,\\\"protocol\\\":\\\"SCTP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int\\\",\\\"containerPort\\\":10001,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-1\\\",\\\"containerPort\\\":10100,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-2\\\",\\\"containerPort\\\":10200,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-3\\\",\\\"containerPort\\\":10300,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep\\\",\\\"containerPort\\\":10002,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-1\\\",\\\"containerPort\\\":10003,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-2\\\",\\\"containerPort\\\":10004,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-3\\\",\\\"containerPort\\\":10005,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-4\\\",\\\"containerPort\\\":10006,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-5\\\",\\\"containerPort\\\":10007,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-6\\\",\\\"containerPort\\\":10008,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-7\\\",\\\"containerPort\\\":10009,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-8\\\",\\\"containerPort\\\":10010,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-9\\\",\\\"containerPort\\\":10011,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-10\\\",\\\"containerPort\\\":10012,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-11\\\",\\\"containerPort\\\":10013,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-12\\\",\\\"containerPort\\\":10014,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-13\\\",\\\"containerPort\\\":10015,\\\"protocol\\\":\\\"TCP\\\"}\\n] ISTIO_META_WORKLOAD_NAME:ss7fep0 JWT_POLICY:third-party-jwt PILOT_CERT_PROVIDER:istiod POD_NAME: POD_NAMESPACE: PROXY_CONFIG:{\\\"tracing\\\":{\\\"zipkin\\\":{\\\"address\\\":\\\"jaeger.istio-system:9411\\\"}}}\\n SERVICE_ACCOUNT: TRUST_DOMAIN:cluster.local TZ:UTC]\\n  ProxyConfig: map[CA_ADDR:cert-manager-istio-csr.cert-manager.svc:443 HOST_IP: INSTANCE_IP: ISTIO_META_APP_CONTAINERS:ss7fep0 ISTIO_META_CLUSTER_ID:Kubernetes ISTIO_META_INTERCEPTION_MODE:REDIRECT ISTIO_META_MESH_ID:cluster.local ISTIO_META_OWNER:kubernetes://apis/apps/v1/namespaces/ig1/statefulsets/ss7fep0 ISTIO_META_POD_PORTS:[\\n    {\\\"name\\\":\\\"sctp-fep0ext\\\",\\\"containerPort\\\":2905,\\\"protocol\\\":\\\"SCTP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int\\\",\\\"containerPort\\\":10001,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-1\\\",\\\"containerPort\\\":10100,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-2\\\",\\\"containerPort\\\":10200,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-fep0int-3\\\",\\\"containerPort\\\":10300,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep\\\",\\\"containerPort\\\":10002,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-1\\\",\\\"containerPort\\\":10003,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-2\\\",\\\"containerPort\\\":10004,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-3\\\",\\\"containerPort\\\":10005,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-4\\\",\\\"containerPort\\\":10006,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-5\\\",\\\"containerPort\\\":10007,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-6\\\",\\\"containerPort\\\":10008,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-7\\\",\\\"containerPort\\\":10009,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-8\\\",\\\"containerPort\\\":10010,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-9\\\",\\\"containerPort\\\":10011,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-10\\\",\\\"containerPort\\\":10012,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-11\\\",\\\"containerPort\\\":10013,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-12\\\",\\\"containerPort\\\":10014,\\\"protocol\\\":\\\"TCP\\\"}\\n    ,{\\\"name\\\":\\\"tcp-bep-port-13\\\",\\\"containerPort\\\":10015,\\\"protocol\\\":\\\"TCP\\\"}\\n] ISTIO_META_WORKLOAD_NAME:ss7fep0 JWT_POLICY:third-party-jwt PILOT_CERT_PROVIDER:istiod POD_NAME: POD_NAMESPACE: PROXY_CONFIG:{\\\"tracing\\\":{\\\"zipkin\\\":{\\\"address\\\":\\\"jaeger.istio-system:9411\\\"}}}\\n SERVICE_ACCOUNT: TRUST_DOMAIN:cluster.local TZ:UTC]\\n\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142938Z\",\"msg\":\"Checking pod ig1/ss7fep0-0 annotations prior to redirect for Istio proxy\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142946Z\",\"msg\":\"Pod ig1/ss7fep0-0 contains inject annotation: true\"}\n{\"level\":\"debug\",\"time\":\"2023-08-10T04:17:42.142948Z\",\"msg\":\"Setting up redirect for pod ig1/ss7fep0-0\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.143072Z\",\"msg\":\"============= Start iptables configuration for ss7fep0-0 =============\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.143306Z\",\"msg\":\"Istio iptables environment:\\nENVOY_PORT=\\nINBOUND_CAPTURE_PORT=\\nISTIO_INBOUND_INTERCEPTION_MODE=\\nISTIO_INBOUND_TPROXY_ROUTE_TABLE=\\nISTIO_INBOUND_PORTS=\\nISTIO_OUTBOUND_PORTS=\\nISTIO_LOCAL_EXCLUDE_PORTS=\\nISTIO_EXCLUDE_INTERFACES=\\nISTIO_SERVICE_CIDR=\\nISTIO_SERVICE_EXCLUDE_CIDR=\\nISTIO_META_DNS_CAPTURE=\\nINVALID_DROP=\\n\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.143352Z\",\"msg\":\"Istio iptables variables:\\nPROXY_PORT=15001\\nPROXY_INBOUND_CAPTURE_PORT=15006\\nPROXY_TUNNEL_PORT=15008\\nPROXY_UID=1337\\nPROXY_GID=1337\\nINBOUND_INTERCEPTION_MODE=REDIRECT\\nINBOUND_TPROXY_MARK=1337\\nINBOUND_TPROXY_ROUTE_TABLE=133\\nINBOUND_PORTS_INCLUDE=*\\nINBOUND_PORTS_EXCLUDE=2905,15020,15021,15090\\nOUTBOUND_OWNER_GROUPS_INCLUDE=*\\nOUTBOUND_OWNER_GROUPS_EXCLUDE=\\nOUTBOUND_IP_RANGES_INCLUDE=*\\nOUTBOUND_IP_RANGES_EXCLUDE=\\nOUTBOUND_PORTS_INCLUDE=\\nOUTBOUND_PORTS_EXCLUDE=2905\\nKUBE_VIRT_INTERFACES=\\nENABLE_INBOUND_IPV6=false\\nDNS_CAPTURE=false\\nDROP_INVALID=false\\nCAPTURE_ALL_DNS=false\\nDNS_SERVERS=[],[]\\nOUTPUT_PATH=\\nNETWORK_NAMESPACE=/var/run/netns/cni-1948e674-c659-5b3f-c8e2-d5b8c4d7497b\\nCNI_MODE=true\\nHOST_NSENTER_EXEC=false\\nEXCLUDE_INTERFACES=\\n\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.143472Z\",\"msg\":\"Writing following contents to rules file: /tmp/iptables-rules-1691641062143412690.txt2407192186\\n* nat\\n-N ISTIO_INBOUND\\n-N ISTIO_REDIRECT\\n-N ISTIO_IN_REDIRECT\\n-N ISTIO_OUTPUT\\n-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN\\n-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001\\n-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006\\n-A PREROUTING -p tcp -j ISTIO_INBOUND\\n-A ISTIO_INBOUND -p tcp --dport 2905 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN\\n-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN\\n-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT\\n-A OUTPUT -p tcp -j ISTIO_OUTPUT\\n-A ISTIO_OUTPUT -p tcp --dport 2905 -j RETURN\\n-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN\\n-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN\\n-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT\\n-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN\\n-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN\\n-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\\n-A ISTIO_OUTPUT -j ISTIO_REDIRECT\\nCOMMIT\"}\n{\"level\":\"info\",\"time\":\"2023-08-10T04:17:42.143505Z\",\"msg\":\"Running command: iptables-restore --noflush /tmp/iptables-rules-1691641062143412690.txt2407192186\"}\n{\"level\":\"error\",\"time\":\"2023-08-10T04:17:42.144589Z\",\"msg\":\"Command error output: xtables other problem: line 2 failed\"}\n{\"level\":\"error\",\"time\":\"2023-08-10T04:17:42.144602Z\",\"msg\":\"Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1691641062143412690.txt2407192186, exit status 1\"}\n"
 Normal   AddedInterface          110s                   multus             Add eth0 [16.0.3.227/32] from aws-cni
 Normal   AddedInterface          109s                   multus             Add eth0 [16.0.1.103/32] from aws-cni
 Normal   AddedInterface          108s                   multus             Add eth0 [16.0.2.20/32] from aws-cni
 Normal   AddedInterface          107s                   multus             Add eth0 [16.0.1.231/32] from aws-cni
 Normal   AddedInterface          106s                   multus             Add eth0 [16.0.0.146/32] from aws-cni
 Normal   AddedInterface          105s                   multus             Add eth0 [16.0.0.199/32] from aws-cni
 Normal   AddedInterface          104s                   multus             Add eth0 [16.0.1.75/32] from aws-cni
 Normal   AddedInterface          103s                   multus             Add eth0 [16.0.3.128/32] from aws-cni
 Normal   AddedInterface          102s                   multus             Add eth0 [16.0.3.79/32] from aws-cni
 Normal   AddedInterface          101s                   multus             Add eth0 [16.0.1.90/32] from aws-cni
 Normal   AddedInterface          100s                   multus             Add eth0 [16.0.1.54/32] from aws-cni
 Normal   AddedInterface          99s                    multus             Add eth0 [16.0.3.181/32] from aws-cni
 `
### Version

```Text
Istio version : 1.16
K8s version : 1.25
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by arunpmohan** [comment]
2023-08-10T15:48:30.566778Z	info	cni	============= Start iptables configuration for ss7fep0-0 =============
2023-08-10T15:48:30.566783Z	info	cni	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=
2023-08-10T15:48:30.566787Z	info	cni	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=2905,15020,15021,15090
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=2905
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=/var/run/netns/cni-82391268-1f40-8fed-acd9-ab2c78359f22
CNI_MODE=true
HOST_NSENTER_EXEC=false
EXCLUDE_INTERFACES=
2023-08-10T15:48:30.566790Z	info	cni	Writing following contents to rules file: /tmp/iptables-rules-1691682510563402494.txt150273347
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 2905 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 2905 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2023-08-10T15:48:30.566793Z	info	cni	Running command: iptables-restore --noflush /tmp/iptables-rules-1691682510563402494.txt150273347
2023-08-10T15:48:30.566796Z	info	cni	Writing following contents to rules file: /tmp/ip6tables-rules-1691682510565435538.txt3540471797
2023-08-10T15:48:30.566798Z	info	cni	Running command: ip6tables-restore --noflush /tmp/ip6tables-rules-1691682510565435538.txt3540471797
2023-08-10T15:48:30.566802Z	info	cni	============= End iptables configuration for ss7fep0-0 =============

**Comment by malbertone** [comment]
Hi, with the same istio version 1.16 on VMWare TKG 2.1 running k8s 1.24 we had a very similar issue on pods having only 1 calico interface, and belonging to a fluentd daemonset. They started a never ending loop while trying to get the istio CNI configured:
  Warning  FailedCreatePodSandBox  92s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "381774a5524e9c22295641c14a079ea65f95989c2d3129e5437372a804437090": plugin type="istio-cni" name="istio-cni" failed (add): netplugin failed: "{\"level\":\"debug\",\"time\":\"2023-09-18T13:18:23.965538Z\",\"msg\":\"istio-cni CmdAdd config: &{NetConf:{CNIVersion:0.3.1 Name:k8s-pod-network Type:istio-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:<nil>} RuntimeConfig:<nil> RawPrevResult:<nil> PrevResult:0xc001202370 LogLevel:debug LogUDSAddress:/var/run/istio-cni/log.sock Kubernetes:{K8sAPIRoot: Kubeconfig:/etc/cni/net.d/ZZZ-istio-cni-kubeconfig InterceptRuleMgrType: NodeName: ExcludeNamespaces:[kube-system istio-system] CNIBinDir:/opt/cni/bin} HostNSEnterExec:false}\"}\n{\"level\":\"debug\",\"time\":\"2023-09-18T13:18:23.965592Z\",\"msg\":\"istio-cni CmdAdd previous result: &{1.0.0 [{Name:cali70daf7aad50 Mac: Sandbox:}] [{Interface:<nil> Address:{IP:100.104.59.195 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\"}\n{\"level\":\"debug\",\"time\":\"2023-09-18T13:18:23.965599Z\",\"msg\":\"istio-cni cmdAdd args: K8S_POD_INFRA_CONTAINER_ID=381774a5524e9c22295641c14a079ea65f95989c2d3129e5437372a804437090;K8S_POD_UID=0a477295-9be6-4c08-978a-
...
1695043103975995813.txt1238345130\"}\n{\"level\":\"error\",\"time\":\"2023-09-18T13:18:23.977796Z\",\"msg\":\"Command error output: xtables other problem: line 2 failed\"}\n{\"level\":\"error\",\"time\":\"2023-09-18T13:18:23.977820Z\",\"msg\":\"Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1695043103975995813.txt1238345130, exit status 1\"}\n"

Configuration attempted was:
2023-09-18T11:40:15.018263Z     info    cni     Writing following contents to rules file: /tmp/iptables-rules-1695037215011585252.txt992860440

* nat

-N ISTIO_INBOUND

-N ISTIO_REDIRECT

-N ISTIO_IN_REDIRECT

-N ISTIO_OUTPUT

-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN

-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001

-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006

-A PREROUTING -p tcp -j ISTIO_INBOUND

-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN

-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN

-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN

-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT

-A OUTPUT -p tcp -j ISTIO_OUTPUT

-A ISTIO_OUTPUT -p tcp --dport 3000 -j RETURN

-A ISTIO_OUTPUT -p tcp --dport 3010 -j RETURN

-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN

-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT

-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN

-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN

-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT

-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN

-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN

-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN

-A ISTIO_OUTPUT -j ISTIO_REDIRECT

COMMIT

2023-09-18T11:40:15.018268Z     info    cni     Running command: iptables-restore --noflush /tmp/iptables-rules-1695037215011585252.txt992860440

2023-09-18T11:40:15.018270Z     info    cni     Writing following contents to rules file: /tmp/ip6tables-rules-1695037215014291072.txt675437866

2023-09-18T11:40:15.018273Z     info    cni     Running command: ip6tables-restore --noflush /tmp/ip6tables-rules-1695037215014291072.txt675437866

2023-09-18T11:40:15.018275Z     info    cni     ============= End iptables configuration for ig-xdrproxy-68df8497d8-fhjmp =============
