### ISSUE TITLE
istio proxy side car container is crashing continuously, version 1.15.3

### ISSUE THREAD

**Issue by sakulka** [istio/istio#46452]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

we are using injecting istio as side car to our microservices, however, off late, we see istio proxy continuously crashing. version is 1.15.3. we have the flag holdapplicationuntilproxystarts enabled globally (understand that enabling this globally has been deprecated in release 1.8.1). below are the logs. 
========
, message: "2023-08-10T05:18:57.513110Z\tinfo\tWaiting for Envoy proxy to be ready (timeout: 60 seconds)...\n2023-08-10T05:19:57.528383Z\terror\ttimeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp 127.0.0.1:15021: connect: connection refused\nError: timeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp 127.0.0.1:15021: connect: connection refused\n"
  Warning  BackOff  2m50s (x3694 over 12h)  kubelet  Back-off restarting failed container
=========
proxy logs, we dont have any network policy defined to allow.deny traffic to 169.254.20.10
============
2023-08-10T05:44:42.383858Z	warn	sds	failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 169.254.20.10:53: no such host"
============
we dont have any network policy defined.

k8s version is 1.23.14

### Version

```Text
istio version 1.15.3
helm 3
k8s version 1.23.14
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by sakulka** [comment]
we have the port opened, as the pod was functioning normally, until we started hitting this error

**Comment by zirain** [comment]
looks coredns failed.

**Comment by sakulka** [comment]
@zirain thanks for replying. i dont see any error logs in coredns other than this shown below
============
santosh.kulkarni@D6M2JVN9KC beta % kubectl logs -n kube-system coredns-548ff45b67-pbsv2
.:53
consul.:53
consul.local.:53
[INFO] plugin/reload: Running configuration MD5 = 38c3c5f16cb41832714872af2e3fb2fd
CoreDNS-1.9.0
linux/amd64, go1.17.6, ace3dcb
==========

**Comment by sakulka** [comment]
**i forgot to add, we have nodelocal dns as cache, i see timed out entries in the logs, but since its a cache, will the domain lookup failures caused by nodelocal dns cache?
=================
[ERROR] plugin/errors: 2 consul-server.consul.svc.cluster.local.cmwnext-previewbeta2.svc.cluster.local. AAAA: dial tcp 10.43.243.23:53: i/o timeout**

**Comment by zirain** [comment]
the only things I can say is DNS is required.

**Comment by sakulka** [comment]
we have core dns pods working, and also dont see any logs in dns pods, sorry if i'm repeating the same, can you please let me know, anything else apart from this to be verified. the dns entries on the node also looks fine

**Comment by zirain** [comment]
> 2023-08-10T05:44:42.383858Z warn sds failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 169.254.20.10:53: no such host"

can you fixed this first? I'm not sure what is `169.254.20.10` stand for?
also you can try use `sidecar.istio.io/discoveryAddress` annotation override discovery address with service ip of `istiod.system.svc`.

**Comment by ramaraochavali** [comment]
Please note 1.15 is already EOL https://istio.io/latest/docs/releases/supported-releases/

**Comment by sakulka** [comment]
we have this 169.254.20.10  in the config map of nodelocal dns

**Comment by keithmattix** [comment]
1.15 is EOL. Please upgrade
