### ISSUE TITLE
Unable to set rollingUpdate strategy in manifests/charts/gateway/templates/deployment.yaml

### ISSUE THREAD

**Issue by hari-rad** [istio/istio#46471]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As we are unable to set these parameters, a large number of gateway pods are terminated simultaneously on a rollingUpdate. This is based on default settings
[This deployment](https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml)
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

### Version

```Text
$ k version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3-eks-a5565ad
$ istioctl version -i kube-system-istio
client version: 1.18.2
control plane version: 1.19.0-alpha.1
data plane version: 1.19.0-alpha.1 (12 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
https://github.com/istio/istio/pull/46473
