### ISSUE TITLE
Feature request: include JWT header information in dynamic metadata

### ISSUE THREAD

**Issue by Niksko** [istio/istio#46484]
**Describe the feature request**

Currently, Istio includes the JWT payload information in the request StreamInfo DynamicMetadata under the `envoy.filters.http.jwt_authn` key. This makes use of the native Envoy filter property `payload_in_metadata` that is documented in the [Envoy docs for the JWT authn filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtauthentication).

We would like to make use of the header information of the JWT, in particular, the `kid` field. This could be achieved by configuring the similar `header_in_metadata` field of the JWT authn filter.

I'd be happy with either an optional field in the `RequestAuthentication` resource that allows for this data to be written to the request StreamInfo DynamicMetadata, or just this data always being there (as it appears to be now with the payload data).

Happy to implement this in Istio if need be.

**Describe alternatives you've considered**

Unfortunately, it's very hard to get this information otherwise.

Istio's `RequestAuthentication` options don't deal with the JWT header information, it's all about copying information from the JWT payload.

Patching the `authn` filter with an `EnvoyFilter` might be possible, but seems difficult, especially on a mesh-wide scale. 
However if folks have suggestions as to how to accomplish this, that would be great, as this would provide a neat solution.

Writing a custom `EnvoyFilter` that parses the JWT and extracts the header information to put into metadata seems doable, but the LuaJIT's lack of support for JSON parsing and base64 decoding makes this difficult to do securely.

Writing a custom WASM based Envoy extension is an option, but one that we'd rather avoid, given that the functionality already exists in Envoy, it just isn't enabled in Istio.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by wulianglongrd** [comment]
I think the easiest and feasible way may be to add a redundant property to the jwt payload (from the jwt header, when the jwt is issued).

**Comment by Niksko** [comment]
That's possible, but I don't think it solves the problem. I'd still want to know that the redundant field in the payload matches the one in the header. And I can't know that without access to the JWT headers.
