### ISSUE TITLE
non-disruptive waypoint additions

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#46495]
**Describe the feature request**

Adding a waypoint proxy should not cause disruption to traffic. We've pitched ambient as "only pay for what you use."  We've encouraged adoption of the ztunnel first and later adding waypoint as you need. If adding the waypoint is a disruptive event it could dampen enthusiasm for this approach.

At present adding a waypoint seems to create a race between the waypoint becoming ready and proxies being configured to use the waypoint. Relevant ztunnel logs for this type of event:

```text
2023-08-10T18:46:46.830246Z DEBUG outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::state: fetch address network_addr.address=10.32.13.48
2023-08-10T18:46:46.830258Z DEBUG outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::state: found upstream Upstream{reviews-v3-6b64666d78-fxf2s with uid Kubernetes//Pod/bookinfo/reviews-v3-6b64666d78-fxf2s:9080 via 10.32.8.82:15008 (HBONE)} from VIP 10.32.13.48
2023-08-10T18:46:46.830265Z DEBUG outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::state: fetch address network_addr.address=10.32.8.82
2023-08-10T18:46:46.830268Z DEBUG outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::state: VIP 10.32.8.82:15008 has no healthy endpoints
2023-08-10T18:46:46.830271Z DEBUG outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::state: waypoint upstream not found wl.name=reviews-v3-6b64666d78-fxf2s
2023-08-10T18:46:46.830359Z  WARN outbound{id=6a3bf7d5d78bbad01004ec89a7276823}: ztunnel::proxy::outbound: failed dur=215.671µs err=unknown waypoint: failed to find waypoint for workload: reviews-v3-6b64666d78-fxf2s
```

Similar behavior has been observed for traffic where the client has a sidecar as well but it's less common.

**Describe alternatives you've considered**

Ask users to deploy waypoints up front even if they don't need them.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

After considering some options I think potential solutions are:

- Make istiod more context aware. If waypoint is deployed but there is no policy used which requires us to send traffic to waypoint do not configure proxies to target the waypoint for that service. Only when there is a policy to enforce at waypoint would it be configured. Advise users to deploy waypoint prior to applying any policy.
- Implement a grace period approach to allow time for waypoints to become ready. This should likely be entirely in istiod where proxies are not configured to use the waypoint to reach ns/sa workloads until grace period expires or waypoints become ready. It could potentially also be implemented in the data plane but this seems like unnecessary work being done in the data path and is likely undesirable as a result.
- both, could consider doing both to provide some extra assurances that users won't be impacted even if they do things out of order

**Comment by howardjohn** [comment]
My original expectation was that we would "ratchet" the readiness of gateway. Once it becomes ready once, we start sending to it. If it later becomes unready we stop sending to it. I think there is some TODOs around this already.

One mechanism for that can be to not allocate the `gateway.status.address` until its ready once.

**Comment by ilrudie** [comment]
I'd agree, I think once it becomes ready then our obligation is to use it. If for some reason there's an outage later on down the line it's an outage, we can't bypass it at that point

**Comment by howardjohn** [comment]
Yep, same with ztunnel initial rollout as well. Ben looked at a lot into that, not sure the current status

**Comment by linsun** [comment]
What is the easiest way to tell if the waypoint is ready once?

**Comment by linsun** [comment]
I am not sure if we want Istiod to be context aware, I'd wait till users ask for it.  Plus like we discussed, how do we know if users deploy waypoint for L7 telemetry but not for policy.

>     * Make istiod more context aware. If waypoint is deployed but there is no policy used which requires us to send traffic to waypoint do not configure proxies to target the waypoint for that service. Only when there is a policy to enforce at waypoint would it be configured. Advise users to deploy waypoint prior to applying any policy.

**Comment by GregHanson** [comment]
not sure if this is related-to/encompassed-by https://github.com/istio/ztunnel/issues/311 - but linking for reference:
https://github.com/istio/ztunnel/issues/311

**Comment by kdorosh** [comment]
> My original expectation was that we would "ratchet" the readiness of gateway. Once it becomes ready once, we start sending to it. If it later becomes unready we do NOT stop sending to it. I think there is some TODOs around this already.

I'm assuming there would be some kind of timeout here? I'd expect istio L7 config to be eventually consistent. If the waypoint never becomes ready if we had L7 auth I'd eventually expect that to start failing, even in the ratchet scenario

**Comment by kdorosh** [comment]
That's a reasonable argument. If k8s operators think that unready waypoints are monitored closely enough that operators will notice and address, then I'm ok with that.

**Comment by keithmattix** [comment]
I think I'm slightly in favor of a timeout because we're dealing with policy. In general, my preference is to fail in an obvious way. If the waypoint isn't ready in ~5 minutes, then yeah it's time for the system to act up to bring attention to the broken state.

**Comment by howardjohn** [comment]
I don't think I have ever seen something in Kubernetes where if you don't resolve an issue within 5 minutes it decides to punish you by causing an outage... it seems like not a very safe idea

**Comment by keithmattix** [comment]
Well, the outage would be scoped to that particular namespace/service account depending on the granularity chosen. My thinking is, if we don't start sending to the waypoint after some upper bound, that creates:
1. An attack vector where if a noisy neighbor hogs node resources and cluster-autoscaler is taking awhile, any policy for the waypoint in question won't be enforced
2. A situation where a user "just has to know" that ztunnel won't send to waypoint if it isn't ready to correctly debug unexpected behavior.

**Comment by howardjohn** [comment]
The current promise we have is "Once a config is fully applied [eventual consistency], its always applied". This is actually trickier than it sounds, since we never _tell_ a user a config has been applied or not. But in general in Kubernetes this is the pattern - you can never just blindly `apply` and walk away, always check it became Ready after.

The same, IMO, applies here. we can encourage this as well by making `istioctl x waypoint apply` also wait (or `--wait`), and document for manual installs how to wait for it to be ready. So they don't have to know magically -- there is a well defined pattern for how they know

**Comment by keithmattix** [comment]
+1 to the above, but the "just know" I'm talking about is referring to ztunnel behavior. IIUC, what's being proposed is for ztunnel to not send traffic to a waypoint until it's ready (once it's ready once, traffic is always routed there even if it becomes unready again). If there's no upper bound on that readiness check, any policy applied to that waypoint will be bypassed in a silent, undetectable way. Sure it's best practice to make sure to check ready, but imagine an ambient cluster with hundreds of services and a hundred waypoint gateways. You've gotta check that particular Gateway's status to see if the waypoint is programmed and worse, you must look at the pods managed by that Gateway to see if it's Ready. By eventually sending traffic to the waypoint to force 503s, we surface the error to the user. How else to they discover the pods aren't ready (say in the cluster autoscaler scenario i mentioned)

**Comment by howardjohn** [comment]
No, my suggestion is Istiod does not configure a Waypoint at all until its Ready (the first time).

> you must look at the pods managed by that Gateway to see if it's Ready.

Istiod is already doing this, see https://github.com/istio/istio/pull/46500

> How else to they discover the pods aren't ready

The Gateway status will report this

**Comment by keithmattix** [comment]
> No, my suggestion is Istiod does not configure a Waypoint at all until its Ready (the first time).

Ack - I thought istiod would configure the waypoint and ztunnel just won't send until ready. I'm good with this 👍🏾

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/46540 is merged, can this be closed?

**Comment by ilrudie** [comment]
I think it can close. We can reopen or create a new issue if we find it's needed in 1.19 as well.
