### ISSUE TITLE
istiod container refuses to start on Docker Desktop's Kubernetes

### ISSUE THREAD

**Issue by CheyenneForbes** [istio/istio#46506]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

The istiod container refused to start on Docker Desktop' Kubernetes with WSL2 with the following error: `k8s.io/client-go@v0.27.0/tools/cache/reflector.go:231: failed to list *v1.ConfigMap: Get "https://10.96.0.1:443/api/v1/namespaces/istio-system/configmaps?fieldSelector=metadata.name%3Distio&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: connect: network is unreachable`

If I install istiod before istio-cni (which is wrong) the istiod container starts but of course it prevents proxying.

### Version

```Text
kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2

helm version --short
v3.11.2+g912ebc1
```

### Additional Information

it's the same experience for both versions 1.17.2 and 1.18.2

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by CheyenneForbes** [comment]
> Istio CNI shouldn't impact the istiod control plane. If it is, the install of Istio CNI is probably totally breaking the node in some way, resulting in this. I would look into the CNI (both Istio CNI and the native k8s one)

The same helm values for the istio CNI charts works ok in multiple cloud providers, so I assume its related to the docker desktop implementation (uses kubeadm)

**Comment by howardjohn** [comment]
Yes my guess would be something like:

1. Istio CNI mucks around on the node
2. The k8s implementation doesn't like this and crashes or something
3. Everything is broken

Hard to say without more details
