### ISSUE TITLE
Helm chart not renedering telemetry for Prometheus

### ISSUE THREAD

**Issue by micahlmartin** [istio/istio#46505]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm tying to install 1.18 version of the helm chart and have it install the telemetry v2 manifests. I believe I have all the values configured correctly but it's still not rendering them.

I believe the issue is caused by[this logic](https://github.com/istio/istio/commit/cce7606d24810ec2b867579de994503ad0c5c9ba#r124322792) in the helm chart: 

```
{{ $prom := not (include "prometheus" . | eq "true") }}
```

Even though `include "prometheus" .` is resulting in `true` the `not` clause is resulting in `$prom` being false.

These are my values (the defaults)

```
telemetry:
  enabled: true

  v2:
    enabled: true

    prometheus:
      enabled: true
```

### Version

```Text
istioctl version: 1.18.2
helm version: v3.8.2+g6e3701e
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
can you check the confiuration of `istioctl pc l`, is there any filter named `istio.stats`?
Istio's trying to use Telemetry API instead of the old EnvoyFilter way.

**Comment by micahlmartin** [comment]
@zirain Here's what I get:

```
❯ istioctl pc l istiod-gateway-79b7b8f78b-gnpmf -n istio
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.8080
0.0.0.0 8443  ALL   Route: http.8443
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```

**Comment by zirain** [comment]
sorry, please add -oyaml

**Comment by caoyukun0430** [comment]
@rahtr and @micahlmartin  Starting with Istio version 1.18, the Prometheus EnvoyFilter will not be installed by default, and instead meshConfig.defaultProviders is used to enable it. Telemetry API should be used to further customize the telemetry pipeline. https://istio.io/latest/docs/tasks/observability/metrics/telemetry-api/
