### ISSUE TITLE
ambient: consider blocking usage in bad installation patterns

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46524]
To offer a carrot+stick towards adopting best practices, we should consider (in varying levels of extreme-ness):

* Not allowing install of ambient with in-cluster operator
* Not allowing ztunnel install in an IstioOperator (istioctl or operator) with other components (i.e. you must manage ztunnel alone)
* Requiring helm

**Comment by bleggett** [comment]
> Requiring helm
> Not allowing install of ambient with in-cluster operator

+1 on both of these.

**Comment by linsun** [comment]
What is the issue of installing ztunnel with ambient profile for folks to quickly try ambient?

I found a bit odd that istio operator server side controller support for ambient is removed in 1.20, before helm support is in.

**Comment by hanxiaop** [comment]
@linsun The Ambient profile itself is a bad installation pattern that includes both the control plane and ztunnel/cni components, making it hard to manage the installed components effectively. As we discourage the use of the in-cluster operator in favor of Helm option, disabling the operator was the first step. See https://github.com/istio/istio/pull/46716#issuecomment-1715908028, and we expect the helm doc option to be finished by 1.20 as well.

**Comment by linsun** [comment]
I assume this is not beta blocker? I don't feel strongly we have to have this:

- Not allowing ztunnel install in an IstioOperator (istioctl or operator) with other components (i.e. you must manage ztunnel alone)

The other two might have already been taken care of.

**Comment by howardjohn** [comment]
We already decided here: no in-cluster operator, but can use with Istioctl
