### ISSUE TITLE
How to migrate istioctl distro to helm chart without loosing VirtualServices/Gateways?

### ISSUE THREAD

**Issue by makarov-roman** [istio/istio#46523]
Hello,
As the title says I'm trying to switch from `istioctl` to `helm chart`.
To do so we should delete current istio. It was installed as `istioctl install -f istio-operator.yaml`
If I do reverse `istio uninstall -f istio-operator.yaml` it leaves resources which prevents helm from being installed.

these are just part of it, after 4th resource I gave up
```bash
kubectl delete serviceaccount istio-reader-service-account -n istio-system
kubectl delete serviceaccount istiod-service-account -n istio-system
kubectl delete clusterrole istiod-istio-system
kubectl delete clusterrole istio-reader-istio-system
```

another line from the doc `istioctl manifest generate <your original installation options> | kubectl delete --ignore-not-found=true -f -` wipes all virtualServices and gateways, so I assume it works like `istioctl uninstall --purge`, which is confusing because there is big warning saying that `--purge` will wipe everything, but manifest generate is next to `istio uninstall -f istio-operator.yaml`.
[Uninstall docs](https://istio.io/latest/docs/setup/install/istioctl/#uninstall-istio)

Could it be that there is a bug in `istio uninstall` that it does not remove all necessary resources? Or it is expected behaviour?

**Comment by makarov-roman** [comment]
Should we create a cli command/script to add the helm label to all necessary resources, so helm can update them instead of replacing.

**Comment by hanxiaop** [comment]
> Should we create a cli command/script to add the helm label to all necessary resources, so helm can update them instead of replacing.

It seems that doing this may still lead to inconsistencies if adding new resources/components, and add a lot of junk to the Helm chart. Maybe we can improve  `istioctl uninstall` to correctly clean up conflicting resources.

**Comment by makarov-roman** [comment]
```bash
      kubectl delete --ignore-not-found=true ValidatingWebhookConfiguration istiod-default-validator -n istio-system
      kubectl delete --ignore-not-found=true serviceaccount istio-reader-service-account -n istio-system
      kubectl delete --ignore-not-found=true ClusterRoleBinding istio-reader-service-account
      kubectl delete --ignore-not-found=true serviceaccount istiod-service-account -n istio-system
      kubectl delete --ignore-not-found=true role istiod-istio-system -n istio-system
      kubectl delete --ignore-not-found=true RoleBinding istiod-istio-system -n istio-system
      kubectl delete --ignore-not-found=true clusterrole istiod-istio-system
      kubectl delete --ignore-not-found=true ClusterRoleBinding istiod-istio-system
      kubectl delete --ignore-not-found=true clusterrole istio-reader-istio-system
      kubectl delete --ignore-not-found=true ClusterRoleBinding istio-reader-istio-system
      # specific?
      kubectl delete --ignore-not-found=true deployment istio-ingressgateway -n istio-system
      kubectl delete --ignore-not-found=true svc istio-ingressgateway -n istio-system
```
that's the list I came up with. I'm not sure if it wipes everything, but it's enough to make helm distro install (base + istiod + gw)

**Comment by makarov-roman** [comment]
@therealmitchconnors Unfortunately I cannot test it, because I can't invest more time into that, but the idea was to switch to helm without deleting routing configuration (e.g. VS,GW). And I assume that --pruge will remove them.
Helm error is very generic `Error: rendered manifests contain a resource that already exists`, basically it can't update existing resource if there is no helm labels on that.
