### ISSUE TITLE
TestCheckReportDisable - check_report_disable failed in racy test

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#4653]
This test suddenly started to fail in racetest on master:  https://circleci.com/gh/istio/istio/61299

**Comment by cmluciano** [comment]
Another example fail https://github.com/istio/istio/pull/4643

**Comment by cmluciano** [comment]
Removed racetest from required to unblock submit queue

**Comment by JimmyCYJ** [comment]
Seems that this test has been updated recently by https://github.com/istio/istio/pull/4231

**Comment by JimmyCYJ** [comment]
After I modify the test setup, the latest racy test succeeds in https://github.com/istio/istio/pull/4643#issuecomment-377554642. I think the test failure is fixed in that PR.
