### ISSUE TITLE
HTTPS_re-encrypt test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46555]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46553/integ-pilot-multicluster_istio/1691782056792559616

We create a SIMPLE DR, but the EDS still shows cross-network endpoints: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/46553/integ-pilot-multicluster_istio/1691782056792559616/artifacts/pilot-989dd9a91575412f97742d3ec/TestTraffic/gateway/HTTPS_re-encrypt/to_b.echo/from_cross-network-primary/_test_context/istio-state31148159/cross-network-primary/istio-ingressgateway-54486f7956-mf6v2_proxy-config.json

Not sure why, at first glance code looks ok. Maybe a caching issue. cc @stevenctl

**Comment by stevenctl** [comment]
https://github.com/istio/istio/blob/93758c226683acea24867e365386ab4da567444f/pilot/pkg/xds/endpoints/mtls_checker.go#L52-L60

SIMPLE doesn't affect the filtering.

**Comment by howardjohn** [comment]
huh, I skipped right over that.

It should, right?

**Comment by stevenctl** [comment]
I'm pretty sure we can support this if SIMPLE still sends the correct SNI and the server is permissive.

**Comment by howardjohn** [comment]
I think it needs the Istio ALPN as well which we shouldn't be setting for SIMPLE.

**Comment by keithmattix** [comment]
Or MUTUAL for that matter right?
