### ISSUE TITLE
How to use hostname in single control plane setup for different network for AWS cloud provider

### ISSUE THREAD

**Issue by apurvisri** [istio/istio#46551]
Hi All,
I am using network load balancer in AWS to get static IP for  Single Control plane Istio Service Mesh setup. Issue is when I am passing IP associated to network load balancer of primary cluster to remote cluster as remoteIpAddress, pod is not coming up and in replicaset we are getting error as 

**"Warning  FailedCreate  14m (x166 over 41h)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "[object.sidecar-injector.istio.io](http://object.sidecar-injector.istio.io/)": failed to call webhook: Post [https://istiod.istio-system.svc:443/inject?timeout=10s](https://istiod.istio-system.svc/inject?timeout=10s): Address is not allowed"** 

and when passing NLB DNS getting same error with "**Hostname Not Allowed**".

Please provide us any solution how to do Istio Single control plane setup in AWS cloud provider using network Load Balancer.

**Comment by hzxuzhonghu** [comment]
Btter provide more info. 


`
"Warning FailedCreate 14m (x166 over 41h) replicaset-controller Error creating: Internal error occurred: failed calling webhook "[object.sidecar-injector.istio.io](http://object.sidecar-injector.istio.io/)": failed to call webhook: Post [https://istiod.istio-system.svc:443/inject?timeout=10s](https://istiod.istio-system.svc/inject?timeout=10s): Address is not allowed"
`

For the error, do you have istiod installed in the cluster? Or is there ant policy that does not allow commincating with the address

**Comment by apurvisri** [comment]
This is for remote cluster on which istiod is not installed and we only have service running which have Discovery Address of Primary Cluster as Endpoints in single control Plane Setup
