### ISSUE TITLE
Istioctl analyze timing out in large clusters

### ISSUE THREAD

**Issue by ivpr** [istio/istio#46563]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have couple of large clusters which have >12k configmaps across namespaces. While running `istioctl analyze` on these clusters, the command is timing out while fetching all config maps. We use config map as the helm storage driver which is the reason for huge number of config maps. (Similar to #45458 but for configmaps)
```
error    analysis    Failed to watch crd resource for analysis: failed to list *v1.ConfigMap: stream error when reading response body, may be caused by closed connection. 

Please retry. Original error: stream error: stream ID 19; INTERNAL_ERROR; received from peer 
```
On checking the usage of configmaps for analyze, I see it's only being used in [injection](https://github.com/istio/istio/blob/11787e8a1c5d6dbe418095c9e4cee1f77ba1b0ac/pkg/config/analysis/analyzers/injection/injection.go#L56) and [injection-image](https://github.com/istio/istio/blob/11787e8a1c5d6dbe418095c9e4cee1f77ba1b0ac/pkg/config/analysis/analyzers/injection/injection-image.go#L61) analyzers where only the `istio-sidecar-injector` configmap is being used. 

Since the configmap is present in the istio config(default istio-system) namespace, can we only get the configmaps from this namespace instead of all configmaps from across the cluster?

### Version

```Text
client version: 1.20-dev
control plane version: 1.15.3
data plane version: 1.15.3 (2519 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Sounds good, I'll check if we have better filtering logic.
