### ISSUE TITLE
Enable Additional Envoy Filters for WasmPlugin

### ISSUE THREAD

**Issue by cpmoser** [istio/istio#46568]
**Describe the feature request**
Istio's `WasmPlugin` currently supports only HTTP filter creation, which limits the ability to create plugins for TCP based protocols.  I would like to propose enabling support for other protocols besides HTTP.

**Describe alternatives you've considered**
The `EnvoyFilter` allows configurability of filters for any Envoy filter type, however this resource appears to be deprecated and no longer supported.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
Please follow this https://github.com/istio/api/pull/2904

**Comment by cpmoser** [comment]
@ramaraochavali cool, thank you

**Comment by kyessenov** [comment]
How do you create Wasm network filters? Should we also somehow mark the binaries somehow? Otherwise, one might try calling HTTP ABI on a network Wasm by accident.

**Comment by cpmoser** [comment]
@kyessenov I don't know enough about the internal of how the `EnvoyFilter` works, but it does take an Envoy filter configuration, where you can specify where in the order of execution the wasm filter goes - at least, that's how I understand it :) 
I suppose one could accidentally call an HTTP on a network filter, not sure what will happen in that case.  I've been using the solo.io assemblyscript SDK and in that class since the paradigm is to derive from a base class so in that case nothing will happen.
