### ISSUE TITLE
warmupDurationSecs erratic behaviour

### ISSUE THREAD

**Issue by palmobar** [istio/istio#46569]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm seeing erratic behaviour when using `warmupDurationSecs`. The `DestinationRule` is as follows:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
  name: aiohttp-service
spec:
  host: aiohttp-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      warmupDurationSecs: 180s
```

The test scenario is as follows: Have a very simple python script that returns 200 for a http GET call (essentially this one: https://github.com/envoyproxy/envoy/blob/main/examples/locality-load-balancing/service.py) running in a deployment and then scale it in sequence in a following manner: 0 -> 1 -> 2 -> 3 -> 4.

What I'd expect to see is that the pods are slowly ramping up the traffic they receive within the warmup window as I scale them out. However what I see is quite erratic

0 -> 1: the pod receives 100% of the traffic immediatelly (this is expected so all good)
1 -> 2: the 2nd pod receives 50% of the traffic immediatelly (this is *not* expected)
2 -> 3: the 3rd pod receives 33% of the traffic immediatelly (this is *not* expected)
3 -> 4: the 4th pod warms up over time which is expected but at the same time one of the pods receives 44% of the traffic at first and then it slowly ramps down to 25% as the new pods ramps up. This is totally unexpected.

<img width="1082" alt="Screenshot 2023-08-17 at 17 39 49" src="https://github.com/istio/istio/assets/95422414/bb00d39a-d9de-4b14-8087-5f3237a20e9b">

### Version

```Text
$ istioctl version
client version: 1.18.2
control plane version: 1.17.3
data plane version: 1.17.3 (150 proxies)
$ kubectl version --short
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.24.16-eks-2d98532
```

### Additional Information

I've filled in a report against envoy as well however since it's an istio feature also I think we should have at least one more pair of eyes in here: https://github.com/envoyproxy/envoy/issues/29008

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hobbytp** [comment]
can you check the envoy configuration has configured in client side, e.g., by using istioctl or configdump?

**Comment by palmobar** [comment]
@hobbytp from envoy's dashboard:

```
    {
     "version_info": "2023-08-14T14:19:53Z/53",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|8080||aiohttp-service.default.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|8080||aiohttp-service.default.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "default_original_port": 8080,
         "services": [
          {
           "name": "aiohttp-service",
           "host": "aiohttp-service.default.svc.cluster.local",
           "namespace": "default"
          }
         ],
         "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/destination-rule/aiohttp-service"
        }
       }
      },
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "protocol": "istio-peer-exchange"
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "tls_params": {
            "tls_minimum_protocol_version": "TLSv1_2",
            "tls_maximum_protocol_version": "TLSv1_3"
           },
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {
             "match_subject_alt_names": [
              {
               "exact": "spiffe://cluster.local/ns/default/sa/default"
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.8080_._.aiohttp-service.default.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
         }
        }
       }
      ],
      "round_robin_lb_config": {
       "slow_start_config": {
        "slow_start_window": "300s"
       }
      }
     },
     "last_updated": "2023-08-14T14:19:53.526Z"
    },
```

**Comment by ramaraochavali** [comment]
I think this is more of an envoy issue rather than Istio issue. Let us see what comes out of Envoy issue that you created.

**Comment by nezdolik** [comment]
Hi, are endpoints spread across multiple priorities in your setup? Also do you use by any chance locality weighted load balancing? (so that endpoints end up in different localities)?

**Comment by palmobar** [comment]
@hobbytp @ramaraochavali so according to findings in the [other issue](https://github.com/envoyproxy/envoy/issues/29008) the slow start feature doesn't work well with locality load balancing:

> Slow start does not work perfectly with cross priority, cross locality load balancing. [see the original comment](https://github.com/envoyproxy/envoy/issues/29008#issuecomment-1737484218)

Istio enables locality by default which is [documented here](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#:~:text=No-,localityLbSetting,-LocalityLoadBalancerSetting) but it doesn't take effect until **outlier** setting is specified in the `DestinationRule`

After setting my `DestinationRule` to the following the warmupDuration is working as expected:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
[...]
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
[...]
```

Question I have is: will disabling `localityLbSetting` in a destinationrule have any unintended consequences? My DestinationRule doesn't make any use of this setting. I think it won't since I'm not making any explicit use of it anyhow.

**Comment by ramaraochavali** [comment]
> Question I have is: will disabling localityLbSetting in a destinationrule have any unintended consequences

It does not have any unintended consequences - it just disables locality load balancer and it seems you do not need it.
