### ISSUE TITLE
How does Go project service use istio and jaeger for distributed tracing?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#46616]
hello, I need an example of Go service combined with istio for distributed tracing. I know that if you use istio for distributed tracing, you need to make some changes to the go business code, such as passing some headers and the like. But I may need a more comprehensive example to help me understand. But I searched around the Internet, and I didn't find a relatively simple example that meets the requirements.

I am now asking everyone, if you have experience in this area, can you analyze it for me. Thanks.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation gives some examples. There isn't go specifically but its pretty general to all languages, and not Isito specific so you can also find more examples around the web
