### ISSUE TITLE
Call validating webhook ......  x509: certificate has expired or is not yet valid 

### ISSUE THREAD

**Issue by mark8s** [istio/istio#46612]
Hello everyone, I have a question.

I'm having issues with what appears to be an expired istio ValidatingWebhookConfiguration ca certificate. It caused isitod to fail to start.

First the `istiod` log is as follows:

![6fcf63f78dab845b42a9bfb639b029c0](https://github.com/istio/istio/assets/47961301/cba687ad-4e82-42d4-8373-2c8d79a719c9)

`api-server` logs：

![image](https://github.com/istio/istio/assets/47961301/1aa897c8-284a-472d-9cce-0332c3e1bdee)

Judging from the above errors, they all say failed calling webhook "validation.istio.io". So it should be that the validation webhook certificate has expired.

My question now is: how do I renew the certificate of the validation webhook? Judging from the phenomenon, it seems that the validity period of the default validation webhook certificate is one year. . .

Do you know? I want help. . .

**Comment by howardjohn** [comment]
It should generate a new one each restart. Has istiod been running for >1 year?

**Comment by hzxuzhonghu** [comment]
1.9 is too old, it has been EOL. Please upgrade

**Comment by mark8s** [comment]
@hzxuzhonghu I know this version is very old, but something is not easy to upgrade, is there a way to solve this problem without upgrading?

**Comment by hzxuzhonghu** [comment]
Why does istiod liist node failed for authz?

**Comment by mark8s** [comment]
@howardjohn i dont know. Maybe it's validation webhook effect?

**Comment by mark8s** [comment]
@hzxuzhonghu  i dont know. Maybe it's validation webhook effect?

**Comment by hzxuzhonghu** [comment]
no, pilot is trying to watch Nodes, however it failed. Maybe missing clusterrole.

 `x509: certificate has expired ` is from kube-apiserver, it means the client is using an expired cert, not sure which client it is. By default, if istiod is deployed in the cluster, it communicate with kube-apiserver with a token, not cert.
