### ISSUE TITLE
Warning for MSK

### ISSUE THREAD

**Issue by Gowtham369** [istio/istio#46622]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to consume MSK logs while the POD is injected with ISTIO, it is throwing Warning:
`WARN [AdminClient clientId=adminclient-1] Connection to node -1 (b-2.taudev3use1streamline.xk2q3s.c7.kafka.us-east-1.amazonaws.com/100.110.9.228:9094) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient) `

### Version

```Text
so, the pod itself does not have any istioctl, kubetl and helm.
But this Environment exists on 1.24 k8s and Istio is 1.11.4.
Helm version is 3.6
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Istio 1.11 is EOL and this really doesn't have enough info to debug. Please upgrade and provide appropriate level of detail

**Comment by Gowtham369** [comment]
Even when having another version of ISTIO.
Have you ever come across this warning even though the MSK is set up fine, was only throwing when passed through ISTIO.
