### ISSUE TITLE
Ambient stale policies

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#46624]
This is vague but I applied a ns wide policy, then made it a workload selector NOT selecting. It was still applied until ztunnel restart..
Needs more investigation

[dump.json.txt](https://github.com/istio/istio/files/12399519/dump.json.txt)

**Comment by howardjohn** [comment]
Failed to reproduce personally. Not sure, the code looks fine as well

**Comment by keithmattix** [comment]
I wonder if ztunnel has keepalives configured correctly...if not, I can imagine one end of the connection dropping and ztunnel having no idea

**Comment by howardjohn** [comment]
oh yeah forgot about that issue. that must be it since it was from a
waypoint

**Comment by howardjohn** [comment]
Flow is `curl --> waypoint --> zt --> backend`

ZT gets a policy change and should now deny the request. But the waypoint-->ZT has a long lived connection ,so its not re-evaluated even though I am sending new `curl`s
