### ISSUE TITLE
releases: api, proxy, istio tags and branches must match

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4664]
The last api repo tag is 0.3.0

for 0.8.0 and the release-0.8 branch they must exist on all the repo which make the release

(this is probably a dup of an older issue I filled long ago)

**Comment by hklai** [comment]
@rkpagadala did you have a chance to verify?

**Comment by ldemailly** [comment]
https://github.com/istio/proxy/pull/1518#issuecomment-384068481

**Comment by rkpagadala** [comment]
adding @qiwzhang the proxy and istio repos have different versions of api. istio is leading api. Wayne will move proxy to match the version in istio repo and then move the proxy sha in istio repo. All these changes in release-0.8 branch.

**Comment by ldemailly** [comment]
thanks for the investigation, good plan, but both master and the branch, right?

**Comment by rshriram** [comment]
why is this a blocker for release? Is it going to turn of some key istio functionality? or is this just for hygiene ? If latter, its a good to have but not a must. It certainly does not stop anyone from installing or using Istio.

**Comment by ldemailly** [comment]
it's basic hygiene / software engineering, and yes to make an LTS that can be patched for bug fixes, it needs to have all the branches in order

**Comment by rshriram** [comment]
why is this a blocker for release?

**Comment by ldemailly** [comment]
because we can't make and maintain a release if we don't know what is in it or if what is in it is a mismatch between the components.

**Comment by hklai** [comment]
Fixed by https://github.com/istio/istio/pull/5314

Both proxy and istio are using API SHA 793db0cb1a2e33012166f1d6ee5918596b8199d4
