### ISSUE TITLE
istioctl proxy-status command not working

### ISSUE THREAD

**Issue by Jotheeswaran-Lakshmanan** [istio/istio#46652]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team,

We are running 3 versions of Istiod Control plane (1.15, 1.16 & 1.18) in our clusters using revision tag and we have enabled **hostNetwork=true** for istiod deployment. So we had to modify few ports used by istiod.
So once we modify **monitoringAddr** from 15014 to 15114 or any other port, we are getting an error while running istioctl proxy-status command.

**ERROR MESSAGE**: 2023-08-23T06:48:52.036368Z     error   klog    an error occurred forwarding 61563 -> 15014: error forwarding port 15014 to pod 603a37aa17fead498e0581d1677d65579ec846e494e12585de8b814f9a3a45c5, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:15014 inside namespace "603a37aa17fead498e0581d1677d65579ec846e494e12585de8b814f9a3a45c5", IPv4: dial tcp4 127.0.0.1:15014: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
Error: failure running port forward process: Get "http://localhost:61563//debug/syncz": EOF

We are not able to find any options are flags available with istioctl to change the monitoring port. Could you please let us know how to make it work, since we use this command extensively to check if our proxies are syncing 

### Version

```Text
2023-08-23T07:00:03.277753Z     error   klog    an error occurred forwarding 62990 -> 15014: error forwarding port 15014 to pod 603a37aa17fead498e0581d1677d65579ec846e494e12585de8b814f9a3a45c5, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:15014 inside namespace "603a37aa17fead498e0581d1677d65579ec846e494e12585de8b814f9a3a45c5", IPv4: dial tcp4 127.0.0.1:15014: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
client version: 1.16.0
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.15.7
istiod version: 1.16.5
istiod version: 1.16.5
istiod version: 1.18.2
istiod version: 1.18.2
istiod version: 1.18.2
data plane version: 1.16.5 (83 proxies)
---
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c3a0bd0f4d44c0f0200eef6eed403c48d99fcfa", GitTreeState:"clean", BuildDate:"2023-06-12T18:45:58Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

[bug-report.log](https://github.com/istio/istio/files/12416687/bug-report.log)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
I think currently it's assuming a fixed value 15014.

**Comment by Jotheeswaran-Lakshmanan** [comment]
so we have to run multiple versions of istio control plane with the same port? since we are using hostNetwork scheduling pods with same host port will be hard. Is there a way around?

**Comment by hanxiaop** [comment]
> so we have to run multiple versions of istio control plane with the same port? since we are using hostNetwork scheduling pods with same host port will be hard. Is there a way around?

Maybe `istioctl x ps` with similar functionality?

**Comment by Jotheeswaran-Lakshmanan** [comment]
> > so we have to run multiple versions of istio control plane with the same port? since we are using hostNetwork scheduling pods with same host port will be hard. Is there a way around?
> 
> @Jotheeswaran-Lakshmanan Maybe `istioctl x ps` with similar functionality?


Same error

./istioctl x ps
2023-08-23T09:00:18.966232Z     error   klog    an error occurred forwarding 52028 -> 15012: error forwarding port 15012 to pod 0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:15012 inside namespace "0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab", IPv4: dial tcp4 127.0.0.1:15012: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
Error: could not get XDS from discovery pod "istiod-1-15-5bd77bfb78-87x75": ADSC: failed running rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"

**Comment by Jotheeswaran-Lakshmanan** [comment]
> is `running 3 versions of Istiod Control plane` a regular status for you? Istio does not encourage such usage

Running two version is the regular state and I suppose istio supports canary deployment of control plane with revision tags and in few case we had to run 3 control planes

**Comment by hanxiaop** [comment]
> > > so we have to run multiple versions of istio control plane with the same port? since we are using hostNetwork scheduling pods with same host port will be hard. Is there a way around?
> > 
> > 
> > @Jotheeswaran-Lakshmanan Maybe `istioctl x ps` with similar functionality?
> 
> Same error
> 
> ./istioctl x ps 2023-08-23T09:00:18.966232Z error klog an error occurred forwarding 52028 -> 15012: error forwarding port 15012 to pod 0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:15012 inside namespace "0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab", IPv4: dial tcp4 127.0.0.1:15012: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found Error: could not get XDS from discovery pod "istiod-1-15-5bd77bfb78-87x75": ADSC: failed running rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"

There's a flag to specify the xds port.

**Comment by Jotheeswaran-Lakshmanan** [comment]
> > > > so we have to run multiple versions of istio control plane with the same port? since we are using hostNetwork scheduling pods with same host port will be hard. Is there a way around?
> > > 
> > > 
> > > @Jotheeswaran-Lakshmanan Maybe `istioctl x ps` with similar functionality?
> > 
> > 
> > Same error
> > ./istioctl x ps 2023-08-23T09:00:18.966232Z error klog an error occurred forwarding 52028 -> 15012: error forwarding port 15012 to pod 0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab, uid : failed to execute portforward in network namespace "host": failed to connect to localhost:15012 inside namespace "0c813b77586e4cc5329f4cc892321db4d374aa2e9169dc6b4aff356f5fe341ab", IPv4: dial tcp4 127.0.0.1:15012: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found Error: could not get XDS from discovery pod "istiod-1-15-5bd77bfb78-87x75": ADSC: failed running rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
> 
> There's a flag to specify the xds port.

Thanks, specifying xds port along with revision fixed it

./istioctl x ps -r 1-15 --xds-port 15212
NAME                                                    CLUSTER          CDS        LDS        EDS        RDS        ECDS         ISTIOD                           VERSION
bakeryapp2-deployment-2-79f5645ccc-8ltf8.bakeryapp2     ecp-weu-poc1     SYNCED     SYNCED     SYNCED     SYNCED     NOT_SENT     istiod-1-15-5bd77bfb78-qpbvl     1.15.7
bakeryapp2-deployment-74c9d998c5-2rlhw.bakeryapp2       ecp-weu-poc1     SYNCED     SYNCED     SYNCED     SYNCED     NOT_SENT     istiod-1-15-5bd77bfb78-ksbtq     1.15.7

**Comment by Jotheeswaran-Lakshmanan** [comment]
thanks for the help, will close the issue

**Comment by dharapvj** [comment]
For someone who comes searching about this later - its the `secureGRPCAddr` param value from istiod pods that we specify as `--xds-port` param to `istioctl x ps`
