### ISSUE TITLE
istio.io/istio/tests/e2e/tests/upgrade TestUpgrade Failure

### ISSUE THREAD

**Issue by hklai** [istio/istio#4666]
Maybe similar to https://github.com/istio/istio/issues/4459, TestUpgrade is failing in release qualification tests.

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/491/daily-e2e-rbac-auth-default/438/

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/491/daily-e2e-rbac-no_auth-default/465/

The only difference between these tests and the post submit tests is that they use the default tags baked in the release.

**Comment by yusuoh** [comment]
#4667

**Comment by ayj** [comment]
Closing in favor of https://github.com/istio/istio/issues/4937
