### ISSUE TITLE
update pilot for api change (destination Name->Host change)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#4668]
https://github.com/istio/api/pull/439 
implies a lot of changes in istio/istio

a lot of them are
https://github.com/istio/istio/compare/27866f85a83ae0a232651ed8c5a8b7c1b2e395d7...0c8a26e1c83bc385f3aea186429acc0b1d770d30

but there was more golden files etc... changes needed

**Comment by rshriram** [comment]
Golden files will not change. Just update clusters.go as well as the ones you have here and that should be it.

**Comment by rshriram** [comment]
Cc @ijsnellf

**Comment by ldemailly** [comment]
ps: this is holding back every other api pr propagation

**Comment by rshriram** [comment]
Thanks. but there is no other API  PR after this, that needs changes in istio/istio. So we are set. We will get to this in a couple of days unless you beat us to it and send your own PR.

**Comment by guptasu** [comment]
@rshriram @ldemailly Can we expedite this PR ? It is blocking other work inside istio/istio

**Comment by guptasu** [comment]
IMHO, we should not be renaming things like this. Instead we should add new name and then use it inside istio/istio. Eventually remove it from istio/api. Else the two closely coupled PRs should almost go next to each other within a matter of hours.

**Comment by ldemailly** [comment]
> Thanks. but there is no other API PR after this, that needs changes in istio/istio. So we are set. 

@rshriram you mean like https://github.com/istio/api/pull/441 https://github.com/istio/api/pull/417 https://github.com/istio/api/pull/442 https://github.com/istio/api/pull/443 or the other 8 open PRs in api ?

**Comment by ldemailly** [comment]
fixed by #4705
