### ISSUE TITLE
Add support to add custom ports to the istio gateway helm chart

### ISSUE THREAD

**Issue by sakirma** [istio/istio#46691]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I use the [official helm chart](https://artifacthub.io/packages/helm/istio-official/gateway) to setup a ingress gateway. The deployment template does not make it possible to add custom ports

My feature request is about making it possible to set these ports through the values I give to the helm chart.

**Describe alternatives you've considered**
Current I am using the command: 
```
kubectl patch deployments.apps -n istio-system istio-ingressgateway -p '{"spec":{"template":{"spec":{"containers":[{"name":"istio-proxy","ports":[{"containerPort":8080,"hostPort":80},{"containerPort":8443,"hostPort":443},{"containerPort":15021,"hostPort":15021}]}]}}}}'
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by rsalmond** [comment]
@sakirma It's counter-intuitive, but you don't actually need to add ports to the deployment. A container can listen on any port it wants to, and other pods in the cluster can connect to it, even if there is no `ports` section in the pod spec. See the `ports` section of the docs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core

>Not specifying a port here DOES NOT prevent that port from being exposed.

**Comment by howardjohn** [comment]
yes this is intentional so you can add ports to the service without restarting the pods

**Comment by sakirma** [comment]
Thanks a lot guys! I should have read up more about the docs 😅
