### ISSUE TITLE
Limit access to Kube Secrets

### ISSUE THREAD

**Issue by gitanuj** [istio/istio#46701]
**Describe the feature request**
Currently Istio discovery relies on [listing all kube secrets on the cluster](https://github.com/istio/istio/blob/c8e0011922eaf1328d15b47086ad77700547333c/pilot/pkg/credentials/kube/secrets.go#L90C2-L92C4). This makes it not a very attractive option to use in muti tenant deployments with strong audit requirements. If there was a way to specify namespaces filter for Kube Secrets to discovery component this issue can be solved.

**Describe alternatives you've considered**
I've tried dropping secrets access from ClusterRoles and add Role/RoleBinding for specific namespaces instead but discovery component fails to boot up.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
It is hard to apply a namespaces filter to secret watcher, we are getting secret from proxy namespace or gateway/DR namespace.

**Comment by howardjohn** [comment]
Yes, as mentioned above this is required to implement core Gateway functionality. In theory it could be scoped to a single namespace, at cost of not having properly functioning gateways.

Note you can scope the _entire_ install to a single namespace with ISTIO_WATCH_NAMESPACE. Beyond that you are probably getting into very bespoke requirements.

**Comment by satrox28** [comment]
Is it possible if istio is used by 1 namepsace to limit the secret watcher?.
