### ISSUE TITLE
Unable to route traffic to IPv4 endpoints in IPv6-only EKS environment

### ISSUE THREAD

**Issue by pseudonator** [istio/istio#46719]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In EKS IPv6-only environment, every node gets both IPv4 and IPv6 addresses.

Whats special about EKS environments when it comes to IPv4 routing from IPv6 pods ?
> Pods will perform a DNS lookup for an endpoint and, upon receiving an IPv4 “A” response, will establish a connection with the IPv4 endpoint using the IPv4 address from the host-local 169.254.172.0/22 IP range. Pod’s node-only unique IPv4 address is translated through network address translation (NAT) to the IPv4 (VPC) address of the primary network interface attached to the node. 

However, Istio doesn't send outbound traffic to these IPv4 endpoints.

This is particularly due to the way the outbound port `15001` (responsible for outbound traffic) binds to tcp6.

```
tcp6   0      0 :::15001                :::*                   LISTEN      -                   
```

One simple solution to this problem in an EKS environment would be to bind to both IPv4 and IPv6 when it comes to outbound traffic via `15001`.

[There](https://github.com/istio/istio/issues/45335) is a similar open issue for dual stack cases.

### Version

Istio:
```
1.17.5
```

Environment:
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.16-eks-2d98532
```

**Comment by mmerickel** [comment]
Running into this same issue with istio 1.18.3. Any pods that are not using istio can access IPv4 endpoints just fine through the host NAT. Is there a workaround for this?

**Comment by pseudonator** [comment]
@mmerickel Is this on EKS as well ?
Waiting for the PR to get approved to get this fixed.

**Comment by mmerickel** [comment]
Yes using EKS with 1.27. I have been trying to use `traffic.sidecar.istio.io/excludeInterfaces: v4if0` on 1.18.3 and 1.19.0 and it has not been working for me. Not sure what I'm doing wrong.

```
root@test:/# curl -6 https://icanhazip.com
<snip working ipv6 address>
root@test:/# curl -4 https://icanhazip.com
curl: (7) Failed to connect to icanhazip.com port 443 after 5 ms: Connection refused
```

**Comment by mmerickel** [comment]
Also, I have read tons of docs/issues on istio and cannot tell if ISTIO_DUAL_STACK is "expected" to be turned on for EKS with IPv6. I've tried both and don't notice a difference, and logically it doesn't seem necessary because I'm not declaring any resource in kubernetes as anything other than ipv6 family.

**Comment by pseudonator** [comment]
Not for IPv6 only clusters.

**Comment by pseudonator** [comment]
Closing as this is now merged.
