### ISSUE TITLE
error handling /istiod-default-validator, retrying (retry count: 31): webhook is not ready, retry

### ISSUE THREAD

**Issue by dabmajor** [istio/istio#46727]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have installed istiod only, in an environment with cilium. Cilium documentation states that we should set socketLB.hostNamespaceOnly=true . We have done this. We have also attempted to enable socketlb. We keep getting this same error. We also found suggestions to make sure hostNetwork=true on all istiod pods; however, this configuration does not exist in our istio helm configuration of 1.18.2.

Any thoughts on this? Other configurations which might cause this error?

```
2023-08-28T20:04:27.271923Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
2023-08-28T20:04:27.271974Z	info	validationController	validatingwebhookconfiguration istiod-default-validator (failurePolicy=Ignore, resourceVersion=10910871) is up-to-date. No change required.
2023-08-28T20:04:27.271990Z	error	controllers	error handling /istiod-default-validator, retrying (retry count: 32): webhook is not ready, retry	controller=validation


$ kubectl get --raw /api/v1/namespaces/istio-system/services/https:istiod:https-webhook/proxy/inject -v4
I0828 14:20:14.825212     712 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: Address is not allowed",
  "reason": "ServiceUnavailable",
  "code": 503
}]
Error from server (ServiceUnavailable): error trying to reach service: Address is not allowed
```

### Version

```Text
kubectl Client Version: v1.25.6-eks-48e63af
istio helm chart version 1.18.2
cilium version is 1.13.4
```

### Additional Information

we do not have istioctl installed

**Comment by dabmajor** [comment]
cilium version is 1.13.4

**Comment by dabmajor** [comment]
We fixed this by manually enabling spec.template.spec.hostnetwork=true. However, we don't see this hostnetwork option in the helm charts. Is this missing?

**Comment by zirain** [comment]
Last time, I dig a issue with this: there's a network issue between Kube-apiserve and istiod pod.

please check your network policy, especially firewall.

**Comment by dabmajor** [comment]
manually injecting hostNetwork.enabled=true into the deployment.yaml file resolved all of these issues. As this option did not exists in the values.yaml helm file

**Comment by apryiomka** [comment]
I am having the same issue: error	controllers	error handling /istio-validator-istio-system, retrying (retry count: 10): webhook is not ready, retry	controller=validation. Setting spec.template.spec.hostnetwork=true did nothing to help. Does anyone have any solution for this?

**Comment by dabmajor** [comment]
This is a slightly different issue, it is a different validator erroring.

**Comment by apryiomka** [comment]
I got both of them failing:
> error handling /istiod-default-validator, retrying (retry count: 7): webhook is not ready, retry controller=validation
and
> error handling /istio-validator-istio-system, retrying (retry count: 8): webhook is not ready, retry	controller=validation

**Comment by prasad-clouduser** [comment]
How to resolve this issue, I am also facing the same issue.

**Comment by PanOS1** [comment]
Same problem here with Cilium  1.16 and Istio  1.22.2

**Comment by kingbj940429** [comment]
I solved this.

my eks version is 1.29 and istio 1.20.

just add security rule like this.

![image](https://github.com/user-attachments/assets/3cd25dec-fac7-41ad-bca3-e66cebb216e7)

**Comment by dtwilliamsWork** [comment]
we had this issue and resolved it with this Terraform code

```
resource "aws_security_group_rule" "istio" {
  description              = "Istio"
  type                     = "ingress"
  from_port                = 15017
  to_port                  = 15017
  protocol                 = "tcp"
  source_security_group_id = module.eks.cluster_security_group_id
  security_group_id        = module.eks.node_security_group_id
}
```

**Comment by sengi** [comment]
For any other EKS + Terraform users arriving here from search engines, here's the equivalent with the more up-to-date `aws_vpc_security_group_ingress_rule` resource, which handles tagging.

```hcl
resource "aws_vpc_security_group_ingress_rule" "k8s_apiserver_to_istio_webhook" {
  tags                         = { Name = "istio-webhook" }
  description                  = "Cluster control plane calls Istio webhook"
  ip_protocol                  = "tcp"
  from_port                    = 15017
  to_port                      = 15017
  security_group_id            = module.eks.node_security_group_id
  referenced_security_group_id = module.eks.cluster_security_group_id
}
```

**Comment by nthskyradiated** [comment]
Any work around this for an on-prem cluster running on HyperV?  Been troubleshooting this for 2 weeks already.

**Comment by basti-nis** [comment]
> For any other EKS + Terraform users arriving here from search engines, here's the equivalent with the more up-to-date `aws_vpc_security_group_ingress_rule` resource, which handles tagging.
> 
> resource "aws_vpc_security_group_ingress_rule" "k8s_apiserver_to_istio_webhook" {
>   tags                         = { Name = "istio-webhook" }
>   description                  = "Cluster control plane calls Istio webhook"
>   ip_protocol                  = "tcp"
>   from_port                    = 15017
>   to_port                      = 15017
>   security_group_id            = module.eks.node_security_group_id
>   referenced_security_group_id = module.eks.cluster_security_group_id
> }

Thanks @sengi this was really helpful!

For anyone looking to integrate the rule directly into the EKS module:

```
  node_security_group_additional_rules = {
    ingress_cluster_istio_webhook = {
      description                   = "Cluster control plane calls Istio webhook"
      protocol                      = "tcp"
      from_port                     = 15017
      to_port                       = 15017
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }
```
