### ISSUE TITLE
istioctl manifest generate cannot patch top level

### ISSUE THREAD

**Issue by juliantaylor** [istio/istio#46763]
**Describe the feature request**

It appears to not be possible to patch the top level of manifests with the method describe here https://istio.io/latest/docs/setup/additional-setup/customize-installation/#patching-the-output-manifest

The patch I'd like to be able to apply is to e.g. the top level of a configmap like:

                  overlays:
                    - kind: ConfigMap
                      name: istio-cni-config
                      patches:
                      - path: ''
                        value:
                          immutable: true 

But it appears this is not possible, empty `path` is skipped, other options like `.`, `$`, `\.` do not work either.

It would be nice if this could be done, but it is very much just a nice to have.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
I think this is not supported in overlays.

**Comment by hanxiaop** [comment]
Adding the feature will involve incorporating some magic logic into the `tpath` package, similar to https://github.com/istio/istio/pull/44480/files#diff-f294054d7d235bbc3f27d26b522ec025bd2eb76f27ce9f5f6f457b854086f044R80, which is not quite maintainable. As a result, I think this feature is not planned.
