### ISSUE TITLE
istio-cni -- Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by Rachitmehrotra** [istio/istio#46764]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello team
i have tried 1.17.3 and 1.17.5  but my istio-cni daemonsets are giving warning " Readiness probe failed: HTTP probe failed with statuscode: 503 ". Though its not restating the pods but still in kubectl get events we
I have not seen any issue related to this but not sure why I am getting this readiness warning.
Is this is known issue ?

### Version

```Text
kubectl version --short
Client Version: v1.17.4
Server Version: v1.25.7
istio version 1.17.4

istioctl version:   1.11.0
```

### Additional Information

kubectl get events -n istio

==========================
LAST SEEN   TYPE      REASON             OBJECT                              MESSAGE
27m         Warning   Unhealthy          pod/istio-cni-node-2fm2x            Readiness probe failed: HTTP probe failed with statuscode: 503
46m         Warning   Unhealthy          pod/istio-cni-node-4lvzj            Readiness probe failed: HTTP probe failed with statuscode: 503
9s          Warning   Unhealthy          pod/istio-cni-node-fq48l            Readiness probe failed: HTTP probe failed with statuscode: 503
54m         Warning   Unhealthy          pod/istio-cni-node-fzmkb            Readiness probe failed: HTTP probe failed with statuscode: 503
50m         Warning   Unhealthy          pod/istio-cni-node-hgjgx            Readiness probe failed: HTTP probe failed with statuscode: 503
2s          Warning   Unhealthy          pod/istio-cni-node-lvzh9            Readiness probe failed: HTTP probe failed with statuscode: 503
47m         Warning   Unhealthy          pod/istio-cni-node-x72x9            Readiness probe failed: HTTP probe failed with statuscode: 503
49m         Warning   Unhealthy          pod/istio-cni-node-xtvcm            Readiness probe failed: HTTP probe failed with statuscode: 5
==========================================
istio-cni logs

2023-08-30T08:35:44.725283Z     info    cni     ============= End iptables configuration for blue-7959d84dd-5s294 =============
2023-08-30T08:36:00.771898Z     info    cni     istio-cni cmdAdd with k8s args: {CommonArgs:{IgnoreUnknown:true} IP:<nil> K8S_POD_NAME:client-8fd8b475b-5j4r6 K8S_POD_NAMESPACE:106893-functional-test-70704-grpc-dev K8S_POD_INFRA_CONTAINER_ID:6d79dd217f4d35ef7ff53b2bfc6ee30090dd154ed24bbea0111cf2f0263317da}
2023-08-30T08:36:00.771921Z     info    cni     ============= Start iptables configuration for client-8fd8b475b-5j4r6 =============
2023-08-30T08:36:00.771923Z     info    cni     Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
INVALID_DROP=
2023-08-30T08:36:00.771926Z     info    cni     Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020,15021,15090
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=15020
KUBE_VIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=/var/run/netns/cni-6be83786-8ed4-78b0-8537-4205e03bcfc7
CNI_MODE=true
HOST_NSENTER_EXEC=false
EXCLUDE_INTERFACES=
2023-08-30T08:36:00.771929Z     info    cni     Writing following contents to rules file: /tmp/iptables-rules-1693384560753963805.txt2692496543
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2023-08-30T08:36:00.771932Z     info    cni     Running command: iptables-restore --noflush /tmp/iptables-rules-1693384560753963805.txt2692496543
2023-08-30T08:36:00.771934Z     info    cni     Writing following contents to rules file: /tmp/ip6tables-rules-1693384560763599918.txt3528322849
2023-08-30T08:36:00.771936Z     info    cni     Running command: ip6tables-restore --noflush /tmp/ip6tables-rules-1693384560763599918.txt3528322849
2023-08-30T08:36:00.771938Z     info    cni     Running command: iptables-save
2023-08-30T08:36:00.771940Z     info    cni     Command output:

**Comment by Rachitmehrotra** [comment]
Any one can help here ?

**Comment by BuchaCyrill** [comment]
up!

**Comment by tosinolaleru** [comment]
Same issue
