### ISSUE TITLE
Promote CUSTOM Action in AuthorizationPolicy from alpha to other phase 

### ISSUE THREAD

**Issue by westwind-sc** [istio/istio#46829]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
The CUSTOM Action in AuthorizationPolicy has been alpha feature since Istio 1.12. https://istio.io/v1.12/docs/reference/config/security/authorization-policy/#AuthorizationPolicy-Action

As Istio already going to Release 1.19, could you consider promote this feature in Istio 1.19 or 1.20?
Then End user have the confident to use it in production.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by westwind-sc** [comment]
@hzxuzhonghu could you consider promote this feature in 1.20?

**Comment by hzxuzhonghu** [comment]
Thanks, we will evaluate it

**Comment by hzxuzhonghu** [comment]
We have complete [docs](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/) for ext auth, and integration test too.

The most important is we have documented external auth bete here https://istio.io/latest/docs/releases/feature-stages/#security-and-policy-enforcement

So we can simply update the document of API

**Comment by westwind-sc** [comment]
@hzxuzhonghu Nice to here that we could  simply update the document of API
The below locations seems need updated.
https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy-Action
https://github.com/istio/api/blob/91a45efbaa44cf2c4de1fbdc007fe0d8e37113d9/security/v1beta1/authorization_policy.proto#L515

> // Note: The CUSTOM action is currently an **alpha feature** and is subject to breaking changes in later versions.

           
External auth promoted to Beta in Istio 1.16. https://istio.io/latest/news/releases/1.16.x/announcing-1.16/#external-authorization-promoted-to-beta

Regarding external auth alpha since 1.12, beta since 1.16, is there any plan for the GA?

**Comment by hzxuzhonghu** [comment]
>Regarding external auth alpha since 1.12, beta since 1.16, is there any plan for the GA?

Actually, it is almost there. We have no breaking/visible change or improvement  since 1.16

**Comment by howardjohn** [comment]
This has now been promoted https://istio.io/latest/docs/releases/feature-stages/#security-and-policy-enforcement
