### ISSUE TITLE
Package Istio-Operator chart

### ISSUE THREAD

**Issue by archups** [istio/istio#46830]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As an end user, I wish to install Istio using Istio Operator using my own helm wrapper chart where I would like to define the istio-operator as helm dependency inside my wrapper Chart.yaml. 

However, at the moment the istio-operator is not released as package chart under https://istio-release.storage.googleapis.com/charts. Hence, it is not possible to use operator as a helm dependency. 

It would be nice to see the istio-operator chart under https://istio-release.storage.googleapis.com/charts for installation using helm. 

### Version

```Text
Latest version are in use.
```

Should this be reported as Feature request? Or is it fine to submit as bug?  Thanks!

**Comment by zirain** [comment]
cc @howardjohn @ericvn

**Comment by howardjohn** [comment]
This is intentionally not packaged. The operator is extremely strongly discouraged, and as part of that we are intentionally not publishing it.

**Comment by ira-gordin-sap** [comment]
@howardjohn Can you please consider to return istio-operator to https://istio-release.storage.googleapis.com/charts or to add to some another helm repo maybe?
We want to use [renovate](https://docs.renovatebot.com/#why-use-renovate) and in order it will success to find the new chart version and fetch it, it should know the helm repo.

**Comment by hanxiaop** [comment]
FYI operator is going to be deprecated soon https://github.com/istio/enhancements/issues/166.

**Comment by ira-gordin-sap** [comment]
@hanxiaop can you please remove it after the deprecation?

**Comment by howardjohn** [comment]
Sorry, I have no intention of promoting `istio-operator` in any way. Someone is free to host a community chart
