### ISSUE TITLE
postsubmits failing on istio webhook scripts not found

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4684]
Error started within the last few days, potentially during release.

snippet
```
sh: 1: /home/bootstrap/go/src/istio.io/istio/install/kubernetes/webhook-create-signed-cert.sh: not found
```

[prow example failure](https://k8s-gubernator.appspot.com/build/istio-prow/e2e-cluster_wide-auth/1271)

**Comment by cmluciano** [comment]
The script was removed in https://github.com/istio/istio/pull/4612

@yusuoh was this replaced somewhere else in helm?

**Comment by cmluciano** [comment]
we may need to update https://github.com/istio/istio.github.io/pull/1132 too if this is changed

**Comment by sdake** [comment]
@cmluciano regarding https://github.com/istio/istio.github.io/pull/1132, 0.7 of the docs repo has not branched, so the patch is valid for 0.6/0.7.  @yusuoh 's work only applies to master as istio/istio branched several weeks ago, IIUC.

It will need to change for 0.8 I suspect.

Cheers
-steve

**Comment by linsun** [comment]
@yusuoh is Upgrade test: increase retry times and add more check #4667 going to fix this issue?

**Comment by yusuoh** [comment]
@linsun Yes. #4667 should fix this issue.
