### ISSUE TITLE
Update WasmPlugin to use TargetRef instead of workloadSelector

### ISSUE THREAD

**Issue by whitneygriffith** [istio/istio#46845]
Part of #46360 
Related to #46560, #46844 

Find where workloadSelector is used (explicitly or implicitly) and add checks for the existence of a targetRef. Defaulting to the current label selector if targetRef doesn't exist for the policy.

Some things to note: 

- RBAC and policy enforcement in general is a listener concern in Envoy as seen in [listener_waypoint.go](https://github.com/istio/istio/blob/5e5abd2e99a18f0c41c4c44e8198a27756f4115f/pilot/pkg/networking/core/v1alpha3/listener_waypoint.go#L360). 
- There may be resources precomputed based on namespace or workload selectors to provide a more effective lookup in [Ambient ](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller/ambientindex.go#L58). As seen [here](https://github.com/istio/istio/blob/addf24b1179734809ab750113e4a445863007d3e/pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go#L486) for Authorization Policy
- targetRef applies to ingress gateways and waypoints
- Validation is done to ensure the policies and the targetReferent is valid

**Comment by keithmattix** [comment]
It looks like WasmPlugin currently doesn't apply to waypoints: https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L369

@howardjohn do we want to change that as part of implementing this?

**Comment by howardjohn** [comment]
Seems reasonable. Any concerns @kyessenov ?

**Comment by kyessenov** [comment]
No new concerns with ambient for Wasm.

**Comment by keithmattix** [comment]
Disregard; we add WASM elsewhere for waypoints
