### ISSUE TITLE
Create architecture doc for Istio CA

### ISSUE THREAD

**Issue by jaellio** [istio/istio#46852]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Document CA configurations, intermediate and root cert rotation workflows, and root cert detection and generation.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hanxiaop** [comment]
not stale
