### ISSUE TITLE
Use externally created service account when installing istiod using helm chart

### ISSUE THREAD

**Issue by frauniki** [istio/istio#46856]
**Describe the feature request**
Use externally created service account when installing istiod using helm chart.

**Describe alternatives you've considered**
Currently, istiod helm chart hardcoats the serviceAccountName in istiod Deployment and does not allow the use of externally created service accounts.
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L77

When using istio with some cloud providers, there are cases where you want to use externally created service accounts in istiod. (For example, AWS IRSA requires custom labeling of service accounts, so it is recommended that service accounts be created separately.)

To support these cases, I would like to be able to change whether the service account is created or not and the serviceAccountName in the istiod helm chart.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
can you achieve that with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/?

**Comment by frauniki** [comment]
Certainly a json patch would accomplish these goals.
If istio recommends this method, I will follow it.
Thank you.
