### ISSUE TITLE
Istio Install Verify fails to find NetworkAttachmentDefinition

### ISSUE THREAD

**Issue by dmosruby** [istio/istio#46859]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are using OpenShift 4.12 and using the `openshift` profile for `istioctl`.

On testing Istio 1.19, I noticed that both the `--verify` for `istioctl install` and `istioctl verify-install` fail to find the NetworkAttachmentDefinition in the default namespace.
```shell
NetworkAttachmentDefinition: istio-cni.default: the server could not find the requested resource (get networkattachmentdefinitions.k8s.cni.cncf.io istio-cni)
```

It does exist from what I can tell as intended, and I think this might be an issue of a typo rather than it missing.

The error shows `get networkattachmentdefinitions.k8s.cni.cncf.io istio-cni`, which, when I try:
```shell
$ kubectl get networkattachmentdefinitions.k8s.cni.cncf.io istio-cni
error: the server doesn't have a resource type "networkattachmentdefinitions"
```

But when I try `network-attachment-definitions`, it is present and found:
```shell
$ kubectl get network-attachment-definitions.k8s.cni.cncf.io istio-cni
NAME        AGE
istio-cni   9s
```

I'll note that the install itself fully succeeds, all pods come online, and the verify only fails on the `NetworkAttachmentDefinition` check, all others pass.

### Version

```Text
$ istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (1 proxies)

$ kubectl version --short       
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.25.8+37a9a08

$ oc version
Client Version: 4.12.13
Kustomize Version: v4.5.7
Server Version: 4.12.18
Kubernetes Version: v1.25.8+37a9a08
```

### Additional Information

One thing I tried was overriding the `values.cni.provider` to `default` instead of the OpenShift profile's `multus`. The verification did succeed then, but of course, the CNIs themselves did not work.

**Comment by hanxiaop** [comment]
It looks like `NetworkAttachmentDefinition` doesn't follow the general kind to plural pattern.

**Comment by howardjohn** [comment]
cc @jwendell
