### ISSUE TITLE
get destinationpolicy returns x509 error

### ISSUE THREAD

**Issue by romervargas** [istio/istio#4685]
Hi everyone,

I'm getting this kind of issue (x509: certificate signed by unknown authority) when I try to run: istioctl get destinationpolicy.
Basically, I'm trying to follow the Circuit Breaking guide by Istio but I'm unable. However, I'm able to apply a side car manual injection when I started the httpbin sample.

Does anybody have an idea?

Thanks in advance

**Comment by andraxylia** [comment]
@lita any idea on what can be wrong?

@romervargas please ask first in istio-users mailing list.

**Comment by romervargas** [comment]
Hi @andraxylia , thanks for your prompt response.

I've posted the same question in istio-user mailing list (https://groups.google.com/forum/#!topic/istio-users/0dw-dhrYD4M)


Thanks

**Comment by linsun** [comment]
Hi, could you give a bit more info on your setup?  I assume you have mTLS enabled and have tried to use your own certs?   Is that for ingress cert or your own CA cert?

Also, can you try the latest 0.7.1 to see if the prob exists there?

Lin
