### ISSUE TITLE
WasmPlugin to scope to specific listener

### ISSUE THREAD

**Issue by boeboe** [istio/istio#46885]
It seems WASMPlugin currently is not scoped to inbound/outbound or even a port. When we define a WASMPlugin with a workload selector, the WASM config is applied to all listeners both inbound and outbound.

Is there a way to control this and scope to specific listeners?

Referring to https://github.com/istio/istio/issues/39345 which was about both listener and route, but this issue got closed because envoy did not support route selection. That does not invalidate the other request to link it to the correct listener.

Can we extend the trafficSelector with a field that would match host_name/listeren_name?
https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#WasmPlugin-TrafficSelector

**Comment by hzxuzhonghu** [comment]
With TrafficSelector.Ports, it can be applied to specific HTTP listener. 
Yes, as per hostname, it can be extended

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by acouvreur** [comment]
I'm also in need of this.

I am currently able to do it in envoy, but this is tricky.

You need to define all your WASM Filters first and mark them all as disabled by default.
![image](https://github.com/istio/istio/assets/22034450/7e60bd6d-e117-4070-9fd4-a98fb066cae8)

And then, you need to patch each filter by its name to enable it on a specific route.
![image](https://github.com/istio/istio/assets/22034450/b375e8de-6613-435a-9021-23bde167bd8f)

I'm not even sure if the `is_optional: true` actually does something... I'm currently experimenting, so this is not really a solution.

You can check my experiments here: https://github.com/acouvreur/sablier/pull/284

---

I know we can patch the envoy config with EnvoyFilter resources, but I don't think WasmPlugin resources are created as http_filters.

If they're not, then we probably can't patch the route to activate it.

**Comment by hzxuzhonghu** [comment]
WasmPlugin can be create as either http filter or networkfilter
