### ISSUE TITLE
Use source.principal attribute instead of source.user

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4689]
Principal is more often used in security context. This is also make it consistent with the other 
attribute (request.auth.principal).

**Comment by diemtvu** [comment]
@mandarjog, do you know if we have to make any change in mixer for this, or simply change mixer client to use new attribute name?

**Comment by wora** [comment]
You probably want to speak to Envoy people and update Envoy AttributeContext to share the same design as this one.

**Comment by liminw** [comment]
Yes, we need consistent story for Istio and Envoy attributes. Currently we do not have request.auth.xxx attributes in Envoy, so it is easy to add them.

**Comment by diemtvu** [comment]
@mandarjog Please prepare mixer for the migration. I'll try to update proxy SHA tmr.

**Comment by mandarjog** [comment]
should this be this source.principal or source.workload.principal? Or is workload assumed?

@geeknoid is adding source.workload.* attributes

**Comment by geeknoid** [comment]
This should indeed be source.workload.principal as per https://github.com/istio/istio/issues/4824

**Comment by diemtvu** [comment]
We chose souce.principal to align with existing attributes. What are source.workload.* attributes for?

@wora, @liminw what do you think?

**Comment by geeknoid** [comment]
As the issue I mentioned shows, we want to rename a bunch of attributes to
clarify their purpose.

**Comment by diemtvu** [comment]
Martin, can you check with Hong in person on this? I tried to asked him to comment on this issue. On our brief chat, he thought source.principle is the right choice. Thanks.

**Comment by lei-tang** [comment]
The source.principal attribute has been added in https://github.com/istio/istio.github.io/pull/1205/, in which the source.user attribute has been marked as to be deprecated.

**Comment by yangminzhu** [comment]
@lei-tang Can we close this issue for now, or could you comment about next steps? Thank you.

**Comment by lei-tang** [comment]
@yangminzhu the issue https://github.com/istio/istio/issues/4824 tracks the latest design/discussion for the naming of the attributes. Per the latest design document (https://docs.google.com/document/d/1IcR6C7j5Vl-4Jx8ervVT4lCTBDrBgsD7Uac77K5C5h4/edit#heading=h.jtgltj1j5e1z), "source.user" will be replaced by "source.principal". The "source.user" attribute is in the Istio 0.8 release. I am not sure about the deprecation planning of the "source.user" attribute for the Istio 1.0 release, please consult with Diem and Limin.

**Comment by diemtvu** [comment]
@mandarjog, what is the procedure to remove attribute? We want to get rid of `source.user`

**Comment by diemtvu** [comment]
Should finish this post 1.0

**Comment by diemtvu** [comment]
@mandarjog @kyessenov Do you foresee any problem for stopping populating source.user now?
