### ISSUE TITLE
Expose Envoy's original_ip_detection custom_header extension

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#46914]
**Describe the feature request**

We have the problem that in our setup with Akamai as the edge server network, we cannot set a constant `numTrustedProxies` in the Istio Network Topology settings, because the number of hops that Akamai itself takes for a request is dynamic within the Akamai network. Sometimes, the XFF list contains 2, sometimes 3, sometimes 4, and sometimes up to 6 Akamai-internal IP adresses until it reaches the origin server.

I've seen that Envoy itself has an extension that can be used to read the external/original IP address from another header: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/custom_header/v3/custom_header.proto#extension-envoy-http-original-ip-detection-custom-header

Alternatively, it would be great to setup Istio (Envoy) to simply always trust the _leftmost_ XFF entry regardless of how long the XFF list actually is, since we absolutely trust the source IP (being Akamai) to give us a true XFF list (we actually use Akamai SiteShield so that we can whitelist (in an Istio AuthorizationPolicy) the source IP ranges).
Because currently, numTrustedProxies determines the entry _from the right_ of the XFF list to trust. And setting this value to a value greater than the XFF list's length avoids parsing/trusting XFF altogether, and simply uses the IP packet's remote address (as is also documented).

**Describe alternatives you've considered**

I am not sure if it is possible to use the envoy custom_header extension via an `EnvoyFilter`, because I don't think it is an actual _filter_?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kyessenov** [comment]
I'd prefer if it was using a custom header than the left most XFF - the latter is not implemented in Envoy for a good reason. This should be easy to add as an alternative to XFF detection in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Topology API.
