### ISSUE TITLE
DualStack - sds ingress QUIC integration test failure

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#46911]
### Bug Description

While enabling dual-stack for Istio integration tests, sds_ingress tests for QUIC are failing.

Failure logs : https://prow.istio.io/view/gs/istio-prow/logs/integ-ds_istio_postsubmit/1699845759966384128

### Version

```Text
$ istioctl version
client version: 1.20-alpha.f7393dd36802a2c40b4efe60895213de87badbf7
control plane version: 1.20-alpha.b52a510c0d5a8f9e5b54f8f8bb0db2f679f11c18
data plane version: 1.20-alpha.b4b2fb49082f8416cffa40f723e2293ffbdad050 (5 proxies), 1.20-alpha.b52a510c0d5a8f9e5b54f8f8bb0db2f679f11c18 (1 proxies)
```

**Comment by kfaseela** [comment]
cc @zhlsunshine

**Comment by leosarra** [comment]
I'm taking a look into this. I will update once I know more

**Comment by leosarra** [comment]
With #48334 the QUIC listeners are now fixed, tests are now enabled and working properly.
