### ISSUE TITLE
AuthorizationPolicy doesn't work with leading slash and suffix match

### ISSUE THREAD

**Issue by martin2176** [istio/istio#46910]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The auth policy does not work when there is a path specified with suffix match.
Note that I am only using one * character which as per document should work.

The below path spec does NOT work:
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /service/*health

curl --cacert feiaz-ferg-com-certs1/feiaz.ferg.com.crt https://jwt.tif.feiaz.ferg.com/service/123health
RBAC: access denied

Same auth policy with prefix match works 
The below path spec works perfectly :
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: require-jwt
  namespace: istio-system
 spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /service/health*

curl --cacert feiaz-ferg-com-certs1/feiaz.ferg.com.crt https://jwt.tif.feiaz.ferg.com/service/health123
works. 

### Version

```Text
#istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (4 proxies)
# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

### Additional Information

As per Istio doc
Rule matches requests from a list of sources that perform a list of operations subject to a list of conditions. A match occurs when at least one source, one operation and all conditions matches the request. An empty rule is always matched.

Any string field in the rule supports Exact, Prefix, Suffix and Presence match:

    Exact match: “abc” will match on value “abc”.
    Prefix match: “abc*” will match on value “abc” and “abcd”.
    Suffix match: “*abc” will match on value “abc” and “xabc”.
    Presence match: “*” will match when value is not empty.

**Comment by howardjohn** [comment]
"Any string field in the rule supports Exact, Prefix, Suffix and Presence match:".

This is none of these. This is working as intended. You can track the FR to add more matching in https://github.com/istio/istio/issues/16585
