### ISSUE TITLE
Add support to downloadIstio.sh to download either latest stable or latest pre-release

### ISSUE THREAD

**Issue by hklai** [istio/istio#4692]
With the [new versioning scheme](https://docs.google.com/document/d/1CVp6jYOAotQ9F8jfZJsHg14xNDokVRab5NlSvHdaOqg/edit#), only LTS releases will be made the "latest release" in github. Other monthly releases will remain as pre-releases. The change will take effect **after 0.8.0** which expects to be an LTS release.

With that, we have a clear distinction between the latest stable release (i.e. LTS or the follow up patches) and the latest bleeding edge monthly release. We should update scripts like [downloadIstio.sh](https://github.com/istio/istio/blob/master/downloadIstio.sh) to be able to download either based on a toggle.

**Comment by ldemailly** [comment]
You can already set an env var to download something else than the latest

ps: I thought we were table-ing this version/labeling scheme change post 1.0, we have more important things to do than break something that finally is starting to work
