### ISSUE TITLE
RequestAuthentication allows incorrectly encoded JWT (+ character at end)

### ISSUE THREAD

**Issue by martin2176** [istio/istio#46929]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If I append a "+" character at the end of a valid JWT and any number of characters after "+" , even though the JWT itself becomes incorrectly encoded , Istio Request authentication policy just ignores it and allows the JWT.
Here is the test case:

Valid JWT: Works
TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJhcGk6Ly8zZjY4ZGY4Mi04MjJiLTQxM2ItYmY0YS01Y2FjZDM0OWYyNzciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yMWM5MzE1Yi1jZGM4LTQxYzgtYjMwZC1kNGRhMmM1YTgwNGIvIiwiaWF0IjoxNjk0NDI1ODk2LCJuYmYiOjE2OTQ0MjU4OTYsImV4cCI6MTY5NDQyOTg5NiwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhVQUFBQWVmN2Via2Zkamh5ME80cUdsRjdHRG4wYjY4YTh1Y2phOExEYU1DNUFOL2lYMWtma2Q1Sm14bjlyUkpXVFJ1UzUiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiOWJlODI4ZTctOTBlMi00Y2VlLWJlZDYtMmYxYjFmMDhmYTBjIiwiYXBwaWRhY3IiOiIwIiwiZ3JvdXBzIjpbImNhZTRkMDlhLTJiYTQtNGJhYS1iMmQ2LWQ4NGViODVjOThlOSJdLCJpcGFkZHIiOiI3NS4xODMuODEuODgiLCJuYW1lIjoiZWNvbXVzZXIxIiwib2lkIjoiNTdmZDlkMmEtYWRkZS00MGZlLTgyY2UtMmM4MDhjMWYwNWQ2IiwicmgiOiIwLkFSc0FXekhKSWNqTnlFR3pEZFRhTEZxQVM0TGZhRDhyZ2p0QnYwcGNyTk5KOG5jb0FDTS4iLCJzY3AiOiJhcGkucmVhZHNjb3BlIiwic3ViIjoib2lIVk5ia3c0bGE4elF2cDZhZlN2N0NuS182X0FTUFU4OUJ3azBrWFJhSSIsInRpZCI6IjIxYzkzMTViLWNkYzgtNDFjOC1iMzBkLWQ0ZGEyYzVhODA0YiIsInVuaXF1ZV9uYW1lIjoiZWNvbXVzZXIxQG1hcnRpbjIxNzZvdXRsb29rLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImVjb211c2VyMUBtYXJ0aW4yMTc2b3V0bG9vay5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJMSExGSTdNRVIwQ3BHYTdDbTFOYUFBIiwidmVyIjoiMS4wIn0.mcL9T_6aEQX1P7FyYD4Wt2tjp6hiSgxBwbLVD-ps9VOxIQlADqRgA38vpV8Z5ODTxgGiMBRMlfGbIj2OTNR-r_2LmDssfp424mdy7vyxd1K3ukKF-tGP6ZdMwTS8Xm-Hvx5mwOAkUD2YdbBSCIe-jcKNvcEuMrSkhs4WgEvxxbKii-CfALMUdNbseJshqmS3ekla5bEEIFqnmlsLuNujqAQ-n3MvolNEc2k2tag6RPxAtBCdkkotzJxOVbv8HV6RJ29b7aoELayQSOFY1iJEg6d4uAPTSIa-T0Fd9tUXaldy0kigEaaA8bLxc3E5DbhU0F0Uks74tTgVD1_x7OQpWQ

curl  --header "Authorization: Bearer $TOKEN" --cacert feiaz-ferg-com-certs1/feiaz.ferg.com.crt https://jwt.tif.feiaz.ferg.com/hello
Hello version: v1, instance: helloworld-v1-6c7df8d8fd-drlbc

Same JWT now appended with +111 (any random character after +). The JWT becomes incorrectly encoded JWT.
Istio should have returned "Jwt payload is an invalid Base64url encoded". However Istio policy silently ignores it and allows it to go through. 

TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJhcGk6Ly8zZjY4ZGY4Mi04MjJiLTQxM2ItYmY0YS01Y2FjZDM0OWYyNzciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yMWM5MzE1Yi1jZGM4LTQxYzgtYjMwZC1kNGRhMmM1YTgwNGIvIiwiaWF0IjoxNjk0NDI1ODk2LCJuYmYiOjE2OTQ0MjU4OTYsImV4cCI6MTY5NDQyOTg5NiwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhVQUFBQWVmN2Via2Zkamh5ME80cUdsRjdHRG4wYjY4YTh1Y2phOExEYU1DNUFOL2lYMWtma2Q1Sm14bjlyUkpXVFJ1UzUiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiOWJlODI4ZTctOTBlMi00Y2VlLWJlZDYtMmYxYjFmMDhmYTBjIiwiYXBwaWRhY3IiOiIwIiwiZ3JvdXBzIjpbImNhZTRkMDlhLTJiYTQtNGJhYS1iMmQ2LWQ4NGViODVjOThlOSJdLCJpcGFkZHIiOiI3NS4xODMuODEuODgiLCJuYW1lIjoiZWNvbXVzZXIxIiwib2lkIjoiNTdmZDlkMmEtYWRkZS00MGZlLTgyY2UtMmM4MDhjMWYwNWQ2IiwicmgiOiIwLkFSc0FXekhKSWNqTnlFR3pEZFRhTEZxQVM0TGZhRDhyZ2p0QnYwcGNyTk5KOG5jb0FDTS4iLCJzY3AiOiJhcGkucmVhZHNjb3BlIiwic3ViIjoib2lIVk5ia3c0bGE4elF2cDZhZlN2N0NuS182X0FTUFU4OUJ3azBrWFJhSSIsInRpZCI6IjIxYzkzMTViLWNkYzgtNDFjOC1iMzBkLWQ0ZGEyYzVhODA0YiIsInVuaXF1ZV9uYW1lIjoiZWNvbXVzZXIxQG1hcnRpbjIxNzZvdXRsb29rLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImVjb211c2VyMUBtYXJ0aW4yMTc2b3V0bG9vay5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJMSExGSTdNRVIwQ3BHYTdDbTFOYUFBIiwidmVyIjoiMS4wIn0.mcL9T_6aEQX1P7FyYD4Wt2tjp6hiSgxBwbLVD-ps9VOxIQlADqRgA38vpV8Z5ODTxgGiMBRMlfGbIj2OTNR-r_2LmDssfp424mdy7vyxd1K3ukKF-tGP6ZdMwTS8Xm-Hvx5mwOAkUD2YdbBSCIe-jcKNvcEuMrSkhs4WgEvxxbKii-CfALMUdNbseJshqmS3ekla5bEEIFqnmlsLuNujqAQ-n3MvolNEc2k2tag6RPxAtBCdkkotzJxOVbv8HV6RJ29b7aoELayQSOFY1iJEg6d4uAPTSIa-T0Fd9tUXaldy0kigEaaA8bLxc3E5DbhU0F0Uks74tTgVD1_x7OQpWQ+11111

curl  --header "Authorization: Bearer $TOKEN" --cacert feiaz-ferg-com-certs1/feiaz.ferg.com.crt https://jwt.tif.feiaz.ferg.com/hello              Hello version: v1, instance: helloworld-v1-6c7df8d8fd-drlbc

If I don't put a "+" sign then JWT verification fails. This fails as expected.

TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJhcGk6Ly8zZjY4ZGY4Mi04MjJiLTQxM2ItYmY0YS01Y2FjZDM0OWYyNzciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yMWM5MzE1Yi1jZGM4LTQxYzgtYjMwZC1kNGRhMmM1YTgwNGIvIiwiaWF0IjoxNjk0NDI1ODk2LCJuYmYiOjE2OTQ0MjU4OTYsImV4cCI6MTY5NDQyOTg5NiwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhVQUFBQWVmN2Via2Zkamh5ME80cUdsRjdHRG4wYjY4YTh1Y2phOExEYU1DNUFOL2lYMWtma2Q1Sm14bjlyUkpXVFJ1UzUiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiOWJlODI4ZTctOTBlMi00Y2VlLWJlZDYtMmYxYjFmMDhmYTBjIiwiYXBwaWRhY3IiOiIwIiwiZ3JvdXBzIjpbImNhZTRkMDlhLTJiYTQtNGJhYS1iMmQ2LWQ4NGViODVjOThlOSJdLCJpcGFkZHIiOiI3NS4xODMuODEuODgiLCJuYW1lIjoiZWNvbXVzZXIxIiwib2lkIjoiNTdmZDlkMmEtYWRkZS00MGZlLTgyY2UtMmM4MDhjMWYwNWQ2IiwicmgiOiIwLkFSc0FXekhKSWNqTnlFR3pEZFRhTEZxQVM0TGZhRDhyZ2p0QnYwcGNyTk5KOG5jb0FDTS4iLCJzY3AiOiJhcGkucmVhZHNjb3BlIiwic3ViIjoib2lIVk5ia3c0bGE4elF2cDZhZlN2N0NuS182X0FTUFU4OUJ3azBrWFJhSSIsInRpZCI6IjIxYzkzMTViLWNkYzgtNDFjOC1iMzBkLWQ0ZGEyYzVhODA0YiIsInVuaXF1ZV9uYW1lIjoiZWNvbXVzZXIxQG1hcnRpbjIxNzZvdXRsb29rLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImVjb211c2VyMUBtYXJ0aW4yMTc2b3V0bG9vay5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJMSExGSTdNRVIwQ3BHYTdDbTFOYUFBIiwidmVyIjoiMS4wIn0.mcL9T_6aEQX1P7FyYD4Wt2tjp6hiSgxBwbLVD-ps9VOxIQlADqRgA38vpV8Z5ODTxgGiMBRMlfGbIj2OTNR-r_2LmDssfp424mdy7vyxd1K3ukKF-tGP6ZdMwTS8Xm-Hvx5mwOAkUD2YdbBSCIe-jcKNvcEuMrSkhs4WgEvxxbKii-CfALMUdNbseJshqmS3ekla5bEEIFqnmlsLuNujqAQ-n3MvolNEc2k2tag6RPxAtBCdkkotzJxOVbv8HV6RJ29b7aoELayQSOFY1iJEg6d4uAPTSIa-T0Fd9tUXaldy0kigEaaA8bLxc3E5DbhU0F0Uks74tTgVD1_x7OQpWQ11111

curl  --header "Authorization: Bearer $TOKEN" --cacert feiaz-ferg-com-certs1/feiaz.ferg.com.crt https://jwt.tif.feiaz.ferg.com/hello              Jwt verification fails

**Summary:**
A + sign followed by characters at end of a valid JWT makes the JWT incorrectly encoded. However  Istio request auth policy doesn't fail it as incorrectly encoded and allows it to go through. It should have given "Jwt payload is an invalid Base64url encoded" or something indicating it is a wrongly encoded jwt

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (4 proxies)
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

### Additional Information

I think the policy should do a verification if JWT is correctly encoded. If encoding is wrong, it should reject it right away

**Comment by howardjohn** [comment]
Interesting. I wonder if this is some obscure part of the spec or an implementation issue

Is there a reason you are doing this? Trying to understand if this is "really weird edge case we stumbled upon" or "we actually have requests like this an need a certain behavior"?

PS: if your answer is security sensitive please email it to the security group rather than publicly comment :-)

**Comment by howardjohn** [comment]
In an abundance of caution I think this should be discussed privately first. Please find me on slack or the PSWG email (https://github.com/istio/istio/security/policy) if you want to discuss more
