### ISSUE TITLE
ConsistentHashLB: Passive cookie hashing mode

### ISSUE THREAD

**Issue by rudmsa** [istio/istio#46922]
**Describe the feature request**

We have a following setup: edge istio ingress gateway which routes requests to an application using Cookie header. The application cheks if the cookie header is set and if not - generates its value based on request headers and some business info.
DestinationRule for the host looks like this:

```
spec:
  exportTo:
  - '*'
  host: my-example-app
  ...
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: u
          ttl: 0s
```

I have encountered a problem with the setup: ingress gateway generates and mixes in `u` cookie on its own and then transmits the updated response. During the subsequent requests the app rejects some of the new requests because of a malformed cookie `u` (it contains data generated by envoy).

This behaviour is covered by the envoy docs (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-cookie) - `ttl` field enables cookie generation.

The same doc specifies a passive cookie hashing mode (Envoy takes a cookie that’s present in the cookies header and hashes on its value, but never generates it by itself). The strange thing is - this mode is forbidden by istio.

If I try to remove the `ttl` field - validation error occurs: https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L1455
It's strange, because from the looks of it: passive cookie hashing is already supported - https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L1295

**Describe alternatives you've considered**

I'm not sure why `ttl` field is required for `consistentHash.httpCookie` configuration. Am I missing something?
Please consider relaxing validation -- passive cookie hashing is a valid case and the code for the configuration is already present.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
IIRC, ttl validate can be loosened

**Comment by ramaraochavali** [comment]
We need to https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto change this as well.

**Comment by hzxuzhonghu** [comment]
assign @rudmsa

**Comment by huanghuangzym** [comment]
will this change backport to istio 1.18?
