### ISSUE TITLE
Pods not emitting standard Istio metrics in Rancher Istio v1.16.3

### ISSUE THREAD

**Issue by praseed44** [istio/istio#46926]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I have Rancher Istio v1.16.3 installed into an AKS cluster v1.25.6. Pods are having istio-proxy sidecars automatically injected and the necessary Prometheus annotations are available in the pods. Also, the overlay file has the configuration enablePrometheusMerge: true. However, I don't see any standard metrics (for eg: istio_requests_total metric) available in the metric endpoint of the proxy (http://localhost:15020/stats/prometheus).

```
 prometheus.io/path: /stats/prometheus
 prometheus.io/port: 15020
 prometheus.io/scrape: true
```

This was working with similar configuration in the upstream istio version v.1.14.4. Please share your thoughts on what could be missing here to enable the pod to emit istio_requests_total metric.

However, the **envoy_*** metrics and **istio_agent*** metrics are getting generated. Can you please help to understand what is required to get standard metrics emitted from proxy.

Looks like the stats envoy filters are not getting created with Rancher Istio installation. Is this required to get the standard metrics emitted?

Thanks,
Praseed

### Version

```Text
$ istioctl-1-16-3 version
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (85 proxies)

$ kubectl version --short
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.6
```

**Comment by zirain** [comment]
do you have real taffic to that pod?

**Comment by zirain** [comment]
can you share config dump and `istioctl x es <pod_name> -o prometheus`

**Comment by praseed44** [comment]
> istioctl x es <pod_name> -o prometheus

Please find attached the envoy stats for the pod.

[httpbin-envoy-stats.txt](https://github.com/istio/istio/files/12577200/httpbin-envoy-stats.txt)

**Comment by zirain** [comment]
can you share the output of `istioctl pc all <pod_name> -oyaml`?

**Comment by praseed44** [comment]
> istioctl pc all <pod_name> -oyaml

Attached.

[httpbin-proxy-config.txt](https://github.com/istio/istio/files/12577292/httpbin-proxy-config.txt)

**Comment by zirain** [comment]
```
cat httpbin-proxy-config.txt | grep istio.stats
        name: envoy.filters.http.istio_stats
        name: envoy.filters.network.istio_stats
```

there's no istio stats filter, please check you configuration.
did you enable telemetryv2?

**Comment by praseed44** [comment]
> 



> ```
> cat httpbin-proxy-config.txt | grep istio.stats
>         name: envoy.filters.http.istio_stats
>         name: envoy.filters.network.istio_stats
> ```
> 
> there's no istio stats filter, please check you configuration. did you enable telemetryv2?

@zirain - thank you for that hint. I have enabled telemetry but not the v2 in the chart. After enabling the telemetryv2, the stats filters are created in the cluster and I see the standard metrics being emitted now.

telemetry:
  enabled: true
  v2:
    enabled: true

`istio_requests_total{response_code="200",reporter="destination",source_workload="fortio-deploy",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/default",source_app="fortio",source_version="unknown",source_cluster="Kubernetes",destination_workload="httpbin",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/httpbin",destination_app="httpbin",destination_version="v1",destination_service="httpbin.default.svc.cluster.local",destination_service_name="httpbin",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="fortio",destination_canonical_service="httpbin",source_canonical_revision="latest",destination_canonical_revision="v1"} 1000`

Many thanks for the help, much appreciated!
