### ISSUE TITLE
Istio Basic Auth

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#4693]
Basic auth and whitelisting on the ingress

**Comment by mandarjog** [comment]
I have this prototyped in 3 ways.

1. Use lua injected filter https://github.com/mandarjog/istioluawebhook
2. nginx ingress with a single backend to --> istio-ingress. Istio-ingress is deployed in ClusterIP.
2a. Instead of using full nginx ingress, use a fronting nginx that delegates to local istio-ingress.
3. Use nginx ingress that delegates to a local istio sidecar. 

4. Use mixer basic auth adapter

**Comment by sakshigoel12** [comment]
Per customer they don't want to use nginx and prefer option 4.

**Comment by cmeyertons** [comment]
this is the one thing holding me back from going full istio ingressing as we need a low effort mechanism to protect lower envs + not ready features

**Comment by douglas-reid** [comment]
@mandarjog what is the status of this?

**Comment by yangminzhu** [comment]
@sakshigoel12 @cmeyertons What about using Istio RBAC on ingress? This will be supported in Istio 1.2, you can write the [ServiceRole](https://istio.io/docs/concepts/security/#servicerole)/[ServiceRoleBinding](https://istio.io/docs/concepts/security/#servicerolebinding) on the ingress gateway to enforce access control. Would you mind to clarify a little bit about what kind of access control you want to enforce on ingress? 

Is it based on HTTP/TCP request for source IP, peer certificate or JWT token? (These are supported in the ServiceRole/ServiceRoleBinding)

/cc @liminw

**Comment by ssuchter** [comment]
What is the criteria that makes us put this one as P0? It seems questionable.

**Comment by chris-ng-scmp** [comment]
what is the status of this?

**Comment by dweidenfeld** [comment]
Any updates?

**Comment by cpick** [comment]
This would still be very useful.

**Comment by chris-ng-scmp** [comment]
Yes, this is an important feature

**Comment by cvmmojo** [comment]
+1

**Comment by pablolibo** [comment]
+1 too

**Comment by rainmetersjtu** [comment]
+1 any new info

**Comment by mandarjog** [comment]
I am adding to as an intern project for Summer 2020.

**Comment by incfly** [comment]
What's the scope of this bug? https://istio.io/docs/tasks/security/authorization/authz-ingress/ this is now well supported. We do we need beyond standard istio authn and authz support on gateway?

@yangminzhu @mandarjog

**Comment by mandarjog** [comment]
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by antonvlassov** [comment]
Hello, do you have any updates on this? Support Basic Authentication on Istio Gateway, validating incoming request against credentials stored in k8s secret? Is will be very helpful.

Thanks

**Comment by bianpengyuan** [comment]
Implementation is ongoing to add WebAssembly based basic auth extensions: https://github.com/istio/proxy/pull/2954

**Comment by douglas-reid** [comment]
With the basic auth extension now merged, can we close this issue?

**Comment by bianpengyuan** [comment]
I will close this once guide is available, and I will work on that.

**Comment by shadiramadan** [comment]
Any updates on a guide @bianpengyuan ?

**Comment by aaaaahaaaaa** [comment]
Has the feature been released already?

**Comment by shadiramadan** [comment]
From Istio's Slack:

> Peter Bian  5 days ago

> We have a basic auth Wasm filter implementation, but we don't have a good story yet about how to distribute that to the proxy. I will discuss with extension folks about whether and how are we going to document it in 1.8

**Comment by mirobertod** [comment]
I see the version 1.8 has been released, but I don't see any mention about the basic auth in the release announcements. (https://istio.io/latest/news/releases/1.8.x/announcing-1.8/)

Any news about that?

Thanks

**Comment by mbfmbf** [comment]
is there any news about this feature?

**Comment by bianpengyuan** [comment]
Sorry for the delay, a bit of update: 1.9 is going to introduce a way to reliably deliver Wasm modules to the proxy. With that we should be able to reliably apply basic auth Wasm filter. Will add the doc link there and close this issue once 1.9 is out. Thanks!

**Comment by mbfmbf** [comment]
@bianpengyuan, would it be possible to have some docs or examples to configure basic authentication in version 1.9 ?

**Comment by bianpengyuan** [comment]
Yeah the doc is wip: https://github.com/istio/istio.io/pull/8918

**Comment by mbfmbf** [comment]
@bianpengyuan thanks,
now, I have the 401 status, but I don't have the popup that asks for authentication with the user / pass

**Comment by bianpengyuan** [comment]
@mbfmbf Thanks for trying out! 

> but I don't have the popup that asks for authentication with the user / pass

it should be fixed by https://github.com/istio-ecosystem/wasm-extensions/pull/48. I will release a new version of basic auth module and update the doc after the fix is merged.

**Comment by bianpengyuan** [comment]
I will close this issue as a Wasm based basic auth solution has been documented at https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/ and https://github.com/istio-ecosystem/wasm-extensions/tree/master/extensions/basic_auth. Please be aware of a known issue with Wasm plugin reconfiguration https://github.com/istio/istio/issues/29843, which will be fixed at 1.9.x.

**Comment by aaaaahaaaaa** [comment]
Quite verbose but glad to see the functionality there :)

**Comment by getvivekv** [comment]
Has anyone had luck successfully configuring this for basic authentication?

**Comment by noman1897** [comment]
Hi @getvivekv,

yes,i tested the config with this repo https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/ and it worrks, i was able to change the uri to protect with basic auth and also the user&password config in the secondo yaml artifact and it works.

A small note: in the https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/ there is an error, you need to correct the uri in the **basic-auth-config** (the uri to download the correct release.)

I replaced it with: 

              code:
                 remote:                   
                   http_uri:
                     uri: https://github.com/istio-ecosystem/wasm-extensions/releases/download/1.9.2/basic-auth.wasm

**Comment by mandarjog** [comment]
@noman1897 thanks for trying it out.
Can you send a PR to the istio.io docs site with the above fix to make it clear that you need to update the url with the release designator?

thanks!

**Comment by noman1897** [comment]
@mandarjog i created an issue as the point need to be discussed: https://github.com/istio/istio.io/issues/10094#issue-948829979

**Comment by ericvn** [comment]
The link specified in the documents is generated from https://github.com/istio-ecosystem/wasm-extensions/releases/download/{{< istio_version >}}.0/basic-auth.wasm where istio_version is 1.10, 1.9, etc. at the time this page was done, there was discussion that there would always be a .0 so the author coded it up that way.

**Comment by 0width** [comment]
this way is working
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sleep
spec:
  hosts:
  - sleep.local.k8s
  gateways:
    - sleep
  http:
  - match:
    - uri:
        exact: /sleep
      headers:
        Authorization:
          exact: "Basic YWRtaW46MTIzNDU2"
    route:
      - destination:
          host: sleep
          port:
            number: 5000
    timeout: 3s
  - match:
    - uri:
        exact: /sleep
    directResponse:
      status: 401
    headers:
      response:
        set:
          Www-Authenticate: 'Basic realm="Authentication Required"'
```

**Comment by BlackCheshire** [comment]
Hi everyone! If you need to close the entire domain, here is an example.

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-ui
  namespace: kafka-dev
spec:
  hosts:
  - "kafka-ui-dev.example.com"
  gateways:
  - gateway-kafka-ui-dev
  http:
  - match:
    - uri:
        prefix: "/"
      headers:
        Authorization:
          exact: "Basic YWRtaW46MTIzNDU2"
# YWRtaW46MTIzNDU2 - its base64 encode admin:123456
    route:
      - destination:
          host: kafka-ui
          port:
            number: 80
    timeout: 3s
  - match:
    - uri:
        prefix: "/"
    directResponse:
      status: 401
    headers:
      response:
        set:
          Www-Authenticate: 'Basic realm="Authentication Required"'
