### ISSUE TITLE
Mixer Basic Auth adapter

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#4695]
Mixer should have a `http basic auth` adapter that is capable of using  `htpasswd` file.

In the future this should support ldap auth as well.

Mixer considerations
Mixer must return grpc.UNAUTHENTICATED  which proxy should turn into a 401.
denier already supports setting specific status, so it is easy to test.

Mixer dispatches adapters in parallel.
The error code of the first adapter to complete its work becomes the error code of Mixer.check, so this is non-deterministic. If another adapter fails with a different error, proxy will get that as the error.

**Comment by mandarjog** [comment]
@stensson  @staffansvensson this issue is tracking basic auth.

**Comment by brian-avery** [comment]
Is this still available? I'd love to pick it up.

**Comment by mandarjog** [comment]
Hi Brian, yes this is very much still available.
Please send PR.

**Comment by sapien99** [comment]
Guys, ist that still in the forge? We built an authentication gateway which is capable of doing server/path protection with htpasswd files. Its implemented in go and integrated into istio as a ext-auth EnvoyFilter. If its ok for you we would gladly share the code

**Comment by mandarjog** [comment]
It would be great if you package that code as an OOP mixer adapter. Since this is a generic adapter we would put it in the main Istio repo.

**Comment by sapien99** [comment]
@mandarjog:  perfect, thanks!. We implemented it as just a generic service because we run it also with nginx-ingress-controller in the switchover phase from ingress to istio ;-) Will try to bring it in the mixer OOP adapter format

**Comment by sapien99** [comment]
does anybody can give me a hint on how to set response headers in an authorization adapter? I would like to send the www-authenticate header together with the 401 when the request is denied

**Comment by brian-avery** [comment]
@sapien99 Not sure of the team's feeling on third party libraries or if it's something useful to you, but I extended the following library with support for most of the basic auth algorithms that I could find: https://github.com/brian-avery/go-htpasswd.

As far as returning responses, I think Mixer is just looking for a grpc.UNAUTHENTICATED response and it will look at the results of all of the adapters it receives responses from collectively to see if anything is succesful. 

return &v1beta1.CheckResult{
		Status:        status.New(rpc.UNAUTHENTICATED),
		ValidDuration: ValidDuration,
		ValidUseCount: ValidUseCount,
}

**Comment by sapien99** [comment]
Hey @brian-avery, 
already using your awesome lib for the "standalone" variant we run as an ext-auth EnvoyFilter ;-) For me it makes sense to use it also there. The only thing i have to discover is if its possible to use go-htpasswd also on a list of strings instead of a file (i get the stringlist from the adapter-config, in the standalone variant i use k8s-secrets which works perfect with your lib)

Regarding the response: i already return 401 - the problem is that a client requested to see the basic-auth dialog in his browser - which requires the www-authenticate header unfortunately....

**Comment by sapien99** [comment]
@brian-avery Stupid me, found the Accept* functions :-)

**Comment by StaffanSvensson-playtech** [comment]
Any new on this sapien99? Looks pretty cool

**Comment by sapien99** [comment]
Hey StaffanSvensson-playtech, unfortunately had a busy start in the new year. Still working on understanding how to do the build with the istio core and doing testcoverage.

In the meantime i can post an envoyfilter providing the same functionality but using a configmap (to store its configuration) and a secret (to store the htpasswd files) if it helps. Load-tested with 10k req/s in our company. Its more or less the predecessor of the adapter - and works until i manage to finish it ;-) If somebody is interested i can put it in a github repo

**Comment by StaffanSvensson-playtech** [comment]
@sapien99 That would be amazing if you could :) 👍

**Comment by Disturbing** [comment]
How's it going so far?

**Comment by muhlba91** [comment]
@sapien99 we are needing such an authentication mechanism as well. it would be amazing if you could post an example of your working filter configuration in a repo to have a work-around for this issue until it has been implemented. :)

**Comment by Disturbing** [comment]
We got it working at kintohub.com with a nginx sidecar. I'll have the team
post the work-around that we did in the next few weeks.

**Comment by bchase2ndwatch** [comment]
Is this still on target for 1.3?

**Comment by gargnupur** [comment]
@Disturbing : Would you guys be able to post the work-around?

**Comment by Disturbing** [comment]
Yes, I’ll have the team post a blog post sometime this month. And also just
something a bit more raw here soon

**Comment by bappr** [comment]
@gargnupur FYI we are running Istio on Kubernetes.
The workaround is not very sexy but it works, we are exposing nginx with basic auth as a side car of the main container/application and using environment variable with `envsubst` to configure it.

Here is our nginx conf
```
server {
    listen       ${NGINX_PORT};
    server_name  localhost;

    location / {
      proxy_pass http://localhost:${TARGET_PORT}/;

      auth_basic           "Basic Authentication";
      auth_basic_user_file ${HTPASSWORD};
    }
}
```

And the command to start the container

```
"htpasswd -bc $HTPASSWORD $USERNAME $PASSWORD && envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```

**Comment by saksmt** [comment]
Any progress on this?

**Comment by mandarjog** [comment]
Reopen, adapter hack candidate
