### ISSUE TITLE
don't trigger pilot full push for K8s service with "networking.istio.io/exportTo: ~" annotation

### ISSUE THREAD

**Issue by fatedier** [istio/istio#46950]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I use `networking.istio.io/exportTo: "~"` annotation to completely hide certain K8s Services from Istio.

However, I noticed that changes to these Services or to the pods of headless services will trigger a full push by Pilot.

Can we ignore these service events directly without triggering a full push?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Sounds reasonable, be careful to processing exportTo annotation changing  to `~`
