### ISSUE TITLE
Grafana pod is not starting on OCP in Istio 1.19

### ISSUE THREAD

**Issue by FilipB** [istio/istio#46974]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

With Istio 1.19 the grafana addon pod is not starting because of:
`Error creating: pods "grafana-7bd5db55c4-" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/grafana]: Forbidden: seccomp may not be set, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{472}: 472 is not an allowed group, provider restricted-v2: .containers[0].runAsUser: Invalid value: 472: must be in the ranges: [1000680000, 1000689999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]`

This issue is not visible in Istio 1.18.2.
anyuid SCC are set correctly and other pods in istio-system namespace are running with anyuid SCC fine. Grafana pod starts only after adding privileged SCC - `oc adm policy add-scc-to-group privileged system:serviceaccounts:istio-system`

### Version

```Text
Client Version: 4.13.2
Kustomize Version: v4.5.7
Server Version: 4.13.9
Kubernetes Version: v1.26.6+6bf3f75

client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (2 proxies)
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/12597285/bug-report.tar.gz)

**Comment by zirain** [comment]
this seems some limitation from OCP, not a related to istio.

**Comment by howardjohn** [comment]
Grafana is not part of Istio, either. Its just a sample of how to run it.
