### ISSUE TITLE
Waypoint proxy can not enforce Authorization policy `source.ipBlocks`

### ISSUE THREAD

**Issue by saiskee** [istio/istio#46982]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Given the following Authorization Policy:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: accesspolicy-ratings-9080-ratin-572d748716e55114a4a47e8e657a131
  namespace: bookinfo
spec:
  rules:
  - from:
    - source:
        ipBlocks:
        - 10.244.2.18
        principals:
        - cluster.local/ns/bookinfo/sa/bookinfo-productpage
    to:
    - operation:
        paths:
        - /ratings*
        ports:
        - "9080"
  selector:
    matchLabels:
      istio.io/gateway-name: bookinfo-ratings
```
That goes through a waypoint for the bookinfo-ratings service, the waypoint always denies any request here because of the sourceIP requirement here. Envoy sees the sourceIP as `envoy://internal_client_address/` rather than the actual source pod IP, most likely because of HBONE.

```log
debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:114	checking request: requestedServerName: , sourceIP: envoy://internal_client_address/, directRemoteIP: envoy://internal_client_address/, remoteIP: envoy://internal_client_address/,localAddress: 10.96.85.21:9080, ssl: none, headers: ':authority', 'ratings:9080'
':path', '/ratings/1'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.83.1-DEV'
'accept', '*/*'
'x-forwarded-proto', 'http'
'x-request-id', 'ff12312f-2d78-47e6-861c-c640722f0ed6'
, dynamicMetadata: 	thread=28
2023-09-13T19:56:14.324057Z	debug	envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:158	enforced denied, matched policy none	thread=28
2023-09-13T19:56:14.324067Z	debug	envoy http external/envoy/source/common/http/filter_manager.cc:953	[Tags: "ConnectionId":"129","StreamId":"9101893357070198794"] Preparing local reply with details rbac_access_denied_matched_policy[none]	thread=28
2023-09-13T19:56:14.324084Z	debug	envoy http external/envoy/source/common/http/filter_manager.cc:995	[Tags: "ConnectionId":"129","StreamId":"9101893357070198794"] Executing sending local reply.	thread=28
```

If I were to remove the sourceIP requirement from the AuthorizationPolicy, the request goes through.

### Version

```Text
`master`
```

**Comment by hzxuzhonghu** [comment]
It has not been implemented, @keithmattix is working on supporting it with TargetRef

**Comment by keithmattix** [comment]
Hmm I'm not sure if targetRef fixes this. Because of the internal listener redirection we do for CONNECT, the source IP gets obfuscated to the point where policy doesn't seem to be working

**Comment by ilrudie** [comment]
> Because of the internal listener redirection we do for CONNECT, the source IP gets obfuscated to the point where policy doesn't seem to be working

That's my take on it too. I'm not familiar enough with the details of how we implemented this to know if we're able to save those details but aren't using them yet or they're actually lost.

**Comment by kyessenov** [comment]
I think we can forge source address, we already forge destination address in the internal listener.

**Comment by linsun** [comment]
Would sandwich help here?  @kyessenov i think you did some prototype on it before?

**Comment by kyessenov** [comment]
It was left unimplemented and easy to fix. More important is to design a solution that doesn't require source IP spoofing from ztunnel. That hurts performance because tunnels cannot be shared.
