### ISSUE TITLE
Istio NLB security groups

### ISSUE THREAD

**Issue by pt20223** [istio/istio#46999]
**Describe the feature request**
According to this https://aws.amazon.com/blogs/containers/network-load-balancers-now-support-security-groups/, NLBs have ability to attach security groups using the "service.beta.kubernetes.io/aws-load-balancer-security-groups" annotation.  Attempting to use that with Istio created NLB service istio-ingressgateway with annotation "service.beta.kuberenetes.io/aws-load-balancer-type": "nlb" does not attach any security groups, guessing cause controller does not recognize this.

This feature apparently exists for AWS Load Balancer Controller as mentioned in article above, can this be added for Istio?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Istio does not interact with AWS or other clouds directly. We provide mechanisms to add annotations. If the annotations are not handle by the AWS that is an AWS issue, nothing Istio can or will do
