### ISSUE TITLE
Whether the from attribute of the AuthorizationPolicy resource can support filtering and allowing traffic based on the label.

### ISSUE THREAD

**Issue by ZhangSetSail** [istio/istio#47008]
Whether the from attribute of the AuthorizationPolicy resource can support filtering and allowing traffic based on the label.
Because the ip of the pod will change after restarting, the only certainty is that the label has been.

**Comment by hzxuzhonghu** [comment]
Why do you use ip auth, if the allowed clients are in the mesh,  Source.Principals can be used instead.
