### ISSUE TITLE
Differing auto-injector configurations 

### ISSUE THREAD

**Issue by Stono** [istio/istio#4703]
Hey, 
@nmittler has recently done https://github.com/istio/istio/pull/4569 which adds the `-n` flag, which resolves https://github.com/istio/istio/issues/3514 which is awesome however when this gets released, it'll cause a problem.

At a high level the `-n` flag needs to be passed to the init proxy container, only for certain workloads (in our case, our multiple nginx deployments).  However the configuration for the istio-proxy comes from
We make use of the pod auto-injection feature, which uses the config in `istio-inject` for _all_ deployments.

I initially started to think about ways we can work around this, for example - disabling auto injection on the nginx controllers and checking in the injection config specific to that repo.  However, as this repo is used on some non-istio clusters too we'll end up with conditional logic in the helm chart which I do try to avoid.  Also, it creates another point which we have to edit as part of an istio upgrade (also, not great).

When I thought about it more, it actually feels to me like using flags in this manner is what is creating the problem and instead why don't we:

**Have istio-proxy read from environment variables**
So instead of using `-n`, why not have `ISTIO_ENABLE_INGRESS_MODE`.  This would allow you to use the name auto-injector template but "tweak" it for the specific use case in the `deployment.yaml` using environment variables.

**Have istio-proxy query annotations**
As above, but using the deployments annotations instead just like we do with mtls exclusions `auth.istio.io/8000: NONE`

There are other flags that fall into this bucket for us, both `--includeIPRanges` and `--excludeIPRanges` are things that we would ideally like to tweak for individual deployments, but still make use of the auto injector.

Thoughts?

**Comment by nmittler** [comment]
Yup, definitely on my radar ... The next step is to make this work for auto-injection.

@ayj any thoughts on a reasonable way to allow a deployment to customize the proxy-init configuration?

**Comment by ayj** [comment]
cc @yusuoh 

You could also move conditional logic into the injection template itself, e.g.

https://github.com/istio/istio/blob/bf18b1fa0a7393b7f524f27c2bc06c9356f7caac/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl#L34-L39.

You could do something similar with annotations on the pod template spec's in your deployments (`param.sidecar.istio.io/ingress=true` , `params.sidecar.istio/includeIPRange=x.x.x.x/x`, etc.)

**Comment by Stono** [comment]
For whar it's worth I think I prefer annotations, especially as they're
already being used for configuration (mtls) it feels nice to be consistent
with that.
