### ISSUE TITLE
regionalFailover and failoverPriority should work together

### ISSUE THREAD

**Issue by tanujd11** [istio/istio#47068]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
The usage of FailoverPriority and RegionalFailover is mentioned in the following [doc](LocalityLoadBalancerSetting). If there is a usecase to keep the traffic local to the network as far as possible, then a failoverPriority can be used in the following way:

```
failoverPriority:
- "topology.istio.io/network"
```

Now on top of this if we want locality based priority, what we can do is we can update the failoverPriority to look like this:
```
failoverPriority:
- "topology.istio.io/network"
- "topology.kubernetes.io/region"
- "topology.kubernetes.io/zone"
- "topology.kubernetes.io/subzone"
```

In the above case matching network, region, zone, subzone will have the highest priority and so on as explained in the doc attached. Now if I want traffic from regionA to failover to only regionB and not regionC or regionD, it won't be possible through failoverPriority alone. How about after the priority calculation using failoverPriority is done and if [failover](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting-Failover) is also configured we calculate the priority of the remaining endpoints with priority P(N)(i.e least priority) through that. i.e P(N+1) will be given to the region mentioned in failover settings. This will enhance the feature drastically with a relatively lower complexity in code change.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
If the suggestion is approved, I can create a PR for the same. Thanks

**Comment by ramaraochavali** [comment]
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I think this is a reasonable requirement.

**Comment by tanujd11** [comment]
Hey @hzxuzhonghu you can assign this to me if you want. I have the change mostly ready. Thanks.

**Comment by howardjohn** [comment]
failoverPriority allows k=v pair 

```
failoverPriority:
- "topology.istio.io/network"
- "topology.kubernetes.io/region=us-west"
- "topology.kubernetes.io/region"
- "topology.kubernetes.io/zone"
- "topology.kubernetes.io/subzone"
```

?

**Comment by tanujd11** [comment]
@howardjohn I can't understand how it will fix this usecase. I want clients in us-east to failover to us-west and traffic should remain in us-east for as long as possible. If the above failoverPriority is used client in us-east will always favour us-west since it will override proxy's default locality to be us-west. Is there anything I am missing here?

**Comment by tanujd11** [comment]
The requirement is as follows:
Client : us-east (nw-0)
Endpoint 1: us-east (nw-0) : P0
Endpoint 2: us-east (nw-1) : P1
Endpoint 3: us-west (nw-2): P2
Endpoint 4: us-central (nw-3): P3

P0 is assigned above using the same network. P1, P2 and P3 are assigned using the `failover`. How can just `failoverPriority` be able to handle this scenario?

**Comment by tanujd11** [comment]
> The requirement is as follows: Client : us-east (nw-0) Endpoint 1: us-east (nw-0) : P0 Endpoint 2: us-east (nw-1) : P1 Endpoint 3: us-west (nw-2): P2 Endpoint 4: us-central (nw-3): P3
> 
> P0 is assigned above using the same network. P1, P2 and P3 are assigned using the `failover`. How can just `failoverPriority` be able to handle this scenario?

In this case I am talking w.r.t client which is a cluster running in us-east. All the clients and endpoints are in different clusters. What failoverPriority can be used for this case?

**Comment by deva26** [comment]
Yeah, with failoverPriority, I can't prioritize among other regions not matching the client locatliy. For example, I would like to keep the traffic local to the cluster, then within my region but another cluster (say us-east), then prioritise where my request should go from the remaining regions like us-west first and then to us-central, etc.

If we have both the combinations of failoverPriority and Locality based with From and To, that would solve it.

@howardjohn - let know if you have other ideas.

**Comment by nmnellis** [comment]
I think this is related as well https://docs.google.com/document/d/1joq6qDKoebjS8SRD2_u2SvonnArJziPwPuJtepfddaw/edit#heading=h.xw1gqgyqs5b

**Comment by tanujd11** [comment]
Hi @nmnellis , Is it being introduced the document you mentioned? Looks like it will be really helpful to define priorities irrespective of client labels.
