### ISSUE TITLE
proxy failing readiness due to slow envoy stats

### ISSUE THREAD

**Issue by nairb774** [istio/istio#47061]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Context: We have a dev cluster with a significant number of services (O(18k)) that the vast majoity of are KNative services. KNative has a few components that act as global traffic concentrators, and as a result I'm unaware of a way to apply a Sidecar resource to significantly trim down the sidecar configuration. The end result is that the sidecar has a fairly beefy ram and CPU footprint - something we've just accepted given the current setup(1).

When the istio-proxy sidecar starts up, it goes through the process of loading all of the configuration information from istiod, and then it looks like there is some sort of health check that starts. At that time in the startup lifecycle we get a repeated number of the following logs:

> 2023-09-20T20:07:12.002721Z    warn    Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2023-09-20T20:07:14.003612Z    warn    Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2023-09-20T20:07:16.000912Z    warn    Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2023-09-20T20:07:18.002081Z    warn    Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Shelling into the pod and using curl to hit the same endpoint seems to take anywhere from 700ms to 8s to return. If the pod is left along for long enough, Envoy will eventually return fast enough, and the sidecar will go ready.

> 2023-09-20T23:26:18.000772Z    warn    Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2023-09-20T23:26:21.116984Z    info    Readiness succeeded in 3h34m48.423494619s
> 2023-09-20T23:26:21.118741Z    info    Envoy proxy is ready

Looking at the code, it seems like there is a 1s deadline - which seems sensible.

Any options for making the time for a pod to go ready a little more predictable? I'm filing as a bug, because given everything I've tried, I can't seem to find a way to make the situation more reliable. I tried disabling all metrice with a Telemetry resource and the deadline doesn't look configurable. Any options to get out from this situation?

(1) We are evaluating reworking things, but I think the bug/question is still relevant.

### Version

```Text
$ istioctl version
client version: 1.15.3
control plane version: 1.16.7
data plane version: 1.16.7 (4671 proxies), 1.14.0 (72 proxies)
$ kubectl version --short
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.23.17-eks-2d98532
WARNING: version difference between client (1.27) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Additional Information

Attempting to use `istioctl bug-report` against the cluster, even scoped to the one namespace is proving to be problematic on my machine. I'll continue to try to pull something, but this cluster is kind of gnarly. Let me know if there is anything I can try to fetch on a targeted basis.

**Comment by hzxuzhonghu** [comment]
I think we should increase the timeout to be larger. I want to know how much time it takes for your request to be reponsed

**Comment by zirain** [comment]
> I think we should increase the timeout to be larger. 

it's better make it configuration.

**Comment by nairb774** [comment]
> I want to know how much time it takes for your request to be reponsed

Some hand testing gave me:

> Shelling into the pod and using curl to hit the same endpoint seems to take anywhere from 700ms to 8s to return.

Let me know if you would like any more precise measurements, and/or any additional data to go with (increased logging? profiles?). Happy to collect if it would help guide decisions or even locate a source of slowness.

> it's better to make it configuration.

It would be awesome if the context.Context available [here on the http.Request](https://github.com/istio/istio/blob/3552d34e71850f6a1a5dac1bd9011f763b64235f/pilot/cmd/pilot-agent/status/server.go#L453) were plumbed down to, I think, [here](https://github.com/istio/istio/blob/3552d34e71850f6a1a5dac1bd9011f763b64235f/pilot/cmd/pilot-agent/status/ready/probe.go#L65) so that the caller of `/healthz/ready` is able to determine how long to wait. This would enable making the timeout configurable by adjusting the `timeoutSeconds` on the container's readiness probe. If you think this would be an acceptable approach, and I'm roughly in the right direction, I would be happy to try to pull together a PR in this direction.

While I have your attention, thanks for Istio! It makes so much possible that would otherwise be impossible.

**Comment by hzxuzhonghu** [comment]
I think it is right to make it consistent with readiness probe timeout (T). 

Currently, there are many checks,  we should make them run in parallel and set the timeout to be a little less than T, maybe be `T-1`.

**Comment by ramaraochavali** [comment]
Aligning with readiness probe timeout makes sense

> Currently, there are many checks, we should make them run in parallel and set the timeout to be a little less than T, maybe be T-1.

The main problem here is the main thread of Envoy is busy ingesting huge config and the stats endpoints hit the main thread - that is why it takes time. Running them in parallel does not improve things.

**Comment by howardjohn** [comment]
Making the timeout longer, IMO, doesn't solve the problem. It doesn't matter if we send 8 requests with a 1s timeout or 1 request with an 8s timeout, result is the same -- it takes 8s to get ready because the config is _massive_

**Comment by howardjohn** [comment]
Istio pretty fundamentally is not going to handle 18k services (actually its much worse, each Kservice is more than 1 service) without sidecar scoping
