### ISSUE TITLE
Long Living TCP Connection 

### ISSUE THREAD

**Issue by nagavijayan-nagarathinam** [istio/istio#47070]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am encountering an issue when using Istio 1.18.2 in conjunction with Amazon EKS 1.25. My microservice is making an API call to abc.com, and the response time from abc.com exceeds 5 minutes. In this scenario, when the response time exceeds 5 minutes, the request fails.

Issue Details:

- Istio Version: 1.18.2
- Amazon EKS Version: 1.25
- Microservice Scenario: The microservice triggers an API call to abc.com, and if the response time is less than 5 minutes, the request succeeds. However, when the response time exceeds 5 minutes, the request fails.

Additional Information:

Without Istio: When Istio is not in use, the network components (NAT and EC2 instances) send keep-alive packets, and long-running connections are successful.
With Istio: When Istio is enabled, it appears that keep-alive packets are not being sent, resulting in connections timing out

These combination work for long living connections:

- Istio + Internet Gateway + Public IP
- NAT + EC2 Instancer(without Istio)

NAT + Istio combination is not working for this long living request

Steps to Reproduce:

- Deploy the microservice with Istio 1.18.2 on Amazon EKS 1.25.
- place debug pod in private subnet with NAT
- Trigger an API call to abc.com with a response time exceeding 5 minutes.

Expected Behavior:
The request should not fail, even when the response time from abc.com exceeds 5 minutes.

Actual Behavior:
The request fails when the response time from abc.com exceeds 5 minutes.

Note:
This issue is impacting our application's ability to handle long response times and is causing disruptions. Any assistance or insights into resolving this issue would be greatly appreciated.

### Version

```Text
istioctl version
client version: 1.18.2
control plane version: 1.18.2
data plane version: 1.18.2 (54 proxies)


kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.25.12-eks-2d98532
```

**Comment by escoffier** [comment]
if not configured, envoy proxy use OS level keep-alive configurations.
[tcpkeepalive](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#envoy-v3-api-msg-config-core-v3-tcpkeepalive )
as i known,  you can set keep-alive parameters by configuring envoy parameters cluster. upstream_connection_options by isto EnvoyFilter CRD.
