### ISSUE TITLE
How to setup a warmup period for the scaled-out replicas in Kubernetes?

### ISSUE THREAD

**Issue by vivuu1989** [istio/istio#47085]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

How to setup a warmup period for the scaled-out replicas in Kubernetes?

### Version

```Text
1.18.2
```

### Additional Information

We are using Istio version 1.18.2 on all our AKS (V1.27.3) based envts (Dev,Stg, Prod, Dr, etc.) setup. We have enabled the Istio sidecars injection with namespace injection for Springboot java-based applications.

During our scalability tests, we noticed that when a service scales out, (i.e. from 3 to 4 instances), the new instance after reporting being healthy immediately gets i.e. 25% of the load. Since the service instance did not have a chance to warm up yet, requests sent to it temporarily time out or show increased response time compared to other existing instances. This state can remain from 3-4 minutes to even 15 minutes, depending on the load, from what we saw in our tastings.

We were looking for a scaling related solution so that a new service instances right after scaling out to receive load that they are able to handle.
so that scaling out does not cause temporary response time to increase for the production services. 

We searched for a solution from istio side and tried as per the solution provided here for Destination Rule. 
https://stackoverflow.com/questions/74517652/gradually-warm-java-application-in-k8s-with-istio#:~:text=trafficPolicy%3A%0A%20%20%20%20loadBalancer%3A%0A%20%20%20%20%20%20simple%3A%20ROUND_ROBIN%0A%20%20%20%20%20%20warmupDurationSecs%3A%20180s 

    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: myapp
      namespace: myns
    spec:
      host: "myapp.myns.svc.cluster.local"
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
          warmupDurationSecs: "180s"
      subsets:
        - name: v1
          labels:
            app: myapp
            version: 1.0

In our destination rule, we haven't configured different versions for subsets, and it will be always v1.0 (we don't require the different versions as of now). But this solution of traffic policy also didn't worked as expected, as we tested the scaling behavior and not anew release.

![IMG_20230927_154254.jpg](https://github.com/istio/istio/assets/25169130/a2764ad0-f7aa-4664-85bb-3fef4beae501)

is there any way to achieve this using istio while scaleout happening. ?

**Comment by ramaraochavali** [comment]
> But this solution of traffic policy also didn't worked as expected, as we tested the scaling behavior and not anew release.

Do you have stats that shows this discrepancy?

**Comment by vivuu1989** [comment]
> > But this solution of traffic policy also didn't worked as expected, as we tested the scaling behavior and not anew release.
> 
> Do you have stats that shows this discrepancy?

The screenshot upload is failing in my environment. The new scaled instance got traffic within 1 minute, where as we configured the warmup. So whether this istio warmup feature is applicable for existing deployments scaling scenario or only during new deployment?

**Comment by ramaraochavali** [comment]
> The new scaled instance got traffic within 1 minute, where as we configured the warmup for 10 minutes.

It will send traffic gradually during those 10 mins. Are you not seeing gradual increase?

> So whether this istio warmup feature is applicable for existing deployments scaling scenario or only during new deployment?

Yes. It works for existing deployments scaling scenario

**Comment by vivuu1989** [comment]
> > The new scaled instance got traffic within 1 minute, where as we configured the warmup for 10 minutes.
> 
> It will send traffic gradually during those 10 mins. Are you not seeing gradual increase?
> 
> > So whether this istio warmup feature is applicable for existing deployments scaling scenario or only during new deployment?
> 
> Yes. It works for existing deployments scaling scenario

No.. First 3 instances were took the traffic within 1 minute and the last instance got the warmup correctly.

**Comment by ramaraochavali** [comment]
> First 3 instances were took the traffic within 1 minute and the last instance got the warmup correctly. 

These 4 are the new scaled up instances?

**Comment by ramaraochavali** [comment]
What was the original instance size before scale up and how did you scale these new 4 instances?

**Comment by vivuu1989** [comment]
> > e new scaled up instances?
> 
> yes.. these are the new 4 instance, first 3 wer

    Started running test at X TPS load
    Increase load to X*4 TPS in 5 minutes
    Kept load at X*4 TPS for 30 minutes

**Comment by vivuu1989** [comment]
> > > e new scaled up instances?
> > 
> > 
> > yes.. these are the new 4 instance, first 3 wer
> 
> Starting capacity was 3 pods. Started running test at X TPS load Increase load to X_4 TPS in 5 minutes Kept load at X_4 TPS for 30 minutes --- At this spike scaling initiated

Any idea on this unexpected behavior of istio ?

**Comment by ramaraochavali** [comment]
So if I understand this correctly, when scaling initiated it brought up 4 new instances at the same time and only one instance got warmed properly?

**Comment by vivuu1989** [comment]
> So if I understand this correctly, when scaling initiated it brought up 4 new instances at the same time and only one instance got warmed properly?

No, scaling initiated at different times as shown in the graph. The first 4 scaled instances got traffic in 1 minute and the 5th scaled instance only got the applied warmup behavior of 10 minutes. The first 4 instances didn't get the warmup settings applied.

**Comment by ramaraochavali** [comment]
Ok. It might be related to how the pods are scaled up in different localities. Please see https://github.com/istio/istio/issues/46569#issuecomment-1739105813.  Try disabling it and see if it helps.
