### ISSUE TITLE
Istio. request. latency bucket customization

### ISSUE THREAD

**Issue by Harif-Rahman** [istio/istio#47095]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istio_request_duration_milliseconds_bucket metrics are emitting the le values bucket with some set of finite values
is there any way to customise this bucket values ?

### Version

```Text
Istio version :istio/proxyv2:1.16.1
Kubernetes version : 1.24
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
i recall there is a annotation can do this, should be sidecar.istio.io/statsHistogramBuckets

**Comment by weidalin** [comment]
> statsHistogramBuckets

sidecar.istio.io/statsHistogramBuckets: '{"istio":[0.5,1,5,10,25,50,100,250,500,1000,2500,5000,10000,15000,30000,45000,60000,90000,150000,300000,600000,1800000,3600000]}'
