### ISSUE TITLE
Endpoints are Wrongly Updated after Setting k8s Service Spec Selector nil and Modifying Endpoints Address

### ISSUE THREAD

**Issue by xiaoyunyu** [istio/istio#47098]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

## What I tried
I can stably reproduce this bug. Here is the steps:
1. create a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin1
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin1
      version: v1
  template:
    metadata:
      labels:
        app: httpbin1
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: governmentpaas/curl-ssl
          imagePullPolicy: IfNotPresent
          name: httpbin
          command:
            - /bin/sleep
            - 30d
          ports:
            - containerPort: 8013
              name: http
```
3. create a service with Spec.Selector pointing to deployment template's labels 
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin1
  namespace: test
  labels:
    app: httpbin1

spec:
  selector:
    app: httpbin1
  ports:
    - name: http
      port: 8000
      targetPort: 8013
```
5. use istioctl to get endpoints configs
<img width="1708" alt="image" src="https://github.com/istio/istio/assets/26958263/c6feffaa-e026-4faf-80cf-9aab7d35dd9e">
the above IPs are actual backend pod IPs. 

6. modify the service as below, I just set Spec.Selector to nil:
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin1
  namespace: test
  labels:
    app: httpbin1

spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8013
```
7. modify the corresponding endpoints address:
```
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-09-25T11:02:21Z"
  labels:
    app: httpbin1
  name: httpbin1
  namespace: test
  resourceVersion: "359893426"
  uid: c6ca0c85-f3ec-44a4-9801-bfc9a3e98e6e
subsets:
- addresses:
  - ip: 1.2.3.4
    nodeName: 10-129-101-68.cls-gexmjc58.ecp.shopeemobile.com
    targetRef:
      kind: Pod
      name: httpbin1-75855fc46f-l4ldk
      namespace: test
      resourceVersion: "359877811"
      uid: 5a4f0f46-1eec-464f-94d2-c1eea754200f
  ports:
  - name: http
    port: 8013
    protocol: TCP
```
In fact, I just delete one address and modify the other address IP to 1.2.3.4. 

## What expected to happen 
After doing the steps above, I expect use istioctl to get endpoints and only 1.2.3.4 is returned. 
## What actual happened 
But actually, I got 3 IPs.
<img width="1674" alt="image" src="https://github.com/istio/istio/assets/26958263/060b50b1-cca2-4e12-96a0-4987146889a0">
10.105.45.14 and 10.105.66.200 should not be here, since I already delete serivce.spec.selector and there is only one IP in k8s endpoints, i.e. 1.2.3.4. 

I have tried adding env PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES=false in istiod deployment and restart istiod, but the two unexpected IPs still exist. 

### Version

```Text
$ istioctl version
client version: 1.19.0
control plane version: 1.13.5
data plane version: 1.12-dev (3 proxies), 1.13.5 (28 proxies), 65536.65536.65536 (1 proxies)
$ kubectl version --short
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.13-ske.1
```

**Comment by howardjohn** [comment]
This is either a Kubernetes bug, or a "using Kubernetes wrong" bug. Its NOT an Istio bug IMO.

I reproduced: 

```
$ kubectl get endpoints
NAME         ENDPOINTS                                         AGE
echo         1.2.3.4:7070,1.2.3.4:443,1.2.3.4:80 + 2 more...   13d
kubernetes   10.128.0.7:443                                    14d
shell        10.36.2.27:9087                                   13d
gke ~/go/src/istio.io/istio/pkg/kube/kclient (kclient/fix-crd-watch-race)
$ kubectl get endpointslices.discovery.k8s.io
NAME          ADDRESSTYPE   PORTS                      ENDPOINTS    AGE
echo-22xmz    IPv4          7070,80,9090 + 2 more...   1.2.3.4      52s
echo-nhgx6    IPv4          7070,80,9090 + 2 more...   10.36.2.29   13d
kubernetes    IPv4          443                        10.128.0.7   660d
shell-59kb8   IPv4          9087                       10.36.2.27   13d
```

You can see endpointslices, the source of truth, has both.

**Comment by xiaoyunyu** [comment]
> This is either a Kubernetes bug, or a "using Kubernetes wrong" bug. Its NOT an Istio bug IMO.
> 
> I reproduced:
> 
> ```
> $ kubectl get endpoints
> NAME         ENDPOINTS                                         AGE
> echo         1.2.3.4:7070,1.2.3.4:443,1.2.3.4:80 + 2 more...   13d
> kubernetes   10.128.0.7:443                                    14d
> shell        10.36.2.27:9087                                   13d
> gke ~/go/src/istio.io/istio/pkg/kube/kclient (kclient/fix-crd-watch-race)
> $ kubectl get endpointslices.discovery.k8s.io
> NAME          ADDRESSTYPE   PORTS                      ENDPOINTS    AGE
> echo-22xmz    IPv4          7070,80,9090 + 2 more...   1.2.3.4      52s
> echo-nhgx6    IPv4          7070,80,9090 + 2 more...   10.36.2.29   13d
> kubernetes    IPv4          443                        10.128.0.7   660d
> shell-59kb8   IPv4          9087                       10.36.2.27   13d
> ```
> 
> You can see endpointslices, the source of truth, has both.

I got it. The problem has confused me for a long time, thank you so much!
