### ISSUE TITLE
Metadata exchange response headers are returned on every request

### ISSUE THREAD

**Issue by StefanCenusa** [istio/istio#47096]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This issue is for the regression of #22546 in istio 1.19.0. 

In brief, metadata headers are once again returned for requests that come from outside the mesh. In 1.17.2 and 1.18.3 this behaviour is as expected (no metadata headers are present).

My use-case is that services are exposed via a Google External HTTPS LoadBalancer with container-native load-balancing enabled (requests go directly into the pods).

A thread was also opened on [slack](https://istio.slack.com/archives/C382V8Q92/p1695210893150059).

### Version

```Text
istioctl 1.19.0
```

**Comment by zirain** [comment]
cc @kyessenov

**Comment by howardjohn** [comment]
Do we know what PR caused the regression?
