### ISSUE TITLE
[Istio 1.18] Istio Gateways Unable to Serve Expired Certs 

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#47104]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

On upgrading to Istio 1.18 endpoints served by an expired cert return SSL failures rather than an expired certificate that can be ignored with curl -k or an --insecure variant on other clients. This is of course avoidable by expiring stale certificates but in the event that a certificate goes expired can result in total failure rather than failure only for clients with strict SSL validation.

This appears to be due to a change in the certificate validation that prevents the cert from being loaded.

Expected Behavior:
Istio gateways should still be able to serve expired certificate

Steps to reproduce:
1. Deploy Istio 1.18 to cluster 
2. Deploy an Istio ingress gateway
3. Create a self-signed cert with a short expiry or an expiration in the past. 
4. Deploy a Gateway resource with a configuration to load the expired cert.
5. Curl/visit an endpoint that should serve the expired cert.

Istioctl pc secret on 1.15 pod
```
RESOURCE NAME                                      TYPE           STATUS     VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
kubernetes://custom-cert                Cert Chain     ACTIVE     false          blah     2023-06-06T23:59:00Z     2021-06-06T23:59:00Z
```

Istioctl pc secret on 1.18 pod
```
RESOURCE NAME                                      TYPE           STATUS     VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
kubernetes://custom-cert                               WARMING     false
```

### Version

```Text
Istio 1.18
```

**Comment by howardjohn** [comment]
Fixed in https://github.com/istio/istio/pull/46970. making sure we cherrypick it to 1.18
