### ISSUE TITLE
Does default config for TerminationDrainDuration should greater than DrainDuration?

### ISSUE THREAD

**Issue by masquee** [istio/istio#47117]
pkg/config/mesh/mesh.go
<img width="1013" alt="image" src="https://github.com/istio/istio/assets/8470824/e19854b8-fc68-41e8-a054-ce8f2459e799">

Currently default config for `TerminationDrainDuration` is 5s, and default config for `DrainDuration` is 45s.

Envoy's `drain-time-s`  is configured based on `DrainDuration` which longer than `TerminationDrainDuration`.

But when pilot agent execute `terminate`, it wait `TerminationDrainDuration` and then send to `abortCh`, which will  make Envoy process exit immediately (signal **KILL** send to Envoy process). 

pkg/envoy/agent.go
<img width="982" alt="image" src="https://github.com/istio/istio/assets/8470824/243d069a-f82d-4355-b6f1-1ee0d65e4e6f">

pkg/envoy/proxy.go
<img width="838" alt="image" src="https://github.com/istio/istio/assets/8470824/23c879de-d3e9-4c18-9ec9-05cd3ebe1bf2">

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by masquee** [comment]
In fact, it is indeed configured through ProxyConfig when we actually use it. My main question here is, is the current default value of `5s` for `TerminationDrainDuration`  unreasonable? **The default value should be such that it behaves reasonably even if it is not set.**

**Comment by ramaraochavali** [comment]
> My main question here is, is the current default value of 5s for TerminationDrainDuration unreasonable

It may be unreasonable. The linked issue discusses the same but we can not change now and hence the suggestion to set it via proxy config
