### ISSUE TITLE
Way to enable Postgres filter

### ISSUE THREAD

**Issue by nbjohnson** [istio/istio#47113]
**Describe the feature request**
A postgres contrib extension was previously added to the istio proxy, need a flag to enable it for use

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

The postgres contrib extension was previously enabled in this PR: https://github.com/istio/proxy/pull/4328/files From what I can see other extensions have a flag to enable such as `PILOT_ENABLE_MONGO_FILTER`, `PILOT_ENABLE_MYSQL_FILTER`, and `PILOT_ENABLE_REDIS_FILTER` as shown on this doc page: https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars Can an entry to enable postgres also be added? Seems like they are added here: https://github.com/istio/istio/blob/cbc7db7e5073f3a5e6b2835cd89de19582e16949/pilot/pkg/features/pilot.go#L141 Unless there is another way to enable postgres for use

**Comment by zirain** [comment]
cc @istio/technical-oversight-committee

**Comment by howardjohn** [comment]
I don't think we should do this; the other ones were added before EnvoyFilter existed. https://github.com/aeraki-mesh/aeraki can do this. We are actively avoiding adding "permanent experimental" features like this, and there doesn't seem to be an effort in the community to drive other L7 protocols to stable

**Comment by howardjohn** [comment]
You don't need Aeraki it just is an orchestrator on top of Istio. You can do it yourself as well. Starttls is also very different than postgres.

**Comment by zirain** [comment]
Hypothetically, if a company or individual commits to maintaining the relevant code, will TOC be accepted to introduce support for other protocols?

**Comment by nbjohnson** [comment]
@howardjohn So we need to use postgres with starttls for encryption. My understanding is these filter extensions are the support for starttls for specific protocols, but maybe I am mistaken. If starttls can be supported at a high level by istio that would be for all protocol types that would be great, but don't know if thats possible
