### ISSUE TITLE
Istio sidecar running at 100% CPU

### ISSUE THREAD

**Issue by chandrakanthkannam** [istio/istio#47154]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are running EKS cluster with istio service mesh and sidecar injection enabled. Few of the replicas for a pod deployment in the cluster having an issue, where istio-proxy has envoy process sitting at 100% and these pods don't have any traffic coming in and the process still sits 100%. 

![image](https://github.com/istio/istio/assets/49658217/e346d318-0fc7-43d1-9bc1-4649ef445bfd)

### Version

```Text
Istio helm chart version: 1.14.3 

EKS version: v1.22.17-eks-0a21954
```

**Comment by chandrakanthkannam** [comment]
Tried to reach out on slack as well: https://istio.slack.com/archives/C37A4KAAD/p1695912023854109

**Comment by zirain** [comment]
if there's no taffic, the most likely reason is stats.
can you check the ouput of command: `istioctl x es <pod_name> -n <namespace> | grep istio|wc -l`

**Comment by kyessenov** [comment]
What features are you using?

**Comment by chandrakanthkannam** [comment]
Sorry guys for the late reply.

What features are you using?
- @kyessenov can you be more specific? I'm not sure i get this question.

if there's no taffic, the most likely reason is stats.
- @zirain  Oh? stats?

can you check the ouput of command:`istioctl x es <pod_name> -n <namespace> | grep istio|wc -l`
- @zirain it says `77`, but I'm not able to reproduce the behavior at the moment
