### ISSUE TITLE
HTTPRoute: unable to remove path prefix via URLRewrite

### ISSUE THREAD

**Issue by brucec5** [istio/istio#47153]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It doesn't seem to be possible to entirely remove a path prefix via URLRewrite when using HTTPRoutes. The [Gateway API docs](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPPathModifier) make it sound like this should be possible, see the table under `replacePrefixMatch`, specifically the the row with a request path of `/foo/bar`, a prefix match of `/foo`, an empty replace prefix, which should result in a path of `/bar`.

Using the following matches/filters in a rule, I'd expect a `/foo/bar` request path to get rewritten to `/bar` but instead I get `//bar`:

```yaml
matches:
- path:
    type: PathPrefix
    value: /foo
filters:
  - type: URLRewrite
    urlRewrite:
      path:
        replacePrefixMatch: /
        type: ReplacePrefixMatch
```

And it looks like we [can't use an empty string](https://github.com/istio/istio/blob/1.19.0/pilot/pkg/networking/core/v1alpha3/route/route.go#L515-L517) for `replacePrefixMatch` either (IIRC this is also an Envoy limitation?).

It seems this stems from the fact that Gateway API routes use path-separated-prefix matches while VirtualServices use plain prefix matches ([link](https://github.com/istio/istio/blob/1.19.0/pilot/pkg/networking/core/v1alpha3/route/route.go#L914-L920)). The result seems to be that we can only replace portions of the prefix path segment, rather than replacing the entire segment itself.

This is related to #8076, but the workarounds suggested for VirtualService don't work with the Gateway API due to the differing path-separated-prefix semantics.

### Version

```Text
$ istioctl version
client version: 1.17.3
control plane version: 1.18.2
$ kubectl version --short
Client Version: v1.26.1
Server Version: v1.25.9
```

**Comment by howardjohn** [comment]
Looks likely a bug in our code and a gap on gateway-api conformance tests possibly. We should see if we can address both
