### ISSUE TITLE
Add max concurrent streams connection pool parameter in Destination Rules

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#47166]
**Describe the feature request**
Currently max_requests_per_connection can be set by configuration DestinationRules. This works well for HTTP/1, and works approximately fine with HTTP/2.

For HTTP/2 envoy provides another parameter called max_concurrent_streams (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-max-concurrent-streams), which is available for both HTTP/2 and HTTP/3.

**Describe alternatives you've considered**
EnvoyFilter can be used to configure this parameter

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

If this can be approved, I can provide a PR.

**Comment by jaellio** [comment]
This seems reasonable, I can make a PR for this if you would like!
