### ISSUE TITLE
istio upgrade

### ISSUE THREAD

**Issue by Nagnathkatkar** [istio/istio#47160]
Hello All
I have to upgrade istio from 1.14.x to 1.15.x on AKS cluster. However, istio is deployed by other team using helm charts. Can I upgrade istio on AKS cluster using canary upgrade mechanism or I have to use helm charts only. Also, how can we identity which profile they have used while deploying istio like minimal, default or demo. please help.

**Comment by zirain** [comment]
Technically you can. 
IIRC, there isn't any existing documentation or guidance.

**Comment by Nagnathkatkar** [comment]
Thank you very much for your response, can we also identity which profile they have used while deploying istio like minimal, default or demo.
