### ISSUE TITLE
Bad Istio VirtualService blocks Gateway's generation of Routes

### ISSUE THREAD

**Issue by CathalC2011** [istio/istio#47177]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

One of our teams recently applied a bad VirtualService config which prevented our ingressgateway's routes from updating. When the gateway next rolled over, its routes emptied completely (or rather never became populated).

The issue is described in this issue, though the cause was slightly different: https://github.com/istio/istio/issues/36021

The following minimal VS reproduces the issue (assuming a Gateway exists for *.[mydomain.com](http://mydomain.com/)):
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: repro
  namespace: default
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - mydomain.com
  http:
  - fault:
      abort:
        httpStatus: 404
        percentage:
          value: 1
```

The matching gateway will log the following:
```
gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.WeightedClusters: embedded message failed validation | caused by WeightedClusterValidationError.Clusters: value must contain at least 1 item(s)): name: \"https.443.https.istio-gateway.istio-system\"\nvirtual_hosts {

... followed by an extremely verbose virtual_host dump ...
```

For sure, the config is invalid, but I have two questions.

Firstly, this comment https://github.com/istio/istio/issues/36021#issuecomment-966529741 on the issue mentions in this scenario, the routes should not become ready, therefore the listeners should not become ready, therefore the gateway's readiness checks should fail. This doesn't appear to be the case (though granted that comment was two years ago so things may have changed). The gateway becomes ready and the listener exists, though the routes do not:
```
istioctl pc listeners $GW.istio-system
ADDRESS PORT  MATCH               DESTINATION
0.0.0.0 443   SNI: *.mydomain.com Route: https.443.https.istio-gateway.istio-system
0.0.0.0 15021 ALL                 Inline Route: /healthz/ready*
0.0.0.0 15090 ALL                 Inline Route: /stats/prometheus*
istioctl pc routes $GW.istio-system
NAME     DOMAINS     MATCH                  VIRTUAL SERVICE
         *           /healthz/ready*
         *           /stats/prometheus*
```

Secondly, shouldn't this config be blocked by Istiod's validating webhook? The code certainly exists to block it:
```
istioctl validate -f minimal-repro.yaml
Error: 1 error occurred:
        * VirtualService/default/repro: HTTP route, redirect or direct_response is required
```

but it doesn't appear to be executed on incoming objects

### Version

```Text
istioctl version --remote=false
1.17.5
```

**Comment by howardjohn** [comment]
You must not have the validating webhook (properly) running; the webhook does block it

**Comment by CathalC2011** [comment]
Thanks @howardjohn, went digging through the webhook configs. Our VirtualServices do not have the [istio.rev](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml#L49-L56) label - issue resolved!

**Comment by howardjohn** [comment]
there is supposed to be a webhook that validates no istio.io/rev label as
well

**Comment by keithmattix** [comment]
@CathalC2011 make sure you set the `defaultRevision` value on your istio install. Without it, only configs (e.g. VirtualService) with a revision label will be processed by the validating webhook
