### ISSUE TITLE
Support OpenID Discovery for JWT authentication

### ISSUE THREAD

**Issue by liminw** [istio/istio#4719]
With OpenID Discovery support (https://openid.net/specs/openid-connect-discovery-1_0.html), users do not need to manually enter public key URL. Instead, the public key URL will be automatically discovered. This will simplify the authentication policy configuration. 

According to Wayne, Envoy does not support dynamic cluster today. So we probably need to implement it in Pilot.

**Comment by liminw** [comment]
@quanjielin @wenchenglu @qiwzhang @diemtvu

**Comment by quanjielin** [comment]
1. PR https://github.com/istio/istio/pull/4834 pending on Pilot/Config owner feedback.
2. working a design doc.

**Comment by quanjielin** [comment]
close this issue as fetch/distribute jwks_uri PR https://github.com/istio/istio/pull/4834 was in. 
will use https://github.com/istio/istio/issues/4917 to track fetch jwt pubkey/key rotation.
