### ISSUE TITLE
Default ports in `gateway` chart aren't listened to

### ISSUE THREAD

**Issue by treyhyde** [istio/istio#47198]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The default target ports for the gateway service `manifests/charts/gateway/values.yaml` are hardcoded to 443, 80 on the pod.  The pod doesn't listen to 80 and 443, it listens to 8080 and 8443.  Thus, attempts to route traffic via the service will fail.

### Version

```Text
istioctl version
client version: 1.19.1
istiod version: 1.19.1
istiod version: 1.19.1
istiod version: 1.19.1
pilot version: 1.18.3
pilot version: 1.18.3
pilot version: 1.18.3
data plane version: 1.18.3 (967 proxies), 1.19.1 (297 proxies)

kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532
```

### Additional Information

1.19.1 version of the `gateway` helm chart

**Comment by njegosrailic** [comment]
Could you please review the Pod and container security contexts? Ensure that the pods run in privileged mode and that the container has the necessary capabilities. Additionally, look at the IstioD logs to understand why it's creating listeners on non-privileged ports instead of privileged ones.

**Comment by howardjohn** [comment]
Why is the pod listening on 8080? 

I suspect you have either multiple services selecting the same pods or have some Gateways referencing port 8080

**Comment by krzkowalczyk** [comment]
I can confirm I've got the same behaviour on GKE.
It's worth to notice that while installing istio using `istioctl` (according to docs with demo profile https://istio.io/latest/docs/setup/getting-started/) the `istio-gateway` service sets a proper port mapping, 80:8080 and 443:8443.
However using helm chart with default values as described in https://istio.io/latest/docs/setup/install/helm/ the service maps to ports 80 and 443 on pod which are not used.

Helm chart 1.19.4 image docker.io/istio/proxyv2:1.19.4

**Comment by howardjohn** [comment]
Simply `helm install`ing will not listen on the ports. You still need to create `Gateway` objects.

For anyone seeing issues, please say the steps you took, otherwise this is not actionable.
