### ISSUE TITLE
[release 0.7.1]:Setting up Istio Role-Based Access Control faile Service-level access control

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#4720]
Setting up Istio Role-Based Access Control failed Service-level access control
https://istio.io/docs/tasks/security/role-based-access-control.html

**Step 11 -16 failed on  Service-level access control**
1. download istio-0.7.1
2. cd ~/istio-0.7.1
3. kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo-add-serviceaccount.yaml)
```
serviceaccount "bookinfo-productpage" created
 deployment "productpage-v1" configured
 serviceaccount "bookinfo-reviews" created
 deployment "reviews-v2" configured
 deployment "reviews-v3" configured
```
4. curl -o /dev/null -s -w "%{http_code}\n" http://$GATEWAY_URL/productpage
`200`

5. istioctl create -f samples/bookinfo/kube/istio-rbac-enable.yaml
```
Created config authorization/istio-system/requestcontext at revision 2431
Created config rbac/istio-system/handler at revision 2432
Created config rule/istio-system/rbaccheck at revision 2433
```
6. curl http://$GATEWAY_URL/productpage
`PERMISSION_DENIED:handler.rbac.istio-system:RBAC: permission denied.`
7. istioctl create -f samples/bookinfo/kube/istio-rbac-namespace.yaml
```
Created config service-role/default/service-viewer at revision 2569
Created config service-role-binding/default/bind-service-viewer at revision 2570
```
8. curl -o /dev/null -s -w "%{http_code}\n" http://$GATEWAY_URL/productpage
`200`
9. istioctl delete -f samples/bookinfo/kube/istio-rbac-namespace.yaml
```
Deleted config: service-role/default/service-viewer
Deleted config: service-role-binding/default/bind-service-viewer
```
10. curl http://$GATEWAY_URL/productpage
`PERMISSION_DENIED:handler.rbac.istio-system:RBAC: permission denied.`
11. istioctl create -f samples/bookinfo/kube/istio-rbac-productpage.yaml
```
Created config service-role/default/productpage-viewer at revision 2874
Created config service-role-binding/default/bind-productpage-viewer at revision 2875
```
12. curl http://$GATEWAY_URL/productpage
`PERMISSION_DENIED:handler.rbac.istio-system:RBAC: permission denied.`
13. istioctl create -f samples/bookinfo/kube/istio-rbac-details-reviews.yaml
```
Created config service-role/default/details-reviews-viewer at revision 3055
Created config service-role-binding/default/bind-details-reviews at revision 3057
```
14. curl http://$GATEWAY_URL/productpage
`PERMISSION_DENIED:handler.rbac.istio-system:RBAC: permission denied.`
15. istioctl create -f samples/bookinfo/kube/istio-rbac-ratings.yaml
```
Created config service-role/default/ratings-viewer at revision 3196
Created config service-role-binding/default/bind-ratings at revision 3197
```
16.istio-0.7.1 janevalley$ curl http://$GATEWAY_URL/productpage
`PERMISSION_DENIED:handler.rbac.istio-system:RBAC: permission denied.`

mixer error log - 
```
{"level":"info","time":"2018-04-03T19:35:36.380300Z","instance":"accesslog.logentry.istio-system","connectionMtls":false,"destinationIp":"10.40.2.4","latency":"26.273531ms","method":"GET","protocol":"http","requestSize":0,"responseCode":403,"responseSize":68,"sourceIp":"10.128.0.19","sourceUser":"","url":"/productpage"}
```
Looks like rbac is applied at ingress. which is not supposed to happen because of namespace restriction in istio-rbac-enable.yaml

**Comment by janevalleye2e** [comment]
@kidiyoor

**Comment by kidiyoor** [comment]
@liminw

**Comment by janevalleye2e** [comment]
@vilobhmm

**Comment by liminw** [comment]
Can you please copy Istio RBAC samples from https://github.com/istio/istio/tree/master/samples/bookinfo/kube, instead of using the ones in installed directory? We made some sample changes, but it was not in the release. 

The instruction also mentioned it: https://istio.io/docs/tasks/security/role-based-access-control.html#before-you-begin

**Comment by janevalleye2e** [comment]
that worked.

basically following change in istio-rbac-productpage.yaml made it work
```
<   - services: ["productpage.default.svc.cluster.local"]
---
>   - services: ["productpage"]
```
But still it doesn't explain why ingress is dealing with rbac

**Comment by liminw** [comment]
I am not which part of Mixer log had the above error. It's possible that Ingress just forwarded 403 response back to the client. There is no evidence that RBAC is enforced on ingress.

**Comment by liminw** [comment]
@janevalleye2e Since RBAC already works in your tests, can we close this issue?

**Comment by janevalleye2e** [comment]
I have tested on https://github.com/istio/istio/tree/master/samples/bookinfo/kube, it worked. 
the following files are changed from above repo:
samples/bookinfo/kube/istio-rbac-ratings.yaml
samples/bookinfo/kube/istio-rbac-productpage.yaml
samples/bookinfo/kube/istio-rbac-details-reviews.yaml

close the ticket

**Comment by vilobhmm** [comment]
@liminw : Just a thought, won't it be better to have these rbac samples included as part of https://github.com/istio/istio/releases/tag/0.7.1 source itself rather than the doc changes here https://istio.io/docs/tasks/security/role-based-access-control.html#before-you-begin ? 

@janevalleye2e

**Comment by liminw** [comment]
Yes, ideally it should be in the release. But since the change was added late, it did not go into 0.7.1 release. But it will be in the next release.
