### ISSUE TITLE
Slow propagation delay after upgrade to 1.16.7

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#47216]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgraded istio from 1.12.5 to 1.16.7, we saw a sudden increase in one of our kubernetes clusters.

This graph shows the the time since last push (extracted from istiod logs) before/after the upgrade (from <1s to ~5s then ~20s) 
![image](https://github.com/istio/istio/assets/7817963/adb7d199-51bf-4b70-ab47-e828992b7722)

Here is the CPU profile for istiod
![image](https://github.com/istio/istio/assets/7817963/2236d6b4-5ff8-4b26-8530-ac73f85cc44f)

[pprof.pilot-discovery.samples.cpu.002.pb.gz](https://github.com/istio/istio/files/12831274/pprof.pilot-discovery.samples.cpu.002.pb.gz)

Here are a few more graphs that might be relevant
![image](https://github.com/istio/istio/assets/7817963/cd4352dd-8078-47a6-a895-ccbd45406105)

__

### Version

```Text
% istioctl version
client version: 1.16.7
control plane version: 1.16.7
data plane version: 1.16.7 (3 proxies)
```

### Additional Information

- We inject a single deployment responsible to route requests to ~5k headless services.
- We use to have PILOT_ENABLE_FLOW_CONTROL=true enabled (now gone in 1.16)
- We have PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES=true
- This could be related to https://github.com/istio/istio/pull/45224 or https://github.com/istio/istio/issues/44985 but I am not sure.

**Comment by hzxuzhonghu** [comment]
From the cpu flame, it seems #46329, which removed IsntancesByPort could help

**Comment by chaudyg** [comment]
Thanks @hzxuzhonghu for the link. I see this has been merged to master very recently. Do you think there are improvements in versions after 1.16 that could help with that ? Or feature flags I could play with ?

**Comment by hzxuzhonghu** [comment]
From the profile i see the most time costing is ``initServiceRegistry`, want to know how many services do you have, and also endpoints number? Do they update frequently?

I believe https://github.com/istio/istio/pull/46329 could largely decrease the time cost on initServiceRegistry

**Comment by chaudyg** [comment]
> want to know how many services do you have, and also endpoints number? Do they update frequently?
~5k services / 6k endoints updating a few times per day in batches.


I've upgraded to istio 1.19.1 and both the debounce_time and pushcontext_init time went down significantly
![image](https://github.com/istio/istio/assets/7817963/954715d1-1ede-4ec7-9d95-29aecbe60cc0)
