### ISSUE TITLE
Re-order custom-authz in filter stack

### ISSUE THREAD

**Issue by eduardosanzb** [istio/istio#47255]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

## Context
**Goal**: Fix running authorization after authentication

With the [current](https://github.com/istio/istio/pull/46899) filter ordering stack:

```
Metadata Exchange

Custom Authz (ext authz)

WASM Authn
Builtin Authn

WASM Authz
Builtin Authz

WASM Stats
Builtin Stats
WASM Rest
Terminal (TCP/HCM)
```

Where Istio is running `ext-authz` before `authn`. It causes the following issues:

A. Confusing system of running authorization before authentication.
B. It is not possible to execute WASM filters before the custom authorization.
C. It is not possible to execute `authz` deny policies before the custom authorization.

To run any `authn` before `custom-authz`, customer would need to either:
1. Code their own `authn` and run that before `custom-authz`.
2. Implement `authn` into `custom-authz`.

**Option 1** might be possible by running Lua filters? Or by using an external authentication service before Istio. But it cannot be used with WASM filters as described in this issue https://github.com/istio/istio/issues/45511. And there’s already built-in `authn`, so why would it make sense to code your own?

**Option 2** mixes the domains of `authn` and `authz` within Istio filters, as custom-authorization filter would now be running authentication. And there’s already built-in `authn`, so why would it make sense to code your own?

But neither of these options solves the confusing system of running `authz` before `authn`.

To solve B: see issue https://github.com/istio/istio/issues/45511

This is why we propose that `authz` should be run at the `authz` step. This solves A, B and C.

The following comments are related to this:

- https://github.com/istio/istio/issues/45511#issuecomment-1747895443
- https://github.com/istio/istio/pull/46899#issuecomment-1716901237
- https://github.com/istio/istio/pull/46899#issuecomment-1717854599

## Proposed Solution

Either before built-in `authz`
```
Metadata Exchange

WASM Authn
Builtin Authn

WASM Authz
Custom Authz (ext authz)  ← Moving after all the different approaches for Authn had been run
Builtin Authz

WASM Stats
Builtin Stats
WASM Rest
Terminal (TCP/HCM)
```

Or after built-in `authz`:
```
Metadata Exchange

WASM Authn
Builtin Authn

WASM Authz
Builtin Authz
Custom Authz (ext authz) ← Moving as the last approach of authz; for potential gain of performance

WASM Stats
Builtin Stats
WASM Rest
Terminal (TCP/HCM)
```

Both of the options solve the core issue.

Case for “Before built-in `authz`”:
No need to change documentation for Authorization Policies. `CUSTOM` runs first.

Case for “After built-in `authz`”:
Solves problem C: Running DENY policies before `custom-authz` saving time gRPC calls to `custom-authz` server. _For example, to deny requests from a certain set of IP addresses users can handle the DENY at `authz` without expensive gRPC calls._

Out of these two options, running after built-in `authz` is superior in terms of performance.

In addition, if all `authz` is run at the same point in the filter chain. The documentation for WASMPlugin does not need to be fixed:
<img width="1020" alt="Screenshot 2023-10-09 at 13 11 12" src="https://github.com/istio/istio/assets/4089986/ce05467b-0633-4872-aea5-ddae9fe831fc">

If the reordering proposed is implemented, the documentation matches the implementation. And the AUTHN phase will always run before authentication filters, and `AUTHZ` phase will always run before authorization filters. Currently the documentation does not state the reality and the `AUTHZ` should probably read “Insert plugin before Istio built-in authorization filters, but after Istio custom-authorization filter and Istio authentication filters”.

In **TLDR**; It seems that the current criteria for ordering the filters is based on *“approaches _(wasm,external, built-in)_”* rather than *“goals _(authentication, authorization)_”*. 
These decisions *do not allow for flexibility in mixing up different “approaches”* therefore enforcing to choose only one kind of “technology” to implement `authn` & `authz`.

This is why the core of this proposal is to mix the “approaches” to satisfy the “goals”.

## Conclusion
The A, B and C are fixed:
A. Confusing system of running authorization before authentication.
B. It is not possible to execute WASM filters before the custom authorization.
C. It is not possible to execute authz deny policies before the custom authorization.

A: Now authentication always runs before authorization.
B: Now WASM filters run before custom authorization then specified to run before authorization.
C: Now DENY authorization policies run before custom authorization.

### Version

```Text
Istio: 1.19.1
```

### Additional Information

n/a

**Comment by Jakousa** [comment]
So basically problem is this: https://github.com/istio/istio/blob/52c1cc6a0819791210e763b7e5cceaa845084c5e/pilot/pkg/networking/core/v1alpha3/networkfilter.go#L114-L115

And the fix is to move it right after this line?
https://github.com/istio/istio/blob/52c1cc6a0819791210e763b7e5cceaa845084c5e/pilot/pkg/networking/core/v1alpha3/networkfilter.go#L125

**Comment by linsun** [comment]
Thanks @eduardosanzb for the detailed report and outline the possible solutions! I think I'm leaning the towards the 2nd option (After built-in authz), it is more intuitive and saves unnecessary authz calls.

**Comment by linsun** [comment]
cc @kyessenov for thoughts since you are starting the [doc](https://github.com/istio/istio/issues/45511#issuecomment-1751022229)

**Comment by tilgovi** [comment]
Not to argue for a particular decision, but just to document a use case, I'll add that the current position allows custom-authz to return upstream headers that get evaluated by authn. There may be token exchange use cases that benefit from running early in the filter chain.
