### ISSUE TITLE
Unable to load private key after upgraded to V1.18.3

### ISSUE THREAD

**Issue by leoweiyu** [istio/istio#47268]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

we have Istio running in both prod and non prod environment okay for the past few years, but after rolling out Istio V1.18.3 (was 1.16.3), we noticed the following error from ingressgateway pod from one of our cluster (k1.25)

"warning envoy config external//envoy/source/common/config/grpc_subscription_Impl.cc 128gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load private key from <inline>, Cause: error:09000068":PEM routines: OPENSSL_internal:BAD_PASSWORD_READ thread=30"

there were no change made to the certificate and keys, the only thing changed was really the Istio version, we using same pipeline to rollout the upgrade across all our k8s fleet and we only have 1 cluster having this issue.

what we have tried so far
1) regenerated the cert/keys and restart all components

any help are appreciated, thank you

### Version

```Text
istio version 1.18.3
k8s version 1.25 (EKS)
```

**Comment by leoweiyu** [comment]
more finding:

we have discovered a duct tape solution which can temporarily "fix the issue"

the fix is we need to add a random label for the secret which Envoy failed to load, once a random label added to the secret, the ingressgateway container can immediately load the certificate straight away, but if we restart the ingressgateway pod, then the problem happens again.

To me, by relabel the label, we kinda bump up the k8s secret version, so could this be a bug which cache related?

we also noticed, if we duplicate the same secret with a different secret name, and update the credentialName in the gateway definition also fix the issue, but if we change it back to the original secret name, the same problem will happen.

**Comment by hzxuzhonghu** [comment]
Do you have multiclusters, suggest you check all clusters if there are same named secret in each cluster

**Comment by leoweiyu** [comment]
@hzxuzhonghu thanks
I have found the issue for the error message "OPENSSL_internal:BAD_PASSWORD_READ thread=30"
It was caused by user created a k8s secret with password protected private key, after remove the secret, the "OPENSSL_internal:BAD_PASSWORD_READ thread=30" is gone, but this time, it throw the following error message instead 

`warning envoy config external/envoy/source/common/config/grpc_subscription_impl.cc: 128 gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load certificate chain from <inline>  thread=30`

could you kindly advice if there is a way to figure out which k8s secret envoy was unable to load? is there any logging can be enabled to find out this information?

many thanks

**Comment by hzxuzhonghu** [comment]
I have a pr validating the certificate in istiod, can you check istiod logs
