### ISSUE TITLE
Forward B3 tracing headers in envoyExtAuthzHttp side requests

### ISSUE THREAD

**Issue by TimJongerius** [istio/istio#47278]
**Describe the feature request**

Can we have the B3 tracing headers added to the envoyExtAuthzHttp side requests? It would be helpful to see these requests in Jaeger.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
We have ` MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.IncludeRequestHeadersInCheck`, could this satisfy your case
`

**Comment by hzxuzhonghu** [comment]
Yes, B3 is generated after ext-auth

**Comment by TimJongerius** [comment]
Is there a way to have the gateway create B3 before authz? Maybe you can get me started with an EnvoyFilter.

**Comment by hzxuzhonghu** [comment]
I believe there is no way that you can get B3 header before it is generated, this is in gateway. But you can get it on the backend server side as the B3 headers will be sent to server.
