### ISSUE TITLE
Enable istio work offline

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#4729]
Istio now using `alpine:latest` as `initContainers`, and it cannot be configured. If I want to have istio work offline, then I have to pull `alpine:latest` for all nodes, we should let customer customized the initContainer for `alpine`.

/cc @linsun

**Comment by linsun** [comment]
maybe provide the customization via helm?

**Comment by gyliu513** [comment]
@linsun this is the part of `kube-inject`, so may not able to be covered by helm chart.

Take such scenario: I have a deployment file, and then use `istioctl kube-inject` to inject sidecar container to the deployment file, and the injection also include `initContainers` which has a container [using `alpine:latest` as the hardcode image](https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/mesh.go#L69), and this will cause offline will not work. 

My thinking for the PR here is let the `initContainer` also use `proxy_init` as the `proxy_init` image also include all of the requested binaries in `alpine:latest` image.

**Comment by gyliu513** [comment]
@linsun 

The `kube-inject` will introduce two  initContainers, and after the fix, both initContainers are using `proxy_init`.

Also the `istioctl kube-inject` support customizing the docker hub by `--hub`, so we can enable customer to specify a local registry and do not need to ensure `proxy_init` image on all nodes.
