### ISSUE TITLE
"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435588:SSL routines:OPENSSL_internal:CLIENTHELLO_TLSEXT 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT"

### ISSUE THREAD

**Issue by anemptyair** [istio/istio#47307]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

How to debug when got below error message?
"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435588:SSL routines:OPENSSL_internal:CLIENTHELLO_TLSEXT 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT"

### Version

```Text
Istio
https://artifacthub.io/packages/helm/istio-official/istiod/1.18.0

kubectl version --short
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.4-eks-2d98532
```

**Comment by GregHanson** [comment]
@anemptyair best guess it to increase the envoy log level in the sidecar/proxy you are seeing the error:
```
istioctl pc log <pod_name>.<pod_ns> --level trace
# send a few requests to trigger the failure
# reset log level back to default
istioctl pc log <pod_name>.<pod_ns> --reset
```
and see if anything additional gets logged around that error message

Is this a call from sidecar to an external service?  Or what is the request path? ingress -> sidecar / sidecar -> sidecar / etc
