### ISSUE TITLE
Make jwks resolver timeout configurable

### ISSUE THREAD

**Issue by tugtugtug** [istio/istio#47328]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
The current timeout of jwks resolver is 5 seconds, as found at https://github.com/istio/istio/blob/0cb0d8afc422349e22077f22d84c2084023e5417/pilot/pkg/model/jwks_resolver.go#L50

I think for some environments, 5 seconds may be too short and this value should probably be allowed to be configurable.

**Describe alternatives you've considered**
We've tried to use a local proxy for the jwks url, and use the local proxy to handle the longer timeout, but that's not quite a good solution.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
We have jwt verification with a remote jwks url. The jwks server may from time to time get overloaded, and serve the requests longer than 5 seconds, but still in the tolerable range. However, istiod seems to report 
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
and then retry in an exponential fashion. This means our service would be down for an somewhat unpredictable amount of time until the jwks timeout is gone.

**Comment by leosarra** [comment]
Hello @tugtugtug 
I will take a look this week and I will try to push some changes :)

**Comment by leosarra** [comment]
Closed as completed via https://github.com/istio/istio/pull/48203
