### ISSUE TITLE
Make JWTRule support jwksUri(s)

### ISSUE THREAD

**Issue by tugtugtug** [istio/istio#47329]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Right now, the JWTRule supports a single jwksUri. It would be preferable if we can support an array of jwksUris, so if one of the server fails, a backup server can be used to load the jwks.
The selection of each retry can be either load balanced or randomly selected from the configured array.

**Describe alternatives you've considered**
We have been using a local proxy for jwksUri to control the behaviour. However, it is undesirable as the traffic from istiod to it is unencrypted, and we have to spent extra resources for this flexibility.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
We have JWTRules for authentication of our services, and jwksUri configured in each rule to fetch the certs remotely to verify the jwt tokens.
We have backup server using different domain (hosted elsewhere) can be used to load balance or fallback to when the primary server fails.

**Comment by jewertow** [comment]
This enhancement should be requested in Envoy first.

**Comment by tugtugtug** [comment]
> The selection of each retry can be either load balanced or randomly selected from the configured array.

Thanks @jewertow, can you please elaborate why? I thought istio calls https://github.com/istio/istio/blob/c63341e70474925abf50128e561eb8554819d4e0/pilot/pkg/model/jwks_resolver.go#L121 for the jwks resolution?

**Comment by leosarra** [comment]
> > The selection of each retry can be either load balanced or randomly selected from the configured array.
> 
> Thanks @jewertow, can you please elaborate why? I thought istio calls https://github.com/istio/istio/blob/c63341e70474925abf50128e561eb8554819d4e0/pilot/pkg/model/jwks_resolver.go#L121 for the jwks resolution?

Istio supports the jwks fetching via istiod, envoy or both (hybrid approach). The resolver is chosen based on the value of PILOT_JWT_ENABLE_REMOTE_JWKS.
Given that envoy does not support multiple jwks out of the box, I'm relucantat to implement it in the "istiod resolver" only.
That would lead to inconsistency between the two resolver.

**Comment by tugtugtug** [comment]
Hmm... Thanks @leosarra! That makes sense. While I still think this would be a good to have feature, I'm okay with the proxy workaround for now. I'll close this for now.
