### ISSUE TITLE
istioctl analyze inside bug-report keeps retrying even after having detected failure 

### ISSUE THREAD

**Issue by syw14** [istio/istio#47338]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Keep retrying for hours for failed operations like "no permission to call cluster" during 'analyze' inside istioctl bug-report

Also, worth to note that istioctl bug-report does have timeout limit but it's not working. 

### Version

```Text
N/A
```

**Comment by GregHanson** [comment]
What istio version are you using, there was a similar fix submitted not too long ago: https://github.com/istio/istio/pull/46825

**Comment by syw14** [comment]
> What istio version are you using, there was a similar fix submitted not too long ago: #46825

It's actually someone else's cluster. Not sure which version. I only accessed the bug-report. I don't think it has anything to do with namespaces though.

**Comment by hanxiaop** [comment]
> Keep retrying for hours for failed operations like "no permission to call cluster" during 'analyze' inside istioctl bug-report

I think this is related to the fix in #46825.

> Also, worth to note that istioctl bug-report does have timeout limit but it's not working.

This is known to me, and the timeout for `analyze` is also not working properly. I think I submitted a PR previously, but it wasn't been merged. Let me find it.

**Comment by hanxiaop** [comment]
It's https://github.com/istio/istio/pull/36320. Would you like to contribute to the timeout part? @syw14

**Comment by syw14** [comment]
> It's #36320. Would you like to contribute to the timeout part? @syw14

I would love to. Why that PR is not merged though?

**Comment by hanxiaop** [comment]
> I would love to. Why that PR wasn't merged though?

I thought the reason was we were lacking UX maintainers to review the PR during that time... IIRC the timeout was functioning properly before removing the galley dependency, so this seems to be a regression for quite some time.

**Comment by syw14** [comment]
> > I would love to. Why that PR wasn't merged though?
> 
> I thought the reason was we were lacking UX maintainers to review the PR during that time... IIRC the timeout was functioning properly before removing the galley dependency, so this seems to be a regression for quite some time.

Do you think we could just reopen your closed PR or you suggest I re-investigate this issue?

**Comment by hanxiaop** [comment]
> > > I would love to. Why that PR wasn't merged though?
> > 
> > 
> > I thought the reason was we were lacking UX maintainers to review the PR during that time... IIRC the timeout was functioning properly before removing the galley dependency, so this seems to be a regression for quite some time.
> 
> Do you think we could just reopen your closed PR or you suggest I re-investigate this issue?

You could re-investigate it since it received no comments. Feel free to use any code from my PR that you find helpful.
