### ISSUE TITLE
how to invoke an external service

### ISSUE THREAD

**Issue by adoo123** [istio/istio#4733]
Hello,i have a problem with invoke an external service.
  I use istio0.6 in my kubernetes cluster.I have a tomcat image,and pinpoint-agent inside, when I "kubectl apply " this deployment(tomcat image),the pinpoint-agent can connect pinpoint-server success.But when I "kubectl apply " with istio, it couldn't connect pinpoint-server.My pinpoint-server is outside the kubernetes cluster.
  I have already found some information on https://istio.io/docs/guides/integrating-vms.html, does it means I just can register a outside service and add ENV in yaml file ,maybe i need modify the code to use ENV, before  use it? It's too troublesome.Because I have a lot of outside service such as mysql,redis ,mango...So could you please help me with this problem?

**Comment by ymesika** [comment]
By default Istio pods can't access services outside of the cluster.
Please take a look here: https://istio.io/docs/tasks/traffic-management/egress.html for more details.

**Comment by linsun** [comment]
@vadimeisenbergibm also published a few blogs on this.  Unfortunately you'd have to write egress rules for it, but it does give you full control on what external services you can access.  

https://istio.io/blog/2018/egress-tcp.html
https://istio.io/blog/2018/egress-https.html
