### ISSUE TITLE
Spammy "default revision" sync logs

### ISSUE THREAD

**Issue by sschepens** [istio/istio#47336]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We're seeing a lot of logs of this kind:
```
info waiting for sync... name=default revision attempt=59800 time=1h40m9.375212247s
```

They seem to come from `DefaultWatcher` which seems to be used for leader election. It would seem like the controller never really finishes syncing and we're not seeing any error specifying what's going on.

Don't know if this is something that's supposed to happen.

### Version

```Text
1.19.3
```

**Comment by hanxiaop** [comment]
I think this is expected when the controller doesn't win the leaderelection?
