### ISSUE TITLE
No mTLS to pods in terminating state after Istio upgrade to 1.18 (headless service)

### ISSUE THREAD

**Issue by stefan-marcu** [istio/istio#47348]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We recently upgraded Istio from 1.16.1 to 1.18.0. After the upgrade we noticed that some workloads that are using headless services are starting to fail when pods have long terminating times.

Setup:
- We have a deployment with haproxy (+ istio proxy) that manages the sticky sessions which connects to another deployment running the application itself (+istio proxy). 
- The application deployment has a long termination period and while in terminating state we need to access the pods for a specific amount of time.
- On the application side we have defined a PeerAuthentication object with mTLS set to STRICT and we have Authorization policies defined using principles

Before 1.18, everything was working as expected. However, after the upgrade to 1.18 we noticed that when haproxy tries to reach one of the pods that has entered the terminating state, it starts doing the request using http (it does not provide the spiffe header) and not mTLS. Which means all requests are failing.

We have pinpointed the issue to version 1.18.0, meaning 1.17.8 and below are working fine. We also upgraded 1.19.3 and the issue persists.

### Version

```Text
❯ istioctl version
client version: 1.19.1
control plane version: 1.18.3
data plane version: 1.18.3 (459 proxies)

❯ kubectl version --short
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.24.14-gke.2700
```

**Comment by howardjohn** [comment]
I think this was probably related to a change I made to derive service account info from endpoints. Likely we need to consider unhealthy in that case -- or hopefully its that simple, at least.

**Comment by howardjohn** [comment]
Unfortunately I think the logic is probably going to be wonky if we don't have `features.SendUnhealthyEndpoints` set. Maybe we need to split that flag so the endpoints are available [here](https://github.com/istio/istio/blob/375951a74976f4bc9860faa43c4105dbcdecdbb5/pilot/pkg/model/endpointshards.go#L346) and just filtered.

Although for headless this may be different, probably need to look a bit deeper

**Comment by stefan-marcu** [comment]
If you need more clarification of the setup, via a diagram, let me know.

**Comment by howardjohn** [comment]
I can reproduce
