### ISSUE TITLE
EnvoyFilter does not get applied (panics) with 1.19

### ISSUE THREAD

**Issue by fraenkel** [istio/istio#47359]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When our EnvoyFilter is attempted to be applied, we see the following in the istiod logs
```
2023-10-13T23:52:01.847014Z	error	listeners patch / caused panic, so the patches did not take effect
2023-10-13T23:52:01.847078Z	error	Observed a panic: &runtime.TypeAssertionError{_interface:(*abi.Type)(0x2ab5080), concrete:(*abi.Type)(nil), asserted:(*abi.Type)(0x2e56c80), missingMethod:""} (interface conversion: protoreflect.ProtoMessage is nil, not *listenerv3.Filter)
goroutine 589 [running]:
istio.io/istio/pilot/pkg/util/runtime.LogPanic({0x2aa9b80, 0xc002549d40})
	istio.io/istio/pilot/pkg/util/runtime/runtime.go:29 +0x47
istio.io/istio/pilot/pkg/util/runtime.HandleCrash({0xc0021e2b30, 0x2, 0xc000100000?})
	istio.io/istio/pilot/pkg/util/runtime/runtime.go:37 +0x51
panic({0x2aa9b80?, 0xc002549d40?})
	runtime/panic.go:914 +0x21f
istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter.patchNetworkFilter(0x1, 0xc00234ba80?, 0x30607b1?, 0x0?, 0xc0023d56d0)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go:478 +0x588
istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter.patchNetworkFilters(0x1, 0xc002549c80?, 0xc000000002?, 0xc00234ba80)
```

If I drop back to 1.18.5 for pilot, it generates the correct configs.

### Version

```Text
istioctl version hangs
but I have tried 1.19.0 and 1.19.3

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2-eks-f8587cb
```

**Comment by wulianglongrd** [comment]
It seems to be caused by the failure of patch value conversion. Can you provide your envoyfilter to help reproduce?
Can you see the following in the istiod logs?
```
failed to build envoy filter value: ....
```

**Comment by fraenkel** [comment]
So I should be more clear, we have 3 matching resources. a job, and 2 stateful sets which both have a headless and clusterip service behind them. The job succeeds but the two stateful sets fail.

The envoyfilter 
```
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 0s
```

And the `failed to build` is
```
2023-10-13T17:37:42.627834Z	error	model	failed to build envoy filter value: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
```

**Comment by wulianglongrd** [comment]
I use [this example](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/web/web.yaml) to test and it didn't reproduce. I use istio 1.19.1, istiod log and config dump are ok.

```code
{
  "name": "envoy.filters.network.tcp_proxy",
  "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
    "stat_prefix": "outbound|80||nginx.default.svc.cluster.local",
    "cluster": "outbound|80||nginx.default.svc.cluster.local",
    "idle_timeout": "0s"
  }
}

{
  "name": "envoy.filters.network.tcp_proxy",
  "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
    "stat_prefix": "inbound|80||",
    "cluster": "inbound|80||",
    "idle_timeout": "0s"
  }
}
```

**Comment by wulianglongrd** [comment]
Wait for others to take a look.

**Comment by zirain** [comment]
can you try with v3?

**Comment by wulianglongrd** [comment]
The istiod error log says it is `v2.TcpProxy`, but the envoyfilter patch you gave says it is `v3.TcpProxy`. This is the difference. If you turn off istiod webhook and patch `v2.TcpProxy`, you will get this panic.

**Comment by fraenkel** [comment]
But why don't I see the issue with the Job. It only occurs with the stateful sets.
Either way I will try v3 and see what happens.

**Comment by fraenkel** [comment]
I am a bit confused.  The webhook is always enabled. If I were to disable it, no sidecar would be injected.

This also doesn't explain what changed between 1.18 and 1.19 to cause this panic.

**Comment by fraenkel** [comment]
So there is something else going on. If I tweak the envoyfilter so it matches nothing, it still panics.
And currently there is no `failed to build` message but the panic exists.

Ok sorry, that failed to build is for some other bogus filter.

**Comment by fraenkel** [comment]
So removing an unrelated filter at least to these services did stop the panic.. The bad filter was in a different namespace with different selectors so I don't really understand why it affected these two stateful sets.

**Comment by wulianglongrd** [comment]
I guess both the bad filter and the correct filter selected stateful sets, but the bad filter did not select the Job service.

**Comment by fraenkel** [comment]
Either removing the offending envoyfilter or fixing it resolved the panic. Still doesn't explain why if affected only 2 out of 100s of pods.

**Comment by fraenkel** [comment]
Nope. The bad filter is in a completely different manager and with non
matching selector.

**Comment by saansh45** [comment]
@wulianglongrd we are also see the same issue with `1.19.3` 

```
2023-10-18T19:25:06.272893Z	error	Observed a panic: &runtime.TypeAssertionError{_interface:(*abi.Type)(0x2ab5080), concrete:(*abi.Type)(nil), asserted:(*abi.Type)(0x2e56c80), missingMethod:""} (interface conversion: protoreflect.ProtoMessage is nil, not *listenerv3.Filter)
goroutine 13213 [running]:
istio.io/istio/pilot/pkg/util/runtime.LogPanic({0x2aa9b80, 0xc00500d440})
	istio.io/istio/pilot/pkg/util/runtime/runtime.go:29 +0x47
istio.io/istio/pilot/pkg/util/runtime.HandleCrash({0xc00541aba0, 0x2, 0x4321aa?})
	istio.io/istio/pilot/pkg/util/runtime/runtime.go:37 +0x51
```

Here is the `failed to build envoy filter value:`

```
error	model	failed to build envoy filter value: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
error	model	failed to build envoy filter value: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
error	model	failed to build envoy filter value: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
error	model	failed to build envoy filter value: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
```

**Comment by wulianglongrd** [comment]
It is recommended to use `v3` instead of `v2`.
