### ISSUE TITLE
istio seems to be closing connections to a managed postgress DB (external) 

### ISSUE THREAD

**Issue by lserranov72** [istio/istio#47378]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a kubernetes Application that uses an istio companion proxy. The App was writen in golang and uses gorm to connect to an external database. 

We have noticed that if we do higher traffic (like 2 to 200 TPS) all is good. However if I run 1 request/minute for long time, eventually the application will have bad response time. The culprit will be that queries to the DB will take 1 or 2 seconds instead of 10-20ms and I will see this in the logs:

{"level":"error","msg":"write tcp 10.32.33.24:12780-\u003e127.0.0.6:41129: write: broken pipe","time":"2023-10-13T00:09:29.280997Z"}

We have done a lots of tuning at the grom level tweaking:

 DB_CONN_MAX_LIFETIME:
 DB_MAX_IDLE_CONNS: 
 DB_CONN_MAX_IDLE_TIME:
 DB_MAX_OPEN_CONNS: 
 
 However looks like there is no config that helps. We tried making  DB_MAX_IDLE_CONNS=0 and that helps but with that setting performance suffer badly at higher traffic. 
 
I was looking at https://github.com/istio/istio/issues/24856 and somebody suggested to have an annotation like this:

annotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "5432"

I did it and it seems to work. 

So I would like to ask if  traffic.sidecar.istio.io/excludeOutboundPorts  is an advisable config to use because in the following link I see it as  an alpha feature  https://istio.io/latest/docs/reference/config/annotations/
 
 Also, if above "hack" has downsides, based on the explanation I gave, is there a better recomendation on what to do to fix the problem? 
 
 Thanks!

### Version

```Text
Istio version:
kubectl get deployment istiod -n istio-system -o jsonpath='{.spec.template.spec.containers[0].image}'

docker.io/istio/pilot:1.16.0

# kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.11
```

**Comment by GregHanson** [comment]
> downsides

per the docs for that annotations, traffic on that port will not be redirected to envoy

> traffic.sidecar.istio.io/excludeOutboundPorts
> A comma separated list of outbound ports to be excluded from redirection to Envoy.

This means that you are bypassing any istio related feature, such as traffic redirection, authentication policies, and metrics

>is there a better recomendation on what to do to fix the problem?

I think alternatives are going to vary by client/env.  I assume in your tests above, you had a ServiceEntry defined for the external postures DB?  If not, you are relying on routing through PassthroughCluster - I would not expect the best results for persistent/long-running database connections.  If you are still seeing poor behavior even with a ServiceEntry, you could try modifying various timeouts/keep-alives at the CLUSTER or LISTENER level via EnvoyFilter/DestinationRule.  You could also define an EnvoyFilter to add a specific [postgres_proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter#config-network-filters-postgres-proxy) filter for port 5432
