### ISSUE TITLE
admit_test.go cannot find ca.crt in extension-apiserver-authentication

### ISSUE THREAD

**Issue by esnible** [istio/istio#4737]
Running `make test` fails with

```
--- FAIL: TestGetAPIServerExtensionCACert (0.27s)
	admit_test.go:469: GetAPIServerExtensionCACert() failed: cannot find ca.crt in extension-apiserver-authentication: ConfigMap.Data is map[string]string{"client-ca-file":"-----BEGIN CERTIFICATE-----
... removed ...
-----END CERTIFICATE-----\n"}
FAIL
```

I am seeing this with both _pilot/pkg/kube/admit/admit_test.go_ and _mixer/pkg/config/crd/admit_test.go_.

I am not sure when this started happening.  I am using commit 4f27c988f7db1cb6afd0677059a989357b8394c5 from April 2.  Several folks have reproduced this.

**Comment by xiaolanz** [comment]
Which cluster did you test it with? This test requires access to a kube api server.

**Comment by ayj** [comment]
I'm refactoring the validation code and removing removing dependency on the api-server `ca.crt` in the process. This issue should be N/A in a few days.

**Comment by esnible** [comment]
@xiaolanz I tested it with a free cluster on IBM Cloud Container Service.  The file is not mentioned yet _tools/vagrant/Vagrantfile_ includes a script that creates a ca.crt on the local environment.  _istio/bin/testEnvLocalK8S.sh_ does something with the file as well.

Jason's comment suggests I shouldn't worry about it.  I had thought perhaps this is a DEV-GUIDE oversight.

**Comment by esnible** [comment]
I was able to fix this by doing `kubectl edit cm -n kube-system extension-apiserver-authentication` and setting data.requestheader-client-ca-file to a valid certificate value I copied from a working test env.

The error message looks wrong in both versions of admit.go:
```
	pem, ok := c.Data["requestheader-client-ca-file"]
	if !ok {
		return nil, fmt.Errorf("cannot find ca.crt in %v: ConfigMap.Data is %#v", name, c.Data)
```

It is trying to find _requestheader-client-ca-file_ yet it reports that it is looking for _ca.crt_.

**Comment by esnible** [comment]
@ayj If my analysis is correct shall I repurpose this work item to be about the error messages reporting the wrong failure?  I can submit a 2-line PR for better messages or we can close as unneeded if you are fixing this elsewhere.

**Comment by ayj** [comment]
Thanks for triaging the issue @esnible. This code path and error message will be removed by https://github.com/istio/istio/pull/4811.
