### ISSUE TITLE
Mismatch of istio_build gauge metrics description

### ISSUE THREAD

**Issue by ymesika** [istio/istio#47397]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The `istio_build` gauge metric is being reported by various Istio components.

With 1.18 we sometimes experience errors collecting these metrics by a prometheus exporter because of a mismatch of the existence/empty of the HELP text for the metric (`gauge has help "Istio component build info" but should have ""`) in different components.
I think we hit this error in cases when the metric is first collected (and therefore initialized) from the sidecars.

Specifically istiod reports something like:
```
# HELP istio_build Istio component build info
# TYPE istio_build gauge
istio_build{component="pilot",tag="1.18.1-30-gba3555469c05"} 1
```

while the stats filter of the sidecars reports the metric without `HELP` text:
```
# TYPE istio_build gauge
istio_build{component="proxy",tag="1.18-dev"} 1
```

We experienced this issue with 1.18.0-1.18.3 but I think it can potentially appear in 1.19+ as well.

### Version

```Text
1.18.3
```

**Comment by ymesika** [comment]
@kyessenov Does it make sense to add the HELP text to the stats filter as well?

**Comment by zirain** [comment]
does envoy support HELP text?

**Comment by ymesika** [comment]
> does envoy support HELP text?

I was wondering myself too and I don't think they do with current impl.

**Comment by krisztianfekete** [comment]
This is not an envoy metric, but an Istio one that reports its tag for the proxies, so the HELP text should be handled by Istio.

**Comment by ymesika** [comment]
> This is not an envoy metric, but an Istio one that reports its tag for the proxies, so the HELP text should be handled by Istio. Also, this only become an issue recently, although I was not able to find where did it break.

@krisztianfekete the Istio stats filter in the proxy is using an envoy telemetry library. I guess the question from @zirain was whether this library supports adding a HELP text to the gauge instance.

**Comment by ymesika** [comment]
> IIRC, envoy don't support HELP text, so I'm not sure what can istio do.

One option is to remove the HELP from Istiod.

**Comment by zirain** [comment]
@ymesika where did you got that error message? I didn't see that with prometheus.

**Comment by ymesika** [comment]
> @ymesika where did you got that error message? I didn't see that with prometheus.

We use [prometheusexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter) in our stack and we see it over there.

**Comment by howardjohn** [comment]
How can you have an expectation that every pod in the entire cluster has the same definitions for metrics? That seems like an invalid expectation.

**Comment by krisztianfekete** [comment]
AFAIK a metric can only have a single HELP text. Here we have a metric with different labels/dimensions, but should only be exposed as a single metric with a single HELP definition.

**Comment by howardjohn** [comment]
Within a single target, sure. But you are comparing across two targets. Do you expect no conflicts in any metrics names across all targets in a multi-tenant environment?

**Comment by krisztianfekete** [comment]
Yes, I do. Just like I'd expect a single and uniform istio_requests_total metric across multiple Istio meshes/tenants.

**Comment by howardjohn** [comment]
`up` is a common metric. Do you really expect EVERY application defines the exact same health text for `up`? It seems a bit farfetched and not how Prometheus works either.

**Comment by krisztianfekete** [comment]
`up` is added by Prometheus automatically for every targets, so that will be consistent for sure.

**Comment by zirain** [comment]
@ymesika you're using something like otel-collector with a pipeline `prometheus receiver -> other components -> prometheus exporter`?

**Comment by krisztianfekete** [comment]
@zirain, yes. Basically we have OTel collectors running in clusters where Istio is running, these have prometheus receivers. Then, these push into another OTel collector (running as a gateway), and this one has prometheus exporter. We are seeing this in the collector deployed as a gateway.

**Comment by zirain** [comment]
I think this's edge case about prometheus, this won't happen with https://github.com/prometheus/client_golang.
Remove the help text in istiod will fixed the issue, but in a bad way.

**Comment by krisztianfekete** [comment]
Using OTel collectors is gaining more and more popularity, I wouldn't really call this an edge case. Here, to me, it looks like we have an issue with metrics generation, not the way OTel (prometheus exporter) exposes the metrics. I have tested this without OTel in the picture, and got the same error (having collectors just makes it easier to notice), sorry for leaving that details out from the initial report.

 The [prometheus exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/) is also using `client_golang` by the way.

**Comment by zirain** [comment]
Alternative: 
1. moving the metric from proxy to istio-agent
2. envoy support help text

**Comment by dashpole** [comment]
Hey, I work on the OpenTelemetry collector's prometheus components.  Can you share the full error message, including which collector component it is coming from?  I suspect this is a bug in the prometheus exporter, but need to confirm.

**Comment by krisztianfekete** [comment]
Hi @dashpole, thanks for taking a look!

```
2023-09-29T15:24:02.049Z        error   prometheusexporter@v0.80.0/log.go:23    error gathering metrics: 2 error(s) occurred:
* collected metric istio_build label:{name:"app"  value:"istiod"}  label:{name:"cluster"  value:"glooplatform-central"}  label:{name:"component"  value:"pilot"}  label:{name:"install_operator_istio_io_owning_resource"  value:"unknown"}  label:{name:"instance"  value:"10.108.2.7:15014"}  label:{name:"istio"  value:"istiod"}  label:{name:"istio_io_rev"  value:"1-18"}  label:{name:"job"  value:"istiod-metrics"}  label:{name:"namespace"  value:"istio-system"}  label:{name:"operator_istio_io_component"  value:"Pilot"}  label:{name:"pod_name"  value:"istiod-1-18-5f7964bccd-jlfwh"}  label:{name:"pod_template_hash"  value:"5f7964bccd"}  label:{name:"sidecar_istio_io_inject"  value:"false"}  label:{name:"tag"  value:"1.18.2-solo"}  gauge:{value:1} has help "Istio component build info" but should have ""
* collected metric istio_build label:{name:"app"  value:"istiod"}  label:{name:"cluster"  value:"glooplatform-east"}  label:{name:"component"  value:"pilot"}  label:{name:"install_operator_istio_io_owning_resource"  value:"unknown"}  label:{name:"instance"  value:"10.104.3.14:15014"}  label:{name:"istio"  value:"istiod"}  label:{name:"istio_io_rev"  value:"1-18"}  label:{name:"job"  value:"istiod-metrics"}  label:{name:"namespace"  value:"istio-system"}  label:{name:"operator_istio_io_component"  value:"Pilot"}  label:{name:"pod_name"  value:"istiod-1-18-7d66654c46-c5frb"}  label:{name:"pod_template_hash"  value:"7d66654c46"}  label:{name:"sidecar_istio_io_inject"  value:"false"}  label:{name:"tag"  value:"1.18.2-solo"}  gauge:{value:1} has help "Istio component build info" but should have ""
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.80.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
        github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/http.go:144
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2487
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
        go.opentelemetry.io/collector/config/confighttp@v0.80.0/compression.go:111
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.80.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
        net/http/server.go:2947
net/http.(*conn).serve
        net/http/server.go:1991
```

**Comment by dashpole** [comment]
That does look like a bug in the collector's prometheus exporter.  Per the [OTel specification](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#metric-metadata-1):

> Exporters MUST drop entire metrics to prevent conflicting TYPE comments, but SHOULD NOT drop metric points as a result of conflicting UNIT or HELP comments. Instead, all but one of the conflicting UNIT and HELP comments (but not metric points) SHOULD be dropped. If dropping a comment or metric points, the exporter SHOULD warn the user through error logging.

I.e. we should be accepting the conflicting description, and choosing one description to keep, and one to drop, and warning the user.

**Comment by dashpole** [comment]
Filed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28617

**Comment by zirain** [comment]
not stale
