### ISSUE TITLE
Istio Resource override not fully applied

### ISSUE THREAD

**Issue by nitinatgh** [istio/istio#47403]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When one group (CPU/Mem) of Istio resource is set via the [annotations](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection), the other group is not applied. As a result if an application has Kubernetes HPA configured then it will fail as all containers do not have the CPU request set which is a requirement by Kubernetes.

Regardless which group is set, it should then take the default if one is missing. Otherwise both groups of request and limits need to be explicitly be set.

Istio Annotations set for memory only
<img width="308" alt="image" src="https://github.com/istio/istio/assets/86051350/1335c3b7-f9c4-4ac2-aad6-d15e0e498a63">

Only Istio Memory Resources set and not CPU
<img width="186" alt="image" src="https://github.com/istio/istio/assets/86051350/7d657675-d15c-460a-8777-e754a35851c9">

Error from Kubernetes as a result of no CPU set
<img width="1104" alt="image" src="https://github.com/istio/istio/assets/86051350/32fa7d35-6e4e-4af9-9366-5577feec4cbe">

Incorrect logic where resources are set via annotations and the injector
https://github.com/istio/istio/blob/a49ca8541c69b89f5c2b31ccd8e02b5e854d2d56/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L1-L26 

### Version

```Text
Istio
client version: 1.18.0
control plane version: 1.19.1
data plane version: 1.17.1 (29 proxies), 1.19.1 (20 proxies)

Kubernetes
Client Version: v1.27.5-eks-43840fb
Kustomize Version: v5.0.1
Server Version: v1.24.16-eks-2d98532
```

**Comment by nitinatgh** [comment]
lifecycle/staleproof

**Comment by nitinatgh** [comment]
Hi @ymesika , is this fixed then based on the change done https://github.com/istio/istio/pull/48404 , or still pending? 
Thanks

**Comment by ymesika** [comment]
@nitinatgh I closed the PR (can't recall why) so this issue is still pending a fix.
not stale

**Comment by ymesika** [comment]
I re-opened the PR.
I think the reason I closed it previously was because I mistakenly thought the [doc](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection) mentions that not setting a limit/request while setting the other one will imply unlimited. E.g:
> If sidecar.istio.io/proxyCPU is set, make sure to explicitly set sidecar.istio.io/proxyCPULimit. Otherwise the sidecar’s cpu limit will be set as unlimited.

But this is a different scenario than the one mentioned in this issue.

**Comment by roman-shandurenko** [comment]
@ymesika Where is your re-opened PR? Can't find it.
I hope it will be reviews sometime soon because have the same issue and had to workaround with "defaults" as well...

**Comment by roman-shandurenko** [comment]
up
