### ISSUE TITLE
Trigger workload cert rotate immediately

### ISSUE THREAD

**Issue by zirain** [istio/istio#47402]
considering to trigger workload cert rotate immediately when receive PCDS.

https://github.com/istio/istio/blob/eb0f84cd483e23bea8dca14455602a2dca8ef8e1/security/pkg/nodeagent/cache/secretcache.go#L740-L751

cc @howardjohn @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@zirain Do you have bandwidth to add a integration test for root cert rotation

**Comment by zirain** [comment]
I will do that after fixe this.

**Comment by jaellio** [comment]
Is the integration test a blocker for v1.20?

**Comment by zirain** [comment]
it's off by default, protected by two feature flag(ISTIO_MULTIROOT_MESH, PROXY_CONFIG_XDS_AGENT).

**Comment by zirain** [comment]
linked to https://github.com/istio/istio/pull/47641

**Comment by zirain** [comment]
fixed by #47641

**Comment by jaellio** [comment]
> fixed by #47641

Did this change make it into v1.20?

**Comment by hzxuzhonghu** [comment]
I think no, will add a cherrypick label
