### ISSUE TITLE
How to pass per-route service config to mixer client filter in Envoy v2 rDS

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#4743]
Currently, in Envoy v1:  we uses two flags

"mixer"  and "mixer_sha".   Not sure if we can continue these use these opaque metadata

**Comment by qiwzhang** [comment]
@mandarjog @lizan

**Comment by lizan** [comment]
https://github.com/envoyproxy/data-plane-api/pull/605 a PR is posted, we can start plan a migrate path.

**Comment by rshriram** [comment]
solved by pilot plugin arch and the per filter config in envoy

**Comment by kyessenov** [comment]
I don't think the current architecture is flexible enough. There are details in a doc how to apply mixer filter setings.

**Comment by andraxylia** [comment]
@kyessenov is this still an issue?
