### ISSUE TITLE
ambient mesh doesn't support docker desktop kubernetes

### ISSUE THREAD

**Issue by chingkt** [istio/istio#47436]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Docker desktop uses `kubenet` as the CNI plugin by default, which supports veth, which is required to run ambient mesh. So theoretically, it should already support ambient mesh. However, some user [complained](https://github.com/docker/roadmap/issues/311) not being able to use it. I have tried this official [tutorial](https://istio.io/latest/docs/ops/ambient/getting-started/) but failed at the application deployment step. Error messages from the istio-cni-node:

```2023-10-18T17:31:37.905799Z     error   controllers     error handling istio-system/ztunnel-zs72z, retrying (retry count: 1): failed to get veth device: no routes found for 10.1.1.58 controller=ambient
2023-10-18T17:48:15.521939Z     error   ambient Failed to list ipset entries: failed to list ipset ztunnel-pods-ips: no such file or directory
2023-10-18T17:48:15.522510Z     info    ambient Pod 'notsleep-5ccf57569-g54sh/default' (9411ba7d-70bf-4981-a958-f92bea4cdcaa) is not in ipset
2023-10-18T17:48:15.553004Z     error   ambient Failed to list ipset entries: failed to list ipset ztunnel-pods-ips: no such file or directory```

### Version

```Text
$istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (1 proxies)

$kubectl version --short              
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.2
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/13033020/bug-report.tar.gz)

**Comment by bleggett** [comment]
There's an open issue with docker desktop around lack of support for CNI plugins generally (including e.g. Cilium): https://github.com/docker/roadmap/issues/311

**Comment by bleggett** [comment]
The other error mentioned/seen: 

```
│   Warning  FailedCreatePodSandBox  14s               kubelet            Failed to create pod sandbox: rpc error: code = Un ││ known desc = [failed to set up sandbox container "b7493d90e9d5e93f486a74cef208c72fc7b8ba9fb54845c0caa28cb4e460b2db" networ  │ k for pod "httpbin-86869bccff-pq7vj": networkPlugin cni failed to set up pod "httpbin-86869bccff-pq7vj_default" network: p ││ lugin type="loopback" failed (add): missing network name:, failed to clean up sandbox container "b7493d90e9d5e93f486a74cef ││ 208c72fc7b8ba9fb54845c0caa28cb4e460b2db" network for pod "httpbin-86869bccff-pq7vj": networkPlugin cni failed to teardown  ││ pod "httpbin-86869bccff-pq7vj_default" network: plugin type="loopback" failed (delete): missing network name]              ││   Normal   SandboxChanged          0s (x2 over 14s)  kubelet            Pod sandbox changed, it will be killed and re-created │
```

This seems to be because `docker-desktop` uses a loopback plugin at lowest priority that runs last, and doesn't actually support the current CNI version spec?

**Comment by linsun** [comment]
Hi @chingkt - thank you for reporting this!   it is a good time to evaluate this again, I believe with the latest istio-cni change https://github.com/istio/istio/issues/48212, ambient for docker desktop k8s should be supported.  While the PRs are still under review, can you try it following the instructions below?

https://github.com/istio/istio/issues/48212#issuecomment-1864725172

**Comment by linsun** [comment]
This is resolved, please try latest master or release 1.21 build, or wait for the official 1.21 release.  see https://github.com/istio/istio/issues/48212

**Comment by linsun** [comment]
Sorry, just got confirmation from Eric that the change is not in beta 0 yet, but should be in -beta.1 since it was merged after beta.0 was released. I expect that the new build will be available in a day or 2.

**Comment by harsh4870** [comment]
Thank you team for help & support however facing issue with Ambient **Beta-1** release Docker Desktop M1

```
kubectl -n istio-system get pods                  
NAME                                    READY   STATUS              RESTARTS   AGE
istio-cni-node-8njst                    1/1     Running             0          116s
istio-ingressgateway-689f9d6fb4-4qssc   1/1     Running             0          20m
istiod-556d7d4cf5-ndg7m                 1/1     Running             0          20m
ztunnel-78ldc                           0/1     Terminating         0          20m
ztunnel-zx8m7                           0/1     ContainerCreating   0          54s
```

```
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               6m28s                 default-scheduler  Successfully assigned istio-system/ztunnel-zx8m7 to docker-desktop
  Warning  FailedCreatePodSandBox  6m27s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to set up pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (add): missing network name:, failed to clean up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to teardown pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (delete): missing network name]
```

**Comment by harsh4870** [comment]
Created issue - https://github.com/istio/istio/issues/49208

**Comment by gjycn** [comment]
> Thank you team for help & support however seeing issue with Ambient **Beta-1** release Docker Desktop M1
> 
> ```
> kubectl -n istio-system get pods                  
> NAME                                    READY   STATUS              RESTARTS   AGE
> istio-cni-node-8njst                    1/1     Running             0          116s
> istio-ingressgateway-689f9d6fb4-4qssc   1/1     Running             0          20m
> istiod-556d7d4cf5-ndg7m                 1/1     Running             0          20m
> ztunnel-78ldc                           0/1     Terminating         0          20m
> ztunnel-zx8m7                           0/1     ContainerCreating   0          54s
> ```
> 
> ```
> Events:
>   Type     Reason                  Age                   From               Message
>   ----     ------                  ----                  ----               -------
>   Normal   Scheduled               6m28s                 default-scheduler  Successfully assigned istio-system/ztunnel-zx8m7 to docker-desktop
>   Warning  FailedCreatePodSandBox  6m27s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to set up pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (add): missing network name:, failed to clean up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to teardown pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (delete): missing network name]
> ```

same issue on Windows 11, docker-desktop 4.28.0 base wsl2, linux kernel is "6.1.21.2-microsoft-standard-WSL2+", k8s version is "1.29.1", istio version is "1.21.0-rc.1"

**Comment by bleggett** [comment]
> > Thank you team for help & support however seeing issue with Ambient **Beta-1** release Docker Desktop M1
> > ```
> > kubectl -n istio-system get pods                  
> > NAME                                    READY   STATUS              RESTARTS   AGE
> > istio-cni-node-8njst                    1/1     Running             0          116s
> > istio-ingressgateway-689f9d6fb4-4qssc   1/1     Running             0          20m
> > istiod-556d7d4cf5-ndg7m                 1/1     Running             0          20m
> > ztunnel-78ldc                           0/1     Terminating         0          20m
> > ztunnel-zx8m7                           0/1     ContainerCreating   0          54s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Events:
> >   Type     Reason                  Age                   From               Message
> >   ----     ------                  ----                  ----               -------
> >   Normal   Scheduled               6m28s                 default-scheduler  Successfully assigned istio-system/ztunnel-zx8m7 to docker-desktop
> >   Warning  FailedCreatePodSandBox  6m27s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to set up pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (add): missing network name:, failed to clean up sandbox container "c88ecf6787ad644d31272bff249c3a6320a86cb5734dc975fd08169f25fb6442" network for pod "ztunnel-zx8m7": networkPlugin cni failed to teardown pod "ztunnel-zx8m7_istio-system" network: plugin type="loopback" failed (delete): missing network name]
> > ```
> 
> same issue on Windows 11, docker-desktop 4.28.0 base wsl2, linux kernel is "6.1.21.2-microsoft-standard-WSL2+", k8s version is "1.29.1", istio version is "1.21.0-rc.1"

Yes, as I mentioned above, this is a general issue with docker desktop and CNI plugins: https://github.com/istio/istio/issues/47436#issuecomment-1769526105

`docker desktop` uses broken CNI plugins that do not correctly support the CNI spec, and as such do not properly support custom CNIs, see also https://github.com/docker/for-mac/issues/4626

1. `docker desktop`'s support for CNI plugins is broken.
2. Use `minikube` or `kind` or anything else, and you won't have this problem.
