### ISSUE TITLE
Envoy filter for rewriting gRPC replies works partially only

### ISSUE THREAD

**Issue by fredo393** [istio/istio#47454]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

For security reasons we do not want to expose error descriptions to the outside. We have set up a filtering using Envoyfilter and see this working for gRPC only partially: message are replaced as intended only if the status code is not containing "_". For status i.e. UNIMPLEMENTED the replacement works for NOT_FOUND it fails.
The attachement contains the filter definition and its resulting behaviour.

### Version

```Text
$ istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (167 proxies)

$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Additional Information

[result.zip](https://github.com/istio/istio/files/13040413/result.zip)

**Comment by GregHanson** [comment]
I would try enabling more verbose logging on the proxy/sidecar in question
```
istioctl pc log <pod_name>.<pod_ns> --level <trace|debug>
# capture working and broken cases, then reset back to default
istioctl pc log <pod_name>.<pod_ns> --reset
```
and step through the logs to see where they differ.  possible there is another error message at the finer granularities

**Comment by fredo393** [comment]
Thanks for replying @GregHanson.
We enabled both debug & trace logs and we tried it out . Below the logs with both negative and positive cases. 
 
[proxy-debug.log](https://github.com/istio/istio/files/13187330/proxy-debug.log)
[proxy-trace.log](https://github.com/istio/istio/files/13187331/proxy-trace.log)

**Comment by minopolous** [comment]
Is it possible to see from the trace logging why "_"-containing grpc states fail to be sanitized while other states are catched by the filter correctly?

**Comment by fredo393** [comment]
@minopolous no. We checked the trace logging ([proxy-trace.log](https://github.com/istio/istio/files/13190229/proxy-trace.log)) and found nothing.

**Comment by minopolous** [comment]
@GregHanson would you mind having a quick look to the log?
