### ISSUE TITLE
error in getting aws info for iam/info : Get "http://169.254.169.254/latest/meta-data/iam/info": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by ikersuen** [istio/istio#47482]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When we enabled debug log, we can see the error below:

`2023-10-20T02:41:22.711317Z    debug    error in getting aws info for iam/info : Get "http://169.254.169.254/latest/meta-data/iam/info": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

It's from IsAWS function checking the platform for bootstrapping is Amazon Web Services, however seems there maybe some problem with fetching the header.

`Code PATH: istio/pkg/bootstrap/platform/aws.go`

Any suggested action can be done to troubleshoot this issue?

### Version

```Text
$ istioctl version
client version: 1.14.3
control plane version: 1.18.2
data plane version: 1.18.2 (6 proxies)
$ kubectl version --short
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.26.7-eks-2d98532
```

**Comment by zirain** [comment]
related to https://github.com/istio/istio/pull/46312?

**Comment by ikersuen** [comment]
> related to #46312?

@zirain seems related, the change will be launched in next release?

**Comment by zirain** [comment]
yes, it would be.

**Comment by ikersuen** [comment]
After resolving some network issue, opening network policy to allow egress to the endpoint, we are getting 401

`2023-10-20T03:32:51.388189Z    debug    error in getting aws info for iam/info : unexpected status 401`

@zirain is the fix catering this problem?
