### ISSUE TITLE
A multi-cluster node authorizer to support multi-cluster scenario in ambient mesh

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#47489]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

It's normal to respectively deploy the control plane and data plane of Istio in different clusters in real production. The deployment pattern in the implementation of service mesh products by cloud providers similar to [Install Istio with an External Control Plane](https://istio.io/latest/docs/setup/install/external-controlplane/) has also become normal.

Let's assume the use case of deploying ztunnels in remote cluster and managing them by istiod in external cluster in ambient mesh. However, ztunnel can't be correctly started in remote cluster based on before assumption. After some investigation, we found out that it has some relates with the `NodeAuthorizer` which fails to authenticate ztunnel in remote cluster.

Basically, this is a really issue occurred in the CSP environment, so we promote a proposal [A multi-cluster node authorizer to support multi-cluster scenario in ambient mesh](https://docs.google.com/document/d/10uf4EvUVif4xGeCYQydaKh9Yaz9wpysao7gyLewJY2Q/edit?resourcekey=0-6i9VYHbp91h6Avy6syu_oA#heading=h.xw1gqgyqs5b) to address this issue.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Following the docs [Install Istio with an External Control Plane](https://istio.io/latest/docs/setup/install/external-controlplane/) and deploying remote cluster with CNI and ambient enabled via Helm(refer to the ambient enable doc), there are 2 parts error messages from both istiod and ztunnel:

**istiod part:**
2023-10-22T11:36:59.963289Z  warn  serverca  impersonation failed: pod istio-system/ztunnel-95fqc not found
![image](https://github.com/istio/istio/assets/4101246/5094404f-2201-4ce8-a14a-1d4df3685ec7)

**ztunnel part:**
2023-10-22T11:36:59.965968Z ERROR ztunnel::cert_fetcher: unable to prefetch cert for "spiffe://cluster.local/ns/default/sa/sleep", skipping, SigningRequest(Status { code: Unauthenticated, message: "request impersonation authentication failure", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None })
![image](https://github.com/istio/istio/assets/4101246/9ab2ab51-e35b-4bc5-8e25-65786eace501)

**Comment by imroc** [comment]
Same issue, any update?

**Comment by imroc** [comment]
> > Same issue, any update?
> 
> Hi @imroc, we are moving forward and there should be some discussion on the `Istio Ambient Weekly Meeting` in recent.

Gotcha, thanks

**Comment by zhlsunshine** [comment]
Hi @imroc, this issue has been fixed, please let me know the details if you want to use it. ^_^
