### ISSUE TITLE
Mixer keeps restarting on build 0.8.0-pre20180404-09-15, missing config file

### ISSUE THREAD

**Issue by jnativio** [istio/istio#4749]
The istio-proxy container cannot find /etc/istio/proxy/envoy_mixer.json and after several times trying, the mixer pod is restarted in a loop (CrashLoopBackOff). 
This is the contents of the /etc/istio/proxy dir on this build:
-rw-r--r-- 1 root root 3245 Apr  4 09:20 envoy_pilot_auth.json
-rw-r--r-- 1 root root 1914 Apr  4 09:20 envoy_pilot.json
-rw-r--r-- 1 root root 4453 Apr  4 09:20 envoy_istio_telemetry_auth.json
-rw-r--r-- 1 root root 4041 Apr  4 09:20 envoy_istio_telemetry.json
-rw-r--r-- 1 root root 4753 Apr  4 09:20 envoy_istio_policy_auth.json
-rw-r--r-- 1 root root 4536 Apr  4 09:20 envoy_istio_policy.json

For 0.7.1, it was:
-rw-r--r-- 1 root root 3245 Mar 30 19:05 envoy_pilot_auth.json
-rw-r--r-- 1 root root 1914 Mar 30 19:05 envoy_pilot.json
-rw-r--r-- 1 root root 1182 Mar 30 19:05 envoy_mixer_auth.json
-rw-r--r-- 1 root root  965 Mar 30 19:05 envoy_mixer.json

So, somehow the required json file is not there anymore.
[mixer.istio-proxy.log](https://github.com/istio/istio/files/1877381/mixer.istio-proxy.log)

**Comment by kyessenov** [comment]
Yes, the files for mixer have been split into policy and telemetry. This requires changes to k8s templates to use the correct file.

**Comment by douglas-reid** [comment]
I think this can be closed. I believe this was fixed for 0.8.
