### ISSUE TITLE
Support for Istio upgrade in Kubernetes

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#475]
Istio control plane components are k8s Deployment objects and can be upgraded using the automatic Deployment rolling update functionality, by changing the deployment spec to point to the new images, via running kubectl apply  -f <new istio>.yaml.

The apps will need a new proxy injected, and new pods to be restarted. This will be handled automatically by Kubernetes only if the apps are also installed as Deployment objects. We need to document this, and reinforce the recommendation about deploying apps as Deployment objects.

We need to define, validate & document the workflow needed to upgrade Istio, for the cases when proxy was injected using the kube-inject tool or kube-inject admission controller.

When apps are Deployment objects, we must handle two cases:

- kube-inject tool was used: users need to run kubectl apply -f <(istioctl kube-inject ...) with the new image
- admission controller: we need a (new?) module that must detect the upgrade and handle it transparently by updating the Deployment specification. It may not be the same as the admission controller, who is called only during pod creation. It can be another smaller controller who watches for changes in the proxy version, in the configMap.

**Comment by ldemailly** [comment]
When we get closer to 0.3 maybe we can turn this into an epic looking at
- backward compatibility
- protocol/capabilities negotiation
- schema and data migration
- visibility and monitoring of which versions are where
- last but not least: automated testing of vN-1 vN interoperability

**Comment by terinjokes** [comment]
We recently attempted an in-place upgrade of Istio on Kubernetes. We encountered errors applying patches to the Custom Resource Definitions, and istio-ca generated a new certificate; as a result all old deployments were considered unhealthy until we manually rolled the deployments, deamonsets, and statefulsets.

**Comment by andraxylia** [comment]
@terinjokes Upgrade is not supported currently, we are working on it. For the time being, please uninstall and install the new version https://istio.io/docs/setup/kubernetes/quick-start.html.

**Comment by terinjokes** [comment]
@andraxylia I understand that it's not supported. I thought it would be helpful to understand what went wrong.

**Comment by ldemailly** [comment]
obviously from 1.0 onward we will support upgrades - maybe even earlier but for now we are focusing on features

**Comment by yusuoh** [comment]
@terinjokes @mhamann I am drafting a design doc for Istio upgrade. It's still WIP but you can take a preview at https://docs.google.com/document/d/1oxrlCgL7R0b_r4aIIFyBne2IxN1Lof3edo9YPy6h2Yk/edit

**Comment by mhamann** [comment]
@yusuoh just requested access to that doc

**Comment by GregHanson** [comment]
Kubernetes upgrade is a supported feature for istio versions 0.5.X and later.  It is part of the release process and work is underway for automating testing.

**Comment by ldemailly** [comment]
I think it may be a tiny bit early to close this, it needs more variants, testing, and doc

**Comment by scraly** [comment]
The documentation is not helpful actually: 
https://istio.io/docs/guides/upgrading-istio.html#application-setup

**Comment by ldemailly** [comment]
😮

**Comment by jasmine-jaksic** [comment]
Closing this issue. The documents were updated as part of 0.8 release, feel free to test and open new issues if the problem still exists.
