### ISSUE TITLE
Support Prefix Rewrite and Regex Rewrite for HTTP Redirections

### ISSUE THREAD

**Issue by larryli2** [istio/istio#47500]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)
**Describe the feature request**

Hi Team,
Do you have plans to support `prefix_rewrite` and `regex_rewrite` for **HTTPRedirect** which supported by Envoy (described [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-redirectaction-prefix-rewrite)).
The RegexRewrite is there in istio-api, but it is now only used for forwarding routes (in this [PR](https://github.com/istio/api/pull/2753)) 
This is a common feature when running the Istio as Edge server. Do you have any plans?

**Describe alternatives you've considered**
We didn't find any alternatives could achieve this.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
@howardjohn @keithmattix maybe something to discuss in next week's WG meeting?

**Comment by larryli2** [comment]
Hi @MorrisLaw @howardjohn @keithmattix, just wanted to check if you guys have had time to discuss this? If it make sense to you to add this feature, I can submit a PR. 
It's just one thing I'm not sure, it looks like these new fields `prefix_rewrite` and `regex_rewrite` should be structured in a `oneof` block along with the existing `uri` ([code](https://github.com/istio/api/blob/master/networking/v1beta1/virtual_service.proto#L1443)). But if we move this existing `uri` to a `oneof` block, we'll need to update some code that referring this field. In the [HTTPRewrite PR](https://github.com/istio/api/pull/2753), which has the similar situation, it is just a new field without touching the existing `uri` field.  Is this the way you would prefer?

**Comment by larryli2** [comment]
Hi @hzxuzhonghu, is it possible for you to also take a look this issue

**Comment by MorrisLaw** [comment]
Hey @larryli2 , there may be some delay in responses since people are at KubeCon this week.

**Comment by yitingdc** [comment]
We definitely need this feature!! Hope we can have it ASAP :)

**Comment by hanxiaop** [comment]
@ramaraochavali @hzxuzhonghu @howardjohn Could you take a look at this?

**Comment by rokkiter** [comment]
This feature is also very valuable to us, as we don't have to write cumbersome envoyfilters to implement the prefix replacement of redirect
