### ISSUE TITLE
istioctl bug-report include filtering logic not working with namespace and pod filtering

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#47522]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to gather information about specific pods within a namespace from multiple namespaces, `istioctl bug-report` does not properly get all proxy information.

This is important because some environments we work with have over 600 services in a single cluster. We would like to grab the istio proxy information of just the control plane, gateways and workload pod having issues. Using the filtering logic in istioctl bug-report does not allow us to do that in a single command or we have to grab proxy information and logs from ALL pods running in the namespaces. 

Use cases

* `istioctl bug-report` - grabs all information as expected
```shell
> istioctl bug-report
Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-23 07:58:20.105709179 -0500 CDT

Cluster endpoint: https://0.0.0.0:43387
CLI version:
version.BuildInfo{Version:"1.19.3", GitRevision:"41218ffa66c12acf77ad08b3ef07d296218d0929", GolangVersion:"go1.21.3", BuildStatus:"Clean", GitTag:"1.19.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.17.1", GitRevision:"7d6d2adacf8dcee110a48450d537f8ad26c7225f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.1}

Fetching logs for the following containers:

default/details-v1/details-v1-7d4d9d5fcb-xv545/details
default/details-v1/details-v1-7d4d9d5fcb-xv545/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/productpage
default/ratings-v1/ratings-v1-85cc46b6d4-d7r57/istio-proxy
default/ratings-v1/ratings-v1-85cc46b6d4-d7r57/ratings
default/reviews-v1/reviews-v1-777df99c6d-46kt4/istio-proxy
default/reviews-v1/reviews-v1-777df99c6d-46kt4/reviews
default/reviews-v2/reviews-v2-cdd8fb88b-gp229/istio-proxy
default/reviews-v2/reviews-v2-cdd8fb88b-gp229/reviews
default/reviews-v3/reviews-v3-58b6479b-lx2xg/istio-proxy
default/reviews-v3/reviews-v3-58b6479b-lx2xg/reviews
istio-system/istio-egressgateway/istio-egressgateway-8694db4556-6sw9q/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-8568ffc4d4-6jwvt/istio-proxy
istio-system/istiod/istiod-76cf8b7b8b-dwstt/discovery

Fetching Istio control plane information from cluster.
```
![Screenshot from 2023-10-23 07-59-34](https://github.com/istio/istio/assets/22355055/1107a8dd-3994-4432-98a9-1445a7e3aef4)

* `istioctl bug-report --include '"default/product*"'` - grabs just the proxy information for productpage which is expected
```shell
▶ istioctl bug-report --include '"default/product*"'
Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: { Namespaces: default/Deployments: product* }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-23 08:00:50.98426119 -0500 CDT

Cluster endpoint: https://0.0.0.0:43387
CLI version:
version.BuildInfo{Version:"1.19.3", GitRevision:"41218ffa66c12acf77ad08b3ef07d296218d0929", GolangVersion:"go1.21.3", BuildStatus:"Clean", GitTag:"1.19.3"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:


Fetching logs for the following containers:

default/productpage-v1/productpage-v1-66756cddfd-lsmq5/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/productpage

Fetching Istio control plane information from cluster.
```
![Screenshot from 2023-10-23 08-02-01](https://github.com/istio/istio/assets/22355055/6c502b6c-c38a-4044-8b7d-7fe64aa5942f)

* `istioctl bug-report --include '"istio-system,default/product*"'` - Includes `istio-system` and product page pods, does not propertly grab information from istio-system namespace desipte the include looking correct `include: { Namespaces: istio-system,default/Deployments: product* }`
```shell
istioctl bug-report --include '"istio-system,default/product*"'

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: { Namespaces: istio-system,default/Deployments: product* }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-23 08:02:26.659024959 -0500 CDT

Cluster endpoint: https://0.0.0.0:43387
CLI version:
version.BuildInfo{Version:"1.19.3", GitRevision:"41218ffa66c12acf77ad08b3ef07d296218d0929", GolangVersion:"go1.21.3", BuildStatus:"Clean", GitTag:"1.19.3"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:


Fetching logs for the following containers:

default/productpage-v1/productpage-v1-66756cddfd-lsmq5/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/productpage

Fetching Istio control plane information from cluster.


Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:

Creating an archive at /home/nick/work/demo/istio/bug-report-logs-bug/bug-report.tar.gz.
Time used for creating the tar file is 19.341403ms.
Cleaning up temporary files in /tmp/bug-report.
Done.
```
![Screenshot from 2023-10-23 08-04-38](https://github.com/istio/istio/assets/22355055/45944f3a-7da5-4887-bc12-7dae0c6b3484)

* `istioctl bug-report --include '"istio-system,default"'` - Using namespaces and no pod filtering. Works as expected
```shell
istioctl bug-report --include '"istio-system,default"' 

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: { Namespaces: istio-system,default }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-23 08:05:02.256065995 -0500 CDT

Cluster endpoint: https://0.0.0.0:43387
CLI version:
version.BuildInfo{Version:"1.19.3", GitRevision:"41218ffa66c12acf77ad08b3ef07d296218d0929", GolangVersion:"go1.21.3", BuildStatus:"Clean", GitTag:"1.19.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.17.1", GitRevision:"7d6d2adacf8dcee110a48450d537f8ad26c7225f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.1}


Fetching logs for the following containers:

default/details-v1/details-v1-7d4d9d5fcb-xv545/details
default/details-v1/details-v1-7d4d9d5fcb-xv545/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/istio-proxy
default/productpage-v1/productpage-v1-66756cddfd-lsmq5/productpage
default/ratings-v1/ratings-v1-85cc46b6d4-d7r57/istio-proxy
default/ratings-v1/ratings-v1-85cc46b6d4-d7r57/ratings
default/reviews-v1/reviews-v1-777df99c6d-46kt4/istio-proxy
default/reviews-v1/reviews-v1-777df99c6d-46kt4/reviews
default/reviews-v2/reviews-v2-cdd8fb88b-gp229/istio-proxy
default/reviews-v2/reviews-v2-cdd8fb88b-gp229/reviews
default/reviews-v3/reviews-v3-58b6479b-lx2xg/istio-proxy
default/reviews-v3/reviews-v3-58b6479b-lx2xg/reviews
istio-system/istio-egressgateway/istio-egressgateway-8694db4556-6sw9q/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-8568ffc4d4-6jwvt/istio-proxy
istio-system/istiod/istiod-76cf8b7b8b-dwstt/discovery

Fetching Istio control plane information from cluster.
```
![Screenshot from 2023-10-23 08-08-20](https://github.com/istio/istio/assets/22355055/42d44aa9-4d8b-4b62-8db5-a29e3c329daf)

* `istioctl bug-report --include '"istio-system/*,default/*"'` - Multiple namespaces with pod filtering does not appear to work as well. it only matches the pods from istio-system 
```shell
istioctl bug-report --include '"istio-system/*,default/*"'

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: { Namespaces: istio-system/Deployments: *,default }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-10-23 08:12:52.858727062 -0500 CDT

Cluster endpoint: https://0.0.0.0:43387
CLI version:
version.BuildInfo{Version:"1.19.3", GitRevision:"41218ffa66c12acf77ad08b3ef07d296218d0929", GolangVersion:"go1.21.3", BuildStatus:"Clean", GitTag:"1.19.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.17.1", GitRevision:"7d6d2adacf8dcee110a48450d537f8ad26c7225f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.17.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.17.1}


Fetching logs for the following containers:

istio-system/istio-egressgateway/istio-egressgateway-8694db4556-6sw9q/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-8568ffc4d4-6jwvt/istio-proxy
istio-system/istiod/istiod-76cf8b7b8b-dwstt/discovery

Fetching Istio control plane information from cluster.


Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:

Creating an archive at /home/nick/work/demo/istio/bug-report-logs-bug/bug-report.tar.gz.
Time used for creating the tar file is 25.811298ms.
Cleaning up temporary files in /tmp/bug-report.
Done.
```
![Screenshot from 2023-10-23 08-14-51](https://github.com/istio/istio/assets/22355055/3f6f37a4-c304-419c-9146-5f3b73cc765b)

Steps to repeat
1. `istioctl install --set profile=demo -y`
2. Deploy bookinfo `kubectl label namespace default istio-injection=enabled && kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`
3. Run `istioctl bug-report --include '"istio-system,default/product*"'` and observe that istio-system pods are not included

### Version

```Text
istioctl version
client version: 1.19.3
```

**Comment by howardjohn** [comment]
cc @syw14

**Comment by syw14** [comment]
@nmnellis Hi Nick, the filtering works like this: namespace/deployments/pods

so if you would like to filter by podnames, we should use 
istioctl bug-report --include istio-system,default//product*

You could also find out this information from the logging too: 
include: { Namespaces: istio-system,default/Deployments: product* } 

It indicates the filtering was applied to Deloyments not podNames.

**Comment by nmnellis** [comment]
@syw14 this doesnt really address the inconsistencies in the bug that i opened. Also selecting a deployment should also select all backing pods behind it? im not seeing how this helps fix the issues im seeing with pod selection inconsistencies

**Comment by syw14** [comment]
When applying `istioctl bug-report --include istio-system,default//product*`, 
It means the filter will only select within namespace of `istio-system` and `default` WHILE the podName satisfy `product*`

Thus it's not really an issue of inconsistency here. 

It's an AND relationship, not OR. 

If we want to support OR, we need to add a new feature. But the AND is the current approach of filtering.

**Comment by nmnellis** [comment]
Why does the below only return pods from istio system? that doesnt seem to match AND semantics

`istioctl bug-report --include '"istio-system/*,default/*"'`

**Comment by nmnellis** [comment]
`istioctl bug-report --include '"istio-system,default"' ` returns pods from both namespaces? how is this different?

**Comment by syw14** [comment]
The filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...'

> https://github.com/istio/istio/blob/master/tools/bug-report/pkg/bugreport/bugreport.go#L74

**Comment by syw14** [comment]
> Why does the below only return pods from istio system? that doesnt seem to match AND semantics
> 
> `istioctl bug-report --include '"istio-system/*,default/*"'`

filtering currently do not support applying - `ns1/dep1, ns2/dep2' we could only do 'ns1,ns2/dep1,dep2' unfortunately,

**Comment by nmnellis** [comment]
That's the bug, it should work according to the documentation

**Comment by syw14** [comment]
> That's the bug, it should work according to the documentation

Per documentation in the code itself, https://github.com/istio/istio/blob/master/tools/bug-report/pkg/bugreport/bugreport.go#L74, It says The filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...'

Which documentation are you referring to please?

**Comment by linsun** [comment]
Hi @syw14 thanks for looking at this issue!  I think what @nmnellis refers to is a common scenario to get bug report from multiple namespaces.  From looking at the issue, seems these two are not working:

Scenario 1:

istioctl bug-report --include '"istio-system,default/product*"'

Without reading code, I would expect all pods from the istio-system ns and the pods starting with product from the default namespace .

Scenario 2: 
istioctl bug-report --include '"istio-system/*,default/*"'

I would expect all pods from istio-system and all pods from default ns.

What do you think the 2 scenarios should work?

cc @istio/wg-user-experience-maintainers to chime in.

**Comment by hanxiaop** [comment]
> istioctl bug-report --include '"istio-system/,default/"'
>
> I would expect all pods from istio-system and all pods from default ns.

I would expect this as well.

**Comment by GregHanson** [comment]
> I would expect this as well.

I agree.  I think the `AND` semantics refer to each element provided between each `/` (`n*//p*/l=v*` for example) in an individual filter rather than a logical `AND` of two comma separated filters.  I would expect a comma separated list of N filters to produce a concatenated result of N separate queries

**Comment by syw14** [comment]
The current implementation uses COMMA as an allowance to work with more options for one specific filter. 

Right now, we could apply `ns1, ns2//pod1*,pod2*` to filter out the podnames satisfying pod1*, pod2* within all the pods of ns1 and ns2. 

If we modify the COMMA usage, we will need to apply - `ns1/pod1*,ns1/pod2*,ns2/pod1*,ns1/pod2*` for the equivalent response. 

Do we think the ladder is strictly better?  In my opinion, the current implementation is only a different way to apply the filter. Sometimes it's more convenient, sometimes it's not. But no implementation will be strictly better.

**Comment by linsun** [comment]
> The current implementation uses COMMA as an allowance to apply more options for one specific filter.
> 
> Right now, we could apply `ns1, ns2//pod1*,pod2*` to filter out the podnames satisfying pod1*, pod2* within all the pods of ns1 and ns2.
> 
> If we modify the COMMA usage, we will need to apply - `ns1/pod1*,ns1/pod2*,ns2/pod1*,ns1/pod2*` for the equivalent response.
> 
> Do we think the ladder is strictly better? In my opinion, the current implementation is only a different way to apply the filter. Sometimes it's more convenient, sometimes it's not. But no implementation will be strictly better.
> 
> I could modify the documentation to make it clearer if you think it's helpful. But if we want to modify the filter itself, maybe we should be more cautious?

I do think the `ns1/pod1*,ns1/pod2*,ns2/pod1*,ns1/pod2*` is better as it is less confusing. There is only 1 way to interpret it and it doesn't require users to look up any docs.
While `ns1, ns2//pod1*,pod2*` is concise, but it can be interpreted in multiple ways. For example, all pods from ns1, and all pod2* in any namespace.

**Comment by ivantrips** [comment]
@linsun can you assign this ticket to me, i could work on it, i also think using `ns1/pod1*,ns1/pod2*,ns2/pod1*,ns1/pod2*` is more clear

**Comment by linsun** [comment]
Hi @ivantrips thank you!!

**Comment by saiskee** [comment]
Hi @ivantrips, are you currently working on this? I would like to take a look if you aren't currently.

**Comment by saiskee** [comment]
@nmnellis 
> istioctl bug-report --include '"istio-system/*,default/*"' - Multiple namespaces with pod filtering does not appear to work as well. it only matches the pods from istio-system

this does work. In this case, the double quotes around the filter are messing with the parser.
```bash
istioctl bug-report --include 'istio-system/*,default/*'
...

Running with the following config:
...
include: { Namespaces: istio-system } AND { Namespaces: default }
```

When I add in the double quotes, as demonstrated in the issue:
```bash
istioctl bug-report --include '"istio-system/*,default/*"'

Running with the following config:
...
include: { Namespaces: istio-system/Deployments: *,default }

```

We can see that it parses the filter incorrectly, and is looking for deployments that match `*,default` in `istio-system` namespace, which is why we are only seeing istio-system pods here.

**Comment by saiskee** [comment]
@linsun 
> istioctl bug-report --include '"istio-system,default/product*"'
Without reading code, I would expect all pods from the istio-system ns and the pods starting with product from the default namespace .

I agree that this would lend to a more intuitive UX. I'm hoping @istio/wg-user-experience-maintainers @hanxiaop can chime in here and give the green light to implement comma separated queries, where each individual query does not affect another query. 
In this case `default/product*` selects all deployments from ns `default` that start with `product`, and all pods from `istio-system`, because that query does not filter down on any other criteria.

**Comment by linsun** [comment]
> @nmnellis
> 
> > istioctl bug-report --include '"istio-system/_,default/_"' - Multiple namespaces with pod filtering does not appear to work as well. it only matches the pods from istio-system
> 
> this does work. In this case, the double quotes around the filter are messing with the parser.
> 
> ```shell
> istioctl bug-report --include 'istio-system/*,default/*'
> ...
> 
> Running with the following config:
> ...
> include: { Namespaces: istio-system } AND { Namespaces: default }
> ```
> 
> When I add in the double quotes, as demonstrated in the issue:
> 
> ```shell
> istioctl bug-report --include '"istio-system/*,default/*"'
> 
> Running with the following config:
> ...
> include: { Namespaces: istio-system/Deployments: *,default }
> ```
> 
> We can see that it parses the filter incorrectly, and is looking for deployments that match `*,default` in `istio-system` namespace, which is why we are only seeing istio-system pods here.



> @linsun
> 
> > istioctl bug-report --include '"istio-system,default/product*"'
> > Without reading code, I would expect all pods from the istio-system ns and the pods starting with product from the default namespace .
> 
> I agree that this would lend to a more intuitive UX. I'm hoping @istio/wg-user-experience-maintainers @hanxiaop can chime in here and give the green light to implement comma separated queries, where each individual query does not affect another query. In this case `default/product*` selects all deployments from ns `default` that start with `product`, and all pods from `istio-system`, because that query does not filter down on any other criteria.

@hanxiaop not sure if you are back from your holiday, would love to get some feedback from you on this.  cc @therealmitchconnors as well.

**Comment by hanxiaop** [comment]
I actually think both implementations have their pros and cons. I agree the new implementation provides a more intuitive user experience. However if I want to select httpbin proxies from different namespaces, I originally only needed to do `default,bookinfo,ambient/httpbin`. Now, I need to query by `default/httpbin,bookinfo/httpbin,ambient/httpbin`. IMO the old implementation is better for selecting the same group of services in large clusters. The con is that selecting things like entire namespaces and specific pods needs to be done in two times. Both implementations make sense to me, and I don't have a strong preference for one over the other. We can improve the tool once we have more feedback from users. Otherwise, it maybe waste effort to change the UX of a debug tool without a strictly improvement.

**Comment by saiskee** [comment]
@hanxiaop 
> However if I want to select httpbin proxies from different namespaces, I originally only needed to do default,bookinfo,ambient/httpbin

This is true, however, the implementation still is incorrect in the following case:
```
default/*, bookinfo/*, ambient/httpbin
```
We would still only get httpbin proxies in these namespaces. Maybe this is an advanced use case that users don't really use, but IMO the impl is incorrect.

**Comment by hanxiaop** [comment]
> @hanxiaop
> 
> > However if I want to select httpbin proxies from different namespaces, I originally only needed to do default,bookinfo,ambient/httpbin
> 
> This is true, however, the implementation still is incorrect in the following case:
> 
> ```
> default/*, bookinfo/*, ambient/httpbin
> ```
> 
> We would still only get httpbin proxies in these namespaces. Maybe this is an advanced use case that users don't really use, but IMO the current impl is incorrect.

@saiskee Thanks for the clarification. It seems to be a bug. At least for the current implementation, `*` is intended to mean all workloads, but actually only the httpbin workload can be fetched.

**Comment by hanxiaop** [comment]
Just tried and noticed an inconsistent behavior: `--include 'default,bookinfo,ambient/httpbin,*'` fetchs only httpbin proxies, but `--include 'default,bookinfo,ambient/*,httpbin'` fetches all proxies in these namespaces.
