### ISSUE TITLE
Allow TLS Renegotiation for jwks resolver

### ISSUE THREAD

**Issue by ethanchowell** [istio/istio#47531]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Allow the pilot jwks resolver client to renegotiate TLS. This could be set [here](https://github.com/istio/istio/blob/9467050aa957cb2cd38fdc1c4b5559a8a6da00d6/pilot/pkg/model/jwks_resolver.go#L179-L185) or enabled as a feature alongside [this](https://github.com/istio/istio/blob/9467050aa957cb2cd38fdc1c4b5559a8a6da00d6/pilot/pkg/features/pilot.go#L677)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I'm working in some environments that require auth via access cards and tokens. These end up requiring TLS1.2 for Keycloak to pick them up in a X509 auth flow. I'm trying to wire up a RequestAuthentication to validate the resulting JWT against keycloak via the `jwksUri`, but keep seeing errors like

```text
Failed to GET from "https://...": local error: tls: no renegotiation
Failed to refresh JWT public key from "https://...": local error: tls: no renegotiation
```

I've been able to work around this in other projects by explicitly configuring [RenegotationSupport](https://pkg.go.dev/crypto/tls#RenegotiationSupport). Since this would allow clients to downgrade to a less secure TLS protocol, it seems reasonable to require users to opt in by setting an env var like `JWKS_RESOLVER_ALLOW_TLS_RENEGOTIATION`. I _think_ the only places that would need to be updated to support this are the pilot features and `JwksResolver` constructors. I'd be happy to put up a PR for this.

**Comment by ethanchowell** [comment]
Another thing I've encountered that could be added in the same place is the need to provide istiod with client certs for resolving the JWKS. I have a Keycloak instance sitting behind a Gateway configured for `MUTUAL` tls. This Keycloak sits in another cluster relative to some istio deployments, so it's not always as easy as some Keycloak configs to change and set the hostname it thinks it should return.

I've been able to get around this to date by having a separate Gateway configured for `SIMPLE` TLS at a separate, internally resolvable hostname, and just pointing istiod to it while telling Keycloak that it's serving at a specific hostname with some of the configs [here](https://www.keycloak.org/server/hostname). Being able to use the mTLS gateway and provide istiod with client certs would really simplify our helmfile configs and cert management for those endpoints. Maybe that's something to track in a separate issue or separate PR though?

**Comment by hzxuzhonghu** [comment]
does renegotiation have any security issue? I rarely see its usage

**Comment by ethanchowell** [comment]
I'm purely speculating here because I just don't have enough background in the protocols/go libs that handle it, but I'd assume renegotiation may have some concerns since maybe you don't know the protocol that the server would respond to downgrade to until the request happens? In that case I would _hope_ that setting the `MinVersion` in the tls config would safeguard against downgrading below that minimum allowable value. But again, I'm purely speculating and don't know that things actually work that way under the hood.
