### ISSUE TITLE
Primary-Remote cluster in multiple network installation not working with revisioned control plane

### ISSUE THREAD

**Issue by xu-jianchu** [istio/istio#47552]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/
If the control plane is installed with revision, the remote cluster can not properly injected with sidecars. 

Observation:
If the remote cluster is installed with `--set revision=...`, the `MutatingWebhookConfiguration` would point to a `Service` `istiod-{revision}` but only `Service` created is `istiod`

If the remote cluster is installed without the revision, the webhook call would fail with the eastwest gateway on the primary cluster report
```
0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - {ip} {ip} istiod.istio-system.svc
```

which is not there since revisioned installation would not create `istiod` service but `istiod-{revision}` service.

### Version

```Text
client version: 1.18.2-asm.4
control plane version: 1.18.2-asm.4
data plane version: 1.18.2-asm.4 (2 proxies)

primary cluster version:

Client Version: v1.23.5
Server Version: v1.27.4-gke.1600
```

Remote cluster version
```
Client Version: v1.23.5
Server Version: v1.27.4-gke.1600
```
```


### Additional Information

_No response_

**Comment by GregHanson** [comment]
I recall a few bug fixes that went in around the revision flag in the past few releases - are you able to reproduce with latest 1.19.3 version?

**Comment by xu-jianchu** [comment]
@GregHanson thank you for replying! Is there a patch version on 1.18 that also includes the fixes? I'm running in a controlled environment and upgrading minor version may cause some compatibility issue

**Comment by howardjohn** [comment]
I think this is basically as simple as making https://github.com/istio/istio/blob/da4c765c0f292d7840e01b16305990d5d941bd1a/manifests/charts/istiod-remote/templates/services.yaml#L10 support the revision suffix. Though you need your VirtualService to match on the specific SNI and route to the correct backend instead of the current `*` match

**Comment by howardjohn** [comment]
expose-istiod-rev.yaml.tmpl sample shows the VS needed

**Comment by xu-jianchu** [comment]
To close the loop for anyone coming across the issue. What we ended up doing is 
1. Configure the VS as
```
...
spec:
  ...
  hosts:
  - istiod-{revision}.{ns}.svc
  tls:
  - match:
    - port: 15012
       sniHosts:
       - istiod-{revision}.{ns}.{k8s service dns suffix}
    - port: 15017
       {same as above}
```
2. When installing remote cluster, add `revision: {revision}` to the `IstioOperator` then `-{revision}` to the `Istiod` service like what's pointed out above.
