### ISSUE TITLE
Introduce a linter to detect expensive debug-only logging code

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4756]
It's easy for debug-only logging code to do expensive work:

log.Debug("Something bad happened: %s", fmt.Sprintf("%s, %d", a, b));

Ideally, this kind of code should be protected with:

if log.DebugEnabled() {
    log.Debug("Something bad happened: %s", fmt.Sprintf("%s, %d", a, b));
}

We could write a linter to detect any case where log.Debugf is called in an expensive way and require the call to be protected via log.DebugEnabled.

**Comment by geeknoid** [comment]
@douglas-reid FYI

**Comment by hklai** [comment]
@JimmyCYJ should this be added to gometalinter or the new testlinter?

**Comment by JimmyCYJ** [comment]
@hklai I think we could implement a lint rule for the new testlinter to cover this case.

**Comment by geeknoid** [comment]
What's testlinter?

Ideally, this can written as a stand-alone program which we can invoke from gometalinter. We've done this to lint adapter code for example.

**Comment by JimmyCYJ** [comment]
We have implemented a testlinter that could be invoked from gometalinter, just like lint adapter code. https://github.com/istio/istio/tree/master/tests/util/checker/testlinter, it is still under implementation. It covers some custom lint rules we proposed for tests, and we could run it manually now.
