### ISSUE TITLE
Counter for Retry Policies on Envoy Proxy

### ISSUE THREAD

**Issue by msfidelis** [istio/istio#47579]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I think the capability to export metrics/counter based on envoy retry policies can be very useful for improve envoy observability. For example, for instance, retry count and condition.

Example on `istio_requests_total` we have a `response_flags` tag, we can be enhance this metrics with a `retry_count` propertie. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
you can do it yourselft whit Telemetry API or EnvoyFilter, I don't think it should be on by default.
