### ISSUE TITLE
Create a ValidatingAdmissionPolicy for MeshConfig

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#47593]
For CRDs, we are largely moving away from webhook to native validation (https://github.com/istio/istio/issues/46151) (not really _away_ for awhile, but augment it).

For MeshConfig, its a configmap so we don't have the same choice. We could add a webhook for that, but doesn't seem great since webhooks are kind of problematic, and has a somewhat circular dependency on Istio

https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy fix all of these problems. They are beta in 1.28. We should make a VAP for MeshConfig. It may not be ready for inclusion in core yet, but it can be a standalone yaml folks can apply

**Comment by hzxuzhonghu** [comment]
For complex validation, it seems webhook can not easily be replaced by `Validating Admission Policy`.
> doesn't seem great since webhooks are kind of problematic, and has a somewhat circular dependency on Istio

CM validation is similar as other Istio APIs, is there any diff.  validation is part of istiod,, so what circular dependency?

**Comment by howardjohn** [comment]
> For complex validation, it seems webhook can not easily be replaced by `Validating Admission Policy`.
> 
> > doesn't seem great since webhooks are kind of problematic, and has a somewhat circular dependency on Istio
> 
> CM validation is similar as other Istio APIs, is there any diff. validation is part of istiod,, so what circular dependency?

Istiod needs the config map to start with correct config, but istiod needs to be started to write the config map.

Probably we could workaround it but still a bit risky

**Comment by hzxuzhonghu** [comment]
IC, this is something that can fail startup.

**Comment by goku321** [comment]
Hello. I would like to work on this :)

**Comment by goku321** [comment]
Not stale

**Comment by zirain** [comment]
not stale

**Comment by goku321** [comment]
Just a bit caught up. Will be spending time on it this week.

**Comment by howardjohn** [comment]
Since writing this I think there is an issue. MeshConfig is really 1 key and a big string. CEL cannot really parse that

**Comment by goku321** [comment]
I don't have enough knowledge on it to comment but will changing the parsing logic help?

**Comment by howardjohn** [comment]
CEL is a limited language, it cannot parse YAML at all

**Comment by goku321** [comment]
I see. So what do you suggest?

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/48991#issuecomment-1922660112

**Comment by hzxuzhonghu** [comment]
>1. in Bootstrap stop loading the meshConfiguration if it is invalid, and using the default meshConfig.
> 2. Adding we validating webhook for meshConfig, and prevent updating invalid config.

It is to validate in two places, both webhook and istiod startup. I believe it works

**Comment by goku321** [comment]
Ok, I guess according to @hzxuzhonghu we can make it work. I can start with the implementation.
