### ISSUE TITLE
Extra line using istioctl analyze on the 1.20.0-beta.0

### ISSUE THREAD

**Issue by ericvn** [istio/istio#47607]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Comparing `istioctl analyze` output during the `Getting Started`.   

1.19.3 has (which matches the doc):
```
> ./bin/istioctl analyze

✔ No validation issues found when analyzing namespace: default. 
```

1.20.0-beta.0 has:
```
> istioctl analyze

validateHTTPRouteDestinations host:"productpage"  port:{number:9080}

✔ No validation issues found when analyzing namespace: default.
```

I'm not sure if the extra line is planned to here, or necessarily what to do about it.

### Version

```Text
1.20.0-beta.0
```

**Comment by hanxiaop** [comment]
This has been fixed by https://github.com/istio/istio/pull/47518

**Comment by hanxiaop** [comment]
Wait beta.1 build https://github.com/istio/release-builder/pull/1682

**Comment by hanxiaop** [comment]
@ericvn Could you please try again? I just tried rc.0 and I think the issue has been fixed.

**Comment by ericvn** [comment]
Verified that the message is not there with the 1.20.0-rc.0:
```
> istioctl analyze


✔ No validation issues found when analyzing namespace: default.
```
