### ISSUE TITLE
Document exposed ports by discovery service

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4760]
Please document ports 15005, 15007, 15003, 15010, 15011 for discovery service.
Which one is for what?

**Comment by kyessenov** [comment]
This is blocking clean-up in PR https://github.com/istio/istio/pull/4721

**Comment by wattli** [comment]
15003/15005/15007 are used for xDS services. Pilot always exposes these three ports.
if controlPlaneAuthPolicy == NONE
   15003 is a plain text port
else
   15003 is mTLS port.
15005 is always for mTLS
15007 is always for plain text

@costinm should know what 15010/15011 are used for

**Comment by kyessenov** [comment]
added comments to the service spec. will see if that is going to survive and stay up to date.
