### ISSUE TITLE
implement migration from virtual service to http route

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#47600]
Hi,

I am migrating from `virtual service` to `HTTPRoute` (mostly because of https://github.com/istio/istio/issues/7674 and because istio itself moving to gateway-api), and I have some questions about the migration.

gateway-api is working great for services that are exposed to the internet but what should I do with internal services?
with `virtual service` (before gateway-api), I created a `virtual service` for each micro service and I didn't add gateways and hosts for internal micro services.
if the service was exposed to the internet I added the `mesh` keyword to the gateways section (according to https://discuss.istio.io/t/internal-traffic-with-virtualservice-and-destinationrule/3726)

Now with `HTTPRoute`, what should I do with internal services?
I want to enable some route rules on internal services, but I couldn't find a valid source/example (in your git samples as well) that addresses my case.

Does `HttpRoute` support services that are not exposed to the internet?
Is it possible to improve docs on this matter or give a source instead?
How for example can I do a retry on a request with status code 503 with HTTPRoute (because the service is exposed to the internet), and do a retry on a request with status code 503 on internal service that does not exposed to the internet?

Does gateway api replaces virtual service and destination rule completly or I need to create both now?

Thanks!

**Comment by howardjohn** [comment]
https://gateway-api.sigs.k8s.io/concepts/gamma/ - mesh for HTTPRoute is in development, a bit earlier than ingress use cases but coming along

**Comment by Rez0k** [comment]
> https://gateway-api.sigs.k8s.io/concepts/gamma/ - mesh for HTTPRoute is in development, a bit earlier than ingress use cases but coming along

Okay, so basicaly all I need to do is to specify Service instead of gateway in `spec.parentRef` correct?
Do you recommend migrating to gateway-api or is it too soon?

**Comment by Rez0k** [comment]
> https://gateway-api.sigs.k8s.io/concepts/gamma/ - mesh for HTTPRoute is in development, a bit earlier than ingress use cases but coming along

any update?

**Comment by rwardhan** [comment]
@howardjohn what's the ETA for HTTPRoute serving serviesh mesh to release (GA)?

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/47600#issuecomment-1781778752
