### ISSUE TITLE
Gateway API: support backend appProtocol

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#47610]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Gateway API v1 has an experimental feature for specifying the backend protocol - ref. https://github.com/kubernetes-sigs/gateway-api/pull/1979

**Describe alternatives you've considered**

N/A

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
There are two upstream conformance tests to test gateway support for HTTP/2 Prior knowledge and websocket backend support.

h2c https://github.com/kubernetes-sigs/gateway-api/pull/2456
websocket - https://github.com/kubernetes-sigs/gateway-api/pull/2495

**Comment by howardjohn** [comment]
Is there some place we are not doing this? AFAIK Istio has done this since day 0

**Comment by keithmattix** [comment]
Perhaps the ask is specific to the kubernetes.io/* protocols? I think there was already a PR submitted for that though

**Comment by dprotaso** [comment]
Nice I opened an issue since I didn't know.  Maybe we should leave this issue open so that Istio opt's into the following experimental features when running Gateway API conformance.

`SupportHTTPRouteBackendProtocolH2C` and `SupportHTTPRouteBackendProtocolWebSocket`

https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/conformance/utils/suite/features.go#L137-L142

But I'll leave it up to you how you want to track that. thanks

**Comment by howardjohn** [comment]
Definitely should turn those on and make sure they work. Thanks!

**Comment by samzong** [comment]
seems great.
