### ISSUE TITLE
After istio version upgrade the ".items[N].spec.tag" for istioOperator is not changed to the newer version

### ISSUE THREAD

**Issue by kiranmenon** [istio/istio#47620]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Im using istioctl to install / upgrade the istio in my clusters hosted in OCI. The upgrade from 1.15.1 to 1.16.0 happened without any errors, but when I checked the ".items[0].spec.tag" for istioOperator, it still points to 1.15.1 
This behavior seems to be inconsistent as I see some of my other clusters have the tag value correctly pointing to 1.16.0
And I see all the proxies, control-plane, and data-plane are showing as 1.16.0 .
What is the significance of ".items[0].spec.tag" and how is it being used? I thought this was from where the istio operator picks up the value of the image tag to be used.

After upgrading istio from 1.15.1 to 1.16.0
````
kubectl get IstioOperator -n istio-system -o jsonpath='{.items[0].spec.tag}'
1.15.1
````

### Version

```Text
istioctl version
client version: 1.16.0
control plane version: 1.16
data plane version: 1.16-dev (37 proxies)
```

```Text
kubectl version  --short 
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.1
```

**Comment by hanxiaop** [comment]
> What is the significance of ".items[0].spec.tag" and how is it being used? I thought this was from where the istio operator picks up the value of the image tag to be used.

This is correct.

You may check again using `istioctl manifest generate` to see if the tag is rendered correctly.
