### ISSUE TITLE
Istiod pushes all ROOTCAs, even when unused

### ISSUE THREAD

**Issue by dwj300** [istio/istio#47626]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have noticed a fairly significant memory increase in Envoy (40%) when using many clusters (~500) with a multiroot mesh, with lots of root cas (~2 dozen). From looking at heap dumps, it looks like envoy will copy all the root certs into each cluster, causing this bloat. We'd like to *just* push the extra ROOT CAs only to proxies that have clusters matching the trust domains of the respective certificates, instead of pushing all N certs to all sidecars

### Version

```Text
1.17.4
```

**Comment by hzxuzhonghu** [comment]
This is intended for multi root cert
