### ISSUE TITLE
Design and implement consistent Default Values in all Istio configurations

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4763]
Short version:

A spec like:

```yaml
spec:
  foo:
```
will be parsed into (proto) object with foo == `nil`, though we may want foo == default_instance of type `Foo`.

Long version:

For authentication policy, we have `MutualTls` message to carry parameters for mTLS authentication, though in most common case, no params need to be set. Hence, a simple policy to enable mTLS will be like this:

```yaml
spec:
  peers:
  - mtls:
```

Note peers is a repeated of `PeerAuthenticationMethod`:

```proto
message PeerAuthenticationMethod {
  oneof params {
    // Set if mTLS is used.
    MutualTls mtls = 1;
    ...
  }
}
...

message Policy {
  repeated PeerAuthenticationMethod peers = 1;
}
```

Pilot can parse this yaml. However the object has peers[0].params with (oneof) type `PeerAuthenticationMethod_Mtls`, but the value (mtls) is `nil`. While this is fine for the need in pilot, it cause trouble when the policy is converted into filter config for proxy. The config will look like this:

```json
"config": {
  "policy": {
    "peers": [
      {
        "mtls": null
      }
    ]
  }
}
```

On proxy code, this will see as peers[0] is an null object of **no** type. 

If peers[0].mtls is not `nil` on pilot side, the config should be `mtls: {}` instead of `mtls: null`, and will be handled correctly by proxy.

Possible solutions:
- Change parser to create object even when there is no details. This fix may be closest to root cause.
- Change the policy to have extra field to define the method, instead of getting method from oneof-type.

**Comment by xiaolanz** [comment]
@douglas-reid @guptasu A while a ago we have a discussion about mixer parsing empty fields. Do you remember what's the decision? nil or default value? 

For example if it's a string, it will nil or ""?

**Comment by guptasu** [comment]
Document https://docs.google.com/document/d/10ci5084oCJ4uyxMOPWyHziusxXBxT-0m3AtiCZEOtwc/edit explains our decision.

**Comment by diemtvu** [comment]
Thanks Kuat. `mtls: {}` could work, but I find it's a bit counter intuitive (we don't need {} when there is some fields followed).

**Comment by xiaolanz** [comment]
Implement a layer at config parsing to fill-in all defaults before sending to components.

**Comment by kyessenov** [comment]
@diemtvu This is the correct behavior according to the specification of JSON mapping from proto3. Proto3 deliberately left out default values, as it was difficult to ensure consistency in a distributed environment. I think we may want to focus on a principled overriding of field values across scopes. I would image we would use cluster-scope value as the default value for the namespace-scope, for example.

**Comment by diemtvu** [comment]
Thanks @kuat. Close with 'work as expected'
