### ISSUE TITLE
TLS authentication with external services

### ISSUE THREAD

**Issue by maxkondr** [istio/istio#4764]
Hi, 
I am looking for service mesh and for the time being is discovering istio (good job btw!).

But I have several questions:
1) I came across this lines in https://istio.io/docs/setup/kubernetes/quick-start.html:
> Install Istio’s core components. Choose one of the two mutually exclusive options below or alternately install with the Helm Chart:
> a) Install Istio without enabling mutual TLS authentication between sidecars. Choose this option for clusters with existing applications, applications where services with an Istio sidecar need to be able to communicate with other non-Istio Kubernetes services, and applications that use liveliness and readiness probes, headless services, or StatefulSets.

So if I understood it properly there is no way to enable TLS authentication for only the part of services in my cluster, right? I must enable TLS for all or for none of them.

2) Another Q: if I enable TLS for all of the services and some particular service_A has to communicate with some external apps without TLS (outside of Kubernetes cluster, service_Ex), but there is some service_B inside K8S that service_A must communicate with using TLS.

service_A--TLS-->service_B
service_A--NO_TLS-->service_Ex

3) the same as 2 but:
prometheus service monitor (https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html) --NO_TLS-->service_A/stats

is it possible to configure?

TIA

**Comment by linsun** [comment]
for 1, I assume you meant mTLS.  Yes, you can enable/disable it per service, see https://istio.io/docs/tasks/security/per-service-mtls.html

for 2, yes, if you meant mTLS, that is totally possible.  If you mean TLS, see https://github.com/istio/istio.github.io/issues/1152

for 3, should be possible.   you can disable mTLS on service_A.

cc @wattli @elevran

**Comment by wattli** [comment]
Thanks Lin for the response. And to add what she said, we support service level mTLS/TLS enablement. The doc/request for doc are listed above. 

Whether a service-to-service communication is mTLS or http is determined by server side, which means, if service A has a config with mTLS enabled, then all clients (with sidecar) will get this info from pilot, and they will send mTLS when talking with service A. And same thing for http/regular TLS.

**Comment by maxkondr** [comment]
@linsun, @wattli 
Thanks for your answers. I am going to study these docs and will come back if have any additional questions.

**Comment by linsun** [comment]
Thanks @wattli  for your comments!  That is interesting (Whether a service-to-service communication is mTLS or http is determined by server side).  Q: can service B sends http to service A when service B is configured with mTLS and service A is configured with non-mTLS?   In the past, I haven't been able to get this working so I ended up configuring both to non mTLS.

**Comment by wattli** [comment]
Close it for now. @maxkondr , please feel free to reopen it if necessary.
