### ISSUE TITLE
webhook-create-signed-cert.sh error

### ISSUE THREAD

**Issue by fengjian1585** [istio/istio#4765]
[root@master1 istio-0.7.1]# ./install/kubernetes/webhook-create-signed-cert.sh \
>     --service istio-sidecar-injector \
>     --namespace istio-system \
>     --secret sidecar-injector-certs
creating certs in tmpdir /tmp/tmp.aGhs59QgVL 
Generating RSA private key, 2048 bit long modulus
.......................................+++
........+++
e is 65537 (0x10001)
certificatesigningrequest.certificates.k8s.io "istio-sidecar-injector.istio-system" created
NAME                                  AGE       REQUESTOR   CONDITION
istio-sidecar-injector.istio-system   0s        admin       Pending
certificatesigningrequest.certificates.k8s.io "istio-sidecar-injector.istio-system" approved

error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

##############
kube-apiserver  config
 admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,PersistentVolumeLabel,ResourceQuota,NodeRestriction,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Initializers 

#########
[root@master1 istio-0.7.1]# kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
node1     Ready     <none>    22h       v1.10.0
node2     Ready     <none>    22h       v1.10.0

**Comment by Tahler** [comment]
Found a work-around: istio/issues#261.
