### ISSUE TITLE
Add helm lint to `bin/linters.sh`

### ISSUE THREAD

**Issue by sdake** [istio/istio#4766]
Add helm lint to `bin/linters.sh`

**Comment by m1093782566** [comment]
@sdake 

I am a new contributor to Istio and would love to offer help. I think this issue can be my start point of contributing, but I am not very clear about this issue. So, could you please explain a bit more on the background?

THANKS!

**Comment by gyliu513** [comment]
@m1093782566 this is mainly used to examines a chart for possible issues by istio via `helm lint` in `bin/linters.sh`.

@sdake

**Comment by ymesika** [comment]
Fixed by #5406 
/close
