### ISSUE TITLE
Config validation also check for conflicts with existing configs

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4767]
Currently, validation only run on the new config that is being submitted. For some use cases, e.g authentication policy, we also want to check if there is any other config with the same scope/target that already exists. In order to do so, the validation code may need to pull all resources of the same kind. Does this sound reasonable?

**Comment by xiaolanz** [comment]
kubernetes api model explicitly discourage cross referencing validation. This is the major motivation we develop service configure and Galley is to introduce a layer of cross-referencing before the generating component level configs.
