### ISSUE TITLE
Can't Build Container on M1 Mac

### ISSUE THREAD

**Issue by KrisJohnstone** [istio/istio#47687]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Trying to build docker containers, results in the following error:
```shell
2023-11-01T12:54:17.380208Z	info	Running command: docker buildx bake -f /work/out/linux_arm64/dockerx_build/docker-bake.json all
ERROR: Cannot connect to the Docker daemon at unix:///Users/krisjohnstone/.docker/run/docker.sock. Is the docker daemon running?
2023-11-01T12:54:17.417170Z	info	build complete	runtime=1.928716001s
```

Things I've tried:
- Turning on/off [default docker support](https://docs.docker.com/desktop/settings/mac/#advanced-1)
- Setting DOCKER_SOCKET_MOUNT:
  - DOCKER_SOCKET_MOUNT="-v /Users/krisjohnstone/.docker/run/docker.sock:/Users/krisjohnstone/.docker/run/docker.sock"
- Running as sudo/root
  - sudo make docker.pilot
  - sudo sh then make docker.pilot  
- Setting 777 on the socket
```shell
ls -la /Users/krisjohnstone/.docker/run/docker.sock
srwxrwxrwx  1 krisjohnstone  staff  0  1 Nov 22:34 /Users/krisjohnstone/.docker/run/docker.sock
```

### Version

```Text
❯ docker version
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### Additional Information

_No response_

**Comment by ericvn** [comment]
I used to have to set `export DOCKER_SOCKET_MOUNT=-v /var/run/docker.sock.raw:/var/run/docker.sock` on my Mac when I was using Docker Desktop (was Intel at the time). Today I have an M2 MBP but since I can't use Docker Desktop anymore (company decision), I've moved to an Ubuntu VM in UTM which has docker installed and I remote to it via ssh (including VSCode).

Docker has been very flakey with various socket mounting issues. I usually run something like `docker run -v /var/run/docker.sock.rae:/var/run/docker.sock -it -u 501: --rm docker docker ps` to verify releases. I had a long running issue open with them for fixing this at various times.

**Comment by ericvn** [comment]
Also, there were issues with Docker Desktop relative to which context one was using. The context might be different inside the build container than what one expected and I ran into issues there as well. There was some discussion here: https://github.com/docker/for-mac/issues/5787#issuecomment-868662836

**Comment by zirain** [comment]
last time I meet this issue, I recall I switch the cotext.
<img width="1072" alt="image" src="https://github.com/istio/istio/assets/4354057/6ea1d762-c051-4838-9010-6d975699011a">

**Comment by shubham1172** [comment]
Thanks @zirain, switching to the default context solved it for me - `docker context use default`.
