### ISSUE TITLE
istioctl add 'approval' stamp to resource

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4768]
To prevent customer submit config via kubectl (and doesn't have necessary validation), should we make istioctl add some annotation to the resource, and pilot should use those that have such signature?

It's not bullet proof, but at least make error cause by wrong kubectl use harder.

**Comment by xiaolanz** [comment]
We are still deciding the roles of istioctl. We are adding server-side validation which is P0 for 1.0. After that, we expect you should experience the same validation experience through kubectl.
