### ISSUE TITLE
Use ProxyConfig CR to config tracing

### ISSUE THREAD

**Issue by erenliu168** [istio/istio#47700]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I want to config custom tracing  options (Skywalking) for apps in different projects (or namespace, workload) without modifying global mesh configuration (Jaeger).
So I think it is more flexible or appropriate to use ProxyConfig CR to set custom tracing  options of proxies. Besides, it can also be used to set other configuration to override global options like concurrency, proxyHeaders and so on.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
please use Telemetry API to do this.

**Comment by erenliu168** [comment]
> please use Telemetry API to do this.

I see. But if I want to add skywalking in tracing using Telemetry API, I still need to add information for it in extensionProviders in MeshConfig. Is that?

**Comment by erenliu168** [comment]
> please use Telemetry API to do this.

So my another point is to make the configuration of skywalking work without modifying the global MeshConfig.

> > please use Telemetry API to do this.
> 
> I see. But if I want to add skywalking in tracing using Telemetry API, I still need to add information for it in extensionProviders in MeshConfig. Is that?



OK, I

> please use Telemetry API to do this.

So my another point is to make the configuration of Skywalking work without modifying the global MeshConfig as I want to just focus on one standalone CR.

**Comment by zirain** [comment]
what I can say, that's not ProxyConfig design for.

**Comment by erenliu168** [comment]
OK. Thanks.
