### ISSUE TITLE
Istio ingress MTLS: TLS alert, unsupported certificate (555)

### ISSUE THREAD

**Issue by freddyaott** [istio/istio#47708]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi all,

I configured a MUTUAL Authentication on my Istio Ingress

`spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: ingress-client-credential
        mode: MUTUAL
        subjectAltNames:
          - test.com
          - test1.com
          - test2.com
`
In the  _ingress-client-credential_ there are my server certificare with private key.
I also create a secret ingress-client-credential-cacert with the CA certificate used to sign test.com, test1.com and test2.com certificates.

The _test.com's_ certificate is created **without x509v3 extension extendedKeyUsage**
The _test1.com's_ certificate is created with x509v3 extension extendedKeyUsage = **clientAuth, serverAuth**
The _test2.com's_ certificate is created  with x509v3 extension extendedKeyUsage = **serverAuth, clientAuth**

Everithing works well if I make a call with certificate test.com and test1.com, TLS handshake recognize the certificate and validate the connection.

On the other hand, if I use certificate test2.com, I receive the following error by Istio Ingress in validating the certificate:
**TLSv1.3 (IN), TLS alert, unsupported certificate (555):**
OpenSSL SSL_read: OpenSSL/3.1.2: error:0A000413:SSL routines::sslv3 alert unsupported certificate, errno 0

Note that, both certificate test1.com and test2.com have the same extendedKeyUsage but in different order.
The one which have _**clientAuth in the first position**_ works well, the other not.

I think that Istio ingress, checks only the first occurance of extendedKeyUsage and in IMHO it's wrong.
It should be able to check in all the array.

Thanks
king regards.

### Version

```Text
$ istioctl version
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.18.1 (2 proxies), 1.19.3 (8 proxies)
$ kubectl version --short
Client Version: v1.26.4-eks-0a21954
Kustomize Version: v4.5.7
Server Version: v1.26.9-eks-f8587cb
```

**Comment by hzxuzhonghu** [comment]
Can you provide the certificate you test? With certs generated by istio script `pkg/testcerts/generate-certs.sh`, there is no issue even change to `serverAuth, clientAuth`
