### ISSUE TITLE
Istio helm not working using release artifacts in 0.7.1

### ISSUE THREAD

**Issue by ameer00** [istio/istio#4770]
I am on Kubernetes Engine (on GCP) ver 1.8.8-gke.0
Installing Istio 0.7.1 using helm chart is failing.   I have created a brand new server.  Here is the error message:
ameerabbas@ameer-1:~$ cd istio-0.7.1/
ameerabbas@ameer-1:~/istio-0.7.1$ kubectl create -f install/kubernetes/helm/helm-service-account.yaml
serviceaccount "tiller" created
clusterrolebinding "tiller" created
ameerabbas@ameer-1:~/istio-0.7.1$ helm init --service-account tiller
$HELM_HOME has been configured at /home/ameerabbas/.helm.
Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Happy Helming!
ameerabbas@ameer-1:~/istio-0.7.1$ helm install install/kubernetes/helm/istio --name istio
Error: render error in "istio/charts/security/templates/serviceaccount.yaml": template: istio/charts/security/templates/serviceaccount.yaml:6:21: executing "istio/charts/security/templates/serviceaccount.yaml" at <{{template "security...>: template "security.name" not defined
ameerabbas@ameer-1:~/istio-0.7.1$

**Comment by ldemailly** [comment]
Assuming this isn’t a doc or user error:

@linsun during the 3 weeks of baking/manual testing of 0.7.0 and 0.7.1 noone tried helm?

if we are getting serious about helm install we better have a test for it (additional test, not dropping the existing istio*.yanl tests)

cc @mandarjog @costinm @hklai

**Comment by ejwood79** [comment]
I'm seeing the same issue, and it's blocking my upgrade from 0.5 to 0.7.1. I actually removed 0.5 manually under the assumption that we'd have a working helm chart.

```
helm template istio --name istio --namespace istio
Error: render error in "istio/charts/pilot/templates/serviceaccount.yaml": template: istio/charts/pilot/templates/serviceaccount.yaml:5:20: executing "istio/charts/pilot/templates/serviceaccount.yaml" at <{{template "pilot.se...>: template "pilot.serviceAccountName" not defined
```

**Comment by linsun** [comment]
the fact is that people only tried master, which does work, but not the released artifact.  Please see 0.7.1 release note for the workaround for this.

Do we have any test to test release artifact?   It would be good to add to that test bucket.

close as dup of https://github.com/istio/istio/issues/4701

**Comment by hklai** [comment]
@linsun currently daily qualification tests sit in https://github.com/istio-releases/daily-release/tree/master/prow (note the different org).

You can add new helm tests there if they are can made to run by prow. Otherwise, we can also hook up with circle as we just use PR to trigger tests (e.g. https://github.com/istio-releases/daily-release/pull/502)

**Comment by ejwood79** [comment]
To be honest, while the release notes point to GitHub issue #4701, the "workaround" is not entirely clear. In other words, I thought I did what the issue said and still ran into a problem. Also, I don't think it's entirely reasonable to expect that the community would pull down master to run a helm install of what is supposed to be a release.

If we expect that istio is going to be widely adopted by the community, a more helpful response to those asking questions would be much appreciated.

**Comment by ldemailly** [comment]
@hklai can you make sure for future release that people do sign up for testing helm with the pre-release (or the dailies) - in addition to have a test

**Comment by hklai** [comment]
@ldemailly @linsun I can help ensure that helm is covered in the manual testing phase of monthly releases.

I think/agree that we need automated tests ASAP. We found helm problems right after monthly release twice already.

**Comment by linsun** [comment]
Agreed, I have some partial code for automated helm test I did a while back, I'll finish it.
