### ISSUE TITLE
use EXIT_ON_ZERO_ACTIVE_CONNECTIONS，grpc service receiver NO_ERROR Received Goaway

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#47718]
We set EXIT_ON_ZERO_ACTIVE_CONNECTIONS true. When our service pod is terminating，service will receiver error, log as follow:
c.t.n.i.s.s.i.EventServiceImpl: Unexpected exception
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway

Prestop in deployment of our service, we use our stop.sh and will sleep 30s before shutdown out service. sleep 30s is writtend in stop.sh.
The exception is receiver in the 30s of sleep.
We also find that there is no accesslog for error request and in the time before and after,there is success request for our service to request upstream service。

istio version is 1.16.4
k8s version is 1.24

**Comment by ramaraochavali** [comment]
Do you want your pod to stay up for 30s, even when there are no active connections?  If yes, you need to set MINIMUM_DRAIN_DURATION to 30s

**Comment by kevinyangI** [comment]
@ramaraochavali Thank you for your reply. We encountered the same problem, I have two questions:
1. MINIMUM_DRAIN_DURATION will be executed first, so why not just set it to 0, and let EXIT_ON_ZERO_ACTIVE_CONNECTIONS to determine when to shutdown? Curious why do you need to set a static 30s before dynamic connection check? #https://github.com/istio/istio/issues/44690#issuecomment-1636339524
2. Prestop in deployment of our service, we use our stop.sh and will sleep 30s before shutdown out service. sleep 30s is writtend in stop.sh. There are no exceptions in the first five seconds(MINIMUM_DRAIN_DURATION default value is 5s), but intermittent exceptions(UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway) occurred in outgoing grpc calls within five seconds to 30 seconds. I am curious about the reason. Do you have any troubleshooting ideas?

**Comment by ramaraochavali** [comment]
We do not set it to 30s. The current default of MINIMUM_DRAIN_DURATION to 5s is because of historical reasons + some race condition involved (The PR should have have all the discussion). We can not change that now. 

It is because Envoy goes in to draining mode after MINIMUM_DRAIN_DURATION and actively sends go aways I think

**Comment by kevinyangI** [comment]
> It is because Envoy goes in to draining mode after MINIMUM_DRAIN_DURATION and actively sends go aways I think

This("actively sends go aways") is detrimental to the service and doesn't sound like graceful downtime is achieved? Under what circumstances will goaway be sent? Because I see that most grpc requests are successful and only a few exceptions.

Does this mean that it is best to enter draining mode after the application container has completed a graceful shutdown?

**Comment by ramaraochavali** [comment]
are you seeing this behaviour for inbound/outbound?

**Comment by hzxuzhonghu** [comment]
With native sidecar support, can we use that to workaround it

**Comment by id-id-id** [comment]
> are you seeing this behaviour for inbound/outbound?

outbound

**Comment by ramaraochavali** [comment]
oubound calls should not have any impact for sidecars. We drain inbound listeners only. But I guess, since the active connections becomes, the proxy might have shutdown. If you want proxy to be up till 30s, you should set MIN_DRAIN_DURATION

**Comment by id-id-id** [comment]
> oubound calls should not have any impact for sidecars. We drain inbound listeners only. But I guess, since the active connections becomes, the proxy might have shutdown. If you want proxy to be up till 30s, you should set MIN_DRAIN_DURATION

From log of istio-proxy，we find the number of active connections is not 0 when an error is reported, which should not trigger proxy shutdown.

**Comment by ramaraochavali** [comment]
Can you share proxy log?

**Comment by id-id-id** [comment]
> > oubound calls should not have any impact for sidecars. We drain inbound listeners only. But I guess, since the active connections becomes, the proxy might have shutdown. If you want proxy to be up till 30s, you should set MIN_DRAIN_DURATION
> 
> From log of istio-proxy，we find the number of active connections is not 0 when an error is reported, which should not trigger proxy shutdown.

We set MIN_DRAIN_DURATION=30s, and It doesn't solve the problem. And in the accesslog，we find all request is receiver 200 in accesslog.
Log as follow.
2023-11-07T12:36:15.086402Z	info	Agent draining Proxy
2023-11-07T12:36:15.087454Z	info	Agent draining proxy for 30s, then waiting for active connections to terminate...  
[2023-11-07T12:36:15.113Z] "POST /xxxxx HTTP/2" 200 - via_upstream - "-" 47 17 16 16 "-" "grpc-java-netty/1.25.0" "0fcafe45-824d-4166-a256-beb72343ba17" "xxxxx:8850" "10.53.29.52:8850" outbound|8850||xxxxx.xxxx.svc.cluster.local xxxxxx:41818 xxxx:8850 xxxxx:36076 - -
[2023-11-07T12:36:15.113Z] "POST /xxxxx HTTP/2" 200 - via_upstream - "-" 47 17 14 13 "-" "grpc-java-netty/1.25.0" "b61cfc32-22df-4592-99c5-78b941365424" "xxxx:8850" "xxxx:8850" outbound|8850||xxxx.xxxx.svc.cluster.local xxxx:41818 xxxx:8850 xxxx:36076 - -
……
[2023-11-07T12:36:17.541Z] "POST /xxxx HTTP/2" 200 - via_upstream - "-" 33 15 2 2 "-" "grpc-java-netty/1.25.0" "76ffec4c-06ce-41db-98bd-2919c806df97" "xxxx:8850" "10.53.29.52:8850" outbound|8850||xxxx.xxxx.svc.cluster.local xxxx:41818 xxxx:8850 xxxx:36928 - -
[2023-11-07T12:36:17.547Z] "POST /xxxx HTTP/2" 200 - via_upstream - "-" 47 242 23 23 "-" "grpc-java-netty/1.25.0" "5f84cf3a-f26f-40fa-8898-549f96be6363" "xxx:8850" "xxxx:8850" outbound|8850||xxx.xxxx.svc.cluster.local 10.53.43.133:43068 xxx:8850 xxx:36940 - -
2023-11-07T12:36:45.088447Z	info	Checking for active connections...
2023-11-07T12:36:46.280820Z	info	There are still 466 active connections
2023-11-07T12:36:47.298137Z	info	There are still 419 active connections
……
2023-11-07T12:37:14.306157Z	info	There are still 440 active connections


And in 12:36:17 our service receiver a error, log as follow:
11-07-2023 12:36:17.547 ERROR [tapo-event-48-1] [TID: 2810340d8f4a4c3a9f9b380c10e6f8cc.3796.16993605401640205] c.t.n.i.s.s.i.EventServiceImpl: Unexpected exception
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway 

In 12:36:17, accesslog in isito-proxy show the request is receiver 200 but our service throw exception.
