### ISSUE TITLE
mTLS over tracing backend

### ISSUE THREAD

**Issue by wattli** [istio/istio#4771]
Customers want to encrypt their traffic to tracing backend with mTLS. 

_"Is it possible to enable side-car and mutual TLS for the tracing backend communication? 
I would like to have my traffic for publishing the spans/traces as well as the query for the UI use mutual TLS. The documentation https://istio.io/docs/tasks/telemetry/distributed-tracing.html does not provide any details in this regards."_

Original post: https://groups.google.com/forum/#!topic/istio-users/U6NotksCr8o

**Comment by wattli** [comment]
Two things we need to investigate:

1) When mTLS enabled, would https://github.com/istio/istio/issues/4771 work? I assume it should, but need verification.

2) When we put a sidecar in front of zipkin/jaeger using kube-inject, would it still work without mTLS, and with mTLS?

**Comment by sakshigoel12** [comment]
@JimmyCYJ can you update this issue

**Comment by JimmyCYJ** [comment]
I don't have update for this issue. Will look into this issue later this week.

**Comment by yangminzhu** [comment]
@JimmyCYJ Is this still needed? There has been no update for about 1.5 years.

**Comment by diemtvu** [comment]
Close this for now. We will reopen this (with better priority) when there are stronger demands.
