### ISSUE TITLE
Prometheus agent unable to connect with istio metrics endpoint to scrape the metrics over the mutual tls

### ISSUE THREAD

**Issue by amolvgaikwad** [istio/istio#47738]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have Kubernetes cluster, I am using the Istio service mesh for internal communication, ingress gateways. 
for monitoring i have deployed Prometheus  agent which should scrape the metrics over the mutual tls but somehow prometehus unable to scrape the metrics. 

<html>
<body>

Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
https://voting-app-frontend.voting-app.svc.cluster.local:15020/stats/prometheus | DOWN | instance="voting-app-frontend.voting-app.svc.cluster.local:15020"job="voting-app" | 1m 47s ago | 30.0s | Get https://voting-app-frontend.voting-app.svc.cluster.local:15020/stats/prometheus: context deadline exceeded

</body>
</html>

Prometheus agent able to scrape  the metrics without mutual tls.  I have referred this document.
https://istio.io/latest/docs/ops/integrations/prometheus/

based on doc i have injected envoy proxies in prometheus pods and mounted istio certs in prometehus pod so prometheus will able to scrape the my voting-app application metrics.

Appreciate any kind of help.

### Version

```Text
istio 1.17 distroless

istio controlpane deployed using the istio operator.
```

**Comment by howardjohn** [comment]
You can scrape *your app* over TLS. But not istio's sidecar (port 15020) - that is only over plaintext
