### ISSUE TITLE
force max_connections greater than 1024

### ISSUE THREAD

**Issue by prune998** [istio/istio#4777]
When `Pilot` return the `Cluster` list to a `sidecar proxy`, the default 1024 limits from Envoy is used.
ex : 
```
{
  "clusters": [
   {
    "name": "in.1080",
    "connect_timeout_ms": 1000,
    "type": "static",
    "lb_type": "round_robin",
    "hosts": [
     {
      "url": "tcp://127.0.0.1:1080"
     }
    ]
   },
...
```

`Pilot` should either : 
- use the limit from the Destination's `CircuitBreaker`
- increase the default `Envoy` limit from 1024 to a larger number

End config should be something like : 
```
{
  "clusters": [
   {
    "name": "in.1080",
    "connect_timeout_ms": 1000,
    "type": "static",
    "lb_type": "round_robin",
    "hosts": [
     {
      "url": "tcp://127.0.0.1:1080"
     },
    ]
    "circuit_breakers": {
     "default": {
      "max_connections": 100000,
      "max_pending_requests": 1000,
      "max_requests": 100000
      }
     }
   },
```

This issue is linked to https://github.com/istio/istio/issues/4751 
While 0.8.0 will use the v2 API, it's really time to change this behaviour !

**Comment by linsun** [comment]
cc @ijsnellf @GregHanson @rshriram @costinm to comment if this issue is/will being addressed in v1alpha3

**Comment by prune998** [comment]
I think it is solved for the XDS but it's not yet done for istio-to-istio setup (linke ingress -> istio-proxy in a pod).

**Comment by linsun** [comment]
Is this still a prob in 1.0?  Isaiah is probably not going to have time for this.

**Comment by mbanikazemi** [comment]
If destination rule is defined with trafficPolicy, I see that the corresponding clusters get configured correctly. That is if connectionPool parameters are defined they get reflected in the configuration of the cluster. I also verified that this get propagated to all pods (sidecars) including ingress/egress pods (routers) as expected. 

@prune998 If you still experience a problem, please update this issue.

**Comment by mbanikazemi** [comment]
@esnible  per latest comment by @prune998 on issue #4751  please close. (In case there is any issues we will reopen.)
