### ISSUE TITLE
Getting ClientCertAuthenticator in istiod

### ISSUE THREAD

**Issue by crux-forum** [istio/istio#47791]
Hi Team,

We have deployed istio 1.14 in AWS EKS version 1.25 and getting the below error is istiod pod. Can you please let us know what is the issue?
```
Failed to authenticate client from x.x.x.x:52560: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster <cluster-name>'s kube client
99
2023-11-08T11:46:02.172583Z	error	ads	Failed to authenticate client from  x.x.x.x:53374: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster <cluster-name>'s kube client

```

**Comment by wulianglongrd** [comment]
The agent on the data plane needs to be authenticated when connecting to istiod (authentication is required only when connecting to istiod's port 15012. It is not required if it connects to port 15010, but unauthenticated agents cannot get secret data through XDS). 

You are currently using the default jwt authentication. However, during authentication, istiod cannot get the kube client through the `clusterid` carried in the request header.

**Comment by crux-integration** [comment]
Thanks @wulianglongrd  For the quick response. Can you let us know how to fix this? Do you suspect this an configuration issues or some missing permissions on the EKS cluster?

**Comment by wulianglongrd** [comment]
TBH, I don't know, I have never used AWS. But, if you manually registered the `ISTIO_META_CLUSTER_ID` environment variable, try resetting it(default value is empty string).

**Comment by hzxuzhonghu** [comment]
what is ` <cluster-name>`

**Comment by crux-integration** [comment]
@hzxuzhonghu  Istio is deployed using helm charts. 
cluster-name is the name of the kubernetes cluster in which istio is deployed.

**Comment by hzxuzhonghu** [comment]
but istio use `kubernetes` as the default value, do you change both side?

**Comment by crux-forum** [comment]
@hzxuzhonghu Default value for what? I didn’t change anything as such.

**Comment by hzxuzhonghu** [comment]
so what is `<cluster-name>`

**Comment by hzxuzhonghu** [comment]
where does istio read this value `<cluster-name>`?

**Comment by crux-forum** [comment]
@hzxuzhonghu Thanks for pointing this out, I realised on checking that it was pointing to the cluster's name which was hard-coded in the values.yaml file. Upon removing it we are not getting the error logs anymore.

**Comment by wulianglongrd** [comment]
Feel free to reopen it if needed.
