### ISSUE TITLE
Failed to release lock: Operation cannot be fulfilled on leases.coordination.k8s.io "istio-gateway-deployment-default"

### ISSUE THREAD

**Issue by hprx** [istio/istio#47792]
### Bug Description

Our configuration is the following:
- AWS EKS
- Istio installed from scratch via istioctl
- 3 replicas of istiod

We have noticed that from time to time there is a log in a replica of istiod (happens in any of istiod replicas) :
`error    klog    Failed to release lock: Operation cannot be fulfilled on leases.coordination.k8s.io "istio-gateway-deployment-default": the object has been modified; please apply your changes to the latest version and try again`

`kubectl get lease -n istio-system` shows us that each replica of istiod takes control over this lease approximately every 7 seconds, therefore we have high count for leaseTransitions

`kubectl get -o yaml lease/istio-gateway-deployment-default -n istio-system `
...
`leaseDurationSeconds: 30`
`leaseTransitions: 7261`
....

I believe the error that we have is due to several replicas at the same time try to put the lock into this lease which is causing the error `the object has been modified; please apply your changes to the latest version and try again`

Questions:
- Is it expected that each replica takes control over this lease so frequently? 
- If this is expected how we can avoid the issue that I described above?

### Version

```Text
istioctl version
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3

kubectl version
Client Version: v1.28.2
Server Version: v1.28.2
```

**Comment by howardjohn** [comment]
`leaseTransitions: 7261` is expected if the leader pod has shutdown ~7261 times. Is the leader transitioning more times than the leader pod is shutting down?

**Comment by hprx** [comment]
@howardjohn the issue here that we don't have any restarts of any istiod replicas

for the time being we have in one of our clusters 3 istiod replicas running for 12 days with 0 restarts and `leaseTransitions: 447014`. like I described above each istiod pod every 7 seconds takes control over this lease

**Comment by howardjohn** [comment]
Well at least its always happening so likely easy to debug :slightly_smiling_face: 

can we get the `-w` with  `-oyaml` for a few transitions, and the logs form the istiod pods with `--vklog=6 --log_output_level=klog:debug`? I think the latter should give us some useful logs

**Comment by hprx** [comment]
@howardjohn as far as I can see there is `HolderKey` should be presented in the structure  
https://github.com/istio/istio/blob/1.19.3/pilot/pkg/leaderelection/k8sleaderelection/leaderelection.go#L342

But I don't see this key in `lease/istio-gateway-deployment-default` 

A few iterations with `-o yaml -w lease/istio-gateway-deployment-default` (in this case we had 2 istiod replicas for demo purposes):
```apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-11-13T11:20:38Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "382801833"
  uid: 52640a58-6bd0-4166-be38-5d6435dd8c38
spec:
  acquireTime: "2023-11-13T11:40:47.858382Z"
  holderIdentity: istiod-7d5b558864-9p2xk
  leaseDurationSeconds: 30
  leaseTransitions: 283
  renewTime: "2023-11-13T11:40:47.858382Z"
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-11-13T11:20:38Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "382801855"
  uid: 52640a58-6bd0-4166-be38-5d6435dd8c38
spec:
  acquireTime: "2023-11-13T11:40:51.564037Z"
  holderIdentity: istiod-7d5b558864-zb29r
  leaseDurationSeconds: 30
  leaseTransitions: 284
  renewTime: "2023-11-13T11:40:51.564037Z"
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-11-13T11:20:38Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "382801878"
  uid: 52640a58-6bd0-4166-be38-5d6435dd8c38
spec:
  acquireTime: "2023-11-13T11:40:55.369349Z"
  holderIdentity: istiod-7d5b558864-9p2xk
  leaseDurationSeconds: 30
  leaseTransitions: 285
  renewTime: "2023-11-13T11:40:55.369349Z"  
```


each of istiod replicas had the following logs (reduced to `klog` related to this issue):
```
2023-11-13T11:41:51.707741Z	info	klog	GET https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/istio-system/leases/istio-gateway-deployment-default 200 OK in 11 milliseconds
2023-11-13T11:41:51.707828Z	debug	klog	lock is held by istiod-7d5b558864-9p2xk with key , but our key () evicts it
2023-11-13T11:41:51.714229Z	info	klog	PUT https://172.20.0.1:443/apis/coordination.k8s.io/v1/namespaces/istio-system/leases/istio-gateway-deployment-default 200 OK in 6 milliseconds
2023-11-13T11:41:51.714288Z	debug	klog	successfully renewed lease istio-system/istio-gateway-deployment-default
```

looks like the issue is in `lock is held by istiod-7d5b558864-9p2xk with key , but our key () evicts it` https://github.com/istio/istio/blob/1.19.3/pilot/pkg/leaderelection/k8sleaderelection/leaderelection.go#L378

do you have any idea why a replica of istiod have `holderKey` as an empty value and didn't set it to `Lease` object?

at the same time I can see `HolderKey` in a configmap:
```
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"istiod-7d5b558864-9p2xk","holderKey":"default","leaseDurationSeconds":30,"acquireTime":"2023-11-13T11:22:43Z","renewTime":"2023-11-13T11:50:32Z","leaderTransitions":2}'
```

**Comment by howardjohn** [comment]
Thanks, I think this is a bug. Not sure why you hit it and others don't -- will look into it.

Its not set on Lease since holderKey is an istio specific thing, and not in the real Lease. We had a KEP to add it but it never moved forward.

**Comment by hprx** [comment]
@howardjohn could this potentially lead to any performance or stability issues?

**Comment by howardjohn** [comment]
Yes, this is a bug we should fix

**Comment by howardjohn** [comment]
Ended up doing two implementations. Added support in Lease in https://github.com/howardjohn/istio/pull/new/lock/lease-leader-election, but realized its overkill and opened https://github.com/istio/istio/pull/47848

**Comment by nadeemhussain** [comment]
are we using lease object or it is configmap for leader election  https://github.com/istio/istio/issues/44756

**Comment by howardjohn** [comment]
We use both depending on the election (for backwards compat)

**Comment by nadeemhussain** [comment]
having the same issue , the lease is changing way too fast , 

```
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-09-11T09:17:21Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "468204610"
  uid: a367c2a9-0c10-485d-b11a-f1eac6a85def
spec:
  acquireTime: "2023-11-24T22:19:50.113333Z"
  holderIdentity: istiod-6ccb9885f4-gqz6p
  leaseDurationSeconds: 30
  leaseTransitions: 19888135
  renewTime: "2023-11-24T22:19:50.113333Z"
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-09-11T09:17:21Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "468204657"
  uid: a367c2a9-0c10-485d-b11a-f1eac6a85def
spec:
  acquireTime: "2023-11-24T22:19:50.325092Z"
  holderIdentity: istiod-6ccb9885f4-h4z5x
  leaseDurationSeconds: 30
  leaseTransitions: 19888136
  renewTime: "2023-11-24T22:19:50.325092Z"
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-09-11T09:17:21Z"
  name: istio-gateway-deployment-default
  namespace: istio-system
  resourceVersion: "468204715"
  uid: a367c2a9-0c10-485d-b11a-f1eac6a85def
spec:
  acquireTime: "2023-11-24T22:19:50.553875Z"
  holderIdentity: istiod-6ccb9885f4-tv2k7
  leaseDurationSeconds: 30
  leaseTransitions: 19888137
  renewTime: "2023-11-24T22:19:50.553875Z"
```

and the leader in the cm remains the same , over a long time 

```
{
  "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"istiod-6ccb9885f4-4g4qn\",\"holderKey\":\"default\",\"leaseDurationSeconds\":30,\"acquireTime\":\"2023-11-24T18:29:16Z\",\"renewTime\":\"2023-11-24T22:22:34Z\",\"leaderTransitions\":13}"
}

```

so in this case which one take effect as both have different leader.

**Comment by howardjohn** [comment]
Yeah its fixed in https://github.com/istio/istio/pull/47848 but that hasn't released yet.

**Comment by avistech** [comment]
hi, we upgraded Istio from **1.18.2** to **1.19.4** version in UAT env and started noticing this error message in istiod pods but we haven't noticed any issues with functionality. May i know how will this impact our mesh and should we hold on the upgrade until the fix is available, thanks

`error	klog	Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "istio-gateway-deployment-1-19-4": the object has been modified; please apply your changes to the latest version and try again`
