### ISSUE TITLE
investigate using dind for k8s for testing

### ISSUE THREAD

**Issue by linsun** [istio/istio#4779]
http://callistaenterprise.se/blogg/teknik/2017/12/20/kubernetes-on-docker-in-docker/

Opening this to document discovery for this journey.  One requirement is snapshot, can we do snapshot this way.  cc @hklai @louiscryan

**Comment by hklai** [comment]
We made vagrant work and that theoretically supports snapshotting already.
https://github.com/istio/istio/tree/master/tests/e2e#using-a-local-vm
