### ISSUE TITLE
Update respect_dns_ttl value by envoyfilter

### ISSUE THREAD

**Issue by ninoamine** [istio/istio#47816]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello,

I'am trying to change the value of respect_dns_ttl to false using the envoyFilter CRD, like this:
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-ttl
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        respect_dns_ttl: false
But does do any changes.

Can you pleas check if my envoyfilter is correct ? and if there any other way to change it ?

Thank you

### Version

```Text
helm version --shor
v3.12.3+g3a31588
```

**Comment by ninoamine** [comment]
sorry for the copy paste:
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-ttl
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        respect_dns_ttl: false`

**Comment by howardjohn** [comment]
probably from https://github.com/istio/istio/issues/18169

**Comment by hzxuzhonghu** [comment]
This is limited by protobuf, it can not distinguish between unset or default value.

**Comment by GregHanson** [comment]
closing as not supported / dup of https://github.com/istio/istio/issues/18169
