### ISSUE TITLE
Support Conditional Logic in Telemetry Configuration for Dynamic Metric Labels EnvoyFilter

### ISSUE THREAD

**Issue by echoava** [istio/istio#47827]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In our k8s cluster, we have enabled the labels "request.url_path" and "request.method" and dont include "workloadSelector" in Envoyfilter to specify the apps, so that every API hosted on the the cluster would have those two labels reported in Premetheus server.
However, there is a scenario that if any API has path parameters (e.g., `/v1/message/{conversationId}`), Istio's telemetry captures the entire URL in metrics, leading a high cardinality in Prometheus. 
The use of Lua and WASM filters can modify request/response metadata, the modification only affects the Enovy dynamic metadata space. However, the dynamic metadata is not directly used by the default istio telemetry set up (i.e, 'istio.stats' filter) when reporting metrics to Prometheus.

**Describe alternatives you've considered**
I come cross this post https://stackoverflow.com/questions/30967822/when-do-i-use-path-params-vs-query-params-in-a-restful-api. and this example use case is modifying the `request.url_path` metric label based on the presence of a custom header (like `x-prometheus-url-path`). If the header is present, the metric label would use the header's value; otherwise, it would default to the standard `request.url_path.'. And this solution wont wont work unless that EnvoyFitler could support conditional logic in Telemetry configuration for dynamic metric labels.

I propose adding a feature to Istio's telemetry configuration that allows for conditional logic in defining metric labels. For instance, a syntax resembling a ternary operator (e.g., `condition ? value_if_true : value_if_false`) could be used to dynamically set a metric label based on the presence of a specific header.

**Benefits:**
- **Reduced Cardinality**: Allows for more control over metric labels, reducing potential high cardinality in Prometheus, especially in APIs with path parameters.
- **Enhanced Flexibility**: Provides users with more flexibility in defining how metrics are labeled based on the dynamic context of requests and responses.
- **Improved Telemetry Customization**: Enhances Istio's telemetry customization capabilities, aligning with diverse user needs and use cases.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
is [this](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values) what you want?
