### ISSUE TITLE
Add from_cookies option into JWTRule

### ISSUE THREAD

**Issue by snuggie12** [istio/istio#47847]
**Describe the feature request**
I noticed in (envoy)[https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto] there's an option called `from_cookies` to extract the jwt. Could we add that as an option into `RequestAuthentication`/`JWTRule`?

**Describe alternatives you've considered**
I believe an `EnvoyFilter` using lua can extract a substring from `Cookie` but if it exists in envoy I figured it'd be easy to add to istio.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
I think it is reasonable, a simple change should work

**Comment by loeffel-io** [comment]
@hzxuzhonghu in which version is this available?
