### ISSUE TITLE
Should the ztunnel DaemonSet have priorityClassName: system-node-critical?

### ISSUE THREAD

**Issue by RobCannon** [istio/istio#47867]
**Describe the feature request**
The HelmChart for deploying ztunnel does not explicity set the priorityClassName, nor does it offer a setting in the template to set the value.  The `istio-cni` chart explicitly sets the priorityClassName here: https://github.com/istio/istio/blob/61ed8d599a84ff458a334479cd9dddeb61c52ebd/manifests/charts/istio-cni/templates/daemonset.yaml#L62
I would think that the ztunnel DaemonSet should also be classified as `system-node-critical`

Without this, when you try to deploy or upgrade ztunnel, pods can get stuck in `Pending` status with a message like '0/8 nodes are available: 1 Insufficient memory. preemption: 0/8 nodes are available: 8 No preemption victims found for incoming pod..'.  Setting the higher priority will ensure that ztunnel runs on all nodes.

**Describe alternatives you've considered**
I can set this value with a kustomization process on the helm chart, but I think that `system-node-critical` should be the default or only possibility, like the istio-cni DaemonSet.

**Affected product area (please put an X in all that apply)**

[X ] Ambient
[ ] Docs
[ ] Dual Stack
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This is a very easy PR to submit, which I can do, but I wanted to see if there was a good reason this should not be the default.

**Comment by hzxuzhonghu** [comment]
remember this was discussed somewhere before.  @costinm

**Comment by RobCannon** [comment]
I did search for this in issues and I couldn't find anything related to the ztunnel chart.  I do see requests for setting this in other charts and it has been added as an option to the gateway chart.

**Comment by hzxuzhonghu** [comment]
IMO, Ztunnel should be put higher priority than gateway

**Comment by costinm** [comment]
Agreed - CNI and ztunnel should both be critical. 

Unpopular opinion: CNI and ztunnel should also be in the same helm chart ( popular opinion seems to be that 
ztunnel should be implemented by the CNI layer directly - but for some reason us having a single helm chart for both
is not ok )

**Comment by costinm** [comment]
Note I didn't say 'same helm daemon set', as 2 separate containers - which would likely be even less popular - but how a native CNI implementation would likely do it ...

**Comment by RobCannon** [comment]
I created a PR for this change (linked above).  I am waiting for our Security Chief to approve our CLA when she gets back from Thanksgiving vacation.

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/issues/47867
