### ISSUE TITLE
read: connection reset by peer", received prior goaway: code: NO_ERROR

### ISSUE THREAD

**Issue by chnacib** [istio/istio#47889]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

im getting a random **read: connection reset by peer** in my application using istio-proxy as sidecar. When i check istio-proxy's logs, there is a lot of warn: ```xdsproxy        upstream [6396] terminated with unexpected error rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: read tcp 10.1.51.58:60692->172.20.31.154:15012: read: connection reset by peer", received prior goaway: code: NO_ERROR```. It happens sometimes when i try to access external services.

### Version

```Text
client version: 1.20.0
control plane version: 1.18.2
data plane version: 1.18.2 (654 proxies)
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.15-eks-4f4795d
```

**Comment by GregHanson** [comment]
Any other information you can provide about the setup? Clean install?  Recent upgrade? New pod deployment/re-deploy to an existing istio installation? Anything suspicious in `istioctl proxy-status` output (STALE?).  Anything from `istioctl analyze`?  If 15012 is having problems, the sidecar probably isn't receiving updates
