### ISSUE TITLE
BootstrapDS should ack/nack

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#47880]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

When looking into dynamic bootstrap config discovery, I can see that currently xds-proxy only handles the bootstrap response once.
No matter the processing fails or succeed, it never send an ACK/NACK to the istiod. It is not align with xds protocol, and also we have no way to know whether it has pushed bootstrap in istiod side. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
BTW, should istio make dynamic bootstrap default on?

**Comment by hzxuzhonghu** [comment]
I donot see urgent requirement, and not sure it is widely tested.

**Comment by zirain** [comment]
IMO, it will only effect when someone apply specific EnvoyFilter, so it's safe to flip on?

**Comment by hzxuzhonghu** [comment]
Sideceeffect is that can slow down proxy bootstraping, because it added one round trip for bootstrap config
