### ISSUE TITLE
Add a robot that merges automatically

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#479]
Have a robot that merges automatically when review + tests are Ok in all the repos.

There are cases where PRs get stuck in out of date branch, plus we would reduce the number of pre-submit runs.

**Comment by ldemailly** [comment]
it's almost there thanks to prow but not quite always working yet nor on for all repos

**Comment by linsun** [comment]
is this done but not working reliably?  not a stop ship for 0.2.

**Comment by ldemailly** [comment]
it's done but not in all repos and not 100% reliable yet - maybe we can close in favor of flat build
