### ISSUE TITLE
istioctl ps is missing cluster info for ztunnel

### ISSUE THREAD

**Issue by linsun** [istio/istio#47917]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Not sure if this is intended, but looks a little odd that info is missing for ztunnel:

```
istioctl ps
NAME                                                   CLUSTER        CDS         LDS         EDS         RDS          ECDS         ISTIOD                      VERSION
ztunnel-r5zn8.istio-system                                            IGNORED     IGNORED     IGNORED     IGNORED      IGNORED      istiod-64d79ff59d-bc89b     1.20.0
istio-ingressgateway-5d8fbb56df-2bvrc.istio-system     Kubernetes     SYNCED      SYNCED      SYNCED      NOT SENT     NOT SENT     istiod-64d79ff59d-bc89b     1.20.0
```

### Version

```Text
1.20.0
```

**Comment by linsun** [comment]
cc @birkland @ilrudie

**Comment by hanxiaop** [comment]
I think I had a fix before but it didn't get merged yet, let me find it.

**Comment by hanxiaop** [comment]
https://github.com/istio/ztunnel/pull/563

**Comment by ilrudie** [comment]
Looks like 1 small thing to correct is the env variable in the ds/ztunnel being set as `CLUSTER_ID` instead of `ISTIO_META_CLUSTER_ID`... will looks at making the quick adjustment to wrap this up shortly.

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/48303
