### ISSUE TITLE
Sidecar injection: value istio-init image is broken if proxy.image is set to an image url

### ISSUE THREAD

**Issue by Smeb** [istio/istio#47911]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In our cluster we wanted to test the proxy for a recent build of istio. To do that, we set `proxy.image` in our mesh to the following:

```yaml
proxy:
  image: <hub>/proxyv2:1.19-alpha.e8caf6b026de0c38adb14fd9cb607f1f5b4df5d3-distroless
```

This caused injection to break pods, because the init pod had the following image:
```yaml
  image: <hub>/<hub>/proxyv2:1.19-alpha.e8caf6b026de0c38adb14fd9cb607f1f5b4df5d3-distroless:1.19.4
```

The reason for this is issue is that if `proxy.image` is set, and `proxy_init.image` is not set, then when `.ProxyImage` is rendered, the function generating the image url will use `proxy.image` as the value _instead_ of the default value of `proxyv2`.

This only happens for `proxy_init` because the check in the default template is if `proxy_init.image` contains `/`, then it's used, otherwise `.ProxyImage` is called. For the actual proxy, the check is on `proxy.image`. (proxy_init can depend on proxy.image).

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.19.4
data plane version: 1.19-alpha.e8caf6b026de0c38adb14fd9cb607f1f5b4df5d3 (5 proxies), 1.19.4 (1 proxies)
```

**Comment by zirain** [comment]
will `sidecar.istio.io/proxyImage` annotation help you?

**Comment by Smeb** [comment]
That would avoid this issue - but this is more about the fact that if `sidecar.istio.io/proxyImage` / `proxy_init.image` are unset, then it's possible to run into this case where the image URL built by `ProxyImage` is wrong.

- I opened a PR [here](https://github.com/istio/istio/pull/47912) which addresses this.
