### ISSUE TITLE
METRIC_ROTATION_INTERVAL doesn't work

### ISSUE THREAD

**Issue by zaitsevpavel** [istio/istio#47924]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi!
We used Istio (v1.16) deployed as Helm chart in Kubernetes cluster (v1.25).
Then we upgraded Istio charts to v.1.18.5 (using official upgrade docs) as well as part of our microservices to apply config from 1.18.

Since we faced continuously increasing memory consumption of istio-proxy sidecar, we tried to apply `METRIC_ROTATION_INTERVAL: 2m` (https://github.com/istio/istio/pull/44995) parameter to rotate old metric samples, but the parameter doesn't work for us.

### Version

```Text
❯ istioctl version
client version: 1.19.0
control plane version: 1.18.5
data plane version: 1.16.0 (5 proxies), 1.16.7 (25 proxies), 1.18.5 (107 proxies)

❯ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.25.15-eks-4f4795d

❯ helm version --short
v3.11.2+g912ebc1
```

### Additional Information

istiod values.yaml:
```
<...>
meshConfig:
  <...>
  defaultConfig:
    <...>
    proxyMetadata:
      METRIC_ROTATION_INTERVAL: 2m
      METRIC_GRACEFUL_DELETION_INTERVAL: 2m
```

kubectl describe <pod_name>:
```
<...>
Containers:
  istio-proxy:
    <...>
    Image:         docker.io/istio/proxyv2:1.18.5
    Image ID:      docker.io/istio/proxyv2@sha256:7d78fe2dec9ba5000f5efb732bc8aa4467e2996540d4a129459993968094f940
    <...>
    Environment:
      <...>
      PROXY_CONFIG:                       {"proxyMetadata":{"METRIC_GRACEFUL_DELETION_INTERVAL":"2m","METRIC_ROTATION_INTERVAL":"2m"},"extraStatTags":["request_uri","url_path","response_code_details","method","host","url_pattern"],"terminationDrainDuration":"30s","proxyStatsMatcher":{"inclusionRegexps":["^istio_requests_total$","^istio_request_duration_milliseconds_bucket$"]},"holdApplicationUntilProxyStarts":true}
      <...>
      METRIC_GRACEFUL_DELETION_INTERVAL:  2m
      METRIC_ROTATION_INTERVAL:           2m
<...>
```

For testing I made a request to non-existing endpoint of the application (pod runs with istio-proxy), waited for 5 mins and still can see the metric sample `/testing_endpoint_1`:
```
istio-proxy@<dest_pod_name>:/$ curl 'localhost:15000/stats/prometheus' | grep -i testing_endpoint
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0istio_requests_total{reporter="destination",source_canonical_service="<source_pod_name>",source_workload_namespace="<source_pod_name>-testing",source_app="<source_pod_name>",destination_workload_namespace="<dest_pod_name>-testing",destination_app="<dest_pod_name>",destination_service="<dest_pod_name>-service-testing.<dest_pod_name>-testing.svc.cluster.local",destination_canonical_service="<dest_pod_name>",response_code="403",response_flags="-",method="GET",request_uri="unknown",response_code_details="via_upstream",url_path="/testing_endpoint_1",url_pattern="unknown"} 6
```

Also memory consumption, samples count of the istio-proxy container are growing.
```
istio-proxy@<dest_pod_name>:/$ curl 'localhost:15000/stats/prometheus' | cut -d'{' -f1 | sort | uniq -c | grep requests_total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  387k    0  387k    0     0   121M      0 --:--:-- --:--:-- --:--:--  126M
      1 # TYPE istio_requests_total counter
     49 istio_requests_total
```

A few moments later:
```
istio-proxy@<dest_pod_name>:/$ curl 'localhost:15000/stats/prometheus' | cut -d'{' -f1 | sort | uniq -c | grep requests_total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  449k    0  449k    0     0   123M      0 --:--:-- --:--:-- --:--:--  146M
      1 # TYPE istio_requests_total counter
     61 istio_requests_total
```

**Comment by zirain** [comment]
it's a pilot flag, not pilot-agent.

**Comment by zirain** [comment]
demo iop looks like:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      env:
        METRIC_ROTATION_INTERVAL: 1m
        METRIC_GRACEFUL_DELETION_INTERVAL: 1m
```

**Comment by zaitsevpavel** [comment]
Thank you for the reply!
Initially I added the envs to pilot-agent envs because it documented as pilot-agent envs:
https://istio.io/latest/docs/reference/commands/pilot-agent/

Tried to add the envs to pilot section of istiod values.yaml then, same result, no rotation.
I also restarted a test application and the istiod deployment pods.
```
pilot:
  <...>
  env:
    METRIC_GRACEFUL_DELETION_INTERVAL: 10s
    METRIC_ROTATION_INTERVAL: 10s
```
Also I see the envs in pilot-discovery container envs of the istiod deployment.
```
  Containers:
   discovery:
    Image:       docker.io/istio/pilot:1.18.5
    <...>
    Environment:
      <...>
      METRIC_GRACEFUL_DELETION_INTERVAL:            10s
      METRIC_ROTATION_INTERVAL:                     10s
```

**Comment by zirain** [comment]
> Initially I added the envs to pilot-agent envs because it documented as pilot-agent envs:
https://istio.io/latest/docs/reference/commands/pilot-agent/
something must be wrong

how did you config stats? EnvoyFilter or Telemetry API, iirc, Telemetry API is the right way.

**Comment by zaitsevpavel** [comment]
@zirain Thank you for your help!

After migrating from Telemetry V2 (EnvoyFilter) to the new TelemetryApi the parameter works as expected.
A few comments:
- As we already discussed, the parameter is described as pilot-agent env, not pilot env;
- There are no any comments in docs about migrating to Telemetry API to make the parameter work;
- It would be great to have a tool for migrating from EnvoyFilters to TelemetryAPI.

**Comment by zirain** [comment]
> As we already discussed, the parameter is described as pilot-agent env, not pilot env

https://github.com/istio/istio/issues/47925

> There are no any comments in docs about migrating to Telemetry API to make the parameter work;

because it's an alpha feature, we're supper happy to hear your feedback.

> It would be great to have a tool for migrating from EnvoyFilters to TelemetryAPI.

it's hard, I recall there're some doc in istio.io.

**Comment by suxiaoxiaomm** [comment]
@zaitsevpavel 
Hi, we are also struggling with increasing memory as istio-proxy sidecar. Does this parameter can really help on this issue? Have you done some test?

If yes, it would be great! I would want to apply to my project too.

**Comment by zaitsevpavel** [comment]
> @zaitsevpavel Hi, we are also struggling with increasing memory as istio-proxy sidecar. Does this parameter can really help on this issue? Have you done some test?
> 
> If yes, it would be great! I would want to apply to my project too.

Yes, the parameter helped us to keep the memory usage of istio-proxy sidecars stable by rotating old samples of metrics.
The following configuration of helm chart values works **only** with the new Telemetry API, so we had to migrate to the new api from using Envoy filters.
```
pilot:
<...>
  env:
    METRIC_GRACEFUL_DELETION_INTERVAL: "2m"
    METRIC_ROTATION_INTERVAL: "2m"
<...>
```

**Comment by suxiaoxiaomm** [comment]
@zaitsevpavel  
Great! Thank you so much for sharing the information!

**Comment by zirain** [comment]
close this, feel free to reopen.
