### ISSUE TITLE
istio.io/istio/tests/e2e/tests/bookinfo TestVMExtendsIstio failed two days in a row

### ISSUE THREAD

**Issue by hklai** [istio/istio#4794]
Today
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/502/daily-e2e-cluster_wide-auth/436/

Yesterday
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/501/daily-e2e-cluster_wide-auth/435/

They are blocking daily releases.

**Comment by chxchx** [comment]
I took a look on the log. The Mason successfully assigned a VM, all sequence of steps or setting up the VM successfully finished, and istallation of istio on the VM using debian pkg also succeeded. It was the final test of asserting connectivity between VM and the service mesh that has failed. I believe that it is not an infrastructure issue that was causing such failure.

TestVMExtendsIstio are failing on master as part of the postsubmit as of right now https://k8s-testgrid.appspot.com/istio#e2e-suite-rbac-auth, so the release failure is just a reflection of this. Testgrid shows that the last passing on master was at `e51254e9a` and the first failure is at `004458de0`, and there are three commits in between.

![screenshot from 2018-04-06 12-42-11](https://user-images.githubusercontent.com/11745975/38440985-15ac72e2-3998-11e8-904a-641ba38a38ec.png)

**Comment by hklai** [comment]
@rshriram could you help with fixing this test?

From https://github.com/istio/istio/compare/e51254e9a...004458de0, it looks like one of the commits broke the test.

**Comment by costinm** [comment]
Nate: can you take a look ? I suspect the iptables change, the failure is on VM->service communication, likely the capture. It broke on Apr 3, about the time of last change to iptables.

**Comment by costinm** [comment]
How can someone reproduce and debug this test ?

**Comment by nmittler** [comment]
The iptables change passed all presubmit tests .... was this not part of it?

**Comment by hklai** [comment]
TestVMExtendsIstio did pass for #3562.

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3562/e2e-suite-rbac-auth/1299/

**Comment by costinm** [comment]
Not sure if it was part of presubmit or how reliable it is, but Shriram's PRs seem to be specific to build and alpha3.

**Comment by costinm** [comment]
Looked at the log: it seems the test is only checking if it can connect to the pilot internal load balancer.
All install was ok, envoy doesn't seem to be involved - yet the VM can't connect. AFAIK this is not supposed to be intercepted by iptables - so:
- either iptables is capturing more than the CIDR
- or some other environment issue on how the machine/firewalls are setup.

**Comment by nmittler** [comment]
@costinm the new iptables script echos the lines that it executes, so you can take a look at that to verify it's doing the right thing.

**Comment by costinm** [comment]
That's not captured by any log - it goes into systemd journals (probably).

**Comment by hklai** [comment]
No longer release blocking since the test was disabled.

Will need to fix it after 0.8.

**Comment by smawson** [comment]
Peter can you look at reenabling this test and seeing if we can get it non-flakey?

**Comment by smawson** [comment]
Ping Peter, can you take a look?

**Comment by bianpengyuan** [comment]
@smawson Ack. Looking into it now.

**Comment by bianpengyuan** [comment]
The test is passing in my test environment. We should try to re-enable the test.

**Comment by bianpengyuan** [comment]
PR is checking in, I am going to observe how it runs on prow and debug as necessary.

**Comment by diemtvu** [comment]
Fixed / obsolete.

From what I can see, this test is no [longer flakiness](https://testgrid.k8s.io/istio-release#e2e-bookinfoTests&width=10&sort-by-flakiness=)

![image](https://user-images.githubusercontent.com/25132401/59874001-16c32580-9352-11e9-9573-5eebd10961c2.png)

The whole pipeline still fails once in a while, but due to permission, [e.g](https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/release-e2e-bookinfoTests/847)
```
/usr/local/bin/entrypoint: line 14: /home/prow/go/src/github.com/istio-releases/pipeline/scripts/build_test_presubmit.sh: Permission denied
```

**Comment by incfly** [comment]
I think the test is not running currently... It's still skipping

I don't think we fixed the underlying problem, the real fix requires ssh user to be set differently in the mesh expansion setup script....

Having that said, it might not worth fixing this particular issue, people are saying we should use kind stuff to run mesh expansion test...

**Comment by diemtvu** [comment]
I'm confused. Do you mean the test is disabled in code. And what is showing in the dashboard is just a do-nothing test?

**Comment by incfly** [comment]
Yeah, that's what I meant. Test should be disabled since last time I
touched on this.
