### ISSUE TITLE
Does istio still not support stateful deployment?

### ISSUE THREAD

**Issue by AbelHugh** [istio/istio#47941]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a kubernetes cluster, deployed the latest istio version, and then used the stateful mysql example on the kubernetes official website.

url: https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/

deploy_file: [k8s_official.zip](https://github.com/istio/istio/files/13407062/k8s_official.zip)

![image](https://github.com/istio/istio/assets/71317399/aff2d411-a137-4a8e-9684-78ac729ac91f)

As shown below, If not use istio, everything is normal, all three containers can be created correctly. but when I use istio, the stateful deployment of all 3 mysql pods can not complete.
when starting to deploy the second mysql container mysql-1, it will always be stuck at 'Init:1/3 '.
![image](https://github.com/istio/istio/assets/71317399/1e99457e-20ce-4a1c-a027-1c1d3f95e910)

### Version

```Text
istio version: 1.19.4
kubernetes version: 1.25.9
```

**Comment by hzxuzhonghu** [comment]
What's the error? Is that the sidecar not ready before the MySQL instance talk with each other?

**Comment by hzxuzhonghu** [comment]
IF so try holdApplicationUntilProxyStarts  https://github.com/istio/istio/issues/38800

**Comment by AbelHugh** [comment]
> What's the error? Is that the sidecar not ready before the MySQL instance talk with each other?

Do you need to check any logs? It is normal for deployment type applications to use istio, only statefulset is abnormal.

**Comment by AbelHugh** [comment]
> IF so try holdApplicationUntilProxyStarts #38800

I don't think this helps, as you can see from the description, it actually stops at the initialization container clone-mysql.
[describe.txt](https://github.com/istio/istio/files/13407958/describe.txt)

**Comment by AbelHugh** [comment]
> IF so try holdApplicationUntilProxyStarts #38800

I have re-added the problem description, please help me take a look.

**Comment by AbelHugh** [comment]
> What's the error? Is that the sidecar not ready before the MySQL instance talk with each other?

I have re-added the problem description, please help me take a look.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers ?

**Comment by linsun** [comment]
Also check https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols, which has mysql port in there
