### ISSUE TITLE
Default to Delta XDS in Istio 1.22

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#47949]
I propose we default to Delta XDS in Istio 1.21 (with, of course, an opt-out).

Delta XDS is, assuming we don't have any bugs, strictly better than SotW in basically every aspect (perhaps not simplicity... but otherwise). We have been testing Delta and devloping on it for 5+ releases. IMO next release is as good as any to turn it on.

I think this basically just needs a PR to flip the flag, switching the test to have a single sotw workload instead of a single delta one (as rest will all be delta), a release note + upgrade note (even though its compatible, its a big change so good to give it proper notice).

Additionally, in the future any changes to delta (to make it more incremental) probably should be behind a new flag like DELTA_XDS_EXPERIMENTAL, so we can graduate optimizations from new -> experimental -> GA; otherwise any such change is fairly risky.

cc @kyessenov @keithmattix @ramaraochavali @hzxuzhonghu

**Comment by kyessenov** [comment]
Agree. There are some bugs (https://github.com/envoyproxy/envoy/issues/30379#issuecomment-1786311451) but they are easy to fix upstream. Do we expect to turn-off SotW?

**Comment by howardjohn** [comment]
I would make the change tell clients to use delta. We will still have some SotW around for other clients (debug tools, grpc, etc) and for opt-out cases. Long term we should start reducing all SotW usage, and possibly get to disabling, but IMO we get most of the value from just changing the envoy client defaults. The code to support SotW isn't too onerous to keep around for a while

**Comment by keithmattix** [comment]
This seems reasonable with some of the exceptions you noted in your comment, specifically for debugging tools

**Comment by hzxuzhonghu** [comment]
I'd suggest turning it on for all the integration test first, but TBH still concerned it will be breaking users with it on in release.

**Comment by linsun** [comment]
Update title to istio 1.22 to avoid confusion, pls correct if i am wrong here
