### ISSUE TITLE
CNI uds logging has invalid timestamps

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#47965]
https://github.com/istio/istio/blob/bd9e52d05817b03b9811a761a818b2e76d356018/cni/pkg/log/uds.go#L120

Here we lose the original timestamp in the logs we get over UDS, which gives confusing results

**Comment by sword-jin** [comment]
I’d like to fix this problem, will submit a PR. Please assign this ticket to me. @howardjohn

**Comment by sword-jin** [comment]
@howardjohn I think this ticket could be closed

**Comment by howardjohn** [comment]
Thanks!
