### ISSUE TITLE
Documentation links on istiod helm chart values are not valid anymore

### ISSUE THREAD

**Issue by justinas-b** [istio/istio#48033]
Documentation links on istiod helm chart values are not valid anymore for `chartsidecarInjectorWebhook`:
https://github.com/istio/istio/blob/d841018fa8b91f8542a13d0b50f4ef1a361573ef/manifests/charts/istio-control/istio-discovery/values.yaml#L91

https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#more-control-adding-exceptions page does not contain any information about `neverInjectSelector` and `alwaysInjectSelector`

**Comment by AurimasNav** [comment]
looking for exact same documentation
