### ISSUE TITLE
followup on prom stats compression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48051]
https://github.com/istio/istio/pull/47997#discussion_r1402384418

We should make it an environment variable. IMO this will not be a permanent API. We should:

1. Turn off by default with opt in
2. Turn on by default with opt-out
3. Remove opt-out, if no one needs it

If we are really confident I am ok with skipping (1).

_Originally posted by @howardjohn in https://github.com/istio/istio/pull/47997#discussion_r1402384418_

**Comment by howardjohn** [comment]
Some insight from @Stono 

> i broadly don’t encourage compression within a local network.  But it depends on your lens.  I found no compression to be more performant than compression, eg it was faster to send data uncompressed over the wire than it was to spend time zipping and unzipping.  More so in microservices; a reasonable amount of cpu time would get spent compressing and uncompressing each hop.  However we personally also offset a lot of our zonal costs with locality routing.
> From a prometheus perspective; performance doesn’t matter.  The consideration here though would be adding additional CPU load onto the proxies.  You’ll increase data plane CPU usage to save a few £ in cross-zone egress.  Because of that my gut would be that it shouldn’t be the default; as we should optimise for least-load on the data plane, rather than cost optimisations.
> Although i suppose you could argue just adding the filter to response to accept-encoding is the toggle, and it’s down to the prometheus operator to control if it requests gzipped content or not
> Just might catch people by surprise; not sure what prom does by default, but say it does ask for gzip and istio suddenly starts doing it; you’ll get a bunch of reports of increased CPU usage on the data plane 
> The other reason I probably don't feel that cost too much is I heavily reduce cardinality at the sidecar (removing some high cardinality labels etc) so I'm already shipping less metrics than the default

**Comment by howardjohn** [comment]
In prom, compression was always on until *last week* where it became a config option: https://github.com/prometheus/prometheus/commit/870627fbedb4dbe2a86eeb8c8795b9b2a0abb7f9.

One can assume ~100% of users will have the `accept-encoding: gzip` sent currently. This kind of points to off-by-default, unless we do some testing of the CPU overhead of this

**Comment by zirain** [comment]
TIL, https://github.com/prometheus/prometheus/commit/870627fbedb4dbe2a86eeb8c8795b9b2a0abb7f9 I think this a cost tradeoff between network and cpu, that PR convinced me.

```
Most our scrape jobs use local network, so we don't need compression and we would happily trade some extra network bandwidth in exchange for extra memory.
```

@kaiburjack can you share more detail about the following scenario, what is `Inter-Zone Egress` traffic?

```
We are currently generating high "Inter-Zone Egress" traffic costs due to the Prometheus scrapes of many pods with many Istio/Envoy metrics and could cut these costs by 1/10th if using gzip compression.
```

if there's no more reason, prefer to (3) or (1).

**Comment by kaiburjack** [comment]
"Inter-zone Egress Traffic" refers to all traffic that originates from a VM/IP in one (availability) zone (AZ) and is destined for another VM/IP in a _different_ AZ. Whenever you run your workloads with a public cloud provider (GCP, AWS, Azure), all of them bill you for traffic that crosses AZs. GCP, our case, bills USD0.01 per Gigabyte of such traffic.
And right now, this is the biggest cost factor in our daily bill statement. Inter-zone egress traffic produced by port 15090 of Istio proxy sidecars with us amasses to ~3 Terabytes per day (for ~300 pods being scraped every 10s) and we are billed around USD35 per day for this invoice item.
This currently is more than what we are billed for the compute capacity (VMs, CPUs, Memory).
So, it was worthwhile for us to reduce the traffic. Currently, we are down to USD0.3 per day only due to using a gzip sidecar proxy that simply gzipps localhost:15090 and provides this under localhost:14090 by means of adding this sidecar as an additional Istio Injection Template.
We are not seeing any additional noticeable CPU or memory being spent due to this and will roll with this now.

I am fine with either setting (opt-in, opt-out). Right now, our "have a separate sidecar providing a gzipped 14090->15090" works great, so we are not dependent on Istio finding a solution quickly for handling opt-in or opt-out.

**Comment by Stono** [comment]
@kaiburjack i'm also on GCP; our egress is about 15% of our CPU+memory costs, i agree it's frustrating.  However what I find interesting is the vast majority of ours is services, not istio.  We're billed around $250/day for inter-zone transfer and that's with over 3000 containers (2000+ running istio), about $10 of that I can associate to istio metrics.  So something feels off there! 

There might be other factors for you to consider?  For example, how often is your prometheus instance scraping?  Have you [turned off metrics you don't need](https://karlstoney.com/federated-prometheus-to-reduce-metric-cardinality/)?  Nailing those also means you don't need as bigger prometheus instance.

**Comment by Stono** [comment]
FYI I wrote a blog on enabling gzip globally on your mesh https://karlstoney.com/compress-your-mesh (prom metrics included)

**Comment by Minh-Ng** [comment]
Following up on https://github.com/istio/istio/pull/47997:

It seems for agent metrics or for those using merged metrics via the agent at 15020 we are still at the mercy of the agent server supporting/not supporting compression.

While kaiburjack's solution of defining a new listener (e.g. 0.0.0.0:14020) on an adjacent port and routing to the corresponding cluster (e.g. 127.0.0.1:15020) will work as an intermediate solution but perhaps we can get support for merged metrics via the agent as well?

**Comment by frittentheke** [comment]
@howardjohn @zirain  do you mind reopening this one?

I just noticed https://github.com/istio/istio/issues/58697 about adding compression support to the pilot-agent when metrics merging is used and realized that the endpoint for the metrics does not even have compression negotiation built-in, but requires the https://istio.io/latest/docs/reference/config/annotations/#SidecarStatsCompression annoations.
For years this some people have noticed the sheer savings potential (https://www.ventx.de/en/blog/istio_compression_metrics/) when compressing the metrics.
See also the slack discussion started by @larhauga https://istio.slack.com/archives/C37A4KAAD/p1767868852835399


But just like your reasons for this issue, to me the current state is way to complex and compression should simply be the default for all metrics. If you look at the two+ years old discussion at Prometheus https://github.com/prometheus/prometheus/pull/13166#issuecomment-1853727824 (shout to @SuperQ), compression is in virtually all cases (modern CPUs and all) free money. Literally. With 90% bandwidth savings this is substantial for people running on hyperscalers with potential traffic costs.

**Comment by frittentheke** [comment]
One more thing on enabling compression by default ... with the capability to disable this per target in Prometheus via `enable_compression` (https://prometheus.io/docs/prometheus/latest/configuration/configuration/), there is still a way for people to not "accept" this is offered by the webservers belonging to Istio (proxy + agent).

**Comment by louiscryan** [comment]
@istio/technical-oversight-committee was discussed in WG meeting so echoing that here.

- We think the goal should be to have simple on/off by default flag. That flag can have a bias towards being 'on' if we believe this is a win in almost all cases. E.g. 'disableMetricsCompression=true|false'. 
- This flag cannot go to on by default without warning users so we need to put something in the 1.29 release notes telling them the default will flip in 1.30
- While many arguments have been made about this being a 'win in all cases' and there is anecdotal evidence for this probably need to see some measurement of this or a more thorough documenting of that evidence to flip the default. Arguments about this being better in node.js (a single threaded runtime) don't hold in our world and the diversity of libraries (ex zip vs zip-ng, ..) used for each algorithm has large effects and varies quite a bit by compute platform.
- gzip is now the least preferred algorithm (zip-ng level 7 is faster than gzip level 1-3) but it seems the prometheus defaults to gzip so we need to know if we can use/prefer/recommend zip
