### ISSUE TITLE
Spurious output from istioctl version -o json

### ISSUE THREAD

**Issue by myshkin5** [istio/istio#48073]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Running from the head of the `release-1.18` branch (later than the 1.18.5 tag) and noticed some extra output from the command `istioctl version -o json`:
```
$ istioctl version -o json
2023-11-28T21:50:08.312053Z	info	tf	port forward completed without error
{
  "clientVersion": {
...
```

The non-json output is causing some integrations to fail.

### Version

```Text
$ istioctl version
2023-11-28T23:21:47.244804Z	info	tf	port forward completed without error
2023-11-28T23:21:47.643070Z	info	tf	port forward completed without error
client version: 1.18.5-private
control plane version: 1.18.5-private
data plane version: none
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Additional Information

Istio isn't actually installed yet (just running istioctl locally) so the bug report isn't available.

**Comment by hanxiaop** [comment]
https://github.com/istio/istio/pull/48074#issuecomment-1830945329 is the solution. However, I think we have never used tf logs for istioctl commands, which seems incorrect to me.

**Comment by myshkin5** [comment]
@hanxiaop #48093 replaces #48074. I saw that the logging framework was changed from the master branch to the release-1.18 branch but didn't realize that because of the logging framework change, the issue didn't affect master.

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio/pull/48093.
