### ISSUE TITLE
Istioctl analyzer: Clarify IST0110 and IST0111 for ambient

### ISSUE THREAD

**Issue by birkland** [istio/istio#48105]
It's possible for Analyzer warnings for Sidecar resources (IST0110 and IST0111) to be thrown, even if such resources are created in ambient enabled namespaces that don't have any sidecar-based workloads to select.    

**Describe the feature request**

Either suppress these analysis results when a Sidecar resource appears in an ambient-enabled namespace, or emit a new kind of warning about the use of Sidecar resources that select non-sidecar ambient workloads. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x ] Ambient
[ x ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
We probably need to redesign the analyzers related to policies in the ambient environment. The Sidecar is a special case, and I think we also have errors with policies like telemetry in ambient namespaces.

**Comment by ilrudie** [comment]
I think having an analyze warning which informs users their sidecar resources have no impact in ambient makes sense. That likely also includes suppression of the other warnings/errors wrt sidecar resources as well so potentially this could be split out into 2 different issues.

**Comment by linsun** [comment]
@hanxiaop are you planning to create a design doc for this? I think this could be a beta blocker for UX, thoughts?

**Comment by hanxiaop** [comment]
> @hanxiaop are you planning to create a design doc for this? I think this could be a beta blocker for UX, thoughts?

The issue at https://github.com/istio/istio/issues/48273 which relates to other policies, has been resolved. I think what remains is dealing with the sidecar resource. I don’t think a design document is needed for the analyzer, and I am going to work on this issue this week.

**Comment by hanxiaop** [comment]
> I think having an analyze warning which informs users their sidecar resources have no impact in ambient makes sense. That likely also includes suppression of the other warnings/errors wrt sidecar resources as well so potentially this could be split out into 2 different issues.

This makes sense to me.
