### ISSUE TITLE
Move CRD reading to 'v1' for security APIs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48107]
Currently, in Istio we read the _oldest_ Istio CRD. This means that we can basically never remove the old versions. In order to ever be able to, we need to move to the new versions.

Reading the old version maximizes compatibility, as everyone has the old versions, but not everyone has the new versions. However, this is moot at this point; there is no one running Istio 1.21 without VirtualService v1beta1, for instance (and if they are, they _should break_).

Moving from alpha -> beta may be a wasted effort, though, if we eventually add a v1 anyways. But for security CRDs, moving seems safe. They are already v1, and introduced in 1.17.
Unless a user is running 1.17 CRDs with Istio 1.21, reading from security v1 will have no negative impact. It will, however, enable us to _eventually_ remove the beta versions; this will be done in a distant followup.

**This issue is for discussion; please do not implement until we have agreed to do so.**

---

more info on "removing beta". To make this compat, we would need:
* All user usages to be against v1. Typically this is via YAML, sometimes via client. We can detect usage from some k8s vendor metrics, if they provide us, but otherwise are blind
* All Istio 1p usage to move to v1. If we move to reading v1 in 1.21, this means we will break Istio 1.20 and older. Our official revision skip-level upgrade skew is 2 versions, but in practice users do far more. I wouldn't feel great about removal until ~1.25 or newer, which is a long ways off.

**Comment by howardjohn** [comment]
@whitneygriffith

**Comment by whitneygriffith** [comment]
@howardjohn is this something we can aim to do for ~1.23? As you mentioned, first class support for users to migrate will be available in [k8s 1.30](https://www.kubernetes.dev/resources/release/)

**Comment by howardjohn** [comment]
For just reading the resources we don't need any support. It would only break users who have newer Istiod than CRDs (Istiod that reads v1 but CRDs only have v1beta1) but that doesn't seem like a legitimate deployment use case. We can wait 1 release after to give some buffer just in case.

But reading the new versions (beta networking apis, v1 authz policy) that changed a while back should be close to zero risk. Maybe for the new promotions in 1.22 we wait to read until 1.23.

The k8s 1.30 thing is for _removing_ old versions

**Comment by howardjohn** [comment]
#52419
