### ISSUE TITLE
Traffic loss umbrella epic (503s, 404s and other errors)

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#4810]
Used for grouping purposes

**Comment by bobbytables** [comment]
What's the status on this? We've disabled istio in our clusters due to these bugs.

**Comment by andraxylia** [comment]
We have switched to Envoy v2 ADS and there are still issues, investigating.

**Comment by rshriram** [comment]
@smawson why move to P1 ? Issues in this epic are in P0 still.

**Comment by jasmine-jaksic** [comment]
@rshriram @andraxylia At ToC last week, we decided not to tag Epics as P0 blockers and instead only add individual issues so they can be tracked/closed easily. Of the 3 open ones, #1038 and #3295 are already on this list, I'm not sure if #1462 is still an issue. If someone can confirm that it is, then we can run it by ToC on Friday.

**Comment by andraxylia** [comment]
@jasmine-jaksic got it, will change the epic to P1.
