### ISSUE TITLE
Testing cert rotation in ztunnel

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#48120]
**Describe the feature request**

brainstorming how to best add some tests around cert rotations with istiod+ztunnel similar to https://github.com/istio/istio/pull/47641

sparked by discussion in https://github.com/istio/ztunnel/pull/730

without supporting some form of PCDS or being able to push something via WDS to signal ztunnel to refresh it's workload certs (after intermediate cert rotation rotation like provided in the [docs](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/#verifying-the-certificates)), ztunnel will only get new certs after the 24hour / 2 refresh interval.

one possible solution is to use a test similar to #47641 , deploy ztunnel with a shortened SECRET_TTL interval as implemented [here](https://github.com/istio/ztunnel/pull/742), and wait for the refresh interval to pass and verify the new intermediate certs are reflected in ztunnel

**Affected product area (please put an X in all that apply)**

[ X ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by GregHanson** [comment]
@hzxuzhonghu any thoughts?

**Comment by hzxuzhonghu** [comment]
If it is for workload cert rotate, we donot need pcds. Just wait the cert ttl passed, and check new cert signed and the traffic is not influenced during this procedure.

PCDS is used to support root cert rotation.

**Comment by GregHanson** [comment]
intermediate cert rotation integration test merged in https://github.com/istio/istio/pull/48168.

Does not cover root cert rotation in ztunnel

**Comment by keithmattix** [comment]
Not stale
