### ISSUE TITLE
Ambient Mesh and unenforceable circuit breakers

### ISSUE THREAD

**Issue by tonya11en** [istio/istio#48121]
I couldn't find any mention of how circuit breakers and overload protection will be handled in the ambient mesh architecture, so please close if it's already been discussed and settled. This issue is just meant to put forward some ideas I had on the matter and start a discussion.

### The problem
The removal of sidecars in ambient mesh makes it such that circuit breakers are unenforceable. When configuring circuit breakers in the sidecar architecture, there is a single proxy receiving traffic destined to a pod. This means that the proxy can enforce an upper-bound on the number of active requests/retries/connections, since all requests must pass through it. 

With the ambient mesh architecture, requests can come from any number of waypoint proxies, making enforcement of these upper-bounds impossible. Waypoint proxies have no way of enforcing circuit breakers, since the decisions on whether to forward or reject the request/retry/etc. is not centralized anymore. This situation warrants overload protection mechanisms that do not require centralized decision-making.

### Alternatives to circuit breakers

**[Retry budgets](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-field-config-cluster-v3-circuitbreakers-thresholds-retry-budget) instead of retry circuit breakers**

Retry budgets enforces an upper-bound on the _percentage_ of active requests that are allowed to be retries. They prevent retry storms by ensuring that traffic can only increase by that amount and does not retry once the threshold has been reached. This way of limiting retries continues to work even if multiple proxies are sending requests/retries to the same host.

**[Admission Control](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/admission_control_filter) instead of max request circuit breakers**

Envoy's admission control filter rejects requests based on the success rate of previous requests in a configurable sliding time window. This method of overload protection does not require any centralized decision-making or state tracking. In addition, it requires minimal tuning compared to circuit breakers.

**No suggestion for connection circuit breakers**

¯\\\_(ツ)\_/¯ 

---

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
The inner implement of waypoint decided that it is impossible to apply circuit breaker on the cluster, because all all the endpoints of `inbound-vip|port|protocol|hostname` point the the same listener `connect_originate`, i am not sure whether the inner listener propagation is treated as a physical connection? @kyessenov

**Comment by kyessenov** [comment]
@hzxuzhonghu Yes, but that's not the actual reason. Waypoints are cattle, you can have more than 1 handling traffic to a single backend. Therefore, the "service owner" policies that are traditionally applied on the inbound chain simply do not make sense in this context. On managed infrastructures, the overload and DDoS protection is usually a distributed service that handles distributed proxies better, than a local enforcement mechanism.

**Comment by linsun** [comment]
Hi @kyessenov and @hzxuzhonghu - what is the conclusion?  Does circuit breaker not make sense in the context for waypoint which runs outside of app pod and don't have a 1 - 1 relationship?

I'm considering this not a beta blocker.
