### ISSUE TITLE
Envoy startup stuck by warming cluster

### ISSUE THREAD

**Issue by freedomljc** [istio/istio#48135]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to upgrade istio to the version 1.20.0, noticed the envoy proxy gets stuck as `PRE_INITIALIZING`, seems related to there's one warming cluster.
The symptom is similar to https://github.com/istio/istio/issues/38709#issuecomment-1132683506

### Version

```Text
1.20
```

### Additional Information

I modified envoy bootstrap to add another static envoy cluster A, whose eds_service_name is same to one istio-generated envoy cluster B. Afterwards, cluster B gets into warming state based on envoy admin config_dump endpoint, and envoy gets stuck as `PRE_INITIALIZING`.

From envoy logs: 
1. envoy sends eds request [A] to istiod due to static cluster A, and able to get the EDS response.
2. envoy sends another eds request [A, ....] to istiod due to dynamic cluster B. There's no hosts in eds response for eds cluster A, thus leading envoy cluster B in warming state.

From istiod logs:
```
2023-12-01T23:48:02.884816Z info  ads ADS: new connection for node:xxx
2023-12-01T23:48:02.885006Z info  ads EDS: PUSH request for node:xxx resources:1 size:621B empty:0 cached:0/1
2023-12-01T23:48:02.886856Z info  ads CDS: PUSH request for node:xxx resources:13 size:12.0kB cached:6/10
2023-12-01T23:48:02.886888Z info  ads ADS:EDS: FORCE RESPONSE xxx for warming.
2023-12-01T23:48:02.886979Z info  ads EDS: PUSH request for node:xxx resources:1 size:621B empty:0 cached:0/1
2023-12-01T23:48:02.895918Z info  ads EDS: PUSH request for node:xxx resources:8 size:4.1kB empty:1 cached:5/8 filtered:1
```

**Comment by freedomljc** [comment]
It's related to https://github.com/istio/istio/pull/44590. It works in the old version 1.14 as [`PILOT_PARTIAL_FULL_PUSHES` is disabled by default](https://github.com/istio/istio/pull/39119). 
The fundamental cause is related to EDS responses cannot be reused across different envoy clusters. https://github.com/envoyproxy/envoy/pull/28877 tried to address the issue for ADS, but it won't help for istio case as `initial_fetch_timeout ` is set as 0s in istio. 

I wonder whether we can bring back `PILOT_PARTIAL_FULL_PUSHES` feature flag, until the EDS responses sharing issue can be addressed in envoy side. Btw, there's a more fundamental issue in envoy side: https://github.com/envoyproxy/envoy/issues/13009. 


cc @ramanujadasu, @howardjohn since there're some discussions in [original issue](https://github.com/istio/istio/issues/38709), and I wonder whether you noticed the issue happened again.

**Comment by howardjohn** [comment]
If you are using custom bootstrap cluster seems you are in very unexpected territory. If we can make it work without much impact I don't mind ,but its not really a supported usage of Istio

**Comment by freedomljc** [comment]
@howardjohn  I just opened a pr https://github.com/istio/istio/pull/48314 to bring back the flag, PTAL.

The change is related to zone-aware routing. Some benefits of bringing zone-aware routing into istio are explained in https://github.com/istio/istio/issues/48173. If envisioning zone-aware routing can be a good extension to istio localicty lb, we can make it work without envoy bootstrap cluster by re-implementing zone-aware routing logic in istiod.
