### ISSUE TITLE
How to log Destination Cluster/Source Cluster in Envoy's log

### ISSUE THREAD

**Issue by j2gg0s** [istio/istio#48148]
[Istio standard metrics](https://istio.io/latest/docs/reference/config/metrics/) has two labels:
- Destination Cluster
- Source Cluster

Can I access this information in Envoy's logs?
Envoy Log: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by zirain** [comment]
you can try with `"%CEL(filter_state['wasm.upstream_peer'].cluster_id)%"` in istio 1.20, I cannot recall the first supported version.

**Comment by j2gg0s** [comment]
> you can try with `"%CEL(filter_state['wasm.upstream_peer'].cluster_id)%"` in istio 1.20, I cannot recall the first supported version.

@zirain

In the following example:
```shell
cat l.json | jq '.[].filterChains[-1].filters[-1].typedConfig.httpFilters[].name'
"istio.metadata_exchange"
"envoy.filters.http.grpc_stats"
"istio.alpn"
"envoy.filters.http.fault"
"envoy.filters.http.cors"
"istio.stats"
"envoy.filters.http.router"
```

- filter istio.metadata_exchange set FILTER_STATE ?
- With Envoy's Document, i think we should access metadata by `%FILTER_STATE()%`
with `"%FILTER_STATE(wasm.upstream_peer::)%"`, i got 
```json
"cluster_id": {
    "@type": "type.googleapis.com/google.protobuf.BytesValue",
    "value": "IAAAAAAAGgAsACgAJAAMACAAHAAAABgAFAAIABAABAAaAAAAKAAAACwAAAAwAAAAWAAAAHAAAAAQAwAAsAIAABQDAABUAAAA1AIAAAEAAAC4AgAAAQAAAFgAAAAKAAAAJAEAAOQAAACwAQAAFAIAAHgBAABAAgAAjAAAAEgAAADMAQAAKAEAAAsAAABjbi1zaGFuZ2hhaQAGAAAAdGVuc29yAAAEAAAAdGVzdAAAAAAPAAAAcml2ZXItd2F0ZXJzaGVkABj+//8UAAAABAAAAAYAAABsYXRlc3QAACMAAABzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1yZXZpc2lvbgBY/v//HAAAAAQAAAAPAAAAcml2ZXItd2F0ZXJzaGVkAB8AAABzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1uYW1lAJz+//8cAAAABAAAAA8AAAByaXZlci13YXRlcnNoZWQAFgAAAGFwcC5rdWJlcm5ldGVzLmlvL25hbWUAANj+//8cAAAABAAAAA8AAAByaXZlci13YXRlcnNoZWQAAwAAAGFwcAAA////GAAAAAQAAAALAAAAY24tc2hhbmdoYWkAGQAAAHRvcG9sb2d5LmlzdGlvLmlvL25ldHdvcmsAAAA8////FAAAAAQAAAAHAAAAZGVmYXVsdAARAAAAZWNoby50ZWNoL3ZlcnNpb24AAABs////FAAAAAQAAAAHAAAAZW5hYmxlZAAUAAAAZWNoby50ZWNoL2ltLWRlZmF1bHQAAAAAoP///xQAAAAEAAAABAAAAHRydWUAAAAAFwAAAHNpZGVjYXIuaXN0aW8uaW8vaW5qZWN0ANT///8UAAAABAAAAAYAAAB0ZW5zb3IAAA4AAABlY2hvLnRlY2gvdGVhbQAACAAMAAQACAAIAAAAFAAAAAQAAAAFAAAAaXN0aW8AAAAZAAAAc2VjdXJpdHkuaXN0aW8uaW8vdGxzTW9kZQAAABcAAAByaXZlci13YXRlcnNoZWQtZGVmYXVsdAAOAAAAMTcyLjIwLjEwMC4xNTQAACcAAAByaXZlci13YXRlcnNoZWQtZGVmYXVsdC1mZjU5ZDg1YzgtdHNobDUABgAAADEuMjAuMAAATwAAAGt1YmVybmV0ZXM6Ly9hcGlzL2FwcHMvdjEvbmFtZXNwYWNlcy90ZW5zb3IvZGVwbG95bWVudHMvcml2ZXItd2F0ZXJzaGVkLWRlZmF1bHQA"
  }
```
- Is there any way to parse value?
- What does CEL mean?

**Comment by zirain** [comment]
CEL is an envoy accesslog formatter, checkout the doc: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/cel/v3/cel.proto#extensions-formatter-cel-v3-cel

**Comment by zirain** [comment]
FILTER_STATE is encoded in flatbuffer, which is difficult for humans to read.

**Comment by j2gg0s** [comment]
> CEL is an envoy accesslog formatter, checkout the doc: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/cel/v3/cel.proto#extensions-formatter-cel-v3-cel


some information to others who need it
- formatter-cel can be used in [SubstitutionFormatString](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/substitution_format_string.proto#envoy-v3-api-msg-config-core-v3-substitutionformatstring) 
- [FileAccessLog](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/file/v3/file.proto#extension-envoy-access-loggers-file) does not use SubstitutionFormatString
- [StdoutAccessLog](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/stream/v3/stream.proto#extension-envoy-access-loggers-stdout) use SubstitutionFormatString

So, if i want to use cel expresion in log, i have to use StdoutAccessLog replace FileAccessLog.

**Comment by zirain** [comment]
> FileAccessLog does not use SubstitutionFormatString

I don't think this's right.

**Comment by j2gg0s** [comment]
> > FileAccessLog does not use SubstitutionFormatString
> 
> I don't think this's right, following configuration is valid.
> 
> ```yaml
> - name: envoy.access_loggers.file
>           typedConfig:
>             '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
>             logFormat:
>               formatters:
>               - name: envoy.formatter.cel
>                 typedConfig:
>                   '@type': type.googleapis.com/envoy.extensions.formatter.cel.v3.Cel
>               textFormatSource:
>                 inlineString: |
>                   [%START_TIME%] %CEL(response.grpc_status)% "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
>             path: /dev/stdout
> ```

Yes, you are right
