### ISSUE TITLE
issue using helm install on version 0.7.1

### ISSUE THREAD

**Issue by renperez** [istio/istio#4814]
I download the release 0.7.1 and I am getting this error when enabling sidecar inside values.yaml
sidecar-injector:
  enabled: true
  serviceAccountName: default # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
Error: render error in "istio/charts/sidecar-injector/templates/deployment.yaml": template: istio/charts/sidecar-injector/templates/deployment.yaml:6:21: executing "istio/charts/sidecar-injector/templates/deployment.yaml" at <{{template "sidecar-...>: template "sidecar-injector.name" not defined

**Comment by renperez** [comment]
Getting this error without enabling sidecar:
Error: render error in "istio/charts/security/templates/serviceaccount.yaml": template: istio/charts/security/templates/serviceaccount.yaml:6:21: executing "istio/charts/security/templates/serviceaccount.yaml" at <{{template "security...>: template "security.name" not defined

**Comment by renperez** [comment]
@sdake thanks for the info. also FYI, cloning master and running helm install is also broken right now.

**Comment by renperez** [comment]
@linsun i decided to just use 0.5 release and now i am getting this error.
Error: error unpacking initializer in istio: chart metadata (Chart.yaml) missing

**Comment by renperez** [comment]
is there a release version that actually works?

**Comment by linsun** [comment]
sorry no release ever worked with helm.  0.7.1 is the closes with the workaround in  #4701

**Comment by renperez** [comment]
@sdake were you able to test helm on master branch?

**Comment by linsun** [comment]
no response after 20 days, i believe this is fixed in master and i validated it yesterday.  we also have a helm automated e2e test now as part of presubmit of a PR.
