### ISSUE TITLE
TestTraffic/consistent-hash/http_cookie_with_ttlb  flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48156]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/48141/integ-pilot_istio/1731576806206607360

**Comment by hzxuzhonghu** [comment]
@ramaraochavali not sure if this is from #47778

**Comment by ramaraochavali** [comment]
It is not from the that PR. That PR just added few log lines. But interestingly those log lines are not coming so `PropagateResponse` is not being called
