### ISSUE TITLE
SidecarScope may return unexpected service

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48169]
In sidecar scope, we use[ `servicesByHostname`](https://github.com/istio/istio/blob/master/pilot/pkg/model/sidecar.go#L124) to store services by hostname. And this is to speed up service acquiring. 

But in some case, different serviceentry can produce services with same host name. 
In this case, user could get unexpected result, sometimes the result may flip-flop and this makes istio unstable.

**Comment by keithmattix** [comment]
Is this #48055 or another issue?

**Comment by hzxuzhonghu** [comment]
Another issue, could be critical bug

**Comment by hzxuzhonghu** [comment]
flip-flop maybe be not correct, i mean during dynamic service creation/deletion, the xds generated for a particular service could vary.

**Comment by hzxuzhonghu** [comment]
Fixed
