### ISSUE TITLE
Add the support on Envoy zone aware routing

### ISSUE THREAD

**Issue by freedomljc** [istio/istio#48173]
Currently, istio supports [locality weight load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight) by explicitly specifying the weight of each zone. In normal case, we'd like to make the traffic in each zone balanced and set equal weight for each zone. However, if host distribution in each zone isn't proportionally distributed in either downstream or upstream, it would cause imbalanced traffic.

To add the support of [zone aware routing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware), there're a few steps needed to make:

1. Add the option of specifying [zone_aware_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-locality-weighted-lb-config) in the CDS response, currently it's hardcoded as [locality_weighted_lb_config](https://github.com/istio/istio/blob/9f827ca9092048b66466bd158671925be00011b8/pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy.go#L221). 
2. Add custom-bootstrap to specify [local_cluster_name in cluster_manager ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-clustermanager), and create one static cluster for local cluster.
3. Create additional serviceentry to generate EDS response for the local cluster, if needed.

When doing the testing, found another subtle xds protocol issue between envoy and istio-proxy in latest istio version 1.20: https://github.com/istio/istio/issues/48135.

I understand it might require developers familiar with how eds cluster name is generated in istio, as it's needed to specify when creating static envoy cluster. However the support of zone-aware-routing would be beneficial for advanced istio users.

Would like to check how istio community think about the direction.

**Comment by hzxuzhonghu** [comment]
We have evaluated envoy zone aware feature when we design istio localictylb, kind of remmber that envoy one is not quite suitable for k8s scenario

**Comment by freedomljc** [comment]
Seems one similar issue had been created before https://github.com/istio/istio/issues/35102, but do not have many followups. let me know whether there're some specific k8s issues you were referencing to.

I had somewhat different experiences regarding zone aware routing vs locality weight load balancing. To appropriately apply locality weight load balancing in complex k8s env, we'll need to adjust the weight automatically based on the zone distribution in downstream and upstream, which requires more complex implementation in envoy control plane side. However, if choosing envoy zone aware routing, envoy would automatically adjust it.

From implementation wise, we can first start with adding the option of specifying [zone_aware_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-locality-weighted-lb-config) in the CDS response backed by the flag. Once it gets enough traction, we can re-implement zone-aware routing logic in istiod side, and remove the need of updating envoy bootstrap due to inconvenience for istio developers.

**Comment by hzxuzhonghu** [comment]
Native envoy zone-aware routing only supports zone affinity, while istio supported region/zone/subzone.

Limitaion: Native envoy zone-aware routing requires envoy startup with [--service-zone](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-service-zone) option which defines the zone for the current host.

**Comment by freedomljc** [comment]
> Native envoy zone-aware routing only supports zone affinity, while istio supported region/zone/subzone.

Good callout. Since the proposal is to add the option of envoy zone-aware routing instead of replacing existing one, I think it would be still valuable, as there're lots of companies who run the infra in a single region but multi-zones.


> Limitaton: Native envoy zone-aware routing requires envoy startup with [--service-zone](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-service-zone) option which defines the zone for the current host.

The `--service-zone` option in envoy startup isn't required for zone-aware routing, as long as the [Bootstrap node](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-field-config-bootstrap-v3-bootstrap-node) message’s [locality.zone](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-locality-zone) field is specified. I have crafted the following custom envoy bootstrap to demonstrate zone-aware routing could work under istio. By sending request to envoy cluster B via the port 9990,  zone-aware routing works as expected for traffic to envoy cluster B. 
```
{
  "cluster_manager": {
    "local_cluster_name": "originating_cluster"
  },
  "static_resources": {
    "clusters": [{
      "name": "originating_cluster",
      "type": "EDS",
      "eds_cluster_config": {
        "eds_config": {
          "ads": {},
          "initial_fetch_timeout": "30s",
          "resource_api_version": "V3"
        },
        "service_name": "$eds_service_name_a"
      },
      "common_lb_config": {
        "zone_aware_lb_config": {}
      }
    },
    {
      "name": "clusterB",
      "type": "EDS",
      "eds_cluster_config": {
        "eds_config": {
          "ads": {},
          "initial_fetch_timeout": "30s",
          "resource_api_version": "V3"
        },
        "service_name": "$eds_service_name_b"
      },
      "common_lb_config": {
        "zone_aware_lb_config": {}
      }
    }],
    "listeners": [{
      "name": "listener_0",
      "address": {
        "socket_address": {
          "address": "0.0.0.0",
          "port_value": 9990
        }
      },
      "filter_chains": [
        {
          "filters": [
            {
              "name": "envoy.http_connection_manager",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                "stat_prefix": "ingress_http",
                "codec_type": "AUTO",
                "route_config": {
                  "name": "local_route",
                  "virtual_hosts": [
                    {
                      "name": "local_service",
                      "domains": [
                        "*"
                      ],
                      "routes": [
                        {
                          "match": {
                            "prefix": "/"
                          },
                          "route": {
                            "cluster": "clusterB",
                            "timeout": "5s"
                          }
                        }
                      ]
                    }
                  ]
                },
                "http_filters": [
                  {
                    "name": "envoy.router",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                    }
                  }
                ]
              }
            }
          ]
        }
      ],
    }]
  },
  "layered_runtime": {
      "layers": [{
          "name": "static_layer_custom",
          "static_layer": {
              "upstream.zone_routing.enabled": %d,
              "upstream.zone_routing.min_cluster_size": %d
          }
      }]
  }
}
```

Note `"$eds_service_name_a"` and `"$eds_service_name_b"` are needed to match the istio-generated the eds service names, so that envoy can get the eds response for them. However, In practice we do not want to keep clusterB and listener_0 in the bootstrap, as they should be dynamically configured in istiod;  to support zone-aware routing in istio, we'll need to specify [zone_aware_lb_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-commonlbconfig-locality-weighted-lb-config) in the CDS response for envoy cluster B first.

**Comment by hzxuzhonghu** [comment]
The istio locality load balancing is a superset of envoy. Any other features that zone-aware-routing provide?

**Comment by freedomljc** [comment]
I think what istio locality load balancing has implemented so far is to implement [envoy locality weighted load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight) with [priority levels](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority) (fallback scenario), and it essentially makes envoy control plane (in the case, istiod) to provide locality weights and priority. W.R.T. [the locality weights in istio](https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/distribute/), it requires developers to **explicitly specify the weight for each locality**, which makes it undesired for the case when host locality distribution frequently fluctuates, as it would cause unbalanced traffic in those hosts.

On the other hand, [zone-aware routing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware) is to make envoy data plane **automatically adjust the weight** based on the host locality distribution in originating cluster and upstream cluster.
