### ISSUE TITLE
Could not connect to redis server

### ISSUE THREAD

**Issue by funlake** [istio/istio#4817]
version : istio 0.7.1
platform : kubernete
I have a container running with sidecar istio-proxy,get error 'read tcp 172.20.3.126:34620->192.168.191.147:6379: read: connection reset by peer' when tried to connected to redis server
If i remove istio-proxy out of my deployment,my container just works fine,i have no idea what was going on
Should there any configuration job i needed to do?
Ps : redis server not running on kubernete

**Comment by mandarjog** [comment]
What was the issue, how was it resolved?

**Comment by funlake** [comment]
sorry ,my bad,i did misunderstanding how istio-proxy works.
i solved it by added parameter '--includeIPRanges=x.x.x.x/x' when i injected istio into my pod,:)

**Comment by k-vishwa** [comment]
I'm also getting the same error "Error: Connection reset by peer". Here is the scenraio

redis pods are in a namespace where istio injection is disabled. 
I have another po (say foo) in a different namesapce where istio injection is enabled.

I can able to connect to redis mater using redis-cli, but when I do any operations say read/write it is throwing error.

root@foo-lmnxyz:/# redis-cli -h 10.44.23.12
10.44.23.12:6379> get hi
Error: Connection reset by peer
root@foo-lmnxyz:/# 

Also the mutual tls is disabled for istio.

**Comment by kenske** [comment]
@k-vishwa I'm having the same issue. Did you manage to figure it out?

**Comment by k-vishwa** [comment]
@kenske didn't find any solution yet

**Comment by kenske** [comment]
@k-vishwa I figured it out. I'm running EKS and was trying to connect to an elasticache instance from one of the pods. I was missing a security group rule that allows traffic from the EKS node to the redis instance.
