### ISSUE TITLE
Istiod appears to erroneously generate conflicting inbound listener

### ISSUE THREAD

**Issue by hammadzz** [istio/istio#48228]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

There are two services that result in a conflicting inbound listener error in istiod (discovery container).

**service-a:** an external facing api.
**service-b**: an internal api consumed by service-a. 
**Note:** _only service-a has a virtualservice and destination rule._

The error generated is here:
```
"message": "Conflicting inbound listener:3000. existing: service-b.demo.svc.cluster.local, incoming: service-a.demo.svc.cluster.local"
```

Not sure why only port is listed in the error with no pod ip as I find in other instances of this error reported online.

```
❯ kubectl get services
NAME                      TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service-a                ClusterIP   10.0.5.79         <none>        3000/TCP   3y290d
service-b                ClusterIP   10.0.12.10        <none>        3000/TCP   3y291d

❯ kubectl get ep
NAME                      ENDPOINTS         AGE
service-a                10.12.2.33:3000   3y290d
service-b                10.12.1.23:3000   3y291d

❯ kubectl get virtualservices
NAME            GATEWAYS                           HOSTS                                      AGE
service-a       ["demo/demo-gateway"]   ["api.demo.example.com"]     448d

❯ kubectl get destinationrules
NAME            HOST                                   AGE
service-a       service-a.demo.svc.cluster.local       448d
```

Service definitions:
```
❯ kubectl describe service service-a
Name:              service-a
Namespace:         demo
Labels:            app.kubernetes.io/managed-by=Helm
Annotations:       meta.helm.sh/release-name: service-a
                            meta.helm.sh/release-namespace: demo
Selector:          app=service-a
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.0.5.79
IPs:               10.0.5.79
Port:              http-web-api  3000/TCP
TargetPort:        3000/TCP
Endpoints:         10.12.2.33:3000
Session Affinity:  None
Events:            <none>

❯ kubectl describe service service-b
Name:              service-b
Namespace:         demo
Labels:            app.kubernetes.io/managed-by=Helm
Annotations:       meta.helm.sh/release-name: service-b
                   meta.helm.sh/release-namespace: demo
Selector:          app=service-b
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.0.12.10
IPs:               10.0.12.10
Port:              <unset>  3000/TCP
TargetPort:        3000/TCP
Endpoints:         10.12.1.23:3000
Session Affinity:  None
Events:            <none>
```

Virtual service definitions:
```
❯ kubectl describe virtualservice service-a
Name:         service-a
Namespace:    demo
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: service-a
                        meta.helm.sh/release-namespace: demo
API Version:  networking.istio.io/v1beta1
Kind:         VirtualService
Spec:
  Gateways:
    demo/demo-gateway
  Hosts:
    api.demo.example.com
  Http:
    Match:
      Uri:
        Prefix:  /
    Route:
      Destination:
        Host:  service-a
        Port:
          Number:  3000
Events:            <none>
```

### Version

```Text
❯ istioctl version
client version: 1.17.2
control plane version: 1.19.3
data plane version: 1.19.3 (44 proxies)
❯ kubectl version --short
Client Version: v1.23.5
Server Version: v1.27.7-gke.1088000
WARNING: version difference between client (1.23) and server (1.27) exceeds the supported minor version skew of +/-1
```

**Comment by howardjohn** [comment]
I don't think its erroneous, you have 2 services on the same port. The inbound proxy cannot identify which one to was the target of a given request. Listed as last bullet on https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements

**Comment by howardjohn** [comment]
Note it will mostly work, you just may have incorrect telemetry mostly

**Comment by hammadzz** [comment]
I have missed an important detail. The gateway is only configured for service-a to serve external requests. While service-b is consumed by service-a internally with the kubernetes service hostname of service-b.

**Comment by howardjohn** [comment]
Ah sorry, I missed the selector is different

**Comment by howardjohn** [comment]
Do you have any `Sidecar` resources?

**Comment by hammadzz** [comment]
@howardjohn I have a potential fix based on more info. Looking at the full log entry (it was split into multiple entries), the error is from the proxy container of service-c. This service has port 3000 declared on the pod but no k8s service configured (as it is not needed). It appears this is confusing istio discovery trying to add service-c to the mesh and resulting in this error. In fact the pod should have annotations to prevent side car injection as it is not needed for this service. I have now removed the port definition and will see if this fixes the issue before debugging further.

**Comment by hzxuzhonghu** [comment]
This error happens when at least two services defined for a proxy. Check the all the services with targetport 3000 in the same namespace

**Comment by hammadzz** [comment]
> can you maybe send the output of `istioctl x internal-debug instancesz`? You can send over slack DM if you don't want to share that many details. `istioctl bug-report` may be useful as well

Sent over slack. Removing the port from the pod container did not help. Oddly the error is coming from a pod that has envoy proxy sidecar but no services with port 3000. All other k8s services on port 3000 are paired to a single pod.

**Comment by hammadzz** [comment]
> This error happens when at least two services defined for a proxy. Check the all the services with targetport 3000 in the same namespace

There are multiple services on port 3000 in the namespace but each is linked to an independent set of pods (deployment set). Shouldn't be an issue.

**Comment by howardjohn** [comment]
Almost positive this is https://github.com/istio/istio/issues/45241 based on the instancesz I was sent offline.
