### ISSUE TITLE
Memory leaks caused by MeshWatcher and NetworksWatcher

### ISSUE THREAD

**Issue by Erica177** [istio/istio#48224]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I associate a remote k8s cluster with Istio, I create a new controller through 

```go
// serviceregistry. kube. controller. (* Multicluster). addCluster.
func (m *Multicluster) addCluster(cluster *multicluster.Cluster) (*Controller, *Options, bool, error) {
	...
	kubeRegistry := NewController(client, options)
	...
}
```

After the controller is created, it calls the initDiscoveryHandlers method to initialize the initMeshWatcherHandler. The initMeshWatcherHandler calls a global variable, which is meshWatcher. It references the controller through AddMeshHandler. When I delete the associated k8s cluster, this reference will not be canceled, resulting in the memory occupied by the controller not being reclaimed. 

That is to say, as long as istio does not stop, the memory occupied by the controller referenced by the meshwatcher will never be released.

This phenomenon is particularly evident when the k8s cluster size is large. 

```go
//  ../serviceregistry/kube/controller/discoverycontrollers.go
func (c *Controller) initMeshWatcherHandler(...) {
	meshWatcher.AddMeshHandler(func() {
		...
		for _, nsName := range newSelectedNamespaces {
			// here
			c.queue.Push(func() error {
				c.handleSelectedNamespace(endpointMode, nsName)
				return nil
			})
		}

		for _, nsName := range deselectedNamespaces {
			// and here
			c.queue.Push(func() error {
				c.handleDeselectedNamespace(kubeClient, endpointMode, nsName)
				return nil
			})
		}
	})
```

Networkswatcher can also cause this type of bug

```go
//  ../serviceregistry/kube/controller/controller.go
if c.opts.NetworksWatcher != nil {
         // here
	c.opts.NetworksWatcher.AddNetworksHandler(c.reloadNetworkLookup)
	...
}
```

### Version

```Text
istio latest version
```

**Comment by hzxuzhonghu** [comment]
Good catch @Erica177

**Comment by SpecialYang** [comment]
This bug will also happen in the remote cluster kubeconfig updating case.  

In our production we need to rotate kubeconfig frequently. Periodic kubeConfig rotation prompted us to discover this memory leak bug. My colleagues @Erica177 will try to fix it and contribute it to the community.

Assign @Erica177 .
