### ISSUE TITLE
Tracker for caveats and existing problems with Multicluster

### ISSUE THREAD

**Issue by sdake** [istio/istio#4822]
This tracker will track caveats and known issues with the multicluster implementation in the 0.8 release.

**Comment by costinm** [comment]
Not sure "merge istio-remote into istio helm chart once istio-remote is solidified" is a good move, cleaner to keep them separate ( as we address SDS and make other improvements, istio-remote should become smaller and may have specific needs - on the other side istio templates are already getting too messy).

**Comment by costinm** [comment]
" determine if local and remotes can use automatic injection, or if manual injection is only available." - I think we just miss the config, there should be no problem.

I would add:
(P2 for 1.0) "improve security and reduce dependency on secret copying" - i.e. if SDS is available switch to it. That would use a central CA, and each node will fetch/renew secrets from it without using k8s Secret.

(P2) Expand MC to non-k8s registries ? 

P1: improve security by using service accounts with reduced RBAC permissions instead of the current 
broad admin credentials installed in the primary cluster.
P2: automated the generation of remote cluster service account and certificates, including cert rotation.

**Comment by tiswanso** [comment]
@sdake @costinm  -- I have the service-account procedure for creating the remote's kubeconf to give pilot limited RBAC controls.  I don't have the exact limitation on what pilot needs, though.  Probably read-only to all service, endpoint, and pod objects.  I will try to push a doc PR soon with what I have.

**Comment by sdake** [comment]
@tiswanso what would be better is a change to istio-remote helm chart with limited RBAC.

**Comment by tiswanso** [comment]
@sdake -- not sure how helm can do anything RBAC-wise but anyway, that's for setting up the Istio control pod (citadel), secrets, and selectorless services on the remote cluster.  The service-account RBAC I'm referring to is tied to the kubeconf secrets we're creating in the control-plane cluster.  So, it'd be limiting what pilot could do on the remote kube-api-server.

**Comment by sdake** [comment]
What I meant was adding very strict rbac here: https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio-remote/templates - perhaps this is the wrong place to do it.

@tiswanso can you create an issue with your proposal?  I'll link it from the first entry in this issue tracker and we can continue discussion there.

Cheers
-steve

**Comment by sdake** [comment]
@myidpt @costinm struggling to write an issue for this text:
```
 P2 automate the generation of remote cluster service account and certificates, including cert rotation. -
```

could either of you expand on this a bit as to what you think is needed in terms of the specific problem so I can write a new issue?  (or alternately write an issue and link it or I can link it).

TIA!
-steve

**Comment by costinm** [comment]
Sorry, by 'RBAC' I meant that we need a service account in each remote,
with RBAC rules limiting it to read
access to resources used by pilot. And to use that service account instead
of the 'admin' account currently
used by multicluster.

When we use kubeconfig to setup MC in 0.8, the master cluster gets too
broad permissions.

**Comment by sdake** [comment]
@costinm thanks - I think both of these requirements are captured now.

Cheers
-steve

**Comment by Rigdon** [comment]
I'm looking at #6092

**Comment by Rigdon** [comment]
Also related to the RBAC discussion: I'm attempting this first with a service account bound to the `system:node-proxier` role on the remote clusters. This service account token is what I'll store on the control plane cluster for each remote.

It's still more permissions than are needed but at least it's read-only.

**Comment by tiswanso** [comment]
doc PR for instructions to create serviceaccount on remotes with min RBAC: https://github.com/istio/istio.github.io/pull/1484

**Comment by Rigdon** [comment]
thanks @tiswanso! I'll add that cluster role to my WIP for the istio-remote helm chart

**Comment by john-a-joyce** [comment]
@sdake - I intend to add the multicluster circleci item we have talked Costin about a few times.   Should be a P1 I think.   If I don't hear anything I will edit in tomorrow.

**Comment by sbezverk** [comment]
@sdake Here is PR to switch multicluster's secret controller to use envoy v2 API:
https://github.com/istio/istio/pull/6311

**Comment by sdake** [comment]
Folks when issues are complete please click the checkmark.

Cheers
-steve

**Comment by sdake** [comment]
A new issue with multicluster reported - invalid credential input causes pilot to crater.  https://github.com/istio/istio/issues/6443

**Comment by sdake** [comment]
this has been released in alpha quality.  If others have additional changes they wish to propose, please file a new issue in the issue tracker.

Cheers
-steve
