### ISSUE TITLE
Istio routes to wrong headless service

### ISSUE THREAD

**Issue by Thrillpool** [istio/istio#48239]
### Is this the right place to submit this?

- [X] This is not a question about how to use Istio
- [X] This is not a security vulnerability or a crashing bug

### Bug Description

I have made a minimal reproduction of my problem in minikube like so. It is a fresh minikube with nothing done but istio installed

I have a service like so

```
apiVersion: v1
kind: Service
metadata:
  name: mys
spec: 
  clusterIP: None
  ports:
  - name: r
    port: 80
    protocol: TCP
    targetPort: 80
```
And an endpoints like so

```
apiVersion: v1
kind: Endpoints
metadata:
  name: mys
susbsets:
- addresses:
  - ip: 142.250.179.238
  ports:
  - name: r
    port: 80
    protocol: TCP
```

I make this service and endpoints in namespace aaaaa and namespace bbbb.

I make a pod in aaaa and bbbb, I have istio-injection enabled for both namespaces.

From each pod I curl `mys`. In the logs for istio-proxy in both pods, I see the same service referred to, e.g. let's say mys.aaaa.svc.cluster.local.

But this doesn't make any sense to me, I anticipated the pod in aaaa would use mys.aaaa.svc.cluster.local and in bbbb would use mys.bbbb.svc.cluster.local. Actually this behaviour of routing to a common place occurs even if the services themselves have different names (e.g. mys1 and mys2, a curl for mys1 will go to mys2)

This situation is unhappy for me, because I want to have destination rules in both namespaces which have a workload selector and target the service in that particular namespace. And indeed, in my actual use case, this is causing me problem, the destination rule works in the one namespace containing the common service that istio is routing to, but not any of the others. 

Ultimately I can work around this, but this setup of having a service and endpoints per namespace is part of a previous design that I must conform to.

### Version

```Text
istioctl
---
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (3 proxies)

kubectl
---
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

**Comment by j2gg0s** [comment]
Can you share your pod's listener config?
Get config by command like: `istioctl proxy-config listener {pod}.{namespace}`

Ref: https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#deep-dive-into-envoy-configuration

**Comment by Thrillpool** [comment]
Yep

```
ADDRESSES       PORT  MATCH                                                                    DESTINATION
10.96.0.10      53    ALL                                                                      Cluster: outbound|53||kube-dns.kube-system.svc.cluster.local
0.0.0.0         80    Trans: raw_buffer; App: http/1.1,h2c                                     Route: 80
0.0.0.0         80    ALL                                                                      PassthroughCluster
142.250.179.238 80    Trans: raw_buffer; App: http/1.1,h2c                                     Route: mys.aaaa.svc.cluster.local:80
142.250.179.238 80    ALL                                                                      Cluster: outbound|80||mys.aaaa.svc.cluster.local
10.109.25.85    443   ALL                                                                      Cluster: outbound|443||istiod.istio-system.svc.cluster.local
10.96.0.1       443   ALL                                                                      Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.96.147.188   443   ALL                                                                      Cluster: outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.96.0.10      9153  Trans: raw_buffer; App: http/1.1,h2c                                     Route: kube-dns.kube-system.svc.cluster.local:9153
10.96.0.10      9153  ALL                                                                      Cluster: outbound|9153||kube-dns.kube-system.svc.cluster.local
0.0.0.0         15001 ALL                                                                      PassthroughCluster
0.0.0.0         15001 Addr: *:15001                                                            Non-HTTP/Non-TCP
0.0.0.0         15006 Addr: *:15006                                                            Non-HTTP/Non-TCP
0.0.0.0         15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: 0.0.0.0/0 InboundPassthroughClusterIpv4
0.0.0.0         15006 Trans: raw_buffer; App: http/1.1,h2c; Addr: 0.0.0.0/0                    InboundPassthroughClusterIpv4
0.0.0.0         15006 Trans: tls; App: TCP TLS; Addr: 0.0.0.0/0                                InboundPassthroughClusterIpv4
0.0.0.0         15006 Trans: raw_buffer; Addr: 0.0.0.0/0                                       InboundPassthroughClusterIpv4
0.0.0.0         15006 Trans: tls; Addr: 0.0.0.0/0                                              InboundPassthroughClusterIpv4
0.0.0.0         15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: *:80      Cluster: inbound|80||
0.0.0.0         15006 Trans: raw_buffer; App: http/1.1,h2c; Addr: *:80                         Cluster: inbound|80||
0.0.0.0         15006 Trans: tls; App: TCP TLS; Addr: *:80                                     Cluster: inbound|80||
0.0.0.0         15006 Trans: raw_buffer; Addr: *:80                                            Cluster: inbound|80||
0.0.0.0         15006 Trans: tls; Addr: *:80                                                   Cluster: inbound|80||
0.0.0.0         15010 Trans: raw_buffer; App: http/1.1,h2c                                     Route: 15010
0.0.0.0         15010 ALL                                                                      PassthroughCluster
10.109.25.85    15012 ALL                                                                      Cluster: outbound|15012||istiod.istio-system.svc.cluster.local
0.0.0.0         15014 Trans: raw_buffer; App: http/1.1,h2c                                     Route: 15014
0.0.0.0         15014 ALL                                                                      PassthroughCluster
0.0.0.0         15021 ALL                                                                      Inline Route: /healthz/ready*
10.96.147.188   15021 Trans: raw_buffer; App: http/1.1,h2c                                     Route: istio-ingressgateway.istio-system.svc.cluster.local:15021
10.96.147.188   15021 ALL                                                                      Cluster: outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
0.0.0.0         15090 ALL                                                                      Inline Route: /stats/prometheus*

```
This is for the pod in the 'bbbb' namespace

**Comment by j2gg0s** [comment]
mys.aaaa(Service) and mys.bbbb(Service) both point to 142.250.179.238(Endpoint)

I'm not sure whether istio can directly support this case,
istio maintains the mapping relationship from endpoint to service in its code.

**Comment by Thrillpool** [comment]
Hmm yep OK I thought you might say something like this, so is this a bug? It is very surprising behaviour no?

Let me explain my use case, basically I have an external to cluster service I want to talk to. Existing design has been setup to make a service and endpoints per namespace pointing to this service. 

OK this isn't exactly how I would have done things (I probably would have either made an external dns entry together with ServiceEntry per namespace, or I would have made a single service in a designated namespace), but I do think the approach chosen makes sense.

Given this design, I want a destination rule with a workload selector per namespace so that traffic to this external service can do tls origination. I wanted to do this by making my destination rule target the per namespace service. But it doesn't work, because except in one lucky namespace, the destination rule won't apply, because the host doesn't agree.

Do you know what is istios intended solution to this use case?

**Comment by Thrillpool** [comment]
Mm that is what I am doing presently, what I mean is the DestinationRule is namespace bbbb, it would only make sense for it to refer to service mys.bbbb, but that service will never get used so DestinationRule won't be applied. And I can't just arbitrarily use mys.aaaa, because I don't know what namespace is going to be the one that gets used.

And because I have a workload selector, it's not like I can write export destinationrule from every namespace to all namespaces (and in any case this seems a hacky fix).

But thank you, will see what specific maintainer says.

**Comment by j2gg0s** [comment]
Although I don’t know the specific answer, I still want to say a few more words.
I hope it didn't take up your time too much.

Do we need multi Service?
Can we use multiple DestinationRules to point to the same service?
And use DestiantionRule control policy in namespace.

**Comment by Thrillpool** [comment]
Mm no of course, thank you for responding

Do we need multi Service?

- In my use case, technically no, I could have shared Service in a common namespace. But, I do think in general it makes sense to want multi service. Imagine a cluster wherein basically namespaces have very limited cross namespace permissions.

Can we use multiple DestinationRules

- technically yes, but then every namespace would need to know every other namespace that has a service defined, this is a strange design

**Comment by howardjohn** [comment]
Given both have the same IP address, they are indistinguishable so Istio has to pick one.

**Comment by Thrillpool** [comment]
I know what you mean, you mean that by the time it reaches istio the only information is the ip address. So you are saying this is 'expected' albeit unfortunate behaviour. I don't really see that it 'has' to pick one though, it could pick a name that's more representative of the fact that it doesn't name. With things as they are presently, things can coincedentally work, which for me is worse than them just consistently not working - but I suppose this was a conscious choice made at the time and there's no undoing it now anyway.

Is there any facility for my to insist that that ip resolve to a given hostname for a given istio container? I guess my confusion is really that like I say, it doesn't seem that unreasonable to have multiple headless services across a cluster pointing at the same ip, and it's not clear to me how to deal with that with resepct to wanting a destination rule, but I appreciate that is a different question to asking whether this is a bug or not.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/ can help.

If you set it as an HTTP service it can route based on the hostname, which doesn't have the IP issue.

**Comment by howardjohn** [comment]
In general though, this is a unique setup I have never seen in 5 years on Istio :slightly_smiling_face: any more context on why things are setup this way? Why not user a ClusterIP service? Or just a single service instead of 2?

**Comment by Thrillpool** [comment]
mm for me I can't make it http service, because in my actual use case it genuinely isn't one, and in any case I don't control the bit of code that defines the services (if I did, I would just make a single service)

Haha, OK, maybe it really is unusual then - that is a lot more time than I have been doing anything in kubernetes at all! I don't have context on why things are set up this way no, possibly I could find out. 

I can appreciate the value of somewhat artificially creating extra ips so that tcp can differentiate between things, it's true, that's a good idea (if I were able to do it). So I won't argue against using a ClusterIP Service - maybe I can ask to have the code changed such that it makes a ClusterIP Service thank you for the suggestion.

Using multiple services that point to same place really does make sense to me though, because I think maybe these services just /happen/ to point to the same ip, i.e. maybe in context A you want to connect to some external postgres database say, and in context B you want to connect to some external postgres database, and you want to define a service 'postgres' in each namespace to go through - that all seems reasonable. And then if it just happens to be that these postgres databases are the same, you end up in this situation.

**Comment by howardjohn** [comment]
If the two are completely independant you can isolate them as well. Either exportTo=. ("expose only to same namespace") on the service, or use Sidecar ("import only some services"). https://istio.io/docs/reference/config/networking/sidecar/

**Comment by Thrillpool** [comment]
These are really kubernetes services not ServiceEntries so I don't think I can exportTo, but this Sidecar configuration sounds like a good idea, let me see if I can make this work in my minikube setup and if so I will paste configuration I used, may be helpful for someone else in the future!

**Comment by Thrillpool** [comment]
mm yep indeed, in my example if I make a Sidecar like

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidekick
spec:
  egress:
  - port:
      number: 80
      protocol: TCP
      name: myegress
    hosts:
    - "aaaa/*"
```
in namespace aaaa and similar in bbbb with hosts changed, I get the right behaviour. There will be some refinement to do to make this actually work in my context, and I'll need to understand exact behaviour of some things but this looks nice.

Thank you! This has been very helpful. Happy for issue to be closed now if you like.

**Comment by howardjohn** [comment]
there is an annotation for exportTo on service as well

**Comment by Thrillpool** [comment]
Oh yep, 

https://istio.io/latest/docs/reference/config/networking/service-entry/

```
For a Kubernetes Service, the equivalent effect can be achieved by setting the annotation “networking.istio.io/exportTo” to a comma-separated list of namespace names.
```

OK very nice, I can't actually use this easily as like I say I don't control this code, but for sure I can ask for this to get added.
