### ISSUE TITLE
test flake TestAccessLogsMode/client-and-server 

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#48243]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/48235/integ-telemetry-discovery_istio/1732920674399293440

### Version

```Text
master
```

**Comment by zirain** [comment]
never see this before, perhaps the load is too high, and logs cannot be output within 3s.
