### ISSUE TITLE
mutatingWebhookConfiguration no-opted when using `istoctl ... --dry-run`

### ISSUE THREAD

**Issue by jvandemark** [istio/istio#48241]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

running certain `istioctl ... --dry-run` commands basically disable the mutating webhook (`istio-sidecar-injector`) by adding the following
```
    matchLabels:
      istio.io/deactivated: never-match
```
e.g.
```
istioctl install --set values.global.proxy.privileged=true --dry-run
```

### Version

```Text
client version: 1.19.3
control plane version: 1.19.3
data plane version: 1.19.3 (5 proxies)
```

**Comment by jvandemark** [comment]
a dry run shouldn't alter anything, especially not the mutating webhook.

**Comment by howardjohn** [comment]
Definitely agree dry run should not write. Thanks for the report

cc @hanxiaop

**Comment by hanxiaop** [comment]
I'll check it.
