### ISSUE TITLE
Cleanup source.* and destination.* attributes

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4824]
We plan to clean up the source.* and destination* attributes to make their purpose and meaning clearer.

We will introduce support for these new attributes as soon as possible, and retain the existing attributes until the 1.0 release. For 1.0, the old attributes will be removed and not be available.

Existing uses of source.service should be changed to source.labels instead.

``` 
Before           After
source.ip        source.workload.ip
source.name      <remove>
source.service   <remove>
source.namespace source.workload.namespace
source.domain    <remove>
source.uid       source.workload.id
source.labels    source.workload.labels
source.user      source.workload.principal

destination.ip          destination.workload.ip
destination.port        destination.workload.port
destination.service     destination.service
destination.name        destination.service.name
destination.namespace   destination.service.namespace
destination.domain      destination.service.domain
destination.uid         destination.workload.id
destination.labels      destination.workload.labels
destination.user        destination.workload.principal
n/a                     destination.service.labels
```

**Comment by geeknoid** [comment]
FYI @mandarjog @douglas-reid

**Comment by kyessenov** [comment]
This is great! A couple of questions:
1. `destination.service` seems to have both types string and an attribute struct
2. `destination.service.port` might be useful, and it is distinct from `destination.workload.port`

**Comment by geeknoid** [comment]
What do you mean by #1? This should be just a string since our attribute model doesn't support structs.

As for #2, that makes sense.

**Comment by kyessenov** [comment]
Re #1: OK, but it may pose a problem if we want to map attribute namespaces to JSON, for example. I'm not informed whether that's a good idea :)

**Comment by liminw** [comment]
Questions:
1. It seems that all the "source" attributes are changed to "source.workload" attributes. Do we have anything else for "source", other than "source.workload"? If not, why not use one word "source" or "sourceWorkload"? "source.workload" seems indicating that there are types other than "workload" for "source". 

2. What is the relationship between service accounts, services, and workloads? Is service account still the identity for a "service", or "workload"?

**Comment by douglas-reid** [comment]
There are use cases for having pod name and container name for source and destination carried in attributes. Can we add detail on how those should be handled in this proposal?

Do we want something like: `*.workload.name` and `*.workload.containerName`?

Also, do we have any need for other workload attributes (domain, cluster)?

**Comment by geeknoid** [comment]
See the latest proposal here: https://docs.google.com/document/d/1IcR6C7j5Vl-4Jx8ervVT4lCTBDrBgsD7Uac77K5C5h4/edit#heading=h.qex63c29z2to

**Comment by yangminzhu** [comment]
cc @yangminzhu

**Comment by douglas-reid** [comment]
Can we close this out now?
