### ISSUE TITLE
Review Authn policy with the upcoming inpod network redirection work

### ISSUE THREAD

**Issue by linsun** [istio/istio#48272]
Opening this to track the drive beta to ambient doc:

Peer authentication policy is implemented for ztunnel but need to check if the impl matches the latest design and is impacted by the new inpod redirection work.

AI: review authn work with inpod redirection.  Do we enable peer authn by default or not?

In pod network update:  https://github.com/istio/istio/issues/48212

**Comment by linsun** [comment]
Waiting on https://github.com/istio/istio/issues/48212 to be merged

**Comment by linsun** [comment]
Hi @bleggett I think you may be a good owner for this?

**Comment by bleggett** [comment]
Inpod doesn't affect this but I  did find some weirdness where less-strict portMTLS settings are seemingly not respected by ztunnel, looking.

**Comment by bleggett** [comment]
Think we chased this down to a CP serialization bug: https://istio.slack.com/archives/C049TCZMPCP/p1706742135078049

cc @keithmattix wants to fix it.

**Comment by keithmattix** [comment]
Should be fixed by #49131

**Comment by howardjohn** [comment]
Looks like the last issues was resolved
