### ISSUE TITLE
Performance test for ambient

### ISSUE THREAD

**Issue by linsun** [istio/istio#48271]
**Describe the feature request**

Discuss performance test for ambient, what benchmark we use. I propose let us focus on step 1 first for 1.22.

- [ ] Ambient will reach beta in 1.22, so we need to refresh this [page](https://istio.io/latest/docs/ops/deployment/performance-and-scalability/) with ambient data (L4 and optioanlly L4 & L7) along with sidecars and no mesh data today. We should run same tests as today to measure latency.
  - Our CNCF hardware is currently set up to run the test, you can find instructions [here](https://github.com/istio/tools/tree/release-1.21/perf/benchmark).
  - one caveat: the test we run today is for sidecar is on the same node. While this is useful to collect but won't be most common scenarios for ambient (or sidecar) and there could be quite some difference between source & target on ambient same node vs different nodes. We should look into having tests run different nodes for source and target.
- [ ] We should also produce performance test results comparing Istio with Cilium & Linkerd

For reference: a few we have used in the past:

From @Stevenjin8 and @keithmattix - https://github.com/istio/tools/tree/master/ambient-tests
Existing Istio performance test for sidecars: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/
Performance test Solo used in the past by @GregHanson @ymesika and @dhawton: https://github.com/solo-io/ambient-performance

Our immediate goal for ambient L4:

[P0] Ambient should be as performant (throughput and latency) as sidecars, at least for L4 only. 

We also want to understand numbers for waypoint as well.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
@AndreaM12345 and I met yesterday and she agreed to have our scripts updated to include ambient L4 & L7 and perform some tests on 1.20.

I have followed up with [CNCF]( https://github.com/cncf/cluster/issues/243#issuecomment-1854707986) and it does sound the equinix env is for us to use even after the mentorship ends.

Some info from @AndreaM12345 on equinix:

https://deploy.equinix.com/developers/docs/metal/getting-started/
https://deploy.equinix.com/developers/docs/metal/accounts/ssh-keys/#getting-your-keys-on-your-servers
links on how to setup up kubernetes in equinox baremetal:
https://blog.alexellis.io/kubernetes-in-10-minutes/
https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart

**Comment by zengyuxing007** [comment]
I conducted a comparative test between ambient and sidecar. Based on the test results, under a certain QPS pressure, the performance of ambient and sidecar is similar (with slightly better latency for ambient). However, when subjected to unlimited QPS stress testing, the performance of ambient L7 Waypoint is worse than that of sidecar. This is likely due to the current connection pool implementation of ztunnel.

**Comment by ymesika** [comment]
@zengyuxing007 I also ran tests to check the difference in latency between sidecar mode and ambient and the latency of Ambient is much better than Sidecars (also max QPS). I tested with 1000 QPS over 100 connections between client and server workloads.
P.S. the difference is close with 1 connection but widens with the number of connections.

<img width="1837" alt="Screenshot 2024-01-24 at 16 17 26" src="https://github.com/istio/istio/assets/26809068/e28c84bc-8acd-40e6-ae53-2d413358e6d2">

I guess your first statement about similar performance under similar QPS is including a waypoint and 1 connection?

**Comment by zengyuxing007** [comment]
> @zengyuxing007 I also ran tests to check the difference in latency between sidecar mode and ambient and the latency of Ambient is much better than Sidecars (also max QPS). I tested with 1000 QPS over 100 connections between client and server workloads. P.S. the difference is close with 1 connection but widens with the number of connections.
> 
> <img alt="Screenshot 2024-01-24 at 16 17 26" width="1837" src="https://private-user-images.githubusercontent.com/26809068/299343817-e28c84bc-8acd-40e6-ae53-2d413358e6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDgwNjMsIm5iZiI6MTcwNjE0Nzc2MywicGF0aCI6Ii8yNjgwOTA2OC8yOTkzNDM4MTctZTI4Yzg0YmMtOGFjZC00MGU2LWFlNTMtMmQ0MTMzNThlNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxNTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjM2EwYTQzZjBlMzM3ZDlkYTgzYzdjMGY2ZThiZTdlM2RhMDAwMGNjZmEyMWVkYmU0Y2ViMjg4NGVkMTY0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dg992OHeV0wa_03ythqVX3dr8x_RiyICshWJIW5hvEU">
> I guess your first statement about similar performance under similar QPS is including a waypoint and 1 connection?

Yes,   forioclient -> fortserver , all is only one pod. this is the simplest model , the specific traffic paths are as follows.

## sidecar 
-  [ fortioclient -> sidecar ] -> [ sidecar -> fortioserver ]
## waypoint 
- [ fortioclient -> ztunnel ] -> waypoint  -> [ ztunnel -> fortioserver ] 

Regarding ztunnel and its upstream connection pool, it's probably better to be configurable. 
The waypoint cpu really isn't running full in the one pod scenario.

We also tested  multiple client and server  scenario.

-  16 client -> 16 waypiont  -> 16 server scenario, concurrency 64 , best effort (Max QPS) , Ambient L7 has better throughput (+30%) 
- 16 client -> 1 waypoint -> 16 server scenario, concurrency 4, best effort(Max QPS), Ambient L7 has worse throughput (-13%)


FYI.

**Comment by linsun** [comment]
> > @zengyuxing007 I also ran tests to check the difference in latency between sidecar mode and ambient and the latency of Ambient is much better than Sidecars (also max QPS). I tested with 1000 QPS over 100 connections between client and server workloads. P.S. the difference is close with 1 connection but widens with the number of connections.
> > <img alt="Screenshot 2024-01-24 at 16 17 26" width="1837" src="https://private-user-images.githubusercontent.com/26809068/299343817-e28c84bc-8acd-40e6-ae53-2d413358e6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDgwNjMsIm5iZiI6MTcwNjE0Nzc2MywicGF0aCI6Ii8yNjgwOTA2OC8yOTkzNDM4MTctZTI4Yzg0YmMtOGFjZC00MGU2LWFlNTMtMmQ0MTMzNThlNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxNTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjM2EwYTQzZjBlMzM3ZDlkYTgzYzdjMGY2ZThiZTdlM2RhMDAwMGNjZmEyMWVkYmU0Y2ViMjg4NGVkMTY0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dg992OHeV0wa_03ythqVX3dr8x_RiyICshWJIW5hvEU">
> > I guess your first statement about similar performance under similar QPS is including a waypoint and 1 connection?
> 
> Yes, forioclient -> fortserver , all is only one pod. this is the simplest model , the specific traffic paths are as follows.
> ## sidecar
> 
>     * [ fortioclient -> sidecar ] -> [ sidecar -> fortioserver ]
> 
> 
> ## waypoint
> 
>     * [ fortioclient -> ztunnel ] -> waypoint  -> [ ztunnel -> fortioserver ]
> 
> 
> Regarding ztunnel and its upstream connection pool, it's probably better to be configurable. The waypoint cpu really isn't running full in the one pod scenario.
> 
> We also tested multiple client and server pods scenario.
> 
>     * 16 client -> 16 waypiont  -> 16 server scenario, concurrency 64 , best effort (Max QPS) , Ambient L7 has better throughput (+30%)
> 
>     * 16 client -> 1 waypoint -> 16 server scenario, concurrency 4, best effort(Max QPS), Ambient L7 has worse throughput (-13%)
> 
> 
> FYI.

Thanks for sharing this! For your test, do you have consistent load between ambient and sidecar?  Can you share the fortio cmd you used? I plan to go back to do another run in a week or two.

**Comment by linsun** [comment]
> @zengyuxing007 I also ran tests to check the difference in latency between sidecar mode and ambient and the latency of Ambient is much better than Sidecars (also max QPS). I tested with 1000 QPS over 100 connections between client and server workloads. P.S. the difference is close with 1 connection but widens with the number of connections.
> <img alt="Screenshot 2024-01-24 at 16 17 26" width="1837" src="https://private-user-images.githubusercontent.com/26809068/299343817-e28c84bc-8acd-40e6-ae53-2d413358e6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTA0MzQsIm5iZiI6MTcwNjE1MDEzNCwicGF0aCI6Ii8yNjgwOTA2OC8yOTkzNDM4MTctZTI4Yzg0YmMtOGFjZC00MGU2LWFlNTMtMmQ0MTMzNThlNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzJkZGY5OWM0NjNmMDA3ODE3ZTcyMzdiMjM1MmU5ZTZkYmY4MWU0ZGNkZGYwNTYzNDE3MDAyZjUxMWE2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHGVq0QUcK5yPXxfKtS_iFZVva-nxgA14Lo9QlAOKyo">
> 
> I guess your first statement about similar performance under similar QPS is including a waypoint and 1 connection?

Very nice!  I assume this is comparing L4 ambient with sidecar, on TCP?  Could you share your commands also @ymesika ? Thanks!

**Comment by ymesika** [comment]
@zengyuxing007 thanks for sharing. I think the difference we see between results (~identical latencies for you vs. gap in latencies for me) is because of the waypoint you added.

My configurations (as this was my own interest) are:
1. `[fortio client][sidecar] -> ... cross nodes ... -> [sidecar][fortio server]`
2. `[fortio client] -> [ztunnel] -> ... cross nodes ... -> [ztunnel] -> [fortio server]`

@zengyuxing007 It's also important to mention that Ztunnel has different data path for cross-nodes vs. same node so make sure you are aware of that. But if you always have a waypoint in your scenarios then it is irrelevant.

@linsun I was using something like (from a fortio client container):
```sh
fortio load -qps 1000 -c 100 -t 60s -a -labels ${LABEL_PREFIX}_1000qps_100c http://fortio-server.test:8080
```
with connections count varying.

**Comment by linsun** [comment]
Unassign Andrea as she is no longer working on istio.

**Comment by linsun** [comment]
@zengyuxing007 I updated the desp with the initial goal of this work. Are you currently working on this?  Andrea indicated to me you have been looking into it.

Adding @dhawton to help provide an estimation of the work to update the scripts to work with ambient.

cc @Shuayb1 here if you have done anything

also cc @kfaseela FYI to avoid dup work.

**Comment by dhawton** [comment]
> @linsun Andrea and I have synchronized on the related matters, and I will be communicating with @Shuayb1 soon to see how we can modify/update the benchmark script and perform comparative performance tests.

Can you loop me into this conversation? If the timeline looks lengthy, I could pick it up to get it completed ideally before 1.22.

**Comment by linsun** [comment]
+1 @zengyuxing007 can you please have the conversations in the open somewhere? I'd prefer ambient-dev in slack or in github.  I'd like to understand how things looking for 1.22 which is targeted for May.

**Comment by linsun** [comment]
Followed up with @zengyuxing007 offline via slack, he is working on this.

**Comment by linsun** [comment]
A round of performance test was done for 1.22, but we need ongoing work for this:
https://preliminary.istio.io/latest/docs/ops/deployment/performance-and-scalability/

**Comment by linsun** [comment]
Work was done for 1.22, @Stevenjin8 do you want to open a new one for 1.24 and link to here?

**Comment by Stevenjin8** [comment]
1.24 issue: https://github.com/istio/istio/issues/52977
