### ISSUE TITLE
SSL_ERROR_SYSCALL in connection to endpoint in istio version. 1.20.0

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#48278]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I installed istio 1.20.0 and getting below error when I connect to third party endpoint. This is intermittent error.

**curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to test.example.com:9000**

I use service entry with the below config:

    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: service-entry-endpoint
    spec:
      hosts:
      - prod.example.com
      - test.example.com
      ports:
      - number: 9000
        name: https
        protocol: HTTPS
      resolution: DNS
      location: MESH_EXTERNAL

NOTE: Everything is working fine with istio version 1.19.4

### Version

```Text
istio version:
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (7 proxies)

***

kubectl version:
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

### Additional Information

istio proxy logs from the same pod:

	{
		"start_time": "2023-12-11T21:31:38.155Z",
		"bytes_sent": 0,
		"route_name": null,
		"authority": null,
		"method": null,
		"upstream_cluster": "outbound|9000||test.example.com",
		"upstream_service_time": null,
		"x_forwarded_for": null,
		"downstream_local_address": "xx.xx.xx.xx:9000",
		"duration": 10003,
		"connection_termination_details": null,
		"response_code": 0,
		"protocol": null,
		"response_flags": "UF,URX",
		"upstream_local_address": null,
		"requested_server_name": "test.example.com",
		"path": null,
		"upstream_host": "xx.xx.xx.xx:9000",
		"request_id": null,
		"bytes_received": 0,
		"response_code_details": null,
		"upstream_transport_failure_reason": null,
		"user_agent": null,
		"downstream_remote_address": "10.1.0.62:34160"
	}

**Comment by howardjohn** [comment]
Looks like it attempts to connect and takes >10s so it times out. I don't see a clear reason why 1.19 vs 1.20 would change this behavior. Is it possible the endpoint itself has had performance degradation and happens to coincide with the upgrade? 

Seems a bit odd, but the config here is very simple, its just a basic TCP proxy, so its hard to see where things can go wrong aside from issues with the connectivity itself.
