### ISSUE TITLE
Update istio annotation and label doc for ambient

### ISSUE THREAD

**Issue by linsun** [istio/istio#48274]
We need to be able to understand what is for L4 and what we can support for beta.

**Comment by GregHanson** [comment]
released to https://github.com/istio/istio/issues/43437

**Comment by ilrudie** [comment]
Not sure if it helps but the [ambient rev](https://docs.google.com/document/d/14Evqp2J8Gr0BkBC92gXQuS1ZlP_mUSH4W6j0jKJ7xHU/edit?resourcekey=0-h68fIlGPTzwse_JIsRBIWA#heading=h.xw1gqgyqs5b) doc has some tables I added regarding labels for ambient and how they interact with sidecar

**Comment by linsun** [comment]
WIP draft to review all existing labels and annotations for ambient: https://docs.google.com/document/d/1BoxkKjtvmZVju5SgH1ML3OmRxQYbWEyO8_Oz7KqJCoc/edit

**Comment by linsun** [comment]
Doc has been reviewed and still working on feedback.

**Comment by linsun** [comment]
Doc has been created and feedback addressed so far. closing this as impact for beta assessment is done
