### ISSUE TITLE
Create an istioctl analyzer to detect targetRef applying to sidecars or workloadSelector applying to Ambient

### ISSUE THREAD

**Issue by linsun** [istio/istio#48273]
Opened based on ambient beta doc to ensure we can help users with eerors in layered authz policy.

**Comment by hanxiaop** [comment]
Currently, we have validation webhook in place, and attempting to apply targetRef to non-k8s gateways will fail the validation. The analyzer includes a schema validation analyzer as well. Therefore, I think the only thing to do is to warn users if they apply a workloadSelector to Kubernetes gateways, as this will have no effect.
