### ISSUE TITLE
traffic error when mtls switch close to strict

### ISSUE THREAD

**Issue by twogoods** [istio/istio#48290]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [ ] This is not a question about how to use Istio

### Bug Description

Config PeerAuthentication DISABLE to STRICT, And serviceA to call serviceB,  A get xds config send tls traffic，but B's xds delayed and not received yet, at the same time the service call A to B will fail. 
How to consider this case?

### Version

```Text
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (4 proxies)
```

**Comment by GregHanson** [comment]
Do you still see this with a more recent version of Istio?  1.16 is EOL

**Comment by twogoods** [comment]
> Do you still see this with a more recent version of Istio? 1.16 is EOL

istio version is not important，I just want to know how istio consider this scene? has any solution for this?

**Comment by wulianglongrd** [comment]
This seems to be expected. You need to set it to `PERMISSIVE` first, make sure there is no plaintext traffic, and then set it to `STRICT`. Here is a migration example. https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/

**Comment by wulianglongrd** [comment]
This document mentions this problem. If you still have problems, please feel free to reopen this issue.

https://istio.io/latest/docs/concepts/security/#updating-authentication-policies

**Comment by twogoods** [comment]
> This document mentions this problem. If you still have problems, please feel free to reopen this issue.
> 
> https://istio.io/latest/docs/concepts/security/#updating-authentication-policies



> This seems to be expected. You need to set it to `PERMISSIVE` first, make sure there is no plaintext traffic, and then set it to `STRICT`. Here is a migration example. https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/

when in PERMISSIVE mode，outbound traffic is plaintext？envoy dump config show outbound is tls. if outbound is tls， `DISABLE to STRICT` is same with `DISABLE to PERMISSIVE` in my case

**Comment by wulianglongrd** [comment]
Good question. I think there are two questions involved:
1. How does envoy determine whether inbound and outbound should establish a plaintext connection or a tls connection?
2. How does envoy switch from plaintext connection to tls connection? Plaintext connection drainage, new connection using tls?

TBH, I am not confident in the answers to these two questions, so I dare not reply rashly to avoid misunderstandings.

**Comment by wulianglongrd** [comment]
> Good question. I think there are two questions involved:
> 
> 1. How does envoy determine whether inbound and outbound should establish a plaintext connection or a tls connection?
> 2. How does envoy switch from plaintext connection to tls connection? Plaintext connection drainage, new connection using tls?
> 
> TBH, I am not confident in the answers to these two questions, so I dare not reply rashly to avoid misunderstandings.

I think @ramaraochavali would be familiar.
