### ISSUE TITLE
Improve MergeTrafficPolicy to automatically merge new added fields

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48292]
follow https://github.com/istio/istio/pull/48268

We can see when we add a new field in API, it is very likely to miss updating this function.  And it costed me much time to debug why the integration test failure in https://github.com/istio/istio/pull/48237

**Comment by ivantrips** [comment]
@hzxuzhonghu if nobody is working on this i would like to work on it, if you can assign it to me

**Comment by hzxuzhonghu** [comment]
Sure, welcome!

**Comment by hzxuzhonghu** [comment]
This can be closed
