### ISSUE TITLE
Updates to access log related meshConfig cause websocket disconnects

### ISSUE THREAD

**Issue by clayvan** [istio/istio#48305]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've found that when you make an update to the istio meshConfig such as `accessLogEncoding` or `accessLogFormat` (probably accessLogFile as well), all websockets will be disconnected right away.

I tested against a bunch of other meshConfig options and was unable to reproduce the disconnects, only with access log related config.

I'm guessing the connection has to be reestablished to update the logger.

In my mind, we need 1 or both of these things:
- Documentation to be updated that updating these access log related mesh configs will cause connections to be disconnected (I would not have done this for example)
- ideally - update istio to respect the `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` flag when updating access log formats

### Version

```Text
$ istioctl version

client version: 1.19.3
control plane version: 1.18.2-tetratefips-v0
data plane version: 1.18.5 (121 proxies)

$ kubectl version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.17-eks-4f4795d
```
```


### Additional Information

_No response_

**Comment by zirain** [comment]
I would say that `this worked as expected`, because of listener will rebuild when `meshConfig` updated.
IMO, the client should try to reconnected

**Comment by clayvan** [comment]
Hmm then should there be a new config for listenerDrainGracePeriod? Clearly it's important to gracefully drain connections or else we wouldn't have all the other config options for draining on termination.

Bare minimum there should be a warning in the docs.

**Comment by clayvan** [comment]
> listener will rebuild when meshConfig updated

Do you know which `meshConfig` fields being updated will cause the listener to rebuild and which will not? From my testing it was only access log related fields, but you make it sound like any field update would cause the listener to be rebuilt?

**Comment by zirain** [comment]
> > listener will rebuild when meshConfig updated
> 
> Do you know which `meshConfig` fields being updated will cause the listener to rebuild and which will not? From my testing it was only access log related fields, but you make it sound like any field update would cause the listener to be rebuilt?

You even need to restart/rollout the deployment for some fields to take effect.

**Comment by clayvan** [comment]
> You even need to restart/rollout the deployment for some fields to take effect.

That seems reasonable to me and would be preferable as my websockets would only be drained following the graceful drain config i've setup to handle rolling restarts.

**Comment by zirain** [comment]
If you really care about this, you can move to use [Telemetry API](https://istio.io/latest/docs/tasks/observability/telemetry/). In that case accesslog in meshconfig will be ignored.

**Comment by zirain** [comment]
> If you really care about this, you can move to use [Telemetry API](https://istio.io/latest/docs/tasks/observability/telemetry/). In that case accesslog in meshconfig will be ignored.

I'm not rigorous, listener will still be updated in most scenarios.

**Comment by clayvan** [comment]
> If you really care about this

Yes I really care about understanding which istio configuration updates will and will not disconnect all active connections without draining them.

In my opinion, it IS NOT reasonable that updating a log format will cause all active connections to be dropped across the entire service mesh.

To be clear, I have already learned this lesson the hard way and I have no plans on reverting back to my previous configuration. So I'm personally not worried about me changing my logging format anymore.

I am worried about three things though:
1. A different meshConfig option that will automatically terminate connections without draining them and that is not documented and this thread does not seem the place to get that information. Now I'm terrified of updating my meshConfig as the behavior is undefined.
2. I feel bad for the next istio consumer who updates this in production and wished this was documented/handled more gracefully
3. I'm worried that the Istio maintainers don't understand the reasoning for _needing_ all connection terminations to be graceful when possible.

**Comment by clayvan** [comment]
@howardjohn Please consider not letting this issue be ignored.

There needs to at very least be documentation of the defined set of Istio resources/properties that WILL cause a listener rebuild and all websockets to be terminated without respecting the graceful drain configuration that occurs during pod terminations.
