### ISSUE TITLE
Istio failed to start on the virtual machine.

### ISSUE THREAD

**Issue by dengxiaolin23** [istio/istio#48311]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

1.Follow this URL:https://istio.io/latest/docs/setup/install/virtual-machine/
2. sudo systemctl start istio(run on Debian）
3. but istio start failed as bell log.
2023-12-13T02:14:05.007242Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev.json --drain-time-s 45 --drain-strategy immediate --local-address-ip-version v4 --file-flush-interval-msec 1000 --disable-hot-restart --allow-unknown-static-fields --log-format %Y-%m-%dT%T.%fZ  %l      envoy %n %g:%#  %v      thread=%t -l warning --component-log-level misc:error]
2023-12-13T02:14:05.020794Z     info    sds     Starting SDS grpc server
2023-12-13T02:14:05.020992Z     info    starting Http service at 127.0.0.1:15004
2023-12-13T02:14:06.136879Z     error   citadelclient   Failed to load key pair open etc/certs/key.pem: no such file or directory
2023-12-13T02:14:06.136964Z     warn    ca      ca request failed, starting attempt 1 in 97.902184ms
2023-12-13T02:14:06.235849Z     warn    ca      ca request failed, starting attempt 2 in 212.49258ms
2023-12-13T02:14:06.449820Z     warn    ca      ca request failed, starting attempt 3 in 378.603717ms
2023-12-13T02:14:06.830193Z     warn    ca      ca request failed, starting attempt 4 in 759.968526ms

How to  generate key.pem？

### Version

```Text
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.4
Kustomize Version: v4.5.7
Server Version: v1.26.4

OS
Debian 12
```

**Comment by hzxuzhonghu** [comment]
I think the vm install doc guide using istio-token to do auth with istiod, so `error citadelclient Failed to load key pair ` indicates some env or param passed unexpectedly

**Comment by hzxuzhonghu** [comment]
Assume env `PROV_CERT` is set

**Comment by dengxiaolin23** [comment]
> Assume env `PROV_CERT` is set

How to set PROV_CERT?

**Comment by hzxuzhonghu** [comment]
You should not set it unless you are using certificate. In this issue, i think you must have set  the env, otherwise the code could not run here

**Comment by dengxiaolin23** [comment]
> You should not set it unless you are using certificate. In this issue, i think you must have set the env, otherwise the code could not run here

都是按照官方的手册去配置的，里面也没有提到要设置PROV_CERT。我不太清楚哪个env会触发？

**Comment by hzxuzhonghu** [comment]
can you show all the pilot-agent logs

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/blob/8c74063ea7ab759339a5697be01c03afdce3a2c5/security/pkg/nodeagent/caclient/providers/citadel/client.go#L163-L169 

I could not think of another reason this failure occur

**Comment by dengxiaolin23** [comment]
> https://github.com/istio/istio/blob/8c74063ea7ab759339a5697be01c03afdce3a2c5/security/pkg/nodeagent/caclient/providers/citadel/client.go#L163-L169
> 
> I could not think of another reason this failure occur

谢谢你的回复，这个问题我知道这么解决了。但是感觉好坑啊。动不动就要重新去重新生成istio-token（特别是重启下机器，直接把/var/run/secrets/tokens这个目录删了，https://blog.haohtml.com/archives/31055）。istio在虚拟机上使用的人估计不多，有些功能还属于实验阶段。如果可以的话能加你的微信向你学习下不（我可以发邮件给你）？

**Comment by zirain** [comment]
Welcome to contribute, not matter the code or the blog/doc.

**Comment by dengxiaolin23** [comment]
在虚拟机起来之后，参照官网部署hello程序，在虚拟机上无法curl请求成功。不知道是什么原因。如下图：
![1](https://github.com/istio/istio/assets/149980880/e84554e7-43ec-4edf-b812-8f3c0725cbdd)
![2](https://github.com/istio/istio/assets/149980880/ea3f3af6-b55d-4586-afb6-3a0db02e0f15)
![3](https://github.com/istio/istio/assets/149980880/30e32330-d80d-4e73-82ec-fa53dd72bce5)

**Comment by zirain** [comment]
you should always read the english doc first, if still not working please report again.

**Comment by dengxiaolin23** [comment]
还是没有解决，其他人的解决办法是加一条静态路由到Pod CIDR网格段。 我加了也没有。telnet端口是通的。curl请求就报错：
[root@istio-node1 ~]# curl helloworld.sample.svc:5000/hello
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection timeout

**Comment by hzxuzhonghu** [comment]
Please comment in English, so more perople may help.

Please check the accesslog，and the configDump

**Comment by dengxiaolin23** [comment]
I cat't reproduce this issue with k8s 1.25.0+istio 1.20.0, but as others have said, it is necessary to add a static route。
