### ISSUE TITLE
(VirtualService default/my-service) Referenced host not found: "my-service.default.svc.non-default-domain

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#48326]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've tried `istioctl analyze` for the first time in our *working* production cluster and it reports lines like the following many times in a row for all services:
```
VirtualService default/my-service) Referenced host not found: "my-service.default.svc.non-default-domain
```
The VirtualServices _themselves_ are working completely fine.
I am sure it is due to us using a non-default cluster domain suffix `non-default-domain` (actual domain different) instead of the default `cluster.local`.
The reason we use a separate cluster domain is to enable VPC-native DNS in the GKE cluster to use Cloud DNS across different clusters with (possibly) identically named service names. Those are then disambiguated by the cluster domain suffix.
This suffix is also the trustDomain for SPIFFE configured in Istio.
So, everywhere where we _can_ change the default cluster domain to what we are using, we _did_ change this config.

However, `istioctl analyze` seems to have a problem with this.

### Version

```Text
1.20.0 and also now 1.20.1 (updated today)
```

**Comment by hanxiaop** [comment]
Not 100% sure but I think this might be a false positive result from the analyzer, as this code should be very old. I'll take a look.
