### ISSUE TITLE
When the pilot is abnormal, istio sidecar injection fails. After the pilot recovers, istio sidecar does not self-heal and is re-injected to the service pod.

### ISSUE THREAD

**Issue by dorseysen** [istio/istio#48321]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When the pilot is abnormal, istio sidecar injection fails. After the pilot recovers, istio sidecar does not self-heal and is re-injected to the service pod.

### Version

```Text
pilot:1.8.6
```

### Additional Information

After the number of replicas of the pilot is changed to 0, and the xxx pod is deleted, the xxx pod has only one primary container. After the pilot is restored, the sidecar container of the xxx pod is not restored.

**Comment by hzxuzhonghu** [comment]
Can you give more info how to reproduce?
Actually i do not know what ` istio sidecar does not self-heal and is re-injected to the service pod.` mean. 
After restart, can't istiod inject sidecar for any pod?

**Comment by hzxuzhonghu** [comment]
BTW, 1.8.6 is EOL, please upgrade

**Comment by dorseysen** [comment]
At first, I change the number of pilot replicas to 0, then delete the service pod, and set failurePolicy to Ignore. In this case, the service pod is started and its status is running 1/1. When the pilot is restored to two replicas, the service pod does not restart or is in the pending state to running 2/2. If failurePolicy=Fail is changed, the global impact is affected. Check whether there is a solution for pods.

**Comment by zirain** [comment]
you need rollout your applications manually when istiod is back.

**Comment by zirain** [comment]
if you're talking about upgrading, please try https://istio.io/latest/docs/setup/upgrade/canary/

**Comment by dorseysen** [comment]
> you need rollout your applications manually when istiod is back.

no，my applications is need to Self-healing，For example, all nodes are powered off. I understand this is a basic reliability scenario.

**Comment by dorseysen** [comment]
> you need rollout your applications manually when istiod is back.

You can't guarantee that polit is always online.

**Comment by hzxuzhonghu** [comment]
BY `Self-healing` , i assume you mean after istio started up again, the workload with one container should be recreated and injected with sidecar.

If so, this is not  istio's responsibility, maybe you can set failPolicy = fail, or you may need another operator to reconcile

**Comment by dorseysen** [comment]
> BY `Self-healing` , i assume you mean after istio started up again, the workload with one container should be recreated and injected with sidecar.
> 
> If so, this is not istio's responsibility, maybe you can set failPolicy = fail, or you may need another operator to reconcile

ok，tks，Is there a pod-level solution? I mean，It's better to have a pod-level solution.

**Comment by hzxuzhonghu** [comment]
No, the inject only happens during pod creation, either set mutatingwebhook with fail policy or let the pod created. After pod is running, istio will not execute any write ops on pod, only read.

You can write a separate controller watching pods that should be injected with sidecar but not, and then trigger them to recreate.

**Comment by dorseysen** [comment]
> No, the inject only happens during pod creation, either set mutatingwebhook with fail policy or let the pod created. After pod is running, istio will not execute any write ops on pod, only read.
> 
> You can write a separate controller watching pods that should be injected with sidecar but not, and then trigger them to recreate.

Does the istio sidecar have a health probe interface? Is it feasible for me to pass liveness?

**Comment by GregHanson** [comment]
@dorseysen istio-proxy containers have the `:15021/healthz/ready` API for readiness, which checks to make sure it has received it's initial XDS push from pilot
