### ISSUE TITLE
Readiness probe failed: Get "http://172.25.0.11:15021/healthz/ready": dial tcp 172.25.0.11:15021: connect: connection refused

### ISSUE THREAD

**Issue by Nutties93** [istio/istio#48358]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have deployed Istio 1.18.3 on my EKS cluster 1.27.
All the Istio control plane components are up and I can see the workloads from KIALI dashboard (which i expose internally using 
 route53, gateway and virtual service) .
![image](https://github.com/istio/istio/assets/48662440/c577d7df-9245-450d-9406-a92263b25d48)
![image](https://github.com/istio/istio/assets/48662440/8d2552f3-5046-48ae-bae5-59f3fcc5128a)

However, I am facing an intermittent issue with the Readiness probe of the Istio sidecar. I am getting this error 
Readiness probe failed: Get "http://172.25.0.11:15021/healthz/ready": dial tcp 172.25.0.11:15021: connect: connection refused. 
When the deployment has 1 replica - everything is working - however, when I increase the replica count to 2 or more. The subsequent pods will always be throwing this error.

Since it is an EKS cluster, it is using amazon's VPC cni and the pods are getting the IP address 172.25.X.X from the subnets of the EKS. I have also ensured that the security group of the EKS cluster is allowing all TCP ports to this CIDR range 172.25.0.0/16.

Does anyone here manage to properly deploy Istio on eks 1.27 or been getting the Readiness probe erros as well?

### Version

```Text
client version: 1.18.3
control plane version: 1.18.3
data plane version: 1.18.3 (5 proxies)

Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.9-eks-a5df82a", GitCommit:"0cef1972df37028b82a19d57f4014a558606526d", GitTreeState:"clean", BuildDate:"2023-10-16T23:34:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.7-eks-4f4795d", GitCommit:"3719c8491f81867f591e895a43b4f5aab4145794", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:04Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

When I increase the deployment replica to 2, there will always be 1 pod that has Readiness probe issue.
![image](https://github.com/istio/istio/assets/48662440/6fc0a9fe-2a86-4803-8a7d-8104cf4dda98)

1 container is showing this error 
![image](https://github.com/istio/istio/assets/48662440/c35292dc-cf1a-422b-bca0-c4bf1b72be41)

The healthy container does not have this error.
![image](https://github.com/istio/istio/assets/48662440/cb2ffe82-0899-47cc-8fae-cc655adcaed8)

**Comment by zirain** [comment]
can you check log from istio-proxy container

**Comment by zirain** [comment]
> 2023-12-14T14:43:16.892416Z warning envoy config external/envoy/source/common/config/grpc_stream.h:191 StreamAggregatedResources gRPC config stream to xds-grpc closed since 20134s ago: 14, connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc: i/o timeout" thread=17
> 2023-12-14T14:48:12.915950Z warn sds failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup istiod.istio-system.svc on 10.100.0.10:53: read udp 172.25.0.146:51451->10.100.0.10:53: i/o timeout"

can you check the network/coredns is ok for the failing container.

**Comment by Nutties93** [comment]
@zirain seems like one of the coredns containers was showing an error. After i restarted the deployment, the istio side car did not have any issues. The pods are all 2/2.
![image](https://github.com/istio/istio/assets/48662440/cb183322-539d-4466-a081-21fc159aa85f)

However, after 30 minutes or so, I tried to increase the replica for other deployments. I got back the same error as above. This time round both the coredns containers do not have errors.  I had to restart the coredns deployment and somehow it works again.

**Comment by zirain** [comment]
when you increase the replica, does the new pod schedule into another node?
I does think this's something related to istio, more likely your cluster network or other things.

**Comment by Nutties93** [comment]
@zirain after investigating with AWS. We found out that the pod that is stuck at 1/2 was unable to ping its healthcheck endpoint at http://localhost:15021/healthz/ready - it will return connection refused immediately. However, if we use another pod that is 2/2 (healthy) to ping this pod at http://<pod-assigned-ip>:15021/healthz/ready, it is returning the health response.

**Comment by Nutties93** [comment]
@zirain For clarity let me show you the following Screenshots.

The 'unhealthy' container was unable to call itself. http://localhost:15021/healthz/ready
![image](https://github.com/istio/istio/assets/48662440/5bd11ad9-2332-41e8-b716-b4e56a4f4388)

This is its error log.
![image](https://github.com/istio/istio/assets/48662440/bb99f188-0359-432e-bb31-18a49538d4b6)


To confirm that it is not a networking issue. I have tried to exec to another container and call the endpoint above. The endpoint is working.
![image](https://github.com/istio/istio/assets/48662440/9e2c0144-5a41-42db-980f-2ffa7b5cf759)

**Comment by linsun** [comment]
> @zirain after investigating with AWS. We found out that the pod that is stuck at 1/2 was unable to ping its healthcheck endpoint at http://localhost:15021/healthz/ready - it will return connection refused immediately. However, if we use another pod that is 2/2 (healthy) to ping this pod at http://:15021/healthz/ready, it is returning the health response.
> 
> I am thinking of installing the latest ISTIO version as I am using version 1.18.3 that was installed via solo.io in AWS marketplace. I have also updated all the kube-system services to AWS latest images. ( kube-proxy, coredns & etc... )
> 
> With regards to networking within the nodes, I have increased one of my deployments to 10 replicas. My kubernetes cluster currently have 3 nodes and among the 10 replicas, i have 7 successful pods running ( in alll 3 nodes ). Somehow there will always be a percentage of pods facing this issue from the point of initialization.

@Nutties93 just confirming you are not using upstream istio but solo.io in AWS marketplace?
cc @dhawton who may have some idea.

**Comment by Jamsa** [comment]
We met a similar issue but we found the issue was caused by IPV6.
After we add `command` and `args` to the deployment of the `helloworld`, it works well.

`["gunicorn", "-b", "[0.0.0.0]:5000", "app:app", "-k", "gevent"]`

https://github.com/istio/istio/blob/master/samples/helloworld/src/Dockerfile

**Comment by Nikhil007nsg** [comment]
@Nutties93 same problem i am getting any one have solution for that

**Comment by RamazanBiyik77** [comment]
Check your node security group. There should be UDP 53 rule. DNS communicate over this port and protocol. In my case i added pod security group. I started to get same error. Relaized that my pod security group was not allowed on node security group over udp53. Probably you need to add tcp53 too.
