### ISSUE TITLE
How to set PILOT_ENABLE_MYSQL_FILTER=true in pilot-agent  environment variables?

### ISSUE THREAD

**Issue by EdisonFu** [istio/istio#48352]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

when I set PILOT_ENABLE_MYSQL_FILTER in IstioOperator like this:
```
pilot:
      env:
        PILOT_ENABLE_MYSQL_FILTER: "true"
```
     
and I can see it in istiod Environment.

```
Environment:
      REVISION:                   default
      JWT_POLICY:                 third-party-jwt
      PILOT_CERT_PROVIDER:        istiod
      POD_NAME:                   istiod-ff695f995-tkkbn (v1:metadata.name)
      POD_NAMESPACE:              istio-system (v1:metadata.namespace)
      SERVICE_ACCOUNT:             (v1:spec.serviceAccountName)
      KUBECONFIG:                 /var/run/secrets/remote/config
      PILOT_TRACE_SAMPLING:       100
      PILOT_ENABLE_MYSQL_FILTER:  true
      ISTIOD_ADDR:                istiod.istio-system.svc:15012
      PILOT_ENABLE_ANALYSIS:      false
      CLUSTER_ID:                 Kubernetes
      GOMEMLIMIT:                 node allocatable (limits.memory)
      GOMAXPROCS:                 node allocatable (limits.cpu)
      PLATFORM:      
```             

But I cna't find it in mysql Pod Environment!
```
Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      human-resources-mysql-mysql-0 (v1:metadata.name)
      POD_NAMESPACE:                 human-resources (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      ISTIO_CPU_LIMIT:               2 (limits.cpu)
      PROXY_CONFIG:                  {}
                                     
      ISTIO_META_POD_PORTS:          [
                                         {"name":"mysql","containerPort":3306,"protocol":"TCP"}
                                         ,{"name":"sidecar-http","containerPort":8080,"protocol":"TCP"}
                                         ,{"name":"prometheus","containerPort":9125,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     mysql,sidecar,metrics-exporter,pt-heartbeat,bit
      GOMEMLIMIT:                    1073741824 (limits.memory)
      GOMAXPROCS:                    2 (limits.cpu)
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_NODE_NAME:           (v1:spec.nodeName)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      human-resources-mysql-mysql
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/human-resources/statefulsets/human-resources-mysql-mysql
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
      ISTIO_PROMETHEUS_ANNOTATIONS:  {"scrape":"true","path":"","port":"9125"}
```

I am not sure how do I verify that the configuration is valid?

### Version

```Text
istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (91 proxies)

kubectl version --short
Client Version: v1.26.5
Kustomize Version: v4.5.7
Server Version: v1.26.5
```

**Comment by hzxuzhonghu** [comment]
It is istiod env, definitely not found in agent

**Comment by hanxiaop** [comment]
You can check if the filter is enabled in the configdump.

**Comment by EdisonFu** [comment]
> You can check if the filter is enabled in the configdump.

Thanks!
I have checked,  there is no mysql filter in the configdump. So how should I do to set it in configdump?

**Comment by GregHanson** [comment]
@EdisonFu are the ports in your mysql service [named appropriately](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)?  The `envoy.filters.network.mysql_proxy` filter should appear if the `PILOT_ENABLE_MYSQL_FILTER` feature flag is enabled and `mysql` protocol is detected via matching against the naming conventions linked above

**Comment by EdisonFu** [comment]
@GregHanson 
Is this right?

`  {
            "active_state": {
              "last_updated": "2023-12-13T23:16:58.731Z",
              "listener": {
                "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
                "access_log": [
                  {
                    "filter": {
                      "response_flag_filter": {
                        "flags": [
                          "NR"
                        ]
                      }
                    },
                    "name": "envoy.access_loggers.file",
                    "typed_config": {
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                      "log_format": {
                        "text_format_source": {
                          "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                        }
                      },
                      "path": "/dev/stdout"
                    }
                  }
                ],
                "address": {
                  "socket_address": {
                    "address": "10.30.69.117",
                    "port_value": 3306
                  }
                },
                "bind_to_port": false,
                "continue_on_listener_filters_timeout": true,
                "filter_chains": [
                  {
                    "filters": [
                      {
                        "name": "istio.stats",
                        "typed_config": {
                          "@type": "type.googleapis.com/stats.PluginConfig"
                        }
                      },
                      {
                        "name": "envoy.filters.network.mysql_proxy",
                        "typed_config": {
                          "@type": "type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy",
                          "stat_prefix": "outbound|3306||mysql-have-sidecar-mysql-master.mysql-no-sidecar.svc.cluster.local"
                        }
                      },
                      {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typed_config": {
                          "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                          "access_log": [
                            {
                              "name": "envoy.access_loggers.file",
                              "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                "log_format": {
                                  "text_format_source": {
                                    "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                                  }
                                },
                                "path": "/dev/stdout"
                              }
                            }
                          ],
                          "cluster": "outbound|3306||mysql-have-sidecar-mysql-master.mysql-no-sidecar.svc.cluster.local",
                          "stat_prefix": "outbound|3306||mysql-have-sidecar-mysql-master.mysql-no-sidecar.svc.cluster.local"
                        }
                      }
                    ]
                  }
                ],
                "listener_filters_timeout": "0s",
                "name": "10.30.69.117_3306",
                "traffic_direction": "OUTBOUND"
              },
              "version_info": "2023-12-13T23:16:57Z/58"
            },
            "name": "10.30.69.117_3306"
          },`

**Comment by hanxiaop** [comment]
> @GregHanson Is this right?
> "name": "istio.stats", "typed_config": { "@type": "type.googleapis.com/stats.PluginConfig" } }, { "name": "envoy.filters.network.mysql_proxy", "typed_config": { "@type": "type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy", "stat_prefix": "outbound|3306||mysql-have-sidecar-mysql-master.mysql-no-sidecar.svc.cluster.local" } }, { "name": "envoy.filters.network.tcp_proxy",

Seems correct to me.
