### ISSUE TITLE
Istio operator not installing in the order expected, and also marks CROs in 'ERROR' state forever

### ISSUE THREAD

**Issue by VivekSubr** [istio/istio#48359]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Installed istio using helm install of istio operator deployment and cro.
[istio operator.zip](https://github.com/istio/istio/files/13672138/istio.operator.zip)

This works (There are other resources of course), but we find that it tries to reconcile gateway resources before creating istiod, which of course fails... looking at the code it seems intent was to install istiod first, here operator explicitly appends gateways at the end of an array of components it intends to install ->
https://github.com/istio/istio/blob/master/operator/pkg/controlplane/control_plane.go

```
func NewIstioControlPlane(
	installSpec *v1alpha1.IstioOperatorSpec,
	translator *translate.Translator,
	filter []string,
	ver *version.Info,
) (*IstioControlPlane, error) {
	out := &IstioControlPlane{}
	opts := &component.Options{
		InstallSpec: installSpec,
		Translator:  translator,
		Filter:      sets.New(filter...),
		Version:     ver,
	}
	for _, c := range name.AllCoreComponentNames {
		o := *opts
		ns, err := name.Namespace(c, installSpec)
		if err != nil {
			return nil, err
		}
		o.Namespace = ns
		out.components = append(out.components, component.NewCoreComponent(c, &o))
	}

	if installSpec.Components != nil {
		for idx, c := range installSpec.Components.IngressGateways {
			o := *opts
			o.Namespace = defaultIfEmpty(c.Namespace, iop.Namespace(installSpec))
			out.components = append(out.components, component.NewIngressComponent(c.Name, idx, c, &o))
		}
		for idx, c := range installSpec.Components.EgressGateways {
			o := *opts
			o.Namespace = defaultIfEmpty(c.Namespace, iop.Namespace(installSpec))
			out.components = append(out.components, component.NewEgressComponent(c.Name, idx, c, &o))
		}
	}
	return out, nil
}
```

But it looks like in the actual reconcile loop components are consumed as a map and order is lost? 
https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L152

Also, even though the gateways eventually timeout and once istiod is finally created system is stabilized, resources marked as 'ERROR' due to that timeout are never marked healthy.

```
subramaniamv@dev-subramaniamv:/localdata/subramaniamv/vm-ado_sqa/interface/aksDeployments/deployment$ kc get istioOperator -n fed-smf
NAME                                             REVISION   STATUS        AGE
gateways-egress-fed-smf-0.0.0-1-istio-4-3-0                 RECONCILING   136m
gateways-egress-li-fed-smf-4.3.0-25-rel-4-3-0               HEALTHY       136m
gateways-ingress-fed-smf-0.0.0-1-istio-4-3-0                ERROR         136m
gateways-ingress-li-fed-smf-4.3.0-25-rel-4-3-0              ERROR         136m

2023-12-08T10:56:42.154793Z     info    installer       using server side apply to update obj: Service/fed-smf/istio-egressgateway
- Processing resources for Egress gateways.

Status:
  Component Status:
    Ingress Gateways:
      Error:  failed to wait for resource: resources not ready after 5m0s: context deadline exceeded
  Deployment/fed-smf/istio-ingressgateway (containers with unready status: [istio-proxy])


subramaniamv@dev-subramaniamv:/localdata/subramaniamv/vm-ado_sqa/interface/aksDeployments/deployment$ kc get istioOperator -n fed-smf
NAME                                             REVISION   STATUS   AGE
gateways-egress-fed-smf-0.0.0-1-istio-4-3-0                 ERROR    151m
gateways-egress-li-fed-smf-4.3.0-25-rel-4-3-0               ERROR    151m
gateways-ingress-fed-smf-0.0.0-1-istio-4-3-0                ERROR    151m
gateways-ingress-li-fed-smf-4.3.0-25-rel-4-3-0              ERROR    151m
```

### Version

```Text
subramaniamv@dev-subramaniamv:/localdata/subramaniamv/istio_upgrade$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

We don't install using istioctl, but version is 1.19.0, upgrading from 1.16.1
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/13672036/bug-report.tar.gz)

**Comment by hanxiaop** [comment]
See

https://github.com/istio/istio/blob/ce6d7ba0f5d89e1af735e796748e23d9e8b4a6e0/operator/pkg/helmreconciler/common.go#L63-L78

We do have the installation order dependency for the components.

**Comment by VivekSubr** [comment]
@hanxiaop - but it doesn't seem to be used? Atleast in my helm upgrade I can clearly see it trying to install gateways before istiod

**Comment by hanxiaop** [comment]
> @hanxiaop - but it doesn't seem to be used? Atleast in my helm upgrade I can clearly see it trying to install gateways before istiod

@VivekSubr I think it will wait before installing the gateway - the logic applies to both the operator controller and istioctl. Let me check your bug report to see if there are any clues.

**Comment by hanxiaop** [comment]
@VivekSubr Looks like you have multiple IOPs which lead to the failure? I think for multiple IOPs, the controller doesn't guarantee the order.

**Comment by VivekSubr** [comment]
@hanxiaop , sorry, what is a IOP?

**Comment by hanxiaop** [comment]
> @hanxiaop , sorry, what is a IOP?

It's IstioOperator resources in your cluster.
