### ISSUE TITLE
add additional "source namespace" to http header during forwarding http request

### ISSUE THREAD

**Issue by amankumarcs** [istio/istio#48350]
i have one requirement . 
Suppose k8s serviceA is communicating with serviceB. Is it possible to include the source and destination service names, along with the namespace, in the http request details?

**Comment by hanxiaop** [comment]
If you know the services you can do with https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers. Or if you need dynamic extration you will need to use WASM or envoyfilter to do it.

**Comment by amankumarcs** [comment]
> If you know the services you can do with https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers. Or if you need dynamic extration you will need to use WASM or envoyfilter to do it.

how we can do through envoyfilter or wasm can you share the code .

**Comment by hanxiaop** [comment]
I don't have an example, but you can check these docs https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter , https://github.com/proxy-wasm/proxy-wasm-rust-sdk/tree/master. There will be Istio metadata exchange that you can use.

**Comment by amankumarcs** [comment]
i'm seeing istio attribute https://istio.io/v1.3/docs/reference/config/policy-and-telemetry/attribute-vocabulary/. can i use this attribute such as i can add in headers through istio ? 
My requirement is as follows: I want to include the source and destination service names, along with the namespace, in the HTTP request details when Kubernetes serviceA communicates with serviceB. This is important because I need this information in the OPA sidecar to match policies. I am currently creating a policy that requires this information.

Service A can only communicate with Service B if the request is a POST to /versions. For all other requests, it should be blocked.
