### ISSUE TITLE
Waypoint Sandwich

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#48362]
Implementation plan:

Basic sandwich

- [X] Basic sandwich
  - [X] Inbound forwards to Waypoint instead of HBONE target
  - [X] Outbound from Waypoint doesn't loop
  - [X] Outbound to captured Waypoint uses zTunnel port
- [X] Tell zTunnel inbound to send PROXY (#50235)
  - [X] Allow configuring a specific port and protocol for captured Waypoints (inbound)
- [X] PROXY Protocol Support in zTunnel
- [x] #49562 
- [ ] Reference impl of a PROXY Waypoint in Istio #49097 

---

Opening this issue as a place to discuss and iterate on ideas for sandwiching Waypoint with the zTunnel. 

The basic idea is: handling HBONE with the zTunnel instead of in the Waypoint. Capture traffic for the Waypoint as we do other apps. 

Motivations:

* Simplify the Waypoint's implementation
* Reduce the work required to bringing alternative Waypoint implementations

Some basic requirements in implementing this:

* Propagate metadata for L7 telemetry. We would likely leverage MDS (#43937) if metadata isn't propagated inline. 
* Propagate the identity validated by the zTunnel. This should be signed in some way that the Wyapoint can validate. 
  * Prototyped (not signed)
* Preserve source/destination IP info. 
  * Prototyped: PROXY Proto

**Comment by stevenctl** [comment]
I have a very work in progress prototype that uses PROXY protocol to inform the Waypoint of:

* Source/Destination address (part of PROXY natively)
* Identity. Currently very hacky, just send the spiffe:// with a PROXY TLV header.

The zTunnel will see the TCP connection IP of the waypoint while the CONNECT header contains the actual destination. When these are different and the actual destination has a waypoint, we will send PROXY. This should properly validate these two IPs actually have this association, or rely on a signal from the control plane. 

A custom Envoy filter uses the TLV to set the peer identity. Instead of sending the identity directly, we need something with a verifiable signature. Metadata for telemetry isn't yet handled. 

The control plane changes modify Waypoint xDS to remove the decap listener, and expose what _was_ the internal listener on a port. Eventually we'd like this to be a UNIX socket, and/or secured over (m)TLS. 

https://github.com/stevenctl/proxy/tree/sandwich
https://github.com/stevenctl/ztunnel/tree/sandwich
https://github.com/stevenctl/istio/tree/sandwich

1. Build Envoy (I use the gcr.io/istio-testing/build-tools-proxy image)
2. Build zTunnel
3.Copy binaries to Istio directory for building images.
4. Build images:

```bash
export HUB=localhost:5000 TAG=sandwich
./tools/docker --targets pilot,proxyv2,ztunnel,install-cni --push
```

5. Create cluster with 3 nodes:

```
export KIND_REGISTRY_NAME=kind-registry # this is the stanard istio testing one
kind create cluster --config=- <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ambient
nodes:
- role: control-plane
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://${KIND_REGISTRY_NAME}:5000"]
EOF
```

6. Install Gateway API CRDs

```
 curl -L https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.8.1/experimental-install.yaml | kubectl apply -f -
```


7. Install Istio

```
go run ./istioctl/cmd/istioctl install -y -f $ISTIO/ambient-perf/iop.yaml --set hub=$HUB \
--set tag=$TAG --set values.global.imagePullPolicy=Always --manifests=$ISTIO/manifests
```

8. Enable ambient, deploy waypoint

```
go run ./istioctl/cmd/istioctl x waypoint apply
kubectl label ns default istio.io/dataplane-mode=ambient
```

9. (Optional) Force waypoint onto a specific node

```
kubectl patch deployments.apps namespace-istio-waypoint --type=merge -p='{"spec":{"template":{"spec": {"nodeName": "ambient-control-plane"}}}}'
```

10. Setup apps (using some perf testing stuff for now.. the charts force things onto specific nodes)

```
cd ambient-perf
./install.sh nighthawk
```

11. Run test traffic (could also just exec pods yourself)

```
 CONNECTIONS=1 DURATION=1 ./tests/nighthawk/test.sh
```

12. Apply authz policy and test again (should fail)

```
kubectl apply -f authz.yaml
CONNECTIONS=1 DURATION=1 ./tests/nighthawk/test.sh
```

**Comment by linsun** [comment]
Hi @stevenctl could you update the issue on what has been done?  I think this has been prototyped:

- [x]  Propagate the identity validated by the zTunnel. This should be signed in some way that the Wyapoint can validate.
- [x]  Preserve source/destination IP info.

**Comment by linsun** [comment]
@stevenctl what is the latest on this? I recall the ambient dev team reviewed this 2-3 weeks ago and decided we should go with the proxy protocol approach.

**Comment by stevenctl** [comment]
The biggest open questions are:

* Secure naming. How can the waypoint use it's outbound zTunnel to ensure the remote presents the expected identity.
* Getting metadata from the waypoint ztunnel to the waypoint. WDS is fine, but we might be able to put this into the PROXY headers as well. 
* Post LB metadata: after the Waypoint picks an upstream, how can we get (preferably signed) metadata from the ztunnel back into the waypoint?

**Comment by zengyuxing007** [comment]
> The biggest open questions are:
> 
> * Secure naming. How can the waypoint use it's outbound zTunnel to ensure the remote presents the expected identity.
> * Getting metadata from the waypoint ztunnel to the waypoint. WDS is fine, but we might be able to put this into the PROXY headers as well.
> * Post LB metadata: after the Waypoint picks an upstream, how can we get (preferably signed) metadata from the ztunnel back into the waypoint?

Can you describe the exact network path?   Just in case there is a misunderstanding of the specific realization, thanks .

[ sleep -> ztunnel ]  -> [ **ztunnel** -> waypoint for httpbin ] -> [ ztunnel -> httpbin] ??

**Comment by stevenctl** [comment]
@zengyuxing007 slightly different

[ sleep -> ztunnel ] -> [ ztunnel -> waypoint for httpbin -> **ztunnel again, outbound ** ] -> [ ztunnel **inbound** -> httpbin]

**Comment by stevenctl** [comment]
Current state: 

* Istiod doesn't have any special requirements for which GatewayClasses can be a waypoint. This means anything that supports HTTP can be a waypoint using basic `Host` header routing (see [TestSimpleHTTPSandwich](https://github.com/istio/istio/blob/06d6b174468f14b43b7c56d80366cc5d99f7aa34/tests/integration/ambient/waypoint_test.go#L199)). 
* `ambient.istio.io/waypoint-inbound-binding` on a GatewayClass can override the port that an inbound zTunnel sends to the waypoint it's terminating mTLS on behalf of. (This is how one can enable PROXY protocol to the waypoint.)
* zTunnel supports sending PROXY protocol to the waypoint. It will set the original source and destination addresses, and forward the validated source identity as a TLV header (0xD0)
* See https://gist.github.com/stevenctl/ec2ddae79734f8f9367400961ca9c48f for a sample of PROXY support.

**Comment by stevenctl** [comment]
Whether we add a sandwiched mode to Istio's own Waypoint is yet to be decided.
