### ISSUE TITLE
Istio ingress not able to bind on port 80

### ISSUE THREAD

**Issue by hemendrateli** [istio/istio#48364]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

[This](https://github.com/istio/istio/commit/e4ae5de66f21cfc645e5744300e58bd2ea53d22c#diff-34a675f455a18d4c77afb1cb2bc877a0a77315b3f8dfb8920ddf2f5af96cecb0) change introduced 1337 for runAsGroup and runAsUser for ingress gateway and [45394](https://github.com/istio/istio/pull/45394) was the initial PR. Now root(0) permissions are not there. So we can't bind port < 1024 to ingress now.

it is affecting our internal tests for ingress where we bind to port 80 and also it will affect upgrade for any istio existing customer who is using port 80 or port 443 or any other port < 1024.

We may want to revert this breaking change.

### Version

```Text
master and release-1.20
```

**Comment by hemendrateli** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
I believe specifically this breaks the "Kubernetes YAML" install in https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway, unless you manually set the securityContext. A fix would be to inject
```
65-      securityContext:
66:        sysctls:
67-        - name: net.ipv4.ip_unprivileged_port_start
68-          value: "0"
```

wdyt @jwendell ?

**Comment by jwendell** [comment]
@hemendrateli How are you deploying the gateways?

**Comment by howardjohn** [comment]
> @hemendrateli How are you deploying the gateways?
the "Kubernetes YAML" install in https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway

(I work with Hemendra)

**Comment by jwendell** [comment]
In that case you are overriding `securityContext`, not using what's in the docs, right?

**Comment by howardjohn** [comment]
Oops, didn't know that doc has ip_unprivileged_port_start set! Specifically meant the general concept, I think literally deploying https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/main/samples/gateways/istio-ingressgateway/deployment.yaml.

Problem is anyone upgrading that installed from there (or istio.io prior to https://github.com/istio/istio.io/commit/55bb838ac40f9c29f9df5a3c9ffe9991b63a582b) will be broken.

**Comment by jwendell** [comment]
So, you're suggesting we add `net.ipv4.ip_unprivileged_port_start` sysctl to the template? I'm fine with it.

**Comment by hemendrateli** [comment]
> So, you're suggesting we add `net.ipv4.ip_unprivileged_port_start` sysctl to the template? I'm fine with it.

I think this should do for the fix.

**Comment by howardjohn** [comment]
Yeah I think that is a universally good idea to set, as long as the cluster allows it. AFAIK any k8s 1.22+ does. If any platform didn't, it would probably be OpenShift? So would be good to double check there.

**Comment by hemendrateli** [comment]
@jwendell Gentle reminder on this, please check when you get time.

**Comment by hemendrateli** [comment]
@howardjohn  I have raised https://github.com/istio/istio/pull/48815 to fix this.

**Comment by hemendrateli** [comment]
Closing this issue, fix is implemented in https://github.com/istio/istio/pull/48815

**Comment by jared-schmidt-niceincontact** [comment]
FYI, for future people running into this: when we switched our deployments from default to distroless images (distroless images are required for ambient istio), we had to add this securityConfig to our ingress gateways to make them work as mentioned in the comments above.
```yaml
securityContext:
  sysctls:
    - name: net.ipv4.ip_unprivileged_port_start
      value: "0"
```
