### ISSUE TITLE
Running istio on openshift requires cluster-admin priviledges

### ISSUE THREAD

**Issue by mocenas** [istio/istio#4837]
User needs the cluster-admin priviledges to run istio application on openshift. 
Specifically:
- service account running container requires SCC "priviledged" - allowing this requires cluster-admin priviledges
- creation of RouteRule requires cluster-admin priviledges.

We don't want to give this priviledge to users neither we want containers run in priviledged mode. Can something be done about it?

**Comment by linsun** [comment]
Would like someone from redhat to help drive this.  cc @christian-posta

**Comment by christian-posta** [comment]
cc @knrc @rettori do we have some on openshift team working on this?

**Comment by knrc** [comment]
@christian-posta We are aware of this but don't yet have someone looking at it, I can certainly help to drive it

**Comment by jwendell** [comment]
Related: https://github.com/istio/issues/issues/172

**Comment by nadilas** [comment]
Is there any way around this already?

**Comment by sfudeus** [comment]
Not sure about openshift in detail, but for vanilla k8s with tighter PodSecurityPolicies, this is somewhat resolved by istio-cni. Plainly for deploying pods, there is no need for a initContainer with iptables/net_admin privileges anymore.

**Comment by knrc** [comment]
There are a few issues with elevated privileges which we have addressed in the maistra version - the need for privileged access, support for random UIDs, cluster wide permissions etc.  The CNI plugin should address the init container/privileged issue for applications, our implementation uses Multus as it's an easier integration within the OpenShift, however you will still need cluster wide permissions for the service accounts within the control plane and anyuid scc for and static UIDs.  Some of these are already being addressed in the Istio community and we are working to integrate our soft multi tenancy updates.
