### ISSUE TITLE
Breaking change report - EDS

### ISSUE THREAD

**Issue by kimmikimmi** [istio/istio#48373]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We bumped up istio version from 1.14.3 to 1.20, and observed newly launched pod's ips are not properly resolved by old pods (registered as ServiceEntry).
```
$ kubectl --context pm -n service-ratelimit get pods -o wide
NAME                                        READY   STATUS    RESTARTS   AGE     IP              NODE                                               NOMINATED NODE   READINESS GATES
service-ratelimit-canary-666d66cc75-cmbnw   6/6     Running   0          12m     IPa   ip-....ap-northeast-2.compute.internal    <none>           <none>
service-ratelimit-canary-666d66cc75-vbbc4   6/6     Running   0          2m6s    IPb     ip-....ap-northeast-2.compute.internal    <none>           <none>

$ istioctl --context ph pc endpoint url-shortener-admin-staging-7c8f9d8d5-dmc5z.url-shortener-admin | grep 'IPb'
No result
```

I think this is because of [the change](https://github.com/istio/istio/compare/1.19.3...1.19.4#diff-c6215f1e2a80c0d2afe120f4616972dfb339bcb51e8815cc5e171750bc11ae18R158), from this change, registering IPs from newly launched ip depends on `PILOT_SEND_UNHEALTHY_ENDPOINTS` flag, and this is false by default. 
```
		if oie, exists := emap[nie.Address]; exists {
				// If endpoint exists already, we should push if it's health status changes.
				if oie.HealthStatus != nie.HealthStatus {
					needPush = true
				}
				newIstioEndpoints = append(newIstioEndpoints, nie)
			} else {
				// If the endpoint does not exist in shards that means it is a
				// new endpoint. Always send new endpoints even if they are not healthy.
				// This is OK since we disable panic threshold when SendUnhealthyEndpoints is enabled.
				// Without SendUnhealthyEndpoints we do not need this; headless services will trigger the push in the Kubernetes controller.
				if features.SendUnhealthyEndpoints.Load() {
					needPush = true
				}
				newIstioEndpoints = append(newIstioEndpoints, nie)
			}
```

### Version

```Text
1.20, but happens from 1.19.4
```

### Additional Information
We use ServiceEntry's workloadSelector to discover mapped ip to mesh internal domain.
_No response_

**Comment by minuyim** [comment]
I think this change causes the issue. (It seems that this block might be controlled by feature flag. Isn't it?)
https://github.com/istio/istio/pull/47379/files#diff-ba0ca10dea37bdd27565870e65fdef4c0cba7ba926b206dc0eac80b9fe1ca758R339-R341

**Comment by howardjohn** [comment]
This has been how Istio has always worked. Only Ready pods are sent. PILOT_SEND_UNHEALTHY_ENDPOINTS is a new flag, off by default, to enable _new behavior_

**Comment by freedomljc** [comment]
It could be related to https://github.com/istio/istio/blob/39a52840433f8c7986b846d0a0775d65675e54fc/pilot/pkg/model/endpointshards.go#L320-L326

As [`PILOT_SEND_UNHEALTHY_ENDPOINTS ` is disabled by default](https://github.com/istio/istio/blob/39a52840433f8c7986b846d0a0775d65675e54fc/pilot/pkg/features/pilot.go#L99-L105), it would cause to not send push for new endpoint update unless `PILOT_SEND_UNHEALTHY_ENDPOINTS ` is set to true. I'm not sure whether the headless service matters or not, but we observed that new ready endpoints are unable to propagate to envoy proxy when `PILOT_SEND_UNHEALTHY_ENDPOINTS ` is set as false.

**Comment by howardjohn** [comment]
If its a headless service, EDS is not used at all.

if what you are saying was the case (new ready endpoints are unable to propagate to envoy proxy) I would imagine Istio would be broken for all users... can you give reproduction steps?

**Comment by minuyim** [comment]
With book-info deployment
```
 ✘ miyim  ~/workspace/istioctl  cat test.yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-dns
spec:
  hosts:
    - ratings.org
  location: MESH_INTERNAL
  ports:
    - name: HTTP-9080
      number: 9080
      protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings

 miyim  ~/workspace/istioctl  kubectl apply -f test.yaml
serviceentry.networking.istio.io/test-dns configured
 miyim  ~/workspace/istioctl  istioctl pc endpoint productpage-v1-864d54b6c8-tcr9h | grep "rating"
10.244.0.23:9080                                        HEALTHY     OK                outbound|9080||ratings.default.svc.cluster.local
10.244.0.23:9080                                        HEALTHY     OK                outbound|9080||ratings.org
10.244.0.24:9080                                        HEALTHY     OK                outbound|9080||ratings.default.svc.cluster.local
10.244.0.24:9080                                        HEALTHY     OK                outbound|9080||ratings.org
 miyim  ~/workspace/istioctl  kubectl delete pod ratings-v1-698fdc88f4-c686k
pod "ratings-v1-698fdc88f4-c686k" deleted
 miyim  ~/workspace/istioctl  istioctl pc endpoint productpage-v1-864d54b6c8-tcr9h | grep "rating"
10.244.0.24:9080                                        HEALTHY     OK                outbound|9080||ratings.default.svc.cluster.local
10.244.0.24:9080                                        HEALTHY     OK                outbound|9080||ratings.org
10.244.0.25:9080                                        HEALTHY     OK                outbound|9080||ratings.default.svc.cluster.local
```

**Comment by howardjohn** [comment]
thanks, missed the serviceentry aspect originally

**Comment by ikersuen** [comment]
what will be the functional impact if we do not upgrade to latest version for this change? May advice the severity level if we don't upgrade for this bugfix in production?

currently using version: 1.20.1

**Comment by howardjohn** [comment]
In some edge cases when using SE endpoints will not be sent to proxies
