### ISSUE TITLE
Verification for ambient dynamic onboard/offboard workloads

### ISSUE THREAD

**Issue by linsun** [istio/istio#48386]
[P0] Dynamic onboarding - enable Ambient without restarting workload
[P0] Offboarding

A few scenarios we should consider:

- workload pods are deployed before ambient label is added -> enroll in ambient without restart workload pods  --> successful
- pods are deployed after ambient label is added. -> enroll in ambient without restart workload pods  --> successful 
- ambient label is removed, workload pods are off ambient without any restart.  -> successful

It would be great if we can have some automated tests for this - we might already have some, as we'll need this work for every single build. :)

**Comment by linsun** [comment]
This Iris! It would be great if we can have some automated tests for this - we might already have some, as we'll need this work for every single build. :)

**Comment by irisdingbj** [comment]
tried manually: 
workload pods are deployed before ambient label is added -> enroll in ambient without restart workload pods --> successful
pods are deployed after ambient label is added. -> enroll in ambient without restart workload pods --> successful
ambient label is removed, workload pods are off ambient without any restart. -> successful

**Comment by bleggett** [comment]
I think we have the above scenarios covered now, which is excellent.

**Comment by irisdingbj** [comment]
Yep, let's close this issue.

**Comment by linsun** [comment]
Awesome, thank you @irisdingbj and @bleggett !

**Comment by dhawton** [comment]
Reopening as the PR was reverted.

**Comment by dhawton** [comment]
@linsun since this was reverted, is this still needed?

**Comment by howardjohn** [comment]
We have a test for service restart, we can do the exact same thing but onboard/offboard
