### ISSUE TITLE
Envoy version pointing to envoy dev branch in istio 1.19.4

### ISSUE THREAD

**Issue by parshva-shah-dsw** [istio/istio#48380]
### Bug Description

<img width="769" alt="image" src="https://github.com/istio/istio/assets/117802398/2766183f-bb2d-434a-80f4-850c29232959">

After upgrading istio from 1.18.5 to 1.19.4 the envoy proxy version is pointing to 1.27.3-dev

as per istio 1.19.x it should be mapped to 1.27.x and latest stable envoy is 1.27.2 https://github.com/envoyproxy/envoy/releases
<img width="551" alt="image" src="https://github.com/istio/istio/assets/117802398/9e9003bc-31f4-4a99-9e6f-1ab338067f50">

Can anyone help here to fix using stable envoy version 1.27.2 while installing istio 1.19.4 or higher version

### Version

```Text
istioctl version
client version: 1.19.4
control plane version: 1.19.4
data plane version: 1.18.5 (10 proxies), 1.19.4 (3 proxies)
```

**Comment by zirain** [comment]
istio does not use upstream releases directly, we build our release with istio's extensions.

**Comment by howardjohn** [comment]
+1, see https://github.com/istio/istio/discussions/48064#discussioncomment-7794044

**Comment by zirain** [comment]
Never mind, it already has, except that the css issue doesn't look like a link.
