### ISSUE TITLE
Enforcement in code to allow users to selectively enable alpha features

### ISSUE THREAD

**Issue by linsun** [istio/istio#48384]
[P0] Create a development process and enforcement mechanism in code to selectively enable alpha Ambient features. (John + Keith)
[P0] Feature/API surface reduction (John + Keith)
When we ship beta, we should not ship "The kitchen sink of Istio features, and some subset is beta that we hopefully correctly documented, and you read the docs, and never accidentally used any feature outside of beta". We should explicitly disable beta features, so a user can reasonably use only beta features.

**Comment by linsun** [comment]
@keithmattix @howardjohn is this still planned for the initial beta?

**Comment by howardjohn** [comment]
Its not really something that makes sense to defer IMO. Either we do it for beta or not,

IMO its still important, as without it it will be impossible for users to actually use "ambient beta" without accidentally using "ambient alpha"

**Comment by linsun** [comment]
No objection for beta - just wanted to make sure we have you or Keith planned for it in the next month or so, or we have to find someone else working on it.

**Comment by linsun** [comment]
@keithmattix @howardjohn said he doesn't have plan to implement this.  Is this something you could pick up or should I ask other contributors for help?

**Comment by keithmattix** [comment]
Yeah I don't have bandwidth to take this on either unfortunately

**Comment by bryceadams1** [comment]
I'd like to pick this one up if it can be assigned to me.

**Comment by whitneygriffith** [comment]
JFYI: The [Release Channels](https://docs.google.com/document/d/1onST4-swbZE1UPCDMQm1c7T5rzYEn7Wo4uFNShz0kNw/edit#heading=h.etg0r5aslvgp) concept can be leveraged here.

**Comment by linsun** [comment]
@bryceadams1 - do you still want us to assign this to you?

**Comment by bryceadams1** [comment]
@linsun yes you can assign it to me

**Comment by linsun** [comment]
Thanks @bryceadams1! I'd recommend you discussing in here and also next ambient meeting on how you plan to support this to socialize your thoughts.
