### ISSUE TITLE
Ambient upgrade automated testing

### ISSUE THREAD

**Issue by linsun** [istio/istio#48388]
[P0] Minimal downtime upgrade testing, L4 only first.

**Comment by linsun** [comment]
Hi @kfaseela this could be a small one to pick up if you have bandwidth.

**Comment by linsun** [comment]
I think we'll start with in place upgrade for ztunnel first, potentially using node cordon.  Basically update it as a k8s daemonset. No existing docs afaik.

Istiod update should be same as today, either in place or revision based.  I recall there are some existing upgrade tests already: for example helm_upgrade_test.go

**Comment by kfaseela** [comment]
@linsun : @howardjohn was indicating that the upgrade strategy is not completely finalized. Would it be too early to pick up this automation task?

**Comment by bleggett** [comment]
@kfaseela I've started an ambient Helm upgrade guide for in-place upgrade here: https://github.com/istio/istio.io/pull/14491

While we may do something fancier/more automated later, this is a baseline that should always work, and if you want to write the tests we can at least start there.

**Comment by kfaseela** [comment]
> @kfaseela I've started an ambient Helm upgrade guide for in-place upgrade here: [istio/istio.io#14491](https://github.com/istio/istio.io/pull/14491)
> 
> While we may do something fancier/more automated later, this is a baseline that should always work, and if you want to grab this ticket and write the tests we can at least start there.

Thanks! Will take a look!

**Comment by linsun** [comment]
Sounds a good plan!  Thanks @bleggett and @kfaseela!

**Comment by kfaseela** [comment]
@linsun not sure if we want to close this with just helm tests. Feel free to reopen if you think other upgrade paths also need to be tested
