### ISSUE TITLE
Update istio.io homepage to reflect ambient

### ISSUE THREAD

**Issue by linsun** [istio/istio#48394]

**Comment by linsun** [comment]
cc @craigbox and @Nadine2016 who may be able to help

**Comment by craigbox** [comment]
Current thoughts are:

* for 1.21, update the [homepage](https://docs.google.com/document/d/1azWlg27vZoH5eVtu7JVnEc3NeXFcIXpFUbCLF7TNx5E/edit), [about service mesh](https://docs.google.com/document/d/1aQFXHsGBJqILASQMbkqpLOAes3-iEyWQBZ2Wxy1bNEg/edit#heading=h.aqvia911gdpt) page, and add a deployment modes page which talks about ambient.
* for 1.22, full site redesign with thorough docs content

**Comment by howardjohn** [comment]
@craigbox I think this is considered done?

**Comment by craigbox** [comment]
yarp
