### ISSUE TITLE
Our L4 ambient doc needs to be updated per latest inpod redirection contribution

### ISSUE THREAD

**Issue by linsun** [istio/istio#48392]
cc @srampal if you have bandwidth, before i mark it as community help needed. :)

**Comment by srampal** [comment]
@linsun yes I can do this, feel free to assign

**Comment by linsun** [comment]
Done, thank you!! :)

**Comment by linsun** [comment]
Hi @srampal do you have bandwidth to work on this?  The in-pod is already merged in 1.21 beta1.

**Comment by srampal** [comment]
> Hi @srampal do you have bandwidth to work on this? Or should i ask others to help out? The in-pod is already merged in 1.21 beta1.

Yes I do .. will put out a PR soon with some doc updates.

**Comment by srampal** [comment]
PR in progress for this issue ...
https://github.com/istio/istio.io/pull/14611

**Comment by linsun** [comment]
I saw https://github.com/istio/istio.io/pull/14611 merged - thank you!! Anything remaining or should we close this out @srampal?

**Comment by srampal** [comment]
Completed
