### ISSUE TITLE
ibm test tests more than e2e or prow

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#484]
I was under the impression that the IBM tests were a subset of the jenkins e2e tests yet the ibm test found a bug in https://github.com/istio/istio/pull/481 while e2e nor prow did

ps: initially thought it's a k8s version difference but it apparently is not

**Comment by ldemailly** [comment]
![screen shot 2017-07-20 at 2 09 34 pm](https://user-images.githubusercontent.com/3664595/28440180-0c89bbee-6d5a-11e7-9c8c-90335620567f.png)

**Comment by ldemailly** [comment]
IBM log: http://169.50.62.220:32622/job/istio-armada-release-test/161/console
```
#################################
Deploying ISTIO
#################################

service "istio-egress" created
serviceaccount "istio-egress-service-account" created
service "istio-ingress" created
serviceaccount "istio-ingress-service-account" created
deployment "istio-ingress" created
configmap "istio-mixer" created
service "istio-mixer" created
deployment "istio-mixer" created
configmap "istio" created
service "istio-pilot" created
serviceaccount "istio-pilot-service-account" created
deployment "istio-pilot" created
error: yaml: line 13: did not find expected key
/home/jenkins/workspace/istio-armada-release-test/tests/kubeUtils.sh: line 41: Failed to create control plane (exit 1)
```
Prow log:
https://storage.googleapis.com/istio-prow/pull/istio_istio/481/istio-presubmit/62/build-log.txt
jenkins:
https://testing.istio.io/job/istio/job/presubmit/834/console

**Comment by sebastienvas** [comment]
Please create a valid issue stating what test needs to be added.

**Comment by ldemailly** [comment]
from doing a search:

https://github.com/istio/istio/blob/c2208fe77b23d9f764d9ad38182b3461874ef141/tests/kubeUtils.sh#L39

**Comment by sebastienvas** [comment]
I stiil don t understand the issue. This test was trying to deploy istio and it failed. What s not covered in the e2e ? btw, this test is deprecated.

**Comment by ldemailly** [comment]
the 'deprecated' test is good because it caught a bug - we need to make sure e2e also tries to deploy yaml and also fails if the yaml has a bug like it did

**Comment by sebastienvas** [comment]
The e2e does not use egress. 
 This updates changed the shell withtout updating the framework https://github.com/istio/istio/commit/957e535525116daa50536150e6b8b12b6937ec6c

 @yutongz is currenlty working on using the generated file instead of using the template (which use the full config). This will have better coverage as we'll test more envs.

**Comment by sebastienvas** [comment]
@yutongz please close this once your worked is done.
