### ISSUE TITLE
Add Documentation for network/system requirements for east-west gateway.

### ISSUE THREAD

**Issue by cccsss01** [istio/istio#48401]
**Describe the feature request**
Add documentation for system/network requirements for east-west gateway
**Describe alternatives you've considered**
Trouble shooting what it is actually doing /requiring for network traffic between the gateways.
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ X] Docs
[ ] Dual Stack
[X ] Installation
[X ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X ] Multi Cluster
[X ] Virtual Machine
[ X] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
What documentation do you think is missing? https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/#requirements already documents this, so it would be good to understand why that is not sufficient

**Comment by cccsss01** [comment]
I need ports/system requirements.  In all of the examples it shows public cloud solutions which provide capability to use load balancer, the example for a dev environment show how to use metalLB, which we wouldn't use for production.  So for a prod environment with an internal load balancer.  I need to know how the communication/networking works.  As that's not too clear.

**Comment by cccsss01** [comment]
Then for load balancing between services, what is required for cluster 1 and cluster 2?  Is this 15021,15017, 15012 inbound and outbound between the clusters?

**Comment by cccsss01** [comment]
Additionally the Virtual service requires FQDN for EXTERNAL_ISTIOD_ADDR.

**Comment by cccsss01** [comment]
Also, i believe ipv6 is required for helloworld v2

**Comment by cccsss01** [comment]
Also, I believe there is an ipv6 requirement for hellow world v2.
which i think is looking for ipv6?
<img width="129" alt="image" src="https://github.com/istio/istio/assets/56396984/06abfaa1-d00d-4f8c-bf9e-f887b2d684b8">
