### ISSUE TITLE
Add support for exiting proxy when there are zero active requests

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#48409]
## Description

The past week, we encountered an issue where requests were being routed to a terminating pod. This problem was observed in one of our application (`http1.1`) that required support for long-running requests lasting around 30 minutes. To accommodate this, we configured a high `terminationDrainDuration` and `drainDuration` through proxyConfig. Additionally, we set the [EXIT_ON_ZERO_ACTIVE_CONNECTIONS](https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars) environment variable to ensure that the proxy terminates when there are no active connections.

It's worth noting that we are using the default max connection duration and idleTimeout, which means that connections to the destination proxy are long-running.

In a regular scenario where a Kubernetes service object is the envoy cluster and the endpoints are the Pod IPs, all these configurations work well. As expected, all active connections (requests made through `*.svc.cluster.local`) to the upstream proxy without any active requests are closed, and eventually, the proxy terminates after serving any in-flight request.

However, in our specific scenario, we have a `ServiceEntry` pointing to the K8s service. This means that the cluster is the `ServiceEntry` host name, and the endpoint is the Kubernetes service. In this case, we observed that the long-running connections persist even though they are not serving any requests.

The `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` setting is not helpful in this situation, as these connections are considered active.

Since the client proxy still maintains a connection to the upstream terminating pod, it continues to send requests to it. As a result, the upstream proxy returns a 503 response with the `connection: close` header. The client then closes the connection, and if a retry is configured, it may succeed, unless the request is routed to another terminating pod.

## Mitigation

Setup a retry on the client proxy through a VirtualService and use a less aggressive rollout strategy so that fewer pods are taken out of rotation. 

This works but there are a few concerns

1. With each subsequent retry, the latency increases.
2. Because of a less aggressive rollout strategy, the deployment time for the service is longer.

## Possible Solutions

Unfortunately, the `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` flag does not function as expected when using `ServiceEntry`. Long-running connections remain open until the upstream terminates after the `terminationDrainDuration` expires. We have observed that when the pod starts to terminate, the log continues to report the message `There are still X active connections`. The `netstat` command on the proxy containers also shows the same number of connections on port `15006`.

To address this issue, in addition to the `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` environment flag, we could introduce another variable called `EXIT_ON_ZERO_ACTIVE_REQUESTS` and monitor the `downstream_rq_active` stats. This way, when the proxy starts to terminate, it will wait for any in-flight requests to complete before closing all open active connections.

## Steps to Reproduce
https://github.com/shriramsharma/istio-long-running-connection/blob/main/README.md

**Comment by howardjohn** [comment]
Hmm.. The root cause of this is you do not have proper load balancing due to pointing to a Service VIP as an endpoint. Are you sure you need or want to do this?

Additionally, a proper fix is in https://istio.io/latest/blog/2023/native-sidecars/

EXIT_ON_ZERO_ACTIVE_CONNECTIONS is already very complex, and not correct (race conditions, etc). I don't know a feasible way to actually implement the request based one, nor does it seem desirable given all the factors involved here (downstream_rq_active is not global, so its hard to query)

**Comment by shriramsharma** [comment]
> Hmm.. The root cause of this is you do not have proper load balancing due to pointing to a Service VIP as an endpoint. Are you sure you need or want to do this?

@howardjohn regarding the above question, we use [admiral](https://github.com/istio-ecosystem/admiral) to orchestrate our cross cluster service discovery and communication on mesh which in turn uses ServiceEntry as an abtsracted and uniform
interface for client applications to communicate to their upstreams.

> Additionally, a proper fix is in https://istio.io/latest/blog/2023/native-sidecars/

This will be a great feature but unfortunately, 1.28 adoption will be a long and slow process for us.

> EXIT_ON_ZERO_ACTIVE_CONNECTIONS is already very complex, and not correct (race conditions, etc). I don't know a feasible way to actually implement the request based one, nor does it seem desirable given all the factors involved here (downstream_rq_active is not global, so its hard to query)

EXIT_ON_ZERO_ACTIVE_REQUEST will be an optional environment variable, similar to EXIT_ON_ZERO_ACTIVE_CONNECTIONS. We need to document that the downstream_rq_active metrics must be made available for this feature to work. While this is not a foolproof solution, it can be useful in scenarios where long-running connections are left open because they are considered active due to which `EXIT_ON_ZERO_ACTIVE_CONNECTIONS` flag does not seem to help.

**Comment by howardjohn** [comment]
> regarding the above question, we use [admiral](https://github.com/istio-ecosystem/admiral) to orchestrate our cross cluster service discovery and communication on mesh which in turn uses ServiceEntry as an abtsracted and uniform
> interface for client applications to communicate to their upstreams.

Am I understanding right that Admiral makes all requests go to Service VIPs instead of underlying endpoint? Is this intended? it breaks a ton of features
