### ISSUE TITLE
When using Istio CNI, recent GKE versions, and oslogin: pod startup delayed by 40-60s

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48416]
A bug occurs in the combination of many things at once:

* Istio CNI plugin is used
* GKE is new enough to have a recent GKE Metadata Server, which is more restrictive
* oslogin is enabled in GCE

With this setup, all pods will take ~60s to startup.

The root cause is a bad interaction between these causing a circular dependency. When a pod starts, istio-cni will be invoked. At this point, the `Pod` is created but not containers are running yet. `istio-cni` more or less calls `nsenter <POD> -- iptables-restore`. Our iptables commands use the xt_owner module (`-m owner`) which in turn calls `getpwnam` (https://git.netfilter.org/iptables/tree/extensions/libxt_owner.c#n150). This triggers PAM for authentication. When OSLogin is enabled on the GCE machine, a PAM module will be loaded: https://github.com/GoogleCloudPlatform/guest-oslogin. When triggered, this will call the metadata server (request like `/computeMetadata/v1/oslogin/users?username=...`).

The GKE Metadata Server will detect this as a request coming from the pod. The pod, however, has not yet started, so the request is denied. The PAM module will [retry](https://github.com/GoogleCloudPlatform/guest-oslogin/blob/a2a250b02af56e161d57fbdae1941b21250c8eb9/src/oslogin_utils.cc#L429) this request a number of times before giving up. Once it gives up, execution can continue as usual.

This impacts all Istio versions, but only recent GKE versions (later patch releases in GKE 1.25+). It does not impact Autopilot, which cannot use oslogin.

**Comment by taisph** [comment]
Just for info: I think we're facing this issue on Istio 1.17 as our GKE was recently upgraded to 1.25 and we're suddenly seeing a lot of xtables lock issues causing pod sandbox creation to fail during deployments. We'll try to schedule an upgrade to 1.18.
