### ISSUE TITLE
adsc: inconsistency with Envoy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48414]
https://github.com/istio/istio/blob/f33730b153a6b315eb7cdf351c4a6b9dacbc3ea8/pkg/adsc/adsc.go#L933

adsc: We request LDS on each EDS until we receive RDS

Envoy: not 100% sure, but I think request CDS and then LDS, regardless of eds. Or at least, only request LDS once

In adsc, if we don't ever subscribe to routes at all then we end up doing tons of LDS requests. TestEDSUnhealthyEndpoints is an example that triggers this.

**Comment by jessicegao** [comment]
Is this complete, i want to have a try in my spare time

**Comment by howardjohn** [comment]
I don't think this was ever worked on
