### ISSUE TITLE
Ask about version range when using canary upgrade 

### ISSUE THREAD

**Issue by vietwow** [istio/istio#48428]
Hi everybody,

In the official upgrade guide (https://istio.io/latest/docs/setup/upgrade/), it said that :

> Upgrading across more than two minor versions (e.g., 1.6.x to 1.9.x) in one step is not officially tested or recommended.

But I would clarify if this is only true for In-place Upgrade or this is true for both In-place Upgrade Canary?

The reason I would ask this is my Istio version is far away from the latest version. So It would helpful for us if we could do 1 time upgrade for greater than 2 versions.

Thank you so much.

Best Regards,

**Comment by zirain** [comment]
I think the limition for the canary upgrade will be more lenient in real world, but it also depend on how you use istio.

**Comment by vietwow** [comment]
@zirain thank you for your reply, could you please describe more? Because, I assume that detailed upgrade steps will be depend on how I use Istio, but my question is just about "Is it ok to use canary upgrade mechanism to upgrade more than 2 versions gap (eg from 1.11 to 1.15) ?"

**Comment by zirain** [comment]
In most of case, it's OK to do that upgrading.
In case you have some special case of usage, e.g. some EnvoyFilter may not working on a newer version.

**Comment by vietwow** [comment]
@zirain Oh, I got it, yes I am assuming that I will need to handle any breaking changes like the normal upgrade process. Thank you so much for your confirmation.

**Comment by howardjohn** [comment]
for in place, anything more than 1 by 1 will break. With canary 2 is officially supported and tested but in practice more tends to work. We have done 10+ versions skipped
