### ISSUE TITLE
Add queue to run ambient index events handler async

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48429]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The event handler now is called synchronously within `ResourceEventHandlerFuncs` could take much longer time compared to other controller implement. 

The best practice is not to block the ResourceEventHandlerFuncs too long, otherwise we could miss events. As the k8s list watch mechanism.

cc @howardjohn 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by sword-jin** [comment]
I am curious how to know current synchronous operation takes to much time, I don't see any metrics in ambient.

**Comment by hzxuzhonghu** [comment]
It is relatively much time. In a word, this is not the recommended implement way

**Comment by sword-jin** [comment]
> It is relatively much time. In a word, this is not the recommended implement way

I see, other controllers are using ResourceEventHandlerFuncs in istio, can you specify a best pratice usage which we can follow, thank you.

**Comment by hzxuzhonghu** [comment]
Yeah, refer to pilot/pkg/serviceregistry/kube/controller/controller.go#L521 `registerHandlers`, we enqueue the object that need to be processed. And then process it async, so wono't block the event handler caller, which is the client-go undelying processor
