### ISSUE TITLE
Datadog tracing issue where Datadog’s “operation name” field would contain what should be in the “resource name” field.

### ISSUE THREAD

**Issue by parshva-shah-dsw** [istio/istio#48433]
### Bug Description

The above mentioned bug was fixed in envoy version 1.26.6 :-
https://www.envoyproxy.io/docs/envoy/v1.26.6/version_history/v1.26/v1.26.6

Current envoy version is 1.27.3-dev when istio 1.19.4 is installed 
![image](https://github.com/istio/istio/assets/117802398/d13efcbd-9de9-4120-8098-b584ea4e708d)

As per release notes of 1.26.6 envoy version the bug is fixed yet we are facing the issue when istio is upgraded to 1.19.4 and envoy 1.27.3-dev.

Can anyone help here ? @howardjohn https://github.com/istio/istio/discussions/48064#discussioncomment-7794044 as we understand the envoy versions are build and managed by istio team itself. 

### Version

```Text
istioctl version
client version: 1.19.4
control plane version: 1.19.4
data plane version: 1.18.5 (10 proxies), 1.19.4 (3 proxies)
```

**Comment by zirain** [comment]
I'm not sure what happen(maybe there is something wrong with backport's process), but can you try with 1.19.5?

**Comment by parshva-shah-dsw** [comment]
After upgrading to istio 1.19.5 resource name value has been changed to istio-virtual service name whereas in istio version 1.18.5 resource name value was with the kubernetes service name. 
In 1.18.5 the resource name pattern :- "abc-svc.namespace.svc.cluster.local:8080/api"
In 1.19.5 the resource name pattern :- "app-istio-virtualservice:443/abc/*"

**Comment by zirain** [comment]
I cannot recall anything related this, could you share the configuration, `istioctl pc l` and `istioctl pc b` .

**Comment by parshva-shah-dsw** [comment]
found similar issue with envoy https://github.com/envoyproxy/envoy/issues/30235 @zirain @howardjohn  any idea is it fixed ?

**Comment by zirain** [comment]
@parshva-shah-dsw can you try with the latest version?

**Comment by parshva-shah-dsw** [comment]
@zirain 1.20.1/1.20.2 which one should we try?
