### ISSUE TITLE
Unable to install istio with Helm on docker for mac running Kubernetes

### ISSUE THREAD

**Issue by JCzz** [istio/istio#4847]
Hi

Setup:
Docker for mac running Kubernetes: `Version 18.04.0-ce-rc2-mac61 (23890)`

Installing istio with Helm gives the following error:
`helm install -f install/kubernetes/helm/istio `                     
  
`Error: Get https://localhost:6443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc."
`

**Comment by ayj** [comment]
Possibly related to https://github.com/kubernetes/ingress-nginx/issues/2188

**Comment by louiscryan** [comment]
Not stale
