### ISSUE TITLE
TestDashboards and TestDashboards/Mixer failed in release tests

### ISSUE THREAD

**Issue by hklai** [istio/istio#4848]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/510/daily-e2e-rbac-auth-default/461/

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/510/daily-e2e-rbac-auth/453/

Both looked green before but started failing today, and they blocked the daily release.

The recent postsubmit run was green however.
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1386/

So they may very well be flaky.

**Comment by linsun** [comment]
same as #4842?

**Comment by hklai** [comment]
Indeed. Thanks @linsun 
Moved the info over and closing this.
