### ISSUE TITLE
failed to create a pytorch container for using Kubeflow UI

### ISSUE THREAD

**Issue by HeaseoChung** [istio/istio#48499]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am fine to create Notebook for Scipy but I am failing to create Notebook for pytorch-gpu using Kubeflow UI.

Error mesages:
Error: failed to start container "test-custom-pytorch-gpu": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "240000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4e630563-2ef5-43bd-a0db-cb29606ca3c7/test-custom-pytorch-gpu/cpu.cfs_quota_us: invalid argument: unknown

$ kubectl describe pod -n kubeflow-user-example-com test-custom-pytorch-gpu-0
Name:             test-custom-pytorch-gpu-0
Namespace:        kubeflow-user-example-com
Priority:         0
Service Account:  default-editor
Node:             minikube/192.168.67.2
Start Time:       Thu, 21 Dec 2023 05:56:09 +0000
Labels:           app=test-custom-pytorch-gpu
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=test-custom-pytorch-gpu-5bf776879f
                  notebook-name=test-custom-pytorch-gpu
                  security.istio.io/tlsMode=istio
                  service.istio.io/canonical-name=test-custom-pytorch-gpu
                  service.istio.io/canonical-revision=latest
                  statefulset=test-custom-pytorch-gpu
                  statefulset.kubernetes.io/pod-name=test-custom-pytorch-gpu-0
Annotations:      kubectl.kubernetes.io/default-container: test-custom-pytorch-gpu
                  kubectl.kubernetes.io/default-logs-container: test-custom-pytorch-gpu
                  prometheus.io/path: /stats/prometheus
                  prometheus.io/port: 15020
                  prometheus.io/scrape: true
                  sidecar.istio.io/status:
                    {"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-env...
Status:           Running
IP:               10.244.0.65
IPs:
  IP:           10.244.0.65
Controlled By:  StatefulSet/test-custom-pytorch-gpu
Init Containers:
  istio-init:
    Container ID:  docker://44b9605bc384efcc8964a52ce00ca81d96b8afefc3e8f44eb5edda5a9ac218a4
    Image:         docker.io/istio/proxyv2:1.17.5
    Image ID:      docker-pullable://istio/proxyv2@sha256:101201e7ebae599d1c95191c51ca1daccf0b5eedb96b0f5f6e1a00abe0d1b31e
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15090,15021,15020
      --log_output_level=default:info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 21 Dec 2023 05:56:10 +0000
      Finished:     Thu, 21 Dec 2023 05:56:10 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s4n29 (ro)
Containers:
  test-custom-pytorch-gpu:
    Container ID:   docker://eb3dffe271f4c740f1c046ccdf139cd3e9ed102406ae3a285a642fd517f07415
    Image:          nvcr.io/nvidia/pytorch:22.08-py3
    Image ID:       docker-pullable://nvcr.io/nvidia/pytorch@sha256:1aa83e1a13f756f31dabf82bc5a3c4f30ba423847cb230ce8c515f3add88b262
    Port:           8888/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "240000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4e630563-2ef5-43bd-a0db-cb29606ca3c7/eb3dffe271f4c740f1c046ccdf139cd3e9ed102406ae3a285a642fd517f07415/cpu.cfs_quota_us: invalid argument: unknown
      Exit Code:    128
      Started:      Thu, 21 Dec 2023 06:10:26 +0000
      Finished:     Thu, 21 Dec 2023 06:10:26 +0000
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:             2400m
      memory:          5153960755200m
      nvidia.com/gpu:  1
    Requests:
      cpu:             2
      memory:          4Gi
      nvidia.com/gpu:  1
    Environment:
      NB_PREFIX:  /notebook/kubeflow-user-example-com/test-custom-pytorch-gpu
    Mounts:
      /dev/shm from dshm (rw)
      /home/jovyan from test-custom-pytorch-gpu-workspace (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s4n29 (ro)
  istio-proxy:
    Container ID:  docker://45ccfc0aabfd3fc01eb1fdcca5bc67853b4c1975c48d7f25733dad7adf848af2
    Image:         docker.io/istio/proxyv2:1.17.5
    Image ID:      docker-pullable://istio/proxyv2@sha256:101201e7ebae599d1c95191c51ca1daccf0b5eedb96b0f5f6e1a00abe0d1b31e
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
      --concurrency
      2
    State:          Running
      Started:      Thu, 21 Dec 2023 06:10:13 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=3s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      test-custom-pytorch-gpu-0 (v1:metadata.name)
      POD_NAMESPACE:                 kubeflow-user-example-com (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      PROXY_CONFIG:                  {"tracing":{}}
                                     
      ISTIO_META_POD_PORTS:          [
                                         {"name":"notebook-port","containerPort":8888,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     test-custom-pytorch-gpu
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_NODE_NAME:           (v1:spec.nodeName)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      test-custom-pytorch-gpu
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/kubeflow-user-example-com/statefulsets/test-custom-pytorch-gpu
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/credential-uds from credential-socket (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s4n29 (ro)
      /var/run/secrets/tokens from istio-token (rw)
      /var/run/secrets/workload-spiffe-credentials from workload-certs (rw)
      /var/run/secrets/workload-spiffe-uds from workload-socket (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  workload-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  credential-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  workload-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  test-custom-pytorch-gpu-workspace:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-custom-pytorch-gpu-workspace
    ReadOnly:   false
  kube-api-access-s4n29:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15m                default-scheduler  Successfully assigned kubeflow-user-example-com/test-custom-pytorch-gpu-0 to minikube
  Normal   Pulled     15m                kubelet            Container image "docker.io/istio/proxyv2:1.17.5" already present on machine
  Normal   Created    15m                kubelet            Created container istio-init
  Normal   Started    15m                kubelet            Started container istio-init
  Normal   Pulling    14m                kubelet            Pulling image "nvcr.io/nvidia/pytorch:22.08-py3"
  Normal   Pulled     58s                kubelet            Container image "docker.io/istio/proxyv2:1.17.5" already present on machine
  Normal   Pulled     58s                kubelet            Successfully pulled image "nvcr.io/nvidia/pytorch:22.08-py3" in 14m0.238s (14m0.238s including waiting)
  Normal   Created    57s                kubelet            Created container istio-proxy
  Normal   Started    57s                kubelet            Started container istio-proxy
  Warning  BackOff    27s (x4 over 56s)  kubelet            Back-off restarting failed container test-custom-pytorch-gpu in pod test-custom-pytorch-gpu-0_kubeflow-user-example-com(4e630563-2ef5-43bd-a0db-cb29606ca3c7)
  Normal   Created    15s (x4 over 58s)  kubelet            Created container test-custom-pytorch-gpu
  Normal   Pulled     15s (x3 over 57s)  kubelet            Container image "nvcr.io/nvidia/pytorch:22.08-py3" already present on machine
  Warning  Failed     14s (x4 over 58s)  kubelet            Error: failed to start container "test-custom-pytorch-gpu": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "240000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod4e630563-2ef5-43bd-a0db-cb29606ca3c7/test-custom-pytorch-gpu/cpu.cfs_quota_us: invalid argument: unknown

### Version

```Text
Client Version: v1.29.0
Server Version: v1.28.3
```

**Comment by zirain** [comment]
is this a issue about Kubeflow or istio?

**Comment by HeaseoChung** [comment]
> is this an issue about Kubeflow or istio?

Sorry I posted it in the wrong page.
