### ISSUE TITLE
ambient: TestTraffic failure

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48508]
I can see this tests failed for almost all prs

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/48502/integ-ambient_istio/1737765601708871680

**Comment by hzxuzhonghu** [comment]
Seems this regression is from #48438

PTAL https://github.com/istio/istio/pull/48509

**Comment by howardjohn** [comment]
Might be fixed by https://github.com/istio/istio/pull/48393

**Comment by ymesika** [comment]
I'm closing because I can't see it happening anymore recent runs.
It indeed seems like #48393 fixed this as well.
