### ISSUE TITLE
How to ignore pod's /metrics api request from istio's `istio_requests_total ` count?

### ISSUE THREAD

**Issue by so2bin** [istio/istio#48518]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

* My pod is a `tritonserver` server and prometheus will intervally grap the `tritonserver`  api `/metrics`, this request action will increase the istio's  `istio_requests_total` value, and cause my QPS metrics is incorrect as follow image shows:
![image](https://github.com/istio/istio/assets/9431914/613be858-fe58-42b6-a4f5-ecbab5345529)
* So how can istio ignore this `/metrics` request from counting to `istio_requests_total`?

### Version

```Text
# helm list -n istio-system
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-base      istio-system    1               2023-06-21 15:53:58.463336923 +0800 CST deployed        base-1.17.3     1.17.3     
istiod          istio-system    4               2023-11-27 20:13:33.902283325 +0800 CST deployed        istiod-1.17.3   1.17.3
```

**Comment by husnialhamdani** [comment]
You can do customization with Telemetry API 
https://istio.io/latest/docs/tasks/observability/metrics/telemetry-api/

**Comment by zirain** [comment]
a possible solution: move `/metric` to specify port, then exclude it.

**Comment by so2bin** [comment]
> a possible solution: move `/metric` to specify port, then exclude it.

@zirain 
Exlucde this port with Telemetry API?  The /metrics API of `tritonserver` is already on a special port: `:8002/metrics`, how can I get this target? Can you show me a configuration example? 
I cannot find any demo examples of this feature on this offical web:
https://istio.io/latest/docs/tasks/observability/metrics/telemetry-api/
Thanks.

**Comment by zirain** [comment]
`traffic.sidecar.istio.io/excludeInboundPorts`

**Comment by zirain** [comment]
another option is request `pod_ip:15020/stats/prometheus`

**Comment by so2bin** [comment]
> `traffic.sidecar.istio.io/excludeInboundPorts`

@zirain Nice, this works for me, thank you!
