### ISSUE TITLE
Zipkin/tracing should be configurable

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4853]
Zipkin address is currently hardcoded, and the component is not easy to disable.
We should allow:
- [ ] changing zipkin for pre-installed zipkin if it is available
- [ ] allow disabling tracing altogether
- [ ] changing zipkin in bootstrap configuration

cc @linsun @mandarjog

**Comment by douglas-reid** [comment]
Agreed on the issue.  Reference to work of exploratory design work at the API level: https://github.com/istio/api/pull/363.

Note also: with the trace template in Mixer (and coming OpenCensus adapter work), there will be an additional knob available for controlling trace reporting.

**Comment by douglas-reid** [comment]
@bianpengyuan can speak to issues related to `zipkin-to-stackdriver`. IIRC, there was a related issue opened just recently.
