### ISSUE TITLE
IstioOperator's Deepcopy returns wrong results

### ISSUE THREAD

**Issue by TC-wang** [istio/istio#48539]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

First, get the DeepCopy object of IstioOperator
Then after modifying the configuration in the original IstioOperator Spec, comparing the original object and the Deepcopy object, the contents of the two are the same, which is not as expected.

The sample code is as follows:
```go
                         origin := &install.IstioOperator{
				TypeMeta:   metav1.TypeMeta{},
				ObjectMeta: metav1.ObjectMeta{},
				Spec:       &v1alpha12.IstioOperatorSpec{
					Hub:                "docker.io",
				},
				Status:     nil,
			}
			newCopy := origin.DeepCopy()
			origin.Spec.Hub = "test"
			if diff := cmp.Diff(origin, newCopy, protocmp.Transform()); diff != "" {
				t.Error(diff)
			}
```

The code implementation of IstioOperator Deepcopy is as follows: `operator/pkg/apis/istio/v1alpha1/zz_generated.deepcopy.go`

```go
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioOperator) DeepCopyInto(out *IstioOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in.Spec.DeepCopyInto(out.Spec)
	}
	if in.Status != nil {
		in.Status.DeepCopyInto(out.Status)
	}
	return
}
```

### Version

```Text
istio version: 1.16.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
It is not a proto message, you can use reflect.DeepCopy

**Comment by hzxuzhonghu** [comment]
NVM, it is the deepcoy method that is not correct
