### ISSUE TITLE
Configure prom labels in envoy metrics output

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4854]
For historical reasons, envoy direct metrics use statsd qualified names (dot-separated strings).
Stats tags have been added to envoy, allowing extracting prom labels from these long names.
This requires configuration at the bootstrap level, see https://github.com/envoyproxy/data-plane-api/blob/master/envoy/config/metrics/v2/stats.proto#L64.

cc @douglas-reid @mandarjog

**Comment by douglas-reid** [comment]
Related issue: https://github.com/istio/istio/issues/3984

**Comment by kyessenov** [comment]
Related sample https://github.com/bakins/kubernetes-envoy-example/blob/master/deploy/statsd.yaml
Thanks @nmnellis for discovering it.
