### ISSUE TITLE
config distribution debug api can not get version

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#48554]
I have use curl http://127.0.0.1:8080/debug/config_distribution?resource=DestinationRule/xxx/dxxx-dr | jq .  to get some information，but response is only show proxyId，not clusterVersion，ListenerVersion，RouteVersion.  Why the response is look like this?

istio version : 1.16.4

Response as follow:
curl http://127.0.0.1:8080/debug/config_distribution?resource=DestinationRule/xxx/dxxx-dr | jq .   
[
{"proxy": "test-service.test"},
{"proxy": "sleep.sample"}
]

**Comment by hzxuzhonghu** [comment]
IIRC, the distribution state is not enabled by default, can you check if you turned it on manually

**Comment by id-id-id** [comment]
来信已收到，祝好！

**Comment by id-id-id** [comment]
I just set PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING=true.   Both PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING and PILOT_ENABLE_STATUS should be enabled?

**Comment by id-id-id** [comment]
I have set both PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING and PILOT_ENABLE_STATUS enabled through set env in isitod deployment, but it doesn't work.

**Comment by hzxuzhonghu** [comment]
I donot recommend using this feature, it is not well tested

**Comment by id-id-id** [comment]
Recently，we want to reduce wait time or find some other method to avoid problem introduce in https://istio.io/latest/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes.

Is there any other recommended ways to avoid 503-errors?  And how can we estimate the waiting time more accurately?

**Comment by hzxuzhonghu** [comment]
If possible, the easist way is to create Config Rules before workload start

**Comment by id-id-id** [comment]
来信已收到，祝好！
