### ISSUE TITLE
istio stats of traffic  from outside passing through ingress gateway updated only when client close the connection(case: websocket)

### ISSUE THREAD

**Issue by deltcloud** [istio/istio#48563]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

istio stats reflect the real traffic

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

In my case it is websocket connection , traffic from outside through ingressgateway ,vs,dstrule ;finally tcp to pod with istio sidecar.

istio_requests_total  and istio_tcp_sent_bytes_total(in my case) stats only get updated when client(remote) close the connection

I notice istio_tcp_sent_bytes_total is a tcp metric. When two pods both with sidecars, communication in the mesh with tcp ,istio_tcp_sent_bytes_total get updated in the life of connection.

In env a client from outside without sidecar request to server in istio , the server responses to client, can we update istio_tcp_sent_bytes_total at regular intervals until the client close the connection, not update after client close the connection.

**Comment by hzxuzhonghu** [comment]
Websocket is special, it is to build a connection using http handshake. And the following data is transported via the tcp connection. There is no HTTP request/response concept. So it behaves like tcp here

**Comment by deltcloud** [comment]
> Websocket is special, it is to build a connection using http handshake. And the following data is transported via the tcp connection. There is no HTTP request/response concept. So it behaves like tcp here

istio_tcp_sent_bytes_total should update at regular intervals，not update after client close the connection

**Comment by zirain** [comment]
> > Websocket is special, it is to build a connection using http handshake. And the following data is transported via the tcp connection. There is no HTTP request/response concept. So it behaves like tcp here
> 
> istio_tcp_sent_bytes_total should update at regular intervals，not update after client close the connection

I recall it update every `5s` by default, @kyessenov anything sepcial to websocket?

**Comment by hzxuzhonghu** [comment]
good to know, can you point to it?

**Comment by kyessenov** [comment]
Periodic reporting is only done for gRPC traffic, not every HTTP request. This is a known limitation.

**Comment by deltcloud** [comment]
> Periodic reporting is only done for gRPC traffic, not every HTTP request. This is a known limitation.

I notice TCP telemetry collection in mesh with client and server envoy.
What about tcp client outside of mesh through gateway, We can get metrics in the tcp server side (istio-proxy)
