### ISSUE TITLE
Add istioctl subcommand to support querying Istio RBAC effect

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#4856]
To make it easier to use Istio RBAC and per #1947, we can provide a command line utility to allow the operator to query the effect of Istio RBAC.
It's better to integrate such utility to istioctl as a subcommand `rbac`. The operator could invoke it with a group of attributes to simulate a request and the command should return allow/deny plus some useful information about the reason for the result.

For example:
The command `$ istioctl rbac can-i --user test --namespace default --service productpage  --path abc/page --method GET` could result in istioctl output like `"Allowed"` or `"Denied. No ServiceRoleBinding found for user test"`.

**Comment by yangminzhu** [comment]
@liminw  @JimmyCYJ

**Comment by yangminzhu** [comment]
cc @ayj @liamawhite @nmittler 
Hi istioctl owners, could you take a look and provide some feedback on this to see if we can move forward with this proposal.
Thanks!

**Comment by yangminzhu** [comment]
cc @spikecurtis

**Comment by spikecurtis** [comment]
Yeah, maybe a good next step would be to write the "help" page for this subcommand. This can serve as the design for people to comment on the UI, and also makes progress.

**Comment by ayj** [comment]
A "help" page with examples would be a good place to start.

**Comment by yangminzhu** [comment]
@ayj @spikecurtis 
I think the command and its purpose is quite simple and the inline help message of the command should be enough. I created a simple PR (#5093) to introduce it so please comment on that PR to see how would you like the interface to look like.
 @liamawhite I think essentially all the flags is optional, if the user doesn't specify any of them, we could just use a empty default value to evaluate it against the RBAC policies.

Thanks for the feedback!
