### ISSUE TITLE
Unify delta xds `WatchedResources.ResourcesNames` maintainence 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48589]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Now the resourceNames for delta xds is not only updated in xds request handling but also in pushing. 
We can see `con.proxy.Lock` is widely used, it can easily lead to deadlock. And even very difficult for us to do a little bit of refactoring.

cc @ramaraochavali @howardjohn Want to know your idea first

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
What do you mean by "unify"? Can share more details on your idea?

**Comment by hzxuzhonghu** [comment]
By `unify` i mean, r/w on `WatchedResources` could probably be put together in one place.

**Comment by ramaraochavali** [comment]
That makes sense
