### ISSUE TITLE
Modifying service target port does not trigger istiod update, leading to a 503 error for an unknown cluster when creating/updating CRDs (e.g., wasmplugin, telemetry).

### ISSUE THREAD

**Issue by fizos** [istio/istio#48580]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

     I have reproduced the bug by redeploying the bookinfo application. First, I followed the official Istio documentation to deploy the bookinfo service, and it can be accessed successfully.
![image](https://github.com/istio/istio/assets/96819554/2babcfe5-fea9-4e85-b257-ce8c735e6738)
![image](https://github.com/istio/istio/assets/96819554/a64af2d6-3a42-4576-b5b7-9afef8c776c3)
Now everything works fine！

Then, I changed the target port of the productpage service from 9080 to 9000.
![image](https://github.com/istio/istio/assets/96819554/07ed7137-c3b6-4318-82e1-811177875e8d)
![image](https://github.com/istio/istio/assets/96819554/a51a2448-0fa0-4a64-a963-fff20bc0e015)
From the above diagram, it can be seen that the listener's port is still 9080, even though the target port has been changed to 9000.

Then, I created a WasmPlugin CRD with the following configuration:
`apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: auth-wasm-plugin
  namespace: default
spec:
  imagePullPolicy: Always
  match:
    - mode: SERVER
  selector:
    matchLabels:
      app: productpage
  url: oci://docker.io/shender/wasmplugin:v1`
![image](https://github.com/istio/istio/assets/96819554/1053bb48-e234-4460-83fb-693cf06e8dba)
At this point, the listener's port has been changed from 9080 to 9000.
However, the inbound cluster remains unchanged.

This can lead to a problem. For example, if we repeat the previous steps but instead change the port from 9000 back to 9080, and then install the WasmPlugin CRD, accessing the service may result in a "unknown cluster" error with HTTP status code 503.

From the source code of the Istio master branch, it appears that the EDS (Endpoint Discovery Service) did not get updated, but the LDS (Listener Discovery Service) did get updated, resulting in a 503 error.
![image](https://github.com/istio/istio/assets/96819554/1cfc3444-a862-4dde-99bd-a2d3024a952e)
![image](https://github.com/istio/istio/assets/96819554/5b746fb5-14c2-4d02-a730-aa6aa0a8664b)
            
**Are there any other ways to solve this problem besides restarting the pods?
Should EDS or other similar discovery services be triggered in addition to LDS when a WasmPlugin CRD is modified?
Urgently seeking resolution for the problem. Thanks very much！！！**

### Version

```Text
istioctl version
client version: 1.20.1
control plane version: 1.19.3
data plane version: 1.19.3 (10 proxies)

kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2
```

**Comment by dddddai** [comment]
There is a bug where istio does not push xDS when target ports are changed
You can set the following env in istiod for a quick fix
```
- name: ISTIO_ENABLE_OPTIMIZED_SERVICE_PUSH
  value: "false"
```

**Comment by so2bin** [comment]
> There is a bug where istio does not push xDS when target ports are changed You can set the following env in istiod for a quick fix
> 
> ```
> - name: ISTIO_ENABLE_OPTIMIZED_SERVICE_PUSH
>   value: "false"
> ```

@dddddai Is there any plan to fix this problem?

**Comment by dddddai** [comment]
Yeah I will fix it
