### ISSUE TITLE
Istio archive contains outdated k8s manifests

### ISSUE THREAD

**Issue by Tahler** [istio/istio#4859]
Running `make istio-archive VERSION=0.8.0 ISTIO_DOCKER_HUB=gcr.io/istio-release` generates "istio-0.8.0-linux.tar.gz", which contains many outdated YAML files under "install/kubernetes":

```yaml
- istio-mixer-validator.yaml
- istio-mixer-with-health-check.yaml
- istio-one-namespace-auth.yaml
- istio-one-namespace.yaml
- orig_istio-auth.yaml
- orig_istio-one-namespace-auth.yaml
- orig_istio-one-namespace.yaml
- orig_istio.yaml
```

These ones do not seem outdated; they are still in documentation.
```yaml
- istio-ca-plugin-certs.yaml
- istio-ca-with-health-check.yaml
```

/cc @mandarjog

**Comment by mandarjog** [comment]
Thanks for taking this @Tahler.

**Comment by mandarjog** [comment]
@wattli how can we update `istio-ca-plugin-certs.yaml, istio-ca-with-health-check.yaml` ?
Do they need to be there?
