### ISSUE TITLE
Raw VM: (flat) network testing

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#486]
- [x] cross region GCE - GKE testing
- [ ] cross region Bluemix testing
- [ ]  vpn testing

**Comment by costinm** [comment]
This seems to be working - only pending work is checking on-prem, and double checking bluemix.

**Comment by ldemailly** [comment]
the vpn one I didn't get around to setup

**Comment by ldemailly** [comment]
@linsun is looking at bluemix setup for reachable podips

**Comment by sakshigoel12** [comment]
@linsun can you update

**Comment by sakshigoel12** [comment]
Raw VM flat testing. Did simple testing last week. MySQL running in VM on Bluemix. K8s in IBM cloud.

Most imp thing is to ping DNS and repos.  Costin and Lin to figure this out on hybrid slack

**Comment by linsun** [comment]
waiting for the deb file in the next release to try this.

**Comment by sakshigoel12** [comment]
@linsun @costinm @ldemailly  can you help test this out

**Comment by sakshigoel12** [comment]
ETA : today or tom

**Comment by sakshigoel12** [comment]
Need to add a patch. Need to try it with a real service.

costin and laurent to talk about this

**Comment by sakshigoel12** [comment]
@linsun @costinm @ldemailly do any of you know whats up with this?

**Comment by ldemailly** [comment]
I don’t know if lin was able to test or not sorry

**Comment by linsun** [comment]
we haven't been able to get flat networking working for us.  We'll have to document this as a limitation before we can sort that out in blue mix.

**Comment by ldemailly** [comment]
let's close this for now then.
