### ISSUE TITLE
Inconsistent behaviors on pseudo headers

### ISSUE THREAD

**Issue by NaturezzZ** [istio/istio#48605]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The behaviors on pseudo headers (e.g., :authority, :method) are inconsistent and confusing in different fields.
In matching, all pseudo headers pass the validation and work well.
In header operations `set` and `add`, only `:authority` passes the validation and works well. `:method` and `:uri` can not pass validation.
In header operation `remove`, all pseudo headers can not pass validation. 

All these behaviors are not documented or explained clearly. The behaviors are inconsistent and confusing, which makes it prone to configuration bugs. 
Did the design take these situations into consideration? Should we make it consistent or enrich clearer documents?

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (4 proxies)
$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

**Comment by howardjohn** [comment]
The documentation doesn't generally have a list of all the valid or invalid options; this is encoded in the validation logic itself

**Comment by hzxuzhonghu** [comment]
istio does allow updating `:authority ` `host`,  other headers prefixed with `:` are not modiable

**Comment by zirain** [comment]
@hzxuzhonghu fixed by https://github.com/istio/istio/pull/48621？
