### ISSUE TITLE
IST0162 analyzer erroneously returning warning when it should not

### ISSUE THREAD

**Issue by josh-pritchard** [istio/istio#48613]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This appears to be a bug in the analyzer upstream. The Gateway
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    cluster.solo.io/cluster: cluster1
  creationTimestamp: "2023-12-21T18:08:52Z"
  generation: 2
  name: bookinfo
  namespace: bookinfo-frontends
  resourceVersion: "3697"
  uid: dc3c6668-9a8e-443c-b163-7fc888121204
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - cluster1-bookinfo.cluster1.rfkjwt4pedyc.instruqt.io
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - cluster1-bookinfo.cluster1.rfkjwt4pedyc.instruqt.io
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls-secret
      mode: SIMPLE
status: {}
```

should and does match the service
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-21T18:05:22Z"
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: istio-ingressgateway
  namespace: istio-gateways
  resourceVersion: "2060"
  uid: 75404632-f764-48ce-84fe-df5645ffbcca
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.2.216.92
  clusterIPs:
  - 10.2.216.92
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http2
    nodePort: 31261
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31151
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    revision: 1-19
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.18.102.1
```

I see the issue in the analyzer, the servicePorts map is never populated if the protocol on the Gateway is anything other than TCP which will cause this analyzer to always trigger no matter what is on the gateways Service, this surely can't be right.

<img width="1117" alt="image" src="https://github.com/solo-io/gloo-mesh-enterprise/assets/53924645/d5ba9203-d1b2-46fa-a3fa-8d3544aafc70">

### Version

```Text
1.20.x
```

**Comment by howardjohn** [comment]
The image doesn't work so its not super clear what is failing here

**Comment by hanxiaop** [comment]
> the servicePorts map is never populated if the protocol on the Gateway is anything other than TCP which will cause this analyzer to always trigger no matter what is on the gateways Service

I can see you have the TCP for service port, and the protocol on Gateway should not be related to the servicePort? Needs the error message to see if there's any problems.
