### ISSUE TITLE
Should external profile be removed?

### ISSUE THREAD

**Issue by peterj** [istio/istio#48634]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`istioctl profile list` still lists the `external` profile, even though it's been deprecated/replaced by the `remote` profile (https://github.com/istio/istio/pull/40822). 

Can the `external` profile be removed (note that it's been removed from the docs and doesn't show up anywhere)?

### Version

```Text
$ istioctl version 
1.20.0
```

**Comment by ericvn** [comment]
@frankbu
