### ISSUE TITLE
[helm] Make PodDisruptionBudget dynamic

### ISSUE THREAD

**Issue by wiardvanrij** [istio/istio#48636]
**Describe the feature request**

Make the PodDisruptionBudget dynamic. See: https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/poddisruptionbudget.yaml#L15 
```
spec:
  minAvailable: 1
```

In an ideal case I want to be able to define the value. For example for larger deployments, I might want to say: `95%` - this way, we do not suddenly lose 10% of our deployments.

Furthermore, it might be beneficial to allow setting either `minAvailable` or `maxUnavailable` 

**Describe alternatives you've considered**

I cannot think of any

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bseenu** [comment]
I can submit the PR for this, but before i want to clarify on this part

`# The values aren't mutable due to a current PodDisruptionBudget limitation
`
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L198

**Comment by zirain** [comment]
FYI, `gateway/istio-(ingress/egress)` is deprecated.

**Comment by hanxiaop** [comment]
> I can submit the PR for this, but before i want to clarify on this part
> 
> `# The values aren't mutable due to a current PodDisruptionBudget limitation ` https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L198

I think setting `minAvailable: 1` was causing autoscaling problems when we had 1 replica in the past.

**Comment by hanxiaop** [comment]
I think you can try this customization https://istio.io/latest/docs/setup/additional-setup/customize-installation/#advanced-install-customization

**Comment by bseenu** [comment]
> > I can submit the PR for this, but before i want to clarify on this part
> > `# The values aren't mutable due to a current PodDisruptionBudget limitation ` https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L198
> 
> I think setting `minAvailable: 1` was causing autoscaling problems when we had 1 replica in the past.

this is what it is currently hardcoded to https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/poddisruptionbudget.yaml#L15

**Comment by bseenu** [comment]
> I think you can try this customization https://istio.io/latest/docs/setup/additional-setup/customize-installation/#advanced-install-customization

we install istio along with other components and all of them are done through helm, so trying to stick to it

**Comment by hanxiaop** [comment]
@bseenu As @zirain said, those charts are deprecated, see https://github.com/istio/istio/tree/master/manifests/charts/gateway#legacy-gateway-helm-charts. I think the `gateway` chart contains some customizations you want?
https://github.com/istio/istio/blob/6479f501668a2eb6d4c8648ec29c579909b4565c/manifests/charts/gateway/values.yaml#L105-L133
