### ISSUE TITLE
introducing `default` revision in a revisioned cluster breaks it

### ISSUE THREAD

**Issue by kanurag94** [istio/istio#48643]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio currently adds a `default` tag MutatingWebhook for sidecar injection for a revision that is installed in the cluster. This tag ensures all namespaces with `istio.io/rev=default` and `istio-injection=enabled` get injected with the present revision in the cluster. However once `default` revision is introduced this `default` tag gets overwritten to be used for `default` revision instead. This is breaking since there can be previous configuration which are created for the revisioned istiod that previously existed.

For example:

At time T0, cluster has `stable` revision
`istio-injection=enabled` and `istio.io/rev=default` on a namespace/ object injects `stable` revision sidecar

At time T1, cluster got installed with `default` revision
`istio-injection=enabled` and `istio.io/rev=default` now will inject `default` revision sidecar.

Until a pod restart happens the namespace will have some proxies connecting to `stable` revision and some to `default` revision. This is indeterministic.

Possible expectation (with most preferred the first):
1. Stick `default` tag for `default` revision only.
2. Use `default` tag for only `istio-injection` label and not for `istio.io/rev` label. Also disable overriding by `default` revision if it becomes available in the cluster later.
3. If this has to be done somehow always, allow reading configuration from both istiod revisions in the transit period. We can introduce `DISCOVERY_REVISIONS` to discover configuration (VS, SE, Sidecar CR) across multiple revisions.

### Version

```Text
client version: 1.17.2
control plane version: 1.19-dev
data plane version: 1.19-dev (7 proxies), 1.19.5-f764c5d759 (1 proxies)

Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.23.6
WARNING: version difference between client (1.27) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Additional Information
Relevant Code: https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L584

**Comment by hanxiaop** [comment]
I think the example you provided is expected. Tag webhook can be managed with `istioctl tag` and associated with specific revisions. See https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels.

**Comment by kanurag94** [comment]
Thanks @hanxiaop
I meant to mention the issue with creating `default` tag which gets created by default for an existing revision in the cluster and gets overridden by `default` revision. This leads to indeterministic behaviour for someone who doesn't wish to use istio tags or has a `default` tag present in the cluster.

IMO, we shouldn't assume a revision other than `default` revision to be referenced by `default` tag but create it manually if required https://istio.io/latest/docs/setup/upgrade/canary/#default-tag

**Comment by hanxiaop** [comment]
> Thanks @hanxiaop I meant to mention the issue with creating `default` tag which gets created by default for an existing revision in the cluster and gets overridden by `default` revision (if `default` revision becomes available later in the cluster). This leads to indeterministic behaviour for someone who doesn't wish to use istio tags or has a `default` tag present in the cluster.

@kanurag94 I see, you mean there's an inconsistent default injection behavior between `revisioned -> default` and `default -> revisioned`? If so, why are you not installing another revisioned control plane and instead opting to install the `default`, which has a different semantic meaning?

**Comment by hanxiaop** [comment]
> IMO, we shouldn't assume a revision other than `default` revision to be referenced by `default` tag but create it manually if required https://istio.io/latest/docs/setup/upgrade/canary/#default-tag

I think there's a different meaning about revision="" and revision="default", doing this will work if revision="default" but for revision="", since with revision="", I assume I have installed an Istio that can at least inject `istio-injection` and `sidecar.istio.io/inject`. However, right now we are treating revision="" and revision="default" the same in code logics, which conforms to the definition of https://istio.io/latest/docs/setup/upgrade/canary/#default-tag.

**Comment by kanurag94** [comment]
Thanks @hanxiaop again
> I see, you mean there's an inconsistent default injection behavior between revisioned -> default and default -> revisioned? If so, why are you not installing another revisioned control plane and instead opting to install the default, which has a different semantic meaning?

You are right. However, I wish to have a deterministic install expectation for namespaces/ object which use `istio.io/rev=default` label. Unlike documented example, I only have use case to use `default` and `canary` revision. In a case where `canary` gets installed first, cluster provisioning errors out because namespaces marked for `istio.io/rev=default` gets connected to istiod-canary instead of istiod.
What I mean is, I do not intend to create a tag, not even `default`, and my expectation thus is to use `default` for `default` only. Istio currently installing `default` tag doesn't let user configure the same and leave an undesired state.

I think, in all cases, istio shouldn't just change injection behavior without user prompt (not even for default tag). Overriding the default revision to be used for default tag when it becomes available is IMO always going to cause issues.
Intuitively, as a user, I feel `istio.io/rev=default` should point to `default` revision in the cluster only unless a user chooses it to point to anything else.

> I think there's a different meaning about revision="" and revision="default", doing this will work if revision="default" but not for revision="", since with revision="", I assume I have installed an Istio that can at least inject istio-injection and sidecar.istio.io/inject. However, right now we are treating revision="" and revision="default" the same in code logics, which conforms to the definition of https://istio.io/latest/docs/setup/upgrade/canary/#default-tag.

AFAIK istio treats revision="" and revision="default" the same in the code logic (reading configuration etc.). So we should create default tag only for these revisions.

AFAIU Tag != Revision. Tags are only there for easier upgrades. Currently istio relies on `istio.io/rev` as the single label to inject both tag and revision. This can always become conflicting. If istio used something like `istio.io/tag` for tags, this would have been much clearer.
