### ISSUE TITLE
/debug/config_distribution correctness

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48679]
`/debug/config_distribution` is to query "Version status of all Envoys connected to this Pilot instance".

This means we should record the nonce based on xds response ACK. However we do also record by  `reportAllEvents` in `pushConnection`, this is completely not right, since this xds could not even be received by envoy.

There is also an issue in `reportAllEvents`and `func (r *Reporter) RegisterEvent(conID string, distributionType xds.EventType, nonce string) {`, they only cover lds.rds.cds.eds.  We all know in istio, not only these four kinds of xds, so this mechanism is totally not right.

@therealmitchconnors

**Comment by lhanjian** [comment]
> However we do also record by reportAllEvents in pushConnection, this is completely not right, since this xds could not even be received by envoy.

So, distribution report is also incorrect?

**Comment by hzxuzhonghu** [comment]
It is not perfect now as in very alpha stage

**Comment by lhanjian** [comment]
I am working on solving this problem for our production system.

Try to get xDS result from Envoy ACK nonce(and its corresponding PUSH) in Istio.

**Comment by hzxuzhonghu** [comment]
I did similar before, FYI https://github.com/istio/istio/pull/48542

Hope it is helpful

**Comment by lhanjian** [comment]
> I did similar before, FYI #48542
> 
> Hope it is helpful

Tks you very much!

I've read it before you mentioned it.

英雄所见略同.

**Comment by hzxuzhonghu** [comment]
It has been removed https://github.com/istio/istio/pull/51866
