### ISSUE TITLE
ControlPlaneAuthPolicy gradual adoption

### ISSUE THREAD

**Issue by costinm** [istio/istio#4868]
For pilot - and probably mixer, we need one port that is clear text and one that is MTLS (regardless of 
default control plane auth policy),  plus the legacy ports for upgrade ( 8080 and 15003 which was used on 0.6 and in most cases is clear text,but can be MTLS if any user enabled control plane MTLS).

Current code seems to repeat the error we made with 15003, and flip MTLS based on the default setting - which prevents having a mix of secure/insecure and 'a-la-carte' adoption.

**Comment by wattli** [comment]
It actually depends on use case.

If we allow customers to flip the bit to turn on/off mTLS on pilot, i.e., the controlPlaneAuthPolicy flag, then we need to support what Costin mentioned, i.e., one http port and one https port so previous services can still talk to pilot. 

If we don't allow customers to do this, then we won't even have this issue.

And Kuat, agree with what you said that we need a way to support mTLS only. However, if the answer to the above question is yes, i think it's of higher priority than support mTLS only.

**Comment by kyessenov** [comment]
I'm pretty sure the bit is no longer flippable without reinstalling the
istio system and/or the app.

**Comment by wattli** [comment]
But we can still flip it by reinstalling istio control plane, in this case, all previous services won't be able to talk to pilot (unless we support both http and https), right?

Actually once multiplexPort/TLS sniffing feature is done, we won't need a separate port any more. We can let pilot support 1) mTLS only 2) mTLS and http 3)http via policy. The solution will be cleaner.

**Comment by diemtvu** [comment]
Just throw out some ideas here. Can pilot provide a way to ask for the mode it uses (i.e a service on port 15123 that simply return NONE or TLS), and sidecar (or pilot agent and alike) can probe and restart itself with proper bootstrap config?

**Comment by costinm** [comment]
For 0.8: just have one port with MTLS on and one with MTLS off. 
There is no use case for same port that may be either on or off depending on setting. We certainly need to support migration and mix of clients.

The user can chose to use control plane mtls per sidecar - if they really want to prevent non-MTLS we can probably add a flag and restart pilot with the non-mtls port disabled.  But we can worry about this for 1.0.

Short term I want to make sure we don't ship 0.8 with a 'maybe on, maybe off' port - we made that mistake in 0.6 already.

**Comment by costinm** [comment]
BTW - same applies to mixer - it must have 2 ports for any 'a-la-carte' adoption.

**Comment by liamawhite** [comment]
@costinm I believe this was delivered as part of 0.8?
