### ISSUE TITLE
support proxy grained istioctl experimental wait

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#48696]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Now `istioctl experimental wait` support checks whether a config like vs has been distributed to all proxies. 

But in some case, we mind whether it has been distributed to a specific proxy, this especially makes sense as ambient introduced a new ztunnel type, which does not even watch traditional xds(lds rds CDs eds). 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by leosarra** [comment]
Hello @hzxuzhonghu , if that is fine for you I would like to work on a PR for this

**Comment by hzxuzhonghu** [comment]
Thanks for taking it
