### ISSUE TITLE
Raw VM: register rawvm (as external service)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#487]

**Comment by ldemailly** [comment]
going to take that one
- [ ] build/learn about pilot
- [ ] learn about k8s
- [ ] learn about grpc

then write a small grpc server with a simple api to register services with k8s on behalf of the VM

**Comment by ldemailly** [comment]
Open questions:

Can we mix external ips and local pods

Using external ips; using selector less endpoints; using something else...
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

cc @costinm @gnirodi

**Comment by sakshigoel12** [comment]
Please update Milestone

**Comment by ldemailly** [comment]
@sakshigoel12 I didn't update the tasks that are already in an epic (in zenhub you can click "issues without epic" to select those, and there are now 0 without a milestone vs > 80 yesterday)

but I can also go through those, it's a bit busy work though (there is no multi-update I could find)
