### ISSUE TITLE
Add `imagePullSecrets` for injected containers

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#4870]
When user deploy new application with `istio`, `istio injector`(manual and automatic) will inject two containers: `istio-proxy` and `istio-proxy_init`. If customer configure those two images to be pulled from private registry, then the image pull will be failed as there is no `imagePullSecrets`, seems we need to add `imagePullSecrets` to inject containers.

What do you think @linsun @rshriram @ayj

**Comment by gyliu513** [comment]
This is related to https://github.com/istio/istio/issues/4729 , both of those two issues want to enable istio injection can work offline with private docker registry.

**Comment by ayj** [comment]
cc @yusuoh

**Comment by gyliu513** [comment]
@ayj how about enable `istioctl kube-inject` support option of `imagePullSecrets`, just like what we did for `imagePullPolicy`?

**Comment by ayj** [comment]
IMO `kube-inject` flags is already quite large. I imagined flags would only be used for the most common aspects, e.g. hub, tag, debug. And the configuration file would be used for more complex customization.

**Comment by loganbfisher** [comment]
@ayj where in the configMap should I put this?  I added  it where I thought it should go and I am still getting the image pull error.

**Comment by loganbfisher** [comment]
Also would I still have to use imagePullSecret if I already edited my default service account to use the pull secret

**Comment by ayj** [comment]
>  where in the configMap should I put this?

I just looked and this will require a code/config change. The applied sidecar config is a list of initContainers, Containers, and volumes. `imagePullSecrets` would need to be added at this level and corresponding templates updated, e.g.

```diff
diff --git a/pilot/pkg/kube/inject/inject.go b/pilot/pkg/kube/inject/inject.go
index d8c872ac9..6a89053c2 100644
--- a/pilot/pkg/kube/inject/inject.go
+++ b/pilot/pkg/kube/inject/inject.go
@@ -93,9 +93,10 @@ const (
 // SidecarInjectionSpec collects all container types and volumes for
 // sidecar mesh injection
 type SidecarInjectionSpec struct {
-       InitContainers []v1.Container `yaml:"initContainers"`
-       Containers     []v1.Container `yaml:"containers"`
-       Volumes        []v1.Volume    `yaml:"volumes"`
+       InitContainers   []v1.Container            `yaml:"initContainers"`
+       Containers       []v1.Container            `yaml:"containers"`
+       Volumes          []v1.Volume               `yaml:"volumes"`
+       ImagePullSecrets []v1.LocalObjectReference `yaml:"imagePullSecrets"`
 }

 // SidecarTemplateData is the data object to which the templated
```

cc @yusuoh

**Comment by shenxg13** [comment]
Hello, how can i enable this config in istio sidecar injector config map? I add a config like this but it still doesnt work.

```
data:
  config: |-
    policy: {{ .Values.global.proxy.autoInject }}
    template: |-
{{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
{{- end }}
{{- end }}
      initContainers:
      - name: istio-init
```
