### ISSUE TITLE
Clean up annotations

### ISSUE THREAD

**Issue by linsun** [istio/istio#48702]
While reviewing our [annotations](https://istio.io/latest/docs/reference/config/annotations/), i'm not seeing any code handles these annotations (other than in the API repo), please let me know if I missed anything:

- install.operator.istio.io/chart-owner
- install.operator.istio.io/owner-generation
- install.operator.istio.io/version

will update the list as I continue go through the rest of annotations. Should we at least mark them as deprecated before removing?

**Comment by hanxiaop** [comment]
IIRC `galley.istio.io/analyze-suppress` is being used in analysis, I'll check it again.

**Comment by hanxiaop** [comment]
> IIRC `galley.istio.io/analyze-suppress` is being used in analysis, I'll check it again.

https://github.com/istio/istio/blob/99d7913cc15252d6bd93aaf67ee021e71f2da6a8/pkg/config/analysis/local/istiod_analyze.go#L536-L544

**Comment by linsun** [comment]
> > IIRC `galley.istio.io/analyze-suppress` is being used in analysis, I'll check it again.
> 
> https://github.com/istio/istio/blob/99d7913cc15252d6bd93aaf67ee021e71f2da6a8/pkg/config/analysis/local/istiod_analyze.go#L536-L544

Thank you, I missed that!  I'll remove it off the list.
