### ISSUE TITLE
How to update HPA minReplicas thru istioctl

### ISSUE THREAD

**Issue by dwishnek** [istio/istio#48713]
Hi,

Running version Istio 1.19.6 in a kubernetes cluster. Was wondering what is the proper method to update the HPA (for any of the controlplane resources). I can use kubectl to modify the HPA directly. Is there a way to update the HPA thru istioctl without a reinstall? 

Thanks

**Comment by hanxiaop** [comment]
Is this what you want? https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L6

You can try with `istioctl install --set`.

**Comment by aboje** [comment]
> Is this what you want? https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L6-L7
> 
> You can try with `istioctl install --set`.

I think the goal is to maintain one IstioOperator definition that's referenced through the lifecycle of the installation. After installation, if a change is required (such as changing hpaMin/hpaMax or adding a port to the ingress controller), is there a way to make these changes from within the istioctl/IstioOperator framework? If so, I don't see that in the documentation.

**Comment by hanxiaop** [comment]
@aboje In this case, I think you can try to maintain an IstioOperator resource file and install it with `istioctl install -f iop.yaml`. When you need to change the HPA, edit the field and run `istioctl install -f iop.yaml` again.

**Comment by dwishnek** [comment]
Yes I think what I was missing before was adding --revision parameter which I believe somehow points to the correct istio operator. (we had 2 operators running since we had just upgraded to v1.9.6) We can close this.. Thanks for your help!
