### ISSUE TITLE
Precommit hook sets GOPATH to empty string

### ISSUE THREAD

**Issue by Tahler** [istio/istio#4872]
The pre-commit hook in "bin/pre-commit" does not work properly because it sets GOPATH to an empty string. It is overall a messy script and in need of updating.

[This line](https://github.com/istio/istio/blob/2497efe94294847da71731756c9802f285ff649f/bin/pre-commit#L18) is the troublemaker.

**Comment by ayj** [comment]
```bash
export GOPATH=$(cd $ROOT/../..)
```

Perhaps a typo? I think this should read:

```bash
export GOPATH=$(cd $ROOT/../.. && pwd)
```

cc @ZackButcher for confirmation

**Comment by ZackButcher** [comment]
Yup probably, though TBH I'm not sure if anyone today actually uses the pre-commit in practice. Either way https://github.com/istio/istio/pull/4874 addresses this just fine IMO.

**Comment by Tahler** [comment]
Ah, I skipped over the part in https://github.com/istio/istio/blob/master/DEV-GUIDE.md#enable-pre-commit-hook which says it's not functional. In any case, I was able to get it working with the changes in #4874. I hope this can also close #2262.

**Comment by hklai** [comment]
@Tahler what is the status? Can we merge #4874?

**Comment by Tahler** [comment]
Well, I think the better move is to remove the pre-submit hooks. No one is using it and even in a fixed state, it will take some time to run the unit tests and linters on each commit. I'll close #4874 and make a different PR to delete the pre-submits from the docs and repo.
