### ISSUE TITLE
After upgrading to istio 1.20.1 , communication fails to rds mysql

### ISSUE THREAD

**Issue by himanshu-tyagi-3pg** [istio/istio#48739]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am new to istio , so pardon for stupid questions
1. After upgrading istio from 1.18.2 to 1.20.1 I have observed some erratic behavior . I have one app namespace where java springboot app is running and also one external service deployed as below to connect to rds mysql

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service
  name: mysql-service
  namespace: app-prd
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  externalName: "mysqlrds.abcdef.us-west-2.rds.amazonaws.com"
  selector:
    app: mysql-service
  type: ExternalName

after upgrading istio to 1.20.1 app pods fails to connect to rds giving communication link fail error.
======
2024-01-10 09:00:02.249 ERROR 7 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
======

but when I make istiod/ingress/egress pods replica to 0 and then again 1 (means bouncing istio processes) then communication link setup again and app pods connects to rds.

This was not the case until 1.18.2 . What is wrong with this version ? can you guide me ?

2. Secondly for production , is it OK that we keep istiod/ingress/egress replicas more than 1 ? e.g. 2 or 3 . will it be a good practice ?

### Version

```Text
$ istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (6 proxies)
```

**Comment by himanshu-tyagi-3pg** [comment]
Infact I did check , even after pod was able to start , but sometimes in application log I can see communication failure in between. 

We are not using mysql ssl . I didnt get how to set this protocol ? and it was not issue in 1.18.2 istio. is it something new now ?

**Comment by himanshu-tyagi-3pg** [comment]
any help ? Also second question was that istiod/ingress/egress can have replica more than 1 ?

**Comment by keithmattix** [comment]
If you change the appProtocol to "tcp-server-first" in your Service, does that change anything?

And yes when you use the helm chart, there is are HPAs deployed for istiod and the gateways

**Comment by himanshu-tyagi-3pg** [comment]
issue is it is now intermittent :-( no firm way to test. but still I try this option. Thanks Keith.

**Comment by whmmm** [comment]
same question
