### ISSUE TITLE
http_proxy is routing incorrectly

### ISSUE THREAD

**Issue by sasokolov** [istio/istio#48763]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using istio-proxy in non transparent proxy mode, a cluster is used when choosing a route without taking into account the requested port.
For example, if there is no port 80 in the target SVC, but only port 8080
```
apiVersion: v1
kind: Service
metadata:
  name: black-box
  namespace: black-box
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: application
  selector:
    app: black-box
  type: ClusterIP
```
then if you request (I have `proxyHttpPort: 15007`)
```
$ curl http://black-box.black-box.svc.cluster.local:8080 -s -x http://127.0.0.1:15007 -v
*   Trying 127.0.0.1:15007...
* Connected to 127.0.0.1 (127.0.0.1) port 15007 (#0)
> GET http://black-box.black-box.svc.cluster.local:8080/ HTTP/1.1
> Host: black-box.black-box.svc.cluster.local:8080
> User-Agent: curl/7.85.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Thu, 11 Jan 2024 04:27:05 GMT
< server: envoy
<
* Connection #0 to host 127.0.0.1 left intact
```
The body is: `no healthy upstream`

when I added such lines to the SVC above, http-80 is required to be the first in the list, otherwise there will be no changes
```
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: application
```
the same query starts working, but it can be seen from the log that the cluster is selected for port 80 instead of 8080
```
{
"authority": "black-box.black-box.svc.cluster.local:8080",
"downstream_local_address": "127.0.0.1:15007",
"upstream_cluster": "outbound|80||black-box.black-box.svc.cluster.local"
}
```

And if you form a request for a port that does not exist at all in the SVC, it will also come as if it was sent to port 80
```
{
"authority": "black-box.black-box.svc.cluster.local:8888",
"downstream_local_address": "127.0.0.1:15007",
"upstream_cluster": "outbound|80||black-box.black-box.svc.cluster.local"
}
```

### Version

```Text
$ istioctl version
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (449 proxies)

$ kubectl version
Client Version: v1.28.3-eks-e71965b
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9

$ helm version --short
v3.7.1+g1d11fcb
```

**Comment by howardjohn** [comment]
cc @ramaraochavali

**Comment by sasokolov** [comment]
I've added annotation for the pod `traffic.sidecar.istio.io/excludeOutboundPorts: "15007"` and now I have the iptables rule:
```
Chain ISTIO_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination
   23  1380 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:15007
``
After that, the behavior did not change.

**Comment by sasokolov** [comment]
still actual
`$ istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (670 proxies)
`
