### ISSUE TITLE
support fake dns in sidecar when enable DNS_CAPTURE

### ISSUE THREAD

**Issue by yylt** [istio/istio#48785]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

when enable DNS_CAPTURE feature, could return fake dns if NXDOMAIN from dns upstream.

client must have one ip address from domain, otherwise not do connect, and envoy sidecar actually will replace destination address

In the step which replace destination address in envoy, there are many other project on it.

- the [slime](https://github.com/slime/slime), will hijack the 4-layer traffic, add a sidecar resource to the destination, and the traffic will be converted to 7-layer traffic next time. in the slime, it does not matter the ip address about domain

- the [aeraki](https://github.com/aeraki-mesh/aeraki), which must fill in a virtual IP address on the serviceentry resource

all about is because connect ip not connect domain, if we could add fake address in sidecar dns server, these could do more convenient

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
Curious if you also have `ISTIO_META_DNS_AUTO_ALLOCATE` enabled?

**Comment by howardjohn** [comment]
If you _always_ fake every single NXDOMAIN won't that break things? Think if I do `nc fakeaddress.com 80`. Before it fails in DNS, now it goes to some bogus IP?

I suppose in both cases it fails...
