### ISSUE TITLE
Raw VM: configuration and bootstrap

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#488]
galley dependency

from doc:
Configuration options - we should support both eventually but probably should pick 1 first:
- Use static configs (puppet, ansible) to generate the sidecar envoy config - for cases where the fleet of raw VMs are managed with an existing CM system. This needs to be integrated with Galley/Pilot/Mixer. The native tools are required at least for bootstrapping - but should be useable to distribute configuration if users have existing CM processes in place.
- Run kubectl with a kube service account - if the raw VM is on the same network with the k8s cluster. This simplifies and makes things consistent with 0.1 istio, and can avoid the dependency on ansible/puppet/etc.

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ldemailly** [comment]
0.2 which is why it's in the epic (it's the VM itself bootstrap)
issues that are inside an epic "inherit" the issue's milestone (unfortunately not in the UI)

**Comment by ldemailly** [comment]
covered by https://github.com/istio/pilot/pull/1100 and https://github.com/istio/proxy/pull/404

**Comment by costinm** [comment]
PRs submitted (pending auth .deb) - will close once it makes it into a release.

**Comment by sakshigoel12** [comment]
PR for scripts is inflight

**Comment by ldemailly** [comment]
yes
