### ISSUE TITLE
[IST0137] sample-bookinfo-argocd-server is associated with multiple services using targetPort "8080" but different ports: [80 443].

### ISSUE THREAD

**Issue by qodirovshohijahon** [istio/istio#48808]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am facing 
Warning [IST0137] (Deployment sample-bookinfo/sample-bookinfo-argocd-server) This deployment sample-bookinfo-argocd-server is associated with multiple services [sample-bookinfo/sample-bookinfo-argocd-server sample-bookinfo/sample-bookinfo-argocd-server] using targetPort "8080" but different ports: [80 443].

Warning [IST0137] (Deployment sample-petclinic/sample-petclinic-argocd-server) This deployment sample-petclinic-argocd-server is associated with multiple services [sample-petclinic/sample-petclinic-argocd-server sample-petclinic/sample-petclinic-argocd-server] using targetPort "8080" but different ports: [80 443].
This waring is caused by the ports on the argocd server
 
It is possible to remove this warning according to the doc, but argo-cd is installed via Helm and deployment/service (argo-cd server deployment and service) cannot be controlled.

These warnings disappear in version 1.20.0, but I want to fix it without waiting for the upgrade.

### Version

```Text
istioctl version: 1.20.0
control/data plane version: 1.18.5
```

### Additional Information

I changed manually service ports and it was fixed but I want to control via helm values

**Comment by fatedier** [comment]
```
# Analyze the current live cluster and suppress PodMissingProxy for pod mypod in namespace 'testing'.
istioctl analyze -S "IST0103=Pod mypod.testing"
```

You can use `-S` to suppress warnings.

**Comment by hanxiaop** [comment]
Not sure if I understand, doesn't modifying the Helm values solve the problem? Or if you're looking to suppress the message, the `analyze` command has the `-S` flag or `galley.istio.io/analyze-suppress` annotation.

**Comment by qodirovshohijahon** [comment]
> Not sure if I understand, doesn't modifying the Helm values solve the problem? Or if you're looking to suppress the message, the `analyze` command has the `-S` flag or `galley.istio.io/analyze-suppress` annotation.

like this, I can not disable https port from here, If I remove manually this port this warning will be removed so I need to disable this port using helm values or with another way

**Comment by hanxiaop** [comment]
@qodirovshohijahon I think you should ask argo community instead of Istio, as we have no control over the manifest. You may also consider using things like Kustomize for overrides.
