### ISSUE TITLE
ServiceEntry with different response

### ISSUE THREAD

**Issue by YanoGit** [istio/istio#48809]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am configuring internal domains with ServiceEntry in my environment. With a single service, everything was working as expected. However, when I applied the configuration to more services, I noticed that the results were intermittent. Running the curl command from within one pod to another, I observed that I was receiving many identical IPs, but with different responses.

``` yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
    argocd.argoproj.io/instance: offers
  name: offers
spec:
  endpoints:
    - address: offers-service.default.svc.cluster.local
  exportTo:
    - .
  hosts:
    - offers.internal.tld
  location: MESH_INTERNAL
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
```

``` bash
➜  ~ kubectl exec -it  web-9bdc4fbdd-bjnx9  -- curl -v offers.internal.tld/api/v1/offers
* Host offers.internal.tld:80 was resolved.
* IPv6: (none)
* IPv4: 240.240.141.162, 240.240.141.162, 240.240.141.162, 240.240.141.162
*   Trying 240.240.141.162:80...
* Connected to offers.internal.tld (240.240.141.162) port 80
> GET /api/v1/offers HTTP/1.1
> Host: offers.internal.tld
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< date: Mon, 15 Jan 2024 19:25:14 GMT
< x-envoy-upstream-service-time: 58
< server: envoy
< transfer-encoding: chunked
```

### Version

```Text
istioctl version  
client version: 1.20.2
control plane version: 1.20.1
data plane version: 1.20.1 (21 proxies)

kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```

**Comment by hzxuzhonghu** [comment]
How many SEs do you have, not sure if the IP allocation varies from time to time

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/48055 https://github.com/istio/istio/issues/48169

**Comment by ramaraochavali** [comment]
Another problem IPv4: 240.240.141.162, 240.240.141.162, 240.240.141.162, 240.240.141.162 - There seems to be some issue

**Comment by YanoGit** [comment]
> How many SEs do you have, not sure if the IP allocation varies from time to time

In this test we have 3 services with each own SE.

**Comment by YanoGit** [comment]
> Are they all for `offers.internal.tld`?

No, for each service I'm creating its own host, like a products `products.internal.tld` and so on.

**Comment by hzxuzhonghu** [comment]
can you paste all your Serviceentry

**Comment by YanoGit** [comment]
> can you paste all your Serviceentry
The other Service Entry records are essentially the same, differing only in the address/hosts.

For some reason, I deleted the gateways/virtual services for all services, and upon recreating them, I am now receiving the correct response, despite the duplication of IPs.

I noticed that when executing the curl command for the internal host, the response time is significantly longer. I believe we can close the issue, as the only remaining problem is the slow response time.

Kubernetes host:
```bash
✗ kubectl exec -it deploy/web -n default -- curl -v offers.default.svc.cluster.local/api/v1/offers -s -o /dev/null -w  "%{time_starttransfer}\n"
* Host offers.default.svc.cluster.local:80 was resolved.
* IPv6: (none)
* IPv4: 10.100.194.182
*   Trying 10.100.194.182:80...
* Connected to offers.default.svc.cluster.local (10.100.194.182) port 80
> GET /api/v1/offers HTTP/1.1
> Host: offers.default.svc.cluster.local
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< date: Fri, 19 Jan 2024 16:34:53 GMT
< x-envoy-upstream-service-time: 63
< server: envoy
< transfer-encoding: chunked
< 
{ [32624 bytes data]
* Connection #0 to host offers.default.svc.cluster.local left intact
0.065007
```

ServiceEntry host:
```bash
✗ kubectl exec -it deploy/web -n default -- curl -v offers.internal.tld/api/v1/offers -s -o /dev/null -w  "%{time_starttransfer}\n"               
* Host offers.internal.tld:80 was resolved.
* IPv6: (none)
* IPv4: 240.240.184.252, 240.240.184.252
*   Trying 240.240.184.252:80...
* Connected to offers.internal.tld (240.240.184.252) port 80
> GET /api/v1/offers HTTP/1.1
> Host: offers.internal.tld
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< date: Fri, 19 Jan 2024 16:35:18 GMT
< x-envoy-upstream-service-time: 10076
< server: envoy
< transfer-encoding: chunked
< 
{ [24440 bytes data]
* Connection #0 to host offers.internal.tld left intact
10.079229
```

**Comment by YanoGit** [comment]
> `x-envoy-upstream-service-time: 10076` means 10.076 time maybe spent by the upstream host processing

If i increasing Istio resources, this time should be shorter, correct?

**Comment by hzxuzhonghu** [comment]
There are many factors that can influence the upstrean service time, it could be the server side overloaded, in this case increasing resource limit is helpful. 

And there are other factors, like the time is wasted in network, then helpless increasing resources
