### ISSUE TITLE
Mixer client tests to use Envoy v2 config

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#4883]
Pilot is ready to use Envoy v2 config to pass config to Envoy.   But it is not tested end-to-end.

One way to test at proxy side is to make Mixer client test use Envoy v2. 

I have some code changes, at

https://github.com/qiwzhang/istio  "use_envoy_v2" branch

, we switch all tests to envoy v2.

**Comment by kyessenov** [comment]
/assign @kyessenov

I've completed this as part of mixer client test cleanup.
