### ISSUE TITLE
Having issue to rewrite uri using istio 

### ISSUE THREAD

**Issue by RaviSingh-Dev** [istio/istio#48863]
Hi , I need help urgently . I am trying to use the virtual service to rewrite the uri and then send the request to destination as below but it's not working can someone help me, I am mentioning the 2 rewrites which I am doing:-
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mylogs-service
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
      - uri: /*/_search
    rewrite:
        uri: /hub/data/v1/*/search
    route:
      - destination:
          host: gateway
          port:
            number: 8080 
    - match:
        uri: /*/_mapping/field/*
    rewrite:
        uri: /hub/data/v1/*/_mapping/field/*
    route:
      - destination:
          host: gateway
          port:
            number: 8080 
I am sending the request as /logs*/search then it should rewrite as /hub/data/v1/logs*/search and another one as /logs*/_mapping/field/* then it should rewrite as /hub/data/v1/logs*/_mapping/field/*  route the request to the destination but it's not doing that at all. I tried with regex too but it's not working can someone help me please it's urgent.

**Comment by hanxiaop** [comment]
I think https://github.com/istio/istio/issues/47500 is related?
