### ISSUE TITLE
Document that established connections are closed when enrolling into ambient

### ISSUE THREAD

**Issue by alpha-baby** [istio/istio#48876]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

After I add the application to the ambient mesh，like this：
```bash
kubectl label namespace default istio.io/dataplane-mode=ambient
```

the keep-alive connection that my application has already established will not work properly.

If I don't redeploy or restart my program, is there a solution for this scenario?

When I remove my app from ambient mesh, I also have the same problem.

Is there any way to avoid hijacking established connections？

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
IIRC, the ambient will not influence a previous injected sidecar. cc @linsun

**Comment by alpha-baby** [comment]
> IIRC, the ambient will not influence a previous injected sidecar. cc @linsun

It will influence established connection after I first add the application to the ambient mesh.

The previous  established connection (not redirect by ambient mesh) will be reset by peer.

**Comment by linsun** [comment]
@alpha-baby - was your app injected with sidecar before?  @hzxuzhonghu is right, we should not impact any sidecar behavior by design.

My guess is your app doesn't have sidecar and established connection stopped working after ambient is added? Note: we have introduced a less invasion redirection called "in-Pod" recently: see:

 Hi folks, many of you in the past have reported ambient doesn't work in your k8s env or with your CNI.  We have a different implementation of traffic redirection (under review atm before they are merged) you can try it by following instruction here - https://github.com/istio/istio/issues/48212#issuecomment-1864725172. We expect it to work with all k8s env with all CNIs. (believe there is some caveat for DPV2)

**Comment by howardjohn** [comment]
cc @bleggett

**Comment by bleggett** [comment]
> the keep-alive connection that my application has already established will not work properly.

> If I don't redeploy or restart my program, is there a solution for this scenario?

> It will influence established connection after I first add the application to the ambient mesh.
> 
> The previous established connection (not redirect by ambient mesh) will be reset by peer.

Yep, that's correct. 

Enrolling apps for the first time in ambient will reset existing connections, yes.

This does _not_ require a pod restart unless your application within the pod lacks connection retries or other forms of fundamental networking resiliency - your app would simply experience its current connection being dropped, would ideally attempt to retry establishing the connection, and that should succeed.

If your application cannot tolerate a networking interruption measured in the milliseconds, it will probably have issues in any network topology.


For _upgrades_, at least, there are mechanisms to allow operators to have more blast radius control than this, which we discussed briefly in the in the [June 14th, 2023 contributor meeting](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4), before ultimately deciding to lean on node cordons and blue/green node pooling as the only upgrade blast radius control for disrupted connections during upgrades, at least for the time being.

**Comment by alpha-baby** [comment]
> @alpha-baby - was your app injected with sidecar before? @hzxuzhonghu is right, we should not impact any sidecar behavior by design.
> 
> My guess is your app doesn't have sidecar and established connection stopped working after ambient is added? Note: we have introduced a less invasion redirection called "in-Pod" recently - see below:
> 
> Hi folks, many of you in the past have reported ambient doesn't work in your k8s env or with your CNI. We have a different implementation of traffic redirection (under review atm before they are merged) you can try it by following instruction here - [#48212 (comment)](https://github.com/istio/istio/issues/48212#issuecomment-1864725172). We expect it to work with all k8s env with all CNIs. (believe there is some caveat for DPV2)

yes，my app not injected with sidecar before. Redirection called "in-pod" is a good idea. In my company, the architecture like this has been running in a production environment for some time now. I think this redirection is a better solution than current.

**Comment by alpha-baby** [comment]
> > the keep-alive connection that my application has already established will not work properly.
> 
> > If I don't redeploy or restart my program, is there a solution for this scenario?
> 
> > It will influence established connection after I first add the application to the ambient mesh.
> > The previous established connection (not redirect by ambient mesh) will be reset by peer.
> 
> Yep, that's correct.
> 
> Enrolling apps for the first time in ambient will reset existing connections, yes.
> 
> This does _not_ require a pod restart or redeoply at all, unless your application within the pod lacks connection retries or other forms of fundamental networking resiliency - your running app would simply experience its current connections being dropped, would ideally attempt to retry establishing the connection, and that should succeed, now thru ambient.
> 
> If your application cannot tolerate a networking interruption measured in the milliseconds, it will probably have stability and reliability issues in any network topology, regardless of Istio or Kube.
> 
> For _upgrades_, at least, there are mechanisms to allow operators to have more blast radius control over what is interrupted than this, which we discussed briefly in the in the [June 14th, 2023 contributor meeting](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4), before ultimately deciding to lean on node cordons and blue/green node pooling as the only upgrade blast radius control for disrupted connections during upgrades, at least for the time being.

yes, my app will attempt to retry establishing the connection. But I think this is not appropriate as it may result in some business requests failing. Using `nf_contrack`, we have a way to avoid resetting the established connection. Using `nf_contrack` in production environments carries risks. In our company's production environment, the use of Linux's nf_contrack module is prohibited.

The new redirection called "in-pod" is a better solution. I will continue to follow it.

**Comment by linsun** [comment]
> > @alpha-baby - was your app injected with sidecar before? @hzxuzhonghu is right, we should not impact any sidecar behavior by design.
> > My guess is your app doesn't have sidecar and established connection stopped working after ambient is added? Note: we have introduced a less invasion redirection called "in-Pod" recently - see below:
> > Hi folks, many of you in the past have reported ambient doesn't work in your k8s env or with your CNI. We have a different implementation of traffic redirection (under review atm before they are merged) you can try it by following instruction here - [#48212 (comment)](https://github.com/istio/istio/issues/48212#issuecomment-1864725172). We expect it to work with all k8s env with all CNIs. (believe there is some caveat for DPV2)
> 
> yes，my app not injected with sidecar before. Redirection called "in-pod" is a good idea. In my company, the architecture like this has been running in a production environment for some time now. I think this redirection is a better solution than current.

Thanks for confirming the inpod is a good idea - we expect it to land in istio 1.21 soon.

**Comment by linsun** [comment]
> > > the keep-alive connection that my application has already established will not work properly.
> > 
> > 
> > > If I don't redeploy or restart my program, is there a solution for this scenario?
> > 
> > 
> > > It will influence established connection after I first add the application to the ambient mesh.
> > > The previous established connection (not redirect by ambient mesh) will be reset by peer.
> > 
> > 
> > Yep, that's correct.
> > Enrolling apps for the first time in ambient will reset existing connections, yes.
> > This does _not_ require a pod restart or redeoply at all, unless your application within the pod lacks connection retries or other forms of fundamental networking resiliency - your running app would simply experience its current connections being dropped, would ideally attempt to retry establishing the connection, and that should succeed, now thru ambient.
> > If your application cannot tolerate a networking interruption measured in the milliseconds, it will probably have stability and reliability issues in any network topology, regardless of Istio or Kube.
> > For _upgrades_, at least, there are mechanisms to allow operators to have more blast radius control over what is interrupted than this, which we discussed briefly in the in the [June 14th, 2023 contributor meeting](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4), before ultimately deciding to lean on node cordons and blue/green node pooling as the only upgrade blast radius control for disrupted connections during upgrades, at least for the time being.
> 
> yes, my app will attempt to retry establishing the connection. But I think this is not appropriate as it may result in some business requests failing. Using `nf_contrack`, we have a way to avoid resetting the established connection. Using `nf_contrack` in production environments carries risks. In our company's production environment, the use of Linux's nf_contrack module is prohibited.
> 
> The new redirection called "in-pod" is a better solution. I will continue to follow it.

I would argue disconnect would be the right behavior here as the prior connection isn't mtls or have policy enforced so you'd want to be disconnected to ensure the the app is properly part of the mesh now.

**Comment by zengyuxing007** [comment]
> > > > the keep-alive connection that my application has already established will not work properly.
> > > 
> > > 
> > > > If I don't redeploy or restart my program, is there a solution for this scenario?
> > > 
> > > 
> > > > It will influence established connection after I first add the application to the ambient mesh.
> > > > The previous established connection (not redirect by ambient mesh) will be reset by peer.
> > > 
> > > 
> > > Yep, that's correct.
> > > Enrolling apps for the first time in ambient will reset existing connections, yes.
> > > This does _not_ require a pod restart or redeoply at all, unless your application within the pod lacks connection retries or other forms of fundamental networking resiliency - your running app would simply experience its current connections being dropped, would ideally attempt to retry establishing the connection, and that should succeed, now thru ambient.
> > > If your application cannot tolerate a networking interruption measured in the milliseconds, it will probably have stability and reliability issues in any network topology, regardless of Istio or Kube.
> > > For _upgrades_, at least, there are mechanisms to allow operators to have more blast radius control over what is interrupted than this, which we discussed briefly in the in the [June 14th, 2023 contributor meeting](https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#heading=h.uph0clj4a3t4), before ultimately deciding to lean on node cordons and blue/green node pooling as the only upgrade blast radius control for disrupted connections during upgrades, at least for the time being.
> > 
> > 
> > yes, my app will attempt to retry establishing the connection. But I think this is not appropriate as it may result in some business requests failing. Using `nf_contrack`, we have a way to avoid resetting the established connection. Using `nf_contrack` in production environments carries risks. In our company's production environment, the use of Linux's nf_contrack module is prohibited.
> > The new redirection called "in-pod" is a better solution. I will continue to follow it.
> 
> I would argue disconnect would be the right behavior here as the prior connection isn't mtls or have policy enforced so you'd want to be disconnected to ensure the the app is properly part of the mesh now.

I don't think established connections should be disconnected unless mTLS is on. mTLS should be user behavior, users should be able to choose whether or not to turn on mTLS when installing istio, and we shouldn't be forced to turn on mTLS.

**Comment by zengyuxing007** [comment]
The optional way should be that inpod redirects only for new connections, which should not change much.

**Comment by linsun** [comment]
> The optional way should be that inpod redirects only for new connections, which should not change much.

I think this could be a good option, if user doesn't have mtls enabled by default.

**Comment by alpha-baby** [comment]
> I don't think established connections should be disconnected unless mTLS is on. mTLS should be user behavior, users should be able to choose whether or not to turn on mTLS when installing istio, and we shouldn't be forced to turn on mTLS.

i agree with you. Users should be able to choose whether or not to disconnect previous connections.

**Comment by alpha-baby** [comment]
not only mTLS scenarios.

In some other scenarios, it is also not to forcibly disconnect the connection, such as MySQL's connection is stateful.

**Comment by linsun** [comment]
@zengyuxing007 I saw you added ambient beta label, adding @istio/technical-oversight-committee and @keithmattix to weigh in. While I agree this is very nice to have if user doesn't have mtls enforced, I would not block beta for it.

**Comment by bleggett** [comment]
> The optional way should be that inpod redirects only for new connections, which should not change much.

Yes, agreed this is very doable, with a deadline for the old connections, perhaps.

**Comment by nrjpoddar** [comment]
This raises a valid concern that we need to document clearly as a caveat for beta but we don't have to block beta release for Ambient if this is not implemented due to developer bandwidth constraints.

**Comment by linsun** [comment]
Agreed Neeraj, thanks for chiming in. @alpha-baby do you have any bandwidth to work on this?

**Comment by alpha-baby** [comment]
> Agreed Neeraj, thanks for chiming in. @alpha-baby do you have any bandwidth to work on this?

yes, i will commit pr to fix this later.
