### ISSUE TITLE
Refactor Galley and istioctl validation dependency on Mixer and Pilot packages

### ISSUE THREAD

**Issue by ayj** [istio/istio#4887]
Galley configuration validation depends on Mixer's own built-in templates, which effectively exposes Mixer internals to Galley. Instead, galley should only depend on the public configuration descriptions from istio/api.

**Comment by lichuqiang** [comment]
How's the thing going?
I'd like to help if possible :)

**Comment by ozevren** [comment]
@jeffmendoza 
Does it make sense to look at this, as part of your protoc-gen-validate work? It would be great if we can knock this off as part of that.

**Comment by jeffmendoza** [comment]
Sounds good.

**Comment by kyessenov** [comment]
There is a path forward since OOP uses proto descriptors for validation. I'll take a look if this can be moved forward.
