### ISSUE TITLE
Ingress gateway spans are named `egress`

### ISSUE THREAD

**Issue by braunsonm** [istio/istio#48884]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I set up Istio's tracing capabilities recently and noticed that traffic which is `client -> istio-gateway -> server` has a span name of `egress example.com`

I assume this is because from the perspective of the gateway the traffic is leaving the gateway to an upstream of `server`. I find this counter intuitive though to most understandings of ingress/egress terminology. Is there a way to properly name the spans to prevent confusion?

### Version

```Text
Istio 1.20.2
```

**Comment by hanxiaop** [comment]
I think it makes sense since egress is for traffic leaving? Which tracing system are you using?

**Comment by braunsonm** [comment]
@hanxiaop I'd like to know what perspective that is from. This is an ingress gateway yet the spans are labelled as egress.

Using opentelemetry with Tempo

**Comment by conradhanson** [comment]
In general, I would think the perspective should always be from istio service mesh.

That would mean if traffic is leaving the mesh, then it is labeled egress. If traffic is entering the mesh, then it is labeled ingress.

So if the client is part of the mesh, and the upstream server is outside of the mesh, then I would think the client's request to `example.com` with the `egress` label is correct.

**Comment by braunsonm** [comment]
I agree @conradhanson however in my example the upstream is in the service mesh and has a sidecar. What you end up seeing is a root span of egress from the gateway, and ingress to the sidecar.

I would expect ingress on both.

**Comment by conradhanson** [comment]
@braunsonm since the upstream is in the service mesh I would expect both spans to be labeled ingress too then

**Comment by braunsonm** [comment]
This remains an issue.
