### ISSUE TITLE
Support OpenTelemetry resource attributes in traces

### ISSUE THREAD

**Issue by braunsonm** [istio/istio#48885]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Envoy supports resource attributes through the standard `OTEL_RESOURCE_ATTRIBUTES` environment variable, however it has to be enabled via: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/tracers/opentelemetry/resource_detectors/v3/environment_resource_detector.proto#extension-envoy-tracers-opentelemetry-resource-detectors-environment

Ideally istio would support this in addition to tags. Resource attributes are critical to be able to set the `environment` that a service lives in.

**Describe alternatives you've considered**
There are no alternatives, you cannot change this property on istio-proxies. Perhaps it would be possible with an EnvoyFilter?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[x] Virtual Machine
[x] Multi Control Plane

**Comment by thiagogcm** [comment]
I guess this is being handled here: https://github.com/istio/api/pull/3002

**Comment by joaopgrassi** [comment]
Yes, I'm working on this!

**Comment by zirain** [comment]
wait for implement

**Comment by braunsonm** [comment]
Awesome work @joaopgrassi Is there any documentation on using this feature? I assume it will land in Istio 1.21

**Comment by joaopgrassi** [comment]
Hey @braunsonm unfortunately it didn't made on 1.21, so it will be for 1.22 only. As for documentation, you can see an example in the proto config for now (once it's live, we can also see it in the MeshConfig docs ) https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L1115
