### ISSUE TITLE
Workload on demand XDS test gap

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#48915]
https://github.com/istio/istio/blob/0727ad5a7ae2cf011415bb1b8377670469c01668/pilot/pkg/xds/workload_test.go#L175

Here if a full push happens, we would get removals for 127.0.0.1 and 127.0.0.2 unexpectedly. However, the test misses this because there happens to not be any full push during this time

**Comment by hzxuzhonghu** [comment]
Yesterday, i was investigating delta wds, and even cannot find a ut.

**Comment by howardjohn** [comment]
there is tests in workload_test.go. But it doesn't cover this case

**Comment by jessicegao** [comment]
@howardjohn is this friendly to first time contributor

**Comment by howardjohn** [comment]
@jessicegao I would hold on this one for now; I found this during a major refactoring of this system so it may be wasted effort if it is refactored away anyways. I will let you know if that changes
