### ISSUE TITLE
Allow to configure connect timeout for PassthroughCluster

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#48917]
We ran into an issue that the application connect timeout is honored for the PassthroughCluster as the diagram below, it caused application startup failure after migrated to Mesh since the app is sensitive to timeout.

![Screenshot 2024-01-23 at 13 44 44](https://github.com/istio/istio/assets/12857255/d7fcc376-7847-46c5-8e1f-41a78a5dc78a)

The PassthroughCluster is configured globally through the `MeshConfig` and the default was 1s later changed to 10s with https://github.com/istio/istio/pull/20920.
```
// Default timeout is 10s.
ConnectTimeout *duration.Duration `protobuf:"bytes,6,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
```
And here is the PassthroughCluster configdump:
```
 {
     "version_info": "2024-01-19T09:09:37Z/692833",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "PassthroughCluster",
      "type": "ORIGINAL_DST",
      "connect_timeout": "10s",
      "lb_policy": "CLUSTER_PROVIDED",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      }
```

There are few options:
1. Is it possible that PassthroughCluster connect timeout configurable through the DestinationRule(or just honor whatever DR configured in the namespace)? 
2. Introduce a proxy metadata like "proxyMetadata":{ "SIDECAR_PASSTHROUGHCLUSTER_CONNET_TIMEOUT":"50ms"} so we can customize for each workload.
3. Create an EnvoyFilter to customize the connect_timeout for PassthroughCluster
4. Import the external hosts to mesh through ServiceEntry/WorkloadEntry is also an option but consider there are a lot of WorkloadEntries and ports and also might need application code change since the discovery logic embedded in the client code, so this option would be challenging.

 

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shonecyx** [comment]
seems similar request as https://github.com/istio/istio/issues/15183

**Comment by howardjohn** [comment]
Why not just set it in MeshConfig? https://github.com/istio/istio/blob/388d5d1b9f37e7c3d15cf72967fad22f0b8e70fb/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L495 it is respected
