### ISSUE TITLE
Unclear rules for merging DR with `workloadselector`

### ISSUE THREAD

**Issue by believening** [istio/istio#48918]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

From both the [api](https://github.com/istio/api/blob/c1312a840eaa8ad1de5b20c8fdd55c31ef037732/networking/v1alpha3/destination_rule.proto#L294-L302) and mr's discussion([1](https://github.com/istio/istio/pull/37174/files#r834160333),[2](https://github.com/istio/istio/pull/37174#discussion_r832791802)), I don't understand the rules by which we merge dr's and the results.

I wrote a test [function](https://go.dev/play/p/ieGY63ODnL1) that merges 4 DR  that are in the same ns and have the same host in the order `withoutSel,withSelector,withoutSel,withSelector`, the two DRs with selectors set do not have the same selector.

I got the result like:

```
=== RUN   TestMergeDestinationRule
     finally we have 3 destination rules
     destination rule test/drWithout1 info:
     	from: [test/drWithout1 test/drWith1 test/drWithout2 test/drWith2]
     	spec: {"host":"httpbin.org","trafficPolicy":{"connectionPool":{"tcp":{"maxConnections":111,"connectTimeout":"1s"}},"tls":{"mode":"MUTUAL","clientCertificate":"/etc/certs/myclientcert.pem","privateKey":"/etc/certs/client_private_key.pem","caCertificates":"/etc/certs/rootcacerts.pem"}},"subsets":[{"name":"v1"},{"name":"v2"},{"name":"v3"}]}
     destination rule test/drWith1 info:
     	from: [test/drWith1 test/drWithout2]
     	spec: {"host":"httpbin.org","trafficPolicy":{"connectionPool":{"tcp":{"maxConnections":111,"connectTimeout":"1s"}},"tls":{"mode":"MUTUAL","clientCertificate":"/etc/certs/myclientcert.pem","privateKey":"/etc/certs/client_private_key.pem","caCertificates":"/etc/certs/rootcacerts.pem"}},"subsets":[{"name":"v2"}],"workloadSelector":{"matchLabels":{"app":"app1"}}}
     destination rule test/drWith2 info:
     	from: [test/drWith2]
     	spec: {"host":"httpbin.org","subsets":[{"name":"v3"}],"workloadSelector":{"matchLabels":{"app":"app2"}}}
--- PASS: TestMergeDestinationRule (0.00s)
```

There are two issues:

1. We got a DR without a selector that merges regardless of the selector difference. 
2. Merges are very sensitive to order (actually creation time)

It makes more sense if we sorts DRs based on whether they have a `WorkloadSelector` set or not, in addition to CreationTime. Of course this also means that the priority for `TrafficPolicy` and `Subset` with the same name changes as well.

After not modifying the mergeDestinationRule function and just sorting the DRs first based on whether the WorkloadSelector is set or not, the result is as follows:
```
=== RUN   TestMergeDestinationRule
     finally we have 3 destination rules
     destination rule test/drWith1 info:
     	from: [test/drWith1 test/drWithout1 test/drWithout2]
     	spec: {"host":"httpbin.org","trafficPolicy":{"connectionPool":{"tcp":{"maxConnections":111,"connectTimeout":"1s"}},"tls":{"mode":"MUTUAL","clientCertificate":"/etc/certs/myclientcert.pem","privateKey":"/etc/certs/client_private_key.pem","caCertificates":"/etc/certs/rootcacerts.pem"}},"subsets":[{"name":"v1"},{"name":"v2"}],"workloadSelector":{"matchLabels":{"app":"app1"}}}
     destination rule test/drWith2 info:
     	from: [test/drWith2 test/drWithout1 test/drWithout2]
     	spec: {"host":"httpbin.org","subsets":[{"name":"v3"},{"name":"v1"},{"name":"v2"}],"workloadSelector":{"matchLabels":{"app":"app2"}}}
     destination rule test/drWithout1 info:
     	from: [test/drWithout1 test/drWithout2]
     	spec: {"host":"httpbin.org","subsets":[{"name":"v1"},{"name":"v2"}]}
```

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.20.0
data plane version: 1.20.0 (5 proxies)
```

**Comment by leosarra** [comment]
Thank you @believening for reporting this, I feel this needs to be fixed.
I would like to hear @kfaseela opinion before I start working on the code changes

**Comment by kfaseela** [comment]
> Thank you @believening for reporting this. I feel DR_with_selector should get priority in a merge with a DR_without_selector, therefore the ordering that does not rely exclusively on creationTime needs to be enforced. Also the results of the first test case is concerning, I think the merge in that case was not correct. I would like to hear @kfaseela opinion on this, in the meantime I'm looking into the code to see what is going on and see what could be changed.

Here is the merge logic: https://github.com/istio/istio/blob/master/pilot/pkg/model/destination_rule.go#L35

**Comment by believening** [comment]
> > Thank you @believening for reporting this. I feel DR_with_selector should get priority in a merge with a DR_without_selector, therefore the ordering that does not rely exclusively on creationTime needs to be enforced. Also the results of the first test case is concerning, I think the merge in that case was not correct. I would like to hear @kfaseela opinion on this, in the meantime I'm looking into the code to see what is going on and see what could be changed.
> 
> Here is the merge logic: https://github.com/istio/istio/blob/master/pilot/pkg/model/destination_rule.go#L35

In fact, I was thinking that the current merge result, is not quite in line with normal thinking(This expression is the result of AI translation, not sure it is accurate), and is not well predictable based on the comment.

**Comment by kfaseela** [comment]
May be we can close this now?

**Comment by leosarra** [comment]
Yes, DR merging is now done based on both the selector and the creation timestamp.
I will proceed and close this
