### ISSUE TITLE
503 Upstream failures during deployment with istio ingress gateway and AWS NLB

### ISSUE THREAD

**Issue by JacobAmar** [istio/istio#48957]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello,
I am currently working with two services, Service A and Service B, serviced by an istio ingress gateway per service behind an AWS network load balancer. Service A has approximately 500 pods, while Service B has around 100 pods.

Recently, we have been experiencing numerous 503 upstream failures on our istio-ingress-gateway during our deployments of Service A. I have conducted a tcpdump and found reset reason indicated as "connection failure". This issue appears to occur between the AWS network load balancer and the ingress gateway pod.

Upon reviewing the istiod pods logs, I found multiple instances of the message "couldn't find "namespace/pod" in informer index". Interestingly, these logs referred to a pod that had been deleted almost 15 minutes before the log was generated.

Also getting the same logs for nodes that were deleted

I'm unsure of what might be causing this issue. If anyone has encountered something similar or can provide any guidance, I would greatly appreciate it.

Thank you in advance for your assistance.

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.16.1
data plane version: 1.16.1 (1118 proxies)
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.17-eks-8cb36c9
$ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}
```

**Comment by choigonyok** [comment]
I had similar problem before, and I resolved this in sequence below

* deploy NLB in public subnet, and k8s cluster in private subnet
* change istio-ingressgateway svc type from LoadBalancer to NodePort
* by using 'TargetGroupBinding', append ingress gateway to NLB's target group
* configure appropriate aws security group

**Comment by JacobAmar** [comment]
> I had similar problem before, and I resolved this in sequence below
> 
> * deploy NLB in public subnet, and k8s cluster in private subnet
> * change istio-ingressgateway svc type from LoadBalancer to NodePort
> * by using 'TargetGroupBinding', append ingress gateway to NLB's target group
> * configure appropriate aws security group

Hi @choigonyok what node port change ? we are using nlb directly to pod IP

**Comment by choigonyok** [comment]
@JacobAmar
How do you directly connect pod IP with NLB? Are you using aws-lb-controller?

I wannt know where `nlb` and `gateway pod` are.

Both of them are in private subnet? or public subnet?

**Comment by YanoGit** [comment]
I have an EKS with Istio NLB. To create the LoadBalancer, I used the AWS Load Balancer Controller. Check its Listeners and ensure they are configured correctly. I encountered several issues with the targets, so also verify if your Istio Ingress has the necessary annotations for AWS.
