### ISSUE TITLE
Use multiple configmaps containing URIs to ratelimit in Global Ratelimit service

### ISSUE THREAD

**Issue by mks27** [istio/istio#48989]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am running web-services on tomcat inside pods and about 40-50 urls are exposed in each of these pod. I am running multiple such pods. Now I want to implement ratelimit on these url, I tried global ratelimit but for that i have to maintain all the urls of different pod in a single cm. I want to separate the cm for each pod, so that i can maintain urls of each pod in its specific cm file and can implement ratelimit using all these cm files instead of single one. Is this possible?

### Version

```Text
istio - 1.18.1
kubernetes - 1.24.9
```

**Comment by zirain** [comment]
I think this related to which ratelimit backend you used.

**Comment by mks27** [comment]
I am using ratelimit and redis service as mentioned in official istio documentation - https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/

**Comment by zirain** [comment]
I think this related to the implement of envoy/ratelimit, which isn't related to istio.
you'd better raise up on upstream repo.
