### ISSUE TITLE
distribution reporter support incremental eds?

### ISSUE THREAD

**Issue by lhanjian** [istio/istio#48985]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
It seems DistributionReport  only support Istio CR/K8s GatewayAPI

May DistributionReport support Endpoints? 

If DistributionReport can feed back the push results of eds, then we can clearly know whether the pod's traffic switch has been successfully completed by dataplain.
​
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
it seesm issue 30179 have some related information

**Comment by howardjohn** [comment]
Is it not one of the supported types? https://github.com/istio/istio/blob/a65841e01642a2f6d638c4d3cc41af9f261ac0a9/pilot/pkg/xds/eventhandler.go#L26

**Comment by howardjohn** [comment]
Ah I think we just don't report it here (https://github.com/istio/istio/blob/8c74063ea7ab759339a5697be01c03afdce3a2c5/pilot/pkg/xds/debug.go#L374) for some reason

**Comment by ymesika** [comment]
Not sure there is a specific reason for omitting the endpoint from the reported json.
I opened a PR to add it.

**Comment by lhanjian** [comment]
May i reopen this issue? @ymesika 

My question is not only debug http api or istio-wait cmd, 

it is distribuiton report(inprogress resource) in Configmap of istio.

**Comment by ymesika** [comment]
But `inprogressresources` reported there are Istio resources (like virtual services) so I'm wondering what you mean by EDS status there.

**Comment by lhanjian** [comment]
> But `inprogressresources` reported there are Istio resources (like virtual services) so I'm wondering what you mean by EDS status there.

yes,

so eds status doesn't exist in `inprogressresources`
