### ISSUE TITLE
Documentation on Istio Federation with SPIRE on multiple mesh

### ISSUE THREAD

**Issue by haithamshahin333** [istio/istio#48998]
**Describe the feature request**

Similar to #40589, I wanted to see if the team can point out an example/doc around mesh federation such that distinct meshes are able to communicate over mTLS and each mesh uses Spire for certificate provisioning.

The goal is that if I have cluster 1 in domain1.com and cluster 2 in domain2.com, then assuming the Spire servers federate, that workloads from cluster 1 can securely connect to workloads in cluster 2. Keep in mind that this is NOT a multi-cluster mesh, but rather distinct/independent meshes that form trust through the Spire federation.

Appreciate your guidance!

**Describe alternatives you've considered**

There are a number of issues that touch on this subject, but none seem complete and don't provide a working solution.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kpanic9** [comment]
We are also considering mesh federation, would be great to have documentation/tutorials for this.
