### ISSUE TITLE
Istio CNI agent upgrades

### ISSUE THREAD

**Issue by bleggett** [istio/istio#49009]
**Describe the feature request**

Istio CNI node agent can be upgraded in-place without traffic disruption in ambient with the merge of https://github.com/istio/istio/pull/48253, but upgrading the CNI node agent still has some corner cases that would need to be addressed and tested before upgrades can be fully safe, specifically around making sure we catch new ambient pods that might have popped up "during" the upgrade, while the CNI is in a transitional state on the node.

https://github.com/istio/istio/issues/48286 is partially related to this, and might be enough on its own, if we can prevent _new_ pods from being scheduled on a node with an unready CNI agent.

We might need something rather like detect-and-repair in sidecars here, but TBD

Either way, we should have tests.

**Describe alternatives you've considered**

Previous PRs: https://github.com/istio/istio/pull/48817

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bleggett** [comment]
A further issue around upgrades is how the CNI agent could tell the difference between "being shut down for _upgrade_" and "being shut down for _uninstall_", for pods that are still captured.

In the former case, we would not want to disturb or unhook ztunnel and iptables from the pod.

In the latter case, we would.

**Comment by zengyuxing007** [comment]
> A further issue around upgrades is how the CNI agent could tell the difference between "being shut down for _upgrade_" and "being shut down for _uninstall_", for pods that are still captured.
> 
> In the former case, we would not want to disturb or unhook ztunnel and iptables from the pod.
> 
> In the latter case, we would.
> 
> To me this still points to some kind of detect-and-repair mechanism like the CNI has for sidecars.

For upgrades, maybe we can have a global status under a cr which kind like IstioStatus (crd)

**Comment by bleggett** [comment]
> > A further issue around upgrades is how the CNI agent could tell the difference between "being shut down for _upgrade_" and "being shut down for _uninstall_", for pods that are still captured.
> > In the former case, we would not want to disturb or unhook ztunnel and iptables from the pod.
> > In the latter case, we would.
> > To me this still points to some kind of detect-and-repair mechanism like the CNI has for sidecars.
> 
> For upgrades, maybe we can have a global status under a cr which kind like IstioStatus (crd)

Yes possibly. Either way, whatever we do has to work with Helm install/upgrade as a baseline, we cannot do anything that relies on special `istioctl` tricks.

**Comment by bleggett** [comment]
See also https://github.com/istio/istio/issues/49067

**Comment by keithmattix** [comment]
Not stale
