### ISSUE TITLE
Clean Install via Helm (v1.20.2) results webhook failing

### ISSUE THREAD

**Issue by kworkbee** [istio/istio#49019]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I installed the Helm Chart, `istio/base` + `istio/istiod`, to build the Control Plane in the External Cluster, but when I deploy Ingress Gateway (via `istio/gateway`), the webhook fails to execute with a log below:

```
Internal Error occurred: failed calling webhook `object.sidecar-injector.istio.io`: failed to call webhook: Post `https://istiod.istio-system.svc:443/inject?timeout=10s`: context deadline exceeded
```

I use an EKS cluster and there is no abnormality in the security group settings.

### Version

```Text
Istio 1.20.2
Helm 3.13.2
kubectl (Client 1.28.2, Server 1.28.5 - EKS)
```

### Additional Information

Calling via curl to Pilot is fine

**Comment by hanxiaop** [comment]
You may check https://github.com/istio/istio/issues/36955.

**Comment by kworkbee** [comment]
@hanxiaop I'm sorry, but I've already checked the link you shared, and as mentioned above, Security Group setting has Inbound open for all ports. If that's not the point I'm trying to make, please tell me more specific information.

**Comment by zirain** [comment]
make sure istiod is ready, check the network between kube-apiserve and istiod.

**Comment by kworkbee** [comment]
@zirain 
```
2024-01-26T12:27:12.653276Z error controllers error handling istiod-default-validator, retrying (retry count: 25): webhook is not ready, retry controller=validation
2024-01-26T12:28:12.654731Z info validationController Not ready to switch validation to fail-closed: dummy invalid config not rejected
2024-01-26T12:28:12.654770Z info validationController validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Ignore, resourceVersion=30389262) is up-to-date. No change required.
```
There are no specifics other than repeatedly sending out the following message.

**Comment by hanxiaop** [comment]
@kworkbee Have you tried https://github.com/istio/istio/wiki/Troubleshooting-Istio#diagnostics? It takes too long to call the webhookin your log.

**Comment by kworkbee** [comment]
@hanxiaop @zirain Although it was connected to `Service` in the `MutatingWebbookConfiguration`, `kube-apiserver`` seemed to connect using Pod IP, so I first opened it for port 15017 and checked that it was connected normally.
By the way, can I set custom `NO_PROXY` env in EKS (Managed)?

**Comment by zirain** [comment]
I'm not an eks expert, for what I can see, this's more like an issue from AWS not istio, you shlould ask help from AWS.

**Comment by hanxiaop** [comment]
Agree with @zirain, this is a kind of network problem, which is not related to Istio.

**Comment by db2crush** [comment]
Same problem. how can you fix it?

**Comment by kworkbee** [comment]
@db2crush Do you use EKS as clusters?

**Comment by kworkbee** [comment]
@db2crush In my case, I am using EKS. Since Control Plane is managed by AWS, so there is no way to know what the detailed configuration is, but on CloudWatch Log, it is confirmed that `kube-apiserver` accesses `Pod` IP straight away without going through `Service` of webhook configuration. Therefore, the issue was resolved by changing Security Group setting to open for the port exposed by the `Pod`.
