### ISSUE TITLE
istio ambient layered authz design

### ISSUE THREAD

**Issue by linsun** [istio/istio#49031]
Old doc: https://docs.google.com/document/d/1EDnk9cyji8GtpK7tF6czqiStd7UTujoIhhBUi1XYAQM/edit#heading=h.stll71jzvhaf

New doc: https://docs.google.com/document/d/1e7BFvBZL622YzgjDoaXC7MFOObu81vc44FO9VKx2AIo/edit#heading=h.4wl7fsia5onn

@louiscryan pls keep us updated in github as well.

**Comment by louiscryan** [comment]
Yup, first up is #49032 then Ill get this completed.
