### ISSUE TITLE
failed (add): exec: "sh": executable file not found in $PATH

### ISSUE THREAD

**Issue by ssurapan** [istio/istio#49038]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Warning  FailedCreatePodSandBox  22s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1b84b823053ccde1c218e402407ee2a1fde9db134d4373b3ea18061dad04230a": plugin type="istio-cni" name="istio-cni" failed (add): exec: "sh": executable file not found in $PATH
  Warning  FailedCreatePodSandBox  6s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1609d24df83e6b7ee26493a923b1b68c4d1fde55efdde10485122e2f6b7ed257": plugin type="istio-cni" name="istio-cni" failed (add): exec: "sh": executable file not found in $PATH
 
It works in 1.20.1

### Version

```Text
istio 1.20.2
```

**Comment by ssurapan** [comment]
this issue is happening on EKS bottlerocket

**Comment by ssurapan** [comment]
i kept the istio control plane at 1.20.2  . just changed istio cni to 1.20.1 and this configuration works

**Comment by ymesika** [comment]
A similar issue: https://github.com/istio/istio/issues/48746
This is fixed by https://github.com/istio/istio/pull/48757

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/48746
