### ISSUE TITLE
Ambient waypoint capture for service and workload design

### ISSUE THREAD

**Issue by linsun** [istio/istio#49032]
[Ambient - Capture for Services and Workloads](https://www.google.com/url?q=https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit%23heading%3Dh.i456k47e7s5d&sa=D&source=calendar&ust=1706736080204490&usg=AOvVaw2RYHuWzwpu0LI-PLUgoEWZ)

**Comment by linsun** [comment]
@louiscryan please keep us updated in github as well

**Comment by louiscryan** [comment]
Thanks @linsun. Reviews are in-flight and good progress is being made. Ill break this out into a task-list once doc is signed off

**Comment by howardjohn** [comment]
Doc is approved, work items tracked in https://github.com/istio/istio/issues/49438
