### ISSUE TITLE
Istio ambient contract and layer design

### ISSUE THREAD

**Issue by linsun** [istio/istio#49030]
Link to doc: [Istio's Layered Future, Policy and Conformance](https://www.google.com/url?q=https://docs.google.com/document/d/1fg95r3C8Iqyivs0OO3z7diiaL6SkD6Ke9SqxaufAVBQ/edit&sa=D&source=calendar&ust=1706736080204490&usg=AOvVaw3W48SYRPhXK-lrlXL1ehOG)

@louiscryan please keep us posted periodically in github on the progress as well, thanks!

**Comment by louiscryan** [comment]
Not blocking for beta but want to make sure this is nailed down for clarity and docs/blog is published. Will follow #49032 and #49031
