### ISSUE TITLE
Support for JWKS refresh in Istiod when a non cached KID is seen in JWT token

### ISSUE THREAD

**Issue by martin2176** [istio/istio#49044]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
IdP such as Azure AD will do key rotation unannounced. When a new public key is introduced to jwks, new JWT tokens are signed with this new private key almost immediately.

How it will manifest as an issue:
Clients will get new JWT tokens signed by the newly introduced private key and the new KID will show up in their JWT tokens.
This new KID will not be in the Istiod JWKS cache for 20 minutes. This interval can be set small if desired.
However setting cache interva smalll doesn't entirely get rid of the problem. 
The right solution would be for Istiod to refresh JWKS when it sees a new KID which is not in JWKS cache.

Pilot variable PILOT_JWT_ENABLE_REMOTE_JWKS  now support Envoy as an option however whether JWKS refresh happens on a cache miss of KID is not clear is still unknown. Does it? Or Does Istiod now does JWKS refresh upon a KID miss in cache?

**Describe alternatives you've considered**
Run a very cache refresh interval such as 1 minute or so. But kind of defeats the purpose of cache and not addressing the root cause.
set to 1minute or less  PILOT_JWT_PUB_KEY_REFRESH_INTERVAL

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Azure AD doc describing the issue and requirement from the key verifier
Eg: 
https://learn.microsoft.com/en-us/entra/identity-platform/signing-key-rollover
Quoting relevant info from above doc
For security purposes, the Microsoft identity platform’s signing key rolls on a periodic basis and, in the case of an emergency, could be rolled over immediately.

"Checking every 24 hours for updates is a best practice, with throttled (once every five minutes at most) immediate refreshes of the key document if a token is encountered that doesn't validate with the keys in your application's cache."

Essentially: the key verifier (envoy or istiod) should do immediate jwks refresh when a new KID

**Comment by zirain** [comment]
will change PILOT_JWT_ENABLE_REMOTE_JWKS to envoy help?

**Comment by martin2176** [comment]
PILOT_JWT_ENABLE_REMOTE_JWKS - As far as I know, this merely handoff the JWKS fetching from Pilot to Envoy and pass the responsibility of caching and keeping public keys (jwks) refreshed to Envoy.

However unclear How envoy does JWKS refresh. ?
Does envoy fetch a new JWKS if it receives a JWT with a KID which is not cached in envoy. (default 10m jwks envoy cache)

So the issue is not going away with this setting: PILOT_JWT_ENABLE_REMOTE_JWKS 
It merely hand off the responsibility from Pilot to envoy.

As per this envoy issue, this "new KID" is still an outstanding issue - 
https://github.com/envoyproxy/envoy/issues/14557#issuecomment-754325193

Is there anything Istiod can do in the meantime to address this "new KID" issue

**Comment by zirain** [comment]
IMO, envoy async fetch mode is the future, if envoy doesn't, istio should wait for envoy first.
WDYT @istio/wg-security-maintainers

**Comment by hzxuzhonghu** [comment]
> The right solution would be for Istiod to refresh JWKS when it sees a new KID which is not in JWKS cache.

How does istiod get to know when it is refreshed.? I donot think we can do this.

**Comment by martin2176** [comment]
> > The right solution would be for Istiod to refresh JWKS when it sees a new KID which is not in JWKS cache.
> 
> How does istiod get to know when it is refreshed.? I donot think we can do this.
true...If Istiod doesn't see the JWT token it cant possibly know when a new KID arrives.

Just a thought:-

envoy sees to be recording jwt verification status code and message in failed_status_in_metadata as per envoy doc below
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto


The values of this field will be code and message and they will contain the JWT authentication failure status code and a message describing the failure.
I ran a test against Istio by manipulating the jwt header for a KID I know doesn't exist in JWKS and I get a clear message in my http call to the service
"Jwks doesn't have key to match kid or alg from Jwt". I am thinking this is coming from envoy
If Istiod can get the verification error status from envoy and finding the status message related to non-matching kid, proceeds to do a jwks refresh and send out the refreshed jwks to all the envoys.
It wont be the perfect solution as few verification requests will fail while istiod refreshes the cache and push it out. (Apps can retry with same jwt token). And it would be better than waiting for the next periodic cache refresh interval.

**Comment by hzxuzhonghu** [comment]
Istiod cannot get that error message. Even if istiod can get that error, i donot think it should be responsible do that. This can cause DDOS vulnerability

**Comment by costinm** [comment]
Envoy gets a JWT, decodes the JWT - and finds the issuer and KID. 

At this point it has the JWTs that Istiod has pushed - or it can fetch JWT from 'remoteJWKS' if that's how it is configured.

Istiod has no visibility into the JWT the each envoy sees - it can't check the status or errors in envoy. 

Assuming Envoy code is handling this properly - or it can be fixed, the correct behavior would be for Envoy to 
attempt to fetch the JWTs from the remoteJWKS URL if the KID is unknown. 

This has some unfortunate effects - an attacker can do a DOS by sending a lot of JWTs with invalid signature but different KIDs, causing all envoys that get this request to fetch from the OIDC well known - with the retries we do it's an amplification attack, so hopefully envoy has code to not fetch too often. But it may work.

If Envoy does not have permissions to connect to the remoteJWKS - and user expects Istiod ( which presumably has the network permissions ) - we may be able to point remoteJWKS to an egress gateway or use Istiod as a cache.

The other approach - which is probably much better but requires issuers/IDPs to do the right thing - is to not issue tokens with the new key immediately, but instead distribute the new key and wait for some time (1h, 1 day ?) before 
starting to use it. 

I suspect the best short term option is to configure JWT fetching from envoy and make sure envoy is fetching with some rate limitting if KID not found.

**Comment by martin2176** [comment]
I understand the DOS possibility you explained which is very valid especially if the Istio Ingress is exposed publicly.

The short term approach you described would be great if it can be implemented in envoy 
ie. fetch JWKS with some rate limit . Also give a flag to turn on/off that feature for customer (preferably on a workload selector basis )
The flag could allow customers to decide whether to turn off/on depending on whether envoy is not exposed publicly( no bad actors) vs public (bad actors).

As far as IdPs not to issue tokens with new key immediately - that is how most IdPs do key rotation. However IdP warn consumers not to rely on that mechanism. Since there may be occasions where an immediate key rotation may be needed such as compromised key. For eg. Azure AD describe this in their signing key rollover document

![image](https://github.com/istio/istio/assets/14482998/31b70cd1-f3f6-4dac-9200-ca6c42319b9a)

**Comment by JorTurFer** [comment]
> The other approach - which is probably much better but requires issuers/IDPs to do the right thing - is to not issue tokens with the new key immediately, but instead distribute the new key and wait for some time (1h, 1 day ?) before
> starting to use it.

Sorry, but I have to respectfully disagree with you. There is an official spec for OIDC protocol that defines this behaviour: https://openid.net/specs/openid-connect-core-1_0.html#RotateEncKeys

The official (and globally accepted) spec says literally:
>The signer can begin using a new key at its discretion and signals the change to the verifier using the kid value. The verifier knows to go back to the jwks_uri location to re-retrieve the keys when it sees an unfamiliar kid value.

![image](https://github.com/user-attachments/assets/b61c9c29-e143-4b37-88c5-9a27b2945900)

I fully understand that istio as project has its own security things to take into account and it's totally right, but suggesting to IdPs to not follow the standard isn't the right way to handle things outside istio scope. 
An Identity Provider has the right to rotate/revoke/disable a signing key for multiple reasons, all of them related with the security. 

Although for "regular operation", an IdP can generate they with enough time before using the new key, the current scenario could be treated as a potential security risk as an attacker who get access to the signing keys can issue valid tokens that istio will accept until the cache expires despite the OIDC spec already defines a security mechanism to prevent this. So, If I gain access to the signing key, actually nothing can be done from the IdP because istio/envoy is catching the revoked key as still valid.

**Comment by JorTurFer** [comment]
This issue is still relevant:
> Although for "regular operation", an IdP can generate them with enough time before using the new keys, the current scenario could be treated as a potential security risk as an attacker who get access to the signing keys can issue valid tokens that istio will accept until the cache expires despite the OIDC spec already defines a security mechanism to prevent this. So, If I gain access to the signing key, actually nothing can be done from the IdP because istio/envoy is catching the revoked key as still valid.

**Comment by SabySen** [comment]
reviving this issue as Ping also has the same action as mentioned in the problem statement where it issues new KID for every request sent

**Comment by Juansasa** [comment]
I think this is a very valid PR ?
