### ISSUE TITLE
Add pprof to Istio CNI

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [istio/istio#49053]
**Describe the feature request**

We observe [memory spikes](https://github.com/istio/istio/discussions/48922) when using Istio CNI, and in order to debug these spikes, it would be nice to have pprof enabled for Istio CNI. 

This issue is about adding pprof support to Istio CNI to allow for troubleshooting Istio CNI pods.

**Describe alternatives you've considered**

We tried using debug logging to determine what causes memory spikes, but we haven't found anything that might be causing this issue.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bleggett** [comment]
I'm not sure if the memory spikes observed in https://github.com/istio/istio/discussions/48922 would still be in 1.21, but either way pprof support generally would be welcome.

**Comment by ilrudie** [comment]
I've implemented pprof before. I can probably take a look at this.

**Comment by ilrudie** [comment]
Some other stuff has come up. I may circle back but going to let this one go back into the pool for now in case someone else has cycles and interest.
