### ISSUE TITLE
AWS EKS Istio Ambient Node connectivity 

### ISSUE THREAD

**Issue by tomahkvt** [istio/istio#49055]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have an AWS EKS Cluster with different networks for Nodes and pods. I have configurated Istio Ambient Mesh at this cluster using this instruction https://istio.io/latest/docs/ops/ambient/getting-started/. I don't have connectivity between pods on different nodes.

I have the errors in ztunnel pods 
2024-01-29T09:48:12.068865Z  WARN xds{id=72}: ztunnel::xds::client: XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: dns error: failed to lookup address information: Temporary failure in name resolution, retrying in 15s
2024-01-29T09:48:47.098195Z  WARN xds{id=73}: ztunnel::xds::client: XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: dns error: failed to lookup address information: Temporary failure in name resolution, retrying in 15s
2024-01-29T09:49:04.901310Z  WARN xds{id=31}: ztunnel::xds::client: XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: tcp connect error: Connection timed out (os error 110), retrying in 15s
2024-01-29T09:51:42.223695Z  WARN xds{id=78}: ztunnel::xds::client: XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: dns error: failed to lookup address information: Temporary failure in name resolution, retrying in 15s
2024-01-29T09:52:17.253477Z  WARN xds{id=79}: ztunnel::xds::client: XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: dns error: failed to lookup address information: Temporary failure in name resolution, retrying in 15s

I checked I have full connectivity between nodes. There is Security groups with full access.
I tested this configuration for case when nodes and pods have the same network and it works.
The problem is for case when AWS EKS Cluster with different networks for Nodes and pods.

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (2 proxies)
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
```

### Additional Information

Target cluster context: aws-test

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-01-29 10:50:11.3692304 +0200 EET

Cluster endpoint: CLI version:
version.BuildInfo{Version:"1.20.2", GitRevision:"5f5d657c72d30a97cae97938de3a6831583e9f15", GolangVersion:"go1.21.5", BuildStatus:"Clean", GitTag:"1.20.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.2", GitRevision:"5f5d657c72d30a97cae97938de3a6831583e9f15", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.2}

Fetching logs for the following containers:

default/details-v1/details-v1-698d88b-mmdzh/details
default/notsleep/notsleep-685df55c6c-62p2d/notsleep
default/productpage-v1/productpage-v1-675fc69cf-hh2hm/productpage
default/ratings-v1/ratings-v1-6484c4d9bb-qcb9n/ratings
default/reviews-v1/reviews-v1-5b5d6494f4-znwsk/reviews
default/reviews-v2/reviews-v2-5b667bcbf8-t6xkd/reviews
default/reviews-v3/reviews-v3-5b9bd44f4-fp6cg/reviews
default/sleep/sleep-7656cf8794-2zbvp/sleep
istio-system/istio-cni-node/istio-cni-node-954pf/install-cni
istio-system/istio-cni-node/istio-cni-node-9c6r7/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-7485988b9-t28vk/istio-proxy
istio-system/istiod/istiod-78c7c47c74-bppng/discovery
istio-system/ztunnel/ztunnel-5rhq5/istio-proxy
istio-system/ztunnel/ztunnel-dr76m/istio-proxy

Fetching Istio control plane information from cluster.

Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
[Run]([bug-report.tar.gz](https://github.com/istio/istio/files/14082517/bug-report.tar.gz)) 'kubectl label namespace infra-tools istio-injection=enabled' to enable it, or 'kubectl label namespace infra-tools istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at istio-1.20.2/bug-report.tar.gz.
Time used for creating the tar file is 59.089746ms.
Cleaning up temporary files in /tmp/bug-report.
Done.
[bug-report.tar.gz](https://github.com/istio/istio/files/14082548/bug-report.tar.gz)

**Comment by ymesika** [comment]
I noticed in #42340 [a comment](https://github.com/istio/istio/issues/42340#issuecomment-1913775449) about AWS being supported in 1.21.0 or current master.

**Comment by tomahkvt** [comment]
Hi @ymesika I have just tested istio-1.21.0-beta.0. But it doesn't work.
$ istioctl version
client version: 1.21.0-beta.0
control plane version: 1.21.0-beta.0
data plane version: 1.21.0-beta.0 (1 proxies)
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde

$ istioctl bug-report

Target cluster context: aws-test

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-01-29 16:21:46.187507805 +0200 EET



Cluster endpoint: https://0934B1BA72A03071CD256B7FBE68770F.gr7.eu-west-1.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.21.0-beta.0", GitRevision:"db553bed81f75526a2c15c05cc2023a6fe366923", GolangVersion:"go1.21.6", BuildStatus:"Clean", GitTag:"1.21.0-beta.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.21.0-beta.0", GitRevision:"db553bed81f75526a2c15c05cc2023a6fe366923", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.21.0-beta.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.21.0-beta.0}


Fetching logs for the following containers:

default/details-v1/details-v1-698d88b-khchg/details
default/notsleep/notsleep-685df55c6c-2rmkx/notsleep
default/productpage-v1/productpage-v1-675fc69cf-k942l/productpage
default/ratings-v1/ratings-v1-6484c4d9bb-prmk4/ratings
default/reviews-v1/reviews-v1-5b5d6494f4-lrppd/reviews
default/reviews-v2/reviews-v2-5b667bcbf8-6w4b6/reviews
default/reviews-v3/reviews-v3-5b9bd44f4-4d788/reviews
default/sleep/sleep-7656cf8794-8w8jb/sleep
istio-system/istio-cni-node/istio-cni-node-6mq2d/install-cni
istio-system/istio-cni-node/istio-cni-node-zqjq8/install-cni
istio-system/istio-ingressgateway/istio-ingressgateway-6ffbb76c5-kbpqx/istio-proxy
istio-system/istiod/istiod-64648d45fd-4svck/discovery
istio-system/ztunnel/ztunnel-8lpqq/istio-proxy
istio-system/ztunnel/ztunnel-zffjh/istio-proxy

Fetching Istio control plane information from cluster.


Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:

Creating an archive at /bug-report.tar.gz.
Time used for creating the tar file is 37.712458ms.
Cleaning up temporary files in /tmp/bug-report.
Done.
[bug-report.tar.gz](https://github.com/istio/istio/files/14085512/bug-report.tar.gz)

**Comment by ymesika** [comment]
@tomahkvt I don't see #48212 included in https://github.com/istio/istio/commits/1.21.0-beta.0/

**Comment by linsun** [comment]
Sorry, just got confirmation from Eric that the change is not in beta 0 yet, but should be in -beta.1 since it was merged after beta.0 was released. I expect that the new build will be available in a day or 2.

**Comment by dhawton** [comment]
You can also test sooner using dev builds if you do not want to wait for the next beta build. These are built for each commit made.

HUB=gcr.io/istio-testing
TAG=1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5

Where 015b39fc798ea20134c67c179397f6e3713a66d5 is the commit hash of the release-1.21 branch. In this case, that commit hash is the latest one and includes the PR above.

**Comment by tomahkvt** [comment]
Hi @dhawton I tried to install this version of istio ambient mesh by following command
`istioctl install --set profile=ambient -y --set "components.ingressGateways[0].enabled=true" --set "components.ingressGateways[0].name=istio-ingressgateway" --set tag=$TAG --set hub=gcr.io/istio-testing`
I got an error in pods istio-cni-node:
Error: failed to create ambient nodeagent service: error initializing the ztunnel server: failed to listen unix: listen unixpacket /var/run/ztunnel/ztunnel.sock: bind: no such file or directory

**Comment by dhawton** [comment]
What is the output of `istioctl version` and the value of TAG? You will need the istioctl from that version if you don't have it, as the manifests are different as well. If you need an updated istioctl binary, you can grab them from https://console.cloud.google.com/storage/browser/istio-build/dev/1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5;tab=objects?prefix=&forceOnObjectsSortingFiltering=false.

**Comment by tomahkvt** [comment]
TAG=1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5
client version: 1.21.0-beta.0
control plane version: 1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5
data plane version: 1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5 (3 proxies)

**Comment by tomahkvt** [comment]
@dhawton 
istioctl version
client version: 1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5
control plane version: 1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5
data plane version: 1.21-alpha.015b39fc798ea20134c67c179397f6e3713a66d5 (3 proxies)
Now I see that this version is working for use case mTLS communication and L4 telemetry.
I tried to Deploy a waypoint proxy for the productpage service:
istioctl x waypoint apply --service-account bookinfo-productpage
I got an error:
Error: missing Kubernetes Gateway CRDs need to be installed before applying a waypoint: the server could not find the requested resource (patch gateways.gateway.networking.k8s.io bookinfo-productpage)

**Comment by dhawton** [comment]
Istio does not install the Kubernetes Gateway API. You may have missed step #3 here: https://istio.io/latest/docs/ops/ambient/getting-started/#download.

**Comment by tomahkvt** [comment]
@dhawton You are right. It looks like everything works. Would you say when this build will become a stable release?

**Comment by linsun** [comment]
Yay, thank you for the validation!  Yes, we expect this to be in the beta-1 build of istio 1.21, which is expected to be out in the new few days at https://github.com/istio/istio/tags

**Comment by linsun** [comment]
@tomahkvt let me know if this issue can be closed now, thanks!

**Comment by tomahkvt** [comment]
@linsun Thank you a lot. Yes you can close this issue.

**Comment by dhawton** [comment]
> @dhawton You are right. It looks like everything works. Сould you tell me when this build will become a stable release?

The planes dates can be found in the wiki, https://github.com/istio/istio/wiki/Istio-Release-1.21. it's always possible these can slide but that is when you can expect a stable release as of now.

**Comment by tomahkvt** [comment]
I hope that the tested changes will be included in the next beta release and I will be able to test these changes at other my services.

**Comment by dhawton** [comment]
> I hope that the tested changes will be included in the next beta release and I will be able to test these changes at other my services.

Yes. They're part of the branch already so once the release managers kick off the beta.1 build, they will be included. Thanks for taking the time to test EKS!

**Comment by anuraj-narayanan** [comment]
I am still getting this issue in EKS. istio version is 1.23.0

                                                                                                                                                                                │
│ 2024-08-29T11:32:02.610493Z    info    hyper_util    listener established    address=:15021 component="readiness"                                                                                                │
│ 2024-08-29T11:32:02.610641Z    info    app    shared proxy mode - in-pod mode enabled                                                                                                                            │
│ 2024-08-29T11:32:02.610716Z    info    hyper_util    listener established    address=127.0.0.1:15000 component="admin"                                                                                           │
│ 2024-08-29T11:32:02.610737Z    info    hyper_util    listener established    address=:15020 component="stats"                                                                                                    │
│ 2024-08-29T11:32:02.610748Z    info    readiness    Task 'dns proxy' complete (1.682099ms), still awaiting 3 tasks                                                                                               │
│ 2024-08-29T11:32:02.610751Z    info    readiness    Task 'proxy' complete (1.686441ms), still awaiting 2 tasks                                                                                                   │
│ 2024-08-29T11:32:02.646194Z    warn    xds::client:xds{id=1}    XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 20ms                                                                                                                                                                 │
│ 2024-08-29T11:32:02.701952Z    warn    xds::client:xds{id=2}    XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 40ms                                                                                                                                                                 │
│ 2024-08-29T11:32:02.758201Z    warn    xds::client:xds{id=3}    XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 80ms
