### ISSUE TITLE
Errors with istio ext-authz cluster name in envoy cluster stats - metrics

### ISSUE THREAD

**Issue by edgargarciao** [istio/istio#49061]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio generate metrics in prometheus matching the cluster name to replace it, but if the cluster name contains points then Istio not replace the name and mantains the cluster name in the metric name.

For example:

sidecar-ag-grpc.ext-authz.deltacloud.io.upstream_rq_time

31147:envoy_cluster_ext_authz_deltacloud_io_upstream_rq_time_bucket{cluster_name="outbound|4500||sidecar-ag-grpc",le="0.5"} 3

### Version

```Text
Istio Version: 1.19.4


~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.8-eks-8cb36c9", GitCommit:"fca3a8722c88c4dba573a903712a6feaf3c40a51", GitTreeState:"clean", BuildDate:"2023-11-22T21:52:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zirain** [comment]
I think this's an envoy bug, rather than istio. istio did nothing to `upstream_rq_time` metric.
Envoy's stats extraction build on top regex things, there's a lot limitation or bug.
