### ISSUE TITLE
Orchestrator - AKV bug where the VaultName property is used for constructing the VaultURL instead of deriving it from the storePath.

### ISSUE THREAD

**Issue by sreiutz** [istio/istio#49063]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Robert Colbert @ Assurant explained in a call that Orchestrator Azure Keyvault extension for Keyfactor requires optional fields in cert store and it's not getting those details from the store path as needed (during Discovery).  Workaround is manually adding the vault name.

See below email from Robert Colbert @ Assurant for details on version tested and his feedback on how to fix:

I just looked at the code for 3.1.2 and it does NOT address the AKV bug where the VaultName property is used for constructing the VaultURL instead of deriving it from the storePath.

There are 2 options for resolving this:
1) Change how vaultURL is derived to construct it from the storePath provided during discovery
2) Change discovery to populate the VaultName property pushed to Control as part of the discovery process.

In my opinion, deriving the URL from the immutable storePath attribute is a cleaner implementation but option 2 is less likely to impact customers.

-Robert
__________________________________
Robert Colbert
Principal Engineer, Cloud Enablement

  

### Version

```Text
Orchestrator Azure Keyvault extension version 3.1.2
```

### Additional Information

n\a

**Comment by keithmattix** [comment]
Can you provide more information for how this is an Istio bug?

**Comment by sreiutz** [comment]
Apologies, did not realize this was istio specific.  Mistake on my part, I will resubmit.

Stephen Reiutz
Sr Solutions Architect
M: (602) 772-1178
***@***.******@***.***>

***@***.***
Identity-first security for every device,
workload, and thing.
Follow Keyfactor on LinkedIn<https://linkedin.com/company/wearekeyfactor/>
-
CONFIDENTIALITY NOTICE
This communication may contain privileged or other confidential information. If you received this email in error,
then please advise the sender by reply email and immediately delete the message and any attachments
without copying or disclosing the contents. Thank you.

**Comment by ilrudie** [comment]
@sreiutz, would it be ok to close out this issue?

**Comment by sreiutz** [comment]
Ian, yes please and thank you!


Thank you,

Stephen Reiutz
Sr Solutions Architect
M: (602) 772-1178
***@***.******@***.***>

***@***.***
Identity-first security for every device,
workload, and thing.
Follow Keyfactor on LinkedIn<https://linkedin.com/company/wearekeyfactor/>
-
CONFIDENTIALITY NOTICE
This communication may contain privileged or other confidential information. If you received this email in error,
then please advise the sender by reply email and immediately delete the message and any attachments
without copying or disclosing the contents. Thank you.

**Comment by ilrudie** [comment]
Closing. OP will re-open against another repo.
