### ISSUE TITLE
Locality Load Balancing  does not meet the expectations

### ISSUE THREAD

**Issue by fizos** [istio/istio#49074]
I have set up a large service mesh consisting of two clusters using the multi-primary multi-network mode, with traffic between clusters going through east-west gateways, and have added region and zone labels to the nodes respectively.

![image](https://github.com/istio/istio/assets/96819554/57649f2f-ed55-4ad1-8dc9-cc4741dcd980)

![image](https://github.com/istio/istio/assets/96819554/489a93dc-6271-446c-aa51-35ce14130d31)

I have deployed the helloworld application in each cluster, with the specific configuration as follows.

apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
        - name: helloworld
          image: docker.io/istio/examples-helloworld-v1
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
        - name: helloworld
          image: docker.io/istio/examples-helloworld-v2
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 5000`
---
# helloworld-gateway.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
    - "*"
  gateways:
    - helloworld-gateway
  http:
    - match:
        - uri:
            exact: /hello
      route:
        - destination:
            host: helloworld
            port:
              number: 5000

**At this point, accessing the service through nodeport on one of the cluster nodes, the helloworld pods in both clusters will respond.**

Next, deploy the following DestinationRule in both clusters as below：
# locality-lb-weight.yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
  namespace: sample
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        distribute:
          - from: region1/*
            to:
              "region1/*": 80
              "region2/*": 20
          - from: region2/*
            to:
              "region2/*": 80
              "region1/*": 20
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m

**When accessing the service from a node in region1, the traffic will only flow through the pods in region1. If you forcibly direct 100% of the traffic in region1 to region2, the response will be a 503, "no healthy upstream" error.**

**How can I configure the traffic management to work effectively based on regional weights? Is it necessary to add corresponding region and zone labels to the workload?**

**Comment by hzxuzhonghu** [comment]
@fizos Please format your yamls well.

My first suspect is that it is thru eastwest gateway, and i think gateway have no locality. I even doubt we donot have a way to specify now
