### ISSUE TITLE
distribution reporter should not report events for types that are unwatched

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#49071]
It is likely for a gateway unwatching rds if no gateway/vs configurred. Currently we report events for {cds, eds, lds, rds}, even a proxy may not watch one  resources.  The reason is istioctl x wait checking whether a config has been synced by quering the debug interface  `/debug/config_distribution`

```
// SyncedVersions shows what resourceVersion of a given resource has been acked by Envoy.
type SyncedVersions struct {
	ProxyID         string `json:"proxy,omitempty"`
	ClusterVersion  string `json:"cluster_acked,omitempty"`
	ListenerVersion string `json:"listener_acked,omitempty"`
	RouteVersion    string `json:"route_acked,omitempty"`
	EndpointVersion string `json:"endpoint_acked,omitempty"`
}

```

In the above casem If we can tell the waiter that no route is watched by a proxy, then the waiter wonot wait for the unsubscribed resources anymore. And then we donot need to report event for that type, which seems very  hacky and urgly.

I think the way is very simple to tell the waiter what it should wait.  If we want to keep as much as current, we can change SyncedVersions's field to string pointer.

```
type SyncedVersions struct {
	ProxyID         *string `json:"proxy,omitempty"`
	ClusterVersion  *string `json:"cluster_acked,omitempty"`
	ListenerVersion *string `json:"listener_acked,omitempty"`
	RouteVersion    *string `json:"route_acked,omitempty"`
	EndpointVersion *string `json:"endpoint_acked,omitempty"`
}
```

**Comment by aryasoni98** [comment]
@hzxuzhonghu Can I work on it?

**Comment by hzxuzhonghu** [comment]
Thank you feel free to take it.  @hanxiaop @howardjohn WDYT

**Comment by hanxiaop** [comment]
> It is likely for a gateway unwatching rds if no gateway/vs configurred. Currently we report events for {cds, eds, lds, rds}, even a proxy may not watch one resources. 

@hzxuzhonghu I haven’t used the wait command for many times, but IIRC the situation you mentioned could cause the wait to hang forever until it times out. The idea makes sense to me, but it seems like it will break older versions of istioctl. Should we support both implementations in the new releases? Or since it's an experimental command, maybe we could simply mention this change in the release notes.

**Comment by hzxuzhonghu** [comment]
I do not mind we just make istioctl work with the specific controlplane version, especially for the experimental cmd.  There is an issue asking for istioctl support multi versions, but it cannot do now.

**Comment by hanxiaop** [comment]
> I do not mind we just make istioctl work with the specific controlplane version, especially for the experimental cmd. There is an issue asking for istioctl support multi versions, but it cannot do now.

SGTM
