### ISSUE TITLE
E2E test fails if Kubernetes configuration has file references

### ISSUE THREAD

**Issue by esnible** [istio/istio#4908]
Using HEAD from April 12.

Running `make e2e_pilot ISTIO_PROXY_IMAGE=proxyv2 HUB=<...> TAG=<...> E2E_ARGS="-v1alpha3=true -v1alpha1=false -auth_enable=false` with KUBECONFIG and pilot/pkg/kube/config pointed to a configuration that contains file references causes the test to fail:

```
error    Unable to create namespace pilot-test-1e878ed124f144ebacbcbad207: command failed:
"error: unable to read certificate-authority /tmp/istio.e2e.529479618/ca-dal13-istio-test-paid.pem
for istio-test-paid due to open /tmp/istio.e2e.529479618/ca-dal13-istio-test-paid.pem:
no such file or directory\n" exit status 1
```

This is a problem for IBM Cloud, which has a file reference for the certificate authority, e.g.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca-hou02-istio07.pem
    server: https://169.47.72.34:23478
  name: istio07
```

What's happened is that the config file was copied to a tmpdir but the .pem referred to was not copied.

_istio/tests/util/kube_utils.go_ does
```func GetKubeConfig(filename string) error {
    _, err := ShellMuteOutput("kubectl config view --raw=true --minify=true > %s", filename)```
and `kubectl config view` does NOT do anything clever with the `certificate-authority: ca-hou02-istio07.pem` entry that is returned.

A work-around for these errors is to edit your $KUBECONFIG and/or _pilot/pkg/kube/config_ so that the files are referred to by absolute path, e.g.

```
- cluster:
    certificate-authority: /home/vagrant/golang/src/istio.io/istio/pilot/pkg/kube/ca-hou02-istio07.pem
```

**Comment by john-a-joyce** [comment]
This has been fixed with https://github.com/istio/istio/pull/4934 
and has been tested in the IBM cloud environment with a partial 
path for the Cert.
