### ISSUE TITLE
Revamp TargetSelector for authN and authZ policy

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4909]
1. Both policies should share the same structure if possible.
1. It needs to be able to address use cases like gateway, or when workloads are shared by multiple services, etc.
1. How to make it work for other platforms that doesn't support namespace.
1. Subset concept.

**Comment by diemtvu** [comment]
@liminw , @yangminzhu Do you think this is still worth doing?

**Comment by yangminzhu** [comment]
I think it's worth to do so but the priority is very low for now. It will benefit us to have a more consistent auth policy but there're a lot of other things to consider for the new design.

**Comment by diemtvu** [comment]
We will do this when the time comes to design new APIs.
