### ISSUE TITLE
Check headers for the new gateway impl

### ISSUE THREAD

**Issue by linsun** [istio/istio#4911]
Headers I captured from my service A, when accessing the service via for istio-ingress -> service A

these are sample headers from a service connected to istio-ingress today: map[Referer:[http://169.60.83.11/]
X-Forwarded-For:[9.27.121.176, 10.188.52.41]
X-B3-Traceid:[ba82cc26ee25e908]
Content-Length:[0]
Revision:[configuration-example-00001]
User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0]
Accept:[application/json, text/javascript, /; q=0.01]
Accept-Language:[en-US,en;q=0.5]
X-Rbt-Optimized-By:[rtp-wx-sh5 (RiOS 9.1.3) SC]
X-Envoy-External-Address:[10.188.52.41]
X-Request-Id:[f395e25c-9026-9c39-b1b8-9459929f48c7]
X-Bluecoat-Via:[a24a3ec2c6c24776]
X-Forwarded-Proto:[http]
X-B3-Sampled:[1]
X-Requested-With:[XMLHttpRequest]
Cache-Control:[max-stale=0]
X-B3-Spanid:[ba82cc26ee25e908]

Opening this WI to ensure we are checking headers for the new gateway impl so these headers are avail to users to propagate to the next service for distributed tracing.

cc @rshriram @ZackButcher @louiscryan

**Comment by ZackButcher** [comment]
This will take some updates to the Gateway API. Today we don't encode any notion of ingress/egress/in-mesh in the Gateway, so it's very hard to tell when we'd need to strip or preserve headers. We likely won't be able to get to this till after 0.8.

**Comment by linsun** [comment]
Thanks @ZackButcher!  does this mean in 0.8, the zipkin or jaeger tracing won't work, e.g. we won't be able to tie multiple spans together from a single request?   I think so if I'm interpreting correctly. cc @ijsnellf

**Comment by linsun** [comment]
hey @zackbutcher is this planned for 0.8?  wanted to make sure we have a distributed tracing story for the new gateway.  cc @esnible @GregHanson @rshriram @frankbu

**Comment by rshriram** [comment]
We could always mark gateways as external in Envoy to allow these to pass

**Comment by linsun** [comment]
@rshriram could you elaborate?

**Comment by esnible** [comment]
I deployed gcr.io/google_containers/echoserver:1.4 and pointed a Gateway+VirtualService at it.

The gateway added the following headers according to echoserver

x-b3-sampled=1
x-b3-spanid=739826e9e7b70239
x-b3-traceid=739826e9e7b70239
x-envoy-decorator-operation=echo
x-envoy-internal=true
x-forwarded-for=10.73.71.198
x-forwarded-proto=http
x-request-id=cf6d5bf0-3716-9f0d-9ced-9f203cce15f2

That covers the headers needed by Zipkin.
