### ISSUE TITLE
Gateway API status write race

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49120]
https://github.com/istio/istio/blob/caa9ee1a03753f8dd7c7c37b04630ba41fd963a2/pilot/pkg/config/kube/gateway/controller.go#L172

and

https://github.com/istio/istio/blob/caa9ee1a03753f8dd7c7c37b04630ba41fd963a2/pilot/pkg/config/kube/gateway/controller.go#L257

Have a TOCTOU issue which can cause L257 to crash as c.statusController is set to nil

**Comment by jaellio** [comment]
Are you referring to the condition when the server starts up and begins shuts down (setting the statusController to nil) while the controller is still handling status updates?

**Comment by howardjohn** [comment]
Its not just shutdown of the process, we call SetStatusWrite(false) if we lose leader election. If it was just shutdown it wouldn't be so bad (crash during shutdown... it was going to shutdown anyways I guess?), but leader election loss can happen at anytime. This was observed in a real world cluster.

But yes, its a rare race that this happens while status updates are triggering.

I think in the real world cluster it was exacerbate by a (already fixed) bug that made us do excessive status writes, so it was basically always writing status
