### ISSUE TITLE
AuthorizationPolicy only working from Istiod namespace?

### ISSUE THREAD

**Issue by achetronic** [istio/istio#49148]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello there,

As title suggest I am trying to deploy an AuthorizationPolicy, and after a lot of tests, they are only applied by Istio when I deploy them inside istio namespace (same namespace where I have the main gateway). 

If I deploy exactly the same policy inside another namespace, this is directly ignored.

ATM I don't really know it istiod is ignoring it when it's into a different namespace. Just in case it's useful, I'm not using only native Istio CRs, but Gateway API V1 to create the gateways and everything works fine with that

### Version

```Text
istioctl version:
client version: 1.20.1
control plane version: 1.19.2
data plane version: 1.19.2 (1 proxies)

kubectl version:
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-gke.1016000
```

### Additional Information

By the moment, The policy I am applying is too greedy to deny all the traffic just for debugging purposes:

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: another-namespace
spec: {}
```

**Comment by zirain** [comment]
> Optional. The selector decides where to apply the authorization policy. The selector will match with workloads in the same namespace as the authorization policy. If the authorization policy is in the root namespace, the selector will additionally match with workloads in all namespaces.

**Comment by achetronic** [comment]
@zirain Hello and thanks for your response :) 

Yesterday i figured out just that but the problem is that it seems that Istiod is only reading the AuthorizationPolicy resources from it's namespace. But if I allocate this resource in another one, for example 'pepito', this authorization policy is not working not even with or without selectors. It seems IstioD is directly ignoring it in all cases

Is this the expected behavior? the rest of the things seems to be working fine. The same thing seems to be happening when I apply EnvoyFilters. They are only being recognized if I deploy them in the namespace where Istio is deployed

Can be this related to the fact we are using Istio with Gateway API CRDs instead of istio ones? Do they need to be in the same namespace that istiod? or in the same namespace where the gateway is running?

**Comment by hzxuzhonghu** [comment]
It is required authzPolicy should be in same namespace as the proxy, or in istio system namespace

**Comment by achetronic** [comment]
@hzxuzhonghu Hello sir, is there any place in the docs that specify this? I did not find it

So I understand this is being watched by the istiod controller but it's only reacting on that namespace as the gateway is just there

Is this behavior different if you use sidecar envoy proxies, and you deploy the Auth Policy resource there?

---

Just for future people digging deep on this topic, we are using Gateway API over Istio, so we have only one gateway (our proxy) deployed in the same namespace than the istiod controller

**Comment by hzxuzhonghu** [comment]
I am not sure whether it is documented

**Comment by achetronic** [comment]
@hzxuzhonghu [According to this documentation](https://istio.io/latest/docs/reference/config/security/authorization-policy/), this should not happens:

> Authorization Policy scope (target) is determined by “metadata/namespace” and an optional selector.
> - “metadata/namespace” tells which namespace the policy applies. If set to root namespace, the policy applies to all namespaces in a mesh.
> - workload selector can be used to further restrict where a policy applies.
> For example, the following authorization policy applies to all workloads in namespace foo. It allows nothing and effectively denies all requests to workloads in namespace foo.

> ```
>v1beta1v1
>apiVersion: security.istio.io/v1
>kind: AuthorizationPolicy
>metadata:
>  name: allow-nothing
>  namespace: foo
>spec: {}

**Comment by hzxuzhonghu** [comment]
This means the authz policy should be in same namespace as the `proxy`, is your gateway in `istio-system`?

**Comment by achetronic** [comment]
By parts:
* Out gateway is deployed on `istio` namespace, which is the root namespace too as we have deployed istiod there too
* from this 
   > “metadata/namespace” tells which namespace the policy applies. If set to root namespace, the policy applies to all 
   > namespaces in a mesh.

   I interpreted by target the `HTTPRoute`. From your message, this target for the policy is the `proxy` and nor the route, which is the gateway

If this is right, I think this is not properly documented as this can drive to misconceptions :)

**Comment by hzxuzhonghu** [comment]
Yes, because authorizationPolicy is applied to inbound, so we require it to be in same namespace as the proxy

**Comment by achetronic** [comment]
@hzxuzhonghu thank you for the response. Is there any change for me to explain this better in the docs? I mean, is the project accepting PRs to improve docs? :)
