### ISSUE TITLE
Feature request: Support more data types in RequestAuthentication claim

### ISSUE THREAD

**Issue by xr** [istio/istio#49169]
**Describe the feature request**

>"Only claim of type string/int/bool is supported"

https://istio.io/latest/docs/reference/config/security/jwt/#ClaimToHeader, it would be nice to support other data types like: arrays in the payload.

**Describe alternatives you've considered**

- only proxy the payload
- or use JwtAuthentication instead of istio RequestAuthentication

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by hanxiaop** [comment]
I think this is related to envoy implementations https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter.html#copy-validated-jwt-claims-to-http-request-headers-example

**Comment by xr** [comment]
@hanxiaop but i think envoy could extract the array type of fields

**Comment by hanxiaop** [comment]
> @hanxiaop but i think envoy could extract the array type of fields

@xr If so, I think the Istio proxy may also work with the array type. Have you tried it?

**Comment by hanxiaop** [comment]
> yes, tried, istio doesn't work for the array field.

@xr Which version of Istio are you using? I've tested the behavior, and it returns a base64-encoded array string.

**Comment by xr** [comment]
hello, it's 1.20.1

**Comment by wulianglongrd** [comment]
The http header is usually a `map[string]string`, and I have almost never seen `map[string][]T`. Isn't it?
