### ISSUE TITLE
Documentation error related to External Control Plane configuration

### ISSUE THREAD

**Issue by kworkbee** [istio/istio#49167]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster

In item 7 of the link above, it is explaning the definition and deployment of `Gateway` object, and the following message comes out as a result of executing the install command in `istioctl`:

```
Error: generate config: error unmarshaling JSON: while decoding JSON: unknown field "selector" in istio.operator.v1alpha1.IstioOperatorSpec
```

### Version

```Text
$ istioctl version                                                                                                                                                                                              
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (1 proxies)

$ kubectl version                                                                                                                                                                                                     
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1
```

**Comment by zirain** [comment]
file created in item 7 and applied in item 9, so there's no error here.

**Comment by kworkbee** [comment]
@zirain Is the CLI itself the cause of the error that occurred?

**Comment by zirain** [comment]
resources generated in item 7 are some istio CRs, it's not for install with istioctl (with install command).
