### ISSUE TITLE
Pilot fetches and distributes JWT public key (to sidecar)

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#4917]
In 0.7, envoy sidecar needs to fetch public key from `JwksURI` (specified as part of JWT filter config). This requires:
* Pilot needs to create outbound cluster (CDS) for each JwksURI, which have some conflicts with v2+v1alpha3 (particularly, concept of `ExternalService`)
* In term of performance, each sidecar will need to fetch the keys independently.

An alternative solution is to have pilot fetch the keys and distribute the them to sidecars; sidecars can use the keys directly, without any extra communication to external services.

To make this works, following assumptions/requirements need to be met:

1. Pilot is allowed to talk to external web services. (does pilot sidecar needs to be configured somehow?)
1. Implementation for cache and key rotation in pilot (i.e if key is updated, it should trigger pilot to push new configs to services).
1. Security concerns: is this acceptable if control plane doesn't use mTLS.

Related issues:
* [Proxy support public key in filter config](https://github.com/istio/proxy/issues/1373)
* [Support OpenID Discovery](https://github.com/istio/istio/issues/4719)
* https://github.com/istio/istio/issues/4633

**Comment by quanjielin** [comment]
almost done, workitems left:
1. proactively push change to sidecar after detecting pubkey change
2. https://github.com/istio/istio/issues/1419

**Comment by quanjielin** [comment]
For workitem 1 above, need to follow with networking team to see if pilot v2 periodically push behavior is good enough for us.

**Comment by diemtvu** [comment]
Create https://github.com/istio/istio/issues/5898 for JWT public key changes handler.
