### ISSUE TITLE
sidecar detect and repair fails with Cilium

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49186]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I've modified the kind-provisioner and ambient-sc.yaml files to allow for provisioning a different CNI during cluster builds adding cilium with the following. It runs conditionally when ambient-sc is the config being used.

```shell
    helm repo add cilium https://helm.cilium.io/
    helm repo update
    helm install cilium cilium/cilium --version 1.15.0 --namespace kube-system --set externalIPs.enabled=true,bpf.masquerade=false,image.pullPolicy=IfNotPresent,ipam.mode=kubernetes,l7Proxy=false,cni.exclusive=false
    kubectl wait --for=condition=ready --timeout=60s -n kube-system pod -l=k8s-app=cilium
```

Running the following command in to provision and test:
`INTEGRATION_TEST_FLAGS="--istio.test.ambient" GOMAXPROCS="2" prow/integ-suite-kind.sh --kind-config prow/config/ambient-sc.yaml test.integration.ambient.kube --skip-cleanup`

As the ambient integ test suite prepares to run and installs the echo apps, sidecar-uncaptured fails to start. The validator init errors out and the istio-cni is constantly attempting to repair. Not 100% convinced it's not a problem with my cilium install but opening to track and will update as I figure things out.

The entire suite does pass with Calico subbed in for Cilium.

### Version

```Text
istio/istio tip of master running the integ test suite

$ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}
```

**Comment by ilrudie** [comment]
https://github.com/ilrudie/istio-istio/tree/integ-ambient-cni

Really rough WIP but may be relevant.

**Comment by bleggett** [comment]
Broader topic: in general, if we are making the claim that ambient is compatible with multiple CNIs, I think we need actual integration tests that run the ambient suite (or some subset of it) with different CNIs, to actually prove that in an ongoing way?

**Comment by ilrudie** [comment]
potentially related PR https://github.com/istio/istio/pull/49207

**Comment by bleggett** [comment]
I actually think this is probably not directly related to ambient, and looks to be a problem with the existing sidecar detect-and-repair in Cilium.

https://github.com/istio/istio/pull/49207 fixes a state where `detect and repair` was used as the primary mechanism, and that has exposed that regular sidecar detect and repair is failing with Cilium.

**Comment by ilrudie** [comment]
It looks like for some reason `getLinkWithDestinationOf` is failing to get any routes.

```go
	routes, err := netlink.RouteListFiltered(
		netlink.FAMILY_V4,
		&netlink.Route{Dst: &net.IPNet{IP: net.ParseIP(ip), Mask: net.CIDRMask(32, 32)}},
		netlink.RT_FILTER_DST)
```

Possible this filter is not appropriate or there's a netlink bug with Cilium.

If I exec into the CNI pod I can use `nsenter -t 1 ip route get {pod's IP}/32` and I do see a route.

**Comment by yuval-k** [comment]
can we remove that function? if not try installing cilium with `endpointRoutes.enabled`

**Comment by bleggett** [comment]
> can we remove that function? i don't think inpod mode needs it anymore?

Inpod doesn't use any of these codepaths at all, this is isolated to sidecar repair.

**Comment by ilrudie** [comment]
https://github.com/ilrudie/istio-istio/tree/detect-and-repair-issue

As @bleggett mentioned, recent fixes mostly avoid the issue. It'll be more prominent in this branch in my fork where I have not yet merged the fixes.

Using the following command with that branch should be a quick repro where the sidecar-uncaptured pods continuously fail.
```shell
INTEGRATION_TEST_FLAGS="--istio.test.ambient" GOMAXPROCS="4" prow/integ-suite-kind.sh --kind-config prow/config/ambient-sc.yaml test.integration.ambient.kube --skip-cleanup
```

It'll install Cilium and then run our test suite which will fail. When it hangs at `=== BEGIN: Deploy echo instances ===` you can just ctrl-c and then interact/investigate as required. It also includes a little bit of additional logging in our CNI which may help.
