### ISSUE TITLE
Isito Install Command Issue For Egress Gateway

### ISSUE THREAD

**Issue by rabiayilmazz** [istio/istio#49222]
´´´´istioctl install´´´´
When this command is executed, there is no egress gateway between the established pods.

https://istio.io/latest/docs/setup/getting-started/

When the installation on this page is based on the installation and done, the error is received without being noticed and it takes a long time to find the solution.

https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/
The problem is solved when you install the Egress gateway page.

**Comment by zirain** [comment]
istioctl install use `default` profile by default, which means no egreegateway will be installed.

**Comment by howardjohn** [comment]
"The egress gateway and access logging will be enabled if you install the demo [configuration profile](https://istio.io/latest/docs/setup/additional-setup/config-profiles/)." is documented on the page
