### ISSUE TITLE
"Waiting for Istio ingress IP to become available ..." 

### ISSUE THREAD

**Issue by msongmetlife** [istio/istio#49225]
I installed Istio 1.18.2 in our AKS cluster with Kubernetes 1.27.7. The installation seems successful because all main components were installed successfully including istio core, istiod, egress gateway and ingress gateway. However, at the very end, "Waiting for Istio ingress IP to become available ..." message was hanging there forever and finally quit.

We have other clusters with the same Istio version installed and there was no issue.

**Comment by zirain** [comment]
cc @keithmattix

**Comment by keithmattix** [comment]
What's your installation mechanism? Does this continue to happen if you try again?

**Comment by msongmetlife** [comment]
@keithmattix I installed it through a pipeline and what it basically does is to call /install.sh. I tried to install it many times and the same thing happened. I checked the pods of ingress-gateway and they are up and running. I always feel that the installation of Istio doesn't an issue but the issue is the connectivity to Ingress.

**Comment by keithmattix** [comment]
What is install.sh? Are you sure you're using an AKS cluster and not CAPZ or a self-managed Kubernetes cluster on Azure?

**Comment by msongmetlife** [comment]
the is the file content of install.sh

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#!/bin/bash


ISTIO_VERSION=$(cat ISTIO_VERSION)

# curl -sL "https://github.com/istio/istio/releases/download/$ISTIO_VERSION/istioctl-$ISTIO_VERSION-osx.tar.gz"

                                                                              # istio-1.7.3-win.zip
curl -SOkL "https://gcsweb.istio.io/gcs/istio-release/releases/$ISTIO_VERSION/istioctl-$ISTIO_VERSION-osx.tar.gz"
curl -SOkL "https://gcsweb.istio.io/gcs/istio-release/releases/$ISTIO_VERSION/istio-$ISTIO_VERSION-osx.tar.gz"

# git clone https://MetLife-Global@dev.azure.com/MetLife-Global/Platforms%20and%20Engineering/_git/istio-artifacts

# cd istio-artifacts

# git checkout phil

# cd ..

# cp istio-artifacts/$ISTIO_VERSION/istioctl-$ISTIO_VERSION-osx.tar.gz .

tar xf istioctl-$ISTIO_VERSION-osx.tar.gz
tar xf istio-$ISTIO_VERSION-osx.tar.gz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Yes, we do use an AKS cluster. Kubernetes version is 1.27.7

**Comment by ilrudie** [comment]
There is another AKS user reporting the same in discussions. Was a resolution found here?

**Comment by ilrudie** [comment]
Thanks. LMK if you'd like a second set of eyes.

**Comment by ilrudie** [comment]
Thanks for clarifying @dkonyayev

**Comment by keithmattix** [comment]
Is this error coming from istioctl?
