### ISSUE TITLE
envoy.filters.network.kafka_mesh was disabled in Istio proxy 1.13

### ISSUE THREAD

**Issue by Zagitori** [istio/istio#49241]
I worked with the extension **envoy.filters.network.kafka_mesh** in Istio proxy version 1.12, in version 1.13 this extension became unavailable, after which it was not included in the Istio Proxy image.
What is the reason for disabling the extension from Istio Proxy images?

**Comment by keithmattix** [comment]
1. Istio 1.12 and 1.13 are severely out of date; please upgrade
2. Envoy has stopped compiling in filters like Kafka by default, only including them in contrib images. Therefore, newer Istio versions do not include them either

**Comment by Zagitori** [comment]
> 1. Istio 1.12 and 1.13 are severely out of date; please upgrade
> 2. Envoy has stopped compiling in filters like Kafka by default, only including them in contrib images. Therefore, newer Istio versions do not include them either

I am currently using the image of version 1.17.8.
The image includes some contrib filters, for example **envoy.filters.network.mysql_proxy** and **envoy.filters.network.postgres_proxy**, but the Kafka filter is missing.
Why is this particular filter not included in the image, does it have any critical vulnerabilities?

[https://github.com/istio/proxy/blob/1.17.8/bazel/extension_config/extensions_build_config.bzl#L412](url)

**Comment by keithmattix** [comment]
Historical context; mysql and postgres were around for a while and we didn't want to break people. The MySQL filter specifically is behind a feture flag though and I don't even know if the postgres proxy filter is even available in Istio anymore without Envoy filter. See https://github.com/istio/istio/issues/47113#issuecomment-1735620300
