### ISSUE TITLE
test ambient with kubernetes netpol

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49301]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

https://github.com/istio/istio/issues/49277 was found running a new proposed integ test in an environment with Cilium CNI installed instead of the KinD default. Ideally we should add integ tests against network policy configurations we test.

https://github.com/istio/istio/pull/49255 seeks to lay groundwork for an integ platfrom based on KinD+Calico. Cilium would also be plausible for CI.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by danehans** [comment]
I'd like to work on this issue. Can someone assign me?

**Comment by bleggett** [comment]
> The results of the discussions ended up that accepting a firm dependency on a cni that enforces net pol for basic testing was undesirable. 

okay, but we still need to accept a firm dependency on Cilium for basic CNI conformance testing generally with Cilium.

If we wanna do that but not test netpol, that's fine, it doesn't really change the need.

**Comment by bleggett** [comment]
I'll just create a new issue with a different title.

**Comment by bleggett** [comment]
@danehans I opened https://github.com/istio/istio/issues/51467 and put you on that one - it's a bit more targeted.

Closing this one.
