### ISSUE TITLE
remove mention of discuss from feature request template

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49302]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

https://discuss.istio.io is being phased out. We're requesting folks to interact in github or slack. We should probably update our template.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[X] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ericvn** [comment]
Closed by https://github.com/istio/istio/pull/49323
