### ISSUE TITLE
No validation for kind's value for Istio Operator Install

### ISSUE THREAD

**Issue by lir2002** [istio/istio#49355]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I am using a IstioOperator manfiest to install istio, I find the value of _**kind**_ can be whatever word or string. I think the _**kind**_ field's value should only be **IstioOperator** as the guide describes. Therefore I guess there is no validation for _**kind**_ field's value.

![屏幕截图 2024-02-14 120440](https://github.com/istio/istio/assets/11921037/ba21ce4c-29cf-4719-9dc8-26fb7d8cc769)

### Version

```Text
$ istioctl version
client version: 1.20.2
control plane version: 1.20.2
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
data plane version: 1.20.2 (3 proxies)
$ helm version --short
v3.11.3+g3232493
```

**Comment by leosarra** [comment]
Although we are not validating the Kind value, we are doing a cast to IstioOperator when reading the value.
If the input yaml does not adhere to the IstioOperator spec it will fail the casting.
@hanxiaop Do you think it is worth to validate the kind as well? If so I can take care of performing the changes.

**Comment by lir2002** [comment]
For me, it's nice to have. It looks strange, although I haven't found any damage.

**Comment by hanxiaop** [comment]
See https://github.com/istio/istio/issues/44814 for our discussions about the IstioOperator resource. In the future, we may remove the need for the resource's GVK to make the configuration clearer to users.

**Comment by leosarra** [comment]
Thank you @hanxiaop for the info
If that is the case then it does not make sense now to enforce the validation of the GVK as the long term plan is to remove the need of them

**Comment by saiskee** [comment]
For the record, I believe this does not propose any security challenges (e.g. RBAC bypass) because this won't work in cluster when trying to install [istio with the operator](https://istio.io/latest/docs/setup/install/operator/#install-istio-with-the-operator). Seems to only be a bug with `istioctl install`

**Comment by lir2002** [comment]
Btw, _**apiVersion**_ can be anything, too.
However, `istioctl verify-install` will fail, because no resource **IstioOperator** is created.
![屏幕截图 2024-02-18 015900](https://github.com/istio/istio/assets/11921037/b67eaee6-dc74-4a3a-a096-cf70c01a8923)
![屏幕截图 2024-02-18 020238](https://github.com/istio/istio/assets/11921037/58ee695d-3a1d-4e75-81fb-9d759300fdad)

**Comment by hanxiaop** [comment]
> Btw, _**apiVersion**_ can be anything, too. However, `istioctl verify-install` will fail, because no resource **IstioOperator** is created. ![屏幕截图 2024-02-18 015900](https://private-user-images.githubusercontent.com/11921037/305662422-b67eaee6-dc74-4a3a-a096-cf70c01a8923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTgxNDEsIm5iZiI6MTcwODIxNzg0MSwicGF0aCI6Ii8xMTkyMTAzNy8zMDU2NjI0MjItYjY3ZWFlZTYtZGM3NC00YTNhLWEwOTYtY2Y3MGMwMWE4OTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAwNTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjUxOWQwYjkyOWIwZDMwNzAwMjRkNTAyNzhlODQ2MmE1NGNlZTk2NDZhNGQzZDVlMjMwYzhhNTE4NjA4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fxwNwVKc4RXDrH8jjdDh9DfrbKUcfoWAKrHbVF5c34) ![屏幕截图 2024-02-18 020238](https://private-user-images.githubusercontent.com/11921037/305662456-58ee695d-3a1d-4e75-81fb-9d759300fdad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTgxNDEsIm5iZiI6MTcwODIxNzg0MSwicGF0aCI6Ii8xMTkyMTAzNy8zMDU2NjI0NTYtNThlZTY5NWQtM2ExZC00ZTc1LTgxZmItOWQ3NTkzMDBmZGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAwNTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjNmOGI0NzBmY2Q3MmQ4ZjQ5NThmNGUzNTI1NjBiOWE1Mzg0ZTE1Mjk4ZWQ1YmRiMGFlNzQwOTAzYjBlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kpKefaQ4Y_ineyl3Jt0weX0DxRriLvUqWY5mpIxv7iw)

@lir2002 Thanks for the info. In release 1.21, `istioctl install` will no longer create an IstioOperator resource, and `verify-install` will not require that resource either. You may try pre-release istioctl builds of 1.21.0 at https://github.com/istio/istio/releases, or wait for the 1.21.0 release (which will be very soon) to see if the problem can be resolved.
