### ISSUE TITLE
Can Istio-IngressGateway be used to route internal service-to-service requests over mTLS ?

### ISSUE THREAD

**Issue by satish2** [istio/istio#49351]
Hi,

Within my cluster I have STRICT mTLS enabled for all traffic between services. In order to route requests, I am inclined towards using Istio-IngressGateway as I already have a virtualService which can handle API routing at IngressGateway. 

When I use https://istio-ingressgateway.<mynamespace>.svc.cluster.local/<API>, I observe that Istio-proxy sidecar within recipient pod do not have visibility towards caller pod's certificate. Since, I need details from caller pod's certificate, I am wondering:

1. If there is any way to pass through caller certificate through Istio-IngressGateway ? 
2. Is it recommended to use Istio-IngressGateway to route even internal traffic ? Stackoverflow posts seem to suggest against it. 
(https://stackoverflow.com/questions/59604397/how-do-i-create-an-internal-gateway-using-istio) 
3. I understand that "mesh" gateway in virtualService can be used as alternative to ensure request is routed directly to target pod without going through IngressGateway. But, I may end up creating two virtualServices, one for all external requests handled by Istio-IngressGW and one for internal service-to-service calls. 

Note: 
a. After various experiments with EnvoyFilters on Istio-IngressGW, I couldn't get the caller certificate information (Subj.Alt.Name etc.,) to pass through to target pod. I am currently pursuing the idea of using two different virtualServices. 
b. For access control on recipient service I need caller's SPIFFE ID (source principals) for Istio authorization policy to work. And, Istio-IngressGateway overwrites this, when request is routed through it. 

Thanks,
Satish

**Comment by howardjohn** [comment]
> If there is any way to pass through caller certificate through Istio-IngressGateway ?

It is/can be passed in XFCC, but you cannot assert policies against this

> Is it recommended to use Istio-IngressGateway to route even internal traffic 

Not generally

> I understand that "mesh" gateway in virtualService can be used as alternative to ensure request is routed directly to target pod without going through IngressGateway. But, I may end up creating two virtualServices, one for all external requests handled by Istio-IngressGW and one for internal service-to-service calls.

Depending on your exact setup you can bind the same VS to 'mesh' and ingrss gw and reuse the route. Or just use tooling like helm to easily duplicate it if you prefer them split.

**Comment by satish2** [comment]
> It is/can be passed in XFCC, but you cannot assert policies against this

Thanks for quick response. By the statement "but you cannot assert policies against this", can you please confirm if you meant I cannot enforce AuthorizationPolicy based on SPIFFE ID (sourcePrincipals) under SubjectAlternativeName ?

**Comment by howardjohn** [comment]
Correct, sourcePrincipals is the source's principal. The source is the ingressgw. There is no "source's Source Principal" assertion

**Comment by satish2** [comment]
Thank you.

**Comment by satish2** [comment]
@howardjohn 
Can you please let me know if there is a guideline on how to add FQDN/IP entry for pseudo gateway "mesh" ? Because, assigning any hostname won't work as pods should be able to resolve the FQDN and it needs an entry in pod's /etc/hosts (managed by K8s) for FQDN to IP for non-existent service within mesh. 

Consider a pod "podA" with istio-proxy and myAppA. I configured pseudo gateway "mesh" with FQDN "myProduct.internal-api.route.cluster.local" under hosts. (Host is mandatory for mesh pseudo gateway. Ref: https://github.com/istio/istio/pull/33904)

When myAppA has to make a request that needs to be routed by VirtualService, I can use http://myProduct.internal-api.route.cluster.local/<API-endpoint>. 

Based on my experiments, it doesn't really matter which FQDN is used as long as it is resolvable by myAppA. Instead of "myProduct.internal-api.route.cluster.local", I can even use "myAppB.<namespace>.svc.cluster.local" in VirtualService and in myApp's code. 

Won't this cause confusion where developers may assume API routing is getting handled by myAppB (based on FQDN) ? whereas Envoy/Istio-proxy within podA is the one intercepting and routing the request ?
