### ISSUE TITLE
[Feature/improvement req] Make warmupDurationSecs start increasing after readiness probe succeeds

### ISSUE THREAD

**Issue by Bennett-Lynch** [istio/istio#49384]
**Describe the feature request**

The warmupDurationSecs configuration allows a service to gradually/linearly ramp up the traffic it receives. However, it measures the start time as when the pod was created. This can mean that for a service that has a prolonged startup procedure, by the time the service passes a readiness probe and begins receiving traffic, enough time may have elapsed that the % of traffic it will receive at first is well over the intended 1%.

Example
1. Service configured with warmupDurationSecs of 300s (5 min)
2. Service takes 60s to startup and pass readiness
3. Service begins receiving 20% traffic as soon as it starts taking traffic, rather than 1%

This creates a conflict where services now need to aggressively ensure there is minimal time between startup and passing readiness. Too much delay and they will receive larger-than-desired traffic. Too little delay and they may start receiving traffic while the app is still undergoing initialization.

Ideally it would be more intuitive for most use cases if the timer started after readiness succeeds. If this change is not possible due to backwards-compatibility, then either an option could be created to control the behavior, or a separate delay could be configured.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by ramaraochavali** [comment]
Are you sure the warmupDurationSeconds includes readiness time? AFAIK, till the pod is ready, Envoy does not consider it for load balancing. In fact we do not send unready endpoints to Envoy. Did you enable "PILOT_SEND_UNHEALTHY_ENDPOINTS" by any chance?

**Comment by Bennett-Lynch** [comment]
Hi @ramaraochavali. I am fairly certain from looking at the metrics.

Example of requests received by pod with no warmup:

![image](https://github.com/istio/istio/assets/11811448/7057187f-4a53-4f97-962d-82973da8ef1c)

Example of requests received by pod with 5m Istio warmup and a 75s readiness delay:

![image](https://github.com/istio/istio/assets/11811448/645903d1-566c-4bcf-b9b5-893c047a345b)

Example of requests received by pod with 5m Istio warmup and a no readiness delay (but ~30s startup delay):

![image](https://github.com/istio/istio/assets/11811448/d8a0249e-9d71-43b1-888e-1fc4856ad901)

Notice the immediate jump to ~25% in the 2nd graph, and notice that being mostly smoothed out in the 3rd graph.

The docs also seemed to confirm this behavior (emphasis mine):

> If set, the newly created endpoint of service remains in warmup mode **_starting from its creation time_** for the duration of this window and Istio progressively increases amount of traffic for that endpoint instead of sending proportional amount of traffic.

**Comment by Bennett-Lynch** [comment]
> Did you enable "PILOT_SEND_UNHEALTHY_ENDPOINTS" by any chance?

No it's not enabled or explicitly configured.

**Comment by Bennett-Lynch** [comment]
Hi @ramaraochavali. Just curious if you were able to confirm that the current behavior is indeed based on container start time, and whether this is intentional or not?

**Comment by ramaraochavali** [comment]
Sorry - I did not get time to take a look at it. But I am 100% certain, if you do not enable "PILOT_SEND_UNHEALTHY_ENDPOINTS" - Istio would only send only healthy (Ready( endpoints to Envoy. So warmupduration would automatically be applied after pod is ready

**Comment by Bennett-Lynch** [comment]
Interesting. My metrics seem to tell a different story but I'll try experimenting with more prolonged durations to confirm the behavior.

**Comment by howardjohn** [comment]
@Bennett-Lynch did you get a chance to investigate more?
