### ISSUE TITLE
All bookinfo reviews pods in CrashLoopBackOff state CentOS

### ISSUE THREAD

**Issue by ayj** [istio/istio#4941]
@Vikash082 commented on [Thu Apr 12 2018](https://github.com/istio/issues/issues/283)

**Is this a BUG or FEATURE REQUEST?:**  BUG

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:
Yes
**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.7.1
kubectl version: v1.10.0
CentOS Linux release 7.4.1708
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.
```
kubectl apply -f install/kubernetes/istio-auth.yaml
```

**What happened**:
All the three reviews-v1-xxxx pods are crashing. Used kubectl logs <pod> to get the below log.
```
CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:524)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:211)
        at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:244)
        at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:119)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
        at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.lang.IllegalStateException: The state  could not be created. state=/opt/ibm/wlp/output/defaultServer/logs/state
        at com.ibm.ws.kernel.boot.internal.KernelUtils.cleanDirectory(KernelUtils.java:213)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.clearServerStateDir(KernelBootstrap.java:226)
        at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:102)
        ... 4 more
```

**What you expected to happen:**
All the three review pods should run.

**How to reproduce it:**
```
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
```

**Feature Request:**
N

**Describe the feature:**

---

@ayj commented on [Thu Apr 12 2018](https://github.com/istio/issues/issues/283#issuecomment-380886585)

Can you provide more information on your test environment / cluster?

cc @linsun @frankbu - any ideas why the bookinfo review app might be crashing?

---

@Vikash082 commented on [Thu Apr 12 2018](https://github.com/istio/issues/issues/283#issuecomment-380889556)

I have 2 physical nodes, one master and one worker. These two machines have 57G free memory and enough disk space. Both the nodes are Centos systems.

Pod info:
```
$ kubectl get pods --all-namespaces
NAMESPACE      NAME                                      READY     STATUS             RESTARTS   AGE
default        details-v1-7b97668445-4s9vl               1/1       Running            0          3h
default        productpage-v1-7bbdd59459-27ndc           1/1       Running            0          3h
default        ratings-v1-76dc7f6b9-qm5s4                1/1       Running            0          3h
default        reviews-v1-64545d97b4-4n246               0/1       CrashLoopBackOff   46         3h
default        reviews-v2-8cb9489c6-c9bdq                0/1       CrashLoopBackOff   46         3h
default        reviews-v3-6bc884b456-pw4t8               0/1       CrashLoopBackOff   46         3h
istio-system   istio-ca-75fb7dc8d5-xdtcc                 1/1       Running            0          6h
istio-system   istio-ingress-8546966f58-4c9r8            1/1       Running            0          6h
istio-system   istio-mixer-566f68f5d6-zkqg5              3/3       Running            0          6h
istio-system   istio-pilot-fd8fb6957-w6m4w               2/2       Running            0          6h
istio-system   istio-sidecar-injector-844b9d4f86-mgbjl   1/1       Running            0          3h
kube-system    etcd-os-ctrl-14                           1/1       Running            1          6d
kube-system    kube-apiserver-os-ctrl-14                 1/1       Running            1          6d
kube-system    kube-controller-manager-os-ctrl-14        1/1       Running            1          6d
kube-system    kube-dns-86f4d74b45-wwvwc                 3/3       Running            24         6d
kube-system    kube-flannel-ds-qtpz7                     1/1       Running            0          6d
kube-system    kube-flannel-ds-srrgc                     1/1       Running            1          6d
kube-system    kube-proxy-5pnmz                          1/1       Running            1          6d
kube-system    kube-proxy-p98rp                          1/1       Running            0          6d
kube-system    kube-scheduler-os-ctrl-14                 1/1       Running            1          6d
```
cluster-info:
```
 kubectl cluster-info
Kubernetes master is running at https://192.168.xx.yy:6443
KubeDNS is running at https://192.168.xx.yy:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
Let me know, if more information is needed.

**Comment by linsun** [comment]
Maybe not enough resource on your minikube? I'm running bookinfo fine on my cluster, but i have mTLS disabled.

Is this only happening when mTLS is enabled?

**Comment by Vikash082** [comment]
@linsun This issue is seen with Centos based systems. I am not using minikube. I have 1 master and 1 worker node on physical servers. On both the setups there are ~57G memory available.

However, I also tried this on Ubuntu 16.04 and it worked fine on it, with and without TLS.

**Comment by pipejakob** [comment]
This doesn't seem like an Istio bug, but could boil down to how either Kubernetes or Docker were configured on CentOS. It isn't a lack-of-resources problem, because these pods are actually getting scheduled and executed (or else they wouldn't even have logs). The logs indicate that something is going wrong inside the container while bringing up the Liberty environment (the platform that the `reviews` service is built on).

Specifically, at start-up time, Liberty tries to clean up its `state` directory by first recursively deleting it, then recreating it (source code [here](https://github.com/OpenLiberty/open-liberty/blob/9c3f1bfcf18a2088c0d37e5b3c3ee88a4d8710c1/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelUtils.java#L201)). Even though this logic executes inside a container (and so hopefully it would have consistent behavior across all Docker-supported environments), I know that some of Java's behavior is still platform-specific, and file I/O is the kind of thing that still needs to be handled by the underlying Kernel, so it may just legitimately have slightly different behavior on different distributions.

Another theory is that, even though the default run-as user for this image is `root`, either the CentOS dockerd configuration or your Kubernetes configuration may have more security-conscious settings, and try to use a less privileged user by default? I don't know if either Docker or Kubernetes actually supports this kind of configuration, but if these containers aren't running as root, it would certainly explain having a permission error when trying to create this directory.

@Vikash082, if it's worth it for you to get to the bottom of this and root cause what's going wrong with CentOS, could you also provide information about how you set up both Kubernetes and Docker so that we could try to reproduce this problem? It would also be great if you were able to confirm if the reviews service is actually running as `root` in its container.

**Comment by Vikash082** [comment]
@pipejakob Here are the steps, I followed for installation:
```
- Disabled SELINUX on both the nodes.
- Installed docker, kubectl, kubeadm and kubelet as root.
- Initialize pod-networking using flannel.
- Created a non-root user on master node.
On worker node:
- Installed docker, kubectl, kubeadm and kubelet as root.
- Joined master node as root.
```
I am not able to determine the whether the reviews service is actually running as root or any other user as it is giving me below error:
```
error: unable to upgrade connection: <h3>Unauthorized</h3>
```

**Comment by wynn5a** [comment]
I am running into the same issue with kubeadm & centos7, any idea to fix it?

**Comment by superxi911** [comment]
I am running into the same issue with kubeadm & centos7, any idea to fix it?

**Comment by tuxknight** [comment]
I am running into the same issue with kubeadm & centos7, any idea to fix it?

**Comment by SpruceWang** [comment]
I am running into the same issue with kubeadm & centos7. Then I rewrite the book-review service into spring boot, hope it can help. https://github.com/SpruceWang/istio-book-info

**Comment by pangsq** [comment]
Adding an env `WLP_OUTPUT_DIR=/opt/output` fix the problem on my k8s.

- os: centos7.2
- kubernetes: v1.12.2
- docker: 18.09.0, overlay2

The deployment is now like:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-v1:1.8.0
        imagePullPolicy: IfNotPresent
        env:
        - name: WLP_OUTPUT_DIR
          value: /opt/output
        ports:
        - containerPort: 9080
```

**Comment by zgfh** [comment]
@pangsq thanks ,it work for me to add this:
```
env:
        - name: WLP_OUTPUT_DIR
          value: /tmp/output
```

**Comment by yuchen9459** [comment]
@pangsq I have tried your method but it still does not work. May I ask did you change any other configurations?

**Comment by ardenxu** [comment]
we run into similar issue with kubelet v1.11.8+istio-1.1.4+docker 1.13.1, and adding "env"option does not work for us, we solved this issue after changing 
/etc/sysconfig/docker-storage DOCKER_STORAGE_OPTIONS from overlay2 to devicemapper.

here is the final content:
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper "

and you need stop kubelet/docker before changing this config, and restart docker/kubelet after changing this config.

**Comment by sdake** [comment]
> we run into similar issue with kubelet v1.11.8+istio-1.1.4+docker 1.13.1, and adding "env"option does not work for us, we solved this issue after changing
> /etc/sysconfig/docker-storage DOCKER_STORAGE_OPTIONS from overlay2 to devicemapper.
> 
> here is the final content:
> DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper "
> 
> and you need stop kubelet/docker before changing this config, and restart docker/kubelet after changing this config.

devicemapper is not ideal for a variety of reasons.

**Comment by sdake** [comment]
Regarding this issue, containers are not 100% portable between distros.  Istio's containers are built on Ubuntu, and some of the compiled against an Ubuntu libc (which really needs to match the kernel for full compatibility).

I am not a bookinfo wizard, but on inspection I'd take a look for
```
setcap
setpcap
```

in the dockerfiles.

The reason I'd suggest looking for these setcap/setpcap calls is that CentOS (atleast v 7) is incompatible with containers built against more modern kernels.  The common workaround used is to change to DM.

There are other various subtle incompatibilities (at the syscall layer between distros.  The best solution is to build per distro (or implement a distroless version of bookinfo).
