### ISSUE TITLE
Istio Multi cluster | Wrong Endpoints | podip showing up instead of east-west-gateway ip

### ISSUE THREAD

**Issue by Muthumj123** [istio/istio#49412]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Using multi network multi primary setup. Followed the guide from [[istio.io](http://istio.io/)](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/)

Noticing inconsistency in endpoint updation across proxies even from same namespace. 
Ips for endpoints of remote cluster are registered with pod ips instead of east-west-gw ip
Happens on both the clusters. Not consistent, If istiod or pod is restarted the endpoints are updated correctly, then quickly goes bad after few hrs/mins.

podip of Cluster1 - 100.100.x.x
podip of Cluster2 - 10.244.x.x
East-west-gw ip   - 10.20.x.x (cluster2)

Following is an example of 3 pods of same deployment in same namespace in cluster1, showing different Ips for the endpoint listed.
myapp-0 showing correct ips (East-west-gw ip for remote cluster, podip for local cluster)
Myapp-1 and 2 show incorrect ips (in-place of East-west-gw ip for remote cluster, local podip of remote cluster is updated with is unroutable)
```
istio-1.16.5$ bin/istioctl pc endpoints myapp-0  --namespace sample16 --cluster "outbound|8000||hello-world.my-ns.svc.cluster.local"
ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
10.20.x.x:15443        HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local
100.100.x.x:8080      HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local


istio-1.16.5$ bin/istioctl pc endpoints myapp-1 --namespace sample16  --cluster "outbound|8000||hello-world.my-ns.svc.cluster.local"
ENDPOINT              STATUS      OUTLIER CHECK     CLUSTER
10.244.x.x:8080        HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local
100.100.x.x:8080      HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local

istio-1.16.5$ bin/istioctl pc endpoints myapp-2 --namespace sample16  --cluster "outbound|8000||hello-world.my-ns.svc.cluster.local"
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.244.x.x:8080        HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local
100.100.x.x:8080      HEALTHY     OK                outbound|8000||hello-world.my-ns.svc.cluster.local
```
So far, I tried to update meshnetworks explictly in the configmap for istiod(s), but it did not help much.
(Edited)
topology.istio.io/network label is updated on all the pods in both the clusters.

### Version

```Text
bin/istioctl version --context cluster1

client version: 1.16.5

istiod version: 1.15.7
istiod version: 1.16.5
istiod version: 1.17.6

data plane version: 1.15.7 (2 proxies), 1.16.5 (57 proxies), 1.17.6 (3 proxies)


bin/istioctl version --context cluster2
client version: 1.16.5

istiod version: 1.16.5
istiod version: 1.17.6
istiod version: 1.18.5

data plane version: 1.16.5 (3 proxies), 1.17.6 (42 proxies), 1.18.5 (5 proxies)
```

**Comment by hanxiaop** [comment]
> Noticing inconsistency in endpoint updation across proxies even from same namespace.
Ips for endpoints of remote cluster are registered with pod ips instead of east-west-gw ip
Happens on both the clusters. Not consistent, If istiod or pod is restarted the endpoints are updated correctly, 

So, does the inconsistency occur at the beginning when the multicluster is set up, or does it happen after you have restarted one of the pods? I think after connecting to another cluster and updating the network, you need to restart all related pods to ensure the east-west gateway endpoint is correctly updated.

> then quickly goes bad after few hrs/mins.

Did you notice any changes when it goes bad?

**Comment by Muthumj123** [comment]
@hanxiaop 

> So, does the inconsistency occur at the beginning when the multicluster is set up, or does it happen after you have restarted one of the pods? I think after connecting to another cluster and updating the network, you need to restart all related pods to ensure the east-west gateway endpoint is correctly updated.

- Yes. Restart was performed on both the clusters after setting up multi cluster. Also performed restart after few config changes on istiod and east-west gateway aswell. I have a script that runs periodically to take a dump on the endpoints, and I notice Inconsistency starts randomly  on few proxies and soon speard of to others.

- Yes. When I restart istiod or  proxies,  correct enpoints appear before it goes bad again randomly after few hours.


> Did you notice any changes when it goes bad?

- When the endpoint changes and if proxies pick wrong enpoint (podid of the remote cluster), they are unable to route traffic causing timeouts.
- From Isitod log (debug) I could not find what's causing it. All I can see is an entry which says `Full push, new service my-ns/svc-name.ns.svc.cluster.local"

**Comment by nicole-lihui** [comment]
The principle behind how istio Multi-Network handles endpoints IPs lies in the concept of `network` flag. (docs ref: `kubectl --context="${CTX_CLUSTER1}" label namespace istio-system topology.istio.io/network=network1`)

If all pods have been restarted but `myapp-0` is correctly, but  `myapp-1` and `myapp-2` cannot. 
I think we can compare the `bootstrap` config of the sidecars for both applications, confirm whether the network flag of the sidecar are correct.

**Comment by nicole-lihui** [comment]
you can use the following methods to confirm the network identifier:
```bash
$ kubectl exec -n <namespace> <pod-name> -c istio-proxy -- printenv | grep ISTIO_META_NETWORK

$ kubectl exec -it -n <namespace> <pod-name>  -c istio-proxy -- curl -s localhost:15000/config_dump | grep <networkName>
```

![image](https://github.com/istio/istio/assets/44200120/cc41bb5f-4988-4add-b812-e9e150047bac)

**Comment by Muthumj123** [comment]
Thanks @nicole-lihui 

We use sidecar injection on all the pods with same config. Toplogy label for these pods are correctly updated on both the cluster. These are the first few things I already verified when troubleshooting.

`kubectl exec -n sample16 pod1 -c istio-proxy -- printenv | grep ISTIO_META_NETWORK`
ISTIO_META_NETWORK=cluster1

`bin/istioctl dash envoy pod1 -n sample16 
`
config_dump
bootstrap
........
      "NETWORK": "cluster1",
      "DNS_AUTO_ALLOCATE": "true",
      "DNS_CAPTURE": "true",
.......
      "LABELS": {
       "topology.istio.io/network": "cluster1" }

**Comment by hanxiaop** [comment]
> From Isitod log (debug) I could not find what's causing it. All I can see is an entry which says `Full push, new service my-ns/svc-name.ns.svc.cluster.local"

Which version of istiod are your service connected to? I see there are three control planes in your cluster. BTW you may also check `/debug/endpointShardz` from your istiod monitoring port.

**Comment by Muthumj123** [comment]
@hanxiaop  We use canary based deployment. At any given time 3 istiod exist (with revision lables deprecated, Default, Latest) with proxies are spread across.

Thanks for sharing this ->` /debug/endpointShardz`
I can see all endpoints with proper labels in both clusters (with address field set to podips of local cluster)

I recently did a NLB to classic LB change for these east-west gateway (for 503 issue) after that, have not noticed wrong enpoints getting updated for last 24 hours. Will wait for few more days to see if the wrong enpoints are back.

**Comment by Muthumj123** [comment]
@hanxiaop  Bad endpoints are returning again. 

/debug/endpointShardz -> output is almost the same when compared with and without bad endpoints.

**Comment by Muthumj123** [comment]
@hanxiaop @nicole-lihui  Might have found the problem.

**_Gateway disconnect due to dns lookup failure._**
Was analysing ADS logs (from control-plane), noticed when istiod disconnects from kube-dns (core) inbetween dns lookup of gateways(EW), it disrupts XDS config pushes  and causes reload of network gateways -> leads to removal of remote network(new cluster) registration -> triggering new ads push, but this time istiod isn't aware of remote network, causing wrong endpoints updated to proxies connected that that istiod pod.

`istioctl x internal-debug networkz --all`

Istiod pod continues to pollute(with worng enpoints) all the proxies connected to it until the network gateways are reloaded again or istiod pod itself restarts.

**Comment by Muthumj123** [comment]
[https://github.com/istio/istio/issues/44155](url)

**Comment by Muthumj123** [comment]
#44155

**Comment by hanxiaop** [comment]
> @hanxiaop @nicole-lihui Might have found the problem.
> 
> **_Gateway disconnect due to dns lookup failure._** Was analysing ADS logs (from control-plane), noticed when istiod disconnects from kube-dns (core) inbetween dns lookup of gateways(EW), it disrupts XDS config pushes and causes reload of network gateways -> leads to removal of remote network(new cluster) registration -> triggering new ads push, but this time istiod isn't aware of remote network, causing wrong endpoints updated to proxies connected that that istiod pod.
> 
> `istioctl x internal-debug networkz --all`
> 
> Istiod pod continues to pollute(with worng enpoints) all the proxies connected to it until the network gateways are reloaded again or istiod pod itself restarts.

Makes sense

**Comment by hanxiaop** [comment]
Since it's fixed and released in new versions, I'll close the issue.
