### ISSUE TITLE
eks

### ISSUE THREAD

**Issue by samsu-lb** [istio/istio#49428]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by samsu-lb** [comment]
描述功能请求
问题描述
在AWS集群中混合使用Windows和Linux节点时，遇到了性能下降的问题。当集群仅包含Linux节点时，访问特定服务接口的响应时间是毫秒级的。然而，在集群中加入Windows节点后，请求频繁超时。服务日志表明请求已经被服务接收并处理，但客户端无法接收到服务端的处理结果，导致请求一直等待直至超时。问题的链路为：LB -> Istio Ingress -> VirtualService -> Service -> Pod。值得注意的是，尽管集群中加入了Windows节点，但是处理请求的服务并未经过Windows节点或Windows的Pod。即使尝试将Windows Pod部署在新的命名空间中，问题依旧存在。

需求
需要对Istio在混合节点（Windows和Linux）环境下的性能和稳定性进行优化，以确保服务间的通信在混合环境下不会受到影响，特别是不会因为节点类型的增加而导致请求超时或其他网络问题。

考虑过的替代方案
将Windows Pod隔离到新的命名空间，但问题依然存在。
暂未找到其他有效的解决方案，希望Istio团队能提供支持或指导。
受影响的产品领域（请在所有适用的选项上打“X”）
 Networking
 Performance and Scalability
 User Experience
受影响的功能（请在所有适用的选项上打“X”）
 多集群
 虚拟机（假设Windows节点以VM形式存在）
 多控制平面
额外上下文
该问题在混合使用Windows和Linux节点的AWS集群环境中出现，可能涉及到Istio在处理跨操作系统节点通信时的性能或配置问题。

**Comment by hanxiaop** [comment]
AFAIK Istio doesn't have native Windows support, or at least it's not a priority thing. BTW please don't use languages other than English, as only a few people can understand.

**Comment by samsu-lb** [comment]
I understand that istio does not support windows. Links with delays do not pass through windows nodes. Is it not possible to add windows nodes to a cluster with istio?

**Comment by hanxiaop** [comment]
@samsu-lb You can track https://github.com/istio/istio/issues/2641

**Comment by samsu-lb** [comment]
Thanks for the reply, I'll try switching to ingress
