### ISSUE TITLE
basic waypoint capture with istio.io/use-waypoint

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49436]
- Basic "use-waypoint" annotation implementation to reference Gateway
  - Service(s). High
  - Pod / Deployment High
  - Namespace High
  - cross-namespace. Med
- Implement "waypoint-capture" to disable High

basic waypoint capture with [istio.io/use-waypoint](https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit#heading=h.r8878rnh9a4w)

Preference would be to implement this in krt rather than the older ambientIndex if we have a high degree of confidence krt will be the future of ambient in the near term (see https://github.com/istio/istio/pull/49162 for state of ambientIndex krt controllers)

This _annotation_ is valid on namespaces, pods, workloads and other equivalent types. It controls which gateway acts as the waypoint for the resource. Valid values are:

- `none` (TBD, possibly `#none` or other variant to avoid collision if a user defines a gateway called `none` and wants to use it as a waypoint)
- `[{namespace}/]{gateway-name}` see doc for further details on requirements for referencing a gateway outside of your own namespace

We may also want to implement `istio.io/waypoint-capture` (value type boolean) to have support for waypoints being defined on a namespace but have pods/svc which do not use the waypoint. Somewhat TBD, maybe this is it's own issue.

**Comment by ilrudie** [comment]
Are there any firm objections to the idea of implementing this in krt right from the start?

cc @howardjohn @stevenctl @keithmattix

**Comment by howardjohn** [comment]
Strongly prefer we do krt. My PR is basically ready to go, was just pending benchmarks which I am running right now -- so far looks good

**Comment by ilrudie** [comment]
@howardjohn, Is this something you had interest in implementing?

**Comment by howardjohn** [comment]
Would be best to have someone else do it I think

**Comment by linsun** [comment]
Think this is done?

**Comment by ilrudie** [comment]
yeah, closed by https://github.com/istio/ztunnel/issues/817
