### ISSUE TITLE
update installation of ref impl waypoints

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49437]
[Ambient - Capture for Services and Workloads](https://www.google.com/url?q=https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit%23heading%3Dh.i456k47e7s5d&sa=D&source=calendar&ust=1706736080204490&usg=AOvVaw2RYHuWzwpu0LI-PLUgoEWZ) changes the implementation for waypoints to really require running under it's own identity (svc account) as well as likely needing new installation mechanics/flags (potentially something like a waypoint-for flag).

- [ ] updates for istioctl x waypoint

**Comment by MorrisLaw** [comment]
> @MorrisLaw, any chance you'd have time to dig in on this?

@ilrudie yeah, I can look into this.

**Comment by ilrudie** [comment]
Thank you!

**Comment by MorrisLaw** [comment]
Will continue this after implementing the prerequisite issue: https://github.com/istio/istio/issues/49851

**Comment by ilrudie** [comment]
I don't think this is a prereq

**Comment by MorrisLaw** [comment]
Ok, yeah that's a good point.

**Comment by ilrudie** [comment]
wondering if it makes sense to be able to name waypoints with istioctl... I think that's a good idea we're going to want since otherwise naming is tied to the old service account functionality

**Comment by MorrisLaw** [comment]
> wondering if it makes sense to be able to name waypoints with istioctl... I think that's a good idea we're going to want since otherwise naming is tied to the old service account functionality

I like the idea of this. Were you thinking of something like a `nameWaypointCmd` or something different @ilrudie ?

**Comment by hanxiaop** [comment]
> > wondering if it makes sense to be able to name waypoints with istioctl... I think that's a good idea we're going to want since otherwise naming is tied to the old service account functionality
> 
> I like the idea of this. Were you thinking of something like a `nameWaypointCmd` or something different @ilrudie ?

@MorrisLaw I think it can simply be a `--name` flag?

**Comment by ilrudie** [comment]
it looks like we're handling this elsewhere already. the problem we have is we're getting rid of the service account attachment which used to provide the name. without a service account you just get a waypoint called `namespace` which used to make sense but now is meaningless and doesn't provide a UX for having multiple waypoints (via istioctl at least)

**Comment by MorrisLaw** [comment]
Can close after merging of waypoint-for annotation work
