### ISSUE TITLE
WDS: svc-addressed waypoint capture

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#49435]
Presently WDS allows only for workloads to have a waypoint assigned. We need to extend WDS to allow for adding waypoint to a service to prepare for further implementation of [Ambient - Capture for Services and Workloads](https://www.google.com/url?q=https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit%23heading%3Dh.i456k47e7s5d&sa=D&source=calendar&ust=1706736080204490&usg=AOvVaw2RYHuWzwpu0LI-PLUgoEWZ)

Istio side of https://github.com/istio/ztunnel/issues/816

**Comment by MorrisLaw** [comment]
Closed by this merged PR: https://github.com/istio/istio/pull/49501
