### ISSUE TITLE
istio - rewriteAppHTTPProbers default value true causes connection pooling issues for probe requests

### ISSUE THREAD

**Issue by yogeshgadge** [istio/istio#49454]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Noticing that when `sidecar.istio.io/rewriteAppHTTPProbers: 'true'` nginx is not able to pool this connection between the istio-proxy sidecar and container (nginx).

I print access logs of nginx with `$connection` and `$connection_requests` and with both liveness and readiness probes running every 10 sec rewriteAppHTTPProbers with true and false here is what I get:-

### /rewriteAppHTTPProbers: 'true

Every time new connection. Only 1 request per connection.
```
{ connection: 8,  connection_request: 1, path: "/liveness"} 
{ connection: 7,  connection_request: 1, path: "/readiness"} 
{ connection: 6,  connection_request: 1, path: "/liveness"} 
{ connection: 5,  connection_request: 1, path: "/readiness"} 

```

### /rewriteAppHTTPProbers: 'true'

nginx is able to use same connection. Multiple requests per connection..
```
{ connection: 5,  connection_request: 4, path: "/liveness"} 
{ connection: 5,  connection_request: 3, path: "/readiness"} 
{ connection: 5,  connection_request: 2, path: "/liveness"} 
{ connection: 5,  connection_request: 1, path: "/readiness"} 

```

So by setting `rewriteAppHTTPProbers: 'false'` my app is benefiting from it as long as concurrency is NOT set to 0
. When concurrency is set to 0 I get no benefit of `rewriteAppHTTPProbers: 'false'`
```
proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
          concurrency: 0
```

I think  `rewriteAppHTTPProbers` should not have any effects on connection pool on the container side.
Setting `concurrency: 0` should affect only threads and resources on the sidecar while allowing containers todo connection pooling.

 

### Version

```Text
# i do not have access to istio-system namespace but the version is Istio Version

    v1.20.2
docker.io/istio/proxyv2:1.20.2 is proxy

```

```
$kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
```
```


### Additional Information

Additional details:
- probes are at http1.1

**Comment by howardjohn** [comment]
kubelet itself should not be reusing the connection; istio-agent mirrors that logic. Is that who is sending the traffic? Or some alternative 3rd party?
