### ISSUE TITLE
Feature-Request: Support WasmServices via WasmPlugin

### ISSUE THREAD

**Issue by ReToCode** [istio/istio#49451]
**Describe the feature request**
The current [Wasm-Plugin](https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/) WASM plugin can be used as type http-filter or network-filter. To build more advanced plugins it can be veriy helpful to also have support for [Wasm Service](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/doc/OVERVIEW.md#wasm-service). This can be used to do some shared work like caching or call-outs to external services in a single thread instead of having to replicate/re-do the work in every http/network filter. So basically the feature request is to also support the type WasmService via `kind: WasmPlugin`.

**Describe alternatives you've considered**
It seems that this can already be done using a `EnvoyFilter` that merges to the `BOOTSTRAP` config ([example](https://istio.io/latest/docs/reference/config/networking/envoy-filter/)) but this seems way more verbose and leads to an additional configuration with another pattern. Also the envoy-filter approach does not support getting the code from OCI, as there is no loader for `EnvoyFilter`.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

I don't know

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
For further reference, an example of what I'm trying to build can be found here: https://github.com/ReToCode/envoy-request-buffer. On istio, the current code uses a second WASM module (which is a [singleton WasmService](https://github.com/ReToCode/envoy-request-buffer/blob/main/local-envoy/envoy.yaml#L4) in the raw envoy variant). In istio the shared service is loaded multiple times (and thus calls the control-plane more often than necessary) and has to provide an unnecessary [HttpContext](https://github.com/ReToCode/envoy-request-buffer/blob/main/wasm-request-buffer/service/main.go#L45) to avoid startup errors in istio.

**Comment by zirain** [comment]
> It seems that this can already be done using a EnvoyFilter that merges to the BOOTSTRAP

I think this's removed, you can achieve this with https://github.com/zirain/istio/blob/b6fc1fb732a5541624869141abb3ae3443044300/samples/custom-bootstrap

**Comment by ReToCode** [comment]
> I think this's removed, you can achieve this with

Ah ok, then I've seen outdated examples for that. Still, would be great to do it with a `WasmModule`. [This](https://github.com/zirain/istio/tree/b6fc1fb732a5541624869141abb3ae3443044300/samples/custom-bootstrap) also looks a bit hacky, especially if you target gateways which might have been auto-deployed (like GW-API Gateways with auto-provisioning).

**Comment by zirain** [comment]
I really don't think WasmPlugin is a good idea, because it's design for dynamic filters. Besides [custom boostrap](https://github.com/istio/istio/tree/b6fc1fb732a5541624869141abb3ae3443044300/samples/custom-bootstrap), another option is MeshConfig, but I'm not sure it's worth it. 
@howardjohn @kyessenov @costinm WDYT?

**Comment by kyessenov** [comment]
Yes, Istio APIs do not cover bootstrap modifications well since they are not dynamic. There are other ad-hoc ways, which solve the need.

**Comment by Aarif123456** [comment]
> Yes, Istio APIs do not cover bootstrap modifications well since they are not dynamic. There are other ad-hoc ways, which solve the need.

@kyessenov what's the recommended way to load singleton WASM in Istio? Custom bootstraps are fairly painful and don't support OCI
