### ISSUE TITLE
Broken pipe on applications when traffic is routed via sidecar with default configuration

### ISSUE THREAD

**Issue by someshkoli** [istio/istio#49484]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have a simple istio setup as described below
aws loadbalancer -> gateway -> (sidecar -> application server)

Earlier we used to have a setup without istio, something like below
aws loadbalancer provisioned via ingress controller -> application server

Since we have moved to istio setup, we're getting _broken pipe_ errors on our application continuously (2-3 every mins). On debugging this we realized the errors go away if we remove sidecar injection. 
On looking further into traces, we found traces with DC disconnection traces.
Although I'm not sure if these DC disconnect are the cause for this, just putting it out here.
![image](https://github.com/istio/istio/assets/41543649/a94a017c-5ebe-4323-933a-2acf31ce10aa)

Further, 
I noticed that in our setup we have not set any keepaliveduration and keepaliverequestcount for envoy connection pool, my assumption here is that envoy -> application connections should never close or atleast those connections should never be closed by envoy proxy.
looking at netstat for envoy -> application connections, there are multiple connections in time_wait state. From what I understand, this state comes up when the client initiates a connection shut down ? (I may be wront here)
![image](https://github.com/istio/istio/assets/41543649/f82dac34-fa72-449e-b862-b88ed4b8347a)

On looking at TCP dump, found that pods were getting RST packets from 127.0.0.6 on our application server port (8080)
![image](https://github.com/istio/istio/assets/41543649/78f990f8-de7d-4270-a3d9-a9b5a281dd5a)

Unable to pinpoint what's causing these connection shutdowns

### Version

```Text
client version: 1.16.1
control plane version: 1.18.2
data plane version: 1.18.2 (169 proxies)

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.28.5-eks-5e0fdde

v3.8.0+gd141386
```

**Comment by someshkoli** [comment]
still valid^

**Comment by someshkoli** [comment]
still valid

**Comment by vandathron** [comment]
@someshkoli Did you get the root cause and solution to this? Experiencing same issue

**Comment by someshkoli** [comment]
> @someshkoli Did you get the root cause and solution to this? Experiencing same issue

It's been quite some time since this, from what I remember we never found the root cause. As of today I no longer work for the firm, so can't be certain about it and also can't provide further information
