### ISSUE TITLE
cleanup: move dockerfiles to top-level component directories

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#4951]
This is a standard practice for placing Dockerfiles. We should move them to mixer/Dockerfile, pilot/Dockerfile, etc.

**Comment by costinm** [comment]
Not sure it is a standard practice - I would rather move all dockerfiles in the top level (/docker/mixer/Dockerfile, /docker/pilot/Dockerfile, etc) - and make sure they have a restricted set of owners and are consistent ( same base, etc ).
