### ISSUE TITLE
Unready istio-proxy container not evicted

### ISSUE THREAD

**Issue by NahuelVarela** [istio/istio#49512]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Each of my services consists of:

- Deployment
- Service
- Virtual Service

We have found that whenever we deploy +10 services in a single helm chart, some of our services become unavailable with:
> "upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection timeout".
This occurs randomly, sometimes in service A, sometimes in service B, etc.

We also found that such error goes away if the pod get's deleted and Kubernetes creates a new pod.
We also found that increasing the replicas from 1 to n+1 also helps mitigate this problem.

Another error that my be related is that almost 50% of the time, when we deploy, helm fails with:

> helm.go:84: [debug] cannot patch "analytics-gateway" with kind Gateway: Internal error occurred: failed calling webhook "validation.istio.io": failed to call webhook: Post "[https://istiod-asm-1203-4.istio-system.svc:443/validate?timeout=10s](https://istiod-asm-1203-4.istio-system.svc/validate?timeout=10s)": dial tcp x.x.x.x:15017: i/o timeout
(ip redacted)

We have also tested that while we get the upstream connect error, we are capable of connecting directly to the container running our code and we get 200 healthy status.

Any idea what could be happening here?

### Version

```Text
We are using 
- GKE: 1.28.3-gke.1286000
- istio: asm-1203-4
- helm: v3.10.0+gce66412
```

**Comment by ramaraochavali** [comment]
So do you deploy only one replica for each deployment?

**Comment by NahuelVarela** [comment]
@ramaraochavali In development, yes.
