### ISSUE TITLE
Calico tests break co-located unit test jobs (indefinitely)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49522]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49215/unit-tests_istio/1761105307632668672

Calico loads the ipip and/or ip_tunnel kernel modules (not sure which tbh). This permanently adds a `tunl0` interface in all namespaces.

The above test expects a new network namespace only has `lo`.

Probably the test should be a bit more permissive?

cc @bleggett @ilrudie

**Comment by ilrudie** [comment]
as a practical matter should we revert the calico job while we work this out?

**Comment by howardjohn** [comment]
I am fine with that or just changing the unit test which would be pretty quick. I am not sure the best way to do that -- we could hardcode allow tunl0 but its kind of fragile.. but good enough?

**Comment by bleggett** [comment]
> Probably the test should be a bit more permissive?

Yeah this would be my pref, we really have no control over how many pod interfaces there are and it shouldn't matter if we have 1 or 100.

**Comment by ilrudie** [comment]
https://github.com/istio/test-infra/pull/5224

I have some issue working with this particular test. For now lets remove the job and I'll circle back to it

**Comment by ilrudie** [comment]
> > Probably the test should be a bit more permissive?
> 
> Yeah this would be my pref, we really have no control over how many pod interfaces there are and it shouldn't matter if we have 1 or 100 - traffic routing is what we care about, not interface count.
> 
> Let's try making that test _not_ hardcode interface lists and if that works leave it in. If it's not that trivial, we can revert - though may still need to recycle prow instances to evict the kmod, even so, so would rather fix the test.
> 
> (as a followup we can see if it's possible to get `calico` to not load kmods, but as with eBPF this might just be a case where it's possible to load something that alters kernel behavior for subsequent tests if we don't carefully unhook it)

In _this_ test specifically I think it does need to care about the interfaces. It's attempting to test that we're in a sandbox so if we have an eth0 present for instance then it really should fail. IMO having a list of "allowed" interfaces we filter out before the check for only "lo" probable strikes the best balance.

**Comment by bleggett** [comment]
`TestRunInSandbox` just needs to know what netns it is in - it's using the iface list a proxy for that.

We can do that without looking at the iface list at all easily enough, e.g: https://github.com/vishvananda/netns/blob/master/nshandle_linux.go#L16

**Comment by ilrudie** [comment]
https://github.com/istio/istio/pull/49563

Nice idea Ben. I gave it a shot.

**Comment by ilrudie** [comment]
For tracking I've filed https://github.com/istio/test-infra/pull/5228 to re-add the job once we're happy with the fix.

**Comment by ilrudie** [comment]
most immediate problem resolved by #49563
