### ISSUE TITLE
Deprecate doc on distributed tracing for OpenCensus and add OpenTelemetry docs

### ISSUE THREAD

**Issue by npuichigo** [istio/istio#49552]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Deprecate doc on distributed tracing for OpenCensus and add OpenTelemetry docs
**Describe alternatives you've considered**
N/A
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
it's WIP and will move forward after 1.21.0 released.
