### ISSUE TITLE
Unable to build Istio 1.20.3 or 1.19.7 from source

### ISSUE THREAD

**Issue by lgadban** [istio/istio#49561]
Attempting to build `istio/proxy` from source at tags [1.20.3](https://github.com/istio/proxy/tree/1.20.3) or [1.19.7](https://github.com/istio/proxy/tree/1.19.7) will fail.

Releases [1.20.3](https://github.com/istio/istio/releases/tag/1.20.3) and [1.19.7](https://github.com/istio/istio/releases/tag/1.19.7) were security releases prompted by [ISTIO-SECURITY-2024-001](https://istio.io/latest/news/security/istio-security-2024-001/).

While the published builds are correct, any downstream user attempting to build from these tags will run into a checksum error. This build failure is due to a discrepancy in the private security build process regarding how the SHA256 that was calculated for envoy. 

Unfortunately we can not modify the existing tags for 1.19.7 & 1.20.3, so this issue will be used to document the problem as well as provide a path forward for users.

The patch branches that were used to produce the release artifacts will be corrected.
Once this is done, downstream consumers will have some options for building these releases:
* Build off the patch branches rather than the tags
* Build off the tagged releases but add the patches locally to fix

**NOTE: If you build both istio/proxy and istio/istio yourself, please [see this comment](https://github.com/istio/istio/issues/49561#issuecomment-1973960460).**

Sincere apologies to all impacted users!
We have corrected this discrepancy and will be adding additional checks in our pipeline to be sure this does not happen again.

**Comment by lgadban** [comment]
The patch branches have been correctly updated.

As outlined above, builds should be possible from these branches or by using the patches from the PRs in a local environment.

1.19.7
proxy: https://github.com/istio/proxy/pull/5317
istio: https://github.com/istio/istio/pull/49569

1.20.3:
proxy: https://github.com/istio/proxy/pull/5362
istio: https://github.com/istio/istio/pull/49568

**Comment by lgadban** [comment]
The `istio/istio` patch branches have been updated to revert the latest commit:
1.19.7: https://github.com/istio/istio/pull/49669
1.20.3: https://github.com/istio/istio/pull/49668

This is to [resolve an issue](https://github.com/istio/istio/pull/49568#issuecomment-1968012161) where users building `istio/istio` but NOT building `istio/proxy` were encountering build failures.

This was broken because a [commit was added](https://github.com/istio/istio/commit/c204ecaff7af64f905cd51c6fc75844993b2dc1b) to point `istio.deps` to the SHA of [the commit to fix `istio/proxy`](https://github.com/istio/proxy/commit/c6043aa697a170c3aa21afc2671958f1ca85de22).
Because this commit of istio/proxy was done on a patch branch, there was no actual proxy built, thus the [envoy-alpha-commit.tgz](https://storage.googleapis.com/istio-build/proxy/envoy-alpha-c6043aa697a170c3aa21afc2671958f1ca85de22.tar.gz) for it does not exist (whereas [it does exist for the previous commit](https://storage.googleapis.com/istio-build/proxy/envoy-alpha-30e213147c5e54158b6176417c39c46eca60c580.tar.gz).

The end result is now the patch branches are all buildable on their own, **however if you build both `istio/proxy` and `istio/istio`, you will need to update `istio.deps` in `istio/istio` to reference your built `istio/proxy` SHA**.

**Comment by howardjohn** [comment]
I think this has been resolved (as much as it will be) per https://github.com/istio/istio/issues/49561#issuecomment-1973960460. Thanks @lgadban
