### ISSUE TITLE
Ambient waypoint 2.0 xDS design

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49562]
As part of https://docs.google.com/document/d/1DAM_6SajCyC2hD8wBUraaZWZJqUVYPyemzw0-xpHmdY/edit#heading=h.qntbxk5xx45, we need to tweak the xDS config for Istio waypoints.

There will be two modes (maybe): PROXY sandwich and native HBONE.

Both of these are largely the same 2 tier routing, just slightly different first tier.

A nice goal would be to re-use as much of the existing Gateway xDS generation as possible, though we  won't get 100%.

Proposal:

**First tier routing** needs to pick a service and port destination. For HBONE, this will be HTTP hostname header matches (just like waypoint today). For PROXY, this will be on the TLV.

For HBONE:

```
connect_terminate:
  Terminate CONNECT
  Single filter chain, terminating TLS and sending through HCM
  Single route, terminating CONNECT, sending to main_internal
main_internal:
  Multiple filter chains, one per service-port
  Matcher tree: Match IP -> Match port -> (if required, sniffed) Match Protocol
```

For PROXY:

```
proxy_terminate:
  Listener filter for PROXY termination. TLV sets metadata for destination IP/port
  Multiple filter chains, one per service-port
  Matcher tree: Match IP (from TLV) -> Match port (from TLV) -> (if required, sniffed) Match Protocol
```

cc @stevenctl @louiscryan

**Comment by stevenctl** [comment]
Prototype here: 

Istiod: https://github.com/istio/istio/pull/49097
zTunnel: https://github.com/istio/ztunnel/pull/789

**Comment by stevenctl** [comment]
The xDS changes are pretty small. In PROXY mode:

* Don't generate connect_terminate/connect_originate
* "proxy_terminate" above is actually identical to main_internal but adds the PROXY filter and binds
* Filter chains do `set_filter_state` using PROXY TLV instead of original_dst

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/50006
