### ISSUE TITLE
Istio should consistently set transport socket match for headless services attached to ingress gateway

### ISSUE THREAD

**Issue by karthikbox** [istio/istio#49584]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi folks,

We noticed the following behavior when an k8s headless service is attached to a istio gateway:

1. if all backends of the headless service have a sidecar, cds with transport socket match to do auto mtls is generated.
2. if atleast 1 backend of the headless service has no sidecar, cds with neither transport socket nor socket match is generated.

the drawback of doing so is that - istiod disables auto mtls for all backends of the service even if some of them do have a sidecar and can do mtls.

Considering that the cds cluster uses eds, istiod should just consistently generate cds cluster with transport socket match set. The transport socket match will take  care of doing mtls to endpoints with sidecar and plain text to services to not having sidecar.

We suspect [this logic](https://github.com/istio/istio/blob/f69047b03842074eb2f56fef5d9ad7ba326de4cc/pilot/pkg/model/push_context.go#L2333) in istiod is causing this issue.

This logic is fine for mesh cases, however, for ingress seems less optimal.

### Version

```Text
istio 1.19
```

**Comment by zengyuxing007** [comment]
Perhaps you could declare two services, let the injection state of the instances under each service is consistent.

The connectivity behavior of the istio ingress gateway to upstream is configured using a cluster-level configuration, not endpoints.
