### ISSUE TITLE
Changing of Request Method from PUT or DELETE to GET when request reaches ISTIO

### ISSUE THREAD

**Issue by Adharsh-Muraleedharan** [istio/istio#49597]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When a PUT or a DELETE request is made to our APPlication hosted on a EKS cluster with istio as a service mesh. When the request is reaching the ISTIO Ingress it is getting converted into a GET call. The Traffic comes through an ALB to the istio ingress Gateway where we are seeing the request getting converted into a GET method call.

The Application is hosted on EKS 1.24. The Delete request is also made through a sidecar ENVOY. We tried routing the request from the ALB to an instance without istio the request reaches there as PUT/DELETE.

### Version

```Text
istioctl version
client version: 1.16.4
control plane version: 1.16.4
data plane version: 1.16.4

Kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-5e0fdde",  Platform:"linux/amd64"}
```

**Comment by howardjohn** [comment]
I don't think Istio even has the capability to change the method type so this seems very likely that something outside of Istio is changing it. Maybe you can trace the request through the various hops and examine at each point 

PS Istio 1.16 is far EOL and has a number of security issues, etc
