### ISSUE TITLE
istioctl kube-inject have no error and any error output,but does not produce inject sidecar yaml

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#4959]
@becile commented on [Fri Feb 02 2018](https://github.com/istio/istio.github.io/issues/927)

istioctl kube-inject have no error and any error output,but does not produce inject sidecar yaml.
in my env.it's because there is no ~/.kube/config file,but istioctl has no error info,so can we add "in the env,there is must exsit available ~/.kube/config file"

---

@becile commented on [Fri Feb 02 2018](https://github.com/istio/istio.github.io/issues/927#issuecomment-362550784)

[root@localhost istio-0.4.0]# istioctl version
Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.9.1

[root@localhost istio-0.4.0]# /opt/cloudlink/phoenix/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost istio-0.4.0]# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

---

@becile commented on [Fri Feb 02 2018](https://github.com/istio/istio.github.io/issues/927#issuecomment-362551443)

when there is no kubeconfig file,error:
[root@localhost istio-0.4.0]# ll ~/.kube/config
ls: cannot access /root/.kube/config: No such file or directory
[root@localhost istio-0.4.0]# 
[root@localhost istio-0.4.0]# istioctl kube-inject -f samples/sleep/sleep.yaml

when there is kubeconfig file,correct:
[root@localhost istio-0.4.0]# ll ~/.kube/config 
-rw-------. 1 root root 219 Feb  1 22:54 /root/.kube/config
[root@localhost istio-0.4.0]# cat ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: ""
  name: k8s
current-context: k8s
kind: Config
preferences: {}
users: []
[root@localhost istio-0.4.0]# 
[root@localhost istio-0.4.0]# istioctl kube-inject -f samples/sleep/sleep.yaml|more
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
......

**Comment by ayj** [comment]
This should be fixed by https://github.com/istio/istio/pull/2334 (Dec 25, 2017)
