### ISSUE TITLE
Implement external (from the mesh to the outside) traffic control

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#496]
Instead of defining external services or IP ranges to be ignored by proxies.
Based on the design proposals https://goo.gl/94DTSH, https://goo.gl/eYY7na.

It includes support of various protocols, and also routing-rules-to-egress-rules, like fault injection, http redirection, http rewrite, etc., when the target is an external (outside of the mesh) service

**Comment by vadimeisenbergibm** [comment]
Related issues:
https://github.com/istio/pilot/issues/67
https://github.com/istio/pilot/pull/463
https://github.com/istio/pilot/issues/515

**Comment by ldemailly** [comment]
can you elaborate a bit more on what you propose ?
afaik egress seems http/https only as well as cumbersome as you have to list every service you might use while https://github.com/istio/pilot/issues/903 would be to not try to adversely affect external traffic

**Comment by vadimeisenbergibm** [comment]
@ldemailly Please see design proposal https://goo.gl/94DTSH. Your comments are welcome.
This design proposal is about adding to Istio egress rules with wildcards, to specify, for example, that all the traffic to `*.bluemix.net` or `*.amazonaws.com` goes thru egress. This way there is no need to list every service.

**Comment by vadimeisenbergibm** [comment]
@ldemailly Please see also https://github.com/istio/istio/issues/552 .
