### ISSUE TITLE
Record some identifier in pilot inbound/outbound listener conflict metrics

### ISSUE THREAD

**Issue by cathal-c** [istio/istio#49624]
**Describe the feature request**
Today, Pilot publishes a set of metrics for listener configs, namely
* pilot_conflict_inbound_listener
* pilot_conflict_outbound_listener_http_over_current_tcp
* pilot_conflict_outbound_listener_tcp_over_current_http
* pilot_conflict_outbound_listener_tcp_over_current_tcp

However these metrics are all published without any identifying labels (actually without any labels at all). This makes it arduous to identify which proxy/service is getting conflicts. It also makes it impossible to filter out any acceptable conflicts you may have in your cluster. This is particularly annoying in the case of TCP headless services, which seem to generate conflicts 100% of the time.

For example. a headless service `kafka` pointing to three replicas tends to generate conflicts:
```
    "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
        "1.1.1.1:18106": {
            "proxy": "foo",
            "message": "Listener=1.1.1.1:18106 AcceptedTCP=kafka-0.default.svc.cluster.local RejectedTCP=kafka.default.svc.cluster.local TCPServices=1"
        },
        "1.1.1.2:18106": {
            "proxy": "foo",
            "message": "Listener=1.1.1.2:18106 AcceptedTCP=kafka-1.default.svc.cluster.local RejectedTCP=kafka.default.svc.cluster.local TCPServices=1"
        },
        "1.1.1.3:18106": {
            "proxy": "foo",
            "message": "Listener=1.1.1.3:18106 AcceptedTCP=kafka-2.default.svc.cluster.local RejectedTCP=kafka.default.svc.cluster.local TCPServices=1"
        }
    },
```

This is an "acceptable" conflict - in that to my knowledge this does not impact traffic routing and I can ignore it - yet there is no way for me to know this via metrics alone. I have to inspect logs to confirm.

It would be great to have some identifiable label which I can use to filter out noise. "Proxy" perhaps? As the context for that information is already there (it's logged): https://github.com/istio/istio/blob/release-1.21/pilot/pkg/networking/core/v1alpha3/listener.go#L300-L308

I'm curious if this is something that would be at all entertained. If so, I could possibly invest some time here. I am weary of cardinality issues as this label would be unbounded, but I can't imagine it would realistically be a problem, and there are plenty of other unbounded labels throughout Istio.

**Describe alternatives you've considered**
Currently the only alternative is logs.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
will that cause high cardinality labels

**Comment by CathalC2011** [comment]
@zirain being unbounded it is technically possible, but unless someone has a really mad setup I can't see it being an issue. All of Istio's traffic metrics are currently unbounded, and people tend to accept that.

Would this be acceptable behind a feature flag?

**Comment by zirain** [comment]
> Would this be acceptable behind a feature flag?

that make sense to me

**Comment by howardjohn** [comment]
I am a bit worried about such a niche feature flag without a path to promotion.

> AcceptedTCP=kafka-1.default.svc.cluster.local RejectedTCP=kafka.default.svc.cluster.local

You have 2 services for the same workload I guess? 1 cluster IP 1 headless?

**Comment by zirain** [comment]
> I am a bit worried about such a niche feature flag without a path to promotion.

TBH, I don't think it will be promoted. It should be alway an option.

**Comment by howardjohn** [comment]
It's not scalable to add an optional metric for every possible thing someone may want to expose. In this case the request is to expose more information about an error so it can be filtered.

A more sustainable approach would be to investigate if we can fix the error entirely so users don't have to filter out the false positives, IMO

**Comment by CathalC2011** [comment]
> I am a bit worried about such a niche feature flag without a path to promotion.
> 
> > AcceptedTCP=kafka-1.default.svc.cluster.local RejectedTCP=kafka.default.svc.cluster.local
> 
> You have 2 services for the same workload I guess? 1 cluster IP 1 headless?

Nope, just a single headless service seems to generate this!

**Comment by howardjohn** [comment]
can you give a reproducer

**Comment by howardjohn** [comment]
> can you give a reproducer

Any chance to give this info?
