### ISSUE TITLE
After upgrading istio 1.19.6 we are facing OPTIONS call preflight failure 

### ISSUE THREAD

**Issue by Amutha14** [istio/istio#49661]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
I am connecting external service inside from istio-mesh
After upgrading istio 1.19.6 we are facing OPTIONS call preflight failure, but the same is working in POST call.
I tried adding **insecureSkipVerify: true** as per [change notes](https://istio.io/latest/news/releases/1.19.x/announcing-1.19/change-notes/#security)  but still facing the issue

Error in OPTIONS call Requested host does not match any Subject Alternative Names (SANs) on TLS certificate

### Version

```Text
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example
spec:
  host: example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      insecureSkipVerify : true

--------------------

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
spec:
  hosts:
  - "*.example.com"
  - a.example.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  exportTo:
  - istio-system
```

**Comment by howardjohn** [comment]
this error seems to either come from your application or the website you are connecting to. So it's hard to debug without more info. But your SE also looks like it's expecting to receive TLS and then also adding another layer of TLS on top which seems wrong.

You might also need to set `sni` in the destination rule

**Comment by MohanakannanNS** [comment]
Hi @howardjohn, Issue is the same config works fine for POST call means it is able to establish the TLS connection. But for OPTIONS call alone we are getting the below error: 
Requested host does not match any Subject Alternative Names (SANs) on TLS certificate in use with this connection.

The same config works previously for both OPTIONS and POST call, recently only we are getting this error.

If I remove the host value from the request header then same exception occurs for POST call too. This host value set in the request header in virtualservice.yaml file.
Could you please help us why OPTIONS call alone is getting failed.

**Comment by Amutha14** [comment]
@howardjohn Thanks issue got resolved after destroy and deployed with sni configuration. Thanks for your help, it saved our time...
But have few queries 
1. why it is not work for OPTIONS call alone in POST call got response?
2. Tried in the older istio version also but the same issue persists so it is not related to the version upgrade, it was working earlier but not sure when it got broken, need to know why the issue occurred.

**Comment by howardjohn** [comment]
> why it is not work for OPTIONS call alone in POST call got response?

As I mentioned in https://github.com/istio/istio/issues/49661#issuecomment-1973761351 this error comes from _your application_. So I cannot answer that question without context on your application. Does it treat OPTIONS differently? Or is there more differences other than just the method? etc?
