### ISSUE TITLE
503 UC upstream_reset_before_response_started{connection_termination}

### ISSUE THREAD

**Issue by giacomolm** [istio/istio#49660]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have been observing intermittent 503 errors while connecting from one istio gateway to another one in a different region. For some reasons cluster connection gets terminated, although the `idle_timeout` seems to be all aligned: honestly I could not find out why this happens. 

I've seen different issues/threads about this, but none of the solutions proposed for me have worked. I am evaluating the following EnvoyFilter and I would like understand if that helps to mitigate the issue. It is based on the [this](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http2protocoloptions) documentation, more specifically the [connection_keepalive](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-keepalivesettings) property 

```kind: EnvoyFilter
metadata:
  name: gateway-envoyfilter
spec:     
  configPatches:
  - applyTo: CLUSTER
    match:    
      cluster:
        name: outbound|80||<DESTINATION>
    patch:      
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options:
                connection_keepalive:
                  interval: 30s
                  timeout: 5s
```
WDYT ?

### Version

```Text
$ istioctl version              
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (328 proxies)

$ kubectl version
Client Version: v1.28.3
Server Version: v1.24.17
```

**Comment by djahandarie** [comment]
@giacomolm Did you try this connection_keepalive EnvoyFilter out, and did it work for you?
