### ISSUE TITLE
Enable ENABLE_ENHANCED_RESOURCE_SCOPING by default in 1.22

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49696]
Should we promote this now?

If so, we will need to change the default to `true`, set it in older compatibility versions, and write a `precheck` to warn any users that have `discoverySelectors` set in their mesh config

cc @hzxuzhonghu @kfaseela

**Comment by kfaseela** [comment]
@leosarra will you be interested in picking this up?

**Comment by leosarra** [comment]
Sure. I'm interested

**Comment by kfaseela** [comment]
> Sure. I'm interested .
> I will assign it to me if that is fine for everyone 

Yes please

**Comment by hzxuzhonghu** [comment]
agreed

**Comment by leosarra** [comment]
This is currently blocked by #49786
