### ISSUE TITLE
Istio should support proxy for external service - egress rules

### ISSUE THREAD

**Issue by Adiqq** [istio/istio#4969]
Hi,

According to https://istio.io/docs/tasks/traffic-management/egress.html it is possible to set egress rules for addresses outside of the k8s cluster.
In some environments, cluster has no access to public internet, except through proxy.

It should be possible to create proxy definitions (address, port, optional user/password) and bind specific proxy to given egress rule.

**Comment by rshriram** [comment]
Also addressed in the new Istio APIs.. we even have an end to end test for this.. You can take this for a test drive by compiling code from Istio master (or try the upcoming 0.8 releases)

**Comment by james-r-smith** [comment]
@rshriram, can you provide where it's addressed in the new APIs, and which end to end test has this configuration. I'm in the same situation as @Adiqq, and I have no idea what I'm doing wrong. I just know it works completely fine without the sidecar, and with the sidecar everything is returning 404. Any tips are much appreciated. Thanks!
