### ISSUE TITLE
Ingress - allow custom ports

### ISSUE THREAD

**Issue by Adiqq** [istio/istio#4970]
Istio ingress should allow specifying custom ports for HTTP/HTTPS.
Voyager ingress is HAproxy ingress that allows it.
https://appscode.com/products/voyager/6.0.0/guides/ingress/http/custom-http-port/

**Comment by rshriram** [comment]
We already have this support implemented.. in Istio gateway (https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto).. and it should be available in 0.8
