### ISSUE TITLE
istioctl upgrade with verify flag fails on DaemonSet

### ISSUE THREAD

**Issue by slideroh** [istio/istio#49718]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I would like to point out that I have already seen this error here in the issue listed, I think as merged (https://github.com/istio/istio/pull/48219) or closed, however, it still occurs in the latest version.

During `istioctl upgrade --verify` the following error kept appearing (re-run will fix):
```
✘ DaemonSet: istio-cni-node.istio-system: Istio installation failed, incomplete or does not match "generated from IOP:installed-state": DaemonSet istio-system/istio-cni-node is not ready. 3 out of 4 expected pods are ready
```

Has the mentioned merge already been added to the release?

### Version

```Text
$istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (23 proxies)

$kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```

**Comment by ilrudie** [comment]
This wasn't cherry picked to 1.20 that I can see and the PR merged after the 1.20 branch cut. The first release containing this code should be 1.21. There is an RC for 1.21 out with the release coming soon.
