### ISSUE TITLE
DNS Proxying for Headless Services resolves to old POD IPs

### ISSUE THREAD

**Issue by flostadler** [istio/istio#49769]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm having issues with DNS Proxying for Headless Services.

DNS proxying is turned on by setting the following two env variables:
- `ISTIO_META_DNS_CAPTURE: "true"`
- `ISTIO_META_DNS_AUTO_ALLOCATE: "true"`

This works fine for the first revision of the deployment, but as soon as I trigger an upgrade (e.g. `kubectl rollout restart`) it falls apart because istio continues to resolve the DNS name to the old IPs of the deployment.

Running the following also shows that the proxy has outdated DNS information:
```
kubectl exec --stdin --tty istiod-646b5b7489-9tdnw -n istio-system -- curl 'localhost:8080/debug/ndsz?proxyID=verification-service-649bd75468-29zlw.verification-service' | jq -r '.resource.table."dummy-service-us.dummy-service-us.svc.cluster.local"'

Output:
{
    "ips": [
        "172.19.64.59",
        "172.19.64.125",
        "172.19.66.163"
    ],
    "registry": "Kubernetes",
    "shortname": "dummy-service-us",
    "namespace": "dummy-service-us"
}
```

Whereas the actual IPs are:
```
kubectl get pods -n dummy-service-us -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
dummy-service-us-6cbc8c94c6-d7g9j   3/3     Running   0          5h      172.19.66.163   ip-REDACTED.ec2.internal   <none>           <none>
dummy-service-us-6cbc8c94c6-k764p   3/3     Running   0          4h59m   172.19.65.86    ip-REDACTED.ec2.internal   <none>           <none>
dummy-service-us-6cbc8c94c6-kvwkb   3/3     Running   0          5h      172.19.66.121   ip-REDACTED.ec2.internal   <none>           <none>
```

### Version

```Text
$ istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (5 proxies)

$ kubectl version
Client Version: v1.29.1
Server Version: v1.28.5-eks-5e0fdde
```

### Additional Information

Target cluster context: arn:aws:eks:us-east-1:REDACTED:cluster/REDACTED

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-03-06 16:23:34.372376 +0100 CET

Cluster endpoint: https://REDACTED.gr7.us-east-1.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.20.3", GitRevision:"Homebrew", GolangVersion:"go1.21.7", BuildStatus:"Homebrew", GitTag:"1.20.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.3", GitRevision:"692e556046b48ebc471205211c68a2c69e74a321", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.3"},
    },
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.3", GitRevision:"692e556046b48ebc471205211c68a2c69e74a321", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.3"},
    },
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.20.3", GitRevision:"692e556046b48ebc471205211c68a2c69e74a321", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.3"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.3}

Fetching logs for the following containers:

aws-load-balancer-controller/aws-load-balancer-controller/aws-load-balancer-controller-848cdcf7fd-5zpmr/aws-load-balancer-controller
aws-load-balancer-controller/aws-load-balancer-controller/aws-load-balancer-controller-848cdcf7fd-lknl9/aws-load-balancer-controller
cert-manager/aws-privateca-issuer/aws-privateca-issuer-6d957b47b8-4f5ch/aws-privateca-issuer
cert-manager/aws-privateca-issuer/aws-privateca-issuer-6d957b47b8-rq9gk/aws-privateca-issuer
cert-manager/cert-manager-cainjector/cert-manager-cainjector-764f57bc-2vncz/cert-manager-cainjector
cert-manager/cert-manager-cainjector/cert-manager-cainjector-764f57bc-lx6jr/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-7b5886cbcd-kxvfv/cert-manager-webhook
cert-manager/cert-manager-webhook/cert-manager-webhook-7b5886cbcd-tx4v5/cert-manager-webhook
cert-manager/cert-manager/cert-manager-79685bfc47-sg6d5/cert-manager-controller
cert-manager/cert-manager/cert-manager-79685bfc47-xjfqm/cert-manager-controller
datadog/datadog-cluster-agent/datadog-cluster-agent-6d877bc549-h69gb/cluster-agent
datadog/datadog-cluster-agent/datadog-cluster-agent-6d877bc549-lkjps/cluster-agent
datadog/datadog-cluster-agent/datadog-cluster-agent-6d877bc549-tkpql/cluster-agent
datadog/datadog/datadog-7qxmh/agent
datadog/datadog/datadog-7qxmh/process-agent
datadog/datadog/datadog-7qxmh/trace-agent
datadog/datadog/datadog-8kvm2/agent
datadog/datadog/datadog-8kvm2/process-agent
datadog/datadog/datadog-8kvm2/trace-agent
datadog/datadog/datadog-c9gbj/agent
datadog/datadog/datadog-c9gbj/process-agent
datadog/datadog/datadog-c9gbj/trace-agent
datadog/datadog/datadog-gm97m/agent
datadog/datadog/datadog-gm97m/process-agent
datadog/datadog/datadog-gm97m/trace-agent
datadog/datadog/datadog-jgk6f/agent
datadog/datadog/datadog-jgk6f/process-agent
datadog/datadog/datadog-jgk6f/trace-agent
datadog/datadog/datadog-pmrnq/agent
datadog/datadog/datadog-pmrnq/process-agent
datadog/datadog/datadog-pmrnq/trace-agent
datadog/datadog/datadog-sn4cv/agent
datadog/datadog/datadog-sn4cv/process-agent
datadog/datadog/datadog-sn4cv/trace-agent
datadog/datadog/datadog-tgz7r/agent
datadog/datadog/datadog-tgz7r/process-agent
datadog/datadog/datadog-tgz7r/trace-agent
datadog/datadog/datadog-ttf9n/agent
datadog/datadog/datadog-ttf9n/process-agent
datadog/datadog/datadog-ttf9n/trace-agent
datadog/datadog/datadog-vklvf/agent
datadog/datadog/datadog-vklvf/process-agent
datadog/datadog/datadog-vklvf/trace-agent
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-d7g9j/dummy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-d7g9j/istio-proxy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-d7g9j/pause
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-k764p/dummy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-k764p/istio-proxy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-k764p/pause
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-kvwkb/dummy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-kvwkb/istio-proxy
dummy-service-us/dummy-service-us/dummy-service-us-6cbc8c94c6-kvwkb/pause
external-secrets/external-secrets-cert-controller/external-secrets-cert-controller-764655985-cbj22/cert-controller
external-secrets/external-secrets-cert-controller/external-secrets-cert-controller-764655985-rp2s2/cert-controller
external-secrets/external-secrets-cert-controller/external-secrets-cert-controller-764655985-vtw2h/cert-controller
external-secrets/external-secrets-webhook/external-secrets-webhook-78f6745764-kxp9d/webhook
external-secrets/external-secrets-webhook/external-secrets-webhook-78f6745764-nwbl8/webhook
external-secrets/external-secrets-webhook/external-secrets-webhook-78f6745764-ttbfh/webhook
external-secrets/external-secrets/external-secrets-566d54c5d9-9svvg/external-secrets
external-secrets/external-secrets/external-secrets-566d54c5d9-hzjfp/external-secrets
external-secrets/external-secrets/external-secrets-566d54c5d9-zbgcs/external-secrets
istio-system/istiod/istiod-646b5b7489-9tdnw/discovery
istio-system/istiod/istiod-646b5b7489-p9rdg/discovery
istio-system/istiod/istiod-646b5b7489-qqjjm/discovery
karpenter/karpenter/karpenter-675cbc6fcf-2k2gd/controller
karpenter/karpenter/karpenter-675cbc6fcf-2k2gd/datadog-agent
karpenter/karpenter/karpenter-675cbc6fcf-k2xbp/controller
karpenter/karpenter/karpenter-675cbc6fcf-k2xbp/datadog-agent
lacework/lacework-agent/lacework-agent-2f2fz/lacework
lacework/lacework-agent/lacework-agent-6jxb5/lacework
lacework/lacework-agent/lacework-agent-85z6x/lacework
lacework/lacework-agent/lacework-agent-94gcv/lacework
lacework/lacework-agent/lacework-agent-9w5fh/lacework
lacework/lacework-agent/lacework-agent-cxhbs/lacework
lacework/lacework-agent/lacework-agent-mzkd9/lacework
lacework/lacework-agent/lacework-agent-n5xwf/lacework
lacework/lacework-agent/lacework-agent-njwvv/lacework
lacework/lacework-agent/lacework-agent-xcc9v/lacework
verification-service/verification-service/verification-service-649bd75468-29zlw/istio-proxy
verification-service/verification-service/verification-service-649bd75468-29zlw/pause

Fetching Istio control plane information from cluster.

Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Error [IST0101] (AuthorizationPolicy dummy-service-us/allow-cross-cluster-access) Referenced namespace not found: "dummy-service-eu"
Error [IST0101] (AuthorizationPolicy dummy-service-us/allow-cross-cluster-access) Referenced namespace not found: "gitlab-runner"
Info [IST0102] (Namespace aws-load-balancer-controller) The namespace is not enabled for Istio injection. Run 'kubectl label namespace aws-load-balancer-controller istio-injection=enabled' to enable it, or 'kubectl label namespace aws-load-balancer-controller istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace datadog) The namespace is not enabled for Istio injection. Run 'kubectl label namespace datadog istio-injection=enabled' to enable it, or 'kubectl label namespace datadog istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace external-secrets) The namespace is not enabled for Istio injection. Run 'kubectl label namespace external-secrets istio-injection=enabled' to enable it, or 'kubectl label namespace external-secrets istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace gitlab-managed-apps) The namespace is not enabled for Istio injection. Run 'kubectl label namespace gitlab-managed-apps istio-injection=enabled' to enable it, or 'kubectl label namespace gitlab-managed-apps istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace karpenter) The namespace is not enabled for Istio injection. Run 'kubectl label namespace karpenter istio-injection=enabled' to enable it, or 'kubectl label namespace karpenter istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace lacework) The namespace is not enabled for Istio injection. Run 'kubectl label namespace lacework istio-injection=enabled' to enable it, or 'kubectl label namespace lacework istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace platform) The namespace is not enabled for Istio injection. Run 'kubectl label namespace platform istio-injection=enabled' to enable it, or 'kubectl label namespace platform istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service aws-load-balancer-controller/aws-load-balancer-webhook-service) Port name webhook-server (port: 443, targetPort: webhook-server) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service datadog/datadog-cluster-agent-admission-controller) Port name datadog-webhook (port: 443, targetPort: 8000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service datadog/datadog-cluster-agent-metrics-api) Port name metricsapi (port: 8443, targetPort: 8443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service datadog/datadog-cluster-agent) Port name agentport (port: 5005, targetPort: 5005) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service datadog/datadog) Port name traceport (port: 8126, targetPort: 8126) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service external-secrets/external-secrets-cert-controller-metrics) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service external-secrets/external-secrets-metrics) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service external-secrets/external-secrets-webhook) Port name metrics (port: 8080, targetPort: 8080) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service external-secrets/external-secrets-webhook) Port name webhook (port: 443, targetPort: 10250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service karpenter/karpenter) Port name webhook-metrics (port: 8001, targetPort: webhook-metrics) doesn't follow the naming convention of Istio port.
Info [IST0135] (Pod datadog/datadog-7qxmh) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-8kvm2) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-c9gbj) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-cluster-agent-6d877bc549-h69gb) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-cluster-agent-6d877bc549-lkjps) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-cluster-agent-6d877bc549-tkpql) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-gm97m) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-jgk6f) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-pmrnq) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-sn4cv) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-tgz7r) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-ttf9n) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Info [IST0135] (Pod datadog/datadog-vklvf) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
Creating an archive at /Users/florianstadler/development/istio-cross-region/bug-report.tar.gz.
Time used for creating the tar file is 160.638541ms.
Cleaning up temporary files in /var/folders/dp/n_12t43s70s2ccn9jmylb11r0000gq/T/bug-report.
Done.

**Comment by flostadler** [comment]
When checking the listeners on the calling deployment (called `verification-service`), I noticed that it also doesn't have listeners for the target (called `dummy-service-us`):

```
istioctl pc listener -n verification-service deployment/verification-service

ADDRESSES      PORT  MATCH                                                                                           DESTINATION
10.100.0.10    53    ALL                                                                                             Cluster: outbound|53||kube-dns.kube-system.svc.cluster.local
10.100.0.1     443   ALL                                                                                             Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.100.103.111 443   ALL                                                                                             Cluster: outbound|443||istiod.istio-system.svc.cluster.local
10.100.162.137 443   Trans: raw_buffer; App: http/1.1,h2c                                                            Route: datadog-cluster-agent-admission-controller.datadog.svc.cluster.local:443
10.100.162.137 443   ALL                                                                                             Cluster: outbound|443||datadog-cluster-agent-admission-controller.datadog.svc.cluster.local
10.100.201.9   443   Trans: raw_buffer; App: http/1.1,h2c                                                            Route: external-secrets-webhook.external-secrets.svc.cluster.local:443
10.100.201.9   443   ALL                                                                                             Cluster: outbound|443||external-secrets-webhook.external-secrets.svc.cluster.local
10.100.239.79  443   ALL                                                                                             Cluster: outbound|443||cert-manager-webhook.cert-manager.svc.cluster.local
10.100.43.19   443   Trans: raw_buffer; App: http/1.1,h2c                                                            Route: aws-load-balancer-webhook-service.aws-load-balancer-controller.svc.cluster.local:443
10.100.43.19   443   ALL                                                                                             Cluster: outbound|443||aws-load-balancer-webhook-service.aws-load-balancer-controller.svc.cluster.local
10.100.201.104 5005  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: datadog-cluster-agent.datadog.svc.cluster.local:5005
10.100.201.104 5005  ALL                                                                                             Cluster: outbound|5005||datadog-cluster-agent.datadog.svc.cluster.local
0.0.0.0        8000  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 8000
0.0.0.0        8000  ALL                                                                                             PassthroughCluster
10.100.33.72   8001  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: karpenter.karpenter.svc.cluster.local:8001
10.100.33.72   8001  ALL                                                                                             Cluster: outbound|8001||karpenter.karpenter.svc.cluster.local
0.0.0.0        8080  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 8080
0.0.0.0        8080  ALL                                                                                             PassthroughCluster
10.100.156.61  8080  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: external-secrets-metrics.external-secrets.svc.cluster.local:8080
10.100.156.61  8080  ALL                                                                                             Cluster: outbound|8080||external-secrets-metrics.external-secrets.svc.cluster.local
10.100.201.9   8080  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: external-secrets-webhook.external-secrets.svc.cluster.local:8080
10.100.201.9   8080  ALL                                                                                             Cluster: outbound|8080||external-secrets-webhook.external-secrets.svc.cluster.local
10.100.85.143  8080  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: external-secrets-cert-controller-metrics.external-secrets.svc.cluster.local:8080
10.100.85.143  8080  ALL                                                                                             Cluster: outbound|8080||external-secrets-cert-controller-metrics.external-secrets.svc.cluster.local
10.100.64.186  8126  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: datadog.datadog.svc.cluster.local:8126
10.100.64.186  8126  ALL                                                                                             Cluster: outbound|8126||datadog.datadog.svc.cluster.local
10.100.18.139  8443  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: datadog-cluster-agent-metrics-api.datadog.svc.cluster.local:8443
10.100.18.139  8443  ALL                                                                                             Cluster: outbound|8443||datadog-cluster-agent-metrics-api.datadog.svc.cluster.local
10.100.33.72   8443  ALL                                                                                             Cluster: outbound|8443||karpenter.karpenter.svc.cluster.local
10.100.0.10    9153  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: kube-dns.kube-system.svc.cluster.local:9153
10.100.0.10    9153  ALL                                                                                             Cluster: outbound|9153||kube-dns.kube-system.svc.cluster.local
10.100.59.131  9402  ALL                                                                                             Cluster: outbound|9402||cert-manager.cert-manager.svc.cluster.local
0.0.0.0        15001 ALL                                                                                             PassthroughCluster
0.0.0.0        15001 Addr: *:15001                                                                                   Non-HTTP/Non-TCP
0.0.0.0        15006 Addr: *:15006                                                                                   Non-HTTP/Non-TCP
0.0.0.0        15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: 0.0.0.0/0                        InboundPassthroughClusterIpv4
0.0.0.0        15006 Trans: raw_buffer; App: http/1.1,h2c; Addr: 0.0.0.0/0                                           InboundPassthroughClusterIpv4
0.0.0.0        15006 Trans: tls; App: TCP TLS; Addr: 0.0.0.0/0                                                       InboundPassthroughClusterIpv4
0.0.0.0        15006 Trans: raw_buffer; Addr: 0.0.0.0/0                                                              InboundPassthroughClusterIpv4
0.0.0.0        15006 Trans: tls; Addr: 0.0.0.0/0                                                                     InboundPassthroughClusterIpv4
0.0.0.0        15006 Trans: tls; App: istio,istio-peer-exchange,istio-http/1.0,istio-http/1.1,istio-h2; Addr: *:8080 Cluster: inbound|8080||
0.0.0.0        15006 Trans: raw_buffer; Addr: *:8080                                                                 Cluster: inbound|8080||
0.0.0.0        15010 Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 15010
0.0.0.0        15010 ALL                                                                                             PassthroughCluster
10.100.103.111 15012 ALL                                                                                             Cluster: outbound|15012||istiod.istio-system.svc.cluster.local
0.0.0.0        15014 Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 15014
0.0.0.0        15014 ALL                                                                                             PassthroughCluster
0.0.0.0        15021 ALL                                                                                             Inline Route: /healthz/ready*
0.0.0.0        15090 ALL                                                                                             Inline Route: /stats/prometheus*
```

**Comment by flostadler** [comment]
This seems to have to do with explicit protocol selection. The port was called http previously, after changing it to something random it starts working and the listeners show up.

Why is this happening?

**Comment by flostadler** [comment]
But would that lead to the listeners disappearing? That's what I'm not fully sure about. The DNS continues resolving to the old IPs whereas the listeners disappear altogether

**Comment by hzxuzhonghu** [comment]
Port of http protocol behaves differently with tcp for headless services, that is we donot generate per pod listener for HTTP. 

>But would that lead to the listeners disappearing? 

So i am not sure what you mean by disappearing.
