### ISSUE TITLE
if possible to route all external outbound traffic to egress gateway or someone cluster

### ISSUE THREAD

**Issue by motocoder-cn** [istio/istio#49774]
some external call A workload, then A workload call back to some external service

do not know external service ip , just know url path

possible to route all outbound traffic match url path to any address to egress gateway?

**Comment by zengyuxing007** [comment]
> some external call A workload, then A workload call back to some external service
> 
> do not know external service ip , just know url path
> 
> possible to route all outbound traffic match url path to any address to egress gateway?

Please ref to this doc: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/

**Comment by motocoder-cn** [comment]
@zengyuxing007 in this doc to use egress gateway need create serviceentry,but serviceentry need set host/address , but in my case I do not know external service address, so I just want route any address to egress gateway,actually serviceentry host can not set as "*"

**Comment by zengyuxing007** [comment]
> @zengyuxing007 in this doc to use egress gateway need create serviceentry,but serviceentry need set host/address , but in my case I do not know external service address, so I just want route any address to egress gateway,actually serviceentry host can not set as "*"

So what do you need egress gateway to do for you? If the request doesn't go through the egress gateway, does it not go through?

The purpose of the istio egress gateway may be to help you add some access control or load balancing, but you need to specify which services you want to access by egress gateway.

**Comment by zirain** [comment]
are you looking for https://istio.io/latest/docs/tasks/traffic-management/mirroring/?

**Comment by motocoder-cn** [comment]
@zirain i need mirror traffic which to "any/all" external service with specific url path,but in doc is mirror traffic which to some specific workload

**Comment by anhnt094** [comment]
Hi @motocoder-cn , have you found the solution yet? 
I also have a use case like in the document, which is "all traffic leaving the service mesh must flow through a set of dedicated nodes. These nodes will run on dedicated machines, separated from the rest of the nodes running applications in the cluster "
