### ISSUE TITLE
Use common domain type virtualservice to config the route rule for all domains

### ISSUE THREAD

**Issue by haifzhu** [istio/istio#49788]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
In fact, business user config route rule for service and no caring about which domain for it. 
So they want config the route rule for all domains with common domain type virtualservice.

**Describe alternatives you've considered**
Use common domain type virtualservice to config the route rule for all domains

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
no

**Comment by hzxuzhonghu** [comment]
Can you elaborate more

**Comment by haifzhu** [comment]
> Can you elaborate more

In our business, we define one vs for service a and another vs for service b, if we define one vs for service c for all domains, we should list all domains in vs for c。
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: a
spec:
  gateways:
  - zcy-gateway
  hosts:
  - a.com
  http:
  - match:
    - uri:
        prefix: /a
    route:
    - destination:
        host: A
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: b
spec:
  gateways:
  - zcy-gateway
  hosts:
  - b.com
  http:
  - match:
    - uri:
        prefix: /b
    route:
    - destination:
        host: B
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: c
spec:
  gateways:
  - zcy-gateway
  hosts:
 - a.com
 - b.com
  - *.com
  http:
  - match:
    - uri:
        prefix: /c
    route:
    - destination:
        host: C
        port:
          number: 8080

if we add another domain, we should also update vs c for all domains.

Can we create one common vs for this scene?

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: c
spec:
  gateways:
  - zcy-gateway
  hosts:
  - *
  http:
  - match:
    - uri:
        prefix: /c
    route:
    - destination:
        host: C
        port:
          number: 8080

then service C provide the api for all domains。

**Comment by haifzhu** [comment]
now * mean the domains no matched other domains, not for all domains。

**Comment by haifzhu** [comment]
> I think we do support specify * for VS hosts

不知道我解释清楚了么？在envoy里面是针对每个vhost的，如果要配置某些路由针对所有域名，就需要显示的把域名列出来，会增加维护成本，是否能提供一个对所有域名都生效类型的virtualservice，在每个vhost都应用这些路由规则。

**Comment by zengyuxing007** [comment]
> > I think we do support specify * for VS hosts
> 
> 不知道我解释清楚了么？在envoy里面是针对每个vhost的，如果要配置某些路由针对所有域名，就需要显示的把域名列出来，会增加维护成本，是否能提供一个对所有域名都生效类型的virtualservice，在每个vhost都应用这些路由规则。

Within Envoy, there is priority matching for virtual hosts, and I believe the current approach is reasonable.

A more precise semantic expression may be required to encompass your needs, rather than a simple asterisk '*'.


```yaml
- vhost:
     - a.com
     - b.com
    route_config:
      match:  /index1
      match: /index2 
-  vhost:
     - *
    route_config:
      match: /index3
```

VS:

```yaml
- vhost:
     - a.com
     - b.com
    route_config:
      match:  /index1
      match: /index2 
      match: /index3
-  vhost:
     - *
    route_config:
      match: /index3
```

**Comment by haifzhu** [comment]
> > > I think we do support specify * for VS hosts
> > 
> > 
> > 不知道我解释清楚了么？在envoy里面是针对每个vhost的，如果要配置某些路由针对所有域名，就需要显示的把域名列出来，会增加维护成本，是否能提供一个对所有域名都生效类型的virtualservice，在每个vhost都应用这些路由规则。
> 
> Within Envoy, there is priority matching for virtual hosts, and I believe the current approach is reasonable.
> 
> A more precise semantic expression may be required to encompass your needs, rather than a simple asterisk '*'.
> 
> ```yaml
> - vhost:
>      - a.com
>      - b.com
>     route_config:
>       match:  /index1
>       match: /index2 
> -  vhost:
>      - *
>     route_config:
>       match: /index3
> ```
> 
> VS:
> 
> ```yaml
> - vhost:
>      - a.com
>      - b.com
>     route_config:
>       match:  /index1
>       match: /index2 
>       match: /index3
> -  vhost:
>      - *
>     route_config:
>       match: /index3
> ```

你这样做没有问题, 从网关的角度上是以域名为维度进行生效的，不过微服务架构下，我们想以应用为中心管理vs规则。现在一个应用对所有域名都暴露接口，就需要整理出所有的域名并配置上。在一个微服务的系统中，应用有200个左右，子域名200个左右，如果有50个应用是针对所有域名的，就需要在这50个应用的vs中添加上所有域名，如果新增一个域名，就需要在50个vs里面都记得添加下。我的诉求是不是可以有一个特殊的vs规则，比如不写hosts字段，这个vs就代表面向所有域名的，最终在envoy里面生效成针对所有vhosts。

**Comment by haifzhu** [comment]
> > > I think we do support specify * for VS hosts
> > 
> > 
> > 不知道我解释清楚了么？在envoy里面是针对每个vhost的，如果要配置某些路由针对所有域名，就需要显示的把域名列出来，会增加维护成本，是否能提供一个对所有域名都生效类型的virtualservice，在每个vhost都应用这些路由规则。
> 
> Within Envoy, there is priority matching for virtual hosts, and I believe the current approach is reasonable.
> 
> A more precise semantic expression may be required to encompass your needs, rather than a simple asterisk '*'.
> 
> ```yaml
> - vhost:
>      - a.com
>      - b.com
>     route_config:
>       match:  /index1
>       match: /index2 
> -  vhost:
>      - *
>     route_config:
>       match: /index3
> ```
> 
> VS:
> 
> ```yaml
> - vhost:
>      - a.com
>      - b.com
>     route_config:
>       match:  /index1
>       match: /index2 
>       match: /index3
> -  vhost:
>      - *
>     route_config:
>       match: /index3
> ```

你这样做没有问题, 从网关的角度上是以域名为维度进行生效的，不过微服务架构下，我们想以应用为中心管理vs规则。现在一个应用对所有域名都暴露接口，就需要整理出所有的域名并配置上。在一个微服务的系统中，应用有200个左右，子域名200个左右，如果有50个应用是针对所有域名的，就需要在这50个应用的vs中添加上所有域名，如果新增一个域名，就需要在50个vs里面都记得添加下。我的诉求是不是可以有一个特殊的vs规则，比如不写hosts字段，这个vs就代表面向所有域名的，最终在envoy里面生效成针对所有vhosts。

**Comment by haifzhu** [comment]
- vhost:  // for service A
     - a.com
     - b.com
    route_config:
      match:  /index1
      match: /index2 
-  vhost:  //  for service B
     - *
    route_config:
      match: /index3
....
-  vhost:  //  for service N
     - *
    route_config:
      match: /indexN

**Comment by haifzhu** [comment]
`- vhost: // for service A
     - a.com
     - b.com
    route_config:
      match:  /index1
      match: /index2 
-  vhost:  // for service C
     - * (all domains)
    route_config:
      match: /index3
...
-  vhost:  // for service N
     - * (all domains)
    route_config:
      match: /indexN
`
VS
`
- vhost: // for service A
     - a.com
     - b.com
    route_config:
      match:  /index1
      match: /index2 
      match: /index3
      .......
      match: /indexN
-  vhost:  // for domain C
     - c.com
    route_config:
      match: /index3
      .......
      match: /indexN
......
-  vhost:  // for domain N
     - n.com
    route_config:
      match: /index3
      .......
      match: /indexN
`
第一种比第二种配置上相对简单些

**Comment by haifzhu** [comment]
~~~
- vhost: // for service A
  - a.com
  - b.com
  route_config:
    match: /index1
    match: /index2
- vhost: // for service C
  - * (all domains)
  route_config:
    match: /index3
......
- vhost: // for service N
  - * (all domains)
  route_config:
    match: /indexN
~~~

VS

~~~
- vhost: // for service A
  - a.com
  - b.com
  route_config:
    match: /index1
    match: /index2
    match: /index3
    .......
    match: /indexN
- vhost: // for domain C
  - c.com
  route_config:
    match: /index3
    .......
    match: /indexN
......
- vhost: // for domain N
  - n.com
  route_config:
    match: /index3
    .......
    match: /indexN
~~~

第一种比第二种配置上简单许多

**Comment by howardjohn** [comment]
These higher level orchestrations over routing configuration are not likely to be added into VirtualService directly but can be handled by templating like Helm, etc
