### ISSUE TITLE
Pilot-agent can create invalid WorkloadEntry names

### ISSUE THREAD

**Issue by dwj300** [istio/istio#49797]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We use `hostname -i` to set INSTANCE_IP when using autoregistration, but in https://github.com/istio/istio/pull/41398/files#diff-dabdcee4f2cb1e46524eec507c7baa18ca1942feee3373ecbcd3428a1dc9dbc3R270, `net.ParseIP` was replaced with `net.ParseAddr()`. When called with a dualstack IP, this can result in a space between the IPv6 and IPv6 address, which results in autoregistration failures as the `name` cannot contain a space. Specifically this error: https://sourcegraph.com/github.com/kubernetes/kubernetes@364ef335dbd49bfa3d66dbc606c642481d283851/-/blob/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go?L178. Pilot-agent should prevent creating invalid WLE names.

```
$ hostname -i
aa80::824:66aa:aa0f:2420%eth0 1.1.1.1
```

### Version

```Text
Istio 1.17.4
```

**Comment by hzxuzhonghu** [comment]
Firstly workload is ot created by pilot-agent. 

> When called with a dualstack IP, this can result in a space between the IPv6 and IPv6 address,

What does this look like

**Comment by dwj300** [comment]
> Firstly workload is ot created by pilot-agent.
> 
> > When called with a dualstack IP, this can result in a space between the IPv6 and IPv6 address,
> 
> What does this look like

Updated in the description

**Comment by hzxuzhonghu** [comment]
aa80::824:66aa:aa0f:2420%eth0 1.1.1.is two ips,but `INSTANCE_IP` represents only one ip

**Comment by keithmattix** [comment]
Haven't repro'd but we should probably look into this

**Comment by dwj300** [comment]
(not stale)
