### ISSUE TITLE
TestBadWasmRemoteLoad test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49793]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49791/integ-telemetry-discovery_istio/1765761748071092224
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49615/integ-telemetry_istio/1765730238731390976

**Comment by zirain** [comment]
cc @ingwonsong

**Comment by howardjohn** [comment]
maybe from delta xds
