### ISSUE TITLE
Enable vtprotobuf

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49790]
Blockers:
* https://github.com/planetscale/vtprotobuf/pull/133
* https://github.com/planetscale/vtprotobuf/pull/130

**Comment by sschepens** [comment]
@howardjohn why do we need stable marshalling? is it for tests? I think Envoy currently supports dealing with reodered maps since https://github.com/envoyproxy/envoy/pull/30761

**Comment by howardjohn** [comment]
Ooh nice. Didn't know about that maybe we don't need it. maybe we don't
even need "strict" either then?

In the past (like 5 years ago) we had an issue around this and it was
pretty subtle and didn't break tests but had issues in real world so I
figured it still mattered.

**Comment by sschepens** [comment]
FWIW `java-control-plane` does non-deterministic serialization (the default) and we've been using that internally for years without issues.

**Comment by sschepens** [comment]
might be interesting to check if we really need Deterministic behaviour, maybe write some tests to see if envoy does what we think it does.

**Comment by sschepens** [comment]
seems like since 2019 https://github.com/envoyproxy/envoy/pull/8231 envoy's been hashing deterministically even Any fields

**Comment by howardjohn** [comment]
One more blocker I think: https://github.com/planetscale/vtprotobuf/pull/137
