### ISSUE TITLE
Should ztunnel forward tcp traffic to waypoint?

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#49799]
**Describe the feature request**

In  Ambient mode, consider this example scenario:

Both sleep and tcp-echo are deployed in  default namespace,  which is labeled ambient, and a default waypoint is deployed. 
> The sleep and tcp-echo pods are dispatched to different nodes.

Use this command to deploy a namespace-level waypoint in the default namespace.
```shell
istioctl x waypoint apply --service-account
```

If we send request to tcp-echo from a sleep pod, the request will be forwarded to the waypoint regardless of whether the request destination is the tcp-echo clusterIP, podIp, or tcp-echo serviceName.

The traffic path is as follows：

[ sleep -> ztunnel ] -> waypoint -> [ ztunnel -> tcp-echo ] 

This shouldn't make much sense, since the sleep request tcp-echo is a simple tcp request, not an L7 request (http / gRPC or others L7 protocols).

I think the ztunnel (L4) should be able to recognize the protocol of the target port and decide whether to forward the request to the waypoint.

btw, we can borrow some of [the service port specifications](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection) we already have in sidecar to accomplish this.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Waypoint is not intended to do L4 proxying now. Of you want L4 proxy, why not ztunnel-> ztunnel suite

**Comment by zengyuxing007** [comment]
> Waypoint is not intended to do L4 proxying now. Of you want L4 proxy, why not ztunnel-> ztunnel suite

@hzxuzhonghu 

Since the namespace level waypoint is configured , the existing implementations of ztunnel  will forward L4 requests （such as tcp echo ) to waypoint.  

I don't think it makes sense.  This is a bug if our design shouldn't forward L4 requests to waypoint.

The question can be raised as to whether ztunnel should forward L4 requests to waypoints, assuming that the user has configured a waypoint for a specific service such as tcp-echo. This is a useless process, though.

**Comment by hzxuzhonghu** [comment]
AH i missed that. It is unexpected to redirect TCP traffic to waypoint

**Comment by ilrudie** [comment]
I'm working right now on better waypoint capture. You'll be able to have a ns-scope waypoint but annotate svc/wl to opt out of waypoint. It's not based on tcp vs http though.

**Comment by howardjohn** [comment]
I disagree that waypoints should not ever do TCP. Of course, HTTP is the primary value add and most important delta in functionality between ztunnel and waypoints. But not the only one. Waypoint can do all sorts of things like:
* "Upgrade" to an L7 protocol (kafka, mysql, etc)
* WASM, ext_authz, ...
* Simply moving policy application from client side to producer side

**Comment by hzxuzhonghu** [comment]
There is use case they donot need such advanced feature, just pure TCP proxying, and for this, we should not redirect traffic to waypoint

**Comment by zengyuxing007** [comment]
> There is use case they donot need such advanced feature, just pure TCP proxying, and for this, we should not redirect traffic to waypoint


![image](https://github.com/istio/istio/assets/370590/c6794fe5-9196-48f4-b624-4f8c9ff2003b)

That's what I meant, if the service is explicitly declared as tcp, and not some other specific protocol (http、gRPC、kafka、mysql, etc) , then ztunnel shouldn't be forwarded to waypoint.

**Comment by ilrudie** [comment]
We're working on a new waypoint capture mechanism that would let you opt out a svc or workload from waypoint explicitly even if you have a waypoint declared for the entire namespace.

https://github.com/istio/istio/issues/49436

**Comment by zengyuxing007** [comment]
> We're working on a new waypoint capture mechanism that would let you opt out a svc or workload from waypoint explicitly even if you have a waypoint declared for the entire namespace.
> 
> #49436

@ilrudie 

Suggestion: Consider having a global configuration that uses the Service port name as a basis for making decisions. Specifically, if a port is explicitly declared to use the TCP protocol, as opposed to HTTP or other well-known protocols (such as MySQL, Kafka, etc.), then the traffic should not be forwarded to the waypoint.
