### ISSUE TITLE
Leadership election is arbitrary between revisions unless tags are used.

### ISSUE THREAD

**Issue by birkland** [istio/istio#49808]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Tags are documented as an opt-in feature to simplify managing revisions.  The [documentation for tags](https://istio.io/latest/docs/setup/upgrade/canary/#stable-revision-labels) states that the default tag
> Steals the leader lock from non-default revisions and performs singleton mesh responsibilities (such as updating resource statuses)

It appears that if one uses revisions, but _not_ tags, then leadership election is completely arbitrary, i.e. any revision can win and retain leader status. 

Since the creating a `default` tag merely results in the creation of a webhook, I tested with
```
helm template istiod istio/istiod -s templates/revision-tags.yaml --set revisionTags="{default}" --set revision=v1 -n istio-system | kubectl apply -f
```

Once the webhook from the above was created, revision `v1` appeared to consistently stole the leadership election.  When I removed the webhook, it appeared that other revisions could win and retain election.

 Are there any consequences to this (e.g. if revisions are from different versions of Istio, or different config/features)?  
 
 At the very least, perhaps the docs should mention that usage of tags is required for deterministic leadership behavior.

### Version

```Text
Tested with 1.19.5
```

### Additional Information

Who won leadership election was determined by looking at the `Istio-leader` configmap.  When the `default` revision ag webhook was present, I observed that if a `v2` pod won election, then it would momentarily be replaced with a `v1` pod.  Without the webhook, a `v2` pod could win election, and stay there.

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"istiod-v2-8b8b4db9d-j478m","holderKey":"v2","leaseDurationSeconds":30,"acquireTime":"2024-03-07T22:32:05Z","renewTime":"2024-03-07T22:32:05Z","leaderTransitions":1}'
  creationTimestamp: "2024-03-07T22:11:55Z"
  name: istio-leader
  namespace: istio-system
  resourceVersion: "5591"
  uid: 52a71dda-b7ae-4dd6-9401-b0a9f8064a17
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"istiod-v1-6c7cb8868f-c4x5v","holderKey":"v1","leaseDurationSeconds":30,"acquireTime":"2024-03-07T22:11:55Z","renewTime":"2024-03-07T22:31:41Z","leaderTransitions":0}'
  creationTimestamp: "2024-03-07T22:11:55Z"
  name: istio-leader
  namespace: istio-system
  resourceVersion: "5425"
  uid: 52a71dda-b7ae-4dd6-9401-b0a9f8064a17
```

**Comment by linsun** [comment]
My understanding is that leadership election could be disabled if there is only 1 node.  Leader does a few tasks such as update status of resources, namespace controller (create configmaps for ns).  Assuming there are no resource status API changes among revisions and assuming all revisions are using the same root cert, the impact of this may be none?

cc @hzxuzhonghu and @howardjohn for their input.

**Comment by keithmattix** [comment]
This is as expected; when installing a new revision (via istioctl or helm) you can optionally set it as the "default" revision. That prevents the flip-flopping

**Comment by linsun** [comment]
Thanks @keithmattix - yep just wanted to make sure there is no negative impact with this behavior when multiple revisions co-exist.  Or should we always recommend users to set the "default" revision, which to my understanding is optional atm?

**Comment by birkland** [comment]
.. and if there is no  negative impact from flip-flopping leadership between revisions, then there is no value to pinning leader to the default revision?

**Comment by keithmattix** [comment]
My understanding is that users should ALWAYS set a default revision. Because without one, config without a revisioned label could be ignored or have its behavior change during a canary upgrade (e.g a VirtualService with no revision label could either be ignored or have its semantics change during a canary upgrade). This has come up in slack several times

**Comment by birkland** [comment]
The [canary upgrade doc](https://istio.io/latest/docs/setup/upgrade/canary/#default-tag) is definitely not clear on that case, then.  It shows the steps for a canary upgrade without tags involved.  Then mentions tags in the context of "rather than go through all that, you can just use tags", then later as an aside "the default tag has special semantics".  Nowhere does it actually recommend or encourage using It, or warn against not using a default tag.  

Regardless, I'm sill interested in knowing if there are consequences to flip-flopping leaders across revisions.  i.e if someone is OK with revision labels, diligently uses and updates them everywhere and otherwise has no reason to use tags (and is happy), is there a downside to flip-flopping that would be remedied by a default tag anyway?

**Comment by howardjohn** [comment]
I am fairly sure validation does not work without a default revision set.

Flip flopping across revisions can give negative impacts if they have different behavior across versions; not common but possible.

**Comment by linsun** [comment]
Validation webhook does seem to handle per revision?  https://github.com/istio/istio/blob/89c548304627c7a2bed1216ce2b180560a8d5a67/manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml#L12

I recall we introduced multiple revisions first then default revision to simplify the UX so i didn't realize default revision is required, till the discussion here.  I do agree that we should recommend users to have default revision to avoid rare scenarios of different behavior across revisions.

**Comment by keithmattix** [comment]
But each validating webhook only handles its own revision. So a 1-20 revisioned VHC won't validate a resource without a istio.io/rev label set to 1-20.
