### ISSUE TITLE
istio cannot rout traffic to ingress resources with virtualhost  

### ISSUE THREAD

**Issue by colltie** [istio/istio#4980]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-0-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: ingress.customer1.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-0-service
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-1-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: ingress.customer2.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-1-service
          servicePort: 80

I have been trying to get this work with any luck

**Comment by andraxylia** [comment]
Can you please try with release 0.8 and Gateway and re-open if you still encounter issues?
https://istio.io/docs/tasks/traffic-management/ingress/
