### ISSUE TITLE
Measure per hop latency 

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#4981]

**Comment by sakshigoel12** [comment]
@ldemailly please update this issue

**Comment by ldemailly** [comment]
the data is now published on
https://istio.io/docs/performance-and-scalability/synthetic-benchmarks/

**Comment by sakshigoel12** [comment]
@ldemailly the linked doc doesn't seem to have the per hop latency. Maybe I am missing something

**Comment by ldemailly** [comment]
s1->s2 and s2->s1 is per hop
