### ISSUE TITLE
`destination_service_namespace` becomes `unknown` when service has no healthy backends

### ISSUE THREAD

**Issue by diranged** [istio/istio#49842]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We noticed that the metrics from `reporter=source` for requests have  `destination_service_namespace=foobar`  become `destination_service_namespace=unknown`  during an outage of the target service where the target workload pods are gone. This caused some of our alarms that report on 5xx responses (as returned from the client workkloads) to not fire off because the label selector for `destination_service_namespace=foobar` no longer matched any metrics.

### Version

```Text
Istio 1.20.3
```

### Additional Information

_Slack Thread_: https://istio.slack.com/archives/C37A4KAAD/p1709769357941709 (no responses though)

**Comment by diranged** [comment]
Image from our metrics ...  the light-blue is where the namespace becomes `unknown`:

![image](https://github.com/istio/istio/assets/768067/7e0ca090-806c-4dda-baae-60c0a712c867)

**Comment by howardjohn** [comment]
`tags_.push_back({context_.destination_service_namespace_, context_.namespace_` and `tags_.push_back({context_.destination_workload_namespace_, context_.namespace_});`

So our code makes the assumption service namespace == workload namespace. Instead we should get the service namespace from the clsuter metadata (which is already there:
```
  metadata:
    filterMetadata:
      istio:
        services:
        - host: vm.echo.svc.cluster.local
          name: vm
          namespace: echo
```
)

**Comment by howardjohn** [comment]
cc @kyessenov @zirain looks like an easy fix if my assumption is correct that we should change it to the cluster metadata

**Comment by kyessenov** [comment]
I think the idea was to report namespace using SPIFFE only since it cannot be forged. Why did they use service namespace and not workload namespace?

**Comment by howardjohn** [comment]
For workload namespace that makes sense, but Service_namespace is a service property not a workload one so seems appropriate to use the service metadata?

**Comment by kyessenov** [comment]
@diranged is the idea behind using `destination_service_namespace` to monitor xDS configuration or data path itself?

**Comment by diranged** [comment]
> @diranged is the idea behind using `destination_service_namespace` to monitor xDS configuration or data path itself?

We're monitoring the request flow and responses - so looking for 5xx responses for example. We realized that when the service was down (no active hosts behind it due to a buggy release), we did not get a 5xx alarm because the alarm was tied to `destination_service=<svc>, destination_service_namespace=<ns>`. The metrics reported by `reporter=source` suddenly had the wrong `destination_service_namespace` in the metrics, which didn't match the alarm, and it did not fire off.

**Comment by diranged** [comment]
@kyessenov Any further houghtst here?

**Comment by howardjohn** [comment]
cc @keithmattix @whitneygriffith

**Comment by keithmattix** [comment]
Oh actually I bet the source is getting these from endpoint metadata and if there are no endpoints then we have no data. I wonder if we can add some of this info to cluster metadata and merge that with endpoint metadata as a fallback?

**Comment by howardjohn** [comment]
The info is already in cluster metadata, so we just need to do the fallback

**Comment by keithmattix** [comment]
Yeah +1 service metrics should come from cluster metadata

**Comment by keithmattix** [comment]
> The info is already in cluster metadata, so we just need to do the fallback

Sorry I deleted my other message because I didn't read the context. We're in agreement
