### ISSUE TITLE
Cannot see liveness probe and readiness probe logs in envoy proxy logs

### ISSUE THREAD

**Issue by manojtr** [istio/istio#49862]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello,
I have liveness and readiness probe setup for an application and it is deployed in a pod along with istio sidecar proxy container.  I don't see the above application probes logged in the envoy proxy container logs. I tried to enable the proxy log as debug and it is still not showing the application probes in the logs. However I have observed, whenever there is a timeout or 5xx errors of the probes I can see those in the proxy logs. 

I am trying to figure out why a restarting application container receives traffics while it is restarting. It should be already made unavailable and istio should not route traffic to it.    

### Version

```Text
$ istioctl version
client version: 1.19.1
control plane version: 1.15.2
data plane version: 1.15.2 (76 proxies)

$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.12-eks-5e0fdde
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Probes do not go through the standard proxy path so do not have access logs.

PS: Istio 1.15 is very eol, I would encourage you to upgrade

**Comment by manojtr** [comment]
@howardjohn thanks for the reply. 
Do you know why the errored ones are reported in the logs? Also, is there a way to log these probes? I know this is out of istio scope but appreciate your suggestion if you know it :)

Yes, we are in the process of upgrading to latest istio version. Upgrade is a slow process to get pass through the bureaucrats :D

**Comment by manojtr** [comment]
Ahh I see. So the istio check is different from the kubelet health checks which determine the restart of the pod after a certain number of failure.

**Comment by howardjohn** [comment]
Istio rewrites the pod probe check to go to the istio proxy, which then forwards it to the app

**Comment by manojtr** [comment]
Ahh then, is there a way to see that rewritten probes and responses in the istio proxy logs? At the moment I don't see that in the access logs but I assume there should be a way to print that in the logs because it is obviously going through proxy. By the way, thanks os much for looking into this. Really appreciated.

**Comment by howardjohn** [comment]
No, currently it only logs failures

**Comment by manojtr** [comment]
@howardjohn  thanks for confirming. Do you think I can lodge a feature request for this? I think logging the probes will be very useful in troubleshooting especially in the case of checking probe response times...etc

**Comment by omer-levy-scaleops** [comment]
Hey, I also agree with @manojtr, it would be very helpful to see the successful probes in order to find why others fail.

**Comment by zirain** [comment]
> Hey, I also agree with @manojtr, it would be very helpful to see the successful probes in order to find why others fail.

that would be a lot of noise.

**Comment by omer-levy-scaleops** [comment]
> > Hey, I also agree with @manojtr, it would be very helpful to see the successful probes in order to find why others fail.
> 
> that would be a lot of noise.

Couldn't it be controlled with logging level?

**Comment by howardjohn** [comment]
If someone wants to add debug logs on the probes I don't mind, please send a PR

**Comment by AnhQKatalon** [comment]
Hi, I also agree with @manojtr , I need this kind of successful probe log in the Istio proxy to determine. Because the log only shows failed health checks, so there may be many successful checks between the failed. I need to find the continuous failed checks to see if the restart matches with `failureThreshold` and `periodSeconds` or not.
