### ISSUE TITLE
Build survey for usage of `--set compatibilityVersion`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49885]
When a user runs `istioctl install --set compatibilityVersion` or `helm install --set compatibilityVersion`, we should display: "You set the compatibility version to <>. Please considering giving feedback on why at <link to survey>".

In the survey, we should have:

1. What Istio version are you installing
2. What compatibility version did you set
3. Why did you set it? (multi checkbox)
* I tried upgrading and ran into issues
* I want to avoid any changes, just in case
* I know I will be impacted by changes from the release notes
* I know I will be impacted by changes from `istioctl precheck`
4. (Optional) When do you plan to unset the `compatibilityVersion`

I think the survey will need to be set up by TOC or Steering (@therealmitchconnors can help point us in the right direction I am sure)

**Comment by howardjohn** [comment]
Still good to have

**Comment by ayushrakesh** [comment]
@howardjohn I am interested to work on this issue, can you please  explain a bit more about it, like how and where to implement survey , what it actually means.
