### ISSUE TITLE
response_flags: DC marked as an error

### ISSUE THREAD

**Issue by erickbitso** [istio/istio#49884]
We are using istio in our clusters, and we also use Datadog APM in our applications, and also integrated istio to ship traces to Datadog. We noticed that some requests have span tags response_flags:DC, response_size:0 and error: true. My understanding is that client disconnections are normal, for example an Android app calling one of our backend endpoints is killed by user or OS, thus the TCP connection is abruptly terminated. So I fail to understand why this is marked as an error. It affects our SLOs as I think there is nothing we can do to mitigate them. Is this correct?

## Context
Istio version: 1.18.2
tracing: datadog

## Problem
Span tags look like this
```
error: true
request_size: 0
response_flags: DC
response_size: 0
```

How can I prevent client (downstream) disconnections from being marked as an error?

**Comment by howardjohn** [comment]
This is about requests that started and did not complete. It seems hard to justify qualifying an incomplete request as "success"?

**Comment by nept** [comment]
Do we know if this will be configurable? Like having the option to set the error to false even if the DC flag is present.
I understand this change, that it's indeed not normal, but as it affects our monitoring I would like to know what your vision is on this.
Thanks!
