### ISSUE TITLE
XDS Proxy: support partially valid WASM rewrites

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#49887]
See https://github.com/envoyproxy/envoy/issues/32880

In https://github.com/istio/istio/blob/a2054917ffc6d84b5a3aab305bddc89c4d73cca3/pkg/istio-agent/xds_proxy.go#L547, we block the entire response. We should just block the invalid resources.

This needs a lot of caution and testing to make sure we don't mess up other semantics in the process

**Comment by kyessenov** [comment]
IMHO the effort is better spent on removing ECDS proxying and fixing Wasm runtime to fetch remotely.

**Comment by hzxuzhonghu** [comment]
Not conflict, both can improve the system stability
