### ISSUE TITLE
wasmplugin yaml with spec.type throws error unknown field type

### ISSUE THREAD

**Issue by PGpmg** [istio/istio#49901]
Error from server (BadRequest): error when creating "wasm-plugin.yaml": WasmPlugin in version "v1alpha1" cannot be handled as a WasmPlugin: strict decoding error: unknown field "spec.type"

By default, it takes HTTP plugin type. How to deploy wasmplugin for TCP network traffic?

I am using Istio 1.19.1 version and k8s 1.26.6

**Comment by hanxiaop** [comment]
It's available in Istio 1.20.0. See https://istio.io/latest/news/releases/1.20.x/announcing-1.20/#expanded-support-for-network-wasmplugin
