### ISSUE TITLE
Istio error：{"data":"upstream connect error or disconnect/reset before headers. reset reason: connection termination}

### ISSUE THREAD

**Issue by smallemployees** [istio/istio#49909]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

{"data":"upstream connect error or disconnect/reset before headers. reset reason: connection termination}

### Version

```Text
v1.21.0
```

**Comment by zirain** [comment]
please share more info, this more like a network issue.
