### ISSUE TITLE
EnvoyOpenTelemetryLogProvider should set TraceId and SpanId

### ISSUE THREAD

**Issue by chrkl** [istio/istio#49911]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

The OpenTelemetry [Log and Event Record Definition](https://opentelemetry.io/docs/specs/otel/logs/data-model/#log-and-event-record-definition) contain dedicated `TraceId` and `SpanId` fields. These fields are not filled by the EnvoyOpenTelemetryLogProvider extension provider yet. The extension provider allows to configure labels, which are mapped to OpenTelemetry log attributes, but not modifying the top level fields of the log record.

**Describe alternatives you've considered**

A possible workaround would be extracting the data from the request header and assigning to a label. E.g., the traceparent header when using the W3C Trace Context: 

```yaml
- envoyOtelAls:
    logFormat:
      labels:
        traceparent: '%REQ(TRACEPARENT)%'
   ```

Afterwards, a processor in an OpenTelemetry Collector could extract the `TraceId` and `SpanId` from the log attributes. Avoiding this overhead would be very convenient.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
can you raise this up on upstream(envoy)?

**Comment by chrkl** [comment]
@zirain Sure. Could you please point me to the right place? I did not find anything about OpenTelemetry-based access logs in the Envoy repo spontaneously.

**Comment by zirain** [comment]
should be here: https://github.com/envoyproxy/envoy/tree/main/source/extensions/access_loggers/open_telemetry

**Comment by zirain** [comment]
@chrkl Trace ID will be auto-detected and set in next major release(should be 1.22).

Not every trace provider implements `getTraceIdAsHex`, but at least it's OK for OpenTelemetry tracer.

**Comment by zirain** [comment]
According to [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#different-types-of-span), there's no plan to set `SpanId`.
