### ISSUE TITLE
Write integration tests to exercise installing each required Ambient component in a different namespace from the others.

### ISSUE THREAD

**Issue by bleggett** [istio/istio#49924]
**Describe the feature request**

Right now, our docs tell everyone to install everything in `istio-system`

This is bad advice from a blast radius and security policy standpoint.

Ambient also changes this a bit, due to requiring the use of `istio-cni` and `ztunnel`, which are node-critical in ways existing components are not.

It is also somewhat unclear what resources _must_ go in what namespaces, and what our actual hard colocation requirements are, and since most of our tests assume everything goes in the same namespace, bugs creep in, such as https://github.com/istio/istio/pull/49869#issuecomment-1991891744

We can continue to document `istio-system` as the catchall namespace in quickstart guides and docs, but we shouldn't have any _requirements_ on its use, or any hidden inter-component colocation requirements, and we should have per-component tests that validate this.

We should add an integration test that Helm installs each of the required Istio ambient components in their own namespace, to the degree this is possible, and identify any duplication of secrets and config this requires across namespaces as potential FIXMES - at the very least the test will codify and test the hard tenancy requirements we have.

This was spun out from discussion here: https://github.com/istio/istio.io/pull/14734#issuecomment-1998537220

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[^] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jmcshane** [comment]
I'd love to work on this issue if no one else is looking at it actively

**Comment by MorrisLaw** [comment]
What additional scenarios need to be tested for after the merging of the above [PR](https://github.com/istio/istio/pull/50288)? cc/ @bleggett

**Comment by jmcshane** [comment]
One of the things I was thinking about after this PR is moving beyond helm install tests to the other integration tests that also assume `istio-system` for everything. I could take one of the ambient existing integration tests and pass values to split the namespaces for these components

The helm install tests only do the most basic validations on the dependencies between the components, so it feels like enabling other ambient tests to support multi-ns deployments would be in line with the spirit of this issues.

**Comment by MorrisLaw** [comment]
Thank you @jmcshane! cc/ @jaellio ^

**Comment by bleggett** [comment]
What @jmcshane added already is a good enough start (we arguably could use a docs pass for some of this too, but that's a separate thing)

> One of the things I was thinking about after this PR is moving beyond helm install tests to the other integration tests that also assume `istio-system` for everything. I could take one of the ambient existing integration tests and pass values to split the namespaces for these components
> 
> The helm install tests only do the most basic validations on the dependencies between the components, so it feels like enabling other ambient tests to support multi-ns deployments would be in line with the spirit of this issues.

I am fine with the test rig having the ability to put each component in a specific namespace (what your PR added), so we can add specific tests for any weirdness we encounter.

From my perspective this issue is done - @jmcshane if you want to do more, PRs welcome, but we can close this one as DONE with @jmcshane's name on it if we want.

**Comment by howardjohn** [comment]
Closing as the recent stuff wraps this up
