### ISSUE TITLE
Invalid VirtualService in istio.networking.v1alpha3.html

### ISSUE THREAD

**Issue by esnible** [istio/istio#4994]
I copied the foo/reviews-route VirtualService from https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html and sent it to the istioctl (HEAD from April 16).  It fails with
```Error: cannot parse proto message: YAML decoding error: hosts:
...
 unknown field "host" in v1alpha3.Destination```

**Comment by ijsnellf** [comment]
It should be `host` according `istio/api` for the sha used by istio master.
to https://github.com/istio/api/blob/bf7eff00d3dede110dbe8b2f8fb09d778c9948ce/networking/v1alpha3/virtual_service.proto#L282
I expect it was just out of sync. Please try again with master.

**Comment by esnible** [comment]
This was a mistake.  I was using an older version of _istioctl_.
