### ISSUE TITLE
XDS: multi xds client in one sidecar, ProxyUpdate seem not update all client

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#49976]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

i want consumer xds data to expands istio, install a client in sidecar call pilot agent UDS address, but seem https://github.com/istio/istio/blob/ea36b73a14a771418d637a5d9551589ce27c4af1/pilot/pkg/xds/ads.go#L803-L808 ,ProxyUpdate only update one client, maybe we have more than one,  Is there a special design in it. 

### Version

```Text
$ istioctl version
client version: 1.20.0
control plane version: 1.19.4
data plane version: 1.19.4 (12 proxies)
```

**Comment by yanickxia** [comment]
@howardjohn Do you know more details about it ? Thanks

**Comment by howardjohn** [comment]
That is code that is triggered when one specific proxy changes and needs an update. Most of the code handles multiple proxies.
