### ISSUE TITLE
Regession with "istio.io/rev" namespace label on 1.17.0

### ISSUE THREAD

**Issue by brec** [istio/istio#49989]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It appears that functionality with the "istio.io/rev" label changed in version 1.17,  which impacts how we do our Istio upgrades.

During an istio upgrade, we deploy side-by-side versions of the istio gateway chart and istiod chart, using the revision flag. The istio base chart is kept at the "old" revision until traffic is ready to be cut over to the new revision, at which point the default revision is updated to point to the new revision.

Most recently on version 1.15.0, the behavior was that the control plane would use the value set in the namespace label "istio.io/rev" to inject that same value in the new version of the istio ingress gateway pod's  "istio.io/rev" value.

This allowed both and the new and old versions to share the same revision. Because our gateway resource and Load Balancer service use the "istio.io/rev" label to route traffic, we could route traffic to both versions.

This allowed us to validate that the new version of the gateway successfully manages traffic, and also verify that envoy can build all listener routes on the new version.

When we are ready to cut over traffic, we update the namespace revision, and then in a subsequent step cycle the new gateway pod versions so they associate with the new revision. After the new version gateway pods are associated with the new revision, the traffic selectors are updated to send traffic to the new revision.

However, with 1.17.0, it appears that the istio control plane ignores the rev flag value set in the namespace. Now, the new version receives the actual version of the deployment, not the value set in the namespace label.

Was this change intended ? If so, where is it documented ? Is there an alternative solution to do the type of upgrade I've outlined above. Thanks.

### Version

```Text
istioctl version:
client version: 1.19.8
istiod version: 1.17.8
istiod version: 1.17.8
istiod version: 1.17.8
istiod version: 1.19.8
istiod version: 1.19.8
istiod version: 1.19.8
data plane version: 1.17.8 (6 proxies)
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12", GitCommit:"19d5e4ee03daf5e8fb55a88b1a52d94332435e7e", GitTreeState:"clean", BuildDate:"2023-07-26T10:00:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

Prior to updating the namespace revision:

```
k get po -n ingress-default --show-labels
NAME                                    READY   STATUS    RESTARTS   AGE   LABELS
istio-gateway-1-17-8-857d8bfcd7-lnfrj   1/1     Running   0          29h   app=istio-gateway-1-17-8,ingress-gateway=default,istio.io/rev=1-17-8,istio=gateway-1-17-8,pod-template-hash=857d8bfcd7,service.istio.io/canonical-name=istio-gateway-1-17-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-gateway-1-17-8-857d8bfcd7-wh59c   1/1     Running   0          29h   app=istio-gateway-1-17-8,ingress-gateway=default,istio.io/rev=1-17-8,istio=gateway-1-17-8,pod-template-hash=857d8bfcd7,service.istio.io/canonical-name=istio-gateway-1-17-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-gateway-1-17-8-857d8bfcd7-x5bqk   1/1     Running   0          29h   app=istio-gateway-1-17-8,ingress-gateway=default,istio.io/rev=1-17-8,istio=gateway-1-17-8,pod-template-hash=857d8bfcd7,service.istio.io/canonical-name=istio-gateway-1-17-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-gateway-1-19-8-844884fc86-4v66t   1/1     Running   0          20s   app=istio-gateway-1-19-8,ingress-gateway=default,istio.io/rev=1-19-8,istio=gateway-1-19-8,pod-template-hash=844884fc86,service.istio.io/canonical-name=istio-gateway-1-19-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-gateway-1-19-8-844884fc86-cf8sz   1/1     Running   0          20s   app=istio-gateway-1-19-8,ingress-gateway=default,istio.io/rev=1-19-8,istio=gateway-1-19-8,pod-template-hash=844884fc86,service.istio.io/canonical-name=istio-gateway-1-19-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true
istio-gateway-1-19-8-844884fc86-gg98w   1/1     Running   0          35s   app=istio-gateway-1-19-8,ingress-gateway=default,istio.io/rev=1-19-8,istio=gateway-1-19-8,pod-template-hash=844884fc86,service.istio.io/canonical-name=istio-gateway-1-19-8,service.istio.io/canonical-revision=latest,sidecar.istio.io/inject=true


kubectl get namespace istio-system -o yaml |grep "istio.io/rev"
    istio.io/rev: 1-17-8
kubectl get namespace ingress-default -o yaml |grep "istio.io/rev"
    istio.io/rev: 1-17-8

istioctl x injector list
NAMESPACE         ISTIO-REVISION POD-REVISIONS
ingress-default                  1-17-8: 6 NEEDS RESTART: 6

NAMESPACES          INJECTOR-HOOK                                 ISTIO-REVISION SIDECAR-IMAGE
ingress-default     istio-sidecar-injector-1-17-8                 1-17-8         <image>/proxyv2:1.17.8
```

**Comment by howardjohn** [comment]
I am not 100% sure I followed exactly what you were doing before, but hopefully this helps:

https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy namespace istio.io/rev should be respected. I am not sure exactly what you mean by `it appears that the istio control plane ignores the rev flag value set in the namespace`

What I expect is you start with istiod on 1.15 and gateway on 1.15.

You deploy a new istiod with 1.17. You then update the namespace label to 1.17. You then restart gateway pod(s), and they start pointing to 1.17. You can then remove Istiod 1.15
