### ISSUE TITLE
Request is not getting logged on Istio ingress gateway and on upstream getting java socket timeout exception read timeout

### ISSUE THREAD

**Issue by parshva-shah-dsw** [istio/istio#49981]
### Bug Description

We have containerized application pods running in single cluster group. It has been observed that we encounter "**java.net.socketTimeoutException:readTimeout**" error on upstream side whenever a new worker node spins-up or spins-down to provision new pods or scaling down replicas. This creates service disruption in our production environment as no error is logged in ingress gateway we would like to understand if this pattern of issue is seen or we have any steps to debug the issue further. @howardjohn @Stono @zirain 

### Version

```Text
istioctl version
client version: 1.19.5
control plane version: 1.19.5

EKS version v1.25.16
```

**Comment by zirain** [comment]
are you sure that the request reach ingressgateway pod?

**Comment by parshva-shah-dsw** [comment]
@zirain request does not reach the ingress gateway when we see socket timeout exception on client application.

**Comment by parshva-shah-dsw** [comment]
@ramaraochavali  can you help us on this issue?

**Comment by parshva-shah-dsw** [comment]
@howardjohn can you help on this issue ?
