### ISSUE TITLE
support stats compression for merged metrics

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#49987]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
With https://github.com/istio/istio/pull/47997 we have support for compressed envoy stats. For those using agent merged metrics for application metrics or getting envoy metrics from the agent stats endpoint it would be useful to support compression as well in order to cut down on cross-zone/cross-region/cross-cloud costs.

This of course comes at a tradeoff of CPU utilization and would likely start as an opt-in rather than a default. This is just a request to extend the ability to enable stats compression on the agent.

**Describe alternatives you've considered**
Current workaround is to setup an envoy listener on an alternative port say 14020 which has a route to 15020 and a GZIP http filter enabled. EnvoyFilter to 15020 alone is not an option as 15020 is an Istio excluded port by default.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by msvticket** [comment]
While I'd prefer having this issue solved I'd like to get the work around working for at least some pods right away. I have managed to set up a listener on port 14090 in pods for a deployment using the method described here: https://github.com/istio/istio/issues/30987#issuecomment-822517456

But I don't understand how to route the traffic for port 150020 to this listener. Can anybody give me a hint?

**Comment by Aaron-ML** [comment]
> While I'd prefer having this issue solved I'd like to get the work around working for at least some pods right away. I have managed to set up a listener on port 14090 in pods for a deployment using the method described here: [#30987 (comment)](https://github.com/istio/istio/issues/30987#issuecomment-822517456)
> 
> But I don't understand how to route the traffic for port 150020 to this listener. Can anybody give me a hint?

I think this depends on the scraping application, for prometheus operator I think you can alter the scrape annotations on the pod:
```
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
```

Ultimately I'd love to see this integrated, currently merged metrics in our environments are over 1-2 megabytes of highly compressible per request. 

We can reduce these requests by over 80% with gzip, with marginal CPU usage. In my opinion there's no reason not to do this out of the box.
