### ISSUE TITLE
upstream connect error or disconnect/reset before headers.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#4999]
**[Environment]**
Kubernetes v1.9.2 + istio 0.7.1 + cilium rs6, installed by kubespary
Kubernetes v1.9.2 + istio 0.5.1 + cilium rs6, installed by kubespary

**[Steps]**
1  Deploy a new serviceA
2  Waiting for new pods of ServiceA started up, make sure all container started up and run successfully.
3  Using istio ingress url, to invoke https://xxx.ing.xxx.com/serviceA/health

**[Expect Result]**
The api will return 200

**[Actual Result]**

- The api will return 503
- The error message is: upstream connect error or disconnect/reset before headers.
- In the log of istio-proxy or service A, there is no any messages. (It means the request did not arrive the container at all I think)  

**[Debug message]**
•	curl localhost:9090/servicePath/v1/companies (In container of this svc)   **ok**
•	curl serviceA.namespace/servicePath/v1/companies   (In container of this svc) **ok**
•	curl serviceA.namespace/servicePath/v1/companies   (In container of other svc) **fail** or **ok**
•	curl -k https://xxx.ing.dev.XXXXX.com/servicePath/v1/companies   **fail**

**[Temp solution]**
Way 1:  Wait for 10 minutes, after new svc deployed.  (This issue only raise sometimes)

Way 2:   If way 1 not work, try below (Recovery rate: 95%)
   kubectl delete pod istio-ingress-67ff757554-8wlmd -n istio-system
   kubectl delete pod istio-pilot-67d6ddbdf6-kfjlp -n istio-system;

Way 3:   If way 2 not work, try below (Recovery rate: 80%)
    kubectl  delete pod kube-dns-79d99cdcd5-t8kv5 -n kube-system
    kubectl  delete pod kube-dns-79d99cdcd5-zgzg8 -n kube-system

Way 4:   If way 3 still not work, try below (Recovery rate: 100% so far)
    Delete all pod of serviceA, let they recreated.
    Do way 2 again
    Do way 3 again.

**Comment by thoslin** [comment]
Have you tried this solution: https://github.com/envoyproxy/envoy/issues/815#issuecomment-371852337

**Comment by imjoey** [comment]
The same issue +1, right after I ran `kubectl apply -f < (istioctl kube-inject -f abc.xml)` to update my services.

I tried all of your four ways but no one worked. Meanwhile I found that the pods IPs in the access log of istio-ingress, were not same as the ones in `kubectl get pods - o wide` output. So this may caused by `kube-dns`, which still took outdated data.

**Comment by imjoey** [comment]
@johnzheng1975  You should file issues in https://github.com/istio/issues/issues, not here. *Only confirmed, triaged and labelled issues should be filed here.*

**Comment by imjoey** [comment]
@johnzheng1975  Thank you, it works!  I also encountered  an issue `rds: fetch failure`, after I restarted the `istio-pilot` pods then everything is OK. Maybe restarting `istio-pilot` pods is also a helpful solution.

**Comment by johnzheng1975** [comment]
Cool! 
One confirm: are you using istio 0.7.1 and this issue still raise?
And, just want to know your issue will raise again? We need resolve it completely.

**Comment by imjoey** [comment]
@johnzheng1975  Yes, istio v0.7.1 still has the `upstream connect error or disconnect/reset before headers.` and `rds: fetch failure`  issues. Thanks for your highly appreciated work. 😄

**Comment by johnzheng1975** [comment]
add envoy configure file in istio-proxy [](url)

**Comment by johnzheng1975** [comment]
Today I reproduced this issue again in another istio0.5.1 platform. I record all the details and logs. As below:
After ham service deployed new version,  pod running well.

**[40 minutes later]**
Access https://use1c.ing.dev.fitstation4me.com/ham/api/v1/health still show “upstream connect error or disconnect/reset before headers”,   
Note: No logs is increased in ham container, no log is increased istio-proxy container(same pod)

In its own ham container, or other service’s container (order container), access api all successfully.
root@hp-order-deploy-6c7d84fb55-h6rk6:/go# curl hp-ham-service.hp/ham/api/v1/health
{"health":{"status":"UP"},"service_name":"L2 HAM"}
Note: Logs both showed in ham container, and istio-proxy container(same pod)

**[48 minutes later]**
Access https://use1c.ing.dev.fitstation4me.com/ham/api/v1/health works. It recovery automatically.

**[Logs attached]**
•	Ham service log
•	Ham service istio-proxy container log
•	Istio-ingress log
•	Cilium log
[istio-ingress.log](https://github.com/istio/istio/files/1932104/istio-ingress.log)
[ham-istio-proxy.log](https://github.com/istio/istio/files/1932105/ham-istio-proxy.log)
[ham-service.log](https://github.com/istio/istio/files/1932106/ham-service.log)
[cilium   .log](https://github.com/istio/istio/files/1932107/cilium.log)

**Comment by manalibhutiyani** [comment]
@johnzheng1975 : Did you try removing `http2_protocol_options: {}` in ` istio0.7.1`. Does it work on removing this option from envoy config file for `0.71`. I see this option in the `0.7.1_envoy_configure_in_istio_proxy.txt` you attached.

```
{
  "stats_config": {
    "use_all_default_tags": false
  },
  "admin": {
    "access_log_path": "/dev/stdout",
    "address": {
      "socket_address": {
        "address": "127.0.0.1",
        "port_value": 15000
      }
    }
  },
  "dynamic_resources": {
    "lds_config": {
      "api_config_source": {
        "api_type": "REST_LEGACY",
        "refresh_delay": {"seconds": 1, "nanos": 0},
        "cluster_names": [
          "rds"
        ]
      }
    },
    "cds_config": {
      "api_config_source": {
        "api_type": "REST_LEGACY",
        "refresh_delay": {"seconds": 1, "nanos": 0},
        "cluster_names": [
          "rds"
        ]
      }
    },
    "deprecated_v1": {
      "sds_config": {
        "api_config_source": {
          "api_type": "GRPC",
          "refresh_delay": {"seconds": 1, "nanos": 0},
          "cluster_names": [
            "xds-grpc"
          ]

        }
      }
    }
  },
  "static_resources": {
    "clusters": [
      {
        "name": "rds",
        "type": "STRICT_DNS",
        "connect_timeout": {"seconds": 10, "nanos": 0},
        "lb_policy": "ROUND_ROBIN",

      "hosts": [
          {
            "socket_address": {"address": "istio-pilot.istio-system", "port_value": 8080}
          }
        ]

    },
    {
    "name": "xds-grpc",
    "type": "STRICT_DNS",
    "connect_timeout": {"seconds": 10, "nanos": 0},
    "lb_policy": "ROUND_ROBIN",
    "hosts": [
    {
    "socket_address": {"address": "istio-pilot.istio-system", "port_value": 15010}
    }
    ],
    "circuit_breakers": {
        "thresholds": [
      {
        "priority": "default",
        "max_connections": "100000",
        "max_pending_requests": "100000",
        "max_requests": "100000"
      },
      {
        "priority": "high",
        "max_connections": "100000",
        "max_pending_requests": "100000",
        "max_requests": "100000"
      }]
    },
    "http2_protocol_options": { }
    }

    
    ,
      {
        "name": "zipkin",
        "type": "STRICT_DNS",
        "connect_timeout": {
          "seconds": 1
        },
        "lb_policy": "ROUND_ROBIN",
        "hosts": [
          {
            "socket_address": {"address": "zipkin.istio-system", "port_value": 9411}
          }
        ]
      }
      
    ]
  },
  
  "tracing": {
    "http": {
      "name": "envoy.zipkin",
      "config": {
        "collector_cluster": "zipkin"
      }
    }
  },
  
  
  "stats_sinks": [
    {
      "name": "envoy.statsd",
      "config": {
        "address": {
          "socket_address": {"address": "10.231.18.173", "port_value": 9125}
        }
      }
    }
  ]

}
```

**Comment by johnzheng1975** [comment]
@manalibhutiyani , this is not the root reason after investigation.
And, it is difficult to change envoy configure file except created a new image.  FYI

**Comment by johnzheng1975** [comment]
Here is comments of Romain (cilium engineer)
1) https://github.com/istio/istio/issues/4903 Istio Pilot crashes and sometimes enters CrashloopBackoff.
One symptom is that Istio Ingress returns 503s, because it tries to connect to the upstream pods that have been deleted.

This is a known upstream issue, for which we just submitted a fix: https://github.com/istio/istio/pull/5373
The fix will likely be merged into the Istio 0.8.0 release.

This bug causes all proxies, including Istio Ingress and sidecars, to not get configured until Pilot recovers.
We have observed that this can take up to 6 minutes.

*There is no workaround for that issue.*
However, the severity is not as high as the 2nd issue, since Pilot seems to recover on its own. (edited)

2) https://github.com/istio/istio/issues/5376 (we filed that issue)
The symptom is that an app's sidecar proxy always returns 503s for all inbound traffic.
We verified that, in this situation:
- Istio Ingress is healthy and correctly configured. It tries to connect to the right upstream pod.
- Istio Ingress has no network connectivity issues. Especially, it can connect with the upstream pod.
- Istio Ingress can correctly establish TCP connections to the backend pod, incl. HTTP connections.
- The upstream pod has no network connectivity issues. It can connect to Ingress, Pilot, other services, DNS, www.google.com, etc.

The root cause is that Pilot never pushes the configuration of the `in.80` cluster to the sidecar. That cluster is the one that handles all inbound traffic to port 80 in the application's pod. Without that cluster configured, no inbound connection can be established between the pod's Envoy proxy and the server within the same pod, so the sidecar proxy returns a 503 for every HTTP request.
When in that state, the sidecar is stuck forever, and never recovers.

*The workaround is to restart Pilot.*
Immediately after restarting, it pushes the right configuration to the app's sidecar, which immediately becomes healthy and stops returning 503s.

**Comment by johnzheng1975** [comment]
#4903
#5373 
#5376

**Comment by renperez** [comment]
is this a bug on 0.7.1? I'm seeing this issue everytime we do a deployment.

**Comment by johnzheng1975** [comment]
For my upstream issue, it related with several istio/cilium defects. Cilium team and istio team are fixing them.

Related issues:
Cilium high load issue:   https://github.com/cilium/cilium/pull/3985
Istio issue: https://github.com/istio/istio/issues/5376
Istio high load issue: https://github.com/istio/istio/issues/1485

Before they are fixed, we can use below workaround **to reduce issue raise**: 
Work around:
**Change istio configure**, to reduce istio load.  
- rdsRefreshDelay: 10s    (previous 1s)
- discoveryRefreshDelay: 10s  (previous 1s)
- Upgrade istio from 0.5.1 to 0.7.1.
**Change cilium configure** (if you use it)
- Disable cilium policy by  “--enable-policy=never”

**Comment by johnzheng1975** [comment]
| Upstream Issue   Cannot Recovery | Pod ready   performance after deploy
-- | -- | --
  | Need Manual Restart Count | Ready before 1m | Ready in 1m - 2m | Ready in 2m - 3m | Ready after 3m
Before work around | First Period:  3/1100   Second Period:  4/127   (Raise more and more frequency)   （Summary: 5/1000） | 1239/1277   (97%) | 27/1277   (2%) | 2/1277   (0.2%) | 9/1277   (0.8%)
After work around | 2/2000   （Summary: 1/1000） | 765/2000   (38%) | 1118/2000   (56%) | 83/2000    (4%) | 34/2000   (1%)

**Comment by johnzheng1975** [comment]
Test summary:
1 After work around, the rate of “Upstream Issue Cannot Recovery” come down a lot  (Excellent)
2 After work around, the “Pod ready performance after deploy” turns worse  (Not good)
   However, 99% pod still can be ready in 3 mins.
3 After work around, the api server pod restart still frequency - 10 times one day  (Same)
4 After work around, the cpu usage of cilium/ istio still very high (Same)

**Comment by johnzheng1975** [comment]
PS: How to change istio configure 
Change 1:
```kubectl -n istio-system edit cm istio```
    rdsRefreshDelay: 10s```
    (changed from 1s)

    ```defaultConfig:
      discoveryRefreshDelay: 10s```
       (changed from 1s)

Change 2:
```kubectl -n istio-system edit deployment istio-ingress```
from:
        ```- --discoveryRefreshDelay
        - 1s```
to:
        ```- --discoveryRefreshDelay
        - 10s```

After that, you need 
1 Restart all istio-system pods  (Just delete pod)
2 re-istioctl all application pods

**Comment by renperez** [comment]
Thanks for this @johnzheng1975

**Comment by gbaufake** [comment]
I'm facing this issue with istio 0.8.0 and istio-ingress config variable `discoveryRefreshDelay` set to 10s
[istio-ingress.txt](https://github.com/istio/istio/files/2125313/istio-ingress.txt)

**Comment by imjoey** [comment]
@gbaufake  which version of the proxy image is in your case? In my istio 0.8.0 cluster with `--discoveryRefreshDelay = 10s`,  right after I upgraded the proxy image to `docker.io/istio/proxyv2:0.8.0`, this issue seems to have been resolved.

**Comment by denniseffing** [comment]
I'm facing the issue as well. 

- istio 0.8.0
- `discoveryRefreshDelay` is set to 10s. 
- proxy image proxyv2:0.8.0

**Comment by denniseffing** [comment]
Just in case someone made the same mistake:

Don't forget to label your namespace for the automatic sidecar injection:
`kubectl label namespace <namespace> istio-injection=enabled`

Default namespace (when you deploy the bookinfo application without specifying one) is called 'default' which results in
`kubectl label namespace default istio-injection=enabled`

If you forget this step, you will see the same error as OP.

**Comment by andraxylia** [comment]
Is this still an issue?

**Comment by andraxylia** [comment]
proxyv2  works with gRPC streaming from pilot, so you should not see this anymore.

**Comment by liamawhite** [comment]
@johnzheng1975 could you give a quick summary of the issue you see in 0.8?

**Comment by liamawhite** [comment]
Added to the traffic loss umbrella and set to P0 as it seems like these issues need to be resolved before 1.0.

**Comment by andraxylia** [comment]
@liamawhite the traffic loss umbrella deals with intermittent traffic loss due to config changes. The issue here seems to have different root causes.

**Comment by johnzheng1975** [comment]
I would like to close it, and track upstream issue in https://github.com/istio/istio/issues/6085
The issue raise on 0.5.1 and 0.7.1 reduced a lot.
For 0.8.0+ issue, I will track in other defects
