### ISSUE TITLE
Ran a VAPT on a EKS cluster with Istio installed. Found excessive permissions on some resources. Need some justifications....

### ISSUE THREAD

**Issue by Nutties93** [istio/istio#49992]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I will require some explanation and understanding on the following.

**It was found that the 3 resources below were able to list secrets. Is there a reason why?** 
1) istio-reader-istio-system
2) istiod-clusterrole-istio-system
3) istiod-istio-system 

**It was found that Kiali can delete any resources. Can I remove this permission?**

### Version

```Text
istio version 1.18.3. Same for add-ons.
```

### Additional Information

I would like to restrict the resources permissions. Not sure if it would affect istio functions.

**Comment by Nutties93** [comment]
Anybody got explanations or advice for this?

**Comment by howardjohn** [comment]
These are used to read Secrets for multi-cluster access and for reading TLS certificates for Gateways
