### ISSUE TITLE
Request from Deployment without service or external.

### ISSUE THREAD

**Issue by fleeto** [istio/istio#500]
I'm trying the feature of fault injection, then I found, to trigger the route-rule. the request must fulfill the requirements list below:

- Inside the cluster and from a injected deployment/pod
- The deployment has a service, or 
  - curl [service-ip:port], success
  - curl [service-name], 404 NR
  - curl [service-fqdn], success

Is it a feature or bug?

~~~
istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1


apiserver version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
~~~

**Comment by kyessenov** [comment]
There's a bug about service-less pods requiring FQDN. We'll fix it in next release.

**Comment by fleeto** [comment]
Thanks for your reply.
How about cases that accessing a service out of the cluster, route-rules seems won't work in that cases.

**Comment by kyessenov** [comment]
route-rule features are enforced by client-side proxies, so it makes sense that some things like faults don't work without a client-side proxy. If you enable istio auth, then the client-side proxy is mandatory in fact.

**Comment by fleeto** [comment]
Got it, thank you so much.
