### ISSUE TITLE
Mirroring percentage on HTTPRoute

### ISSUE THREAD

**Issue by sim-commits** [istio/istio#50007]
Hi,

Following the Istio documentation : https://istio.io/latest/docs/tasks/traffic-management/mirroring/ I am trying to mirror a percentage of the traffic using HTTPRoute. Do you have any idea how to achieve that?

Thanks a lot

**Comment by howardjohn** [comment]
This is not currently supported upstream. It is being tracked upstream now: https://github.com/kubernetes-sigs/gateway-api/discussions/3103#discussioncomment-9706899. Once it lands we can implement it in Istio
