### ISSUE TITLE
503 Intermitent error(no healthy upstream)

### ISSUE THREAD

**Issue by ritesh58** [istio/istio#50000]
![Uploading erroristio.png…]()
Hi Team,
 
We need an urgent help. We are getting 503 no healthy upstream error intermittently from istio gateway. Seeing your release note which has the same bug stated fixed in envoy version which comes with istio version 1.21 , we upgraded the istio to latest version but the error is still here. Our whole infrastructure is impacted by it. Help will be greatly appreciated.
 
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (299 proxies)
[09:41] Gupta, Ritesh

**Comment by chaseSpace** [comment]
Maybe you should give some details here.

**Comment by ritesh58** [comment]
Hi , as stated we getting no healthy upstreams. after getting details log it is showing below in istio-proxy log
![Uploading erroristio.png…]()

**Comment by chaseSpace** [comment]
What protocol your app used? Have you tried access your app container use same protocol? Access test should be continuous.

**Comment by ritesh58** [comment]
It seems it does . but we see below error though the istio release notes says the issue has already been fixed. So just wanted to ask is there a way to override connections setting to pervent it to break
<img width="1398" alt="image" src="https://github.com/istio/istio/assets/3917151/8c1c65f7-61e6-43b7-88ec-dadb4ebe5fa5">
