### ISSUE TITLE
How to custom --service-node for envoy process?

### ISSUE THREAD

**Issue by shenxg13** [istio/istio#5003]
my k8s cluster has a custom domain name y.kube:
[root@k8s-192-168-0-52-kube01 istio]# ps -ef|grep y.kube
root      1168     1  2 Apr16 ?        00:44:42 /usr/local/bin/kubelet --address=0.0.0.0 --pod-infra-container-image=192.168.0.41/kube/pause-amd64:3.0 --bootstrap-kubeconfig=/etc/kubernetes/ssl/kubelet-bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cert-dir=/etc/kubernetes/ssl --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --cgroup-driver=systemd --cluster_dns=10.17.0.2 **--cluster_domain=y.kube** --v=2 --rotate-certificates --feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true --cloud-provider=vsphere --cloud-config=/etc/kubernetes/vsphere.conf --node-labels=level=1

but the istio proxy still using the default domain name cluster.local:
/usr/local/bin/envoy -c /etc/istio/proxy/envoy_mixer.json --restart-epoch 3 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster istio-proxy **--service-node mixer~~.~.svc.cluster.local** --max-obj-name-len 189 -l info

how can i change the --service-node from cluster.local to y.kube?

**Comment by liamawhite** [comment]
@shenxg13 how are you deploying Istio? `kube-inject` or initialiser?

**Comment by andraxylia** [comment]
Please check for serviceCluster here:
https://istio.io/docs/setup/kubernetes/sidecar-injection/
