### ISSUE TITLE
Istio ingress gateway high memory usage

### ISSUE THREAD

**Issue by RyanRennCN** [istio/istio#50035]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Im experiencing the issue noted in this closed (no resolution) issue: https://github.com/istio/istio/issues/29542

Randomly, we will see dramatically increased consumption of memory in the Istio Ingress Gateway pods. This has led to outages for ingress into the cluster because the pods get OOM killed. We have since increased the limit twice, but I am concerned about it continuing to grow over time.

Additionally, we do notice increased network transmission from the the ingress gateway pods during these spikes but overall traffic into the pods from outside the cluster is minimal or unchanged from when the memory is normal.

<img width="963" alt="image" src="https://github.com/istio/istio/assets/102681076/9e0b006f-38ca-4695-9e61-a193dd5b86a1">
Above is an example showing the spikes in memory. The right side of each chart shows sporadic statistics (but they are abnormally high when recorded) because the pod was crash looping from the OOM kills.

Istio in this case was deployed as part of the "Kubeflow-on-AWS" distribution of "Kubeflow".

I have so far been unable to find a cause for this high memory or anything to correlate it to in order to find a cause.

### Version

```Text
$ istioctl version
client version: 1.21.0
control plane version: 1.16.0
data plane version: 1.16.0 (199 proxies)

$ kubectl version
Client Version: v1.29.1
Server Version: v1.25.16-eks-508b6b3

helm version --short
v3.13.3+gc8b9489
```

### Additional Information

I did pull this information, but I am concerned about posting it publicly since it appears to contain a lot of information about our company's cluster. If I can share this more discreetly with a smaller audience or if I can pull some specific information from it in order to make sure its sanitized, that would be great. Please let me know.

**Comment by samuel-esp** [comment]
Hi @RyanRennCN, looks like you are experiencing the same problem I have. I also think you are using a Cluster Autoscaler that can choose different instance types (with different vCPU and Memory available). If this is the case the IstioProxy inside your Ingress Gateway pod configures its concurrency settings based on the node where it scheduled. This results in a very strange behavior where the Ingress Gateway Pod consumes a lot of memory in bigger nodes (>16 vCPUs) and normal memory in (<16 vCPUs)

Look at my thread #49945 where I'm trying to understand the best settings to reduce memory usage and control this behavior

**Comment by RyanRennCN** [comment]
> Hi @RyanRennCN, looks like you are experiencing the same problem I have. I also think you are using a Cluster Autoscaler that can choose different instance types (with different vCPU and Memory available). If this is the case the IstioProxy inside your Ingress Gateway pod configures its concurrency settings based on the vCPUs of the node where it is scheduled. This results in a very strange behavior where the Ingress Gateway Pod consumes a lot of memory in bigger nodes (>=16 vCPUs) and normal memory in normal nodes (<16 vCPUs)
> 
> Look at my thread #49945 where I'm trying to understand the best settings to reduce memory usage and control this behavior

Thanks for the information, @samuel-esp . I was not aware of this behavior with different sized instances. I will review.
