### ISSUE TITLE
missing lbEndpoint for second cluster in istio egressgateway proxy

### ISSUE THREAD

**Issue by lkalaivanan** [istio/istio#50041]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Missing lbEndpoint for second cluster in istio egressgateway proxy 

STEPS:

- BringUp two k8s cluster and install 1.20.4 istio on the both
- Deployed say shopping in cluster1 which will connect to catalog service that is running in cluster2
- Configured the needed service entries, destinationrules and gateways 

**Service Entry:**

```
% k get se -n default        nsxsm.catalog  -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2024-03-21T09:12:41Z"
  generation: 1
  labels:
    cluster: eekkss
    createdby: test
  name: nsxsm.catalog
  namespace: default
  resourceVersion: "5908383"
  uid: 91b0df7f-0efd-4f18-be0d-b1ef76fede05
spec:
  addresses:
  - XXX.XXX.XXX.XXX
  endpoints:
  - address: istio-egressgateway.istio-system
    ports:
      http-catalog: 443
    weight: 1
  exportTo:
  - .
  hosts:
  - catalog.acme.com
  location: MESH_INTERNAL
  ports:
  - name: http-catalog
    number: 8082
    protocol: HTTP
  resolution: DNS

```

**Destination Rule:**
```
% k get dr -n istio-system   nsxsm.gns.acmetest.com -o yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  creationTimestamp: "2024-03-21T10:31:21Z"
  generation: 1
  labels:
    createdby: test
  name: nsxsm.gns.acme.com
  namespace: istio-system
  resourceVersion: "5928249"
  uid: 83ce0e72-16b0-461f-8f5a-d3e880e546a3
spec:
  host: '*.acme.com'
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 120s
      consecutive5xxErrors: 1
      consecutiveGatewayErrors: 1
      interval: 1s
      maxEjectionPercent: 1
      minHealthPercent: 1
    tls:
      mode: ISTIO_MUTUAL

`

**gateway : Egressgateway**

`
% k get gw -n istio-system   istio-egressgateway  -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: "2024-03-21T11:36:53Z"
  generation: 1
  labels:
    app: gateways
    createdby: allspark
    release: istio
  name: istio-egressgateway
  namespace: istio-system
  resourceVersion: "5944911"
  uid: 4e1b90e3-09e5-4c94-aee4-68c96220440a
spec:
  selector:
    app: istio-egressgateway
    istio: egressgateway
  servers:
  - hosts:
    - '*.acme.com'
    port:
      name: tls-multicluster-listener
      number: 443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
```
**Expected:**

The shopping service in cluster1 should able to connect to catalog service in cluster2

**Actual:**
Receiving 503 error in shopping when tries to connect to catalog. **Same config worked with istio 1.19.3**

**Istio Egress Proxy config:**

```
% istioctl proxy-config cluster -i istio-system istio-egressgateway-9f4bb8b8d-4pq9c.istio-system --fqdn catalog.acme.com -o json                 
[
    {
        "name": "outbound|8082||catalog.acme.com",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|8082||catalog.acme.com",
            "endpoints": [
                {
                    "locality": {},
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": “XXX.XXX.XXX.XXX”,
                                        "portValue": 443
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "istio": {
                                        "workload": ";;;;Kubernetes"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        },
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "istio-egressgateway.istio-system",
                                        "portValue": 443
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "istio": {
                                        "workload": ";;;;Kubernetes"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 2
                }
            ]
        },
        ………
	………
                "sni": "outbound_.8082_._.catalog.acme.com"
            }
        },
       ………
	………
    },

    {
        "name": "outbound_.8082_._.catalog.acme.com",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound_.8082_._.catalog.acme.com",
            "endpoints": [
                {
                    "locality": {}                               <<<<<<<<<<<<<<. LbEndpoints missing here
                }
            ]
        },
       ………
	………
]
```

### Version

```Text
% istioctl version
client version: 1.20.0
control plane version: 1.20.4
data plane version: 1.20.4


 % kubectl version

Client Version: v1.26.10"
Kustomize Version: v4.5.7
Server Version: v1.26.13-eks-508b6b3
```

**Comment by lkalaivanan** [comment]
@hzxuzhonghu Can someone take a look on this, this is blocking our production.

**Comment by howardjohn** [comment]
There must be a second SE for catalog.acme.com in istio-system? Can you include it?

Stepping back, this is a pretty unexpected configuration - I have never seen a setup like this. Are you intentionally or accidentally differing from the usual setup?

**Comment by lkalaivanan** [comment]
@howardjohn 

**SE from istio-system:**

`
% k get se -n istio-system   nsxsm.gns.asdf.catalog -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2024-03-21T11:36:55Z"
  generation: 3
  labels:
    cluster: eekkss
    createdby: allspark
    gns: asdf
  name: nsxsm.gns.asdf.catalog
  namespace: istio-system
  resourceVersion: "7232978"
  uid: aaabbb72-1689-4b91-aea7-fcb9f9e5ec9f
spec:
  addresses:
  - 245.185.36.76
  endpoints:
  - address: 34.16.45.245
    network: external
    ports:
      http-catalog: 443
  - address: istio-egressgateway.istio-system
    ports:
      http-catalog: 443
    weight: 1
  exportTo:
  - .
  hosts:
  - catalog.asdf.com
  location: MESH_INTERNAL
  ports:
  - name: http-catalog
    number: 8082
    protocol: HTTP
  resolution: DNS

`

Yes not able to provide the whole config unfortunately.. If you gave me list of configs needed for debugging will provide the informations.

**Comment by hzxuzhonghu** [comment]
Normally cluster like this format could only be generated for east-west-gateway. 

Is there a gateway for tls auto passthrough on egress gateway?

**Comment by hzxuzhonghu** [comment]
@lkalaivanan You should check all SEs with catalog.acme.com host. Could be in any namespaces

**Comment by lkalaivanan** [comment]
> Normally cluster like this format could only be generated for east-west-gateway.
> 
> Is there a gateway for tls auto passthrough on egress gateway?

Yes there is TLS auto passthrough on egress gateway.

`
% k get gw -n istio-system   istio-egressgateway  -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: "2024-03-21T11:36:53Z"
  generation: 1
  labels:
    app: gateways
    createdby: allspark
    release: istio
  name: istio-egressgateway
  namespace: istio-system
  resourceVersion: "5944911"
  uid: 4e1b90e3-09e5-4c94-aee4-68c96220440a
spec:
  selector:
    app: istio-egressgateway
    istio: egressgateway
  servers:
  - hosts:
    - '*.acme.com'
    port:
      name: tls-multicluster-listener
      number: 443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
`

**Comment by lkalaivanan** [comment]
> @lkalaivanan You should check all SEs with catalog.acme.com host. Could be in any namespaces

Yes, SEs with catalog.acme.com host in two namespaces. one is on default and other is on istio-system.

**Comment by howardjohn** [comment]
the auto passthrough mode filters endpoints that do not do mTLS

**Comment by howardjohn** [comment]
this was probably a bug in 1.19 not 1.20

**Comment by lkalaivanan** [comment]
@howardjohn Not only for 1.19, on the previous versions like 1.18 and 1.17 it used to work for us. Is there a new changes happened in these areas.

**Comment by howardjohn** [comment]
Yeah there was a unification of EDS and CDS code

**Comment by hzxuzhonghu** [comment]
what does the other SE look like, i suspect it has no endpoints

**Comment by lkalaivanan** [comment]
> what does the other SE look like, i suspect it has no endpoints


**Default Namespace SE:**

`
% k get se -n default        nsxsm.gns.acme.catalog -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2024-03-07T09:52:16Z"
  generation: 1
  labels:
    cluster: eks119
    domain: default
  name: nsxsm.gns.acme.catalog
  namespace: default
  resourceVersion: "714374"
  uid: 8852ad7a-cf72-47f3-9de3-8100c0a925e0
spec:
  addresses:
  - XX.XX.XX.XX
  endpoints:
  - address: istio-egressgateway.istio-system
    ports:
      http-catalog: 443
    weight: 1
  exportTo:
  - .
  hosts:
  - catalog.acme.com
  location: MESH_INTERNAL
  ports:
  - name: http-catalog
    number: 8082
    protocol: HTTP
  resolution: DNS
   `
   
 **Istio-system Namespace SE:**
 
 `
  % k get se -n istio-system   nsxsm.acme.catalog  -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2024-03-07T09:52:16Z"
  generation: 1
  labels:
    cluster: eks119
  name: nsxsm.acme.catalog
  namespace: istio-system
  resourceVersion: "714379"
  uid: cc39f612-6938-415c-a07a-f4fc0d49f44d
spec:
  addresses:
  - XX.XX.XX.XX
  endpoints:
  - address: XX.XX.XX.XX
    network: external
    ports:
      http-catalog: 443
  - address: istio-egressgateway.istio-system
    ports:
      http-catalog: 443
    weight: 1
  exportTo:
  - .
  hosts:
  - catalog.acme.com
  location: MESH_INTERNAL
  ports:
  - name: http-catalog
    number: 8082
    protocol: HTTP
  resolution: DNS
 `

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu 

To re-iterate. The problem for us is, a service in cluster one not able to access a service in cluster2.

In working setup i.e in version 1.19 or 1.18 or 1.17 the istio egressgateway proxy config will have an LBendpoint pointing to the ingressgateway of cluster2. I hope this route is getting resolved from the istio-system SE mentioned in previous comment.

But in 1.20 istio the LBendpoint is missing in egressgateway. This is the issue for us. Following is the proxy container log and access.

**Proxy Log :** 

`
2024-02-06T07:22:31.274651Z        debug        envoy filter external/envoy/source/common/tcp_proxy/tcp_proxy.cc:430        [Tags: "ConnectionId":"2027"] Creating connection to cluster outbound_.8082_._.catalog.acme.com        thread=38
2024-02-06T07:22:31.274669Z        debug        envoy upstream external/envoy/source/common/upstream/cluster_manager_impl.cc:2072        no healthy host for TCP connection pool        thread=38

`

**Access Log:**

`
[2024-02-05T06:07:16.076Z] "- - -" 0 UH - - "-" 0 0 1 - "-" "-" "-" "-" "-" outbound_.8082_._.catalog.acme.com - 10.20.3.17:8443 10.20.3.22:60698 outbound_.8082_._.catalog.acme.com -
[2024-02-05T06:07:16.063Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" outbound_.8082_._.catalog.acme.com - 10.20.1.51:8443 10.20.3.22:60688 outbound_.8082_._.catalog.acme.com -
[2024-02-05T06:07:16.073Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" outbound_.8082_._.catalog.acme.com - 10.20.1.51:8443 10.20.3.22:60696 outbound_.8082_._.catalog.acme.com -
`

**Comment by lkalaivanan** [comment]
> mTLS

So MTLS is mandatory to achieve cross clustering.?

**Comment by hzxuzhonghu** [comment]
I am not sure why donot you use istio multicluster mode, and make traffic pass through  east-west gateway

https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/ or https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu 

we have some proprietary stuff in configuring cross clustering. But the configuration what ever we used is working past several versions. We only see issue with 1.20.

**Comment by hzxuzhonghu** [comment]
can you sen me all the configs via email or slack if you donot want to share publicly, i can do some deeper investigate

**Comment by lkalaivanan** [comment]
@hzxuzhonghu Let me know what are the information needed from the setup, will discuss with team and send you the logs / configs.

**Comment by lkalaivanan** [comment]
@hzxuzhonghu Please share the informations needed for your debugging will share the details. But I hope In previous chats I shared most of the informations.

**Comment by hzxuzhonghu** [comment]
All services/serviceEntry, VS and DestinationRule, Gateway related to catalog.acme.com

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu

Please find the logs attached with informations needed,

[cluster_one_all_service_entry.txt](https://github.com/istio/istio/files/14832349/cluster_one_all_service_entry.txt)
[cluster_one_all_GW.txt](https://github.com/istio/istio/files/14832359/cluster_one_all_GW.txt)
[cluster_one_all_service.txt](https://github.com/istio/istio/files/14832360/cluster_one_all_service.txt)
[cluster_one_all_VS.txt](https://github.com/istio/istio/files/14832361/cluster_one_all_VS.txt)

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu

Istio Egress proxy config which has missing end point,


[
    {
        "name": "outbound|8082||catalog.acme.com",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|8082||catalog.acme.com",
            "endpoints": [
                {
                    "locality": {},
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "XX.XX.XX.XX",
                                        "portValue": 443
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "istio": {
                                        "workload": ";;;;Kubernetes"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        },
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "istio-egressgateway.istio-system",
                                        "portValue": 443
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "istio": {
                                        "workload": ";;;;Kubernetes"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 2
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295,
                    "trackRemaining": true
                }
            ]
        },
        "dnsRefreshRate": "60s",
        "respectDnsTtl": true,
        "dnsLookupFamily": "V4_ONLY",
        "outlierDetection": {
            "consecutive5xx": 1,
            "interval": "1s",
            "baseEjectionTime": "120s",
            "maxEjectionPercent": 1,
            "enforcingConsecutive5xx": 100,
            "enforcingSuccessRate": 0,
            "consecutiveGatewayFailure": 1,
            "enforcingConsecutiveGatewayFailure": 100
        },
        "commonLbConfig": {
            "healthyPanicThreshold": {
                "value": 1
            }
        },
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsParams": {
                        "tlsMinimumProtocolVersion": "TLSv1_2",
                        "tlsMaximumProtocolVersion": "TLSv1_3"
                    },
                    "tlsCertificateSdsSecretConfigs": [
                        {
                            "name": "default",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    ],
                    "combinedValidationContext": {
                        "defaultValidationContext": {},
                        "validationContextSdsSecretConfig": {
                            "name": "ROOTCA",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    },
                    "alpnProtocols": [
                        "istio-peer-exchange",
                        "istio"
                    ]
                },
                "sni": "outbound_.8082_._.catalog.acme.com"
            }
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/destination-rule/nsxsm.acme.com",
                    "services": [
                        {
                            "host": "catalog.acme.com",
                            "name": "catalog.acme.com",
                            "namespace": "istio-system"
                        }
                    ]
                }
            }
        }
    },
    {
        "name": "outbound_.8082_._.catalog.acme.com",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound_.8082_._.catalog.acme.com",
            **"endpoints": [
                {
                    "locality": {}             <<<<<<< lbEndpoints missing here. 
                }**
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295,
                    "trackRemaining": true
                }
            ]
        },
        "dnsRefreshRate": "60s",
        "respectDnsTtl": true,
        "dnsLookupFamily": "V4_ONLY",
        "outlierDetection": {
            "consecutive5xx": 1,
            "interval": "1s",
            "baseEjectionTime": "120s",
            "maxEjectionPercent": 1,
            "enforcingConsecutive5xx": 100,
            "enforcingSuccessRate": 0,
            "consecutiveGatewayFailure": 1,
            "enforcingConsecutiveGatewayFailure": 100
        },
        "commonLbConfig": {
            "healthyPanicThreshold": {
                "value": 1
            }
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/destination-rule/nsxsm.acme.com",
                    "services": [
                        {
                            "host": "catalog.acme.com",
                            "name": "catalog.acme.com",
                            "namespace": "istio-system"
                        }
                    ]
                }
            }
        }
    }
]

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu Is the issue https://github.com/istio/istio/issues/50186 is related ?

**Comment by howardjohn** [comment]
No, that issue is about a new envoy commit merged days ago

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu  are you guys able to verify the config's attached has requested.

**Comment by lkalaivanan** [comment]
> No, that issue is about a new envoy commit merged days ago

But the change is in 1.20 istio. 1.19 that envoy change is not there right. 
Also why I asked is, in egress access log I am seeing the same error mentioned in that ticket. I may be wrong.

![image](https://github.com/istio/istio/assets/13291057/8037423f-6ec1-4eff-8c2b-eeaffe736ff0)

**Comment by howardjohn** [comment]
This was changed in https://github.com/istio/istio/commit/d4f548ab4bedb4b7a59f0229e38ecae1a6ebfc05. mTLS is required for multi-network. This was a bug that was (accidentally) fixed in 1.20 by the above change.

**Comment by lkalaivanan** [comment]
> This was changed in [d4f548a](https://github.com/istio/istio/commit/d4f548ab4bedb4b7a59f0229e38ecae1a6ebfc05). mTLS is required for multi-network. This was a bug that was (accidentally) fixed in 1.20 by the above change.

@howardjohn Is this comment regarding ticket https://github.com/istio/istio/issues/50186 or the actual issue I filed.

Even when MTLS is mandatory for cross cluster setting tls.mode to auto_passthrough in GW should work right ?

`    
tls:
      mode: AUTO_PASSTHROUGH
      `

**Comment by lkalaivanan** [comment]
> @hzxuzhonghu

@hzxuzhonghu  have you able to go through the configs attached.

**Comment by lkalaivanan** [comment]
@howardjohn  @hzxuzhonghu

Found following in egressgateway proxy logs,

In **istio 1.19**  after add/update cluster event,

`56510 2024-04-05T10:09:56.251870Z     debug   envoy upstream external/envoy/source/common/upstream/cluster_manager_impl.cc:760        add/update cluster outbound_.8082_._.catalog.acmetest.com starting warming      thread=15  `    

there was a DNS resolution initiated,

```
56511 2024-04-05T10:09:56.251877Z     trace   envoy upstream external/envoy/source/extensions/clusters/strict_dns/**strict_dns_cluster**.cc:104   starting async DNS resolution for XX.XX.XX.XX   thread=15
56512 2024-04-05T10:09:56.251880Z     debug   envoy dns external/envoy/source/extensions/network/dns_resolver/cares/dns_impl.cc:358   dns resolution for XX.XX.XX.XX  started  thread=15
56513 2024-04-05T10:09:56.251966Z     debug   envoy dns external/envoy/source/extensions/network/dns_resolver/cares/dns_impl.cc:278   dns resolution for XX.XX.XX.XX  completed with status 0  thread=15
```

But in **istio 1.20** after add/update cluster event not dns resolution happened.

```
1324 2024-03-22T12:17:13.718851Z     debug   envoy upstream external/envoy/source/common/upstream/cluster_manager_impl.cc:771        add/update cluster outbound_.8082_._.catalog.asdf.com during init       thread=16                     
  1325 2024-03-22T12:17:13.718863Z     debug   envoy upstream external/envoy/source/common/upstream/upstream_impl.cc:1579      initializing Primary cluster outbound_.8082_._.catalog.asdf.com completed       thread=16
  1326 2024-03-22T12:17:13.718866Z     debug   envoy init external/envoy/source/common/init/manager_impl.cc:49 init manager Cluster outbound_.8082_._.catalog.asdf.com contains no targets     thread=16
  1327 2024-03-22T12:17:13.718868Z     debug   envoy init external/envoy/source/common/init/watcher_impl.cc:14 init manager Cluster outbound_.8082_._.catalog.asdf.com initialized, notifying ClusterImplBase  thread=16
  1328 2024-03-22T12:17:13.718882Z     debug   envoy upstream external/envoy/source/common/upstream/cluster_manager_impl.cc:1231       adding TLS cluster outbound_.8082_._.catalog.asdf.com   thread=16
  1329 2024-03-22T12:17:13.718903Z     trace   envoy upstream external/envoy/source/common/upstream/cluster_discovery_manager.cc:37    cm cdm: starting processing cluster name outbound_.8082_._.catalog.asdf.com (status 2) from cluster lifecycle callback in main_thread   thread=16
  1330 2024-03-22T12:17:13.718907Z     trace   envoy upstream external/envoy/source/common/upstream/cluster_discovery_manager.cc:47    cm cdm: no callbacks for the cluster name outbound_.8082_._.catalog.asdf.com in main_thread     thread       =16
  1331 2024-03-22T12:17:13.718911Z     debug   envoy upstream external/envoy/source/common/upstream/cluster_manager_impl.cc:153        cm init: init complete: cluster=outbound_.8082_._.catalog.asdf.com primary=12 secondary=35      thread       =16
```

**Comment by howardjohn** [comment]
Yes, the endpoint is filtered because mTLS isn't configured. mTLS is required for auto_passthrough

**Comment by lkalaivanan** [comment]
@howardjohn In my case the MTLS is enabled cluster wide. Please verify the configs below,

**Peerauthentication :**

```
% k get pa -n istio-system   default -o yaml
....
spec:
  mtls:
    mode: STRICT
```
   
**Destination Rule in istio-system for that domain:**

```
 % k get dr -n istio-system   mydr -o yaml 
....
    tls:
      mode: ISTIO_MUTUAL
```

**EgressGateway GW:**

```
k -n istio-system get gw istio-egressgateway  -o yaml
.....
    tls:
      mode: AUTO_PASSTHROUGH
```

So If I understand correctly In istio 1.20, setting "AUTO_PASSTHROUGH" not allowed in GW for cross clustering.

**Comment by hzxuzhonghu** [comment]
In ServiceEntry registry, we make endpoint converted from SE as tls disabled.

```
func (s *Controller) convertServiceEntryToInstances(cfg config.Config, services []*model.Service) []*model.ServiceInstance {

```

**Comment by lkalaivanan** [comment]
@howardjohn @hzxuzhonghu THANKS for the help.

Adding following label to the service entry (spec.endpoints.lables) in istio-system fixed our issue.

`labels:
      security.istio.io/tlsMode: istio`

**Comment by akashjain971** [comment]
> @howardjohn @hzxuzhonghu THANKS for the help.
> 
> Adding following label to the service entry (spec.endpoints.lables) in istio-system namespace fixed our issue.
> 
> labels: security.istio.io/tlsMode: istio

@lkalaivanan how did you learn about this label?
I do not find it in the docs. I see code references though.
Also, is there a way to set this globally instead of setting this on every ServiceEntry?

**Comment by lkalaivanan** [comment]
> In ServiceEntry registry, we make endpoint converted from SE as tls disabled.
> 
> ```
> func (s *Controller) convertServiceEntryToInstances(cfg config.Config, services []*model.Service) []*model.ServiceInstance {
> ```

@akashjain971 I found it directly from code using the above reference provided by @hzxuzhonghu . 

Yes there is no documentation for this. 

I dont know how to set it globally. Our usecase is bit different which doesn't needed global setting.
