### ISSUE TITLE
Enable the `tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh` istio.io test

### ISSUE THREAD

**Issue by ericvn** [istio/istio#50040]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Moving the istio.io tests back to the main branch after release-1.21 was released had the `tasks/traffic-management/egress/egress-tls-origination/mtls_test.sh` test failing.

I'm thinking the `kubectl create secret generic client-credential --from-file=tls.key=client.example.com.key --from-file=tls.crt=client.example.com.crt --from-file=ca.crt=example.com.crt` isn't creating the `kubernetes:` lines as was done in 1.20:

https://github.com/istio/istio/issues/49900?

### Version

```Text
master branch
```

**Comment by frankbu** [comment]
Maybe related to delta xDS? More details here: https://github.com/istio/istio.io/pull/14753#issuecomment-2008011373

**Comment by zirain** [comment]
I think related to https://github.com/istio/istio/issues/49900

**Comment by keithmattix** [comment]
#50406 will hopefully fixes; still needs a deep dive later though

**Comment by keithmattix** [comment]
Do we have the actual run errors? This may have been fixed

**Comment by ericvn** [comment]
I can quick enable the test and see if/how it fails.

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/14907 created.

**Comment by keithmattix** [comment]
Yeah it still fails; looks like the secret is still not properly being sent by the proxy. I think it's different from what @howardjohn  and I are chasing down, but I could be wrong

**Comment by zirain** [comment]
@keithmattix @howardjohn can you take a look at https://github.com/istio/istio/issues/49900?

**Comment by keithmattix** [comment]
Yeah I can fix the docs tomorrow

**Comment by keithmattix** [comment]
Fixed by istio/istio.io#14914

**Comment by ericvn** [comment]
As noted, this is fixed.
