### ISSUE TITLE
Gateway routing to Headless Service - no healthy upstream

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5005]
Using the istio-ingressgateway i created a virtualservice route to a headless service and always get "no healthy upstream" even though there are 5 healthy pods in the headless service

```
[2018-04-17T12:07:35.054Z] "GET /ui/ HTTP/1.1" 503 UH 0 19 0 - "174.82.221.133, 172.28.33.242" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "c78a639e-6151-965b-bf24-8d4072036ed5" "consul.my-cluster.weather.com" "-"
```

**Comment by ijsnellf** [comment]
Are you using Consul registry?

**Comment by nmnellis** [comment]
no, this is just a kv store for some of our apps.

**Comment by linsun** [comment]
this works for istio-ingress, would be good to get it fixed in 0.8 so users can move to the new gateway.

**Comment by hklai** [comment]
@GregHanson  How much more work is required for this? Any ETA?

**Comment by linsun** [comment]
@rshriram correct me if I'm wrong, I had thought this would work with v1alpha1 routing to headless service.

**Comment by rshriram** [comment]
gateway will not work with any v1alpha1 feature. I spoke to @nmnellis .. Routing to headless is not a critical feature for him, nor do I think it is a critical show stopper for anyone adopting Istio. Its a relatively corner case, that we can afford to fix in later point releases.

**Comment by linsun** [comment]
We are not asking gateway to work with v1alpha1 feature.  Nick was using the new gateway and the new route rule (virtual service).   If this is a limitation with the new gateway to not support headless service for 0.8, we have to provide this limitation in our doc and also a recommendation to our users.  I think the current recommendation is to use nginx iiuc which is what @nmnellis had to do.

cc @costinm @ZackButcher @frankbu @louiscryan @esnible  FYI. I'm okay to drop the release block tag if others are okay.

**Comment by rshriram** [comment]
From my experience looking at, answering, troubleshooting 100s of issues on the mailing list, I have yet to see a pattern emerge that asks for direct routing to headless services via ingress. So, IMO, this is not a blocker. But if you feel this is a critical show stopper feature for Istio, please contribute or add more developer resources, as our current bandwidth is small/ focusing on the key items listed here #4791.

Another thing: the release block tag should be assigned by the working group leads, who have full knowledge of the code/issues involved and are supposed to keep track of the critical vs non critical use cases. Every issue is dear to the person who posts it, but working group leads have to prioritize. If we tag every minor issue as a release blocker, we cannot expect to make monthly or timely releases :).

**Comment by nmnellis** [comment]
Yes this is not critical for us as we can use nginx as a workaround

**Comment by liamawhite** [comment]
@nmnellis is this still an issue?

**Comment by rshriram** [comment]
Thinking more about this, Gateway not being able to route to a headless service is semantically correct. Headless services/stateful sets are inherently peer-to-peer communication based, without any client-side load balancing that is typical of other services. Routing to a headless service via a Gateway implies that you are asking hte Gateway to perform client side load balancing to what is inherently a direct pod to pod communication system, by randomly selecting a pod. That doesn't make much sense in this context.

It used to work for Istio ingress because we didn't pay full attention to the semantics (i.e. it was actually a bug).

**Comment by andraxylia** [comment]
@rshriram should we close this issue if it does not make sense semantically?

There was a discussion in the env meetings about headless services not working, trying to get the full picture.
