### ISSUE TITLE
503 no healthy upstream 

### ISSUE THREAD

**Issue by santoshkumarkanithi** [istio/istio#50058]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are experiencing connection drops following the restart of the istio-system namespace. Older connections to the pod are being terminated at the ingress level with a 503 Unavailable (UH) status, signifying the absence of a healthy upstream. Concurrently, new connections are being successfully established. Our environment is running on Istio version 1.21.
Following the restart of the application pods, they successfully reestablished connections.

### Version

```Text
current version of istio  1.21.0
```

**Comment by hzxuzhonghu** [comment]
Is this always producible? 503UH means not healthy upstream, so it reflects the eds endpoints is empty.  So can you check istiod logs to see whether there is some kind of `initial sync timed out `
