### ISSUE TITLE
proposal: support customized spiffeId format

### ISSUE THREAD

**Issue by doujiang24** [istio/istio#50064]
Background:
We are migrating our existing large-scale north-south gateway from Nginx to Istio/Envoy, at Ant Group.
We want to enhance Istio to support our scenario without hacking the existing Istio core codebase. 

Here is a case:
`ParseIdentity` only supports the standard spiffe ID, but we have a customized format.
https://github.com/istio/istio/blob/master/pkg/spiffe/spiffe.go#L65

Here is my thought:
1. introduce an interface:
```
type SpiffeIdParser interface {
    Parse(s string) (domain, namespace, serviceAccount string, err error)
}
```

2. and register the existing logic in `ParseIdentity` as the default `SpiffeIdParser`.

So that we could register our customized spiffe id parser, without hacking Istio.

Any suggestions are welcome, thanks!

**Comment by keithmattix** [comment]
This approach would still require a fork. My recommendation would be a configurable url template with named variables that correspond to the service account and namespace. I do agree though that this needs to be solved

**Comment by doujiang24** [comment]
Thanks @keithmattix , url template would be simple and works in most scenarios.
but in our scenario, there are multiple versions of spiffeId format, so, we need to configure multiple url templates, which would also work for us.

A fork is acceptable and desired for us, maybe we can support registering `SpiffeIdParser` interface first?
It gives us the ability to customize more flexibly.

**Comment by alpha-baby** [comment]
> Thanks @keithmattix , url template would be simple and works in most scenarios. but in our scenario, there are multiple versions of spiffeId format, so, we need to configure multiple url templates, which would also work for us.
> 
> A fork is acceptable and desired for us, maybe we can support registering `SpiffeIdParser` interface first? It gives us the ability to customize more flexibly.

i agree, Registering `SpiffeIdParser` will be more flexible.

**Comment by lhanjian** [comment]
Maybe there are too many places in istio that can be easily and cleanly extended through the interface

**Comment by keithmattix** [comment]
#43105 has a lot more discussion/context on custom spiffe formats, though it doesn't seek to necessarily address the forking use case. I imagine any kind of progress here would result in a new interface so I'm inclined to close this issue in favor of the ongoing discussion

**Comment by doujiang24** [comment]
Hi @keithmattix , sorry for the late, I'm happy to take non-interface ways, i.e. multiple url templates.
An interface is just a prefered choice for us, since we already need a fork based on othe requirements.

So, do you think multiple url templates is accepted? if yes, I would like to have a try, thanks~

**Comment by keithmattix** [comment]
Not stale

**Comment by howardjohn** [comment]
I think for the general purpose case of customized ID we are tracking in https://github.com/istio/istio/issues/43105. The project is not currently making generic interfaces to make forking Istio easier.
