### ISSUE TITLE
Istio 1.21 Ambient + Microk8s fails on CNI Install

### ISSUE THREAD

**Issue by goafabric** [istio/istio#50063]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio Ambient CNI Installation fails a little non deterministically on latest Microk8s 1.29.2.
--- cut ---
`2024-03-22T15:01:09.174602Z`	warn	install	Istio CNI is configured as chained plugin, but cannot find existing CNI network config: no networks found in /host/etc/cni/net.d
2024-03-22T15:01:09.174611Z	info	install	Waiting for CNI network config file to be written in /host/etc/cni/net.d..`
--- cut ---

Also See the complete Log attached.
[logs-from-install-cni-in-istio-cni-node-6jgg9.log](https://github.com/istio/istio/files/14730851/logs-from-install-cni-in-istio-cni-node-6jgg9.log)

It seems to always install on a fresh linux machine, I verified this with MultiPass.
But if an older version of Microk8s was installed and removed, it fails ...
I tried that in a "real linux machine"

I've found a similar older issue, which might or might not relate, because Istio Ambient evolved a lot since then:
https://github.com/istio/istio/issues/41153

Any Hint how to fix this ?

### Version

```Text
istio version : 1.21.0
kubectl version : v1.29.1
microk8s version: v1.29.2
```

**Comment by xocodergit** [comment]
i think here is the reason below: (copied from https://microk8s.io/docs/change-cidr)

```
Kubernetes requires a CNI to configure the network namespaces and interfaces of pods. CNI configuration comprises of two things:

One (or more) conflist files (in JSON format) describing the CNI configuration. This configuration is typically found at /etc/cni/net.d. **In a MicroK8s cluster, the configuration path is instead /var/snap/microk8s/current/args/cni-network**.
CNI binaries, which implement the CNI specification. These binaries are typically found at /opt/cni/bin. In a MicroK8s cluster, the binaries are instead installed under /var/snap/microk8s/current/opt/cni/bin.
```

the Istio CNI parameter "mounted-cni-net-dir" can be use to specify the directory which contains cni conflist file on the node. you may try add the parameter `--mounted-cni-net-dir=/var/snap/microk8s/current/args/cni-network` into arg list of CNI DaemonSet

**Comment by goafabric** [comment]
@xocodergit 
thx 4 your reply .. and you maybe right .. the cni config can only be found inside the /var/snap directory
but can you explain how to exactly change the deamon set ?

I tried to simply patch the deamonset via the Kubernetes dashboard like below ... but this didn't solve the problem

containers:
        - name: install-cni
          image: docker.io/istio/install-cni:1.21.0
          command:
            - install-cni
          args:
            - >-
              --log_output_level=default:info,cni:info
              --mounted-cni-net-dir=/var/snap/microk8s/current/args/cni-network

**Comment by goafabric** [comment]
This will do the trick
istioctl install -y --set profile=ambient--set values.cni.cniConfDir=/var/snap/microk8s/current/args/cni-network --set values.cni.cniBinDir=/var/snap/microk8s/current/opt/cni/bin -f ./templates/meshconfig.yaml

So thx 4 pointing into to right direction .. the only question is, why it seems to be working on a fresh linux install with microk8s 1.29 .. but I could eventually reproduce and take a look at the directories

Also .. does it have to be like this for microk8s .. or could the install-cni container eventually autodetect that ?

No matter what .. excellent work on ambient mesh ! .. The Benefits of Istio, without having the 50MB Sidecar is a huge thing

**Comment by sando38** [comment]
For the record: I also saw the error message from the initial post, when using `k3s` deployed with this command

```bash
MYSECRET='iMbNehKnok2TzFbuc7sZPDhKv7tboSSoF6xj8mLKXz8snTaRFXdAW9YceN'
curl -fL https://get.k3s.io | K3S_TOKEN=${MYSECRET} INSTALL_K3S_VERSION=1.29.2-k3s1 \
    sh -s - server \
    --disable traefik \
    --disable servicelb
```

Afterwards installed the Gateway CRDs from [here](https://istio.io/latest/docs/ops/ambient/getting-started/#download) and installed everything else from the [helm chart installation guide](https://istio.io/latest/docs/ops/ambient/install/helm-installation/).

**Comment by bleggett** [comment]
> This will do the trick istioctl install -y --set profile=ambient--set values.cni.cniConfDir=/var/snap/microk8s/current/args/cni-network --set values.cni.cniBinDir=/var/snap/microk8s/current/opt/cni/bin -f ./templates/meshconfig.yaml
> 
> So thx 4 pointing into to right direction .. the only question is, why it seems to be working on a fresh linux install with microk8s 1.29 .. but I could eventually reproduce and take a look at the directories
> 
> Also .. does it have to be like this for microk8s .. or could the install-cni container eventually autodetect that ?
> 
> No matter what .. excellent work on ambient mesh ! .. The Benefits of Istio, without having the 50MB Sidecar is a huge thing

Ah good catch @goafabric and @xocodergit - we should add this MicroK8S specific note to https://istio.io/latest/docs/ops/ambient/install/platform-prerequisites/

**Comment by ericvn** [comment]
I believe this is now documented. Please reopen if additional work is required.
