### ISSUE TITLE
`istioctl x describe` fails to retrieve gateway info

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#50074]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

when I use the commond `istio x describe svc httpbin`, it's doesn't display the corresponding gateway information. 

I followed the istio docs https://istio.io/latest/docs/setup/additional-setup/gateway/ for gateway installation,
and the usage of the ingress gateway was also according the the doc(https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/).

However , I'm unable to locate the corresponding gateway content.

### Version

```Text
$ istioctl version               
client version: 1.20.3
control plane version: 1.18.6
data plane version: 1.18.6 (9 proxies)
```

### Additional Information

$ istioctl x describe svc httpbin 
Service: httpbin
   Port: http 8000/HTTP targets pod port 80
Skipping Gateway information (no ingress gateway pods)

$ helm list -n istio-ingress                                       
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-ingressgateway    istio-ingress   1               2024-03-25 11:50:13.347348 +0800 CST    deployed        gateway-1.21.0  1.21.0  

$ istioctl kubectl get svc                 
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
httpbin      ClusterIP   10.233.63.1   <none>        8000/TCP   19d
kubernetes   ClusterIP   10.233.0.1    <none>        443/TCP    532d
$ istioctl kubectl get svc -n istio-ingress
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                      AGE
istio-ingressgateway   LoadBalancer   10.233.4.252   10.6.136.33   15021:31212/TCP,80:32624/TCP,443:31672/TCP   9m1s

$istioctl  kubectl get vs                  
NAME      GATEWAYS              HOSTS                     AGE
httpbin   ["httpbin-gateway"]   ["httpbin.example.com"]   7m58s

**Comment by chaseSpace** [comment]
Hi, I have a question. Which document describes can this command query gateway information related to the service?

in my case, it can only get dst and vs info:
```
./istioctl x describe svc go-multiroute                        
Service: go-multiroute
   Port: http 3000/HTTP targets pod port 3000
DestinationRule: go-multiroute for "go-multiroute"
   Matching subsets: v2
      (Non-matching subsets v1)
   Traffic Policy TLS Mode: ISTIO_MUTUAL
   load balancer/connection pool
VirtualService: go-multiroute
   Match:  when headers are test-version=v2
   Route to host "go-multiroute" subset "v2" with weight 20%
```
Without gateway info, same as istio version of your.

**Comment by nicole-lihui** [comment]
> Hi, I have a question. Which document describes can this command query gateway information related to the service?
> 
@chaseSpace 

Oh, this is a fun one! So, about `istioctl x describe`, the istio docs is really doesn't have a more detailed description. 
I had to do Sherlock-level digging in the source code(https://github.com/istio/istio/blob/master/istioctl/pkg/describe/describe.go#L168-L169).

Right now , it's a experimental feature -- you're not quite sure what you're gonna get.
But I believe it's crucial to provide users with more information through docs. This is what we should do next.

**Comment by hanxiaop** [comment]
@chaseSpace How did you set up your gateway?

**Comment by chaseSpace** [comment]
> @chaseSpace How did you set up your gateway?

Ingress: https://github.com/chaseSpace/k8s-tutorial-cn/blob/main/k8s_actions_guide/version1/istio_manifest/ingress-gwy.yaml
Vs: https://github.com/chaseSpace/k8s-tutorial-cn/blob/main/k8s_actions_guide/version1/istio_manifest/ingress-virtualsvc.yaml

**Comment by chaseSpace** [comment]
@nicole-lihui That's nice~ Maybe you can rebuild istio project to debug the function `printIngressInfo()`.

**Comment by nicole-lihui** [comment]
> Ingress: https://github.com/chaseSpace/k8s-tutorial-cn/blob/main/k8s_actions_guide/version1/istio_manifest/ingress-gwy.yaml
> Vs: https://github.com/chaseSpace/k8s-tutorial-cn/blob/main/k8s_actions_guide/version1/istio_manifest/ingress-virtualsvc.yaml

@chaseSpace There is another reason why you cannot see the relevant gateway information: 

If you need to display this gateway information, you've got two criteria to meet:
- The gateway instance is located in `istio-system` ns. (fixed in #50013)
- The gateway pod has the label `istio=ingressgateway`.

**Comment by nicole-lihui** [comment]
yep, I'm giving it a shot, step by step, to enhance this part `istioctl x describe`

**Comment by chaseSpace** [comment]
> The gateway instance is located in istio-system ns.
Thanks, I just corrected it.

**Comment by nicole-lihui** [comment]
this issue can be closed by https://github.com/istio/istio/pull/50013
