### ISSUE TITLE
A lot of intermittent UH errors on istio egress gateway

### ISSUE THREAD

**Issue by kalyanteja19** [istio/istio#50075]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

INFO 2024-03-25T08:56:41.897522475Z [resource.labels.containerName: istio-proxy] [2024-03-25T08:56:41.328Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" outbound|443||xxx.segment.xxx - xxxxx:8443 xxxxx:38532 xxxx.segment.xxx -

A lot of UH errors on istio egress gateway. We are seeing these errors as intermittent. Need your help to resolve this issue permanently.

We already set HPA for istio egress gateway.

### Version

```Text
istioctl version
client version: 1.18.7
control plane version: 1.18.7
data plane version: 1.18.7 (1212 proxies)

kubectl version --short
Client Version: v1.26.10
Server Version: v1.26.10
```

**Comment by chaseSpace** [comment]
Hi, `UH` means unhealthy upstream. For egress gateway, this means the external service beyond egress gateway is unhealthy. You can use `istioctl pc endpoint  istio-egressgateway-$POD_ID.istio-system |grep segment` (segement is your svc partial name) to query the svc's healthy.

Moreover, your may be need to check destination rule(alias to DR) for the external service, because the healthy status provided by istioctl is queried according to the DR.

**Comment by kalyanteja19** [comment]
> Hi, `UH` means unhealthy upstream. For egress gateway, this means the external service beyond egress gateway is unhealthy. You can use `istioctl pc endpoint istio-egressgateway-$POD_ID.istio-system |grep segment` (segement is your svc partial name) to query the svc's healthy.
> 
> Moreover, your may be need to check destination rule(alias to DR) for the external service, because the healthy status provided by istioctl is queried according to the DR.
> 
> Check endpoint health detail:
> 
> ```
> istioctl pc endpoint  istio-egressgateway-$POD_ID.istio-system --cluster "outbound|443..." -ojson
> ```

Sure, thanks for the suggestion. We will check on this but we are facing this UH behaviour intermittenly for some URLs. I am not sure if istioctl really help here?

**Comment by chaseSpace** [comment]
There is a possiblity is that envoy default to reuse connection for HTTP/1.1, but the connection has been closed when it was reused. This case happened intermittenly is due to it only happened on a time window exists.

So now you can set `maxRequestsPerConnection=1` in DR manifest, this field's default value is zero means unlimited.

**Comment by kalyanteja19** [comment]
> One possibility is that the envoy defaults to reusing HTTP/1.1 connections upstream, but the connection has been closed when it was reused. This case happenes intermittenly is due to it only happenes on a time window exists.
> 
> So now you can set `connectionPool.http.maxRequestsPerConnection=1` in trafficPolicy of DR manifest, this field's default value is zero means unlimited. This setting may cause perf issues, and another solution is to set `retries.attempts=3` in the VR manifest, you can have a try on it~

Thank you so much for your response. We will check and update on it.

**Comment by kalyanteja19** [comment]
> One possibility is that the envoy defaults to reusing HTTP/1.1 connections upstream, but the connection has been closed when it was reused. This case happenes intermittenly is due to it only happenes on a time window exists.
> 
> So now you can set `connectionPool.http.maxRequestsPerConnection=1` in trafficPolicy of DR manifest, this field's default value is zero means unlimited. This setting may cause perf issues, and another solution is to set `retries.attempts=3` in the VR manifest, you can have a try on it~

We are not able to resolve this UH errors. 

We are planning to route the traffic through NSG/ firewall along with istio service entry. During the process, when adding individual domains, it is working fine. But with the wildcard domains, this is not working. Any suggestions on it?

Below error when we use wildcard on istio service entry with*.facebook.com

/ # curl
https://www.facebook.com/
-Iv
*   Trying 157.240.229.35:443...
* Connected to
[www.facebook.com](https://www.facebook.com/)
(157.240.229.35) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to
[www.facebook.com:443](https://www.facebook.com/)
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to
[www.facebook.com:443](https://www.facebook.com/)

**Comment by chaseSpace** [comment]
You might paste curl client pod's `istio-proxy` log here.

**Comment by kalyanteja19** [comment]
> You might paste container `istio-proxy` log of curl client pod here. See also https://istio.io/latest/docs/tasks/observability/logs/access-log/#using-mesh-config to open access log.

<img width="755" alt="image" src="https://github.com/istio/istio/assets/53315599/468d5a73-d004-44d2-b380-48f0027099c0">

**Comment by kalyanteja19** [comment]
@howardjohn , Can you help me on this issue? @chaseSpace

**Comment by kalyanteja19** [comment]
> @howardjohn , Can you help me on this issue? @chaseSpace

Hi Team,
Can anyone help here?

**Comment by kalyanteja19** [comment]
> > @howardjohn , Can you help me on this issue? @chaseSpace
> 
> Hi Team, Can anyone help here? We are having more than huge clusters using wildcard model, hence need your suggestion at earliest.

Hi Team, any suggestions on this issue

**Comment by chaseSpace** [comment]
I am come back!

**Comment by chaseSpace** [comment]
Hey guy, I think i found some points. 

**Firstly**, if the host is a real external address(along with`MESH_EXTERNAL`), we should set `resolution` to `DNS` inside SE manifest, or the gateway will direct the traffic to itself in an infinite loop. This can be found with below context:

```
DNS resolution must be used in the service entry below. If the resolution is NONE, the gateway will direct the traffic to itself in an
 infinite loop. This is because the gateway receives a request with the original destination IP address which is equal to the service 
IP of the gateway (since the request is directed by sidecar proxies to the gateway).
```
From blog [Egress Gateways](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/).

**Secondly**, if we specified a real external wildcard prefix domain as host, we can only specify `resolution` as `STATIC`, and   `resolution` must not be `NONE`, it would cause infinite route loop. `NONE` only can be used with requested target already is a IP not a domain.

So here we need to add some endpoints, like below:
```
...
  location: MESH_EXTERNAL
  endpoints:
    - address: 198.18.0.5 # replace with real fb ip
```

Then we can access hosts matched with wildcard host on mesh container:

```
~ $ curl https://www.facebook.com -w '%{http_code}\n' -s -o /dev/null -L
200
```
And we can check out egress pod log:
```
[root@k8s-master ~]# kubectl logs -l app=istio-egressgateway -n istio-system --tail=1
{"x_forwarded_for":null,"start_time":"2024-05-23T03:15:15.117Z","connection_termination_details":null,"upstream_transport_failure_reason":null,"response_flags":"-",
"downstream_remote_address":"20.2.0.17:33030","duration":756,"user_agent":null,"response_code_details":null,"upstream_local_address":"20.2.0.14:48018",
"upstream_host":"198.18.0.5:443","path":null,"requested_server_name":"www.facebook.com","request_id":null,"upstream_service_time":null,
"method":null,"authority":null,"downstream_local_address":"20.2.0.14:8443","response_code":0,"upstream_cluster":"outbound|443||*.facebook.com",
"bytes_received":860,"bytes_sent":73988,"protocol":null,"route_name":null}
```

Well, i think also this config method is not a good practice, so it may not be recommend for wildcard prefix host usage. I would expect istio expert to clarify it.

**Comment by kalyanteja19** [comment]
> Hey guy, I think i found some points.
> 
> **Firstly**, if the host is a real external address(along with`MESH_EXTERNAL`), we should set `resolution` to `DNS` inside SE manifest, or the gateway will direct the traffic to itself in an infinite loop. This can be found with below context:
> 
> ```
> DNS resolution must be used in the service entry below. If the resolution is NONE, the gateway will direct the traffic to itself in an
>  infinite loop. This is because the gateway receives a request with the original destination IP address which is equal to the service 
> IP of the gateway (since the request is directed by sidecar proxies to the gateway).
> ```
> 
> From blog [Egress Gateways](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/).
> 
> **Secondly**, if we specified a real external wildcard prefix domain as host, we can only specify `resolution` as `STATIC`, and `resolution` must not be `NONE`, it would cause infinite route loop. `NONE` only can be used with requested target already is a IP not a domain.
> 
> So here we need to add some endpoints, like below:
> 
> ```
> ...
>   resolution: STATIC
>   location: MESH_EXTERNAL
>   endpoints:
>     - address: 198.18.0.5 # replace with real fb ip
> ```
> 
> Then we can access host matched with wildcard host on mesh internal container:
> 
> ```
> ~ $ curl https://www.facebook.com -w '%{http_code}\n' -s -o /dev/null -L
> 200
> ```
> 
> And we can check out egress pod log:
> 
> ```
> [root@k8s-master ~]# kubectl logs -l app=istio-egressgateway -n istio-system --tail=1
> {"x_forwarded_for":null,"start_time":"2024-05-23T03:15:15.117Z","connection_termination_details":null,"upstream_transport_failure_reason":null,"response_flags":"-",
> "downstream_remote_address":"20.2.0.17:33030","duration":756,"user_agent":null,"response_code_details":null,"upstream_local_address":"20.2.0.14:48018",
> "upstream_host":"198.18.0.5:443","path":null,"requested_server_name":"www.facebook.com","request_id":null,"upstream_service_time":null,
> "method":null,"authority":null,"downstream_local_address":"20.2.0.14:8443","response_code":0,"upstream_cluster":"outbound|443||*.facebook.com",
> "bytes_received":860,"bytes_sent":73988,"protocol":null,"route_name":null}
> ```
> 
> Well, i think also this config method is not a good practice, so it may not be recommend for wildcard prefix host usage. I would expect istio expert to clarify it.

Thank you @chaseSpace , we will for istio team suggestion on this issue
