### ISSUE TITLE
More improvements for istioctl analyze to help diagnose TLS certificate issues (or other doc/logging fixes)

### ISSUE THREAD

**Issue by SJrX** [istio/istio#50070]
Lol I got bit by the same thing that bit me in #43891 as I was creating another ingress and the improvements implemented in #43921 didn't really help.

I was doing the following:
1. Declaring a new gateway and istio-ingressgateway in a brand new namespace called longhorn
2. Had secrets declared in a `longhorn-tls` secret.

Curl would give me:

```
curl: (35) Recv failure: Connection reset by peer
```

If I turned off tls redirection then HTTP would work, but HTTPs didn't work.

For some reason I thought that in #43891 was due to an expired cert, and so didn't think to look back at it, since I knew the TLS certs were fine, and double checked that (it is in fact the same cert)

### Feature Request(s)
1. Log a warning with `istioctl analyze` if the secret status on a proxy is `WARMING` or `false`. 
   * This might be transient, but simply saying "Proxy/Deployment does not have secret" would have saved me an hour trying to narrow down that it was a cert issue.
   *  I think this was suppose to be done as part of #43891 (https://github.com/istio/istio/issues/43891#issuecomment-1466172006) , but even in 
2. If you don't have a Service Account, even tracing logs are limited (you will see the following once):
```
2024-03-24T18:54:09.590162Z	warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:130	gRPC config: initial fetch timed out for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret	thread=16
```

Then on every request

```
2024-03-24T18:55:21.945692Z	debug	envoy filter external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:137	tls:onServerName(), requestedServerName: longhorn.private.sjrx.net	thread=27
2024-03-24T18:55:21.945773Z	debug	envoy config external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:456	Create NotReadySslSocket	thread=27
```

I'm not sure if everything should work, and be ready if you can't get the TLS Cert, but it'd be nice if the side car proxy got an error saying permission denied instead of a timeout. Eventually I looked at istios logs and saw a permission error:
```
2024-03-24T18:53:54.661429Z     warn    ads     proxy istio-ingressgateway-845bcf49dc-rzfrn.longhorn-system attempted to access unauthorized certificates longhorn-tls: default/longhorn-system is not authorized to read secrets:
```
  I guess if the service account for a proxy doesn't have permission it'd be nice if it just said this. I know in #43891 when I raised this before @hanxiaop said 

> IMO analysis involves analyzing configurations to identify any incorrect Istio-related configurations that users may not be aware of. The scenario you described sounds more like debugging processes, which would be better suited for a debug session in the documentation.  (https://github.com/istio/istio/issues/43891#issuecomment-1465425419) 

But this seems like Istio configuration not debugging. It isn't Kubernetes rejecting the read of the secret, it is istio doing it here https://github.com/istio/istio/blob/master/pilot/pkg/xds/sds.go#L298. 

I did skim a bunch of documentation today on Istio's site but I just can't even find where this requirement is documented.

3. Please add a mention to the to the [Traffic Management Problems documentation](https://istio.io/latest/docs/ops/common-problems/network-issues/#tls-configuration-mistakes) , there is just no mention of a need of a Service Account, and on the few pages I skimmed nothing. 

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

Thank you!

**Comment by hanxiaop** [comment]
@SJrX Thanks for the feedback!

Currently, `istioctl analyze` does not actively send requests to retrieve proxy configurations - it only checks static resource configs. Since fetching the proxy configuration can be quite slow in large clusters and will lead to significant resource consumption, we need to find a way to avoid this in in-cluster analysis before we can proceed. Right now I think you can use `istioctl pc secret` to inspect the status of secrets.

For 2, it seems reasonable to me.

**Comment by SJrX** [comment]
I guess I don't fully understand the boundary of how things work and the responsibility between Gateway, and everything else, but maybe if for a Deployment of gateway, has a match label for an ingress gateway, has a TLS credential, and the associated ServiceAccount doesn't have permission istioctl analyze could flag it, that seems like a static configuration error.

Thank you for your response.

**Comment by hanxiaop** [comment]
Yes for the service account, istioctl can send a warning message.
