### ISSUE TITLE
istio support pilot-discovery KubeController to use server side filter

### ISSUE THREAD

**Issue by lhanjian** [istio/istio#50084]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
We have a discoverySelector that uses an objectFilter, which in turn employs a client-side filter. However, if we have a 1,200,000 Pod (where Istio might have 50GB RAM), Istio could potentially encounter an out-of-memory (OOM) situation when the client-side filter is running. To mitigate this, we need to utilize a server-side filter to avoid reading unnecessary data from the API server.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by lhanjian** [comment]
![image](https://github.com/istio/istio/assets/3404496/b4afdb5d-765f-4f53-ae8b-d00729fe977b)

This modification is ugly, but it works,

How can we implement an elegant server side filter?

**Comment by howardjohn** [comment]
The Discoveryselector as implemented today is impossible to do server side. We could introduce a simpler API like you did above in theory.

What does 120W pods mean? 120Million?

**Comment by wulianglongrd** [comment]
> What does 120W pods mean? 120Million?

120w=1.2Million, `w` is a counting unit commonly used in China, 1w=10k=10000

**Comment by lhanjian** [comment]
> The Discoveryselector as implemented today is impossible to do server side. We could introduce a simpler API like you did above in theory.
> 
> What does 120W pods mean? 120Million?
my poor english. 1,200,000 

we need a proposal?
this proposal does not conflict with discoverySelector and can be used at the same time?

**Comment by lhanjian** [comment]
The first step，I may consider filter out namespaces/services/endpointslices/pods in pilot/pkg/serviceregistry/kube/controller/controller.go firstly

They are key to reducing memory waste.

But we have too many kclient.NewFiltered to shared our informer cache, 
Gateway Controller/Deployment Controller/Ingress Status Controller/Namespace Controller/.....

**Comment by hzxuzhonghu** [comment]
> However, if we have a 1,200,000 Pod (where Istio might have 50GB RAM

How could it possible, i think we have done some optimization like remove useless fields. Let me check where it is

**Comment by hzxuzhonghu** [comment]
Yes, find it. `StripPodUnusedFileds`

**Comment by hzxuzhonghu** [comment]
What i can tell is golang is not a memory saving language, even some heap is unused, it may not return back to os

**Comment by hzxuzhonghu** [comment]
I donot think so, previously we donot even watch pod, and I remembered we use metadata informer for node. 

The memory cost is still very high if there are huge amount of proxies, and from the flame, There is no evidence informer cache cost most of the memory. IIRC, our test showed  most mem costed by marshal/unmarshal proto

**Comment by lhanjian** [comment]
> I donot think so, previously we donot even watch pod, and I remembered we use metadata informer for node.
> 
> The memory cost is still very high if there are huge amount of proxies, and from the flame, There is no evidence informer cache cost most of the memory. IIRC, our test showed most mem costed by marshal/unmarshal proto

Tks for your information!

I use pprof to analyze heap.

Is this the proto you mentioned? A huge unmarshal

![image](https://github.com/istio/istio/assets/3404496/b4f513f7-e4b9-4bff-8c32-39f2bf4249ea)

But it can also be optimized through server side filter.
When I add a server side filter to istio， unmarshal is eliminated from the source

**Comment by howardjohn** [comment]
why is ObjectMeta like 90% but the spec is 4%? that seems quite odd

**Comment by lhanjian** [comment]
> why is ObjectMeta like 90% but the spec is 4%? that seems quite odd

I done a pprof 3min ago. Not so different.
![image](https://github.com/istio/istio/assets/3404496/701bd222-28c1-4d27-9411-9cf3bee10331)

I guess, because our pods have so many labels and annotation.

if direct access a pod json from APIServer HTTP API. 1 pod json cost 50000bytes.

**Comment by hzxuzhonghu** [comment]
Isn't StripPodUnusedFields too late, it is called after receiving from kube-apiserver, but just before store it in local cache.

I just think the above flame profiling is during an idle time, when no xds push needed. Once xds psuh happen，it should be quite different from my previous investigation

**Comment by lhanjian** [comment]
> Isn't StripPodUnusedFields too late, it is called after receiving from kube-apiserver, but just before store it in local cache.
> 
> I just think the above flame profiling is during an idle time, when no xds push needed. Once xds psuh happen，it should be quite different from my previous investigation

yes, there is no envoy connected to istio.

Tks for your suggestion, i will analyze istio later when xDS pushing.

**Comment by howardjohn** [comment]
having 25gb of Pod seems like it's just not going to work, full stop. I am not sure I understand why you have so many labels. How does Kubernetes itself function?

**Comment by lhanjian** [comment]
> having 25gb of Pod seems like it's just not going to work, full stop. I am not sure I understand why you have so many labels. How does Kubernetes itself function?

Our K8s works as usual. 
Our Kube-master works on 768GB memory VM and Relational database which supports etcd api, 
so our single k8s work as expected with 10000Nodes with 200000 Pods.
Our apiserver typically consumes 200GB RAM, it has been running for at least 4 years.

The reason i hacked a server side filter for istio, because i need istio running on multi cluster(4+ k8s clusters,1000000Pods+).And our k8s SRE promised "Not a problem for us".

Next week or the Next Next week, we will test istio on 4+ k8s clusters.

Right now, our problem is just the total number of pods.

Our real problem may be that 20W+ Pods need to be stored in the istio ingress gateway. And there may be more than 5,000+ HTTP routing entries

We plan to use Istio+Envoy (with our golang plugin) as the Centralized gateway to host the services of our applications that require internet ingress.

My teammates have more than 10 years of experience in using nginx to build large-scale centralized L7 gateways, and now we have invested more than ten man-months manpower in preparing to switch to Istio+Envoy (WithGolangFilter).

**Comment by howardjohn** [comment]
Got it, thanks for the context. Is the only large scale aspects the Nodes and Pods, or others as well? 5000 HTTP Routes seems relatively small, are there millions of services as well though? Or a few large services?

Do you only need to filter pods, or other resources as well?

One thing that may bloat things is managedFields. It may be worthwhile to filter that in some way _on the server side_. Kubernetes itself doesn't support this.

Depending on your needs, it might be feasible to have a proxy in front of the api-server that prefilters, removes things like managedFields, etc. This may be overkill though.

QQ - you mention Istiod takes 5min to startup. How does kubernetes controller-manager fare?

Do you have more profiles? Preferably with CPU profiles during startup, and the raw profile instead of image.

Overall, I think Istio will not scale to this level out of the box, but its plausible we can get there with some work.

Thanks!

**Comment by lhanjian** [comment]
> Got it, thanks for the context. Is the only large scale aspects the Nodes and Pods, or others as well? 5000 HTTP Routes seems relatively small, are there millions of services as well though? Or a few large services?
> 
> Do you only need to filter pods, or other resources as well?
> 
> One thing that may bloat things is managedFields. It may be worthwhile to filter that in some way _on the server side_. Kubernetes itself doesn't support this.
> 
> Depending on your needs, it might be feasible to have a proxy in front of the api-server that prefilters, removes things like managedFields, etc. This may be overkill though.
> 
> QQ - you mention Istiod takes 5min to startup. How does kubernetes controller-manager fare?
> 
> Do you have more profiles? Preferably with CPU profiles during startup, and the raw profile instead of image.
> 
> Overall, I think Istio will not scale to this level out of the box, but its plausible we can get there with some work.
> 
> Thanks!

 Tks for your suggestions! I will inverstigate it.

**Comment by lhanjian** [comment]
> Got it, thanks for the context. Is the only large scale aspects the Nodes and Pods, or others as well? 5000 HTTP Routes seems relatively small, are there millions of services as well though? Or a few large services?

The reason for the small number of routes is that many pods do not actually need to be exposed to the ingress gateway, so the scale is not so large as the number of services. Services only have 100,000-.

> Do you only need to filter pods, or other resources as well?

_Endpoints/Services/_Secrets/IstioCRDs__
Because our metadata management platform cannot manage labels for namespaces, so we can't use DiscoverySelector in short term.
To avoid discovering resources created by others that we don’t care about, we may filter these CRDs.

> One thing that may bloat things is managedFields. It may be worthwhile to filter that in some way _on the server side_. Kubernetes itself doesn't support this.

managedFields has not found in our k8s. Seems It has been disabled.

> Depending on your needs, it might be feasible to have a proxy in front of the api-server that prefilters, removes things like managedFields, etc. This may be overkill though.

We already have a proxy to APIServer for the istio, but it's difficult to work with istio multiclusters(because it uses secrets to manage KubeConfig), so we don't use it in short term.

**Comment by howardjohn** [comment]
Hmm, how is ObjectMeta 3000x times more than podSpec? Especially if you do not have managedFields.

BTW I think the optimization in https://github.com/istio/istio/issues/50084#issuecomment-2031311990 may not necesarily work depending on the impl, it may not shrink the map to reclaim the memory.

**Comment by lhanjian** [comment]
> Hmm, how is ObjectMeta 3000x times more than podSpec? Especially if you do not have managedFields. Do you have like 1000s of annotations and labels?嗯，ObjectMeta 是 podSpec 的 3000 倍吗？特别是如果您没有 ManagedFields。您是否有数千个注释和标签？

Our K8s use `--feature-gates=ServerSideApply=false`，so managedFields been disabled.


![image](https://github.com/istio/istio/assets/3404496/6a17691f-fd43-44d7-a9bd-456e4389f8e5)


> BTW I think the optimization in [#50084 (comment)](https://github.com/istio/istio/issues/50084#issuecomment-2031311990) may not necesarily work depending on the impl, it may not shrink the map to reclaim the memory.顺便说一句，我认为#50084（评论）中的优化可能不一定有效，具体取决于实现，它可能不会缩小映射以回收内存。

Tks for your suggestion!
