### ISSUE TITLE
Istio randomly drops connections

### ISSUE THREAD

**Issue by owais** [istio/istio#50089]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We run a number of Elastic Search clusters in more than a dozen k8s clusters. We are rolling out istio to all these k8s clusters. Oddly we are running into a strange issue with istio + Elastic Search in one of our production clusters. It seems Elastic Search nodes keep losing connection with each other sending the cluster into Yellow state and causing some imbalance until the nodes find each other again and recover. 

We've since removed istio temporarily from elastic search nodes but this puts us out of compliance due to lack of EIT for Elastic Search nodes and its clients.

- We've verified that the k8s/EKS cluster, ES clusters, AWS VPC/networking and istio control are identical to other clusters that are not facing this issue.
- This happens irrespective of client traffic/load. Even a freshly deployed ES cluster without any clients faces the same issue.
- Connections drops seemingly randomly anywhere between 10 - 40 min mark
- Have not seen any UF,URX like errors in istio log lines at the time when connection drops
- The issue *only* surfaces when ES nodes have the istio sidecar.
- I suspected auto-mTLS handshake and tried Permissive, Strict and Disabled modes for mTLS and the issue kept surfacing in all three modes.

Elastic Search nodes throw the following error while as we don't see anything that stands out in istio logs:

```
zen-disco-node-failed({istiotest-es6-2}{Bj8Gq86XQRCEEHaQAJ21bQ}{zRJFDjVOSeWnMnL5efdtIg}{10.125.50.30}{10.125.50.30:9300}{xpack.installed=true, service=istiotest-es, zone=ap-southeast-2c, cell=ap-southeast-2c}), reason(transport disconnected)[{istiotest-es6-2}{Bj8Gq86XQRCEEHaQAJ21bQ}{zRJFDjVOSeWnMnL5efdtIg}{10.125.50.30}{10.125.50.30:9300}{xpack.installed=true, service=istiotest-es, zone=ap-southeast-2c, cell=ap-southeast-2c} transport disconnected], reason: removed {{istiotest-es6-2}{Bj8Gq86XQRCEEHaQAJ21bQ}{zRJFDjVOSeWnMnL5efdtIg}{10.125.50.30}{10.125.50.30:9300}{xpack.installed=true, service=istiotest-es, zone=ap-southeast-2c, cell=ap-southeast-2c},}
```

### Other potentially related issues

We're actually seeing a lot of TCP services experience similar disconnects but most of them are able to recover quick enough to not cause alert storms. This manifests very visibly for Elastic Search but we think the same issue affects the entire cluster. It's almost as if istio is closing connections periodically even though we are not seeing temporal patterns and disconnects seem random.

#### 1 hour default timeout
We faced a similar issue during our staging rollout but that turned out to be istio's default TCP timeout of 1 hour. We disabled that and the hourly disconnections went away. 

#### ES xpack security being incompatible with istio
Elastic Search has inbuilt encryption with xpack and they suggest it doesn't work with istio but our ES deployment has xpack security disabled so all communication is happening in plain text.

### Version

```Text
❯ istioctl version
client version: 1.20.3
control plane version: 1.18.7
data plane version: 1.18.7 (441 proxies)
```

### Additional Information

This is happening in a production cluster so not sure if I can share this publicly but more than happy to share it via slack or email.

**Comment by hzxuzhonghu** [comment]
There is some idle timeout settings in cluster connection pool, can be set via DestinationRule

```
The idle timeout for TCP connections. The idle timeout is defined as the period in which there are no bytes sent or received on either the upstream or downstream connection. If not set, the default idle timeout is 1 hour. If set to 0s, the timeout will be disabled. Idle timeout is not configured per each cluster individually when weighted destinations are used, because idleTimeout is a property of a listener, not a cluster. In that case, idleTimeout specified in a destination rule for the first weighted route is configured in the listener, which means also for all weighted routes.
```


And there is also http idle timeout in listener, which can be set via ISTIO_META_IDLE_TIMEOUT

**Comment by owais** [comment]
We have `ISTIO_META_IDLE_TIMEOUT` set to `0` cluster wide because istio was killing elastic, spark and some other idle connections. It was a similar issue but connections would die every hour. After setting `ISTIO_META_IDLE_TIMEOUT` to `0`, that issue got resolved and we never saw that again in any cluster.

This one does look very similar but so far we haven't seen any time pattern in connections getting killed and `ISTIO_META_IDLE_TIMEOUT` is already set to `0` for this cluster as well.

**Comment by hzxuzhonghu** [comment]
And did you also set DestinationRule tcp timeout?

**Comment by owais** [comment]
There are a handful of DestinationRules deployed only for services that Istio Ingress Gateway routes traffic to. None of them define any timeout rules and only configure load balancing. Rest of the services (95% of the cluster) do not have any destination rules applied.

**Comment by hzxuzhonghu** [comment]
you need to configure ConnectionPoolSettings_TCPSettings.IdleTimeout, otherwise the upstream connection can be closed one hour if idle

**Comment by owais** [comment]
I see. Thanks. Are you suggesting to do this for every single endpoint/service even though we have `ISTIO_META_IDLE_TIMEOUT` set to `0` globally already?

> otherwise the upstream connection can be closed one hour if idle

This was exactly what we experienced in staging clusters and we fixed it by disabling it globally using `ISTIO_META_IDLE_TIMEOUT`. At this time, all affected connections were dropped exactly every hour but right now they seem very random and sometimes drop as soon as within 10-15 mins after establishment.

**Comment by hzxuzhonghu** [comment]
>I see. Thanks. Are you suggesting to do this for every single endpoint/service even though we have ISTIO_META_IDLE_TIMEOUT set to 0 globally already?

Yes, they control differently. 

random 10-15 seems not from envoy/istio default setting, can you check whether the application itself close connection

**Comment by owais** [comment]
Apps are not doing it as most apps are affected by this and we have hundreds of very diverse apps, both first party and 3rd party like elasticsearch. It could be the root cause is somewhere in k8s/EKS/VPC but somehow it only manifests when a service has istio sidecar present.

**Comment by owais** [comment]
We are running 1.18 still and looks like `ConnectionPoolSettings_TCPSettings.IdleTimeout` was added in a later version. I'll try to start the upgrade process but that can take weeks. Any other things I can/should try or data I can gather that might help investigate?

**Comment by hzxuzhonghu** [comment]
You may dump all the xds configurations
