### ISSUE TITLE
e2e: test logs have improperly formatted printf

### ISSUE THREAD

**Issue by nlandolfi** [istio/istio#501]
improperly formatted printf in logs
```
W0725 20:39:30.798] I0725 20:39:30.797805    4355 testInfo.go:217] Fetched logs on %s
W0725 20:39:30.799] projects/istio-testing/logs/hook
```

**Comment by nlandolfi** [comment]
offending line: https://github.com/istio/istio/blob/7a9bc3a127a2930ed9ddc97f366c718c4a1c23c7/tests/e2e/framework/testInfo.go#L217

**Comment by nlandolfi** [comment]
should be Infof

**Comment by ldemailly** [comment]
my IDE (atom.io + goplus) lints me that kind of error - I wonder if we can find a linter and add it

**Comment by ldemailly** [comment]
fixed in https://github.com/istio/istio/pull/184

**Comment by nlandolfi** [comment]
nice!
