### ISSUE TITLE
(TLS passthrough) with istio 1.21.0 with k8's gateway api. Looks like TLS passthrough does not work. 

### ISSUE THREAD

**Issue by doddisam** [istio/istio#50101]
I am running istio 1.21.0 in (profile=minimal) with k8's gateway API. Looks like TLS passthrough does not work. Below is my Gateway config. My backend app seem to work only with passthrough. The same Gateway config seem to work with contour. is there any limitation with istio (gateway api) ?

Does TLS passthrough supported as of now in istio gateway api ? 

![image](https://github.com/istio/istio/assets/89137330/f05edfb7-05f8-48a6-a8ed-4a939cd84ac5)

TLSRoute
![image](https://github.com/istio/istio/assets/89137330/cf469c50-8d94-41ce-b043-7ae020f89d31)

_Originally posted by @doddisam in https://github.com/istio/istio/issues/47366#issuecomment-2020114779_

**Comment by howardjohn** [comment]
closing as this was resolved - thanks!
