### ISSUE TITLE
Issues with mixed case Host Names in Istio Resources not attached to expected routes

### ISSUE THREAD

**Issue by singamL887** [istio/istio#50118]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As per our analysis we understood that istio does bypasses the capital letters to proxy and envoy honours / enforces strict matching of letter case in the hosts field. You can get better context with the below example,
 
We have used Virtual Service to demonstrate the issue, below are the relevant logs. 
 
Every Service in the cluster creates a route with the port number it is associated to (in the given case, it is port 8000). This route has domain names which are created same as the service names (in this given case, httpbin.default.svc.cluster.local , httpbin.default.svc.cluster.local:8000 etc).
 
`apiVersion: v1
  kind: Service
  metadata:
    name: httpbin
    namespace: default
  spec:
    ports:
      - port: 8000
        name: http
    selector:
      app: httpbin`
 
- name: "8000"
...
  - domains:
    - httpbin.default.svc.cluster.local
    - httpbin.default.svc.cluster.local:8000
    - httpbin
    - httpbin:8000
    - httpbin.default.svc
    - httpbin.default.svc:8000
    - httpbin.default
    - httpbin.default:8000
    - 10.96.195.98
    - 10.96.195.98:8000
  ...
    route:
      cluster: outbound|8000||httpbin.default.svc.cluster.local
      
When there is a Virtual Service with host name which matches one of the domain names of the route, the Virtual Service get applied to the route.
 
`apiVersion: networking.istio.io/v1alpha3 
  kind: VirtualService
  metadata:
  name: httpbin
  namespace: default
  spec:
     hosts:
      - httpbin
     http:
 
    - route:
 
        - destination:
 
            host: httpbin
 
            subset: v1
 
          weight: 20
 
        - destination:
 
            host: httpbin
 
            subset: v2
 
          weight: 80`
          
`- name: "8000"
  - domains:
    - httpbin.default.svc.cluster.local
    - httpbin.default.svc.cluster.local:8000
    - httpbin
    - httpbin:8000
    - httpbin.default.svc
    - httpbin.default.svc:8000
    - httpbin.default
    - httpbin.default:8000
    - 10.96.195.98
    - 10.96.195.98:8000
	...
        weightedClusters:
          clusters:
          - name: outbound|8000|v1|httpbin.default.svc.cluster.local
            weight: 20
          - name: outbound|8000|v2|httpbin.default.svc.cluster.local
            weight: 80`
            
We tried to create a Virtual Service with mixed case hostname.

`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  hosts:
    - HTTPbin
  http:
    - route:
        - destination:
            host: httpbin
            subset: v1
          weight: 20
        - destination:
            host: httpbin
            subset: v2
          weight: 80`
          
As the host name in the above Virtual Service doesn't match with any of the domain names in the route 8000, this route won't get the updated with the routing rules in Virtual Service.

To have a domain name in the route which could match with hostname in the above Virtual Service (mixed case host name), we need to create a Service with mixed case name. This is not possible as it throws the following error "Invalid value: "HTTpbin": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')".

So we consider that in Virtual Services, either the host names should be converted to lower case explicitly, or it should restrict users to create mixed case host names similar to Service.

I think this also needs to be propagated to all the Istio resources which would contain the use of host names,

1. Virtual Service
2. Destination Rules
3. Service Entry
4. Gateway 

### Version

```Text
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (4 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by singamL887** [comment]
@howardjohn can you please check this.

**Comment by wulianglongrd** [comment]
> This is not possible as it throws the following error "Invalid value: "HTTpbin": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z](https://github.com/istio/istio/issues/%5B-a-z0-9%5D*%5Ba-z0-9%5D)?')".

How did you get this message? istio looks like no such check, and the hostname should be case sensitive when XDS translate.

**Comment by singamL887** [comment]
> > This is not possible as it throws the following error "Invalid value: "HTTpbin": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z](https://github.com/istio/istio/issues/%5B-a-z0-9%5D*%5Ba-z0-9%5D)?')".
> 
> How did you get this message? istio looks like no such check, and the hostname should be case sensitive when XDS translate (but I don't know if this is by design.).

I have got this message when trying to apply the following Service 

```
apiVersion: v1
kind: Service
metadata:
  name: HTTpbin
  namespace: default
spec:
  ports:
    - port: 8000
      name: http
  selector:
    app: httpbin
```

**Comment by keithmattix** [comment]
This is a Kubernetes validation: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names. Is there a reason you need mixed-case services?
