### ISSUE TITLE
Migrate grafana off angular panels

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50128]
https://grafana.com/developers/plugin-tools/migration-guides/migrate-angularjs-to-react

We did this for a few in https://github.com/istio/istio/pull/50125 and https://github.com/istio/istio/pull/50102 but there are many left

**Comment by snuggie12** [comment]
apologies as I presume you're already aware, but in the UI you can change all panels to "timeseries" and export the json. I only resorted to this after attempting to create some simple script and looking into jsonnet to see if it was simple. Neither option was like a 5 minute solution so it just seemed quicker to manually migrate the handful of dashboards we owned.
