### ISSUE TITLE
Option to allow invalid/expired client certs when Gateway ServerTLSSettings.TLSmode is OPTIONAL_MUTUAL

### ISSUE THREAD

**Issue by tapwaterbuffalo** [istio/istio#50148]
**Describe the feature request**

This request is to add a configuration to the [Gateway ServerTLSSettings](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) to optionally require valid client certs when the tls mode is OPTIONAL_MUTUAL.

Today, the client cert is validated and rejected if it is invalid (unknown ca, expired). The rationale here is that the client does not need to send a cert to be allowed in anyway.

The use case I am considering is primarily hard-to-update hardware devices. In a few specific cases (which we currently handle outside of istio), we need customer devices to continue working until we can get them all updated. We do this by examining the peer certificate issuer.

In such a case, I would expect we could use [downstreamSslConnection:peerCertificateValidated](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#peercertificatevalidated) along with issuerPeerCertificate and subjectPeerCertifcate in a lua filter on the Gateway to make a determination on the request.

**Describe alternatives you've considered**
I havent found a way to circumvent the client cert validation, it appears baked in. If I missed something, please enlighten me 😄 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I understand the request but am opposed to putting something like this into Istio unfortunately. The risk of API complexity and confusion, possibly leading users to accidentally use this *very unsafe* setting is not worth it IMO. I don't think Envoy can actually do this either (?). If there is enough desire to use this, I would recommend getting support in Envoy added then patching it in with an EnvoyFilter.
