### ISSUE TITLE
Enable the `ambient/getting-started` istio.io tests

### ISSUE THREAD

**Issue by ericvn** [istio/istio#50145]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Tests get (ex: https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_istio.io/14775/doc.test.profile-none_istio.io/1773380790281834496/artifacts/tests-setup-profile-none-f8b3f6/TestDocs/ops/ambient/getting-started/test.sh/test.sh/_test_context):
```
VERIFY FAILED snip_layer_7_authorization_policy_4 (timeout after 120s):
received:
"upstream connect error or disconnect/reset before headers. reset reason: connection termination"
expected:
"RBAC: access denied"
```

### Version

```Text
main istio branch
```

**Comment by linsun** [comment]
One thing I noted is this cmd needs to be updated:

```
kubectl logs ds/ztunnel -n istio-system  | grep inpod_enabled
```

as of latest master, this returns number of pods vs true|false.

```
Found 3 pods, using pod/ztunnel-lg4ft
```

**Comment by linsun** [comment]
Hi @ilrudie I tried to enable test in https://github.com/istio/istio.io/pull/14922 as it seem to work pretty well when i tested manually.

**Comment by ilrudie** [comment]
Sounds good. I will take a look at your pr shortly!

**Comment by ericvn** [comment]
This test has not been enabled, so re-opening.

**Comment by linsun** [comment]
Sorry I misunderstood the issue. I had thought it is the tests button in the doc, but it is not.  @ilrudie give this back to you :)

**Comment by ericvn** [comment]
Just enabling the tests to see if they maybe work in https://github.com/istio/istio.io/pull/14941

**Comment by ericvn** [comment]
There are test failures noted in that PR. One may be a needed test framework update, but also it seems that some renumbering was done in the snippets in the other PR which need to be pulled into the tests.

**Comment by ericvn** [comment]
@ilrudie You can start with my PR. It should have a good start for the test.sh, but might need some renumbering/changes in the gtw_test.sh. If my verify fix PR isn't merged, just grab the one line change in verify.sh to make headway.

**Comment by ilrudie** [comment]
@ericvn, ty.

**Comment by ilrudie** [comment]
Closed by https://github.com/istio/istio.io/pull/14953
