### ISSUE TITLE
Cannot connect Kiali web-ui in other hosts

### ISSUE THREAD

**Issue by chaseSpace** [istio/istio#50140]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This is my first time installing Kiali according to the [installation document][x1], and the installation was successful.

```
$ kubectl get svc kiali -n istio-system                    
NAME    TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
kiali   ClusterIP   20.1.26.170   <none>        20001/TCP   40m

$ ip addr
...
2: ens33: ...
    inet 192.168.31.2/24 brd 192.168.31.255 scope global ens33

$ kubectl port-forward svc/kiali 20001:20001 -n istio-system
Forwarding from 127.0.0.1:20001 -> 20001
Forwarding from [::1]:20001 -> 20001
```
Then i tested in localhost using curl, it's ok(200 OK). But it's always failed in another k8s node or others.

```
# in another node(192.168.31.3), 192.168.31.2 below is the ip of kiali node.

$ curl 192.168.31.2:20001
curl: (7) Failed connect to 192.168.31.2:20001; Connection refused

$ nc  192.168.31.2 20001
Ncat: Connection refused.
```
There is no firewall reason. I tested port `20001` using nc(ncat) command, and the result is successful.

[x1]: https://istio.io/latest/docs/ops/integrations/kiali/#installation

### Version

```Text
istioctl verison 1.20.3
```

**Comment by zirain** [comment]
add `--address 0.0.0.0` on port-forward, you should not use this expect for test.

**Comment by chaseSpace** [comment]
Thank you, I rarely use port forwarding option.
