### ISSUE TITLE
proxy: switch to Delta SDS

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#50153]
Rewrite node agent to use Delta SDS and limit istiod imports to improve #50134 
CC @keithmattix

**Comment by kyessenov** [comment]
I'm not sure why we need the entire Istiod xDS server for something tiny like SDS server. It shouldn't be hard to write a standalone SDS service - and this will can also help avoid whatever Delta issues manifested from Istiod.

**Comment by keithmattix** [comment]
I don't know that we need to duplicate the xDS logic though; does it make sense instead to keep the core istiod xDS library small/with minimal dependencies and continue to use it?

**Comment by kyessenov** [comment]
Sure, if you can manage to accomplish it. I took a look at it, and the structure has a dozen fields for all sorts of Istio configs. Even though all fields are empty, we link the code for those fields.

**Comment by howardjohn** [comment]
What is the relationship between Delta imports? I get why a rewrite to avoid the Istiod xDS server would help but not sure why Delta vs SotW matters there?

**Comment by kyessenov** [comment]
Doesn't matter directly, but it's easier to do Delta in node agent since secrets are permanent. We can ship that faster.

**Comment by howardjohn** [comment]
Before we go rewrite a bunch of critical code to trim dependencies a bit, can we make sure we have an implementable plan to do it fully? It doesn't make sense to add risk+complexity to write a new xDS server to trim Envoy imports if we just import them from somewhere else anyways.

**Comment by kyessenov** [comment]
AFAICT, SDS is the main remaining part of the sidecar agent that pulls much of pilot code. I can make it clear if you let me incrementally rule out the other parts, e.g. with #50155

**Comment by hzxuzhonghu** [comment]
I am not objected to rewriting sds or any other coupling component, but what i am worried about is how we can guarantee the evolution stability, we donot have a good test framework. we heavily depend on the integration test, which only include a limited number of cases. past several years experience tell us, there maybe some potential bugs we haven't figured out on xds. 

So can we do such work a small step by step.

**Comment by kyessenov** [comment]
@hzxuzhonghu The risks are inherent in switching to Delta. If you can find any other implementation for `DeltaSecrets` that is well tested, we can use that. I have no preference, as long as it has a small footprint. Neither Cilium, nor SPIFFE do, it appears. We can't use files unfortunately since we have the API bridge to CA providers.

**Comment by hzxuzhonghu** [comment]
Yes, delta is very risky, since making it default there are a lot of bugs found. I mean the step should be first: rewrite sds server, second migrate to delta

**Comment by howardjohn** [comment]
Can someone help me understand the benefit of switching to delta for sds? For the core istiod the benefits are clear (performance and possibly some functionality) but for SDS neither seem relevant?

**Comment by howardjohn** [comment]
If the real goal is to reduce binary size, then we should strongly consider alternatives like making the existing server import less things vs rewriting critical code from scratch

**Comment by kyessenov** [comment]
Yeah, it's fine to stick to 2) with SotW for the purpose of reducing the trusted base. A basic xDS routine, especially for SotW, is 100 lines of code, there's no need to make something too modular when it is easy to copy the code.

**Comment by kyessenov** [comment]
10x improvement is a goal, but getting it 2x smaller would be good.

**Comment by keithmattix** [comment]
10X is certainly _a_ goal but it seems dubious to me that we can make that happen without also cutting a great deal of the value that the agent brings, especially in the realm of security

**Comment by kyessenov** [comment]
@keithmattix 10x is a long term goal. I think we're very close to 2x, and it gets progressively harder for 10x because we have to re-architect some solutions. I don't agree that the agent adds any security benefits. It's mostly a patchwork for the capability gaps in either the environment (k8s?) or the proxy (Envoy).

For example:
* Wasm xDS proxy is definitely a hack to avoid implementing it properly in Envoy, e.g. https://github.com/envoyproxy/envoy/issues/33212.
* Various readiness gates could be done in Envoy, although this isn't taking much binary space.
* Several SDS providers are mostly legacy solutions and will be deprecated eventually. The environment can provide the secrets. They also should not be in the OSS build anyways, since Google ones are proprietary.
* Various STS indirections are also a Google-specific problem - OSS has no use for them.
* xDS proxying is pure overhead. There are some features that benefit, e.g. ProxyConfig reload, but that has nothing to do with xDS as most people understand it that programs the data plane.

**Comment by kyessenov** [comment]
@howardjohn @bleggett I wonder if we should instead switch to file delivery of certificates to Envoy instead of SDS because it's consistent with Kubernetes direction https://github.com/kubernetes/enhancements/pull/4318. The existing providers will be converted to using files, and can be converted to sidecars instead of an in-process module.

**Comment by bleggett** [comment]
> @howardjohn @bleggett I wonder if we should instead switch to file delivery of certificates to Envoy instead of SDS because it's consistent with Kubernetes direction [kubernetes/enhancements#4318](https://github.com/kubernetes/enhancements/pull/4318). The existing providers will be converted to using files, and can be converted to sidecars instead of an in-process module.

We could for sidecars, yes. Though it wouldn't really work for ambient.

I haven't seen any movement on that KEP recently. I'm not against it (though I did have some qs about the proposal) but I don't think adopting it really solves any specific problems we have - though I guess depending on how the KEP matures it could be an easier integration path with external workload CAs like SPIRE than the current CSI driver approach.

> I think there is some (at least _perceived_) desire to only keep private keys in memory rather than on disk (or over the network).
> 
> So we would need to analyze how important that is

+1, and aside from that, and assuming the KEP makes it in, realistically we'd have to keep SDS around for a while anyway.

If it makes it into K8S, and if it works as-well-as SDS in all cases, and if it makes integrating with other workload CAs (like SPIRE) simpler, then replacing SDS might make sense.

**Comment by kyessenov** [comment]
SG, we can park KEP4318 transition for later. AFAIK the mount is not really files, they are backed by FUSE. So from a security perspective, it's the same to read from a plaintext UDS with SDS or from a POSIX file with FUSE.
