### ISSUE TITLE
DestinationRule .spec.host does not support FQDN host names (ending with ".")

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#50168]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In a journey to reduce the number of DNS queries in our cluster (famous "ndots" problem with DNS and Kubernetes using ndots=5) I came across an interesting observation: When defining a DestinationRule (and a ServiceEntry) for an external domain, say `httpbin.org`, then even without active HTTP requests to this domain, DNS queries are made to it regularly (as per the Istio documentation for Envoy STRICT_DNS clusters).
That in itself is not a problem. The actual problem is that instead of first trying to resolve `httpbin.org`, due to Kubernetes' default /etc/resolve.conf ndots=5 and GKE using **6** search domains, we end up with 6 DNS queries to e.g. `httpbin.org.default.svc.cluster.local.` and `httpbin.org.svc.cluster.local.`, etc. until finally the DNS resolver will want to resolve `httpbin.org.`.

That can be mitigated by a few techniques:

Reducing ndots via a pod's `dnsConfig` to some lower value, say `1`, such that all hostname queries that have at least one dot in them will first try to resolve directly without going through the /etc/resolve.conf search list (ideal for external domains - not ideal for in-cluster service domains).

Another way to resolve the problem is to always use fully-qualified domain names (FQDN in the sense that the DNS system defines a FQDN: a domain name with a dot `.` as the last character.
This would result in the DNS resolver to not try the search list, but instead resolve this name as is. This would be _ideal_ for external domains, while in-cluster domains would still benefit from search list DNS queries for things like `http://myservice`, which must actually be queried as `myservice.default.svc.cluster.local.`.

Curl actually has no problems doing `curl http://httpbin.org./status/200`. It will lead to resolving `httpbin.org.` directly without the search list and everything works.

Now, I was trying to define a `DestinationRule` like so:
```yaml
spec:
  host: httpbin.org.
```

However, that is being rejected due to the host name not matching the regex. However, this regex does not allow to define a DNS FQDN host name (those ending with a `.` to make them resolve as is).

### Version

```Text
Istio 1.21.0
```

**Comment by wulianglongrd** [comment]
similar issue #50119

**Comment by kaiburjack** [comment]
not stale
