### ISSUE TITLE
TCP RST Packets Sent on WebSocket Connection Closure When Using Istio

### ISSUE THREAD

**Issue by nagavijayan-nagarathinam** [istio/istio#50176]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When running a WebSocket-based application within an Istio service mesh, TCP RST (Reset) packets are consistently observed upon initiating WebSocket connection closures from the client side. This behavior is observed only when the application is deployed within the Istio-enabled Kubernetes environment, suggesting that the presence of Istio might be influencing the TCP connection termination process in a way that deviates from the expected graceful closure using TCP FIN packets.

### Version

```Text
$ istioctl version
client version: 1.20.3
control plane version: 1.18.2
data plane version: 1.18.2 (149 proxies)

$kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.16-eks-508b6b3
```

### Additional Information

**Steps to Reproduce**

1. Deploy a WebSocket server and client application on a Kubernetes cluster with Istio service mesh enabled.
2. Establish a WebSocket connection between the client and server.
3. Initiate a connection closure from the client using the WebSocket .close() method.
4. Observe the network traffic using a tool like Wireshark or tcpdump.

Expected Behavior
The WebSocket connection closure initiated by the client should result in a graceful TCP connection termination, characterized by the exchange of TCP FIN packets between the client and server.

**Actual Behavior**
Instead of the expected TCP FIN packets signaling a graceful connection closure, TCP RST packets are sent, indicating an abrupt termination of the TCP connection. This behavior is only observed when the application is deployed within an Istio-enabled environment.

**Impact**
The unexpected sending of TCP RST packets may lead to potential issues with connection stability and reliability in production environments. It deviates from the standard practice of gracefully terminating TCP connections, potentially affecting client-side connection handling logic.

Server Code to Reproduce 

```
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 5000 });

wss.on('connection', function connection(ws) {
    console.log('A new client connected.');

    ws.on('message', function incoming(message) {
      console.log('received: %s', message);
      if (message === "Ping") {
        ws.send('Pong');
      }
    });
  
    ws.on('close', () => {
      console.log('Client has disconnected.');
      // Perform any cleanup or final operations here before the connection fully closes
    });
  });
```

Client Code to Reproduce [ Update Server URL/Service to connect ]

```const WebSocket = require('ws');
const readline = require('readline');

let ws = null; // WebSocket connection
let pingInterval = null; // Interval for sending Ping messages
let connectionOpenTime, connectionCloseTime;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function connectToServer() {
  if (ws !== null) {
    console.log('Already connected. Please disconnect before connecting again.');
    return;
  }

  connectionOpenTime = new Date(); // Record connection open time
  console.log(`Connection opened at: ${connectionOpenTime.toISOString()}`);
  
  ws = new WebSocket('ws://<server-code-service-url');

  ws.on('open', function open() {
    console.log('Connected to the server.');
    // Start sending Ping messages every 2 minutes
    pingInterval = setInterval(sendPing, 120000); // 120000 milliseconds = 2 minutes
  });

  ws.on('message', function incoming(data) {
    console.log(`Received: ${data}`);
  });

  ws.on('close', function close() {
    console.log('Disconnected from the server.');
    connectionCloseTime = new Date(); // Record connection close time
    console.log(`Connection closed at: ${connectionCloseTime.toISOString()}`);
    clearInterval(pingInterval); // Stop sending Ping messages
    ws = null; // Reset the connection
  });

  ws.on('error', function error(err) {
    console.error('Connection error:', err);
    ws = null; // Reset the connection on error
  });
}

function sendPing() {
  if (ws && ws.readyState === WebSocket.OPEN) {
    console.log('Sent: Ping');
    ws.send('Ping');
  } else {
    console.log('You are not connected to the server.');
    clearInterval(pingInterval); // Ensure ping interval is cleared if connection is not open
  }
}

function closeConnection() {
  if (ws) {
    console.log('Closing connection...');
    ws.close(1000, 'Client closed connection');
    // Note: Connection close time will be recorded in the 'close' event handler
  } else {
    console.log('You are not connected to the server.');
  }
}

connectToServer()
console.log('Type "connect" to connect to the server, "ping" to send a Ping message, or "disconnect" to close the connection:');
rl.prompt();

rl.on('line', (line) => {
  switch (line.trim()) {
    case 'connect':
      connectToServer();
      break;
    case 'ping':
      sendPing();
      break;
    case 'disconnect':
      closeConnection();
      break;
    default:
      console.log('Unknown command. Type "connect", "ping", or "disconnect".');
  }
  rl.prompt();
}).on('close', () => {
  console.log('Exiting client...');
  if (ws && ws.readyState === WebSocket.OPEN) {
    ws.close(1000, 'Client exited');
  }
  process.exit(0);
});

```

**Comment by jsirianni** [comment]
I believe I am seeing this issue in my environment.

**Comment by jsirianni** [comment]
It is disappointing to see that this issue did not even get a response.
