### ISSUE TITLE
proxy-config routes command doesn't have route entry for all k8s services

### ISSUE THREAD

**Issue by PGpmg** [istio/istio#50177]
While trying to apply default http retry policy using global mesh config while deploying the Istio, I have noticed that, proxy-config routes doesn't have route entry for all k8s services.
Retry policy is successful to the ones which are part of route entries.

Missing ones are listed as proxy-config listeners for a pod.
Could you please shed more light on how these missing ones are part of pod listeners and if I want to configure the http retry policy for them, how could I do it?

**Comment by howardjohn** [comment]
Likely these are not HTTP services at all? TCP services do not use route. See https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

Without more info its hard to say much more

**Comment by PGpmg** [comment]
Thanks for the reply.  All are HTTP services, some were detected as HTTP whereas others as TCP.
After explicitly mentioning the appProtocol: https in services, able to see them in routes.

Thanks for the help.
