### ISSUE TITLE
Proxy sync broken by SDS changes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50186]
https://github.com/istio/istio/pull/50183#issuecomment-2030188128

I assume from https://github.com/envoyproxy/envoy/commit/907e48ef5a48d2cfce2b4050c0e1d4498372c0e7

Looks like we are sending removes for SDS, and the cluster ends up stuck warming.

We assert `Secret is not supplied by SDS`, but we get `no healthy upstream`. I think the UH is because we switch from EDS to STRICT_DNS, but remove the endpoints from EDS (oops? might be its own subtle bug).

cc @ericvn @keithmattix

**Comment by keithmattix** [comment]
istiod sends a remove because the sidecar doesn't have k8s rbac access to the secret so it's signaling to the sidecar/sds client that the secret is unavailable. Before https://github.com/envoyproxy/envoy/commit/907e48ef5a48d2cfce2b4050c0e1d4498372c0e7, this indeed would've resulted in the "Secret is not supplied by SDS" error, but now the cluster would just remain warming. I'll update the tests

**Comment by howardjohn** [comment]
In SotW why does it get "Secret is not supplied by SDS" instead?

If we did not send a 'delete' but just never responded, would it be 'Secret is not supplied by SDS' for Delta?

**Comment by keithmattix** [comment]
This is TLS origination with a DR cert coming from istiod; wouldn't that be the delta flow?

**Comment by howardjohn** [comment]
I mean prior to 2 months ago when we used SotW everywhere

**Comment by keithmattix** [comment]
Ah yeah SotW would result in that error even now. The SotW version of the SDS request looks like `resources: []` which results in the missing SDS secrets error. Now that we're using delta, this looks like: `updated: [], removed: [kubernetes://...]` which is ignored

**Comment by howardjohn** [comment]
Behavior on the test:

SotW: UH for 15s, not cert after
Delta pre-change: no cert provided immediately
Delta post change: UH forever

This seems unexpected

**Comment by keithmattix** [comment]
envoyproxy/envoy#33362 should fix this

**Comment by keithmattix** [comment]
This is fixed
