### ISSUE TITLE
TestSimpleHTTPSandwich Test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50184]
https://prow.istio.io/view/gs/istio-prow/logs/integ-cni_istio_postsubmit/1774280229850714112

**Comment by stevenctl** [comment]
I'll keep an eye on it but I can't find any other recent occurrences in prow for either the CNI or ambient job and can't replicate locally yet.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50406/integ-ambient_istio/1778878701564334080 popped up again

**Comment by stevenctl** [comment]
```
2024-04-12T20:27:48.093751Z	warn	access	connection failed	src.addr=10.244.1.11:49452 dst.addr=10.96.197.198:80 direction="outbound" error=unknown waypoint: unable to determine waypoint upstream
```

Looking at WDS, the workload/service point at `10.96.29.55` as the Waypoint, but we don't have an entry for that Service.

**Comment by howardjohn** [comment]
Probably fixed by one of my recent PRs then
