### ISSUE TITLE
Allow local file as jwks datasource in `RequestAuthentication`

### ISSUE THREAD

**Issue by ks-yim** [istio/istio#50196]
**Describe the feature request**

Currently, `RequestAuthentication` API only allows "remote uri" and "inline string" for jwks datasource.

This works well with asymmetric JWT signing algorithms with which public jwks is used for signature verification, but when we use it with symmetric key signing algorithms(e.g. HS256) where jwks is always private and thus needs to be secured, there's no easy way to load jwks from a secure place like k8s secret.

Adding a feature to load jwks from a local file will make it a lot easier to use `RequestAuthentication` to verify JWTs signed by symmetric key algorithms in a secure way without the risk of exposing credentials in plaintext.
(by mounting k8s secret to `istio-proxy` container and referencing the mounted file in `RequestAuthentication`)

**Describe alternatives you've considered**

Envoy's [jwt_authn filter](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/jwt_authn/v3/config.proto#L180) allows specifying a local file as jwks datasource as described in the following example.

Example:
```yaml
providers:
  origins-0:
    local_jwks:
      filename: /etc/istio/secrets/jwks.json
```

We can extend [RequestAuthentication](https://github.com/istio/api/blob/master/security/v1/jwt.proto#L61) API so that users can specify `jwksFilename` in `JWTRule` which will then be mapped to Envoy `jwt_authn` filter's `local_jwks.filename` property.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
How do you plan to get the file? Is this a `Secret` that is mounted?

**Comment by ks-yim** [comment]
@howardjohn Yes, jwt_authn filter can pick up the file mounted to `istio-proxy` container.
I tried this idea by editing `jwt_authn` filter added by `RequestAuthentication` using `EnvoyFilter` API, and confirmed that it's working.
