### ISSUE TITLE
Service Account SAN added for simple TLS origination at the sidecar

### ISSUE THREAD

**Issue by wtzhang23** [istio/istio#50193]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

For "External" registries, Istiod will add the SPIFFE URI to the ClientTlsSettings' SubjectAltNames when using the `SIMPLE` or `MUTUAL` TLS modes (see source [code](https://github.com/istio/istio/blob/15a79ad4f265ac26359abffaad40cb14330fa45b/pilot/pkg/networking/core/v1alpha3/cluster_tls.go#L196-L200)). For use cases outside of SPIFFE federation, this leads to certificate validation error when defining a DestinationRule without an explicitly-set list of SANs, `ENABLE_AUTO_SNI=false`, and `VERIFY_CERTIFICATE_AT_CLIENT=true`.

Possible fixes:
Due to possible security regressions should this behavior be removed
* A Pilot environmental variable toggle for Istiod not to add this
* An explicit field in DestinationRule to not validate SANs but validate certificate signatures (finer-grained InsecureSkipVerify)

### Version

```Text
$ helm list -n istio-system
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-base      istio-system    1               2024-04-01 16:26:12.905948058 -0500 CDT deployed        base-1.19.3     1.19.3     
istiod          istio-system    1               2024-04-01 16:26:13.225228464 -0500 CDT deployed        istiod-1.19.3   1.19.3 

Probably not relevant below:
$ helm list -n istio-ingress
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-eastwestgateway   istio-ingress   1               2024-04-01 16:26:29.639182247 -0500 CDT deployed        gateway-1.19.3  1.19.3  
$ helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```

### Additional Information

Relevant ServiceEntry config:
```
"test-ca-signed-cert/testbox-https": {
    "@type": "type.googleapis.com/istio.mcp.v1alpha1.Resource",
    "metadata": {
        "name": "test-ca-signed-cert/testbox-https",
        "createTime": "2024-04-02T00:03:06.294205346Z",
        "version": "2024-04-02T00:03:06.294204387Z"
    },
    "body": {
        "@type": "type.googleapis.com/istio.networking.v1alpha3.ServiceEntry",
        "hosts": [
            "testbox-https.internal.test-ca-signed-cert"
        ],
        "ports": [
            {
                "number": 10000,
                "name": "consul-service-port"
            }
        ],
        "location": "MESH_INTERNAL",
        "resolution": "STATIC",
        "endpoints": [
            {
                "address": "10.211.55.10",
                "ports": {
                    "consul-service-port": 28526
                },
                "serviceAccount": "server-sa"
            }
        ],
        "exportTo": [
            "*"
        ]
    }
}
```
Relevant DestinationRule config:
```
"test-ca-signed-cert/testbox-https": {
            "@type": "type.googleapis.com/istio.mcp.v1alpha1.Resource",
            "metadata": {
                "name": "test-ca-signed-cert/testbox-https",
                "createTime": "2024-04-02T00:03:06.294308054Z",
                "version": "2024-04-02T00:03:06.294307262Z"
            },
            "body": {
                "@type": "type.googleapis.com/istio.networking.v1alpha3.DestinationRule",
                "host": "testbox-https.internal.test-ca-signed-cert",
                "trafficPolicy": {
                    "loadBalancer": {
                        "simple": "LEAST_REQUEST"
                    },
                    "connectionPool": {
                        "http": {
                            "useClientProtocol": true
                        }
                    },
                    "tls": {
                        "mode": "SIMPLE",
                        "caCertificates": "/var/run/secrets/istio/outbound_origination.pem"
                    }
                }
            }
        },
```
Relevant `localhost:15000/config_dump` snippet:
```
"transport_socket": {
 "name": "envoy.transport_sockets.tls",
 "typed_config": {
  "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
  "common_tls_context": {
   "tls_params": {
    "tls_minimum_protocol_version": "TLSv1_2",
    "tls_maximum_protocol_version": "TLSv1_3"
   },
   "combined_validation_context": {
    "default_validation_context": {
     "match_subject_alt_names": [
      {
       "exact": "spiffe://cluster.local/ns/test-ca-signed-cert/sa/server-sa"
      }
     ]
    },
    "validation_context_sds_secret_config": {
     "name": "file-root:/var/run/secrets/istio/outbound_origination.pem",
     "sds_config": {
      "api_config_source": {
       "api_type": "GRPC",
       "grpc_services": [
        {
         "envoy_grpc": {
          "cluster_name": "sds-grpc"
         }
        }
       ],
       "set_node_on_first_message_only": true,
       "transport_api_version": "V3"
      },
      "resource_api_version": "V3"
     }
    }
   }
  }
 }
},
```

**Comment by howardjohn** [comment]
If anything I would expect this to validate `testbox-https.internal.test-ca-signed-cert` as the SAN. 

A SAN must be verified, so I don't think a mode to not verify it other than insecureSkipVerify makes much sense?

**Comment by wtzhang23** [comment]
Although not verifying SANs is far from ideal, verifying the certificate at least ensures that the certificate is minted from a trusted CA (in our case, an internal CA).

**Comment by ramaraochavali** [comment]
Is there a plan to move VERIFY_CERTIFICATE_AT_CLIENT and ENABLE_AUTO_SNI to proper apis (specially ENABLE_AUTO_SNI) @howardjohn @kfaseela

**Comment by wtzhang23** [comment]
FWIW you can use system certs by setting `caCertificates: system`. Don't think this is documented.

**Comment by howardjohn** [comment]
> Is there a plan to move VERIFY_CERTIFICATE_AT_CLIENT and ENABLE_AUTO_SNI to proper apis (specially ENABLE_AUTO_SNI) @howardjohn @kfaseela

`VERIFY_CERTIFICATE_AT_CLIENT` is insecureSkipVerify on DR. Auto SNI is effectively "explicitly set the SNI on DR"?

**Comment by ramaraochavali** [comment]
VERIFY_CERTIFICATE_AT_CLIENT looks like not exactly equivalent of insecureSkipVerify. insecureSkipVerify does not even validate CA - but I get why we want to force the validation of CA.

AutoSNI - In the current model, we allow services to not set SNI (it is not mandatory). So even though DR has that field, we can skip. But with AutoSNI (I assume it will be removed in future), will force SNI to be set (either host name or whatever it is set in DR). For service -> service we do not have to set SNI (I guess ISTIO_MUTUAL works like this - we might set some dummy sni) today for MUTUAL, but with auto SNI it sets up host. I do not know the implications of setting auto SNI though.  That is why I was asking - is there a way to skip not setting SNI for mesh calls . Similar to Lizan's comment here https://github.com/istio/api/pull/1773#discussion_r537268481

**Comment by howardjohn** [comment]
Standard mesh calls do not use auto_sni and already have used a custom Istio SNI format. Might not apply to your usage if you use MUTUAL, though.

**Comment by ramaraochavali** [comment]
Yes. I was asking for MUTUAL

**Comment by kfaseela** [comment]
> VERIFY_CERTIFICATE_AT_CLIENT looks like not exactly equivalent of insecureSkipVerify. insecureSkipVerify does not even validate CA - but I get why we want to force the validation of CA.
> 
> AutoSNI - In the current model, we allow services to not set SNI (it is not mandatory). So even though DR has that field, we can skip. But with AutoSNI (I assume it will be removed in future), will force SNI to be set (either host name or whatever it is set in DR). For service -> service we do not have to set SNI (I guess ISTIO_MUTUAL works like this - we might set some dummy sni) today for MUTUAL, but with auto SNI it sets up host. I do not know the implications of setting auto SNI though. That is why I was asking - is there a way to skip not setting SNI for mesh calls . Similar to Lizan's comment here [istio/api#1773 (comment)](https://github.com/istio/api/pull/1773#discussion_r537268481)

I think this comment addresses Lizan's comment: https://github.com/istio/api/pull/1773#discussion_r824546155

**Comment by howardjohn** [comment]
@ramaraochavali are there specific concerns you have with either of these fields for your usage?

**Comment by ramaraochavali** [comment]
> I think this comment addresses Lizan's comment:

That RFC is for HTTP2. Not for HTTP1.1 AFAIK

I have concern about Auto SNI feature with MUTUAL in service-> service traffic. Without that enabled, and if user does not specify SNI in ClientTLSSettings we do not set any SNI. So it used to be driven by Users Choice.  With this enabled, we automatically set SNI as the host name even if user does not specify SNI - which is kind of change in behaviour and we are forcefully setting SNI. Not sure if there are any side affects of this.

**Comment by ramaraochavali** [comment]
>  does it work if you set sni: "" explicitly?

it may work  but we check if tls.sni != "" - We may have to fix that

**Comment by howardjohn** [comment]
Ah we probably cannot detect unset vs `""`
