### ISSUE TITLE
opentelemetry tracing bug: status code always unset

### ISSUE THREAD

**Issue by Frapschen** [istio/istio#50195]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have reviewed some Istio spans and it appears that the Status code does not change when an HTTP request fails. I expect the Status code to adhere to the [Status semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status).

origin issue: https://github.com/envoyproxy/envoy/issues/32114

### Version

```Text
istio 1.17.8
```

**Comment by zirain** [comment]
1.17.8 is EOL for a long time, please update to latest and retry. If it's still exist, envoy need a fix.

**Comment by Frapschen** [comment]
> 1.17.8 is EOL for a long time, please update to latest and retry. If it's still exist, envoy need a fix.

thanks, I will try the latest

**Comment by miroswan** [comment]
@Frapschen did this resolve your issue?

**Comment by zirain** [comment]
this seems need code change in envoy, will take a look later.

**Comment by zirain** [comment]
fixed by https://github.com/envoyproxy/envoy/pull/33674, will land in istio v1.23.
