### ISSUE TITLE
Gateway API support related docs

### ISSUE THREAD

**Issue by linsun** [istio/istio#50200]
One user reached out to me regarding our support statement for gateway API.  Gateway API [reached 1.0](https://kubernetes.io/blog/2023/10/31/gateway-api-ga/) in KubeCon US 2023.  Istio's [feature status](https://istio.io/latest/docs/releases/feature-stages/) page says gateway API is beta. Our ingress doc still uses v1beta1.  Does it make sense to update our ingress doc to use v1 of the Gateway and HTTPRoute resources?

Our request [routing doc](https://istio.io/latest/docs/tasks/traffic-management/request-routing/) still says install experimental CRD and requires enabling of the PILOT_ENABLE_ALPHA_GATEWAY_API env var, while it also says `Istio includes beta support for the Kubernetes [Gateway API](https://gateway-api.sigs.k8s.io/). @howardjohn @frankbu, is it correct to interpret that internal mesh (east-west) traffic that requires Gateway API is still experimental? 

[ ] Ambient
[ x ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Mesh is blocked by https://github.com/kubernetes-sigs/gateway-api/pull/2873

Ingress can be made 'stable' IMO and use v1

**Comment by frankbu** [comment]
> Does it make sense to update our ingress doc to use v1 of the Gateway and HTTPRoute resources?

Good point. Not really necessary, since the v1beta1 resources are just aliases for v1, but I think it's best to use v1 in our docs. Note that the v1 resources also include experimental features if the experimental channel CRDs are used.

**Comment by frankbu** [comment]
I think the other thing that's a little confusing is there are several different support levels at play here.

1. The Gateway API resource version (some are v1 some are v1alpha2)
2. Two version of the CRDs, stable and experimental release channels (stable only includes the v1 resources, experimental adds the v1alpha2 resources and extra experimental features in the v1 resources)
3. The Istio implementation of Gateway API (currently beta)

Maybe we should remove `beta` from this note in the docs `Istio includes beta support for the Kubernetes Gateway API`, and just say `Istio includes support ...`

**Comment by keithmattix** [comment]
I think a firmer support policy is useful here a la what we have for k8s. Saying something like: "Istio will support as stable the standard channel for the last n-X Gateway API versions" will send an unambiguous message to users and give them confidence in what they're using

**Comment by linsun** [comment]
Thanks all for chiming in. Sounds like consensus is to move to use v1 for ingress.

As far as supporting statement, I'd agree we should remove `beta` in the statement for the [Ingress gateway](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) page along with other pages who have this warning.

**Comment by linsun** [comment]
> I think a firmer support policy is useful here a la what we have for k8s. Saying something like: "Istio will support as stable the standard channel for the last n-X Gateway API versions" will send an unambiguous message to users and give them confidence in what they're using

Agreed, this would be useful in general, maybe as part of the work @whitneygriffith is driving.

**Comment by joebowbeer** [comment]
@howardjohn wrote:
> Mesh is blocked by [kubernetes-sigs/gateway-api#2873](https://github.com/kubernetes-sigs/gateway-api/pull/2873)

IIUC, Your PR was merged and Mesh is now part of standard Gateway API

Should Istio's Service Mesh Implementation Status be changed from Beta to GA, and the [description](https://gateway-api.sigs.k8s.io/implementations/#istio) updated?

> For service mesh users, Istio also fully supports the [GAMMA initiative's](https://gateway-api.sigs.k8s.io/concepts/gamma/) experimental Gateway API [support for east-west traffic management](https://gateway-api.sigs.k8s.io/concepts/gamma/) within the mesh.
