### ISSUE TITLE
Support short name for services in RBAC config

### ISSUE THREAD

**Issue by liminw** [istio/istio#5020]
Currently the service names in RBAC config must be fully qualified names like "productpage.default.svc.cluster.local". We should support use of short names (like "productpage") for services for the following reasons.
1.  If a ServiceRole is defined on a certain namespace, the services in the ServiceRole definitions must all be inside the same namespace. The code can construct the fully qualified service name from service short name and the namespace from metadata.
2. Better user experience. Short name is easier to write.

Hence, 
* For ServiceRole that is defined on a given namespace, we can support both short names and fully qualified names for services. If fully qualified names is used, the validation code should verify that the namespace in service name matches ServiceRole namespace. 
* For ServiceRole that is defined on global scope. Only fully qualified service name should be used.

**Comment by rshriram** [comment]
>If fully qualified names is used, the validation code should verify that the namespace in service name matches ServiceRole namespace.

This is not a correct behavior. Not all platforms have the concept of namespace. What will be the solution for these platforms, where the namespace is not part of the DNS name ? (cc @louiscryan/ @ZackButcher  )..

I suggest following the approach taken by networking. Allow people to define rbacs by DNS suffixes.. e.g., *.foo.com, *.ns.svc.cluster.local, etc.. This has the advantage of being cross platform, while still being friendly to kube where shortnames can be used (i.e. shortname is resolved into a longer name based on the ambient DNS namespace).

**Comment by ZackButcher** [comment]
I'm with Shriram here: hostnames form a hierarchy which can be used for policy, and the k8s case falls right out of supporting a wildcard hostname. For example, to write a policy about all services in the namespace `foo` I target the hostname `*.foo.svc.cluster.local`.

The caveat is that we only support replacement, and closest match runs: a policy about `bar.foo.svc.cluster.local` replaces the namespace wide policy `*.foo.svc.cluster.local` for service `bar` with no merging of the two policies.
