### ISSUE TITLE
upstream [95] error: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""

### ISSUE THREAD

**Issue by ldtnix** [istio/istio#50210]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are using istio version 1.21.0 in data plane version, and we get these errors below in every hour.
`{"level":"error","time":"2024-04-01T21:02:02.771280Z","scope":"xdsproxy","msg":"upstream [95] error: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR, debug data: \"max_age\""}`
We saw similar issue at https://github.com/istio/istio/issues/37875.
It does not break any network connectivity but it pollutes the logs and something confusing when troubleshooting other issues

### Version

```Text
$istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.19.6 (1 proxies), 1.21.0 (199 proxies)
$kubectl version --short
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.27.11
```

**Comment by ldtnix** [comment]
Thank you @howardjohn

**Comment by howardjohn** [comment]
This was backported https://github.com/istio/istio/commit/822301c3fef14155df67f63a7ec62545da8ea24a so will be in the next 1.21 patch. Thanks!
