### ISSUE TITLE
Inbound request occasionally fail due to cluster_not_found error during RDS update

### ISSUE THREAD

**Issue by freedomljc** [istio/istio#50214]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Found the inbound requests occasionally fail due to cluster_not_found error. The issue lasts for < 1 minute, and the timing exactly aligns with when envoy gets RDS update for the inbound route config `InboundPassthroughClusterIpv4`. 

For `cluster_not_found` error, I initially thought it's related to the corresponding cluster `InboundPassthroughClusterIpv4` wasn't ready when the issue happened, but found the associated cluster config hadn't been changed for a while by checking envoy "config_dump" admin endpoint. Later on, found the associated route config  `InboundPassthroughClusterIpv4` was being updated when the error happened. As the error only lasts for < 1 minute, seems to me that the issue only happens during rds update.

### Version

```Text
istioctl version:
control plane: 1.20.0
data plane: 1.20.0
```

**Comment by Deancup** [comment]
i have same problem in 1.17.2, anyone know how to solve it?
