### ISSUE TITLE
 Ingress gateways not installing in Kind Cluster while setting Istio ambient mesh

### ISSUE THREAD

**Issue by Bharath-vi** [istio/istio#50219]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

 Ingress gateways not installing in Kind Cluster while setting Istio ambient mesh
`
![image](https://github.com/istio/istio/assets/81402835/c08fafa1-1f99-4c21-ab7d-cef5dd29b119)

$ istioctl install --set profile=ambient
This will install the Istio 1.21.0 "ambient" profile (with components: Istio core, Istiod, CNI, and Ztunnel) into the cluster. Proceed? (y/N) y
Istio core installed    
Istiod installed
CNI installed  
Ztunnel installed
Pruning removed resources                                                                                                                                                             
Installation complete 

Installation completes without Ingress gateway.
`

### Version

```Text
$ istioctl version
client version: 1.21.0
control plane version: 1.21.0
data plane version: none

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.2-eks-a59e1f0
Kustomize Version: v4.5.7
Server Version: v1.27.1
```

**Comment by howardjohn** [comment]
This is intended. The ingress is no longer part of the default install and needs to be explicitly enabled

**Comment by linsun** [comment]
+1, were you following some docs that we need to update perhaps @Bharath-vi ?

**Comment by tppalani** [comment]
Hi @linsun  Here the page which we followed https://github.com/istio/istio/issues/50219#issuecomment-2034719342

**Comment by ericvn** [comment]
As noted on the profile page, https://istio.io/latest/docs/setup/additional-setup/config-profiles/, the ambient profile does not include the istio-ingressgateway.

**Comment by tppalani** [comment]
Hi @ericvn 

thanks for your help I will try to install gateay
