### ISSUE TITLE
Test framework dump missing some namespaces

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50238]
Example: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-128_istio_postsubmit/1775631905698353152

Dump has echo-1 namespace: https://gcsweb.istio.io/gcs/istio-prow/logs/integ-k8s-128_istio_postsubmit/1775631905698353152/artifacts/ambient-dbca91265f0d43afa40b732/TestTraffic/virtualservice/added_header/captured/to_waypoint/_test_context/

But the test is spinning up its own echo namespace, echo-4: https://github.com/istio/istio/blob/08b2bcef3b4585f2d05234e3495196751e909c7a/tests/integration/ambient/traffic_test.go#L32

For some reason this is missed, making troubleshooting hard

**Comment by howardjohn** [comment]
So the normal ones are made at the suite level, and this one is made at the test level.

```
suite {
  echo-1 namespace
  testtraffic {
    echo-4 namespace
    testtraffic/subtest1 {}
    testtraffic/subtest2 {}
  }
}
```
When a test fails it dumps everything created _below it_ and suite-level. So testtraffic does dump it, but only after all of testtraffic runs, not immediately on testtraffic/subtest1 failure.

Not sure a good fix

**Comment by howardjohn** [comment]
@stevenctl any ideas? we could just change up how we write the test as well

**Comment by stevenctl** [comment]
```go
		rt.DumpCustom(c, false)
		c.scope.dump(c, true)
```

Right now we dump the global scope (shallow), and the current scope (recursive). 
We could add a marker like `TestGroup` or `Subsuite` to `TestContext`. We recursively walk up `.parent` contexts and dump anything with that mark. `TestTraffic` will have such a mark.
