### ISSUE TITLE
istioctl waypoint: consider a way to enroll the namespace

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50248]
Maybe we should have a `--enroll-namespace`, possibly even on by default, flag to `istioctl x waypoint apply` to label the namespace with `istio.io/use-waypoint=<name>`. This could help ease a common mistake of not enrolling workloads

**Comment by MorrisLaw** [comment]
Do we mean to add a `label` or instead add an `annotation` like:

`istio.io/use-waypoint:<name>`

**Comment by howardjohn** [comment]
Yep annotation, got it mixed up with label. Another reason to automate it for people :slightly_smiling_face:
