### ISSUE TITLE
Analyzer for waypoint without anything enrolled

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50249]
Today you can deploy a waypoint but not attach any pods/services to it. We should add an analyzer to warn when this happens

**Comment by MorrisLaw** [comment]
I'm trying to think of some options of how this could be achieved and I'm not too sure what makes the most sense. Here are a few possible options:

- Add an analyzer to check for `istio.io/use-waypoint=<waypoint-name>` annotation on the resources where a Waypoint could be attached, like: `namespace, service, pod, serviceEntry, workloadEntry`. Seems to be the least efficient option.
- Add an analyzer that checks wds for waypoint with the presumption that if it's in wds then it's used, if not found then it is not used. Seems to be more efficient than iterating through all resources.
- Don't use an analyzer at all, write to status of the gateway from Istiod's ambient index controller itself to warn users of when a waypoint is not attached. Avoids duplicating logic or maintenance issues with analyzer as the index controller gets updated over time. Mitigates the chances of an analyzer incorrectly warning for unattached waypoints when it shouldn't be.

*caveat: I'm not 100% sure yet how exactly the analyzer logic works so it could be much simpler than I'm describing it and maybe there are reasons we shouldn't be writing to status that I'm not aware of*

cc/ @ilrudie @keithmattix for opinions/thoughts

**Comment by ilrudie** [comment]
> * Add an analyzer that checks wds for waypoint with the presumption that if it's in wds then it's used, if not found then it is not used. Seems to be more efficient than iterating through all resources.
 
One point of clarification is the check should be if it has been configured as a waypoint in WDS. the waypoint pods and svc would be in there even if it's not used.

**Comment by hanxiaop** [comment]
> > * Add an analyzer that checks wds for waypoint with the presumption that if it's in wds then it's used, if not found then it is not used. Seems to be more efficient than iterating through all resources.
> 
> One point of clarification is the check should be if it has been configured as a waypoint in WDS. the waypoint pods and svc would be in there even if it's not used.

FWIW currently the analyzers are checking only static k8s resources, and there isn't a similar analyzer for querying things like wds or proxyconfig.

1 may be an easier option, as the current analyzer implementation has the known scalablility issue.

**Comment by MorrisLaw** [comment]
Tbc @hanxiaop, are you saying you like this option as well:
> Add an analyzer that checks wds for waypoint with the presumption that if it's in wds then it's used, if not found then it is not used. Seems to be more efficient than iterating through all resources.

**Comment by howardjohn** [comment]
I think it's a good idea but it seems like a pretty massive change we should think through the design of pretty closely. Probably there is a general benefit to utilizing krt here in some way.

**Comment by MorrisLaw** [comment]
> I think it's a good idea but it seems like a pretty massive change we should think through the design of pretty closely. Probably there is a general benefit to utilizing krt here in some way.

I agree. This may warrant an Istio design doc to help us talk/think through the design. I'll draft that up soon and share.

**Comment by MorrisLaw** [comment]
I think I'll want to get some thoughts around this from contributors who are experienced with how the istioctl analyzer works along with people who have a good understanding of krt.

I'm on vacation next week but I hope to schedule a meeting with a few people who are interested when I'm back.

**Comment by MorrisLaw** [comment]
I'm going to focus on some other issues, so I won't have time to work on this in the near future. Going to unassign myself and leave it open for others to take up if they'd like to.
