### ISSUE TITLE
Test framework: drop "features"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50272]
This was added 4 years ago with the intent that it would help us understand what features are tested. However, it hasn't shown any value throughout this time. It does, however, have a pretty high implementation complexity.

We should remove it, pending agreement in T&R

**Comment by keithmattix** [comment]
I think this is still good information to have; as it stands, we have no idea how much of our codebase(s) are tested except anecdotally. I would actually argue we need to improve the features framework and make it usable

**Comment by howardjohn** [comment]
IMO it had 4 years to prove value.. in the spirit of "up or out" we also need to cut our losses on efforts like this. 

Also its not like the current labelling is particularly well done

**Comment by keithmattix** [comment]
Agree that current labeling isn't useful. I obviously don't have the context you do, but I want to distinguish between whether the data isn't useful vs. if we aren't making use of the data. IMO, those are two different problems with two different solutions

**Comment by howardjohn** [comment]
I certainly don't mind comments or other documentation on tests. I do mind the huge machinery around it that is unused (https://github.com/istio/istio/pull/50274)

**Comment by keithmattix** [comment]
I'm proposing we use it :) If there are "features" or "areas" that are lacking coverage, we should create good-first-issues for them so new contributors or others should help out. We should gate releases based on whether we see coverage increase vs. decrease. We need to have _some_ visibility over how well our code is tested and I worry that removing this is removing one of the few sources of data we have

**Comment by ericvn** [comment]
Unfortunately, I don't have a strong feeling one way or the other. I certainly understand what is probably a current lack in value from the framework and it does cause issues occasionally (I don't recall any major issues, but I might not have seen/heard about it). This would tend to make it's removal a good thing (especially is someone has already done most of that work). Thus I would lean toward removal unless we can get someone to make changes so we get more value (and it's hard to find people to do some of the less glamorous work).

**Comment by jacob-delgado** [comment]
Adding integration test coverage would be better to instrument this than capability. Not sure how easy it would be to do that. But I agree that there is little to no value with this feature.

**Comment by keithmattix** [comment]
At this point, I'm probably just misunderstanding the feature then. I'll withdraw my opposition 👍🏾

**Comment by hanxiaop** [comment]
+1 since the features part provides little value and also introduces complexity when maintaining the list and writing tests.
