### ISSUE TITLE
Ambient: allow DNS Service types

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50301]
https://github.com/istio/istio/blob/a5f3ef0c3045373624efbf15b79d5737060e345c/pilot/pkg/networking/core/cluster_waypoint.go#L97 we hardcode EDS. If we allowed DNS types, we could have essentially an egress gateway.

We should, however, consider doing this 'properly' and introducing a full on DFP

**Comment by jessicegao** [comment]
The use case seems not valid, for dns service, why not going though a real egress gateway not waypoint
