### ISSUE TITLE
Support source IP based sticky sessions over multiple protocols

### ISSUE THREAD

**Issue by thomasdraebing** [istio/istio#50316]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

We deploy a stateful application that allows using HTTPS and SSH (TCP) for requests. We have configured source IP based sticky sessions and this works well for each protocol individually. However, there is a separate session for each protocol, so that clients using a mix of both protocols potentially use different application instances.

It would be useful to have a single session that supports all protocols served by a given destination.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This seems pretty unlikely to be feasible given the architecture of Istio/Envoy. Each port is basically 100% orthogonal.

I recall in Kubernetes core, there was some controversy around whether their session affinity was per-port or per-service as well. I don't recall the outcome, though.
