### ISSUE TITLE
Failed to connect to istio-telemetry port 42422: Connection refused

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5032]
Docker Image docker.io/istionightly/mixer:circleci-nightly

It appears that mixer is not listening on port 42422 for prometheus metrics. I validated that the service exists and has the port definitions

```
root@istio-ingressgateway-694c49556f-42fss:/# curl "istio-telemetry:42422/metrics"
curl: (7) Failed to connect to istio-telemetry port 42422: Connection refused
```
@mandarjog

**Comment by nmnellis** [comment]
same issue on `gcr.io/istio-testing/mixer:923dcb80da79f2ce2035d4afd6438f6225b78e38`

**Comment by douglas-reid** [comment]
These images should be going through a set of e2e tests that validate this behavior. Are you missing configuration?

**Comment by nmnellis** [comment]
This was due to the `istio-mixer-create-cr` job not running on deployment. I ran it and all is good

**Comment by shahaf600** [comment]
hi @nmnellis , i'm having the same issue and I see you managed to fix it.
I'm using helm to deploy it. but can't find anything on this job. can you explain what this job is a bit ?

**Comment by nmnellis** [comment]
in helm there is a post "hook" that populates the config for mixer. if this hook doesn't run, mixer has no context. since this issue is older there is a chance that the config isn't loaded via these means anymore
