### ISSUE TITLE
add Boolean parameter to decide to allow or not accumulating http chunks. 

### ISSUE THREAD

**Issue by LeiYangGH** [istio/istio#50327]
**Describe the feature request**

When using istio(sidecar, loadBalancer, LEAST_REQUEST), we noticed server response
 http chunks are often accumulated.
I'm not English native speaker, so descriptions maybe not be accurate. let me explain more,

our service responses `Transfer-Encoding: chunked`, `Content-Type: multipart/form-data`.
the server is designed to have each [http chunk](https://en.wikipedia.org/wiki/Chunked_transfer_encoding)(first a hex number a line indicating how many bytes in content, followed by new line and the content) to be exactly one http multipart.

But when using istio, the client received http chunks are often combined with two or more http multiparts, maybe this is a common behavior of most http networking libraries, it potentially improves performance （by caching small chunks to save network time）, if i am asked to explain the behavior.

However, our client heavily relies on the chunking behavior and not want the chunks to be messed up. our client uses sockets to read chunks, to have best performance （the first multipart latency is very important to us）. it doesn't have to really use the http multipart libraries to parse response.

**Describe alternatives you've considered**

In issue scenario we are forced to re design our clients, either by handling rechunked contents which makes code more complex and harder to maintain, or use higher level networking libraries, sacrificing the performance.

**Affected product area (please put an X in all that apply)**
[ ] Networking

**Comment by howardjohn** [comment]
If you need this level of transparency your best bet is probably to treat the traffic as opaque TCP (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)

**Comment by LeiYangGH** [comment]
> If you need this level of transparency your best bet is probably to treat the traffic as opaque TCP (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)

thanks, i tried setting `appProtocol: tcp` in both server side and client side k8s service but doesn't help. maybe the feature i request should be `appProtocol: http-chunked`.

**Comment by howardjohn** [comment]
If you set `appProtocol: tcp` then it is not Istio that is causing this, since it would not modify the traffic in any way
