### ISSUE TITLE
Deployment does not have minimum availability.

### ISSUE THREAD

**Issue by lijie123bes** [istio/istio#50339]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

helm install istio-ingressgateway istio/gateway -n istio-system

### Version

```Text
istio/pilot:1.21.1

Client Version: v1.23.6
Server Version: v1.23.6

v3.10.3+g835b733
```

**Comment by howardjohn** [comment]
This doesn't have enough, or really any information to debug. Please include meaningful information if you'd like to receive help such as logs, environment info, etc.
