### ISSUE TITLE
custom bootstrap is not applied to ingress gateway

### ISSUE THREAD

**Issue by akamac** [istio/istio#50345]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Custom bootstrap, provided [via annotation](https://github.com/istio/istio/tree/master/samples/custom-bootstrap), is not applied to ingress gateway, because it is not supported in the [gateway injection template](https://github.com/istio/istio/blob/master/manifests/charts/istiod-remote/files/gateway-injection-template.yaml).

Given that bootstrap patching via EnvoyFilter no longer works in 1.21, this is quite critical.

### Version

```Text
client version: 1.21.0
control plane version: 1.21.1
data plane version: 1.21.1 (3 proxies)
```

**Comment by howardjohn** [comment]
fwiw you could manually add it to the deployment in the short term. It's just an env var and volume mount. 

That being said, consistency here probably makes sense

**Comment by akamac** [comment]
> fwiw you could manually add it to the deployment in the short term. It's just an env var and volume mount.
> 
> That being said, consistency here probably makes sense

Yep, I've ended up adding the custom injection template for gw that does support bootstrap override.
The PR is trivial, but needs some tests I guess.

**Comment by StianOvrevage** [comment]
Similar to https://github.com/istio/istio/issues/28302 with a workaround documented in https://istio.io/latest/news/security/istio-security-2020-007/#mitigation

**Comment by ben-childs-docusign** [comment]
> fwiw you could manually add it to the deployment in the short term. It's just an env var and volume mount.
> 
> That being said, consistency here probably makes sense

We are hitting a similar issue and it is blocking our upgrade to 1.21 as we need to customize histogram metric buckets. Is there any more detail on the volume mount / env var required? 

We are trying to get upgraded to 1.21 before 1.20 goes out of support in July.
