### ISSUE TITLE
Add/Remove Response Headers

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#5036]
We would like to strip/add response headers to routes as traffic passes through envoy.

This functionality is currently supported within envoy https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers

**Comment by kyessenov** [comment]
There is this https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L371, but I think you want response headers? I think the API need to have both options exposed for the request and the response header/trailer manipulation.

We've also started thinking how to manipulate headers from the policy adaptors, but that's for the longer term.

**Comment by sneko** [comment]
Related to #4971

**Comment by howardjohn** [comment]
This is supported now https://github.com/istio/api/pull/709/files
