### ISSUE TITLE
GCP metadata incorrect locality

### ISSUE THREAD

**Issue by Stono** [istio/istio#50379]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We noticed the span tag is broadly wrong, reporting almost all of our workloads in `west4-a` which is wrong.

<img width="1920" alt="Screenshot 2024-04-11 at 14 23 54" src="https://github.com/istio/istio/assets/1486729/c6d5769e-e6aa-406c-b427-c3f1e9184a3a">

Digging into this more, here you can clearly see a pod running in west4-c, is being reported in the config_dump as west4-a:

```
❯ k get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE                                                  NOMINATED NODE   READINESS GATES
shippr-cli-api-5f6997c78-44tgc   2/2     Running   0          13m   10.194.62.215   gke-delivery-platform-normal-20220831-fe7b3a8a-r9ch   <none>           <none>
shippr-cli-api-5f6997c78-cmlf9   2/2     Running   0          14m   10.194.53.209   gke-delivery-platform-normal-20220831-6749e4f8-nh1m   <none>           <none>

~
❯ k get node gke-delivery-platform-normal-20220831-fe7b3a8a-r9ch -oyaml | grep west4
    csi.volume.kubernetes.io/nodeid: '{"pd.csi.storage.gke.io":"projects/at-delivery-platform-prod/zones/europe-west4-c/instances/gke-delivery-platform-normal-20220831-fe7b3a8a-r9ch"}'
    failure-domain.beta.kubernetes.io/region: europe-west4
    failure-domain.beta.kubernetes.io/zone: europe-west4-c
    topology.gke.io/zone: europe-west4-c
    topology.kubernetes.io/region: europe-west4
    topology.kubernetes.io/zone: europe-west4-c
  providerID: gce://at-delivery-platform-prod/europe-west4-c/gke-delivery-platform-normal-20220831-fe7b3a8a-r9ch

~
❯ k exec -it shippr-cli-api-5f6997c78-44tgc -- curl http://127.0.0.1:15000/config_dump | grep west4
       "gcp_location": "europe-west4-a",
       "gcp_gke_cluster_url": "https://container.googleapis.com/v1/projects/at-delivery-platform-prod/locations/europe-west4-a/clusters/delivery-platform",
      "region": "europe-west4",
      "zone": "europe-west4-a"
```

The config dump shows:
```
     "locality": {
      "region": "europe-west4",
      "zone": "europe-west4-a"
     },
```

### Version

```Text
1.20 and 1.21
```

### Additional Information

It appears to be the cluster locality rather than the pod locality.

**Comment by howardjohn** [comment]
Hmm: https://github.com/istio/istio/blob/febeb83b345abdf32ee0dc7551bd3605dbce2482/pkg/bootstrap/platform/gcp.go#L98-L102

I wonder why its looking for cluster-location than falling back to Zone(). I would think Zone() is the correct one?

These translate to `instance/zone` and `instance/attributes/cluster-location` btw

**Comment by howardjohn** [comment]
Interesting: https://github.com/googleapis/google-cloud-go/pull/9094. So some other places are intentionally doing this. I think in some instances we may want one vs the other, but we have a single field used for everything.

TBH I don't really see why you would want the cluster location, but if the log schema says "cluster location" I suppose using "cluster location" is right :shrug: . But for locality LB, etc its clearly not.

**Comment by Stono** [comment]
It certainly makes little sense from a Jaeger span perspective at least.  Recording `zone` of a pod but the value being the cluster zone rather than the pod zone 🤷 

This is on a GCP "zonal" cluster by the way (single zone master), wonder what the value is set to on a regional cluster (multi zone master)?

Are you saying this is the value being used in locality routing to?  In which case that feature would just be broken right?

**Comment by howardjohn** [comment]
Ah nvm, the config_dump zone is a fallback, not the primary source: https://github.com/istio/istio/blob/b6cfe7ec72d321d51aa0f66cdd0b9a0cf7865e5b/pilot/pkg/xds/ads.go#L618. So locality LB should be fine in this case

**Comment by Stono** [comment]
Was going to say i'm pretty sure it's working as our egress charges aren't through the roof! but i'll double check now...

**Comment by Stono** [comment]
Yah locality routing is working fine.  So in terms of impact (for me) its just odd data in Jaeger

**Comment by Stono** [comment]
@howardjohn is this something that can/will be fixed?  It's misleading to label up traffic with the wrong locality in spans, it makes debugging zonal issues difficult.

**Comment by howardjohn** [comment]
Maybe @kyessenov or @lei-tang can help out

**Comment by Stono** [comment]
Extremely hacky way i worked around this:

Create a custom `istio-pilot` image with a wrapper for `pilot-agent`:

```
#!/bin/bash

METADATA_SERVER="http://metadata.google.internal/computeMetadata/v1"

ZONE_INFO_PATH="instance/zone"
NODE_NAME_PATH="instance/name"

ZONE=$(curl --max-time 2 "${METADATA_SERVER}/${ZONE_INFO_PATH}" -H "Metadata-Flavor: Google" -s)
if [ $? -ne 0 ]; then
    NODE_ZONE="unknown"
else
    NODE_ZONE=$(echo $ZONE | awk -F/ '{print $NF}')
fi
export NODE_ZONE

NODE_NAME=$(curl --max-time 2 "${METADATA_SERVER}/${NODE_NAME_PATH}" -H "Metadata-Flavor: Google" -s)
if [ $? -ne 0 ]; then
    NODE_NAME="unknown"
fi
export NODE_NAME

exec /usr/local/bin/pilot-agent "$@"
```

Use the telemetry API to put those env vars into tags:
```
  tracing:
  - customTags:
      node-name:
        environment:
          name: NODE_NAME
      node-zone:
        environment:
          name: NODE_ZONE
      x-auth-email:
        header:
          name: x-auth-email
```

![Screenshot 2024-07-02 at 10 20 18](https://github.com/istio/istio/assets/1486729/4add98a7-89a0-42fb-8eb0-98582cbe60d0)

**Comment by kyessenov** [comment]
For tracing, the workload location is definitely the right thing. I'm not sure what cluster location has to do at all for pod-to-pod traffic.

**Comment by vkrishnamoorthy-sift** [comment]
Hello, please see linked issue - https://github.com/istio/istio/issues/52363  I extract locality info using node.locality.zone and use it as an extra attribute for my stats. With the new versions (anything above 1.18), I can no longer see this correctly set I have a regional cluster and I see locality being set like this:

**Comment by vkrishnamoorthy-sift** [comment]
I appreciate any help/pointers to this problem. I need to extract zone information into envoy stats. I used to do it in an envoy filter in the older versions by extracting node.locality.region With the 1.19+ I am trying to create a Telemetry resource(posted above). If there are other ways/work-arounds to do this, please let me know. We are seriously blocked with our upgrade since we have a lot of usecases (alerts, metrics, dashboards, etc) relying on this. I also tried out a custom [image](https://github.com/istio/istio/issues/50379#issuecomment-2202507042) by setting something like `ISTIO_BOOTSTRAP_OVERRIDE="node: {id: 'node1'}"`   but I am not sure it is working .. I dont see my changes getting picked up

**Comment by Stono** [comment]
@kyessenov or @lei-tang is there any plan to fix this? 
I'm unable to use distroless images because of it, as i have to run a funky init script to set some env variables based on gke metadata queries - its super hacky

**Comment by kyessenov** [comment]
@Stono @howardjohn From GCP perspective, the location has to be the cluster location. That's just an artifact of how internal Monarch system operates, the telemetry is stored based on the monitored resource which is keyed on the cluster location for historical reasons. In other words, `gcp_location` must absolutely be the cluster location.

**Comment by howardjohn** [comment]
> @Stono @howardjohn From GCP perspective, the location has to be the cluster location. That's just an artifact of how internal Monarch system operates, the telemetry is stored based on the monitored resource which is keyed on the cluster location for historical reasons. In other words, `gcp_location` must absolutely be the cluster location.

That doesn't really apply to the majority of users using other tooling (jaeger, prometheus, etc) though, no?

**Comment by kyessenov** [comment]
> > @Stono @howardjohn From GCP perspective, the location has to be the cluster location. That's just an artifact of how internal Monarch system operates, the telemetry is stored based on the monitored resource which is keyed on the cluster location for historical reasons. In other words, `gcp_location` must absolutely be the cluster location.
> 
> That doesn't really apply to the majority of users using other tooling (jaeger, prometheus, etc) though, no? Maybe we need to have two 'location' concepts for the different usages

Yes, that means those users should not use `gcp_location`. That key is reserved for Google purposes. It's not the pod location. In fact, even Google's own SDKs pick different location (Go chooses cluster, C++ chooses pod location) - so it's definitely being confusing even internally.

**Comment by kyessenov** [comment]
I think https://github.com/istio/istio/issues/50379#issuecomment-2202507042 is the right solution, so it needs to be upstreamed to avoid agent-agent overhead.

**Comment by howardjohn** [comment]
That is basically what https://github.com/istio/istio/pull/53821 does so that is good.
