### ISSUE TITLE
Network performance in Ambient - OpenShift

### ISSUE THREAD

**Issue by rsevilla87** [istio/istio#50373]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I'd like to share some of my findings with respect of the networking performance (TCP) observed in an early stage testing I'm doing for ambient mesh running on top of OpenShift.

Before running this simple test I've deployed ambient mesh using the command described in the Version section. The test I've executed consists of running some simple network throughput tests using different tools (iperf3 or netperf) using a pair of client/server pods running in different nodes (to ensure traffic travels through ztunnel), these pods are deployed in a namespace labeled with `istio.io/dataplane-mode=ambient`

The results I've got are pretty relevant after running iperf3 with two threads, packets of 8128 bytes length and traffic traveling through a regular ClusterIP service.

```shell
$ kubectl get svc iperf-service
NAME            TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                                   AGE
iperf-service   ClusterIP   172.30.30.8   <none>        22865/TCP,22865/UDP,43433/TCP,43433/UDP   2d1h
$  kubectl exec -it client-across-5b9f754c44-mxhgq -- bash
sh-5.1$ iperf3 -c 172.30.30.8 -l 8192 -P 2 -p 22865 -t 10
sh-5.1$ iperf3 -c 172.30.30.8 -l 8192 -P 2 -p 22865 -t 10                                                                                                                                                                                     
Connecting to host 172.30.30.8, port 22865
[  5] local 10.131.0.10 port 48300 connected to 172.30.30.8 port 22865
[  7] local 10.131.0.10 port 48314 connected to 172.30.30.8 port 22865                                    
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   302 MBytes  2.53 Gbits/sec    1    942 KBytes       
[  7]   0.00-1.00   sec   303 MBytes  2.54 Gbits/sec    1    743 KBytes       
[SUM]   0.00-1.00   sec   606 MBytes  5.08 Gbits/sec    2              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   1.00-2.00   sec   294 MBytes  2.47 Gbits/sec    0    942 KBytes       
[  7]   1.00-2.00   sec   293 MBytes  2.46 Gbits/sec    0    743 KBytes       
[SUM]   1.00-2.00   sec   588 MBytes  4.93 Gbits/sec    0              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   2.00-3.00   sec   292 MBytes  2.45 Gbits/sec    0    942 KBytes       
[  7]   2.00-3.00   sec   292 MBytes  2.45 Gbits/sec    0    743 KBytes       
[SUM]   2.00-3.00   sec   585 MBytes  4.90 Gbits/sec    0              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   3.00-4.00   sec   291 MBytes  2.44 Gbits/sec    2    942 KBytes       
[  7]   3.00-4.00   sec   290 MBytes  2.44 Gbits/sec    0    743 KBytes       
[SUM]   3.00-4.00   sec   581 MBytes  4.88 Gbits/sec    2              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   4.00-5.00   sec   291 MBytes  2.44 Gbits/sec    0    942 KBytes       
[  7]   4.00-5.00   sec   294 MBytes  2.46 Gbits/sec    2    743 KBytes       
[SUM]   4.00-5.00   sec   585 MBytes  4.91 Gbits/sec    2              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   5.00-6.00   sec   289 MBytes  2.43 Gbits/sec    0    942 KBytes       
[  7]   5.00-6.00   sec   292 MBytes  2.45 Gbits/sec    4    743 KBytes       
[SUM]   5.00-6.00   sec   581 MBytes  4.87 Gbits/sec    4              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   6.00-7.00   sec   291 MBytes  2.44 Gbits/sec    2    942 KBytes       
[  7]   6.00-7.00   sec   293 MBytes  2.45 Gbits/sec    1    743 KBytes       
[SUM]   6.00-7.00   sec   584 MBytes  4.90 Gbits/sec    3              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   7.00-8.00   sec   287 MBytes  2.41 Gbits/sec    0    942 KBytes       
[  7]   7.00-8.00   sec   298 MBytes  2.50 Gbits/sec    3    743 KBytes       
[SUM]   7.00-8.00   sec   585 MBytes  4.91 Gbits/sec    3              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   8.00-9.00   sec   291 MBytes  2.44 Gbits/sec    2    942 KBytes       
[  7]   8.00-9.00   sec   290 MBytes  2.44 Gbits/sec    2    743 KBytes       
[SUM]   8.00-9.00   sec   581 MBytes  4.88 Gbits/sec    4              
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   9.00-10.00  sec   292 MBytes  2.45 Gbits/sec    2    942 KBytes       
[  7]   9.00-10.00  sec   292 MBytes  2.45 Gbits/sec    0    743 KBytes       
[SUM]   9.00-10.00  sec   584 MBytes  4.90 Gbits/sec    2              
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  2.85 GBytes  2.45 Gbits/sec    9             sender
[  5]   0.00-10.05  sec  2.85 GBytes  2.43 Gbits/sec                  receiver
[  7]   0.00-10.00  sec  2.87 GBytes  2.46 Gbits/sec   13             sender
[  7]   0.00-10.05  sec  2.86 GBytes  2.44 Gbits/sec                  receiver
[SUM]   0.00-10.00  sec  5.72 GBytes  4.91 Gbits/sec   22             sender
[SUM]   0.00-10.05  sec  5.71 GBytes  4.88 Gbits/sec                  receiver

iperf Done.
```

From the above we observe that avg throughput was ~4.9 Gbps

Repeating the same test after removing the ambient mesh label, gives a much better result, basically duplicating the throughput obtained with ambient.

```shell
$ kubectl label namespace network-perf istio.io/dataplane-mode-
namespace/network-perf unlabeled
$ kubectl exec -it client-across-5b9f754c44-mxhgq -- bash
bash-5.1$ iperf3 -c 172.30.30.8 -l 8192 -P 2 -p 22865 -t 10
Connecting to host 172.30.30.8, port 22865
[  5] local 10.131.0.10 port 58492 connected to 172.30.30.8 port 22865
[  7] local 10.131.0.10 port 58500 connected to 172.30.30.8 port 22865
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   591 MBytes  4.96 Gbits/sec   42   1.29 MBytes       
[  7]   0.00-1.00   sec   592 MBytes  4.96 Gbits/sec    0   1.36 MBytes       
[SUM]   0.00-1.00   sec  1.16 GBytes  9.92 Gbits/sec   42             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   1.00-2.00   sec   588 MBytes  4.93 Gbits/sec    0   1.30 MBytes       
[  7]   1.00-2.00   sec   588 MBytes  4.93 Gbits/sec    0   1.43 MBytes       
[SUM]   1.00-2.00   sec  1.15 GBytes  9.86 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   2.00-3.00   sec   588 MBytes  4.93 Gbits/sec    0   1.32 MBytes       
[  7]   2.00-3.00   sec   588 MBytes  4.93 Gbits/sec    0   1.43 MBytes       
[SUM]   2.00-3.00   sec  1.15 GBytes  9.87 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   3.00-4.00   sec   587 MBytes  4.92 Gbits/sec    0   1.39 MBytes       
[  7]   3.00-4.00   sec   588 MBytes  4.93 Gbits/sec    0   1.43 MBytes       
[SUM]   3.00-4.00   sec  1.15 GBytes  9.85 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   4.00-5.00   sec   588 MBytes  4.93 Gbits/sec    0   1.43 MBytes       
[  7]   4.00-5.00   sec   589 MBytes  4.94 Gbits/sec    0   1.58 MBytes       
[SUM]   4.00-5.00   sec  1.15 GBytes  9.87 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   5.00-6.00   sec   588 MBytes  4.93 Gbits/sec    0   1.65 MBytes       
[  7]   5.00-6.00   sec   587 MBytes  4.92 Gbits/sec    0   1.65 MBytes       
[SUM]   5.00-6.00   sec  1.15 GBytes  9.85 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   6.00-7.00   sec   587 MBytes  4.93 Gbits/sec    0   1.98 MBytes       
[  7]   6.00-7.00   sec   586 MBytes  4.92 Gbits/sec    0   1.74 MBytes       
[SUM]   6.00-7.00   sec  1.15 GBytes  9.85 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   7.00-8.00   sec   588 MBytes  4.93 Gbits/sec    0   1.98 MBytes       
[  7]   7.00-8.00   sec   588 MBytes  4.93 Gbits/sec    0   1.83 MBytes       
[SUM]   7.00-8.00   sec  1.15 GBytes  9.86 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   8.00-9.00   sec   588 MBytes  4.94 Gbits/sec    0   1.98 MBytes       
[  7]   8.00-9.00   sec   587 MBytes  4.93 Gbits/sec    0   2.06 MBytes       
[SUM]   8.00-9.00   sec  1.15 GBytes  9.86 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[  5]   9.00-10.00  sec   588 MBytes  4.93 Gbits/sec    0   1.98 MBytes       
[  7]   9.00-10.00  sec   588 MBytes  4.93 Gbits/sec    0   2.06 MBytes       
[SUM]   9.00-10.00  sec  1.15 GBytes  9.86 Gbits/sec    0             
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  5.74 GBytes  4.93 Gbits/sec   42             sender
[  5]   0.00-10.00  sec  5.74 GBytes  4.93 Gbits/sec                  receiver
[  7]   0.00-10.00  sec  5.74 GBytes  4.93 Gbits/sec    0             sender
[  7]   0.00-10.00  sec  5.74 GBytes  4.93 Gbits/sec                  receiver
[SUM]   0.00-10.00  sec  11.5 GBytes  9.87 Gbits/sec   42             sender
[SUM]   0.00-10.00  sec  11.5 GBytes  9.86 Gbits/sec                  receiver
```

### Version

```Text
Ambient mesh was deployed with: 

$ ./istioctl install --set hub=gcr.io/istio-testing --set tag=1.22-alpha.f1898ff2fc1406b7899dcf2409876f94b0e76dca --set profile=openshift-ambient
```

### Additional Information

The tests were performed in an OpenShift cluster deployed in AWS and pods ran in m6i.2xlarge nodes (max bandwidth of 12.5Gbps)

Results from another test comparing results with regular istio 1.18.5 and Envoy 1.26.8 and no proxied traffic

![image](https://github.com/istio/istio/assets/4614641/3f37b2a7-7ef5-42a4-bf60-064187f1005a)

**Comment by howardjohn** [comment]
The sharp drop off at ~4.9Gb/s is suspicious. Here is what I get:

same node

naked
[SUM]   0.00..10.00 sec  23.80 GiB   20.45 Gbits/sec        sender
[SUM]   0.00..10.00 sec  23.71 GiB   20.37 Gbits/sec        receiver

ambient (debug)
[SUM]   0.00..10.01 sec  4.10 GiB   3.52 Gbits/sec        sender
[SUM]   0.00..10.00 sec  4.07 GiB   3.49 Gbits/sec        receiver

ambient (release)
[SUM]   0.00..10.00 sec  10.11 GiB   8.69 Gbits/sec        sender
[SUM]   0.00..10.00 sec  10.05 GiB   8.63 Gbits/sec        receiver

Envoy 
[SUM]   0.00..10.00 sec  11.67 GiB   10.03 Gbits/sec        sender
[SUM]   0.00..10.00 sec  11.61 GiB   9.97 Gbits/sec        receiver

-----

Cross node


naked
[SUM]   0.00..10.00 sec  15.36 GiB   13.19 Gbits/sec        sender
[SUM]   0.00..10.00 sec  15.30 GiB   13.15 Gbits/sec        receiver

ambient (debug)
[SUM]   0.00..10.00 sec  5.74 GiB   4.93 Gbits/sec        sender
[SUM]   0.00..10.00 sec  5.70 GiB   4.90 Gbits/sec        receiver

ambient (release)
[SUM]   0.00..10.00 sec  14.21 GiB   12.21 Gbits/sec        sender
[SUM]   0.00..10.00 sec  14.14 GiB   12.14 Gbits/sec        receiver

Envoy
[SUM]   0.00..10.00 sec  10.79 GiB   9.27 Gbits/sec        sender
[SUM]   0.00..10.00 sec  10.73 GiB   9.22 Gbits/sec        receiver


----

Note similar bad numbers when running a debug build of Ztunnel. Make sure you aren't doing that (I first did it by accident :slightly_smiling_face: ; the official builds are all "release" builds though).

One other thing is for same node, performance is actually worse since the same traffic is all going through one process instead of 2. Unlike sidecars, where its always 2.

But overall in my testing I am seeing slightly better performance with ambient. 

Given your result is not "Envoy is slightly faster" but rather "Ztunnel is neck and neck with Envoy but Ztunnel caps at 4.9Gb/s", that seems like we are hitting some unexpected limit somewhere

**Comment by rsevilla87** [comment]
> The sharp drop off at ~4.9Gb/s is suspicious. Here is what I get:
> 
> same node
> 
> naked [SUM] 0.00..10.00 sec 23.80 GiB 20.45 Gbits/sec sender [SUM] 0.00..10.00 sec 23.71 GiB 20.37 Gbits/sec receiver
> 
> ambient (debug) [SUM] 0.00..10.01 sec 4.10 GiB 3.52 Gbits/sec sender [SUM] 0.00..10.00 sec 4.07 GiB 3.49 Gbits/sec receiver
> 
> ambient (release) [SUM] 0.00..10.00 sec 10.11 GiB 8.69 Gbits/sec sender [SUM] 0.00..10.00 sec 10.05 GiB 8.63 Gbits/sec receiver
> 
> Envoy [SUM] 0.00..10.00 sec 11.67 GiB 10.03 Gbits/sec sender [SUM] 0.00..10.00 sec 11.61 GiB 9.97 Gbits/sec receiver
> 
> Cross node
> 
> naked [SUM] 0.00..10.00 sec 15.36 GiB 13.19 Gbits/sec sender [SUM] 0.00..10.00 sec 15.30 GiB 13.15 Gbits/sec receiver
> 
> ambient (debug) [SUM] 0.00..10.00 sec 5.74 GiB 4.93 Gbits/sec sender [SUM] 0.00..10.00 sec 5.70 GiB 4.90 Gbits/sec receiver
> 
> ambient (release) [SUM] 0.00..10.00 sec 14.21 GiB 12.21 Gbits/sec sender [SUM] 0.00..10.00 sec 14.14 GiB 12.14 Gbits/sec receiver
> 
> Envoy [SUM] 0.00..10.00 sec 10.79 GiB 9.27 Gbits/sec sender [SUM] 0.00..10.00 sec 10.73 GiB 9.22 Gbits/sec receiver
> 
> Note similar bad numbers when running a debug build of Ztunnel. Make sure you aren't doing that (I first did it by accident 🙂 ; the official builds are all "release" builds though).
> 
> One other thing is for same node, performance is actually worse since the same traffic is all going through one process instead of 2. Unlike sidecars, where its always 2.
> 
> But overall in my testing I am seeing slightly better performance with ambient.
> 
> Given your result is not "Envoy is slightly faster" but rather "Ztunnel is neck and neck with Envoy but Ztunnel caps at 4.9Gb/s", that seems like we are hitting some unexpected limit somewhere

Thanks for your response, I've repeated the same test after updating the ztunnel image to the latest stable one suggested, namely `gcr.io/istio-release/ztunnel:1.21.1`, but no luck so far (throughput still capped at ~4.9Gbps), the performance bottleneck seems to be something specific to OpenShift. I'll continue my investigations...

**Comment by howardjohn** [comment]
I actually would recommend using the latest nightly builds (1.22-alpha.xxx), just if you build it yourself it may be in debug mode. If you use the gcr.io/istio-testing ones they should be release mode

**Comment by rsevilla87** [comment]
> I actually would recommend using the latest nightly builds (1.22-alpha.xxx), just if you build it yourself it may be in debug mode. If you use the gcr.io/istio-testing ones they should be release mode

sorry, I don't follow you (I'm not very familiarized with all the istio ecosystem yet), the release I used for my latest test was from grc.io/istio-release, which I supposed it's in release mode and results were bad, how is possible that builds from istio-testing are in release mode as well?

**Comment by howardjohn** [comment]
Rust has "debug" and "release" profiles. Debug builds are super slow (and large) and not intended for real world

Istio builds we publish to docker are always "release" builds. gcr.io/istio-testing stores pre-release builds for each commit, and gcr.io/istio-release stores official releases; both of these are built the same way ("release" mode)

If you just build yourself from the repo (`cargo build`, etc) you will get a debug build. If you are not doing your own build (as it looks like you are not), then you should be fine.

tl;dr: "release" has 2 meanings

**Comment by rsevilla87** [comment]
> Rust has "debug" and "release" profiles. Debug builds are super slow (and large) and not intended for real world
> 
> Istio builds we publish to docker are always "release" builds. gcr.io/istio-testing stores pre-release builds for each commit, and gcr.io/istio-release stores official releases; both of these are built the same way ("release" mode)
> 
> If you just build yourself from the repo (`cargo build`, etc) you will get a debug build. If you are not doing your own build (as it looks like you are not), then you should be fine.
> 
> tl;dr: "release" has 2 meanings

got it, thanks for the explanation. With that, then I can confirm that I'm hitting the performance issue using a ztunnel release build (tested with gcr.io/istio-testing/ztunnel:1.22-dev and gcr.io/istio-release/ztunnel:1.21.1)

**Comment by howardjohn** [comment]
@rsevilla87 did you ever get more info here? Note performance in 1.23 (currently master) should be about 40% higher for this type of workload
