### ISSUE TITLE
Authentication Policy missing `request.auth.claims` attribute

### ISSUE THREAD

**Issue by theganyo** [istio/istio#5040]
The new Authentication Policy should expose a `request.auth.claims` attribute. See: https://preliminary.istio.io/docs/concepts/security/authn-policy.html.

However, this attribute hasn't been defined for Mixer. I get an error attempting to use it (in 0.7.1, 0.8, and HEAD):

2018-04-18T00:20:16.772654Z	error	Unable to initialize adapter: snapshot='6', handler='apigee-handler.apigee.istio-system', adapter='apigee', err='cannot infer type information from params in instanceConfig 'apigee.authorization.istio-system': failed to evaluate expression for field 'Subject'; failed to evaluate expression for field 'Subject.Properties[encoded_claims]'; unknown attribute request.auth.claims’.

This attribute is a must-have for me to use the policy. Thanks!

**Comment by theganyo** [comment]
Note: There is a similar, older issue having to do with the old EUA policy that could probably be closed as irrelevant: https://github.com/istio/istio/issues/3194.

**Comment by qiwzhang** [comment]
Are you using authn config?  Is it Envoy config generated by Pilot?  The code is in
https://github.com/istio/proxy/blob/master/src/istio/control/http/attributes_builder.cc#L89

If not working, we need to debug it.  Please provide your config detail

**Comment by theganyo** [comment]
Yes, that code is in Proxy... and is probably fine there, but Mixer doesn't understand that `request.auth.claims` is a valid attribute. I don't know where all it needs to be declared in Mixer, but you can see that the generated vocabulary is missing this attribute: https://preliminary.istio.io/docs/reference/config/mixer/attribute-vocabulary.html.

**Comment by lei-tang** [comment]
In the PR https://github.com/istio/istio/pull/5136, the tests istio/mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go and istio/mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go show that the request.auth.claims is in Mixer. These two tests in the PR 5136 configure the Istio authn policy, send a HTTP request, and verify that the attributes at Mixer are as expected.

**Comment by lei-tang** [comment]
The SHA of the api repo used in the release-0.8 branch is 9d978d76653da8b7b4bd6421b7e8f9925d8c79ea, which was committed in two months ago. Thus the recent changes on the api repo are not included in the release-0.8 branch yet. According to the following comments in the istio/istio.deps in the release-0.8 branch, the dependency of api repo is auto updated by a robot: 
	{
		"_comment": "This file is auto updated by a robot executing `https://github.com/istio/test-infra/blob/master/prow/test-infra-update-deps.sh`.",
		"name": "istio.io/api",
		"repoName": "api",
		"prodBranch": "master",
		"file": "Gopkg.toml",
		"lastStableSHA": "9d978d76653da8b7b4bd6421b7e8f9925d8c79ea"
	},

**Comment by theganyo** [comment]
What needs to happen to get the api changes merged into release-0.8? @douglas-reid ?

**Comment by theganyo** [comment]
@mandarjog can you help?

**Comment by theganyo** [comment]
Just linking to a file with the missing attribute for quick reference: https://github.com/istio/istio/blob/release-0.8/mixer/pkg/attribute/list.gen.go

**Comment by hklai** [comment]
This was brought to my attention today and there is some confusion about whether this is release blocking for 0.8.0.

Could someone provide some detail if this is indeed blocking 0.8? If so, it needs to be tracked in https://docs.google.com/spreadsheets/d/1KquD8HJLlg-IwGYuF6O8AqJMpJPWLHjA-VEY24Eu8b8/edit#gid=0.

**Comment by lei-tang** [comment]
The following code in istio/Gopkg.lock shows that the SHA for "istio.io/api" repo used by release-0.8 has been updated to 170445541e5b5a1515b52c9c9596570220679a27, which is committed on May 3, 2018. So the request.auth.claims should have been in the release-0.8 branch. In the commit https://github.com/istio/istio/commit/23a8d3ec89c79f891d1d14fb1133f4596d5f32b7 in the release-0.8 branch, the tests istio/mixer/test/client/istio_authn_origin_jwt_bound_origin/authn_report_test.go and istio/mixer/test/client/istio_authn_peer_jwt_bound_peer/authn_report_test.go show that the request.auth.claims is in Mixer. These two tests configure the Istio authn policy, send a HTTP request, and verify that the attributes at Mixer are as expected.

[[projects]]
  branch = "master"
  name = "istio.io/api"
  packages = [
    "authentication/v1alpha1",
    "broker/dev",
    "envoy/config/filter/http/authn/v2alpha1",
    "mesh/v1alpha1",
    "mixer/adapter/model/v1beta1",
    "mixer/v1",
    "mixer/v1/config/client",
    "networking/v1alpha3",
    "policy/v1beta1",
    "rbac/v1alpha1",
    "routing/v1alpha1"
  ]
  revision = "170445541e5b5a1515b52c9c9596570220679a27"

**Comment by hklai** [comment]
Thanks @lei-tang. If the fix is already in release-0.8, I suppose no additional work is needed and hence this is not blocking anymore.

For reference, please make sure to add the [kind/blocking release](https://github.com/istio/istio/labels/kind%2Fblocking%20release) label to the blocking issues in future to make sure issues won't fall through the crack.

**Comment by douglas-reid** [comment]
@hklai @theganyo @mandarjog we need to run `go generate ./mixer/pkg/attribute/...` on the branch.

I rebased to the release-0.8 branch, and was able to generate the following diff:

```
index 06311870e..1bf9545d1 100644
--- a/mixer/pkg/attribute/list.gen.go
+++ b/mixer/pkg/attribute/list.gen.go
@@ -185,5 +185,7 @@ var (
               "connection.event",
               "check.cache_hit",
               "quota.cache_hit",
+               "source.principal",
+               "request.auth.claims",
    }
```

**Comment by douglas-reid** [comment]
@theganyo we also need to update the attribute manifest. Example: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml#L85

**Comment by theganyo** [comment]
Status update: I've added the necessary `request.auth.claims` attributes in mixer, but there's a bigger problem that will need to be solved: Proxy is processing and delivering `request.auth.claims` as a string map and will need to be rewritten to deliver a string.

**Comment by lei-tang** [comment]
Alternatively, the string map of request.auth.claims produced by the proxy can be converted into a string by a consumer of the request.auth.claims. Different consumers of request.auth.claims may want to convert the string map of the claims into different formats of  strings based on their own requirements, e.g, a string of claims delimited by comma, or by semicolon, and so on.

**Comment by theganyo** [comment]
That wouldn't be sufficient. JWT claim values can be complex and the existing implementation on Proxy drops all JWT claims that don't have simple string values.

**Comment by theganyo** [comment]
After discussing with @mandarjog, we've decided to move forward with the string map and file a separate issue against the proxy for it to include raw string values for all claims. Meanwhile, I'll submit a PR for this shortly.

**Comment by mandarjog** [comment]
`request.auth.claims_raw` contains the original claims from the header.
We need to add this as a `string` attribute to the attribute vocabulary.
We should revisit this solution, if we want `map<string, string>` to contain all claims or just simple claims.

**Comment by douglas-reid** [comment]
is `request.auth.claims_raw` a final naming decision?  should this be `request.auth.raw_claims` to better match style guidelines?  or maybe `request.auth.claims.raw` and `request.auth.claims.map` ?

**Comment by theganyo** [comment]
It's actually `raw_claims`: https://github.com/istio/proxy/pull/1744. But as Mandar mentioned, it's not yet in the mixer attributes.

**Comment by diemtvu** [comment]
The name is indeed request.auth.raw_claims.

I didn't add the attribute to [global_dictionary](https://github.com/istio/api/blob/master/mixer/v1/global_dictionary.yaml), as per my understanding, it is for optimization mainly. However, feel free to add it, or let me know if you want me to do. Other than that, I don't know any other place we need to change to hook up with mixer. As long as (mixer) client send the attribute, mixer should see it, right?

**Comment by theganyo** [comment]
verified as fixed in nightly build. thanks!
