### ISSUE TITLE
Workload IDs for non-k8s workloads

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#5045]
For the purpose of telemetry, workloads carry an ID so that Mixer can extract additional metadata about the workloads. For kubernetes, it's of the form `kubernetes://podX.nsY`. How do we deal with non-kubernetes workloads, such as VMs or mesh expansion?

**Comment by douglas-reid** [comment]
Not stale. @jeffmendoza has been doing some thinking on this issue recently.

**Comment by ayj** [comment]
related https://github.com/istio/api/issues/610

**Comment by douglas-reid** [comment]
I think it is time to close this. Mixer is no longer a going concern, and VM identity has evolved.
