### ISSUE TITLE
Write a VAP for Istio annotations and labels

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50462]
A https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/ could be written to ensure valid formation of labels and annotations in Istio. This is beneficial as we don't deploy (or want to be on the critical path) webhooks for things like services, namespaces, etc. 

cc @keithmattix 

We could also start by just validating the new ambient ones if we feel this is somehow risky

**Comment by keithmattix** [comment]
So the idea is to just make sure the istio.io/ family of labels and annotations comes from a known set?

**Comment by howardjohn** [comment]
Not just a known set, some have semantics on what is valid. must be a bool, etc
