### ISSUE TITLE
Enrich the debug API to dump the configuration from configStore

### ISSUE THREAD

**Issue by spacewander** [istio/istio#50480]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

Sometimes, when multiple configuration stores are enabled (for example, mcp and k8s), it would be useful to dump the final  configuration received by istio. It also provides an unite interface to debug the resource generated by the mcp.

There is a debug API to dump the schema of watched resources:
https://github.com/istio/istio/blob/d7df7b9c825064c8912c991aeb12df0eaeb41737/pilot/pkg/xds/debug.go#L196

What about extending it to also dump the resources? For example, using `/debug/resourcesz?list=envoyfilter` to list the envoyfilters.

If this proposal is accepted, I would like to contribute code.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
configz does this I think?

**Comment by spacewander** [comment]
> configz does this I think?

That's what I want! Thank you.
