### ISSUE TITLE
Incomplete CDS response cause cluster_not_found error during xds update

### ISSUE THREAD

**Issue by freedomljc** [istio/istio#50487]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

During CDS update, istiod might return incomplete CDS response, thus causing cluster_not_found error for local cluster `inbound|80||`. However, after <1 min, the istiod seems to start to return correct CDS response, as the cluster_not_found error is gone.

envoy proxy log:

CDS: update / add cluster `inbound|1080||`, and remove `inbound|80||`
<img width="1675" alt="Screenshot 2024-04-16 at 10 14 29 AM" src="https://github.com/istio/istio/assets/6963707/f32f0226-0a6c-4b57-bf66-c81009a9fdd7">

`cluster_not_found` error started to happen shortly
<img width="1641" alt="Screenshot 2024-04-16 at 7 51 41 AM" src="https://github.com/istio/istio/assets/6963707/658f3ffc-c6ad-4f17-a07b-3f270514991f">

istiod log:
<img width="1097" alt="Screenshot 2024-04-16 at 10 27 04 AM" src="https://github.com/istio/istio/assets/6963707/922bffcc-b27d-49df-aadb-c9e17ef6231d">

### Version

```Text
data plane version: 1.20.0
istiod version: 1.20.0
```

**Comment by ramaraochavali** [comment]
Can you please share istiod log and proxy log?

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/49507 Was backported, but not 1.20.0. Can you upgrade to have a test

**Comment by freedomljc** [comment]
Thanks for responses, I'll report it back once we try out the new version.

**Comment by ramaraochavali** [comment]
The fix was not backported to 1.20
