### ISSUE TITLE
grafana:87cdc595-689d-4779-be29-ac845d47492e not available

### ISSUE THREAD

**Issue by mwieczorek** [istio/istio#505]
**Using version:** https://github.com/istio/istio/commit/64d469a318a6588de9dcdf6c6ecc183fae4ac588 

**Issue:**
I'm following docs: https://istio.io/docs/tasks/installing-istio.html

```
kubectl apply -f install/kubernetes/addons/grafana.yaml
```
Grafana pod is in state ErrImagePull
Logs:
```
Failed to pull image "gcr.io/istio-testing/grafana:87cdc595-689d-4779-be29-ac845d47492e"
```

I think image set in:
https://github.com/istio/istio/blob/f0d452d20fb55193551daa2df74d0de2cd5d22bb/install/kubernetes/addons/grafana.yaml#L29
is not available.
When I searched it manually by that tag (https://console.cloud.google.com/gcr/images/istio-testing/GLOBAL/grafana?pli=1) I couldn't find it.

**Comment by ldemailly** [comment]
it's fixed I think - now gcr.io/istio-testing/grafana:3561e297ceb365ba990cbf376d99713b0a0add69

**Comment by kyessenov** [comment]
I don't know where grafana comes from.

**Comment by ldemailly** [comment]
@kyessenov I closed the issue so it doesn't matter who is assigned,  but I had assigned it to you because git blame showed you were the one that updated the sha
