### ISSUE TITLE
Add feature flag to disable default retry policy

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#50506]
There is default retry policy hard coded which will retry twice on connection issue or 503 introduced by https://github.com/istio/istio/pull/10566:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/route/retry/retry.go#L34-L48
```
func DefaultPolicy() *route.RetryPolicy {
	policy := route.RetryPolicy{
		NumRetries:           &wrappers.UInt32Value{Value: 2},
		RetryOn:              "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
		RetriableStatusCodes: []uint32{http.StatusServiceUnavailable},
		RetryHostPredicate: []*route.RetryPolicy_RetryHostPredicate{
			// to configure retries to prefer hosts that haven’t been attempted already,
			// the builtin `envoy.retry_host_predicates.previous_hosts` predicate can be used.
			xdsfilters.RetryPreviousHosts,
		},
		// TODO: allow this to be configured via API.
		HostSelectionRetryMaxAttempts: 5,
	}
	return &policy
}
```

In our production environment we have thousands of VirtualServices created without retry policy which means it's using the default. 

For most cases we don't see issue but we are seesing problems with idempotent POST request retry and some POST requests are actually payout, which eventually caused double payout issue.

Here is one case we got for the double pay due to retry:

```
IngressGateway access log
2024-04-14 08:31:51.000 
bytes_received=85 bytes_sent=0 configId= duration=0 filename=accesslog method=POST path=/create_repayments protocol=HTTP/1.1 response_code=0 response_code_details=downstream_remote_disconnect response_flags=DC start_time=2024-04-14T00:31:51.244Z 

Sidecar access log
2024-04-14 08:31:52.000 
bytes_received=85 bytes_sent=0 configId= duration=0 filename=accesslog method=POST path=/create_repayments protocol=HTTP/1.1 response_code=0 response_code_details=downstream_remote_disconnect response_flags=DC route_name=default start_time=2024-04-14T00:31:51.244Z 
```

So we want to disable the default retry and instead one by one by setting the VirtualService retry num to 0, it could be better to have a feature flag globally. 

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L1318 - you can use Mesh Config to configure default retry policy

**Comment by Stono** [comment]
Please see my comments here: https://github.com/istio/istio/issues/51704#issuecomment-2188555136; i don't believe Istios default retry policy should include `retryable-status-codes`.

**Comment by ramaraochavali** [comment]
> i don't believe Istios default retry policy should include retryable-status-codes.

I think it can have retryable-status-codes for services to use [x-envoy-retriable-statuscodes](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retriable-status-codes) and control status codes themselves. Defaulting to 503 is not correct IMO

**Comment by Stono** [comment]
> > i don't believe Istios default retry policy should include retryable-status-codes.
> 
> I think it can have retryable-status-codes for services to use [x-envoy-retriable-statuscodes](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retriable-status-codes) and control status codes themselves. Defaulting to 503 is not correct IMO

👍 also works.

**Comment by Stono** [comment]
Just to call out i went down a rabbithole today (https://github.com/istio/istio/issues/51762) trying to retry 503's that were actually caused by reset.

They were again resets before headers, so an istio level default policy of `retry-before-request` would have saved me from that! 

Also I learned that the `503` you see in the case of a `UC` won't be retried by Istios default policy anyway because it isn't a "real" 503 (see the linked issue).  Therefore the only 503 being retried by istio right now is one returned from an upstream (easily happens in a microservice architecture as you'll get 503UC (destination) -> 503 (middle service) -> app

**Comment by howardjohn** [comment]
`defaultHttpRetryPolicy` is availabie in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/. Also a valid point wrt to whether our default-defaults should change though

**Comment by sschepens** [comment]
@howardjohn I think defaults should probably change, I don't think it's good for Istio to have "unsafe" defaults enabled by default.

**Comment by shonecyx** [comment]
I think it would be better to remove the `retriable-status-codes` 503 since for most cases we don't know if the 503 is retriable, especially for the post request.

**Comment by ramaraochavali** [comment]
I agree. I am working on a PR for that

**Comment by oyvindwe** [comment]
Apologies if this should be a separate issue, but is the [reference documentation](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute-retries) outdated, as it stills lists 503?

> Note: the default cluster-wide retry policy, if not specified, is:
>
> ```yaml
> attempts: 2
> retryOn: "connect-failure,refused-stream,unavailable,cancelled,503"
> ```

**Comment by ramaraochavali** [comment]
Yes. Sorry. PR for for doc update https://github.com/istio/api/pull/3416

**Comment by Kyslik** [comment]
@ramaraochavali latest docs are still "outdated" (contain `503` as default).

**Comment by ramaraochavali** [comment]
can you share the link where you are seeing this outdated text?

**Comment by Kyslik** [comment]
👋🏻 the same as @oyvindwe linked - https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute-retries.

> Retry policy for HTTP requests.
> 
> Note: the default cluster-wide retry policy, if not specified, is:
> 
> ```
> attempts: 2
> retryOn: "connect-failure,refused-stream,unavailable,cancelled,503"
> ```
> 
> This can be customized in [Mesh Config defaultHttpRetryPolicy](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig).

**Comment by ramaraochavali** [comment]
Ok. Thank you.

Sorry -I missed to update the example. Only fixed doc comments of that field. https://github.com/istio/api/pull/3514 to fix it

**Comment by king-of-poppk** [comment]
@shonecyx Sorry but can you elaborate on how retrying something truly "idempotent" can be a problem?
