### ISSUE TITLE
PILOT_ENABLE_STATUS won't take effect if it is set without PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING

### ISSUE THREAD

**Issue by spacewander** [istio/istio#50500]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Since https://github.com/istio/istio/pull/43226, the PILOT_ENABLE_STATUS only takes effect when PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING is also set to true. Is this behavior intended? If it is, maybe we can mark PILOT_ENABLE_STATUS as deprecated as it doesn't have a unique meaning.

### Version

```Text
$ istioctl version                                                                          
client version: 1.21.0
control plane version: unknown
data plane version: 1.21.0 (2 proxies)
$ kubectl version --short
Client Version: v1.25.11
Kustomize Version: v4.5.7
Server Version: v1.25.11
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hanxiaop** [comment]
Wasn't sure if that flag was designed to control the write status for different controllers, such as gateway/analysis, or if it is just for config distribution tracking. If it's the latter, I think we can deprecate it.

**Comment by spacewander** [comment]
On the other side, only setting PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING won't take effect if PILOT_ENABLE_STATUS is not set. Maybe we can deal with this together during the deprecation.
