### ISSUE TITLE
Istio pilot e2e integration tests for ExternalName break without ENABLE_EXTERNAL_NAME_ALIAS

### ISSUE THREAD

**Issue by nshankar13** [istio/istio#50517]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The istio pilot integration tests assume that the pilot env variable ENABLE_EXTERNAL_NAME_ALIAS is enabled (along with other vars set in [base.yaml](https://github.com/istio/istio/blob/master/tests/integration/base.yaml#L19-L24)). However, this fails on environments where Istio is pre-installed without the external name env variable set. 

The fix for this would be to add logic in the tests to verify whether the env variable is set and run the test accordingly (perhaps by also providing a corresponding CLI flag to pass into the e2es for `enableExternalNameAlias`). In general, ideally, the e2es should not make assumptions about Istio installation settings and should instead have greater flexibility to account for various env vars and installation settings - this experience would be in line with previous improvements to break assumptions in the test suites about namespaces, selectors, etc. 

### Version

```Text
From release-1.20 onwards.
```

**Comment by howardjohn** [comment]
There is a pretty large set of assumptions made about other variables as well fwiw

**Comment by keithmattix** [comment]
True, but we probably shouldn't write tests assuming that a feature flag that defaults to off is turned on

**Comment by howardjohn** [comment]
It defaults to `true`

**Comment by keithmattix** [comment]
@nshankar13 if this is already default true in 1.21+, then I think this is probably fine right?
@howardjohn SetForTest probably helps reduce the overhead, but probably moot at this point IMO

**Comment by howardjohn** [comment]
`SetForTest` doesn't work in e2e tests

**Comment by howardjohn** [comment]
Unless we expose a debug interface for it :thinking: except we probably don't handle them dynamically changing (in unit tests, we change it before any setup

**Comment by keithmattix** [comment]
Ah this is for e2es you're right 🤔 yeah the separate test suite for each dependent test is a pain but doable if needed. +1 that dynamically changing likely breaks a lot of our assumptions using these feature flags

**Comment by nshankar13** [comment]
I think there are 2 things here: 1) how to prevent future changes that make assumptions and 2) what to to about existing assumptions.

For 1: how about a new test suite in CI called `istioPreInstalled` or something with different settings (namespaces, labels, selectors, etc) that runs various integration tests. 

The idea here is to preemptively catch PRs / corresponding e2e changes that make assumptions about certain settings being enabled.

If this is overkill, we can instead add a checklist with "e2e best practices/guidelines" for PRs that touch the e2e dir. 

For 2: I don't have a great answer besides adding more CLI flags for running the tests like we did for the ingress / egress gateways and systemNamespace - then the tests would have logic and conditionals to handle diff values accordingly.

**Comment by keithmattix** [comment]
I lost track of this, but let's track it for 1.23.
