### ISSUE TITLE
Ambient: The service account waypoint is only take effect on inbound and not  outbound.

### ISSUE THREAD

**Issue by luohua13** [istio/istio#50522]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a deployment "httpbin-a" that hava a service account "httpbin-a" and a deployment "httpbin-b" that have a service account  "httpbin-b", then I run "istioctl x waypoint apply --service-account httpbin-a --wait". Finally, when I send request from "httpbin-b" to "httpbin-a", the traffic is intercepted by the service account waypoint, but when I send request form "httpbin-a" to "httpbin-b", the traffic is not intercepted by the service account waypoint.

Whether deployment "httpbin-a" is acting as a client or a server, shouldn't the most reasonable behavior be that all traffic is intercepted?
### Version

```Text
$istioctl version
client version: 1.21.1
control plane version: 1.21.1
data plane version: 1.21.1 (8 proxies)

$kubectl version
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
The current design of waypoints is the only apply to incoming traffic, not outgoing traffic. Once we ship the beta in 1.22 we will start to look at "egress waypoints" to handle these cases.

Do you have specific use cases in mind where this is desirable to help us plan, or just found it unexpected?

**Comment by luohua13** [comment]
> The current design of waypoints is the only apply to incoming traffic, not outgoing traffic. Once we ship the beta in 1.22 we will start to look at "egress waypoints" to handle these cases.
> 
> Do you have specific use cases in mind where this is desirable to help us plan, or just found it unexpected?

Yeah, I'm trying it and just found it unexpected.
