### ISSUE TITLE
Ambient: Create service account waypoint first and then create namespace waypoint on the same namespace, an error "Empty reply from server" will happen. 

### ISSUE THREAD

**Issue by luohua13** [istio/istio#50523]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I create a service account waypoint firstly, I send request from client to server and the server's response is ok. Then I create a namespace waypoint on the same namespace, I send request from client to server and the server's response is "curl: (52) Empty reply from server". Finally I restart the server and the response is ok.

### Version

```Text
$istioctl version
client version: 1.21.1
control plane version: 1.21.1
data plane version: 1.21.1 (8 proxies)

$kubectl version
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Thanks for the report, sorry this looks like it slipped under the radar (somehow didn't get automatically labeled like it was supposed to?). This code was changed dramatically and basically re-written from scratch in 1.22, so I think this is obsolete. Please let us know if you see issues with 1.22. Thanks!
