### ISSUE TITLE
Istio-operator  deprecated CustomResourceDefinition API version error

### ISSUE THREAD

**Issue by emeg1** [istio/istio#50526]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am installing Istio using the official Istio operator helm chart to an EKS cluster (kubernetes version 1.26) but getting error   ["Helm install failed: failed to install CRD crds/crd-operator.yaml: unable to recognize "": no matches for kind "**CustomResourceDefinition**" in version "**apiextensions.k8s.io/v1beta1"** ]

The same helm chart was working perfectly when running an older Kubernetes version e.g v1.21.

Kubernetes deprecated  apiextensions.k8s.io/v1beta1 in v1.22 (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122). Hence, when I run 
"kubectl api-resources | grep CustomResourceDefinition" I get

customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1           

Searching through your code, I can see the deprecated API version "apiextensions.k8s.io/v1beta1" being used for the CRD "https://github.com/istio/istio/blob/12b77bc7c1fcaaac91ee0480b026b7e87db05ff9/operator/cmd/mesh/testdata/operator/output/operator-remove.yaml#L122"

Can this be updated to use the supported API version? Or Is there a way I can resolve this considering I want to continue using Istio operator's official helm chart.

### Version

```Text
kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.13-eks-508b6b
```

**Comment by howardjohn** [comment]
Which istio version?

**Comment by vinothvenkatachalam2406** [comment]
we have tried to use latest version as well 1.21. but still facing issue

**Comment by emeg1** [comment]
@howardjohn   using HelmRelease for Istio 
    GitRepository   
    url: https://github.com/istio/istio ref:tag: 1.9.2 and also tried tag: 1.21.1  
    chart: ./manifests/charts/istio-operator

**Comment by howardjohn** [comment]
```
((HEAD detached at 1.21.1))
$ rg CustomRes manifests/charts/istio-operator -C1
manifests/charts/istio-operator/crds/crd-operator.yaml
2-apiVersion: apiextensions.k8s.io/v1
3:kind: CustomResourceDefinition
```

Are you sure you are on 1.21?

**Comment by howardjohn** [comment]
Seems like you still have `tag: 1.9.2`, no?

I cannot express enough how bad of an idea it is to run Istio 1.9 in 2024. It is ancient software full of CVEs, critical bugs, obsolete APIs, and more. I strongly recommend you make it a priority to move off of it.

**Comment by emeg1** [comment]
My bad, should have commented it out. The old code had 1.9.2 but have been testing today using v1.21.1 . Thanks for your prompt reply @howardjohn. Still reviewing updates in the new release. Will let you know how it goes

**Comment by howardjohn** [comment]
I am fairly sure if its somehow happening on v1.21 its a stale error or something else. I am certain Istio 1.21 does not use the old CRD.

**Comment by howardjohn** [comment]
Nice, glad its resolved
