### ISSUE TITLE
Helm chart schema should allow boolean on annotations

### ISSUE THREAD

**Issue by cparis** [istio/istio#50543]
In the gateway Helm schema currently String and Integer types are allowed for additional annotations.   But many times annotations are booleans which is not in the list of allowed schema types for annotations.

### Use Case: 
Azure has a setting to allocate an internal IP address, using a boolean value:

`helm install istio-ingressgateway istio/gateway -n istio-system --set annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=true`

### Expected Behavior:
Value is accepted and sets it in the annotation as a boolean.

### Actual Result:

> Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
> gateway:
> - annotations.service.beta.kubernetes.io/azure-load-balancer-internal: Invalid type. Expected: [string,integer], given: boolean

### Proposed Fix in each values.schema.json:

```
        "annotations": {
          "additionalProperties": {
            "type": [
              "string",
              "integer",
              "boolean"
            ]
          },
          "type": "object"
        },
```

### Partial Workaround:

You can force helm to set the value as a string using --set-string, but, this wraps the value in "" and is not a true boolean.

`helm install istio-ingressgateway istio/gateway -n istio-system --set-string annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=true`

**Comment by howardjohn** [comment]
An annotation in kubernetes is a string so I don't see what the issue is with --set-string? 

If you don't have the quotes kubernetes will reject it
