### ISSUE TITLE
No liveness probe for envoy sidecar

### ISSUE THREAD

**Issue by nsu700** [istio/istio#50550]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Recently we hit an issue that the sidecar suddently not ready and could not collect related logs for further troubleshooting, hence we are trying to find a way to auto restart it, however we found that there is only readiness probe but no liveness probe, may I know what is the reason why there is no liveness probe for the envoy proxy, thanks

### Version

```Text
istio version: 1.18.5
envoy proxy: 1.26.8
```

**Comment by j2gg0s** [comment]
- Sidecar need readiness. It needs initialize resource before serve request

- If your container has liveness, istio will use sidecar's port replace it when injecting.
So if your container fails, sidecar also fails.

My opinion:
Just like application contaienr, it's difficult to define whether sidecar can still provide all the services.
So just dont define it.

**Comment by nsu700** [comment]
We found [this page](https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/) and know that both the liveness and readiness probe of the app will be automatically rewrite by istio, it is ok for us, but now our issue is that the sidecar fails but because there is no liveness probe of the sidecar, the app still running(at least the pod not being restarted, we have liveness probe on the app), that's why we are looking for a way to define liveness probe for the sidecar

**Comment by howardjohn** [comment]
Liveness probe is intentionally not configured as it is generally not seen as beneficial (see https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html).

If your opinions differ, no problem - you can customize in https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
