### ISSUE TITLE
allow enroll-namespace for waypoint generate

### ISSUE THREAD

**Issue by linsun** [istio/istio#50567]
Would be useful to have this in the generate cmd as well so that users can preview/capture what the cmd does before running the apply cmd.  @MorrisLaw - Thoughts? Love the `enroll-namespace` you added for apply!

```
./istioctl x waypoint generate --enroll-namespace                           
Error: unknown flag: --enroll-namespace
```

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
This seems like a reasonable thing to add. 👍🏽

**Comment by howardjohn** [comment]
IMO `generate` is for doing things that don't touch the cluster. This pattern persists across `helm template`, `istioctl manifest generate`, etc.

**Comment by MorrisLaw** [comment]
@howardjohn being able to preview what the command does, does seem generally useful. Do you think it makes sense to add something to support this even if ends up being something different than the generate command? I imagine there may be more desire to preview commands as we continue to update istioctl wrt Waypoint related commands. Wdyt?

**Comment by linsun** [comment]
+1 on preview the commands, also user wants to know exactly what we applied via waypoint apply if they choose to automate via gitops.

**Comment by howardjohn** [comment]
> +1 on preview the commands, also user wants to know exactly what we applied via waypoint apply if they choose to automate via gitops.

Problem is there isn't a way to give a yaml they can apply since we want to just patch it. We can give instructions on how to do it I guess. 

But tbh probably best to have a docs page on istio.io for ambient w/ gitops (maybe in addition to some of this stuff)

**Comment by MorrisLaw** [comment]
> But tbh probably best to have a docs page on istio.io for ambient w/ gitops (maybe in addition to some of this stuff)

@linsun @craigbox did we end up adding this or did we already create an issue to track that work?

**Comment by craigbox** [comment]
I don't think we have an issue, so please do create one, and let's CC @ably77 in case he wants to help with it!

**Comment by howardjohn** [comment]
As per above I don't think this is feasible, but https://github.com/istio/istio.io/issues/15079 tracks docs improvements
