### ISSUE TITLE
waypoint delete all should clean up the use-waypoint annotation?

### ISSUE THREAD

**Issue by linsun** [istio/istio#50570]
**Describe the feature request**

While enroll-namespace adds the use-waypoint annotation, delete all waypoint in the namespace doesn't clean the annotation up. Should we clean the annotation for user?

```
./istioctl x waypoint delete --all
waypoint default/waypoint deleted
 ~/Downloads/istio-dev/ k get ns default -o yaml          
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    istio.io/use-waypoint: waypoint
  creationTimestamp: "2024-04-04T18:13:55Z"
  labels:
    istio.io/dataplane-mode: ambient
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "377263"
  uid: 5d6f54ab-bf56-41d1-81bc-83a349357450
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

Alternative is to ask users to run `$ kubectl annotate namespace default istio.io/use-waypoint-`
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
cc @MorrisLaw

**Comment by howardjohn** [comment]
For consistency with enrolling maybe error if they have it (or warn, but error might be safer) and have a flag to do it automatically?

**Comment by MorrisLaw** [comment]
> For consistency with enrolling maybe error if they have it (or warn, but error might be safer) and have a flag to do it automatically?

@howardjohn, tbc... is your suggestion to error on the `delete --all` command and in addition provide some flag to delete waypoint? Or is your suggestion in the context of the `--enroll-namespace` command?

**Comment by howardjohn** [comment]
I think we should:
* Warn or error if they have references to it
* Maybe allow a flag to `--unenroll`

FWIW I think automating it is Hard to do for all cases. It can be labelled on a pod, and that is almost always controlled by a higher level object.
