### ISSUE TITLE
Source IP to upstream Requests changed from 127.0.0.1 to POD_IP

### ISSUE THREAD

**Issue by timo-42** [istio/istio#50611]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,

I'm not sure if this is a Bug in Istio, a Bug in Envoy or just new undocumented behavior.

After updating from 1.20.5 to 1.21.0 we observed different behavior of the istio sidecar, the source IP of  the connection to the sidecar/upstream service changed:
<img width="1538" alt="Screenshot 2024-04-22 at 17 46 17" src="https://github.com/istio/istio/assets/10377071/05a7d331-860e-4ebf-83b8-852e7e664b3e">

<img width="1529" alt="Screenshot 2024-04-22 at 17 46 50" src="https://github.com/istio/istio/assets/10377071/9627d34e-6f23-4686-90c9-eca2b226d2b7">

I read the [Changelog](https://istio.io/latest/news/releases/1.20.x/announcing-1.20/change-notes/) but I did not see any changes regarding network interfaces or source IP for Sidecars.

Regards
Timo

### Version

```Text
# Many Versions since I wanted to know when the change started to occur.

istioctl version
client version: 1.21.1
istiod version: 1.19.3
istiod version: 1.19.3
istiod version: 1.19.4
istiod version: 1.19.4
istiod version: 1.19.5
istiod version: 1.19.5
istiod version: 1.19.6
istiod version: 1.19.6
istiod version: 1.19.7
istiod version: 1.19.7
istiod version: 1.19.8
istiod version: 1.19.8
istiod version: 1.19.9
istiod version: 1.19.9
istiod version: 1.20.0
istiod version: 1.20.0
istiod version: 1.20.1
istiod version: 1.20.1
istiod version: 1.20.2
istiod version: 1.20.2
istiod version: 1.20.3
istiod version: 1.20.3
istiod version: 1.20.4
istiod version: 1.20.4
istiod version: 1.20.5
istiod version: 1.20.5
istiod version: 1.21.0
istiod version: 1.21.0
istiod version: 1.21.1
istiod version: 1.21.1
data plane version: 1.19.3 (44 proxies), 1.20.5 (2 proxies), 1.21.0 (1 proxies), 1.21.1 (11 proxies)

kubectl  version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"05f2dca83369807327c976b24846de8687923cb6", GitTreeState:"clean", BuildDate:"2024-04-12T23:22:53Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by keithmattix** [comment]
Check out: https://github.com/istio/istio/commit/59f2cf1911d2d82409fea27e98eb2a8d382285be#diff-d6b1447634d5ccd60af75e578dfe03da0e2eb1e6c14d1dccabf1e6ffd84e57b9

**Comment by timo-42** [comment]
This could be it. We did not deviate from the default settings here. I will check it out tomorrow. 

Thanks!

**Comment by timo-42** [comment]
Thank you for the fast feedback. With a change in[gunicorn settings](https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips), this is not an issue anymore.
