### ISSUE TITLE
extend WasmPlugin's traffic selector to select paths

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#50638]
Currently WASMPlugin's [Traffic Selector](https://github.com/istio/api/blob/941d58de83fb9ef6ee41425549c7c58af0e1056a/extensions/v1alpha1/wasm.proto#L358) injects WASM based on port or inbound/outbound. We would like to apply WASM filter only to specific paths/ or based on some header value. 

Can we extend traffic selector to include path? This would need to enable WASM filter based on Envoy's Composite filter and select path at run time

**Comment by ramaraochavali** [comment]
@kyessenov WDYT?

**Comment by howardjohn** [comment]
There has been a general desire to allow a `targetRef=HTTPRoute` on these types of resources. So I think that would be the path we go around, not another matching mechanism?

**Comment by spacewander** [comment]
If we want to select path in the wasm plugin, do we implement it in the control plane or data plane?

If we want to implement it in the control plane, the current Wasm Filter hasn't supported RDS-level configuration yet. It seems that a per-route Wasm VM will be expensive.

 If we want to implement it in the data plane, will it be like Higress's [WasmPlugin CRD](https://github.com/alibaba/higress/blob/e68b5c86c4c9fec8fe626f5cfb0617cfe363e52d/api/extensions/v1alpha1/wasm.proto#L112), which provides a SDK to wrap the original proxy wasm SDK and do the route match?

**Comment by ramaraochavali** [comment]
> There has been a general desire to allow a targetRef=HTTPRoute on these types of resources.

Does it mean it works for only Gateway API routes? We would like for paths using simple composite filter action. We do not have to have a separate HTTPRoute/Virtual Service route defined for that path.

**Comment by kyessenov** [comment]
I concur that it is better to make WasmPlugin self contained for traffic selection, rather than binding to a Gateway resource in a non-standard way. For inbound especially, we need this applied for passthrough traffic.

**Comment by ramaraochavali** [comment]
@howardjohn Are you OK with adding this capability to WASM Plugin? If yes, I would like start this as we have many use cases coming up for this.

**Comment by howardjohn** [comment]
I'm very concerned about us adding different matching mechanisms into each API. 

Can you help explain your use case more around why you want to match path but cannot have a VS for that path?

**Comment by ramaraochavali** [comment]
One example use case is path based Authz on the inbound path .The WASM filter would need to be deployed with different conditions or a different WASM filter needs to added for some paths. We do not generally define a VS for inbound paths. Without this capability the path processing logic gets in to each of the WASMs and has to skip paths that not relevant to it which is very cumbersome. 

Even if you define VS for paths, how would we refer here unless we move to Gateway API - May be I am not understanding some thing here

**Comment by howardjohn** [comment]
Ah sidecar inbound, that is is quite different ... FWIW linkerd does this by having HTTPRoutes apply to inbound (with no backendRef allowed, so its just a matcher). Just one option.

For VS vs Gateway API, I think we can make it work with both probably. But that was more for outbound

**Comment by ramaraochavali** [comment]
Are you OK with adding path matching support for Inbound?

**Comment by howardjohn** [comment]
We discussed this a bit in the WG meeting yesterday. The general consensus was we want to build out a generic matching representation for policies. For outbound, this is fairly obvious - bind to Route; inbound is slightly less clear. In the meantime this can be done via envoyfilter and/or matching in the WASM logic itself. There was some concerns about adding additional ad-hoc matching to another API.

**Comment by ramaraochavali** [comment]
>  In the meantime this can be done via envoyfilter and/or matching in the WASM logic itself. 

Adding that logic WASM filter it self not scalable - we do not know the paths upfront and every WASM filter needs to be changed to know about that path and act on it. Doing it via Envoy filter is not possible especially for WASM with image fetching involved - Istio relies on top level filter being WASM. If we change code and allow composite filter type of config also it works. IMO when we design the matching API, we should also consider inbound - without that it is not complete. In the mean time, should we change Istio to also work with ExtensionWithMatcher some thing like this https://github.com/istio/istio/pull/45889? If we generate WASM filter with extension with config - I think it would allow users to do it per path while we design the API

**Comment by kyessenov** [comment]
@ramaraochavali are you fetching the Wasm from HTTP? I think Tetrate folks wanted to fix the native fetch support for Wasm in Envoy so it would not be an issue to use EnvoyFilter directly.

**Comment by ramaraochavali** [comment]
No. We are using oci image fetch capability in Istio. Oci image fetch image
fetch is a huge problem in lot substrates because of short lives secrets
etc. We do lot of Envoy filter dance to make it work. We are stuck with
this because we do not have proper composite filter support in Istio.
Is Envoy also solving oci image fetch.

**Comment by spacewander** [comment]
Just be curious - If we use ExtensionWithMatcher to configure Wasm filter,

1. For outbound, we want to configure the plugin per Route. However, the [match API](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api.html) seems doesn't support matching via route id/name. Do we have a plan for this support?
2. The ExtensionWithMatcher seems to only configure a ruleset at a time. If we want to have N different route configurations or inbound paths, does it mean that we will have N  ECDS resources generated from one WasmPlugin?
