### ISSUE TITLE
Backporting the fix #48147 to 1.19, 1.20 Istio versions

### ISSUE THREAD

**Issue by jeswinkoshyninan** [istio/istio#50642]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It is noted that 1.19 is introduced with webhooks by default as per #43897 and the upgrades are ending up with failures  because of webhook conflict issue  as fixed here #48147. I think it is much better to backporting the fix to the version 1.19 and 1.20 to avoid creating the issue as mentioned. 

### Version

```Text
$istioctl version
client version: 1.19.9
control plane version: 1.19.9
data plane version: 1.19.9
$kubectl version
Client Version: v1.27.4
Server Version: v1.27.4
```

**Comment by kfaseela** [comment]
@hanxiaop mind taking a look?

**Comment by hanxiaop** [comment]
The first PR was trying to fix a different issue, where successfully installing the operator didn’t go with the validation webhook, and it didn’t change the confliction behavior. The fixes related to the confliction were to make the installation process smoother, but IIRC there were 2 to 3 related PRs, which involves both webhook and the webhook analyzer logics, and that may not be done easily.

I think If we want to backport PRs, we can do for 1.20 maybe, in case if there are any regressions from the backport and 1.19 is EOL and doesn't accept PRs anymore.

**Comment by jeswinkoshyninan** [comment]
@hanxiaop thank you for comments, sounds good. I hope this will backport in 1.20?

**Comment by jeswinkoshyninan** [comment]
@hanxiaop once you confirm, please let us know the date at which the backporting can be done. Also confirm if upgrading from 1.18 to 1.20 is possible. I knew that this is not recommended but still checking for options.
