### ISSUE TITLE
Optimization of the Kubernetes client cache

### ISSUE THREAD

**Issue by Zagitori** [istio/istio#50647]
Hi!

I have several control planes in one kubernetes cluster. Some namespaces are controlled by the first control plane, others by the second control plane. 
To implement resource processing restrictions, the **ENABLE_ENHANCED_RESOURCE_SCOPING** env is set and **discoverySelectors** are set. 
When creating resources (Gateways, EnvoyFilters, Secrets and others) in a namespace controlled by the first CP, the second CP also caches these resources and consumes more memory.

**Are there plans to refine the pilot-discovery, allowing you to cache resources only from those namespaces that match the selector?**

**Comment by howardjohn** [comment]
What scale are you at in terms of resources, and the memory usage of them?
