### ISSUE TITLE
istioctl ztunnel-config improvement

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#50655]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

istioctl x ztunnel-config doesn't have much in the way of verbosity control. it would be good to be able to add this for a more refined ux

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

https://github.com/istio/istio/pull/50654#discussion_r1576848796

**Comment by MorrisLaw** [comment]
When we refer to verbosity control, what are we referring to exactly @ilrudie ?

We have log level verbosity commonly used throughout ztunnel-config (and istioctl) in general. But we don't have any examples of a `--verbosity N` command (where N is the number/level of verbosity).

**Comment by ilrudie** [comment]
take a look at the linked pr. it might help with understanding where this comes from. basically we have internal mechanisms for verbose or not verbose in terms of the command output already implemented but afaik we don't expose those to the user. It came up because I hardcoded verbose to true in one spot in the PR in order to get more useful summary information.

**Comment by MorrisLaw** [comment]
Pausing work on this for a bit until I sort out [ztunnel-config unmarshalling error](https://istio.slack.com/archives/C049TCZMPCP/p1716478632840099).

**Comment by howardjohn** [comment]
Lets close until we have a use case
