### ISSUE TITLE
Istio upgrade from 1.18.5 to 1.21.1 fails in IPv6 cluster

### ISSUE THREAD

**Issue by ajaykumarmandapati** [istio/istio#50660]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have been long waiting for an upgrade from 1.18.5 which is EOL to a version that is compatible with bottle-rocket nodes, 
However, an upgrade to 1.21.1 now fails with the below log message from the `istio-validation` container.

Note: we have to upgrade to 1.21.1 since we use bottle-rocket nodes in AWS EKS environment - https://github.com/istio/istio/issues/50198

```
2024-04-24T07:45:56.651101Z	info	Starting iptables validation. This check verifies that iptables rules are properly established for the network.
2024-04-24T07:45:56.651169Z	info	Listening on [::1]:15001
2024-04-24T07:45:56.651435Z	info	Listening on [::1]:15006
2024-04-24T07:46:01.651924Z	error iptables validation failed; workload is not ready for Istio.
When using Istio CNI, this can occur if a pod is scheduled before the node is ready.

If installed with 'cni.repair.deletePods=true', this pod should automatically be deleted and retry.
Otherwise, this pod will need to be manually removed so that it is scheduled on a node with istio-cni running, allowing iptables rules to be established.
2024-04-24T07:46:01.652186273Z
```
Below are the logs from the DS `istio-cni-node`
```
# Completed on Wed Apr 24 07:42:42 2024
2024-04-24T07:42:42.401663Z	info	cni	============= End iptables configuration for echoserver-55ff5756b8-mtzwx =============
2024-04-24T07:42:52.511775Z	info	repair	Repairing pod...	pod=default/echoserver-55ff5756b8-mtzwx
2024-04-24T07:42:52.512351Z	error	controllers	error handling default/echoserver-55ff5756b8-mtzwx, retrying (retry count: 1): get netns: in host network: network id: find link for 2a05:d014:1d16:3d05:7696::5: no routes found for 2a05:d014:1d16:3d05:7696::5	controller=repair pods
2024-04-24T07:42:52.517605Z	info	repair	Repairing pod...	pod=default/echoserver-55ff5756b8-mtzwx
2024-04-24T07:42:52.517993Z	error	controllers	error handling default/echoserver-55ff5756b8-mtzwx, retrying (retry count: 2): get netns: in host network: network id: find link for 2a05:d014:1d16:3d05:7696::5: no routes found for 2a05:d014:1d16:3d05:7696::5	controller=repair pods
2024-04-24T07:42:52.528325Z	info	repair	Repairing pod...	pod=default/echoserver-55ff5756b8-mtzwx
2024-04-24T07:42:52.528826Z	error	controllers	error handling default/echoserver-55ff5756b8-mtzwx, retrying (retry count: 3): get netns: in host network: network id: find link for 2a05:d014:1d16:3d05:7696::5: no routes found for 2a05:d014:1d16:3d05:7696::5	controller=repair pods
2024-04-24T07:42:52.549094Z	info	repair	Repairing pod...	pod=default/echoserver-55ff5756b8-mtzwx
2024-04-24T07:42:52.549508Z	error	controllers	error handling default/echoserver-55ff5756b8-mtzwx, retrying (retry count: 4): get netns: in host network: network id: find link for 2a05:d014:1d16:3d05:7696::5: no routes found for 2a05:d014:1d16:3d05:7696::5	controller=repair pods
2024-04-24T07:42:52.589751Z	info	repair	Repairing pod...	pod=default/echoserver-55ff5756b8-mtzwx
2024-04-24T07:42:52.590244Z	error	controllers	error handling default/echoserver-55ff5756b8-mtzwx, and retry budget exceeded: get netns: in host network: network id: find link for 2a05:d014:1d16:3d05:7696::5: no routes found for 2a05:d014:1d16:3d05:7696::5	controller=repair pods
```

### Version

```Text
istioctl version                                                                                                                                       
client version: 1.21.1
control plane version: 1.21.1
data plane version: 1.18.5 (3 proxies), 1.21.1 (1 proxies)

kubectl version                                                                                                                                        
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-eks-adc7111

helm version --short                                                                                                                                   
v3.11.1+g293b50c
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/15090659/bug-report.tar.gz)

**Comment by subpathdev** [comment]
We run into the same issue too. Also running eks with bottlerocket as ami-type.
Our upgrade path was a little bit different as we have upgraded from 1.20.5 (no issues) to 1.21.1 with this issue.

One additional information is: 
* by deleting the pods manually via `kubectl delete` we are able to start the failing pod successfully. 
* the issue occurs only on new nodes and when the pod is scheduled shortly after the node creation. (In our example the time period is 29s).

**Comment by ajaykumarmandapati** [comment]
> We run into the same issue too. Also running eks with bottlerocket as ami-type. Our upgrade path was a little bit different as we have upgraded from 1.20.5 (no issues) to 1.21.1 with this issue.
> 
> One additional information is:
> 
> * by deleting the pods manually via `kubectl delete` we are able to start the failing pod successfully.
> * the issue occurs only on new nodes and when the pod is scheduled shortly after the node creation. (In our example the time period is 29s).

I am unable to run `1.20.5` , I do get the same error `error iptables validation failed; workload is not ready for Istio.
When using Istio CNI, this can occur if a pod is scheduled before the node is ready.` Did you'l have to change any helm values to run `1.20.5` ?

**Comment by bleggett** [comment]
>     * the issue occurs only on new nodes and when the pod is scheduled shortly after the node creation. (In our example the time period is 29s).

This specifically is likely a problem with the CNI not actually being installed + reaching ready state on the node before pods are scheduled on the node.

https://github.com/istio/istio/issues/40303

The way to manage this sort of things in K8S is with node taints, to prevent the runtime from starting pods before the node is ready.

https://github.com/istio/istio/pull/48818 should help with this.

**Comment by subpathdev** [comment]
> > We run into the same issue too. Also running eks with bottlerocket as ami-type. Our upgrade path was a little bit different as we have upgraded from 1.20.5 (no issues) to 1.21.1 with this issue.
> > One additional information is:
> > 
> > * by deleting the pods manually via `kubectl delete` we are able to start the failing pod successfully.
> > * the issue occurs only on new nodes and when the pod is scheduled shortly after the node creation. (In our example the time period is 29s).
> 
> I am unable to run `1.20.5` , I do get the same error `error iptables validation failed; workload is not ready for Istio. When using Istio CNI, this can occur if a pod is scheduled before the node is ready.` Did you'l have to change any helm values to run `1.20.5` ?


We do not have modified our settings by moving from 1.19.5 to 1.20.5. But pods in error state will be removed by us in previously to 1.21.1 with the configuration flag `values.cni.repair. deletePods` perhaps you have disabled this?

**Comment by subpathdev** [comment]
> > ```
> > * the issue occurs only on new nodes and when the pod is scheduled shortly after the node creation. (In our example the time period is 29s).
> > ```
> 
> This specifically is likely a problem with the CNI not actually being installed + reaching ready state on the node before pods are scheduled on the node.
> 
> #40303
> 
> The way to manage this sort of thing in K8S is with node taints, to prevent the runtime from starting pods before the node is ready.
> 
> #48818 should help with this.

As far as I understand the modification in MR #48818  it could resolve our issue. It would be nice to have some documentation anywhere about this feature / setting as well.

**Comment by sdomme** [comment]
Hi People, unfortunately we still have the issue stated in the bug description. Even with the 1.22
istio-validation fails in every circumstances. New node, old node, restarting the app POD, restarting istio-cni-node POD.

Anything we can do to dig deeper? Maybe to clarify it a bit. It is not like the upgrade is not working. That is fine. We are not able to run apps with istio per sidecar injection after the upgrade. We do CNI chain with cilium.

**Comment by sdomme** [comment]
Another deep dive brought some new findings:

It stopped working between 1.19.4 and 1.19.5 https://github.com/istio/istio/compare/1.19.4...1.19.5

Comparing the logs of istio-cni-node of both versions, testing the same workload shows a difference in the 
`cni Istio iptables environment`

The `ENABLE_INBOUND_IPV6` is set to `false` in >=1.19.5 and therefore `ip6tables-restore` and `ip6tables-save` are not executed at all to configure rules for the workload. 
On a IPv6-only EKS cluster...

I suspect that something is not working [here](https://github.com/istio/istio/blob/6a089c8e9eaff7aa7e5bf8e1090a78fded2f7907/tools/istio-iptables/pkg/config/config.go#L199)  anymore?

**Comment by bleggett** [comment]
> I suspect that something is not working [here](https://github.com/istio/istio/blob/6a089c8e9eaff7aa7e5bf8e1090a78fded2f7907/tools/istio-iptables/pkg/config/config.go#L199) anymore?

It looks like between 1.18 and 1.19 env vars changed.

`1.18` -> `ISTIO_AGENT_DUAL_STACK`
1.19` -> `ISTIO_DUAL_STACK`

If you previously used `ISTIO_AGENT_DUAL_STACK` consider changing to the new env, and see if that helps.

Note that IPv6 clusters have always and remain entirely unsupported and are currently experimental.

**Comment by sdomme** [comment]
I can imagine it started with https://github.com/istio/istio/pull/48159/files somewhere here https://github.com/howardjohn/istio/blob/d60d686a7d86836d313dc9c1fb87f162485cad4e/tools/istio-iptables/pkg/config/config.go

**Comment by bleggett** [comment]
As per slack discuss, `ISTIO_DUAL_STACK` as mentioned above should be working for you - if you find other issues, raise them.

We make no stability guarantees around IPv6 support, as it is currently `experimental`.

**Comment by sdomme** [comment]
Yes. I checked our setup. With this parameter set to true it is working now on 1.22. Thanks again for the support. I think this one can be closed now.

**Comment by bleggett** [comment]
@sdomme if you hit more dualstack issues, let us know! TY.
