### ISSUE TITLE
Errors discovered while attempting to use Istio's automatic injection feature

### ISSUE THREAD

**Issue by CCTV-six** [istio/istio#50674]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Error from server (InternalServerError): error when creating "my-service.yaml": Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: service "istio-sidecar-injector" not found

### Version

```Text
1.15.7
```

**Comment by zirain** [comment]
1. 1.15 is EOL, please use latest version
2. please check the network between kube-apiserver(master node) and istiod(worker node).

**Comment by leosarra** [comment]
Yes, as @zirain suggested 1.15.x is EOL and you should try with a new version.

Moreover, the request made toward istio-sidecar-injector.istio-system.etc/443 looks strange, it should have been istiod.istio-system.etc.
If the problem persist please provide also the steps you are using to deploy Istio.
