### ISSUE TITLE
considering istioctl status

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#50735]
Add a status feature to istioctl. This issue is really not immediately implementable, short term it is simple meant to act as a place to discuss ideas.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by ilrudie** [comment]
- report status of istio workloads
- report xds connection status for data plane
- report whether or not ambient controllers are running
- report GTWAPI installation 👍/👎
- https://github.com/istio/istio/issues/50249 show deployed but unused waypoints

**Comment by linsun** [comment]
+1, would be good to report istio component status too:  gw, istiod, istio-cni, ztunnel etc
