### ISSUE TITLE
HTTP/L7 metrics for TLS-terminated downstream requests in a Gateway

### ISSUE THREAD

**Issue by kaiburjack** [istio/istio#50758]
**Describe the feature request**

We are currently using the Egress Gateway to terminate HTTPS/TLS requests originating from our workloads to external domains that we control as well and whose traffic we want to observe on L7. We do have an own self-signed CA and a server certificate with a PKI that we distribute securely to the Istio Egress Gateway. The role of that Egress Gateway should then be to terminate the HTTPS/TLS connections, make the HTTP requests visible for L7 metrics gathering, and then optionally send these HTTP requests further to an egress *cache* (Varnish) which is used to cache egress requests and whose Istio sidecar will then do TLS origination to the actual external domains; or the Egress Gateway will TLS-originate those requests again and send them off to the actual destination domain.

That all works splendidly, *however* no HTTP/L7 metrics are gathered by Istio/Envoy for downstream HTTPS/TLS requests to the Egress Gateway that are ultimately TLS-terminated by the Egress Gateway, so _should_ be available to Istio/Envoy there.

I am assuming that, when you have a HTTPS/443 listener on a `Gateway` CRD with downstream tls configured, then the Envoy listener this is configured for, is still a HTTPS/TLS listener which "thinks" that it cannot inspect HTTP/L7 metrics, even though we are doing TLS-termination here.

**Describe alternatives you've considered**

Observing HTTP/L7 metrics for *outbound*/upstream requests in the Egress Gateway works, though. So, we currently do not have L7 metrics for downstream requests *to* the Egress Gateway (which are originally HTTPS/TLS requests, but TLS-terminate by the Egress Gateway), but we have HTTP/L7 metrics for *upstream* requests done by the Egress Gateway.

However, that means, we lose the correlation between the source service where the HTTPS/TLS connections/requests originate from and the Egress Gateway where those requests are received (and TLS-terminated) and then sent further upstream.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Can you share a config dump (`istioctl pc all PODNAME`)? Istio knows when its HTTPS and does HTTP metrics, so this means either:
* Its not actually doing what you think (terminating HTTPS)
* Stats are not configured correctly
* A new bug

**Comment by kaiburjack** [comment]
The Egress Gateway is _definitely_ terminating the TLS connection. I see the Common Name of the certificate when I do e.g. `curl https://httpbin.org/status/200` in a source workload/pod. And the certificate is only ever mounted to the Egress Gateway's `Gateway` CRD, which looks like this:
```yaml
spec:
  selector:
    app: istio-egressgateway
    istio: egressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https-port
      number: 443
      protocol: HTTPS
    tls:
      credentialName: egress-server-cert-secret
      mode: SIMPLE
```

I think, it is much like with an Ingress Gateway which terminates HTTPS/TLS connections for our own server domain (with a public Let's Encrypt certificate). There, I also do not see (via Prometheus stats endpoint) the *incoming*/downstream requests from clients towards the Ingress Gateway. So, no `istio_requests_total` metrics here when the `reporter="destination"` on that Ingress Gateway pod. However, upstream requests are visible as Prometheus metrics when the HTTPS/TLS-terminated requests go upstream from the Ingress Gateway to the upstream services/backends. There, I do see the HTTP requests e.g. via `istio_requests_total{reporter="source", source_app="istio-ingressgateway"}`.

But no downstream HTTP metrics with `istio_requests_total{reporter="destination", destination_app="istio-ingressgateway"}`.

The exact same scenario is with the *Egress* Gateway: Terminating the downstream HTTPS/TLS connections, but no HTTP/L7 metrics over the Prometheus stats endpoint for incoming/downstream requests. Though, _outgoing_/upstream requests, the metrics are fine.

I am going to assemble a sensible `istioctl pc all egress-gateway-...` output, because it contains many sensitive information at many places and is many tens of thousands of lines long.

**Comment by howardjohn** [comment]
1 request to a gateway generates 1 single metric, not a distinct one for upstream and downstream.

Sidecars generate 2 because there are two distinct sidecars (each generates 1)

**Comment by kaiburjack** [comment]
> 1 request to a gateway generates 1 single metric, not a distinct one for upstream and downstream.
Oh, that makes _total_ sense, since there is only one listener filter chain and single http connection manager processed.
So, is there no way to correlate requests through a gateway between the downstream and upstream?
What I really am after is to know in the metrics which downstream service was sending a request through a gateway, which ultimately sent this very request upstream to another service.
I cannot track the HTTPS request in the originating workload's outgoing sidecar, because it cannot inspect the HTTPS/TLS traffic. Only the gateway could do that, but since, as you said, there is only a single metric generated, and that metrics seems to look like "outgoing/upstream" metrics (so the source_app is the gateway and the destination_app is the service this request is destined for).
What I would like to have is a single metric point with the originating service being the source_app and the eventual destination upstream being the destination_app.

**Comment by howardjohn** [comment]
Basically no. You can use tracing to do this, but its of course not quite the same as metrics.

Interestingly, part of ambient mesh we decided to make the waypoint component work exactly how you want it to work: https://github.com/istio/istio/issues/42320#issuecomment-1977262417. While we haven't talked about it much yet, there are plans to be able to use waypoints like egress gateways, which would ultimately fulfill that use case. Its a ways off to get the egress part though.

**Comment by kaiburjack** [comment]
Thank you for your answers and insights. Much appreciated!
Actually, the reason why we opted for an egress _gateway_ was that there does not seem to be an easy way for the outbound listener of a workload's sidecar to do the TLS-termination, because whenever a ServiceEntry was configured with a HTTPS port, it would not configure a Http connection manager on it, but only make TLS metrics visible. Terminating the application-side HTTPS/TLS connection on the outbound listener would also suit us here.
Using the downstream tls config on a gateway was just the next best thing, since there currently is no such thing as a tls config on a sidecar's _outbound_/upstream listener.
While researching this topic I came across at least these following Istio GitHub issues tackling the same problem, I think:
- https://github.com/istio/istio/issues/21368
- https://github.com/istio/istio/issues/37160
- https://github.com/istio/istio/issues/39490

**Comment by howardjohn** [comment]
I think the current state is:
* This can work with a waypoint instead. Not well documented, but I plan to in a couple weeks hopefully
* Could be done with sidecar termination, but its not implemented. See above for reference issues
* Could be done with traces, but not quite the same

Overall I think this is the expected state, and while there isn't a great solution to this right now there isn't anything directly to do on this issue

**Comment by s7an-it** [comment]
hi @kaiburjack, I am trying to achive the same setup app originates tls nad to terminates on egress so I can modify traffic and send to teh destination and I have some issues when I am not using PASSTHROUGH so I was wondering how did you achive it, especially the terminating TLS part?
