### ISSUE TITLE
Incompletely support of traffic.sidecar.istio.io/excludeOutboundIPRanges while upgrading istio from version 1.15.2 to 1.20

### ISSUE THREAD

**Issue by navneet-we** [istio/istio#50786]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istioctl x precheck --from-version=1.20
Info [IST0136] (Pod staging/demo-858bd586b-6kj77) Annotation "traffic.sidecar.istio.io/excludeOutboundIPRanges" is part of an alpha-phase feature and may be incompletely supported.

### Version

```Text
istioctl version  
client version: 1.15.2
istiod version: 1.15.2
data plane version: 1.15.2 (204 proxies)
```

### Additional Information

I am upgrading the istio version from 1.15.2 to 1.20.6 before that i running the command istioctl x precheck --from-version=1.20 and i am getting this 
Info [IST0136] (Pod staging/buggy-app-858bd586b-6kj77) Annotation "traffic.sidecar.istio.io/excludeOutboundIPRanges" is part of an alpha-phase feature and may be incompletely supported.
i am not getting the alternate for "traffic.sidecar.istio.io/excludeOutboundIPRanges" or please let me know when traffic.sidecar.istio.io/excludeOutboundIPRanges got deprecated upto which version of istio we can use this "traffic.sidecar.istio.io/excludeOutboundIPRanges"

and the deployment file is below 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app
spec:
  selector:
    matchLabels:
      app: buggy-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 40%
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: buggy-app
    spec:
      affinity:

**Comment by navneet-we** [comment]
can you please explain "part of an alpha-phase feature and may be incompletely supported."

**Comment by howardjohn** [comment]
It is an alpha feature: https://istio.io/latest/docs/releases/feature-stages/

**Comment by navneet-we** [comment]
i want to know what is incompletely supported in this traffic.sidecar.istio.io/excludeOutboundIPRanges

**Comment by howardjohn** [comment]
Nothing, the message is logged for any alpha features.

**Comment by navneet-we** [comment]
thanks for the support

**Comment by navneet-we** [comment]
thanks for the support

**Comment by navneet-we** [comment]
how can i achieve sidecar version rollout for particular workload (deployment), i have 2 version 1.15.2 and 1.20.6.
i want to run only one deployment out of 10 of dev namespace, i had provide the annotation in deployment.yaml
annotations:
        istio.io/rev: 1-20-6 but still it is using istio version 1.15.2 version
        
       
<img width="577" alt="Screenshot 2024-05-02 at 8 07 15 PM" src="https://github.com/istio/istio/assets/161301101/deeba4ac-7bf9-4c02-894b-9d8f1f33e8a2">

**Comment by howardjohn** [comment]
istio.io/rev is a label, not an annotation. I recommend opening a discussion (https://github.com/istio/istio/discussions) or slack thread for questions, re-opening closed issues will not likely get noticed quickly  (as you may have noticed unfortunately)
