### ISSUE TITLE
istioctl x waypoint generate is missing the `--for` config

### ISSUE THREAD

**Issue by linsun** [istio/istio#50790]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Seems only avail for the apply cmd:

      --for string         Specify the traffic type [all none service workload] for the waypoint (default "service")

Could we add this for the generate cmd as well?

### Version

```Text
1.22 dev
```

**Comment by linsun** [comment]
Hi @MorrisLaw could you look into this? Thanks

**Comment by MorrisLaw** [comment]
Thanks for making the issue @linsun , I'll update this.
