### ISSUE TITLE
ztunnel-config might not be printing out ztunnel data correctly

### ISSUE THREAD

**Issue by MorrisLaw** [istio/istio#50807]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

draft PR https://github.com/istio/istio/pull/50806 describes this in detail with examples.

The ztunnel config dump writer does not appear to be getting the ztunnel config dump and unmarshalling that into the ztunnelDump struct correctly within the istioctl code. I think it's causing issues with how this data gets printed for commands like `istioctl x ztunnel-config workload`

### Version

```Text
$ istioctl version
client version: 1.23-dev                                                                                                                                                               control plane version: 1.21.1                                                                                                                                                          data plane version: 1.21.1 (3 proxies)
```

### Additional Information

https://github.com/istio/istio/pull/50806

**Comment by MorrisLaw** [comment]
The unit test shows the logic is fine assuming that the bytes to be unmarshalled contain the right fields. It seems my local environment does not produce the right data (confirmed by curling localhost:15000/config_dump and also by printing it out as shown in the draft PR linked above). Does not match the example of expected data in testdata/dump.json.

**Comment by bleggett** [comment]
> Does not match the example of expected data structure in testdata/dump.json.

We should probably have a schema or proto in both spots for this, or at least an istio-side integ test.

**Comment by howardjohn** [comment]
are you on latest version of both? it works for me. We changed the keys a while back

**Comment by MorrisLaw** [comment]
> are you on latest version of both? it works for me. We changed the keys a while back

Ok, good! Wdym, when you say latest version of both @howardjohn ? The istio repo and ztunnel repo I have locally is as up to date as today, but maybe you're referring to something else?

**Comment by MorrisLaw** [comment]
I think my ztunnel binary was out of date, this is a non-issue
