### ISSUE TITLE
disable opencensus

### ISSUE THREAD

**Issue by zirain** [istio/istio#50808]
follow https://github.com/envoyproxy/envoy/pull/33912, need remove all related things from istio?

cc @kyessenov @lei-tang

**Comment by kyessenov** [comment]
I'd prefer if we just kept it in Google builds. We don't expect much help from OSS Istio here, and it's not worth exposing the entire project to the mess of opencensus deprecation.

**Comment by zirain** [comment]
is it fine to remove directly? better to deprecated in 1.23 and removed in 1.24?

**Comment by kyessenov** [comment]
@lei-tang @zirain There are several usages of opencensus that need different solutions:

1. The test that @zirain disabled is for zipkin. We need to stop using opencensus for zipkin tracing.
2. OpenCensus tracing driver needs to be removed from OSS Istio. It's only used for Google tracing integration.
3. OpenCensus metrics driver needs to be removed from OSS Istio Proxy. It's only used for Google monitoring integration and resides in Istio/proxy.

**Comment by lei-tang** [comment]
With regard to OpenCensus removal from OSS Istio, the following items need to be done.

In the OSS istio proxy repository, the usage of following items need to be removed:
- OpenCensus tracer
- Metrics implemented through the OpenCensus SDK.

In the OSS istio repository, the code programming the OpenCensus tracer into xDS should be removed.

The user guides referring to the items above should be updated.

**Comment by howardjohn** [comment]
@lei-tang @kyessenov which of these (if any) will we be doing as well?
1. Removing Istiod OC XDS generation
2. Removing Istiod SD XDS generation
3. Removing istio/proxy SD filter

**Comment by kyessenov** [comment]
@howardjohn I'm doing (3).

**Comment by howardjohn** [comment]
Does that mean we should do 1+2 as well? Doesn't have to be you specifically. I would assume (2) at least

**Comment by kyessenov** [comment]
@howardjohn I don't think we strictly have to remove protobuf generation. Envoy policy, for example, is to keep protobufs from deleted filters because it's disruptive to delete Protos.

**Comment by howardjohn** [comment]
I suppose we want to do it for 1 release so we have N-1 support, why do we need it longer though?

**Comment by lei-tang** [comment]
Istio Stackdriver metrics implemented through the istio.stackdriver filter uses OpenCensus. I will create a PR to remove the XDS programming of the istio.stackdriver filter for metrics from Istio.

**Comment by lei-tang** [comment]
I am working on a PR https://github.com/istio/istio/pull/51070 to remove the XDS programming of the Istio Stackdriver logs from Istio.

**Comment by craigbox** [comment]
(/cc self to make sure documentation is updated to remove mention of OpenCensus and Stackdriver.)

**Comment by zirain** [comment]
this seems done, feel free to reopen.

**Comment by sword-jin** [comment]
@zirain 
I have a doubt after removing opencensus, for these use cases(opencensus with CLOUD_TRACE_CONTEXT), the envoy doesn't support GCP trace natively, do we have other recommend operations for the migration from opencensus to opentelemetry

**Comment by sword-jin** [comment]
@howardjohn 
Thank you, but I am using otel-collector already, the problem is we have enabled a `envoyExtAuthzGrpc extension provider` which the address is `auth.default.svc`(for example), then a request goes to a real backend service like `shop.default.svc`, the trace generated by `envoy` is not the one which is created by goole LB(`x-cloud-trace-context`).

With the old opencensus, it support `CLOUD_TRACE_CONTEXT` context.

After we removed opencensus, I think the alternative approach is using a custom `EnvoyFilter`
