### ISSUE TITLE
Support for connection via UNIX Domain Socket(UDS) when sending trace spans from istio-proxy to Datadog Agent.

### ISSUE THREAD

**Issue by mugioka** [istio/istio#50816]
**Describe the feature request**

Currently, we are unable to configure the Unix Domain Socket (UDS) to send tracing spans to Datadog. This limitation arises from the [DataDogAddress function](https://github.com/istio/istio/blob/75c6eafc5bc8d160b5643c3ea18acb9785855564/pkg/bootstrap/option/instances.go#L181-L183) which only accepts values in the `host:port` format. Moreover, the Istiod-generated configuration below does not support UDS:

```
{
    “name”: “datadog_agent”,
    “type”: “STRICT_DNS”,
    “connectTimeout”: “1s”,
    “loadAssignment”: {
        “clusterName”: “datadog_agent”,
        “endpoints”: [
            {
                “lbEndpoints”: [
                    {
                        “endpoint”: {
                            “address”: {
                                “socketAddress”: {
                                    “address”: “datadog.example.svc.cluster.local”,
                                    “portValue”: 8126
                                }
                            }
                        }
                    }
                ]
            }
        ]
    },
    “respectDnsTtl”: true,
    “dnsLookupFamily”: “V4_ONLY”
}
```
From my understanding of the Envoy configuration, [config.core.v3.SocketAddress](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-socketaddress) does not support UDS. Therefore, we need to use [config.core.v3.Pipe](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-pipe) to send the tracing span via UDS.

Datadog supports UDS for receiving trace spans. Therefore, we would like to support that send trace spans via UDS to optimize the performance of traceable Istio-proxy.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ x ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by mugioka** [comment]
Envoy is internally used Datadog integration for cpp.
So to send tracing spans to Datadog agent via UDS, we need to change Envoy and datadog cpp tracing lib.

https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/datadog/README.md

**Comment by mugioka** [comment]
https://github.com/DataDog/dd-trace-cpp/blob/main/src/datadog/http_client.cpp

Datadog cpp lib supports unix domain sockets.

**Comment by zirain** [comment]
need envoy support this first.

**Comment by dmehala** [comment]
Hey @mugioka 

This issue was brought to my attention today. I'll investigate its feasibility.

**Comment by happyyi008** [comment]
can we reopen this issue?

**Comment by happyyi008** [comment]
Can this issue be reopened?
