### ISSUE TITLE
Improve UX for workload captured waypoint

### ISSUE THREAD

**Issue by linsun** [istio/istio#50849]
**Describe the feature request**

Workload captured waypoint requires some brain power atm to ensure the use-waypoint label on the pod is pointing to a waypoint that can capture workload, which isn't default and requires specific configuration when deploying a waypoint.

Would be nice to improve this - by giving some warnings when inconsistency detected via analyzer?  Or use a different gatewayclass for workload waypoint?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
> Would be nice to improve this - by giving some warnings when inconsistency detected via analyzer?

Yeah I agree. It may not be trivial though. Here is a related issue where this was discussed in more detail: https://github.com/istio/istio/issues/50249
