### ISSUE TITLE
Noisy attempts to use extended fields when on standard Gateway API CRDs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#50851]
If you use standard gateway CRDs, istiod logs `unknown field "status.supportedFeatures"`.

This is because we write this in status (on GC) but its not in standard. 

We don't actually know if they are on standard or not. but we could -- if we read `gateway.networking.k8s.io/channel`?

cc @keithmattix

**Comment by keithmattix** [comment]
Hmm yeah this seems like a reasonable use case but I worry it could be abused in the future and create a split horizon control plane

**Comment by pderrierw** [comment]
I confirm this happens with Gateway CRDs, is there any side effect of this info log ?
