### ISSUE TITLE
High CPU on istiod control plane 1.19.8

### ISSUE THREAD

**Issue by seifrajhi** [istio/istio#50867]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone,
We have upgraded our Istio pilot/control plane from version `1.17` to `1.19.8` in our AWS EKS clusters. 
While all other Istio components appear to be functioning correctly, We have noticed unusually high CPU usage within the istiod pod, and CPU looks like it flapping for some reason.

<img width="1209" alt="Screenshot 2024-05-05 at 19 23 54" src="https://github.com/istio/istio/assets/130180976/1cbdf01b-aa20-42e4-823d-99a83bcc3989">

As you may see in above screenshot few minutes, after upgrade CPU started to get higher and higher and flapping.

We have carefully reviewed the istiod pod logs and we haven't found any apparent errors or anomalies. 
The logs seem to indicate normal operation.

I am trying to collect [CPU profile](https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#cpu) from one of the istiod pods, but I can't manage to do so, because the peak goes very quickly. 

### Version

```Text
$ istioctl version
client version: 1.19.8
istiod version: 1.19.8
data plane version: 1.19.8 (717 proxies)

$ kubectl version
Client Version: v1.29.3
Server Version: v1.25.16-eks
```

**Comment by wulianglongrd** [comment]
I often use crontab to regularly check the CPU usage and automatically collect it. For your reference, please note to modify it as needed.

script `/path/to/istio/tools/profiling.sh`
```shell
#!/bin/bash

sec=$1
if [[ $sec == "" ]]; then
  sec=0
fi

if [[ $(echo "$sec > 0" | bc) -eq 1 ]]; then
  echo "sleep $sec seconds"
  sleep $sec
fi

cnt=$(ps -ef | grep /debug/pprof/ | grep -v grep | wc -l)
if [[ $cnt -ne 0 ]]; then
  echo "pprof is running, aborting"
  exit
fi

pid=$(ps -ef | grep pilot-discovery | grep -v grep | awk '{print $2}' | xargs)
echo "pid:${pid}"
if [[ $pid == "" ]]; then
  echo "pilot is not running, aborting"
  exit
fi

cpuRate=$(top -b -n 2 -d 0.2 -p "$pid" | tail -1 | awk '{print $9}')
echo "$(date "+%Y-%m-%d %H:%M:%S") cpuRate:${cpuRate}"

threshold=1000 # please update it
if [[ $(echo "$cpuRate > $threshold" | bc) -eq 1 ]]; then
  echo "$(date "+%Y-%m-%d %H:%M:%S") start pprof"
  /path/to/istio/tools/go/bin/go tool pprof localhost:8080/debug/pprof/profile?seconds=60
fi
```

crontab config
```
# check every 10 seconds
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 0 >> /path/to/istio/log/profiling.log 2>&1 &
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 10 >> /path/to/istio/log/profiling.log 2>&1 &
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 20 >> /path/to/istio/log/profiling.log 2>&1 &
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 30 >> /path/to/istio/log/profiling.log 2>&1 &
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 40 >> /path/to/istio/log/profiling.log 2>&1 &
* * * * * /bin/sh /path/to/istio/tools/profiling.sh 50 >> /path/to/istio/log/profiling.log 2>&1 &
```

**Comment by seifrajhi** [comment]
Thank you @wulianglongrd for your detailed answer.
I can do that but I am afraid the `HPA` will keep killing and recreating pods each around 1 hour or so,
therefore it is hard to get this script working

**Comment by wulianglongrd** [comment]
Sorry I'm not familiar with how `HPA` works, but does it actually happen? Is there a way to temporarily close it?

**Comment by seifrajhi** [comment]
Yes I can disable it 👍 
I will test this script and get back with result.

**Comment by howardjohn** [comment]
Also I would upgrade. Istio 1.19 is EOL and we have performance improvements in every release, including major ones in 1.21.
