### ISSUE TITLE
Can we merge bookinfo-versions info bookinfo?

### ISSUE THREAD

**Issue by linsun** [istio/istio#50871]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It is a little cumbersome to have 2 yamls for 1 bookinfo app.   Seems no harm to merge even for classic Istio resources or Gateway API?

@frankbu any objection?

Examples where this would be useful:

https://preliminary.istio.io/latest/docs/ambient/getting-started/
and https://deploy-preview-15007--preliminary-istio.netlify.app/latest/docs/ambient/usage/waypoint/#attach-a-l7-policy-to-a-specific-service

### Version

```Text
istio 1.22 dev
```

**Comment by frankbu** [comment]
Although nothing will break, it might make things confusing for users of the Istio classic API since they are not used. The version Services are only used with Gateway API, classic API uses DestinationRule subsets to define the versions.

**Comment by linsun** [comment]
Understood @frankbu, can we create a v2 of bookinfo in samples/bookinfo/platform/kube/bookinfo-v2.yaml for ambient?

**Comment by linsun** [comment]
Ah :) didn't realize v2 could be confusing too!  bookinfo-all.yaml SGTM
