### ISSUE TITLE
External Authorization not work,always return 403(envoyExtAuthzGrpc)

### ISSUE THREAD

**Issue by matchseller** [istio/istio#50881]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

This is the package I captured using tcpdump. I found that the grpc request sent by ingress-gateway to ext-authz uses http1.1 instead of http2, which may be the cause of the problem.So I want to know how to configure ingress-gateway to use http2 to send grpc requests. I looked through the mesh config of istio and found no available information.
![image](https://github.com/istio/istio/assets/30618552/2b94f3b1-7279-4278-94ee-a08100bd51a9)

### Version

```Text
$istioctl version
client version: 1.20.5
control plane version: 1.20.5
data plane version: 1.20.5
$kubectl version
Client Version: v1.28.8
Server Version: v1.28.8
```

**Comment by zirain** [comment]
can you sahre the service config which is used by ext-authz

**Comment by matchseller** [comment]
> can you sahre the service config which is used by ext-authz

I feel it has nothing to do with the ext-authz service. What I used tcpdump to capture was the packet of the network card in the ingress-gateway container.
![image](https://github.com/istio/istio/assets/30618552/0768473f-078f-4552-9fd0-bc811f620e30)

**Comment by zirain** [comment]
the port name looks good, can you check the cluster configuration by running `istioctl pc c <pod_name>.<pod_namespace> --fqdn <fqdn>`

**Comment by matchseller** [comment]
> the port name looks good, can you check the cluster configuration by running `istioctl pc c <pod_name>.<pod_namespace> --fqdn <fqdn>`
istioctl pc c ext-authz-696d554b4-w8wxc.default--fqdn ext-authz.default.svc.cluster.local
![image](https://github.com/istio/istio/assets/30618552/901bfaa7-e55a-4cca-b66d-f6b92a0d2928)

**Comment by zirain** [comment]
> > the port name looks good, can you check the cluster configuration by running `istioctl pc c <pod_name>.<pod_namespace> --fqdn <fqdn>`
> > istioctl pc c ext-authz-696d554b4-w8wxc.default--fqdn ext-authz.default.svc.cluster.local
> > ![image](https://private-user-images.githubusercontent.com/30618552/328424819-901bfaa7-e55a-4cca-b66d-f6b92a0d2928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjc1NzEsIm5iZiI6MTcxNTA2NzI3MSwicGF0aCI6Ii8zMDYxODU1Mi8zMjg0MjQ4MTktOTAxYmZhYTctZTU1YS00Y2NhLWI2NmQtZjZiOTJhMGQyOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3MzQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YmMyODM3MWM0NTk3MzRmMDNiYjk2MmZlNjM2Y2QwNjY5N2U1YjQ3ZGZkYzBjOTgwZDYyNjIwNDU2Nzg5ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOSZNYB8S3AJvtP9EOgEvAVzpud0lF58i3iks-aLiK4)

sorry should add `-o yaml/json`

**Comment by matchseller** [comment]
> > > the port name looks good, can you check the cluster configuration by running `istioctl pc c <pod_name>.<pod_namespace> --fqdn <fqdn>`
> > > istioctl pc c ext-authz-696d554b4-w8wxc.default--fqdn ext-authz.default.svc.cluster.local
> > > ![image](https://private-user-images.githubusercontent.com/30618552/328424819-901bfaa7-e55a-4cca-b66d-f6b92a0d2928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjc1NzEsIm5iZiI6MTcxNTA2NzI3MSwicGF0aCI6Ii8zMDYxODU1Mi8zMjg0MjQ4MTktOTAxYmZhYTctZTU1YS00Y2NhLWI2NmQtZjZiOTJhMGQyOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3MzQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YmMyODM3MWM0NTk3MzRmMDNiYjk2MmZlNjM2Y2QwNjY5N2U1YjQ3ZGZkYzBjOTgwZDYyNjIwNDU2Nzg5ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOSZNYB8S3AJvtP9EOgEvAVzpud0lF58i3iks-aLiK4)
> 
> sorry should add `-o yaml/json`
There seems to be something wrong with this section
![image](https://github.com/istio/istio/assets/30618552/0d429e85-a895-48a3-ba66-8376869accd8)

**Comment by zirain** [comment]
Is there anything like EnvoyFilter patched the cluster?

**Comment by matchseller** [comment]
> Is there anything like EnvoyFilter patched the cluster?

Yes,it has been patched. After I deleted the envoyfilter, there was no problem. Thank you very much!
