### ISSUE TITLE
http_conn_manager_prefix stat tag is not matched accordingly

### ISSUE THREAD

**Issue by sschepens** [istio/istio#50894]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

All of our http filter stats do not correctly include the `http_conn_manager_prefix` tag. Here is an example:
```
/stats

http.InboundPassthroughClusterIpv4.jwt_authn.allowed: 0
http.InboundPassthroughClusterIpv4.jwt_authn.denied: 0
http.InboundPassthroughClusterIpv4.rbac.allowed: 0
http.InboundPassthroughClusterIpv4.rbac.denied: 0
http.InboundPassthroughClusterIpv4.rbac.shadow_allowed: 0
http.InboundPassthroughClusterIpv4.rbac.shadow_denied: 0
http.inbound_10.38.36.249_8080.jwt_authn.allowed: 11486
http.inbound_10.38.36.249_8080.jwt_authn.denied: 0
http.inbound_10.38.36.249_8080.rbac.allowed: 11486
http.inbound_10.38.36.249_8080.rbac.denied: 0
http.inbound_10.38.36.249_8080.rbac.shadow_allowed: 11486
http.inbound_10.38.36.249_8080.rbac.shadow_denied: 0
http.inbound_10.38.36.249_8443.jwt_authn.allowed: 154936
http.inbound_10.38.36.249_8443.jwt_authn.denied: 0
http.inbound_10.38.36.249_8443.rbac.allowed: 154936
http.inbound_10.38.36.249_8443.rbac.denied: 0
http.inbound_10.38.36.249_8443.rbac.shadow_allowed: 154936
http.inbound_10.38.36.249_8443.rbac.shadow_denied: 0
```

```
/stats/prometheus

envoy_http_InboundPassthroughClusterIpv4_jwt_authn_allowed{} 0
envoy_http_InboundPassthroughClusterIpv4_jwt_authn_denied{} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_enforce_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_enforce_result="denied"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_result="allowed"} 0
envoy_http_InboundPassthroughClusterIpv4_rbac{authz_dry_run_result="denied"} 0
envoy_http_inbound_10_38_36_249_8080_jwt_authn_allowed{} 11618
envoy_http_inbound_10_38_36_249_8080_jwt_authn_denied{} 0
envoy_http_inbound_10_38_36_249_8080_rbac{authz_enforce_result="allowed"} 11618
envoy_http_inbound_10_38_36_249_8080_rbac{authz_enforce_result="denied"} 0
envoy_http_inbound_10_38_36_249_8080_rbac{authz_dry_run_result="allowed"} 11618
envoy_http_inbound_10_38_36_249_8080_rbac{authz_dry_run_result="denied"} 0
envoy_http_inbound_10_38_36_249_8443_jwt_authn_allowed{} 156829
envoy_http_inbound_10_38_36_249_8443_jwt_authn_denied{} 0
envoy_http_inbound_10_38_36_249_8443_rbac{authz_enforce_result="allowed"} 156829
envoy_http_inbound_10_38_36_249_8443_rbac{authz_enforce_result="denied"} 0
envoy_http_inbound_10_38_36_249_8443_rbac{authz_dry_run_result="allowed"} 156829
envoy_http_inbound_10_38_36_249_8443_rbac{authz_dry_run_result="denied"} 0
```

Theoretically `InboundPassthroughClusterIpv4` and `inbound_10.38.36.249_8080` should be extracted as a tag `http_conn_manager_prefix` which is included in [istio bootstrap templates](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap.json#L99-L102)

We were using BDS to fix this which was deprecated in #48693 and now are left with only tweaking istio bootstrap templates which we were hoping to avoid.

Now this seems like a bug in Istio because the tag extracion regex is defined but does not match values generated by istio itself. Maybe some time ago Istio changed the format used for generating http connection manager names and never adjusted the tag regex accordingly?

FYI, we're using `Sidecar` CRD to define ingress ports.

### Version

```Text
1.21.2
```

**Comment by howardjohn** [comment]
@keithmattix @kyessenov @zirain is there not some way to have envoy do structured stats without performing a regex against a flat string? I think I have asked this before and was told "no", but it just seems kind of hard to accept?

**Comment by sschepens** [comment]
> @keithmattix @kyessenov @zirain is there not some way to have envoy do structured stats without performing a regex against a flat string? I think I have asked this before and was told "no", but it just seems kind of hard to accept?

There are some ways to generate structured stats but internally in envoy and I think they're note used for most stuff, only used for some filters.

Another way to look at this is probably do something like we do with Istio custom stats. Istio custom stats generate tag keys and values with a specific pattern which is then easy to match in regexes. Maybe we can do the same for `stat_prefixes` to ensure we can always extract those tags

**Comment by keithmattix** [comment]
Yeah I think stats is only through regex in Envoy

**Comment by kyessenov** [comment]
Envoy stats pre-date labels so labels can only be added in post-processing.

Yes, I agree we should default to something sane for regexes. Not sure how it ended up in this state. We should set "stat_prefix" to something that's regex friendly or elide superficial details, like port numbers, to avoid a cardinality explosion.

**Comment by jwestbury** [comment]
Any updates on this issue? We're also running into it, and are also hoping to avoid tweaking bootstrap templates.

**Comment by howardjohn** [comment]
@keithmattix did you fix this?

**Comment by jwestbury** [comment]
I suspect @keithmattix 's change won't fix this specific problem - it looks like that PR addresses a similar issue for the cluster name, but not for the http connection manager stat prefix. I think a similar approach should work here, too, though?

I'm happy to dive into the code a bit and contribute a PR here, but admittedly also hesitant given the [backwards compatibility issue](https://github.com/istio/istio/pull/52031) with the cluster name stat fix.

**Comment by keithmattix** [comment]
No I didn't catch this in my initial PR; I can make a follow-up with the same approach. I'd prefer to get #52031 merged first though

**Comment by jwestbury** [comment]
Cheers, Keith. Happy to wait for the other PR to get merged!

**Comment by keithmattix** [comment]
> @keithmattix, we just rolled out the update. We are seeing a double `_` in the metrics:
> 
> `envoy_http__downstream_rq_total{http_conn_manager_prefix="outbound_172.20.75.34_8081"} 0`
> 
> 
> 
> Would this be an easy fix? 

Thanks for the report! I'm surprised my tests didn't catch this but yeah hopefully this'll be a simple fix

**Comment by gustazobalicas** [comment]
@keithmattix is this the simple fix you were alluding to? https://github.com/istio/istio/pull/52234

**Comment by keithmattix** [comment]
> @keithmattix is this the simple fix you were alluding to? #52234

Nope it was #52829 and the accompanying cherry-pick

**Comment by gustazobalicas** [comment]
> Nope it was https://github.com/istio/istio/pull/52829 and the accompanying cherry-pick

Oh sweet! When can we expect this patch to be released/available?

**Comment by keithmattix** [comment]
During the next 1.23 release; should be ~1 month?
