### ISSUE TITLE
Instructions on how to add wasm http filter with custom bootstrap config

### ISSUE THREAD

**Issue by GOVYANSONG** [istio/istio#50893]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Provide detailed instructions to show how to add wasm http filter with custom bootstrap configuration. I was trying with basic auth wasm filter but never able to get it working. When i checked the log of istio-proxy container, it showed either critical panic unset oneof or duplicate listener.

**Describe alternatives you've considered**

WasmPlugin and EnvoyFilter is not an option in our k8s cluster.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by GOVYANSONG** [comment]
I was able to make it work with istio bookstore app and basic auth wasm filter. Instead of remote wasm module, i used persistent volume to store the wasm module file and mount to istio-proxy with pod resource annotation e.g. sidecar.istio.io/uservolume and sidecar.istio.io/uservolumemount. the key takeaway is to create a new listener with filters including wasm filter and route, a cluster to upstream service,

**Comment by zirain** [comment]
> I was able to make it work with istio bookstore app and basic auth wasm filter. Instead of remote wasm module, i used persistent volume to store the wasm module file and mount to istio-proxy with pod resource annotation e.g. sidecar.istio.io/uservolume and sidecar.istio.io/uservolumemount. the key takeaway is to create a new listener with filters including wasm filter and route, a cluster to upstream service,

it would be better if you can share the community a full example.

**Comment by GOVYANSONG** [comment]
Part #1 - custom bootstrap 

=====

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    "staticResources":
    {
      "listeners":
      [
        {
        "address": {
          "socketAddress": {
          "address": "0.0.0.0",
          "portValue": 1080
        }
        },
        "filterChains":
        [
          {
            "filters":
            [
              {
                "name": "envoy.filters.network.http_connection_manager",
                "typedConfig": 
                {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                  "statPrefix": "customauth",
                  "routeConfig": {
                   "name": "local_route",
                   "virtual_hosts": [
                     {
                      "name": "service",
                      "domains": [
                        "*"
                      ],
                      "routes": [
                        {
                         "match": {
                           "prefix": "/"
                         },
                         "route": {
                           "cluster": "local_service"
                         }
                        }
                      ]
                     }
                   ]
                  }
                 ,
                  "httpFilters": 
                  [
                    {
                      "name": "istio.basic_auth",
                      "typed_config": {
                        "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                        "type_url": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                        "value": {
                          "config": {
                            "configuration": {
                              "@type": "type.googleapis.com/google.protobuf.StringValue",
                              "value": "{\n  \"basic_auth_rules\": [\n    {\n      \"prefix\": \"/productpage\",\n      \"request_methods\":[ \"GET\", \"POST\" ],\n      \"credentials\":[ \"ok:test\", \"YWRtaW4zOmFkbWluMw==\" ]\n    }\n  ]\n}\n"
                            },
                            "vm_config": {
                              "vm_id": "basic_auth",
                              "code": {
                                #"remote": {
                                #  "http_uri": {
                                #    "uri": "https://github.com/istio-ecosystem/wasm-extensions/releases/download/1.11.0/basic-auth.wasm",
                                #    "cluster": "remote_wasm",
                                #    "timeout": "10s"
                                #  },
                                #  "sha256": "1a9aec2e3356a5ce3b69e99822cb4a1aada8eebeea1c3f73b19672796b3bcc16"
                                
                                "local": {
                                  "filename": "/var/opt/basic-auth.wasm"
                                }
                              },
                              "runtime": "envoy.wasm.runtime.v8"
                            }
                          }
                        }
                      }
                    },
                    {
                      "name": "envoy.filters.http.router",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                      }
                    }
                  ]
                }
              }
            ]
          }
        ]
        }
      ],
      "clusters": [
        {
            "name": "local_service",
            "type": "STATIC",
            "lb_policy": "ROUND_ROBIN",
            "loadAssignment": {
                "clusterName": "local_service",
                "endpoints": [
                    {
                        "lbEndpoints": [
                            {
                                "endpoint": {
                                    "address": {
                                        "socketAddress": {
                                            "address": "127.0.0.1",
                                            "portValue": 80
                                        }
                                    }
                                }
                            }
                        ]
                    }
                ]
            }
        },
        {
            "name": "remote_wasm",
            "type": "STRICT_DNS",
            "connect_timeout": "1s",
            "dns_refresh_rate": "5s",
            "dns_lookup_family": "v4_only",
            "load_assignment": {
              "cluster_name": "remote_wasm",
              "endpoints": [
                {
                  "lb_endpoints": [
                    {
                      "endpoint": {
                        "address": {
                          "socket_address": {
                            "address": "github.com",
                            "port_value": 443
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            },
            "transport_socket": {
              "name": "envoy.transport_sockets.tls",
              "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                "sni": "github.com"
              }
            }
          }
        ]
    }

**Comment by zirain** [comment]
you can put your examples here: https://github.com/istio/istio/tree/master/samples/custom-bootstrap

**Comment by GOVYANSONG** [comment]
PR created for sample files.

**Comment by zirain** [comment]
can you combine those into a single PR, and keep it minimal.
