### ISSUE TITLE
perf: mixerfilter should shed reports() if telemetry is overloaded

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#5095]
We should validate that mixerfilter does neither block nor incur significant CPU costs once telemetry service starts rejecting RPCs. We have a risk of overloading telemetry if improperly configured, and we don't want to disrupt the entire mesh in that case.

cc @douglas-reid

**Comment by ldemailly** [comment]
great idea but we should also have a counter of how much we dropped on the floor and report that for each subsequent call so we track the % of loss

**Comment by kyessenov** [comment]
Not stale.
