### ISSUE TITLE
Consolidate logging in `istio-cni`

### ISSUE THREAD

**Issue by bleggett** [istio/istio#50958]
**Describe the feature request**

Right now if you want to enable logging for the `istio-cni` daemonset you might try to supply the following granular `logLevel` config:

`level: default:info,cni:debug`

this will only show debug logs for the _cni plugin (used by ambient or sidecar)_ but will not show any logs for the ambient controller, or the CNI plugin (sidecar or ambient) install logic, which are registered as different subcomponents within `istio-cni` - for that you need (I think):

`level: default:info,cni:debug,ambient:debug,install:debug`

This is confusing, and nonobvious. We should consider using either a common component name for log signaling for _everything_ in `istio-cni` (`istio-cni` maybe), or something a bit smarter.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Why not just set `all:debug` if you want everything?

**Comment by bleggett** [comment]
> Why not just set `all:debug` if you want everything?

That will work if you explicitly set `cni.logLevel` directly/by itself yep. And since `cni.logLevel` currently ignores the global setting, that's fine, but that still results in having to do something like

`--set values.cni.logLevel="all:debug" --set values.global.logging.level="all:info"`

ideally I'd want `cni.logLevel` to inherit the global log config, and it cannot as long as we have :point_up:

**Comment by yas8say** [comment]
Hello, a newbie here. Can you guys help me understand this a bit more

**Comment by bleggett** [comment]
@yas8say Sorry! I ended up fixing this in https://github.com/istio/istio/pull/51074 myself because I was already working in the area.

TYVM for volunteering!
