### ISSUE TITLE
migrate guestbook istio workshop using new route rule

### ISSUE THREAD

**Issue by linsun** [istio/istio#5097]
We need to migrate the istio workshop to be used at kubecon EU to use the new route rule and mostly important, validate it works. @dcberg found it doesn't work in 0.7.1 when multiple route rules are applied towards ingress.

**Comment by linsun** [comment]
for 0.7.1: https://github.com/retroryan/istio-workshop/blob/master/exercise-10/README.md

What I am seeing is that when I apply a routerule with a higher precedence that rule is applied but no other rule is kept. Thus only the highest precedence rule is used and the others are discarded.

**Comment by esnible** [comment]
I used the conversion tool on the 80/20 rule and found it doesn't work.  See https://github.com/istio/istio/issues/3621#issuecomment-383169427

I was able to get it working by creating a _DestinationRule_ to define the _Subsets_ referenced by the generated rule.

**Comment by esnible** [comment]
I have a PR that fixes the problem with the 80/20 rule.  https://github.com/istio/istio/pull/5126

**Comment by hklai** [comment]
@linsun is this blocking 0.8 release?

**Comment by linsun** [comment]
yes, ideally we should get the workshop migrated to use the new route rule so that folks can run the workshop with 0.8.

**Comment by esnible** [comment]
Note that one of the guestbook examples is apparently incorrect: https://github.com/retroryan/istio-workshop/issues/32

**Comment by linsun** [comment]
fair point, let's focus on getting the most simple rules working as documented in exercise-10.

**Comment by esnible** [comment]
The rules in the guestbook example will convert if PR https://github.com/istio/istio/pull/5359 is merged.

**Comment by esnible** [comment]
The rules in the guestbook example will convert if PR https://github.com/istio/istio/pull/5411 is merged.  I am closing this work item, which is about https://github.com/retroryan/istio-workshop not about istio/istio.
