### ISSUE TITLE
Use Self Signed Certificate without domain name on Istio Ingress Gateway

### ISSUE THREAD

**Issue by SohilD-TML** [istio/istio#50979]
### Discussed in https://github.com/istio/istio/discussions/50978

<div type='discussions-op-text'>

<sup>Originally posted by **SohilD-TML** May 10, 2024</sup>
Hi all,
I have settup ingress gateway service as NodePort since I dont have domain name. I configure the ingress gateway and virtual service accordingly and it is working fine for HTTP request.

Issue is with the HTTPS when Im trying to use the self signed cert as the secrets providing certificate and key and for calling the api using url: https://nodeportIP:httpport it is giving SSL error. 

can you tell me how to scure http url using istio ingress gateway with self signed cert without using domain name</div>

**Comment by hzxuzhonghu** [comment]
You may provide more info, like the ingress gatewat service, and its xds configuration. Maybe even more cert info
