### ISSUE TITLE
ISTIO_DELTA_XDS is not a pilot-discovery env var

### ISSUE THREAD

**Issue by spacewander** [istio/istio#50977]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

(This is trivial nowadays as ISTIO_DELTA_XDS is defaulted to true since istio 1.22)

Although ISTIO_DELTA_XDS is listed as a pilot-discovery env var in https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars, in fact, it's only used in the pilot-agent.

Therefore setting ISTIO_DELTA_XDS like other pilot discovery env var doesn't take effect. We need to set it as a pilot agent env var with something like `meshConfig.defaultConfig.proxyMetadata.ISTIO_DELTA_XDS=true`.

### Version

```Text
$ istioctl version                                                                          
client version: 1.21.0
control plane version: unknown
data plane version: 1.21.0 (2 proxies)
$ kubectl version --short
Client Version: v1.25.11
Kustomize Version: v4.5.7
Server Version: v1.25.11
```

**Comment by zirain** [comment]
it's a known issue https://github.com/istio/istio/issues/47925

**Comment by hzxuzhonghu** [comment]
Currently not only this one, but also other envs, like `ISTIO_AGENT_ENABLE_WASM_REMOTE_LOAD_CONVERSION`

**Comment by howardjohn** [comment]
Tracking in https://github.com/istio/istio/issues/47925
