### ISSUE TITLE
istio mirror not work when http body larger than about 2M

### ISSUE THREAD

**Issue by Lj-Sakura** [istio/istio#51002]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

By config VirtualService's "mirror" and "mirrorPercentage" field,
i want when http call to service a, then mirror to service b.   when http post body size is small, mirror work fine, but when http post body size is larger than about 2M, mirror not work,  and service b can not receive any request.

### Version

```Text
istioctl version
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (33 proxies), 1.9-dev (5 proxies)

 kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zirain** [comment]
1.9?
