### ISSUE TITLE
FATAL: ThreadSanitizer: unexpected memory mapping 0x583447b8d000-0x58344d4e7000

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#51073]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

CI fails on Tsan, correlated with node upgrades. TSan build likely needs to be upgraded to match the kernel. 

### Version

```Text
all
```

**Comment by kyessenov** [comment]
Likely cause https://github.com/google/sanitizers/issues/1716.
Need clang 18 as a true fix or disable ASLR temporarily.

**Comment by howardjohn** [comment]
Triggered by node upgrade from v1.26.14-gke.1006000 to v1.29.1-gke.1589020, kernel 5.15.146+ -> 6.1.58+.

We are on LLVM 14 mirroring upstream (https://github.com/envoyproxy/envoy-build-tools/blob/c41199833f85ea06a88f1dfa3ac4ebef179c9bdd/docker/linux/ubuntu/Dockerfile#L24)

**Comment by howardjohn** [comment]
Temporary workaround is https://github.com/istio/test-infra/pull/5352, @kyessenov is looking into upgrading LLVM.

Also plausible is `vm.mmap_rnd_bits`.

This might impact older release branches, cc @istio/release-managers

**Comment by howardjohn** [comment]
@kyessenov did we ever get unblocked on LLVM to add the job back?

**Comment by kyessenov** [comment]
No, we from Google are not currently working on updating LLVM toolchains to restore TSan/Asan in OSS right now. We rely on an alternative internal toolchain for now.
