### ISSUE TITLE
Add more platform-specific cni bindir/confdir autodetect in `istio-cni` Helm chart

### ISSUE THREAD

**Issue by bleggett** [istio/istio#51121]
**Describe the feature request**

Right now we use Helm variables to autodetect and set the correct `istio-cni` bin dir for GKE:

https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/templates/daemonset.yaml#L4

Right now GKE is the only "production" platform that seems to need this override, but several mini/local clusters require similar overrides: https://istio.io/latest/docs/ambient/install/platform-prerequisites/

We should look into expanding this autodetection for other platforms/kube variants that need similar overrides. We should also look at whether we want to do this with Helm installtime detection, or Helm profiles (sorta like we already do for openshift - do we want templating autodetect, or do we want something like `helm install XXX --profile=platform-k3d`?)

Should work for:

- Helm (must-have)
- Istioctl (must-have)
- manual template gen + manual apply (not must-have)
 
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
k3s/rancher/similar would be nice

**Comment by bleggett** [comment]
At this point I don't actually think we can do "autodetection" for this.

- We need to know hostpaths at installtime, not runtime, for setting up hostmounts.
- The kubernetes version/gitversions are poor proxies for this generally, as it's actually the primary CNI/container runtime that determine these directories, not Kubernetes.
- gitversions don't even work for most of the cases outside of GKE we need to account for.

Which means realistically the answer is probably mimicking what `openshift` does -> `global.platform=foo` and using profiles.

**Comment by howardjohn** [comment]
I think its still useful to add some istioctl stuff as you mentioned.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/52981 added a bunch of platforms, we need auto-detect for istioctl though

**Comment by bleggett** [comment]
I'm closing this out as a I think _charts_ in general shouldn't rely on autodetection and platform profiles work pretty well.

I do think as mentioned above `istioctl` autodetection + profile selection still makes a lot of sense, so closing this and opening a new issue for that.
