### ISSUE TITLE
In multi-cluster mode, adding topology.kubernetes.io/region label to a new nodes does not trigger the update of envoy cluster endpoints.

### ISSUE THREAD

**Issue by fizos** [istio/istio#51144]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have a multi-primary, multi-network Istio cluster. Currently, everything is functioning properly. However, when we add a new worker node (without the topology.kubernetes.io/region label) to one of the clusters and trigger workload scaling, the traffic is not routed to the pods on the new worker node. By using the "istioctl pc endpoints" command, we can see that the pods on the node are not included in the envoy endpoints configuration. After adding the topology.kubernetes.io/region label to the new node, istiod does not update the cluster endpoints configuration in envoy based on the pods on that node. To make it effective, we need to manually restart these pods.

In this scenario, should istiod be responsible for triggering the update of envoy endpoint configuration based on changes in the topology.kubernetes.io/region label?

### Version

```Text
client version: 1.21.1
control plane version: 1.21.1
data plane version: 1.21.1 (92 proxies)

Client Version: v1.27.6
Kustomize Version: v5.0.1
Server Version: v1.27.6
```

**Comment by hzxuzhonghu** [comment]
This is expected, we donot have a informer watching on node labels. Because the useful attributes istio cared about rarely change.

While watching it may be costy.

**Comment by hzxuzhonghu** [comment]
One workaround is to update the pod labels to retrigger topology recompute

**Comment by fizos** [comment]
OK, thank you for your reply！
