### ISSUE TITLE
TestAuthz_NotHost test: Refactor to run this as a normal test rather than running it via Ingress

### ISSUE THREAD

**Issue by Adarsh-Prakash-Agarwal** [istio/istio#51168]
TestAuthz_NotHost integration test present in the security suite checks for the notHosts operation under authorization policy in istio. This integration test is running via Ingress to different echo targets:
https://github.com/istio/istio/blob/94913d6b11f14655ffd88ab9872e8646696480f6/tests/integration/security/authz_test.go#L426-L483

While we already have a dedicated test for running via ingress in the security test suite to test authorization policy when the source is Ingress:
https://github.com/istio/istio/blob/94913d6b11f14655ffd88ab9872e8646696480f6/tests/integration/security/authz_test.go#L1077-L1243

Can we refactor the TestAuthz_NotHost test case to run it like the below test case present in the security test suite(from one echo instance to another):
https://github.com/istio/istio/blob/94913d6b11f14655ffd88ab9872e8646696480f6/tests/integration/security/authz_test.go#L390-L424

**Comment by howardjohn** [comment]
Host checks are almost exclusively used in ingress so it kind of makes sense as written.

Is there some context behind the motivation here?
