### ISSUE TITLE
CUSTOM AuthorizationPolicy filter Order

### ISSUE THREAD

**Issue by sschepens** [istio/istio#51173]
**Describe the feature request**
This issue is related to https://github.com/istio/istio/issues/45511 and https://github.com/istio/istio/issues/47255 
Creating a new issue because the latter has been closed and the first one is not seeing any progress.

Current status:
```
- Metadata Exchange
- CUSTOM Authz <-- move this after Authz
- WASM Authn
- Authn
- WASM Authz
- Authz
- WASM Stats
- Stats
- WASM unspecified
```

From a conceptual stand point, we're using `AuthorizationPolicy` so this this is `authz` and should at least run in the `authz` phase, not at the very first of the filter chain.

From an architectural stand point, we're not really interested on having *invalid* traffic (unauthenticated or unauthorized) hit our `ext_authz` server, which is currently possible because `CUSTOM authz` policies are placed at the very first of the filter chain, so nothing stops that traffic from generating requests to our `ext_authz` server. We also want to be able to use information populated by `jwt` filters in `CUSTOM authz`, which should totally make sense since `authz` is supposed to need information form `authn` and we don't really want to implement `authn` again in our `ext_authz` server.

Desired:
```
- Metadata Exchange
- WASM Authn
- Authn
- WASM Authz
- Authz
- CUSTOM Authz <-- moved
- WASM Stats
- Stats
- WASM unspecified
```

I realize that changing this ordering can break some setupd, I think I read some comments of pleople saying that current ordering allows to use `ext_authz` as an authenticator, though it probably should not be the intended use case.
Maybe we want to add a field to `AuhtorizationPolicy` to be able to customize the ordering according to the use case?

**Describe alternatives you've considered**
Using EnvoyFilter to configure filters ourselves

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by sschepens** [comment]
@howardjohn @kyessenov what do you think about this? I could open a PR to add a filed to `AuthorizationPolicy` to be able to customize the order if that's desirable, or maybe we could use an annotation.

**Comment by howardjohn** [comment]
I think this would break a lot of cases, so at best this could be an option IIUC the use cases correctly

**Comment by nvh0412** [comment]
I came across this issue from our Istio slack, I thought it was a bug initially as for me, it was kind of oblivious when putting `authn` before `authz`, but turned out there were some specific usecases where some people used this `ext_authz` filter to do a token exchange for example. In my case, I were wanted to piggyback on the `RequestAuthentication` to offload some of the traffic from this external authorization by applying RequestAuthentication with JWT on top of it. So it might be impossible with the current implementation.
