### ISSUE TITLE
Blackholecluster logs missing REQUESTED_SERVER_NAME in json mode

### ISSUE THREAD

**Issue by adamdavis40208** [istio/istio#51178]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Previously, our proxy logs were using the defaults, and would print out information about the host we were trying to connect to:
`[2023-04-24T15:57:17.434Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 142.250.217.115:443 10.52.97.65:58576 sqa.ory.sh -`

Since updating to json logs, this information about the host name is now null, and makes debugging these tough:

`{"route_name":null,"request_id":null,"x_forwarded_for":null,"response_code":0,"response_code_details":null,"bytes_received":0,"connection_termination_details":null,"user_agent":null,"authority":null,"upstream_transport_failure_reason":null,"protocol":null,"stack_name":"stacky-stack","requested_server_name":null,"method":null,"upstream_host":null,"duration":0,"client_ip":null,"grpc_status":n
ull,"upstream_local_address":null,"upstream_cluster":"BlackHoleCluster","env":"dev","response_flags":"UH","downstream_remote_address":"10.52.59.26:59206","upstream_service_time":null,"downstream_loc
al_address":"240.240.180.115:81","request_fwd_for":null,"path":null,"start_time":"2024-05-21T16:19:04.707Z","bytes_sent":0}`

Any tips on debugging why this information is now null?

The docs point at REQUESTED_SERVER_NAME being the source where we used to see it: https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format

`istioctl proxy-config listeners my-pod-6849b95c99-b79sp -n my-namespace -o json`

```       
 "accessLog": [
        {
            "name": "envoy.access_loggers.file",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                "path": "/dev/stdout",
                "logFormat": {
                    "jsonFormat": {
                        "authority": "%REQ(:AUTHORITY)%",
                        "bytes_received": "%BYTES_RECEIVED%",
                        "bytes_sent": "%BYTES_SENT%",
                        "client_ip": "%REQ(TRUE-Client-IP)%",
                        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
                        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
                        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
                        "duration": "%DURATION%",
                        "grpc_status": "%GRPC_STATUS%",
                        "janus_environment": "%ENVIRONMENT(JANUS_ENVIRONMENT)%",
                        "janus_stack_name": "%ENVIRONMENT(JANUS_STACK_NAME)%",
                        "method": "%REQ(:METHOD)%",
                        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                        "protocol": "%PROTOCOL%",
                        "request_fwd_for": "%REQ(X-FORWARDED-FOR)%",
                        "request_id": "%REQ(X-REQUEST-ID)%",
                        "requested_server_name": "%REQUESTED_SERVER_NAME%",
                        "response_code": "%RESPONSE_CODE%",
                        "response_code_details": "%RESPONSE_CODE_DETAILS%",
                        "response_flags": "%RESPONSE_FLAGS%",
                        "route_name": "%ROUTE_NAME%",
                        "start_time": "%START_TIME%",
                        "upstream_cluster": "%UPSTREAM_CLUSTER%",
                        "upstream_host": "%UPSTREAM_HOST%",
                        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
                        "upstream_service_time": "%REQ(X-ENVOY-UPSTREAM_SERVICE_TIME)%",
                        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
                        "user_agent": "%REQ(USER-AGENT)%",
                        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%"
                    }
                }
            }```


### Version

```Text
$ istioctl version                                                                                                                       
client version: 1.21.2
istiod version: 1.20.6
```

**Comment by howardjohn** [comment]
Is the only difference changing to json? and if you switch back it works?

**Comment by mikhail-khodorovskiy** [comment]
> Is the only difference changing to json? and if you switch back it works?

I have the same problem.  JSON logs don't log the REQUESTED_SERVER_NAME and it's critical for Blackhole cluster debugging to have this information.

**Comment by howardjohn** [comment]
Is the issue specifically about JSON _only_, or you happen to be using JSON?

If not tied to json, then https://github.com/envoyproxy/envoy/issues/34396 is needed to fix it. Unfortunately the Envoy community doesn't seem to interested.

**Comment by altdelnow** [comment]
@howardjohn We are experiencing intermittent failed request on our eks cluster using istio-1.24.0. Following is log snippet. Any pointer as to how to debug can be very helpful.

 :"istio-proxy","container_hash":"1234","docker_id":"1234","host":""},"log":"2025-07-21T08:44:43.30982997Z stdout F {"upstream_cluster":"outbound|3198|b|svc.","duration":20018,"requested_server_name":null,"response_code":0,"response_flags":"DC","upstream_host":"1.0.0.0.","response_code_details":"downstream_remote_disconnect","upstream_service_time":null,"upstream_transport_failure_reason":null,"upstream_local_address":"1.0.0.0:60192","start_time":"2025-07-21T08:44:23.097Z","user_agent":"Apache-HttpClient/4.5.13ll,
