### ISSUE TITLE
EnvoyFilter FIlterClass not implemented

### ISSUE THREAD

**Issue by sschepens** [istio/istio#51177]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

EnvoyFilter has a field `filterClass` which according to documentation is intended to be used to insert filters at specific points relative to standard istio filters. It was introduced in https://github.com/istio/api/pull/1588 but apparently never implemented in Istio codebase.

### Version

```Text
1.22
```

**Comment by hzxuzhonghu** [comment]
@kyessenov Do you remember that

**Comment by kyessenov** [comment]
Not implemented. It should have been marked that way.

**Comment by hzxuzhonghu** [comment]
Lets first ,mark it

**Comment by hzxuzhonghu** [comment]
not stale
