### ISSUE TITLE
CNI uses a fixed value cluster.local for trustDomain in ambient mode

### ISSUE THREAD

**Issue by birkland** [istio/istio#51182]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If you install istiod in ambient mode with a specified trustDomain, pod-to-pod communication won't work in ambient mode

Install with a custom trustDomain:
```
profile: ambient
meshConfig:
  defaultConfig: {}
  trustDomain: mgmt-cluster
```

curl between two pods in captured namespaces does not succeed, with this in ztunnel logs:
```
2024-05-20T23:52:37.605553Z     error   state:proxy{uid=3f957bae-0947-42d3-a3db-d90258c0f0e9}   workload does not match proxy workload uid. this is probably a bug. please report an issue
2024-05-20T23:52:37.605687Z     error   access  connection complete     src.addr=10.244.0.15:53326 src.workload=curl-7b7ddfb96-2tqrc src.namespace=curl dst.addr=10.244.0.12:8080 dst.service=httpbin.httpbin-inmesh.svc.cluster.local dst.workload=httpbin-675998f577-m4fbz dst.namespace=httpbin-inmesh direction="inbound" bytes_sent=0 bytes_recv=0 duration="0ms" error="connection closed due to policy rejection"
```

Looking at the ztunnel config it looks like there is a conflict in trustDomain for workloads
```
"3f957bae-0947-42d3-a3db-d90258c0f0e9": {
      "connections": {
        "inbound": [],
        "outbound": []
      },
      "info": {
        "name": "httpbin-675998f577-m4fbz",
        "namespace": "httpbin-inmesh",
        "serviceAccount": "httpbin",
        "trustDomain": "cluster.local"
      },
      "state": "Up"
    },
```
```
    "/10.244.0.12": {
      "canonicalName": "httpbin",
      "canonicalRevision": "v1",
      "clusterId": "mgmt-cluster",
      "name": "httpbin-675998f577-m4fbz",
      "namespace": "httpbin-inmesh",
      "node": "mgmt-cluster-control-plane",
      "protocol": "HBONE",
      "serviceAccount": "httpbin",
      "status": "Healthy",
      "trustDomain": "mgmt-cluster",
      "uid": "mgmt-cluster//Pod/httpbin-inmesh/httpbin-675998f577-m4fbz",
      "workloadIps": [
        "10.244.0.12"
      ],
      "workloadName": "httpbin",
      "workloadType": "deployment"
    },
```

The problem stems from the fact that the CNI provides the contents of `info` above, and right now the CNI only returns the default value. 
from [cni/pkg/nodeagent/ztunnelserver.go](https://github.com/istio/istio/blob/be48f338ce99b207c3ffe52b336695b9bc481a39/cni/pkg/nodeagent/ztunnelserver.go#L280)
```
func podToWorkload(pod *v1.Pod) *zdsapi.WorkloadInfo {
	namespace := pod.ObjectMeta.Namespace
	name := pod.ObjectMeta.Name
	svcAccount := pod.Spec.ServiceAccountName
	trustDomain := spiffe.GetTrustDomain()
	return &zdsapi.WorkloadInfo{
		Namespace:      namespace,
		Name:           name,
		ServiceAccount: svcAccount,
		TrustDomain:    trustDomain,
	}
}
```
`spiffe.GetTrustDomain()` returns a default of `cluster.local`, unless the `spiffe.SetTrustDomain()` has been called to set a different value.  There is currently nowhere in the Istio CNI codebase that calls `spiffe.SetTrustDomain()`.  The CNI should maybe  inspect istiod configMap (though if there are two configMaps for two revisions and they don't agree on trust domain, it's not clear what should happen).  

### Version

```Text
1.22.0
```

**Comment by howardjohn** [comment]
@bleggett wdyt here? we don't read mesh config in CNI today...

**Comment by bleggett** [comment]
I guess we could read meshconfig, or set an install time env for the CNI, but I don't think the CNI should provide this information - it's not K8S context, it's Istio's context, and by-design `istio-cni` doesn't have a CP dependency.

ztunnel does - wonder if we could just have ZT set this? It should be able to.

**Comment by howardjohn** [comment]
good call maybe we just remove trust domain from WorkloadInfo? it's not needed from  security POV on the pod check

**Comment by keithmattix** [comment]
FYI, we read trusdomain for WDS to do telemetry

**Comment by bleggett** [comment]
> good call maybe we just remove trust domain from WorkloadInfo? it's not needed from  security POV on the pod check 

Yep we should just drop it. I'll do this in a bit.

**Comment by howardjohn** [comment]
Yeah we get all info from wds, this is used to match wds to the fd sent by cni so we are not matching on ip

**Comment by birkland** [comment]
Not sure what the original intent was, but removing `trustDomain` from `zdsapi.WorkloadInfo` seems to make a lot of sense.  It doesn't seem to provide any value coming from the CNI.
