### ISSUE TITLE
istioctl should install Gateway API CRDs for you

### ISSUE THREAD

**Issue by craigbox** [istio/istio#51190]
**Describe the feature request**

istioctl precheck should check for the correct version of the Gateway API CRDs for you, and (optionally) istioctl install should install them for you.

**Describe alternatives you've considered**

Make everyone read an awkward warning on every page of istio.io.

**Affected product area (please put an X in all that apply)**

[x] Ambient
[x] Docs
[x] User Experience

**Comment by howardjohn** [comment]
Check SGTM.

Install -- is there a meaningful difference between "make sure you install with `istioctl install --include-gateway-crds`" vs "install, then run `kubectl apply crds.yaml`"? Or is the expectation it would be on by default as well?

The tricky thing with the CRDs is Istio doesn't own them. There are many versions, variants (experimental or not), and many implementations in the same cluster concurrently using them

**Comment by ilrudie** [comment]
Seems like we should at least consider a --install-if-not-found type of behavior to prevent trampling existing CRDs

**Comment by craigbox** [comment]
> is there a meaningful difference between X and Y

People seem to care about how many "steps" a "getting started" guide takes.  Given we have our own utility that does the installation, I'd love to get as much as practical into that.  (For example, I'm also checking if we can have it handle addons.)

**Comment by howardjohn** [comment]
Addon removal was intentional: https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM/edit#heading=h.qlmnvhzb2ib2

**Comment by howardjohn** [comment]
if we want a kitchen-sink playground to install in 1 step we can do something like https://github.com/csantanapr/knative-kind

**Comment by craigbox** [comment]
I do remember that.

Part of the reasoning behind the question was @peterj's comment that with other tools, you only need the client binary to get going, and you get a lot more in the download for Istio.

I don't like how we're judged, but if there are simple things we can do to improve the process, I'd love to consider them.

**Comment by peterj** [comment]
Not sure who's maintaining it, but there's a Homebrew package for Istio CLI. Using that gets rid of a couple of steps in the installation (download the package, it creates a folder for you, copy/move the istioctl binary somewhere, put it in the path etc.). 

However, if you've installed the CLI with `brew` you don't have any of the addon YAML files. Pointing users to install or download the YAMLs files from github URLs doesn't look pretty. My thinking was if we'd embed the Grafana/Jaeger/Kiali manifests into the istioctl binary and add a subcommand that installs those either individually or as part of some demo installation: 

```
istioctl install --set profile=demo -y 
..
istioctl addons prometheus install
istioctl addons grafana install
..
```

**Comment by craigbox** [comment]
(Or just have the `istioctl` command download them from GitHub URLs)

**Comment by MorrisLaw** [comment]
> istioctl precheck should check for the correct version of the Gateway API CRDs for you, and (optionally) istioctl install should install them for you.

+1 to this and other's comments about installing the Gateway API CRDs if not found. That would be pretty helpful imo.

**Comment by craigbox** [comment]
I hate you, policy bot

**Comment by gclawes** [comment]
For those installing via helm it would be nice to be able to install the Gateway API CRDs that way, as well.
