### ISSUE TITLE
[ambient] Ingress gateway to waypoint

### ISSUE THREAD

**Issue by sando38** [istio/istio#51214]
**Describe the feature request**

Currently, if I have cluster external ingress via a `gateway`, the traffic from the `gateway` to a `waypoint` enabled service does not go through the `waypoint` (but probably via `ztunnel` only).

Most L7 policies I can attach to the ingress gateway `authzPol`, however, I have one setup which does not work:
* admin policy for "allow-nothing"
* A CUSTOM policy on the gateway to initiate OIDC for `requestAuthn`
* Now using `requestPrincipals` in the `AuthzPol` of the destination application does not work, because it does not go through the waypoint. Same applies to any other L7 policies like `methods: GET`.

**Describe alternatives you've considered**

I helped myself by creating an in-between `haproxy` being part of the ambient mesh just inelegantly mapping and forwarding requests to destination services which then would be captured by the `waypoint`, because it is mesh-to-mesh traffic

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by sando38** [comment]
@louiscryan as discussed. 👍

**Comment by mikemorris** [comment]
Following this as it relates to https://github.com/kubernetes-sigs/gateway-api/issues/1478 - this is undefined in the Gateway API spec currently, and default behavior differs between Istio (route from ingress directly to backends, bypassing mesh rules) and Linkerd (deploy sidecar next to in-cluster 3rd party N/S gateway, follow mesh rules). Additionally, most cluster-external N/S gateways (such as those offered by cloud vendors), would typically route directly from the ingress to backend pods to avoid an extra routing hop and due to the impracticality of deploying a sidecar next to them.

**Comment by nuKs** [comment]
Does it mean there is _no_ way for ingress traffic to be routed from the

(a) aws NLB, to
(b) a random ztunnel, to
(c) the namespace-specific target (waypoint or ingress) gateway

with this setup (1 - N arity / aws NLB - istio X gateway) ?

Would you recommend switching back to sidecar for this purpose?

**Comment by sando38** [comment]
@howardjohn At least for me this issue is closed with the introduction of the service label `istio.io/ingress-use-waypoint: true` from the `1.24` release (https://github.com/istio/istio/commit/e998c65978624405a8427a850abb78b8481f6960).

**Comment by howardjohn** [comment]
Great! Thanks

**Comment by nataraj24** [comment]
> [@howardjohn](https://github.com/howardjohn) At least for me this issue is resolved with the introduction of the service label `istio.io/ingress-use-waypoint: true` from the `1.24` release ([e998c65](https://github.com/istio/istio/commit/e998c65978624405a8427a850abb78b8481f6960)).

@sando38 - can you please share more details how this issue is resolved.  i am also facing this issue.

**Comment by vivekbhalerao** [comment]
> > [@howardjohn](https://github.com/howardjohn) At least for me this issue is resolved with the introduction of the service label `istio.io/ingress-use-waypoint: true` from the `1.24` release ([e998c65](https://github.com/istio/istio/commit/e998c65978624405a8427a850abb78b8481f6960)).
> 
> [@sando38](https://github.com/sando38) - can you please share more details how this issue is resolved. on which istio object the label applied, apart from this any configuration is changed. i am also facing this issue.

i have tried adding the label to ingress gateway, namespace and service(trial and error), but the ingress traffic did not route through waypoint, do i need to add any additional config. Am using istio 1.25

**Comment by jaehong21** [comment]
> > > [@howardjohn](https://github.com/howardjohn) At least for me this issue is resolved with the introduction of the service label `istio.io/ingress-use-waypoint: true` from the `1.24` release ([e998c65](https://github.com/istio/istio/commit/e998c65978624405a8427a850abb78b8481f6960)).
> > 
> > 
> > [@sando38](https://github.com/sando38) - can you please share more details how this issue is resolved. on which istio object the label applied, apart from this any configuration is changed. i am also facing this issue.
> 
> i have tried adding the label to ingress gateway, namespace and service(trial and error), but the ingress traffic did not route through waypoint, do i need to add any additional config. Am using istio 1.25

https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars
@vivekbhalerao Have you tried to set `ENABLE_INGRESS_WAYPOINT_ROUTING` env to `true` for pilot?

**Comment by dellnoantechnp** [comment]
> > > [@howardjohn](https://github.com/howardjohn) At least for me this issue is resolved with the introduction of the service label `istio.io/ingress-use-waypoint: true` from the `1.24` release ([e998c65](https://github.com/istio/istio/commit/e998c65978624405a8427a850abb78b8481f6960)).
> > 
> > 
> > [@sando38](https://github.com/sando38) - can you please share more details how this issue is resolved. on which istio object the label applied, apart from this any configuration is changed. i am also facing this issue.
> 
> i have tried adding the label to ingress gateway, namespace and service(trial and error), but the ingress traffic did not route through waypoint, do i need to add any additional config. Am using istio 1.25

I used istio `1.25`, when I set service label `istio.io/ingress-use-waypoint: "true"` to service  `httpbin` , it's effect.

```txt
---------------------------------------------  AuthorizationPolicy ------------------------------------------------------
curl -->  istio-ingressgateway  --> ztunnel  -->  my-waypoint  --> ztunnel  -->  httpbin service -->  httpbin pod
----------------------------------------------------------------------------------  set label here  -----------------------
```
help you.

**Comment by mgnisia** [comment]
can confirm the that approach of @dellnoantechnp also worked for me.

**Comment by deepak7946** [comment]
Is there a way to get a similar routing if we are using google gateways (regional internal load-balancers - L7)? Have already tried the label on the target service which did not work, is there any way to get a similar routing in this case?
