### ISSUE TITLE
TLS passthrough sends all traffic on 443 to single service

### ISSUE THREAD

**Issue by Sumanth-A** [istio/istio#51220]
We are setting up an app on AKS and we use Istio to manage TLS and traffic routing. Since this app is expecting HTTPS traffic we are not terminating TLS at Istio gateway level and using TLS mode PASSTHROUGH to send traffic as is, for this we also match port 443 of gateway to app's service in Virtual Service configuration which now sends all traffic at gateway on 443 including traffic that is meant for other services to this service. I understand since Istio is not terminating TLS it won't be able to route traffic. Now other than creating another host and use it for MQ is there another way we can handle this?

**Comment by hzxuzhonghu** [comment]
This guide provides a good example https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/#configure-an-ingress-gateway
