### ISSUE TITLE
ExportTo "*" is not working when we have multiple virtualservices with a same host

### ISSUE THREAD

**Issue by anannaya** [istio/istio#51253]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are trying split the multiple virtualservices with the same host with mesh gateway using ExportTo ,  When we try with .  or  individual namespaces list routes are properly working . But with * its not working.   Fundamental requirement is keep the route across the mesh using mesh gateway  , Any solution would be helpful.

### Version

```Text
bin/istioctl version
client version: 1.20.3
control plane version: 1.20.3
data plane version: 1.20.3 (863 proxies)
```

**Comment by hzxuzhonghu** [comment]
what do you mean by `But with * its not working`

**Comment by anannaya** [comment]
@hzxuzhonghu  Thanks for checking,
We have 2 or more Split vs , As i am aware of limitation that at mesh gateway we cannot have multiple vs with the same hostname, So we are using the "exportTo" feature . 
For Example:

`
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtual-assistant-redirect-vs
  namespace: tr
spec:
  exportTo:
  - "gm"
  - "mm"
  - "tr"
  gateways:
  - default-gateway-alb.istio-system.svc.cluster.local
  - mesh
  hosts:
  - virtual-assistant.www.xxxx.com
  - virtual-assistant.tr.svc.cluster.local
  http:
  - match:
    - uri:
        regex: .*\/virtual-assistant\/v1\/.*(b47e2cdb-f826-43ff-9699-25cd917e432f).*
    - queryParams:
        canary:
          exact: "true"
`
And
`
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtual-assistant-vs
  namespace: tr
spec:
  exportTo:
  - "gm"
  - "mm"
  - "tr"
  gateways:
  - default-gateway-alb.istio-system.svc.cluster.local
  - mesh
  hosts:
  - virtual-assistant.www.xxxx.com
  - virtual-assistant.tr.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /virtual-assistant/v1/text
    route:
    - destination:
        host: virtual-assistant
        port:
          number: 8080
        subset: virtual-assistant
  - match:
    - uri:
        prefix: /build_info
    route:
    - destination:
        host: virtual-assistant
        port:
          number: 8080
        subset: virtual-assistant
`

We want actually to sync routes for entire mesh using  using 
`
  exportTo:
  - "."
  `
which is not working.

**Comment by anannaya** [comment]
@hzxuzhonghu  Am i missing anything here ?

**Comment by hzxuzhonghu** [comment]
@anannaya What do you expect, and what is the current route config look like

**Comment by hzxuzhonghu** [comment]
>As i am aware of limitation that at mesh gateway we cannot have multiple vs with the same hostname, 

I think i cannot find the limitation. As from `BuildSidecarVirtualHostWrapper`, we can generate vhost from different vses

**Comment by anannaya** [comment]
@hzxuzhonghu  https://github.com/istio/istio/issues/22997#issuecomment-1274176259 .  This is the same requirement i have.

**Comment by anannaya** [comment]
> @anannaya What do you expect, and what is the current route config look like
When we create a multiple VS with the samehostname at the mesh gateway , latest applied vs routes does not get added. 
So we used the "exportTo" option both the VS it seems to working but the only challenge is we need to specify all the namespace namespace in exportTo .

**Comment by hzxuzhonghu** [comment]
>@hzxuzhonghu https://github.com/istio/istio/issues/22997#issuecomment-1274176259 . This is the same requirement i have.

@anannaya It is just not recommended to use that way, because the route order is undetermined if there are multi VS for same host.

**Comment by hzxuzhonghu** [comment]
>When we create a multiple VS with the samehostname at the mesh gateway , latest applied vs routes does not get added.

I think the later one maybe ignorred by matchall route defined in older one

**Comment by keithmattix** [comment]
That is generally the case yes; exact host duplicates theoretically get filtered with the first one taking precedence

**Comment by anannaya** [comment]
We have a many APIs So We have to split the VS , there is no conflict of routing rules between 2 VS and also we are not concerned about the routes priority order.   When we use `exportTo` for both the VS routes are synced properly but the question is Why `*` is not working? @keithmattix @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Checked the code and found #49554 sort the vs by creation timestamp. But iirc this patch is not included in 1.20.3.

**Comment by anannaya** [comment]
@hzxuzhonghu  So using delegate we can merge the virtualService routes ?

**Comment by hzxuzhonghu** [comment]
Delegate vs feature can be used to merge one root VS with multi delegates. And keep in mind it does not alter the orders

**Comment by anannaya** [comment]
@hzxuzhonghu  We already using the exporTo " ns1,ns2"  which overrides the RDS rules from the older VS , Will this gets behaviour gets impacted when we upgrade latest versions from 1.20.3 ?
