### ISSUE TITLE
Support for Custom Resource Configurations in Waypoint

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#51251]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
I need to customize the resource configuration for my Waypoint, but I could not find any related configuration options.

From the current implementation of Waypoint, it seems that the template does not support any configuration and is hard-coded. 
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/waypoint.yaml#L185-L191

![image](https://github.com/istio/istio/assets/44200120/d61e1d9a-09c8-4267-af19-b37f21e15076)

This lack of flexibility makes it difficult to adapt Waypoint to specific use cases that require different resource allocations, replica counts, or other pod-level settings.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by nicole-lihui** [comment]
add discussion： https://github.com/istio/istio/discussions/51252

**Comment by nicole-lihui** [comment]
similar: https://github.com/istio/istio/issues/48000

gatewayAPI and waypoint are essentially similar. so they share the same requirements.

**Comment by zirain** [comment]
let's keep track in one place
