### ISSUE TITLE
Istio-side tests to validate `istioctl` can correctly deserialize output from various ztunnel endpoints

### ISSUE THREAD

**Issue by bleggett** [istio/istio#51261]
**Describe the feature request**

Context:

https://github.com/istio/istio/issues/50807#issuecomment-2090783344

https://github.com/istio/istio/pull/51225#issuecomment-2128123267

Desired outcome: 

Istio CI should fail if there is a mismatch between what ztunnel actually emits for admin/status/config enpoints, and what `istioctl` expects. Right now we do not have a CI check for this, so we rely on manual testing to catch, which is not ideal.

This is pretty straightforward and should be a trivial test.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
closed by #53126
