### ISSUE TITLE
Istio sidecar communication only works in one direction?

### ISSUE THREAD

**Issue by aMiss-aWry** [istio/istio#51267]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We use istio networking by injecting istio sidecars set up on our kubernetes pods. We intermittently see the following errors. Restarting the application pods appears to halt the errors for hours, but they eventually resume. This is causing problems downstream as we believe the this may be the cause of missing events, which various users use to trigger CI jobs which are now no longer being triggered.

We see these three types of errors:

UF, URX:

`[2024-05-28T18:42:53.929Z] "- - -" 0 UF,URX - - "delayed_connect_error:_111" 0 0 0 - "-" "-" "-" "-" "100.72.2.95:7801" InboundPassthroughClusterIpv4 - 100.72.2.95:7801 100.72.9.97:33948 - -`

503 UF: 

`[2024-05-28T15:12:57.143Z] "POST /plugins/high-availability/event/ref-updated HTTP/1.1" 503 UF upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111} - "delayed_connect_error:_111" 398 152 0 - "-" "Apache-HttpClient/4.5.14 (Java/17.0.10)" "87383523-4754-4ac6-9acd-5e63d4cebb65" "redacted.svc.cluster.local:8080" "100.72.2.83:8080" inbound|8080|| - 100.72.2.83:8080 100.72.9.85:44759 - default`

503 URX:

`[2024-05-28T15:12:57.638Z] "POST /plugins/high-availability/event/ref-updated HTTP/1.1" 503 URX via_upstream - "-" 334 152 77 76 "-" "Apache-HttpClient/4.5.14 (Java/17.0.10)" "d7d45b0a-1a65-451a-bf6c-990bc8572d95" "redacted.svc.cluster.local:8080" "100.72.2.83:8080" outbound|8080||redacted.svc.cluster.local 100.72.9.85:46041 100.72.2.83:8080 100.72.9.85:39162 - default`

I checked and the application itself remained healthy throughout this time, the servers were accessible to end users etc.

Sample healthy message after pod restart:
`[2024-05-28T18:52:35.465Z] "POST /plugins/high-availability/event/ref-updated HTTP/1.1" 204 - via_upstream - "-" 376 0 451 451 "-" "Apache-HttpClient/4.5.14 (Java/17.0.10)" "30689307-fecc-479b-8775-3cb85500f91c" "redacted.svc.cluster.local:8080" "100.72.2.95:8080" outbound|8080||redacted.svc.cluster.local 100.72.9.97:41300 100.72.2.95:8080 100.72.9.97:41288 - default`

Any hints for what to look for from here would be greatly appreciated.

### Version

```Text
$ istioctl version
client version: 1.16.5
control plane version: 1.20.4
data plane version: 1.19.3 (3 proxies), 1.20.4 (16 proxies)
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

### Additional Information

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-05-28 20:12:34.461446 +0200 CEST

CLI version:
version.BuildInfo{Version:"1.16.5", GitRevision:"ae8d5164776cd55bf61d9d3fc4658b44a77c6e24", GolangVersion:"go1.19.9", BuildStatus:"Clean", GitTag:"1.16.5"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.20.4", GitRevision:"ff333a3512ba8321f40d90b6fc041db04fcb280b", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.4"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.20.4", GitRevision:"ff333a3512ba8321f40d90b6fc041db04fcb280b", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.20.4"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.20.4, 1.19.3}

**Comment by hzxuzhonghu** [comment]
delayed connect error: 111, 111 means Connection Refused

https://github.com/istio/istio/issues/48267

**Comment by aMiss-aWry** [comment]
> delayed connect error: 111, 111 means Connection Refused
> 
> #48267

I see that in that thread the solution is not given, I understand the problem is Connection Refused, but why would the port be intermittently closed or unavailable?

**Comment by aMiss-aWry** [comment]
@hzxuzhonghu Hi, I believe I have more details after debugging today. 

We have two sample logs, one a success and one a failure:

Successful, from pod-0 meant to go to pod-1:

[2024-05-28T15:11:31.724Z] "POST /link HTTP/1.1" 204 - via_upstream - "-" 1373 0 8 8 "-" "Apache-HttpClient/4.5.14 (Java/17.0.10)" "e3e28bb6-abb7-4b36-9a1e-ce0b64ab32fd" "pod-1:8080" "100.72.9.85:8080" **inbound|8080|| 100.72.2.83:53185 100.72.9.85:8080 100.72.2.83:54318** - default

Source: pod-0
Destination: pod-1
Source IP: 100.72.2.83 (correct)
Destination IP: 100.72.9.85 (correct)

Failing, from pod-1 meant to go to pod-0:

[2024-05-28T15:12:08.546Z] "POST /link HTTP/1.1" 503 UF upstream_reset_before_response_started{remote_connection_failure,delayed_connect_error:_111} - "delayed_connect_error:_111" 1207 152 0 - "-" "Apache-HttpClient/4.5.14 (Java/17.0.10)" "360a416f-3e44-4b11-9330-560a67c77c1e" "pod-0:8080" "100.72.2.83:8080" **inbound|8080|| - 100.72.2.83:8080 100.72.9.85:33236** - default

Source: pod-1
Destination: pod-0
Source IP: 100.72.2.83 (actually the ip of the destination!)
Destination IP: 100.72.9.85 (actually the ip of the source!)

Is my understanding of this correct? That would explain the errors we're seeing (all events from pod-0 to pod-1 are fine, but from pod-1 to pod-0 are missing). I understand this is likely our error at this point, do you have any hints or have you seen similar?

**Comment by hzxuzhonghu** [comment]
Is `100.72.2.83:8080` pod0?  Can you check it manually does your pod0 listenen on 8080

**Comment by gaurav-jotwani** [comment]
[aMiss-aWry](https://github.com/aMiss-aWry) were you able to resolve this issue?
