### ISSUE TITLE
Request: Option for istio gateways to return more logical response codes

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [istio/istio#51276]
**Describe the feature request**
We had an [issue](https://github.com/istio/istio/issues/49638) causing the istiogateway RDS to go stale. This presented as a 404 response to users as the gateway couldn't find the route. To us this didn't make much sense and would have made more sense to be presented as a 502 or 503 as there was the problem was a bad gateway. Looking at the docs to see if there was a way to toggle what response was presented to one that makes sense i couldn't find anything so an ability to override the 404 in this situation would be useful to whatever code makes sense for the team managing

**Describe alternatives you've considered**
Not really sure what alternatives could exist. Arguably the fact that it returns 404 could be considered a bug but i'm sure there are reasons it is the way it is

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
How would envoy distinguish between "the user sent a totally bogus request that was not found" vs "this should have been found but I didn't have the route"?

**Comment by hzxuzhonghu** [comment]
Kind of remember that code can be customized @howardjohn

**Comment by dhumphries-sainsburys** [comment]
> How would envoy distinguish between "the user sent a totally bogus request that was not found" vs "this should have been found but I didn't have the route"?

I would say by not returning a 404 on the ones where a route should have been found, something as simple as switching gateway 404's to 503's makes sense as if there is no service then the service is definitely unavailable. The issue we have is that a lot of applications on our platform regularly return a 404 as normal operation and a problem on the ingress layer returning the same would just get lost in the noise and whilst technically correct doesn't really fit with what is actually happening problem-wise.

**Comment by dhumphries-sainsburys** [comment]
I suppose the thing we are looking for here is a way to differentiate a 404 from there legitimately being no route and a 404 from the gateway itself as it's internal routing failed for whatever reason as i get it it is literally a no route found as far as the gateway is concerned but the reason for the lack of route isn't because it doesn't exist but a failure in the gateway.

Even if it was something slightly hacky as a switch that essentially says _"if the gateway is in any way unhealthy and you hit an error all errors are to be treated as code xxx"_ as obviously we will aim for the gateway services to all be completely healthy and it will have the effect of alerting us to issues rather than waiting for our users to tell us they are getting 404's for their service and trying to figure out if they are real ones or this type of issue again

**Comment by howardjohn** [comment]
no route will set the response flag to NR . I think you could customize to expose the response flag in a response header if you want

**Comment by howardjohn** [comment]
Isn't 'where it was trying to get to' part of the request itself?

Users sends "give me example.com", we respond "No route found". What is missing?

**Comment by dhumphries-sainsburys** [comment]
Yes it would be from a users perspective but we aren't the ones making the request just running the platform so we are blind here we just get the istio metrics in prometheus. What we are looking for is primarily a way to alert for the scenario where there should be a route but for whatever reason the gateway either doesn't have it or is failing to route it like we encountered in the linked issue. Currently this just appears as a 404 so would get lost in other legitimate 404 errors and with this flag is only visible to end users anyways (and even then still wouldn't necessarily say whether the route doesn't exist or the route is failing) 

Just to be really clear we need a way to differentiate between user error and gateway error as currently they all get lumped together

**Comment by howardjohn** [comment]
I feel like what you are after is not really possible, regardless of Istio. There is no way to tell if a request "should" find a route. Any service exposed on public internet is going to get a 100s of bogus requests from bots daily.

Where do you want the data returned, if not in the HTTP request

**Comment by dhumphries-sainsburys** [comment]
Well what we are after is only going to be possible in istio seeing as it is all about the gateways of istio. I get where you are coming from and yes really the HTTP request should return the data but the issue I had with the previous suggestion was that as we aren't the ones making the request itself we have no awareness of what was being requested and the metrics endpoint has no idea about the request it seems. So seeing 404 with an unknown destination told us there was a failure but doesn't tell me if it is a "real" 404 or a 404 from gateway itself which is why we have a desire for the gateway 404's where it shouldn't be one to come across as something more in line with what is happening in the grand scheme of things (a gateway failure). 

In regards to there being no way to know if a request "should" find a route we aren't saying the request itself should know but gateway/istio certainly should as it has all the config and knows about it's own state. If it can't trust that it's response is correct (such as what we saw) it would make a lot more sense for the response to reflect that as well not just a "shrug 404 i guess"

**Comment by howardjohn** [comment]
If the gateway responds 404 it has response_flag=NR (no route). If the backend responds 404 it does not.
