### ISSUE TITLE
consider making ingress gateway an optional component in Kiali

### ISSUE THREAD

**Issue by peterj** [istio/istio#51271]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If you install ambient mesh + Kiali, the Istio component status for the ingress gateway shows up with a red exclamation mark that might signify to new users something is wrong. 

![Screenshot 2024-05-23 at 3 25 23 PM](https://github.com/istio/istio/assets/11080940/ade5d8a4-3ec3-402e-9f5b-eacc2b821d8c)

I suggest we make the ingress gateway an optional component in the Kiali configuration (the same as the egress gateway) so it doesn't show up with the red icon next to it. 

![Screenshot 2024-05-28 at 2 07 44 PM](https://github.com/istio/istio/assets/11080940/59d9f2c6-5fff-45fb-9118-7b4cb0d9b842)

### Version

```Text
Istio 1.22.0
```

**Comment by keithmattix** [comment]
Probably better for https://github.com/kiali/kiali?
