### ISSUE TITLE
Allow sniHosts with underscores in virtualservices

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#51285]
**Describe the feature request**
Envoy allows sniHosts to contain underscores, and allows names like: `outbound_.80_._.e2e.foobar.mesh`.

We observe this when using AUTO_PASSTHROUGH mode at Istio Ingress layer.

We are working on migrating to PASSTHROUGH mode, and require creating VirtualServices, with the same value: `outbound_.80_._.e2e.foobar.mesh` to be added under the sniHosts section.

But Istio throws the following error:
```
 domain name "outbound_.80_._.e2e.foobar.mesh" invalid (label "outbound_" invalid)
```

Given envoy allows such domains in the server_name, can Istio allow the same ?

**Describe alternatives you've considered**
Change the SNI value on the client's destinationrule. But if we go this path, then there is a huge cost implication for migrating to PASSTHROUGH.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Is it just sniHosts or also spec.hosts?

If its just sniHosts that seems reasonable

**Comment by nirvanagit** [comment]
Its not allowed in both.

**Comment by howardjohn** [comment]
I know, do you need it in both though or just in `sniHosts`?

**Comment by nirvanagit** [comment]
Yes, need in both, because we don't allow adding `*` to spec.hosts.

**Comment by nirvanagit** [comment]
We can submit a PR once you are okay with this.

**Comment by howardjohn** [comment]
I think it's ok if we can lock it down to only this use case. 

Maybe
* must have only tls route with matching sniHost
* only for gateways, not mesh
* must be the full istio format, not just arbitrary _

wdyt

**Comment by nirvanagit** [comment]
Looks good, didn't get the last point: "must be the full istio format, not just arbitrary _"

**Comment by howardjohn** [comment]
I mean we do not just allow `_` anywhere, it MUST be in the format `outbound_.<port>_.<subset>_.<hostname>` if it has a _

**Comment by nirvanagit** [comment]
That works.

**Comment by nirvanagit** [comment]
Does this mean you are okay with us contributing to add this feature?

**Comment by howardjohn** [comment]
Yep

**Comment by nirvanagit** [comment]
Great, thanks!!

**Comment by howardjohn** [comment]
@nirvanagit lmk when you have something to review and ill take a look

**Comment by nirvanagit** [comment]
Thanks, will update once I have it up.

**Comment by nirvanagit** [comment]
Hey @howardjohn - please review PR: https://github.com/istio/istio/pull/52142.
