### ISSUE TITLE
Inaccurate list of supported groups for TLS

### ISSUE THREAD

**Issue by navaneethrameshan** [istio/istio#51281]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The underlying boringssl version used in envoy no longer supports CECPQ2 for TLS groups, and is upgraded to use X25519Kyber768Draft00. Reflect this usage accurately in Istio by removing CECPQ2, and enabling X25519Kyber768Draft00

### Version

```Text
$ istioctl version 
1.23-dev 

$ kubectl version 
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

**Comment by navaneethrameshan** [comment]
PR to address the issue - https://github.com/istio/istio/pull/51280

**Comment by jaellio** [comment]
BoringSSL PR removing support for CECPQ2 https://github.com/google/boringssl/commit/4ae4fb76c809bfc48a5ab100670395ce404244ce#diff-b4d1fee360b068e022d5ca8c8712cee12257f1666de6c9b91718cf8823c8c3db
