### ISSUE TITLE
CNI Plugin: Inconsistent Kubernetes Args

### ISSUE THREAD

**Issue by danehans** [istio/istio#51292]
[This](https://github.com/istio/istio/blob/master/cni/pkg/plugin/plugin.go#L75-L83) states the fields of `K8sArgs` should be consistent with containerd but it's missing `K8S_POD_UID`.

**Comment by bleggett** [comment]
Yeah this is not part of the CNI spec and is not a spec at all, it's just k8s convention.

**Comment by bleggett** [comment]
(historical context): https://github.com/containernetworking/cni/issues/606
