### ISSUE TITLE
`istioctl`: provide a reliable UX for checking waypoint deployment status

### ISSUE THREAD

**Issue by bleggett** [istio/istio#51294]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
```
k create ns test1
k apply -f samples/httpbin/httpbin.yaml -n test1
istioctl x waypoint apply -n test1 --name httpbin --enroll-namespace
```
-> 

```
waypoint test1/httpbin applied
namespace test1 labeled with "istio.io/use-waypoint: httpbin"
```

k get pods -n test1 ->

```
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE                    NOMINATED NODE   READINESS GATES
httpbin-648f469544-7sfds   1/1     Running   0          9m    10.244.2.2   istio-testing-worker2   <none>           <none>
```

k get gateways -n test1
```
NAME      CLASS            ADDRESS   PROGRAMMED   AGE
httpbin   istio-waypoint             False        35s
```

### Version

```Text
1.22
```

### Additional Information
Refusing to create with a name collision is fine, but the fact that it doesn't tell me that there's a problem and seems happy is probably not.

**Comment by ilrudie** [comment]
controller does write the programmed false status condition

**Comment by ilrudie** [comment]
adding --wait flag the the waypoint apply results in a basic timeout. one point of improvement could be the check gtw status when it times out and print the conditions

**Comment by MorrisLaw** [comment]
@bleggett 

The only way that a warning seems plausible is to mirror what the controller checks for currently, but there is risk of deviation overtime. Then we're in a situation of having to update istioctl to match the gateway deployment(?) controller whenever that changes. That seems less than ideal.

If the controller _does_ write the programmed false status condition as @ilrudie pointed out, do we need to do more work/checking in istioctl?

**Comment by bleggett** [comment]
> If the controller does write the programmed false status condition as @ilrudie pointed out, do we need to do more work/checking in istioctl?

Maybe not, but it's not great UX - I did something reasonable, you let me do it with no negative feedback, and there's (some other) command I need to check to actually know that it didn't take for whatever reason.


(maybe just putting 

```
waypoint test1/httpbin applied
namespace test1 labeled with "istio.io/use-waypoint: httpbin"
monitor status of waypoint deployment with `k get gateways -n test1`
```

in `waypoint apply`'s output would be enough of a breadcrumb)

**Comment by keithmattix** [comment]
Yeah we need to train people to check status on Gateways, and this is part of that industry-wide transition. Adding a monitor should improve the UX though, so +1 to that idea

**Comment by ilrudie** [comment]
@bleggett, would you say that being able to return the failure message IF you use the wait flag is not good enough?

IMO `waypoint apply` is OK to be transactionally similar to kubectl apply. Just because a vwh or cel didn't deny you doesn't mean that it worked like you envisioned (e.g. you got the image wrong in your deployment and your pods never come up).

**Comment by MorrisLaw** [comment]
> > If the controller does write the programmed false status condition as @ilrudie pointed out, do we need to do more work/checking in istioctl?
> 
> Maybe not, but it's not great UX - I did something reasonable, you let me do it with no negative feedback, and there's (some other) command I need to check to actually know that it didn't take for whatever reason, and until/unless I do that the policy I think will be applied is not being applied.
> 
> (maybe just putting
> 
> ```
> waypoint test1/httpbin applied
> namespace test1 labeled with "istio.io/use-waypoint: httpbin"
> monitor status of waypoint deployment with `k get gateways -n test1`
> ```
> 
> in `waypoint apply`'s output would be enough of a breadcrumb)

@howardjohn brought up some good points as to why this might not be as helpful as we'd think:

https://github.com/istio/istio/pull/51394

> Does not seem very helpful for a newer users. It will return istio gateways, not k8s ones, in some cases I think as a first issue. It also doesn't tell users what do look for. It also is hard to monitor because its a one-shot command

**Comment by MorrisLaw** [comment]
@bleggett ^

**Comment by bleggett** [comment]
If I'm saying "it would be good to have a way to check that the waypoint is working and to point people at how they can do this" and we are saying "well, the tool for that isn't useful or reliable for that" I think we still have a UX problem, if I understand it correctly.

What _do_ we expect people to do here? Always use `--wait`? What do they do if they don't?

**Comment by ilrudie** [comment]
I think a waypoint status makes more sense then expecting istioctl to analyze whether or not the waypoint is valid statically. waiting works because we can check on the status that the waypoint controllers write and report it back if it fails or return happily if it succeeds but we don't need to figure out everything the controllers are doing. In that line of thinking having an istioctl command that gets your waypoint status seems more reasonable.

**Comment by bleggett** [comment]
Aight renamed.

"`k get gateways -n test1` doesn't do the job, so we need an `istioctl` command" seems reasonable to me.

**Comment by MorrisLaw** [comment]
@bleggett 

So safe to say should we scrap this [one ](https://github.com/istio/istio/pull/51394) and show status to the user instead?
