### ISSUE TITLE
Running waypoint (istio-proxy container) as non root

### ISSUE THREAD

**Issue by r0bj** [istio/istio#51291]
**Describe the feature request**
Currently, the waypoint (istio-proxy container) is running as root (securityContext.runAsUser=0). It would be beneficial to run it as a non-root user because it cannot operate in restricted namespaces (https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted). This is particularly important because the waypoint is supposed to run in the same namespace as the application workloads, posing a significant limitation.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/51290
