### ISSUE TITLE
Manual setup of Ingress IP(Via e2e env var)

### ISSUE THREAD

**Issue by cesarlbf** [istio/istio#5129]
In order to test in some cloud providers without the kube Load Balancer, there is a need to allow https://github.com/istio/istio/tree/master/tests/e2e to support a variable with the `Ingress` Public IP/Port. 

As exists today for other elements in the test framework. https://github.com/istio/istio/blob/d1eb7e3ff5ac063fd74ddb7971586055d175d6aa/tests/e2e/framework/kubernetes.go#L62

The goal is to have `GetIngress` to consume a variable (`istio-ingress-address`) in some cases, instead of running:
`"kubectl get svc istio-ingress -n %s -o jsonpath='{.status.loadBalancer.ingress[*].ip}' --kubeconfig=%s` that could return no IPs in some scenarios, that a worker node public is available to run the tests. 

https://github.com/istio/istio/blob/d1eb7e3ff5ac063fd74ddb7971586055d175d6aa/tests/util/kube_utils.go#L185

PS: My first issue, if opened it on the wrong place, please let me know. :)

**Comment by linsun** [comment]
can you submit a PR for this small change?

**Comment by cesarlbf** [comment]
Yes,  I am investigating impact of the changes needed to try a PR soon.

**Comment by cesarlbf** [comment]
Waiting the new test framework to see if this is addressed. This Issue can be closed for now
