### ISSUE TITLE
istioctl output is unclear when cluster not installed

### ISSUE THREAD

**Issue by craigbox** [istio/istio#51296]
**Describe the feature request**

istioctl when installed in cluster:

```
$ istioctl version
client version: 1.22.0
control plane version: 1.22.0-beta.1
data plane version: 1.22.0-beta.1 (4 proxies)
```

istioctl when not installed in cluster:

```
$ istioctl version 
no ready Istio pods in "istio-system"
1.22.0
```

I would like this to say something more like

```
$ istioctl version 
client version: 1.22.0
Istio is not installed in this cluster (checked namespace: istio-system)
```

and looking at https://github.com/istio/istio/blob/master/istioctl/pkg/version/version.go#L75 it seems that this is expected to happen.

- [x] User Experience

**Comment by nicole-lihui** [comment]
hello, i tried to impl it  https://github.com/istio/istio/pull/51301   😄
