### ISSUE TITLE
Update documentation and dashboards to account for reporter=Waypoint

### ISSUE THREAD

**Issue by r0bj** [istio/istio#51313]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

According to the documentation on [Istio's website](https://istio.io/latest/docs/reference/config/metrics/#labels), the label "Reporter" should have a value of either "source" or "destination." However, when using a waypoint, the "Reporter" label has the value "waypoint."

Example for metric `istio_requests_total`:
```
istio_requests_total{connection_security_policy="mutual_tls", destination_app="productpage", destination_canonical_revision="v1", destination_canonical_service="productpage", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/istio-workloads-lab/sa/bookinfo-productpage", destination_service="productpage.istio-workloads-lab.svc.cluster.local", destination_service_name="productpage", destination_service_namespace="istio-workloads-lab", destination_version="v1", destination_workload="productpage-v1", destination_workload_namespace="istio-workloads-lab", endpoint="metrics", instance="10.205.64.152:15020", job="istio-waypoint", namespace="istio-workloads-lab", pod="waypoint-565898c798-hjdcp", reporter="waypoint", request_protocol="http", response_code="200", response_flags="-", service="waypoint-metrics", source_app="sleep", source_canonical_revision="latest", source_canonical_service="sleep", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/istio-workloads-lab/sa/sleep", source_version="latest", source_workload="sleep", source_workload_namespace="istio-workloads-lab"}
```

Note label `reporter="waypoint"`.

This is particularly significant because the Istio Grafana dashboard, available on [Istio's website](https://istio.io/latest/docs/ops/integrations/grafana/) (version 1.22.0), uses a variable selector for "Reporter" defined as "source,destination," which results in empty graphs.

Istio and waypoint were deployed as described in the [Istio getting started guide](https://istio.io/latest/docs/ambient/getting-started/).

### Version

```Text
$ istioctl version
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.22.0 (14 proxies)
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

**Comment by howardjohn** [comment]
Thanks. This is valid, but its a documentation + dashboard error. The reporter=waypoint was an intentional decision to distinguish these

**Comment by christian-posta** [comment]
@r0bj any chance you have cycles to dig into fixing this?

**Comment by rorynickolls-skyral** [comment]
I've just run into this issue. I think it just needs the additional `waypoint` option to be added here: 

https://github.com/istio/istio/blob/6fbfc2b7af34b60cf1d1b480a32a0a846f7367d5/manifests/addons/dashboards/istio-workload-dashboard.json#L2933-L2944

and the same for the service dashboard.

**Comment by howardjohn** [comment]
I updated `mesh` one in #52352
