### ISSUE TITLE
Waypoint service account leak after gateway deleted

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#51322]
Istio now depend on gateway to deploy waypoint. But when i remove the gateway, it deleted most of the resources it created, but sa is still there.

**Comment by howardjohn** [comment]
I think this was fixed on recent versions, we had it intentionally for a while due to a k8s GC

**Comment by hzxuzhonghu** [comment]
I did test it in istio 1.22

**Comment by hzxuzhonghu** [comment]
More preciously 1.22.0, which is downloaded from github release

**Comment by hzxuzhonghu** [comment]
I am not yet

**Comment by hzxuzhonghu** [comment]
Why only set ownerref on 1.28+

**Comment by howardjohn** [comment]
bug in k8s that causes the pod to never terminate on shutdown https://github.com/istio/istio/issues/43687#issuecomment-1450253070
