### ISSUE TITLE
ambient mesh timeout on EKS for sample application (bookinfo)

### ISSUE THREAD

**Issue by duxing** [istio/istio#51342]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

From `istio` [slack](https://istio.slack.com/archives/C041EQL1XMY/p1717141356622339) for better tracking / triaging:

I'm setting up `istio` `ambient` on a newly provisioned `EKS` cluster (no north-south traffic yet) and my `curl` calls for [sample application](https://istio.io/latest/docs/examples/bookinfo/) times out after 10s with a 503 response from `ztunnel` logs.

I have a feeling that this the fix is probably a simple one-line thing but I can't figure it out after going through the `trace` / `debug` logs from ztunnel. Can I get some help figuring out why this happens and put in a fix?

Context:
 - `EKS@1.29` + `istio@1.22.0` + `aws-vpc-cni@v1.17.1-eksbuild.1` (EKS addons)
   - everything provisioned with `terraform`
   - instance AMI: `ami-0a5010afd9acfaa26` / `amazon-eks-node-1.29-v20240227`
   - instance class: `r5.4xlarge`
   - `vpc-cni` configuration override: [here](https://github.com/istio/istio/issues/51342#issuecomment-2143043966)
 - all `istio` charts installed with `helm` (`@3.14.4` if matters):
   - `istio-base` + `istiod` + `istio-cni` + `ztunnel`: all at version `1.22.0`
   - for `istiod` and `ztunnel` : I did specify an override value file (equivalent to `helm install <release> istio/<chart> --namespace istio-system --set profile=ambient -f my_override.yaml`, where:
     - `istiod` override: [here](https://github.com/istio/istio/issues/51342#issuecomment-2143037129)
     - `ztunnel` override: [here](https://github.com/istio/istio/issues/51342#issuecomment-2143040267)
 - all charts are deployed successfully and all `istio` pods are healthy.
 - on the same cluster I have some existing workloads (no active traffic) under other namespaces that uses `istio` sidecar injection: I'm under the impression that it won't interfere.

This issue is discovered while I'm adding [istio.io/dataplane-mode](http://istio.io/dataplane-mode) to my workloads but I later found out that the sample application on my cluster has the same issue:
 - followed the exact steps(except using a non-`default` namespace) [here](https://istio.io/latest/docs/ambient/getting-started/#bookinfo) to install the application
 - "Test your bookinfo application" worked well before adding `istio.io/dataplane-mode=ambient` label
 - after adding the label, step 2 [here](https://istio.io/latest/docs/ambient/getting-started/#addtoambient) failed with a 10s timeout + connection termination response

I've also tested:
 - if disable `istio.io/dataplane-mode=ambient` label (set to`none`) for either `source` or `destination` `namespace`, the request goes through fine (200 response without a noticeable delay)
 - turning on `trace`/`debug` log shows empty log activity during that 10s delay. 
 - no `warn` or `error` log was emitted from `ztunnel`
 - I saw a "connection opened" debug log followed by a "no allow policies, allow"  **before** the 10s timeout. 
 - tested setting `kubectl -n istio-system  set env ds/ztunnel ENABLE_ORIG_SRC=false` and the request timeout become indefinite (rather than 10s)
 - I was able to curl the destination service using it's pod IP (`curl <podIp>:80`) from within itself as well as the `ztunnel` instance on its node.

full debug and trace log will can be provided (it's also available in the [slack thread](https://istio.slack.com/archives/C041EQL1XMY/p1717141356622339)) 

`netstat -ntpl` from the destination pod (my own application rather than the sample application) shows it's listening to the 3 ports for `ztunnel`:
```
bash-4.4# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::80                   :::*                    LISTEN      1/./server          
tcp6       0      0 :::15001                :::*                    LISTEN      -                   
tcp6       0      0 :::15006                :::*                    LISTEN      -                   
tcp6       0      0 :::15008                :::*                    LISTEN      -                   
tcp6       0      0 :::50051                :::*                    LISTEN      1/./server    
```

### Version

```Text
istioctl version
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.22.0 (65 proxies)

kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

**Comment by duxing** [comment]
`my_override.yaml` for `istiod`:

```
# helm upgrade --install istiod istio/istiod --version 1.22.0 --namespace istio-system -f this_file.yaml
profile: ambient

pilot:
  autoscaleEnabled: false
  replicaCount: 6
  resources:
    requests:
      cpu: "4"
      memory: 16Gi
    limits:
      cpu: "4"
      memory: 16Gi
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    minDomains: 3
    labelSelector:
      matchLabels:
        operator.istion.io/component: Pilot
    matchLabelKeys:
    - pod-template-hash
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - istiod
            - key: istio
              operator: In
              values:
              - pilot
          topologyKey: kubernetes.io/hostname
    # # node affinity, specific to my set up but should not affect reproducing this issue.
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: pool
    #         operator: In
    #         values:
    #         - critical-addons-worker
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
  podLabels:
    team: cloud-infra
    cluster_addon: "true"
  podAnnotations:
    # for submitting metrics to datadog
    ad.datadoghq.com/discovery.check_names: '["istio"]'
    ad.datadoghq.com/discovery.init_configs: '[{}]'
    ad.datadoghq.com/discovery.instances: |
      [
       {
         "istiod_endpoint": "http://%%host%%:15014/metrics",
         "use_openmetrics": "true"
       }
      ]
  extraContainerArgs:
  - --profile

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
telemetry:
  enabled: true
global:
  # ambient profile specified "distroless": override.
  variant: debug
  istioNamespace: istio-system
  defaultPodDisruptionBudget:
    enabled: true
    minAvailable: 1
  logAsJson: false

  logging:
    level: "default:info"
    
  proxy:
    logLevel: info
    tracer: "none"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

meshConfig:
  enableTracing: false
  accessLogFile: /dev/stdout
  accessLogFormat: "start=%START_TIME% method=\"%REQ(:METHOD)%\" path=\"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\" protocol=\"%PROTOCOL%\" res_code=\"%RESPONSE_CODE%\" res_flags=\"%RESPONSE_FLAGS%\" res_code_details=\"%RESPONSE_CODE_DETAILS%\" conn_termination_details=\"%CONNECTION_TERMINATION_DETAILS%\"
\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" bytes_received=\"%BYTES_RECEIVED%\" bytes_sent=\"%BYTES_SENT%\" duration=\"%DURATION%\" %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\"
\"%REQ(:AUTHORITY)%\" upstream_host=\"%UPSTREAM_HOST%\" upstream_cluster=\"%UPSTREAM_CLUSTER%\" upstream_local_addr=\"%UPSTREAM_LOCAL_ADDRESS%\" downstream_local_addr=\"%DOWNSTREAM_LOCAL_ADDRESS%\" downstream_remote_addr=\"%DOWNSTREAM_REMOTE_ADDRESS%\" req_server_name=\"%REQUESTED_SERVER_NAME%\" route=\"%ROUTE_NAME%\"\n"
  enablePrometheusMerge: false
  defaultConfig:
    holdApplicationUntilProxyStarts: true
```

**Comment by duxing** [comment]
`my_override.yaml` for `ztunnel`:
```
podLabels:
  team: my-team
  cluster_addon: "true"
podAnnotations:
  prometheus.io/scrape: "true"
logLevel: trace
resources:
  requests:
    cpu: 200m
    memory: 512Mi
```

**Comment by duxing** [comment]
maybe related: `vpc-cni` addon configuration (submitted to EKS via `terrarform`)
```
vpc_cni:
  version: "v1.17.1-eksbuild.1"
  # aws eks describe-addon-configuration --region us-east-1 --addon-name vpc-cni --addon-version <version> | jq -r '.configurationSchema' | jq .definitions
  config:
    env:
      ENABLE_PREFIX_DELEGATION: "true"
      WARM_PREFIX_TARGET: "1"
```

**Comment by duxing** [comment]
@bleggett @howardjohn 
thank you in advance!

**Comment by danehans** [comment]
> no warn or error log was emitted from ztunnel

I question whether the traffic is being properly redirected by istio-cni-node. Can you provide the istio-cni-node logs? The ambient getting started steps have been tested on EKS but I don't believe with prefix delegation.

**Comment by duxing** [comment]
@danehans do you mind sharing what makes you question that?

here are the 2 logs (from `ztunnel` debug logs, available from the slack thread in the description, both emitted after the 10s delay):

inbound to the destination pod
> 2024-05-31T07:09:02.849471Z error access  connection complete src.addr=10.231.104.89:36453 src.workload=pod0 src.namespace=ns0 src.identity="spiffe://cluster.local/ns/ns0/sa/default" dst.addr=10.231.99.25:80 dst.hbone_addr=10.231.99.25:80 dst.service=svc1.ns1.svc.cluster.local dst.workload=svc1-7f4487f4d4-lcj9t dst.namespace=ns1 dst.identity="spiffe://cluster.local/ns/ns1/sa/sa1" direction="inbound" bytes_sent=0 bytes_recv=0 duration="10000ms" error="deadline has elapsed"

outbound from the source pod
> 2024-05-31T07:09:02.849493Z debug proxy::connection_manager:inbound{id=449474e43bb608f2552f9c21e663d559 peer=10.231.104.89:36453 peer_id=spiffe://cluster.local/ns/ns0/sa/default} rbac context InboundConnection { ctx: ProxyRbacContext { conn: Connection { src: 10.231.104.89:36453, dst: 10.231.99.25:80, src_identity: Some(Spiffe { trust_domain: "cluster.local", namespace: "ns0", service_account: "default" }), dst_network: "" }, dest_workload_info: Some(WorkloadInfo { name: "svc1-7f4487f4d4-lcj9t", namespace: "ns1", trust_domain: "cluster.local", service_account: "sa1" }) }, dest_service: Some("svc1.ns1.svc.cluster.local") } auto-dropped 

prior to the 10s delay, there are several debug logs from the destination `ztunnel`s related to opening and accepting connections. in this case, both source and destination are placed on the same node so both destination and source `ztunnel` map to the same instance.

**Comment by danehans** [comment]
> @danehans do you mind sharing what makes you question that?

The following comment made me question whether the traffic is being redirected by the istio cni node:

> no warn or error log was emitted from ztunnel

Are you able to test without prefix delegation?

**Comment by howardjohn** [comment]
> no warn or error log was emitted from ztunnel

There is a log about the traffic, though -- just no errors beyond "it started the connection"

**Comment by duxing** [comment]
@danehans I see why you ask.

> no warn or error log was emitted from ztunnel

I meant that there were no observed errors from `ztunnel`. I did see an "info" log from both source `ztunnel` and destination `ztunnel`, and that's why I think the issue is from destination `ztunnel` connecting to destination pod.

**Comment by danielloader** [comment]
Might be unrelated but I've seen similar behaviour without as much digging as you've done, albeit with once and done postgres TCP connections rather than HTTP level ones - https://istio.slack.com/archives/C041EQL1XMY/p1718969144142009

**Comment by duxing** [comment]
It's been 4months since this issue was submitted with detailed repro

It's disappointing that fundamental networking issues like this aren't getting any attention from the maintainers. 
reasons like this force me to move away from using `istio` to an alternative as my enterprise solution.

**Comment by bleggett** [comment]
> It's been 4months since this issue was submitted with detailed repro

Yes. Understand we haven't been able to reproduce it and have users using ambient on EKS with vpc-cni that do not have this issue, indicating it's something unique to your setup.

> It's disappointing that fundamental networking issues like this aren't getting any attention from the maintainers. I liked many things about `istio` but reasons like this force me to move away from using `istio` to an alternative as my enterprise solution.

Are you still able to reproduce this with the latest 1.23.X release?

**Comment by howardjohn** [comment]
Do you have `POD_SECURITY_GROUP_ENFORCING_MODE: strict`? on the VPC

**Comment by duxing** [comment]
I absolutely agree that it's much more likely to be on my end (e.g. a networking configuration change in my stack) than a bug in `ztunnel` or `istio`

however, the same stack (same instances of EKS clusters, same environment, same addons, and same values) had no problem with `istio` sidecar (various versions) or `linkerd2` (various versions). As shared in the description, the set up isn't complex or niche either. I don't think my stack is solely responsible for this issue.

I don't know if you attempted reproducing this issue using the identical setup as I described (if not, I suggest give it a try as the last attempt), but I totally understand there's very little you can do if you can't reproduce the issue. 

this service mesh set up is for building an enterprise solution (not personal project) and business requirements made it difficult to afford spending more time (after spending weeks). I have moved away from `istio` to `linkerd` to meet the business requirements without running into any resource or networking issues I reported to `istio`.

I don't have business needs to look into `istio` further at the moment. if I get more free time or requirements changes, I'll revisit `istio` `ambient`. At that point I can revisit this topic and collaborate to help figure this out

**Comment by achaikaJH** [comment]
I actually have very similar configuration and the same issue running on AKS 1.30.6

`istioctl version
client version: 1.24.2
control plane version: 1.24.2
data plane version: 1.24.2 (27 proxies)`


istiod

`values:
    cni:
      enabled: true
    global:
      hub: caaksprodcacacr.azurecr.io/istio
      proxy:
        logLevel: error
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
      tag: 1.24.2
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
          ISTIO_META_DNS_CAPTURE: "true"
          ISTIO_META_ENABLE_HBONE: "true"
        tracing:
          sampling: 100
          zipkin:
            address: jaeger-collector.observability.svc.cluster.local:9411
      enableTracing: true
      extensionProviders:
      - envoyExtAuthzHttp:
          headersToDownstreamOnDeny:
          - set-cookie
          headersToUpstreamOnAllow:
          - authorization
          includeRequestHeadersInCheck:
          - cookie
          port: "80"
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        name: oauth2-proxy
      h2UpgradePolicy: DO_NOT_UPGRADE
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 2
      cni:
        enabled: true
      env:
        AMBIENT_ENABLE_STATUS: true
        ENABLE_DEBUG_ON_HTTP: "true"
        ENABLE_INGRESS_WAYPOINT_ROUTING: true
        ENABLE_LEGACY_FSGROUP_INJECTION: "false"
        PILOT_ENABLE_AMBIENT: "true"
        PILOT_ENABLE_AMBIENT_WAYPOINTS: true
      resources:
        limits:
          cpu: 1000m
          memory: 2048Mi
        requests:
          cpu: 500m
          memory: 1768Mi
      seccompProfile:
        type: RuntimeDefault
      spec:
        containers:
        - args:
          - discovery
          - --grpcAddr=`
I have ingress gateway and virtual service deployed to the namespace along with the waypoint proxy.
I can see the call go all the way from ingress to ztunnel to waypoint and the destination seems to be correct, yet it ends in timeout.

ztunnel logs

`2025-01-07T16:04:38.727398Z    error    access    connection complete    src.addr=172.29.1.140:55496 src.workload="ns-istio-test05-gw-85b8cf4c5c-ctwbw" src.namespace="ns-istio-test05" src.identity="spiffe://cluster.local/ns/ns-istio-test05/sa/ns-istio-test05-gw" dst.addr=172.29.1.170:15008 dst.hbone_addr=172.29.1.170:9898 dst.service="podinfo.ns-istio-test05.svc.cluster.local" dst.workload="podinfo-blue-5d64794875-mb7rz" dst.namespace="ns-istio-test05" dst.identity="spiffe://cluster.local/ns/ns-istio-test05/sa/default" direction="inbound" bytes_sent=0 bytes_recv=0 duration="10001ms" error="connection failed: deadline has elapsed" 2025-01-07T16:04:52.172925Z    error    access    connection complete    src.addr=172.29.1.141:36640 src.workload="ns-istio-test05-gw-85b8cf4c5c-t55db" src.namespace="ns-istio-test05" src.identity="spiffe://cluster.local/ns/ns-istio-test05/sa/ns-istio-test05-gw" dst.addr=172.29.1.170:15008 dst.hbone_addr=172.29.1.170`

waypoint logs

`[2025-01-07T16:28:43.785Z] "GET / HTTP/1.1" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 0 95 10004 - "10.34.98.70" "curl/8.7.1" "ba65c257-504b-92bf-afd2-3e219f53f564" "istio-test05.us.aks.com" "envoy://connect_originate/172.29.1.171:9898" inbound-vip|9898|http|podinfo.ns-istio-test05.svc.cluster.local envoy://internal_client_address/ 172.29.146.239:9898 10.34.98.70:0 - default
[2025-01-07T16:36:53.800Z] "- - -" 0 UF,URX - - "-" 0 0 10001 - "-" "-" "-" "-" "172.29.1.171:15008" connect_originate - 172.29.1.171:9898 envoy://internal_client_address/ - -`
