### ISSUE TITLE
WatchedResource data race in TestSyncz

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51340]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/51316/unit-tests-arm64_istio/1796565465967890432

**Comment by howardjohn** [comment]
`git bisect`ing

**Comment by howardjohn** [comment]
Bisect having trouble, I think its rare enough that its hard to fine. May need to increase the time and run it overnight or something

**Comment by howardjohn** [comment]
Originally ran with 
good=5b4b010e4e
bad=f21041a1bf

**Comment by hzxuzhonghu** [comment]
We should lock when access `wr.NonceSent`
