### ISSUE TITLE
go get istio.io/istio => module declares its path as: dario.cat/mergo but was required as: github.com/imdario/mergo

### ISSUE THREAD

**Issue by alunduil-tm** [istio/istio#51369]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I attempt to do `go get istio.io/istio` I'm met with the following error:

```
go: istio.io/istio@upgrade (v0.0.0-20240603082905-a1d55815cbf7) requires github.com/imdario/mergo@v1.0.0: parsing go.mod:
        module declares its path as: dario.cat/mergo
                but was required as: github.com/imdario/mergo
```

This smells like an issue in istio.io/istio/go.mod referring to github.com/imdario/mergo instead of the new name dario.cat/mergo, but I'm not sure and unfamiliar with go dependencies.

I'd love to get some guidance on how to circumvent this or if it could be made explicit in some documentation if I'm using a library that shouldn't be.

### Version

```Text
v0.0.0-20240603082905-a1d55815cbf7
```

**Comment by howardjohn** [comment]
Istio is not really intended to be imported like this. If you do, you need to copy the `replace` directives in go.mod since Go does not pull those in from dependencies.

https://github.com/kubernetes/kubernetes/issues/107499 is longer term fix.

I recommend not importing istio/istio though, we have no compatibility guarantees

**Comment by alunduil-tm** [comment]
@howardjohn thanks for the confirmation.  I'll check internally if we still want to move this direction and if we're accepting of those caveats.  

Where would a good place for a note about istio.io/istio not being a go library so others can find this as well?

**Comment by howardjohn** [comment]
Honestly, not very sure. Where would you have looked, as someone that was interested in consuming it :slightly_smiling_face: ?

**Comment by alunduil-tm** [comment]
@howardjohn my ideal location would be a combination of the following:

- Clear error from go get indicating this library isn't intended to be used via go get
- Notice on [the library documentation](https://pkg.go.dev/istio.io/istio) that this shouldn't be used as a library
- Notice on the README about not using import istio.io/istio/...

If that makes sense I can put together a pull request (or more if needed) that adds that language to make this more clear and hopefully others looking to reuse this will prefer reimplementing some of these checks or using istioctl exclusively.
