### ISSUE TITLE
json log with sort_properties prints decimals for all numbers

### ISSUE THREAD

**Issue by larhauga** [istio/istio#51363]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The json logs when using Envoy FileAccessLog are serialized as floating numbers with decimals rather than integers.
An example is response codes which are logged as "HTTP" 200.0.
We see this when json_format_options.sort_properties: true is set (introduced in https://github.com/envoyproxy/envoy/commit/fc33e5d94f6919f6748e468b75df607bdd667e24 and enabled in istio in https://github.com/istio/istio/pull/48882).  

```json
{"bytes_received":0.0,"bytes_sent":11576.0,"duration":6.0,"method":"GET","response_code":200.0,"upstream_service_time":"6"}...
```

This creates inconsistent data and HTTP Response Codes should only be integers.

Ref https://github.com/envoyproxy/envoy/issues/34420.

Should sorting of the json be disabled until it is fixed in envoy?
Are there any workarounds to disable this?

### Version

```Text
>= istio 1.22.0
```

### Additional Information

https://github.com/envoyproxy/envoy/issues/34420
https://github.com/istio/istio/pull/48882

**Comment by zirain** [comment]
fxied by https://github.com/istio/istio/pull/51535
