### ISSUE TITLE
as per security requirement we need to disable automount service account token, can we disable this in istio?

### ISSUE THREAD

**Issue by rsaini6261** [istio/istio#51391]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
as per security requirement we need to disable automount service account token, can we disable this in istio? #51391

### Version

```Text
1.20.2 istio version
```

**Comment by howardjohn** [comment]
In which component? istiod needs it to communicate to the API server.

In the past, there has been similar discussions - "A security scanner told me to disable it, so I must disable it". The security scanner is wrong; you should disable it **where its not needed**, but its is needed in any component communicating with the api-server which Istiod does/requires
