### ISSUE TITLE
istio envoy access log should specify if (m)TLS is used or not

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#5139]
current log entry look like (for ingress for instance)

[2018-04-23T23:24:50.950Z] "GET /d/1/ HTTP/1.1" 503 UF 0 57 4 - "10.150.0.5" "curl/7.54.0" "bd681cb9-fa08-99af-a816-66bf90e6475d" "35.188.253.194" "10.36.1.9:3000"

This should say the inbound and outbound Plain/TLS/mTLS; it would greatly help ability to debug if the failure is mtls related or not - also should have an error log when it is mtls failure (https://github.com/envoyproxy/envoy/issues/1472)

**Comment by rshriram** [comment]
Please file this in Envoy. There is no way to detect if connection came via tls or plain text. Once again, please stop assigning labels unless you are the lead of the working group for that label.

**Comment by ldemailly** [comment]
cc @andraxylia such a pleasure to help with labels and issues.

note that afaik the access log of envoy is customizable

**Comment by andraxylia** [comment]
It's preferable if the person opening an issue categorizes it with an area and labels it to the best of his/her knowledge.
