### ISSUE TITLE
After adding Jaegar add on , error stating service not found

### ISSUE THREAD

**Issue by OteemoSanjay** [istio/istio#51420]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi

We on istio 1.22 and have kiali enabled.   One of the team wanted Jaeger enabled.
After running the jaeger YAML from the samples/addons folder.

If we click the Jaeger link from Istio , we get the below error

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no service port 16686 found for service \"tracing\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

please advise

### Version

```Text
❯ istioctl version
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.22.0 (4 proxies)
```

### Additional Information

Target cluster context: sandbox1

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-06-05 10:58:44.658679 -0600 CST

Cluster endpoint: https://cluster-console.sand.lib.harvard.edu/k8s/clusters/local
CLI version:
version.BuildInfo{Version:"1.22.0", GitRevision:"Homebrew", GolangVersion:"go1.22.3", BuildStatus:"Homebrew", GitTag:"1.22.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.22.0", GitRevision:"aaf597fbfae607adf4bb4e77538a7ea98995328a", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.22.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.22.0}

Fetching logs for the following containers:

argocd/argo-cd-argocd-applicationset-controller/argo-cd-argocd-applicationset-controller-76cd598988-mzcl9/applicationset-controller
argocd/argo-cd-argocd-dex-server/argo-cd-argocd-dex-server-999f566b6-dkkbg/dex-server
argocd/argo-cd-argocd-notifications-controller/argo-cd-argocd-notifications-controller-5f479c7f46-vh2gw/notifications-controller
argocd/argo-cd-argocd-redis/argo-cd-argocd-redis-584b9fcd7b-n4wzp/redis
argocd/argo-cd-argocd-repo-server/argo-cd-argocd-repo-server-77b9f8d7d6-fxjf4/repo-server
argocd/argo-cd-argocd-server/argo-cd-argocd-server-864689d7ff-wqpgg/server
cattle-fleet-local-system/fleet-agent/fleet-agent-7d884d744d-5fw7t/fleet-agent
cattle-fleet-system/fleet-controller/fleet-controller-84fcc77b65-cdgb6/fleet-controller
cattle-fleet-system/gitjob/gitjob-85b5fc4d86-qvhgg/gitjob
cattle-monitoring-system/pushprox-kube-controller-manager-client/pushprox-kube-controller-manager-client-rqbzv/pushprox-client
cattle-monitoring-system/pushprox-kube-controller-manager-proxy/pushprox-kube-controller-manager-proxy-6f5db6f869-cjbg9/pushprox-proxy
cattle-monitoring-system/pushprox-kube-etcd-client/pushprox-kube-etcd-client-8zcg4/pushprox-client
cattle-monitoring-system/pushprox-kube-etcd-proxy/pushprox-kube-etcd-proxy-bdf7fbc7-cw9j2/pushprox-proxy
cattle-monitoring-system/pushprox-kube-proxy-client/pushprox-kube-proxy-client-8lmdd/pushprox-client
cattle-monitoring-system/pushprox-kube-proxy-client/pushprox-kube-proxy-client-gfbvv/pushprox-client
cattle-monitoring-system/pushprox-kube-proxy-client/pushprox-kube-proxy-client-ndxht/pushprox-client
cattle-monitoring-system/pushprox-kube-proxy-proxy/pushprox-kube-proxy-proxy-6bd88b8849-zhbxg/pushprox-proxy
cattle-monitoring-system/pushprox-kube-scheduler-client/pushprox-kube-scheduler-client-9cm94/pushprox-client
cattle-monitoring-system/pushprox-kube-scheduler-proxy/pushprox-kube-scheduler-proxy-77df8c4b7-gfhsx/pushprox-proxy
cattle-monitoring-system/rancher-monitoring-grafana/rancher-monitoring-grafana-64d7d7c8b4-r8z42/grafana
cattle-monitoring-system/rancher-monitoring-grafana/rancher-monitoring-grafana-64d7d7c8b4-r8z42/grafana-proxy
cattle-monitoring-system/rancher-monitoring-grafana/rancher-monitoring-grafana-64d7d7c8b4-r8z42/grafana-sc-dashboard
cattle-monitoring-system/rancher-monitoring-grafana/rancher-monitoring-grafana-64d7d7c8b4-r8z42/grafana-sc-datasources
cattle-monitoring-system/rancher-monitoring-kube-state-metrics/rancher-monitoring-kube-state-metrics-7889dccd84-prklv/kube-state-metrics
cattle-monitoring-system/rancher-monitoring-operator/rancher-monitoring-operator-77fddfc4b8-wxqxt/rancher-monitoring
cattle-monitoring-system/rancher-monitoring-prometheus-adapter/rancher-monitoring-prometheus-adapter-55dc9ccd5d-k5nfn/prometheus-adapter
cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter/rancher-monitoring-prometheus-node-exporter-4xggk/node-exporter
cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter/rancher-monitoring-prometheus-node-exporter-dlr8j/node-exporter
cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter/rancher-monitoring-prometheus-node-exporter-lcjv2/node-exporter
cattle-provisioning-capi-system/capi-controller-manager/capi-controller-manager-79ddf9b9d8-db6w4/manager
cattle-resources-system/rancher-backup/rancher-backup-6f6b77fd56-r55lc/rancher-backup
cattle-system/rancher-webhook/rancher-webhook-7cb964c7f6-6pg66/rancher-webhook
cattle-system/rancher/rancher-b7f4b55cd-875bk/rancher
cert-manager/cert-manager-cainjector/cert-manager-cainjector-6dd494d696-rr9l9/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-7bf48d45fd-fvgkv/cert-manager-webhook
cert-manager/cert-manager/cert-manager-5bf6cdbb96-85s7l/cert-manager-controller
external-secrets/external-secrets-cert-controller/external-secrets-cert-controller-5685785964-cf6wv/cert-controller
external-secrets/external-secrets-webhook/external-secrets-webhook-7f5fb896f5-4vrgr/webhook
external-secrets/external-secrets/external-secrets-98d86764-x8pcz/external-secrets
istio-system/istio-apiprivate-ingressgateway/istio-apiprivate-ingressgateway-788fc57dc-4w5hc/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6c7bf84654-x2xqt/istio-proxy
istio-system/istio-private-ingressgateway/istio-private-ingressgateway-588b46b75-5nszr/istio-proxy
istio-system/istio-server-ingressgateway/istio-server-ingressgateway-8f7cdc45f-zxbvv/istio-proxy
istio-system/istiod/istiod-698c8846c8-8s9bs/discovery
istio-system/jaeger/jaeger-774db7958c-r6jv7/jaeger
istio-system/kiali/kiali-66d8cdcf5-rtrfw/kiali
istio-system/prometheus/prometheus-5d5d6d6fc-n79kz/prometheus-server
istio-system/prometheus/prometheus-5d5d6d6fc-n79kz/prometheus-server-configmap-reload
observability/jaegertracing-agent/jaegertracing-agent-768vw/jaegertracing-agent
observability/jaegertracing-agent/jaegertracing-agent-7bvvc/jaegertracing-agent
observability/jaegertracing-agent/jaegertracing-agent-r95jn/jaegertracing-agent
observability/jaegertracing-collector/jaegertracing-collector-f6b595f88-8bvmv/jaegertracing-collector
observability/jaegertracing-query/jaegertracing-query-7ff7b5b5f7-s8p8p/jaegertracing-agent-sidecar
observability/jaegertracing-query/jaegertracing-query-7ff7b5b5f7-s8p8p/jaegertracing-query

Fetching Istio control plane information from cluster.

**Comment by OteemoSanjay** [comment]
The service portions is in the 'jaeger.yaml' file.
But there is nothing defined in the POD for this port

apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger

**Comment by zirain** [comment]
I think you should ask help in [kiali/kiali](https://github.com/kiali/kiali)?
