### ISSUE TITLE
How to get long lived token for istiod service account

### ISSUE THREAD

**Issue by CJsPod** [istio/istio#51431]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Is there a way in istio helm chart to create service tokens for istiod service account we recently upgraded to istio 1.22 and istiod sa doesnt have any tokens associated.

### Version

```Text
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.21.1 (121 proxies), 1.22.1 (1 proxies)

K8s - v1.28.6

Helm - v3.14
```

### Additional Information

Error in logs

"scope":"security","msg":"Failed to authenticate client from xxxxxx: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster \"Kubernetes\": Unauthorized"}

**Comment by howardjohn** [comment]
To answer your first question: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount.

I don't see how that relates to the "Error in logs" though, so maybe you have a different problem I did not understand?

**Comment by CJsPod** [comment]
Thank You for quick response, Yes, we had a different issue and it was not related to istiod sa.
