### ISSUE TITLE
Ability to disable proxy CPU limits

### ISSUE THREAD

**Issue by cathal-c** [istio/istio#51456]
**Describe the feature request**

A simple ask - I would like to be able to disable proxy CPU limits entirely. This requirement has come up a number of times between GitHub issues, the Istio discussion forum and Istio's Slack, yet strangely it does not appear to be possible today, via annotation or otherwise.

Setting CPU limits is generally understood to be counterproductive, and even where they make sense, cluster admins should have the power to disable them when needed, as they deem fit.

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
will [Custom templates](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#custom-templates-experimental) help?

**Comment by cathal-c** [comment]
@zirain that may work, thank you 👍 

@howardjohn Thank you for that insight. But isn't the number of Envoy worker threads locked to two (`--concurrency=2`) by default when bootstrapped by Istio?

**Comment by howardjohn** [comment]
No - it by default uses the CPU limit, which is also 2. You can explicitly set it to t 2 still though, with meshConfig.defaultConfig.concurrency=2

**Comment by cathal-c** [comment]
Aha... Following you now. 

You're right. I always thought it was locked to 2, but turns out that's indirectly coming from our default cpu limits of `2000m` as you suggested. 

In that case, I am inclined to _actually_ lock it to 2 via the `concurrency` param, and work towards removing limits. We see too much throttling in high throughput sidecars, but I do not want any more than 2 threads per the reasons you outlined.
