### ISSUE TITLE
pilot e2e test TestRoutes/v1alpha1/a->c[v1=100]_append_headers is flaky in CircleCI

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#5146]
The pilot e2e test is flaky in CircleCI. The test failure is observed in two PRs.
TestRoutes/v1alpha1/a->c[v1=100]_append_headers.
TestRoutes/v1alpha1/a->c[v1=100]_CORS_policy is also flaky, not sure whether the root cause is the same.

**Comment by JimmyCYJ** [comment]
cc @costinm

**Comment by ostromart** [comment]
This test is not flaky anymore, looking at the presubmits for the last few days.
