### ISSUE TITLE
As per security, we need to configure readiness-probe in Istio-Operator deployment but readiness probe is getting fail

### ISSUE THREAD

**Issue by rsaini6261** [istio/istio#51478]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

As per security, we need to configure readiness-probe in Istio-Operator deployment but readiness probe is getting fail, Please suggest readiness config for istio-operator

### Version

```Text
1.20.2
```

**Comment by howardjohn** [comment]
The IstioOperator has now been removed https://istio.io/latest/blog/2024/in-cluster-operator-deprecation-announcement/
