### ISSUE TITLE
istioctl analyze doesnt report missing certs

### ISSUE THREAD

**Issue by OteemoSanjay** [istio/istio#51479]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

hi

We have installed the latest istio, which is 1.22.1
However after installing we notice that the istioctl analyze -n istio-system does not report missing certs.

Previously on 1.20.x. it used to report that as below:
❯ istioctl analyze -n istio-system
Error [IST0101] (Gateway istio-system/api-private-gateway) Referenced credentialName not found: "apiprivate-cert"
Warning [IST0162] (Gateway istio-system/public-gateway) The gateway is listening on a target port (port 80) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.

### Version

```Text
❯ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (4 proxies)
```

### Additional Information

hi

Even if you run the istioctl against the NS.  Where there are no secrets/ certs.  It still report no issues

❯ istioctl analyze -n istio-system

✔ No validation issues found when analyzing namespace: istio-system.

Event hough there only the default certs.

❯ kubectl get secrets
NAME                                 TYPE                 DATA   AGE
istio-ca-secret                      istio.io/ca-root     5      9m
sh.helm.release.v1.istiod.v1         helm.sh/release.v1   1      9m5s
sh.helm.release.v1.kiali-server.v1   helm.sh/release.v1   1      8m44s

And I have multiple GW with their own certs

❯ kubectl get pods
NAME                                               READY   STATUS    RESTARTS   AGE
istio-apiprivate-ingressgateway-74cb6d594b-ntdcq   1/1     Running   0          8m53s
istio-ingressgateway-6b9886bd9f-kc6q9              1/1     Running   0          8m53s
istio-private-ingressgateway-7497654586-5lxgv      1/1     Running   0          8m52s
istio-server-ingressgateway-dfc6cc97d-rdtg5        0/1     Pending   0          8m52s

**Comment by leosarra** [comment]
I tried to reproduce locally with istioctl from 1.22.1 but I can still see the error being raised

```
leosarra@est-workstation:~/Desktop/istio$ go run istioctl/cmd/istioctl/main.go analyze -n istio-system
Error [IST0101] (Gateway istio-system/mygateway) Referenced credentialName not found: "httpbin-credential"
Warning [IST0162] (Gateway istio-system/mygateway) The gateway is listening on a target port (port 443) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.
Error: Analyzers found issues when analyzing namespace: istio-system.
See https://istio.io/v1.22/docs/reference/config/analysis for more information about causes and resolutions.
```

Can you provide an example of CR that was triggering the error in 1.20.x but does not do anymore?

**Comment by leosarra** [comment]
yes but could you provide me with a simplified (removing all the confidential information) of your api-private-gateway Gateway resource so that I can try it out on my machine.
My GW with non-existing credential is able to triggering the error just fine, perhaps there is something more in your resource that leads to a different behavior.

**Comment by OteemoSanjay** [comment]
hola Leonardo 

I rebuilt one of our environments with 1.22.1 and the analyse works as expected.
Sorry for the confusion..
```

❯ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (3 proxies)
(⎈|sandbox1:istio-system)

~ via  v22.2.0 on ☁️  (us-east-1) on ☁️   took 2s
❯ istioctl analyze -n istio-system
Error [IST0101] (Gateway istio-system/private-gateway) Referenced credentialName not found: "private-cert"
Error [IST0101] (Gateway istio-system/public-gateway) Referenced credentialName not found: "public-cert"
Error [IST0101] (Gateway istio-system/server-gateway) Referenced credentialName not found: "server-cert"
Warning [IST0162] (Gateway istio-system/public-gateway) The gateway is listening on a target port (port 80) that is not defined in the Service associated with its workload instances (Pod selector istio=ingressgateway). If you need to access the gateway port through the gateway Service, it will not be available.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Error: Analyzers found issues when analyzing namespace: istio-system.

thanks for your time

**Comment by leosarra** [comment]
You are welcome. Let me know if some weird behavior shows up again and I will take a look :)
