### ISSUE TITLE
CNI plugin labels lost

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51494]
We log `log.WithLabels("pod", podNamespace+"/"+podName)`. But in the kubectl logs we get:

```
2024-06-10T14:57:14.106192Z     info    cni-plugin      excluded due to inject-disabled annotation

```

No labels there

cc @bleggett

**Comment by bleggett** [comment]
There's some legacy weirdness for the sidecar labels where we check for either the annotation or label, but only log the label.

May also be a simple logging snafu.

**Comment by howardjohn** [comment]
I am just talking about the log missing info, not related to pod - there should be `pod=name/ns` in the log line
