### ISSUE TITLE
Install: Expose Waypoint Resources

### ISSUE THREAD

**Issue by danehans** [istio/istio#51496]
**Describe the feature request**

Provide the ability to customize waypoint deployment resources at install through Helm values. This approach provides consistency with other components that expose configurable resources.

**Describe alternatives you've considered**
1. Using gatewayclass or gateway annotations to configure waypoint resources, e.g. `networking.istio.io/waypoint-cpu-requests: 500m`. This approach provides consistency in customizing an ingress gateway but will be superseded in the future by the following option.
2. With https://github.com/kubernetes-sigs/gateway-api/pull/2924, gateway `parametersRef` can manage waypoint resources. However, this requires considerable API changes to implement. 

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Waypoint resources are currently defined as:
```
resources:
  limits:
    cpu: "2"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
```

xref discussion: https://github.com/istio/istio/discussions/51252

**Comment by keithmattix** [comment]
IMO we should solve this one time for all Kubernetes gateways and not special class anything for waypoints

**Comment by danehans** [comment]
@keithmattix k8s gateways already support configurable resources ([xref](https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml#L86-L87)). I'm proposing that we take the same approach for waypoints.

**Comment by keithmattix** [comment]
I believe that's the regular Istio gateway; the k8s gateway one isn't a helm template: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/kube-gateway.yaml

**Comment by danehans** [comment]
@keithmattix thanks for the heads-up. The k8s gateway that you reference exposes resource config too:
```
        resources:
          {{- toYaml .Values.global.proxy.resources | nindent 10 }}
        {{- end }}
```

The current hardcoded waypoint resources differ from `.Values.global.proxy.resources`. Should the default waypoint resource values be updated to be `Values.global.proxy.resources` or should separate values, e.g. `Values.global.waypoint.resources` be used to manage waypoint resources? Since a waypoint is another instance of an Envoy proxy, I lean towards the former.

cc: @howardjohn

**Comment by howardjohn** [comment]
I would set them to `.Values.global.proxy.resources`

**Comment by zirain** [comment]
> I would set them to `.Values.global.proxy.resources`

Correct me if I'm wrong, it's not recommend to use Sidecar and Ambient together, but it's our goal.
In a mixed cluster(with both Sidecar and Waypoint), the default resource should be different, is it better to use a seperate resources from the begining (e.g. `Values.global.waypoint.resources`)?

**Comment by hzxuzhonghu** [comment]
I would suggest we introduce a annotation on gateway, waypoint can be deployed per namespace/service/pod, which is quite different.

**Comment by hzxuzhonghu** [comment]
What do you mean @zirain

**Comment by zirain** [comment]
> What do you mean @zirain

support both helm(.values.global.waypoint/proxy.resources) and annotaions(in `Gateway.spec.infrastructure`)

**Comment by hzxuzhonghu** [comment]
I am not sure waypoint can be deployed by helm now

**Comment by bleggett** [comment]
sharing one resource var path makes sense to me for now. if we encounter a need for anything more granular, that's where

> With https://github.com/kubernetes-sigs/gateway-api/pull/2924, gateway parametersRef can manage waypoint resources. However, this requires considerable API changes to implement.

comes in.

**Comment by louiscryan** [comment]
I get we may need to offer arbitrary control over resources but I don't think that's the ideal UX for most users.

What % of users need arbitrary control vs something like a t-shirt size option ?

**Comment by hzxuzhonghu** [comment]
This is a global default value, make sense to me. For fine-grained control ,we can infer  that from gateway or gatewayclass. 

One confusion maybe if we do support both `.Values.global.proxy.resources` and gatewayclass, which one takes priority
