### ISSUE TITLE
Test and support manual EndpointSlices in ambient

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51539]
Today I think we only look for Pod and WE for endpoints. Users may put arbitrary things in EndpointSlice. We should support those.

This needs some thinking through how they translate to WDS

**Comment by jsievenpiper** [comment]
Looks like this has a PR up already which is awesome -- adding some additional context for others who might be looking to adopt ambient:

---

I _think_ this is what's happening today preventing me from adopting Ambient for my database cluster.

I have a Postgres cluster deployed via [Cruncy PGO](https://github.com/CrunchyData/postgres-operator) that uses a Service with no selector to identify the "primary" instance, and Patroni then [manually creates and manages the corresponding Endpoints](https://patroni.readthedocs.io/en/latest/kubernetes.html#use-endpoints) to point that service toward the correct pod IP.
