### ISSUE TITLE
Use of named templates in istiod helm chart precludes use as dependent sub-chart

### ISSUE THREAD

**Issue by brydoncheyney** [istio/istio#51548]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Up to this point, the process to upgrade our organisation's istiod has involved [multiple helm charts](https://istio.io/latest/docs/setup/upgrade/helm/), with a number of deployment steps involved to validate a canary release, before rolling out a new control plane and removing the old. We encountered a few issues with this approach with the management of version tags and ownership of resources, namely the `MutatingWebhookConfiguration istio-revision-tag-stable` resource. In an attempt to simplify the coordination of upgrades, a single chart was created, with sub-charts to represent the blue/green istiod deployments. However, I observed some strange rendering of `MutatingWebhookConfiguration` resources when upgrading from 1.18.7 to 1.20.6, which was producing an invalid `reinvocationPolicy: ""` for the 1.18.7 templates.

The istio charts use [named templates](https://helm.sh/docs/chart_template_guide/named_templates/) -

> An important detail to keep in mind when naming templates: template names are global. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.

The 1.18.7 `MutatingWebhookConfiguration` template is using a [named template](https://github.com/istio/istio/blob/1.18.7/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml#L8), "core", with _no_ `revocationPolicy`.

The 1.20.7 `MutatingWebhookConfiguration` template is using a [named template](https://github.com/istio/istio/blob/1.20.7/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml#L9), "core", _with_ `revocationPolicy`, introduced in [1.19.0-beta.0](https://github.com/istio/istio/blob/1.19.0-beta.0/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml).

This second 1.20.7 definition of the named template is being used by _both_ charts and, given there is [no value defined](https://github.com/istio/istio/blob/1.18.7/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml#L3-L7) for `revocationPolicy` in the helm values for 1.18,7, this is being set as `revocationPolicy: ""`, which is invalid.

The helm recommendation here is to _prefix each defined template_

> One popular naming convention is to prefix each defined template with the name of the chart: {{ define "mychart.labels" }}. By using the specific chart name as a prefix we can avoid any conflicts that may arise due to two different charts that implement templates of the same name.
>
> This behavior also applies to different versions of a chart. If you have mychart version 1.0.0 that defines a template one way, and a mychart version 2.0.0 that modifies the existing named template, it will use the one that was loaded last. You can work around this issue by also adding a version in the name of the chart: `{{ define "mychart.v1.labels" }}` and `{{ define "mychart.v2.labels" }}`.

Versioning the named templates on changes would ensure this clash does not occur on changes to these named templates. I've validated that this is the case, by unpacking the `istio-1.20.7.tgz` chart archive and renaming the `core` named template to `v1.core` (as well as any include references), which would then render both sets of `MutatingWebhookConfiguration` resources as expected. Further, the chart could also prefix the named templates with the name of the chart, resulting in named templates like `istiod.v1.core`.

### Version

```Text
; ./istioctl version
client version: 1.18.7
control plane version: 1.18.7
data plane version: 1.18.7 (411 proxies)

; kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
WARNING: version difference between client (1.30) and server (1.28) exceeds the supported minor version skew of +/-1

; helm version --short
v3.15.1+ge211f2a
```

**Comment by howardjohn** [comment]
funny, this just came up: https://github.com/istio/istio/pull/51517#issuecomment-2164028592. I think @bleggett is looking into it

**Comment by bleggett** [comment]
weird :D yea that PR should fix all the occurrences we have of this.

**Comment by howardjohn** [comment]
I think this was in https://github.com/istio/istio/pull/51517 but we ended up going with another PR that didn't have the fix, so this is still needed

**Comment by brydoncheyney** [comment]
As mentioned earlier, it looks like a fix for this is still needed 🙏
