### ISSUE TITLE
Istio annotation networking.istio.io/service-type is not recognized

### ISSUE THREAD

**Issue by ashleywang1** [istio/istio#51575]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When testing a sample app with `istioctl x waypoint apply --namespace httpbin-inmesh --wait`  running `istioctl analyze` gave me the following error:
`Istio annotation networking.istio.io/service-type is not recognized`

### Version

```Text
❯ istioctl version
client version: 1.22.0
control plane version: 1.22.1
data plane version: 1.22.1 (1 proxies)

❯ k version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

**Comment by howardjohn** [comment]
The analyzer pulls from what is in istio.io/api for labels and annotations. We have a bunch of new ones that landed directly in istio/istio, not in API. Should be a fairly straightforward task to port those over
