### ISSUE TITLE
Istio Distributed Tracing only show one span

### ISSUE THREAD

**Issue by du2016** [istio/istio#5158]
i hava two service,A will request B,if i don't set headers,it will in muiti trace,if A set request headers,it only hava one span and one trace,i am set headers as the doc: https://istio.io/docs/tasks/telemetry/distributed-tracing.html

**Comment by douglas-reid** [comment]
I just tested this from master with the bookinfo samples and am able to see distributed traces for the calls.

I did notice some strange behavior regarding Mixer spans, but otherwise everything looks to be working.  Can you provide more detail on your issue ?

**Comment by du2016** [comment]
when i test the bookinfo,it work's ok,but i want to develop my own program, for example ,A request B,A set request headers like this:

func gethandler(w http.ResponseWriter,r *http.Request){
	client := &http.Client{}
	req,err:=http.NewRequest("GET","XXX",nil)
	headers:=[]string{"x-request-id","x-b3-traceid","x-b3-spanid","x-b3-parentspanid","x-b3-sampled","x-b3-flags","x-ot-span-context"}
	for _,v:=range headers{
		log.Println(v,"  :",r.Header.Get(v))
		if req.Header.Get(v)!=""{
			req.Header.Set(v,r.Header.Get(v))
		}
	}
	resp,err:=client.Do(req)
        if err!=nil {
		w.Write([]byte(err.Error()))
		return
	}
	result,err:=ioutil.ReadAll(resp.Body)
	if err!=nil {
		w.Write([]byte(err.Error()))
		return
	}
       w.Write([]byte(result))
}

**Comment by douglas-reid** [comment]
Can you compare your custom code to the bookinfo examples for header prop and distill any differences?

Alternatively, have you tried using any OpenTracing libraries to handle the header parsing and prop in your services.

There should be nothing special about the bookinfo application's handling of headers.

**Comment by bianpengyuan** [comment]
It actually works as expected if you are using Zipkin. It models one request to one span: both client-side information and server side information will be included and they share the same span id.

**Comment by du2016** [comment]
thanks,my program work's ok
