### ISSUE TITLE
Helm installation for istiod doesn't work for multi-cluster primary-remote on remote clusters. 

### ISSUE THREAD

**Issue by nshankar13** [istio/istio#51600]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When installing on a multi-cluster primary-remote setup with Helm, istiod cannot be installed on the remote cluster. 

The `istiod-remote` [chart](https://github.com/istio/istio/tree/1.22.1/manifests/charts/istiod-remote/templates) installs all the Services and Endpoints for the remote cluster. However, because this Helm chart is not published, the primary-remote setup needs to be done via the `base` and `istiod` charts. 

When installing the `base` Helm chart, the following command would be used:

```
helm install istio-base istio/base --set global.externalIstiod=true --set global.remotePilotAddress=${DISCOVERY_ADDRESS} --set pilot.enabled=false -n istio-system --kube-context $CTX_CLUSTER2
```

This installs all the Services and Endpoints in the remote cluster including for `istiod`. However, this causes errors when installing `istiod` after. 

```
helm install istiod istio/istiod -n istio-system --set global.externalIstiod=true --set global.remotePilotAddress=${DISCOVERY_ADDRESS} --set pilot.enabled=false --kube-context $CTX_CLUSTER2 
```

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Service "istiod" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "istiod": current value is "istio-base".
```

When the `istiod` helm installation sets `global.remotePilotAddress` - then the Helm installation should only install the necessary components

Alternatively, the `istiod-remote` Helm chart should be built and published and this should be the main way of installing `istiod` on the remote clusters. 

### Version

```Text
Using Helm v3.9.3 and istio-1.20 but the problem is also there for istio-1.22.
```

**Comment by keithmattix** [comment]
Yeah this totally makes sense to publish given Helm is our way forward. Can anyone from @istio/wg-environments-maintainers or @istio/wg-test-and-release-maintainers help out with next steps here? I'm happy to do whatever is needed

**Comment by bleggett** [comment]
In general publishing new charts is a PR in https://github.com/istio/release-builder
