### ISSUE TITLE
503 UC upstream_reset_before_response_started{connection_termination} on incomming call after two minutes

### ISSUE THREAD

**Issue by Shohou** [istio/istio#51619]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
I'm editing this issue because it has nothing to do with update to 1.21.3...

We have two pods with single app in each of them, let's say `A` and `B` with istio sidecars enabled and `A` is doing POST rest call to `B`. `B` is very slow for some reason and replies after let's say 3 minutes. By that time after 2 minutes istio-proxy sidecar on `B` pod replies back to `A` error 503:
```
[2024-06-18T10:19:42.614Z] "POST /v1/accounting/api-portal/card/CSP_XXXXXXX/ORE00000/DEC000000/topup HTTP/1.1" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 138 95 120001 - "-" "-" "ed37e325-1a4e-9827-b994-1a3317bcc0b1" "internal-api:8080" "10.34.127.167:8080" inbound|8080|| 127.0.0.6:58719 10.34.127.167:8080 10.34.126.119:57080 outbound_.8080_._.internal-api.default.svc.cluster.local default
```
Pod `A` has default istio-proxy configuration which has `retryPolicy` with `numRetries: 2` and `retriableStatusCodes: [503]` and retries this call.
As the result our component in pod `B` receives the same rest call 3 times and if it is not "idempotent" we have problems...

So far I'm failing to find where this 2 minutes timeout on incoming request is set...

### Version

```Text
istio version after downgrade back to 1.21.0, also tested with 1.21.3 and 1.19.6
client version: 1.21.0
control plane version: 1.21.0
data plane version: 1.21.0 (17 proxies), 1.21.3 (5 proxies)
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

**Comment by Shohou** [comment]
original description updated

**Comment by Stono** [comment]
Hey, see https://github.com/istio/istio/issues/51704

**Comment by hzxuzhonghu** [comment]
I donot remember we have 2 minutes timeout set

**Comment by Stono** [comment]
You don't, what this will be is an idle timeout on the application terminating the connection (see https://karlstoney.com/istio-503s-ucs-and-tcp-fun-times/).  I believe my suggestions in https://github.com/istio/istio/issues/51704 would resolve this.

**Comment by Shohou** [comment]
Thank you @Stono for you investigation and pointing this issues here.

Indeed 2 minutes timeout is our application timeout, found it in settings...

I changed description of this issue because I found it consistently fails on long requests, but I'm not sure it was my original problem on prod. By the app logs I see it didn't take 2 mins for pod `B` to reply. In logs it looked like `B` app replied fast, but 503 error in istio log still appeared after 2 minutes... maybe something else was blocking app response and timeout killed that connection... And somehow downgrading from 1.21.3 to 1.21.0 fixed the issue, maybe a simple restart would be just as good... don't know...

**Comment by Stono** [comment]
Id suggest if at all possible getting a packet capture with wireshark (look for knsiff), it's the only definitive way to know what's happening but I'm willing to bet you'll see RST from your app.

**Comment by hzxuzhonghu** [comment]
https://karlstoney.com/istio-503s-ucs-and-tcp-fun-times/ is a good explanation

**Comment by Philmon22** [comment]
I have the same issue but it isn't because of timeout. If you enable debug on the pod. It probably gives the error below. The document states it supports http1.1 and it can make the call to another API with http1.1 but refuses to send the information back to the client 

debug envoy client external/envoy/source/common/https/codec_clienr.cc:171 [tag: "ConnectionId":"201"] Error dispatching received data: http1.1 protocol error: unsupported transfer encoding thread=22

**Comment by hzxuzhonghu** [comment]
@Philmon22 Your probelem is mostly user setting error, which means the protocol set is not aligned with the application real used.

**Comment by Philmon22** [comment]
Thanks it was a code issue.

**Comment by Shohou** [comment]
#52111 - this pull request should fix this I believe
