### ISSUE TITLE
Documentation: clarify annotation usage

### ISSUE THREAD

**Issue by kovaxur** [istio/istio#51611]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi,
I try to use Istio resources annotations based on the following documentation:
https://istio.io/latest/docs/reference/config/annotations/

I try to use for example the includeInboundPorts annotation, which has two versions:

**traffic.istio.io/includeInboundPorts**
A comma separated list of inbound ports for which traffic is to be redirected to Envoy. The wildcard character ‘*’ can be used to configure redirection for all ports. An empty list will disable all inbound redirection.

**traffic.sidecar.istio.io/includeInboundPorts**
A comma separated list of inbound ports for which traffic is to be redirected to Envoy. The wildcard character ‘*’ can be used to configure redirection for all ports. An empty list will disable all inbound redirection.

For me the "traffic.istio.io" annotation was not working but the "traffic.sidecar.istio.io" was. Can you please extend the documentation, which to use when? Or maybe one is deprecated?

Thanks

### Version

```Text
istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (57 proxies)

kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio.io/pull/15307
