### ISSUE TITLE
Istion ambient mode with another namespace

### ISSUE THREAD

**Issue by anuraj-narayanan** [istio/istio#51643]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I try the istio ambient mode its working fine with my services(layer 7 header routing) if its deployed in default namespace. But the same is not working if the services deployed in a different namespace, say servicemesh.
Does the below waypoint command works fine?

➜  istio-1.22.1 istioctl x waypoint apply --namespace servicemesh --enroll-namespace --wait 
waypoint servicemesh/waypoint applied
namespace servicemesh labeled with "istio.io/use-waypoint: waypoint"
➜  istio-1.22.1 kubectl get gtw waypoint -n servicemesh

NAME       CLASS            ADDRESS        PROGRAMMED   AGE
waypoint   istio-waypoint   10.105.84.20   True         17s
➜  istio-1.22.1 

I have changed only this for a different namespace. 

### Version

```Text
istio version 1.22.1 used
Followed docs in https://istio.io/latest/docs/ambient/install/helm-installation/ and https://istio.io/latest/docs/ambient/getting-started/#bookinfo
```

**Comment by howardjohn** [comment]
Do you have the namespace labelled with `istio.io/dataplane-mode=ambient`?

**Comment by anuraj-narayanan** [comment]
Yes

➜  istio-1.22.1 kubectl describe namespace servicemesh
Name:         servicemesh
Labels:       istio.io/dataplane-mode=ambient
              istio.io/use-waypoint=waypoint
              kubernetes.io/metadata.name=servicemesh
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
➜  istio-1.22.1

**Comment by anuraj-narayanan** [comment]
@howardjohn - Did i miss anything, can you please advise?

**Comment by howardjohn** [comment]
this definitely shouldn't happen. Istio-cni logs will give info on why or
why not ambient was enabled, can you check? Might need to turn on the debug
log level

**Comment by anuraj-narayanan** [comment]
I deleted the namespace and reconfigured everything again.
Looks like i did some wrong configuration previously.
its working fine now, thanks @howardjohn for the support

**Comment by howardjohn** [comment]
Awesome, thanks! If it does happen again please get the istio-cni logs and we can take a look
