### ISSUE TITLE
Support PeerAuthentication.MutualTLS.Mode Strict for RMI connections

### ISSUE THREAD

**Issue by JessHolle** [istio/istio#51658]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Our RMI connections are blocked unless we use PeerAuthentication.MutualTLS.Mode Permissive/Disabled.

We want the service mesh to handle MTLS here, so we don't have to do so ourselves -- inclusive of RMI.

### Version

```Text
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.29.2

istioctl version
client version: 1.19.0
control plane version: 1.19.0
data plane version: 1.19.0 (2 proxies)
```

**Comment by JessHolle** [comment]
Or perhaps put another way, Istio's Auto mTLS does not seem to be getting applied to RMI connections...

**Comment by keithmattix** [comment]
IIUC RMI uses tcp and/or http so it should have auto mTLS applied. Are both Java applications in the mesh?

**Comment by JessHolle** [comment]
Yes, RMI uses TCP and both Java applications are in the mesh.

**Comment by keithmattix** [comment]
What address are you using for RMI: a pod ip or a service ip?

**Comment by JessHolle** [comment]
Service IP.

**Comment by keithmattix** [comment]
Hmmm I'm not super familiar with Java and RMI; does this issue help? https://github.com/istio/istio/issues/15293

**Comment by JessHolle** [comment]
We can look at that issue again.  But... RMI _does_ work if we set PeerAuthentication.MutualTLS.Mode to Permissive/Disable.

**Comment by howardjohn** [comment]
Not really, this needs more info on what it means to be "blocked". Access logs, etc

Probably it is sending to specific pod IPs instead of service VIPs

**Comment by JessHolle** [comment]
So... sorry for the noise here, but it turns out there was a port misconfiguration underlying our issues.

Yes, RMI works fine with Istio mTLS -- as expected.

**Comment by JessHolle** [comment]
Closing this issue as per my previous comment.
