### ISSUE TITLE
Istio Discovery’s helm chart is missing imagePullSecrets implementation 

### ISSUE THREAD

**Issue by imtmcdonald** [istio/istio#51653]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I tried to deploy the istiod helm chart using a private registry and associated image pull secret. 

Upon deployment, the pod failed with ErrImagePull.  Describing the pod, it displayed an event complaining about unauthorized access to the private registry.

I checked the rendered helm chart for istiod and the image pull secret isn’t referenced anywhere in the chart. I also searched the charts for each various past versions and this looks to be an ongoing issue.

Please update istiod helm chart so it leverages imagepullsecrets.

### Version

```Text
Kubectl version - 1.30
Helm chart version - latest
Chart - manifests/charts/istio-control/istio-discovery
```

### Additional Information

There was a previous PR created to resolve this issue, but was closed with no comments.
Ref: https://github.com/istio/istio/pull/50139

**Comment by RicHincapie** [comment]
the `imagePullSecret` implementation for istiod is at its ServiceAcount level [here](https://github.com/istio/istio/blob/1c5963301ae491bdb7a76d9480fcc0610c045559/manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml#L4).
From Kubernetes docs:

> Now, when a new Pod is created in the current namespace and using the default ServiceAccount, the new Pod has its spec.imagePullSecrets field set automatically

 You're probably hitting some other issue.
