### ISSUE TITLE
Adopt go1.23

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51664]
Tracking issue.

1 test fails currently. Related to https://github.com/golang/go/issues/68113
```                
2: FAIL:  ([]netip.Addr=[::ffff:11.1.1.12]) != ([]netip.Addr=[11.1.1.12])
```
In TestCNIPluginServer.

**Comment by ayushrakesh** [comment]
@howardjohn Can you help where is this test and how to reproduce this?

**Comment by howardjohn** [comment]
`go1.23rc1 test ./cni/pkg/nodeagent -run '^TestCNIPluginServer$'` will trigger it. Just need to install go1.23rc1

**Comment by howardjohn** [comment]
Done
