### ISSUE TITLE
k8s job no longer works after label the NS

### ISSUE THREAD

**Issue by linsun** [istio/istio#51662]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Adding the ambient label to my namespace, the job which simply calls the server and prints the output no longer works.

The job's ztunnel log indicated the error. 

```
2024-06-21T15:22:19.610683Z    warn    access    connection failed    src.addr=10.42.0.10:38576 dst.addr=104.16.1.35:443 direction="outbound" error=unknown source: 10.42.0.10                                               │
│ 2024-06-21T15:22:19.610995Z    warn    access    connection failed    src.addr=10.42.0.10:46036 dst.addr=10.43.244.207:3000 direction="outbound" error=unknown source: 10.42.0.10   
```

`10.42.0.10` is the job's POD IP.
```
simple         client-4prt9-qzcll                        0/1     Completed   0          2m10s   10.42.0.10   k3d-k3s-default-agent-0    <none>           <none>
```

### Version

```Text
1.22
```

**Comment by linsun** [comment]
Server's svc IP:

```
simple         server           ClusterIP   10.43.244.207   <none>        3000/TCP                                13h
```

**Comment by howardjohn** [comment]
Probably fixed by https://github.com/istio/ztunnel/pull/1111

**Comment by linsun** [comment]
Closing as this is fixed in master. not in 1.22.1, should be in next 1.22.x.
