### ISSUE TITLE
AZ issue with mTLS

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#5167]
Issue: confirm Availability Zone feature is working even in mTLS mode

was:

I installed the 0.8 release candidate using istio-auth.yaml
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.8.0-pre20180421-09-15/
( using https://github.com/istio/istio/blob/master/tools/setup_perf_cluster.sh )

and the ingress log had multiple:
```
2018-04-23T23:25:50.332019Z    info    Unable to retrieve availability zone from pilot: Get https://istio-pilot:15005/v1/az/istio-ingress/ingress~~istio-ingress-5566c5dcdd-k4hqr.istio-system~istio-system.svc.cluster.local: x509: certificate is not valid for any names, but wanted to match istio-pilot.svc 2
```

**Comment by liamawhite** [comment]
This is out of scope for 0.8 and the logs have been turned off

**Comment by ldemailly** [comment]
is there an open issue for 1.0 then ?

does it mean for 0.8 when using auth/mTLS AZ doesn't work ? will that be documented as a known issue (not sure removing the log is a useful "fix" for that problem)

**Comment by liamawhite** [comment]
https://github.com/istio/istio/issues/4702 and we don't support any AZ functionality currently because it required changes to envoy so there's nothing to document.

**Comment by ldemailly** [comment]
isn't it working, without mtls, in 0.7 ?

k closing this one in favor of #4702 (but curious about ^)

**Comment by liamawhite** [comment]
It is not we couldn't configure the defaults and the `local_cluster_name` was an issue and has moved in the v2 APIs.
