### ISSUE TITLE
Implement retry on connection reset to upstream

### ISSUE THREAD

**Issue by Stono** [istio/istio#51704]
**Describe the feature request**
Almost all 503's I see are connection resets.  

```
{"level":"debug","time":"2024-06-25T09:10:35.552211Z","scope":"envoy router","msg":"[Tags: \"ConnectionId\":\"621\",\"StreamId\":\"15076901503968233471\"] upstream reset: reset reason: connection termination, transport failure reason: ","caller":"external/envoy/source/common/router/router.cc:1332","thread":55}
```

These are connection resets between the Destination sidecar and the local app.  I've wrote about them before here [connection resets](https://karlstoney.com/istio-503s-ucs-and-tcp-fun-times/).  

<img width="806" alt="Screenshot 2024-06-25 at 10 21 42" src="https://github.com/istio/istio/assets/1486729/d0cbc4a1-7278-4748-ab2c-5a235a228ac6">

**Many** istio users run up against this, it's a pain to debug, and a pain to resolve, and continually comes back.  I believe if the destination sidecar implemented a retry policy on `reset` to the local app, it'd be a huge improvement for users of Istio out of the box.

The challenge at the moment is the current `DestinationRule` has a `retryOn`, but that's describing the connection between the source sidecar and the destination.  The resets described in the above scenario do not present at the source sidecar as a reset, they just present as a 503.  Arguably you could retryOn 503's but that's a much bigger blast radius than simply retrying on connection reset.

As an added thought, `retryOn: reset` carries some risk, in that you could in theory retry requests that _did_ make it to the destination service, which is a behaviour you may not want.

https://github.com/envoyproxy/envoy/issues/10007 (unfortunately old and closed) detailed a `reset-before-request` proposal, eg a safe reset.  Implementing this feature, and having it as the default on both `source sidecar -> destination sidecar` (eg retryOn in DestinationRule), and destination sidecar -> destination app (currently not configurable) I believe would resolve most users 503's.

**Describe alternatives you've considered**
There are no alternatives, currently users have to spend extremely large amounts of time trying to debug the reason for the 503 at the destination.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
> These are connection resets between the Destination sidecar and the local app. 

Are they happening when pod is shutting down?

**Comment by Stono** [comment]
No, they are not.  This is not related to startup or shutdown hooks.
  
Almost all of the time this is miss-matched keepAlive configuration between envoy and the local app (see https://karlstoney.com/istio-503s-ucs-and-tcp-fun-times/).  

It is completely fixable if we expect end users to ensure these align, however the proposal here would "fix" it somewhat transparently and _many_ 503 user issues would just go away.

**Comment by hzxuzhonghu** [comment]
>As an added thought, retryOn: reset carries some risk, in that you could in theory retry requests that did make it to the destination service, which is a behaviour you may not want.

Not sure i understand about this risk

**Comment by Stono** [comment]
so `retryOn: reset` can retry requests that have actually reached the destination service, but the connection has terminated before the response was received.  Retrying with `retryOn: reset` by default, means that you could potentially retry requests that should _not_ be retired.  Think for example; a payment request.

That's why I linked https://github.com/envoyproxy/envoy/issues/10007, which is a proposal for `reset-before-request`.

**Comment by sschepens** [comment]
@Stono just curious about what exactly is causing the resets you see.

I agree that we probably need a retry policy for ingress routes, but misaligned idle-timeouts usually produce un-retryable resets because envoy only realizes the connection is closed when writing the headers and at that point request is no longer retryable.

Did you try adding a retry policy to see if those 503 errors went away?

**Comment by Stono** [comment]
> Did you try adding a retry policy to see if those 503 errors went away?

You can't add a retry policy, because the timeout is between the local sidecar and the local application on the inbound request.  There is no API exposed in istio for this.

And as detailed on my original post, I wouldn't add a `retry` policy on `503` to the source sidecar, because then i'll retry unsafe requests.

> because envoy only realizes the connection is closed when writing the headers and at that point request is no longer retryable.

If that's the case, then what I'm proposing in this issue cannot be achieved.

**Comment by sschepens** [comment]
> You can't add a retry policy, because the issue is between the local sidecar and the local application on the inbound request (destination, on my diagram). There is no API exposed in Istio for this.

You can use an `EnvoyFilter` to patch Routes on ingress listeners

> If that's the case, then what I'm proposing in this issue cannot be achieved safely.

You can give it a try with using an EnvoyFilter, but I'm pretty sure that misaligned idle-timeouts issues cannot be retries safely.

We've experienced this issue of misaligned idle-timeouts as well in my company, and still encounter it from time to time. The most troublesome webserver is usualy nodejs which defaults to 5s idle timeouts which is way lower than the defaults Istio/Envoy have. I believe that the best way to solve this issues for good is to lower default the default idle timeout in ingress clusters to 5s. This is pretty safe since we're talking of unused connections and since they are local connections, they're pretty cheap to establish.

**Comment by Stono** [comment]
> You can use an EnvoyFilter to patch Routes on ingress listeners

I haven't tried with an EnvoyFilter, no.  I see no reason why it wouldn't work.

> I believe that the best way to solve this issues for good is to lower default the default idle timeout in ingress clusters to 5s

Seems reasonable too - have you tried that with an `EnvoyFilter`?  I wouldn't say it's mutually exclusive with a sensible/safe retry policy however.  

@ramaraochavali just thinking, the recent change you made in https://github.com/istio/istio/issues/51929 / https://github.com/istio/istio/pull/51935 to disable cleanup for inbound clusters, i'm wondering if that might subsequently exacerbate this problem?

**Comment by sschepens** [comment]
> Seems reasonable too - have you tried that with an EnvoyFilter? I wouldn't say it's mutually exclusive with a sensible/safe retry policy however as we have by default between on outbound clusters.

You can control inbound idle timeout through #[Sidecar resource](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioIngressListener-connection_pool). We're not currently modifying this since we've managed to push most usualy used frameworks/sdks in our company to have higher defaults, our nodejs framework also increses idle timeout.

**Comment by Stono** [comment]
@sschepens ah yes, I tried that actually and had no joy.

Similar to you, we've simply "fixed" it in all the web servers.  What i'm striving for in this thread is ideally defaults/settings that mean people don't need to go down the same rabbithole we have!

**Comment by Stono** [comment]
No, wait I lied - I didn't realise you can control the `connectionPool` on `Sidecar`, only on `DestinationRule`.  That's interesting - and I didn't try it.  I only fiddled with the `DestinationRule` config which obviously didn't help much because the problem wasn't between the downstream+proxy it was proxy+upstream.

Did you try `Sidecar` connectionpool, did it work?

**Comment by Stono** [comment]
Hey I just wanted to share this works a treat :-) 
`ENABLE_INBOUND_RETRY_POLICY=true` on pilot and as you can see from envoy metrics low level niggles getting caught! 

![Screenshot 2024-09-02 at 17 26 04](https://github.com/user-attachments/assets/8ada68fa-4eb5-4400-a491-b6a27c2642a4)

**Comment by ramaraochavali** [comment]
Thank you @Stono for the update

**Comment by Kyslik** [comment]
If anyone needs to amend the default via `EnvoyFilter` you can use following one:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: inbound-retry-on-reset
  namespace: a-namespace # or root namespace to apply cluster wide
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      routeConfiguration:
        name: inbound|4040||
    patch:
      operation: MERGE
      value:
        route:  
          retry_policy:
            retry_on: "reset,reset-before-request"
```

You can get the name of the inbound route(s) via `istioctl pc route POD | grep inbound`. 

Oh, and definitely read the article https://medium.com/@kburjack/fixing-503-errors-when-using-istio-envoy-bf63aa720826.

**Comment by ramaraochavali** [comment]
reset is not safe for retry. Use it if you are sure the requests are idempotent
