### ISSUE TITLE
the type of cacert is "Opaque" not " istio.io/key-and-cert"

### ISSUE THREAD

**Issue by sgilsonapigee** [istio/istio#5172]
The procedure described in "Plugging in CA certificate and key" at https://istio.io/docs/tasks/security/plugin-ca-cert.html includes these lines:

```
$kubectl create secret generic cacerts -n istio-system --from-file=/tmp/ca-cert.pem --from-file=/tmp/ca-key.pem --from-file=/tmp/root-cert.pem --from-file=/tmp/cert-chain.pem`

$kubectl apply -f install/kubernetes/istio-ca-plugin-certs.yaml
```

If you then examine cacert, its type is "Opaque" but the original secret, istio.default  is of type " istio.io/key-and-cert". Shouldn't they be the same?

`$ kubectl get secrets -n istio-system`

Returns:

```
NAME                 TYPE                                        
cacerts               Opaque                                     
istio.default        istio.io/key-and-cert              
```

**Comment by kidiyoor** [comment]
@myidpt

**Comment by myidpt** [comment]
Yes, there types are different, but I don't think there's any issue regarding to security. Do you see any issue here?

**Comment by sgilsonapigee** [comment]
no, but I was curious as to why?

**Comment by myidpt** [comment]
Because we are not using the TYPE of the service accounts.

When the users set the secret through command line, it is "Opaque" type, and when the Istio CA / Citadel creates a secret for the workload, it is of "istio.io/key-and-cert" type.
