### ISSUE TITLE
delete istio.default in the "istio-system" namespace when uploading a custom cert/key?

### ISSUE THREAD

**Issue by sgilsonapigee** [istio/istio#5173]
The procedure described in "Plugging in CA certificate and key" at https://istio.io/docs/tasks/security/plugin-ca-cert.html includes this lines to delete istio.default in the "default" namespace:

`kubectl delete secret istio.default`

But istio.default still exists in the "istio-system" namespace. Shouldn't you delete it in both:

`kubectl delete secret istio.default -n istio-system`

**Comment by kidiyoor** [comment]
@myidpt

**Comment by myidpt** [comment]
That's good question. Actually the task indicates "To make sure the workloads obtain the new certificates promptly, delete the secrets generated by Istio CA (named as istio.*)."

So yes, you need to do `kubectl delete secret istio.default -n istio-system` as well - and also for any other service accounts you created.
