### ISSUE TITLE
[multiple gateways] not able to use multiple gateways

### ISSUE THREAD

**Issue by ashishmahamuni21** [istio/istio#51733]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

i am trying to install 2 gateways where each gateway connected to the OCI NLB
i have installed this via helm on k8s cluster, where as i have to use 2 gateways where one is for public access and one gateway will route my traffic for all my internal applications with IP whitelisting. 
e.g - Public access gateway without authPolicy for public access for *.xyz.xyz traffic
`apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
        - *.xyz.zyx
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - *.xyz.zyx
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tls-wildcard-cert2
        mode: SIMPLE`

and another gateway for internal use for some restricted sites like canary.xyz.xyz:
`apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: canary-gateway
  namespace: canary
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
        -  canary.xyz.xyz
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        -  canary.xyz.xyz
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tls-wildcard-cert2
        mode: SIMPLE`
and the Authpolicy is:
`apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: canary-ip-whitelist
  namespace: canary
spec:
  selector:
    matchLabels:
      app: frontend
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks:
          - x.x.x.x/32`
          
where action DENY allows  the traffic for all IPs publicly even if i gave DENY IP
and action ALLOW blocks the traffic from all the IP's and gives RBAC access denied error

### Version

```Text
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

$ helm version --short
v3.8.1+g5cb9af4
```

### Additional Information

Installed gateway and istio via official helm chart with additional gateway written above
and istio version installed via helm is: 1.22.1

**Comment by sambo2021** [comment]
I don't know why it is closed!
but me either cannot use 2 gateways for the same ingress controller, only one works and second gives 504
