### ISSUE TITLE
Listeners missing for service entries with TCP ports and multiple addresses [1.22]

### ISSUE THREAD

**Issue by ashevtsov-wawa** [istio/istio#51747]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After upgrading from 1.21 to 1.22 listeners are missing for second and consecutive addresses listed in `addresses` block in service entry definition when resolution is `NONE` and protocol is `TCP`.

If I change protocol from `TCP` to `TLS` additional listeners get added to match the number of hosts specified in the spec but only the first address entry is used.

### Version

```Text
$ istioctl version
client version: 1.22.1
control plane version: 1.22.1
data plane version: 1.22.1 (18 proxies)

$ kubectl version
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b

$ helm version --short
v3.14.3+gf03cc04
```

### Istio 1.21 and Kubernetes 1.29
Added this for comparison. Configuration is taken from an identical cluster that runs Istio 1.21 and Kubernetes 1.29.
As you can see three listeners have been created - one for each address entry. The sample-app can communicate with the external service (all three AWS MSK brokers).
```
$ kubectl --context=cluster-02 get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.8.192/28
  - 10.123.8.208/28
  - 10.123.8.224/28
exportTo:
  - .
hosts:
  - b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-2.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
  - b-3.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: tcp
    number: 9092
    protocol: TCP
  - name: tcp-2
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9092
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9092 Addr: 10.123.8.192/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.208/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 Addr: 10.123.8.224/28 Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 ALL                   Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com

$ istioctl --context=cluster-02 proxy-config listener sample-app-6f45cbb67d-2xt62.sample-ns --port 9098
ADDRESSES PORT MATCH                 DESTINATION
0.0.0.0   9098 Addr: 10.123.8.192/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.208/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 Addr: 10.123.8.224/28 Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 ALL                   Cluster: outbound|9098||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TCP` protocol

Only one listener gets created in this case. The sample-app can talk to only one MSK broker, other requests end up being BlackHole'd.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TCP
  - name: msk-iam-auth
    number: 9098
    protocol: TCP
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9092 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9092 Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                  DESTINATION
0.0.0.0   9098 ALL                    Non-HTTP/Non-TCP
0.0.0.0   9098 Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### Istio 1.22 and Kubernetes 1.30 - `TLS` protocol

Not sure if this is relevant, since Istio seems to be using SNI only and probably ignores addresses block. The sample-app can communicate with all MSK brokers.

```
$ kubectl get serviceentry -n sample-ns msk-serviceentry -o yaml | yq e '.spec'
addresses:
  - 10.123.16.192/28
  - 10.123.16.208/28
  - 10.123.16.224/28
exportTo:
  - .
hosts:
  - b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
  - b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: msk-mtls-auth
    number: 9092
    protocol: TLS
  - name: msk-iam-auth
    number: 9098
    protocol: TLS
resolution: NONE

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9092
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9092 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9092 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9092 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9092||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com

$ istioctl proxy-config listener sample-app-6fb986c8d5-7mm67.sample-ns --port 9098
ADDRESSES PORT MATCH                                                                                           DESTINATION
0.0.0.0   9098 ALL                                                                                             Non-HTTP/Non-TCP
0.0.0.0   9098 SNI: b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-3.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-2.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098 SNI: b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com; Addr: 10.123.16.192/28 Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

**Comment by howardjohn** [comment]
:eyes: 

```
$ ik pc l deploy/shell | rg 9092
0.0.0.0       9092  ALL                                                                                             PassthroughCluster
0.0.0.0       9092  Addr: 10.123.8.192/28                                                                           Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
$  cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar
spec:
  egress:
  - hosts:
    - ./*
EOF
sidecar.networking.istio.io/sidecar created
$ ik pc l deploy/shell | rg 9092
0.0.0.0   9092  ALL                                                                                             PassthroughCluster
0.0.0.0   9092  Addr: 10.123.8.192/28                                                                           Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092  Addr: 10.123.8.208/28                                                                           Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com
0.0.0.0   9092  Addr: 10.123.8.224/28                                                                           Cluster: outbound|9092||b-1.msk02.fedcba.b12.kafka.us-east-1.amazonaws.com

**Comment by ashevtsov-wawa** [comment]
Added this sidecar resource and the missing listeners were recreated.
Does this affect egress between workloads in the same and different namespaces? Most importantly whether authorization policies are still applicable because that's how we allow communication between different workloads in the same or different namespaces.
It's hard to tell what `allow egress traffic only to other workloads in the same namespace` means in regards to authorization policies.

**Comment by howardjohn** [comment]
Just to clarify in my comment, I think this is bug. Just a subtle one which is only triggered in some scenarios. Details incoming as I investigate, I think I mostly understand the problem, just thinking through solutions.

Authorization only impacts inbound traffic. Sidecar.egress impacts outbound traffic. So they are mostly decoupled. However, you could have a sidecar.egress policy that hides the info on how to connect to `backend`, and cause it to not do mTLS or other policies, and thus indirectly make it fail authorization.

That being said, the policy above says "include everything" (which is what is the default if you don't have one, https://github.com/istio/istio/blob/c089c81567e8a2e617c11e87045c4b3a8edb506f/pilot/pkg/model/sidecar.go#L289, it just has a bug)so should be fine

**Comment by howardjohn** [comment]
So the difference is from a mismatch in `SidecarScope.services` and `SidecarScope.EgressListeners.services`.

The former is used in CDS/NDS, the latter in LDS/RDS (proxyless gRPC uses the SidecarScope.services for LDS -- perhaps a bug).

```
DefaultSidecarScopeForNamespace
  services := ps.servicesExportedToNamespace(configNamespace)
  SCOPE: out.services = appendSidecarServices
  WRAPPER: defaultEgressListener.services = out.services

convertToSidecarScope
  WRAPPER: convertIstioListenerToWrapper
    svces := ps.servicesExportedToNamespace(configNamespace)
    out.services = out.selectServices(svces, configNamespace, hostsByNamespace)
  SCOPE: collectImportedServices(from all wrappers)
```

is the high level flows.

Ultimately in the no-sidecar case we end up with services only being filtered through `appendSidecarServices`. This has a more restrictive de-duping check based on hostname. (note: the SE gets translated into 1-Service-per-address).

**Comment by howardjohn** [comment]
I put a PR up to fully unify these two codepaths: https://github.com/istio/istio/pull/51776. It fixes this case, though I am sure there are some weird edge cases I didn't think of, will see how it goes through tests.

cc @hzxuzhonghu @ramaraochavali

**Comment by ashevtsov-wawa** [comment]
Thank you for quick turnaround. I am going to try to build a container image off of your feature branch and run it on the affected cluster to confirm whether the issue gets resolved. Will keep you posted.

**Comment by howardjohn** [comment]
Alright looks like every test failed so its not exactly ready to go :-). Just setting 
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar
spec:
  egress:
  - hosts:
    - ./*
```

should be the best workaround for now. You might even be able to put it in istio-system and just have one mesh-wide, not 100% sure

**Comment by ashevtsov-wawa** [comment]
I did put it in the istio-system namespace. But it introduced another "issue" (which might be expected behavior though). Listeners for service entries that exist in the istio-system namespace (which are cluster-wide - don't have `exportTo: ["."]`) disappeared.

### Service entry

```
❯ k get serviceentry -n istio-system aws-sts-se -o yaml | yq e '.spec'
hosts:
  - sts.amazonaws.com
  - sts.us-east-1.amazonaws.com
  - sts.us-east-2.amazonaws.com
  - sts.us-west-1.amazonaws.com
  - sts.us-west-2.amazonaws.com
location: MESH_EXTERNAL
ports:
  - name: https
    number: 443
    protocol: TLS
resolution: DNS
```

### With sidecar in istio-system
```
❯ istioctl proxy-config listener sample-app-2.sample-ns-2 | grep amazonaws.com
ADDRESSES PORT  MATCH                                                                    DESTINATION
0.0.0.0   9094  Addr: 10.123.16.192/28                                                   Cluster: outbound|9094||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9094  Addr: 10.123.16.208/28                                                   Cluster: outbound|9094||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9094  Addr: 10.123.16.224/28                                                   Cluster: outbound|9094||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098  Addr: 10.123.16.192/28                                                   Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098  Addr: 10.123.16.208/28                                                   Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098  Addr: 10.123.16.224/28                                                   Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0   9098  ALL                                                                      Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

### Without sidecar in istio-system
```
❯ istioctl proxy-config listener sample-app-2.sample-ns-2 | grep amazonaws.com
0.0.0.0         443   SNI: sts.us-west-2.amazonaws.com                                         Cluster: outbound|443||sts.us-west-2.amazonaws.com
0.0.0.0         443   SNI: sts.us-west-1.amazonaws.com                                         Cluster: outbound|443||sts.us-west-1.amazonaws.com
0.0.0.0         443   SNI: sts.us-east-2.amazonaws.com                                         Cluster: outbound|443||sts.us-east-2.amazonaws.com
0.0.0.0         443   SNI: sts.us-east-1.amazonaws.com                                         Cluster: outbound|443||sts.us-east-1.amazonaws.com
0.0.0.0         443   SNI: sts.amazonaws.com                                                   Cluster: outbound|443||sts.amazonaws.com
0.0.0.0         9094  Addr: 10.123.16.192/28                                                   Cluster: outbound|9094||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
0.0.0.0         9098  Addr: 10.123.16.192/28                                                   Cluster: outbound|9098||b-1.msk03.abcdef.a01.kafka.us-east-1.amazonaws.com
```

**Comment by hzxuzhonghu** [comment]
Yes, previously i identified the services in SidecarScope can be inconsistent. Will try to understand this issue though

**Comment by howardjohn** [comment]
Route has a similar but different issue:

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: echo
spec:
  addresses:
  - 240.240.240.210
  - 2001:2::f0f0:255
  endpoints:
  - address: fc00:f853:ccd:e793::65
    ports:
      http: 80
  hosts:
  - serviceentry.istio.io
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 12345
    protocol: HTTP
  resolution: STATIC
```

It never shows both IPs in the domain match

**Comment by ramaraochavali** [comment]
Is this a regression or never worked?

**Comment by hzxuzhonghu** [comment]
LIke a regression

**Comment by ashevtsov-wawa** [comment]
Original issue is a regression. Not sure about the case that John described earlier.

**Comment by jewertow** [comment]
I am reopening this issue to decide what we do about this bug in 1.22.

@howardjohn I investigated the workaround with Sidecar and the PR https://github.com/istio/istio/pull/51776, and even though both approaches fix the reported issue in 1.22, we will not need it anymore in 1.23+, because we no longer create internal services for each [hostname , address] pair. I mean, it's a good code improvement, but it no longer fixes generating listeners, and at the same time, that PR caused a few test failures and I wasn't able to quickly fix them, and my tries to fix them caused other failures. So I wonder what is safer to backport to 1.22: #51776 vs #51967?

**Comment by howardjohn** [comment]
I view 51776 as highly risky, so would prefer backporting 51967 and work on 51776 in master and taking our time to get it right

**Comment by jewertow** [comment]
Ok, thanks for confirmation. @eoinfennessy will try to fix test failures in https://github.com/istio/istio/pull/51776 and complete that change.

**Comment by jewertow** [comment]
@ashevtsov-wawa the bug fix will be released in 1.22.4, so I am closing the issue.

**Comment by howardjohn** [comment]
Wanted to followup on this. The 1.22 and 1.23 changes for this have been reverted.

There is a simple workaround:

```yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: sidecar
  namespace: default
spec:
  egress:
  - hosts:
    - '*/*'
```

(don't create this if you already have a Sidecar).

We will forward fix this with https://github.com/istio/istio/pull/51776 once its ready in the near future

**Comment by Kyslik** [comment]
👋🏻 , since the fix was reverted should the issue be re-opened 🧐?

@howardjohn can you please elaborate on ramifications of applying the workaround in MeshConfig [root namespace](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig).

Reference: https://istio.io/latest/docs/reference/config/networking/sidecar/#Sidecar

**Comment by howardjohn** [comment]
1.24 essentially made the default behavior that way, you can see the upgrade notes that explain the minor behavioral differences: https://istio.io/latest/news/releases/1.24.x/announcing-1.24/upgrade-notes/#sidecar-scoping-changes
