### ISSUE TITLE
Istio upgrade where data plane and control plane are on different versions

### ISSUE THREAD

**Issue by nabiladoui** [istio/istio#51795]
Hi,
we are currently planning an istio upgrade from 1.17.8 to 1.19.10. we understand that as part of the upgrade process, manual pod restart is required to upgrade the sidecars as well, however this would cause service interruption.

The question is : can data plane and conrol plane be on different versions ? is there any compatibility matrix to follow in this regard ?

thank you

**Comment by zirain** [comment]
https://istio.io/latest/docs/releases/supported-releases/#control-planedata-plane-skew

**Comment by zirain** [comment]
please use https://istio.io/latest/docs/setup/upgrade/canary/
