### ISSUE TITLE
Test CNI ambient flow with integration tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51845]
We now have the ability to create various namespaces without root; we do this in `tools/istio-iptables/pkg/dependencies/implementation_linux_test.go` already.

It may be valuable to test more end-to-end flows of the CNI plugin + ambient + ztunnel lifecycle. I am not 100% convinced this is will improve coverage, but my intuition is that it will

cc @bleggett

**Comment by bleggett** [comment]
xref: https://github.com/istio/istio/issues/50991

It would be good to (re)enable coverage for `istio-cni` before we did this, to actually make sure we were covering new scenarios/branches/hitting the least-covered flows first.
