### ISSUE TITLE
Support matching multiple IPs for one service in waypoint

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#51886]
A SE like `addresses: [240.240.240.239, 2001:2::f0f0:239]` only generates a listener config for `240.240.240.239` on the waypoint. This is because this creates 2 model.Services, and we dedupe by hostname

related: https://github.com/istio/istio/issues/51747, especially https://github.com/istio/istio/issues/51747#issuecomment-2204503610

**Comment by jewertow** [comment]
I drafted a simple (maybe naive) [solution](https://github.com/istio/istio/compare/master...jewertow:upstream-istio:match-multiple-svc-ips-in-waypoint) and it works. I will investigate it more and will submit a PR soon.

**Comment by howardjohn** [comment]
Nice! I forgot I opened this issue and also played around with a draft https://github.com/istio/istio/pull/51913. Looks like we came up with exactly the same solution which is a good sign. Feel free to continue the work here if you a e interested, I am mostly ooo next week so probably wouldn't get enough time to make it merge-able next week in time for code freeze (but can review yours).

Thanks! And sorry I forgot. to link to this ossue

**Comment by jewertow** [comment]
Ok, I will continue.

**Comment by howardjohn** [comment]
btw the challenge here is to make sure the change in the SE logic is safe
for non-ambient. There have been a lot of bugs in this (some still
outstanding! this could actually fix them; I'll find a link tomorrow) in
the past.

Especially worried about if the same hostname is defined in k8s service as
well, since now the clusterid will conflict (?)

**Comment by howardjohn** [comment]
Ok I tested the change a bit for sidecars. Behavior as follows:


Master, No sidecar
```
ADDRESSES       PORT MATCH DESTINATION
240.240.240.255 9090 ALL   Cluster: outbound|9090||dummy.example.com
NAME     VHOST NAME                 DOMAINS                                MATCH     VIRTUAL SERVICE
9091     dummy.example.com:9091     dummy.example.com, 240.240.240.255     /*
```

Sidecar
```
ADDRESSES        PORT MATCH DESTINATION
2001:2::f0f0:255 9090 ALL   Cluster: outbound|9090||dummy.example.com
240.240.240.255  9090 ALL   Cluster: outbound|9090||dummy.example.com
NAME     VHOST NAME                 DOMAINS                                   MATCH     VIRTUAL SERVICE
9091     dummy.example.com:9091     dummy.example.com, [2001:2::f0f0:255]     /*
```

PR, no sidecar
```
ADDRESSES       PORT MATCH DESTINATION
240.240.240.255 9090 ALL   Cluster: outbound|9090||dummy.example.com
NAME     VHOST NAME                 DOMAINS                                MATCH     VIRTUAL SERVICE
9091     dummy.example.com:9091     dummy.example.com, 240.240.240.255     /*
```


PR, sidecar
```
ADDRESSES       PORT MATCH DESTINATION
240.240.240.255 9090 ALL   Cluster: outbound|9090||dummy.example.com
NAME     VHOST NAME                 DOMAINS                                MATCH     VIRTUAL SERVICE
9091     dummy.example.com:9091     dummy.example.com, 240.240.240.255     /*
```

Related PR/issue is https://github.com/istio/istio/pull/51776. 
So I think to go along with this PR, we will also need fixes to listeners and routes to properly use all addresses?
