### ISSUE TITLE
istioctl verify-install throws unknown field "oneNamespace" in v1alpha1.GlobalConfig in Istiocli 1.22.2

### ISSUE THREAD

**Issue by DavidLeonardoGutierrez** [istio/istio#51889]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

On canary upgrades, after installing the canary revision, our team usually runs the following command:

`istioctl verify-install --context kubeContext --revision $canary-revision-tag`

Unfortunately, during canary upgrade(process from `v1.20.3` -> `v1.22.2`), the `verify-install` started showing the following error: 
`✘ IstioOperator: installed-state-v1-20-3.istio-system: unknown field "oneNamespace" in v1alpha1.GlobalConfig`  and `Error: unknown field "oneNamespace" in v1alpha1.GlobalConfig`. 

We noticed that `oneNamespace` field [was removed](https://github.com/istio/istio/pull/49610) recently.

Could you guys help us to confirm if this is an issue with the `istioctl verify-install`?

### Version

```Text
istioctl and Istio control plane versions: `v1.22.2` and `v1.20.3`
```

### Additional Information

command for installing Istio revisions:

`istioctl manifest install --context kubeContext -f manifest.yaml --set revision=$canary-revision-tag -y --readiness-timeout 10m0s`

**Comment by howardjohn** [comment]
I think this means the in-cluster IstioOperator object has the old legacy field so it fails to unmarshal it. 

Though there are also some other issues on verify install now: https://github.com/istio/istio/issues/51666

**Comment by DavidLeonardoGutierrez** [comment]
Thanks for your answer @howardjohn.

Yeah, I think that's what's happening.

In our case we run that command for both: stable(`v1.20`) version and canary(`v1.22`) version. It fails for canary. 

The interesting part is that even if the command is executed specifying the canary revision, it seems to use the IstioOperator of the stable version. 

I noticed the following in`v1.21` release notes:

`Removed the installed-state IstioOperator that was created when running istioctl install. This previously provided only a snapshot of what was installed. However, it was a common source of confusion (as users would change it and nothing would happen), and did not reliably represent the current state. As there is no IstioOperator needed for these usages anymore, istioctl install and helm install no longer install the IstioOperator CRD. Note this only impacts istioctl install, not the in-cluster operator.`

Feel like the command might be using the unique `IstioOperator` it founds.

**Comment by sonnyhcl** [comment]
I run into similar error which I believe the same root cause
```
++ istioctl verify-install --revision 1-21-4
2024-07-08 12:06:21.460716: Run the command with the --force flag if you want to ignore the validation error and proceed.
2024-07-08 12:06:21.461182: \N{HEAVY BALLOT X} IstioOperator: installed-state-istiocontrolplane-1-19-3.istio-system: unknown field "wasmEnabled" in v1alpha1.TelemetryV2PrometheusConfig
2024-07-08 12:06:21.595991: Run the command with the --force flag if you want to ignore the validation error and proceed.
2024-07-08 12:06:21.596268: \N{HEAVY BALLOT X} IstioOperator: installed-state-istiocontrolplane-1-20-2.istio-system: unknown field "wasmEnabled" in v1alpha1.TelemetryV2PrometheusConfig
```

**Comment by sbeck14** [comment]
Thought I'd drop this here for anyone coming from a Google search:

If you are updating Istio and encountering this error

```
unknown field "wasmEnabled" in v1alpha1.TelemetryV2PrometheusConfig
```

or this one

```
Error: unknown field "oneNamespace" in v1alpha1.GlobalConfig
```

I was able to get this resolved by removing the values that were taken out in https://github.com/istio/istio/pull/47892:

https://github.com/istio/istio/pull/47892/files#diff-b4613f2d13979a0bcaceab1167366420e6a2c387d0be747c708df63c2630e944L138-L148

- `telemetry.v2.metadataExchange`
- `telemetry.v2.prometheus.wasmEnabled`
- `telemetry.v2.stackdriver.logging`
- `telemetry.v2.stackdriver.monitoring`
- `telemetry.v2.stackdriver.topology`
- `telemetry.v2.stackdriver.configOverride`

as well as `global.oneNamespace` (removed in the MR mentioned before https://github.com/istio/istio/pull/49610).

**Comment by howardjohn** [comment]
I think there are two parts here:
* Fields that do nothing/have been deprecated for a long time are removed (in past releases and likely future ones). You should remove the fields in your config
* Various verify-install specific issues, which is being tracked in https://github.com/istio/istio/issues/51666
