### ISSUE TITLE
TreatMissingHeaderAsEmpty for regex matchers

### ISSUE THREAD

**Issue by Ferdudas97** [istio/istio#51880]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Regex matcher for headers in Virutal Service doesn't work for missing headers - when there is a regex like a `|foo` then the request without header will not be matched.

It is because there is a lack of TreatMissingHeaderAsEmpty - https://github.com/wulianglongrd/istio/blob/master/pilot/pkg/networking/core/route/route.go#L1007

. 

### Version

```Text
istioctl version
client version: 1.20.0
control plane version: 1.20.1
data plane version: 1.20.1 (283 proxies)
```

**Comment by ramaraochavali** [comment]
We can't change this for backward compatibility reasons. Also not sure whether it is correct to treat missing headers as empty. That regex match user may intend to specify whether that header carries empty value of it has value it should be "foo". I think that is the reason Envoy added that config option.

Are you not able to change this via Envoy filter?

**Comment by Ferdudas97** [comment]
Nope, because headers  matchers in in Envoy config are a [list](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routematch) and merging policy in EnvoyFilters adds the new item in the list instead of merging the element for the same header

**Comment by ramaraochavali** [comment]
Got it. I am not sure if it is safe to set this for regex matches. May be we need an API change. @howardjohn @hzxuzhonghu  WDYT?
