### ISSUE TITLE
Gateway injection template ignores `sidecar.istio.io/proxyImage` annotation

### ISSUE THREAD

**Issue by dpasiukevich** [istio/istio#51888]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Gateway injection template for some reason only looks at `.Values.global.proxy.image` without checking proxyImage annotation (even though this annotation's value is used line below).

https://github.com/istio/istio/blob/91af022f3d320d2562fe6e57ccf22149636dd294/manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml#L25-L26

### Version

```Text
istioctl version
1.18.4

kubectl version
Client Version: v1.30.2
```

**Comment by zirain** [comment]
have you every try with a supported version(currently it's 1.21 and 1.22)?

**Comment by dpasiukevich** [comment]
The template has not changed since and the same piece of code is in the HEAD.

If needed I can set up 1.22 locally and verify

**Comment by dpasiukevich** [comment]
I have verified in istio 1.22
```
 % bin/istioctl version
client version: 1.22.2
control plane version: 1.22.2
data plane version: 1.22.2 (9 proxies)
```

Summary:
For gateway injection template a `sidecar.istio.io/proxyImage` annotation is not working by default. Users must modify `.Values.global.proxy.image` to some non-default value that contains '/' to be able to use `proxyImage` annotation for injection.

@howardjohn could you confirm if that's a bug and I can make a fix if needed.

Thanks!

**Comment by zirain** [comment]
oh I see, this's more like a bug from my side.

**Comment by dpasiukevich** [comment]
@zirain sg, should I make a fix (if this is only to do in that template)? Or it's better if you do it (e.g. if you have capacity)?

**Comment by zirain** [comment]
> @zirain sg, should I make a fix (if this is only to do in that template)? Or it's better if you do it (e.g. if you have capacity)?

it's better you do it(Unless you don't want to).

**Comment by dpasiukevich** [comment]
> > @zirain sg, should I make a fix (if this is only to do in that template)? Or it's better if you do it (e.g. if you have capacity)?
> 
> it's better you do it(Unless you don't want to).

Sure thing, I will send a PR.
