### ISSUE TITLE
Add notes to authorization-policy docs

### ISSUE THREAD

**Issue by christianlafleur** [istio/istio#51896]
**Describe the feature request**
Using Istio 1.22, it seem that authorization-policy must contain gateway namespace in source.namespace field to prevent "response_code_details":"rbac_access_denied_matched_policy[none]"

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
can you give some more details about the before and after? there were jonintended changes to this API.
