### ISSUE TITLE
Istio has sent a listener with the incorrect port for a headless service.

### ISSUE THREAD

**Issue by ghtian123** [istio/istio#51908]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio has sent a listener with the incorrect port for a headless service.

![image](https://github.com/istio/istio/assets/28430660/742a5ffe-1241-4052-b1a1-f65ed32a03b1)

with this service istio use port for listener 

![image](https://github.com/istio/istio/assets/28430660/301ee05e-3ecd-49dc-904d-39cf65c8fe63)

I think that the targetPort should be used as the port for the listener.

### Version

```Text
$istioctl version
client version: 1.20.2
control plane version: 1.20.8
data plane version:  (2 proxies), 1.20.2 (6 proxies)

$kubectl version --short
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.4
```

**Comment by howardjohn** [comment]
You should not set targetPort!=port in headless service. This has no meaning, and is effectively a bug in the Kubernetes API that they do not prevent this. Try without Istio for instance, you will see it is ignored

**Comment by jiayoukun** [comment]
@howardjohn In fact, our initial attempt with the headless service was to configure it without a targetPort. When deploying the listener, it used the service's port, which prompted me to try adding the targetPort configuration. In my understanding, since the headless mode is already being used, the listener should select the Pod's port instead. However, it used the service's port. Is my understanding incorrect?

**Comment by jiayoukun** [comment]
> You should have servicePort==targetPort==the port the pod is listening on

So since my Service has enabled headless mode, why is the port of the listener in the deployed xds using the Service's port? My understanding is that since the Service has enabled headless mode, the listener's configuration should be Pod IP:Pod Port, not Pod IP:Service Port?

**Comment by howardjohn** [comment]
In Kubernetes headless service port have no meaning at all. To workaround limitations in Istio (not present in ambient, fwiw), Istio encodes a specific meaning to them.

**Comment by jiayoukun** [comment]
> In Kubernetes headless service port have no meaning at all. To workaround limitations in Istio (not present in ambient, fwiw), Istio encodes a specific meaning to them.

What is the significance of encoding specific meanings for headless service ports in this way? My understanding is that it sacrifices the flexibility of multi-container Pods when deploying the xds listener.

**Comment by howardjohn** [comment]
because we cannot express routing configuration without considering ports in envoy.

**Comment by jiayoukun** [comment]
> because we cannot express routing configuration without considering ports in envoy.

You misunderstood my question: After the Service enables headless mode, the listener deployed by xds is Pod IP:Service port. My question is, why is this Service port needed? Since the Pod IP is already being used, why not use the Pod Port?

**Comment by yuzhiquan** [comment]
`targetPorts` on headless services were tolerated in k8s, so they did not have the validation.

**Comment by howardjohn** [comment]
This is essentially a limitation of Istio that it cannot properly express a headless service. This is encoded in https://github.com/istio/istio/issues/36596. Until that happens (which, TBH, is unlikely to happen soon) the existing state is unlikely to change
