### ISSUE TITLE
Client-Side AuthorizationPolicy

### ISSUE THREAD

**Issue by MaYuan-02** [istio/istio#51906]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Current authorizationpolicy works on server-side, which can protect my server.  But in sidecar mode, istio-proxy also plays a role as a client proxy.
My request is: restrict the destinations(such as ip, destination host, destination service) which current client can access, no matter it's in-cluster or not-in-cluster. The first idea in my mind is use authorizationpolicy, but it only works on server-side.
Can we add a parameter in authorizaitonpolicy like inbound/outbound to support this use case.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by wulianglongrd** [comment]
Weird usage, can you describe your actual usage scenario?

It looks like a routing requirement, not an authentication requirement.

**Comment by secretXIAOYU** [comment]
I want to restrict my application pod to only access the external services that I allow. 
Example: 
* My application can access "ip 12.12.12.12/16 AND  port 22" OR "ip any AND port 80".
* My application can only access the servers(in-cluster or not-in-cluster) which are in my whitelist. No other servers are allowed.
Of course I can do this on server-side, but that needs a lot of configs.

**Comment by howardjohn** [comment]
I don't think this will ever happen in sidecar mode. See https://blog.howardjohn.info/posts/bypass-egress/. *maybe* it could for ambient.

**Comment by hzxuzhonghu** [comment]
Can you limit that a little with `Sidecar` api

**Comment by MaYuan-02** [comment]
> I don't think this will ever happen in sidecar mode. See https://blog.howardjohn.info/posts/bypass-egress/. _maybe_ it could for ambient.

I see, thanks for your reply. My requirements almost are based on L4 info, will we consider implementing this capability in Ambient(ztunnel)?

**Comment by MaYuan-02** [comment]
> Can you limit that a little with `Sidecar` api

yes, I have tried. But if destinations were  external, I need to registry all of them and enable registry-only. It's really a big change in my env.

**Comment by howardjohn** [comment]
> I see, thanks for your reply. My requirements almost are based on L4 info, will we consider implementing this capability in Ambient(ztunnel)?

Its been considered but hasn't happened yet and doesn't have any concrete plans or ownership yet. I would expect it will *eventually* happen, but its not currently a priority and its Very Hard

**Comment by MaYuan-02** [comment]
OK

**Comment by MaYuan-02** [comment]
@howardjohn 
I’m running into this issue again. In my environment, NetworkPolicy isn’t available, so we rely on ztunnel to block outbound traffic.

Could we support a configuration similar to the sidecar mode “registry-only” behavior? Besides adding the necessary decision logic in ztunnel, are any additional changes needed to ensure security?
