### ISSUE TITLE
lower tls_inspector initial_read_buffer_size 

### ISSUE THREAD

**Issue by sschepens** [istio/istio#51910]
**Describe the feature request**
We've been hit by the same issue as reported in envoy: https://github.com/envoyproxy/envoy/issues/34706

As stated in [this comment](https://github.com/envoyproxy/envoy/issues/34706#issuecomment-2165596873) `tls_inspector` default `initial_read_buffer_size` is `64kb` which is a lot and causes a lot of memory to be used when there is a lot of active connections.

It would be great to find an ideal standard size to set for Istio deployments, and probably be able to tune this for different listeners, for example:
- ingress listeners receive mtls client hello from other sidecars, we could check what's the standard size of those packets.
- egress listeners i think usually don't receive much tls traffic a much less frequently mtls traffic, we could further reduce the size read from these listeners.

Tweaking this configuration is pretty safe because if the filter needs more data, then it continues double the read buffer size until `64kb` is reached which is the maximum. So in the worst case scenario we would end up performing more socket reads, which shouldn't be too bad.

To take into consideration, `http_inspector` reads only `8k` which is 8 times less.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
I agree. While TLS RFCs do not limit the size of a client hello, 64k is pretty high.  TLS Max record size it self is 16k I think. We can safely reduce it to 8k atleast.

**Comment by zhqworld4303** [comment]
@ramaraochavali or @howardjohn I suspect this fix caused https://github.com/istio/istio/issues/57312, can you have a look?
