### ISSUE TITLE
Include additional kubeconfig fields in encoded data when creating remote secret

### ISSUE THREAD

**Issue by AnirbanNandi** [istio/istio#51934]
**Describe the feature request**

Background: 
`istioctl analyze` doesn't work for multi cluster setups where each cluster needs to be accessed via different proxies. This is because `istioctl create-remote-secret` ignores the `proxy-url` field in the kubeconfig when creating the secret (or more accurately, sets only a [specific set of fields](https://github.com/istio/istio/blame/23fc23c669d0567a029e77fa0fa9ee5dcee094ac/istioctl/pkg/multicluster/remote_secret.go#L702)).

Clarification: 
I'm curious if they was any specific rationale behind not using the kubeconfig as-is when creating the remote secret, except for maybe few fields like the [service account token secret](https://github.com/istio/istio/blame/23fc23c669d0567a029e77fa0fa9ee5dcee094ac/istioctl/pkg/multicluster/remote_secret.go#L683)? 

Proposal: 
A general solution to the above problem could be to improve `istioctl/pkg/multicluster/remote_secret.go` to consider additional fields in the supplied kubeconfig when creating the remote secret (`proxy-url` being one of them). Changing the source code to something like the following should work (this is a crude modification simply for demonstration):
```
func createBaseKubeconfig(caData []byte, clusterName, server, proxyURL string) *api.Config {
	return &api.Config{
		Clusters: map[string]*api.Cluster{
			clusterName: {
				...
				ProxyURL:   proxyURL,
                                ...
			},
		},
        ...
}
...
func createRemoteSecret(opt RemoteSecretOptions, client kube.CLIClient) (*v1.Secret, Warning, error) {
        ...
	proxyURL, err := client.RESTConfig().Proxy(nil)
	if err != nil {
		return nil, nil, fmt.Errorf("get proxy url: %v", err)
	}
	
	var remoteSecret *v1.Secret
	switch opt.AuthType {
	case RemoteSecretAuthTypeBearerToken:
		remoteSecret, err = createRemoteSecretFromTokenAndServer(client, tokenSecret, opt.ClusterName, server, secretName, proxyURL.String())
        ...
```
@howardjohn @ayj @nmittler @hanxiaop (Tagging y'all from the list of top contributors to this file but please loop in other folks as needed)

**Describe alternatives you've considered**

1. Users can set the `HTTPS_PROXY` env var to the proxy url before running `istioctl-analyze` but that would work only when all clusters are reachable from the same proxy.
2. Users can modify the remote secrets in the cluster that `istioctl analyze` is run against so that the encoded data also includes the `proxy-url` field. The obvious downside is that there would be significant manual toil when there are a lot of clusters.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by AnirbanNandi** [comment]
> Can you clarify - where would the proxy be set ?
>
> The 'remote kubeconfig' is intended for Istiod running in a flat network and having direct access to k8s.

The proxy would mostly be set on the dev machine but now that you mention the "intended" use-case of these secrets, I realise that including additional kubeconfig fields in the secret could be problematic

> A better approach for istioctl would be to just load and use all contexts in kubeconfig - and leave the JWTs for istiod.

I guess this would require a change in the multi-cluster analyze flow then (in the [getClients](https://github.com/istio/istio/blob/a518143322f2c06b366a3489f1ce2ac38d298db8/istioctl/pkg/analyze/analyze.go#L493) method).
@hanxiaop wdyt?

**Comment by AnirbanNandi** [comment]
@hanxiaop did you have a chance to take a look at this?

Using the user-input kubeconfig instead of remote secrets would also solve [this issue](https://github.com/istio/istio/pull/51843#discussion_r1677370305) that we were discussing.

**Comment by nmittler** [comment]
Yeah, agree with @costinm. istioctl shouldn't be accessing the remote secret. Not sure how the istioctl client (running outside of the cluster) should get the full list of contexts, or if the assumption is they already have it. @costinm can you expand your thoughts here?
