### ISSUE TITLE
SourceLabels don't filter out clusters.

### ISSUE THREAD

**Issue by Ferdudas97** [istio/istio#51936]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When in virtual service are routes with sourceLabels and workloads don't contain these labels then their envoys don't receive these routes, but they still receive clusters for them. IMO this behavior is a bug, because these clusters are unroutable so it produces unnecessary memory footprint.

### Version

```Text
istioctl
client version: 1.22.2
control plane version: 1.22.2
data plane version: 1.20.1 (9 proxies), 1.22.2 (823 proxies)
```

**Comment by howardjohn** [comment]
By default there is no filtering at all. Do you mean you have a Sidecar that imports only the VS and the not the service (which we implicitly import the Service for), and sourceLabels is not taken into account there?

Can you give more info?

**Comment by wulianglongrd** [comment]
I guess what he meant was:

Envoy's execution order is RDS -> CDS. When `sourceLabels` is used, some of the RDS routes will be filtered, which may cause some CDS to be unreachable. If istio filters these unreachable CDS and does not send them to envoy, it can reduce the memory consumption of the data plane.

Because multiple RDS routers can point to the same CDS, and CDS is sent before RDS, it seems that implementing this filtering is not easy.

**Comment by howardjohn** [comment]
I get that but the default is there is no filtering of clusters at all. So why is the focus on sourceLabels?

**Comment by wulianglongrd** [comment]
Maybe not every istio user understands the implementation of istio. Since sourceLabels can filter routes, it is natural to think that it can also filter out unreachable CDS? I am just guessing.

However, I think this requirement seems reasonable 😊.

**Comment by howardjohn** [comment]
I agree it's fairly natural to want to filter clusters - just trying to understand why (or if) it should be *only* based on sourceLabels or more generally and the OP only noticed for sourceLabels

**Comment by Ferdudas97** [comment]
@howardjohn yes, I have a huge and very custom kubernetes clusters setup. Each service has own Sidecar, which points to some Virtual Services. Some virtaul services have a lot of routes and not all clients needs them. According to documentation sourceLabels and sourceNamespace can restrict where this routes can be send (istiod filters them during creation of RDS routes). My expected behavior is to not send the clusters if they are not reachable.


IMO (I don't know well Istio's code) it will be easy to implement.
In [code](https://github.com/istio/istio/blob/master/pilot/pkg/model/sidecar.go#L442) responsible for creation of clusters the destinations from VS are copied to service list, without any filtering. There should be a similar filtering logic as it is in routes creation - [code](https://github.com/istio/istio/blob/3727b5719435c0cb4146413ac02ac16f8378cd36/pilot/pkg/networking/core/route/route.go#L460).

**Comment by howardjohn** [comment]
Ok yeah, thanks for the clarifying.

One problem is the SidecarScope being computed is for a specific namespace. The same object is shared by name pods with arbitrary labels. So we cannot just implement filtering in virtualServiceDestinations (maybe for sourceNamespace, but not sourceLabels). It would have to be filtered at a later step which may be problematic

**Comment by Ferdudas97** [comment]
I dived into this code and i have some idea. Can you vaildate that? 
Instead of storing the SidecarScope in sidecarIndex, we can store there a SidecarScopeFactory or smth like that, which will be responsible for creation of a proper SidecarScope during assigning SidecarScope to the Proxy - [code](https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L492).  Thanks to that we can parametrize this process by Proxy labels

**Comment by howardjohn** [comment]
In theory it could work perhaps but I'm not sure it will be viable from a performance standpoint. SidecarScope is one of the top bottlenecks in the system in terms of memory (to store) and cpu (to compute)

**Comment by Ferdudas97** [comment]
Are there performance tests that can be executed to confirm the impact of the changes? Are you giving the green light for implementation and merging if the performance tests are satisfactory?

**Comment by howardjohn** [comment]
I would be very worried about even the code complexity of such a change to build SidecarScope on-demand, let alone the performance. This is the number 1 source of bugs and performance issues in Istio in past experience, so its highly sensitive. While I understand to your specific setup the optimization is highly important, to the broader userbase its a very niche optimization; we need to heavily take into account the cost vs benefit profile.

FWIW, there are plenty of other cases where 'dead' clusters are created in Istio today: https://github.com/istio/istio/issues/45979 for instance.

Do you specifically need to use sourceLabels? Does sourceNamespaces meet the use case?

**Comment by Ferdudas97** [comment]
hmm, with sourceLabels it would be easier for us but with sourceNamespaces it is doable :D. Can I implement this filtering for namespaces?

**Comment by howardjohn** [comment]
Actually now that I think about it, if you can do sourceNamespaces I think you could probably also do `exportTo` on the virtual service? I think that optimization already exists.

if not, the filtering for sourceNamespaces I think should be fine, unless there are any edge cases I am not thinking of that come up. But it seems it should be ok as we are computing sidecarScope for each namespace, then we can just ignore VS where we know can never apply to us.

**Comment by Ferdudas97** [comment]
It is very custom edge case and limiting visibility at virtualService level will not help :D. Only `networking.istio.io/exportTo
` at service level can solve our problem but it is problematic to implement on our side. From our perspective sourceNamespace is a good compromise between sourceLabels and this exportTo.
