### ISSUE TITLE
registry hub does not change upon upgrading istio

### ISSUE THREAD

**Issue by namgk** [istio/istio#51930]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We had istio 1.19 installed with `--set hub=<our reg>/<reg namespace>`. 

You can see it's running properly as follow:

```
kubectl describe pod -n cert-manager cert-manager-869bb674db-vfnsx | grep -A 5 istio-init:
  istio-init:
    Container ID:  containerd://990fef0bba09b2d15290e8a5386d00d4a8c2f0665d245f32626ca1f968b0cac3
    Image:         <our reg>/<reg namespace>/proxyv2:1.19.0
    Image ID:      <our reg>/<reg namespace>/proxyv2@sha256:81367b09a42ea93fe75063d6bb84da98c09178483d2472a83569080710ad5d26
    Port:          <none>
    Host Port:     <none>
```

I took a sample describe of the cert-manager pod and saw that istio injected the istio-init container into this pod with the correct private registry image.

Now we do an upgrade of istio by reinstall with a new version (1.21.2) and set a new hub config (namespace removed): `--set hub=<our reg>`.

Istiod is correctly upgraded:

```
kubectl describe pod -n istio-system istiod-7d4ddbf655-brfhh | grep Image:
    Image:         <our reg>/pilot:1.21.2
```

However, when cert-manager is rotated to pick up the change, it still uses the namespaced registry, with the new image tag:

```
kubectl describe pod -n cert-manager cert-manager-869bb674db-lvnsp | grep -A 5 istio-init:
  istio-init:
    Container ID:  containerd://1e16a28b5242fdf7f31eb095078c8b4b1fa537ec7063f80e6d6314c6bff9d93b
    Image:         <our reg>/<reg namespace>/proxyv2:1.21.2
    Image ID:      <our reg>/<reg namespace>/proxyv2@sha256:7167f5de13d08921fd848afcc907baff71b5cd7036df307e69ea9f9fcb3bebf0
    Port:          <none>
    Host Port:     <none>
```

This caused ImagePull error cause the image was pushed to the non-namespaced location from our setup. We had to manually place them in the namespaced location to fix it.

### Version

```Text
istioctl version
client version: 1.21.2
control plane version: 1.21.2
data plane version: 1.19.0 (45 proxies), 1.21.2 (22 proxies)

kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-gke.1019001
```

### Additional Information

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.21.2", GitRevision:"ed90e14d3473bc3fe54f98298eb16664002d14d1", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.21.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.21.2, 1.19.0}

**Comment by howardjohn** [comment]
Thanks for the report. Was the install with helm or istioctl?

**Comment by howardjohn** [comment]
```shell
crane cp istio/pilot:1.19.0 localhost:5000/nested/pilot:1.19.0
crane cp istio/proxyv2:1.19.0 localhost:5000/nested/proxyv2:1.19.0
crane cp istio/pilot:1.21.2 localhost:5000/pilot:1.21.2
crane cp istio/proxyv2:1.21.2 localhost:5000/proxyv2:1.21.2
~/istio/istio-1.19.0/bin/istioctl install -y --set hub=localhost:5000/nested
~/istio/istio-1.21.2/bin/istioctl install -y --set hub=localhost:5000
```

I tried above, I could not replicate. I think we need some more info. `kubectl  -n istio-system  get cm istio-sidecar-injector -oyaml` is a good start

**Comment by howardjohn** [comment]
Any more info on this?
