### ISSUE TITLE
`cni` and `pilot` Helm charts use confusing scopes

### ISSUE THREAD

**Issue by bleggett** [istio/istio#51944]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Unlike our other charts, `istio-cni` and `pilot`/`istiod` charts do not rely on normal Helm prefixing/scoping patterns, and instead forcibly add their own prefixes to all Helm values - `cni` and `pilot` respectively.

What this means is you have to do something like

`helm install istio-cni istio/cni -n istio-system --set cni.foo` to override the value `foo` for this chart.

This

- is strictly unnecessary
- is bad/atypical Helm UX
- doesn't address the problem from the perspective of the user (they care about consistency _across_ charts, because they install multiple charts to "install Istio" - and having to remember that chart A does things one way and chart B does them another is silly)
- doesn't compose nicely with the regular Helm value scoping, e.g. if you try to compose the above chart as a dependency named `cni` - you would have to set the value like so, as it is double-scoped: `--set cni.cni.foo`
- the source of more than one bug related to values being applied and used consistently (or not) across charts
- The `ztunnel` chart is better (ish) because it's newer, but it does little good to have 1 model chart if the users have to install 3 others that are not model charts and work differently in confusing ways.

Instead it should be 

`--set foo`

and `--set <helmscope>.foo` respectively - we should not introduce our own chart-global scope for a single-app/single-image chart. 

We should seek to deprecate this.

### Version

```Text
N/A
```

### Additional Information

Effectively, not doing this (incrementally or otherwise) blocks https://github.com/istio/istio/issues/52034 (or, if not totally blocks, at least makes it much harder).

**Comment by bleggett** [comment]
There are two ways to solve this problem - one of them incremental, the other all-at-once.

In the incremental approach, we identify the most common things that are overridden _across_ charts, such as

- labels
- annotations
- image URLs

and tackle them one-at-a-time, until only the ones that are highly subcomponent-specific (e.g. `pilot.trustedZtunnelNamespace`) and therefore less commonly set by users, are left under the deprecated scope.

We can do this with shared `sprig` templating, such as https://github.com/istio/istio/pull/51517/files#diff-9e517c2405d381930226cbdc5b4ec16976f5c4939bc34bc145214a71df658be2R87

Benefits:

- Can be done in stages/incrementally, without adding any new Helm values to the public API surface we that we would need to deprecate if we decided on different approaches to achieve the same effect.
- Addresses the problem from the perspective of the user ("I install istio using multiple charts in all cases, so UX behavior hiccups _across_ charts are what I see and care about"
- Addresses the underlying root cause of the UX issues by relying on central templates for each of the above "groups" of common things for discipline and consistency - not developers, which are, as a species, poor at both.

Downsides:

- It's done in stages, so while the most commonly-used values will incrementally "get better", some of the less-used ones will still have the old scoping, which can cause additional confusion for people that set both.

---
Or we can do this `all-at-once`

Benefits:
- It's NOT done in stages, so the scopings will change all at once, leading to less confusion for the subset of people that override the "common" values as well as the unique/less-commonly-used ones.

Downsides:

- Can't be done incrementally, meaning it is both less likely to be done soon, or at all.
- Can't be done incrementally, so if the mechanism we use to accomplish the descoping doesn't work or has corner cases that do not work (composition, etc), it's harder to correct and fix.

**Comment by therealmitchconnors** [comment]
Do you know why this scoping was added in the first place?  Was it required for splitting the helm charts out from one massive chart a while back?

**Comment by bleggett** [comment]
> Do you know why this scoping was added in the first place? Was it required for splitting the helm charts out from one massive chart a while back?

I suspect it was, or something like that.

I know for a fact we can "undo" the scoping in a backwards-compatible way for most of the values, since I already did that for the purposes of doing image templating in https://github.com/istio/istio/pull/51517

It's mostly just a question of "undo them all at once" in that fashion, or undo them chunk by chunk, starting with the major/common ones (image values, tags, annotations, etc)

**Comment by Stevenjin8** [comment]
@bleggett @therealmitchconnors I'm interested in working on this. Do we have consensus on how to approach it? I don't have enough experience to have an opinion.

**Comment by therealmitchconnors** [comment]
That's great!  For my part, I prefer the incremental approach for safety reasons...

**Comment by bleggett** [comment]
@Stevenjin8 and @therealmitchconnors 

John took this on, did it in one go, and I think we're in a good spot now - PTAL https://github.com/istio/istio/pull/52036


@Stevenjin8 if you still want something in this area - https://github.com/istio/istio/issues/52034 is the next bit, if you are interested!

**Comment by Stevenjin8** [comment]
Going to close this them
