### ISSUE TITLE
Ambient AKS: Failed to initialize key-value store of network plugin: error Acquiring store lock: timed out locking store

### ISSUE THREAD

**Issue by lapaartis** [istio/istio#51965]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have an AKS cluster with network setup Azure CNI + Calico + Istio CNI + Istio Ambient mesh.

At some point, multiple pods stopped starting in stuck in a pending state on 1/2 of nodes with the following errors in the pod description:
```
Type     Reason                  Age                   From               Message
----     ------                  ----                  ----               -------
Normal   Scheduled               23m                   default-scheduler  Successfully assigned mynamespace/mypod-1720448400-main-593210081 to aks-pool-27018240-vmss000000
Warning  FailedCreatePodSandBox  23m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f0ae639770de48129b63c1143857e140098daafe228f1226396fd17605071407": plugin type="azure-vnet" failed (add): Failed to initialize key-value store of network plugin: error Acquiring store lock: timed out locking store
Warning  FailedCreatePodSandBox  20m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c3c9c19581df06b0918359ce97a127f84ac250f869f6f313c3bdf36a2431bc58": plugin type="azure-vnet" failed (add): Failed to initialize key-value store of network plugin: error Acquiring store lock: timed out locking store
Warning  FailedCreatePodSandBox  16m (x2 over 17m)     kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to reserve sandbox name "mypod-1720448400-main-593210081_mynamespace_cb1d47d2-96ba-494b-a143-e789eb9e030f_1": name "container-1720448400-main-593210081_mynamespace_cb1d47d2-96ba-494b-a143-e789eb9e030f_1" is reserved for "c3c9c19581df06b0918359ce97a127f84ac250f869f6f313c3bdf36a2431bc58"
Normal   SandboxChanged          3m13s (x56 over 23m)  kubelet            Pod sandbox changed, it will be killed and re-created.
```
After the node drains and migrates to the new node these pods starting normally and have completed status, but after a few hours issue appears again!
Making some adjustments and trying to identify what caused such behavior, I noticed that just restarting `istio-cni` on that single node all affected pods from pending status start working and complete!

Affected pods are only those that were started by argo-workflow but regular deployment pods are working fine.
---
Configuration
```
# Istio Helm chart values
cni:
  ambient:
    enabled: true

  excludeNamespaces:
    - istio-system
    - kube-system
```

Let me know if more information and any specific logs are required.

### Version

```Text
$ istioctl version
client version: 1.22.1
control plane version: 1.22.2
data plane version: 1.22.2 (13 proxies)
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

### Additional Information

Noticed that prometheus node-exported cpu/ram metrics are empty during period of issue until `istio-cni` pod restarted and in Logs dozen:
```
caller=stdlib.go:105 level=error caller="error encoding and sending metric family: write tcp 10.9.140.171:9100" msg="->10.9.136.27:43520: write: broken pipe"
```
List of system and service pods on that node:
```
NAMESPACE↑                NAME
calico-system             calico-node-hxcnx
istio-system              istio-cni-node-clj96
kube-system               ama-logs-2pnx8
kube-system               azure-ip-masq-agent-2dp28
kube-system               cloud-node-manager-fdf2r
kube-system               coredns-5b76c476bc-smgwk
kube-system               csi-azuredisk-node-jcsx6
kube-system               csi-azurefile-node-xnp98
kube-system               konnectivity-agent-7b88b55d57-sw2xt
kube-system               kube-proxy-sxhh8
monitoring                prometheus-kube-state-metrics-6dbb45b896-lfkxj
monitoring                prometheus-prometheus-node-exporter-zbzj2
monitoring                promtail-lplwl
```

**Comment by howardjohn** [comment]
So..

`Warning  FailedCreatePodSandBox  23m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f0ae639770de48129b63c1143857e140098daafe228f1226396fd17605071407": plugin type="azure-vnet" failed (add): Failed to initialize key-value store of network plugin: error Acquiring store lock: timed out locking store`

is from the Azure CNI. There are a few ways I could see Istio making this fail:
* Our CNI plugin runs before it, and something we do breaks it. This can be verified by reading the CNI configuration on the node. CNI will log something like `MountedCNINetDir: /host/etc/cni/net.d` that can show you where it is (note the /host prefix is where it is in the CNI pod, on the host it would just be /etc/...)
* Our CNI plugin modifies the node networking in some way that messes with azure-vnet. I doubt this is the case
* Something azure-vnet depends on is in the mesh and there is a circular dependency...? Seems unlikely

cc @keithmattix @therealmitchconnors

**Comment by howardjohn** [comment]
Are you still seeing this issue? Did you find any more info?

**Comment by keithmattix** [comment]
Sorry I completely missed this; I will take a look on compatibility here

**Comment by jaellio** [comment]
Hi @lapaartis! I have a few questions:
- Could you share more about your Argo workflow? 
- Could you also confirm that you are only seeing these failures with Argo managed workloads? 
- How much workload churn is expected in your cluster? Is it expected that pods are being creating and deleted frequently? Is this in response scaling or do they execute short lived tasks?
- What is the frequency of these failures?

**Comment by jaellio** [comment]
@lapaartis I am going to close this issue for now. Please reopen it if the issue is still ongoing. Thanks!
