### ISSUE TITLE
Clean up operator API fields

### ISSUE THREAD

**Issue by dgn** [istio/istio#51987]
We have a bunch of fields in the Operator API that have long been removed from the helm charts and have no effect anymore. I'm going through the proto file to find anything that is unused and will link removal PRs here. At the end, I'll create a release note listing all the removed fields.

### PilotConfig
- [x] https://github.com/istio/istio/pull/51984
- [x] https://github.com/istio/istio/pull/51986
- [x] https://github.com/istio/istio/pull/51989
- [x] https://github.com/istio/istio/pull/51990

### GlobalConfig
- [x] https://github.com/istio/istio/pull/51994
- [x] https://github.com/istio/istio/pull/52596

### GatewayConfig
- [x] https://github.com/istio/istio/pull/51994

### SidecarInjectorConfig
- [x] https://github.com/istio/istio/pull/52058
- [x] https://github.com/istio/istio/pull/52083

### Release Note
- [ ] https://github.com/istio/istio/pull/52896

**Comment by howardjohn** [comment]
@dgn anything left? seems everything is checked off

**Comment by dgn** [comment]
> @dgn anything left? seems everything is checked off

Checking, but looking good for now. Will create PR with a release note shortly

**Comment by kolodziejczak** [comment]
It looks like those PRs were merged before `release-1.23` cutoff. Does it mean that those fields were removed already in 1.23, but the release notes are delayed to 1.24? @howardjohn @dgn
