### ISSUE TITLE
Istio installation initialization error

### ISSUE THREAD

**Issue by smallemployees** [istio/istio#51980]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

failed to create "EnvoyFilter/istio-system/stats-filter-1.16": Internal error occurred: failed calling webhook "rev.validation.istio.io": failed to call webhook

### Version

```Text
1.16
```

### Additional Information

Why did it still prompt an error on webhook? How should I handle it

**Comment by zirain** [comment]
Have you installed istio before? Whether it was cleaned up?

**Comment by howardjohn** [comment]
Istio 1.16 has been EOL for a long time now. Please upgrade and if you are still seeing the issue, include the full error (it is clearly truncated here which makes this impossible to help).
