### ISSUE TITLE
Failure to install 1.22.x (since 1.21.x) using Helm v3.7.1

### ISSUE THREAD

**Issue by dio** [istio/istio#52016]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Since this PR https://github.com/istio/istio/pull/48249/files is merged, installing the istiod chart using Helm v3.7.x (actually since v3.6.x, as mentioned in the Istio docs, https://istio.io/latest/docs/setup/install/helm/#prerequisites the prerequisite is helm >= v3.6) is failing with the following error.

```console
Error: template: istiod/templates/NOTES.txt:8:8: executing "istiod/templates/NOTES.txt" at <eq .Values.profile "ambient">: error calling eq: incompatible types for comparison
```

Given helm v3.7.x and v3.6.x do not handle type checking as gracefully as newer versions, we would need to ensure that `.Values.profile` is explicitly set to a string.

```console
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
$ helm upgrade -i istiod tetratelabs/istiod --version 1.22.2
Error: UPGRADE FAILED: template: istiod/templates/NOTES.txt:8:8: executing "istiod/templates/NOTES.txt" at <eq .Values.profile "ambient">: error calling eq: incompatible types for comparison
```

### Version

```Text
$ helm version --short
v3.7.1+g1d11fcb
```

### Additional Information

> For information, Helm v3.8 has this "behavior" fixed

## Current workaround

Given helm v3.7.x and v3.6.x do not handle type checking as gracefully as newer versions, we would need to ensure that `.Values.profile` is explicitly set to a string.

One can set the profile field to an empty string as a workaround to make helm v3.7.x and v3.6.x work. It will install Istio with the “default” behavior for that version. Please check on: https://github.com/istio/istio/blob/1.22.2/manifests/zzz_profile.yaml#L21.

We can however introduce a fix to make it work for helm v3.6.x and v3.7.x, i.e. by adding the following:

```diff
diff --git a/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt b/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
index 0771b919d3..1d7e589b4d 100644
--- a/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
+++ b/manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
@@ -5,7 +5,8 @@ To learn more about the release, try:
   $ helm get all {{ .Release.Name }} -n {{ .Release.Namespace }}
 
 Next steps:
-{{- if (eq .Values.profile "ambient") }}
+{{- $profile := default "" .Values.profile }}
+{{- if (eq $profile "ambient") }}
   * Get started with ambient: https://istio.io/latest/docs/ops/ambient/getting-started/
   * Review ambient's architecture: https://istio.io/latest/docs/ops/ambient/architecture/
 {{- else }}
```

WDYT?

**Comment by dio** [comment]
cc. @zirain

**Comment by zirain** [comment]
sgtm, can you raise an PR?

**Comment by dio** [comment]
@zirain I have submitted it here: https://github.com/istio/istio/pull/52017

**Comment by jacob-delgado** [comment]
Helm 3.6 was released in May 2021. Any reason why you cannot use a later version? A more appropriate change is to do update the docs to use something like Helm 3.14
