### ISSUE TITLE
Out of the box Istio install in AKS blocks internal traffic between services

### ISSUE THREAD

**Issue by kpmg-bengmoody** [istio/istio#52064]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm assuming there's some default behaviour here, as I'm still experiencing this in 2024. Have tried many of the above solutions.

I have a vanilla AKS cluster with Istio enabled via the menu. I have made a new NS called bendev which has istio injection enabled via the label istio.io/rev: asm-1-20

The sidecars are injecting ok, but no matter which combination of the above solutions I try my internal services can't communicate.

I notice that by default there is no "catch-all" listener on 0.0.0.0:443 for TLS traffic. This may be why I can't communicate to the API service without excludeIPs (this is the 1 solution that works). I don't really want to start moving traffic out of the mesh, however. I would rather figure out why this is happening.

I created some basic services, such as an nginx-deployment consisting of 3 replicas, behind a simple ClusterIP service.
I also created a long lived process pod which curls a bunch of internal service endpoints, then sleeps, to allow me the chance to exec into it. I'll call this netshoot

When using exec into the terminal, I can curl everything quite happily using the exact .  I am assuming this sidesteps Istio somehow.

However, when relying on the script, all of the curls fail (unless using excludeIPs) including the curl to the internal svc, nginx-deploy.bendev.svc.cluster.local:80

I can see a route for this does exist in the proxy config for the netshoot pod out of the box, due to this deployment having been created "on the watch" of istio

I have tried making a service entry to cover the kubernetes API, using location EXTERNAL/INTERNAL and resolution DNS/STATIC/NONE whilst switching the address to the local address for the kubernetes.default.svc server within the cluster (for me it is 10.0.0.1)

I have tried to make a custom sidecar but I couldn't get it to inject, as per
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: aks-istio-system
spec:  
  egress:
    - hosts:
        - ./*
        - default/kubernetes.default.svc.cluster.local
        - default/etcd.default.svc.cluster.local
        - aks-istio-system/*

I have also tried a virtual service in addition to the service-entry above, to create a listener on 0.0.0.0/443 and a route

None of these things worked, and the script itself always fails

There are no authorization policies or peerauthentication requirements across the cluster.

I am also not getting any logs inside Envoy in the istio-proxy sidecar. Seems like my requests aren't even getting that far.

### Version

```Text
$ istioctl version
client version: 1.22.2
control plane version: 1.22.2
data plane version: 1.22.2
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.10
```

**Comment by keithmattix** [comment]
What url are you curling when trying to access mesh services (from inside a meshed pod of course)?

**Comment by kpmg-bengmoody** [comment]
hello, for example http://nginx-deploy.bendev.svc:80 

> What url are you curling when trying to access mesh services (from inside a meshed pod of course)?

**Comment by keithmattix** [comment]
If you can curl your meshed service from a meshed pod, then istio is working as expected. Does NGINX have errors?

**Comment by kpmg-bengmoody** [comment]
But that's what I'm saying, I can't - the curl doesn't work when running from the script.

It only works when you manually exec in and run the same commands.  It doesn't work when running directly from the pod in an automated/scripted fashion.  This suggests to me that doing manual commands is somehow circumventing Istio.  
**When running from the script**
![image](https://github.com/user-attachments/assets/702e6e62-3dd7-47f4-9df0-32aeffa2f7c2)

![image](https://github.com/user-attachments/assets/91d4659d-48a1-4f50-9648-36e05cb14e30)
"Couldn't connect to server"

**When running manually**
![image](https://github.com/user-attachments/assets/c3e069de-8b66-417f-9f03-80fe8c2eb870)


I had thought maybe it is to do with some authentication issue - like it doesn't like the fact the user agent has less permissions than me, but like I say there's no AuthorizationPolicies in the cluster from Istio.

Any further advice?

**Comment by kpmg-bengmoody** [comment]
Ok, so it seems it was a pod authorization issue. Using runAsUser: 1000 in the security context works. I also realised I didn't have logs turned on so having turned these on, I can see Envoy is working as expected. Thanks for the help
