### ISSUE TITLE
failed to connect to server "/var/run/ztunnel/ztunnel.sock"

### ISSUE THREAD

**Issue by piotrwasilewski420** [istio/istio#52077]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I installed ztunnel with helm chart with this command `helm install ztunnel istio/ztunnel -n istio-system --wait` and it deployed to the cluster but the ztunnel pods itself are not healthy because they fail to connect to a server. All information that I get from the logs is `inpod::workloadmanager    failed to connect to server "/var/run/ztunnel/ztunnel.sock": Os { code: 2, kind: NotFound, message: "No such file or directory" }.`  The most interesting thing is that it all works just fine when I install istio with `istioctl install --set profile=ambient` but we have already well established pipeline so obviously I want to install all components separately that is why I install everything via helm. I run k8s version 1.29.6 on my EKS cluster. Below logs from ztunnel pod
![image](https://github.com/user-attachments/assets/ec49ae69-1900-4ade-bf93-1b2092bae33f)

### Version

```Text
$ helm version --short
v3.14.1+ge8858f8
```

### Additional Information

I can't provide it due to compliance but it only shows me all of the resources that are not included into the mesh.

**Comment by edallastella** [comment]
Hello, I see the issue as completed but I'm getting the same error. Were you able to fix it?

**Comment by matihost** [comment]
I encountered the same issue when installed via helm
Minikube 1.33.1 K8S 1.30.0
and following https://istio.io/latest/docs/ambient/install/helm/

After I added `--set ambient.enabled=true` to Istio CNI helm installation then the ztunnel pod started  successfully.
