### ISSUE TITLE
Istio Bookinfo Sample App stuck with CrashLoopBackOff

### ISSUE THREAD

**Issue by spirrello** [istio/istio#521]
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**OS: Ubuntu 16.04 LTS**

Hi,

I'm running the Bookinfo deployment to test Istio and I keep getting the following errors.  Can you advise on how to fix this?

kubectl apply -f <(istioctl kube-inject -f applications/samples/apps/bookinfo/bookinfo.yaml -c /opt/kubernetes/kubeconfig)

Errors show up in the Details-v1 and Reviews-v1 apps.  These same errors were also happening in the Productpage-v1 app but have magically cleared.

**Errors**
failed to register Third-Party Resources. the server has asked for the client to provide credentials (get thirdpartyresources.extensions istio-config.istio.io)

* failed to register Third-Party Resources. Failed to create all TPRs

TPR "IstioConfig" is not ready (the server has asked for the client to provide credentials (get IstioConfigs.istio.io)). Waiting...

**Comment by vadimeisenbergibm** [comment]
Do you have Istio components [installed](https://istio.io/docs/tasks/installing-istio.html) and running? Do you see Istio _pilot_, _mixer_, _ingress_ and _egress_ pods when you run `kubectl get pods`?

**Comment by spirrello** [comment]
Yes sir.

kubectl get pods
NAME                              READY     STATUS             RESTARTS   AGE
details-v1-1192410764-bxr2q       1/2       Error              20         1h
grafana-4175437752-698sj          1/1       Running            0          3h
istio-egress-2735314046-z46kk     1/1       Running            0          3h
istio-ingress-3331978175-hh1lx    1/1       Running            0          3h
istio-mixer-2598054512-0jpzf      1/1       Running            0          3h
istio-pilot-1027118154-rh3mk      2/2       Running            0          3h
istio-pilot-1027118154-tsxqt      2/2       Running            0          3h
productpage-v1-1863041972-ctlj4   2/2       Running            0          1h
prometheus-3208567892-gx48j       1/1       Running            0          3h
ratings-v1-1419296450-zmsfs       2/2       Running            0          3h
reviews-v1-2290728681-whwpk       1/2       CrashLoopBackOff   20         1h
reviews-v2-2818948843-lscgd       2/2       Running            0          3h
reviews-v3-3347169005-vmkrc       2/2       Running            0          3h
servicegraph-3117540837-03gx8     1/1       Running            0          3h
zipkin-722223511-jgztd            1/1       Running            0          3h

**Comment by ldemailly** [comment]
looks like an auth/rbac problem possibly - is that using istio 0.1.6 with k8s 1.6.x or 1.7.x ?

if still an issue please reopen under
https://github.com/istio/issues/issues
