### ISSUE TITLE
xClusterStatName new variables

### ISSUE THREAD

**Issue by Ferdudas97** [istio/istio#52177]
**Describe the feature request**
There should be a new variables, which can be used in inboundClusterStatName/outboundClusterStatName:
%SERVICE_NAME% - Will be substituted with name of the service.
%SERVICE_NAMESPACE% - Will be substituted with namespace of the service.

It gives more flexibility in defining patterns.
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
In our k8s kubernetes setup the service foo can be present in many namespaces and have to be treated as the same service (for this purpose we aggregate them behind one virtualservice) - but each pair of service name and namespace is a different envoy cluster and have different name in metrics which have huge impact on cardinality of these metrics. Having a option to configure envoy altStatName with the same value (using only %SERVICE_NAME%) for these clusters will reduce it dramatically.

**Comment by ramaraochavali** [comment]
But this is a mesh wide config. How will you set for specific service? If you really need %SERVICE_NAME% makes sense. Why do you need ONLY %SERVICE_NAMESPACE%?

**Comment by Ferdudas97** [comment]
okay, so can i prepare a pr with addition of this %SERVICE_NAME%?

**Comment by ramaraochavali** [comment]
yes
