### ISSUE TITLE
Error: failed to convert to proto. unknown field "interceptionMode" in v1alpha1.ProxyConfig

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#5218]
I got the below error when injecting envoy sidecar to bookinfo application:

ubuntu@istio-k8s-master:~$ istioctl kube-inject -f istio-0.7.1/samples/bookinfo/kube/bookinfo.yaml
Error: failed to convert to proto. unknown field "interceptionMode" in v1alpha1.ProxyConfig

ubuntu@istio-k8s-master:~$ istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
BuildStatus: Clean

**Comment by rshriram** [comment]
old code with new config format .. interceptionMode was introduced after 0.7.1

**Comment by ostromart** [comment]
Please retry with recent version and reopen if issue persists.

**Comment by coolboi567** [comment]
I encountered similar issue today.
```
$ istioctl kube-inject -f dev-deployment.yaml
Error: failed to convert to proto. unknown field "tracing" in v1alpha1.ProxyConfig
```

With the latest version of istioctl:
```
$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Comment by marcstreeter** [comment]
getting the same exact error as @coolboi567 

```
$  istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Comment by marcstreeter** [comment]
For me (using a helm managed setup) I followed these steps:
*more than likely you're passed the sample book application and on to greater things but this helped me who **is** still at this point and was hitting the same error you mentioned above*

Cleared Istio completely out by:

### removing istio helm managed packages
```
helm del --purge istio-init
helm del --purge istio
# either of these may not be present depending on how you deployed previously
# probably should just inspect what helm managed packages you have with 'helm list'
```

### removing helm istio repository

```
helm repo remove istio.io
# you may have named it differently (and you may not even have a repo for istio)
```

### removing  istio crds
```
kubectl delete $(kubectl get crds -o name)
#  This clears out all crd’s — currently I only have istio crds so I’m ok with using it
```

### removing istio namespace
```
kubectl delete ns istio-system
# you may have named your istio namespace differently)
```

### check out fresh clone of git repo at correct tag (at the time of this writing that is 1.0.5)
```
git clone https://github.com/istio/istio.git
cd istio
git checkout tags/1.0.5
```

### deploy istio 1.0.5 with helm
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set grafana.enabled=true \
  --set kiali.enabled=true \
  --set tracing.enabled=true \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set gateways.istio-egressgateway.type=NodePort 
```
*You may want to have different options, but I'm only investigating istio (for onprem reasons) for now so this is my set up*

*the `kiali` container may be failing if a secret hasn't been created, [refer to docs here](https://preliminary.istio.io/docs/tasks/telemetry/kiali/#before-you-begin ) or don't include it.

### deploy book app
```
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)
```
results in

```
service/details created
deployment.extensions/details-v1 created
service/ratings created
deployment.extensions/ratings-v1 created
service/reviews created
deployment.extensions/reviews-v1 created
deployment.extensions/reviews-v2 created
deployment.extensions/reviews-v3 created
service/productpage created
deployment.extensions/productpage-v1 created
```

**Comment by coolboi567** [comment]
@marcstreeter I had to do the same. Did a fresh installation after completely removing it. I am sorry that I forgot to tell about it here.
