### ISSUE TITLE
SimpleLBPolicy has no effect?

### ISSUE THREAD

**Issue by fleeto** [istio/istio#522]
I'm trying to eject a pod which will return a status code of 500.

There are 4 pods in the deployment, 3 of them will return 500, the other 1 will return 200.

I'd create the default route-rule for a service named "svc-frontend":

~~~yaml
type: route-rule
name: frontend-default
spec:
  destination: svc-frontend.default.svc.cluster.local
  precedence: 1
  route:
  - tags:
      version: "1"
~~~

And then create a CircuitBreaker:

~~~yaml
type: destination-policy
name: httperror
spec:
  destination: svc-frontend.default.svc.cluster.local
  policy:
  - tags:
      version: "1"
    circuitBreaker:
      simpleCb:
        httpConsecutiveErrors: 1
        httpDetectionInterval: 5m
        sleepWindow: 1m
        httpMaxEjectionPercent: 100
    loadBalancing:
      name: RANDOM
~~~

According to the document, when I'm accessing the service, I will see a little response of  500, and then I will get only 200,  But I still get 500 constantly( about 75%). 

What's wrong with my configuration?

~~~
istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1


apiserver version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
~~~

**Comment by jhaals** [comment]
Stumbled on the same thing, any takers?

**Comment by kyessenov** [comment]
Let me try to reproduce it.

**Comment by kyessenov** [comment]
Issue moved to [istio/pilot #1054](https://github.com/istio/pilot/issues/1054) via [**ZenHub**](https://www.zenhub.com/)
