### ISSUE TITLE
GetProxyServiceTargets is iterating all the endpointslices of the namespace

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#52214]
https://github.com/istio/istio/blob/33539491628fe5f3ad4f5f1fb339b0da9455c028/pilot/pkg/serviceregistry/kube/controller/endpointslice.go#L159-L167

While it is seraching all endpointslice one by one, this is very expensive. The total cost is O(n * m), n means the total proxies  connected, while m is the endpoints number of a namespace.  

GetProxyServiceTargets is frequently called, may once push per proxy.

**Comment by hzxuzhonghu** [comment]
@howardjohn

**Comment by howardjohn** [comment]
Agreed but FWIW this is only called here: https://github.com/istio/istio/blob/dbdb9522d34c2c3c0e272933879ec018968532ad/pilot/pkg/serviceregistry/kube/controller/controller.go#L856

Although this is also probably a bug -- its possible for a single workload to have a Service with selector and without.

This would be very easy to solve with `krt` but is pretty tricky to solve without.

**Comment by hzxuzhonghu** [comment]
I did think a little about how to optimize it, but could not think of a good way. 😕
