### ISSUE TITLE
Isiod is missing profiles

### ISSUE THREAD

**Issue by PeterBasista** [istio/istio#52219]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Based on documentation found here https://istio.io/latest/docs/setup/additional-setup/config-profiles/ and https://artifacthub.io/packages/helm/istio-official/istiod#profiles we are able to use `--set profile=<profile>`. Using this feature will allow only some components to be installed using HELM. The problem is that while using this option we are having issue with:
`Error: UPGRADE FAILED: execution error at (istiod/templates/zzz_profile.yaml:25:3): unknown profile minimal`

Upon investigation we found that problem is comming from zzz_profile.yaml line 25 which is in this case `else` https://github.com/istio/istio/blob/master/manifests/charts/istiod-remote/templates/zzz_profile.yaml#L25
Based on code from line 23 the `if` is looking for file in `files/profile-<profile>.yaml`
https://github.com/istio/istio/blob/master/manifests/charts/istiod-remote/templates/zzz_profile.yaml#L23

But minimal profile as described in the official docs are missing there (no profile-minimal.yaml file)
https://github.com/istio/istio/tree/master/manifests/charts/istiod-remote/files

### Version

```Text
HELM ls
istio-base 1.22.2
istiod  1.22.2

kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7
```

**Comment by howardjohn** [comment]
This is intentional but a documentation issue.

`minimal` doesn't make sense for Helm, as in Helm you explicitly install each component individually. The minimal profiles only role was to NOT enable components, as `istioctl install` bundles them all together

**Comment by PeterBasista** [comment]
> This is intentional but a documentation issue.
> 
> `minimal` doesn't make sense for Helm, as in Helm you explicitly install each component individually. The minimal profiles only role was to NOT enable components, as `istioctl install` bundles them all together

That make perfect sense. I was also wondering what is the meaning for it in HELM and now I know. Thanks for clarification!

**Comment by up9t** [comment]
```bash
helm install istiod istio/istiod --namespace istio-system --set profile=default
```
Error: INSTALLATION FAILED: execution error at (istiod/templates/zzz_profile.yaml:31:3): unknown profile default

the documentation here was misleading

<img width="1156" height="466" alt="Image" src="https://github.com/user-attachments/assets/32e3c903-c274-4710-85c7-06bcee9eda83" />
