### ISSUE TITLE
Missing documentation on HTTPRoute rule limits

### ISSUE THREAD

**Issue by kovaxur** [istio/istio#52225]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to set up the ambient mesh in our test system with the use of the Kubernetes Gateway API.

We have some services, which expose a lot of endpoints (most is 60), and when I generate the HTTPRoute objects, I receive one of the following errors:

When I try to add 1 rule per endpoint:
`Error from server (Invalid): HTTPRoute.gateway.networking.k8s.io "XXXX-api" is invalid: [spec.rules: Too many: 60: must have at most 16 items, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]`

When I try to add one match per endpoint under only one rule:
`Error from server (Invalid): HTTPRoute.gateway.networking.k8s.io "XXXX-api" is invalid: [spec.rules[0].matches: Too many: 60: must have at most 8 items, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]`

I can't find any limitation like this in either the Istio or the Kubernetes Gateway API documentation, can you please extend the documentation to include these?

### Version

```Text
client version: 1.22.1
control plane version: 1.22.3
data plane version: 1.22.3 (45 proxies)

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

**Comment by howardjohn** [comment]
This ultimately comes from https://github.com/kubernetes-sigs/gateway-api/issues/3209. I've opened a copy of this in that repo, so I think we can close this and track there?

Thanks for the feedback!
