### ISSUE TITLE
bug: 0.7.1 can not access service after route all to v1

### ISSUE THREAD

**Issue by ccx1024cc** [istio/istio#5223]
i am trying 0.7.1
i am trying examle(bookinfo) : 
istioctl create -f samples/bookinfo/consul/route-rule-all-v1.yaml

but i see 
can not fetch detail info and reviews info

how can i make it work for rule injection example, guys?
note: i tried the solution for running bookinfo up, maybe it is related with this problem?
this is the solution link:
https://groups.google.com/forum/#!searchin/istio-users/consul%7Csort:date/istio-users/HF46YxrBu7I/gipnq5ZQCgAJ

This is the route log:
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: details-default
  namespace: default
  resourceVersion: "113"
spec:
  destination:
    service: details.service.consul
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: productpage-default
  namespace: default
  resourceVersion: "110"
spec:
  destination:
    service: productpage.service.consul
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: ratings-default
  namespace: default
  resourceVersion: "112"
spec:
  destination:
    service: ratings.service.consul
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  creationTimestamp: null
  name: reviews-default
  namespace: default
  resourceVersion: "111"
spec:
  destination:
    service: reviews.service.consul
  precedence: 1
  route:
  - labels:
      version: v1
---

**Comment by ostromart** [comment]
I need more information, could you please provide all the steps you took to create the cluster and install istio?

**Comment by sakshigoel12** [comment]
@ccx1024cc please upgrade to 0.8 and reopen this issue if you still notice this error
