### ISSUE TITLE
servicesDiff never reports unchangedSvcs, causes full push even only the endpoint is changed

### ISSUE THREAD

**Issue by spacewander** [istio/istio#52248]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In `serviceEntryHandler`, there is a method call that diffs the services:
https://github.com/istio/istio/blob/809f73e2b3aa1b3ffcd377a44bbdf07ce3ae6094/pilot/pkg/serviceregistry/serviceentry/controller.go#L379

If the services are unchanged (and with some other conditions), the change of ServiceEntry will trigger an incremental push. Otherwise, a full push is used.

Unfortunately, the servicesDiff will compare the auto allocated IPs:
https://github.com/istio/istio/blob/809f73e2b3aa1b3ffcd377a44bbdf07ce3ae6094/pilot/pkg/model/service.go#L1453

However, as the new services are freshly converted from ServiceEntry, their auto allocated IPs are always empty, which will cause the comparison to return false, even if the other fields are equal. So the new services are always not equal to the old one.

### Version

```Text
$ istioctl version
# A custom istio from istio 1.21, but the issue seems to exist in the main branch.
```

### Additional Information

The simplest way to fix the problem is not to compare the auto generated IPs. Since the IP is reused according to the service domain:
https://github.com/istio/istio/blob/809f73e2b3aa1b3ffcd377a44bbdf07ce3ae6094/pilot/pkg/serviceregistry/serviceentry/controller.go#L951-L969

So old and new services are the same, they will share the same IP after syncing the new service into the store.

**Comment by spacewander** [comment]
> Is it possible the new one gets a new IP allocated since the allocation isn't stable?

The allocation only happens in autoAllocateIPs function. Its comment says that the allocation is deterministic:
https://github.com/istio/istio/blob/809f73e2b3aa1b3ffcd377a44bbdf07ce3ae6094/pilot/pkg/serviceregistry/serviceentry/controller.go#L891-L892

This function allocates the IP according to the service key:
1. allocate the IP according to the hash of the service key
2. if two services have the same key, they will share the same IP

So if two services are the same except for the allocated IPs, they will have the same key, and will have the same IP later.

**Comment by howardjohn** [comment]
Services don't share the same IP, there is a conflict resolution mechanism to assign it a different one. So it's not a stable function but rather depends on the entire state of all services

**Comment by spacewander** [comment]
> Services don't share the same IP, there is a conflict resolution mechanism to assign it a different one. So it's not a stable function but rather depends on the entire state of all services

Could you give a link to the implementation? According to the implementation of autoAllocateIPs function, the IP is terminated by the service key (namespace + "/" + hostname). If two services have the same key, they will have the same IPs.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/809f73e2b3aa1b3ffcd377a44bbdf07ce3ae6094/pilot/pkg/serviceregistry/serviceentry/controller.go#L925

**Comment by spacewander** [comment]
> istio/pilot/pkg/serviceregistry/serviceentry/controller.go

Thanks for pointing it out. So it's a bit tricky to solve the problem. Let me think about it a little more.

**Comment by spacewander** [comment]
@howardjohn 
What do you think about moving the IP allocation from the read part to the write one?

We can allocate the IP only for the changed services in these two cases:
1. after all the services are first synced.
2. when some services are changed.

Here are the advantages:
1. the services allocated with IP won't be allocated with a new one, as hash collision only affects the new services. In the current implementation, since all services are allocated the IP at the same time, if there is a new service occupies a hash slot, the old service which uses this slot before will have to move to new one and use a new IP.
2. the complexity of the algorithm will be O(k) instead of O(n), while the k is the number of changed services and n is the number of total services.

**Comment by SpecialYang** [comment]
Istio is stateless, so I believe reallocation is the safest approach to avoid inconsistencies in cluster IPs across different replicas caused by Istio restarts or deployments.

**Comment by SpecialYang** [comment]
A ServiceEntry change event needs to trigger a full push because LDS or RDS also relies on the ServiceEntry.

**Comment by spacewander** [comment]
> A ServiceEntry change event needs to trigger a full push because LDS or RDS also relies on the ServiceEntry.

If only endpoints are changed, istio can only send an EDS push. In istio, there is already an optimization:
https://github.com/istio/istio/blob/eded0820fe3e3d4408a45451496b7bb1977abd4b/pilot/pkg/serviceregistry/serviceentry/controller.go#L452-L456

However, in the current implementation, if the ServiceEntry's addresses field is empty, it will never walk through the optimization field.

> Istio is stateless, so I believe reallocation is the safest approach to avoid inconsistencies in cluster IPs across different replicas caused by Istio restarts or deployments.

In fact, reallocation doesn't always avoid inconsistencies. Considering a case, we have services A & C:
A has IP 1.1.1.1, C has IP 1.1.1.2.

Then comes service B, because of hash collision, we allocate IP 1.1.1.3 to it.

When the istiod restarts, we reallocate the services in the order of A/B/C. Now B will have IP 1.1.1.2, and C will have IP 1.1.1.3, which is different from the before.

IMHO, the safest approach is to introduce a kvstore to store the IP allocation state, as Cillium does.
