### ISSUE TITLE
Istioctl x workload entry configure, configmap not found when CM is istiod-22-3 (looking for istiod)

### ISSUE THREAD

**Issue by cccsss01** [istio/istio#52257]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description
When running istioctl x workload entry configure with revisioned deployment receive error stating configmap not found

Can't find information on istioctl x, and can't specify configmap to use (defaults to istiod cm in istio-system namespace (can't confirm the namespace thing but i'm assuming)

I'm using the revision nomenclature which is creating many things with the added revision.  When i run
istioctl x workload entry configure -f workloadgroup.yaml -o "${WORK_DIR}" --clusterID "${CLUSTER}"
I get configmap not found, which is because it's istiod-revision
looking at the options of istioctl x isn't listed, so either it's not possible to specify the cm or not documented.
Not sure i'm willing to try the auto workload creation due to the "experimental" notation

### Version

```Text
istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (1 proxies)

kubectl version
Client Version: v1.29.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7

helm version
v3.15.3+g3bb50bb
```

### Additional Information

Potentially need additional capabilities to istioctl or more documentation?

**Comment by howardjohn** [comment]
Youll need to pass `--revision`
