### ISSUE TITLE
The ingressgateway pod is unable to start due to a readiness probe failure caused by a timeout.

### ISSUE THREAD

**Issue by AndreyPavlovFlant** [istio/istio#52268]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi there. 

We've encountered an issue where one of our "istio-ingressgateway" pods has rebooted at some point and is unable to start, remaining in the "0/1 Running" status.
Attempting to restart the ingressgateway and istiod pods has not resolved the issue, as the other pods have rebooted and started successfully, but the problematic container continues to fail.

In the describe of this problematic pod, we see an error related to the readinessprobe:

```
Readiness probe failed: Get "http://10.111.39.29:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

In addition, in the logs we see:
```
warn	Envoy proxy is NOT ready: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Interestingly, when we execute this same request from within the problematic pods itself, it succeeds.
I measured how long it takes to execute this request - it is just over 1 second.

```
time curl "http://127.0.0.1:15000/stats?usedonly&filter=^(cluster_manager\\.cds|listener_manager\\.lds)\\.(update_success|update_rejected)$"
cluster_manager.cds.update_success: 74
listener_manager.lds.update_success: 72

real	0m1.173s
user	0m0.004s
sys	0m0.007s
```

I have tried to enable the debug and trace logs from envoy, but I could not find any information in them that could explain the reason for this behavior.

Could you please tell me what might be the cause of this behavior? What else can I check and how? What should I look for in the logs?

We'd appreciate any insights or suggestions you may have. Thank you for your assistance.

### Version

```Text
$ istioctl version
client version: 1.19.7
control plane version: 1.19.7
data plane version: 1.19.7 (12 proxies)
$ kubectl version --short
Client Version: v1.27.14
Kustomize Version: v5.0.1
Server Version: v1.27.14
```

**Comment by unzld** [comment]
Experiencing this same issue as well. Eventually readiness succeeds after a long time (2H and above, it varies).

**Comment by apolovov** [comment]
It is still actual issue.
