### ISSUE TITLE
istio_build metric is dropped after METRIC_GRACEFUL_DELETION_INTERVAL when METRIC_ROTATION_INTERVAL is enabled

### ISSUE THREAD

**Issue by ben-childs-docusign** [istio/istio#52284]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In our environment we recently enabled METRIC_ROTATION_INTERVAL and METRIC_GRACEFUL_DELETION_INTERVAL environment variables to fix the memory leak of metrics over time.

What we observe is that after METRIC_GRACEFUL_DELETION_INTERVAL passes (in our case 120m) for a given pod the istio_build gauge is removed and no longer emitted by the pod. I suspect this is due to the gauge only being emitted once and then not being refreshed periodically? In this case I suppose the metric deletion is purging it.

### Version

```Text
istioctl version
client version: 1.22.3
control plane version: 1.21.3-tetratefips0
data plane version: 1.21.3-tetratefips0 (822 proxies)

kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5
```

**Comment by howardjohn** [comment]
cc @zirain

**Comment by zirain** [comment]
I think it should be a problem, should never clean istio_build metric.
