### ISSUE TITLE
Issue with ConfigMap "istio-ca-root-cert" Creation Delays After Upgrading istiod to v1.20

### ISSUE THREAD

**Issue by haitwang-cloud** [istio/istio#52344]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello Istio Community,
We have been following the guidelines provided in the following documentation to set up multiple Istio environments in our production Kubernetes cluster:

[Canary Upgrades](https://istio.io/latest/docs/setup/upgrade/canary/)
[Discovery Selectors](https://istio.io/v1.13/blog/2021/discovery-selectors/)

Currently, we are managing the following Istio control planes:
- istio-system -> v1.17--> v1.20
- istio-canary -> v1.18
- istio-prod -> v1.19

We're using the ConfigMap: istio in the istio-system namespace with the following configuration to control the generation of the istio-ca-root-cert ConfigMap in different customer namespaces. This setup has worked seamlessly for us:
```
  discoverySelectors:
    - matchExpressions:
      - key: istio-tag
        operator: NotIn
        values:
          - "istio-canary"
          - "istio-prod"
  ```
However, after recently upgrading the `istiod` version in the `istio-system` namespace from v1.17 to v1.20, we noticed anomalies in the behavior of the ConfigMap `istio-ca-root-cert` creation for the namespaces managed by `istio-system`. The issues we are observing are as follows:

The `istio-ca-root-cert` ConfigMap, which should be created immediately after a namespace is created, is now being created within a window of up to 2 minutes after the namespace creation.
In some cases, the `istio-ca-root-cert` ConfigMap is not created at all unless we restart the `istiod` component in the `istio-system` namespace.

I have verified that the documentation at [Istio Mesh Configuration](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) still supports discoverySelectors.
We are unsure of the root cause of this issue and would appreciate any guidance or recommendations the community can provide.
Thank you for your assistance.

### Version

```Text
~ istioctl1.20 version
client version: 1.20.4
control plane version: 1.20.4
data plane version: 1.16.0 (6 proxies), 1.20.4 (146 proxies)

~ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9

~ helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.22.2"}
```

**Comment by hzxuzhonghu** [comment]
We did not change anything between 1.19 to 1.20 on https://github.com/istio/istio/blob/1.20.4/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go

Are you sure it can always reproduce delay creating?

**Comment by haitwang-cloud** [comment]
Thank you for your prompt response. This issue occurs consistently across all our Kubernetes clusters (Dev, Pre-Prod, and Prod). Your help in resolving this is greatly appreciated. Let me check the code and find out more details by myself.

**Comment by howardjohn** [comment]
I strongly suspect this is a bug I fixed in #52428. Has 100% the same symptoms

**Comment by haitwang-cloud** [comment]
@howardjohn Perfect, it turns out your PR really fix this issue and I have verified in my UTs in this PR https://github.com/istio/istio/pull/53307 . 

Could u PTAL?

**Comment by haitwang-cloud** [comment]
This issue has been verified as fixed in this unit test: https://github.com/istio/istio/pull/53347

**Comment by haitwang-cloud** [comment]
This issue has been verified as fixed in this unit test: https://github.com/istio/istio/pull/53347
