### ISSUE TITLE
Missing inbound endpoint when activating PeerAuthentication with STRICT mtls mode

### ISSUE THREAD

**Issue by 4gsim** [istio/istio#52378]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am trying to enable the PeerAuthentication with mtls mode set to STRICT:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peer-auth
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
```

After enabling the listening endpoint (inbound) is disapearing from on of my pods.

Before:

ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
x.x.118.10:8529     HEALTHY     OK                outbound|8529||arango-coordinator-qa3nljvz.ns-kch-test.svc.cluster.local
x.x.118.10:8529     HEALTHY     OK                outbound|8529||arango.ns-kch-test.svc.cluster.local
x.x.118.13:8529     HEALTHY     OK                outbound|8529||arango-agent-af0vtgfr.ns-kch-test.svc.cluster.local
x.x.118.20:8529     HEALTHY     OK                outbound|8529||arango-agent-r4rwf9oq.ns-kch-test.svc.cluster.local
x.x.118.28:8529     HEALTHY     OK                outbound|8529||arango-agent-tmezmxof.ns-kch-test.svc.cluster.local
**x.x.118.39:8529     HEALTHY     OK                inbound|8529||**
x.x.118.39:8529     HEALTHY     OK                outbound|8529||arango-dbserver-bhze9tqt.ns-kch-test.svc.cluster.local
x.x.118.42:8529     HEALTHY     OK                outbound|8529||arango-dbserver-gcgmql59.ns-kch-test.svc.cluster.local
x.x.118.51:8529     HEALTHY     OK                outbound|8529||arango-dbserver-kfcgzmss.ns-kch-test.svc.cluster.local
x.x.118.9:8529      HEALTHY     OK                outbound|8529||arango-coordinator-x2b0bhw5.ns-kch-test.svc.cluster.local
x.x.118.9:8529      HEALTHY     OK                outbound|8529||arango.ns-kch-test.svc.cluster.local

And after:

x.x.118.10:8529     HEALTHY     OK                outbound|8529||arango-coordinator-qa3nljvz.ns-kch-test.svc.cluster.local
x.x.118.10:8529     HEALTHY     OK                outbound|8529||arango.ns-kch-test.svc.cluster.local
x.x.118.13:8529     HEALTHY     OK                outbound|8529||arango-agent-af0vtgfr.ns-kch-test.svc.cluster.local
x.x.118.20:8529     HEALTHY     OK                outbound|8529||arango-agent-r4rwf9oq.ns-kch-test.svc.cluster.local
x.x.118.28:8529     HEALTHY     OK                outbound|8529||arango-agent-tmezmxof.ns-kch-test.svc.cluster.local
x.x.118.42:8529     HEALTHY     OK                outbound|8529||arango-dbserver-gcgmql59.ns-kch-test.svc.cluster.local
x.x.118.51:8529     HEALTHY     OK                outbound|8529||arango-dbserver-kfcgzmss.ns-kch-test.svc.cluster.local
x.x.118.63:8529     HEALTHY     OK                outbound|8529||arango-dbserver-bhze9tqt.ns-kch-test.svc.cluster.local
x.x.118.9:8529      HEALTHY     OK                outbound|8529||arango-coordinator-x2b0bhw5.ns-kch-test.svc.cluster.local
x.x.118.9:8529      HEALTHY     OK                outbound|8529||arango.ns-kch-test.svc.cluster.local

The communication stops working to that particular pod.
Do you have any idea why this would happen? Or where to look for the problem?

### Version

```Text
client version: 1.22.3
control plane version: 1.21.0
data plane version: 1.21.0 (51 proxies)
```

**Comment by 4gsim** [comment]
We get these errors on the inbound connection:
```
2024-07-29T12:01:27.930Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.224.118.63:8529 10.224.118.30:40040 - -                                                                    
[2024-07-29T12:01:27.968Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.224.118.63:8529 10.224.118.30:40046 - -                                                                    
```

**Comment by howardjohn** [comment]
That endpoints is not configured statically, it just shows up when there has been a connection to it. So you get an error and thus no connection so no endpoints. 

The error means the client is not sending mtls

**Comment by 4gsim** [comment]
How could I check if the other end is sending mtls? Everything in the namespace is configured with istio

**Comment by hzxuzhonghu** [comment]
you can use `tcpdump`

**Comment by 4gsim** [comment]
I have added a destination rule that specifies tls ISTIO_MUTUAL option and it works now.

**Comment by 4gsim** [comment]
I have added a destination rule that specifies tls ISTIO_MUTUAL option and it works now.
