### ISSUE TITLE
Create option in docker to view TCP Request IP adress and port

### ISSUE THREAD

**Issue by Marc1200** [istio/istio#52433]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Can you make an option in docker TCP server to enable view of the request IP adresses and ports, so that i can quickly block some IP adresses which are not allowed.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Its not really clear what you are asking for here. What is the 'docker TCP server'?

Istio access logs (https://istio.io/latest/docs/tasks/observability/logs/access-log/) do include the IP/port
