### ISSUE TITLE
AWS Guard duty throws security flags for Istio cni daemonset pod with Privileged Container with sensitive mount

### ISSUE THREAD

**Issue by Falcondevils** [istio/istio#52448]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The bug is about elevated privileges assigned to istio cni daemonset pods while deploying using chart(https://artifacthub.io/packages/helm/istio-official/cni/1.22.3) and i believe the istio cni container does not need elevated permission(privileged: true).
The reason i am saying that i disabled the privileged to false for daemonset so pods are replaced. Then i uninstalled the application and installed them back. It didn't make a difference.
Also installing istio cni using istio operator does not created istio cni container in privileged mode but istio functionality still works.

AWS guard duty also flags it with
https://www.eksworkshop.com/docs/security/guardduty/log-monitoring/privileged_container_mount/

This might not be considered a bug but user needs to have a flexibility what to set in security contexts instead of totally hardcoding it.
https://artifacthub.io/packages/helm/istio-official/cni/1.22.3?modal=template&template=daemonset.yaml

Default values are appreciated and  but a little flexibility is also needed to customize it using helm values.

### Version

```Text
istioctl version

client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.2 (22 proxies), 1.22.3 (2 proxies)

kubectl version --short

Client Version: v1.29.3-eks-ae9a62a
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

helm version --short
v3.15.0-rc.2+gc4e37b3
```

### Additional Information

I guess i provided all the info.
Hopefully this security enhancements get released in next version.

**Comment by howardjohn** [comment]
Fundamentally, CNI plugins (which Istio CNI is) acts by running a binary on the node **as root**. They are privileged inherently, and need to because they manipulate the network. Every single CNI is privileged.

Specifically though, there are two checks:
ContainerWithSensitiveMount is something that cannot ever go away, this is fundamental to how istio CNI works (and every CNI that I have ever seen). This is used to place the binary on the node.

**Comment by howardjohn** [comment]
To be clear -- every networking product doing things like Istio is doing is privileged. Full stop. The only question is whether they are privileged in a way your security scanning tool knows about, or not.

The solution is not to try to hide from the scanning tool, but to acknowledge the reality (and probably add an allowance in the tool so it stops bugging you!).

I am sure the tool is already inserting some of these allowances:
```
$ kubectl -n kube-system get ds kube-proxy -oyaml | grep privi
          privileged: true
```
