### ISSUE TITLE
Move off `copystructure`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52446]
We are using hand written DeepCopy methods in most places, but use copystructure for IstioEndpoints. This _probably_ has a performance impact (untested!), so we should consider moving off.

```
pkg/test/framework/components/echo/config.go
23:     "github.com/mitchellh/copystructure"
556:    copied, err := copystructure.Copy(v)
558:            // There are 2 locations where errors are generated in copystructure.Copy:

pilot/pkg/model/service.go
35:     "github.com/mitchellh/copystructure"
1507:   copied, err := copystructure.Copy(v)
```

Test usage isn't bad, though dropping the dep entirely may make it worth it. IstioEndpoint is critical path though.

**Comment by wulianglongrd** [comment]
It seems that writing `IstioEndpoint` deepcopy by hand is simple and not difficult to maintain because it has no complex fields.
