### ISSUE TITLE
Why is the memory usage so high?

### ISSUE THREAD

**Issue by Webster-Yang** [istio/istio#52457]
Memory usage analysis

(pprof) top8
Showing nodes accounting for 283.42MB, 60.35% of 469.66MB total
Dropped 249 nodes (cum <= 2.35MB)
Showing top 8 nodes out of 170
      flat  flat%   sum%        cum   cum%
      52MB 11.07% 11.07%    78.81MB 16.78%  github.com/json-iterator/go.(*Iterator).ReadString
   45.02MB  9.59% 20.66%   114.03MB 24.28%  github.com/json-iterator/go.(*Iterator).Read.func2
   41.32MB  8.80% 29.46%    41.32MB  8.80%  reflect.unsafe_NewArray
   37.19MB  7.92% 37.37%    37.19MB  7.92%  k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).UnmarshalJSON
   29.06MB  6.19% 43.56%    29.06MB  6.19%  github.com/gogo/protobuf/proto.Marshal
   26.81MB  5.71% 49.27%    26.81MB  5.71%  github.com/json-iterator/go.(*Iterator).readStringSlowPath
   26.50MB  5.64% 54.91%   115.53MB 24.60%  github.com/json-iterator/go.(*Iterator).Read
   25.53MB  5.44% 60.35%    25.53MB  5.44%  reflect.mapassign

**Comment by howardjohn** [comment]
There isn't much progress we can make here without the requested information. TBH the minimal info listed doesn't even look like its from Istio...
