### ISSUE TITLE
Helm chart replacement errors after flatten helm chart values PR

### ISSUE THREAD

**Issue by fjglira** [istio/istio#52458]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After the merge of the PR's #52395 and #52036 some of the replacements using the profile yaml are being done wrong because of the move of the fields on those PR's. I tested using openshift cluster and I found differents errors: 

CNI fields incorrectly replaced:
* cniBinDir
* cniConfDir
* chained
* cniConfFileName
this affected `istio-cni` templates: configmap-cni, daemonset, network-attachment-definition 

Side Injector configmap error:
* CNI values for provider and enabled was still being passed to the configmap under pilot

Errors in the profile related to openshift:
* Because of the move of the fields we need to adjust those fields in the profile

### Version

```Text
istioctl version
client version: 1.22.3
control plane version: 1.24-dev
data plane version: 1.24-dev (10 proxies)

Running latest master
```

**Comment by fjglira** [comment]
cc @howardjohn 

I have a question after the PR to flatten the values:

* Do these CNI fields make sense to have under global?
```
  cniBinDir
  cniConfDir
  chained
  cniConfFileName
```
because they are strictly related to CNI and have it under default in the `values.yaml` and in the profiles can be confusing. It may be worth more to move under `cni` because we still have to have `cni` because we have provider and enabled field also. wdyt?

**Comment by howardjohn** [comment]
No, they should not be global. Note the PR doesn't mean you cannot put things under `cni` in the profile/values.yaml, it just means you don't _have_ to.

**Comment by fjglira** [comment]
I updated the PR moving again those field

**Comment by bleggett** [comment]
1. `pilot.cni.provider = multus` should be dropped, it's redundant (I believe in every single spot) with `platform=openshift` AFAICT.

2. `pilot.cni.enabled` can be moved or renamed, but isn't global because it's only scoped to pilot.

3. No values that are only consumed by a single chart should ever be made `global`. My personal rule of thumb is "if 3+ charts reference exactly the same value, we can start talking about `globals`".
