### ISSUE TITLE
Improve helm charts values and drop un used values

### ISSUE THREAD

**Issue by fjglira** [istio/istio#52528]
Working on PR #52520. Creating the issue to track all the work and discuss here if needed

We need to make some changes on Helm charts and values to:
* `.Values.platform` is used in multiple charts and we already have `.Values.global.platform` in other places, so, seems logical to me to merge them all in `.Values.global.platform`
* `.Values.provider "multus"` is only used for openshift. Change the use of `.Values.provider "multus"` by directly `.Values.global.platform "openshift"`
* Replace `.Values.pilot.cni.enabled` by `.Values.pilot.cniEnabled` to avoid failures when values are unwrapped
* Delete unused values from openshift profiles

**Comment by fjglira** [comment]
I'll change the scope of the issue after some discussion internally with the team. I'll update the issue with the agreements to open the proper PR to onboard the changes

**Comment by howardjohn** [comment]
Just checking in, anything left here?

**Comment by fjglira** [comment]
No, I think everything is set now and we agree not to make these changes. Closing the issue
