### ISSUE TITLE
Traces for authorization requests to custom provider do not include a span for the outbound request

### ISSUE THREAD

**Issue by Stono** [istio/istio#52545]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using a customer authz provider, eg:

```
spec:
  action: CUSTOM
  provider:
    name: whatever 
```

You do not get any spans recorded for the outbound auth request.

In my meshConfig i've tried adding:

```
        includeRequestHeadersInCheck:
        ...
        - x-request-id
        - x-b3-traceid
        - x-b3-spanid
        - x-b3-parentspanid
        - x-b3-sampled
        - x-b3-flags
```

And in the authz service i can see these headers on the incoming request, so i know they're being sent; there's just no span being recorded from the outbound sidecar.

### Version

```Text
1.22
```

**Comment by hzxuzhonghu** [comment]
Trace reporting is done in the httpConnectionManager, while the authz filter is in the http filters under httpConnectionManager. They are in the same level, so the trace setting does not function on the authz filter.

**Comment by Stono** [comment]
Sure, but it would be nice for users to be able to see the impact of custom authz requests in their traces
