### ISSUE TITLE
Unable to use request.headers[Cookie] when there is more than one cookie

### ISSUE THREAD

**Issue by Stono** [istio/istio#52557]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In a RequestAuthentication policy, you might want a matcher to allow the request through if a particular cookie is present, for example:

```
  rules:
  - when:
    - key: request.headers[Cookie]
      values:
      - 'cookie2=*'
 ```

This works fine, when there is only one cookie, however if there's more than one then cookies get concatenated in the `cookie` header, eg:

```
cookie1=whatever; cookie2=whatever;
```

The above matcher will no longer match.

You can't use `*cookie2=*` as matching is supported at the start, end, but not both.

As a result you're stuck and `request.headers[Cookie]` cannot be used if you ever have more than one cookie (basically always).

### Version

```Text
1.22
```

**Comment by simonRos** [comment]
This is still an issue. Please reopen
