### ISSUE TITLE
istioctl register/unregister cmd failed

### ISSUE THREAD

**Issue by linsun** [istio/istio#5255]
Downloaded the daily build (04/25's).   The istioctl uses the default location for the .pem file but mine isn't in the default location.

$ ls $(dirname $KUBECONFIG)
ca-wdc06-linistio3.pem          kube-config-wdc06-linistio3.yml

~/go/src/github.com/linsun/examples/guestbook-go on  master! ⌚ 11:38:29
$ echo $KUBECONFIG
/Users/linsun/.bluemix/plugins/container-service/clusters/linistio3/kube-config-wdc06-linistio3.yml

$ kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
redis-master-pxdm2   1/1       Running   0          43d
redis-slave-fntrc    1/1       Running   0          43d
redis-slave-kmb72    1/1       Running   0          43d

~/go/src/github.com/linsun/examples/guestbook-go on  master! ⌚ 11:24:47
$ istioctl kube-inject -f guestbook-deployment.yaml --debug
Error: invalid configuration: unable to read certificate-authority ca-wdc06-linistio3.pem for linistio3 due to open ca-wdc06-linistio3.pem: no such file or directory

**Comment by linsun** [comment]
cc @esnible @liamawhite

**Comment by linsun** [comment]
marking as blocking release as this is a common scenario where the pem and yml are in a dir but perhaps not in a default dir.  it only works if I modify the yml to use the absolute path of the pem file.

**Comment by esnible** [comment]
I have verified that this ONLY affects `kube-inject`.  The .pem file is handled correctly for `istioctl get routerules`.  I verified using _strace_.

**Comment by esnible** [comment]
This is still an issue because `register` and `deregister` still fail with the same error for the same reason.  To reproduce:

```
istioctl register foo 9.1.2.3 80
```

The problem is that a call to _clientcmd.LoadFromFile()_ is eating the pathname of the certificate file.  The `get` and other working commands use _clientcmd.BuildConfigFromFlags()_ which does not have this problem.  I will take a look at https://github.com/istio/istio/pull/5300 and see if the same code will fix register and deregister.

**Comment by linsun** [comment]
good point, register still fails..

**Comment by esnible** [comment]
@ayj While working on this I noticed debugging output coming from these CLI commands.  As far as I can tell the CLI is the only thing that calls _pilot/pkg/serviceregistry/kube/register.go_  and _deregister.go_.  Would it be reasonable to change the output in those methods to fmt.Printf() and log.Debugf() from the current log.Infof()?  Would it be reasonable to do that on the PR for this fix?

**Comment by ayj** [comment]
cc @ldemailly for `register.go` and `deregister.go` specific changes. 

Debug output should be off by default. Level `info` should be sufficient to use the command under normal circumstances.

**Comment by ldemailly** [comment]
logging from command line with more details isn’t unheard of, I would leave log.Info()

**Comment by jasmine-jaksic** [comment]
Not 0.8 release blocking per discussion with @louiscryan

**Comment by linsun** [comment]
Agreed, i should have removed it after the kube-inject cmd works now.

**Comment by ldemailly** [comment]
So we are dropping support for 0.2 mesh expension feature because ... ?

**Comment by gyliu513** [comment]
I'd like to say this is a blocker for 0.8, as many customer are now trying service mesh expansion now, any workaround solutions for this?

```
root@gyliu-icp-6:~/cases# istioctl -n bookinfo register details 9.111.255.28 http:9080
2018-05-11T10:33:53.150072Z	info	Registering for service 'details' ip '9.111.255.28', ports list [{9080 http}]
2018-05-11T10:33:53.150122Z	info	0 labels ([]) and 1 annotations ([alpha.istio.io/kubernetes-serviceaccounts=default])
Error: invalid configuration: unable to read certificate-authority mycluster1/ca.pem for mycluster1 due to open mycluster1/ca.pem: no such file or directory
```

/cc @linsun @ldemailly

**Comment by esnible** [comment]
I had a PR that fixed this problem.  It was about 4 lines of fixes and about 4 lines of changing log levels.  I deleted the PR because it was not clear if the commands should be removed or fixed.  I am happy to take over the Issue but I have never used these commands and I need wisdom/guidance to know if the goal is to make these commands work, to remove them, or to improve them.

**Comment by gyliu513** [comment]
@esnible @linsun I think that we need at least keep this works in 0.8 release and can improve for next release, so @esnible , can you please continue your PR to fix this for 0.8?

**Comment by linsun** [comment]
@esnible, i think your PR will make the cmd work, at least work like it used to with the old route rule.

**Comment by ldemailly** [comment]
@esnible as I commented in your then PR (and here indirectly) there is no reason for the command to cease working (and also no reason to change the logging from Info to another level, it is "informative" about what it is doing, if a user doesn't want the output they can raise the level to warning)
