### ISSUE TITLE
With Kubernetes Service IP we are getting all the Headers but with Istio gateway IP we are not getting all the header especially connection type keep-alive.

### ISSUE THREAD

**Issue by pransem** [istio/istio#52573]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

From Kubernetes Service IP address Header Details:
![image](https://github.com/user-attachments/assets/f140247a-89bb-4a70-8f4e-4cbc99fe0606)

From Istio Gateway IP address Header Details:
![image](https://github.com/user-attachments/assets/57248457-dc78-4352-b55c-456d07d9a877)

We have tried by adding EnvoyFilter. My gateway is in the default namespace so i have added namespace as default.

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-headers-filter
  namespace: default 
spec:
  workloadSelector:
    labels:
      istio: ingressgateway 
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value: # This is the configuration for the Envoy Lua filter
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_response(response_handle)
                response_handle:headers():add("Keep-Alive", "timeout=300, max=100")
              end
              
Other than that, we have also tried adding timeout in the virtual service too, but it didn't work.
            
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: transaction-service
  namespace: default
spec:
  gateways:
  - new-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /transaction/
    - uri:
        exact: /transaction
    route:
    - destination:
        host: transaction-service
        port:
          number: 8080
    headers:
      response:
        set:
          Connection: "keep-alive"
          keep-alive: "timeout=300"
      request:
        set:
          x-envoy-upstream-rq-timeout-ms: "300000"
          
  Please anyone help here to fix this issue.
      
            
            

### Version

```Text
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2

$ istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (58 proxies)
```

**Comment by howardjohn** [comment]
This is working as intended. HTTP has Hop-by-hop headers (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#hop-by-hop_headers). These must not be proxied. Istio is a proxy. How it sets these settings is up to its own control, unrelated to the downstream application.
