### ISSUE TITLE
Ambient L4 AuthorizationPolicy doesn't  work in remote cluster

### ISSUE THREAD

**Issue by MaYuan-02** [istio/istio#52571]
**Describe the feature request**
I'm using primary-remote mode to deployment istio and try to enable ambient.
In sidecar mode, I apply all policy(vs, dr, authorizationpolicy etc) in primary cluster and they effect both two cluster.
In ambient mode, AuthorizationPolicies on waypoint also effect both two cluster but authorizationpolicies on ztunnel are different. **when I apply a L4 authorizationpolicy in primary cluster,  it doesn't work in remote cluster.** 
Will this be fixed in the future? Maybe this is a feature?
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Multicluster is currently not supported for ambient. Please follow https://github.com/istio/istio/issues/42137. Thanks!
