### ISSUE TITLE
TestAdsEds - v2 failed racetest. 

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#5258]
Failed
==================
WARNING: DATA RACE
Write at 0x00c4202ab860 by goroutine 143:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:694 +0x0
  istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Services()
      /go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:71 +0x3ce
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters()
      /go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:51 +0xf0
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:48 +0x124
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:281 +0x2d2d
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      /go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:129 +0xd2
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1059 +0x1318
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1152 +0x12f8
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:637 +0xac

Previous write at 0x00c4202ab860 by goroutine 168:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:694 +0x0
  istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Services()
      /go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:71 +0x3ce
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters()
      /go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:51 +0xf0
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:48 +0x124
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:281 +0x2d2d
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      /go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:129 +0xd2
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1059 +0x1318
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1152 +0x12f8
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:637 +0xac

Goroutine 143 (running) created at:
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:635 +0xb8
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:383 +0x1389
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:415 +0x648
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:633 +0x16e
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:590 +0x53
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:598 +0x34

Goroutine 168 (running) created at:
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:635 +0xb8
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/handler_server.go:399 +0xa5a
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:633 +0x16e
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).ServeHTTP()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:706 +0x158
  istio.io/istio/pilot/pkg/bootstrap.(*Server).secureGrpcStart.func2()
      /go/src/istio.io/istio/pilot/pkg/bootstrap/server.go:864 +0x14f
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1947 +0x51
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2694 +0xb9
  net/http.initNPNRequest.ServeHTTP()
      /usr/local/go/src/net/http/server.go:3260 +0x100
  net/http.(*initNPNRequest).ServeHTTP()
      <autogenerated>:1 +0x8f
  net/http.(Handler).ServeHTTP-fm()
      /usr/local/go/src/net/http/h2_bundle.go:5475 +0x64
  net/http.(*http2serverConn).runHandler()
      /usr/local/go/src/net/http/h2_bundle.go:5760 +0x96
==================
==================
WARNING: DATA RACE
Write at 0x00c4203b83e8 by goroutine 143:
  istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Services()
      /go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:71 +0x3e4
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters()
      /go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:51 +0xf0
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:48 +0x124
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:281 +0x2d2d
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      /go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:129 +0xd2
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1059 +0x1318
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1152 +0x12f8
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:637 +0xac

Previous write at 0x00c4203b83e8 by goroutine 168:
  istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Services()
      /go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:71 +0x3e4
  istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters()
      /go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:51 +0xf0
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:48 +0x124
  istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources()
      /go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:281 +0x2d2d
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler()
      /go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:129 +0xd2
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1059 +0x1318
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1152 +0x12f8
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:637 +0xac

Goroutine 143 (running) created at:
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:635 +0xb8
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:383 +0x1389
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/http2_server.go:415 +0x648
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:633 +0x16e
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func2()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:590 +0x53
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleRawConn.func3()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:598 +0x34

Goroutine 168 (running) created at:
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:635 +0xb8
  istio.io/istio/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/transport/handler_server.go:399 +0xa5a
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:633 +0x16e
  istio.io/istio/vendor/google.golang.org/grpc.(*Server).ServeHTTP()
      /go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:706 +0x158
  istio.io/istio/pilot/pkg/bootstrap.(*Server).secureGrpcStart.func2()
      /go/src/istio.io/istio/pilot/pkg/bootstrap/server.go:864 +0x14f
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1947 +0x51
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2694 +0xb9
  net/http.initNPNRequest.ServeHTTP()
      /usr/local/go/src/net/http/server.go:3260 +0x100
  net/http.(*initNPNRequest).ServeHTTP()
      <autogenerated>:1 +0x8f
  net/http.(Handler).ServeHTTP-fm()
      /usr/local/go/src/net/http/h2_bundle.go:5475 +0x64
  net/http.(*http2serverConn).runHandler()
      /usr/local/go/src/net/http/h2_bundle.go:5760 +0x96
==================
testing.go:730: race detected during execution of test

**Comment by andraxylia** [comment]
@baodongli I see the issue was fixed by your commit, closing it.
