### ISSUE TITLE
grpc and h2 benchmark (run the benchmark, analyze the results)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#526]

**Comment by ldemailly** [comment]
Early numbers of just the framework itself:
GRPC 0.370 ms avg, 21631.1 qps
HTTP 0.177 ms avg, 45052.5 qps
so somehow grpc is more expensive...
(and that's before any TLS)

**Comment by sakshigoel12** [comment]
@ldemailly please assign this issue if it is still considered P0

**Comment by ldemailly** [comment]
@sakshigoel12 do you have a set of people I can assign it to ?
(a set that isn't just me)
