### ISSUE TITLE
[Ambient] Specified host header is ignored

### ISSUE THREAD

**Issue by qts0312** [istio/istio#52607]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In ambient mode, I cannot make traffic captured by specific VirtualService by specifying the host header. That means given the VirtualService like this, traffic `curl -H"host:aaa" http://bbb:80` can only be captured by it when `bbb` is exactly same as `aaa`. So is specified host header ignored in ambient mode?

```yaml
kind: VirtualService
spec:
  hosts:
    - "aaa"
 ```

### Version

```Text
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (6 proxies)

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

**Comment by howardjohn** [comment]
Yes, ambient mode does not use Host headers for routing and instead uses service. This is fundamental to almost all parts of the design of ambient so cannot be changed. 

Note this is more clear when you use HTTPRoute, which is the recommended way, as there is not a "hostname" but instead a reference to a specific Service.
