### ISSUE TITLE
AWS EKS Istio Ambient connectivity not working(Health Check failure)

### ISSUE THREAD

**Issue by nick-akmatov-runbuggy** [istio/istio#52620]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am using following commands to install istio-gateway to our AWS EKS Cluster:
helm install istio-ingress istio/gateway -n istio-ingress --create-namespace -f my-file-values.yaml --wait.
In my values file I have a those following annotations for NLB Load Balancer:
```service:
    # Type of service. Set to "None" to disable the service entirely
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```
<img width="690" alt="Screenshot 2024-08-09 at 12 46 50 PM" src="https://github.com/user-attachments/assets/a0c820ab-e643-4576-9822-da71038b65d2">

  NLB and Node Target Groups are created successfully, but node health check for ports: 443 and 80 are failing
{See attached screenshot}
We have searched in internet and tried different annotations, but still failing nodes health check
    

### Version

```Text
kubectl version:
Client Version: v1.30.1
EKS Version: v1.24.17
helm version:
v3.15.2
```

**Comment by howardjohn** [comment]
Not super familiar with how it should be set up with AWS NLBs, but the reason it is failing is probably that Istio does not actually listen on the ports until you tell it do so with a Gateway configuration. So AWS tries to connect to the port and fails.

Typically the health check is following the k8s health check on port 15021
