### ISSUE TITLE
Add logAsJson value to ztunnel helm chart

### ISSUE THREAD

**Issue by markusobsil** [istio/istio#52631]
**Describe the feature request**
Istio helm charts (e.g. [istiod](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L259), [cni](https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/values.yaml#L129)) use the value `logAsJson` to change the logging format to JSON. The ztunnel helm chart does not have this value. I would like to add it for sake of consistency/user experience.

**Describe alternatives you've considered**
The current way (and only possible way) to configure this is to change the LOG_FORMAT environment variable.

```yaml
env:
  LOG_FORMAT: json
```
But this is not consistent with the way how it is configured in istiod and istio-cni. 

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by MorrisLaw** [comment]
Completed by #52633
