### ISSUE TITLE
Allow to disable overload manager for health checks and metrics

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [istio/istio#52663]
**Describe the feature request**

In [Envoy 1.31](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.31/v1.31.0), a new feature was added to the listener called `bypass_overload_manager`:

> listener: Added [bypass_overload_manager](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-bypass-overload-manager) to bypass the overload manager for a listener. When set to true, the listener will not be subject to overload protection.

This feature is useful to be enabled for health check and metrics listeners, so that they can bypass the overload manager.

For example, the overload manager might be configured to drop any new connections or HTTP requests when the memory reaches 95%. 

However, this affects both health checks and metrics, leading to a problem that the metrics will not be exported, or the proxy might be killed, because it won't respond to the health check.

As for now, the health checks and metrics listeners are configured using [bootstrap configuration](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap.json). This bootstrap configuration might be overridden, though, I am not sure if we can override these listeners, and how complex it is to do this.

My proposal is to add an env variable, similar to `ISTIO_DUAL_STACK`, that will allow to configure the `bypass_overload_manager` for the static listeners in the bootstrap file.

**Describe alternatives you've considered**

An alternative is to override the bootstrap configuration. However, I am not sure how custom bootstrap configuration is merged with the default one. It seems to me that adding a new property to the bootstrap configuration is pretty straight-forward, but changing existing values is not. 

Moreover, the listeners configuration is provided as an array, which might be more difficult to override. 

Lastly, overriding the bootstrap configuration is more error-prone between Istio versions. Having an explicit option seem to be a better choice.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Related issues - #41859

**Comment by howardjohn** [comment]
For metrics I think this makes a lot of sense, you'll definitely want to understand the metrics of something in a bad state.

For health checks... if we are overloaded, do we actually want to pass health checks?

**Comment by AleksanderBrzozowski** [comment]
@howardjohn 

Ah, to be honest I don't know if the health check should pass, maybe this should be configurable.

Anyways, there is no option right now to disable either of them. Maybe it would be useful to have two env variables that would allow to set them separately?

I am not familiar yet with options that are available with overload manager, but I feel that there are cases in which it makes sense to bypass both health check and metrics. 

WDYT?

**Comment by howardjohn** [comment]
My thought process was this should eventually just be on by default for everyone. We can have an env var to control it in the short term as a feature flag.

If we want control over which ones need it vs which don't, though, then that may change that..

@briansonnenberg has thought about this a bit IIRC, maybe has some opinions

**Comment by eduardobaitello** [comment]
It's nice that this feature becomes available on 1.24! 😄 

For the unlucky ones still using 1.23: is there a temporary way to override bootstrap so that the metrics and health check listeners ignore the overload manager and max connections?

I'm trying to implement a palliative solution, but I'm having a lot of difficulty 😭

**Comment by vinay-g** [comment]
@howardjohn @ramaraochavali The above change does a bypass for /stats/prometheus and /healthz/ready. Can you suggest a way to add a bypass for the app container health checks example: /app-health/hello-world/readyz which runs on 15020

We want the app to continue running when overload thresholds are met.
