### ISSUE TITLE
Document how to run ambient without elevated privileges/extra CRDs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52675]
We should document for users how they can remove the webhook (which is not needed for sidecars) and turn off CRDs they don't need (Sidecar, etc)

---
Previous we had an idea about an "ambient only" profile. This was modified in https://docs.google.com/document/d/1SMlwliEnthgq7r2PjpLl1kCq3t8rAMbgu6r_lDAXJ0w/edit#bookmark=id.4v4eck7nwu42; below is the original description

## Original description

Today, we have an "ambient" profile in the install. This is basically adding features only, not removing features that don't make sense.

There is some desire to have a mode where we only have the new stuff. This issue tracks that.

Some ideas on what we might remove:

* CRDs: Sidecar, EnvoyFilter, Gateway, VirtualService
* Mutating webhooks
* ?

Note the disabling CRDs is a bit wonky as they are not helm templated.

**Comment by keithmattix** [comment]
> Note the disabling CRDs is a bit wonky as they are not helm templated.

Let's just template them :p

**Comment by bleggett** [comment]
If we wanted to get wild we could also have this make `istioctl analyze` warn you if you use any `sidecar.istio.io` labels.

**Comment by zirain** [comment]
if we support this, users can not run a mixer(Ambient + Sidecar) mode in the cluster?

**Comment by howardjohn** [comment]
Yeah just to be clear this would be an option not the default. the intent was to have minimal privileges in the cluster now that some are not needed with ambient

**Comment by linsun** [comment]
cc @danehans

**Comment by ilrudie** [comment]
Do we need to also consider a way to easily move from "ambient only" to "full" Istio or is "install with ambient profile" good enough?

**Comment by linsun** [comment]
> Do we need to also consider a way to easily move from "ambient only" to "full" Istio or is "install with ambient profile" good enough?

Maybe i'm missing something, isn't that simplying by running the install cmd again with the desired profile + config?

**Comment by danielloader** [comment]
Losing EnvoyFilter would be a mixed blessing.

Currently using it to intercept any 503s that come back from dead upstreams to issue a static maintenance page for example.

I'm aware most of the functionality in the EnvoyFilter doesn't work with ambient but all the same it's the only exit hatch for some functionality that comes out the box with other gateways like traefik.

Not to say I wouldn't prefer standardised apis for such things but you take what you can get sometimes.

**Comment by ilrudie** [comment]
@danielloader,  You can still install "full" Istio ambient, which isn't going away, rather than "just the necessities" ambient...
