### ISSUE TITLE
Deprecate and remove `install.operator.istio.io/owning-resource` label in favor of more standard `app.kubernetes.io/managed-by` & `app.kubernetes.io/part-of` labels

### ISSUE THREAD

**Issue by bleggett** [istio/istio#52670]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

`install.operator.istio.io/owning-resource` is an Istio-specific label that is entirely redundant with [more standardized K8S labels like](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)  `app.kubernetes.io/managed-by` & `app.kubernetes.io/part-of`. It is also not consistently applied across all our charts.

Additionally, the operator is removed as of recently: https://github.com/istio/istio/pull/52090 so likely `install.operator.istio.io/owning-resource` can simply be dropped entirely - it is barely used outside of one or two tests, and in most tests/usages we just explicitly set it to `unknown` anyway.

A previous failed attempt at dropping it is [here](https://github.com/istio/istio/pull/52471) (context [here](https://github.com/istio/istio/issues/52034#issuecomment-2263687886)) - this (unsurprisingly) caused some weird and apparently unrelated test failures and I did not pursue it further, but if the usages in the test suite are to be believed, we do not rely on this label for very much, and are better served by using the standard K8S labels anyway.

If there are concerns about dropping it, and requests that we permanently retain `install.operator.istio.io/owning-resource` even though it's redundant/not-preferred, we should instead globally populate `app.kubernetes.io/managed-by` & `app.kubernetes.io/part-of` consistently across all charts, and set `install.operator.istio.io/owning-resource` to the values of those labels in the charts where the latter appears.

_probably_ we can just use `app.kubernetes.io/part-of` as a direct replacement for `owning-resource`

### Version

```Text
N/A
```

**Comment by howardjohn** [comment]
I have no clue why we put them in the pure helm charts, but they are used for sure in `istioctl install` which uses them for pruning.

**Comment by bleggett** [comment]
> I have no clue why we put them in the pure helm charts, but they are used for sure in `istioctl install` which uses them for pruning.

Yeah - I saw that. Shouldn't be too hard to make `istioctl` prune against `app.kubernetes.io/managed-by` or `app.kubernetes.io/part-of` instead tho - and ideally in a world where `istioctl` does a `helm uninstall` there shouldn't be much left left to prune / we should handle that locally in the chart with a removal hook.
