### ISSUE TITLE
Document Ambient Improvements

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52698]
- [x] [performance/scalability](https://preliminary.istio.io/latest/docs/ops/deployment/performance-and-scalability/) (This also includes having corresponding tests to avoid regressions). Subtask: https://github.com/istio/istio/issues/52977. Owner: @Stevenjin8 
- [x] security model. Owner: @howardjohn ? https://github.com/istio/istio.io/pull/15672 - in review
- [x] verifying mTLS. Subtask: https://github.com/istio/istio.io/issues/15486. Owner: @linsun
- [x] supported APIs (feature status). Owner: @linsun
- [x] finalize docs for revision based [upgrades](https://preliminary.istio.io/latest/docs/ambient/upgrade/helm-upgrade/). Owner: @therealmitchconnors ?
- [x] TBD: finalize docs for in-place [upgrades]. Owner: ?

**Comment by Stevenjin8** [comment]
Related to #48271

**Comment by linsun** [comment]
I can help with 2 and 3, i'll add my name to it.

**Comment by keithmattix** [comment]
@Stevenjin8 do you think you could help with/own 1)?
