### ISSUE TITLE
2-3 Production users have validated Ambient in real world scale/environment

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52696]

**Comment by Stevenjin8** [comment]
From @linsun 
> At least 2-3 users running ambient in production, exercising a few of ambient’s features such as mTLS or observability etc

**Comment by howardjohn** [comment]
We have engaged with a number of users in the #ambient slack channel giving confidence this is achieved. There is a strong desire to get some case studies done which we will track outside of this
