### ISSUE TITLE
Proxy resource overrides through annotations are not mutually exclusive

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#52693]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

## Problem Statement

It seems the proxy resource override [annotations](https://istio.io/latest/docs/reference/config/annotations/#SidecarProxyMemory) are not mutually exclusive. For example, if I set `sidecar.istio.io/proxyCPU` in my deployment, then the rest of the defaults such cpu/memory limit and memory request are removed. 
Ideally, the overrides should be mutually exclusive to each other. 

## Steps to reproduce
1. Capture the default resource configuration of the proxy.
```
   resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
```
2. Edit the `httpbin` deployment and add the following override
```
annotations:
  sidecar.istio.io/proxyCPU: 1800m
```
3. Verify the resource configuration of the proxy again, you'll notice the memory request, limit and cpu limit is removed.
```
resources:
  requests:
    cpu: 1800m
```

### Version

```Text
$ istioctl version
client version: 1.17.4
control plane version: 1.20.0
data plane version: 1.20.0 (2 proxies)
```

**Comment by keithmattix** [comment]
Looks like a generic merging bug; should be pretty straightforward to fix if you or someone else would like to submit a PR!

**Comment by shriramsharma** [comment]
thanks @keithmattix , I have the fix almost ready. Will have the PR out soon

**Comment by slawekww** [comment]
@shriramsharma PR is not merged. When fix is planned to be delivered? It is annoying to provide always full set of annotations.
