### ISSUE TITLE
Finalize Ambient Install Mechanisms

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52702]
From [Ambient GA RFC](https://docs.google.com/document/d/1GiD2-MmY9VrkfEs-ET0b7UGPmVII2GQUD7m1iAvbrjo):
> Ensure that install mechanisms are approved and will not require known major breaking changes post-GA.

**Comment by linsun** [comment]
Hi @howardjohn I saw this is in progress, wanted to ask if you have plans to consolidate some of our charts?  Maybe istio base, istio-cni & istiod?   Any reduction from 5 charts is good :)

**Comment by howardjohn** [comment]
In terms of merging:
* Istiod is not a singleton, so it needs to be kept away from singletons
* Base is a singleton, we basically only need CRDs from it though
* CNI is a singleton
* Ztunnel is a singleton
* Gateway doesn't count; you can install it 0..N times (or not even use helm and use Gateway API)

So realistically the only thing we can do is merge CNI and Ztunnel. You could maybe merge CRDs with those, although its awkward. I don't think there will ever be a model such that we literally merge N charts to 1; instead we can document and give samples of composing charts. We can also publish pre-composed ones (this is the `ambient` chart) to make this even easier.

The consolidated `ambient` chart merging all of them into one, IMO, can never be the recommended option: its impossible to follow a safe upgrade pattern. Not even mentioning the fact there is no revision support possible, you cannot sequence Istiod to upgrade first which is the only supported path. We can provide it, but its not safe and thus really shouldn't be the default production installation recommendation.

CNI and Ztunnel could plausible be merged.

Do we think its worth it to make a whole new `ambient-dataplane` chart to merge cni and ztunnel?

**Comment by linsun** [comment]
Would it be possible to have 1 helm chart but installing selectively components? not sure if this is possible with helm, here is what i'm thinking:

# install istiod, could be revisioned
helm install istiod istio/ambient --set component=istiod

# install cni, ztunnel and potentially CRD
helm install istio-dp istio/ambient --set component=dp

**Comment by bleggett** [comment]
> Would it be possible to have 1 helm chart but installing selectively components? not sure if this is possible with helm, here is what i'm thinking:
> 
> ```
> # install istiod, could be revisioned
> helm install istiod istio/ambient --set component=istiod
> 
> or
> 
> helm install istiod istio/ambient --set istiod.enabled=true
> 
> # install cni, ztunnel and potentially CRD
> helm install istio-dp istio/ambient --set component=dp
> 
> or
> 
> helm install istiod istio/ambient --set ztunnel.enabled=true --set base.enabled=true --set cni.enabled=true
> ```
> 
> That way, if users are okay with in place, they can just do `helm install istio istio/ambient`. And if users want revision based upgrade and sequence of CP first then DP, they can do the 2 steps (or even more steps if needed). Basically, simple scenario doesn't need to pay for the complexity.

Probably not, this would only really work if you used a different install name for each.

Ex:

> helm install istiod istio/ambient --set istiod.enabled=true

would install everything but `istiod` as an installation named `istiod`

> helm install istiod istio/ambient --set istiod.enabled=false

would _replace/upgrade_ the installation named `istiod`, and remove the (now-disabled) component.


Ex:


> helm install istiod istio/ambient --set istiod.enabled=true

would install everything but `istiod` as an installation named `istiod`

> helm install istiod-try2 istio/ambient --set istiod.enabled=false

would create a new installation named `istiod-try2` in parallel with the existing one.

Our charts probably have singletons that will collide tho and can't be installed SxS, in this case.


A better approach IMO would be to actually formalize our upgrade cadences across all components into 2 categories:

- `istio-controlplane`
- `istio-dataplane`

and have 2 charts, which effectively gives you exactly 2 upgrade cadences to play with, and no more.

**Comment by bleggett** [comment]
The consensus was that 

- individual chart installs are (naturally) always going to be supported
- if we later add composed installs to simplify the Helm installation process, people will not be able to upgrade easily from the individual to the composed model, they will have to reinstall.
- while going GA without that will ossify the current model and lock people who use it into a particular upgrade cadence, it is already ossified at this point, so deferring this to post-GA is not a unique UX risk.

So closing this as done now.
