### ISSUE TITLE
More Ambient analyzers

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52706]
This includes 
* #50249 
* #52602

**Comment by Stevenjin8** [comment]
Related to #50249

**Comment by MorrisLaw** [comment]
With Ambient mode (and maybe even future multicluster analysis can be affected by this) there is a need to do things involving the Analyzer that are different than what we've done in the past. We will need to spend time thinking about and refactoring code to support these new expectations for this Istio feature. This will include refactoring the way we:
- retrieve data for the Analyzer; might need to come from different sources (e.g. for Waypoints this will mean wds) as opposed to just expecting all data to come from k8s static resources. (examples of analyzers that need this and some related issues: #50249, #50849, #24345)
- write status with the Analyzer; there are multiple ways so one consideration could be to refactor writing status to be more uniform and allow individual status writing controllers to have their own queues to enqueue status writing, with all status writing controllers leveraging a shared worker pool with a globally set limit to prevent overloading the system (as discussed here #52602)
