### ISSUE TITLE
TestIngressMetric fails in both master and the 0.8 release branch

### ISSUE THREAD

**Issue by hklai** [istio/istio#5270]
Example:
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1558/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1557/

From Doug:
"the ingress metrics one looks like because the service was renamed to "istio-ingressgateway"
from "istio-ingress". whomever did that broke the test

Peter can help debug that"

**Comment by hklai** [comment]
This test is still failing in the latest post-submit test in the release-0.8 branch.

https://storage.googleapis.com/istio-prow/e2e-suite-rbac-auth/1564/build-log.txt

**Comment by bianpengyuan** [comment]
I guess it is because both istio-ingress and istio-ingressgateway are running in the test cluster, and this caused pilot v1 to be confused when it builds ingress listener. See code here: https://github.com/istio/istio/blob/HEAD/pilot/pkg/proxy/envoy/v1/config.go#L164 and the prefix of istio-ingress and istio-ingressgateway are "istio-ingress".

@vadimeisenbergibm Is ingressgateway expected to show up in a mixer-e2e-test?

**Comment by vadimeisenbergibm** [comment]
@bianpengyuan Yes, `istio-ingressgateway` is expected to show up in all the tests now. However, the tests of v1alpha1 should have the ingress traffic going through `istio-ingress`, so `istio-ingressgateway` should not get any traffic and should not influence the tests.

**Comment by bianpengyuan** [comment]
@vadimeisenbergibm According to code here: https://github.com/istio/istio/blob/HEAD/pilot/pkg/proxy/envoy/v1/config.go#L164. Listener config will only be generated for one ingress services based on prefix match, which would affect ingress mixer client metric report, isn't it?

**Comment by vadimeisenbergibm** [comment]
@bianpengyuan ah, you are right, there is a `break` there! This code should be changed to handle both `istio-ingress` and `istio-ingressgateway`.

**Comment by vadimeisenbergibm** [comment]
^^^ @hklai probably this is the problem, discovered by @bianpengyuan

**Comment by vadimeisenbergibm** [comment]
@bianpengyuan actually, I think it should handle only `istio-ingress`. And also, the name of `istio-ingress` should be read from the mesh config. cc @rshriram

**Comment by vadimeisenbergibm** [comment]
I think this is the plan of @rshriram. See https://github.com/istio/istio/blob/release-0.8/install/kubernetes/helm/istio/values.yaml, both ingress and ingress gateway are enabled.

**Comment by bianpengyuan** [comment]
IngressMetricsTest stops being flaky. Fixed.
