### ISSUE TITLE
Ambient umbrella chart improvement

### ISSUE THREAD

**Issue by linsun** [istio/istio#52718]
It would be nice if I could only set the hub and tag once:

```
helm upgrade -i istio-ambient istio/ambient \
  --kube-context solo-cluster \
  --namespace istio-system \
  --create-namespace \
  --set "cni.defaults.global.hub=${ISTIO_REPO}" \
  --set "cni.defaults.global.tag=${ISTIO_VER}" \
  --set "istiod.defaults.global.hub=${ISTIO_REPO}" \
  --set "istiod.defaults.global.tag=${ISTIO_VER}" \
  --set "ztunnel.defaults.hub=${ISTIO_REPO}" \
  --set "ztunnel.defaults.tag=${ISTIO_VER}" \
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
cc @vincentjorgensen

**Comment by bleggett** [comment]
This should already be fixed by https://github.com/istio/istio/issues/51943

`--set global.hub --set global.tag` should apply to all components.

**Comment by vincentjorgensen** [comment]
I'll try it out. thx

**Comment by linsun** [comment]
Nice thanks @bleggett.

I've tried it, works:

```
helm template my-ambient istio/ambient --set global.hub=foo --set global.tag=bar
```

**Comment by linsun** [comment]
Closing it as it works!
