### ISSUE TITLE
DestinationRule mutual TLS with credential name requires too wide RBAC permissions

### ISSUE THREAD

**Issue by erplsf** [istio/istio#52728]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to configure Egress TLS for one workload, so when it connects to the external service it uses the client certificates to identify itself. Everything works if I follow the [official documentation](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#configure-the-client-sleep-pod) and create a role that can list all secrets in the namespace.

But I see this is as a breach of security - if I specify `credentialName` inside the `DestinationRule`, why cannot I limit the role to **just** that secret?

So that's what I've tried - I've tried to restrict the role via `resourceNames` field to **just** that secret, and I've verified (via `kubectl auth can-i`) that `ServiceAccount` for the workload can get/list/watch the secret in question.

But when I `exec` into the workload, I cannot reach the external service and get the following error:
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
```

When I remove the RBAC role scoping (set `resourceNames` field to empty array), basically allowing workload to get/list all secrets in the namespace, it starts working again.

I see this is as an area that can be improved, and would be glad to help out if you can point me to the relevant section of code where I could contribute.

### Version

```Text
$ istioctl version
client version: 1.22.1
istiod version: 1.22.1
data plane version: 1.22.1 (314 proxies)
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-eks-db838b0
```

### Additional Information

I cannot include relevant information as this includes sensitive customer information.

**Comment by howardjohn** [comment]
Here is the context here...

In the original days, gateways literally read Secrets directly from the API server. So, of course, they had to have RBAC permission to do so.

We later changed this to Istiod, but we had to solve a problem: how do we know which XDS connections we should allow access to secrets for? We decided to rely on the same RBAC. We didn't want to just use "if its in Gateway its fine" because (1) users were not used to Gateway implicitly giving Secret access, and (2) Gateways applied cross-namespace which is makes this insecure to do so.

To implement this, we do a cached check if its allowed, checking if LIST is allowed. This is important because some gateways may have 10k certificates.

Later, we added DR. Same logic applied there. DR is a bit different since it does not have the cross-namespace aspect, though it does have the "users are not used to DR implicitly giving Secret access" issue.

----

So it seems there are two solutions here:

* Allow access without RBAC, and find a way we are comfortable with the security implications of that
* Lookup individual accesses, instead of "can LIST", and find a way we are comfortable with the scalability implications of that

**Comment by kyessenov** [comment]
> But I see this is as a breach of security - if I specify `credentialName` inside the `DestinationRule`, why cannot I limit the role to **just** that secret?

Istiod is not an RBAC engine to k8s resources, so the fact that the secret is mentioned is not an explicit authorization. k8s doesn't allow per-resource access I believe, it's GET or LIST for all secrets, isn't it?

Secrets in general should be minimally transported, and ideally retrieve directly from Envoy using something like https://github.com/envoyproxy/envoy/issues/35729.

**Comment by erplsf** [comment]
> k8s doesn't allow per-resource access I believe, it's GET or LIST for all secrets, isn't it?
It does. here's an example to reproduce:
```
$ kubectl create secret generic rbac-test --from-literal=key=secret
$ kubectl create serviceaccount rbac-test-no-access
$ kubectl auth can-i get secret/rbac-test --as=system:serviceaccount:default:rbac-test-no-access
no
$ kubectl create role rbac-scoped-secret-access --resource=secret --verb=get,list,watch --resource-name=rbac-test
$ kubectl create serviceaccount rbac-test-scoped-access
$ kubectl create rolebinding rbac-test-binding --role=rbac-scoped-secret-access --serviceaccount=default:rbac-test-scoped-access
$ kubectl auth can-i get secret/rbac-test --as=system:serviceaccount:default:rbac-test-scoped-access
yes
$ kubectl create secret generic rbac-test-not-allowed --from-literal=key=secret
$ kubectl auth can-i get secret/rbac-test-not-allowed --as=system:serviceaccount:default:rbac-test-scoped-access
no
```

**Comment by howardjohn** [comment]
> hat scalability implications? you can do list on all secrets, or you can do list on a specific secret that's mentioned in your configuration. API server will do (i presume), the same amount of work checking your permission level. And I can grant list permissions just for secrets I want to expose, if that's the requirement. The issue, as I see it, is that the check is performed ("can I list secrets?") against ALL secrets (in the namespace), and not against those mentioned in the DR.

Imagine I have 6000 secrets in one namespace.
1. How we implement it: 1 call "can they LIST in namespace"
2. individual secrets: 6000 calls to "can they GET"

**Comment by howardjohn** [comment]
And I am fairly sure you cannot list a subset of resources

**Comment by erplsf** [comment]
Isn't doing RBAC check on Istio side is kinda doing security in the wrong place? Maybe I'm naive here, but this looks like the job for the k8s api server, and Istio should only present an error from the API server if when it tries to access a resource it cannot.
Anyway, this issue is about the fact that by deciding to use Istio features, we expose all secrets in the namespace to the workload, which lowers our security posture - is there a chance to review this area of code and accept alternative ideas?

**Comment by howardjohn** [comment]
And as mentioned in https://github.com/istio/istio/issues/52728#issuecomment-2294096519 I am open to alternative ideas, there just hasn't been any presented when this was first discussed (for like 6 months we reviewed the design) or over the years since then.

**Comment by kyessenov** [comment]
FWIW Google is moving SDS fetching back into proxy where it respects proper RBAC in our version, in a dedicated agent/sidecar for gateways. If there is interest, it can be upstreamed. @igsong
