### ISSUE TITLE
"Poison pills" 

### ISSUE THREAD

**Issue by costinm** [istio/istio#5272]
An example found doing manual testing is having 2 virtual services with same domain - resulting in all listeners getting rejected. This particular bug is supposed to be fixed now - the problem is that we have no
way to debug or notify user of such cases. 

This also affects customers who have production issues - one example is a failure to find an endpoint 
resulting in LDS not having in listeners and cascading failures.

We need to add at least more logs and metrics in all error points.

**Comment by hklai** [comment]
Not release blocking per discussion with @costinm @louiscryan and @jasminejaksic.

**Comment by ostromart** [comment]
I believe this is a planned work item for 1.0 pilot but I'm not sure if anyone has taken it @rshriram ? I do agree it's a high priority for usability.
