### ISSUE TITLE
CEL validation is rejecting the creation of WorkloadGroups when spec.template.address isn't set

### ISSUE THREAD

**Issue by djannot** [istio/istio#52749]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The address field is mandatory when creating a WorkdloadEntry, but it shouldn't be for WorkloadGroups

### Version

```Text
istioctl version

client version: 1.23.0
control plane version: 1.23.0-solo
data plane version: 1.23.0-solo (7 proxies)

kubectl version --short

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

**Comment by howardjohn** [comment]
needs https://github.com/istio/api/pull/3295 still
