### ISSUE TITLE
Support `connection.sni` in AuthorizationPolicy for waypoint proxy

### ISSUE THREAD

**Issue by Pythoner6** [istio/istio#52752]
**Describe the feature request**

I've been looking at setting up ambient mode and using a waypoint proxy for egress traffic, however when I try to set up ServiceEntries using `protocol: TLS`, there doesn't seem to be any good way to apply an AuthorizationPolicy to restrict based on the different service entries. It seems like the condition `connection.sni` does not work with the waypoint proxy.

**Describe alternatives you've considered**

The best alternative I've found is manually specifying the IP address for the ServiceEntry, and then using the `destination.ip` condition in the policy, which is annoying, but does seem to work.

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Thanks for the report. ill probably look into this soon, but if someone else wants to take it over just assign yourself.

**Comment by howardjohn** [comment]
Basically I suspect we could add the TLS inspector when the protocol is 'TLS/HTTPS'

**Comment by jewertow** [comment]
@howardjohn, I can see that ztunnel does not support `connection.sni` for now. Can I implement this condition in ztunnel as well or is it unsupported on purpose?

**Comment by howardjohn** [comment]
SNI is an L7 property so it is not supported on Ztunnel intentionally
