### ISSUE TITLE
Missing upgrade note for 1.23.0 Ambient mode

### ISSUE THREAD

**Issue by Phenix66** [istio/istio#52751]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Upgrading Istio Ambient mode from 1.22.2 to 1.23.0 and it seems there is a missing upgrade note in https://istio.io/latest/news/releases/1.23.x/announcing-1.23/upgrade-notes/

My Istio configuration details (I would paste my IstioOperator manifest but it's on another network):
- Profile: ambient
- Istiod is deployed to istio-system
- CNI and ztunnel pods are deployed to kube-system. We do not allow privileged pods in any other namespace.

My issue was nearly identical to https://github.com/istio/istio/issues/52057 except I encountered the error only after upgrading Istio and changing nothing else in my configuration. Thanks to @yardenshoham commenting on that issue, I figured out the fix. I had to configure the env var `CA_TRUSTED_NODE_ACCOUNTS: "kube-system/ztunnel"` for the pilot component in my config then everything worked smoothly. 

The default value for this env var on the istiod container was `istio-system/ztunnel` on my Istio 1.23.0 deployment. I checked my most recent v1.22.2 deployment and that env var was set to `istio-system/ztunnel,kube-system/ztunnel` automatically. So either the documentation should have mentioned that this value would need to be configured appropriately when upgrading to 1.23.0, if this change was intended, or there is a regression where that env var isn't being configured correctly anymore when deploying ztunnel to a different namespace.

### Version

```Text
Istio v1.23.0
Kubernetes 1.30.2
```

**Comment by howardjohn** [comment]
cc @bleggett

**Comment by howardjohn** [comment]
For helm we may need to have users explicitly do it, but for istioctl we can automatically set `trustedZtunnelNamespace` based on `components.ztunnel.namespace`. Should be a 1 line change.

**Comment by bleggett** [comment]
Yeah this is another one that I _definitely created a release note for_ but which didn't make it into the published notes, for reasons that I'm not clear on.

https://github.com/istio/istio/pull/51311

**Comment by howardjohn** [comment]
Oh it is in the change notes: https://istio.io/latest/news/releases/1.23.x/announcing-1.23/change-notes/#installation

**Comment by bleggett** [comment]
The reason we did not simply sustain the previous default was that the previous default granted access to two namespaces, only one of which would ever be used, which was arguably a security hole.

**Comment by Phenix66** [comment]
> Oh it is in the change notes: https://istio.io/latest/news/releases/1.23.x/announcing-1.23/change-notes/#installation

I don't use the Helm chart however and nothing in that line tells me that previous default behavior changed. Based on the upgrade notes, I expected to be able to install Istio 1.23.0 using my current IstioOperator manifest and the `istioctl` command.

**Comment by Phenix66** [comment]
> The reason we did not simply sustain the previous default (`istio-system/ztunnel,kube-system/ztunnel`) was that the previous default granted access to two namespaces, only one of which would ever be used, which was arguably a security hole.

I definitely agree with that sentiment. In my new configuration I only configured it for kube-system.

> Installing `ztunnel` to a different namespace than `istiod` requires explicit configuration, in all cases.

Are all of the various places it needs to be configured documented somewhere? I haven't come across a complete list of the places updates are needed, I kind of just figured it out when I initially deployed Ambient mode on 1.22.x.

**Comment by Phenix66** [comment]
> Agreed, fair. It could have been more explicit that because the default behavior was a problem, the default behavior has changed. Since ambient is still in beta, maintaining strict back compat is not a requirement, but the relnote (that I wrote) could have been worded more explicitly.

Ah to be honest, Ambient mode has worked so well I kind of forgot it is technically a beta feature :sweat_smile: 

> Or in operator-resource-speak:
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
>   components:
>     pilot:
>       trustedZtunnelNamespace: <MY_ZTUNNEL_NS>
> ```

Thank you! That is simpler than specifying via the environment variable.

**Comment by craigbox** [comment]
> Ah to be honest, Ambient mode has worked so well I kind of forgot it is technically a beta feature 😅

Please ping me on Slack so we can publish a case study based on that sentiment :)

**Comment by Phenix66** [comment]
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
>   components:
>     pilot:
>       trustedZtunnelNamespace: <MY_ZTUNNEL_NS>
> ```

Using that config results in `Error: generate config: error unmarshaling JSON: while decoding JSON: unknown field "trustedZtunnelNamespace" in isitio.operator.v1alpha1.ComponentSpec`

It doesn't look to be a valid part of https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#ComponentSpec either. I tried nesting it under `spec.components.pilot.spec`, Istio deploys but istiod has the incorrect CA_TRUSTED_NODE_ACCOUNTS again.

This is the config that is currently working for me but I don't know if it is a recommended way of configuring it. I grepped through the manifests included in the Istio v1.23.0 release and it looks like this env var is the only place `.Values.pilot.trustedZtunnelNamespace` is used.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
        - name: CA_TRUSTED_NODE_ACCOUNTS
           value: "kube-system/ztunnel"
```

**Comment by bleggett** [comment]
https://github.com/istio/istio/pull/51311/files#diff-74a4ba6cc7c1c0c2070204a32d2f14931b8f379cd72424d5fa4639f625c3587eR982

It should be in `values_types` already.

**Comment by bleggett** [comment]
oh @Phenix66 my bad - it should be 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      trustedZtunnelNamespace: default
```

(why do we have 6 ways to do one thing? IDK - I do apologize tho)

**Comment by Phenix66** [comment]
> oh @Phenix66 my bad - it should be
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
>   values:
>     pilot:
>       trustedZtunnelNamespace: <MY_ZT_NAMESPACE>
> ```
> 
> Because the IstioOperator indirects the Helm values, but (apparently) in several different ways. (component.pilot = no, values.pilot = yes)
> 
> (why do we have 6 ways to do one thing? IDK - I do apologize tho)

That worked perfectly, thank you!

**Comment by howardjohn** [comment]
Closing since we found this is documented in https://istio.io/latest/news/releases/1.23.x/announcing-1.23/change-notes/#installation and issue resolved above. Thanks everyone.
