### ISSUE TITLE
istio-pilot failed to create discovery service:failed to register custom resources. 

### ISSUE THREAD

**Issue by nieshuai123** [istio/istio#5278]
istioctl version  0.7.1
kubectl version 1.10.1

What happened:
discovery container in istio-pilot CrashLoopBackOff from time to time. discovery container logs:
Error: failed to create discovery service: failed to register custom resources. Post https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 10.96.0.1:443: i/o timeout

What you expected to happen:
how to solve it

How to reproduce it:
install and configure Istio in a Kubernetes cluster follow https://istio.io/docs/setup/kubernetes/quick-start.html

**Comment by ostromart** [comment]
@nieshuai123 sorry for the long delay in getting to this, but it looks like it was not commonly observed so it could be an issue on your setup. If you are still experiencing this could you please add:
 - how you created your cluster
 - kubectl describe of pilot pod
 - full pilot discovery logs

**Comment by andraxylia** [comment]
Could you please try release 0.8 and re-open if you still see the issue?

**Comment by wansuiye** [comment]
1.1.3 met the same problem

**Comment by soulseen** [comment]
i met the same problem in istio-1.1.7

**Comment by panpanli521** [comment]
@nieshuai123  Have you resolved this problem?
