### ISSUE TITLE
Unexpected httpcode 502 through istio-ingressgateway after load test

### ISSUE THREAD

**Issue by k0s15** [istio/istio#52805]
Hi All,

I encountered an issue and can’t determine the root cause. 
I’m hoping someone might have some insights.

Scenario:
1. Trigger load test (say 500 con-current users access) on my Kubernetes with Istio 1.17.2.
2. During the load test, some requests was having httpcode 502 unexpectedly. 
3. And after the load test, the httpcode 502 still occurs randomly and cannot be eliminated until I had step 4. 
4. The issue can be resolved if and only if I re-create the istio-ingressgateway.

Does anyone have any suggestions or know of any configurations I should check to resolve this issue?

**Comment by howardjohn** [comment]
Istio is not generating 502 errors from the gateway itself AFAIK. So this is likely something being done by the downstream, or a proxy in front of the ingress. This will be impossible to debug without more info such as access logs, maybe a reproducer, etc., Can you give some more info?


Also note Istio 1.17 has been EOL for over a year: https://istio.io/latest/news/support/announcing-1.17-eol/

**Comment by k0s15** [comment]
To supplement, we discover the issue will happen when istio-ingressgateway is being scale out and in during the load test.
If we scale out and fixed the number of istio-ingressgateway, the issue will not happen.

Yes, we understand Istio 1.17 has been EOL and now planning to upgrade.
