### ISSUE TITLE
Ubuntu 24.04 + Vanilla k8s + Calico + 1.23 Ambient - istio-cni failing to start on 2/3 nodes

### ISSUE THREAD

**Issue by hyacin75** [istio/istio#52804]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Node are set up 100% identical save for a couple minor hardware differences on one, but two are 100% identical and one is working and one is failing.

Installed "vanilla k8s" with kubeadm, installed calico as per docs, cluster is running fine.  Following the Ambient install guide and failing at the second step, installing istio-cni from helm (though I'm having the same issue with istioctl).

Two of the pods, on the same two nodes every time, are dying and staying in a backoff loop with -

`Error: failed to create ambient nodeagent service: error configuring iptables: binary iptables-save not found in path: exit status 127`

Yet they're using the exact same image as the node it is starting successfully on, and the systems are configured the same and have iptables installed and iptables-save available (not sure if it's referring to within a container or on the host tbh).

Troubleshooting for a full day now, and all I can come up with is 'bug'

### Version

```Text
istioctl version -
Istio is not present in the cluster: no running Istio pods in namespace "istio-system"
client version: 1.23.0

kubectl version -
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3

helm version --short -
v3.15.4+gfa9efb0
```

### Additional Information

Target cluster context: vcluster

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-08-21 21:37:36.725950598 -0400 EDT

Cluster endpoint: https://vcluster-vip.mydomain.tld:6444
CLI version:
version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"go1.22.6", BuildStatus:"Clean", GitTag:"1.23.0"}

The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:

Fetching logs for the following containers:

calico-apiserver/calico-apiserver/calico-apiserver-85b898779c-779t4/calico-apiserver
calico-apiserver/calico-apiserver/calico-apiserver-85b898779c-tdwxh/calico-apiserver
calico-system/calico-kube-controllers/calico-kube-controllers-77b9c68f4-96gjf/calico-kube-controllers
calico-system/calico-node/calico-node-26pk8/calico-node
calico-system/calico-node/calico-node-4rz7x/calico-node
calico-system/calico-node/calico-node-g665r/calico-node
calico-system/calico-typha/calico-typha-7854c6d879-2xdgf/calico-typha
calico-system/calico-typha/calico-typha-7854c6d879-mq872/calico-typha
calico-system/csi-node-driver/csi-node-driver-4fcwh/calico-csi
calico-system/csi-node-driver/csi-node-driver-4fcwh/csi-node-driver-registrar
calico-system/csi-node-driver/csi-node-driver-rslkr/calico-csi
calico-system/csi-node-driver/csi-node-driver-rslkr/csi-node-driver-registrar
calico-system/csi-node-driver/csi-node-driver-v8hsn/calico-csi
calico-system/csi-node-driver/csi-node-driver-v8hsn/csi-node-driver-registrar
istio-system/istio-cni-node/istio-cni-node-dw5wb/install-cni
istio-system/istio-cni-node/istio-cni-node-jqqgj/install-cni
istio-system/istio-cni-node/istio-cni-node-r8wvj/install-cni
tigera-operator/tigera-operator/tigera-operator-77f994b5bb-mhv54/tigera-operator

Fetching Istio control plane information from cluster.

Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace calico-apiserver) The namespace is not enabled for Istio injection. Run 'kubectl label namespace calico-apiserver istio-injection=enabled' to enable it, or 'kubectl label namespace calico-apiserver istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace calico-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace calico-system istio-injection=enabled' to enable it, or 'kubectl label namespace calico-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-public) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-public istio-injection=enabled' to enable it, or 'kubectl label namespace kube-public istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-system istio-injection=enabled' to enable it, or 'kubectl label namespace kube-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace tigera-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace tigera-operator istio-injection=enabled' to enable it, or 'kubectl label namespace tigera-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service calico-apiserver/calico-api) Port name apiserver (port: 443, targetPort: 5443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service calico-system/calico-kube-controllers-metrics) Port name metrics-port (port: 9094, targetPort: 9094) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service calico-system/calico-typha) Port name calico-typha (port: 5473, targetPort: calico-typha) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service kube-system/kube-dns) Port name metrics (port: 9153, targetPort: 9153) doesn't follow the naming convention of Istio port.
Creating an archive at /home/me/bug-report.tar.gz.
Time used for creating the tar file is 143.414681ms.
Cleaning up temporary files in /tmp/bug-report.
Done.

[bug-report.tar.gz](https://github.com/user-attachments/files/16702857/bug-report.tar.gz)

Please note the cluster is _named_ vcluster, because I intend to install vcluster on it at some point, but it is not yet installed, and this is not a vcluster, it's vanilla k8s running on Ubuntu VMs running on Proxmox.

**Comment by hyacin75** [comment]
I reinstalled 24.04 on the VMs, did a Kubespray 1.30.3 install in case I'd missed something doing kubeadm myself previously - and STILL have the same results ... oddly, I think, with the issue happening on the same two nodes again.  Will try 22.04 tonight I suppose.

**Comment by hyacin75** [comment]
Reinstalled OS, 22.04, Kubespray 1.30.3, cluster working happily.  I did all this from "node3" this time rather than node1 to see if that made any difference.  I also accidentally only set node3 to do a minimal install, previously all nodes were minimal.

Get to Istio step, running everything from node3 ...

As always, node1 has a working pod, and node2 and node3 are in a crashloopbackoff, both terminating with -

`me@vcluster-03:~$ kubectl logs -n istio-system istio-cni-node-6tsnz | tail -1
Error: failed to create ambient nodeagent service: error configuring iptables: binary iptables-save not found in path: exit status 127
me@vcluster-03:~$ kubectl logs -n istio-system istio-cni-node-rgt29 | tail -1
Error: failed to create ambient nodeagent service: error configuring iptables: binary iptables-save not found in path: exit status 127
me@vcluster-03:~$
`

Guess I'll try recreating VMs next, though I can't imagine how that could possible have anything to do with a seemingly missing binary.

**Comment by howardjohn** [comment]
cc @bleggett

**Comment by bleggett** [comment]
> Yet they're using the exact same image as the node it is starting successfully on, and the systems are configured the same and have iptables installed and iptables-save available (not sure if it's referring to within a container or on the host tbh).

Our `istio` base image ships both variants, and for ambient we are only running from containers, so we attempt to select the correct in-container binary based on whether (nft|legacy) tables already have rules in them.

if we can't "tiebreak" between `nft`/`legacy` by checking rulecount, we always fall back to the local default symlink e..g `iptables`/`iptables-save`). 

My suspicion is that on some of your nodes, you _have_ `nft` rules on the node already when we come up, which is why `istio-cni-node-r8wvj` for instance picks `nft`, and doesn't have a problem.

The other nodes probably don't have any rules in either legacy or nft tables, at the time we check, so we fall back to the local default symlink.

(in this scenario it would be better to just prefer `nft`, which would mask your problem here, as mentioned over here: https://github.com/istio/istio/issues/52357#issuecomment-2253300746)

You could confirm this if you wish by installing `istio-cni` with debug logging enabled (`--set global.logging.level="all:debug"`), and you should see it fall-though the more specific choices before settling on the system symlink.

The _weird_ thing about what you're reporting tho is this: `Error: failed to create ambient nodeagent service: error configuring iptables: binary iptables-save not found in path: exit status 127`. This is _very_ odd, as Istio's `distroless` images _should_ (or did, at least) _have_ the local default symlinks of `iptables` and `iptables-save` in PATH.

Either way, I will open a PR to prefer `nft` unconditionally when we find _both_ `legacy` and `nft`, which IMO we should do anyway.

**Comment by hyacin75** [comment]
> You could confirm this theory (if you wish, no worries if not, already a great bug report) by installing istio-cni with debug logging enabled (--set global.logging.level="all:debug"), and you should see it fall-though the more specific choices before settling on the system symlink.

```
2024-08-23T00:58:56.398486Z     info    ControlZ available at 127.0.0.1:9876
2024-08-23T00:58:56.398642Z     debug   monitoring      MeterProvider created   Resource=service.name=unknown_service:install-cni,telemetry.sdk.language=go,telemetry.sdk.name=opentelemetry,telemetry.sdk.version=1.27.0 Readers=[0xc000348ac0] Views=1
2024-08-23T00:58:56.398670Z     debug   monitoring      Meter created   Name=istio Version= SchemaURL=
2024-08-23T00:58:56.398897Z     debug   cni-agent       starting UDS server for CNI plugin logs
2024-08-23T00:58:56.398973Z     info    cni-agent       Starting ambient node agent with inpod redirect mode
2024-08-23T00:58:56.399811Z     debug   cni-agent       creating ipsets in the node netns
2024-08-23T00:58:56.400565Z     debug   did not find (or cannot use) iptables binary, error was %!w(*fmt.wrapError=&{binary iptables-nft-save not found in path: exit status 127 0xc0003b58c0}): {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}
2024-08-23T00:58:56.401010Z     debug   did not find (or cannot use) iptables binary, error was %!w(*fmt.wrapError=&{binary iptables-legacy-save not found in path: exit status 127 0xc0003b5960}): {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}
Error: failed to create ambient nodeagent service: error configuring iptables: binary iptables-save not found in path: exit status 127
```

**Comment by hyacin75** [comment]
> My suspicion is that on some of your nodes, you have nft rules on the node already when we come up, which is why istio-cni-node-r8wvj for instance picks nft, and doesn't have a problem.

The number of rules are _different_, which I find odd, but it does seem to be a tie on both -

Working one -
```
me@vcluster-01:~$ sudo iptables-save | grep "^-" | wc -l
261
me@vcluster-01:~$ sudo iptables-nft-save | grep "^-" | wc -l
261
me@vcluster-01:~$
```

First not working one -
```
me@vcluster-02:~$ sudo iptables-save | grep "^-" | wc -l
227
me@vcluster-02:~$ sudo iptables-nft-save | grep "^-" | wc -l
227
me@vcluster-02:~$
```

Second non-working one, and one I installed ansible and helm on and ran Kubespray/helm install from this time -

```
me@vcluster-03:~$ sudo iptables-save | grep "^-" | wc -l
118
me@vcluster-03:~$ sudo iptables-nft-save | grep "^-" | wc -l
118
me@vcluster-03:~$
```

I guess vcluster-03 is so much lower because it's a minimal install.  Ties all around though.

**Comment by hyacin75** [comment]
> This is very odd, as Istio's distroless images should (or did, at least) have the local default symlinks of iptables and iptables-save in PATH.

I can only take a gander into the one that stays up as the others exit too quickly -

```
root@vcluster-01:/run/containerd/io.containerd.runtime.v2.task/k8s.io/dea8f0ab0a543412b740ada1779d1d773d7b1e63805ee45aeb8402281d2c6390/rootfs# find . -name iptables-save -exec ls -l {} \;
lrwxrwxrwx 1 root root 20 Dec 31  1969 ./sbin/iptables-save -> xtables-legacy-multi
root@vcluster-01:/run/containerd/io.containerd.runtime.v2.task/k8s.io/dea8f0ab0a543412b740ada1779d1d773d7b1e63805ee45aeb8402281d2c6390/rootfs# find . -name iptables -exec ls -l {} \;
-rw-r--r-- 1 root root 351 Dec 31  1969 ./etc/conf.d/iptables
total 0
lrwxrwxrwx 1 root root 20 Dec 31  1969 ./sbin/iptables -> xtables-legacy-multi
total 0
root@vcluster-01:/run/containerd/io.containerd.runtime.v2.task/k8s.io/dea8f0ab0a543412b740ada1779d1d773d7b1e63805ee45aeb8402281d2c6390/rootfs#
```

**Comment by hyacin75** [comment]
I noticed `AmbientIPv6: true` in the log output so I checked the ip6tables-legacy-save and ip6tables-nft-save on node1 and node3, both have rules in nft but none in legacy.

**Comment by hyacin75** [comment]
Oh I just found a weird difference, and maybe the only one of note between the working and non-working but practically identical systems - non-working is using kvm64 CPU, working is using "host" (Xeon something) ...

I still can't see how it could be related, but, it could be something ...

**Comment by bleggett** [comment]
> The number of rules are different node to node, which I find odd, but it does seem to be a tie on all of them (wrong command, actually seems nft should win on all of them) -

Ok, well, nevermind that theory then. That just means we actually picked the "right" binary (`iptables-nft-save`) but execing it with no args straight-up failed on those nodes.

> 2024-08-23T00:58:56.400565Z     debug   did not find (or cannot use) iptables binary, error was %!w(*fmt.wrapError=&{binary iptables-nft-save not found in path: exit status 127 0xc0003b58c0}): {DetectedBinary: DetectedSaveBinary: DetectedRestoreBinary: Version:<nil> Legacy:false ExistingRules:false}

Interesting. This means that `iptables-nft-save` [actually failed to execute on the problem nodes](https://github.com/istio/istio/blob/9de1df6de843fa482e4632c032efabe12af395f8/tools/istio-iptables/pkg/dependencies/implementation_linux.go#L51) (as in, returned a non-zero exit code when run with no args).

In this case, we got ` exit status 127` which is usually `command not found`.

> Update2: and I just fixed the 3rd by doing the same, kvm64 cpu -> Ryzen 5 4500U
> Something with KVM64 CPU, or how Ubuntu configures itself for it, not jiving with the checks somehow 😕

Weird. Literally all we are doing here is running `iptables-nft-save` with no args. If the kernel version and loaded kmods are the same across nodes, I can't imagine why execing ``iptables-nft-save` with no args on one node versus the other would fail.

I'm not _very_ familiar with Proxmox, but it seems that `kvm64` is an emulated CPU type with a reduced instruction set? 

https://my.f5.com/manage/s/article/K000092821

My hunch is something about that emulated CPU type is causing either 

- Some kmods to not be autoloaded on those nodes, because that emulated CPU type doesn't advertise the right featureset/instructionsets?
- Some kernel features are not autoenabled on those nodes,  because that emulated CPU type doesn't advertise the right featureset/instructionsets?
- Some of our in-container userspace libs  are segfaulting because that emulated CPU type doesn't advertise the right featureset/instructionsets?

**Comment by bleggett** [comment]
> Yet they're using the exact same image as the node it is starting successfully on

What is that image, exactly?

**Comment by hyacin75** [comment]
> What is that image, exactly?

Sorry, that was a LOT of data I dumped last night, lol ... it's here - https://github.com/istio/istio/issues/52804#issuecomment-2305987825

```
me@vcluster-01:~$ for pod in `kubectl get pod -n istio-system --no-headers | cut -d' ' -f1`; do kubectl get -n istio-system pod -oyaml | grep image:; done | sort | uniq
      image: docker.io/istio/install-cni:1.23.0-distroless
me@vcluster-01:~$
```


> I'm not very familiar with Proxmox, but it seems that kvm64 is an emulated CPU type with a reduced instruction set?

Correct, which allows live migration, even between AMD and Intel hypervisors, which I guess is why it's the default in the Proxmox UI, yet it's qemu under the hood, and the qemu docs linked from the F5 page you provided specifically do NOT recommend using that CPU type -

https://qemu-project.gitlab.io/qemu/system/qemu-cpu-models.html

**Comment by bleggett** [comment]
> > What is that image, exactly?
> 
> Sorry, that was a LOT of data I dumped last night, lol ... it's hiding in here - [#52804 (comment)](https://github.com/istio/istio/issues/52804#issuecomment-2305987825)
> 
> ```
> me@vcluster-01:~$ for pod in `kubectl get pod -n istio-system --no-headers | cut -d' ' -f1`; do kubectl get -n istio-system pod -oyaml | grep image:; done | sort | uniq
>       image: docker.io/istio/install-cni:1.23.0-distroless
> me@vcluster-01:~$
> ```
Sorry, I mean the _node_ image - what OS/kernel/glib/etc.

**Comment by hyacin75** [comment]
> Sorry, I mean the _node_ image - what distro/kernel/glib/etc.

Ah!

During the last round of failures I was running Ubuntu Server 22.04, I can spin up a VM later to check what the kernel/glib versions are on that.

Earlier attempts and what I've since reverted to were Ubuntu Server 24.04 minimal -

```
ldd (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
Linux vcluster-01 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bleggett** [comment]
> > What is that image, exactly?
> 
> Sorry, that was a LOT of data I dumped last night, lol ... it's hiding in here - [#52804 (comment)](https://github.com/istio/istio/issues/52804#issuecomment-2305987825)
> 
> ```
> me@vcluster-01:~$ for pod in `kubectl get pod -n istio-system --no-headers | cut -d' ' -f1`; do kubectl get -n istio-system pod -oyaml | grep image:; done | sort | uniq
>       image: docker.io/istio/install-cni:1.23.0-distroless
> me@vcluster-01:~$
> ```
> 
> > I'm not very familiar with Proxmox, but it seems that kvm64 is an emulated CPU type with a reduced instruction set?
> 
> Correct, which allows live migration, even between AMD and Intel hypervisors, which I guess is why it's the default in the Proxmox UI, yet it's qemu under the hood, and the qemu docs linked from the F5 page you provided specifically do NOT recommend using that CPU type -
> 
> https://qemu-project.gitlab.io/qemu/system/qemu-cpu-models.html

Yeah - I don't know _why_ using that kvm64 type would make something not be exec'able from path.

It might be useful to run 

`kubectl exec -it -n istio-system <istio-cni-pod-on-broken-kvm64-node> -- iptables-nft-save` and see what it does - that will run the in-container binary on the node - I'd expect that to fail on the broken nodes in the same way.

**Comment by hyacin75** [comment]
> It might be useful to run
> 
> kubectl exec -it -n istio-system <istio-cni-pod-on-broken-kvm64-node> -- iptables-nft-save and see what it does - that will run the in-container binary from inside the container, on the node (which is all istio-cni is doing here) - I'd expect that to fail on the broken nodes in the same way.

This will take some doing.  I was hoping flipping it back to kvm64 would do the trick, but no, it's running fine - it's just at that decision point during installation/setup I guess it is that things get mucked up.  I'll need to build a new node and add it to the cluster to test.  Should have time tonight (though energy may be a different story).

**Comment by antonioberben** [comment]
I've got the same issue with Istio version `1.23.2`, deployed in a Lima VM (KVM) with Kind cluster.

Deploying Istio with `variant: debug` works.

At the top, you can see that it is a KVM. On the left, installing with `variant: distroless`. On the right, the error log in the `istio-cni-node` pod

![image](https://github.com/user-attachments/assets/c840166a-1e2d-4d26-acf5-970bc1c2b72c)


This does not work:
```
istioctl install -y --set profile=ambient --set meshConfig.accessLogFile=/dev/stdout --set values.global.variant=distroless
```

this works:
```
istioctl install -y --set profile=ambient --set meshConfig.accessLogFile=/dev/stdout --set values.global.variant=debug
```

**Comment by bleggett** [comment]
@kctsengh @antonioberben 

What you two are seeing is necessarily a completely different issue, so please open a new bug.

**Comment by bleggett** [comment]
Closing this issue as the original reporter resolved the issue where only one specific node had an issue by using homogeneous node types in KVM, and using recommended machine types in KVM.
