### ISSUE TITLE
1.20.0 tag for bookinfo has an execute script error

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#52811]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The latest bookinfo app has an execute script error which causes it to not render fully:

In the chrome browser tools I see this error:
Refused to execute script from 'https://productpage.redacted.com/static/tailwind/tailwind.css' because its MIME type ('text/css') is not executable, and strict MIME type checking is enabled.

<img width="1792" alt="Screenshot 2024-08-22 at 9 14 58 AM" src="https://github.com/user-attachments/assets/60e0d234-4161-4ef7-8cd7-90806da90b50">

### Version

```Text
this is the image tag of productpage:
examples-bookinfo-productpage-v1:1.20.0
and
examples-bookinfo-productpage-v1:1.20.1
```

**Comment by howardjohn** [comment]
Does it only happen on 1.20.0? I don't think we shipped v1.20.0 with any Istio release; don't use it. 1.20.1 is what we shipped

**Comment by ceastman-r7** [comment]
I bumped bookinfo image tags to 1.20.1 but I still see the same error message in the chrome browser tools.

**Comment by peterj** [comment]
How does your setup look like? I am trying with Istio 1.23.0 (booking productpage version is `1.20.1`), metallb and Kubernetes Gateway API resources. If I open Chrome and go to `ip/productpage`, I don't see the same error. If I set up a host (`/etc/hosts`) (e.g. `bookinfo.internal`), I still don't see the error.

Is there anything in your setup that's different from mine? Do you have a tls cert set up? (I haven't tried it with that)
