### ISSUE TITLE
Per pod 'emergency off'

### ISSUE THREAD

**Issue by costinm** [istio/istio#5281]
I think we need at least minimal support for 0.8 - based on a prod incident. 
If something goes wrong, user needs to have a documented and (relatively) fast way to turn off 
Istio features on a pod, and allow it to operate in degraded mode. 

The behavior can be (long term):
- selectively disable features - telemetry, policy, MTLS
- disable inbound interception - which also means MTLS, telemetry and policy checks will be off
- disable outbound interception on select services - losing routing rules (fallback to kube-proxy behavior)

Not clear what is the minimal viable subset for 0.8 - might be just documentation of per-pod env  
variable to turn off interception (and more doc on migrating to istio - since such a pod will behave
like pods getting migrated to Istio, i.e. with only default routes, no mtls, etc)

As background, for some (yet unknown) cause a pod failed to receive listeners, resulting in 
probe failures and crashes, and eventually more pods got into this state. In most cases users 
should be able to turn off some features while the root cause is mitigated, or to isolate 
and quickly determine if Istio is causing the issue. While in this example we suspect istio was
not causing the issue, it is important to have a way to quickly verify this. 

Note that in 0.8 it is possible to pass a subset of sidecar env variables to pilot (as used for TPROXY),
and make decisions on pilot based on the pod settings, overriding global settings.

**Comment by Stono** [comment]
Most definitely agree with this.  As I put in email the other day, the blast radius for istio going wrong is potentially extremely high, and having the ability to toggle things on or off at run time would definitely ease the concerns.

I suppose my slight worry is that if a pod wasn't receiving listeners/configuration correctly, in such a scenario what confidence would we have that it would receive "kill switch" style configuration either?

It'd have to be some method that sits outside of the main configuration distribution mechanisms.

**Comment by hklai** [comment]
Not release blocking per discussion with @costinm @louiscryan and @jasminejaksic.

**Comment by cmluciano** [comment]
cc @ozevren @xiaolanz . This feels like the intent of Galley.
