### ISSUE TITLE
Support TLS Sniffing/MultiplexPort on Envoy Side

### ISSUE THREAD

**Issue by costinm** [istio/istio#5282]
For tracking, Security and Networking WG consider transparent MTLS as critical for 0.8 customers.

The envoy PR seems to be in but there are still config changes in pilot and testing left. 
We need to evaluate the status and decide if we continue to delay 0.8 or we push this to 0.9/1.0 (
and possibly cherry-pick this feature into a 0.8.x )

**Comment by andraxylia** [comment]
This issue will track TLS sniffing for the purpose of incremental mTLS adoption and health checking, which are required for 1.0.

SNI routing will be tracked by #5455

**Comment by PiotrSikora** [comment]
Health checking was supposed to be fixed by https://github.com/kubernetes/kubernetes/issues/60952 and not TLS sniffing.

cc @wattli

**Comment by andraxylia** [comment]
Last I know is TLS sniffing will be use as a short term solution, until k8s implements mTLS for kubelet.

**Comment by wattli** [comment]
@PiotrSikora , we will still use TLS sniffing for health check, once your envoy PR is in, I will take care of it. K8s does not have plan to support it.

**Comment by PiotrSikora** [comment]
This has been implemented a while ago:
1) SNI-based routing: https://github.com/envoyproxy/envoy/commit/a328bc5d69a9e90ed3197a6735997ec48a850351, https://github.com/envoyproxy/envoy/commit/93780c1663a89c596e46a43ff17cffc25bb00b18,
2) ALPN-based routing: https://github.com/envoyproxy/envoy/commit/554e57a89e95a9d9bed684e5d663d217a1ea502c, https://github.com/envoyproxy/envoy/commit/12c470e666d23f1cedaea92cdae6c747d6081dfe.
