### ISSUE TITLE
Jitter in DNS resolution

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52877]
Now that https://github.com/envoyproxy/envoy/issues/35641 and https://github.com/envoyproxy/envoy/pull/35745 are resolved, should we enable some dns resolution jitter by default in Istio?

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
+1, I don't see any reason not to make it by default. We can have a feature flag to turn it off

**Comment by Stevenjin8** [comment]
@howardjohn By feature flag, do you mean a flag like ISTIO_META_DNS_CAPTURE`?

**Comment by howardjohn** [comment]
Yes but that one is on each proxy.. we can probably just have a global in Istiod.
