### ISSUE TITLE
Ztunnel Sock permission denied

### ISSUE THREAD

**Issue by yankees5963** [istio/istio#52876]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When deploying ambient mode either in helm or istioctl, everything says running but ztunnel logs show: `warn	inpod::workloadmanager	failed to connect to server "/var/run/ztunnel/ztunnel.sock": Os { code: 13, kind: PermissionDenied, message: "Permission denied" }. retrying in 15s`

Kubernetes; RKE2
Base OS: RHEL8 with FIPS and SELINUX enforcing
CIS benchmark applied

### Version

```Text
istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (3 proxies)
kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3+rke2r1
```

### Additional Information

istioctl bug-report

Target cluster context: default

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2024-08-27 08:14:17.533503641 -0400 EDT

Cluster endpoint: https://10.114.7.253:6443
CLI version:
version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"go1.22.6", BuildStatus:"Clean", GitTag:"1.23.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Revision:  "default",
        Info:      version.BuildInfo{Version:"1.23.0", GitRevision:"d0ca037e58f90f58b38b33c5769fec25b6bfa9f3", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.23.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.23.0}

Fetching logs for the following containers:

argocd/argocd-applicationset-controller/argocd-applicationset-controller-657d5c74c9-hn9sx/applicationset-controller
argocd/argocd-dex-server/argocd-dex-server-69b4f85cdb-vvvmz/dex-server
argocd/argocd-notifications-controller/argocd-notifications-controller-8484fbdbfc-6wblc/notifications-controller
argocd/argocd-redis/argocd-redis-6ddc76cf75-8kr8z/redis
argocd/argocd-repo-server/argocd-repo-server-5fcd885c8-ggrv2/repo-server
argocd/argocd-server/argocd-server-f96d6c6b9-qppsm/server
argoflow/argoflow-argo-workflows-server/argoflow-argo-workflows-server-59f8d65875-tzbvq/argo-server
argoflow/argoflow-argo-workflows-workflow-controller/argoflow-argo-workflows-workflow-controller-8684c5f4f4-pf4hn/controller
cert-manager/cert-manager-cainjector/cert-manager-cainjector-7477d56b47-c726x/cert-manager-cainjector
cert-manager/cert-manager-webhook/cert-manager-webhook-6d5cb854fc-cs8fl/cert-manager-webhook
cert-manager/cert-manager/cert-manager-84489bc478-8nlc4/cert-manager-controller
cert-manager/trust-manager/trust-manager-85ff4d597d-m8k8p/trust-manager
coder/coder-saszala-saszala/coder-saszala-saszala-65777d5f79-znqsp/dev
coder/coder/coder-67bc5c4f8c-hjqmm/coder
external-secrets/external-secrets-cert-controller/external-secrets-cert-controller-b49486bfb-thmnp/cert-controller
external-secrets/external-secrets-webhook/external-secrets-webhook-55d559b668-hvsp5/webhook
external-secrets/external-secrets/external-secrets-56bc947c46-g29fp/external-secrets
gitlab-runner/cpu-runner-gitlab-runner/cpu-runner-gitlab-runner-7fb6fcf998-69kr7/cpu-runner-gitlab-runner
gitlab-runner/gpu-runner-gitlab-runner/gpu-runner-gitlab-runner-67cbcc9f67-kc67v/gpu-runner-gitlab-runner
homepage/homepage/homepage-74dbcc98f-wnl9n/homepage
istio-system/istio-cni-node/istio-cni-node-plw7h/install-cni
istio-system/istio-cni-node/istio-cni-node-xmc8g/install-cni
istio-system/istio-cni-node/istio-cni-node-zr2jz/install-cni
istio-system/istiod/istiod-74b46f46fb-mfrml/discovery
istio-system/ztunnel/ztunnel-fbf9m/istio-proxy
istio-system/ztunnel/ztunnel-lg2zv/istio-proxy
istio-system/ztunnel/ztunnel-rvrsp/istio-proxy
kubecost/kubecost-cost-analyzer/kubecost-cost-analyzer-dcf85476b-b2bj9/aggregator
kubecost/kubecost-cost-analyzer/kubecost-cost-analyzer-dcf85476b-b2bj9/cloud-cost
kubecost/kubecost-cost-analyzer/kubecost-cost-analyzer-dcf85476b-b2bj9/cost-analyzer-frontend
kubecost/kubecost-cost-analyzer/kubecost-cost-analyzer-dcf85476b-b2bj9/cost-model
kubecost/kubecost-forecasting/kubecost-forecasting-54bdb9d8f9-tsz6t/forecasting
metafig/metafig/metafig-5b49698774-vlk28/metafig
mlflow/mlflow-run/mlflow-run-665c46d9fb-vlcgr/mlflow
mlflow/mlflow-tracking/mlflow-tracking-67c49587b5-zwcrv/mlflow
monitoring/monitoring-gitlab-ci-pipelines-exporter/monitoring-gitlab-ci-pipelines-exporter-7c7fd6d66c-zxpzl/gitlab-ci-pipelines-exporter
monitoring/monitoring-grafana/monitoring-grafana-67d5c5599f-bd4sr/grafana
monitoring/monitoring-kube-state-metrics/monitoring-kube-state-metrics-556968cddf-skpk5/kube-state-metrics
monitoring/monitoring-metrics-server/monitoring-metrics-server-77679ff97b-xxr9n/metrics-server
monitoring/monitoring-prometheus-node-exporter/monitoring-prometheus-node-exporter-nszkx/node-exporter
monitoring/monitoring-prometheus-node-exporter/monitoring-prometheus-node-exporter-qzclh/node-exporter
monitoring/monitoring-prometheus-node-exporter/monitoring-prometheus-node-exporter-x7rkt/node-exporter
monitoring/monitoring-prometheus-pushgateway/monitoring-prometheus-pushgateway-5ccc6654f8-qnxn6/pushgateway
monitoring/monitoring-prometheus-server/monitoring-prometheus-server-57cdb88d47-q82zw/prometheus-server
monitoring/monitoring-prometheus-server/monitoring-prometheus-server-57cdb88d47-q82zw/prometheus-server-configmap-reload
neuvector/neuvector-controller-pod/neuvector-controller-pod-766b7c74cb-6xzz4/neuvector-controller-pod
neuvector/neuvector-controller-pod/neuvector-controller-pod-766b7c74cb-c97z9/neuvector-controller-pod
neuvector/neuvector-controller-pod/neuvector-controller-pod-766b7c74cb-t5grg/neuvector-controller-pod
neuvector/neuvector-enforcer-pod/neuvector-enforcer-pod-nxfsg/neuvector-enforcer-pod
neuvector/neuvector-enforcer-pod/neuvector-enforcer-pod-tcz9w/neuvector-enforcer-pod
neuvector/neuvector-manager-pod/neuvector-manager-pod-6bdcf9f69d-jhzq2/neuvector-manager-pod
neuvector/neuvector-scanner-pod/neuvector-scanner-pod-7bc884648d-cw4q9/neuvector-scanner-pod
neuvector/neuvector-scanner-pod/neuvector-scanner-pod-7bc884648d-jvbvs/neuvector-scanner-pod
neuvector/neuvector-scanner-pod/neuvector-scanner-pod-7bc884648d-vrp8h/neuvector-scanner-pod
velero/node-agent/node-agent-cmrvs/node-agent
velero/node-agent/node-agent-jvt6f/node-agent
velero/velero/velero-7d7db57c6c-7wxq2/velero

Fetching Istio control plane information from cluster.

Fetching CNI logs from cluster.

Running Istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace argocd) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argocd istio-injection=enabled' to enable it, or 'kubectl label namespace argocd istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace argoflow) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argoflow istio-injection=enabled' to enable it, or 'kubectl label namespace argoflow istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace coder) The namespace is not enabled for Istio injection. Run 'kubectl label namespace coder istio-injection=enabled' to enable it, or 'kubectl label namespace coder istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace external-secrets) The namespace is not enabled for Istio injection. Run 'kubectl label namespace external-secrets istio-injection=enabled' to enable it, or 'kubectl label namespace external-secrets istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace gitlab-runner) The namespace is not enabled for Istio injection. Run 'kubectl label namespace gitlab-runner istio-injection=enabled' to enable it, or 'kubectl label namespace gitlab-runner istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace gpu) The namespace is not enabled for Istio injection. Run 'kubectl label namespace gpu istio-injection=enabled' to enable it, or 'kubectl label namespace gpu istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace homepage) The namespace is not enabled for Istio injection. Run 'kubectl label namespace homepage istio-injection=enabled' to enable it, or 'kubectl label namespace homepage istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kafka) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kafka istio-injection=enabled' to enable it, or 'kubectl label namespace kafka istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace keycloak) The namespace is not enabled for Istio injection. Run 'kubectl label namespace keycloak istio-injection=enabled' to enable it, or 'kubectl label namespace keycloak istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-public) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-public istio-injection=enabled' to enable it, or 'kubectl label namespace kube-public istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kube-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-system istio-injection=enabled' to enable it, or 'kubectl label namespace kube-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kubecost) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kubecost istio-injection=enabled' to enable it, or 'kubectl label namespace kubecost istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace metafig) The namespace is not enabled for Istio injection. Run 'kubectl label namespace metafig istio-injection=enabled' to enable it, or 'kubectl label namespace metafig istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace mlflow) The namespace is not enabled for Istio injection. Run 'kubectl label namespace mlflow istio-injection=enabled' to enable it, or 'kubectl label namespace mlflow istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace monitoring) The namespace is not enabled for Istio injection. Run 'kubectl label namespace monitoring istio-injection=enabled' to enable it, or 'kubectl label namespace monitoring istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace neuvector) The namespace is not enabled for Istio injection. Run 'kubectl label namespace neuvector istio-injection=enabled' to enable it, or 'kubectl label namespace neuvector istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace redis) The namespace is not enabled for Istio injection. Run 'kubectl label namespace redis istio-injection=enabled' to enable it, or 'kubectl label namespace redis istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace spark) The namespace is not enabled for Istio injection. Run 'kubectl label namespace spark istio-injection=enabled' to enable it, or 'kubectl label namespace spark istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace test) The namespace is not enabled for Istio injection. Run 'kubectl label namespace test istio-injection=enabled' to enable it, or 'kubectl label namespace test istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace velero) The namespace is not enabled for Istio injection. Run 'kubectl label namespace velero istio-injection=enabled' to enable it, or 'kubectl label namespace velero istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service argoflow/argoflow-argo-workflows-server) Port name  (port: 2746, targetPort: 2746) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service external-secrets/external-secrets-webhook) Port name webhook (port: 443, targetPort: 10250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service homepage/homepage) Port name  (port: 3000, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service metafig/metafig) Port name  (port: 8501, targetPort: 8501) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service monitoring/monitoring-grafana) Port name service (port: 80, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service kube-system/monitoring-kube-prometheus-kubelet) Port name cadvisor (port: 4194, targetPort: 4194) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service monitoring/monitoring-prometheus-node-exporter) Port name metrics (port: 9100, targetPort: 9100) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service neuvector/neuvector-service-webui) Port name manager (port: 8443, targetPort: 8443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service neuvector/neuvector-svc-admission-webhook) Port name admission-webhook (port: 443, targetPort: 20443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service neuvector/neuvector-svc-controller) Port name cluster-tcp-18300 (port: 18300, targetPort: 18300) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service neuvector/neuvector-svc-controller) Port name cluster-tcp-18301 (port: 18301, targetPort: 18301) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service neuvector/neuvector-svc-crd-webhook) Port name crd-webhook (port: 443, targetPort: 30443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service spark/spark-master-svc) Port name cluster (port: 7077, targetPort: cluster) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service cert-manager/trust-manager-metrics) Port name metrics (port: 9402, targetPort: 9402) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service cert-manager/trust-manager) Port name webhook (port: 443, targetPort: 6443) doesn't follow the naming convention of Istio port.
Creating an archive at /home/coder/bug-report.tar.gz.
Time used for creating the tar file is 542.200952ms.
Cleaning up temporary files in /tmp/bug-report.
Done.

**Comment by yankees5963** [comment]
not sure if its a issue with selinux since its permission denied but pods are running in priv. namespace

**Comment by howardjohn** [comment]
just a guess but there is probably some part of the "openshift ambient" profile that would fix this. I think there is some selinux override there

**Comment by yankees5963** [comment]
> just a guess but there is probably some part of the "openshift ambient" profile that would fix this. I think there is some selinux override there

Setting `profile: openshift-ambient` on only the ztunnel conf has everything running healthy now.

**Comment by bleggett** [comment]
Weirdly, that override is defined as a `global` in the Helm profile (which is wrong, it's only referenced in `ztunnel`).

**Comment by bleggett** [comment]
You can also set `ztunnel.seLinuxOptions` directly, if you don't want the whole openshift profile: https://github.com/istio/istio/blob/master/manifests/charts/ztunnel/values.yaml#L96

we just need `spc_t` on ztunnel.

**Comment by howardjohn** [comment]
Closing as this has been resolved. Thanks everyone
