### ISSUE TITLE
Subtle undocumented metrics changes between 1.22 and 1.23

### ISSUE THREAD

**Issue by Stono** [istio/istio#52897]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

A subtle metrics change in the istio 1.23 release caught us out.

If we have a Service Entry, and Virtual Service for an external host (which we do a lot, as we use tls origination to get the http metrics) historically `destination_service_namespace` used to be `unknown`, which makes sense, as the workload isn't in a namespace.  We had a bunch of prometheus matchers based on the expectation that is unset for off-cluster destinations, so here is a metric example from 1.22.4:

```
istio_requests_total{reporter="source",source_workload="insurance-partner-service",source_workload_namespace="insurance-partner-service",source_app="insurance-partner-service",destination_workload="unknown",destination_workload_namespace="unknown",destination_service="www.moneysupermarket.com",destination_canonical_service="unknown",destination_service_name="www.moneysupermarket.com",destination_service_namespace="unknown",response_code="200",response_flags="-"} 133
```

However, on `1.23` - `destination_service_namespace` now seems to be set to the namespace that the `ServiceEntry` / `VirtualService` resides in, eg:

```
istio_requests_total{reporter="source",source_workload="insurance-partner-service",source_workload_namespace="insurance-partner-service",source_app="insurance-partner-service",destination_workload="unknown",destination_workload_namespace="unknown",destination_service="www.moneysupermarket.com",destination_canonical_service="unknown",destination_service_name="www.moneysupermarket.com",destination_service_namespace="insurance-partner-service",response_code="200",response_flags="-"} 1767424
```

It'd be good to know if this change is intentional or not.

The documentation [here](https://istio.io/latest/docs/reference/config/metrics/) just says:

"Destination Service Namespace: This identifies the namespace of destination service." 

So i think it's a bit ambiguous/subject to terminology overload, yes the service is defined in that namespace (eg via a service entry) but there is no "service". 

### Version

```Text
1.23.0
```

**Comment by hzxuzhonghu** [comment]
maybe not intended, but setting to SE namespace looks reasonable from my perspective

**Comment by Stono** [comment]
Yeah I _think_ i agree if we're saying the **service** in `source|destination_service_` metrics isn't kubernetes service, it's any "service"; eg a serviceEntry too.

Definitely worth confirming if it was intentional or not, and i'm guessing if not it highlights some missing tests around metric labels for service entries.

**Comment by keithmattix** [comment]
This was intentional; it was part of a bug fix here: https://github.com/istio/proxy/pull/5617

**Comment by Stono** [comment]
Fair enough, @keithmattix do you want me to close this? is there anything to do here?
As a user it'd be good to see any metric label changes in release notes but unsure how programatically you can ensure that happens

**Comment by keithmattix** [comment]
Ah yeah we don't have auto release notes for the proxy repo; that's a gap. But yeah you can probably close this
