### ISSUE TITLE
Timeouts where headers have been sent are not included in outlierDetection

### ISSUE THREAD

**Issue by Stono** [istio/istio#52900]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Whilst investigating https://github.com/istio/istio/issues/52879; i noticed that outlier detection was not working in that particular use case.

It looks to be because the response code was `200UT`, because the destination sent the HTTP headers, but did not complete the body.  I would assume this is because its response code that's being considered, not response flags.

A `UT` (upstream timeout) is still an upstream failure in my eyes, and should be captured by outlier detection, and that upstream pod should be evicted as per the eviction policy.

Because of this; the pod was never evicted and errors continued.

### Version

```Text
1.23
```

**Comment by keithmattix** [comment]
Interesting....yeah this feels like an envoy behavioral decision; I'll try and find time to investigate
