### ISSUE TITLE
HTTPRetry applies to GRPC too

### ISSUE THREAD

**Issue by alexlo03** [istio/istio#52905]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

[HTTPRetry](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry) and 
[meshConfig.defaultHttpRetryPolicy](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig ) are labeled as "HTTP" but really the status codes it takes are for HTTP and GRPC, you can see [the union list here in the src](https://github.com/istio/istio/blob/447d3d80d58e527fdacf430ea41be6090e6cbc8d/pkg/config/validation/validation.go#L81)

### Version

```Text
Any
```

**Comment by howardjohn** [comment]
Yes, Grpc is Http. Most of our APIs do not specifically reference Grpc except for the (rare) Grpc specific things

**Comment by alexlo03** [comment]
alright feel free to close but IMO it is not easy to figure that out.
