### ISSUE TITLE
Install: Makes Waypoint TopologySpreadConstraints, Tolerations & NodeSelector Configurable

### ISSUE THREAD

**Issue by bmagic** [istio/istio#52901]
**Describe the feature request**
Provide the ability to customize waypoint deployment topology spread constraint, tolerations & nodeSelector during installation through Helm values.
I have already done the code here: https://github.com/istio/istio/compare/master...bmagic:istio:feature/waypoint-scheduling-options
I'm waiting for your approval to open a PR here. 

**Describe alternatives you've considered**

- Manually reconfiguring configmap/static-waypoint-config with the necessary config.

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This request is similar to https://github.com/istio/istio/issues/51496 & https://github.com/istio/istio/issues/52883

**Comment by danehans** [comment]
Aside from using global values, e.g. `.Values.global.waypoint.tolerations`, your changes LGTM. I'm also unsure if `manifests/sample-charts/ambient/Chart.lock` should be included.
