### ISSUE TITLE
Install: Makes Waypoint replicas & hpa configurable

### ISSUE THREAD

**Issue by bmagic** [istio/istio#52923]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Provide the ability to customize waypoint replicas & hpa during installation through Helm values.
I have already done the code here: https://github.com/istio/istio/compare/master...bmagic:istio:feature/waypoint-hpa
I'm waiting for your approval to open a PR here.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This request is similar to https://github.com/istio/istio/issues/51496, https://github.com/istio/istio/issues/52883, https://github.com/istio/istio/issues/52901

However, with the current implementation it's not easy to delete hpa that have been created. If a user activates the hpa and then deactivates it, the HPA resource will not be deleted. The current controller reconciliation only renders the configmap.
If necessary, I can modify the code, but this will have a greater impact on the way waypoints are reconciled.

**Comment by howardjohn** [comment]
HPA can be done, see https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#resource-attachment-and-scaling. I would tend to prefer that approach

**Comment by bmagic** [comment]
Thx I close this issue.
