### ISSUE TITLE
Istio Ambient mode - ztunnel is not working in EKS

### ISSUE THREAD

**Issue by anuraj-narayanan** [istio/istio#52937]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

ztunnel pod is not starting in the istio-system namespace when trying the Ambient mode in AWS EKS. Its failed with error XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012/. Detailed trace is below

│ 2024-08-29T11:32:02.610493Z info hyper_util listener established address=:15021 component="readiness" │
│ 2024-08-29T11:32:02.610641Z info app shared proxy mode - in-pod mode enabled │
│ 2024-08-29T11:32:02.610716Z info hyper_util listener established address=127.0.0.1:15000 component="admin" │
│ 2024-08-29T11:32:02.610737Z info hyper_util listener established address=:15020 component="stats" │
│ 2024-08-29T11:32:02.610748Z info readiness Task 'dns proxy' complete (1.682099ms), still awaiting 3 tasks │
│ 2024-08-29T11:32:02.610751Z info readiness Task 'proxy' complete (1.686441ms), still awaiting 2 tasks │
│ 2024-08-29T11:32:02.646194Z warn xds::client:xds{id=1} XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012/: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 20ms │
│ 2024-08-29T11:32:02.701952Z warn xds::client:xds{id=2} XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012/: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 40ms │
│ 2024-08-29T11:32:02.758201Z warn xds::client:xds{id=3} XDS client connection error: gRPC connection error connecting to https://istiod.istio-system.svc:15012/: status: Unknown, message: "ztunnel requi │
│ res PILOT_ENABLE_AMBIENT=true", retrying in 80ms

### Version

```Text
$ istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.22.0 (6 proxies), 1.23.0 (1 proxies)
$ kubectl version
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.28.11-eks-db838b0
```

**Comment by RonPortnoy** [comment]
you should add to istio pilot this env's:
 PILOT_ENABLE_AMBIENT=true
 PILOT_ENABLE_AMBIENT_WAYPOINTS=true

**Comment by howardjohn** [comment]
Specifically you should set `--set profile=ambient` during install so you don't need to track all the internal env vars required.

**Comment by ssichynskyi** [comment]
Same story when installing Istio Ambient using helm charts. Without setting this in istiod values, it won't work and will fail with the above mentioned errors:
```yaml
        _internal_defaults_do_not_set:
          #...
          env:
            PILOT_ENABLE_AMBIENT: true
            PILOT_ENABLE_AMBIENT_WAYPOINTS: true
```

**Comment by howardjohn** [comment]
@ssichynskyi do not set the values labeled `_internal_defaults_do_not_set`.

**Comment by ssichynskyi** [comment]
> [@ssichynskyi](https://github.com/ssichynskyi) do not set the values labeled `_internal_defaults_do_not_set`.

Where shall I set them then? This is the only section in values file.

**Comment by howardjohn** [comment]
When using helm you should not copy+paste the values.yaml file from the repo. That is the default values. You provide your own to override it. Don't set the _internal_defaults_do_not_set in the overrides.

**Comment by ssichynskyi** [comment]
@howardjohn  do you mean, I have to simply use the contents of  the head section `_internal_defaults_do_not_set` without head section itself? I've tried this and it works, but that's weird, never faced anything similar.

**Comment by howardjohn** [comment]
@ssichynskyi when you run a command like `helm install <chartname> -f values.yaml` -- don't pass a values.yaml file with EVERY value of the chart. Those are hardcoded defaults into the chart itself.

You only need to put overrides into values.yaml. If you have nothing to override, leave the file empty entirely.

If you want to set 1 field, just set 1 field.

**Comment by ssichynskyi** [comment]
@howardjohn that's obvious. However, it usually does no harm when overwriting a default value with default value. Do you mean that in this case it  could cause issues?

**Comment by howardjohn** [comment]
Yes, due to the way our charts handle things it is. You can either not override all of them, or just strip the _internal_defaults_do_not_set prefix. You can see the reasoning behind why we do it in https://blog.howardjohn.info/posts/advanced-helm/#profiles

**Comment by ssichynskyi** [comment]
@howardjohn thanks for the inside! Now the idea of the profiles and the way files are organized makes more sense. It, however, complicates things for me since I'm trying to deploy istio components using ArgoCD, not normal `$ helm install ...` commands where profiles are set. I need to clarify how to match this.

**Comment by howardjohn** [comment]
argo shouldn't really change anything you can still just pass helm values in the spec
