### ISSUE TITLE
egress gateway not creating - Failed to assign to any requested addresses: hostname \"egress.istio-egress.svc.cluster.local\" not found"

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#52933]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Trying to deploy an egress gateway using the waypoint proxy: 
based upon this doc https://istio.io/latest/docs/ambient/usage/waypoint/#deploy-a-waypoint-proxy
and this blog: https://www.solo.io/blog/egress-gateways-made-easy/

The gateway remains in a "PROGRAMMED" false state.

### Version

```Text
istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (11 proxies)

kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.29.7-eks-2f46c53
```

### Additional Information

[bug-report.tar.gz](https://github.com/user-attachments/files/16807563/bug-report.tar.gz)

**Comment by howardjohn** [comment]
```
{"level":"error","time":"2024-08-29T22:07:24.540321Z","scope":"controllers","msg":"error handling istio-egress/egress, retrying (retry count: 4): apply failed: patch apps/v1, Kind=Deployment/istio-egress/egress: admission webhook \"validate.kyverno.svc-fail\" denied the request: \n\nresource Deployment/istio-egress/egress was blocked due to the following policies \n\nallowed-registries-r7-istio-xgress:\n  autogen-r7-repos-istio-auto: All images in this Pod must come from an authorized\n    repository.\n","controller":"gateway deployment"}
```

from your istiod logs

**Comment by ceastman-r7** [comment]
ah thank you.

**Comment by ceastman-r7** [comment]
I found this while trying to troubleshoot this issue: is the following still needed

`istiod:
  pilot:
    env:
      PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
`

**Comment by howardjohn** [comment]
only if you need the alpha APIs (tcp route, tls route, etc)

**Comment by ceastman-r7** [comment]
got it, thank you.
