### ISSUE TITLE
istio can't deploy istiod and ingress gateway on same node

### ISSUE THREAD

**Issue by king311247** [istio/istio#52940]
environment:
kubernetes 1.30+Flannel  3master+1worker

istio version 1.22

istio install command: istioctl install --set profile=default

result:
istiod start successful
ingress gateway start failed (but there's no problem when ingress gateway on diff node)

![image](https://github.com/user-attachments/assets/a296d18a-42da-4b84-b1fc-c19ab66510ae)

**Comment by zirain** [comment]
> > is istiod health?
> > this's more like a cni problem, dataplane(gateway/sidecar) need to connect to controlplane(istiod), logs show there's a traffic problem.
> 
> istiod is health. When not on the same node, everything is normal.

please check you container network first.
