### ISSUE TITLE
Outlier Detection | How to get details of ejected pod of Upstream service

### ISSUE THREAD

**Issue by sandeepsharmadevops** [istio/istio#52962]
### Is this the right place to submit this?

- [X] This is not a question about how to use Istio
- [X] This is not a security vulnerability or a crashing bug

### Bug Description
We are using Outlier Detection to eject the problematic hosts/pods of the upstream service, below are the settings applied to Kubernetes services.
```
outlierDetection:
      splitExternalLocalOriginErrors: true
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
```

We are using the below query in Grafana to get the details about the active ejections, and it works fine.
```
envoy_cluster_outlier_detection_ejections_active{cluster_name="outbound|port||svcname.default.svc.cluster.local"}
```

Now, we additionally need the ejected pod details of the upstream service, tried using available filters i.e. **pod** & **kubernetes_pod_name**, but unfortunately these filters show the calling/downstream service pods.

So, I wanted to know if this is the desired behavior? is this possible to get the details of ejected pods of the upstream service, if yes please share some references to be followed.

Thanks

### Version

```Text
Kubectl version
1. Client version - v1.29.3
2. kustomize version - v5.0.4-0
3. Server version - v1.29.6

Istio version - 1.20
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by sandeepsharmadevops** [comment]
Hi Team,

Please let me know about the feasibility, with some ref.

THanks

**Comment by ramaraochavali** [comment]
I do not think there are metrics to tell which pods are ejected via outlier. You can enable  outlierLogPath https://istio.io/latest/docs/reference/commands/pilot-agent/ and it should record the events in the log

**Comment by sandeepsharmadevops** [comment]
Thanks for the confirmation @ramaraochavali
