### ISSUE TITLE
ARM cluster networking is flaky

### ISSUE THREAD

**Issue by dgn** [istio/istio#52965]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Our ARM tests on prow seem to be flaky. I found instances of both the [ARM unit tests](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52896/unit-tests-arm64_istio/1830358575755563008) and the [ARM integration tests](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52942/integ-basic-arm64_istio_release-1.23/1830583193686773760) failing with errors that are unrelated to the actual changes in the PR. They all look like this:
```
...
 * [new tag]             1.9.9            -> 1.9.9
$ PWD=/home/prow/go/src/istio.io/istio GIT_SSH_COMMAND=/usr/bin/ssh -o UserKnownHostsFile=/tmp/known_hosts git fetch --filter=blob:none https://github.com/istio/istio.git b468779ff09d9522ec30cd4ae1fabcdd1f2a80dd (runtime: 2.662625934s)
From https://github.com/istio/istio
 * branch                b468779ff09d9522ec30cd4ae1fabcdd1f2a80dd -> FETCH_HEAD
$ PWD=/home/prow/go/src/istio.io/istio GIT_SSH_COMMAND=/usr/bin/ssh -o UserKnownHostsFile=/tmp/known_hosts git checkout b468779ff09d9522ec30cd4ae1fabcdd1f2a80dd (runtime: 13.155607113s)
error: RPC failed; HTTP 400 curl 92 HTTP/2 stream 3 was not closed cleanly: CANCEL (err 8)
fatal: expected 'packfile'
fatal: could not fetch c1ff78b6d08dbb302d07969124bcfd7da3d7d063 from promisor remote
# Error: exit status 128
# Final SHA: 
# Total runtime: 0s
```

They will usually pass on the third or fourth execution.

### Version

```Text
current
```

**Comment by howardjohn** [comment]
This is from GCP networking, there isn't really anything we can do AFAIK other than replace the nodes.
