### ISSUE TITLE
Performance updates and tests

### ISSUE THREAD

**Issue by Stevenjin8** [istio/istio#52977]
Need to re-run performance benchmarks for Istio 1.24 and update the site https://istio.io/latest/docs/ops/deployment/performance-and-scalability/. Hopefully, this should also add some way of automating these tests to make them easier to run.

**Comment by Stevenjin8** [comment]
@linsun Just to update the performance page, I will run tests on a similar hardware as before, but on AKS. But to automate, I imagine I'll need some google cloud credentials.

**Comment by MorrisLaw** [comment]
cc/ @justinpettit

**Comment by MorrisLaw** [comment]
> @linsun Just to update the performance page, I will run tests on a similar hardware as before, but on AKS. But to automate, I imagine I'll need some google cloud credentials.

cc/ @justinpettit

**Comment by Stevenjin8** [comment]
@dhawton @Shuayb1 @zengyuxing007 Hello, could any of you point me to the code used for the Ambient 1.22 performance tests?
* What CNCF hardware did you do? Given that they provide only bare metal, how did you set up a k8 cluster?
* Do you have scripts to run the tests? The current ones in istio/tools/perf don't reference Ambient at all.
* How did you measure memory usage per request in your load tests?

@linsun How important is it that we test on CNCF hardware? Would Azure Kubernetes Service also work? Is our main priority updating the latency metrics?

**Comment by Stevenjin8** [comment]
@linsun bump

**Comment by Stevenjin8** [comment]
Closed by https://github.com/istio/istio.io/pull/15727
