### ISSUE TITLE
AUTO_PASSTHROUGH XDS generation doesn't de-duplicate services across gateway servers

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#52979]
Code: https://github.com/istio/istio/blob/178bdd781ff64abcd3ca4135d088001aef8489c1/pilot/pkg/networking/core/gateway.go#L879

The code is basically

```
for gateway.spec.server {
  for service {  build FC if it matches a gw host }
}
```

This means if there is a host in 2 different `server`s (likely this is from 2 Gateways) that matches the same service, we get a duplicate filter chain matcher, which leads to envoy NACK

**Comment by NancyR17** [comment]
envoy NACK issue caused by duplicate filter chain matchers, for gateway in gateways:
    for server in gateway.spec.servers:
        for service in services:
            if service.hostnames intersect with server.hostnames:
                build filter chain for the service

**Comment by goku321** [comment]
Is this up for grabs?

**Comment by ramaraochavali** [comment]
yes. Please feel free to take.

**Comment by goku321** [comment]
Thanks @ramaraochavali

**Comment by linsun** [comment]
Hi @goku321, thanks for picking up this one! What is your ETA for getting a PR out? I'm not sure if @howardjohn is already working on it.

**Comment by goku321** [comment]
Hello @linsun probably by Friday. Would that be okay?

**Comment by linsun** [comment]
That sounds good, thanks @goku321!

**Comment by yuval-k** [comment]
this also happens if one defines an empty subset (i.e. `{}`) in a destination rule

**Comment by goku321** [comment]
Sorry for the delay. I'm a bit caught up at the moment. Will try to get this in a couple of days. Thanks for your patience 🙇

**Comment by linsun** [comment]
Thanks @goku321! Please keep us posted. If you are not actively working on it, we would like to reassign :)
