### ISSUE TITLE
envoyOtelAls Not supported field in StreamInfo: REQ_WITHOUT_QUERY

### ISSUE THREAD

**Issue by shuxnhs** [istio/istio#53003]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

this is the config of istio

extensionProviders:
    - envoyOtelAls:
        logFormat:
          labels:
            duration: '%DURATION%'
            host: '%REQ(HOST)%'
            method: '%REQ(:METHOD)%'
            path: '%REQ(:PATH)%'
            status: '%RESPONSE_CODE%'
            upstream_host: '%UPSTREAM_HOST%'`
`

After configuration, the sidecar error message is as follows:
`
: Not supported field in StreamInfo: REQ_WITHOUT_QUERY
`

### Version

```Text
$ istioctl version
client version: 1.16.5
control plane version: 1.16
data plane version: 1.16.5 (174 proxies)
$ kubectl version
v1.26.1
```

**Comment by zirain** [comment]
I recall I fixed this in recently vesion, can you retry with latest istio?

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/51486
