### ISSUE TITLE
Sampling needs to be configurable for tracing, even if using custom sampler. Current code results in massive log spam

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio#53012]
**Describe the feature request**

We use Dynatrace at our company and are currently testing using the new OTEL configuration it provides with Istio 1.22, since OpenTracing was removed in Envoy 1.30, which is what Istio 1.22 uses. We have it all working but are seeing this message nonstop in our logs, to the point it's very difficult to see actual traffic logs without some sort of filtering done:

`2024-09-05T18:28:10.787073363Z 2024-09-05T18:28:10.786914Z	error	envoy tracing external/envoy/source/extensions/tracers/opentelemetry/http_trace_exporter.cc:86	OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message	thread=23`

It looks like Istio hardcodes a sample rate of 100 when using a custom sampler - https://github.com/istio/istio/blob/b8197f455bcf6b0ce48ef8a1f26b7a1313c429fb/pilot/pkg/networking/core/tracing.go#L119-L130. Thus, we have deduced with Dynatrace support that it's just rejecting the majority of the traces due to sampling rate limits on its side.

The comment says "_the sampling percentage is set to 100% so all spans arrive at the sampler for its decision_" but why limit it in this way? I don't want to sample EVERY call, and send EVERY call to Dynatrace just for them to throw away 95% of them; isn't that incredibly wasteful? Not to mention, the very point of this issue which is my istio-proxy logs are filled nonstop with 503's.

**I suggest making the sample rate configurable, just like it is with a non-custom sampler, so consumers can choose what works best for them.**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
@joaopgrassi

**Comment by howardjohn** [comment]
Not an expert here but I think there is some confusion. First, the logs you are seeing (`OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message`) have nothing to do with sampling. This means that we are failing to report to dynatrace. This is orthogonal from how much we sample -- it seems like your setup is completely broken and not able to export to dynatrace. 

Note a single one of those calls could be (attempting to) exporting 1000s of spans at once.

Now on the 100% tracing - it does not mean 100% of traces will be sampled. It means you are using a custom sampler which is not (just) percentage based. if we were to set this to something else (say 1%), then we would **prefilter** 1% of spans before we even let the custom sampler. Dynatraces sampler (and others) expect to see all spans (locally!) so they can decide which ones to sample using more complex algorithms.

**Comment by jbilliau-rcd** [comment]
Interesting.....ok then, let me take this back to our own monitoring SME's and Dynatrace and see what they say. Interestingly enough, we see traces in Dynatrace, so at least SOME of getting over there. But then we also see these 503's, so it almost seems like it's working sporadically, which makes no sense to me. We are using the exact setup steps in their docs. ¯\_(ツ)_/¯

Thanks @howardjohn , I hope to follow up shortly.

**Comment by joaopgrassi** [comment]
Hi all, sorry this notification seem to have slipped on the myriad of my other notifications. 

Yes, @jbilliau-rcd  what @howardjohn mentioned is correct. The percentage sampling is hardcoded to 100% **when using a customer sampler** on purpose. For a sampler to be able to accurately apply the decision, it needs to "see" all spans. If we were to set the percentage to 1%, then the sampler only has 1% of the entire population to sample. So we want everything there.


I'm an engineer working at Dynatrace, I have looked now into your support case. Can you confirm that it's a healthcheck that is being fired in the pod? Can you confirm that the spans that do get ingested Dynatrace are the health check ones? (should have attributes to help find this out). 

My assumption at the moment is that the health checks are producing the spans non-stop. I think it may be even a bug in the OTel tracer in Envoy. If there's a customer sampler configured (which is your case), it seems we don't use the sample decision from Envoy and 100% rely on the sampler.  https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/opentelemetry/tracer.cc#L219. See that `tracing_decision` is not used when a sampler is present. 

I have found this PR https://github.com/envoyproxy/envoy/pull/3578 that seem to somehow address sampling of healthchecks. If I'm right, that decision sets the `tracing_decision` to false for health check requests, but since we don't use it, they are all sampled.

But, I tried using this sample app from Istio to reproduce it https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/ but I get no spans at all. No errors, nothing. Can you maybe share the app/pod definition that you deploy in the cluster so I can verify this? One thing you can try is editing the MeshConfig and removing the Dynatrace sampler and see if the error stops.

**Comment by jbilliau-rcd** [comment]
hey @joaopgrassi , thanks for responding....this has been holding up our Istio 1.22 rollout for over a month now while we try to figure out what these 503's are. Our nonprod Dynatrace environment is already configured to ignore all health checks, as well as prometheus scraping:

![image](https://github.com/user-attachments/assets/cdf360c9-072f-4a82-b236-f79f9dc8c35f)

Now, just out of curiosity, I have removed all PodMonitors from my cluster (so prometheus isn't scraping anything anymore) AND removed my readinessProbe....so at this point, nothing is hitting my application, internally or externally. And yet....in the logs I see this:

169.254.169.254:80 172.18.76.152:46580 - - -
2024-09-20T15:25:18.210571734Z [2024-09-20T15:25:17.896Z] "- - -" 0 - "-" 170 256 22 - "-" "-" "-" "-" "169.254.169.254:80" outbound|80||not.used 172.18.76.152:46712 169.254.169.254:80 172.18.76.152:46598 - - -
2024-09-20T15:25:18.210573093Z [2024-09-20T15:25:17.915Z] "- - -" 0 - "-" 175 255 2 - "-" "-" "-" "-" "169.254.169.254:80" outbound|80||not.used 172.18.76.152:46748 169.254.169.254:80 172.18.76.152:46698 - - -
2024-09-20T15:25:18.210574418Z [2024-09-20T15:25:17.918Z] "- - -" 0 - "-" 178 251 0 - "-" "-" "-" "-" "169.254.169.254:80" outbound|80||not.used 172.18.76.152:46764 169.254.169.254:80 172.18.76.152:46750 - - -
2024-09-20T15:25:18.210575777Z [2024-09-20T15:25:17.918Z] "- - -" 0 - "-" 179 256 0 - "-" "-" "-" "-" "169.254.169.254:80" outbound|80||not.used 172.18.76.152:46772 169.254.169.254:80 172.18.76.152:46754 - - -
2024-09-20T15:25:24.214691710Z [2024-09-20T15:25:20.891Z] "- - -" 0 - "-" 1254 1637 3007 - "-" "-" "-" "-" "172.18.71.102:9999" outbound|443||jason-dev-418023852230-use2-activegate.dynatrace.svc.cluster.local 172.18.76.152:43360 10.100.132.113:443 172.18.76.152:45000 - - -
2024-09-20T15:25:28.219517601Z [2024-09-20T15:25:28.098Z] "- - -" 0 - "-" 1846 2621 12 - "-" "-" "-" "-" "172.18.8.120:443" outbound|443||kubernetes.default.svc.cluster.local 172.18.76.152:53922 10.100.0.1:443 172.18.76.152:43128 - - -
2024-09-20T15:25:30.220557382Z [2024-09-20T15:25:23.898Z] "- - -" 0 - "-" 5732 1640 6005 - "-" "-" "-" "-" "172.18.53.202:9999" outbound|443||jason-dev-418023852230-use2-activegate.dynatrace.svc.cluster.local 172.18.76.152:45546 10.100.132.113:443 172.18.76.152:35824 - - -
2024-09-20T15:25:42.224714190Z [2024-09-20T15:25:38.098Z] "- - -" 0 - "-" 884 1564 3331 - "-" "-" "-" "-" "172.18.71.102:9999" outbound|443||jason-dev-418023852230-use2-activegate.dynatrace.svc.cluster.local 172.18.76.152:54300 10.100.132.113:443 172.18.76.152:36778 - - -
2024-09-20T15:32:37.301613681Z 2024-09-20T15:32:37.301316Z	error	envoy tracing external/envoy/source
/extensions/tracers/opentelemetry/http_trace_exporter.cc:86	OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message	thread=31
2024-09-20T15:33:17.299095151Z 2024-09-20T15:33:17.298735Z	error	envoy tracing external/envoy/source/extensions/tracers/opentelemetry/http_trace_exporter.cc:86	OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message	thread=32
2024-09-20T15:36:12.304875Z	error	envoy tracing external/envoy/source/extensions/tracers/opentelemetry/http_trace_exporter.cc:86	OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message	thread=32
2024-09-20T15:38:42.242738Z	error	envoy tracing external/envoy/source/extensions/tracers/opentelemetry/http_trace_exporter.cc:86	OTLP HTTP exporter received a non-success status code: 503 while exporting the OTLP message	thread=20

So the first few lines are Istio connecting to EC2 instance metadata to get topology and region information...then we see the pod connecting to the in-cluster DT activategate....so far, all normal. Then, the 503's start, even with no traffic, no prom scraping, no probes configured at all.

Something's gotta be going on here. This is our IstioOperator config we deploy with istioctl:

```
extensionProviders:
          - name: dynatrace-otel
            opentelemetry:
              dynatrace_sampler:
                cluster_id: 1317850380
                tenant: akp68187
              http:
                headers:
                  - name: Authorization
                    value: Api-Token XXX
                path: /api/v2/otlp/v1/traces
                timeout: 10s
              port: 443
              resource_detectors:
                dynatrace: {}
              service: istio-config/akpXXXX.live.dynatrace.com
```

So not sure where to go from here. Thoughts?

**Comment by joaopgrassi** [comment]
When Envoy exports to Dynatrace `akpXXXX.live.dynatrace.com` the OTLP message is forwarded to our servers, without any configuration being applied. The configuration you have there, is only applied later on in the pipeline. So it doesn't interfere with the initial "ingest" of the OTLP message. Our public APIs still receive it and forward the message. 

But if Envoy is trying to export and getting the 503s, then unfortunately something must be triggering it to generate the spans. I'm not sure at this point how one can find out what is making it generate spans. Certainly _something_ in your cluster is causing it. And it must be a lot, for the OTLP trace requests go over your tenant's limits and the requests are being throttled. 

Maybe the Istio folks here can give more ideas how we can find out what is generating traffic on the pod? @zirain

**Comment by jbilliau-rcd** [comment]
Also, from my support case with Dynatrace:

_Our dev's have idenitified some notable behavior. As mentioned before, on the cluster/active gate side we were not seeing 503's as shown by the OTel exporter. This was the main source of confusion, but while 503's were not present, we were reporting large spikes in 429 errors. This throttling error lines up far more with the envoy side spam. The reasoning for why the 429's appear as 503s seem to be a envoy/otel quirk. Searching online for similar issues has shown some similar cases where when the export endpoint stops responding, the 503 appears rather than the expected result. Unfortunately there is not much information on why this is, but it is envoy side and not a large focus._

So it almost does seem like if envoy doesn't get a 200, it just 503's regardless of the reason why. Thus, why I created this issue on the Envoy side...that log message should be mute-able, I don't want to see it.

https://github.com/envoyproxy/envoy/issues/35997#issuecomment-2334739443

**Comment by joaopgrassi** [comment]
Also, I experienced the log span you mentioned. It seems once a request fails to export traces, it keeps retrying, because my Envoy logs were filled with these messages: (even though **I sent only a single request to Envoy**)

![image](https://github.com/user-attachments/assets/bb59c90b-dbb8-4558-b0cb-f04eb4144982)

**Comment by jbilliau-rcd** [comment]
This issue as it's stated can be closed, turns out this was a bug on the envoy side and was fixed via a PR by @joaopgrassi . Closing.

**Comment by joaopgrassi** [comment]
There's backports now in Envoy for versions 1.29|30|31. So once Istio releases new patch releases that includes those then this should be resolved for everyone.
