### ISSUE TITLE
 defaults.global.hub does not affect ztunnel

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#53018]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using an alternative image repo to install istio (especially now that Docker is locking down), all components except ztunnel seem to use defaults.global.hub.  

### Version

```Text
1.23
```

**Comment by bleggett** [comment]
`defaults` is a thing we invented that is supposed to be hidden/unused.

Just set `global.hub` - never use `default` prefixes.
