### ISSUE TITLE
Inaccessible {{ .config }} and {{ .metadata }} in the bootstrap template

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#53037]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

It doesn't seem to be possible to use those fields in the bootstrap since they passed as `any` in the template data. I'm not sure why we even have them - is it safe to delete these variables?

### Version

```Text
all
```

**Comment by howardjohn** [comment]
It seems like we access `.config` all over the place. `{{ .config.ProxyAdminPort }}`, etc

**Comment by kyessenov** [comment]
Huh, yeah. `{{ .metadata.NAME }}` doesn't seem to work (something about field in interface{}) but it could be a misleading error.

**Comment by kyessenov** [comment]
I think this is just due to an unfortunate way that metadata is merged from raw metadata.
