### ISSUE TITLE
Rate Limit: Token Bucket Algorithm

### ISSUE THREAD

**Issue by krshna-dtdl** [istio/istio#53053]
1. We need to implement Token Bucket Algo at ISTIO.
2. Lets say I got an API call and I assigned a token it, once that API is completed only at time token must be released.
3. We also want to update the number of tokens at runtime via any API.

Is this already in place?

Can someone please suggest.

**Comment by zirain** [comment]
check [istio's doc](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/) and then https://github.com/envoyproxy/ratelimit

**Comment by krshna-dtdl** [comment]
Hey @zirain I am not able to find exact solution required. Can you please help.
