### ISSUE TITLE
Istioctl debug-dump 

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5308]
When a problem occurs in istio, the operator must be able to run a debug dump tool that produces debugging artifacts.

This is similar to `kubectl cluster-info dump`

This should include the following
  * Output of `istioctl proxy-cfg` for all pods [ this could be a large number, so user could choose]
  *  All configuration artifacts
  *  K8s all pods / service / endpoint states. `kubectl get pods,service,endpoints -o yaml`
  * Logs and previous logs from istio components.

**Comment by mandarjog** [comment]
@nmittler @rshriram @costinm

**Comment by mandarjog** [comment]
`kubectl cluster-info dump` does provide a few of these resources, but it creates a single text file that cannot be easily consumed.

**Comment by mandarjog** [comment]
We have a `dumpsys` target at present that does the following
```
dumpsys:
        @mkdir -p ${OUT_DIR}/tests
        @mkdir -p ${OUT_DIR}/logs
        kubectl get all -o wide --all-namespaces
        kubectl cluster-info dump > ${OUT_DIR}/logs/cluster-info.dump.txt
        kubectl describe pods -n istio-system > ${OUT_DIR}/logs/pods-system.txt
        kubectl logs -n istio-system -listio=pilot -c discovery
        $(JUNIT_REPORT) <${OUT_DIR}/logs/test-report.raw >${OUT_DIR}/tests/junit.xml
```

**Comment by mandarjog** [comment]
https://gist.github.com/Stono/bb53f4fddc3cf4676d1d065a3d1b3a98

https://github.com/istio/istio/wiki/Collecting-Logs-and-Debug-information

**Comment by ayj** [comment]
```bash
kubectl cluster-info dump --namespace istio-system,default --output-directory=dump-dir
```
That will dump resource state (pods, services, etc) and logs for everything in the `istio-system` and `default` namespace to a directory. Artifacts are organized under their respective namespace. Logs files are per-pod. Resource JSON files are per kind.

The only thing that's missing are Istio specific configuration (CRDs) and proxy config state.

**Comment by ayj** [comment]
@Tahler @mandarjog - is this issue resolved by https://github.com/istio/istio/pull/5422?

**Comment by Tahler** [comment]
Yes. It doesn't use `istioctl proxy-cfg` but I believe it gathers the same information. Should probably get confirmation from @mandarjog though

**Comment by esnible** [comment]
Issue https://github.com/istio/istio/issues/2491 to have `istioctl version` show the server version is related.

**Comment by liamawhite** [comment]
We should unify this all in a single command in istioctl. Users shouldn't be expected to run multiple scripts and commands in order to send this to us. A single command like `istioctl mesh-info dump` should just create an archive for them to send.

We should probably break some of these things down into smaller chunks. Or start by implementing https://github.com/istio/istio/issues/6382 and iterate on top of that. Thoughts?
