### ISSUE TITLE
Istio sets the sidecar CRD for the current namespace, but services in other namespaces are still accessible.

### ISSUE THREAD

**Issue by 18515291426** [istio/istio#53083]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

"Istio sets the sidecar CRD for the current namespace, but services in other namespaces are still accessible. I hope someone can help answer this question. Thank you!

![9f8126ef333eda9c0230479f87a2459](https://github.com/user-attachments/assets/dfe47b41-22df-4031-95bb-6433536931a1)

### Version

```Text
1.13
```

**Comment by zirain** [comment]
I assume you're running in ALLOW_ANY mode, and request go with PASSTHROUHT.
Sidecar is not design for block/allow request, you should try with Authz.

BTW, 1.13 is EOL

**Comment by zirain** [comment]
duplicated with https://github.com/istio/istio/discussions/53084
