### ISSUE TITLE
Why zipkin provider collector does not support customized endpoint

### ISSUE THREAD

**Issue by Kuromesi** [istio/istio#53086]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Recently I'm trying to export tracing to a customized zipkin collector, which requires to add authentication token in the path like `/AUTH_TOKEN/api/v2/spans`, and it seems that istio does not support customized zipkin collector endpoint.

```go
func zipkinConfig(hostname, cluster string, enable128BitTraceID bool) (*anypb.Any, error) {
	zc := &tracingcfg.ZipkinConfig{
		CollectorCluster:         cluster,
		CollectorEndpoint:        "/api/v2/spans",                   // envoy deprecated v1 support
		CollectorEndpointVersion: tracingcfg.ZipkinConfig_HTTP_JSON, // use v2 JSON for now
		CollectorHostname:        hostname,                          // http host header
		TraceId_128Bit:           enable128BitTraceID,               // istio default enable 128 bit trace id
		SharedSpanContext:        wrapperspb.Bool(false),
	}
	return protoconv.MessageToAnyWithError(zc)
}
```

I'm curious about why customized zipkin collector endpoint is not supported and is there an alternative way to achieve that?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
yeah, can you use OTel-collector as intermediary agent?

**Comment by Kuromesi** [comment]
> yeah, can you use OTel-collector as intermediary agent?

Sure I can do that, currently I deployed an nginx service to proxy my requests and I'm just thinking is there any simple way to do that. 🤔

**Comment by zirain** [comment]
> It will be more convenient if I could export traces to zipkin directly, do you have any ideas why customized zipkin endpoint is not supported?

probably because most people don't need it

**Comment by Kuromesi** [comment]
> > It will be more convenient if I could export traces to zipkin directly, do you have any ideas why customized zipkin endpoint is not supported?
> 
> probably because most people don't need it

Is it possible to add a new fields for customizing zipkin endpoint? And I'm willing to implement that.

**Comment by zirain** [comment]
> > > It will be more convenient if I could export traces to zipkin directly, do you have any ideas why customized zipkin endpoint is not supported?
> > 
> > 
> > probably because most people don't need it
> 
> Is it possible to add a new fields for customizing zipkin endpoint? And I'm willing to implement that.

Reasonable requirement to me.

**Comment by Kuromesi** [comment]
> > > > It will be more convenient if I could export traces to zipkin directly, do you have any ideas why customized zipkin endpoint is not supported?
> > > 
> > > 
> > > probably because most people don't need it
> > 
> > 
> > Is it possible to add a new fields for customizing zipkin endpoint? And I'm willing to implement that.
> 
> Reasonable requirement to me.

Got it, thanks! 😊

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/53107, will land in v1.24.
