### ISSUE TITLE
Document istio xDS resource naming scheme and metadata

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#5311]
Istio translates its config into xDS resources. Istio Pilot plugins are only allowed to operate on xDS resources directly, without access to the originating istio config/service representation. For this to work, we need to formalize the naming scheme of xDS resources, so as plugins can recover the original istio resources.

**Comment by kyessenov** [comment]
cc @spikecurtis since this is probably also an issue for you.

**Comment by kyessenov** [comment]
@rshriram @louiscryan Have you thought about how we un-truncate the cluster names? The cluster names (and routes and listeners) are all up to fixed length, and we need full DNS names for mixer.

**Comment by kyessenov** [comment]
cc @douglas-reid

**Comment by kyessenov** [comment]
Ping? This is also blocking progress on https://github.com/istio/istio/issues/4854

**Comment by louiscryan** [comment]
cc @htuch

**Comment by kyessenov** [comment]
This is specific to how istio names resources (out.*, in.* and what not).

**Comment by htuch** [comment]
FWIW, Envoy has relaxed the limits on cluster name length, the bound can be configured on the CLI.

**Comment by rshriram** [comment]
It has no impact on performance. Its just a startup time overhead, but we benchmarked it earlier.. For upto 255 characters, its actually fine. btw, i dont think the current limit is 127 characters (its 181 or 187 IIRC for the last few months). We have had this for the last two releases and there has not been any reported case of everything crashing. We can document this limit in our docs.

We also have a global option for increasing the maximum length of cluster name (it needs to be wired up properly). So there is that escape route as well.

**Comment by kyessenov** [comment]
I think the limit on names is just a part of what we're interested in. We would like to know how to recover the names of k8s resources from:
1. listener names (so that we can extract metrics from envoy)
2. route names (so that we can put the right mixer attributes in the config)
3. cluster names (mostly for metrics)

@rshriram imposed a requirement that mixerfilter needs to operate directly on xDS resources. That means it is part of the plugin code contract how these names are defined and structured, for future compatibility. We need these original names in mixerfilter to associate metadata extracted from k8s adapter for richer metrics, as well as to apply the policy on k8s services rather than envoy resources.

Looking at the code, I no longer see any truncation happening. How do we recover from a too-long cluster names? That would produce a poison config.

**Comment by htuch** [comment]
I agree that metadata is probably a good place to avoid having to parse out identifiers from opaque strings. We use this internally at Google for similar kinds of purposes.

**Comment by kyessenov** [comment]
@htuch @louiscryan I would be happy if we can insert the appropriate metadata directly into the config, instead of having to decipher names from xDS.

**Comment by rshriram** [comment]
We don't truncate the cluster names. If it fails, it fails. As I said, there is a global option to increase the stat name length. there are probably more elegant ways of fixing this, but this is certainly not our priority now.

I don't think we should mix mixer filter code into the core networking code, as you seem to imply indirectly. The code was a mess in v1alpha1/v1 and its taken us a long time to migrate, and clearly separate the various stages. Mixing filter logic with the core connectivity logic is going to lead to more headaches down the line when we want to migrate to another api version.

We can always make the plugin calls for *every* route that we add, so that you get to stick whatever metadata you want per route in the per-filter config. In other words, you can always enrich the plugin interface with whatever data you need.

**Comment by rshriram** [comment]
and I will document the naming scheme in the plugin doc.

**Comment by kyessenov** [comment]
Thanks. Documentation is all we're asking. This is blocking improvements to mixerfilter config.

**Comment by kyessenov** [comment]
Issue #5331 is an instance where naming affects the functionality of filters. It's very important that we pick a naming scheme and stick with it, not change it mid-implementation.

**Comment by kyessenov** [comment]
xref PR #5423 which changes cluster naming. While this is hot, @rshriram or @costinm, do you mind creating a doc for clusters to start with?

**Comment by kyessenov** [comment]
@costinm @rshriram @douglas-reid What is your stance on annotating xDS resources with metadata (envoy opaque metadata) that we can utilize in plugins? Since the naming is in flux, that seems like a solution to unblock the progress on telemetry side? Per Harvey, that is appropriate from envoy's standpoint.

**Comment by louiscryan** [comment]
This seems like a pretty reasonable approach overall and fits with the
intended purpose. @rshriram thoughts?

**Comment by rshriram** [comment]
depends on where. @htuch was also opposed to reading filter configuration from metadata as it was abuse of the API. Thats why we added the per-filter route config stuff..

**Comment by kyessenov** [comment]
Mixerfilter will not read metadata. Pilot plugin will read metadata and
create the corresponding per_*_filter_config. We can erase metadata after
plugins processing.

**Comment by rshriram** [comment]
Ah cool.. Yeah, that works nicely. You could repurpose your PR and essentially stick per route metadata and then use it in the mixer plugin..

**Comment by htuch** [comment]
I don't think it's too heinous to use metadata to contain alternative names for a given resource. E.g. a different cluster name or identifier corresponding in the cluster metadata.

**Comment by kyessenov** [comment]
Why is this nebulous future? Are we expecting more breaking changes in this area?
