### ISSUE TITLE
NR error in gateway with NLB-IP mode in aws load balancer

### ISSUE THREAD

**Issue by parshva-shah-dsw** [istio/istio#53113]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We have configured a nlb-ip mode load balancer for istio-gateway. by following the below documentation :-
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/nlb_ip_mode/
https://www.eksworkshop.com/docs/fundamentals/exposing/loadbalancer/ip-mode/#:~:text=The%20AWS%20Load%20Balancer%20Controller%20also%20supports%20creating,through%20the%20worker%20nodes%20in%20the%20Kubernetes%20cluster.

after making this changes in the load balancer mode we are getting NR error in the gateway while executing the requests the same gateway and virtual service configuration is being used which works in instance mode load balancer.

can we have any help here with any documentation on configuration with gateway

### Version

```Text
istioctl version 1.21.0
control plane version 1.21.0
data plane version 1.21.0 (95 proxies)

kubernetes 1.29.5 EKS
```

**Comment by howardjohn** [comment]
almost always this error is from https://istio.io/latest/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni.

**Comment by parshva-shah-dsw** [comment]
@howardjohn We have a host entry and we are not using wildcard and it is able to resolve. In nlb-ip mode only it is failing. Any additional information required which I can share

**Comment by howardjohn** [comment]
I am not quite sure that what you said means its not the issue I linked. If you have `host` set, that means you MUST send SNI. Its very likely you are not

**Comment by parshva-shah-dsw** [comment]
@howardjohn here I am reffering to the same configuration is working for instance mode load balancer and not working for the ip mode load balancer.

Do we have any reference for nlb-ip mode reference for istio.
