### ISSUE TITLE
SDS in istiod: permission requirements for proxy's SA  are too high and need to be reduced

### ISSUE THREAD

**Issue by MaYuan-02** [istio/istio#53124]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
```go
func (s *CredentialsController) Authorize(serviceAccount, namespace string) error {
	user := sa.MakeUsername(namespace, serviceAccount)
	if cached, f := s.cachedAuthorization(user); f {
		return cached
	}
	err := func() error {
		resp, err := s.sar.Create(context.Background(), &authorizationv1.SubjectAccessReview{
			ObjectMeta: metav1.ObjectMeta{},
			Spec: authorizationv1.SubjectAccessReviewSpec{
				ResourceAttributes: &authorizationv1.ResourceAttributes{
					Namespace: namespace,
					Verb:      "list",
					Resource:  "secrets",
				},
				User: user,
			},
		}, metav1.CreateOptions{})
		if err != nil {
			return err
		}
		if !resp.Status.Allowed {
			return fmt.Errorf("%s/%s is not authorized to read secrets: %v", serviceAccount, namespace, resp.Status.Reason)
		}
		return nil
	}()
	s.insertCache(user, err)
	return err
}
``` 
This function is meant to handle permission checks when SDS delivers secrets. Currently, it enforces the requirement to have list permissions for all secrets in the namespace, which is too high. 

* The gateway needs permission to access all secrets in the `istio-system` namespace.
* The sidecar also requires list permission for all secrets in the current namespace when initiating mTLS to external services.

These requirements are unreasonable.
The corresponding proxy's service account only needs GET permission for the specified secrets.

**Comment by howardjohn** [comment]
Thanks for the report. This is essentially the same as https://github.com/istio/istio/issues/52728 which has some discussion, I think we can consolidate on that issue to ensure everyone is working in the same place.
