### ISSUE TITLE
AWS NLB-IP support for istio 1.21 +

### ISSUE THREAD

**Issue by altdelnow** [istio/istio#53130]
Hi... We are currently using AWS NLB which is routing packets to worker node of EKS cluster which gives socket connection error whenever we scale PODs up or down. AWS team has recommended to use NLB-IP mode so traffic can be routed directly to POD ip and we will not face this issue. We are using Istio 1.21. My query is: Is Istio 1.21 certified to run with NLB-IP mode from AWS ? If yes, is there any documentation available for such deployment.

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by altdelnow** [comment]
@howardjohn can you please confirm ?

**Comment by howardjohn** [comment]
Istio is not "certified" to run on any load balancer. Its up to the platform to reliable get connections to Istio ingress. If AWS NLB-IP can do that (which I would assume they can, as that is it's purpose), it should work with Istio. If not, its very likely an issue in AWS, not in Istio

**Comment by altdelnow** [comment]
thanks @howardjohn for your quick reply.....
