### ISSUE TITLE
istio_tcp_received_bytes_total do not increase after a period of time

### ISSUE THREAD

**Issue by ZSJGG** [istio/istio#53138]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

istio_tcp_received_bytes_total do not increase after a period of time，but istio_requests_total is still increasing, we test on bookinfo
![image-20240914143158606](https://github.com/user-attachments/assets/ffab4079-ed86-4d0b-9a20-a6ef0afb28da)

### Version

```Text
kubectl version
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8

istioctl version
client version: 1.23.0
control plane version: 1.23.0
data plane version: 1.23.0 (15 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
istio_tcp_received_bytes_total and istio_requests_total are orthogonal. Istio does not report istio_tcp_received_bytes_total for HTTP requests, so its not expected to be correlated

**Comment by ZSJGG** [comment]
> istio_tcp_received_bytes_total and istio_requests_total are orthogonal. Istio does not report istio_tcp_received_bytes_total for HTTP requests, so its not expected to be correlated

but when HTTP requests occurs, the total amount of TCP reception should increase, that means istio_requests_total should be increase.

**Comment by howardjohn** [comment]
Yeah I understand it could work that way, but in Istio the way its impemented is a request is either classified as "TCP" or "HTTP" and gets one metric or the other.

**Comment by ZSJGG** [comment]
I got it ,Thank you for your reply.
