### ISSUE TITLE
[pre-release 0.8.0 : 0.8.0-pre20180416-09-15] Error out on istioctl kube-inject -f bookinfo.yaml

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#5315]
kubectl create -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml)
error: error converting YAML to JSON: yaml: mapping values are not allowed in this context

**Comment by ymesika** [comment]
I believe it's already fixed in release and post-release.
