### ISSUE TITLE
Istio Ambient Mesh + Strict mtLS +  Apisix Gateway

### ISSUE THREAD

**Issue by goafabric** [istio/istio#53167]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

While Istio Ambient is making awesome progress,
there is some small problem with the APISIX Gateway.

- While the very similar Kong Gateway works
- And Apisix works in sidecar mode,
- With Ambient Mode Apisix Gateway fails, if beeing part of the mesh.

It will throw some funky SSL errors, which i don't expect anyone to solve here
"apisix http_ssl_client_hello_phase(): failed to match any ssl certificate by sni"

My question is more, with strict mtls mode enabled, is there a way to whitelist the apisix namespace or application ?
What i tried is below .. the allow-apisix is something i stole from another ticket that sounded similar.
But it will not work and i am not sure reading the docs if whitelisting is posible at all

https://istio.io/latest/docs/reference/config/security/peer_authentication/

Thx in adavance

--- cut ---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: example
  namespace: example
spec:
  mtls:
    mode: STRICT

----

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-apisix
#  namespace: example
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
  mtls:
    mode: PERMISSIVE

### Version

```Text
istioctl:
client version: 1.23.1
control plane version: 1.23.1
data plane version: 1.23.1 (3 proxies)

kubectl
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7
```

**Comment by howardjohn** [comment]
What exactly is the expected flow of traffic and mTLS here? its not clear

**Comment by goafabric** [comment]
it would be apisix -> example

But we've found a workaround by setting the host inside the route

host: "internalservice.svc.cluster.local"

so i will close the issue, thx for getting back
