### ISSUE TITLE
Expose SetCurrentClientCertDetails envoy object to better control XFCC header 

### ISSUE THREAD

**Issue by leosarra** [istio/istio#53170]
**Describe the feature request**

Hello everyone,
Internally, we are trying to configure clients with the X.509 authenticator type and OAuth2 client credentials to be authenticated by an external party.
Envoy proxy would need to terminates external mTLS connections and forwards the client certificate plus some extra details over the HTTP header named XFCC (x-forwarded-client-cert).

Istio supports forwarding the XFCC header through the [ForwardClientCertDetails]( https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ForwardClientCertDetails) setting. 
The problem with this setting is that when enabled, it does not forward all certificate details by default. Those details (entire client cert, entire client cert chain, DNS type SANs of client cert, URI type SANs) can be forwarded if the [HttpConnectionManager.SetCurrentClientCertDetails](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-setcurrentclientcertdetails) object is configured accordingly. 
However, we don't have right now an API to control Envoy's SetCurrentClientCertDetails object.

Do you think it makes sense to improve upon the existing `ForwardClientCertDetails` Istio API and add a `SetCurrentClientCertDetails` object to better control what is forwarded?
If we agree that this is something that makes sense to be added then I can work on the required changes.

**Describe alternatives you've considered**
So far the only way to achieve this is with an EF.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/api/pull/3323 (I think). Please re-open if not!
