### ISSUE TITLE
Patch version Istio 1.23.x not support K8s 1.31

### ISSUE THREAD

**Issue by westwind-sc** [istio/istio#53231]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

K8s 1.31.0 Released at August 13th, 2024, as the discussion in https://github.com/istio/istio/discussions/52144#discussioncomment-10343054,

> The plan is for 1.23.1 to support 1.31.

But just check Istio `1.23.1`  https://github.com/istio/istio/blob/64cfafb98498c62fa35e981b95cb5c7a36678af8/prow/integ-suite-kind.sh#L40 and `1.23.2` https://github.com/istio/istio/blob/da0b3f29e9f9eef387691bdf5870a6d665c704c9/prow/integ-suite-kind.sh#L40

They only tested with K8s `1.30.0`.

Suggest bump the test to `1.31.0` for Istio 1.23.x, so not blocking end user upgrade to K8s 1.31.

### Version

```Text
$
```

**Comment by hzxuzhonghu** [comment]
I think this is just not tested, does not mean istio cannot run within k8s 1.31
