### ISSUE TITLE
ci/circleci: e2e-pilot is flaky

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#5323]
It is blocking a lot of PR. Please either fix the flakiness or mark it as not required.

**Comment by hklai** [comment]
It's failing more often than not.
https://k8s-testgrid.appspot.com/istio-postsubmits#circleci-e2e-pilot

And it looks the same in prow.
https://prow.istio.io/?type=presubmit&job=istio-pilot-e2e

**Comment by nmittler** [comment]
@hklai @costinm @kyessenov 
Running locally on minikube, there seems to be an issue with contacting the zipkin server.  I noticed that the zipkin tests are disabled.  What is the reason for this?  Could there be a correlation?

**Comment by nmittler** [comment]
Looks like the zipkin tests were disabled in #5188.

@rshriram any thoughts? Should we re-enable the zipkin tests?

**Comment by nmittler** [comment]
Re-enablling the zipkin tests locally, it's having the same problem.

Does anyone know what's going on with zipkin?

**Comment by nmittler** [comment]
@mandarjog @douglas-reid any ideas what might be causing "connection refused" when trying to connect to zipkin?

**Comment by nmittler** [comment]
Looking at the logs on the zipkin pod, I don't see any errors or anything indicating it's received a request ... although I've never looked at zipkin logs before and am not sure what events are typically logged.

**Comment by mandarjog** [comment]
@nmittler we collect these logs for all tests in circle. Look at artifacts logs on any older zipkin build and you will see a "normal" log.

**Comment by nmittler** [comment]
Doing a little more digging...

When running on minikube, I'm seeing Prometheus restart every time a request is sent to the zipkin server:

```
level=warn ts=2018-05-24T19:07:07.26144441Z caller=main.go:374 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2018-05-24T19:07:07.269457896Z caller=main.go:398 msg="Stopping scrape discovery manager..."
level=info ts=2018-05-24T19:07:08.900432011Z caller=main.go:411 msg="Stopping notify discovery manager..."
level=info ts=2018-05-24T19:07:08.900607557Z caller=main.go:432 msg="Stopping scrape manager..."
level=info ts=2018-05-24T19:07:10.843304564Z caller=main.go:394 msg="Scrape discovery manager stopped"
level=info ts=2018-05-24T19:07:10.88485881Z caller=main.go:407 msg="Notify discovery manager stopped"
level=info ts=2018-05-24T19:07:18.197290036Z caller=main.go:426 msg="Scrape manager stopped"
level=info ts=2018-05-24T19:07:18.232419965Z caller=manager.go:460 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-05-24T19:07:18.232757788Z caller=manager.go:466 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-05-24T19:07:18.232820006Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-05-24T19:07:18.232992907Z caller=main.go:573 msg="Notifier manager stopped"
level=info ts=2018-05-24T19:07:18.234006831Z caller=main.go:584 msg="See you next time!"
``` 

No idea what could be causing this.  The request is run from app `t`, which has no sidecar ... so nothing should be going to Prometheus, AFAIK.

**Comment by nmittler** [comment]
re-assigning to @mandarjog since it seems zipkin-related.

**Comment by ostromart** [comment]
@mandarjog, will you able to drive this one? I can help/ give moral support if needed.

**Comment by douglas-reid** [comment]
I don't know why zipkin and Prometheus would be intertwined. That is very odd.

FWIW, @gargnupur has mentioned looking into building a proper, separate e2e test for tracing in general. That would replace any need for Pilot-specific trace testing, and could enable the removal of the zipkin service from environmental setup altogether for this test.

**Comment by objectiser** [comment]
At the moment the tracing tests are disabled - I've created a PR https://github.com/istio/istio/pull/5884 to re-enable them based on the jaeger backend.

**Comment by hklai** [comment]
e2e-pilot is no more, but https://k8s-testgrid.appspot.com/istio-postsubmits#pilot-e2e-envoyv2-v1alpha3, but the v1alpha3 version is pretty solidly green now.
https://k8s-testgrid.appspot.com/istio-postsubmits#circleci-e2e-pilot-auth-v1alpha3-v2

I see #5884 is closed and the test is still being skipped.
https://github.com/istio/istio/blob/master/tests/e2e/tests/pilot/a_zipkin_test.go#L35
