### ISSUE TITLE
Bring Istio Operator EOL policy to the Operator readme

### ISSUE THREAD

**Issue by shazib-summar** [istio/istio#53244]
**Describe the feature request**
Istio Operator has an EOL policy as defined by this file: https://github.com/istio/istio/blob/master/operator/version/version.go

This information should be available in the operator readme at: https://github.com/istio/istio/blob/master/operator/README.md for more visibility. This will help users choose supported versions and have to make fewer upgrade cycles for Istio Operator.

**Describe alternatives you've considered**
None

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shazib-summar** [comment]
I'd be more than happy to create a PR for this.

**Comment by keithmattix** [comment]
Thanks for raising this! Yes do please create a PR in the istio.io repo (I'll try and move this issue there)

**Comment by keithmattix** [comment]
Yes please create a PR

**Comment by zirain** [comment]
The truth is IstioOperator is EOL, I'm not sure that code is still using. cc @howardjohn

**Comment by keithmattix** [comment]
I mean at the very least, we can put the EOL date in the readme right?

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/releases/supported-releases/ is the canonical
documentation. Readme are not user facing docs and , in this case, is
extremely likely to fall out of date.

**Comment by shazib-summar** [comment]
>The truth is IstioOperator is EOL

@zirain can you elaborate on this. is this documented anywhere?


>Readme are not user facing docs and , in this case, is
extremely likely to fall out of date.

@howardjohn would https://github.com/istio/istio.io/blob/master/content/en/docs/releases/supported-releases/index.md be the appropriate place then?

**Comment by zirain** [comment]
@shazib-summar https://istio.io/latest/news/releases/1.23.x/announcing-1.23/#deprecating-the-in-cluster-operator

**Comment by howardjohn** [comment]
the data comes from https://github.com/istio/istio.io/blob/master/data/compatibility/supportStatus.yml fwiw

**Comment by shazib-summar** [comment]
Thank you for the clarification and your time. Given that Istio Operator is deprecated and the announcements are made, it doesn't seems desirable to mention EOL dates in the readme. I'll close this ticket for now.

Thanks again.
