### ISSUE TITLE
samples/bookinfo/routing/route-rule-ratings-test-abort.yaml no longer validates

### ISSUE THREAD

**Issue by esnible** [istio/istio#5328]
Our fault injection sample no longer validates:

```
$ istioctl create -f ./samples/bookinfo/routing/route-rule-ratings-test-abort.yaml
Error: configuration is invalid: HTTP route or redirect is required
```

We must either fix validation, or the rule, for 0.8 or the example will not work.

**Comment by frankbu** [comment]
Fixing the rule for 0.8 in https://github.com/istio/istio/pull/5366.
Proper solution is to fix the validation to allow this case, so let's fix the validation in 0.9.
