### ISSUE TITLE
Hardening TLS certificate key size

### ISSUE THREAD

**Issue by videlov** [istio/istio#53326]
**Describe the feature request**

For our enterprise solution at SAP using Istio we have a requirement to increase TLS certificate key size to at least 3072 bits.

We explored the possibilities of hardening our configuration of Istio installation in terms of having certificates with bigger key size (4096). We had a look at both configuring `CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE` to 4096 (following [this guide](https://istio.io/latest/docs/ops/configuration/traffic-management/manage-mesh-certificates/)), as well as providing our own Intermediate CA (folllowing [this guide](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/) and [this one](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)). They both worked.

However we verified that the TLS certificate for pod-to-pod communication pod-to-pod is still of key size 2048 bits, even for new clusters / installations. 

We could not come up with a solution to ensure that the SPIFFE mTLS identity certificate generated for the SA is of size 4096 bits. We did also address the issue [on Slack](https://istio.slack.com/archives/C38CF1PEC/p1726662063326359).

Could you please provide configuration for that or advise on how we can achieve it if it is possible?

**Describe alternatives you've considered**

There is no alternative as far as we know.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I think that env var is just for the self-signed cert for istiod itself, for the proxies you want `WORKLOAD_RSA_KEY_SIZE` which is set on the proxy container

**Comment by videlov** [comment]
is there another way to enable it for the whole service mesh other than for instance usage of `ProxyConfig`, e.g.:
```
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: kyma-proxy-config
  namespace: istio-system
spec:
  environmentVariables:
    WORKLOAD_RSA_KEY_SIZE: '4096'
```

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig lists some ways to set it

**Comment by videlov** [comment]
Yes, this works, first tried it with `ProxyConfig` CR but will be better to configure it directly to `IstioOperator`'s `proxyMetadata` in the `meshConfig` section.

Thank you very much for the help.
