### ISSUE TITLE
Traffic not shown in Kiali

### ISSUE THREAD

**Issue by CC007** [istio/istio#53346]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I tried to install the bookinfo demo. It looks like it works. I do get the virtual services to point to 1 specific version of reviews, so it looks like things  are working.

However, when I look in Kiali, I see this:
![368364448-f855f428-f456-47c5-af77-2c92fe59f4fd](https://github.com/user-attachments/assets/95042f51-5631-4e8b-883a-ffc7b9a78fdd)
Here it only shows traffic from the ingress to productpage, but all traffic between productpage, details, reviews, etc. is not visible. Also, it doesn't show the icon that the traffic is mTLS encrypted, even though I specified that it should be enabled. 

I expected something more like this (without the ratings traffic, since I specified only reviews v1 traffic): 
<img width="1128" alt="369688017-7bfef1d1-e7aa-44f9-b61e-4a165c0fe753" src="https://github.com/user-attachments/assets/0063ad99-6000-4f98-a091-d8192db5754a">

### Version

```Text
Hardware: Raspberry Pi 4B (8x)
Arch: arm64
OS version: Ubuntu 22.04.4 LTS
Rancher version: v2.9.0
K8S version: k3s v1.30.3+k3s1
Helm chart: rancher-istio (version: 104.4.0+up1.22.1)
Istio version: 1.22.1
Kiali version: v1.86.0
```

### Additional Information

[Bookinfo config](https://github.com/user-attachments/files/17035582/bookinfo.zip)

General config:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
 ```

**Comment by howardjohn** [comment]
Hey, I recommend looking into https://kiali.io/docs/faq/graph/. Note that Kiali is not a part of Istio, so you will want to engage there community (https://github.com/kiali/kiali/) if the FAQ doesn't help. The FAQ will at least give some more diagnostic information

**Comment by CC007** [comment]
Ah, my bad. It came bundled in the same helm chart, so I wrongfully assumed.

**Comment by howardjohn** [comment]
NP. That may be from `rancher-istio` usage rather than the official
