### ISSUE TITLE
Configure different tracing provider for different workloads & workloads in different clusters

### ISSUE THREAD

**Issue by Kuromesi** [istio/istio#53411]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
We are trying to export traces to different endpoint in different clusters, for example, we export traces to cloud provider for cluster A for higher stability and some advanced features, but for cluster B, we export traces to customized zipkin endpoint to reduce cost and increase confidentiality. It seems that in current version it can not be achieved since only one tracing provider can be used. 

Is it possible to add annotation like `tracing.istio.io/provider` to specify providers workloads trying to export, when this annotation is not specified, global provider will be used. Or is there any better way to achieve that? 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
In Telemetry, you can specify which workloads to attach to, and which provider to use. This should enable this use case.
