### ISSUE TITLE
Skipping DaemonSet due to policy check

### ISSUE THREAD

**Issue by GarrettPoore** [istio/istio#53440]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'm trying to deploy a DaemonSet to a cluster that already has Istio installed (using the istiod Helm chart) and working for a deployment in a different Namespace. I have a Job that applies the Namespace label, then runs a rolling restart on the Deployments/DaemonSets in the Namespace to get the istio sidecar (I can't label the Namespace beforehand due to a slew of issues).

When the Pods in the namespace are terminated/restarted they still do not have an istio sidecar, with istiod logging:
```
Skipping falcon-system/crowdstrike-falcon-sensor-***** (actual name not yet known) due to policy check
```

The current state of the namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: falcon-system
  name: falcon-system
```

I've run the `check-inject` command from [here](https://istio.io/latest/docs/ops/diagnostic-tools/check-inject/) as well, and it says the Pods should be getting the sidecar.
```
> istioctl experimental check-inject -n falcon-system daemonset/crowdstrike-falcon-sensor
WEBHOOK                 REVISION  INJECTED      REASON
istio-sidecar-injector  default   ✔             Namespace label istio-injection=enabled matches
```

Running `istioctl analyze -n falcon-system` only brings up the completed Job Pod as missing the proxy, not any of the DaemonSet Pods.

Does istio not support adding the sidecar to DaemonSets? I've search several different queries and cannot find anything saying one thing or the other. AFAIK, they are just more Pods so it shouldn't matter.

### Version

```Text
> istioctl version
client version: 1.22.3
control plane version: 1.22.3
data plane version: 1.22.3 (35 proxies)

> kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7-eks-a18cd3a
```

**Comment by howardjohn** [comment]
This is probably from HostNetwork. Its definitely not do to being a DaemonSet

**Comment by GarrettPoore** [comment]
@howardjohn Good catch, that was indeed it. Is there a way to get a better error message when it's something like this?

Also, for my use case here with CrowdStrike, only specific nodes have egress access to the Internet. In the past I set up an Envoy proxy on one of those nodes for CrowdStrike to use. My plan was to just use an egress Gateway on that node with istio, as I'm currently using that for other internet egress.

What would be the best way to use that for a Pod with HostNetworking enabled? An ingress Gateway to enter the mesh, then it will work it's way to the egress Gateway? Or can I just target the egress Gateway from outside the mesh somehow?

**Comment by howardjohn** [comment]
Istio cannot capture traffic for hostnetwork pods. So the only way to use an egress gateway would be to have the application manually change how they call things and manually program the egress gateway. Really this is like a standard ingress setp. For example I could make a DNS name `httpbin.egress.company.com` and point it to my egress gw, then have the app call that, and then forward to httpbin. Basically no Istio 'mesh', just usage as a gateway

**Comment by GarrettPoore** [comment]
OK thanks, I don't think I can change the DNS used by the app itself. It does allow for proxying, but I noticed that is different than the way istio mentions proxying in it's documentation. Istio using a `Host` header to proxy, versus the app using proxy at a lower level (equivalent to `--proxy` in `curl`).
