### ISSUE TITLE
Publish pre-releases for Helm to OCI and/or GCS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53462]
We do not publish Helm to GCS or OCI for dev builds.

We do have the repo:
```
$ helm template istiod oci://gcr.io/istio-testing/charts/istiod --devel | rg gcr.io/istio-testing/pilot
Pulled: gcr.io/istio-testing/charts/istiod:1.19.0-releasebuilder.fc5bef1
Digest: sha256:c9b56124c12b4bdb61d45e05a13093ce51f08e983109769b3ccf6cf5abac644a
          image: "gcr.io/istio-testing/pilot:1.19.0-releasebuilder.fc5bef1"
```

But its not used anymore (it was not ever used in istio/istio, actually was in istio/release-builder).

We should add these, maybe both. Only worry with GCS is that the index.yaml will be massive...

cc @dhawton @bleggett

**Comment by dhawton** [comment]
I can see index.yaml becoming massive really quickly.. not sure if we should look at lifecycle rules to trim dev builds after a certain period of time to help alleviate this? Since they're dev builds, do they need to be available indefinitely?

**Comment by bleggett** [comment]
IIRC you don't need `index.yaml` for pure OCI registries? 

So maybe for dev builds we only do OCI publish.

I think OCI generally has less robust "search for tags" capabilities but IMO that's sort of moot for dev builds - you either want to pull a specific SHA or you don't.

**Comment by dhawton** [comment]
> IIRC you don't need `index.yaml` for pure OCI registries?
> 
> So maybe for dev builds we only do OCI publish and skip GCS for now, which I think I am OK with.
> 
> I think OCI generally [has less robust "search for tags" repo indexing capabilities](https://github.com/helm/helm/issues/11000) but IMO that's sort of moot for dev builds - you either want to pull a specific SHA or you don't.

This is also an option, if we don't want to be a "helm repo".

**Comment by bleggett** [comment]
Seems like this is working as of https://prow.istio.io/view/gs/istio-prow/logs/release_istio_postsubmit/1849222683024166912

I think publishing dev builds to OCI is enough for now, and we can skip GCS. If we want to revisit doing that later we can reopen.
