### ISSUE TITLE
Istio ambient mesh does not support ipv4 directly

### ISSUE THREAD

**Issue by horba89** [istio/istio#53483]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have ipv6 only EKS cluster and istio service mesh with sidecar proxy containers. In this setup i can connect directly ipv4 endpoint e.g. curl -v -4 https://sts.eu-central-1.amazonaws.com. I have recently upgraded istio to version 1.23.2 and switched to ambient mode and the same connection is not possible from application pod anymore. However, it works from istio-cni and ztunnel pods as well as out of the mesh. Environment variable `ISTIO_ENABLE_IPV4_OUTBOUND_LISTENER_FOR_IPV6_CLUSTERS` is set to true for istiod and istio-cni.

curl command output:
```
* Host sts.eu-central-1.amazonaws.com:443 was resolved.
* IPv6: (none)
* IPv4: 54.239.54.197
*   Trying 54.239.54.197:443...
* Connected to sts.eu-central-1.amazonaws.com (54.239.54.197) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to sts.eu-central-1.amazonaws.com:443 
* closing connection #0
curl: (35) Recv failure: Connection reset by peer
```

ztunnel log:
```
warn	access	connection failed	src.addr=169.254.172.11:48584 dst.addr=54.239.54.197:443 direction="outbound" error="unknown source: 169.254.172.11"
```

### Version

```Text
istioctl version  
client version: 1.23.2
control plane version: 1.23.2
data plane version: 1.23.2 (26 proxies)

kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4-eks-a737599

helm version
version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}
```

**Comment by howardjohn** [comment]
would you be able to try out the 1.24 pre release? I believe this is fixed there https://github.com/istio/istio/wiki/Dev-Builds
