### ISSUE TITLE
pilot e2e --namespace option broken

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5348]
This used to work before switching to go test framework.

Called the tests with the argument --namespace istio and received this error:

"the namespace from the provided object "istio-system" does not match the namespace "istio". You must pass '--namespace=istio-system' to perform this operation."

**Comment by andraxylia** [comment]
thanks @ymesika

**Comment by ostromart** [comment]
Hi @ymesika, are you still planning to work on this? If not I will reassign. Thanks.

**Comment by ymesika** [comment]
It's in my queue which became a LIFO recently.
I will remove myself to let someone else to pick it but will keep it in my queue.

**Comment by andraxylia** [comment]
cc @alexburnos

**Comment by ymesika** [comment]
Not stale. Still valid.
