### ISSUE TITLE
ztunnel grafana dashboard not pushed to api.grafana.com for 1.23.2

### ISSUE THREAD

**Issue by sdake** [istio/istio#53503]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

https://grafana.com/api/dashboards/21306/revisions

You will see there is no dashboard pushed for 1.23.2. There are for the other istio-related grafana dashboards.

### Version

```Text
1.23.2
```

### Additional Information

none

**Comment by howardjohn** [comment]
Thanks!! Missed this.

https://github.com/istio/release-builder/pull/1952 will fix for future releases. Not sure how easy it is to backfill though. FWIW the revision published there is identical to the one that would have been for 1.23.2 so you can use it. Also found at https://gcsweb.istio.io/gcs/istio-release/releases/1.23.2/grafana/

**Comment by sdake** [comment]
Thanks @howardjohn, I have a workaround in place for now, no need to tag the history.

Appreciate all you do for Istio!

**Comment by howardjohn** [comment]
Great, thanks @sdake !
