### ISSUE TITLE
Ambient CNI fails to program with `invalid comment` on Mac Docker Desktop

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#53512]
`failed add IP 10.42.2.30 to ipset istio-inpod-probes-v4: invalid comment` log from the CNI. 

```
NAME                       STATUS   ROLES                  AGE    VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION    CONTAINER-RUNTIME
k3d-k3s-default-agent-0    Ready    <none>                 102m   v1.28.8+k3s1   172.20.0.4    <none>        K3s v1.28.8+k3s1   6.6.32-linuxkit   containerd://1.7.11-k3s2
```

cc @bleggett @linsun

**Comment by bleggett** [comment]
Addl context.


1. We store the pod UID in the ipset entry comment, unconditionally for all `add` flows.
2. `invalid comment` comes from the Linux kernel
3. I checked, and `netlink` is, as far as I can tell, correctly mapping the Linux kernel ipset error here: https://github.com/vishvananda/netlink/blob/main/nl/ipset_linux.go#L133 https://github.com/torvalds/linux/blob/1d227fcc72223cbdd34d0ce13541cbaab5e0d72f/include/uapi/linux/netfilter/ipset/ip_set.h#L145
4. This is a kernel error, and probably has to do with customizations to the way this kernel was built, and there's no feasible way for this to be an intermittent failure, as far as I can tell. Either your kernel has ipset comment support (and this should never fail at the kernel level), or it does not (and it should fail every time).
5. We have had problems with the `linuxkit` kernels Docker Desktop ships in the past - they fail to load eBPF progs, for instance, because they turn that (and other) functionality off to get slimmer kernel builds.

I would suspect it is not reproducible outside of Docker Desktop + that specific `linuxkit` kernel.

**Comment by howardjohn** [comment]
I got the same on Linux + k3d:

```
$ k get nodes -owide
NAME                        STATUS   ROLES                  AGE     VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE   KERNEL-VERSION   CONTAINER-RUNTIME
k3d-wasm-cluster-server-0   Ready    control-plane,master   6m40s   v1.27.8+k3s2   172.19.0.2    <none>        K3s dev    6.11.6-arch1-1   containerd://1.7.7-k3s1.27
k3d-wasm-cluster-agent-1    Ready    <none>                 6m38s   v1.27.8+k3s2   172.19.0.4    <none>        K3s dev    6.11.6-arch1-1   containerd://1.7.7-k3s1.27
k3d-wasm-cluster-agent-0    Ready    <none>                 6m38s   v1.27.8+k3s2   172.19.0.3    <none>        K3s dev    6.11.6-arch1-1   containerd://1.7.7-k3s1.27
```

Note I am using a custom k3d from https://www.spinkube.dev/docs/install/quickstart/#prerequisites (and its pretty old) but I don't think its important.

```
2024-11-11T14:43:13.511563Z     error   cni-agent       failed adding pod simple-spinapp-d6fcfc964-lnpl6 to ipset %!s(*string=0xc00034e198) with ip 10.42.1.46, error was failed to add IP 10.42.1.46 to ipset istio-inpod-probes-v4: invalid comment
2024-11-11T14:43:13.511582Z     error   cni-agent       failed to add pod to ipset: default/simple-spinapp-d6fcfc964-lnpl6 failed to add IP 10.42.1.46 to ipset istio-inpod-probes-v4: invalid comment
```

**Comment by howardjohn** [comment]
Working (kind):
```
# ipset list
Name: istio-inpod-probes-v4
Type: hash:ip
Revision: 0
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 801
References: 1
Number of entries: 5
Members:
10.244.0.12
10.244.0.7
10.244.0.9
10.244.0.8
10.244.0.11

Name: istio-inpod-probes-v6
Type: hash:ip
Revision: 0
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 224
References: 1
Number of entries: 0
Members:
root@kind-control-plane:/# ipset --version
ipset v7.19, protocol version: 7
```

Locally, I tried to make a comment. I had to make a set with comments enabled at the set level. See the 'header' on myset2:

```
$ sudo ipset list
Name: myset
Type: hash:net
Revision: 7
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x8f6f1189
Size in memory: 456
References: 0
Number of entries: 0
Members:

Name: myset2
Type: hash:net
Revision: 7
Header: family inet hashsize 1024 maxelem 65536 comment bucketsize 12 initval 0x1e78f5a1
Size in memory: 456
References: 0
Number of entries: 0
Members:

$ ipset version
ipset v7.22, protocol version: 7
$ sudo ipset add myset 14.144.0.0/12 comment "foo"
[1] kind-kind ~/go/src/istio.io/istio (master)
$ sudo ipset add myset2 14.144.0.0/12 comment "foo"
```

k3d (broken):

```
/ # ipset list
Name: istio-inpod-probes-v4
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 216
References: 1
Number of entries: 0
Members:

Name: istio-inpod-probes-v6
Type: hash:ip
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 224
References: 1
Number of entries: 0
Members:

/ # ipset add  istio-inpod-probes-v4 14.144.0.0/32 comment "foo"
ipset v7.15: Comment cannot be used: set was created without comment support
```

Now here is something weird... I spin up a new k3d cluster this time with `rancher/k3s:v1.30.4-k3s1`
```
$ docker exec k3d-mycluster-server-0 ipset add istio-inpod-probes-v4 14.144.0.0/32 comment "foo"
ipset v7.16: Argument `comment' is supported in the kernel module of the set type hash:ip starting from the revision 2 and you have installed revision 0 only. Your kernel is behind your ipset utility.
$ docker exec k3d-mycluster-server-0 ipset list
Name: istio-inpod-probes-v4
Type: hash:ip
Revision: 0
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 333
References: 1
Number of entries: 1
Members:
10.42.0.12

Name: istio-inpod-probes-v6
Type: hash:ip
Revision: 0
Header: family inet6 hashsize 1024 maxelem 65536
Size in memory: 224
References: 1
Number of entries: 0
Members:
```

But _it works fine_

**Comment by howardjohn** [comment]
Go ipset:

```
sendto(3, 
[
  {nlmsg_len=76, nlmsg_type=NFNL_SUBSYS_IPSET<<8|IPSET_CMD_CREATE, nlmsg_flags=NLM_F_REQUEST|NLM_F_ACK|0x600, nlmsg_seq=1, nlmsg_pid=0},
  {nfgen_family=AF_NETLINK, version=NFNETLINK_V0, res_id=htons(0)},
  [
    [{nla_len=5, nla_type=0x1}, "\x06"],
    [{nla_len=8, nla_type=0x2}, "\x67\x6f\x33\x00"],
    [{nla_len=12, nla_type=0x3}, "\x68\x61\x73\x68\x3a\x69\x70\x00"],
    [{nla_len=5, nla_type=0x4}, "\x00"],
    [{nla_len=5, nla_type=0x5}, "\x02"],
    [{nla_len=12, nla_type=NLA_F_NESTED|0x7}, "\x08\x00\x08\x40\x00\x00\x00\x10"]
  ]
],
gh76, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}
```

real ipset:
```
sendto(3,
[
  {nlmsg_len=80, nlmsg_type=NFNL_SUBSYS_IPSET<<8|IPSET_CMD_CREATE, nlmsg_flags=NLM_F_REQUEST|NLM_F_ACK|0x600, nlmsg_seq=1731337400, nlmsg_pid=0},
  {nfgen_family=AF_INET, version=NFNETLINK_V0, res_id=htons(0)}, 
  [
    [{nla_len=5, nla_type=0x1}, "\x07"],
    [{nla_len=9, nla_type=0x2}, "\x72\x61\x77\x33\x00"],
    [{nla_len=12, nla_type=0x3}, "\x68\x61\x73\x68\x3a\x69\x70\x00"],
    [{nla_len=5, nla_type=0x4}, "\x06"],
    [{nla_len=5, nla_type=0x5}, "\x02"],
    [{nla_len=12, nla_type=NLA_F_NESTED|0x7}, "\x08\x00\x08\x40\x00\x00\x00\x10"]
  ]
], 80, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 80
```

So diffs... (go vs normal CLI):

* `nla_len=5, nla_type=0x1` is the protocol version. Go is '6', ipset command is '7'! Note in all cases above, ipset CLI was protocol version 7
* `nfgen_family=AF_NETLINK` vs `nfgen_family=AF_INET`
* `nla_type=0x2` line is the name, so difference here is me naming the sets differently
* `nla_type=0x3` line is the type name, this is identical
* `nla_type=0x4` is the 'revision'. Go has '0', CLI has 6 

Tentative conclusion is either the revision or the protocl version impacts the `comment` stuff. Note that this may not actually be the real root cause, though!

**Comment by howardjohn** [comment]
I also looked into the error messages to see if the Go library was missing error context from the kernel. Its not; the ipset CLI just parses IPSET_ERR_COMMENT ('4112') into a nicer message than the go library

**Comment by howardjohn** [comment]
Comparing the ipset from the working vs not working, I also notice the broken one has `Revision:5` on the ipset. The working has `Revision:0`. I don't know where this comes from...

**Comment by howardjohn** [comment]
One thing I don't get... how does the container image/version impact this?? We should just be going `istio-cni Go code --> kernel` I thought

**Comment by bleggett** [comment]
> One thing I don't get... how does the container image/version impact this?? We should just be going `istio-cni Go code --> kernel` I thought

Likely different kernel version, and possibly a different set of kernel modules.

**Comment by howardjohn** [comment]
> Likely different kernel version, and possibly a different set of kernel modules.

Its all just containers on the same host though, should be the same kernel

**Comment by bleggett** [comment]
I am disinclined to think that the go library we're using is the problem, there's likely some kind of kernel version skew we need to document here, but without knowing what a particular base image's kconfig was it's hard to tell.

**Comment by bleggett** [comment]
> > Likely different kernel version, and possibly a different set of kernel modules.
> 
> Its all just containers on the same host though, should be the same kernel

Yep, my bad, misread. It would be, and there isn't a userspace `ipset` component, AFAIK.

Comments were introduced in one of the `ipset` revisions (I think 6 or something) - but if it's the same kernel and there's no userspace component, it should either work or not.

**Comment by bleggett** [comment]
It might be worth bumping the golib to protocol version 7 - that doesn't explain why a different image would produce a different result, but it might cause the kernel validation to behave differently.

**Comment by bleggett** [comment]
Also apparently `nftables` has its own ipset analog, so we should probably use that in a pure-nftables mode.

**Comment by bleggett** [comment]
> It might be worth bumping the golib to protocol version 7 - that doesn't explain why a different image would produce a different result, but it might cause the kernel validation to behave differently.

https://github.com/vishvananda/netlink/issues/942

**Comment by howardjohn** [comment]
I still don't get why on the same machine it occurs in one place but not the other. Maybe there is some other netlink activity happening that causes the versioning to get weird.. just not sure what - there are no other ipsets I can see on the bad nodes

**Comment by bleggett** [comment]
> So diffs... (go vs normal CLI):

> nla_len=5, nla_type=0x1 is the protocol version. Go is '6', ipset command is '7'! Note in all cases above, ipset CLI was protocol version 7

`vishvananda/netlink` [hardcodes `protocol` to 6](https://github.com/vishvananda/netlink/blob/976bd8de7d8167e548320e1dd74e0b0f494577dd/nl/ipset_linux.go#L11). This probably should be dynamic, as there's a netlink socket message you can use to query the kernel's supported protocol ver, and this is exposed, but only used by a CLI test tool `ipset-test` they have - I suspect the `ipset` CLI tool probably autodetects.

> nfgen_family=AF_NETLINK vs nfgen_family=AF_INET
This I'm not sure about, it should always be `AF_NETLINK` from what I can see? Also hardcoded in `vishvananda/netlink`.

> nla_type=0x4 is the 'revision'. Go has '0', CLI has 6

`vishvananda/netlink` chooses a default for this [based on the set type name, which is suspicious - that is by no means an exhaustive list they're checking.](https://github.com/vishvananda/netlink/blob/main/ipset_linux.go#L398). I cannot tell what exactly this is used for in the kernel, but we can set it to 6 easily enough.

**Comment by bleggett** [comment]
seems like `revision` is a factor, or at least I can reproduce the k3d failure and that seems to fix it.

**Comment by bleggett** [comment]
https://github.com/bleggett/istio/commits/bleggett/fix-comment-bug/

@howardjohn this seems to work for me on the old-k3d nodes as well as the kind nodes.

No, I am not really clear still on what `Revision` _does_.

**Comment by bleggett** [comment]
> I still don't get why on the same machine it occurs in one place but not the other.

Since the kernel is shared, I am wondering if there is kernel state involved here.

It is very possible that an ipset created with `go` might not be readable with one of the older container's userspace `ipset` binaries, or vice-versa.

**Comment by howardjohn** [comment]
This is assumed to be fixed by https://github.com/istio/istio/pull/53862. If anyone sees this when running a build with this PR please let us know!
