### ISSUE TITLE
[0.7.1] [Helm] Pulls nightly images

### ISSUE THREAD

**Issue by BastienM** [istio/istio#5354]
Hi,

I am trying to deploy Istio `v0.7.1` (using `release-0.7` branch) via Helm and while checking why the Pilot pod won't start I noticed that all the pulled image by Helm are `istionigthly/*:circleci-nightly`.

```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
istionightly/mixer                     circleci-nightly    9f123f3f06af        6 days ago          58.3MB
istionightly/proxy                     circleci-nightly    4d26babbb54a        6 days ago          802MB
istionightly/pilot                     circleci-nightly    7b8cf3bff7bf        6 days ago          54.8MB
```

The same problem happened in issue #4701.

Is it by design ?

**Edit:**

Updating `install/kubernetes/helm/istio.values.yaml` with the following :
```
 # Common settings.
 global:
   # Default tag for Istio images.
-  hub: docker.io/istionightly
+  hub: docker.io/istio

   # Default tag for Istio images.
   # Should track latest released version.
   # Currently using nightly build, for testing
-  tag: circleci-nightly
+  tag: 0.7.1
   proxy:
     image: proxy
```

makes everything working fine.

**Comment by linsun** [comment]
sorry we aren't putting fix in 0.7.x, could you try 0.8's nightly build pls?

**Comment by linsun** [comment]
This is a known issue in 0.7.1 (as documented in the release note).  Please wait till 0.8 is out to try this if you prefer to wait for a stable build.

**Comment by BastienM** [comment]
My bad @linsun, I quickly read the changelogs and overlook the depreciation of `0.7`.
We can close the issue.
