### ISSUE TITLE
Promote istio-cni to stable

### ISSUE THREAD

**Issue by jaellio** [istio/istio#53554]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

The Istio CNI Plugin is currently listed as "Beta". To promote Ambient to "Stable", the Istio CNI Plugin should also be stable since it is required for Ambient mode. Istio CNI and Ambient should be announced as stable/GA together.

Opening this issue to determine the requirements for promoting istio-cni to stable.

Requirements:

Nice to have:
- [ ] Improved test coverage https://github.com/istio/istio/issues/50991 

**Affected product area (please put an X in all that apply)**

[X] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
As i commented on the proposal, this istio-cni ambient functionality is coupled with ztunnel.  It seems to announce this part as GA without Ambient

**Comment by therealmitchconnors** [comment]
Ambient is graduating to GA in this release.  It would not make sense for CNI to stay in Beta.

**Comment by hzxuzhonghu** [comment]
That make sense to be together

**Comment by bleggett** [comment]
FWIW I don't see https://github.com/istio/istio/issues/50991

as a prerequisite, as no other Istio component has that yet anyway.
