### ISSUE TITLE
when multiple virtualservices are defined, istio route order should create route in the order in which they are deployed

### ISSUE THREAD

**Issue by sambitr** [istio/istio#53550]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

we deploy 2 virtualservices from 2 Helm chart deployments for their own microservice, which uses host as * and shared istio-ingressgateway

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-ingress-api
  namespace: demo
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /demo/api/
    route:
    - destination:
        host: api
        port:
          number: 80
    timeout: 30s
  - match:
    - uri:
        prefix: /demo/swagger
    route:
    - destination:
        host: api
        port:
          number: 80
    timeout: 30s
---
$ k get virtualservices -n demo demo-ingress-web -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: demo-ingress-web
  namespace: demo
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /demo/
	rewrite:
	  uri: /
    route:
    - destination:
        host: web
        port:
          number: 80
    timeout: 30s
```

they are deployed in the order in which they are defined above.

The way istio orders the route is:

```
$ istioctl proxy-config routes istio-ingressgateway-5688c54c67-g8dkx -n istio-system
NAME                                                  VHOST NAME     DOMAINS     MATCH                  VIRTUAL SERVICE
https.443.https.istio-ingressgateway.istio-system     *:443          *           /demo*                 demo-ingress-web.demo
https.443.https.istio-ingressgateway.istio-system     *:443          *           /demo/api/*            demo-ingress-api.demo
https.443.https.istio-ingressgateway.istio-system     *:443          *           /demo/swagger*         demo-ingress-api.demo
```

So what is happening is that, all the traffic that should go to api virtual service, when called: <host-name>/demo/api is going to web virtual service.

I feel the routing order is responsible for that.

Interestingly, if I keep the web virtualservice like:

```
$ k get virtualservices -n demo demo-ingress-web -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: demo-ingress-web
  namespace: demo
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web
        port:
          number: 80
    timeout: 30s
```

routing turns out as below and it solves the problem:

```
NAME                                                  VHOST NAME     DOMAINS     MATCH                  VIRTUAL SERVICE
https.443.https.istio-ingressgateway.istio-system     *:443          *           /demo/api/*            demo-ingress-api.demo
https.443.https.istio-ingressgateway.istio-system     *:443          *           /demo/swagger*         demo-ingress-api.demo
https.443.https.istio-ingressgateway.istio-system     *:443          *           /*                     demo-ingress-web.demo
```

**What should be better, if we can control the routing order incase we deploy it from multiple deployments.**

****FYI:** I know if we keep it in a single virtualservice, that works. But keeping it in multiple virtual services help our application team understand it better, so that they can modify when they require it.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
From the generated route. it seems `demo-ingress-api` is created or updated later than `demo-ingress-web`.

**Comment by sambitr** [comment]
this was addressed in https://github.com/istio/istio/issues/53564
