### ISSUE TITLE
Dynamically deliver the istio-ca-root-cert based on the criteria

### ISSUE THREAD

**Issue by zhangdalei3745** [istio/istio#53601]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**
Our services is sensitive to configmaps in their namespace, so i want those namespaces which do not use istio will not be deliver istio-ca-root-cert.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
`discoverySelectors` will help.

**Comment by zhangdalei3745** [comment]
discoverySelectors  do not  stop delivering  istio-ca action to namespaces which do not match label selector .

**Comment by zirain** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
discoverySelector only takes effect on root ca distribution when `ENABLE_ENHANCED_RESOURCE_SCOPING` = true

**Comment by zirain** [comment]
> discoverySelector only takes effect on root ca distribution when `ENABLE_ENHANCED_RESOURCE_SCOPING` = true

why we need two gates(1. user set `discoverySelector` 2. add another env flag)  for one feature?

**Comment by hzxuzhonghu** [comment]
At first, discoverySelector is only used to filter services/endpoint. Later, there is a requirement to filter VS/DR, including istio-ca-cert based on it too.

Now ENABLE_ENHANCED_RESOURCE_SCOPING  defaulted to true, in the future we can remove this env

**Comment by zhangdalei3745** [comment]
ok, i got it

**Comment by zhangdalei3745** [comment]
ok, i got it
