### ISSUE TITLE
GRPC telemetry config path

### ISSUE THREAD

**Issue by erikwoo** [istio/istio#53617]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

Considering upload tracing data to quickwit，which exposes a GRPC api with path = /api/v1/otlp/v1/traces

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by rsalmond** [comment]
The quickwit docs state that they [support the open telemetry tracing standard](https://quickwit.io/docs/distributed-tracing/overview) and [so does istio](https://quickwit.io/docs/distributed-tracing/overview). It probably already works.

**Comment by erikwoo** [comment]
Configuring Istio to export tracing directly to QuickWit does not function correctly. However, exporting tracing through OpenTelemetry Collector to QuickWit works seamlessly. To achieve this, configure TLS with insecure=true following the guidelines at [Using OTEL Collector](https://quickwit.io/docs/distributed-tracing/send-traces/using-otel-collector).

If either Istio or QuickWit were to adopt TLS configurations, this would eliminate the need for an intermediary collector proxy.

**Comment by erikwoo** [comment]
After investigating, I found that because Im using sidecar mode, and mesh global options set to outboundTrafficPolicy = registry_only.

Without configuring the quickwit/opentelemetry egress to the sidecar. But with EnvoyFilter adds quickwit/opentelemetry to SIDECAR_OUTBOUND CLUSTER, the enovy was successfully export tracing using the HTTP method. However, failed via gRPC.

My solution was adding quickwit/opentelemetry  egress to all sidecar, finally envoy success to export tracing via gRPC
