### ISSUE TITLE
Upgrade from 1.22 to 1.23 throwing `exec format error` when using helm upgrade on AKS

### ISSUE THREAD

**Issue by aturcott** [istio/istio#53697]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When trying to upgrade from 1.22 to 1.23, we are getting an `exec format error` on some of our AKS clusters. We are trying to run 4 istiod pods, some come up healthy and others fail with the above error. We are running this from a github action. Confirmed that the images and nodes are running the same architecture. The upgrade times out at this step in our github workflow `helm upgrade -i istiod-${DASHED_NEW_ISTIO_VERSION}` after upgrading istio base because the pods fail to come up healthy.

![image](https://github.com/user-attachments/assets/b644eefe-ff70-48ce-b147-937b2a248e39)

![image](https://github.com/user-attachments/assets/d958c749-f607-4c25-bbc5-a2fdca44cd10)

<img width="496" alt="image" src="https://github.com/user-attachments/assets/f11c78a2-1eb0-4506-84c0-4487201f5b1b">

### Version

```Text
istioctl-1.23.2-linux-amd64.tar.gz used by our runners as a binary
```

**Comment by howardjohn** [comment]
What is the image with the sha256? The only times i have seen this, a user incorrectly pushed only the amd64 image to their own registry, making it no longer a multi-arch image.

**Comment by aturcott** [comment]
> What is the image with the sha256? The only times i have seen this, a user incorrectly pushed only the amd64 image to their own registry, making it no longer a multi-arch image.

Here's the manifest for the istio/pilot:1.23.2 image in our container registry. We did a `docker pull istio/pilot:1.23.2` and then `docker tag istio/pilot:1.23.2 <container registry>/istio/pilot:1.23.2` and then `docker push <container registry>/istio/pilot:1.23.2`. Those were the original commands that were failing with the same error so we tried again but using `docker pull --platform linux/amd64 istio/pilot:1.23.2` to make sure the arch was compatible.

{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 4037,
    "digest": "sha256:a342234ebb356711afdfba00daa6e4178e194049dd5c92d8c4d74a26ec1ec2e6"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 30567306,
      "digest": "sha256:eb993dcd6942ffcb7633f2cb271bd4b0a275fc9bdc8f5100c5b4d24694cacf50"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 23713757,
      "digest": "sha256:5dc5876572ae6ff8a1c35532f8ac40be475ab0cb183a59a22a266f8f0a480418"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 4483,
      "digest": "sha256:68b3f62a8929f5520bbc6376ce777bfb01a9ac8617fb9216cdfae228d3cd6600"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 24896416,
      "digest": "sha256:c0543a4b59a07709a9672587689ac16c25ed28b2d1512db8f63c83764c2ea944"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 3910,
      "digest": "sha256:9fa4f9ea149ec376410b8d283308350539da673a1c40e204c8052199de8c0e13"
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 1669,
      "digest": "sha256:95298a1c1064f195d7b815f71fd0e80c1d8e5ef88482f9ec4689cd019f94ba9e"
    }
  ]
}

**Comment by howardjohn** [comment]
Yeah that doesn't work. Docker will pull the platform of where you ran it on. I use [crane cp](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md) to do this, probably there are other ways as well

**Comment by zirain** [comment]
FYI: `crane index filter "${imageName}" --platform linux/amd64 --platform linux/arm64 -t "${MIRROR_REGISTRY}/${imageName}"` if there're too much platforms.

**Comment by aturcott** [comment]
It seems that when we pushed the original image after using `docker pull istio/pilot:1.23.2` which had the incorrect arm architecture, the images were cached on our nodes. After pulling the correct image with `docker pull --platform linux/amd64 istio/pilot:1.23.2` and pushing that to our container registry, we updated the pull policy from `IfNotPresent` to `Always` which fixed the issue.
