### ISSUE TITLE
Istio-agent ignores url params during scraping

### ISSUE THREAD

**Issue by StupidScience** [istio/istio#53707]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

During scraping istio-agent ignores url parameters set (at least for scraping from envoy).
In particular we wanna scrape only `usedonly` metrics from envoy but agent instead returning all of them ([code link](https://github.com/istio/istio/blob/f37a8d2481bdfa5fb4ffde695246cf122d5bba42/pilot/cmd/pilot-agent/status/server.go#L544))

As an example for our env:
we are getting ~12k metrics from envoy without usedonly
```
curl -i "localhost:15020/stats/prometheus?usedonly=true" | grep envoy_ | wc -l
   11864
```
and just about 500 when `usedonly` parameter is respected:
```
curl -i "localhost:15090/stats/prometheus?usedonly=true" | grep "envoy_" | wc -l 
     449
```

Can we make istio-agent respect this parameter?

### Version

```Text
Irrelevant
```

### Additional Information

I consider this rather as a bug, but it might be considered as feature request as well.

**Comment by StupidScience** [comment]
It is envoy’s feature, not Prometheus’
Link https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--stats?usedonly

**Comment by zirain** [comment]
we need code change here: https://github.com/istio/istio/blob/0e30509be5a69a82d74907dab1da0d11da2b7cd8/pilot/cmd/pilot-agent/status/server.go#L544

**Comment by StupidScience** [comment]
@zirain my bad, looking into code it should work as I would expect and add query params. apparently we use version that does not support that yet

**Comment by StupidScience** [comment]
Fixed in https://github.com/istio/istio/pull/52574. Just there is no stable release with this fix yet.
Closing
