### ISSUE TITLE
AccessLog command `%FILTER_STATE('upstream_peer')%` not working

### ISSUE THREAD

**Issue by zirain** [istio/istio#53769]
as https://github.com/istio/proxy/pull/5825 mentionded, should be able use `%FILTER_STATE('upstream_peer')%` instead of `%FILTER_STATE('wasm.upstream_peer')%`, it didn't worked as expected.

cc @kyessenov

**Comment by kyessenov** [comment]
The correct way is to use `%UPSTREAM_FILTER_STATE('upstream_peer')%` for TCP filter state. The note referred to the downstream filter state, not upstream.
