### ISSUE TITLE
jaeger doesn't work in the demo profile

### ISSUE THREAD

**Issue by craigbox** [istio/istio#53779]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

#49615 removed the default `zipkin` backend for tracing, which was (counter-intuitively) required to make Jaeger work.

The instructions for installing Jaeger don't adequately reflect this, and as a result when you follow [option 1](https://istio.io/latest/docs/ops/integrations/jaeger/#installation) in the Jaeger docs, you don't have working tracing.

[The upgrade notes](https://istio.io/latest/news/releases/1.22.x/announcing-1.22/upgrade-notes/#default-tracing-to-zipkinistio-systemsvc-removed) tell you to use the Telemetry API instead, but they then give a Zipkin example.

Now that Jaeger uses OpenTelemetry as its default protocol, we should update the docs to tell someone how to configure sending traces in OTLP format.

The demo profile has an `otel-tracing` provider set up to the OpenTelemetry collector, which logs to stdout.  I think it would be much more useful if it had a tracing provider set up which delivers traces to `tracing.default.svc.cluster.local:4318` (or whatever equivalent works with the `jaeger.yaml` add-on we ship.

### Version

```Text
1.22+
```

**Comment by naslth** [comment]
me too

**Comment by naslth** [comment]
how to use with telemetry api?

**Comment by craigbox** [comment]
I fixed the Istio docs on that:
https://istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/
(This bug is about fixing the installation default.)
