### ISSUE TITLE
Is there a way to disable specific Istio sidecar metrics

### ISSUE THREAD

**Issue by benyahman** [istio/istio#53797]
**Describe the feature request**
How can I disable the following Istio sidecar metrics? 
- istio_request_duration_milliseconds_bucket
- istio_response_bytes_bucket
- istio_request_bytes_bucket

These types of metrics generate too much data , which cause overhead on Prometheus.

**Describe alternatives you've considered**
Are there any examples that demo how to disable specific metrics through Telemetry  or other methods?

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
https://istio.io/latest/docs/tasks/observability/metrics/telemetry-api/#disable-metrics
