### ISSUE TITLE
move to use docker.io instead of grc.io

### ISSUE THREAD

**Issue by linsun** [istio/istio#538]
This was discussed briefly on one of the channels.  @sebastienvas, could you move back to docker hub?   I don't know the exact commit(s) but we discovered it here:   https://github.com/istio/istio/pull/524   See discussion below:

why did we change docker hub to gcr.io/istio-io instead of dockerhub?

6 replies
Douglas Reid 
[5 hours ago] 
I moved to gcr when I was desperate to restore e2e green, mainly because I could build and push images easier. Docker hub now that everything is back to green seems like the thing to do.

Lin Sun 
[2 hours ago] 
@dougreid  I understand why you moved… I would love to see the green light too.  Given docker hub is also back to green, would you kindly move back to use dockerhub instead?  This is a community core project, it should be best practice not to use any vendor specific image repo or integration.

Douglas Reid 
[2 hours ago] 
I vote yes for moving back to docker hub.  @sebastienvas made the last change to the images used, however.  can you coordinate with him to find the appropriate images ?

Douglas Reid 
[2 hours ago] 
@sebastienvas  ^^

Laurent Demailly
[1 hour ago] 
you might want to open an issue or shoot an email, most people aren't on slack all the time

Lin Sun [2 minutes ago] 
ok will do thank you for chiming in quickly @ldemailly @dougreid!

**Comment by sebastienvas** [comment]
For the release I am planning on staying on gcr.io for simple ACLs reason. Everybody has access to docker.io and can overwrite tags. Release artifacts should be immutable. Google Cloud Registry provides fine grain ACLs and docker hub does not.

**Comment by sebastienvas** [comment]
Also I want to separate docker images created by CI for testing, from official docker images for best practice. The gcr.io/istio-testing is used for CI, gcr.io/istio-io is used for official packages. While we can also push official docker images to docker.io, I don t think it makes sense to push CI testing images.

**Comment by linsun** [comment]
@sebastienvas I think I agree with you on CI testing.  For release artifacts, why can't we have in docker hub and restrict write access to that to only a few folks?  I don't understand why we need to go with gcr.io.  I think having it in docker hub makes it easier for people to search and consume istio images.  (I have to confess I 'm a few days old on this project, pls let me know if I'm missing something obvious here. :)  )

**Comment by rshriram** [comment]
I am against hosting our release images in gcr as its not easily consumable. dockerhub is searchable and has lot more visibility. Test images - sure. Even for those, it would be nice to parameterize the registry so that people can use their cloud providers registries instead of relying on GCR.

**Comment by andrewhowdencom** [comment]
Suggest `quay.io` as a reasonable alternative; which does implement the ACLs, and is a reasonably common place for containers to be found.

**Comment by sebastienvas** [comment]
@linsun Nobody but CI and release (and infra admins) will have write access to gcr.io docker hubs. You should all have a personal docker hub to push your own images like you need your own cluster to run your test. From a release point of view we need to be able to differentiate images that we can trust (CI or official) from the one that we cannot (personal), I see people in istio pushing their own image, I think this is bad practice, you should use the one generated by the CI. If you commit something, the CI will build it, if it does not lets fix the CI. 

@rshriram Do you agree to give write access to CI only (and couple of admins) and not anyone else ? If not I cannot trust this hub.

**Comment by ldemailly** [comment]
I agree we should use docker hub for official builds (and yes nobody should manually push stuff there so it means clear protocol and/or limited access) and it should be easy to switch/configure so the base isn't hard coded everywhere or the same variable overrides it consistently

**Comment by rshriram** [comment]
I agree. Lets limit access.

**Comment by linsun** [comment]
@sebastienvas I'm not saying differently than you :)  I think limited access make sense for official images and users should not push their own image in there.

**Comment by sebastienvas** [comment]
The nice thing about gcr is the update restriction which I think would prevent people from overriding a tag.

Anyway, I am running through the release with @rvkubiak Monday, so we ll discuss on how to update this since we might move to some other tool than Jenkins.
For reference, this is where it is hard coded
https://github.com/istio/pilot/blob/master/Jenkinsfile#L133, there is another file for Mixer and Auth.

**Comment by linsun** [comment]
Ok thanks @sebastienvas!  How did your discussion go?

Regardless how nice GCR is about update restriction, the fact that it is not searchable from docker hub and I can't even search it even as a GCR user made this not a good choice for me or any other users.

**Comment by linsun** [comment]
BTW, I'd be more than happy to submit a PR and understand the process to test this to help out.

**Comment by sebastienvas** [comment]
I was thinking of using gc.io as a docker hub mirror like so:
https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring

That way official docker images are on docker.io and we can prevent people from updating tags. What do you guys think ?

**Comment by linsun** [comment]
@sebastienvas thanks, i think that can work.  Just to ensure we are on the same page, does that mean official images are still pushed to docker.io for former builds, and the build server or anyone can optionally configure the docker deamon with the gcr as the mirror?

**Comment by sebastienvas** [comment]
I read too fast the documentation this only apply to user's local docker hub, which does not help. I'll be creating PRs to update our script to upload to docker.io.

**Comment by linsun** [comment]
@sebastienvas, do you mean user's local docker engine/deamon when you say user's local docker hub?   Regardless, thank you for investigating on this!

**Comment by sebastienvas** [comment]
Yes. you have a local docker image cache associated with you docker instance. I thought you could setup the docker io hub to do the same thing, but did not find any way to do it. Anyways I sent the PRs to update to docker.io
