### ISSUE TITLE
Helm purge doesn't cleanup all kubernetes resources

### ISSUE THREAD

**Issue by morvencao** [istio/istio#5380]
**env:**
```
centos: 7.3
istio version: 0.7.1
kubenetes version: v1.9.1
```

**action:**
```
# helm install --name istio --namespace istio-system ./istio
...
# helm list --tls
NAME 	REVISION	UPDATED                 	STATUS  	CHART          	NAMESPACE
istio	1       	Thu May  3 04:13:23 2018	DEPLOYED	istio-0.7.1	istio-system
# helm delete istio --purge
release "istio" deleted
# kubectl get all,cm,secrets,sa,clusterrolebinding,clusterrole,crd -n istio-system | grep istio
istio-ca-secret                          istio.io/ca-root                      2         14m
istio.default                            istio.io/key-and-cert                 3         14m
istio.istio-ingress-service-account      istio.io/key-and-cert                 3         13m
istio.istio-mixer-service-account        istio.io/key-and-cert                 3         14m
istio.istio-pilot-service-account        istio.io/key-and-cert                 3         13m
istio.istio-prometheus-service-account   istio.io/key-and-cert                 3         14m
istio.istio-security-service-account     istio.io/key-and-cert                 3         12m

enduserauthenticationpolicyspecbindings.config.istio.io   15m
enduserauthenticationpolicyspecs.config.istio.io          15m
gateways.networking.istio.io                              15m
httpapispecbindings.config.istio.io                       15m
httpapispecs.config.istio.io                              15m
policies.authentication.istio.io                          15m
quotaspecbindings.config.istio.io                         15m
quotaspecs.config.istio.io                                15m
```

**problem:**
There are still some kubernetes resources after `Helm delete --purge`, including secrets for serviceaccount, some CRDs.

**expected**
There should be no kubernetes resources after `Helm delete --purge`:
```
# kubectl get all,cm,secrets,sa,clusterrolebinding,clusterrole,crd -n istio-system | grep istio
# 
```

/cc @gyliu513

**Comment by ymesika** [comment]
I can confirm that same issue still exists on v0.8.0 from `release-0.8`.
You can assign to me if no one is already covering it in another issue.
CC @linsun

**Comment by gyliu513** [comment]
@ymesika what is your solution to fix this? Thanks.

**Comment by ymesika** [comment]
@gyliu513 this needs further investigation but it seems like stuff which isn't created by the Chart remains as well as the namespace itself.
I'm not sure if Helm is able to remove a namespace.

**Comment by ymesika** [comment]
According to the [Helm documentation](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases) resources that were created by a hook aren't being deleted with the release.

I suggest creating a Helm `post-delete` hook that will remove those _secret_ and/or _crd_ leftovers.

**Comment by ymesika** [comment]
For the leftover CRDs I have PR #5750 that adds them to the Pilot's template making them managed by Helm like the rest of the CRDs.

As for secrets, still needs to be investigated. The proposed `post-delete` hook is one option.

**Comment by ymesika** [comment]
Fixed by the various PRs.
