### ISSUE TITLE
Documentation for CRD Upgrades

### ISSUE THREAD

**Issue by alpkahvecioglu** [istio/istio#53815]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

In the documentation,

https://istio.io/latest/docs/setup/upgrade/helm/#in-place-upgrade

there is the following `kubectl apply -f manifests/charts/base/crds` command to apply the new CRDs before going through the upgrade procedure. However when I look at the base chart there isn't a folder called crds.

In the [README](https://github.com/istio/istio/blob/master/manifests/charts/README.md) for the charts folder, there is the following command `kubectl apply -f base/files` however this also doesn't look right to me.

What should be the correct command to upgrade the CRDs? I assume it is `kubectl apply -f base/files/crd-all.gen.yaml` but I wanted to make sure.

### Version

```Text
❯ istioctl version
client version: 1.23.1
❯ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.0
❯ helm version --short
v3.16.1+g5a5449d
```

**Comment by zirain** [comment]
yes, other yaml files were introduced recently.

**Comment by bleggett** [comment]
This is documented in the 1.24 upgrade notes, which is the release where the change was introduced.

https://preliminary.istio.io/latest/news/releases/1.24.x/announcing-1.24/upgrade-notes/

Additionally, `istio.io` doc changes have already been merged in https://github.com/istio/istio.io/pull/15744 and should be updated when the 1.24 docs bump happens (if it has not already).
