### ISSUE TITLE
Unknown platform gcp when upgrading istio-base Helm chart from 1.22.2 to 1.24.0

### ISSUE THREAD

**Issue by rachelstowell** [istio/istio#53860]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Steps to Replicate:
1. Have an existing deployment of istio-base with the following values:

```
global:
  platform: "gcp"
```

2. Add the "managed by helm" labels to CRDs as documented here: https://istio.io/latest/news/releases/1.24.x/announcing-1.24/upgrade-notes/#istio-crds-are-templated-by-default-and-can-be-installed-and-upgraded-via-helm-install-istio-base
3. Upgrade the istio-base helm chart via Terraform from 1.22.2 to 1.24.0

Expected Behavior:
Update applies and CRDs are upgraded

Actual Behavior:
Error: execution error at (base/templates/zzz_profile.yaml:45:3): unknown platform gcp

### Version

```Text
$ istioctl version
client version: 1.24.0
control plane version: 1.24.0
data plane version: 1.22.2 (1 proxies), 1.24.0 (1 proxies)

$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5-gke.1014003

$ helm version --short
v3.14.4+g81c902a

helm version in tf lock file: 2.16.1
```

**Comment by howardjohn** [comment]
There are only 5 platforms configured this way: https://github.com/istio/istio/tree/master/manifests/helm-profiles. I'm not exactly sure why we didn't have one for gcp, given it doesn't require some customizations, but for gcp no config is needed (while there is customizations needed, they are auto detected anyways)

**Comment by schildwaechter** [comment]
The base-charts default `values.yaml` lists "gcp" as one of two values for this parameter.
https://github.com/istio/istio/blob/0d9721d804a72a7a0d1c64a2c0df5eca6bb2b03e/manifests/charts/base/values.yaml#L14

So if this value is not needed for GCP, the values.yaml should probably be changed?

**Comment by howardjohn** [comment]
Thanks! that is confusing. fixed in https://github.com/istio/istio/pull/53929
