### ISSUE TITLE
memory of the sidecar is growing slowly

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio#53864]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a set of applications whose memory is growing slowly in a "staircase" pattern. The TPS (transactions per second) is not high, but the data volume is relatively large. Currently, I don’t have any ideas on why the memory is increasing.
![img_v3_02g5_12b6620f-8553-41d9-9cfd-f569badcdf6g](https://github.com/user-attachments/assets/e4c1a790-96e4-4811-a42a-3eff412a7d08)

![img_v3_02g5_414e9ad0-5870-4429-a6d4-17e2b2e74d7g](https://github.com/user-attachments/assets/cee6fb4e-9c09-41ac-ad9b-8477cbd396fd)

![img_v3_02g5_88a1e513-c0da-42be-a820-8ea86662ed0g](https://github.com/user-attachments/assets/97a90448-1691-44b3-aa35-76487f6f47f4)

### Version

```Text
istioctl version
client version: 1.20.2
control plane version: 1.20.2
data plane version: 1.20.2 (80 proxies)
```

**Comment by zirain** [comment]
1.20 is EOL, please upgrade to a supported release.
BTW, please check the count of metrics first.
