### ISSUE TITLE
'Collecting Metrics and Logs' task documentation fix

### ISSUE THREAD

**Issue by stepanv** [istio/istio#540]
The [Collecting Metrics and Logs](https://istio.io/docs/tasks/metrics-logs.html) task suggests to create a `new_rule.yaml` file with `metrics` aspect `label` for `source` as follows:
```
        labels:
          source: source.service | "unknown"
```
however, since the Grafana query filters by _label_ and not by the FQDN: `response_size_bucket{source=~"unknown|productpage|reviews" ...`, the `source` label should be:
```
        labels:
          source: source.labels["app"] | "unknown"
```

There is a commit possibly fixing this: https://github.com/istio/istio/pull/367 but the documentation didn't change. 

Is this intended? Is there some other file that needs to be changed (not sure from where the doc is generated)?

**Comment by ldemailly** [comment]
Issue moved to [istio/istio.github.io #433](https://github.com/istio/istio.github.io/issues/433) via [**ZenHub**](https://www.zenhub.com/)
