### ISSUE TITLE
[Ambient] AuthorizationPolicy targetRef support

### ISSUE THREAD

**Issue by ilrudie** [istio/istio#54027]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When using ambient mode binding policy to waypoint should use `targetRefs` (plural) however there is an undocumented `targetRef` (singular) field. When used some functionality does not work correctly

- status writing is broken
- policy acceptance/use needs to be investigated still

**changing to the plural `targetRefs` field which accepts a list is a viable workaround**

### Version

```Text
control plane and data plane @ 1.24.0 impacted
```

### Additional Information

https://istio.slack.com/archives/C041EQL1XMY/p1731933435853339 is the troubleshooting thread which initially highlighted this.

**Comment by ilrudie** [comment]
There was a difference in how status logic and apply logic were accessing targetRefs which caused status not to work with the singular version of the field

**Comment by zirain** [comment]
cc @keithmattix , I recall `targetRef` was introduced first, and marked as hided soon, correct me if I'm wrong.

**Comment by ilrudie** [comment]
I think that's correct. I just accessed that field incorrectly when I wrote it the first time around. I have a [fix](https://github.com/istio/istio/pull/54028) merged and [cherry-picked](https://github.com/istio/istio/pull/54038). Should be fixed in 1.24.2 when that releases.
