### ISSUE TITLE
Prow dashboard e2e tests are failing in release-0.8 branch

### ISSUE THREAD

**Issue by hklai** [istio/istio#5404]
Example:
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1600/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/1533/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-cluster_wide-auth/1560/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/1599/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/1534/
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-cluster_wide-auth/1559/

Failed tests:
Given they failed in all the three test suites twice in a row, they are probably not the flakiness we saw before. 

Please help resolve them ASAP as they are blocking daily releases for the 0.8 branch.

**Comment by douglas-reid** [comment]
I'm OOO for the next week really. It seems fairly clear from these failures that something has broken TCP `Report()`ing. 

Given that this is not flaky, per your description, I suspect either:
- something has changed with respect to test setup
- a recent PR has legit broken the metrics for TCP

TCP traffic generation runs after HTTP traffic generation. In the logs, it appears to succeed:

```
I0504 00:12:41.553] 2018-05-04T00:12:41.552241Z	info	Running command kubectl -n dashboard-test-6a80d54267b64daf87492f exec netcat-client-8495cf8d84-smc5l -c netcat -- sh -c "echo 'test' | nc -vv -w5 -vv netcat-srv 44444"
I0504 00:12:46.875] 2018-05-04T00:12:46.875586Z	info	Command output: 
I0504 00:12:46.876] Connection to netcat-srv 44444 port [tcp/*] succeeded!
```

But we have no evidence of this success recorded in Mixer (metrics or logs).

@mandarjog can you help debug this issue? I suspect either (a) the proxies for the TCP service aren't ready when traffic is sent (slow loading) or (b) something has changed RE: proxy configuration for the netcat client/server. Of course, I'm a bit out-of-the-loop with respect to the v2 push.

**Comment by hklai** [comment]
This is still blocking release as the test failures prevent automatic release from happening. 

Please disable the tests if those failures are not important for 0.8.0 until they are fixed.

**Comment by bianpengyuan** [comment]
This is due to a change to proxy_init container arguments, which uses container ports instead of '*' wildcard for inbound traffic redirect ports, and the container port of the test app is wrong in dashboard e2e test.

**Comment by hklai** [comment]
Thanks for the update. Can it be fixed soon? =)

**Comment by bianpengyuan** [comment]
Fix was merged. I will close this once I verify the test passes in post submit.

**Comment by bianpengyuan** [comment]
Seems it succeed in the most recent post submit run . Close this.
