### ISSUE TITLE
Pod label update lead to twice push

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#54058]
We found that If we update a pod label, our sidecar received two pushes. 

This is caused by ProxyUpdate() being called twice.

**Comment by tangmengqiu** [comment]
which versions will be impacted?

**Comment by ramaraochavali** [comment]
But I see only it is called once in labelFilter - Are thinking labelFilter is invoked twice?

**Comment by hzxuzhonghu** [comment]
Ohh, could happen rarely when we update the label before pod turns ready

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/54102 to eliminate it
