### ISSUE TITLE
Support Graceful Termination of Long-Lived Connections Without Restarting Main Container in Istio

### ISSUE THREAD

**Issue by gongbosheng** [istio/istio#54060]
**Describe the feature request**

Provide a mechanism to gracefully close all long-lived connections, such as WebSocket, without restarting the main container.

Currently, there is no straightforward way to achieve this. The available options affect the main container’s operation or health probes:
	1.	Using curl http://localhost:15000/drain_listeners does not fully terminate all long-lived connections.
	2.	Using curl http://localhost:15000/quitquitquit affects the main container’s health probes, causing the main container to restart.

A solution is needed to address this without requiring modifications to the livenessProbe configuration.

**Describe alternatives you’ve considered**
	•	Modifying the livenessProbe configuration using the annotation sidecar.istio.io/rewriteAppHTTPProbers: "false". However, this results in 503 errors in probes and the main container fails to start correctly.

Affected product area (please put an X in all that apply)

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

The requirement is to gracefully terminate long-lived connections (e.g., WebSocket) without restarting the main container or disrupting the health probes. The current workaround approaches either do not work or cause unintended consequences like container restarts or probe errors. This feature would improve application availability and reduce disruptions during operations that require long-lived connections to be closed.

**Comment by ramaraochavali** [comment]
Do you want them to be closed on demand or close them periodically? Can you please explain more about the use case?

**Comment by gongbosheng** [comment]
> Do you want them to be closed on demand or close them periodically? Can you please explain more about the use case?

We occasionally experience memory overflow issues in production services. When this issue occurs, we want to preserve the current pod’s state for debugging and investigation. To achieve this, we need to perform the following two steps:
	1.	Remove the pod from the load balancer: This has already been achieved by modifying the pod’s labels.
	2.	Terminate existing long-lived connections: Currently, we are considering two approaches:
	•	Restarting the Envoy sidecar container.
	•	Using Envoy management APIs to forcibly close long-lived connections.

The goal is to accomplish the second step without restarting the main container or disrupting its probes. This is essential to maintain the pod’s state while addressing the problematic connections.

We are currently using Istio version 1.14.

**Comment by ramaraochavali** [comment]
For 2. Did you try drain_listeners?graceful&skip_exit? It should close all connections

BTW. 1.14 is very old so difficult to identify if there any issues

**Comment by gongbosheng** [comment]
> For 2. Did you try drain_listeners?graceful&skip_exit? It should close all connections
> 
> BTW. 1.14 is very old so difficult to identify if there any issues

Thank you for the suggestion! I tried using drain_listeners?graceful&skip_exit, and it worked successfully. The connections are indeed closed, but it seems there is a graceful timeout period before they are fully terminated, so the effect is not immediate. This behavior is sufficient for our current needs, and we appreciate your guidance. 😊
