### ISSUE TITLE
Document that the proxy uses UUID 1337 and customers can change it if needed to avoid conflicting with their own processes.

### ISSUE THREAD

**Issue by Stono** [istio/istio#5408]
Hey Istio folks, 
It's your favourite annoying bug finder :-)

  - kube: 1.9.6-gke.1
  - istio: 0.7.1

We changed the UUID of our base image today to be `1337` (because you know, our pods are "leet") and in doing so, we lost all outbound communication from our pods:

```
❯ k exec -it at-consumer-platform-5556c66d6f-7llgk /bin/bash
Defaulting container name to master.
Use 'kubectl describe pod/at-consumer-platform-5556c66d6f-7llgk -n default' to see all of the containers in this pod.
[java@at-consumer-platform-5556c66d6f-7llgk app]$ cat /etc/passwd | grep java
java:x:1337:1337::/home/java:/bin/bash
[java@at-consumer-platform-5556c66d6f-7llgk app]$ curl http://at-search-one-service
curl: (56) Recv failure: Connection reset by peer
```

After pulling my hair out for two hours (at kubecon...)  i discovered that changing the UUID to something other than `1337` (i went to `1338`) resolved the problem:

```
❯ k exec -it at-consumer-platform-6957f5d6d9-7z624 /bin/bash
Defaulting container name to master.
Use 'kubectl describe pod/at-consumer-platform-6957f5d6d9-7z624 -n default' to see all of the containers in this pod.
[java@at-consumer-platform-6957f5d6d9-7z624 app]$ cat /etc/passwd | grep java
java:x:1338:1338::/home/java:/bin/bash
[java@at-consumer-platform-6957f5d6d9-7z624 app]$ curl http://at-search-one-service
{
  "timestamp" : 1525437672838,
  "status" : 401,
  "error" : "Unauthorized",
  "message" : "Full authentication is required to access this resource",
  "path" : "/"
}
```

I can only assume this is something to do with the fact that istio-proxy is also very "leet"?

```
❯ k exec -it at-consumer-platform-6957f5d6d9-7z624 -c istio-proxy /bin/sh
$ whoami
whoami: cannot find name for user ID 1337
```

But have no idea why this would matter.

**Comment by Stono** [comment]
Hey,
I'd certainly recommend making it very clear to the users that they can't use the same uuid as proxy.  Unless I'm being blind I don't see that anywhere in the docs?

Even better would be a more graceful failure than generic TCP errors.

**Comment by nmittler** [comment]
@Stono @vadimeisenbergibm what are the next steps here?

**Comment by Stono** [comment]
@nmittler nothing really from my perspective, I'd just make sure you document it a bit clearer perhaps?

**Comment by vadimeisenbergibm** [comment]
1337 is hardcoded in Istio, in particular in the Docker file https://github.com/istio/istio/blob/e42981c270214b8cddea52c2dce7569567121a99/pilot/docker/Dockerfile.proxyv2#L27, so it cannot be parametrized (the proxy image is built with the UID 1337).

**Comment by vadimeisenbergibm** [comment]
Fixed in https://github.com/istio/istio.io/pull/2940. @Stono Could you please close this issue?
