### ISSUE TITLE
The metrics of istio gateway  get old destination_canonical_revision  

### ISSUE THREAD

**Issue by zzmg** [istio/istio#54128]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

After the service is released, the version will change, but the metrics of the old version will still exist, but not all the metrics of the old version will exist. However I found this  metrics  from istio gateway，istio_requests_total： may have old version labels，like this label destination_canonical_revision，and the metrics values ​​for this old version will not grow. like dirty data。The size of metrics will increase，many days later， it may cause the program that collects metrics to crash，like OOM

### Version

```Text
% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.30.6-eks-7f9249a
WARNING: version difference between client (1.27) and server (1.30) exceeds the supported minor version skew of +/-1

% bin/istioctl version
client version: 1.21.6
control plane version: 1.21.6
```

### Additional Information

none

**Comment by howardjohn** [comment]
We are still looking into making this on-by-default so there is no user action needed, but this can be remdiated by METRIC_ROTATION_INTERVAL. https://github.com/istio/istio/issues/53836 https://github.com/istio/istio/issues/50419 can help

**Comment by zzmg** [comment]
thanks

**Comment by zzmg** [comment]
add env for istiod
          env:
            - name: METRIC_ROTATION_INTERVAL
              value: "150s"
            - name: METRIC_GRACEFUL_DELETION_INTERVAL
              value: "120s"
promble sloved

**Comment by zzmg** [comment]
one question, after i add env, istiod rollout restart ,during this period，there is a network interruption of about 10 seconds on the data plane.
i want to know why @zirain

**Comment by zirain** [comment]
I cannot recall it will affect that.

**Comment by zzmg** [comment]
from the log of istio proxy ,i can not found something suspicious

**Comment by patsevanton** [comment]
Hello! when set by default ?
