### ISSUE TITLE
sidecar-injector: injector should be part of released yamls 

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#5413]
While verifying docs for 0.8, I noted that we [require helm to create the sidecar-injector](https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#installing-the-webhook). This spits out a istio.yaml with the injector AND all of istio. If I start for the beginning of the quickstart instructions, I probably already have istio installed through the released istio.yaml or another helm fashion.

We should have a helm command to only generate the sidecar-injector or we should ship it under the addons directory so that a user can simply create this new component.

**Comment by cmluciano** [comment]
cc @hklai @ayj WDYT?

**Comment by ayj** [comment]
cc @yusuoh 

The setup instructions should probably be updated to refer to helm. Most of the manual cert provisioning steps have now been automated (via Citadel).

**Comment by cmluciano** [comment]
Possibly related https://github.com/istio/istio/issues/5332#issuecomment-385819571

**Comment by ostromart** [comment]
It seems reasonable to me to regenerate all of istio.yaml unless this is a common scenario, but I can see the annoyance there. In any case, this should be assigned to whoever inherited helm from yusuo.
