### ISSUE TITLE
helm-chart: istio-base: 1.24.x: usage of `enableCRDTemplates`

### ISSUE THREAD

**Issue by sedflix** [istio/istio#54172]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Besides setting the default for `enableCRDTemplates` to `true`, it seems like we have modified the template to **always** include CRDs due to the `else` block at https://github.com/istio/istio/blob/master/manifests/charts/base/templates/crds.yaml#L19-L21.

Due to this, it's impossible to manage CRDs separately from the base as it was before. The upgrade note says that: 

> If you previously installed or upgraded CRDs with kubectl apply and not Helm, you can continue to do so.

But it's not possible. Setting `enableCRDTemplates=false` will render the CRDs. 

### Version

```Text
$ istioctl version
client version: 1.22.2
control plane version: 1.24.1
data plane version: 1.24.1 (8 proxies)

$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.5-gke.1014003

$ helm version --short
v3.16.2+g13654a5
```

### Additional Information

1. Is it recommended that istio-base not be used when installing CRDs separately? 
2. Or is the recommendation to always use istio-base to install CRDs?

**Comment by howardjohn** [comment]
> Or is the recommendation to always use istio-base to install CRDs?

I think this and the note is wrong.

@bleggett can you confirm?

@sedflix is that a concern for you? Like is it just a doc issue or also problematic behavior?

**Comment by bleggett** [comment]
> Due to this, it's impossible to manage CRDs separately from the base as it was before.

Define what you mean by `manage` here.

1. `kubectl apply -f https://github.com/istio/istio/blob/master/manifests/charts/base/files/crd-all.gen.yaml` should work, regardless of whether you use `base` or not.

2. `helm template base | kubectl apply -f` should also work.

3. `helm install base -> helm upgrade base` should also work.

**Comment by sedflix** [comment]
I will explain our current setup a bit more. We use `flux` for installation/management. We install/manage the following in order with dependency on the previous step:
1. Install CRDs (We are not using `kubectl apply -f` but using `kustomize`)
2. Install istio-base (without CRDs)
3. Install istio-discovery 


The following statement _may_ not be correct for 1.24.x. 
(It kind of works when using `kubectl` but it won't when using any gitops tools,)

> kubectl apply -f https://github.com/istio/istio/blob/master/manifests/charts/base/files/crd-all.gen.yaml should work, regardless of whether you use base or not.

We will always get an error like below when using istio-base 1.24.x 

```
reconciliation failed: Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "wasmplugins.extensions.istio.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "http://app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istio-base"; annotation validation error: missing key "http://meta.helm.sh/release-namespace": must be set to "istio-system"
```
 
 With the release of 1.24.x, actively managing CRDs separately when using the istio-base helm chart is impossible.
 **And this is because istio-base 1.24.x always installs CRDs**.

---

> The recommendation is to manage them yourself outside the chart OR manage them with the chart

If we are managing the CRDs ourselves outside the chart, should we use istio-base helm-chart or not?


---

I have the following choices right now:
1. Remove our `Install CRDs` step.
OR
2. Remote our `Install istio-base` step
OR
3. Maybe the mandatory installation of CRDs with istio-base was unintentional. 

If the recommendation is to "always use istio-base to install CRDs" we will go ahead with 1.
---

**Comment by sedflix** [comment]
> is that a concern for you? Like is it just a doc issue or also problematic behavior? 

I think it's mostly a doc+recommendation issue. 
It's a very minor refactor anyway.

**Comment by howardjohn** [comment]
>  If the recommendation is to "always use istio-base to install CRDs" we will go ahead with 1.

Yep.

You should follow https://istio.io/latest/news/releases/1.24.x/announcing-1.24/upgrade-notes/#istio-crds-are-templated-by-default-and-can-be-installed-and-upgraded-via-helm-install-istio-base to 'take over' the CRDs (1 time action) and then stop `kubectl apply`ing them basically.

I agree some docs improvements seem needed here though

**Comment by sedflix** [comment]
Thank you! 
I think even the "Install with Helm" docs are fine. Is it possible to update the upgrade note 😅 ?

**Comment by bleggett** [comment]
> I will explain our current setup a bit more. We use `flux` for installation/management. We install/manage the following in order with dependency on the previous step:
> 
>     1. Install CRDs (We are not using `kubectl apply -f` but using `kustomize`)
> 
>     2. Install istio-base (without CRDs)
> 
>     3. Install istio-discovery
> 
> 
> The following statement _may_ not be correct for 1.24.x. (It kind of works when using `kubectl` but it won't when using any gitops tools)
> 
> > kubectl apply -f https://github.com/istio/istio/blob/master/manifests/charts/base/files/crd-all.gen.yaml should work, regardless of whether you use base or not.
> 
> We will always get an error like below when using istio-base 1.24.x if we have install CRDs separately in a different manner.
> 
> ```
> reconciliation failed: Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "wasmplugins.extensions.istio.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "http://app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istio-base"; annotation validation error: missing key "http://meta.helm.sh/release-namespace": must be set to "istio-system"
> ```

Yep - fundamentally you can't manage the same resource with 2 different things at the same time.

- If you are using Helm at all, already, you must use `helm install base/helm template base`
- If you were not using Helm at all, you can continue to `kubectl apply -f` the `crd.yaml`

But you can't do both at the same time (and no longer need to) - I'll update the upgrade note to be clearer about this, sorry about that!

**Comment by bleggett** [comment]
> Thank you! I think even the "Install with Helm" docs are fine. Is it possible to update the upgrade note 😅 ?

https://github.com/istio/istio.io/pull/16065

Let me know if this is (more clear) or (less clear) - feel free to leave a Github review with concrete suggestions if you think it's still confusing.

**Comment by sedflix** [comment]
Thank you!
