### ISSUE TITLE
JSON access log has trailing ; on UPSTREAM_CLUSTER

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#54219]
It was not updated to use UPSTREAM_CLUSTER_RAW like the non-json format. Probably unintentional?

cc @keithmattix

**Comment by keithmattix** [comment]
Yeah I just missed this. If someone can get to it before me, knock yourself out, otherwise I'll push a PR when I'm back next week

**Comment by ramaraochavali** [comment]
https://github.com/istio/istio/pull/54224
