### ISSUE TITLE
Mixer Unit Tests are consistently failing in release-0.8

### ISSUE THREAD

**Issue by hklai** [istio/istio#5424]
Log:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/575/daily-unit-tests/42/
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/575/daily-unit-tests/41/

Failing tests include:
TestNetworkFailure
TestQuotaCache
TestReportBatch
TestTCPMixerFilter
TestTCPMixerFilterPeriodicalReport
TestTCPMixerFilterV1Config

**Comment by bianpengyuan** [comment]
Seems like istio/istio#5267 is the cause. Mixer client e2e test failed in the postsubmit of this PR and thereafter. I will try to revert the PR and see if it fixes the problem.

**Comment by hklai** [comment]
Fixed by #5424
