### ISSUE TITLE
istio-proxy fails to start when datadog tracing enabled on IPv6 clusters

### ISSUE THREAD

**Issue by andrewjamesbrown** [istio/istio#54267]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Istio sidecars fail to start on EKS IPv6 clusters with the following error:
```
2024-12-10T22:43:09.040160Z info Apply proxy config from env {"tracing":{"datadog":{"address":"2600:1f18:c69:5902::cb3f:8126"},"customTags":{"env":{"literal":{"value":"production"}}},"sampling":100},"proxyMetadata":{"DD_REMOTE_CONFIGURATION_ENABLED":"false"},"image":{"imageType":"distroless"}}
2024-12-10T22:43:09.042016Z info cpu limit detected as 2, setting concurrency
2024-12-10T22:43:09.042100Z error failed to get proxy config: 1 error occurred:
* invalid datadog config: unable to split "2600:1f18:c69:5902::cb3f:8126": address 2600:1f18:c69:5902::cb3f:8126: too many colons in address
Error: failed to get proxy config: 1 error occurred:
* invalid datadog config: unable to split "2600:1f18:c69:5902::cb3f:8126": address 2600:1f18:c69:5902::cb3f:8126: too many colons in address

```

It appears that `meshConfig.defaultConfig.tracing.datadog.address` is configured with a default of `$(HOST_IP):8126` which fails validation due to https://github.com/istio/istio/blob/74ad0965f6e27e48bdbfd5c647d7caee587f6c3c/pilot/pkg/util/network/ip_test.go#L123-L129.

This might be resolved if this value is set to `[$(HOST_IP)]:8126` on IPv6 clusters; the default is [$(HOST_IP):8126](https://github.com/istio/istio/blob/1.22.6/manifests/charts/istio-control/istio-discovery/templates/configmap.yaml#L51)

### Version

```Text
% istioctl version
client version: 1.24.0
control plane version: 1.22.6
data plane version: 1.21.6 (4 proxies), 1.22.6 (249 proxies)
% kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.29.10-eks-7f9249a
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
```

**Comment by howardjohn** [comment]
Hmm, not sure a good solution. The `[]` wrapping is breaking IPv4.

Overall I would generally prefer to not use HOST_IP and instead use https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/#using-service-internal-traffic-policy but that is imposing things on users -- we probably still want to support this case.

perhaps here https://github.com/istio/istio/blob/1bf8cf9c85669cb4a0cc3b6709f897abbd060b58/pkg/envoy/proxy.go#L170 we conditionally wrap it in `[]` if it is IPv6. That would break users that have already done this workaround, however...

**Comment by andrewjamesbrown** [comment]
@howardjohn I've filed https://github.com/istio/istio/pull/54269 as an attempt to resolve this.
