### ISSUE TITLE
Gateway Controller Default Tag Failure

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#54280]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When two revisions of Istio are installed and a default tag points to one revision, the two istiods battle each other for control of gateways with no istio.io/rev label.  

### Version

```Text
istioctl version
client version: 1.24.1
control plane version: 1.24.1
data plane version: 1.24.1 (5 proxies)

~# k version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.29.9
```

### Additional Information

repro steps:

```
istioctl install  --set profile=ambient --set revision=foo
istioctl install  --set profile=ambient --set revision=bar
kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.2.0" | kubectl apply -f -; }
istioctl tag set default --revision=foo
k apply -f https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/bookinfo/gateway-api/bookinfo-gateway.yaml
```

result: the gateway pods churn, constantly starting and terminating as the two istiods battle over the pod revision annotation.

**Comment by therealmitchconnors** [comment]
The Gateway Deployment Controller uses the TagWatcher to track which tags it should be managing.  Somehow, the TagWatcher for the non-default revision is reporting, in addition to it's own tag, a zero-length tag, which matches gateways that lack the istio.io/rev label.  I'm still investigating where the tag watcher is getting this zero length tag from...

**Comment by therealmitchconnors** [comment]
The root cause appears to be #51576, which migrated tok8s indexers in lieu of client-side indexes.  While this optimizes index performance, it also means that indexes no longer respect client-side filters.  This may also impact discoverySelector implementations in other controllers which use an index.

**Comment by greg-swift-yohana** [comment]
I didn't find this issue when looking for my problem but it is the same thing so i thought i'd add a little more context for others:

In logs I was seeing Pilot logging constantly about reconciling the Gateway

```
2024-12-13T06:22:56.593050Z info gateway reconciling gateway=istio-system/bookinfo
2024-12-13T06:22:56.592971Z info gateway gateway updated gateway=istio-system/bookinfo
2024-12-13T06:22:56.530300Z info gateway reconciling gateway=istio-system/bookinfo
2024-12-13T06:22:56.530259Z info gateway gateway updated gateway=istio-system/bookinfo
2024-12-13T06:22:56.471239Z info gateway reconciling gateway=istio-system/bookinfo
2024-12-13T06:22:56.471193Z info gateway gateway updated gateway=istio-system/bookinfo
2024-12-13T06:22:56.426124Z info gateway reconciling gateway=istio-system/bookinfo
2024-12-13T06:22:56.426074Z info gateway gateway updated gateway=istio-system/bookinfo
```

The gateway controller created  bookinfo-istio deployment has multiple replicasets that are constantly scaling up and down.

```
OldReplicaSets:  bookinfo-istio-6f7bbcf78d (1/1 replicas created)
NewReplicaSet:   bookinfo-istio-5f5d6b4996 (0/0 replicas created)
Events:
  Type    Reason             Age              From                   Message
  ----    ------             ----             ----                   -------
  Normal  ScalingReplicaSet  9s               deployment-controller  Scaled up replica set bookinfo-istio-5f5d6b4996 to 1
  Normal  ScalingReplicaSet  9s               deployment-controller  Scaled up replica set bookinfo-istio-6f7bbcf78d to 1
  Normal  ScalingReplicaSet  1s (x7 over 6s)  deployment-controller  Scaled down replica set bookinfo-istio-5f5d6b4996 to 0 from 1
  Normal  ScalingReplicaSet  1s (x6 over 5s)  deployment-controller  Scaled up replica set bookinfo-istio-5f5d6b4996 to 1 from 0
```

I had both 1.23.3 and 1.24.1 installed, and from this issue and what I was told on slack they were fighting over the deployment.

Workarounds until you are on the patched versions:

1. Only have 1 revision of istio installed
2. Explicitly label the Gateway with `istio.io/rev=<revid>`, which you should probably remove after you've upgraded to a fixed version.

Hopefully this helps someone else find this issue :D
