### ISSUE TITLE
Unexpected: updating a service cause two handler called

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#54356]
```
2024-12-17T02:55:16.245199Z	debug	kube	Handle event update for service sleep in namespace default
2024-12-17T02:55:16.253057Z	debug	kube	Handle EDS endpoint sleep update in namespace default
2024-12-17T02:55:16.254769Z	debug	kube	Handle event update for service sleep in namespace default
2024-12-17T02:55:16.354541Z	info	ads	Push debounce stable[302] 4 for config Address//default/sleep.default.svc.cluster.local and 3 more configs: 100.769485ms since last change, 109.223611ms since last push, full=true
```
Super easy to reproduce by `kubectl edit svc`

**Comment by hzxuzhonghu** [comment]
I am sure this is not a normal behavior, it is `debug` so no one find it before, it may exist long

**Comment by hzxuzhonghu** [comment]
This is because the service.status is updated each time. So user update once, the status writer update once, so the controller ger two notifications. That's not expected, we should not change the lastTransition time unless the condition really change.
This cause redudant api server/istiod burden. @howardjohn @ilrudie

**Comment by howardjohn** [comment]
What is the status update from? You have a waypoint and a status like 
```
status:
  conditions:
  - lastTransitionTime: "2024-12-17T14:30:35Z"
    message: Successfully attached to waypoint default/waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```

Right?

One concern I have is the `observedGeneration` - I think this should be set and updated when it changes.. but it looks like in my cluster Service has no metadata.generation?? Maybe its only for CRDs.

**Comment by howardjohn** [comment]
Nice find!

**Comment by hzxuzhonghu** [comment]
Yes. i configurred a waypoint for the whole namespace

**Comment by howardjohn** [comment]
So right now we are doing server side apply. We don't actually know if its changed until we apply. At this point its too late to change/not change the timestamp.

So we would need to switch this approach entirely, not just a small tweak

**Comment by hzxuzhonghu** [comment]
Kubernetes pod status update is using strategy patch, i think this kind of patch can be used for service status patch. 

But for se it seems not applicable.

**Comment by hzxuzhonghu** [comment]
my fault: SE support strategy patch as well 

```
	// Current service state of ServiceEntry.
	// More info: https://istio.io/docs/reference/config/config-status/
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []*v1alpha1.IstioCondition 
```

**Comment by howardjohn** [comment]
I think those are actually ignored for CRDs and have no meaning. not certain though

**Comment by hzxuzhonghu** [comment]
I am not sure either
