### ISSUE TITLE
`ambient.enabled=true|false` should be a Helm global

### ISSUE THREAD

**Issue by bleggett** [istio/istio#54401]
**Describe the feature request**
I think it makes sense to have `ambient.enabled` be a global/cross chart value.

Reasoning:

- As mentioned [in our guidance](https://github.com/istio/istio/blob/master/manifests/charts/UPDATING-CHARTS.md), it is a simple boolean flag "used across 2 or more charts"

- It is a simple boolean value that should be set consistently across all installed charts, unconditionally.

- It makes `profiles` usable with wrapper charts, e.g. you can now do this:
> `helm install istio-wrapper --set global.profile=ambient`

instead of this:

>`helm install istio-wrapper --set global.profile=ambient --set <subchart1>.ambient.enabled=true --set <subchart2>.ambient.enabled=true --set <subchart3>.ambient.enabled=true...`

- It allows people to construct `values.yaml` files like this

```
global.ambient.enabled=true

cni:
  <scoped values>
istiod:
  <scoped values>
ztunnel:
  <scoped values>
base:
  <scoped values>
...
```

versus this:

```
cni:
  <scoped values>
  ambient.enabled=true

istiod:
  <scoped values>
  ambient.enabled=true

ztunnel:
  <scoped values>
  ambient.enabled=true

base:
  <scoped values>
  ambient.enabled=true
...
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Ambient
[ ] Docs
[ ] Dual Stack
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I'm confused how this relates to profile. you said this enabled you to use global.profile=ambient.. but ambient.enabled != profile=ambient?

**Comment by bleggett** [comment]
> but ambient.enabled != profile=ambient?

Correct. I'm saying that if `global.ambient=true` is a thing, we can put `global.ambient=true` in the `ambient` profile.

So that `--profile=ambient` actually _can_ mean both, and people don't have to specify both.

**Comment by howardjohn** [comment]
Can you not just do `--set global.profile=ambient` today?

**Comment by howardjohn** [comment]
Could also do something like 

```
diff --git a/manifests/charts/istio-cni/templates/zzz_profile.yaml b/manifests/charts/istio-cni/templates/zzz_profile.yaml
index 35623047cd..0633347e9f 100644
--- a/manifests/charts/istio-cni/templates/zzz_profile.yaml
+++ b/manifests/charts/istio-cni/templates/zzz_profile.yaml
@@ -24,7 +24,7 @@ Finally, we can set all of that under .Values so the chart behaves without aware
 {{- $defaults := $.Values._internal_defaults_do_not_set }}
 {{- $_ := unset $.Values "_internal_defaults_do_not_set" }}
 {{- $profile := dict }}
-{{- with .Values.profile }}
+{{- with (coalesce .Values.profile .Values.global.profile) }}
 {{- with $.Files.Get (printf "files/profile-%s.yaml" .)}}
 {{- $profile = (. | fromYaml) }}
 {{- else }}
```

Regardless of the mechanism, it seems the issue is you cannot do `global.profile=...`. I am not sure why the solution is anything other than making that work

**Comment by bleggett** [comment]
> Regardless of the mechanism, it seems the issue is you cannot do `global.profile=...`. I am not sure why the solution is anything other than making that work

AH - I had fixed that in https://github.com/istio/istio/pull/54264 but didn't resync https://github.com/istio/istio/pull/54265 against it.

It does actually work as-is with that, my bad. Closing this.
