### ISSUE TITLE
reduce gateway config size

### ISSUE THREAD

**Issue by deepakdeore2004** [istio/istio#54443]
(This is used to request new product features, please visit <https://github.com/istio/istio/discussions> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Dual Stack
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

[sidecar object isnt applicable to gateway](https://istio.io/latest/docs/reference/config/networking/sidecar/), `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` doesn't affect config if set at gateway level alone, this is mesh wide variable.
Can there be a setting to apply sidecar similar setting at individual gateway level instead of whole mesh?

**Comment by ramaraochavali** [comment]
Can you explain more about use case? Why do you need optimized config only for certain gateways?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/29131 and https://github.com/istio/istio/issues/45979 are the only credible solutions. Unless there are concrete ideas here on how we can reduce the config size beyond those 2 ideas, I think we can close this and track there.

**Comment by deepakdeore2004** [comment]
> Can you explain more about use case? Why do you need optimized config only for certain gateways?

i want to apply this config only on few gateways on a shared cluster

**Comment by howardjohn** [comment]
Which config...?

**Comment by deepakdeore2004** [comment]
> Which config...?

the envoy config_dump

**Comment by howardjohn** [comment]
> #29131 and #45979 are the only credible solutions. Unless there are concrete ideas here on how we can reduce the config size beyond those 2 ideas, I think we can close this and track there.

Based on this I don't think there are any new ideas on how to achieve this other than these 2, so lets track there. Thanks.
