### ISSUE TITLE
Istio ambient multi-cluster issue

### ISSUE THREAD

**Issue by ro-distefano** [istio/istio#54470]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [ ] This is not a question about how to use Istio

### Bug Description

Hello Istio Team,

I am encountering some difficulties implementing the multi-cluster mode with Istio, and I have found conflicting information between the official documentation and various online blogs. According to Istio's official documentation, it seems that the multi-cluster mode is not currently supported in ambient mode. However, I have come across some blogs that claim it is possible to configure Istio in ambient mode to operate with multi-cluster.

I would like to know:
1) If the multi-cluster mode is not supported, what are the technical limitations or main reasons preventing this functionality?
2) If the multi-cluster mode is supported, could you provide a guide or detailed example on how to properly configure the clusters?

Until now  I have installed Istio Ambient in two clusters. I managed to get communication working in Ambient mode within the same cluster and in Sidecar mode between the two clusters. However, when I try to communicate between a pod in Sidecar mode on cluster1 and a service in Ambient mode on cluster2, I receive a 503 error. Additionally, if I try to communicate between Ambient and Ambient or between Ambient and Sidecar, the service cannot be resolved.

Any clarification would be greatly appreciated, as this functionality is crucial for our current project.
Thank you in advance for your support.

Best regards

Roberto Di Stefano

### Version

```Text
$ istioctl version
client version: 1.21.0
control plane version: 1.23.3
data plane version: 1.23.3 (21 proxies)

$ kubectl version
Client Version: v1.21.14
Server Version: v1.30.7
```

**Comment by hzxuzhonghu** [comment]
https://docs.google.com/document/d/1Wg6sx9ZUJL4AsHj5wM1kMx3E436s5wg2qoMqoI-bqbQ/edit?tab=t.0#heading=h.ppr0kg59hrq3

**Comment by howardjohn** [comment]
Istio ambient does not support multicluster in any form currently. If you see any official docs stating otherwise let us know and we can fix those up.

**Comment by ro-distefano** [comment]
Thank you for the answers, 

another question, as of today there is an approximate date by which the multicluster mode will be enabled in ambient.

Best regards

Roberto Di Stefano
