### ISSUE TITLE
Failing 1.23.4 CRDs

### ISSUE THREAD

**Issue by OteemoSanjay** [istio/istio#54476]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

hi

When apply the CRDs, version 1.23.4 seems to fail after the telemetries.telemetry.istio.io

When apply via kubectl after the binaries extracted, we get a 403.

(⎈|sandbox1:istio-system)sjairam@sanjMacBookM3 crds % k apply -f crd-all.gen.yaml --validate=false
customresourcedefinition.apiextensions.k8s.io/wasmplugins.extensions.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/proxyconfigs.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/telemetries.telemetry.istio.io unchanged
Error from server (Forbidden): error when creating "crd-all.gen.yaml": <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html> (post customresourcedefinitions.apiextensions.k8s.io)
Error from server (Forbidden): error when creating "crd-all.gen.yaml": <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>

### Version

```Text
(⎈|sandbox1:istio-system)sjairam@sanjMacBookM3 istio-kiali % istioctl version
client version: 1.23.4
control plane version: 1.23.4
data plane version: 1.23.4 (6 proxies)

(⎈|sandbox1:istio-system)sjairam@sanjMacBookM3 istio-kiali % kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.4+rke2r1
```

### Additional Information

Even via istioctl install -f there seem to be issues with the 1.23.4 release.
This works fine in 1.22.6

There are no remanants of 1.22.x on the cluster as we did a full rebuild

**Comment by OteemoSanjay** [comment]
hi
Addded CRD from 1.23.4 
[istio-1.23.4-osx-arm64.tar.gz](https://github.com/user-attachments/files/18253491/istio-1.23.4-osx-arm64.tar.gz)

rgds sanj

**Comment by howardjohn** [comment]
that is a (nonstandard) error from the API server. You'll want to debut your API server for why it's behaving strange. I do not see how Istio can cause this.
