### ISSUE TITLE
Zone Aware Routing - Mesh expansion and VM only enviornment

### ISSUE THREAD

**Issue by vilobhmm** [istio/istio#5454]
Evaluate whether Zone aware routing works for Mesh expansion and VM only enviornments.

**Comment by vilobhmm** [comment]
@costinm : ^^

**Comment by costinm** [comment]
AFAIK it works - but needs testing. 
@vilobhmm  - if you have some time, please check it, if it works we can document it in 0.8. 
( code is using ServiceEntry labels to set the equivalent of the zone aware node annotations)
