### ISSUE TITLE
SNI sniffing/routing support in Gateway

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5455]
Envoy is adding support for SNI sniffing and routing in envoyproxy/envoy#3217 and  envoyproxy/envoy#3267, similar to apache traffic server:

https://docs.trafficserver.apache.org/en/latest/admin-guide/layer-4-routing.en.html

We need corresponding pilot changes to enable this in Gateway
cc @costinm @rshriram @PiotrSikora

**Comment by andraxylia** [comment]
Re-open, #5282 will track just sniffing for incremental mTLS adoption.

**Comment by rshriram** [comment]
This is already implemented in the gateway and sidecars as well.

**Comment by avdhoot** [comment]
@rshriram @andraxylia Is SNI routing is supported on ingress gateway?
