### ISSUE TITLE
Strip proxy release binary

### ISSUE THREAD

**Issue by costinm** [istio/istio#5477]
It's a simple/safe change - the proxy image is huge (300M - bigger than the ubuntu base)

**Comment by costinm** [comment]
We still need to update the sha in istio/istio once the proxy build is ready.

**Comment by hklai** [comment]
@costinm it should already be done now with https://github.com/istio/istio/pull/5482

**Comment by costinm** [comment]
It doesn't make sense - you can build a docker image with debug symbols for your own debugging. 
That doesn't mean regular users need this. Just replace the envoy in the docker container with your custom build.

The real problem is that core dump seems to be broken - and we should fix that, which will give you all
the info you need.

Please revert the release version with stripped binary - I can change the build to generate a custom version of proxy with debug symbols if  we find more crashes and core dumps can't be fixed - but vast majority of users don't need this.

**Comment by costinm** [comment]
Please revert back to stripped - #5745 will take care of providing detailed stack trace ( core can be used against an unstripped binary ). We will need to provide a download link for an unstripped binary for devs who need to debug core dumps - but this can be done separately.
