### ISSUE TITLE
Authn policy's TargetSelector support for subset 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#5486]
authN policy's [TargetSelector](https://github.com/istio/api/blob/master/authentication/v1alpha1/policy.proto#L320) has subset property defined in proto but not been used in the code now.  Policy dark launch may need the authn policy subset field to take effect to align with [VirtualService.http.mirror.subset](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L310)

Current behavior:
1. create a VirtualService which contains two subset v1, v2; v2 is only for traffic mirroring. 
2. apply an authN policy only on subset v2.
3. send traffic to the service, got resp code 401, expected 200.

**Comment by rshriram** [comment]
There is no status code for mirroring. It’s fire and forget.

**Comment by quanjielin** [comment]
1. Yes, 'fire and forget' is from user's standpoint, Istio proxy still can get status code of the mirroring traffic and report it(together with other attributes we want to collect) to mixer. 
2. For my example described in this issue, user should get a 200, since real traffic is routed to service subset without authn policy applied; the reason why it got 401 now is because authn policy doesn't support subset, that's what PR https://github.com/istio/istio/pull/5521 trying to fix.

**Comment by diemtvu** [comment]
We probably want to remove subset concept for authn policy for now, until we have clearer idea how to make the whole concept more consistent. For the time being, I think authN is on `workload`, so it may be better to use label directly, instead of `subset`, which is more on the `service` concept.

**Comment by diemtvu** [comment]
Btw, https://github.com/istio/api/pull/469 will remove `subset` in authN to avoid confusion for now.

**Comment by rshriram** [comment]
> Yes, 'fire and forget' is from user's standpoint, Istio proxy still can get status code of the mirroring traffic and report it(together with other attributes we want to collect) to mixer.

Its fire and forget from Envoy. So, unless you propagate some custom headers and then trap them on the receiving end, you really cannot track the response codes for mirrored traffic.

**Comment by quanjielin** [comment]
@rshriram, I think by default mixer filter already captured all request/response headers which includes resp code etc(even for mirroring);  agree more logic needs to be added if we need to collect non-default custom attributes in the proxy.
