### ISSUE TITLE
Pilot 0.2 cannot work with rbac cluster

### ISSUE THREAD

**Issue by yutongz** [istio/istio#550]
The latest 0.2 version crashes in rbac cluster. 
In a rbac enabled cluster, I apply rbac rule first, and apply istio.yaml with pilot:0.2.0. The pilot pod crashed immediately with the status "error". I tried to describe the pod, no obvious message showing why it happened.

**Comment by kyessenov** [comment]
expected since I removed the "default" account permissions hack.
@mandarjog and @myidpt to provide RBAC rules for Istio components now that they're being enforced.

**Comment by ldemailly** [comment]
we should ideally improve the logging to make clear that the failure has to do with unable to get some permissions
