### ISSUE TITLE
Istio performance regression 0.8.0-pre20180417-22-02 --> release-0.8-20180504-17-20

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5509]
https://ibmcloud-perf.istio.io/regpatrol/

0.8.0-pre20180417 to 0.8-20180504

Ingress only performance has gradually regressed from: 3961 --> 3469  ~ 13 %
Full istio performance: 1240 --> 1147

**Comment by mandarjog** [comment]
@suryadu @ldemailly @costinm

**Comment by mandarjog** [comment]
https://fortio-daily.istio.io/?xMin=&xMax=&xLog=false&yLog=false&sel=qps_max-s1_to_s2-release-0.8-20180508-17-41-2018-05-08-18-11&sel=qps_max-s1_to_s2-0.8.0-pre20180417-22-02-2018-04-18-01-37

fortio found a similar regression.

**Comment by ldemailly** [comment]
closing this in favor of more current data
