### ISSUE TITLE
Allow microservice visit external network

### ISSUE THREAD

**Issue by lqj679ssn** [istio/istio#5519]
For `bookinfo` sample, the `details` microservice visits external google api and succeeds. And the config file should be `egress-rule-google-apis.yaml`. But when I run this sample, I only used `bookinfo.yaml`, but never touched `egress-rule-google-apis.yaml`.
How could that be?

**Comment by vadimeisenbergibm** [comment]
It is `details` `v2` that uses google api, `bookinfo.yaml` deploys `details` `v1`, which does not use external services.
