### ISSUE TITLE
Case-insensitive DNS names

### ISSUE THREAD

**Issue by Nino-K** [istio/istio#5527]
We notice that DNS validation in [Pilot's model validation](https://github.com/istio/istio/blob/35e2b9042fe3d4ebe68772311aa1ebe46b66a1be/pilot/pkg/model/validation.go#L45) is using a regex which does not support uppercase dns entries. There is a newer [RFC 4343](https://tools.ietf.org/html/rfc4343) which states that the DNS names are case insensitive. Also in kubernete's [DNS validation](https://github.com/kubernetes/kubernetes/pull/39635/files) this change has already taken place. 

Is this a potential change that we could PR?

**Comment by shalako** [comment]
@rshriram

**Comment by rshriram** [comment]
Shouldn’t make a difference in current code. Go for it

**Comment by ymesika** [comment]
Fixed by #5528
