### ISSUE TITLE
istioctl kube-inject 0.2.0 references images which do not exist

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#553]
image: docker.io/istio/proxy_debug:0.2.0
        image: docker.io/istio/proxy_init:0.2.0

can we push those images asap (or make a 0.2.1 with working images/kube-inject) ?
(I guess it's somewhat related to, but not a dup of (imo) #538 but somewhat more acute as it's not working at the moment)

**Comment by sebastienvas** [comment]
Done created those 2.

**Comment by ldemailly** [comment]
thanks a lot ! super fast fix !

**Comment by mclarke47** [comment]
Can you also create https://hub.docker.com/r/istio/proxy/tags/ 0.2.0?

**Comment by ldemailly** [comment]
@mclarke47 curious, why ? (only proxy_init and proxy_debug are referenced as far as I can tell)

**Comment by mclarke47** [comment]
It's just the non debug version of the debug proxy image I think

**Comment by sebastienvas** [comment]
Pushed  docker.io/istio/proxy:0.2.0
