### ISSUE TITLE
Improvements to _istioctl get_ to show key fields

### ISSUE THREAD

**Issue by esnible** [istio/istio#5538]
Currently _istioctl get _type_ shows NAME/TYPE/NAMESPACE.  I'd rather see:

_istioctl get gateways_
```
NAME			    HOSTS	AGE
guestbook-gateway	     *               3d
```

_istioctl get virtualservices_
```
NAME		GATEWAYS		   HOSTS   HTTP 	TCP		AGE
guestbook	guestbook-gateway          *       1       0            3d
```

_istioctl get destinationrule_
```
NAME			HOST                 SUBSETS                                   AGE
helloworld-service	helloworld-service  version-1-0; version-2-0	3d
```

_istioctl get serviceentry_
```
NAME				HOSTS				PORTS         AGE
googleapis			*.googleapis.com             443              2d
```

**Comment by linsun** [comment]
I think this will be very useful.  My vote is to support both single and plural, e.g. 

$ kubectl get virtualservice
NAME        AGE
guestbook   56m

$ kubectl get virtualservices
NAME        AGE
guestbook   56m

**Comment by esnible** [comment]
@rshriram When I created this work item I noticed there was no way to label it as "istioctl" specific.  So I created the label and labeled this myself.  From your comments elsewhere it seems I shouldn't have done that.  Shall I remove the "area/cli" labels I added?  I was trying to keep track of CLI-specific issues.

**Comment by esnible** [comment]
For "legacy" types, and types with no special listing format, I recommend two changes.

Show "AGE" like _kubectl_ does.  (I am almost ready with code for this.)
Ensure there is a space between columns.  Currently we show something like this:

```
$ istioctl get gateways
NAME		KIND					NAMESPACE
bookinfo-gatewayGateway.networking.istio.io.v1alpha3	default
```

It is difficult to parse that output in a script because of the lack of whitespace between "bookinfo-gateway" and Gateway.

**Comment by ozevren** [comment]
@esnible , what is the current implementation state of this issue? What is left?

**Comment by esnible** [comment]
@ozevren All that was left was merging the AGE column.  That was done yesterday and I am closing this item.
