### ISSUE TITLE
Fix service instance lookup by port names

### ISSUE THREAD

**Issue by rshriram** [istio/istio#5539]
we really really need to fix the port lookup by name thing. It’s hindering our ability to reroute traffic from 80 to 443 (ext services), and the ability to route traffic from one service to another (where both services are on different ports), as well as from some port on gateway to some other port on the backend. The real and common fix for all of these is to either add a model.ServiceInstancesByPort(int) or fix model.ServiceInstances() to take integer port argument. I don’t foresee problems from any registry other than kubernetes where we could do a lookup of port name from the service model and then query kube. With this fix in place, we should be able to remove the logic around looking up ports on service in httproute.go ie no more black hole clusters. And all cluster names will only have port number not name. (Also fixes cluster naming stuff partially). I can take a crack at this but need help finishing the PR

**Comment by rshriram** [comment]
#5543 fixes the issue

**Comment by baodongli** [comment]
Can you provide a little bit more details about the issues (such as reroute traffic from 80 to 443, ..), and why replacing instance lookup by port names with by port numbers will fix those issues? thanks.

**Comment by kyessenov** [comment]
Can this hold off 0.8 or is there some blocking issue? This might the same
kind of bugs Mandar encountered trying to change cluster naming.

**Comment by rshriram** [comment]
Gateway to internal service routing is partly broken. Also broken is the ability to reroute from 80 to 443 for external services (http google to auto https google). And finally routing from one service to another on a different (non overlapping port) is also broken.

**Comment by rshriram** [comment]
tackled by #5543
