### ISSUE TITLE
Add mixer destination policy to the default install

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#5546]
cc @hklai.

There is a regression with the upstream cluster settings for mixer filter. This will negatively affect any load performance tests that utilize mixer. We need to bring back those customizations for mixer before shipping the final 0.8.x

**Comment by hklai** [comment]
Is anyone working on this?

**Comment by kyessenov** [comment]
Shouldn't this be assigned to whoever changed the mixer clusters to begin with? :)

**Comment by hklai** [comment]
@mandarjog nominated you. 

The goal is to get 0.8.0 out ASAP and we need all hands onboard.

**Comment by kyessenov** [comment]
Looking into changing helm install for pilot. CRDs are non-trivial with
helm, you need one-time batch jobs, and that has not been done for pilot.

**Comment by hklai** [comment]
What is the status now, given #5568 is closed?

**Comment by kyessenov** [comment]
Mandar took over in https://github.com/istio/istio/pull/5669
