### ISSUE TITLE
Standardize mixer and proxy protobuf definitions in istio/api

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#557]
Currently, mixer uses "Required", while proxy used "REQUIRED". Should be "Required" in both.

**Comment by vadimeisenbergibm** [comment]
Following @ZackButcher's proposal.

**Comment by ldemailly** [comment]
similar to target/destination issue? we should get all the renames in before 0.2 ?

**Comment by rshriram** [comment]
please move to istio/api

**Comment by sakshigoel12** [comment]
rshriram@ - if you are using zenhub there is an option to move issues between repos on the right pane (last option). It would be easier to not close and reopen issues.

**Comment by rshriram** [comment]
I was actually looking for such a feature! will look out for that next time. Thanks

**Comment by ldemailly** [comment]
![screen shot 2017-08-17 at 1 39 54 pm](https://user-images.githubusercontent.com/3664595/29432740-9fd81a8c-8351-11e7-9d24-5ee9edb89963.png)
