### ISSUE TITLE
The story of a broken cluster

### ISSUE THREAD

**Issue by Stono** [istio/istio#5576]
Hey! 
This isn't a bug per-se, but I wanted to share my experience of how I managed to take an entire cluster out today whilst using istio, to see if theres anything you think could be done to stop people not accidentally doing the same...

**Context**
By default, as you can see on this line 
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/sidecar-injector/templates/mutatingwebhook.yaml#L25, the `MutatingWebhookConfiguration` only fires on namespaces labeled with `istio-injection`.  This was fine for us until recently, where a change of process resulted in us creating a _lot_ more namespaces.

Those namespaces were made via `helm install --namespace`, rather than through a `namespace.yaml`, so couldn't be tagged with the label.  You (currently) can't add a `namespace.yaml` to your helm chart with such a value and specify `--namespace` as helm will throw a wobbly about the namespace already existing. 

**The solution to the immediate problem**
Seemed simple, I simply removed the `namespaceSelector` from the MutatingWebhookConfiguration so it would look at all namespaces, and set the `policy` in the ConfigMap for the injector to disabled.  That way all pods would go through the handler, and only those with the annotation would be injected.

**The problem as a result of that solution**
This actually worked beautifully until this sequence of events:

 - The injector pod was rescheduled
 - The MutatingWebhookConfiguration then tried to send the request to the injector pod for the new injector pod, obviously it couldn't, as it's currently offline and because of the `failurePolicy: reject` it never came back up.  So you have a bit of a chicken and the egg scenario.
 - Then slowly but surely as other pods get rescheduled for whatever reason they also don't come back up because of the failure policy
 - Before long this includes the entire kube-system namespace too (we use pre-emptible nodes in this particular environment, so this results in quite a lot of rescheduling).

And you end up with this:
```
❯ kubectl --namespace=kube-system get pods
No resources found.
```

A very broken cluster.

Feel free to change the title to something more suitable!

**Comment by Stono** [comment]
For those who are interested, I inverted the logic:

```
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
```

I then labeled istio-system with `disabled`:
```
kubectl label namespace istio-system istio-injection=disabled
kubectl label namespace kube-system istio-injection=disabled
```

**Comment by mandarjog** [comment]
@Stono thanks for that entertaining description.
I think your inverted namespace selector is a fine solution. The question is can we just make that the default. I think so.

**Comment by Stono** [comment]
@mandarjog just like to throw in a suggestion here.
Making this part of the webhook configurable as part of the helm `values.yaml` would mean one less manual mutation of the `gen-deploy` output for us.

**Comment by sakshigoel12** [comment]
@ajy can you take a look?

**Comment by ostromart** [comment]
Seems to be working ok in my testing. I'll move ahead with making this change to the template.

**Comment by nmittler** [comment]
@ostromart any updates?

**Comment by ostromart** [comment]
It's working it's way up the queue - will get to it this week.

**Comment by ostromart** [comment]
I have a partial PR for it, but still need to control opt-in to new behavior with a flag.
https://github.com/istio/istio/pull/6439
