### ISSUE TITLE
Connecting to AWS RDS in Istio Service Mesh

### ISSUE THREAD

**Issue by anuranjit** [istio/istio#5580]
We have a issue where connecting to AWS RDS in Istio Service Mesh is results in `upstream connect error or disconnect/reset before header` . 
Our Egress rule is as below  

     apiVersion: config.istio.io/v1alpha2
     kind: EgressRule
     metadata:
         namespace: <our-namespace>
         name: rds-egress-rule-with
     spec:
         destination:
         service: <RDS End point> 
     ports:
         - port: 80
           protocol: http
         - port: 443
           protocol: https
         - port: 3306
           protocol: https 

The connection to MySQL works fine in a stand alone MySQL in EC2. The connection to AWS RDS works fine without Istio.  The problem only occurs in Istio Service Mesh. 

We are using istio in Disabled Mutual TLS Configuration.

**Comment by etiennetremel** [comment]
You should consider migrating to the new networking.istio.io/v1alpha3 API and use a [TCP EgressRule](https://istio.io/docs/tasks/traffic-management/egress-tcp/) instead.

**Comment by andraxylia** [comment]
Please re-open if you still see issues with the 0.8 release and the new alpha3 apis:

https://istio.io/docs/tasks/traffic-management/egress/

**Comment by jh-sz** [comment]
I am experiencing the same issue, and using istio v1.3.0. The cluster is new and without any network policies or egress rules configuration. I have `global.outboundTrafficPolicy.mode` in default `ALLOW_ANY`. And I am able to connect to other rds postgres db instances in rds but not one of them and having password error similar to [this article](https://medium.com/@cy.chiang/problems-when-trying-to-connect-aws-services-with-istio-a5140d2846ab), but his solution doesn't work for me

**Comment by jh-sz** [comment]
OK.. I have got it working, in case anyone else stumble on to this, my setup might be a bit different, basically i have vpc-peering and communicating with rds postgres db instance from another vpc.
https://github.com/istio/istio/issues/6593 helped me. Basically i need to add a `ServiceEntry`.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloud-sql-instance
#  namespace: istio-example-cloud-sql
spec:
  hosts:
  # looks like the host here doesn't matter
  # Note that the hosts field is ignored for TCP service entries.
  # but service entry must have at least 1 host
  - xxx.com
  addresses:
  # and i gave the vpc cidr of the peering vpc
  - 192.168.0.0/16 # a block of IPs in CIDR notation
  ports:
  - name: tcp
    number: 5432 # at the moment, Google Cloud SQL always available on port 3307
    protocol: tcp # enable TCP traffic
  location: MESH_EXTERNAL
```

**Comment by gustavovalverde** [comment]
I'm still not understanding why if the if the `outboundTrafficPolicy.mode` is set to ALLOW_ANY this steps are still needed. Isn't this a bug? @rshriram @vadimeisenbergibm

**Comment by rshriram** [comment]
Outbound traffic policy controls the behavior of the sidecar (after traffic capture). The sidecar will forward the traffic as is, for "unknown" services. However, in the case above, there is a service entry for port 5432 or 3306 or whatever. All captured traffic lands on that envoy listener. Per the service entry, traffic for that port is configured in Envoy as 0.0.0.0:3306 (i.e. traffic for ANY ip:3306 will land in this Envoy listener, as we dont know the service IP for this RDS service).

So, when it lands on 0.0.0.0:3306, the first specified host will be the destination. You are probably better off doing something like this:

```serviceEntry:
hosts: dummy.com
ports:
- name: blah, number:3306, protocol: TCP
location: MESH_EXTERNAL
resolution: NONE
```

In combination with ALLOW_ANY, this will achieve the desired effect - i.e. all traffic to 3306 will be forwarded as is, irrespective of the destination host DNS or IP.

**Comment by jh-sz** [comment]
Apologies, i found the root cause of my problem, and haven't got a chance to update my comment. Still new to istio.

My problem is because I defined an externalName for the db address:
```
kind: Service
apiVersion: v1
spec:
  type: ExternalName
  externalName: my-db.example.com
  ports:
  - port: 5432
```
And since ExternalName does not have a `ClusterIP`, it becomes `0.0.0.0`. I have removed the port from `ExternalName` service for now. Which seem work for my case, and I don't need to add a `ServiceEntry` for that

**Comment by mswehli** [comment]
Just to add, i had the opposite problem as @jh-sz . I'm using AWS RDS on the same VPC as my istio cluster, and just habitually added a ServiceEntry for the db, for it to resolve externally. 
When using AWS RDS from within the same VPC as the kubernetes cluster, remove the service entry resource!
