### ISSUE TITLE
bookinfo nonfunctional on 0.8 branch

### ISSUE THREAD

**Issue by sdake** [istio/istio#5600]
bookinfo was recently updated in commit a45393812edff128464105c1790fb893fb184d13 which breaks bookinfo for me locally on my testbed.  I am running in the gate to see if I can get a clean run out of CI: https://github.com/istio/istio/pull/5599.

A git revert of the commit results in a working bookinfo.

Using bookinfo from upstream/release-0.7 branch works.

Behavior:
```
STDAKE-M-26T1:~ sdake$ !curl
curl -v 10.23.220.90/productpage
*   Trying 10.23.220.90...
* TCP_NODELAY set
* Connected to 10.23.220.90 (10.23.220.90) port 80 (#0)
> GET /productpage HTTP/1.1
> Host: 10.23.220.90
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Tue, 15 May 2018 02:01:56 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host 10.23.220.90 left intact```

same curl with 0.7 produces the product pages.

**Comment by sdake** [comment]
as the gatecheck passed, I'd appreciate if another dev could validate if release-0.8 works for them.

**Comment by vadimeisenbergibm** [comment]
@sdake Please note the instructions for configuring the new Istio Ingress Gateway https://vadimeisenbergibm.github.io/docs/tasks/traffic-management-v1alpha3/ingress.html. A PR submitted to istio/istio.github.io.

**Comment by sdake** [comment]
Thanks for the information related to the public IP allocation.  I wasn't aware that was an issue, but have noticed it definately.  This raises   the question how do we ship that envoyv2 transition target, as the default make target (istio-auth.yaml) includes both ingress and ingressgateway.

**Comment by sdake** [comment]
@vadimeisenbergibm thanks for pointing out the updated documentation.  I will give it a go in a few hours after my morning routine and respond on this bug if this isn't busted.  I guess I should have looked in preliminary.  My bad.  Still concerned about the dual ingress commentary.  Not sure what to do about that issue.

Cheers
-steve

**Comment by vadimeisenbergibm** [comment]
@sdake The simplest thing to do currently is to remove _ingress_ from your Istio yamls and not to deploy it. Either manually, or by running `make generate_yaml-envoyv2_transition_loadbalancer_ingressgateway` or by helm `--set ingress.enabled=false` option.

**Comment by hklai** [comment]
@sdake @vadimeisenbergibm 
Any update? Is this still release blocking?

**Comment by sdake** [comment]
closing - found a doc workaround.  thanks.
