### ISSUE TITLE
race test is failing everywhere

### ISSUE THREAD

**Issue by linsun** [istio/istio#5608]
and didn't generate a report either... we can't mark it as required when none of the PR can pass the test.

cc @mandarjog @xiaolanz @hklai

**Comment by linsun** [comment]
sample PR https://github.com/istio/istio/pull/5597

**Comment by linsun** [comment]
FYI, i discussed this on #oncall and #test-and-release, and followed the process to disable the race test as required.

**Comment by hklai** [comment]
Let's track race test problems and updates in https://github.com/istio/istio/issues/4235 going forward.
