### ISSUE TITLE
Istio does not remove cluster dynamically when remove a cluster secret

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5629]
This is a follow up issue for https://github.com/istio/istio/issues/5534 .

After a remote cluster was registered via secret, then even after we delete the remote cluster secret, we can still access the services in the remote cluster. 

The [deleteMemberCluster](https://github.com/istio/istio/blob/release-0.8/pilot/pkg/config/clusterregistry/secretcontroller.go#L257-L272) should be updated to remove service controller registry etc.

/cc @sbezverk @sdake

**Comment by ymesika** [comment]
Fixed by #5672
