### ISSUE TITLE
Create a dummy e2e test that just test the depoyment

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#564]
This will be used to understand if the testing infra structure is failing.
Example
- Create a namespace
- Deploy a dummy application ie Nginx echo
- Send wrk request to it

We should not deploy istio.

**Comment by linsun** [comment]
is this still planned for v0.2?   i'd like to move to 0.3, let me know if you object to it.

**Comment by hklai** [comment]
This looks obsolete. Closing. Please reopen if this is applicable.
