### ISSUE TITLE
Use existing CRs in the pilot config validate function

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#5646]
Currently the config validation is done by the Validate function specified in ProtoSchema: https://github.com/istio/istio/blob/26262e8a1d89c4cd17f52db645d91ce9d9918e6e/pilot/pkg/model/config.go#L210

The Validate function only accepts the config proto as argument which limits the ability of the validation. In order to have a deep semantic validation, it's necessary to fetch the existing CRs so that we have more information to do more validation.

For example, In RBAC policy, A ServiceRoleBinding needs to reference to an existing ServiceRole and we would like to make sure such reference is valid. so we need first know what ServiceRole we already have in system. (@liminw)

In the Authn policy, Operators are responsible to make sure there are no other policy already defined for a specific host when submitting new one, it would be nice if we can catch this in validation stage. (@diemtvu)

I'm creating this issue to look for some suggestions to see if this is doable (technically, we should be able to either pass the IstioConfigStore to Validation or create a new k8s client inside the Validation in order to fetch the needed CRs).
Comments are appreciated, Thank you!
@kyessenov @costinm  @ayj  @andraxylia @rshriram

**Comment by ayj** [comment]
By "deep semantic validation" I believe you mean checking referential integrity across resources. That's not really possible with the Kubernetes' resource model. Event ordering would prevent a 100% reliable scheme using local cache for cross-resource checking.

(From Kubernetes Resource Management doc, see [here](https://docs.google.com/document/d/1RmHXdLhNbyOWPW_AtnnowaRfGejw-qlKQIuLKQWlwzs/edit#heading=h.s1pss2oftys))
> The Kubernetes API also does not provide strong ordering or consistency across multiple resources, and does not enforce referential integrity

>  A ServiceRoleBinding needs to reference to an existing ServiceRole and we would like to make sure such reference is valid.

This could could be reported in the ServiceRoleBinding's status field based on the observed state of the system as a whole. But lack of ServiceRole wouldn't block creation of ServiceRoleBinding.

> Operators are responsible to make sure there are no other policy already defined for a specific host.

This could be addressed by using the host as the resource name, assuming host is scoped to the service and resource namespace.
