### ISSUE TITLE
Need validation to not allow multiple VirtualServices or DestinationRules for the same host

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5647]
from @ayj on slack
"Admission webhook (pre-create/update) in k8s doesn't support atomic transactions across multiple resources. See "Additional resource model properties" in https://docs.google.com/document/d/1RmHXdLhNbyOWPW_AtnnowaRfGejw-qlKQIuLKQWlwzs. 

Best case Pilot could possibly detect and reflect conflict back into resource's status field"

**Comment by shubhaat** [comment]
We also came across this issue. We were able to associate multiple virtual services with the same host.  What makes this more confusing is that we could not do a read or a get to see which virtual service is actually applied for the host. Ideally an operator would get an error when trying to create multiple virtual services for the same host. 

To see an example, refer to the gist here: https://gist.github.com/shubhaat/13cc9651d4ff3a678d64ea4526d57437
