### ISSUE TITLE
TestTempWorkspace is failing in 0.8 release qualification

### ISSUE THREAD

**Issue by hklai** [istio/istio#5648]
I0516 19:36:03.877] === RUN   TestTempWorkspace
I0516 19:36:03.878] 2018-05-16T19:36:03.877592Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0516 19:36:03.878] 2018-05-16T19:36:03.878124Z	warn	error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
I0516 19:36:03.879] --- FAIL: TestTempWorkspace (0.00s)

**Comment by linsun** [comment]
could you show me a log that has this test working?   I can't find any.   I think the test was not running in a cluster thus not able to create incluster config.  cc @ayj

**Comment by linsun** [comment]
a failed one:  https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/597/daily-pilot-e2e-envoyv2-v1alpha3/101/?log#log

**Comment by hklai** [comment]
@linsun

The test passed in this run in the release-0.8 branch.
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/5616/istio-pilot-e2e-envoyv2-v1alpha3/1575/

Could you help figure out why it seem to fail consistently in the daily tests for release-0.8?
https://prow.istio.io/?job=daily-pilot-e2e-envoyv2-v1alpha3

The two successful runs were from master instead (which means it failed fairly often in master as well)?

**Comment by linsun** [comment]
@hklai this 5615 one seems to be run today, and it has my change I'd assume.

It seems something environmental, either the test code isn't running in a k8s cluster or the k8s cluster isn't cleaned properly which cause not able to create the k8s client for the k8s cluster that the test code is supposed to run.

**Comment by linsun** [comment]
close now since Seb made a fix
