### ISSUE TITLE
Need to update .jinja for 0.8

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5676]
For Istio testing community day, I tried to follow the instructions below, and noticed the Istio 0.6 is installed by default and I cannot override the version.
https://preliminary.istio.io/docs/setup/kubernetes/quick-start-gke-dm.html

This issue is to update .jinja si re-do the testing to verify correct version is installed.

**Comment by yusuoh** [comment]
@selmanj Could you please take this issue?

**Comment by hklai** [comment]
Just checked with @selmanj. He kindly agreed to test this out and verify if the template can work with 0.8.

**Comment by jasmine-jaksic** [comment]
@selmanj can progress on this?

**Comment by selmanj** [comment]
@salrashid123 is currently working on this - I think he's gotten pretty close.

**Comment by salrashid123** [comment]
pls see:
* template https://github.com/istio/istio/pull/6010
* docs https://github.com/istio/istio.github.io/pull/1437

**Comment by smawson** [comment]
Looks like this was fixed but not closed, reopen if I got that wrong.
