### ISSUE TITLE
Cannot install sidecar injector with helm

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5678]
Downloaded 0.8 candidate.

helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set prometheus.enabled=true > $HOME/istio.yaml

Followed instructions from here for sidecar injector with helm:
https://preliminary.istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection

Got:
helm install --namespace=istio-system --set sidecar-injector.enabled=true install/kubernetes/helm/istio
Error: release loopy-stoat failed: configmaps "istio-mixer-custom-resources" already exists

- delete step does not work if helm template was used , only if helm install was used:
helm delete --purge istio

- Customization with help is possible also during helm template command, not just during install. Please update the text :" during the helm install command. "

**Comment by andraxylia** [comment]
cc @linsun

**Comment by sdake** [comment]
I can see how the docs are a little confusing.

There are two alternative workflows - one uses helm install / kubectl create - the other uses helm install (with no kubectl create).

The exact 3 steps that must be followed for istio with injection are:
https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html#alternatively-use-helm-and-tiller-to-manage-the-istio-deployment

**Comment by mandarjog** [comment]
@andraxylia as sdake states the change was already made by @Tahler 
It removes the confusing instructions.

**Comment by mandarjog** [comment]
Removing release blocking, if you think its not sufficient please suggest changes. Thanks.

**Comment by andraxylia** [comment]
ok to close
