### ISSUE TITLE
Feature Request - Kiali addon

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5683]
Kiali is a front end to istio currently in development (no official release just yet) - it does take the Prometheus metrics and visualizes them (along with visualizing the mesh and other things such as visualizing circuit breakers, route rules and integrating Jaeger tracing). See https://kiali.github.io/ for details. 

There is a JIRA issue created to propose it as an istio add-on at here https://issues.jboss.org/browse/KIALI-386

Tasks in this would include 
- istio/kubernetes addon template
- kubernetes helm chart

/cc @linsun @morvencao

**Comment by sdake** [comment]
looks good!  The tracing threw an error, but I had tracing disabled.

**Comment by gbaufake** [comment]
@sdake and @gyliu513, I sent #5921 to include on Ansible as well.
