### ISSUE TITLE
Fault injection with Abort match clause not working

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5685]
I tried this task with Abort
https://preliminary.istio.io/docs/tasks/traffic-management/fault-injection.html

I see service not available even when I am not logged in as Jason. It rounds robin between v1 and "service not available".

Behaviour is the same if I log in as user "jason" or not.

Unclear if there is an error in the yaml file, since the yaml is similar to the delay case, and that one works.

cc @ijsnellf @GregHanson

**Comment by ymesika** [comment]
Tested with `istio-release-0.8-20180526-09-15` and it works as expected.
