### ISSUE TITLE
Secure Gateway does not work

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5686]
Followed the instructions here:
https://preliminary.istio.io/docs/tasks/traffic-management/ingress.html

Make sure you do not have another Gateway matching "*", because this will not work at all.

Regular Gateway works, secure does not:
$ curl -I -k https://$SECURE_INGRESS_HOST/status/200
Skippy Security Tip: It seems that you are using the flags: --insecure or -k. These flags disable SSL verification and could allow someone to tamper with your connection.
Suggestion: Use curl without the flags: --insecure or -k
More info: http://go/roole/downloaders_nossl.md
Do you still want to execute this command? [y/n]y
curl: (7) Failed to connect to 192.168.99.100 port 31390: Connection refused

Regular Gateway works:
$ curl -I http://$INGRESS_HOST/status/200
HTTP/1.1 200 OK
server: envoy
date: Thu, 17 May 2018 22:35:50 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 5

**Comment by cmluciano** [comment]
https://github.com/istio/istio.github.io/pull/1286 was merged recently, I will test if the extra settings work

**Comment by cmluciano** [comment]
Confirmed with `DAILY=release-0.8-20180520-18-17` and the latest preliminary docs are not working. I don't know if this is a problem on MacOS with LibreSSL or not. 

```
curl --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST -I -k https://httpbin.example.com:$SECURE_INGRESS_PORT/status/200
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.example.com:443 
```

**Comment by lizan** [comment]
Confirmed with `istio-release-0.8-20180521-15-16` as well, it doesn't seems to it related to MacOS.

```
$ curl -k -vvvv --resolve httpbin.example.com:443:$INGRESS_HOST -I http://httpbin.example.com:443/status/404

* Added httpbin.example.com:443:35.202.150.39 to DNS cache
* Hostname httpbin.example.com was found in DNS cache
*   Trying 35.202.150.39...
* TCP_NODELAY set
* Connected to httpbin.example.com (35.202.150.39) port 443 (#0)
> HEAD /status/404 HTTP/1.1
> Host: httpbin.example.com:443
> User-Agent: curl/7.52.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by lizan** [comment]
Looks like the gateway is not listening to port 443, here is the logs from ingressgateway pod:

```
[2018-05-21 22:27:26.835][20][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:200] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener tcp_0.0.0.0_443: unable to read file: /etc/istio/ingressgateway-certs/tls.crt
[2018-05-21 22:27:26.835][20][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:69] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener tcp_0.0.0.0_443: unable to read file: /etc/istio/ingressgateway-certs/tls.crt
[2018-05-21 22:28:03.706][20][info][upstream] external/envoy/source/server/lds_api.cc:61] lds: add/update listener 'tcp_0.0.0.0_443'
```

**Comment by lizan** [comment]
After restarting ingress I don't see the error above, though LDS delivered filter chain with no filters to ingress:

```
filter_chains {
  filter_chain_match {
    sni_domains: "httpbin.example.com"
  }
  tls_context {
    common_tls_context {
      tls_certificates {
        certificate_chain {
          filename: "/etc/istio/ingressgateway-certs/tls.crt"
        }
        private_key {
          filename: "/etc/istio/ingressgateway-certs/tls.key"
        }
      }
      alpn_protocols: "h2"
      alpn_protocols: "http/1.1"
    }
    require_sni {
    }
  }
}
```

**Comment by rshriram** [comment]
@lizan see my pr on SNI forwarding. I think if fixes this issue.

**Comment by vadimeisenbergibm** [comment]
@andraxylia @cmluciano @lizan @rshriram note that it takes some time (30-60 seconds) for the secret gateway to start working, after adding the secret and redefining the gateway definition. We should decide what to do with it:
1. Add a comment to the documentation and advise to wait for 30-60 seconds
1. Debug this issue

**Comment by frankbu** [comment]
@vadimeisenbergibm I think there's more to it. I waited several minutes but it continues to fail
```
$ curl --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST -I -k https://httpbin.example.com:$SECURE_INGRESS_PORT/status/200
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.example.com:31390 
```

**Comment by cmluciano** [comment]
Echo'ing Frank's findings. I get the same error from a build that I just created from release-0.8 tip

**Comment by vadimeisenbergibm** [comment]
@frankbu @cmluciano I see, will debug it today.

**Comment by rshriram** [comment]
The problem is with SNI. The gateway's SNI is probably set to `*`

**Comment by lizan** [comment]
With `istio-release-0.8-20180523-09-15` this worked expected with the latest doc.

**Comment by andraxylia** [comment]
I will close this based on confirmation from @lizan . Thanks @rshriram @vadimeisenbergibm .

**Comment by frankbu** [comment]
FYI, I confirmed it does work for me now.

**Comment by Deepika1010** [comment]
> I tried the same release and still could not get this to work after waiting 5+ minutes
> 
> ```
> curl --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST -I -k https://httpbin.example.com:$SECURE_INGRESS_PORT/status/200
> curl: (35) gnutls_handshake() failed: Error in the pull function.
> ```
> ```
> curl --resolve httpbin.example.com:$INGRESS_PORT:$INGRESS_HOST -I http://httpbin.example.com:$INGRESS_PORT/status/200
> 
> HTTP/1.1 404 Not Found
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: text/html; charset=utf-8
> Connection: Keep-Alive
> Content-Length: 558
> ```
> I'm fine with keeping this closed if there is a sufficient quorum of individuals that have made it work. My only caution would be if my e2e test in #5547 continues to fail after rebasing/updates.

Any Solution to this error, I am facing the same, using istio-1.0.5:
curl: (35) gnutls_handshake() failed: Error in the pull function.

**Comment by frankbu** [comment]
It's worked for me since the SNI fix.

@cmluciano is the one that seemed to still be having a problem. Is that still the case?

**Comment by apryiomka** [comment]
I still cannot make this work in istio v1.7:

```
istioctl -n istio-system proxy-config listener $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0]..metadata.name}')
ADDRESS PORT  MATCH                DESTINATION
0.0.0.0 8080  ALL                  Route: http.80
0.0.0.0 8443  SNI: *.example.com Route: https.443.https.mygateway.istio-system
0.0.0.0 15021 ALL                  Non-HTTP/Non-TCP
0.0.0.0 15090 ALL                  Non-HTTP/Non-TCP
```

The gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-credential
    hosts:
    - '*'
```
the virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
  - httpbin.example.com
  gateways:
  - mygateway.istio-system
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 80
        host: httpbin
```

I am getting this:
```
curl -v -HHost:httpbin.example.com --resolve "httpbin.example.com:31047:10.0.0.1" -I -k "https://httpbin.example.com:31047/status/200" --insecure
* Added httpbin.example.com:31047:10.0.0.1 to DNS cache
* Hostname httpbin.example.com was found in DNS cache
*   Trying 10.0.0.1...
* Connected to httpbin.example.com (10.0.0.1) port 31047 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the pull function.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the pull function.
```
