### ISSUE TITLE
Ingress traffic via k8s Ingress no longer works

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#5689]
This task does not work.
https://preliminary.istio.io/docs/tasks/traffic-management/ingress.html#verifying-simple-ingress

The documentation needs to be updated.

**Comment by jasmine-jaksic** [comment]
Can you provide more specifics on which parts of the doc needs to be updated?

**Comment by andraxylia** [comment]
The part I link to in the description does not work.

**Comment by vadimeisenbergibm** [comment]
@andraxylia Please note that the documentation was updated and the ingress should work now. Note also my comment here - https://github.com/istio/istio/issues/5686#issuecomment-390886204

**Comment by vadimeisenbergibm** [comment]
Closing, based on https://github.com/istio/istio/issues/5686#issuecomment-391560577.

**Comment by andraxylia** [comment]
Re-opening, I just tried and it does not work.

**Comment by andraxylia** [comment]
I tried the task and this is what ingress log shows when I
curl -I http://192.168.99.100:32000/status/200 

2018-05-30 01:10:41.054][21][debug][filter] src/envoy/http/mixer/filter.cc:175] Called Mixer::Filter : check complete OK
[2018-05-30 01:10:41.054][21][debug][router] external/envoy/source/common/router/router.cc:196] [C19][S5275222670755177034] **no cluster match for URL '/status/200'**
[2018-05-30 01:10:41.055][21][debug][http] external/envoy/source/common/http/conn_manager_impl.cc:970] [C19][S5275222670755177034] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Wed, 30 May 2018 01:10:38 GMT'
'server', 'envoy'

2018-05-30 01:10:41.054][21][debug][filter] src/envoy/http/mixer/filter.cc:175] Called Mixer::Filter : check complete OK
[2018-05-30 01:10:41.054][21][debug][router] external/envoy/source/common/router/router.cc:196] [C19][S5275222670755177034] no cluster match for URL '/status/200'
[2018-05-30 01:10:41.055][21][debug][http] external/envoy/source/common/http/conn_manager_impl.cc:970] [C19][S5275222670755177034] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Wed, 30 May 2018 01:10:38 GMT'
'server', 'envoy'

However, the route for status/200 is there, and the cluster is there, see attached files.
[rds.txt](https://github.com/istio/istio/files/2052015/rds.txt)
[cds.txt](https://github.com/istio/istio/files/2052016/cds.txt)

**Comment by costinm** [comment]
I'm confused: if you are following the new instructions (with Gateway) - you can't have rds/cds. Those are 
intended for ingressgateway, which only uses v2/ADS.

For ingress - the old 7.1 docs apply.

**Comment by vadimeisenbergibm** [comment]
@andraxylia The latest instructions are here https://istio.io/docs/tasks/traffic-management/ingress/. They are valid for `istio-ingressgateway` with v2.

As @costinm [wrote](https://github.com/istio/istio/issues/5689#issuecomment-393032580) 
> For `istio-ingress` the old 7.1 docs apply.

**Comment by vadimeisenbergibm** [comment]
@andraxylia Ah, I see, you mean the instructions in the old 7.1 docs do not work with `istio-ingress` and v1, when applied to Istio 0.8. OK, let me handle this.

**Comment by hklai** [comment]
@vadimeisenbergibm does it require code change or is it about updating doc?

**Comment by vadimeisenbergibm** [comment]
@hklai I have to check it, let me do it until Monday.

**Comment by vadimeisenbergibm** [comment]
@andraxylia @hklai it works for me on IBM cloud. Could you please let me know the exact environment you experience the problems with?

```
$ cat <<EOF | kubectl create -f -
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: simple-ingress
>   annotations:
>     kubernetes.io/ingress.class: istio
> spec:
>   rules:
>   - http:
>       paths:
>       - path: /status/.*
>         backend:
>           serviceName: httpbin
>           servicePort: 8000
>       - path: /delay/.*
>         backend:
>           serviceName: httpbin
>           servicePort: 8000
> EOF
ingress "simple-ingress" created
$ kubectl get ingress simple-ingress -o wide
NAME             HOSTS     ADDRESS          PORTS     AGE
simple-ingress   *         169.XXX.XXX.XXX   80        11s
$ export INGRESS_HOST=169.XXX.XXX.XXX
$ curl -I http://$INGRESS_HOST/status/200
HTTP/1.1 200 OK
server: envoy
date: Mon, 04 Jun 2018 05:11:29 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 6
$ curl  http://$INGRESS_HOST/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
$ kubectl describe pod -l app=httpbin | grep "docker.io/istio/proxy"
    Image:         docker.io/istio/proxy_init:0.8.0
    Image:         docker.io/istio/proxy_init:0.8.0
    Image:         docker.io/istio/proxy:0.8.0
  Normal  Pulled                 5m    kubelet, 10.127.220.66  Container image "docker.io/istio/proxy_init:0.8.0" already present on machine
  Normal  Pulled                 5m    kubelet, 10.127.220.66  Container image "docker.io/istio/proxy_init:0.8.0" already present on machine
  Normal  Pulled                 5m    kubelet, 10.127.220.66  Container image "docker.io/istio/proxy:0.8.0" already present on machine
```

**Comment by vadimeisenbergibm** [comment]
Tested on minikube:
```
$ cat <<EOF | kubectl create -f -
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: simple-ingress
>   annotations:
>     kubernetes.io/ingress.class: istio
> spec:
>   rules:
>   - http:
>       paths:
>       - path: /status/.*
>         backend:
>           serviceName: httpbin
>           servicePort: 8000
>       - path: /delay/.*
>         backend:
>           serviceName: httpbin
>           servicePort: 8000
> EOF
ingress "simple-ingress" created
$ kubectl get ingress simple-ingress -o wide
NAME             HOSTS     ADDRESS   PORTS     AGE
simple-ingress   *                   80        10s
$ kubectl -n istio-system get po -l istio=ingress -o jsonpath='{.items[0].status.hostIP}'
192.168.99.100
$ kubectl -n istio-system get svc istio-ingress
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
istio-ingress   LoadBalancer   10.104.186.73   <pending>     80:32000/TCP,443:31825/TCP   4m
$ export INGRESS_HOST=192.168.99.100:32000
$ curl -I http://$INGRESS_HOST/status/200
HTTP/1.1 200 OK
server: envoy
date: Mon, 04 Jun 2018 07:24:54 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 8

$ curl http://$INGRESS_HOST/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
$ kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     <none>    10d       v1.9.0
$ kubectl describe pod -l app=httpbin | grep "docker.io/istio/proxy"
    Image:         docker.io/istio/proxy_init:0.8.0
    Image:         docker.io/istio/proxy_init:0.8.0
    Image:         docker.io/istio/proxy:0.8.0
  Normal  Pulling                7m    kubelet, minikube  pulling image "docker.io/istio/proxy_init:0.8.0"
  Normal  Pulled                 6m    kubelet, minikube  Successfully pulled image "docker.io/istio/proxy_init:0.8.0"
  Normal  Pulled                 6m    kubelet, minikube  Container image "docker.io/istio/proxy_init:0.8.0" already present on machine
  Normal  Pulled                 5m    kubelet, minikube  Container image "docker.io/istio/proxy:0.8.0" already present on machine
```

**Comment by andraxylia** [comment]
If it works for you I must have been doing something wrong. I will close it now.
