### ISSUE TITLE
Grafana add-on on fresh Bookinfo install has no data to visualize

### ISSUE THREAD

**Issue by Tahler** [istio/istio#5691]
Helm-installed Istio on GKE, applied Bookinfo, then followed instructions in https://preliminary.istio.io/docs/tasks/telemetry/using-istio-dashboard.html.

I get the following result:

![image](https://user-images.githubusercontent.com/10715719/40208961-74dc5b32-59f1-11e8-9eaf-415dd5d73b9a.png)

Perhaps I also need to add prometheus, but the documentation doesn't explicitly require prometheus and it seems to be included in the grafana image.

**Comment by douglas-reid** [comment]
Yes. This seems like an issue with prometheus not being installed.

@mandarjog the `istio.yaml` packaged with the release includes prometheus. Should we update the helm instructions to include the prom enablement?

**Comment by Tahler** [comment]
Discussed in istio/istio.github.io#1315.
