### ISSUE TITLE
Improve INSTALL.md to help new users

### ISSUE THREAD

**Issue by esnible** [istio/istio#57]
This issue is multi-part.

I found the optional step to create the "Kubernetes namespace" hard to understand so I skipped it.  I would prefer my Istio components to be in istio-system instead of default but was afraid to try because 1) I have been running Istio in default for weeks and don't know the effects running it elsewhere will have and 2) Frank's bookinfo included instructions for starting it in default and I asked him about that and didn't understand why he wanted it there.

The second problem is the optional add-ons.  I would *love* to see Grafana and the control panel.  I have not been able to get anyone to show them to me.  However when I run the instructions the services don't come fully up.  They stay in "pending" state.  I suspect this is because I am on Minikube.  An alternate path for Minikube users would be very helpful.

**Comment by frankbu** [comment]
Regarding the namespace being used for the demos. The yaml file I've been using for manager in the bookinfo demo passes "default" as an argument when starting manager: https://github.com/istio/istio/blob/master/demos/istio/manager-discovery.yaml#L30. @kyessenov said that without this manager will process all namespaces, which adds a lot of processing noise. I'm not sure if that means it's also a performance issue, but I had the feeling that we do want to restrict things to a particular namespace (maybe "demo" if not "default"). @andraxylia's version of the yaml file does not currently pass this argument, so it will work with any namespace.

**Comment by kyessenov** [comment]
There is a typo in the YAML, it should be `"-n", "default"`. It should also include mixer address flag `"-m"` if you are using mixer. I would recommend restricting manager service to a single namespace for now or at least give it more replicas. It lacks caching, so it's pretty heavy on CPU. This is an easily solvable problem, so if you really want per-cluster manager service, that can be done.

**Comment by geeknoid** [comment]
How are we doing here? Are all the recent updates in this space sufficient to close this issue?

**Comment by andraxylia** [comment]
Latest updates are sufficient, we can close this issue.
