### ISSUE TITLE
Improve ingress certificate distribution

### ISSUE THREAD

**Issue by costinm** [istio/istio#570]
In 0.1, ingress certs are distributed by pilot over http. 
We need https and authenticaiton.

Alternatively, we should use the same mechanism used for the service-to-service certs - 
we shouldn't have 2 different ways to distribute certs.

**Comment by sakshigoel12** [comment]
costinm@ are the owner for this? Please update assignees

**Comment by wattli** [comment]
@myidpt , could you investigate on this please? Thanks

**Comment by myidpt** [comment]
This is tracked by https://github.com/istio/pilot/issues/1134

**Comment by wattli** [comment]
Dedup, refer to istio/pilot#1134
