### ISSUE TITLE
There is no tab between NAME and KIND

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#5704]
From the output, we can see that the output of istioctl does not include a tab between NAME and KIND, this caused the output difficult to read.

```
root@gyliu-icp-6:~/cases/istio-release-0.8-20180518-01-13# istioctl get gateways
NAME		KIND					NAMESPACE
bookinfo-gatewayGateway.networking.istio.io.v1alpha3	default
```
```
root@gyliu-icp-6:~/cases/istio-release-0.8-20180518-01-13# istioctl get virtualservices
NAME	KIND						NAMESPACE
bookinfoVirtualService.networking.istio.io.v1alpha3	default
```

/cc @morvencao

**Comment by morvencao** [comment]
Suggest to align with kubernetes printer format:
https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/tabwriter.go#L24-L30

**Comment by esnible** [comment]
Doesn't PR https://github.com/istio/istio/pull/5706 also fix this?

**Comment by gyliu513** [comment]
@esnible , we create another PR #5707 based on 0.8 branch and #5706 is based on master.

**Comment by linsun** [comment]
No need to create one for master.  @hklai will merge all 0.8 changes to master.

**Comment by gyliu513** [comment]
I think we need to keep this issue open until #5707 got merged? @linsun

**Comment by linsun** [comment]
Up to you if you want to baby sit to close it :). I trust Andy as he has been merging changes from 0.8 to master.
