### ISSUE TITLE
need to be able to generate v1 istio-auth.yaml similar/compatible with 0.7.1

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#5720]
Looks like we recently renamed istio-auth.yaml to istio-demo-auth.yaml and that file contains v2 proxy settings (#5653 which is fine if we want people starting from scratch to get a clear message it's not the same as before)

But we also need to have easy/clear way to regenerate the same file as in 0.7.1 for people not ready to convert to v1alpha3 and yet wanting to upgrade to 0.8

ps: this also broke the daily perf tests so while I will write a v2 script/set of rules, I do need to check that v1 still works - cc @rkpagadala

**Comment by ldemailly** [comment]
maybe just a doc issue, but what is the gendeploy equivalent of:

```
helm template  --set global.proxy.image=proxy \
		  --values install/kubernetes/helm/istio/values-istio-auth.yaml \
		  install/kubernetes/helm/istio >> install/kubernetes/istio-auth.yaml
```
which if I understand correctly would be what is needed? (cc @mandarjog , @rkpagadala )

**Comment by costinm** [comment]
Yes, that is the command - but the generated file should not be in the
release, to avoid confusion.

**Comment by linsun** [comment]
@ldemailly @costinm I agree this is just a doc issue in the https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio.html page, agree?

**Comment by ldemailly** [comment]
how do I generate with `istioctl gendeploy` ? (ie without requiring helm to be installed, install with only kubectl and what is in the release tar ball)

**Comment by jasmine-jaksic** [comment]
Did either of you fix the doc? Can this issue be closed?

**Comment by ldemailly** [comment]
replied in the other task that no afaik the doc to use gendeploy isn't on https://istio.io/docs/setup/kubernetes/upgrading-istio/ (is it elsewhere I missed?)

**Comment by costinm** [comment]
WAI.

**Comment by ldemailly** [comment]
what is “WAI”?
afaik it’s still not documented- I ended up using helm template but istioctl gendeploy should be documented
