### ISSUE TITLE
Bookinfo app add mysql db access to ratings service

### ISSUE THREAD

**Issue by saumoh** [istio/istio#573]
It was decided in https://github.com/istio/istio/pull/473, that we'd first add mysql db access to the ratings service in the bookinfo app.
Opening this issue to track this requirement.

**Comment by ldemailly** [comment]
we do want to add mysql as a rawvm demo soon but otherwise I suppose this is for 0.3 ?

**Comment by rshriram** [comment]
For 0.1.
MySQL is in cluster tcp service in this example. We also want to pivot the
same example to a egress service (e.g. hosted MySQL in cloud or on prem,
outside istio). We have had support since 0.1 but didn't create examples.

-- 

~shriram
