### ISSUE TITLE
Issues when running pilot+ingress only

### ISSUE THREAD

**Issue by ymesika** [istio/istio#5731]
Trying to cover a scenario when user would only want to use Istio's ingress features by installing only relevant components. A guide is [planned](https://github.com/istio/istio.github.io/issues/1294) to be written.

Following is a summary of the issues encountered so far:

#### Citadel Always Included
When disabling all components but `ingress`, `ingressgateway` and `pilot` the following 4 pods are being installed:
```sh
NAME                                    READY     STATUS    RESTARTS   AGE
istio-citadel-64c9df88bc-wm5sw          1/1       Running   0          3m
istio-ingress-5d6896cdb5-l4nwf          1/1       Running   0          3m
istio-ingressgateway-7595bdb4bf-t8g55   1/1       Running   0          3m
istio-pilot-7ff65fbb95-d2wfg            2/2       Running   0          3m
```

`istio-citadel` is being installed because there is no toggle flag to disable its creation by helm. 
PR #5675 is intended to allow this toggling.

#### Proxy Crash
Both `ingress` and `ingressgateway` fail to start with an error:
```sh
[2018-05-21 07:32:02.226][47][critical][main] external/envoy/source/server/server.cc:75] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-statsd-prom-bridge
```

The reason is that the proxy is being provided with an arg `--statsdUdpAddress=istio-statsd-prom-bridge:9125`.
Removing this argument will keep proxy running.

Possible solutions:
* Modify proxy to avoid crash
* Update helm template to add the argument only if mixer is enabled. This is a little tricky because ingress chart can't access `enabled` flag of the mixer chart
* Ask the users to remove those args in the generated YAML

/cc @linsun @mandarjog @rshriram

**Comment by linsun** [comment]
Is it possible to run proxy with statsdUdpAddress being the optional arg?   This used to work in v0.2.

cc @costinm @GregHanson @ijsnellf

**Comment by costinm** [comment]
Yes, we should make the statsdUdpAddress dependent on telemetry.enabled

Or even better - stop using it completely, envoy now supports prometheus metrics directly, so we could just configure prom to pull from envoys.

**Comment by costinm** [comment]
Doug - opinions ? I would vote for removing the statsd if setting up prom is not too hard.

**Comment by douglas-reid** [comment]
We don't have a good way to consume proxy metrics with Prometheus yet. We'd have to figure out access and the config for all scenarios, including mTLS-enabled. And we need a way to keep these requests from being traced, etc.

I think that `telemetry.enabled` seems too coarse. When `statsd-prom-bridge` was split out from mixer, things got a bit wonky here. Ideally, there would be a `envoy.statsd.telemetry.enabled` or something that speaks directly to generating and having the `statsd-prom-bridge` service available.

**Comment by ymesika** [comment]
One more option is to move the `statsd-prom-bridge` Service/Deployment generation template from Mixer chart to Pilot's. Having `statsd-prom-bridge` without Mixer generates a

```[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:Cluster not available```

but Envoy is not crashing as it was without both Mixer and statsd-prom-bridge.

My assumption here is that Mixer can't live without Pilot while the opposite is possible (the topic of this issue).

Any objections to that?

/cc @mandarjog

**Comment by sdake** [comment]
cc @sdake

**Comment by sdake** [comment]
It is very common for folks to want to turn off metrics for high throughput workloads.  Is it acceptable to backport the solution to this problem to the 0.8 branch (targeting 0.8.1)?

**Comment by douglas-reid** [comment]
@ymesika I think we've confused a couple of things. The `statsd-prom-bridge` is completely independent of Mixer. Those Mixer report errors you are seeing are related to a different issue (likely having `disable_report_calls` set to `false`, but not having a `mixer_report_server` cluster).

Mixer can live without Pilot. It has no dependencies on Pilot.

@sdake are you suggesting a targeted (per-workload) enablement of envoy (and perhaps Mixer) telemetry collection?

**Comment by andraxylia** [comment]
Is this not already supported via the helm template or istioctl gen-deploy? If nothing is pending, can you please close this issue?

**Comment by ymesika** [comment]
My last PR support this was merged yesterday.
