### ISSUE TITLE
Feature: Istioctl should be able to retrieve the sync status of each proxy

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#5732]
As discussed with @rshriram a `proxy-status` command will be created that provides this information.

It should contain version sent and version ack'd for xDS for each pod.

**Comment by esnible** [comment]
@liamawhite Can you give a proposal for what the output should look like?

**Comment by liamawhite** [comment]
| Pod   | EDS Sent | EDS Acked | CDS Sent | CDS Acked | LDS Sent | LDS Acked |
|-------|----------|-----------|----------|-----------|----------|-----------|
| pod-1 | nonce    | nonce     | nonce    | nonce     | nonce    | nonce     |
| pod-2 | nonce    | nonce     | nonce    | nonce     | nonce    | nonce     |
| pod-3 | nonce    | nonce     | nonce    | nonce     | nonce    | nonce     |

look about right @rshriram ?

**Comment by liamawhite** [comment]
completed with https://github.com/istio/istio/pull/6373
