### ISSUE TITLE
Zipkin isn't included in manifest yaml file for daily build package

### ISSUE THREAD

**Issue by morvencao** [istio/istio#5747]
**env:**
```
ubuntu: 16.04
istio version: istio-release-0.8-20180521-15-16(daily build)
kubenetes version: v1.10.0
```

**issue**
Daily build package doesn't include `zipkin` neither in `istio-demo*.yaml`, nor in `addons` directory. While other addons(prometheus, grafana and servicegraph) are.
```
# grep zipkin istio-release-0.8-20180521-15-16/install/kubernetes/istio-demo-auth.yaml
        - --zipkinAddress
      zipkinAddress: zipkin.istio-system:9411
          - --zipkinAddress
          - zipkin:9411
          - --zipkinAddress
          - zipkin:9411
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans

# grep zipkin istio-release-0.8-20180521-15-16/install/kubernetes/istio-demo.yaml
        - --zipkinAddress
      zipkinAddress: zipkin.istio-system:9411
          - --zipkinAddress
          - zipkin:9411
          - --zipkinAddress
          - zipkin:9411
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
          - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
# ls -l istio-release-0.8-20180521-15-16/install/kubernetes/addons/
total 4
-rw-r--r-- 1 root root 1153 May 21 15:21 grafana.yaml
```

**Comment by morvencao** [comment]
@gyliu513 Seems that release-0.8 has replace `zipkin` with `jaeger`
See: https://github.com/istio/istio/commit/6dbbacac0b478017179480778637c9d8d781ac25#diff-b6a1565b257517e23073e89749791828

**Comment by gyliu513** [comment]
@linsun @sdake so for 0.8 and future release, istio will not have zipkin anymore?

**Comment by sdake** [comment]
I don't know the answer @gyliu513 to whether zipkin is in or out.  I saw a review fly by to change tracing to standardize on Jaeger, however, I believe the goal was to provide an implementation of for both (with possibly others in the future).

Cheers
-steve

**Comment by linsun** [comment]
for 0.8, It will be changed back to zipkin due to memory leak issue from jaeger.

**Comment by morvencao** [comment]
Revert switch to jaeger: https://github.com/istio/istio/pull/5795
