### ISSUE TITLE
No trace collected for selector-less service and endpoints on a mesh expansion machine

### ISSUE THREAD

**Issue by morvencao** [istio/istio#5752]
**env:**
```
ubuntu: 16.04
istio version: istio-release-0.8-20180521-15-16(daily build)
kubenetes version: v1.10.0
```

**Scenario**
I have followed the Istio mesh Expansion [doc](https://istio.io/docs/setup/kubernetes/mesh-expansion/) and deploy the bookinfo application as follows:
![image](https://user-images.githubusercontent.com/5468682/50805622-40e9d380-132e-11e9-8c7c-7f980ab556b1.png)

Run `details` and `mysqlDB` on VM outside of k8s cluster and register `details` & `mysqldb` services with `istioctl`.

It turns out bookinfo application works fine in my env, except that zipkin can't collect any trace for `details` and `mysqldb` services.
Haven't tried if metrics and logs for `details` and `mysqldb` services will be collected by prometheus or not.

So have I missed somethings as I followed the latest doc? Or this feature is not support for the latest version?

/cc @gyliu513

**Comment by morvencao** [comment]
@gyliu513 `Jarger` also can't collect traces for `details` and `mysqldb` services.

**Comment by utkuturunc** [comment]
I am having a similar issue. Jaeger only picks up traces from the ingress gateway but I don't see any traces that contain the names of any microservices.

**Comment by rokii** [comment]
same issue for my env with istio0.7.1
@morvencao  how do you get the daily build?

**Comment by morvencao** [comment]
@rokii https://github.com/istio/istio/wiki/Daily%20Builds

**Comment by utkuturunc** [comment]
By the way there is no choice of istio-proxy in zipkin or jaeger.

**Comment by rokii** [comment]
Is this fixed ?

**Comment by morvencao** [comment]
The issue should still exists in the latest version. 
Let's reopen this.

**Comment by linsun** [comment]
If you use service entry to connect to the remote details and mysqlDB on VM, would you at least get the client side metrics for these 2 services?  I am not sure if we'd advocate mesh expansion over service entries??

**Comment by morvencao** [comment]
@linsun Seems that the `zipkin` address parameter is not passed to envoy on VM in this case, have raised a [PR](https://github.com/istio/istio/pull/10797) to fix this, still working on it.
