### ISSUE TITLE
CI should keep mac builds working

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#576]
Mac build regularly breaks, it'd be good to keep it working by testing it continuously

it's very important/useful for community adoption and dev productivity

**Comment by sebastienvas** [comment]
Why P0 ? until Apple provides a VM to deal with this there is no way to do this on GCP. According the @rshriram Travis might be able to do this.

Also please define mac build. If bazel build are failing, please file a bug in bazel, for the rest, we need to list all the script that user need to run.

**Comment by ldemailly** [comment]
I think it's P0 for community support to be able to develop istio on a mac 

And it's maybe dependant on a build that doesn't involve many steps (re defining "mac build")

@thisisnotapril can you run a survey for the community to confirm my impression that mac is a primary dev environment we should support ?

**Comment by mandarjog** [comment]
+1

**Comment by sebastienvas** [comment]
Why don't we consider this one for Q4.

**Comment by ldemailly** [comment]
it's pretty clear the majority of istio contributors have a mac and having a pretty poor experience

**Comment by hklai** [comment]
Well AFAICT mac build is fairly stable for the past few months.

**Comment by ldemailly** [comment]
you don’t think it’s important to have it in CI?

**Comment by hklai** [comment]
I don't think it is feasible as both circle and prow do not and cannot run mac builds and tests.

**Comment by kyessenov** [comment]
There is a circle Mac job on istio/proxy I believe.

**Comment by hklai** [comment]
Thanks. I see. 
Example: https://circleci.com/gh/istio/proxy/2286

**Comment by ldemailly** [comment]
...

**Comment by loewenstein** [comment]
What about this? I recall @holgero and myself fixing a lot of issues on Mac that we had. Would be nice to not have them reoccurring just because CI doesn't check it.

**Comment by ldemailly** [comment]
I don't know, you should ask @hklai or @louiscryan

**Comment by esnible** [comment]
https://github.com/istio/istio/issues/10725 is an example of an issue caused by the inability to test Mac istioctl builds.

**Comment by howardjohn** [comment]
This has been around for 2 years. It seems useful, but unless someone is willing to invest some effort into this it doesn't seem like this will get done
