### ISSUE TITLE
High Availability for Ingress / Gateway

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#5761]
Similar to https://github.com/istio/istio/issues/2224, Ingress/Gateway need to be autoscaled.

If the service using Istio is autoscaled, there usually no way for the service owner to know before hand how much traffic they will be handling.  

Autoscaling will be much beneficial in such cases.

**Comment by rshriram** [comment]
The istio-demo.yaml shows autoscaling config for both ingress/egress gateways (as of 0.8)
