### ISSUE TITLE
Istio 0.8 Egress renaming

### ISSUE THREAD

**Issue by jsenon** [istio/istio#5764]
I think that external service was rename serviceentry, Does "Entry" is  something relevant for communication outside the cluster?

https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#ServiceEntry

**Comment by vadimeisenbergibm** [comment]
@jsenon I use the term "Mesh-External Service Entry". It is a ServiceEntry, with `location` `MESH_EXTERNAL`. So it is an additional service, or an entry in the Service Registry, that refers to a service external to the mesh.

Is this term more clear? Does it explain the intention?
