### ISSUE TITLE
e2e failed at create namespace error

### ISSUE THREAD

**Issue by linsun** [istio/istio#578]
I've hit this multiple times... it seems we are requesting the namespace to be deleted, then we immediate create the namespace which would fail.

I0818 17:41:03.719739    3516 mixer_test.go:172] Cleaning up mixer proxy
I0818 17:41:03.719814    3516 istioctl.go:89] Cleaning up istioctl
I0818 17:41:03.719821    3516 kubernetes.go:137] Cleaning up kubeInfo
I0818 17:41:03.719836    3516 commonUtils.go:53] Running command kubectl delete namespace lin111
I0818 17:41:03.958440    3516 kubernetes.go:145] Namespace lin111 deleted
I0818 17:41:03.958500    3516 framework.go:166] Cleanup complete
....

INFO: Running command line: bazel-bin/tests/e2e/tests/bookinfo/go_default_test -alsologtostderr -test.v -v 2 --namespace lin111 --istioctl /home/jenkins/istio/istioctl --use_local_cluster true --namespace lin111 --istioctl /home/jenkins/istio/istioctl --use_local_cluster true --rbac_path install/kubernetes/istio-rbac-beta.yaml
I0818 17:41:07.175768    4032 framework.go:72] Logging initialized
I0818 17:41:07.176297    4032 testInfo.go:113] Using log dir /tmp/istio.e2e.895142206
I0818 17:41:07.177221    4032 framework.go:137] Starting Initialization
I0818 17:41:07.177242    4032 kubernetes.go:100] Setting up kubeInfo
I0818 17:41:07.177332    4032 commonUtils.go:53] Running command kubectl create namespace lin111
E0818 17:41:07.359333    4032 kubernetes.go:107] Failed to create namespace.
E0818 17:41:07.359822    4032 framework.go:199] Failed to complete Init. Error command failed: "Error from server (AlreadyExists): object is being deleted: namespaces \"lin111\" already exists\n" exit status 1

**Comment by yutongz** [comment]
I think it's normal since when you delete a namespace, kubernetes needs time to clean up everything resource under this namespace. Since in tests we create many resource e.g. ingress, deployment, it needs some time to actually release this namespace for future use.

**Comment by linsun** [comment]
right, the kubectl req is async request and it would return as soon as it is receiving the req.  I'm putting some change to ensure namespace is removed before we continue else my e2e test just failed.   Curious why you didn't hit this @yutongz?

**Comment by yutongz** [comment]
We are using random namespace for each tests, so no need to worry about that.

**Comment by linsun** [comment]
can you show me how you invoke the e2e with random namespace?

**Comment by yutongz** [comment]
https://github.com/istio/istio/blob/172957a43f150ef3fd6c4b69493759f0ed15a5da/tests/e2e/framework/kubernetes.go#L77

If you don't specify a namespace, framework will use runID which is a UUID.

**Comment by yutongz** [comment]
That's why I am wondering why we want to use a specific namespace.

**Comment by linsun** [comment]
ah i see.  yea, our script was specifying a namespace, which is a valid flag you support. :)

**Comment by linsun** [comment]
it helps to search and clean up too when you pre-specify the namespace if tests failed in the middle.

**Comment by ldemailly** [comment]
I assume #594 closes this (tip: use "Fixes #578" instead of "PR for #578" to auto close the issue on merge)

**Comment by linsun** [comment]
Yes, thank you for the tip! :)
