### ISSUE TITLE
What ingress controller can be used for istio-ingress ?

### ISSUE THREAD

**Issue by goodforever** [istio/istio#5781]
Does  the istio-ingress include ingress controller ? if no , What ingress controller can be used for istio-ingress ?

**Comment by goodforever** [comment]
Nobody answer my simple question, I look for  other service mesh, I found a good service mesh ,Conduit.  but I still want to  confim my question, finally,  I found  that "minikube addons enable ingress" can open ingress-nginx.  share it with beginner

**Comment by nrjpoddar** [comment]
AFAIK istio-ingress is very tied to the istio control plane. You can install istio control plane i.e. istio-pilot, istio-mixer, istio-citadel and istio-ingress without the sidecar injector. This will ensure you have a functioning ingress but no sidecars are injected in any Pods. Is that what you're looking for?

**Comment by idouba** [comment]
Actually istio-ingress is a pod with ONE istio/proxy container which do the request routing just like other proxies within mesh. The ingress controller you mentioned is in pilot, that is pilot watch the Ingress api server, and convert the rule to istio specified rules which will be consumed by the proxies above.
The details can be find here:  
[https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/ingress/controller.go#L62](https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/ingress/controller.go#L62)

**Comment by nrjpoddar** [comment]
@idouba do you have a working configuration of istio-ingress with just istio-pilot i.e. no istio-mixer and istio-citadel?

If you have `mTLS` disabled, `mixerCheckServer` and `mixerReportServer` commented out in `istio` config map you should be able to run istio-pilot as ingress controller (without the rest of Istio control plane) for istio-ingress. Is that correct?

**Comment by idouba** [comment]
@nrjpoddar  I am using pilot as well as mixer.

**Comment by jasmine-jaksic** [comment]
Please use istio-users@googlegroups.com or https://istio.rocket.chat if you have additional questions.
