### ISSUE TITLE
Refactor pilot bootstrap code (take 2)

### ISSUE THREAD

**Issue by nmittler** [istio/istio#5783]
The pilot bootstrap logic has gained a bit of cruft over the past several months and it's getting to the point where another facelift is in order.

In comparison, the mixer startup code is much more extensible and better separates the configuration from the server startup. We should do something similar in Pilot.

The initial motivation for this issue is for writing the setup code for a local pilot for the new test framework.

**Comment by costinm** [comment]
Post 1.0

**Comment by nmittler** [comment]
Some parts of this work can't wait for 1.0.  We'll need a new sort of service registry that we can altered manually as to test runs. This implies that the structure of the bootstrap code has to change to be more pluggable.  This will be a reasonably significant change that will have to occur soon ... certainly before 1.0.

**Comment by nmittler** [comment]
Abandoning this issue for now. I suspect some of this refactoring will happen organically over time. I don't think we need an issue for it at this point.
