### ISSUE TITLE
node_agent_k8s fails to save key/cert to file system 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#5799]
Repro steps - 
Follow [instruction](https://github.com/istio/istio/blob/master/security/cmd/node_agent_k8s/README.md), using latest node_agent_k8s image rather than gcr.io/istio-testing/nodeagent:latest, after adding new workload, see below errror logs in node_agent_k8s container 

_failed to save key cert for ns = default, service account = default, uid = cb0557b1-5ee6-11e8-9032-42010a8000fb error failed to create directory for default, err mkdir /etc/certs/workload/default: no such file or directory_

I tried to fix above error by creating /etc/certs/workload/ first, then hit error
_failed to save key cert for ns = default, service account = default, uid = e14d33fa-5ee9-11e8-b6bc-42010a8000fd error failed to create directory "/etc/certs/workload", err mkdir /etc/certs/workload: read-only file system_

current default directory("/etc/certs/workload") for "secret-dir" is read-only, may need to use another directory to store workloads' key/cert pairs.

**Comment by wattli** [comment]
This readme is actually deprecated since we are not using flexvolume any more. I would not spend too much time on it.

**Comment by quanjielin** [comment]
Does it mean node agent will deprecate filesystem storage for key cert (only use memory forward) ? if yes, then probably we could ignore this; otherwise it needs to be fixed.

**Comment by quanjielin** [comment]
close this issue as the code is removed
