### ISSUE TITLE
e2e test for all the tasks

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#580]
During the 0.1 launch we decided we should at least have automated coverage for every task we describe on the website https://istio.io/docs/tasks/ so those stay working at all times

https://github.com/istio/istio/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22create%20e2e%20for%20Task%22%20is%3Aclosed%20

was the individual list. Some tests have been added since but it's unclear they all are

We should keep the tasks open until verified rather than mass close and hope it's ok

cc @sakshigoel12

**Comment by sakshigoel12** [comment]
Added all the Tasks currently on website. We should evaluate if there are new tasks for 0.2

**Comment by sakshigoel12** [comment]
reopen if there are missing tests

**Comment by ldemailly** [comment]
is there a tracking or replacement issue that will ensure those exist for/before 1.0 ?
