### ISSUE TITLE
bookinfo doesn't work on 1.10.2-gke.1

### ISSUE THREAD

**Issue by lizan** [istio/istio#5806]
kind of similar to #5723 

Followed docs:
- https://preliminary.istio.io/docs/setup/kubernetes/quick-start.html
- https://preliminary.istio.io/docs/guides/bookinfo.html

`curl -o /dev/null -s -w "%{http_code}\n" http://${GATEWAY_URL}/productpage` returns `504` (Gateway timeout) while on `1.9.7-gke.1` it returns `200` as expected.

**Comment by hklai** [comment]
is it the same issue as runconduit/conduit#982?

have you tried switching node-images to ubuntu?

**Comment by lizan** [comment]
Yes I think it is same issue, working on this.

**Comment by lizan** [comment]
[GKE 1.10.4-gke.0](https://cloud.google.com/kubernetes-engine/release-notes) is rolling out this week, and it contains the fix of this issue.
