### ISSUE TITLE
zipkin.yaml missing in 0.8

### ISSUE THREAD

**Issue by esnible** [istio/istio#5813]
The pre 0.8 daily builds no longer have _zipkin.yaml_ for deploying Zipkin.  _istio-release-0.8-20180523-09-15/install/kubernetes/addons_ only contains _grafana.yaml_.  Our docs at https://istio.io/docs/tasks/telemetry/distributed-tracing.html suggest _zipkin.yaml_ should be there.  Which is incorrect, the deployment artifact or the docs?

https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html says it generates _istio.yaml_. How is zipkin.yaml generated? And should the doc be updated to reflect that?

**Comment by gyliu513** [comment]
@esnible this seems duplicate with https://github.com/istio/istio/issues/5747 ?

**Comment by sdake** [comment]
@esnible yes, the docs need an update.  It is missing instructions on how to setup tracing.

From today on out, we have two workflows:
1. generate your own yaml with `istioctl gendeploy` or `helm template` and then `kubectl apply` it
2. use `helm install` to deploy the Istio chart

The Istio chart has zipkin support, but zipkin is not enabled by default.  Do you need instructions on zipkin generation?

**Comment by esnible** [comment]
With the latest changes, Zipkin now starts automatically for me when I bring up Istio with `helm template`.

**Comment by sdake** [comment]
Yes the docs are wrong.  We do intend to document the common scenarios for the --set options.  Working on a PR atm that autogenerates the table in the current helm install.

**Comment by esnible** [comment]
This issue is a duplicate of #5747
