### ISSUE TITLE
accessConfigFile only accepts /dev/null

### ISSUE THREAD

**Issue by sdake** [istio/istio#5816]
Within Istio, every sidecar is loaded with an accessConfigFIle of stdout (iiuc).  Changing accessConfigFIle to '/dev/null' still works, however, the calculation of the log messages for every proxy is still very expensive.  What would be ideal is a `nil` value specified in accessConfigaFile which shuts off all Envoy logging.  @mandarjog mentioned during community testing day this was not particularly easy to do.

Removing the accessConfigFile logging improves performance (even with /dev/null).  I expect performance would be much greater without any log creation at all (per HTTP access request).

Anyone more experienced with Envoy willing to take a crack at this prior to 1.0?

**Comment by sdake** [comment]
@kyessenov in the data path (envoy) - every connection to the sidecar or through the sidecars triggers a log message which creates a timestamp and formats a string.  This log creation in Envoy appears to be done via macros.

Could you expand on "logging is done outside the data path"?

**Comment by kyessenov** [comment]
It does not directly contribute to the perceived latency, except through consuming shared resources.

**Comment by sdake** [comment]
@kyessenov changing around accessConfigFile does contribute directly to TPS, which is typically 1k TPS per core without mixer.  If a VM has a limited number of cores, the TPS is limited.
