### ISSUE TITLE
Pilot to generate 'http_proxy' routes

### ISSUE THREAD

**Issue by costinm** [istio/istio#582]
Tested with a manual config: 

curl -v  -x localhost:15002 http://myservice.default.svc/

Config to generate should be a variant of:

Additional listener:
  {
      "address": "tcp://0.0.0.0:15002",
      "use_original_dst": true,
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "http_proxy",
            "filters": [
              {
                "type": "decoder",
                "name": "router",
                "config": {}
              } + (mixer config )
            ],
            "rds": {
              "cluster": "rds",
              "route_config_name": "http_proxy", 
// I used "80" to get the 80 routes, but we need to concat all the routes
              "refresh_delay_ms": 1000
            },
            "http1_settings": {
              "allow_absolute_url": true
            },
            "access_log": [
              {
                "path": "/dev/stdout"
              }
            ]
          }
        }
      ],
      "bind_to_port": true
    },

Additional route "http_proxy" - all http routes combined.

This also allow easier integration testing of pilot and proxy, on local dev machine ( no docker or k8s), using http_proxy for testing - no iptables needed.

**Comment by costinm** [comment]
Btw - for localhost testing, need to create a 'rawvm' dummy service, and an endpoint with the IP of the localhost.

**Comment by kyessenov** [comment]
Issue moved to [istio/pilot #1067](https://github.com/istio/pilot/issues/1067) via [**ZenHub**](https://www.zenhub.com/)
