### ISSUE TITLE
Kubernetes version compatability

### ISSUE THREAD

**Issue by Stono** [istio/istio#5830]
Hey, 
Do you publish a kubernetes version compatibility chart with Istio?

I ask because I've discovered on my cluster using 1.10.2+ nodes with istio 0.7.1 = pods unable to make any outbound communication.

Rolling back to 1.9.7 fixed this problem.

**Comment by lizan** [comment]
@Stono can you also record the kernel version? If you are on GKE, likely the kernel bug (see #5723 for detail) is related.

**Comment by Stono** [comment]
Hola!
I've rolled back now, but yes it was GKE and the symptoms were the same!

**Comment by lizan** [comment]
I'm working with GKE team to fix this issue, in a meanwhile, use 1.9.7 or use Ubuntu node image as a workaround.

**Comment by sakshigoel12** [comment]
@lizan is there a confirmed GKE version the fix will be rolled into yet?

**Comment by sakshigoel12** [comment]
We are expecting this issue to be resolved with GKE 1.10.4 release.

**Comment by Stono** [comment]
Sounds good, definitely think you should publish a compatibility matrix though of confirmed tested version :-)

**Comment by Stono** [comment]
Will do, it's out today but not in my region yet!  As soon as it's there
I'll test

**Comment by lizan** [comment]
Sure, no hurry. I already tested bookinfo in us-east1-d and it worked.

**Comment by Stono** [comment]
@lizan tested it on our two non-prod clusters today and all seems OK

**Comment by lizan** [comment]
Thanks for verifying!
