### ISSUE TITLE
How to manually deploy Istio envoy sidecar on a pod?

### ISSUE THREAD

**Issue by deepvish23** [istio/istio#5837]
Hi,

I am trying to install Istio envoy sidecar manually on my application and my .yaml file contains **'kind: Pod'**. I already read that this is not one of the supported types to inject an envoy sidecar but I just want to know if there is any workaround for this?

Any suggestions will help!

Thanks!
Deepthi

**Comment by ymesika** [comment]
If you have automatic sidecar injection set, the sidecar will be injected to the Pod upon creating it.
Or, you can also manually inject by editing your yaml. `istioctl kube-inject` currently doesn't inject into a Pod.

**Comment by deepvish23** [comment]
Thank you for the reply! Can you please elaborate on what exactly is it that I have to modify in my yaml file? Is there any particular syntax to follow so that a sidecar gets injected in the pod? 

Regarding automatic sidecar injection, I am running into the following error:

**ERROR: After approving csr istio-sidecar-injector.istio-system, the signed certificate did not appear on the resource. Giving up after 10 attempts.**

Please let me know if there is any work around to resolve this.

Many thanks!
Deepthi

**Comment by ymesika** [comment]
It's some kind of a hack and I've never tried it before but you can:
1. Create a new temporary yaml with a `Deployment`
2. Use `istioctl kube-inject` to "Istiofy" this yaml (add the necessary containers)
3. Take the extra stuff that was injected into yaml from step 1 and put it in your Pod's yaml

As I said, I haven't tried so it's just a rough guidelines.

**Comment by deepvish23** [comment]
I will try this and update in the thread! Thank you for the work around.

Is there any solution for the error I am facing for automatic sidecar injection? Any suggestion there will be a great help!

Thanks,
Deepthi

**Comment by ayj** [comment]
> Is there any solution for the error I am facing for automatic sidecar injection? Any suggestion there will be a great help!

Please verify that you've setup your k8s cluster with a running certificate controller / manager per the setup instructions (see [here](https://istio.io/docs/setup/kubernetes/quick-start/)). The automatic sidecar injection install procedure has been simplified in Istio 0.8 so you shouldn't need to run the extra bash scripts.

**Comment by dangtrinhnt-mmt** [comment]
I also have the same question as of today, 2019.
