### ISSUE TITLE
Restore TPROXY functionality 

### ISSUE THREAD

**Issue by ostromart** [istio/istio#5848]
TPROXY is broken due to https://github.com/istio/istio/issues/5745.
To restore tproxy in next release, we have some options (in rough order of complexity):
1. Bifurcate dockerfiles into regular/tproxy
2. Add prctl() syscall in envoy which will restore ability to core dump (there could be security objections to this).
3. Move the chgrp into pilot agent and set it there conditionally (based on tproxy support)
4. Figure out some way to make tproxy work without the chgrp.
5. ???

**Comment by costinm** [comment]
Done in 1.0
