### ISSUE TITLE
Readiness update timing results in envoy stuck with a TCP proxy

### ISSUE THREAD

**Issue by costinm** [istio/istio#5856]
Based on user test report resulting in envoy not getting http logs or mixer, but still forwarding requests to app, I suspect what happens is:

1. pod starts 
2. pilot generates a config - but doesn't see the endpoint yet, so it generates a 'management port' for the readiness
3. a bit later the endpoint shows up, and pilot generates the correct config - which is what we have in the adsz
4. envoy rejects the new listener on 9000 because it already has a listener, and it can't replace it 
since the name is different.
5. envoy is stuck with a tcp listener on 9000 ( the original one set for readiness ). Requests go to the app and we see 127.0.0.1 as remote address ( since it actually goes trough envoy ), but it's the TCP proxy for readiness, which has no mixer or logs.

One way to verify is to try to 'kill -9' the envoy - if after restart it gets the correct config we can confirm this theory. Another option to confirm this is to temporarily disable the readiness/liveness check. 

We'll work on a fix - from what I see in the code the scenario can happen, depending on apiserver event timing, and would result in this behavior.

For people not using mtls - we can disable the management port completely, since it doesn't provide anything,  it is already replaced when the endpoint shows up. For mtls we need to wait for the transparent mode or a better readiness solution.

**Comment by kyessenov** [comment]
Yeah, I pointed it out that listener names should not include the protocol.
The fix was merged by Shriram.

**Comment by costinm** [comment]
When was it merged ? 

Looking at the code, if there is a listener already we skip the 'management' port anyways. And since we no longer capture ports not listened in containerPort - the other uses for management proxy are also gone. 

Only case where a tcp proxy for readiness is still needed is if the user has a containerPort declaring the 
readiness port, and doesn't have any service pointing to the containerPort.

**Comment by costinm** [comment]
Seems to be working now - name of listener is IP_portnumber
