### ISSUE TITLE
404 error when trying to route istio-annotation ingress host.

### ISSUE THREAD

**Issue by LELEFIVE** [istio/istio#5880]
## Base Environment
**istio version**
~~~
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
~~~

**ingress.yml**
~~~
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gb-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: hello.gb.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: gb
          servicePort: 80
~~~
## Problems
Outside k8s, I config the 
~~~
172.20.36.235 hello.gb.cn
~~~
 into the Windows hosts file. When  browsing the url 
~~~
http://hello.gb.cn/
~~~
, I got the error 
~~~
404 page not found
~~~
I haved tried  changing the annotation to taefik and deleting the annotation, both methods worked fine and return the right respone message. Is this a istio's bug or something? Please help me , thank you.

**Comment by LELEFIVE** [comment]
Anyone here?

**Comment by andraxylia** [comment]
Can you please try with istio release 0.8 and Gateway configs like here?
https://istio.io/docs/tasks/traffic-management/ingress/
