### ISSUE TITLE
Prometheus and Zipkin data incomplete if >1 K8s Service refers to a pod

### ISSUE THREAD

**Issue by esnible** [istio/istio#5885]
I am testing with six microservices.  The communication between some microservice pairs is not making it to Prometheus.  I am querying Prometheus manually using

```
istio_request_count{destination_service!="istio-telemetry.istio-system.svc.cluster.local", destination_service!="istio-pilot.istio-system.svc.cluster.local",destination_service!="istio-policy.istio-system.svc.cluster.local",source_service!="unknown"}
```

After a while, the microservices that are not reporting failures changes.  However, at no time do all the microservices supply correct telemetry that makes it to Prometheus.

The data reported by Pilot Discovery on istio-pilot.istio-system:15007/debug/adsz shows many duplicates of my Service Node id, with different -nnnnn suffixes.

**Comment by esnible** [comment]
This seems to happen when more than one K8s Service points to the pod.

It seems to be related to destination.service:

```
curl istio-pilot.istio-system:15007/v1/listeners/node5/sidecar~172.30.150.243~node5-v1-7c4794c47b-88pdx.default~default.svc.cluster.local
```

will show two mixer decode filter config.v2.serviceConfigs; one called `node5-v1-np.default.svc.cluster.local` and one called `node5.default.svc.cluster.local` and each having its name as the `destination.service` value.

**Comment by esnible** [comment]
Verified that the destination.service is random because it is determined using the random _defaultDestinationService_:

```
$ kubectl exec node5-v1-7c4794c47b-88pdx -c istio-proxy -- curl istio-pilot.istio-system:15007/v1/listeners/node5/sidecar~172.30.150.243~node5-v1-7c4794c47b-88pdx.default~default.svc.cluster.local | grep defaultDestinationService
           "defaultDestinationService": "node5.default.svc.cluster.local",
...
$ kubectl delete pod istio-pilot-569fddb4d8-qbbht -n istio-system
pod "istio-pilot-569fddb4d8-qbbht" deleted
$ kubectl exec node5-v1-7c4794c47b-88pdx -c istio-proxy -- curl istio-pilot.istio-system:15007/v1/listeners/node5/sidecar~172.30.150.243~node5-v1-7c4794c47b-88pdx.default~default.svc.cluster.local | grep defaultDestinationService
           "defaultDestinationService": "node5-v1-np.default.svc.cluster.local",
...
```

**Comment by esnible** [comment]
I propose that Envoy sidecar should use the incoming _HOST_ header instead of defaultDestinationService when REPORTing to Mixer.  @mbanikazemi and I will look into this.

**Comment by esnible** [comment]
@kuat Additional problem.  Even if I delete the secondary K8s Service and restart Pilot the sidecars continue REPORTing using the now-deleted services.  I had to restart the Envoy process within the sidecar to get the reports to happen.

I am worried Service deletion isn't being pushed to sidecars.  (I can't figure out an easy way to verify this until `curl localhost:15000/config_dump` stops dumping core).

I am also worried that sidecars take a long time or never receive LDS updates if Pilot restarts due to a problem.

**Comment by kyessenov** [comment]
It could be that pilot generates an invalid configuration that gets
rejected by envoys. Envoy sticks to the last working configuration in this
case. You should be able to see rejection in sidecar logs ("fetch failed"
or some validation errors). Jason is working towards adding telemetry for
the internal state of pilot, so we can monitor how fast pilot gets/pushes
the config.

**Comment by esnible** [comment]
@kyessenov You were correct about "fetched failed".  

Every 20 seconds a sidecar reported

```
[warning][config] external/envoy/source/server/listener_manager_impl.cc:401] error adding listener: 'tcp_172.30.150.243_8080' has duplicate address '172.30.150.243:8080' as existing listener
[warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: Error adding/updating listener tcp_172.30.150.243_8080: error adding listener: 'tcp_172.30.150.243_8080' has duplicate address '172.30.150.243:8080' as existing listener
```

Eventually that Envoy segfaults, and when it restarts the fetch failures stop.

tcp_172.30.150.243_8080 refers to a pod at 172.30.150.243 and has two services pointing at it.

**Comment by kyessenov** [comment]
I'm pretty sure I fixed that naming conflict issue. Perhaps, trying out a more recent build should resolve this particular validation error.

**Comment by esnible** [comment]
I am stopping work on this because it seems likely Kuat's proposal will solve the problem.  If it doesn't we need to revisit this issue.

**Comment by kyessenov** [comment]
For HTTP: this has been solved by changing to report "unknown" service when there is ambiguity.
See https://github.com/istio/istio/pull/6122

Since most services we care about are HTTP, I think we can close this issue. I'll follow up with TCP issue.
