### ISSUE TITLE
Tool to run 'deep validation' for authN policy and related destination rule

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#5897]
We may want to provide a tool for customers to verify authN policy setup (mainly focus on mTLS, due to the complexity of having authN policy and destination rule that control server and clients independently).

The tool could be part of `istioctl`, or as a stand-alone script/binary.

1. Check for authentication policies *conflicts* (i.e if there are more than one policies with the same target scope).
1. Similar, check for destination rule *conflicts*. 
1. Check if mTLS is enabled for a service, but destination rule for that service doesn't use TLS (and vice-versa).

(Note: the first 2 items could be generic for all types of CRD-based config/policy)

**Comment by diemtvu** [comment]
Also relate: https://github.com/istio/istio/issues/4856

**Comment by yangminzhu** [comment]
cc @yangminzhu

**Comment by ayj** [comment]
Does this need to validate the running system or the source of truth (e.g. git)?

**Comment by diemtvu** [comment]
`istioctl authn tls-check` is a start. It still need few enhancement, e.g detect that there are more than one policies or rules at the same scope match to the host, or verify settings at endpoints.

To answer @ayj question, it could be both. The best, imo, is on the source of truth and prevent submit policy that might cause trouble. On the other hand, the tool above is checking the from system (pilot) as it's easier to implement.
