### ISSUE TITLE
install/perf report for release-0.8-20180526-09-15

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#5899]
@hklai istio 0.8 rc install and perf report

- https://github.com/istio/istio/blame/release-0.8/install/kubernetes/README.md#L9
mentions istio.yaml and istio-auth.yaml which do not exist anymore
- #5720 : the instructions on https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio/#control-plane-upgrade don't explain how to do it without helm (`istioctl gendeploy`)
- ran
```
helm template  --set global.proxy.image=proxy \
  --values install/kubernetes/helm/istio/values-istio-auth.yaml \
  install/kubernetes/helm/istio >> install/kubernetes/istio-auth.yaml
```

but then when installing it:
```
error: unable to recognize "STDIN": no matches for admissionregistration.k8s.io/, Kind=MutatingWebhookConfiguration
```

**Comment by ldemailly** [comment]
the error above is because webhook don't work for 1.8, so the command line need to be

```
helm template --set sidecarInjectorWebhook.enabled=false \
   --set global.proxy.image=proxy  \
   --values install/kubernetes/helm/istio/values-istio-auth.yaml \
   install/kubernetes/helm/istio > install/kubernetes/istio-auth.yaml
```
Note that it should be `>` not `>>` which appends and so will generate issues when ran more than once

**Comment by ldemailly** [comment]
turns out you now must add `-n istio-system` or your control plane ends up inside the default namespace

**Comment by ldemailly** [comment]
the old mixer seems to stay behind:
istio-mixer-6cff7ff5c-cq8ss                 3/3       Running   0          46m
```
$ kis get pods
NAME                                        READY     STATUS    RESTARTS   AGE
grafana-578d8b8dd8-2gbwq                    1/1       Running   0          31m
istio-citadel-776fdfcdc8-4j54w              1/1       Running   0          11m
istio-egressgateway-84975c774b-vlkw8        1/1       Running   0          11m
istio-ingress-6c5449bcc8-lnnpm              1/1       Running   0          11m
istio-ingressgateway-96bf454db-gnrsp        1/1       Running   0          11m
istio-mixer-6cff7ff5c-cq8ss                 3/3       Running   0          46m
istio-pilot-777cff45b8-msqzg                2/2       Running   0          11m
istio-policy-57fcb7df54-nw92m               2/2       Running   0          11m
istio-statsd-prom-bridge-6c96d54b7d-kw7bb   1/1       Running   0          15m
istio-telemetry-864697446b-zzw9h            2/2       Running   0          11m
prometheus-55d7945b68-l9hms                 1/1       Running   0          15m
```

**Comment by ldemailly** [comment]
after all this, I was able to run the (v1) tests and got similar latencies as 0.7 as expected

**Comment by ldemailly** [comment]
cc @rkpagadala

**Comment by ldemailly** [comment]
final (working) command is

```
helm template --namespace istio-system --set sidecarInjectorWebhook.enabled=false --set global.proxy.image=proxy   --values install/kubernetes/helm/istio/values-istio-auth.yaml   install/kubernetes/helm/istio > install/kubernetes/istio-auth.yaml
```

we still need the istioctl version

**Comment by rkpagadala** [comment]
I made the changes, but it still seems to fail
https://github.com/istio-releases/daily-release/pull/626/files

the failure logs are at  https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/626/daily-perf-tests/187/

**Comment by ldemailly** [comment]
it's because the generated yaml doesn't create the namespace anymore... another gotcha to document

**Comment by sdake** [comment]
cc @sdake

**Comment by jasmine-jaksic** [comment]
Did this get documented in FAQ or known issues in release notes?

**Comment by ldemailly** [comment]
> Did this get documented in FAQ or known issues in release notes?

not completely no (namespace needing creation for instance, or the incorrect use of `>>` are not on
https://istio.io/docs/setup/kubernetes/upgrading-istio/

**Comment by hklai** [comment]
please reopen if this is still a problem
