### ISSUE TITLE
Istio chart can't be installed multiple times 

### ISSUE THREAD

**Issue by morvencao** [istio/istio#5910]
Istio chart is much more stable, we still encounter cases that Istio chart can't be installed successfully, either for previous version of Istio chart  hasn't been cleanup completely, or there is another version of Istio chart installed. 
Root cause is that we have many hard coded object names in template fils. 

By the best practice of helm chart, we should support installing Istio chart multiple times, even in the same namespace, improving robustness and preventing cascading failures.

/cc @gyliu513 @linsun @sdake

**Comment by gyliu513** [comment]
I'm now thinking is it a valid case? I think for most of the user scenarios, we only need one istio running in a k8s cluster to manage all applications, I did not see some use cases which request running multiple istio in one k8s cluster.

**Comment by costinm** [comment]
Agreed, it gets too complicated. For upgrade we'll need something - but not the generic case, and targeted to control plane upgrade rollout.
