### ISSUE TITLE
Add coredump collection and scanning for segfaults to bin/dump_kubernetes.sh

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#5928]
`bin/dump_kubernetes.sh` should scan all `istio-proxy` logs for segmentation faults and core dumps. 

1. Records in the dump summary if any segfaults are observed.
2. copy coredumps which are in /etc/istio/proxy/core.***

@ostromart can you add a link to an istio-proxy log that produced a core dump and authoritative location of the core files.

**Comment by ostromart** [comment]
See https://github.com/istio/istio/issues/5694
The crashlogs are definitely in /etc/istio/proxy/core.*** in 0.8 but we'd like to change that to /var/istio/core.*** shortly.

**Comment by hklai** [comment]
@mandarjog @ostromart this does not belong to Test and Release.
Please reassign accordingly.

**Comment by Tahler** [comment]
This is arguably related to test and release because we wanted e2e tests to fail if there were any core dumps.

However, this issue should be resolved by the recently merged #5984.

**Comment by kyessenov** [comment]
We need a test that core dumps are generated, because they are not.
