### ISSUE TITLE
dev / test setup script (compile and install head of everything)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#593]
Right now the closest we have to a way to test/setup using current master is something like

run proxy docker build, copy the sha in 3 places in pilot and then in pilot:

bazel run //test/integration -- --logtostderr -tag mydevtag -n e2e -auth enable

+ ctrl-c after the first reachability test passes

we need a script that does compile the latest of everything and installs it in a cluster/namespace

**Comment by andraxylia** [comment]
Is this about the pilot test/integration? We already have a script that does everything, bin/e2e.sh.

I also recommend trying the go build test/integration , it's easier if you just want to run the integration.

**Comment by ldemailly** [comment]
it's better than nothing (which is why I documented it in the comment) but it doesn't exactly "does everything" no:

- [ ] it doesn't get the latest proxy (you have to manually edit 3 files)
- [ ] it doesn't get the latest mixer
- [ ] you have to ctrl-c in the middle
- [ ] you have to create the namespace
- [ ] you have to know about -auth
- [ ] it doesn't really give you a working istioctl (have to pass -tag etc later)

**Comment by ldemailly** [comment]
this may be "make test" or similar soon - we haven't yet quite recovered the instructions and commands on how to run 1 e2e test like we had sort of at the end of 0.2

**Comment by sakshigoel12** [comment]
@andy can you assign this issue if we still think it is a P0

**Comment by ldemailly** [comment]
this is pretty much the charter of the testing swat team

**Comment by andy** [comment]
@sakshigoel12 sorry, but I’m not the right person

**Comment by ldemailly** [comment]
cc right andy: @hklai

**Comment by hklai** [comment]
This is part of https://github.com/istio/istio/issues/4536. 

The workflow will be something like
1. scripts to set up local test env
2. make docker
3, make e2e-foobar
