### ISSUE TITLE
Add telemetry to sidecar injector service

### ISSUE THREAD

**Issue by costinm** [istio/istio#5946]
On a long running cluster I noticed that auto-injection stopped after some time, and 
some pods were not injected.

We need to add a /metrics page that can be queried by prometheus with stats about rejected/accepted
injections, and details to allow an SRE to identify problems. In particular - I've seen some logs suggesting
the TLS connection was rejected, which might be caused by a bug in cert rotation handling. Unfortunately
I didn't capture the log - but having metrics may allow us to identify this kind of behavior in future.

We also need to add the /ctrlz to allow logging to be adjusted at runtime and possibly inspect the template and setting, and maybe see a list of recent injected pods.

**Comment by ayj** [comment]
k8s api-server does provide some webhook request metrics.

```bash
kubectl proxy &
$ curl -s localhost:8001/metrics |grep sidecar-inject
apiserver_request_count{client="sidecar-injector/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",contentType="application/json",resource="mutatingwebhookconfigurations",scope="cluster",subresource="",verb="GET"} 3
apiserver_request_count{client="sidecar-injector/v0.0.0 (linux/amd64) kubernetes/$Format",code="200",contentType="application/json",resource="mutatingwebhookconfigurations",scope="cluster",subresource="",verb="PATCH"} 3
```

**Comment by kyessenov** [comment]
Do you want a proxy in front the injector?
