### ISSUE TITLE
Istioctl gen-deploy doesn't honour conditional chart dependencies

### ISSUE THREAD

**Issue by Stono** [istio/istio#5968]
Hey, 
I have `ingressgateway` and `egressgateway` enabled = `false`, however when running `istioctl gen-deploy` I still get those charts output.

This *does not* happen if i just use helm template.

Question:  what does `gen-deploy` do over `helm template` ?
Ta
Karl

**Comment by Stono** [comment]
Same goes for galley actually, so looks like gen-deploy doesn't honour the conditions in the chart dependencies

**Comment by wattli** [comment]
@ayj , please help to take a look or reassign, thanks!

**Comment by sakshigoel12** [comment]
@mandarjog can you take a look?

**Comment by nmittler** [comment]
@mandarjog any update on this?

**Comment by nmittler** [comment]
@mandarjog gentle ping :)

**Comment by ayj** [comment]
Shall we deprecate `gen-deploy` now that `helm` is the [official installation mechanism](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-users/ZveTbMj1L4k/sD7OiF_tCgAJ)?

**Comment by ayj** [comment]
We should strongly consider removing `gen-deploy` for 1.1 release. It is currently broken and not really tested anymore. Helm seems to be the preferred (supported) mechanism. We can consider re-introducing a similar 'install' subcommand later if needed.

**Comment by ozevren** [comment]
Any objections to removing the command?
