### ISSUE TITLE
Distributed tracing page out of date with 0.8.0

### ISSUE THREAD

**Issue by objectiser** [istio/istio#5971]
The [distributed tracing](https://istio.io/docs/tasks/telemetry/distributed-tracing) page refers to `install/kubernetes/addons/zipkin.yaml` which no longer exists.

Not sure if there is an alternative template for zipkin?

Or should the page be updated to describe the new helm install option with `--set tracing.enabled=true`, or using the `istio-demo.yaml` - and then accessing the UI via the `tracing` service?

**Comment by wattli** [comment]
@douglas-reid , can you help to take a look or reassign please? Thanks.

**Comment by douglas-reid** [comment]
@linsun do i recall correctly that you were handling something related to the addon yamls, including `zipkin.yaml` ? I don't remember what the final decisions were related to the deployment artifacts.

@objectiser I'm fine with updating, if the add-on yamls are no longer being generated.

**Comment by linsun** [comment]
@douglas-reid sorry i haven't played much with tracing yet in 0.8, on my todo.  I believe we decided to have  jaeger as optional component.

@objectiser feel free to submit a PR (or doc PR) for this.
