### ISSUE TITLE
Add an automated test for kiali

### ISSUE THREAD

**Issue by linsun** [istio/istio#5977]
Kiali was added as an optional addon, let's add a simple test case to ensure it can be properly installed and running via helm.

**Comment by gbaufake** [comment]
@linsun 
I'll create the test. Is this an e2e test or a different type of test?

**Comment by linsun** [comment]
@gbaufake thank you!  e-2-e is great, or you could start with just validate the component and CRDs exist.

**Comment by gbaufake** [comment]
cc @jeffmendoza

**Comment by gbaufake** [comment]
WIP.
@linsun  can you find someone that is able to review #11448 ?

**Comment by gbaufake** [comment]
Closing this one because #11448
