### ISSUE TITLE
Istio oncall Handoff

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#598]
Place to leave history of oncall rotation events to facilitate Handoff to the next person.

**Comment by sebastienvas** [comment]
@gnirodi please see the list of oustanding issues
https://github.com/search?q=org%3Aistio+is%3Aissue+is%3Aopen+label%3Aoncall+

**Comment by ldemailly** [comment]
should we write up a bit what happened/progress every day ? (with link to created/solved issues etc)

**Comment by andraxylia** [comment]
Why is this tracked as an issue and not in a document? This reads from top -> bottom and it will get very long. A document can have the last week at the top.

**Comment by sebastienvas** [comment]
I feel this is a little bit overkill. [Here](https://github.com/istio/istio#boards?labels=oncall&notFullScreen=false&repos=78482929,75322405,75686596,76675987,74177509,82706976,74175805,91006461,81612946,76586412,84989584&showPRs=false&showClosed=false ) is a better link. is a better link than the first one. You can look at details there, but maybe a summary would be enough from week to week.

**Comment by sebastienvas** [comment]
@gnirodi Please provide a summary and assign this to @ZackButcher.

**Comment by xiaolanz** [comment]
@gnirodi  I'm the primary oncall. Please assign to me.

**Comment by ldemailly** [comment]
joy you should be able to assign yourself to istio/istio issues - are you not ? if not let me know I'll try to find where to add you

**Comment by xiaolanz** [comment]
Yes. But I'm await gnirodi@ to assign it to me officially for handoff. He was still holding on to it until the release is done.

**Comment by sebastienvas** [comment]
I am finding this bug kind of useless, I think the list of bug is good enough for handover. Re-open if you don't agree

**Comment by kyessenov** [comment]
Removing the link from oncall document.
