### ISSUE TITLE
Error: could not read valid configmap "istio" from namespace  "istio-system"

### ISSUE THREAD

**Issue by bochuxt** [istio/istio#5994]
kubectl apply -f <(istioctl kube-inject --debug -f samples/bookinfo/kube/bookinfo.yaml)
Flag --debug has been deprecated, Use --injectConfigMapName or --injectConfigFile instead
Error: could not read valid configmap "istio" from namespace  "istio-system": configmaps "istio" not found - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
error: no objects passed to apply

**Comment by ymesika** [comment]
You need to install Istio before running this command and make sure `kubectl` can access your cluster. E.g. `kubectl get nodes`.

**Comment by sakshigoel12** [comment]
@bochuxt please confirm if above comment resolves your issue and close it

**Comment by bochuxt** [comment]
works now. Thank you so much.
