### ISSUE TITLE
Enable `istioctl edit` to edit some resources

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6004]
Kubernetes support `kubectl edit`, it is better to enable`istioctl` also support `edit` option so as to update some resources, such as `virtualservices`, `gateway` etc.

**Comment by mk01** [comment]
@gyliu513 

you cannot use kubectl ? all the stuff is CRDs.

kubectl edit/get/xyz gateway, virtualservices, routerules   [-o yaml] works.

at least if you don't require also validation. but quick edits/changes are fine.

**Comment by gyliu513** [comment]
@mk01  Yes, we can use `kubectl edit`, but without validation is not acceptable when edit the CRD, as people may make some mistakes when update.

**Comment by ayj** [comment]
Server-side validation is enabled by default in master now and should ship with 1.0

**Comment by gyliu513** [comment]
Thanks @ayj , then with Server-side validation, we can always encourage end user user `kubectl` to edit resources. Can you please link the Server-side validation to this issue for reference?

**Comment by ayj** [comment]
Tracking issue for server-side validation - https://github.com/istio/istio/issues/1894
