### ISSUE TITLE
Redeploying istio chart get error: jobs.batch "istio-mixer-post-install" already exists

### ISSUE THREAD

**Issue by morvencao** [istio/istio#6009]
**env:**
```
ubuntu: 16.04
istio version: istio-0.8.0
kubenetes version: v1.10.0
helm version
Client: &version.Version{SemVer:"v2.7.3", GitCommit:"f44bccdcdb09221c3817b4e1f9f26241113ac65e", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"v2.7.3", GitCommit:"27442e4cfd324d8f82f935fe0b7b492994d4c289", GitTreeState:"dirty"}
```

**Reproduce steps**
1. Download and install `istio-0.8.0` with helm:
```
curl -L https://git.io/getLatestIstio | sh -
cd istio-0.8.0/
kubectl create ns istio-system
helm install ./install/kubernetes/helm/istio --name istio --namespace istio-system
```
2. Delete and Redeploy istio-chart
```
helm delete istio --purge
helm install ./install/kubernetes/helm/istio --name istio --namespace istio-system
```
Get error message:
```
root@master:~/istio-0.8.0# helm install ./install/kubernetes/helm/istio --name istio --namespace istio-system
Error: jobs.batch "istio-mixer-post-install" already exists
```

**Analysis**
We have mentioned in doc that helm 2.7.2+ is required in https://istio.io/docs/setup/kubernetes/multicluster-install/#prerequisites
and https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/Chart.yaml#L4
But we have used  new feature **before-hook-creation** required helm/tiller 2.9.0+: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml#L64

Results that the hook job and corresponding pod keep living after the chart is delete, and redeploy will fail.

/cc @mandarjog @linsun @gyliu513

**Comment by gyliu513** [comment]
@morvencao I think that we need to update document to tell customer how to clean up those CRD if they are using helm <2.9.0

@mandarjog @linsun any comments?

**Comment by ymesika** [comment]
@gyliu513 The CRDs should already be removed by helm after #5750.
The only remains are secrets and that job.

**Comment by morvencao** [comment]
@ymesika @gyliu513 Just job and corresponding pod for creating CR in mixer subchart are left behind.

**Comment by gyliu513** [comment]
so I think we need to document for how to delete those garbage resources before customer re-install with helm.

**Comment by mandarjog** [comment]
@morvencao , @ymesika @gyliu513 . I agree we need to update document. Does any one  have the bandwidth to update docs?

previously we had used 
```diff
--   "helm.sh/hook-delete-policy": hook-succeeded
++   "helm.sh/hook-delete-policy": before-hook-creation
```

**Comment by gyliu513** [comment]
@morvencao will help update the document.
