### ISSUE TITLE
Mutual tls is not working with istio 0.8.0

### ISSUE THREAD

**Issue by ajit-hybris** [istio/istio#6026]
**How istio is deployed:**

https://istio.io/docs/setup/kubernetes/quick-start/#minikube
K8s version 1.10.0
$ kubectl apply -f install/kubernetes/istio-demo-_**auth**_.yaml

**Description**:

Two pods with side-car injected and mTLS enabled are not able to communicate with each other.
Error: connection reset by peer

**But** a pod with no side-car can communicate with any of the mtls pods. 
 
------

**How to reproduce:**

I have compiled my steps of deploying and verifying ingress (istio_demo_on_minikube.sh)
https://github.com/ajit-dev-ops/k8s-istio/tree/master/deploying-on-minikube

**Comment by ajit-hybris** [comment]
Here is the result of verifying mTLS:

11:53 $ kubectl get namespace -L istio-injection
NAME           STATUS    AGE       ISTIO-INJECTION
default        Active    10m       enabled
istio-system   Active    9m
kube-public    Active    10m
kube-system    Active    10m
my-ns          Active    3m

---------
11:25 $ kubectl get pods -n default
NAME                                     READY     STATUS    RESTARTS   AGE
my-nginx-with-istio-1-78df8675db-fv6xp   2/2       Running   0          1h
my-nginx-with-istio-2-c46c56976-74bfx    2/2       Running   0          1h

---------

kubectl exec -it $(kubectl  get pods -l run=my-nginx-with-istio-1 -o jsonpath='{.items[0].metadata.name}') -c my-nginx-with-istio-1 \
     curl my-nginx-with-istio-2

curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56

**Comment by ymesika** [comment]
If you'll add `--port=80` to your pod deployment commands it should work. E.g. from your script:
```sh
kubectl run my-nginx-with-istio-1 --image=ajitchahal/nginx-2 --port=80
kubectl run my-nginx-with-istio-2 --image=ajitchahal/nginx-2 --port=80
```

This is the equivalent of having a `containerPort` in a deployment yaml.

**Comment by ajit-hybris** [comment]
Magic 👍 , the same setup was working with istio 0.6.0.

**Comment by ymesika** [comment]
I don't think the port number matters.
The name too because in Ajit's case for example there is no name at all.

**Comment by vijaycruise** [comment]
@ymesika Thanks for the clarification. I tested with a non-default port and it is working as documented here - https://istio.io/docs/tasks/security/authn-policy/
