### ISSUE TITLE
mtlsExcludedServices doesn't appear to be working (as it did in 0.7.1)

### ISSUE THREAD

**Issue by Stono** [istio/istio#6028]
Hey, 
Following on from https://github.com/istio/istio/issues/3533

We have the following istio configuration:

```
apiVersion: v1
data:
  mesh: |
    ---
    authPolicy: MUTUAL_TLS
    mtlsExcludedServices:
    - kubernetes.default.svc.cluster.local
```

However, `ingress-nginx` when booting attempts to talk to the kubernetes master:

```
❯ kn logs ingress-nginx-internal-controller-5ff98ccd58-tjnx2 --follow master -p
Booting nginx...(/nginx-ingress-controller --default-backend-service=ingress-nginx/default-http-backend --configmap=ingress-nginx/nginx-configuration-internal --tcp-services-configmap=ingress-nginx/tcp-services --udp-services-configmap=ingress-nginx/udp-services --annotations-prefix=nginx.ingress.kubernetes.io --publish-service=ingress-nginx/ingress-nginx-internal --ingress-class=nginx-internal --enable-ssl-chain-completion=false)
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.15.0
  Build:      git-f3e9292c0
  Repository: https://github.com/aledbf/ingress-nginx
-------------------------------------------------------------------------------

I0605 07:50:09.164896       1 flags.go:162] Watching for ingress class: nginx-internal
W0605 07:50:09.164956       1 flags.go:165] only Ingress with class "nginx-internal" will be processed by this ingress controller
W0605 07:50:09.165113       1 flags.go:195] Check of SSL certificate chain is disabled (--enable-ssl-chain-completion=false)
nginx version: nginx/1.13.12
W0605 07:50:09.290332       1 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0605 07:50:09.290555       1 main.go:160] Creating API client for https://10.192.96.1:443
```

This fails, unless I explicitly add a DestinationRule like so:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-to-k8s
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

Which doesn't really make sense, as it's in `mtlsExcludedServices`.

This worked in 0.7.1 so feels like a bit of a regression if you plan to continue the `mtlsExcludedServices` ConfigMap configuration.

**Comment by nmittler** [comment]
@rshriram Just looking through the history, #5525 looks like it might be related. Any thoughts?

**Comment by rshriram** [comment]
Hi, the mTLSExcludedServices setting has been deprecated. Starting with 0.8, you can opt in services for Auth, instead of excluding one or more services. 
I have asked @incfly and @diemtvu to remove these settings to avoid confusion and add the destination rules for kubernetes.default.svc.cluster.local to istio install, so that you don't have to explicitly specify these settings.

**Comment by diemtvu** [comment]
FYI, here is the instruction to replace it with destination rule.

https://istio.io/docs/setup/kubernetes/upgrading-istio/#migrating-mtls-excluded-services-config-to-destination-rules

**Comment by maxkondr** [comment]
please remove mtlsExcludedServices option from configs in repo/helm chart, as soon as it confuses new users

**Comment by Stono** [comment]
Agreed, and I'd also ship with a default `DestinationRule` for the kubernetes master in the helm chart

**Comment by wattli** [comment]
I don't think we need DestinationRule for k8s any more since by default it's not mTLS.

**Comment by Stono** [comment]
What do you mean "by default it's not mtls"?

Multiple people have needed to add this destinationrule since 0.8

**Comment by diemtvu** [comment]
We will ship it together with the new way to enable mTLS globally in the next release (a quick heads up, we will provide an yaml file that contain necessary authentication policy and destination rules to enable mTLS, instead of using mesh config flags). Sorry for this migration trouble.
