### ISSUE TITLE
Cryptic error when failing to download istioctl

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#603]
W0826 07:34:29.954] E0826 07:34:29.951714    1022 framework.go:199] Failed to complete Init. Error command failed: "" fork/exec /tmp/istio.e2e.631616937/istioctl: exec format error

When we get this error, the file is missing. Let's make sure we check return code and return a proper error.

**Comment by yutongz** [comment]
Put it here as a reference:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/600/e2e-suite-rbac-no_auth/90/
