### ISSUE TITLE
where elasticsearch data saved?

### ISSUE THREAD

**Issue by jiuchongxiao** [istio/istio#6030]
in Logging with Fluentd module
where elasticsearch data saved? 
it write as flower:
   volumeMounts:
        - name: elasticsearch
          mountPath: /data
      volumes:
      - name: elasticsearch
        emptyDir: {}

but i can not see the elasticsearch data under /data. who can help me? thank you

**Comment by jasmine-jaksic** [comment]
Please use istio-users@googlegroups.com or https://istio.rocket.chat if you have additional questions.
