### ISSUE TITLE
Deploy istio chart fails due to mixer post-install hook job keep failing

### ISSUE THREAD

**Issue by morvencao** [istio/istio#6031]
**env:**
```
ubuntu: 16.04
istio version: istio-0.8.0
kubenetes version: v1.10.0
```

**Reproduce steps**
Actually it's hard to reproduce by `helm install` command line. I have reproduced this deploying the istio-chart from Catalog of IBM Cloud Private.

**Symptom**
The error is that mixer post-install hook job keeps creating new pod and keep failing until timeout.
Have caught the logs of failed pods:
```
root@llcao-master:~/istio-chart# kubectl -n istio-system logs -f istio-mixer-post-install-gspwf
2018-06-05 08:41:14.429103 I | proto: duplicate proto type registered: google.protobuf.Any
2018-06-05 08:41:14.429152 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-06-05 08:41:14.429164 I | proto: duplicate proto type registered: google.protobuf.Timestamp
attributemanifest "istioproxy" configured
attributemanifest "kubernetes" configured
stdio "handler" configured
logentry "accesslog" configured
rule "stdio" configured
metric "requestcount" configured
metric "requestduration" configured
metric "requestsize" configured
metric "responsesize" configured
metric "tcpbytesent" configured
metric "tcpbytereceived" configured
prometheus "handler" configured
rule "promhttp" configured
rule "promtcp" configured
kubernetesenv "handler" configured
destinationrule "istio-policy" configured
destinationrule "istio-telemetry" configured
Error from server: error when creating "/tmp/mixer/custom-resources.yaml": admission webhook "mixer.validation.istio.io" denied the request: 1 error occurred:

* actions[0].instances[0]: attributes.kubernetes not found
Error from server: error when creating "/tmp/mixer/custom-resources.yaml": admission webhook "mixer.validation.istio.io" denied the request: 1 error occurred:

* actions[0].instances[0]: attributes.kubernetes not found
Error from server: error when creating "/tmp/mixer/custom-resources.yaml": admission webhook "mixer.validation.istio.io" denied the request: error evaluating AttributeBinding expression 'adapter_template_kubernetes.output.source_service | "unknown"' for attribute 'source.service': unknown attribute adapter_template_kubernetes.output.source_service
```

More accurately, the error is relate to these lines: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml#L447-L496

Have tried change the sequence of the related CR, still no good.
Suspect that this has something with the validating webhook defined here: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/galley/templates/validatingwebhook.yaml#L49-L94
But it's all right when I deploy with `helm install` CLI.

/cc @gyliu513 @linsun

**Comment by mandarjog** [comment]
@morvencao do you see `istio-galley` deployment up and running? `galley` chart is not enabled in values.yaml. So it looks like you are specifically enabling this chart and installing validating webhook.
This feature is not really supported in 0.8.

**Comment by morvencao** [comment]
@mandarjog Thanks, I do enable `galley`. I thought the `validatingWebhook` is working for istio 0.8.0
It's all right after I disable `galley`.

**Comment by ayj** [comment]
@guptasu, would this possibly related to your recent mixer validation changes?

**Comment by mandarjog** [comment]
@ayj this problem happens in 0.8, the latest changes that @guptasu made are in pending on master, were you thinking about some other changes?

**Comment by ymesika** [comment]
I'm also seeing these errors with `master` without touching `values.yaml` (galley enabled by default).
Are the galley and validation webhook mutual exclusive?
