### ISSUE TITLE
Flag --includeIPRanges has been deprecated, Use --injectConfigMapName or --injectConfigFile instead

### ISSUE THREAD

**Issue by adoo123** [istio/istio#6043]
Hello,
Could you give an example to use --injectConfigMapName or --injectConfigFile instead --includeIPRanges in istio 0.8?
![image](https://user-images.githubusercontent.com/32384019/41012709-87d67dba-6975-11e8-8269-063d2f532279.png)

**Comment by gyliu513** [comment]
Duplicate with https://github.com/istio/istio.github.io/issues/1433

Please check the PR here https://github.com/istio/istio.github.io/pull/1450 for how to do this.
