### ISSUE TITLE
Ingressgateway couldn't be unified entrance for multi services

### ISSUE THREAD

**Issue by adoo123** [istio/istio#6045]
When I use ingress, I can create different Ingress with different context path.I can use ingress ip:port and different context path to access different service.
How can I use gateway and virtualservice to archive this?When i create a gateway,and two virtual service,it has error ：

![image](https://user-images.githubusercontent.com/32384019/41013884-dca114d6-697a-11e8-97d0-bbb69e0e319b.png)

![image](https://user-images.githubusercontent.com/32384019/41013875-d095d6e0-697a-11e8-9307-453621e5896a.png)

![image](https://user-images.githubusercontent.com/32384019/41015229-f420ea2c-697b-11e8-8723-6347c0004481.png)

![image](https://user-images.githubusercontent.com/32384019/41013730-2328a3ca-697a-11e8-8785-d30d2cafef78.png)

I know the host can not repeat，but I want to use ingressgateway's ip and port to be unified entrance.When the "match" write in the same virtualservice,it can archive,but I don't want to write together,how to fix it?

**Comment by gyliu513** [comment]
@rshriram @vadimeisenbergibm @cmluciano comments for this?

So for such case, I can use one ingress gateway with wildcard domain and multiple virtualservice rules to handle this? What is the best practise for this?

**Comment by gyliu513** [comment]
@adoo123 you can merge your two virtualservices to one file as follows and it will work, let us wait some comments from @rshriram @vadimeisenbergibm @cmluciano 

```
[root@gyliu-icp-1 istio-0.8.0]# istioctl get virtualservices -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: bookinfo
  namespace: default
  resourceVersion: "1715393"
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
---
```

**Comment by adoo123** [comment]
@gyliu513 I know this solution，but it's inflexible and inconvenient to maintain.Cause some service need domain ,others no need,it needs to be written separately

**Comment by gyliu513** [comment]
Thanks @rshriram one more question, for which case I need to create my own ingressgateway?

**Comment by adoo123** [comment]
@rshriram It seems I can use a gateway with host "*", domain virtualservice can be written separately, no-domain virtualservice must be written together.So i will try k8s ingress to instead ingressgateway.

**Comment by wodepan** [comment]
@rshriram  How to create gateway? When i create a new gateway, it can't work.   

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
    app: helloworld
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helo.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helo-vs
spec:
  hosts:
  - "helo.com"
  gateways:
  - helo-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: helloworld
        port:
          number: 80

**Comment by wodepan** [comment]
@adoo123  How can i  add a new gateway? When i create a new gateway , it can't work.
<pre> 
<code>
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
    app: helloworld
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helo.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helo-vs
spec:
  hosts:
  - "helo.com"
  gateways:
  - helo-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: helloworld
        port:
          number: 80
</code>
</pre>

**Comment by adoo123** [comment]
@wodepan If you want to create multiple gateway,you need make sure the gateway's port cannot be repeated. For your yaml,you can try to modify "exact: /" to "prefix: /".

**Comment by wodepan** [comment]
@adoo123 Thanks a lot. I want to create a ingressgateway,but i don't know how to create it.

**Comment by gyliu513** [comment]
@wodepan does this help https://github.com/istio/istio/blob/master/tests/helm/templates/gateway.yaml#L15-L23 , you can add more `hosts` as new ingressgateway.

**Comment by wodepan** [comment]
@gyliu513 Tanks a lot. My problem is,  i have ten service, every service provide external service (TCP) ,   i want to create ten ingressgateway as istio:ingressgateway, and create one gateway for every ingressgateway, and create one virtualservice for every gateway, but i can't found the sample for istio:ingressgateway .

**Comment by adoo123** [comment]
@wodepan Why don't you use NodePort..?

**Comment by rshriram** [comment]
You need to launch separate gateway pods and services for each gateway you want. You have to play with helm to get the kubernetes yamls. https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/charts/ingressgateway

Once you launch a gateway service (which is essentially a load balancer service), you use the pod selectors for this service in the Istio Gateway spec

**Comment by gyliu513** [comment]
@rshriram @frankbu one more question, in which scenario shall I need to create my own separate ingressgateway?

**Comment by jasmine-jaksic** [comment]
Please use istio-users@googlegroups.com or https://istio.rocket.chat if you have questions.

**Comment by xiajidexue** [comment]
> @gyliu513 Tanks a lot. My problem is, i have ten service, every service provide external service (TCP) , i want to create ten ingressgateway as istio:ingressgateway, and create one gateway for every ingressgateway, and create one virtualservice for every gateway, but i can't found the sample for istio:ingressgateway .

I have the same requirement, have you got the solution or workaround?

**Comment by xiajidexue** [comment]
> You need to launch separate gateway pods and services for each gateway you want. You have to play with helm to get the kubernetes yamls. https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/charts/ingressgateway
> 
> Once you launch a gateway service (which is essentially a load balancer service), you use the pod selectors for this service in the Istio Gateway spec

Only one way you entioned to match wodepan's requirements? are there other ones?

**Comment by xiajidexue** [comment]
I have solved this problem, now i can use Ingress gateway IP and different ports to distinguish different Kubernetes services.

**Comment by frankbu** [comment]
Doesn't this help solve @wodepan's problem? https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host

**Comment by sangnguyen7** [comment]
> I have solved this problem, now i can use Ingress gateway IP and different ports to distinguish different Kubernetes services.
@xiajidexue could you please share how you do that?
