### ISSUE TITLE
Do not expose targetPort/containerPort in helm chart

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6047]
Currently, in istio helm chart, we exposed many `targePort`, but the `targetPort` is the pod port which was exposed by docker image, and if customer change this port, the service may not work, so we should not expose those ports.

Such as follows:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L38
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L18

/cc @costinm @sdake comments?

**Comment by morvencao** [comment]
+1 
We also need remove the following `containerPort` from `values.yam`
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L175-L177
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L215-L216

**Comment by kyessenov** [comment]
Istio requires container ports. If you don't specify the pod port in the container port list, all the istio feature will be disabled for those ports.

**Comment by kyessenov** [comment]
Yes, hardcoding is fine.

**Comment by costinm** [comment]
Actually - not clear this is needed or good ( and conflicts with the goal of simplified installation ).

We ship docker containers - the install should match the target ports. They are not customisable, and we don't have tests for istio using different ports. If users change the ports and use their own values - they should change helm as well, and not expect us to support them

**Comment by sdake** [comment]
@costinm if you take a look at the PR submitted for this issue, the container ports are hard coded instead of dynamic.  This seems like an improvement to me as the root issue is "dynamic ports could cause breakage"

 Perhaps we don't need containerPorts at all to be specified in the yaml.  Is that why the issue was closed?

Cheers
-steve
