### ISSUE TITLE
includeIPRanges not working in istio 0.8

### ISSUE THREAD

**Issue by zainul-ma** [istio/istio#6048]
i try to use ```includeIPRanges``` in istio 0.8 when started service using manual ```kube-inject``` and then the out say

```
Flag --includeIPRanges has been deprecated, Use --injectConfigMapName or --injectConfigFile instead
```

it's like not supported again ? and how to make baypass all, because currently i try setting eggress also not work ?

**Comment by zainul-ma** [comment]
found the issue , about istioctl , i use istioctl version 0.7.1 but istio 0.8 it's work for me
it's like bug in istioctl
but and how about setting egress not work in istio 0.8 i still figure out ..

/bug

**Comment by gyliu513** [comment]
Duplicate with https://github.com/istio/istio.github.io/issues/1433

Please check the PR here https://github.com/istio/istio.github.io/pull/1450 for how to do this.
