### ISSUE TITLE
Update Istio

### ISSUE THREAD

**Issue by hamon-e** [istio/istio#6050]
I'm trying to update my istio to 0.8 (I previously update my k8s master to 1.9.7)

Firstly i ran this:
```
helm template --namespace istio-system --set global.proxy.image=proxy \
        --values install/kubernetes/helm/istio/values-istio.yaml \
        install/kubernetes/helm/istio >> install/kubernetes/istio.yaml

```

When I secondly run kubectl apply -f ..../istio.yaml, I have this error
```
The Service "istio-ingressgateway" is invalid: spec.ports[0].nodePort: Invalid value: 31380: provided port is already allocated
```

I indeed have a service running on this port

What should i do ?

Thanks

**Comment by ymesika** [comment]
Do you use the `values-istio.yaml` instead of `values.yaml` for a reason? If not you can try using a different available port for the `ingressgateway` by adding another set:

```sh
helm template --namespace istio-system --set global.proxy.image=proxy \
--set ingressgateway.service.ports[0].nodePort=12345 \
--values install/kubernetes/helm/istio/values.yaml install/kubernetes/helm/istio
```

**Comment by hamon-e** [comment]
It works, thanks

**Comment by hklai** [comment]
Looks like this has been resolved.
