### ISSUE TITLE
Re-enable kubernetes adapter validation

### ISSUE THREAD

**Issue by ayj** [istio/istio#6055]
Validation for `kuberneteses` adapter CRDs are temporarily disabled. Mixer validation has some issues (see [here](https://github.com/istio/istio/pull/6035#issuecomment-394927685)) which prevents dependent rules from being created. Re-enable this resource in galley's validatingwebhookconfiguration.yaml once mixer validation is fixed for this type.

**Comment by ozevren** [comment]
CRD per adapter model is going away. Keeping the bug around for posterity.

**Comment by douglas-reid** [comment]
@ozevren I'm going to just close the bug instead of keeping it around. With 1.2, the old adapter config model will no longer be the default. I think it is OK to no longer track this work.
