### ISSUE TITLE
istioctl should support short names

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6065]
Kubernetes support short name with kubectl, such as 

```
kubectl get svc
```
```
kubectl get crd
```

It is better for istioctl create such command so that we can use command with ease

**Comment by ayj** [comment]
Short names seem reasonable for well known types, e.g. service, customresourcedefinition. I'm not sure how well they will work long term with multiple k8s add-ons using CRDs. We already have issues with short names conflicting (see https://github.com/istio/istio/issues/5532)

**Comment by gyliu513** [comment]
@ayj I think here the base line is we should make sure istio does not conflict with Kubernetes names. For CRD, I think the customer need to check if their CRD conflict with Kubernetes or Isito short names, comments?

**Comment by gyliu513** [comment]
Duplicate with follows:
- https://github.com/istio/istio/pull/3394
- https://github.com/istio/istio/issues/2650
