### ISSUE TITLE
port problem of  VirtualService's hosts

### ISSUE THREAD

**Issue by wodepan** [istio/istio#6066]
When i access http service  by 31380 port,  i must specified  host and port for hosts as below.  why?
<pre>
<code>
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helo-vs
spec:
  hosts:
  - "helo.com:31380"
  - "helo.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: helloworld
        port:
          number: 80
</code>
</pre>

**Comment by idouba** [comment]
We met exactly the same problem.

**Comment by x15zhang** [comment]
I suspect the reason is that the same host in gateway may have different port. If not specified port in that situation,the request cannot be routed correctly. 
But if only one port(expect 80) for a host in gateway,it should not be specified in VirtualService.
Can it be improvement? @rshriram

**Comment by rshriram** [comment]
Check the curl or client you are using. If the client is appending the portname to the http host header, then yes, you would need to specify the port in the virtual service. if the client is simply using the hostname alone, "helo.com", then port number is not needed. Essentially, think of the hosts in the virtual hosts as the equivalent of http server's virtual hosts - if the client does not access the server using that virtual host, the server will jhave no way of knowing where to route the connection to.

**Comment by jasmine-jaksic** [comment]
Please use istio-users@googlegroups.com or https://istio.rocket.chat if you have additional questions.
