### ISSUE TITLE
Clean up end to end multicluster testing

### ISSUE THREAD

**Issue by sdake** [istio/istio#6072]
Multicluster testing currently uses the configmap which is deprecated.  To finish the deprecation process and remove the configmap from the system, the e2e tests need modifications to register secrets as documented here:
https://istio.io/docs/setup/kubernetes/multicluster-install/#gather-credential-files-from-remote

This will make testing line up with documentation.

**Comment by tiswanso** [comment]
unstale

**Comment by tiswanso** [comment]
#6454  merged ... closing

**Comment by tiswanso** [comment]
Additionally, the merge of the following PRs fix the multicluster e2e prow job:

#7376
#6679
