### ISSUE TITLE
Istio bookinfo sample deployment The connection has timed out

### ISSUE THREAD

**Issue by arycloud** [istio/istio#608]
I'm trying to setup istio on Google container engine, istio has been installed successfully but booking sample has been failed to load.

Is there something I have configured in wrong way?
Help me, please!
Thanks in advance!

Here's what's I have tried:

    kubectl get pods

    details-v1-3121678156-3h2wx       2/2       Running   0          58m
    grafana-1395297218-h0tjv          1/1       Running   0          5h
    istio-ca-4001657623-n00zx         1/1       Running   0          5h
    istio-egress-2038322175-0jtf5     1/1       Running   0          5h
    istio-ingress-2247081378-fvr33    1/1       Running   0          5h
    istio-mixer-2450814972-jrrm4      1/1       Running   0          5h
    istio-pilot-1836659236-kw7cr      2/2       Running   0          5h
    productpage-v1-1440812148-gqrgl   0/2       Pending   0          57m
    prometheus-3067433533-fqcfw       1/1       Running   0          5h
    ratings-v1-3755476866-jbh80       2/2       Running   0          58m
    reviews-v1-3728017321-0m7mk       0/2       Pending   0          58m
    reviews-v2-196544427-6ftf5        0/2       Pending   0          58m
    reviews-v3-959055789-079xz        0/2       Pending   0          57m
    servicegraph-3127588006-03b93     1/1       Running   0          5h
    zipkin-4057566570-0cb86           1/1       Running   0          5h

**kubectl get svc**
    
    NAME            CLUSTER-IP      EXTERNAL-IP       PORT(S)                        
    details         10.11.249.214   <none>            9080/TCP                      
    grafana         10.11.247.226   104.199.211.175   3000:31036/TCP         
    istio-egress    10.11.246.60    <none>            80/TCP              
    istio-ingress   10.11.242.178   35.189.165.119    80:31622/TCP,443:31241/TCP  
    istio-mixer     10.11.242.104   <none>            9091/TCP,9094/TCP,42422/TCP 
    istio-pilot     10.11.251.240   <none>            8080/TCP,8081/TCP           
    kubernetes      10.11.240.1     <none>            443/TCP                  
    productpage     10.11.255.53    <none>            9080/TCP                      
    prometheus      10.11.248.237   130.211.249.66    9090:32056/TCP               
    ratings         10.11.252.40    <none>            9080/TCP                      
    reviews         10.11.242.168   <none>            9080/TCP                      
    servicegraph    10.11.252.60    35.185.161.219    8088:32709/TCP               
    zipkin          10.11.245.4     35.185.144.62     9411:31677/TCP          

**get ingress IP and export env variable then curl**

    NAME      HOSTS     ADDRESS          PORTS     AGE
    gateway   *         35.189.165.119   80        1h
    Abduls-MacBook-Pro:~ abdul$ export GATEWAY_URL=35.189.165.119:80
    Abduls-MacBook-Pro:~ abdul$ curl -o /dev/null -s -w "%{http_code}\n"    http://${GATEWAY_URL}/productpage
    000

**Comment by andraxylia** [comment]
You need 4 nodes in your cluster, but default the cluster is created with 3 nodes.

**Comment by ldemailly** [comment]
closing assuming a bigger cluster resolves the issue
