### ISSUE TITLE
Exposing `Status` on Istio resources

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#6082]
It would be great if Istio resources (like Gateway) expose some Status information so that downstream can check before sending traffic to the Gateway.

Similarly, it would be good to know when a VirtualService's routerules have been propagated / effective.

**Comment by tcnghia** [comment]
@andraxylia

**Comment by esnible** [comment]
Issue https://github.com/istio/istio/issues/5732 proposes exposing this information via the CLI.

**Comment by ayj** [comment]
Config telemetry would also help here. e.g. something like https://github.com/istio/istio/pull/5893 reported by the proxy correlated back to user authored CRD.

**Comment by ayj** [comment]
dup of #882
