### ISSUE TITLE
Exposing a way to use the Istio API

### ISSUE THREAD

**Issue by tcnghia** [istio/istio#6084]
Currently Istio resources are defined as protobuf.  This makes it hard to generate a K8S style API client for downstream application to call the API.  For example, some application may want to create Gateway/VirtualServices on behalf of the users.

One way is to expose and document the code to convert Istio resources from protocol buffer to and from JSON/YAML, which would allows a client to talk to low level K8s using JSON serialized from the protobufs.    It looks like there is code like this already in the Istio source (like https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/conversion.go).

Or alternatively, if possible, Istio team coud maintain a generated K8s style API client.  I have such generated client currently, and would love to share.  It will be certainly more work to keep such client in-sync with the .proto files, but the benefit is that Istio clients won't need to do this themselves.

**Comment by andraxylia** [comment]
cc @ayj

**Comment by tcnghia** [comment]
cc @ozevren

**Comment by ozevren** [comment]
@tcnghia we are exploring K8s style Go based client libraries:
https://github.com/istio/istio/issues/8772

Would that be useful for you.

**Comment by tcnghia** [comment]
Yes, that would be great.  We're maintaining our hand-made version at https://github.com/knative/pkg/tree/master/apis/istio , but it's not complete.  If this is provided by Istio it will help a lot in using more Istio feature, as well as upgrading to a new version of the API when it comes out in the future.

**Comment by ayj** [comment]
https://github.com/istio/istio/issues/8772 proposes creating Go client libraries for Istio APIs. Closing this issue as #8772 has more information re: design.
