### ISSUE TITLE
Improve multicluster security by using service accounts with reduced RBAC permissions

### ISSUE THREAD

**Issue by sdake** [istio/istio#6094]
@costinm had suggested improving security by reduced RBAC permissions in https://github.com/istio/istio/issues/4822#issuecomment-395318154.  Need a little more clarity on requirements.

A couple options were discussed in the multicluster 0.8 issue tracker.

1. Place RBAC rules in the istio-remote helm chart
1. Reduce permissions from admin to some lesser privileges on credentials registered with the Istio control plane

Do 1, or 2, or both?

**Comment by tiswanso** [comment]
doc PR with multicluster procedure with service-account and minimal clusterRole:   https://github.com/istio/istio.github.io/pull/1484
    rendered page:  https://deploy-preview-1484--preliminary-istio.netlify.com/

Possibly the ServiceAccount, ClusterRole, and ClusterRoleBinding creation could be added to the istio-remote helm chart.  Still the documented procedure would need to have instructions for building the remote's kubeconfig for the serviceaccount token.

**Comment by tiswanso** [comment]
With the merge of #6366 an istio-multi service-account is created via the istio-remote. This service-account is bound to a clusterrole, istio-reader, with minimal and read-only access.  The setup->kubernetes->multicluster document details how to create a kubeconfig file mapped to this service-account and create the multicluster secret for pilot to use it.

Closing this issue.
