### ISSUE TITLE
Restrict the permission for service account of ingress gateway and egress gateway

### ISSUE THREAD

**Issue by morvencao** [istio/istio#6109]
We have created two independent `ServiceAccount` for `ingressgateway` and `egressgateway`, but bind with special role.
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/ingressgateway/templates/serviceaccount.yaml
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/egressgateway/templates/serviceaccount.yaml

Can we replace them with `default` serviceAccount?

/cc @gyliu513 @rshriram @sdake

**Comment by andraxylia** [comment]
Why?

Are you asking for a helm option? If helm template is used, the yaml files can be customized before deployment, but I do not see why we would enable this.

**Comment by gyliu513** [comment]
@andraxylia just not clear why we create this service account without any clusterrolebindings.

/cc @rshriram who is the original author for this.

**Comment by andraxylia** [comment]
It's something we missed when Gateway was added, and an issue, since we do not want to let the default service account configure gateways. It is only the network operator who should do it. gyliu513 could you please fix this? And let's change the title of this issue.

**Comment by gyliu513** [comment]
@andraxylia Yes, I think we can use same clusterrole and clusterrolebindings as ingress, will post a PR soon.
