### ISSUE TITLE
mixer: scope configuration by destination workload namespace as well

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6125]
Currently, mixer requires providing destination service for config resolution. For TCP services, there is no reliable way to derive the destination service without client cooperation. The end result is that pilot currently hardcodes one by guessing which services _might be_ pointing to the workload, and picking the first one. I suggest we remove the guessing logic, and fix mixer config resolution to not require destination service being sent from the proxy.

cc @ozevren @mandarjog @geeknoid

**Comment by ozevren** [comment]
So, what would be the replacement?

**Comment by kyessenov** [comment]
I think one of the two ways are reasonable:
- Allow `destination.namespace` or `destination.workload.namespace` as the primary key for the config lookup. All workloads carry some namespace, whether or not they belong to a service.
- Run config resolution after APAs. APA can infer the service (unique port for TCP, host header for HTTP).

**Comment by kyessenov** [comment]
I'm uncomfortable using "inbound" and "outbound" terminology, given we can execute most functions with a middle proxy, in which the distinction becomes murky. The proxy does not necessarily have to share its security context with the application.

Using destination namespace as the identity attribute is not sufficient. It does not cover the client-side policy check calls.

**Comment by geeknoid** [comment]
"inbound" and "outbound" are independent of how we implement this stuff, isn't it?

Inbound: traffic received by a workload instance
Outbound: traffic produced by a workload instance
