### ISSUE TITLE
Construct a model of 'nested services' or application to manage a group of services 

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#6135]
Currently It is not convienent to manage a group of services for user with istio.
It is better to construct a model of 'nested services' to manage a serial of services more conveniently. These would be logical services that encapsulate other services, making the encapsulated services invisible to the rest of the mesh.

**Comment by idouba** [comment]
Maybe can refer to [Kubernetes Applications](https://github.com/kubernetes-sigs/application).

**Comment by x15zhang** [comment]
cc @geeknoid
