### ISSUE TITLE
umbrella requests from dev

### ISSUE THREAD

**Issue by Brian-Xincheng-Zhang** [istio/istio#614]
** need to create individual issue when each is being addressed**

P0: Fast test infra, efficient access to logs / troubleshooting, visibility on queues. Responsiveness on flackyness: solution: Build cop pairing with eng prod --ldemailly
P0: Nightly or Weekly automated builds of latest of each repo, easy release promotion, auto release-notes gathering -- ldemailly
P0 (imo/tbd) Flat build -- ldemailly

P1: Pool of clusters - option to freeze/keep a cluster for troubleshooting -- ldemailly
P1: 1 working set of tools (and processes) like linter, bazel to go, etc… across repos -- ldemailly
P1: Dependencies update tools (we should uprev the dependencies at fixed point in the release cycle (at the beginning, and if emergency bugs require it)) -- ldemailly
P1: RawVM tests support -- ldemailly
P2: (github/zenhub/PjM) Issue opening/closed tracking/rates, release stabilization graphs, etc -- ldemailly

For 0.3
P0: Multi cluster test support -- ldemailly

**Comment by sebastienvas** [comment]
Created missing bug. Please see details in https://docs.google.com/document/d/1VPVpqkkJOwVhXhpiSOTqyLtTglyTBacpgEwL6xjoVnU/edit
