### ISSUE TITLE
readinessProbe for Envoy

### ISSUE THREAD

**Issue by Stono** [istio/istio#6145]
Hi, 
At first I thought this issue may be covered by https://github.com/istio/istio/issues/1425, however I now feel it is different.  If i'm wrong, please close this issue.

At a high level, I need to ensure that `istio-proxy` does not become `Ready` before it has successfully received configuration information from the control plane and has configured its listeners.

At the moment, an application pod could become `Ready` and `istio-pilot` pod would be immediately ready (due to the lack of readinessProbes on the `istio-pilot` container), yet the application would not be able to receive or send communications because `istio-pilot` has not actually initialised.

This results in a situation where we cannot do 0 downtime rollouts of an application with `istio-proxy`, as kubernetes will add it to the service before it's truly `Ready` to handle traffic.  This is particularly visible in our `ingress-nginx` controller, which (sometimes) starts receiving external mesh traffic before istio-proxy has configured, thus `ingress-nginx` is unable to send the traffic to the upstream components.

I'm wondering if there is some sort of readinessProbe that I could add to the sidecar, perhaps `curl http://127.0.0.1:15000/stats | grep <something here>` which would indicate that proxy has received its configuration from the control plane and the listeners are configured correctly.

Hope this makes sense, it's quite an urgent one for us to fix so any advice would be appreciated.
Cheers
Karl

**Comment by wattli** [comment]
This is about the actual readiness of istio-proxy/istio-pilot. I am not actively working on it.

**Comment by frankbu** [comment]
This looks like its covered by #6082

**Comment by Stono** [comment]
@frankbu how would I utilise that issue to resolve this one?

**Comment by frankbu** [comment]
For a proper solution, seems you need to wait for the solution to #882.

If you are looking for a short term workaround, I guess you could look at getting Envoy stats, something like what istioctl will be doing for #6082.

**Comment by nmittler** [comment]
@Stono FYI readiness probe for istio-proxy was implemented by https://github.com/istio/istio/pull/7465

**Comment by nmittler** [comment]
@costinm is it too late to get this into 1.0.2?
