### ISSUE TITLE
kubernetes adaptor spam

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6152]
Kubernetes adaptor should produce only one instance of the following error:
```
2018-06-11T21:45:25.897568Z     error   istio.io/istio/mixer/adapter/kubernetesenv/cache.go:147: Failed to list *v1.ReplicaSet: the server could not find the requested resources
```

Currently, it prints a line non-stop every second.

/assign @douglas-reid

**Comment by kyessenov** [comment]
I think this is actually a hard error. Mixer API is not available when I see this spam.

**Comment by kyessenov** [comment]
Confirmed by modifying the code that this is causing complete failure of telemetry. API endpoint is not created so the data gets lost on the way.

**Comment by douglas-reid** [comment]
I'm still not sure what the root cause of this issue is. Is it that the API Server has no notion of v1.ReplicaSets ?

**Comment by douglas-reid** [comment]
Is your cluster running 1.8?

**Comment by kyessenov** [comment]
Yes, it is 1.8.8.

**Comment by douglas-reid** [comment]
Ah, `v1.ReplicaSets` came in 1.9, iirc.

Do we have a minimum supported k8s version?

**Comment by douglas-reid** [comment]
Does your `$kubectl api-versions` include `apps/v1` ?

**Comment by douglas-reid** [comment]
Looks like we *recommend* 1.9. I don't know what this means for code that is using 1.9 APIs.

**Comment by kyessenov** [comment]
You should be to enumerate all server-supported APIs and figure out which
ones are available. Alternatively, you could ignore the errors that happen
due to missing versions. I think that's better than the hard-stop behavior
that happens now.

**Comment by kyessenov** [comment]
Closing since 1.9 was decided to be minimum version for 1.0. This may need to be re-opened for later milestones (in case we use alpha/beta kubernetes APIs).
