### ISSUE TITLE
Citadel setup in multiplecluster

### ISSUE THREAD

**Issue by wattli** [istio/istio#6153]
Currently each cluster has a citadel, and they share the same key/cert. Ideally, we want them to have distinguish key/cert issued by the same root.

**Comment by wattli** [comment]
@sdake , FYI, please link this to https://github.com/istio/istio/issues/4822

**Comment by tiswanso** [comment]
This seems most applicable to documentation since I believe the install templates allow for setting up citadel to use secrets for keys/certs.  Orchestrating the distribution of certs/keys signed by common CA seems outside the scope of istio/istio.

**Comment by gyliu513** [comment]
I saw there is a design here https://docs.google.com/document/d/1__rxQI74LjSdTNhKcCzzOl8esFMKZeqN5uFQmRYi6KE/edit#heading=h.x9snb54sjlu9 , but seems outdated?

@tiswanso I think we still need a solution to do cert rotation, cert revoke etc cross cluster with istio?

**Comment by tiswanso** [comment]
@gyliu513 -- Thanks for pointing me to the doc.  It does present a compelling solution to the problem with a lot more features than just setting up common CA root between citadel in multiple clusters.  I stand corrected on whether folks are viewing orchestrating the certs/keys as in scope 😄 

I do think until that spec is implemented there's a need for documentation describing the simple case described by this issue.  I think just describing or referencing how to setup the main Istio control plane cluster and remote clusters to use specific certs/keys from the multicluster setup guide would be sufficient until the auto provisioning feature is done.

**Comment by gyliu513** [comment]
@sdake can you please show me the docs of floating about on setting up citadel to work properly with multiple clusters? I want to check  more for how does cert rotation works in multicluster.

**Comment by craigbox** [comment]
This isn't obvious to a new user.

When I install Istio in two clusters, it seems I get a regular Citadel installation in the first, and a self-signed? Citadel in the second.

I'm currently trying to debug why sidecars in the second can't talk to Pilot in the first, and it seems reasonable that it might be a CA problem.

I'm therefore trying to check the certs, but if they're being acquired from a secret, I have no idea how that propagates from the first cluster to the second.  Can someone explain the current state too? I can write it up in the docs if so.
