### ISSUE TITLE
telemetry: missing client-side destination service

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6154]
Telemetry from the client-side puts "unknown" instead of destination services. This requires extending pilot plugins to annotate routes with destinations. See below:

|||||||
|--- |--- |--- |--- |--- |--- |
|reporter.local|reporterUID|destinationService|destinationUID|id|sourceUID|
|true|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|productpage.bookinfo.svc.cluster.local|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|00b1fbc5-ab19-9361-86af-b98a57a35101||
|false|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|unknown||00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|
|false|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|unknown||00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|
|true|kubernetes://details-v1-d8d8b948f-crjp7.bookinfo|details.bookinfo.svc.cluster.local|kubernetes://details-v1-d8d8b948f-crjp7.bookinfo|00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|
|true|kubernetes://reviews-v3-7cffd89777-f8gsh.bookinfo|reviews.bookinfo.svc.cluster.local|kubernetes://reviews-v3-7cffd89777-f8gsh.bookinfo|00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://productpage-v1-bdd5b55bf-5v4ch.bookinfo|
|false|kubernetes://reviews-v3-7cffd89777-f8gsh.bookinfo|unknown||00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://reviews-v3-7cffd89777-f8gsh.bookinfo|
|true|kubernetes://ratings-v1-7865946665-tgkq5.bookinfo|ratings.bookinfo.svc.cluster.local|kubernetes://ratings-v1-7865946665-tgkq5.bookinfo|00b1fbc5-ab19-9361-86af-b98a57a35101|kubernetes://reviews-v3-7cffd89777-f8gsh.bookinfo|

**Comment by ostromart** [comment]
There's no good way to annotate in the plugins because we are passing protos around. But we can create a map and pass that in as part of plugin.InputParams. Would that work?

**Comment by kyessenov** [comment]
Sure. A map from the pointers in the route configuration to destination service would work.

Also, for TCP listeners, we need to pass the route information. Currently, it's not calling on outbound route for TCP (and probably should not), so we need to extend on outbound listener as well.

**Comment by andraxylia** [comment]
How involved is the fix?

**Comment by kyessenov** [comment]
cc @bianpengyuan @douglas-reid @smawson
