### ISSUE TITLE
pilot plugins: gateway callbacks

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6162]
Gateway calls OnOutboundListener but not OnOutboundRoute. It should either call both or none of them (using dedicated OnGatewayListener callbacks). It's also not intuitive why gateway is outbound, when it is for mesh inbound traffic.

**Comment by ostromart** [comment]
I can add the OnOutboundRoute at least. I agree inbound/outbound is a bit confusing in gateway but calling it inbound could cause other confusion (listeners are outbound from gateway perspective).

**Comment by kyessenov** [comment]
Adding OnOutboundRoute seems acceptable.

**Comment by andraxylia** [comment]
What is the effect of not calling OnOutboundRoute ?

**Comment by ostromart** [comment]
well right now most of the stuff that would be in a callback is just inlined. that's different from sidecar where all the action is in the plugin callback.

**Comment by andraxylia** [comment]
This is implementation detail. What is the user visible impact/bug if this is not fixed for 1.0?

**Comment by kyessenov** [comment]
The end result is that we report incorrect telemetry, and possibly apply
incorrect policy checks.

**Comment by kyessenov** [comment]
To put some context, I'd not file this issue if this implementation detail was not a road block to some user visible problems.

**Comment by andraxylia** [comment]
@kyessenov thanks for clarifying, it helps with setting the right priority.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/6325
