### ISSUE TITLE
[test-framework] Implement a reliable config distribution detection mechanism for Pilot

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6170]
Similar to https://github.com/istio/istio/issues/6169, we'd like to implement a reliable way to detect config dissemination via Pilot, for test purposes. Ideally, this methodology would involve querying Envoy directly.

The following mechanisms can be used to listen to configuration and observe changes.
https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--config_dump
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#listener-manager

**Comment by nmittler** [comment]
appeasing the bots.

**Comment by nmittler** [comment]
This issue actually has implications beyond the testing framework (perhaps we should move it out of this epic?). We need a reliable way in Istio to determine whether the galley configuration has been propagated everywhere.

FYI @ozevren @louiscryan @costinm

**Comment by ozevren** [comment]
I think we can do something quick and cheap for the test-framework alone, by querying config dump.

The answer on the product side is going to be pretty thorny to figure out and will take some time to implement.

**Comment by cdmitri** [comment]
Just looking at this - we've done similar config polling in a custom environment to look at the diffs in the pilot config associated with specific events for debugging.

It would be nice to have it as part of the framework to be able to have all the changes/diffs for all pilots in 1 place as a sort of "pilotdump" to debug non-trivial/flaky/time-depended issues.

**Comment by ozevren** [comment]
@nmittler, how far off this with the sidecar component? Should we try to schedule some time in 1.2 to get this implemented?

**Comment by nmittler** [comment]
The sidecar gets us much closer. However, for each type of config we'll need custom logic to determine that it has been propagated.

**Comment by therealmitchconnors** [comment]
Design proposal here: https://docs.google.com/document/d/1HnfvRFBhS1iafaZQBS8Bt9o44Ldh2e_VNh-RmHqHEPM/edit#
