### ISSUE TITLE
[test-framework] Rationalize and implement GetFortioApp(s) methods.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6171]
We have two different overloads, one referencing FortioApps by name, the other one by selectors. We should rationalize this.

Presumably, Fortio Apps will be deployed once and test-framework can hard-write any selectors as necessary: We do not need to expose this to the test authors.

This includes:
- [ ]  Deciding on the API shape that is needed.
- [ ]  Doing the implementation for the cluster environment.
- [ ]  Doing the implementation for the local environment.

**Comment by ozevren** [comment]
@nmittler could you take a look at this when you have time?

**Comment by lichuqiang** [comment]
I have interest in this. But I'm lack of the background knowledge.
Seems we haven't make use of the Fortio Apps in existing tests for now?
So the task would be deciding how we make use of it, and add test cases accordingly?
