### ISSUE TITLE
[test-framework] Ensure that the port-forwarder lifecycle is limited.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6173]
The current port-forwarding logic in the test-framework launches kubectl as a process to forward ports. This has potential cleanup issues: if the user terminates the go test, or if there is a panic, then the clean up would not be executed and the port forwarder processes will keep running.

There are two potential solutions to this problem:

- Use the port-forwarder as a library (https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go)
- Use a wrapper around kubectl that checks for a heartbeat (e.g. a shell program that launches port-forwarder in the background and checks for timestamp/process list updates to detect if the test is running).

**Comment by lichuqiang** [comment]
@ozevren If you've not got time to start on this, I'd like to help
