### ISSUE TITLE
[test-framework] split out test.Tag call, so that it can be used independent of the framework.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6177]
We want the test.Tag mechanism to be usable by all tests in general. Currently, it is heavily bound to the internal mechanisms of the test framework.

**Comment by hklai** [comment]
@ozevren is it feasible to tag the whole file in addition to tagging individual tests or suite (TestMain)?

I suppose in most cases, the tags apply to the whole files for most tests (e.g. all tests belong to the networking, or all tests in the file are integration tests.)

**Comment by ozevren** [comment]
I think we should identify how the tag is going to be used first.

Here is the current execution logic:

Currently, the tag is being used for filtering decisions. The test.Tag method calls Skip(), if it decides that the test should be skipped, based on tags. For this to work, test itself needs to always call test.Tag.

The test.SuiteTag in TestMain is useful for adding common tags for all tests. It can be used to tag all tests within that suite.

With this in-mind, there is really no way to tag files themselves directly. We can invent new mechanisms, such as:

```golang
var fileTags = test.Tags(labels.Foo, labels.Bar, labels.Baz)
// ...
func TestBoo(t *testing.T) {
  test.Tag(fileTags)
  ...
```

This is similar to how log scopes work.

Would that be useful?

**Comment by hklai** [comment]
@ozevren 

> Currently, the tag is being used for filtering decisions. The test.Tag method calls Skip(), if it decides
> that the test should be skipped, based on tags. For this to work, test itself needs to always call 
> test.Tag.

I sort of remember a feedback in the prototype review was that it might make sense to decouple tagging and the filtering action. In other word, perhaps a test can call tag for labelling, but another method for the skip decision, so the semantic is more clear.  And therefore tagging can be moved to suite level or file level easily.

>The test.SuiteTag in TestMain is useful for adding common tags for all tests. It can be used to tag all
> tests within that suite.

How do the tests make the filtering decision then, if they do not need to call anything?


> With this in-mind, there is really no way to tag files themselves directly. We can invent new
> mechanisms, such as:
> var fileTags = test.Tags(labels.Foo, labels.Bar, labels.Baz)
> // ...
> func TestBoo(t *testing.T) {
>  test.Tag(fileTags)
>  ...
> This is similar to how log scopes work.
>
> Would that be useful?

Looks reasonable to me. In this case how does the test framework associate the labels with the right scope (file/method/etc)?

**Comment by ozevren** [comment]
I sort of remember a feedback in the prototype review was that it might
make sense to decouple tagging and the filtering action. In other word,
perhaps a test can call tag for labelling, but another method for the skip
decision, so the semantic is more clear. And therefore tagging can be moved
to suite level or file level easily.

We can do the split, but I don't think splitting in this way is highly
useful. It means, as a test author I'd be calling two methods, instead of
one, for every test I write. That's somewhat tedious. But functionally they
are equivalent. This doesn't change any suite/file level tagging behavior
though.

How do the tests make the filtering decision then, if they do not need to
call anything?

They need to call test.Tag (as the code currently stands). Even if there is
no additional tags, it can do the skip/pass based on the tags at the suite
level.

Looks reasonable to me. In this case how does the test framework associate
the labels with the right scope (file/method/etc)?
Through the test.Tag call within the test method? Each test within the file
would use the tags defined in the file.

**Comment by hklai** [comment]
> We can do the split, but I don't think splitting in this way is highly
useful. It means, as a test author I'd be calling two methods, instead of
one, for every test I write. That's somewhat tedious. But functionally they
are equivalent. This doesn't change any suite/file level tagging behavior
though.

Wouldn't it be a better experience if I normally just tag the whole file, and call a boiler plate function in the test function for the filtering decision? Then I don't need to think about the labels again in the test function, unless I want to change or override.

If labels are supposed to be very dynamic across different functions in the same file, then yes I agree with you, but I doubt that is not the majority use case. 


> They need to call test.Tag (as the code currently stands). Even if there is
no additional tags, it can do the skip/pass based on the tags at the suite
level.

It goes along with my point above. Having to tag again introduce a mental burden having to think about what label to use/reuse.

**Comment by ozevren** [comment]
Wouldn't it be a better experience if I normally just tag the whole file,
and call a boiler plate function in the test function for the filtering
decision? Then I don't need to think about the labels again in the test
function, unless I want to change or override.

Can you write a pseudo-coding showing how this would work?

**Comment by hklai** [comment]
Following your earlier example:


```
var fileTags = test.Tags(labels.Foo, labels.Bar, labels.Baz)
// ...
func TestBoo(t *testing.T) {
  // "Foo", "Bar", and "Baz" apply
  test.skipIfNotApplicable()
  ...
}
func TestBoo2(t *testing.T) {
  test.Tags(labels.Fancy)
  // "Fancy" applies (assuming override instead of additive behavior)
  test.skipIfNotApplicable()
  ...
}
```


In this case, all tests use the same set of tags unless they override in the test, like TestBoo2(). I am thinking most tests will be similar to TestBoo() instead. Am I making sense?

**Comment by ozevren** [comment]
How does Foo, Bar, Baz apply to the tests in this file only? The only way I
can think of is a singleton backing object. If I have another file that
goes into the same suite, wouldn't they collide (or rather, the union of
all labels will apply to all the tests in all the files in the suite)?

**Comment by lichuqiang** [comment]
I'd like to help with this, but I didn't find any `Tag` usage in existing code.
Can you give an example?

**Comment by hklai** [comment]
After multiple rounds of discussions, we killed the generic tagging as we were not able to find a clear use case that cannot be solved by build tag or packages.

For flakiness handling, we decided to use a specialized method and @JimmyCYJ is working on that.
