### ISSUE TITLE
[test-framework] integrate local registry support with test framework

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6178]
There is an ongoing work to integrate local-registry support to the existing test framework.

We also need the same integration to happen with the new test framework.

The PR for the current test-framework is here: https://github.com/istio/istio/pull/5855

In addition, the image loading/resolution algorithm when installing the image should work as follows:

- If nothing is specified, use local changes/bits with local registry
- Allow override of individual images from the command line.

**Comment by nmittler** [comment]
@sebastienvas does any of your recent work apply here? Would you be willing to take this on?

**Comment by sebastienvas** [comment]
yes on it.

**Comment by howardjohn** [comment]
I believe this is made obsolete by our use of [kind](https://kind.sigs.k8s.io). We just directly load the docker images, there is no registry required at all. If I misunderstand then feel free to reopen

**Comment by nmittler** [comment]
@howardjohn are we using kind for everything now? Or are there still jobs running on gke directly?

**Comment by howardjohn** [comment]
all integration tests are on kind and have been for a month or so. The only e2e jobs are multicluster and dashboard - just because they need some more effort, I am planning on moving them over as well

**Comment by nmittler** [comment]
ok sounds good ... yeah, closing this makes sense.
