### ISSUE TITLE
Invalid certificate on sidecar injector pods preventing deployment

### ISSUE THREAD

**Issue by Stono** [istio/istio#6186]
Hey, 
We've been running 0.8 since release, and today encountered our first issue which prevented deployments to a cluster.

We noticed that ReplicaSets from a Deployment rollout were failing to start the pods with the following error:

```
Warning  FailedCreate  3m (x17 over 8m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "k8s.cluster.local")
```

I deleted both instances of our sidecar injector pods to allow them to restart, and this solved the problem, so we have a mitigation, but i'd really like to ensure this doesn't happen again moving forward.

**Comment by vvangestel** [comment]
We've encountered the same issue, restarting the sidecar injector pod however doesn't solve it for us.

The installation was done using the helm chart and it's default values.
K8s was deployed with juju.

**Comment by costinm** [comment]
Dup #5947

**Comment by ostromart** [comment]
Closing duplicate.

**Comment by vvangestel** [comment]
Not sure if my case is a duplicate. The problem occurs immediately after a fresh helm install, not after reapplying any yaml. The caBundle field after calling `kubectl get MutatingWebhookConfiguration -o yaml` is also populated. The istio-sidecar-injector pod is not logging any errors. Restarting injector pods is also no solution for us.

**Comment by costinm** [comment]
Please add all as many details as possible to the main bug - it may be a
different cause, but same effect.
