### ISSUE TITLE
Do we have plan of providing  management WebUI for Istio?

### ISSUE THREAD

**Issue by rokii** [istio/istio#6189]
Just As K8s' WebUI dashboard:  https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#using-dashboard

**Comment by rshriram** [comment]
Check the kiali project? https://github.com/kiali/kiali

**Comment by rokii** [comment]
Great. It now just supports visualization but has plan to provide us the ability to manage Istio resource.

**Comment by yshemesh** [comment]
Istio should be the control-plane of Envoy. And as such it needs a more extensive web-UI.

**Comment by WestFarmer** [comment]
why this issue closed ? Does istio already have a management UI ?
