### ISSUE TITLE
Ansible Installer is not working for previous versions to 0.8.0

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#6190]
When you use ansible installer from master, with `istio.release_tag_version` with 0.7.1, it results on the following error.

> TASK [istio : Copy definition file] ********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cp", "~/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml", "/tmp/ansible.QlxBG3JcPb/def.yml"], "delta": "0:00:00.920507", "end": "2018-06-12 06:02:08.022152", "msg": "non-zero return code", "rc": 1, "start": "2018-06-12 06:02:07.101645", "stderr": "cp: cannot stat '/home/jenkins/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml': No such file or directory", "stderr_lines": ["cp: cannot stat '/home/jenkins/.istio/istio-0.7.1/install/kubernetes/istio-demo.yaml': No such file or directory"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/jenkins/workspace/install-istio/istio/install/ansible/main.retry

**Comment by sdake** [comment]
@gbaufake in PR https://github.com/istio/istio/pull/6144 @geoand is aware of this problem.

**Comment by geoand** [comment]
@gbaufake Can you please see if  #6144 fixes your problem?

**Comment by gbaufake** [comment]
@geoand 

I think it won't solve my problem since the backport for older versions will be dropped.

Checking the old branches may solve it (I have tested for 0.7.1 and it seems to be fine)

**Comment by geoand** [comment]
The PR will only work for `0.8`. I am pretty sure it won't work for older versions (although I haven't tried it)
