### ISSUE TITLE
Add circle-ci e2e-pilot-noauth-v1alpha3-v2 to master branch and mark as required

### ISSUE THREAD

**Issue by incfly** [istio/istio#6196]
When developing #6121 , we found the this test combo is not part of presubmit in master. We'll add it and mark it required.

**Comment by incfly** [comment]
For some reason the test is not running in the presubmit test, https://github.com/istio/istio/pull/6201.

This will block the PR merge, so temporarily remove it from "required."

**Comment by ostromart** [comment]
#5322 is from 6 weeks ago so it's not a valid data point. Disabling the entire test suite is a nuclear option, please skip any tests that are flaky and create issues for those.
