### ISSUE TITLE
book info instruction is confusing on clean up and next step

### ISSUE THREAD

**Issue by linsun** [istio/istio#620]
I got a user who complains to me that the book info instruction tells him to clean up, then what is next, which he just did the clean up and what is next actually needs the artifact deployed.

https://istio.io/docs/samples/bookinfo.html

**Comment by linsun** [comment]
More from the user:  another area that is confusing (to me at least)…
https://istio.io/docs/tasks/rate-limiting.html
This task shows you how to use Istio to dynamically limit the traffic to a service.
in the whats next area, the links are all to docs and not labs, but then it says if you aren’t doing any more tasks you can clean up bookinfo
maybe more is coming?
who knows :slightly_smiling_face:

My reply: it is a little confusing :slightly_smiling_face: 
if you follow the task flow, next task is enable simple access control (on the left menu)
which still uses bookinfo

**Comment by ldemailly** [comment]
is it better now ?
can we close this

(not release blocking either way)
