### ISSUE TITLE
Consider to remove authn-enable test suites

### ISSUE THREAD

**Issue by incfly** [istio/istio#6209]
After removing the inference from authn policy, all mTLS enabling is through authn policy and we plan to deprecate the global mesh config flag `AuthEnable`. We should make the e2e test aligned to reduce the maintenance overhead.  Couple of things need to address before purging them, based on discussion with @diemtvu :

- `AuthnEnable` also controls the control plane (pilot to sidecar) communication whether in mTLS or not.
-  Make sure TestHTTP/TCP/Grpc work as intended in the new settings. (aka have corresponding Authn policy and DR, still works)

**Comment by diemtvu** [comment]
This will be handled as part of https://github.com/istio/istio/issues/5900
