### ISSUE TITLE
Publish the .deb artifacts 

### ISSUE THREAD

**Issue by costinm** [istio/istio#622]
Auth, pilot and proxy generate .deb artifacts, they need to be published with the other binaries.

**Comment by sebastienvas** [comment]
Please help me here, in auth and pilot we have a release script https://github.com/istio/pilot/blob/master/bin/release.sh, could you make a script that is like 
./bin/upload-istioctl to upload the debian packages and add to the release script ?

**Comment by sebastienvas** [comment]
pkg_deb(
    name = "istio-node-agent",
    architecture = "amd64",
    built_using = "bazel",
    data = ":debian-data",
    description_file = "description",
    homepage = "http://istio.io",
    maintainer = "The Istio Authors <istio-dev@googlegroups.com>",
    package = "istio-node-agent",
    version = "0.2.1",
)

Hard coding the version in there, is not right. I need to find a better solution for this.

@wattli is working on updating the relase script for auth

**Comment by costinm** [comment]
It appears K8S is also hardcoding the version ( I used them as a template -
except for making the rules explicit instead
of using a .bzl file), and I believe it's common to manually upgrade the
version when moving to the next
release. Android does it too.

Will look at the scripts - already added the proxy deb to the script that
releases the artifacts, but need to
make sure it is plumbed all the way.

**Comment by costinm** [comment]
And I'll update the pilot script first thing tomorrow, thanks for the
pointer.

**Comment by sebastienvas** [comment]
Any update on this ?

**Comment by costinm** [comment]
Sorry, got stuck on other issues - and didn't find any good way to test my
change.
It's just a line change "gsutil -m cp -r
bazel-bin/tools/deb/istio-agent.deb
gs://istio-release/releases/"${TAG_NAME}"/deb" - but
not sure if permissions / directory / layout is right.

Same change needs to be done for the istio/auth/tools/deb package.

**Comment by rvkubiak** [comment]
@sebastienvas suggested updating the deb build rule to use a istio.VERSION file.  We update this file (at least for istio/istio) with a script as part of the release, so duplicating this for the Debian package version would match up well with the existing release process.

Example:
https://github.com/cloudendpoints/esp/blob/master/src/nginx/main/BUILD#L298

I'm going to start work on integrating the deb push into the release script.

**Comment by costinm** [comment]
SGTM - at this point I don't think the top priority is automatic update of
the version file but just getting the .deb published and working.
The deb files are built in auth, proxy and pilot repos - which don't have
same istio.VERSION.
We can have the 'unified build' with a single istio.VERSION in a later
version and update the version manually for now, or if you have a solution
for
using istio.VERSION and time - I would be happy to see it, but it's not
blocker.

**Comment by sebastienvas** [comment]
@costinm Is the debian package from Proxy the only package that is of value for the release ?

**Comment by sakshigoel12** [comment]
this should be done
