### ISSUE TITLE
`make lint` failed because of type alias in mixer

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6237]
Because of https://github.com/istio/istio/blob/master/pilot/pkg/networking/plugin/mixer/mixer.go#L39

```
type attribute = *mpb.Attributes_AttributeValue
```

Seems go 1.10.3 does not recognize this type alias.

```
/Users/gyliu/go/bin/goimports
/tmp/~output.go:37:16: expected type, found '='
make: *** [lint] Error 2
```
```
LiuGuangyas-MacBook-Pro:istio gyliu$ go version
go version go1.10.3 darwin/amd64
```

/cc @kyessenov

**Comment by kyessenov** [comment]
This should be assigned to whoever owns the linting in istio. Go 1.10.3 has no problem with type aliases (they were introduced in go 1.0).

**Comment by kyessenov** [comment]
Please delegate @hklai.

**Comment by hklai** [comment]
Looks like this has been fixed?
https://circleci.com/gh/istio/istio/159085
