### ISSUE TITLE
no matches for kind "DestinationPolicy" in version "config.istio.io/v1alpha1"

### ISSUE THREAD

**Issue by ozevren** [istio/istio#6261]
@fleeto commented on [Sat Apr 14 2018](https://github.com/istio/issues/issues/288)

**Is this a BUG or FEATURE REQUEST?:**

**Did you review https://istio.io/help/ and existing issues to identify if this is already solved or being worked on?**:

Y

**Bug:**

Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**

```
istioctl version: 0.7.1
kubectl version: 1.10.1
kubernetes version: 1.8.11
```

**Is Istio Auth enabled or not ?**
Did you install the stable istio.yaml, istio-auth.yaml....  or if using the Helm chart please provide full command line input.

No

**What happened**:

```
kubectl apply -f httpbin/destinationpolicies/httpbin-circuit-breaker.yaml                    [11:03:39]
error: unable to recognize "httpbin/destinationpolicies/httpbin-circuit-breaker.yaml": no matches for kind "DestinationPolicy" in version "config.istio.io/v1alpha1"
```

```
istioctl create -f httpbin/destinationpolicies/httpbin-circuit-breaker.yaml                  [11:04:09]
Created config destination-policy/istio-workload/httpbin-circuit-breaker at revision 627702
```

**What you expected to happen:**

**How to reproduce it:**

```
kubectl apply -f httpbin/destinationpolicies/httpbin-circuit-breaker.yaml
istioctl create -f httpbin/destinationpolicies/httpbin-circuit-breaker.yaml

```

**Feature Request:**

N

**Describe the feature:**

---

@fleeto commented on [Sat Apr 14 2018](https://github.com/istio/issues/issues/288#issuecomment-381376838)

https://github.com/istio/istio/blob/master/samples/httpbin/destinationpolicies/httpbin-circuit-breaker.yaml

**Comment by rshriram** [comment]
Please upgrade to 0.8 and use DestinationRule instead.

**Comment by ozevren** [comment]
The sample needs to be updated.
