### ISSUE TITLE
Retire istio/issue repo

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#6266]
We're not getting real value out of having istio/issue as a separate repo. It just leads to additional administration overhead. We should just use istio/istio to track all issues. It'd be great to nail this before 1.0 ships so we're on the right plan for all the new customers.

We should move all issues to the istio/istio repo, and then we can delete the istio/issue repo. We'll need to change a few "report a bug" links on istio.io accordingly.

@louiscryan @smawson @linsun @rshriram

**Comment by smawson** [comment]
+1, I think it had value when we had lots of repos, now that we have istio/istio as a monorepo it is fairly worthless.

**Comment by rshriram** [comment]
+1. But let’s please not move and create more duplicates. Let the leads triage and close or manually copy the relevant issues or link to an existing issue. Meanwhile we can lock down the issues repo

**Comment by geeknoid** [comment]
I'll go ahead and change the "report a bug" links to point to istio/istio.
I'll also move the template from istio/issue to istio/istio.

**Comment by geeknoid** [comment]
So:

- Bug reporting links now point to istio/istio/issues

- We now use GitHub's new templating controls. When you click "New Issue" in istio/istio, you now get asked whether you want to report a bug or a request a new feature, and you get type-appropriate templates.

- The issue template on istio/issues was updated with a link to the istio/istio repo asking people to post issues there instead.

**Comment by jasmine-jaksic** [comment]
@rshriram I understand why you don't want to move them in bulk but the flip side is people opening new entries in the issues repo. As an example, 3 new ones were opened in the last 24 hours. 

Not to mention we currently have ~160 open issues in that repo. It took 11 of us about 3 hours to close ~100 issues yesterday, I'm not sure when we will have a dedicated triage session next time. Why don't we move them all to istio/istio, achieve the issues repo and have leads continue to triage their areas over time?

**Comment by geeknoid** [comment]
Moving issues between repos unfortunately lose all labels. So they would
have to be reapplied.

**Comment by geeknoid** [comment]
The repo has been renamed to old_issues_repo, and description+template were updated to point people to istio/istio, so we're as close as we can get to deleting the repo outright, without moving items.
