### ISSUE TITLE
Retire istio/api repo.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#6267]
We've got general agreement on the team that having istio/api as a distinct repo is a burden with no significant upsides and many downsides. We should just merge its contents to an api directory in the istio/istio repo.

@louiscryan @smawson @linsun @costinm @hklai

**Comment by kyessenov** [comment]
There is auto-generated python code there now. What do we do about it?

**Comment by kyessenov** [comment]
Another thing to keep in mind: proxy depends on bazel build in istio/api. That's not going away anytime soon since envoy is committed to bazel. We'd need to bazelify istio/istio as a result of this.

**Comment by rshriram** [comment]
You can mirror the contents of the api folder into istio/api. There is little need to draw in bazel back into istio/istio.

**Comment by kyessenov** [comment]
Mirroring is fine, but then you still need to get bazel files from somewhere, and they should come from the source, which is istio/istio.

**Comment by rshriram** [comment]
if I copy istio/api into istio/istio, can I simply keep the bazel files within the api/ folder? if not, i nominate you for the task. :)

**Comment by kyessenov** [comment]
I think we thought you signed up for the task. You need to put bazel files in the root of the repo, since that's what bazel expects.

**Comment by qiwzhang** [comment]
Proxy can create  "api" folder which is just the mirror of "istio/istio "api" folder.  Put bazel files inside the "api" folder.

**Comment by kyessenov** [comment]
@qiwzhang @geeknoid are we open to moving proxy into istio as well? We can go monorepo all the way.... Combining api and istio creates a vicious dependency cycle istio <-> proxy.

**Comment by geeknoid** [comment]
​So what benefits do we get by the current split?​

**Comment by lizan** [comment]
The most benefits is for people depends on API only and don't want to pull huge istio/istio repo for just APIs. Within istio that is proxy and I don't know if there are outside interests.

In last [mail thread](https://groups.google.com/forum/#!msg/istio-dev/znLqMD-j-4o/Ab55pnY_CQAJ) the general agreement is making istio/istio as source of truth, and have nightly job to sync it to istio/api.

**Comment by hklai** [comment]
Are we still going to pursue this?
