### ISSUE TITLE
APAs, referenced attributes, and caching

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6275]
In policy checks, proxies can reliably report UID attributes of the pods they belong to. Mixer then applies APAs to derive the rest of the metadata (workload names, services, labels, etc). If the policy references any of the derived metadata, then the resulting referenced attribute returned to the proxy is not useful as a cache key, as the proxy cannot derive the same metadata.

I think we should allow APA to make the inference for some immutable attributes be implicit. APA should erase references to workload name for example, provided UID is known to the proxy, since the relationship between the two is immutable. Then proxy can apply an effective cache key for that policy.

/cc @douglas-reid @mandarjog @geeknoid

**Comment by douglas-reid** [comment]
I think this would be very useful. We had some design discussions around better plumbing attribute use / derivation characteristics through APAs, etc. awhile back. Unfortunately, I think we only ended up addressing the low-hanging fruit. IIRC, this was part of it. Being able to track attribute derivation is definitely on our TODOs.
