### ISSUE TITLE
istio-pilot/api-server pod restart lots times in nine days

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#6276]
istio-pilot pod restart 60 times in nine days

ENVIRONMENT
- istio version: 0.8.0
- auth disabled
- k8s 1.9.5

![image](https://user-images.githubusercontent.com/17720035/41392839-9dfc4fc8-6fd5-11e8-92f8-85431b54fcd6.png)

[istio-pilot.log](https://github.com/istio/issues/files/2100901/istio-pilot.log)

**_kubectl describe pod istio-pilot-6c5c6b586c-z4th8 -n istio-system_**
[describe_pod_istio-pilot_env1.txt](https://github.com/istio/istio/files/2101039/describe_pod_istio-pilot_env1.txt)

**_kubectl logs -n istio-system istio-pilot-6c5c6b586c-z4th8  --previous --timestamps_**
[istio-pilot_previous.log](https://github.com/istio/istio/files/2101055/istio-pilot_previous.log)

'''
2018-06-12T11:25:16.4091304Z 2018-06-12T11:25:16.408895Z warn Neither --kubeconfig nor --master was specified. Using the inClusterConfig.
'''

**Comment by johnzheng1975** [comment]
**_Another environment:_**
Restart 2 times in latest 2 day.

![image](https://user-images.githubusercontent.com/17720035/41393858-4b794256-6fda-11e8-8f25-eeae009cd1a1.png)


kubectl describe pod istio-pilot-6c5c6b586c-2cbnk -n istio-system
Name:           istio-pilot-6c5c6b586c-2cbnk
Namespace:      istio-system
Node:           ip-10-202-83-150.ec2.internal/10.202.83.150
Start Time:     Mon, 11 Jun 2018 09:59:55 +0000
Labels:         istio=pilot
                pod-template-hash=2717261427
Annotations:    cilium.io/identity=37155
                sidecar.istio.io/inject=false
Status:         Running
IP:             10.222.73.201
Controlled By:  ReplicaSet/istio-pilot-6c5c6b586c
Containers:
  discovery:
    Container ID:  docker://6b2193720e0de48e356246048d3f0bbf10203a1249eb898b308dbf8946fff825
    Image:         docker.io/istio/pilot:0.8.0
    Image ID:      docker-pullable://istio/pilot@sha256:c9203d3d56aff27e12d43fb3882608fac49f56e6205cb12962cb8f04c1f29b44
    Ports:         8080/TCP, 15010/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      discovery
    State:          Running
      Started:      Tue, 12 Jun 2018 01:20:39 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 11 Jun 2018 09:59:56 +0000
      Finished:     Tue, 12 Jun 2018 01:19:22 +0000
    Ready:          True
    Restart Count:  1
    Readiness:      http-get http://:8080/v1/registration delay=30s timeout=5s period=30s #success=1 #failure=3
    Environment:
      POD_NAME:            istio-pilot-6c5c6b586c-2cbnk (v1:metadata.name)
      POD_NAMESPACE:       istio-system (v1:metadata.namespace)
      PILOT_THROTTLE:      500
      PILOT_CACHE_SQUASH:  5
    Mounts:
      /etc/certs from istio-certs (ro)
      /etc/istio/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-pilot-service-account-token-k52mm (ro)
  istio-proxy:
    Container ID:  docker://47df8599676cf03e2831ed27b79ad96a3dfe6809d0e058c8d395ac0c7c67103b
    Image:         docker.io/istio/proxyv2:0.8.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:1930f0603321b1917b2249c576ecb4141aaceeaae5fcc0760b6a88dc88daea3e
    Ports:         15003/TCP, 15005/TCP, 15007/TCP, 15011/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      --serviceCluster
      istio-pilot
      --templateFile
      /etc/istio/proxy/envoy_pilot.yaml.tmpl
      --controlPlaneAuthPolicy
      NONE
    State:          Running
      Started:      Tue, 12 Jun 2018 01:20:39 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 11 Jun 2018 09:59:57 +0000
      Finished:     Tue, 12 Jun 2018 01:19:22 +0000
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:       istio-pilot-6c5c6b586c-2cbnk (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
    Mounts:
      /etc/certs from istio-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-pilot-service-account-token-k52mm (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  false
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-pilot-service-account
    Optional:    false
  istio-pilot-service-account-token-k52mm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-pilot-service-account-token-k52mm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>

**Comment by johnzheng1975** [comment]
Environment | Run time | Restart Count | Note
-- | -- | -- | --
Dev1b | 18 h | 0 | Istio 0.7.1  +   Cilium v1.0.0-rc12
QA1c | 9 d | 60 | Istio 0.8.0  + v1.1.0-rc3   (restart may cause by my testing last week, re-deploy   new services thousands of times)
QA1b | 1 d | 0 | Istio 0.7.1  +   Cilium v1.0.0
Stage1b | 18 h | 0 | Istio 0.8.0  + v1.1.0-rc3
Stage1c | 2 d | 2 | Istio 0.8.0  + v1.1.0-rc3
Prod1b | 9 h | 0 | Istio 0.8.0  + v1.1.0-rc3
Prod1c | 17h | 0 | Istio 0.8.0  + v1.1.0-rc3

**Comment by johnzheng1975** [comment]
Thanks Romain (from cilium team) may found root reason from log, FYI
2018-06-12T11:25:16.4091304Z 2018-06-12T11:25:16.408895Z    warn    Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

**Comment by costinm** [comment]
That message is normal( well, confusing and needs to be clened up, but harmless). It only means in-cluster config is used, with no override - which is normal behavior.
