### ISSUE TITLE
Is it currect or normal that I can't visit each POD or Service by Pod ip or Cluster ip with Istio0.7 installed?

### ISSUE THREAD

**Issue by Yisaer** [istio/istio#6278]
Hello , I installed Istio0.7 and prometheus and I found that prometheus can't visit each pod by pod ip with istio enabled , so is it currect that we can't visit pod by pod ip with Istio enabled?

**Comment by Yisaer** [comment]
you mean it is correct that i can't acces pod by pod ip with istio enabled. @ymesika

**Comment by ymesika** [comment]
You should be able to access the service by its ClusterIP but not a pod by its ClusterIP.
