### ISSUE TITLE
Istio 0.8.0 EnvoyV2 memory consumption is too high

### ISSUE THREAD

**Issue by icowan** [istio/istio#6283]
# Istio 0.8.0 EnvoyV2 Memory consumption is too high

### istio 0.7.1

![](https://ofbudvg4c.qnssl.com/images/k8s/15289807430340.jpg)

Kubernetes version: v1.10.0

### istio 0.8.0

![](https://ofbudvg4c.qnssl.com/images/k8s/15289807832139.jpg)

Kubernetes version: v1.10.3

**Comment by andraxylia** [comment]
cc @ldemailly @mandarjog

**Comment by ldemailly** [comment]
it’s pilot and shows the data - ptal?

**Comment by icowan** [comment]
@ldemailly no, it's heapster plugin.  and linux command: `top` to same.

**Comment by PiotrSikora** [comment]
Presumably this is a duplicate of #7912? This should be fixed in 1.1.

**Comment by icowan** [comment]
问题依旧在
