### ISSUE TITLE
[Ansible] Prometheus file is not being located

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#6286]
**Describe the bug**
Installing Istio using Ansible on master is not working because prometheus file is not being located

> TASK [istio : Add ServiceAccount to prometheus add-on] *************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path /home/jenkins/.istio/istio-0.8.0/install/kubernetes/addons/prometheus.yaml does not exist !", "rc": 257}
	to retry, use: --limit @/home/jenkins/workspace/Istio-Upstream/istio/install/ansible/main.retr

Full log attached: 
[ansible.log](https://github.com/istio/istio/files/2103285/ansible.log)

**Expected behavior**
Istio should be installed

**Steps to reproduce the bug**
`ansible-playbook main.yml -e '{"istio": {"release_tag_name": "0.8.0", "auth": false, "delete_resources": true}}`

**Version**
istio: `0.8.0`

**Is Istio Auth enabled or not?**
istio auth is not enabled

**Environment**

- RHEL 7

**Comment by gbaufake** [comment]
cc @ymesika @sdake @gyliu513 @geoand

**Comment by geoand** [comment]
At the risk of sounding like a broken record, have you tested if  PR #6144 solves the problem?

**Comment by geoand** [comment]
The istio (demo) installation has changed a lot in `0.8.0` and the PR is meant to address the various issues (while also dropping any notion of backward compatibility)

**Comment by geoand** [comment]
@gbaufake In the PR you will see that most of the add-ons have been dropped, including Prometheus. That's because the Istio demo installation now adds them by default and therefore there is no need for the playbook to perform any special handling

**Comment by gbaufake** [comment]
@geoand Right. Your PR #6144 
Sorry for not trying this first before open this issue.

A little detail:
> TASK [istio : Delete Addons] ***************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "'istio_all_addons' is undefined"}
...ignoring

> TASK [istio : Delete Addon ServiceAccounts] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "'istio_all_addons' is undefined"}
...ignoring

`istio_all_addons` is not defined I think... should this step be mainted on your PR or should this variable be defined?

Best Regards

**Comment by geoand** [comment]
Good catch!

I didn't check the delete stuff! I will update the PR soon to fix the
issue.
Thanks for reporting this!

**Comment by gbaufake** [comment]
@geoand Did you push it? I've not seen it.

**Comment by geoand** [comment]
The change should be in the `delete_resources` file. 
I see as part of the changes in the PR

**Comment by gbaufake** [comment]
It is there.

Thank you!

**Comment by geoand** [comment]
Thank you for spotting the issue!!!

**Comment by ymesika** [comment]
Seems to be resolved by #6592 / #6144.
Reopen if it's not.
