### ISSUE TITLE
pilot-postsubmit.sh fails with: bin/toolbox/pkg_coverage.sh no such file  

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#631]
https://k8s-gubernator.appspot.com/build/istio-prow/pilot-postsubmit/87/

W0830 20:13:30.694] prow/pilot-postsubmit.sh: line 57: bin/toolbox/pkg_coverage.sh: No such file or directory
E0830 20:13:30.694] Build failed
I0830 20:13:30.694] process 348 exited with code 1 after 2.5m
E0830 20:13:30.695] FAIL: pilot-postsubmit

**Comment by sebastienvas** [comment]
@chxchx Could you please look into this ?

**Comment by chxchx** [comment]
@yutongz has been working on a fix but have a hard time merging since pilot/master has been red. He will take over from here.

**Comment by ldemailly** [comment]
it seems the UI showing an outdated branch is missing in pilot repo

is there a / command to rebase a PR - seems there is  some chicken and egg / deadlock where the presubmit fails because it needs rebase but it won't rebase because the pre submit failed ?
talking about https://github.com/istio/pilot/pull/1168

**Comment by yutongz** [comment]
Need rebase should not be the reason for the presubmit failure. As we mentioned couple times before: Prow will rebase before run tests: 
https://github.com/istio/test-infra/tree/master/mungegithub#stage-two

If you take a look at full logs, you can see the rebase processes:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1168/pilot-presubmit/808/
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1168/pilot-presubmit/809/

I am with, I am also confused why I rebased and then it passed. But it seems pilot-presubmit is flaky? I don't know. Let's rerun presubmit multiple times to find it out.

**Comment by ldemailly** [comment]
I didn't know prow silentely rebased, my bad. maybe that's why I have a pr with a mysterious error. 

maybe having some indication or way to actually do the rebase would help the humans.


this being said we should keep the UI anyway - specially given pilot bots have been "disabled"
