### ISSUE TITLE
Enable Citadel manage a group of namespaces

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6312]
**Is your feature request related to a problem? Please describe.**
In 0.8, we can use external CA key and certificate according to here https://istio.io/docs/tasks/security/plugin-ca-cert/ .

The question is if I have multiple services and I want different services use different key and cert, how to achieve this?

I can start multiple citadel services, but how to let different workload use different citadel services?

I can see that the citadel has a parameter which can define the flag that is it listening via `listened-namespace`, so I can define which namespace that I want the citadel to monitor.

But the problem is that now I can only define one namespace for listened-namespace, this is not convenient for me to manage a large cluster with customized CA.

**Describe the solution you'd like**
Enable Citadel can manage a group of namespaces.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

/cc @wattli @lei-tang

**Comment by wenchenglu** [comment]
@gyliu513 
thank you for reporting this feature request. I wonder if you mind discussing this use case in the next Istio Security community meeting, and we can decide the priority and start design to support this use case. We may also ask contribution from community :)

In particular, I am interested in the overall story for this use case including network and monitoring. For example:
(1) do you also plan to run Pilot&Mixer to monitor the same set of namespaces as monitored by CA? 
(2) do you still need services to communicate with each other when their key/certs are issued by different CAs?
(3) what isolation model are you looking for when using namespaces to divide teams?

**Comment by gyliu513** [comment]
@wenchenglu thanks for the comments. Please check my answers as below. I want to attend the meeting as well but it is too late for me.

> (1) do you also plan to run Pilot&Mixer to monitor the same set of namespaces as monitored by CA?

Sorry, not clear for this question. Do you mean we can also configure the namespace to be managed by Pilot and Mixer? I do not know this feature, can you please show more detail for this?

> (2) do you still need services to communicate with each other when their key/certs are issued by different CAs?

Yes. But for this case, as long as I can provide the root ca, private key and cert chain, it should works?

> (3) what isolation model are you looking for when using namespaces to divide teams?

I was doing as follows, each group is map to a team and each team can have multiple namespaces.

DevTeam
  |
  | - namespace1  (has its own services)
  |
  | - namespace2  (has its own services)
  |
  | - namespace3  (has its own services)


TestTeam
  |
  | - namespace4  (has its own services)
  |
  | - namespace5  (has its own services)
  |
  | - namespace6  (has its own services)

**Comment by clyang82** [comment]
`listened-namespaces` will be supported in this PR - #11667
