### ISSUE TITLE
5s refresh on 6h dashboard (Istio HTTP/GRPC Service Dashboard ) results in strange UI

### ISSUE THREAD

**Issue by Stono** [istio/istio#6318]
Hey @douglas-reid 
Another observation on the new dashboards for you.

I have a service which gets infrequent (10-20 Reqs per minute) so I set the dashboard to a 6h interval, but left the 5s refresh enabled.

What this results in is a totally different looking graph every 5 seconds, guessing to do with the way the data is being sampled?  I'm not sure. Either way it results in a totally different view of the world for people looking at the same 6h window (eg Person A opens 6h, Person B opens 6h, one of them might see 500's, the other might not).

EG:
5s (shows some 500s):
<img width="1920" alt="screen shot 2018-06-15 at 14 28 39" src="https://user-images.githubusercontent.com/1486729/41470549-ce730650-70a8-11e8-9c4e-bebd129d73e6.png">

Next 5s (no 500s):
<img width="1920" alt="screen shot 2018-06-15 at 14 28 46" src="https://user-images.githubusercontent.com/1486729/41470559-d339c462-70a8-11e8-8fb5-c6682d5b5b15.png">

Next 5s:
<img width="1920" alt="screen shot 2018-06-15 at 14 28 50" src="https://user-images.githubusercontent.com/1486729/41470567-d744a5cc-70a8-11e8-812c-a3fd0f7adb18.png">

Ta
Karl

**Comment by douglas-reid** [comment]
@Stono It probably does have something to do with sampling rate and the querying. If you are feeling adventurous, you could try editing the queries and change `irate` to `rate` and possibly extending the window of time in the calculation and see what the impact is.

I hope to spend more time with the dashboards soon. I'll try out a few things to see if this can be improved. 5s is nice for demos and stuff, but I don't know if we need that kind of refresh rate in prod as the default.
