### ISSUE TITLE
Figure out multi namespace / multi control plane / mesh configuration

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#632]
For 0.3 we need to solve the bootstrap configuration issue for the side cars

For testing (at least and also probably (tbd?) for production use cases) we want to support

multiple sets of multiple namespaces using 1 istio control plane and config in the same cluster
(and also multi cluster meshes eventually)

Right now the way the sidecar finds pilot and mixer is by assuming there is a mounted configmap coming from the namespace - that doesn't scale well with dozens of namespaces

See https://github.com/istio/pilot/issues/1153 and https://github.com/istio/pilot/issues/1154 for some 0.2 background

Note: even if we don't want to support multiple meshes in prod, the bootstrap can use streamlining and shouldn't require copying a configmap in each namespace (imo)

**Comment by andraxylia** [comment]
This is not a scale problem with dozens or event hundred of namespaces unless proven otherwise. It happens as a namespace is created. 
This issue jus makes an opinion, and does not propose an alternate viable and better proposal. I will leave it open for tracking for the first few weeks of 0.3, and close it if nothing better is proposed.

**Comment by andraxylia** [comment]
This should also be moved to pilot.

**Comment by ldemailly** [comment]
There is relevant discussion in newly filled https://github.com/istio/pilot/issues/1272 but this issue is istio wide not only pilot related

**Comment by andraxylia** [comment]
This is no longer an issue.

**Comment by ldemailly** [comment]
it's only no longer an issue if we don't want to support multiple control planes in a cluster

**Comment by andraxylia** [comment]
No concrete plans for multiple control planes, so let's re-open if/when needed, so we can focus on the ones we are working on.

**Comment by ldemailly** [comment]
sgtm / agreed

**Comment by msogrin** [comment]
> This is no longer an issue.

@andraxylia Could you please elaborate on the solution/conclusion/workaround/change_of_direction/etc?

**Comment by ldemailly** [comment]
@msogrin we fixed the unnecessary config map copying part of the issue (the bug/perf/scale issue)

and for now we are assuming istio watches all your namespaces in any given namespace
