### ISSUE TITLE
istio-remote deploy failed when zipkin is disabled

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6322]
Please get more detail from https://github.com/istio/istio/pull/6127#issuecomment-397601409

I think the solution is we need add a parameter to check if we need to add zipkin endpoint or not.

/cc @sdake @tiswanso

**Comment by tiswanso** [comment]
I created a general istio-remote issue with handling services in #6321 

IMO, we should either all but the absolutely essential services optional via not setting endpoint defaults in the values.yaml and checking if the value is set OR using helm subcharts and tags/conditions to include/exclude service manifests.

**Comment by gyliu513** [comment]
Thanks @tiswanso , let me close this one and trace it in your ticket.
