### ISSUE TITLE
mixer-postsubmit fails due to timeout: //pkg/config/crd:go_default_test

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#633]
https://k8s-gubernator.appspot.com/build/istio-prow/mixer-postsubmit/96/

Most likely cause: test size is too big to run. I'm assigning this to sebastienvas@ ++ to investigate how tests like these ought to be structured to avoid becoming too large for testing.

I0831 18:54:25.812] Executed 53 out of 53 tests: 52 tests pass and 1 fails locally.
I0831 18:54:25.812] There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
W0831 18:54:25.815] TIMEOUT: //pkg/config/crd:go_default_test (see /home/bootstrap/.cache/bazel/_bazel_bootstrap/2ba7a783f3c05b4605aea2aadf54c5cd/execroot/com_github_istio_mixer/bazel-out/local-fastbuild/testlogs/pkg/config/crd/go_default_test/test.log)
W0831 18:54:25.815] ____From Testing //pkg/config/crd:go_default_test:
W0831 18:54:25.815] ____Elapsed time: 79.872s, Critical Path: 64.09s
E0831 18:54:25.815] Build failed

**Comment by sebastienvas** [comment]
@gnirodi  This can be fixed by marking the test as large, or by changing the the test. Please assign this to the creator of the test.

**Comment by jmuk** [comment]
It shouldn't take that much, and so I'm afraid that `size="large"` wouldn't solve the problem, anyways it would fail. Maybe it's some test flake. I'll check on my side.

**Comment by jmuk** [comment]
My PR was merged. I believe this fixes this issue.

**Comment by gnirodi** [comment]
Not sure if this entirely fixed this issue: See
https://k8s-gubernator.appspot.com/build/istio-prow/mixer-postsubmit/114/

This is today's post submit in response to:
https://github.com/istio/mixer/commit/ed6e995d78203aacd420a1e12b4600d568a463dc

**Comment by jmuk** [comment]
Another fix for this was merged yesterday, so far it seems working. Can we close this?

**Comment by sebastienvas** [comment]
yes thanks!
