### ISSUE TITLE
[Github Wiki] Adapter wiki with broken image links

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#6343]
**Describe the bug**
The image links are broken in the following wiki explaining the adapter architecture
https://github.com/istio/istio/wiki/Mixer-Adapter-Dev-Guide

**Expected behavior**
Correct links in HTML to the images

**Steps to reproduce the bug**
Go to https://github.com/istio/istio/wiki/Mixer-Adapter-Dev-Guide

Please reassign to relevant bucket if required.

**Comment by geeknoid** [comment]
Fixed.
