### ISSUE TITLE
Supporting TLS interception between workload and sidecar proxy

### ISSUE THREAD

**Issue by elevran** [istio/istio#6355]
**Is your feature request related to a problem? Please describe.**
Customers have requested support for TLS between the application and sidecar proxy.
This would:
- avoid dependencies' URL configuration changes (e.g., when using a "client SDK" that does not support it. A recent example discussed was gRPC using Go which always uses h2s, but there are quite a few client libraries that only accept credentials and not a target URL)
- comply with a requirement that "all communication must be encrypted" (including the localhost namespace)

**Describe the solution you'd like**
introduce an optional *local* proxy CA functionality to Istio:
1. upon startup, the proxy generates a new root certificate and copies it to a path (e.g., volume) accessible to the application
1. the application explicitly imports the root CA when starting up
1. the proxy sniffs the TLS handshake to generate a new certificate based on the client's SNI, signed with with the proxy CA

**Describe alternatives you've considered**
There are several alternatives for supporting this including, for example:
- extending client libraries: this might prove a large community effort (e.g., supporting gRPC over h2c in Go); forking the original library may not always be desirable/possible
- Using kernel TLS: requires kernel 4.17 or later and changes to traffic interception used by Istio (e.g,. a-la Cilium's syscall interception and socket buffers)

**Additional context**
Please see https://drive.google.com/file/d/1KaOZPa58iLuo6yvCuaw_JjDya3nrD_rY/view?usp=sharing
and messages in https://groups.google.com/forum/#!topic/istio-users/M0qU3NUxYEM

**Comment by elevran** [comment]
[Design specification](https://docs.google.com/document/d/1TTl8OszfnUEkBmz5AtcUCyYRTT7O6axiHZabHdH2950/edit?usp=sharing.) submitted for review

**Comment by gyliu513** [comment]
@elevran can you please show some detail for what do you mean of `TLS between the application and sidecar proxy.`?

Does not the current mTLS support this https://istio.io/docs/tasks/security/mutual-tls/#verify-requests ? With current mTLS, I can access an application from a pod which has a sidecar proxy running in it.

**Comment by elevran** [comment]
@gyliu513 currently the application workload must use clear text to communicate with the world, so that the proxy can provide request routing, per request metrics, etc.
mTLS works between proxies (and by extension, between workloads), but not between the workload and the sidecar proxy itself:
- workload--(`cleartext`)->proxy--(`mtls`)->proxy--(`cleartext`)->workload; or 
- workload--(`cleartext`)->proxy--(`tls`)->world

We had a customer requirement to *encrypt the workload->proxy communication* as well. The community feedback to the design proposal (see links above) indicated that we should not move forward with the proposed design. The issue is left here to see if there is still a need to support and if there are alternative ways to implement the requirement in a manner that would be more acceptable.

**Comment by linouxis9** [comment]
Are there been any updates on this matter? Thanks a lot!
