### ISSUE TITLE
Error Adding Listener

### ISSUE THREAD

**Issue by infinitydon** [istio/istio#6356]
**Describe the bug**
I am getting the following errors from the istio sidecars:

```
[2018-06-18 12:06:33.618][12][warning][config] external/envoy/source/server/listener_manager_impl.cc:378] error adding listener: 'http_100.96.2.19_8080' has duplicate address '100.96.2.19:8080' as existing listener
[2018-06-18 12:06:33.618][12][warning][upstream] external/envoy/source/server/lds_subscription.cc:68] lds: fetch failure: error adding listener: 'http_100.96.2.19_8080' has duplicate address '100.96.2.19:8080' as existing listener
```

How do I troubleshoot/resolve this? What is the impact of this error?

**Version**
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean


kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler
```

**Is Istio Auth enabled or not?**
No

Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

Installed via istio.yaml

**Environment**
AWS kops

**Comment by andraxylia** [comment]
Could you please attach the following info?

kubectl get all 

istioctl proxy-config pilot mesh ads

For the pod with IP 100.96.2.19:
istioctl proxy-config endpoint <pod-name>

**Comment by infinitydon** [comment]
Sorry, I deleted the installation when I did not get a response on time and recreated from scratch..

Will re-open if I face the issue again.
