### ISSUE TITLE
Add install template for sidecar initializer 

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#636]
We introduced sidecar initializer at https://github.com/istio/pilot/issues/335 , should enable it as a deployment here.

/cc @ayj comments?

**Comment by ayj** [comment]
Yes, that's the plan. It needs to be done in two steps: (1) enable initializer deployment (w/ConfigMap) and (2) enable InitializerConfiguration. (1) needs to be running in all test instances across the shared clusters before (2) to avoid namespaces without a corresponding initializer.

**Comment by gyliu513** [comment]
@ayj for this issue, I think that I only need to add (1) a new deployment file for initializer and (2) a InitializerConfiguration , which test shall I run in istio?

**Comment by ayj** [comment]
https://github.com/istio/istio/blob/master/tests/e2e.sh

Don't enable the InitializerConfiguration by default in the changes pushed to Github just yet. Its fine to test locally but we need to phase-in this feature to avoid breaking tests in the shared cluster.

**Comment by ayj** [comment]
https://github.com/istio/istio/blob/master/tests/e2e.sh

Don't enable the InitializerConfiguration by default in the changes pushed to Github just yet. Its fine to test locally but we need to phase-in this feature to avoid breaking tests in the shared cluster.

**Comment by andraxylia** [comment]
This is done.
