### ISSUE TITLE
Pilot discovery output log format question

### ISSUE THREAD

**Issue by jsenon** [istio/istio#6367]
**Describe the bug**
Does istio-pilot and container discovery log in JSON format?

**Expected behavior**
N/A

**Steps to reproduce the bug**
```
kubectl logs istio-pilot-7966858769-rvj4s  discovery
```

**Version**
1.0: istio-master-20180615-09-15

**Is Istio Auth enabled or not?**
not

**Environment**

```
istio-pilot-7966858769-rvj4s discovery 2018-06-18T20:12:06.274070Z	warn	requeuing dummy, err services "istio-ingress" not found
```

**Comment by ldemailly** [comment]
this looks like a question - also please use a descriptive subject

try emailing istio-users@ ?

**Comment by jsenon** [comment]
Sry, I ve updated subject.

**Comment by ldemailly** [comment]
1.0 is not out yet, I assume you mean some pre release or a daily build or build from master, can you specify which it is ?

also what are you asking exactly ? is it how to get logs in json ? or about that services "istio-ingress" not found warning ?

**Comment by ldemailly** [comment]
please also clarify #6369 as well

**Comment by jsenon** [comment]
I'm not talking about `warn`, I'm just talking about log format that seems not to be in JSON format that will generate issue if we need to scrap/parse it.

**Comment by jsenon** [comment]
My bad output is JSON formatted, log is set by pkg/log which is zapper
