### ISSUE TITLE
Secure Ingress via Traffic Management API fails

### ISSUE THREAD

**Issue by kvudata** [istio/istio#6371]
**Describe the bug**
Tried to setup Ingress by following the 0.8 docs, secure ingress fails with a `curl: (35) Server aborted the SSL handshake` error.

**Expected behavior**
Able to follow the docs and connect securely.

**Steps to reproduce the bug**
Follow the directions here: https://istio.io/docs/tasks/traffic-management/ingress/, got stuck at "Verifying the gateway for HTTPS".

**Version**
```
] istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
] kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.1", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-05-11T17:16:56Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Not enabled, installed via `helm template ~/src/istio-0.8.0/install/kubernetes/helm/istio --name istio --namespace istio-system > /tmp/istio.yaml && kubectl apply -f /tmp/istio.yaml`

**Environment**
GKE k8s v1.9.7-gke.1.
Istio v0.8

**Comment by vadimeisenbergibm** [comment]
Could you please provide the output of `kubectl get svc -n istio-system`, `istioctl get gateway -o yaml`, `echo $INGRESS_PORT`, `echo $INGRESS_HOST`, `echo $SECURE_INGRESS_PORT`.

**Comment by prune998** [comment]
@kvudata I had an issue also, using the OsX `curl`. Can you confirm your curl version and OS ?

**Comment by kvudata** [comment]
@vadimeisenbergibm, here are the requested outputs:
```
14:12 $ kubectl get svc -n istio-system
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                                                               AGE
istio-citadel              ClusterIP      10.19.242.21    <none>           8060/TCP,9093/TCP                                                     3d
istio-egressgateway        ClusterIP      10.19.244.210   <none>           80/TCP,443/TCP                                                        3d
istio-ingress              LoadBalancer   10.19.246.188   35.197.77.101    80:32000/TCP,443:32088/TCP                                            3d
istio-ingressgateway       LoadBalancer   10.19.246.148   35.233.203.100   80:31380/TCP,443:31390/TCP,31400:31400/TCP                            3d
istio-pilot                ClusterIP      10.19.247.192   <none>           15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   3d
istio-policy               ClusterIP      10.19.241.219   <none>           9091/TCP,15004/TCP,9093/TCP                                           3d
istio-sidecar-injector     ClusterIP      10.19.247.41    <none>           443/TCP                                                               3d
istio-statsd-prom-bridge   ClusterIP      10.19.244.103   <none>           9102/TCP,9125/UDP                                                     3d
istio-telemetry            ClusterIP      10.19.254.217   <none>           9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 3d
prometheus                 ClusterIP      10.19.253.181   <none>           9090/TCP                                                              3d

14:13 $ istioctl get gateway -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: httpbin-gateway
  namespace: ing-test
  resourceVersion: "610829"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpbin.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - httpbin.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---

14:13 $ echo $INGRESS_PORT
80

14:14 $ echo $INGRESS_HOST
35.233.203.100

14:14 $ echo $SECURE_INGRESS_PORT
443
```

@prune998, I'm using curl `curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8` on OS X 10.12.6

**Comment by vadimeisenbergibm** [comment]
@kvudata The values you shared seem correct. And do you use `curl --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST -HHost:httpbin.example.com -I -k https://httpbin.example.com:$SECURE_INGRESS_PORT/status/200` to test your ingress?

Additional check to perform, run `kubectl exec -it -n istio-system $(kubectl -n istio-system get pods -l istio=ingressgateway -o jsonpath='{.items[0].metadata.name}') -- ls -al /etc/istio/ingressgateway-certs` and check if you have `tls.key` and `tls.crt` in `/etc/istio/ingressgateway-certs`

**Comment by prune998** [comment]
@kvudata don't use OSX `curl`...  use a linux curl or go with https://httpie.org/

**Comment by kvudata** [comment]
@prune998, wow, you're right! I tried using a linux curl (used the `radial/busyboxplus:curl` image) and it works!

**Comment by vadimeisenbergibm** [comment]
@kvudata @prune998 Strange, I use OS X curl and it works for me:
```
curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by vadimeisenbergibm** [comment]
@kvudata So if it works for you, could you please close the issue?

**Comment by kvudata** [comment]
Looks like my curl is slightly different:
```
$ curl --version
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by kvudata** [comment]
@vadimeisenbergibm, it seems like there is some sort of compatibility issue here (I haven't done anything special with my version of curl) - perhaps worth calling out in the tutorial / FAQ?

**Comment by vadimeisenbergibm** [comment]
@kvudata I see now - it is `SecureTransport` vs `LibreSSL`. I will document it in the task.

**Comment by vadimeisenbergibm** [comment]
@kvudata I have added a commit to address this https://github.com/istio/istio.github.io/commit/91dc65d2bcb7232524cc3f1f7c151e889d7cc361.
