### ISSUE TITLE
Single command to dump out state of entire mesh for debugging

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6382]
istioctl proxy-config is an excellent tool. It allows to query pilot for ads delivered to all proxies:

istioctl proxy-config pilot mesh ads 

It allows to query the actual Envoy config on a specific proxy (localhost:15000/config_dump) with a command like this

istioctl proxy-config endpoint pod-name

It would be great to add a "all" command that can get the 
- config_dump from all Envoys 
-the pilot ads config
- kubectl get all --all-namespaces
-anything else we need , depending on the  platforms

I would like to use a single command like "istioctl proxy-config all" , and redirect it to an archive utility and get all the troubleshooting info I need.

Later, I would like an option to have hyperlinks, so I can browse listeners etc from a web browser (this is covered by #2751 )

I would also like to request users to get a snapshot of their istioctl proxy-config after installing istio, and a snapshot if an issue arrises,  so we can compare the two. This could be automated.

**Comment by andraxylia** [comment]
cc @douglas-reid @sakshigoel12

**Comment by liamawhite** [comment]
It definitely would be useful! I'm in the process of trying to simplify the `proxy-config` command into something a bit more user friendly based on feedback from people.

I would suggest this functionality has its own dedicated command. That way users don't have to remember some magic incantation of flags to get an entire dump and we don't overload `proxy-config`. I've been refactoring some  of the interfaces so most of the code required is now in re-usable libraries anyway.

A simple `istioctl mesh-dump [<archive-name>]` that dumps all Envoy config dumps into an archive of one per file is probably a good starter point. We can then advance to hyperlinking in the next iteration.

**Comment by andraxylia** [comment]
@liamawhite sgtm

**Comment by andraxylia** [comment]
At a minimum we need reasonable documentation.
