### ISSUE TITLE
Make sure a test case covers test services out of control plane NS

### ISSUE THREAD

**Issue by ymesika** [istio/istio#6391]
Investigate why the fix of #6349 wasn't covered by any tests when testing #6133.
If there is no test to cover it, add/modify one.

**Comment by ymesika** [comment]
Not stale

**Comment by cmluciano** [comment]
@ymesika Do you have an update on this test-failure status?

**Comment by duderino** [comment]
@ymesika any update?

**Comment by ymesika** [comment]
No update. Sorry didn't notice I was assigned to this preventing from others to pick it up.
