### ISSUE TITLE
Wrong HOST_IP command in documentation if minikube 0.28.0 isused

### ISSUE THREAD

**Issue by scheu** [istio/istio#6399]
**Describe the bug**
When running the latest minikube (v0.28.0), the instruction for obtaining the HOST_IP does not work (https://istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports)

The command
```
export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o 'jsonpath={.items[0].status.hostIP}')
```
should be replaced with the following if running minikube:
```
export INGRESS_HOST=$(minikube ip)
```

On my machine, the first statement produces the incorrect IP 10.0.2.15 and the second statement produces the correct IP 192.168.99.100.

**Expected behavior**
See above

**Steps to reproduce the bug**
Run the bookinfo-sample with minikube 0.28.0

**Version**
istio version 0.8.0
kubectl 1.10.4
minikube 0.28.0

**Is Istio Auth enabled or not?**
No auth

**Environment**
MAC OS

**Comment by cesarlbf** [comment]
I opened a PR to try to fix the docs: https://github.com/istio/istio.github.io/pull/1553

**Comment by cesarlbf** [comment]
Newer mini-kube seems to provide a internal ip when run:  `kubectl get po -l istio=ingressgateway -n istio-system -o 'jsonpath={.items[0].status.hostIP}'`

> Based on Kubernetes API:
> `status.hostIP`(string) | IP address of the host to which the pod is assigned. Empty if not yet scheduled.
-- | --
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/

I think minikube is using its VM IP in some scenarios, that is not how it exposed on the `vboxnet0`.

**Comment by cesarlbf** [comment]
Merged! Waiting updates to reflect on the public website, before closing it.

**Comment by cesarlbf** [comment]
Updated! +1
