### ISSUE TITLE
prometheus and statsd exporter should be at release version

### ISSUE THREAD

**Issue by ostromart** [istio/istio#6400]
prometheus and statsd exporter are currently at latest in istio.yaml templates. They should be at a release tag to ensure reproducability.

**Comment by hklai** [comment]
I am generally in favor of fixing the versions instead of using latest as well.

However, the telemetry team owns these dependencies and it is up to them to decide what version is used, so I suppose @douglas-reid is the rightful owner.

**Comment by douglas-reid** [comment]
What is the specific concern re: reproducability ?  These are add-ons, and should not impact core Istio features.

That being said, I'm fine with pointing them at release versions.

My concern would be that it is generally fairly easy to forget about the release version, leaving us lagging behind security patches, etc., for the addons.  Is that something we could manage as part of the release cycle @hklai ?  What checks do we have in place for making sure deps are up-to-date -- and can we apply that process to this as well?

**Comment by ostromart** [comment]
They're used extensively throughout tests, so if you go back in time and rerun a test the behavior may be different than it was originally. Also having latest cedes all control of versions, so bad releases can be introduced into the mix in customer clusters in an uncontrolled way. I agree it's less likely to cause trouble with prometheus specifically but it still seems like a solid principle to follow.
I don't think this is any different than managing any other dependency which we are already doing.

**Comment by hklai** [comment]
Right. These should be the same as any other dependencies, and hard wiring the versions in gopkg makes releases more deterministic. (i.e. we won't pick up a different version when we cut a patch release a month later, for example).

Currently there is no global dependencies update process, as it most likely will need to be evaluated on a case by case basis.
