### ISSUE TITLE
e2e/integration tests should run with multiple namespaces

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#6404]
to avoid a repeat of #6363 we should have most e2e tests not run the test apps in the istio-system namespace

I think having 4 namespaces would be a realistic setup that tests functionality:
- 1 namespace for control plane (whether we want to test for the ability to change this from istio-system to something else is debatable - it should work elsewhere but I'm afraid it doesn't)
- 1 auto injected namespace for some services (e.g. `app1`)
- 1 istioctl kube-injected namespace for some services (e.g. `app2`)
- 1 non injected namespace (e.g. `noistio`)

and the tests should check that both intra and cross namespace communication between services in all 3 work

cc @kyessenov

**Comment by kyessenov** [comment]
This is circle-specific. Prow runs the normal workflow (components in istio-system, apps in its own namespace).

**Comment by ldemailly** [comment]
that's good, but eventually we should cover the 3+1 namespaces I suggest
