### ISSUE TITLE
[perf swat] produce profiling data

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#6409]
one of the items for 

https://docs.google.com/document/d/1TiMmzbM5r9QlBfs79owBqiAZJgflMyXa3Zuev7xZKSc/edit#

is to rerun the scenarios to produce profiling information for the fortio max ingress -> s1 (mixer call not cached case)
e.g https://fortio.istio.io/?xMin=&xMax=&xLog=false&yLog=false&sel=qps_max-ingress_to_s1-0.7.1-2018-04-05-22-04
as a first step

**Comment by louiscryan** [comment]
Pinging to keep alive as this is still valid.
