### ISSUE TITLE
install/updateVersion shouldn't require -xfoo (when using the natural -x foo it inserts a bogus space)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#642]
See https://github.com/istio/istio/pull/641/commits/8e30a37b827a392621f1aadecdb4ed5005a91e74#diff-bd1aae3c2854764f1c73dabf2af617a7R5

when running
```
install/updateVersion.sh -x gcr.io/istio-testing,f043c7ea6bf68cb1603a7e17e9e1b3ac8b568859
```
you get
```
export MIXER_HUB=" gcr.io/istio-testing"
```
with a bogus leading space

**Comment by ldemailly** [comment]
also -p should imply -i

eg shouldn't need to do
```
install/updateVersion.sh -pgcr.io/istio-testing,fb947d4c6d0902a841e0e82ffa3bee16786be0df -i https://storage.googleapis.com/istio-artifacts/pilot/fb947d4c6d0902a841e0e82ffa3bee16786be0df/artifacts/istioctl
```

to change the pilot sha (which drives the istioctl sha) - at least by default

**Comment by rcurran1** [comment]
Having trouble reproducing. 

Downloaded istio (git clone https://github.com/istio/istio) to two different OS systems ("Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11)" and "Linux version 3.13.0-68-generic (buildd@lgw01-46) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) )")
Testing against tag 0.2.7 (from "git describe --tags --abbrev=0") Also tested against some older tags.
After execting "install/updateVersion.sh -x gcr.io/istio-testing,f043c7ea6bf68cb1603a7e17e9e1b3ac8b568859"
$ more istio.VERSION | grep MIXER_HUB
export MIXER_HUB="gcr.io/istio-testing"

Please add more information to this issue on how to reproduce.

**Comment by ldemailly** [comment]
looks like someone fixed it since
and we want to get rid of updateVersion anyway
