### ISSUE TITLE
pre submit should catch that install/updateVersion.sh must be a noop

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#643]
pre submit should catch that install/updateVersion.sh must be a noop
and that people haven't not manually edited the generated files
(like accidentally happened in #623 )

**Comment by ldemailly** [comment]
we wasted hours because of this

ideally actually we just wouldn't check in all those generated files and just make them for the release or even better generate them with variable substitution and flags from a program (istioctl generateConfig or such)

**Comment by ldemailly** [comment]
another example:
https://github.com/istio/istio/pull/815

**Comment by ldemailly** [comment]
@sebastienvas is there a quick/easy fix here ?

**Comment by sebastienvas** [comment]
Yes better code reviews

**Comment by sebastienvas** [comment]
Just kidding, yes that should be easy to check.

**Comment by ldemailly** [comment]
verified in https://github.com/istio/istio/pull/823
thank you
