### ISSUE TITLE
Rationalize use of MessageName and TypeURL in galley code

### ISSUE THREAD

**Issue by ayj** [istio/istio#6437]
This is a cleanup item for the new Galley code. We use both MessageName and TypeURL to name protobuf types. ~~We should align on using MessageName and TypeURL should be abstracted away in the MCP layer.~~

_edit_: we should align on using TypeURL consistently throughout galley and MCP code. We originally thought it would be useful to hide the TypeURL encoding but that turned out to not provide much benefit.

**Comment by lichuqiang** [comment]
@ayj So you'd suggest we update MCP to not rely on TypeURL for supportedTypes validation, so that we can get rid of TypeURL in galley runtime?
Or like @ozevren [suggested](https://github.com/istio/istio/pull/6425#discussion_r196921068), we'd keep MCP as is, and only some inner update for galley?(that is, we will still need TypeURL to talk to MCP)

**Comment by ayj** [comment]
We should use TypeURL throughout MCP and Galley code. I updated the original issue to reflect this change.

**Comment by lichuqiang** [comment]
Thanks! took a closer look at the code, seems we've already use TypeURL in MCP server and most of Galley logic, the parts that still related to MessageName are:
1. The logic to get goType via typeUrl, which makes use of `proto.MessageType`, I think the part difficult to modify, and we'll still need MessageName here.
2. the MCP client. A downside is that users will have to pass in fully qualified resource names if we update this part. I can't decide if it worthwhile.

Let me know if I missed somehing

**Comment by ayj** [comment]
We've mostly switched over to TypeURL already but, as you've noted, there are few places in the MCP client and server codes that still use MessageName in their exported APIs. 

> The logic to get goType via typeUrl, which makes use of proto.MessageType, I think the part difficult to modify, and we'll still need MessageName here.

That should be fine. `github.com/gogo/protobuf/proto` package uses message name but everything above that in MCP layers can use TypeURL. The `istio.io/istio/galley/pkg/runtime/resource` package has helper methods to get the message name the few times it is need when interacting with the gogo proto packages.

> ... the MCP client. A downside is that users will have to pass in fully qualified resource names if we update this part. I can't decide if it worthwhile.

The upside is consistency between galley, the MCP client users, MCP implementation, and over-the-air encoding all using the TypeURL. A whole class of problems is largely avoided, i.e. "do I need to use MessageName or TypeUrl" for this API.

**Comment by ayj** [comment]
No, not yet. `gen-meta` is already auto-generating types.go files with typeURL which is good enough for now.

**Comment by ozevren** [comment]
Should this item be closed now? Is there anything left?

**Comment by ayj** [comment]
This is done for now.
