### ISSUE TITLE
[Adapter] Guidance on building a private mixer adapter

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#6448]
**Is your feature request related to a problem? Please describe.**
I would like to use a create a private custom template and adapter and use with Mixer. From my understanding of the dev guide, the way to build an adapter that would be private is to
1. Fork istio to a private repository
2. Add new template and adapter to the package
3. Define them in `istio/mixer/template/inventory.yaml` and `istio/mixer/adapter/inventory.yaml`

Private repository creates overhead every time istio has to be updated.

**Describe the solution you'd like**
Is there a way to do this without forking istio to a private repository? Is there a better approach to doing this that I am not considering?

**Comment by douglas-reid** [comment]
@adityats2020 There is a much better way. The approach involves using the newly-supported gRPC adapters. There is work right now on adding the appropriate dev guide.

**Comment by adityats2020** [comment]
That sounds much better indeed!
Has there already been an adapter developed using gRPC I can take a look while the dev guide is being worked on?
Can you also link the issue tracking the work?
