### ISSUE TITLE
document how to run tests/e2e.sh on minikube (ie -use_local_cluster)

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#645]
Right now, the tests setup ingress as type LoadBalancer and check for an external IP address to be assigned.
This does not work on minikube, so it should be removed or adapter.

We need to run and debug the e2e smoke test  outside of the test cluster.

**Comment by ldemailly** [comment]
is that with -use_local_cluster ?

**Comment by andraxylia** [comment]
Cool, that works. In that case, the option -use_local_cluster needs to be documented in README, with some explanation about what it does related to ingress svc type.

**Comment by ldemailly** [comment]
yes I mentioned in some code review when I saw it that it wasn't clear what it meant etc
(in a way this is a sub task of https://github.com/istio/istio/issues/593 )
