### ISSUE TITLE
Istio webhook config should use informer/watch to monitor caBundle

### ISSUE THREAD

**Issue by ostromart** [istio/istio#6451]
Currently, as a mitigation to https://github.com/istio/istio/issues/6069, the CA bundle in the webhook config is periodically checked and re-patched in case it becomes reset (by for example reapplying istio.yaml).
The mitigation is https://github.com/istio/istio/pull/6435
The periodic check should be converted to use informer/watch.

**Comment by lichuqiang** [comment]
Is this still an issue?
If so, I'd like to help improve this :)

**Comment by jwendell** [comment]
proposed fix: https://github.com/istio/istio/pull/8886
