### ISSUE TITLE
Telemetry for pilot xDS streaming

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#6458]
With envoy v2, we lost metrics of sidecar's xDS request, because non-mtls traffic goes to pilot grpc port directly without going through sidecar. Besides that, we don't have good support for http streaming telemetry https://github.com/istio/proxy/issues/1828. Suggest to revive pilot metrics after istio-proxy adds grpc streaming telemetry report.

cc @costinm @douglas-reid @kyessenov

**Comment by douglas-reid** [comment]
I'm not sure why we opted out of the proxy for non-mTLS traffic. That seems like a step backwards -- and one that was not done with the requisite changes to monitoring configuration for dashboards, etc. It also significantly impacts the ability to route telemetry for Pilot through Mixer, undoing work that has been marked as complete on our roadmap for a long time now.

cc: @andraxylia 

I think all of this means that we need to disable large sections of the Pilot dashboard -- pending suitable replacements.

**Comment by andraxylia** [comment]
@costinm had a reason for bypassing the proxy.

**Comment by rshriram** [comment]
Even with the proxy in between, you won't get any useful metrics. You simply get info that the ADS call was made and not about the individual resources requested in each call. Pilot is emitting the same metrics internally (as prometheus metrics). We can stream these metrics to the dashboard, if that helps..

**Comment by kyessenov** [comment]
Custom metrics will not be handled by mixer adaptors. That's why we want to
emit the default limited metrics. The missing details in metrics is an
istio limitation that we should all be working towards fixing, since the
same arguments apply to application level metrics.

**Comment by douglas-reid** [comment]
@rshriram yeah, we are going to have to make sure that we have a source for those metrics.

I do want to point out that this isn't just about metrics. This also means we've lost access logs for Pilot (and any other sort of information that could be generated from `Report()` calls, including trace, edge, and other known templates).

The switch to streaming gRPC certainly would have impacted us as well, but a little something is still marginally better than nothing.

In any case, we need to update the dashboards, track further changes, and document that Pilot is no longer using Istio for monitoring (i think this undoes release notes from 0.8).

**Comment by kyessenov** [comment]
This is probably no longer relevant without a sidecar. Let's close this and open a more general one for h2/grpc streaming metrics.

**Comment by kyessenov** [comment]
ref https://github.com/istio/istio/pull/7251

**Comment by kyessenov** [comment]
ref https://github.com/istio/istio/issues/7259
