### ISSUE TITLE
Pilot: Support filtering svc/pod through label

### ISSUE THREAD

**Issue by rokii** [istio/istio#6461]
**Is your feature request related to a problem? Please describe.**
I donnot want pilot to fill envoy with all the svc/endpoint in k8s.
And I am sure my pods with istio-proxy will never access certain services.

**Describe the solution you'd like**
Current Pilot only supports restriction of  watching one ns through _appNamesapce_ param.
Can it be enhanced to support filtering svc/endpoint/pod to be watched by label？

**Comment by andraxylia** [comment]
@rokii Do you have a particular scale, or have you noticed problems? Or is it more of a theoretical proposal?

We have plans to add similar functionality in the future, but not before 1.0.

**Comment by rokii** [comment]
@andraxylia  We have lots of applications deployed in k8s. Now some teams want to adopt Istio. And many applications like data mining or ML jobs  are not services and will never join the mesh. So it is better to have Istio just manage and list limited endpoints.  In the long run , we may have dedicated k8s cluster for Istio service mesh. But in the initial phase , operation could be cost effective if we reuse current cluster. 
I agree that it is neither blocking issue nor urgent.

**Comment by andraxylia** [comment]
@rokii thanks for the clarification.

**Comment by nrshrivatsan** [comment]
Given Istio is `1.0` now, I do vote for @rokii point of not auto-populating all `service` & `endpoints` into Envoy Config.

It only make sense to have a istio listen on a specific `set of namespaces`.

If not, should support `ignore-namespaces`
