### ISSUE TITLE
Return more meaningfull HTTP error code for mTLS 

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#6462]
**Is your feature request related to a problem? Please describe.**
Istio authentication (especially with mTLS) have different error code returns:
- If request is plain text, and server expect mTLS, the request is rejected with 000 (due to TLS handshaking failure)
- If request is TLS, but server is expecting plain text, return code is 503 (service not found).
- Last but not least, if connection is made, but request is rejected by authn filter, return code is 401 (which is the right code) 

**Describe the solution you'd like**
It would be best if we can change all of them to return 401, with message to explain why.

**Comment by gyliu513** [comment]
Thanks @diemtvu for opening this, for more detail, please refer to https://github.com/istio/istio/issues/6180#issuecomment-396761980
