### ISSUE TITLE
istioctl version maybe mismatched?

### ISSUE THREAD

**Issue by bechampion** [istio/istio#6466]
Hey guys im testing a number of things specifically egress , and during the chart installation im finding this on kube-inject
```
~/Projects/istiotest$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

~/Projects/istiotest$ istioctl kube-inject -f httpbin.yaml  -i default
Error: failed to convert to proto. unknown field "egressProxyAddress" in v1alpha1.MeshConfig
```

I've installed istio using helm on incubator and this is the chart version:
```
~/Projects/istiotest$ helm search istio
NAME            CHART VERSION   APP VERSION     DESCRIPTION
incubator/istio 0.2.13-chart4   0.2.12          Istio Helm chart for Kubernetes
```

I'm sure there's a mismatch between istioctl and the chart i've deployed since the "egressProxyAddress" value that it's complaining about is on the configmap:

```
~/Projects/istiotest$ k get configmap istio -o yaml | egrep egress
    egressProxyAddress: istio-egress.default:80
```

Running all this on minikube with kubernetes-version v1.10.0 with RBAC

Thank you!

**Comment by esnible** [comment]
The _egressProxyAddress_ was removed from istio/api on Feb 8. 
 Clusters running versions before Feb 8 may expose this when using _istioctl_ post Feb 8, 
 https://github.com/istio/api/commit/b5d35aad98bedc3757f3fa76d50ae0b0dacca426#diff-e7424aa96af1917e2a00aea6798dc071

**Comment by bechampion** [comment]
Thank you. Had some success running the chart on master and pointing images to gcr.io
