### ISSUE TITLE
istio-mixer-post-install first run fails

### ISSUE THREAD

**Issue by ymesika** [istio/istio#6470]
When installing Istio using helm the istio-mixer-post-install job is being triggered but the first try fails:
```sh
istio-mixer-post-install-dcfxt              0/1       Error       0          2m
istio-mixer-post-install-drlr7              0/1       Completed   0          1m
```

The log from the failed run says that it got timeout:
```sh
2018-06-21 16:01:16.371423 I | proto: duplicate proto type registered: google.protobuf.Any
2018-06-21 16:01:16.371646 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-06-21 16:01:16.371869 I | proto: duplicate proto type registered: google.protobuf.Timestamp
attributemanifest "kubernetes" created
stdio "handler" created
logentry "accesslog" created
rule "stdio" created
metric "requestcount" created
metric "requestduration" created
metric "requestsize" created
metric "responsesize" created
metric "tcpbytesent" created
metric "tcpbytereceived" created
prometheus "handler" created
rule "promhttp" created
rule "promtcp" created
kubernetesenv "handler" created
rule "kubeattrgenrulerule" created
rule "tcpkubeattrgenrulerule" created
kubernetes "attributes" created
destinationrule "istio-policy" created
destinationrule "istio-telemetry" created
Error from server (Timeout): error when creating "/tmp/mixer/custom-resources.yaml": Timeout: request did not complete within allowed duration
```

**Comment by kyessenov** [comment]
This is likely an issue with helm/installation/upgrade, so environments WG is more appropriate.

**Comment by sdake** [comment]
Note I ran into this today.  The logs were:
```
sdake@falkor-07:~/go/src/istio.io/istio$ kubectl logs istio-mixer-post-install-lk88h -n istio-system
2018-06-23 19:33:16.399417 I | proto: duplicate proto type registered: google.protobuf.Any
2018-06-23 19:33:16.399559 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-06-23 19:33:16.399585 I | proto: duplicate proto type registered: google.protobuf.Timestamp
rule "promtcp" created
kubernetesenv "handler" created
rule "kubeattrgenrulerule" created
rule "tcpkubeattrgenrulerule" created
kubernetes "attributes" configured
destinationrule "istio-policy" created
destinationrule "istio-telemetry" created
Error from server (InternalError): error when creating "/tmp/mixer/custom-resources.yaml": Internal error occurred: failed calling admission webhook "mixer.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitmixer?timeout=30s: dial tcp 10.110.174.153:443: getsockopt: connection refused
```
With the last line spewed hundreds of times.  after 2 or 3 restarts, the pod started up correctly.

**Comment by sdake** [comment]
@ayj is this a startup ordering issue related to galley?

**Comment by ymesika** [comment]
Sleep or even request timeout is just a temporary solution because each platform is different than the other in the time it takes to bring up the various components.
We need to figure a way to have dependencies between the helm charts as galley needs to available before starting the other charts. I will look into what Helm has to offer.

**Comment by ayj** [comment]
The security and mixer post-install jobs both use `restartPolicy: Never`. Shouldn't we be using `OnFailure`? That would limit the number of outstanding failed jobs and avoid pod re-scheduling.

**Comment by sdake** [comment]
The latest TOC notes list Kubernetes 1.9 and 1.10 as the supported versions, however, other versions should work (YMMV).

**Comment by ymesika** [comment]
@sdake Good decision. Can we move to Hyperkube 1.9.x then?

**Comment by sdake** [comment]
@ymesika I'll ask the TOC mailer for a commitment so we aren't left guessing and get back to you.

Cheers
-steve

**Comment by ayj** [comment]
> We need to figure a way to have dependencies between the helm charts as galley needs to available before starting the other charts

https://github.com/istio/istio/pull/6648 adds an explicit dependency check between the custom-resource jobs and galley.

**Comment by andraxylia** [comment]
I just hit this issue with 06/27 daily and k8s 1.10.4.

It's not ok to ship with one of the install components failing.

**Comment by andraxylia** [comment]
It actually recovers after a while, but still not ok.

**Comment by ayj** [comment]
A proper installer or controller (e.g. operator) would help. The current install flow is not orchestrated and relies on some post-install jobs (w/bash scripts) which eventually converge to the right state.

**Comment by markns** [comment]
I also ran into this with the following helm install command: 

```
helm install --name istio install/kubernetes/helm/istio --namespace istio-system \  
                                                   --set global.mtls.enabled=false \
                                                   --set global.controlPlaneSecurityEnabled=true \
                                                   --set global.proxy.includeIPRanges=$INCLUDE_IP_RANGES \
                                                   --set global.proxy.resources.requests.cpu=10m \
                                                   --set global.proxy.resources.requests.memory=64Mi \
                                                   --set global.proxy.resources.limits.cpu=100m \
                                                   --set global.proxy.resources.limits.memory=128Mi \
                                                   --set gateways.istio-ingressgateway.enabled=true \
                                                   --set gateways.istio-egressgateway.enabled=false \
                                                   --set ingress.enabled=false \
                                                   --set prometheus.enabled=false \
                                                   --set galley.enabled=false \
                                                   --set global.imagePullPolicy=Always \
                                                   --set global.tag=1.0.0-snapshot.0
Error: timed out waiting for the condition
```
However, in my case the istio-mixer-post-install job never completed, and the helm install command timed out.

```
istio-mixer-post-install-hmfg2   0/1       Error     4         1m
istio-mixer-post-install-hmfg2   0/1       CrashLoopBackOff   4         1m
istio-mixer-post-install-hmfg2   1/1       Running   5         3m
istio-mixer-post-install-hmfg2   0/1       Error     5         3m
istio-mixer-post-install-hmfg2   0/1       CrashLoopBackOff   5         3m
```

There were also no logs at all in the istio-mixer-post-install pod.

1.10.4-gke.2

**Comment by ayj** [comment]
@markns, this should be fixed by https://github.com/istio/istio/pull/6682 which is included in the 1.0 release branch (e.g. https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180706-09-15).

**Comment by Parvathy-Geetha** [comment]
I am getting this issue with the 1.0.0 bits.

**Comment by thedevelopnik** [comment]
This is coming up for me in an EKS cluster using 1.0

**Comment by alphashaw** [comment]
The same with 1.1.0
