### ISSUE TITLE
Mesh Config Protocol Client in Pilot

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6473]
Mesh Config Protocol client in Pilot

Part of Pilot Decomposition Epic #6471 

Generic client that registers with one or more MCP servers; offers an interface that allows interested observers to sign up for notifications on certain object types
upon receiving incoming protobuf data from the wire, builds a heterogenous list of objects with their type and notifies interested observers by looping through the list of objects and list of observers and calling the add/update/delete handler
does not typecast to individual objects, so it stays generic

**Comment by andraxylia** [comment]
cc @ayj @ozevren

**Comment by ayj** [comment]
I'm working on a generic client that addresses these requirements. Finishing up the unit test and then I'll post for review in a day or so.

**Comment by ayj** [comment]
This should be addressed by https://github.com/istio/istio/pull/8192. We'll need a follow-up issue to track Pilot merging configuration from multiple sources into a single config store.
