### ISSUE TITLE
Add file-based support to Galley MCP server

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6479]

**Comment by andraxylia** [comment]
cc @ayj

**Comment by andraxylia** [comment]
not stale.

**Comment by loewenstein** [comment]
Could I run Galley without k8s dependency (i.e. on a VM and with no kube-api configured) serving Istio config from file system once this issue is resolved?

**Comment by ozevren** [comment]
Yes for Galley, specifically. But bear in mind that the primary driving scenario is testing at this point. As such, the current format is going to be based on Kubernetes resource format.

As for downstream components, they may still retain some API Server dependency.

**Comment by costinm** [comment]
Pilot can already run with files only (and has for a while - see ads tests)

Costin

**Comment by ozevren** [comment]
Implemented: https://github.com/istio/istio/pull/8831
