### ISSUE TITLE
Galley convert from k8s resources to Mesh Config APIs over MCP

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6480]
This includes CRDs, as well as Services and Endpoints.

**Comment by andraxylia** [comment]
not stale

**Comment by ozevren** [comment]
Galley does the conversion of CRDs now. Do we need services & endpoints for a minimum viable implementation? If not, any objections to track it separately?

**Comment by andraxylia** [comment]
As discussed a while ago, for an MVP we need the Gateway, VirtualService and DestinationRules, which Pilot now considers CRDs.

Let's track separately ServiceEntry in #7698 and AuthenticationPolicy in #6481 .
