### ISSUE TITLE
Define authn scheme for Pilot Decomposition

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#6481]
Auth is currently defined as a CRD. Galley has to read the CRDs and convert it to MCA securely.

Strawman options: 
co-locate galley alongside Pilot, Mixer, etc. and use gRPC over UDS (intermediate option only)
mTLS between Galley and components 
mTLS with additional ACLs, e.g. components only allowed to receive config within their domain (functional, organizational, etc)

**Comment by andraxylia** [comment]
not stale

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/7881 adds mTLS support with a basic list ACL using pod identity.

**Comment by ozevren** [comment]
For 1.1, we're using mTLS with limited ACLing support & file based certs. For 1.2, we will integrate with SDS.

Moving to 1.2

**Comment by ozevren** [comment]
Subsumed by https://github.com/istio/istio/issues/11787
