### ISSUE TITLE
Integration Test Step from the Adapter Walkthrough guide is not working

### ISSUE THREAD

**Issue by vinayvenkat** [istio/istio#6490]
**Describe the bug**
I followed all the steps outlined in the following link:
https://github.com/istio/istio/wiki/Mixer-Adapter-Walkthrough

All the steps worked great. However, I wanted to implement a test to locally test out my adapter. 
However, running that command does not seem to:

 (1) run the test when the full command is run. 
     i.e go build ./... && go test adapter/mysampleadapter/*.go
     This just seems to run the build which seems to pass, but does not execute the test. 

    The out.txt file does not get populated. 

 (2) when I run the test command separately: i.e   go test adapter/mysampleadapter/*.go

     I get the following error:
ec2-user@se-summit mixer]$ go test adapter/mysampleadapter/*.go
# command-line-arguments
adapter/mysampleadapter/mysampleadapter_test.go:25:13: undefined: server.NewArgs
FAIL	command-line-arguments [build failed]

**Expected behavior**

   The expectation is for the mysampleadapter_test.go file to execute and spit out data in the 
   out.txt file. 
   However, this file does not get created. 

**Steps to reproduce the bug**

1. Create the mysampleadapter_test.go file and populate it with the code shown.
2. run the build and test command:
 go build ./... && go test adapter/mysampleadapter/*.go

**Environment**
The environment is Centos Linux with local development. i.e checked out and built the istio project and trying to run locally as described by the Adapter Walkthrough example documentation.

**Comment by vinayvenkat** [comment]
@guptasu Any guidance here would be greatly appreciated. 

Thank you also to your comments on the other thread with examples. You referenced tests there and hence I decided to start here and this is failing. Thanks!

**Comment by guptasu** [comment]
@vinayvenkat let me take a look.

**Comment by guptasu** [comment]
@vinayvenkat this is fixed now

**Comment by guptasu** [comment]
please review the walkthrough again

**Comment by vinayvenkat** [comment]
@guptasu Thank you for looking it and getting back to me so quickly! 

I tried it and now I am getting the following errors:

[ec2-user@se-summit mysampleadapter]$ ls
config  mysampleadapter.go  mysampleadapter_test.go  testdata
[ec2-user@se-summit mysampleadapter]$ ls testdata/
attributes.yaml  mysampleadapter.yaml
[ec2-user@se-summit mysampleadapter]$ go build ./... && go test *.go
# command-line-arguments
./mysampleadapter_test.go:72:22: unknown field 'GetConfig' in struct literal of type test.Scenario
FAIL	command-line-arguments [build failed]
[ec2-user@se-summit mysampleadapter]$

**Comment by guptasu** [comment]
@vinayvenkat you will need to get latest version of Mixer the GetConfig was added recently 8 days ago.
https://github.com/istio/istio/pull/6217

**Comment by vinayvenkat** [comment]
@guptasu Thank you for the update and the changes. The tests run successfully now!

However, I think we need to update the docs to reflect that upon a successful run the "out.txt" file gets deleted. So the user can't really introspect the contents of that file. 
Thanks a lot for you help!

**Comment by vinayvenkat** [comment]
@guptasu I have a follow up question. Maybe its a candidate for a totally separate question but its kind of related. 

I've deployed istio and my custom adapter etc on kubernetes cluster on GKE. I've deployed a custom operator config and want to see my sample adapter in action. I've added some logic in my custom adapter that when called it sends out a tweet to be able to identify that my adapter is indeed being called. 
Problem is when I run some traffic against the product page endpoint i don't see the tweet from my adapter. How can I go about debugging the same. Is there a way to run localized "calls" to point to the mixer. Fundamentally, how do I know and debug the fact that my mixer adapter is indeed getting called? This will be of immense help and I can also help document the same. I'm very close to getting this working and would love to put together a guide if thats helpful as well. 
Thanks!

**Comment by guptasu** [comment]
+ @mandarjog @douglas-reid . Mixer debug logs have details on what adapter was invoked and what config was resolved (if any). Most of the time, I have observed, it is the incorrect operator configuration that results into adapter not getting triggered; might not be the case here.

@mandarjog do we have documentation on how to enable Mixer debug logs, or are they enabled by default ? (I think add  "- --log_output_level\n- debug" to the mixer's deployment config)

**Comment by guptasu** [comment]
adding @geeknoid also

**Comment by vinayvenkat** [comment]
@guptasu Thanks for the response. Which file would I enable the log output that you have shown? I think I'm very close and would love to close the loop on this. 
Thanks!

**Comment by vinayvenkat** [comment]
@guptasu I was able to extract some logs:

2018-07-24T22:17:46.465957Z	warn	testhandler.mysampleadapter.istio-system unable to unmarshal: unknown field "metrics" in config.Params, {"metrics":[{"name":"requestcount.metric.istio-system","type":"COUNTER"},{"name":"requestduration.metric.istio-system","type":"DISTRIBUTION"},{"name":"requestsize.metric.istio-system","type":"GAUGE"},{"name":"responsesize.metric.istio-system","type":"GAUGE"}]}
2018-07-24T22:17:46.466375Z	error	Failed to convert testhandler.mysampleadapter.istio-system spec: unknown field "metrics" in config.Params

2018-07-24T22:17:46.472394Z	error	Handler not found: handler='testhandler.mysampleadapter'

How can I debug this? Any suggestions? Thanks!

**Comment by vinayvenkat** [comment]
@guptasu @mandarjog I'm going to close this and I'll open a new ticket on Istio debugging.
