### ISSUE TITLE
Missing destination.service in mixer network filter

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#6510]
destination.service does not present in the attributes of mixer filter, which makes tcp telemetry from server side missing. One example inbound listener from config dump:
         "filters": [
         {
          "name": "mixer",
          "config": {
           "transport": {
            "report_cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
            "attributes_for_mixer_proxy": {
             "attributes": {
              "source.uid": {
               "string_value": "kubernetes://svc-c-9cbcfbb8c-drtzn.default"
              }
             }
            },
            "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local"
           },
           "mixer_attributes": {
            "attributes": {
             "context.reporter.local": {
              "bool_value": true
             },
             "destination.port": {
              "int64_value": "23333"
             },
             "destination.ip": {
              "bytes_value": "AAAAAAAAAAAAAP//CjgBFQ=="
             },
             "destination.uid": {
              "string_value": "kubernetes://svc-c-9cbcfbb8c-drtzn.default"
             },
             "context.reporter.uid": {
              "string_value": "kubernetes://svc-c-9cbcfbb8c-drtzn.default"
             }
            }
           }
          }

e2e_mixer does not catch this. Maybe because it cannot distinguish server / client metrics. We should add something for client in mixer e2e test

**Comment by kyessenov** [comment]
This is intentional. We don't have a reliable way to determine destination service on the server since a single IP:PORT can represent multiple services, and there is no extra-context passed around from the client.

There is an ongoing discussion to uniquely assign ports to TCP services. That mapping can be used in mixer (there is no need to push that information down to proxies).

**Comment by kyessenov** [comment]
@bianpengyuan Can you elaborate what are the subsequent effects of missing destination service here? Is this just breaking grafana dashboard or something else, too?

**Comment by bianpengyuan** [comment]
@kyessenov  There is no server side TCP metrics reported, and I am keep getting `preprocessing attributes failed: identity parameter not found: 'destination.service'` in mixer log.

**Comment by vadimeisenbergibm** [comment]
@kyessenov Is it possible to replace the error with warning for TCP services? Also, is there any default logger for TCP, like `stdio`? Should it be added? For HTTP, `stdio` prints source/destination IP, URL etc. in the output of the proxy container, very convenient.

**Comment by kyessenov** [comment]
@bianpengyuan @vadimeisenbergibm the error about config resolution failing should be resolved. It's a separate issue.
