### ISSUE TITLE
virtual service not work with a ip host

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#6512]
**Describe the bug**

A1(A,version1) running outside the cluster, its ip is 10.20.30.40 and port is 9000, meanwhile  B running inside, B send a request to A with a ip host like this:http://10.20.30.40:9000/{uri}, to do this i set a serviceentry for A1. now i want to running  A2(A, version2) inside, and want to transfer requests for certain rules to A2.

**Expected behavior**

A1(A,version1) running outside the cluster, its ip is 10.20.30.40 and port is 9000, meanwhile  B running inside, B send a request to A with a ip host like this:http://10.20.30.40:9000/{uri}, now i want to running  A2(A, version2) inside, and want to transfer requests for certain rules to A2. I used serviceentry and virtualservice ,but it not work. 
the config as below:

service entry:

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: A1
spec:
  hosts:
  - 10.20.30.40
  location: MESH_EXTERNAL
  ports:
  - number: 9000
    name: A1
    protocol: HTTP
  resolution: NONE

virtual service：
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: A
spec:
  hosts:
  - "10.20.30.40"
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: "/user/info"
      port: 9000
    route:
    - destination:
        host: A2.A.svc.cluster.local
        port:
          number: 9000

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
0.8.0

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
not

**Environment**
Which environment, cloud vendor, OS, etc are you using?
kubernetes

**Comment by dcberg** [comment]
Just a clarification.... Is your ServiceEntry (external) service host ip expected to be the same as the VirtualService (internal) service host?

**Comment by wansuiye** [comment]
@dcberg Hi，the host is different，A2(external ) host is ip(10.20.30.40), meanwhile A2 host is A2.A.svc.cluster.local(kubernetes). I fixed the description of A2 in virtual service above, 
Looking forward to your reply～

**Comment by wansuiye** [comment]
i find this description in [The](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService) 
"hosts field applies to both HTTP and TCP services. Service inside the mesh, i.e., those found in the service registry, must always be referred to using their alphanumeric names. IP addresses are allowed only for services defined via the Gateway."

Does this mean that requests with  a ip host cannot be forwarded to internal services？

**Comment by costinm** [comment]
The problem may be related with using IP address directly.  

We'll need to debug the generated config (config dump, /adsz, etc)

**Comment by louiscryan** [comment]
Looks like the issue here is the lack of a default match in the VirtualService that routes traffic to A1.

VirtualService does not implement fall-through routing to the default service for that matched hostname/ip. You need to have another match block at the end of VirtualService of the form

match:
  destination:
     host:  10.20.30.40


We don't support fall-through as the next available match could be a wildcarding rule and we wouldn't be able to assume how to order those.

We could augment the system to make this clearer, perhaps as part of API validation. Feedback on that would be welcome

**Comment by FrelDX** [comment]
exterior A host ip 10.0.0.1   curl VirtualService  to v1 pod
exterior  B  host ip 10.0.0.2   curl VirtualService  to v2 pod
VirtualService  Can it be done
