### ISSUE TITLE
add duration out of date to proxy-status

### ISSUE THREAD

**Issue by esnible** [istio/istio#6518]
If a proxy is `STALE` I would like to see how stale.  For example

```
$ istioctl proxy-status -proxy reviews-v3-66f7f5f8b-c579d.default
PROXY					CDS		LDS		EDS		RDS		PILOT
reviews-v3-66f7f5f8b-c579d.default	SYNCED		SYNCED		STALE (0%)	SYNCED		istio-pilot-5b456745cc-gdvfk
```

I don't know if _reviews-v3_ is stale by 1s because I could it during an update or if it is stale by 2h because 2h ago I added a CRD that caused the proxy to reject the EDS.

Perhaps output like `STALE (0% AGE 2h)`

**Comment by MorrisLaw** [comment]
Is this still a good first issue? I'd like to start contributing and this seems like a good place to start. @liamawhite @esnible

**Comment by liamawhite** [comment]
Yes! the code is [here](https://github.com/istio/istio/blob/master/istioctl/pkg/writer/pilot/status.go). You should only need to make changes to that file and add some tests. 

Take a look at the test files to see what the input looks like, but basically the nonce we pass around is a timestamp.

If you need any more pointers let me know.

**Comment by liamawhite** [comment]
@MorrisLaw How is progress? Do you need any help?

**Comment by MorrisLaw** [comment]
Hey @liamawhite I should be making a PR soon. I've just noticed your response on rocket chat, I'm usually on slack and admittedly don't use rocket chat often. So I didn't notice your response until today. But based on what you've said, I think I have a better idea of the task now. Thank you!

**Comment by liamawhite** [comment]
No worries, I also don't check the rocket chat too often.

**Comment by MorrisLaw** [comment]
Commented in PR, still in progress

**Comment by c0d1ngm0nk3y** [comment]
Is someone still working on this? Otherwise, I would like to contribute. I am watching this issue for a while and it seems stale.

**Comment by MorrisLaw** [comment]
https://github.com/istio/istio/pull/11568

**Comment by liamawhite** [comment]
this is complete
