### ISSUE TITLE
Should samples use istioctl or kubectl?

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#652]
Last PR #647 switched to using kubectl to send config to pilot.
Should we advertise the use of kubectl in all of our samples and documentation or use istioctl instead?
Note that the input format of the two tools is not the same at the moment. istioctl uses the same format as 0.1.x.

cc @louiscryan @rshriram @frankbu

**Comment by ldemailly** [comment]
My take is use istioctl (even if it's just a passthru to api server like kubectl would do) but maybe we can use istioctl with a version flag passed, if the 0.2 format is the future, it's nice to have 0.1 support but the main format should be the current one not the old one

**Comment by kyessenov** [comment]
cc @mandarjog since Mixer wants to use kubectl solely.
cc @ayj for missing AC validator concerns.

**Comment by rshriram** [comment]
I spoke to @mandarjog earlier on slack. He seemed okay with using ` istioctl create -f ` format.

**Comment by andraxylia** [comment]
Do we have time to make all the changes for 0.2?
If yes, we should switch to using kubectl sooner than later, feedback so far indicates people actually prefer a tool they already use. Plus , it would save us the problems with ensuring istioctl version is compatible etc.

**Comment by rshriram** [comment]
It's not about time. We cannot force users to use kubectl in a docker swarm or mesos or cloud Foundry or vm only environment. The fact that we reuse kube API server is purely implementation detail. In such environments, the only thing people need is CRD access. They should not be exposed to concepts like pods, deployments, etc.

**Comment by ldemailly** [comment]
none of those use cases were officially slated for 0.2; it's nice consul/eureka showed up early but that doesn't necessarily mean we have to scramble to support stuff we didn't plan to.

this being said having an idea what we'll do in 0.3 for non k8s env can inform which tradeoffs we pick right now. I think having istioctl support istio setup makes sense (and in k8s env, if for some category of config it is exactly equivalent to kubectl then sure we can use the same syntax and users in k8s can use kubectl directly if they wish)

**Comment by rshriram** [comment]
It's irrespective of the functionalities added in this or future releases. Our goal is to be platform independent. It makes little sense to bind ourselves to a platform specific cli and force it on other platform users - now or in future.

**Comment by frankbu** [comment]
I think the right answer is that we need to update istioctl so that it takes the exact same rule format as kubectl. Right now the non-spec parts are slightly different. Then we can document the commands as `istioctl -create|replace|apply|etc`, but say that k8s users can use `kubectl -create|replace|apply|etc` instead (no need to install istioctl for kube).

**Comment by kyessenov** [comment]
We could do that. We need to support the entire metadata struct then (see https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta) in case `istioctl` receives output of `kubectl`. We could also do better `apply` as `kubectl` does not support `apply`/PATCH for CRDs.

**Comment by rshriram** [comment]
Solved..

**Comment by ayj** [comment]
Yes, I would recommend you use `kubectl` to manage your Istio resources.

**Comment by MaikJaek** [comment]
Many thanks for your quick response @ayj !
