### ISSUE TITLE
Add “Setup/Performance and Scale” section for istio.io

### ISSUE THREAD

**Issue by jasmine-jaksic** [istio/istio#6534]
As part of doc items needed for 1.0, add a section that describes the consideration and techniques for scaling a mesh.

Refer to: https://docs.google.com/document/d/1WSmAwmVBoGoGz5Hek5rGK1JnXjnGKdCO9tqpbvv9404/edit#

**Comment by jasmine-jaksic** [comment]
Issue moved to [istio/istio.github.io #1575](https://github.com/istio/istio.github.io/issues/1575) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ldemailly** [comment]
this already exist / was https://github.com/istio/istio.github.io/issues/911
