### ISSUE TITLE
Improve Istio Debugging Experience

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#6541]
This is an epic to contain all the work going on to improve the debugging experience for users. Feel free to add any feature requests, suggestions or bugs to this epic.

**Comment by liamawhite** [comment]
I have an upcoming PR that will retrieve all loaded clusters/listeners/route that includes static and dynamic.

Does this cover your requirements?

**Comment by ldemailly** [comment]
#358

**Comment by rokii** [comment]
@liamawhite Exactly!

**Comment by liamawhite** [comment]
@rokii https://github.com/istio/istio/pull/6575

**Comment by esnible** [comment]
`istioctl inspect` https://docs.google.com/document/d/1OnJpw1Hi5vtfnIajOFwvuJPlnPlB2rJeCkRvSVJx9vI/edit# https://github.com/istio/istio/issues/15526 https://github.com/istio/istio/pull/15827

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/12513 Write a debug tool for Istio developers to troubleshooting mTLS issues

**Comment by esnible** [comment]
Closing because of `istioctl x describe` and `analyze`.
