### ISSUE TITLE
TestAuthNJwt in e2e-pilot is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#6545]
**Describe the bug**
TestAuthNJwt is flaky and it occasionally blocks PR merges since e2e-pilot is a required test.

**Expected behavior**
No flake

**Steps to reproduce the bug**
Example flakes in CIs
https://circleci.com/gh/istio/istio/121646?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/5886/istio-pilot-e2e-envoyv2-v1alpha3/3219/

**Version**

**Is Istio Auth enabled or not?**
Yes

**Environment**
CIs

**Comment by quanjielin** [comment]
looks similar to https://github.com/istio/istio/issues/6288 
one JWT test case fail(TestAuthNJwt/b->d[401]) with authN enabled recently(seems regression),

**Comment by hklai** [comment]
Closing this in favor of https://github.com/istio/istio/issues/6288
