### ISSUE TITLE
Multiplexing does not work on 1.0.0-snapshot.0 release

### ISSUE THREAD

**Issue by incfly** [istio/istio#6551]
When I tried to use https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0.0-snapshot.0-20180622-17-43/ to verify multiplexing feature, it does not work.

After some investigation, I found it's because pilot is not generating correct LDS Envoy configuration in that release version.

1. Check the build SHA, based on [manifest.xml](https://storage.googleapis.com/istio-prerelease/daily-build/release-1.0.0-snapshot.0-20180622-17-43/manifest.xml), it's `765445e938ac3b3088a6edecce7b4b17925dcba0` for istio/istio.
2. I checked out release-1.0.0-snapshot.0 and sync up to that commit, rebuild the pilot Docker image and locally build a Docker image, push it to `gcr.io/jianfeih-test/pilot:0622-rebuild-a`.
3. I modify the `istio-pilot` deployment YAML to use the locally build image.
4. Then the multiplexing feature works. Pilot generates the correct configuration.

Based on that, I suspect that Docker image is not built correctly for that release.

**Comment by hklai** [comment]
@incfly did you add any test for the feature? if so, could you check why https://github.com/istio-releases/daily-release/pull/677 passes?

**Comment by incfly** [comment]
I do add a test for the feature, it's part of the circle ci, e2e-pilot-noauth-v1alpha3 test. That test indeed pass.

Let me recreate a refresh env to reproduce the verification.

**Comment by incfly** [comment]
We recut the release so this becomes obsolete.
