### ISSUE TITLE
serviceregistry/kube TestServices is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#6555]
**Describe the bug**

serviceregistry/kube TestServices has been flaky and it blocks PR merges.

https://circleci.com/gh/istio/istio/119705?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6435/istio-unit-tests/9219/

**Expected behavior**
No flake

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
N/A

**Is Istio Auth enabled or not?**
N/A

**Environment**
Happened to both CircleCI and Prow tests.

**Comment by kyessenov** [comment]
That's because it's not a unit test. Do you want to move it to e2e suite?

**Comment by hklai** [comment]
My 2C is yes, but I don't own the code and the test. =)

**Comment by kyessenov** [comment]
Neither do I :)

**Comment by cmluciano** [comment]
This does not appear to persist in more recent builds on master and test has not been changed according to master branch
