### ISSUE TITLE
Running iptables script on Debian VMs does not intercept users whose group ID equals -u argument

### ISSUE THREAD

**Issue by tianyicaii** [istio/istio#6557]
**Describe the bug**
iptables script does not redirect users with group ID equals the number specified with -u option.
https://github.com/istio/istio/blob/master/tools/deb/istio-iptables.sh#L265

**Expected behavior**
I am expecting only the user whose user ID specified with -u is not affected by the iptables redirection.

**Steps to reproduce the bug**
Given two users: user-a and user-b:
username  |  user-id  |  group-id
user-a        |  5001     |  8001
user-b        |  8001     |  9001
If I evoke the script with: "sudo ./istio-iptables.sh -u 8001 -i '*' -p 15001", then both user-a and user-b will not be intercepted.

**Version**
I was using the iptables script alone on a VM.

**Is Istio Auth enabled or not?**
Not relavent.

**Environment**
A GCE VM with image "Google Drawfork Debian GNU/Linux 9"

**Comment by ymesika** [comment]
Fixed in #6561
