### ISSUE TITLE
e2e: Need more artifacts (pod logs)

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#657]
This is missing a few pod logs: from bookinfo application (container istio-proxy) & egress. Mixer log is empty and it should not be. API server log is obsolete.

http://gcsweb.k8s.io/gcs/istio-prow/pull/istio_mixer/1199/mixer-e2e-smoketest/400/artifacts/mixer-test-14408e86d6aa4cacb5307e6567/

For easier maintenance, I recommend getting logs for all the pods in that namespace, and create files with the same name, having a generic fct.

**Comment by chxchx** [comment]
@andraxylia We started off fetching logs from all pods but it ended up taking way too long, so the compromise was to only fetch logs from a defined list of pods (white list), which is
```
"apiserver",
"discovery",
"istio-ingress",
"mixer",
"prometheus",
"statesd-to-prometheus",
```
So we just add "istio-proxy", "istio-egress", and remove "apiserver" right?

Do you mind sharing the link to the original PR so I could investigate why mixer log is empty? Thanks!

**Comment by andraxylia** [comment]
At a minimum we need to add productpage (container istio-proxy), istio-egress, and remove apiserver.

I do not understand how much longer it takes to bring ~5 more logs, there must be some other underlying problem.

@douglas-reid do we really need the prom and statsd-to-prom logs?

**Comment by douglas-reid** [comment]
@andraxylia @chxchx we can drop prom and statsd-to-prom logs.

**Comment by chxchx** [comment]
@andraxylia Getting 5 more logs is probably fine. When we tried getting all logs, there were more than 50 kinds of logs, which takes too long. Just let me know what those 5 logs are and I will add them to the list.

**Comment by kyessenov** [comment]
We need to get _all_ the logs from istio components. All sidecar proxies + central services. Without that, we have no way to fully debug the failures, and just pointing in the dark. It's not important to us how you do it, stackdriver (which seems to be over-promised), docker logs, or your own log collector agent. There cannot possibly be a problem with storage or data transfer, or something must be very wrong with the setup.

**Comment by andraxylia** [comment]
At a minimum these ones:

istio-ca-xxx
istio-sidecar-XXXX
details-v1-525457007-4pt8g    
istio-egress-2542870796-2ww3g  
istio-ingress-1392073146-wh40m 
istio-mixer-259290900-sp4sk    
istio-pilot-2301231356-m02ng    
productpage-v1-354903437-lgrn2   
ratings-v1-1800611655-sx407      
reviews-v1-4120681136-180d0    
reviews-v2-3900684862-0whn6    
reviews-v3-905664992-213jp

**Comment by sakshigoel12** [comment]
chxchx@ please could you provide an update here

**Comment by chxchx** [comment]
https://github.com/istio/istio/pull/673
I have this PR ready but istio presubmit has been red for all pending PRs and will merge once tests are stable

**Comment by chxchx** [comment]
https://github.com/istio/istio/pull/673 was merged.
