### ISSUE TITLE
Istioctl CLI fails with a merged KUBECONFIG 

### ISSUE THREAD

**Issue by dcberg** [istio/istio#6579]
**Describe the bug**

The istio CLI (istioctl) fails to execute commands if the terminal session is using a merged KUBECONFIG. A merged KUBECONFIG is where the KUBECONFIG environment variable lists multiple kubernetes configuration files separated by a `:`. When using a merged KUBECONFIG every `istioctl` command fails with the following message...

`
Error: kubernetes configuration file "<path to config file1>:<path to config file2>:<path to config file 3>" does not exist.
`

**Expected behavior**

The `istioctl` should respected a merged KUBECONFIG and use the current context for access the kube cluster.

**Steps to reproduce the bug**
Steps to reproduce the behavior.

1. Setup a terminal with `export KUBECONFIG=<path to config file1>:<path to config file2>:<path to config file 3>`. 
2. Set the current context to a valid context (e.g., `kubectl config use-context <context>`
3. Execute any `istioctl` command in the terminal window.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

`
→ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
`

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

Doesn't matter.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

I'm using IBM Cloud Kubernetes Service clusters running on a mac OS.

**Comment by gyliu513** [comment]
@dcberg @ymesika Is this duplicate with https://github.com/istio/istio/issues/4081 and already fixed in master?

**Comment by ymesika** [comment]
@gyliu513 Yes, I just wanted to re-verify it first before closing.

@dcberg We now have a new `context` flag so you can also choose a context when using istioctl: `istioctl get all --context my-context`.

**Comment by dcberg** [comment]
@ymesika what version of the istio CLI is this new flag?

Are you saying that the istioctl will *NOT* respect the current context from the kubernetes config?

**Comment by ymesika** [comment]
It will respect the current but you can overwrite it with a different one if you have multiple contexts within your config.

This has been added after the 0.8.0 release and any recent daily release has this and the multiple paths bug fix.
