### ISSUE TITLE
Servicegraph add query parameter to filter by namespace 

### ISSUE THREAD

**Issue by SeriyBg** [istio/istio#6588]
**Is your feature request related to a problem? Please describe.**
When looking at servicegraph for the standard Istio installation you can see a lot of Istio services which makes a lot of noise and make it hard to understand the topology of your application 

**Describe the solution you'd like**
I'm think that it would be great to add the query parameter for to filter out the services by namespace or by name. E.g. `?namespaces=default`

**Comment by SeriyBg** [comment]
If you consider this feature, I can try to work on it. It seems easy to implement

**Comment by SeriyBg** [comment]
Prometheus supports some filter by name, so in the query could be added `{job=".*default"}` so it could be implemented not only to filter by namespaces, but by service names
Can someone discuss which option is more preferable?

**Comment by SeriyBg** [comment]
Please take a look at my post in the Istio Developers mailing list [here](https://groups.google.com/forum/#!topic/istio-dev/6H6eLIBxTfk).

**Comment by SeriyBg** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
@SeriyBg a big +1 to this feature. If you want to work on it, that'd be great. I've been wanting similar controls for awhile now, but it has just not been a priority.  It should be a fairly straightforward change -- and I'd be happy to review any PR for it.

I should mention that more full-featured and better supported graphing solutions are being developed in the community (kiali, scope). I don't know if you've played with them, but they might provide all-around better UX than the example servicegraph application.

**Comment by SeriyBg** [comment]
@douglas-reid thanks for your reply! I have actually done this, but it uses `destination_service` and `source_service` metric labels. I will change it to use the new labels and then submit the PR.
