### ISSUE TITLE
How to route request internal with a external domain

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#6591]
**Describe the bug**

now i have tow svcs: A and B, B's domain is b.xx.yy, now deploy A and B in istio，but stil use the domain。 i set a virtual service, host is domain and destination is B's serviceName, it can work, but i find the request go through the ingressgateway。How can the request flow internal，while the svcs are all internal

**Expected behavior**

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
0.8.0

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
not

**Environment**
Which environment, cloud vendor, OS, etc are you using?
kubernetes

**Comment by duderino** [comment]
can you share your yaml?  it's hard to see exactly what you're trying to do from this description
