### ISSUE TITLE
Istio 0.8.0 mTLS + MongoDB 3.6 does not work

### ISSUE THREAD

**Issue by yacut** [istio/istio#6596]
```shell
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Steps to reproduce:**

1. Deploy Istio 0.8.0 with mTLS: `kubectl apply -f install/kubernetes/istio-demo-auth.yaml`
2. Create and label namespace: `kubectl create namespace mongodb && kubectl label namespace mongodb -istio-injection=enabled`
3. Deploy [MongoDB Chart](https://github.com/kubernetes/charts/tree/master/stable/mongodb) with replica set: `curl -O https://raw.githubusercontent.com/kubernetes/charts/master/stable/mongodb/values-production.yaml && helm install --namespace mongodb --name my-release --set mongodbRootPassword=secretpassword,mongodbUsername=my-user,mongodbPassword=my-password,mongodbDatabase=my-database stable/mongodb -f ./values-production.yaml stable/mongodb`
4. Show the logs from secondary pod: `kubectl --namespace mongodb logs -f my-release-mongodb-secondary-0 mongodb-secondary`

**Expected behavior:**
The secondary node is connected to the primary node. Replica set is configured on secondary node.

**Actual behavior:**
The secondary node is not connected to the primary node. 

---
Primary node logs:
```
2018-06-25T17:29:49.670+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:60414 #4 (1 connection now open)
2018-06-25T17:29:49.671+0000 I NETWORK  [conn4] received client metadata from 127.0.0.1:60414 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.6.5" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.14.22+" } }
2018-06-25T17:29:49.674+0000 I NETWORK  [conn4] end connection 127.0.0.1:60414 (0 connections now open)
```

Secondary node logs:
```
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set mode
mongodb INFO  ==> Configuring MongoDB secondary node
INFO  Trying to connect to MongoDB server
INFO  Found MongoDB server listening at mongodb:27017
INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
2018-06-25T17:29:49.678+0000 E QUERY    [thread1] Error: network error while attempting to run command 'isMaster' on host 'mongodb:27017'  :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:21


exception: connect failed

INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
2018-06-25T17:29:49.970+0000 E QUERY    [thread1] Error: network error while attempting to run command 'isMaster' on host 'mongodb:27017'  :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:21


exception: connect failed
```

MongoDB error explanation: https://www.aptible.com/documentation/enclave/troubleshooting/mongodb-error.html

**Comment by evanfoster** [comment]
I'm having this exact same issue. I'm guessing it's because MongoDB doesn't use HTTP to communicate with the replicaset members, so Envoy doesn't know what to do. This is just pure conjecture on my part, but it's the only thing that makes sense to me.

**Comment by yacut** [comment]
@evanfoster I've tested [mongodb statefulset](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset) with Istio 1.0.2 and 1.0.5, it still does not work. I've also tried different configurations for [DestinationRule](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#DestinationRule) and [Policy](https://istio.io/docs/reference/config/istio.authentication.v1alpha1/#Policy). Once sidecar is running, the pods in Statefulset can not communicate with each other.
The only way for mongodb replicaset currently - deploy without sidecar:
```yaml
annotations:
  sidecar.istio.io/inject: "false"
```
If I understand correctly, [support for statefulsets is planned in milestone 1.2](https://github.com/istio/istio/issues/10659)
