### ISSUE TITLE
Mixer Report failed with: UNAVAILABLE

### ISSUE THREAD

**Issue by fogongzi** [istio/istio#660]
When I use istio 0.2.1 and kubernetes 1.7.4, I deployed the bookinfo example, it gives out:
Sorry, product details are currently unavailable for this book.
Sorry, product reviews are currently unavailable for this book.

When I find logs with productpage and proxy_debug container, the proxy_debug container gives the error messages:
**[libprotobuf ERROR external/mixerclient_git/src/report_batch.cc:78] Mixer Report failed with: UNAVAILABLE**

Then I find logs with istio-mixer container, and it gives the error messages:
I0904 09:47:44.344661      15 reflector.go:225] Listing and watching *v1.Pod from external/io_k8s_client_go/tools/cache/reflector.go:96
E0904 09:47:44.355371      15 reflector.go:190] external/io_k8s_client_go/tools/cache/reflector.go:96: Failed to list *v1.Pod: User "system:serviceaccount:istio:default" cannot list pods at the cluster scope. (get pods)

So what is the issue, thanks!

**Comment by ldemailly** [comment]
> E0904 09:47:44.355371 15 reflector.go:190] external/io_k8s_client_go/tools/cache/reflector.go:96: Failed to list *v1.Pod: User "system:serviceaccount:istio:default" cannot list pods at the cluster scope. (get pods)

looks like you need to add that clusterrolebinding for istio service account to be able to list pods?

**Comment by fogongzi** [comment]
@ldemailly ,yes, I have found the solution, I do not create clusterrolebinding in my namespace. thanks!

**Comment by ldemailly** [comment]
we haven't refined the roles yet but when the final 0.2 it should work out of the box
