### ISSUE TITLE
Instructions to enable Istio with Kubernetes with the MutatingWebhookConfiguration enabled 

### ISSUE THREAD

**Issue by vinayvenkat** [istio/istio#6605]
**Describe the bug**
I've been following the Istio instructions to deploy the side using automatic injection at 
https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection

However, I've been unsuccessful in getting the automated injection to work. I've followed the instructions verbatim and ensure I'm using the right kubernetes version as well as the right Istio version. This however is not working for me. 

**Expected behavior**

The expectation is that after I have Istio appropriately installed, that when I deploy a new service, the side car gets automatically injected. This is however, not happening. 

**Steps to reproduce the bug**

1. Install kubernetes 1.10.4-gke.2 on GCP.
2. Install Istio using instructions from: 
https://cloud.google.com/kubernetes-engine/docs/tutorials/installing-istio

3. then follow instructions from: 

https://istio.io/docs/setup/kubernetes/sidecar-injection/#automatic-sidecar-injection

**Version**

~/istio-0.7.1 >istioctl version
Version: 0.7.1
GitRevision: 62110d4f0373a7613e57b8a4d559ded9cb6a1cc8
User: root@c5207293dc14
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean

~/istio-0.7.1 >kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**

I installed istio-auth.yaml.

**Environment**
Running on GCP.

**Comment by sdake** [comment]
Kubernetes 1.8 (your client) does not support mutating webhooks.  Can you try a newer version of kubectl?

Also, I'd recommend using 0.8.0 as its an LTS and 0.7.1 is unsupported.  The 0.8.0 version enables webhooks by default.  Documentation is here:
https://istio.io/docs/setup/kubernetes/

Cheers
-steve

**Comment by vinayvenkat** [comment]
@sdake Thank you for the response. Apologies for the delay in responding. You are right. I upgraded to a newer version (0.10.x) and then used helm to deploy istio. With this it all worked.
