### ISSUE TITLE
Move networking APIs to beta1

### ISSUE THREAD

**Issue by costinm** [istio/istio#6613]
I think it should be P0, filling it initially as P1.

What is required:
- create the beta1 resources
- change the k8s code to read both alpha3 and beta1 - same proto and validation.
- verify both alpha3 and beta1 configs are loaded - to support upgrade from 0.8
- change docs, examples, tests to use beta1

**Comment by ayj** [comment]
k8s CRD doesn't supported versioning yet. See https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/rX99p_YWObA. You'll need to create a new group/kind, making a breaking change, or wait until 1.11 is min required version.

Support for no-conversion versioning is targeted for k8s 1.11 (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresources-versioning.md and https://github.com/kubernetes/kubernetes/pull/63830)

**Comment by nmittler** [comment]
@costinm please advise

**Comment by nmittler** [comment]
@costinm gentle ping

Looks like all 1.0 changes need to be merged by Monday 7/2.  I suspect that it's unlikely to get this change through review and submitted by then. I recommend pushing this work out until after 1.0.  Thoughts?

**Comment by andraxylia** [comment]
Kubernetes 1.11 is out. It seems reasonable to make this change in 1.1.

**Comment by ayj** [comment]
Multiple versions of the same CRD group/kind cannot coexist (see example below). 

```bash
$ cat crd-alpha.yaml 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.networking.istio.io
  labels:
    app: istio-pilot
spec:
  group: networking.istio.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
  scope: Namespaced
  version: v1alpha3

$ kubectl apply -f crd-alpha.yaml 
customresourcedefinition.apiextensions.k8s.io "virtualservices.networking.istio.io" configured
```

```bash
$ cat crd-beta.yaml 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.networking.istio.io
  labels:
    app: istio-pilot
spec:
  group: networking.istio.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
  scope: Namespaced
  version: v1beta1

$ kubectl apply -f crd-beta.yaml 
The CustomResourceDefinition "virtualservices.networking.istio.io" is invalid: spec.version: Invalid value: "v1beta1": field is immutable

```

**Comment by costinm** [comment]
Last time we did this I think we changed the group or the names.

Adding @rshriram @louiscryan 
The options are:

- do nothing

- update only the docs (and api directory) and say "Networking APIs are beta, but due to limitations in K8S < 1.11 users will still need to use alpha3 labels until 1.11 is available"

- update the group - v1.networking.istio.io   with version beta1

**Comment by costinm** [comment]
Of course - the trick with v1.networking.istio.io will not work for beta2 - but by that time hopefully we'll have k8s 1.11

**Comment by ayj** [comment]
> update the group - v1.networking.istio.io with version beta1

Encoding the version in the group name will make the YAML confusing, e.g.

```yaml
apiVersion: v1.networking.istio.io/v1beta1
kind: VirtualService
...
```

Updating the docs seems like a reasonable compromise until k8s 1.11 is our minimum supported version (~9 months).

**Comment by costinm** [comment]
No, it will be v1.networking.istio.io/beta1

No need to double v1

**Comment by costinm** [comment]
I don't think v1.networking.istio.io/beta1 versus
networking.istio.io/v1beta1 is a huge problem - and less than the risks of
users
not comfortable with 'alpha3' label in all their configs and hurting
adoption.

**Comment by rshriram** [comment]
Lets please not do the group name hack again.. its gross.. We went through a big cycle of changes across istio to have consistent naming for all our resources. We can communicate in the docs that networking APIs are beta but are still called alpha due to k8s limitations. By the next istio release (or after that), everyone would have moved to kube 1.11, at which point we can name this v1beta1. 

Its not like the alternatives are going to solve the optics issue nice, since its simply appending versions to the group name. People would then expect v1.networking.istio.io/stable?? which might get clunky.

**Comment by ayj** [comment]
> People would then expect v1.networking.istio.io/stable?? which might get clunky.

Following k8s apiVersion conventions we'd have `v1.networking.istio.io/v1` and, take to the extreme, `v1.networking.istio.io/v2` which is really confusing.

**Comment by costinm** [comment]
Ok, let's just document. 

@rshriram by the time we have beta2 or stable I hope k8s 1.11 will be available - and we can have 
v1.networking.istio.io/beta2 or /stable as expected. 

But given the time we have left - and all the doc updates we would need to do - it's probably safer to postpone this. 

The K8s naming model - with separate labeled 'version', which ends up appended to name anyways - is not ideal. When we move to v2 we'll obviously change the group again - v2.networking.istio.io/alpha,beta,stable

**Comment by rshriram** [comment]
> The K8s naming model - with separate labeled 'version', which ends up appended to name anyways - is not ideal. When we move to v2 we'll obviously change the group again - v2.networking.istio.io/alpha,beta,stable

?? are you saying that in k8s 1.11, we cant do networking.istio.io/v2alpha1 ?

**Comment by costinm** [comment]
in 1.11 - we can do anything.

The question is - are we stuck with alpha3 (and the other alphas) until
1.11 ? Keep in mind it's not when 1.11 is released - but when 1.11 is the
minimum version and we stop supporting 1.10

I think that's a long time to be stuck.

The alternative is to forget the broken k8s version - and use the 'group'
to namespace and version the API.

I personally don't see a huge difference between
v1.networking.istio.io/beta1 and networking.istio.io/v1beta1

**Comment by costinm** [comment]
Better option:

 v1beta1.networking.istio.io/v1

which allow us to evolve without having to wait for k8s 1.11 to be our required min. version.

Next will be 
  v1beta2.networking.istio.io/v1
  ...
  v1.networking.istio.io/v1
  v2alpha1.networking.istio.io/v2
etc

**Comment by rshriram** [comment]
I like the prefix part v1beta1.networking.istio.io/v1 

But we still have to support networking.istio.io/v1alpha3 for 0.8.. if someone can guarantee that we can register both crds simultaneously, then the amount of work required is minimal. We can let people use old and new formats without any issues for 1.0

**Comment by costinm** [comment]
Yes, I can guarantee we can register and support both - we did it for
alpha1 and alpha2. As long as the group name is different
registration is fine. Tested that I can register the new resource.

Work required:
- copy the API to beta1 directory
- add the CRDs
- add code to read the new beta1 - cut&pasted from alpha3, the content is
the same
- update the samples and docs to use v1beta1.networking... instead of
networking...
- update tests so few of the test cases use v1beta1 (no need to convert all
- we need a mix in the test suite, not what
we did for alpha1 where we had 2 separate suites and a lot of pain)
- update the docs

It seems like a lot - but it's pretty safe, adding new files and code to
read new CRDs has almost zero risk.
If we can't finish all - it's still ok.

We can still discuss the actual format of the name - the first and 3rd work
item can proceed and may need to be
adjusted if we bikeshed a different name, just want to avoid being stuck
until k8s 1.11

**Comment by rshriram** [comment]
@geeknoid thoughts ?

**Comment by ayj** [comment]
Non-standard group/versioning will make it difficult to do proper CRD versioning later with (k8s >= v1.11). Will we be stuck with this format forever, or switch to the strict `<group>/<version>` format later?

FWIW, it also violates our [API style guide](https://github.com/istio/api/blob/master/STYLE-GUIDE.md#crd-versioning).

**Comment by ozevren** [comment]
Bear in mind that this will also cause issues with key spaces (supporting two different api groups creates two different key space, allowing same-named resource to be created in both)?

**Comment by costinm** [comment]
API style guide is easy to fix - in particular since it clearly is not working and didn't work ( you can't have versioning if only one version is supported).

Allowing same-named resource is a problem we can deal with easily - the common case is user updating to the new version of the API and using same name, we can't ask user to delete the old one because it would create a migration problem - so we need to pick the name with largest version. 

My point is: if you don't like this proposal, what do you suggest ? That we'll be stuck with no way to upgrade any API until k8s 1.11 - just because we chose a versioning scheme that doesn't work with current k8s and are too stubborn to change ? What is your plan for auth or other APIs that may need 
to make changes - and why is it better than simply using a scheme that works now and will work in future ?

**Comment by ozevren** [comment]
I don't think this stops from making you changes to the actual data format.
As long as the parsing can elide unrecognized fields, you can make backward
compatible changes to the format itself over time. So this mostly affects
"advertising", unless I am missing something. Waiting for 1.11 to be the
baseline doesn't seem too bad, compared to trying to invent our own
versioning scheme on top of Kubernetes' own, which is likely to be
confusing.

However, If we're going to actually invent and adopt a new versioning
scheme, let's do it across the board, and not try to do it piece meal.

**Comment by ayj** [comment]
My understanding is that we planned to support the three most recent k8s releases. k8s 1.11 was recently released and k8s release cadence is every three months. k8s 1.11 would be our minimum supported version in ~6-7 months. In the context of this PR for release 1.0 (update networking APIs) I was suggesting we wait it out and document it (see [here](https://github.com/istio/istio/issues/6613#issuecomment-402323905) and [here](https://github.com/istio/istio/issues/6613#issuecomment-402325663)). 

If, instead, we're discussing a longer term, more general approach to versioning, then I think we ought to do what @ozevren suggested and consider the longer term implications.

**Comment by costinm** [comment]
@ozevren  yes, this proposal applies to all other Istio APIs, as they need to move to a new version. 
Right now AFAIK networking is ready to go to beta1, same scheme should apply to all others.

We are not 'inventing' a new versioning scheme here - using version as part of domain is already 
invented and well adopted. K8S may have attempted to invent a new scheme - but for CRD
it is provable that their scheme doesn't work and as such nobody really 'adopted' it ( i.e. used it to
version anything). I don't know if any product using CRD had to version - but if they did it's clear they
couldn't use the k8s version but either what I'm proposing or a scheme where the names are mangled. 

If anyone can provide any good reason why having version at the end as path instead of in domain is 'better' and worth waiting 7 months without any backward incompatible change to any Istio API - happy to wait. 

As a general versioning solution, having the version in domain works better with istio - easier to route - and grpc or protocols where path is strictly defined.

**Comment by cmluciano** [comment]
I've lost track of the name that is being proposed. @costinm Can you comment on what you think the name should be. FWIW I don't see a strong argument to change the domain field in order to signify that it is in beta form. If/when we do adopt the strict apigroup/version format, this would be another breaking change to undo the naming.
