### ISSUE TITLE
unknown flag: --configStore2URL

### ISSUE THREAD

**Issue by Lord-Y** [istio/istio#6624]
Hi all,

When you tried to install istio with chart version 0.2.13-chart4, you can't because of this flag. In the help of the mixer you have
`--configStoreURL string
`
In the template templates/deployment/mixer.yaml you must replace configStore2URL by configStoreURL

To reproduce it:
```
ISTIO_CHART_VERSION=0.2.13-chart4
ISTIO_IMAGE_VERSION=0.8.0
helm upgrade -i istio incubator/istio --reuse-values --set istio.install=true,istio.release=$ISTIO_IMAGE_VERSION,rbac.install=false --devel --version $ISTIO_CHART_VERSION --namespace istio-system
```
Log of my pod:
```
kubectl logs -n istio-system istio-mixer-687668dc55-rgt5b -c istio-mixer
Error: unknown flag: --configStore2URL
Usage:
  mixs server [flags]
```

My kubectl version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
Auth is enable and I'm deploying istio on gcloud.

Thx

**Comment by ymesika** [comment]
This flag no longer exists in any helm chart. We also don't have `istio-mixer-*` pods anymore.
What version of istio are you using? What is the `incubator/istio`?

**Comment by Lord-Y** [comment]
Yes `incubator/istio` as previously mentionned but I figure this out. I was using chart version 0.2.13-chart4 and then I saw that istio-0.3.0 version exist here https://kubernetes-charts-incubator.storage.googleapis.com/.
The thing is when you try to deploy istio version 0.8.0 this charts istio-0.3.0, you can't because there is no docker ca image version 0.8.0 on docker hub.
```
kubectl logs -n istio-system istio-istio-ca-7d9bd9b585-xwctk
Error from server (BadRequest): container "ca" in pod "istio-istio-ca-7d9bd9b585-xwctk" is waiting to start: trying and failing to pull image
```
The last version is 0.7.1. In the CA deployment chart you got:
`image: "{{ .Values.ca.deployment.image }}:{{ .Values.istioRelease }}"`

So if you guys can create it, it will be great or maybe I missed something. For now I will try to install 0.7.1 for my testing purpose :)

**Comment by ymesika** [comment]
In 0.8.0 CA is called `Citadel`

**Comment by Lord-Y** [comment]
I finally make version 0.8.0 works but following only istio documentation on istio website.
