### ISSUE TITLE
Response time and Response Size queries slow

### ISSUE THREAD

**Issue by Stono** [istio/istio#6626]
Hey, 
One for @douglas-reid 
Something we've noticed today is that the response time and response size graphs on the individual service dashboard are slow to load on applications which have a high frequency of deployments (this particular app is deployed 30-40 times per day.

<img width="1680" alt="screen shot 2018-06-26 at 13 37 29" src="https://user-images.githubusercontent.com/1486729/41912040-4e7f32b0-7946-11e8-8f6f-4f2089920321.png">

Prometheus here only has about 3 hours of data in its data store, and has 6vCPU and 4gigRAM and SSD storage.  This is running on a 15min window.

**Comment by douglas-reid** [comment]
@Stono i wonder if this is because it is trying to load all the p*s at the same time for each version?

BTW, does each deployment have a unique name?  Would you ever want an individualized workload graph?

**Comment by Stono** [comment]
@douglas-reid I'm happy to close this in favour of https://github.com/istio/istio/issues/6741 - as the underlying problem is the build up of versions due to mixer not clearing out historical data.
