### ISSUE TITLE
istio-sidecar-injector pod shows "CrashLoopBackOff" on Kubernetes version 1.8.x or earlier

### ISSUE THREAD

**Issue by sgilsonapigee** [istio/istio#6627]
If you install Istio 0.8.0 on Kubernetes version 1.9 or earlier, you will see an error in the pod for the istio-sidecar-injector. 

$ kubectl get pods -n istio-system

NAME                                        READY     STATUS             RESTARTS   AGE
istio-sidecar-injector-7d58f79779-bxtld     0/1       CrashLoopBackOff   573        1d

While you can ignore that error, it should not occur.

**Expected behavior**
No error for 

**Version**
$ istioctl version

Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
**Is Istio Auth enabled or not?**
Does not matter

**Environment**
GCE

**Comment by ymesika** [comment]
What is Anchor?
Sidecar injector in Istio 0.8.0 are base on a Kuberenete feature called Mutating Webhooks which is only available from K8s v1.9.
We documented it [here](https://istio.io/docs/setup/kubernetes/sidecar-injection/).

**Comment by sgilsonapigee** [comment]
Thanks @ymesika. That was a typo, I meant Istio.
