### ISSUE TITLE
Unsupported argument --admission-service in pilot template file

### ISSUE THREAD

**Issue by hkshaw1990** [istio/istio#6628]
**Describe the bug**
`--admission-service` exists as an argument to `pilot-discovery` in `install/kubernetes/templates/istio-pilot.yaml.tmpl` template file:
```
      - name: discovery
        image: {PILOT_HUB}/pilot:{PILOT_TAG}
        imagePullPolicy: IfNotPresent
        args: ["discovery", "--admission-service", "istio-pilot"]
```
`--admission-service` is not supported by `pilot-discovery` anymore:
```
# kubectl logs istio-pilot-c74b4c998-r9rhd -n istio-system -c discovery
Error: unknown flag: --admission-service
```
The templates in helm charts are however have been updated.

**Expected behavior**
`--admission-service` argument to be removed from the template file.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
istio version: commit e80a6e4058543eed75a5f4b093f87e105cfde038 (master)

**Comment by ymesika** [comment]
`istio-pilot.yaml.tmpl` and any other template in `install/kubernetes/templates` are not updated and will be removed soon (#6585).
Installation should be done with Helm template/install.

**Comment by hkshaw1990** [comment]
@ymesika thanks for the update. Will close this issue then.

**Comment by jiuchongxiao** [comment]
@hkshaw1990  did you have solved the issue? i have the same issue

**Comment by hkshaw1990** [comment]
@jiuchongxiao yes, we need to remove `--admission-service` flag and adapt it to `0.8.0` version (can't send a PR as the templates are no longer updated). Or better yet, generating the yaml using `helm template` works, that's what I used anyway.
