### ISSUE TITLE
Multi-cluster support for Istio security

### ISSUE THREAD

**Issue by wattli** [istio/istio#6635]
This is a post-1.0 feature.

**Comment by sdake** [comment]
@wattli - bit confused by this issue tracker as it lacks a bit of detail.  Currently multicluster is secure although could benefit from a design audit.  For reference, citadel is deployed on each multicluster Kubernetes control plane, and certificates can be set in either intermediate mode or with a shared root certificate.

Cheers
-steve

**Comment by wattli** [comment]
The current "multicluster" is to treat several clusters as one, I am not sure whether we want to go with this way in the long run, i.e., whether we need a control plane for each cluster or not. That's why I leave this issue for now.
