### ISSUE TITLE
Need integration test of complex routing + policy enforcement

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#664]
Recent (and outstanding) changes to the existing integration test suites are removing a bunch of routing rule (and other) complexity from tests in an attempt to make tests more debuggable (and understandable).

However, this leaves a void in testing of complex mesh behavior. We need to add additional tests that attempt to "stress test", if you will, the mesh for more than just simple scenarios.

**Comment by hklai** [comment]
Removing "area/test and release" label as it is not meant for adding functional tests or test coverage.
Please assign issues to the appropriate functional area going forward.

**Comment by ldemailly** [comment]
andy while I agree the specific issues aren't necessarily test and release specific, the underlying theme across is the ease  (or not) of adding non flacky simple tests (applies to #3029 as well) - how easy those gets fixed will I guess inform on whether we are where we want from a test framework point of view.

**Comment by hklai** [comment]
@ldemailly yes that is part of what swat team is doing (i.e. less flaky framework), but labeling all test issues with "area/test and release" is not helpful to anyone.

**Comment by ldemailly** [comment]
I think a label to track test issues would be useful

**Comment by hklai** [comment]
The closest one is "kind/test failure".

**Comment by ldemailly** [comment]
looking more for kind/test coverage
