### ISSUE TITLE
Temporarily remove ServiceEntry from server-side validation for 1.0

### ISSUE THREAD

**Issue by ayj** [istio/istio#6640]
Per @costinm's request, we can temporarily omit ServiceEntry from server-side validation for 1.0.

**Comment by jasmine-jaksic** [comment]
New P0 issues should be approved by ToC (refer to the email I sent to istio-dev@ yesterday). Why is this a launch blocker for 1.0? And what's the ETA?

**Comment by ayj** [comment]
Moved to P1. @costinm requested that ServiceEntry be omitted if config validation is enabled by default in 1.0
