### ISSUE TITLE
Document how to query proxy configuration

### ISSUE THREAD

**Issue by nmittler** [istio/istio#6642]
There are many cases where it may be desirable to query the configuration of the proxy.

One common scenario is at pod startup.  Kubernetes will start the service container and the `istio-proxy` container at the same time and will allow traffic as soon as the service container reports that it's healthy. This can lead to temporary traffic loss if Envoy hasn't yet received its first configuration from Pilot.

Some customers have handled this with custom scripts that are run on the service container, which delay startup of the service application until Envoy has received its initial configuration from Pilot.

We should document both this issue as well as how to query Envoy status in general.  We should also recommend a solution.

**Comment by nmittler** [comment]
cc @rshriram @Stono

**Comment by nmittler** [comment]
Also cc @liamawhite who has done some work in this area and may have some thoughts.

**Comment by nmittler** [comment]
@costinm I feel like we should target 1.0 for this? WDYT?

**Comment by Stono** [comment]
Rather than querying / grepping the proxy config, a simple /ready endpoint would be welcome.

**Comment by liamawhite** [comment]
We could add a ready endpoint to pilot-agent. The handler could query the Envoy admin API config dump and check for the presence of dynamic clusters and listeners.

We would probably have to add another static listener in order to get a request routed there.

**Comment by Stono** [comment]
In the interim if anyone wants to share a working envoy readiness probe they've done that'd be sweet :-)

**Comment by nmittler** [comment]
@liamawhite 

> The handler could query the Envoy admin API config dump and check for the presence of dynamic clusters and listeners.

What if there was only a single service instance? Would any dynamic clusters/listeners be assigned?

**Comment by nmittler** [comment]
Actually, we could just look for the existence of the blackhole cluster.  WDYT?

**Comment by nmittler** [comment]
@liamawhite 

> We would probably have to add another static listener in order to get a request routed there.

Pilot already adds management ports for 3333 and 9999 ... could we use those?

**Comment by liamawhite** [comment]
In kube there will be kube stuff in there. Kube-dns, kube-dash, etc. Maybe not if we decide to selectively load clusters at a later date though.

**Comment by nmittler** [comment]
@costinm what would be a reasonable default for a readiness port? 15003?

**Comment by rshriram** [comment]
Where is this port going to point to? What’s the output? How do you know if the output is complete with all xDS info ?

**Comment by nmittler** [comment]
@rshriram 

> Where is this port going to point to? What’s the output? How do you know if the output is complete with all xDS info ?

The new port would be open by the agent and implement a [k8s TCP probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-tcp-liveness-probe).  When the agent starts, it will poll the Envoy admin port until it contains dynamic clusters/listeners.  At that point, it will open the server socket for the readiness probe.

**Comment by costinm** [comment]
Not sure I like this approach. How about opening a HTTP probe, so we can extend it in the future with 
metrics about the agent, controlz, etc ? It's as easy to code.

But please run a small test: in my testing it appears the generated config is bad while readiness returns false, because pilot can't find the IP. See slack discussion for a possible fix.

**Comment by nmittler** [comment]
@costinm 

> Not sure I like this approach.

It would be helpful if you'd explain why you don't like it.  IIRC, it was your idea to use a TCP readiness probe (rather than HTTP).

**Comment by rshriram** [comment]
Don't open any HTTP/TCP ports. It will not play nicely with IPtables stuff. Please run it as execScript thingy in K8S.

**Comment by nmittler** [comment]
Moving discussion of implementation details to https://github.com/istio/istio/pull/7465

**Comment by liamawhite** [comment]
@nmittler Whats outstanding on this issue? Just the documentation part?

**Comment by nmittler** [comment]
@liamawhite IIRC the original goal of this issue was to allow developers to write their own probers until we had readiness implemented.  I'm fine closing this.
