### ISSUE TITLE
Add helm feature flag to enable/disable server-side config validation

### ISSUE THREAD

**Issue by ayj** [istio/istio#6643]
Server-side config validation should be configurable with an explicit feature flag (i.e. `configValidation`). The current helm files only allow all of galley to be enabled/disabled which is not desirable long term.

**Comment by costinm** [comment]
Maybe the 'fail open/fail close' should also have a flag.

This will allow users to have validation - but if galley has any problem still be able to make changes.
We can continue to debate what is the right default - but still allow users to make the tradeoffs they need.

**Comment by ayj** [comment]
Fail open is susceptible to gaps in validation when pods are reschedule, e.g. preemptible instances. This would occur even when galley is operating correctly. Changing the failure policy is a one-line YAML change that could be achieved with `kubectl patch`. We can document this option in the validation playbook (TBD).

**Comment by ayj** [comment]
Fixed by https://github.com/istio/istio/pull/6690
