### ISSUE TITLE
How to access the dashboard of prometheus and servicegraph after istio 0.8 is installed?

### ISSUE THREAD

**Issue by dongdan39** [istio/istio#6652]
Hi, Experts,
  I have installed istio 0.8 on my kubernetes 1.10 cluster and all components are running. Besides that, the bookinfo example are tested and runs successfully. But one question, I could not find out how to access the dashboard of prometheus and servicegraph although they are running there:
# kubectl get svc --all-namespaces
default        details                    ClusterIP      10.102.15.55     <none>        9080/TCP                                                              2d
default        kubernetes                 ClusterIP      10.96.0.1        <none>        443/TCP                                                               6d
default        productpage                ClusterIP      10.108.105.110   <none>        9080/TCP                                                              2d
default        ratings                    ClusterIP      10.104.41.42     <none>        9080/TCP                                                              2d
default        reviews                    ClusterIP      10.110.74.9      <none>        9080/TCP                                                              2d
istio-system   grafana                    ClusterIP      10.101.176.137   <none>        3000/TCP                                                              6d
istio-system   istio-citadel              ClusterIP      10.106.71.189    <none>        8060/TCP,9093/TCP                                                     6d
istio-system   istio-egressgateway        ClusterIP      10.98.202.62     <none>        80/TCP,443/TCP                                                        6d
istio-system   istio-ingressgateway       NodePort       10.106.74.58     <none>        80:31380/TCP,443:31390/TCP,31400:31400/TCP                            6d
istio-system   istio-pilot                ClusterIP      10.106.111.9     <none>        15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   6d
istio-system   istio-policy               ClusterIP      10.99.6.217      <none>        9091/TCP,15004/TCP,9093/TCP                                           6d
istio-system   istio-sidecar-injector     ClusterIP      10.108.177.215   <none>        443/TCP                                                               6d
istio-system   istio-statsd-prom-bridge   ClusterIP      10.102.157.13    <none>        9102/TCP,9125/UDP                                                     6d
istio-system   istio-telemetry            ClusterIP      10.96.132.82     <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 6d
istio-system   prometheus                 ClusterIP      10.102.198.76    <none>        9090/TCP                                                              6d
istio-system   servicegraph               ClusterIP      10.101.35.245    <none>        8088/TCP                                                              6d
istio-system   tracing                    LoadBalancer   10.103.106.142   <pending>     80:31639/TCP                                                          6d
istio-system   zipkin                     ClusterIP      10.98.192.126    <none>        9411/TCP                                                              6d

  Do I have to modify install/kubernetes/istio-demo-auth.yaml somewhat and reinstall istio again? Thanks for your helps!
  Cheers,
  Dan

**Comment by rokii** [comment]
You can edit the svc prometheus&prometheus  to change type from ClusterIP to LoadBalancer. Then access the svc through external-ip

**Comment by dongdan39** [comment]
@rokii Thanks a lot, it works!

**Comment by HARISHDARA** [comment]
@rokli. Thanks for your help for me as well, but want to know why we need to change the type from ClusterIP to LoadBalancer. Just give some description, it will help to me.

**Comment by richardwxn** [comment]
@HARISHDARA ClusterIP makes the service available only within the cluster, to expose it externally you need to use LoadBalancer or NodePort
