### ISSUE TITLE
istio/pilot/pkg/proxy/envoy/v2 Test_Syncz is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#6653]
**Describe the bug**

istio/pilot/pkg/proxy/envoy/v2 Test_Syncz has been flaky and it blocks PR merges.

Examples:
https://circleci.com/gh/istio/istio/119705?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/2308/

**Expected behavior**
No flake

**Steps to reproduce the bug**
**Steps to reproduce the behavior.**

**Version**
N/A

**Is Istio Auth enabled or not?**
N/A

**Environment**
Happened to both CircleCI and Prow tests.

**Comment by ymesika** [comment]
I think it's related to a bug I solved yesterday: #6632

**Comment by cmluciano** [comment]
closing due to staleness
