### ISSUE TITLE
Routing rules do not take effect

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#666]
With istio/istio latest head at 671b2dddb3ceb267c56851a1172b832d197b82bc
Tried the bookinfo in the default namespace, it works.
Applied default routing rules 
kubectl create -f samples/apps/bookinfo/rules/route-rule-all-v1.yaml

There is no effect, I still see a round robin distribution of no stars, red stars, black stars.

**Comment by andraxylia** [comment]
cc @kyessenov @frankbu

**Comment by andraxylia** [comment]
Operator error.

**Comment by darren-fu** [comment]
@andraxylia  meet seam error, may I know how to deal with this?
