### ISSUE TITLE
Helm install should support domain param

### ISSUE THREAD

**Issue by rokii** [istio/istio#6661]
**Is your feature request related to a problem? Please describe.**
Refer to https://github.com/istio/istio/issues/6313

**Describe the solution you'd like**
Since  Pilot has parameter --domain and there are fixed domain suffix in the yaml templates(e.g. [configmap](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/configmap.yaml#L23-L24)), helm install should provide a param for user customization of --cluster-domain argument in k8s.

**Comment by AWKIF** [comment]
this would be great indeed

**Comment by costinm** [comment]
Sounds reasonable - but not sure if we'll have time to test it in 1.0 
The helm change doesn't seem too big - but if we add a param we need to also test it, and we don't have
infrastructure in place. I don't know if any code is also making this assumption. 
Adding an option without testing it is risky.

**Comment by Rigdon** [comment]
Multi-cluster should eventually support this as well. Currently the secret used to tell pilot about remote clusters doesn't have an option to indicate the remote clusters custom domain even if Pilot supported it.
