### ISSUE TITLE
Inaccurate instructions to setup INGRESS_HOST environment variable

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio#6663]
Instructions to setup `INGRESS_HOST` at https://istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports says:

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

Where as, what worked was:

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
```

**Comment by ymesika** [comment]
Issue moved to [istio/istio.github.io #1603](https://github.com/istio/istio.github.io/issues/1603) via [**ZenHub**](https://www.zenhub.com/)
