### ISSUE TITLE
COPY button for a code copies $ sign

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio#6664]
On https://istio.io/docs/guides/bookinfo/, clicking on the COPY button of the following code:

```
   $ export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
```

copies the `$` as well. This makes it annoying to copy/paste the command in a terminal. 

For other boxes, `$` is not copied.

**Comment by rcurran1** [comment]
Fixed on master: https://preliminary.istio.io/docs/guides/bookinfo/
via https://github.com/istio/istio.github.io/pull/1558
Also note that this issue should have been opened under: https://github.com/istio/istio.github.io/issues
(this is the repo for the Istio docs.)
