### ISSUE TITLE
Wrong secret name in the Helm template of the egressgateway

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#6667]
**Describe the bug**

Egress gateway Helm template contains `istio.default` as the secret name, should be `istio.istio-egressgateway-service-account`. The bug is fixed in master by https://github.com/istio/istio/pull/6350 on master , I would like to have it in 0.8.1.

Due to the wrong secret name, mTLS between a sidecar proxy and the egress gateway will fail.

**Expected behavior**
Directing egress traffic from an application pod to the egress gateway should work when Istio is deployed with mTLS.

**Steps to reproduce the bug**
Follow the steps in https://github.com/istio/istio.github.io/pull/1605 for Istio with mTLS.

**Version**
The release 0.8.0.

**Is Istio Auth enabled or not?**
Yes.

**Environment**
Kubernetes.

**Comment by hklai** [comment]
Added in https://github.com/istio/istio/issues/5982. Please use it for further request.

**Comment by vadimeisenbergibm** [comment]
@hklai I see, will do.

**Comment by hklai** [comment]
As noted in #5982, we do not intend to cut 0.8.1 anymore since 1.0 is right around the corner. 

Closing this for now.
