### ISSUE TITLE
Clarify TLS ServiceEntries/VirtualServices semantics

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#6676]
I would like to use this issue to discuss TLS ServiceEntry/VirtualService semantics, related to https://github.com/istio/istio/pull/6402.

- First, the semantics of HTTP ServiceEntries/VirtualServices is as follows:
One can define HTTP service entries for `www.google.com` and `edition.cnn.com`. Then an HTTP request sent to `www.google.com` will be routed by the HOST header to `wwww.google.com`, and an HTTP request sent to `edition.cnn.com` will be routed to `edition.cnn.com`.In the case of HTTP, there are two values related to the destination: the destination IP and the HOST header. The default routing is performed by the HOST header, without the need to define any  `VirtualService`.  Now suppose one wants to change the default routing behavior and to forward an HTTP  request with the HOST header `edition.cnn.com` to `www.foxnews.com`. They can define a `VirtualService` that will forward HTTP requests with HOST header `edition.cnn.com` to `www.foxnews.com`, by specifying `http` `match` by `authority`.

- Now I propose the following semantics for TLS ServiceEntries/VirtualServices, by analogy with their HTTP counterparts:
One can define TLS service entries for `www.google.com` and `edition.cnn.com`. Then an HTTPS request sent to `www.google.com` will be routed by the SNI value to `wwww.google.com`, and an HTTPS request sent to `edition.cnn.com` will be routed to `edition.cnn.com`. In the case of TLS, there are two values related to the destination: the destination IP and the SNI value. The default routing is performed by the SNI value, without the need to define any `VirtualService`. Now suppose one wants to change the default routing behavior and to forward a  request with SNI value `edition.cnn.com` to `www.foxnews.com`. They can define a `VirtualService` that will forward HTTPS requests with the SNI value `edition.cnn.com` to `www.foxnews.com`, by specifying `tls` `match` by `sni_domains`.

Any comments are welcome.

**Comment by vadimeisenbergibm** [comment]
@louiscryan @rshriram @ijsnellf @frankbu - what do you think?

**Comment by rshriram** [comment]
I think the contentious issue here is one of auto inferring SNI names based on the host value. With HTTP, service name is same as HTTP Host header (or most often). but with TLS, it may not be the case. Especially when people have wildcard certs, e.g., they declare foo.bar.com, abc.bar.com as TLS ports and have a common *.bar.com cert. 
Also, think of SNI based routing as a mode of tunnelling. We would want to support other tunnelling protocols in future ( PROXY protocol, CONNECT protocol, etc.). Having a explicit way to model that is helpful. 
From that point of view, unless a virtual service is bound to a service with a TLS port (and the virtual service uses SNI routing), we should treat the TLS ports as TCP ports by default as traffic is opaque to us.

**Comment by vadimeisenbergibm** [comment]
Consider the documentation of Istio Egress:
1.  Create an `ServiceEntry` to allow access to an external HTTP service:

    ```
    $ cat <<EOF | istioctl create -f -
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: httpbin-ext
    spec:
      hosts:
      - httpbin.org
      ports:
      - number: 80
        name: http
        protocol: HTTP
    EOF
    ```

1.  Create an `ServiceEntry` to allow access to an external HTTPS service:

    ```
    $ cat <<EOF | istioctl create -f -
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: google
    spec:
      hosts:
      - www.google.com
      ports:
      - number: 443
        name: https
        protocol: HTTPS
    EOF
    ```

### Make requests to the external services

1.  Exec into the pod being used as the test source. For example,
    if you are using the sleep service, run the following commands:

    ```
    $ export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
    $ kubectl exec -it $SOURCE_POD -c sleep bash
    root@sleep-7ccd8d5c6-8p8zn:/#
    ```

1.  Make a request to the external HTTP service:

    ```
    $ curl http://httpbin.org/headers
    {"headers":{"Accept":"*/*","Connection":"close","Host":"httpbin.org","User-Agent":"curl/7.35.0",...
    ```

1.  Make a request to some other HTTP service and verify that the access is not possible,
the _404 Not Found_ error is returned:

    ```
    $ curl -s -w "%{http_code}\n" -o /dev/null http://edition.cnn.com
    404
    ```

1.  Make a request to the external HTTPS service:

    ```
    $ curl -s https://www.google.com | grep -o '<title>.*</title>'
    <title>Google</title>
    ```

1.  Make a request to some other HTTPS service and verify that the access is not possible,
    the _404 Not Found_ error is returned:

    ```
    $ curl -s -w "%{http_code}\n" -o /dev/null https://edition.cnn.com
    200
    ```

Note that in the last step 200 is returned, once a user defines an HTTPS ServiceEntry for _www.google.com_, access to all the HTTPS services is allowed, which is counterintuitive
. For HTTP, if you allow access to  _httpbin.org_, only access to _httpbin.org_ allowed.

I can change the documentation to define a TLS VirtualService for HTTPS services to restrict access to _www.google.com_, I am afraid that could be confusing users.
