### ISSUE TITLE
Egress using https causing SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by wralph** [istio/istio#6694]
**Describe the bug**
I wanted to configure some egress to call external services. To do so I have specified egress policies according to the documentation here -> https://istio.io/docs/tasks/traffic-management/egress/
To keep it simple I kept with the example from the doc but am using bbc.com instead of google.com.
Although I can not call an https endpoint from within my pods due to the following error.
```
/ # curl https://www.bbc.com/robots.txt --verbose
*   Trying 212.58.244.67...
* TCP_NODELAY set
* Connected to www.bbc.com (212.58.244.67) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Closing connection 0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
 
 
Although when using this format it works.
 
 
/ # curl http://www.bbc.com:443/robots.txt --verbose
*   Trying 212.58.244.27...
* TCP_NODELAY set
* Connected to www.bbc.com (212.58.244.27) port 443 (#0)
> GET /robots.txt HTTP/1.1
> Host: www.bbc.com:443
> User-Agent: curl/7.55.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: envoy
< cache-control: max-age=3600, public
< content-type: text/plain
< date: Wed, 27 Jun 2018 09:44:02 GMT
< keep-alive: timeout=10, max=1000
< accept-ranges: bytes
< etag: "2da-56e19d5566500"
< last-modified: Fri, 08 Jun 2018 04:28:36 GMT
< content-length: 730
< x-envoy-upstream-service-time: 45
…
```

**Expected behavior**
I was hoping to be able to call an external service via https

**Steps to reproduce the bug**
Follow the egress tutorial and start a curl container, governmentpaas/curl-ssl in my case. From that container call curl https://www.bbc.com/robots.txt

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
 
 
k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
I also tried the same using Istio daily build(istio-release-1.0.0-snapshot.0-20180622-17-43)
**Is Istio Auth enabled or not?**
No auth enabled

**Environment**
Azure AKS

Any help or hint is highly appreciated.

**Comment by vadimeisenbergibm** [comment]
Could you please attach your Service Entry definition?

**Comment by vadimeisenbergibm** [comment]
@wralph Yes, the destination rule is used for TLS origination, when the service entry is HTTP, and there is a requirement to connect to the destination by HTTPS.

In your case the service entry is HTTPS, it means that the origination is performed by the client application.

More on TLS origination - https://istio.io/docs/tasks/traffic-management/egress-tls-origination/
