### ISSUE TITLE
Isito sidecar impacted performance a lot

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#6697]
I was following steps at https://github.com/istio/istio/blob/master/tools/README.md to test the performance of istio, and focusing on two cases:

- service communication without sidecar 
- service communication with sidecar

![image](https://user-images.githubusercontent.com/4461983/42026306-608a8e0a-7af9-11e8-88e7-59394245691e.png)

And I found that the performance with sidecar is almost 40+ times slow compared without sidecar.

Performance between services with sidecar container
![image](https://user-images.githubusercontent.com/4461983/42026391-8f17ce5e-7af9-11e8-9a15-6d52e142f2da.png)

Performance between services without sidecar container
![image](https://user-images.githubusercontent.com/4461983/42026416-9ed99ec6-7af9-11e8-87d9-64fbd96745c9.png)

We can see the QPS for without sidecar is 4949 while 123.7 with sidecar, why did the QPS impact so much with sidecar container?

I was using istio 0.8.0 for this test, has anyone test such scenario and what is the impact of the sidecar container?

/cc @suryadu @ldemailly @morvencao

**Comment by ldemailly** [comment]
please also see
https://github.com/istio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass
or use the script in tools/ as right now you tested with the default 8 connections which is not meant to work for real test, as latency increases you need more connection to sustain the same throughput

**Comment by gyliu513** [comment]
@ldemailly thanks for the explantation, still not clear why the performance test has so much difference between with and without sidecar, can you elaborate more for this?

Also what is the impact of `v1alpha3`? Does the perf improved for this? Where is the PR?

We also test with 48 connections but found the result is almost same, will check https://github.com/istio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass for more detail.

**Comment by ldemailly** [comment]
#6658 is the PR aiming to convert to v1alpha3 but when @rkpagadala is testing it, the ingress doesn't seem to work (though not sure yet if the issue is something unrelated)

**Comment by gyliu513** [comment]
@ldemailly I think this will not impact the performance, but we are trying to compare the performance between ingress and ingressgateway soon.

Still have some concern why the performance test has so much difference between with and without sidecar, did you also got same result when doing the tests? This might be a big impact for customer deploy istio to production.

**Comment by gyliu513** [comment]
@ldemailly but there are indeed customer want to get some overhead for the sidecar, anyway that I can test this?

Also if this case is not valid, I think we should remove it from  https://github.com/istio/istio/blob/master/tools/README.md ?

**Comment by ldemailly** [comment]
I don't think we understand each other
please review the second part of https://istio.io/docs/performance-and-scalability/scalability/
which is determined using
https://istio.io/docs/performance-and-scalability/synthetic-benchmarks/
which is done using
https://github.com/istio/istio/blob/master/tools/README.md
