### ISSUE TITLE
When first connection to fluentd fails, fluentd adaptor is disabled.

### ISSUE THREAD

**Issue by bgokden** [istio/istio#6699]
**Describe the bug**
When first connection to fluend fails, fluentd adaptor is disabled.
Create a fluend adapter while fluentd service is not available.
We observed this problem when fluentd is restarted or not ready yet.

In our environment,
we have a mapping creation at start up, it requires to fluentd connect to Elasticsearch.
Elasticsearch starts slowly and fluentd elasticsearch pligin restarts fluentd if connection to Elasticsearch fails.
Mixer fluentd adapter disables itself if the fluent is not ready.
This happens sporadically.

**Expected behavior**
Adapter retires to connect to fluentd service.

**Steps to reproduce the bug**
Create a fluentd adapter while fluentd is not available.
Follow the demo of fluentd logging https://istio.io/docs/tasks/telemetry/fluentd/
Kill or don't start fluentd.

**Version**
kubernetes: v1.9.7-gke.3
istio: 0.8

**Is Istio Auth enabled or not?**
No

**Environment**
GCP

**Comment by bgokden** [comment]
Our proposed solution is to change the  line at https://github.com/istio/istio/blob/c0f1ea7471bbef8f9912e7cf54d2ffdb8fd452de/mixer/adapter/fluentd/fluentd.go#L78

To:
`han.logger, err = fluent.New(fluent.Config{FluentPort: p, FluentHost: h, Async: true})`

It will enable async client, and fluentd client will handle the connection failures.

**Comment by sdake** [comment]
@douglas-reid looks like a simple change, can you take a look?

**Comment by douglas-reid** [comment]
assigning to @jeffmendoza who wrote the fluentd adapter.

**Comment by jeffmendoza** [comment]
Sounds great. We are vendored to v1.3.0, the latest release

https://github.com/istio/istio/blob/master/Gopkg.toml#L116
https://github.com/fluent/fluent-logger-golang/releases

I'm not sure this change is included in the latest release, it might be more recent. CC @tagomoris @alexlrt if they can provide any insight. Thanks!

**Comment by alexlry** [comment]
Hi guys, the "Async: true" was not released in v.1.3.0 and is only available in master. You can instead use "AsyncConnect: true" with v1.3.0 and it should work just fine.

However, please note v1.3.0 can panic if your fluent service is down for a long time. This is solved with latest changes from PR fluent/fluent-logger-golang#56 along with performance improvements of asynchronous mode.
I don't know what are @tagomoris plans regarding new release but I'm using fluent/fluent-logger-golang master on production environment with 1000+ logs / seconds with no problem.

**Comment by jeffmendoza** [comment]
@bgokden See comment above, we can update Gopkg.toml to a recent SHA including the latest behaviour and change to `Async: true`. Are you interested in submitting this PR?

**Comment by bgokden** [comment]
@jeffmendoza yes, I want to submit at as pr.

**Comment by jeffmendoza** [comment]
Sounds great!
