### ISSUE TITLE
Running E2E simple tests with Helm takes 15 minutes extra and doesn't delete namespace

### ISSUE THREAD

**Issue by akshaymankar** [istio/istio#6700]
**Describe the bug**
When I run `make test e2e_simple_run TAG='0.8.0' E2E_ARGS='--installer=helm'`, the tests keep waiting with this message:

```
Deleting namespace simple-auth-test-2ff8de94cbcf40109b24
```
It seems like the test code doesn't delete namespace and keeps waiting for 10 minutes and then moves on anyways.

**Expected behavior**

The tests should delete the namespace and not take so long to finish.

**Steps to reproduce the bug**
Checkout to `0.8.0` tag and run
```
make test e2e_simple_run TAG='0.8.0' E2E_ARGS='--installer=helm'
```

**Version**
Istio: 0.8.0
Kubectl and Kubernetes: 1.10.4
Helm client & server: 2.9.1

**Comment by sdake** [comment]
@akshaymankar thanks for contribution of the bug report.  This will be addressed when time permits.  We are working very hard to release 1.0 on schedule, and this particular problem, while annoying, doesn't seem to be a P0 or P1 as per 1.0 release criteria.

Cheers
-steve

**Comment by akshaymankar** [comment]
@sdake I can understand. I will submit a PR, it should be a small one. Hopefully it can be merged in the earliest release.

**Comment by akshaymankar** [comment]
The related PR seems to have been merged, so I am closing this.
