### ISSUE TITLE
Istio Telemetry retention issues causing Prometheus death

### ISSUE THREAD

**Issue by Stono** [istio/istio#6741]
Hey, 
As discussed with @douglas-reid we have a big problem with prometheus and mixer.  At a high level we:

  - Have a very high turnover development environment, which results in mixer returning a very high number of metrics due to the cardinality around IP's, pod names etc.  
  - We have been tweaking prometheus retention lower and lower, only to realise the issue wasn't actually the amount of data per metric, but the number of metrics that was causing the problem.
  - Deleting the data in prometheus, and bringing it back up results in it pulling __all__ metrics for long gone historical pods, since the moment mixer was born, thus repopulating prometheus and, killing it (with metric fire).

So my question/statement is:  We need to be able to control the retention period of metrics exposed by the `/metrics` endpoint of istio-telemetry.

**Hacky Workaround**
I've created a cron job that deletes mixer every 12 hours, which resets the metrics.

This is a brand new prometheus instance that's instantly repopulated from mixer:

<img width="1214" alt="screen shot 2018-06-29 at 19 51 54" src="https://user-images.githubusercontent.com/1486729/42110357-b6239bb0-7bd8-11e8-98d1-c3d4d63300ec.png">

Here is the output from `/metrics`
<img width="1162" alt="screen shot 2018-06-29 at 19 38 15" src="https://user-images.githubusercontent.com/1486729/42110369-c222d3d6-7bd8-11e8-86e0-065291c9e289.png">

#pleasesavemyprometheus

**Comment by douglas-reid** [comment]
There is a way to purge old labels from a vec. It will take a little custom config in the prom adapter, but we should be able to put something together. Still need to reflect on proper way to deal with long-lived stale metrics.

**Comment by Stono** [comment]
Having it configurable for us is also key, as we'd most likely want a lower setting in our pre-prod, higher turnover environments

**Comment by Stono** [comment]
Thinking about this a little more, there'd be no need to expose things in /metrics for any longer than `prometheus scrape period`?

I don't know the ins and outs here but if there was a way to detect a certain cardinality of metrics as stale/dead/no longer exists, you could probably get rid of it after say, 10 minutes?

**Comment by douglas-reid** [comment]
@Stono yeah, that's the general idea i have too. but i'm not sure if there is a built-in way to expire, or if we need to build it.

**Comment by nmittler** [comment]
@smawson can we make this a P0?

**Comment by Stono** [comment]
@douglas-reid I don't think this is going to help....
Long story short if the metrics expire from mixer, they seem to get back-deleted from prometheus.

You can observe this behaviour by simply restarting mixer, then querying prometheus and you'll see `istio_request_count` is totally empty.

**Comment by Stono** [comment]
@douglas-reid a broader question... why do we create metrics named per application and not variablised?

eg.

`envoy_cluster_inbound_80__app_consumer_platform_svc_cluster_local_external_upstream_rq_200`

vs:

`envoy_cluster_inbound_80_external_upstream_rq_200{service="app.consumer-platform.svc.cluster.local"}`

**Comment by Stono** [comment]
^^ just realised that by removing the `envoy` scrape job, i get rid of all those keys that we don't actually use.

**Comment by nmittler** [comment]
@douglas-reid what's the status? Will we have something in place for 1.1?

**Comment by douglas-reid** [comment]
@nmittler we have a mixer-focused PR available. we can merge it anytime.

**Comment by nmittler** [comment]
@douglas-reid any reason that you haven't merged it yet?

**Comment by douglas-reid** [comment]
@nmittler well, it seemed a bit risky for 1.0, and I've been on vacation :).

**Comment by nmittler** [comment]
@douglas-reid ah ok, makes sense ... and I hope I haven't been pestering you on your vacation :). Cheers!

**Comment by douglas-reid** [comment]
@nmittler no worries. as soon as the PR gets the LG/Approval, it can be merged.

**Comment by douglas-reid** [comment]
Closing, as this is now a supported install option in `release-1.1` branch: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/mixer/templates/config.yaml#L603
