### ISSUE TITLE
Security integration tests are failing

### ISSUE THREAD

**Issue by hklai** [istio/istio#6756]
The security integration tests have been disabled in https://github.com/istio/istio/pull/6752, because they started failing in setup.

Example:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6752/istio-presubmit/13856/

I0629 22:52:24.766] 2018-06-29T22:52:24.761283Z	error	failed to create test namespace: failed to create a role (error: failed to create role (error: roles.rbac.authorization.k8s.io "istio-ca-role" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:["core"], Verbs:["update"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:["core"], Verbs:["list"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["serviceaccounts"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]}] user=&{chx@google.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]))
I0629 22:52:24.766] 2018-06-29T22:52:24.761405Z	error	test environment creation failure
I0629 22:52:24.766] FAIL	istio.io/istio/security/tests/integration/certificateRotationTest	0.695s
E0629 22:52:24.789] Build failed

The timing of these failure collide with the test cluster being recycled today. Not sure if there is any permission setup with the test cluster.

**Comment by hklai** [comment]
Need more work

**Comment by JimmyCYJ** [comment]
These tests are obsolete. Once we have new test framework running Citadel and nodeagent, we can add new tests to cover Citadel and nodeagent.
