### ISSUE TITLE
TCP proxy from istio gateway to MTLS service fails.

### ISSUE THREAD

**Issue by costinm** [istio/istio#6757]
I got a TCP proxy working great, with mtls disabled.

Same service, with a DestinationRule and policy setting mtls - fails. Spent some time debugging, will restart next week - we need to sort it out for 1.0

Please try lastest 1.0 build and create a TCP proxy with mtls enabled for any service, let me know if you get it working. (one way to do it is to declare the port as tcp on fortio, or use the test app)

**Comment by wattli** [comment]
@costinm , i would be great if you could provide the DestinationRule and AuthPolicy in this issue, which would make it easier for the reproduce. And have you tried the http proxy with mTLS?
