### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by veotax** [istio/istio#6760]
I saw there's a working-in-progress PR here: https://github.com/istio/istio/issues/6377. I don't know if it's too late, but there's a library called [Casbin](https://github.com/casbin/casbin) that already provides the RBAC functionality.

In functionality, in the above PR, the RESTful scenario of ``user, method, path``, the IP match (match an IP with a network address), the prefix match (like /books/*), the RBAC role, and the ABAC attributes. These features are all covered by Casbin. RBAC roles in Casbin also support role hierarchy.

In maintainability, Casbin provides good logging. I saw the tests in the PR but it looks incomplete. Casbin provides more complete testing even for corner cases. Correctness is very important for authorization. Morever, Casbin also provides a online policy grammar checker here: http://casbin.org/editor/, which will help security member to design authorization policy rules. Casbin also supports storing policy into dozens of DBs, which is convenient.

I think it's better to use Casbin as the authorization engine for this project, what do you think? Thanks.

**Comment by yangminzhu** [comment]
Thanks for the report Dave, I think currently we don't have plans to use Casbin as the authz engine in Istio, but we could definitely investigate about supporting custom authz engine if there are any actual user case.

For Istio RBAC, It's already implemented before #6377 and it's actually an enhancement to the existing implementation, Also check [here](https://istio.io/docs/concepts/security/rbac/) for more information about Istio RBAC.
 
/cc @liminw
