### ISSUE TITLE
ImagePullBackOff Error For 0.8.0

### ISSUE THREAD

**Issue by namsoila** [istio/istio#6772]
**Describe the bug**
Running on GKE 1.10.4-gke.2. Using the following to setup istio:

`kubectl apply -f install/kubernetes/istio-demo-auth.yaml`

Services are installed without error but pods have numerous ImagePullBackOff errors:

```
grafana-6f6dff9986-hkr57                   0/1       ImagePullBackOff
istio-citadel-7bdc7775c7-8mrlx             0/1       ImagePullBackOff
istio-cleanup-old-ca-vztk5                 0/1       ErrImagePull
istio-egressgateway-78dd788b6d-qjt9x       0/1       Error
istio-ingressgateway-7dd84b68d6-t9gfp      0/1       Error 
istio-mixer-post-install-5sw4k             0/1       ImagePullBackOff
istio-policy-64595c6fff-4s7sn              1/2       ImagePullBackOff
istio-statsd-prom-bridge-949999c4c-gxrjt   0/1       ImagePullBackOff
istio-telemetry-cfb674b6c-5z6v7            1/2       ImagePullBackOff 
istio-tracing-754cdfd695-nz9bf             0/1       ImagePullBackOff
servicegraph-5849b7d696-krcvc              0/1       ImagePullBackOff
```

Running `kubectl describe` for one of the pods yields:

`Failed to pull image "docker.io/istio/grafana:0.8.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Expected behavior**

All pods are supposed to be running. Currently, only a few are such as:

```
prometheus-86cb6dd77c-z78hl                1/1       Running             0          10m
istio-ingressgateway-7dd84b68d6-t9gfp      1/1       Running             2          10m
istio-egressgateway-78dd788b6d-qjt9x       1/1       Running             2          10m
```

**Steps to reproduce the bug**

Create a GKE 1.10.4-gke.2 cluser and follow instructions here:

https://istio.io/docs/setup/kubernetes/quick-start/

Using the following command:

`kubectl apply -f install/kubernetes/istio-demo-auth.yaml`

**Version**
istioctl version:

Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version:

v1.10.4-gke.2

**Is Istio Auth enabled or not?**

Using istio-auth.yaml

**Environment**

GKE v1.10.4-gke.2

https://github.com/istio/old_issues_repo/issues/387

https://github.com/istio/istio/issues/6433

**Comment by namsoila** [comment]
This was due to creating a private gke cluster. Will resolve based on gke setup since istio setup running on non private gke has all pods running.

**Comment by ishankhare07** [comment]
For people still facing this issue AND trying to setup istio on a **private** cluster. You would need to setup cloud NAT so that the cluster can fetch control plane docker images from docker hub.
