### ISSUE TITLE
Be able to change default k8s cluster domain

### ISSUE THREAD

**Issue by AWKIF** [istio/istio#6779]
**Is your feature request related to a problem? Please describe.**
My default k8s cluster domain is not "cluster.local"

**Describe the solution you'd like**
I'd like to be able to change my cluster domain easily

**Describe alternatives you've considered**
Manually change/add param to the default istio-demo.yaml

Thank you !

**Comment by rokii** [comment]
same requirement https://github.com/istio/istio/issues/6661

**Comment by rshriram** [comment]
closed as duplicate
