### ISSUE TITLE
Unable to get running virtual services

### ISSUE THREAD

**Issue by vishalpandey2192** [istio/istio#6791]
**Describe the bug**
I am running istio using consul , While deploying any configuration/application, lets say the official bookinfo sample, after successfully deploying the required yaml files when I run istioctl get virtualservices, I get an error  Error: the server could not find the requested resource (get virtualservices.networking.istio.io)

**Expected behavior**
This command should give a list of all running virtualservices

**Steps to reproduce the bug**
Steps to reproduce the behavior.
1. Install istio
2.Go to samples/bookinfo
3. Run - docker-compose -f samples/bookinfo/consul/bookinfo.yaml up -d
docker-compose -f samples/bookinfo/consul/bookinfo.sidecars.yaml up -d
4. run istioctl get virtualservices

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

istioctl - 0.80
Running on consul

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
Yes

**Environment**
Which environment, cloud vendor, OS, etc are you using?
Running locally using consul

**Comment by louiscryan** [comment]
not stale
