### ISSUE TITLE
Use SNI in telemetry reports and policy checks

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#6810]
**Is your feature request related to a problem? Please describe.**
The problem: lack of monitoring and access policies based on the SNI value of TLS handshake.

**Describe the solution you'd like**
Istio proxy should be able to extract the SNI value from the TLS connection and to send it to telemetry and policy components.

**Comment by kyessenov** [comment]
The process to add attributes is as follows:
1. define a new attribute in the compression dictionary: https://github.com/istio/api/blob/master/mixer/v1/global_dictionary.yaml
2. document a new attribute on the website
3. implement extraction in proxy; related to this, we should work out upstream/downstream connection differences
4. expose the attribute to mixer adapters using mixer's config.yaml
5. publish it to prometheus/metrics adapters

**Comment by vadimeisenbergibm** [comment]
The implementing PRs:
https://github.com/istio/api/pull/575
https://github.com/istio/istio.github.io/pull/1712
https://github.com/istio/proxy/pull/1843

**Comment by vadimeisenbergibm** [comment]
@kyessenov @douglas-reid Could you please review the PRs in https://github.com/istio/istio/issues/6810#issuecomment-403793802 ?

**Comment by vadimeisenbergibm** [comment]
@hklai Could you please merge the PRs: istio/api#575 and istio/istio.github.io#1712, related to this issue?

**Comment by kyessenov** [comment]
This was merged too early...

**Comment by kyessenov** [comment]
Please update API dependency ASAP. Otherwise, there is a risk of breaking
mixer protocol.

**Comment by vadimeisenbergibm** [comment]
@costinm Could you please help me with merging these PRs? I think we are just several hours from having SNI enabled for monitoring and policy enforcement. It would be a pity if Istio 1.0 is released without support for SNI monitoring/logging and SNI-based policies. We have routing by SNI, we have everything ready to handle SNI, seems to me a pity not to merge it. cc @kyessenov @rshriram @hklai @linsun

**Comment by hklai** [comment]
@vadimeisenbergibm I have merged istio/api#575 but I had to revert #1843 as I apparently merged it prematurely. Please resend it with @qiwzhang's [comment](https://github.com/istio/proxy/pull/1843#pullrequestreview-136010880) addressed?

**Comment by kyessenov** [comment]
This seems to have been done, testing will be a follow-up as we establish local mTLS envoy tests.

**Comment by vadimeisenbergibm** [comment]
The SNI reporting does not work, requires debugging, removing it before the release.

**Comment by vadimeisenbergibm** [comment]
The PR to remove the SNI attribute https://github.com/istio/istio/pull/7278.

**Comment by douglas-reid** [comment]
@vadimeisenbergibm what is the current status of this issue?

**Comment by vadimeisenbergibm** [comment]
@douglas-reid It works, documented in https://preliminary.istio.io/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies/.

Closing the issue.
