### ISSUE TITLE
e2e smoke test: need dedicated node for fortio or wrk

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#682]
It has been observed during e2e tests the qps can be increased with more nodes are added. To get more deterministic results, we need to run the traffic generator (fortio or wrk) on its own node.

**Comment by ldemailly** [comment]
#833 is/has an evolving example of that

**Comment by ldemailly** [comment]
it's not in e2e but scripts to create a vm and run fortio are part of the perf setup

https://github.com/istio/istio/blob/master/tools/setup_perf_cluster.sh#L61-L89
