### ISSUE TITLE
Generate a single istio-demo.yaml, with a subset of services using mtls

### ISSUE THREAD

**Issue by costinm** [istio/istio#6825]
In previous versions we distributed 2 installs - with mtls on by default and off by default. 

Now we have ability to do per-service policy config as well as transparent migration - it would be great for the 'default' demo to showcase those 2 features, and no longer distribute one with no mtls and one with all mtls. 

We could set a policy and destination rule for one of the services to be mtls, another to be 'permissive' - and ship a single demo file.

**Comment by costinm** [comment]
@rshriram  
This will also help reduce the use of the global mtls setting - and point users to the new API.

**Comment by wattli** [comment]
@costinm , the istio-demo-auth.yaml actually implements the global AuthPolicy/DestRule already, see https://github.com/istio/istio/issues/5900, and this actually hides some details from customers so they don't have to understand the fancy policy/rule if they just want global mTLS works

**Comment by costinm** [comment]
My point was that the default demo should have 1-2 services with mtls
enabled.

Users should be able to enable global mtls when using helm template - it's
not a big deal if we keep
distributing istio-demo-auth.yaml, but most users (AFAIK) are using
istio-demo.yaml to get started
and it would help for it to have AuthPolicy/DestRule samples for mtls.
