### ISSUE TITLE
Remove job(s) that handled 0.8-to-1 mitgration

### ISSUE THREAD

**Issue by ayj** [istio/istio#6836]
ref: [istio-clean-old-ca](https://github.com/istio/istio/blob/560c9f991fbdfa325fe81a5a180794ecfcb5285b/install/kubernetes/helm/istio/charts/security/templates/cleanup-old-ca.yaml#L1
) and possibly [istio-clean-secrets](https://github.com/istio/istio/blob/560c9f991fbdfa325fe81a5a180794ecfcb5285b/install/kubernetes/helm/istio/charts/security/templates/cleanup-secrets.yaml#L65)

**Comment by ayj** [comment]
cc @costinm

**Comment by wattli** [comment]
@costinm , happy to take this. But is the migration done? Are we still having customers with 0.8 and would like to migrate to 1.0 later?

**Comment by wattli** [comment]
CA clean up is done by https://github.com/istio/istio/pull/6947

and I don't think the secret clean up is for migration.
