### ISSUE TITLE
Consider consolidating post-install jobs for default istio configuration

### ISSUE THREAD

**Issue by ayj** [istio/istio#6837]
The default Istio installation includes network and policy configuration for the mixer and authentication (see  [istio-mixer-post-install](https://github.com/istio/istio/blob/560c9f991fbdfa325fe81a5a180794ecfcb5285b/install/kubernetes/helm/istio/charts/mixer/templates/create-custom-resources-job.yaml#L60) and [istio-security-post-install](https://github.com/istio/istio/blob/560c9f991fbdfa325fe81a5a180794ecfcb5285b/install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml#L55)). Post 1.0 we should re-evaluate how these resources are create during the install processes. 

cc @costinm @ozevren

**Comment by costinm** [comment]
More urgent: in 1.0 we need to cleanup the jobs that are no longer relevant
( the citadel rename, etc).
No point in shipping dead jobs.

**Comment by kyessenov** [comment]
This is breaking istio installation for me occasionally. It's a matter of luck : whether helm chooses to install mixer or pilot first. Might be noticeable on slower clusters (or clusters with slow masters that take longer to establish CRDs).
