### ISSUE TITLE
E2E tests fail with gke1.10 Prow Setup

### ISSUE THREAD

**Issue by hklai** [istio/istio#6838]
**Describe the bug**
pilot-e2e tests are consistently failing with gke 1.10 setup in Prow.
https://prow.istio.io/?job=istio-pilot-e2e-envoyv2-v1alpha3-k8s-1.10

This is likely a test setup problem as istio works with gke1.10 in manual testing.

**Expected behavior**
Test passes, just like the 1.9 variation.
https://prow.istio.io/?job=istio-pilot-e2e-envoyv2-v1alpha3

**Is Istio Auth enabled or not?**
No

**Comment by sebastienvas** [comment]
The setup is no different than 1.9. Did people try with alpha feature on on 1.10 ? I just created a PR to disable it in Boskos.

**Comment by hklai** [comment]
These tests actually have been restored.
https://prow.istio.io/?job=istio-pilot-e2e-envoyv2-v1alpha3-k8s-1.10

Could you re-enable them?

**Comment by sebastienvas** [comment]
I just disable the alpha feature for cluster creation. I don't think I need to re-enable it, right ?

**Comment by hklai** [comment]
Right.  I don't believe we need any alpha features.

**Comment by cmluciano** [comment]
Moving issue to GKE env, but this may be stale

**Comment by hklai** [comment]
Most prow e2e tests are now using 1.10 already, and a few are using 1.11.

We can close this.
