### ISSUE TITLE
Response time capped to 10s in dashboard

### ISSUE THREAD

**Issue by msogrin** [istio/istio#6843]
**Describe the bug**
Response time charts in dashboard seem to be capped at 10s, even when many requests take longer than that.

![image](https://user-images.githubusercontent.com/9539622/42274953-67f55454-7f86-11e8-86b9-d2141a47c1d0.png)

In the first portion in the screenshot above, istio-ingressgateway service has average (p50) response time ~4-5s, but other lines (p90, p95, p99) are all too close to 10s line to be believable.

istio-ingressgateway logs show a lot of requests go over 10s (and up to 30s in rare cases).
Response time measurements at client-side also show a lot of requests go over 10s

In the second portion in the screenshot, the service is loaded over its limit, so that all lines, including p50, cap at 10s. But client-side response time measurements were showing 12s average and lots of requests at ~30s. (Client was in a container deployed in the same cluster, but outside of Istio mesh).

**Expected behavior**
Istio dashboard charts show unaltered data, which could be relied upon.

**Steps to reproduce the bug**
Steps to reproduce the behavior.

**Version**
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-2+c8f1f59d8d233c", GitCommit:"c8f1f59d8d233c6e9a10cedd8aad4f43ad9ef5c7", GitTreeState:"clean", BuildDate:"2018-06-06T06:07:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
Not.

**Environment**
IBM Kubernetes service, paid cluster.

**Comment by erSitzt** [comment]
@msogrin 
Did you ever find out anything about the reason ?
I'm facing the same issue in my somewhat *old* Rancher 2.4.11 with Istio 1.5.9

<img width="710" alt="image" src="https://user-images.githubusercontent.com/1625376/205004413-1a10c0e6-89b8-4a97-b9e4-ded1cefd873b.png">

**Comment by erSitzt** [comment]
Hmm... i just found out that this is histogram data in buckets... the last two are 10s and Inf
So it seems this is just stored the wrong way at least for longer requests...
