### ISSUE TITLE
Test description "Control Egress TCP Traffic" uses deprecated api. 

### ISSUE THREAD

**Issue by axel7born** [istio/istio#6856]
**Describe the bug**
The test description of ["Control Egress TCP Traffic"](https://preliminary.istio.io/blog/2018/egress-tcp/)  on the Istio 1.0 Community Testing sheet uses deprecated api for route rules.
E.g. the description points to the file [samples/bookinfo/kube/route-rule-ratings-mysql.yaml](https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/kube/route-rule-ratings-mysql.yaml). In this file the kind RouteRoule is used. Later in the text the kind EgressRule is used. 

**Expected behavior**
The test description and sample files should be updated to use v1alpha3 route rules. 

**Steps to reproduce the bug**
Follow the instructions on https://preliminary.istio.io/blog/2018/egress-tcp/.

**Version**
```
$ istioctl version
Version: 1.0.0-snapshot.0
GitRevision: cf65e19c6a54df14d3a92de2221cc1e5153825de
User: root@5b39c9818787
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
 `helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.tag=1.0.0-snapshot.0 > $HOME/istio.yaml`

**Comment by frankbu** [comment]
@vadimeisenbergibm Do you have a PR in the works to update your egress blog post?

**Comment by vadimeisenbergibm** [comment]
@frankbu I will work on it this week.

**Comment by vadimeisenbergibm** [comment]
@jasmine-jaksic Will do it today or tomorrow, sorry, had urgent tasks to perform.

**Comment by vadimeisenbergibm** [comment]
@axel7born @jasmine-jaksic The PR merged, closing the issue.
