### ISSUE TITLE
Set default envoy timeout/retry/etc instead of using lots of virtualservices/destination rules

### ISSUE THREAD

**Issue by KresoDenis** [istio/istio#6861]
**Is your feature request related to a problem? Please describe.**
https://github.com/istio/istio/issues/6860
Even without this issue, this feature would be nice to have

**Describe the solution you'd like**
I would like to pass to all envoys to use default timeout of 60s

**Describe alternatives you've considered**
setting a lots of timeouts inbetween services

**Additional context**
Set default envoy timeout instead of using lots of virtualservices with specific timeouts. So i just want to increase deafult timeout of 15s to lets say 60s for all requests.

**Comment by utako** [comment]
@KresoDenis,

Does implementing this feature for 1.1 in favor of fixing #6860 work for you? In that case, do you want to close that issue?

For this feature: are you asking to change the default timeout to 60s, or to get rid of the ability to configure specific virtual service timeouts in favor of using the default timeout for everything?

**Comment by KresoDenis** [comment]
Main point is that i need to have timeouts larger than 15s (30-40s)

Istio cant set it lower than 15 seconds. My opinion is that it just cant set it lower than envoy default and it just happens that default is 15s.

In theory if i can raise default to 60 it will fix my issue, and hopefully even after that i can specify timeouts in VirtualService of 40s (since 40 is lower than 60 default that i will set)

Now question arises if issue is related to default envoy value or somewhere hardcoded to 15s.

I think both tickets are important.

But lets say that this request is finsihed i can set default to 60 and then use VirtualService to speicfy timeout values lower than that. Than  #6860 is still important but with lower priority becouse Timeout in VirtualService still cant be larger then default.

Lets say i have 50 services, and i want 49 to have 30 seconds, and only one 60s.

If the bug exists i have to set default to 60s, and then use 49 timeout overrides in VirtualServices to set them to 30s.

But if the bug is fixed, i set the default to 30s, and use only one overide in VS to 60s.

So basicly if this one is easier to do then yes it will solve it for me. But i think other should not be closed. But perhapse postponed and set with lower priority.

Currently i disabled Istio on our Prod since we have no way of using timeouts larger than 15s. 

So for me both tickets should fix my issue.

**Comment by jsw** [comment]
I would also like this feature. It's somewhat unexpected that there's a default timeout at all, and 15s seems pretty low to apply to an entire cluster. I want to set the default to a very high number (120+ seconds) so that it doesn't interfere with higher timeouts set by applications. When applications shift timeout/retry logic to the proxy, they can set lower values to override the high default.

Meanwhile, the workarounds to set a higher timeout are either a `VirtualService` or to set this header? https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#config-http-filters-router-x-envoy-upstream-rq-timeout-ms

**Comment by Stono** [comment]
There's a whole bunch of other defaults i'd be interested in too, like the RetryPolicy

**Comment by vaibhavjain882** [comment]
Do we have any solution for this? https://github.com/istio/istio/issues/6861#issuecomment-404676996
I want to increase the global timeout to 120 seconds.

**Comment by fierro-fuego** [comment]
Is there really no way to set global envoy defaults for all services in Istio without creating a VirtualService for each?

**Comment by linux-user001** [comment]
This sound like a legit request ...
Modifying the default value for timeout seems very basic to me ..

**Comment by Stono** [comment]
@howardjohn can we reopen this?

**Comment by howardjohn** [comment]
Yep

**Comment by chaudyg** [comment]
After looking at the code, I would suggest we disable the timeout all-together (PR is coming).

- There is no rational behind the current 15 seconds timeout. It comes comes from a unset `timeout` flag which default to 15s (see [codebase](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/httproute.go#L185-L200) and [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction))
- What would be a sensible value (other than disabling the timeout)? Some people want 15s, other 60, other 120+. It really falls down to what external endpoint you are trying to reach.
- Disabling it would be consistent with the timeout flag in the VS, which explicitly disable the timeout [see here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L399-L403)

**Comment by Stono** [comment]
I think it's worth baring in mind other oddities when setting a timeout to infinite, more people will run into things like this https://github.com/istio/istio/issues/18089#issuecomment-549842540 before they run into a 504 (which is more obvious as to the cause)

**Comment by howardjohn** [comment]
I think the above is strictly about timeout for passthrough cluster which cannot even be configured today. Slightly different than a global default

**Comment by chaudyg** [comment]
Good point @howardjohn . https://github.com/istio/istio/pull/19864 is only for passthrough cluster.

@Stono Do you think  https://github.com/istio/istio/issues/18089#issuecomment-549842540 also impacts egress traffic (passthrough cluster)? What's the easiest way to reproduce the 503 (did not manage).

Conceptually are we ok with the idea of disabling the timeout for egress traffic?

**Comment by Stono** [comment]
> Conceptually are we ok with the idea of disabling the timeout for egress traffic? 

If it's something that can't be configured today, for sure I would disable it.

> @Stono Do you think #18089 (comment) also impacts egress traffic (passthrough cluster)? What's the easiest way to reproduce the 503 (did not manage).

Not sure, but I'm guessing so.  Easiest way to repro is simply create some connections to an endpoint that takes say, 30 seconds to respond and then trigger something that causes a listener reload.  You'd believe that as 30 seconds is within the 45s default `drain duration` that they'd all be OK, but they won't be, they'll get terminated at different intervals.

**Comment by howardjohn** [comment]
I'm not sure if requests to passthrough cluster will be drained if the listener changes. My understanding is internally the connection may he transferred from the listener to the cluster (presumably the cluster never changes). Would be nice to verify

**Comment by rvennam** [comment]
Request from an Istio user: "How does one apply a timeout of 30s globally for all requests within the service mesh?"

**Comment by irl-segfault** [comment]
^ it seems like the only way is to modify the default sidecar injection template

**Comment by ddifranc** [comment]
I want this feature too.  I want to be able to increate the timeout for all of my 10s of microservices, without creating a VirtualService for each.

Is there any way to patch this in my installation, e.g. https://istio.io/docs/reference/config/networking/envoy-filter/ 
or settings in the helm chart?

**Comment by ramaraochavali** [comment]
@ddifranc If you are looking for setting a default timeout for all your services without virtual services, please follow this PR https://github.com/istio/istio/pull/21511 - It intends to do the same with flag in pilot.

**Comment by howardjohn** [comment]
Design doc for this: https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/

Useful comment from another duplicate issue: https://github.com/istio/istio/issues/26158#issuecomment-669703887

**Comment by puneetloya** [comment]
If this feature is fixed in the future,  Are these following features will be supported?
1) setting a global timeout would be supported 
2) This timeout will apply to tcp requests too.

**Comment by sidprak** [comment]
I might be misunderstanding the purpose of this setting, but based on https://github.com/istio/istio/pull/21511, I set the value of ISTIO_DEFAULT_REQUEST_TIMEOUT to globally configure a timeout for virtual services that don't define one. Does this accomplish the ask here?

**Comment by nrjpoddar** [comment]
@GregHanson @howardjohn afaict the work done in 1.9 didn't fix retry issue as the retry config currently resides in VirtualService and we only addresses DestinationRule knobs in 1.9. Is my understanding correct? Is anyone working on addressing VirtualService related fields like default retry config?

**Comment by howardjohn** [comment]
Yes that is correct. I don't know of any work on that but Greg may be

**Comment by howardjohn** [comment]
This is implemented in 1.12: https://github.com/istio/api/pull/2058
