### ISSUE TITLE
istioctl validate tool for k8s services 

### ISSUE THREAD

**Issue by rshriram** [istio/istio#6892]
We need to run istioctl on a k8s service to emit the following validation errors: ports not named correctly, protocol conflicts with other services/service entries in the system, warnings about headless services if any etc. 

We could combine this with as standalone client side validation -inject. Logic for this would involve fetching existing services, service entries, virtual services, etc. from kubernetes to run checks for port conflicts. 

This should help users avoid pitfalls like conflicting protocols on same port (cc @Stono) or common issues like ports not named properly or a port 80 service being called tcp, etc. the tool does not have to be exact/correct.  It simply has to emit warnings and pointers that would help users avoid pitfalls early in the process. It would run through a processing pipeline similar to pilot. Sort of a static pilot cli. 

Ideally before 1.0

**Comment by rshriram** [comment]
Could invoke networking library and emit warnings on console.

**Comment by Stono** [comment]
Hey, 
Just FYI we don't use istio inject to add the sidecar, it's done via the auto-injector.  Our pipelines and charts that deploy services to kubernetes, where possible, are istio agnostic (ie they should work on local kubernetes, and on our k8s clusters with istio enabled).

The added complexity here is that it implies that all services are deployed being concerned for istio - which isn't true for us.  For example; we have redis and rabbitmq in namespaces that explicitly aren't injected, aren't part of the mesh, yet their headless services still get detected by istio and cause conflicts.  So in that scenario, a team with absolutely no concern or care about istio, who most defiantly won't be using istioctl or any sort of istio validation tool can still cause us "mesh" issues.

I'm not dismissing its use in some circumstances by the way, I could add it to the CI/CD workflow for most of our common apps and it'd detect a bunch of stuff.  I just wanted to give you more context with regards to our multi-tenant cluster(s).

**Comment by murarisumit** [comment]
hi @rshriram  @ayj can I pick this issue, i was almost stuck for a day because of "ports were not named correctly".

**Comment by rshriram** [comment]
That would be great.. The AspenMesh folks have been working in istio-vet https://github.com/aspenmesh/istio-vet
I think that addresses most of this..

**Comment by murarisumit** [comment]
thanks @rshriram  for response.  I think it should part of istioctl  like `--validate` flag similar to `--configtest` in nginx. 

Should I work on to add it in istio or leave it for `istio-vet` tool ?

cc @nrjpoddar

**Comment by nrjpoddar** [comment]
@murarisumit here's [istio-vet](https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/serviceportprefix/README.md) vetter for service port prefix. Let me know if this is sufficient and also we accept contributions if you have suggestions to improve it. :)

**Comment by murarisumit** [comment]
@nrjpoddar istio-vet is fine tool, does what I need it for. 

I was just thinking should this functionality be baked into `istioctl` with `--validate/--configtest` flag  or we use third-party tool for that.

**Comment by rshriram** [comment]
you could import istio-vet and  use it in istioctl.. soemthing like istioctl --vet blah.. That would be great..

**Comment by linsun** [comment]
we already have istioctl validate... anything else we need in this space?

```
$ istioctl validate -f bookinfo-gateway.yaml
Error: 1 error occurred:

* error validating resource (networking.istio.io/v1alpha3, Kind=Gateway Name=bookinfo-gateway Namespace=): port name must be set: number:80 protocol:"HTTP"
```

**Comment by linsun** [comment]
@irisdingbj can you check if this validate cmd can be improved to some of the other checks @rshriram mentioned to improve user's debugging experience?

cc @esnible

**Comment by esnible** [comment]
@irisdingbj I have given a lot of thought to this issue.  If you would like to collaborate on a design before coding begins let me know.

**Comment by irisdingbj** [comment]
@esnible sure, will catch you on slack.

**Comment by Stono** [comment]
https://github.com/instrumenta/kubeval/issues/80 ?

**Comment by irisdingbj** [comment]
submit a pr to address some checks of istio pre-req: https://github.com/istio/istio/pull/14390

according to https://istio.io/docs/setup/kubernetes/prepare/requirements/

**Comment by linsun** [comment]
should this be closed now @irisdingbj?

**Comment by esnible** [comment]
https://github.com/istio/istio/issues/15526 does most of the things requested here.  I will add support for the other things.
