### ISSUE TITLE
Investigate why bookinfo + istio supports low qps

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#690]
In the rate limit e2e tests we have seen often that on a low cpu cluster, we can only drive 2 qps traffic.

We uses to run the test with 30+ qps before.

https://github.com/istio/istio/pull/676
temporarily lowers the rate limit in tests.

**Comment by ldemailly** [comment]
in the simplified env there is no regression, on the contrary there is significant improvements compared to 0.1

**Comment by linsun** [comment]
what remains for this?  Sounds like you are saying performance is better than 0.1.  curious to see any comparison table/chart you have.

**Comment by ldemailly** [comment]
there is a ton of work there - I have some tooling  (fortio) and some setup (the one described in istio/istio/devel/README.md#local) and I've had ongoing PR to keep that setup working, I'll rerun the tests once we have the next build (but again it's only very basic and we need more people looking at that,  it's going to be one of the top focus area for 0.3)

**Comment by ldemailly** [comment]
With only 4 simultaneous connection and on a shared cluster I can get:

W0927 01:51:59.298] All done 5123 calls (plus 4 warmup) 7.812 ms avg, 511.8 qps

so I'm closing this for 0.2
