### ISSUE TITLE
Consistent hash load balancing

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#6937]
It is common to have upstreams hold sizable caches for pre-computed results. In such cases, a consistent load balancing strategy is desired. For example, many ingress proxies use `source.ip` as part of hashing strategy.

Envoy supports maglev-style load balancing using headers, cookies, source IP, or combination thereof (https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-hashpolicy). Istio should expose this feature for gateways, to allow drop-in replacement of existing proxies.

**Comment by rshriram** [comment]
we already have this.

**Comment by rshriram** [comment]
https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#LoadBalancerSettings-ConsistentHashLB

**Comment by kyessenov** [comment]
We need both cookie and source IP based hash. Why is it not a repeated field?

**Comment by rshriram** [comment]
envoy allows only one

**Comment by kyessenov** [comment]
I see repeated in the API definition: https://github.com/envoyproxy/data-plane-api/blob/384e449430bb5cbf48d21df966a93b94d0b51990/envoy/api/v2/route/route.proto#L594
