### ISSUE TITLE
"Distributed Tracing" either broken or out of date.

### ISSUE THREAD

**Issue by Tahler** [istio/istio#6950]
**Describe the bug**
Followed instructions for [Distributed Tracing](https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/) and found the screenshots did not match my outcome.

Expected (from the documentation):

![image](https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/istio-tracing-list.png)

![image](https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/istio-tracing-details.png)

Actual (from my Jaeger UI):

![image](https://user-images.githubusercontent.com/10715719/42481046-3d4b2c02-8395-11e8-812f-6925ee5ea8ef.png)

![image](https://user-images.githubusercontent.com/10715719/42481212-0bffaa96-8396-11e8-93bf-0bf89d91876a.png)

"productpage" is not selectable as a service, though it is viewable through ingressgateway. Diving into the details is much more lean than the large tracing viewable in the second expected screenshot.

The screenshot from the documentation leads me to believe that I've done something wrong. Either this is actually correct behavior and the documentation is out of date or the tracing is not working properly.

**Steps to reproduce the bug**
1. Download latest release (https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180709-09-15/)
1. Helm install with defaults + tracing.enabled=true:
   `helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true`
1. [Deploy Bookinfo](https://preliminary.istio.io/docs/examples/bookinfo/)
1. Follow instructions on https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/

**Version**
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
Version: release-1.0-20180709-09-15
GitRevision: 7c964ecb39cf25f72e78ff5c1eb7c9becd394dd1
User: root@182fd09cc844
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Environment**
GKE

**Comment by objectiser** [comment]
You would get this behaviour if you didn't inject the proxies into the bookinfo services. If you try with the manual sidecar injection it should work fine.
