### ISSUE TITLE
pilot discovery cpu usage is too high 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#6962]
**Describe the bug**

pilot-discovery cpu uasage is about 20% running bookinfo sample.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
 32607 root      20   0   96340  83696  26556 S  19.3  0.5 311:59.26 pilot-discovery                                                           

```

**Expected behavior**

not too much cpu

**Steps to reproduce the bug**

run sample bookinfo

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

`Version: 1.0.0-snapshot.0`

```
root@szvp000201060:/home/paas# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1799+fd222e64412e4c-dirty", GitCommit:"fd222e64412e4c402759b49f1f130e1727ef7a77", GitTreeState:"dirty", BuildDate:"2018-07-09T06:05:40Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1799+fd222e64412e4c-dirty", GitCommit:"fd222e64412e4c402759b49f1f130e1727ef7a77", GitTreeState:"dirty", BuildDate:"2018-07-09T06:05:40Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

```
**Is Istio Auth enabled or not?**

no

**Environment**

linux

**Comment by hzxuzhonghu** [comment]
NO, it is always so since I noticed.

**Comment by hzxuzhonghu** [comment]
go-torch created a flame graph
https://gist.githubusercontent.com/hzxuzhonghu/43afa1ef7f93e2b88453e6ab635277aa/raw/dcae6909df49c8391779770175dff7a1d445b4d2/torch.svg

**Comment by hzxuzhonghu** [comment]
It still exist in 1.0 branch 
```

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                        
105035 root      20   0   69808  58400  26196 S  17.1  0.4 221:15.49 /usr/local/bin/pilot-discovery discovery
```

**Comment by nmittler** [comment]
@costinm any update on the fix that you mentioned in https://github.com/istio/istio/issues/7595#issuecomment-410417910?

**Comment by ibuildthecloud** [comment]
Did a bit of digging around and I think the idle CPU usage is due to https://github.com/istio/istio/blob/adb21944b0a79fabe9c67eba55549b6308b7f1d1/pilot/pkg/serviceregistry/kube/queue.go#L108.  The queue appears to run at the ratelimit all the time.  So something like 10 times a second it wakes up and does nothing.  I changed the implementation of queue.go to use a channel and my CPU usage went to 0.3% from a consistent 12% on my system.

I'm not sure why the queue is implemented with a slice and sleeping as opposed to a channel, but the channel approach seems to work better at doing nothing :)

**Comment by andraxylia** [comment]
@ibuildthecloud this is great find, ship it!

**Comment by hzxuzhonghu** [comment]
Maybe we should make use of sync.Cond to notify instead of checking `if len(q.queue) == 0 {` every time.

I can test this today.

**Comment by costinm** [comment]
Yes, that's been a problem for a long time. We planned to get rid of it as
we refactor the serviceregustry to event based ( there will be no queue),
and for config galley would take over k8s integration, so lower priority.

**Comment by hzxuzhonghu** [comment]
@all I opened a pr #8123 to fix this. 

reduce pilot cpu usage from about 20% down to below 1%

**Comment by hzxuzhonghu** [comment]
>We planned to get rid of it as
we refactor the serviceregustry to event based ( there will be no queue),
and for config galley would take over k8s integration, so lower priority.

@costinm  I have interest in this.

**Comment by andraxylia** [comment]
I see #8123 is only in master, it will be in 1.1 in November time-frame.

**Comment by jaygorrell** [comment]
Ahh thanks - I see now, it's in 1.1.0 snapshot 1 but not snapshot 0.

**Comment by dreadbird** [comment]
yes!
I have rise to 1.0.2 and the cpu is still high.

![image](https://user-images.githubusercontent.com/2113395/47847631-c9b43280-de06-11e8-9e45-025d7a4326c5.png)

**Comment by Justin2997** [comment]
@mnuttall Having the same problem that was not fixed in the past version?
