### ISSUE TITLE
bookinfo demo

### ISSUE THREAD

**Issue by YealZoy** [istio/istio#6963]
I can't get the file from the google,Could you do not use the href  https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js when you make the bookinfo image

give you :poultry_leg:

**Comment by ymesika** [comment]
Thanks for the 🍗
We haven't updated the Bookinfo demo images since Istio v0.5.0 or so. Do you say that you don't have access to the Google server for fetching the jQuery file? Are you trying it run the demo offline?

**Comment by YealZoy** [comment]
yes, I can't have access to the Google server for fetching some files.I run the demo online
![image](https://user-images.githubusercontent.com/10301073/42545658-d35c0818-84eb-11e8-99f8-2ff76e548041.png)

**Comment by smawson** [comment]
I assume this was fixed? Can you close this if it works in the later versions?

**Comment by smawson** [comment]
Actually just reopen if this is still an issue.
