### ISSUE TITLE
Doc issue / grafana addon missing?

### ISSUE THREAD

**Issue by krancour** [istio/istio#6972]
In [Viewing the Istio Dashboard](https://istio.io/docs/tasks/telemetry/using-istio-dashboard/#viewing-the-istio-dashboard), the very first step fails:

```
$ kubectl apply -f install/kubernetes/addons/grafana.yaml
error: the path "install/kubernetes/addons/grafana.yaml" does not exist
```

**Comment by ymesika** [comment]
With which version/release?

**Comment by krancour** [comment]
I've looked at both v0.8.0 and the head of master.

**Comment by ymesika** [comment]
The `release 0.8.0` has this file within the downloaded package/zip/tar.
If you work with branches then this file isn't committed. It's generated when releasing or when you run `install/updateVersion.sh`.

**Comment by ymesika** [comment]
Sorry, my bad. We don't deliver it anymore. It's now available as a Helm chart and can be installed by enabling the `grafana.enabled` flag.
It's a doc issue so I will move this one to there.

**Comment by ymesika** [comment]
Issue moved to [istio/istio.github.io #1739](https://github.com/istio/istio.github.io/issues/1739) via [**ZenHub**](https://www.zenhub.com/)

**Comment by krancour** [comment]
Thanks!
