### ISSUE TITLE
test-infra bug: wrong logs (directory sent instead of file?)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#698]
many of the .log file, for instance mixer.log are 30 bytes of binary instead of the actual log
^_<8B>^H^Hl۱Y^B<FF>tmpMNPhtG^@^C^@^@^@^@^@^@^@^@^@

http://gcsweb.k8s.io/gcs/istio-prow/pull/istio_istio/696/e2e-suite-rbac-auth/340/artifacts/mixer-test-420eb6ab95c34042ae90d8ffcf/

**Comment by ldemailly** [comment]
ok so we discussed offline, there are 2 issues:

a) somewhat cosmetic but still confusing: when there are no logs we get that 30 bytes of garbage. let's have either: no file, a 0 byte file, or a file containing whichever error occurred that explained why we got no logs

b) mixer.log is 'empty' for rbac auth test somehow

**Comment by hklai** [comment]
I think this has been fixed. I don't see those 30 bytes binary files anymore.

E.g. http://gcsweb.k8s.io/gcs/istio-prow/pull/istio-releases_daily-release/449/daily-e2e-rbac-auth/376/artifacts/mixer-test-da3da98c5a014155917a4ae9dd/

**Comment by ldemailly** [comment]
was trying to check one of the daily:

https://prow.istio.io/?job=daily-e2e-rbac-auth

when I click on the log icon
-> https://prow.istio.io/log?job=daily-e2e-rbac-auth&id=377
Log not found: response has status "404 Not Found" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"befad880-22b3-11e8-acb2-0a580a2c295a\" not found","reason":"NotFound","details":{"name":"befad880-22b3-11e8-acb2-0a580a2c295a","kind":"pods"},"code":404}
"


but it still happens:

http://gcsweb.k8s.io/gcs/istio-prow/pull/istio_istio/4091/e2e-bookInfoTests/816/artifacts/demo-test-31eda9e7dcd04f0bbfd0a433cb6/

https://storage.googleapis.com/istio-prow/pull/istio_istio/4091/e2e-bookInfoTests/816/artifacts/demo-test-31eda9e7dcd04f0bbfd0a433cb6/productpage-v1-56585865f4-z2d5s_container:productpage.log

31 bytes 
```
0000000   us  8b  bs  bs   |   ?   ?   Z stx   ?   t   m   p   j   L   6
0000020    L   n   g nul   ? stx nul  93 ack   ?   2 soh nul nul nul    
0000037
```

on the other hand maybe we don't care

**Comment by ldemailly** [comment]
actually it's plausible that product page log is just a new line (once gunziped)

closing this as it's not important. but maybe checking the current prow UI for the error when clicking on the left side log like icon can be a new separate task
