### ISSUE TITLE
flaky test TestIngressGateway503DuringRuleChange 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#6982]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6679/istio-pilot-e2e-envoyv2-v1alpha3/3949
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6946/istio-pilot-e2e-envoyv2-v1alpha3/3953
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6967/istio-pilot-e2e-envoyv2-v1alpha3/3946

**Comment by rshriram** [comment]
fixed
