### ISSUE TITLE
deprecate sidecar certs watcher in pilot-agent after switch to SDS   

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#6986]
1. current we use secret-mount files for sidecars, pilot-agent [monitor those certs file change](https://github.com/istio/istio/blob/e99cad5fc0f4dc5cdda6680c0330c5516d218f3c/pilot/cmd/pilot-agent/main.go#L241) and restart proxy when detect change. This needs to be deprecated after switching to [SDS](https://github.com/envoyproxy/envoy/blob/master/api/envoy/service/discovery/v2/sds.proto)   

2. the cert watch in pilot-agent still needs to be kept for ingress certs, which isn't generated by Istio but brought by customer.

**Comment by wattli** [comment]
Let's hold on this for now. And we can chat offline.

**Comment by rokii** [comment]
hot discussion here https://github.com/istio/istio/issues/2120
