### ISSUE TITLE
istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml -n sohnny Error: Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Sohnny0** [istio/istio#7038]
istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml -n sohnny
Error: Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority

**Comment by quanjielin** [comment]
same issue mentioned https://github.com/istio/istio/issues/4938, which @ayj has a fix.
resolve this as dup for now.

**Comment by kahramanakyil** [comment]
Still getting this error when installed istio on local on-premise kubernetes cluster on Ubuntu 16.04.6.
Error from server (InternalError): error when creating "microservices.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority

istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (2 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial


kubectl -n istio-system get pod istio-galley-5c869899f9-6jtd6 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2020-02-03T15:54:54Z"
  generateName: istio-galley-5c869899f9-
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    istio: galley
    pod-template-hash: 5c869899f9
    release: istio
  name: istio-galley-5c869899f9-6jtd6
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-galley-5c869899f9
    uid: e1a4c6f8-3152-4180-9696-1fd734aa47a6
  resourceVersion: "5035998"
  selfLink: /api/v1/namespaces/istio-system/pods/istio-galley-5c869899f9-6jtd6
  uid: 1c124a9a-ed4c-4fd2-a2fb-cd2d43ae6732
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - command:
    - /usr/local/bin/galley
    - server
    - --meshConfigFile=/etc/mesh-config/mesh
    - --livenessProbeInterval=1s
    - --livenessProbePath=/healthliveness
    - --readinessProbePath=/healthready
    - --readinessProbeInterval=1s
    - --deployment-namespace=istio-system
    - --insecure=true
    - --enable-reconcileWebhookConfiguration=true
    - --validation-webhook-config-file
    - /etc/config/validatingwebhookconfiguration.yaml
    - --monitoringPort=15014
    - --log_output_level=default:info
    image: docker.io/istio/galley:1.4.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthliveness
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: galley
    ports:
    - containerPort: 443
      protocol: TCP
    - containerPort: 15014
      protocol: TCP
    - containerPort: 9901
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthready
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
      readOnly: true
    - mountPath: /etc/config
      name: config
      readOnly: true
    - mountPath: /etc/mesh-config
      name: mesh-config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-galley-service-account-token-k8trn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-galley-service-account
  serviceAccountName: istio-galley-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: istio.istio-galley-service-account
  - configMap:
      defaultMode: 420
      name: istio-galley-configuration
    name: config
  - configMap:
      defaultMode: 420
      name: istio
    name: mesh-config
  - name: istio-galley-service-account-token-k8trn
    secret:
      defaultMode: 420
      secretName: istio-galley-service-account-token-k8trn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:54:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:55:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:55:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:54:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0773b2a1fcf6062ef37e8ab4e1c2ad6ff7e7c29008fdc12e30882eaa91a0217f
    image: istio/galley:1.4.3
    imageID: docker-pullable://istio/galley@sha256:cd808046179ead05a46327b1d7e33c42e5427808d394459cf49b33903b5dce74
    lastState: {}
    name: galley
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-02-03T15:55:16Z"
  hostIP: 100.126.251.154
  phase: Running
  podIP: 10.244.1.131
  podIPs:
  - ip: 10.244.1.131
  qosClass: Burstable
  startTime: "2020-02-03T15:54:59Z"
  
  
kubectl get clusterrole istio-galley-istio-system -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"galley","chart":"galley","heritage":"Tiller","release":"istio"},"name":"istio-galley-istio-system"},"rules":[{"apiGroups":["authentication.istio.io","config.istio.io","networking.istio.io","rbac.istio.io","security.istio.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["authentication.istio.io","config.istio.io","networking.istio.io","rbac.istio.io","security.istio.io"],"resources":["*/status"],"verbs":["update"]},{"apiGroups":["admissionregistration.k8s.io"],"resources":["validatingwebhookconfigurations"],"verbs":["*"]},{"apiGroups":["extensions","apps"],"resourceNames":["istio-galley"],"resources":["deployments"],"verbs":["get"]},{"apiGroups":[""],"resources":["pods","nodes","services","endpoints","namespaces"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resourceNames":["istio-galley"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2020-02-03T15:54:51Z"
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    release: istio
  name: istio-galley-istio-system
  resourceVersion: "5035442"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/istio-galley-istio-system
  uid: 636ab440-045d-48b1-9f7d-a8020e28fcd9
rules:
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*/status'
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resourceNames:
  - istio-galley
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resourceNames:
  - istio-galley
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch

kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"sidecarInjectorWebhook","chart":"sidecarInjectorWebhook","heritage":"Tiller","release":"istio"},"name":"istio-sidecar-injector"},"webhooks":[{"clientConfig":{"caBundle":"","service":{"name":"istio-sidecar-injector","namespace":"istio-system","path":"/inject"}},"failurePolicy":"Fail","name":"sidecar-injector.istio.io","namespaceSelector":{"matchLabels":{"istio-injection":"enabled"}},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]}]}
  creationTimestamp: "2020-02-03T15:54:55Z"
  generation: 2
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: istio
  name: istio-sidecar-injector
  resourceVersion: "5035845"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/istio-sidecar-injector
  uid: 88b4abba-5655-4188-b464-a604cf7e0f63
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNhZ0F3SUJBZ0lSQUxaTExjM1dvSzVLZUJ2SVVtbmhYYzB3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1EQXlNRE14TlRVMU1ETmFGdzB6TURBeApNekV4TlRVMU1ETmFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFh3dDRPNW5FS21Td2w0c0hDeVN4UE04bTR5ZHF2K20yOUFQRHQKVVRTc1Yyd3lUYWprMGRKV2w3TFhBQ29EenVRdXFXajQ4N0x3V1NBcEh4aFB5VjdyZzRrS2J2Uk9lN1ZZcHdDRAo0dG5FS3VaWWNTcVpmTnhDSFEvemp4U0FxYTdmQ0NlOWNRNVZ0dG93azZudldYaU05OElHV3d5Nnl3S252WXZHCmtkbGpyMVdIQll0L1BoOXo2cGVzVFVLYm9pZU1qaHFEaEFiNFhOL3lqekJPRDBDcFBzWEsxRHU1L3I1cHlYZnYKOEZ2UXlCRVNjTVB2YllTWmU3V2F0ampZTGE3dEV1b0FsUjEwcGI2RVQ3UEwrUHpmcjBEVlZTQVljcWN0djJlNwp1dzZhZzhoaGM4Mlo0SlJEOU5ySGlUZ0EwRVNhWjB1Q0U1TVFYVmJCWm8xMUdLUkJBZ01CQUFHakl6QWhNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFBL1Z0Qzk5REZ4WjQzbHhEUEE5Z3hxaWx0OXJ0Sm5VNjRIOG41ZDFOVWlZQzB5N0liSXg3UXh3VDhPK0Z2MgpORVVyOE1vbUhEOGNYS0ZHMSt6Q044WmhEc0xSZ3FxR3J2SCtLQjNqVFlYalQxUFI0cVo4YXBLcGlZdmw3UjlCCmM3bEsvZjZCWUpMVjZ5ZDN5YjVZTnhjKzhoZnVyVnpCRlFzQVNnZFRTYVBUR0NqM0J6Z3RLSWZQL3NkRmJaWncKekVuc1dhWmZnRnovazRrcmJENDlyQlVrRStJbXBxNm9XRVNmbVpTbEcwUFV5VE9jN1MxaEhPSExPMGZBRVdUaAp6dnN5NGEwQVgrUGFMVXZEblZkTVRRUFBoUVE3ZzZUVzhYMXhuSUVBNmVIWmx5K2x2TnhrWi9RUlEySklBVndXCnlvcVpaWHdUM2J3R2NzZUJ6YzlxOXp2bgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-sidecar-injector
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
