### ISSUE TITLE
Can't access bookinfo productpage after changing service to NodePort

### ISSUE THREAD

**Issue by john-a-joyce** [istio/istio#704]
There seems to be an issue if the istio-ingress service definition is changed while applications that are already part of the service mesh are installed.  
1. Installed istio, all the addons and the bookinfo application
1. Edited the istio-ingress service using kubectl edit svc istio-ingress
1. Changed "spec: type:" to "NodePort" 
1. Got 503 errors when trying to get the productpage URL via the nodes IP address and the Istio-ingress service port (the productpage was available directly form the productpage container)

If I delete the bookinfo application and reinstall the application then the productpage can be retrieved.   Note the istio-ingress service is not changed between the delete and reinstall 

I installed istio following the directions here: https://github.com/kubernetes/charts/tree/master/incubator/istio#installing-the-chart

This kubernetes installation is on a single physical node (e.g AIO).  

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1

apiserver version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1

Side Note:   In this setup the grafana and servicegraph are not displaying any data.   I will enter a separate issue for that after I have debugged it a bit further.

**Comment by ldemailly** [comment]
not sure we support this, but can you try again with 0.2.6 and if you still have issues
open a new issue in https://github.com/istio/issues/issues ?
