### ISSUE TITLE
The "jason" example is quite misleading

### ISSUE THREAD

**Issue by krancour** [istio/istio#7047]
[This example](https://istio.io/docs/tasks/traffic-management/request-routing/) shows routing decisions made on the basis of what user is logged in. Most users accessing the bookinfo app see reviews from reviews:v1, while authenticated user "jason" sees reviews from reviews:v2.

I know what is _really_ being demonstrated here is the ability to route traffic based on headers. Cookies, like the `user` cookie, after all, are sent from client to server in an HTTP request header.

_However_, most readers probably walk away from this example with a different takeaway-- "Istio lets me route different users to different endpoints." This is obviously a valuable idea. Imagine that during a blue/green deployment, for instance, you might want your product owner to get into the new version first to do some UAT before you start using weights to shift traffic from everyone else over.

The problem is that this notion of "Istio lets me route different users to different endpoints" doesn't hold up in the real world.

The bookinfo app is a toy. The current user's username is stored in plain text in a cookie that can be edited, allowing an attacker to assume the identity of another user. Apps in the real world do not work this way. Any cookie that plays a role in user identity / session is either going to be encrypted or might even be an opaque token that is correlated to identity or session on the server side. Obviously, this is to prevent identity / session hijacking.

My point is only that the "jason" example sets readers up with a false notion that Istio can be used in this desirable way in the real world, when really, it cannot. Is there, perhaps, a less misleading demonstration of routing requests based on a header that could replace this example?

**Comment by rshriram** [comment]
YEs, we are very well aware of that. The thing is, asking users to install chrome extensions that will allow them to add more headers to a request is super clunky. The plaintext cookie was a convenient exit out of this issue. That said, we should certainly clarify in our docs that this will not hold up in the real world for cookie based routing as cookies are often encrypted/opaque to istio.

If you are interested, I welcome you to submit a Pr to istio.github.io in the bookinfo task related to content based routing.

**Comment by krancour** [comment]
>  The thing is, asking users to install chrome extensions that will allow them to add more headers to a request is super clunky.

Totally understandable. My impulse is to say it's less clunky using curl. Of course the problem then becomes that raw HTML is a terrible way to view a web page.

Would it make any kind of sense for the examples to be reworked to not involve a UI?

**Comment by ymesika** [comment]
People staring at you demoing Istio usually prefer to see something visual then Curl and terminal.
Visual also make it easy to capture the change rather than "Can you please enlarge the font? I can't see your command/output"? ;-)

**Comment by krancour** [comment]
@ymesika @rshriram I totally agree that a demo hits harder when the audience doesn't have to carefully scrutinize the outcome, so the impact from something visual is greater. I'm convinced.

> If you are interested, I welcome you to submit a Pr to istio.github.io in the bookinfo task related to content based routing.

I'm very willing to PR that, but still worry "in real life... encrypted cookies... yada, yada, yada" will be overlooked in the "fine print--" meaning many readers still walk away with a false impression that routing based on user identity is something you can do.

I keep coming back to this:

> The thing is, asking users to install chrome extensions that will allow them to add more headers to a request is super clunky.

I keep wondering if there's some header other than `Cookie` whose value "naturally" varies based on something a user can do (easily). The thing I keep coming back to is `User-Agent`...

Obviously, I think some more thought needs to go into this, but what would your initial reactions be if I proposed that the example could route traffic from a given browser-- Firefox, perhaps-- to reviews:v2 while all other browsers continue to be routed to reviews:v1?

__The plot thickens...__

While researching options for improving this demo, I guess I really went down the rabbit hole. I started to wonder how the cookie that the user's browser sends with the HTTP request to the product page is visible as a header in the HTTP request that the product page makes to the rating service...

When I started tugging on that thread, I found that the product page _forwards_ that cookie in its request to the rating service. (Even if we hypothetically based routing on the `User-Agent` header instead of the `Cookie` header, we'd still have to forward that header.)

If using a plain text user cookie was the first thing this demo does that a real application would never do, forwarding that cookie to a downstream service is a second. I don't intend this in any malicious way, but I frankly feel _deceived_ by this demo. For the sake of packing a bigger punch, it compromises on security in ways that would be entirely unacceptable in the real world. Assuming that users won't want to compromise on security, they could never actually _use_ Istio as it is demonstrated here. This feels tantamount to false advertising.

Make no mistake, _I think Istio is awesome._ With as many great features as it has, I believe that with some thought and effort (which I am happy to contribute to) a more honest demonstration of its capabilities is possible and can be just as impactful.

**Comment by krancour** [comment]
Here are two small changes that could possibly fix this whole thing:

1. Ignoring for a moment that it's plain text, the audience should reasonably expect that the user cookie is a secret between the end user's browser and the product info app. What if instead of forwarding that entire cookie downstream to the reviews service, the product info page were to set a _custom header_ on the outbound request that identifies the end user? This seems like a more realistic scenario that one would encounter in the real world.

2. After no. 1 is fixed, the cookie (which would now be relevant only to the request from browser to product info app) no longer needs to be plain text. It could be encrypted just as it would be in any real web application.

**Comment by krancour** [comment]
This was closed by #7109
