### ISSUE TITLE
1.0 Quick Start with Google Kubernetes Engine:  Istio GKE Deployment Manager fails

### ISSUE THREAD

**Issue by duderino** [istio/istio#7049]
**Describe the bug**

The 1.0 GKE Quick Start works up to this point:  https://preliminary.istio.io/docs/setup/kubernetes/quick-start-gke-dm/#launch-deployment-manager

When I try to open the 'Istio GKE Deployment Manager' I get a blank page

**Expected behavior**

Something useful should be generated

**Steps to reproduce the bug**

Start from the top of https://preliminary.istio.io/docs/setup/kubernetes/quick-start-gke-dm and work your way down to opening the 'Istio GKE Deployment Manager'

**Version**

```
$ istioctl version
Version: master-20180709-09-15
GitRevision: 7bba996125b321cbe694e057e1e8f0dfc4386593
User: root@1be68a119004
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.0", GitCommit:"f4c74e18e57148052c59cc0467bb7e99dcc46399", GitTreeState:"clean", BuildDate:"2018-06-21T14:11:26Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**

No

**Environment**

GKE

**Comment by andraxylia** [comment]
We need to update this file once the 1.0 release is created

https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja#L107

**Comment by andraxylia** [comment]
cc @salrashid123

**Comment by rcleveng** [comment]
For me the deployment manager starts, but fails with this error. I think because the debian8 images are not longer available, so the DM template needs to be updated AFAICT.

```
"ResourceType":"compute.v1.instance","ResourceErrorCode":"404","ResourceErrorMessage":{"code":404,"errors":[{"domain":"global","message":"The resource 'projects/debian-cloud/global/images/family/debian-8' was not found","reason":"notFound"}],"message":"The resource 'projects/debian-cloud/global/images/family/debian-8' was not found","statusMessage":"Not Found","requestPath":"https://www.googleapis.com/compute/v1/projects/REDACTED/zones/us-central1-a/instances","httpMethod":"POST"}}
```

**Comment by costinm** [comment]
Reopen for tracking 1.0 merge.
