### ISSUE TITLE
Getting 403 on upgrade connection in the sample Websockets app

### ISSUE THREAD

**Issue by sekka1** [istio/istio#7058]
**Describe the bug**
Using Istio 0.8.0 and trying out the websocket example:  https://github.com/istio/istio/tree/master/samples/websockets

I am getting a 403 on the websocket upgrade.

![screenshot from 2018-07-12 11-38-52](https://user-images.githubusercontent.com/575972/42652745-3272634c-85c8-11e8-9b02-3c752e741913.png)

Maybe im missing some addition steps I need to take to setup Istio to allow websockets?

**Expected behavior**
Expected the page to show with a "WebSocket status: Open" in green and also expected the `ws` connection to not return a 403.

**Steps to reproduce the bug**
1. Install Istio 0.8.0 per default instructions
2. Launch this websocket sample into a namespace

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
```
istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
helm

```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml


kubectl create namespace istio-system
kubectl create -f $HOME/istio.yaml
```

**Environment**
On AWS and the kube cluster was created with kops

**Comment by ymesika** [comment]
Istio 0.8.0 don't have the websockets support.
It got enabled only after the release. Try with 1.0 snapshot and re-open if you still see the issue.
Thanks.
