### ISSUE TITLE
internal Istio mesh communication is limited to 100 HTTP/2 streams

### ISSUE THREAD

**Issue by prune998** [istio/istio#7061]
**Describe the bug**
when 2 application inside the mesh talk to each other (using the istio sidecar), the number of HTTP/2 streams are limited to 100.

**Expected behavior**
The number of streams should be limited by the client or server capability and not limited by the `proxy` (Istio Sidecar)

**Steps to reproduce the bug**
Deploy a client/server pod from https://github.com/prune998/goHelloGrpcStream with Istio Sidecar Injection.
Use the `lloadtest_client` like : 
```
./loadtest_client -debug -server greeter-server:7788 -clients=300 -cnxDelay=30000s
```

The server only receive 100 * <number of CPU> connexions (as Envoy support only one TCP connexion per CPU per upstream)

** More Info **
This issue is not technically in Istio, but is linked to Envoy and ngHttp library.
While Envoy allow to override the 100 streams default value, there is no clear way to tell Envoy to do so from Istio configuration. 

**Version**
### Istio
Istio Sidecar and Pilot are using image version `proxyv2:1.0.0-snapshot.0` and is using the v2 API.
```
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean
```

### Kubectl
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.0", GitCommit:"f4c74e18e57148052c59cc0467bb7e99dcc46399", GitTreeState:"clean", BuildDate:"2018-06-21T14:11:26Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
NO

**Environment**
Google GKE v1.10.5

**Comment by mandarjog** [comment]
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L488 
fixes this issue. 
Are you positive that your experiment is testing H2 streams and not TCP connections themselves ?

**Comment by prune998** [comment]
@mandarjog thanks for your answer.

- Yes, I'm using HTTP/2 gRPC streams
- I haven't created any Istio specific config 
- port name in the Service and in the Deployment is defined as : 
```
    "ports": [
      {
        "name": "grpc-greeter",
        "protocol": "TCP",
        "port": 7788,
        "targetPort": 7788
      }
```

The `routeconfig` on the client is like : 
```
{
"versionInfo": "2018-07-12 11:33:39.35752902 +0000 UTC m=+84474.223289186",
"routeConfig": {
"name": "7788",
"virtualHosts": [
{
"name": "greeter-server.default.svc.cluster.local:7788",
"domains": [
"greeter-server.default.svc.cluster.local",
"greeter-server.default.svc.cluster.local:7788",
"greeter-server",
"greeter-server:7788",
"greeter-server.default.svc.cluster",
"greeter-server.default.svc.cluster:7788",
"greeter-server.default.svc",
"greeter-server.default.svc:7788",
"greeter-server.default",
"greeter-server.default:7788",
"10.63.249.113",
"10.63.249.113:7788"
],
"routes": [
{
"match": {
"prefix": "/"
},
"route": {
"cluster": "outbound|7788||greeter-server.default.svc.cluster.local",
"timeout": "0s"
},
"decorator": {
"operation": "greeter-server.default.svc.cluster.local:7788/*"
},
"perFilterConfig": {
"mixer": {
"forward_attributes": {
"attributes": {
"destination.service": {
"string_value": "greeter-server.default.svc.cluster.local"
},
"destination.service.host": {
"string_value": "greeter-server.default.svc.cluster.local"
}
}
},
"mixer_attributes": {
"attributes": {
"destination.service": {
"string_value": "greeter-server.default.svc.cluster.local"
},
"destination.service.host": {
"string_value": "greeter-server.default.svc.cluster.local"
}
}
},
"disable_check_calls": true
}
}
}
]
}
],
"validateClusters": false
}
},
```

and in the `dynamicActiveClusters` I have : 
```
{
"versionInfo": "2018-07-12 11:33:39.35752902 +0000 UTC m=+84474.223289186",
"cluster": {
"name": "outbound|7788||greeter-server.default.svc.cluster.local",
"type": "EDS",
"edsClusterConfig": {
"edsConfig": {
"ads": {}
},
"serviceName": "outbound|7788||greeter-server.default.svc.cluster.local"
},
"connectTimeout": "2s",
"maxRequestsPerConnection": 800,
"circuitBreakers": {
"thresholds": [
{
"maxConnections": 2048,
"maxRequests": 800
}
]
},
"http2ProtocolOptions": {
"maxConcurrentStreams": 1073741824
}
}
},
```

When the first connexion occures (as seen when making `tcpdump` on the client), I do see the `http2.settings.max_concurrent_streams = 1073741824` header sent. 
But while the Istio sidecar receives 300 streams requests (upstream_rq_active = 300), I see only 100 streams per TCP connexions, so in my case, 200 streams).
Istio Sidecar on the client is "queuing" other streams.

As far as I remember (I may be wrong), the `max_concurrent_streams` header is NOT a negociation. The client say how many streams he can receive, which is not related to how many streams the server can receive.
My understanding here is that, while the client is setting it's number of streams, the server is not, so the client still thinks the limit is the default one in NgHttp2, 100 streams... 
Again, I may be wrong on this, but the behaviour here is that I'm limited to 100 streams per TCP connexion...

**Comment by prune998** [comment]
Just as another clue, I tried with a server without Istio.... 
I do see the client sending the `maxConcurrentStreams: 1073741824`, then the server replying with `maxConcurrentStreams: 50000` as specified (for testing) in my server's code.
In that situation I have no issue going above the 100 streams limit.

**Comment by sdake** [comment]
Can you try with  a more recent revision then snapshot.0?  Look here for the latest test builds:
http://bit.do/istio10-latest-daily

**Comment by lizan** [comment]
Not yet... https://github.com/envoyproxy/envoy/issues/3076

**Comment by PiotrSikora** [comment]
The fix for this was merged already (https://github.com/envoyproxy/envoy/pull/3658 via https://github.com/istio/proxy/pull/1862 via #7232).
