### ISSUE TITLE
mixer: randomness in adapters

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#7099]
I think there is a problem with how caching & randomness play out in proxy/adapter integration. Currently, if the adapter wants to utilize a random coin (e.g. failure injection), then we have two choices:
1. mark `x-request-id` as referenced, which effectively disables any caching in the proxy
2. do not mark `x-request-id` as referenced, which effectively caches the random decision at the proxy,  which in turn means the behavior is not random per request, but per cache expiration duration.

I propose we should generate random bits at the proxy (uniformly, and independently of the request), and send this new `coin` attribute to Mixer. For example, assuming `coin` takes a value in the range `0..1000`, the adaptor now has a third choice:

3. mark `coin` as a referenced attribute, which will apply behavior randomly per request, without sending RPCs for every request.

There are several related ideas that follow up:
- `coin` is useful for debugging / audit of decisions that need randomness
- we should ensure the values are truly random at the proxy
- it would be useful to cache based on ranges of values, e.g. `x < coin <= y`.
- as a workaround, we can generate a pseudo attribute that is a hash of `x-request-id`; we would need to implement this special hash interpretation in the proxy

/cc @mandarjog @douglas-reid @geeknoid

**Comment by mandarjog** [comment]
Suppose we add such a `coin` attribute where some decision is based on `x <= coin <= y`.
It would be much better for the classification to take place on the proxy.  Otherwise a random number 
 [0...1000] will also exhibit poor caching behaviour.

**Comment by douglas-reid** [comment]
Do we have any concrete use cases for randomness in policy enforcement at the Mixer level that exist today?  Are there any Check adapters out in the wild that are referencing `x-request-id` (or similar)?

I agree that there is general utility in having a way to turn "do this for every N/1000 requests". Would like to understand the relative priority however (and how this might overlap with existing networking features).

**Comment by kyessenov** [comment]
@douglas-reid 

This request was not driven by a concrete use-case, but I anticipate an issue when some sort of request sampling is needed in Mixer, given how we cache decisions in the proxy. We don't have that many Check adapters yet, and I am not aware of one that references individual requests (that seems like a bad pattern anyways).

Fault injection is an obvious case where this would be useful. Networking-style fault injection is stateless, while Mixer can apply a more nuanced policy (e.g. inject a fault for a user in a group on a server-side sidecar).

**Comment by kyessenov** [comment]
Not stale.

**Comment by douglas-reid** [comment]
I'm going to close this issue, as it is not on the near term roadmap, and I don't think this will get addressed before any architectural changes.
