### ISSUE TITLE
Provide contextual information to internal adapters

### ISSUE THREAD

**Issue by theganyo** [istio/istio#7100]
It would be useful for some Mixer adapters to know if they are operating in the policy or telemetry mixer instance during initialization. For example, the Apigee adapter starts some background daemons during initialization, but some of these processes are specific to either policy decisions or telemetry.

**Comment by douglas-reid** [comment]
Right now, the only supported mechanism is to read the POD_NAME env var and see if it includes "policy" or "telemetry".

This only works for in-proc adapters, however.

**Comment by mandarjog** [comment]
Adapter code should not rely on information other that what is available in the api.

So during build check adapter, the adapter knows it is check and should do the needful.

Policy and telemetry mixers are deployment options. A customer can choose to run just one mixer and point both services to it.
