### ISSUE TITLE
Mixer high allocation, crashing

### ISSUE THREAD

**Issue by costinm** [istio/istio#7114]
Splitting this from #7050, which only caught the restart issue.

Last restart mixer showed 20G - job started at 8:11, lasted until 8:14 when it crashed. 

I did turn on zipkin in the load cluster - maybe that is what triggered the problems, I can try turning it off.

You can check weekly10 under istio-testing GCP project - and the tests/helm directory if you want to repro.

**Comment by costinm** [comment]
Rolled back mixer to image from 20180710 (which was pretty stable under same load) - didn't help. So maybe some config changed for mixer ? I was hoping to have a stability test running over the weekend, but  doesn't seem possible.

**Comment by douglas-reid** [comment]
@geeknoid @mandarjog @kyessenov any ideas on what could be causing mem leak?

**Comment by douglas-reid** [comment]
Running a quick test before running out the door with 100 qps against a bookinfo test cluster, I see steady mem alloc and near constant num of goroutines.

**Comment by costinm** [comment]
I did a bit more testing - it appears it's not a leak, but just a capacity regression - reducing the QPS seems to solve the problem. I'll add the missing autoscaler config which solved my testing problem.

100qps is far too low to see problems - 5000 qps is where it starts to explode. That's requests in the cluster - with batching it's lower as request to telemetry.

We need to confirm this is the only problem - I'll leave it running to see if it leaks, but if it's just lower capacity it should be fine. 

We had similar problem in pilot - at some point the allocations are larger than what GC can handle, 
and it just explodes. Surprisingly, memory allocs are not free.

**Comment by kyessenov** [comment]
Can you try with two telemetry pods in your setup? We can relieve the pressure on GC and see if that is a sustainable solution to larger load from the cluster.

I don't think there was any major change to mixer in the last week.

**Comment by kyessenov** [comment]
We should also check if any of our dependency upgrade brought some bad leak (historical lesson).

**Comment by douglas-reid** [comment]
@costinm that confirms my suspicion. with HPA, we should be ok. rate limit is the only issue. we need the redisquota stuff to work.

**Comment by douglas-reid** [comment]
created an initial HPA PR for mixer services. will work on refinement. @costinm do you have an understanding of scaling factors from your tests?

**Comment by mandarjog** [comment]
Ideally this should result in mixer getting slower and slower so it applies back pressure on proxies so they send mixer less work.

Perhaps at a certain point gc pauses would have become more frequent, but oom killer stepped in. 

Perhaps GOGC=50 will also solve the problem at some additional cpu cost.
Gc is simply not running frequently enough.

**Comment by costinm** [comment]
I used just CPU, seems enough. I think what changed is the liveness check - can you double check that liveness is retried and is able to deal with 50xs ? While mixer is under stress - it does return a lot of 50x,
I assume liveness as well. It is possible that before it was recovering, now it dies (and since it can't restart...).

I doubt GOGC is the solution - in the end for a specific QPS you allocate x objects and that sets the limit. Either reduce the cost per query, or make sure you have enough replicas. If we know a 4 CPU mixer can handle ~5000qps (with the default config) we need to let users configure based on their traffic, like we do in google. 

Assuming restart problem is fixed - we can move this to 1.1 once we have a HPA and some docs, but please try to run your own load tests next week.

**Comment by kyessenov** [comment]
Renamed the issue given that we have no indicate that this is a memory leak.

**Comment by mandarjog** [comment]
Liveness is using /version endpoint that returns the  version constant string.

I don’t see it returning 5xx.
