### ISSUE TITLE
gRPC load-balancing with Istio

### ISSUE THREAD

**Issue by ayushpateria** [istio/istio#7117]
I'm not able to get gRPC load-balancing working with Istio 0.8.0. I've named the service port of the gRPC service as 'grpc', but still all the requests seem to be going to a single backend. Are there any more steps to be followed?

**Comment by rshriram** [comment]
I think the load balancing would happen beyond a certain load. Envoy tries to keep a persistent connection for all H2 streams.. Alternatively, you could reduce the connection pool size or tweak the metrics (using destinationrules) to see if the load balancing kicks in.
