### ISSUE TITLE
Enable envoy's access log for the TCP proxy

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7132]
**Is your feature request related to a problem? Please describe.**
Currently, only HTTP requests appear in the stdout of the sidecar proxy, no TCP. I would like envoy to emit log entries about TCP connections as well.

**Describe the solution you'd like**
Switch to V2 configuration of  `envoy.tcp_proxy` and set `access_log`, similar to the HTTP filter.

**Comment by vadimeisenbergibm** [comment]
@loewenstein Sorry, I was on vacation. I guess we should stop using the deprecated tcp_proxy at some point, shouldn't we? Then TCP access_log could be set.

**Comment by loewenstein** [comment]
@vadimeisenbergibm is everything ready to replace the deprecated usage? As far as I remember limited support for filter chain matches was a reason to keep using v1 tcp_proxy...

**Comment by vadimeisenbergibm** [comment]
@loewenstein I do not know, sorry. This issue is open to track that switch, I do not claim it must/could be done immediately
