### ISSUE TITLE
[istio-release-1.0-20180713-09-15] Sidecar upgrade failed on invalid: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#7137]
**Describe the bug**
[istio-release-1.0-20180713-09-15] Sidecar upgrade failed on invalid: spec.clusterIP: Invalid value: "": field is immutable

**Expected behavior**
Sidecar upgrade should be succeed without errors
 
**Steps to reproduce the bug**
Steps to reproduce the behavior.
Installation on istio-0.8.0:https: //istio.io/docs/guides/bookinfo/
cd ~/istio-0.8.0
kubectl apply -f install/kubernetes/istio-demo.yaml
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml
bin/istioctl create -f samples/bookinfo/routing/bookinfo-gateway.yaml

upgrade to istio-release-1.0-20180713-09-15
1. control plane upgrade
cd ~/Downloads/istio-release-1.0-20180713-09-15
helm template --namespace istio-system --set global.proxy.image=proxy --values install/kubernetes/helm/istio/values-istio.yaml install/kubernetes/helm/istio >> install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio.yaml

2. Sidecar upgrade 
kubectl replace -f <(bin/istioctl kube-inject -f ~/istio-0.8.0/samples/bookinfo/kube/bookinfo.yaml)
```
deployment "details-v1" replaced
deployment "ratings-v1" replaced
deployment "reviews-v1" replaced
deployment "reviews-v2" replaced
deployment "reviews-v3" replaced
deployment "productpage-v1" replaced
Error from server (Invalid): error when replacing "/dev/fd/63": Service "details" is invalid: spec.clusterIP: Invalid value: "": field is immutable
Error from server (Invalid): error when replacing "/dev/fd/63": Service "ratings" is invalid: spec.clusterIP: Invalid value: "": field is immutable
Error from server (Invalid): error when replacing "/dev/fd/63": Service "reviews" is invalid: spec.clusterIP: Invalid value: "": field is immutable
Error from server (Invalid): error when replacing "/dev/fd/63": Service "productpage" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

**Comment by janevalleye2e** [comment]
@kidiyoor @mandarjog @vilobhmm @costinm @sdake

**Comment by sdake** [comment]
@ayj any thoughts?

**Comment by janevalleye2e** [comment]
tested on daily build:istio-release-1.0-20180719-09-15
1. control plane upgrade
cd ~/Downloads/istio-release-1.0-20180719-09-15
helm template --namespace istio-system --set global.proxy.image=proxy --values install/kubernetes/helm/istio/values-istio.yaml install/kubernetes/helm/istio >> install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio.yaml
2. Sidecar upgrade
kubectl replace -f <(istioctl kube-inject -f ~/istio-0.8.0/samples/bookinfo/kube/bookinfo.yaml)
Error: failed to convert to proto. unknown field "sdsRefreshDelay" in v1alpha1.MeshConfig

**Comment by costinm** [comment]
Can you descibe the environment - how was the cluster created ? 

Can't repro - does it happen with final release ?

**Comment by janevalleye2e** [comment]
1. This issues happens on istio-1.0 GA version
2. Use GCP: gcloud container clusters create

**Comment by ayj** [comment]
Can you try using `apply` instead of `replace`?

```bash
kubectl apply -f <(bin/istioctl kube-inject -f ~/istio-0.8.0/samples/bookinfo/kube/bookinfo.yaml)
```

**Comment by janevalleye2e** [comment]
kubectl apply -f <(bin/istioctl kube-inject -f ~/istio-0.8.0/samples/bookinfo/kube/bookinfo.yaml) ran through without errors; but kubectl replace -f <(bin/istioctl kube-inject -f ~/istio-0.8.0/samples/bookinfo/kube/bookinfo.yaml) faild on Invalid value: "": field is immutable

**Comment by ayj** [comment]
Thanks for checking. @costinm, @sdake @ostromart, we should update docs to use `apply` instead of `replace`.

**Comment by ostromart** [comment]
https://github.com/istio/istio.github.io/pull/2176
