### ISSUE TITLE
BookInfo guide page is missing injection labelling step

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7161]
The apply step for automatic injection in the Bookinfo page is missing details about creation of a namespace (or tagging with istio-injection).

https://preliminary.istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes

If the guide is followed in isolation, it is very easy to miss this and end up with a deployment without injection. 

When not done, user sees 503s when performing the curl operation in the "what's next" step.

Tagging the default namespace with istio-injection works (although probably shouldn't be recommended).

@ayj

**Comment by ayj** [comment]
cc @sdake @ostromart 

Steve, I think you had some thoughts on consolidating references to automatic injection configuration throughout the docs?

**Comment by sdake** [comment]
@ayj i'd like to do so.  @ozevren can you do me a solid and file this bug against the istio docs repo.  We can collect the docs that need changing in that repo rather than here.

Cheers
-steve

**Comment by ozevren** [comment]
Issue moved to [istio/istio.github.io #1859](https://github.com/istio/istio.github.io/issues/1859) via [**ZenHub**](https://www.zenhub.com/)
