### ISSUE TITLE
Unnecessary use of istioctl in BookInfo page

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7163]
https://preliminary.istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes

"Define the ingress gateway for the application" step is using istioctl, whereas all other commands are kubectl. Use of istioctl is not necessary as it does "-f apply".

**Comment by ozevren** [comment]
istioctl is not necessary in the uninstall/kubernetes steps.

**Comment by ymesika** [comment]
Issue moved to [istio/istio.github.io #1843](https://github.com/istio/istio.github.io/issues/1843) via [**ZenHub**](https://www.zenhub.com/)
