### ISSUE TITLE
Missing cleanup step in the telemetry task.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7167]
https://preliminary.istio.io/docs/tasks/telemetry/metrics-logs/

This page starts a port-forwarder for accessing Prometheus, but does not instruct to clean it up in the cleanup stage.

**Comment by ozevren** [comment]
Ditto for https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/

(Correct example: https://preliminary.istio.io/docs/tasks/telemetry/querying-metrics/ )

**Comment by ymesika** [comment]
Issue moved to [istio/istio.github.io #1842](https://github.com/istio/istio.github.io/issues/1842) via [**ZenHub**](https://www.zenhub.com/)
