### ISSUE TITLE
Wrong metric name in "Querying Metrics from Prometheus"

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7169]
https://preliminary.istio.io/docs/tasks/telemetry/querying-metrics/

Instructions ask to enter "istio_request_count", but this doesn't exist. "istio_request_bytes_count" works.

**Comment by ymesika** [comment]
Issue moved to [istio/istio.github.io #1841](https://github.com/istio/istio.github.io/issues/1841) via [**ZenHub**](https://www.zenhub.com/)
