### ISSUE TITLE
Grafana task for 1.0 is broken with multiple issues.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7171]
https://preliminary.istio.io/docs/tasks/telemetry/using-istio-dashboard/

1)
Instructions ask to do:
$ kubectl apply -f install/kubernetes/addons/grafana.yaml
However, addons/ directory is empty.

Grafana is already installed and running.

```
$ kubectl -n istio-system get svc grafana
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
grafana   ClusterIP   10.11.248.75   <none>        3000/TCP   2h
```

2)
Following instructions further, trying to access the dashboard (after port-forward) causes Grafana web UI to come-up but the dashboard is not found.
<img width="1434" alt="screen shot 2018-07-16 at 3 47 30 pm" src="https://user-images.githubusercontent.com/17071139/42787526-b789f406-890f-11e8-8f07-49802cc7f896.png">

**Comment by ymesika** [comment]
As for the doc part, it should be updated because Grafana is now a Helm flag: https://github.com/istio/istio.github.io/issues/1739

**Comment by douglas-reid** [comment]
There is an outstanding PR in the docs repo for this (as well as associated issues). Let's track the work there.

**Comment by ozevren** [comment]
The issue is not docs only. The task didn't work.  I couldn't access the dashboard.

**Comment by douglas-reid** [comment]
it is a docs issue. the task, as properly written, provides access to the dashboard.

**Comment by ozevren** [comment]
ok then. :)

**Comment by douglas-reid** [comment]
ok. docs have been updated. would you mind trying again? :crossed_fingers:

**Comment by douglas-reid** [comment]
Closing for now. Please reopen in problem persists.
