### ISSUE TITLE
MountVolume.SetUp failed for volume "istio-certs" : secrets "istio.istio-pilot-service-account" not found 

### ISSUE THREAD

**Issue by Sohnny0** [istio/istio#7174]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11869240/42790053-56813d22-899b-11e8-9971-986ec38e359e.png)

The other deployments were normal, and only three had problems

**Steps to reproduce the bug**
$ kubectl apply -f install/kubernetes/istio.yaml

**Version**
1.0

**Is Istio Auth enabled or not?**
not

**Environment**
OS

**Comment by quanjielin** [comment]
looks like a dup of https://github.com/istio/istio/issues/6499
btw, where do you get the build from ? it's weird that chart label show 0.8 in above screenshot. (now we test against 1.0 daily release http://bit.do/istio10-latest-daily)

**Comment by Sohnny0** [comment]
@quanjielin   I downloaded it here : https://github.com/istio/istio/releases  
istio-1.0.0-snapshot.0-linux.tar.gz
$ kubectl apply -f install/kubernetes/istio-demo.yaml

**Comment by quanjielin** [comment]
current 1.0 snapshot is cut end of June, @hklai will cut a new snapshot this week; meanwhile could you pls use the daily build for testing ? thanks.

**Comment by Sohnny0** [comment]
@quanjielin ok, thanks.

**Comment by sdake** [comment]
@Sohnny0 for reference, the latest daily is here: http://bit.do/istio10-latest-daily

**Comment by costinm** [comment]
#7338

**Comment by 1282009188** [comment]
Has this bug been fixed in istio-1.0.1?

**Comment by ngupta-cn** [comment]
I am facing the same issue recently in kubectl version 1.11 and istio 1.0.0. But everything was working fine a week ago. Is this issue resolved?

**Comment by codebreach** [comment]
+1 same issue with 1.0.2

**Comment by metal3d** [comment]
Same problem using Ansible deployment:

MountVolume.SetUp failed for volume "certs" : secrets "istio.istio-sidecar-injector-service-account" not found

Version v1.0.2

**Comment by metal3d** [comment]
Hum... after 2 minutes, everything seems to be ok but as Ansible stopped, is it correctly installed ?

![image](https://user-images.githubusercontent.com/100080/45497518-5122e500-b778-11e8-878a-311d5688e8f1.png)

**Comment by isnuryusuf** [comment]
+1 same issue with 1.0.2

**Comment by blerko** [comment]
I hit this issue when trying to run the minimal install as outlined in the docs: https://istio.io/docs/setup/kubernetes/minimal-install/ the missing secret is created by the citadel pod which isn't running due to the the --set security.enabled=false flag, setting that to true starts citadel and the secret is created and then pilot will start.

**Comment by linsun** [comment]
@blerko were you running pilot in sidecar=false mode?

**Comment by stryd3r** [comment]
If you install the minimal just set :
 kubectl label namespace default istio-injection=enabled

and then restart the pod (scale the deployment to 0, then restore it to 1)

**Comment by hustcat** [comment]
Hit the same issue with v1.0.3

**Comment by Lorryrui** [comment]
yum install -y nfs-utils nfs-utils-lib 
then retry.
