### ISSUE TITLE
Envoy requiring root privileges

### ISSUE THREAD

**Issue by texzone** [istio/istio#7184]
I am looking into using envoy alongside some kubernetes containers, but it came to my attention that envoy requires root access, which introduces an attack vector. I want to understand why envoy requires root permissions and if there is any work around.

**Comment by rshriram** [comment]
Envoy does not require root privileges. It runs as user 1337 (non root).

**Comment by texzone** [comment]
@rshriram 


up vote
1
down vote
unaccept

According to the instructions I read, Envoy creates iptables rules with Envoy user UID (like in Istio).

`sudo iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-port 5001`

`sudo iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-port 5001 -m owner '!' --uid-owner ${Envoy_User_UID}`

In order to run this rule, a new user with ${Envoy_User_UID} needs to be created before launching Envoy. Envoy then needs to be run under this user id, so that packets from Envoy don't get redirected to themselves. For the new user to do this, it needs to have root permissions. It is a non-root user, but it needs root permissions to change iptable rules, it being on the kernel and all. Or am I misunderstanding something here?

**Comment by rshriram** [comment]
I don't know where these instructions are from. The init container in Istio does require cap_net_admin privileges to install IPtables rules. Other than that, the sidecar runs as non-root user

**Comment by texzone** [comment]
Okay. Is there a way for me to query from istio the rules it wants to install in the iptable without actually granting it that privilege? I just want to leave as little attack vectors open as possible.

**Comment by Manish10689** [comment]
@rshriram is it possible to inject sidecar to pod running as a non root user? What I understood is init container requires cap_net_admin  to install iptables and it does all these configuration before application pod starts. In my case, the application pod is running as non root user and I need to inject side car to my application pod to get some metrics. If I inject it in application pod I get "error :  container run as non root and image run as a root error".  Is there any way I can achieve this ?

**Comment by dbenque-1a** [comment]
@Manish10689, yes it is possible, I am actually doing it based on the setup inspired from this blog:
https://blog.openshift.com/increasing-security-of-istio-deployments-by-removing-the-need-for-privileged-containers/
The IP table modification is done by a dedicated DaemonSet that has the required privilege. With this your entire pod can run as nonroot.
I am now checking if I can even run using "restricted" scc instead of "nonroot". For this I need to check if istio can run with such scc or really need to run user 1337.

**Comment by Manish10689** [comment]
Thanks @dbenque-1a for the reply. I checked it with "Istio Pod Network Controller" but encountered below error (after executing the command helm template -n istio-pod-network-controller ./chart/istio-pod-network-controller | kubectl apply -f - ):

time="2018-11-13T06:17:18Z" level=info msg="Managing Pods Running on Node: sgscapl003"
E1113 06:17:18.695759   20331 runtime.go:66] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)

Did you face any such issues with controller ?

**Comment by dbenque-1a** [comment]
@Manish10689 , I am not facing that error, my pod controlled by the DaemonSet works correctly:
```
> oc logs istio-pod-network-controller-c55gt | head -20
time="2018-11-12T16:31:31Z" level=info msg="Go Version: go1.9.4"
time="2018-11-12T16:31:31Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-11-12T16:31:31Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-11-12T16:31:31Z" level=info msg="Managing Pods Running on Node: app-node-0.dbenque.nce"
...
```
I am running an Openshift v3.9. What is your environment?

**Comment by Manish10689** [comment]
@dbenque-1a,  i have used kubeadm for kubernetes deployment, below is the version details

 Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
