### ISSUE TITLE
missing grafana/servicegraph yaml files in install/kubernetes/addons/

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#7190]
**Describe the bug**
follow https://preliminary.istio.io/docs/tasks/telemetry/using-istio-dashboard/ and https://preliminary.istio.io/docs/tasks/telemetry/servicegraph/, there should be servicegraph.yaml and grafana.yaml, however those files don't exist in latest 1.0 release daily build https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180717-09-58/

**Comment by quanjielin** [comment]
seems a similar issue as https://github.com/istio/istio/issues/6922, grafana.yaml.tmpl is removed in https://github.com/istio/istio/commit/beceb07af9bb63b83691bf7df10231a7ac6c0e55#diff-17e443480eea200223e3547be4382604

**Comment by ymesika** [comment]
Duplication of #7171
Docs needs an update: https://github.com/istio/istio.github.io/issues/1739
