### ISSUE TITLE
e2e unify the test framework

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#723]
There are currently two variations, one based on bash, one based on go.
Any change needs to go in two places.

1.We need to switch to a single framework, preferably the one in go.

2. Decouple the tests from the istio templates. Tests need to test the istio.yaml file only, or the result of the script that generates the istio.yaml, they should not process templates individually, nor generate anything. Currently any new template needs to have a corresponding change in the e2e.

**Comment by nmittler** [comment]
nope ... closing.
