### ISSUE TITLE
Api, mixerclient, proxy aren't tagged with the versions

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#724]
@ldemailly commented on [Sun Sep 10 2017](https://github.com/istio/api/issues/170)

for 0.2.2 release and onward we should use the 0.2.2 api tag instead of some different shas in different children repos

if we can start by having the complete list of places referencing api that'd be good
I know of pilot/WORKSPACE - what is the complete list ?

ps: same for mixerclient and proxy

**Comment by sebastienvas** [comment]
The way this currently works this would require a new build for each repo which is not pratical. What happen if the tag that we select is different from master? The only way to make this efficiently is to use flat builds, which comes back to the same issue.

**Comment by ldemailly** [comment]
k let's just first make sure everyone use the master sha
or tag 0.2.2 manually on api and use that tag everywhere by hand

**Comment by ldemailly** [comment]
what is the complete list ? can we write a script that makes the updates everywhere ?

**Comment by sebastienvas** [comment]
as of today the list is istio, mixer, pilot, auth, proxy, mixerclient, api. 
mixer, pilot, auth, proxy actually provide artifacts so it should be easy to update the tool that we have to include proxy, the remaining 2 are kind of not easy to do as the mixerclient and api are barried in proxy files and as we pointed out pilot might use a different version that proxy uses etc.... I think we should limit to  repo that provide artifacts

**Comment by ldemailly** [comment]
let's try to do all as they all directly or indirectly contribute to the binaries

do you have a file list?

**Comment by sebastienvas** [comment]
I ll automate proxy. The rest is not straightforward.

**Comment by sakshigoel12** [comment]
not yet for mixer client. manual for now, let finish the rest after 0.2
