### ISSUE TITLE
Release script needs to set the correct tag in helm config

### ISSUE THREAD

**Issue by hklai** [istio/istio#7261]
**Describe the bug**
The tag value in values.yaml in both istio-1.0.0-snapshot.1 and istio-release-1.0-20180719-09-15 are pointing to release-1.0-latest-daily, instead of the actual version (i.e. istio-1.0.0-snapshot.1 and istio-release-1.0-20180719-09-15). This is a regression from earlier daily releases.

This needs to be fixed ASAP, and must be by 1.0.0.

**Expected behavior**
The tag value should be set tot the release tag.

**Comment by hklai** [comment]
Update: this seems to be a problem with osx binaries. linux binaries look fine.

**Comment by yutongz** [comment]
Pushed a fix online and kicked off a new daily-release to verify. (Since daily and monthly share the same part of code, so we can use daily result to verify).

Will report back when it's verified.

**Comment by yutongz** [comment]
Fixed.
Example: https://gcsweb.istio.io/gcs/istio-release-pipeline-data/daily-build/release-1.0-20180722-02-44/
