### ISSUE TITLE
Automatic sidecar injection not working

### ISSUE THREAD

**Issue by shettyh** [istio/istio#7266]
**Describe the bug**
Trying to deploy the Bookinfo sample with istio, it works fine with manual `kube-inject` command but not with automatic sidecar injection

**Expected behavior**
Should work fine with automatic side car injection also

**Version**
- Kubernetes 
  Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Istio
  Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

**Is Istio Auth enabled or not?**
```helm install install/kubernetes/helm/istio --name istio --namespace istio-system```

**Environment**
CentOS, On-Premise

All the solutions from the other issues or docs not seem to work, following info might be usefull

- API server flags
  ``` --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota```

- Admission registration
  ```admissionregistration.k8s.io/v1beta1```

- Events log
```Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: unexpected EOF```

**Comment by LillyWu** [comment]
@shettyh  could you check whether your default namesapce is labeled with `istio-injection` with command `kubectl get namespace -L istio-injection`. If it's labeled, it should return 
```
NAME             STATUS    AGE       ISTIO-INJECTION
default          Active    87d       enabled
```
otherwise, please label it with `kubectl label namespace default istio-injection=enabled` and try to bookinfo from the beginning again. If every pod runs two containers, then the sidecar is injected.

For much more details, please follow: https://istio.io/docs/setup/kubernetes/sidecar-injection/#deploying-an-app

**Comment by shettyh** [comment]
Yes the namespace has the label

```
NAME                 STATUS        AGE       ISTIO-INJECTION
default              Active        44d       enabled
ingress-controller   Active        38d
ingress-nginx        Active        16d
istio-system         Active        17h
kube-public          Active        44d
kube-system          Active        44d
minio-kube           Active        1d
monitoring           Active        2d
moss-edge            Active        44d
naren                Active        2d
ndn-cloud            Active        4h
rook                 Terminating   41d
test                 Active        14d       enabled

```

Pods itself is not created and `kubectl get events` displays this error

```
   1m           14        reviews-v2-8cb9489c6.1543312eb30d9c1c           ReplicaSet                                  Warning   FailedCreate                                                    replicaset-controller                   Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: unexpected EOF

```

**Comment by LillyWu** [comment]
@shettyh  is your kubernetes version > 1.9 ?

**Comment by shettyh** [comment]
@LillyWu 

- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- ```istio-sidecar-injector``` logs

```
...
    securityContext:
        privileged: false
        readOnlyRootFilesystem: true
        [[ if eq (or (index .ObjectMeta.Annotations "sidecar.istio.io/interceptionMode") .ProxyConfig.InterceptionMode.String) "TPROXY" -]]
        capabilities:
          add:
          - NET_ADMIN
        [[ else -]]
        runAsUser: 1337
        [[ end -]]
    restartPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
  volumes:
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - name: istio-certs
    secret:
      optional: true
      [[ if eq .Spec.ServiceAccountName "" -]]
      secretName: istio.default
      [[ else -]]
      secretName: [[ printf "istio.%s" .Spec.ServiceAccountName ]]
      [[ end -]]
2018-07-20T03:29:54.832062Z     warn    Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

**Comment by LillyWu** [comment]
@shettyh  I can't repro this error in IBM Kubernetes Service. But some other users have the same issue which related to the kuberneter deployment, could you check this: https://github.com/istio/old_issues_repo/issues/271

**Comment by shettyh** [comment]
Upgraded to Istio 1.0 still i am facing the same issue

**Comment by ajit-hybris** [comment]
I am facing the same issue, has any one found solution in the mean time?

**Comment by iedwin** [comment]
Facing the same issue too, my workaround is just changing the sidecar injection method from auto-inject to manually-inject.

**Comment by ajit-hybris** [comment]
For now, solution is to disable AlwaysPullImages admission controller.  Details https://github.com/kubernetes/kubernetes/issues/64333

**Comment by shettyh** [comment]
@LillyWu 
@ajit-hybris tried by disabling the `AlwaysPullImages`. Still same issue.

I am getting this error in `istio-sidecar-injector` pod

```
error   Patch webhook failed: Get https://10.96.0.1:443/apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/istio-sidecar-injector: dial tcp 10.96.0.1:443: connect: connection refused
``

Any idea ?

**Comment by shettyh** [comment]
API server was configured with `proxy` thats why it was able to contact web hooks. Removed proxy from API server. Auto injection works fine

**Comment by ShaikhMJAM** [comment]
Hi I am faing same issue can someone help me
