### ISSUE TITLE
Can't install Istio 1.0.0-snapshot.1 - 1.0.0 Preview on kubernetes 1.10

### ISSUE THREAD

**Issue by Tristar666** [istio/istio#7270]
Command: kubectl apply -f istio-demo.yaml

Error message: The CustomResourceDefinition "rbacconfigs.config.istio.io" is invalid: spec.scope: Invalid value: "Namespaced": field is immutable

Istio version: 1.0.0-snapshot.1 - 1.0.0 Preview

[root@kube-istio-0 kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ymesika** [comment]
@Tristar666 Thanks for reporting. See PR #7271 for a suggestion to fix this issue.
For a quick fix, and assuming you don't mind cleaning your Istio cluster, remove this CRD before installing the new Istio with:
```
kubectl delete crd rbacconfigs.config.istio.io
```

**Comment by Tristar666** [comment]
@ymesika thanks. I've removed CRD and it works. Checked on fresh installed kubernetes v1.10 and error did't occur.
