### ISSUE TITLE
Sample istio callme-service not follwing the route rule definition 

### ISSUE THREAD

**Issue by varnaik** [istio/istio#7275]
Bug Description:
Curl on the caller-service not routing to the callme-service based on the traffic split definition in routing rule. Sample routing rule splits traffic in proportions 20:80 between versions 1.0 and 2.0 of the callme-service.

Existing behavior:
$ kubectl get svc
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
caller-service   NodePort    10.105.206.86    <none>        8090:30465/TCP   1h
callme-service   NodePort    10.104.166.27    <none>        8091:30484/TCP   1h
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version 
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:1.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:1.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:1.0.0-SNAPSHOT with version null

Expected behavior:
$ kubectl get svc
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
caller-service   NodePort    10.105.206.86    <none>        8090:30465/TCP   1h
callme-service   NodePort    10.104.166.27    <none>        8091:30484/TCP   1h
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:1.0.0-SNAPSHOT with version 
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:1.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null
$ curl -L http://10.105.206.86:8090/caller/ping
caller-service:1.0.0-SNAPSHOT. Calling... callme-service:2.0.0-SNAPSHOT with version null

Steps to reproduce the bug:
Followed the below links:
Repo from:
https://github.com/piomin/sample-istio-services
Steps as in :
https://dzone.com/articles/service-mesh-with-istio-on-kubernetes-in-5-steps

Version:
$ istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Is Istio Auth enabled or not?:
Installation with Helm
https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template.
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system

Routing rules 
routerule.yaml
![routerule](https://user-images.githubusercontent.com/41481321/43010797-1ea04f08-8c5f-11e8-9097-2ffa125b7929.PNG)

caller-service.yaml
![caller-service](https://user-images.githubusercontent.com/41481321/43010828-37db5ce2-8c5f-11e8-89ab-bf4366b30ddd.PNG)

callme-service-v1.yaml
![callme-service-v1](https://user-images.githubusercontent.com/41481321/43010854-46404162-8c5f-11e8-9c3d-26d4377506a6.PNG)

callme-service-v2.yaml
![callme-service-v2](https://user-images.githubusercontent.com/41481321/43010862-4f49b6d0-8c5f-11e8-9ae1-dc832341c45d.PNG)

Curl commands show that the routing is still round robin ( callme-service:2.0.0-SNAPSHOT and callme-service:1.0.0-SNAPSHOT with traffic splitting 50:50 ) as opposed to what is specified in the routerule.yaml ( 20:80 ).

**Comment by rshriram** [comment]
Can you use the newer routing rules (virtual services, etc. ) ?

**Comment by varnaik** [comment]
With Virtual Service , the curl to the caller gives the desired output ..
i.e, curl -L http://10.105.206.86:8090/caller/ping pings the callme-service based on the VirtualService definition of callme-service .

But the curl on callme-service , still follows the round-robin in selecting the different versions of callme-service..
i.e, curl -L http://10.106.113.204:8091/callme/ping
Is this an expected behavior ? 
I  wanted to achieve the routing using a single ( standalone ) service using istio .
Example :  Consul service 

[consulv2.txt](https://github.com/istio/istio/files/2222148/consulv2.txt)
[consul_route.txt](https://github.com/istio/istio/files/2222149/consul_route.txt)
[consulv1.txt](https://github.com/istio/istio/files/2222150/consulv1.txt)

$kubectl get svc
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
consul-service   NodePort    10.97.12.114     <none>        8500:32457/TCP   19h

$kubectl get endpoints
NAME                           ENDPOINTS                           AGE
consul-service   10.244.0.84:8500,10.244.1.34:8500   19h

Now , "curl -L http://10.97.12.114:8500/v1/catalog/nodes" should route to the desired version of consul-service as defined in the VirtualService ( consul_route.txt attached ). 
Is the routing achievable using single service with multiple versions and istio  ?

**Comment by varnaik** [comment]
I was able to achieve the desired traffic routing using a "Gateway" 
[consul-gateway.txt](https://github.com/istio/istio/files/2243929/consul-gateway.txt)
[consul-service.txt](https://github.com/istio/istio/files/2243930/consul-service.txt)

LoadBalancing works as expected when curl is done on INGRESS_HOST and INGRESS_PORT ( determining INGRESS_HOST and INGRESS_PORT present [here](https://istio.io/docs/tasks/traffic-management/ingress/) )

Traffic routing rules work when curled upon INGRESS_HOST/INGRESS_PORT and **NOT** when curled upon service ClusterIP/ClusterPort 
$ curl -L http://10.97.12.114:8500/v1/catalog/nodes -- Does not work
$ curl -L http://$INGRESS_HOST:$INGRESS_PORT/v1/catalog/nodes  -- WORKS
 
Is this an expected behavior ? 
Also , curl -L http://10.106.113.204:8091/callme/ping doesn't follow route rule..
Is this also expected behavior ?
