### ISSUE TITLE
Istio installation profiles

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#7279]
Helm pre-cooked installation profiles to support various way of deploying Istio:
- networking
- ingress only
- mixer
- with galley and validation
- mesh expansion
- multi-cluster
etc.

We also need automated testing to validate they work.

**Comment by kyessenov** [comment]
I want to highlight the problem that pilot CRs are present across other component installation templates, preventing isolated component installs without pilot.

**Comment by kyessenov** [comment]
Note: test and release is not responsible for installation.

**Comment by louiscryan** [comment]
Hey @sdake since you've volunteered we're probably going to need a design doc for this and review in the environments WG

**Comment by sdake** [comment]
@louiscryan looks like @linsun has proposed a design here:

https://docs.google.com/document/d/1gfmj7vRBGBsLnzChWL_Hzc-EcZLlsmgUGBSxQDUXBzc/edit#
