### ISSUE TITLE
Task "docs/tasks/policy-enforcement/rate-limiting/index.md" is missing creation of DestinationRules used by "reviews" and "ratings" VirtualServices

### ISSUE THREAD

**Issue by witlessbird** [istio/istio#7285]
**Describe the bug**
After applying virtual service configuration as described in step 3, attempts to reach /productpage result in "Error fetching product details!" and "Error fetching product reviews!" errors.  

**Expected behavior**
/productpage should render without errors

**Steps to reproduce the bug**
Follow the steps described in the task.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
kubernetes: 1.10
istio: 1.0.0-snapshot.1

**Is Istio Auth enabled or not?**
No

**Environment**
minikube

**Comment by frankbu** [comment]
This has been recently fixed by creating the destination rules up front when the bookinfo app is started, so none of bookinfo-based tasks need to worry about creating them.
https://preliminary.istio.io/docs/examples/bookinfo/#apply-default-destination-rules

**Comment by witlessbird** [comment]
I'm going to close the issue, as it has already been fixed (thank you for pointing to the changes in bookinfo installation docs, @frankbu).
