### ISSUE TITLE
Services loose connectivity during mixer policy restart

### ISSUE THREAD

**Issue by cdmitri** [istio/istio#7334]
**Describe the bug**
Services with prior connectivity loose connectivity during istio-policy restart

**Expected behavior**
Service connectivity remain unaffected during istio-policy restart

**Steps to reproduce the bug**
1. Deploy latest release-1.0 build with istio-demo.yaml on single node cluster
2. Scale istio-policy to 2 replicas
3. Run 1 replica of service A issuing HTTP GET to 1 replica of service B
4. Observe that A->B with no errors
5. Simulate mixer failure by deleting pod
```sh
### kill mixer 1:1
$ kubectl delete pod istio-policy-d9d9d7d6-f4vfp -n istio-system; kubectl get pods -n istio-system --watch
pod "istio-policy-d9d9d7d6-f4vfp" deleted
NAME                                        READY     STATUS              RESTARTS   AGE
grafana-68ff89f9ff-cdr9v                    1/1       Running             0          11m
istio-citadel-6fd4747d74-q6556              1/1       Running             0          11m
istio-cleanup-secrets-b7pkw                 0/1       Completed           0          11m
istio-egressgateway-8689d84656-xcn7q        1/1       Running             0          11m
istio-galley-bc65ccfc4-dq5sp                1/1       Running             0          11m
istio-grafana-post-install-hl5sm            0/1       Completed           0          11m
istio-ingressgateway-84ffcdd574-x86bt       1/1       Running             0          11m
istio-mixer-post-install-1.0-7cbbs          0/1       Completed           0          11m
istio-pilot-878dd49f6-sgpwp                 2/2       Running             0          11m
istio-policy-d9d9d7d6-4gnmf                 0/2       ContainerCreating   0          0s
istio-policy-d9d9d7d6-f4vfp                 2/2       Terminating         0          2m
istio-sidecar-injector-7b4f7c4bcc-mp5c2     1/1       Running             0          11m
istio-statsd-prom-bridge-6889648ccf-4kzmw   1/1       Running             0          11m
istio-telemetry-698c747dc5-9dfj4            2/2       Running             0          11m
istio-tracing-ff7787d49-2q4rd               1/1       Running             0          11m
prometheus-ffd95f9f6-bd26d                  1/1       Running             0          11m
servicegraph-799dbb89cc-pfftj               1/1       Running             0          11m
istio-policy-d9d9d7d6-f4vfp   0/2       Terminating   0         2m
istio-policy-d9d9d7d6-f4vfp   0/2       Terminating   0         2m
istio-policy-d9d9d7d6-4gnmf   2/2       Running   0         2s
istio-policy-d9d9d7d6-f4vfp   0/2       Terminating   0         2m
istio-policy-d9d9d7d6-f4vfp   0/2       Terminating   0         2m
``` 
5. Observe connectivity disrupted during istio-policy recovery
```sh
2018-07-23T18:57:01+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:57:31+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:57:32+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:57:32+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:57:33+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:57:36+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:57:36+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
```
NOTE: similar behavior observed with 1 mixer replica as well. Also, failure has been simulated with:
```sh
 ### kill mixer 1:2 FAILURE: A-flapping
$ docker kill 2ba1d6b8e394; kubectl get pods -n istio-system --watch
2ba1d6b8e394
NAME                                        READY     STATUS      RESTARTS   AGE
grafana-68ff89f9ff-cdr9v                    1/1       Running     0          1h
istio-citadel-6fd4747d74-q6556              1/1       Running     0          1h
istio-cleanup-secrets-b7pkw                 0/1       Completed   0          1h
istio-egressgateway-8689d84656-xcn7q        1/1       Running     0          1h
istio-galley-bc65ccfc4-dq5sp                1/1       Running     0          1h
istio-grafana-post-install-hl5sm            0/1       Completed   0          1h
istio-ingressgateway-84ffcdd574-x86bt       1/1       Running     0          1h
istio-mixer-post-install-1.0-7cbbs          0/1       Completed   0          1h
istio-pilot-878dd49f6-sgpwp                 2/2       Running     0          1h
istio-policy-d9d9d7d6-9f24r                 2/2       Running     0          34m
istio-policy-d9d9d7d6-krk2q                 2/2       Running     1          42m
istio-sidecar-injector-7b4f7c4bcc-mp5c2     1/1       Running     0          1h
istio-statsd-prom-bridge-6889648ccf-4kzmw   1/1       Running     0          1h
istio-telemetry-698c747dc5-9dfj4            2/2       Running     0          1h
istio-tracing-ff7787d49-2q4rd               1/1       Running     0          1h
prometheus-ffd95f9f6-bd26d                  1/1       Running     0          1h
servicegraph-799dbb89cc-pfftj               1/1       Running     0          1h
istio-policy-d9d9d7d6-9f24r   1/2       Error     0         34m
istio-policy-d9d9d7d6-9f24r   2/2       Running   1         34m

# result:
2018-07-23T18:44:08+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:47:09+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:47:10+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:47:11+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:47:11+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
2018-07-23T18:47:13+00:00 CONSOLE: http://squeak-devshell:32323 -> no response
2018-07-23T18:47:13+00:00 CONSOLE: http://squeak-devshell:32323 -> {"id":"squeak.devshell-cl-sc-zlocal-n2dvm"}
```

NOTE:  There are 3 results overall:  A: flapping, B: cannot connect for 20s+, C: no disruption. A->B HTTP requests are done at 0.5s intervals.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
Istio: Version: release-1.0-20180723-09-15
Kubernetes: v1.10.2

**Is Istio Auth enabled or not?*
```$ kubectl create -f install/kubernetes/istio-demo.yaml```

**Environment**
kubeadm single node cluster in VM for testing

**Comment by kyessenov** [comment]
/kind area/networking

I think this is due to a delay in propagating endpoints from pilot.

**Comment by cdmitri** [comment]
The interesting part also is the A failure mode above - where the connectivity is "flapping".  

The way the above test works is that new output is only at the "status change", so since there is a call every 0.5s there are at least a couple of calls that return no response vs. successful connect, with only 1 replica/pod/ip on the other end.

**Comment by mandarjog** [comment]
@cdmitri do you receive a 503 or 403 as a reponse? The real solution here is health checking from client side to the Mixer upstream. I will try adding outlier detection or real remote health checks.

Pilot cannot guarantee speedy removal of stale endpoints, so the client side envoy has to do it.

**Comment by kyessenov** [comment]
@mandarjog It is trivial to set-up an active health check on envoy (see https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#envoy-api-msg-core-healthcheck-httphealthcheck). The problem is lack of istio API to propagate down to clusters (destination policy I guess), and the desire to standardize on gRPC health checking (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

**Comment by rshriram** [comment]
There is always going to be a delay (no matter how small) between deleting a mixer pod and updating Envoy lb pools - and in a system where application is constantly sending requests, the application will see failures. 

We can reduce the flapping period but the fact remains that there will be downtime if you delete a mixer pod, until all envoys to that pod talk to other pods. 

What you might want to experiment with is the fail_open mode. By default, envoys are in fail close mode with regard to mixer. Mixer down no connection or communication. I think there is a global config that you can set to make envoys fail open when mixer is out.

**Comment by mandarjog** [comment]
Continuing to send requests to mixer which does not exists is clearly incorrect. I want to use upstream health checks for that. Perhaps outlier detection will work as well.

The current behavior seems incorrect. Don’t repeatedly try to send traffic to a destination that results in a network error.
Also if connect error happens for one endpoint then try another one, not sure if this is happening.

Partial transaction cannot be safely retired unless we can assert that it is safe to do so.
We can asset that check can be safely retried.

**Comment by cdmitri** [comment]
@kyessenov @mandarjog @rshriram I'll write some traces to capture all the response codes and also envoy config changes [and errors] on both ends to see the full picture. Will update this issue with the details. Thanks for looking at this!

**Comment by ayushpateria** [comment]
@kyessenov @mandarjog @rshriram 
What's the status on this? This problem doesn't seem to be limited to only mixer. We use our gRPC services on preemptible nodes, and whenever there is a node preemption we see increase in error rates our gateway. The error rate is pretty high and doesn't go down until 4-5 mins. I think it's quite important for Istio to use Envoy active health checks - I understand we cannot avoid the errors completely, but currently the period is too long for us to use Istio in production.

**Comment by cdmitri** [comment]
@ayushpateria - to my last commnet - we made a test plan that we were comleting and now are coming back around and I'm starting to look at the new test framework "integration2" to see how more data can be captured. If we get back to this and there are any updates on our end, I'll post them here.

**Comment by miracle-jia** [comment]
Does any proccess on this issue?
We use the 1.3.0 version and restart the istio-policy, our service cannot be access.

Here is our issue:
Our deployment is configured a liveness probe to health check every 3 or 5 second. When the istio-policy restarted, during the restart, the pod envoy cannot connect to policy, all of request will be delayed 5 seconds. While the health check request is deplayed 5 second, the liveness probe failed always and then the pod will be restart, eventually leads to service cannot be access during the pod restart. 

Does anyone knows?

**Comment by miracle-jia** [comment]
The management plane‘abnormal causes the user pod cannot be access. Is this reasonable?
