### ISSUE TITLE
Add field into issue form

### ISSUE THREAD

**Issue by jsenon** [istio/istio#7341]
**Is your feature request related to a problem? Please describe.**
Don't have enough info regarding cloud provider when issue is open

**Describe the solution you'd like**
Add field asking cloud provider/on premise info

**Describe alternatives you've considered**
Ask question on thread

**Additional context**
N/A

**Comment by ymesika** [comment]
We actually do have `Environment - Which environment, cloud vendor, OS, etc are you using?` section in the template of opening a bug.
Are you referring to "Feature" issue?
