### ISSUE TITLE
redudant whitespace in clusterrole.yaml make it fails to run parse

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#7383]
**Describe the bug**
redudant whitespace in clusterrole.yaml make it fails to run parse
Error: YAML parse error on istio-remote/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context
**Expected behavior**
pasring should succeed

**Steps to reproduce the bug**
Just run 'helm install install/kubernetes/helm/istio-remote --name istio-remote --set global.pilotEndpoint=${PILOT_POD_IP} --set global.policyEndpoint=${POLICY_POD_IP} --set global.statsdEndpoint=${STATSD_POD_IP} --namespace istio-system
'

**Version**
1.0

**Is Istio Auth enabled or not?**
NO

**Environment**
Ubuntu

**Comment by munnerz** [comment]
Also #7358 - although it looks like you've already created a similar PR 😄

**Comment by irisdingbj** [comment]
@munnerz oh, yes, I have not seen your PR :(  Anyway, the fix is in now.
