### ISSUE TITLE
NPE when adding remote cluster

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#7386]
**Describe the bug**
I am trying the multi-cluster scenarios in istio following the doc https://istio.io/docs/setup/kubernetes/multicluster-install/
but after I add the remote cluster's config as secret into the local cluster, my pilot fails to run:

Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

**Expected behavior**

**Steps to reproduce the bug**

**Version**

0.8
**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
ubuntu

**Comment by irisdingbj** [comment]
Found some clue. will submit a PR soon.

**Comment by sdake** [comment]
docs are here: https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/

Cheers
-steve

**Comment by irisdingbj** [comment]
@sdake  Thanks for this pointer.  Tried using the release-1.0 build and the problem is fixed.
