### ISSUE TITLE
istio resource informer

### ISSUE THREAD

**Issue by cnicy** [istio/istio#7390]
**Is your feature request related to a problem? Please describe.**
 I want to do a API level operation on the resources of istio
K8s provides a informer mechanism for the operation of a resource object, but when I analyze istio, I find that istio's client does not provide the watch method, and the restclient in client is private, so I think it is more troublesome to construct watch by myself. I would like to ask what methods should be used if we want to achieve monitoring of resources.

example:

`import (
	"istio.io/istio/pilot/pkg/config/kube/crd"
	"yunzhicloud.com/istio/utils/k8s"
)

type Gateway interface {
	List(ns string) (list *crd.GatewayList, err error)
}

type gateway struct {
	client *crd.Client
}

func NewGateway() (g Gateway, err error) {
	client, err := k8s.NewIstioClient()
	if nil != err {
		return nil, err
	}
	return &gateway{client: client}, nil
}

func (c *gateway) List(ns string) (*crd.GatewayList, error) {
	return &crd.GatewayList{}, nil
}`

c.client not found watch method?
and  I look at the source code found (Istio-0.8)：
https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/controller.go
line 108--120 There is such a code snippet

`rc.dynamic.Get().
				Prefix("watch").
				Namespace(namespace).
				Resource(ResourceName(schema.Plural)).
				VersionedParams(&opts, meta_v1.ParameterCodec).
				Watch()`
but the restclient is  not expose 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by rshriram** [comment]
Istio does not store the resources. You can use the standard informers on k8s CRDs related to Istio

**Comment by ozevren** [comment]
I think https://github.com/istio/istio/issues/8772 will cover this. Closing this as a dupe.
