### ISSUE TITLE
Use release versions of tools (such as protoc, gogo).

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7395]
Context: https://github.com/istio/api/pull/591#pullrequestreview-140394392

Our tool dependencies tend to use the master/latest version of the tools. We should update our tooling to target stable/released versions.

Specifically, the docker file in istio/api that creates a docker image with these tools needs to be updated for this purpose.

@kyessenov

**Comment by ozevren** [comment]
@hklai FYI.

**Comment by kyessenov** [comment]
Big 👍 . A docker image with all the tools pre-installed seems like the easiest way to do until proper tooling exists for go (bazel/vgo/whatever).
