### ISSUE TITLE
Most Container do not handle SIGTERM

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#7397]
**Describe the bug**
While instrumenting the binaries for code coverage I noticed that some container did not provide any report (actually only pilot discovery and side car agent do) I realized that the server did not handle SIGTERM, and therefore the Test created to gather coverage could not report data.

**Expected behavior**
When a pod needs to be terminated, kubernetes sends a SIGTERM, which should be handle by the binary to gracefully shutdown or at least stop receiving new request. After a while a kubernetes will send a SIGKILL. Handling SIGTERM is very important for roll out and upgrade.

**Steps to reproduce the bug**
Start a binary and send a SIGTERM

**Version**
Master d836d2ffbe279cf74b38902f6f998dafafa55f4a, also present in most version before 1.0.

**Is Istio Auth enabled or not?**
Does not matter

**Environment**
Kubernetes

**Comment by douglas-reid** [comment]
cc: @geeknoid we should add signal handling to Mixer.

**Comment by markusthoemmes** [comment]
On top, I believe that pilot should handle SIGTERM gracefully as well, especially the pilot-agent. It should gracefully shutdown all envoy proxies before exiting itself, causing a sidecar to vanish.
