### ISSUE TITLE
Helm setting ingressgateway.type to NodePort does not work

### ISSUE THREAD

**Issue by arkanmgerges** [istio/istio#7402]
**Describe the bug**
In your master branch v1.0, it's specified on [Using helm to install Istio](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/)

--set ingressgateway.service.type=NodePort, and this has no effect

**Expected behavior**
istio-ingressgateway service should be of type NodePort

**Steps to reproduce the bug**
1. git clone https://github.com/istio/istio.git
2. helm install istio/install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set ingressgateway.service.type=NodePort \
    --set sidecarInjectorWebhook.enabled=false

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
```sh
root@node1:/home/arkan# k version -o yaml
clientVersion:
  buildDate: 2018-07-17T18:53:20Z
  compiler: gc
  gitCommit: b1b29978270dc22fecc592ac55d903350454310a
  gitTreeState: clean
  gitVersion: v1.11.1
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-27T20:08:34Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: linux/amd64
```

**Is Istio Auth enabled or not?**
helm install istio/install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set ingressgateway.service.type=NodePort \
    --set sidecarInjectorWebhook.enabled=false

**Environment**
Which environment, cloud vendor, OS, etc are you using?
6 nodes using VirtualBox installed on a laptop
```sh
root@node1:/home/arkan# uname -a
Linux node1 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@node1:/home/arkan# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by ymesika** [comment]
Doc issue. Should be `--set gateways.istio-ingressgateway.type=NodePort`.
Thanks.

**Comment by arkanmgerges** [comment]
Hi,
The same problem goes for --set egressgateway.service.type=NodePort

**Comment by AntoineNGUYEN31** [comment]
Hi, you can verify the option by doing: "helm show values istio/gateway"
The good option is : --set service.type=NodePort
