### ISSUE TITLE
How to do ip whitelisting in istio

### ISSUE THREAD

**Issue by huydinhle** [istio/istio#7427]
How do you configure your gateway or virtual service to do ip-whitelisting. Right now it seems that the ingress gateway created a public load balancer. This is great for ingress traffic for public endpoint. But what if there is some endpoints that should be only accessed from internal network. How would I do that ip whitelisting in istio.

**Comment by huydinhle** [comment]
The only thing I see is using sourceSubnet in virtualservice

**Comment by nixgadget** [comment]
I just have a Nginx proxy sitting infront of the Gateway doing the whitelisting. I myself couldnt find a similar feature in Istio.

**Comment by huydinhle** [comment]
A work-around that I have done is that creating a different ingressgateway deployment and service manually. And with the loadbalancer service you created, just add ip-source range in there because kubernetes support it

**Comment by dunjut** [comment]
@huydinhle You can deploy two sets of ingressgateways. One for public APIs, deployed on edge nodes with internet access and firewall configured; the other one for internal APIs, deployed on nodes inside private networks.

Checkout: https://github.com/istio/istio/issues/8428

**Comment by vinaykumard** [comment]
If you are using GKE then you can use Cloud NAT and private cluster combination to route all your request through a public IP which you can use to whitelisted, as all request will be routed through this IP. 
https://cloud.google.com/nat/docs/overview#NATwithGKE

**Comment by nesl247** [comment]
This is definitely a concern of ours as well. We'd rather not deploy a second `ingressgateway` as that will have to be self-maintained rather than automatically maintained via the GKE Istio addon.

**Comment by Eslamanwar** [comment]
Is there any Annotation like
```
  annotations:
    ingress.kubernetes.io/whitelist-source-range: "1.1.1.1/32"
```
to white list certain CIDRs
