### ISSUE TITLE
daily build flakey:  debug_test.go:157: wanted RouteAcked set true got  for syncApp-644fc65469-96dza.testns

### ISSUE THREAD

**Issue by duderino** [istio/istio#7429]
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/793/daily-unit-tests/384/

```
debug_test.go:157: wanted RouteAcked set true got  for syncApp-644fc65469-96dza.testns
```

Looks like the flakiness started with https://github.com/istio/istio/pull/6521/

**Comment by liamawhite** [comment]
Is there anywhere I can see builds over time where this test has failed?

**Comment by liamawhite** [comment]
I've been unable to recreate locally having run the package tests ~250 times. My best guess is a timing window with the mock Envoy acking the route. Would you be against be adding a sleep of 5 . seconds in front of the validation function? Its a bit crap but if it fixes it then we can see if we can come up with a better resolution.

**Comment by duderino** [comment]
How often would that validation function be called per run of the unit test suite?

Is it possible to wait until the mock envoy is initialized in some sort of event driven way (e.g., repeatedly try connecting to one of the mock's ports until a connection is accepted ... and fail the test if you can't connect after 5 sec)?
