### ISSUE TITLE
Pilot clearsCache() in response to any change event from configCache

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7431]
Pilot in [discovery.go::NewDiscoveryService()](https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/discovery.go#L374) registers a trivial `out.ClearCache()` function for a config change.

This means that every config change results in a complete re-computation of the cache.

This is a big deal if the change rate is high. The time taken to rebuild cache is proportional to the size of the istio deployment.

**Comment by mandarjog** [comment]
cc @zachgersh @costinm @rshriram

**Comment by kyessenov** [comment]
The way to solve this is to monitor individual resources, and maintain the dependencies between resources in the intermediate computations. Then we can propagate individual virtual host change all the way to RDS slice. I think there are some seeds of this idea (with the guarded host and so on), but there needs to be more discipline about pilot proto construction works.

**Comment by rshriram** [comment]
We are very well aware of the problem. Will be working on fixing in next couple of releases.

**Comment by mandarjog** [comment]
@costinm should we close this now? Is it done already ?
