### ISSUE TITLE
curl helloword service error：Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#744]
when create app helloword in local cluster
```
root@SZX1000353068:~/istio-0.2.1/samples/apps/helloworld# kubectl get svc helloworld
NAME         TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
helloworld   NodePort   10.0.0.111   <none>        5000:31858/TCP   16m

```
and I visit helloword
```
root@SZX1000353068:~/istio-0.2.1/samples/apps/helloworld# curl 127.0.0.1:5000/helloword
curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused

```

I curl pod ip, the same error, 
then I enter container, and curl 127.0.0.1:5000/helloword it works ok. But curl podIP:5000, still recv  Connection refused.

I do not know what's the matter

**Comment by hzxuzhonghu** [comment]
By the way, I use istio-0.2.1, kubernetes 
```
root@SZX1000353068:~/istio-0.2.1# kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2994+3cf7000b3b5947", GitCommit:"3cf7000b3b5947e957f1f54faa75680bc51a987c", GitTreeState:"clean", BuildDate:"2017-09-02T08:52:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ldemailly** [comment]
does curl http://helloworld:5000/ work ?
why do you expect localhost to work (unless you use kubectl port-forward ?)

**Comment by hzxuzhonghu** [comment]
because it is nodeport service.

**Comment by ldemailly** [comment]
Issue moved to [istio/pilot #1370](https://github.com/istio/pilot/issues/1370) via [**ZenHub**](https://www.zenhub.com/)
