### ISSUE TITLE
[Kiali] Security hole in helm chart

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#7447]
Kiali includes a dashbord, and cluster admin need configure `username` and `password` in `values.yaml` as https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/values.yaml#L504-L508  , this is a security hole, as the operator or the cluster viewer who can run `helm get --tls values istio` will be able to get the username and password for Kiali.

Seems we do not have a good solution for now, but a possible solution is we can update the README by highlighting if user want to use Kiali, they may want to create a secret first, and then let Kiali deployment use the pre-created secret. This can avoid configuring username and password in `values.yaml`.

/cc @sdake @costinm @gbaufake

**Comment by munnerz** [comment]
I think this is a general purpose problem with Helm to be honest - further, Helm releases are stored in configmaps in the Kubernetes cluster (alongside their values.yaml data).

> they may want to create a secret first, and then let Kiali deployment use the pre-created secret

+1, with Helm, I think this is one of the only ways to do it securely (and then add a `secretName` parameter to the values.yaml)

**Comment by gyliu513** [comment]
Thanks @munnerz , we are on same page ;-)

Let's get more comments from @sdake @costinm @gbaufake , and I hope that we can fix this in 1.0 GA release.

**Comment by gbaufake** [comment]
@gyliu513 
I see 2 options for this issue:

1- I think we can also generate it randomly and then the user could store it (from the logs) to use in the future (I don't know if that would be a good option)

2- Pre-generated secret as mentioned before.
@jmazzitelli any thoughts on this issue?

**Comment by gyliu513** [comment]
@gbaufake for option 1, if the password was generated randomly, do you mean get it from log? If so, this is also not safe to expose it in logs.

**Comment by jmazzitelli** [comment]
Kiali itself already uses a secret to store its user/pass - the example secret is here: https://github.com/kiali/kiali/blob/master/deploy/kubernetes/kiali-secrets.yaml

We would need the helm templates to use that secret and possibly have the user be able to override the user/pass in that secret. I'm not that familiar with helm, but I have to believe this is something that could be done, but I honestly don't know.

**Comment by gyliu513** [comment]
Thanks @jmazzitelli , as comments above, we can use the solution https://github.com/istio/istio/issues/7447#issuecomment-408433030 .

With this solution, end user need first create a secret, and then put secret name into `values.yaml` for Kiali reference.
