### ISSUE TITLE
Egress through proxy - example in documentation

### ISSUE THREAD

**Issue by Adiqq** [istio/istio#7448]
**Is your feature request related to a problem? Please describe.**
Istio allows to define external services e.g. http://www.google.pl/
In some environments access to public internet is not available directly, only through HTTP proxy.
Istio has no entry in documentation that shows how to configure it for such use case.
According to attached issue it should be possible, but I can't find e2e test that covers this use case.

**Describe the solution you'd like**
There should be example that shows how to configure egress traffic through HTTP proxy to external services.

**Describe alternatives you've considered**

**Additional context**
https://github.com/istio/istio/issues/4969

**Comment by FrediWeber** [comment]
We have the same problem.
I can't find any documentation on this.

@rshriram You referenced to a test case and an implementation. Can you point out where I can find these?

**Comment by xaka** [comment]
One of the solutions is here https://github.com/istio/istio/issues/7302 for those who are interested.

**Comment by FrediWeber** [comment]
@xaka Perfect, this works.
Maybe the doc should be updated to cover this case.
