### ISSUE TITLE
GKE default cluster too small to schedule pilot pod

### ISSUE THREAD

**Issue by duderino** [istio/istio#7459]
I ran into this while running through Bookinfo with the istio-release-1.0-20180727-14-34 daily build. 

I created GKE cluster following the instructions at  https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/gke/

I noticed the pilot pod never started:

```
kubectl get pods -n istio-system
NAME                                        READY     STATUS    RESTARTS   AGE
grafana-86cb97c8dc-ns28r                    1/1       Running   0          1h
istio-citadel-7579978b98-ssh9d              1/1       Running   0          1h
istio-egressgateway-7bbb9887d6-z2v94        1/1       Running   0          1h
istio-galley-5b9fd75ccf-rlgcw               1/1       Running   0          1h
istio-ingressgateway-54f7bc87cc-c8zxm       1/1       Running   0          1h
istio-pilot-ff8d97db-cfhxr                  0/2       Pending   0          1h
istio-policy-544ccbcc9c-gpzkq               2/2       Running   0          1h
istio-sidecar-injector-7b5879b66-pzvfz      1/1       Running   0          1h
istio-statsd-prom-bridge-6889648ccf-lm4k4   1/1       Running   0          1h
istio-telemetry-cbdf9f78-dtndl              2/2       Running   0          1h
istio-tracing-ff94688bb-77rcz               1/1       Running   0          1h
prometheus-5554fd4f79-7bjrf                 1/1       Running   0          1h
servicegraph-55c4b6f649-pjmxp               1/1       Running   0          1h
```

The GKE console showed that the pilot pod was unschedulable: https://photos.app.goo.gl/qRgFw9a5iTqDmkC66

I found two ways to get past this:  either add a 2+ vCPU node to the pool or reduce the resource settings in the istio-demo.yaml from 800m cpu to something smaller.   

Since we'd like to keep bookinfo footprint small, I'll send a PR to reduce the resource settings shortly.

**Comment by vhosakot** [comment]
I saw `istio-pilot` in 1.1 rc3 consume a lot of CPU and failed to start due to the following message in `kubectl describe <istio-pilot pod name> -n=istio-system`:

```
Warning  FailedScheduling  1m (x25 over 3m)  default-scheduler  0/2 nodes are available:
1 Insufficient cpu, 1 node(s) had taints that the pod didn't tolerate.
```

I was able to reduce it by doing `--set pilot.resources.requests.cpu=30m` when installing istio using helm.

https://github.com/istio/istio/blob/1.1.0-rc.3/install/kubernetes/helm/istio/charts/pilot/values.yaml#L16
