### ISSUE TITLE
[Grafana] Security hole in helm chart 

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#7476]
Same as https://github.com/istio/istio/issues/7447

Grafana includes a dashbord, and cluster admin need configure `username` and `password` in `values.yaml` as https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/values.yaml#L396-L397  , this is a security hole, as the operator or the cluster viewer who can run `helm get --tls values istio` will be able to get the username and password for Grafana.

Seems we do not have a good solution for now, but a possible solution is we can update the README by highlighting if user want to use Grafana, they may want to create a secret first, and then let Grafana deployment use the pre-created secret. This can avoid configuring username and password in `values.yaml`.

/cc @sdake @costinm @douglas-reid

**Comment by douglas-reid** [comment]
This seems like a terrible feature for helm to have.  But I don't see why it is a problem for the operator to be able to get the username and password that they would have set up?

**Comment by gyliu513** [comment]
The admin password should only be known by the admin user but not other users, like operator etc. Otherwise, the Grafana dashboard will be out of contorl, as for some security issue, we do not want non-admin users to view all resources in the cluster from Grafana.

**Comment by jmazzitelli** [comment]
[repeating the comment from issue #7447]
Kiali itself already uses a secret to store its user/pass - the example secret is here: https://github.com/kiali/kiali/blob/master/deploy/kubernetes/kiali-secrets.yaml

We would need the helm templates to use that secret and possibly have the user be able to override the user/pass in that secret. I'm not that familiar with helm, but I have to believe this is something that could be done, but I honestly don't know.
