### ISSUE TITLE
mixer Failed to list *v1.ReplicaSet: the server could not find the requested resource

### ISSUE THREAD

**Issue by chalvern** [istio/istio#7489]
**Describe the bug**

after deploy the 1.0.0-snapshot.2 in k8s (v1.8.6 as same as my production cluster), mixer Failed to list *v1.ReplicaSet: the server could not find the requested resource. 

**Expected behavior**

mixer works correct.

**Steps to reproduce the bug**
Steps to reproduce the behavior.
```bash
# start a k8s cluster
minikube start  --kubernetes-version v1.8.6

# apply istio 1.0.0-snapshort.2
kubectl apply -f install/kubernetes/istio-demo.yaml

# see the log

kubectl logs istio-telemetry-xxx-xxx -n istio-system -c mixer
```

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

```bash
minikube version
# output
minikube version: v0.28.0

istioctl version
# output
Version: 1.0.0-snapshot.2
GolangVersion: go1.10.1

kubectl version
# output
Client Version v1.10.1
Server Version v1.8.6


```

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

not enabled.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

minikube on MacOS

**Comment by chalvern** [comment]
seems like istio would not support k8s of v1.8.*, as the mixer newCacheController hardcode the appsv1ReplicaSet, referenced by following url: 
https://github.com/istio/istio/blob/release-1.0/mixer/adapter/kubernetesenv/cache.go#L94

at the same time , k8s of v1.8.* has no v1.ReplicaSet

https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#-strong-read-operations-strong--77

**Comment by douglas-reid** [comment]
I believe Istio requires k8s 1.9 or greater.

**Comment by douglas-reid** [comment]
Prior discussion: https://github.com/istio/istio/pull/6157

**Comment by roldanx** [comment]
Same error happening on Kubernetes 1.21.9:

istio-policy mixer logs:
`2022-12-02T11:49:26.467204Z	error	istio.io/istio/mixer/adapter/kubernetesenv/cache.go:148: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource`

kubeApiServer logs:
`{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"f893a655-7f14-4881-a0ab-1e06202fa963","stage":"ResponseComplete","requestURI":"/apis/extensions/v1beta1/replicasets?limit=500\u0026resourceVersion=0","verb":"list","user":{"username":"system:serviceaccount:istio-system:istio-mixer-service-account","uid":"7bb4da4b-a3ee-11e8-934e-005056a45b4c","groups":["system:serviceaccounts","system:serviceaccounts:istio-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["istio-policy-766bf4bd6d-f4f8d"],"authentication.kubernetes.io/pod-uid":["aae78f64-9354-4d5c-96a6-87ec54f6d39c"]}},"sourceIPs":["192.168.206.20"],"userAgent":"mixs/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"replicasets","apiGroup":"extensions","apiVersion":"v1beta1"},"responseStatus":{"metadata":{},"status":"Failure","reason":"NotFound","code":404},"requestReceivedTimestamp":"2022-12-02T10:46:00.691081Z","stageTimestamp":"2022-12-02T10:46:00.691541Z","annotations":{"authentication.k8s.io/stale-token":"subject: system:serviceaccount:istio-system:istio-mixer-service-account, seconds after warning threshold: 321717","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"istio-mixer-admin-role-binding-istio-system\" of ClusterRole \"istio-mixer-istio-system\" to ServiceAccount \"istio-mixer-service-account/istio-system\""}}`

Any clue?

**Comment by zirain** [comment]
mixer is EOL, please upgrade to latest version
