### ISSUE TITLE
301 redirection  in istio

### ISSUE THREAD

**Issue by stunn3r** [istio/istio#7497]
**Is your feature request related to a problem? Please describe.**

We are planningto move istio to production and doing extensive POCs and testing on it.

currently we are using NGINX-ingress, obviously with istio we would like to do all the things that we use to do with nginx, such as:

> location /folder/js-sdk.fonts.min.css {
> 
> 		proxy_pass http://static-dev.company.com/folder/live/js-sdk.fonts.min.css;
> 	}

This is a 301 redirection and not possible with istio.

**Describe the solution you'd like**

Is there any workaround to achieve this ?

**Describe alternatives you've considered**
I have thought of having nginx inside my mesh to and will forward all the calls, that istio cant handle as needed, to be routed to nginx.

**Additional context**
istio 0.8 without using HELM.

**Comment by ijsnellf** [comment]
Would you be able to use this?:
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPRedirect
