### ISSUE TITLE
[Galley] Combine Validation Webhook mode with Server Mode

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7500]
Currently, galley executable can start in either mode: An MCP server, or a validation web-hook. To reduce the cognitive load on operators, we should simplify it and reduce it to one:

- When Galley starts, it starts both the webhook module, and the server module.
- Either can be optionally disabled through command-line.

One important thing worth noting here is, both have different liveness/readiness probe modes, so those needs to be aligned as well.

The steps to complete this task are:

- [ ] Combine the liveness/readiness probes of both webhook and the server mode. We should standardize on istio.io/istio/pkg/probe, which server is already using.
- [ ] Make it so that both modes start when just typing "galley" (i.e. not "galley validator"  or "galley server", just "galley"). It should be possible to disable either mode.
- [ ] Update helm charts, so that they use the new form of the command-line.
- [ ] Remove other command-line modes.

**Comment by ozevren** [comment]
cc @irisdingbj

**Comment by irisdingbj** [comment]
@ozevren ^^
