### ISSUE TITLE
Unified Config Tooling Pipeline for Istio

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7502]
Our config related tooling in Istio is haphazardly grown. And this causes some issues:
- Many files needs to be kept manually in sync when changing things (i.e. changing a field, adding a new config proto, changing API version etc.). These set of files are generally not discoverable.
- It is easy to make mistakes and miss things, causing disruptions and latent bugs.
- There is no guard against accidentally breaking backward compatibility.

This epic captures some of the changes we can make to our config tooling pipeline to make things better. At a high-level, we should implement a toolchain, that starts from our source-of-truth (i.e. protos in istio/api), perform validation and flow it to the rest of the system.

In detail:

- A way to attach additional metadata to our protos to derive CRD information.
- A way to attach validation metadata to our protos to derive Open API Spec and automatic proto validation.
- Generate Go-based client libraries for our CRD's from the generated metadata.
- Enough metadata to flow into istio/istio, so that we can generate Pilot code, Galley code, Helm charts (w/ tests to protect against stale data).
- Automated test gate, so that stable APIs will not break backwards compat.

**Comment by howardjohn** [comment]
I believe we have all of these now
