### ISSUE TITLE
Provide SHA2-256 Checksum of Builds

### ISSUE THREAD

**Issue by duderino** [istio/istio#7506]
@jmassey-datadog commented on [Thu Mar 22 2018](https://github.com/istio/old_issues_repo/issues/247)

In an effort to provide more security, can you provide the SHA2-256 outputs of the build artifacts? These could be added to the release artifacts as `istio-${ISTIO_VERSION}-${OSEXT}.tar.gz.sha256`. The hash **should** be included in the release notes on Istio's website. 

If an attacker gains access to a github account who has rights to push an Istio release, she would also need to gain access to Istio's website to compromise the hash. 

---

@trishankatdatadog commented on [Thu Mar 22 2018](https://github.com/istio/old_issues_repo/issues/247#issuecomment-375347141)

I second this, especially with the separation of duties part, otherwise one risks running into the [same fate as Bitcoin Gold when they had their GitHub account hacked](https://bitcoingold.org/critical-warning-nov-26/).

In the long term, I would **strongly** recommend at least GPG-signing Istio artifacts. Hopefully, this [Yubikey guide](https://github.com/trishankatdatadog/yubikey) might come in handy.

---

@jwhitlark commented on [Mon Jul 30 2018](https://github.com/istio/old_issues_repo/issues/247#issuecomment-408958899)

Considering one of the big selling points of a service mesh is it's security, I'd say this needs to be a priority.  Especially since it's not hard to just add a sha-256.

I'm writing a book on cloud native dev practices, was just preaching security, and when writing the istio example, realized I couldn't confirm the checksum. :-(

**Comment by jmassey-datadog** [comment]
👀 watching

**Comment by jwhitlark** [comment]
I don't mean to be difficult about this, but I don't see how an encryption product can ship a 1.0 without checksums, (and signed commits, but that's for another issue)....

**Comment by jwhitlark** [comment]
This is somewhat related to https://github.com/istio/istio/issues/7511
