### ISSUE TITLE
SCTP Support 

### ISSUE THREAD

**Issue by varnaik** [istio/istio#7521]
SCTP ( Stream Control Transmission Protocol ) traffic support in istio.

Use-case: 
In Telecommunication industry , the core network of LTE which is the Evolved Packet Core (EPC), has a number of entities which use SCTP protocol to communicate with each other . 
This will enable istio to be used by many telecom vendors .

Do you plan to support the same in any of your future release ?

**Comment by ijsnellf** [comment]
I'm not qualified to talk about long term plans, but our underlying proxy (Envoy) does not support SCTP right now. To implement SCTP in Istio, SCTP support in Envoy would be required as a minimum. Link: www.envoyproxy.io

**Comment by janosi** [comment]
@ijsnellf I would like to understand, is it really so, that other proxy cannot integrate with Istio? Is Envoy a mandatory component as proxy? If other proxy can be integrated with Istio, can we say that SCTP support in Istio is independent from the same feature in Envoy? I.e. Istio could support "SCTP" as protocol value on the API to the proxy - no matter which proxy it is. Thank you!

**Comment by hwinkel** [comment]
AFAIK nginx has shown how to use nginx with istio as a proxy piloted by pilot
