### ISSUE TITLE
Configure external Prometheus

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7528]
**Is your feature request related to a problem? Please describe.**
The feature is related to this user question https://groups.google.com/forum/#!topic/istio-users/Rb3gnYekrck

**Describe the solution you'd like**
A helm configuration option to configure the URL of the external prometheus instance and an istio.io task to describe how to configure it.

**Describe alternatives you've considered**
An alternative is to redefine the `prometheus` Kubernetes service - to use a Kubernetes `ExternalName` service instead to point to the external prometheus service.

**Additional context**
Add any other context about the feature request here.

**Comment by marcuslindfeldt** [comment]
The official prometheus [helm chart](https://hub.kubeapps.com/charts/stable/prometheus) allows you to set annotations on the pods you wish to scrape and then automatically configures prometheus to scrape the endpoints defined in these annotations. 

As I understand it's the mixer that is exposing the metrics endpoints so it would be great if we can pass annotations to the mixer from the helm chart. Then you could do something like:

```
# helm values.yaml
...
mixer:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/" # If the metrics path is not `/metrics` override this.
    prometheus.io/port: "10123" # If the metrics are exposed on a different port to the service then set this appropriately.
```

**Comment by hd-deman** [comment]
And/Or support Prometheus operator
https://github.com/coreos/prometheus-operator/issues/1160

**Comment by linsun** [comment]
@ymesika could you help look into this?  A couple of IBM users also have asked about this.

**Comment by douglas-reid** [comment]
With the introduction of support for the prom operator in the new istio/installer, I believe we now have a path for external prometheus support. As such, I'm going to close this issue. Any issues with the prom operator-based approach should be raised against the installer repo.

Please re-open this issue if you think there is more that should be done here.
