### ISSUE TITLE
sample configuration using native Ingress instead of gateways

### ISSUE THREAD

**Issue by stephen-dahl** [istio/istio#7529]
**Is your feature request related to a problem? Please describe.**
I am using Rancher 2 and the ability to create ingress records through that UI is more important to me than the extra traffic routing features offered by gateways

**Describe the solution you'd like**
add a sample configuration that uses Ingress instead of gateways. preferably a values file.

**Describe alternatives you've considered**
20+ hours of trying to get it working on my own

**Additional context**
Add any other context about the feature request here.

**Comment by vadimeisenbergibm** [comment]
CC @rshriram @ZackButcher
