### ISSUE TITLE
Got the exception when installed istio since 1.0.0

### ISSUE THREAD

**Issue by thangchung** [istio/istio#7530]
**Describe the bug**
Update and run `istio 1.0.0`, and got the exception like

```
Error: apiVersion "config.istio.io/v1alpha3" in istio/charts/mixer/templates/config.yaml is not available
```

```
Error: apiVersion "networking.istio.io/v1alpha3" in istio/charts/pilot/templates/gateway.yaml is not available
```

**Expected behavior**
I expected that it should work like the previous version (`istio-1.0.0-snapshot.2`) on my machine.

**Steps to reproduce the bug**
Download `istio 1.0.0` at `https://github.com/istio/istio/releases/download/1.0.0/istio-1.0.0-win.zip`
I used `helm` to upgrade and run it

```
helm init --service-account tiller
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```

Then I got the exception like above

**Version**

Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Istio version
```
1.0.0 at https://github.com/istio/istio/releases/download/1.0.0/istio-1.0.0-win.zip
```

**Environment**
	
Windows 10 with Docker for Windows

**Comment by ymesika** [comment]
@thangchung There is a change in 1.0.0 in how you install using Helm - You need to create the CRD prior to running the `helm install` with `kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`.

Once 1.0.0 docs are alive you will notice this change in the docs.

**Comment by sanguinius69** [comment]
Can you update your docs then please ? Or When are they going live ?
Thanks

**Comment by ymesika** [comment]
@sanguinius69 It's already alive. Documented [here](https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps).

**Comment by thangchung** [comment]
@ymesika That's working now. Thank you very much for your quick response to us. 
@sanguinius69 Run `kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`, keep waiting seconds, then run `helm install install/kubernetes/helm/istio --name istio --namespace istio-system`. It should work!
