### ISSUE TITLE
Unable to have "opt in" behaviour of injection since 1.0

### ISSUE THREAD

**Issue by Stono** [istio/istio#7535]
**Describe the bug**
We run our cluster with a `sidecar-injector` config of `policy: disabled`, and then "opt in" the pods we want to have istio with the annotation:

```
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
```

**Observed behaviour**
Pods with this annotation are not injected.

```
2018-07-31T17:11:22.265486Z     info    AdmissionReview for Kind=/v1, Kind=Pod Namespace=default Name= () UID=bf97a4a8-94e4-11e8-b41a-42010aa4005e Rfc6902PatchOperation=CREATE UserInfo={system:serviceaccount:kube-system:replicaset-controller 786d5efc-5615-11e8-807f-42010aa40068 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]}
2018-07-31T17:11:22.265531Z     info    Skipping / due to policy check
```

**Expected behaviour**
On 0.8, this resulted in pods being injected if they have the annotation.

From our perspective, this means that istio has gone from "opt in" to "opt out" on our cluster, which is very none-backwards-compatible for us (we have plenty of deployments which don't specify the annotation and don't expect to be injected, but with policy: enabled, they would be).

**Comment by Stono** [comment]
OK I've worked this out.
There is a new config value in 1.0 `.Values.global.proxy.autoInject`, this used to be controlled by `.Values.global.proxy.policy`.  

I *incorrectly* read `autoInject` as a true/false value.  Whereas actually, `autoInject` is actually a straight mapping to the old `proxy.policy`, thus needs to be `disabled`, not `false.

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L15

So; 
  - Probably needs a better named config option or the helm template perhaps should transform `false` to `disabled`? 
  - Should be some validation somewhere that doesn't accept `policy: false` as a valid value.

**Comment by nmittler** [comment]
@ostromart can you take a look?

**Comment by ostromart** [comment]
Yes, this is on my plate. Will keep this bug open till the change is in.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/7572
This should at least avoid wild goose chases. Long term solution is to use operators for install to validate all that stuff.
