### ISSUE TITLE
Helm installation with Tiller is broken for 1.0

### ISSUE THREAD

**Issue by vilobhmm** [istio/istio#7551]
**Describe the bug**
Helm installation with Tiller is broken for 1.0

**Expected behavior**
Helm installation with Tiller should work and install Istio components under the istio-system namespace.

**Steps to reproduce the bug**
Follow the instructions here 

1. https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install

2. When you run 

$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
Error: render error in "istio/charts/prometheus/templates/ingress.yaml": template: istio/charts/prometheus/templates/ingress.yaml:1:14: executing "istio/charts/prometheus/templates/ingress.yaml" at <.Values.ingress.enab...>: can't evaluate field enabled in type interface {}

If you move the problematic file somewhere else just to avoid this problem like this

mv ./install/kubernetes/helm/istio/charts/prometheus/templates/ingress.yaml ~/.

you will run into another issue mentioned below.

$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system 
Error: the server has asked for the client to provide credentials

helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

All these things were working fine for the daily build istio-release-1.0-20180719-09-15

**Version**
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

K8S version : 1.9

**Is Istio Auth enabled or not?**
Nope
using istio-demo.yaml

**Environment**
GCP

**Comment by ymesika** [comment]
@vilobhmm What version of 1.0 are you using? I have the release one freshly downloaded and there is no file `istio/charts/prometheus/templates/ingress.yaml` within it.

**Comment by jiuchongxiao** [comment]
@vilobhmm  i have the same issue , did you solve it?

**Comment by rkpagadala** [comment]
@jiuchongxiao Vilobh deleted the .helm directory and it worked

**Comment by JCzz** [comment]
I have the same problem.

Tryed to deletge ~/.helm and re-installing helm. Did not work?

**Comment by ymesika** [comment]
Please re-open if you still experience this issue.
