### ISSUE TITLE
Virutal Service with lot of rules

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#7559]
We have an example here https://istio.io/docs/tasks/traffic-management/request-routing/#route-based-on-user-identity which is using `username` as the router rule.

In a real customer environment, they have almost 1M users, and they want each user have their own rules to access some services, does Istio can handle such scale if I create a virutalservice rule for each user? Or if there are other options to achieve this?

/cc @rshriram @vadimeisenbergibm

**Comment by ijsnellf** [comment]
That is just an example to demonstrate simple routing rules. It is not meant as a design pattern or recommendation for how to organize your architecture. I do not think this is any scenario you would want to have unique routing behavior for 1M users.

**Comment by mandarjog** [comment]
Can you elaborate on the requirements?
Truly unique routing behaviors seems incorrect. I can see that users belong with a group or a class and then a class may have unique routing behavior.

We surely have not tested with 1M virtual services.

**Comment by gyliu513** [comment]
Thanks @ijsnellf @mandarjog

Let me elaborate more for this case, using 1M user may not be accurate but agree with @mandarjog , all of those users belong to different groups and each group have different roles, so we need to set different virtualservices based on groups, and there are 5000+ groups for this organization.

So any good solutions to handle this 5000+ groups for their virutualservice management?
