### ISSUE TITLE
helm template does not generate sidecar-inject ConfigMap when injector webhook disabled

### ISSUE THREAD

**Issue by ostromart** [istio/istio#7567]
Reported by users
https://groups.google.com/forum/#!topic/istio-users/S04ure6q_-8

helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set sidecarInjectorWebhook.enabled=false > istio.yaml

works fine from the istio repo but not from the release tarball.
Possibly something helm related is missing from the release.

**Comment by rlenglet** [comment]
I don't see how that can possibly work in the release-1.0 branch without enabling the injector webhook: https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L1

**Comment by rlenglet** [comment]
That's maybe because the injector is enabled by default?
https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/values.yaml#L316

**Comment by ayj** [comment]
xref: https://github.com/istio/istio/pull/7565
