### ISSUE TITLE
Can not create gateway

### ISSUE THREAD

**Issue by mingweiLIU** [istio/istio#7583]
**Describe the bug**
Follow the doc "https://istio.io/docs/tasks/traffic-management/ingress/" to create gateway, Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: EOF
**Expected behavior**
The gateway should be created
**Steps to reproduce the bug**
Steps to reproduce the behavior.
1. Download istio and export the path:export PATH=$PWD/bin:$PATH

2.Install CRD:kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
 
3.Install istio with Helm:helm install install/kubernetes/helm/istio --name istio --namespace istio-system

4.manually inject the sidecar to deploying the httpbin application：kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml)

5. export INGRESS_PORT、SECURE_INGRESS_PORT and INGRESS_HOST
6. Create an Istio Gateway:
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
EOF
**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
istioctl version：
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version：
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
Using Helm to install istio: helm install install/kubernetes/helm/istio --name istio --namespace istio-system

**Environment**
Which environment, cloud vendor, OS, etc are you using?
Centos7 in VM, Kubernetes installed with Kubeadm，1 master 2 nodes

**Comment by vadimeisenbergibm** [comment]
At which point do you get ` Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: ` ?

**Comment by vadimeisenbergibm** [comment]
May be related to https://github.com/istio/istio/issues/7593.

**Comment by mingweiLIU** [comment]
The error occurs at kubectl apply -f gateway.yaml

**Comment by mingweiLIU** [comment]
If I try：curl https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s the result is：
curl: (35) Encountered end of file

**Comment by ayj** [comment]
@mingweiLIU, can you please follow the diagnostic steps at https://preliminary.istio.io/help/ops/setup/validation/#creating-configuration-fails-with-no-such-hosts-or-no-endpoints-available-errors to capture more information.

**Comment by mingweiLIU** [comment]
$  kubectl -n istio-system get pod -listio=galley
NAME                           READY     STATUS    RESTARTS   AGE
istio-galley-5669f7c9b-ngxm6   1/1       Running   0          7m

$ kubectl -n istio-system get endpoints istio-galley
NAME           ENDPOINTS                              AGE
istio-galley   192.168.2.122:9093,192.168.2.122:443   7m

$ kubectl get clusterrole istio-galley-istio-system -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: 2018-08-03T02:30:37Z
  labels:
    app: istio-galley
    chart: galley-1.0.0
    heritage: Tiller
    release: istio
  name: istio-galley-istio-system
  resourceVersion: "1708297"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/istio-galley-istio-system
  uid: 34b88918-96c5-11e8-adee-000c29b5782e
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resourceNames:
  - istio-galley
  resources:
  - deployments
  verbs:
  - get

**Comment by ayj** [comment]
Can you also capture the following:

- validatingwebhookconfiguration 

```
kubectl get validatingwebhookconfiguration istio-galley -o yaml
```

- istio-galley logs

````
for pod in $(kubectl -n istio-system get pod -listio=galley -o jsonpath='{.items[*].metadata.name}'); do \
    kubectl -n istio-system logs ${pod} \
done
````

- istio-galley metrics

```
kubectl proxy &
curl -s localhost:8001/api/v1/namespaces/istio-system/services/istio-galley:9093/proxy/metrics | grep ^galley
```

**Comment by soar-zhengjian** [comment]
same issue.

**Comment by ayj** [comment]
Your galley configuration looks correct. You apiserver can't reach the in-cluster webhook service/pod. Can you dump the kubeadm logs and look for an warnings/errors having to do with pod-cidr/service-cidr and proxies (see step #4 in [here](https://istio.io/help/ops/setup/webhook/))

**Comment by Viali** [comment]
I have exactly the same issue.
Any solution?
otherwise, I have to go back to Isito 0.8 :(

**Comment by mingweiLIU** [comment]
Well, if there is no possible solution, I will have a try with 0.8.

**Comment by ayj** [comment]
You can disable validation with Istio 1.0.0 using the `--set global.configValidation=false` helm option if your k8s provider doesn't support webhooks.

**Comment by mingweiLIU** [comment]
Wow, thanks, it works for me. Then what's the difference of disable validation or not?

**Comment by Viali** [comment]
@ayj Thanks... any suggestion if I used "kubeadm" to install K8S, and "kubectl apply" to install Istio ?

**Comment by Wayne-Liu** [comment]
I use "kubeadm" install K8S 1.12，and Helm install istio 1.0.2， @ayj use your method add `--set global.configValidation=false` ,my create works!
```
[root@node1 istio-1.0.2]# cat <<EOF | istioctl create -f -
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: httpbin-gateway
> spec:
>   selector:
>     istio: ingressgateway # use Istio default gateway implementation
>   servers:
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - "httpbin.example.com"
> EOF
Error: Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: EOF

[root@node1 istio-1.0.2]# cat <<EOF | istioctl create -f -
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: httpbin-gateway
> spec:
>   selector:
>     istio: ingressgateway # use Istio default gateway implementation
>   servers:
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - "httpbin.example.com"
> EOF
Created config gateway/default/httpbin-gateway at revision 1475192

```

**Comment by sfesfizh** [comment]
The same issue in 1.0.4.
istio-galley pod logs at the end make sense I think:
`2019-01-15T20:05:40.233777Z	warn	istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no ready addresses
2019-01-15T20:05:45.185312Z	info	istio-galley validatingwebhookconfiguration updated`

**Comment by Tushar120120** [comment]
if we do not use helm, is there any solution?

**Comment by simox-83** [comment]
Same issue here using Istio 1.1.7 and kubernetes cluster v. 1.13.5
```Error from server (InternalError): error when creating "bookinfo-gateway.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: Service Unavailable```

Using the flag to not validate the config makes it working, however we would like not to use it.
Any idea please?

**Comment by huo4444** [comment]
the cause : kube-api-server node  can not access  the pod network of kubelet node. I use flannel ,my kube-api-server node can not access flannel network  ,so k8s apiserver access service in k8s cluster is failed.

**Comment by simox-83** [comment]
> Same issue here using Istio 1.1.7 and kubernetes cluster v. 1.13.5
> `Error from server (InternalError): error when creating "bookinfo-gateway.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: Service Unavailable`
> 
> Using the flag to not validate the config makes it working, however we would like not to use it.
> Any idea please?

I found the problem and it's our proxy. Basically the calls to .istio-system.svc were passing through the proxy. Adding the domain to the no_proxy variable in the api server flags fixed the issue.
Hope this helps anybody who encounters a similar issue!

**Comment by pmint93** [comment]
I'm using Istio 1.1.12 and still experience this issue.

> the cause : kube-api-server node can not access the pod network of kubelet node. I use flannel ,my kube-api-server node can not access flannel network ,so k8s apiserver access service in k8s cluster is failed.

Is this really the cause ?
My kubernetes cluster was setup with masters & workers separately , which is you can not see master nodes by command `kubectl get nodes`

**Comment by howardjohn** [comment]
@pmint93 in your setup can the api server reach services in the cluster?

**Comment by pmint93** [comment]
> @pmint93 in your setup can the api server reach services in the cluster?

No. Now I see this could be my mistake to try running a k8s cluster with maters without kubelet, so network plugin (flannel) could not be installed on them. And when I create istio gateway, apiserver need to call services in the cluster which is failed to reach.

**Comment by howardjohn** [comment]
yeah I think that is the case, if you need to keep your set up you would have to turn off the validation and auto Injection

**Comment by pmint93** [comment]
Yeah, thank you.

**Comment by vhosakot** [comment]
Saw the same error when installing istio `1.3.6`:

```
Error: release istio failed: Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.107.180.45:443: connect: connection refused
```

Galley and pilot logs had the following errors: 

```
$ kubectl logs istio-galley-66f5bcd4f9-ds2w9 -n=istio-system
...
2019-12-16T22:21:39.963581Z	info	validation	https handler for validation webhook is not ready: HTTP request to https://localhost:443/ready failed: Get https://localhost:443/ready: dial tcp 127.0.0.1:443: connect: connection refused
2019-12-16T22:21:40.052199Z	warn	validation	istio-system/istio-galley endpoint not ready: no subsets
2019-12-16T22:21:40.600664Z	warn	validation	istio-system/istio-galley endpoint not ready: no ready addresses
...

$ kubectl logs istio-pilot-6c94f7f575-69wbf -n=istio-system --all-containers=true
...
2019-12-16T22:21:49.974537Z	info	grpc: addrConn.createTransport failed to connect to {istio-galley.istio-system.svc:9901 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.107.180.45:9901: connect: no route to host". Reconnecting...
2019-12-16T22:21:49.974779Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc00063f670, TRANSIENT_FAILURE
2019-12-16T22:21:49.974936Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.107.180.45:9901: connect: no route to host"
...
```

Using `--set global.configValidation=false` when installing istio resolved the error for me.

**Comment by shouldnotappearcalm** [comment]
I'm using Istio `1.5.0` and still experience this issue.I replaced `flannel` with `calico` to restart the cluster to solve this problem
