### ISSUE TITLE
Istio run in a separate server, all the services in k8s

### ISSUE THREAD

**Issue by SmileSees** [istio/istio#7584]
**Describe the solution you'd like**
Our team want a istio run in a separate server or cluster, and keep all the services still in k8s.

**Additional context**
Is that possible that we can achieve this? If we can do this, what are the matters need attention?

**Comment by vadimeisenbergibm** [comment]
cc @costinm @rshriram

**Comment by SmileSees** [comment]
I support it is not realistic, close this issue.
