### ISSUE TITLE
Not able to create bookinfo-gateway using EKS

### ISSUE THREAD

**Issue by prabhatpankaj** [istio/istio#7585]
Please help me out .
I am getting timeout error for EKS and ISTIO

kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within allowed duration

**Comment by chilcano** [comment]
Hi @prabhatpankaj  
What version of Istio are you using?.

I've installed Istio 0.8 on EKS successfully, before I had to replace `istioctl` binary for this new binary: https://github.com/istio/istio/issues/5327#issuecomment-397845262

After, I tried Istio 1.0 and worked, but manual sidecar injection didn't work, although The 1.0 release notes mention that EKS isn't supported (https://istio.io/about/notes/1.0/#istioctl) . I used the above shared binary `istioctl` and I got this error:
```sh
$ kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml) -n bookinfo
Error: failed to convert to proto. unknown field "sdsRefreshDelay" in v1alpha1.MeshConfig
error: no objects passed to apply
```
Regards.

**Comment by prabhatpankaj** [comment]
# cat istio.VERSION 
# DO NOT EDIT THIS FILE MANUALLY instead use
# install/updateVersion.sh (see install/README.md)
export CITADEL_HUB="gcr.io/istio-release"
export CITADEL_TAG="1.0.0"
export MIXER_HUB="gcr.io/istio-release"
export MIXER_TAG="1.0.0"
export PILOT_HUB="gcr.io/istio-release"
export PILOT_TAG="1.0.0"
export PROXY_HUB="gcr.io/istio-release"
export PROXY_TAG="1.0.0"
export PROXY_DEBUG=""
export ISTIO_NAMESPACE="istio-system"
export PILOT_DEBIAN_URL="https://storage.googleapis.com/istio-release-pipeline-data/prerelease/1.0.0/deb"
export FORTIO_HUB="docker.io/istio"
export FORTIO_TAG="latest_release"
export HYPERKUBE_HUB="quay.io/coreos/hyperkube"
export HYPERKUBE_TAG="v1.7.6_coreos.0"

**Comment by prabhatpankaj** [comment]
it seems both have problem ..

istio-ingressgateway-b55bc6bbb-wglz5        0/1       CrashLoopBackOff   4          23m

servicegraph-7875b75b4f-g4l5c               0/1       CrashLoopBackOff   4          1m

**Comment by prabhatpankaj** [comment]
@chilcano can you please share the working steps ?

As istio documents are very confusing . 

need to know which methods are working for 1.0 version...

Thanks

**Comment by prabhatpankaj** [comment]
Hi finally i am able to use it inside EKS .

Instruction - I have updated it in 
https://github.com/prabhatpankaj/eks-terraform-istio/blob/master/README.md

Hope it will help others ..

**Comment by chilcano** [comment]
I've updated the guide to use `Istio 1.0` and `BookInfo` Application with manual sidecar injection.
https://github.com/chilcano/service-mesh-workshop/blob/master/labs/00-k8s/eks/README.md

Regards.

**Comment by nrshrivatsan** [comment]
@prabhatpankaj given [comment](https://github.com/istio/istio/issues/7585#issuecomment-410741495) from @chilcano, could we close this issue?

**Comment by prabhatpankaj** [comment]
yaa .. please close it ....

**Comment by nrshrivatsan** [comment]
@prabhatpankaj  ops, not a part of maintainers yet. Can't close the issue...
