### ISSUE TITLE
make proxy-config use an annotation to mark the containers with Envoy

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7588]
Add this annotation to gateway templates and to the injected sidecar proxy.

Based on the discussion in https://github.com/istio/istio/pull/7566#issuecomment-409677251

**Comment by itaysk** [comment]
AFAICT annotatations are pod level, not container level. given that, how will pod level annotaion help proxy-config find the proxy containers in pods? maybe I'm missing something about this issue?

**Comment by liamawhite** [comment]
@itaysk you are correct, this conversation was a while ago so I cannot remember the reasoning or context behind it. It should be possible to add an annotation to the pod that gives the name of the proxy-container though.

I think this issue has actually been solved by making sure all `istio-proxy` containers are named `istio-proxy`. So I will close it and reopen if we do see any related ones.
