### ISSUE TITLE
Kiali ImagePullBackOff 

### ISSUE THREAD

**Issue by kamilgregorczyk** [istio/istio#7589]
Kiali image is not available for pull

**Steps to reproduce**
```
helm upgrade istio install/kubernetes/helm/istio  --set gateways.istio-ingressgateway.type=NodePort --set gateways.istio-egressgateway.type=NodePort --set grafana.enabled=true --set kiali.enabled=true --set servicegraph.enabled=true
```

```
➜  istio-1.0.0 kubectl describe pod kiali-644f5dd546-cpf47 -n istio-system
Name:           kiali-644f5dd546-cpf47
Namespace:      istio-system
Node:           minikube/10.0.2.15
Start Time:     Thu, 02 Aug 2018 11:01:57 +0200
Labels:         app=kiali
                pod-template-hash=2009188102
Annotations:    scheduler.alpha.kubernetes.io/critical-pod=
                sidecar.istio.io/inject=false
Status:         Pending
IP:             172.17.0.27
Controlled By:  ReplicaSet/kiali-644f5dd546
Containers:
  kiali:
    Container ID:
    Image:         docker.io/kiali/kiali:istio-release-1.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/kiali/kiali
      -config
      /kiali-configuration/config.yaml
      -v
      4
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:  10m
    Environment:
      ACTIVE_NAMESPACE:             istio-system (v1:metadata.namespace)
      SERVER_CREDENTIALS_USERNAME:  <set to the key 'username' in secret 'kiali'>    Optional: false
      SERVER_CREDENTIALS_PASSWORD:  <set to the key 'passphrase' in secret 'kiali'>  Optional: false
      PROMETHEUS_SERVICE_URL:       http://prometheus:9090
      GRAFANA_DASHBOARD:            istio-service-dashboard
      GRAFANA_VAR_SERVICE_SOURCE:   var-service
      GRAFANA_VAR_SERVICE_DEST:     var-service
    Mounts:
      /kiali-configuration from kiali-configuration (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kiali-service-account-token-r4l59 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  kiali-configuration:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kiali
    Optional:  false
  kiali-service-account-token-r4l59:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali-service-account-token-r4l59
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   Scheduled              15m                 default-scheduler  Successfully assigned kiali-644f5dd546-cpf47 to minikube
  Normal   SuccessfulMountVolume  15m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "kiali-configuration"
  Normal   SuccessfulMountVolume  15m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "kiali-service-account-token-r4l59"
  Normal   Pulling                14m (x4 over 15m)   kubelet, minikube  pulling image "docker.io/kiali/kiali:istio-release-1.0"
  Warning  Failed                 14m (x4 over 15m)   kubelet, minikube  Failed to pull image "docker.io/kiali/kiali:istio-release-1.0": rpc error: code = Unknown desc = Error response from daemon: manifest for kiali/kiali:istio-release-1.0 not found
  Warning  Failed                 14m (x4 over 15m)   kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                5m (x41 over 15m)   kubelet, minikube  Back-off pulling image "docker.io/kiali/kiali:istio-release-1.0"
  Warning  Failed                 37s (x62 over 15m)  kubelet, minikube  Error: ImagePullBackOff
```

**Comment by theute** [comment]
With the changes between Istio 0.8 and 1.0, Kiali isn't yet "ready" for 1.0 (It works well for 0.8).
The progress in the branch for Istio 1.0 are well under way: https://github.com/kiali/kiali/tree/istio-1.0 It is working "to some extend".

Rather than delaying Istio 1.0, the decision was made to go ahead without the image of Kiali being available, we're expecting the image to be available within 2 or 3 weeks...

So this error is unfortunate, but this is expected at this time.

If someone is willing to help getting this expedited, don't hesitate to join us: https://groups.google.com/forum/#!forum/kiali-dev :)

**Comment by gbaufake** [comment]
@kamilgregorczyk 
We have a new kiali which is Istio 1.0 compatible (kiali v0.6.0). Also, there is a new kiali version coming up on #8909.

Best regards, 
Guilherme Baufaker Rêgo

**Comment by barrieumaru** [comment]
**Can someone help: If i run the following command i got the result**

=> kubectl describe pods -n istio-system kiali-7ff568c949-4vxcm

Name:           kiali-7ff568c949-4vxcm
Namespace:      istio-system
Priority:       0
Node:           k8s-agentpool1-39702042-2/10.240.0.4
Start Time:     Tue, 19 May 2020 10:06:05 +0000
Labels:         app=kiali
                pod-template-hash=7ff568c949
                release=istio
Annotations:    kiali.io/runtimes: go,kiali
                kubernetes.io/psp: privileged
                prometheus.io/port: 9090
                prometheus.io/scrape: true
                scheduler.alpha.kubernetes.io/critical-pod:
                sidecar.istio.io/inject: false
Status:         Pending
IP:             10.240.0.21
Controlled By:  ReplicaSet/kiali-7ff568c949
Containers:
  kiali:
    Container ID:
    Image:         quay.io/kiali/kiali:v1.15
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/kiali/kiali
      -config
      /kiali-configuration/config.yaml
      -v
      3
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
    Liveness:   http-get http://:20001/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:20001/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Environment:
      ACTIVE_NAMESPACE:  istio-system (v1:metadata.namespace)
    Mounts:
      /kiali-cert from kiali-cert (rw)
      /kiali-configuration from kiali-configuration (rw)
      /kiali-secret from kiali-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kiali-service-account-token-hxrgh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kiali-configuration:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kiali
    Optional:  false
  kiali-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.kiali-service-account
    Optional:    true
  kiali-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali
    Optional:    true
  kiali-service-account-token-hxrgh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali-service-account-token-hxrgh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
