### ISSUE TITLE
failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot: service "istio-galley" not found

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7593]
https://k8s-gubernator.appspot.com/build/istio-prow/istio-pilot-e2e-envoyv2-v1alpha3/4840/

**Comment by ayj** [comment]
This looks like a test specific issue where the previous test run's resources (including validation) were not finished cleaning up before the next test ran. Deleting the namespace triggers a cascading delete, but the test doesn't wait for all child resources to be cleaned up before proceeding with the next test.

**Comment by lichuqiang** [comment]
@ayj Not sure if I get your meaning.
Took a look at the error info
```
config.go:459: Post(VirtualService) => got Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot: service "istio-galley" not found
config.go:459: Post(DestinationRule) => got Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot: service "istio-galley" not found
config.go:459: Post(Gateway) => got Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot: service "istio-galley" not found
```

Seems something is wrong with the galley service. I think for e2e tests, galley (validatrr) is expected to keep running as a dependency, and should not be affected by the test resources cleanup stuff.
Have I missed someting?

**Comment by ayj** [comment]
The galley service shouldn't be running for `go test -v -timeout 25m ./tests/e2e/tests/controller`. These particular unit tests check internal pilot packages directly. The fact that we see this error means the galley`validatingwebhookconfiguration` wasn't cleaned up from the previous test (see below)

> I0802 05:16:29.127] set -o pipefail; go test -v -timeout 25m ./tests/e2e/tests/pilot 

`validatingwebhookconfiguration` _should_ be cleaned up by deletion of its owner reference (istio-galley deployment). In the logs the `istio-system` namespace is deleted first which triggers deletion of the deployments in that namespace. By the time the test tries to delete the galley deployment, k8s has already deleted it first and, in theory, the webhook configuration that references it. The fact that it still exists suggests a timing issue (k8s hasn't GC the webhook config yet) or bug.

> I0802 05:33:33.223] namespace "istio-system" deleted
> ...
> I0802 05:33:33.235] Error from server (NotFound): error when stopping "/home/bootstrap/go/src/istio.io/istio/_artifacts/pilot-test-aa6f511f25f14d44bee61d8267/yaml/istio.yaml": deployments.extensions "istio-galley" not found
