### ISSUE TITLE
Reconfiguring a deployment creates a new workload

### ISSUE THREAD

**Issue by jotak** [istio/istio#7597]
**Describe the bug**

When I try to reconfigure a deployment that has previously been injected using istioctl (for instance I change its labels), there is a new Workload that is created and that I can see in Kiali or Grafana. And I can see that my previous deployment was not actually _replaced_ with a new one, its pods are still running. A new _Replica Set_ is created instead and runs concurrently with the old config.

**Expected behavior**
I suppose a Deployment reconfiguration should erase the previous one, and I expect the new workload to keep the same name based on Deployment name.

**Steps to reproduce the bug**

- `oc apply -f <(istioctl kube-inject -f ./depl.yml` (any standard deployment yaml, for example one from the bookinfo demo)
- edit the "app" or "version" labels in that yaml, putting anything different. But keep the same deployment name.
- `oc apply -f <(istioctl kube-inject -f ./depl.yml`

output: `deployment "test-deployment" configured`

**Version**
```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
Disabled (I installed istio-demo.yaml from the tgz archive)

**Environment**
OpenShift 3.9. I guess the same would happen on plain Kubernetes?

```
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```

**Comment by jotak** [comment]
Note: if I modify something else than the labels - for instance, I change an environment variable that is passed to the container - then it works as expected. A new version of the deployment is created, and new pods substitute to the old ones.

**Comment by jmazzitelli** [comment]
It seems odd that Istio is storing the replica set name as workload name in the telemetry sometimes, but not all the time (the initial deployment with the initial replica set resulted in the deployment name being the workload name in the telemetry).

It seems to me like this is potentially a bug - why does the telemetry use deployment name first, and then replica set after the re-deployment? Seems inconsistent to me (and it makes it harder for clients of the telemetry to know how to interpret the data).

IMO, if Istio telemetry uses replica set name for workload name sometimes, it should use it all the time.

**Comment by vadimeisenbergibm** [comment]
> I can see that my previous deployment was not actually replaced with a new one, its pods are still running. 

So is the issue related to Kubernetes "the pods of the previous deployment are still running" ?

**Comment by jmazzitelli** [comment]
@jotak might be useful to add a comment here with the actual Prometheus metrics that you see.

**Comment by jotak** [comment]
@vadimeisenbergibm well it depends how you consider it, to me that's just one part of the problem ; the other part being that the reconfiguration does not result in the update of the deployment as I would expect; instead, the new Replica Set that is created is not tied to the Deployment. And, I guess as a result, the Workload than I can see in metrics is named after the replica set, not after the deployment:

```
istio_requests_total{connection_security_policy="unknown",destination_app="ui",destination_principal="unknown",destination_service="ui.mesh-arena.svc.cluster.local",destination_service_name="ui",destination_service_namespace="mesh-arena",destination_version="v1",destination_workload="ui",destination_workload_namespace="mesh-arena",instance="172.17.0.14:42422",job="istio-mesh",reporter="source",request_protocol="http",response_code="200",source_app="unknown",source_principal="unknown",source_version="unknown",source_workload="test-deployment-b8d656c67",source_workload_namespace="mesh-arena"}
```

Note how "Source workload" is "test-deployment-b8d656c67" instead of just "test-deployment".

Also if you look at the output of the replica sets:
- The initial replica-set, tied to the Deployment:

```
$ oc describe replicaset test-deployment-5854b77d8b
Name:           test-deployment-5854b77d8b
Namespace:      mesh-arena
Selector:       pod-template-hash=1410633846,version=test,zapp=stadium
Labels:         pod-template-hash=1410633846
                version=test
                zapp=stadium
Annotations:    deployment.kubernetes.io/desired-replicas=1
                deployment.kubernetes.io/max-replicas=2
                deployment.kubernetes.io/revision=2
Controlled By:  Deployment/test-deployment
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
(etc.)
```

- The reconfigured replica-set:
```
$ oc describe replicaset test-deployment-b8d656c67
Name:         test-deployment-b8d656c67
Namespace:    mesh-arena
Selector:     pod-template-hash=648212723,version=test2,zapp=stadium
Labels:       pod-template-hash=648212723
              version=test2
              zapp=stadium
Annotations:  deployment.kubernetes.io/desired-replicas=1
              deployment.kubernetes.io/max-replicas=2
              deployment.kubernetes.io/revision=1
Replicas:     1 current / 1 desired
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
(etc.)
```

Note how `Controlled By:  Deployment/test-deployment` is missing in the second one. I guess all these odd things are all related.

**Comment by vadimeisenbergibm** [comment]
@jotak Still, for me it seems like Kubernetes/OpenShift issue - "the pods of the old deployment are still running", "the new Replica Set that is created is not tied to the Deployment", it is not related to Istio. I would fix that issue first, and then check the metrics.

**Comment by jotak** [comment]
Digging a little in istio code, I eached these lines of code:
https://github.com/istio/istio/blob/405f47f54d19e6d998aa3e863ec9e2bc23c157f1/mixer/adapter/kubernetesenv/cache.go#L180-L214

So indeed, it seems not related to Istio (or maybe, not _only_), as Istio only takes the root owner of pods as the Workload name.
However there's still something odd. If I update my yaml file without passing through istioctl, like this: (after changing the labels, again) 

```
$ oc apply -f ./services/stadium/Deployment-Bigger-bis.yml
```

Then the old deployment is not *updated* but *removed* and replaced by a new one with the same name (I say not updated because the deployment's version counter is not increased but reset to 1)

So it seems that's there's something special going with k8s/openshift when labels are modified, and for some reason Istio is affected because it cannot find (maybe just for a moment?) the deployment reference in order to set the workload name, and stops at the replica set level.

That's probably something that is tricky to solve.

**Comment by vadimeisenbergibm** [comment]
cc @christian-posta

**Comment by abonas** [comment]
@knrc any idea?
