### ISSUE TITLE
global.hub --set option not updating all image: paths

### ISSUE THREAD

**Issue by davidmgrantham** [istio/istio#7599]
@christian-posta 

**Describe the bug**
When setting --set global.hub only some of the image: paths are updated.

This image didn't change the path "docker.io/prom/statsd-exporter:v0.6.0"

but this one did

<accountid>.dkr.ecr.us-east-1.amazonaws.com/platform/istio/components/proxy_init:1.0.0

**Expected behavior**
All image: container paths should be updated 

**Steps to reproduce the bug**
Use global.hub to produce a template from helm

**Version**

istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**
EKS (AWS)

**Comment by ymesika** [comment]
It's actually not a problem because `docker.io/prom/statsd-exporter:v0.6.0` is not an Istio image.

**Comment by christian-posta** [comment]
We still need a way to control the base hub for any image in the helm charts. I'd expect operators to what to curate an installation using known/trusted registries for their images and tuning that via helm properties seems reasonable.

**Comment by davidmgrantham** [comment]
Doing a "true global" or being able to managed each registry would be a nice to have. Currently we are putting all containers shown in the helm generated yaml into Amazon ECR. We tested yesterday just using global.hub and was successful but ultimately we are going to need to manually update the yaml after its generated to include those paths.
