### ISSUE TITLE
Warnings in all sidecar for "TLS Inspector listener filter"

### ISSUE THREAD

**Issue by Stono** [istio/istio#7601]
Hey, 
I'm seeing this in all my side car logs:

```
[2018-08-02 17:56:29.368][26][warning][config] external/envoy/source/server/listener_manager_impl.cc:257] adding listener '0.0.0.0:443': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
```

I know it's only a warning, but theres one of these for each VirtualService+DestinationService for tls SNI outside the mesh.  So it's a bit spammy.

Everything *appears* to be working OK...

**Comment by PiotrSikora** [comment]
This warning is harmless (but indeed spammy).

But if you're seeing them, then it means that Pilot isn't adding `listener_filters` with `tls_inspector` to the VirtualService+DestinationService, so that should be fixed to silence the warnings.

**Comment by Stono** [comment]
Just to be clear @PiotrSikora when you say "should be fixed", are we implying an istio code fix here or something about my VS+DS being misconfigured?

**Comment by PiotrSikora** [comment]
Sorry, I mean Pilot's code.

**Comment by Stono** [comment]
Thanks, just checking it wasn't user error :D

**Comment by PiotrSikora** [comment]
cc @rshriram

**Comment by vadimeisenbergibm** [comment]
@PiotrSikora @ijsnellf Correcting myself, configuring `tls_inspector`explicitly  is not required for SNI reporting, my mistake in https://github.com/istio/istio/issues/7601#issuecomment-410527139 .

**Comment by ijsnellf** [comment]
Sounds like the impact is just confusing warnings. I'll fix it.

**Comment by PiotrSikora** [comment]
Yup, it's just a harmless warning (which is needed, in case someone builds Envoy without `tls_inspector` filter, which we try to auto-inject, and Envoy crashes).
