### ISSUE TITLE
Verify the latest Istio runs on minikube

### ISSUE THREAD

**Issue by joysarkarhub** [istio/istio#7602]
**Describe the bug**
reviews-v1, reviews-v2 and reviews-v3 are in ImagePullBackOff state with error:
 Warning  Failed                 6m                kubelet, minikube  Failed to pull image "istio/examples-bookinfo-reviews-v1:1.8.0": rpc error: code = Unknown desc = failed to register layer: Error processing tar file(exit status 1): operation not supported

**Expected behavior**
Bookinfo app should start
**Steps to reproduce the bug**
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)
Steps to reproduce the behavior.
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)
**Version**
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
yes
kubectl apply -f install/kubernetes/istio-demo.yaml

**Environment**
minikube version: v0.28.2
Istio Version: 1.0.0

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.

**Comment by vadimeisenbergibm** [comment]
Related to the user's question https://groups.google.com/forum/#!topic/istio-users/d7bnv7tpiHs

**Comment by vadimeisenbergibm** [comment]
cc @rshriram @ZackButcher @costinm
