### ISSUE TITLE
sidecarInjectorWebhook.enabled=false no longer generates sidecar injector configmap

### ISSUE THREAD

**Issue by joewilliams** [istio/istio#7604]
**Describe the bug**
Looks like as of istio 1.0 using helm to generate the istio config with `sidecarInjectorWebhook.enabled=false` no longer includes the sidecar injector configmap. This was not the case in 0.8.0. Looks like it happened as a part of https://github.com/istio/istio/pull/7408/files#diff-de5983fcb0f040db64cf0281f3b152c0R1

**Expected behavior**
`sidecarInjectorWebhook.enabled=false` should still generate the configmap so that it's possible to do something like the following to get the appropriate configs to inject manually:

```
$ kubectl -n istio-system get configmap istio-sidecar-injector -o=jsonpath='{.data.config}' > inject-config.yaml
$ kubectl -n istio-system get configmap istio -o=jsonpath='{.data.mesh}' > mesh-config.yaml
```
From https://istio.io/docs/setup/kubernetes/sidecar-injection/#manual-sidecar-injection

**Steps to reproduce the bug**
```
 ~/istio-0.8.0 $ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set sidecarInjectorWebhook.enabled=false > ./istio.yaml
 ~/istio-0.8.0 $ grep istio-sidecar-injector istio.yaml
  name: istio-sidecar-injector
```

vs

```
~/istio-1.0.0 $ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set sidecarInjectorWebhook.enabled=false > ./istio.yaml
 ~/istio-1.0.0 $ grep istio-sidecar-injector istio.yaml
```
**Version**
istio 0.8.0 and/or 1.0.0
kube 1.10.2

**Is Istio Auth enabled or not?**
yes

**Environment**
bare metal, debian jessie

**Cluster state**
n/a

**Comment by joewilliams** [comment]
I am happy to submit a PR to fix this but would appreciate a 👍 before I do.

**Comment by ymesika** [comment]
Duplication of #7567

**Comment by joewilliams** [comment]
Thanks!
