### ISSUE TITLE
Helm install with only pilot enabled doesn't work

### ISSUE THREAD

**Issue by linsun** [istio/istio#7615]
**Describe the bug**
tried to start only the pilot, but failed

**Expected behavior**
expect user can only install network portion of istio.

**Steps to reproduce the bug**
```
~/Downloads/istio-1.0.0 :watch: 17:12:59
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set security.enabled=false \
  --set ingress.enabled=false \
  --set gateways.istio-ingressgateway.enabled=false \
  --set gateways.istio-egressgateway.enabled=false \
  --set galley.enabled=false \
  --set sidecarInjectorWebhook.enabled=false \
  --set mixer.enabled=false \
  --set prometheus.enabled=false \
  --set global.proxy.envoyStatsd.enabled=false \
  --set pilot.sidecar=false
``` 
(edited)

```$ kubectl get pods -n istio-system                        
NAME                          READY     STATUS              RESTARTS   AGE
istio-pilot-c7469fb87-vfx7m   0/1       ContainerCreating   0          19h
```
**Version**
1.0.0

**Is Istio Auth enabled or not?**
no

**Environment**
k8s 1.9.9

Could use a little help troubleshoot this since there is no log for pilot pod.  cc @costinm @rshriram @ymesika 

Enable network and security does work.  FYI.

**Comment by linsun** [comment]
@ymesika thank you - that was it, got pilot up running now.   I'll submit a PR for this soon.

**Comment by ymesika** [comment]
@linsun another option is to add to the secret an `optional: true` instead of having if condition to remove the volume mount.

**Comment by linsun** [comment]
This is working now, and minimal profile is published

**Comment by ghostsquad** [comment]
I just came across this using istioctl 1.4.0 and the `--profile minimum`, and `pilot` doesn't want to come up. 

from discovery container

```
2019-11-17T21:33:37.222333Z     info    mcp     (re)trying to establish new MCP sink stream
2019-11-17T21:33:37.222487Z     error   mcp     Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:15019: connect: connection refused"
```

from istio-proxy container

```
2019-11-17T21:34:09.063949Z     info    waiting for file
```

Has this not actually be published to the minimal profile?

What's the fix?
