### ISSUE TITLE
Grafana dashboard for service availability is confusing

### ISSUE THREAD

**Issue by linsun** [istio/istio#7616]
**Describe the bug**
Grafana dashboard for service availability is confusing.  The dashboard is configured to show last 5 mins, however the service success rate is shown only for last 1 min.  Plus the success rate is only calculated when there is traffic.   The app could be running perfectly fine but the dashboard will report success rate 0 when there is no live traffic visiting the app in the past 1 min.

**Expected behavior**
I would expect the time frame matches what user has on grafana or at least increase it for a longer time window.  Further, the success rate based on live traffic is somewhat limited.

**Steps to reproduce the bug**
Follow the telemtry task:  https://istio.io/docs/tasks/telemetry/using-istio-dashboard/

**Version**
istio 1.0.0
k8s 1.9.9

**Is Istio Auth enabled or not?**
no

![image](https://user-images.githubusercontent.com/1588319/43620825-8a700a00-96a2-11e8-95d2-f7d180536861.png)

**Comment by douglas-reid** [comment]
A few thoughts:

What do we expect the success rate to be for situations in which there is no traffic?  `NaN` seems almost appropriate to me. `100%` doesn't seem correct, to me. Note also, it isn't just success rate that can't be calculated when there is no traffic. We also cannot calculate latencies.

Using the grafana time window, if we could do that, is tricky too. In your example, it is "Last 5 minutes", but it could also be values like "This day last week". This gets hard to translate into a simple promQL query.

The refresh rate is `5s` in your example. It could be also argued that we should calculate graph windows over the refresh rate window (which I know we can get from grafana). I'm also not convinced that is ideal either.

The table widget is not set up to show historical values (unlike charts). For now, what is displayed is the *current* rate. `rate(...[1m])` seems like a decently happy medium for calculating the current rate. I've seen other dashboards use `30s`. I don't have strong feelings around the appropriate window. But I worry that extending it to something like `24h` in circumstances could potentially be very misleading.

**Comment by linsun** [comment]
@douglas-reid I understand some of your concerns.  To improve the usability, perhaps we could differ not a number (NaN) from 0% success rate (all red) for the user?  All i see is 0% and all red before i can read NaN in detail.
