### ISSUE TITLE
bookinfo-gateway cannot create

### ISSUE THREAD

**Issue by xylucky** [istio/istio#7622]
root@han-ThinkPad-T480s:/home/soft/istio-1.0.0# kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"

**Comment by ijsnellf** [comment]
Looks like you need make sure Istio was installed successfully. Please see https://istio.io/docs/setup/kubernetes/ and make sure you are able to install without any issues.

**Comment by vadimeisenbergibm** [comment]
After you install istio correctly, you may run `kubectl get crd` and check that the following resources appear, among others:
```
gateways.networking.istio.io
virtualservices.networking.istio.io
```

**Comment by Ghost---Shadow** [comment]
bump

**Comment by Vineet-Sharma29** [comment]
SImilar error on `GKE`. When I try to run `kubectl apply -f ./samples/bookinfo/networking/bookinfo-gateway.yaml`, I get following error:-
```
unable to recognize "./samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "./samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```

**Comment by Vineet-Sharma29** [comment]
> After you install istio correctly, you may run `kubectl get crd` and check that the following resources appear, among others:
> 
> ```
> gateways.networking.istio.io
> virtualservices.networking.istio.io
> ```

@vadimeisenbergibm Can you tell through which commands should we use to install `gateways.networking.istio.io1` and `virtualservices.networking.istio.io`?

**Comment by Vineet-Sharma29** [comment]
For me `kubectl create -f samples/bookinfo/networking/bookinfo-gateway.yaml` worked

**Comment by omeryounus** [comment]
unable to recognize "https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"

**Comment by omeryounus** [comment]
Also this one does the same...

ubuntu@ip-172-26-12-49:~/istio-1.7.0$ kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
