### ISSUE TITLE
Servicegraph ingress backend service name not match Service metadata name

### ISSUE THREAD

**Issue by xiaxianzhi** [istio/istio#7624]
**Describe the bug**
In `install/kubernetes/helm/istio/charts/servicegraph/templates/ingress.yaml`, the ingress backend service name is `servicegraph.fullname` which will renderred as `istio-servicegraph`, but in `install/kubernetes/helm/istio/charts/servicegraph/templates/service.yaml`, the service name is exactly `servicegraph`. It will result to no backend service will be matched for this ingress.
 
**Expected behavior**
Fix the ingress service name.
**Steps to reproduce the bug**
Steps to reproduce the behavior.
helm upgrade istio install/kubernetes/helm/istio --install --namespace istio-system  --set servicegraph.enabled=true --set servicegraph.ingress.enabled=true
**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
Istio version: 1.0.0
Kubernetes version : v1.10.0
**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

**Environment**
Which environment, cloud vendor, OS, etc are you using?

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.

**Comment by linsun** [comment]
We have chose to favor kiali over service graph.

@jmazzitelli I don't think Kiali 's helm subchart has this prob, could you check?
