### ISSUE TITLE
Bookinfo example - Applying virtualServices leading to unreachable services

### ISSUE THREAD

**Issue by KevinKlinger** [istio/istio#7627]
**Describe the bug**
I setup the bookinfo example as described in the docs - which works fine by default.
But when I try to apply the `samples/bookinfo/networking/virtual-service-all-v1.yaml` and refresh the product page, I get errors returned as:

"Error fetching product details!", "Sorry, product details are currently unavailable for this book.",
"Error fetching product reviews!", "Sorry, product reviews are currently unavailable for this book."

(You can also see it in the picture I attached)
![product page error](https://user-images.githubusercontent.com/26734854/43643112-769ece2a-972a-11e8-93cb-5541040dc521.jpeg)

As soon as I delete the config by using `kubectl delete -f samples/bookinfo/networking/virtual-service-all-v1.yaml` it works again using all 3 versions of the ratings.

Are there any logs may giving more information about this? I tried getting the logs for the product-page pod and the istio-pilot pod but none of them showed any error.

**Expected behavior**
The behavior i expected was the product page to return results but only from v1 of the rating services.

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
**Istio:**
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Kubernetes:**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**
I am running istio + minikube on Windows 10

**Comment by GregHanson** [comment]
Did you create the corresponding DestinationRules?
```
kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml
```
The VirtualService rules reference a specific destination subset for each service
```
    - destination:
        host: details
        subset: v1
```
Since a subset name is specified - there must be a corresponding DestinationRule for `details` with a matching subset defined
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
spec:
  host: details
  subsets:
  - name: v1
    labels:
      version: v1
```

**Comment by ijsnellf** [comment]
These configs were separated recently, so the docs might be missing instructions to apply both. Can you link to the segment of the docs you followed?

**Comment by SirNexus** [comment]
I encountered the same error. Followed these docs: https://istio.io/docs/tasks/traffic-management/request-routing/. Says to be familiar with destination rules, but doesn't say to apply the yaml file @GregHanson suggested. Bookinfo works when I apply the destination rules.

**Comment by KevinKlinger** [comment]
Okay, after applying [samples/bookinfo/networking/destination-rule-all.yaml)](https://raw.githubusercontent.com/istio/istio/release-1.0/samples/bookinfo/networking/destination-rule-all.yaml) it perfectly works.
Thanks for the help :)
