### ISSUE TITLE
Mixer grpc adapters: Add TLS + MTLS support

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7637]
Mixer should support calling grpc adapters over a TLS connection with basic authentication.

**Comment by bianpengyuan** [comment]
For Adapters running in the mesh, mixer and adapters could communicate with mtls using certs distributed by citadel like pilot and proxy. We could provide some examples or a library to facilitate adapter development.

For Adapters running outside the mesh, where mtls is hard, user could simply use basic auth: create a secret with a password and mount it in mixer deployment, mixer sends the password as per rpc credential and adapter verifies the password with grpc interceptor. Alternatively for better security user could deploy mixer with jwt signing key to use jwt auth or tls cert trusted by adapter to use mtls.

**Comment by douglas-reid** [comment]
Can we close this issue now?

**Comment by bianpengyuan** [comment]
Yes.
