### ISSUE TITLE
cannot access book info example 

### ISSUE THREAD

**Issue by shavo007** [istio/istio#7640]
**Describe the bug**
I followed the steps to install istio and the book info example. i got down as far as accessing the service https://istio.io/docs/examples/bookinfo/#confirm-the-app-is-running.

```
$ kubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                     AGE
istio-ingressgateway   LoadBalancer   10.107.177.68   localhost     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31531/TCP,8060:30656/TCP,15030:32388/TCP,15031:31829/TCP   52m
```

I am running docker for mac with kubernetes and have a feeling that this is the issue. 

**Expected behavior**
 I expected to access the service on the nodeport and host localhost

**Steps to reproduce the bug**
Install istio on docker for mac with kubernetes locally and install the book info example.

**Version**
```

$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
I installed without mutual TLS
`kubectl apply -f install/kubernetes/istio-demo.yaml`

**Environment**
Docker for mac version 18.06.0-ce-mac69

Services
```

$ kubectl get services
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   10.104.19.162    <none>        9080/TCP   1h
kubernetes    ClusterIP   10.96.0.1        <none>        443/TCP    28d
productpage   ClusterIP   10.99.191.13     <none>        9080/TCP   1h
ratings       ClusterIP   10.101.138.190   <none>        9080/TCP   1h
reviews       ClusterIP   10.103.132.194   <none>        9080/TCP   1h
sleep         ClusterIP   10.97.58.54      <none>        80/TCP     1h
```

pods

```
$ kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
details-v1-6865b9b99d-nhw2q    2/2       Running   0          1h
productpage-v1-f8c8fb8-6d6rs   2/2       Running   0          1h
ratings-v1-77f657f55d-xb9nf    2/2       Running   0          1h
reviews-v1-6b7f6db5c5-7fklj    2/2       Running   0          1h
reviews-v2-7ff5966b99-jlm67    2/2       Running   0          1h
reviews-v3-5df889bcff-v4t7m    2/2       Running   0          1h
sleep-86f6b99f94-xwr7b         2/2       Running   0          1h
```

**Comment by shavo007** [comment]
I have no problems when running nginx for example
```
 kubectl run nginx  --image=nginx
kubectl expose deployment nginx --type=LoadBalancer --port=80
curl http://localhost:30230/

```

**Comment by vadimeisenbergibm** [comment]
You may want to try this task first https://istio.io/docs/tasks/traffic-management/ingress/.

Regarding bookinfo, remember to apply `samples/bookinfo/networking/bookinfo-gateway.yaml`.

**Comment by yfxu1990** [comment]
@shavo007  Hi,  Have you solved it now？

**Comment by shavo007** [comment]
havent got around to trying it again yet.  will let you know when i do. i tested at the weekend on azure aks and had no problem. so well see..

**Comment by yfxu1990** [comment]
@shavo007 
I think the problem should be the sidcar or the virtual-service-all-v1.yaml or the bookinfo-gateway.yaml.

Today I redeployed istio1.0 and accessing  bookinfo-service normal using nodeport.

But I don't know why.

**Comment by supereagle** [comment]
@shavo007  Meet the same problem. Have you test this on your Mac again?

**Comment by supereagle** [comment]
> Today I redeployed istio1.0 and accessing bookinfo-service normal using nodeport.

Have you found the reason?

**Comment by hvn4179** [comment]
I have the same problem on my mac laptop. Any suggestion?

**Comment by supereagle** [comment]
Check whether `istio-ingressgateway` pod has opened these ports.

```
kubectl -n istio-system exec -it istio-ingressgateway-67995c486c-zq5kh -- netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      19/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      19/envoy
tcp        0      0 10.1.0.131:33478        10.1.0.118:9091         TIME_WAIT   -
tcp        0      0 10.1.0.131:58104        10.111.10.198:9411      ESTABLISHED 19/envoy
tcp        0      0 10.1.0.131:80           192.168.65.3:41098      ESTABLISHED 19/envoy
tcp        0      0 10.1.0.131:43744        10.1.0.120:9080         ESTABLISHED 19/envoy
tcp        0      0 10.1.0.131:56830        10.1.0.110:9091         TIME_WAIT   -
tcp        0      0 10.1.0.131:54240        10.97.184.67:15010      ESTABLISHED 19/envoy
udp        0      0 10.1.0.131:50554        10.108.66.205:9125      ESTABLISHED 19/envoy
udp        0      0 10.1.0.131:35326        10.108.66.205:9125      ESTABLISHED 19/envoy
udp        0      0 10.1.0.131:54043        10.108.66.205:9125      ESTABLISHED 19/envoy
udp        0      0 10.1.0.131:49983        10.108.66.205:9125      ESTABLISHED 19/envoy
udp        0      0 10.1.0.131:50198        10.108.66.205:9125      ESTABLISHED 19/envoy
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ]         DGRAM                    7623383  19/envoy            @envoy_domain_socket_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by hvn4179** [comment]
@supereagle What can you tell me about my deployment?
$ kubectl get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                                                                                   AGE
istio-ingressgateway   LoadBalancer   10.98.92.73   <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32074/TCP,8060:30945/TCP,853:31976/TCP,15030:30911/TCP,15031:31166/TCP   11m
$ kubectl get pods -n istio-system
NAME                                        READY     STATUS      RESTARTS   AGE
grafana-6cbdcfb45-5xdbx                     1/1       Running     0          21h
istio-citadel-6b6fdfdd6f-h7tsp              1/1       Running     0          21h
istio-cleanup-secrets-fk5hj                 0/1       Completed   0          21h
istio-egressgateway-56bdd5fcfb-r24dp        1/1       Running     0          21h
istio-galley-96464ff6-czn2q                 1/1       Running     0          21h
istio-grafana-post-install-rg8qs            0/1       Completed   0          21h
istio-ingressgateway-7f4dd7d699-9znwq       1/1       Running     0          21h
istio-pilot-6f8d49d4c4-snqp7                0/2       Pending     0          21h
istio-policy-67f4d49564-5cb6k               2/2       Running     0          21h
istio-sidecar-injector-69c4bc7974-f6bmb     1/1       Running     0          21h
istio-statsd-prom-bridge-7f44bb5ddb-z2m76   1/1       Running     0          21h
istio-telemetry-76869cd64f-2rssb            2/2       Running     0          21h
istio-tracing-ff94688bb-2mvj6               1/1       Running     0          21h
prometheus-84bd4b9796-nltkh                 1/1       Running     0          21h
servicegraph-c6456d6f5-swkjp                1/1       Running     0          21h

kubectl -n istio-system exec -it istio-ingressgateway-7f4dd7d699-9znwq -- netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      27/envoy
udp        0      0 10.1.0.69:35007         10.104.224.7:9125       ESTABLISHED 27/envoy
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ]         DGRAM                    105679   27/envoy            @envoy_domain_socket_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by supereagle** [comment]
Not sure why some ports are not opened, you can have a try to restart `istio-ingressgateway` pod.

**Comment by wangybgit** [comment]
> @shavo007
> I think the problem should be the sidcar or the virtual-service-all-v1.yaml or the bookinfo-gateway.yaml.
> 
> Today I redeployed istio1.0 and accessing bookinfo-service normal using nodeport.
> 
> But I don't know why.
I meet the same problem,when I start the bookinfo application using the nodePort:
kubectl apply -f <(istioctl kube-inject -f bookinfo.yaml)
then start the  gateway(had changed the destination port to the nodePort of productpage service), access the productpage  service failed.
but I can access after some times(about 5 minutes),why???

**Comment by wangybgit** [comment]
I meet a problem,I start the bookinfo application without changing any yaml files:
kubectl apply -f <(istioctl kube-injct -f bookinfo.yaml)
and start the gateway:
kubectl apply -f bookinfo-gateway.yaml
then try to access the productpage service use the port:31380
![image](https://user-images.githubusercontent.com/19662595/47889650-f9564f80-de85-11e8-8460-b361b001c1fb.png)
access the service failed,I tried several times,can not work.
but,It can be access when I start the gateway again.
the first is failed,the second time is successful,why?

**Comment by yuanzhang** [comment]
same problem

**Comment by orangeh8** [comment]
I have the same problem

**Comment by chainat** [comment]
I was testing kubernetes supplied by docker-for-mac with istio 1.0.5 where encountered the exact same problem. I deployed the stack by using a `istio-demo.yaml` file. Took me a while to figure out the routing issue. I found out that the problem is from Gateway resource from that file. It had a wrong pod selector.  The correct one should be `istio: ingressgateway` but the package contains just `istio: ingress`

Here is a working copy:
`
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      protocol: HTTP2
      name: http
    hosts:
    - "*"
`
Once updated, technically, you should be able to access `http://localhost/productpage` straightaway. However, In my case, I needed to restart an isio-ingressgateway controller pod in istio-system. I shouldn't need to do that tho.

**Comment by davinkevin** [comment]
+1 with @chainat ! 
I didn't find where to do a PR to fix this. Any idea ?

**Comment by chainat** [comment]
@davinkevin I haven't created a PR yet. I will need a little extra time to understand the project structure and code contribution process. FYI - `istio-demo.yaml` seems to be an autogenerated file which value is derived from Helm's file. The fix would be to update a value in a Helm's value file. Will create a PR once I have a chance.

**Comment by idarvind** [comment]
Check if gateway and virtual services created, if not then create it and then try to access the bookinfo app
```
kubectl get gateway
kubectl get virtualservice
```
```
$ kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
gateway.networking.istio.io/bookinfo-gateway created
virtualservice.networking.istio.io/bookinfo created
```

Now try to access the http:/<istio-ingress IP>productpage

**Comment by sha-rath** [comment]
I am having the same problem. I'm using Mac with Docker for Desktop installed (k8s running too). Istio v1.5.2 and bookinfo deployment is fine. I have defined both gateway and virtual service, but I'm unable to access http://localhost/productpage

**Comment by amitabak-MA** [comment]
Following the documentation in https://istio.io/latest/docs/setup/getting-started/  doesnt end up with the correct link , namely http://localhost/productpage. Please fix documentation

**Comment by patelrutva** [comment]
I am also having the similar issue. I'm using MacOS with Minikube installed (k8s running too). same as @shavo007 @sha-rath I have also performed all the mentioned steps successfully, but unable to access `http://gatewayurl/productpage`

Anybody who already resolved this can you please share the solution you have applied.

**Comment by patelrutva** [comment]
I finally found the solution:

please refer this link : [https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/](url) 

Thanks

**Comment by rohangoyalDTC** [comment]
@patelrutva What worked as a fix for you?

**Comment by sha-rath** [comment]
I'm using Docker Desktop for Mac (v2.5.0.1) and I don't see any issues now. The EXTERNAL-IP value is set to _localhost._ You can see this when you do:
`kubectl get svc istio-ingressgateway -n istio-system`

Therefore, make sure the INGRESS_PORT is set to 80.
`export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')`

Set INGRESS_HOST as follows:
`export INGRESS_HOST=127.0.0.1`

Set GATEWAY_URL:
`export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT`

`echo $GATEWAY_URL` should show `127.0.0.1:80`

Try accessing _productpage_ from the browser like `http://localhost/productpage`. This should work!

**Comment by rohangoyalDTC** [comment]
Actually, what worked for me was deleting the nginx ingress which was competing with istio for catching a request. Thanks

**Comment by kochsecurity** [comment]
I'm having a hard time accessing the application when I change the service to NodePort. My cluster is deployed in EKS.
So far using LoadBalancer service worked  but when I switched the service to nodePort and tried to access the application with curl, I can an error.

```export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT```

```curl -s "http://${GATEWAY_URL}/productpage" | grep -o "<title>.*</title>" ```

Any help with be appreciated.

**Comment by raydemandforce** [comment]
You can run follow to set your INGRESS_HOST
```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
```
This will set your to INGRESS_HOST=localhost

**Comment by alexandrperry** [comment]
You need to run this command in the separate terminal when using minikube
`minikube tunnel`
