### ISSUE TITLE
Unsupported type error when creating a gRPC adapter

### ISSUE THREAD

**Issue by eyeofthefrog** [istio/istio#7645]
**Describe the bug**
I'm creating a gRPC adapter. When I use attributes that are simple strings, it works fine. When I use other types, then I get errors like the following:
```
2018-08-03T21:43:39.161921Z     error   config does not conforms to schema of template 'authorization': 
unable to build message field: action, unable to build message field: properties, 
unable to build message field: value, unsupported type: IP_ADDRESS
```
Here's a sample of the instance I'm defining:
```
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: my-authorization
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: request.auth.principal | ""
      groups: request.auth.principal | ""
      properties:
        sourceIp: source.ip | ip("0.0.0.0")
        sourceAddress: source.service | ""
        sourcePort: source.port | 0
        sourceName: source.name | ""
        sourceUid: source.uid | ""
        sourceNamespace: source.namespace | ""
        sourceVersion: source.labels["version"] | "unknown"
    action:
      namespace: destination.namespace | ""
      service: destination.service | ""
      method: request.method | ""
      path: request.path | ""
      properties:
        protocol: request.scheme | ""
        destinationIp: destination.ip | ip("0.0.0.0")
        destinationAddress: destination.service | ""
        destinationPort: destination.port | 0
        destinationName: destination.name | ""
        destinationUid: destination.uid | ""
        destinationNamespace: destination.namespace | ""
        destinationVersion: destination.labels["version"] | "unknown"
```
**Expected behavior**
No errors when loading the configuration for my adapter.

**Steps to reproduce the bug**
Create a gRPC adapter using properties of type other than string.

**Version**
istio: 1.0.0
kubernetes: v1.10.5-gke.3

**Is Istio Auth enabled or not?**
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```

**Environment**
GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2259759/istio-dump.tar.gz)

**Comment by mandarjog** [comment]
@theganyo are facing the same problem?

**Comment by theganyo** [comment]
Yes, I'm seeing the same issue. (Also seeing a similar issue with non-string config items in the handler definition.)

**Comment by mandarjog** [comment]
More logs
```
proto: no coders for interface {}
proto: no encoder for Params interface {} [GetProperties]
proto: no coders for interface {}
proto: no encoder for Params interface {} [GetProperties]
2018-08-09T18:04:47.837410Z	error	field 'client_timeout' is of type 'string' instead of expected type 'google.protobuf.Duration'
2018-08-09T18:04:47.840250Z	error	config does not conforms to schema of template 'apigee-analytics': unable to process: name:"client_ip" number:3 label:LABEL_OPTIONAL type:TYPE_MESSAGE type_name:".istio.policy.v1beta1.IPAddress" json_name:"clientIp" , got string, want: map[string]interface{}
2018-08-09T18:04:47.840310Z	error	Handler not found: handler='apigee-handler'
```

handler config
```
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: apg-handler
  namespace: istio-system
spec:
  adapter: apg
  connection:
    address: ":5000"
  params:
    key: 5c90332eb25
    secret: 9916492e959

    temp_dir: "/tmp/istio"
    client_timeout: 30s
    products:
      refresh_rate: 2m
    analytics:
      legacy_endpoint: false
      file_limit: 1024
```

Need special handling for `.istio.policy.v1beta1.`

**Comment by mandarjog** [comment]
@theganyo can you test it against gcr.io/mixologist-142215/mixer:1.0.1-grpc1  build ?
The master build may not be ready yet.

**Comment by theganyo** [comment]
Yup. It looks good! Thanks!

**Comment by edodekel** [comment]
when I add:
        sourceLabels: source.labels | emptyStringMap()

to the properties under 
spec: 
   params:
      subject:
i get the following error
2018-08-30T12:43:10.132556Z     error   config does not conform to schema of template 'authorization': unable to build message field: subject, unable to build message field: properties, unable to build message field: value, **unsupported type: STRING_MAP** (.istio.policy.v1beta1
.Value)

can you please support STRING_MAPs?

**Comment by mandarjog** [comment]
@edodekel can you pass along the labels that you want on the other side?
Our approach generally is that operator should be explicit in mapping. source.label / request.headers may contain information that you may not want to disclose without explicit intent.

**Comment by eyeofthefrog** [comment]
@mandarjog What about logging adapters where we would like to capture all the request and response headers for analysis later?

**Comment by edodekel** [comment]
@mandarjog My use-case is exactly what @eyeofthefrog mentioned. Moreover I do not know the source.labels beforehand and need to analyze them at run time. My point is that we should support all of the attributes that istio allows (https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/)

**Comment by edodekel** [comment]
hi. is there any update? all of the attribute-vocabulary should be supported.
