### ISSUE TITLE
Test concurrency of ingress gateway

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#7653]
Asked at Istio-users https://groups.google.com/forum/#!topic/istio-users/zdR98MVvRVw.

**Comment by adamzhoul** [comment]
with concurrency add .
tcp Three-way Handshake time increase obviously.
which lead to poor performance.

Does any one know have any idea?

**Comment by mandarjog** [comment]
Adam please use istio/fortio, jmeter, or wrk / wrk2 tools to perform this test. That is what we use for the project. We are not tracking connect time specifically though .

**Comment by adamzhoul** [comment]
@mandarjog i use another service do the test. this two are no different.
on my mac
with command :  ./fortio  load -qps 0 -t 60s -c 1000 -r 0.0001 "http://zlkotest.mservice.svc.mfw"
# target 50% 0.0626915
# target 75% 0.180499
# target 90% 0.496795
# target 99% 2.58317
# target 99.9% 8.42624

with command : curl -o /dev/null -s -w time_namelookup:"\t"%{time_namelookup}"\n"time_connect:"\t\t"%{time_connect}"\n"time_appconnect:"\t"%{time_appconnect}"\n"time_pretransfer:"\t"%{time_pretransfer}"\n"time_starttransfer:"\t"%{time_starttransfer}"\n"time_total:"\t\t"%{time_total}"\n"time_redirect:"\t\t"%{time_redirect}"\n" http://zlkotest.mservice.svc.mfw
time_namelookup:	0.005
time_connect:		0.006
time_appconnect:	0.000
time_pretransfer:	0.006
time_starttransfer:	0.013
time_total:		0.014
time_redirect:		0.000

we can see from this,  total time increase much.
