### ISSUE TITLE
How can I apply multiple certificates in istio-ingressgateway

### ISSUE THREAD

**Issue by exiaohao** [istio/istio#7658]
**--what the problem is--**
I have several TLS certificates for different domains on ingress-gateway,
But it seems support only one certificate which was `istio-ingressgateway-certs` from secret/tls (from https://istio.io/docs/tasks/traffic-management/secure-ingress/)

How can I apply more than one certificate for different domains?

ps.
Why not use Kubernetes' `secret` to specify key & certificates instead of loading files like this:
```yaml
tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**Comment by vadimeisenbergibm** [comment]
You can either edit the ingress gateway deployment manually and add more volume mounts, or use `helm` and set `secretVolumes` array with your certificates, see the original value in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L237.

> Why not use Kubernetes' secret to specify key & certificates

Because Istio is designed to run also in non-Kubernetes environments, so it's configuration strives not to contain Kubernetes constructs.

**Comment by dunjut** [comment]
@vadimeisenbergibm So essentially, to get https traffic working, a user only has to specify the certificate path in Gateway and make sure it exists in the ingressgateway container, no matter the certificate is mounted from kubernetes secret or any other means, right?

If so, to dynamically adding more tls certificates to ingressgateway without re-deployment, we may need to develop a tool which defines how users upload their certs (using k8s Secret for example) and automatically place those certs into user-specified paths inside ingressgateway container when uploading events happen?

**Comment by vadimeisenbergibm** [comment]
@dunjut That's correct.

**Comment by dunjut** [comment]
@vadimeisenbergibm Plenty of users run istio in kubernetes (istio is designed for multi kind of environments though), to make dynamic tls certificate support available to users like us, is it acceptable that we develop such a tool and make it optional in helm chart like kiali, certmanager and so?

**Comment by dunjut** [comment]
@incfly replied to [this istio-dev thread](https://groups.google.com/forum/#!topic/istio-dev/ik18OpIkgE8) and said you're working on integrating Envoy SDS to let the workload fetch key cert in the runtime. Will that work solve this issue? cc @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment]
> integrating Envoy SDS to let the workload fetch key cert in the runtime. Will that work solve this issue?

@dunjut Yes, it seems so.

**Comment by myidpt** [comment]
@dunjut 
Now Istio supports multiple external certificates on gateway.
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway
I haven't tried how to configure it yet (sorry, just came back from long vacation). I will update the "secure ingress" task soon after I verify the configuration.
For dynamic update of the external secret, the Pilot agent watcher restarts the gateway automatically once you update the cert/key files on the gateway pod.
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/main.go#L247 
In the future, I believe we should get rid of the file watcher, and use SDS to update the key/cert for external certs as well.

**Comment by andersjanmyr** [comment]
@myidpt I don't see how Istio supports multiple external certificates from the documentation on gateway that you referenced. As far as I can tell it only supports one certificate per server.
```
 - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```
We would also need to specify for what host a certificate is served for.
Envoy supports multiple certificates through `filter_chains`, https://www.envoyproxy.io/docs/envoy/latest/faq/sni, but as far as I can tell this is not generated by Istio at the moment. 

Do I misunderstand?

**Comment by dunjut** [comment]
I just spend some time writing a [tool](https://github.com/dunjut/cert-sync) to automate the synchronization between kubernetes secrets and istio-ingressgateway certificates.

Folks who suffer from this issue can have try on it (a very early version though).

cc @vadimeisenbergibm @myidpt @andraxylia @andersjanmyr

**Comment by vadimeisenbergibm** [comment]
@exiaohao Here is how you can do it https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/#configure-a-tls-ingress-gateway-for-multiple-hosts

**Comment by ZhiminXiang** [comment]
@vadimeisenbergibm I am not sure if the Gateway could still serve the traffic well during the process of the redeployment?

**Comment by exiaohao** [comment]
@vadimeisenbergibm Thanks for your help, it seem that new certificates will take effect after redeploy istio-ingressgateway. But in this way I'm not sure `Gateway` can upgrade without downtime.
if so, it's not really a good idea for users I think, we'd reduce any downtime and have a failover plan for incorrect config.
Is there any official solutions like @dunjut 's way, I think it's a easy way without downtime.

**Comment by sudermanjr** [comment]
@exiaohao With the ingressgateway being scalable now, I think you should be able to rolling-update the ingressgateway with your new cert without downtime.

**Comment by dunjut** [comment]
@sudermanjr Scaling and rolling-updating implies some kind of loadbalancer in front of ingressgateway, which is common in a cloud environment, but it's not always true in bare-metals.

In our scenario, we deploy ingressgateway as DaemonSet on a set of dedicated physical machines, facing directly to users, acting as edge layer 7 gateway.

**Comment by myidpt** [comment]
I think the best solution here is to have ingress gateway use SDS to load these certs from node agent (which can watch certs from k8s secrets or external API). This can be implemented after node agent work is done on master (hopefully soon). The work is not very complex when node agent is ready, and dunjut is also willing to help :) For anyone having a timing concern, please try dunjut's tool.

**Comment by ZhiminXiang** [comment]
My understanding about dunjut's tool is that it places certificates into the volumes that have been created in the istio-ingressgateway pods.
But if all of volumes are already taken and we still want to add a new domain and its certificate into Gateway, we have to redeploy istio-ingressgateway pods to add more volumes, right? Is there any solution to avoid redeployment of istio-ingressgateway in this case?

**Comment by exiaohao** [comment]
@ZhiminXiang https://github.com/dunjut/cert-sync use `<certdir>/<namespace>/<name>` as path for certificates.
By default setting, certificates has load to `/etc/istio/ingressgateway-certs/<namespace>/<name>.{key, crt}`
It takes only one directory for all certificates and no need to redeploy.

**Comment by vadimeisenbergibm** [comment]
@exiaohao Is this issue still relevant? What else is required to be done?

**Comment by annismckenzie** [comment]
This shouldn't have been closed until @myidpt's suggestion is either implemented or documented to be working?

**Comment by mmckane** [comment]
Can someone Please Re-Open this? This is not implemented or documented from what I can tell. Envoy appears to have implemented the Secret Discovery Service, and the Node Agent appears to have some implementation of the envoy secret discovery service but I am guessing that is for mtls cert refresh. If this does work for the Istio Gateway does anyone have details on how this works or how to set it up?

**Comment by myidpt** [comment]
Please see https://github.com/istio/istio/issues/9030. It should solve the multiple-tls cert issue here.
