### ISSUE TITLE
mTLS doesn't work with subset

### ISSUE THREAD

**Issue by panywei** [istio/istio#7666]
**Describe the bug**
If I apply a DestinationRule with a subset defined, the mlts connection doesn't work as expected, but ignore the subset settings.

**Expected behavior**
The traffic which goes to subset should honor the DestinationRule mtls settings.

**Steps to reproduce the bug**
1) Change Authn policy of service to PERMISSIVE
2) Apply a DestinationRule with a subset
3) Issue a traffic to the productpage, and the connection should be in mtls.

The actual yaml is like this:
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: reviews-policy
  namespace: demo
spec:
  targets:
  - name: reviews
    ports:
    - number: 9080
  peers:
    - mtls:
        mode: PERMISSIVE
---        
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-destinationrule
  namespace: demo
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: DISABLE
  subsets:
  - name: v3
    labels:
      version: v3
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL

**Version**
Istio 1.0 and GKE 1.10.5

**Is Istio Auth enabled or not?**
No

**Environment**
GKE

**Cluster state**

**Comment by wattli** [comment]
@diemtvu @liminw i think it should work now. Could you help to verify? Thanks.
