### ISSUE TITLE
Ship Istio with Permissive mode as default

### ISSUE THREAD

**Issue by wattli** [istio/istio#7667]
We already support permissive mode (i.e., mTLS and http are both supported at server side) with auth policy. Enabling this mode as default can improve istio (security) adoption UX. 

Work:
- some performance/stableness test to make sure permissive mode does not incur too much overhead
- integrate with monitoring tools (grafana or others) to make sure customers can clearly see what (http/mTLS) traffic are in the connection

@louiscryan @wenchenglu

**Comment by Stono** [comment]
@wattli any docs around permissive mode?  I ask because I think this might solve a problem for us where we need prometheus to be able to scrape metrics from an an mTLS endpoint (but prometheus doesn't have istio-pilot).
