### ISSUE TITLE
Integrating other service registry. Using consul, eureka with Istio

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#767]

**Comment by linsun** [comment]
Part of this is done in #681.  cc @ijsnellf would like to have similar docs for Eureka.

**Comment by rshriram** [comment]
@linsun this is for the istio docs tasks. 
cc @GregHanson

**Comment by rshriram** [comment]
Issue moved to [istio/istio.github.io #469](https://github.com/istio/istio.github.io/issues/469) via [**ZenHub**](https://www.zenhub.com/)
