### ISSUE TITLE
[Ansible Installer] Istio Demo file is not found in Ansible Installer on Istio 1.0.0

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#7673]
## Description
Istio Demo file is not found in Ansible Installer.

Executed the following command `ansible-playbook main.yml -e '{"istio": {"release_tag_name": "1.0.0", "auth": false, "delete_resources": true}}' on `release-1.0` branch

## Expected Behaviour
- Istio installed

## Actual Behaviour

> TASK [istio : Copy definition file] ************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cp", "/home/user/istio/install/kubernetes/istio-demo.yaml", "/tmp/ansible.e8nrr0lJ0v/def.yml"], "delta": "0:00:00.002999", "end": "2018-08-06 18:02:07.137754", "msg": "non-zero return code", "rc": 1, "start": "2018-08-06 18:02:07.134755", "stderr": "cp: cannot stat '/home/user/istio/install/kubernetes/istio-demo.yaml': No such file or directory", "stderr_lines": ["cp: cannot stat '/home/user/istio/install/kubernetes/istio-demo.yaml': No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by gbaufake** [comment]
cc @sdake @gyliu513  @geoand @ymesika

**Comment by ymesika** [comment]
This looks like having a typo: `/home/usert/istio/install/kubernetes/istio-demo.yaml`
`usert`?

**Comment by geoand** [comment]
That indeed looks like a type, it's weird however that such a type shows up...

**Comment by gbaufake** [comment]
@ymesika you are right.
There was typo on my error. Updated!

**Comment by geoand** [comment]
@gbaufake I probably won't be able to look at this for a couple days :(

**Comment by gbaufake** [comment]
I think I have figured out.
By downloading the release and executing the ansible command works like a charm.


Since the istio-demo.yaml is included  https://github.com/istio/istio/blob/f3a6d521a1a3225ac855b95fada056e234dbf503/.gitignore#L39.]

When you do clone the repository, the ansible repository will not work since it doesn't contain the istio-demo file (which I don't know if it is on purpose or not).

Anyhow, 
Thanks for attention.
