### ISSUE TITLE
Sanitize and/or provide useful X-Forwarded-For header

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#7679]
**Describe the bug**
`X-Forwarded-For` header isn't sanitized before being forwarded by ingress gateway, which means that malicious client can easily spoof its source address by sending `X-Forwarded-For` header with fake IP address, and while the fake IP address won't be used by ingress gateway (because of the `use_remote_address: true` setting), it might be accepted by workloads trusting ingress to pass client's IP using this header.

Note that the presence of spoofed `X-Forwarded-For` header results in either `X-Envoy-Internal` or `X-Envoy-External-Address` being forwarded to the workload.

Furthermore, even without spoofing, both `X-Forwarded-For` and `X-Envoy-External-Address` headers contain IP address of `kube-proxy` (e.g. `10.128.0.5`) and not client's IP, rendering it pretty useless.

External request:
```
curl -v -H"Host: httpbin.example.com" http://$INGRESS_HOST:$INGRESS_PORT/get?show_env=1
```
```
< HTTP/1.1 200 OK
< server: envoy
< date: Tue, 07 Aug 2018 00:29:34 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< content-length: 534
< x-envoy-upstream-service-time: 6
<
{
  "args": {
    "show_env": "1"
  },
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "httpbin.example.com",
    "User-Agent": "curl/7.60.0",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "f318863530d246b3",
    "X-B3-Traceid": "f318863530d246b3",
    "X-Envoy-Internal": "true",
    "X-Forwarded-For": "10.128.0.5",
    "X-Forwarded-Proto": "http",
    "X-Request-Id": "a53a017d-dc07-9784-a4ec-5957a1915800"
  },
  "origin": "10.128.0.5",
  "url": "http://httpbin.example.com/get?show_env=1"
}
```

External request with spoofed `X-Forwarded-For` header:
```
curl -v -H"Host: httpbin.example.com" -H"X-Forwarded-For: 1.2.3.4" http://$INGRESS_HOST:$INGRESS_PORT/get?show_env=1
```
```
< HTTP/1.1 200 OK
< server: envoy
< date: Tue, 07 Aug 2018 00:29:50 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< content-length: 566
< x-envoy-upstream-service-time: 13
<
{
  "args": {
    "show_env": "1"
  },
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "httpbin.example.com",
    "User-Agent": "curl/7.60.0",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "384e7075880e36c8",
    "X-B3-Traceid": "384e7075880e36c8",
    "X-Envoy-External-Address": "10.128.0.5",
    "X-Forwarded-For": "1.2.3.4, 10.128.0.5",
    "X-Forwarded-Proto": "http",
    "X-Request-Id": "38bab7c1-5691-9825-ba76-a3a654b83842"
  },
  "origin": "1.2.3.4, 10.128.0.5",
  "url": "http://httpbin.example.com/get?show_env=1"
}
```

**Expected behavior**
`X-Forwarded-For` header should contain valid client's IP, and ingress gateway should sanitize and/or strip untrusted values before forwarding requests to backend services.

Note that we should account for trusted load balancers being deployed in front of ingress gateway and forwarding valid client's IP using this header.

**Steps to reproduce the bug**
[Deploy sample `httpbin` service and expose it via ingress gateway from the official guide](https://istio.io/docs/tasks/traffic-management/ingress/) and issue `curl` commands mentioned above.

**Version**
```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
n/a

**Environment**
GKE

cc @louiscryan @costinm @rshriram

**Comment by kyessenov** [comment]
Ingress gateways should run with externalTrafficPolicy set to Local (see https://github.com/istio/istio/issues/7328)

**Comment by PiotrSikora** [comment]
@kyessenov Good find, thanks! Indeed, changing `externalTrafficPolicy` from `Cluster` to `Local` results in real client IP being passed via `X-Forwarded-For` header.

That leaves us with sanitization that won't break `X-Forwarded-For` passed by load balancers.

**Comment by mandarjog** [comment]
It depends on which lbs are in the front of ingress. If there is a trusted lb like gcp lb or  elb is in front, then you want the left most address set by in xff, if the fronting lb already sanitizes. this should be configurable by deployment. 
Is there a way to configure trusted downstream in envoy?

**Comment by rshriram** [comment]
There is a load balancer source ip range in kube. Not sure if that helps. Else we can look into ip tagging filter or add a source subnet field in the filter chain match so that we can enable it via api (users specify source ip ranges in the gateway spec).

**Comment by rshriram** [comment]
I think source subnet match is easiest way forward.

**Comment by PiotrSikora** [comment]
@mandarjog you can configure number of trusted proxies ([xff_num_trusted_hops](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for)), which, while not perfect, works for the "behind cloud load balancer" use case.

**Comment by exiaohao** [comment]
@kyessenov 
I've changed `externalTrafficPolicy` from `Cluster` to `Local`, Ingressgateway seems stopped working. envoy is still listening port but the port doesn't response any request.

my istio-ingressgateway config
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","chart":"gateways-1.0.0","heritage":"Tiller","istio":"ingressgateway","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"http2","nodePort":31380,"port":80,"targetPort":80},{"name":"https","nodePort":31390,"port":443},{"name":"tcp","nodePort":31400,"port":31400},{"name":"tcp-pilot-grpc-tls","port":15011,"targetPort":15011},{"name":"tcp-citadel-grpc-tls","port":8060,"targetPort":8060},{"name":"http2-prometheus","port":15030,"targetPort":15030},{"name":"http2-grafana","port":15031,"targetPort":15031}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
  creationTimestamp: 2018-08-09T09:07:09Z
  labels:
    app: istio-ingressgateway
    chart: gateways-1.0.0
    heritage: Tiller
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "1430477"
  selfLink: /api/v1/namespaces/istio-system/services/istio-ingressgateway
  uid: 98cb3523-9bb3-11e8-91cb-000c29469214
spec:
  clusterIP: 172.21.188.124
  externalIPs:
  - 10.7.0.194
  externalTrafficPolicy: Cluster
  ports:
  - name: http2
    nodePort: 31380
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31390
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcp
    nodePort: 31400
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tcp-pilot-grpc-tls
    nodePort: 30833
    port: 15011
    protocol: TCP
    targetPort: 15011
  - name: tcp-citadel-grpc-tls
    nodePort: 32514
    port: 8060
    protocol: TCP
    targetPort: 8060
  - name: http2-prometheus
    nodePort: 30431
    port: 15030
    protocol: TCP
    targetPort: 15030
  - name: http2-grafana
    nodePort: 31506
    port: 15031
    protocol: TCP
    targetPort: 15031
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by andraxylia** [comment]
We can add a helm deployment option in the istio-ingressgateway proxy, where the user can specify if the gateway is an edge proxy, or it is located behind a trusted load balancer. This will get passed via proxy node Metadata  to Pilot, which will generate the correct Envoy config with the correct combination of use_remote_address and xff_num_trusted_hops as described here:

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for

Let me know if you see issues with this approach for 1.0.1.

**Comment by duderino** [comment]
@rshriram's proposal to filter on source IP with a CIDR or similar would handle cases where an ingress gateway wants to strip an xff header from some but not all of its clients.   The current approach is all or nothing - the ingress gateway trusts all of its clients or none of its clients.

Is that flexible enough?

**Comment by andraxylia** [comment]
@duderino Envoy does not have support for filtering x-forwarded-for , it would need to be added.

What are the best practices in the industry to prevent spoofing and how do other proxies handle it? I wonder why Envoy went with the num_hops solely. @PiotrSikora

**Comment by andraxylia** [comment]
filtering based on IP is discussed here also as a possible fix: https://github.com/cloudfoundry/gorouter/issues/179

**Comment by rkpagadala** [comment]
@PiotrSikora We want to cut a build on Friday, what is the status of this bug

**Comment by merlineus** [comment]
Should this work with AWS ELB?
I've added ```externalTrafficPolicy: Local``` to ```istio-ingressgateway``` service but can see only the balancer's IP in nginx logs.

**Comment by andraxylia** [comment]
@rkpagadala I am working on this as per this proposal: https://github.com/istio/istio/issues/7679#issuecomment-412739471

**Comment by PiotrSikora** [comment]
@andraxylia I thought the plan for 1.0.1 was to only strip `X-Forwarded-For`, since we don't have `externalTrafficPolicy: Local` merged yet (see: https://github.com/istio/istio/pull/7918), so the info there is pretty useless.

**Comment by andraxylia** [comment]
@PiotrSikora the agreement was to have a flag for edge proxy, on by default, and to strip only for edge proxies. This way, when externalTrafficPolicy is fixed, we don't need to revisit this issue anymore, it will just work.

**Comment by Dagon-** [comment]
@exiaohao Did you find a fix for this? I'm seeing the same thing.

**Comment by osswangxining** [comment]
> @exiaohao Did you find a fix for this? I'm seeing the same thing.

You can specify the parameter gateways.istio-ingressgateway.externalTrafficPolicy to Local if using Helm to deploy.

**Comment by migueleliasweb** [comment]
I'm having the same problems as @exiaohao . When I use `externalTrafficPolicy: Local` the IngressGateway basically stops working. I'm even seeing the NLB is unable to perform the healthchecks...

**Comment by slabber** [comment]
> @mandarjog you can configure number of trusted proxies ([xff_num_trusted_hops](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for)), which, while not perfect, works for the "behind cloud load balancer" use case.

How is it possible in istio to do this?  I'm running my istio-ingressgateway behind a CDN so I need envoy to process the X-Forwarded-For header - so far using Istio 1.0.3 I've been unable to figure out how to do it.

**Comment by julianvmodesto** [comment]
We'd like to use the X-Forwarded-For header for client ip affinity, using `LoadBalancerSettings.ConsistentHashLB`, so this is a blocker for us to use Istio on GKE, with a hop to a GCLB.

```
x-forwarded-for=<client ip>, <gclb ip>, <ingress ip>
```

**Comment by slabber** [comment]
It's a bit hackish but it's actually possible to do this with a separate pod and the envoy External Authorization filter.  You can specify which client header to send to the authorization service and which  return header to then forward to your upstream.

I ended up with a filter like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: header-sanitize
spec:
  filters:
  - filterConfig:
      http_service:
        allowed_authorization_headers:
        - x-forwarded-for
        allowed_request_headers:
        - x-forwarded-for
        server_uri:
          cluster: outbound|80||headersanitizer.default.svc.cluster.local
          failure_mode_allow: true
          timeout: 0.25s
          uri: headersanitizer.default.svc.cluster.local:80
    filterName: envoy.ext_authz
    filterType: HTTP
    listenerMatch:
      listenerProtocol: HTTP
      listenerType: GATEWAY
      portNumber: 443
  workloadLabels:
    istio: ingressgateway
```

The header sanitizer can just be a simple apache container that does a rewrite for all requests to a simple script that can then manipulate the headers for you:

apache.conf
```
RewriteEngine On
RewriteCond %{REQUEST_URI} !^/index\.php$
RewriteRule . /index.php [L]
```

index.php
```
<html>hello world</html>
<?php

if( !function_exists('apache_request_headers') ) {
///
function apache_request_headers() {
  $arh = array();
  $rx_http = '/\AHTTP_/';
  foreach($_SERVER as $key => $val) {
    if( preg_match($rx_http, $key) ) {
      $arh_key = preg_replace($rx_http, '', $key);
      $rx_matches = array();
      // do some nasty string manipulations to restore the original letter case
      // this should work in most cases
      $rx_matches = explode('_', $arh_key);
      if( count($rx_matches) > 0 and strlen($arh_key) > 2 ) {
        foreach($rx_matches as $ak_key => $ak_val) $rx_matches[$ak_key] = ucfirst($ak_val);
        $arh_key = implode('-', $rx_matches);
      }
      $arh[$arh_key] = $val;
    }
  }
  return( $arh );
}
///
}

$headers = apache_request_headers();

foreach ($headers as $header_name => $header_field) {
    if (strcasecmp($header_name, "X-Forwarded-For") === 0) {

        $x_forwarded_for = explode(",", $header_field);

        array_pop($x_forwarded_for);
        array_pop($x_forwarded_for);

        header("$header_name: " . trim(end($x_forwarded_for)));
        exit();
    }
}
exit;

?>
```

This one just removes the 2 right most values from the x-forwarded-for

**Comment by seventhfish** [comment]
> @kyessenov
> I've changed `externalTrafficPolicy` from `Cluster` to `Local`, Ingressgateway seems stopped working. envoy is still listening port but the port doesn't response any request.
> 
> my istio-ingressgateway config
> 
> ```yaml
> apiVersion: v1
> kind: Service
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","chart":"gateways-1.0.0","heritage":"Tiller","istio":"ingressgateway","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"http2","nodePort":31380,"port":80,"targetPort":80},{"name":"https","nodePort":31390,"port":443},{"name":"tcp","nodePort":31400,"port":31400},{"name":"tcp-pilot-grpc-tls","port":15011,"targetPort":15011},{"name":"tcp-citadel-grpc-tls","port":8060,"targetPort":8060},{"name":"http2-prometheus","port":15030,"targetPort":15030},{"name":"http2-grafana","port":15031,"targetPort":15031}],"selector":{"app":"istio-ingressgateway","istio":"ingressgateway"},"type":"LoadBalancer"}}
>   creationTimestamp: 2018-08-09T09:07:09Z
>   labels:
>     app: istio-ingressgateway
>     chart: gateways-1.0.0
>     heritage: Tiller
>     istio: ingressgateway
>     release: istio
>   name: istio-ingressgateway
>   namespace: istio-system
>   resourceVersion: "1430477"
>   selfLink: /api/v1/namespaces/istio-system/services/istio-ingressgateway
>   uid: 98cb3523-9bb3-11e8-91cb-000c29469214
> spec:
>   clusterIP: 172.21.188.124
>   externalIPs:
>   - 10.7.0.194
>   externalTrafficPolicy: Cluster
>   ports:
>   - name: http2
>     nodePort: 31380
>     port: 80
>     protocol: TCP
>     targetPort: 80
>   - name: https
>     nodePort: 31390
>     port: 443
>     protocol: TCP
>     targetPort: 443
>   - name: tcp
>     nodePort: 31400
>     port: 31400
>     protocol: TCP
>     targetPort: 31400
>   - name: tcp-pilot-grpc-tls
>     nodePort: 30833
>     port: 15011
>     protocol: TCP
>     targetPort: 15011
>   - name: tcp-citadel-grpc-tls
>     nodePort: 32514
>     port: 8060
>     protocol: TCP
>     targetPort: 8060
>   - name: http2-prometheus
>     nodePort: 30431
>     port: 15030
>     protocol: TCP
>     targetPort: 15030
>   - name: http2-grafana
>     nodePort: 31506
>     port: 15031
>     protocol: TCP
>     targetPort: 15031
>   selector:
>     app: istio-ingressgateway
>     istio: ingressgateway
>   sessionAffinity: None
>   type: LoadBalancer
> status:
>   loadBalancer: {}
> ```

Have the same issue, how to fix it, thx

**Comment by tx19980520** [comment]
@kyessenov
@exiaohao Have you solved the problems? Or maybe other params need change.
Or change the param in Helm?

**Comment by tx19980520** [comment]
> > @exiaohao Did you find a fix for this? I'm seeing the same thing.
> 
> You can specify the parameter gateways.istio-ingressgateway.externalTrafficPolicy to Local if using Helm to deploy.

@osswangxining 
I upgrade from 1.1 => 1.2.5 by using helm template and changed the externalTrafficPolicy to Local but the ingressgateway is not working. `kubectl edit svc istio-ingressgateway -n istio-system` change it to local it works well.
I just wanna get a real client IP to have a dynamic blacklist to limit rate by IP.

**Comment by haddadianhamed1** [comment]
for anyone who had the issue with setting externalTrafficPolicy from Cluster to Local you would need to make sure istio-ingress is running on the node you are connecting to. for example in my case I had 4 ingress gateway when I changed externalTrafficPolicy on the service from Cluster to Local I couldnt get access to my internal nodes. so what I had to do was add podaffinity to make sure istio-ingressgateway is running on the hosts that traffic is going to. when you are changing Cluster to Local it basically stops kubernetes service to proxy traffic to another host. for example if you have host A and B and you are accessing host B but istio-ingressgateway is running on host A  changing externalTrafficPolicy Cluster to Local would break the traffic. that was the issue I had. ```          - preference:
              matchExpressions:
              - key: kubernetes.io/network
                operator: In
                values:
                - public```

**Comment by PiotrSikora** [comment]
cc @nrjpoddar @costinm

**Comment by howardjohn** [comment]
Does https://github.com/istio/istio/pull/23292 fix this or is it just a part of it?

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/

**Comment by erSitzt** [comment]
> for anyone who had the issue with setting externalTrafficPolicy from Cluster to Local you would need to make sure istio-ingress is running on the node you are connecting to. for example in my case I had 4 ingress gateway when I changed externalTrafficPolicy on the service from Cluster to Local I couldnt get access to my internal containers. so what I had to do was add podaffinity to make sure istio-ingressgateway is running on the hosts that traffic is going to. when you are changing Cluster to Local it basically stops kubernetes service to proxy traffic to another host. for example if you have host A and B and you are accessing host B but istio-ingressgateway is running on host A changing externalTrafficPolicy Cluster to Local would break the traffic. that was the issue I had.
> 
> or change ingressgateway to run as DaemonSet
> 
> > ```
> >       - preference:
> > ```
> 
> ```
>           matchExpressions:
>           - key: kubernetes.io/network
>             operator: In
>             values:
>             - public
>         weight: 2
> ```

Is there a way to configure the ingress-gateway to run on all nodes via the helm values ?
I manually scaled it up to run on all nodes, but an update of istio in Rancher reverted my changes... and it took me some time to remember this problem.

Whats the *correct* way to do this ?

**Comment by nrjpoddar** [comment]
> Does #23292 fix this or is it just a part of it?

Envoy doesn't sanitize XFF headers, you can only set which XFF to use and the trusted proxies in front is supposed to sanitize if needed. The Gateway topology API allows users to easily specify which XFF to choose but doesn't guarantee sanitization.
