### ISSUE TITLE
Can't connect to Google Cloud Memorystore (redis) from pod with sidecar

### ISSUE THREAD

**Issue by jonasdkhansen** [istio/istio#7687]
**Describe the bug**
I have a fresh cluster GKE cluster, with istio 1.0 installed successfully. Then i have a redis server (memorystore on gcp), which has ip 10.0.0.3, and i'am trying to make a connection with telnet to redis, from a pod with istio sidecar. I can telnet to redis without the sidecar, so the problems lays here.
I have added the iprange to includeIPRanges: "10.0.0.0/29,10.36.0.0/14,10.100.0.0/20" in the istio configuration.

I'm using the example from Google to connect to redis https://cloud.google.com/memorystore/docs/redis/connecting-redis-instance

I have also tried with Istio 0.8.0, and that didn't work.

**Expected behavior**
I expect to connect with telnet to the service, and send a ping, to see if it is connected correctly.

**Steps to reproduce the bug**
Talk to a memorystore service in GCP from a pod with sidecar.

**Version**
Kubectl: v1.9.0
Kubernetes: v1.10.5-gke.3
Istio 1.0.0

**Is Istio Auth enabled or not?**
Installed without auth and with helm:
helm install install/kubernetes/helm/istio --name istio --namespace istio-system

**Environment**
Google Cloud Platform, and Google Kubernetes Engine

**Comment by ymesika** [comment]
The IP address of your Redis server is covered by the `10.0.0.0/29` CIDR therefore you either need to remove it or create a `ServiceEntry` that allows access to the external service.

**Comment by jonasdkhansen** [comment]
I'm not sure what you mean, i know that the redis ip i covered by 10.0.0.0/29, and that's why i added it to includeIPRanges list. Should i remove it from the list and create a ServiceEntry instead ?

**Comment by ymesika** [comment]
Did you try just removing that CIDR? Keeping the included IP range though.
Alternatively, the recommended way now is not to have the included IP flag at all and add `ServiceEntry` to external services you need.
