### ISSUE TITLE
Question: Other service meshes?

### ISSUE THREAD

**Issue by krancour** [istio/istio#7691]
I see (in the Twittersphere) and hear (from co-workers) frequent comparisons between Istio and Linkerd-- including assertions that Linkerd is better for reasons xyz.

Frankly, I feel that this is an apples to oranges comparison and that such critics are overlooking the real story-- that the separation of the Istio control plane from the Istio data plane (Envoy) was deliberately intended to promote a (someday) common/ubiquitous control plane that works with a variety underlying meshes...

Am I reading that correctly? I don't really see it stated explicitly anywhere in the docs, roadmap, etc. that compatibility with other meshes is a goal. Am I just reading into the architecture too much? (I hope not!)

Bouyant published [this blog post](https://blog.buoyant.io/2017/07/11/linkerd-istio/) over a year ago (which is like seven years in container years) about, experimentally, using Istio and Linkerd together. As recently as Linkerd 1.3.1, they still seemed to be working on that. At minimum, I am assuming that Linkerd is not yet Istio 1.0 compatible. (I'll open a separate issue against Linkerd to inquire about that.)

What I'm looking for is some sense of whether Istio + other meshes (in general; not _just_ Linkerd) is a goal. Is the Istio control plane intended as an abstraction... or not? If so, is it possible that project messaging needs to be updated to convey this more clearly to critics who are overlooking this?

P.S.-- Knative seems to have raised a red flag for some pundits by being "tightly coupled" to Istio. Knative is now exploring ways to couple more loosely to the underlying mesh. In my mind, that's what Istio was for-- that Istio _is_ the abstraction that decouples Knative from Envoy / Linkerd / Conduit, whatever.

**Comment by krancour** [comment]
Realizing now that some of my impressions were probably influenced by [this article](https://thenewstack.io/which-service-mesh-should-i-use/) that @christian-posta collaborated on.

> Istio is designed to provide a universal control plane to manage a variety of underlying service proxies (it pairs with Envoy by default).

**Comment by christian-posta** [comment]
I think that is definitely part of Istio's architectural goals: to provide a common set of infrastructure and APIs to support a data plane (Envoy, or other proxies). Moreover, Istio's not tied to any specific deployment platform (i.e., Kubernetes), or backend metrics/policy engines. Istio's greatest strength is its APIs and "pluggability" with other systems.

**Comment by krancour** [comment]
@christian-posta thanks for validating my understanding.

Two follow up questions:

1. Is Istio's messaging / narrative failing to convey this point? The constant apples to oranges comparisons I'm seeing makes me think that many folks are overlooking more than half the story here.

2. "Fermi's paradox," if you will: "Where is everyone?" i.e. What other meshes are buying into the use of Istio as their control plane? It seems, per [this conversation](https://github.com/linkerd/linkerd/issues/2092) that Linkerd, for instance, may soon, in fact, be marking Istio integration deprecated. :(
