### ISSUE TITLE
Re-enable TestZipkin

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#7695]
**Describe the bug**
[TestZipkin](tests/e2e/tests/pilot/a_zipkin_test.go) is disabled in https://github.com/istio/istio/pull/5188. If this test is still needed, we have to enable it, otherwise, we could remove the test. File this issue to keep track

**Comment by JimmyCYJ** [comment]
Tentatively assign to @rshriram as jaeger stuff causes test flakiness. https://github.com/istio/istio/pull/5188#issuecomment-384768050

**Comment by duderino** [comment]
@rshriram can you work on this?  if not, please unassign yourself and add the 'community/help wanted' label

**Comment by smawson** [comment]
I'm writing a new shiny integration-test-framework version of this that isn't flakey, will delete the old one once done.

**Comment by gargnupur** [comment]
Added this test using new integration test framework.. hence closing..
