### ISSUE TITLE
Galley converts ServiceEntry CRDs to MCP

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#7698]

**Comment by ayj** [comment]
Should we consider moving the service registry ingestion code to a common top-level directory? i.e. `istio.io/istio/pilot/pkg/serviceregistry` => `istio.io/istio/pkg/serviceregistry`. 

This would continued to be used by both Pilot in addition to Galley and any other out-of-process adapter that may wish to provide service registry information via MCP. We could keep the existing interfaces / data structures for now but slowly work on decoupled this layer from the pilot's internal data model structures.

**Comment by andraxylia** [comment]
Absolutely!

Anything that can be re-used across components should be top level.

**Comment by ozevren** [comment]
Closing this. Nathan's current work should take care of this.
