### ISSUE TITLE
Update Proxy to include ORIGINAL_DST_LB fix.

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#7710]
For 1.0.1, should we pull Proxy from:

1. `master` branch, which already includes the fix, but also a few unrelated changes,
2. `release-1.0` branch, after we roll-forward Envoy to include the fix,
3. `release-1.0` branch, with cherry-picked [ORIGINAL_DST_LB fix](https://github.com/envoyproxy/envoy/commit/346059548e135199eb0b7f0006f3ef19e173bf79).

?

cc @costinm

**Comment by rkpagadala** [comment]
@PiotrSikora the fixes have to go into release-1.0 branch so either option 2 or 3

**Comment by PiotrSikora** [comment]
@costinm @louiscryan any objections before we proceed with rolling-forward?

cc @lizan

**Comment by rkpagadala** [comment]
@PiotrSikora  We want to cut a build for 1.0.1 on Friday, what is the status of this bug

**Comment by PiotrSikora** [comment]
@rkpagadala it's fixed, but it takes a bit to propagate all the way to `istio/istio`.

`master`: pending https://github.com/istio/istio/pull/7922,
`release-1.0`: pending https://github.com/istio/proxy/pull/1921, https://github.com/istio/proxy/pull/1919 and merge to `istio/istio`.
