### ISSUE TITLE
I want to apply to join istio members.

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#7721]
I want to be istio members. And found basic requirements here: https://github.com/istio/community/blob/master/ROLES.md#member

But there is no way to do this. Can anyone approve my apply?

I am `hzxuzhonghu`, currently a kubernetes apiserver reviewer.  And focus on cloud native open source.

/cc @gyliu513 @ZackButcher @rshriram

**Comment by gyliu513** [comment]
+1 to this. 

/cc @linsun

**Comment by sdake** [comment]
@hzxuzhonghu Could you expand on "no way to do this"?  I think the guidelines set forth are fairly straightforward, but if the community repository could use some fine tuning to clarify, we should take that action of clarifying membership.

Cheers
-steve

**Comment by linsun** [comment]
Please simply document your contribution so far, and we'll invite you as a member once the criteria is met:  https://github.com/istio/community/blob/master/ROLES.md#member

**Comment by hzxuzhonghu** [comment]
@linsun Thanks, following is my prs and issue

1. [remove deprecated flags](https://github.com/istio/istio/pull/7725)

1. [/watch has been deprecated, use `?watch=true`](https://github.com/istio/istio/pull/7443)

1. [use shared informer to watch kubernetes resources ](https://github.com/istio/istio/pull/7442)

1. [update time.Duration print](https://github.com/istio/istio/pull/7115)

1. [fix some misc in pilot](https://github.com/istio/istio/pull/7000)

1. [fix potential timer leak](https://github.com/istio/istio/pull/6964)

1. [use read only stop channel](https://github.com/istio/istio/pull/6960)

1. [mixer: remove outdated comments ](https://github.com/istio/istio/pull/6902)

issue: https://github.com/istio/istio/issues/1367

**Comment by hzxuzhonghu** [comment]
cc @costinm @geeknoid @kyessenov it is related to contributor experience , is there a explicitly document about this?

**Comment by hzxuzhonghu** [comment]
@rshriram Could anyone invite me to join?
