### ISSUE TITLE
Sample BookInfo Ingress Gateway Not Working -  Empty reply from server. Need to restart istio-pilot 

### ISSUE THREAD

**Issue by veludurai106** [istio/istio#7726]
**Description**
Installed Istio 1.0 using helm chart and deployed sample bookinfo application with sidecar and created ingress gateway. 

When I hit browser/curl it worked for first time but when I cleaned and re deployed the app I am getting 'curl: (52) Empty reply from server' error. If I restart istio-system it is working

**Expected behavior**
Page should loaded via ingress gateway.

**Steps to reproduce the bug**
Deployed BookInfo Sample App
`kubectl label namespace default istio-injection=enabled`
`kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`

`curl  http://${GATEWAY_URL}/productpage` returned the page
Redeployed the App
`samples/bookinfo/platform/kube/cleanup.sh`
`kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`

`curl  http://${GATEWAY_URL}/productpage` returns - curl: (52) Empty reply from server' error. 

If I try after 30 minutes it is working or If I delete the istio-pilot pod, it is returning the page. 

**Version**
Istio Version: 1.0.0
K8s Version: 1.9.8

**Installation**
Installed using helm chart
`kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`
`helm install install/kubernetes/helm/istio --name istio --namespace istio-system -f helm-istio-config-aws.yaml`

global:
  refreshInterval : 10s
  proxy:
    includeIPRanges: 100.64.0.0/10
ingress:
  enabled: true
ingressgateway:
  enabled: true
egressgateway:
  enabled: true
grafana:
  enabled: false
prometheus:
  enabled: false
servicegraph:
  enabled: false
tracing:
  enabled: true
  jaeger:
    enabled: true
kiali:
  enabled: true
pilot:
  enabled: true
  replicaCount: 3

**Environment**
Installed K8s in aws using KOPS. 

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2269726/istio-dump.tar.gz)

**Comment by uvegla** [comment]
I am getting the same running it locally on kubernetes with Docker Edge for Mac. Had similar issues with the 0.8 release and ended up using Minikube where I did not have the issue.

**Comment by veludurai106** [comment]
@uvegla  I am not facing this with 0.8 running in aws. (kops). I am facing in 1.0

**Comment by veludurai106** [comment]
Also istio-1.0.0-snapshot.1  working without this any issue.

**Comment by yepapa** [comment]
I am facing this too
Have you solved it?

**Environment**
MAC
Docker Edge 18.06
Kubernetes v1.10.3

**Comment by jsenon** [comment]
Have you seen some CPU issue on pilot pod?

**Comment by rad91** [comment]
I have the same issue running locally on docker edge for mac with kubernetes.

**Comment by procyclinsur** [comment]
I am also having the same issue with version 1.0.5 deploying to AWS, except that this is not resolved by waiting 30 minutes... I have been waiting over 2 hours and I still receive the `Empty reply from server` error message.

What can be done to fix this?
