### ISSUE TITLE
Traces more than two folds deep are being lost

### ISSUE THREAD

**Issue by Stono** [istio/istio#7730]
**Describe the bug**
Hey, we seem unable to get traces to chain together more than two services down

[nginx] -> [consumer platform] -> [sauron web] -> [abtest allocator]

We get separate traces in jaeger for:

  - [nginx] -> [consumer-platform]
  - [sauron-web] -> [abtest allocator]

For example; take the following curl, which returns a 404.

`curl -H "x-b3-flags: true" -H "x-request-id: 26930273-5a3a-47c4-8fc5-ff9782144c3f" https://our-app.com/bacon`

We see a trace in istio for the nginx -> consumer-platform:

<img width="1678" alt="screen shot 2018-08-08 at 13 38 32" src="https://user-images.githubusercontent.com/1486729/43837427-5eb986da-9b10-11e8-8ab1-54a71e810384.png">

But we do not see a trace for consumer-platform -> sauron-web (as you can see above, it stops at consumer platform.

We do then see a trace for sauron-web to abtest-allocator, but the trace and request id are different:

<img width="1680" alt="screen shot 2018-08-08 at 13 41 00" src="https://user-images.githubusercontent.com/1486729/43837537-bb778de0-9b10-11e8-86c0-0404bf638b3e.png">

Mixer logs are interesting because you can see the same consistent request id right down to sauron.

```
{"level":"info","time":"2018-08-08T12:22:02.795563Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"mutual_tls","destinationApp":"sauron-web","destinationIp":"10.202.4.48","destinationName":"sauron-web-74c8c4d4bb-d75rd","destinationNamespace":"sauron-web","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/sauron-web/deployments/sauron-web","destinationPrincipal":"cluster.local/ns/sauron-web/sa/default","destinationServiceHost":"app.sauron-web.svc.cluster.local","destinationWorkload":"sauron-web","httpAuthority":"app.sauron-web","latency":"11.63669ms","method":"GET","protocol":"http","receivedBytes":1334,"referer":"","reporter":"destination","requestId":"26930273-5a3a-97c4-8fc5-ff9782144c3g","requestSize":0,"responseCode":404,"responseSize":7510,"responseTimestamp":"2018-08-08T12:22:02.806909Z","sentBytes":8539,"sourceApp":"consumer-platform","sourceIp":"10.202.8.40","sourceName":"consumer-platform-7cddfcdd4d-wrqz2","sourceNamespace":"consumer-platform","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/consumer-platform/deployments/consumer-platform","sourcePrincipal":"cluster.local/ns/consumer-platform/sa/default","sourceWorkload":"consumer-platform","url":"/bacon","userAgent":"curl/7.54.0","xForwardedFor":"193.243.130.243, 127.0.0.1"}

{"level":"info","time":"2018-08-08T12:22:02.791014Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"mutual_tls","destinationApp":"consumer-platform","destinationIp":"10.202.8.40","destinationName":"consumer-platform-7cddfcdd4d-wrqz2","destinationNamespace":"consumer-platform","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/consumer-platform/deployments/consumer-platform","destinationPrincipal":"cluster.local/ns/consumer-platform/sa/default","destinationServiceHost":"app.consumer-platform.svc.cluster.local","destinationWorkload":"consumer-platform","httpAuthority":"app.consumer-platform.svc.cluster.local","latency":"19.182397ms","method":"GET","protocol":"http","receivedBytes":1335,"referer":"","reporter":"destination","requestId":"26930273-5a3a-97c4-8fc5-ff9782144c3g","requestSize":0,"responseCode":404,"responseSize":7510,"responseTimestamp":"2018-08-08T12:22:02.809910Z","sentBytes":8956,"sourceApp":"ingress-nginx-external","sourceIp":"10.202.7.22","sourceName":"ingress-nginx-external-controller-74c78b6bc9-vnlcd","sourceNamespace":"ingress-nginx","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/ingress-nginx/deployments/ingress-nginx-external-controller","sourcePrincipal":"cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount","sourceWorkload":"ingress-nginx-external-controller","url":"/bacon","userAgent":"curl/7.54.0","xForwardedFor":"193.243.130.243"}

{"level":"info","time":"2018-08-08T12:22:02.785721Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"unknown","destinationApp":"consumer-platform","destinationIp":"10.202.8.40","destinationName":"consumer-platform-7cddfcdd4d-wrqz2","destinationNamespace":"consumer-platform","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/consumer-platform/deployments/consumer-platform","destinationPrincipal":"","destinationServiceHost":"app.consumer-platform.svc.cluster.local","destinationWorkload":"consumer-platform","httpAuthority":"app.consumer-platform.svc.cluster.local","latency":"30.409472ms","method":"GET","protocol":"http","receivedBytes":658,"referer":"","reporter":"source","requestId":"26930273-5a3a-97c4-8fc5-ff9782144c3g","requestSize":0,"responseCode":404,"responseSize":7510,"responseTimestamp":"2018-08-08T12:22:02.816022Z","sentBytes":8971,"sourceApp":"ingress-nginx-external","sourceIp":"10.202.7.22","sourceName":"ingress-nginx-external-controller-74c78b6bc9-vnlcd","sourceNamespace":"ingress-nginx","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/ingress-nginx/deployments/ingress-nginx-external-controller","sourcePrincipal":"","sourceWorkload":"ingress-nginx-external-controller","url":"/bacon","userAgent":"curl/7.54.0","xForwardedFor":"193.243.130.243"}

{"level":"info","time":"2018-08-08T12:22:02.794182Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"unknown","destinationApp":"sauron-web","destinationIp":"10.202.4.48","destinationName":"sauron-web-74c8c4d4bb-d75rd","destinationNamespace":"sauron-web","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/sauron-web/deployments/sauron-web","destinationPrincipal":"","destinationServiceHost":"app.sauron-web.svc.cluster.local","destinationWorkload":"sauron-web","httpAuthority":"app.sauron-web","latency":"14.787346ms","method":"GET","protocol":"http","receivedBytes":746,"referer":"","reporter":"source","requestId":"26930273-5a3a-97c4-8fc5-ff9782144c3g","requestSize":0,"responseCode":404,"responseSize":7510,"responseTimestamp":"2018-08-08T12:22:02.808866Z","sentBytes":8539,"sourceApp":"consumer-platform","sourceIp":"10.202.8.40","sourceName":"consumer-platform-7cddfcdd4d-wrqz2","sourceNamespace":"consumer-platform","sourceOwner":"kubernetes://apis/extensions/v1beta1/namespaces/consumer-platform/deployments/consumer-platform","sourcePrincipal":"","sourceWorkload":"consumer-platform","url":"/bacon","userAgent":"curl/7.54.0","xForwardedFor":"193.243.130.243, 127.0.0.1"}
```

We've seen this behaviour since 0.8, we're on 1.0 now.  Really not sure if we're doing something wrong of if it's a bug, but we're struggling to debug it.

We are forwarding these headers in each of our applications:

```
        addTracingHeader(ctx,"x-request-id");
        addTracingHeader(ctx,"x-b3-spanid");
        addTracingHeader(ctx,"x-b3-traceid");
        addTracingHeader(ctx,"x-b3-parentspanid");
        addTracingHeader(ctx,"x-b3-sampled");
        addTracingHeader(ctx,"x-b3-flags");
```
Any ideas?

Logging out headers from sauron-web, we see:

```
< x-request-id: 26930273-5a3a-97c4-8fc5-ff9782144c3j
< x-b3-parentspanid:
< x-b3-traceid: 243b1bf3ba539dd8
< x-b3-spanid: 243b1bf3ba539dd8
< x-b3-sampled: 1
< x-b3-flags:
```

Note, no parentspanid or flags

**Comment by Stono** [comment]
OK doing some more digging, if i set an arbitrary parentspanid on my curl: 

`curl -H "x-b3-parentspanid: 243b1bf3ba539dd8" -H "x-envoy-force-trace: true" -H "x-request-id: 26930273-5a3a-47c4-8fc5-ff9782144c3k" https://www-k8-gcp.autotrader.co.uk/bacon -v > /dev/null`

I get back a new parentspanid header:

```
< x-request-id: 26930273-5a3a-97c4-8fc5-ff9782144c3k
< x-b3-parentspanid: 0bc6593789b60492
< x-b3-traceid: 0bc6593789b60492
< x-b3-spanid: 63d8c3d812e9b3bf
< x-b3-sampled: 1
< x-b3-flags:
```

We *do not* use the istio ingress controller, which [i believe](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/third-party-addons/opentracing.md) would be setting these headers.  I've tried to enable opentracing in nginx, but theres currently this bug https://github.com/kubernetes/ingress-nginx/issues/2914

I do also think however that if envoy sees theres no parent-id, it should set one, rather than leaving it null?

**Comment by objectiser** [comment]
This seems strange, as usually if it was a propagation problem the two trace fragments would have a common service, one having the outbound client span, and the other starting with the inbound server span.

However your two trace instances doen't have a service in common - which means both the client span in the `consumer-platform` and the server span in `sauron-web` are missing.

Is there anything specific/different about the communication between these two services?

Can you try not specifying any headers - i.e. just do a single request and look for the spans in the UI, without specifying the `x-request-id`? If no trace appears (due to sampling), then just specify `x-b3-sampled: 1`.

**Comment by objectiser** [comment]
Another thing to check is whether the service ports are named correctly for `sauron-web` - see [Named ports](https://istio.io/docs/setup/kubernetes/spec-requirements/).

**Comment by Stono** [comment]
@objectiser they're all named correctly, based off the same template.  There is nothing specific about the comms between those two services no as again all our services are based off the same fundamental scaffold/template.

I haven't had time to dig into the issue more, but I will try your x-request-id suggestion some time early next week.

I find it weird how if i manually add a `-H x-b3-parentspanid: 243b1bf3ba539dd8` to the request it all works!  I'm actually going to get nginx (as we use that as an ingress point) to generate the parentspanid as soon as https://github.com/opentracing-contrib/nginx-opentracing/issues/52 is fixed.

**Comment by garethdown44** [comment]
After struggling with the lack of tracing reports in Jaeger for a long time, I realised that `pilot.TraceSampling` is set to 1. It needs to be set to 100 if you want to see traces for every request. It doesn't say to do this in any of the tutorials; it only mentions that you can reduce it if you wish.
