### ISSUE TITLE
helm enhancement: Add a loadBalancerSourceRanges helm option for Ingress Gateway Service

### ISSUE THREAD

**Issue by bzon** [istio/istio#7740]
**Is your feature request related to a problem? Please describe.**

When deploying istio with ingress gateway, there is no way to specify a `loadBalancerSourceRanges` through [helm options](https://istio.io/docs/reference/config/installation-options/). 

We need a way to put a  `loadBalancerSourceRanges` in the ingress gateway service template.

**Describe the solution you'd like**

I want to configure the service `loadBalancerSourceRanges` using helm options.

Taking the [nginx ingress controller service](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml) as an example:

```yaml
spec:
...
{{- if .Values.controller.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.controller.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
```

**Describe alternatives you've considered**

Modify the ingress gateway service manually to add `loadBalancerSourceRanges`.

**Comment by ymesika** [comment]
`loadBalancerSourceRanges` is a list of ranges. When you say:
> I want to configure the service loadBalancerSourceRanges using helm options.

Do you meaning setting it with the `--set` command flag? If so then I'm not sure it can accept a list value. Am I correct?

**Comment by bzon** [comment]
@ymesika yes you can. That is why I referred the nginx controller service template.

Even if you can, there is no way to add it as a value since https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/ingress/templates/service.yaml file does not have the template variable for it. 👍
