### ISSUE TITLE
add affinity to the ingress controller

### ISSUE THREAD

**Issue by zencircle** [istio/istio#7749]
**Describe the bug**
I am running Kubernetes with DC/OS and would like to install istio ingress on a public node 

**Expected behavior**
ingress controller pod should be installed on specific node.

**Steps to reproduce the bug**
Add  affinity rules to values.yaml file under ingress configuration

  affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - ingress
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        kubernetes.dcos.io/node-type: public
      tolerations:
      - key: "node-type.kubernetes.dcos.io/public"
        operator: "Exists"
        effect: "NoSchedule" 

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`
./kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ ./istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.
./helm install istio-1.0.0/install/kubernetes/helm/istio --name istio --namespace istio-system

**Environment**
Which environment, cloud vendor, OS, etc are you using?
AWS EC2, RedHat 7.2, DCOS 1.11.3, Kubernetes 1.10.6

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.
[istio-dump.tar.gz](https://github.com/istio/istio/files/2271941/istio-dump.tar.gz)

**Comment by kyessenov** [comment]
Dupe of #7330
