### ISSUE TITLE
"end-user" based routing not working with istio-1.0.0 for bookinfo application

### ISSUE THREAD

**Issue by ramkri123** [istio/istio#7755]
**Describe the bug**
Configured user-based routing as described in the Istio docs (https://istio.io/docs/tasks/traffic-management/request-routing/). The star ratings do not appear for use jason. 

**Expected behavior**
On the /productpage of the Bookinfo app, log in as user jason. Refresh the browser. What do you see? The star ratings appear next to each review.

**Steps to reproduce the bug**
Steps to reproduce the behavior.

Follow the instructions exactly as described in the Istio documentation
-- Setup Istio by following the instructions in the Installation guide. 
-- Deploy the Bookinfo sample application.
-- Configure request routing

**Version**
What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`

ramki@ramki-virtual-machine:~/istio-1.0.0$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

ramki@ramki-virtual-machine:~/istio-1.0.0$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.

Istio Auth is not enabled. Using stable istio.yaml as per the instructions.

**Environment**
Which environment, cloud vendor, OS, etc are you using?
-- Ubuntu 16.04 OS on VMware vSphere VM in a private cloud setup.
-- The entire k8S cluster is on a single VM.
-- K8S cluster uses flannel for networking.
-- Used Kubeadm for bringing up the kubernetes cluster.

**Cluster state**
If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.

Thanks in advance for all the help.
[istio-dump.tar.gz](https://github.com/istio/istio/files/2272209/istio-dump.tar.gz)

**Comment by ymesika** [comment]
I couldn't find the [default Bookinfo `DestinationRule`](https://istio.io/docs/examples/bookinfo/#apply-default-destination-rules) in your istio dump.
Please make sure you apply it.

**Comment by ramkri123** [comment]
Many thanks for the pointer. The issue is fixed.
