### ISSUE TITLE
Docker Swarm Support

### ISSUE THREAD

**Issue by Routhinator** [istio/istio#7777]
I don't see Docker Swarm support in the roadmap or mentioned in the docs anywhere, or in this repo. I see some Stack Exchange questions from 2017 indicating there were whispers of Itsio implementing swarm support in the future, but currently see nothing about it in the roadmap.

What's the status here, when can we expect Swarm support, if ever?

**Comment by BretFisher** [comment]
Chanwit (Docker Captain on twitter) may have some progress to share https://twitter.com/chanwit/status/1004155314109759488

**Comment by GregHanson** [comment]
@chanwit has anyone from Istio followed up on your tweet?  Did you have something WIP for a Docker Swarm adapter?  I contributed to most of the platform adapters in pilot so I would be willing to help or pick up where you left off

**Comment by chanwit** [comment]
@GregHanson Thank you for pining me.
What I have done so far has been based on Consul with Swarm service instances. Ideally, this feature should be using Swarm as the Service Registry. Pilot would be scanning the list of services from a Swarm manager, obtain a list of service instances and convert them to the Istio model.

I've been studying your Pilot codes mainly trying to fit the Swarm Service model to the Consul / Istio model. But I don't have much progress. It would be nice to be working with you guys to make this happen.

Here's my summary:
  *  My Istio proxy injection for Swarm is partially working so far. I intercept container events on every Swarm node and start a proxy container inside the same network namespace for each service instance. But a lot of testing is needed.
  * Ingress from 0.8.0 is working so far, but I haven't tried 1.0.x with Swarm yet.
  * The Swarm Service model does not fit well to the Istio model as the Service is an IPVS virtual IP. I'm still not sure how to properly convert it to be an Istio service.

**Comment by cmluciano** [comment]
@chanwit We can address the IPVS VIP by adding some logic to the init script to create the IPVS rule instead of an iptables entry. 

Once the one rule forwards into the sidecar, Envoy takes care of directing it to the desired endpoints. Beyond this entry, we do not need to continue programming iptables/IPVS like kube-proxy. 

That said, we would need to test to ensure that all features are properly working since there may be functionality that is expecting [TPROXY](https://www.kernel.org/doc/Documentation/networking/tproxy.txt) to be setup.

**Comment by idibidiart** [comment]
I guess support for Docker Swarm is not a high priority. Does the Istio team see Docker Swarm as a distraction? I find Swarm easier to setup and would love to play with Istio+Docker Swarm.

**Comment by diegoug** [comment]
I have a question, in the official site of Istio I saw that there is a docker installation guide, can this be used in swarm?

[Running on Docker with Consul or Eureka](https://archive.istio.io/v0.7/docs/guides/bookinfo.html#running-on-docker-with-consul-or-eureka)
[Quick Start on Docker](https://archive.istio.io/v0.7/docs/setup/consul/quick-start.html)
[Using Istio in a non-kubernetes environment](https://archive.istio.io/v0.7/docs/setup/consul/install.html)
[sample application](https://archive.istio.io/v0.7/docs/guides/bookinfo.html#running-on-docker-with-consul-or-eureka)

**Comment by xirius** [comment]
+1 for the support for Istio+Docker Swarm. Hope we will get it!

**Comment by Bluesboy** [comment]
I think whole Istio approach barely applicable to Swarm due to it's nature — there is no such thing as sidecar container in Swarm therefore you can't run Envoy with each replica of service.
