### ISSUE TITLE
Timeouts when creating istio custom resources on eks (bookinfo specifically)

### ISSUE THREAD

**Issue by empath** [istio/istio#7780]
**Describe the bug**
<sub><sup>A clear and concise description of what the bug is.</sup></sub>
```
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml  -n bookinfo
Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within allowed duration
```

**Expected behavior**
<sub><sup>A clear and concise description of what you expected to happen.</sup></sub>
It should create the resources.

**Steps to reproduce the bug**
<sub><sup>Steps to reproduce the behavior.</sup></sub>

Install istio 1.0 on eks and follow the bookinfo tutorial.  Creating the deployments and manual sidecar injection works, but creating the custom istio resources fails.

**Version**
<sub><sup>What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`</sup></sub>

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
 ~                                                          14:35:32  uye976
❯ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

**Is Istio Auth enabled or not?**
<sub><sup>Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.</sup></sub>
```
helm install --name=istio --namespace=istio-system install/kubernetes/helm/istio --set sidecarInjectorWebhook.enabled=false,grafana.enabled=true,kiali.enabled=true,tracing.enabled=true,servicegraph.enabled=true,gateways.istio-ingressgateway.type=NodePort,gateways.istio-egressgateway.type=NodePort
```

**Environment**
<sub><sup>Which environment, cloud vendor, OS, etc are you using?</sup></sub>
EKS, using weave cni.

**Cluster state**
<sub><sup>If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.</sup></sub>

**Comment by sdake** [comment]
This is likely because webhooks do not work on EKS.  See https://istio.io/about/notes/1.0/#known-issues-with-1-0

Try turning off galley.

Cheers
-steve

**Comment by ayj** [comment]
You can disable the validation webhook with the `--set global.configValidation=false` helm option.
