### ISSUE TITLE
Router instance can not run in host network

### ISSUE THREAD

**Issue by ibuildthecloud** [istio/istio#7792]
**Describe the bug**
Deploying a gateway instance of envoy proxy in the host network in kubernetes (HostNetwork=true) causes undeterministic behavior.  It appears that when building the configuration for the proxy the pod.IP is used as a key.  The pod.IP will be the node.IP and will not be unique so non-deterministic things happen.  In the end it just seems like the router is not getting updated.

**Expected behavior**
Host networking supported for gateways.  It just seemed like a waste to use ingress or service loadbalancer to get to my gateway, so I'd like to deploy in host network.  I can try host ports, but that means each time a port is changed I have to redploy the gateway.

**Steps to reproduce the bug**
Set HostNetwork=true on the gateway pod

**Version**
1.0.0

**Comment by kyessenov** [comment]
ref https://github.com/istio/istio/issues/1436
