### ISSUE TITLE
Implement rollout canarying between Pilot and Envoy

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#7794]
@ozevren @ayj @geeknoid @costinm @mandarjog @rshriram 

The suggestion here is to allow operators to control the set of Envoy's to which Pilot distributes configuration as a means to canary that configuration prior to rolling it out to the fleet.

A feature like this would have been very useful in some of the production outages we say with earlier iterations when broken Envoy configs were pushed aggressively.

As a strawman:
- Operator nominates a small % of workloads as canaries by labelling them
- Pilot tracks these workloads and pushes the latest merged configuration set to them
- If Envoy ADS NACKs these configurations or some other synthetic signal indicates that they are broken then pushing of changes to the rest of the fleet is stalled until the canarys ACK a config as safe
- If a config change is NACKed Pilot can provide a status update to Galley about the resources in the delta between the last known good state which Galley can surface to the user in a variety of ways

In the future when we provide support for HDS in Pilot we can support a richer synthetic definition of Envoy health to make the canarying robust. We can also support an outside healthchecker via an API if needed.

This proposal gives operators a lot of control over the scale and locality of their canarying which they will likely find appealing.

This proposal also proposes an interaction between Galley and Pilot that involves a feedback loop about resource status which merits a deeper discussion.

**Comment by ozevren** [comment]
We can expand the MCP protocol (or create a sister one, perhaps using the same connection) to add a finer-grained and asynchronous status/error reporting path, through which Pilot can report back.

**Comment by ayj** [comment]
> Operator nominates a small % of workloads as canaries by labelling them

gateway has a [scoping selector](https://github.com/istio/api/blob/fe4a677a40364b439ecc29cfb22513edb8ff9625/networking/v1alpha3/gateway.proto#L161). Would a similar scheme work for VirtualService and DestinationRule? As a first pass, user could be responsible for updating/removing the selector after they're satisfied the canary was successful (e.g. by monitoring metrics). Pilot doesn't need to wait for anything. 

An status feedback mechanism would be generally useful (see [reporting merge conflicts](https://github.com/istio/istio/issues/7793)). 

> a simple 'report back to Galley' won't work, there are multiple
pilots each connected to possible multiple Galley replicas and other config
providers that would also need similar reporting.

We don't need to do anything that complicated here. A galley replica could pass through a pilot replica's status directly to the CRD status subresource index by the pilot's identity. We'd need some GC to clean-up stale pilot pod references, but this wouldn't rely on shared/consistent global state across replicas.

**Comment by costinm** [comment]
Reopenning - it is still an important feature to add.

**Comment by howardjohn** [comment]
still important

**Comment by thinkin** [comment]
> The basic canary is relatively easy - we have the endpoint labels, easy to push first to canaries

it's very . it means  every endpoint shoulid has label
for example. in a Service A which access service B, some endpoints have label (tag: test)，but other endpoints don't have label tag；it's very difficult to achieve canary for endpoints which have label tag=test

`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: B-virual-service
spec:
  hosts:
  - test.service.B
  tcp:
  - match:
    - sourceLabels:
        app: A
        tag: test
    route:
    - destination:
        host: test.service.B
        subset: subset1
  - match:
    - sourceLabels:
        app: A
    route:
    - destination:
        host: test.service.B`

Service A endpoints which have label tag=test will match two subset(subset1、subset2)，so i think the most simple solution is “sourceLabels support the best match”
in this case，Service A endpoints which have label tag=test only match the subset1（not subset1 and subset2）

**Comment by thinkin** [comment]
@howardjohn @costinm

**Comment by howardjohn** [comment]
not stale

**Comment by ramaraochavali** [comment]
not stale

**Comment by shimengwang** [comment]
@howardjohn  I see that this issue has been marked as done under Prioritization. Will this issue no longer be supported in the future?

**Comment by howardjohn** [comment]
That is just a side effect of migrating the project from projects v1 to v2, not done by a human
