### ISSUE TITLE
istioctl proxy-status <pod> should print update time

### ISSUE THREAD

**Issue by esnible** [istio/istio#7805]
It would be helpful when troubleshooting Envoy proxy config problems to know if Pilot attempted to inform Envoy of a change in configuration.  (This came up during tests around Issue #7787 Envoy acked everything, but the routes were not in sync.  I assume Pilot didn't try to sync, but I am uncertain)

The `istioctl proxy-status <pod>` command currently prints
```
Routes Match
```

or

```
+++ Envoy Routes
<huge diff output>
```

I would like it to say
```
Routes Match (RDS sent on Fri Aug 10 09:29:27 EDT; SYNCED)
```

or

```
Routes DON'T MATCH (RDS sent on Fri Aug 10 09:29:27 EDT)
+++ Envoy Routes
<huge diff>
```

These changes will make it easy for both humans and scripts to see if Pilot noticed a change.

**Comment by venilnoronha** [comment]
Where do you get `Fri Aug 10 09:29:27 EDT` from? Is it the latest of the [`LastUpdated`](https://github.com/istio/istio/blob/405f47f54d19e6d998aa3e863ec9e2bc23c157f1/istioctl/pkg/util/configdump/route.go#L38) values from the `DynamicRouteConfigs` on `envoy`?

**Comment by esnible** [comment]
I was hoping to get the times from the push/ack that Pilot sends to the Envoys.  @liamawhite will know if it is possible and how to implement it.

**Comment by liamawhite** [comment]
It would have to be the last updated from dynamic route configs, although this would require looping through each dynamic route config and keeping the most recent. You could also call the syncz endpoint on all Pilots but this will be much slower unless you only have one Pilot.

It would have to be `RDS last loaded at ...` if coming from Envoy, and we wouldn't be able to get the sync status.

**Comment by venilnoronha** [comment]
@liamawhite thanks for the details. I'll give it a try.
