### ISSUE TITLE
Race test failure: testadsreconnectwithnonce 

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7808]
https://k8s-gubernator.appspot.com/build/istio-circleci/racetest/154203#istioioistiopilotpkgproxyenvoyv2-testadsreconnectwithnonce

**Comment by hzxuzhonghu** [comment]
The Config.Spec is an interface, so I think we can clone it in `initVirtualServices` before we mutate it.

 ```
type Config struct {
	ConfigMeta

	// Spec holds the configuration object as a protobuf message
	Spec proto.Message
}

```
