### ISSUE TITLE
 Updating release version for DM template

### ISSUE THREAD

**Issue by jasminejaksic** [istio/istio#7820]
Currently the DM template needs to be manually updated every-time we have a new release, however this is not on anyone's radar and it's not efficient. We need to figure out 1) a way to automate release version so DM points to latest and greatest 2) Incorporate this into ete testing (preferably automated)

**Comment by hklai** [comment]
/CC  @salrashid123

I think we need to update this line for every LTS release.
https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.yaml#L20

However, I see some more substantial change in the past (e.g. https://github.com/istio/istio/commit/9d406f0fdb9a7de20b227cd064dc894306069cba#diff-d764556de0ab3729c898977dd8b12ab2) and I don't think we can automate more than the one line change in the yaml file.

**Comment by salrashid123** [comment]
yeah, the current DM template looks for the version specified in the schema values here as ```installIstioRelease```

* [istio-cluster.jinja.schema](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja.schema#L46)
* [istio-cluster.yaml](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.yaml#L20)

and then downloads that file to untar an install here:
 - [istio-cluster.jinja](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja#L93)

so unless the actual istio install flow changes, it should be a matter of updating that variable (by changes i mean helm variables, where the .tar.gz for istio is found, etc)

@hklai   all  those changes were actually originally added in back on the  ```0.8``` branch.  It never made it to `master` so when ```1.0.0``` was cut, i had to 'reapply'  all those changes in.   I'd suggest merging the dm stuff thats currently in `1.0.0` into `master` so the changes moving forward don't look like i'm changing a ton of stuff:

i had a PR to do that which i abandoned though:
  https://github.com/istio/istio/pull/7237

**Comment by salrashid123** [comment]
@hklai  neverminds.  `master` has the latest set of changes in it already for `1.0.0`
- [https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja#L79](https://github.com/istio/istio/blob/master/install/gcp/deployment_manager/istio-cluster.jinja#L79)

i didn't see any branch for any followup release so when you're ready to cut one for the next release, it should be a matter of changing the variables cited above.  Alternatively, if i can download istio from a url like:
https://github.com/istio/istio/releases/download/{{ properties['installIstioRelease'] }}/istio-{{ properties['installIstioRelease'] }}-linux.tar.gz

where `installIstioRlease=latest`  

and the helm config is the same, i can just make the DM template use that and remove the per-release version in the config file  and url dependency.  i'm fine eitherway.

**Comment by ldemailly** [comment]
bt the way the issue isn't exactly new, and this was supposed to be a temporary thing:

https://github.com/istio/istio/pull/1861#pullrequestreview-79358216

**Comment by ldemailly** [comment]
example of a script that downloads the latest release marked as not a pre release
https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh
