### ISSUE TITLE
Q: how to deploy mixer such that services in a namespace always goes to particular mixer deployment set.

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#7822]
Q: 
Can we have namespace level isolation for mixer check call ?
eg. services in prod namespace and e2e namespace should hit 2 different set of mixers ?

**Comment by kyessenov** [comment]
Mixer destination is decided based on mesh-level config. We would need namespace-scoped override for the mesh config.
/cc @ozevren , the config TL

**Comment by ayj** [comment]
@ostromart and I were discussing namespace scoped sidecar injection configuration via a CRD, e.g. to allow for more incremental and controlled updates. A similar idea could work for the mesh configuration. 

Some considerations:

- The CR could live in the application namespace or `istio-system` with a name that corresponds to the application namespace. 
- We'd probably want to retain the default CR in case the app CR is absent. 
- To avoid a direct k8s dependency, Pilot shouldn't consume the CR directly. Instead if should either receive the equivalent from a file (configmap) or MCP.

**Comment by ozevren** [comment]
@mandarjog @geeknoid @douglas-reid 
Any comments from Mixer perspective? Are there any plans or already existing mechanisms for traffic sharding currently?

**Comment by mandarjog** [comment]
Mixer will use eds to do such a thing.
When a workload can be directed to use a specific mixer by pilot based on workload metadata like namespace.

I am planning to do the same for canarying a new mixer binary.

**Comment by mandarjog** [comment]
@douglas-reid and I have talked about using maglev to prefer particular endpoints.

**Comment by arghya88** [comment]
@mandarjog Can you share an example of how to configure envoys in a namespace send metrics to a specific mixer

**Comment by ozevren** [comment]
@mandarjog With the current Mixer V2 plan, is this issue obsolete?

**Comment by douglas-reid** [comment]
Closing, as i believe this issue was OBE and will not be addressed in the existing architecture.
