### ISSUE TITLE
May not be able to view metrics when sharding prometheus

### ISSUE THREAD

**Issue by k** [istio/istio#7823]
**Describe the bug**
When increasing the `replicaCount` of prometheus [link to values](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L415) the grafana instance will not necessarily be able to pull the data because each prometheus pod's data is not shared with the others. (see default [local storage](https://prometheus.io/docs/prometheus/latest/storage/#local-storage))

**Expected behavior**
I would expect if I increase the `replicaCount` to be able to access the same data from every prometheus pod.

**Steps to reproduce the bug**
install the helm chart with prometheus + grafana enabled and set the `replicaCount` of prometheus to something large like 10.

**Version**
#### istio with helm
`istio           	10      	Thu Aug  9 17:20:03 2018	DEPLOYED	istio-1.0.0           	1.0.0      	istio-system`
branch `release-1.0`

#### kubectl
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No

**Environment**
aws kubernetes with kops

**Cluster state**
I don't believe this is necessary

**Potential Solution**
Have a default remote time series db that is shared among the prometheus pods. See [Remote Storage Integrations](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations)

**Comment by douglas-reid** [comment]
For the most part, Istio has provided relatively simple example configurations and deployments for the add-ons (such as Prometheus). We have not attempted, to-date, to focus on improving the robustness or general scalability of the add-ons. That being said, we would love to have community contributions around this issue.

For Prometheus itself, there is a FAQ about running HA prometheus here: https://prometheus.io/docs/introduction/faq/#can-prometheus-be-made-highly-available.

> Yes, run identical Prometheus servers on two or more separate machines.

This recommended approach would seem to be inline with multiple replicas of Prom running with the same config, perhaps with the difference being around independent addressability.

There was an issue tracking HA on prometheus here: https://github.com/prometheus/prometheus/issues/1500. It had similar recs.

I think the trick would be getting Grafana to not ping back and forth across the multiple replicas (to ensure you aren't seeing data bounce across collection times, etc.).

There is some discussion here: https://community.grafana.com/t/recommended-ha-setup/1526/13.  I believe grafana has some support for sticky sessions, though I have not tested it nor am I aware of its limitations.

**Comment by k** [comment]
@Douglas-reid thanks for pointing me to the relevant info. For now it seems single Prometheus instance will serve my need (it’s  supposed to support up to roughly 1000 servers I read online), but in the future if I need to revisit I can modify.
