### ISSUE TITLE
Unable to access my application when using istio ingress and put in a non-root path

### ISSUE THREAD

**Issue by linsun** [istio/istio#783]
Here is my app:  https://github.com/IBM-Bluemix/investment-insights-for-asset-managers

When I try to run it, I can always access it via k8s node port.  When I try to access via istio ingress, it works with this configuration:

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: investment-insights-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: investment-insights-ux
          servicePort: 6001
```

however, if i choose to put it under /investment, not /, like:

`      - path: /investment/.*`

It stops working.  curl {istio-ip}/investment returns the right source, but curl {istio-ip}/investment/js/app.js doesn't return property app.js code.

**Comment by rshriram** [comment]
Cc @kyessenov

**Comment by ldemailly** [comment]
related: I don't see the translated path in the envoy access log

also we need to improve the doc as it's not clear at all what happens with  path: /foo/.*

if I call /foo/A/B does it mean it goes to svc as /A/B (which I'd like) or something else ?

**Comment by ldemailly** [comment]
looks like you'd need to use
https://istio.io/docs/reference/config/traffic-rules/routing-rules.html#istio.proxy.v1.config.HTTPRewrite

but I'm still trying to get it to work

**Comment by ldemailly** [comment]
I've put details of my issue in https://github.com/istio/pilot/issues/1288

**Comment by ldemailly** [comment]
do you still have this issue with 0.2.6 and validated ingress rules
https://github.com/istio/istio/blob/db873c2189b23a03b5176c04308abf8f577a501b/tests/e2e/tests/simple/servicesToBeInjected.yaml#L42
may help

will close but reopen if you still have issues
