### ISSUE TITLE
Merge istio/proxy into istio/istio

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#7841]
With the monorepo merge, we have left behind istio/proxy repo. The process to update the proxy SHA is entirely manual, which leads to constant problems with commits to the proxy breaking integration tests in istio/istio. The more recent example is https://github.com/istio/proxy/issues/1910. There are three distinct changes in the proxy (JWT, mTLS, proxy error code), for which there were no follow ups to fix the corresponding tests in istio/istio. This means that the next unfortunate soul to try to update the proxy is left to fix multiple test failures and integrate all the changes made.

The side-effect of the monorepo is that we have lost the machinery to run cross-repo tests. There is currently no way to indicate istio/istio test failures during the PR process in proxy. I think the reasonable thing to do at this point is to finish the move, and merge the istio/proxy repo into istio/istio. 

There are a few simple arguments against this:
- proxy is bazelified, OMG bazel is back: not a problem since bazel ignores non-bazel directories and go ignores bazel directories; go hackers can continue to be blissfully unaware of bazel existence.
- proxy needs api: we already vendor api repo, so it's one less dependency tracking problem actually;
- proxy build is slow: given that istio/istio e2e tests are significantly longer, I think we can tolerate one more parallel job in istio/istio;
- istio tests are slow: this is a cost no matter if it is done by bumping the SHA or making changes to the repository directly.

Thoughts?
cc @hklai @qiwzhang @lizan @JimmyCYJ @diemtvu

**Comment by costinm** [comment]
No way. We are trying to do the opposite, and move pilot (and maybe other components) to a separate repo. We moved to single repo because of Bazel SHA craziness.

There are other ways to test and update proxy.

**Comment by kyessenov** [comment]
> No way. We are trying to do the opposite, and move pilot (and maybe other components) to a separate > repo. We moved to single repo because of Bazel SHA craziness.

Yes, this is trying to get rid of `istio.deps` file with hard-coded proxy SHA. It's clearly not a viable process as we continue to fail to update the dependency SHAs.

**Comment by kyessenov** [comment]
@rshriram I heard some offline objection to this, do you mind documenting it here, so I can improve my proposal?

**Comment by PiotrSikora** [comment]
I agree with @kyessenov that the current situation is pretty terrible, because person updating the Proxy is almost always going to run into changes made in `istio/proxy`, for which the corresponding changes where not made in `istio/istio`, which results in a lot of time spent on reverse engineering original changes and updating the tests. However, this could be also solved by requiring @istio/proxy-hackers to immediately push `istio/proxy` changes to `istio/istio`.

On the other hand, control plane and data plane shouldn't be tied too closely together, in order to keep the changes backward- and forward-compatible, otherwise we're going to lose the ability to update them independently. Pilot should (must, really!) be able to work fine with Proxy vN-1, vN and vN+1, at the very least. That most likely doesn't work right now, but keeping them separate at least gives the illusion that we're working towards that.

**Comment by kyessenov** [comment]
Thanks for your feedback. My main concern is (1) lack of an enforcement mechanism to mandate a sequence of two PRs, (2) merging partially finished features into proxy that may block other istio features.  

For (1), if you ask them, all the leads have been continually coercing proxy hackers to make appropriate update to istio/istio. That does not appear to be effective, as we have seen multiple times. Once the pattern establishes itself, and proxy is no longer in sync with istio, it is difficult to fix forward.

For (2), cross-cutting features, such as adding a new mixer attribute are difficult to stage since that requires changes across all of istio repos. Too often, it is not done to completion (missing integration test, missing documentation, missing vocabulary change, etc). With fewer repos, it is easier to see the whole effect of the feature on the code (but still missing docs and APIs, of course), and easier to spot and test for incomplete PRs.

**Comment by ldemailly** [comment]
[maybe a tangent] Wasn't it decided to move api into istio first (and auto re-export) as api is another (major) source of out of sync and multi PR/vendor update ? or something changed since then ?

**Comment by kyessenov** [comment]
@ldemailly This is true, see https://github.com/istio/istio/pull/7545. There are two parallel efforts. The challenge with API is running the sync. There is no sync necessary for proxy.

**Comment by JimmyCYJ** [comment]
Currently when we commit a PR, the proxy-postsubmit job builds proxy image with the changes made in that PR. This job takes over one hour to finish, and we cannot update istio.deps before that. Normally people does not update istio.deps right after the proxy-postsubmit job completes. Therefore every time people update istio.deps, it always contains multiple commits made in proxy repo. If any commit breaks an e2e test in istio, that normally takes a long time to identify the problematic commit.

**Comment by kyessenov** [comment]
Keep it open

**Comment by ldemailly** [comment]
api isn't getting moved after all so I suppose this one will continue in limbo/manual update hell too ?

**Comment by howardjohn** [comment]
I don't think this is still planned given we are moving other components out of istio/istio now? Feel free to reopen if thats not accurate @kyessenov
