### ISSUE TITLE
Prometheus service url is not configurable in kiali helm chart

### ISSUE THREAD

**Issue by acartapanis** [istio/istio#7848]
**Describe the bug**
prometheus service url is not configurable in kiali helm chart :
https://github.com/istio/istio/blob/eb6f9ef9e0c77585399de870cde5eae34d45175b/install/kubernetes/helm/istio/charts/kiali/templates/deployment.yaml#L52
Note that grafana or jaeger url are configurable.

**Expected behavior**
As i use my own prometheus deployment and not the one provided by the chart, the prometheus URL must be configurable

**Version**
istioctl version :
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
kubectl version :
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gbaufake** [comment]
@acartapanis Addressed your concern on #8909
