### ISSUE TITLE
Release notes for 0.2

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#787]

**Comment by sakshigoel12** [comment]
https://istio.io/docs/reference/release-notes.html

**Comment by sakshigoel12** [comment]
Raw release -- people should update PRs
Website -- maybe early next week

**Comment by ldemailly** [comment]
from a mechanics point of view, the raw/detailed notes go [here (wiki)](https://github.com/istio/istio/wiki)

the high level rel notes for the website I thought we had a task already but I can't find it so adding sven and louis for that one (and removing myself)

**Comment by geeknoid** [comment]
I'm going to put the notes together in the next few days.

**Comment by smawson** [comment]
Let me know if you need anything from me, I was going to be doing some docs this weekend.

**Comment by geeknoid** [comment]
PR is now outstanding for this.

**Comment by geeknoid** [comment]
Done.

**Comment by ldemailly** [comment]
https://istio.io/docs/reference/release-notes.html is live, thanks
