### ISSUE TITLE
statsd prometheus bridge is gradually OOMing

### ISSUE THREAD

**Issue by Stono** [istio/istio#7873]
**Describe the bug**
statsd bridge is gradually using up more and more memory, please see the graph on the top right which shows the last 7 days.

<img width="1673" alt="screen shot 2018-08-13 at 19 55 48" src="https://user-images.githubusercontent.com/1486729/44051870-f9df33c8-9f32-11e8-818d-21180718dfe3.png">

Istio 1.0, k8 1.10.5

**Comment by nmittler** [comment]
@douglas-reid do we have an owner for this?

**Comment by douglas-reid** [comment]
@nmittler not really. Istio doesn't really have a story for containers/processes we don't own. We are working towards a joint solution for replacing the need for this piece, but we don't have any  short-term fixes for the issue planned.

Interestingly, there is this issue on the source repo: https://github.com/prometheus/statsd_exporter/issues/76. The original suggestion there is to run an instance per node:

> The general recommendation is to run one exporter per node, and configure all apps to send to localhost. This allows for easy scaling and eliminates the exporter as a SPoF.

We could alter our deployments to do that in the short-term.

I'm not convinced that that does anything other than delay the issue, but I haven't spent much time investigating.  That issue remains open.

**Comment by douglas-reid** [comment]
This issue is no longer needed. the statsd bridge was deprecated and is no longer recommended.
