### ISSUE TITLE
Filesystem watch code should take symlinks into account

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7877]
fsnotify/fsnotify#199, spf13/viper#284

The filesystem watcher code we use does not play well with certificates that are exposed as sym-links. Specifically, the library we depend on follows symlinks when watching.

Worse, one-off handling of this kind of code is dispersed in various areas of our code. Ideally we should have a single library that can take care of all the quirks and simplify the common usage patterns that we have in Istio.

Marking this as config, as it looks like we're hitting this issue primarily in the config area.

**Comment by Stono** [comment]
@ozevren is this associated https://github.com/istio/istio/issues/7872 ?

**Comment by lichuqiang** [comment]
I would like to help with this, but I think I need to make clear the requirement first.

Besides the symlinks issue, have we got any requirement that specific to istio (i.e. the istio common usage patterns described above)?

**Comment by ayj** [comment]
We basically need a wrapper around fsnotify that handles symlinks properly for k8s secrets/configmaps. 

It would also be useful to have a [fake implementation](https://github.com/istio/istio/blob/9c6c2130809e3d88936c960ed5c8f5490616440f/pkg/mcp/creds/watcher_test.go#L34-L59) for testing purposes.

```golang
type Watcher interface {
    Add(path string) error
    Remove(path string) 
    Close() error
    Events() chan fsnotify.Event
    Errors() chan error    
}

func NewWatcher() (Watcher, error) {}
func NewFakeWatcher(Watcher, error) {} // for unit tests
```

The simplest option might be to maintain one `fsnotify.Watcher` per watched path/file. Each watcher would watch the parent directory of it's own target filename. Channel events/errors are send *if* the modified file matches the target filename for that particular watcher. 

This retains the existing `fsnotify.Watcher` interface (good) at the expense of dedicated watcher for each file (bad?). In practice, we don't watch that many files and that number should go down when SecretDiscoveryService (SDS) replaces k8s secrets for cert/key distribution.

**Comment by lichuqiang** [comment]
> The simplest option might be to maintain one fsnotify.Watcher per watched path/file. Each watcher would watch the parent directory of it's own target filename.

Yeah, this should be the simplest approach. I tried to create a watcher from scratch to address the `IN_DONT_FOLLOW` issue, but the fact that the watcher should have cross platform support bothered me.

**Comment by lichuqiang** [comment]
> Channel events/errors are send if the modified file matches the target filename for that particular watcher

I did some investigation on the issue. For k8s secrets/configmaps files, we can not see the target file path in result events, for the target file is symlink to files under `..data` path, and system operates the `..data` instead:
```
root@redis:/# ll /test-configmap/
total 12
drwxrwxrwx 3 root root 4096 Oct  3 10:37 ./
drwxr-xr-x 1 root root 4096 Oct  3 10:35 ../
drwxr-xr-x 2 root root 4096 Oct  3 10:37 ..2018_10_03_10_37_03.231628406/
lrwxrwxrwx 1 root root   31 Oct  3 10:37 ..data -> ..2018_10_03_10_37_03.231628406/
lrwxrwxrwx 1 root root   16 Oct  3 10:35 test.conf -> ..data/test.conf
```
Here the target file path is supposed to be "/test-configmap/test.conf", but when I update the configmap, it only watched events like these:
```
watched event: "/test-configmap/..2018_10_03_10_44_01.662174045": CREATE
watched event: "/test-configmap/..2018_10_03_10_44_01.662174045": CHMOD
watched event: "/test-configmap/..data_tmp": RENAME
watched event: "/test-configmap/..data": CREATE
watched event: "/test-configmap/..2018_10_03_10_37_03.231628406": REMOVE
```

So for secrets/configmaps files, I'm afraid we'll have to trigger an update for all the events, without matching its file path. @ayj thoughts?

**Comment by ayj** [comment]
@lichuqiang, are you still planning to work on this issue?

> For k8s secrets/configmaps files, we can not see the target file path in result events ...

Right, that's why I suggested creating one watcher per file and re-adding the watch on delete. It's a bit wasteful but we don't plan on watching a large number of files per processes anyway. Alternatively, you could watch the parent directory of the file and use a checksum of the file contents to determine which file(s) changed.

**Comment by lichuqiang** [comment]
> are you still planning to work on this issue?

Yeah, sorry that I’ve been away for a while, and just came back. I'll post an implementation for this soon.

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/9370 added a new package to support file watchers.
https://github.com/istio/istio/pull/9622 updated galley server to use the new package.
