### ISSUE TITLE
1/4 istio-pilot instances getting basically no load

### ISSUE THREAD

**Issue by Stono** [istio/istio#7878]
**Describe the bug**
Deploying 4 replicas of istio-pilot, three appeared to start up without issue but one is seemingly doing nothing.  This was observed because 3/4 pilots were running at 100-150% CPU and this one is at 5%.

CPU from this pilot:
<img width="801" alt="screen shot 2018-08-13 at 20 55 22" src="https://user-images.githubusercontent.com/1486729/44054699-3ed5fefa-9f3b-11e8-8b52-0bb6e9336271.png">

CPU from (basically all other 3) pilots:
<img width="820" alt="screen shot 2018-08-13 at 20 56 32" src="https://user-images.githubusercontent.com/1486729/44054769-696f4004-9f3b-11e8-840e-830b846e6371.png">

Logs from the unutilised pilot, basically empty.  This pilot has been up for 12 minutes.
```
❯ kis logs istio-pilot-6545f69d9b-dpkx2 discovery
2018-08-13T19:42:59.603297Z     warn    Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

When i restarted this pod, it came back up and started churning like the others.  Not really sure what other logs I could provide here or how to help you debug this, especially as I can't seem to reproduce it now.  So I guess this is just more FYI than anything else...

**Comment by costinm** [comment]
I've seen this few times - it's a bit tricky to solve, but the cause is simple: envoy uses pilot VIP, which resolves to a set of endpoints. Pilots don't show up all at once - so one pilot will show up first, followed by another, etc. The sooner a pilot starts  - more envoys will connect to it.

For normal http services - it's fine, future request will be balanced. For pilot - it is not because the connections are very long lived, once an envoy connects to a pilot it'll stay connected. In time things will smooth out ( as envoys get restarted/reconnected ). 

We could add a config to pilot to shed requests once a certain limit is reached - for example a deployment with 10k endpoints could have 2000 limit per pilot, and each pilot will reject additional requests. User would need 6-7 pilot replicas, and each pilot will handle 2000 endpoints and no more. It's the only simple solution I know.

**Comment by Stono** [comment]
Hmmm this is interesting then, as you've got HPA enabled as of 1.0, but really HPA isn't going to help a whole lot in the short term as you'll scale up a pilot but everything will have persistent connections to the other pilots until as and when envoys redeploy.  It's actually going to be much better for us to pick a static number of pilot instances based on informed decisions about how much load each pilot could handle vs rough expected number of endpoints, and disable HPA.

**Comment by louiscryan** [comment]
@PiotrSikora @hutch 

Thoughts here? We can try to have Pilot load shed or we can configure Envoy to timeout connections so it naturally rebalances it's traffic. My concern with the latter is that if Envoy reconnects for ADS whether it would go through a lot of churn of config state even though the Pilot it connected to was essentially a replica of the one it got migrated away from.

**Comment by rshriram** [comment]
alternatively, if we did dns srv in envoy, and then randomized the list in envoy before picked one, we should get an even load distribution across pilot instances.

**Comment by Stono** [comment]
@rshriram not sure how that would help dealing with existing load which holds a persistent, long lived connection to pilot?

**Comment by louiscryan** [comment]
@rshriram I don't think that works well enough. If HPA brings up a new Pilot to meet load we wouldn't rebalance existing connections over to it.

Options here are:
1. Edge-trigger for load shedding as Pilot knows when a new instance of Pilot is added to the endpoints. Pros: Quick response. Cons: Thundering herd risks
2. Have a max-age mechanism for connections between an Envoy and Pilot and allow gradual tenuring to smooth the load across Pilots over time. Pros: Not edge dependent. Cons: Slow

In either case we will have an issue when an Envoy instance is kicked over to another Pilot how much intelligence it has about avoiding a full reload of its configuration state. Ideally Envoy would be able to know that a rebalancing here could be treated as a continuation of the same configuration stream. Some thought will have to go into that otherwise we could get some pretty undesireable behavior.

**Comment by louiscryan** [comment]
@Stono For context. We believe we have optimized the CPU & garbage collection aspects of Pilot so that it has a significantly lower overhead, thereby making working with HPA less of a priority. Hence the priority of P1 instead of P0.

**Comment by Stono** [comment]
@louiscryan that makes sense

**Comment by ayj** [comment]
> we will have an issue when an Envoy instance is kicked over to another Pilot how much intelligence it has about avoiding a full reload of its configuration state. Ideally Envoy would be able to know that a rebalancing here could be treated as a continuation of the same configuration stream.

[Incremental xDS](https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md#incremental-xds) may help here if Pilot uses consistent per-resource versioning.

**Comment by Stono** [comment]
Hello @ayj @louiscryan I would like to rekindle this because it's becoming more of a problem for us.

Take the following situation:

Two istio-pilot pods, which have overtime (lets say a few weeks) had all the proxies evenly balance over them.

Lets say, for argument sake, they're sitting at around 60-70% capacity each.  

Now; when we have come to do a rolling deployment of istio-proxy today, those two pods have been updated one by one and what we have ended up with is a one pod trying to deal with 120-140% of the load, and the other basically doing none.

Pod1:
<img width="1618" alt="screen shot 2018-10-24 at 14 03 55" src="https://user-images.githubusercontent.com/1486729/47432435-07c1ae80-d796-11e8-87b9-34f6a604f957.png">

Pod2:
<img width="1623" alt="screen shot 2018-10-24 at 14 04 03" src="https://user-images.githubusercontent.com/1486729/47432444-0bedcc00-d796-11e8-87f9-96a29b0c199a.png">

The only way we've found to resolve this problem is to manually trigger a restart of every istio-proxy pod on the mesh which causes other problems (restarting 100s of apps....).

We really need a better solution to this please!

**Comment by mandarjog** [comment]
I am looking at both those things as part of scalability.
Pilots sending disconnects when they are over subscribed and they know that other pilots are around.

The custom metric auto scaling also works but the above will make it such that cpu based hpa may do just fine.

How many pods are in your deployment?

**Comment by Stono** [comment]
For others working on this, this super hacky way of deploying proxy helped us:

`kubectl --namespace=istio-system patch svc istio-pilot -p "{\"spec\":{\"selector\": {\"istio\": \"pilot-deploying\"}}}"`

`.... deploy istio`

`kubectl --namespace=istio-system patch svc istio-pilot -p "{\"spec\":{\"selector\": {\"istio\": \"pilot\"}}}"`

@mandarjog at the moment the above cluster is:

  - pods: 320
  - services: 147

**Comment by Stono** [comment]
This is becoming more of a problem for us now... we run two instances of pilot, during a node upgrade, one of the pilots will terminate and *all* connections will go onto the other.  Then, the second one will terminate and *all* connections go onto the second one.  Leaving everything wildly imbalanced.

We've gone down the route of writing customer prometheus metrics which monitor `istioctl proxy-status` and output metrics like this:

```
# HELP ipe_pilot_proxy_imbalanced A gauge which represents if the proxies to pilots ratio is imbalanced
# TYPE ipe_pilot_proxy_imbalanced gauge
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-645679fc85-txt66",proxies_connected="22",percentage_target="50",percentage_connected="56.41025641025641"} 0
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-645679fc85-rgvpt",proxies_connected="17",percentage_target="50",percentage_connected="43.58974358974359"} 0
```

If the `percentage_connection` is +/- 20% of the expected even distribution the metric is `1`, and then in that scenario, we run this script which rebalances the proxies:

```
if kubectl --namespace=istio-system get svc istio-pilot &>/dev/null; then
  kubectl --namespace=istio-system patch svc istio-pilot -p "{\"spec\":{\"selector\": {\"istio\": \"pilot-deploying\"}}}"
  sleep 3
fi

# Restart pilot
kubectl -n istio-system patch deployment istio-pilot -p \
  "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"RESTARTED_ON\":\"`date +'%s'`\"}}}}}"
kubectl -n istio-system rollout status deployment/istio-pilot

# Patch it back so things can connect to pilot
if kubectl --namespace=istio-system get svc istio-pilot -o yaml | grep "pilot-deploying" &>/dev/null; then
  sleep 3
  kubectl --namespace=istio-system patch svc istio-pilot -p "{\"spec\":{\"selector\": {\"istio\": \"pilot\"}}}"
fi
```

Majorly hacky...

**Comment by rshriram** [comment]
So it seems the default load balancing mode in all proxies towards Pilot is set to RoundRobin!!! 
https://github.com/istio/istio/blob/dce455456d77ca5af34ba5848f9704577349c6bd/tools/deb/envoy_bootstrap_v2.json#L93

If you are interested, see if you can replace this with RANDOM. That should effectively redistribute load.

**Comment by rshriram** [comment]
hmm.. ignore.. it shouldn;t make any difference because we are using Pilot's clusterIP. So, the fault is at Kubernetes level really.

**Comment by Stono** [comment]
@rshriram yeah k8s does round robin load balancing that's true, I wouldn't say "fault" is the right word... it's how kubernetes works so should be a consideration of istio at scale.  Perhaps pilot should reject connections if it's wildly imbalanced, or reject connections with a message like "connect to this pilot instead x.x.x.x"

**Comment by Stono** [comment]
Hey folks, 
would be good to know if this is getting any focus in 1.1+, currently horizontally scaling is a bit of a lottery and if people end up with a very overloaded pilot, they have slow pushes and thus outages.

**Comment by munrodg** [comment]
@ZackButcher can you take a look at this issue.

**Comment by duderino** [comment]
@costinm @rshriram @frankbu how would you go about implementing this one too?

**Comment by ja30278** [comment]
In fact, it seems like this could be done internal to the connection servicing loop, and looks like a relatively non-invasive change (see the WIP PR).

**Comment by ja30278** [comment]
(actually, I see this was proposed earlier in the thread, but raised the possibility of unwanted churn)

**Comment by elevran** [comment]
in order to create a more balancing connection distribution, Envoys would need to reconnect. This can be forced entirely by Pilot, by Envoy or by some cooperative measure.

- A Pilot only solution could use [keepalive.ServerParams.MaxConnectionAge](https://github.com/grpc/grpc-go/blob/bd0b3b2aa2a9c87b323ee812359b0e9cda680dad/keepalive/keepalive.go#L59)
- similarly, Envoy could force a reconnect as suggested in #10838 (unilaterally or based on server provided duration in xDS calls)

Both of these are time based and do not account for the current load. They are good short term workarounds, IMHO. 
A longer term solution (beyond 1.1) could possibly monitor the Pilot service endpoints and force a subset of Envoy connections to close on overloaded instances (this can be randomized on count and jittered to smooth out thundering herds). I'm thinking a Unary/StreamServerInterceptor can be used to implement that disconnect).

Since I believe the long term solution should be in Pilot, I'd prefer to submit the first (server side `MaxConnectionAge`) as a short term fix for this issue, making the connection age a configuration value. This could still cause some churn (hopefully with incremental xDS - mitigating most), but would allow LB to converge faster.

**Comment by duderino** [comment]
Sorry for the late commentary, but I'm worried that this approach may cause more harm then good.  If all the Envoys start around the same time, then all will have their connections age out around the same time. 

I think some randomness needs to be added to the max connection age so all the Envoys don't try to reconnect to the Pilots all at once.

**Comment by ramaraochavali** [comment]
gRPC's max connection age implementation adds jitter to address the same behaviour. See java docs for example https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L369

**Comment by duderino** [comment]
Thanks for the clarification.  I see Etai said something similar above for the Go impl.  Sorry I missed that

**Comment by mandarjog** [comment]
This forces server side disconnects after the configured time. System responds slowly, and does not actually respond to changing load or imbalance. If this slow response is ok, this is a fine solution. 

For faster response time, we can reduce this time, but it introduces a lot of churn.

In a very large deployment this is needless even when load is correctly balanced.

Ultimately we will have grpc-lb

**Comment by linsun** [comment]
@elevran any work remaining for it?  does pilot have the right config to leverage the new config nob you added?

**Comment by linsun** [comment]
e.g. could we have our automated test enabled for the 2 flags...

**Comment by mandarjog** [comment]
These are command line Params and we don’t have helm options for them. We just need to expose one param, I don’t see a reason to keep grace period configurable. It just adds to confusion.

**Comment by linsun** [comment]
okay with not user configurable but we need to configure pilot more than the infinite timeout today.

**Comment by elevran** [comment]
@linsun the default is unset to ensure "least surprise" and maintain current behavior, leaving this under user explicit control. Adding documentation and helm option (for maxConnectionAge only, we can hardcode grace to 10s) can be done.  I'll submit against the `release-1.1`, if needed. Let me know. 

@mandarjog the system should converge after the `maxConnectionAge`. A value of a few minutes could be a reasonable compromise (@Stono - 5-10m would be acceptable in your case?).

I think this is probably ok as a short term solution and we need a need a more robust solution that better manages connection LB. Regarding grpc-lb, if this is the built in client side LB, not sure if it would handle the described use case. It seems to do a a name resolution on connection initiation and then balance between available servers. This would not help in the case of servers coming up after the client resolves the name, which was the original problem.

**Comment by linsun** [comment]
@elevran agreed, so if pilot replica is 1, there is no need to configure this `maxConnectionAge`.  If replica is 1+, then user can configure it based on what they are willing to tolerate.

Agreed this is a short term solution for 1.1... for longer term, it would be much better to have some intelligence to balance the loads among all replicas of Pilot.

**Comment by elevran** [comment]
@linsun #11126 has been merged into release 1.1. Does it make sense to close this issue with the merged short term fix (limiting maximum connection age via the command line) and open a separate issue for more advanced and informed LB by Istio components?

**Comment by linsun** [comment]
+1 @elevran to what you said!

**Comment by elevran** [comment]
@linsun @Stono @morvencao @mandarjog opened #11181 to track enhancement, post release-1.1 
@Stono - please consider closing this issue - the original issue is (at least partially) addressed and further work will be done in context of follow up issue.

**Comment by Stono** [comment]
Been chatting to @elevran; will close in favour of #11181
