### ISSUE TITLE
Update Concepts on the website

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#788]

**Comment by ldemailly** [comment]
Issue moved to [istio/istio.github.io #449](https://github.com/istio/istio.github.io/issues/449) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ldemailly** [comment]
@sakshigoel12 we should open website content issues directly in https://github.com/istio/istio.github.io/issues/
in the future

only if a doc change also happens in istio/istio (like the *.md here) or has cross repo work (like updating comments in api repo to regenerate docs on website,...) should it be in istio/istio

this being said I saw there are a bunch of new docs tagged issues and I won't create more noise by moving them, stopping at this one
