### ISSUE TITLE
CI lint case failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#7894]
seems related to your removal `--exclude="${EXCLUDES}"`
/cc @Tahler 

https://circleci.com/gh/istio/istio/156483?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Tahler** [comment]
That step isn't enabled right now actually. You just need to rebase your PR. Re-open this or ping me on slack if that doesn't work.
