### ISSUE TITLE
Path based routing is not working with Istio 1.0

### ISSUE THREAD

**Issue by asudhakarreddy** [istio/istio#7896]
**Describe the bug**
<sub><sup>Use case: I have two services running in on premisses k8s cluster with Istio 1.0, namely Kibana with port: 5601 and Grafana with port:3000.</sup></sub>

**Expected behavior**
<sub><sup>Istio should route trafic based on prefix separarion, Example http://172.16.22.233:31380/kibana and http://172.16.22.233:31380/grafana</sup></sub>

**Steps to reproduce the bug**
<sub><sup>On prem k8s with Istio 1.0</sup></sub>

**Version**
<sub><sup>`Istio 1.0` and `Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3"`</sup></sub>

**Is Istio Auth enabled or not?**
<sub><sup>Anuth desabled, helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort
</sup></sub>

**Environment**
<sub><sup>On prem</sup></sub>

**Cluster state**
<sub><sup>If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.</sup></sub>

**Comment by ijsnellf** [comment]
Please provide your config, your expected behavior and your observed behavior.

**Comment by asudhakarreddy** [comment]
Steps to reproduce:
-------------------------

1. deploy k8s cluster using kubeadm (on premises)

#From the k8s master, execute below steps
2. Configure helm

3. Download and install Istio using helm
$ curl -L https://git.io/getLatestIstio | sh -
$ cd istio-1.0.0

$export PATH=$PWD/bin:$PATH

4. Install CRDs
$ kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml

5. Install istio
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort

6. Label the default namespace with istio-injection=enabled
$ kubectl label namespace default istio-injection=enabled


7. Deploy Influxddb (use shared configurattion file influxdb.yaml)
$ kubectl apply -f influxdb.yaml

8. Deploy Grafana (use shared configurattion file grafana.yaml)
$ kubectl apply -f grafana.yaml

9. Deploy Istio gateway and virtualservices

$ kubectl apply -f gateway.yaml
$ kubectl apply -f virtualservice.yaml

10. Using browser, try access grafana service using Istio ingressgateway service
Example: URL: http://172.16.20.77:31380/grafana
Note: When I tried same grafana service using k8s NodePort the UI is opening without any issue.

Expected behavior: 
------------------------
Istio ingressgateway should redirect traffic to grafana service and a user should access grafana UI from browser. Example url: http://172.16.20.77:31380/grafana




Current behavior:
----------------------
Grafana UI is not opening.





Thanks,
Sudhakar Ambati
