### ISSUE TITLE
Use fraction instead of uint32 for percentage in fault injection, following the same change in Envoy

### ISSUE THREAD

**Issue by trabetti** [istio/istio#7903]
**Is your feature request related to a problem? Please describe.**
<sub>Envoy changed the percentage for fault injection to be a fraction instead of a uint32. The uint32 will be deprecated. I suggest a similar change in Istio.
</sub>

**Additional context**
<sub>Link to the Envoy issue: https://github.com/envoyproxy/envoy/issues/3904
and PR: https://github.com/envoyproxy/envoy/pull/3978</sub>

**Comment by venilnoronha** [comment]
I'd like to work on this.
