### ISSUE TITLE
Re-enable the reporting of force merges to on-call slack channel.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#7915]
It looks like we have run into a slew of issues due to force-merge. @kyessenov mentioned there was a bot reporting feature that reported force-merges to the Slack on-call channel. 

It would be great to get this feature back.

**Comment by sebastienvas** [comment]
It is enabled. It works for test-release but not oncall for some reason. 
https://github.com/istio/test-infra/blob/master/prow/plugins.yaml#L34

**Comment by sebastienvas** [comment]
I verified that the bot can write to the channel just fine. Checking if something is wrong when parsing the config.
