### ISSUE TITLE
beta feature "ingress" despite of alpha api of Gateway?

### ISSUE THREAD

**Issue by pourquoi42** [istio/istio#7931]
**Describe the bug**
Discrepancy between release notes / documentation and code regarding API version of Gateway custom resource:

according to 
https://istio.io/about/feature-stages/

ingress is in beta-stage

therefore ....

**Expected behavior**
.... I would expect the corresponding api version NOT to be in alpha stage. But it is:
https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/templates/crds.yaml#L86

**Steps to reproduce the bug**
follow above links

**Version**

Gateway resource is v1alpha3 in 1.0 branch as well as master

**Is Istio Auth enabled or not?**
n.a.

**Environment**
any
**Cluster state**
n.a.

**Comment by ijsnellf** [comment]
cc @rshriram @ZackButcher

**Comment by rshriram** [comment]
cc @jasmine-jaksic ..

**Comment by ayj** [comment]
The networking APIs are in v1beta1 stage despite the k8s apiVersion. Kubernetes CRD don't support multiple versions of the same group yet. As such, renaming the networking APIs from v1alpha3 to v1beta1 would have broken existing deployments.

Upstream k8s support for CRD versioning is targeted for alpha release in 1.12. Once that feature is widely available in supported k8s clusters, we can rename the apiVersion to match the actual feature stage.

xref: https://github.com/istio/istio/issues/6613

**Comment by pourquoi42** [comment]
thanks!
