### ISSUE TITLE
Update grafana to its latest version

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#7943]
**Describe the bug**
https://github.com/istio/istio/blob/master/addons/grafana/Dockerfile.grafana#L1 shows that Istio currently uses the version 5.0.4 of grafana, which was released on March 27, 2018. The latest version of grafana is 5.2.2, released on July 24, 2018. Istio should update its grafana version to leverage the fixes included in the latest grafana version.

**Expected behavior**
<sub><sup>A clear and concise description of what you expected to happen.</sup></sub>

**Steps to reproduce the bug**
<sub><sup>Steps to reproduce the behavior.</sup></sub>

**Version**
<sub><sup>What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`</sup></sub>

**Is Istio Auth enabled or not?**
<sub><sup>Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input.</sup></sub>

**Environment**
<sub><sup>Which environment, cloud vendor, OS, etc are you using?</sup></sub>

**Cluster state**
<sub><sup>If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue.</sup></sub>

**Comment by lei-tang** [comment]
#7945

**Comment by rkpagadala** [comment]
@lei-tang @sdake Why is this important to go in 1.0.1? Why can't this go in 1.1?

**Comment by lei-tang** [comment]
@rkpagadala this is important because the older version does not have the security fixes in the latest version.

**Comment by lei-tang** [comment]
An update to this issue: I have created the PR https://github.com/istio/istio/pull/7945 to fix this issue by updating the grafana used by Istio to the latest grafana version 5.2.2.  I have included two screenshots in https://github.com/istio/istio/pull/7945:  the first screenshot shows the upgraded grafana version 5.2.2 and the second screenshot shows the Istio service traffic in the dash board of grafana 5.2.2. The  PR https://github.com/istio/istio/pull/7945 has been merged in the commit [dea5796](https://github.com/istio/istio/commit/dea5796fa3f1fb0c71ed44dbc14b19ad4020c9ac).

**Comment by louisvernon** [comment]
@lei-tang Did you test the istio-mesh-dashboard? It requires some changes to work with Grafana 5.2.3 (we did not test 5.2.2):

![image](https://user-images.githubusercontent.com/552230/44750255-16f7e900-aad2-11e8-86ca-5a5d24864f72.png)

**Comment by lei-tang** [comment]
@louisvernon The tests I did are generating some traffic in Istio and view the Istio service dashboard in grafana. The results are shown in the screenshots attached to #7945. The first screenshot shows the upgraded grafana version 5.2.2 and the second screenshot shows the Istio service traffic in the dash board of grafana 5.2.2.

**Comment by douglas-reid** [comment]
Closing. Grafana is on 5.2.3 now on all branches now.
