### ISSUE TITLE
Always push initial MCP response for new streams

### ISSUE THREAD

**Issue by ayj** [istio/istio#7947]
Some users of MCP client (e.g. Pilot) may want an explicit indicate when the initial per-type state has synced. The MCP server layer currently does not push a response until there are resources available for the requested type. Consider pushing an empty response (per type) on new streams.

**Comment by ozevren** [comment]
Is this needed for 1.1?

**Comment by ayj** [comment]
Possibly. I believe the FullSync indication is hooked up to Pilot's readiness checks.

**Comment by ozevren** [comment]
Fixed by #9553
