### ISSUE TITLE
Debugging Custom Istio Adapter

### ISSUE THREAD

**Issue by vinayvenkat** [istio/istio#7952]
**Describe the bug**
<sub><sup>Currently there is no documentation to help debug custom Istio (mixer) adapters</sup></sub>

**Expected behavior**
<sub><sup>It would be great to have a prescribed document on how to debug custom adpaters for the following scenarios: 
1. Local development. (This exists)
2. Run the Mixer, ie. policy and telemetry containers independently and then be able to run check and report calls directly using mixc against a running mixer (i.e mixs is my guess). 
</sup></sub>

**Steps to reproduce the bug**
<sub><sup>I currently have Istio deployed along with my custom mixer container. However, I am unable to get to talk to my mixer. I am making requests but also getting many errors. </sup></sub>

**Version**
<sub><sup>1.10.5-gke.4 </sup></sub>

**Is Istio Auth enabled or not?**
<sub><sup>Yes</sup></sub>

**Environment**
<sub><sup>GKE</sup></sub>

**Error**
<sub><sup 
2018-08-15T17:07:23.896946Z	warn	testhandler.mysampleadapter.istio-system unable to unmarshal: unknown field "metrics" in config.Params, {"metrics":[{"name":"requestcount.metric.istio-system","type":"COUNTER"},{"name":"requestduration.metric.istio-system","type":"DISTRIBUTION"},{"name":"requestsize.metric.istio-system","type":"GAUGE"},{"name":"responsesize.metric.istio-system","type":"GAUGE"}]}
2018-08-15T17:07:23.897215Z	error	Failed to convert testhandler.mysampleadapter.istio-system an event: unknown field "metrics" in config.Params

and 

2018-08-15T17:07:22.859843Z	error	Handler not found: handler='testhandler.mysampleadapter'
</sup></sub>

**Comment by vinayvenkat** [comment]
@guptasu @mandarjog Can you please help. I've been stuck on this for close to a month.

**Comment by douglas-reid** [comment]
What does your config proto look like?  And have you run the required generation steps, etc.?

**Comment by vinayvenkat** [comment]
I followed all the steps outlined in: https://github.com/istio/istio/wiki/Mixer-Compiled-In-Adapter-Walkthrough

When I test it locally it works. (with the mixs and mixc)
However, when I push it to a running Istio deployment I get the errors shown above.

My config.proto is:

syntax = "proto3";

package adapter.mysampleadapter.config;

import "google/protobuf/duration.proto";
import "gogoproto/gogo.proto";

option go_package="config";

message Params {
    // Path of the file to save the information about runtime requests.
    string file_path = 1;
}

**Comment by douglas-reid** [comment]
I'm confused. Your config.proto doesn't show any `metrics` field. Shouldn't it include a `metrics` field for this all to work?

**Comment by vinayvenkat** [comment]
I was approaching this in a phased manner. As I mentioned, I followed the custom adapter walkthrough example. And following got me to the point of running the mixs and the mixc and I could see my adapter being invoked. 
My assumption was that if I built the mixer and updated the mixer policy and telemetry pods with my new image and if I ran some traffic against my app with all the right configs (that is with handler, instances, operatorconfigs etc), that this same thing would invoke my custom adapter and would have the same behavior. 

Am I not in right in that assumption. If not can you point me to some documentation or examples which ties all these aspects together? 
Thank you for the responses.

**Comment by douglas-reid** [comment]
I'm not sure I follow your plan -- my apologies.

If you have istio config for your handler (you've `kubectl apply -f`'d some YAML) and it has config for `metrics` (as appears), then this cannot work unless you add a field to your config proto for `metrics` of the correct type, etc.

Please post your handler config here for confirmation.

Picking an adapter at random, we'll use `circonus` to explain:
- Note the `metrics` field in the `config.proto`: https://github.com/istio/istio/blob/master/mixer/adapter/circonus/config/config.proto#L59
- Note the handler config in their example `operatorconfig` yamls: https://github.com/istio/istio/blob/master/mixer/adapter/circonus/operatorconfig/circonus.yaml#L62-L80

Does that help?

**Comment by mandarjog** [comment]
@vinayvenkat It would be great if you write your adapter as out-of-process.
https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough

It decouples you from mixer itself and arguable easier to test.
You can install a stock istio / Mixer release and then deploy your adapter independently.

Here is a sample adapter including its integration test.
https://github.com/istio/istio/blob/master/mixer/test/prometheus

**Comment by sputtag1** [comment]
@douglas-reid We are following this defect as well. We followed all the steps in https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough and configured a custom adapter to build a new adapter. Since we coded our custom adapter inside the mixer folder, we were wondering how could we deploy our adapter independently from the mixer. And if the mixer container is inside the telemetry and the policy pods, how do we compile this adapter independently. We have been following this guide https://github.com/istio/istio/wiki/Mixer-Using-a-Custom-Adapter to build an out-proc adapter, but in Step 2 we dont seem to find our custom adapter in the CRD definitions listed. Do you know the reason why?

**Comment by douglas-reid** [comment]
@sputtag1 a guide on deploying OOP adapters would be very useful, I agree. would you mind filing a separate issue to cover this need? we'd want to cover best practices, etc. and add to it as bits like auth and security are incorporated.

RE: the missing CRD

I believe you have to add the adapter to the adapter inventory for the `mixs crd` command to be aware of it. @mandarjog is this the intended dep? Is there another way we can support generation?

RE: template -> API

The generated go code for a template should directly contain the details needed for implementation. For the `metric` template, this includes:

```go
service HandleMetricService {
    // HandleMetric is called by Mixer at request-time to deliver 'metric' instances to the backend.
    rpc HandleMetric(HandleMetricRequest) returns (istio.mixer.adapter.model.v1beta1.ReportResult);

}
```

Does that help?

**Comment by douglas-reid** [comment]
An example OOP adapter with a deployment can be found in [mixer/test/prometheus/cmd](https://github.com/istio/istio/tree/master/mixer/test/prometheus/cmd). My suggestion would be to start with that as a guideline on how to get something working.

**Comment by sputtag1** [comment]
@douglas-reid Thankyou, we followed the steps that you have mentioned. We were able to build the image, push it and apply it. But when the pod is starting we are running into this error: "container_linux.go:247: starting container process caused “exec: \“/usr/local/bin/mygrpcadapter\“: permission denied”". So why is it searching for the image at /usr/local/bin, while we have a different path set in the Dockerfile add. Is this path hardcoded by any chance? 

Our Dockerfile content: 

`
FROM scratch
ADD mygrpcadapter /root/adapter
ENTRYPOINT ["/root/adapter"]
`

**Comment by douglas-reid** [comment]
You should probably consult the docker docs at this point, but you might try:

`FROM scratch ADD mygrpcadapter /usr/local/bin/ ENTRYPOINT ["/usr/local/bin/mygrpcadapter"]`

**Comment by sputtag1** [comment]
@douglas-reid That dint work either. https://github.com/istio/old_issues_repo/issues/179 - our issue is similar to this one. We are using istio 1.0.0

**Comment by sputtag1** [comment]
@douglas-reid We have successfully deployed our custom adapter. But when we apply the handler/rules/instances in sample_operator_cfg.yaml. 
We are running into this error: 
```
2018-08-24T21:42:31.168799Z	info	Publishing 3 events
2018-08-24T21:42:31.172676Z	error	adapter 'mygrpcadapter' not found
2018-08-24T21:42:31.173335Z	error	template 'metric' not found
2018-08-24T21:42:31.179011Z	error	Handler not found: handler='h1.istio-system'
2018-08-24T21:42:31.179063Z	error	No valid actions found in rule
2018-08-24T21:42:31.179232Z	info	Built new config.Snapshot: id='2'```
Could you please help us through it ?

**Comment by venilnoronha** [comment]
Can you provide your `Service`, `Deployment`, `handler`, `instance` and `rule` configuration?

**Comment by mandarjog** [comment]
You need to register metric as a dynamic template and you also need to register your adapter.

Look At Prometheus.yml in the test directory that you used earlier for an  sample of adapter.
 For metric template apply this file: https://github.com/istio/istio/blob/master/mixer/template/metric/template.yaml

**Comment by vinayvenkat** [comment]
Hi @douglas-reid @mandarjog:
Question about the running the mixer server. 

I run it with: 
/home/ec2-user/go/out/linux_amd64/release/mixs server --configStoreURL=fs://$(pwd)/mixer/adapter/mysampleadapter/testdata

When it runs it outputs the default config: 

MaxConcurrentStreams: 1024
APIWorkerPoolSize: 1024
AdapterWorkerPoolSize: 1024
APIPort: 9091
APIAddress:
MonitoringPort: 9093
EnableProfiling: true
SingleThreaded: false
NumCheckCacheEntries: 1500000
ConfigStoreURL: fs:///home/ec2-user/go/src/istio.io/istio/mixer/adapter/mysampleadapter/testdata
ConfigDefaultNamespace: istio-system
ConfigIdentityAttribute: destination.service
ConfigIdentityAttributeDomain: svc.cluster.local

====

So the ConfigIdentityAttribute is set to: destination.service and the 
ConfigIdentityAttributeDomain is set to: svc.cluster.local

Now when I send a report command:

/home/ec2-user/go/out/linux_amd64/release/mixc report -s destination.service="svc.cluster.local" -t request.time="2017-02-01T10:12:14Z"

everything works. 

However, I am unable to change the arguments i pass into the report call. 

For example, I can't seem to run this command: 

/home/ec2-user/go/out/linux_amd64/release/mixc report -s source.labels="app:vv_app" -t request.time="2017-02-01T10:12:14Z"

Error: 
2018-08-16T22:58:10.083301Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc420063980, READY
Report RPC returned Unknown (1 error occurred:

* preprocessing attributes failed: identity parameter not found: 'destination.service')

How can I test other parameters that I send to the server? Can you please advise?

**Comment by kyessenov** [comment]
Hi there,

Which version of istio are you using?
We have mostly deprecated the use of `destination.service` attribute. From
version 1.0, the configuration resolution is scoped to a namespace of the
source or destination, depending on the direction of the call.

Best,
--kuat

**Comment by vinayvenkat** [comment]
Hi!
I am using Version: 0.8.0

: ~ >istioctl version
Version: 0.8.0
GitRevision: 6f9f420f0c7119ff4fa6a1966a6f6d89b1b4db84
User: root@48d5ddfd72da
Hub: docker.io/istio
GolangVersion: go1.10.1
BuildStatus: Clean

I will upgrade. Thanks.

**Comment by vinayvenkat** [comment]
I also figured out the problem: 

The command needs to be invoked as:

/home/ec2-user/go/out/linux_amd64/release/mixc report -s destination.service="svc.cluster.local" --stringmap_attributes source.labels=app:vv_app -t request.time="2017-02-01T10:12:14Z"


I'll also close this ticket. I think all the issues have been addressed. Thank you for all the help.
