### ISSUE TITLE
Proxy should indicate Mixer not available in RESPONSE_FLAGs

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#7959]
At present If Mixer (istio-policy) is not available, then we get
`[2018-08-14T09:26:52.187Z] "GET /apis HTTP/1.1" 503 - 0 69 4 - "10.132.0.3" "FxVersion" "bae0a141-3e55-9240-9074-8429433ffc32" "mysvc" "-"`

Both `UPSTREAM_HOST` and `RESPONSE_FLAGS` are empty.

Mixer client should record the reason in RESPONSE_FLAGS

- [x] At present use `UNAUTHORIZED_EXTERNAL_SERVICE` response flag
- [ ] Add `UNAVAILABLE_EXTERNAL_SERVICE` or equivalent flag to envoy and use it so that access logs distinguish between the two.

**Comment by kyessenov** [comment]
Implemented in 1.1:
`mixer/test/client/failed_request/failed_request_test.go:  "context.proxy_error_code": "UAEX",`
