### ISSUE TITLE
no healthy upstream

### ISSUE THREAD

**Issue by git-duzhengjie** [istio/istio#7965]
**Describe the bug**
<sub><sup>I create the sample bookinfo , but when i visit it , i get the message 'no healthy upstream'</sup></sub>

**Steps to reproduce the bug**
<sub><sup>At first , i can visit it , it comes out when i remove the istio and install it again</sup></sub>

**Version**
<sub><sup>istio version:1.0.0
kubernetes version: 1.9.1
</sup></sub>

**Is Istio Auth enabled or not?**
<sub><sup>yes</sup></sub>

**Environment**
<sub><sup>kubernetes local</sup></sub>

**Comment by ijsnellf** [comment]
What does the output of `kubectl get po --all-namespaces` look like? For pods which are in a non-running state, what does the output of `kubectl describe po <pod>` look like? Are there errors or warnings in the logs of pods in the `istio-system` namespace?

**Comment by git-duzhengjie** [comment]
all pod is running in the namespace istio-system ,but a pod named "istio-sidecar-injector" goes some wrong."Liveness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded" and "Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded" are the messages in the described info.What does it mean?@ijsnellf

**Comment by sdake** [comment]
@git-duzhengjie which platform?

**Comment by git-duzhengjie** [comment]
@sdake Kubernetes on CentOS，my own test environment

**Comment by git-duzhengjie** [comment]
i find the reason,i remove the bookinfo not via the istioctl but the kubectl
