### ISSUE TITLE
Traces are not being sampled, every request is sent to jaeger

### ISSUE THREAD

**Issue by Stono** [istio/istio#7968]
**Describe the bug**
It became apparent today during some load testing that every request is being sampled to Jaeger.  One of our tests was doing 100 requests/second and every single one had `x-b3-sampled`, and they all appeared in Jaeger.

```
< x-request-id: e8c8d121-c498-9450-8f10-bae64cf245a9
< x-b3-parentspanid:
< x-b3-traceid: f9941cf73de4848e
< x-b3-spanid: f9941cf73de4848e
< x-b3-sampled: 1
< x-b3-flags:
```

**Expected behaviour**
Configurable, or sensible default behaviours where this isn't the case, as under any sort of production load we quickly dos jaeger.

Associated: https://github.com/envoyproxy/envoy/issues/1813

**Comment by chanjarster** [comment]
@Stono I think [Trace sampling][1] can help you

[1]: https://istio.io/docs/tasks/telemetry/distributed-tracing/#trace-sampling

**Comment by Stono** [comment]
Ahh brilliant @chanjarster - i totally missed that documentation.  Will give it a go now.

**Comment by Stono** [comment]
OK the issue appears to be in ingress-nginx now, not istio https://github.com/kubernetes/ingress-nginx/issues/2949 so i'll close this!
