### ISSUE TITLE
Helm Charts: BookInfo Application example not working with mixer disabled

### ISSUE THREAD

**Issue by Rajadeepan** [istio/istio#7982]
**Describe the bug**
<sub><sup> As per the istio documentation the istio can work with minimal components(https://istio.io/docs/concepts/policies-and-telemetry/). Trying to test the BookInfo Application  deploying istio with disabling mixer . It is giving connection refused error. 
(Tested the BookInfo application  deploying istio with all the components it works fine.) 
Have used Helm for installation of istio in both cases.
</sup></sub>

**Expected behavior**
<sub><sup>The BookInfo Application should work fine with mixer disabled</sup></sub>

**Steps to reproduce the bug**
<sub><sup>
1) Install istio with mixer diabled.
![image](https://user-images.githubusercontent.com/13465886/44208648-9b677500-a17e-11e8-924e-016d13b5d8df.png)
 In the istio system namespace all the istio components are running except mixer components
![image](https://user-images.githubusercontent.com/13465886/44208731-df5a7a00-a17e-11e8-87ef-2a0190ab9819.png)
<sub><sup>
2) Deploy the Book Application example as shown below
<sub><sup>
![image](https://user-images.githubusercontent.com/13465886/44208680-b89c4380-a17e-11e8-889d-6cd0fc304813.png)

All the pods are running 
![image](https://user-images.githubusercontent.com/13465886/44208751-f26d4a00-a17e-11e8-91be-7e91bb6f1ff4.png)

![image](https://user-images.githubusercontent.com/13465886/44208758-fe590c00-a17e-11e8-8f83-0e75656f940f.png)

![image](https://user-images.githubusercontent.com/13465886/44208767-087b0a80-a17f-11e8-9882-6ebe8b53295f.png)

*Connection refused error is getting show when trying to access the application.*
</sup></sub>

### Observation: 
<sub><sup>
  The egress and ingress pods in the istio-system get restarted and the logs shows 

![image](https://user-images.githubusercontent.com/13465886/44208859-4e37d300-a17f-11e8-91ad-91dd443fda3e.png)

![image](https://user-images.githubusercontent.com/13465886/44215776-f6a26300-a190-11e8-8856-64e505fb6e15.png)

</sup></sub>

**Version**
<sub><sup>  istio version       : 1.0.0
                      kubectl version  : v1.10.4
</sup></sub>

**Is Istio Auth enabled or not?**
<sub><sup>Disabled </sup></sub>

**Environment**
<sub><sup>Ubuntu 
![image](https://user-images.githubusercontent.com/13465886/44210854-2c414f00-a185-11e8-9654-84824b978ee9.png)
</sup></sub>

**Comment by ijsnellf** [comment]
@Rajadeepan: did you install istio using helm? Can you provide the command you used to install istio?

**Comment by Rajadeepan** [comment]
@ijsnellf  yes i have installed istio with helm.  This is the command used to install istio without mixer

**helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
--set mixer.enabled=false** 

(referred this doc https://istio.io/docs/setup/kubernetes/helm-install/#customization-example-traffic-management-minimal-set)

**Comment by mandarjog** [comment]
`mixer.enabled=false` removes stasd-to-prom bridge as well.
Envoy relies on statsd-to-prom bridge to emit metrics, needs to be fixed by always deploying stasd-to-prom and prometheus as well.

stats collection directly from envoy should not be conditional on mixer.

**Comment by gbaufake** [comment]
@ijsnellf This problem is visible on Ansible Installer and openshift as well

**Comment by liamawhite** [comment]
You also need to turn off the Envoy statsd stuff mentioned in the docs you linked to:

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system 
--set mixer.enabled=false  --set global.proxy.envoyStatsd.enabled=false
```

Otherwise Envoy expects statsd-to-prom to be there

**Comment by nrshrivatsan** [comment]
@liamawhite suggestion [here](https://github.com/istio/istio/issues/7982#issuecomment-414135541) works on my `minikube` on macos

**Comment by Rajadeepan** [comment]
@liamawhite you suggestion worked. thanks
