### ISSUE TITLE
Use go-control-plane/master instead of custom branch

### ISSUE THREAD

**Issue by rshriram** [istio/istio#7985]
There was some grpc update in go-control-plane and its incompatible with rest of Istio code base (some gogo vodoo). As a result, we are stuck with go-control-plane:revert-grpc-update branch. We need to do the proper fix ups and move to go-control-plane:master, so that we can start getting the updates from Envoy in Pilot.

cc @kyessenov (who did the gRPC update thing in go-control-plane) / @mandarjog .

**Comment by kyessenov** [comment]
Seems like we need a conversation on the project-level tasks. At some point we need to update all libraries, including kubernetes APIs. Should this belong to test & release group?

@hklai Thoughts?

**Comment by kyessenov** [comment]
Fixed by https://github.com/istio/istio/pull/8036
