### ISSUE TITLE
Mixer test failed during setup in new-cluster test

### ISSUE THREAD

**Issue by yutongz** [istio/istio#799]
It takes time to pull all images needed in the new-cluster test, for now simply extend the timeout. Should have a better to wait until pulling images finishes.

One example here: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/789/new-e2e-rbac_no_auth/244/

**Comment by ldemailly** [comment]
+1 on 'should have a better way' - follow up ?

**Comment by yutongz** [comment]
Let's do this after 0.2. Together with all other "sleep and wait" in tests, replace them with "check and wait"

**Comment by sebastienvas** [comment]
@ldemailly, if you have an idea, we will gracefully review your PR :)

**Comment by ldemailly** [comment]
thankfully in 0.3 we'll have 100% of team working on that kind of stuff, not just a handful of people

**Comment by yutongz** [comment]
/reopen 
Better fix in https://github.com/istio/istio/pull/899
