### ISSUE TITLE
Add OCSP Certificate Revocation Support

### ISSUE THREAD

**Issue by danehans** [istio/istio#7990]
**Is your feature request related to a problem? Please describe.**
<sub>Yes, Istio does not support OCSP for certificate revocation checking.</sub>

**Describe the solution you'd like**
<sub>Support X.509 certificate revocation using OCSP. Istio may support other means of checking for revocation in addition to OCSP. Istio should skip OCSP for certificates validated using DANE/DNSSEC. Support OCSP stapling in TLS. Apply reasonable caching and validation policies. Control keys that can be used to sign OCSP responses.</sub>

**Describe alternatives you've considered**
<sub>None. OCSP-based certificate revocation checking is a mandatory security requirement.</sub>

**Additional context**
<sup>It appears that Envoy does not support OCSP either.</sup>

**Comment by danehans** [comment]
@myidpt even with short-lived certs, our security policy requires OCSP.

**Comment by netdisciple** [comment]
i must not have permission to add a label to this.
label:"community/help wanted"

**Comment by netdisciple** [comment]
still need this

**Comment by JimmyCYJ** [comment]
@danehans  could you open a feature request to Envoy community for the OCSP support?

**Comment by howardjohn** [comment]
This is a duplicate of https://github.com/istio/istio/issues/17763
