### ISSUE TITLE
Eliminate https://github.com/istio/api/tree/master/common/v1alpha1

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#7997]
**Describe the bug**
We've recently added https://github.com/istio/api/tree/master/common/v1alpha1 as a stand-alone proto, and it doesn't really fit how we've been organizing protos to date. It looks silly in our docs (https://preliminary.istio.io/docs/reference/config/istio.string.v1alpha1/)

Let's combine this proto with whatever place is trying to use it, instead of having this in a separate file.

**Comment by geeknoid** [comment]
@rshriram FYI

**Comment by yangminzhu** [comment]
It's currently only used in [policy.proto](https://github.com/istio/api/blob/168b2a7df6df30c4ff01cdbad156a22ed56cc1d2/authentication/v1alpha1/policy.proto#L175), I'll move it to that file.

/cc @diemtvu
