### ISSUE TITLE
TestLocalPilot is flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#8002]
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/8000/istio-unit-tests/11675/

/assign @nmittler @ozevren

**Comment by hklai** [comment]
This keeps happening.
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/8701/istio-unit-tests/13392/

@nmittler, could you please take a look?
