### ISSUE TITLE
HTTPRoute `appendHeaders` got wrong result if that header already exists in request headers.

### ISSUE THREAD

**Issue by chanjarster** [istio/istio#8019]
**Describe the bug**

HTTPRoute `appendHeaders` got wrong result if that header already exists in request headers.

**Steps to reproduce the bug**

1. Deploy echo-server using this [yaml][1].
1. `curl -H 'x-foo:foo' http://<host>:<port>/echo-istio`
1. Observe the result:
   ```
   ...
   x-foo=table: 0x40d4b988
   ...
   ```

**Expected behavior**

the correct result should be `x-foo=foo,bar`

**Version**

```
$ istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version --short
Client Version: v1.11.2
Server Version: v1.11.1
```

**Is Istio Auth enabled or not?**

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set gateways.istio-egressgateway.type=NodePort \
  --set tracing.enabled=true \
  --set servicegraph.enabled=true \
  --set grafana.enabled=true
```

**Environment**

On-premise OpenStack cloud

**Cluster state**

Too big, not uploaded

[1]: https://gist.github.com/chanjarster/d746c09813fab7602c87a53cf4fa1eb2

**Comment by ijsnellf** [comment]
Replicated with minikube.

This is the corresponding Envoy field we are setting.
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=request_headers_to_add

This is the area of code where we set the field:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L378

**Comment by ijsnellf** [comment]
I think this is a bug with `gcr.io/google-containers/echoserver:1.10`. It isn't handling multiple headers correctly.

I wrote a simple Python echo server:
https://gist.github.com/ijsnellf/6c28a4a108d04db0654df673aebafb51

Note the two headers in the response:
```bash
isaiah@nostromo:~/workspace/src/istio.io/istio$ curl -H 'x-foo:foo' 192.168.99.100:31380/echo-istio
backend-response: host: 192.168.99.100:31380
user-agent: curl/7.47.0
accept: */*
x-foo: foo
x-forwarded-for: 172.17.0.1
x-forwarded-proto: http
x-request-id: afe5561d-f450-9b9b-bbc4-dd850441575b
x-b3-traceid: 28b340802ce0d15c
x-b3-spanid: 28b340802ce0d15c
x-b3-sampled: 1
x-foo: bar
content-length: 0
x-envoy-internal: true
```

**Comment by chanjarster** [comment]
@ijsnellf Hmm... seems like echoserver's bug. But two headers is a little strange, why not one header with two values joined by comma. I'm not sure this a bug or not. Is there a *standard way* to handle this situation?

**Comment by chanjarster** [comment]
Well this is not Istio's bug

**Comment by ijsnellf** [comment]
Multiple headers with the same name are valid as long as the ordering is maintained and the values can be concatenated with commas (last paragraph):
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
