### ISSUE TITLE
gke 1.10 istio 1.0 helm chart deploy with tracing, kiali is looking for tracing on localhost

### ISSUE THREAD

**Issue by JohnDzialo** [istio/istio#8027]
**Describe the bug**
I recently deployed istio1.0 to gke 1.10 with grafana, kiali and tracing using the helm chart.  on deploy kiali is not able to resolve distributed tracing as it is looking for jaeger tracing at localhost.  An option to overwrite the url for grafana and jaeger in the kiali deployment seems to make sense here.

**Expected behavior**
Helm deployment of istio1.0 with value overrides for grafana and jaeger tracing urls so kiali can read from the kube dns name, for example istio-tracing.istio-system.svc.cluster.local or grafana.istio-system.svc.cluster.local.

**Steps to reproduce the bug**
Deploy with helm chart enabling tracing, grafana and kiali.  kiali will not be able to access distributed tracing as it is looking at localhost by default.

**Version**
istio1.0 pulled from github and deployed with helm chart
k8s gke 1.10.5-gke.4ds

**Is Istio Auth enabled or not?**
stable

**Environment**
GKE

**Cluster state**
that's a lot of data from our cluster if it is necessary I can update it later

**Comment by ijsnellf** [comment]
cc @linsun @kyessenov

**Comment by lucasponce** [comment]
Hello @JohnDzialo,
Could you test with the new istio-release-1.0 kiali image ?
https://hub.docker.com/r/kiali/kiali/tags/

We had a reported issue in kiali: https://github.com/kiali/kiali/issues/416 and it would help us to test it on GKE.

Thanks.

**Comment by JohnDzialo** [comment]
Hi @lucasponce!  Thanks for the reploy.

I was using the kiali :latest tag previously I now have moved over to the istio-release-1.0 tag for kiali.  And the problem appears to be the same.

Let me know if there is anything else I can do to help diagnose a method.

**Comment by JohnDzialo** [comment]
![screen shot 2018-08-17 at 1 59 06 pm](https://user-images.githubusercontent.com/9005145/44281528-1899f500-a226-11e8-992d-675097ae9919.png)
I still see the error even with the new docker image istio-release-1.0.

**Comment by lucasponce** [comment]
Thanks @JohnDzialo.

A couple of checks:
- Could you run a `kubectl get services -n istio-system` (or equivalent in GKE) to check if the jaeger-query service is up an running in the expected port ?
- What is the output of the http://localhost:20001/api/jaeger ?

Basically, Kiali uses a simple proxy to serve jaeger-query under the port 32439, to not manually expose the jaeger-query service, but for some reason in your scenario it is not working.

Let me know and I can investigate.

Thanks again for the feedback.

**Comment by awdrius** [comment]
@JohnDzialo @lucasponce I'm having the same issue so hopefully you guys won't mind me jumping in the middle.

To answer your question:

* jaeger-query is running: `jaeger-query               ClusterIP      x.x.x.x   <none>            16686/TCP      1h`

* kubectl port-forwarding kiali and curl'ing http://localhost:20001/api/jaeger gives me this:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 20001 (#0)
> GET /api/jaeger HTTP/1.1
> Host: localhost:20001
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="Kiali"
< X-Content-Type-Options: nosniff
< Date: Thu, 23 Aug 2018 17:35:06 GMT
< Content-Length: 13
< 
Unauthorized
```

I have it freshly installed (using 1.0.0 tag) and can provide more details if needed.

**Comment by lucasponce** [comment]
@awdrius @JohnDzialo Thanks for your details.
Definetely there is some issue with the networking configuration.
I'm trying to reproduce same environment to see if I can get same scenario and propuse a fix.

**Comment by lucasponce** [comment]
Ok, it seems the Helm Chart is missing here the kiali-jaeger port:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/service.yaml

There is a PR coming to fix this:
https://github.com/istio/istio/pull/8115/files

Basically, kiali exposes the jaeger-query service with a proxy using an additional port, and it seems the Helm installation won't take it:
https://github.com/kiali/kiali/blob/master/deploy/kubernetes/kiali.yaml#L26

Sorry, for the inconvenience, the workaround would be to pull and install kiali manually, following similar steps as the kiali makefile:
https://github.com/kiali/kiali/blob/master/Makefile#L245

Please, let me know if that would solve this issue (until the PR is merged and it can be applied to future versions).

Thanks !

**Comment by awdrius** [comment]
@lucasponce thanks for an update.

I've created that missing service manually.

```
apiVersion: v1
kind: Service
metadata:
  name: kiali-jaeger
  namespace: istio-system
  labels:
    app: kiali
spec:
  type: NodePort
  ports:
  - name: jaeger
    protocol: TCP
    nodePort: 32439
    port: 20002
  selector:
    app: kiali
```

The only downside is that now I need to kubectl port forward both kiali and kiali-jaeger to make "Distributed Tracing" work:

```
kubectl port-forward svc/kiali 20001 -n istio-system
```
```
kubectl port-forward svc/kiali-jaeger 32439:20002
```

It makes sense as http://localhost:20001/api/jaeger return an address to the jaeger:

```
{"url":"http://localhost:32439"}
```

I get why it's implemented that way but I wish kiali would proxy requests to jaeger by itself intead of relying on exposing jaeger.

**Comment by lucasponce** [comment]
Thanks @awdrius for the update.
Yes, the long term is to embed jaeger internally as a UI component to not need this proxy.
It is something we had in Kiali backlog and we hope to start working on next Sprint.
https://issues.jboss.org/browse/KIALI-1405

So, with the workaround put it in place, you can now get Jaeger correctly from Kiali pages ?
(Specially, it propagates the filter from the service details pages).

Thanks.

**Comment by awdrius** [comment]
No worries, thanks for the speedy reply.

Jaeger is fully embedded and I can use its UI and see traces/spans. I do not have any complex services deployed yet so I do not know if complex queries work (I see no reason why they shouldn't). I'll try getting more of the stuff deployed and will post an update.

![2018-08-24-14 01 14_1846x804_scrot](https://user-images.githubusercontent.com/8440387/44586029-375c3680-a7a6-11e8-8d03-912dad71ecd0.png)

**Comment by lucasponce** [comment]
Great @awdrius.
One of the features is to link this one from the service details page.
If you navigate from Services -> Details -> Tab Traces, you will see same info but filtered.

**Comment by awdrius** [comment]
Ah yes, it works: I can navigate directly to "Distributed Tracing" traces from "Services" tab meaning that that feature works. That is a neat integration!

**Comment by ozevren** [comment]
Just following up on this. Based on the conversation above, it looks like this problem is resolved. Anything else to follow through on the Istio side?

**Comment by douglas-reid** [comment]
I think that this issue has been resolved and/or is better tracked via kiali's tracking. Closing.
