### ISSUE TITLE
Upgrading from 0.8.0 to 1.0.0 is non-functional with tiller (option 2)

### ISSUE THREAD

**Issue by cosoriog** [istio/istio#8034]
Version currently installed: [0.8.0](https://github.com/istio/istio/releases/tag/0.8.0)
Istio being upgraded to [1.0.0](https://github.com/istio/istio/releases/tag/1.0.0)
OS: CentOS 7.4.1708
Kubectl version: Client v1.9.7, Server v1.9.6+coreos.0
Helm version: Client and server v2.9.1

Istio 0.8.0 was installed with helm

Steps to upgrade (based on [this page](https://istio.io/docs/setup/kubernetes/upgrading-istio/)):
1. kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
2. Wait for a few seconds until changes are completed
3. helm upgrade istio install/kubernetes/helm/istio --namespace istio-system

Log:
`[debug] Created tunnel using local port: '43940'`
`[debug] SERVER: "127.0.0.1:43940"`
`Error: UPGRADE FAILED: no ConfigMap with the name "istio-galley-configuration" found`

Configmap istio-galley-configuration is new in 1.0.0 but it seems helm it trying to find it in 0.8.0 before it applies changes.

**Comment by sdake** [comment]
```
sdake@falkor-07:~$ helm upgrade istio istio-1.0.0/install/kubernetes/helm/istio --set galley.enabled=false
Error: UPGRADE FAILED: no ConfigMap with the name "istio-security-custom-resources" found
```

**Comment by sdake** [comment]
```
sdake@falkor-07:~$ helm upgrade istio istio-1.0.0/install/kubernetes/helm/istio --set galley.enabled=false --set security.enabled=false
Error: UPGRADE FAILED: no ClusterRole with the name "istio-egressgateway-istio-system" found
```

**Comment by sdake** [comment]
```
sdake@falkor-07:~$ helm upgrade istio istio-1.0.0/install/kubernetes/helm/istio --set galley.enabled=false --set security.enabled=false --set egressgateway.enabled=false
Error: UPGRADE FAILED: no ClusterRole with the name "istio-ingressgateway-istio-system" found
```

**Comment by sdake** [comment]
Helm 2.7.2, which was tested on the release candidates and worked well, fails in the same way as reported in this bug log.

**Comment by sdake** [comment]
I executed a `bisect` between `1.0.0-snapshot.0` ...`1.0.0` could not find an upgradeable version with `helm 2.10.0`.

**Comment by kamilgregorczyk** [comment]
Might be related #7562

**Comment by andelhie** [comment]
I am affected by this bug have we found a work around yet?

**Comment by kamilgregorczyk** [comment]
I don't think so, it's actually helm problem

śr., 5 wrz 2018, 18:33 użytkownik Andy del Hierro <notifications@github.com>
napisał:

**Comment by sdake** [comment]
A workaround is proposed here: https://github.com/helm/helm/issues/1193#issuecomment-419555433

Although I have not tested that approach, nor its impact for Istio's upgrade.

Cheers
-steve
