### ISSUE TITLE
Advice for IP based services

### ISSUE THREAD

**Issue by Stono** [istio/istio#8057]
We have numerous applications which talked to clustered state stores by IP, not hostname - and this is a requirement of the data store rather than the client.

Redis is a prime example; take the following HA redis setup.  In this example, the client is configured to talk to the sentinel nodes by their hostnames:

  - sentinel1.redis-headless.namespace.svc.cluster.local
  - sentinel2.redis-headless.namespace.svc.cluster.local
  - sentinel3.redis-headless.namespace.svc.cluster.local

![1](https://user-images.githubusercontent.com/1486729/44307074-0e960480-a394-11e8-80ad-e6a6bd767af1.png)

And that works fine (ish, bar the port problems with headless services), I can define a ServiceEntry for it.  However, sentinel doesn't use hostnames, it maintains the cluster state by IP address and will return an array of the nodes, the client will then attempt to talk to the nodes on their ip and in turn get a 404 from envoy.

![client to redis](https://user-images.githubusercontent.com/1486729/44307093-42712a00-a394-11e8-8dc5-00e286c1d757.png)

I have a couple of solutions at the moment, none of which I really like:

  - Sit around and wait for managed redis to be available in my GCP region.
  - Architect Redis with a service (perhaps haproxy) in front of it which handles this logic, and have apps connect to that service instead.
  - Exclude these apps from Istio all together

Any ideas?

**Comment by Stono** [comment]
No, because pod IPs are ephemeral 🤷

**Comment by LinAnt** [comment]
Did you come up with a solution to this? I am facing the same issue with vault/etcd.

**Comment by Stono** [comment]
@LinAnt nope, it's basically unsupported.  In the case of redis I ended up building a HAProxy LB in front of it and used the annotation `traffic.sidecar.istio.io/includeOutboundIPRanges: ""`, to have envoy not intercept any outbound traffic.  This only works when the app is not talking to any istio stuff upstream.

**Comment by gsf** [comment]
We are considering as a stop gap creating a deployed service that will listen for updates from sentinel and update a ServiceEntry to match advertised IP addresses. Could that work?
