### ISSUE TITLE
Port 15001 not opened when trying to use TPROXY mode

### ISSUE THREAD

**Issue by 0xCA7F00D** [istio/istio#8059]
**Describe the bug**
Upon changing the env interceptionMode to the value "TPROXY",
kube-inject changes the yaml as expected(injecting the new mode, both on proxy_init and on proxyv2) and when I look at the iptables, changes are done correctly.
The problem is that the envoy proxy doesn't expose port 15001 as expected for making its communication and therefore I get an upstream error.
**Expected behavior**
everything should work correctly, with transparent proxy mode configured.
**Steps to reproduce the bug**
change the env in istio-demo.yaml
deploy istio-demo.yaml
that's it :)
**Version**
newest stable version of Istio(1.0.0)
kubernetes 1.11
**Is Istio Auth enabled or not?**
I tried both, I guess that has no affect on the problem at all

the part I changed at istio-demo.yaml:

>       # The mode used to redirect inbound connections to Envoy. This setting
>       # has no effect on outbound traffic: iptables REDIRECT is always used for
>       # outbound connections.
>       # If "REDIRECT", use iptables REDIRECT to NAT and redirect to Envoy.
>       # The "REDIRECT" mode loses source addresses during redirection.
>       # If "TPROXY", use iptables TPROXY to redirect to Envoy.
>       # The "TPROXY" mode preserves both the source and destination IP
>       # addresses and ports, so that they can be used for advanced filtering
>       # and manipulation.
>       # The "TPROXY" mode also configures the sidecar to run with the
>       # CAP_NET_ADMIN capability, which is required to use TPROXY.
>       interceptionMode: **TPROXY**

the part that got changed in the injected yaml:

> 
>          - name: ISTIO_META_INTERCEPTION_MODE
>           value: **TPROXY**
>         image: gcr.io/istio-release/proxyv2:1.0.0
>         imagePullPolicy: IfNotPresent
>         name: istio-proxy
>         resources:
>           requests:
>             cpu: 10m
>         securityContext:
>           **capabilities:
>             add:
>             - NET_ADMIN**
>           privileged: false
>           readOnlyRootFilesystem: true
>           runAs**Group**: 1337
>         volumeMounts:
>         - mountPath: /etc/istio/proxy
>           name: istio-envoy
>         - mountPath: /etc/certs/
>           name: istio-certs
>           readOnly: true
>       initContainers:
>       - args:
>         - -p
>         - "15001"
>         - -u
>         - "1337"
>         - -m
>         - **TPROXY**
>         - -i
>         - '*'
>         - -x
>         - ""
>         - -b
>         - 9080,
>         - -d
>         - ""
> 

and yet, when I nsenter any of the deployed pods, I only see the original open port(by the application, for example 9080 in bookinfo, and 15000 for admin but no 15001)

> root@***:~# netstat -l
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State
> tcp        0      0 localhost:15000         *:*                     LISTEN
> tcp        0      0 *:9080                  *:*                     LISTEN
> Active UNIX domain sockets (only servers)
> Proto RefCnt Flags       Type       State         I-Node   Path

@rlenglet  I know you mess with TPROXY a lot in Istio ;) 
Thanks

**Comment by ijsnellf** [comment]
cc @costinm

**Comment by rlenglet** [comment]
@galniv1 The `proxyv2` image in Istio 1.0.0 doesn’t support TPROXY anymore. That got broken in https://github.com/istio/istio/pull/5846. You have to use the `proxytproxy` image now, cf. https://github.com/istio/istio/pull/6873. I think that’s the only change you have to make.

**Comment by 0xCA7F00D** [comment]
@rlenglet thank you very much for your help.
It in fact worked, but I don't understand something,
I read #5679 and haven't managed to figure out the current state of transparent proxy in Istio.
how does it help you as a user ? my original intention was to get the result Lin expected.
You wrote down there that the proxy itself will see the original ip, which it already observes in redirection, than what is the difference between the two modes, if there's any difference ?
(other than TPROXY requiring CAP_SYS_ADMIN which is a problem for itself ;) but I understand why )

**Comment by rlenglet** [comment]
@0xCA7F00D The benefit currently is that Envoy will see the original source IPs, so Mixer can report the real source IPs, you can apply policies on source IPs, etc.
TPROXY is also more efficient than REDIRECT.

**Comment by 0xCA7F00D** [comment]
@rlenglet 
I get that, but from what I understand, iptables REDIRECT only alters the destination ip(and port, of course) to localhost, which leads to Envoy still getting the correct source ip which is not changed.
From the man page:

> "It redirects the packet to the machine itself by changing the destination IP to the primary address of 
the incoming interface (locally-generated packets are mapped to the localhost address, 127.0.0.1 for IPv4 and ::1 for IPv6)."

If that's right, there is no use currently for TPROXY in Istio(or as you said, the reason is efficiency).
I am talking about incoming traffic of course.

**Comment by hzxuzhonghu** [comment]
@rlenglet  I have the same doubt

**Comment by hzxuzhonghu** [comment]
BTW, I can only access my service only when using images `costinm/proxytproxy:tproxy`. 

However, when I checkout master branch, and exec `make docker.proxytproxy` to build a new image. 
Then, I set `sidecar.istio.io/interceptionMode: TPROXY` and `sidecar.istio.io/proxyImage` annotation, 
so sadly I can not access my service, and also 15001 port is not open in my pod. 

/cc @costinm @rlenglet I am not sure whether envoy does some regression.

**Comment by anthonyhaussman** [comment]
Hi,

I'm trying to set the TPROXY mode by default on my platform.
I have a simple nginx proxypass to an application for POST resquest.

With a default istio config it returns:
```
[gateway-7fdf49c4ff-p5l2p nginx] 2019/01/30 09:31:19 [error] 8#8: *9 lua tcp socket read timed out, client: 127.0.0.1, server: graphql-stage.api.toto.com, request: "POST / HTTP/1.1", host: "graphql-istio.kube.tt.gg" 
[gateway-7fdf49c4ff-p5l2p nginx] 127.0.0.1 - - [30/Jan/2019:09:31:19 +0000] "POST / HTTP/1.1" 499 0 "-" "curl/7.63.0" 
```

The client returns is IP 127.0.0.1 which is not to be the case. Without istio:
```
[gateway-7fdf49c4ff-jsccd] 192.168.51.99 - - [30/Jan/2019:09:48:20 +0000] "POST / HTTP/1.1" 200 49 "-" "curl/7.63.0" 
```

So, I have modified on my istio (1.0.5) deploy to enable TPROXY mode by default and use the image istio_proxy from cilium:
```
# ConfigMap istio
...
      # CAP_NET_ADMIN capability, which is required to use TPROXY.
      #interceptionMode: REDIRECT
      interceptionMode: TPROXY
      #    
...

# ConfigMap istio-sidecar-injector
...
        - "-m"
        - TPROXY
...
      containers:
      - name: istio-proxy
        image: [[ annotation .ObjectMeta `sidecar.istio.io/proxyImage`  "docker.io/cilium/istio_proxy:1.0.2" ]]
...
        - name: ISTIO_META_INTERCEPTION_MODE
          value: TPROXY
...
          readOnlyRootFilesystem: true
          capabilities:
            add:
            - NET_ADMIN
          runAsGroup: 1337
        restartPolicy: Always
...
```

But even with this configuration. The nginx container continue to return:
```
[gateway-7fdf49c4ff-5ccvh nginx] 2019/01/30 10:09:13 [error] 8#8: *38 lua tcp socket read timed out, client: 127.0.0.1, server: graphql-stage.api.toto.com, request: "POST / HTTP/1.1", host: "graphql-istio.kube.tt.gg" 
[gateway-7fdf49c4ff-5ccvh nginx] 127.0.0.1 - - [30/Jan/2019:10:09:13 +0000] "POST / HTTP/1.1" 499 0 "-" "curl/7.63.0" 
```

The istio-proxy returns some errors:
```
[gateway-7fdf49c4ff-5ccvh istio-proxy] [libprotobuf ERROR external/istio_proxy/src/istio/mixerclient/check_cache.cc:152] Referenced attributes: Absence-keys: context.reporter.kind, source.ip, source.uid, Exact-keys: context.protocol, destination.namespace, destination.port, destination.service, destination.uid, 
[gateway-7fdf49c4ff-5ccvh istio-proxy] [libprotobuf ERROR external/istio_proxy/src/istio/mixerclient/check_cache.cc:150] Response referenced mismatchs with request 
[gateway-7fdf49c4ff-5ccvh istio-proxy] [libprotobuf ERROR external/istio_proxy/src/istio/mixerclient/check_cache.cc:151] Request attributes: attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "connection.mtls" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] bool_value: false 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "context.protocol" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "http" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "context.reporter.kind" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "inbound" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "context.reporter.uid" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "kubernetes://gateway-7fdf49c4ff-5ccvh.westeros" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.ip" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] bytes_value: "000000000000000000000000000000377377n2566$" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.namespace" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "westeros" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.port" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] int64_value: 80 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.service" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "gateway.westeros.svc.cluster.local" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.service.host" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "gateway.westeros.svc.cluster.local" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.service.name" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "gateway" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.service.namespace" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "westeros" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.service.uid" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "istio://westeros/services/gateway" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "destination.uid" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "kubernetes://gateway-7fdf49c4ff-5ccvh.westeros" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "origin.ip" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] bytes_value: "n275024\" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.headers" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_map_value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: ":authority" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "10.174.54.36:80" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: ":method" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "GET" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: ":path" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "accept-encoding" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "gzip" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "user-agent" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "kube-probe/1.13" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "x-b3-sampled" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "1" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "x-b3-spanid" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "70a04d1038aecb78" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "x-b3-traceid" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "70a04d1038aecb78" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "x-forwarded-proto" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "http" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] entries { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "x-request-id" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value: "017d2b81-9520-98b2-bcdc-3aa57bc6e209" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.host" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "10.174.54.36:80" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.method" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "GET" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.path" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.scheme" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "http" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.time" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] timestamp_value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] seconds: 1548842946 
[gateway-7fdf49c4ff-5ccvh istio-proxy] nanos: 509105302 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.url_path" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] attributes { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] key: "request.useragent" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] value { 
[gateway-7fdf49c4ff-5ccvh istio-proxy] string_value: "kube-probe/1.13" 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy] } 
[gateway-7fdf49c4ff-5ccvh istio-proxy]  
```

It's like the TPROXY mode is not working.
Do you have an idea about the issue ?

**Comment by zenvdeluca** [comment]
Running Version: 1.0.5 (GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad-dirty) 

port 15001 isnt listening as expect, per the reasons already described above -- envoy can't establish gRPC config stream to pilot. 

any expectations when should we have istio-proxy image fully functional with TPROXY module ?

**Comment by zuzzas** [comment]
I can give you, people, a solution.

Enable [RunAsGroup](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) feature gate in your cluster. And don't forget to restart everything!

Why should we do this?

Because sidecar-injector's template includes this part. Notice the `runAsGroup` field which is hidden behind a feature flag.
```
          [[ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) "TPROXY" -]]
          capabilities:
            add:
            - NET_ADMIN
          runAsGroup: 1337
          [[ else -]]
          runAsUser: 1337
          [[ end -]]
```

This UID or GID is used in the iptables of a Pod in the `table` in the `OUTPUT` chain:
```
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -d 10.0.0.0/8 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -d 192.168.0.0/16 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -d 172.16.0.0/12 -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
```

If feature flag is not enabled in a cluster, then `envoy` process runs as root/root UID/GID, which means that it gets to the last dreadful rule that redirects *all* TCP traffic, including traffic generated by envoy itself, to `localhost:15001`, which is not being listened on because `envoy` has yet to contact `pilot` and enable virtual listeners, which is impossible because [the ride never ends](https://ih1.redbubble.net/image.473347132.9900/flat,550x550,075,f.u2.jpg).

**Comment by zuzzas** [comment]
@rlenglet 
Should the documentation be changed in regards to the `runAsGroup` feature flag? I've been thinking about opening a PR, but I'm not sure where to put it, since there is not mention of `TPROXY` anywhere in documentation.

**Comment by rlenglet** [comment]
@zuzzas Thanks, that's a great find! I think the [Istio 1.1 doc on the Sidecar resource](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/) may be a good place to document this.
