### ISSUE TITLE
Go mod: Switch to go modules for 1.11+

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#8061]
**Describe the feature request**
With go 1.11 “go modules” is available in standard tools.

Evaluate and switch from dep to “go mod”

**Comment by douglas-reid** [comment]
Has anyone tried playing around with `vgo` + Istio yet?

**Comment by ayj** [comment]
(from https://github.com/golang/go/wiki/Modules)
> Go modules will be an **experimental** opt-in feature in Go 1.11, with the hope of incorporating feedback and finalizing the feature for Go 1.12.

Should we consider waiting until 1.12 when modules are no longer experimental before switching?

**Comment by rshriram** [comment]
+1. I suggest waiting for 1.12.

**Comment by leaxoy** [comment]
Go 1.12 released today

**Comment by douglas-reid** [comment]
FWIW, I believe the notes have updated to suggest that `1.13` is now when they expect modules to be on by default.

**Comment by jwendell** [comment]
Fixed in #13899.
