### ISSUE TITLE
Message "Ratings service is currently unavailable" does not always show up for bookinfo app when applied abort fault rule for ratings service

### ISSUE THREAD

**Issue by apichick** [istio/istio#8069]
**Describe the bug**
In the bookinfo application when I apply virtual-service-ratings-test-abort.xml and I am logged in as user json, I do not always see the message "Ratings service is currently unavailable" even if I would expect so because the faul is configured with percent 100

    fault:
      abort:
[istio-dump.tar.gz](https://github.com/istio/istio/files/2302151/istio-dump.tar.gz)

        percent: 100
        httpStatus: 500

**Expected behavior**
I should always be seeing the message "Ratings service is currently unavailable"

**Steps to reproduce the bug**
In a cluster with mutual TLS enabled and automatic sidecar injection run the following 4 commands:

kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl apply -f samples/bookinfo/networking/destination-rule-all-mtls.yaml
kubectl apply -f samples/bookinfo/networking/virtual-service-ratings-test-abort.yaml

**Version**
Kubernetes version is: 1.10.5-gke.4
Istio version is: 1.0.0

**Is Istio Auth enabled or not?**
Istio Auth is enabled

**Environment**
GCP

**Cluster state**
Attached

**Comment by ymesika** [comment]
My guess is that because you didn't apply the `virtual-service-all-v1.yaml` there is some traffic going (in round-robin) to ratings versions other than v1 where the fault injection isn't applied.

**Comment by apichick** [comment]
Ah ok, that makes sense. Thanks.

**Comment by apichick** [comment]
I applied that but, now it always goes to v1 when logged as jason, how do you control precedence?

**Comment by apichick** [comment]
I was meaning that it does not raise the fault ever.
