### ISSUE TITLE
Update istioctl to remove old mixer configuration endpoint

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#807]
Three steps:
- [x] update tests not to rely on istioctl
- [x] update istioctl to remove mixer subcommand
- [x] update docs for all calls to configure mixer

**Comment by mandarjog** [comment]
https://github.com/istio/istio/pull/809  --> update tests not to rely on istioctl

**Comment by mandarjog** [comment]
https://github.com/istio/pilot/pull/1274 --> update istioctl to remove mixer subcommand

**Comment by mandarjog** [comment]
done.
