### ISSUE TITLE
Permit use of third party grafana

### ISSUE THREAD

**Issue by sdake** [istio/istio#8075]
**Describe the feature request**
Allow third parties that already have a grafana container to converge on one grafana container instead of having two (theirs which may just be pristine upstream grafana container, as well as the Istio grafana container).

This was not possible until grafana 5.y.z added a api versioning field.

**Describe alternatives you've considered**
I can't think of any alternatives, although plenty of approaches exist related to implementation.

**Additional context**
Implementation at a high level should be fairly straightforward.  Two files are injected into a grafana container during build time.  Instead, these could be injected during runtime via a configmap and volume mount.  This would permit third parties to have multiple injected dashboards in the pristine upstream grafana container.

**Comment by douglas-reid** [comment]
@sdake we also have an issue open for publishing our dashboards to grafana's site, easing use of the dashboards without our image. that might address this concern in a different fashion. thoughts?

**Comment by sdake** [comment]
@douglas-reid wfm.  I am not a grafana wizard, so I'm not really clear on the best approach.

Cheers
-steve

**Comment by visheyra** [comment]
I'm currently running istio with my custom grafana.

I get the istio's dash from the raw json from github that I pack as an archive containing the dash + the files needed by grafana for versionning.
All packed in a job for my grafana setup.

To link a third party setup to istio, tweak the grafana part of the helm chart should be sufficient.

I would be glad to help if you need any.

**Comment by gyliu513** [comment]
Also some discussion at https://github.com/istio/istio/issues/2920 as well for reference.

**Comment by sdake** [comment]
Third party grafana is usable as a result of PR: https://github.com/istio/istio/pull/8189.
