### ISSUE TITLE
Managing core dumps

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#8077]
Follow up from #8043 

We can have a mounted volumes where core dumps are stored, and a CronJob that checks the space on the volume and removes older files and/or sends notifications.

Investigate if that mounted volume can auto-scale.

This issue is about managing core dumps in Kubernetes in general, and not so much tied with Istio, thus it is a good first contribution.

**Comment by lichuqiang** [comment]
I'd like to help with this :)

**Comment by andraxylia** [comment]
thanks for contributing @lichuqiang !

**Comment by lichuqiang** [comment]
Have the folks reach an agreement on ideas above?
Or it still need further discussion before we can set about?

**Comment by costinm** [comment]
My primary concern is that core dumps include sensitive information -
private keys, user related info (from in-memory requests fragments), etc.
As such, it is a security/privacy risk. Files on a Volumes is not the right
way to store secret/private data, and RBAC alone is generally not
considered sufficient. Private data at rest must be encrypted, and have
better protection (many orgs have pretty strict rules about it).

The secondary concern is the management of the cores - who is using them,
and for what ?

The third concern is added complexity to the install system and to
administration - versus benefits.

The container disk is supposed to be removed after the container is removed
- I am not very sure how the disk is scrubbed, so I am
not comfortable with even enabling core dumps by default for the same
privacy/security reason.

Maybe including some extra tools and data on the image to allow getting a
stack trace would be ok ? And sending the stack
traces to mixer or some other tool that can aggregate and alert ?

**Comment by andraxylia** [comment]
@costinm stack trace is not always sufficient , we need to be able to enable core files.

Your concerns are valid, so let's see how we can improve the proposal or come up with a better one.

- Core dumps is already an optional feature that can be enabled/disabled by Helm. I am ok with default disabled, it will be up to the users to make an informed decision. cc @ostromart . Can we maybe do a helm upgrade and mount the disk as needed?
- Encryption at rest is supported by https://github.com/kubernetes/kubernetes/issues/30792
