### ISSUE TITLE
Add more configuration options to the retry policy

### ISSUE THREAD

**Issue by arnecls** [istio/istio#8081]
**Describe the feature request**

Currently Istio (v1.0) hard codes the retry policy to `5xx,connect-failure,refused-stream`.
See https://github.com/istio/istio/blob/8f0adf314f58a22a6d54d979ec899277d0f7c1fd/pilot/pkg/networking/core/v1alpha3/route/route.go#L519

It would be great to be able to change this setting to the values allowed by envoy. See https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#config-http-filters-router-x-envoy-retry-on

There are situations where you e.g. might want to differentiate between `5xx` and `gateway-error`.

**Comment by andraxylia** [comment]
I would change the title to "Add more configuration options to the retry policy", since it is already configurable, it is just missing all possible options.

**Comment by arnecls** [comment]
👍 agreed

**Comment by rshriram** [comment]
Per my comments in your other PR, please change the existing retry policy to gateway-error,connect-failure,refused-stream. No point supporting retries for all 5XX. We had 5XX because gateway-error didn’t exist at that time.

**Comment by dunjut** [comment]
Is this feature request approved?

**Comment by arnecls** [comment]
@rshriram here I think using the current values as a default and an additional config option make a lot more sense here than adjusting the fixed standard.
As far as I can see, retry is a http-only feature (so no need for a TCP fallback) and in contrast to outlier detection, the reason for retries depend a lot more on protocol/service logic.
There are for example services where it makes a lot of sense to react on 500s (e.g. if one instance cannot react on a request but another might be able to) while for other services you certainly don't want to do that (e.g. when they are caused by the request and/or retries will take your service offline).

**Comment by rshriram** [comment]
fine. But switch the default setting to gateway errors only. 5XX can be something people explicitly configure.

**Comment by rshriram** [comment]
@pnambiarsf I would be happy to accept any tweaks/improvements to the respective sections in Istio/api .. Thats where these things need to be added..

**Comment by hzxuzhonghu** [comment]
@rshriram I would like do this. 
/assign

**Comment by cmluciano** [comment]
@rshriram does https://github.com/istio/api/pull/679 fix this issue so that we can close this out?

**Comment by pnambiarsf** [comment]
@cmluciano - Not really. We still need https://github.com/istio/istio/blob/8f0adf314f58a22a6d54d979ec899277d0f7c1fd/pilot/pkg/networking/core/v1alpha3/route/route.go#L519 to use the config introduced in istio/api#679

@hzxuzhonghu - are u working on that as well ?

**Comment by hzxuzhonghu** [comment]
Yes, since the commit just cherry-picked to master,  i will vendor it and open a pr.

**Comment by sakthishanmugam02** [comment]
any update on this issue? i tried snapshot version which has support for retryOn. but it is not working. do i need to raise separate issue to track it

**Comment by hzxuzhonghu** [comment]
This should have been fixed by #9840

**Comment by hzxuzhonghu** [comment]
@sakthishanmugam02 Please put up a new issue if this not works well.

**Comment by sakthishanmugam02** [comment]
Before that, I would like to understand the steps i followed is correct or not. @hzxuzhonghu   

APP SERVICE YAML file
~~~~~~~~~~~~~~~~~~~~~

apiVersion: v1
kind: Service
metadata:
  name: app-two-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    name: grpc
  selector:
    app: app-two


ISTIO rules YAML file
~~~~~~~~~~~~~~~~~~~~~

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apps-vs
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /rest-app
    route:
    - destination:
        host: app-one-service
        port:
          number: 8082
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: app-two-service
        port:
          number: 50051
    retries:
      attempts: 3
      perTryTimeout: 20s
      retryOn: unavailable

**Comment by hzxuzhonghu** [comment]
```yaml
// apiVersion: networking.istio.io/v1alpha3
// kind: VirtualService
// metadata:
//   name: ratings-route
// spec:
//   hosts:
//   - ratings.prod.svc.cluster.local
//   http:
//   - route:
//     - destination:
//         host: ratings.prod.svc.cluster.local
//         subset: v1
//     retries:
//       attempts: 3
//       perTryTimeout: 2s
//       retryOn: gateway-error,connect-failure,refused-stream
 ```
The retryOn can not be set.
For grpc, the 'retryOn' should be in https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-retry-grpc-on

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu thanks for the reply. you meant, newer version of envoy is required?

the support in snapshot version is only for http configurable error codes, not for grpc

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu 

Following is my yaml files:
SERVICE 1:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - image: localhost:5000/app-one:1.1
          imagePullPolicy: IfNotPresent
          name: app-one
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: regcred
`
`
apiVersion: v1
kind: Service
metadata:
  name: app-one-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: http
  selector:
    app: app-one
`
SERVICE 2:

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - image: localhost:5000/app-two:1.1
          imagePullPolicy: IfNotPresent
          name: app-two
          ports:
            - containerPort: 50051
      imagePullSecrets:
        - name: regcred
`

`
apiVersion: v1
kind: Service
metadata:
  name: app-two-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    name: grpc
  selector:
    app: app-two
`
ISTIO rules

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 9090
      name: grpc
      protocol: GRPC
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apps-vs
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /rest-app
    route:
    - destination:
        host: app-one-service
        port:
          number: 8082
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: app-two-service
        port:
          number: 50051
    retries:
      attempts: 3
      perTryTimeout: 20s
      retryOn: unavailable
`

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu I have raised an issue to track this case; if you find any issue with my yaml configuration let me know
https://github.com/istio/istio/issues/10391
