### ISSUE TITLE
Distinguish between 5xx and Gateway errors in outlier detection

### ISSUE THREAD

**Issue by arnecls** [istio/istio#8082]
**Describe the feature request**

Currently Istio only supports `consecutive_5xx` for outlier detection. See https://github.com/istio/istio/blob/7c65420e82219d854908e1addc4d19dd3fbce739/pilot/pkg/networking/core/v1alpha3/cluster.go#L381

Enovy however also supports `consecutive_gateway_failure` for outlier detection.
This mode is extremely helpful when dealing with systems that misuse http 500 as "not supported".
See https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_outlier_detection.html

Related to #8081

**Comment by linsun** [comment]
Close since fixes are merged?

**Comment by arnecls** [comment]
Yes.
