### ISSUE TITLE
Flakey configmap test in Galley

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#8084]
Seeing this in multiple places:
```
I0820 20:01:13.293] --- FAIL: TestWatchAccessList_Update (1.03s)
I0820 20:01:13.293] 	configmap_test.go:101: Expected spiffe id to be allowed.
```
Example:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/8040/istio-unit-tests/11882/

@ozevren: assigned to you because you showed up on the git blame. Please re-assign as you see fit.

**Comment by lichuqiang** [comment]
I ran the case hundreds of times, but failed to reproduce the error.
Have I missed something?

**Comment by ayj** [comment]
This should be fixed by https://github.com/istio/istio/pull/7950 which was merged ~22 hours ago. Developers need to rebase against master to pick up the fix.
