### ISSUE TITLE
istio 1.0.0 can't run the bookinfo

### ISSUE THREAD

**Issue by damozhiying** [istio/istio#8096]
sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

sudo kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
virtualservice "bookinfo" configured
Error from server (NotFound): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": the server could not find the requested resource (post gatewaies.networking.istio.io)

**Comment by ymesika** [comment]
I suspect this is due to the old version of your `kubectl`.
We had users reporting this in the past and it got resolved when they upgraded their kubectl version.

**Comment by damozhiying** [comment]
@ymesika 
sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}


you can see the kubectl is latest,

**Comment by ymesika** [comment]
1.6.6 isn't the latest

**Comment by damozhiying** [comment]
@ymesika  thank you very much,i will try again

**Comment by damozhiying** [comment]
@ymesika  i use rancher 2.0 ,docker images is  rancher/rancher ,how to update the kubectl version

**Comment by damozhiying** [comment]
@ymesika rancher/rancher 2.0  can support istio?

**Comment by ymesika** [comment]
@damozhiying Sorry. I'm not familiar with rancher.
Let's keep it open and see if someone else is more familiar with it.

**Comment by damozhiying** [comment]
@ymesika now i update the kubectl to v1.11.1,   istio and bookinfo demo run well,   
everything is ok ,the page http://192.168.3.6:31380/productpage show success,
but i run  kubectl apply -n istio-test -f istio-1.0.0/samples/bookinfo/networking/virtual-service-all-v1.yaml  
![qq 20180822120816](https://user-images.githubusercontent.com/10277950/44442337-25db2900-a604-11e8-9ec6-82a15827a368.png)
 when request the page http://192.168.3.6:31380/productpage same as the before,There is no effect

**Comment by ymesika** [comment]
That's great.
Did you apply the `destination-rule-all.yaml` destination rules?

**Comment by damozhiying** [comment]
@ymesika i think the sidecar not inject into the pod ,but i order execution these yaml

![qq 20180822143522](https://user-images.githubusercontent.com/10277950/44446839-e23eea00-a618-11e8-9706-7ce5ed9b6f90.png)
![qq 20180822143602](https://user-images.githubusercontent.com/10277950/44446841-e408ad80-a618-11e8-8124-0fc0b807296a.png)


So weird

**Comment by ymesika** [comment]
Yes, with sidecar injected you should have 2 containers per pod so it wasn't injected.
Do you have the `istio-sidecar-injector` running in `istio-system`?

**Comment by damozhiying** [comment]
@ymesika 
![qq 20180822154053](https://user-images.githubusercontent.com/10277950/44449833-cf7ce300-a621-11e8-9a2e-b69dd5a14cba.png)

**Comment by damozhiying** [comment]
@ymesika please see ,if the admissionregistration have some error
![qq 20180822154712](https://user-images.githubusercontent.com/10277950/44450161-c6d8dc80-a622-11e8-9e73-85cbd2c8de7c.png)

**Comment by brunoban** [comment]
Did you label your namespace with `istio-injection=enable`?

A `kubectl get namespace -L istio-injection` should show you. If you didn't, do `kubectl label namespace default istio-injection=enabled` and kill the relevant pods, they should be recreated with the sidecars.

**Comment by david-maumenee** [comment]
kube-apiserver process must have the admission-control flag set with the MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission controllers added and listed in the correct order.

With K8s cluster build with Rancher (RKE) this is not by default

To check your apiserver config in a K8s cluster control by Rancher 2, connect to the controle plane node and run
```
docker inspect kube-apiserver | grep admission-control
```

To customize K8s config on rancher see https://github.com/rancher/rancher/issues/15182 and https://github.com/rancher/rancher/issues/14032

**Comment by Carmon-Lee** [comment]
the same for me

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
