### ISSUE TITLE
Proxy lost connection to pilot

### ISSUE THREAD

**Issue by Stono** [istio/istio#8107]
**Describe the bug**
We have a single instance of an app, where the istio-proxy has gotten into an unhealthy state, and has been like that for the last 10 hours.

Apps (see the last one):
```
❯ k -n vehicle-metric-service get pods
NAME                                      READY     STATUS    RESTARTS   AGE
vehicle-metric-service-6fcdb498b5-4rgx5   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-cf4lq   2/2       Running   0          3d
vehicle-metric-service-6fcdb498b5-ctl5r   2/2       Running   0          3d
vehicle-metric-service-6fcdb498b5-gh9rr   2/2       Running   0          3h
vehicle-metric-service-6fcdb498b5-m875j   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-n68tw   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-nnj6p   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-s2zz5   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-sn2xr   2/2       Running   0          4d
vehicle-metric-service-6fcdb498b5-tpvws   1/2       Running   0          3d
```

Logs from the proxy:
```
2018-08-21T05:37:25.306950Z     info    watchFileEvents: notifying
2018-08-21T05:38:28.296330Z     info    watchFileEvents: "/etc/certs/": MODIFY|ATTRIB
2018-08-21T05:38:28.296421Z     info    watchFileEvents: "/etc/certs//..2018_08_20_13_34_47.551428982": MODIFY|ATTRIB
2018-08-21T05:38:38.296563Z     info    watchFileEvents: notifying
[2018-08-21 05:39:46.735][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 13,
[2018-08-21 05:39:46.789][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
[2018-08-21 05:39:46.789][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
[2018-08-21 05:39:48.902][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
[2018-08-21 05:39:48.902][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
[2018-08-21 05:39:49.867][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
[2018-08-21 05:39:49.867][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
[2018-08-21 05:39:52.286][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
[2018-08-21 05:39:52.287][16][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
```

As you can see this container is not appearing in istioctl:

```
❯ istioctl proxy-status | grep vehicle-metric-service
vehicle-metric-service-6fcdb498b5-4rgx5.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-7v7g7     1.0.0
vehicle-metric-service-6fcdb498b5-cf4lq.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-rxw4n     1.0.0
vehicle-metric-service-6fcdb498b5-ctl5r.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-gjxkt     1.0.0
vehicle-metric-service-6fcdb498b5-gh9rr.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-rxw4n     1.0.0
vehicle-metric-service-6fcdb498b5-m875j.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-vz4zf     1.0.0
vehicle-metric-service-6fcdb498b5-n68tw.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-7v7g7     1.0.0
vehicle-metric-service-6fcdb498b5-nnj6p.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-7v7g7     1.0.0
vehicle-metric-service-6fcdb498b5-s2zz5.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-7v7g7     1.0.0
vehicle-metric-service-6fcdb498b5-sn2xr.vehicle-metric-service             SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-7f644fdbb8-vz4zf     1.0.0
```

Pilot is up and running just fine:
```
❯ kis get pods -l istio=pilot
NAME                           READY     STATUS    RESTARTS   AGE
istio-pilot-7f644fdbb8-7v7g7   2/2       Running   0          4d
istio-pilot-7f644fdbb8-gjxkt   2/2       Running   0          4d
istio-pilot-7f644fdbb8-rxw4n   2/2       Running   0          4d
istio-pilot-7f644fdbb8-vz4zf   2/2       Running   0          4d
```

Restarting the pod fixed it.

**Comment by Stono** [comment]
cc. @nmittler your health checks would presumably catch this?  downside it'd just be "unready" whereas really, it needs to restart.

**Comment by Stono** [comment]
@nmittler I think readiness as you have done it is fine for both startup, disruption (migration) and intermittent issues, but I do think you need liveness probes too.

It could even be the same as your readinessProbe but with a `failureThreshold` much higher, so what we're basically saying is - "if you've got bad config for 30 seconds or so, you're unready, but if that persists for 10 minutes, there's probably a bigger issue and kubernetes should try restarting you".

You could get clever too, if your pod is being restarted due to a liveness probe failing, allow people to opt-in to a pre-shutdown which gathers debug information and sends it to you for debugging before the SIGTERM is handled by istio-proxy.

**Comment by nmittler** [comment]
@costinm @rshriram @mandarjog @PiotrSikora @Stono 

After discussing with @mandarjog we think we can simplify the approach so long as we have both readiness and health checks.  I think our issue so far is that we've been conflating the two (both in discussions and with my initial attempt at the readiness logic). We propose separating the roles of the two probes as follows:

- **Readiness**: At startup of the `istio-proxy` container, the agent will poll the stats of Envoy until there have been CDS and LDS updates, and there are no warming clusters or listeners. Once this condition is met, `istio-proxy` will report ready indefinitely. The connection state to Pilot will not be involved in the readiness decision. Readiness will just indicate that clusters and listeners have been received from Pilot and that should be enough to support communication, even in the event that the connection to Pilot is lost.

- **Health**: the health probes will monitor the connection between Envoy and Pilot. When the connection is lost, `istio-proxy` will continue reporting healthy until some threshold (10 min?). This will cause k8s to eventually restart the container (causing the readiness logic will restart as well). Eventually healthiness may take other factors into account as well, but this is enough for the current task.

Thoughts/concerns?

**Comment by Stono** [comment]
Sounds spot on to me @nmittler

**Comment by PiotrSikora** [comment]
@nmittler I agree on the **Readiness** probe, but still disagree on the **Health** probe being conditional on a connection to Pilot, since misbehaving Pilot will effectively bring the whole, otherwise healthy, cluster down.

**Comment by nmittler** [comment]
@Stono 

> Actually ... One point. Why have it tranisiton to "unhealthy" state and rely on a liveness probe to restart it, vs just exiting with a non zero status code which would trigger a reload anyway?

I'd rather stick with the k8s idioms here.  Do you see an advantage of forcing the app to quit?

**Comment by nmittler** [comment]
@costinm @rshriram @mandarjog @PiotrSikora 

from @PiotrSikora's comment:

> still disagree on the Health probe being conditional on a connection to Pilot, since misbehaving Pilot will effectively bring the whole, otherwise healthy, cluster down.

We had an offline discussion and I agree that this just kicks the can a bit.  We can pick a large threshold, but what is a good value? A day? 3 days? Regardless, after that time the entire cluster would go down.

A better solution might be to make health a function of outbound request failures.  Assuming we have some metric for "badness" (i.e. a lot of outbound requests are failing ... or maybe we have a lot of outbound clusters that have 100% failures), then health could be something like this:

```golang
healthy := connectedToPilot && outboundTrafficOK
```
Obviously, the hard part will be determining `outboundTrafficOK`. I suspect we'll need a design doc with a lot of heated discussion to determine a good metric :).

Does this make sense?

**Comment by Stono** [comment]
Closing this, there's been so much change since i had it, i'll open a new issue if it all arises again
