### ISSUE TITLE
Allow users to run mixer per node

### ISSUE THREAD

**Issue by linsun** [istio/istio#8130]
a couple of side conversation with @ymesika @geeknoid and @elevran @dcberg this seems a good option to allow user to configure.

**Comment by ymesika** [comment]
It's possible to run Mixer per node but it's not just a matter of configuration and will require some code changes to support that.

The first question is what Mixer we want per node - Policy, Telemetry or both.

One approach, yet the simplest, of per-node is running the pods as `DaemonSets`. However when we discuss Mixer then it isn't that straightforward. Currently mesh config has the addresses and ports of both Mixer services configured before installing Istio. With DaemonSet, calling the service won't guarantee accessing the local Mixer port. So we need to configure the address to the local pod in the config and that's unknown and might change with the pod lifecycle.

There are possibly other approaches and one of them might be using Affinity and Anti-Affinity to gain similar results but I suspect they too have their cons.

**Comment by linsun** [comment]
I think getting istio-policy running per node is more interesting as it is in the request flow so having it call local host can reduce network trips calling out to centralized mixer and hold up the call.

istio-telemtry running per node isn't that interesting IMHO as it doesn't block the request.

**Comment by kyessenov** [comment]
Telemetry:
Per-node telemetry is actually fairly common. See https://kubernetes.io/docs/concepts/cluster-administration/logging/ for the architecture overview. Fluentd runs as a daemonset: https://github.com/GoogleCloudPlatform/container-engine-customize-fluentd/blob/master/kubernetes/fluentd-daemonset.yaml

Policy:
Per-node policy is also quite common. Calico uses a daemon set communicating with pods over host network UDS port: https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml.
