### ISSUE TITLE
Add Incremental MCP support 

### ISSUE THREAD

**Issue by ayj** [istio/istio#8148]
Add support for incremental update support for Mesh Control Protocol (MCP) based on [incremental xDS](https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md#incremental-xds). This provides the following benefits:

- Per-resource versioning. This aligns more closely with k8s CRD's notion of resource version for the purposes of tracking e2e operational status of configuration.
- Session resumption
- More efficient delivery and state management. Clients can apply incremental diffs at the per-resource version level which potentially avoids unnecessary memory allocations and GC.

This consists of four work items:

- [x] update istio.io/api/mcp - add `IncrementalMeshConfig{Request,Response}` messages and `IncrementalAgregatedResources` rpc method to `StreamAggregatedResources` (https://github.com/istio/api/pull/620)
- [x] implement MCP server support 
- [x] implement MCP client support
- [ ] update Pilot / Mixer to use incremental update feature of MCP client

**Comment by lichuqiang** [comment]
Sounds interesting.
I'd like to help if possible (perhaps some of the downside implementations).

**Comment by Nino-K** [comment]
Just wondering what is the status of the server/client support for incremental updates? I would like to help on this.

**Comment by linsun** [comment]
is this targeted for 1.1 @ayj ?

**Comment by ayj** [comment]
Yes, we'd like to get this into 1.1 now that we're targeting beta status in January.

**Comment by linsun** [comment]
ok @irisdingbj can probably help out with this in jan.

**Comment by ayj** [comment]
Thanks @Nino-K @linsun. I've started the client/server implementation for incremental MCP. Incremental is not directly compatible with the non-incremental version, but the package-level interfaces should be pretty close. Switching over to the new implementation should be somewhat straightforward since we haven't shipped Istio w/MCP yet (no backwards compat. issues across upgrades).

I believe @Nino-K was going to look into adding some targeted benchmarks to Pilot so we can track config/MCP perf over time. There may be additional profiling/optimization work for @irisdingbj to take up in Jan.

**Comment by ayj** [comment]
Incremental MCP support is now available as an option in Galley. It is off by default and can be enabled with a few lines of code. 

Additional changes are required in Pilot to enable integration of incremental MCP support. This is tracked by https://github.com/istio/istio/issues/10497.

Incremental support in Mixer can be tracked in another issue, or we can post-postpone that work assuming MixerV2 architecture where a standalone mixer doesn't exist.
