### ISSUE TITLE
Failed to set up host by minikube

### ISSUE THREAD

**Issue by m1093782566** [istio/istio#8159]
**Describe the bug**

Failed to set up host by minkube scripts after installing minikube. ERROR logs:

```
root@instance-2:/home/dj199008/gopath/src/istio.io/istio/tests/e2e/local/minikube# ./install_prereqs_debian.sh 
Hit:1 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:3 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='/root/.minikube/machines/minikube/minikube.rawdisk'/>
      <target dev='hda' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <mac address='3c:5e:ec:03:07:33'/>
      <model type='virtio'/>
    </interface>
    <interface type='network'>
      <source network='minikube-net'/>
      <mac address='3c:5e:ec:03:07:33'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <rng model='virtio'>
      <backend model='random'>/dev/random</backend>
    </rng>
    
  </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')
E0823 02:56:11.519867    3964 env.go:330] Error setting machine env variable(s): Error getting ip from host: machine in unknown state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
The connection to the server localhost:8080 was refused - did you specify the right host or port?
kube-proxy not ready, will check again in 5 sec
The connection to the server localhost:8080 was refused - did you specify the right host or port?
kube-proxy not ready, will check again in 5 sec
...
```

**Expected behavior**

Can successfully set up a kubernetes host using minikube scripts.

**Steps to reproduce the bug**

./install_prereqs_debian.sh -- successfully

./setup_host.sh -- failed

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Is Istio Auth enabled or not?**
{{ Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input }}

**Environment**
Ubuntu 18.04

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by m1093782566** [comment]
The error message is 

```
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')
```

@gargnupur do you have any information?

**Comment by gargnupur** [comment]
Can you please check if virtualization is enabled in your bios?
dmesg | grep kvm

And if it is, can you please try running "sudo modprobe kvm" (This step is now included in prereqs install step which was not there before)

**Comment by m1093782566** [comment]
Thanks for your prompt reply @gargnupur 

The output of `dmesg | grep kvm`

```
[    0.000000] kvm-clock: cpu 0, msr 2:3ff52001, primary cpu clock
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: using sched offset of 12810634734 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.004000] kvm-clock: cpu 1, msr 2:3ff52041, secondary cpu clock
[    0.004000] kvm-clock: cpu 2, msr 2:3ff52081, secondary cpu clock
[    0.004000] kvm-clock: cpu 3, msr 2:3ff520c1, secondary cpu clock
[    0.312092] clocksource: Switched to clocksource kvm-clock
[    3.791244] systemd[1]: Detected virtualization kvm.
```

Seems kvm is detected?

I also run `modprobe kvm` and `lsmode | grep kvm` and found kvm module is already installed in my kernel.

```
kvm                   598016  0
irqbypass              16384  1 kvm
```

But, it still does not work.

When I run `kvm-ok`, it tells me 

```
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
```

I am not sure if it matters? PS. I just launched a GCE VM with Intel Haswell platform CPU.

**Comment by m1093782566** [comment]
minikube `--vm-driver=none` works for me now :)

@hklai Can we support `--vm-driver=none` in local minikube setup?

**Comment by hklai** [comment]
@m1093782566 Sure, and https://github.com/istio/istio/pull/8648 is in.
