### ISSUE TITLE
Need guidelines for creating out-of-tree mixer adapters

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#8190]
**Describe the feature request**
Currently, it's possible to have out-of-process adapters via gRPC. It'd be great to have these adapters out of Istio tree. Good documentation around this would be really helpful.

**Comment by theganyo** [comment]
+1. And I could potentially help around this... once I get mine working.

**Comment by venilnoronha** [comment]
I've created a Wiki page to address this. You can find it at https://github.com/istio/istio/wiki/%5BPreliminary%5D-Mixer-Out-of-Tree-Adapter-Walkthrough.
