### ISSUE TITLE
Improve config.pb.go generation for out-of-tree adapters

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#8191]
**Describe the feature request**
The [instructions](https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough) for creating out of process adapters suggests the following command for generating `config.pb.go`.

```go
//go:generate $GOPATH/src/istio.io/istio/bin/mixer_codegen.sh -a mixer/adapter/mygrpcadapter/config/config.proto -x "-s=false -n mygrpcadapter -t metric"
```

This has a couple of problems when working with out-of-tree adapters.

1. It depends on `$GOPATH/src/istio.io/istio`.
2. Needs the adapter to be at a relative location within the istio repo i.e. `mixer/adapter/mygrpcadapter`.

One way to improve this would be to extract the codegen components into a seperate `go` package and use it to build adapters just by vendoring it.

/cc @mandarjog @oaktowner

**Comment by ashutoshraina** [comment]
I am also interested in this, as this makes OOT adapter development very difficult.

**Comment by venilnoronha** [comment]
The whole adapter development model is going to change soon with the Mixer v2 architecture.

**Comment by mandarjog** [comment]
closing, this does not apply any more.
