### ISSUE TITLE
gometalinter failed to report lint errors due to missing dependencies

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#8202]
**Describe the bug**
[gometalinter](https://github.com/istio/istio/blob/78d2f0e7770557872a66a3886d8d5a3eef1863dc/bin/linters.sh#L33) is one of the lint tools that will be ran when invoking `make lint`. However it failed to report a tons of lint errors when running in CircleCi due to missing dependencies.

**Expected behavior**
`gometalinter` reports all lint errors.

**Steps to reproduce the bug**
See how #8200 triggered a ton of lint failures without changing a single line of source code.

**Root cause**
#8201 enabled the debug logging for `gometalinter` and the output is [here](https://gist.github.com/yangminzhu/18694549d68314d99a2a006ac827f0a7). Check the output and note that `vet`, `errcheck` `maligned`, `vetshadow`, `megacheck`, `varcheck`, `structcheck`, `unconvert` failed to finish the lint due to:
```
warning: /go/bin/unconvert returned exit status 1: /go/src/istio.io/istio/mixer/pkg/protobuf/yaml/testdata/all/types.pb.go:18:14: could not import github.com/gogo/protobuf/proto (cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/local/go/src/github.com/gogo/protobuf/proto (from $GOROOT)
	/go/src/github.com/gogo/protobuf/proto (from $GOPATH))
/go/src/istio.io/istio/mixer/pkg/protobuf/yaml/testdata/all/types.pb.go:21:29: could not import istio.io/api/policy/v1beta1 (cannot find package "istio.io/api/policy/v1beta1" in any of:
	/usr/local/go/src/istio.io/api/policy/v1beta1 (from $GOROOT)
	/go/src/istio.io/api/policy/v1beta1 (from $GOPATH))
/go/src/istio.io/istio/mixer/pkg/protobuf/yaml/testdata/all/types.pb.go:29:17: could not import github.com/gogo/protobuf/sortkeys (cannot find package "github.com/gogo/protobuf/sortkeys" in any of:
	/usr/local/go/src/github.com/gogo/protobuf/sortkeys (from $GOROOT)
	/go/src/github.com/gogo/protobuf/sortkeys (from $GOPATH))
```
And note that `gometalinter` doesn't report such failures and `make lint` still succeeded in this PR.

**Solution**
We could fix the issue by installing necessary dependencies before invoking `gometalinter` as I did in  #8200. This might break again in the future if we depend on some new packages but forget adding to `linters.sh` and I'm not sure if there are any better ways to fix this. And no matter what option we choose, we'll need to fix the existing tons of lint errors. (I'll try to do this with the lint fix in one big PR)

@geeknoid @hklai WDYT?

**Comment by yangminzhu** [comment]
@geeknoid 
Yeah, we cannot fix it simply like #8200, it's not reliable and people may run `make lint` locally and I don't want to change their local environment.

I think the root cause is those lint tools doesn't support vendoring? so I'm afraid it's hard to write a test that have a good coverage on possible failing cases, like in this one, we don't know those tools will fail for a missing dependency. 

Maybe we should update `gometalinter` to treat the tool failures also as errors. (But it seems it doesn't support this for now).

To fix the `gometalinter`, I'm thinking maybe we can set the `GOPATH` to also include the vendor directory before running `make lint` in CirecleCI and reset it to default after the run. This should be able to workaround it but I haven't tried it yet. Do you think it's okay to do so?

**Comment by kyessenov** [comment]
We used to run linters in a docker container, since that clearly solved all the dependency issues. Maybe we should just go back to that to at least get some functional linter enabled?

I don't like changing user's environment in general (installing software or messing with GOPATH).

**Comment by yangminzhu** [comment]
@kyessenov 
I mean only changing the $GOPATH in CircleCI, Not in user environment or `Makefile`. we have all the dependencies in the `istio.io/istio/vendor` directory, It seems it's just these line tools doesn't work with the vendored dependencies.
So even if running in a docker container, we still need to put those dependencies under `src` package if we do not want to change `$GOPATH`? and I feel this is not reliable as the dependency could change anytime.
