### ISSUE TITLE
root-cert.pem is expired

### ISSUE THREAD

**Issue by yellowred** [istio/istio#8205]
**Describe the bug**
Enabling jwt Policy `jwt-example` from Authentication tasks causes error when I try to connect to httpbin:
```
$ curl -v localhost/ip
upstream connect error or disconnect/reset before headers
```

 Checking certificates:
```
kubectl get secret istio.default -o jsonpath='{.data.root-cert\.pem}' | base64 --decode | openssl x509 -noout -text | grep "Not After"
            Not After : Aug 23 08:46:00 2019 GMT
```

**Expected behavior**
Expected successful response HTTP 200

**Steps to reproduce the bug**
Install istio 1.0 on a fresh kubernetes cluster. Follow Authentication tasks steps.

**Version**
1.0

**Is Istio Auth enabled or not?**
Istio was installed without mTLS
```
ubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
helm init --service-account tiller
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```
After that mTLS was enabled for a namespace following Authentication task.

**Environment**
Docker for Mac

**Comment by quanjielin** [comment]
It's still valid to 2019  - ```Not After : Aug 23 08:46:00 2019 GMT```

**Comment by yellowred** [comment]
Looks like the cert was updated
