### ISSUE TITLE
ServiceEntry with resolution DNS sometimes mapped to cluster of type EDS 

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#8220]
**Describe the bug**
I want to connect an external MySQL database, i.e. plain TCP communication over port 3306.
The database has an external hostname.
In the cluster I want to make this database available under a different hostname.

Therefore I create a Service to make the DNS name available in the cluster, e.g. `ext/istioprovider-dev-tcp`.
Then I created a ServiceEntry that uses the clusterIP of the service as address and maps to the URL of Mysql. That means the ServiceEntry maps to a host name, not an IP address.
Finally I create a DestinationRule that disables TLS for this communication as auth is enabled.
Both ServiceEntry and DestinationRule use the host name matching the fully qualified hostname of the service, i.e. `istioprovider-dev-tcp.ext.svc.cluster.local

Intermittently the ServiceEntry seems to be mapped to a cluster with type EDS so that the target host name is discarded and I see this error in the pilot log:
```
2018-08-24T10:38:38.577956Z     error   ads     EDS: unexpected pilot model endpoint v1 to v2 conversion: invalid IP address url.to.mysql.com
2018-08-24T10:38:38.586807Z     info    ads     CDS: PUSH for testcurl-8659b9654f-wtfts.default "127.0.0.1:51256", Clusters: 46
2018-08-24T10:38:38.807104Z     info    ads     ADS: RDS: PUSH for node: testcurl-8659b9654f-wtfts.default addr:127.0.0.1:51256 routes:11
2018-08-24T10:38:38.819091Z     info    ads     ADS: RDS: PUSH for node: mysql-client-766b4b7945-9dmlh.default addr:127.0.0.1:56366 routes:11
2018-08-24T10:38:38.846244Z     info    ads     LDS: PUSH for node:testcurl-8659b9654f-wtfts.default addr:"127.0.0.1:51256" listeners:28
2018-08-24T10:38:38.855458Z     info    ads     LDS: PUSH for node:mysql-client-766b4b7945-9dmlh.default addr:"127.0.0.1:56366" listeners:28
2018-08-24T10:38:38.855549Z     info    ads     Push finished: 353.315099ms {
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "10.106.63.103:3306": {
                "proxy": "mysql-client-766b4b7945-9dmlh.default",
                "message": "Listener=10.106.63.103:3306 AcceptedTCP=istioprovider-dev-tcp.ext.svc.cluster.local RejectedTCP=istioprovider-dev-tcp.ext.svc.cluster.local TCPServices=1"
            }
        },
        "pilot_eds_no_instances": {
            "outbound|3306||mysql-dev.default.svc.cluster.local": {},
            "outbound|80||istioprovider-dev.ext.svc.cluster.local": {}
        },
        "pilot_no_ip": {
            "mysql-client-766b4b7945-9dmlh.default": {
                "proxy": "mysql-client-766b4b7945-9dmlh.default"
            },
            "testcurl-8659b9654f-wtfts.default": {
                "proxy": "testcurl-8659b9654f-wtfts.default"
            }
        }
    },
    "Start": "2018-08-24T10:38:38.502230469Z",
    "End": "2018-08-24T10:38:38.85550338Z"
}
```

**Expected behavior**
I expect that traffic to the istioprovider-dev-tcp.ext:3306 is reliably forwarded to the external address.

The output of `istioctl pc cluster` clearly shows that the cluster is classified as EDS, which doesn't seem to be right.

The configuration of a ServiceEntry should always override the configuration of a Service. 
Or is there another way to make the name available inside the Istio cluster?

**Steps to reproduce the bug**
I created a configuration with this Kubernetes Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-24T10:38:34Z
  name: istioprovider-dev-tcp
  namespace: ext
  resourceVersion: "1851612"
  selfLink: /api/v1/namespaces/ext/services/istioprovider-dev-tcp
  uid: da2f11cb-a789-11e8-8da5-025000000001
spec:
  clusterIP: 10.106.63.103
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Additionally I have these Istio CRDs:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  clusterName: ""
  creationTimestamp: 2018-08-24T10:38:34Z
  generation: 1
  name: istioprovider-dev
  namespace: ext
  resourceVersion: "1851613"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/ext/serviceentries/istioprovider-dev
  uid: da445e0f-a789-11e8-8da5-025000000001
spec:
  addresses:
  - 10.106.63.103
  endpoints:
  - address: url.to.mysql.com
    ports:
      tcp: 3306
  hosts:
  - istioprovider-dev-tcp.ext.svc.cluster.local
  ports:
  - name: tcp
    number: 3306
    protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
  clusterName: ""
  creationTimestamp: 2018-08-24T10:38:35Z
  generation: 1
  name: istioprovider-dev
  namespace: ext
  resourceVersion: "1851614"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/ext/destinationrules/istioprovider-dev
  uid: da7dfeee-a789-11e8-8da5-025000000001
spec:
  host: istioprovider-dev-tcp.ext.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 1.000s
    tls: {}
```

**Version**
Istio:
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
I installed Istio with helm:
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system -f install/kubernetes/helm/istio/values-istio-auth.yaml --no-crd-hook
```
Additionally set `auth_policy: MUTUAL_TLS` in the istio config map, otherwise it looks like mTLS isn't used.

**Environment**
Locally on a single node cluster with Docker for Mac

**Cluster state**
[clusters.txt](https://github.com/istio/istio/files/2318111/clusters.txt)
[route.txt](https://github.com/istio/istio/files/2318112/route.txt)
[listeners.txt](https://github.com/istio/istio/files/2318114/listeners.txt)

**Comment by robertpanzer** [comment]
To clarify the meaning of "intermittently":
Sometimes after I create these resources the route works reliably.
Sometimes after I create these resources the route does not work at all.

**Comment by robertpanzer** [comment]
A reliable way to reproduce this is to first create the Istio resources.
After these changes are pushed out to the istio proxies create the Kubernetes service.
Then the cluster seems to have type EDS.

If I create the Kubernetes service first, wait a bit and then create Istio resource it seems to behave properly.

Currently I have an automated way to create the resources in the sequence Kubernetes service first – to get the ClusterIP – and Istio CRDs after that, but this is within a few milliseconds.
Therefore I could imagine that this is a race condition that depends on who is reported first by the watchers.

**Comment by rshriram** [comment]
Overriding service registry level services is not supported. So the behavior is undefined when you try to reuse an already allocated service VIP as you seem to do above.
See if this helps: https://github.com/rshriram/istio-coredns-plugin
where you create the service entry with the appropriate IP. You need to program your KubeDNS to forward to this coreDNS as the upstream DNS server for the desired domains.

**Comment by robertpanzer** [comment]
Thanks for your response.
The plugin gives a good idea where to go and where to start.

**Comment by iftachsc** [comment]
Hi,
This seems related to my goals which I’m not able to get. I have 3 external tco endpoints(eg redis cluster) I am trying to create a combo ration of a Kubernetes service(without selector) maybe with manually created endpoints  and a service entry so pods inside the mesh can address the host (service name and host in serviceentry) and to be able to be loadbalancer on these 3 endpoints. I expected to be able to do this only with servicenetry but cannot make this work. Is this possible?
