### ISSUE TITLE
If telemetry server is down or slow, envoy crashes

### ISSUE THREAD

**Issue by costinm** [istio/istio#8224]
Discussed on slack: to repro create a high load (2-3000 qps) on ingress, and kill the mixer pods.
The ingress shows a number of error messages that report can't be reached, and crashes (with 
'signal: killed' message). 

It is likely the mixer plugin doesn't have the right deadline or can't shed load. Telemetry should fail open.

**Comment by costinm** [comment]
For 1.0.2

**Comment by lizan** [comment]
It is likely due to OOM. What do we expect for this other than not failing, should mixer write pending reports temporarily to disk, or just drop the pending reports?

**Comment by mandarjog** [comment]
Dropping is fine. This should only happen if no other upstream mixers are available.

I don’t think retry policy is set or used on this code path.

**Comment by kyessenov** [comment]
Dropping but recording how much got dropped. Endlessly accumulating failed RPCs seems like an anti-pattern. 

/ref https://github.com/istio/istio/issues/5095

**Comment by duderino** [comment]
I'll try this one

**Comment by munrodg** [comment]
Moving to P1 pending testing feedback

**Comment by douglas-reid** [comment]
@duderino I'm going to close this, as we have adopted loadshedding by default for the mixer services. Moving forward, we are pursuing a future architecture without Mixer, so this issue is not likely to receive any further direct attention.

**Comment by duderino** [comment]
@douglas-reid sorry I forgot to circle back on this one. bug fixes that went into 1.1 fixed at least one of the crashes and considering there was no additional commentary on this bug that may have been the primary source.
