### ISSUE TITLE
Istio 1.0.2 Tracker

### ISSUE THREAD

**Issue by rkpagadala** [istio/istio#8225]
1.0.1 patch has been released on the 1.00 train.
We may create another patch release 1.0.2 next month if there are critical issues* in 1.0.1.

If you have any PRs that should be considered for 1.0.2, please add them to this issue.

(*) Critical Issues Definition
Regression of a feature that is used by customers in prior releases.
Runtime crashes that severely regress stability of the system (i.e. SLO)

**Comment by rkpagadala** [comment]
Referencing #7672 which is tracker for 1.0.1

**Comment by k** [comment]
#7553

**Comment by sdake** [comment]
This may remove a regression - pending review: https://github.com/istio/istio/pull/8250

**Comment by PiotrSikora** [comment]
#8310 - easily reproducible istio-proxy segfaults, IMHO warrants 1.0.2 as soon as it's fixed.

cc @costinm @louiscryan

**Comment by rkpagadala** [comment]
@k regarding #7553 please cherrypick to branch release-1.0 and send a PR

**Comment by k** [comment]
@rkpagadala okay waiting on #8416 for a bug fix

**Comment by sdake** [comment]
gateway-telemetry feature has been DOA since 1.0.0 - https://github.com/istio/istio/pull/8450

**Comment by sdake** [comment]
Istio multicluster failure in many scenarios since the introduction of envoyv2 discovery - https://github.com/istio/istio/pull/8451

**Comment by pennyluis** [comment]
Approve

**Comment by hklai** [comment]
Update: we can cutting 1.0.2 for two urgent bug fixes:
https://github.com/istio/istio/pull/8452
https://github.com/istio/istio/pull/8389

Some earlier mentioned PRs will also be included:
https://github.com/istio/istio/pull/8252
https://github.com/istio/istio/pull/8250

Here is a list of all included commits since 1.0.1
https://github.com/istio/istio/compare/1.0.1...release-1.0

Other bug fixes are pushed to 1.0.3.

**Comment by sdake** [comment]
@hklai - can you confirm everything in https://github.com/istio/istio/compare/1.0.1...release-1.0 will be released in 1.0.2?  Specifically looking for the merged https://github.com/istio/istio/pull/8377 to make 1.0.2 as multicluster is semi-DOA without it.

Cheers
-steve

**Comment by hklai** [comment]
@sdake Right, #8377 will be included.

**Comment by hklai** [comment]
RC for 1.0.2 is available at
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180905-18-29/

Please test it and report problem, if any.

**Comment by PiotrSikora** [comment]
@hklai I verified that RC works fine (i.e. no more proxy segfaults), thanks!

**Comment by hklai** [comment]
The RC had been verified by @costinm, @myidpt, @mandarjog and @PiotrSikora.

We will proceed to cut the release today.

**Comment by hklai** [comment]
https://github.com/istio/istio/releases/tag/1.0.2 is published.
