### ISSUE TITLE
DestinationRule subset.name and VirtualService subset validation error typo

### ISSUE THREAD

**Issue by kronin** [istio/istio#8227]
**Describe the bug**
When creating a DestinationRule with an invalid subset.name (one that is not a valid DNS1123 label), the error message is:
"Error: validation error: subnet name is invalid: foo.bar" 

**Expected behavior**
The error message should be:
"Error: validation error: subset name is invalid: foo.bar"

**Steps to reproduce the bug**
istioctl create -f foo.yaml <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-service
  namespace: default
spec:
  host: my-service
  subsets:
  - labels:
      version: major.minor
    name: major.minor
EOF

**Version**
istio 1.0.0
kubernetes 1.9.9

**Is Istio Auth enabled or not?**
Helm install

**Environment**
AWS

**Comment by kronin** [comment]
It's a one-character change in pilot/pkg/model/validation.go line 2051(master). Current employer makes it very difficult to contribute, else I'd submit a patch:

func validateSubsetName(name string) error {
        if len(name) == 0 {
                return fmt.Errorf("subset name cannot be empty")
        }
        if !IsDNS1123Label(name) {
                return fmt.Errorf("subnet name is invalid: %s", name)
        }
        return nil
}

Proposed patch on master:
diff --git a/pilot/pkg/model/validation.go b/pilot/pkg/model/validation.go
index 0e747f2d6..bb94114d3 100644
--- a/pilot/pkg/model/validation.go
+++ b/pilot/pkg/model/validation.go
@@ -2048,7 +2048,7 @@ func validateSubsetName(name string) error {
                return fmt.Errorf("subset name cannot be empty")
        }
        if !IsDNS1123Label(name) {
-               return fmt.Errorf("subnet name is invalid: %s", name)
+               return fmt.Errorf("subset name is invalid: %s", name)
        }
        return nil
 }

**Comment by hzxuzhonghu** [comment]
Thanks @kronin
