### ISSUE TITLE
Support install local test environment for Centos Platform

### ISSUE THREAD

**Issue by m1093782566** [istio/istio#8239]
**Describe the feature request**
Currently minikube and vagrant installation scripts only support debian/ubuntu and macos platform, for many centos users, there is no way to install a local test environment.

**Describe alternatives you've considered**
Support install local test environment for Centos Platform

**Additional context**
If no one has objections to this, I volunteered to send a PR.

cc @costinm @hklai @JimmyCYJ @gargnupur @nmittler any comments?

**Comment by hklai** [comment]
Contribution is certainly welcome. =)

**Comment by m1093782566** [comment]
@hklai Thanks for your positive response :)

I will send a PR in recent days and will assign you for review when it's ready :)

**Comment by m1093782566** [comment]
I just sent out a PR(#8248), please check :)
