### ISSUE TITLE
High RAM usage for istio-proxy

### ISSUE THREAD

**Issue by Stono** [istio/istio#8247]
Hey,
The bump to 1.0.1 has significantly improved my boot times, yay, but I'm noticing a little higher memory footprint for the sidecars, they're all circa 220meg(ish) on our preprod cluster:

Numbers: 
  - VirtualServices: 45
  - ServiceEntry: 14
  - Services: 76
  - Pods: 214

<img width="286" alt="screen shot 2018-08-26 at 08 32 33" src="https://user-images.githubusercontent.com/1486729/44625895-b8ccd980-a90a-11e8-8608-b0023dab30a1.png">

Adding 250ish meg of ram to the memory footprint of every pod, some of which only use around 500meg themselves is quite a bit of an overhead.

Interestingly, they're significantly less in dev (which has less apps on it, thus less services), so there appears to be a correlation:

Numbers:
  - VirtualServices: 22
  - ServiceEntry: 14
  - Services: 52
  - Pods: 139

<img width="293" alt="screen shot 2018-08-26 at 08 45 21" src="https://user-images.githubusercontent.com/1486729/44625983-668cb800-a90c-11e8-9d08-780e2d639ad3.png">

**Comment by Stono** [comment]
OK I've done some more digging in the dev cluster and it appears correlation =/= causation, I've found some `istio-proxy` pods on the less utilised cluster also using 2.5x the RAM of others:

<img width="268" alt="screen shot 2018-08-26 at 08 56 21" src="https://user-images.githubusercontent.com/1486729/44626053-ef582380-a90d-11e8-9c78-085d4c24a023.png">

What I have noticed is all the istio-proxies that are using more ram, have some event at different times in their history where ram usage really jumped:

<img width="801" alt="screen shot 2018-08-26 at 08 57 21" src="https://user-images.githubusercontent.com/1486729/44626063-4d850680-a90e-11e8-8d8a-14850745bf1b.png">

<img width="811" alt="screen shot 2018-08-26 at 08 58 31" src="https://user-images.githubusercontent.com/1486729/44626064-507ff700-a90e-11e8-8275-df0c6c59f73c.png">

I've attached the log from the second sreenshots istio-proxy, which i must add is quite spammy with cluster reloads and grpc disconnections?

[istio-proxy.log](https://github.com/istio/istio/files/2321337/istio-proxy.log)

**Comment by rshriram** [comment]
cc @PiotrSikora LCTrie mem optimizations don't seem to help.

**Comment by PiotrSikora** [comment]
@Stono compared to https://github.com/istio/istio/issues/7912 and my experiments, those numbers look awfully high for the number of services in your clusters. How many CPUs are on the host systems running those containers? Could you run those commands for me?

`$ kubectl exec -it <pod> -c istio-proxy -- grep -c ^processor /proc/cpuinfo`
`$ kubectl exec -it <pod> -c istio-proxy -- pgrep -w envoy | wc -l`

There are 2 major sources of high RAM usage in the proxy:
1) Per cluster/service overhead (~80% of which is allocated for stats), which is currently proportional to number of services in the cluster,
2) Per worker thread overhead for each cluster/service, which makes 1. even worse.

By default, proxy will start worker thread for each CPU on the host system, which means that the more powerful machine you're using, the more RAM proxy is going to consume by default.

If you're not processing thousands of requests per second, then you might try to lower the number of worker threads to something more reasonable, even 1 or 2, using the `global.proxy.concurrency` setting, i.e.:
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.proxy.concurrency=1
```
Unfortunately, [the change](https://github.com/istio/istio/pull/8196) didn't make into 1.0.1 release, so you'd need to use [daily from 20180828](https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20180828-09-15/) or newer to play with it now.

**Comment by Stono** [comment]
```
❯ kubectl exec -it $pod -c istio-proxy -- grep -c ^processor /proc/cpuinfo
12
```

```
❯ kubectl exec -it $pod -c istio-proxy -- pgrep -w envoy | wc -l
      30
```

I can't unfortunately use daily releases on these systems.

I'm confused however that istio-proxy would be creating threads per cpu on the host, rather than looking at the cgroup allocation for that pod?

Nodes are by nature multi tenant, based on our size of node for us we get this sort of setup:

```
❯ k get pods --all-namespaces -o wide | grep gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
conference-application       conference-application-6b754b56c8-4jkrm                    2/2       Running   0          6h        10.198.0.26    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
consumer-platform            consumer-platform-5c78cd6bc9-js86x                         2/2       Running   0          2d        10.198.0.5     gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
core-system                  prometheus-node-exporter-v68sm                             1/1       Running   0          5d        10.193.32.2    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
core-system                  weave-scope-agent-brmhq                                    1/1       Running   0          5d        10.193.32.2    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
data-platform                alertmanager-0                                             2/2       Running   0          5d        10.198.0.2     gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
data-platform                cloudwatch-billing-exporter-5b698f9dbc-g9vcn               1/1       Running   0          5d        10.198.0.14    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  calico-node-4hzlh                                          2/2       Running   0          5d        10.193.32.2    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  calico-typha-horizontal-autoscaler-5545fbd5d6-9qgrq        1/1       Running   0          5d        10.198.0.11    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  filebeat-preprod-gtrww                                     1/1       Running   0          5d        10.198.0.10    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  ip-masq-agent-s594r                                        1/1       Running   0          5d        10.193.32.2    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  kube-dns-788979dc8f-29scp                                  4/4       Running   0          5d        10.198.0.13    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  kube-proxy-gke-delivery-platform-cpu1ram2-f11b16a5-nkfb    1/1       Running   0          5d        10.193.32.2    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
kube-system                  metrics-server-v0.2.1-7486f5bd67-clfm5                     2/2       Running   0          5d        10.198.0.6     gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
location-service-soap        location-service-soap-56f7dd754f-5glkh                     2/2       Running   0          23h       10.198.0.19    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
private-advert-service       private-advert-service-57d7c6f859-w5pm8                    2/2       Running   0          1h        10.198.0.49    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
sauron-web-partners          sauron-web-partners-5659987d69-62cpj                       2/2       Running   0          49m       10.198.0.52    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
sauron-web                   sauron-web-549884d69b-2gq5k                                2/2       Running   0          40m       10.198.0.53    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
search-solr                  zoonavigator-6874bcc68b-5qg8j                              1/1       Running   0          5d        10.198.0.17    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
search-solr                  zoonavigator-api-f6cb74f4d-w4rq9                           1/1       Running   0          5d        10.198.0.4     gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
vehicle-metric-service       vehicle-metric-service-6f5df59fdb-w2ps8                    2/2       Running   0          1d        10.198.0.12    gke-delivery-platform-cpu1ram2-f11b16a5-nkfb
```

7 of these apps have istio sidecars, so that's 7 processes creating 12 threads?

**Comment by mandarjog** [comment]
@stono, you can update the sidecar-injector config map and add 

- —concurrency
- “1”

And then restart a pod to be reinjected.

**Comment by Stono** [comment]
Will give it a go today @mandarjog - ta

**Comment by Stono** [comment]
Rolling out concurrency=1 seems to have significantly reduced our memory use.

<img width="908" alt="screen shot 2018-08-30 at 13 53 17" src="https://user-images.githubusercontent.com/1486729/44852807-1be8a400-ac5c-11e8-9eac-44d43efb8a70.png">

This does feel like a mitigation though, i would still question having proxy default threads === cores on node, imagine someone was running 64 core nodes, with 32 apps (thus 32 proxies) on there, it'd be pretty catastrophic :)

Feels like it'd be more sensible to set a fixed, lower limit and then document how to tweak under high throughput?

**Comment by PiotrSikora** [comment]
@Stono great, thanks for testing!

Yes, I totally agree that we should have 1 or 2 proxy threads by default, at least for the sidecar, otherwise we're stealing resources away from the workload. Adding `global.proxy.concurrency` (and soon annotations for it) was just prerequisite to dialing it down.

**Comment by shane-kennedy** [comment]
can global.proxy.concurrency be modified after installation ?

i'm having this same issue but would prefer not to reinstall

**Comment by mandarjog** [comment]
The default now is 2.
You can update global.proxy.concurrency, rerender the template.
Most of the changes should be no-op, so it is not a reinstall.
