### ISSUE TITLE
Envoy's "per_filter_config" support in Istio

### ISSUE THREAD

**Issue by virendrasingh007** [istio/istio#8264]
**Describe the feature request**
{{ We want to use Envoy's "per_filter_config", which allows custom filters on envoy routing to having additional configuration and we have few use cases for the same. So hereby request is to add Envoy's "per_filter_config" support in Istio}}

**Describe alternatives you've considered**
{{ NA}}

**Additional context**
{{ Is this feature is already in plan/consideration?  expected ETA? }}

**Comment by rshriram** [comment]
We are already using it for fault injection. Can you detail your use case please?
I assume that you would be enabling your filter via EnvoyFilter CRD?

**Comment by virendrasingh007** [comment]
Thanks Shriram for reply.
Currently we have below static rule at Envoy. We are able to get Virtual_Host data from Istio using VirtualService CRD. Now we want "per_filter_config" data from Istio as below. I believe you are saying that this can be done using "envoyFilter" CRD. Can you please share the steps to get it done? In the meantime we will try to test the same and let you know the result.

Snippet from Envoy bootstrap `yaml` :
       filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: http2
              stat_prefix: ingress_http
              http_protocol_options:
                allow_absolute_url: true
              route_config:
                name: local_route
                validate_clusters: false
                virtual_hosts:
                - name: abc1-fqdn-route
                  domains:
                  - "abc1.p1-nf-ns"
                  routes:
                  - match:
                      prefix: "/xx-yy"
                      headers:
                        name: "id"
                        range_match:
                          start: 100000000
                          end: 200000000
                    route:
                      cluster: outbound|80||abc1.p1-nf-ns.svc.cluster.local
                  - match:
                      prefix: "/zzz-yyy"
                    route:
                      cluster: BlackHoleCluster
                    **per_filter_config:
                      TestRule: #Custome filter created for our use case
                        lookupparam: id
                        lookuptype: header
                        pathregex: /zzz-yyy/v1/(.*)/xe
                        methodtype: GET**

**Comment by itsrajivbansal** [comment]
Thanks Shriram for reply. I am taking up this problem description further.

**Intention/Goal:**
> Create a new custom filter in envoy
> On Istio-Pilot, for **each** matching rule in VirtualService, we want to specify a per_filter_config for custom filter.
> When a rule matches for incoming message, per_filter_config will provide additional inputs to custom filter for additional processing

**As per our understanding:**
- VirtualService in IstioPilot does not allow defining PerFilterConfig for a custom filters (maybe only possibility is through mixer attributes, but IMHO that limits the perfilterconfig capability to custom filter need shall be invoked after mixer filter)
- Mixer plugin generates PerFilterConfig internally (which is based on pre-defined criteria/rules)

Please excuse my ignorance, as we are in very early stage to learn and understand the istio-pilot support to expose envoy capabilities.

**Comment by rshriram** [comment]
@itsrajivbansal / @virendrasingh007 really sorry. I missed this notification (one too many GH notifications).

So if you want to add per-filter config, simply add an extensionConfig field to the VirtualService.route block. This field can specify the per filter config and in Istio, you simply convert this field to perFilterConfig.

And then, to enable your custom filter, you use the EnvoyFilter CRD resource to add this filter to one or more listeners..

**Comment by furlongmt** [comment]
I've also been looking to add a per-filter config for a custom filter. Could you elaborate more on you solution @rshriram?
