### ISSUE TITLE
mixer/pkg/server TestErrors case result in host system err

### ISSUE THREAD

**Issue by Lion-Wei** [istio/istio#8268]
**Describe the bug**
After running ut case `go test ./mixer/pkg/server/ --run=TestErrors -v`, leave the host system some err, like:
```shell
# go test ./mixer/pkg/server/ --run=TestErrors -v
go tool compile: open /dev/null: no such device or address
go tool compile: open /dev/null: no such device or address
# git st
fatal: open /dev/null or dup failed: No such device or address
```
Which is because `/dev/null` mod changed, before is `crw-rw-rw-`, and after test `srwxr-xr-x`.

**Expected behavior**
UT should have no influence for host environment.

**Steps to reproduce the bug**
1. Run unit test. `go test ./mixer/pkg/server/ --run=TestErrors -v`
2. Run again, and got err: `go test ./mixer/pkg/server/ --run=TestErrors -v`.

**Version**
master

**Environment**
ubuntu 16.04.2 LTS,
kernal: Linux 127.0.0.1 4.4.0-62-generic

**Comment by Lion-Wei** [comment]
@douglas-reid PTAL, thanks. 
I'd like to send a pr to fix this problem, if this is not by design. : )
And by the way, I never got this case pass. Always failed in `TestErrors/unix_socket_removal`, is this case suppose return err `unable to remove unix`?

**Comment by douglas-reid** [comment]
@Lion-Wei That doesn't seem like it is by design.  So, please send a PR.
