### ISSUE TITLE
Galley validator crashes for default webhook-config-file 

### ISSUE THREAD

**Issue by mihai-tiriplica-hs** [istio/istio#8269]
**Describe the bug**
If no option for webhook-config-file is sent to Istio Galley fails with the following error:
`cannot create validation webhook service: could not watch : no such file or directory`

I think it's caused by this check: https://github.com/istio/istio/blob/1.0.0/galley/pkg/crd/validation/webhook.go#L151
and that the fix should be to not set a watcher if there is no webhook config file.
I can help with writing the solution if you are ok with this if

**Expected behavior**
Istio Galley runs without any problems.

**Steps to reproduce the bug**
In the quick setup guide for kubernetes, in `install/kubernetes/istio-demo.yaml` remove the `-- webhook-config-file` option.

**Version**

Istio 1.0.0, kubectl 1.8.6

**Is Istio Auth enabled or not?**
It's disabled

**Environment**
Minikube wih no virtual env (runs on linux)

**Cluster state**
I can't provide this information.

**Comment by ayj** [comment]
Fixed by https://github.com/istio/istio/pull/8757
