### ISSUE TITLE
Have a nonroot proxy_init container

### ISSUE THREAD

**Issue by wmuizelaar** [istio/istio#8271]
**Describe the feature request**
We run our clusters with strict pod security policies, which don't allow things to run as root. The proxy_init container that set the iptables rules obviously needs to run as root, but we would like to have that more restricted.

**Additional context**
A solution that we implemented ourselves is to run the proxy_init with a pod security policy that allows the `NET_RAW` and `NET_ADMIN` capabilities. And then also we did a `setcap 'cap_net_raw,cap_net_admin=+ep' "$(readlink -f /sbin/iptables)"` to a custom-built proxy_init container.

Would it be feasible to have this supported within istio itself?

**Comment by sdake** [comment]
@wmuizelaar what you describe is being worked here: https://github.com/istio/istio/pull/7488.  Note that setcap on files does not work correctly across distros from my recollection.  Istio remains platform agnostic and should run in as many environments as possible.

**Comment by wmuizelaar** [comment]
@sdake ah! that looks great! I guess I can just wait until that is merged.
