### ISSUE TITLE
perf: Pilot optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8276]
**Describe the feature request**
Optimize Pilot performance

**Comment by mandarjog** [comment]
3.3.1 is about data path performance with 2 sidecars and increasing number of clients.  I suggest that we close this and open specific pilot performance issues.

**Comment by suryadu** [comment]
@mandarjog sure! we can do that. @jnativio can you please close this issue and update the table in the performance report with all the pilot specific issues.

**Comment by jnativio** [comment]
@mandarjog Could you please let me know what are the specific Pilot perf issues you are investigating or if you have already opened these issues, let me know their numbers.

**Comment by jnativio** [comment]
#9680

**Comment by jnativio** [comment]
#9680 was open to track the performance improvements on Pilot for scalability.

**Comment by jnativio** [comment]
#9800   was opened to investigate alternatives for json marsh/unmarsh
