### ISSUE TITLE
perf:  Cache Management optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8280]
**Describe the feature request**
Improve caching on Data and Control planes in order to minimize latency.

**Comment by suryadu** [comment]
This issue of better cache management is to reduce the latency while using Istio service mesh. As seen below in the acmeair microservices benchmark, we see the latency increase from 2ms to 10 ms with Istio default policies and config (see fig 3.2.3.1 from this report -> https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing)

@mandarjog and I discussed few ideas including externalizing config parameters to tune the cache both at the data plane as well as control plane (with larger cache size at control plane and keeping the side car light weight with smaller cache).

**Comment by jnativio** [comment]
This issue should remain open.

**Comment by jnativio** [comment]
keep open
