### ISSUE TITLE
perf: Buffer Management optimization

### ISSUE THREAD

**Issue by jnativio** [istio/istio#8281]
**Describe the feature request**
Improve Istio buffer management

**Comment by cmluciano** [comment]
Can we add more context to this in terms of what we think the bottleneck is? Also we should add SLIs to indicate what we are targeting in general.

**Comment by suryadu** [comment]
This issue of better buffer management is to reduce the latency while using Istio service mesh. As seen below in the acmeair microservices benchmark, we see the latency increase from 2ms to 10 ms with Istio default policies and config (see fig 3.2.3.1 from this report -> https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit?usp=sharing)

@mandarjog and I discussed few ideas including externalizing config parameters to tune the buffer both at the data plane as well as control plane (with larger buffer size at control plane and keeping the side car light weight with smaller buffer).

**Comment by jnativio** [comment]
This issue should remain open.

**Comment by jnativio** [comment]
keep open

**Comment by vergnes** [comment]
Does this ticket cover controlling Envoy buffers size see #15260? We have a use case where we'd like to control the window size used by Envoy as well. Should I create a separate ticket?

**Comment by jnativio** [comment]
It is better to open a separate issue.

**Comment by howardjohn** [comment]
This issue is from a year ago with no clear description of what is needed. Is someone working on this? Is this still relevant?

**Comment by randomizedcoder** [comment]
This ticket came from this issue ticket: https://github.com/istio/istio/issues/15260
