### ISSUE TITLE
I want to apply to join istio members

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#8289]
Hello Istio Team, 

I want to be part of istio members. 

I think met the requirements: https://github.com/istio/community/blob/master/ROLES.md#member

My focus is on code quality, catching bugs, especially around the Helm Installer, Ansible Installer and Kiali related (policies and telemetry)

Some of my contributions (Pull Requests):
https://github.com/istio/istio/pull/8115
https://github.com/istio/istio/pull/7741
https://github.com/istio/istio/pull/7708
https://github.com/istio/istio/pull/7042
https://github.com/istio/istio/pull/7007
https://github.com/istio/istio/pull/6930
https://github.com/istio/istio/pull/6930
https://github.com/istio/istio/pull/6594
https://github.com/istio/istio/pull/6192
https://github.com/istio/istio/pull/6191
https://github.com/istio/istio/pull/5921
https://github.com/istio/istio/pull/4364

Issues:
https://github.com/istio/istio/issues/6286
https://github.com/istio/istio/issues/7709
https://github.com/istio/istio/issues/7673
https://github.com/istio/istio/issues/6190
https://github.com/istio/istio/issues/4447
https://github.com/istio/istio/issues/7735

cc @gyliu513

**Comment by gyliu513** [comment]
+1, thanks @gbaufake for the contribution!

/cc @sdake @linsun

**Comment by linsun** [comment]
invited, welcome!
