### ISSUE TITLE
0.8.0 LTS deploys prom/statsd_exporter:latest image that introduced breaking change in 0.7.0

### ISSUE THREAD

**Issue by geauxvirtual** [istio/istio#8293]
**Describe the bug**
In the 0.8.0 LTS release files, there are .yaml files under install/kubernetes that deploy the `prom/statsd_exporter` container from `latest` image. Prometheus just released 0.7.0 of this container which introduced a breaking change of requiring command line parameters to use two dashs `--` instead of one `-`. The config yaml included in the 0.8.0 LTS files passes `-statsd.mapping-config` to the container causing the container to error. However, even passing `--statsd.mapping-config`, the container still errors. See this issue I've opened on prometheus/statsd_exporter https://github.com/prometheus/statsd_exporter/issues/147 .

The 1.0.0 and 1.0.1 releases have updated the .yaml files under install/kubernetes to pull the `prom/statsd_exporter:v0.6.0` image, however, the .yaml files still specify the option with a single dash. The `v0.6.0` image of `prom/statsd_exporter` can accept the command line option as `--statsd.mapping-config`.

**Expected behavior**
Istio to deploy successfully with supplied .yaml files and passing correct command line options to any containers that it deploys.

**Steps to reproduce the bug**
From the 0.8.0 LTS release download,
`kubectl apply -f install/kubernetes/istio-demo-auth.yaml`

**Version**
Istio: v0.8.0
Kubernetes: v1.11.2

**Is Istio Auth enabled or not?**
Yes

**Environment**
Development VM, CentOS 7

**Cluster state**

**Comment by ymesika** [comment]
Should be resolved by #8249

**Comment by sdake** [comment]
Patch merged, closing issue.  Thanks for the report.

Cheers
-steve
