### ISSUE TITLE
Apply to be an istio member

### ISSUE THREAD

**Issue by lichuqiang** [istio/istio#8296]
I want to be istio member.

I think met the requirements: https://github.com/istio/community/blob/master/ROLES.md#member

Mainly focus on config and API management, catching bugs

Some of my contributions (Pull Requests):

https://github.com/istio/istio/pull/8207
https://github.com/istio/istio/pull/7905
https://github.com/istio/istio/pull/7900
https://github.com/istio/istio/pull/8260
https://github.com/istio/istio/pull/8265
https://github.com/istio/istio/pull/8068
https://github.com/istio/istio/pull/7928
https://github.com/istio/istio/pull/7847
https://github.com/istio/istio/pull/7973
https://github.com/istio/istio/pull/7796

Issues involved in:
https://github.com/istio/istio/issues/8077
https://github.com/istio/istio/issues/7877
https://github.com/istio/istio/issues/6437

/cc @ayj @hzxuzhonghu for sponsor
/cc @linsun

**Comment by hzxuzhonghu** [comment]
+1

**Comment by linsun** [comment]
seems a good PR contribution to be invited as a member, anyone objects to this?

**Comment by rshriram** [comment]
This is a bit silly. We should have a different communication channel for applying to be members of the org instead of filing github issues.

**Comment by linsun** [comment]
invited, welcome!

pls feel free to propose other ways to apply member.  Github has histories and folks can chime in with their support.
