### ISSUE TITLE
Should deprecate `--monitoringAddr` 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#8306]
As https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/monitoring.go#L47 said
```
// Deprecated: we shouldn't have 2 http ports. Will be removed after code using
// this port is removed.
```

We should first deprecate `--monitoringAddr`  and eventually remove it in a future version.

cc @costinm @nmittler

**Comment by howardjohn** [comment]
Closing as this is standard across components, and this is a year old. The comment no longer exists so I assume this is desired to have 2 ports
