### ISSUE TITLE
istio-proxy segfaults when it receives a non-mtls connection on an mtls port

### ISSUE THREAD

**Issue by Stono** [istio/istio#8310]
**Describe the bug**
We were experiencing segfaults on one of our istio-proxy pods:

```
[2018-08-28 10:15:39.606][312][critical][backtrace] bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x80
2018-08-28T10:15:39.634555Z     warn    Epoch 0 terminated with an error: signal: segmentation fault
2018-08-28T10:15:39.634604Z     warn    Aborted all epochs
2018-08-28T10:15:39.634636Z     info    Epoch 0: set retry delay to 1m42.4s, budget to 0
```

We were struggling to get to the bottom of it, but we eventually found a cronjob that was periodically trying to talk to the pod without the mTLS credentials (obviously this shouldn't be allowed), when istio-proxy was getting that inbound connection it is segfaulting

I've recorded a terminal session which shows this in action, the top panel of the recording shows the logs from istio-proxy, the bottom panel shows me curling the service from a non-istio/non-mtls pod.  Obviously I wouldn't expect that connection to work, but I don't expect istio-proxy to segfault either.

https://asciinema.org/a/8GTYIhBs0QqTSzmFCNxYJGYXg

**Comment by mandarjog** [comment]
@PiotrSikora perhaps issue with tls inspector ?

**Comment by PiotrSikora** [comment]
Trace-level log preceding the crash, which is unfortunately quite easy to replicate (so this is P0, cc @costinm):

```
[debug][filter] external/envoy/source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
[debug][filter] src/envoy/tcp/mixer/filter.cc:28] Called tcp filter: Filter
[debug][filter] src/envoy/tcp/mixer/filter.cc:38] Called tcp filter: initializeReadFilterCallbacks
[debug][filter] external/envoy/source/common/tcp_proxy/tcp_proxy.cc:157] [C9] new tcp proxy session
[trace][connection] external/envoy/source/common/network/connection_impl.cc:232] [C9] readDisable: enabled=true disable=true
[debug][filter] src/envoy/tcp/mixer/filter.cc:98] [C9] Called tcp filter onNewConnection: remote 10.48.7.6:56038, local 10.48.1.8:8000
[debug][filter] external/envoy/source/common/tcp_proxy/tcp_proxy.cc:293] [C9] Creating connection to cluster inbound|8000||tcpbin.default.svc.cluster.local
[debug][pool] external/envoy/source/common/tcp/conn_pool.cc:67] creating a new connection
[debug][pool] external/envoy/source/common/tcp/conn_pool.cc:325] [C10] connecting
[debug][connection] external/envoy/source/common/network/connection_impl.cc:572] [C10] connecting to 127.0.0.1:8000
[debug][connection] external/envoy/source/common/network/connection_impl.cc:581] [C10] connection in progress
[debug][pool] external/envoy/source/common/tcp/conn_pool.cc:92] queueing request due to no available connections
[debug][main] external/envoy/source/server/connection_handler_impl.cc:218] [C9] new connection
[trace][connection] external/envoy/source/common/network/connection_impl.cc:389] [C9] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:457] [C9] write ready
[debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C9] handshake error: 1
[debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:141] [C9] SSL error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST
[debug][connection] external/envoy/source/common/network/connection_impl.cc:133] [C9] closing socket: 0
[debug][filter] src/envoy/tcp/mixer/filter.cc:134] Called tcp filter onEvent: 0
[debug][main] external/envoy/source/server/connection_handler_impl.cc:51] [C9] adding to cleanup list
[trace][main] external/envoy/source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=1)
[trace][connection] external/envoy/source/common/network/connection_impl.cc:389] [C10] socket event: 2
[trace][connection] external/envoy/source/common/network/connection_impl.cc:457] [C10] write ready
[debug][connection] external/envoy/source/common/network/connection_impl.cc:466] [C10] connected
[debug][pool] external/envoy/source/common/tcp/conn_pool.cc:249] [C10] assigning connection
[trace][main] external/envoy/source/common/event/dispatcher_impl.cc:52] clearing deferred deletion list (size=1)
[debug][filter] src/envoy/tcp/mixer/filter.cc:33] Called tcp filter : ~Filter
[debug][connection] external/envoy/source/common/network/connection_impl.cc:98] [C10] closing data_to_write=0 type=1
[debug][connection] external/envoy/source/common/network/connection_impl.cc:133] [C10] closing socket: 1
[debug][pool] external/envoy/source/common/tcp/conn_pool.cc:107] [C10] client disconnected
[trace][main] external/envoy/source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=1)
[critical][backtrace] bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x80 
```

**Comment by PiotrSikora** [comment]
Also, it seems that this is happening only for TCP proxy and not HTTP.

**Comment by PiotrSikora** [comment]
Added stacktrace.

**Comment by kyessenov** [comment]
@PiotrSikora Is this an upstream bug? I don't see anything specific to mixer in the stack. Can you link an upstream bug?

**Comment by lizan** [comment]
https://github.com/envoyproxy/envoy/pull/4296 might be related.

**Comment by PiotrSikora** [comment]
@lizan unfortunately, it doesn't. I've update istio-proxy to envoyproxy/envoy#4296 and I was still able to reproduce the crash.

I'm still tracking this, but the turnaround is rather slow, since I can replicate this only on k8s and not locally (probably because of timing).

What's bizarre is that the crash happens only with istio and istio-proxy 1.0.1, I cannot reproduce crashes using istio 1.0.1 with istio-proxy 1.0.0 or istio 1.0.0 with istio-proxy 1.0.1.

**Comment by PiotrSikora** [comment]
@kyessenov it's a regression in upstream, yes (see: https://github.com/istio/envoy/pull/10).

**Comment by zuercher** [comment]
I don’t have access to a computer to do any debugging, but I expect the problem is that the upstream connection callback (onPoolReady in tcp proxy) is firing after the downstream has been closed and is trying to enable reads on the already closed downstream.

**Comment by ggreenway** [comment]
I think this may be related to the mixer filter, due to this line from the trace above:

`[debug][filter] src/envoy/tcp/mixer/filter.cc:98] [C2] Called tcp filter onNewConnection: remote 10.48.5.4:39950, local 10.48.4.6:8000`

With only a tcp_proxy filter, and a listener configured for TLS, onNewConnection() will only be called when the TLS handshake completes, and if mTLS validation fails, that should never happen. The tcp_proxy doesn't try to connect to an upstream until onNewConnection() is called.

However, I'm not sure that there isn't still a bug in tcp_proxy. I just don't have a means to try to reproduce it. But I think we may need to add, in `onDownstreamEvent()`, something like:

```
if (upstream_handle_) { upstream_handle_->cancel(); }
```

**Comment by PiotrSikora** [comment]
> I think this may be related to the mixer filter, due to this line from the trace above:

Yes, I haven't ruled this out completely, however it worked fine before the TCP proxy changes, and it works fine after reverting them, so it's either regression or a silent breakage in upstream anyway.

> With only a tcp_proxy filter, and a listener configured for TLS, onNewConnection() will only be called when the TLS handshake completes, and if mTLS validation fails, that should never happen. The tcp_proxy doesn't try to connect to an upstream until onNewConnection() is called.

That's definitely not true, and this assumption is most likely the source of this issue).

> [debug][connection] external/envoy/source/common/network/connection_impl.cc:572] [C3] connecting to 127.0.0.1:8000
> [debug][connection] external/envoy/source/common/network/connection_impl.cc:581] [C3] connection in progress
> [debug][pool] external/envoy/source/common/tcp/conn_pool.cc:92] queueing request due to no available connections
> [debug][main] external/envoy/source/server/connection_handler_impl.cc:218] [C2] new connection
> [trace][connection] external/envoy/source/common/network/connection_impl.cc:389] [C2] socket event: 2
> [trace][connection] external/envoy/source/common/network/connection_impl.cc:457] [C2] write ready
> [debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C2] handshake error: 1
> [debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:141] [C2] SSL error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST

In the above excerpt `C2` is downstream and `C3` is upstream (`127.0.0.1:8000` is the configured cluster endpoint, not the mixer endpoint), so it's definitely connecting before TLS handshake completes (or errors out).

Also, see the discussion in #2800.

**Comment by ggreenway** [comment]
Ah, I see where I went wrong. `raiseEvent(Connected)` happens when the handshake completes. `onNewConnection()` happens as soon as the filter chain has been constructed. I conflated the two in my mind.
