### ISSUE TITLE
Send pod/VM labels directly from Envoy to Pilot in the discovery request

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#8318]
Envoy already sends Metadata associated with the discovery request, that is a map of KV pairs and contains currently environmental variables prefixed with ISTIO_META_ * .

We can use the same mechanism to send the Pod/VM labels/annotations used for source_labels filtering in the Gateway and VirtualServices, so Pilot will not need to read labels directly from Kubernetes. We can prefix them with ISTIO_LABELS_* , or ISTIO_ANNOTATIONS_*.

The labels can be passed to pilot_agent via the kubernetes downward API, or can be written in the file /etc/podinfo/labels for VMs or other non-kubernetes environments:

https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api

Since labels can be changed on the fly, pilot-agent needs to periodically read the content of  /etc/podinfo/labels and /etc/podinfo/annotations to pick up the label changes, and re-connect to pilot. The even simpler alternative is to request a restart of the pod.

It may also fix #7787 .

cc @louiscryan @costinm

**Comment by ymesika** [comment]
Is it the same mechanism to be used by the Split Horizon EDS?

**Comment by andraxylia** [comment]
@ymesika labeling of pods can be used for multiple purposes. This mechanism talks about how Pilot learns the labels from Envoy, not what Pilot uses the labels for.

**Comment by munrodg** [comment]
Done
