### ISSUE TITLE
Unable to get client IP in AWS with ELB TCP listeners

### ISSUE THREAD

**Issue by merlineus** [istio/istio#8337]
Istio uses TCP listeners in AWS ELB which don't preserve and forward client IP to Envoy so we can get only ELB's internal IP in backend microservices and not client IP.

Using TCP listeners is necessary for dynamic serving of SSL certs, so the only workaround I've found for this case is [enabling](https://github.com/envoyproxy/envoy/issues/136#issuecomment-252787381) ProxyProtocol in ELB. To parse this protocol with Envoy we should enable ```use_proxy_proto``` in ingressgateway's Listener [configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto#listener-filterchain), but I can't figure out how can I modify it with Istio. Could someone point how this can be done?

As I've found this is a very common problem in AWS so maybe Istio should have some options for configuring this.

**Comment by merlineus** [comment]
@ibelikov Thanks, I missed out that NLB preserves client IP, will check that.

Another solution may be to switch ELB's listener on 443 port to HTTPS and add SSL certificate there, but I've not tested this yet.

**Comment by ibelikov** [comment]
@merlineus switching to HTTP/HTTPS also works, but you'll be limited to only HTTP/HTTPS then. I needed WebSocket and HTTP/2 support, so that didn't work out for me.

**Comment by eduardobaitello** [comment]
@merlineus Were you able to configure Envoy to use proxy-protocol?

**Comment by merlineus** [comment]
Nope.
There is no setting or API for that in Istio. Ingressgateway's listener configuration is created by Gateway resource. So this option can only be supported by Istio developers.

**Comment by xeor** [comment]
https://github.com/istio/istio/pull/12748 seams to fix this.. I'm waiting for it as well..
