### ISSUE TITLE
[test-framework] Switch to new test framework

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8349]
This is an Epic for tracking all of the remaining tasks before we can switch all of the existing integration/e2e tests to the new framework.

A deck for the test framework from Nate and Oz:  https://docs.google.com/presentation/d/1CWHVuzdvfCI_yIDPg3AK8rYtV4b245dH3jkoLyHBNCM/edit#slide=id.p

**Comment by lichuqiang** [comment]
I have interest in this. 
Please let me know if some of them are up for grabs :)

**Comment by nmittler** [comment]
@lichuqiang want to start with https://github.com/istio/istio/issues/6173? The port-forwarder is going to be pretty important.

**Comment by lichuqiang** [comment]
Sure!

**Comment by m1093782566** [comment]
I volunteered to help this work

**Comment by nmittler** [comment]
@m1093782566 great! It's a cleanup task, but it would be nice to get #8465 done ... would you mind taking that one?

**Comment by m1093782566** [comment]
Awesome! I am looking at #8465 and will send a PR in recent days...

**Comment by esnible** [comment]
Where can we find a guide to switching to the test framework.  I want to greatly increase the tests and code coverage for _istioctl_.

**Comment by howardjohn** [comment]
This has been migrated
