### ISSUE TITLE
[test-framework] Add support for creating k8s cluster

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8353]
Currently the new test framework assumes that a k8s cluster exists. We should add the ability to create a new k8s cluster if desired.

**Comment by m1093782566** [comment]
@nmittler I volunteered to help this task, you can assign it to me :)

**Comment by m1093782566** [comment]
cc @hklai

**Comment by nmittler** [comment]
@m1093782566, @ozevren and I discussed this a bit yesterday ... this needs more thought.  I'm not sure we're ready to work this issue just yet.

**Comment by ozevren** [comment]
Sorry, I don't know how @m1093782566 got removed.  I just set the label. I cannot add him back for some reason.

**Comment by nmittler** [comment]
This work has already been done.
