### ISSUE TITLE
[test-framework] Migrate Pilot e2e tests to new framework

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8354]
Based on previous categorization work, here is the current list. *Note that the list can change as this is living code*.

Still, it is worth capturing this in the bug, to keep track:

Local Environment:
- [ ] istio.io/istio/tests/e2e/tests/controller.TestTempWorkspace
- [ ] istio.io/istio/tests/e2e/tests/controller.TestUnknownConfig
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestAuthNJwt
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestCoreDumpGenerated
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestEnvoyFilterConfigViaCRD
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_HTTPIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_HTTPSIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_TCPIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGatewayIngress_AuthN_JWT
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGrpc
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestHttp
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestIngressGateway503DuringRuleChange
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestListenerConflicts
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestMTlsWithAuthNPolicy
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestPilotMCPClient
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRBAC
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteFaultInjection
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteHTTPViaEgressGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteMirroring
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteRedirectInjection
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRoutes
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteSNIViaEgressGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestServiceEntry
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTcpNonHeadlessPorts
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTCPNonIstioToIstioHeadlessPort
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTcpStatefulSets
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTLSMultiplexing
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestVirtualServiceMergingAtGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestZipkin

Kubernetes Environment:
- [ ] istio.io/istio/tests/e2e/tests/controller.TestTempWorkspace
- [ ] istio.io/istio/tests/e2e/tests/controller.TestUnknownConfig
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestAuthNJwt
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestCoreDumpGenerated
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestEnvoyFilterConfigViaCRD
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_HTTPIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_HTTPSIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGateway_TCPIngress
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGatewayIngress_AuthN_JWT
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestGrpc
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestHttp
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestIngressGateway503DuringRuleChange
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestListenerConflicts
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestMTlsWithAuthNPolicy
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestPilotMCPClient
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRBAC
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteFaultInjection
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteHTTPViaEgressGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteMirroring
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteRedirectInjection
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRoutes
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestRouteSNIViaEgressGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestServiceEntry
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTcpNonHeadlessPorts
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTCPNonIstioToIstioHeadlessPort
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTcpStatefulSets
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestTLSMultiplexing
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestVirtualServiceMergingAtGateway
- [ ] istio.io/istio/tests/e2e/tests/pilot.TestZipkin

*Important* Do not close this work-item until we deprecate the old set of tests and make sure there are no new incoming tests to-be-ported. The line item below is used to track this, and should be done as the last thing before closing this issue.

- [ ]  Final walkthrough to ensure all tests are appropriately ported and the old tests are deprecated.

**Comment by ozevren** [comment]
@hklai
