### ISSUE TITLE
[test-framework] Migrate Mixer e2e tests to new framework

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8355]
Based on previous categorization work, here is the current list. *Note that the list can change as this is living code.*

Still, it is worth capturing this in the bug, to keep track:

Local Environment:

- [ ] istio.io/istio/tests/e2e/tests/mixer.TestCheckCache
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestDenials
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestIngressCheckCache
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestIngressDenials
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestIngressMetric
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestKubeenvMetrics
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestMetric
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestMetricsAndRateLimitAndRulesAndBookinfo
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestMixerReportingToMixer
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestNewMetrics
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestRedisQuotaFixedWindow
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestRedisQuotaRollingWindow
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestTcpMetrics

Kubernetes Environment:

- [ ] istio.io/istio/tests/e2e/tests/mixer.TestCheckCache
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestDenials
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestIngressCheckCache
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestIngressDenials
- [x] istio.io/istio/tests/e2e/tests/mixer.TestIngressMetric
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestKubeenvMetrics
- [x] istio.io/istio/tests/e2e/tests/mixer.TestMetric
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestMetricsAndRateLimitAndRulesAndBookinfo
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestMixerReportingToMixer
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestNewMetrics
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestRedisQuotaFixedWindow
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestRedisQuotaRollingWindow
- [ ] istio.io/istio/tests/e2e/tests/mixer.TestTcpMetrics

*Important* Do not close this work-item until we deprecate the old set of tests and make sure there are no new incoming tests to-be-ported. The line item below is used to track this, and should be done as the last thing before closing this issue.

- [ ] Final walkthrough to ensure all tests are appropriately ported and the old tests are deprecated.

**Comment by ozevren** [comment]
@hklai

**Comment by ozevren** [comment]
I've ported a few of these, but I won't be working to complete the rest. Unassigning myself.

**Comment by howardjohn** [comment]
Is this wont-fix due to mixer v2 efforts, or something still worthwhile?

**Comment by howardjohn** [comment]
I believe this is done, and efforts are on v2
