### ISSUE TITLE
Does istio support Apache Thrift?

### ISSUE THREAD

**Issue by AceHack** [istio/istio#8358]
I'm having a hard time finding any info on this.  Thanks.

**Comment by kyessenov** [comment]
The short answer is no. The underlying transport is probably allowed (TCP/HTTP), but istio does not have any thrift protocol understanding ATM.

**Comment by ymesika** [comment]
But the optimistic aspect is that Envoy is (slowly) moving in that direction: https://github.com/envoyproxy/envoy/issues/2247

**Comment by AceHack** [comment]
Any update?

**Comment by pnovotnak** [comment]
Hey all, is thrift on the roadmap now that Envoy supports it? If not, could someone give a ballpark estimate for how much time would be required to add it?
