### ISSUE TITLE
The deployment Bookinfo doesn't work on istio system without mixer

### ISSUE THREAD

**Issue by zxDiscovery** [istio/istio#8362]
**Describe the bug**
I want to deploy the bookinfo on istio system without mixer deployment. But the bookinfo doesn't work after do that. Does the istio can work without mixer?
**Expected behavior**
Bookinfo work normally on istio system without mixer

**Steps to reproduce the bug**
1. Install istio without mixer.
2. Deploy bookinfo
3. Confirm the bookinfo is running

**Version**
istio-1.0.3

**Is Istio Auth enabled or not?**
No

**Environment**
Ubuntu

**Cluster state**
N/A

**Comment by ymesika** [comment]
Yes, the basic Bookinfo with traffic routings should work without Mixer installed.
Just make sure that you also specify `--set global.proxy.envoyStatsd.enabled=false` when installing without it.

**Comment by zxDiscovery** [comment]
@ymesika Oh, I don't specify ``--set global.proxy.envoyStatsd.enabled=false``. I will try it again. Thank you!

**Comment by zxDiscovery** [comment]
It works after specify ``--set global.proxy.envoyStatsd.enabled=false``. So close this issue.
