### ISSUE TITLE
Istio 1.0 always take default value "http://localhost:8080" without using value from kubeconfig in minikube

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#8369]
**Describe the bug**
We have built a web application which create istioclient using kubeconfig, while i query istio resources we observed resources were not found. On further debugging we observed apiserver it was using  default value "http://localhost:8080" in k8s.io/client-go/tools/clientcmd/client_config.go:49 instead of apiserver value in kubeconfig file.

Root cause: Commit https://github.com/istio/istio/commit/93efbf0c5b0d405f4082b3a1f83547371340c2ac#diff-52591d88d036b712a96e8c075a3ed153 in file client.go, changed api from clientcmd.BuildConfigFromFlags("", kubeconfig) to kubecfg.BuildClientConfig(kubeconfig). Istio-1.0 changes set default kubeconfig value https://github.com/istio/istio/commit/93efbf0c5b0d405f4082b3a1f83547371340c2ac#diff-160ea5be69467ad0270b64ecf7b73636R44.  Further code flows k8s.io/client-go/tools/clientcmd/client_config.go:108 -> k8s.io/client-go/tools/clientcmd/client_config.go:433. If we observe method, k8s.io/client-go/tools/clientcmd/client_config.go:433 it first merge default value, later merge values from kubeconfig. As merge override flag is set to false, Default values is never replaced by kubeconfig values. 

It uses default value k8s.io/client-go/tools/clientcmd/client_config.go:49.

If you see k8s.io/client-go/tools/clientcmd/client_config.go:531 implementation, it never set default value to LoadingRules. Code below:
```
func BuildConfigFromFlags(masterUrl, kubeconfigPath string) (*restclient.Config, error) {
       ........// some code
	return NewNonInteractiveDeferredLoadingClientConfig(
		&ClientConfigLoadingRules{ExplicitPath: kubeconfigPath},
		&ConfigOverrides{ClusterInfo: clientcmdapi.Cluster{Server: masterUrl}}).ClientConfig()
}
```

But Istio set default value to LoadingRules as below,
```
func BuildClientConfig(kubeconfig, context string) (*rest.Config, error) {
        ........// some code
	loadingRules.DefaultClientConfig = &clientcmd.DefaultClientConfig
	loadingRules.ExplicitPath = kubeconfig
	configOverrides := &clientcmd.ConfigOverrides{}
	return clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides).ClientConfig()
}
```

**Expected behavior**
It should always use apiserver in kubeconfig and not default.

**Steps to reproduce the bug**
Deploy minikube with kubernetes 1.10 and install Istio-1.0 in cluster. Write any go main method and create istioclient by passsing kubeconfig and query any istio resources like virtualservice etc. Ot shows error Failed while creating route rule: sample-rule, error the server could not find the requested resource (post virtualservices.networking.istio.io)

Sample code: 
```
package main
import (
	"fmt"
	"istio.io/istio/pilot/pkg/config/kube/crd"
	"istio.io/istio/pilot/pkg/model"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	"os"
	"os/user"
	"path/filepath"
)

func main() {
	path := filepath.Join(homeDir(), ".kube", "config")
	istioClient := GetIstioClient(path)
	routerules, err := istioClient.List(model.Gateway.Type, model.NamespaceAll)
	if err != nil {
		panic(fmt.Sprintf("Failed to query virtual service from cluster: %+v", err))
	}
	for i := 0; i < len(routerules); i++ {
		fmt.Println(routerules[i].Name)
	}
	if _, exists := istioClient.Get(model.VirtualService.Type, "helloworld", "default"); exists {
		fmt.Println(exists)
	}
}

// Create istio client using kubeconfig file
func GetIstioClient(kubeConfigPath string) *crd.Client {
	istioClient, err := crd.NewClient(kubeConfigPath, "minikube", model.IstioConfigTypes, "")
	if err != nil {
		panic(fmt.Sprintf("Failed to create istio client: %+v", err))
	}
	return istioClient
}

func homeDir() string {
	u, e := user.Current()
	if e != nil {
		panic(e)
	}
	return u.HomeDir
}
```

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
Istio- 1.0
Kubernetes- 1.10

**Is Istio Auth enabled or not?**
{{ Did you install the stable istio.yaml, istio-auth.yaml.... or if using the Helm chart please provide full command line input }}
Installed using  istio.yaml.

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
Minikube

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by ymesika** [comment]
Just tried running `istioctl` with a `-c` flag that points to non-default kubeconfig. `istioctl` is using the same API you use (`crd.NewClient`) and it works correctly. I.e. it connects to the K8s API I provided in the flag.

Please notice that if the provided kubeconfig doesn't exists or fails to load it will fallback to the default. Can you verify that you can get an existing one with the `path := filepath.Join(homeDir(), ".kube", "config")`?

Do you run your istioclient in-cluster or out of cluster?

**Comment by keerthig9** [comment]
Any updates? We are waiting to upgrade to istio-1.0 and this is blocking us.

**Comment by ymesika** [comment]
This is a problem on your environment.
Your piece of code works correctly on my environment as it is. My only change to your code was to replace "minikube" with the kubeconfig context I have. Are you sure you have the kubeconfig context "minikube" defined in your kubeconfig?

**Comment by keerthig9** [comment]
If i debug through code also as i explained in description, its very clear that default value never replaced by value in kubeconfig file as merge() at k8s.io/client-go/tools/clientcmd/client_config.go:433  never replace value if it has one.

Can you recheck ?
Software to use: Kubernetes 1.10, Minikube 0.28.0, Istio 1.0 version
Copy sample code provided to Goland running in Mac (outside of minikube). 

We see this issue only when we run sample code in Goland but works fine when application is deployed in minikube and kubernetes cluster.

**Comment by ymesika** [comment]
I'm happy to help but I can't reproduce it. I don't have Goland so I just create a `test.go` file with your code snippet and ran it with `go run test.go`. I don't see any issues.
Can you try it too (outside of gland)? Just to make sure your Goland isn't creating environment variables when launching your program?

Also, if I understand correctly your code is reading the kubeconfig from `~/.kube/config` and this config has a minikube context like you pasted in https://github.com/istio/istio/issues/8369#issuecomment-422928261.

Where is the 8080 defined then? What configs does your `$KUBECONFIG` point to?

**Comment by tiny1990** [comment]
It's a client-go bug

I debug  and see client_config.go

https://github.com/kubernetes/client-go/blob/release-8.0/tools/clientcmd/client_config.go#L459

mergo.Merge not Overwrite 
so you should use mergo.MergeWithOverwrite

or update to release-9.0 + 

https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/client_config.go#L456

I see fix pr 
https://github.com/kubernetes/client-go/commit/ae46060c39ab7a09ffbdc4d720f1626c9bfb37e1

you just update

**Comment by ayj** [comment]
github.com/imdario/mergo changed semantics of `mergo.Mergo`. k8s client-go previously pinned to the older mergo version to avoid problems. They've since updated their code to use the mergeWithOverwrite. We did something similar in Istio (see https://github.com/istio/istio/pull/6987) and will eventually move to release-9.0+ with the fix.

**Comment by kidiyoor** [comment]
Facing the same issue with following code snippet:
Istio client doesn't pick up the right endpoint from kubeconfig context. It uses localhost:8080 always.
```
package main
import(
	"istio.io/istio/pilot/pkg/config/kube/crd"
	"istio.io/istio/pilot/pkg/model"
	"fmt"
	networking "istio.io/api/networking/v1alpha3"
	"github.com/gogo/protobuf/proto"
)
func main() {
	IstioConfigTypes := model.ConfigDescriptor{model.Gateway, model.VirtualService}

	//https://github.com/istio/istio/issues/8369
	client, err := crd.NewClient("/Users/gauthamvk/.kube/config", "gke_research-163304_us-central1-a_istio-gateway", IstioConfigTypes, model.IstioAPIGroupDomain)
	if err != nil {
		fmt.Println(err)
	}
	configMeta := model.ConfigMeta{
		Name:      "MyName",
		Namespace: "default",
		Type:      model.Gateway.Type,
		Group:     model.Gateway.Group + model.IstioAPIGroupDomain,
		Version:   model.Gateway.Version,
	}
	gatewaySpec := &networking.Gateway{
		Selector: map[string]string{"istio": "ingressgateway"},
		Servers: []*networking.Server{
			{
				Port: &networking.Port{
					Name:     "http",
					Number:   80,
					Protocol: "HTTP",
				},
				Hosts: []string{"host.example.com"},
			},
		},
	}
	gateway := model.Config{
		ConfigMeta: configMeta,
		Spec:       gatewaySpec,
	}
	_, err = client.Create(gateway)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by kidiyoor** [comment]
It started working after adding 
```
[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
```
to Gopkg.toml of my project. 

I wonder why https://github.com/istio/istio/blob/master/Gopkg.toml#L359 didn't take care of this.
