### ISSUE TITLE
GDB doesn't work due to missing capabilities in the container.

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#8383]
**Describe the bug**
GDB doesn't work due to missing capabilities (`CAP_SYS_PTRACE` or `CAP_SYS_ADMIN`) in the container, even though it's documented in the [official documentation](https://istio.io/help/ops/component-debugging/#with-gdb).

```
$ kubectl exec -it tcpbin-c5984649c-swj5s -c istio-proxy -- /bin/bash
```
```
istio-proxy@tcpbin-c5984649c-swj5s:/$ gdb -p `pgrep envoy` /usr/local/bin/envoy
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/envoy...done.
Attaching to program: /usr/local/bin/envoy, process 43
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
(gdb)
```
```
istio-proxy@tcpbin-c5984649c-2ttz8:/$ cat /proc/sys/kernel/yama/ptrace_scope
1
```

**Expected behavior**
GDB works, at the very least when using `proxy_debug` image.

**Steps to reproduce the bug**
```
$ kubectl exec -it <pod> -c istio-proxy -- /bin/bash
```
```
$ gdb -p `pgrep envoy`  /usr/local/bin/envoy
```

**Version**
```
$ istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.1", GitCommit:"ee18aa41359293b5c9c7e13a35697690491736c9", GitTreeState:"clean", BuildDate:"2018-08-08T18:09:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
N/A

**Environment**
GKE

**Cluster state**
N/A

**Comment by irisdingbj** [comment]
not stale

**Comment by sdake** [comment]
I'd prefer not to remove the documentation, however, we can't add these capabilities in the general case, as many platforms don't run with `--privelged` and disable the ability to run with extra capabilities.

An injector annotation may make sense here (e.g. if the injector sees the annotation, run that container with the correct capabilities).  @howardjohn normally I'd ask @costinm his thoughts, but as he is on PTO, thoughts for this approach (or any other ideas) for 1.2?

If not, we may need to temporarily remove this from the documentation for 1.2 and reintroduce the documentation for 1.3 once we find a proper solution.

**Comment by howardjohn** [comment]
Do we even have gdb in the images anymore? I recently saw a PR from crazyxy to add it (sorry on phone so can't link it) that I'd still open

**Comment by howardjohn** [comment]
```
istio-proxy@shell-77dd85d479-57dds:/$ gdb
bash: gdb: command not found
```

We don't, lets just remove the docs. In general I think that whole section of docs needs a refresher

**Comment by sdake** [comment]
ok - works for me.  I'll work out the pr(s).

**Comment by sdake** [comment]
Rather than hijack this issue, I've created a new one: 

https://github.com/istio/istio.io/issues/4361

**Comment by irisdingbj** [comment]
@sdake  @howardjohn Thanks for clearing this out!

**Comment by esnible** [comment]
When I look at the injector configmap, `kubectl -n istio-system get cm istio-sidecar-injector -o jsonpath="{.data.config}"`, I see

```
      {{- if .Values.global.proxy.privileged }}
      privileged: true
      {{- end }}
```

Have we verified _gdb_ behavior with _global.proxy.privileged_ set to true?  If that isn't enough we should document how to add CAP_SYS_PTRACE to the sidecar injector configmap.

**Comment by costinm** [comment]
I believe we verified it is possible to use gdb from the node - and attach
to the process running in container. Delve (go debug) too.

Adding more privs to the injector is far from ideal - in particular given
that we want to move the other way around and reduce the privs and
eventually
the injection ( using CNI instead ).

I would close this bug.

**Comment by howardjohn** [comment]
Removed from docs, and still possible to attach from the node. I think safe to close
