### ISSUE TITLE
Auto sidecar injected pod report Init Crash Loop Back-off 

### ISSUE THREAD

**Issue by ZhangLv1979** [istio/istio#8387]
**Describe the bug**
installed 1.0.1 on openshift origin 3.10, auto inject sidecar succeed, but proxy_init container keep report Crash Loop Back-off. so the Pod stay PodInitializing status

**Expected behavior**
should start pod with sidecar container.

**Steps to reproduce the bug**
lable a project as auto inject.
deploy a pod to the project.

**Version**
istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

 kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-20T18:04:21Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-20T18:04:21Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
install with ansible
`ansible-playbook main.yml`

**Environment**
Atomic Centos
Istio 1.0.1
Openshift origin 3.10
Docker 1.13.1

**Cluster state**

[istio-dump.tar.gz](https://github.com/istio/istio/files/2338486/istio-dump.tar.gz)

proxy_init logs: 

> Environment:                                                                           
> ------------                                                                           
> ENVOY_PORT=                                                                            
> ISTIO_INBOUND_INTERCEPTION_MODE=                                                       
> ISTIO_INBOUND_TPROXY_MARK=                                                             
> ISTIO_INBOUND_TPROXY_ROUTE_TABLE=                                                      
> ISTIO_INBOUND_PORTS=                                                                   
> ISTIO_LOCAL_EXCLUDE_PORTS=                                                             
> ISTIO_SERVICE_CIDR=                                                                    
> ISTIO_SERVICE_EXCLUDE_CIDR=                                                            
>                                                                                        
> Variables:                                                                             
> ----------                                                                             
> PROXY_PORT=15001                                                                       
> INBOUND_CAPTURE_PORT=15001                                                             
> PROXY_UID=1337                                                                         
> INBOUND_INTERCEPTION_MODE=REDIRECT                                                     
> INBOUND_TPROXY_MARK=1337                                                               
> INBOUND_TPROXY_ROUTE_TABLE=133                                                         
> INBOUND_PORTS_INCLUDE=6006, 8888,                                                      
> INBOUND_PORTS_EXCLUDE=                                                                 
> OUTBOUND_IP_RANGES_INCLUDE=*                                                           
> OUTBOUND_IP_RANGES_EXCLUDE=                                                            
>                                                                                        
> + iptables -t nat -N ISTIO_REDIRECT                                                    
> + iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001                 
> iptables: No chain/target/match by that name.                                          
> + dump                                                                                 
> + iptables-save                                                                        
> # Generated by iptables-save v1.6.0 on Fri Aug 31 01:13:58 2018                        
> *filter                                                                                
> :INPUT ACCEPT [0:0]                                                                    
> :FORWARD ACCEPT [0:0]                                                                  
> :OUTPUT ACCEPT [0:0]                                                                   
> COMMIT                                                                                 
> # Completed on Fri Aug 31 01:13:58 2018                                                
> # Generated by iptables-save v1.6.0 on Fri Aug 31 01:13:58 2018                        
> *nat                                                                                   
> :PREROUTING ACCEPT [0:0]                                                               
> :INPUT ACCEPT [0:0]                                                                    
> :OUTPUT ACCEPT [0:0]                                                                   
> :POSTROUTING ACCEPT [0:0]                                                              
> :ISTIO_REDIRECT - [0:0]                                                                
> COMMIT                                                                                 
> # Completed on Fri Aug 31 01:13:58 2018

**Comment by ZhangLv1979** [comment]
![image](https://user-images.githubusercontent.com/18044598/45341312-c5b92080-b5cc-11e8-945a-c920109702e6.png)

after i manually add privileged to proxy-init, it works. because selinux is enforcing...... 

this option is needed when inject.

**Comment by lalan7** [comment]
This help me in the exact same situation. Thanks

**Comment by arnaud-deprez** [comment]
Hi, I'm facing the same issue with istioctl 1.0.2.
Has it been fixed somewhere, I don't see any git commit to it to solve the istioctl injection.

**Comment by simonswine** [comment]
With a helm based setup on v1.0.2 you can just set this parameter:

```
--set global.proxy.privileged=true
```

**Comment by pbn4** [comment]
What are the implications of privileged proxy?
