### ISSUE TITLE
Apply for Istio membership

### ISSUE THREAD

**Issue by m1093782566** [istio/istio#8390]
I am creating this issue for the sake of applying for Istio membership.

I have Subscribed to istio-dev@googlegroups.com

I am currently working on improving local e2e test environment setup. Following is the list of PRs got merged:

#7851
#7897
#8023 
#8099 
#8173 
#8237
#8246
#8298 

PRs in flight:

#8248 
#8367 

Issues involved in:

#8159
#8167
#8239
#8365

/cc @hklai @sdake @gargnupur for sponsors

/assign @linsun for approval

**Comment by hklai** [comment]
I can vouch for @m1093782566 who contributed to local E2E testing and will also help out other testing improvements.

**Comment by m1093782566** [comment]
Thanks @hklai !

**Comment by sdake** [comment]
Agree to sponsor @m1093782566 - does great work and is enthusiastic.

cc @geeknoid

**Comment by m1093782566** [comment]
Thanks @sdake

**Comment by linsun** [comment]
invited, welcome @m1093782566 !

**Comment by m1093782566** [comment]
thank you @linsun
