### ISSUE TITLE
istio-security-post-install fails

### ISSUE THREAD

**Issue by DaspawnW** [istio/istio#8408]
**Describe the bug**
The Istio-Security-Post-Install pod runs in Crash-Loop

**Expected behavior**
The Istio-Security-Post-Install pod finishes

**Steps to reproduce the bug**
Follow the instructions on https://istio.io/docs/setup/kubernetes/helm-install/
There it a description in the [Installation steps](https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps) section that you must deploy the crd's only if you are using Helm version prior to 2.10.0.
Then use installation Option 1 with enabled mtls.

This will generate everything except two CRD's:
* MeshPolicy
* DestinationRule

If you deploy the istio.yaml file it will run into an exception by trying to apply the security-default.yaml.tpl via the istio security post install pod.
The reason is that the two CRD's doesn't exist in kubernetes api server.

**Version**
```
$ istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
**Is Istio Auth enabled or not?**
yes:
```
~/Downloads/darwin-amd64/helm template install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    --set global.mtls.enabled=true \
    --set sidecarInjectorWebhook.enabled=false \
    --set ingress.enabled=false \
    --set gateways.istio-ingressgateway.enabled=true \
    --set gateways.istio-ingressgateway.type=NodePort \
    --set gateways.istio-egressgateway.enabled=false \
    --set gateways.istio-egressgateway.type=NodePort \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    > ../istio.yaml
```

**Environment**
Kubernetes: AWS Ubuntu 16.04
Local Instance: Mac OSX

**Workaround**
First apply the crds.yaml file and then apply the rendered template:
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
kubectl apply -f ../istio.yaml

**Comment by ymesika** [comment]
You are missing a flag: `--set security.enabled=true`.
Adding it will generate the missing CRDs as well.

**Comment by DaspawnW** [comment]
Hi @ymesika,

You are right, security.enabled=true did it :-)
In think the parameter is not documented in the helm values and also not in the README.md
