### ISSUE TITLE
Racetest hits alive goroutines limit

### ISSUE THREAD

**Issue by ymesika** [istio/istio#8424]
Recent racetest executions are failing with an error:
`race: limit on 8192 simultaneously alive goroutines is exceeded, dying`
in `TestErrors`.

Example: https://circleci.com/gh/istio/istio/173695?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hzxuzhonghu** [comment]
I can investigate.

/assign

**Comment by hzxuzhonghu** [comment]
propose a pr to fix it.

**Comment by ymesika** [comment]
Thanks @hzxuzhonghu
