### ISSUE TITLE
Grafana pod CreateContainerConfigError because secret created in default namespace

### ISSUE THREAD

**Issue by hyder** [istio/istio#8429]
**Describe the bug**
Grafana pod creation results in CreateContainerConfigError. Error message: "Error: secrets "grafana" not found". Grafana secret is created in default namespace instead of istio-system

**Expected behavior**
Grafana pod should be in Running state

**Steps to reproduce the bug**
Following helm installation via template (Option 1)

helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set grafana.enabled=true \
--set grafana.security.enabled=true \
--set grafana.security.adminUser=admin \
--set grafana.security.adminPassword=password > istio.yaml

**Version**
kubectl: 1.10.5
istioctl: 1.0.1
helm: 2.10.0

**Is Istio Auth enabled or not?**
No

helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set grafana.enabled=true \
--set grafana.security.enabled=true \
--set grafana.security.adminUser=admin \
--set grafana.security.adminPassword=password > istio.yaml

**Environment**
Linux

**Additional Steps**

*** Via K8s dashboard ***
1. Open istio.yaml
2. Copy the grafana secret 
3. Select istio-system namespace
4. Create, paste and update.
5. Grafana Pod is successfully created shortly after

*** Via manifest ***
1. Edit istio.yaml before applying
2. Add namespace to grafana secret: namespace: istio-system
3. Save and kubectl apply
4. Grafana Pod is successfully created

*** Add namespace to source secret.yaml **
1. The grafana secret is created from the following chart file: 
    <span>#<span> Source: istio/charts/grafana/templates/secret.yaml
2. Edit the original secret.yaml
3. Add the namespace as above.
4. Generate istio template with the options above.
5. Grafana Pod is successfully created

**Comment by ymesika** [comment]
This has been modified in #7719 for next 1.x but not available in 1.0.x yet.

**Comment by ymesika** [comment]
@mabushey There should be a resource of `kind: Secret` within the YAML and you'll notice that unlike the ConfigMap and Deployment you mentioned it doesn't have the `namespace: istio-system`.

**Comment by mabushey** [comment]
@ymesika Thanks for the response. No, There is no `kind: Secret` in istio.yaml created via `helm template ../istio/install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true  --set grafana.security.enabled=true  --set grafana.security.adminUser=admin --set grafana.security.adminPassword=pass
> istio.yaml`

**Comment by ymesika** [comment]
@mabushey are you doing it with the `1.0.1` release? I just copied and pasted your command into mine and the Secret is there.

**Comment by mabushey** [comment]
@ymesika Bingo. I was using the latest git repo master. I downloaded the 1.0.1 version and now the secret is there, after adding the namespace and applying I was able to log in with the creds from the helm command. Thank you! :)

**Comment by hyder** [comment]
Hi, 

The secret is there. But the namespace of the secret was not there in the 1.0.1 release.

**Comment by ymesika** [comment]
@hyder Right. It got fixed in #8430. Thanks for reporting.

**Comment by hyder** [comment]
Ah thanks
