### ISSUE TITLE
[test-framework] Consolidate Envoy utilities

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8465]
The new framework defines its [own utility](https://github.com/istio/istio/blob/master/pkg/test/framework/components/apps/local/envoy/envoy.go) for running Envoy locally.  Other components, such as [Mixer](https://github.com/istio/istio/blob/master/mixer/test/client/env/envoy.go), define similar wrappers around Envoy.  We should combine them into a single implementation under `/pkg/test/envoy`.

**Comment by nmittler** [comment]
m1093782566 have you been able to make any progress here? I'd like to get this sorted out.  If you don't have bandwidth, feel free to assign to me for now.

**Comment by nmittler** [comment]
@m1093782566 have you been able to make any progress here? I'd like to get this sorted out.  If you don't have bandwidth, feel free to assign to me for now.

**Comment by m1093782566** [comment]
sorry for delay but I'm working on it and will send a pr by tomorrow

**Comment by nmittler** [comment]
@m1093782566 no worries ... sounds good!
