### ISSUE TITLE
request.auth.claims[scope] does not allow a JWT an array of scopes

### ISSUE THREAD

**Issue by cameronmoreau** [istio/istio#8466]
**Describe the bug**
When enabling RBAC, the `request.auth.claims[scope]` [authorization property](https://istio.io/docs/reference/config/authorization/constraints-and-properties/#properties) does not have a way to validate scopes in the form of an array.

i.e. `{..., "scope": ["foo.read"]}`

**Expected behavior**
If the token's scopes are in the form of an array, there should still be a way to validate these scopes using `request.auth.claims[scope]`.

For example, if we set the following in the ServiceRoleBinding policy:
`request.auth.claims[scope]: "foo.read"`
An incoming JWT in the following format should pass:
`{..., "scope": ["foo.read"]}`

**Steps to reproduce the bug**
1. Enable mTLS (istio-auth.yaml) on app similar to BookInfo
1. Enable JWT Policy
1. Configure a ServiceBindingRole with the following subject properties
```
subjects:
  - user: "*"
    properties:
      request.auth.claims[scope]: "foo.read"
```
4. Visit the page with a JWT containing the following or equivalent scopes
```{..., "scope": ["foo.read"]}```

5. See that the JWT is rejected. 

**Version**
```
○ → istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
○ → k version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
`istio-auth.yaml` enabled on demo BookInfo app with the example [JWT Policy enabled](https://istio.io/docs/tasks/security/authn-policy/#end-user-authentication)

**Environment**
```minikube version: v0.28.1```

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2329196/istio-dump.tar.gz); jwks information in the JWT Policy may need to be updated so that tokens can be generated with scopes in the form of an array.

Related issue: https://github.com/istio/istio/issues/8319

**Comment by liminw** [comment]
In Istio 1.0, Istio RBAC does not support JWT claims with array type. We recently added this support (bullet 3 of issue #6984). We are in the process of updating documentation. It will be available in 1.1 release. 
@lei-tang 

For now, the workaround is to use a single string instead of array of one element. For example:
`{..., "scope": "foo.read"}`

**Comment by lei-tang** [comment]
@cameronmoreau: in your "step 2. Enable JWT Policy", what commands and configurations did you run?

**Comment by cameronmoreau** [comment]
Confirmed that istio 1.1.0.Snapshot.1 fixes the described issue 👍 Thanks!

**Comment by lei-tang** [comment]
The PR #7747 fixed this issue. Thanks for confirming that the fix works!
