### ISSUE TITLE
Rationalize namespaced vs. cluster scoped MCP resources 

### ISSUE THREAD

**Issue by ayj** [istio/istio#8469]
We use the same type_url for namespace and cluster scoped MCP resources (e.g. see [Policy vs. MeshPolicy](https://github.com/istio/istio/blob/feae02be949a5958567616485655efb9f279851b/galley/tools/gen-meta/metadata.yaml#L68-L81)). MCP clients cannot differentiate between the two scopes and, as a result, policy is misapplied. 

For networking APIs, namespace scoped resources provide some convenience w/k8s short names. Namespace based ACL'ing is still [WIP](http://bit.ly/2nGO5cx).

For authentication APIs, Policy can be applied to all services/workloads in a namespace or for _all_ services/workloads (i.e. mesh scoped). 

For Mixer Policy APIs, scope is resolved at runtime per request against the attribute match expression. Namespace'd configuration that should not apply to a particular request is silently ignored at runtime.

A few options to consider:

1) Create new protobuf types for mesh scoped resources,  e.g. `type.googleapis.com/istio.authentication.v1alpha1.MeshPolicy`
2) Resuse the existing protobuf types and encode scope as additional metadata in the type_url, e.g. `type.googleapis.com/istio.authentication.v1alpha1.MeshPolicy?scope=mesh`
3) Fully normalize resource scope outside Istio runtime components (Pilot / Mixer).

(1) and (2) requires components to resolve mesh vs. namespace/service/workload scope. That already do this today. (3) requires moving some (all?) scope resolution into Galley (or equiv.).

- Platform specific service name resolution for networking APIs is fairly straightforward, assuming knowledge of service topology is not required, e.g. short name `foo` in namespace `bar` resolves to `foo.bar.svc.cluster.local`. 
- Workload resolution is TBD and currently assumes fixed mapping of service-to-workload.
- Namespace resolution requires complete knowledge of services / workloads in each namespace. Istio APIs that select targets by namespace including AuthenticationPolicy and possibly Mixer rules.

Fully resolving scope per service/workload at config ingestion time requires additional component-level design work. For example, Pilot resolves mesh and namespace scoped resources on-demand because proxy's identity includes scope (name/namespace). The default mesh authentication policy is unconditionally applied to _any_ workload if no lesser scoped policy exists. Pilot _doesn't_ pre-resolve per workload/service configuration.

cc @geeknoid @ozevren @liminw @andraxylia

**Comment by andraxylia** [comment]
Latest agreement is ServiceEntries are namespaced, there is no cluster scope ServiceEntry.

**Comment by ayj** [comment]
We're slowly moving to a model where all mesh-level resources are namespaced. This reduces the total number of CRD/APIs that user needs to reason about.
