### ISSUE TITLE
Stress test for rbac

### ISSUE THREAD

**Issue by wattli** [istio/istio#8477]
According to Mandar, we need some stress test to validate the performance of Istio rbac policy. Basically we need to start a tree of 500 services and create some script for rbac. And then verify the performance.

**Comment by yangminzhu** [comment]
As now the RBAC policy is fully enforced in Envoy RBAC filter, Do you mean this is stress test for the pilot [RBAC plugin](https://github.com/istio/istio/blob/master/pilot/pkg/networking/plugin/authz/rbac.go)? And you want to have a lot (like 500) services in the mesh with RBAC policies enabled and how would it affect pilot's performance when generating and distributing these policies?

If so, I think this is not specific to RBAC, but to all plugin code in pilot that is doing the same thing, like for `VirtualService`, `Gateway`, `DestinationService` and `Authentication Policy`, etc.

**Comment by liminw** [comment]
FYI. @yangminzhu is working on it right now. Hopefully we will get some perf data soon.

**Comment by wattli** [comment]
@liminw @yangminzhu , can we mark this PR as closed now?

**Comment by mandarjog** [comment]
Please close this *after* we get some performance data.

**Comment by mandarjog** [comment]
oops, never mind..., There is perf data associated with the PR.

**Comment by costinm** [comment]
@costinm @duderino

**Comment by yangminzhu** [comment]
@mandarjog Do we need some high level CPU cost data from Prometheus or do we need something like the flame graph collected from the sidecar? Also could you take a look at https://github.com/istio/tools/pull/33?

**Comment by yangminzhu** [comment]
@mandarjog Stats about the Pilot cpu/memory usage with 3000 RBAC rules applied for 2 pods:
![pilot-cpu-with-3k-rbac-rules](https://user-images.githubusercontent.com/2189160/51153909-c4bc2800-1826-11e9-9f8d-9df54748740e.png)
![pilot-memory-with-3k-rbac-rules](https://user-images.githubusercontent.com/2189160/51153911-c71e8200-1826-11e9-9087-8c8099de7a25.png)

**Comment by mandarjog** [comment]
@yangminzhu thanks for adding generation code to isotope.
However what I am also looking for is helm templates.
We have a dormant one checked in here - https://github.com/istio/tools/blob/master/perf/servicegraph/templates/_rbac_yaml

If you can update that, add a flag to enable / disable rbak testing in values, that would be great.

**Comment by yangminzhu** [comment]
@mandarjog 
The code generation in isotope is already able to generate the required RBAC rules for tests, you can configure it like here: https://github.com/istio/tools/blob/master/isotope/example-topologies/canonical.yaml#L4

Could you clarify a little how would you expect to use the helm templates, Do you mean you want to manually generate and apply the RBAC rules in a cluster?

Apart from the rule generation, does the Pilot memory/cpu usage in https://github.com/istio/istio/issues/8477#issuecomment-454240931 look good to you?

**Comment by liminw** [comment]
@mandarjog @yangminzhu Is this done? Can we close it?
