### ISSUE TITLE
Resolve networking API shortnames to FQDN in Galley for MCP resources

### ISSUE THREAD

**Issue by ayj** [istio/istio#8478]
The networking API resources (e.g. VirtualService, Gateway) allow k8s short names. Pilot uses the resource's namespace and domain suffix (i.e. `cluster.local`) to resolve these names to the FQDN host name. With the introduction of MCP, Galley can perform this name resolution such that Pilot can operate on the fully resolved hostname when MCP is enabled. 

This also implies that the domain suffix option must (1) be added to galley and (2) eventually removed from Pilot once MCP is the only configuration ingestion mechanism.

**Comment by ayj** [comment]
cc @andraxylia @ozevren

**Comment by andraxylia** [comment]
cc @qfel

**Comment by ayj** [comment]
@andraxylia, are you still working on this? Galley's config analyzers are performing resolution which may not be consistent with Pilots. cc @nrjpoddar

**Comment by nrjpoddar** [comment]
Thanks @ayj for pointing out this issue. Why do you think that currently we are not consistent? I tried to look at Pilot logic and resolve it in a similar way. If I missed something can you point out the specifics?

**Comment by ayj** [comment]
They may already be consistent with one another, but I wasn't sure. Do we have tests in place to verify?

**Comment by howardjohn** [comment]
Given we are moving away from MCP source I don't think this is required anymore
