### ISSUE TITLE
Istio Scale & Performance

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#849]
Epic tracking overall Istio scale & performance, used for grouping various issues.

**Comment by ldemailly** [comment]
there is already an epic for this for 0.2 btw

**Comment by andraxylia** [comment]
where?

**Comment by ldemailly** [comment]
https://github.com/istio/istio/issues/369
but we can have a different one for 0.3 / time to switchover some tasks

**Comment by andraxylia** [comment]
Moved the two issues to #369 and closing in favor of #369, whose milestone needs to be changed to 0.3.
