### ISSUE TITLE
reviewer has removed the `needs-ok-to-test ` label but it still requests an `/ok-to-test` message

### ISSUE THREAD

**Issue by islinwb** [istio/istio#8497]
**Describe the bug**
The reviewer has removed the `needs-ok-to-test ` label but it still requests an `/ok-to-test` message to trigger testing. (I've come across the problem two times.)
I think it is not an intended behavior. Correct me if I am wrong. Thanks!

See https://github.com/istio/istio/pull/8449: one reviewer has removed  the `needs-ok-to-test ` label
> geeknoid removed the needs-ok-to-test  label 22 hours ago

but it still requests an `/ok-to-test` message to trigger testing
> Cannot trigger testing until a trusted user reviews the PR and leaves an /ok-to-test message.

/cc @ymesika

**Comment by BenTheElder** [comment]
yes, this is WAI for now, see also this discussion: https://github.com/kubernetes/test-infra/issues/3827 and this KEP: https://github.com/kubernetes/community/pull/2310 currently under review

**Comment by islinwb** [comment]
Thanks @sebastienvas @BenTheElder for clarifying!
/close
