### ISSUE TITLE
Helm installation with Tiller is broken for istio-1.0.0 and istio-1.0.1

### ISSUE THREAD

**Issue by janevalleye2e** [istio/istio#8499]
**Describe the bug**
Helm installation with Tiller is broken for istio-1.0.0 and istio-1.0.1

**Expected behavior**
Helm installation with Tiller should work and install Istio components under the istio-system namespace.

**Steps to reproduce the bug**
Follow the instructions here

https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install

When you run

$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
Error: apiVersion "networking.istio.io/v1alpha3" in istio/charts/mixer/templates/config.yaml is not available

**Version**
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

K8S version : 1.9

**Environment**
GCP

**Comment by janevalleye2e** [comment]
@hklai @rkpagadala @costinm @janevalleye2e @kidiyoor @vilobhmm

**Comment by sdake** [comment]
@janevalleye2e the documentation here could add a little clarity.

Did you create the CRDs in this step?
https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps

Another solution is to use Helm 2.10
Cheers
-steve

**Comment by jsenon** [comment]
I've also tried to deployed with helm 2.10. I've created CRD before. but during helm install it seems that some CRD is created twice, resulting fatal error during installation.
Am I the only one ?
