### ISSUE TITLE
Docker cluster support 

### ISSUE THREAD

**Issue by animo3** [istio/istio#8505]
Hi Team,
I followed the examples on how to get started with Istio and K8s cluster and wanted to check if you have a similar detailed guide for a Docker cluster. The documentation states that it has not been tested  on Nomad for Docker. Is there any beta documentation/guide available to try out for Istio-Nomad-Docker setup? Also are there any plans of adding support to work with AWS ECS?

**Comment by ibm-jason** [comment]
/cc @animo3, @linsun 

Is this still a valid task?
