### ISSUE TITLE
Convert Istio templates to helm style

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#851]

**Comment by ldemailly** [comment]
I don't think we should do this for 0.2 unless it's somehow super straightforward, it's an unplanned new feature

**Comment by andraxylia** [comment]
It requires just replacing the syntax in the templates, it's not a new feature, and there are no code changes.

**Comment by ldemailly** [comment]
the feature (as far as I understand) is to (re-)use the helm engine to do variable substitution in our templates,
that sounds great but again not sure now is the right time, maybe we should finish up creating the N yamls the way we've been doing so far and only what we need to check in and consider that change for when we have more time to think it through (unless again it's very straightforward, I'm very much looking forward to a big red diff at some point to delete all those generated files but probably not 0.2)

**Comment by rshriram** [comment]
@lachie83 can you take a crack at this? Many of our users love the helm charts that you guys did. So we would like to make sure that the helm charts for 0.2.x are well tested before public consumption. Also, it would be great if you could fix the helm versions. The 0.2 helm chart installing 0.1.x has been thoroughly confusing for some of our end users. 

To be clear, the 0.2.4 is not the final release. There will be quite a few patch releases and potentially weekly releases going forward. It would be good to sync the helm chart version with the istio version.

**Comment by ldemailly** [comment]
note that this task is slightly different from the helm chart themselves

See https://github.com/kubernetes/charts/issues/2297 for cleanup request of confusing helm versions

See https://github.com/kubernetes/charts/issues/1909 for having helm charts for 0.2 series

**Comment by lachie83** [comment]
Sure. I'd love it. Thanks for asking. Would it be worth jumping on a quick call to straighten out the details then I'll write up a proposal in Github?

**Comment by gyliu513** [comment]
@lachie83 @rshriram @ldemailly I think we want a stable version before update the helm charts for istio based on the request here https://github.com/kubernetes/charts/issues/1909

**Comment by rshriram** [comment]
@gyliu513 stable version will not help when we start doing weekly releases. We need a mechanism for users to specify the version they want or pick a helm chart corresponding to the minor version (0.2.x, 0.3.x, etc).

**Comment by gyliu513** [comment]
@rshriram ok, I see, I think that now the helm chart should already have such capability to handle different versions. @lachie83

**Comment by lachie83** [comment]
@rshriram can you confirm that I'm clear to cut a chart for 0.2.4 pre-release? I've created a release variable in the chart values so it should be simple enough to update that value once we have the 0.2.x kubernetes resources updated. See https://github.com/kubernetes/charts/blob/master/incubator/istio/values.yaml#L6

**Comment by linsun** [comment]
@lachie83 sorry we missed this earlier.  Yes, it would be great if you could cut a chart for 0.2.4, which is our first RC.  I expect a new RC will come out this week too, but it is good to have the helm chart and people testing that too.

**Comment by lachie83** [comment]
@linsun -- Absolutely. I will rebuild the chart of that pre-release. I will provide a link to the PR and you can let me know what values need to be exposed as configurable items when installing with Helm. I'm planning to start working on this tomorrow

**Comment by linsun** [comment]
@lachie83 excellent, thank you!!

**Comment by andraxylia** [comment]
@lachie83 can you please use the files and templates from master? There will be another release, and there have been changes in the last 6 days.

**Comment by lachie83** [comment]
@andraxylia okay can do. Where are the installation docs?

**Comment by ldemailly** [comment]
https://istio.io/docs/setup/kubernetes/quick-start.html

**Comment by gyliu513** [comment]
@lachie83 are you going to post some PRs for https://github.com/kubernetes/charts/issues/1909 ? If not, I can help to make a 0.2.4 version of istio.

**Comment by lachie83** [comment]
Yes I will

**Comment by lachie83** [comment]
Here's the PR #2369 - I'm having issues rendering CRDs correctly using helm 2.6.1 on a Kubernetes 1.7 cluster. I'm going to raise an issue there.

**Comment by lachie83** [comment]
Here's the helm issue - https://github.com/kubernetes/helm/issues/2994

**Comment by lachie83** [comment]
The PR is all but done but need an assist on the following:

- ServiceGraph not rendering dotviz
- Dashboard not displaying data
- Deploying BookInfo only works in the same namespace as the istio components (istio-system)

Happy to schedule a time to walk through the helm chart to demo the UX and gather feedback.

**Comment by andraxylia** [comment]
Great, thanks @lachie83 !

For ServiceGraph and Dashboard cc @douglas-reid 

I need to try bookinfo, it works for us, and the fact istio is install with helm should not change behaviour.

**Comment by douglas-reid** [comment]
@lachie83 how can I help troubleshoot? have you tried deploying in a similar fashion (w/o Helm) and verified that dotviz and the istio dashboard work as expected with your test case?

Should we troubleshoot in a separate thread?

**Comment by lachie83** [comment]
@douglas-reid Thanks for reaching out Doug. No doubt I've probably make a typo in the configuration when converting to Helm. I have a cluster up and running with helm and just need a set of eyes to walk me through how to debug. Do you have a free 30m to jump on a zoom?

**Comment by douglas-reid** [comment]
@lachie83 Sure. Maybe tomorrow mid-morning?  Let's schedule over email: dougreid at google.

**Comment by linsun** [comment]
> Deploying BookInfo only works in the same namespace as the istio components (istio-system)
I have been deploying bookinfo in the default namespace, and it works fine.  In fact, we don't recommend users to deploy the microservices in the istio-system namespace, as automatic side car injection would not work.

**Comment by lachie83** [comment]
@andraxylia I've fixed all remaining issues and the PR should be good to review. I was able to work around all but a single helm issue which was to do with the initializer install which I will follow up.

**Comment by lachie83** [comment]
Thanks @linsun I found an issue in my configuration and have fixed this. I'm now able to install bookinfo into another namespace.

**Comment by andraxylia** [comment]
Thanks, I will review as well. FYI, the initializer requires kubernetes cluster with alpha features enabled.

**Comment by lachie83** [comment]
@ldemailly we may have to rethink the way we're doing chart versioning. See https://github.com/kubernetes/helm/issues/3009

**Comment by costinm** [comment]
Based on feedback, we are going with making the helm functionally identical with the old templates and deprecating.

**Comment by ldemailly** [comment]
that hasn't shipped, did it ? so a bit early to close, no ?

**Comment by hklai** [comment]
I believe helm is standard now. Closing.
