### ISSUE TITLE
Apply for Istio membership

### ISSUE THREAD

**Issue by islinwb** [istio/istio#8522]
Hello Istio Team,
I want to an istio member.
I think met the requirements: https://github.com/istio/community/blob/master/ROLES.md#member
My focus is on code quality, catching bugs.

Some of my contributions (Pull Requests):
https://github.com/istio/istio/pull/7921
https://github.com/istio/istio/pull/8025
https://github.com/istio/istio/pull/8257
https://github.com/istio/istio/pull/8262
https://github.com/istio/istio/pull/8300
https://github.com/istio/istio/pull/8303
https://github.com/istio/istio/pull/8375
https://github.com/istio/istio/pull/8431
https://github.com/istio/istio/pull/8449

Issues involved:
https://github.com/istio/istio/issues/8373
https://github.com/istio/istio/issues/8497

with @hzxuzhonghu @sdake as sponsors
/cc @linsun

**Comment by hzxuzhonghu** [comment]
+1, thanks @islinwb for contibution to ut and some cleanup work.

**Comment by gyliu513** [comment]
+1 and welcome!
