### ISSUE TITLE
authn policy PERMISSIVE mode support for TCP service

### ISSUE THREAD

**Issue by incfly** [istio/istio#8540]
When implementing TLS multiplexing, it's my misunderstanding that authn policy only works for http service.

For mTLS peer authentication we still can use authn policy to configure a TCP service in `STRICT` `PERMISSIVE` different modes.

We should support that as well.

**Comment by incfly** [comment]
FYI @PiotrSikora @diemtvu

**Comment by diemtvu** [comment]
Release 1.0 was fixed by https://github.com/istio/istio/issues/8540
Master was fixed by incfly@ when refactoring listener code (the part that create filter chain moved below the protocol switch, so it is shared by both TCP and HTTP).

**Comment by mandarjog** [comment]
@Diem Vu <diemvu@google.com> 8540 is pointing back the issue itself, can
you link to the correct PR ?
