### ISSUE TITLE
Citadel in CrashLoopBackOff

### ISSUE THREAD

**Issue by mabushey** [istio/istio#8542]
**Describe the bug**
Use helm to create a yaml file including grafana

**Expected behavior**
running grafana container

**Steps to reproduce the bug**
helm template ../istio/install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true  --set grafana.security.enabled=true  --set grafana.security.adminUser=admin --set grafana.security.adminPassword=mypass > istio.yaml

kubectl create ns istio-system
kubectl apply -n istio-system -f istio.yaml

```
$ kubectl get all --all-namespaces | grep -i istio

istio-system   pod/grafana-67c5b957f9-l79mq                                             0/1       CreateContainerConfigError   0          8m
istio-system   pod/istio-citadel-7d9c98786d-prpwn                                       0/1       CrashLoopBackOff             6          8m
istio-system   pod/istio-cleanup-secrets-s5fhb                                          0/1       Completed                    0          8m
istio-system   pod/istio-egressgateway-7bdd8c695f-t6g6f                                 1/1       Running                      0          8m
istio-system   pod/istio-galley-6c799667d4-jscww                                        0/1       ContainerCreating            0          8m
...
istio-system   pod/istio-sidecar-injector-c8c4c568b-55h7z                               0/1       ContainerCreating            0          8m
...
```

**Version**

```
$ istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not?**
No idea

**Environment**
Kops w/coreOS on AWS

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2358972/istio-dump.tar.gz)

**Comment by mabushey** [comment]
If I drop off the auth on grafana: `helm template ../istio/install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true > istio.yaml`

I get a running pod/grafana-7dc59cdfff-4pch7
I think this is the secret created in the wrong namespace bug.

I still have citadel crashing: 
`istio-system   pod/istio-citadel-7d9c98786d-bc8pm                                       0/1       CrashLoopBackOff    5          3m`

Is there any way to get logs on this?

**Comment by myidpt** [comment]
Can you run `kubectl logs -l istio=citadel -n istio-system`? Thanks.
