### ISSUE TITLE
Got `HTTP/1.1 403 Forbidden` from envoy when try to use HTTP/2

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#8552]
**Describe the bug**

Run curl in another cluster:

`curl --http2 http://my-service:8080`

I got this:

```
*   Trying 100.70.238.220...
* TCP_NODELAY set
* Connected to my-service (100.70.238.220) port 8080 (#0)
> GET / HTTP/1.1
> Host: my-service:8080
> User-Agent: curl/7.56.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
< HTTP/1.1 403 Forbidden
< date: Fri, 07 Sep 2018 11:36:25 GMT
< server: envoy
< connection: close
< content-length: 0
<
* Closing connection 0
```

It works when I remove auto-inject.

**Version**
1.0.1

**Is Istio Auth enabled or not?**
no

**Comment by rdsubhas** [comment]
Here is an updated issue: https://github.com/istio/istio/issues/16391 and a repo with reproduceable test case https://github.com/rdsubhas/java-istio

This basically breaks ALL Java 11+ applications and most Java 9+ applications, as that's the default behavior of Java.
