### ISSUE TITLE
Add annotations for setting limits on sidecar proxy containers

### ISSUE THREAD

**Issue by wmuizelaar** [istio/istio#8553]
**Describe the feature request**
I would like to have annotations for setting sidecar limits, next to requests as can be done by setting `sidecar.istio.io/proxyCPU` and `sidecar.istio.io/proxyMemory` annotations.

**Describe alternatives you've considered**
None.

**Additional context**
Currently, requests and limits of the sidecar proxy can be set generally though the helm-chart by passing options like `--set global.proxy.resources.limits.cpu=1024m`. For requests, these defaults can be overridden by using the aboven mentioned annotations, but that is not possible for limits.

I would like to have annotations like `sidecar.istio.io/proxyLimitCPU` and `sidecar.istio.io/proxyLimitMemory` added, so these can be overridden as well. (Naming obviously open for debate.

If agreed, I can try creating a PR to facilitate this.

**Comment by dotw** [comment]
I need to feature too. We must change the sidecar configuration based on the service types. e.g give more limited resources for transaction-intensive services, and less for others.

**Comment by ostromart** [comment]
Sounds good to me.

**Comment by fisherxu** [comment]
Have some discuss at this PR, PTAL #[8584](https://github.com/istio/istio/pull/8584#discussion_r217796747), but still have no conclusion now...
