### ISSUE TITLE
Pilot EDS, ADS, CDS not updated when remote cluster removed

### ISSUE THREAD

**Issue by john-a-joyce** [istio/istio#8554]
**Describe the bug**
In a multicluster scenario when a secret is deleted EDS and ADS is not updated properly.
The logs show that the cluster is properly deleted:

2018-09-07T12:41:01.190718Z     info    Deleting cluster member: ds82.conf
2018-09-07T12:41:01.190752Z     info    Registry for the cluster ds82.conf has been deleted.
2018-09-07T12:41:01.190797Z     info    Number of clusters in the cluster store: 0

But when curling debug/cdsz, debug/edsz or debug/adsz the endpoints and services for the remote cluster are still shown 

**Expected behavior**
When a remote cluster is removed from the cluster registry the associated services and endpoints from that cluster should also be deleted.  

**Steps to reproduce the bug**
Deploy a multicluster scenario.  Deploy services and endpoints on the remote.   Then delete the remote cluster.  Check that the cds, eds, and ads in pilot to check for full removal of remote cluster resources.  

**Version**

This was confirmed on master from Sept 4th, 2018.  

 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

root@bxb-ds-84:~# go/out/linux_amd64/release/istioctl version
Version: 4e5e14668a62e0b1a3c2d1d6fc763d14fa7ad4e1
GitRevision: 4e5e14668a62e0b1a3c2d1d6fc763d14fa7ad4e1
User: root@bxb-ds-84
Hub: docker.io/istio
GolangVersion: go1.10
BuildStatus: Clean

**Is Istio Auth enabled or not?**
No pertinent to this issue 

**Environment**
Developer baremetal single node cluster. 

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
That's really not acceptable. Let me have a look.
