### ISSUE TITLE
Istio Grafa not able to access

### ISSUE THREAD

**Issue by leeadh** [istio/istio#8556]
So i am running istio on aws ec2. 

I am trying to depoy the grafana dashboard via this

kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=grafana -o jsonpath='{.items[0].metadata.name}') 3000:3000

However, when i try to access masterip:3000, nothing happens. 

it slistening on port 3000 when i did a lsof 

 lsof -i:3000
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
kubectl 12267  opc    6u  IPv4  45964      0t0  TCP localhost:hbci (LISTEN)
kubectl 12267  opc    7u  IPv6  45965      0t0  TCP localhost:hbci (LISTEN)

Whats happening. on local host this work however

**Comment by sdake** [comment]
port-forward only binds to `127.0.0.1` IOW, it will not bind to your master IP.  port-forward will not do what you want. In 1.0.0, there are config options called `telemetry-ingress` however that feature was DOA in 1.0.0 sadly.  1.0.2 has resolved this problem with commit: https://github.com/istio/istio/commit/40143b05d92e5192df5a4629da7ece36111aed17.  I'd encourage you to try 1.0.2

Use the helm commands documented with `--set telemetry-gateway.grafanaEnabled` and access port `15031` of your load balancer external IP.  Note there is no authentication!

Can you point out the documentation which mentions to use port-forward so it can be corrected?

Cheers
-steve

**Comment by douglas-reid** [comment]
@leeadh and @sdake this is probably better discussed on a mailing-list.

Can we please move this to: istio-users@ googlegroups.com ?

**Comment by sdake** [comment]
@leeadh can you report this question on the mailing list please.

Thanks!
-steve

**Comment by leeadh** [comment]
https://istio.io/docs/tasks/telemetry/using-istio-dashboard/

@sdake.  An using istio 1.1.0
