### ISSUE TITLE
Error creating bookinfo-gateway

### ISSUE THREAD

**Issue by delubi** [istio/istio#8557]
I'm new to istio. Set up istio 1.0.1 with Kubernetes 1.10.4. Below are the steps performed.

```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
helm install install/kubernetes/helm/istio --name istio --namespace istio-system

kubectl get pods -n istio-system
NAME                                        READY     STATUS    RESTARTS   AGE
istio-citadel-769b85bf84-9rlb9              1/1       Running   0          1m
istio-egressgateway-677c95648f-xnl59        1/1       Running   0          1m
istio-galley-5c65774d47-sghgr               1/1       Running   0          1m
istio-ingressgateway-6fd6575b8b-rxrlx       1/1       Running   0          1m
istio-pilot-65f4cfb764-dfckc                2/2       Running   0          1m
istio-policy-5b9945744b-p9pqb               2/2       Running   0          1m
istio-sidecar-injector-75bfd779c9-p8zxx     1/1       Running   0          1m
istio-statsd-prom-bridge-7f44bb5ddb-bzrzf   1/1       Running   0          1m
istio-telemetry-5fc7ccc5b7-lbfnr            2/2       Running   0          1m
prometheus-84bd4b9796-d6vrb                 1/1       Running   0          1m

```

Then I tried following the steps in https://istio.io/docs/examples/bookinfo/

```
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)

kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

```

Getting error as below

[root@k8smaster istio-1.0.1]# kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
Error from server (InternalError): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: Proxy Error ( Try the request again.  )
Error from server (InternalError): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: Proxy Error ( Try the request again.  )

Note that the host node has to access Internet via http proxy so in my .bashrc, I have

```
export http_proxy=http://<proxy ip>:<proxy port>
export https_proxy=http://<proxy ip>:<proxy port>
export no_proxy=127.0.0.1,localhost,istio-galley.istio-system.svc
```

Any suggestion how to resolve the issue?

Thanks,
Forrest

**Comment by sdake** [comment]
@delubi welcome to Istio!  Which cloud platorm are you using?

**Comment by delubi** [comment]
@sdake My k8s runs in a CentOS7 VM in VMware vCenter. I deployed istio in the k8s.

**Comment by jungsh83** [comment]
@sdake I have same problem in my k8s cluster, too. My k8s cluster has been installed on CentOS7 & physical machine (HP DL360e Gen8).

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by daugustus** [comment]
I am having a similar problem with the bookinfo demo on AWS-eks but I think this has to do with the automatic sidecar injection. Here are my commands:
`kubectl label namespace default istio-injection=enabled`
`kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml`

```
> service "details" created
> deployment.extensions "details-v1" created
> service "ratings" created
> deployment.extensions "ratings-v1" created
> service "reviews" created
> deployment.extensions "reviews-v1" created
> deployment.extensions "reviews-v2" created
> deployment.extensions "reviews-v3" created
> service "productpage" created
> deployment.extensions "productpage-v1" created
```

`kubectl get services`

```
> NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
> details       ClusterIP   10.100.53.144    <none>        9080/TCP   1m
> kubernetes    ClusterIP   10.100.0.1       <none>        443/TCP    3h
> productpage   ClusterIP   10.100.102.48    <none>        9080/TCP   1m
> ratings       ClusterIP   10.100.105.236   <none>        9080/TCP   1m
> reviews       ClusterIP   10.100.132.216   <none>        9080/TCP   1m
```

`kubectl get pods`

```
> NAME                           READY     STATUS    RESTARTS   AGE
> details-v1-6865b9b99d-d6clt    1/1       Running   0          4m
> productpage-v1-f8c8fb8-mkf4c   1/1       Running   0          4m
> ratings-v1-77f657f55d-842p7    1/1       Running   0          4m
> reviews-v1-6b7f6db5c5-gsh6n    1/1       Running   0          4m
> reviews-v2-7ff5966b99-rck8l    1/1       Running   0          4m
> reviews-v3-5df889bcff-x6nch    1/1       Running   0          4m
```

**At this point, shouldn't there be 2 pods as the demo shows?**

and the gateway creation step fails...
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`

```
> unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
> unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
```

`kubectl version`

> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Thanks for your help!!!

**Comment by Vineet-Sharma29** [comment]
Similar error on `GKE`. @daugustus Were you able to solve it?

**Comment by alikumbhar** [comment]
i am also facing same issue ?
