### ISSUE TITLE
Improve efficiency of service account lookup in Pilot

### ISSUE THREAD

**Issue by incfly** [istio/istio#8560]
Imagine a mesh has N services, each uses different service account, and each pair of service(s1,s2) needs to talk to each other. Pilot needs to generate N Clusters for all N services.

When mTLS is turned on, we need to lookup a service account a service is running as for secure naming, which is used to set `Cluster.TLSContext.VerifySubjects`.  This is implemented as a O(N) [complexity iteration](https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller.go#L522).

The overall complexity for finishing all calculation thus is O(N^3), which can be improved.

This bug is to track the investigation, measurements, and actual optimization implementation.

**Comment by incfly** [comment]
/cc @costinm @diemtvu

It's important to have some load testing framework to actual measure before and after. @hklai,  @mandarjog  do you know if there's any off-shelf framework for this purpose? I'd like to have some consistent framework instead one-off manual measurement.

**Comment by wattli** [comment]
+1, looking forward to a design

**Comment by incfly** [comment]
Copy from https://github.com/istio/istio/issues/10263#issue-387093122

Currently during push, GetIstioServiceAccounts is called when pilot generate outbound clusters for each proxy. It is very inefficient, complexity is O(n*n).

Should better cache the ServiceAccounts in push context, like map[hostname:port]-->[]string. Just like allServices virtualServiceConfigs...

**Comment by jnativio** [comment]
@incfly @mandarjog Is this issue still worth to pursue given the new Pilot design?
