### ISSUE TITLE
ServiceEntry should support port ranges

### ISSUE THREAD

**Issue by gtseres** [istio/istio#8579]
**Describe the feature request**
When deploying a microservice, there are cases where you want to talk with some external service, e.g. a DB, which resides in another provider (externally to the cluster). Some of those providers assign random ports to the services that your provision (e.g. MongoLab). In order to create generic rules that allow traffic to that domain and subdomains, one has to define a range of ports, or to allow all ports. Currently, the `ServiceEntry` spec does not allow that. It would be great to add support, as bypassing the proxy would not allow one to have visibility into that kind of egress traffic.

**Describe alternatives you've considered**
Bypassing the traffic comes with losing the observability Istio provides.

**Additional context**
N/A

**Comment by dstockton** [comment]
👍

**Comment by JoshKeegan** [comment]
@hzxuzhonghu (Sorry if you're not the right person, just pinging a random member): can this issue be re-opened & marked as "help wanted"?

**Comment by dal13002** [comment]
This would be a really helpful feature. Any way to reopen this?

**Comment by tgolly** [comment]
This would be incredibly useful.
