### ISSUE TITLE
Implement test cases to make sure local e2e testing scripts are not broken

### ISSUE THREAD

**Issue by hklai** [istio/istio#8598]
The scripts for local e2e testing are getting more complicated now. Without automatic tests, it is very difficult to maintain and ensure it really does what we need.

Therefore, it may be a good idea to implement some automatic tests to run in CI for sanity testing.

For example, we can bring up minikube, exercise the scrips, and run e2e_simple on both mac and linux on circle ci (not sure about centos, need to confirm). 

And we can probably do the same to exercise the vagrant path as well.

**Comment by m1093782566** [comment]
I am interested in joining this effort!

Self assigning...

**Comment by m1093782566** [comment]
cc @rshriram

**Comment by hklai** [comment]
@m1093782566 In a nutshell, I think what we want to do is to exercise https://github.com/istio/istio/blob/master/tests/e2e/local/minikube/README.md and https://github.com/istio/istio/blob/master/tests/e2e/local/vagrant/README.md.

So, I imagine here is what we want to do:

1. Provision a VM on circle (similar to all other circle jobs we already have).
2. Exercise the install_prereq script (probably most prereqs are already pre-installed, but at least it's a way to exercise the script).
3. Exercise the setup_host script.
4. Exercise the setup_test script.
5. Run one or two e2e tests for sanity checking (e.g. make e2e_simple)

I expect we can test the above on both linux and macos. We have a macos jobs set up in the proxy repo. Perhaps you can take a look as well.  https://github.com/istio/proxy/blob/master/.circleci/config.yml#L69
