### ISSUE TITLE
Can't create virtual service, 504 Gateway Timeout?

### ISSUE THREAD

**Issue by yantang-msft** [istio/istio#8603]
**Describe the bug**
I successfully followed [Configuring Request Routing](https://istio.io/docs/tasks/traffic-management/request-routing/). When I'm trying to follow [Fault Injection](https://istio.io/docs/tasks/traffic-management/fault-injection/), this command ``` kubectl apply -f samples/bookinfo/networking/virtual-service-ratings-test-delay.yaml``` failed.
Then I removed the virtual services by ```kubectl delete -f samples/bookinfo/networking/virtual-service-all-v1.yaml``` and try to create them, still got a time out failure.

Here is the details of the request
```
I0910 14:39:11.381910   30520 request.go:874] Request Body: {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"name":"ratings","namespace":"default"},"spec":{"hosts":["ratings"],"http":[{"route":[{"destination":{"host":"ratings","subset":"v1"}}]}]}}
I0910 14:39:11.381910   30520 round_trippers.go:383] POST https://yanmingaks4-6e282a32.hcp.eastus.azmk8s.io:443/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices
I0910 14:39:11.381910   30520 round_trippers.go:390] Request Headers:
I0910 14:39:11.382889   30520 round_trippers.go:393]     Content-Type: application/json
I0910 14:39:11.382889   30520 round_trippers.go:393]     User-Agent: kubectl/v1.10.3 (windows/amd64) kubernetes/2bba012
I0910 14:39:11.383892   30520 round_trippers.go:393]     Accept: application/json
I0910 14:39:11.383892   30520 round_trippers.go:393]     Authorization: Bearer c656f3a577e7515eb1b8c785bde4d016
I0910 14:39:41.462112   30520 round_trippers.go:408] Response Status: 504 Gateway Timeout in 30078 milliseconds
I0910 14:39:41.462112   30520 round_trippers.go:411] Response Headers:
I0910 14:39:41.462112   30520 round_trippers.go:414]     Content-Type: application/json
I0910 14:39:41.463112   30520 round_trippers.go:414]     Content-Length: 182
I0910 14:39:41.463112   30520 round_trippers.go:414]     Date: Mon, 10 Sep 2018 21:39:41 GMT
I0910 14:39:41.463112   30520 request.go:874] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within allowed duration","reason":"Timeout","details":{},"code":504}
```

**Expected behavior**
I should be able to create virtual services as documented.

**Steps to reproduce the bug**
1. Install istio and enable mutual TLS ```kubectl apply -f install/kubernetes/istio-demo-auth.yaml```
2. Deploy bookinfo app as described [here](https://istio.io/docs/examples/bookinfo/)
3. It may succeed for the first time, but will never work again after a while. I reproduced this on two of my Azure AKS cluster.

**Version**
istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9
.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3
", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
Yes, I used this yaml istio-demo-auth.yaml

**Environment**
Azure AKS

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2368646/istio-dump.tar.gz)

**Comment by yantang-msft** [comment]
I promise it kept failing for couple hours, but somehow is working again after I created this issue. And from the command output you can see it's failed partially of my first command. 
I'll leave this issue open in case you still want to investigate what happened.
```
D:\istio-1.0.2>kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml
virtualservice.networking.istio.io "ratings" created
virtualservice.networking.istio.io "details" created
Error from server (Timeout): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when creating "samples/bookinfo/networking/virtual-service-all-v1.yaml": Timeout: request did not complete within allowed duration

D:\istio-1.0.2>kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml
virtualservice.networking.istio.io "productpage" created
virtualservice.networking.istio.io "reviews" created
virtualservice.networking.istio.io "ratings" configured
virtualservice.networking.istio.io "details" configured

D:\istio-1.0.2>kubectl apply -f samples/bookinfo/networking/virtual-service-ratings-test-delay.yaml
virtualservice.networking.istio.io "ratings" configured
```

**Comment by slega** [comment]
The same here (see the log below), did anybody know how to fix this?

`I0124 18:09:29.470703    2355 request.go:942] Request Body: {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"name":"my-wiki-rule","namespace":"default"},"spec":{"hosts":["wikipedia.org"],"http":[{"route":[{"destination":{"host":"wikipedia.org"}}],"timeout":"5s"}]}}
I0124 18:09:29.470737    2355 round_trippers.go:383] POST https://XX.XX.XX.XX:6443/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices
I0124 18:09:29.470742    2355 round_trippers.go:390] Request Headers:
I0124 18:09:29.470747    2355 round_trippers.go:393]     Accept: application/json
I0124 18:09:29.470751    2355 round_trippers.go:393]     Content-Type: application/json
I0124 18:09:29.470755    2355 round_trippers.go:393]     User-Agent: kubectl/v1.12.3 (linux/amd64) kubernetes/435f92c
I0124 18:09:59.472591    2355 round_trippers.go:408] Response Status: 504 Gateway Timeout in 30001 milliseconds
I0124 18:09:59.472625    2355 round_trippers.go:411] Response Headers:
I0124 18:09:59.472642    2355 round_trippers.go:414]     Content-Length: 187
I0124 18:09:59.472646    2355 round_trippers.go:414]     Date: Thu, 24 Jan 2019 15:09:59 GMT
I0124 18:09:59.472650    2355 round_trippers.go:414]     Content-Type: application/json
I0124 18:09:59.472690    2355 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout 30s","reason":"Timeout","details":{},"code":504}
I0124 18:09:59.472944    2355 helpers.go:201] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"wiki.yaml\": Timeout: request did not complete within requested timeout 30s",
  "reason": "Timeout",
  "details": {},
  "code": 504
}]
F0124 18:09:59.472968    2355 helpers.go:119] Error from server (Timeout): error when creating "wiki.yaml": Timeout: request did not complete within requested timeout 30s`
