### ISSUE TITLE
Overlapping meaning from card client.Get

### ISSUE THREAD

**Issue by zhaogaolong** [istio/istio#8609]
code in https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L333

why return Pointer type and bool type，this return two value have overlapping meaning . 

Pointer type can completely replace boolean type. don't need return bool, this is bed code.

**Comment by hzxuzhonghu** [comment]
Indeed.

/assign

**Comment by caitong93** [comment]
By returning nil, we have no change to know what error happened inside.
Please consider return the error so we can react to it.
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
There is no error, just not exists.

**Comment by caitong93** [comment]
I mean the error returned by apiserver
https://github.com/hzxuzhonghu/istio/blob/76a09e95f59c9c0a44cd9dba9e1bc38851ed937c/pilot/pkg/config/kube/crd/client.go#L352
