### ISSUE TITLE
unecessary redownload of istioctl slows down dev+test cycle

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#861]
each time I run my test and the test code change or the test fails, for instance
```
bazel run //tests/e2e/tests/simple:go_default_test -- -alsologtostderr -test.v -v 2 -test.run TestSvc2Svc --skip_setup --skip_cleanup --auth_enable --namespace=e2e-test4
```
the same istioctl is re-downloaded:

```
I0918 22:33:44.783560   68809 commonUtils.go:110] Start downloading from https://storage.googleapis.com/istio-artifacts/pilot/438acd5c5a0069b707e392f86f44e40946a59fad/artifacts/istioctl/istioctl-osx to /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/istio.e2e.999444277/istioctl ...
```

**Comment by ldemailly** [comment]
cc @andraxylia to explain "by design, it’s correct behaviour" (oh can it be correct behavior to redownload the exact same istioctl by sha more than once)

**Comment by andraxylia** [comment]
It is correct to download the version specified in istio.VERSION, and test against it.

**Comment by ldemailly** [comment]
> It is correct to download the version specified in istio.VERSION, and test against it.

that's not what I asked about on slack nor wrote here

**Comment by ldemailly** [comment]
source if the download is https://github.com/istio/istio/blob/6f17cf513217c13422cc55724a4ef2dfbc3398b6/tests/e2e/framework/istioctl.go#L113

and a workaround is to download manually and then use -istioctl location but that doesn't work inside bazel run

once I have a short version I'll update https://github.com/istio/istio/blob/master/tests/e2e/README.md
(if there is any Bazel guru listening, there should be a way to make bazel do the download so it will cache it/not download it over and over again no ?)
