### ISSUE TITLE
Propose remove ingress

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#8613]
It is time for us to remove ingress totally.  It does not take effect now.

In 0.8:  https://istio.io/about/notes/0.8/#networking
```
Gateway for Ingress/Egress. We no longer support combining Kubernetes Ingress specs with Istio routing
rules as it has led to several bugs and reliability issues. 
```

In 1.1:  https://istio.io/about/notes/1.0/#networking

```
Istio Ingress Deprecated. The old Istio ingress is deprecated and disabled by default. 
We encourage users to use gateways instead.
```

**Comment by hzxuzhonghu** [comment]
Can anyone give some comments?

**Comment by sdake** [comment]
@hzxuzhonghu this had been planned for 1.0, but we wanted a transition phase for folks to be able to upgrade from 0.8 to 1.0.  Removing in 1.1 seems fine to me.

Cheers
-steve

**Comment by rshriram** [comment]
Wait, you want to remove the entire ingress controller code ? I don’t mind but I think some google folks wanted to have ingress support around for things like letsencrypt etc.

**Comment by hzxuzhonghu** [comment]
Thanks, will wait acks from google.
