### ISSUE TITLE
404 on request to Pod IP

### ISSUE THREAD

**Issue by sapien99** [istio/istio#8617]
**Describe the bug**
I have several (in the test 2) pods belonging to one deployment. I can call them by service/virtualservice without any problem using their servicename, but when i call them using their pod-ip (kubetcl get pods -o wide) i end up with a 404. I guess thats because there is no host-entry matching to the ip.

When i set the servicename explicitly as the host-header i can reach it - but then the normal service-routing seems to kick in - which results in both of the pods getting requests. Same behavior when using the pod-ip as a hostname in the virtualservice. Unfortunately hardcoding them is not an option as those applications need to be scalable and the mentioned deployment normally contains 10+ replicas.

We need that because we have a second service-registry which picks the pods to call on base of several (business) criteria, for an instance the data they have deployed. Mid-term we want to change that and go to a more "kubernetes-ish" way using labels etc, but currently its unfortunately a showstopper.

A possible scenario which i am currently testing may be to exclude the whole range of pod-ips from envoy, would that be the suggested solution?

**Expected behavior**
requests using POD IP route to the specified pod

**Steps to reproduce the bug**
- create a deployment with 2 istio-proxy-injected pods
- kubectl get pods -o wide to get the pod-ips
- curl on any pod-ip from inside another pod

**Version**
$istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Is Istio Auth enabled or not?**
helm template istio-1.0.1/install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true

**Environment**
Azure AKS

**Comment by cmidt-veasna** [comment]
I run into the same issue. In our case, we have a deployment which have multiple pod implement Ralf Protocol. Pod need to communicate to each other for log replication. However base on a [google group thread](https://groups.google.com/forum/#!topic/istio-users/d-THsO19oAM), I learn that Istio model does not allow pod to pod communication from the same cluster or deployment.

**Comment by sapien99** [comment]
Hey cmidt-veasna, there actually is a solution i found - dont know why its not mentioned in the docs. You can specify CIDRS ranges also in the annotations traffic.sidecar.istio.io/excludeOutboundIPRanges  and traffic.sidecar.istio.io/excludeInboundIPRanges on pod-template in your deployments. 

Its possible to choose between blacklist and whitelist (personally i like to exclude things from the standard better than changing it), and the fact that you can set it on deployment/pod level is awesome - because only some deployment need that functionality

**Comment by cmidt-veasna** [comment]
@sapien99 Thanks, I'll try it later.

**Comment by mandarjog** [comment]
What is your exact use case? Why are you trying to reach these pods individually?

**Comment by cmidt-veasna** [comment]
@mandarjog For my use case, our application is implemented Raft Protocol where each pod required direct communication to each other for log replication and proxy to leader pod. The election phase was working fine as it's using Go Kubernetes client library to perform leader election. However after election process, leader pod need to send replicates log to the follower pod that why it's require to access pod directly by ip address.

**Comment by mandarjog** [comment]
Do you have a need for the direct pod to pod traffic to be encrypted? Do you need to apply other policies?

**Comment by markya0616** [comment]
Any updates about this issue. We also need similar feature.

**Comment by jaygorrell** [comment]
A real and popular example of this is the datadog daemonset and how it reaches `kube-state-metrics`.  If you try to run DD in the mesh, the logs will fill with things like:
```
[ AGENT ] 2019-04-01 02:14:20 UTC | ERROR | (runner.go:289 in work) | Error running check kubernetes_state: [{"message": "404 Client Error: Not Found for url: http://100.126.128.5:8080/metrics", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py\", line 387, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/kubernetes_state/kubernetes_state.py\", line 99, in check\n    self.process(scraper_config, metric_transformers=self.METRIC_TRANSFORMERS)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 294, in process\n    for metric in self.scrape_metrics(scraper_config):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 262, in scrape_metrics\n    response = self.poll(scraper_config)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 424, in poll\n    response.raise_for_status()\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py\", line 940, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nHTTPError: 404 Client Error: Not Found for url: http://100.126.128.5:8080/metrics\n"}]
```

100.126.128.5 in this case is the pod IP of kube-state-metrics.
