### ISSUE TITLE
To support `Single Sign-On` scenario, `Istio Origin Authentication` should accept a `JWT Token` sent in a `cookie`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#8619]
**Describe the feature request**
To support `Single Sign-On` scenario, `Istio Origin Authentication` should accept a `JWT Token` sent in a `cookie`.

**Describe alternatives you've considered**
- At the moment, we're using a `Lua` script that runs before `jwt-auth` filter and copies `JWT Token` from a `cookie` into a `header`
- However, this solution has a number of downsides:
  - As Istio documentation points out, this is a break glass configuration; it has to be re-assesed on every `Istio` upgrade
  - `Lua` support in `Envoy` is not stable yet: there are open tickets for `Lua` filter crashing `Envoy` (
https://github.com/envoyproxy/envoy/issues/4305) and `Lua` filter causing memory leaks (
https://github.com/envoyproxy/envoy/issues/3570)

**Additional context**
From API perspective, `istio.authentication.v1alpha1.Jwt` resource (
https://istio.io/docs/reference/config/istio.authentication.v1alpha1/) should support one more field, ie `jwt_cookies`

```
message Jwt {
  ...
  repeated string jwt_headers = 6;

  repeated string jwt_params = 7;
  ...
  repeated string jwt_cookies = 9;
}
```

**Comment by Nisreen123** [comment]
any update on this?

**Comment by Bessonov** [comment]
Interested in this too. Storing JWT on localStorage isn't an option. Even there is no 100% protection, but Cookie + CSRF-Protection improve security AFAIK.

But I doubt that istio should care about JWT at all. For me it's out of the scope, even it is nice. Things get more complicated, if you want to accept JWT as Cookie from a browser.

**Comment by tnwang** [comment]
You might be interested in https://docs.google.com/document/d/1mGpUsRgmA9wPB73trfTiB9YUuwYh-31iulYg9USxe0Y/edit#heading=h.qex63c29z2to - While it's not directly this requested functionality, there's some overlap that could be extended upon as the linked proposal provides a basic feature set related to End User OIDC and session management.

**Comment by Miouge1** [comment]
Is the recommendation to add a proxy service to translate cookies into Authorization header?

**Comment by xeor** [comment]
We need this as well, trying to setup SSO (beyondcorp style) using keycloak. @yskopets can you please share some of the configuration/lua you are doing as a workaround?

**Comment by farcaller** [comment]
I'd also be interested in the existing workarounds.

**Comment by samwyma** [comment]
Hey guys,

We ended up doing something similar to what @yskopets is doing, so I'll share the code here (it's a relatively small lua script). The basic flow is: 
- An Envoy Filter extracts the JWT from a cookie and sets it in a header
- An Authentication Policy validates the JWT
- If the JWT is invalid, the same Envoy Filter catches the 401 and redirects off to a little server we run which basically redirects to Auth0 to do the Oauth flow

__NOTE__ that you probably want to update Istio to 1.1.8 as this contains a bug fix which makes Envoy Filters _a lot_ more stable. We've been running this for about a week for our internal SSO and it hasn't caused any issues so far.

Envoy Filter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-sso-filter-live
spec:
  workloadLabels:
    auth0_sso_filter: "live"
  filters:
  - filterConfig:
      inlineCode: |
        function stringSplit(inputstr, sep)
          if sep == nil then
            sep = "%s"
          end
          local t={}
          for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
            print (str)
            table.insert(t, str)
          end
          return t
        end
        function envoy_on_request(handle) 
          headers = handle:headers()
          streamInfo = handle:streamInfo()
          connection = handle:connection()
          dynamicMetadata = streamInfo:dynamicMetadata()
          dynamicMetadata:set("request_headers", "request_authority", headers:get(":authority"))
          dynamicMetadata:set("request_headers", "request_path", headers:get(":path"))

          proto = "http"
          if connection:ssl() ~= nil then
            proto = "https"
          else
            forwarded_proto = headers:get("x-forwarded-proto")
            if forwarded_proto ~= nil then
              proto = forwarded_proto
            end
          end
          dynamicMetadata:set("request_headers", "proto", proto)

          cookieString = headers:get("cookie")
          if cookieString ~= nil then
            splitCookieString = stringSplit(cookieString, ";")
            
            jwt = nil
            for i, cookieItem in ipairs(splitCookieString) do
              if string.find(cookieItem, "k8_sso") ~= nil then
                jwt = string.gsub(cookieItem, "k8_sso=", "")
              end
            end

            if jwt ~= nil then
              auth = string.gsub(jwt, "^ ", "")
              headers:replace("x-sso-auth", auth)
            end
          end
        end

        function envoy_on_response(handle) 
          headers = handle:headers()
          streamInfo = handle:streamInfo()
          dynamicMetadata = streamInfo:dynamicMetadata()
          requestData = dynamicMetadata:get("request_headers")
          headers:replace("x-auth-envoy-filter-passthrough", "yes")
          
          if headers:get(":status") == "401" then
            if requestData ~= nil then
              headers:replace(":status", "302")
              redirect_url = requestData["proto"].."://"..requestData["request_authority"]..requestData["request_path"]
              headers:replace("location", "https://auth.example.com/login?redirect="..redirect_url)
            end
          end
        end
    filterName: envoy.lua
    filterType: HTTP
    listenerMatch:
      listenerType: ANY
```
A couple notes on this: 
- Any pod with the label `auth0_sso_filter=live` will have this filter attached to it
- envoy_on_request does the following:
  - Extracts the JWT from a cookie called `k8_sso` and puts it in a header called `x-forwarded-proto`
  - It also assigns some metadata to the request such as the protocol, host, and path. This is because we cannot access the request itself in the response handler. I've assumed here that `dynamicMetadata` is per request. If anyone more familiar with Envoy knows otherwise please let me know!
- envoy_on_response simply redirects based on metadata should the response be a 401. In this example it redirects to `auth.example.com/login` and puts the current request url in as a query parameter. 

Here is the Authentication Policy:
```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: httpbin
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "https://my.issuer.domain.com/"
      jwksUri: "https://my.issuer.domain.com/.well-known/jwks.json"
      jwtHeaders: 
      - x-sso-auth
  principalBinding: USE_ORIGIN
```

I hope this is useful! If anyone has any questions or spots any issues then don't hesitate to shout out.

**Comment by yangminzhu** [comment]
@samwyma Thank you for the great workaround, that's very nice!

I think it shouldn't be too hard to allow getting the JWT token from cookie header, which doesn't look any strange to the other 2 options: from header or from params.

@diemtvu @qiwzhang Any thoughts?

**Comment by myidpt** [comment]
Temporarily setting it to P2. Please feel free to modify.

**Comment by ceastman-ibm** [comment]
@samwyma thank you for the hope for a 401 redirect, im trying to use your code but it doesnt seem to be working. would errors be in the istio ingress pods?

**Comment by liminw** [comment]
There is an effort to add OIDC token acquisition and session management for CSRF protection, as @tnwang mentioned in the [comment](https://github.com/istio/istio/issues/8619#issuecomment-467160143). It's relevant to the feature request here.

**Comment by robpacheco** [comment]
It looks like this issue has been open for a bit of time, as well as the OIDC being planned for a while. I'd like to help this effort where possible, either in terms of putting in place a short-term solution or helping the larger effort of support OIDC.

How can I help?

**Comment by liminw** [comment]
The OIDC effort is driven by @nickrmc83 and @peterhaochen47.

**Comment by Miles-Garnsey** [comment]
@samwyma, your lua filter looks very similar to what I need as well, but I'm using Keycloak, not auth0. With your auth0 endpoint, do you know which particular OIDC flow you're using? 

I don't know how much this depends on particular auth0 settings attached to your application, but it looks almost as though you're expecting the `/login` uri to hand you back a full JWT token, which I think corresponds to an implicit flow? There are diagrams of the various flows [here](https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660).

From my (very limited) understanding, Keycloak's defaults are set up to avoid the implicit flow by using the RFC 6749 authorization code flow, which would require an additional `POST` step after obtaining the authorization code in order to obtain the actual JWT token.

**Comment by Just-Insane** [comment]
I am also having issues getting this sort of setup working (Istio + Keycloak + Oauth2_Proxy) to get OIDC with Istio.

Were you able to get it working with Keycloak?

**Comment by nfickas** [comment]
@samwyma is there any reason why the above lua script wouldn't work with istio 1.4.2?

**Comment by samwyma** [comment]
> @samwyma, your lua filter looks very similar to what I need as well, but I'm using Keycloak, not auth0. With your auth0 endpoint, do you know which particular OIDC flow you're using?
> 
> I don't know how much this depends on particular auth0 settings attached to your application, but it looks almost as though you're expecting the `/login` uri to hand you back a full JWT token, which I think corresponds to an implicit flow? There are diagrams of the various flows [here](https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660).
> 
> From my (very limited) understanding, Keycloak's defaults are set up to avoid the implicit flow by using the RFC 6749 authorization code flow, which would require an additional `POST` step after obtaining the authorization code in order to obtain the actual JWT token.

@Miles-Garnsey 
Sorry about the delay in replying. At the basic level, all the envoy filter does is move a value from a cookie to a header, and also redirects to a authentication endpoint if a request is unauthorised. We have a small Node server running which basically proxies through to Auth0 and handles the OAuth flow itself, so the envoy filter just acts as a bridge to that.

I'm not sure if this possible for you to do, but it sounds like you should be handling the extra POST step on the server which authenticates with Keycloak? Then, once the full JWT is obtained you can tell the client to save a cookie containing the JWT (the authentication server needs to be under the same domain as whatever services your accessing)


> @samwyma is there any reason why the above lua script wouldn't work with istio 1.4.2?

@nfickas 
I guess it's possible? In the Istio docs for the Envoy Filter they used to have a warning that there was np guarantee that a filter would work with new releases of Istio.

We see this solution as fairly temporary and we only use it for backend services (e.g. Kibana), not customer facing apps. There are starting to be a [couple](https://istio.io/blog/2019/app-identity-and-access-adapter/) of [projects](https://github.com/istio-ecosystem/authservice) for an OIDC flow emerge with Istio, so it may be better to explore those (I'd be interested in knowing how you get on with them!)

**Comment by Just-Insane** [comment]
> We see this solution as fairly temporary and we only use it for backend services (e.g. Kibana), not customer facing apps. There are starting to be a couple of projects for an OIDC flow emerge with Istio, so it may be better to explore those (I'd be interested in knowing how you get on with them!)

These solutions are a lot nicer than what I was able to come up with - https://homelab.blog/blog/devops/Istio-OIDC-Config/ which is just an external auth. lua Filter and oauth2_proxy.

Cheers for that!

**Comment by cmanzi** [comment]
While doing this totally natively in Istio would be great - for anyone looking to do this I would recommend just using nginx-ingress + oauth2-proxy instead. It offers a much more streamlined integration, and it is perfectly compatible with Istio backend services.

**Comment by Miles-Garnsey** [comment]
@samwyma, cheers for the reply. Yes, I got this up and running already and it works quite smoothly. Running the POST request (required to avoid an implicit flow) out from inside the mesh takes a small amount of configuration, but it certainly isn't impossible.

 For anyone still having trouble with this matter, there is an app identity and access [adaptor](https://istio.io/blog/2019/app-identity-and-access-adapter/) for mixer also available, not sure if this is an alternative approach to our Lua hacks.

**Comment by Just-Insane** [comment]
@Miles-Garnsey do you have example code for this?

I’m interested in the part where you say it doesn’t require any external services. That would make things a lot easier, and in theory more secure if you don’t want to wildcard the redirect URL in Keycloak.

**Comment by davidxia** [comment]
I want to secure browser access to a port on a K8s Pod with required JWT and AuthorizationPolicy. Browsers don't send `Authorization: Bearer ...` HTTP headers on their own, but they do send cookies set for the domain being accessed.

I have a backend service that sets a `jwt` cookie containing the token for client browsers. I need to add a filter that runs before Istio's JWT authentication happens. @samwyma's snippet got me almost all the way there. Here's my working solution on Istio 1.17.1. The filter uses inline Lua code to extract the JWT token from the `jwt` cookie and set it in an `Authorization: Bearer TOKEN` HTTP header.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: binding-lily
  namespace: hackweek
spec:
  workloadSelector:
    labels:
      some-workload-label-key: some-workload-label-value
  configPatches:
  # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 3000  # protected port
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"  # need to run the Lua code below BEFORE the jwt_authn filter
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function stringSplit(inputstr, sep)
              if sep == nil then
                sep = "%s"
              end
              local t={}
              for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
                table.insert(t, str)
              end
              return t
            end
    
            function envoy_on_request(handle) 
              headers = handle:headers()
              streamInfo = handle:streamInfo()
              connection = handle:connection()
              dynamicMetadata = streamInfo:dynamicMetadata()
              dynamicMetadata:set("request_headers", "request_authority", headers:get(":authority"))
              dynamicMetadata:set("request_headers", "request_path", headers:get(":path"))
    
              proto = "http"
              if connection:ssl() ~= nil then
                proto = "https"
              else
                forwarded_proto = headers:get("x-forwarded-proto")
                if forwarded_proto ~= nil then
                  proto = forwarded_proto
                end
              end
              dynamicMetadata:set("request_headers", "proto", proto)

              # get cookie HTTP header
              cookieString = headers:get("cookie")
              if cookieString ~= nil then
                splitCookieString = stringSplit(cookieString, ";")

                # find the `jwt` cookie
                jwt = nil
                for i, cookieItem in ipairs(splitCookieString) do
                  if string.find(cookieItem, "jwt") ~= nil then
                    jwt = string.gsub(cookieItem, "jwt=", "")
                  end
                end
    
                # set the `Authorization` HTTP header
                if jwt ~= nil then
                  headers:replace("Authorization", "Bearer "..jwt)
                end
              end
            end
```

Here's my RequestAuthentication that authenticates JWTs and AuthorizationPolicy that requires a JWT with issuer (`iss`) of `admin@example.com` and subject (`sub`) `user1@example.com`.

```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: default
spec:
  jwtRules:
  - issuer: admin@example.com
    jwks: |
      { "keys":[{"kty":"RSA","e":"AQAB","n":"public-key"}]}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: my-policy
spec:
  action: DENY
  rules:
  - to:
    - operation:
        ports:
        - "3000"
    when:
    - key: request.auth.principal
      notValues:
      - admin@example.com/user1@example.com
  selector:
    matchLabels:
      some-workload-label-key: some-workload-label-value
```

**Comment by loeffel-io** [comment]
i was able to apply the envoy filter to all gateways successfully. It was required to do some changes, please see the comments. 

thank you @davidxia so much! 🙏 

```hcl
resource "kubernetes_manifest" "kubernetes_manifest_envoy_filter_jwt_cookie_to_authorization_header" {
  manifest = yamldecode(<<-EOF
    apiVersion: networking.istio.io/v1alpha3
    kind: EnvoyFilter
    metadata:
      name: jwt-cookie-to-authorization-header
      namespace: istio-system
    spec:
      configPatches:
        - applyTo: HTTP_FILTER
          match:
            context: GATEWAY # SIDECAR_INBOUND
            listener:
              portNumber: 3000
              filterChain:
                filter:
                  name: "envoy.filters.network.http_connection_manager"
                  subFilter:
                    name: "envoy.filters.http.router" # "envoy.filters.http.jwt_authn"
          patch:
            operation: INSERT_BEFORE
            value:
              name: envoy.filters.http.lua
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
                inlineCode: |
                  function stringSplit(inputstr, sep)
                    if sep == nil then
                      sep = "%s"
                    end
                    local t={}
                    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
                      table.insert(t, str)
                    end
                    return t
                  end

                  function envoy_on_request(handle)
                    headers = handle:headers()
                    streamInfo = handle:streamInfo()
                    connection = handle:connection()
                    dynamicMetadata = streamInfo:dynamicMetadata()
                    dynamicMetadata:set("request_headers", "request_authority", headers:get(":authority"))
                    dynamicMetadata:set("request_headers", "request_path", headers:get(":path"))

                    proto = "http"
                    if connection:ssl() ~= nil then
                      proto = "https"
                    else
                      forwarded_proto = headers:get("x-forwarded-proto")
                      if forwarded_proto ~= nil then
                        proto = forwarded_proto
                      end
                    end
                    dynamicMetadata:set("request_headers", "proto", proto)

                    cookieString = headers:get("cookie")
                    if cookieString ~= nil then
                      splitCookieString = stringSplit(cookieString, ";")

                      jwt = nil
                      for i, cookieItem in ipairs(splitCookieString) do
                        if string.find(cookieItem, "jwt") ~= nil then
                          jwt = string.gsub(cookieItem, "jwt=", "")
                        end
                      end

                      if jwt ~= nil then
                        headers:replace("Authorization", "Bearer "..jwt)
                      end
                    end
                  end
                  function envoy_on_response(response_handle)
                    filter_name = "jwt-cookie-to-authorization-header"
                    response_handle:headers():add("envoy-filter", filter_name)
                  end
    EOF
  )
}
```

**Comment by cabrinoob** [comment]
Today, in may 2023, do you know if there's any chance to have the support of "jwt cookie" directly in Istio JWTRules ? Because using a LUA script is the last thing I'd like to do because I'am an Istio user, not an envoy user.
As Istio users we should not be aware of that part imho. 
Then, the use case "SPA + backend API" is, I think, a really common use case, massively used, so the basic requirement with this kind of application is to use http only cookies to store sensitive data (such as access tokens). I'am surprised that Istio does not support that natively.

**Comment by cywang1905** [comment]
I alse hope istio can support to customize jwt extraction behavior from cookies.

**Comment by Stono** [comment]
Yeah +1 for this, having to hack around with envoy filters to extract from a cookie sucks.

**Comment by Stono** [comment]
Yeah +1 for this, having to hack around with envoy filters to extract from a cookie sucks and is a terrible devex. 

@howardjohn do you think this is something that could be discussed to potentially get on the radar?

**Comment by loeffel-io** [comment]
this is already be available with istio 1.21

**Comment by Stono** [comment]
Where?  I must be completely missing it in the docs!

**Comment by keithmattix** [comment]
I think it was added in https://github.com/istio/istio/pull/48099

**Comment by Stono** [comment]
Ah awesome, I will have a play in a bit, thanks all
