### ISSUE TITLE
Re-enable gometalinter test after install bug is fixed

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#8625]
as reported and disabled here: https://github.com/istio/istio/pull/8623

This issue is for tracking the work for re-enabling the gometalinter test as well as fixing any lint errors introduced during the period it was disabled

**Comment by GregHanson** [comment]
install fail example: https://circleci.com/gh/istio/istio/181030?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
+ install_gometalinter
+ echo 'Installing gometalinter ....'
Installing gometalinter ....
+ go get -u gopkg.in/alecthomas/gometalinter.v2
package gopkg.in/alecthomas/gometalinter.v2: unrecognized import path "gopkg.in/alecthomas/gometalinter.v2" (parse https://gopkg.in/alecthomas/gometalinter.v2?go-get=1: no go-import meta tags ())
Makefile:289: recipe for target 'lint' failed
```

**Comment by sebastienvas** [comment]
This got resolved on its own.
