### ISSUE TITLE
Document helm installation options

### ISSUE THREAD

**Issue by hyder** [istio/istio#8637]
**Describe the feature request**
There's a large and growing number of helm installation options as listed here: https://istio.io/docs/reference/config/installation-options/. Some are self-explanatory, however others are not and there impact are not well understood. Is it possible to document their purpose, possible values etc?

This is a documentation request.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by islinwb** [comment]
Part of them can be found in https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio#configuration.

**Comment by sdake** [comment]
@hyder please see https://github.com/istio/istio.github.io/issues/2566

This issue is tracked in the documentation repository, so closing here.

Cheers
-steve
