### ISSUE TITLE
Need to push book info consul image into istio docker repo

### ISSUE THREAD

**Issue by linsun** [istio/istio#864]
https://istio.io/docs/setup/install-consul.html assumes that docker images for book info are already built.  while users can use build-docker-services.sh to build it, it is best we also push these images to istio docker hub as each point release like the other book info docker images.

**Comment by linsun** [comment]
Did some investigation and consulted @sebastienvas -- this is unfortunately harder than I had thought before the flat build is in place.   we don't currently run bin/release script in istio repo which is where the consul images are built today.  defer this to 0.3 and push the images manually for now.

**Comment by ldemailly** [comment]
is this done/still needed?

**Comment by GregHanson** [comment]
this is addressed by using docker swarm, app and sidecar run in different containers but in the same pod.  Consul and Eureka samples have been updated to use this
