### ISSUE TITLE
security: should validate before deleting record from identity registry 

### ISSUE THREAD

**Issue by lichuqiang** [istio/istio#8649]
**Describe the bug**
In the serviceController for auth check, the controller just [remove the identity record from identity registry upon service deletion event](https://github.com/istio/istio/blob/master/security/pkg/registry/kube/service.go#L94):

```
func (c *ServiceController) serviceDeleted(obj interface{}) {
	svc := obj.(*v1.Service)
	svcAcct, ok := svc.ObjectMeta.Annotations[kube.KubeServiceAccountsOnVMAnnotation]
	if ok {
		err := c.reg.DeleteMapping(svcAcct, svcAcct)
		if err != nil {
			log.Errorf("cannot delete mapping %q to %q from registry: %s", svcAcct, svcAcct, err.Error())
		}
	}
}
```

What I'm worried about is if it possible that the `KubeServiceAccountsOnVMAnnotation` on different services can be of same value? If so, we should count the records  of  a same identity, and remove it only if all of its services have been deleted.
Or it's required that the annotation on different services must be of different values?

/cc @myidpt @incfly @diemtvu 

I can give it a fix if this is considered a bug.

**Comment by hzxuzhonghu** [comment]
I do not find how `c.reg` used.  Is it legacy code?
