### ISSUE TITLE
istio NewClient ever request localhost

### ISSUE THREAD

**Issue by zhaogaolong** [istio/istio#8656]
**Describe the bug**
NewClient  host is default addr  (http://localhost:8080)

**Expected behavior**
use kube config (not default kube path) init client ever request http://localhost:8080

**Version**
istio version : 1.0.0
k8s version: 1.10.4

I found the answer.   must use github.com/imdario/mergo@6633656539c1639d9d78127b7d47c622b5d7b6dc version is ok, 
but v0.3.6 version Will trigger this bug.

**Comment by ayj** [comment]
Good catch - this should already be fixed by https://github.com/istio/istio/pull/6987
