### ISSUE TITLE
Remove wildcard * restriction on the gateways

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#8658]
The following check does not allow wildcard host * 
https://github.com/istio/istio/blob/188baf0c93308b741087ca7556d4a77967777b69/pilot/pkg/model/validation.go#L1316
```
else if appliesToMesh && host == "*" {
			errs = appendErrors(errs, fmt.Errorf("wildcard host * is not allowed for virtual services bound to the mesh gateway"))
			allHostsValid = false
		}
```

Why do we have this restriction? Why `*.com` is OK and `*` is not? The use case is directing all the SNI traffic thru an egress gateway, see https://github.com/istio/istio.github.io/pull/1984/commits/095c4c1436049f7af93552fc86282783c2a4593b

**Comment by linsun** [comment]
@frankbu do you know why we don't support wildcard * on the gateways?  Or is this only for the egress gateway @vadimeisenbergibm ?   host: "*" is listed as an example here https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto#L74

**Comment by vadimeisenbergibm** [comment]
@rshriram Do you know why `*` hosts are not allowed?

```
else if appliesToMesh && host == "*" {
   errs = appendErrors(errs, fmt.Errorf("wildcard host * is not allowed for virtual services bound to the mesh gateway"))
```

**Comment by jdamour98** [comment]
Hello? No answer? I have 2 pods running behind my ingress gateway, and I want to route to a pod based purely on the uri prefix. Any reason this isn't allowed? @rshriram @linsun

**Comment by anyyyy** [comment]
Hello.What is the reason for restricting mesh gateways from using wildcards "*"? If I apply VirtualService to the created gateway now, then the policy rules in VirtualService will not take effect between services in the grid. . Is my understanding wrong, or if there are other solutions.

**Comment by hzxuzhonghu** [comment]
Wildcard host in vs is very risky. 

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/route_matching#route-matching

**Comment by ramaraochavali** [comment]
I did not understand why it is only risky for mesh gateway not for others?

**Comment by hzxuzhonghu** [comment]
I did not think about the difference, should take a look at the original context

**Comment by sreejesh-radhakrishnan-db** [comment]
any update please?  will host = "*" be allowed? or atleast host ="me.*"  ?
