### ISSUE TITLE
Can't get routing to work on BookInfo sample

### ISSUE THREAD

**Issue by SS-TT** [istio/istio#8660]
**Describe the bug**
Same bug as reported in #6240.
After applying `samples/bookinfo/networking/virtual-service-all-v1.yaml` I still can see rating stars in product page.

**Expected behavior**
Stars shouldn't be visible when using reviews v1.

**Steps to reproduce the bug**
Same as this [tutorial](https://istio.io/docs/tasks/traffic-management/request-routing/#apply-a-virtual-service)

**Version**
`istioctl version`:
> Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

`kubectl version`:
>Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-08-03T07:21:49Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-09-06T02:06:59Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Followed [this tutorial](https://istio.io/docs/setup/kubernetes/quick-start/)

**Environment**
`uname -a`:
> Linux machinename 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Cluster state**
My company's policy doesn't allow me to post the dump because it may contain sensitive data, if you need more data please let me know and I'll see what I can do.

**Comment by SS-TT** [comment]
I just tried and reapplied `virtual-service-all-v1.yaml` after that, still getting the same results.

**Comment by frankbu** [comment]
I suggest starting again from the beginning. Make sure that you follow ALL the instructions in `Before you begin -> Deploy the Bookinfo sample application` including this part:

https://istio.io/docs/examples/bookinfo/#apply-default-destination-rules

**Comment by yizhilong28** [comment]
check your Sidercar inject success

**Comment by yizhilong28** [comment]
**istioctl proxy-config listeners productpage-v1-xxx -n xxxx**

**Comment by yizhilong28** [comment]
if not resolve ，check the docker image pull success, 
`gcr.io/istio-release/proxy_init:1.0.0`
my problem is the image pull failed (because the gfw), but the pods run success.
actually sidecar injection not success.

**Comment by SS-TT** [comment]
@yizhilong28 thanks.
I found out that this may be related to #6085 because I'm having a lot of `gRPC config stream closed: 14, no healthy upstream` lines in my reviews' pods logs.
