### ISSUE TITLE
FR: Installation Validation Tool

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#8663]
**Describe the feature request**
Istio should provide a tool that can verify that a cluster has a "complete" install for a given release. This tool *could* be `istioctl`, a la `istioctl verify-install --version 1.0.2` or similar.

As discussed at the last Policies and Telemetry WG, there are many examples in the wild of partial installs of Istio leading to user confusion and operator pain. The partial installs can be caused by any number of issues, from Istio version upgrade to errors during `kubectl apply -f` executions to issues with helm itself.

Obviously, validation of install gets a bit tricky, as users/operators are free to customize config artifacts, etc., but I feel like for default / first-time users, as well as support use cases, there is a baseline validation that *should* be possible.

One possibility would be to generate metrics on Istio-related resources and then run queries to retrieve those values and compare against a baseline generated with each Istio release.

**Describe alternatives you've considered**
Absent providing an explicit tool, perhaps Galley could expose a metric/endpoint that indicates the version of Istio that *it believes* is installed. So, maybe `istio-galley:9093/versions/istio` could return a string like `istio-1.0.2-default` or `istio-1.0.2-dirty` (where when `-dirty` appears, additional lines detail the diff from a "default" install) or `unknown` (to indicate the install base does not match baseline for any known Istio version).

**Additional context**

/cc @geeknoid @ozevren @ayj @theganyo

**Comment by ozevren** [comment]
Galley doesn't have access to topology information. We might add in the future, strictly for config distribution purposes, but I don't think it is otherwise a reasonable place to make this deduction at this point.

An "Istio Controller" that performs actual Istio deployments might be a better place for this. In fact, the configuration of such a controller can be the place for deducing such things.

What was the most common cases? Given the information above, it looks like this is an "errors during installation being ignored by the user" problem more than anything else. (This is akin to program installation. If it fails, there should not be a reasonable expectation of correctness). Was there more to the issue?

**Comment by douglas-reid** [comment]
There was a long thread recently on the #general channel that was related (names, etc., removed here):

```
Hi All, a bit of a newbie question but I am running through the bookinfo example and I get the following error when trying to create the gateway and virtualservice, anyone else encountered this? unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

`kubectl get crds | wc -l` plz (edited)
if it is not a large number, like 45+, the crds are not installed

thanks, much appreciated, the number is 46

that sounds close
run `kubectl get crds | grep Gateway`

done, should it now work as i still see 46

that should output a 1 liner

$ kubectl get crd | grep gateway
gateways.networking.istio.io           1d

gateways.config.istio.io                                  30d
```

Notice the diff in namespaces for gateways config. That problem was resolved via: 

```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
```

I'm not sure that we can pin such issues exclusively on "users ignoring error messages". A simple helm install generates a *large* amount of information that flies by on the screen. That information is mostly meaningless to an average human.

And, even if that were the root cause, it would be nice to have a simple tool that is doing the kind of installation validation that was manually attempted here. Instead of saying "you should see something like 45 CRDs", we should be able to have a simple "run this tool. does it report errors?" support.

**Comment by ozevren** [comment]
Not denying the validity of the problem, but being able to easily figure out a failure at the point of failure (i.e. install/upgrade) seems to be a much more valuable thing to have than being able to tell after it happened. 

I am not aware of any, but I am wondering if there is some tooling we can already use to cheaply detect this for diagnostic purposes: Something that can read the current config state and diff against a representative Yaml perhaps? I don't think this is an Istio specific problem in this regard.

**Comment by ayj** [comment]
> ... Something that can read the current config state and diff against a representative Yaml perhaps? I don't think this is an Istio specific problem in this regard.

Diagnosing _and_ fixing the problem would also be useful. e.g. a reconciliation loop that ensures the actual Istio install matches the desired state.

**Comment by ozevren** [comment]
For the long term, an "Istio controller" is probably the right solution to this problem. As a bona fide Kubernetes controller, it would do reconciliation and avoid "half-install" problems.

For the short term though a cheap, diff-based solution might give us a very good mileage.

**Comment by sdake** [comment]
I tend to find the most common failure case in bug reports is probably a documentation issue in that evaluators often skip step #1 (apply CRDs) and jump right to step #2 (apply Istio yaml). 
 It probably doesn't help that sometimes people don't read the documentation at all :)

The challenge of a generic deployment validation tool is determining "what makes a deployment valid" - this is typically uniquely individual to each component, and requires component level understanding coupled with a holistic view of the components interactions with one another and their configuration.  This same challenge is what makes installation so challenging to even get right, as well as upgrade and reconfig.  Validation seems achievable; would like to see us having upgrade and reconfig working well in addition.

Cheers
-steve

**Comment by linsun** [comment]
I think this will be particularly useful as I know there are times I thought my istio env is good enough but it is not.   This can especially happen after i run helm upgrade a few times to switch among different configurations.

Is it possible to do this on the client side like istioctl?  Having Galley handle the server side is fine if it exists but there are scenarios where Galley isn't even installed, see https://istio.io/docs/setup/kubernetes/minimal-install/

**Comment by ozevren** [comment]
Here is a straw-man design for a tool:

1. Capture/retain the setup Yaml file (i.e. Helm/tiller based deployments will not be supported).
2. Tool parses the Yaml file and extract resources generically.
3. For each resource type, apply validation functions:
    1. Generically, for each resource, check that the resource exists or not.
    2. If the ```Kind``` of the resource is recognized, then run an appropriate ```Kind``` specific code for validation. As an example, if Kind == Deployment, ensure that the deployment has completed successfully.
    3. In addition to 1-1 validation, allow set validation rules (e.g. for ```Kind``` == Deployment, you cannot have additional deployments in the same namespace). These can be pretty generic.
4. Add point-wise specific checks as needed through custom code, as we identify gaps.

Does this sound like a reasonable approach to a tool?

**Comment by douglas-reid** [comment]
@ozevren that sounds reasonable to me. and likely to provide some useful debug bits (diffs between versions), etc. a first pass that just did simple counts might also be enough to start.

**Comment by linsun** [comment]
@ozevren while validating yaml is helpful, I think it is more valuable to validate against a running env like k8s to see if istio is installed properly, for a given feature or profile.  In my case, I always start with recommended istio yaml or helm chart (which is golden and tested by our tests framework) but still ends up with non functional istio env.

**Comment by ozevren** [comment]
This is about validating against installed Istio.

The tool would diff the yaml on-hand against the state from API Server.

**Comment by linsun** [comment]
Ok cool, I missed that.   would you propose to do this within istioctl against a running k8s?

**Comment by ozevren** [comment]
istioctl has been the default place to put things in, so it probably makes sense to put the command-line portion there.

The core logic should be a library though. It would be useful for tests as well.

**Comment by linsun** [comment]
cc @irisdingbj who expressed interest in working on this.

**Comment by irisdingbj** [comment]
Will add command like "istioctl install-validate -f istio-demo.yaml" to validate the status from api server against the install file user used.

**Comment by irisdingbj** [comment]
@linsun @ozevren @ayj @douglas-reid Does above command work? If so I will begin to implement it.

**Comment by douglas-reid** [comment]
It sounds reasonable to me. I might just call the command `validate` (and maybe have a subcommand of `install`) for simplicity, but otherwise that seems reasonable to me.

**Comment by linsun** [comment]
+1 thank you @irisdingbj !  for -f, it would be great if it can take a url or local file.
`istioctl validate -f xx.yaml` works for me.

**Comment by linsun** [comment]
one thing is our profiles today assume CRDs are installed too, and CRDs could change among releases, so it would be useful to have a -v flat to pass in versions of istio.

**Comment by ayj** [comment]
`istioctl validate` [already exists](https://github.com/istio/istio/blob/12fbc34ea14bf8a07066508508ce66644979ba07/istioctl/pkg/validate/validate.go#L167-L169.) for validating user authored configuration. Maybe `istioctl validate-install` or `istioctl check-install`? Also, we may want to put this under `istioctl experimental` while we experiment with the requirements/implementation.

**Comment by ozevren** [comment]
Agreed with @ayj. Please put the command-line under experimental, and let's not use validate.
How about verify-install?

**Comment by linsun** [comment]
ok if validate already exist (I don't see it in my 1.0.2 istioctl), i'd agree not use it.

Now, do we expect this cmd to just validate install?  Would it be convenient for the user to also print out control plane status??  It is like give me my istio status which install is a key piece of.

**Comment by linsun** [comment]
how about `istioctl mesh-info`?

**Comment by ozevren** [comment]
Can we keep it scoped for the time being? We can add new features, or make
it part of a bigger feature as we make progress.

**Comment by douglas-reid** [comment]
> one thing is our profiles today assume CRDs are installed too, and CRDs could change among releases, so it would be useful to have a -v flat to pass in versions of istio.

Yeah, this _might_ be easier/better UX: `istioctl experimental verify-install -v 1.0.2-demo` (in case you don't have the exact generated file in front of you... not sure exactly what that case would be, but...).

**Comment by ozevren** [comment]
I don't think we should try to do this. The tool is meant to be tactical
(i.e. given a yaml file, see if it is installed correctly). This is a
simple problem with a straightforward implementation, and is a simple
diagnostic utility.

Given that with Helm, we can specify numerous options to generate a huge
variety of Yaml files, I don't think we can exhaustively and meaningfully
say what "version xxx Istio" looks like.

IMHO, the actual problem should be fixed by a Istio application/add-on
controller that can continuously reconcile the state of Istio. That should
obviate the need for such a tool.

**Comment by linsun** [comment]
I agree, our install is highly customization so it makes sense for user to feed us the yaml.

**Comment by irisdingbj** [comment]
@ozevren @linsun  @ayj  @douglas-reid  The initial implementation is ready at https://github.com/istio/istio/pull/9468, Please let me know your comments. Many Thanks~

**Comment by irisdingbj** [comment]
This has already been delivered in https://github.com/istio/istio/pull/9628
