### ISSUE TITLE
istio-tracing pod crashing 

### ISSUE THREAD

**Issue by aghag10** [istio/istio#8670]
**Describe the bug**
istio-tracing crashing and the jaeger container in the pod is getting restarted

istio-system   istio-tracing-ff94688bb-wwrlq                        0/1       Running       5          4m

kubectl describe pod istio-tracing-ff94688bb-wwrlq -n istio-system

 Normal   Killing                6m (x2 over 7m)  kubelet, sc**  Killing container with id docker://jaeger:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy              6m (x7 over 8m)  kubelet, sc**  Readiness probe failed: Get http://172.25.0.11:16686/: dial tcp 172.25.0.11:16686: getsockopt: connection refused
  Warning  Unhealthy              6m (x6 over 8m)  kubelet, sc**  Liveness probe failed: Get http://172.25.0.11:16686/: dial tcp 172.25.0.11:16686: getsockopt: connection refused
  Warning  BackOff                3m               kubelet, sc**  Back-off restarting failed container

**Expected behavior**
READy status should be 1/1

**Steps to reproduce the bug**
kubectl apply -f install/kubernetes/istio-demo.yaml

**Version**
 istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead",

**Installation**
kubectl apply -f install/kubernetes/istio-demo.yaml

The logs suggest that the http query server was successfully started on port 16686-- 

kubectl logs istio-tracing-ff94688bb-wwrlq -c jaeger -n istio-system

{"level":"info","ts":1536792244.9043777,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1536792244.9059174,"caller":"tchannel/builder.go:89","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1536792244.9060128,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"127.0.0.1:14267"}
{"level":"info","ts":1536792244.9074311,"caller":"standalone/main.go:179","msg":"Starting agent"}
{"level":"info","ts":1536792244.9082475,"caller":"standalone/main.go:219","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1536792244.9085205,"caller":"standalone/main.go:229","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1536792244.954611,"caller":"standalone/main.go:249","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
{"level":"info","ts":1536792245.908471,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1536792245.90864,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"127.0.0.1:14267"}
{"level":"info","ts":1536792245.9093337,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"}
{"level":"info","ts":1536792274.965503,"caller":"standalone/main.go:290","msg":"Registering metrics handler with jaeger-query HTTP server","route":"/metrics"}
{"level":"info","ts":1536792274.9657593,"caller":"standalone/main.go:296","msg":"Starting jaeger-query HTTP server","port":16686}
{"level":"info","ts":1536792274.965845,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"} ---------> http query server was correctly started and became READY

However, I'm not able to do a curl call to the health probe api - 
curl http://172.25.0.11:16686
curl: (7) Failed to connect to 172.25.0.11 port 16686: Connection refused

Is the container being killed because of failed liveness probes even before the http query server is started?

**Comment by moeyui1** [comment]
Does it work on isio-1.0.0?

**Comment by aditivghag** [comment]
I haven't tried istio-1.0 yet. I think the issue may have something do with the fact that the istio-demo.yaml from the official repo is deploying both Jaeger and Zipkin services. 

If I delete the zipkin service, then the istio-tracing is able to run successfully, but the Jaeger UI still doesn't any services/traces. 

Looking at the istio-demo manifest file, the tracing url is provided as -

    # Zipkin trace collector
      zipkinAddress: zipkin.istio-system:9411

So we need the zipkin service? 

Can someone please point me to the correct manifest file to use? Thanks!

**Comment by aghag10** [comment]
I used a workaround for now to remove the liveness probes from yaml file.

**Comment by lxv458** [comment]
> I used a workaround for now to remove the liveness probes from yaml file.

hi, how do you solve this problem, I met the same problem with you.
