### ISSUE TITLE
Unable to get egressgateway working in seperate namespace

### ISSUE THREAD

**Issue by wmuizelaar** [istio/istio#8685]
**Describe the bug**
I would like to spin up the egressgateway in a seperate (non istio-system) namespace, so we can make sure with egress networkpolicies that all traffic leaving the cluster is going through the egressgateway. I can't get this to work at the moment.

**Expected behavior**
I would expect the egressgateway to be working.

**Steps to reproduce the bug**
Install istio (see installation step), install egress gateway seperately, follow the examples from https://istio.io/docs/examples/advanced-egress/egress-gateway/
In those examples, where references to the gateway in `istio-system` were, they ware replaced with `istio-egressgateway`.

**Version**
```
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.1", GitCommit:"7221ffe8776f399448d61b4dc9edb5c69232aece", GitTreeState:"clean", BuildDate:"2018-08-29T23:11:12Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio was installed with `helm template` from the istio-1.0.2.tar.gz, using this script: 
https://gist.github.com/wmuizelaar/d946880f0e2c9af06a6d89ad87b0bb44
The yaml that was generated from the `helm template` command is published here:
https://gist.github.com/wmuizelaar/745611bf93f3cfdd37e218b4273e7dd9

Afterwards, the egress gateway was installed using this script:
https://gist.github.com/wmuizelaar/61e4dccc59c472ca1a955a1e6f9276d5
The yaml from that specific `helm template` command is published here:
https://gist.github.com/wmuizelaar/1fa3ddba75d50b81a7f614481790e21f

**Environment**
We are running on GKE, with regional / private clusters, and pod security policies enabled. 

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2378699/istio-dump.tar.gz)

**Comment by wmuizelaar** [comment]
I tested a bit more - and finally found out that Istio was just working fine, but networkpolicies from kubernetes were blocking traffic. When I solved that problem, the issue was gone. So I'm gonna close this.

**Comment by mabushey** [comment]
@wmuizelaar What specifically did you do? I tried this:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  ingress:
  - {}
```
But it didn't fix anything. My issue is ingress however (yours was egress).

**Comment by wmuizelaar** [comment]
For me the networkpolicy that you copy-pasted fixed it. For ingress, I had no troubles at all to install it in a seperate namespace

**Comment by mabushey** [comment]
Don't know. I can route to containers in default and istio-system (I can route to `host: grafana.istio-system.svc.cluster.local`), but if I have containers in any other namespace I can not route to them.

**Comment by mabushey** [comment]
I must have had multiple problems, I have this working now, not really sure why or what specifically fixed this.
