### ISSUE TITLE
Enable linting of import groups

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#8689]
**Describe the feature request**
As a follow-up to PR #8687, it would be good to have linting for grouped imports. [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) organizes imports by groups as described in [this document](https://github.com/golang/go/wiki/CodeReviewComments#imports). This could be added to the commit process, or we could explictly check for such formatting errors via the linter.

**Comment by kyessenov** [comment]
Done already with golangci-lint.
