### ISSUE TITLE
istio tracing Jaeger UI not showing any services/traces

### ISSUE THREAD

**Issue by aghag10** [istio/istio#8709]
**Describe the bug**
Jaeger UI is not showing any services/traces

**Expected behavior**
Sample application bookinfo/sock-shop microservices should show up in the UI. 

**Steps to reproduce the bug**
Neither of the application services show up. 
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)
istioctl kube-inject -f complete-demo.yaml | kubectl apply -f -

**Version**
istioctl version
Version: 1.0.2 (Same issue with 1.2 as well)
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0"

**Installation**
https://istio.io/docs/setup/kubernetes/quick-start/

**Cluster state**
kubectl get all -n istio-system

NAME                             READY     STATUS      RESTARTS   AGE
istio-citadel-5b956fdf54-8wcng   1/1       Running     0          46m
istio-cleanup-secrets-kxl4t      0/1       Completed   0          46m
istio-pilot-6cd95f9cc4-9tnx6     2/2       Running     0          46m
istio-tracing-76b74dd87c-z9fgb   1/1       Running     0          46m

NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
istio-citadel      ClusterIP   10.97.73.168     <none>        8060/TCP,9093/TCP                       46m
istio-pilot        ClusterIP   10.97.206.13     <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP   46m
jaeger-agent       ClusterIP   None             <none>        5775/UDP,6831/UDP,6832/UDP              46m
jaeger-collector   ClusterIP   10.101.217.208   <none>        14267/TCP,14268/TCP                     46m
jaeger-query       ClusterIP   10.101.50.90     <none>        16686/TCP                               46m
tracing            ClusterIP   10.111.231.215   <none>        80/TCP                                  46m
zipkin             ClusterIP   10.109.143.177   <none>        9411/TCP                                46m

NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
istio-citadel   1         1         1            1           46m
istio-pilot     1         1         1            1           46m
istio-tracing   1         1         1            1           46m

NAME                       DESIRED   CURRENT   READY     AGE
istio-citadel-5b956fdf54   1         1         1         46m
istio-pilot-6cd95f9cc4     1         1         1         46m
istio-tracing-76b74dd87c   1         1         1         46m

NAME                    DESIRED   SUCCESSFUL   AGE
istio-cleanup-secrets   1         1            46m

kubectl get ep -n istio-system
NAME               ENDPOINTS                                                         AGE
istio-citadel      172.25.0.13:9093,172.25.0.13:8060                                 48m
istio-pilot        172.25.0.11:9093,172.25.0.11:15010,172.25.0.11:8080 + 1 more...   48m
jaeger-agent       172.25.0.12:6831,172.25.0.12:5775,172.25.0.12:6832                48m
jaeger-collector   172.25.0.12:14267,172.25.0.12:14268                               48m
jaeger-query       172.25.0.12:16686                                                 48m
tracing            172.25.0.12:16686                                                 48m
zipkin             172.25.0.12:9411                                                  48m

Any pointers?

**Comment by spekr** [comment]
Did you find a sollution @aghag10 ? We have a similar issue.

**Comment by objectiser** [comment]
@spekr Have you checked out https://istio.io/help/faq/distributed-tracing/#no-tracing ?

**Comment by spekr** [comment]
@objectiser yes we have. Unfortunately this did not help. Only service that's being traced is the jaeger-query service 😞

**Comment by objectiser** [comment]
@spekr Can you provide details of the Istio version, environment, etc? Are you trying the bookinfo example or your own - if you own does it work with bookinfo?

**Comment by spekr** [comment]
- Istio version 1.1 installed with helm. 
- pilot value.yaml has "traceSampling: 100.0"
- Tracing is enabled. 
- Our nodes are on 1.12.5-gke.10 

I use a different application, but I have tried the bookinfo example as well. This does not create tracing either. 

Our setup is a little bit different from the vanilla istio install. We have the prometheus / grafana / jaeger applications outside of the istio-system namespace (non-default) with side-car auto-inject enabled. The services are being exposed with a VirtualService. 

I suspect Pilot can not push the notifications to Jaeger as the envoy expects mtls. Could this be the problem? And if so, is there a way to work around this?

**Comment by objectiser** [comment]
Does your Jaeger deployment have sidecar injection disabled? e.g. https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/deployment-jaeger.yaml#L22

**Comment by spekr** [comment]
No, we have it enabled (for it to be accessible through virtualservices).

**Comment by spekr** [comment]
I removed the sidecar from the jaeger deployment. Still no result, so I think we can rule out the sidecar as the problem.

**Comment by objectiser** [comment]
Did you update the helm setting for `global.tracer.zipkin.address` to point to the new namespace?

**Comment by spekr** [comment]
@objectiser yes. Namespace is 'operations' and the below is what I found in the ingress-deployment yaml, so I think it should be good. (Double checked the zipkin service, port 9411 is also correct).

  - --zipkinAddress
  - zipkin.operations.svc.cluster.local:9411

**Comment by spekr** [comment]
@objectiser Ok, now I am getting some results. The problem was a combination of the zipkinAddress (typo) and the sidecar. WIthout sidecar and with the right zipkinAddress it seems to be working. So it seems the only option is to keep Jaeger in the istio-system namespace (with auto-injection disabled). Or do you know of a way to make an exception for the pilot to access the service?

**Comment by objectiser** [comment]
@spekr Sorry, was confused by your last comment - you say it is now working in a separate namespace without the sidecar, but then say only option is to run Jaeger in the istio-system namespace?

**Comment by objectiser** [comment]
If you are installing Jaeger in a separate namespace - have you also created the `zipkin` service, e.g. https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L12-L30 ?

This is used to provide a standard service for reporting zipkin span data to any selected tracing backend. However if you don't have this service, and don't want it to be defined, then other option would be to use the `jaeger-collector` service but still with the zipkin port `9411`.

**Comment by spekr** [comment]
Yeah you're right, that does not make any sense :-P. What I mean is this: we've taken Jaeger from the istio-system namespace so that it can have a sidecar injected. We want to expose the service through a virtualservice instead of the kubernetes-ingress. (Trying to keep it clean.). So there is no reason for us to keep it in a seperate namespace (if it only works without sidecar).

We have the zipkin service, but it points to the istio-tracing pod (jaeger). If the pod has a sidecar, the zipkin service can not be accessed by pods without sidecar. 

I am now trying to disable mtls for this specific port with Policy / DestinationRule. If this works I will let you know.

**Comment by spekr** [comment]
Ok, fixed it with the following addition to the helm-chart:

```
{{ if eq .Values.provider "jaeger" }}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "zipkin-mtls-exception"
  namespace: {{ .Values.namespace }}
spec:
  targets:
    - name: zipkin
      ports:
        - number: 9411
  peers:
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "zipkin-mtls-exception"
  namespace: {{ .Values.namespace }}
spec:
  host: zipkin.operations.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    portLevelSettings:
      - port:
          number: 9411
        tls:
          mode: DISABLE
{{ end }}
```

Thanks for thinking along @objectiser!

**Comment by ngocketit** [comment]
I tried the Bookinfo example with Istio 1.7 and there are only traces for `istio-ingressgateway` and `jaeger-query`. Is there a way to debug tracing (e.g, whether traces have been sent or not)?

**Comment by BlueMaverick** [comment]
> fined, then othe

Need some guidance here for same issue.

I deployed jaeger without zipkin and my istiod tracing address is pointed to jaeger-collector service at port 14268  which is the http port for collector service. It is not receiving any tracing data from services except jaeger-query similar to original issue mentioned above. 

Why do you say to still point it to port 9411 with jaeger collector service when this port does not exist in collector service or deployment? Thanks in advance.

**Comment by BlueMaverick** [comment]
@objectiser Hi, Please reply to my comment above. Thanks

**Comment by objectiser** [comment]
@BlueMaverick I haven't worked on istio or Jaeger for over a year so not sure of any changes since last used - but from my prior knowledge Istio only generates zipkin format data - and therefore if you want Jaeger to receive it, you will need to configure Istio to point to the zipkin port, and configure the Jaeger collector to provide the zipkin port, e.g. ` --collector.zipkin.host-port=....` - see https://www.jaegertracing.io/docs/1.34/cli/#jaeger-collector

**Comment by BlueMaverick** [comment]
Thanks. It makes sense now. 
I have upgraded my jaeger helm charts with `--set collector.service.zipkin.port:9411` and I can see tracing data in jaeger now.

### Sharing complete solution that worked for me:

1. jaeger installation in independent namespace (with ingress reverse proxy ):
`helm upgrade --install jaeger jaegertracing/jaeger --set fullnameOverride=jaeger  --set query.basePath='/jaeger' --set collector.service.zipkin.port=9411  -n mynamespace`
2. Upgrade istiod charts to send tracing data to jaeger collector service:
`--set values.global.tracer.zipkin.address=jaeger-collector.mynamespace.svc.cluster.local:9411`
Step 2 can also be achieved by manually updating configmap istio in istio-system namespace and restarting istiod pod.
3. Point by Domain context path /jaeger to jaeger-query service:
` - match:
    - uri:
        prefix: /jaeger
    name: jaeger
    route:
    - destination:
        host: jaeger-query.mynamespace.svc.cluster.local
        port:
          number: 80`
