### ISSUE TITLE
Hostname match rules doesn't seems right

### ISSUE THREAD

**Issue by Lion-Wei** [istio/istio#8713]
**Describe the bug**
As test case `TestHostnameMatches` mentioned, long wildcard hosename should match short host, like 
`*.foo.bar.baz` can match `baz`, 
Is this true? Seems weird.

https://github.com/istio/istio/blob/master/pilot/pkg/model/service_test.go#L253-L254

**Version**
Master

**Comment by rshriram** [comment]
*.foo.bar.baz should match *.baz..
e.g., a.foo.bar.baz will match *.baz and *.foo.bar.baz

**Comment by Lion-Wei** [comment]
Thanks, @rshriram , I think if we simply understand it as wildcard match, then *.foo.bar.baz should not match *.baz, but I got it.
