### ISSUE TITLE
Requests failing for 60-100 seconds when one of the cluster's machines is terminated

### ISSUE THREAD

**Issue by andriosr** [istio/istio#8718]
Similar to what happens at #8243, when one of the nodes in a k8s cluster goes down (terminated - not gracefully draining pods as in #8243) , even using 2 or 3 replicas of control plane pods, distributed to different nodes using [PodAntiAffinity](https://github.com/istio/istio/pull/8480), the requests would fail for about 60-100 seconds. Getting the exact same logs and response code.

**Expected behavior**
The service mesh should not become unavailable in a scenario where a machine in a cluster goes down, which is pretty common at scale.

**Steps to reproduce the bug**
Terminate a machine in a k8s cluster running Istio 

**Version**
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Istio 1.0.0
```
**Installation**
Kubernetes - Helm

**Environment**
AWS, Kops/Debian

**Comment by Caspervw** [comment]
Same setup (multiple control plane replicas with PodAntiAffinity), same result. Our cluster horizontally scales under load (GKE) and fails for a couple of minutes per week.
