### ISSUE TITLE
Latest Ansible Installer was not included Istio 1.0.2

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#8730]
**Describe the bug**
- Latest ansible installer was not included on Istio 1.0.2 release, which means if we follow the documentation on https://istio.io/docs/setup/kubernetes/ansible-install/, on section:

> Operator installs Istio on OpenShift with settings other than the default:
` ansible-playbook main.yml -e '{"istio": {"auth": true, "delete_resources": true}}'` 

it will delete after installing, which is reported as a fixed bug (https://github.com/istio/istio/issues/7735).

Also, some additions, like exporting routes on openshift for grafana are not there as well.

Can we include latest ansible installer on next Istio release?

Best Regards,
Guilherme Baufaker Rêgo

cc @sdake @linsun @gyliu513 @geoand

**Comment by gyliu513** [comment]
@gbaufake I'm +1 on this. Please go-ahead for a PR for this, thanks.

**Comment by sdake** [comment]
@gbaufake works for me.  please cherrypick the PRs that are relevant to the release-1.0 branch.  Once cherrypicked, add the cherrypick PRs to the Istio-1.0.3 tracker.   Ultimately T&R and the TOC have final oversight over backports.

cheers
-steve

**Comment by sdake** [comment]
@gbaufake I haven't seen any PRs for 1.0 series hit the repo related to Ansible.  I wanted to set expectations that I am hearing we are about 1 week out from 1.0.3 release, and this may be the last 1.0 series release for Istio.

Cheers
-steve

**Comment by gbaufake** [comment]
Fixed by #8787
