### ISSUE TITLE
Remove Citadel dependency from Galley validation webhook

### ISSUE THREAD

**Issue by ayj** [istio/istio#8736]
The Galley and Sidecar injector webhooks requires a key/certificate for simple TLS with the kube-apiserver. We currently rely on Citadel to provision this key/certificate. The Citadel root ca cert is provided to kube-apiserver in the k8s validatingwebhookconfiguration. The key/certificate are provided to galley and the sidecar injector via k8s secret. 

We should reconsider this approach given the following points:

1) Citadel is moving to a model where it key/certs are distributed  with [SecretDiscoveryService (SDS)](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/discovery/v2/sds.proto). Envoy will get key/certs from a node local agent (i.e. via SDS over UDS) rather than from a local file (via k8s secret). 

2) Citadel generates certs with Spiffie identity. Certs for k8s webhooks must have DNS names. Special cases exist in Citadel to generate certs w/DNS names for Galley and Sidecar injector services. This is inflexible given users wish to deploy webhooks with alternative names.

3) In the not too distant future (Istio ~1.2?), Galley will be required as _the_ integration point for Istio on Kubernetes. Pilot/Mixer will receive configuration from Galley via MCP. It's desirable to remove Galley's hard dependency on Citadel for minimal Istio installations, e.g. Pilot only. For example, it should be possible, though _not recommended_, to install Istio without Citadel on Kubernetes. The control plane will not be secured via mTLS (e.g. Galley to Pilot, Pilot to Envoy) but the validation webhook should still be operational. Each webhook should be responsible for cert rotation.

Options:

1) Galley and Sidecar injector webhooks optionally generate self-signed certificates, use the key/cert in their local TLS server configuration, and set the cert as the caBundle in their k8s {mutating,validating}webhookconfiguration. To handle replicated webhook instances, this key/cert should be stored as a k8s secret. Upon startup, new webhook replicas check for the existence of the key/cert, use it if present, otherwise fallback to the self-signed cert path.

2) Write an [operator](https://coreos.com/operators/) to handle cert provisioning and rotation. No changes is required to the existing webhooks. A new controller is required to generate key/cert material, have it signed, and store it as a k8s secret. Certs could be self-signed or use the [k8s CSR API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request-object-to-send-to-the-kubernetes-api).

**Comment by ayj** [comment]
cc @myidpt @wattli

**Comment by clyang82** [comment]
Is anybody working on this one? if no, I would like to pick it. 
/assign @clyang82

**Comment by justinburke** [comment]
With Citadel, one of the reasons for wanting to use SDS was to remove sensitive key material from k8s secrets (where access to those secrets is often too broad). Seems like we'd have the same concerns here for at least the Galley component, or is that not the case?

/cc @wattli @myidpt

**Comment by ayj** [comment]
I don't think its necessarily an either/or scenario. Galley requires key material for two purposes: service-to-service (e.g. Pilot-to-Galley) and k8s webhooks (kube apiserver-to-Galley). I think we want to eventually use SDS for the former case and require Citadel. The latter case is a bit different when we consider minimal Istio installs (w/o Citadel).

**Comment by ozevren** [comment]
Splitting this into two issues for better tracking The Sidecar Injection bug is tracked separately here:
https://github.com/istio/istio/issues/11995

**Comment by costinm** [comment]
The Pilot-Galley connection will soon switch to using the Sidecar (and SDS where available) with normal SPIFEE certs, and is not a concern. This is only about the webhooks, which need self-signed certificates that they place in the apiserver config so apiserver->webhook is secured. 

They do need storage for the private key and cert in a secret - because you may have multiple replicas.

I believe @rshriram proposed a much simpler solution - the secret and the certs can be generated at install time, Helm( and operator, which uses helm templates) can generate self-signed certs and simplify the config.  I guess that's back to the original implementation, which used a script to setup the webhook.
This would also not only decouple webhooks from citadel, but allow users to plugin whatever certs they are required to.

**Comment by ozevren** [comment]
Will cert rotation be a concern in that approach?

**Comment by ozevren** [comment]
Adding @lei-tang as he will be working on this, per discussion with @myidpt.

**Comment by ozevren** [comment]
Moving this to v1.4

**Comment by lei-tang** [comment]
This issue is tracked in https://github.com/istio/istio/issues/17061.

**Comment by esnible** [comment]
@ayj Is this issue still valid in the Istiod world?

**Comment by ayj** [comment]
No
