### ISSUE TITLE
 More accurate definition for istio with distributed tracing

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#8742]
**Describe the feature request**
In istio.io ,istio is defined as "Istio makes it easy to create a network of deployed services with load balancing, service-to-service authentication, monitoring, and more, **without any changes in service code**", but actually users should propagate some headers in code for distributed tracing.

**Describe alternatives you've considered**
Update comments to tell users requiring very little code change.

**Comment by x15zhang** [comment]
@linsun @idouba @geeknoid

**Comment by linsun** [comment]
FYI - we have this already changed in 1.1:  https://preliminary.istio.io/docs/concepts/what-is-istio/#why-use-istio

**Comment by idouba** [comment]
@linsun Great.

**Comment by x15zhang** [comment]
@linsun  Thanks for clarifying.
