### ISSUE TITLE
Remove port name from route.Destination in the API

### ISSUE THREAD

**Issue by Lion-Wei** [istio/istio#8754]
**Describe the feature request**

Since we already deprecated `PortSelector_Name`, the use of port name will be ignored, I think we should better remove this filed from route.Destination in the API, in case user use this foeld, but can't get what they needed.

The work should include: 

- [ ] Remove or refactor `PortSelector_Name` related logic in istio.
- [ ] Remove `PortSelector_Number` from route.Destination in istio.io/api.
- [ ] Update vendor.

**Describe alternatives you've considered**
{{ Describe alternative solutions or workarounds you've considered. }}

**Additional context**
{{ Add any other context about the feature request here }}

**Comment by rshriram** [comment]
I dont mind.. if someone does the PR

**Comment by linsun** [comment]
Agreed this would be good to have.   @vadimeisenbergibm or @GregHanson could one of you help with the WI?

**Comment by lmmarsano** [comment]
Naming ports is standard behavior in the core API ([pod port](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports) & [ingress backend](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressBackend)).
It's more self-documenting & provides better flexibility, which [k8s documentation appears to recommend](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service):
> Port definitions in Pods have names, and you can reference these names in the `targetPort` attribute of a Service. This works even if there is a mixture of Pods in the Service using a single configured name, with the same network protocol available via different port numbers. This offers a lot of flexibility for deploying and evolving your Services.

How am I supposed to refer to my named ports with possibly mixed port numbers?
