### ISSUE TITLE
Applying for Istio membership

### ISSUE THREAD

**Issue by stewart-yu** [istio/istio#8762]
I am creating this issue for the sake of applying for Istio membership.

I have Subscribed to [istio-dev@googlegroups.com](istio-dev@googlegroups.com)

I am currently working on some work about `CI`, such as `codecov`、`linter` bash secript and so on. 
especially, add `check_spelling.sh` secript in CI, and fix `codecov error` in CI.
Following is the list of PRs got merged:

#8174 
#8206 
#8304 
#8514 
#8567 
#8570 
#8680 
#8706 
#8711

PRs in flight:

#8737 
#8752 
#8758 

Issues involved in:

#8508 
#8568 

/cc @GregHanson  @sdake @ayj @linsun  for sponsors
emmm...., i'm not sure whether  suitable to commit a issuse in here to apply member now, If i'm wrong, please correct me.

**Comment by linsun** [comment]
FYI - this is the new process:  https://github.com/istio/community/pull/76

**Comment by stewart-yu** [comment]
In favor of https://github.com/istio/community/issues/78, close it now
