### ISSUE TITLE
Provide way for users to change Mixer config default namespace

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#878]
We should provide an easy way to update the default config namespace of Mixer for users that don't want to use `istio-config-default`.

This is blocked by changes in https://github.com/istio/istio/pull/866.

**Comment by linsun** [comment]
@douglas-reid could this be closed now with #866 merged?

**Comment by ldemailly** [comment]
we could recycle this issue for "provide a way to label config as global vs namespace" but there is https://github.com/istio/istio/issues/632 for that so I'm closing this one
