### ISSUE TITLE
merge bot apparently did not rebase when running tests before merge

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#8783]
**Describe the bug**
The merge bot merged a PR that failed required test on master.

**Expected behavior**
The merge bot should only merge a PR when it passes all required tests by rebasing it against the latest master before merging.

**Steps to reproduce the bug**
I think I have seen this before but the latest example is #8606.

**Version**
Master

**Installation**
N/A

**Environment**
N/A

**Cluster state**
N/A

**Comment by sebastienvas** [comment]
From your example, all the required checks are passing. Can you give more information of which required checks are failing, pointing to some logs. Note also that Tide (The merge bot) does not re-run required checks on circle ci.

**Comment by yangminzhu** [comment]
> Note also that Tide (The merge bot) does not re-run required checks on circle ci.

Could this be the reason? `ci/circleci: test` is the required unit tests but not re-run by Tide. The `prow/istio-unit-tests.sh` is not required so it's also not re-run by Tide?

**Comment by hklai** [comment]
Tide does not rerun circleci tests. That is known and expected until someone implements a circle controller.

Prow tests should be able to catch something like this however.

**Comment by yangminzhu** [comment]
@hklai 
Does Tide rerun all prow tests r only those required prow tests before merge? If the latter, we might need to change `prow/istio-unit-tests.sh` to required.

**Comment by hklai** [comment]
Yes I think it should have been required, It was made optional when it was flaky, I think. 

Let me send a PR

**Comment by sebastienvas** [comment]
Tide will probably restart all tests in Prow, but only merge when all required tests are complete. So it is possible that an optional test might be pending when we merge.

**Comment by hklai** [comment]
Prow merges the current head with the PR before running tests. You can check the clone log in the artifacts.
E.g. http://gcsweb.k8s.io/gcs/istio-prow/pr-logs/pull/istio_istio/11423/istio-unit-tests/20219/
