### ISSUE TITLE
Be able to disable vulnerable TLS versions in Ingress Gateway

### ISSUE THREAD

**Issue by ldounis** [istio/istio#8804]
**Describe the feature request**
Istio admins should be able to set a minimum TLS version of TLSv1_2 for the Istio ingressgateway proxy.

Here is the respective envoy configuration:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html?highlight=common_tls_context#envoy-api-msg-auth-tlsparameters

Please add a respective field in Gateway or any other appropriate entity.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ssmogos** [comment]
Would those changes include allowing to specify the cipher suites?

**Comment by ldounis** [comment]
The request is to add the minimum TLS protocol field, which will cover most cases.
If we broaden the request we should add the following three fields:

  "tls_minimum_protocol_version": "...",
  "tls_maximum_protocol_version": "...",
  "cipher_suites": [],

Implementation should be straightforward, 
1. update gateway proto in istio/api repo -> networking/v1alpha3/gateway.proto
2. update pilot to use new fields in istio/istio repo ->  pilot/pkg/networking/core/v1alpha3/gateway.go

**Comment by sdake** [comment]
A related issue (cipher suite restriction):
https://github.com/istio/istio/issues/8769

**Comment by marshallford** [comment]
To broaden the conversation quite a bit: If this TLS version feature is added, is it reasonable to expect other HTTP server options to be approved/added as well? One of my reservations about moving to Istio from something like the [NGINX Ingress Controller](https://github.com/nginxinc/kubernetes-ingress) is the lack of "traditional web server" options. I'm not suggesting full feature parity with something like Nginx, but a lot of these [customizations](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization) could be must haves if Istio is on the edge of your network. I'm interesting in hearing from a maintainer about the larger scope and roadmap of the Istio Gateway. Thank you for all of your work.
