### ISSUE TITLE
Improvements to "Mixer out of process adapter walkthrough" document

### ISSUE THREAD

**Issue by DanRoscigno** [istio/istio#8806]
**Describe the feature request**
{{ A couple of doc changes to make the mixer out of process adapter walkthrough easier }}

**Describe alternatives you've considered**
{{ None, although I did speak to @mandarjog and he suggested that I open an issue and then make the edits. }}

**Additional context**
{{ These are suggestions for the [walkthrough](https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough):

Changes to Out of Process Adapter [Walkthrough](https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough)

### Before you start

Docker, Kubernetes, and Go are required for this walkthrough, if you need details see the [Dev Guide](https://github.com/istio/istio/wiki/Dev-Guide).

Start Docker with Kubernetes enabled on local machine

Change:

"Download a local copy of the Mixer repo" as the rest of the doc expects the repo to be downloaded to `$GOPATH/src/istio.io/`

```
mkdir -p $GOPATH/src/istio.io/ && \
cd $GOPATH/src/istio.io/  && \
git clone https://github.com/istio/istio
```

In the section **Now let's start the gRPC adapter. On a new terminal run**

change `go run cmd/main.go`

to

```
export ISTIO=$GOPATH/src/istio.io
export MIXER_REPO=$GOPATH/src/istio.io/istio/mixer
cd $MIXER_REPO/adapter/mygrpcadapter
go run cmd/main.go
```

In the section **On a new terminal export the listener address in a ADDRESS variable.** change:

`export ADDRESS=[::]:38355`

to

```
export ISTIO=$GOPATH/src/istio.io
export MIXER_REPO=$GOPATH/src/istio.io/istio/mixer
export ADDRESS=[::]:38355
```

 }}

**Comment by venilnoronha** [comment]
> You will need three terminals open to complete this walkthrough, open three terminals or three tabs now and set the environment in each:

I'd prefer specifying instructions to add the environment variables to the `~/.bashrc` (or equivalent) file instead of controlling the number of terminals/tabs to open.

**Comment by DanRoscigno** [comment]
Thanks for reading @venilnoronha.  In general I agree that the .bashrc is a good place for environment vars, but these are specific to this tutorial and should not persist long term.  How about I address the concern of specifying the number of terminals by adding the export statements where the text "open a new terminal" occurs in the doc?  This will fix the problem without needing an edit to .bashrc.

**Comment by venilnoronha** [comment]
That would work. Thanks.

**Comment by DanRoscigno** [comment]
Editing up top to reflect the discussion with Venil Noronha.

**Comment by geeknoid** [comment]
I applied those changes to the Wiki.

Thanks!
