### ISSUE TITLE
Decide on the fate of the CI logging scope

### ISSUE THREAD

**Issue by ozevren** [istio/istio#8812]
We have a CI logging scope in the test framework for spewing logs that maybe helpful in a CI environment. There is contention in the usefulness of this scope. 

We should observe the trends with the new Test Framework adoption and decide on the fate of this scope. We can either eliminate it and combine with the Framework scope, or we can keep it.

**Comment by nmittler** [comment]
I think it's fine for now.  We can bring it back up in the future if anyone growls.
