### ISSUE TITLE
Design Istio wide config status mechanism

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#882]
K8s has a standard way to get  status for a resource. 
For most resources `status` gets attached as a sub resource.
 
`kubectl get pods podname`
gives you
```bash
spec:...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-09-13T21:07:12Z
    status: "True"
    type: Initialized
  containerStatuses:
  - containerID: docker://869827ddb2eb7f1d21950bb01cf1b06210c7953717b1eb360bb2140091f94b7e
    state:
      running:
        startedAt: 2017-09-13T21:07:13Z
  hostIP: 10.128.0.10
  phase: Running
  podIP: 10.44.0.98
  qosClass: BestEffort
  startTime: 2017-09-13T21:07:12Z
``` 

We need a mechanism to query the status of a configuration resource. 
There are 2 choices
1. We ask the API server for this info like other k8s resources. However different Istio components will have their own view of the configuration and specifically status. All this information will have to be consolidated into one place.
2. Add a `/config/status` endpoint on all Istio components where one can query the components' view of the configuration and its status. This approach is taken in https://github.com/istio/mixer/pull/1325/

This also involves defining the `status` sub resource schema.

**Comment by kyessenov** [comment]
1. Why would multiple components collide on a single resource? This approach has more technical challenges. For example, ingress controllers go through the whole leader election cycle to prevent multiple writes to the same ingresses.

2. What does it mean for a config intent to have status? In case of pilot, does that mean some pilot picked up the rule and some proxy fetched it? I think it's difficult to get configuration-resource level observability. What we need is system-wide status. For example, we need to propagate the rules 
 and their revisions used to make any decisions by Istio to the logs and monitoring systems. That would solve the problem of finding which rules affect the behavior. Then there's a question of why a rule is _not_ applied. For that, we need a way to execute decisions on user-provided inputs (something like simulate or test commands in CLIs). This is just a generic problem of policy engines

**Comment by kyessenov** [comment]
Please don't add ad-hoc status sub-resources until we properly design the semantics.

**Comment by costinm** [comment]
Keep in mind hybrid / multi-region will also change the semantics of this
in 0.3 ( and I assume this is needed for 0.3 or
later ). Various proposals in hybrid involve sync / replication - we should
embrace and accept 'eventually consistent',
attempting to get global status is tricky.

What feature depends on knowing the exact status - and can we avoid this ?

Costin

**Comment by mandarjog** [comment]
#2 asks every component about its view of config resources including status, I.e. Does the configuration make sense to the component and was it able to act on that configuration.

In this case we don't need to have a globally consolidated view, it is eventual consistency friendly.

Re: need to know system status, I don't think we need to know anything. From a user perspective, say that I revoked an API key, it would be nice for me to know if that change has taken effect system wide.  

What do our users expect when they submit a new routing rule? That it may never fully take effect, *and* I have no way to know if it has taken effect. Is that an acceptable answer ? If so we don't need to solve the problem of system wide status.

#2, component status will work just fine.

**Comment by costinm** [comment]
If it's for debugging purpose, it seems very reasonable for each component
to be able to report its status, version, etc
Even for monitoring purpose, you can have each component report the
timestamp or version of last config it
got, or some sha.

What doesn't work so well is if you have code that relies on status - and
tries to act on it, like 'wait
until status is applied on all components, do something'. You need to get
the real status from the sidecars -
and while now we only have envoy and flat network, in hybrid we may have
'native' Istio ( gRPC, etc),
or other sidecars - but more important firewalls and NATs. You can't assume
you'll have access to the
debug/status of each node in the mesh. Even if you could - think about 10K+
pods in far-away locations.
It doesn't work very well in practice (at least in my experience).

Adding a requirement that each mesh components reports a config watermark (
along with load info
for example ) and aggregating it as part of monitoring is very useful, but
I don't think we can tell
users we'll be able to provide real time global config status in hybrid and
large meshes.

Costin

**Comment by ayj** [comment]
ref: https://github.com/istio/istio/pull/5893

**Comment by andraxylia** [comment]
Bumping up the milestone on this one based on #6082 : "It would be great if Istio resources (like Gateway) expose some Status information so that downstream can check before sending traffic to the Gateway.

Similarly, it would be good to know when a VirtualService's routerules have been propagated / effective."

**Comment by liamawhite** [comment]
This is possible by looking at the `config_dump` endpoint in Envoy Admin API. You can work out which clusters/listeners/routes have been added from Pilot.

**Comment by ozevren** [comment]
We have a design for multi-resource validation and an associated prototype for updating CRD status:
https://docs.google.com/document/d/1m19jkLyiIXNmUH_TYClRH-IOmuCJO4-vduy5KaCa99E/edit
https://github.com/istio/istio/pull/15824

Some of this work (analysis framework) is already landing in master as of this message. The CRD status controller should land in 1.4, off by default.

**Comment by ozevren** [comment]
I am moving this issue to be config only, unless there are objections. @sushicw is already working on this area, so I am assigning this item to him for tracking.

**Comment by sushicw** [comment]
https://github.com/istio/istio/issues/16350 got the foundation of this into master, but we still need to add the status update part. (There's a WIP PR at https://github.com/sushicw/istio/pull/6/files)

**Comment by ozevren** [comment]
The status controller is in: https://github.com/istio/istio/pull/17360 (also https://github.com/istio/istio/pull/17423 pending).

**Comment by sushicw** [comment]
This should all be in master and working now. 

This issue covered a lot of ground, though, so consider this a last call for comments before closing.
