### ISSUE TITLE
Fix the user cookie in bookinfo test that expires monthly

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#8821]
**Describe the bug**
The e2e-bookInfoTests-envoyv2-v1alpha3 fails monthly due to the user cookie used in the test (#7109) expires monthly.

Test log: https://k8s-gubernator.appspot.com/build/istio-prow/e2e-bookInfoTests-envoyv2-v1alpha3/7160

The most recent fixes: #8052 #8819 

**Expected behavior**
The test should either use a never expired cookie or have a mechanism to update the cookie dynamically each time running the test.

**Steps to reproduce the bug**
N/A

/assign @krancour 
/cc @hklai @rshriram

**Comment by hklai** [comment]
And it was possibly caused by https://github.com/istio/istio/pull/7109.

**Comment by sdake** [comment]
Can the individual that fixes this please backport to 1.0.

TX
-steve

**Comment by krancour** [comment]
Whoa. Completely did not realize that the encoded cookie that I hard-coded into the test had such a short ttl. I'll happily fix this.

**Comment by krancour** [comment]
@yangminzhu @hklai actually... I'm struggling right now to understand how that cookie has been implicated in these test failures.

In fact, the data that is hard-coded in that `sessionCookie` attribute of the `User` type is _just_ the cookie's data/contents. History shows that has been tampered with twice-- there should have been no reason to do so.

That data gets _added_ to the `Value` of an `http.Cookie`-- which has _no expiry_ set on it. i.e. The cookie that is being sent from the test client to the bookinfo product page _has no expiry_.

So something else is going on that is causing test failures. It's not the cookie.

**Comment by hklai** [comment]
@krancour here is an attempt https://github.com/istio/istio/pull/8848

**Comment by krancour** [comment]
@hklai can you comment on my response? Expiry date/time are _not_ encoded in the cookie currently, so I don't understand why this issue is occurring monthly, nor do I understand how it's been implicated in the test failures.

I will say, however, that now I am wondering if Flask session cookies have their _own_ expiry encoded into them that are separate from the actual cookie's expiration...

That could be it maybe...

**Comment by krancour** [comment]
Ah... that's it...

https://stackoverflow.com/questions/11783025/is-there-an-easy-way-to-make-sessions-timeout-in-flask

> By default in Flask, permanent_session_lifetime is set to 31 days.

So the expiry on the cookie is _not_ set, but Flask adds its own expiry.

I guess #8848 is a reasonable approach. The alternative could be to set `session.permanent = True` in the bookinfo productpage app.

**Comment by yangminzhu** [comment]
@krancour I think for the session cookie like `eyJ1c2VyIjoibm9ybWFsLXVzZXIifQ.DoMUEA.sydRfASlm9ky6FHX_BHKvW7YvkA`, the middle part (`DoMUEA`) is the encoded timestamp of when it's issued by the server. (The first part encodes the actual user name and the last part is the signature)

**Comment by yangminzhu** [comment]
This should be fixed by #8848.

**Comment by krancour** [comment]
@yangminzhu... ah ok. I was never able to decode that middle part. I'm not a Flask expert, really, but I guess that makes some kind of sense.
