### ISSUE TITLE
UX: Troubleshooting inbound and outbound traffic

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#8823]
We should consider prefixing the listeners and routes name with inbound and outbound, similar to what we do with clusters, to help our users troubleshoot network issues, which is one of the pain points of Istio users. We would this convention also to build tooling that would trace traffic, and do a dry-run of the mesh.

Right now, one has to understand the convention Pilot adopted to generate listeners and routes to be able to make sense of Envoy config. In the future, Pilot may change the convention ( the lack of a standard is an entirely issue in itself).

For instance:
$ istioctl proxy-config listeners --port 9080 reviews-v1-6b7f6db5c5-xhtcz -ojson
[
    {
        "name": "10.36.0.13_9080",  <--- this is an inbound listeners"
    ....
        "name": "0.0.0.0_9080", <-- this is an outbound listener
]

Route inside listener
"rds": {
                                "config_source": {
                                    "ads": {}
                                },
                                "route_config_name": "9080" . <-- this is the route
                            },

thoughts ? @rshriram @costinm @douglas-reid

**Comment by praveensastry** [comment]
@rshriram I would like to pick this up, would this also require a change in envoy proxy or has already been changed in the v2 api?
