### ISSUE TITLE
Kiali SSL support

### ISSUE THREAD

**Issue by morvencao** [istio/istio#8826]
**Describe the feature request**
Currently, `kiali` in `Istio` chart doesn't support `SSL`, however, `kiali` itself supports `SSL` after the PR: https://github.com/kiali/kiali/pull/469
We need to add option for Istio chart to support SSL.

**Describe alternatives you've considered**

**Additional context**

/cc @gyliu513 @clyang82

**Comment by sdake** [comment]
would be nice if there were an telemetry-gateway type feature for Kiali as well.

**Comment by gbaufake** [comment]
I'll send a PR which will enable SSL support for Kiali in Helm

**Comment by morvencao** [comment]
@sdake You mean we can export kiali service with ingressgateway, just like how we handle with `grafana` and `prometheus`?
This is a solution, I think we should also support HTTPS for `Kiali` itself, we just need to provide cert/key pair and set it in ENV.

**Comment by linsun** [comment]
@morvencao @gbaufake can this be closed now with latest kiali?

**Comment by jmazzitelli** [comment]
We fixed this in istio 1.1 via PR https://github.com/istio/istio/pull/10363
So I think this issue can be closed.

**Comment by morvencao** [comment]
Yep, OK to close.
