### ISSUE TITLE
OOP adapter performance

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#8829]
This issue is to track works related to Mixer OOP adapter performance benchmark. https://github.com/istio/istio/pull/8815 adds a benchmark test which runs single report dispatch against compiled in spyadapter and IBP based spybackend and measures encoding/decoding and grpc transport latency overhead. Two more benchmark remains:

- [ ] encoding latency: golang benchmark test which just measures encoding latency and avoids network latency
- [ ] throughput benchmark: instance dispatching per second per core

cc @mandarjog

**Comment by bianpengyuan** [comment]
Here are some rough results from initial tests:

**Latency:** I used [oop benchmark test](https://github.com/istio/istio/blob/master/mixer/test/perf/oop_report_test.go) to measure difference of dispatch latency between compiled-in and oop adapter. To avoid network latency I have to comment out the code which invokes the adapter remote handler since golang grpc does not support in memory transport. Here is the result:

```
Benchmark_IBP_Adapter_Report/InProcessBypassGrpc-12         	  100000	     22154 ns/op	    6273 B/op	     113 allocs/op
Benchmark_Inproc_Adapter_Report/InProcessBypassGrpc-12         	  100000	     17060 ns/op	    3525 B/op	      86 allocs/op
```

Roughly oop dispatch code path increases latency by 30%.

**CPU:** I set up a simple test environment with GKE and two nodes to measure CPU consumption difference. In the test environment, mixc runs on one node and istio-policy + a noop oop adapter run on the other node. Check cache is disabled in istio-policy. By defining the same authorization instance with decent complexity and decent amount of traffic from mixc, here is the result: ![screenshot from 2018-09-27 18-24-38](https://user-images.githubusercontent.com/34738376/46182788-9ff57200-c282-11e8-85ee-724ad8c603ea.png)

Roughly policy + oop adapter spends 50% more cpu than policy with inproc adapter.

**Comment by bianpengyuan** [comment]
After taking a closer look at the mixer cpu profile of compiled in adapter and OOP adapter, most of increased CPU usage are from grpc transport between mixer and adapters. Protocol encoding does not consume much CPU. This specific test set up make the cpu consumption even worse because check cache is disabled and every check request invokes a RPC from mixer to the adapter. With check cache the cpu usage increase should be mitigated a lot. Profile flame graphs could be found [here](https://github.com/bianpengyuan/mixer-oop-perf/tree/master/check-oop-perf-test).

However it is not as easy to optimize cpu for report, we might need another buffer before the mixer call to OOP to reduce system call overhead. Here is the result of similar test for report, with mixc batches 1000 reports per RPC call as mixer client does.
![screenshot from 2018-10-03 17-45-59](https://user-images.githubusercontent.com/34738376/46446971-3a96fa80-c734-11e8-9ff8-06ef304b11fb.png)

**Comment by mandarjog** [comment]
@bianpengyuan batching remote report calls has been on the agenda. This clearly shows the importance of that. Thanks for doing this work, this is great.

**Comment by bianpengyuan** [comment]
@mandarjog Batching of remote report calls does not help much. The encoded instance is not compressed and grpc has 4 Mb max message size limit, which makes each batch could only contain 5000 instances (5 mixer report calls from mixer client in this test setup basically).
