### ISSUE TITLE
Istio seems to modify the content of my TCP request

### ISSUE THREAD

**Issue by sneko** [istio/istio#8836]
Hi!

I'm using Istio 0.7 with Auth **disabled** and I'm trying to use a Redis cluster inside a Kubernetes cluster. (plus, there is also a Sentinel cluster needed to manage who is the master/slave of the Redis cluster)

_Note that my Redis and Sentinel clusters are in a namespace not injected by Istio._

You need first to understand what I need to do to write on the Redis master:
1. I reach one of the Sentinel pod through the service "sentinel-service" and ask it for the Redis master IP
2. The Sentinel pod answers me the IP
3. I can now write to my Redis master through its IP for example with the command `SET mykey "Hello"`

But I got an error:
```
/data # redis-cli -p 6379 -h 100.96.7.69 SET mykey "Hello"
Error: Connection reset by peer
```

Since my Sentinel pods were accessible and that they use the same Docker image (except a parameter --sentinel) I figured out that I need to create a service bound to these Redis pods to "make it working" even if I don't use this service. Like that the error is a bit different:
```
/data # redis-cli -p 6379 -h 100.96.7.69 SET mykey "Hello"
Error: Protocol error, got "H" as reply type byte
```

It's like if with a service Istio know about this pod and let me reach it. But there is still this `Error: Protocol error, got "H" as reply type byte` issue. I made a lot of researches on Google but didn't find the answer to fix this issue.

So I have basically disabled the injection of Envoy into my pod and... surprize, it works well  😀 ... : 
```
/data # redis-cli -p 6379 -h 100.96.7.69 SET mykey "Hello"
OK
```

The only thing that is different between both case is the presence of the Envoy sidecar on my client (remember, I don't have any sidecar on the Redis servers).

Do you have any idea about this issue? What could interfer with my request?

I cannot get rid of my Istio service mesh, I have to find a solution 🔨 

Thank you,

**Comment by mandarjog** [comment]
You are attempting route directly to pod ips.
There are multiple ways of doing that, simplest is to exclude the pod ip CIDR from capture using “excludeIPranges”.

It would be great if you can use a post 1.0 version of istio.

**Comment by sneko** [comment]
@mandarjog the major problem is that my Redis pods could have a different IP in case of a restart/crash... It's pretty hard to define the IP range :/

Since I'm loosing my hair I think I'm gonna upgrade to Istio 1.0.2 even if cert-manager is still unable to create Gateway to renew SSL certificates. I will do that manually... no other choice 😢 

By advising me to switch over a 1.0+ version, is it easier to communicate with a pod through its IP?

Thank you,

**Comment by mandarjog** [comment]
@sneko pod IP CIDRs are explicitly defined in K8s, you can exclude all of them. 
You normally do not need to adjust the range for a cluster until you make a network level change.

**Comment by sneko** [comment]
@mandarjog I saw the part in the docs about that:
https://istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly

There is a "generic" way to find them no matter the environment you have:
```
kubectl cluster-info dump | grep -i cidr
```

I added my IPs ranges in Istio Egress exclusion and it works well now! I'm able to reach my Redis cluster pods through their IP 😀 

Thank you very much @mandarjog! Have a good day!

_PS: By the way, I upgraded Istio to 1.0.2 but I'm hopping the Istio team will soon find a great way to deal with Cert-Manager HTTP01 programmatically instead of DNS01 👍 _

**Comment by sneko** [comment]
@mandarjog one quick question, is it possible that by excluding all my Kubernetes pods IPs it makes my impossible to communicate with ISTIO_MUTUAL?

Ref:
https://groups.google.com/forum/#!topic/istio-users/sBpualYweX0

Thank you,

**Comment by sneko** [comment]
@mandarjog I just upgraded my Kubernetes cluster from 1.9 to 1.10 and the pod CIDR changed... so my Istio settings were broken and it broke some of my microservices due to this 👎 

Have you heard about this problem? I hope it won't happen each minor k8s update... 😆

**Comment by sneko** [comment]
Hi @mandarjog , you said:
`There are multiple ways of doing that, simplest is to exclude the pod ip CIDR from capture using “excludeIPranges”.``

Since I'm still annoyed by changing PodCIDR after each Kubernetes update, I'm wondering what are the other ways you mentioned?

Thank you,
