### ISSUE TITLE
Istio upgrade: customized config maps

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#8841]
Istio installation contains standard config maps.
`istio - mesh config`, `istio-sidecar-injector` and `prometheus` are just a few examples.

A simple upgrade with kubectl apply will overwrite these config maps with defaults from the next version.

A possible solution is to have an additional override configmap, where operator makes changes.
We always combine the managed and unmanaged configmap to arrive at final configuration.

**Comment by mandarjog** [comment]
@sdake

**Comment by nmittler** [comment]
What sort of tooling do we have for upgrades? If the user were asked to provide the previous Istio version at the beginning of the upgrade (or if we could automatically detect it), we could determine what values have changed from the defaults for that version and automatically merge them into the resulting configmap.

**Comment by sdake** [comment]
@nmittler I think what you describe is a 3 way patch merge.  The tooling we have at present is Helm which stores the configmaps internally in tiller.  Think of tiller as a pre-CRD specialized CRD controller + some extra magic.  Helm has rejected 3 way merge as a solution for the 2.y.z series.  See: https://github.com/helm/helm/issues/3805#issuecomment-414133289 for more context.

Cheers
-steve

**Comment by sdake** [comment]
I believe adding unmanaged objects to helm could result in an un-upgradeable system, but could be wrong.  We have been working to stamp out unmanaged objects in Helm entirely to eliminate the problems discussed in https://github.com/helm/helm/issues/1193.

Cheers
-steve

**Comment by sdake** [comment]
There are two install/upgrade approaches:
1. `kubectl apply` (install and upgrade)
1. `helm install` or `helm upgrade`

The second approach is the use case most Helm consumers are most familiar with.  Generally Istio has been strongly recommending approach 1.  Approach 1 suffers from many problems.  Approach 2 suffers from many problems.

I suspect a specialized operator would end up reimplementing approach 1 + what is coming in Helm 3.0 targeted EOY.

Cheers
-steve

**Comment by ozevren** [comment]
Can we make this a non-problem by making use of sane defaults?

IMO ConfigMaps fields should be treated as APIs. From version to version, not only we need to retain backwards compatibility of the fields, but we should also make sure that all new fields will default to "sane values" when not-specified. (Similar to how API versioning would be done across minor versions).

Are there any problems that this approach won't fix?

**Comment by mandarjog** [comment]
I do not think sane default address this problem. They are good, but orthogonal here.

It is about customization. We can say that these configmaps are implementation detail and the only supported way to customize is helm template and `values.yaml`. 
This means that we will have to ensure that every supported feature in meshconfig (and other configmaps) is available in helm.

I think this is an ok position, but the cost of forgetting this is that the system forgets customizations on upgrade.

**Comment by howardjohn** [comment]
@ostromart this seems to be basically what you are working on right now.

**Comment by esnible** [comment]
I believe the plan is that `istioctl install` writes the IstioOperator to the cluster.  I am working on a PR for `istioctl upgrade` that causes that IstioOperator to be used as the basis for `istioctl upgrade` rather than the default Istio profile.  https://github.com/istio/istio/issues/23183 .

Will this behavior be sufficient for this Issue?
