### ISSUE TITLE
[test-framework] Allow use of non-"istio-system" namespaces

### ISSUE THREAD

**Issue by ozevren** [istio/istio#8849]
We currently cannot deploy Istio to namespaces other than "istio-system". This bug is tracking the work that needs to be done to fix that.

**Comment by ayj** [comment]
What's the motivation for testing installing in other namespaces? Is the intend to run multiple concurrent tests in different namespaces in the same cluster? We might need tests to provide an additional _hint_ about whether they are cluster or namespace scoped. Some aspects of Istio control plane may be cluster scoped, e.g. webhooks, default auth policy.

**Comment by skydoctor** [comment]
Can someone comment on what are the things that don't work specifically when a different namespace is used? I rendered a helm chart by using some other value in "--namespace" using helm template. The resulting istio control-plane appears to be working fine. What are the things I should check as potentially being broken?

**Comment by skydoctor** [comment]
@linsun: I see that you have worked on a few namespace related issues. Do you know what works and what doesn't when the namespace is changed from "istio-system" ? Thanks

**Comment by ozevren** [comment]
Ideally nothing should be broken when a namespace other than "istio-system" is picked. However, I don't think we have a test that particularly covers this.

Being able to change the deployment namespace should be a simple "use the supplied config value, instead of a constant" for the system (and the framework).

**Comment by jmazzitelli** [comment]
This reminds me - Kiali needs to be told where Istio is deployed if not in default namespace of istio-system. I just created a couple PRs for this:

https://github.com/istio/istio/pull/9762
https://github.com/istio/istio/pull/9763

**Comment by nmittler** [comment]
@ozevren is all that remains here is to try out the test framework with an alternative namespace?

In fact, I wonder if by default the system namespace should be auto-generated the same way we do for test and suite scopes.

**Comment by ozevren** [comment]
I am not sure what is left blocking this at this point. It needs to be tried out. Auto-generation sounds like a good idea. It will implicitly test and enforce the use of non-standard system namespaces.

**Comment by linsun** [comment]
I'm not aware of issues running in a namespace other than istio-system.  I recall red hat team published a blog on istio.io that describes running multiple istio in multiple namespaces for soft multi tenancy.

**Comment by nmittler** [comment]
@linsun IIUC this issue is specifically related to the new test framework, not Istio in general.

**Comment by ozevren** [comment]
There are only three references to the istio-system namespace in the new framework code, and all of them are benign (1 for default, 1 for documentation comment, 1 for generating attributemanifest from template, but the namespace is effectively ignored after that).

Closing this.
