### ISSUE TITLE
Use kubeclient to replace kubeclient apply in pkg/test/kube

### ISSUE THREAD

**Issue by m1093782566** [istio/istio#8873]
**Describe the feature request**
Use kubeclient to replace kubeclient apply. Kubernetes test team has already switched from kubectl to kubeclient - kubectl is not very safe.

**Describe alternatives you've considered**

Create kubeclient utils in pkg/test/kube.

**Additional context**

cc @nmittler @ozevren @hklai

**Comment by nmittler** [comment]
@m1093782566 sorry I just saw this.  Closing this in favor of https://github.com/istio/istio/issues/8877 (it's more slightly more generic).

**Comment by m1093782566** [comment]
no problem

m1093782566
发件人：Nathan Mittler
收件人：istio/istio,
抄 送：dujun (D),Mention,
时间：2018-09-21 00:04:01
主 题：Re: [istio/istio] Use kubeclient to replace kubeclient apply in pkg/test/kube (#8873)


Closed #8873<https://github.com/istio/istio/issues/8873>.
