### ISSUE TITLE
[test-framework] Use kube client everywhere

### ISSUE THREAD

**Issue by nmittler** [istio/istio#8877]
For k8s, the test framework is still using a mix of kube client and kubectl from the command line. We should move to having the test framework use kube client exclusively.

**Comment by m1093782566** [comment]
@nmittler 

As I am pretty familiar with Kubernetes, you can assign this task to me!

cc @ozevren @hklai

**Comment by nmittler** [comment]
@m1093782566 sgtm ... it's yours :)

**Comment by nmittler** [comment]
I've merged all k8s commands into the Accessor. This is good enough to mark this as done.
