### ISSUE TITLE
(vm support) istio debian packages should not pollute /usr/local/bin

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#888]
We install binaries that are only called by systemd or other scripts into /usr/local/bin
on the user's machine/VM (not a container)

That's a problem in itself which is compounded because we also use very generic names (eg node-agent for auth) which are more likely to collide with existing software on the machine

I believe should put all our software under $PREFIX - for instance /usr/local/istio by default (or /opt/istio or whichever as long as it's not pushing binaries into system locations where they would  conflict unnecessarily)

This includes "envoy" which should really be "istio-envoy" in case they have their own envoy binary used on their VM

(this came up in https://github.com/istio/auth/pull/270 (and in early deb code reviews))

**Comment by costinm** [comment]
+1 - also should probably be a (semantically) versioned directory, and use consistent naming across repos.

Not clear if double-istio is needed - i.e. /opt/istio/bin/istio-envoy vs /opt/istio/bin/envoy, or how this interferes with distros ( debian, etc ) that may want to package using LSB conventions. A doc 
considering all implications would be nice ( i.e. interaction with spiffee, alternative installations, upgrade/downgrade, etc)

**Comment by ldemailly** [comment]
@jwendell volunteered for a bigger version of this which would be to unify and make configurable
both the install directory prefix (aka `--prefix` in good ole configure) and the names (istio-x eg istio-pilot istio-envoy ... aka `--program-prefix` in good ole configure)

**Comment by ldemailly** [comment]
not stale (not the most useful bot)
