### ISSUE TITLE
[Security Vulnerability] : usage of /tmp directory as output

### ISSUE THREAD

**Issue by Hamza2404** [istio/istio#8892]
**Describe the feature request**
bin\istio-proxy-cfg.py:291
291  `output_dir = "/tmp/" + pod.name`

There are a number of rules to follow when creating a temporary directory path.
It could a vulnerability for attackers to look for commonly hard-coding file paths starting with :
- /tmp', '/var/tmp', '/dev/shm

**Describe alternatives you've considered**
- use [https://github.com/PyCQA/bandit](url) from @PyCQA as an alternative when bulding python application 
- cp files to another directory then reference back to the full path /.../tmp/ 

**Additional context**
https://docs.openstack.org/developer/bandit/plugins/hardcoded_tmp_directory.html

**Comment by sdake** [comment]
@Hamza2404 please see https://istio.io/about/security-vulnerabilities/
