### ISSUE TITLE
How to handle Isito chart version

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#8895]
Istio 1.0 already got released, but we are continually fixing bugs in release-1.0 branch for Istio helm chart without updating the helm chart version. 

This may bring some trouble to end user, as they may confused sometimes Istio 1.0 helm chart have different configurations. 

For Helm chart policy, the update to a released helm chart should have the chart version increased, we already have those field in helm chart, shall we follow the guidance to increase the `version` field for each backed merge to release-1.0 branch?

```
version: 1.1.0
appVersion: 1.1.0
```
/cc @costinm @sdake @linsun @morvencao

**Comment by linsun** [comment]
I think this is reasonable going forward for fixpacks and LTSs.  I would not worry about it for monthly releases.

**Comment by sdake** [comment]
@gyliu513 in speaking with @hklai about this topic, T&R plans to automate the version field changes for istio-1.0.3 and later.

Cheers
-steve

**Comment by hklai** [comment]
I originally plan to update these versions similar to how we deal with the tag in https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/values.yaml#L9

However, these chart files need to use semantic versions so a stable release tag won't work. I don't have an immediate plan how this can be fixed, but I updated the versions in release-1.0 to 1.0.3, in preparation for the new patch release.

**Comment by gyliu513** [comment]
I'm good with this solution, thanks @sdake @linsun @hklai
