### ISSUE TITLE
istio install file parity

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#890]
right now we have
```
istio.yaml  # everything, no auth
istio-auth.yaml # same file with mtls on
```
we discussed that
```
istio.yaml -> istio-no-auth.yaml 
```
and
```
istio-auth.yaml -> istio-with-auth.yaml
```
would be more clear and make it more likely a user would understand the choice

cc @rshriram @andraxylia 

only downside is there is a lot of references to istio.yaml and istio-auth.yaml from 0.1 and tests that would need update. a less risky alternative may be to only change it on the release tgz and the website

or just leave with it until 0.3 / installer....

putting 0.2 for now as a proposal for tweaking this last minute (on the other hand the last PR setting up those files was merged only this morning so it's not like it's been "stable")

**Comment by andraxylia** [comment]
I propose we wait until auth will be on by default, and we can toggle auth on and off. At that point, there will be just istio.yaml.

**Comment by linsun** [comment]
I would prefer to leave as it is today.

**Comment by linsun** [comment]
sorry i was not super clear, that was a statement for 0.2.   because we have a lot of work right now for 0.2 and istio.yaml generates no confusion for me... plus like you said a lot of references.

**Comment by rshriram** [comment]
I would opt for istio-noauth and istio-auth.yaml.. The reason is because, once defaults go out, its going to be hard to change perceptions and systems that rely on really not having auth or some features, will break when they install an istio.yaml which has auth turned on by default. It also makes the two options very clear in the docs.

**Comment by andraxylia** [comment]
There will be just istio with auth pretty soon, and a single istio.yaml file, with the option of toggling encryption on/off via some config/configMap.  The current model helps with the transition. A better change would be to have istio and istio-noauth, and get rid of istio-noauth in 0.3.

**Comment by linsun** [comment]
defer this to 0.3 as it is not critical for 0.2...let me know if anyone strongly disagrees :)

**Comment by ldemailly** [comment]
sgtm

**Comment by costinm** [comment]
We are moving to helm template, where each feature can be individually configured.

We'll still generate istio and istio-auth, for backward compat - but expectation is that each user will set the features however they want. 

We will have some pre-baked sets of defaults - 'values-demo' with all on, 'values-auth', etc

**Comment by ldemailly** [comment]
A good start would be to have istio-noauth.yaml and istio-auth.yaml
generated from whichever is the source of truth for an upcoming release

**Comment by costinm** [comment]
AFAIK the plan is to switch to helm/istioctl, and keep the 2 configs only for migration/legacy. 

In helm/istioctl each feature is independently enabled/disabled.
