### ISSUE TITLE
Testgrid dashboard is not showing consistent data for CircleCI Jobs

### ISSUE THREAD

**Issue by ozevren** [istio/istio#8907]
http://k8s-testgrid.appspot.com/istio-presubmits

Some of the links in the presubmit is showing data from each checkin, whereas the other ones are showing data from nightly runs, or some unrelated branches/jobs.

Some examples:
http://k8s-testgrid.appspot.com/istio-presubmits#circleci-e2e-simple
http://k8s-testgrid.appspot.com/istio-presubmits#circleci-e2e-pilot-cloudfoundry-v1alpha3-v2
http://k8s-testgrid.appspot.com/istio-presubmits#circleci-test

Counter example:
http://k8s-testgrid.appspot.com/istio-presubmits#circleci-racetest

It is probable that this is because of our dependency on CIRCLE_PULL_REQUEST environment variable, which may be getting set inconsistently:

https://discuss.circleci.com/t/circle-pull-request-not-being-set/14409

**Comment by hklai** [comment]
I found some more problem symptoms.

1. Some circle presubmits are not longer uploading to GCS. Example https://circleci.com/gh/istio/istio/193967

```
#!/bin/bash -eo pipefail
bin/ci2gubernator.sh --job_starts
GCS_BUCKET_TOKEN not defined

```
2. The non presubmit bucket now have post submit data from master branch, while the presubmit buckets have post submit data from all other branches.

I will try to fix it.

**Comment by hklai** [comment]
1. The first problem is fixed by @rshriram. GCS_BUCKET_TOKEN  is now passed to all test jobs.
2. The second problem is fixed by https://github.com/istio/istio/pull/8910.

I am going to fix testgrid config to make sure things are pointing to the right bucket.
