### ISSUE TITLE
How to strip path in ingress?

### ISSUE THREAD

**Issue by santhosh-git** [istio/istio#8917]
I am using Istio in my kubernetes cluster. Below yaml is my ingress rule. Here /nginx is proxying to the backend. Is there any way to strip path while proxying to backend.

Example: 
https://gateway.example.com/nginx  should be proxied to backend like localhost:80/

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  clusterName: ""
  name: nginx
  namespace: default
spec:
  gateways:
  - gateway
  hosts:
  - test.abc.com
  http:
  - match:
    - uri:
        exact: /nginx
    route:
    - destination:
        host: httpd
        port:
          number: 80
---

**Comment by mabushey** [comment]
I think you just need to use rewrite:
```
  - match:
    - uri:
        exact: /nginx
    rewrite:
      uri: /
```

**Comment by santhosh-git** [comment]
Thanks, Mabushey. Your solution helped!!!

**Comment by jaygorrell** [comment]
This isn't a good solution. Rewriting `/nginx` to `/` means `http://service/nginx/index` gets rewritten to `http://service//index`. There's some better discussion in https://github.com/istio/istio/issues/8076

**Comment by samunbest** [comment]
> This isn't a good solution. Rewriting `/nginx` to `/` means `http://service/nginx/index` gets rewritten to `http://service//index`. There's some better discussion in #8076

yes but i seems wrong when i rewrite ""
