### ISSUE TITLE
Grafana Mesh Dashboard shows low success rate for everything due to incorrect column alignment

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#8918]
**Describe the bug**
This is basically a Helm-applied Istio install with only prometheus/grafana enabled and includeIPRanges set to the k8s network. The grafana mesh dashboard shows mostly a < 1% success rate for all services, despite the global success rate in the header being 99.9%. The services are working fine so it appears to be a display issue. I have also seen some numbers as high as 1000%.

**Expected behavior**
Success rate on dashboard is accurately bound between 0% and 100%.

**Version**
Istio 1.0.2
Kubernetes 1.9.3

**Installation**
Helm template with `includeIPRanges` set to `"100.64.0.0/10"` and prometheus/grafana enabled.

**Environment**
AWS / Kops

![screenshot 2018-09-23 17 44 16](https://user-images.githubusercontent.com/12174604/45933326-57734700-bf58-11e8-836e-71f5d3f4cccb.png)

**Comment by mandarjog** [comment]
Thanks for the bug report. A PR to fix this will be merged in shortly. The value in column F is the real success rate.

**Comment by jaygorrell** [comment]
Thanks @mandarjog - I was just going to update that it looks similar to something referenced here: https://github.com/istio/istio/issues/7943#issuecomment-416736876

Is there a temporary fix by manually bumping an image version that I can do?

**Comment by k** [comment]
I installed `1.1.0-snapshot.1` and this appears to be fixed

**Comment by jaygorrell** [comment]
Thanks @k, I confirmed that fixes this issue as well. So the released dashboard in 1.0.2 is simply busted? I suppose this can be closed then but if this should be reopened to track a fix for 1.0.x, feel free.
