### ISSUE TITLE
[test-framework] Align environment variables used by tests

### ISSUE THREAD

**Issue by ozevren** [istio/istio#8928]
We currently have two sets of environment variables in pkg/test/env. these are getting used by both e2e framework, as well as the new test framework. While there is an overlap between the two, it is not possible to use them interchangeably, due to the particular use-cases they are accessed (e.g. CircleCI v.s. local use).

We should rationalize and align them.

**Comment by nmittler** [comment]
@ozevren do you have a specific example? Is the problem simply a matter of which default is used?
