### ISSUE TITLE
Consider using 1 or 2 instead of NCPU worker threads in sidecars

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#8938]
**Describe the feature request**
Currently, sidecars are started without specifying `--concurrency` parameter, which means that they spawn NCPU (number of CPUs available on the host system) worker threads.

This not only leads to a higher memory usage (~2KB per configured cluster for each worker thread), but also to a higher effective CPU limit, where a single sidecar can saturate all CPUs available to the host system, leaving little to nothing to the workloads.

I've added the ability to control number of sidecar worker threads in https://github.com/istio/istio/pull/8287, but the default was left as-is for the moment.

**Additional context**
https://github.com/istio/istio/issues/8247

**Comment by PiotrSikora** [comment]
cc @costinm @rshriram @duderino

**Comment by mandarjog** [comment]
Yes, Please do make this change for 1.1. We want this number to be equal to the `requested` CPU.
The minimal should be one and if it make sense 2.

**Comment by cmluciano** [comment]
@duderino Are you still working on this?

**Comment by Liv1020** [comment]
if template has more containers, you don't know which one container's requested cpu is main, we can add metadata's annotation like `proxy.sidecar.istio.io/concurrency`?

**Comment by cmluciano** [comment]
@knrc Are you still working on this?

**Comment by knrc** [comment]
@cmluciano Yes, I had a slight break to get a release out but am now on this

**Comment by knrc** [comment]
@cmluciano I have a WIP which I'm about to test and can submit a PR within the next day, it adds a validator for the sidecar.istio.io/proxyCPU annotation and a new function for determining the correct quantity within inject.go.

Do we want to introduce a second annotation as suggested?

**Comment by knrc** [comment]
The PR was pushed up yesterday, https://github.com/istio/istio/pull/10854

**Comment by Liv1020** [comment]
I look at other annotation format, Is `proxy.sidecar.istio.io/cpu` more suitable?

**Comment by knrc** [comment]
@Liv1020 it's an existing annotation

**Comment by Liv1020** [comment]
@knrc I see, so i delete comment

**Comment by rvansa** [comment]
Hello, I've been trying to get some grisp on the actual effect of changing worker thread count. Please see [this report](https://docs.google.com/document/d/1UCqHBOL24is47R1mbM417h8XAvATNER_oGTxHQTlER8/edit?usp=sharing); TLDR is that using as many threads as cores is helpful if the server is not doing very heavy computation, and if it is, 4 - 8 threads on a 32-core machine seems as the optimum.

I'll be amending the document with further results employing more envoy instances on the same physical machine.

**Comment by duderino** [comment]
@rvansa thanks for the analysis.

@knrc how about changing the default to 4 envoys threads per virtual core?

@PiotrSikora and @mandarjog please sanity check ^^

**Comment by knrc** [comment]
@duderino I can certainly take a look at that.  I'll be meeting with @rvansa next week in any case, he's one of the performance guys assigned to us and we had been talking about this earlier in the week.

**Comment by rvansa** [comment]
@duderino @knrc I've added more results for a case with 4 proxies on the same machine. The results show that even here the effect of more threads is rather positive.

Is it even wise to expose configuration of worker threads through Istio? I assume that the number of cores is taken through c-group information, and this can be set natively through resource limits on CPU. If we keep the default based on cores (rather than fixed value somewhere else in configs) it would pick the threads accordingly. I need to verify if this works as I expect.

**Comment by rvansa** [comment]
@knrc In the PR you've set the `--concurrency` to `ceil(CPUs)`, but from the 4-proxy setup it looks that having multiple threads per core might be beneficial. IIUC there is no way to override concurrency when `sidecar.istio.io/proxyCPU` is set; it might be useful to allow `sidecar.istio.io/proxyThreadsPerCore` multiplier. The default is questionable ofc, from what I've seen 2 might be actually better than 1.

**Comment by knrc** [comment]
@rvansa We can chat about this on Friday and then update this issue

**Comment by suryadu** [comment]
I think we need to do some more analysis in the concurrency as our results on Cloud native end to end workload are here 
![image](https://user-images.githubusercontent.com/13684010/51625144-10935f00-1f02-11e9-90c2-bc677590c007.png)

**Comment by suryadu** [comment]
As seen in the chart, with 1 worker threads, we do see less sidecar CPU. we need to do more tests

**Comment by PiotrSikora** [comment]
@rvansa @suryadu yes, ultimately, this is a trade-off between latency vs CPU and memory usage, and no default will be perfect for all the use cases.

The main reasons for drastically lowering the default number of worker threads are:
- lower sidecar's total memory usage, since there is a non-zero memory overhead per thread, though it has been significantly reduced in the past few months (see: #7912, #8247),
- make number of workers somehow realistic, because NCPUs reflects host-available CPUs and not container-available CPUs, which means that if there are 16 workloads with sidecars on 64 vCPU host, currently, there would be 1024 (16*64) worker threads started (see: #8247),
- avoid consuming too much resources by the networking layer (i.e. proxy), e.g. in the example above, with 4 threads per sidecar, there would be 64 worker threads started, which, under load, could use all the available CPU cycles, without leaving anything to the workload.

Hope this helps!

**Comment by duderino** [comment]
@knrc looks like this PR is stuck due to the prow/istio-integ-local-tests.sh failure.

Looks like the same failure for both test runs on this PR:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/pull/istio_istio/10854/istio-integ-local-tests/

But other PRs don't have the issue:  https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio-integ-local-tests

**Comment by knrc** [comment]
@duderino at first glance they seem to be unrelated to the changes I've added, I'll take a deeper look

**Comment by knrc** [comment]
@duderino It seems to have been an issue elsewhere, rerunning the test passes

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10854/istio-integ-local-tests/4680

**Comment by knrc** [comment]
@duderino It looks as if there are now more files to update in the tests though, I'll rebase and update those as well.  I'll push it up again tomorrow.

**Comment by knrc** [comment]
@duderino It looks as if this was left hanging for so long because of the discussions that someone decided to do this through another PR, https://github.com/istio/istio/pull/11311 and https://github.com/istio/istio/issues/11268

**Comment by rshriram** [comment]
fixed by #11311

**Comment by rvansa** [comment]
I've amended [my report](https://docs.google.com/document/d/1UCqHBOL24is47R1mbM417h8XAvATNER_oGTxHQTlER8/edit#) with results from a setup on Openshift with Istio. TLDR: on 8 or 16 CPU node giving 2 CPUs and passing `--concurrency 4` look like a good tradeoff.

**Comment by rvansa** [comment]
Since this issue was closed I'll post on discuss.
