### ISSUE TITLE
Determine how or if to maintain gendeploy

### ISSUE THREAD

**Issue by sdake** [istio/istio#8940]
**Describe the feature request**
istioctl gendeploy doesn't really do anything useful.  It appears unmaintained.  Either determine the requirements of gendeploy and make the implementation useful or remove it from istioctl.

**Describe alternatives you've considered**
Alternatives are described in the feature request.

**Additional context**
A feature request PR was requested in review: https://github.com/istio/istio/pull/8934

**Comment by andraxylia** [comment]
Gendeploy was added to support istio à la carte. Since we are doing this with helm, it's ok to deprecate it.

**Comment by ZackButcher** [comment]
We should just remove this, it never really achieved the goal I intended for it and we've largely replaced the use case with better helm config.

_Might_ be worth thinking about adding back with Istio-a-la-carte work; I'm not sure what the install story is supposed to be there (cc @louiscryan).
