### ISSUE TITLE
Create feature flag library

### ISSUE THREAD

**Issue by rshriram** [istio/istio#8960]
We have a number of trial features or new strategies to handle this/that, across all of Istio. While some have CLI flags and associated CRDs, some do not.. Esp pilot, that has a host of env variables that not only pollute the core code, but make it harder to follow, when things go wrong. Some of these variables are also long forgotten.

It would be good to have a single place (e.g., pkg/features/pilot.go) where we define variables that hold all these feature flags/settings obtained from env vars. The rest of the code could simply use the `if(feature_set), do x else do y` . This should make it easy for us to track what things are in experimentation mode (e.g., throttle debounce, etc..) and once things are stable, we can remove the feature flag and make it the only implementation (i.e. remove the else case).

We could also have a loop that periodically scans these env vars and updates the feature flags so that people can turn it on or off dynamically.

**Comment by rshriram** [comment]
cc @hzxuzhonghu / co or others, if you are looking for a TODO, this is a big one :).

**Comment by hzxuzhonghu** [comment]
Let me have a try. 
/assign
