### ISSUE TITLE
Kiali reports problem with virtual services

### ISSUE THREAD

**Issue by sdake** [istio/istio#8970]
**Describe the bug**
In master, Kiali reports an error on a valid virtual service (see screenshot).

**Expected behavior**
No error should be highlighted.

**Steps to reproduce the bug**
helm template istio --namespace istio-system --set grafana.enabled=true --set kiali.enabled=true --set telemetry-gateway.grafanaEnabled=true > gateway.yaml
kubectl create ns istio-syswtem
kubectl create -f grafnaa.yaml -n istio-system

**Version**
master

**Installation**
see reproduction steps

**Environment**
Istio + metallb + bare metal
<img width="1199" alt="screen shot 2018-09-25 at 11 15 38 pm" src="https://user-images.githubusercontent.com/755849/46060831-5fc6b000-c119-11e8-9aca-4634134fd90f.png">

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by sdake** [comment]
@knrc I am not able to assign this to you.  Could you take a look at getting this problem resolved in master?

Cheers
-steve

**Comment by pilhuhn** [comment]
@sdake What does the triangle on the failure say that it detected?

**Comment by lucasponce** [comment]
I have created a JIRA https://issues.jboss.org/browse/KIALI-1616 to track this one in Kiali project.

**Comment by sdake** [comment]
@pilhuhn kiali 0.6 - the warning is shown in the attached screenshot.  I am obtaining info on whether the warning is valid or not.
<img width="349" alt="screen shot 2018-09-26 at 10 06 18 am" src="https://user-images.githubusercontent.com/755849/46096397-edcf8480-c173-11e8-9448-3c73fe6e1203.png">

**Comment by frankbu** [comment]
Starting with Istio 1.0.1, multiple virtual services for the same host are allowed if the VSs are bound to a gateway. The warning should only appear for VSs without a gateway binding. Optionally it could also give a warning if there is an obvious conflict between the VSs (for example, there are multiple "catch-all" rules, i.e., ones without a match field). Documentation on VS merging is [here](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host).

**Comment by lucasponce** [comment]
Yes, thanks @frankbu, kiali 0.6 is holding an old validation rule, so we will update this logic for next versions in kiali.
