### ISSUE TITLE
kubernetes 1.5.x

### ISSUE THREAD

**Issue by arunkjn** [istio/istio#898]
Hi,

I wanted to ask if istio is compatible with k8s 1.5.x? As I saw in the getting started docs, it assumes k8s 1.7.x is present. 

My use case revolves around just using envoy as an edge router to ingress to a grpc service and also do in cluster load balancing (service to service) for the same service.

**Comment by ldemailly** [comment]
0.1.6 is compatible with k8s 1.5
0.2.x requires at least 1.7
