### ISSUE TITLE
FR: Support adapter configuration selection options in install

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#8986]
**Describe the feature request**
In a recent thread on the mailing-lists, it was noted that there is no way to control the set of Mixer adapter configuration that is generated for install (via helm, etc.). For example, the [config.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml) currently supports no template-based configuration.

The use case mentioned was that the user *only* wanted a Mixer with the `stdio` adapter configured for an installation.

We would probably need to consider support for a few template-based profiles, instead of just selecting adapters, as well. For instance, if you don't select any adapters that have say `metric` template support, should we still install the default `metric` configuration?

**Describe alternatives you've considered**
The workaround is to hand-edit the generated configmap in the larger yaml to remove out the handler configuration.

**Additional context**

**Comment by kyessenov** [comment]
This probably will benefit greatly from OOP adapters. Adapters can be installed and activated independently from the core installation.

**Comment by douglas-reid** [comment]
This was actually addressed in install code recently.
