### ISSUE TITLE
GKE cluster is not reachable right after being created

### ISSUE THREAD

**Issue by yutongz** [istio/istio#900]
There is a chance that a cluster is not reachable right after we create it on fly, we need to double check and make sure it's connectable before moving to next step.

One example: https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/872/new-e2e-rbac_no_auth/374/

**Comment by ayj** [comment]
dup of https://github.com/istio/istio/issues/858?

**Comment by yutongz** [comment]
@ayj Yes! Didn't notice you created one.

**Comment by linsun** [comment]
real close :)
