### ISSUE TITLE
Is there a guide on how to route TCP Egress traffic to an Egress gateway with istio 0.8

### ISSUE THREAD

**Issue by huydinhle** [istio/istio#9017]
I tried this guide out https://istio.io/docs/examples/advanced-egress/egress-gateway/ using istio 0.8. It only works with HTTP traffic. However it won't work with TCP at all, is there a guide for that ?

Thank you

**Comment by huydinhle** [comment]
Like let's say if I want to route TCP traffic  in the mesh to google.com but going through my egress gateway. How would I do that?

**Comment by vadimeisenbergibm** [comment]
@huydinhle Please see https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/ for TLS and https://preliminary.istio.io/blog/2018/egress-mongo/ for TCP traffic.
