### ISSUE TITLE
Prow Unit Tests broken after container upgrade

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#9032]
**Describe the bug**
From Slack
```
Sebastien Vas [1:53 AM]
Help needed, So I updated prow jobs with new container, and istio-unit test is failing. I am not sure I undertsand the reason, once says that its unauthorized to create a ns, and I am not sure I understand the other one, but it might be something related.
here is a sample failure: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/8476/istio-unit-tests/14272#istioioistiomixerpkgconfigstore-testfsstore2robust

Sebastien Vas [2:01 AM]
note that KUBECONFIG is set and pointing the right cluster. Not really sure why namespace creation would fail. The only way it could fail would be if it was trying to create a ns in the prow cluster.
```
**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by sebastienvas** [comment]
#9026 Added to skip failing test. While work for a resolution

**Comment by sebastienvas** [comment]
So the new container is indeed running as root.
