### ISSUE TITLE
No way to create config with type "policy" using MCP

### ISSUE THREAD

**Issue by peterhaochen47** [istio/istio#9034]
**Describe the bug**
When using MCP, we are sending an envelope containing objects of typeUrl: `type.googleapis.com/istio.authentication.v1alpha1.Policy`, which is the type URL for both "policy" and "mesh-policy". For example:

```go
builder := snap.NewInMemoryBuilder()
builder.Set("type.googleapis.com/istio.authentication.v1alpha1.Policy", "1", policyrules)
snapshot := builder.Build()
```
Where `policyrules` is an array containing the encoded `authentication.Policy` objects.

MCP will always translate the envelope into a config with type "mesh-policy": cURLing `/debug/configz` endpoint yields the following output:
```json
{
    "type": "mesh-policy",
    "group": "authentication",
    "version": "v1alpha1",
    "name": "default",
    "domain": "cluster.local",
    "creationTimestamp": "2018-09-26T23:06:38.474220367Z",
    "Spec": {
      "origins": [
        {
          "jwt": {
            "issuer": "testing@secure.istio.io",
            "jwks_uri": "https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json"
          }
        }
      ],
      "principal_binding": 1
    }
  }
```

In summary, because both "policy" and "mesh-policy" have the same typeUrl, and MCP only interprets this typeUrl as "mesh-policy", there is no way to create config with type "policy" using MCP.

**Expected behavior**
The ability to send an envelope to MCP that results in a config with type "policy".

**Steps to reproduce the bug**

1. Set up a MCP server
2. Send an envelope to MCP containing encoded `authentication.Policy` objects with typeUrl: `type.googleapis.com/istio.authentication.v1alpha1.Policy`
3. When cURL'ing `/debug/configz`, you will see a config of type "mesh-policy"

**Version**
Not using kubernetes, istio version 1.0.2

**Installation**
Using [Cloud Foundry Istio Release](https://github.com/cloudfoundry/istio-release) that packages Istio and Envoy.

**Environment**
GCP environment, using Cloud Foundry platform, Ubuntu.

**Cluster state**
n/a

**Comment by Nino-K** [comment]
Have you tried creating your MCP envelopes with Metadata name like the following format:
```
	yourEnvelope = []*mcp.Envelope{
		{
			Metadata: &mcp.Metadata{
				Name: "yourNamespace/name",
			},
			Resource: "your Marshalled resources",
		},
	}
```
When you define the metadata name in the format above ("namespace/name") mcp controller allows you to create an Authentication Policy model with type set to `policy`.
https://github.com/istio/istio/blob/8a84d6ddcadef0505f0678e99d65eff88ff0b496/pilot/pkg/config/coredatamodel/controller.go#L145

**Comment by ozevren** [comment]
@ayj, could you follow up.

**Comment by ayj** [comment]
What @Nino-K suggested is correct. You need to provide a namespace prefix of the form <namespace>/<name> for non-mesh scoped authentication policy.

**Comment by peterhaochen47** [comment]
I see. An empty "namespace" will result in a Policy envelope getting interpreted as MeshPolicy. 
We are intergrating Istio with a platform where "namespace" is not yet a clearly defined term, so we are still figuring this out. Thanks!
