### ISSUE TITLE
Connection problems with large deployments (1200+ pods)

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#9043]
**Updated Issue (12/30/18)**
---
_(Issue has been updated to reflect the current understanding of this problem, which is much improved since it was originally opened. See 10/1/18 edit in history for original text.)_

**Describe the bug**
Deployments become unstable as they grow in size with sidecars deployed. This manifests as one of the following 3 errors:
```
Readiness probe failed: HTTP probe failed with statuscode: 503
Liveness probe failed: HTTP probe failed with statuscode: 503
Liveness probe failed: Get http://10.41.128.12:9080/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
This appears to only happen on very large `Deployment` (1200+ pods), but it is regardless of instance count or size available in the cluster. I have tried with 15x m4.large, 20x m4.xlarge, 20x r4.xlarge, etc. The threshold for failure does not change. The other key point here is that the issue does not occur if there is no k8s `Service` on the deployment.

**Expected behavior**
Large Deployments do not have problems handling requests

**Steps to reproduce the bug**
1. Have a cluster that should easily handle 1500 pods (15-20 m4.xlarge is fine)
2. Install istio with the following values.yaml:
```
global:
  proxy:
    # Disable Mixer logging every request
    accessLogFile: ""
mixer:
  replicaCount: 3
  autoscaleMin: 3
  autoscaleMax: 10
pilot:
  replicaCount: 3
  autoscaleMin: 3
  autoscaleMax: 10
```
3. Label the `default` namespace with `istio-injection=enabled`
4. Create a simple http-listener deployment/service; I'll use bookinfo to keep it simple.
a. This should have 100 replicas, liveness/readiness probes, and set the resource claims to 0 to make things simple to test
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
spec:
  replicas: 100
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.8.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0
            memory: 0
        ports:
        - containerPort: 9080
        livenessProbe: &probe
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 9080
        readinessProbe:
          <<: *probe
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-v1
  labels:
    app: productpage-v1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
    version: v1
```
5. Apply the manifest to create the deployment and service
6. Wait for the pods to become `Running` and passing health checks
7. Increase the deployments by 100 and apply changes; repeat until 1200-1500 where you will see health checks start to fail on both old and new pods.

I want to go ahead and note here that separating the deployments into 100-200 pod chunks (I went to 9 deployments of 200 each for 1800 pods) seems to address the issue.

**Version**
Istio: 1.0.5
Kubernetes: 1.10.11

**Environment**
- New kops-built clusters to validate this issue on AWS (no other traffic) with Weave overlay
- Various instance sizes up to 20x r4.xlarge
- mTLS disabled
- All pods have `httpGet` liveness/readiness probes

** Other Notes**
- Liveness/Readiness probes are a way to see the problem reliably, but I imagine it would be similar for end-users hitting a service
- Removing Istio addresses stability problems
- Removing the `Service` from the deployments addresses stability problems
- Running 18 separate deployments of 100 pods each addresses stability problems (though I didn't test a shared service on all of them)
- Once a cluster gets into a busted state from a large deployment, scaling down won't fix it until I restart the masters
- Toying with the mixer HPA numbers does seem to alleviate the issue -- perhaps a larger deployment is heavier on mixer? With all the moving parts, I haven't nailed down a good test here... just speculation.

**Comment by mandarjog** [comment]
@costinm

**Comment by mandarjog** [comment]
1. What is the total amount of traffic in mesh? It is available in grafana on top left as global traffic.
2. What did logs from istio-proxy say in the pods that were dying? A pod that is not able to connect to pilot for any reason will show this behavior. Are there any config stream ended type messages?
3. You should do
Kubectl -n istio-system delete rules stdio  tcpstdio 
4. Ordinarily should not need so many instances. With Prometheus metrics and no stdout we need 0.4 vcpu per 1000 mesh requests.

**Comment by jaygorrell** [comment]
Thanks @mandarjog -- I'll spin up the test cluster today and get some answers on these.
1. I'll get the number when it starts failing but actual user traffic was 0... it was all from liveness probes.
2. The only thing I noticed was frequent 1000s instead of 200s from the http liveness probes. I still have all the logs in Splunk though but there's nothing with "config stream ended". 
3. Will definitely try this one - are there any pages in the docs that detail these defaults or when to remove them? Or a Helm option to suppress generating them?
4. Understood. So the cpu claims should be adjusted according to expected traffic using those numbers? This makes it sound like the default claims should be changed from 10m to 400m or something to prevent unnecessary HPA triggers.

**Comment by jaygorrell** [comment]
@mandarjog here's the traffic based on pod count (pods - ops):
```
5 - 0.5
100 - 45
200 - 91
300 - 137
400 - 181
500 - 225
600 - 275
700 - 322
800 - 371
900 - 418
1000 - 468
```

I did delete the two rules you mentioned and that had a significant impact and pushed the issue a bit higher in pod counts. Around 900 pods now, I start getting the issues... again regardless of host count. The actual effect is a mix of responses between `Client.Timeout exceeded while awaiting headers`, `dial tcp 100.119.0.53:9080: getsockopt: connection refused`, and just 404 responses often enough to cause some pods to die.

I did go back down to default HPA caps for this and here's what it looks like with 800 pods:
```
NAME                   REFERENCE                         TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
istio-egressgateway    Deployment/istio-egressgateway    50%/80%    1         5         1          4h
istio-ingressgateway   Deployment/istio-ingressgateway   50%/80%    1         5         1          4h
istio-pilot            Deployment/istio-pilot            48%/80%    3         10        3          4h
istio-policy           Deployment/istio-policy           96%/80%    3         10        10         4h
istio-telemetry        Deployment/istio-telemetry        305%/80%   3         10        10         4h
```

This definitely felt like a nice improvement... the limit was pushed up another 200 pods or so, but still hits similar issues at a higher volume.

**Comment by mandarjog** [comment]
Just to be clear, at 1000 pods, you see 468  rps traffic == (0.468 k ops) ? At that rate you will need  ( 0.468 * 0.4) 0.188 cpu cores for telemetry.

If the traffic is 468K rps then you will need full 188 cpu cores for telemetry. `8 x m4.2xlarge` only gives you 64 cpu cores.

@jaygorrell for large performance runs we use the following values.
https://github.com/istio/tools/blob/master/perf/twoPodTest/values-istio-auth.yaml
You should adjust the proxyv2 claims according to your traffic. Also disable access logs at the proxy like it is done in the values file.

I would also like to know the actual CPU being used by pilot, telemetry and policy.
`kubectl --namespace istio-system top pods --containers`

I have an additional dashboard under review, but you can install it in your grafana 
[from here](https://raw.githubusercontent.com/istio/istio/f913da7ce67a3c02cc7ea9bd36de5e5322a62447/install/kubernetes/helm/istio/charts/grafana/dashboards/istio-performance-dashboard.json)

**Comment by jaygorrell** [comment]
Thanks @mandarjog. That's correct, this was just 468 ops... not thousands. So we should be good on cpu. Since I've also tried everything from 9 to 22 instances and the issue happens around the same pod count, I don't believe I'm hitting any cpu/memory constraints on the cluster. I'll take a closer look though and get your questions answered.

The values file you linked is for a small pod count (2 cores per proxy) and isn't easily applied to this issue where it kicks in around 900 pods. The only other notable difference I see there is the usage of `accessLogFile: ""` vs `accessLogFile: "/dev/null"` which I assumed is the same but I'll give it a try.

If you have a reasonable environment at the ready, I'm curious if this issue is as reproducible as it seems for me. I assume there's nothing special about the liveness probes and that it's just simulating traffic (and really not _that_ much), as the ops shows.

Thanks for the help here - I'm excited to get this out into production once we work through the initial problems.

**Comment by jaygorrell** [comment]
900 Pods:
![screenshot 2018-10-04 13 46 12](https://user-images.githubusercontent.com/12174604/46492599-070fab00-c7dc-11e8-8b98-d838a26be4a8.png)

`kubectl --namespace istio-system top pods --containers`
```
POD                                         NAME                       CPU(cores)   MEMORY(bytes)
grafana-75485f89b9-bxhpq                    grafana                    9m           26Mi
istio-citadel-84fb7985bf-vq692              citadel                    0m           8Mi
istio-egressgateway-bd9fb967d-hs992         istio-proxy                5m           30Mi
istio-galley-655c4f9ccd-rnzqr               validator                  14m          12Mi
istio-ingressgateway-688865c5f7-lbj4g       istio-proxy                4m           29Mi
istio-pilot-74c5b54784-7629j                discovery                  584m         118Mi
istio-pilot-74c5b54784-7629j                istio-proxy                1m           16Mi
istio-pilot-74c5b54784-977wx                discovery                  206m         238Mi
istio-pilot-74c5b54784-977wx                istio-proxy                1m           16Mi
istio-pilot-74c5b54784-g5ncl                discovery                  49m          50Mi
istio-pilot-74c5b54784-g5ncl                istio-proxy                3m           16Mi
istio-pilot-74c5b54784-gzjmw                discovery                  784m         122Mi
istio-pilot-74c5b54784-gzjmw                istio-proxy                2m           16Mi
istio-pilot-74c5b54784-qt8s4                discovery                  187m         229Mi
istio-pilot-74c5b54784-qt8s4                istio-proxy                2m           16Mi
istio-pilot-74c5b54784-t8zqt                discovery                  190m         227Mi
istio-pilot-74c5b54784-t8zqt                istio-proxy                3m           16Mi
istio-pilot-74c5b54784-z6lqs                discovery                  49m          53Mi
istio-pilot-74c5b54784-z6lqs                istio-proxy                2m           16Mi
istio-policy-6b9f4697d-7k2qn                mixer                      35m          405Mi
istio-policy-6b9f4697d-7k2qn                istio-proxy                7m           63Mi
istio-policy-6b9f4697d-9ktn4                mixer                      29m          376Mi
istio-policy-6b9f4697d-9ktn4                istio-proxy                6m           63Mi
istio-policy-6b9f4697d-9rqsb                mixer                      21m          248Mi
istio-policy-6b9f4697d-9rqsb                istio-proxy                8m           62Mi
istio-policy-6b9f4697d-h86ts                mixer                      31m          377Mi
istio-policy-6b9f4697d-h86ts                istio-proxy                7m           64Mi
istio-policy-6b9f4697d-m9vmk                mixer                      31m          363Mi
istio-policy-6b9f4697d-m9vmk                istio-proxy                8m           61Mi
istio-policy-6b9f4697d-pmfsh                mixer                      20m          247Mi
istio-policy-6b9f4697d-pmfsh                istio-proxy                7m           61Mi
istio-policy-6b9f4697d-tgbtc                mixer                      26m          375Mi
istio-policy-6b9f4697d-tgbtc                istio-proxy                8m           63Mi
istio-policy-6b9f4697d-wvskw                istio-proxy                7m           38Mi
istio-policy-6b9f4697d-wvskw                mixer                      20m          248Mi
istio-policy-6b9f4697d-zfhb5                mixer                      20m          292Mi
istio-policy-6b9f4697d-zfhb5                istio-proxy                6m           61Mi
istio-policy-6b9f4697d-zq25n                mixer                      21m          245Mi
istio-policy-6b9f4697d-zq25n                istio-proxy                7m           50Mi
istio-sidecar-injector-8975849b4-7p77x      sidecar-injector-webhook   15m          8Mi
istio-statsd-prom-bridge-7f44bb5ddb-2q9d6   statsd-prom-bridge         832m         428Mi
istio-telemetry-6b5579595f-49k2h            istio-proxy                19m          78Mi
istio-telemetry-6b5579595f-49k2h            mixer                      59m          491Mi
istio-telemetry-6b5579595f-7bb79            mixer                      89m          686Mi
istio-telemetry-6b5579595f-7bb79            istio-proxy                23m          79Mi
istio-telemetry-6b5579595f-d6tgp            mixer                      69m          424Mi
istio-telemetry-6b5579595f-d6tgp            istio-proxy                18m          79Mi
istio-telemetry-6b5579595f-d8vgq            mixer                      49m          401Mi
istio-telemetry-6b5579595f-d8vgq            istio-proxy                20m          78Mi
istio-telemetry-6b5579595f-l9z48            istio-proxy                18m          79Mi
istio-telemetry-6b5579595f-l9z48            mixer                      57m          437Mi
istio-telemetry-6b5579595f-p2rzj            mixer                      72m          551Mi
istio-telemetry-6b5579595f-p2rzj            istio-proxy                16m          79Mi
istio-telemetry-6b5579595f-pq9wx            istio-proxy                17m          80Mi
istio-telemetry-6b5579595f-pq9wx            mixer                      58m          407Mi
istio-telemetry-6b5579595f-pr28z            mixer                      56m          398Mi
istio-telemetry-6b5579595f-pr28z            istio-proxy                15m          79Mi
istio-telemetry-6b5579595f-rtr99            mixer                      81m          587Mi
istio-telemetry-6b5579595f-rtr99            istio-proxy                18m          80Mi
istio-telemetry-6b5579595f-sm5cw            mixer                      66m          468Mi
istio-telemetry-6b5579595f-sm5cw            istio-proxy                19m          79Mi
prometheus-84bd4b9796-shxc9                 prometheus                 496m         2009Mi```

**Comment by jaygorrell** [comment]
I tried a few more things here to debug today:

I started looking through major differences in `istio-1.1.0.snapshot.1` to see what else I could try and noticed `envoyStatsd` was removed so I tried disabling that since it had some pretty large cpu fluctuations. No luck, similar results.

I then tried changing the deployment to only have a livenessProbe (dropped the readiness probe) since that's the main thing I'm concerned about and the results were promising. It still means there's a bottleneck somewhere as 900 pods doing liveness + readiness checks is making something choke -- but again, removing the sidecar addresses that problem so it's an interaction with Istio somewhere.

Finally I tried the full `istio-1.1.0.snapshot.1` release... the results there look very promising. Here is a screenshot with the exact same configuration as my last screenshot, except on the new version (added bonus of columns being fixed too):
![screenshot 2018-10-06 23 29 04](https://user-images.githubusercontent.com/12174604/46577914-a771f500-c9bf-11e8-8ba7-639f0e04a0a2.png)

In addition to the stability while at 900 pods, it was taking me about 2 hours on 1.0.2 for each test to slowly add 100 pods at a time, as anything too fast would cause health checks to choke and pods would hit multiple restarts before coming up. On 1.0.2 without a readiness check (only liveness) this was much faster, but on `1.1.0.snapshot.1` it's even faster still -- and that's with both liveness and readiness checks in place ... and with the default rules running.

Something in `1.1.0.snapshot.1` had a huge impact here. I'm fine moving to it but does anyone have any ideas what the difference-maker was here? I'd be happy to re-test 1.0.2 with an identified change given this info.

cc: @mandarjog

**Comment by jaygorrell** [comment]
I just tried 1.0.3 to see if there were any improvements here with no luck. It's actually a bit worse.

Info:
- Brand-new k8s cluster
- Only changes: `enableTracing: false`, `accessLogFile: ""`, and grafana enabled
- Added liveness and readiness probes to bookinfo's productpage-v1 deployment

From there, I deployed 100 pods with no problem. I bumped it to 200 and already saw some pod restarts from probe failures. I then went to 250 and about 20 of the pods restarted 6+ times before finally becoming healthy:
```
productpage-v1-847b985594-rvqp2   1/2       CrashLoopBackOff   6          9m
productpage-v1-847b985594-vp2vl   1/2       CrashLoopBackOff   6          9m
productpage-v1-847b985594-w79sq   1/2       CrashLoopBackOff   6          9m
productpage-v1-847b985594-xgwjh   1/2       CrashLoopBackOff   6          9m
productpage-v1-847b985594-xxhtw   1/2       CrashLoopBackOff   6          9m
productpage-v1-847b985594-z247m   1/2       CrashLoopBackOff   6          9m
```

One thing I did notice that changed is that I was getting 404s from the probes initially when new pods came up but the bulk of the errors came from 503s shortly after. On 1.0.3 it appears that the 503s are gone and it's the 404s that take longer to shake out.

You can see the results of the problem immediately now that the dashboard is working again:
![screenshot 2018-11-02 21 14 49](https://user-images.githubusercontent.com/12174604/47946615-5f71bf80-dee4-11e8-8f1e-1fad15a6ad73.png)

If it helps, here's a snapshot of the HPA numbers with 250 pods
```
NAMESPACE      NAME                   REFERENCE                         TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
istio-system   istio-egressgateway    Deployment/istio-egressgateway    30%/80%    1         5         1          24m
istio-system   istio-ingressgateway   Deployment/istio-ingressgateway   30%/80%    1         5         1          24m
istio-system   istio-pilot            Deployment/istio-pilot            28%/80%    1         5         1          24m
istio-system   istio-policy           Deployment/istio-policy           63%/80%    1         5         3          24m
istio-system   istio-telemetry        Deployment/istio-telemetry        200%/80%   1         5         5          24m
```

I definitely see the pilot improvements at least so that's a nice change.

**Comment by mandarjog** [comment]
If possible can you export mixer and mesh and performance dashboards to raintank?

In my large cluster I run with 500 to 1000 pods and things are fine .

**Comment by jaygorrell** [comment]
Mixer: https://snapshot.raintank.io/dashboard/snapshot/5iVsHizfKmb6cQOsLtd6Efz98T7RF5Ji?orgId=2
Mesh: https://snapshot.raintank.io/dashboard/snapshot/wwqcMwjvjg4qglRpG9SH9q7h0y6JeBsE?orgId=2
Performance: https://snapshot.raintank.io/dashboard/snapshot/9tmOuPh4tvJh524U9g0ZjE16Em7Ptj3N?orgId=2

It seems like the 500s on the dashboard are only during the initial pod creation when adding another 50-100, however once it returns to 100% success rate on the mesh dashboard, pods continue to restart and fail liveness probes for quite some time (up to 15-20 minutes).

**Comment by mandarjog** [comment]
https://github.com/istio/tools/blob/master/perf/servicegraph/values.yaml

This is the performance test. It is modular per namespace and uses about 20 services with 3 pods each. They use readiness probe.  Then we create 10 to 20 such name spaces.

**Comment by jaygorrell** [comment]
Interesting. Can you see anything that would cause a difference with my test? I'd ignore it, but I get the same results in a real environment. Would love to see if you're able to reproduce it and isolate the difference.

**Comment by jaygorrell** [comment]
@mandarjog can you give me a bit more info about that environment? I'm trying to help isolate this because I can reproduce it every time with new clusters. Anything that could be helpful... instance sizes, network overlays, etc.

There also seems to be two different things here:
1. Deploying 200-300 pods at once causes dozens of them to hit multiple restarts before things settle.
2. Once things are settled, occasional http health check failures happen but only at larger pod counts.

The second issue is quite a bit better than 1.0.2 but still present... the first issue seems just as bad. It happens with 100 pods too but not as easy to see. Can you reproduce that one by chance?

**Comment by jaygorrell** [comment]
I've been debugging this as much as I can in my spare time. The first issue was just choking the pilot -- it settles down after deployments and scales back to 1 by default so throwing 200 pods at at time will cause lots of health check failures until it catches up but setting the HPA minimum to 3 fixes this.

For the main issue, I found that Kubernetes services are another factor here. Here are some of the test results, starting with the original test:
```
1 deployment of 600-800 pods, 1 service: Liveness/Readiness probe failures
12 deployments of 100 pods, 12 services: Liveness/Readiness probe failures
1 deployment of 1200 pods, 0 services: No issues
12 deployments of 100 pods, 0 services: No issues
```

Does this help point to something I can dig deeper into?

**Comment by jaygorrell** [comment]
@costinm I'm happy to test a release with #7665 when it's available. Does that fix fit the scenario that it seems to only be a problem when k8s services are on the pods?

**Comment by nmittler** [comment]
@costinm could you provide an update?

**Comment by jaygorrell** [comment]
I just edited the original post to represent what the current status of this issue is (as of 1.0.5) with some new details. Would still be happy to test the above changes to see the impact there when it's available.

**Comment by nea1** [comment]
@jaygorrell We've been refocused on other projects so we haven't revisited this in anger. I was initially thinking that we would hold out for the 1.1.0 release, however it looks like 1.0.5 is worth trying. I'll be sure to update you if we give it a go.

**Comment by costinm** [comment]
Update: Sidecar is in and if used should solve this problem. Requires that each namespace creates a Sidecar resource and deps to other namespaces are listed. We are starting to test the limits and close the bug once we verified with ~3000 services and ~6000 pods.

**Comment by jaygorrell** [comment]
@costinm Can you clarify what "sidecar is in" means here? From context, this sounds really promising though!

**Comment by ZackButcher** [comment]
He means the new [`Sidecar`](https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#Sidecar) resource, and accompanying [`export_to` fields](https://github.com/istio/api/blob/release-1.1/mesh/v1alpha1/config.proto#L220-L260), which lets you restrict what config gets sent to each set of sidecars (that link is the mesh wide default, similar fields exist on each resource: [VirtualService](https://github.com/istio/api/blob/release-1.1/networking/v1alpha3/virtual_service.proto#L180-L192), [DestinationRule](https://github.com/istio/api/blob/release-1.1/networking/v1alpha3/destination_rule.proto#L122-L125), [ServiceEntry](https://github.com/istio/api/blob/5945a02236f53ad860d518772f730594709b1234/networking/v1alpha3/service_entry.proto#L474-L490)). See the docs (I'll check and see why the `export_to` fields are still hidden), but to help your scale problem:
- Write a `Sidecar` for each namespace in your deployment. In each namespace, include services (or whole namespaces) you need to call out to in the `egress` clause.
  ```yaml
  # This restricts the clusters and endpoints sent to Envoys in the `foo` namespace
  # to just other services in the same namespace, every service in the `baz` namespace,
  # and the `bang` service from the `bar` namespace.
  apiVersion: networking.istio.io/v1alpha3
  kind: Sidecar
  metadata:
    name: default
    namespace: foo
  spec:
    egress:
    - hosts:
      - "bar/bang.bar.svc.cluster.local"
      - "baz/*"
  ```
  `Sidecar`s are opt-in per namespace, so just setting it up for the few large apps may be enough. However, if large sets of services need to communicate there may still be issues.

- After creating `Sidecar`s, set the `defaultServiceExportTo` of the field `MeshConfig` to `"."` make service namespace-private by default. Then they'll only be visible by configuring them via a sidecar.

Order is important here: sidecars will not be able to route traffic to services that are not visible, so setting the default before creating `Sidecar`s for each namespace will break cross-namespace traffic in apps with Istio sidecars deployed.

**Comment by costinm** [comment]
Last tests from Mandar seem to confirm this is no longer a problem, as long as Isolation (Sidecar crd) is used.
