### ISSUE TITLE
http to https with   ACM (AWS certificate).

### ISSUE THREAD

**Issue by naveeng68** [istio/istio#9057]
Hi, Could you please add feature to redirect http to https with   ACM (AWS certificate).
Like ingress controller we can give below conf to use ACM certificate.

like in ingress controller I passes in ingress service.yaml below surf:

kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-support
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {‌{AWS_Cert_ARN}}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
-------------
config.yaml
------------
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-support
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
data:
  use-proxy-protocol: "false"
  proxy-buffer-size: "6k"

So please add above feature.

**Comment by Pajk** [comment]
Duplicate of #6566 ?

**Comment by eduardobaitello** [comment]
@naveeng68 [my comment](https://github.com/istio/istio/issues/6566#issuecomment-428914509) on #6566 do not solve your problem?

If you managed it to work would be nice to close this issue  :)
