### ISSUE TITLE
Make Galley configuration metadata dynamically loadable

### ISSUE THREAD

**Issue by ayj** [istio/istio#9063]
Galley currently loads configuration resource metadata from a [hardcoded](https://github.com/istio/istio/blob/master/galley/pkg/metadata/types.go) [list](https://github.com/istio/istio/blob/master/galley/pkg/metadata/kube/types.go). Galley must be re-built and re-started to change per-resource metadata, e.g. group, version, kind. Instead of hardcoding this metadata, Galley can load it from a local file to allow for fine adjustments to Group/Version/Kind.

**Comment by ayj** [comment]
CRD installation is conditional on presence of Pilot, Security, and Mixer being enabled (see below). Galley's dynamic config metadata may need to be similarly conditional on feature APIs.

https://github.com/istio/istio/blob/3378c01f98d1b5b284b022483ac0cd83f6f3eb0f/install/kubernetes/helm/istio/templates/crds.yaml#L3
https://github.com/istio/istio/blob/3378c01f98d1b5b284b022483ac0cd83f6f3eb0f/install/kubernetes/helm/istio/templates/crds.yaml#L149
https://github.com/istio/istio/blob/3378c01f98d1b5b284b022483ac0cd83f6f3eb0f/install/kubernetes/helm/istio/templates/crds.yaml#L199

**Comment by ozevren** [comment]
Currently, the metadata is an embedded metadata.yaml file. It is relatively straightforward to make this an external config file now.

**Comment by howardjohn** [comment]
Given galley is removed I think  this is no longer relevant
