### ISSUE TITLE
replace Service Graph with Kiali

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#9066]
**Describe the feature request**

The Policies and Telemetry WG and the Tech. Oversight Committee voted to approve the replacement of Service Graph with Kiali. See the [proposal document here](https://docs.google.com/document/d/1k7_U7ioZ8-BjRkZWP2fojsX0kaPQW1YgJEuwqDerEvU/edit?ts=5baa9c99#)

This issue is to document this feature request.

As per the proposal document, some things that need to get done for the initial implementation of this feature request are as follows:

- [x] Add to Istio Ansible (https://github.com/istio/istio/pull/9069 (**merged**))
- [x] Add to Istio Helm Chart (https://github.com/istio/istio/pull/9084 (**merged**))
- [x] Add to Istio demo yamls (https://github.com/istio/istio/pull/9084 (**merged**))
- [x] Add Kiali to gateway/virtual service in the telemetry-gateway (https://github.com/istio/istio/pull/8971 (**merged**))
- [x] Make a note in the existing Service Graph README to indicate it is deprecated (https://github.com/istio/istio/pull/9094 (**merged**))
- [x] New version of Kiali was released - we want to install that version (https://github.com/istio/istio/pull/9230 (**merged**))
- [x] Add Kiali Task to Istio documentation and deprecate Service Graph Task docs (https://github.com/istio/istio.io/pull/2715) (**merged**)

**Comment by jmazzitelli** [comment]
PR to add Kiali task is found here: https://github.com/istio/istio.io/pull/2715

**Comment by jmazzitelli** [comment]
PR to update Ansible installer is found here: https://github.com/istio/istio/pull/9069

**Comment by jmazzitelli** [comment]
@jeffmendoza in the [proposal document](https://docs.google.com/document/d/1k7_U7ioZ8-BjRkZWP2fojsX0kaPQW1YgJEuwqDerEvU/edit?ts=5baa9c99#) we have this:

```
The existing Service Graph readme will note that it is deprecated.
To be done by: jeffmendoza@google.com
```

That is the last action item in this issue that needs to be started. Are you going to create a PR on this, or do you want me to do it? I assume it would simply involve added a deprecation notice on the top of the [Service Graph README.md](https://github.com/istio/istio/blob/master/addons/servicegraph/README.md) file.

**Comment by jeffmendoza** [comment]
Good to hear everything is moving along. I'll open the PR tomorrow morning.

**Comment by jmazzitelli** [comment]
FYI: all Istio code PRs are merged. Only thing left to do before this is considered complete is for a review/approval/merge of the Task documentation - https://github.com/istio/istio.io/pull/2715

**Comment by jmazzitelli** [comment]
All PRs are merged, this issue can be closed.

**Comment by sdake** [comment]
closing at @jmazzitelli 'z request.
