### ISSUE TITLE
[test-framework] local mixer depends on helm

### ISSUE THREAD

**Issue by nmittler** [istio/istio#9070]
I just ran into this on a new machine with no k8s setup. Running a local pilot test crashed because helm wasn't installed. The offending line in the local mixer is the call to `deployment.ExtractAttributeManifest()`.

**Comment by ozevren** [comment]
Helm is supposed to be setup during developer environment setup, right?

Without this, we need to make a snapshot copy of the attribute manifests, which will be prone to going out of sync.

**Comment by nmittler** [comment]
@ozevren I don't think we want to require that for out-of-the box local testing. Making a snapshot will be a bit of a maintenance burden, but it's better for developer experience.

**Comment by ozevren** [comment]
The problem with the developer experience is, when it goes out of sync, it is likely that it will be a failure point in somebody's attempt to write tests. It will be very hard to diagnose what is going on and fix it (i.e. recreate the snapshot).

Helm being missing is very easy to spot and fix. It should be a non-issue, especially for someone following the dev guide (if it is not there, we should definitely add it). It is not different than having to have docker (which we currently use to ensure stable builds, by adding calling some version-pegged developer tools, such as protoc).

**Comment by nmittler** [comment]
If it goes out-of-sync, how much of a concern is this for local tests? And if it does go out-of-sync, wouldn't the offending PR also fail?

**Comment by ozevren** [comment]
When it goes out of sync, how do you diagnose it? It will be a head scratcher.

Generating it from the source of truth every time completely avoids the issue.

**Comment by nmittler** [comment]
It does, but it also requires that you follow the Istio steps for setting up helm.  If I have a fresh environment and I just want to build and test Istio for the first time, I shouldn't need anything beyond Golang.

**Comment by ozevren** [comment]
You already need Docker (and a slew of other things, which (scarily) might be getting installed without your consent). I don't think it is a big ask from the developers to have that.

As a compromise, we can extract the attribute manifest resource to its own template, and we can generate it directly without using Helm.

**Comment by nmittler** [comment]
You also shouldn't need docker for running locally. Most of the tools are going to be for the k8s environment.  One of the main advantages of the new framework is to simplify the developer experience (in particular the getting-started experience). The fewer extra steps in the setup, the better ... especially if they don't make obvious sense for running things locally.

> As a compromise, we can extract the attribute manifest resource to its own template, and we can generate it directly without using Helm.

That seems reasonable.
