### ISSUE TITLE
Helm value to configure affinity, and tolerations

### ISSUE THREAD

**Issue by MrSaints** [istio/istio#9074]
**Describe the feature request**

I'd like to bounce the idea of introducing new Helm "values" for setting the `affinity`, and `tolerations` for various deployments.

Our use-case for this is to _control_ where certain deployments are placed across our node pools.
There are certain deployments in Istio which we would consider as higher priority than others. As such, we may have a preference for placing them in larger or more resilient instances.
Other deployments such as Grafana, may not be _customer facing_, and we would consider them as lower priority, probably even placing them in node pool with preemptible nodes.

**Describe alternatives you've considered**

We currently use Helm via `helm template` for more visibility, and control. In theory, we can simply "patch" the generated yml files after generation. That way, we can have upstream updates, while still applying our own `spec` - namely, affinity, and tolerations. Though this is a consideration, we would prefer if such a configuration option was made first-class so as to reduce the number of steps needed.

**Additional context**

Somewhat related to: https://github.com/istio/istio/issues/7330

I'd be happy to make a PR if this sounds appropriate. Otherwise, I'm open to alternatives besides the aforementioned.

**Comment by sdake** [comment]
@MrSaints I don't see any issue with a PR that doesn't change the default behavior (which is extremely well tested) with a few configuration options for this use case.
