### ISSUE TITLE
Upgrade kiali to version 0.8

### ISSUE THREAD

**Issue by clyang82** [istio/istio#9079]
**Describe the feature request**
Kiali supports customized context path in the latest release - v0.8.
for more details, refer to https://github.com/kiali/kiali/issues/526

**Comment by jmazzitelli** [comment]
Yes, this is being worked on - ansible installer upgraded: https://github.com/istio/istio/pull/9069

See this issue where the work will be getting done: https://github.com/istio/istio/issues/9066

**Comment by gyliu513** [comment]
Cool, thanks @jmazzitelli and @clyang82
