### ISSUE TITLE
Cherrypick #7944 back to master

### ISSUE THREAD

**Issue by hklai** [istio/istio#9098]
https://github.com/istio/istio/pull/7944 was merged to release-1.0 but it apparently was not merged to master (i.e. 1.1 and after).

A simple cherry-pick is no longer possible to due merge conflicts. Please help:

1. Check if it is needed is master.
2. If so, please cherry-pick and resolve conflicts.

**Comment by douglas-reid** [comment]
I believe this is needed in master. I will work on the cherry-pick.
