### ISSUE TITLE
Cherrypick #8138 back to master

### ISSUE THREAD

**Issue by hklai** [istio/istio#9102]
#8138 was merged to release-1.0 but it apparently was not merged to master (i.e. 1.1 and after).

A simple cherry-pick is no longer possible to due merge conflicts. Please help:

1. Check if it is needed is master.
2. If so, please cherry-pick and resolve conflicts.

**Comment by ibm-jason** [comment]
/cc @hklai - Hi there! 👋 

New to the community, and I'm looking for things to tackle. Is this still a valid task?

**Comment by hklai** [comment]
I believe so. Feel free to spend some time to do some investigstion first.

**Comment by ibm-jason** [comment]
Not sure if this is relevant anymore. @hklai, @costinm - thoughts?

**Comment by howardjohn** [comment]
I believe we have all the changes here we need in master
