### ISSUE TITLE
Host Header Limitation/Advice

### ISSUE THREAD

**Issue by Stono** [istio/istio#9107]
Hey, 
I wouldn't say this is a bug, _per-se_, but it feels like something I shouldn't need to worry about if a service mesh was truly transparent.  I'm hoping someone can help / suggest some options that I'm perhaps missing.

Take this simple example, a user makes a request say to `www.example.com`, that hits nginx and nginx reverse proxies that request to app.  App receives that request with the header `Host: www.example.com`.  App happens to do lots of operations which are dependent on the value of `Host` being `www.example.com.

[ user ] -> [ nginx ] -> [ app ]

Now if you stick istio-proxy into the mix, it kind of looks like this:

[ user ] -> [ nginx | istio-proxy ] -> [ istio-proxy | app ]

The difference is, in order for the user request to `www.example.com` to be successfully routed by `istio-proxy` to `app`, it needs to use the service upstream rewrite `Host: app.default.svc.cluster.local`, because we cannot let nginx directly access `app` by its IP as `istio-proxy` will throw a 503.

So the question is, at a high level, how can I ensure that `app` receives `Host: www.example.com`?  

Is there a way I can tell the `istio-proxy` on the `nginx` side the name of the target upstream service?  like `x-envoy-upstream` or something like that, so I don't have to touch `Host`?  Perhaps https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#envoy-api-field-cluster-originaldstlbconfig-use-http-header - it doesn't seem to work so i guess `use_http_header` is false, does anyone know a way I can enable this?

I'm really open to suggestion as the need to always use the correct service name in the `Host` header is becoming quite a limitation for us.

**Comment by Stono** [comment]
Not sure how that helps?  Are you suggesting rewriting the Host header with the contents of X-Forwarded-Host?

**Comment by rshriram** [comment]
okay I am confused. can you show me a partial nginx config that causes the Host header to be rewritten to some internal service? There is no restriction in the inbound path on the hostname.. we allow wildcard `*`

**Comment by Stono** [comment]
I actually think I'm getting somewhere now... if I modify my `VirtualService` to have host entries for the external addresses:

```
  hosts:
  - app
  - www.example.com
```

And then leave nginx to send requests to the pod ip's directly, rather than to the service ip it works.  This is less than optimal really as it means nginx is constantly watching for pods rather than just using the service address.  I might get some input from the nginx guys about their `use-service-upstream` option.

**Comment by Stono** [comment]
OK for others coming across this problem (as I know a few people are doing nginx and istio)...

Just use: `nginx.ingress.kubernetes.io/service-upstream: "true"` and NOT `nginx.ingress.kubernetes.io/upstream-vhost`, and then in your VirtualService ensure you have the external `fqdn` in the `hosts` section and voila, istio compatible nginx.

**Comment by dvlato** [comment]
We are using an nginx-ingress to do the routing based on path and never change the Host: header (so it is example.com for all our apps).  That works perfectly fine for us right now.

 If we started intercepting inbound traffic with Istio in app1, the request would go to the envoy proxy who has to forward it to the app.  What is it used to do this 'internal forwarding'? It seems to be the "Host: " header, but we don't want modify that one as it is needed by the backendapps and we were expecting that istio would be transparent so we don't need to change our infrastructure to integrate istio. Is the host header really required?   From @Stono message it seems that using 'service-upstream' to use the Service IP would work...but I wonder if that's needed!  In this case he also mentioned we might have to modify some 'VirtualService' but I was expecting that we'd be able to inject istio transparently.  Can you please elaborate ?

**Comment by deiwin** [comment]
Any updates on the "multiple (k8s) `Services` using the same external FQDN" question? We're in the same boat and wouldn't want to repeat all the routing in a single `VirtualService`. @Stono, was this ever a problem for you?

**Comment by xeor** [comment]
I'm trying to find a solution to this as well. The problem is still around, but is there s workaround yet?

**Comment by maciej-orba** [comment]
+1
