### ISSUE TITLE
Istio not reporting https traces to jaeger 

### ISSUE THREAD

**Issue by kuberkaul** [istio/istio#9142]
**Describe the bug**
We have an container running with envoy sidecar proxy with service/deployment for port 443 using istio's own example : sample/https/nginx . We can curl the container to get nginx page just fine but see absolutely no traces in jaeger for https calls. We see http calls in jaeger as soon as we swich the port to 80 in deployment/service 

**Expected behavior**
We should see traces for both http/https calls to container. 

**Steps to reproduce the bug**
- create nginx config :  https://github.com/istio/istio/blob/master/samples/https/nginx-app.yaml
- Create nginx deployment : kubectl apply -f <(istioctl kube-inject -f nginx.yaml) 
- curl -kv https://service-ip gives 200
- no traces in jaeger for https

**Version**
```
istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

[root@ip-10-147-5-150 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
- kubectl apply -f install/kubernetes/helm/helm-service-account.yaml
- helm init --service-account tiller
- helm install install/kubernetes/helm/istio --name istio --namespace istio-system
- helm upgrade --set tracing.enabled=true --set servicegraph.enabled=true --set global.configValidation=false istio install/kubernetes/helm/istio
```

**Environment**
- Running this within AWS EKS

**Cluster state**
- Attached 
[archite.tar.gz](https://github.com/istio/istio/files/2448004/archite.tar.gz)

**Comment by objectiser** [comment]
The problem is probably due to the port name, see https://istio.io/help/faq/traffic-management/#naming-port-convention

If you leave the port as 443, but change the name from `https` to `http`, it should work.

**Comment by kuberkaul** [comment]
@objectiser Im using istio -1.0.2 which supports https out of the container so I thought it should be good right especially since they have the same in istio docs themselves ..

Anyhow if I switch to `http-secure` for 443 I get following :

```
curl -kv https://10.147.6.197
* About to connect() to 10.147.6.197 port 443 (#0)
*   Trying 10.147.6.197...
* Connected to 10.147.6.197 (10.147.6.197) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.
```
I believe because istio is sending this as http ?

**Comment by objectiser** [comment]
I guess to be certain it would be worth changing the name to `https-secure` and seeing if that works again?

**Comment by kuberkaul** [comment]
@objectiser yup as soon as I switch to anything besides `http/http-` for the name , the curl works fine (200) but nothing on jaeger for trace.. Only request going on `http` show up on jaeger. E.g - if I have name `http` and I do :

```[root@ip-10-147-5-150 nginx]# curl -kv http://10.147.6.197:443
* About to connect() to 10.147.6.197 port 443 (#0)
*   Trying 10.147.6.197...
* Connected to 10.147.6.197 (10.147.6.197) port 443 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.147.6.197:443
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.11.3
< Date: Fri, 05 Oct 2018 13:11:19 GMT
< Content-Type: text/html
< Content-Length: 271
< Connection: close
<
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.11.3</center>
</body>
</html>
* Closing connection 0
```

fails but I see this trace on jaeger but nothing with https.

**Comment by kuberkaul** [comment]
<img width="408" alt="screen shot 2018-10-05 at 9 15 42 am" src="https://user-images.githubusercontent.com/2179966/46537423-45aa7180-c87f-11e8-85bf-23e838a14985.png">

**Comment by objectiser** [comment]
Looking at some of the code it looks like https is being treated differently to http/http2: https://github.com/istio/istio/blob/master/pilot/pkg/model/service.go#L228 - unclear why https is included in the `IsTCP` method instead of `IsHTTP`? Possibly one of the core maintainers can explain.

I tried to reproduce the problem using your instructions but it was missing the configmap `nginxconfigmap` - could you include a reference to it, or paste here?

**Comment by kuberkaul** [comment]
@objectiser  - yup its also in the sample of istio docs : https://github.com/istio/istio/blob/master/samples/https/nginx-app.yaml

but from within mesh :

```
[root@ip-10-147-5-150 centos]# kubectl get  configmaps nginxconfigmap -o yaml
apiVersion: v1
data:
  default.conf: |
    server {
            listen 443 ssl;

            root /usr/share/nginx/html;
            index index.html;

            server_name localhost;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2018-10-03T02:30:39Z
  name: nginxconfigmap
  namespace: default
  resourceVersion: "5401207"
  selfLink: /api/v1/namespaces/default/configmaps/nginxconfigmap
  uid: 517c2800-c6b4-11e8-920e-0ea3efceb3e6
```

**Comment by objectiser** [comment]
Ok thanks - might not be able to try it out until next week - but hopefully someone else may know more information.

**Comment by kuberkaul** [comment]
@geeknoid @kyessenov ^ any input here ?

**Comment by kyessenov** [comment]
HTTPS is treated as TCP if it is not originated by istio, since it's completely opaque to istio (by design). We can only trace requests if we originate/terminate encrypted traffic.

**Comment by kuberkaul** [comment]
@kyessenov Does that mean all istio traffic management features (traffic shaping/fault injection/delay) wont work with https ? it completely bypasses envoy ?

**Comment by kuberkaul** [comment]
so in essence you ned to have http coming out of your container and envoy can terminate SSL  for https ?

**Comment by clyang82** [comment]
I met the same problem in IBM Private Cloud environment. When I inject the sidecar into the kibana deployment. And then perform `curl` in the kibana container:

```
bash-4.2$ curl -k --cert ./curator.crt --key ./curator.key https://elasticsearch:9200/ -vvv
* About to connect() to elasticsearch port 9200 (#0)
*   Trying 10.0.111.104...
* Connected to elasticsearch (10.0.111.104) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.
```
@geeknoid @kyessenov @douglas-reid any input here? Thanks.

**Comment by douglas-reid** [comment]
@clyang82 Can you clarify what you would like input on?  Tracing with HTTPS ?  Or all Istio features with kibana+HTTPS?

**Comment by clyang82** [comment]
@douglas-reid Thanks for your response. I would like to 
1. Kibana can be able to start successfully - right now, Kibana cannot connect with es when enable sidecar
2. Tracing with HTTPS

**Comment by clyang82** [comment]
> https://github.com/istio/istio/issues/2306
note that egress service does not function as HTTP Proxy. It intercepts tcp traffic by iptables. So you cannot use it a HTTP proxy. The only solution I see currently is calling Cloudant directly - https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly.


I am not sure it is only solution or not so far. When I configured the elasticsearch ip address into `excludeIPRanges` of sidecar in Kibana pod. the Kibana can start normally.

**Comment by douglas-reid** [comment]
for 1: did you answer your own question with your follow-on question? 

for 2: please see @kyessenov 's explanation for tracing with HTTPS to the instance: https://github.com/istio/istio/issues/9142#issuecomment-427458450

**Comment by kuberkaul** [comment]
@clyang82 - You can't have HTTPS originating from your container if you wants istio to be able to trace your request all the way to the container. (won't be able to decrypt it and is fully opaque to istio). HTTP only from container and you can encrypt from envoy proxy using istio config. (this will be fully traceable via istio integrations)

**Comment by clyang82** [comment]
@douglas-reid @kuberkaul Thanks for your answers. It is clear for me now.

**Comment by kuberkaul** [comment]
for sure, an entry in FAQ would have saved me a lot of time.

**Comment by douglas-reid** [comment]
@linsun @kuberkaul @clyang82 @adriancole please take a look at a draft FAQ I put together this afternoon (added to the Istio community team drive): https://docs.google.com/document/d/1fHKozeDC1bQlY58dN2SP-IQxtD2TzZ0COOyRc7kcao4/edit#.

Would appreciate any and all comments before I send it off to the appropriate editors, etc.
