### ISSUE TITLE
Feature: Application liveness and readiness probes with mTLS is enabled.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#9150]
**Status**

all the PRs implementing the feature is now merged. You can wait for a daily build after 2019-0205 and follow instructions of https://preliminary.istio.io/help/ops/setup/app-health-check/#probe-rewrite to test. Please consider to provide feedback on how this feature works for your services to help us decide if we enable this by default, #10357

**FR description**

When mTLS is enabled http liveness and readiness probes do not work because the kubernetes prober does not have access to istio certificates. [Istio Standard health checks](https://docs.google.com/document/d/1RxO3IBT8z68XNmM8tGWxrUcSbrRneiBWlL1A4qZf3CU/edit#heading=h.x9snb54sjlu9) has more discussion on this issue.

In proxy readiness work, Proxy's readiness is handled by proxy agent on a dedicated ``readiness.status.sidecar.istio.io/applicationPorts`. We also plan to use status port on a dedicated path to service application readiness / liveness checks.

Steps when mTLS is enabled
1. Sidecar injector reads http liveness and readiness checks for application
    a. ensure that they are on the mtls enabled application port.
2. Sidecar injector rewrites pod spec to point the application probes to `proxy_agent:application_port/application/live` and  `proxy_agent:application_port/application/ready`
3. Pass the original probe paths to proxy agent as arguments  `--livenessPath`, `--readinessPath`
4. Ensure that these new arguments in `sidecar-injector-configmap.yaml` are placed inside the `statusPort` conditional. This ensures backwards compatibility.

**Comment by incfly** [comment]
Thanks for filing the bug. One thing I'd like to confirm:

> Steps when mTLS is enabled...

Since whether mTLS is turned on or not depends on runtime authn policy, I think it's okay to apply above steps for all injector, regardless whether mTLs is turned on or not, right? As long as we can make kubelet happy(it does not care the content AFAIK).

wdty?

**Comment by mandarjog** [comment]
Ok, makes sense. We can always rewrite the health check even when mtls is off.

**Comment by wattli** [comment]
Makes sense for always rewrite.

**Comment by hzxuzhonghu** [comment]
@incfly Can you update the outdated `--livenessPath, --readinessPath` flag ?

**Comment by incfly** [comment]
Unfortunately, `istioctl` and `webhook` auto inject use slightly different code path. https://github.com/istio/istio/pull/10175 only takes care of the `istioctl kube-inject`. We need some more work to support webhook later as well. Not sure why we have two code paths, which seems problematic... 

Regarding flag change, I'll add a config option in the `sidecarInjectionConfig` and let the injector to read from that config's option to decide whether to probe rewrite.

@costinm 
On top of that we can also consider a command line flag on `istioctl` to override the injection template, such that we can have customer to play with this feature on manual deployment based while having it default off at mesh level. 

[1] https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/webhook.go#L401
[2] https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/inject.go#L549

**Comment by incfly** [comment]
I take a look on the `integration2` test framework. It supports k8s deployments. However, I believe it's only relies on webhook auto injection [1]. We need to finish above work before being able to test that...

Will work on the auto injection support first.

[1] https://github.com/istio/istio/blob/master/pkg/test/framework/runtime/components/apps/kube.go#L102

**Comment by incfly** [comment]
Here're my thoughts on e2e test after some investigation.

- `integration2` framework only deploy apps thru webhook sidecar injector.
- Currently `istioctl kube-inject` and `webhook` injection has quite different  code path.

So my plan
- Add `istioctl kube-inject` as a new component for the test framework. Maybe as `DeployedIstioctl` (weird name but just for consistency...)
- Extend `apps` component's parameter to make it possible deployed through `istioctl` component.

@nmittler do you think that looks good to you for testing framework?

**Comment by nmittler** [comment]
@incfly yeah, let's just keep the test framework using webhook ... that's the long-term goal anyway. I like your idea about just unit testing istioctl.

**Comment by incfly** [comment]
/cc @mandarjog @hzxuzhonghu 

I think we have a security hole by using http header to pass the original application port to the pilot agent. Pilot agent does not check whether the seen path or port matches the config in `PodSpec.Container.Probe`. Anyone can send anything to the pod using `15020` with header configured. Even we strip out the body content, response code still reveals information and `POST` can even mutate the service state...

A intuitive fix is to go back original solution as passing probe info as command line flag to to pilot agent.

**Comment by hzxuzhonghu** [comment]
Why not only support `GET` ? As k8s probe only support `GET`.

**Comment by hzxuzhonghu** [comment]
>response code still reveals information 

Yeah, with `GET`, this can be even inevitable.  Passing probe path and port in as flags sounds a good solution.

**Comment by incfly** [comment]
Quote from @awly 

> Consider also restricting methods (only GET), body (no body) and headers.
IMO ideally only path and port are taken from incoming request, with restrictions.

Good point, since `HTTPGetAction` from k8s only allow GET request from kubelet anyway.

**Comment by smawson** [comment]
Has this been fixed? Can we close this out?

**Comment by wattli** [comment]
I believe so, but need @incfly to confirm

**Comment by ekarlso** [comment]
@incfly is it ready ?

**Comment by ekarlso** [comment]
And what about /metrics or alike?

**Comment by incfly** [comment]
@ekarlso The last PR is under review. Doc is ready in preliminary release, https://preliminary.istio.io/help/ops/setup/app-health-check/

What do you refer to by `/metrics`?

**Comment by ekarlso** [comment]
Prometheus scraping.

**Comment by incfly** [comment]
I don't think this FR will solve mTLs + Prometheus problem. That should be a separate solution.
@mandarjog might more context on that one.

**Comment by incfly** [comment]
For the folks caring about this feature, all the PRs implementing the feature is now merged. You can wait for a daily build after 2019-0205 and follow instructions of https://preliminary.istio.io/help/ops/setup/app-health-check/#probe-rewrite to test. Please consider to provide feedback on how this feature works for your services to help us decide if we enable this by default, https://github.com/istio/istio/issues/10357

**Comment by incfly** [comment]
The rest is e2e test and documentation improvements, I'll continue to work on it, but closing this one for now.

**Comment by ekarlso** [comment]
Hi guys, I am trying to use the rewrite approach with 

```      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz/ready
          port: 8080
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: nodejs
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
```

but 
  Warning  Unhealthy  3m               kubelet, aks-default-39479143-0  Liveness probe failed: Get http://10.244.0.208:8080/healthz/ready: read tcp 10.244.0.1:46374->10.244.0.208:8080: read: connection reset by peer


What am I doing wrong? Should the httpGet probe not work?

**Comment by incfly** [comment]
From the error message it seems like the prober is not written, still remains as what it is.

Did you turn on `sidecarInjectorWebhook.rewriteAppHTTPProbe=true` using Helm? Also this feature depends on istio-proxy version to be at 1.1. Older proxy does not work.

https://preliminary.istio.io/help/ops/setup/app-health-check/#probe-rewrite

**Comment by cscetbon** [comment]
Hey @incfly, I have the same issue and even setting that parameter does not help. I tried with and without MTLS and I get the same result :

`0s          Warning   Unhealthy           pod/my-pod-566ff945f9-vnsnh    Readiness probe failed: HTTP probe failed with statuscode: 503`

Here you can see that rewriteAppHTTPProbe is set :
```
helm get istio |grep -A 1 ^sidecarInjectorWebhook|head -2    
sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true
```

Any idea what could be wrong ?

**Comment by incfly** [comment]
@cscetbon  Can you try to deploy the liveness-http.yaml as https://github.com/istio/istio/blob/master/samples/health-check/liveness-http.yaml while enabling that flag? And see if that's working for you or not?

If yes, then we need to see if theres' something special about your container's probe defintion that we failed to cover.

**Comment by cscetbon** [comment]
@incfly no issue with your deployment. The weird thing is that my pod actually does not have an http probe but has an exec probe. Here is the content of the helm https://pastebin.com/BLic5NJg.

**Comment by cscetbon** [comment]
@incfly I've updated it at https://pastebin.com/XHGn7k7t cause there was a syntax error. You can use `--validate=false` when you apply it. I've found out that if I remove the **readinessProbe** key I still get this error which makes more sense as it's not an http probe. I've also tested without Istio and this probe is added by Istio :

```
Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      ....
      ISTIO_META_POD_NAME:           casskop-cassandra-k8s-operator-bff89b48-g5m6l (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   cassandra-e2e (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_LABELS:         {"app":"cassandra-k8s-operator","name":"cassandra-k8s-operator","operator":"cassandra","pod-template-hash":"bff89b48"}

      ISTIO_KUBE_APP_PROBERS:        {}
```

So I can't understand why and even if it's needed, why it does not work then ..

**Comment by incfly** [comment]
:15020 probes are not added to your cassandra container, it's added to `istio-proxy` container, Istio adds this prober to ensure the sidecar receives necessary envoy configuration in order to serve the request.

cassanra may have some known issues, unrelated to health check. I'm not sure what's the current status. I remembered theres' some known issues about Cassandra & Istio support in general, https://github.com/istio/istio/issues/10053.

**Comment by cscetbon** [comment]
@incfly but wait here there is no cassandra cluster at all. So it's only on that pod. I get it that it was added to the Istio container in that pod. But why is it failing because of that probe ? This is only a warning but seeing one pod running out of 2 makes me think that this is a problem
```
NAME                                            READY   STATUS    RESTARTS   AGE
casskop-cassandra-k8s-operator-bff89b48-g5m6l   1/2     Running   1          20m

Normal   Scheduled  20m                 default-scheduler     Successfully assigned cassandra-e2e/casskop-cassandra-k8s-operator-bff89b48-g5m6l to kube-node-1
  Normal   Pulled     20m                 kubelet, kube-node-1  Container image "docker.io/istio/proxy_init:1.1.7" already present on machine
  Normal   Created    20m                 kubelet, kube-node-1  Created container
  Normal   Started    20m                 kubelet, kube-node-1  Started container
  Normal   Started    20m                 kubelet, kube-node-1  Started container
  Normal   Pulled     20m                 kubelet, kube-node-1  Container image "docker.io/istio/proxyv2:1.1.7" already present on machine
  Normal   Created    20m                 kubelet, kube-node-1  Created container
  Normal   Pulled     20m (x2 over 20m)   kubelet, kube-node-1  Successfully pulled image "orangeopensource/cassandra-k8s-operator:0.3.1-service-dc"
  Normal   Created    20m (x2 over 20m)   kubelet, kube-node-1  Created container
  Normal   Pulling    20m (x2 over 20m)   kubelet, kube-node-1  pulling image "orangeopensource/cassandra-k8s-operator:0.3.1-service-dc"
  Normal   Started    20m (x2 over 20m)   kubelet, kube-node-1  Started container
  Warning  Unhealthy  19m (x11 over 20m)  kubelet, kube-node-1  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by cscetbon** [comment]
okay so I found that the issue was coming from an exposed port on the operator with no running server  on that port. Istio doesn't like it when there is no listener on a port that is supposed to be exported ... Don't know if it's a bug or not but that was the issue
