### ISSUE TITLE
Envoy memory leak on daily build master-20181004-09-15

### ISSUE THREAD

**Issue by jnativio** [istio/istio#9159]
**Describe the bug**
Envoy has a severe memory leak on build master-20181004-09-15 when under load. Both the ingressgateway instances and the sidecars showed a continuously increase on memory usage during the regression patrol run, up to the point of using almost 100% of the memory available in the worker node and causing failures.

![image](https://user-images.githubusercontent.com/18554027/46544486-ba86a700-c891-11e8-9d88-df39aacb6232.png)

![image](https://user-images.githubusercontent.com/18554027/46544584-00436f80-c892-11e8-8191-4645baf616bf.png)

**Expected behavior**
No memory leaks.

**Steps to reproduce the bug**
Install this build and drive load to it.

**Version**
./istioctl version
version.BuildInfo{Version:"master-20181004-09-15", GitRevision:"24657b44315e8c0a9a53bfe5a0418984db938e7c", User:"root", Host:"72a127890223", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T19:01:12Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10+IKS", GitCommit:"a2e40acbc885ea18f6b745559928362c690ce062", GitTreeState:"clean", BuildDate:"2018-09-28T04:07:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Using the istio-demo.yaml from the build.

**Environment**
IKS 

**Cluster state**
Plenty of data available in the regression patrol report for the run:
https://ibmcloud-perf.istio.io/regpatrol/master-20181004-09-15/istio_full

**Comment by qiwzhang** [comment]
I am trying to run standalone mixer and envoy, and use fortio to load the traffic to see if I can reproduce the memory leak in local.

**Comment by qiwzhang** [comment]
I can reproduce the memory leak in local setup. I am investigating now.

**Comment by qiwzhang** [comment]
https://github.com/istio/istio/pull/9200

**Comment by jnativio** [comment]
Issue fixed in recent builds.
