### ISSUE TITLE
Please migrate the dogstatsd adapter to the out-of-process adapter model.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#9170]
As described [here](https://groups.google.com/forum/?pli=1#!topic/istio-policies-and-telemetry/SiOJbZ_TDD8), we're in the process of deprecating Mixer's in-process adapter model. Please migrate this adapter to use the out-of-process model, and relocate the source code to your own repo.

Thank you.

@awwithro

**Comment by awwithro** [comment]
@geeknoid I think you missed a link in the issue description

**Comment by awwithro** [comment]
While this is still a valid issue, I've since moved on to working other projects and don't have the cycles to convert this. Help would be appreciated if this is an adapter people are still using.

**Comment by awwithro** [comment]
@geeknoid ^^
