### ISSUE TITLE
Please migrate the SolarWinds adapter to the out-of-process adapter model

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#9173]
As described [here](https://groups.google.com/forum/?pli=1#!topic/istio-policies-and-telemetry/SiOJbZ_TDD8), we're in the process of deprecating Mixer's in-process adapter model. Please migrate this adapter to use the out-of-process model, and relocate the source code to your own repo.

Thank you.

@girishranganathan

**Comment by girishranganathan** [comment]
@geeknoid thank you. 
I will work on this. FYI the link is missing in the above comment. I presume it is this one: https://groups.google.com/forum/?pli=1#!topic/istio-policies-and-telemetry/SiOJbZ_TDD8. Can you please confirm?

**Comment by geeknoid** [comment]
Yes, that's the right link. The link didn't cut & paste correctly. I fixed
it in the issue description.

**Comment by leecalcote** [comment]
@geeknoid which adapters will remain in-process?

**Comment by geeknoid** [comment]
It's likely to be the "dumb" ones that don't talk to any backends: denier,
list, stdio, and maybe prometheus. Everything else will be over gRPC.
