### ISSUE TITLE
Istio upgrade results in 503 and connectivity issues

### ISSUE THREAD

**Issue by hklai** [istio/istio#9185]
**Describe the bug**
Upgrade tests are now run in automated release qualification daily. They tests both version upgrade and downgrade. These tests are currently made to tolerate some errors, including 503s and connectivity problems.

It is not a regression as running similar upgrade tests from 1.0.0 to 1.0.2 result in similar errors.

Example:
Upgrade tests from 1.0.2 to daily 1.0.X releases (i.e. release-1.0 branch).
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio-releases_daily-release/1314/daily-upgrade-tests-1.0.2/262/build-log.txt

Upgrade tests from 1.0.2 to daily 1.1 releases (i.e. release-1.1 branch).
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio-releases_daily-release/1309/daily-upgrade-tests-1.0.2/260/build-log.txt

Search for something like

Code  -1 : 322 (4.6 %)
Code 200 : 6647 (95.3 %)
Code 503 : 7 (0.1 %)

**Expected behavior**
No 503s, or no connectivity issue

**Steps to reproduce the bug**
They run everyday and can be monitored https://github.com/istio-releases/daily-release/pulls?utf8=%E2%9C%93&q=is%3Apr+%22Release+Qualification%22.

Alternatively, these tests can run separately using https://github.com/istio/istio/blob/master/tests/upgrade/test_crossgrade.sh

**Version**
Kubernetes 1.9

**Installation**
N/A

**Environment**
GKE

**Comment by linsun** [comment]
503 are caused often when control plane is down.   During the upgrade, does the control plane have HA?  If so, were the upgrade rolled to the control plane components in a way that is not causing down time.

**Comment by ostromart** [comment]
That's a very good observation Lin. We'll try it with HA, and we should make this a requirement for 503-free upgrades.

**Comment by hklai** [comment]
Also updated bug description to reflect the current state.

**Comment by linsun** [comment]
+1 thanks @ostromart @hklai

**Comment by rshriram** [comment]
It would be good to test if 503s repeat when mixer is set to fail open.

**Comment by rshriram** [comment]
Also instead of simply doing helm upgrade or some such thing, add new version of mixer pods, delete the labels from old mixer deployment, wait for a couple of minutes and then delete old mixer deployment. 

This is the issue with rolling in place upgrades.

**Comment by linsun** [comment]
That is a great point @rshriram.   Per this user, 503 went away when mixer policy is disabled:  https://groups.google.com/forum/#!topic/istio-users/JIUfrIX3zs4

**Comment by sdake** [comment]
> Also instead of simply doing helm upgrade or some such thing, add new version of mixer pods, delete the labels from old mixer deployment, wait for a couple of minutes and then delete old mixer deployment.
> 
> This is the issue with rolling in place upgrades.

@rshriram from what I can tell from procceeding WG meetings, the approach you outline is roughly planned for 1.2.  Essentially when upgrading, there will be two control planes in action - the 1.1 control plane, the 1.2 control plane, and 1.1 will be terminated after 1.2 is in place and providing service.

Cheers
-steve

**Comment by jasminejaksic** [comment]
@linsun Did you get a chance to test this? Did #9951 fix this issue?

**Comment by linsun** [comment]
@hklai is this the right place to look at the upgrade test?  https://k8s-testgrid.appspot.com/istio-release#Summary&width=80

I checked our tests aren't run with multiple control plane so I plan to enable that in our test first.

**Comment by linsun** [comment]
also @hklai we recently merged #9951 in release-1.1, should we also merge it to release-1.0 as the upgrade test is being tested on release-1.0?

Or should we simply test upgrade from release-1.1 build 1 to release-1.1 build 2?

**Comment by linsun** [comment]
cc @costinm @sdake for input

**Comment by hklai** [comment]
>is this the right place to look at the upgrade test? https://k8s-testgrid.appspot.com/istio-release#Summary&width=80

@linsun yes, but the upgrade tests currently need some fixing in release-1.1 and master first.
https://github.com/istio/istio/issues/10806

They have been running in release-1.0 though.


> also @hklai we recently merged #9951 in release-1.1, should we also merge it to release-1.0 as the upgrade test is being tested on release-1.0?

That PR was closed?


> Or should we simply test upgrade from release-1.1 build 1 to release-1.1 build 2?
For now we are trying to up/down grade from/to 1.0.x, what do you mean by release-1.1 build 1 and 2?

**Comment by linsun** [comment]
@hklai yes, it is merged to 1.1 but I can create a new one for 1.0.

**Comment by duderino** [comment]
@linsun did you mean to close this?  if so please close
