### ISSUE TITLE
Perf:Istio Scalability improvements for Cloud Foundry Use Cases

### ISSUE THREAD

**Issue by suryadu** [istio/istio#9187]
**Describe the feature request**
As Cloud Foundry is working actively to embrace Istio both at the routing layer (North-South traffic) as well app to app communication layer with policies and traffic management (East-West traffic), it is essential to provide the scalability that is enjoyed by Cloud Foundry today. The main focus is going to be around supporting thousands of routing rules and Pilot scalability apart from other aspects.

This issue will track all the optimization work being done in this space as part of Istio Performance and scalability workgroup.

**Comment by suryadu** [comment]
@mandarjog , I am adding this issue to our SWAT work and we can discuss this in our next Istio work group meeting. Can you please add the pilot issue that CF team brought up to this issue?
https://docs.google.com/document/d/1ob9M2TfI5GS3_rqrEhWFIpVyfFVKPTE8N3YZpeiDJxw/edit#

**Comment by howardjohn** [comment]
This doesn't have any associated issues or work to be done, so I am going to close. Feel free to reopen if there is anything to do here
