### ISSUE TITLE
Grafana Mesh Dashboard flashes sub-100% success rate occasionally for multiple services

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#9189]
**Describe the bug**
While sitting on the Grafana Mesh Dashboard, it will occasionally flash orange success rates in the 80's and 90's for multiple services for just one update tick (5 seconds), correcting itself back to 100% on the next tick.

![screenshot 2018-10-07 17 15 35](https://user-images.githubusercontent.com/12174604/46587057-2d8c4b00-ca55-11e8-8c1c-4a450eeb61ef.png)

**Expected behavior**
If the success rate is truly 100%, some updates shouldn't show something under that. If the success rate does dip, it shouldn't recover to 100% within the next 5 second update. I believe the monitored window is 15 minutes, right?

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
`1.1.0-snapshot.1`

**Installation**
Helm template with `enableTracing: false`, and `grafana.enabled: true`.

**Environment**
AWS / Kops

**Comment by douglas-reid** [comment]
@jaygorrell the rates are not shown over a 15min window. The rates are calculated via:

`sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"destination\"}[1m]))`

As you can see, the rates are over a 1m window. I think I recall reading somewhere that `rate` uses the first and last data point within that window for calculation. So, it is possible that a difference of 5s ends up excluding the error (causing it to jump back to 100% in the next refresh).

Do you see any 4xx responses in your access logs that correspond?

**Comment by jaygorrell** [comment]
>As you can see, the rates are over a 1m window. I think I recall reading somewhere that rate uses the first and last data point within that window for calculation.
Can you elaborate on this? It's a 1m window for the metric but it's only made up of two datapoints? You also mentioned 4xx's but those don't impact the success rate, do they? I would imagine it's only 500-level.

**Comment by douglas-reid** [comment]
@jaygorrell I didn't see an official reference, but I was quickly able to find other places with the claim of:
>The rate function takes a time series over a time range, and based on the first and last data points within that range (allowing for counter resets) calculates a per-second rate.

Sorry, I meant 5xx but typed 4xx.

**Comment by jaygorrell** [comment]
No problem, thanks :) But yeah, Grafana itself confirms those services never actually dipped below 100% at any time.

**Comment by douglas-reid** [comment]
@jaygorrell There is actually a difference in the queries on each of the different dashbaords (`irate` v. `rate` and differing windows).

One important thing to note: the time window for Grafana display is completely distinct from the window used in querying for per-second values.  So, you may be showing 15m worth of chart, but that isn't reflected in the querying.

Again, I think the thing we want to figure out is if you are seeing non-success requests via another mechanism (access logs, etc.) to determine if this is a display glitch (misaligned data, etc.) or otherwise.

**Comment by jaygorrell** [comment]
I can confirm that I do not have non-200 responses for some of the services. One example is
`kubectl logs <service-name> istio-proxy | grep -v 200`, which returns no results aside from the startup logs. If you look closely (I missed this myself), the 100% rows in the original screenshot were actually over 100% by a fraction.

When this happens, it's always a handful of services at the same time and they all recover back to green at the same time. I'm guessing it may be something related to Chrome and the clock as described here: https://istio.io/help/ops/telemetry/grafana/

The other alternative is that I haven't exposed Grafana and am viewing it through a kubectl tunnel.
