### ISSUE TITLE
I can't see my service and deployment in istio jaeger dependency graph

### ISSUE THREAD

**Issue by pgnaleen** [istio/istio#9190]
**Describe the bug**

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smsoffer-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smsoffer-test
    spec:
      containers:
      - name: smsoffer-test-container
        image: pgnaleen/microservicesapps:smsoffer-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8823
          #        volumeMounts:
                #        - mountPath: /logs/
          #          name: log-volume
          #        - mountPath: /etc/configs/
          #          name: configs
        env:
        - name: MESSAGE
          value: "hello world"
        command: ["/bin/echo"]
        args: ["$(MESSAGE)"]
        command: ["/bin/sh"]
#        args: ["-l", "-c", " tail -f /dev/null"]
        args: ["-l", "-c", "java -jar /root/localSMSOffer-1.0.0.jar"]
        #      volumes:
              #      - name: log-volume
        #        hostPath:
         # directory location on host
         #         path: /home/k8s_istio_platform/logs/
         #      - name: configs
        #        hostPath:
         # directory location on host
         #         path: /home/k8s_istio_platform/configs/
---
kind: Service
apiVersion: v1
metadata:
  name: smsoffer-test
  namespace: default
spec:
  selector:
    app: smsoffer-test
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
#  clusterIP: 10.0.171.239
#  loadBalancerIP: 172.26.76.122
#  externalIPs:
#  - 172.26.76.122
  type: LoadBalancer

gatewayfile
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sms-test-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smsoffer-test
spec:
  hosts:
  - "*"
  gateways:
  - sms-test-gateway
  http:
  - match:
    - uri:
        exact: /cloudtest
    route:
    - destination:
        host: smsoffer-test
        port:
          number: 8080

**Environment**
google cloud

**Cluster state**
istio 1.0

please instruct me how to get my service into istio jaeger UI graph

**Comment by objectiser** [comment]
The Jaeger dependency graph only shows dependencies - so if your service is not communicating with any other service, then it will not show up.

You might want to try [kiali](https://www.kiali.io/), as I believe it shows standalone services.

**Comment by pgnaleen** [comment]
what about Grafana istio mesh , istio service dashboard. my service doesn't show to those dashboards as well

**Comment by objectiser** [comment]
Are you seeing trace instances in the Jaeger UI?

**Comment by douglas-reid** [comment]
@pgnaleen are your services kube-injected?  Is the proxy running in front of your services?

**Comment by pgnaleen** [comment]
![capture](https://user-images.githubusercontent.com/6938631/46645161-3db14100-cba1-11e8-9d3e-af9b985a64ba.JPG)

![capture](https://user-images.githubusercontent.com/6938631/46645222-7f41ec00-cba1-11e8-807c-6f3644de6ff7.JPG)

**Comment by pgnaleen** [comment]
only my service missing

**Comment by pgnaleen** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sms-test-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smsoffer-test
spec:
  hosts:
  - "*"
  gateways:
  - sms-test-gateway
  http:
  - match:
    - uri:
        exact: /cloudtest
    route:
    - destination:
        host: smsoffer-test
        #host: smsoffer-test-container
        port:
          number: 8080

**Comment by gyliu513** [comment]
Please check https://istio.io/docs/setup/kubernetes/spec-requirements/ for
service tracing requirement, your service are missing named ports, this
will cause the service cannot be traced by Jaeger.

**Comment by pgnaleen** [comment]
thank you @gyliu513 
now i can see my service and container on istio service dashboard. But i called few times to my loadbalance public url. But still i can't see my traffic on istio service dashboard.

http://35.200.183.248:8080/cloudtest

![capture](https://user-images.githubusercontent.com/6938631/46646484-0befa880-cba8-11e8-9704-026ceee2a192.JPG)

**Comment by gyliu513** [comment]
Not sure about this, @douglas-reid <https://github.com/douglas-reid> ,
comments for this?

**Comment by pgnaleen** [comment]
i see problem was the container port was not named.

kind: Deployment
metadata:
  name: smsoffer-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smsoffer-test
    spec:
      containers:
      - name: smsoffer-test-container
        image: pgnaleen/microservicesapps:smsoffer-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          **name: http**   
after adding this last line every thing was fine. and i can see my service on all the graphs.

But after some time again it went worng

http://35.200.228.96/cloudtest
return  no healthy upstream now.
But this worked correctly after few min ago.

**Comment by pgnaleen** [comment]
but after run following line i can work with below url
gcloud container clusters get-credentials istio-cluster --zone asia-south1-c --project igneous-primacy-218203  && kubectl port-forward $(kubectl get pod --selector="app=smsoffer-test" --output jsonpath='{.items[0].metadata.name}') 8080:8080

https://8080-dot-4533440-dot-devshell.appspot.com/cloudtest

so my deploymetn working fine.

**Comment by pgnaleen** [comment]
![capture](https://user-images.githubusercontent.com/6938631/46652545-faff6100-cbc0-11e8-93f2-4faddf6cb05e.JPG)

can anyone find the error with this image

**Comment by objectiser** [comment]
Can you list the tags associated with the root span.

**Comment by pgnaleen** [comment]
![capture](https://user-images.githubusercontent.com/6938631/46655829-4702d380-cbca-11e8-94cd-a834406fb57f.JPG)

**Comment by pgnaleen** [comment]
how can i find that error


![capture](https://user-images.githubusercontent.com/6938631/46656196-1bccb400-cbcb-11e8-9931-af55efceb248.JPG)

when i call url for my service i see traffic show on unknown service category not on localsms category

**Comment by objectiser** [comment]
Not sure - possibly this is showing metrics from the ingress gateway.

For the trace with the 503 root span - does it actually call your service? If so, what are the tags for the server span for your service?

**Comment by pgnaleen** [comment]
**apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sms-test-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-new
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smsoffer-test
spec:
  hosts:
  - "*"
  gateways:
  - sms-test-gateway
  http:
  - match:
    - uri:
        exact: /cloudtest
    route:
    - destination:
        host: smsoffer-test
        #host: smsoffer-test-container
        port:
          name: http-new
          number: 8080**

this is the gateway and virtual service. i think there is something missing in this configuration. please advice me.
I already deleted the gateway for bookinfo example. 

my response is 

no healthy upstream

i think traffic not going to direct to my service.

**Comment by pgnaleen** [comment]
can anyone tell me what is this destination 

destination:
host: smsoffer-test
#host: smsoffer-test-container
port:
name: http-new
number: 8080**

is this host is service name or container name..... should i specify the container port

**Comment by pgnaleen** [comment]
please anyone has a comment.
