### ISSUE TITLE
Remove `mixerCheckServer` and `mixerReportServer` from Helm Chart

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#9211]
This is a follow up issue for PR https://github.com/istio/istio/pull/9180#discussion_r223215901

For the parameters of `mixerCheckServer` and `mixerReportServer`, from the helm chart description, it is deprecated in mixer as mixer is now using EDS, so can we remove those parameters from helm chart?

/cc @rshriram @sdake

@Rigdon I found that the `istio-remote` chart was also using those parameters, can this be removed as well?

**Comment by sdake** [comment]
@gyliu513 no clue if those variables are still used, however, we do want to try to reduce the footprint (and eventually remove) the configmap from what I've heard in TOC meetings.  Removing this stuff if its not used would help get us a little closer :)

Cheers
-steve

**Comment by rshriram** [comment]
They are both being used..

**Comment by gyliu513** [comment]
Thanks @sdake and @rshriram 

@rshriram , but based on comments here https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/configmap.yaml#L24 , it is saying those parameters are deprecated, am I missing anything?

**Comment by rshriram** [comment]
Invalid comment

**Comment by gyliu513** [comment]
@rshriram sorry, not quite catch what do you mean here ;-)

**Comment by linsun** [comment]
@gyliu513 can this be closed?  Seems they are both used per @rshriram.  The helm comments on deprecation look odd to me too.

**Comment by linsun** [comment]
pls reopen if needed
