### ISSUE TITLE
Citadel standalone not working, arguments mismatch

### ISSUE THREAD

**Issue by ldounis** [istio/istio#9228]
**Describe the bug**
Deployed istio-citadel-standalone.yaml of istio-1.1.0.snapshot.1 and citadel pod is in a crash loop.

kubectl logs istio-standalone-citadel-7f59798f4b-9k2xz -n istio-system
Error: unknown flag: --stderrthreshold

kubectl logs istio-standalone-citadel-796b8967b5-x2lqf -n istio-system
Error: unknown flag: --logtostderr

kubectl logs istio-standalone-citadel-5cb955c5fd-fbvj7 -n istio-system
2018-10-09T14:51:21.865955Z     error   unknown flag: --self-signed-ca-org

**Expected behavior**
An up to date yaml file so that someone can deploy it.

**Steps to reproduce the bug**
kubectl apply -f install/kubernetes/istio-citadel-standalone.yaml

**Version**
istio-1.1.0.snapshot.1

**Installation**
No istio installation

**Environment**
Azure cloud

**Comment by myidpt** [comment]
Quick fix is to remove the two flags from the deployment args.
I will have a PR to fix it.
