### ISSUE TITLE
Mesh expansion missing ISTIO_VERSION

### ISSUE THREAD

**Issue by costinm** [istio/istio#9240]
**Describe the bug**
Docker image for proxy has ISTIO_META_ISTIO_VERSION=1.0.2, which causes RBAC and other 
plugins to generate config. It is missing in the startup script for mesh expansion.

**Comment by cmluciano** [comment]
Is this still relevant?

**Comment by costinm** [comment]
Yes, it's a simple change in the build, didn't have time to make it.

**Comment by costinm** [comment]
We need more people familiar with mesh expansion install - can you take a look ? The problem is testing the current build (including all the changes in security and config) and validating the .deb still works.

**Comment by wattli** [comment]
Unfortunately I am pretty occupied for other issues.

**Comment by costinm** [comment]
Fixed in 1.1
