### ISSUE TITLE
Unable to expose Grafana through the ingress gateway

### ISSUE THREAD

**Issue by consult-kk** [istio/istio#9247]
Hi,
I am working with Istio 1.0.2 on GKE. I am able to deploy services like eureka and consul in my default namespace and expose them to the outside world using the virtualservice. 
But when I attempt the same with the Grafana service ( installed along with istio ) , it dont seem to work. Here is the Grafana VirtualService YML file I am using . Rest of the Istio installation is default and I have not changed anything else . 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
  - "istiotest-grafana.mydomain"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana
        port:
          number: 3000
```

**Comment by clyang82** [comment]
Please append the output of `kubectl get gateway istio-gateway -o yaml -n istio-system` and `kubectl get svc grafana -o yaml -n istio-system`

**Comment by consult-kk** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"istio-gateway","namespace":"istio-system"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  clusterName: ""
  creationTimestamp: 2018-10-10T11:48:09Z
  generation: 1
  name: istio-gateway
  namespace: istio-system
  resourceVersion: "100886"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/gateways/istio-gateway
  uid: 5ba82088-cc82-11e8-a5e7-42010a8e008d
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```
and here are the details for the grafana service.... 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grafana","chart":"grafana-1.0.1","heritage":"Tiller","release":"RELEASE-NAME"},"name":"grafana","namespace":"istio-system"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"grafana"},"type":"ClusterIP"}}
  creationTimestamp: 2018-10-09T23:20:45Z
  labels:
    app: grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: RELEASE-NAME
  name: grafana
  namespace: istio-system
  resourceVersion: "1649"
  selfLink: /api/v1/namespaces/istio-system/services/grafana
  uid: f2baeaea-cc19-11e8-a5e7-42010a8e008d
spec:
  clusterIP: 10.51.244.97
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by douglas-reid** [comment]
Have you looked at the config for the `telemetry-gateway` ?  It is a working example of basically what you are trying to do. Please see: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/telemetry-gateway/templates/gateway.yaml

**Comment by consult-kk** [comment]
Hi,
Thanks for the reply. But I tried the following commands to install/configure istio : 

```
- gcloud container clusters create  tele-istio --cluster-version=latest --num-nodes 4
- kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)
- kubectl label namespace default istio-injection=enabled
- helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true --set prometheus.enabled=true --set servicegraph.enabled=true --set tracing.enabled=true  > istio.yml
- kubectl apply -f istio.yml
```

Even with this.. the telemetry YML contents are not generated.. and the section in istio.yml is empty
and given this setup .. what do I need to now access grafana. Ideally I would only need an ingress service to expose Grafana. But that also doesnt seem to be the case.
Any help is appreciated on this.

**Comment by douglas-reid** [comment]
@consult-kk you were missing some of the helm options needed. this is a bit confusing, to be fair. You need `telemetry-gateway.gatewayEnabled` set to `true`, a la:

`$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true --set telemetry-gateway.grafanaEnabled=true   > istio.yml`

```
---
# Source: istio/charts/telemetry-gateway/templates/gateway.yaml

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-telemetry-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15031
      name: http2-grafana
      protocol: HTTP2
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: istio-system
spec:
  host: grafana.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE      
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: telemetry-virtual-service
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istio-telemetry-gateway
  http:
  - match:
    - port: 15031
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
```

**Comment by consult-kk** [comment]
Hi Douglas,
Thanks for your help. I was able to expose Grafana to the outside world. 
Now I have couple of questions  :

1) Can I use deploy a different ingressgateway for all my microservices and still have the metrics gather by Grafana running in the istio-system namespace.
2) if not, should I use the one single ingressgateway to allow access to all of my microservices APIs, if so how would I go about achieving this.

Thanks ,
KK

**Comment by douglas-reid** [comment]
@consult-kk There is no requirement for the gateway used to access Grafana to be the same as the one used for accessing other services.

**Comment by douglas-reid** [comment]
@consult-kk I'm going to close this issue, as I feel like we've addressed the original concern. Let's follow-up on further questions on mailing-lists or in a separate issue. Please feel free to re-open if you feel it is appropriate.

**Comment by tim-beatson** [comment]
Hi, I have a similar issue exposing Grafana. I can get as far as the login page, and when I enter my credentials I can see that they get accepted, but then I'm directed straight back to the login page. If anyone can suggest what I might be missing from my config to make this work, it would be greatly appreciated.

**Comment by hustshawn** [comment]
> @consult-kk you were missing some of the helm options needed. this is a bit confusing, to be fair. You need `telemetry-gateway.grafanaEnabled` set to `true`, a la:
> 
> `$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true --set telemetry-gateway.grafanaEnabled=true > istio.yml`
> 
> ```
> ---
> # Source: istio/charts/telemetry-gateway/templates/gateway.yaml
> 
> apiVersion: networking.istio.io/v1alpha3
> kind: Gateway
> metadata:
>   name: istio-telemetry-gateway
>   namespace: istio-system
> spec:
>   selector:
>     istio: ingressgateway
>   servers:
>   - port:
>       number: 15031
>       name: http2-grafana
>       protocol: HTTP2
>     hosts:
>     - "*"
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: DestinationRule
> metadata:
>   name: grafana
>   namespace: istio-system
> spec:
>   host: grafana.istio-system.svc.cluster.local
>   trafficPolicy:
>     tls:
>       mode: DISABLE      
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: telemetry-virtual-service
>   namespace: istio-system
> spec:
>   hosts:
>   - "*"
>   gateways:
>   - istio-telemetry-gateway
>   http:
>   - match:
>     - port: 15031
>     route:
>     - destination:
>         host: grafana.istio-system.svc.cluster.local
>         port:
>           number: 3000
> ```

@douglas-reid Your provided solution works well for proxy the grafana with ingress+port，may I konw how to achieve the same goal by a uri route like ` uri: /grafana`?

**Comment by douglas-reid** [comment]
@hustshawn that is slightly more complicated. some of the mechanisms for exposing the add-ons have migrated since this issue was first opened. i have not recently attempted such a thing, but I believe the `contextPath` support in the ingress template (see: https://github.com/istio/installer/blob/master/istio-telemetry/grafana/templates/ingress.yaml) may provide some help here, too, if you want to look at that.

**Comment by victory1908** [comment]
Hi @douglas-reid all the link you provide is now `404`. I'm looking for a template to expose `grafana`, `prometheus`, `kiali`... through default port for existing `istio` installation

**Comment by douglas-reid** [comment]
@victory1908 this PR (https://github.com/istio/installer/pull/225) removed that file. you can look at the source prior to the change, I suppose, for inspiration.
