### ISSUE TITLE
Outputs an warning when an unexpected NodeType is passed

### ISSUE THREAD

**Issue by nakabonne** [istio/istio#9249]
**Describe the feature request**
Hi, This is a small proposal.
[Here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L97) and [here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/httproute.go#L43), there is processing that ConfigGeneratorImpl generates Resource according to the passed NodeType.
When an unexpected NodeType comes in, it returns nil, but I think that it should output the log as shown below.

```go
switch node.Type {
case model.Sidecar:
	return configgen.buildSidecarListeners(env, node, push)
case model.Router, model.Ingress:
	return configgen.buildGatewayListeners(env, node, push)
default:
	log.Warn("BuildListeners Unexpected NodeType")
}
```

As this does not mean that something bug happened, if you judge it is not necessary, please close this issue.

**Comment by nakabonne** [comment]
If it does not matter, I would like to fix it.

**Comment by nakabonne** [comment]
Should such a small proposal be discussed within the mailing list?

**Comment by hzxuzhonghu** [comment]
@nakabonne We have three kind of type totally: sidecar, ingress and router. In pilot this value is parsed from discovery request. So i think log a warning is reasonable.

**Comment by supereagle** [comment]
> So i think log a warning is reasonable.

+1
It would be better to print the node type in the warning.

**Comment by nakabonne** [comment]
@supereagle 
Thank for your request!

@hzxuzhonghu 
Thank you for your reply.
Then, may I add warning with NodeType [here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L97) and [here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/httproute.go#L43)?

Like this:

```go
log.Warnf("BuildListeners Unexpected NodeType %s", node.Type)
