### ISSUE TITLE
Adding `nodeSelector` to istio deployment files

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#925]
A related PR for helm chart of istio is in fly https://github.com/kubernetes/charts/pull/2320

**Comment by ldemailly** [comment]
can you say a bit more about what's broken/what a fix would be etc ?

**Comment by gyliu513** [comment]
Someone might want to deploy isito on to nodes with specific architecture or resources, such as with nodes cpu>4core, memory>10G, running istio on POWER or X86 etc. 

We can probably put a placeholder in deployment file and enable end user can customize it?  @ldemailly

**Comment by linsun** [comment]
+1, user may choose to deploy istio on edge nodes, for example.

**Comment by gyliu513** [comment]
I have finished this in istio charts here https://github.com/kubernetes/charts/pull/2436  , will try to create a PR for istio next week. @linsun @ldemailly

**Comment by campbelldgunn** [comment]
@geeknoid - I notice that the helm charts for this are still referencing 0.3.0 and not 0.4.0 in the latest release downloaded from github.com. Is there going to be a 0.4.0 helm chart release?

**Comment by geeknoid** [comment]
Not sure, maybe @gyliu513 would know.

**Comment by gyliu513** [comment]
Yes, I think that we need upgrade this to 0.4 now. @sbezverk , any plan for this?

**Comment by linsun** [comment]
there is a WI for this, I plan to look at it very soon.   https://github.com/istio/istio/issues/2516

**Comment by gyliu513** [comment]
Already implemented at https://github.com/istio/istio/pull/3856
