### ISSUE TITLE
istio/install/kubernetes/istio-demo-auth.yaml: No such file or directory"

### ISSUE THREAD

**Issue by Kiran01bm** [istio/istio#9272]
Trying to install istio with Ansible on Openshift. I've attempted both with and without auth and for both cases I get the "No such file or directory" for the istio-demo.yaml and istio-demo-auth.yaml files. The .gitignore excludes both these files.

To be able to deploy istio on Openshift Container Platform or can the documentation on https://istio.io/docs/setup/kubernetes/ansible-install/#deploy-with-ansible be updated ?

Run the below playbook from **istio/install/kubernetes/ansible/** dir

`ansible-playbook main.yml -e '{"istio": {"auth": true, "delete_resources": true, "samples": ["helloworld", "bookinfo"], "addon": ["kiali"]}}'`

**Comment by supereagle** [comment]
There is already a warning before all steps.

> All execution of the Ansible playbooks must take place in the install/kubernetes/ansible path of Istio.

**Comment by Kiran01bm** [comment]
I'm running from that path. The issue is with istio-demo.yaml and istio-demo-auth.yaml files being part of .gitignore and hence...

`
TASK [istio : Copy definition file] ************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cp", "/Users/kiran/Documents/GIT/istio-master/install/kubernetes/istio-demo-auth.yaml", "/var/folders/jl/x_f0cfh15vdb268g6c727fm00000gn/T/ansible.XXXXXXXXXX.WUUnWfho/def.yml"], "delta": "0:00:00.009053", "end": "2018-10-18 17:34:12.565681", "msg": "non-zero return code", "rc": 1, "start": "2018-10-18 17:34:12.556628", "stderr": "cp: /Users/kiran/Documents/GIT/istio-master/install/kubernetes/istio-demo-auth.yaml: No such file or directory", "stderr_lines": ["cp: /Users/kiran/Documents/GIT/istio-master/install/kubernetes/istio-demo-auth.yaml: No such file or directory"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/kiran/Documents/GIT/istio-master/install/kubernetes/ansible/main.retry

PLAY RECAP *************************************************************************************************************************************************************************************************************************
localhost                  : ok=19   changed=3    unreachable=0    failed=1
`

**Comment by supereagle** [comment]
What's istio version? I will take a look.

**Comment by sdake** [comment]
The playbooks cannot be run from the repository unless `make generate_yaml` is run.  We don't check in istio-demo.yaml.  The playbooks in the release artifact should work correctly.

Can you verify and if so close and comment?

Cheers
-steve

**Comment by gbaufake** [comment]
@supereagle 
If you are using the istio that comes with the release, you will find these files (istio-demo-auth and istio-demo files) on the repository and ansible playbook should run fine. If not please create an issue and assign to me that I will take a out 

If you want to test straight out from istio repository, you need to do some installation with helm:

- Install Helm (https://docs.helm.sh/using_helm/)

- `helm repo add istio.io https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts`

- `helm dep update install/kubernetes/helm/istio`

- `helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=false --set tracing.enabled=true --set grafana.enabled=true > install/kubernetes/istio-demo.yaml` (to generate the file without mtls)

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true --set tracing.enabled=true --set grafana.enabled=true > install/kubernetes/istio-demo-auth.yaml`
