### ISSUE TITLE
Downstream disconnects reported as status 500

### ISSUE THREAD

**Issue by kayleg** [istio/istio#9292]
**Describe the bug**
When a client disconnects before envoy can return a response, log entry has response code of 0 but telemetry records the result as a status 500. This shows up in prometheus and grafana as status 500 as well. 

**Expected behavior**
Not entirely sure, but it seems like `500` is incorrect. There wasn't any internal server error; the client disconnected so envoy correctly aborted processing.
Maybe initialize the request_data response code to `499` which according to https://httpstatuses.com/499 is for client disconnected before processing is complete

**Steps to reproduce the bug**
Disconnect before upstream can deliver result, causing proxy to create log entry with a format like:
`"GET / HTTP/1.0" 0 - 0 0 0 - "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64)"` <- Note the **0** for the response code.

**Version**
```
istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.1", GitCommit:"7221ffe8776f399448d61b4dc9edb5c69232aece", GitTreeState:"clean", BuildDate:"2018-08-29T23:11:12Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm install

**Environment**
GKE

**Comment by vaibhavrtk** [comment]
/open I am facing this issue as well. We have alerts on 5xx errors and the client DC shouldnt be treated as an error on Server side

**Comment by mpfaehler** [comment]
If you'd like to filter those client disconnects from your monitoring, you may have a look at the response_flag "DC",
cp:
https://github.com/envoyproxy/envoy/issues/5119
https://blog.getambassador.io/understanding-envoy-proxy-and-ambassador-http-access-logs-fee7802a2ec5
As far as I understand it, your client disconnects should have the response_flag "DC" set.

**Comment by trevorlinton** [comment]
For anyone else trying to figure this out, we ended up routing our logs to a fluentd system, when setting up our access log instance type for the response status code we used the expression `conditional(context.proxy_error_code == "DC", 499, response.code | 0)` which sets the response code to 499 if the downstream client disconnects.
