### ISSUE TITLE
 GetProxyServiceInstances should be more efficient 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#9296]
GetProxyServiceInstances 
 https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller.go#L413-L471

Now it iterates over all endpoints in k8s cluster. And get its service and do some kind of compare&conversion work.
In cluster with massive of services and endpoints, pilot could be very slow . 

We should get the services by the way kubernetes endpoint_controller does: using the svc selector to match pod labels. 
```
func (s *serviceLister) GetPodServices(pod *v1.Pod) ([]*v1.Service, error) {
	allServices, err := s.Services(pod.Namespace).List(labels.Everything())
	if err != nil {
		return nil, err
	}

	var services []*v1.Service
	for i := range allServices {
		service := allServices[i]
		if service.Spec.Selector == nil {
			// services with nil selectors match nothing, not everything.
			continue
		}
		selector := labels.Set(service.Spec.Selector).AsSelectorPreValidated()
		if selector.Matches(labels.Set(pod.Labels)) {
			services = append(services, service)
		}
	}

	return services, nil
}
```

**Comment by yangminzhu** [comment]
The current `GetProxyServiceInstances()` uses IP to match pod and endpoints:
https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/controller.go#L479-L482

This means the [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) that doesn't have selectors is also supported.

If we change to use service selector, how do we support the headless services? Or should we drop the headless service support in `GetProxyServiceInstances()`?

**Comment by hzxuzhonghu** [comment]
@yangminzhu Can we say the headless services without selectors equal to external services?

For external service we donot need this. If I miss something, please correct me.

**Comment by yangminzhu** [comment]
Not as far as I know, I think it's at least allowed to create headless service for internal services for now.

**Comment by rshriram** [comment]
Headless services are part of the mesh. Stateful sets is a good example. We definitely need to support headless services (people have asked for mTLS to/from and among nodes of stateful sets). 

One optimization we can do is to try the logic @hzxuzhonghu has.. and if it fails, we fallback to the slow path of iterating over all endpoints. This way, the slowness will happen only for headless services, while 95% of normal services will take the fast path.

**Comment by hzxuzhonghu** [comment]
Now it is clear, thanks. Will propose a pr later.
