### ISSUE TITLE
Ability to define default traffic and retry policy for the entire mesh

### ISSUE THREAD

**Issue by pnambiarsf** [istio/istio#9300]
**Describe the feature request**
From what we can tell, right now traffic and retry policies can only be defined per service via VirtualService and DestinationRule objects.  We would like the ability  to define defaults for the entire mesh that will take effect for all services with the option to override per service as necessary. 

**Describe alternatives you've considered**
Our only option right now seems to be to update VirtualService and DestinationRule objects of all services in the mesh when we want to change these policies across the board. 

**Additional context**
We currently use mainline envoy as our sidecar with a limited in-house implementation of the control plane. We would like to migrate to Istio.  With the current setup, we serve up defaults for traffic and retry policies for all services via the in-house control plane. We expect to continue doing that with a few services needing to override them at a service level.

**Comment by pnambiarsf** [comment]
@ayj - This issue should probably be tagged with the area/config label rather than area/networking.

**Comment by shakti-das** [comment]
This would mean exposing TrafficPolicy and HttpRetry in api/mesh/config and use the values if set as mesh-wide defaults unless overridden by DestinationRule or VirtualService respectively.

Order of priority would then be: 
TrafficPolicy specified in DestinationRule overrides TrafficPolicy set in MeshConfig.
Similarly, HttpRetry specified in VirtualService overrides HttpRetry set in MeshConfig.

If this is the agreed functionality, I would like to pick it up for release-1.1.

**Comment by pnambiarsf** [comment]
defaults was discussed in the last networking WG meeting. Current thought is that galley would be a good place to support defaults. Ideally we should have one consistent pattern to specify defaults for all types of config and not just networking.

@ozevren - FYI.

**Comment by rajusharma** [comment]
any progress or further details about this issue? 🙏

**Comment by XanderStrike** [comment]
This is an issue we're running into as well, shouldn't be stale.

**Comment by howardjohn** [comment]
We have a bunch of issues around defaults, lets consolidate into #6861 to clean things up. Please also see https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/ which is a design doc for this being actively worked on.
