### ISSUE TITLE
RBAC: Support SNI in ServiceRole

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#9308]
Envoy has merged the PR to support [SNI](https://github.com/envoyproxy/envoy/blob/ae6a4e7951bc82a21f8627ccce4b14629f876163/api/envoy/config/rbac/v2alpha/rbac.proto#L149) in the Permission.

Istio ServiceRole should support specifying this field accordingly.

We have several options:

- Support the SNI as a first-class field in the [AccessRule](https://preliminary.istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#AccessRule)

- Support the SNI as a constraints `connection.requested_server_name` in the AccessRule, this aligns with the [Istio attribute vocabulary](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/).

- Support the SNI in the service field in the AccessRule. There are multiple on-going work to re-design the authorization policies, like extending it to Ingress/Egress, and workload-centric policy design. So we need more thoughts on this option to align with these on-going work before we change the API.

/cc @liminw @rshriram @diemtvu 
Any thoughts?

**Comment by rshriram** [comment]
I suggest option 2. Easiest.

**Comment by rshriram** [comment]
I also don’t think we should call it as requested server name! Not so intuitive. People know SNI very well. Simply call it connection.sni ?

**Comment by liminw** [comment]
I agree treating it as an attribute (option 2) is the easiest.

**Comment by yangminzhu** [comment]
@rshriram @liminw Thanks for your comment, I'll go ahead for option 2 using attribute name `connection.sni`.
 
/cc @venilnoronha

**Comment by yangminzhu** [comment]
Fixed by #9344
