### ISSUE TITLE
Outage on Istio upgrades or host upgrades

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#9315]
**Describe the bug**
When cycling hosts (k8s upgrades, etc.) or when upgrading istio and replacing it's system pods, there is a connectivity outage with cluster services. I did some testing and narrowed this down to the istio-policy pods, regardless if there are multiple pods or not.

**Expected behavior**
An istio-policy pod restarting should not prevent connectivity to cluster services.

**Steps to reproduce the bug**
1. Run a handful of pods with health checks (or be ready to simulate traffic)
2. Monitor the event log: `kubectl get events -w`
3. Delete an istio-policy pod
4. Observe that some requests to the cluster fail

**Version**
k8s v1.10.5 / Istio 1.1.0-snapshot-1

**Installation**
Helm Template defaults

**Environment**
AWS / Kops

**Comment by ayushpateria** [comment]
This is same issue as https://github.com/istio/istio/issues/7334. Any updates on when are health checks coming?

**Comment by jaygorrell** [comment]
Looks like you're correct @ayushpateria -- I'll close this one and have subscribed to that one.
