### ISSUE TITLE
Istio Operator for Kubernetes

### ISSUE THREAD

**Issue by secat** [istio/istio#9333]
Are there some plans to create an Istio [Operator](https://coreos.com/operators/) for Kubernetes?

Istio has a very complex deployment scheme with multiple components. I realized from my experience using Helm to deploy/upgrade/manage such complex deployments that Helm has some limits.

**Comment by mabushey** [comment]
Anything to get away from Helm would be great as all it does is add complexity and problems. Helm causes way more problems than it solves.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/10015
Early version of an operator for 1.1. Additional work is going on that will hopefully land in 1.2.

**Comment by sdake** [comment]
For folks following this work, the initial goal is to solve one very simple problem as simply as possible:
https://github.com/istio/istio/issues/9884

**Comment by shadowlord017** [comment]
There is operator for Openshift: [maistra](https://github.com/Maistra/istio-operator)
And [example installation](https://github.com/debianmaster/openshift-examples/tree/master/istio)

**Comment by martonsereg** [comment]
We've just released an open-source Istio operator, and would be very happy to receive some feedback. You can check out the repo [here](https://github.com/banzaicloud/istio-operator/).

**Comment by mabushey** [comment]
@martonsereg  This is amazing! Thank you. I'm using Kops to install k8s. The newest version of k8s Kops can install is 1.11, so the newest kubectl I can run in 1.12. Any chance this operator can work with kubectl 1.12?

**Comment by martonsereg** [comment]
@mabushey That’s a mistake in the readme I think, there shouldn’t be anything in the code that requires 1.13, so I think it should work with kubectl 1.12 as well, please give it a try.

**Comment by waynz0r** [comment]
@mabushey Hi, it should work just fine. We're gonna fix the requirements.

**Comment by linsun** [comment]
BTW this was created this week https://github.com/istio-ecosystem/istio-operator

**Comment by jmazzitelli** [comment]
Kiali has published an operator as well - so can be integrated when you want to pull in Kiali in your Istio environment. I was planning on incorporated it in the helm install stuff (I think Jaeger is doing this kind of thing, too, with their operator - of they are planning to if it is not done yet). It will be incorporated in the Maistra Istio operator soon as well.

See:

https://www.kiali.io/gettingstarted/
https://quay.io/repository/kiali/kiali-operator?tab=tags

The Kiali operator will be up on OperatorHub.io soon.

**Comment by ostromart** [comment]
That's great - the istio operator will no longer incorporate the full manifests for addons like kiali, prom etc. but rather just pass through opaque config through to these "sub-operators". In most cases, users will probably just interact with the sub-operator directly, the pass-through function will be there for managed Istio cases.

**Comment by zot24** [comment]
Hi there! I'm confuse about what's the official state of the "Istio Operator" and I was hopping the community could throw some light.

@linsun who is behind the istio-ecosystem project? it's that going to be an "official" repo to support the istio operator?

@ostromart when you say `istio operator` which istio operator do you refer to? do you have a link you can provide? so far I can only see that PR you share a while back https://github.com/istio/istio/pull/10015#issuecomment-448481680 but that PR have been closed in favor of helm chart that doesn't use operators, or at least I can't find any reference to the operator sdk in here https://github.com/istio/istio/tree/master/install/kubernetes/helm

So far I have only found the [banzaicloud operator](https://github.com/banzaicloud/istio-operator/) and the [maistra one](https://github.com/Maistra/istio-operator)

ta

**Comment by ostromart** [comment]
The new "official" operator is going to take some code from those (the authors themselves will be merging gradually) and live in istio-ecosystem initially, likely moving into istio when it matures somewhat. So that also answers the "who's behind this" question: @rcernich (Red Hat), @martonsereg, @matyix, @waynz0r (BanzaiCloud) and me (Google), along with design contributions from various folks in environments WG and Istio TOC.
So far there are only internal docs but one of the checkins will be some public docs. Keep in mind it will take a while before the MVP is ready for folks to start playing with, this is something that will also be reflected in the repo docs.
Also the repo will be open for community contributions so we look forward to wider inputs into the project.

**Comment by StevenACoffman** [comment]
This work is being done in [istio operator](https://github.com/istio/operator) and [istio installer](https://github.com/istio/installer) if people wish to track it’s progress.

**Comment by sdake** [comment]
Alpha quality P0 item for 1.3.

**Comment by sdake** [comment]
Just to clarify, P0 items block a release.  The Istio project has specific guidelines around what blocks a release.  A new feature is not something that can generally block a release.  As a result, all operator work is P1+.

**Comment by howardjohn** [comment]
This is shipped! https://istio.io/docs/setup/install/operator/

There is still lots to do though, anyone interested please take a look at https://github.com/istio/operator/ or issues with the label `area/environments/operator`.
