### ISSUE TITLE
[test-framework] Integrate Galley into the Test Framework for Local Environment.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#9347]
Currently, the Local environment of the test framework uses Mixer's file-based APIs and Pilot's in-memory APIs to push configuration. We should make Galley as the sole way of distributing config in the system to these components in the local environment. 

When the test framework starts up in Local environment, it should *always* startup and initialize Galley. When environment.Configure is called, the configuration should be pushed to Galley (initially through a file-based model that Galley currently supports. Over time, it can be purely in memory).

The local versions of the other components (i.e. Mixer and Pilot) should be configured to use the MCP protocol to get their configuration from the local Galley.

**Comment by irisdingbj** [comment]
sorry for late. working on this now

**Comment by irisdingbj** [comment]
@ozevren   code is in: https://github.com/istio/istio/pull/10617

**Comment by ozevren** [comment]
With the new framework refactroring, this is already done.
