### ISSUE TITLE
can't get service graph to work 

### ISSUE THREAD

**Issue by linsun** [istio/istio#935]
following instructions on https://istio.io/docs/setup/kubernetes/quick-start.html#verifying-the-servicegraph-service on a k8s 1.7.4 on bluemix, but service graph doesn't work.  The page seems to trying to load, and I see the Tiny example as the title but no other content.  the log is pretty empty:

```→ kubectl get pods -n istio-system
NAME                                READY     STATUS    RESTARTS   AGE
grafana-579678665-zsffk             1/1       Running   0          5m
istio-ca-1144596003-mkhwj           1/1       Running   0          11m
istio-egress-3154791461-n5293       1/1       Running   0          11m
istio-ingress-2908173285-8chtb      1/1       Running   0          11m
istio-initializer-184129454-zdgf5   1/1       Running   0          10m
istio-mixer-2151117871-nhkv2        2/2       Running   0          11m
istio-pilot-1744039731-jptf7        1/1       Running   0          11m
prometheus-4086688911-8gpjm         1/1       Running   0          5m
servicegraph-3304329788-l6wpg       1/1       Running   0          5m

# linsun at linsun in ~/go/src/istio.io/istio on git:master ● [16:37:43]
→ kubectl get pod -n istio-system -l app=servicegraph -o jsonpath='{.items[0].metadata.name}
quote> 

# linsun at linsun in ~/go/src/istio.io/istio on git:master ● [16:39:30]
→ kubectl get pod -n istio-system -l app=servicegraph -o jsonpath='{.items[0].metadata.name}'
servicegraph-3304329788-l6wpg%                                                                                                      
# linsun at linsun in ~/go/src/istio.io/istio on git:master ● [16:39:33]
→ kubectl logs servicegraph-3304329788-l6wpg -n istio-system
2017/09/25 20:32:36 Starting servicegraph service at :8088
```
 http://localhost:8088/graph returned 
```{"nodes":{},"edges":[]}```

**Comment by gyliu513** [comment]
@linsun you may also want to deploy bookInfo if want to see some graphs.

BTW: There are three endpoints for servicegraph as here https://github.com/istio/mixer/tree/master/example/servicegraph#servicegraph-service

- /graph which provides a JSON serialization of the servicegraph
- /dotgraph which provides a dot serialization of the servicegraph
- /dotviz which provides a visual representation of the servicegraph

**Comment by zeroum** [comment]
The graph appears after deploying some services, like BookInfo. In the BookInfo guide, you can get your GATEWAY_IP in Bluemix by running `bx cs worker-get YOUR_WORKER_ID --json | jq '.publicIP' -r`

Anyways, it's a bit misleading to have that servicegraph section in the quick start doc w/o any services deployed to show.

**Comment by linsun** [comment]
@gyliu513 thanks, i would expect some basic info without bookinfo, but i'll deploy that shortly.

@douglas-reid fyi, tried to reinstall  prometheus, grafana and servicegraph using latest yaml from istio/istio,  still hit the same thing as described earlier.

**Comment by linsun** [comment]
@gyliu513 @zeroum you guys were right, after installing bookinfo, the data comes in. I'll try reword this doc a bit as it is misleading.

**Comment by douglas-reid** [comment]
@linsun no need to update the old doc. i've sent out a PR for review that removes that doc and replaces it with a add-on focused doc. we should work on making the new one clearer.

**Comment by linsun** [comment]
can you link your new PR here?  @douglas-reid

**Comment by douglas-reid** [comment]
@linsun https://github.com/istio/istio.github.io/pull/524

**Comment by linsun** [comment]
thank you @douglas-reid!  I merged my PR in as it has other clean-ups and reviewed.  Sorry I didn't know you already had  istio/istio.github.io#524.

**Comment by douglas-reid** [comment]
Shall we close this issue now?
