### ISSUE TITLE
failed to query scale subresource for Deployment/default/istio-pilot: deployments/scale.extensions "istio-pilot" not found

### ISSUE THREAD

**Issue by SFHfeihong** [istio/istio#9353]
**Describe the bug**
failed to query scale subresource for Deployment/default/istio-pilot: deployments/scale.extensions "istio-pilot" not found
**Expected behavior**
I think it should query scale subresource for Deployment/istio-system/istio-pilot rather than the default namespaces.
**Version**
Istio version: 1.0.2
k8s version: 1.9.3
**Installation**
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
kubectl apply -f install/kubernetes/istio-demo.yaml
**Environment**
OS: centos7.2
etcd: 3.2.22

**Comment by ymesika** [comment]
This has already been fixed upstream since v1.0.2.
The `HorizontalPodAutoscaler` for `istio-pilot` was indeed in default NS in the `istio-demo.yaml` file.
As a workaround (until next release) you can modify the file and manually add the namespace.
