### ISSUE TITLE
Create a custom VM image for circleci VM testing

### ISSUE THREAD

**Issue by ayj** [istio/istio#9363]
xref: https://circleci.com/docs/2.0/vm-service/
￼￼￼￼￼
(from @costinm in slack)
> It seems Circle can now customize the image used for the machine executor. So we can do the same tricks we do for the 'build' image - pre-install all the tools we need at the same version used for build. And I guess we can enable docker layer caching too - which will save even more time. The current machine executor uses go 1.9 - so it may be worth doing this just to get to 1.11. I would also bring the circle docker image at the same level and  include a stable goimports/gofmt, etc. Maybe even a stable linter - pretty much all the stuff we 'go get' or download (except envoy) can be cached and reused

**Comment by ibm-jason** [comment]
/cc @ayj Hi there! 👋 

I'm new to the Istio community, and looking for things to tackle. Is this still a valid task?

**Comment by ayj** [comment]
@hklai @costinm - do we still need a custom VM image for circleci testing?

**Comment by ibm-jason** [comment]
@hklai @costinm - bumping this issue.... any news here?

**Comment by hklai** [comment]
No update from me. I have not been working much on circle testing.

**Comment by ibm-jason** [comment]
@ayj not sure if this is needed any longer. @costinm, @hklai can you confirm?

**Comment by howardjohn** [comment]
No longer needed, we have migrated to prow
