### ISSUE TITLE
Sidecar uses a large amount of memory

### ISSUE THREAD

**Issue by evrardp** [istio/istio#9367]
**Describe the bug**

When I inject the istio sidecar in a pod, the memory consumption of this pod increases by ± 1Gb, which seems to be enormous.

I've followed the tls authentication page (https://istio.io/docs/tasks/security/authn-policy/) and created some deployments with the httpbin and sleep services.  In the namespace foo and bar, a pod uses ± 1Gb memory, but in the legacy namespace (without sidecar), it's around 30Mb.

I see the same behavior with our own microservices.

When I get the stats on the port 15.000 on the envoy, I see a very large number of entries for services, and also that:
```
listener_manager.listener_added: 164
listener_manager.listener_create_failure: 0
listener_manager.listener_create_success: 1312
listener_manager.listener_modified: 0
listener_manager.listener_removed: 0
listener_manager.total_listeners_active: 164
listener_manager.total_listeners_draining: 0
listener_manager.total_listeners_warming: 0
runtime.admin_overrides_active: 0
runtime.load_error: 0
runtime.load_success: 0
runtime.num_keys: 0
runtime.override_dir_exists: 0
runtime.override_dir_not_exists: 0
server.days_until_first_cert_expiring: 83
server.hot_restart_epoch: 0
server.live: 1
**server.memory_allocated: 708540872
server.memory_heap_size: 901324800**
server.parent_connections: 0
server.total_connections: 0
server.uptime: 695
server.version: 0
server.watchdog_mega_miss: 31
server.watchdog_miss: 163
stats.overflow: 425093
```
So I guess the large memory consumption is due to the number of services on the cluster (around 3150 services in all namespaces)...

**Expected behavior**

The memory footprint of an istio sidecar should be much lower.

**Version**
```
Istio version: 1.0.2
k8s version: 1.10.7
```
**Installation**
```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
kubectl apply -f install/kubernetes/istio-demo.yaml
```
**Environment**

Google Cloud Platform.

**Comment by evrardp** [comment]
For technical reasons, we had the temporary double all the services (so we have temporary ±6000 services defined now on the cluster).  The sidecar memory consumption has raised to 8.5Gb.  It seems it's not proportional, but exponential.

We will rapidly come back to ±3000 services, but it's blocking our investigations in vente-exclusive.com.  We cannot continue further, unfortunately....

Would it be possible to limit the number of services the sidecar is aware of ? (only some namespaces and not all for example ?)

I've tried the --concurrency flag and set it to 1, but I think it's not taken into account.

If you consider we have too many services, what would be the maximum number of services Istio could support ?

Thanks for any relevant information.

**Comment by gyliu513** [comment]
@rshriram @suryadu @mandarjog

**Comment by derekperkins** [comment]
cc @liljenstolpe

**Comment by mandarjog** [comment]
This is related to #7912

**Comment by howardjohn** [comment]
You can scope the config with https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/ now.

There have been a lot of changes/improvements to the memory usage since 1.0.7, do you see similar issues using 1.1.x or 1.2? If not I think this can be closed. Please reopen if you see similar issues even with Sidecar
