### ISSUE TITLE
What is circuit breaking designed in V1alph3, and why Istio discard CircuitBreakerPolicy which well defined circuit breaking in v1alph1

### ISSUE THREAD

**Issue by idouba** [istio/istio#9375]
In V1aph3 how can config Istio to do circuit breaking? and why Istio v1alph3 discard [CircuitBreakerPolicy](https://archive.istio.io/v0.7/docs/reference/config/istio.routing.v1alpha1.html#CircuitBreaker) which is well defined in v1alph1?

For example ,he following config  sets a limit of 100 connections and 1000 concurrent requests, and any host that fails 7 consecutive times with 5XX error code will be ejected for 15 minutes.
```
metadata:
  name: reviews-cb-policy
  namespace: default
spec:
  destination:
    name: reviews
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      maxConnections: 100
      httpMaxRequests: 1000
      httpMaxRequestsPerConnection: 10
      httpConsecutiveErrors: 7
      sleepWindow: 15m
      httpDetectionInterval: 5m
```
all the parameter well described a circuit breaker case.

And in v1alph3, I am pretty confused should use [ConnectionPoolSettings ](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ConnectionPoolSettings) or  [OutlierDetection](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#OutlierDetection) to do circuit breaker.

I have used netflix [Hystrix](https://github.com/Netflix/Hystrix) before,  accordingly,  [OutlierDetection](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#OutlierDetection)  is more similar to Hystrix circuit-breaker.

I am more confused when comparing the Istio connection(request) config with Envoy as following. It seems that Envoy's 4 important circuit_breakers  parameter which is defined upon [cluster/circuit_breaker](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto) ,several is defined in istio‘s [TCPSettings](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ConnectionPoolSettings-TCPSettings), and other's is in [HTTPSetings](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ConnectionPoolSettings-HTTPSettings)
That is several Istio ConnectionPoolSettings is configed for circuit_breakers  and others is just normal configured for [envoy's cluster]( https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto)

| Envoy   paramether          | Envoy upon   object      | Istio parameter          | Istio upon   ojbect |
| --------------------------- | ------------------------ | ------------------------ | ------------------- |
| max_connections             | cluster.circuit_breakers | maxConnections           | TCPSettings.        |
| max_pending_requests        | cluster.circuit_breakers | http1MaxPendingRequests  | HTTPSettings        |
| max_requests                | cluster.circuit_breakers | http2MaxRequests         | HTTPSettings        |
| max_retries                 | cluster.circuit_breakers | maxRetries               | HTTPSettings        |
| connect_timeout_ms          | cluster                  | connectTimeout           | TCPSettings.        |
| max_requests_per_connection | cluster                  | maxRequestsPerConnection | HTTPSettings        |

Christian Posta's [comparing-envoy-and-istio-circuit-breaking-with-netflix-hystrix](http://blog.christianposta.com/microservices/comparing-envoy-and-istio-circuit-breaking-with-netflix-hystrix/) well described the circuit breaking in isito and hystrix. Is there a more official doc described how to config circuit breaking in Istio in the current V1alph3？

**Comment by idouba** [comment]
@linsun @rshriram

**Comment by howardjohn** [comment]
Please see https://istio.io/docs/tasks/traffic-management/circuit-breaking/ and https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#OutlierDetection for configuring circuit breaking, as well as some other fields as you mentioned above. Istio APIs do not aim to provide a 1:1 mapping of Envoys, which is why they may not directly line up
