### ISSUE TITLE
Add Helm config for switch ingressGateway to expose as internal ELB

### ISSUE THREAD

**Issue by andelhie** [istio/istio#9380]
**Describe the feature request**
New Helm config for when deploying in to AWS to have a choice to expose the IngressGateway as a internet facing ELB or an internal facing ELB only. This feature is a simple addition to the service creation you just add an annotation with below line.
```
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

**Describe alternatives you've considered**
Was able to do this with the upgrade of the classic ELB to a NLB and while upgrading switching it to internal facing.

**Comment by sdake** [comment]
@andelhie we will see if we can introduce this RFE in 1.1.  I am not sure if it is possible, but will investigate.

Cheers
-steve

**Comment by sdake** [comment]
@andelhie can you take a look at this issue and see if the solution presented works for you?  Should be able to create a new `myvalues.yaml` directly and achieve desired result without modifying the helm chart itself.

https://github.com/istio/istio/issues/9037

Cheers
-steve

**Comment by sdake** [comment]
@andelhie The workaround in https://github.com/istio/istio/issues/9037 works in my testing, so closing this issue out.

If you disagree, feel free to reopen.

Cheers
-steve

**Comment by munrodg** [comment]
Closed per Steve's comments
