### ISSUE TITLE
Error: secrets "kiali" not found

### ISSUE THREAD

**Issue by li1191863273** [istio/istio#9392]
**Describe the bug**
use this
helm upgrade --recreate-pods --namespace istio-system --set grafana.enabled=true \
            --set kiali.enabled=true \
             istio \
             install/kubernetes/helm/istio
the kiali pod event

Error: secrets "kiali" not found

**Version**
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}

➜  ~ istioctl version
version.BuildInfo{Version:"1.1.0.snapshot.1", GitRevision:"45692c579c6d755194421540149a99ac4cb59528", User:"root", Host:"ac7ff4b30ee4", GolangVersion:"go1.10.1", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}

**Comment by sdake** [comment]
@li1191863273 Assume you are following the Kiali instructions here?

https://github.com/istio/istio/blob/44798c747a5a4483bafc810c35e568494d78cc99/install/kubernetes/helm/istio/README.md

(step 1)

**Comment by sdake** [comment]
Rather: 
https://github.com/istio/istio/blob/aa034934c7f2a2a265224061c066eae88a652703/install/kubernetes/helm/istio/README.md

step 5. :)

**Comment by jmazzitelli** [comment]
FYI: It was purposefully decided that we will NOT create the secret for Kiali automatically when installing - hence why the instructions tell the user that they should create their own credentials.

@sdake shows the install instructions where this is mentioned - it is also mentioned in the Kiali Task as well: https://preliminary.istio.io/docs/tasks/telemetry/kiali/#before-you-begin

**Comment by jmazzitelli** [comment]
FWIW: a recent change went into the helm charts - a kiali secret will be automatically created for you IF you deploy the demo profile (demo.yaml or demo-auth.yaml).

Other production installations (non-demo) still require the secret to be created. If this happens, kiali will still deploy and run, but the login screen will tell you about the problem.

See: https://issues.jboss.org/browse/KIALI-2303

**Comment by li1191863273** [comment]
yes， This issue can be closes
