### ISSUE TITLE
Config Propagation Verification

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#9411]
**Describe the feature request**
KNative folks requested a feature for verifying that a particular config (VirtualService in this case) has been propagated to sidecars.  Would like to expose an API (potentially in pilot) that allows a user to check whether a particular config has been propagated to sidecars.  This API may be called by istioctl (possible expansion of the `istioctl get all` command output) or by the Kiali dashboard to show a status for a particular config.

**Additional context**
There is a `proxy-status` istioctl command available, but that just verifies that a sidecar is up-to-date with what is in pilot - but does not verify that pilot has received the config and pushed said config to sidecars.

**Comment by ozevren** [comment]
This is already covered by https://github.com/istio/istio/issues/882, I believe.

**Comment by ozevren** [comment]
IMO, this should be closed in favor of #882. Any objections?
