### ISSUE TITLE
 istio-tracing and servicegraph end up in a CrashLoopBackOff after initial start

### ISSUE THREAD

**Issue by timfpark** [istio/istio#9414]
**Describe the bug**
Pods istio-tracing and servicegraph end up in a CrashLoopBackOff after initial start

{"level":"info","ts":1539891873.6724212,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1539891873.6729143,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":50000}}
{"level":"info","ts":1539891873.6745164,"caller":"tchannel/builder.go:94","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1539891873.674602,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"127.0.0.1:14267"}
{"level":"info","ts":1539891873.6750853,"caller":"standalone/main.go:187","msg":"Starting agent"}
{"level":"info","ts":1539891873.675734,"caller":"standalone/main.go:227","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1539891873.6757777,"caller":"standalone/main.go:237","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1539891873.7040489,"caller":"standalone/main.go:257","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
{"level":"info","ts":1539891874.6749003,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1539891874.6750093,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"127.0.0.1:14267"}
{"level":"info","ts":1539891874.6757677,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"}
{"level":"info","ts":1539891923.8808026,"caller":"standalone/main.go:298","msg":"Registering metrics handler with jaeger-query HTTP server","route":"/metrics"}
{"level":"info","ts":1539891923.8808954,"caller":"standalone/main.go:304","msg":"Starting jaeger-query HTTP server","port":16686}
{"level":"info","ts":1539891923.8809383,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}

**Expected behavior**
Istio to start correctly

**Steps to reproduce the bug**
Install Istio per the manual steps for "Option 2: Install Istio with default mutual TLS authentication" 

**Version**
$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Per Option 2: Install Istio with default mutual TLS authentication

**Environment**
Azure AKS 1.11.3 cluster

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2493402/istio-dump.tar.gz)

**Comment by douglas-reid** [comment]
Is this possibly another manifestation of the issues involved in https://github.com/istio/istio/issues/7675 ?
