### ISSUE TITLE
mixer: value type coverage in proto/config/IL

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#9415]
Mixer values type system is documented via https://github.com/istio/api/blob/master/policy/v1beta1/value_type.proto. However, internally the support for the types is not uniform. Some (email address and URI) are marked as experimental, and not always get handled correctly. Some (time stamp) may need further improvements.

The task is to increase e2e coverage for the entire set of types, or deprecate some of them as necessary.

/cc @douglas-reid

**Comment by kyessenov** [comment]
ref #10252

**Comment by kyessenov** [comment]
wakawakawaka

**Comment by douglas-reid** [comment]
This is a valiant goal. Unfortunately, with Mixer being deprecated (and the config model with it), I think that it is unlikely that this will get addressed. And so, I'm closing this issue.
