### ISSUE TITLE
multiple istio-ingressgateway

### ISSUE THREAD

**Issue by naveeng68** [istio/istio#9426]
Hi,
How we implement multiple istio ingress (i want to implement multiple AWS certificate each cert have different domain name And I want separate load balancer for each domain).

example: I want to deploy 2 application(abc, xyz) with diff domain in same cluster, Istio ingress Create one load balancer in AWS. both application exposed service taking to that load balancer (Under Route 53, External DNS service  point record set with istio-ingress load balancer)

But I want two ISTIO ingress (each application has his own istio load balancer) liek abc.com point to one istio load balancer and xyz.com point to other load balancer  .

How we use same in ISTIO? under istio-1.0.2/install/kubernetes/istio-demo-auth.yaml. which contexts I to use again with separate name?
like in nginx ingress controller we create one more ngnix controller. with separate name. its working perfect.

**Comment by naveeng68** [comment]
I am not install istio via helm, Could you please let me know how we add multiple istio via installing with mutua auth

**Comment by naveeng68** [comment]
> You can add multiple ingress gateway instances by adding entries in the "gateways" property of the helm values.
> 
> You will have to specify unique host ports but this will generate a loadbalancer for each.
> 
> See [values-istio-gateways.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-gateways.yaml) as a reference.
> 
> To reference it in the gateway you will need to make a selector that matches the ingress-gateway you need.

I am not install istio via helm, Could you please let me know how we add multiple istio via installing with mutua auth

**Comment by Sanjanare** [comment]
@yciabaud https://github.com/istio/istio/issues/14625 can you please check this have similar issue, am i doing ryt?
newbee
