### ISSUE TITLE
issue with the command sudo ./oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial

### ISSUE THREAD

**Issue by RakeshDevUK** [istio/istio#9428]
Unable to execute below command, always ends up in error 

sudo ./oc apply -f <(istioctl kube-inject -f ../../kubernetes/Deployment.yml) -n tutorial Command is never executed normally gives a lot of pain since the istio release.

Getting below error on the openshift installation done locally on centos .
Error: could not read valid configmap "istio" from namespace  "istio-system": **Get http://localhost:8080/api/v1/namespaces/istio-system/configmaps/istio: dial tcp [::1]:8080: connect: connection refused -** Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists
error: the path "/dev/fd/63" does not exist
Already checked below steps:-
1. istio named config are already present 

QQ:- Why is trying to connect on 8080 when my openshift is running on 8443?

**Comment by RakeshDevUK** [comment]
any specific setup required for kube-inject?

**Comment by jwendell** [comment]
Why are you running this command with sudo? That means it's being executed under `root` user, and probably the kubeconfig file for root user doesn't exist under `/root/.kube`.

Try removing `sudo` from your command.

Also, if you're using Openshift, make sure to give enough permissions to your cluster/service accounts.
