### ISSUE TITLE
Release Assets do not include grafana dashboards

### ISSUE THREAD

**Issue by k** [istio/istio#9437]
**Describe the bug**
When downloading release assets and attempting to install with helm there are no grafana dashboards because the `dashboards` folder is not included in the assets.

**Expected behavior**
If the helm folder is included in release assets, it should include all the files needed to install via the helm chart.

**Steps to reproduce the bug**
Go to releases tab, download 1.1.0-snapshot.1 or 1.0.2 linux/osx tar.gz files. unzip and observe there is no `install/kubernetes/helm/istio/charts/grafana/dashboards` folder.

**Version**
1.1.0-snapshot.1

**Installation**
helm

**Comment by douglas-reid** [comment]
@hklai @mandarjog I believe we fixed this for `release-1.0` branch. Did we miss a cherry-pick somewhere?

**Comment by hklai** [comment]
@douglas-reid could you point me to the PR that fixes this in release-1.0?

**Comment by douglas-reid** [comment]
There is this, which appears to be on `master`, so I'm a bit confused now:

https://github.com/istio/istio/pull/8953

**Comment by douglas-reid** [comment]
How do we fix?  Or do we not?

**Comment by hklai** [comment]
The fix is supposedly in https://github.com/istio/istio/releases/tag/1.1.0-snapshot.2, which has just been published.
