### ISSUE TITLE
Support multiple IP addresses for proxy in consul deployment

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#9441]
**Describe the feature request**
I ran into a multi-IP addresses problem when trying to integrate Istio with our product, here is the situation I'm facing:

* The applications are deployed in K8S.
* We don't use "K8S service" for service discovery, instead, we're using Consul as the service registry.  The two main reasons are:
  1. We need multiple network Interfaces in the POD, so we developed our own CNI implementation, and multiple network interfaces can't work well with K8S service.
  2. Some of the legacy applications are not typical Microservices, they have multiple APIs which need to be registered independently. 
* We deploy Istio control plane components(Pilot, Mixer, Istio API Server) on the host, and deploy apps in K8S cluster,  an Envoy proxy is deployed alongside the application in each pod.
* Services are registered to the Consul, and Consul is integrated with Istio Pilot.
* Each pod has two network interfaces(Let's say network1 and network2), for some reasons, some services are registered via network1, others are registered via network2.

The pilot is using the IP Address reported by Envoy proxy to build the inbound listener(The IP address is conveyed by the id in the node structure of the xDS request, such as `sidecar~192.168.206.23~productpage-v1-54b8b9f55-bx2dq.default~default.svc.cluster.local`).
In case that there're two IP Addresses in the pod, only the IP address of the first network interface is sent to Pilot, so when services in the pod are registered via the IP address of the second network interface, the Pilot doesn't know these services are located in the same pod with the proxy and don't build inbound listeners for them. This causes an infinite loop when the envoy receiving an inbound request and result in envoy crash because of running out of file descriptors.

Although multiple network interfaces in a pod may sound rare, this can also happen in VM/bare metal deployment of Istio(without K8S).

`

                      +------+         +------+
                      |Pilot +-------->+Consul|
                      ++----++         +---+--+
                       ^    |              ^
                       |    |Svc1 as       |
            xDS request|    |outbound      | Register Svc1
            (IP 1)     |    |listener      | (IP 2)
                       |    v              |
                     +-------------------------+
                     | +------+       +-----+  |
                     | |Envoy |       |Svc 1|  |
                     | +------+       +-----+  |
                     |         Pod/Host        |
                     +-------------------------+
                        |--|           |--|
                        +--+           +--+
                        IP 1           IP 2

`

**Describe alternatives you've considered**
Allows proxy to send multiple IP addresses to Pilot, Pilot use all the IP addresses to tell which services are located with the proxy and build the inbound listeners for that proxy.

**Additional context**
If this request does make sense, I'd be glad to contribute the codes.  It's almost done in my current working project.

**Comment by baodongli** [comment]
Thanks for creating the issue. As it stands right now, only podIP is available through k8s API. And as you've found out, the podIP is passed to pilot from the proxy. 

But it might be possible to do this with the help of istio CNI that we are developing since it's aware of all the IPs assigned to the POD.

**Comment by zhaohuabing** [comment]
Hi @baodongli ,  should we address this issue in the data plane API rather than in the Istio CNI?  We know that Istio can run with or without kubernetes. 

The workaround I'm using now is to pass all the IPs to Pilot via the Node Metadata of the discovery request. This approach is compatible with the current data plane API and it solves the issue in both the kubernetes and consul deployment of Istio.

https://github.com/DexMesh/istio/commit/97417e852e3e1575c0bb85b71fb1c2a9277f6b5c

**Comment by baodongli** [comment]
@zhaohuabing the change looks good to me. My question to you is how you passed the multiple IP addresses to pilot agent which builds the node metadata. I guess that it was manually entered in the manifest?

**Comment by zhaohuabing** [comment]
@baodongli We can directly get the IPs of the node in pilot-agent using go net package, this approach works both with and without kubernetes: https://github.com/DexMesh/istio/commit/e6ce750d0cb85662e4140599581654acf1b4b3a1

**Comment by baodongli** [comment]
That's right, pilot agent can simply grab IPs from the interfaces.

**Comment by zhaohuabing** [comment]
Hi guys, could we merger this enhancement to the next release if it makes sense?

**Comment by baodongli** [comment]
Why not propose a PR for it?

**Comment by zhaohuabing** [comment]
This has been fixed by https://github.com/istio/istio/pull/9688
