### ISSUE TITLE
No need watch certificate 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#9476]
In belowing code, i donot think the watcher is necessary, should load cert directly from file system.

https://github.com/istio/istio/blob/65419adeaf1c442481db425f3f8bba552aaa43d7/pkg/mcp/creds/create.go#L28-L31

https://github.com/istio/istio/blob/65419adeaf1c442481db425f3f8bba552aaa43d7/pkg/mcp/creds/create.go#L42-L45

/cc @ozevren I am not sure if there is other intention.

**Comment by hzxuzhonghu** [comment]
Maybe #37877 is not a concern, if we load cert directly.

**Comment by ayj** [comment]
Re-loading the cert per tls connection is certainly simpler. Some potential downsides to consider:

1) error checking is deferred to connection time. We won't be able to reuse the previous cert (assuming its still valid) if the new cert fails to load.
2) key/cert loading may be replaced by SecretDiscoveryService (SDS) which is conceptually similar to the file watcher approach
3) file I/O in the connection setup path. Probably not a huge deal for the normal case when auth-check passes.

**Comment by hzxuzhonghu** [comment]
But the connection is long-running grpc, so will not call the reload very often.  Unless connection error and reconnect.

**Comment by ayj** [comment]
re: (3), the normal successfully case wouldn't be an issue. The not-authorized path would be more costly.

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/9622 address the immediate need for properly watching certs. Longer term, this will be replaced with  SecretDiscoveryService (SDS).
