### ISSUE TITLE
Mixer policy hardcoded to fail close

### ISSUE THREAD

**Issue by rshriram** [istio/istio#9483]
**Describe the bug**
```shriramr@shriramr-a01:~/go/src/istio.io/istio/pilot $ git grep -i fail_close
pkg/networking/plugin/mixer/mixer.go:           NetworkFailPolicy: &mccpb.NetworkFailPolicy{Policy: mccpb.FAIL_CLOSE},
```

A few folks I work with have Istio 1.0.x in production. They report seeing 503s anytime istio policy pod's health goes down. They would rather have fail open behavior than the current fail close behavior, but there is no way to configure this.

**Expected behavior**
Need a way to configure the failure mode to fail open through Helm.

**Version**
Istio 1.0.x

We need this in 1.0.x as well as 1.1..

**Comment by mandarjog** [comment]
@yangminzhu Please also submit the api PR in 1.0 brach.
If you could fix pilot  it in 1.0 branch first that would be great.

**Comment by douglas-reid** [comment]
Can we close this now?

**Comment by yangminzhu** [comment]
Yes, the work is done for both 1.0 and 1.0.
