### ISSUE TITLE
FR: Need way to set `FAIL_OPEN` for istio-policy service

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#9485]
**Describe the feature request**
Right now, `FAIL_CLOSED` is hard-coded in the mixer plugin for pilot. This prevents operators from using Istio Policy options in situations when they want the behavior of falling back to allow all traffic in cases when the policy service cannot be reached.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/istio/istio/pull/6616#discussion_r198968125

**Comment by douglas-reid** [comment]
Related to: #9483

**Comment by douglas-reid** [comment]
@yangminzhu thanks!  can we close this FR now?

**Comment by yangminzhu** [comment]
@douglas-reid Yes, Shriram have cherry picked this to 1.1 branch as well.
