### ISSUE TITLE
Galley Ingress missing

### ISSUE THREAD

**Issue by costinm** [istio/istio#9490]
When Galley is enabled, I don't see any Ingress resource - AFAIK we still need to support k8s Ingress.

I think this is blocker for turning on galley - it doesn't seem possible to use both k8s config store and galley at the same time, and I don't think in 1.1 we can drop support for Ingress.

**Comment by costinm** [comment]
(tested by using /debug/configz in pilot, on a cluster that has Ingress resources)

**Comment by ozevren** [comment]
Is there a test for this?

**Comment by costinm** [comment]
For Ingress conversion in pilot - pretty sure there are some. 
E2E - we used to have one in simple test, but probably got converted to Gateway.

**Comment by costinm** [comment]
But we do test Ingress on load tests part of release qualification - just not automated yet.

**Comment by ayj** [comment]
Pilot k8s ingress code - https://github.com/istio/istio/tree/master/pilot/pkg/config/kube/ingress. The [conversion](https://github.com/istio/istio/blob/5ab881ad8563e29748b6c5427ab6b231b1d40b9f/pilot/pkg/config/kube/ingress/conversion.go#L123) [functions](https://github.com/istio/istio/blob/5ab881ad8563e29748b6c5427ab6b231b1d40b9f/pilot/pkg/config/kube/ingress/conversion.go#L64) are already exported, though we'll need to [convert](https://github.com/istio/istio/blob/5ab881ad8563e29748b6c5427ab6b231b1d40b9f/pilot/pkg/config/kube/crd/conversion.go#L84) from Pilot's `model.Config` type to the k8s or MCP proto form. 

I *think* the Ingress StatusSyncer is [handled by the k8s registry path](https://github.com/istio/istio/blob/fdb5563d1e41f086e2e583cdae3899d947a12334/pilot/pkg/bootstrap/server.go#L665-L688) right now.
