### ISSUE TITLE
Galley 'sync complete' issues

### ISSUE THREAD

**Issue by costinm** [istio/istio#9491]
Running some manual tests, 2 things I noticed:
1. Galley 'sync complete' happens after the first connections to pilot. This results in possibly invalid config (some updates may be in). Not sure if it's a regression or just more likely to happen due to the additional setup. Old code has some protection - if HasSynced is false the events are suppressed, and for endpoints we wait for HasSynced ( but it may also experience some corner cases ).

2. If a CRD is missing - it gets into a fast retry loop and never completes 'has synced'. While in the default installer typically CRDs are installed correctly, not sure if in all environments we can rely on that. At least some timeout ( to not block hasSynced) and backoff (to not kill apiserver) are needed.

**Comment by ayj** [comment]
Fixed by https://github.com/istio/istio/pull/9702 and https://github.com/istio/istio/pull/9553
