### ISSUE TITLE
provide option to skip peer cert verfication when fetching jwt pubkey 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#9505]
**Describe the bug**
[customer request]
today in pilot, if jwt uri starts with https, pilot fetching jwt pubkey through [secureHTTPClient](https://github.com/istio/istio/blob/master/pilot/pkg/model/jwks_resolver.go#L132); 

provide option to skip peer cert validation using [httpclient](https://github.com/istio/istio/blob/master/pilot/pkg/model/jwks_resolver.go#L117) that set ```InsecureSkipVerify=true``` since in dev env there is no auth server.

**Comment by yangminzhu** [comment]
I think it's more accurate to say `some dev env uses certs issued by their custom ca cert that is not included in pilot's root CA bundle` instead `there is no auth server in dev env`.

**Comment by costinm** [comment]
Only for specific URLs I hope.

**Comment by pitlv2109** [comment]
Totally forgot about this. Do we still need this?

**Comment by incfly** [comment]
https://github.com/istio/istio/issues/15086 seems better in terms of security.

**Comment by yangminzhu** [comment]
Not needed, closing for now.
