### ISSUE TITLE
Pods land in Kube-System with auto injection and istioctl not being in the Path

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#9506]
**Describe the bug**
Not having Istioctl in the path causes deployment pods to land in kube-system.

**Expected behavior**
Shouldn't have affected the default namespace 

**Steps to reproduce the bug**
1. Have a Kubernetes cluster up and running.
2. execute:
```
$ helm template install/kubernetes/helm/istio --name istio --set global.mtls.enabled=false --namespace istio-system > istio.yaml
```
3. Apply istio.yaml:
```
$ kubectl create namespace istio-system 
$ kubectl apply -f istio.yaml
```
4. Execute below commands to label the default namespace and create the Bookinfo test app.
```
$ kubectl label namespace default istio-injection=enabled
$ kubectl apply -f platform/kube/bookinfo.yaml
```
5. Execute ` kubectl get pods ` and verify that there are no resources. (the resources are in kube-system namespace)

**Version**
I am using the version 1.1.0.snapshot.1. **BUT I do not have istioctl in the path.**

**Installation**
Part of the steps to reproduce the bug.

**Environment**
Tried in Minikube and AKS

**Additional Information**
Potentially this is expected when you don't put **Istioctl** in the path, but then we might clarify the purpose and effects of **istioctl** in more details as the below description [from the docs](https://istio.io/docs/setup/kubernetes/download-release/) seems to be incorrect:

```
The istioctl client binary in the bin/ directory. istioctl is used when manually injecting Envoy as a sidecar proxy and for creating routing rules and policies.
```

**Comment by ayj** [comment]
`istioctl` should have no effect on where your deployments/pods/etc are created with kubectl. 

You could check that your current kubectl context doesn't change the default namespace from `default` to `kube-system` with the following command. 

`$ kubectl config get-contexts $(kubectl config current-context)`
