### ISSUE TITLE
[Istio 1.1.snapshot2] cannot run helm template with demos value yaml

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#9509]
**Describe the bug**

Cannot use Helm to install Istio 1.1.snapshot.2. Running helm template with the demo values yaml causes an error.

This was discussed here: https://groups.google.com/forum/#!msg/istio-users/dedvy7HRTTE/Rv8g-ZjoBgAJ

**Expected behavior**
helm template to build the full yaml that I can use to apply via kubectl or oc.

**Steps to reproduce the bug**
Download 1.1.snapshot.2 and run "helm template" with the demo values yaml:

```
$ helm template --values install/kubernetes/helm/istio/values-istio-demo.yaml install/kubernetes/helm/istio --name istio --namespace istio-system 
```

The error I get when I run that command is: 

``` 
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, certmanager 
``` 

All of those appear to be in the install/kubernetes/helm/subcharts directory. 

**Version**
istio 1.1.snapshot2

**Installation**
That's the problem :) See description.

**Environment**
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Comment by matejgera** [comment]
Had the similar issue today after trying to perform `helm install`. Stranegly what helped was to execute following from istio's root folder:

`helm dependency update install/kubernetes/helm/istio`

**Comment by ayj** [comment]
This seems to be a documentation issue (see https://github.com/istio/istio.io/issues/2787). Closing this since https://github.com/istio/istio.io/issues/2787 is already tracking the doc fix.
