### ISSUE TITLE
Multicluster, consul and mesh expansion likely broken in 1.1

### ISSUE THREAD

**Issue by costinm** [istio/istio#9515]
https://github.com/istio/istio/pull/9397 returns an error if a POD IP is not found in k8s.

It seems this results in grpc error - mesh expansion at least seems broken - but looking at the code consul and multicluster will be broken too.

**Comment by ayj** [comment]
@costinm, why is this tagged for 1.1? #9397 was merged into master.

**Comment by costinm** [comment]
So it didn't make it into 1.1 ? Didn't check - still needs to be reverted
either way.

**Comment by hzxuzhonghu** [comment]
It is in 1.1, and ptal #9522 and #9523.

**Comment by hzxuzhonghu** [comment]
can close now
