### ISSUE TITLE
Honor trace sampling decisions when using mixer

### ISSUE THREAD

**Issue by negz** [istio/istio#9530]
**Describe the feature request**
I'd like mixer to honor the [`x3-b3-sampled` HTTP header](https://github.com/openzipkin/b3-propagation#sampling-state-1). This header is set by upstream tracers to indicate that a request was sampled for tracing and should therefore be traced at further hops.

High traffic meshes use a low trace sample rate (i.e. 1% of requests or less). With each hop making a sampling decision without knowledge of upstream decisions it's unlikely that any one request will actually be sampled all the way along the route.

I'd be happy to contribute this functionality to the existing Stackdriver and SignalFX tracing implementations, assuming there was a point in doing so given their impending migration to out of process adapters. This would look something like:

1. Add a `sampled` field to the existing `tracespan` template such that it could be extraced from `x-b3-sampled` similar to how the other `x-b3-` propagation headers are populated.
2. Use the [existing Opencensus B3 propagation code](https://github.com/census-instrumentation/opencensus-go/blob/3a82755/plugin/ochttp/propagation/b3/b3.go#L101) to extract the sampling decision from the `tracespan`.
3. Force sampling of the relevant traces.

**Comment by douglas-reid** [comment]
@negz I believe you are concerned with proper trace sampling for Mixer tracespan *adapters*. Is that correct?

One thing you might want to consider the recently added API-level support for sampling in general.  We have not yet started on the implementation yet, and therefore have plenty of time to ensure that it meets the use case you are describing here.

See: https://github.com/istio/api/blob/master/policy/v1beta1/cfg.proto#L344

I believe that we should be able to craft an attribute expression to properly setup sampling here (or add a different sampling type to the API). This would allow sampling for traces to follow the same general mechanism as will be used elsewhere.

Does that make sense?

I'm happy to coordinate on details, etc.

**Comment by negz** [comment]
> I believe you are concerned with proper trace sampling for Mixer tracespan adapters.
That's correct!

I'm currently experimenting with using the Stackdriver adapter to trace requests through the mesh. Many of my requests have already begun a trace when they first enter the Istio mesh, so I'd like them to continue those traces regardless of the sampling decisions Istio hops make.

Your proposal sounds good, as long as it can be done in a fashion that can interoperate with non-Istio tracing implementations. i.e. Assume I run Istio in my Kubernetes clusters, but run an Istio-unaware API gateway at my network edge that routes requests to each Kubernetes cluster's Istio gateway. I want to have my API gateway (instrumented via Opencensus, and using Zipkin B3 header trace propagation) make trace sampling decisions and have Istio honor those decisions.

It sounds like what you suggest is the better/more sustainable pattern here, but I'm also looking for a quick fix. I'll probably fork Mixer and make the changes I suggested for my local environment; would it be worth me submitting a PR with said changes given they'd soon be replaced?
