### ISSUE TITLE
Istio sidecar telemetry vs. GCP stackdriver logging agent

### ISSUE THREAD

**Issue by psaia** [istio/istio#9562]
While there are instructions for setting up a [Stackdriver logging agent](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/stackdriver/) for Istio + GCP, I couldn't find a recommended strategy to deal with the default fluentd/stackdriver logging agent which gets installed on a GCP k8s cluster. Is it recommended to remove this if using Istio? This may be considered out of scope for istio's documentation, but the correct path is not obvious to me. Using the default logging agent without any configuration, everything works great (logging/monitoring via stackdriver, istio/envoy routing, etc), but it would be nice to see this confirmed as an OK strategy.

Currently, I don't have sidecars injected and this is working fine since `mtls.enabled=false`. Istio is just being used for external routing/loadbalancing and basic internal networking. 

It feels somewhat wasteful and _dirty_ to not use Istio for telemetry. However, it appears the sidecar doesn't work with some helm charts (like [postgres](https://github.com/istio/istio/issues/1985)) and I'd rather not lose observability for these types of services running without a sidecar. Any clarification around this would be greatly appreciated.

**Comment by douglas-reid** [comment]
@psaia The stackdriver logging agent operates at a different level from the SD adapter for Mixer that is available to be exposed via Istio. The fluentd agent will grab all the application logs -- something that Istio is not currently setup to handle. The Stackdriver adapter for Istio allows you to provide customizable logging (and metrics, trace, edge collection) based on request/response metadata ((info about stuff flowing through the proxy). 

If you don't have sidecars injected, there won't be much in the way of telemetry reported through Istio (and thus through the Stackdriver adapter).

The documentation on the Stackdriver adapter needs a significant upgrade (it was pending the public rollout of some metrics schemas which *just* happened. see: https://cloud.google.com/monitoring/api/metrics_other#other-istio.io).

Adding clarity around these issues is on the agenda, to be sure. I hope to have more to share soon.

**Comment by psaia** [comment]
@douglas-reid That makes a lot of sense. Thank you for explaining it and for the great work.
