### ISSUE TITLE
Helm: cannot override mixer/pilot's proxy image

### ISSUE THREAD

**Issue by rshriram** [istio/istio#9563]
setting proxy/image in helm/istio/values.yaml to something like docker.io/rshriram/shriram-test-proxy:0.0.1 results in a yaml like this for istio-pilot and istio-mixer

```
 - name: istio-proxy
    image: "gcr.io/istio-release/docker.io/rshriram/shriram-test-proxy:0.0.1:master-20181023-09-15"
    imagePullPolicy: IfNotPresent
```

This is sure to break all installs if someone uses a custom proxy image.

**Comment by rshriram** [comment]
cc @hklai

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/9565

**Comment by munrodg** [comment]
Fixed
