### ISSUE TITLE
"unused" pod ports added to iptables but not to sidecar

### ISSUE THREAD

**Issue by arnecls** [istio/istio#9572]
**Describe the bug**

Create a pod witch a container that exposes 3 ports (let's call them A-C).
Use A in the readiness probe
Use B in the healthiness probe
C is left "unused"

In the istio-init container logs you can see, that ingress rules for all 3 ports are being generated.
However - as istio-pilot only adds service ports and "management" ports, i.e. port A+B to the proxy, port C cannot be accessed from the outside.
In our case this is problematic because C exposes prometheus metrics which are scraped by a mesh-external instane.

**Expected behavior**

Port C should either be added to the sidecar or NOT added to iptables.

**Steps to reproduce the bug**

See description.

**Version**

istio 1.0.2
kubernetes 1.10.7-gke.6

**Comment by fuxu** [comment]
you should remove definition of C port in your pod template.

then it will not appear in your iptable chains

**Comment by arnecls** [comment]
That would be a short-term fix, yes, but IMO this issue is very confusing for people who e.g. use the pod spec as a kind of documentation. It took us two days to figure out and required a look into the code as this behaviour seems not to be mentioned anywhere in the docs.
