### ISSUE TITLE
Support query parameters in the expression language

### ISSUE THREAD

**Issue by theganyo** [istio/istio#9576]
**Describe the feature request**
Add support for templates and rules to consider a request's query parameters in a manner similar to a request's headers. In other words, be able to reference them directly via string map expressions, eg:

```
request.queryParameters["test"]
```

Today you must:
Rule expressions: Write a regex against request.path.
Attribute expressions: Specify request.path and expect the adapter to parse.

**Comment by bianpengyuan** [comment]
The feature should be ready in 1.1 and attribute reference doc already has that. See request.query_params in https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/

**Comment by kyessenov** [comment]
Great. It's not in preliminary stage right now, but the code has been there for awhile.
Let us know if it doesn't work @theganyo

**Comment by theganyo** [comment]
FYI @geeknoid

**Comment by theganyo** [comment]
Thanks @kyessenov and @bianpengyuan. Good to see that's coming soon. Just curious, has there been any discussion of supporting access of cookies from headers?
