### ISSUE TITLE
Need to add namespace for tracing operation_name to differentiate the services with same name under different namespace

### ISSUE THREAD

**Issue by osswangxining** [istio/istio#9579]
**Describe the bug**
{{ Succinctly describe the bug }}
Currently if two services with same name under different namespace in Kubernetes, the Jaeger tracing cannot differentiate them. Looks like the operation name assigned from Istio does not include the namespace.
**Expected behavior**
{{ What did you expect to happen? }}
Need to add namespace for tracing operation_name to differentiate the services with same name under different namespace
**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by objectiser** [comment]
The namespace is now used in service name #7803 which will be available in version 1.1.

**Comment by osswangxining** [comment]
@objectiser  thanks for your info and looking forward to learn from version 1.1.
