### ISSUE TITLE
Proxy status reports proxy version incorrectly

### ISSUE THREAD

**Issue by Stono** [istio/istio#9597]
As you can see the proxy is on 1.0.3

```
❯ kn logs ingress-nginx-external-controller-5878b8df7c-rc7bp --follow istio-proxy
2018-10-29T10:42:28.130078Z     info    Version root@0ead81bba27d-docker.io/istio-1.0.3-a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3-Clean
```

proxy-status says otherwise:
```
❯ istioctl proxy-status
PROXY                                                                      CDS        LDS        EDS               RDS        PILOT                            VERSION
ingress-nginx-external-controller-5878b8df7c-rc7bp.ingress-nginx           SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-55c5b77c8b-tmnks     1.0.2
```

**Comment by Stono** [comment]
Hi all
This is still a problem in 1.0.4, and kind of annoying when you're trying to do a cluster upgrade and check all the sidecars are OK.

**Comment by Stono** [comment]
And still a problem in 1.0.5!

**Comment by dwradcliffe** [comment]
This is still a problem in 1.1.1, apparently.

inspecting pod:
`image: docker.io/istio/proxyv2:1.1.1`
istioctl proxy-status:
```
NAME                                                   CDS        LDS        EDS               RDS          PILOT                            VERSION
web-7b6d4ffd59-5x5lm.foo-bar                SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-5996947b5f-f86dk     1.1.0
```

istioctl proxy-config bootstrap:
```
{
    "bootstrap": {
        "node": {
            "metadata": {
                    "ISTIO_PROXY_VERSION": "1.1.0",
                    "ISTIO_VERSION": "1.1.1",
```

**Comment by dwradcliffe** [comment]
I think this is tied to the fact that the ISTIO_META_ISTIO_PROXY_VERSION is not equal to the actual proxy version, and only gets bumped when the capabilities need to change. This is essentially hardcodeded into the proxy image (unless you override it, which might break things).

The value was changed for 1.1.0 and previously for 1.0.2, hence the examples @Stono posted.

https://github.com/istio/istio/blob/d76cc6f9e3e635050d1f19c8e1acac86c21ee502/pilot/docker/Dockerfile.proxyv2#L13-L14

Unless I'm missing something there are 2 options to solve this:
1. Bump this value in the images for each build (This might break things? Perhaps @costinm can comment)
2. Rework the proxy-status flow to pull the version from something else.

**Comment by cyrus-mc** [comment]
@dwradcliffe Simple solution would be to just set the ENV correctly in the deployment manifests.

**Comment by dwradcliffe** [comment]
I've been running a set of proxies with the ENV set to `1.1.1` and it seems to be working fine. I also took a quick look at the code and I think the only thing using the value is the check to see if it's `> "1.1"`. That is definitely the simplest solution.

**Comment by anoopl** [comment]
We have upgraded from Istio 1.1.3 to 1.1.4 
But even after restarting pods, istioctl proxy-status shows version 1.1.3.
When I check the pods with `k get pods <pod_name> -o yaml` we can see that istio-proxy image tag is 1.1.4.

**Comment by dwradcliffe** [comment]
ref: https://github.com/istio/istio/pull/8252
