### ISSUE TITLE
Sidecar injection not working with 1.0.3

### ISSUE THREAD

**Issue by acartapanis** [istio/istio#9605]
**Describe the bug**
Sidecar injection does not work with 1.0.3 when the pods have labels with '/' inside name (for exemple, "app.kubernetes.io/name" or "app.kubernetes.io/version").
The error is : 
```
Error creating: Pod "default-apigateway-5756bb6557-64csm" is invalid: [spec.containers[2].env[7].name: Invalid value: "ISTIO_META_app.kubernetes.io/instance": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.containers[2].env[8].name: Invalid value: "ISTIO_META_app.kubernetes.io/name": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.containers[2].env[9].name: Invalid value: "ISTIO_META_app.kubernetes.io/version": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')] 
```

Note that this error appears after moving from istio 1.0.2 to istio 1.0.3.

**Steps to reproduce the bug**
Deploy a pod with standard label (see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

**Version**
```
$ istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio has been deployed with helm

**Comment by acartapanis** [comment]
It seems to come from modification to the configmap (https://github.com/istio/istio/blob/a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L139 to https://github.com/istio/istio/blob/a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L142)

**Comment by cezarsa** [comment]
Looks like a dup to #9571. This bug made 1.0.3 (and 1.1 snapshots) unusable for me. I'd be happy to provide a PR after some guidance, could this be changed to create a `ISTIO_METAJSON_LABELS` similar to how annotations are handled?

**Comment by mandarjog** [comment]
@ostromart submitted a PR for 1.04.

**Comment by sdake** [comment]
if 1.0.3 is DOA (is it doa?) we should cut 1.0.4 asap.

Cheers
-steve

**Comment by mandarjog** [comment]
@sdake  it is only a problem if you happen to have / in your label names.
This is not very common. There is an easy workaround available.

**Comment by jlegrone** [comment]
There are no workarounds for StatefulSet due to the `statefulset.kubernetes.io/pod-name` added by the StatefulSet controller.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-name-label

**Comment by acartapanis** [comment]
@sdake using "/" in labels is the kubernetes official recommended labels, see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by mandarjog** [comment]
Thanks for the docs, I never used those characters in labels, but they are clearly used :-)

I meant the workaround is to edit the `istio-sidecar-injector` config map in `istio-system` as specified in https://github.com/istio/istio/pull/9634/files.

That PR has merged now.

**Comment by jlegrone** [comment]
@mandarjog understood. Thanks for the quick patch!

**Comment by acartapanis** [comment]
+1 for correction.
Should I close this issue, or wait for the release ?

**Comment by batond** [comment]
@mandarjog I get this in the deployment after changing the `istio-sidecar-injector` config map.

kubectl get deployment details-v1 -o yaml

```
...
message: 'Internal error occurred: admission webhook "sidecar-injector.istio.io"
      denied the request: error converting YAML to JSON: yaml: line 81: could not
      find expected '':'''
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
...
```

**Comment by antweiss** [comment]
@mandarjog Thanks! I've edited the configmap as advised. While this seems to fix the issue of pod generation - it for some reason causes the istio-init container to crash. No termination message is generated, the log seems fine, but it exits with 2. Haven't had the chance to research this further. Any ideas?

**Comment by antweiss** [comment]
Note: the carsh of istio-init happens in pods that are fine otherwise (i.e no '/' in names) If I revert the configmap change  - they are created normally again.

**Comment by mandarjog** [comment]
@antweiss can you try out the latest daily build from the 1.0 branch ?
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20181030-09-15/

**Comment by antweiss** [comment]
@mandarjog tried this. Same thing. istio-init exits with code '2' but the log seems fine. see here: https://gist.github.com/antweiss/2d5429cfed5f392f5b4189b49b642426
(I pushed the proxy-init image from the daily build to our repo for testing and updated the configmap accordingly)

**Comment by antweiss** [comment]
Never mind, I think my OUTBOUND_IP_RANGES_EXCLUDE was misconfigured.

**Comment by davidkarlsen** [comment]
Let's keep the issue alive and not stale

**Comment by ostromart** [comment]
afaics it's fixed - if so could you close it @mandarjog ?
