### ISSUE TITLE
Mixer: support sending arbitrary attributes generated by non-oss envoy filters

### ISSUE THREAD

**Issue by rshriram** [istio/istio#9613]
I have some custom codec in Envoy that generates some attributes for some protocol. Envoy now has a mechanism to share state across filters. So, in theory, mixer filter in Envoy should be able to see these attributes (present as a Protobuf::Struct). I would like to stream these attributes to Mixer for telemetry purposes. This would require supporting Protobuf::Struct as a first class attribute that an adapter can process and extract information from. With support for this, Mixer filter can essentially scan through the entire set of dynamically generated attributes by other envoy filters, and forward them as is to Mixer. 

Otherwise, the only option I have today is to have a fork of mixer filter, where I generate the custom attributes I want - this is not a scalable option.

Per @douglas-reid , we can shoehorn all the struct into value.bytes, and do the casting in the adapter. It would be nice to have Protobuf::Struct as the base attribute type. Note that Any does not work because of the way these attributes are generated inside Envoy (dynamic filter state is created and stored as Structs).

**Comment by rshriram** [comment]
`envoy::api::v2::core::Metadata& metadata` - mixer filter uses StreamInfo() to gather info about a request. StreamINfo, in addition to providing things like response codes, etc., also has dynamicMetadata - information generated by one or more filters (codecs for example). It would be valuable to log this data in mixer report calls. I don't know whats the required magic to introduce another attribute to be sent in the report calls..

**Comment by mandarjog** [comment]
`envoy::api::v2::core::Metadata` is `map<string, Struct>`, we should not send the thing whole sale over to Mixer. I think it is better to name individual elements in the map and send them over. A pair of filters may put some sensitive information in the dynamic metadata and we will end up sending it to Mixer.

I prefer only sending named and defined elements from here.

There is an analogy between `request.headers` and this data, but headers are understood to be going upstream and out of the proxy.

**Comment by kyessenov** [comment]
Thanks. @rshriram what is it specifically do you want to send in metadata? Why can't _that_ thing be written to metadata as Mixer attributes?

**Comment by geeknoid** [comment]
Yes, the value that Mixer provides is that it allows the operator fine-grained control over the telemetry state produced by the mesh. The operator gets to augment or redact this data before it leaves the mesh. Our model leverages type information to eliminate a class of errors for the operator by statically constraining assignments and use.

Passing raw state to Mixer to shovel to an adapter completely eliminate Mixer's benefit and doesn't seem like a useful thing. If you want to send custom data blobs from Envoy to a custom backend, you can just write directly to your custom backend and skip the whole Mixer thing.

**Comment by rshriram** [comment]
This is not about custom data blobs. This is more of an issue of maintenance and extensibility. Today, if I have some internal codec that is generating one or more attributes (strings, ints, etc.) that I want to send to mixer via the usual envoy-mixer-filter to mixer-server, I need to do the following:
1. fork Istio/proxy and create my own version of mixer filter that sends these attributes extracted from the dynamic metadata - this immediately becomes a maintenance nightmare, having to keep patches internally, and constantly track state in upstream istio/proxy
2. add one or more attributes to the attribute manifest
3. write my adapter to extract these attributes and do their thing (logging).

In general, while mixer has a mechanism that allows users to add custom attributes, there is no mechanism at the primary data source i.e. envoy, to add such attributes without having to create a personal version of istio-proxy. Serializing envoy's dynamic metadata (map<string, struct>) is essentially a way of allowing custom attributes generated by third party codecs, to flow into mixer via Envoys. 

The only reason we are still planning to use mixer internally at vmware is for the flexible telemetry pipeline. If forking istio/proxy (mixer filter) is the only way to add custom attributes, then as @geeknoid says, we are probably better off completely removing mixer and creating our own telemetry sources that send directly to our telemetry sinks.

**Comment by kyessenov** [comment]
@rshriram Regarding the maintenance issue, I think there is a simple way to push a config to mixerfilter that does the following:
1) it takes a list of triples: attribute name, JSON path, attribute type
2) mixerfilter scans through dynamic metadata, follows JSON path to extract data from extracts, type checks, and populates the attributes.

Our concern is that passing untyped blobs of data through mixer (which can also be potentially large in size) is not the right direction for policy/telemetry.

**Comment by geeknoid** [comment]
If the raw data is not exposed as attributes, then Mixer and its pipeline is providing no value so it doesn't make sense to use it for that purpose.

The intent has always been to make the attribute protocol open-ended so that new attributes can be added in a systematic way and still benefit from the type checking we do and the general declarative syntax we offer.

**Comment by rshriram** [comment]
But there is no systematic way to add attributes to the source (envoy). Its a whole set of changes that I have to make. The config stuff is okay, but certainly not the scalable way unless these configs flow through Pilot (which means there needs to be a CRD of some sort).

the problem here is that the design of the envoy client did not take in to account the fact that attributes can be produced by other filters. It assumes that attributes can ONLY be extracted by the istio mixer filter itself and packed into the wire. This is inherently flawed, as Envoy model allows for a lot of extensibility -- i.e. multiple filters can generate attributes. When you look at the problem this way, you will realize that either you need a way to dynamically determine attributes that envoy should pick up i.e. a struct blob that has more attributes packed into it (for reports), with zero config, or you provide ways to dynamically "define" attributes, reprogram the mixer client to pick up these attributes with their types, etc.

**Comment by kyessenov** [comment]
Dynamic metadata is a fairly new phenomenon. If I recall correctly it was added less than a year ago as part of xDS proto3 spec, long after mixerclient was written. I don't think it is fully worked out, I think it's missing namespaces and filter rerun semantics. I think it's a reasonable request to support dynamic metadata in mixerfilter, but not as an opaque blob, but as config-driven extraction. We need at the very least a toggle to disable the entire dynamic metadata in case it becomes a performance problem.

**Comment by douglas-reid** [comment]
I don't know that our message should be "then don't use Mixer".  There is little distinction between having a new attribute be string and serializing that attribute value out passing it along and having the adapter do something once an operator decides the adapter should have access to that value. 

@mandarjog we don't currently support a `Struct` type at all. Is what you are saying that you are fine with individual entries in that map but not the map as an entire entity?  That would seem a reasonable limitation. Relatedly, it might be nice to have a way to only send *portions* of request headers.

I think we generally have a sensitive data issue within the Mixer flow that is unaddressed. I understand not wanting to potentially increase the surface area of the problem, but I don't know that we should discard this use case for this reason outright.

**Comment by douglas-reid** [comment]
@rshriram Can you provide some concrete examples here (per discussion in the P&T WG)?
