### ISSUE TITLE
503s under concurrent load with istio 1.0.3

### ISSUE THREAD

**Issue by Stono** [istio/istio#9618]
Just creating this placeholder issue, the title describes the observation, the underlying problem we're yet to locate.

Following the ongoing conversations with @mandarjog tonight; we've rolled back to 1.0.2 due to seeing approximately a 5-10% error rate (503s) for services deployed AFTER pilot.

So just to be clear:

- Pilot started
- App started (app has error rate)
- Pilot restarted (resolves app errors)
- App restarted (app has error rate)

These errors were more pronounced when multiple concurrent requests were hitting a service.

All logs provided to @mandarjog privately as they contain potentially sensitive information.

**Comment by Stono** [comment]
Hey folks, 
Are we getting anywhere debugging this?

**Comment by nmittler** [comment]
@costinm @mandarjog any update here?

**Comment by mandarjog** [comment]
@Stono EDS has now become much faster, so it delivers endpoint updates to all sidecars in under 1s. We were checking if non-ready endpoints are being sent to sidecars, but we don't think this is happening.  We will have more updates tomorrow.

**Comment by Stono** [comment]
@mandarjog that'd make sense if I saw 503s only briefly after the sidecars came up (but weren't ready) but surely we'd then expect it to settle down - which it didn't.  

The only way I was able to "reset" things and get the 503's to go away would be to restart pilot.

**Comment by MichaelHudgins** [comment]
I believe i was having a similar problem to this.  Right after the upgrade from 1.0.2 to 1.0.3 via helm on 1.10.7-gke.6 .  After the upgrade i began getting 503 errors from my external health checks with no 503s coming from the inside of my application pods.  A rollback to 1.0.2 fixed it for me.

**Comment by Stono** [comment]
Any updates @mandarjog ?

**Comment by Stono** [comment]
@mandarjog @costinm that linked issue looks very interesting

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/9805

**Comment by Stono** [comment]
@roblg I believe i've seen that too, just never narrowed it down to mixer (see https://github.com/istio/istio/issues/8243)

**Comment by MrSaints** [comment]
Potentially related to #9906

**Comment by mandarjog** [comment]
This issue has been addressed by #9805

**Comment by Stono** [comment]
It has, I think there are still some lingering EDS issues though, see: https://github.com/istio/istio/issues/10116 - but this one can be closed
