### ISSUE TITLE
Istio is forwarding request headers in lower case

### ISSUE THREAD

**Issue by amitsinha11** [istio/istio#9630]
**Describe the bug**
Istio is forwarding request headers in lower case to pods even when I'm sending with camel casing to my service, what should I do?  e.g. X-Request-ID is going as x-request-id, Authorization is going as authorization etc.

`Call create user with headers: {host=[microservice-abc], x-forwarded-host=[abc.host.name], x-forwarded-serverabc.host.name], x-forwarded-port=[443,80], x-forwarded-proto=[https,http], x-forwarded-for=[10.1.1.1, 127.0.0.1], x-real-ip=[10.1.1.1], x-request-id=[e7b369bc-93fe-9900-a461-753a32cba72c], psu-geo-location=[GEO:52.234,13.234], psu-ip-address=[182.1.1.1], psu-user-agent=[Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0], x-sbs-env-port=[30201], content-type=[application/json], user-agent=[Apache-HttpClient/4.5.5 (Java/1.8.0_181)], authorization=[Bearer dfgsafgsfag]`

**Expected behavior**
It should forward the headers as sent in request.

**Version**
Istio version is : 1.0.2

**Comment by clyang82** [comment]
relevant issue - https://github.com/istio/istio/issues/9432. Link together.

**Comment by esnible** [comment]
HTTP headers are case insensitive.  https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

Perhaps it would make more sense to preserve what clients supply, but it is non-spec and servers shouldn't expect a particular case.
