### ISSUE TITLE
tutum/curl in "Sleep" sample no longer exists

### ISSUE THREAD

**Issue by tomkerkhove** [istio/istio#9635]
**Describe the bug**
`tutum/curl` in "Sleep" sample no longer exists

**Expected behavior**
Be able to create a deployment

**Steps to reproduce the bug**
1. Deploy https://github.com/istio/istio/blob/master/samples/sleep/sleep.yaml
2. Deployment will fail when pulling the image as it's no longer there

**Version**
N/A

**Installation**
N/A

**Environment**
N/A

**Cluster state**
Failed to pull the image `tutum/curl`

**Comment by jmazzitelli** [comment]
This affects the "prow/e2e-mixer-no_auth.sh" tests, too -- see https://groups.google.com/forum/#!msg/istio-dev/VA5k1hEQmKY/SCp2FjEoCgAJ

**Comment by esnible** [comment]
https://hub.docker.com/r/tutum/curl is still there.

**Comment by tomkerkhove** [comment]
That's odd.

Given I'm not using this sample anymore I will just close this.
