### ISSUE TITLE
FR: Istio should publish its own Docker image with curl

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#9638]
**Describe the feature request**
Istio ideally should not rely on third-party images, especially in e2e tests. This feature request is for Istio to use an Istio-managed image for the `sleep` sample. It doesn't need to be updated with any frequency, just needs to be published once and have its lifecycle maintained by Istio.

**Describe alternatives you've considered**
Find random test breakages at times when third-party images are deleted.

**Additional context**
#9635 #9637

**Comment by kyessenov** [comment]
Per offline discussion, I think we can reuse our base build image with all of the goodies to replace some of the 3rd party images we depend upon.

**Comment by supereagle** [comment]
Any detailed plan? I am glad to participate in 😃
