### ISSUE TITLE
Helm Upgrade failed when upgrading from 0.8 ==> 1.0.3

### ISSUE THREAD

**Issue by vilobhmm** [istio/istio#9644]
Helm upgrade fails when upgrading from 0.8 to 1.0.3 with unable to get the destination rule and configmap info even when both of them are present.

Steps tried
=========

1. Install Istio with 0.8
2. Follow the instructions to upgrade Istio here https://istio.io/docs/setup/kubernetes/upgrading-istio/

Log
===

$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no DestinationRule with the name "istio-telemetry" found

$ kubectl get destinationrule -n istio-system
NAME              AGE
istio-policy      6m
istio-telemetry   6m

$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no ConfigMap with the name "istio-galley-configuration" found

$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no ConfigMap with the name "istio-galley-configuration" found

$ kubectl get destinationrule -n istio-system
NAME              AGE
istio-policy      7m
istio-telemetry   7m

$ kubectl get configmaps -n istio-system
NAME                                    DATA      AGE
istio                                   1         8m
istio-galley-configuration              1         55s
istio-ingress-controller-leader-istio   0         7m
istio-mixer-custom-resources            1         8m
istio-security-custom-resources         2         55s
istio-sidecar-injector                  1         8m
istio-statsd-prom-bridge                1         8m
prometheus                              1         8m

$ helm upgrade istio install/kubernetes/helm/istio --namespace istio-system
Error: UPGRADE FAILED: no ConfigMap with the name "istio-galley-configuration" found

**Comment by vilobhmm** [comment]
@hklai @costinm

**Comment by hklai** [comment]
+@mandarjog
