### ISSUE TITLE
Mixer Check results are not traced

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#9658]
**Describe the feature request**
When configuring check rules and the request is rejected, for example by a listchecker handler, Jaeger only shows that the Handler execution itself finished successfully, which means no error did occur in evaluation.
But there is no hint on the CheckResult itself and one can only guess why a request was rejected.
This could be enhanced if the checkResult would be passed to completeSpan in https://github.com/istio/istio/blob/34cf6da5b6fa1a645d00c295e0eb935c9a1fa996/mixer/pkg/runtime/dispatcher/dispatchstate.go#L126-L143

**Additional context**
I tested this on 1.0.2 but the current master sources also seem like the result is still not traced.

**Comment by douglas-reid** [comment]
@robertpanzer thanks for raising this issue. this is related to a larger need to have the yes/no votes of check adapters available for inspection by the larger system, including report adapters.  But I think we can *start* with having this info available in spans for now.

cc: @kyessenov who is looking at enhancing information flowing back from check adapters.

**Comment by robertpanzer** [comment]
Thanks! 
@douglas-reid I could also try to create a PR for this. 
I think for Quota Checks it would also make sense to log the QuotaResult and not the error if it is nil.

**Comment by mandarjog** [comment]
@douglas-reid #9658 will address the problem only when a particular request is traced.
While testing, the request can force trace.
But if the requirement is to know why a particular request was rejected this solution is not sufficient.
@liminw what is the customer requirement ?

**Comment by douglas-reid** [comment]
@mandarjog as i've raised elsewhere, I believe the follow-on is that Mixer should put adapter results (yes/no, validity period) in attributes that are available for the Report functionality. This should be fairly straightforward to add onto the route-directive work.

**Comment by robertpanzer** [comment]
> But if the requirement is to know why a particular request was rejected this solution is not sufficient.

@mandarjog I don't fully understand what you mean, can you clarify? 
I understand that I will not be able to find out why the request was rejected in case it was not sampled, that's just how things are and it seems that sampling is the decision of the originator of a request. 
But if it is sampled I would expect to see that the Mixer rejected it on purpose instead of only seeing that an HTTP 403 was sent and everything else just says "OK".
Also, would it make more sense to discuss the proposed solution on the pull request instead of on the issue?

**Comment by mandarjog** [comment]
This issue is framed narrowly and the PR addresses it fully. If a request is traced, we can get this info.

If my requirement is to audit an arbitrary request in the past as identified by x-request Id and know why it was rejected, then the PR does not solve that problem and we need additional solutions.

**Comment by robertpanzer** [comment]
Agree.
My current goal was to just give the right information for what is there, because the traces that are currently presented to the user – if sampled – don't help in analyzing such problems.
It would certainly be nice to give additional information for all requests that were rejected.

**Comment by douglas-reid** [comment]
PR #10681 has been approved. Awaiting full test passing.

**Comment by douglas-reid** [comment]
The PR has been merged. Closing this issue.
