### ISSUE TITLE
A hyphen is missing in string literal

### ISSUE THREAD

**Issue by ajit-hybris** [istio/istio#9663]
Code line: https://github.com/istio/istio/blob/42773aacced474d97159902d20579a25b1f98106/install/kubernetes/helm/istio/charts/mixer/templates/statsdtoprom.yaml#L60

Missing hyphen in string literal causes istio-statsd-prom-bridge pod to crash.
Correct value is '--statsd.mapping-config=/etc/statsd/mapping.conf'

**Comment by ymesika** [comment]
We don't have this file anymore in `master`/`release-1.0`/`release-1.1`.
