### ISSUE TITLE
CDS with strict_dns doesn't support version routing

### ISSUE THREAD

**Issue by rshriram** [istio/istio#9664]
Create service entries with endpoints having dns names, and some labels. Try to do version routing. Traffic ends up going to all endpoints instead of endpoints for the specific version.

The CDS code computes cluster hosts only once (https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L118) and reuses the same set for all subsets (https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L136). The code in the latter segment needs to filter by subset labels if specified (if no subset labels, all endpoints should be used).

**Comment by munrodg** [comment]
Can we move this to 1.2?

**Comment by rshriram** [comment]
fixed..
