### ISSUE TITLE
dashboard test should send galley some traffic

### ISSUE THREAD

**Issue by tangiel** [istio/istio#9674]
Right now we're filtering more dashboard tests for Galley than we need to, even more than just error state metrics, because there are some metrics in the zero state, which aren't exported.

**Comment by ozevren** [comment]
Can you give more details? What type of metrics are not exported? (Presumably things pertaining to MCP and incoming CRD notifications?)

**Comment by tangiel** [comment]
Any metrics that aren't modified aren't exported by the OpenCensus exporter. This is mostly error metrics but also the ones I added to the query filter in #9673.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/19898 fixes this
