### ISSUE TITLE
Option to create client-side spans but not server-side spans

### ISSUE THREAD

**Issue by adinunzio84** [istio/istio#9692]
**Describe the feature request**
Istio provides valuable information for tracing, but due to the nature of OpenTracing, where it's impossible to get a Span from a SpanContext, we cannot do anything with this server-side span from within our app, except use its context in outgoing requests for child-spans. 

If we want to call `span.log(...)` or add tags of our own, we are required to create child spans, which is not particularly easy at the moment (istio/istio.io#2800) and does not look very good within the Jaeger UI.

It would be helpful to have an option to *not* automatically create server-side Spans (but still create client-side Spans). Instead, it could pass the tags - such as HTTP method, url, etc. - in a different header, where we can apply those tags in the server-span that we create (as a child of the incoming client-span).

**Describe alternatives you've considered**
I've considered just creating a Mixer adapter to modify the headers in a similar way that Istio does (and disabling Istio tracing), but I'd prefer an Istio-based solution if possible, since I'm not too familiar with these adapters.

**Comment by douglas-reid** [comment]
I'm not sure how desirable it would be to turn off server-side tracespan generation in the proxy. I'd like to think about this use case a bit more -- perhaps we can discuss it in the P&T WG meeting next week?

In the meantime, @objectiser do you have any light you can shed here ?

A few clarifications / follow-up questions:
- I'm not sure why we believe that it is not easy to create child spans ([example](https://github.com/istio/istio/blob/master/mixer/pkg/runtime/dispatcher/dispatchstate.go#L73-L80)) or why you believe it is impossible to get a Span from a context (for instance: [SpanFromContext](https://github.com/istio/istio/blob/master/vendor/github.com/opentracing/opentracing-go/gocontext.go#L21)).  Would you mind clarifying here?

- As for your alternative, I'm not sure I understand the distinction between Mixer-based solutions and Istio-based solutions (Mixer is part of Istio).  However, I don't believe that you would need to do any header mangling in Mixer if you just wanted access to the headers themselves in your application.

**Comment by adinunzio84** [comment]
I'd be happy to discuss my use case - I see the WG weekly [meeting link here](https://github.com/istio/istio/wiki/Policies-and-Telemetry-WG), but I don't see a date/time. 

To answer your first question:
It isn't hard to create child spans once you have a SpanContext. It seems the codebase you linked stores Spans in **context.Context**s and retrieves them from there. The challenge is in getting Spans from SpanContexts.

When a request comes in, we can get a SpanContext from the headers using an OpenTracing HTTP_HEADERS carrier to extract the info from the headers into a SpanContext. Once you have this SpanContext, you can inject it into headers of outgoing requests with the HTTP_HEADERS carrier (both of these use the Zipkin B3 TextMap codec in Jaeger). There are other headers that still need to manually be propagated, since Istio requires `x-request-id` and `x-ot-span-context` in addition to the Zipkin headers. This whole approach is different from what's currently documented of just manually propagating a set of headers with each request (which you can't do if you want to create child spans). The problem is that since the server-side Span is created for us, we can't add tags to it or log in the context of it, since we have no way to access the Span that Istio created.

By extracting the SpanContext, you can create sub-spans. If the SpanContext that we extract is the client-side span that Istio (or Envoy?) creates, then we can create a Span as a child of that SpanContext, then we have not only the SpanContext that we can propagate, but also the server-side Span itself (since it would be created inside our app), which we can then use for things like `span.log(...)` and `span.setTag(...)`.

For your second question:
I guess what I meant was, I was thinking about trying to mimic what the proxies are doing to create the spans (with their interactions with the Mixer) and just disable the "tracing" feature of Istio. I created this issue though, since I think being able to do stuff with the server-side span is important and others would probably want to do this as well.

**Comment by objectiser** [comment]
Having the server span reported by the proxy, and another child span (possibly marked also as server kind) reported from within the app enables information regarding the latency of the proxy to be understood - and the app can then report any log/tags against that internal server span.

However I understand that this can bloat the trace data.

Accessing the span from spancontext has been discussed in the opentracing community: https://github.com/opentracing/specification/issues/81 - but there is no solution currently.

If you have specific interest in visualisation in Jaeger, then one possibility would be to raise an issue there to see if there is any way to make it easier to collapse the information in such cases (i.e. where a proxy has been used).

Alternatively its possible zipkin/brave could provide a solution - using the [brave API](https://static.javadoc.io/io.zipkin.brave/brave/4.3.1/brave/Tracer.html#toSpan-brave.propagation.TraceContext-) I believe you can extract a span from the context and report additional logs/tags for the same span id. But you would need to use the zipkin backend.

**Comment by adinunzio84** [comment]
That's a good point that the proxy latency is good information to have. Looking through your links, it seems like a SELF reference is exactly what I was looking for (or a "decorates" span), but yeah this would not give proxy latency info I'd imagine.

I am hesitant to use a different API. I'd like to use only OpenTracing, with implementation-specific APIs only being used to initialize the tracer. 

I will consider posting an Issue to the Jaeger UI, perhaps to add a span tag like "combineWithParent" or "hasProxy" or something, that would combine the node in its tree with the one that Envoy creates. This could be useful for outgoing client spans too (though I haven't yet had a reason to do anything with client spans yet).

Thanks for the info.
