### ISSUE TITLE
perf: Optimizations around Prometheus scalability and performance.

### ISSUE THREAD

**Issue by jnativio** [istio/istio#9694]
**Describe the feature request**
As part of general performance improvements on Istio, this issue/epic aims to track fixes and solutions regarding Prometheus, in particular the case of large environments where it was verified that a single instance of Prometheus cannot handle the load.

**Comment by jnativio** [comment]
#9541 This PR adds an option to control Prom scrape interval

**Comment by douglas-reid** [comment]
I believe that we can close this, as we had several PRs in `release-1.1` to address this issue.

**Comment by mandarjog** [comment]
converting this to an epic.

**Comment by douglas-reid** [comment]
@mandarjog is this still 1.1 focused then?  Or can we make this 1.2?

**Comment by douglas-reid** [comment]
@mandarjog what is left to do here? I don't see any issues attached to this Epic.

**Comment by howardjohn** [comment]
It doesn't seem like there is anything left to do here. Sounds like we are moving to a bring-your-own operator model anyways so we don't really control the prometheus perf?

If there is no work here we should close, this is marked as P0 for 1.3

**Comment by douglas-reid** [comment]
@howardjohn concur. i think this covered a variety of things that are OBE or are being tracked as part of other efforts.
