### ISSUE TITLE
[ Helm istio-1.1.0-snapshot.2] Missing ImagePullsecret for kubectl image

### ISSUE THREAD

**Issue by pmontanari** [istio/istio#9707]
**Describe the bug**
When using a private docker registry, we can pull all images using an Imagepullsecret execpt for the new kubectl image.

Here are the occurences:
subcharts/security/templates/create-custom-resources-job.yaml
subcharts/security/templates/cleanup-secrets.yaml
subcharts/grafana/templates/create-custom-resources-job.yaml

**Expected behavior**
Should use the global.imagePullSecrets helm variable

**Version**
istio-1.1.0-snapshot.2

**Installation**
Using Helm

**Environment**
RHEL7

**Comment by pmontanari** [comment]
The related Service Accounts are:
- istio-security-post-install-account
- istio-cleanup-secrets-service-account
- istio-grafana-post-install-account

**Comment by igowithjava** [comment]
Can any developer take care of this issue ?
