### ISSUE TITLE
Create a metadata library for istio

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#9710]
We have a number of metadata used for node(proxy). And they do not reside in a common place. 
So it is a burden for developers and users to config or use these metadata. 

It would be good to have a single place (e.g., pkg/metadata/metadata.go) where we define variables that hold all these ,metadata names. Like #8960(move all feature envs to a file)

**Comment by mathspanda** [comment]
Is there anyone working on this? I could help with it.

**Comment by hzxuzhonghu** [comment]
welcome
