### ISSUE TITLE
grpc-transcoding issues for some services

### ISSUE THREAD

**Issue by mukundha** [istio/istio#9716]
**Describe the bug**
grpc-transcoding using the Envoy filter is not working for some services, 

Not working = receiving a empty response, instead of a JSON response
I created a gist to reproduce the problem,
https://gist.github.com/mukundha/4e8a7527f87cca1da73461269dc77ae2
As you will notice, transcoding works for the products service but not for currencyservice, 
FWIW, i have tested the same configuration with cloud endpoints (with esp proxy), its working for all services, but not working in Istio. So I guess, the pb config and http annotations are good, might be a issue with istio

**Expected behavior**
grpc-transcoding works for all services (in this case, currencyservice)

**Steps to reproduce the bug**
Steps on GCP https://gist.github.com/mukundha/4e8a7527f87cca1da73461269dc77ae2

**Version**
GKE - v1.10.7-gke.6
Istio - 1.0.3

**Installation**
https://istio.io/docs/setup/kubernetes/quick-start/

**Environment**
GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2542783/istio-dump.tar.gz)

**Comment by qiwzhang** [comment]
@mukundha   I just looked your filter_config for filter_name": "envoy.grpc_json_transcoder".  I could not spot any problem.  You indeed listed all the services.   

could you provide list of the not-working services?  especially their request json. 

We need to debug it.

@lizan could you take a look?  

Here is his envoy filter config:

"filter_name": "envoy.grpc_json_transcoder",
          "filter_config": {
            "fields": {
              "match_incoming_request_route": {
                "Kind": {
                  "BoolValue": true
                }
              },
              "proto_descriptor": {
                "Kind": {
                  "StringValue": "/gce/api_descriptor.pb"
                }
              },
              "services": {
                "Kind": {
                  "ListValue": {
                    "values": [
                      {
                        "Kind": {
                          "StringValue": "hipstershop.RecommendationService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.CurrencyService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.AdService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.ProductCatalogService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.CartService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.ShippingService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.PaymentService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.EmailService"
                        }
                      },
                      {
                        "Kind": {
                          "StringValue": "hipstershop.CheckoutService"
                        }
                      }
                    ]
                  }

**Comment by lizan** [comment]
Do you have access log for the failed request? How do you generate the pb descriptors?

**Comment by mukundha** [comment]
Thanks for checking,
I am generating descriptors as described [here](https://cloud.google.com/endpoints/docs/grpc/transcoding#deploying_a_service_using_transcoding)
```
protoc \
        --include_imports \
        --include_source_info \
        --proto_path=${GOOGLEAPIS_DIR} \
        --proto_path=. \
        --descriptor_set_out=api_descriptor.pb \
        http_bookstore.proto
 ```
[Here](https://github.com/mukundha/hipster-apim-demo/blob/master/endpoints/api_descriptor.pb) is the proto descriptor I am using 

Problem is I not seeing anything in the logs of both on istio-proxy as well as my server container

Calls thro istio-ingress results in 503 -no healthy upstream
Calls directly to the service from within the mesh results in no response [just empty response]

You can easily reproduce this for this [deployment](https://github.com/mukundha/istio-sample-grpc-transcoding/blob/master/currencyservice.yaml) or as shown in the [gist](https://gist.github.com/mukundha/4e8a7527f87cca1da73461269dc77ae2)

**Comment by lizan** [comment]
@mukundha Looks like you're applying EnvoyFilter to label `transcode: http`, but your currencyservice deployments doesn't have that?
https://github.com/mukundha/istio-sample-grpc-transcoding/blob/master/currencyservice.yaml#L23

Others seems to be fine:
https://github.com/mukundha/istio-sample-grpc-transcoding/blob/master/products.yaml#L25

**Comment by mukundha** [comment]
sorry, pushed the wrong config.. fixed the config now.. yes currencyservice doesn't work even with the label
https://github.com/mukundha/istio-sample-grpc-transcoding/blob/master/currencyservice.yaml
Thanks,

**Comment by lizan** [comment]
It seems you're using "match_incoming_request_route" which might lead 503 no upstream with istio. What if you turn off that? You might need change the route setting as well though.

**Comment by mukundha** [comment]
ok tried that, still not working. The same config("match_incoming_request_route"), works for other services, just not for this and couple others [but this is easy to test]

If i try within the cluster this is what I get, 
```
$ curl currencyservice/currencies -v
*   Trying 10.47.254.7...
* Connected to currencyservice (10.47.254.7) port 80 (#0)
> GET /currencies HTTP/1.1
> Host: currencyservice
> User-Agent: curl/7.47.0
> Accept: */*
>
* Connection #0 to host currencyservice left intact
@@
```
I guess, this is what gets translated to, when I hit the ingressgateway
```
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Thu, 08 Nov 2018 08:31:03 GMT
< server: envoy
<
* Connection #0 to host 35.240.26.151 left intact
upstream connect error or disconnect/reset before headers%
```

**Comment by lizan** [comment]
Is your service serving gRPC request?

**Comment by mukundha** [comment]
Yep, this is the one I am using - https://github.com/GoogleCloudPlatform/microservices-demo/tree/master/src/currencyservice
also FWIW - i tried to use the same config files with CloudEndpoints, transcoding works well [with esp proxy]

**Comment by mukundha** [comment]
ok i think i found a reason on why this isn't working,
so, when i did a configdump on the istio-proxy sidecar on a pod that is working (products) vs a pod that is not working (currencies)


For Products (Working)
```
listeners: {
 dynamic_active_listeners: [
  { listener: { name: <pod_id>_<pod_port> } , filter_chains: [ { filters: [ {name: "envoy.http_connection_manager" , config: { http_filters: [ {name: "envoy.grpc_json_transcoder", ..}]}} ] }]}, {} , {}
]
}
```
While for Currencies (Not working),
```
listeners: {
 dynamic_active_listeners: [
  { listener: { name: <pod_id>_<pod_port> } , filter_chains: [ { filters: [ {name: mixer, ..}, {name: "envoy.tcp_proxy",.. }] }] }, {} , {}
]
}
```

Not sure why the filter config is not injected only to this sidecar [and is happening everytime], is there a way to force this config or apply individually ? do you see anything else inconsistent with my configuration?

Thanks,

**Comment by mukundha** [comment]
Ok, i found this on the pilot logs, for the currencyservice
```
2018-11-08T15:48:53.487244Z	warn	Ignoring filter envoy.grpc_json_transcoder. Cannot insert HTTP filter in network filter
```
This is not happening for other services - think we are close, any ideas why this is happening?

**Comment by mukundha** [comment]
and here is that error - https://github.com/istio/istio/blob/18bd3e70530f737ec1c9e5666035c691b5893e04/pilot/pkg/networking/plugin/envoyfilter/envoyfilter.go#L106

```
if in.ListenerProtocol == plugin.ListenerProtocolHTTP && f.FilterType == networking.EnvoyFilter_Filter_HTTP {
			// Insert into http connection manager
			for cnum := range mutable.FilterChains {
				insertHTTPFilter(&mutable.FilterChains[cnum], f)
			}
		} else {
			// tcp listener with some opaque filter or http listener with some opaque filter
			// We treat both as insert network filter X into network filter chain.
			// We cannot insert a HTTP in filter in network filter chain. Even HTTP connection manager is a network filter
			if f.FilterType == networking.EnvoyFilter_Filter_HTTP {
				log.Warnf("Ignoring filter %s. Cannot insert HTTP filter in network filter chain", f.FilterName)
				continue
			}
			for cnum := range mutable.FilterChains {
				insertNetworkFilter(&mutable.FilterChains[cnum], f)
			}
		}
```
both my config looks same, how do i tell if my listener is http or tcp? in service configuration, i have named the ports as `http1` and `grpc`

**Comment by mukundha** [comment]
ok I tried `istioctl proxy-config listeners` on both the pods
The working pod has
```
ADDRESS          PORT      TYPE
10.0.1.20        3550      HTTP
```
and the problematic pod has
```
ADDRESS          PORT      TYPE
10.0.1.23        7000      TCP
```

how the listener type is decided whether its TCP or HTTP?

**Comment by mukundha** [comment]
From the Model spec, looks like its assigned from the `name` of the Port, if I set that to `http` instead of `http1`, filter gets applied to the listener, but am still seeing the original error.
