### ISSUE TITLE
Proposal: Support short names for Istio resources

### ISSUE THREAD

**Issue by supereagle** [istio/istio#9729]
**Describe the feature request**

There are many resources defined in Istio such as VirtualService, ServiceEntry, DestinationRule and so on. 
They don't have short names, so it is not convenient to operate them through kubectl.

**Describe alternatives you've considered**

I think it is necessary to support short names for frequently used resources.

**Additional context**

xref: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-dev/_OX4WW_KzM4/c7mR8ixpCwAJ

**Comment by esnible** [comment]
This should be simple, adding `shortNames` entries to _install/kubernetes/helm/istio-init/files/crd-10.yaml_

**Comment by duderino** [comment]
anything left to be done here or should this be closed?
