### ISSUE TITLE
Feature Request: RateLimitService directly scrapes from istio-proxy

### ISSUE THREAD

**Issue by osswangxining** [istio/istio#9733]
**Describe the feature request**
As Envoy 1.8+ already support HTTP rate limit filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/rate_limit_filter
And Envoy can integrate directly with a global gRPC rate limiting service. 

Will Istio plan to make RateLimitService directly scrapes from istio-proxy to improve the performance?

**Describe alternatives you've considered**
{{ Describe alternative solutions or workarounds you've considered. }}

**Additional context**
{{ Add any other context about the feature request here }}

**Comment by hzxuzhonghu** [comment]
Does this meet your requirement? https://istio.io/docs/tasks/policy-enforcement/rate-limiting/

**Comment by osswangxining** [comment]
> Does this meet your requirement? https://istio.io/docs/tasks/policy-enforcement/rate-limiting/

Thanks for your response. This link provides the guide about how to use mixer adapter to enable the rate limit, while mixer is optional and envoy proxy already supprot it: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/global_rate_limiting. 

Currently "istio-proxy"supports to talk with Zipkin and Statsd using the paramters below:
- --zipkinAddress
 - --statsdUdpAddress
So it looks like possible to support the talk directly to RateLimitService just adding one more paramter: - --rateLimitServiceAddress

Once this feature is moved from mixer adapter to Envoy proxy, the performance should be better.

Any comments for this? Thanks.

**Comment by forkjoseph** [comment]
Following up @hzxuzhonghu, it looks like istio supports "filter" functionality of envoy (https://istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/). 

While the example Lua filter works, other filters such as HTTP rate limit (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/filter) seems not working even if pilot-agent is provisioned with filter configuration? I'm currently running rate limit service (gRPC) server on separate container within local cluster and looks like envoy doesn't make gRPC call to the server even if traffic matches filter criteria, allowing the traffic 'passthrough'. 

Does istio plan to support all envoy's existing filters? or just limited ones? The istio's reference doc (the first link) doesn't mention anything about what filters can be used or not.
