### ISSUE TITLE
telemetry-gateway subchart is not in requirements.yaml

### ISSUE THREAD

**Issue by rchernobelskiy** [istio/istio#9748]
**Describe the bug**
telemetry-gateway subchart is ignored even if enabled in values.yaml because it's not present in requirements.yaml

**Expected behavior**
I would expect it to be a part of the requirements.yaml or for it to be removed altogether if that's the plan

**Version**
latest master

**Comment by douglas-reid** [comment]
@sdake I know that we've been re-org'ing the gateways. Thoughts on this issue?
