### ISSUE TITLE
Unable to send an istio log entry request using mixc 

### ISSUE THREAD

**Issue by vinayvenkat** [istio/istio#9752]
**Describe the bug**

mixer server (mixs) error when trying to send commands via the mixc tool to send report commands for the logentry template. 

Error on the mixs process is:

* fieldEncoder: timestamp - lookup failed: 'request.time'
* internal: no instances sent
2018-11-05T19:46:08.683711Z     info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2018-11-05T19:46:39.922196Z     error   error creating instance: destination='logentry.template.istio-system:h1.handler.istio-system(mygrpclogger.adapter.istio-system)', error='fieldEncoder: timestamp - lookup failed: 'request.time''
2018-11-05T19:46:39.922283Z     error   api     Report failed:2 errors occurred:

**Expected behavior**

I have my out of process adapter running and I expected the server to send the report call request to my out of proces adapter, very similar to the metric template. 

**Steps to reproduce the bug**

1. Follow the mixer out of process adapter walkthrough steps

2. run my grpc adapter as follows:
    go run cmd/main.go 

3. Run the mixs process with the following command:
   $GOPATH/out/linux_amd64/release/mixs server --configStoreURL=fs://$(pwd)/mixer/adapter/mygrpclogger/testdata

3. Run the client with the following command:

   $GOPATH/out/linux_amd64/release/mixc report --timestamp_attributes request.time="2017-07-04T00:01:10Z"

Error on the mixs is: 

* fieldEncoder: timestamp - lookup failed: 'request.time'
* internal: no instances sent
2018-11-05T19:46:39.923017Z     info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2018-11-05T19:47:33.168140Z     error   error creating instance: destination='logentry.template.istio-system:h1.handler.istio-system(mygrpclogger.adapter.istio-system)', error='fieldEncoder: timestamp - lookup failed: 'request.time''
2018-11-05T19:47:33.168410Z     error   api     Report failed:2 errors occurred:

**Version**

istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

kubectl version

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.6", GitCommit:"06898a4d0f2b96f82b43d9e59fa2825bd3d616a2", GitTreeState:"clean", BuildDate:"2018-10-02T17:32:01Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**

kubectl apply -f install/kubernetes/istio-demo-auth.yaml

**Environment**

Running this on Ubuntu 18.04 

**Cluster state**

Your timely help would be greatly appreciated.

**Comment by douglas-reid** [comment]
I'm able to pass in `request.time` without issue, via: `-t request.time="2018-01-29T12:12:14Z",response.time="2018-01-29T12:12:15Z"`.

Example full command: `mixc report -s context.protocol="http",destination.service="test",request.path="/doug-test",destination.uid="kubernetes://productpage-v1-79b8db5f94-dg4pw.crazy" -t request.time="2018-01-29T12:12:14Z",response.time="2018-01-29T12:12:15Z"`.

This is with `mixc` and `mixs` built from the HEAD of `release-1.1` branch, but it should work for all versions of Istio (as I use `mixc` to test consistently).

Can you please run `mixs` with `--log_output_level=attributes:debug` and try submitting your request?

You should see:

```
2018-11-05T21:11:32.822882Z	debug	attributes	Creating bag with attributes: context.protocol              : http
destination.ip                : [10 60 0 26]
destination.service           : test
destination.uid               : kubernetes://productpage-v1-79b8db5f94-dg4pw.crazy
request.headers               : {request.headers map[x-b3-traceid:2141234123412344abfe] 0xc009762fc0}
request.path                  : /doug-test
request.time                  : 2018-01-29 12:12:14 +0000 UTC
response.time                 : 2018-01-29 12:12:15 +0000 UTC
```

**Comment by vinayvenkat** [comment]
@douglas-reid 
Thanks for the response. I ran the server with the debug flags. Please see output below. Instances are not being sent to my grpc adapter:

2018-11-05T21:29:34.340872Z     debug   attributes      Creating bag with attributes: source.ip                     : http
source.labels                 : 2018-01-29 12:12:15 +0000 UTC
source.name                   : /doug-test
source.namespace              : 2018-01-29 12:12:14 +0000 UTC
source.port                   : test
source.uid                    : kubernetes://productpage-v1-79b8db5f94-dg4pw.crazy

2018-11-05T21:29:34.340972Z     error   error creating instance: destination='logentry.template.istio-system:h1.handler.istio-system(mygrpclogger.adapter.istio-system)', error='fieldEncoder: timestamp - lookup failed: 'request.time''
2018-11-05T21:29:34.341042Z     error   api     Report failed:2 errors occurred:

* fieldEncoder: timestamp - lookup failed: 'request.time'
* internal: no instances sent
2018-11-05T21:29:34.342295Z     info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"

**Comment by vinayvenkat** [comment]
@douglas-reid 
Looks like this was not fixed in the master branch that I had checked out. Its very similar to identical to another issue raised by someone else. I updated my branch and it worked. 
When will the fixes in the release-1.1 branch get merged and pushed out into a main release?

**Comment by douglas-reid** [comment]
@vinayvenkat ah, this is the `mixc` encoding issue! We should cherry-pick that immediately. I'm traveling tomorrow, but can handle it the day after (or will /lgtm one if you do it).

**Comment by javafuns** [comment]
I got this output:

> 2019-02-13T07:06:15.315188Z	debug	attributes	Returning bag with attributes:
> destination.service           : svc.cluster.local
> request.size                  : 1235
> 
> 2019-02-13T07:06:15.316710Z	warn	grpcAdapter	unable to connect to:/metric.HandleMetricService/HandleMetric, [::]:49540
> 2019-02-13T07:06:15.316811Z	error	api	Report failed:1 error occurred:
> 
> * rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

**Comment by javafuns** [comment]
The gRPC server is alive:
> $ go run cmd/main.go 
> listening on "[::]:49540"

**Comment by tangxusc** [comment]
I also encountered a similar problem in instances where I could not use properties such as request.path that start with request
---
$ istioctl version
Version: 1.0.4
GitRevision: d5cb99f479ad9da88eebb8bb3637b17c323bc50b
User: root@8c2feba0b568
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Comment by tangxusc** [comment]
I used `request.path |"/"` to solve this problem, but I don't know why.

**Comment by douglas-reid** [comment]
@tangxusc that typically means that `request.path` didn't have a value in your request. you can debug that by turning on attribute debug levels in mixer. if using `mixc`, you'll need to provide a value for `request.path` if you wish to use it without a fallback value.

@javafuns your issue is not related to this parent issue. it appears to be related to something OOP adapters.

Since this issue was about a long-fixed encoding issue with `mixc`, I'm closing this issue again.

**Comment by javafuns** [comment]
> I got this output:
> 
> > 2019-02-13T07:06:15.315188Z	debug	attributes	Returning bag with attributes:
> > destination.service           : svc.cluster.local
> > request.size                  : 1235
> > 2019-02-13T07:06:15.316710Z	warn	grpcAdapter	unable to connect to:/metric.HandleMetricService/HandleMetric, [::]:49540
> > 2019-02-13T07:06:15.316811Z	error	api	Report failed:1 error occurred:
> > 
> > * rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error:

Changing address: [::]:49540 to address: localhost:49540 fixed my issue.
