### ISSUE TITLE
Once istio injection enabled POD not able to connect external endpoints

### ISSUE THREAD

**Issue by ssubramanian123** [istio/istio#9755]
**Describe the bug**
I am enabling istio proxy injection using below command. Once it is enabled, my application pods are not able to connect our external endpoints.

**Expected behavior**
External endpoints should be reachable from the pod. 
Our application connects to the following type of external endpoints.
- endpoints in same VPC in  AWS as kubernetes cluster VPC
- endpoints in different VPC in AWS from k8s VPC
- Completely external endpoints.
Note : Using service entry will not fix my issue, because of number of external endpoint it is very difficult to identify all and enable it.

**Steps to reproduce the bug**
- enable namespace with istion injection as
kubectl label namespace {mynamespace} istio-injection=enable --overwrite  --kubeconfig=config
- I am not able to get values from any external endpoints. application throws error
```	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused) 
```

**Version**
1.0.3

**Installation**
=> Download istio
curl -L https://git.io/getLatestIstio | sh -
=> Deploy CRD
kubectl --kubeconfig=config apply -f istio-1.0.3/install/kubernetes/helm/istio/templates/crds.yaml
=> Generate manifest using helm template
helm --kubeconfig=config template istio-1.0.3/install/kubernetes/helm/istio --name istio --namespace istio-system > istio.yaml
=> Deploy istio
kubectl --kubeconfig=config create namespace istio-system
kubectl --kubeconfig=config apply -f istio.yaml

**Environment**
AWS KOPS create cluster, CentOS

**Cluster state**
Kubernetes cluster in AWS using KOPS. Kubernetes version 1.10.8

**Comment by geauxvirtual** [comment]
If you can't define a ServiceEntry for external ip addresses, you can use either includeIPRanges or excludeIPRanges to tell Istio what CIDRs to manage (includeIPRanges) and let everything else through, or to manage all CIDRs (*) and which CIDRs to exclude (excludeIPRanges). This is set when Istio is installed. There is a configmap that can be updated, and then the pod would need to be deleted so it's recreated with a sidecar with the updated config.

**Comment by vadimeisenbergibm** [comment]
@ssubramanian123 Check https://preliminary.istio.io/docs/tasks/traffic-management/egress/.
