### ISSUE TITLE
Support fully local testing

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#977]
It would be great to be able to run the entire testing suite (per-repo and per-istio) on a local cluster. This can help with de-risking test-infra cluster reliability, if developers can validate locally their contributions.

**Comment by ldemailly** [comment]
try to set milestone directly

**Comment by kyessenov** [comment]
minikube has been used successfully. I'll let @nmittler pick whether to use this issue to track container-less testing set-up or just close it.

**Comment by nmittler** [comment]
I think minikube is good enough for this issue.  If we decide we want container-less, we can open a new issue. Closing
