### ISSUE TITLE
Make --monitoringPort for pilot/mixer/galley configurable

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#9770]
**Describe the bug**
Attempted to deploy Istio without using the default `monitoringPort=9093` used by the istio controlplane.  This setting is not configurable via helm and pilot discovery fails to start when setting the --monitoringPort command line flag.

**Expected Behavior**
Expect to be able to easily configure this port via helm and for control plane to deploy properly

**Steps to reproduce the bug**
- download latest release of istio
- perform find/replace for all instances of port 9093 with desired port in install/kubernetes/istio-demo.yaml
- append `--monitoringPort=XXX` arg to istio-galley, istio-policy, istio-telemetry and istio-pilot deployments in install/kubernetes/istio-demo.yaml
- append `--monitoringAddr=":XXX"` arg to istio-pilot deployment in install/kubernetes/istio-demo.yaml
- `kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml &&  kubectl apply -f install/kubernetes/istio-demo.yaml`
- check logs: `kubectl logs -n istio-system istio-pilot discovery` 

**Version**
1.0.3

**Comment by GregHanson** [comment]
link to modified release istio-demo.yaml
https://gist.github.com/GregHanson/a6a0b634188671e3278e79bf0528376b

**Comment by GregHanson** [comment]
Error returned by pilot when attempting to use port 9094 for example for the monitoring port
```
          args:
          - "discovery"
          - --monitoringPort=9094
          - --monitoringAddr=":9094"
```

```
2018-11-02T20:16:07.538631Z    info    Discovery service started at http=[::]:8080 grpc=[::]:15010
Error: failed to start discovery service: unable to listen on socket: listen tcp: address tcp/9094": unknown port
2018-11-02T20:16:07.539046Z    error    failed to start discovery service: unable to listen on socket: listen tcp: address tcp/9094": unknown port
```

**Comment by GregHanson** [comment]
assigning nmittler since since he was the last person to modify those flags in pilot

**Comment by GregHanson** [comment]
the reason for trying to run Istio on a different monitoringPort is because Kafka uses port 9093 for its message brokers.  Attempting to create a required TCP listener on 9093 via a ServiceEntry results in a port conflict (since istio control plane has a HTTP listener on 9093 already) and the new listener is silently rejected

**Comment by douglas-reid** [comment]
Wasn't `monitoringPort` just removed from pilot?  Does this work if you *only* set --monitoringAddr ?

**Comment by douglas-reid** [comment]
BTW, changing the monitoring port in the args should also be reflected in the artifacts for the services/deployments (as this will impact metrics gathering). Example: https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/mixer/templates/service.yaml#L20-L21

**Comment by linsun** [comment]
close it per made http-monitoring port configurable for istio control plane #10019
