### ISSUE TITLE
AB stress testing: istio performance ERROR: Benchmarking 10.0.*.* (be patient)...apr_pollset_poll: The timeout specified has expired (70007)

### ISSUE THREAD

**Issue by SFHfeihong** [istio/istio#9778]
Istio version: 1.0.2
k8s version: 1.9.3

I create deployment and service. It has been injected by sidecar. I create gateway and virtualservice. It can be visited by "curl  http://10.0.*.*:31380/productpage". But it has errors when i use "AB" to do stress testing.

ab -n 1 -c 1 -k http://10.0.*.*:31380/productpage
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.0.*.* (be patient)...apr_pollset_poll: The timeout specified has expired (70007)

I use "jmeter", it also works well.

**Comment by ibrokethecloud** [comment]
`ab` only supports http 1.0 and envoy requests an upgrade to http 1.1 and `ab` is unable to handle the same.

Please try and add `-v 3` to the test and you will see this effect in action.
