### ISSUE TITLE
issue with weight based traffic routing

### ISSUE THREAD

**Issue by Sheshagiri** [istio/istio#9785]
**Describe the bug**
I'm not able to get the weight based routing work with the [sample app](https://github.com/Sheshagiri/Hello-Go/tree/routing) as described in https://istio.io/docs/reference/config/istio.networking.v1alpha3/ 

**Expected behavior**
I'm expecting for the requests to be routed to a different version based on the weight specified against each version. When the url is invoked I see the following error.
```
upstream connect error or disconnect/reset before headers
```

**Steps to reproduce the bug**
Install Istio 1.0.3 
kubectl apply -f https://github.com/Sheshagiri/Hello-Go/blob/routing/deploy/kubernetes/hello-go-all-routing.yaml -n <namespace with istio-injection enabled>

**Version**
Istio
```Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```
k8s
```Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
On premise installation of Istio. k8s is setup with kubeadm with metal as external loadbalancer.

**Environment**
On premise. VMware Workstation Player-15. VM's with Ubuntu 16.04.5 LTS.

**Cluster state**
Please find attached the logs.
[istio-dump.tar.gz](https://github.com/istio/istio/files/2557365/istio-dump.tar.gz)

**Comment by esnible** [comment]
This may not be a problem with weights but a general problem with your application or your mesh.

This error is usually associated with HTTP 503 response codes and with mutual TLS (mTLS) mismatches.  Can you run `istioctl authn tls-check` and see if there are `CONFLICT`s?

**Comment by Sheshagiri** [comment]
@esnible thank you for letting me know. I don't have the setup any more. I tried the sample book info app and that seem to be working as expected. I'll close this for now and come back if this happens again.
