### ISSUE TITLE
`kubectl get -o=yaml --export` gives empty elements on istio resources

### ISSUE THREAD

**Issue by Velyks** [istio/istio#9789]
**Describe the bug**
When performing `kubectl get -o=yaml --export` on istio custom resources, elements inside the yaml are incorrectly set to `""`

Example, `clusterName`, `namespace`, `resourceVersion`, and `uid` shouldn't be there:
``` yaml
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  clusterName: ""
  generation: 1
  name: bookinfo-gateway
  namespace: ""
  resourceVersion: ""
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/gateways/bookinfo-gateway
  uid: ""
```

**Expected behavior**
When using `--export` the kubernetes-generated elements should be completely omitted

**Steps to reproduce the bug**
Perform `kubectl get -o=yaml --export <name>` on an istio custom resource

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio: 1.0.2
kube: 1.10.3-eks

**Installation**
Via helm

**Environment**
Amazon EKS

**Cluster state**
Will provide if necessary, but I don't think it is.

**Comment by ayj** [comment]
> --export=false: If true, use 'export' for the resources.  Exported resources are stripped of cluster-specific
> information.
> 

The documentation for `kubectl get --export` says that cluster-specific information is stripped. In your example, this is true and those fields are set to `""`.  Other non-Istio CRD behavior in a similar way with kubectl.

**Comment by Velyks** [comment]
Can you give examples so I can raise the same issue with them? CRDs should act consistently with the non-custom resources.
