### ISSUE TITLE
Should istioctl use the default namespace from kubectl config when it exists?

### ISSUE THREAD

**Issue by emaildanwilson** [istio/istio#979]
When walking through the bookstore guide and examples for traffic routing I found that objects created w/ kubectl ended up in the namespace configured in my local kubectl context but the `istioctl create -f` commands used the default namespace which was different than I expected.

I see now in the guide that one could also use kubectl directly to apply those routes which is an ok workaround but should istioctl just use the same namespace from the kube config? It's getting other cluster context data from there anyways, right?

Let me know if you think this makes sense or not, happy to help out if it does.

**Comment by kyessenov** [comment]
I think it does make sense, and we do indeed ignore the kubectl context namespace field. I think it sounds reasonable to respect the context namespace. The two command line tools might be interchangeable after awhile (there's extra validation with istioctl). The code is here: 
https://github.com/istio/pilot/blob/master/cmd/istioctl/main.go

There is some (unrelated) context usage here https://github.com/istio/pilot/blob/master/cmd/istioctl/main.go#L440
