### ISSUE TITLE
Pilot doesn't listen for mesh config changes

### ISSUE THREAD

**Issue by jwendell** [istio/istio#9799]
In a default k8s deployment, where the mesh config comes from a file within a volume that comes from the `istio` configmap, Pilot doesn't listen for changes in that file.

Thus, if we change something the the `istio` configmap, those changes will never reach Envoys, unless we restart pilot.

**Comment by rshriram** [comment]
This has been fixed..

**Comment by rshriram** [comment]
cc @ymesika

**Comment by ymesika** [comment]
Currently the Mesh config file watcher only tells the XDS server about the update.
The `policyCheckFailOpen` is used by the Mixer and we currently don't have the logic for updating Mixer with the new config.
