### ISSUE TITLE
perf: Investigate alternatives to optimize json marshal/unmarshal on Pilot

### ISSUE THREAD

**Issue by jnativio** [istio/istio#9800]
**Describe the feature request**
Pilot spends a lot of time with json marshaling/unmarshaling, as shown in the flame graph below obtained when Pilot was very busy:

![image](https://user-images.githubusercontent.com/18554027/48163435-aa595180-e2ad-11e8-9e28-cb5377ce8b76.png)

The complete flame graph can be found here --> https://ibmcloud-perf.istio.io/data_istio/pilot_flamegraphs/

**Describe alternatives you've considered**
One alternative could be the usage of a fast json serializer like ffjson.

**Comment by mandarjog** [comment]
There has been prep work done on this to address the problem in two ways.
1. Put a cache in front of messageToStruct
 The cache is not effective because structures contain data that varies by each proxy. Specifically proxy uid and namespace.

Proxy no longer needs this, so now a simple cache can be placed here after eleminating the uids 

2. Use any encoding instead of struct. Waiting for envoy api change to make that happen.

**Comment by irisdingbj** [comment]
@mandarjog  For #1, can you clarify whether we need the proxy uid and namespace or not? Also are you working on this now?
For #2, I have not found issue opened in envoy.  Do you have some clues for it? 
  // [#not-implemented-hide:]
  // The per_filter_config field can be used to provide virtual host-specific
  // configurations for filters. The key should match the filter name, such as
  // *envoy.buffer* for the HTTP buffer filter. Use of this field is filter
  // specific; see the :ref:`HTTP filter documentation <config_http_filters>`
  // for if and how it is utilized.

Thanks a lot

**Comment by irisdingbj** [comment]
Trying to add a cache for this to avoid converting frequently.

**Comment by jnativio** [comment]
Measurements done with image containing #10292 changes and comparing with build release-1.1-20181208-09-15. The scenario consisted in deploying a new pod/service in a cluster with a number of pods already present and measuring the startup time for the new pod and the Pilot cpu/mem consumption. It was done with no other service present and 200 services present.

Startup time for a new pod:
![image](https://user-images.githubusercontent.com/18554027/49828725-95635880-fd5a-11e8-83d1-06ac6e5e7000.png)

Pilot CPU consumption: 
![image](https://user-images.githubusercontent.com/18554027/49828853-f12de180-fd5a-11e8-826f-b8dbc261ce38.png)

Pilot Memory footprint:
![image](https://user-images.githubusercontent.com/18554027/49828868-f9861c80-fd5a-11e8-90bd-c9a0fc3dff7b.png)

Flamegraphs for these cases can be found here:   https://ibmcloud-perf.istio.io/data_istio/pilot_flamegraphs/patch_10292/

**Comment by mandarjog** [comment]
This is great, pilot cpu and memory cut down by >50%

**Comment by irisdingbj** [comment]
Adding a cache for mixer route config using service host name+ inbound/outbound as key to prevent repeated the json <-> protobuf convention. Now all testing passed and waiting for PR merge : https://github.com/istio/istio/pull/10292

**Comment by irisdingbj** [comment]
@suryadu ^^^

**Comment by jnativio** [comment]
@irisdingbj Is this issue still valid and should remain open or the changes were already incorporated to 1.1?

**Comment by kyessenov** [comment]
We can close this. The linked PRs provide the desired optimizations, although both are disabled due to unexpected side effects.
