### ISSUE TITLE
perf: Investigate possible optimizations in the mixer filter codepath for Envoy

### ISSUE THREAD

**Issue by jnativio** [istio/istio#9802]
**Describe the feature request**
A flame graph obtained from istio-proxy sidecar during load shows that it spends considerable time in the mixer filtering:

![image](https://user-images.githubusercontent.com/18554027/48164338-2f456a80-e2b0-11e8-9ecd-63729735ddab.png)

**Describe alternatives you've considered**
Evaluate the codepath related to filtering to see if performance optimizations can be implemented.

**Comment by cmluciano** [comment]
istio/proxy#1970 decreased the ReportBatch operation by a bit as seen in the [before](https://ibmcloud-perf.istio.io/regpatrol/1.0.3/istio_full//flamegraphs/flame.envoy.flight.svg) and [after](https://ibmcloud-perf.istio.io/regpatrol/release-1.1-20181120-09-15/istio_full//flamegraphs/flame.envoy.flight.svg).

Two more possible enhancements:
- [istio::mixerclient::CompressByDict ](https://github.com/istio/proxy/blob/master/src/istio/mixerclient/attribute_compressor.cc#L85)(10.91% of ReportBatch's total 23.50%)
- [istio::control::http::RequestHandlerImpl::Check](https://github.com/istio/proxy/blob/master/src/istio/control/http/request_handler_impl.cc#L63)
