### ISSUE TITLE
Stackdriver Adapter does not batch requests to Context Graph API

### ISSUE THREAD

**Issue by jeffmendoza** [istio/istio#9803]
As noted in the TODO here:
https://github.com/istio/istio/blob/release-1.1/mixer/adapter/stackdriver/contextgraph/send.go#L122

This API has a  max size of 600K. Sometimes we are calling it with a larger size. Istio needs to batch large requests.

I'd like to get this fix into Istio 1.1 if possible.

**Comment by douglas-reid** [comment]
Closing, as PR fix is merged.
