### ISSUE TITLE
Mesos support?

### ISSUE THREAD

**Issue by harryge00** [istio/istio#9821]
**Describe the feature request**
Can Istio run on Mesos/Marathon directly? Such as a framework, or as containers managed by Marathon.

**Describe alternatives you've considered**
Now Kubernetes can run on DC/OS, and Istio can run on K8s. But this means other services running on Mesos (out of K8s service) can not access Istio directly.

**Comment by stevenlee87** [comment]
Istio does not currently have native support for Mesos.However, you can take advantage of our integration with Consul to run Istio Mesh on Mesos with it.For more details, refer to the Consul installation.

**Comment by harryge00** [comment]
@stevenlee87 Thanks. I will have a try.
