### ISSUE TITLE
Consume Envoy Stats and Publish to Adapters

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#9827]
**Describe the feature request**
Envoy generates a lot of stats which might be useful to external adapters, and for use cases like #8902.

**Additional context**
Prometheus does access these stats currently; however, we need some work to support that for other adapters.

/cc @mandarjog

**Comment by mandarjog** [comment]
Can you provide a clear use case here? The linked issue is a use case, but it is already supported by Mixer core (`context.proxy_error_code` sans a few config changes).

It makes sense to expose all request bound / related metrics, but generally making all metrics available to adapters does not make sense to me.

**Comment by venilnoronha** [comment]
Stats around upstream/downstream connections, memory allocation, etc. can be quite useful. These stats are served at the proxy level and not per request, so we might need some work around obtaining such stats from Envoy.

**Comment by douglas-reid** [comment]
@venilnoronha I'm going to close this for now. There are several options for export of envoy metrics within the system (and including things like the OpenCensus service). There is no planned work on the horizon for Istio to take on this work.

**Comment by venilnoronha** [comment]
Okay, thanks for the heads up.
