### ISSUE TITLE
Compliance testing for our public APIs

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#983]
[P0] Attributes specification verification
[P1] Pilot xDS API compliance
[P1] Mixer API compliance
[P2] Proxy behavior compliance testing

**Comment by sakshigoel12** [comment]
@hklai please assign this issue if it is still considered P0

**Comment by hklai** [comment]
"area/test and release" is meant for common test infra and improvements, and release automation. 
I have reassigned to the appropriate areas, and the leads can decide the priorities.

**Comment by ozevren** [comment]
Can you add more details to this issue? Specifically, what are the goals for having this set of compliance tests? Is the goal is to ensure we can replace any of the Istio components in a reliable way?

**Comment by andraxylia** [comment]
@ozevren yes, and that our components have an API that is defined and it is backward compatible.

**Comment by douglas-reid** [comment]
Removing p&t label, as i don't think that we will be establishing new tests for mixer API, given the technical direction we are now moving in.
