### ISSUE TITLE
Ingress with host network

### ISSUE THREAD

**Issue by decker502** [istio/istio#984]
The `hostnetwork` configuration option of Deployment does not take effect, after pod started  the `80` and `443` port did not find

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: istio-ingress
      namespace: istio-system
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            istio: ingress
        spec:
          nodeSelector:
            kubernetes.io/role: istio
          hostNetwork: true
          serviceAccountName: istio-ingress-service-account
          containers:
          - name: istio-ingress
            image: reg.miz.so/istio/proxy_debug:0.2.4
            args:
            - proxy
            - ingress
            - -v
            - "2"
            - --discoveryAddress
            - istio-pilot:8080
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
            - containerPort: 443
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: istio-certs
              mountPath: /etc/certs
              readOnly: true
            - name: ingress-certs
              mountPath: /etc/istio/ingress-certs
              readOnly: true
          volumes:
          - name: istio-certs
            secret:
              secretName: istio.default
              optional: true
          - name: ingress-certs
            secret:
              secretName: istio-ingress-certs
              optional: true

**Comment by markeijsermans** [comment]
Another option might be to use `hostPort`s on your pod spec. Perhaps binding on ports <1024 is restricted for your system and requires "privileged" mode? Try:
```yaml
spec:
  template:
    spec:
      containers:
      #...
        ports:
        - containerPort: 80
           hostPort: 8080
        - containerPort: 443
           hostPort: 8443
```
This is the solution I used to wire up the ingress running on a dedicated worker pool (separate autoscale group) to our public facing ELB's

**Comment by ayj** [comment]
Issue moved to [istio/pilot #1478](https://github.com/istio/pilot/issues/1478) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chenleji** [comment]
use NodePort or hostPorts.
