### ISSUE TITLE
pilot/pkg/proxy/envoy tests are flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#9864]
Source:
https://testgrid.k8s.io/istio-postsubmits#unit-tests
https://testgrid.k8s.io/istio-postsubmits#circleci-test

TestEds:
https://gubernator.k8s.io/build/istio-prow/logs/istio-postsubmit/3726
https://circleci.com/gh/istio/istio/242960

TestAdsClusterUpdate
https://gubernator.k8s.io/build/istio-prow/logs/istio-postsubmit/3721
https://circleci.com/gh/istio/istio/242629

**Comment by hzxuzhonghu** [comment]
About `TestAdsClusterUpdate` I found that the flake caused by the initial push all has not finished when the request for `cluster` comes.

**Comment by hzxuzhonghu** [comment]
`TestEds/PushIncremental` flake is caused by this.

https://github.com/istio/istio/blob/a6bfa7ba6723d6b562616607afce8e4c85797662/pilot/pkg/proxy/envoy/v2/xds_test.go#L287

Confirmed by remove the sleep.

**Comment by irisdingbj** [comment]
fixed already.
