### ISSUE TITLE
Test flakiness: Running out of Boskos resource

### ISSUE THREAD

**Issue by hklai** [istio/istio#9865]
Example:
https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3/10946

Even though the dashboard says it still has free cluster at around that time
![rbdbcvw54hz](https://user-images.githubusercontent.com/31747472/48290607-5030cb80-e428-11e8-8ae3-46b9e3e0cd7b.png)

**Comment by sebastienvas** [comment]
When looking at the resource at 2018-11-09 08:21 PST, there is actually no more free resources.

**Comment by sebastienvas** [comment]
Sorry I resolved this last week, by adding more resources.
