### ISSUE TITLE
Pilot E2E tests are flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#9867]
* TestVirtualServiceMergingAtGateway
Examples: 
https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3-k8s-latest/596
https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3-k8s-latest/589

* TestIngressGateway503DuringRuleChange
Example: 
https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3-k8s-latest/596

* TestGateway
Example:
https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3-k8s-latest/567

**Comment by smawson** [comment]
Andy are these tests still failing regularly? What are next steps to figure out the issue here?

**Comment by hklai** [comment]
The tests are mostly green recently.
https://testgrid.k8s.io/istio-postsubmits#pilot-e2e-envoyv2-v1alpha3
https://testgrid.k8s.io/istio-postsubmits#circleci-e2e-pilot-auth-v1alpha3-v2

The remaining occasional flakes are:
* TestVirtualService and TestGateway
E.g. https://gubernator.k8s.io/build/istio-circleci/e2e-pilot-noauth-v1alpha3-v2/289657
We need some help from the pilot folks to fix them.

* startup problem
E.g. https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3/13243. 
There seems to be many variations of symptoms. I will try to categorize them.

* clean up timeout problem 
E.g. https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3/13363 
It had been fixed last week by https://github.com/istio/istio/pull/10878

**Comment by smawson** [comment]
Create you create more targeted issues for those and then close this one out?

**Comment by duderino** [comment]
@hklai can you create issues for each issue and link them here?

**Comment by hklai** [comment]
There are some occasional flakes like https://gubernator.k8s.io/build/istio-prow/logs/istio-pilot-e2e-envoyv2-v1alpha3/14810, but relatively rare.

Closing this for now.
