### ISSUE TITLE
Mixer E2E MCP tests are failing

### ISSUE THREAD

**Issue by hklai** [istio/istio#9872]
Apparently they had not passed for a long time.

https://testgrid.k8s.io/istio-postsubmits#circleci-e2e-mixer-noauth-v1alpha3-v2-mcp
https://testgrid.k8s.io/istio-presubmits#e2e-mixer-no_auth-mcp

Please fix or remove to reduce noise.

**Comment by ozevren** [comment]
There is a pending fix: https://github.com/istio/istio/pull/9862

**Comment by ayj** [comment]
Fixed in master by https://github.com/istio/istio/pull/9873. General e2e-mixer auth flakiness tracked by https://github.com/istio/istio/issues/9858
