### ISSUE TITLE
Images on gcr.io/istio-release tag:master-latest-daily not getting pushed

### ISSUE THREAD

**Issue by offzale** [istio/istio#9876]
I'm trying to get latest image of galley from master-latest-daily tag but it seems not to be updated. I'm running Istio from master branch and the only error I am getting is from galley. 
```
Error: unknown flag: --meshConfigFile
```

But I saw the [commit](https://github.com/istio/istio/commit/bfa4aaa0d50bb81e16997b72dc9179bf93a93df6
) with the changes got merged into master more than a day ago.

Then I checked the [registry](https://console.cloud.google.com/gcr/images/istio-release/GLOBAL/galley?gcrImageListsize=30) and last "daily" image from master got pushed on Thursday Nov 8th. However, daily images from release-1.0 and release-1.1 are still being generated.

Is the `master-latest-daily` tag build/push broken? 

**Steps to reproduce the bug**
Pull the image:
`docker pull gcr.io/istio-release/galley:master-latest-daily`

Run the help command to check that flag _meshConfigFile_ is not in there:
`docker run gcr.io/istio-release/galley:master-latest-daily --help`

**Version**
Istio master branch d4f2522b5dba3849258093bf2700c681fbf392b0
Kubernetes 1.12

**Comment by clyang82** [comment]
+1
I met the same issue that the `master-latest-daily` cannot get pushed, because the `imagePullPolicy: IfNotPresent`. You can modify it to `imagePullPolicy: Always` to pull the latest images.

**Comment by ozevren** [comment]
@hklai Assigning to you. I believe this is fixed. Could you confirm?

**Comment by hklai** [comment]
Yup these tags are getting pushed.
