### ISSUE TITLE
Are you going to support etcd-based environments?

### ISSUE THREAD

**Issue by jiming** [istio/istio#988]
> Istio currently supports Kubernetes, Consul, Eureka-based environments. We plan support for additional platforms such as Cloud Foundry, and Mesos in the near future.

I feel wierd. K8S is using etcd, are you going to support etcd-based environments? Or, why not etcd-based environment? Thanks!

**Comment by rshriram** [comment]
Can you provide more information? What exactly do you mean by etcd based environments? Do you have a custom service registration format ? The nice thing about K8s, Consul, Eureka, etc. is that the scheme for service information is well defined and allows us to write adapters in Pilot that will work for every one using these platforms.  Plain etcd backend implies that you as user can register your services and store the registration information in any format you want. In this case, Pilot would have no way of interpreting the information in the backend datastore

**Comment by jiming** [comment]
I am on the very begining of evaluating latest micro service platform.

Istio looks exciting. Currently all of zookeeper, etcd, consul, eureka could be used as service registry. Apprently I don't want to use all of them. The best solution is to use only one of them, which could reduce admin resources. 

I pick zookeeper so far. Although it is old and heavy, it is more mature and third part tools support. 

Then k8s using etcd, so I have to use etcd too, and manage it with extra. So bad.

When reading your document, I read this:

> Istio currently supports Kubernetes, Consul, Eureka-based environments. We plan support for additional platforms such as Cloud Foundry, and Mesos in the near future.

I really do not want to maintain one more similar thing to using istio. So far I still not sure how consul, eureka works in istio. I mean if consul and eureka are important part, I wish I can use zookeeper or etcd to replace them. Otherwise, I am ok.

Have a nice day!

Jiming

**Comment by ldemailly** [comment]
You can use etcd as the k8s api server storage even if you don’t want all of kubernetes

**Comment by jiming** [comment]
@ldemailly 

k8s is a must used service, so I must use etcd. 

What I wanted to say is that I wish I can use istio without consul or eureka. In case consul or eureka is a necessary, I wish I can use etcd or zookeeper to replace them.

Thanks!

**Comment by ldemailly** [comment]
you can by registering your services into k8s, see the mesh expansion on our website (note this is an early feature)

**Comment by jiming** [comment]
ok, thank you very much!
