### ISSUE TITLE
HPA disabled for Telemetry and Policy due naming mismatches

### ISSUE THREAD

**Issue by jnativio** [istio/istio#9881]
**Describe the bug**
HPA is disabled  by default for Telemetry and Policy on build release-1.1-20181109-09-15. The reason this appears to be changes in naming introduced by PR #9768, that caused some names mismatches in the helm values:
on install/kubernetes/helm/istio/values.yaml:
_mixer:
 **policy:**
   enabled: true
 **telemetry:**
   enabled: true_

but on install/kubernetes/helm/subcharts/mixer/values.yaml:
**istio-policy:**
  _enabled: true
  replicaCount: 1
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80

**istio-telemetry:**
 enabled: true
 replicaCount: 1
 autoscaleEnabled: true
 autoscaleMin: 1
 autoscaleMax: 5
 cpu:
   targetAverageUtilization: 80_

Maybe there other mismatches in other files in other files, but I noticed the effect of this one.

**Expected behavior**
Have HPA enabled by default for these components.

**Steps to reproduce the bug**
Check the names mismatch on this build

**Comment by linsun** [comment]
Thank you @jnativio !!  https://github.com/istio/istio/pull/9890

**Comment by linsun** [comment]
#9890 is merged now and should fix this @jnativio - thank you for reporting this!
