### ISSUE TITLE
Helm upgrades are broken related to CRDs

### ISSUE THREAD

**Issue by sdake** [istio/istio#9884]
**Describe the bug**
The information for the bug starts hjere:
https://github.com/istio/istio/issues/9604#issuecomment-437291974

**Expected behavior**
helm upgrade adds crds as required

**Steps to reproduce the bug**
See reproducer in https://github.com/istio/istio/issues/9604

**Version**
1.0, master

**Installation**
any installation involving `helm upgrade`.  `helm template` / `kubectl apply` work well.

**Environment**
Kubernetes 1.10, Istio release-1.0, istio-release-1.1, bare metal, metallb load balancer

**Comment by sdake** [comment]
#9847

**Comment by ayj** [comment]
Specifically for 1.1, given that `crd-install` is broken for upgrades, is there any reason we can't use the [helm < 2.10.0 two-step install process](https://istio.io/docs/setup/kubernetes/helm-install/#installation-steps) with helm upgrade? CRD aren't managed anyway and Istio CRD are left in the cluster after `helm del --purge istio`.  

```bash
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.crds=false
```

We'd need to modify the crds.yaml template as follows to not automatically install CRD with newer helm versions:

```diff
diff --git a/install/kubernetes/helm/istio/templates/crds.yaml b/install/kubernetes/helm/istio/templates/crds.yaml
index b2c70b3..645fa7b 100644
--- a/install/kubernetes/helm/istio/templates/crds.yaml
+++ b/install/kubernetes/helm/istio/templates/crds.yaml
@@ -1,4 +1,4 @@
-# {{ if or .Values.global.crds (semverCompare ">=2.10.0-0" .Capabilities.TillerVersion.SemVer) }}
+# {{ if .Values.global.crds  }}
 # these CRDs only make sense when pilot is enabled
 # {{- if .Values.pilot.enabled }}
 apiVersion: apiextensions.k8s.io/v1beta1
```

We could also change the default for `global.crds` to `false` and require 2-step for `helm template` and `helm install` methods and even `kubectl apply`.

**Comment by sdake** [comment]
@ayj your proposal is viable for folks that have not used Helm 2.10+ to install Istio.  If they have the following constraints apply:

https://github.com/istio/istio/issues/9604#issuecomment-437372398

Quoted here:
```
Subscribing to this - we have a similar issue with cert-manager too.

To roughly summarise the current position, which I think applies to Istio too:

- Users upgrading from a release without the annotation see all their CRDs deleted (which is really, really bad)
- Users who upgrade and then manually fix it (by manually deleting/creating CRDs), will not be able to upgrade if we remove the annotation
- Users who install for the first time with the annotation will not be able to upgrade if we remove it, and won’t get updates to CRDs if we keep it

I'm hoping to hear back from the wider Helm community on what a recommended path to fixing this is - I think a 2-phase Helm install may be required.
```

In short, we can't do the following:
- remove the annotation as I have done in https://github.com/istio/istio/pull/9847.  The annotations need to stay.

I really like @costinm's proposal of removing the new CRDs from 1.0.4 - this simplifies 1.0.4 and lets us release now to provide a little more time to release 1.1.  This may require us to call 1.0.3 DOA for `helm install` installation models.  I'd encourage @hklai's feedback on this idea - with possible notification in the artifact download that using `helm install` with 1.0.3 is dangerous and should be avoided.

For 1.0.4, I'd recomend @costinm's approach of removing the two CRD entries as they are not critical *in comparison* to providing an upgrade experience that is painless.  In this model, we keep the single step install process.

For 1.1, we can introduce a μ-operator in short order that simply handles CRD creation from a configmap as you had proposed - even something simple as a shell script container which loops... as unsatisifying as that is)  and keep the Helm CRD code as is.  In this model, we keep the single step install process.

For 1.2, we can come up with more complete design plans for an upgrade approach which may involve a coherent operator approach while not under release pressure.

Cheers
-steve

**Comment by ayj** [comment]
Removing the new CRD as a temporary mitigation seems reasonable. 1.0.3 would be discouraged and we'll need to provide documented workarounds for those that have already applied it.

I wasn't suggesting we remove the `crd-install` annotation (yet). That would need to come later post 1.1, either with a helm fix (e.g. 3-way merge) or we switch away from helm for managing CRDs. I was trying to understand the case where we'd need to keep the new CRD. If we don't, then @costinm's proposal works.

**Comment by sdake** [comment]
A more advanced take on this problem (for 1.1 or 1.2) is in this PR: https://github.com/istio/istio/pull/10015.  I am unclear if we have enough time available to properly test this approach for 1.1.  It may make more sense to just forward port https://github.com/istio/istio/pull/10005 to 1.1 and introduce the operator approach as a more completely baked implementation in 1.2.

Cheers
-steve

**Comment by sdake** [comment]
> Removing the new CRD as a temporary mitigation seems reasonable. 1.0.3 would be discouraged and we'll need to provide documented workarounds for those that have already applied it.
> 
> I wasn't suggesting we remove the `crd-install` annotation (yet). That would need to come later post 1.1, either with a helm fix (e.g. 3-way merge) or we switch away from helm for managing CRDs. I was trying to understand the case where we'd need to keep the new CRD. If we don't, then @costinm's proposal works.


Fwiw, Helm upstream has indicated they have no interest in a 3 way merge upstream at least for the 2.y.z series.  They left 3.y.z open for debate IIUC.

Otherwise, agree.  I did ask @douglas-reid to review and verify the removal of the CRDs would not cause the telemetry WG significant difficulties.

Cheers
-steve

**Comment by sdake** [comment]
Solution to this problem: https://github.com/istio/istio/pull/10120

**Comment by sdake** [comment]
An earlier solution to this problem: https://github.com/istio/istio/pull/10015

**Comment by sdake** [comment]
Costin's Helm chart restructure: https://github.com/costinm/istio-helm/blob/master/README.md

**Comment by sdake** [comment]
A thread on istio-env asking for assistance on this issue: https://groups.google.com/forum/#!topic/istio-dev/J5gy_7pSwCc

**Comment by sdake** [comment]
The current status of this issue is as follows:
- `crd-install` is defective in Helm 2.y.z series
- Helm upstream very focused on implementing helm 3.y.z and is not accepting PRs for 2.y.z series.
- A process-based implementation has been generated
- An implementation in Galley has been generated
- High level details of the implementation
  - The implementation reads configmaps
  - The configmaps contain raw CRDs to instantiate in the system
  - The implementation is safe in an upgrade scenario in either `template` & `kubectl apply` or `install` & `upgrade` modes of installation.
  - The implementation requires removing `tiller`'s knowledge of the CRDs.

1. The galley based implementation requirees splitting the Helm charts into two charts:
  - One chart contains:
    - configmaps
    - citadel
    - galley
  - The other chart contains the remainder of the manifests.
2. The single process based implementation requires splitting the Helm charts into two charts:
  - One chart contains:
    - configmaps
    - citadel (this could possibly go in the second set of charts)
    - process to read configmaps and convert to CRDs dynamically via a Kubernetes deployment.
    - the process could be reworked into a Kubernetes job.
  - The other chart contains the remainder of the manifests.

Any of this work **depends** on the ability to instruct Helm's `tiller` deployment to no longer have copies of the CRDs.

Tiller stores deployment information in protos within a uuencoded gzipped `configmap`.  In older versions of Helm the deployments are not gzipped.  @sbezverk is taking a look at the possibility of writing a tool to delete CRDs from the tiller stored deployments by directly manipulating the configmap that tiller uses.  The tool would **not** delete Kubernetes CRDs.

With such a tool, the upgrade workflow of 1.1 would be:

1. run @sbezverk tool to instruct Helm to no longer be aware of the CRDs.
2. `helm install` the `isito-system` chart (containing the first of the charts listed above in either of the options.
3. `helm upgrade istio` (the second chart of the charts listed above in either of the options).

This may result in some minimal outage with tiller, as it may be mandatory to stop the `tiller` pod while modifying the configmaps it operates with.   The tool @sbezverk is developing could do this.

The @sbezverk tool is speculative.  We don't yet know if it will work.  @Stono seemed to think the idea of having CRDs not known to Helm is solid.

Some in our community will not want a multistep upgrade process.  I'm not sure how to manage expectations related to multi-step upgrade.  We promised we would offer one step install and upgrade using Helm but we never really deliverred on this promise.

There is alot more detail in the PRs linked above and the thread started on istio-env & istio-dev.

Cheers
-steve

**Comment by sdake** [comment]
@munnerz approach to this problem:

https://gist.github.com/munnerz/9c08a5744a73ff63f96ae16e7a96c392

I had thought of this line of approach, however, it doesn't solve upgrades for 1.1.  I had thought of an intermediate step in addition where we have a two phase upgrade to get us to a crd-definition-free implementation in 1.1

**Comment by sdake** [comment]
@sbezverk 'z tool works correctly in an upgrade.  He is working up a PR for release-1.1 branch now from my understanding.  It isn't mandatory to run, unless the operator has deployed with Helm < 2.10.  I'd recommend just running it in all conditions to simplify the upgrade process.

**Comment by sdake** [comment]
@sbezverk 'z tool: https://github.com/istio/istio/pull/10155

**Comment by jasminejaksic** [comment]
Based on discussion with @costinm and team, the fix is good enough, so closing the issue.
