### ISSUE TITLE
Increase the stability of test e2e-mixer-no_auth

### ISSUE THREAD

**Issue by supereagle** [istio/istio#9899]
Test `e2e-mixer-no_auth` always fails, but is not caused by the code changes of PRs.
As it is a required CI, so PRs are frequently blocked by this test. I think we need to increase the stability of this test.

xref: [Build history of e2e-mixer-no_auth](https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/e2e-mixer-no_auth)

**Comment by douglas-reid** [comment]
It looks like some of the failures are related to `TestKubeenvMetrics`, which assumed a single `istio-ingressgateway` pod. I have a PR in-dev that fixes this issue.

**Comment by douglas-reid** [comment]
The two most recent failures were test init failures. I'll monitor this over the next week to see what else needs to be addressed from a test execution perspective.

**Comment by douglas-reid** [comment]
@supereagle mind if we track stability fixes with #9858 ?  I'll close this for now. If not, please feel free to reopen this issue.

**Comment by supereagle** [comment]
@douglas-reid  It's ok
