### ISSUE TITLE
Helm install Option 2 failed at Prometheus configmap

### ISSUE THREAD

**Issue by vnugent** [istio/istio#9918]
**Describe the bug**
I followed preliminary docs [Helm install option 2](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install)

For step 3 I ran the following:
```
 helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set kiali.enabled=true --set gateways.istio-ingressgateway.type=NodePort
```
Error:

> Error: render error in "istio/charts/prometheus/templates/configmap.yaml": template:  istio/charts/prometheus/templates/configmap.yaml:32:16: executing "istio/charts/prometheus/templates/configmap.yaml" at <.Values.global.proxy...>: can't evaluate field prometheusPort in type interface {}

**Expected behavior**
`helm install` should run to completion.  
 
**Steps to reproduce the bug**
`git checkout release-1.1`
 Follow 1.1 docs Helm install Option 2 https://preliminary.istio.io/docs/setup/kubernetes/helm-install

**Version**
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

# git log
commit eb41fafccde1f3749a0d821bcd3827482e79a320 (HEAD -> release-1.1, origin/release-1.1)
Author: Douglas Reid <douglas-reid@users.noreply.github.com>
Date:   Mon Nov 12 14:28:01 2018 -0800
...
```

**Installation**
Option 2 https://preliminary.istio.io/docs/setup/kubernetes/helm-install

**Environment**
Fedora 28

**Cluster state**
helm install failed

**Comment by douglas-reid** [comment]
Have you fetched and rebased recently?  I just created a branch tracking `release-1.1` and was able to successfully run `helm template` without issue. And running a `git grep prometheusPort` does not return any results in the `install` dir.

```
$ git log 
commit 61d5644273b3b1e24aeccd560658b48bda251b28 (HEAD -> helm-test, upstream/release-1.1)
Author: Jeff Mendoza <jlm@jlm.name>
Date:   Tue Nov 13 14:22:00 2018 -0800
```

**Comment by vnugent** [comment]
I applied `helm repo add...` in PR9920 and it solved my problem.   This [doc](https://preliminary.istio.io/docs/setup/kubernetes/helm-install) should be updated with those 2 additional steps as well
