### ISSUE TITLE
Istio policy may exists memory leak (Increase 4GB during 7 days)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#9928]
**Describe the bug**
Memory of istio-policy pod increase from 0GB to 4GB, after run cluster for 6 days.

Memory leak may exists on istio-policy

**Expected behavior**
No memory leak

**Steps to reproduce the bug**
Restart istio-policy, and continue to run cluster.
Monitor the memory in next 7 days.

**Version**
kubernest 1.9.5
istio 1.0.0

**Installation**
helm
no auth

**Environment**
latest coreos
CNI plugin is cilium

**Comment by johnzheng1975** [comment]
![isto-policy](https://user-images.githubusercontent.com/17720035/48427110-06870e80-e7a3-11e8-8a66-e403403a9683.png)

**Comment by johnzheng1975** [comment]
My current work around:
Increase policy replicator (hps min:2 max 5;)
Set the limit memory for istio-policy, let it restart if memory increase too much.

**Comment by douglas-reid** [comment]
@johnzheng1975 Can you share any info on the configured adapters you have for policy?

**Comment by mandarjog** [comment]
Can you export the mixer grafana dashboard to raintank ?
That will tell us goroutine use, adapters and errors.

**Comment by mandarjog** [comment]
@johnzheng1975  it would be great if you are able to use 1.0.3 for the same test and send us the dashboard. Thanks.

**Comment by munrodg** [comment]
@johnzheng1975 it would be great if you could use the latest 1.1 release for the same test and send us the dashboard. Thanks.

**Comment by mandarjog** [comment]
related to #10393

**Comment by duderino** [comment]
@mandarjog update please

**Comment by mandarjog** [comment]
The related #10393  caused kubenev adapter to never release k8s cache memory. It has been fixed in 1.1  and 1.0.
