### ISSUE TITLE
Helm charts dir is not included in istio-1.1 snapshot/daily

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#9931]
**Describe the bug**
Cannot use helm with Istio 1.1; fails with:

`Error: found in requirements.yaml, but missing in charts/ directory`

If you check the install/kubernetes/helm/istio directory there is no `charts` dir

**Expected behavior**
Expected installation to progress.

**Steps to reproduce the bug**
See below how I installed

**Version**

kubernetes:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.9", GitCommit:"6191a1d5adb87b656a6e14a9344267ccbfe4abc2", GitTreeState:"clean", BuildDate:"2018-11-02T23:33:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

istio:
version.BuildInfo{Version:"1.1.0-snapshot.2", GitRevision:"bd24a62648c07e24ca655c39727aeb0e4761919a", User:"root", Host:"6408abaf1dac", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}

This is true for both the latest istio-1.1 snapshot as well as the latest 1.1 daily builds

**Installation**
`helm install latest/install/kubernetes/helm/istio --name istio --namespace istio-system  \
    --set sidecarInjectorWebhook.enabled=false`

**Environment**
Mac OS X, on GKE

cc @sdake have you seen this also?

**Comment by linsun** [comment]
@christian-posta Check the instruction here:  https://github.com/istio/istio/pull/9920/files

**Comment by linsun** [comment]
basically you'd need `helm repo add` first, then run `helm dep update`

**Comment by douglas-reid** [comment]
I discovered a new make target: `make helm-update-repo` which handles the first step. There is not a `make helm-dep-update` as far as I can tell however.

**Comment by jmazzitelli** [comment]
OK, I see a PR has recently been created to add these instructions to the helm install Setup page. I added some comments because I don't think that PR is complete: https://github.com/istio/istio.io/pull/2876

**Comment by hklai** [comment]
It looks like a doc issue and istio/istio.io#2876 should address this.

Is there anything else that needs to be done here?

**Comment by munrodg** [comment]
Closed due to doc issue
