### ISSUE TITLE
Switch from gometalinters to golang-ci

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#9933]
We should switch from gometalinters to the new golangci-lint meta linter. It runs 5x-7x faster than golemtalinter and handles dependencies in a much cleaner way, ensuring consistent results.

https://github.com/golangci/golangci-lint

FYI: @douglas-reid @rshriram

**Comment by douglas-reid** [comment]
:+1: you had me at 5x faster and consistent results.

**Comment by kyessenov** [comment]
Is there anything I can help here? I'd like to fix the import sorting issue, in particular.

**Comment by geeknoid** [comment]
Well, you could do the work I suppose :-) I haven't started. I was going to
do it over the weekend...

**Comment by kyessenov** [comment]
Started https://github.com/istio/istio/pull/9970

**Comment by kyessenov** [comment]
Per offline discussion, it's up to pilot team to decide whether they want linting or not, since the rest of the code is linted. Therefore, assigning the issue to networking area.

**Comment by kyessenov** [comment]
Not all are recommended actually. I've tried nakedret, gosec, errcheck, goconst, maligned. There is a very large number of fixes needed (and of arguable quality). We can leave those for later, in case we decide to put in the work needed to fix all the files.
