### ISSUE TITLE
Configure ingress-gateways with URL references to certificates for SNI

### ISSUE THREAD

**Issue by shubhaat** [istio/istio#9944]
**Describe the feature request**
We want to be able to configure envoy to fetch secrets(TLS keypairs) from a remote secure store for vanity ingress domains. This would be more secure and dynamic.  

**Describe alternatives you've considered**
Currently the requirement that keypairs reside on the filesystem as the ingress-gateway is not ideal, updating the certificates is tedious and storing them on the file system is not secure. 

**Additional context**
- In Cloud Foundry we have heard from users that being able to dynamically configure key pairs that are stored at a secure location, and can be fetched when needed is preferable. 
- We also want to give users self service control on configuring these key pairs but users will not have access to the ingress-gateways

@rosenhouse , @shalako

**Comment by shalako** [comment]
@rshriram @Nino-K Could you tag this `help wanted`?

**Comment by rosenhouse** [comment]
I think we can make this work using SDS now.

**Comment by murarisumit** [comment]
@rosenhouse @shubhaat  if no one is doing it, can I pick this issue ?

**Comment by trevorlinton** [comment]
I believe this I related to https://github.com/istio/istio/pull/11496 and 
https://github.com/istio/istio/issues/9030

**Comment by shalako** [comment]
The CF team hasn’t started working on it; would love for someone to pick it up!

**Comment by rosenhouse** [comment]
@utako is this possible now with #11496 or other recent enhancements?

**Comment by rshriram** [comment]
yep

**Comment by myidpt** [comment]
With the new SDS enhancements, do we still need this feature? @shubhaat
