### ISSUE TITLE
Is it should be a delete event

### ISSUE THREAD

**Issue by acmore** [istio/istio#9949]
**Describe the bug**
https://github.com/istio/istio/blob/a247fd8985bf4434558320bd0fc1c3e3c01331aa/pilot/pkg/serviceregistry/kube/controller.go#L200 is it intended to be an add event?

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by ymesika** [comment]
Thanks. It's fixed in `release-1.1` by #9853.
