### ISSUE TITLE
Record basic performance metrics 

### ISSUE THREAD

**Issue by sakshigoel12** [istio/istio#995]
We need to re-capture performance metrics before launch

**Comment by ldemailly** [comment]
See https://github.com/istio/istio/issues/690
and https://github.com/istio/istio/issues/369

I don't think we have any claim to any specific numbers either for 0.1 or 0.2

**Comment by ldemailly** [comment]
done, manually for each release (see perf WG and https://fortio.istio.io )- integration with build and release automation tbd
