### ISSUE TITLE
Pod Disruption Budget for helm install

### ISSUE THREAD

**Issue by kimxogus** [istio/istio#9951]
**Describe the feature request**
As there's no pdb in helm chart, when you upgrade istio chart, existing pods turns into `Terminating` status before new pods become healthy which causes downtime! I temporally set `replicaCount: 2` to contain healthy pod, but I don't think this is right solution. Also, istio system downtime may cause without pdb in various situations like node draining.
I suggest to add PodDisruptionBudget templates for istio components.

**Describe alternatives you've considered**
Setting `replicaCount: 2`, but this doesn't seem to be right solution.

**Additional context**
Eviction like node draining(`kubectl drain`) can also cause istio downtime. As istio manages external endpoints, those downtime situations are critical.

**Comment by linsun** [comment]
close out, thank you @kimxogus for your contribution!

**Comment by duderino** [comment]
Reopening:  would be good to get some test feedback from Mandar here

**Comment by linsun** [comment]
Yes, I'm trying to get this tested in our upgrade test.  At least per yesterday's upgrade test, this portion run successfully.

https://github.com/istio-releases/pipeline/pull/209

**Comment by sdake** [comment]
@mandarjog https://github.com/istio/istio/issues/11210

The PDB spec is completely immutable.  If PDB works well in upgrades, I believe the consensus is the spec values should be hard-coded and not configurable.

**Comment by smawson** [comment]
Has this been manually tested and verified? If so can we move to P1 and leave the P1 for getting this into the upgrade test?

**Comment by sdake** [comment]
@smawson I've manually verified the PDB spec is immutable.  There is kubernetes issue https://github.com/kubernetes/kubernetes/issues/45398 on the topic with no action for 20 months.  I have not manually verified if the PDB improves the state of unavailability during an upgrade.  I don't know whether @linsun gave that a go.

In general, one additional check would be a test for immutability.  One implementation would be to deploy a standard manifest, then modify each value one by one upgrading along the way to test for the capability to configure values that are configurable in values.yaml.  No other test would need to be done - just that kubectl apply applies the manifest without error.  This still is no guarantee that operators won't hand modify the templates (reference last Env WG meeting).

Could you be more specific on the desired check?

Cheers
-steve

**Comment by linsun** [comment]
I will modify our upgrade test to test 1+ replicas for each control plane so this feature can be properly explored in our upgrade test.

**Comment by linsun** [comment]
the desired check imho would be whether this improves the non 200 response code ratio for the test app during istio control and data plane upgrade.

**Comment by sdake** [comment]
@linsun I thought this has merged.  If so, can you close?

Cheers
-steve

**Comment by sdake** [comment]
(accidentally clicked wrong button, reopened - but I'll leave you to it)

**Comment by duderino** [comment]
@linsun anything left to do here?

**Comment by linsun** [comment]
Sorry for the slow reply, yes, okay to close as all changes are merged.
