### ISSUE TITLE
Deleting the Gateway does not delete the ELB

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#9954]
**Describe the bug**
I am deploying Istio 1.0.3 on EKS(AWS)
I used the Bookinfo as shown here https://istio.io/docs/examples/bookinfo/
and ran the 
`kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)`
and then created the Gateway 
`kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`

Everything came up fine and i was able to test various scenarios. Then i deleted everything using 
`samples/bookinfo/platform/kube/cleanup.sh`

After a week i tried to redeploy the application following the same steps and i noticed it had never deleted the ELB.  I got back the ELB which i had used 1 week before when eveything worked. 
I cleanup again and manually deleted the ELB and again tried redeploying everything and i saw i get the same ELB(ELB doesnt exist since i had now deleted it) Looks like it gets the info from DB which seems to have cached the ELB. I even renamed the Gateway but still sends me same ELB

**Expected behavior**
deleting Gateway should delete the ELB. 
kubectl get svc -n istio-system
gave me 
`NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)                                                                                                                   AGE
grafana                  ClusterIP      10.100.28.178    <none>             3000/TCP                                                                                                                  6d
istio-citadel            ClusterIP      10.100.152.48    <none>             8060/TCP,9093/TCP                                                                                                         6d
istio-egressgateway      ClusterIP      10.100.202.0     <none>             80/TCP,443/TCP                                                                                                            6d
istio-galley             ClusterIP      10.100.232.69    <none>             443/TCP,9093/TCP                                                                                                          6d
**istio-ingressgateway     LoadBalancer**   10.100.24.212    a57277916e2bf...   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32609/TCP,8060:30190/TCP,853:30377/TCP,15030:30483/TCP,15031:30407/TCP   6d
istio-pilot              ClusterIP      10.100.3.155     <none>             15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     6d
istio-policy             ClusterIP      10.100.107.7     <none>             9091/TCP,15004/TCP,9093/TCP                                                                                               6d
istio-sidecar-injector   ClusterIP      10.100.206.248   <none>             443/TCP                                                                                                                   6d
istio-telemetry          ClusterIP      10.100.106.154   <none>             9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     6d
prometheus               ClusterIP      10.100.215.159   <none>             9090/TCP                                                                                                                  6d`

Notice the "istio-ingressgateway     LoadBalancer" still exists
**Steps to reproduce the bug**
Mentioned above

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
Istio version-->>
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

K8s version -->>
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Helm install 

**Environment**
EKS

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by ymesika** [comment]
The ELB you are referring to is the Istio Ingressgateway and it is installed with Istio.
When you run the `cleanup.sh` of Bookinfo it only deletes resources related to the Bookinfo and doesn't remove Istio. That's why the ELB is still around. You need to remove Istio too to completely clean up.
