### ISSUE TITLE
1.1 Pilot memory and cpu regression

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#9961]
The two snapshots below show the same configuration and workloads running on 1.1-pre and 1.0.4-pre clusters.

At 300 active connections in both cases, 1.1-pre is using more goroutines, cpu and memory.

1.0.4 https://snapshot.raintank.io/dashboard/snapshot/sAVoeBv98auA0V5lfLNUo2D89gpnFV9y
1.1 https://snapshot.raintank.io/dashboard/snapshot/KvgVBadMUtTlPSwU5NAMAjItuLv37Gd7

**Comment by Nino-K** [comment]
We do have a PR in flight related to this. https://github.com/istio/istio/pull/10475

**Comment by jasminejaksic** [comment]
PR merged, closing the issue

**Comment by duderino** [comment]
I'd like @mandarjog and mitch connors to say that 1.1 Pilot memory and cpu usage is acceptable, then we can close this

**Comment by mandarjog** [comment]
1.1 snapshot [performance](https://snapshot.raintank.io/dashboard/snapshot/sfmS6AmUIGdz12RRXq6ymHis03YDl0AB?orgId=2)

**Comment by duderino** [comment]
@mandarjog I think you are saying 'no, pilot memory and cpu usage is *not* acceptable'.   Looks like 1.1 memory and cpu efficiency is still much worse than 1.0

**Comment by munrodg** [comment]
Fixed
