### ISSUE TITLE
istio.io/istio/pilot/pkg/proxy/envoy/v2 TestAdsClusterUpdate is flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#9968]
Example of flake:
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/9965/istio-unit-tests/16725#istioioistiopilotpkgproxyenvoyv2-testadsclusterupdate

The owner is discovered using git blame. 

/assign @Nino-K

**Comment by duderino** [comment]
@Nino-K can you work on this?  if not, please unassign yourself and add the 'community/help wanted' label

**Comment by duderino** [comment]
No response from @Nino-K so asking for someone else to pick this up.

**Comment by irisdingbj** [comment]
In failure cases, new test starts to run before s.grpcServer.GracefulStop() completes. 
below is printed in the new test: 
Push finished: 662.904µs {
    "ProxyStatus": {
        "pilot_destrule_subsets": {
            "c-weighted.extsvc.com": {
                "message": "Duplicate subset v2 found while merging destination rules for c-weighted.extsvc.com"
            }
        },
        "pilot_eds_no_instances": {
            "outbound|80||adsupdate2.default.svc.cluster.local": {}
        }
    },
    "Start": "2018-11-14T19:40:25.419434268Z",
    "End": "2018-11-14T19:40:25.420023636Z",
    "AuthzPolicies": null
}

**Comment by irisdingbj** [comment]
THis has been fixed now. no occurrence any more.
