### ISSUE TITLE
istio.io/istio/pkg/kube/secretcontroller Test_SecretController is flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#9980]
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/9970/istio-unit-tests/16769

/assign @rcurran1

**Comment by duderino** [comment]
@rcurran1 can you work on this?  if not, please unassign yourself and add the 'community/help wanted' label

**Comment by rcurran1** [comment]
@duderino - Unfortunately, I won't be able to work on this issue. Someone else in my group may take it over it time permits. I'll unassign. One possible way to fix is similar to what was done for a mixer test for accessing the secret controller; https://github.com/istio/istio/pull/8536/files#diff-173fd746907fbbed803ceaa79e43a1f6R423 in the creation of the verifyControllers() function.

With this change you eliminate for static sleep() call with a call the sleeps until an event occurs. 
I think the new function would look like this:
func verifyControllerDeleted(t *testing.T, timeoutName string) {
     pkgtest.NewEventualOpts(10*time.Millisecond, 5*time.Second).Eventually(t, timeoutName, func() bool {
     testDeleteControllerCalled != true
})
}
Call flow in test would change to:
err = deleteMultiClusterSecret(clientset)
if err != nil {
     t.Fatalf("Unexpected error   on secret delete: %v", err)
}
// Test - Verify that the remote controller has been removed. 
verifyControllerDeleted(t, "delete remote secret controller")
// Remove the current test that checks for 'create' call.

Not sure if there have been any intermediate failed tests on the create portion. If yes, then you can update/rename the verifyControllerDeleted() function to deal w/ both create/delete calls (probably just by creating additional passed in variables).

**Comment by sdake** [comment]
@kyessenov @duderino appears that @john-a-joyce has resolved this - just needs a review.

Cheers
-steve
