### ISSUE TITLE
Istio 1.0.3 version, sidecar can't be injected in statefulset

### ISSUE THREAD

**Issue by li1191863273** [istio/istio#9982]
**Describe the bug**

When I use the isti 1.0.3 version, deploying with deploy is normal, using statefulset deployment fails, the following exception occurs

	create Pod nginx-0 in StatefulSet nginx failed error: Pod "nginx-0" is invalid: spec.containers[1].env[8].name: Invalid value: "ISTIO_META_statefulset.kubernetes.io/pod-name": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name', or 'MY_ENV.NAME', or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')

**Version**
k8s

	Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

istio

	1.0.3

**Comment by mabushey** [comment]
I believe this change in istio.yaml will fix that specific problem:
```
-        [[ if .ObjectMeta.Labels ]]
-        - name: ISTIO_METAJSON_LABELS
-          value: |
-                 [[ toJson .ObjectMeta.Labels ]]
+        [[ range $k,$v := .ObjectMeta.Labels ]]
+        - name: ISTIO_META_[[ $k ]]
+          value: "[[ $v ]]"
```

However the containers will still not internally route to each other in 1.0.3, at least when they are all in a custom namespace.

**Comment by FaKod** [comment]
Same here for Prometheus Operator

creating a Pod fails because Pod has the annotation:
 
`statefulset.kubernetes.io/pod-name:  "prometheus-kube-prometheus-0"`      

Obviously ISTIO_META_statefulset.kubernetes.io/pod-name is not a valid ENV name.

So, what can I do with (defined in ConfigMap istio-sidecar-injector):

```yaml
[[ range $k,$v := .ObjectMeta.Labels ]]
    - name: ISTIO_META_[[ $k ]]
      value: "[[ $v ]]"
    [[ end ]]
```

to add a check or to create a valid ENV name?

**Comment by douglas-reid** [comment]
@mandarjog Can you provide comments here?

**Comment by FaKod** [comment]
should be fixed in 1.0.4 (see #9634)

**Comment by rafik8** [comment]
Hi, Upgrading to 1.0.4 and be able to have my MariaDB broken deployment (in 1.0.3 )working.

**Comment by esnible** [comment]
This may be a duplicate of #9571
