### ISSUE TITLE
Duplicate B3 tracing headers

### ISSUE THREAD

**Issue by objectiser** [istio/istio#9985]
**Describe the bug**
Envoy recently added support for the B3 single header, which resulted in the existing B3 headers being duplicated with different values: https://github.com/envoyproxy/envoy/issues/5017

This bug seems to be included in the Envoy versions currently being used in master and release-1.1 branches.

The fix https://github.com/envoyproxy/envoy/pull/5019 has been merged in Envoy.

**Expected behavior**
B3 headers should not be duplicated.

cc @douglas-reid

**Comment by objectiser** [comment]
This should be resolved in master when https://github.com/istio/istio/pull/9915 is merged.

**Comment by adriancole** [comment]
#9915 was merged a while back. does this mean this can be closed?

**Comment by objectiser** [comment]
Confirmed that both master and release-1.1 branch now includes envoy proxy with fix.
