### ISSUE TITLE
restore fortio automated daily runs

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#9988]
https://fortio-daily.istio.io/?s=master
has last data from July 2017

the 4 scenarios described in https://istio.io/docs/concepts/performance-and-scalability/#testing-scenarios and that have been running continuously from the 0.2 to the 0.7 releases should continue to be run (or why not?)

**Comment by ldemailly** [comment]
ping, can you explain what is the hold up/issue ?

**Comment by ldemailly** [comment]
happy new year... and... ping ? can you give any update at all on what's going on here?

**Comment by ewolff** [comment]
@hklai Are those performance tests somewhere on Github?

**Comment by hklai** [comment]
@mandarjog I suppose the plan is to replace them with some new perf test suite.

**Comment by ldemailly** [comment]
because?

**Comment by ldemailly** [comment]
ping

**Comment by huang195** [comment]
Is there any plans to have this re-enabled again to see latency numbers over time? I understand there have been a lot of changes that could impact the numbers, and it won't always be an apple-to-apple comparison, but at least it will show how latency changes under the _default_ configuration over time.
