### ISSUE TITLE
Bouncing mixer causes 503s on Istio 1.0.3

### ISSUE THREAD

**Issue by theganyo** [istio/istio#9992]
**Describe the bug**
After restarting a policy mixer, client calls can fail with a 503 error:

HTTP/1.1 503 Service Unavailable
content-length: 69
content-type: text/plain
date: Thu, 15 Nov 2018 23:29:44 GMT
server: envoy
x-envoy-upstream-service-time: 1016
UNAVAILABLE:upstream connect error or disconnect/reset before headers

**Expected behavior**
All curl commands to complete successfully once policy mixer has restarted.

**Steps to reproduce the bug**
1. Install default Istio 1.0.3 (install/kubernetes/istio-demo.yaml).
2. Install helloworld sample (samples/helloworld/helloworld.yaml).
3. Verify curls to /helloworld are successful.
4. Delete mixer policy pod and allow it to restart.
5. Curl commands will inconsistently succeed or fail with error above.

**Version**
Istio 1.0.3

**Installation**
install/kubernetes/istio-demo.yaml

**Environment**
Docker for Mac, GKE

**Comment by kyessenov** [comment]
This is likely due to some delays in propagating new mixer endpoint. The fail close scenario is by design, and can be turned off if needed.

It would help us to report how long it takes for envoy to pick up the new mixer endpoint (perhaps, observe mixer cluster stats for refreshes).

**Comment by theganyo** [comment]
I filed this issue 20 minutes ago and just tried again now. Still getting errors.

**Comment by kyessenov** [comment]
That's no good. Can you provide cluster dump?

**Comment by theganyo** [comment]
I tried, but the dump failed - see below. (This should be very easily reproducible, though.)

```
➜  istio-1.0.3 curl https://raw.githubusercontent.com/istio/istio/release-1.0/tools/dump_kubernetes.sh | sh -s -- -z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7837  100  7837    0     0  25884      0 --:--:-- --:--:-- --:--:-- 25864
Fetching debug/configz from pilot
Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7121    0  7121    0     0   402k      0 --:--:-- --:--:-- --:--:--  434k
Fetching debug/endpointz from pilot
Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58410    0 58410    0     0  4030k      0 --:--:-- --:--:-- --:--:-- 4387k
Fetching debug/adsz from pilot
Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1034  100  1034    0     0   110k      0 --:--:-- --:--:-- --:--:--  126k
Fetching metrics from pilot
Unable to use a TTY - input is not a terminal or the right kind of file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15825  100 15825    0     0   859k      0 --:--:-- --:--:-- --:--:--  909k
Retrieving kubernetes resource configurations
Retrieving istio resource configurations
Retrieving logs for copy_core_dumps_if_istio_proxy//
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
error: resource name may not be empty
sh: line 108: [: : integer expression expected
Wrote ./istio-dump.tar.gz
Wrote to istio-dump
sh: line 283: return: tap_containers: numeric argument required
```

**Comment by kyessenov** [comment]
cc @ostromart @mandarjog for the dump tool.

**Comment by kyessenov** [comment]
OK, can you perhaps extract logs from mixer pod (both mixs and the proxy). Maybe we can find some signal about what's going on? Describing the mixer pod with kubectl would also help.

**Comment by kyessenov** [comment]
I'm unable to reproduce this on 1.1.
Here's what I did:
1. install 1.1 tip, deploy it and the helloworld sample.
2. delete istio-policy HPA
3. run a continuous load: `while true; do curl $INGRESS/hello; done`
4. edit istio-policy deployment and scale down to 0.
5. observe gradual degradation (no healthy upstream):
```
Hello version: v1, instance: helloworld-v1-b69bbbd8c-chrtq
curl: (7) Failed to connect to 35.230.28.202 port 80: Connection refused
Hello version: v1, instance: helloworld-v1-b69bbbd8c-chrtq
Hello version: v2, instance: helloworld-v2-5c4fddc5f6-84vth
Hello version: v2, instance: helloworld-v2-5c4fddc5f6-84vth
curl: (7) Failed to connect to 35.230.28.202 port 80: Connection refused
curl: (7) Failed to connect to 35.230.28.202 port 80: Connection refused
Hello version: v2, instance: helloworld-v2-5c4fddc5f6-84vth
Hello version: v1, instance: helloworld-v1-b69bbbd8c-chrtq
UNAVAILABLE:no healthy upstreamUNAVAILABLE:no healthy upstreamUNAVAILABLE:no healthy upstreamUNAVAILABLE:no healthy upstreamUNAVAILABLE:no healthy upstreamUNAVAILABLE:no healthy upstreamHello version: v2, instance: helloworld-v2-5c4fddc5f6-84vth
Hello version: v1, instance: helloworld-v1-b69bbbd8c-chrtq
Hello version: v1, instance: helloworld-v1-b69bbbd8c-chrtq
UNAVAILABLE:no healthy upstreamHello version: v2, instance: helloworld-v2-5c4fddc5f6-84vth
```
6. scale up istio-policy to 1 replica.
7. observe a hanging request (envoy seemingly blocking the request trying to connect to policy).
8. observe healthy upstream from now on.

**Comment by karthikt-yahoo** [comment]
it is reproducible in istio-1.3 
Steps to reproduce:
   1. kubectl edit cm istio -n istio-system
         update the setting to policyCheckFailOpen: true
              # policyCheckFailOpen allows traffic in cases when the mixer policy service cannot be 
                  reached.
              # Default is false which means the traffic is denied when the client is unable to connect to Mixer.

   2. Edit istio-policy deployment and scale down to 0.

Now any request going through ingressgateway failes with 503.

**Comment by kyessenov** [comment]
@karthikt-yahoo I think this might be a different issue. Your example suggests that FailOpen is not being respected. The original issue was that 503s go away after mixer is killed/restarted.

**Comment by karthikt-yahoo** [comment]
@kyessenov Thanks for checking. I take back. i am not able to reproduce the issue i reported and the problem reported in this issue.

**Comment by duderino** [comment]
A fix to retry failed policy/quota checks on transport error made it into 1.1RC0 with retries set to 0 by default.  As we get experience with it we may default retries to 1+ and we may do this in a 1.1.x release.

Example from @howardjohn to enable it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
      annotations:
        policy.istio.io/checkRetries: "2"
        policy.istio.io/checkBaseRetryWaitTime: 80ms
        policy.istio.io/checkMaxRetryWaitTime: 1000ms
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        ports:
        - containerPort: 80
```

**Comment by gotwarlost** [comment]
We introduced automatic retries to all proxy sidecars using the sidecar injection config map and this made all transient errors due to blips in adapter deployment go away. This has been  a very useful feature for us.
