### ISSUE TITLE
Issues with istio-release-1.1-20181115-09-15

### ISSUE THREAD

**Issue by mabushey** [istio/istio#9993]
I like the premise of istio, I wish someone could release a working version. After 3 months of working with it I'm about to give up. The docs and the quality control is about the worst I've ever seen, especially for a project this big. I love how the ingress/routing works, if it could only do it w/o corrupting packets.

#1 - chart/subcharts is still messed up - you have to run `cp -r istio-release-1.1-20181115-09-15/install/kubernetes/helm/subcharts istio-release-1.1-20181115-09-15/install/kubernetes/helm/istio/chart` to get around this issue.

#2 - `helm template istio-release-1.1-20181115-09-15/install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true  --set grafana.security.enabled=true  --set grafana.security.adminUser=admin --set grafana.security.adminPassword=pass --set tracing.enabled=true > istio.yaml`
Error: found in requirements.yaml, but missing in charts/ directory: istio-cni

I commented out istio-cni from the `requirements.yaml` file.

`helm install --namespace wordpress --name my --set serviceType=ClusterIP,persistence.storageClass=rook-ceph-block,persistence.existingClaim=my-wordpress  stable/wordpress`

#3 Broke... Fixed it via this: https://github.com/istio/old_issues_repo/issues/316 - added 
    `runAsUser: 0` to `securityContext:` in `istio.yaml`

run helm install again for wordpress....
```
$ helm install --namespace wordpress --name my --set serviceType=ClusterIP,persistence.storageClass=rook-ceph-block,persistence.existingClaim=my-wordpress  stable/wordpress
NAME:   my
E1115 23:43:29.155220   26790 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:34939->127.0.0.1:55222: write tcp4 127.0.0.1:34939->127.0.0.1:55222: write: broken pipe
```

Looks the like the statefulset `/` name bug is finally fixed, mariadb actually comes up now (but fails and restarts again and again)... Wordpress fails :
```
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at my-mariadb:3306
mysql-c ERROR [canConnect] Connection with 'bn_wordpress' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_wordpress' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_wordpress' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_wordpress' user is unsuccessful
```

**Comment by harpratap** [comment]
Facing the same problems with installing 1.1 snapshots. You can try 1.0.x versions which seem to install fine.

**Comment by mabushey** [comment]
I went back to 1.0.2, it's the last version that still allows communication between containers.

**Comment by esnible** [comment]
Issue https://github.com/istio/istio/issues/10716 may cover the same issue; problems communicating with MySQL.
