### ISSUE TITLE
Is it possible to only run gateway and ingress?

### ISSUE THREAD

**Issue by mabushey** [istio/istio#9995]
Istio Ingress is awesome, but it's the only part of Istio that I can make work. Is it possible to run only the gateway and ingress portion of Istio? Linkerd2 looks like it can handle the rest. I've seen some docs on this, but they are a year old and I doubt they have much in common with Istio Ingress now.

**Comment by linsun** [comment]
Yes, that is possible, I think you also need pilot to push config to the gateway.  BTW, istio ingress is deprecated now.

**Comment by mabushey** [comment]
@linsun Thanks for the response. :) I believe the `istio ingress` being deprecated is the old system, and the new system is the Gateway / VirtualService routing rules, correct? Gateway / VirtualService is what I'm using now and it is absolutely awesome.

**Comment by linsun** [comment]
@mabushey yes, that is correct.  Gateway / VirtualService replaces the old ingress and routing rules.
