### ISSUE TITLE
Error from server (InternalError): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.254.176.80:443: connect: connection timed out

### ISSUE THREAD

**Issue by Linuxbody** [istio/istio#9998]
**Describe the bug**
{{ Succinctly describe the bug }}

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by hzxuzhonghu** [comment]
@Linuxbody Can you check your  galley service by 
 `kubectl get svc -n istio-system`

**Comment by Linuxbody** [comment]
kubectl get svc,endpoints -n istio-system|grep ga
service/istio-egressgateway      NodePort    10.254.158.174   <none>        80:31435/TCP,443:32910/TCP                                                                                                3d
service/istio-galley             ClusterIP   10.254.129.150   <none>        443/TCP,9093/TCP                                                                                                          3d
service/istio-ingressgateway     NodePort    10.254.226.196   <none>        80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:43906/TCP,8060:32826/TCP,853:37592/TCP,15030:40785/TCP,15031:44695/TCP   3d

endpoints/istio-egressgateway      192.168.169.168:80,192.168.169.168:443                                        3d
endpoints/istio-galley             192.168.169.167:9093,192.168.169.167:443                                      3d
endpoints/istio-ingressgateway     192.168.169.148:80,192.168.169.148:15030,192.168.169.148:15011 + 5 more...    3d

**Comment by hzxuzhonghu** [comment]
Check if your galley service accessible?

**Comment by Linuxbody** [comment]
@hzxuzhonghu 
 logs:

kubectl -n istio-system logs -f istio-galley-58f566cb66-556db 
  warn    istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no subsets
2018-11-20T14:06:20.187377Z     warn    istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no subsets
2018-11-20T14:06:25.184009Z     warn    istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no subsets

**Comment by Linuxbody** [comment]
[root@k8s-master1 istio-1.0.3]# kubectl -n istio-system get po,svc
NAME                                         READY     STATUS      RESTARTS   AGE
pod/grafana-59b787b9b-55rk9                  1/1       Running     0          8m
pod/istio-citadel-78df8c67d9-qkj94           1/1       Running     0          8m
pod/istio-cleanup-secrets-bg477              0/1       Completed   0          8m
pod/istio-egressgateway-6b96cd7f5-pkd7f      1/1       Running     0          8m
pod/istio-galley-58f566cb66-556db            1/1       Running     0          8m
pod/istio-grafana-post-install-7tcgg         0/1       Completed   0          8m
pod/istio-ingressgateway-6cbbf596f6-zfdcj    1/1       Running     0          8m
pod/istio-pilot-76474d9d49-tm4vq             2/2       Running     0          8m
pod/istio-policy-6b99d88bc5-fmfg5            2/2       Running     0          8m
pod/istio-security-post-install-64f9h        0/1       Completed   0          8m
pod/istio-sidecar-injector-b88dfb954-whlq4   1/1       Running     0          8m
pod/istio-telemetry-675cb4cb9d-8xmb6         2/2       Running     0          8m
pod/istio-tracing-7596597bd7-pcsqr           1/1       Running     0          8m
pod/prometheus-76db5fddd5-7x72x              1/1       Running     0          8m
pod/servicegraph-fc55fc579-vcd47             1/1       Running     0          8m

NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                   AGE
service/grafana                  ClusterIP      10.254.28.187    <none>        3000/TCP                                                                                                                  8m
service/istio-citadel            ClusterIP      10.254.46.17     <none>        8060/TCP,9093/TCP                                                                                                         8m
service/istio-egressgateway      ClusterIP      10.254.18.155    <none>        80/TCP,443/TCP                                                                                                            8m
service/istio-galley             ClusterIP      10.254.173.220   <none>        443/TCP,9093/TCP                                                                                                          8m
service/istio-ingressgateway     LoadBalancer   10.254.47.132    <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:34019/TCP,8060:40045/TCP,853:34557/TCP,15030:30001/TCP,15031:38852/TCP   8m
service/istio-pilot              ClusterIP      10.254.9.95      <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     8m
service/istio-policy             ClusterIP      10.254.140.193   <none>        9091/TCP,15004/TCP,9093/TCP                                                                                               8m
service/istio-sidecar-injector   ClusterIP      10.254.212.72    <none>        443/TCP                                                                                                                   8m
service/istio-telemetry          ClusterIP      10.254.203.18    <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     8m
service/jaeger-agent             ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                8m
service/jaeger-collector         ClusterIP      10.254.74.131    <none>        14267/TCP,14268/TCP                                                                                                       8m
service/jaeger-query             ClusterIP      10.254.177.16    <none>        16686/TCP                                                                                                                 8m
service/prometheus               ClusterIP      10.254.1.58      <none>        9090/TCP                                                                                                                  8m
service/servicegraph             ClusterIP      10.254.152.121   <none>        8088/TCP                                                                                                                  8m
service/tracing                  ClusterIP      10.254.211.213   <none>        80/TCP                                                                                                                    8m
service/zipkin                   ClusterIP      10.254.35.254    <none>        9411/TCP                                                                                                                  8m[root@k8s-master1 istio-1.0.3]# kubectl -n istio-system get po,svc
NAME                                         READY     STATUS      RESTARTS   AGE
pod/grafana-59b787b9b-55rk9                  1/1       Running     0          8m
pod/istio-citadel-78df8c67d9-qkj94           1/1       Running     0          8m
pod/istio-cleanup-secrets-bg477              0/1       Completed   0          8m
pod/istio-egressgateway-6b96cd7f5-pkd7f      1/1       Running     0          8m
pod/istio-galley-58f566cb66-556db            1/1       Running     0          8m
pod/istio-grafana-post-install-7tcgg         0/1       Completed   0          8m
pod/istio-ingressgateway-6cbbf596f6-zfdcj    1/1       Running     0          8m
pod/istio-pilot-76474d9d49-tm4vq             2/2       Running     0          8m
pod/istio-policy-6b99d88bc5-fmfg5            2/2       Running     0          8m
pod/istio-security-post-install-64f9h        0/1       Completed   0          8m
pod/istio-sidecar-injector-b88dfb954-whlq4   1/1       Running     0          8m
pod/istio-telemetry-675cb4cb9d-8xmb6         2/2       Running     0          8m
pod/istio-tracing-7596597bd7-pcsqr           1/1       Running     0          8m
pod/prometheus-76db5fddd5-7x72x              1/1       Running     0          8m
pod/servicegraph-fc55fc579-vcd47             1/1       Running     0          8m

NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                   AGE
service/grafana                  ClusterIP      10.254.28.187    <none>        3000/TCP                                                                                                                  8m
service/istio-citadel            ClusterIP      10.254.46.17     <none>        8060/TCP,9093/TCP                                                                                                         8m
service/istio-egressgateway      ClusterIP      10.254.18.155    <none>        80/TCP,443/TCP                                                                                                            8m
service/istio-galley             ClusterIP      10.254.173.220   <none>        443/TCP,9093/TCP                                                                                                          8m
service/istio-ingressgateway     LoadBalancer   10.254.47.132    <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:34019/TCP,8060:40045/TCP,853:34557/TCP,15030:30001/TCP,15031:38852/TCP   8m
service/istio-pilot              ClusterIP      10.254.9.95      <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     8m
service/istio-policy             ClusterIP      10.254.140.193   <none>        9091/TCP,15004/TCP,9093/TCP                                                                                               8m
service/istio-sidecar-injector   ClusterIP      10.254.212.72    <none>        443/TCP                                                                                                                   8m
service/istio-telemetry          ClusterIP      10.254.203.18    <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     8m
service/jaeger-agent             ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                8m
service/jaeger-collector         ClusterIP      10.254.74.131    <none>        14267/TCP,14268/TCP                                                                                                       8m
service/jaeger-query             ClusterIP      10.254.177.16    <none>        16686/TCP                                                                                                                 8m
service/prometheus               ClusterIP      10.254.1.58      <none>        9090/TCP                                                                                                                  8m
service/servicegraph             ClusterIP      10.254.152.121   <none>        8088/TCP                                                                                                                  8m
service/tracing                  ClusterIP      10.254.211.213   <none>        80/TCP                                                                                                                    8m
service/zipkin                   ClusterIP      10.254.35.254    <none>        9411/TCP                                                                                                                  8m

**Comment by Linuxbody** [comment]
![image](https://user-images.githubusercontent.com/9931457/48779241-21f99880-ed12-11e8-9295-ed32c00979c0.png)

**Comment by ayj** [comment]
Could you try deleting the `istio-galley` validatingwebhookconfiguration and seeing what happens? Galley doesn't create the configuration until the endpoint is ready. 

That said, even if a previous configuration was leftover, the logs below show that despite the endpoint being ready (via kubectl get), the logs showing the endpoint is not ready. I'm not sure what to make of that.

> 2018-11-20T14:06:25.184009Z warn istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no subsets

> kubectl get svc,endpoints -n istio-system|grep galley
> endpoints/istio-galley 192.168.169.167:9093,192.168.169.167:443 3d

What k8s provider / distribution are you using?

**Comment by hzxuzhonghu** [comment]
>2018-11-20T14:06:20.187377Z warn istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no subsets

This is the cause.

**Comment by ayj** [comment]
https://github.com/istio/istio/issues/9998#issuecomment-440146973 shows a istio-galley endpoint with address 192.168.169.167:443. It's not clear if that was was captured at roughly the same time or not as the logs, or if there is a transient endpoint readiness issue.

**Comment by hzxuzhonghu** [comment]
Notice that, weird

**Comment by hzxuzhonghu** [comment]
Check this: 
`kubectl get ep -n istio-system istio-galley -oyaml`

**Comment by Linuxbody** [comment]
[root@k8s-master1 ~]# kubectl get ep -n istio-system istio-galley -oyaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-11-20T14:05:56Z
  labels:
    istio: galley
  name: istio-galley
  namespace: istio-system
  resourceVersion: "1804656"
  selfLink: /api/v1/namespaces/istio-system/endpoints/istio-galley
  uid: 664f02a7-eccd-11e8-8c32-000c29f04163
subsets:
- addresses:
  - ip: 192.168.36.95
    nodeName: k8s-node1
    targetRef:
      kind: Pod
      name: istio-galley-58f566cb66-556db
      namespace: istio-system
      resourceVersion: "1706974"
      uid: 66642f61-eccd-11e8-8c32-000c29f04163
  ports:
  - name: http-monitoring
    port: 9093
    protocol: TCP
  - name: https-validation
    port: 443
    protocol: TCP

**Comment by Linuxbody** [comment]
> [＃9998（注释）](https://github.com/istio/istio/issues/9998#issuecomment-440146973)显示了一个地址为192.168.169.167:443的istio-galley端点。目前尚不清楚是否与日志大致同时捕获，或者是否存在暂时的端点准备问题。
@ayj 
Self-built kubernetes, version 1.11.3 ;
After removing istio-galley, the same error

[root@k8s-master1 ~]# kubectl -n istio-system delete pod istio-galley-58f566cb66-556db
pod "istio-galley-58f566cb66-556db" deleted
[root@k8s-master1 ~]# kubectl -n istio-system get pod
NAME                                     READY     STATUS      RESTARTS   AGE
grafana-59b787b9b-55rk9                  1/1       Running     0          18h
istio-citadel-78df8c67d9-qkj94           1/1       Running     0          18h
istio-cleanup-secrets-bg477              0/1       Completed   0          18h
istio-egressgateway-6b96cd7f5-pkd7f      1/1       Running     0          18h
istio-galley-58f566cb66-2kt8r            1/1       Running     0          8s
istio-grafana-post-install-7tcgg         0/1       Completed   0          18h
istio-ingressgateway-6cbbf596f6-zfdcj    1/1       Running     0          18h
istio-pilot-76474d9d49-tm4vq             2/2       Running     0          18h
istio-policy-6b99d88bc5-fmfg5            2/2       Running     0          18h
istio-security-post-install-64f9h        0/1       Completed   0          18h
istio-sidecar-injector-b88dfb954-whlq4   1/1       Running     0          18h
istio-telemetry-675cb4cb9d-8xmb6         2/2       Running     0          18h
istio-tracing-7596597bd7-pcsqr           1/1       Running     0          18h
prometheus-76db5fddd5-7x72x              1/1       Running     0          18h
servicegraph-fc55fc579-vcd47             1/1       Running     0          18h
[root@k8s-master1 ~]# kubectl -n istio-system logs -f istio-galley-58f566cb66-2kt8r
2018-11-21T08:14:16.931343Z     info    server-side configuration validation enabled
2018-11-21T08:14:21.933690Z     info    istio-galley validatingwebhookconfiguration (re)loaded: 
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    app: istio-galley
    chart: galley-1.0.3
    heritage: Tiller
    release: istio
  name: istio-galley
  namespace: istio-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: istio-galley
    uid: 66a930d8-eccd-11e8-869d-000c2967d19f
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lSQUxXRHZodjZLeWd6V25QcTVZVCtibnd3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQ2hNUmF6aHpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NVGd4TVRJd01UUXdOakF6V2hjTgpNVGt4TVRJd01UUXdOakF6V2pBY01Sb3dHQVlEVlFRS0V4RnJPSE11WTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMd05HZGRHM3psTWJ3NlNkQUVXOUw5VnlxUU0KbVBjZUVVK2FZL3lZS3ZnVnFVMGVHaWl2bkIzb05tbFpUUDRhZU1mOTdCWjUwRTFIeWxTeE82L21rY2YycWVvcwp0b0d6TkV3VktoTC9oY3JXV2d1L0cwNWg5SCtTSlJQcThIRVNKNTV4K0NvSXBoNzlKZm12NVoyTE1Zc0ZSaC95CkNaZVNOREx6N2E1K0lud2Z4VEVoRjllWUIwdVVpWjlrRmZXUUt6dW50d2NUN1g0OWxYUng3eTQ3ZzBkQ0FtdlgKYXNqUDl1bkpSLzFVVDArRWkwQmtPWFM0NUg1NXl6NkpiZUZva2ViVEljdTd6Zk1yL3NtaXhjenNlMXFsSDQwSwpYYjcyTUhuRnlCcmpNK2VyckduMWVxY3ZzS2FsUDQzQnozN3c3R014bExha0ZXdU1IV2JSRVNQSXVNTUNBd0VBCkFhTWpNQ0V3RGdZRFZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUhlV3pWUmJYZ1owTVdleG5GQ2tZRjREY0RuOWlFck5kWDNEZXlwR1BYLy9JcG1VaXhIVgp4K0tpN2plbjAydUR2VzAwS05PcE1Wdk5FRjBNMkdrbElCRUI1RHFuYkc2MktoUng1NXdtREd4TVVyM3ZsaDVxCjJpUnBIYmltSFlEZlhaQ1ptNXNmVGJBMFNZazdVeS9HRDVEVFdGaDZlZTVZNDFYVG1IS2k1TFVEMW1COFVmaVgKWHBDT01MNWpibm1hZ08yTXdDcGlCN29CQy9yOEVNY3BqUHJjNnU1WWVhTWFiU1JrREhNZ25IUldwNzFLdDdWMApwM1VhS0NjYzFtekROTkpRWmpQTW1VZk1nQWgvcHJMRzlBdG5KbzBiQnZSK1F3TnViZDdldU92b2x6NytRanNjCk43YWYzS2p2clM2V1YwUkFvZGJvcnd2Si9rbDlPcnJYdlBJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-galley
      namespace: istio-system
      path: /admitpilot
  failurePolicy: Fail
  name: pilot.validation.istio.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - config.istio.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpapispecs
    - httpapispecbindings
    - quotaspecs
    - quotaspecbindings
  - apiGroups:
    - rbac.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  - apiGroups:
    - authentication.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
  - apiGroups:
    - networking.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - destinationrules
    - envoyfilters
    - gateways
    - serviceentries
    - virtualservices
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lSQUxXRHZodjZLeWd6V25QcTVZVCtibnd3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQ2hNUmF6aHpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NVGd4TVRJd01UUXdOakF6V2hjTgpNVGt4TVRJd01UUXdOakF6V2pBY01Sb3dHQVlEVlFRS0V4RnJPSE11WTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMd05HZGRHM3psTWJ3NlNkQUVXOUw5VnlxUU0KbVBjZUVVK2FZL3lZS3ZnVnFVMGVHaWl2bkIzb05tbFpUUDRhZU1mOTdCWjUwRTFIeWxTeE82L21rY2YycWVvcwp0b0d6TkV3VktoTC9oY3JXV2d1L0cwNWg5SCtTSlJQcThIRVNKNTV4K0NvSXBoNzlKZm12NVoyTE1Zc0ZSaC95CkNaZVNOREx6N2E1K0lud2Z4VEVoRjllWUIwdVVpWjlrRmZXUUt6dW50d2NUN1g0OWxYUng3eTQ3ZzBkQ0FtdlgKYXNqUDl1bkpSLzFVVDArRWkwQmtPWFM0NUg1NXl6NkpiZUZva2ViVEljdTd6Zk1yL3NtaXhjenNlMXFsSDQwSwpYYjcyTUhuRnlCcmpNK2VyckduMWVxY3ZzS2FsUDQzQnozN3c3R014bExha0ZXdU1IV2JSRVNQSXVNTUNBd0VBCkFhTWpNQ0V3RGdZRFZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUhlV3pWUmJYZ1owTVdleG5GQ2tZRjREY0RuOWlFck5kWDNEZXlwR1BYLy9JcG1VaXhIVgp4K0tpN2plbjAydUR2VzAwS05PcE1Wdk5FRjBNMkdrbElCRUI1RHFuYkc2MktoUng1NXdtREd4TVVyM3ZsaDVxCjJpUnBIYmltSFlEZlhaQ1ptNXNmVGJBMFNZazdVeS9HRDVEVFdGaDZlZTVZNDFYVG1IS2k1TFVEMW1COFVmaVgKWHBDT01MNWpibm1hZ08yTXdDcGlCN29CQy9yOEVNY3BqUHJjNnU1WWVhTWFiU1JrREhNZ25IUldwNzFLdDdWMApwM1VhS0NjYzFtekROTkpRWmpQTW1VZk1nQWgvcHJMRzlBdG5KbzBiQnZSK1F3TnViZDdldU92b2x6NytRanNjCk43YWYzS2p2clM2V1YwUkFvZGJvcnd2Si9rbDlPcnJYdlBJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-galley
      namespace: istio-system
      path: /admitmixer
  failurePolicy: Fail
  name: mixer.validation.istio.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - config.istio.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - rules
    - attributemanifests
    - circonuses
    - deniers
    - fluentds
    - kubernetesenvs
    - listcheckers
    - memquotas
    - noops
    - opas
    - prometheuses
    - rbacs
    - servicecontrols
    - solarwindses
    - stackdrivers
    - cloudwatches
    - dogstatsds
    - statsds
    - stdios
    - apikeys
    - authorizations
    - checknothings
    - listentries
    - logentries
    - metrics
    - quotas
    - reportnothings
    - servicecontrolreports
    - tracespans

2018-11-21T08:14:21.936806Z     warn    istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no ready addresses

**Comment by ayj** [comment]
Can you check the endpoint _after_ you delete the pod and the new pod is running again? Also, can you check the logs after you verify that the new pod/endpoint are up and running? Can you also do `kubectl -n istio-system describe pod <istio-galley-pod-name>` after the new pod is created to see if the readiness probe is intermediately failing?

**Comment by Linuxbody** [comment]
@ayj 
[root@k8s-master1 ~]# kubectl -n istio-system describe pod istio-galley-58f566cb66-2kt8r 
Name:               istio-galley-58f566cb66-2kt8r
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               k8s-node1/10.117.150.34
Start Time:         Wed, 21 Nov 2018 16:14:16 +0800
Labels:             istio=galley
                    pod-template-hash=1491227622
Annotations:        scheduler.alpha.kubernetes.io/critical-pod=
                    sidecar.istio.io/inject=false
Status:             Running
IP:                 192.168.36.110
Controlled By:      ReplicaSet/istio-galley-58f566cb66
Containers:
  validator:
    Container ID:  docker://a1c3171a094ed17095d633c818dc697ec69af4962cbf690315c6e875865ea757
    Image:         docker.io/istio/galley:1.0.3
    Image ID:      docker-pullable://istio/galley@sha256:cffec029bf2a1b16a3bd2aa1a1c309f5fd5c686e89edbcabcebea6ff1c737ed0
    Ports:         443/TCP, 9093/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /usr/local/bin/galley
      validator
      --deployment-namespace=istio-system
      --caCertFile=/etc/istio/certs/root-cert.pem
      --tlsCertFile=/etc/istio/certs/cert-chain.pem
      --tlsKeyFile=/etc/istio/certs/key.pem
      --healthCheckInterval=1s
      --healthCheckFile=/health
      --webhook-config-file
      /etc/istio/config/validatingwebhookconfiguration.yaml
    State:          Running
      Started:      Wed, 21 Nov 2018 16:14:16 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        10m
    Liveness:     exec [/usr/local/bin/galley probe --probe-path=/health --interval=10s] delay=5s timeout=1s period=5s #success=1 #failure=3
    Readiness:    exec [/usr/local/bin/galley probe --probe-path=/health --interval=10s] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/istio/certs from certs (ro)
      /etc/istio/config from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-galley-service-account-token-pr8vs (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-galley-service-account
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-galley-configuration
    Optional:  false
  istio-galley-service-account-token-pr8vs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-galley-service-account-token-pr8vs
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                Message
  ----    ------     ----  ----                -------
  Normal  Scheduled  17h   default-scheduler   Successfully assigned istio-system/istio-galley-58f566cb66-2kt8r to k8s-node1
  Normal  Pulled     17h   kubelet, k8s-node1  Container image "docker.io/istio/galley:1.0.3" already present on machine
  Normal  Created    17h   kubelet, k8s-node1  Created container
  Normal  Started    17h   kubelet, k8s-node1  Started container

**Comment by hzxuzhonghu** [comment]
Your format is so difficult to read.
